### ISSUE TITLE
无法加载Mod的版本，Mod管理中提示信息更改

### ISSUE THREAD

**Issue by ZJH-github34987233** [Hex-Dragon/PCL2#1001]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

将 "Forge 或 Fabric" 更改为 "Mod 加载器"

### 原因

Mod 加载器不止Forge和Fabric

**Comment by WForst-Breeze** [comment]
已提交 pr #1002

**Comment by WorldHim** [comment]
额，这个算是完成了吧。

**Comment by WorldHim** [comment]
额
