### ISSUE TITLE
为自定义下载支持自定义文件名

### ISSUE THREAD

**Issue by WorldHim** [Hex-Dragon/PCL2#1003]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

来自  @myunco 在 #889 中的[回复](https://github.com/Hex-Dragon/PCL2/issues/889#issuecomment-1401968023_)
> 既然自动获取名称不好实现，不如下载前允许手动指定文件名...

### 原因

便于下载前自定义文件名。

**Comment by LTCatt** [comment]
等 #889 给一个样例，修好了那个 Bug 我才方便加这个 =。=

**Comment by LTCatt** [comment]
![image](https://user-images.githubusercontent.com/40348278/214511851-7f13841b-b2ad-446d-91e0-25a8e7c01a05.png)
事实上你选一个路径深一点的文件夹谁都下不了。Windows 规定了最长的路径字符数，不是我能绕过的。
#980 里应该是出现了路径带 GET 参数的情况。

**Comment by WorldHim** [comment]
@LTCatt 在 release 中把这个功能归到 @myunco 上，谢谢。

**Comment by LTCatt** [comment]
收到（
