### ISSUE TITLE
支持自定义下载线程数

### ISSUE THREAD

**Issue by idhaname** [Hex-Dragon/PCL2#1004]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

受限于滑块条的最大数量，PCL2目前的下载线程设置最高只能设置到255
虽然可以通过更改注册表HKEY_USERS\S-1-5-21-3665154605-1687499917-1518635061-1001\Software\PCL\ToolDownloadThread的键值来达到更改下载线程数的目的，但更改注册表多多少少有点麻烦
而隔壁HMCL已经支持自定义下载线程，BakaXL已经支持2048线程的发射模式
更改建议：建议改成像HMCL那样在滑块条右边添加一个文本框
![BakaXL的发射模式](https://user-images.githubusercontent.com/68469786/214323499-433451cf-2415-4201-82bf-0e06c65749ad.png)
图1-BakaXL的发射模式
![HMCL的下载设置](https://user-images.githubusercontent.com/68469786/214323507-d1ed6237-ec50-4349-987f-b0b95a0bcd37.png)
图2-HMCL的下载设置

### 原因

这项优化让我可以更方便地更改下载线程数，以便取得良好的下载体验。
如果没有这项优化，我每次都必须通过注册表更改，让操作变得很麻烦。

**Comment by Big-Cake-jpg** [comment]
不建议过于追求线程数量，过多的线程数可能会造成严重的卡顿，一般情况下 256 / 512 线程足矣。感觉做的可能性比较低。

已初步确认，感谢你的反馈～

**Comment by LTCatt** [comment]
根据实际测试，到达 64 线程后，线程数对速度的提升已经非常有限。在 128 线程后，线程数已经不再是下载速度的瓶颈，继续增加线程反而会降低性能，但几乎没有收益（甚至收益为负），所以不再提供更高的线程数选项。
