### ISSUE TITLE
让启动器支持清理内存

### ISSUE THREAD

**Issue by idhaname** [Hex-Dragon/PCL2#1005]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

BakaXL已经支持强制释放内存，经本人实测，一次可以释放近1G的内存
希望PCL2也可以添加诸如此类的功能。
![QQ截图20230124225427](https://user-images.githubusercontent.com/68469786/214327744-f4c7d146-732f-4bfa-a35b-6ea7aded90ce.png)
图1-BakaXL的强制释放内存
原始discussion: #943 

### 原因

我需要这个功能来释放内存。很多人都有清理内存的需求，尤其是一些只有4G以下内存的渣机。

**Comment by Big-Cake-jpg** [comment]
内存清理的话，也许你可以尝试一下 Mem Reduct……？做的可能性不大。

已初步确认，感谢你的反馈～

**Comment by LTCatt** [comment]
我之前考虑过制作类似功能，但没有找到任何技术方案资料，加上 BakaXL 闭源，所以也不知道它是咋做的。
如果有可行的技术方案会考虑制作。

**Comment by LTCatt** [comment]
整会了，做完了
