### ISSUE TITLE
下载ATM8 1.0.9整合包出现问题，非网络问题，1.0.8正常

### ISSUE THREAD

**Issue by ScottCTD** [Hex-Dragon/PCL2#1006]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在下载All The Mods 8整合包1.0.9版本时，出现报错，弹出提示：
```
弹出提示：CurseForge 整合包安装：ATM8 1.0.9 失败：Unable to cast object of type 'Newtonsoft.Json.Linq.JValue' to type 'Newtonsoft.Json.Linq.JArray'. → 构造 Mod 下载信息失败 → 整合包安装失败
```

非网络原因，下载ATM8没有问题。

### 重现步骤

1、点击下载
2、下载ATM8 1.0.9版本
3、 出现错误

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10495443/Log3.txt)

Line 236 安装报错

Line 278 UI 报错

**Comment by WForst-Breeze** [comment]
稳定复现，已初步确认问题存在，感谢你的反馈~
![image](https://user-images.githubusercontent.com/110760354/214469628-89a2a837-93c6-468b-b747-d6ea7071fabc.png)

**Comment by LTCatt** [comment]
这是 CurseForge API 的 Bug，minecolonies-1.19.2-1.0.1200-BETA.jar 的信息中，modules 返回了 null，根据 API 规范这绝对不应当发生。
……怎么看都不应该是我去修的 Bug，麻了，只能加个临时补丁让它不报错了。

**Comment by Klosw** [comment]
> 这是CurseForge API的Bug，minecolonies-1.19.2-1.0.1200-BETA.jar的信息中，modules返回了null，根据API规范这绝不会对应不当发生。 ……怎么看都不应该我去修改Bug，麻了，只能加个临时补丁让它不报错了。

为啥使用 2.3.5的版本可以下载呀 ?
