### ISSUE TITLE
Optifine 版本选择应置顶最新正式版

### ISSUE THREAD

**Issue by zkitefly** [Hex-Dragon/PCL2#1007]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

像 Forge 选择版本那样，将最新版和稳定版置顶

![image](https://user-images.githubusercontent.com/64117916/214465559-6d01d609-188e-4855-884b-d777dc96ae16.png)

![image](https://user-images.githubusercontent.com/64117916/214465790-247b8f67-4cda-4295-b5f5-841bbc505264.png)

目前是这样的：

![image](https://user-images.githubusercontent.com/64117916/214467223-43b54476-9c20-4bc8-b270-93fb5347085e.png)

### 原因

听说 Optifine 的 Pre 版本特别不稳定，

应该筛选将最新稳定版置顶，

或许可以减少有小白选择 Pre 版本导致一系列的问题。

**Comment by WForst-Breeze** [comment]
已初步确认，感谢您的反馈~

**Comment by zkitefly** [comment]
这么快？！
