### ISSUE TITLE
添加“游戏结束后执行命令”

### ISSUE THREAD

**Issue by zkitefly** [Hex-Dragon/PCL2#1008]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

“游戏结束后执行命令”和“启动前执行命令”功能一致，区别是何时自行，

在 游戏进程结束后 执行指定的命令

### 原因

尽然有“启动前执行命令”，那为啥不来个“游戏结束后执行命令”呢QWQ

**Comment by LTCatt** [comment]
你打开游戏后把 PCL 关了这个就炸了。
到时候还得有人来找我说理……

**Comment by JingHai-Lingyun** [comment]
如果 PCL 能在有此项配置启动时被关闭留下一个无 UI 进程，直到退出后指令执行完毕再关闭呢？

**Comment by SALTWOOD** [comment]
干脆直接设置成与打开游戏后关闭PCL不兼容得了

**Comment by Silverteal** [comment]
管理额外进程是有开销的，到时候内存泄露了竞争死锁了什么的又麻烦
