### ISSUE TITLE
模组下载界面希望记住之前的进度

### ISSUE THREAD

**Issue by MC-1One** [Hex-Dragon/PCL2#1012]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

安装模组的时候经常遇到要下载前置模组,和主要模组,
切换到前置模组页面选择版本的时候,
之前的进度又要重新滑动才能回到之前的状态
比如下载一个旧版本比如游戏版本1.12.2的模组,需要滑动到下面,但是看到需要前置模组,于是点击前置模组界面,下载完前置模组后,返回下载主要模组,又要重新滑动到下面,希望可以记住之前进度,减少重复滑动.

### 原因

更好地安装当前游戏版本的模组
如果可以默认优先显示当前游戏版本的模组就更好啦

**Comment by WForst-Breeze** [comment]
原始反馈 #1011 已初步确认，感谢您的反馈~

**Comment by LTCatt** [comment]
在搜索时可以直接筛选对应版本，PCL 会将该版本的文件置顶。
