### ISSUE TITLE
使用jre17.0.6时错误的弹窗

### ISSUE THREAD

**Issue by ZHAOSBC** [Hex-Dragon/PCL2#1017]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

使用jre17.0.6启动游戏时弹窗，使用jdk17.0.6时正常（其他版本的jre17没有试过）
![image](https://user-images.githubusercontent.com/119199014/214858028-1a644f0c-beb3-4379-bdce-ad4972edb752.png)
![屏幕截图_20230126_220306](https://user-images.githubusercontent.com/119199014/214858207-9cc0af96-ba4f-4aaa-a5b3-21a899f1ce77.png)

### 重现步骤

1.手动指定jre17.0.6后启动游戏
2.当只有jre17.0.6时启动游戏

### 日志与附件

[自动选择时.txt](https://github.com/Hex-Dragon/PCL2/files/10510053/default.txt)
[手动指定时.txt](https://github.com/Hex-Dragon/PCL2/files/10510054/default.txt)

**Comment by youzi-2333** [comment]
JRE 17.0.2，没法复现
但是在爱发电看到好多人反映这个问题，应该是存在滴，先等别人回复吧……

**Comment by LTCatt** [comment]
为啥这么喜欢用高版本 JRE……

**Comment by ZHAOSBC** [comment]
我认为#799的题不是新版本jre导致的而是jre16独有的问题，这在forge的论坛上可以找到（链接：https://forums.minecraftforge.net/announcement/15-java-and-you-how-to-avoid-crashes/）
并且你测试出来问题的java除了JDK20和jre16其他的应该都可以称为上古版本（JDK20毕竟还没正式发布，有问题很正常）

**Comment by ZHAOSBC** [comment]
> 为啥这么喜欢用高版本 JRE......
我认为#799的题不是新版本jre导致的而是jre16独有的问题，这在forge的论坛上可以找到（链接：[https://forums.minecraftforge.net/announcement/15-java-and-you-how-to-avoid-crashes/] 并且你测试出来问题的java除了JDK20和jre16其他的应该都可以称为上古版本（JDK20毕竟还没正式发布，有问题很正常）

**Comment by ZHAOSBC** [comment]
> 

.

**Comment by ZHAOSBC** [comment]
解锁

**Comment by ZHAOSBC** [comment]
话说活跃橙能给吗(っ///c)
识别码：AEE9-B117-7F2F-5498

**Comment by LTCatt** [comment]
你的解锁码：JTb+teM63vlsvLPyqcigbuzDU5y1PSbK
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
