### ISSUE TITLE
优化快照版PCL反馈按钮

### ISSUE THREAD

**Issue by LTDove** [Hex-Dragon/PCL2#1018]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

支持点击"提交新反馈"时复制识别码和打开网址

### 原因

这项优化让我可以更方便地提交反馈
可以更方便快照版用户获取活跃橙(如果提前把识别码填好后 龙猫就可以直接发兑换码了.......而不用再次回复(

**Comment by WForst-Breeze** [comment]
已初步确认，感谢您的反馈~

**Comment by LTCatt** [comment]
没必要，在没有明确提示的情况下覆盖剪贴板也不是好事……
