### ISSUE TITLE
支持更新 Mod（手动选择要更新哪些）

### ISSUE THREAD

**Issue by LTCatt** [Hex-Dragon/PCL2#102]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

支持检查 Mod 的更新，并且在有更新的时候可以自行选择更新哪些，然后一键更新。

### 原因

整合包可能需要。

---

这是 #52 的后续讨论。

**Comment by shiyang0510** [comment]
MOD一键更新会处理在游戏中或多或少的奇怪bug（可能还能减少bug的反馈）

**Comment by MiracleBelief** [comment]
俺也觉得有必要，我还找了半天投票还想能不能自己添个这个投票来着。可惜我只会C#，对VB一窍不通，没法给龙猫帮上啥忙，只能到处找提议的地方。。。。

**Comment by allMagicNB** [comment]
不错，很期待 `2.6.16`
