### ISSUE TITLE
启动器最小化时窗口动画失效

### ISSUE THREAD

**Issue by ExpertPbSeal** [Hex-Dragon/PCL2#1020]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

任意情况下将启动器最小化，或在最小化情况下将启动器页面调出，均无动画效果。

### 重现步骤

打开启动器，窗口浮现动画正常；点击启动器最小化按钮，启动器页面直接消失而无退出动画播放。
*一般软件界面或系统页面在最小化或还原时会有缩放动画。
*怀疑是自造车轮的问题，与启动器内容实现无关。

### 日志与附件

不认为启动器日志会为本问题提供帮助。启动器各功能暂时运行正常。
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10510232/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10510235/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10510236/Log4.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10510240/Log1.txt)

**Comment by youzi-2333** [comment]
龙猫应该不会修，WPF 窗体最小化似乎只有这一种方法，先等回复.jpg

**Comment by LTCatt** [comment]
最小化动画被 Windows 接管，WPF 无法在自定义窗口模式下调用该动画
