### ISSUE TITLE
有考虑过"回声洞"像"你知道吗"一样自定义吗

### ISSUE THREAD

**Issue by LTDove** [Hex-Dragon/PCL2#1021]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

有考虑过"回声洞"像"你知道吗"一样自定义吗

### 原因

好像没啥用
只能为某些整合包作者有些用
可以为整合包弄些介绍啥的

**Comment by FangFuJi1991** [comment]
介绍的话可以写一个自定义主页 :-D

**Comment by youzi-2333** [comment]
回声洞是沙雕网友的投稿，并且快照版才能投，那么即使能够自定义也要用快照版，但是快照版不能做整合包……应该不会考虑（
