### ISSUE TITLE
刷新背景音乐 UI 失败导致的无法打开且只显示logo

### ISSUE THREAD

**Issue by Albedo-Favonius** [Hex-Dragon/PCL2#1025]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

[23:56:20.192] 刷新背景音乐 UI 失败：不包含文件名：
   在 PCL.ModBase.GetFileNameFromPath(String FilePath)
   在 PCL.ModBase.GetFileNameWithoutExtentionFromPath(String FilePath)
   在 PCL.ModMusic._Closure$__._Lambda$__5-0()
[23:56:20.228] [Control] 普通弹窗：出现错误
刷新背景音乐 UI 失败：不包含文件名：
   在 PCL.ModBase.GetFileNameFromPath(String FilePath)
   在 PCL.ModBase.GetFileNameWithoutExtentionFromPath(String FilePath)
   在 PCL.ModMusic._Closure$__._Lambda$__5-0()

是否反馈此问题？如果不反馈，这个问题可能永远无法得到解决！
[23:57:40.583] [System] 程序已退出，返回值：Success

背景音乐可以正常加载，但卡在登录logo（为什么我的GitHub啥也加载不出来啊，好卡）

### 重现步骤

1、点击xxxx
2、往下滚，然后点击xxxx
我也不知道，我只是打开了启动器，在打开启动器后我只下载了1.8.9的版本游玩，然后退出游戏并关闭了启动器，再次打开启动器就出现了bug，怎么触发不知道，但是这个bug一直存在，重启没有用

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10511099/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10511100/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10511101/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10511102/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10511103/Log2.txt)

**Comment by LTCatt** [comment]
你慢了， #1024
