### ISSUE TITLE
使用特定 Java 可能导致启动不成功

### ISSUE THREAD

**Issue by MC-luoluo** [Hex-Dragon/PCL2#1026]
### 检查项

- [ ] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃不是 PCL2 的原因，请 **不要** 提交反馈。你可以在 QQ 群里或者论坛找人求助，但这里并不是你求助的地方。
- [ ] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是游戏本身的问题，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

启动游戏时
Minecraft 出现错误
很抱歉，你的游戏出现了一些问题……
如果要寻求帮助，请向他人发送错误报告文件，而不是发送这个窗口的截图。
你也可以查看错误报告，其中可能会有出错的原因。

多次尝试无果将错误报告发给群友，群友说我用的badlion的Java（8.0.51），换成其他java（java11）就好了，希望修复java选择问题

### 错误报告、日志与附件

[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10511980/Log5.txt)
[错误报告-23-01-26_周四_20.04.22.zip](https://github.com/Hex-Dragon/PCL2/files/10511981/-23-01-26_._20.04.22.zip)

**Comment by MC-luoluo** [comment]
![image](https://user-images.githubusercontent.com/113677351/214910952-34d5530c-7f42-4b1b-9c5a-110a45affa10.png)

**Comment by LTCatt** [comment]
可以补发一下你用的那个 Java……传网盘
我没有 Badlion.jpg

**Comment by MC-luoluo** [comment]
为什么要从java上找原因...只识别C:\Program Files\Java里的java不行吗...

**Comment by MC-luoluo** [comment]
没网盘...OneDrive登不上...

**Comment by MC-luoluo** [comment]
https://1drv.ms/u/s!AuEcLrc_qmOLg8Vr0bDJSMTd_BKM6Q?e=HaGhTh

**Comment by MC-luoluo** [comment]
Onedrive企业版登不上，用个人版传的

**Comment by 00ll00** [comment]
我没能复现这个Bug😥，能否继续进行以下两个测试：

1. 在使用其他版本的Java成功运行后使用出错的Java能否成功运行；
2. 删除 C:\Users\15928\AppData\Roaming\PCL\ 目录下的 libwrapper.dll（若存在的话），并再次复现这个bug，检查此目录下是否有 libwrapper.dll 出现。

**Comment by MC-luoluo** [comment]
1的话直接就可以说，现在就是因为自己复现不了所以用的出BUG时的日志，现在不会出现这个问题了（可能是概率事件？）

**Comment by MC-luoluo** [comment]
因为再次尝试复现不了...所以只能说下当时的结果，当时（指用java11成功启动之前） libwrapper.dll 我删过一次，并且会再次出现

**Comment by MC-luoluo** [comment]
我的建议是PCL2可以优先使用C:\Program Files\Java里的java，如果这个目录找不到java再尝试去别的地方找

**Comment by 00ll00** [comment]
感谢答复🌹。现在复现不了的话只能暂时认为是概率事件，需要更多信息判断是否为Bug🐛。

Java优先级的特性需要龙猫回复。

**Comment by LTCatt** [comment]
暂时认定成小概率事件，如果之后收到同样原因的第二个错误报告再行处理……
至于 Java 优先级，PCL 会在把 Java 加进列表前对它进行测试，所以能进列表的 Java 应该不会有问题。至少在查明这次失败的原因前没有必要修改 =。=

**Comment by RawDiamondMC** [comment]
和#1108 是同一个bug...
所以这个怎么处理？ @LTCatt

**Comment by MC-luoluo** [comment]
我先3天反馈...

**Comment by WForst-Breeze** [comment]
> 和#1108 是同一个bug... 所以这个怎么处理？

已经处理完毕的问题不用太过于计较（）问题解决了即可😉

**Comment by MC-luoluo** [comment]
> > 和#1108 是同一个错误...所以这个怎么处理？
> 
> 已经处理完毕的问题不用太过于计较（）问题解决了即可😉

确实....但是活跃橙？

**Comment by WForst-Breeze** [comment]
> 确实....但是活跃橙？

hmmm，若您需要，可以在下方留言并说明情况，我觉得是会给的

**Comment by RawDiamondMC** [comment]
> 我先3天反馈...

正常，见#479 与#535

**Comment by MC-luoluo** [comment]
> > 我先3天反馈...
> 
> 正常，见#[479](https://github.com/Hex-Dragon/PCL2/issues/479) 与#535

哦..还是有些不同的...我反馈的是游戏崩溃，与1.18+的java要求没有关系，可能是特定java版本不兼容mod或者游戏本体

**Comment by MC-luoluo** [comment]
> > > 我先3天反馈...
> > 
> > 
> > 正常，见#[479](https://github.com/Hex-Dragon/PCL2/issues/479) 与#535
> 
> 哦..还是有些不同的...我反馈的是游戏崩溃，与1.18+的java要求没有关系，可能是特定java版本不兼容mod或者游戏本体

当然也有可能是万能的小概率事件（

**Comment by RawDiamondMC** [comment]
> > > 我先3天反馈...
> > 
> > 
> > 正常，见#[479](https://github.com/Hex-Dragon/PCL2/issues/479) 与#535
> 
> 哦..还是有些不同的...我反馈的是游戏崩溃，与1.18+的java要求没有关系，可能是特定java版本不兼容mod或者游戏本体

但是是同一个bug导致的，从libwrapper.dll: Can't find dependent libraries两边都有这一点就能看出来
