### ISSUE TITLE
对于JAVA虚拟机错误的错误分析以及改进建议

### ISSUE THREAD

**Issue by duoduo70** [Hex-Dragon/PCL2#1031]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在我尝试测试DragonWell JDK的Wisp2功能时 输入了参数 -XX:+UseWisp2 （开启JVM的一个优化功能）
得到报错
![image](https://user-images.githubusercontent.com/81518666/215010608-1e1f4b80-6fb3-4677-b5d1-e123c4dc52c6.png)
实为：

Error: VM option 'UseWisp2' is experimental and must be enabled via -XX:+UnlockExperimentalVMOptions.

错误分析将其一概而论成了JAVA中文路径/JAVA损坏
格式 Error: VM option XXX 的报错信息的分析结果应为 “JVM 参数错误”
且将“由于”改为“可能是”
或将JAVA报错打印到启动器报错分析弹窗上

### 原因

这个修改相对简单，且不修改可能会产生误导

**Comment by youzi-2333** [comment]
~~感觉你是来卡Bug的~~已经确认，感谢您的反馈

**Comment by youzi-2333** [comment]
ok当我没说（），1.12.2成功复现，感谢反馈。
