### ISSUE TITLE
添加多种登录组合

### ISSUE THREAD

**Issue by turuihang** [Hex-Dragon/PCL2#1034]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

添加多种登录组合,如:正版登录+第三方登录

### 原因

方便启动游戏，提升PCL使用体验

**Comment by WForst-Breeze** [comment]
已初步确认，感谢您的反馈~
（注：反馈者貌似指的是 **版本设置-设置-服务器-登录方式**

**Comment by turuihang** [comment]
> 已初步确认，感谢您的反馈~ （注：反馈者貌似指的是 **版本设置-设置-服务器-登录方式**

抱歉，我说的不够清楚，的确是 **版本设置-设置-服务器-登录方式** ，麻烦了

**Comment by LBZiXL** [comment]
@turuihang 感觉和我的 https://github.com/Hex-Dragon/PCL2/discussions/350 好像是一个意思......

**Comment by WorldHim** [comment]
与 #350 重复（效果一致，在 `版本设置-设置-服务器-登录方式` 的更改会作用到主页上），谢谢您的反馈

**Comment by WorldHim** [comment]
这bot不太机灵的样子。。。

**Comment by WForst-Breeze** [comment]
> 与 #350 重复（效果一致，在 `版本设置-设置-服务器-登录方式` 的更改会作用到主页上），可以视作 #350 的补充，谢谢您的反馈。 ~话说主页显示的登录方式和 `服务器` 有什么关系？~

个人理解，反馈者的意思**并非是添加第三方登录至主页**，而是指在 版本设置-设置-服务器-登录方式 中添加自定义登录方式的组合功能（举个栗子，就是把那块做成类似于多选勾选框而非现在的下拉框）以实现**类似于**在启动页显示 正版+离线+第三方 或 正版+第三方 或 离线+第三方 **等**的组合形式
~虽然大概率会被拒绝~

**Comment by LBZiXL** [comment]
> > 与 #350 重复（效果一致，在 `版本设置-设置-服务器-登录方式` 的更改会作用到主页上），可以视作 #350 的补充，谢谢您的反馈。 ~话说主页显示的登录方式和 `服务器` 有什么关系？~
> 
> 个人理解，反馈者的意思**并非是添加第三方登录至主页**，而是指在 版本设置-设置-服务器-登录方式 中添加自定义登录方式的组合功能（举个栗子，就是把那块做成类似于多选勾选框而非现在的下拉框）以实现**类似于**在启动页显示 正版+离线+第三方 或 正版+第三方 或 离线+第三方 **等**的组合形式。 ~虽然大概率会被拒绝，而且的确等 #350 做完了这个优化用处也就不大了，所以 reopen 的意义……貌似也不太大，只是想说明一下（qwq~

对呀，我写 https://github.com/Hex-Dragon/PCL2/discussions/350 也是想实现你说的这个效果呀。
