### ISSUE TITLE
删除版本或mod时的优化

### ISSUE THREAD

**Issue by zfn-star** [Hex-Dragon/PCL2#1038]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

删除版本时可以按住shift直接删除，而不用删除到回收站

### 原因

这项优化让我可以更方便地删除版本。
如果没有这项优化，我每次都必须清空回收站，让操作变得很麻烦。

**Comment by quannen** [comment]
这倒是的，感觉可以加一个选择框让用户选择一下

**Comment by LBZiXL** [comment]
@zfn-star 你的意思应该是按shift再点删除按钮然后永久删除（不到回收站）吧？

**Comment by WForst-Breeze** [comment]
> 你的意思应该是按shift再点删除按钮然后永久删除（不到回收站）吧？

是的，反馈者就是这个意思（

**Comment by 212112111zwl** [comment]
同意，这样就不需要到回收站再操作一遍了
