### ISSUE TITLE
清理游戏垃圾按钮错误

### ISSUE THREAD

**Issue by fhh1224** [Hex-Dragon/PCL2#1040]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

点击清理游戏垃圾后弹窗中取消会导致按钮变灰

### 重现步骤

1、点击清理游戏垃圾
2、点取消
3、清理游戏垃圾按钮变灰

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10518484/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10518486/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10518487/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10518488/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10518489/Log5.txt)

**Comment by WForst-Breeze** [comment]
稳定复现，已初步确认问题存在，请等待开发者进一步回复，感谢您的反馈~
![image](https://user-images.githubusercontent.com/110760354/215080023-feeb0886-472d-4256-a49e-d9503433d9ce.png)

**Comment by fhh1224** [comment]
这变灰是连续清3次才应该出现的吧

**Comment by fhh1224** [comment]
……评论自动关？？

**Comment by bwtx2023** [comment]
> ……评论自动关？？

你点的是 close with comment

**Comment by 212112111zwl** [comment]
> 这变灰是连续清3次才应该出现的吧

我一次取消它就灰了

**Comment by fhh1224** [comment]
解锁活跃橙主题

**Comment by WorldHim** [comment]
> 解锁活跃橙主题

请提供识别码

**Comment by fhh1224** [comment]
85CD-2E4D-A478-94D0

**Comment by LTCatt** [comment]
你的解锁码：DWauzk9kthfVSb6iHzfRlK0mly9ESrb8
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by fhh1224** [comment]
D77C-32C2-F52C-5E8B

**Comment by LTCatt** [comment]
你的解锁码：ijEbGvivVmh5yFRjqYbyhm0QR6n/zBR1
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
