### ISSUE TITLE
PCL无权访问图片或音乐文件夹时会一直卡在启动界面

### ISSUE THREAD

**Issue by YangkoStudio** [Hex-Dragon/PCL2#1048]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

PCL无权访问PCL/Pictures（Musics）文件夹时，一直卡在启动界面，并且不会弹出提示

### 重现步骤

1、将Pictures或Musics文件夹设置为禁止访问
2、打开PCL2

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10524275/Log1.txt)

**Comment by youzi-2333** [comment]
稳定复现，感谢您的反馈。

**Comment by LTCatt** [comment]
PCL 会在启动时确认有对 PCL 文件夹的访问权限，因此非刻意触发的情况下，不可能出现能访问 PCL 文件夹但不能访问其中的子文件夹的情况。
因此，这是一个只在刻意构造的环境下触发的 Bug，在正常使用条件下没有触发可能，所以不作修复。
