### ISSUE TITLE
mod管理中点击“全部启用”或者”全部禁用“时给出确认菜单避免误点

### ISSUE THREAD

**Issue by IF-desu** [Hex-Dragon/PCL2#1052]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

%如题%
确认菜单里面有取消和确定（

### 原因

作为一个整合包作者，做自用端或者整合包时候经常添加mod，也会经常禁用掉旧版本mod和冲突的mod，有时候误点到全部启用和全部禁用就挺绝望的。还得一个一个开
普通玩家也许也需要:)

**Comment by WorldHim** [comment]
难说。虽然要改不是很麻烦，但是貌似对普通玩家不怎么有用。

**Comment by IF-desu** [comment]
> 难说。虽然要改不是很麻烦，但是貌似对普通玩家不怎么有用。

lol，谁的mods里面没几个disabled的冲突mod呢

**Comment by IF-desu** [comment]
> 难说。虽然要改不是很麻烦，但是貌似对普通玩家不怎么有用。

而且不只是冲突的mod，许多人下载下了整合包或者自己配自用端会禁用一些不想用的mod

**Comment by LTCatt** [comment]
不应对非严重破坏性的操作添加二次提示。这样做的收益比增加一步操作的损失小。

**Comment by IF-desu** [comment]
寄

**Comment by youzi-2333** [comment]
那或许能考虑一下，mod 数量很多（例如大于 50 个）的时候再进行提示（？）
