### ISSUE TITLE
版本分类不正确

### ISSUE THREAD

**Issue by RawDiamondMC** [Hex-Dragon/PCL2#1054]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在没有其他1.19.2Optifine版本时，1.19.2-Optifine-H1和1.19.2-Optifine-H1-pre4都被归到不常用版本。

### 重现步骤

1、下载1.19.2 Optifine H1 pre4（这个版本在Optifine官网被移除）
2、下载1.19.2 Optifine H1
3、两个版本都被归到不常用版本

### 日志与附件

![屏幕截图 2023-01-28 120259](https://user-images.githubusercontent.com/112449001/215241218-6f0dce4a-2fc6-4f36-8a88-bf8a3d37efd4.png)

**Comment by youzi-2333** [comment]
我复现出来是 I1-pre4 被归到不常用，I1 归到常规版本（？）
先等别人测试吧，你这个情况可能是装了 1.19.2 的 Forge 或 Fabric 版本，导致原版被折叠

**Comment by WForst-Breeze** [comment]
经测试，当文件夹中同时存在 1.19.3 optifine 和 1.19.2 optifine 时， PCL2 会选择 折叠后者，鉴于这可能是刻意的设计，故调整为 **优化建议** ，感谢您的反馈~

**Comment by RawDiamondMC** [comment]
> 经测试，当文件夹中同时存在 1.19.3 optifine 和 1.19.2 optifine 时， PCL2 会选择 折叠后者，鉴于这可能是刻意的设计，故调整为 **优化建议** ，感谢您的反馈~ ![image](https://user-images.githubusercontent.com/110760354/215247240-6517f4bc-2b3e-408a-a3f4-c79a1936f6d4.png)

~草，原来是因为1.19.3的Optifine~

**Comment by LTCatt** [comment]
因为存在同样大版本下更新的小版本的 OptiFine。WAI。
