### ISSUE TITLE
mcbbs某些整合包用不了

### ISSUE THREAD

**Issue by chentianyou1** [Hex-Dragon/PCL2#1059]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

下载后mod文件中mod无法识别

### 重现步骤

1、点击版本选择
2、然后点击导入整合包
3、然后导入tales of silent整合包
4、然后导入完tales of silent整合包
5、然后点击版本设置
6、然后点击Mod管理
最后bug出现

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10527431/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10527432/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10527433/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10527434/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10527435/Log2.txt)

**Comment by WForst-Breeze** [comment]
请补充整合包文件及相关截图，谢谢！

**Comment by LTCatt** [comment]
超时关闭，如果看到了可以继续回复
