### ISSUE TITLE
有反作弊无法获取Minecraft窗口时PCL展示报错

### ISSUE THREAD

**Issue by 150149** [Hex-Dragon/PCL2#1062]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃不是 PCL2 的原因，请 **不要** 提交反馈。你可以在 QQ 群里或者论坛找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是游戏本身的问题，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

有反作弊无法获取Minecraft窗口时PCL展示报错
提示

出现错误：
检查Minecraft窗口失败，拒绝访问

### 错误报告、日志与附件

[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10529267/Log5.txt)
![_B_83`276R3H`TF8FPY%U)Q](https://user-images.githubusercontent.com/32214195/215311970-d00e9e42-9434-43c2-b4b4-7ba4806b69c0.png)

**Comment by youzi-2333** [comment]
1.12.2 使用 [禁止作弊](https://www.mcmod.cn/class/3770.html) mod 无法复现，请补充 mod 或数据包文件。

**Comment by 150149** [comment]
![image](https://user-images.githubusercontent.com/32214195/215314170-2b73b53a-dd1e-4dca-8c57-59f27e77a26e.png)
文件不方便提供暂时，新版反作弊还没有做好，不管反作弊是如何实现保护进程的，对于非游戏进程，反作弊都将不允许其访问游戏进程，并且PCL并没有数字签名，反作弊也无法判断启动器是否合法

**Comment by youzi-2333** [comment]
~~我觉得你应该交到 Mod 开发者那边~~那就先看龙猫咋办吧，如果可以的话就搞个数字签名，如果不行也没辙了……

**Comment by LTCatt** [comment]
没有文件无法复现的话我也不好修复，如果多久能提供文件了可以继续在下面回复

**Comment by 150149** [comment]
我可以提供反作弊文件，能否使用QQ发送，文件较大，我的QQ是1802796278

**Comment by LTCatt** [comment]
我直接加个容错处理吧……
