### ISSUE TITLE
新版本离线模式启动设置的皮肤失效

### ISSUE THREAD

**Issue by Sean1110** [Hex-Dragon/PCL2#1063]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

启动23w04a后，发现世界内的皮肤不是我设置的皮肤（我确定是启动器的最新版本，正式版2.4.7）

### 重现步骤

1、启动PCL2
2、点击头像，更换离线模式的皮肤
3、启动23w04a
4、进入世界，发现皮肤不是我设置的

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10529272/Log3.txt)

**Comment by WForst-Breeze** [comment]
稳定复现，已初步确认问题存在，感谢您的反馈~
![image](https://user-images.githubusercontent.com/110760354/215313458-59636b2d-2eb9-4e40-a10f-693d124d4268.png)

**Comment by Sean1110** [comment]
好像是这个引起的
![image](https://user-images.githubusercontent.com/122132148/215313575-5802b0e8-f9eb-4764-96e1-d22a291c0d66.png)
这是我在MCwiki上看到的关于23w03a的更新介绍
[https://minecraft.fandom.com/zh/wiki/23w03a](url)
