### ISSUE TITLE
优化 清理游戏垃圾 按钮的位置

### ISSUE THREAD

**Issue by FangFuJi1991** [Hex-Dragon/PCL2#1064]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

可以将 **清理游戏垃圾** 添加至 **版本选择** 与 **版本设置** 里，以方便清理 **单独** 的版本和 **全部** 版本，并删除旧位置。

### 原因

可以更方便的清除游戏垃圾，还可以指定清除单独的版本和全部版本。
:-)

**Comment by quannen** [comment]
旧位置删除没必要吧

**Comment by FangFuJi1991** [comment]
> 旧位置删除没必要吧

留下做彩蛋（？

**Comment by LTCatt** [comment]
没有必要单独删除一个版本的垃圾……
