### ISSUE TITLE
增加其他jvm的下载支持

### ISSUE THREAD

**Issue by tanzihongweb** [Hex-Dragon/PCL2#1069]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [x] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [x] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

有一些机型对甲骨文版的java的运行速度不是太好
建议增加比如 Open J9 ,Open JRE 和 IBM JRE等高性能的jre下载
这样可以让更多想玩Minecraft的人能够流畅玩耍
增加一个java版本自选(java8,11,16分开)
(根本来说就是 Open J9 下太慢了)

### 原因

我需要这个功能来流畅玩耍。很多人都有不同的需求，但如果没有这个功能，就不能让更多想玩Minecraft的人流畅玩耍了了。

**Comment by youzi-2333** [comment]
已经确认，感谢您的反馈~

~~但是工程量有点大，龙猫可能不会加.jpg~~

**Comment by bwtx2023** [comment]
就目前来看龙猫更加倾向于使用 Mojang 提供的 Java...

**Comment by WTP016-CN** [comment]
根据 #99 #104 的讨论，OpenJDK 等非官方 JDK 暂时是不予考虑的……
由于使用 OpenJDK 不一定会有官方的 Oracle JDK 稳定性好（
我也先处理了，等龙猫解决吧（

**Comment by WorldHim** [comment]
PCL 可能不会支持，你可以手动下载 Zulu 等优化较好的 Java 使用。
