### ISSUE TITLE
资源下载页面的版本筛选框为空时添加标识而不是空白

### ISSUE THREAD

**Issue by ZHAOSBC** [Hex-Dragon/PCL2#1074]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

1.在选择的mod版本与所选游戏版本不相符时让玩家手动选择安装的游戏版本而不是自动选择
2.搜索时选择游戏版本的地方全部版本添加标识而不是空白
![image](https://user-images.githubusercontent.com/119199014/215392219-4f0937de-d983-4225-97da-ba712eb8cd3b.png)

### 原因

1.启动器自动选择的游戏版本大部分时候都不正确，玩家一不注意就会把mod下载的到错误的游戏里
2.会导致玩家找不到全部版本分类并且不美观

**Comment by WTP016-CN** [comment]
1. PCL2 的 Mod 下载时并非自动选择，而是选择你在版本选择内选择的版本
2. 可行

**Comment by ZHAOSBC** [comment]
> 1. PCL2 的 Mod 下载时并非自动选择，而是选择你在版本选择内选择的版本
> 2. 可行

在版本选择内选择的版本与mod对应的版本相符时确实是这样，但是在版本选择内选择的版本与mod对应的版本不相符时（比如你版本选择内选择的是1.18但mod选择的是1.19）PCL会自动在游戏文件夹内寻找合适的版本（并且只会在启动器右下角有一个一闪而过的提示），当游戏文件夹内有多个合适的版本可能会导致选择错误

**Comment by ZHAOSBC** [comment]
1.的图附上
![image](https://user-images.githubusercontent.com/119199014/215398703-a3e1ceae-7a99-48ba-9584-88dbbc04f95d.png)

**Comment by LTCatt** [comment]
第一条算了，这个真的很难做，要大改版本选择页面，但收益相对太小了
第二条可以弄弄 =。=

**Comment by 212112111zwl** [comment]
> 第一条算了，这个真的很难做，要大改版本选择页面，但收益相对太小了

把它做成一个弹窗，就不用大改了，添加一个界面就好了（吧

**Comment by z0z0r4** [comment]
> > 第一条算了，这个真的很难做，要大改版本选择页面，但收益相对太小了
> 
> 把它做成一个弹窗，就不用大改了，添加一个界面就好了（吧

这里的大改指的是工作量很高…添加新界面不能减少工作量…

**Comment by 212112111zwl** [comment]
> > > 第一条算了，这个真的很难做，要大改版本选择页面，但收益相对太小了
> > 
> > 
> > 把它做成一个弹窗，就不用大改了，添加一个界面就好了（吧
> 
> 这里的大改指的是工作量很高…添加新界面不能减少工作量…

的确需要大改，我的意思是，不用大改 _选择界面_ 添加一个弹窗就好了，不是指工作量不大
