### ISSUE TITLE
使用文件资源管理器修改游戏文件夹导致的bug

### ISSUE THREAD

**Issue by ZHAOSBC** [Hex-Dragon/PCL2#1076]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

PCL运行时使用文件资源管理器修改游戏文件夹后在版本选择内刷新文件夹后PCL会按照原路径创建新文件夹
（如果修改后再启动PCL则会提示文件无效并从列表内移除）

### 重现步骤

1.确保PCL正在运行
2.用文件资源管理器修改游戏文件夹（如改名，移动，删除）
3.在版本选择内刷新游戏文件夹

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10532991/Log1.txt)

**Comment by youzi-2333** [comment]
刻意卡出的 Bug 龙猫不会修。资源管理器重命名文件夹会导致 Json 文件与文件夹名称不匹配，导致找不到 Json，请在版本设置中重命名。

**Comment by ZHAOSBC** [comment]
> 刻意卡出的 Bug 龙猫不会修。资源管理器重命名文件夹会导致 Json 文件与文件夹名称不匹配，导致找不到 Json，请在版本设置中重命名。

但是PCL会按照原路径自动创建一个新文件夹，而不是提示文件夹无效，不仅是改名，移动和删除也会（

**Comment by LTCatt** [comment]
刻意卡出的 Bug 不修

**Comment by youzi-2333** [comment]
您所说的情况我无法复现……找不到 Json 文件应该就是直接归为错误的版本，而且 Log 里面也看不出端倪（
