### ISSUE TITLE
游戏窗口自定义大小错误

### ISSUE THREAD

**Issue by Somnia1337** [Hex-Dragon/PCL2#1077]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

自定义游戏窗口大小为1920\*1080，但是启动后实际为1918\*1041，上一个PCL2版本中没有此问题

### 重现步骤

启动游戏，窗口大小与自定义的大小不符

### 日志与附件

[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10533160/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10533161/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10533162/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10533163/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10533164/Log4.txt)

**Comment by LTCatt** [comment]
这个数值没法完全精确，因为不同系统环境下窗口标题栏和边框的大小不一致……所以大致是对的就行了 Orz

**Comment by TheWithCommands** [comment]
如果这样的话，对于直播来说每次需要手动拖动窗口大小，这就不行了。
所以，应以F3显示的大小为准，而不是实际窗口大小。

按照这里所说，那么长减去2，宽减去39，于是就1918x1041了。

**Comment by dsb987** [comment]
和https://github.com/Hex-Dragon/PCL2/issues/1077差不多，但也有https://github.com/Hex-Dragon/PCL2/issues/3463的部分内容与补充。
重要的是，这里给出了旧的PCL2（v2.3.2版本），曾经并没有这个bug，然而现在却有了。。。说明代码确实出了问题。。。
