### ISSUE TITLE
添加已有 Minecraft 文件夹时，允许游戏目录使用相对路径

### ISSUE THREAD

**Issue by WForst-Breeze** [Hex-Dragon/PCL2#1080]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

如题，在添加已有 Minecraft 文件夹时，允许游戏目录使用相对路径。此功能或许可以参考 [HMCL](https://github.com/huanghongxun/HMCL)
![image](https://user-images.githubusercontent.com/110760354/215440505-6e0b11e6-29c3-4dc0-b271-58a9971ca290.png)

### 原因

部分玩家可能需要。

尽管很少有人会去更改游戏所在的文件夹的名字或是移动游戏文件夹，但是一旦进行相关更改后，又需要全部重新手动导入游戏文件夹，使得操作变得较为繁琐。

**Comment by youzi-2333** [comment]
要不先看看龙猫咋处理（？）

**Comment by LTCatt** [comment]
重新导入一下文件夹而已……这点收益相对复杂度增加还是算了……
