### ISSUE TITLE
错误的允许OptiFine HD U I2 pre1和OptiFine HD U I2 pre2与forge共存

### ISSUE THREAD

**Issue by ZHAOSBC** [Hex-Dragon/PCL2#1086]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

（这个问题会应该随着新版本的optifine的发布而解决，但我觉得有必要反馈一下）
在PCL自动安装功能中可以同时安装forge和OptiFine HD U I2 pre1、OptiFine HD U I2 pre2
![image](https://user-images.githubusercontent.com/119199014/215524695-ea8f9482-d6a4-4136-9c03-3d379eea246f.png)
![image](https://user-images.githubusercontent.com/119199014/215524724-26325f5c-22c5-46b4-a087-7cbbba2fcf83.png)
而optifine的官方文档明确写着这两个版本的optifine与forge不兼容，这应该会导致游戏崩溃
![屏幕截图_20230130_233256](https://user-images.githubusercontent.com/119199014/215526053-83ca7f82-9c10-499b-8d08-99736691082f.png)
![屏幕截图_20230130_233304](https://user-images.githubusercontent.com/119199014/215526081-93793850-3dc2-42d5-bb1c-d8d0a2321ebd.png)

### 重现步骤

1.在自动安装界面选择1.19.
2.可以同时选择forge和OptiFine HD U I2 pre1或OptiFine HD U I2 pre2

### 日志与附件

在同时安装forge与OptiFine HD U I2 pre1或OptiFine HD U I2 pre2启动游戏时的错误报告如下：
[错误报告pre1.zip](https://github.com/Hex-Dragon/PCL2/files/10537425/pre1.zip)
[错误报告pre2.zip](https://github.com/Hex-Dragon/PCL2/files/10537432/pre2.zip)

**Comment by ZHAOSBC** [comment]
纠正一下，游戏版本为1.19.3

**Comment by youzi-2333** [comment]
已复现，感谢您的反馈~

**Comment by ZHAOSBC** [comment]
活跃橙（之前的电脑系统被玩炸了T-T
识别码：B390-C267-78B1-4958

**Comment by LTCatt** [comment]
你的解锁码：kNuc0Hmx8XW5RE66KZmC8IEI+005NQEK
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
