### ISSUE TITLE
内存显示错误

### ISSUE THREAD

**Issue by yshuoyan** [Hex-Dragon/PCL2#1087]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃不是 PCL2 的原因，请 **不要** 提交反馈。你可以在 QQ 群里或者论坛找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是游戏本身的问题，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

内存提示不足，但是在pcl2里面显示还有5G左右的内存，进行游玩可以，但是会过一会崩溃

### 错误报告、日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10538011/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10538012/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10538013/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10538014/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10538015/Log5.txt)

**Comment by youzi-2333** [comment]
<details>
<summary>PCL2 日志</summary>
<code>[00:48:08.095] 崩溃分析失败：引发类型为“System.OutOfMemoryException”的异常。
你的电脑运行内存不足，导致 PCL2 无法继续运行。请在关闭一部分不需要的程序后再试。
————————————
详细错误信息：
   在 PCL.ModBase.Log(Exception Ex, String Desc, LogLevel Level, String Title)
   在 PCL.CrashAnalyzer.Collect(String VersionPathIndie, IList`1 LatestLog)
   在 PCL.ModWatcher.Watcher._Lambda$__32-0()
错误类型：System.OutOfMemoryException
[00:48:22.528] [System] 诊断信息：
操作系统：Microsoft Windows 11 专业版 Insider Preview
剩余内存：5152 M / 8109 M
DPI：96（100%）
MC 文件夹：E:\Minecraft\.minecraft\
文件位置：E:\Minecraft\PCL2\
[00:48:22.528] 程序出现未知错误：引发类型为“System.OutOfMemoryException”的异常。
你的电脑运行内存不足，导致 PCL2 无法继续运行。请在关闭一部分不需要的程序后再试。
————————————
详细错误信息：
   在 PCL.FormMain.FormMain_KeyDown(Object sender, KeyEventArgs e)
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   在 System.Windows.Input.InputManager.ProcessStagingArea()
   在 System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   在 System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   在 System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   在 System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   在 System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   在 System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
错误类型：System.OutOfMemoryException</code>
</details>
48 分 22 秒的诊断信息里面，内存是 5152 M / 8109 M，49 分 09 秒更是直接达到了 2463 M / 8109 M，为啥会内存不足呢……

或许确实是 PCL2 获取到的内存不对？那就先给龙猫看看吧.jpg，感谢您的反馈~

**Comment by bwtx2023** [comment]
看一看虚拟内存设置多少了...

**Comment by yshuoyan** [comment]
怎么看虚拟内存

**Comment by yshuoyan** [comment]
> 看一看虚拟内存设置多少了...

![屏幕截图 2023-01-31 082515](https://user-images.githubusercontent.com/121127756/215627125-6d30be9e-0d14-492a-a9e0-66117d259d11.png)

**Comment by WorldHim** [comment]
在 `Log1.txt` 的 627、628 行：
> 627 `[Render thread/ERROR] [mojang/GlDebug]: OpenGL API ERROR: 0 (Unknown internal debug message. The NVIDIA OpenGL driver has encountered`
> 628 `an out of memory error.`
671、712 行：
> 671 `[Render thread/ERROR] [mojang/GlDebug]: OpenGL API ERROR: 1285 (GL_OUT_OF_MEMORY error generated. Failed to allocate memory for buffer data.)`
> 712 `[Render thread/ERROR] [ne.op.sh.SMCLog/]: [Shaders] OpenGL error: 1285 (Out of memory), program: shadow, at: modelViewMatrix`
都报告了 OpenGL 错误，游戏崩溃前的错误即第 712 行报告 `Out of memory`。
貌似是你用了光影爆显存了，而 PCL 显示的是内存，试试不加光影？

**Comment by ZHAOSBC** [comment]
发现了几个问题：
1.PCL错误的江JDK17.0.4识别为17.4.1
2.剩余内存为5G却给jvm分配了8G内存
3.其中一次崩溃似乎是因为驱动不兼容（?）
你是不是加了什么高清材质包导致显存爆了（
是否能提供游戏客户端的错误报告（crash那个）

**Comment by yshuoyan** [comment]
现在不在家，等一会回来再搞可以吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月31日(周二) 中午1:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Hex-Dragon/PCL2] 内存显示错误 (Issue #1087)




 
发现了几个问题：
 1.PCL错误的江JDK17.0.4识别为17.4.1
 2.剩余内存为5G却给jvm分配了8G内存
 3.其中一次崩溃似乎是因为驱动不兼容（?）
 你是不是加了什么高清材质包导致显存爆了（
 是否能提供游戏客户端的错误报告（crash那个）

**Comment by ZHAOSBC** [comment]
> 现在不在家，等一会回来再搞可以吗
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年1月31日(周二) 中午1:47 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [Hex-Dragon/PCL2] 内存显示错误 (Issue #1087) 发现了几个问题： 1.PCL错误的江JDK17.0.4识别为17.4.1 2.剩余内存为5G却给jvm分配了8G内存 3.其中一次崩溃似乎是因为驱动不兼容（?） 你是不是加了什么高清材质包导致显存爆了（ 是否能提供游戏客户端的错误报告（crash那个） — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

随时都可以,又不是什么急事awa

**Comment by WorldHim** [comment]
> 发现了几个问题： 1.PCL错误的江JDK17.0.4识别为17.4.1 2.剩余内存为5G却给jvm分配了8G内存 3.其中一次崩溃似乎是因为驱动不兼容（?） 你是不是加了什么高清材质包导致显存爆了（ 是否能提供游戏客户端的错误报告（crash那个）

1. PCL 貌似有一个奇怪的判断机制会将 `X.0.X.X`（17.0.4.1）格式的 Java 版本号变成 `X.X.X`（17.4.1）建议新开 issue 反馈。
2. 可能是手动设置了内存大小导致的。
3. 我已经写的很清楚了。。。不是驱动不兼容，是内存溢出。。。日志连起来是：
> `The NVIDIA OpenGL driver has encountered an out of memory error.`
> Nvidia OpenGL 驱动遇到内存溢出错误。

使用光影在 `Log1.txt` 第 313 行：
> `[Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Loaded shaderpack: BSL_v7.2 绘境标准光影_原版 .zip`

**Comment by ZHAOSBC** [comment]
> > 发现了几个问题： 1.PCL错误的江JDK17.0.4识别为17.4.1 2.剩余内存为5G却给jvm分配了8G内存 3.其中一次崩溃似乎是因为驱动不兼容（?） 你是不是加了什么高清材质包导致显存爆了（ 是否能提供游戏客户端的错误报告（crash那个）
> 
> 1. PCL 貌似有一个奇怪的判断机制会将 `X.0.X.X`（17.0.4.1）格式的 Java 版本号变成 `X.X.X`（17.4.1），建议新开 issue 反馈。
> 2. 可能是手动设置了内存大小导致的。
> 3. 我已经写的很清楚了。。。不是驱动不兼容，是内存溢出。。。日志连起来是：
> 
> > `The NVIDIA OpenGL driver has encountered an out of memory error.`
> > Nvidia OpenGL 驱动遇到内存溢出错误。
> 
> 使用光影在 `Log1.txt` 第 313 行：
> 
> > `[Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Loaded shaderpack: BSL_v7.2 绘境标准光影_原版 .zip`

在log1第1469行PCL弹窗是驱动不兼容（不知道是怎么得出来的）
光影一般不怎么占显存，占显存的是高清材质包，并且显存满了会使用一部分内存作为显存，并不会导致游戏崩溃

**Comment by yshuoyan** [comment]
有光影，有材质包，是高光矿物和一个不是高清材质包，我也不知道为什么显卡驱动会出问题，那个jdk版本我还真没注意到，内存我统一说一下，打错了，是显示4G可用，一共8G，但是游戏进去一会就崩溃提示内存不足



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月31日(周二) 下午3:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Hex-Dragon/PCL2] 内存显示错误 (Issue #1087)




   
发现了几个问题： 1.PCL错误的江JDK17.0.4识别为17.4.1 2.剩余内存为5G却给jvm分配了8G内存 3.其中一次崩溃似乎是因为驱动不兼容（?） 你是不是加了什么高清材质包导致显存爆了（ 是否能提供游戏客户端的错误报告（crash那个）
   
PCL 貌似有一个奇怪的判断机制会将 X.0.X.X（17.0.4.1）格式的 Java 版本号变成 X.X.X（17.4.1），建议新开 issue 反馈。
 
可能是手动设置了内存大小导致的。
 
我已经写的很清楚了。。。不是驱动不兼容，是内存溢出。。。日志连起来是：
   
The NVIDIA OpenGL driver has encountered an out of memory error.
 Nvidia OpenGL 驱动遇到内存溢出错误。
  
使用光影在 Log1.txt 第 313 行：
  
[Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Loaded shaderpack: BSL_v7.2 绘境标准光影_原版 .zip
   
在log1第1469行PCL弹窗是驱动不兼容（不知道是怎么得出来的）
 光影一般不怎么占显存，占显存的是高清材质包，并且显存满了会使用一部分内存作为显存，并不会导致游戏崩溃

**Comment by yshuoyan** [comment]
我现在远控电脑看一看jdk版本



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月31日(周二) 下午3:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Hex-Dragon/PCL2] 内存显示错误 (Issue #1087)




   
发现了几个问题： 1.PCL错误的江JDK17.0.4识别为17.4.1 2.剩余内存为5G却给jvm分配了8G内存 3.其中一次崩溃似乎是因为驱动不兼容（?） 你是不是加了什么高清材质包导致显存爆了（ 是否能提供游戏客户端的错误报告（crash那个）
   
PCL 貌似有一个奇怪的判断机制会将 X.0.X.X（17.0.4.1）格式的 Java 版本号变成 X.X.X（17.4.1），建议新开 issue 反馈。
 
可能是手动设置了内存大小导致的。
 
我已经写的很清楚了。。。不是驱动不兼容，是内存溢出。。。日志连起来是：
   
The NVIDIA OpenGL driver has encountered an out of memory error.
 Nvidia OpenGL 驱动遇到内存溢出错误。
  
使用光影在 Log1.txt 第 313 行：
  
[Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Loaded shaderpack: BSL_v7.2 绘境标准光影_原版 .zip
   
在log1第1469行PCL弹窗是驱动不兼容（不知道是怎么得出来的）
 光影一般不怎么占显存，占显存的是高清材质包，并且显存满了会使用一部分内存作为显存，并不会导致游戏崩溃

**Comment by yshuoyan** [comment]
真的，PCL2显示jdk版本是错误的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月31日(周二) 下午3:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Hex-Dragon/PCL2] 内存显示错误 (Issue #1087)




   
发现了几个问题： 1.PCL错误的江JDK17.0.4识别为17.4.1 2.剩余内存为5G却给jvm分配了8G内存 3.其中一次崩溃似乎是因为驱动不兼容（?） 你是不是加了什么高清材质包导致显存爆了（ 是否能提供游戏客户端的错误报告（crash那个）
   
PCL 貌似有一个奇怪的判断机制会将 X.0.X.X（17.0.4.1）格式的 Java 版本号变成 X.X.X（17.4.1），建议新开 issue 反馈。
 
可能是手动设置了内存大小导致的。
 
我已经写的很清楚了。。。不是驱动不兼容，是内存溢出。。。日志连起来是：
   
The NVIDIA OpenGL driver has encountered an out of memory error.
 Nvidia OpenGL 驱动遇到内存溢出错误。
  
使用光影在 Log1.txt 第 313 行：
  
[Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Loaded shaderpack: BSL_v7.2 绘境标准光影_原版 .zip
   
在log1第1469行PCL弹窗是驱动不兼容（不知道是怎么得出来的）
 光影一般不怎么占显存，占显存的是高清材质包，并且显存满了会使用一部分内存作为显存，并不会导致游戏崩溃

**Comment by WorldHim** [comment]
> 真的，PCL2显示jdk版本是错误的
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年1月31日(周二) 下午3:17 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [Hex-Dragon/PCL2] 内存显示错误 (Issue #1087) 发现了几个问题： 1.PCL错误的江JDK17.0.4识别为17.4.1 2.剩余内存为5G却给jvm分配了8G内存 3.其中一次崩溃似乎是因为驱动不兼容（?） 你是不是加了什么高清材质包导致显存爆了（ 是否能提供游戏客户端的错误报告（crash那个） PCL 貌似有一个奇怪的判断机制会将 X.0.X.X（17.0.4.1）格式的 Java 版本号变成 X.X.X（17.4.1），建议新开 issue 反馈。 可能是手动设置了内存大小导致的。 我已经写的很清楚了。。。不是驱动不兼容，是内存溢出。。。日志连起来是： The NVIDIA OpenGL driver has encountered an out of memory error. Nvidia OpenGL 驱动遇到内存溢出错误。 使用光影在 Log1.txt 第 313 行： [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Loaded shaderpack: BSL_v7.2 绘境标准光影_原版 .zip 在log1第1469行PCL弹窗是驱动不兼容（不知道是怎么得出来的） 光影一般不怎么占显存，占显存的是高清材质包，并且显存满了会使用一部分内存作为显存，并不会导致游戏崩溃 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

额，你可以发个 issue 反馈或者我帮你发了。

**Comment by yshuoyan** [comment]
等我回去吧，现在在回家的路上，这个GitHub我在摸索摸索，我没用过



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月31日(周二) 下午3:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Hex-Dragon/PCL2] 内存显示错误 (Issue #1087)




  
真的，PCL2显示jdk版本是错误的
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2023年1月31日(周二) 下午3:17 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [Hex-Dragon/PCL2] 内存显示错误 (Issue #1087) 发现了几个问题： 1.PCL错误的江JDK17.0.4识别为17.4.1 2.剩余内存为5G却给jvm分配了8G内存 3.其中一次崩溃似乎是因为驱动不兼容（?） 你是不是加了什么高清材质包导致显存爆了（ 是否能提供游戏客户端的错误报告（crash那个） PCL 貌似有一个奇怪的判断机制会将 X.0.X.X（17.0.4.1）格式的 Java 版本号变成 X.X.X（17.4.1），建议新开 issue 反馈。 可能是手动设置了内存大小导致的。 我已经写的很清楚了。。。不是驱动不兼容，是内存溢出。。。日志连起来是： The NVIDIA OpenGL driver has encountered an out of memory error. Nvidia OpenGL 驱动遇到内存溢出错误。 使用光影在 Log1.txt 第 313 行： [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Loaded shaderpack: BSL_v7.2 绘境标准光影_原版 .zip 在log1第1469行PCL弹窗是驱动不兼容（不知道是怎么得出来的） 光影一般不怎么占显存，占显存的是高清材质包，并且显存满了会使用一部分内存作为显存，并不会导致游戏崩溃 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
额，你可以发个 issue 反馈或者我帮你发了。

**Comment by WorldHim** [comment]
> 等我回去吧，现在在回家的路上，这个GitHub我在摸索摸索，我没用过
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年1月31日(周二) 下午3:25 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [Hex-Dragon/PCL2] 内存显示错误 (Issue #1087) 真的，PCL2显示jdk版本是错误的 … ---原始邮件--- 发件人: @.&gt; 发送时间: 2023年1月31日(周二) 下午3:17 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [Hex-Dragon/PCL2] 内存显示错误 (Issue #1087) 发现了几个问题： 1.PCL错误的江JDK17.0.4识别为17.4.1 2.剩余内存为5G却给jvm分配了8G内存 3.其中一次崩溃似乎是因为驱动不兼容（?） 你是不是加了什么高清材质包导致显存爆了（ 是否能提供游戏客户端的错误报告（crash那个） PCL 貌似有一个奇怪的判断机制会将 X.0.X.X（17.0.4.1）格式的 Java 版本号变成 X.X.X（17.4.1），建议新开 issue 反馈。 可能是手动设置了内存大小导致的。 我已经写的很清楚了。。。不是驱动不兼容，是内存溢出。。。日志连起来是： The NVIDIA OpenGL driver has encountered an out of memory error. Nvidia OpenGL 驱动遇到内存溢出错误。 使用光影在 Log1.txt 第 313 行： [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Loaded shaderpack: BSL_v7.2 绘境标准光影_原版 .zip 在log1第1469行PCL弹窗是驱动不兼容（不知道是怎么得出来的） 光影一般不怎么占显存，占显存的是高清材质包，并且显存满了会使用一部分内存作为显存，并不会导致游戏崩溃 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt; 额，你可以发个 issue 反馈或者我帮你发了。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

那我先发 issue 顺便 at 你。

**Comment by LTCatt** [comment]
但这种崩溃和启动器无关，怎么说也不是 PCL 的 issue……

**Comment by yshuoyan** [comment]
这样的吗，可是内存显示4G可用不过一会就崩了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月31日(周二) 下午4:19
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Hex-Dragon/PCL2] 内存显示错误 (Issue #1087)




 
但这种崩溃和启动器无关，怎么说也不是 PCL 的 issue……
