### ISSUE TITLE
希望可以添加动画和颜色滤镜的开关

### ISSUE THREAD

**Issue by Dream-yyk** [Hex-Dragon/PCL2#1090]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

希望可以添加动画和颜色滤镜的开关

### 原因

动画还好，错误或警告弹窗的那个红色滤镜太吓人，可以类比gta三部曲的旧死亡动画qwq
改不了的话我只能降级用2.4.4了

**Comment by LTCatt** [comment]
……警告弹窗不警告一下那警告了个啥………………

**Comment by Dream-yyk** [comment]
但是我觉得弹窗上的红字够明显了，就想要个开关而已

**Comment by Dream-yyk** [comment]
大不了用2.4.4，关个更新提醒就是＞﹏＜
