### ISSUE TITLE
我手动设置了java17却在启动1.19.3时出现了java兼容性警告？

### ISSUE THREAD

**Issue by no-have-name** [Hex-Dragon/PCL2#1091]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我使用了java 17.0.3 x64去启动1.19.3和forge44.0.48
使用的是第三方登录
操作系统：win7 旗舰版 x64
PCL版本：Release 2.4.7

### 重现步骤

1、更新PCL2至2.4.7
2、使用第三方登录Minecraft
3、启动1.19.3+forge44.0.48

### 日志与附件

图片(https://user-images.githubusercontent.com/123821867/215672830-f48ca84e-ea23-4362-b70b-9c6ae9f9ba9d.png)

[log2-5（不知道为什么没有1）：(https://github.com/Hex-Dragon/PCL2/files/10543090/log2-5.1.zip)

 视频：https://user-images.githubusercontent.com/123821867/215673395-b5bec7c8-ca70-4c1d-8ee3-16f0a847c970.mp4

**Comment by youzi-2333** [comment]
与 #907 重复，感谢您的反馈~

**Comment by youzi-2333** [comment]
与 #907 重复，感谢您的反馈~

**Comment by WorldHim** [comment]
Java 17.0.3 无法启动 1.19.3。

**Comment by no-have-name** [comment]
我可以啊







                       
原始邮件
                       
                     

发件人："何嘉宸"< ***@***.*** &gt;;

发件时间：2023/1/31 13:59

收件人："Hex-Dragon/PCL2"< ***@***.*** &gt;;

抄送人："no-have-name"< ***@***.*** &gt;;"State change"< ***@***.*** &gt;;

主题：Re: [Hex-Dragon/PCL2] 我手动设置了java17却在启动1.19.3时出现了java兼容性警告？ (Issue #1091)




 
Java 17.0.3 无法启动 1.19.3。
 
&mdash;

**Comment by WorldHim** [comment]
> 我可以啊 原始邮件 发件人："何嘉宸"< ***@***.*** &gt;; 发件时间：2023/1/31 13:59 收件人："Hex-Dragon/PCL2"< ***@***.*** &gt;; 抄送人："no-have-name"< ***@***.*** &gt;;"State change"< ***@***.*** &gt;; 主题：Re: [Hex-Dragon/PCL2] 我手动设置了java17却在启动1.19.3时出现了java兼容性警告？ (Issue #1091) Java 17.0.3 无法启动 1.19.3。 &mdash; Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

确实重复，你的版本写错了，你用的是正式版 2.4.4，下次交 issue 记得确定版本。。。

**Comment by no-have-name** [comment]
我就是2.4.7啊，今天打开PCL时ta就帮我自动更新了2.4.7，确定后，第三方登录没了，java设置没了，还只扫出来java17，还得手动设置和添加


                       
原始邮件
                       
                     

发件人："何嘉宸"< ***@***.*** &gt;;

发件时间：2023/1/31 14:07

收件人："Hex-Dragon/PCL2"< ***@***.*** &gt;;

抄送人："no-have-name"< ***@***.*** &gt;;"State change"< ***@***.*** &gt;;

主题：Re: [Hex-Dragon/PCL2] 我手动设置了java17却在启动1.19.3时出现了java兼容性警告？ (Issue #1091)




  
我可以啊 原始邮件 发件人："何嘉宸"< @.*** &gt;; 发件时间：2023/1/31 13:59 收件人："Hex-Dragon/PCL2"< @.*** &gt;; 抄送人："no-have-name"< @.*** &gt;;"State change"< @.*** &gt;; 主题：Re: [Hex-Dragon/PCL2] 我手动设置了java17却在启动1.19.3时出现了java兼容性警告？ (Issue #1091) Java 17.0.3 无法启动 1.19.3。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.***&gt;
  
确实重复，你的版本写错了，你用的是正式版 2.4.4，下次交 issue 记得确定版本。。。

**Comment by no-have-name** [comment]
我用的就是2.4.7，今天打开PCL后，ta就自己给我升级了4.2.7，确定后，第三方设置没了，java设置没了，还只扫出来7、8，还得自己添加17



                       
原始邮件
                       
                     

发件人："何嘉宸"< ***@***.*** &gt;;

发件时间：2023/1/31 14:07

收件人："Hex-Dragon/PCL2"< ***@***.*** &gt;;

抄送人："no-have-name"< ***@***.*** &gt;;"State change"< ***@***.*** &gt;;

主题：Re: [Hex-Dragon/PCL2] 我手动设置了java17却在启动1.19.3时出现了java兼容性警告？ (Issue #1091)




  
我可以啊 原始邮件 发件人："何嘉宸"< @.*** &gt;; 发件时间：2023/1/31 13:59 收件人："Hex-Dragon/PCL2"< @.*** &gt;; 抄送人："no-have-name"< @.*** &gt;;"State change"< @.*** &gt;; 主题：Re: [Hex-Dragon/PCL2] 我手动设置了java17却在启动1.19.3时出现了java兼容性警告？ (Issue #1091) Java 17.0.3 无法启动 1.19.3。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.***&gt;
  
确实重复，你的版本写错了，你用的是正式版 2.4.4，下次交 issue 记得确定版本。。。

**Comment by WorldHim** [comment]
`Log2.txt` 第 1 行：
> `[Start] 程序版本：Release 2.4.4（272）`

第 32 行（更新弹窗）：
> `[Control] 普通弹窗：PCL2 已更新至 Release 2.4.4`

而且你使用的是正式版怎么更新到 2.4.7。。。

**Comment by youzi-2333** [comment]
正式版已经推出 2.4.7 了，如果更新后仍然没有修复请联系重开。

**Comment by no-have-name** [comment]
我依稀记得启动PCL时有个错误，好像是权限不足，无法写入（忘记了）







                       
原始邮件
                       
                     

发件人："柚子柚子"< ***@***.*** &gt;;

发件时间：2023/1/31 14:33

收件人："Hex-Dragon/PCL2"< ***@***.*** &gt;;

抄送人："no-have-name"< ***@***.*** &gt;;"State change"< ***@***.*** &gt;;

主题：Re: [Hex-Dragon/PCL2] 我手动设置了java17却在启动1.19.3时出现了java兼容性警告？ (Issue #1091)




 
正式版已经推出 2.4.7 了，如果更新后仍然没有修复请联系重开。
 
&mdash;

**Comment by WorldHim** [comment]
> 我依稀记得启动PCL时有个错误，好像是权限不足，无法写入（忘记了） 原始邮件 发件人："柚子柚子"< ***@***.*** &gt;; 发件时间：2023/1/31 14:33 收件人："Hex-Dragon/PCL2"< ***@***.*** &gt;; 抄送人："no-have-name"< ***@***.*** &gt;;"State change"< ***@***.*** &gt;; 主题：Re: [Hex-Dragon/PCL2] 我手动设置了java17却在启动1.19.3时出现了java兼容性警告？ (Issue #1091) 正式版已经推出 2.4.7 了，如果更新后仍然没有修复请联系重开。 &mdash; Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

你可以试试手动下载最新版本，看看会不会出现问题。

**Comment by no-have-name** [comment]
之前的log1倍隐藏了，解除后就好了，也正常写入版本是2.4.7了







                       
原始邮件
                       
                     

发件人："何嘉宸"< ***@***.*** &gt;;

发件时间：2023/1/31 14:45

收件人："Hex-Dragon/PCL2"< ***@***.*** &gt;;

抄送人："no-have-name"< ***@***.*** &gt;;"State change"< ***@***.*** &gt;;

主题：Re: [Hex-Dragon/PCL2] 我手动设置了java17却在启动1.19.3时出现了java兼容性警告？ (Issue #1091)




  
我依稀记得启动PCL时有个错误，好像是权限不足，无法写入（忘记了） 原始邮件 发件人："柚子柚子"< @.*** &gt;; 发件时间：2023/1/31 14:33 收件人："Hex-Dragon/PCL2"< @.*** &gt;; 抄送人："no-have-name"< @.*** &gt;;"State change"< @.*** &gt;; 主题：Re: [Hex-Dragon/PCL2] 我手动设置了java17却在启动1.19.3时出现了java兼容性警告？ (Issue #1091) 正式版已经推出 2.4.7 了，如果更新后仍然没有修复请联系重开。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.***&gt;
  
你可以试试手动下载最新版本，看看会不会出现问题。
