### ISSUE TITLE
[功能优化]在刷新背景图片或音乐时忽略当前正在使用的文件

### ISSUE THREAD

**Issue by yigenhuobahh** [Hex-Dragon/PCL2#1092]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在刷新背景图片或音乐时忽略当前正在使用的图片或音乐
或许可以和Q音一样做一个随机列表顺序切换？

### 原因

特殊的一次我换了七八次图片才不是一样的

**Comment by yigenhuobahh** [comment]
坐等忽略.jpg

**Comment by youzi-2333** [comment]
举个例子，如果只加三张图片，那么每次重复的概率应该是 1/3，连续好几次一样也有可能；但是不应该七八次都一样啊……这概率太小了……

而且切背景图片不是放那里让用户按的，是启动 PCL2 的时候切的，先等龙猫回复吧，感谢您的反馈~

**Comment by LTCatt** [comment]
刷新背景图片的作用不是这个……
