### ISSUE TITLE
Java 版本识别错误

### ISSUE THREAD

**Issue by WorldHim** [Hex-Dragon/PCL2#1093]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

从 #1087 中发现的问题。
PCL 有一个奇怪的判断机制会将 `X.0.X.X`（17.0.4.1）格式的 Java 版本号识别成 `X.X.X`（17.4.1）。
![image](https://user-images.githubusercontent.com/68632311/215697250-ab2339dd-2d7d-4c6f-9277-80ba0c61af4c.png)

### 重现步骤

搜索或导入版本号为 `X.0.X.X` 格式的 Java。

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10543934/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10543935/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10543936/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10543937/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10543938/Log5.txt)

**Comment by WorldHim** [comment]
建议反馈者建议写 @ZHAOSBC 和 @yshuoyan，谢谢

**Comment by LTCatt** [comment]
PCL 会把版本号的零抠掉改成三段式，WAI。
