### ISSUE TITLE
点击关闭运行中的minecraft没有关闭，关闭启动器也不行

### ISSUE THREAD

**Issue by Chormore-EDGE** [Hex-Dragon/PCL2#1094]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

启动游戏后，点击关闭运行中的mine craft没有关闭，pcl2提示已经关闭，游戏实际上没关闭（概率）

### 重现步骤

1、启动游戏（所有版本都可以）
2、运行一段时间后点击''关闭运行中的Minecraft'按钮
3.游戏未关闭

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10544194/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10544195/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10544196/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10544197/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10544198/Log5.txt)

**Comment by youzi-2333** [comment]
如果启动游戏后关闭了第一次的 PCL2，游戏进程信息会消失，第二次启动 PCL2 时，即使第二次启动了游戏，也无法结束第一次启动的游戏。
请确认在启动游戏后没有关闭 PCL2，感谢您的反馈~

**Comment by Chormore-EDGE** [comment]
没有关闭，一直在挂在任务栏，

**Comment by youzi-2333** [comment]
这可能是因为 Minecraft 占用内存过多，导致操作系统决定淘汰某些内存，以保证操作系统运行正常；而 PCL2 的 GameProcess 内容正好就被淘汰了，导致 PCL2 无法获取游戏 Process 信息，也没法杀掉进程了 =。=（仅为猜测）

**Comment by yigenhuobahh** [comment]
奇怪，我的w10 22h2只有8g内存也不会出现bug，但是看你的日志有11.3g可用内存，给MC分了8g应该还有2.3g的可用啊

**Comment by youzi-2333** [comment]
他可能在玩一种很新的东西，让 Minecraft 的占用内存大幅上升（
也有可能是因为 PCL2 挂在后台，自动进了效能模式或被操作系统挂起了，然后卡出了一些想不到的 Bug。
既然能复现出来，应该也可以修掉（吧）

**Comment by Chormore-EDGE** [comment]
我玩的服务器经常崩掉，可能是有人造了高频红石
（6）

**Comment by Chormore-EDGE** [comment]
好久之前的bug了，结果反馈的时候没开加速器访问不了github(悲

**Comment by youzi-2333** [comment]
既然是服务器的话，那可能确实是因为高频红石导致下载量剧增，然后接收缓冲区爆满（即使只有一瞬间是满的，内存也可能会被操作系统淘汰掉）不过我其实感觉不一定是内存被删除的原因，我平时把 PCL2 挂到后台玩三四个小时也没问题.jpg

刚刚在 1.19.3 里面炸了 25000 个 TNT，游戏干到未响应，还是无法复现，真的不知道啥原因了……

**Comment by LTCatt** [comment]
`Java 信息：JRE 18 (18.1.1)，64 位：C:\Program Files\Common Files\Oracle\Java\javatmp\`
这个路径的 Java 有相当蛋疼的性质，会让 PCL 关闭不了。
你的 Java 列表里还有哪些 Java，截个图？

**Comment by Chormore-EDGE** [comment]
![image](https://user-images.githubusercontent.com/114737601/215923778-38585dfd-2624-4484-a036-e6558cb42a4a.png)

**Comment by Chormore-EDGE** [comment]
不知道为啥会识别到网易的java

**Comment by iPodtouch6557** [comment]
我有时也会这样（）
而且我更加离谱的是有时我在游戏启动进程只到60%的时候关闭启动器，游戏也会正常启动，有一次我闲的重复了多次，结果电脑卡爆了（**********

**Comment by LionelMessi114514** [comment]
在任务栏右键，点任务管理器，强制退出。

**Comment by iPodtouch6557** [comment]
> 在任务栏右键，点任务管理器，强制退出。

那会已经卡死了，没用（）

**Comment by iPodtouch6557** [comment]
我再补充一个，是我在测试另一个bug时出现的
版本是2.3.2，不管多久前的版本，哪怕2.0.5,2.1.4都一样，2.4.7也试过，复现成功
就是在启动界面启动到 等待窗口出现 时取消启动（我后来关了pcl，事实是关不关都行）仍然会启动游戏
总结一下，就是在特定情况下（启动器启动了游戏但窗口没出现），pcl会杀不掉进程

**Comment by LTCatt** [comment]
这个问题我没法直接修复，因为这是一部分特殊的 Java 导致的……
曲线救国，下个版本起 PCL 将不会优先使用这些特殊的 Java =。=

**Comment by Chormore-EDGE** [comment]
(⊙﹏⊙)

**Comment by Chormore-EDGE** [comment]
![image](https://user-images.githubusercontent.com/114737601/223622310-8a265812-5782-4f77-ace5-cd6db879e8a0.png)
解个锁？awa

**Comment by LTCatt** [comment]
你的解锁码：zga42NdvBxBaDRIreD6/+WAOsBXp8acd
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by Chormore-EDGE** [comment]
谢谢awa

**Comment by LTCatt** [comment]
再发下识别码？

**Comment by LTCatt** [comment]
你的解锁码：B2KdWhZm3/uXriyQGl5ODp8AcWouWI2N
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by Chormore-EDGE** [comment]
好的，谢谢
(下次再也不换系统了

**Comment by Chormore-EDGE** [comment]
我又来了，要个活跃橙，解锁码 346E-7C94-76E6-8985

**Comment by LTCatt** [comment]
你的解锁码：aw5NUWlrrx45kRl22n0hq03tvpiitFFW
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
