### ISSUE TITLE
为重复Mod的Forge错误提示提供处理方案

### ISSUE THREAD

**Issue by infidiotWolf** [Hex-Dragon/PCL2#1096]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在Forge提示Mod重复时，提供解决方案（提示哪些Mod重复需要删除，并基于版本信息提供建议）
而不是仅仅显示一个Forge提供的错误信息（
![image](https://user-images.githubusercontent.com/96373780/215719478-69da5fc2-bd88-41ac-8d5f-2bbb4f12f9f7.png)

### 原因

这项优化让我可以更方便地xxxx。
如果没有这项优化，我每次都必须xxxx，让操作变得很麻烦。
所以这项优化可以让xxxx更加便捷，以此xxxx才能得到普遍。
也能令xxxx的计划实行是，不会因xxxx强大的引力偏移轨道，后达到洛希极限被xxxx。
同时xxxx也可以修复煎饼果子里没有果子，方便面里没有便的bug。
那么只需要xxxx，这项优化就会被采用，也会使一氧化二氢的毒性被xxxx中和。

**Comment by Mineshelf-3j6zz0** [comment]
这个实现起来会把龙猫累个半死吧……
{除非找第三方的错误检测组件}(bushi)

**Comment by Mineshelf-3j6zz0** [comment]
> 这个实现起来会把龙猫累个半死吧…… {除非找第三方的错误检测组件}(bushi)

不过是不是可以转变一下思路，让PCL2校验mod大小后给大小一样的mod做内容对比然后主动提示[这样可能对性能有损耗吧?]

**Comment by WForst-Breeze** [comment]
一般来讲，直接用翻译软件翻译就可以**确认并解决**绝大多数 Mod 重复导致的游戏崩溃问题（
已初步确认，感谢您的反馈~

**Comment by bwtx2023** [comment]
> 这个实现起来会把龙猫累个半死吧……
> 
> {除非找第三方的错误检测组件}(bushi)

检测关键词即可

**Comment by 212112111zwl** [comment]
> 这个实现起来会把龙猫累个半死吧……

就是解析一下错误信息而已，不会很麻烦的（吧

**Comment by LTCatt** [comment]
这个没有明确格式，并且翻译一下就行，没必要
