### ISSUE TITLE
允许执行命令后暂停启动游戏/将执行命令加入总设置中

### ISSUE THREAD

**Issue by Shapaper** [Hex-Dragon/PCL2#1100]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

1.pcl2在新版本中加入了启动前执行命令的功能，是否能获取回调，当命令行最新的消息为False，就取消启动，如果检测到True，就直接启动，不继续等命令行真正执行
2.允许将启动前执行的命令放在pcl2的总设置内【版本设置改成：默认跟随全局设置】

### 原因

1.这个功能可以方便外置的检测更新等更多高级的玩法
2.可以方便一次性设置多个版本

**Comment by Shapaper** [comment]
顺便能不能再加几个变量:
1.模组加载器+加载器版本
2.版本备注
3.分配内存大小
4.本机当前IP【这个没太大必要，但是可以给内网映射的那种服务器获取到IP】
5.Mod列表【格式为json的mod列表，尽量提供mod介绍】【可能有点长，但是cmd没长度限制吧（】
以上几种可以方便腐竹/整合包作者远程帮助解决用户无法启动游戏。

**Comment by YUANXINGlingyun** [comment]
可能有戏
期待正式加入中

**Comment by QWXL** [comment]
我认为这种……敏感（或许）的设置，在版本设置内的默认情况应该是什么都不做比较好，然后添加复选框额外控制是否跟随全局。

**Comment by Shapaper** [comment]
> 我认为这种……敏感（或许）的设置，在版本设置内的默认情况应该是什么都不做比较好，然后添加复选框额外控制是否跟随全局。

我不这样认为：
1.用户填写时自己

**Comment by Shapaper** [comment]
话说能不能可以加一个指定执行顺序：
启动后执行命令，并可以把进程的pid｛pid｝传给指令
@LTCatt

**Comment by QWXL** [comment]
> 

不，用户在很多情况下是会忘的。
比如说：
有一个玩家喜欢玩多mod整合包，他有很多个整合包，并且用cmd写了一个自动关闭浏览器等高耗能软件的脚本，将其添加进了全局设置里，使其在整合包启动前执行一次。
但，有一次他想玩普通纯净端的时候，他下意识忽略了会关闭浏览器（在他的潜意识里认为这没必要释放内存）就启动了游戏，导致他在浏览器上编写的文档没能保存。

而且，只是一个复选框并不麻烦，点一下的事情，但却能规避许多潜在风险。

**Comment by Shapaper** [comment]
你说的是特殊情况，这个本来就不应该放全局

**Comment by QWXL** [comment]
> 你说的是特殊情况，这个本来就不应该放全局

这并不特殊，不是任何人都可以随意开着多个软件玩游戏的。相反，大多数人都需要事先关闭一些高性能消耗的软件才能流畅游戏，在此基础上，把自动关闭，释放内存等操作放在全局自动执行是很正常，也普遍的事情。
并且不少人也习惯，或者必须使用浏览器进行编辑。

而且，添加一个复选框并不难，也对操作进行了极大的简化（与每一个游戏版本都输入一遍命令相比），同时还能规避一些可能的风险，何乐而不为之？

**Comment by Shapaper** [comment]
我在上面写的是添加全局，并且把原有的设置默认跟随全局（是默认，可以独立设置啊）

**Comment by Shapaper** [comment]
可能您理解错了qwq

**Comment by QWXL** [comment]
不，我要说的是默认不追随全局，手动使用复选框再调用全局设置。您误会我的意思了，cmd命令作为直接对windows进行修改的东西，默认情况下是关闭才好。
同时，也更保险，并且对便利性依旧有不少的优化。

**Comment by Shapaper** [comment]
他自己填写的全局就要自己负担责任
ps：我想做个社会调查，让参加调查的人在全局变量中添加一个指令，就可以在他们每次启动时候发出一个请求到服务器，半年后公布调查结果。比如哪个版本的人用得多（

**Comment by QWXL** [comment]
不是很现实，不可能指望用户自己去记住他做的任何更改。更何况，哪怕提前声明需要自己负责，也有事后被找上门的风险
不如使用复选框，在技术上来说这并不困难，却能规避很多风险……包括个人数据上的或者是其他的事情

并且……“高级用户”也是人，也会忘记事情，也可能把自己曾经做过的更改忘掉

**Comment by Shapaper** [comment]
全局变量为懒人而生，它的作用就是不用重复填写，按照您的思路，就失去它的作用

**Comment by Shapaper** [comment]
就像全局设置中的设置内存功能，就会有人一不小心挑错，但这个功能依然在

**Comment by Shapaper** [comment]
我的建议是：在填写的时候弹窗确认
