### ISSUE TITLE
崩溃后执行命令

### ISSUE THREAD

**Issue by Shapaper** [Hex-Dragon/PCL2#1101]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

与启动前执行命令同理
允许崩溃后执行命令
希望的环境变量：
1.pcl2分析的报错
2.报错信息.zip的路径[假如使用这个变量，则在缓存目录自动生成zip后执行命令，让这个写命令的自己删除临时文件]

### 原因

1.这个功能可以方便腐竹/整合包作者第一时间获取到崩溃信息，尽早解决问题
2.进行数据统计后可以快速定位最容易导致崩溃的问题

**Comment by youzi-2333** [comment]
~~好家伙，真是万物皆可执行命令~~已确认，感谢您的反馈~

**Comment by WForst-Breeze** [comment]
是否与 #1008 性质相同qwq？

**Comment by youzi-2333** [comment]
um，看来是有点类似……

**Comment by Shapaper** [comment]
> 是否与 #1008 性质相同qwq？

不相同，崩溃后pcl2可以弹出报错窗口，代表pcl2肯定能检测到的

**Comment by Shapaper** [comment]
1.既然龙猫制作了奔溃分析功能，那这个肯定也是同理有用的
2.崩溃可能在游戏启动一瞬间就崩溃

**Comment by youzi-2333** [comment]
既然有崩溃分析了，为啥还要执行命令。。
虽然有些人看不懂崩溃弹窗第二行的内容……
看看龙猫咋说吧

**Comment by Shapaper** [comment]
> 既然有崩溃分析了，为啥还要执行命令。。 虽然有些人看不懂崩溃弹窗第二行的内容…… 看看龙猫咋说吧

1.大数据分析（bushi
分析大家经常出现的问题
一些几率高的修复下。
一些一共就出现1-2次的概率奔溃就不修了(
2.可以自己搓个弹窗，用来分析某些端的独占bug（比如i18n高版本的几率无法启动游戏bug）

**Comment by Shapaper** [comment]
> 既然有崩溃分析了，为啥还要执行命令。。 虽然有些人看不懂崩溃弹窗第二行的内容…… 看看龙猫咋说吧

1.大数据分析（bushi
分析大家经常出现的问题
一些几率高的修复下。
一些一共就出现1-2次的概率奔溃就不修了(
2.可以自己搓个弹窗，用来分析某些端的独占bug（比如i18n高版本的几率无法启动游戏bug）

**Comment by LTCatt** [comment]
适用面太小，并且与 #1008 同样不能确保执行，暂不考虑
