### ISSUE TITLE
鼠标悬浮在按钮上的提示

### ISSUE THREAD

**Issue by gi-b716** [Hex-Dragon/PCL2#1103]
### 检查项

- [x] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

现在 当鼠标悬浮在某一些按钮上，
出现的提示只会短暂显示一下 然后消失
来不及看清
你可以看这个视频：https://www.dropbox.com/s/raok1q1pzbautqe/2023-02-01_11-17-02.mp4?dl=0
其中 当鼠标移到按钮上 “清除Minecraft日志”的提示框 只出现了一小下

### 原因

这项优化让我可以更方便地查看按钮用途。
如果没有这项优化，我每次都必须动用我的钛合金狗眼 才能看到提示框，让操作变得很麻烦。

**Comment by youzi-2333** [comment]
你确定只会短暂显示一下？
只要不乱按 `Esc`，鼠标在按钮上面乱晃都没事……

**Comment by LTDove** [comment]
emmm ?
没吧
我这边好好的啊

**Comment by gi-b716** [comment]
emmm
我是win11
最新版pcl
重新下载一个都不行（

**Comment by youzi-2333** [comment]
https://user-images.githubusercontent.com/106497113/215941404-e7b892ee-2d86-4340-87e5-89155f9f3955.mp4

我这边就是这样的，除非按 Esc 会隐藏提示，敲键盘和移鼠标都不会消失……要是重启 PCL2 不行的话就找龙猫处理
