### ISSUE TITLE
下载版本命名里有空格还有大小写就会无法下载

### ISSUE THREAD

**Issue by LTDove** [Hex-Dragon/PCL2#1104]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

下载版本命名里有空格还有大小写就会无法下载

### 重现步骤

在下载前命名 含有 空格 大小写字母 好像就无法下载

### 日志与附件

暂时无法上传

**Comment by LTDove** [comment]
emmmmm,离谱.jpg

**Comment by youzi-2333** [comment]
我这边无法复现。请上传 Log 看看怎么回事，如果 GitHub 传不上可以传网盘。

还有，下次发 Comment 记得不要点 Close with comment……

**Comment by LTDove** [comment]
好像又好了.........
不知道是不是我的问题......

**Comment by LTDove** [comment]
内群的朋友说可以加
估计应该是我的问题......

**Comment by LTDove** [comment]
a,是我的问题....为了进git开了加速器(抱歉 打扰了

**Comment by youzi-2333** [comment]
好的，感谢您的反馈~
