### ISSUE TITLE
无法启动游戏：libjlw-1.3.2.dll: Can't find dependent libraries

### ISSUE THREAD

**Issue by ghost** [Hex-Dragon/PCL2#1108]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

下载1.19.3Forge失败，不管是哪个Forge版本

### 重现步骤

尝试去下载1.19.3的Forge版本

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10554543/Log1.txt)

**Comment by Xiaomckedou233** [comment]
似乎PCL的判断有问题,安装1.19.3Forge会自动选择Java 8

**Comment by King-ming136121** [comment]
> ```
> [15:49:39.529] [Java] 选定的 Java：JRE 8 (8.0.51)，64 位：C:\Program Files\Java\jre1.8.0_51\bin\
> 
> [15:50:10.594] [Download] 开始安装 Forge：-Doolloo.jlw.tmpdir="C:\Users\32023\AppData\Roaming\PCL" -cp "C:\Users\32023\AppData\Local\Temp\PCL\Cache\forge_installer.jar;C:\Users\32023\AppData\Local\Temp\PCL\Cache\Code\ForgeInstall-44.1.7_68959" -jar "C:\Users\32023\AppData\Roaming\PCL\JavaWrapper.jar"  com.bangbang93.ForgeInstaller "C:\Users\32023\AppData\Local\Temp\PCL\Install\790530263\
> [15:50:11.010] [Installer] Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\32023\AppData\Roaming\PCL\libwrapper.dll: Can't find dependent libraries
> [15:50:11.010] [Installer] 	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
> [15:50:11.010] [Installer] 	at java.lang.ClassLoader.loadLibrary0(Unknown Source)
> [15:50:11.010] [Installer] 	at java.lang.ClassLoader.loadLibrary(Unknown Source)
> [15:50:11.010] [Installer] 	at java.lang.Runtime.load0(Unknown Source)
> [15:50:11.010] [Installer] 	at java.lang.System.load(Unknown Source)
> [15:50:11.010] [Installer] 	at oolloo.jlw.ArgLoader.loadNative(ArgLoader.java:93)
> [15:50:11.010] [Installer] 	at oolloo.jlw.ArgLoader.<init>(ArgLoader.java:16)
> [15:50:11.010] [Installer] 	at oolloo.jlw.Wrapper.main(Wrapper.java:22)
> [15:50:11.041] Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\32023\AppData\Roaming\PCL\libwrapper.dll: Can't find dependent libraries
> 	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
> 	at java.lang.ClassLoader.loadLibrary0(Unknown Source)
> 	at java.lang.ClassLoader.loadLibrary(Unknown Source)
> 	at java.lang.Runtime.load0(Unknown Source)
> 	at java.lang.System.load(Unknown Source)
> 	at oolloo.jlw.ArgLoader.loadNative(ArgLoader.java:93)
> 	at oolloo.jlw.ArgLoader.<init>(ArgLoader.java:16)
> 	at oolloo.jlw.Wrapper.main(Wrapper.java:22)
> ```
> 
> 怎么做到用 Java 8 安装 Forge 1.19.3 的......

我弄得是自动选择适用的java版本，怎么变java8了

**Comment by Big-Cake-jpg** [comment]
建议更改标题为：Forge 1.19.3 安装失败：安装时使用的 Java 版本错误

**Comment by King-ming136121** [comment]
> 建议更改标题为：Forge 1.19.3 安装失败：安装时使用的 Java 版本错误

好吧！我更改下试试！

**Comment by King-ming136121** [comment]
> 建议更改标题为：Forge 1.19.3 安装失败：安装时使用的 Java 版本错误。
> 
> 但不知为何，我这里无法复现。

我也不知道为啥，我也是无意中才复现的！

**Comment by King-ming136121** [comment]
> hmmmmm 你Java是怎么装的

就重官网上安装的！

**Comment by YUANXINGlingyun** [comment]
改完依赖了么？

**Comment by YUANXINGlingyun** [comment]
改完依赖了么？

**Comment by YUANXINGlingyun** [comment]
改完依赖了么？

**Comment by YUANXINGlingyun** [comment]
改完依赖了么？

**Comment by YUANXINGlingyun** [comment]
改完依赖了么？

**Comment by YUANXINGlingyun** [comment]
改完依赖了么？

**Comment by Xiaomckedou233** [comment]
> > hmmmmm 你Java是怎么装的
> 
> 就重官网上安装的！

那不应该啊,手动更换其他Java版本看看?

**Comment by 212112111zwl** [comment]
> 改完依赖了么？
> 改完依赖了么？
> 改完依赖了么？
> 改完依赖了么？
> 改完依赖了么？
> 改完依赖了么？
> 改完依赖了么？

请不要刷屏，谢谢

**Comment by King-ming136121** [comment]
> > > hmmmmm 你Java是怎么装的
> > 
> > 
> > 就重官网上安装的！
> 
> 那不应该啊，手动更换其他Java版本看看？

好！我更改下试试！

**Comment by King-ming136121** [comment]
> 改完依赖了么？

改了！

**Comment by Xiaomckedou233** [comment]
Java 8我这边安装时并没有问题,可能是你Java安装中一些差错?

**Comment by King-ming136121** [comment]
> Java 8我这边安装时并没有问题，可能是你Java安装中一些差错？

![image](https://user-images.githubusercontent.com/110441378/215991103-ea5651eb-eb05-4370-8633-8c5508cfa29a.png)
没问题啊！我无非是选择了稍旧版本的java，有啥问题吗？

**Comment by King-ming136121** [comment]
> 手动切换成适合该版本运行所需要的java，问题没有复现，似乎错误出现在开启自动选择java版本后，PCL2没有选择适用于该版本所需运行的Java——Java17, 而是选择了Java8！

而且我手动切换成适合该版本运行所需要的java，问题没有复现，不知道咋回事？

**Comment by YUANXINGlingyun** [comment]
在让 PCL2 启动器自动选择用于安装和启动 快照2.4.7 Forge 1.19.3的 Java时应当选择 Java 17 而不是错误的 Java 8

Bug吧，龙猫来看下

**Comment by LTCatt** [comment]
@00ll00 又来一个……
ps. 这不是 Java 的问题……

**Comment by ZHAOSBC** [comment]
新版本的java8是能完成forge的安装的，但是你安装的这个版本是2015年发布的（那时候PCL都没有，什么上古版本）。你可能找到假的官网了（

**Comment by 00ll00** [comment]
是wrapper的问题，等我修修🐛

**Comment by ZHAOSBC** [comment]
> 是wrapper的问题，等我修修🐛

这样啊(´･_･`)

**Comment by King-ming136121** [comment]
> 新版本的java8是能完成forge的安装的，但是你安装的这个版本是2015年发布的（那时候PCL都没有，什么上古版本）。你可能找到假的官网了（

我听别人说换用较高的Java版本，PCL2可能会提醒你降低java版本，所以我就找到了这个低版本的Java，而且还是在mcbbs上找的，怎么可能会遇到假的呢？

**Comment by King-ming136121** [comment]
> 新版本的java8是能完成forge的安装的，但是你安装的这个版本是2015年发布的（那时候PCL都没有，什么上古版本）。你可能找到假的官网了（

我也真的想不明白！

**Comment by LTCatt** [comment]
在文件资源管理器地址输入 `%APPDATA%\PCL` 然后删除 libwrapper.dll 和 libwrapper32.dll 再试？

**Comment by King-ming136121** [comment]
> %APPDATA%\PCL

![image](https://user-images.githubusercontent.com/110441378/216526213-c3387891-d1b6-43f0-abb1-e8331f5ca19f.png)
文件管理器没有啊！

**Comment by King-ming136121** [comment]
> 在文件资源管理器地址输入 `%APPDATA%\PCL` 然后删除 libwrapper.dll 和 libwrapper32.dll 再试？

只有这些关于联机模块的东西,要把这些东西给删了？

**Comment by YUANXINGlingyun** [comment]
不是有个 libwrapper.dll 吗，删掉试试

在 2023-02-03 14:15:03，user123456 ***@***.***> 写道：


%APPDATA%\PCL


文件管理器没有啊！

**Comment by WForst-Breeze** [comment]
> 只有这些关于联机模块的东西,要把这些东西给删了？

试着删除这个
![image](https://user-images.githubusercontent.com/110760354/216531370-8112c8f1-fddf-470d-8a45-736609ace941.png)

**Comment by King-ming136121** [comment]
> > 只有这些关于联机模块的东西,要把这些东西给删了？
> 
> 试着删除这个 ![image](https://user-images.githubusercontent.com/110760354/216531370-8112c8f1-fddf-470d-8a45-736609ace941.png)

OK！我试试！

**Comment by King-ming136121** [comment]
> 在文件资源管理器地址输入 `%APPDATA%\PCL` 然后删除 libwrapper.dll 和 libwrapper32.dll 再试？

还是不行！似乎删掉libwrapper.dll后再去换上自动选择后java版本后再去下载1.19.3Forge版本还是会失败！而且显示的错误提示一样！

**Comment by King-ming136121** [comment]
> 在文件资源管理器地址输入 `%APPDATA%\PCL` 然后删除 libwrapper.dll 和 libwrapper32.dll 再试？

除非手动选择java17，要不然还是出错！手动选择java17则不会！

**Comment by YUANXINGlingyun** [comment]
等JavaWrapper 的修复吧

**Comment by YUANXINGlingyun** [comment]
等JavaWrapper 的修复吧

**Comment by LTCatt** [comment]
#1129 同样汇报了此问题，确认不是个例（

**Comment by LTCatt** [comment]
请尝试更新 PCL 到 2.5.0，检查这个 issue 是否依然存在，如果依然存在请重新上传新版本下的日志，多谢（

**Comment by King-ming136121** [comment]
> 请尝试更新 PCL 到 2.5.0，检查这个 issue 是否依然存在，如果依然存在请重新上传新版本下的日志，多谢（

现在问题已经不会复现了！可以关闭这条issue了！快照2.5.0未复现该问题！

**Comment by RawDiamondMC** [comment]
草了，这玩意明明是好了怎么被添加上忽略标签了

**Comment by LTCatt** [comment]
#2929 已确认在 2.6.10 复现

**Comment by Rakkaun** [comment]
[RawOutput.log](https://github.com/Hex-Dragon/PCL2/files/13535885/RawOutput.log)
2.6.10pcl出现了这个问题

**Comment by LTCatt** [comment]
@00ll00 再康康？

**Comment by burningtnt** [comment]
[错误报告-2023-12-16_17.41.20.zip](https://github.com/Hex-Dragon/PCL2/files/13692293/-2023-12-16_17.41.20.zip) @xwh1412 也出现了一样的问题

**Comment by LTCatt** [comment]
疑似和 Java 8 有关，试试换 Java 11？
@Rakkaun @cym405

**Comment by 00ll00** [comment]
好像有在arm架构的机器上无法加载dll的情况？有人能帮忙测试一下吗🤔

**Comment by LTCatt** [comment]
如果谁有 arm 架构的环境可以测试的话，可以在下面回复自己的 QQ，方便我们加好友联系测试

**Comment by allMagicNB** [comment]
> 如果谁有 arm 架构的环境可以测试的话，可以在下面回复自己的 QQ，方便我们加好友联系测试

@LTCatt 你可以尝试找玩**WOA**(Windows On Android)的，那些基本都是arm64架构的安卓设备安装Windows系统的。举个例子，B站搜**某贼**

**Comment by rumengchuxing062** [comment]
> 如果谁有 arm 架构的环境可以测试的话，可以在下面回复自己的 QQ，方便我们加好友联系测试

用qemu试试（雾）

**Comment by allMagicNB** [comment]
> > 如果谁有 arm 架构的环境可以测试的话，可以在下面回复自己的 QQ，方便我们加好友联系测试
> 
> 用qemu试试（雾）

QEMU改变不了架构吧.jpg

**Comment by rumengchuxing062** [comment]
> 如果谁有 arm 架构的环境可以测试的话，可以在下面回复自己的 QQ，方便我们加好友联系测试

QEMU支持模拟arm和arm64架构的说
话说PCL支持arm64吗的说

**Comment by allMagicNB** [comment]
找到人了，QQ号：1330250642
下午4:30💰有空

**Comment by allMagicNB** [comment]
找到人了，QQ号：1330250642
下午4:30前可能没时间

**Comment by rumengchuxing062** [comment]
> > > 如果谁有 arm 架构的环境可以测试的话，可以在下面回复自己的 QQ，方便我们加好友联系测试
> > 
> > 用qemu试试（雾）
> 
> QEMU改变不了架构吧.jpg

QEMU实现原理是软件模拟CPU，操作都是软件处理，我的想法是用QEMU运行，使单个软件的运行环境变成arm64架构

**Comment by allMagicNB** [comment]
> > > > 如果谁有 arm 架构的环境可以测试的话，可以在下面回复自己的 QQ，方便我们加好友联系测试
> > > 
> > > 用qemu试试（雾）
> > 
> > QEMU改变不了架构吧.jpg
> 
> QEMU实现原理是软件模拟CPU，操作都是软件处理，我的想法是用QEMU运行，使单个软件的运行环境变成arm64架构

已经找到人了，没事了，而且还是真实的arm64架构CPU

**Comment by allMagicNB** [comment]
> 他的显卡不支持 OpenGL，压根开不了 MC……
> 不过看起来 Java 已经正常启动了，没有复现出来
> @allMagicNB 

确实哦，安卓设备GPU没必要支持OpenGL……

**Comment by Colin130716** [comment]
同问题，启动游戏时错误日志内容显示
`jlw: native file exists: 'C:\Users\qsdwindows\AppData\Roaming\PCL\libjlw-1.3.2.dll'.
jlw: native file checked.
jlw: existing native file 'C:\Users\qsdwindows\AppData\Roaming\PCL\libjlw-1.3.2.dll' failed to load, trying to overwrite.
jlw: releasing native file to 'C:\Users\qsdwindows\AppData\Roaming\PCL\libjlw-1.3.2.dll'.
Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\qsdwindows\AppData\Roaming\PCL\libjlw-1.3.2.dll: %1 不是有效的 Win32 应用程序。
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1937)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1822)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at oolloo.jlw.ArgLoader.loadNative(ArgLoader.java:122)
	at oolloo.jlw.ArgLoader.<init>(ArgLoader.java:19)
	at oolloo.jlw.Wrapper.main(Wrapper.java:24)`
游戏版本1.8.9
java版本自动选择
尝试改变Java版本为jdk8u392-b08-jre，成功启动

**Comment by 00ll00** [comment]
> 同问题，启动游戏时错误日志内容显示 `jlw: native file exists: 'C:\Users\qsdwindows\AppData\Roaming\PCL\libjlw-1.3.2.dll'. jlw: native file checked. jlw: existing native file 'C:\Users\qsdwindows\AppData\Roaming\PCL\libjlw-1.3.2.dll' failed to load, trying to overwrite. jlw: releasing native file to 'C:\Users\qsdwindows\AppData\Roaming\PCL\libjlw-1.3.2.dll'. Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\qsdwindows\AppData\Roaming\PCL\libjlw-1.3.2.dll: %1 不是有效的 Win32 应用程序。 at java.lang.ClassLoader$NativeLibrary.load(Native Method) at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1937) at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1822) at java.lang.Runtime.load0(Runtime.java:809) at java.lang.System.load(System.java:1086) at oolloo.jlw.ArgLoader.loadNative(ArgLoader.java:122) at oolloo.jlw.ArgLoader.<init>(ArgLoader.java:19) at oolloo.jlw.Wrapper.main(Wrapper.java:24) ` 游戏版本1.8.9 java版本自动选择 pcl版本2.6.13，最新 尝试改变Java版本为jdk8u392-b08-jre，成功启动 emmm...pcl背大锅（

这个可能是因为使用了32位的java，但是wrapper识别成64位了。

需要确认一下触发这个bug的java是否是32位。

（新的bug增加了🤦‍♂️）

**Comment by LTCatt** [comment]
@Colin130716 可以提供一下 QQ 以便测试么

**Comment by 00ll00** [comment]
改用 zig 编译 jni 库，去除了对 VCRUNTIME 等东西的依赖，经热心群友测试大概是修好了🎉

[更新wrapper](https://github.com/00ll00/java_launch_wrapper/releases/tag/v1.4.0)🌹
