### ISSUE TITLE
“清理游戏垃圾”按钮在被禁用后关闭游戏后也无法点击

### ISSUE THREAD

**Issue by zfn-star** [Hex-Dragon/PCL2#1109]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如题

### 重现步骤

1、点击“清理游戏垃圾”按钮(确保游戏已打开)
2、关闭游戏，再次点击“清理游戏垃圾”按钮,可以发现无法点击

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10555963/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10555964/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10555965/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10555966/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10555967/Log1.txt)

**Comment by LTCatt** [comment]
与 #1040 重复
