### ISSUE TITLE
更新自定义主页Event

### ISSUE THREAD

**Issue by LTDove** [Hex-Dragon/PCL2#1112]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

希望能增加:刷新音乐 背景图片 版本设置等Event
方便整合包作者更好为用户提供帮助

### 原因

这项优化让我可以更方便地使用PCL2。
如果没有这项优化，我每次都必须多次点击按钮而有了新Event能一键更改(你不觉得很方便吗.jpg，让操作变得很麻烦。

**Comment by LTDove** [comment]
主要是为了方便.....

**Comment by youzi-2333** [comment]
已初步确认，感谢您的反馈~

**Comment by LTCatt** [comment]
适用面不大，算了……
