### ISSUE TITLE
PCL2特别提供的远古版本无法正常下载安装

### ISSUE THREAD

**Issue by idomoy** [Hex-Dragon/PCL2#1125]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

尝试下载PCL2里面几个有“特别提供”标识的远古版本时，下载进度总是卡在某个位置不动，有时会报错称我的网络质量不佳，但下载其他不是特供的远古版本则没有问题。连接VPN后也不能正常下载。

### 重现步骤

1、点击下载/自动安装/远古版
2、下载一个有[PCL2特别提供]标识的远古版本

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10575247/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10575248/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10575249/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10575251/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10575252/Log5.txt)

**Comment by youzi-2333** [comment]
成功复现，感谢您的反馈~

我 Ping 了一下 `assets.minecraft.net`，同样无法解析服务器，换成 `resources.download.minecraft.net` 报 404……

**Comment by z0z0r4** [comment]
下载原版 b1.9-pre6失败
你的网络环境不佳，导致难以连接到服务器。请检查网络，多重试几次，或尝试使用 VPN。
————————————
详细错误信息：
→ 下载原版支持库文件失败
→ 下载原版支持库文件（副加载器）失败
→ 文件下载失败：D:\Minecraft\.minecraft\versions\b1.9-pre6\b1.9-pre6.jar
基础连接已经关闭: 发送时发生错误。（https://assets.minecraft.net/1_9-pre6/minecraft.jar）
→ 基础连接已经关闭: 发送时发生错误。
→ 由于远程方已关闭传输流，身份验证失败。
   在 PCL.ModNet.NetFile.Thread(NetThread Info)
错误类型：System.IO.IOException

**Comment by z0z0r4** [comment]
> 成功复现，感谢您的反馈~
> 
> 我 Ping 了一下 `assets.minecraft.net`，同样无法解析服务器，换成 `resources.download.minecraft.net` 报 404……

因为可能根本不存在这个jar...

**Comment by z0z0r4** [comment]
没记错的话这些得去龙猫的CDN上面拿，现实情况就是拿到的链接有点抽象...

**Comment by youzi-2333** [comment]
雀氏要去 CDN 下载，所以等龙猫修吧（

**Comment by idomoy** [comment]
能给个活跃橙吗
2398-9765-E9EF-2784

**Comment by LTCatt** [comment]
你的解锁码：maogcvibaq53KRzQo7KKV4jX004gYJQ/
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
