### ISSUE TITLE
用PCL下载的1.17.1带Forge版本无法正常运行

### ISSUE THREAD

**Issue by Vism1** [Hex-Dragon/PCL2#1127]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

游戏能打开，并无报错或崩溃，所以没有日志可以提供（恼）（我也想它能够报错，这样多省事啊，省得我描述起来这么麻烦）

### 我尝试了以下几种情况：

1. 用PCL下载1.17.1-Forge_37.1.0-Optifine_H1版本，能打开并创建世界，创建世界时选择**允许作弊**，打开世界后却发现**无法正常使用作弊指令** *，点击**保存并退回到标题界面**后就一直**卡在保存界面** **，也不报错也不崩溃，点关闭窗口(右上角的×)没有反应，只能在PCL界面点关闭Minecraft才能关闭。
-另外我用HMCL打开这个版本会报错 ***，不知道这个要不要提供给你们。

2.  用PCL下载1.17.1-Forge_37.1.0版本，情况同上。
3.  用PCL下载1.17.1-Optifine_H1版本，能正常运行，以上问题都没有出现，HMCL也能运行这个版本。
4.  用PCL下载1.17.1原版，能正常运行，以上问题都没有出现，HMCL也能运行这个版本。
5. 用**HMCL**下载1.17.1-Forge_37.1.0-Optifine_H1版本，用HMCL能正常运行，用PCL运行时，出现了和运行PCL自己下载的同版本出现的一样的问题。

### 以下是配图：
*![image](https://user-images.githubusercontent.com/124331925/216520302-1d81f25a-35d7-42d3-abf6-9e4b327b465e.png)
只能使用这些指令，就跟关了作弊是一样的

**![image](https://user-images.githubusercontent.com/124331925/216521013-6454a144-8d7d-4c08-aefe-2bfa8a463d6f.png)

***![image](https://user-images.githubusercontent.com/124331925/216523599-c92d1f52-f55a-490a-b6aa-f520ede52752.png)
HMCL的报错

### 重现步骤

下载1.17.1带Forge的版本

### 日志与附件

似乎没有包含错误信息的文件

**Comment by WForst-Breeze** [comment]
我这里无法复现qwq……如果可以的话请提供触发此问题的**游戏日志文件**（在游戏目录中的 logs 文件夹里）、**HMCL 崩溃报告等日志文件**。或者尝试补全文件是否可以解决此问题？感谢反馈
![image](https://user-images.githubusercontent.com/110760354/216526192-d0ac27e5-1be7-457d-8673-6a2eade65430.png)

**Comment by youzi-2333** [comment]
1. 请再次确认是否开启了作弊，无法复现；退出游戏我也是正常的；用 HMCL 打开崩溃的话，请把 Issue 交到 HMCL 储存库；
2. 同上；
3. 既然单独 Optifine 能跑起来，可能是 Forge 与 Optifine 不兼容（？）；
4. 不说了；
5. 我记得以前也有一个 Issue 说 HMCL 下的版本 PCL2 无法启动，找不着了（）

**Comment by Vism1** [comment]
> 我这里无法复现qwq......如果可以的话请提供触发此问题的游戏日志文件（在**游戏**目录中的 logs 文件夹里）、**HMCL 崩溃报告等日志文件**。或者尝试补全文件是否可以解决此问题？感谢反馈 ![image](https://user-images.githubusercontent.com/110760354/216526192-d0ac27e5-1be7-457d-8673-6a2eade65430.png)

那里面貌似是空的；HMCL崩溃报告倒是有；补全文件不能解决问题
[minecraft-exported-crash-info-2023-02-03T18-49-35.zip](https://github.com/Hex-Dragon/PCL2/files/10578183/minecraft-exported-crash-info-2023-02-03T18-49-35.zip)

**Comment by LTCatt** [comment]
这应当不是启动器导致的问题，所以无法修复。

**Comment by Vism1** [comment]
@LTCatt @youzi-2333 等一下，现在有了新的发现，就是如果我选择微软登录启动的话，就能正常运行。你们有没有试过离线启动来复现这个情况？

**Comment by youzi-2333** [comment]
搞得好像我有钱买微软账户似的（划）
我本来就是离线……

**Comment by Vism1** [comment]
好吧，那似乎又是无解了
