### ISSUE TITLE
拖拽安装 Mod 时不会选择适合的版本

### ISSUE THREAD

**Issue by zhoujy1209** [Hex-Dragon/PCL2#1131]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

将Mod自动保存至对应的文件夹内，否则一些新手可能不会添加

**Comment by youzi-2333** [comment]
已经有了……
详见 https://github.com/Hex-Dragon/PCL2/issues/721#issuecomment-1365804102 ，PCL2 会优先把 Mod 存到您在启动页里面选择的版本，如果版本不兼容，则会尝试存到兼容的版本里面。感谢您的反馈~

**Comment by WForst-Breeze** [comment]
反馈者是否指的是**拖拽安装 mod 时**自动选择与之兼容的游戏版本？🤔

**Comment by youzi-2333** [comment]
en，应该是的（）
抱歉.jpg

**Comment by zhoujy1209** [comment]
是的

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年2月3日 15:41
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [Hex-Dragon/PCL2] 将Mod自动保存至对应的文件夹内 (Issue #1131)


反馈者是否指的是拖拽安装 mod 时自动选择与之兼容的游戏版本？🤔

**Comment by ZHAOSBC** [comment]
建议自动选择的时候要弹窗提示，如果选择的版本不对可以手动选择

**Comment by youzi-2333** [comment]
我觉得顶多加一个兼容性警告，要是自动选择的时候弹窗提示就有点复杂了（

**Comment by LTCatt** [comment]
拖拽安装的 Mod 文件 PCL 无法 **准确** 判断它到底支持哪些版本，所以也没法自动选择 =。=
