### ISSUE TITLE
无法启动pcl2

### ISSUE THREAD

**Issue by makabaka-andy** [Hex-Dragon/PCL2#1138]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我的pcl2 3天前用的是2.3版本，今天打开提示未知错误，更新到最新版本也是一样提示，管理员打开也试过
![image](https://user-images.githubusercontent.com/97527014/216579281-980c7f3c-1d62-489f-b8c1-9ec09f184859.png)
作者大大快快解决，谢谢！

### 重现步骤

1、管理员打开pcl2
2、提示错误

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10578042/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10578044/Log2.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10578048/Log5.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10578047/Log4.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10578077/Log3.txt)

**Comment by HamsterYrc** [comment]
1、改成unicode？
2、提升用户权限

**Comment by youzi-2333** [comment]
这不是 PCL2 的问题。
请尝试右键 PCL2 并以管理员身份运行，或者打开 F:\安装包\PCL2 文件夹属性，安全，将 Everyone 的访问级别设为完全控制再试，感谢您的反馈～

**Comment by makabaka-andy** [comment]
这两位的我都试过的，还是不行，之前好好的，今天就开始了

**Comment by makabaka-andy** [comment]
> 1、改成unicode？ 2、提升用户权限

不行啊

**Comment by youzi-2333** [comment]
我这边没法复现…（
把 PCL2 换个位置试试？如果还是不行就重开.jpg

**Comment by youzi-2333** [comment]
既然前几次可以记录 Log，说明它本来应该挺好的，就是后面出了问题（

**Comment by makabaka-andy** [comment]
后面过几天又自己好了，真是玄学
