### ISSUE TITLE
1.19.3根本无法下载

### ISSUE THREAD

**Issue by HamsterYrc** [Hex-Dragon/PCL2#1139]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

当你的pcl的上级文件夹为Minecraft时无法下载

### 重现步骤

1、pcl上级文件夹改成Minecraft
2、下载1.19.3原版
3、它就会发现文件夹重名…………

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10578087/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10578089/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10578090/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10578091/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10578092/Log1.txt)
![image](https://user-images.githubusercontent.com/109511472/216581653-bf01f71b-a949-4e07-b1a2-1c1cd6aa8870.png)

**Comment by youzi-2333** [comment]
既然您本来就有一个名字叫做 1.19.3 的版本了，那么当然和已有文件夹重复了.jpg
请尝试将版本名改为别的名称，然后重试。一般不建议修改 PCL2 自动生成的版本名……

**Comment by HamsterYrc** [comment]
我原版的忘记截图了…………

**Comment by HamsterYrc** [comment]
<img width="553" alt="image" src="https://user-images.githubusercontent.com/109511472/216601651-0c5d6075-5bd2-4723-98d7-54ade5ac4b64.png">
？？？？？？？？

**Comment by HamsterYrc** [comment]
wc，这是官启文件夹
