### ISSUE TITLE
增加游戏日志导出

### ISSUE THREAD

**Issue by cdy2012** [Hex-Dragon/PCL2#1144]
### 检查项

- [x] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

建议增加导出游戏日志按钮。

### 原因

有时游戏突然崩溃，pcl没有自动导出崩溃报告，导致了无法报告bug。

**Comment by youzi-2333** [comment]
已初步确认，感谢您的反馈~

**Comment by LTCatt** [comment]
原反馈者已经 Close 了为啥还要把它 Reopen 回来……

**Comment by youzi-2333** [comment]
草，还以为他点错了，抱歉抱歉…
