### ISSUE TITLE
打开PCL时背景变白

### ISSUE THREAD

**Issue by Skibleminecraft** [Hex-Dragon/PCL2#1145]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

没设置任何背景时 打开PCL 背景可能变成白色

### 重现步骤

1. 直接打开
2. 观察背景
3. 变白了

### 日志与附件

[Uploading Log2.txt…]()

**Comment by youzi-2333** [comment]
先提醒一句，Log2 没传上来（）

**Comment by youzi-2333** [comment]
还有一种可能性就是内存不足，Windows 决定不加载某些控件以节省内存，就加载不出背景了……

**Comment by 212112111zwl** [comment]
是不是把个性化里的彩色背景关了？

**Comment by youzi-2333** [comment]
请确认是否关闭了彩色背景；如果没有关闭，请上传 Log 与截图。长时间不回复的 Issue 会被关闭，感谢配合。

**Comment by LTCatt** [comment]
已经两周了，先关了，有需要可以在这里继续回复（

**Comment by Cai-kunkun** [comment]
好臭的issue

**Comment by BarbTurnip437** [comment]
搜issue号过来的
