### ISSUE TITLE
让 千万别点 更加好玩

### ISSUE THREAD

**Issue by YUANXINGlingyun** [Hex-Dragon/PCL2#1147]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

让 更多-千万别点 的 癫痫概率 和 Rickroll 概率更大一点

### 原因

看看 Discussions #1141

**Comment by WForst-Breeze** [comment]
已初步确认，感谢您的反馈~
原始 Discussion：#1141

**Comment by YUANXINGlingyun** [comment]
为啥不让 千万别点 更加的奇怪呢？
