### ISSUE TITLE
建议将Pcl2内测版中的-更多-反馈的内容变更为github上的反馈

### ISSUE THREAD

**Issue by CakeSakura** [Hex-Dragon/PCL2#115]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

我是真的建议龙猫大大改掉这个玩意，免得一些人太无聊，整这些东西对PCL2造成影响
![V DTDSNAXNMW7MJ 70FJ$PF](https://user-images.githubusercontent.com/109448772/183244387-5a67cbd1-e4a5-4db9-8851-040d55352f88.png)
![F}PVH)781LFGAMW1SNF88JE](https://user-images.githubusercontent.com/109448772/183244392-1df28f51-c200-48eb-b3cd-0a9c827222a3.png)

### 原因

这项优化是为了避免某些人利用旧版的反馈地址发表不正当言论后映射到pcl2中的反馈列表
因为已经有些人开始了这个想法，具体图片在描述中

**Comment by CakeSakura** [comment]
这些东西是我无意中看到的，证明有的人能无聊到什么程度，没有下限

**Comment by WTP016-CN** [comment]
![ADBD79AB-A59F-4F33-8E01-F7EDA5BFCB33](https://user-images.githubusercontent.com/66893541/183244475-5b9fb8b2-12e8-4d39-971b-ee5e036f319d.png)
已有相关计划，无需重复提交反馈。

**Comment by Big-Cake-jpg** [comment]
hmmmm，实在不知道这个 Issue 到底该打甚么 label（

**Comment by Big-Cake-jpg** [comment]
@WTP016-CN 不应该 Closed as completed 吧......

**Comment by CakeSakura** [comment]
huh

**Comment by WTP016-CN** [comment]
> @WTP016-CN 不应该 Closed as completed 吧......

但是我觉得 as not planned 也不行 毕竟这有计划（）

**Comment by CakeSakura** [comment]
那应该....?

**Comment by WTP016-CN** [comment]
先不管了，就这样吧（摆

**Comment by Big-Cake-jpg** [comment]
> 但是我觉得 as not planned 也不行 毕竟这有计划（）

Not planned 确实适用于重复的 Issue

**Comment by CakeSakura** [comment]
hhhhhhhhhhc

**Comment by WTP016-CN** [comment]
> > 但是我觉得 as not planned 也不行 毕竟这有计划（）
> 
> Not planned 确实适用于重复的 Issue

好的 知道了（

**Comment by LTCatt** [comment]
> @WTP016-CN 不应该 Closed as completed 吧......

不要自己去 Close，只需要添加对应的标签，伯特会自动去处理的……
并且这个应该加无效，它没有和其他反馈重复（

**Comment by WTP016-CN** [comment]
> > @WTP016-CN 不应该 Closed as completed 吧......
> 
> 不要自己去 Close，只需要添加对应的标签，伯特会自动去处理的…… 并且这个应该加忽略，它没有和其他反馈重复（

好的（）
