### ISSUE TITLE
在设置里添加对minecraft启动数量的限制

### ISSUE THREAD

**Issue by iPodtouch6557** [Hex-Dragon/PCL2#1150]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

首先，在设置里添加一个标签页，就是可以设置总多开限制数量，1到几到无限都可以（有些人可能比较依赖多开功能）同时单版本也要添加这个限制（具体怎么互相适配用你的脑子自己想），同时这个无法使用游戏单独的设置
这是大概的框架，我就讲这么细，要我补充了再叫我

### 原因

这项优化可以让我的lj电脑卡不死（）
minecraft对我来说非常占内存，随便开一个内存都可以到60%~70%，有时我会意外的无法关闭minecraft（就像#1094），这样就可以避免（***

**Comment by WForst-Breeze** [comment]
已初步确认，感谢您的反馈~
（不过我觉得此建议被采纳的概率不大……要是说您的意思是要是要**避免启动游戏后内存不足导致的一系列问题**的话，我个人认为可能就……加一个 **"内存不足是否继续启动？"** 的询问弹窗就应该足够了

**Comment by iPodtouch6557** [comment]
> 已初步确认，感谢您的反馈~ （不过我觉得此建议被采纳的概率不大......要是说您的意思是要是要**避免启动游戏后内存不足导致的一系列问题**的话，我个人认为可能就......加一个 **"内存不足是否继续启动？"** 的询问弹窗就应该足够了

有点道理，但与我的想象背道而驰（就是那种问题若有若无
所以我认为就看龙猫怎么想的了，因为你说的也不是不可以（）

**Comment by LTCatt** [comment]
你已经开了一个就别再开第二个了啊……

**Comment by iPodtouch6557** [comment]
> 你已经开了一个就别再开第二个了啊......

不是，啥意思？我没懂啊…………………………
