### ISSUE TITLE
允许在下载准备页面更改版本描述

### ISSUE THREAD

**Issue by ComputerCPT** [Hex-Dragon/PCL2#1151]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

如标题，可加在版本名称一栏下方

### 原因

这项优化让我可以更方便地更改版本描述

**Comment by YUANXINGlingyun** [comment]
好主意，加入待处理吧

**Comment by WForst-Breeze** [comment]
已初步确认，感谢您的反馈~

**Comment by LTCatt** [comment]
与 #1066 实质重复

**Comment by dargoncat** [comment]
反馈者指的是不是**在mc安装预览界面更改版本描述**？
![QQ截图20230205220722](https://user-images.githubusercontent.com/121101691/216824358-194ba00c-8690-47de-99da-8900eddcee6d.png)
![QQ截图20230205220842](https://user-images.githubusercontent.com/121101691/216824371-66fe60dc-af9a-45d9-a12f-1a54e1f704a9.png)

**Comment by youzi-2333** [comment]
> 反馈者指的是不是**在mc安装预览界面更改版本描述**？

我也感觉是这样的.jpg

**Comment by dargoncat** [comment]
> > 反馈者指的是不是**在mc安装预览界面更改版本描述**？
> 
> 我也感觉是这样的.jpg

要不reopen看看龙猫怎么说?

**Comment by youzi-2333** [comment]
刑，先开了再说（

**Comment by LTCatt** [comment]
知道意思了……额……但在下载页面再加一个框也不咋简洁，所以……抱歉 orz
