### ISSUE TITLE
启动器更新问题

### ISSUE THREAD

**Issue by QWXL** [Hex-Dragon/PCL2#1153]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我的PCL2在打开自动更新的时候，并未给我自动进行更新（也没有要求我提供更新秘钥），需要手动检查更新。

### 重现步骤

有新更新时就会触发这个问题，问题似乎是必然的。

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10774721/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10774722/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10774723/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10774724/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10774725/Log5.txt)

已经补充问题发生时的Logs。

**Comment by YUANXINGlingyun** [comment]
正式版吗

**Comment by QWXL** [comment]
测试最新版

**Comment by LTCatt** [comment]
等到下次更新传当时的 log 吧……

**Comment by iPodtouch6557** [comment]
> 等到下次更新传当时的 log 吧......

（_所以你快更新_）我偶尔也会遇到这个情况，就是自动更新不好使，得手动官网下载的
但是我大半年前就没这问题了，有可能是你自身的问题，比如下载任务被拦截等等

**Comment by QWXL** [comment]
自动更新检测后会发起下载任务，如果下载被拦截应该会报错的，但是连错误也没有提示

**Comment by iPodtouch6557** [comment]
> 自动更新检测后会发起下载任务，如果下载被拦截应该会报错的，但是连错误也没有提示

有没有可能在断网时碰上自动更新，结果导致更新无法完成，就再也不检测本次更新了？？？

**Comment by QWXL** [comment]
不现实，我开pcl2的之前习惯先开浏览器看看视频什么的，QQ也是开机自启，肯定是有网络环境下的

**Comment by iPodtouch6557** [comment]
> 不现实，我开pcl2的之前习惯先开浏览器看看视频什么的，QQ也是开机自启，肯定是有网络环境下的

撒个啊？你还有这个好习惯啊？？？那我就帮你到这了……

**Comment by z0z0r4** [comment]
哥们发log，别在issue聊天了

**Comment by iPodtouch6557** [comment]
（不是我聊啥了，分析错误原因没错吧我又不是发issue的人）

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: z0z0r4 ***@***.***>
发送时间: Saturday, February 11, 2023 10:02:12 AM
收件人: Hex-Dragon/PCL2 ***@***.***>
抄送: 刘宇儿 ***@***.***>; Comment ***@***.***>
主题: Re: [Hex-Dragon/PCL2] 启动器更新问题 (Issue #1153)


哥们发log，别在issue聊天了

―

**Comment by QWXL** [comment]
把logs补了，来个人看看

**Comment by youzi-2333** [comment]
不对啊，Log 中还是没有发现问题（）
[2.4.8 下载链接](https://fasthub.cc/Hex-Dragon/PCL2/raw/64539ad55c8341045ea8aa2cd255e0ccb9049686/%E6%9C%80%E6%96%B0%E6%AD%A3%E5%BC%8F%E7%89%88.zip) 请使用这个版本再次尝试更新，如果没问题就关掉吧……有问题就传 Log……

**Comment by QWXL** [comment]
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10776306/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10776307/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10776308/Log3.txt)
问题的确有，在我打开启动器的时候没有向我自动推送更新，只有在我手动检查更新的时候才更新

**Comment by LTCatt** [comment]
只会在有新版本更新的时候一次性触发，这一次之后就不会自动推送了（
