### ISSUE TITLE
导出错误报告失败：复制文件出错（未能找到文件 LatestLaunch.bat）

### ISSUE THREAD

**Issue by doushaTV** [Hex-Dragon/PCL2#1155]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃不是 PCL2 的原因，请 **不要** 提交反馈。你可以在 QQ 群里或者论坛找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是游戏本身的问题，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10608536/Log1.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10608547/Log1.txt)

### 错误报告、日志与附件

pcl2让我反馈的### _****_
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10608541/Log1.txt)

**Comment by LTCatt** [comment]
导出错误报告失败：复制文件出错：C:\Users\*\Desktop\PCL\LatestLaunch.bat -> C:\Users\*\AppData\Local\Temp\PCL\CrashAnalyzer\694420011771\Report\启动脚本.bat
→ 未能找到文件“C:\Users\*\Desktop\PCL\LatestLaunch.bat”。
   在 PCL.ModBase.CopyFile(String FromPath, String ToPath)
   在 PCL.CrashAnalyzer.Output(Boolean IsHandAnalyze, List`1 ExtraFiles)
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   在 PCL.ModBase.CopyFile(String FromPath, String ToPath)
错误类型：System.IO.FileNotFoundException

**Comment by youzi-2333** [comment]
应该是在启动游戏后删除了 `C:\Users\牛梦迪\Desktop\PCL\LatestLaunch.bat` 或 `C:\Users\牛梦迪\Desktop\PCL`。

既然删掉这个文件会发生错误，那么应该可以修一修……感谢您的反馈~

**Comment by YUANXINGlingyun** [comment]
？还有这样的？
