### ISSUE TITLE
建议在自动安装的版本预览页面添加”返回“或”上一级“按钮

### ISSUE THREAD

**Issue by sunlogo-soto** [Hex-Dragon/PCL2#1157]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

**建议在自动安装的版本预览页面添加“返回“或”上一级“按钮**

### 原因

PCL2的自动安装界面中一旦选择版本就无法直接返回到下载版本选择画面。
这就导致**一旦选择错版本只能刷新**_（有的时候网有点卡还半天都刷新不出来×）_。
建议在”安装预览“卡片的上部或者其他合适的位置**添加”返回“或者“上一级”按钮以降低操作的复杂度**。

**Comment by YUANXINGlingyun** [comment]
？你是不是没注意到 Minecraft 选项右边有个箭头

**Comment by sunlogo-soto** [comment]
> ？你是不是没注意到 Minecraft 选项右边有个箭头

az 不好意思这个确实没注意到
不过还是建议更改一下外观qwq...

**Comment by WForst-Breeze** [comment]
其实是可以直接回到主界面的qwq……已初步确认，感谢您的反馈~
![image](https://user-images.githubusercontent.com/110760354/216799075-835cb310-87c5-4755-a39f-22429fa6452a.png)

**Comment by FangFuJi1991** [comment]
感觉可以，不知道怎么返回的人可以按返回键

**Comment by idomoy** [comment]
虽然可以返回，但这个按钮的设计确实容易忽视或者误解，可以改一下

**Comment by YUANXINGlingyun** [comment]
在确认下载的按钮边上加个返回按钮，就跟点击Minecraft右边箭头同一个效果

**Comment by iPodtouch6557** [comment]
确实，我一般直接点自动安装按钮回去，第一次知道的时候找了老半天才发现（）
建议参考部分其他软件公司的ui设计，比如苹果

**Comment by LTCatt** [comment]
![image](https://user-images.githubusercontent.com/40348278/222892076-5b4f2891-fc8b-4f97-ab4d-079bf812d8ad.png)

**Comment by iPodtouch6557** [comment]
好耶~
