### ISSUE TITLE
建议添加不同方向的任务栏和折叠任务栏按钮 

### ISSUE THREAD

**Issue by iPodtouch6557** [Hex-Dragon/PCL2#1164]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

1*可不可以像windows那样可以调整任务栏在窗口的哪一边，就像这个设置
<img width="314" alt="捕获" src="https://user-images.githubusercontent.com/118656946/216810630-8fcbb76a-1c3d-4555-87dd-12e86e45d25a.PNG">
2*可不可以添加类似于windows的开始按钮，折叠所有可用标签页，要用了点一下就开，甚至可以智能关闭（具体怎么关闭可以随你便）

### 原因

第一个就闲的，为了贴合第二条搞的，不改也行……
第二个就是我觉得不应该允许用户可以极其方便地在两个层级的交互按键进行跨层级操作，比如你在下载标签页下载东西，结果这个ui允许你用着用着直接跳到主页，而允许你把没做完的工作直接扔在那，是不是有点大病（）
所以应当添加一个隔离
其实都闲的，就是一个建议，龙猫是不是要在设计上头下点工夫……（虽然我知道你不一定有时间

**Comment by YUANXINGlingyun** [comment]
改成新功能label吧，貌似好多东西的样子

**Comment by WForst-Breeze** [comment]
> 改成新功能label吧，貌似好多东西的样子

个人认为暂时不做调整（）第二条有点倾向于新功能，但是整体讲还是偏向于对操作形式设计上的优化

**Comment by idomoy** [comment]
说实话第2条看不太懂...

**Comment by iPodtouch6557** [comment]
> 说实话第2条看不太懂...

本来嘛，装个*（doge）
我总结能力有限，就能说这么清楚了（）

**Comment by LTCatt** [comment]
`我觉得不应该允许用户可以极其方便地在两个层级的交互按键进行跨层级操作`
方便点有啥不好呢？
