### ISSUE TITLE
"删除游戏垃圾“按键仅会删除.minecraft下的日志文件，对开启版本隔离的游戏日志文件不起作用

### ISSUE THREAD

**Issue by CN171-1** [Hex-Dragon/PCL2#1166]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如题，PCL仅会删除.minecraft下的游戏缓存，对versions里的游戏缓存文件不起作用

### 重现步骤

1、点击"删除游戏垃圾“按键
即可复现

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10611052/Log1.txt)
![开启版本隔离的游戏日志文件](https://user-images.githubusercontent.com/110646806/216820067-e0c11376-b9b6-4362-9ef3-ebb844d50085.png)

**Comment by HamsterYrc** [comment]
api是哪个，我尝试复现

**Comment by youzi-2333** [comment]
似乎复现出来了，但又总感觉哪里不太对劲（）
~~为了保证在 2 天内打上待处理~~，就先等回复吧……

**Comment by CN171-1** [comment]
龙猫啊，能不能给个活跃橙啊.png
识别码是09FB-33D9-583C-5CF7 @LTCatt

**Comment by LTCatt** [comment]
你的解锁码：gyN95zCvE2w/aZj3WAiQMCcn3j1PA/3/
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
