### ISSUE TITLE
Java 兼容性警告异常

### ISSUE THREAD

**Issue by TotemFuture** [Hex-Dragon/PCL2#1167]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

选择java 8 启动1.8.9的mc 出现java兼容性警告 “你在设置中手动指定了使用java 8 但当前需要java 8”

### 重现步骤

启动1.8.9-OptiFine_M5（且所有启动设置均为让PCL自动选择）
PCL自动选择了Java8（8.0.311）
在自动选择8.0.311后
PCL弹出提示
Java 兼容性警告
点击让PCL自动选择后 PCL优先使用了Java8（8.0.332）
（该bug由启动器可用Java数量大于等于2时会复现，高版本正常且Java版本均为Java8 经实测可以稳定复现）

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10611098/Log1.txt)

**Comment by youzi-2333** [comment]
难道 2.4.7 还没修好？
这 Bug 我见过好多次了，死活复现不出……

**Comment by youzi-2333** [comment]
```
[21:04:41.666] [Java] JRE 8 (8.0.332)，64 位：E:\学习资料\信息\windows\PCL2\.minecraft\jre\jre8u332b09-windows-x64\bin\
[21:04:41.673] [Java] 检查后找到 1 个特定目录下的 Java
[21:04:41.673] [Java] 发现用户指定的不兼容 Java：JRE 8 (8.0.311)，64 位：E:\Java\bin\
[21:04:41.776] [Control] 普通弹窗：Java 兼容性警告
你在设置中手动指定了使用 Java 8，但当前需要 Java 8。
如果强制使用该 Java，可能会导致出现异常。

 - 指定的 Java：JRE 8 (8.0.311)，64 位：E:\Java\bin\
```
估计是 JRE 的问题……不过我卸了所有 Java，就留了 JRE 8，还是无法复现……

**Comment by LTCatt** [comment]
没法复现，加下我的 QQ 1043137532？

**Comment by CN171-1** [comment]
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10942911/Log1.txt)
我是发现这个bug的人，这个反馈是我朋友想要一个活跃橙而送他的，上面是在PCL2 2.5.1下开启调试模式的log文件

**Comment by CN171-1** [comment]
补充：设置页面中”游戏Java“的设置为”自动选择合适的 Java “
           且版本设置中的所有设置均为”使用全局设置“

**Comment by CN171-1** [comment]
![image](https://user-images.githubusercontent.com/110646806/224733456-f337f037-e9e3-454f-ba62-75807c3b9b24.png)
顺带一提，现在的bug已经到达了离谱的境界，在2.5.1之前只会有1.8.9有这个问题，换上2.5.1后《其他版本也会有这个提示了》

**Comment by CN171-1** [comment]
![image](https://user-images.githubusercontent.com/110646806/224734048-e41b67de-5059-4831-a77b-fad2ccda3c40.png)
Like this....

**Comment by CN171-1** [comment]
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10962902/Log2.txt)
附日志
更离谱的是，当我在全局设置中的“游戏Java”设置中在已经选择了”让PCL2自动选择“的时候，再点击一次”让PCL2自动选择“（未点击其他Java版本），这个bug竟然神奇般的消失了，此后我再也不能复现该bug了（这个情况也在上面的日志里有记录）
