### ISSUE TITLE
点击左下角的提示后无法隐藏

### ISSUE THREAD

**Issue by youzi-2333** [Hex-Dragon/PCL2#1168]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://fasthub.cc/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

点击左下角提示框无法隐藏提示。

### 重现步骤

1. 随便搞出个提示框出来
2. 点击提示框
3. 无法隐藏提示

### 日志与附件

[见此](https://github.com/Hex-Dragon/PCL2/issues/1168#issuecomment-1418928078)

**Comment by WForst-Breeze** [comment]
我好像没能完全理解您的意思qwq 没能成功复现😢

**Comment by youzi-2333** [comment]
彳亍口巴，一会补 Log（）

大概意思就是，最近添加了个“点击左下角提示框可以隐藏所有提示”功能，但是按照上述方法弄一遍，再点击提示框，就没法隐藏了……

**Comment by youzi-2333** [comment]
https://user-images.githubusercontent.com/106497113/216959470-ddcd3cba-3862-4daa-9ef7-8d459c8a25a7.mp4

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10662472/Log1.txt)

**Comment by youzi-2333** [comment]
突然发现，不仅是关闭 Minecraft，任何 Hint 都无法点击关闭了.jpg
因此 2.4.4 的 [点击左下角的弹出提示会立即隐藏所有提示](https://github.com/Hex-Dragon/PCL2/releases/tag/2.4.4) 功能失效力……

**Comment by WForst-Breeze** [comment]
是不是在 2.4.5 就删了（？）[取消弹出提示的点击手动收回功能](https://github.com/Hex-Dragon/PCL2/releases/tag/2.4.5)

**Comment by youzi-2333** [comment]
《有 道 理》
