### ISSUE TITLE
自定义主页卡片间无法添加间距

### ISSUE THREAD

**Issue by Duck-Deng** [Hex-Dragon/PCL2#117]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

![image](https://user-images.githubusercontent.com/64295725/183251451-6c0988ef-802c-4499-bd92-78a4587388b2.png)
主页的卡片默认没有间距，卡片间是连在一起的

### 原因

这项优化让主页更加美观。
如果没有这项优化，卡片是连在一起的，不太好看。

**Comment by WTP016-CN** [comment]
请参考帮助库内的 XAML 格式手动设置。
