### ISSUE TITLE
更改pcl2常见问题于爱发电的链接

### ISSUE THREAD

**Issue by HamsterYrc** [Hex-Dragon/PCL2#1173]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

shimowendang.com变成shimo.im

### 原因

这项优化让我可以更方便地查看指南。
如果没有这项优化，我每次都必须更改链接，让操作变得很麻烦。

**Comment by LTCatt** [comment]
爱发电里已经改了？没找到你说的在哪^

**Comment by HamsterYrc** [comment]
没改，几天前还是这个
<img width="482" alt="image" src="https://user-images.githubusercontent.com/109511472/217118659-f3fe37bd-9f30-483c-96b9-f15c3f4e7c77.png">

**Comment by LTCatt** [comment]
三天前改了……

**Comment by HamsterYrc** [comment]
……………………







                       
原始邮件
                       
                     

发件人："龙腾猫跃"< ***@***.*** &gt;;

发件时间：2023/2/7 15:06

收件人："Hex-Dragon/PCL2"< ***@***.*** &gt;;

抄送人："HamsterYrc"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [Hex-Dragon/PCL2] 更改pcl2常见问题于爱发电的链接 (Issue #1173)




 
三天前改了……
 
&mdash;
