### ISSUE TITLE
游戏启动崩溃

### ISSUE THREAD

**Issue by zhoujy1209** [Hex-Dragon/PCL2#1174]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃不是 PCL2 的原因，请 **不要** 提交反馈。你可以在 QQ 群里或者论坛找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是游戏本身的问题，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

1.16.5 1.8.9 1.12.2以及他们的Forge版本启动时全部崩溃

### 错误报告、日志与附件

[错误报告-2023-2-6_11.25.11.zip](https://github.com/Hex-Dragon/PCL2/files/10642450/-2023-2-6_11.25.11.zip)
[错误报告-2023-2-6_11.26.07.zip](https://github.com/Hex-Dragon/PCL2/files/10642838/-2023-2-6_11.26.07.zip)
[错误报告-2023-2-6_11.26.31.zip](https://github.com/Hex-Dragon/PCL2/files/10642996/-2023-2-6_11.26.31.zip)
以上都是原版Minecraft
[错误报告-2023-2-6_11.28.58.zip](https://github.com/Hex-Dragon/PCL2/files/10644054/-2023-2-6_11.28.58.zip)
[错误报告-2023-2-6_11.29.15.zip](https://github.com/Hex-Dragon/PCL2/files/10644149/-2023-2-6_11.29.15.zip)
以上是Forge版本

**Comment by youzi-2333** [comment]
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no nio in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1865)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	... 剩余 43 个
```
网上说是 Java 没有找到支持库，多半是 Path 环境变量或 `java.library.path` Property 的设置问题，不过 JVM 安装的时候应该会设置 Path……？

先等消息吧（）

**Comment by LTCatt** [comment]
先确认一下，使用其他启动器是否也会出现该问题？
如果没有，补充一个其他启动器导出的启动脚本……

**Comment by zhoujy1209** [comment]
[1.12.2.zip](https://github.com/Hex-Dragon/PCL2/files/10680928/1.12.2.zip)
[1.16.5.zip](https://github.com/Hex-Dragon/PCL2/files/10680929/1.16.5.zip)
[1.8.9.zip](https://github.com/Hex-Dragon/PCL2/files/10680930/1.8.9.zip)
这些是我用HMCL启动器生成的

**Comment by gyspyw** [comment]
把JAVA卸载重装一下试试看

**Comment by zhoujy1209** [comment]
现在好了，把Java8重装了下
