### ISSUE TITLE
可视化Mod列表出错：已添加具有相同键的项

### ISSUE THREAD

**Issue by LuoFeng2007** [Hex-Dragon/PCL2#1175]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![屏幕截图_20230206_165244](https://user-images.githubusercontent.com/124565574/216928503-51edac1d-f056-4c01-bc85-a4229607edaf.png)

### 重现步骤

打开下载mod就会这样

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10661279/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10661280/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10661282/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10661283/Log4.txt)

**Comment by terryaxe** [comment]
啊这
我提交时还没有你这个呢

**Comment by 212112111zwl** [comment]
哦我刚刚也遇到了，还新开了一个issue

**Comment by terryaxe** [comment]
草
蚌埠住了

**Comment by 212112111zwl** [comment]
@LuoFeng2007 建议把反馈标题改一下

**Comment by LuoFeng2007** [comment]
> 

好的，已修改

**Comment by WForst-Breeze** [comment]
在刚刚推送的 Release/Snapshot 2.4.8 中稳定复现，整合包界面也会出现此问题
![image](https://user-images.githubusercontent.com/110760354/216942212-916c2c27-edc0-4f67-b56b-278964967e29.png)

**Comment by AgustinLin** [comment]
我这边可以通过刷新界面恢复（mod或整合包都可以），恢复后重启启动器可以再次复现

**Comment by 212112111zwl** [comment]
好像是启动后第一次获取 模组 或 整合包 列表都会出现以上问题

**Comment by txs1234** [comment]
遇到了同样的问题

**Comment by 7xcc** [comment]
遇到相同的问题

**Comment by NoclubOIRzXx** [comment]
刚更新完就出现一样的问题
![image](https://user-images.githubusercontent.com/40497676/217058203-dbaa6291-a58a-4ce2-bf9e-6482458c5b6e.png)

**Comment by NoclubOIRzXx** [comment]
刚更新完成就出现一样的问题

![image](https://user-images.githubusercontent.com/40497676/217059231-8e79d37a-4b5d-450f-9a98-78fb83c89c23.png)

![explorer_Ngfm0hNQl4](https://user-images.githubusercontent.com/40497676/217059640-45a908be-58a1-4a83-a139-31ad39a464c7.gif)
