### ISSUE TITLE
PCL 提示可视化mod列表出错

### ISSUE THREAD

**Issue by 212112111zwl** [Hex-Dragon/PCL2#1178]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在搜索mod时出现的错误
刚刚升到2.4.8，更新前从来没有遇到过类似问题（难道是……

具体请见附件
![image](https://user-images.githubusercontent.com/121177845/216936040-4dba6a21-f429-4aab-b641-dce0e664de28.png)

### 重现步骤

不是每次搜索mod都会出现：

打开pcl -> 下载
每次刷新列表时都有几率出现（但概率不大）

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10661594/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10661595/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10661596/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10661597/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10661598/Log5.txt)

**Comment by 212112111zwl** [comment]
刚刚发现与 issue1175 重复了，但我觉得我描述的更详细一点（呵呵），大家看着办

**Comment by terryaxe** [comment]
没毛病

**Comment by 212112111zwl** [comment]
这个issue我先关了，移步到1175说吧

**Comment by WForst-Breeze** [comment]
进一步讨论请移步 #1175
