### ISSUE TITLE
用户协议与免责声明无法使用

### ISSUE THREAD

**Issue by sadbee-wzx** [Hex-Dragon/PCL2#1180]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

石墨文档已拒绝连接

### 重现步骤

1.点击更多
2.选择关注与鸣谢
3.展开法律信息
4.选择用户协议与免责声明

### 日志与附件

[Uploading Log1.txt…]()

**Comment by WForst-Breeze** [comment]
已初步确认问题存在，感谢您的反馈~
