### ISSUE TITLE
可视化MOD列表出错[提供操作方法,与之前的人提交的不一样]

### ISSUE THREAD

**Issue by StarXiyu** [Hex-Dragon/PCL2#1182]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

[18:30:12.279] [Control] 普通弹窗：出现错误
可视化 Mod 列表出错：已添加了具有相同键的项。
   在 PCL.ModDownload.ReleaseCfDatabase()
   在 PCL.ModDownload.DlCfProject.LoginReponse()
   在 PCL.ModDownload.DlCfProject.ToCfItem(Boolean ShowVersionDesc, Boolean ShowLoaderDesc, ClickEventHandler OnClick)
   在 PCL.PageDownloadMod.Load_OnFinish()

### 重现步骤

1.以管理员身份在Powershell中依次运行如下命令（用以解决windows安全中心打不开，其实我是去关防火墙的）：

$BasePath = Get-Content .\appx.list（报错不要管）
$BasePath | % { 
$Path = $($_).Trim() Add-AppxPackage -Register -DisableDevelopmentMode "$Path\AppXManifest.xml"
}

Get-AppxPackage | Select InstallLocation | Out-file appx.list

Add-AppxPackage -Register -DisableDevelopmentMode "C:\Windows\SystemApps\Microsoft.Windows.SecHealthUI_cw5n1h2txyewy\AppXManifest.xml"

2.打开MOD列表

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10662079/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10662080/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10662081/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10662082/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10662094/Log5.txt)

**Comment by LTCatt** [comment]
实质相同，不单独处理
