### ISSUE TITLE
启动前执行命令无法正确结束导致隐藏的僵尸进程

### ISSUE THREAD

**Issue by cxim-xh** [Hex-Dragon/PCL2#1183]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

启动前执行命令无法正确结束导致隐藏的僵尸进程

### 重现步骤

1、在：版本设置》设置》高级启动选项》启动前执行命令 中填写无法正常终止的命令，取消“等待命令执行完成后再继续启动”。
2、启动游戏，点击“关闭Minecraft”
3、命令执行程序未能关闭，并始终处于隐藏状态
4、关闭PCL，该进程仍然存在，且依旧处于隐藏状态

### 日志与附件

![搜狗截图20230206184138](https://user-images.githubusercontent.com/115422429/216952093-77e612b1-8efc-4946-ba7e-357e0935797d.png)

**Comment by youzi-2333** [comment]
~~你闲着没事运行 pause 干嘛~~已确认，感谢您的反馈~

**Comment by cxim-xh** [comment]
> ~你闲着没事运行 pause 干嘛~已确认，感谢您的反馈~

其实pause是为了稳定复现

**Comment by youzi-2333** [comment]
这玩意我也遇到过，但是我没想到会出现僵尸进程……
