### ISSUE TITLE
更新时出现文件重复报错

### ISSUE THREAD

**Issue by Roser7419** [Hex-Dragon/PCL2#1185]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

注：此现象实际上是在 V2.4.7 出现，但未在更新日志内找到相关内容，我也没法在 V2.4.8 再试一次...

具体表现为在 开启自动下载 的情况下，点击了 检查更新 且 确认了进行更新 后，于下载后可能出现报错 "...Desktop\PCL\Plain Craft Launcher 2.exe" 已经存在

在试图更新时此状况仅出现了一次

以及报错的解决方案有点矛盾（）
大抵意思就是
启动器更新失败! 更新启动器可能可以解决该问题...(x

### 重现步骤

* 自动更新选择项目 在有新版本时自动下载
* 2.4.7 -> 2.4.8 更新
在 设置/启动器 检查更新，然后同意下载就好

### 日志与附件

问题 Log 为 Log2
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10662588/Log2.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10662589/Log1.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10662592/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10662593/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10662594/Log5.txt)

**Comment by idomoy** [comment]
今天更新时也遇到了这个情况...
![image](https://user-images.githubusercontent.com/54678032/217221440-c1322228-e381-4dd1-8db7-f820d9ca2db3.png)

**Comment by gyspyw** [comment]
+1,
![image](https://user-images.githubusercontent.com/87260715/217423959-4bbef542-6332-4569-91c2-2d2dd2bcd5bc.png)

**Comment by LTCatt** [comment]
在 2.5.0 中添加了一些调试日志，如果使用 2.5.0 更 gēng 新到更 gèng 新的版本时，又触发了这个问题，希望能重新传个 2.5.0 的日志 =。=

**Comment by LTCatt** [comment]
由于暂时无人复现，先关闭这个 issue，如果有人复现了可以继续回复。
