### ISSUE TITLE
未将对象引用设置至对象的实例

### ISSUE THREAD

**Issue by ThelevenFD** [Hex-Dragon/PCL2#1189]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

选择自动选择java选项时启动会出现“未将对象引用至对象的实例“

### 重现步骤

1.随意选择一个游戏版本
2.选择java，点自动选择

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10663668/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10663671/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10663672/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10663673/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10663674/Log1.txt)

**Comment by YUANXINGlingyun** [comment]
并没有复现出此 Bug，请确认你的启动器是不是最新版~

**Comment by LTCatt** [comment]
版本独立设置中指定的 Java 已无法使用，此设置已重置：未将对象引用设置到对象的实例。
   在 PCL.ModMinecraft.JavaEntry.FromJson(JObject Data)
   在 PCL.ModMinecraft.JavaSelect(String CancelException, Version MinVersion, Version MaxVersion, McVersion RelatedVersion)
错误类型：System.NullReferenceException

该报错重复出现

**Comment by ThelevenFD** [comment]
解锁主题

**Comment by WForst-Breeze** [comment]
反馈者识别码为：92EB-FC6A-74A1-42A7

**Comment by LTCatt** [comment]
你的解锁码：augxjHNlxH1iZClUjulfGAN3voJEE3Qu
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
