### ISSUE TITLE
MOD列表部分最新更新时间错误

### ISSUE THREAD

**Issue by Nyaheart** [Hex-Dragon/PCL2#1194]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

Snapchat 2.4.8（280.0）
PCL2内显示的最新更新时间与Cureforge不相符

### 重现步骤

PCL2首页-下载-Mod-搜索某Mod-部分Mod的最新更新时间与Cureforge实际最新更新时间不相符
<img src="https://cdn.mewoth.cyou/pcltest.gif">

### 日志与附件

我不知道为什么我上传不了 w

https://cdn.mewoth.cyou/Log1.txt

**Comment by youzi-2333** [comment]
![Bug](https://user-images.githubusercontent.com/106497113/217138033-b006bdb2-cfc1-4d5f-b6f0-c39d74876797.png)
已复现，感谢您的反馈~

**Comment by AliceLeader** [comment]
快照的这个版本每次打开PCL后第一次进入 下载 的 mod 界面时都会跳出这个没什么干扰的错误反馈，也一起修修吧
![屏幕截图 2023-02-07 135635](https://user-images.githubusercontent.com/120795372/217163025-ad16fab9-9a04-4464-9cd6-a30aaff91b44.jpg)

**Comment by WForst-Breeze** [comment]
> 快照的这个版本每次打开PCL后第一次进入 下载 的 mod 界面时都会跳出这个没什么干扰的错误反馈，也一起修修吧

#1175

**Comment by LTCatt** [comment]
![image](https://user-images.githubusercontent.com/40348278/222905611-fa5d6b43-33cb-4ac5-be14-3b0907c75387.png)
CurseForge 捏麻麻逝了，dateModified 不知道是个啥，dateReleased 是最近更新时间？？
![image](https://user-images.githubusercontent.com/40348278/222905820-68d4baf8-10ee-4622-aae8-0ac46b289e9e.png)
