### ISSUE TITLE
PCL2最新版本不支持中文ID进入游戏

### ISSUE THREAD

**Issue by blackshou** [Hex-Dragon/PCL2#1205]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

![image](https://user-images.githubusercontent.com/97861611/217284224-1b8bec21-dc52-4034-a998-a6b5ed3e16a4.png)

### 原因

更改的服务器核心让玩家支持高版本中文ID登录及游玩
同时服务器加了正版和离线中文id验证 离线只允许使用中文id进入 而pcl2这次改动严重导致玩家无法进入服务器
![image](https://user-images.githubusercontent.com/97861611/217284543-e4204ab7-1bbd-4911-bbc1-07af5e255d87.png)

**Comment by WForst-Breeze** [comment]
已初步确认，感谢您的反馈~
