### ISSUE TITLE
【功能请求】通过热补丁进行紧急更新

### ISSUE THREAD

**Issue by Nyatasi** [Hex-Dragon/PCL2#1207]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

Snapshot 2.4.9 (282.0)
快照版：赞助用户体验新功能尝鲜的不保证稳定的版本
正式版：保证用户的体验稳定的普通版本
我本人同样也觉得这个功能用处不大 在考虑如果有不少人也希望有这个功能 那么我希望开发者可以考虑一下 于是就有了这个 Issues

（这个Issues没有考虑到多少因素 有错误请指出）

### 原因

开发者最快通常是次日修复紧急bug
热补丁可以使在修复这个bug立即发布快照版/正式版同时修复该bug

大版本更新时间紧凑也显得尴尬 ×

**Comment by WForst-Breeze** [comment]
原始 Discussion #1201 
已初步确认，感谢您的反馈~

**Comment by LTCatt** [comment]
技术上没法实现……
