### ISSUE TITLE
微软登录可以添加“使用安全密钥登录”

### ISSUE THREAD

**Issue by choking-chips** [Hex-Dragon/PCL2#121]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在使用Chrome之类的浏览器时，微软登录有这样一个选项：

<img src="https://user-images.githubusercontent.com/52846426/183278449-3b6150df-7822-47cc-a306-753a45812523.png" alt="使用安全密钥登录" title="使用安全密钥登录">

点击它，就能使浏览器打开一个窗口，可以通过输入PIN、按压指纹识别器等方式来验证是你，然后即可用该账户登录的微软账户来登录。

### 原因

如果有这项更改的话，那么登录账号也就因此变得更加简单了，不用再输入长长的微软账户密码，而是输入PIN、按压指纹识别器等更加便捷的方式即可解决登录。

~虽然似乎账号只需要登录一次，一次性功能了属于是。~

**Comment by WTP016-CN** [comment]
印象里 PCL2 微软帐号登录调用 IE，似乎不能使用这个功能（）

**Comment by choking-chips** [comment]
确实是IE（点登录显示Internet Explorer可以记住密码），也许可以尝试调用新版Edge？（我不懂，我乱说的（

**Comment by WTP016-CN** [comment]
> 确实是IE（点登录显示Internet Explorer可以记住密码），也许可以尝试调用新版Edge？（我不懂，我乱说的（

这边建议单独开一个 Issue 建议更换到 EdgeWebView （）
这个和那个分开 不要写在一起

**Comment by choking-chips** [comment]
> 这边建议单独开一个 Issue 建议更换到 EdgeWebView （） 这个和那个分开 不要写在一起

如果更换到EdgeWebView的话，能实现的功能也许就只有这个？（据我使用来看应该是这样）

要不我编辑一下这个Issue，写得详细些？

**Comment by WTP016-CN** [comment]
> > 这边建议单独开一个 Issue 建议更换到 EdgeWebView （） 这个和那个分开 不要写在一起
> 
> 如果更换到EdgeWebView的话，能实现的功能也许就只有这个？（据我使用来看应该是这样）
> 
> 要不我编辑一下这个Issue，写得详细些？

一个 Issue 中不可以提出多个优化建议
换到 EdgeWebview 之后，可以加快页面加载速度，还可以避免由 IE 如同屎山的代码带来的性能损耗，但可能会对 Win7 等不带 EdgeWebview 组件的电脑带来空间困扰（
（但是装了 Edge 就自带 EdgeWebview我记得

**Comment by LTCatt** [comment]
根据微软官方文档，WebView2 需要调用额外的安装程序进行安装，这对 PCL2 来说是无法接受的……

**Comment by WTP016-CN** [comment]
> 根据微软官方文档，WebView2 需要调用额外的安装程序进行安装，这对 PCL2 来说是无法接受的……

这个 Issue 本来讨论的问题可不可以用 IE 实现呢（）

**Comment by WTP016-CN** [comment]
点错了（）

**Comment by LTCatt** [comment]
> > 根据微软官方文档，WebView2 需要调用额外的安装程序进行安装，这对 PCL2 来说是无法接受的……
> 
> 这个 Issue 本来讨论的问题可不可以用 IE 实现呢（）

微软的登录网页应该是由微软自己判定浏览器类型，应该没办法……
PCL2 不是在直接调用 IE，而是调用 WPF 的浏览器控件，它使用了 IE 内核。

**Comment by choking-chips** [comment]
那能否折中一下，让有安装Edge WebView2的情况下调用此，否则仍然使用自带的浏览器控件来登录呢？

**Comment by LTCatt** [comment]
> 那能否折中一下，让有安装Edge WebView2的情况下调用此，否则仍然使用自带的浏览器控件来登录呢？

看 #122 吧

**Comment by so1ve** [comment]
> > 那能否折中一下，让有安装Edge WebView2的情况下调用此，否则仍然使用自带的浏览器控件来登录呢？
> 
> 看 #122 吧

我记得[tauri](https://github.com/tauri-app/tauri)有实现自动的webview2检测（？）龙猫或许可以参考一下实现
