### ISSUE TITLE
下载自定义文件页面被遮挡

### ISSUE THREAD

**Issue by ProgramApe6020** [Hex-Dragon/PCL2#1213]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

输入下载网址后点击下载后 “开始下载”和“打开文件夹”两个按钮会被遮挡，如图：

### 重现步骤

1、点击更多-百宝箱
2、点击下载自定义文件-开始下载

### 日志与附件

![图片](https://user-images.githubusercontent.com/77217592/217508348-44891868-fd40-4bc4-95bb-ed3dcb402508.png)

**Comment by WForst-Breeze** [comment]
窗口拉大点就好了（）已初步确认，感谢您的反馈~

**Comment by LTCatt** [comment]
窗口拉大点就好了……算了……
