### ISSUE TITLE
增加对单层离线皮肤的支持

### ISSUE THREAD

**Issue by ZmdNotFound** [Hex-Dragon/PCL2#1216]
### 检查项

- [x] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在离线皮肤设置中支持64×32大小的单层离线皮肤

### 原因

离线登录游玩时需要

**Comment by WForst-Breeze** [comment]
已初步确认，感谢您的反馈~

**Comment by iPodtouch6557** [comment]
这个反馈有道理，因为部分皮肤是64*32的，pcl自定义不支持它，现在可获得这种皮肤的唯一方法就是输入正版名，这算个bug（）
