### ISSUE TITLE
标题栏文本上限可以突破

### ISSUE THREAD

**Issue by ZmdNotFound** [Hex-Dragon/PCL2#1220]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

启动器设置->个性化中的标题栏文本字数上限可以通过修改文件突破

### 重现步骤

1、修改PCL\Setup.ini中UiLogoText项为一串很长的文本
2、打开PCL2即可突破限制

### 日志与附件

这个需要上传日志吗.jpg

**Comment by youzi-2333** [comment]
刻意卡的 Bug 龙猫不会修……

不过我也不敢关掉，先放着吧（）

**Comment by WForst-Breeze** [comment]
应该不会修（）但还是先初步确认了，感谢您的反馈~

**Comment by LTCatt** [comment]
刻意卡的 Bug 不修……
