### ISSUE TITLE
[BUG][附个人解决方案]1.19.3无法发言

### ISSUE THREAD

**Issue by horizon86** [Hex-Dragon/PCL2#1221]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

发言时提示：由于个人信息公钥丢失，聊天已被禁用。请尝试重新连接。

### 重现步骤

使用PCL2启动，并加入正版验证且`enforce-secure-profile=true`的1.19.3的服务器并发言。

### 日志与附件

无需。
解决方案：官启可以。或者把PCL的启动参数中`--userType mojang`改成`--userType msa`即可。

**Comment by WForst-Breeze** [comment]
此反馈提供了 #949 提及事项的可供参考的解决方案，已初步确认，十分感谢您的反馈~

**Comment by horizon86** [comment]
> 

@LTCatt @WForst-Breeze 我自己构建了一份HMCL，仅修改了`--userType msa`的设置部分。
目前：如果之前登陆过官启，用这份HMCL启动可以发言。

如果之前没有登陆过官启，用这份HMCL不可以发言（不完全确定，有人没成）。所以需要验证没下载安装过官启的环境下，该解决方案的可用性。
