### ISSUE TITLE
更新提示的bug,触发原因不明

### ISSUE THREAD

**Issue by ZELDA2007823** [Hex-Dragon/PCL2#1230]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

每次启动启动器[即使已经有了新的mc版本],不明原因会弹出更新提示[新版本下载提示]

### 重现步骤

1、点击xxxx
2、往下滚，然后点击xxxx

### 日志与附件

日志
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10708960/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10708961/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10708962/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10708963/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10708964/Log1.txt)
截图
![_X552Q G08${A3 TF(~T1DO](https://user-images.githubusercontent.com/110316388/218131829-6ce96e19-50f4-4e45-a023-7602235ebded.png)
望处理感谢

**Comment by ZELDA2007823** [comment]
多次点击自动安装的刷新列表也可以的达到类似的效果

**Comment by naiximcn** [comment]
明明几天前的版本也会突然提示（）

**Comment by youzi-2333** [comment]
如果你有了这个版本，PCL2 也不会关掉更新提示（毕竟 PCL2 第一次发现这个版本，你怎么在 PCL2 里面安装）~~所以扯了这么多~~个人感觉可以改成“有相同 MC 版本时不显示更新提示”的新功能，如果的确是 Bug 的话就当我没说，感谢您的反馈～

**Comment by WForst-Breeze** [comment]
与 #359 类似，龙猫初步判断为意外获取到旧缓存导致，此反馈是其补充

**Comment by LTCatt** [comment]
根据测试，mojang 的更新内容有奇怪的缓存，导致新快照刚更新时你会随机获取到老版本和新版本，这里每次的随机变化 PCL 都会判断为更新。我没法修复它……
