### ISSUE TITLE
存在自定义主页的情况下在清理缓存后"更多-帮助"出现报错

### ISSUE THREAD

**Issue by Dontplay1003** [Hex-Dragon/PCL2#1234]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在存在自定义主页"Custom.xaml"的文件时，在"设置-启动器-系统-清理缓存"后，再次打开"启动"对应的主页面会出现报错提示
![image](https://user-images.githubusercontent.com/98459770/218239779-5ab9dd42-de35-4406-9863-dc6b48d1f7d0.png)

在打开过"更多-帮助"后，改提示不再出现

### 重现步骤

1、如果没有自定义过主页，则先打开"设置-个性化-自定义主页-本地文件"，并点击"设置-个性化-自定义主页-生成教学文件"(联网更新暂时没有尝试过)
2、然后点击"设置-启动器-系统-清理缓存"
3、再次打开PCL2，即会弹出**描述**中所示的报错提示
4、点击"更多"，显示过"帮助"后不会再出现这一报错提示

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10712614/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10712610/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10712611/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10712612/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10712613/Log5.txt)

**Comment by WorldHim** [comment]
已复现，感谢您的反馈。
![image](https://user-images.githubusercontent.com/68632311/218242374-da0d32fc-666c-4a9b-854a-d6a7949a1829.png)

**Comment by Dontplay1003** [comment]
@LTCatt @WorldHim 
有个可能的解决方法。
重新检查了一下这个报错，感觉这个标题可能不太合适，因为报错应该是生成的自定义主页教学文件里引用了不存在的文件导致的。

报错的逻辑应该是因为生成的教学文件里，最后一个卡片(高级：预置图片和列表项)中涉及了对"自定义帮助页面"(更多-帮助-个性化-自定义帮助页面)的引用。但是一旦清理了缓存，"~/Appdata/Local/Temp/PCL"这一文件夹就会被清除，所以导致了再次打开，xaml文件在做检查时就检查不到"~/AppData/Local/Temp/PCL/Help/帮助/自定义帮助.xaml"这个文件了。
PCL在首次启动未打开过"更多-帮助"的情况下不会在"~/Appdata/Local/Temp/PCL"下生成"Help"文件夹。

可能的解决方法：在PCL启动时就检查并生成这些帮助文件？不过，这样好像有点儿影响启动的性能。或者在生成自定义主页时检查并生成这些帮助文件吧，这样好像好点儿？

PS：真的会有人第一次启动PCL就直奔设置，生成自定义主页的教学文件，然后不打开帮助再立刻回到启动这个主页面吧，应该会。。有吧（笑

**Comment by Dontplay1003** [comment]
1A25-FC29-7981-A5E3，诶嘿

**Comment by LTCatt** [comment]
你的解锁码：2n3gyMP1bZgacktmUenbn6+9ThdfSU0P
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
