### ISSUE TITLE
百宝箱下载小问题

### ISSUE THREAD

**Issue by quannen** [Hex-Dragon/PCL2#1235]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

复制链接下载时会提示“链接无效”但是已经开始下载

### 重现步骤

打开百宝箱
复制粘贴链接并下载

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10712656/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10712657/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10712658/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10712659/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10712660/Log5.txt)

**Comment by WorldHim** [comment]
已复现，感谢您的反馈。（即点击下载后下载地址会清空，使 PCL 判断网址为空无效）

**Comment by quannen** [comment]
还有一个Bug,（不想再开一个issue了）点更新后提示连接PCL服务器失败，可是当再次打开启动器时发现已经完成更新

**Comment by quannen** [comment]
我不保证那一次的log已经被覆盖了
