### ISSUE TITLE
Littleskin皮肤与启动器不同步

### ISSUE THREAD

**Issue by nlywto5b** [Hex-Dragon/PCL2#1236]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在littleskin上更改皮肤后启动器不同步，已经尝试过刷新皮肤/启动器内重新登录littleskin账号/重新配置第三方登录/重新启动启动器，都没有用，游戏里的皮肤也没有更改

### 重现步骤

1、在littleskin上更改皮肤
2、在pcl2启动器上登录littleskin账号

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10712703/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10712705/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10712706/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10712713/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10712714/Log5.txt)

**Comment by nlywto5b** [comment]
在安装“万用皮肤补丁”模组后游戏内皮肤同步了，但启动器上的皮肤仍然不同步

**Comment by naiximcn** [comment]
这边建议亲亲清除pcl2缓存关闭然后再打开看看（）

**Comment by nlywto5b** [comment]
试过了，没用

**Comment by nlywto5b** [comment]
> 这边建议亲亲清除pcl2缓存关闭然后再打开看看（）

试过了，没用

**Comment by naiximcn** [comment]
> > 这边建议亲亲清除pcl2缓存关闭然后再打开看看（）
> 
> 试过了，没用

先确认一下皮肤更换成功 再退出重新登录littleskin账号试试？ 一般更新皮肤短时间内不会生效而且启动器会有缓存包括正版皮肤（）

**Comment by WorldHim** [comment]
更新有延迟，请耐心等待。如果过长时间仍未更新可以发一下截图。
~~而且实际上这只是一个皮肤头部预览，没什么用吧~~

**Comment by nlywto5b** [comment]
![屏幕截图 2023-02-11 164024](https://user-images.githubusercontent.com/118055561/218248940-e53317ed-5458-4cb9-842f-31daae65c170.jpg)
![屏幕截图 2023-02-11 163941](https://user-images.githubusercontent.com/118055561/218248945-4674c393-c4c3-47c3-8a8b-82a2435a6cb1.jpg)

**Comment by nlywto5b** [comment]
> 更新有延迟，请耐心等待。如果过长时间仍未更新可以发一下截图。 ~而且实际上这只是一个皮肤头部预览，没什么用吧~

![屏幕截图 2023-02-11 164024](https://user-images.githubusercontent.com/118055561/218248965-7930894b-8d44-4235-ba5a-0ac5ff846251.jpg)
![屏幕截图 2023-02-11 163941](https://user-images.githubusercontent.com/118055561/218248967-1fffd02f-814e-4b1b-8223-2e384e916989.jpg)

**Comment by Big-Cake-jpg** [comment]
你可能需要右键角色头像，然后按下“刷新”按钮。
![image](https://user-images.githubusercontent.com/76810494/218254972-12e53c1c-50e1-45fd-8c3e-94243421f471.png)

**Comment by nlywto5b** [comment]
> 你可能需要右键角色头像，然后按下“刷新”按钮。 ![image](https://user-images.githubusercontent.com/76810494/218254972-12e53c1c-50e1-45fd-8c3e-94243421f471.png)

已经尝试过，仍未同步

**Comment by CANYSHANGYV** [comment]
> 在安装"万用皮肤补丁"模组后游戏内皮肤同步了，但启动器上的皮肤仍然不同步

版本设置  高级启动项选项  文件检验  关闭这个这个就行了
