### ISSUE TITLE
更改更新时候的标题

### ISSUE THREAD

**Issue by misividkoukou** [Hex-Dragon/PCL2#1239]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在更新输入解锁码时依然提示在内群输入.update而不是在爱发电处理此问题，建议修改

### 原因

（示例）
这项优化让我可以更方便地更新。
如果没有这项优化，我会很难受，让操作变得很麻烦。（doge

**Comment by LTCatt** [comment]
新版本已修复，但你用的是老版本才会看到更新提示……
