### ISSUE TITLE
增加一个为多次获得活跃橙的用户的新主题

### ISSUE THREAD

**Issue by LTDove** [Hex-Dragon/PCL2#1242]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

增加一个新主题
为多次提交bug/帮助库用户写个新主题
可能会让多次提交的用户对PCL有归属感
？
可能还能保留用户？？？

### 原因

需要新主题~（
来增加PCL的活跃度~
也许加一个
bug提交变多了~
PCL变好了~
lm不快乐了~
但是用户爽了~
（P.S 其实是活跃橙看久了
不是本来也说要重写没.jpg）

**Comment by youzi-2333** [comment]
总感觉有人反馈过，但又搜不到……先看龙猫咋处理吧，感谢您的反馈～

**Comment by idomoy** [comment]
但我觉得这样会促使很多玩家刻意去反馈一些鸡毛蒜皮的bug（）

**Comment by idomoy** [comment]
> 但我觉得这样会促使很多玩家刻意去反馈一些鸡毛蒜皮的bug（）
甚至一些根本不是bug的bug...带来一些不必要的麻烦（）

**Comment by WorldHim** [comment]
其实这反馈奖励有利有弊，具体不好说。
