### ISSUE TITLE
启动 PCL2 时允许关闭已经在运行的 MC

### ISSUE THREAD

**Issue by Anythingteam** [Hex-Dragon/PCL2#1243]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

支持在重启pcl2后也能检测正在运行中的mc并可单独关闭的功能

### 原因

重启pcl2后就没有关闭mc的按钮了，感觉有点不协调？

**Comment by Big-Cake-jpg** [comment]
我记得这个是有人提到过的......隐约记得是被拒绝了的

**Comment by LTCatt** [comment]
仔细想了想，这个不太行，很难识别一个 Java 进程是不是真的 MC，并且作用也不是很大，算了 orz
