### ISSUE TITLE
卸载mod时跳出无法删除，但文件仍然消失

### ISSUE THREAD

**Issue by wtmdyslawas** [Hex-Dragon/PCL2#1245]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在喷气背包猫整合包（forge）中卸载误安装的fabirc模组时跳出错误窗口，文件仍被删除。（其实不影响体验，且无法复刻)

### 重现步骤

在喷气背包猫整合包（forge）中卸载误安装的fabirc模组

### 日志与附件

[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10713678/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10713679/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10713681/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10713682/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10713683/Log4.txt)

**Comment by youzi-2333** [comment]
既然是您那边的问题，那就先关了（）感谢您的反馈~
