### ISSUE TITLE
为啥还是没有1.19.3的离线皮肤修复？

### ISSUE THREAD

**Issue by liuchenxi12** [Hex-Dragon/PCL2#1250]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

还是没有修复1.19.3的皮肤bug

### 重现步骤

1、自定义皮肤后离线启动
2、进入游戏即可复现

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10715183/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10715184/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10715185/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10715186/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10715187/Log5.txt)

**Comment by iPodtouch6557** [comment]
不是，原issue是啥啊，发个链接（看你这样有源issue）

**Comment by youzi-2333** [comment]
~~你就不会搜索吗~~原始 Issue 为 #590

**Comment by iPodtouch6557** [comment]
> ~你就不会搜索吗~原始 Issue 为 #590

~好吧我脑子不好~是不是其实修了没在你那体现？

**Comment by youzi-2333** [comment]
> 是不是其实修了没在你那体现？

有可能，~~刚蹭到免费 WiFi~~ 看了下 Log，Log2 中无法下载来自 `launchermeta.mojang.com` 的文件，Log3 正常启动并正常退出，版本均为 1.19.3，没有发现释放离线皮肤资源包的错误……难道是 Mojang 服务器的锅？

不管怎样似乎都有问题，先加上待处理等消息吧，要是后续又好了可以联系关掉……

（我在外面没法复现，抱歉了）

**Comment by LTCatt** [comment]
你的网络问题……
