### ISSUE TITLE
使用正版玩家皮肤小bug

### ISSUE THREAD

**Issue by MarxEngels1918** [Hex-Dragon/PCL2#1254]
### 检查项

- [x] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

离线单人游戏用正版玩家皮肤导致游戏中ID改变，而且无法保存存档（游戏退回标题页面后卡在保存世界中，只能任务管理器或者在pcl里面关闭）
![image](https://user-images.githubusercontent.com/123903743/218298604-90dec03c-efd9-433a-9a20-43fd5e4580f8.png)
![image](https://user-images.githubusercontent.com/123903743/218298626-1f078083-53fc-498e-9783-859427324445.png)
启动之后，进地图，用effect命令能发现id改为正版皮肤的id
![image](https://user-images.githubusercontent.com/123903743/218298873-aef4b5fb-0140-4f52-988e-0942fedca313.png)

如图

### 重现步骤

1、在pcl启动器的设置里选用正版id玩家皮肤（正版id与游戏id不同）
2、启动游戏

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10715552/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10715553/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10715554/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10715555/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10715556/Log1.txt)

**Comment by iPodtouch6557** [comment]
我这没这个情况，你可以说详细一点吗，比如说游戏版本、启动器版本、等等

**Comment by MarxEngels1918** [comment]
> 我这没这个情况，你可以说详细一点吗，比如说游戏版本、启动器版本、等等

游戏1.18.2,启动器是最新版本

**Comment by iPodtouch6557** [comment]
不对呀，我以前会用那个b站主播大白的皮肤，他的ID是ZHAIXIAOpang，我嫌这个id没意思，换了别的一个，没这情况啊
还有，是不是只有/effect会触发bug，我的死亡提示没有触发

**Comment by youzi-2333** [comment]
我好久以前就发现了，一直以为是正常现象（）

至于正不正常我也不知道，先等龙猫看看吧，感谢您的反馈～

**Comment by youzi-2333** [comment]
> 还有，是不是只有/effect会触发bug，我的死亡提示没有触发

只有 effect 命令触发 Bug 的话，可能是 MC 那边的问题（？）

**Comment by iPodtouch6557** [comment]
> > 还有，是不是只有/effect会触发bug，我的死亡提示没有触发
> 
> 只有 effect 命令触发 Bug 的话，可能是 MC 那边的问题（？）

（~有本事你去bugs.mojang.com反馈~）反正我这没有，好像你们的bug与我绝缘（）

**Comment by MarxEngels1918** [comment]
> 
不只是effect,bug触发以后游戏是无法正常保存的

**Comment by iPodtouch6557** [comment]
> > 
> 
> 不只是effect，bug触发以后游戏是无法正常保存的

对我来说，只有模组加太多了，版本又低于1.18.2的才会卡死保存不了
所以我也不会看代码，别问我了（）

**Comment by LTCatt** [comment]
这是 MC 的 Bug
