### ISSUE TITLE
在启动器还没有弹出 已启动游戏 的时候取消启动，还是会弹出Minecraft界面

### ISSUE THREAD

**Issue by 3cxc** [Hex-Dragon/PCL2#1255]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

当你启动Minecraft时突然不想玩了,然后取消启动
虽然启动器取消启动了，但是Minecraft还是出现了

### 重现步骤

1、点击启动游戏
2、在还没弹出 已启动游戏 的时候取消启动(拼手速)
3、你就会发现Minecraft还是启动了(一定概率，我自己测了10次,6次启动)

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10715737/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10715739/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10715740/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10715741/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10715742/Log1.txt)

**Comment by youzi-2333** [comment]
以前我遇到过，但是之后就莫名其妙的好了……

已初步确认，感谢您的反馈～

**Comment by iPodtouch6557** [comment]
这个功能投票里有，重复了，关了吧

**Comment by 3cxc** [comment]
您是说哪一个投票？我并未找到有这个功能的投票啊

**Comment by iPodtouch6557** [comment]
> @iPodtouch6557 您是说哪一个投票？我并未找到与这个有关的投票

https://github.com/Hex-Dragon/PCL2/discussions/1249
他的意思和你一样的，只不过你以bug体现，他以优化体现

**Comment by iPodtouch6557** [comment]
https://github.com/Hex-Dragon/PCL2/discussions/1249 
~说话别这么客气~他的意思和你一样的，只不过你以bug体现，
他以优化体现

**Comment by YUANXINGlingyun** [comment]
我也想反馈来着

**Comment by dargoncat** [comment]
> #1249 ~说话别这么客气~他的意思和你一样的，只不过你以bug体现， 他以优化体现

这个与你提到的优化应该不重复，你仔细揣摩一下意思

**Comment by 3cxc** [comment]
@iPodtouch6557 
#1249 跟我反馈的内容不一样
他说的是"启动PCL2时允许关闭已经在运行的MC"
我反馈的是在PCL2启动MC时(未弹出 游戏已启动)点击取消启动后仍会有概率启动MC的问题

**Comment by iPodtouch6557** [comment]
不是那这不包括你说的问题吗，我指的就是这个啊，这个情况是我遇到的最多的情况
还有我忽然想到一个问题，就是你用启动器启动了游戏后玩一会，闲的没事关掉启动器再打开，游戏会被关闭，这不是操作上的冲突吗（虽然我觉得没人会这么干，闲的啊）

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年2月12日 21:21
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [Hex-Dragon/PCL2] 在启动器还没有弹出 已启动游戏 的时候取消启动，还是会弹出Minecraft界面 (Issue #1255)


@iPodtouch6557<https://github.com/iPodtouch6557>
#1249<https://github.com/Hex-Dragon/PCL2/discussions/1249> 跟我反馈的内容不一样
他说的是"启动PCL2时允许关闭已经在运行的MC"
我反馈的是在PCL2启动MC时(未弹出 游戏已启动)点击取消启动后仍会有概率启动MC的问题

―

**Comment by 3cxc** [comment]
@iPodtouch6557 #1249 怎么就包括我说的问题了？
"启动 PCL2 时允许关闭已经在运行的 MC"
"在启动器还没有弹出 已启动游戏 的时候取消启动，还是会弹出Minecraft界面"
这两个是一样的吗？

**Comment by iPodtouch6557** [comment]
> @iPodtouch6557 我反馈的是在PCL2启动MC时（**未弹出 游戏已启动**）点击取消启动后仍会有概率启动MC的问题 但 #1249 是 **启动**PCL2时允许关闭在运行的MC

这，好吧，是关闭按钮的锅，不是启动器taskkill做的不好啊（合并反馈一下吧）

**Comment by youzi-2333** [comment]
别吵了（），源码里面 如果（开始了日志监控）则（等同于关闭游戏按钮，强制结束游戏进程），否则如果（启动进程已经开始 并且 启动进程尚未结束）则（杀掉启动进程），但是如果日志监控结束了（我也不知道因为啥原因结束），那么就只能杀启动进程了……这样就关不掉 MC……

也有可能是 #1094 的问题，等那个 Issue 处理好应该就……修好了吧？

**Comment by Chormore-EDGE** [comment]
如果 #1094 修好了但是这个bug没好的话就是另一个事情了

**Comment by LTCatt** [comment]
看了看 log，确实是 #1094 的 Bug
