### ISSUE TITLE
mod优化

### ISSUE THREAD

**Issue by fermi2022** [Hex-Dragon/PCL2#1256]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [x] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

启动器有个mod下载列表，有很多模组没有加入列表，希望可以允许玩家自己上传mod，经过审批加入列表

### 原因

这项优化让我可以更方便地查阅到当前比较流行的mod
如果没有这项优化，我每次都必须上网进行搜索，版本也有所差异，让操作变得很麻烦。

**Comment by youzi-2333** [comment]
龙腾猫跃曾经说过，永远不会做服务器，而 PCL2 的 Mod 来源于 CurseForge，因此无法自己上传 Mod 到 PCL2 服务器……

如果龙猫打算做的话再说吧……

**Comment by fermi2022** [comment]
啊这，那整合包呢？


从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年2月12日 17:45
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [Hex-Dragon/PCL2] mod优化 (Issue #1256)


龙腾猫跃曾经说过，永远不会做服务器，而 PCL2 的 Mod 来源于 CurseForge，因此无法自己上传 Mod 到 PCL2 服务器……

如果龙猫打算做的话再说吧……

―

**Comment by idomoy** [comment]
mod和整合包都是第三方下载源

**Comment by fermi2022** [comment]
好的，谢谢你的回复

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年2月12日 17:55
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [Hex-Dragon/PCL2] mod优化 (Issue #1256)


mod和整合包都是第三方下载源

―

**Comment by 212112111zwl** [comment]
> 有很多模组没有加入列表

几乎所有curseforge上能搜到的模组都能下载，下载界面也明确标注了模组的版本。
pcl只会加载热门模组列表的前100项，并不是所有curse上的模组，如果想寻找特定的模组，请搜索关键词。

关于允许玩家添加mod的功能，1是 “PCL2 的 Mod 来源于 CurseForge”，2是mod审核需要大量人力物力的投入，因此不太可能在一个**基本功能完全免费**的启动器上完成

谢谢您的反馈~
