### ISSUE TITLE
极客蓝提示优化

### ISSUE THREAD

**Issue by fhh1224** [Hex-Dragon/PCL2#1257]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

![image](https://user-images.githubusercontent.com/99572573/218307996-e8f2207b-1f51-44ee-a916-ee57a4f4daed.png)
第一行“没有谜题可以或需要以此来解决”
第四行“任意相关群”

### 原因

病句

**Comment by youzi-2333** [comment]
有问题吗（）

如果实在觉得不太对劲的话……那就等龙猫改一下吧……感谢您的反馈～

**Comment by iPodtouch6557** [comment]
~真会挑刺~不过谁这么干

**Comment by idomoy** [comment]
我看不出来哪里有语病
