### ISSUE TITLE
崩溃误报

### ISSUE THREAD

**Issue by AwardedStatue97** [Hex-Dragon/PCL2#1258]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在使用某些会自动更新mod后重启游戏的mod时，PCL2会在游戏仍在运行，且正常启动的情况下，提示崩溃，且如点击查看日志，则此弹窗会再次跳出

### 重现步骤

1、下载Minecraft Mod Updater
2、配置好此模组再重新启动

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10716097/Log1.txt)

**Comment by youzi-2333** [comment]
已初步确认，感谢您的反馈~

Mod 下载：https://www.mcmod.cn/class/5650.html

**Comment by LTCatt** [comment]
大概可以检测 `Restarting Minecraft with command` ……

**Comment by AwardedStatue97** [comment]
3871-CF47-2C6D-E779

**Comment by LTCatt** [comment]
你的解锁码：1z8YVElV2eZdUxRPbO74nRG1P6wrVYeB
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
