### ISSUE TITLE
我在使用PCL2时弹窗出HWI*.exe崩溃

### ISSUE THREAD

**Issue by MCjiangzhen** [Hex-Dragon/PCL2#1259]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在进入一个网页(https://thejaspel.itch.io/backpack-hero)后突然弹窗出HWI*.exe崩溃，点击”是“后似乎是文件资源管理器突然崩溃我的Edge和QQ也崩溃了，在文件资源管理器重启后弹出窗口(标题为中文乱码)

### 重现步骤

1、进入网页
2、概率弹出HWI*.exe崩溃
3、点击“是”文件资源管理器会崩溃

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10717807/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10717808/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10717809/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10717810/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10717811/Log2.txt)

**Comment by youzi-2333** [comment]
Log2 有如下报错：
```
[08:51:54.910] 程序出现未知错误：UCEERR_RENDERTHREADFAILURE (异常来自 HRESULT:0x88980406)
   在 System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
   在 System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   在 System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   在 System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   在 System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
错误类型：System.Runtime.InteropServices.COMException
```
与 #685 相同，`HRESULT` 通常是系统配置问题，不是 PCL2 的问题。感谢您的反馈~
