### ISSUE TITLE
mod损坏

### ISSUE THREAD

**Issue by lol2c** [Hex-Dragon/PCL2#1261]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

未知，突然提示replaymod中央目录损坏，未进行任何设置，但是用HMCL启动过一次

### 重现步骤

点击“版本选择”

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10718632/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10718635/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10718636/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10718637/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10718638/Log5.txt)

**Comment by youzi-2333** [comment]
```
[12:21:38.985] Mod 文件无法打开（D:\1.8.9\.minecraft\versions\1.8.9-forge1.8.9-11.15.1.1722\mods\Replay-1.8.9.jar.disabled）：中央目录损坏。
→ 试图将文件指针移到文件开头之前。

   在 System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   在 System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
   在 PCL.ModMinecraft.McMod.Load(Boolean ForceReload)
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.SeekCore(Int64 offset, SeekOrigin origin)
   在 System.IO.FileStream.Seek(Int64 offset, SeekOrigin origin)
   在 System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
错误类型：System.IO.IOException
```
既然是“试图将文件指针移到文件开头前”，多半是 PCL2 的问题……先等龙猫处理吧，感谢您的反馈~
