### ISSUE TITLE
为何在个性化隐藏勾选除“反馈”和“新功能投票”外再勾选一个会让“反馈”和“新功能投票”消失？

### ISSUE THREAD

**Issue by XiaoQing114514** [Hex-Dragon/PCL2#1267]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在个性化“功能隐藏”中勾选除“反馈”和“新功能投票”外，如果带上这俩再带两个，开启隐藏后“反馈”和“新功能投票”会消失，只剩未勾选的那一个了。

### 重现步骤

1、点击个性化功能隐藏
2、将除“反馈”和“新功能投票”的功能再勾选上两个
3、开启隐藏
4、你会发现BUG出现

### 日志与附件

![屏幕截图1](https://user-images.githubusercontent.com/125367737/218738666-165a6141-d9aa-4708-a486-a8d20765e3a1.png)
![屏幕截图2](https://user-images.githubusercontent.com/125367737/218739550-734ff50d-2470-4e55-9917-9966dd28ca06.png)
![屏幕截图3](https://user-images.githubusercontent.com/125367737/218739437-13d4ebaa-81a5-4ac2-bbfb-f053e1cd61f6.png)

**Comment by idomoy** [comment]
测试了一下，只要同时勾选[关于与鸣谢][百宝箱]这两个，[反馈][新功能投票]就会跟着一起消失。
此时如果再勾选上[帮助]的话，[更多]就会整个全部隐藏掉。
原因其实不难想到，[反馈][新功能]投票这两个选项并没有对应的软件内页面，点击只是会出现一个弹窗而已。如果其他功能都隐藏而只保留这两个选项的话，[更多]页面就没有页面可以展示了。所以隐藏其他之后这两个也会一起隐藏掉。
但是只隐藏[反馈][新功能投票]也会让这两个消失......我觉得这个确实是个问题......其实可以让[帮助]跟这两个并列显示的吧，看龙猫怎么说吧。

**Comment by LTCatt** [comment]
![image](https://user-images.githubusercontent.com/40348278/222953051-f39e204c-0549-40af-ad84-85191010947b.png)

现在在无法展示时会直接锁定这俩选项为强制开启 =。=
