### ISSUE TITLE
建议在Minecraft弹出崩溃弹窗时点击[查看日志]后不播放弹窗关闭动画

### ISSUE THREAD

**Issue by Yweiwu30** [Hex-Dragon/PCL2#1269]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在弹出弹窗提示Minecraft崩溃时，点击[查看日志]时可以让弹窗不发生任何变化（而不是先关闭弹窗然后再次弹出）

### 原因

原来的动画可能会造成误解，以为是启动器bug

**Comment by iPodtouch6557** [comment]
我就说啊，pcl启动器有很多设计上的细节没抠好，其实还是应该有更多类似反馈的
但是就不知道龙猫会不会去管……
