### ISSUE TITLE
整合包安装失败：下载mod失败

### ISSUE THREAD

**Issue by taoqibaohalo** [Hex-Dragon/PCL2#1276]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

这是下载界面上的报错内容

CurseForge整合包安装:Create: Above and Beyond
整合包安装失败
**Caused By:下载Mod失败**
**Caused By:输入的下载链接不正确!**
在PCL.ModNet.LoaderDownload._Lambda$__14-0()
错误类型: System.ArgumentException

注：网络环境已经检查了，没挂VPN，没看DNS，没有加速，可以正常访问curseforge.com
![image](https://user-images.githubusercontent.com/115784649/219034122-a4f46437-69bb-4ef6-bd55-8a5bbcb1af06.png)

### 重现步骤

1.点击下载
2.点”整合包“并搜索一个任意整合包
3.点击下载
4.出现的报错如上一栏描述

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10743189/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10743192/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10743193/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10743194/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10743195/Log2.txt)

**Comment by WForst-Breeze** [comment]
无法复现，请将启动器更新至最新版本后再尝试下载
```
[20:45:14.406] [Start] 程序版本：Snapshot 2.2.10（249）
```

**Comment by taoqibaohalo** [comment]
好的.png
