### ISSUE TITLE
Minecraft-fabric崩溃时PCL提供了错误的信息

### ISSUE THREAD

**Issue by Yweiwu30** [Hex-Dragon/PCL2#1281]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

Minecraft崩溃后（安装了fabric模组），查看日志可得知是数组越界的问题，而PCL提供了不必要的信息：
![image](https://user-images.githubusercontent.com/65439010/219056184-3d0de424-55f7-4ddd-bd65-3adcf4b6f66e.png)

### 重现步骤

1.启动游戏
2.Minecraft崩溃
3.崩溃提示

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10744012/Log1.txt)
[错误报告-2023-2-15_22.24.56.zip](https://github.com/Hex-Dragon/PCL2/files/10744015/-2023-2-15_22.24.56.zip)

**Comment by youzi-2333** [comment]
确实是数组越界……
已初步确认，感谢您的反馈～

**Comment by Yweiwu30** [comment]
FB5D-3A0B-3031-C60F

**Comment by LTCatt** [comment]
你的解锁码：bdDg6nEAknhHvflVIP7Rlgh+rElRSbQd
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
