### ISSUE TITLE
建议在认证正版账号后，再解锁离线模式及外置登录

### ISSUE THREAD

**Issue by smartcreeper192** [Hex-Dragon/PCL2#1282]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

建议在认证正版账号后，再解锁离线模式及外置登录

### 原因

网易疯了，避避风头

**Comment by Chormore-EDGE** [comment]
pcl本身就是离线和正版与一身的离线启动器...没了离线用户会流失的

**Comment by Chormore-EDGE** [comment]
而且有人买不起正版的，只能用离线，离线和外置改来改去还不如不改

**Comment by idomoy** [comment]
网易没疯。。你安心玩游戏一点事都不会有的
