### ISSUE TITLE
国内下载源下载失败，官方可以

### ISSUE THREAD

**Issue by DuoYu33243111** [Hex-Dragon/PCL2#1283]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

下载源下载失败

### 重现步骤

下载游戏时用镜像源下载错误

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10754002/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10754004/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10754005/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10754006/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10754007/Log5.txt)

**Comment by TsaiTou2926** [comment]
網易Feng了
PCL2也被舉報

**Comment by youzi-2333** [comment]
Log 中没看到相关 Bug……
请使用最新版 PCL2 重新复现后再次上传 Log，感谢配合。

**Comment by idomoy** [comment]
> 網易Feng了 PCL2也被舉報

PCL2用的都是第三方下载源，就算挂了也绝对不会是因为PCL2被举报而挂的（）
网易就下架了几个视频，还啥都没干呢

**Comment by iPodtouch6557** [comment]
> > 網易Feng了 PCL2也被舉報
> 
> PCL2用的都是第三方下载源，就算挂了也绝对不会是因为PCL2被举报而挂的（） 网易就下架了几个视频，还啥都没干呢

我就觉得现在对于冈易的举报问题已经引起一定恐慌了啊（听你们讲BakaXL作者是被抓了还是咋地
是冈易的蛋糕被碰了还是咋地了

**Comment by WForst-Breeze** [comment]
@TsaiTou2926 @iPodtouch6557 请停止讨论与本 Issue 无关内容，所谓开发者被抓等均为谣言，感谢您的配合☹

**Comment by iPodtouch6557** [comment]
> @TsaiTou2926 @iPodtouch6557 请停止讨论与本 Issue 无关内容，所谓开发者被抓等均为谣言，感谢您的配合☹

~（我长这么大第一次被谣言KO）~我认为就是对于下载源解析方面的一些问题了（）

**Comment by LTCatt** [comment]
> 網易Feng了 PCL2也被舉報

没有哦，不要传谣 =。=

**Comment by Chiloven945** [comment]
这多久没回复了，要不加个规则反馈者一段时间后还没反馈就直接close？

**Comment by WForst-Breeze** [comment]
> 这多久没回复了，要不加个规则反馈者一段时间后还没反馈就直接close？

我们会定期查看并提醒的（）

**Comment by Chiloven945** [comment]
好的（

**Comment by WForst-Breeze** [comment]
自 2/16 算起，您未能在10天内完成信息补充。请您在一周内尽快完成上述信息补充，否则此反馈将会被关闭，感谢您的支持和理解~

**Comment by iPodtouch6557** [comment]
> 自 2/16 算起，您未能在10天内完成信息补充。请您在一周内尽快完成上述信息补充，否则此反馈将会被关闭，感谢您的支持和理解~

@DuoYu33243111 ，最近好像接到BMClapi炸掉的消息，已经有人弯道超车你了

**Comment by youzi-2333** [comment]
> 最近好像接到 BMCLAPI 炸掉的消息，已经有人弯道超车你了

得先等他补充 Log 再看原因……

**Comment by LTCatt** [comment]
超时未回复暂时关闭，如有需要可以继续回
