### ISSUE TITLE
使用了正确的游戏java意外报错

### ISSUE THREAD

**Issue by binahenter** [Hex-Dragon/PCL2#1284]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![屏幕截图 2023-02-16 214531](https://user-images.githubusercontent.com/125573115/219381630-fb97e64d-5e05-42fa-bb9c-92dc66cc109e.png)
如图,使用了正确的游戏java意外报错

### 重现步骤

打开23w07a

### 日志与附件

[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10756573/Log5.txt)

**Comment by binahenter** [comment]
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10756601/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10756602/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10756605/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10756606/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10756607/Log4.txt)

**Comment by LTCatt** [comment]
应该是 JRE 17 和 JDK 17 的差别……

**Comment by iPodtouch6557** [comment]
之前也有人反馈过一个，标题是《你在设置中指定使用了Java8，但当前至少需要Java8》
说是pcl2对Java判定有误

**Comment by LTCatt** [comment]
可以查看 #1167 最新的说明
