### ISSUE TITLE
[较危险的BUG]错误报告所包含的启动脚本中带有token

### ISSUE THREAD

**Issue by TIMER-err** [Hex-Dragon/PCL2#1296]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我不知道这个bug有没有被发现过，但我觉得还是反馈一下比较好。
![1PMKXLWUO{@UDI@6 KIK%JO](https://user-images.githubusercontent.com/78411927/219692047-379d64ee-171d-422d-9d6b-5b5f6a7f798d.png)
这是我在内群里随便找的一个错误报告，
可以看到其中的启动脚本是带有token,username和uuid的，
只需要把它们复制到自己的启动脚本中，就可以登录别人的账号。
![2023-02-17_22 54 56](https://user-images.githubusercontent.com/78411927/219692602-c7d927cb-c871-4cd1-bb55-7210adefddd4.png)
可以看到我利用它登陆了hypixel（我发誓我没有做任何坏事），也证实了这个方法的可行性。
如果这个漏洞被不怀好意的人利用，后果不堪设想。
我的建议是在导出错误报告时在启动脚本中删去accesstoken,username,uuid参数。
希望可以修复此漏洞。

### 重现步骤

..................

### 日志与附件

这个不需要日志吧......
[Log.txt](https://github.com/Hex-Dragon/PCL2/files/10768225/Log.txt)

**Comment by SuoHouDaiShi** [comment]
我也发现了欸

**Comment by zkitefly** [comment]
我记得在此版本修了呀？
![image](https://user-images.githubusercontent.com/64117916/219712412-e1e8d4cc-5d87-4bf7-8c32-74b4087d7042.png)

**Comment by SuoHouDaiShi** [comment]
> 我记得在这个版本本修改了呀？ 当我就发生了这样的问题，我可能是安全性原因被删掉了（？） ![图像](https://user-images.githubusercontent.com/64117916/219712412-e1e8d4cc-5d87-4bf7-8c32-74b4087d7042.png)

我去看一下
反正在这之前，启动脚本里都包含token

**Comment by youzi-2333** [comment]
新版本确实修掉了.jpg

**Comment by TIMER-err** [comment]
原来我看的是旧版本😂

**Comment by TIMER-err** [comment]
> 
知道了，我看的是旧版本😂

**Comment by TIMER-err** [comment]
但是内群里已经发送的旧版错误报告怎么处理呢

**Comment by LTCatt** [comment]
> 但是内群里已经发送的旧版错误报告怎么处理呢

Token 会在一天后自动过期，你现在看到的旧版报告的 Token 都过期了（
