### ISSUE TITLE
关于笔记本电脑独显直连热切换冲突的问题

### ISSUE THREAD

**Issue by Spturate** [Hex-Dragon/PCL2#1298]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我的电脑是联想的Y7000P2021H，用他那个独显直连热切换会和PCL启动器冲突导致切换不过去
![屏幕截图_20230218_135246](https://user-images.githubusercontent.com/30800649/219843826-69ccedf7-c0e9-4785-a210-221a8b42e243.png)

### 重现步骤

1.打开启动器
2.启动游戏后如果按照英伟达的设置电脑会自动切换到独显输出的模式，但是弹出一个提示框说PCL启动器阻止了显示模式的更改

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10773449/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10773450/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10773451/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10773452/Log5.txt)
[Log.txt](https://github.com/Hex-Dragon/PCL2/files/10773453/Log.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10773454/Log1.txt)

**Comment by youzi-2333** [comment]
不太确定是不是 PCL2 的 Bug（）先看看龙猫怎么说吧（）感谢您的反馈～

**Comment by LTCatt** [comment]
这是因为 PCL 在使用集成显卡绘制，不属于我能修复的东西
