### ISSUE TITLE
关于正版档案明明在minecraft官网很正常，但打开启动器却提示没有档案，还可以正常启动登录

### ISSUE THREAD

**Issue by yunchuanjun** [Hex-Dragon/PCL2#1299]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

打开启动器总是提示没有档案，还可以正常启动登录（个人认为是检查错误）总是弹出来就很烦，从几年前就有了

### 重现步骤

没什么方法。只要打开启动器就有概率弹出来。（一般是在启动器打开之后的20秒内）

### 日志与附件

[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10773567/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10773568/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10773569/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10773570/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10773571/Log4.txt)

**Comment by youzi-2333** [comment]
<details>
<summary>Log4 报错</summary>
[13:58:56.446] 微软登录第 6 步汇报 404：网络请求失败（https://api.minecraftservices.com/minecraft/profile，远程服务器返回错误: (404) 未找到。）
{
  "path" : "/minecraft/profile",
  "error" : "NOT_FOUND",
  "errorMessage" : "Not Found"
}
→ 远程服务器返回错误: (404) 未找到。
   在 PCL.ModNet.NetRequestMuity(String Url, String Method, Object Data, String ContentType, Int32 RequestCount, Dictionary`2 Headers)
   在 PCL.ModLaunch.MsLoginStep6(String AccessToken)
   在 System.Net.HttpWebRequest.GetResponse()
   在 PCL.ModNet.NetRequestOnce(String Url, String Method, Object Data, String ContentType, Int32 Timeout, Dictionary`2 Headers, Boolean MakeLog)
错误类型：System.Net.WebException
[13:58:56.446] 加载线程 Loader Login Ms (18) 发生运行时错误：$$
   在 PCL.ModLaunch.MsLoginStep6(String AccessToken)
   在 PCL.ModLaunch.McLoginMsStart(LoaderTask`2 Data)
   在 PCL.ModLoader.LoaderTask`2._Closure$__12-0._Lambda$__0()
[13:58:56.446] [Loader] 加载器 Loader Login Ms 状态改变：Failed
[13:58:56.462] 加载线程 登录 (17) 发生运行时错误：$$
   在 PCL.ModLoader.LoaderBase.WaitForExit(Object Input, LoaderBase LoaderToSyncProgress, Boolean IsForceRestart)
   在 PCL.ModLaunch.McLoginStart(LoaderTask`2 Data)
   在 PCL.ModLoader.LoaderTask`2._Closure$__12-0._Lambda$__0()
   在 PCL.ModLaunch.MsLoginStep6(String AccessToken)
   在 PCL.ModLaunch.McLoginMsStart(LoaderTask`2 Data)
   在 PCL.ModLoader.LoaderTask`2._Closure$__12-0._Lambda$__0()
[13:58:56.462] [Loader] 加载器 登录 状态改变：Failed
[13:58:56.462] [Control] 普通弹窗：登录失败
你可能没有在 Minecraft 官网创建档案，或者没有购买 Minecraft。
如果你已经购买了游戏，请在官网上创建档案后再试。
</details>

有可能是微软登录步骤 6 的 URL 改掉了……？
但是 Minecraft Wiki 里面没变……

先加上待处理等回复吧，感谢您的反馈～

**Comment by LTCatt** [comment]
mojang 的 bug

**Comment by SimayiCC** [comment]
这种情况我也有过，开一下官网就能登上了
