### ISSUE TITLE
如题(

### ISSUE THREAD

**Issue by C1en-QwQ** [Hex-Dragon/PCL2#1305]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如题()
![image](https://user-images.githubusercontent.com/63438478/219869561-b5164137-2e40-43b8-b9c5-f91ab556b259.png)
![image](https://user-images.githubusercontent.com/63438478/219869568-431d6d08-1293-4cf6-81f9-3f99b9a9248b.png)

### 重现步骤

1、点击下载
2、往下滚，然后并未发现23w07a

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10774411/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10774412/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10774413/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10774415/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10774416/Log5.txt)

**Comment by ZHAOSBC** [comment]
这应该是镜像源的问题(
打开PCL2→设置→启动器→把版本列表获取改为“尽量使用官方源”即可解决

**Comment by C1en-QwQ** [comment]
> 这应该是镜像源的问题( 打开PCL2→设置→启动器→把版本列表获取改为“尽量使用官方源”即可解决

解决啦 谢谢
