### ISSUE TITLE
打开PCL2的第一次弹窗动画会有些卡顿

### ISSUE THREAD

**Issue by Anruicat** [Hex-Dragon/PCL2#1308]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

我没做过程序与动画，这个弹窗动画可以提前预加载么
额，就是那个联机模块提醒、今日人品的弹窗动画

### 原因

这项优化可以让一些老电脑更加流畅。
额，没了。。。

**Comment by 212112111zwl** [comment]
启动PCL2后第一次切换页面的动画会卡顿，但我这边的弹窗动画很丝滑……
你的电脑配置如何？如果是上古神机的化那就不能怪pcl了~

**Comment by Chormore-EDGE** [comment]
我这边还好，i5-6500核显配置挺流畅的

**Comment by Anruicat** [comment]
我配置奔腾双核E6700 3.2GHz 6GB DDR3 1333频率 显卡GT430 机械硬盘（西数蓝盘 大概10mb每秒）
还有我同学的小米轻薄本（忘了啥型号了）第一次打开比我这个流畅一些，但是没有第二次的弹窗流畅




Cloud
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Hex-Dragon/PCL2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月19日(星期天) 中午12:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Hex-Dragon/PCL2] 打开PCL2的第一次弹窗动画会有些卡顿 (Issue #1308)





 
我这边还好，i5-6500核显配置挺流畅的

**Comment by WorldHim** [comment]
> 我这边还好，i5-6500核显配置挺流畅的

你这配置又不算差。。。

**Comment by WorldHim** [comment]
> 我配置奔腾双核E6700 3.2GHz 6GB DDR3 1333频率 显卡GT430 机械硬盘（西数蓝盘 大概10mb每秒） 还有我同学的小米轻薄本（忘了啥型号了）第一次打开比我这个流畅一些，但是没有第二次的弹窗流畅

预加载浪费资源。。。几乎没有电脑会在弹窗上卡吧。。。
~~这个配置你还能用就离谱。~~

**Comment by LTCatt** [comment]
这种也不太能解决……
