### ISSUE TITLE
连续搜索两次会出现 “可视化 Mod 列表出错”

### ISSUE THREAD

**Issue by mcwuguodadi** [Hex-Dragon/PCL2#1311]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

2.5.0更新后搜索mod时出错

报错内容：
[16:50:00.480] 可视化 Mod 列表出错：索引超出范围。必须为非负值并小于集合大小。
参数名: index
   在 System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   在 PCL.PageDownloadMod.Load_OnFinish()
错误类型：System.ArgumentOutOfRangeException

在日志119行以及148行处（一共尝试了两次，一次关键词“mod”，一次关键词“sodium”，均无其他筛选）

![QQ图片20230219165350](https://user-images.githubusercontent.com/82522552/219938420-e35e6603-07a7-4464-a219-b643841586b7.png)

### 重现步骤

1、更新2.5.0
2、前往下载-资源-mod中搜索任意一个mod名称
3、报错

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10776474/Log1.txt)

**Comment by WForst-Breeze** [comment]
稳定复现，非常感谢您的反馈~
![image](https://user-images.githubusercontent.com/110760354/219938645-af261bd3-f65a-4c35-a436-a333875b3b17.png)

**Comment by LTCatt** [comment]
为啥我没法复现……

**Comment by WForst-Breeze** [comment]
> 为啥我没法复现……

我搜索 sodium 是可以直接复现的（）您再试试？

**Comment by haotian2004** [comment]
这是数据获取错误吗？//猜测//

**Comment by SuperMCPlayer** [comment]
咱就是说我为啥正常

**Comment by haotian2004** [comment]
网络的原因吗？

**Comment by 212112111zwl** [comment]
> 网络的原因吗？

能稳定复现，说明大概率不是网络问题

**Comment by mcwuguodadi** [comment]
> 网络的原因吗？

不是吧，和可视化有关，或许是动画的问题？

**Comment by WForst-Breeze** [comment]
#1316 提及了更加稳定的复现方式，适用于所有搜索内容：
**搜 索 时 敲 两 下 回 车**

**Comment by mcwuguodadi** [comment]
> #1316 提及了更加稳定的复现方式，适用于所有搜索内容： **搜 索 时 敲 两 下 回 车** ~这个方法我这里 100% 复现……复现方式开始往离谱的方向发展~

哈哈哈，离谱
~（这和直接搜索有什么区别）~

**Comment by mcwuguodadi** [comment]
> #1316 提及了更加稳定的复现方式，适用于所有搜索内容： **搜 索 时 敲 两 下 回 车** ~这个方法我这里 100% 复现……复现方式开始往离谱的方向发展~

哈哈哈，离谱
~（这和直接搜索有什么区别）~

**Comment by Chiloven945** [comment]
好像是在用像中文这类有候选框的语言模式输入的时候，如果我们想要打一个英文的单词一般会打完直接按回车，回车会输入自己打的东西而不是候选框的，但是PCL在输入的时候会把在输入时确定用候选框还是自己打的内容回车检测到，然后因为习惯基本上确定一个东西都是回车，所以说这就直接导致PCL检测到了两次回车，因该是两个问题首先是PCL不该检测候选框还在的时候用于确定内容的回车还有两次回车导致的报错？

**Comment by Chiloven945** [comment]
![a](https://user-images.githubusercontent.com/116699482/220638447-c9d47f1f-2960-4fe8-8dd0-42a0b009fed1.gif)
像这种我打完cre按回车对应的操作因该是确定不是进行搜索，这个原因加上我们打完按回车确定然后再次按回车开始搜索，但是PCL却检测了两次回车于是就导致报错了

**Comment by Chiloven945** [comment]
而且好像是在任意一个地方的输入框输入过程中按回车都会被检测到

**Comment by swysgh** [comment]
我刚遇到

**Comment by Chiloven945** [comment]
标题应该改成连续两次回车吧

**Comment by swysgh** [comment]
情况是这样的，就是输中文，然后回车，会进行搜索，然后如果又回车一次就会出错

**Comment by Chiloven945** [comment]
![image](https://user-images.githubusercontent.com/116699482/221359938-9cb1ac53-841e-4a3a-8e58-35f44a3cc654.png)
整合包搜索界面一样

**Comment by z0z0r4** [comment]
![image](https://user-images.githubusercontent.com/78744121/221363072-ba54a4f4-61ae-48eb-870c-a024b1964711.png)

同
