### ISSUE TITLE
模组及整合包搜索界面允许直接跳转至指定页数

### ISSUE THREAD

**Issue by WForst-Breeze** [Hex-Dragon/PCL2#1313]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

![image](https://user-images.githubusercontent.com/110760354/219938316-53c4437a-8db3-48a5-9a71-085cde4249b4.png)
如题，目前 PCL2 已经支持了 #157 提及的搜索翻页功能，但也仅仅是翻页（）希望可以允许模组及整合包搜索界面直接跳转至指定页数（包括支持直接跳转至首页和末页）。

### 原因

部分整合包制作者可能需要。
此项优化可以更好地允许用户筛选相关资源，允许用户更好地发现其适用且心仪的资源

**Comment by LTCatt** [comment]
因为技术原因，无法预测一共会有多少页，所以无法实现 :(
