### ISSUE TITLE
mod列表翻页优化

### ISSUE THREAD

**Issue by 212112111zwl** [Hex-Dragon/PCL2#1314]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

pcl在翻页时会返回到顶部，并同时加载下一页（上一页）的mod列表。这回导致返回顶部的动画出现卡顿。

建议先返回顶部再加载列表，动画不会卡顿，翻页也不会多等太久

### 重现步骤

打开mod下载界面
滚到底部
翻页

### 日志与附件

这应该不需要什么日志吧……

**Comment by WForst-Breeze** [comment]
我这里很流畅（）无法复现

**Comment by youzi-2333** [comment]
~~额，作为公测用户表示很淦~~ 源码里面是会休眠 100 ms，等待向上滚的动画结束，然后再在新的工作线程中获取 Mod 列表，这期间 Mod 列表的 Card 不可用，但是理论上是没问题的（）如果确实感觉卡顿的话可以录个屏发出来……

**Comment by 212112111zwl** [comment]
@WForst-Breeze 可能你的电脑配置比较好
上视频
https://user-images.githubusercontent.com/121177845/219944808-ab0c44cf-b2cc-44a1-b364-cc9ce24e104c.mp4

顺便补一下log（如果有帮助的话）
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10776707/Log1.txt)

**Comment by WForst-Breeze** [comment]
从录屏看的确有卡顿情况，不过我个人认为应该不算是 Bug，先换成优化 label 了，看看龙猫怎么想吧，感谢您的反馈~

**Comment by 212112111zwl** [comment]
那我稍微改一下名字

**Comment by 212112111zwl** [comment]
好像是当pcl正好在翻页时加载完下一页mod列表时才会卡一下
你们那边是怎么样的，方便发一个正常的翻页的录屏吗？

**Comment by WForst-Breeze** [comment]
> 好像是当pcl正好在回到顶部时加载完下一页mod列表时才会卡一下 你们那边是怎么样的，方便发一个正常的翻页的录屏吗？


https://user-images.githubusercontent.com/110760354/219945607-90cbb4ce-69ac-43a8-965b-43f41597f717.mp4

**Comment by 212112111zwl** [comment]
说明我网比较好，比你们提前加载出了mod列表……
然后pcl当时还在执行回到顶部的动画……
然后就卡了……

**Comment by LTCatt** [comment]
它确实会等待动画结束后再加载，卡顿估计是其他原因引起的，我也没法复现……算了（
