### ISSUE TITLE
在支持的 MC 主版本不一致时不合并不同来源的 Mod

### ISSUE THREAD

**Issue by RawDiamondMC** [Hex-Dragon/PCL2#1318]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

如题。

### 原因

例如模组“No Fade”，它在modrinth上只有1.16.x版本，1.19只存在curseforge上。

**Comment by LTCatt** [comment]
我觉得这是 Mod 作者脑抽的罕见情况……应该找 Mod 作者反馈暴打一顿（

**Comment by RawDiamondMC** [comment]
> 我觉得这是 Mod 作者脑抽的罕见情况……应该找 Mod 作者反馈暴打一顿（ ……算了我加个检测吧，如果 Modrinth 和 CF 支持的版本不一致就不合并……

这可不罕见...等1.19.4更新后一抓一把（）

**Comment by RawDiamondMC** [comment]
> 我觉得这是 Mod 作者脑抽的罕见情况……应该找 Mod 作者反馈暴打一顿（ ……算了我加个检测吧，如果 Modrinth 和 CF 支持的版本不一致就不合并……

如果要暴打的话估计打不过一群人()()
