### ISSUE TITLE
分离CF和MR下载渠道

### ISSUE THREAD

**Issue by TuanZiGit** [Hex-Dragon/PCL2#1320]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

在下载页将“资源”修改成“CurseForge”和“Modrinth”两个分区，或者在下载mod和整合包页添加选项“CurseForge””Modrinth“”自动“

### 原因

主要是有的时候我优先会选择CF罢（

**Comment by 212112111zwl** [comment]
现在两个并在一起看起来也有点不清晰，建议在搜索模组名称那一行加一个选项框（选cf或mr）
![Snipaste_2023-02-20_19-44-24](https://user-images.githubusercontent.com/121177845/220097588-28cce96c-8995-4b33-a946-78e0ff894dec.png)

**Comment by LTCatt** [comment]
……为什么非要分开呢，一起搜也没啥区别啊

**Comment by iPodtouch6557** [comment]
> ......为什么非要分开呢，一起搜也没啥区别啊

啪��，或者不分也行，在设置里设置来源就可以……？

**Comment by RawDiamondMC** [comment]
> ……为什么非要分开呢，一起搜也没啥区别啊

要么设置放一个分离modrinth与curseforge搜索？

**Comment by ZmdNotFound** [comment]
有必要……我今天下载版本的时候默认用MR下载爆404……😂

**Comment by LTCatt** [comment]
> 有必要……我今天下载版本的时候默认用MR下载爆404……😂

这是 Bug……单独交个 issue 吧

**Comment by LTCatt** [comment]
目前情况看，依然不觉得分离渠道有什么实际上的必要性。
如果确实有什么需要分离来实现的东西再考虑。

**Comment by RawDiamondMC** [comment]
> 目前情况看，依然不觉得分离渠道有什么实际上的必要性。 如果确实有什么需要分离来实现的东西再考虑。

举例：搜索Bookshelf不再能搜索到在CF上名称叫bookshelf的lib，只能通过其他依赖Bookshelf的模组（例：EnchantmentDescription）进入界面....

**Comment by LTCatt** [comment]
> 举例：搜索Bookshelf不再能搜索到在CF上名称叫bookshelf的lib，只能通过其他依赖Bookshelf的模组（例：EnchantmentDescription）进入界面....

这个应该是 bug……交个 issue 吧……

**Comment by ZmdNotFound** [comment]
> > 有必要......我今天下载版本的时候默认用MR下载爆404......😂
> 
> 这是 Bug...单独交个 issue 吧

Emmm....最近似乎又好了，看着办吧，说不定以后会不会再现（）

**Comment by WForst-Breeze** [comment]
个人认为有必要分离，原因有二：

- 如 #1513，某些 Mod 有时会在搜索页面出现两次，有失简洁性。一般而言 Curseforge 下载量会高于 Modrinth，使得前者排位较靠前，从而会导致下方我提及的问题（我不确定 #1513 修复后会变成什么样子，不过我猜测修复后下方问题依旧会存在）。
- 当玩家需需要访问资源发布页以查看详细信息时，会出现以下几种情况：
  - 玩家缺乏较好的网络环境或相关配置，导致访问 Curseforge 速度很慢，加载时间较长。而需要注意的是，正如上条所讲，Curseforge 下载量一般会高于 Modrinth，这就会使的部分玩家没能发现下方下载量较低的、易于访问的 Modrinth 发布的相同 Mod，从而不得不放弃下载该 Mod，造成较差的下载体验（举个比较极端的栗子：Economical Villager Trading，CF 下载量 118598；MR 下载量 716）
  - 玩家有较好的网络环境或相关配置，可以较快访问 Curseforge 和 Modrinth。而 Modrinth 没有 Curseforge 拥有的评论区功能，当玩家对此 Mod 存在一定疑问时，Curseforge 的评论区往往会给出部分问题的答案（如该 Mod 是否可以在最新版本正常工作等），若没有分离下载渠道，则会造成一定不便。

如果分离渠道（或是在 Mod 详情页同时展示 Mod 的 CF MR 的发布页链接），则可以使有不同需求、不同情况的玩家自由选择相应的平台渠道，可以极大优化下载体验。

**Comment by Chiloven945** [comment]
> 个人认为有必要分离，原因有二：
> 
> * 如 [下载模块出现重复项 #1513](https://github.com/Hex-Dragon/PCL2/issues/1513)，某些 Mod 有时会在搜索页面出现两次，有失简洁性。一般而言 Curseforge 下载量会高于 Modrinth，使得前者排位较靠前，从而会导致下方我提及的问题（我不确定 [下载模块出现重复项 #1513](https://github.com/Hex-Dragon/PCL2/issues/1513) 修复后会变成什么样子，不过我猜测修复后下方问题依旧会存在）。
> * 当玩家需需要访问资源发布页以查看详细信息时，会出现以下几种情况：
>   
>   * 玩家缺乏较好的网络环境或相关配置，导致访问 Curseforge 速度很慢，加载时间较长。而需要注意的是，正如上条所讲，Curseforge 下载量一般会高于 Modrinth，这就会使的部分玩家没能发现下方下载量较低的、易于访问的 Modrinth 发布的相同 Mod，从而不得不放弃下载该 Mod，造成较差的下载体验（举个比较极端的栗子：Economical Villager Trading，CF 下载量 118598；MR 下载量 716）
>   * 玩家有较好的网络环境或相关配置，可以较快访问 Curseforge 和 Modrinth。而 Modrinth 没有 Curseforge 拥有的评论区功能，当玩家对此 Mod 存在一定疑问时，Curseforge 的评论区往往会给出部分问题的答案（如该 Mod 是否可以在最新版本正常工作等），若没有分离下载渠道，则会造成一定不便。
> 
> 如果分离渠道（或是在 Mod 详情页同时展示 Mod 的 CF MR 的发布页链接，算是个折中方案 OwO），则可以使有不同需求、不同情况的玩家自由选择相应的平台渠道，可以极大优化下载体验。
> 
> ~而且从重复反馈的量上也可以看出来用户们也很希望有这个功能~

感觉可以加个选择项目，可以多选要展示的下载源（🤔

**Comment by WorldHim** [comment]
cf与mr搜索结果合并后会有mod重复，而且部分mod在cf或mr中有版本缺失（例如cf有该mod的低版本，而mr没有）

**Comment by LTCatt** [comment]
![image](https://user-images.githubusercontent.com/40348278/230656534-5c591250-8a79-4c40-bc03-2505a3da5844.png)

**Comment by TuanZiGit** [comment]
对了这里显示issue已完成那么可以给个活跃橙吗
识别码：CF90-B591-F8DE-21F0

**Comment by WForst-Breeze** [comment]
> 对了这里显示issue已完成那么可以给个活跃橙吗
> 识别码：CF90-B591-F8DE-21F0

很抱歉，新功能提案无法获得活跃橙
