### ISSUE TITLE
Mod 详情页面报错：Comp File 索引超出范围

### ISSUE THREAD

**Issue by WForst-Breeze** [Hex-Dragon/PCL2#1322]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

> 尚不确定是否与 #1311 重复，麻烦看看（）我看报错有点差别就来扔反馈了qwq  *注：第 190-215 行*

如题，在查看某 Mod 版本列表时，出现此问题
![image](https://user-images.githubusercontent.com/110760354/220116901-82d32bfe-3603-42dd-9fcf-bbd5f27e3bd2.png)
```
[21:02:47.615] 加载线程 Comp File (55) 发生运行时错误：索引超出范围。必须为非负值并小于集合大小。
参数名: index
   在 System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   在 System.Collections.Generic.List`1.get_Item(Int32 index)
   在 PCL.ModComp.CompFile..ctor(JObject Data, CompType Type)
   在 PCL.ModComp._Closure$__16-0._Lambda$__0(JToken a)
   在 System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   在 System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   在 System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   在 PCL.ModComp.CompFilesGet(String ProjectId, Boolean FromCurseForge)
   在 PCL.PageDownloadCompDetail._Lambda$__1-0(LoaderTask`2 Task)
   在 PCL.ModLoader.LoaderTask`2._Closure$__12-0._Lambda$__0()
错误类型：System.ArgumentOutOfRangeException
[21:02:47.615] [Loader] 加载器 Comp File 状态改变：Failed
```

### 重现步骤

搜索 OneBar mod 并进入其版本列表，稳定复现。尚未发现其余 Mod 出现此问题

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10784615/Log1.txt)

**Comment by youzi-2333** [comment]
为啥我无法复现……
单条 (OneBar) Mod 进入详情页面后，除了标题栏上移，不会出现啥 Bug.jpg

**Comment by WForst-Breeze** [comment]
> 为啥我无法复现…… 单条 (OneBar) Mod 进入详情页面后，除了标题栏上移，不会出现啥 Bug.jpg

估计是 Snapshot 2.5.0 才会有的问题（）毕竟这个 Mod 的信息是从 Modrinth 获取的

**Comment by AgustinLin** [comment]
我这里单条稳定复现
以及现在是只能Modrinth吗？或者有CurseForge但是优先显示Modrinth链接？

**Comment by terryaxe** [comment]
+1草一更新又炸了
![image](https://user-images.githubusercontent.com/108184807/220905472-7d02c5fb-7d0b-4165-bb85-d452846cd9d2.png)

**Comment by WForst-Breeze** [comment]
> +1草一更新又炸了 

这个是 #1311

**Comment by Chiloven945** [comment]
又来一个
![image](https://user-images.githubusercontent.com/116699482/222455794-ff4bac21-b24a-45e6-8619-e667b1143021.png)

**Comment by ZouGuaiJue** [comment]
![image](https://user-images.githubusercontent.com/102940695/222796719-c20aafa4-6866-4568-b12e-520fc72414c9.png)
问题mod加一，并且单条稳定复现，同搜索下其他mod无问题

**Comment by WForst-Breeze** [comment]
欸嘿~！换电脑啦来整个新解锁码 (╹ڡ╹ )

82CB-4623-DC92-C1EF

**Comment by LTCatt** [comment]
你的解锁码：JGCFD9C4XTjMxpd2k1GVOqJnTOoAPS5m
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
