### ISSUE TITLE
启动游戏时按回车键不是取消而是再次启动

### ISSUE THREAD

**Issue by Xx114514xX1819** [Hex-Dragon/PCL2#1325]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

启动游戏时按回车键不是取消而是再次启动，非常不符合常理

### 重现步骤

1、随便启动一个游戏
2、在启动时按回车键

### 日志与附件

[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10789559/Log5.txt)
[Log.txt](https://github.com/Hex-Dragon/PCL2/files/10789561/Log.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10789562/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10789563/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10789564/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10789565/Log4.txt)
![YP%6$~~IS4FY)4})J%O0{@5](https://user-images.githubusercontent.com/114345474/220247398-1b955045-ef37-4a76-ac8d-c06966e91cf8.png)

**Comment by LTCatt** [comment]
改成了按回车键无效 =。=

**Comment by Xx114514xX1819** [comment]
FFF2-E8FE-4BF7-58A2

**Comment by LTCatt** [comment]
你的解锁码：4h/jp8idKjm0C8fsYuOF9uLzab4pKUEa
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
