### ISSUE TITLE
下载OptiFine时显示Java Virtual Machine Launcher

### ISSUE THREAD

**Issue by DreamYao520** [Hex-Dragon/PCL2#1326]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在下载Forge和Optifine的时候提示
Error: Invalid or corrupt jarfile
C:\Users\ASUS\AppData\Roaming\PCLVJavaWrapper.jar

![R6CCMWOO 8}CAGCUNQKK)MP](https://user-images.githubusercontent.com/123301307/220254868-d555be5a-bece-4ea4-a7d9-0403bf49d598.png)

### 重现步骤

点击下载-自动安装
选择1.19.2版本-依次选择Optifine:1.19.2 I1-Forge:43.2.4

![0 BG2E_XT@758OKJ{{HW%E9](https://user-images.githubusercontent.com/123301307/220255273-ae262205-03ec-46f8-a4dd-1cec6d9cd422.png)

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10789864/Log3.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10789866/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10789867/Log2.txt)

**Comment by youzi-2333** [comment]
与 #1126 重复，感谢您的反馈～

下次提交反馈前请先在 Issues 页面搜索，多谢配合。
