### ISSUE TITLE
还是关于 强制Unicode字体 的事

### ISSUE THREAD

**Issue by GTEMYee** [Hex-Dragon/PCL2#1328]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

添加一个复选框
在没有 options.txt 情况下启动 Minecraft 时仅设置中文而且不同时启用 强制Unicode字体

### 原因

不用再多点一次
而且某些服务器已经开始ban强制Unicode字体了

**Comment by youzi-2333** [comment]
与 #565 重复，感谢您的反馈～

下次提交前请先在 Issues 页面搜索，多谢配合。

**Comment by iPodtouch6557** [comment]
不是，这家伙跟那个荣家诺二次反馈国足的那个不就一样的吗……

**Comment by youzi-2333** [comment]
~~我去原来 565 也是他反馈的~~ 上次反馈已经拒绝了，请不要重复提交反馈……

**Comment by GTEMYee** [comment]
> ~我去原来 565 也是他反馈的~ 上次反馈已经拒绝了，请不要重复提交反馈……

但是上一次我没有提及 options.txt，或许你已经看到了

**Comment by LTCatt** [comment]
> 而且某些服务器已经开始ban强制Unicode字体了

为啥啊？

**Comment by GTEMYee** [comment]
> > 而且某些服务器已经开始ban强制Unicode字体了
> 
> 为啥啊？

有服务器登录插件，而且有些人会把 l 看成 1
