### ISSUE TITLE
mod相同版本重复显示

### ISSUE THREAD

**Issue by 212112111zwl** [Hex-Dragon/PCL2#1330]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

不知道是不是pcl的问题
fpsreducer1.19.2里面一下出现了一大堆一模一样的文件，如下图
![image](https://user-images.githubusercontent.com/121177845/220353475-fbbbcd8c-dcca-49e7-862b-7baf915ac329.png)
任意下了两个，用winmerge比较了一下：
![image](https://user-images.githubusercontent.com/121177845/220353671-edbad31f-b1b5-48e0-b5aa-05238fe04bbf.png)

### 重现步骤

mod搜索fpsreducer，进去之后选1.19.2

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10793811/Log1.txt)

**Comment by WForst-Breeze** [comment]
我依稀记得这个是有朋友反馈过的，被拒绝了……（）但我找不到那个 issue 了……应该是 CF 的 api 问题

**Comment by 212112111zwl** [comment]
那如果是这样的化，龙猫你看看能不能加一个判断拦截一下啥的，如果不行或者嫌麻烦就算了🤣
