### ISSUE TITLE
在百宝箱栏添加滚动条

### ISSUE THREAD

**Issue by Chiloven945** [Hex-Dragon/PCL2#1334]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

百宝箱的自定义下载在都报错的时候，如果窗口很小的话那按钮直接被挤没了
![image](https://user-images.githubusercontent.com/116699482/220643801-6eb50db8-7424-4a32-8bb7-f8511b72f9a6.png)
建议加个滚动条

### 原因

虽然填完了就不会超出去但是真的好丑

**Comment by youzi-2333** [comment]
虽然但是，我感觉这像一个 Bug（）
先加上待处理等回复吧，感谢您的反馈～

**Comment by LTCatt** [comment]
没啥影响，算了 =。=

**Comment by Chiloven945** [comment]
主要是太丑了（

**Comment by 212112111zwl** [comment]
可以尝试把pcl窗口调大一点，拖住启动器右下角就能改变窗口大小

**Comment by Chiloven945** [comment]
你这搞得像我不会缩放一样，我当然知道这样可以啊，但是这不应该是因为窗口为最小所以说才导致这个Bug的出现，这个必须是要适配在范围内所有窗口大小的

**Comment by 212112111zwl** [comment]
我的目的是想让你用起来不觉得“太丑了”，并不是说你这个提议不好，希望你能理解

**Comment by Chiloven945** [comment]
？这是加了吗？

**Comment by LTCatt** [comment]
加了 =。=
