### ISSUE TITLE
在 Mod 管理页添加跳转到对应的 Mod 下载页的选项

### ISSUE THREAD

**Issue by qizri** [Hex-Dragon/PCL2#1336]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

在百科搜索按钮旁边加入一个按钮（这个按钮最好直接显示出来），可以直接打开该mod的pcl下载界面，或者直接打开该模组pcl的mod搜索页面，就像直接打开百科搜索页面一样。此时需要再加入一个按钮便于快速跳转回模组页面。

### 原因

例如我将1.12.2的模组更新到1.16.5，这需要在pcl上一个一个的输入模组名称搜索出来再下载，大量模组下载使得过程十分繁琐。（这些个模组英文名字，中文名字千奇百怪，打字前还要查看名字打对没，好麻烦！！！）（即使复制粘贴也麻烦！！！）

加入这个按钮后我就可以在1.12.2的模组页面直接点击按钮跳转到模组下载页面，或者跳转到模组搜索页面，下载想要下载的版本，这将大大简化下载过程。

这样也可以快速检测模组更新情况。而不是每次都要从模组页面退出来打开下载页面搜索模组名称，最后才能查看
和下载新版本。

当然要是能更新个一键批量升级模组版本的按钮就更好了，没有对应版本的模组就列出来，这样简直完美，不用我一个一个搜索下载了。（搜索半天发现没有更新，或者没有对应版本！！！）

**Comment by Chiloven945** [comment]
Collaborator去哪了

**Comment by Chiloven945** [comment]
> 如果加入了这个功能确实挺好，就是万一这玩意把资源占用搞大了怎么办 而且 ![image](https://user-images.githubusercontent.com/114737601/220849720-f82d1eca-8523-4dfc-accc-3f651d0deb1c.png) _也需要去全网查找_ 。。。 等其他人来吧

之前好像有一个类似的，是可以转成中文名，但是被拒绝了所以说我估计做不到

**Comment by Chormore-EDGE** [comment]
> 我感觉应该找百科和pcl合作会更好

看鸣谢列表，已经合作过了

**Comment by YUANXINGlingyun** [comment]
这新功能提案好大,龙猫来看看吧

**Comment by hejiehao** [comment]
> > 我感觉应该找百科和pcl合作会更好
> 
> 看鸣谢列表，已经合作过了
> 

鸣谢和合作是两个意思，后面也写了是爬虫

**Comment by WForst-Breeze** [comment]
> Collaborator去哪了

别着急……我们也不是 24h 在线的（）谅解一下~qwq

---
先提供一下您提及的部分期望的相关答复
> 例如我将1.12.2的模组更新到1.16.5，这需要在pcl上一个一个的输入模组名称搜索出来再下载，大量模组下载使得过程十分繁琐。

#728，已被拒绝

> 当然要是能更新个一键批量升级模组版本的按钮就更好了，没有对应版本的模组就列出来，这样简直完美，不用我一个一个搜索下载了。

#102，暂缓处理

---
回到反馈本身，其实之前有一个类似反馈 #1053，但是鉴于与 #728 **需求类似**，于是就 close 了。不过看来还是有挺多人迫切需要这个功能的，因此我就先开着，尽管可能在技术层面可能会有很多需要解决的问题……但还是先等待开发者进一步考虑吧~ 已初步确认，感谢您的反馈~
