### ISSUE TITLE
无法将类型 "String" 的实例添加到类型 "UIElementCollection" 的集合，仅允许类型 "UlElement" 的项。

### ISSUE THREAD

**Issue by YUANXINGlingyun** [Hex-Dragon/PCL2#1339]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://user-images.githubusercontent.com/109946426/220929844-6eae1f88-8355-4005-8de3-1982aaa88cbf.png)

如图，加载 xaml 文件时意外报错

### 重现步骤

加载附件中的 xaml 主页自定义文件

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10814281/Log1.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10814283/Log4.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10814288/Log3.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10814284/Log5.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10814286/Log2.txt)
[Custom.xaml](https://github.com/Hex-Dragon/PCL2/files/10814292/Custom.xaml.txt)

**Comment by YUANXINGlingyun** [comment]
没人...

**Comment by Chormore-EDGE** [comment]
等人吧，我Java没学完呢qwq

**Comment by Chormore-EDGE** [comment]
复现成功一半，错误不一样
![image](https://user-images.githubusercontent.com/114737601/221113293-a87b3cf2-a457-40f4-a0db-aecd779c0a58.png)

**Comment by Chormore-EDGE** [comment]
奇怪
为啥啊
我和你的错误不一样
![image](https://user-images.githubusercontent.com/114737601/221117373-d21b155c-dcc5-4d0d-b700-7a1b2875c02c.png)
老是ka'z卡在这个位置

**Comment by Chiloven945** [comment]
你这issue的标题对我这个强迫症患者很窒息（

**Comment by YUANXINGlingyun** [comment]
草，才发现 Title 怪怪的

**Comment by LTCatt** [comment]
这个应当是自定义的文件写错了，不是 PCL 自身自带的 Bug？

**Comment by YUANXINGlingyun** [comment]
哈？

**Comment by YUANXINGlingyun** [comment]
xaml没问题啊？

**Comment by LTCatt** [comment]
![image](https://user-images.githubusercontent.com/40348278/221353403-f1e6bda8-a809-4c7e-ab65-bcc8709de297.png)

必须使用 x:Name 而非 Name

**Comment by YUANXINGlingyun** [comment]
额

**Comment by YUANXINGlingyun** [comment]
最新版改了。。。以前 Name 是可以的。。。

**Comment by YUANXINGlingyun** [comment]
不对，不是这个问题

**Comment by YUANXINGlingyun** [comment]
![image](https://user-images.githubusercontent.com/109946426/221391601-15cc40a4-0061-4a26-a170-8227ba6cea02.png)
![image](https://user-images.githubusercontent.com/109946426/221391608-d0880ca5-7c13-4d63-b5ec-89db6fae39d5.png)
见鬼，只留下卡片也报错

**Comment by YUANXINGlingyun** [comment]
猫猫?
@LTCatt
