### ISSUE TITLE
Mod列表显示Mod版本

### ISSUE THREAD

**Issue by sssysy** [Hex-Dragon/PCL2#1342]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

部分作者在modrinth上传的mod不会把模组名称写到标题上，而是写到了version number里面。
可以把version number显示在可选版本列表的副标题中。
![软件内不显示版本号](https://user-images.githubusercontent.com/79786006/221174799-bff90187-bace-41db-a078-eb0f1c8842e3.png)
![版本号位置](https://user-images.githubusercontent.com/79786006/221174807-ae86a56e-3e62-4a68-b4fd-8f0890495135.png)

### 原因

这项优化让我可以更方便地查找mod的指定版本。
如果没有这项优化，我每次都必须打开modrinth网页查看version number，让操作变得很麻烦。

**Comment by IF-desu** [comment]
这应该算是bug了吧。。
