### ISSUE TITLE
模组与整合包界面搜索英文出现错误

### ISSUE THREAD

**Issue by XueLiMC** [Hex-Dragon/PCL2#1343]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

当我在Mod 与 整合包 搜索界面搜索搜索英文均出现
【可视化Mod列表出错:索引超出范围。必须为非负值并小于集合大小。
参数名: index
在PCL.PageDownloadMod.Load. _OnFinish()
错误类型: System.ArgumentOutOfRangeException】

### 重现步骤

点击Mod或整合包界面搜索英文就会触发bug

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10823977/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10823980/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10823981/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10823990/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10823993/Log5.txt)

**Comment by youzi-2333** [comment]
与 #1311 #1322 类似，感谢您的反馈。

如果下一个版本的 PCL2 仍然没有修好请联系重开……
