### ISSUE TITLE
Mod列表显示Mod版本(#1342是我不小心点错然后关了)

### ISSUE THREAD

**Issue by sssysy** [Hex-Dragon/PCL2#1344]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

部分作者在modrinth上传的mod不会把模组名称写到标题上，而是写到了version number里面。
可以把version number显示在可选版本列表的副标题中。
![软件内不显示版本号](https://user-images.githubusercontent.com/79786006/221177379-a3c82963-293c-4230-8e88-f220d57e2113.png)
![版本号位置](https://user-images.githubusercontent.com/79786006/221177393-16338297-7b82-4f0a-b37c-4196154d4e28.png)

至于#1342中 [IF-desu](https://github.com/IF-desu) 说是bug，我觉得不算。因为modrinth上大部分作者是把mod版本一起写在标题里然后再写一个在version number的，这个时候标题有版本号是看得到的。
但是有些作者并不会把版本号写在标题上，只写在了version number里面，如果每个版本的标题是一样的话就会显示的一样

### 原因

这项优化让我可以更方便地查找mod的指定版本。
如果没有这项优化，我每次都必须打开modrinth网页查看version number，让操作变得很麻烦。

**Comment by youzi-2333** [comment]
~~公测用户表示很淦~~先加上待处理了……感谢您的反馈~

**Comment by WForst-Breeze** [comment]
原始 Issue：#1342 已初步确认，感谢您的反馈~
（下次误关可以自己点 Reopen issue，或者说留个言让我们开也可以的，不用再开一个 Issue……qwq

**Comment by Chiloven945** [comment]
的确有点致命这个
