### ISSUE TITLE
[优化] 使用本地文件作为帮助文档图片时，不锁定该文件

### ISSUE THREAD

**Issue by youzi-2333** [Hex-Dragon/PCL2#1345]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://fasthub.cc/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://fasthub.cc/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

例如使用 `<Image Margin="0,0,0,4" Source="{path}image.png" />` ，刷新帮助文档后，本文件被锁定，可读不可写。

### 原因

这项优化能够让我更好的修改帮助文档的图片。如果没有这项优化，每次修改前必须关闭 PCL2（或删除 Image 控件再刷新帮助文档）。

**Comment by youzi-2333** [comment]
突然意识到一个问题，这是 WPF 的事情，不是 PCL2 的（）

如果确实是 WPF 的问题的话，可以改成“复制到缓存目录再加载帮助文档”……

**Comment by LTCatt** [comment]
看了看，确实没法改。Image 是 WPF 的原生行为，我没法去改它的文件读取……
