### ISSUE TITLE
*Minecraft又双无法启动，系统和显示器还出问题了

### ISSUE THREAD

**Issue by Chormore-EDGE** [Hex-Dragon/PCL2#1352]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃不是 PCL2 的原因，请 **不要** 提交反馈。你可以在 QQ 群里或者论坛找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是游戏本身的问题，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

就是玩服务器的时候minecraft突然卡的要死，系统和dwm处于假死状态，无奈只能重启（关电源再开）之后minecraft无法启动，给了提示窗口（错误窗口）
![}_E34Z1XHHQE`WX3KY` O7R](https://user-images.githubusercontent.com/114737601/221349571-c60df45d-ddeb-40f9-b770-cf84fc67a1d4.png)
屏幕还有残影

### 错误报告、日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10830714/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10830715/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10830716/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10830718/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10830719/Log1.txt)

**Comment by Chormore-EDGE** [comment]
问了一下，说是显卡驱动炸了，可是我没换过或者更新驱动啊

**Comment by Chormore-EDGE** [comment]
https://www.intel.cn/content/www/cn/zh/support/articles/000058790/graphics.html

**Comment by Chormore-EDGE** [comment]
显卡驱动炸了，但还是想问一下为什么会炸

**Comment by Chormore-EDGE** [comment]
重新安装就好了

**Comment by Chormore-EDGE** [comment]
![image](https://user-images.githubusercontent.com/114737601/221350327-bd77c5ba-e289-4316-84d0-6283acc0c43e.png)

**Comment by YUANXINGlingyun** [comment]
请前往[提问板块](github.com/Hex-Dragon/PCL2/discussions)提问

**Comment by YUANXINGlingyun** [comment]
既然修好了issues可以关了

**Comment by Chormore-EDGE** [comment]
好的，谢谢。
