### ISSUE TITLE
部分情况下弹出窗口边缘阴影有瑕疵

### ISSUE THREAD

**Issue by Chiloven945** [Hex-Dragon/PCL2#1356]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

弹出窗口时边缘阴影有瑕疵
![image](https://user-images.githubusercontent.com/116699482/221360262-777b3fb6-3460-41b1-b7a3-2460067bcac0.png)这是窗口为最小时的情况，有明显的棱角
![image](https://user-images.githubusercontent.com/116699482/221360330-3dc709a6-ef31-4ddf-8c7c-5fa6ca479921.png)放大后恢复正常

今日人品的弹窗是不论大小都有瑕疵
![image](https://user-images.githubusercontent.com/116699482/221360451-12d0546a-d7c1-45dd-bcf5-90ea9e076a43.png)
![image](https://user-images.githubusercontent.com/116699482/221360462-cca5ac50-110a-4f7b-9e12-c9cdd335c2ae.png)

### 重现步骤

任意打开一个弹出窗口

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10831298/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10831299/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10831300/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10831301/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10831302/Log5.txt)

**Comment by WForst-Breeze** [comment]
我这里未能复现，还有朋友可以稳定复现此问题的吗（

**Comment by Chiloven945** [comment]
![image](https://user-images.githubusercontent.com/116699482/221375338-bc861022-4beb-41d2-b551-2d5b9424a179.png)
因该看得出来这东西……

**Comment by YUANXINGlingyun** [comment]
![image](https://user-images.githubusercontent.com/109946426/221390331-d0ce719c-7cb8-41c4-aa71-c43bd1d0b036.png)
![image](https://user-images.githubusercontent.com/109946426/221390340-0f276b53-5776-4f23-bb3d-7b2afc45317f.png)
没用

**Comment by YUANXINGlingyun** [comment]
不过我有种办法能把 local:MyCard 的边角给显示出来，就是加上 Background="#fff"
![image](https://user-images.githubusercontent.com/109946426/221390386-a877566e-10e9-42de-a55c-978e5f714b59.png)

**Comment by youzi-2333** [comment]
弹窗应该不区分怎么触发，都是调用 `MyMsgBox` 函数……我现在也没带电脑……（悲）

如果还有人没法复现的话，可以挂一个需要帮助的 Label……

**Comment by youzi-2333** [comment]
> ![image](https://user-images.githubusercontent.com/116699482/221375338-bc861022-4beb-41d2-b551-2d5b9424a179.png) 
> 应该看得出来这东西……

um 我待会回去复现一下……

**Comment by LTCatt** [comment]
这是 WPF 的阴影控件的 Bug，微软的问题，我修不了 :(
