### ISSUE TITLE
改进选择版本的选项

### ISSUE THREAD

**Issue by MangoGong** [Hex-Dragon/PCL2#1358]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

您好，首先感谢开发者对MC圈子做出的巨大贡献
这里提点建议
1.PCL2启动器在右侧由巨大的空余空间，虽然可以放信息流，但是有些人不会（比如我），建议加入预设的信息流选项。
2.现版本切换mc版本的过程有些繁琐，建议简化步骤（可以把选择列表塞到第一点所说的地方去？）

### 原因

此举可进一步优化操作流程，并显著提高启动器的易用性

**Comment by Chiloven945** [comment]
个人感觉目前挺好，因为我旁边用来放启动日志（

**Comment by WForst-Breeze** [comment]
> PCL2启动器在右侧由巨大的空余空间，虽然可以放信息流，但是有些人不会（比如我），建议加入预设的信息流选项。

此条我记得有人提及过，不过具体找不到了（）您可以尝试使用 https://news.bugjump.net 的自定义主页，先前 PCL2 有过这个打算，不过由于诸多原因被放弃了

已初步确认，感谢您的反馈~

**Comment by bwtx2023** [comment]
点三下切换+启动游戏也不麻烦吧...

**Comment by MangoGong** [comment]
> 点三下切换+启动游戏也不麻烦吧...

在重复使用的时候的确感觉效率有点低了，况且这只是提个建议，重点在第一点（

**Comment by 212112111zwl** [comment]
那请问你建议预设信息流里应该加一些什么内容呢？@MangoGong

**Comment by WForst-Breeze** [comment]
第一条不太可能制作，请见 [#190 龙猫的回复](https://github.com/Hex-Dragon/PCL2/issues/190#issuecomment-1271911821) 
就看看第二条会不会考虑了，概率也不大……毕竟说实话不算太麻烦，没有太大必要
>之前有和 Light-Beacon 商量过把新闻主页转正，问题其实蛮多的……
首先怕被攻击，至少刷流量都会很头疼，其次需要有人时时刻刻进行维护，而我肯定没这心思（这代表着这玩意儿肯定得第三方，谁去搞实时翻译什么的）……

感谢建议~

**Comment by MangoGong** [comment]
> 那请问你建议预设信息流里应该加一些什么内容呢？@MangoGong

如上面回答所提到的，mc更新日志、mc启动日志还有我建议的版本选择，建议增加尽可能多的自定义选项。谢谢！

**Comment by LTCatt** [comment]
已添加了 #1368 作为此条的替代（
