### ISSUE TITLE
关于启动器的自定义主页问题

### ISSUE THREAD

**Issue by Spturate** [Hex-Dragon/PCL2#1364]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

像这个复杂按钮，希望能适配启动器缩放进行等比缩小，图里这个按钮已经显示不全了
<img width="638" alt="屏幕截图_20230226_132614" src="https://user-images.githubusercontent.com/30800649/221394023-f06a586d-e51a-46a3-ac6d-883831ebcaee.png">

### 原因

只是有时候看着不舒服

**Comment by Hatsushigure** [comment]
这不应该由龙猫解决吧...
如果 `WPF` 支持直接在 `xaml` 里写等比缩小，那么你可以自己写。如果没有直接的支持，那也不方便从应用层面去改，毕竟这个 `xaml` 是你自己写的，龙猫也不可能知道里面有什么。

**Comment by youzi-2333** [comment]
您好，
自定义主页使用 WPF 实现，并且 PCL2 的 `local:MyButton` 控件支持设置按钮长宽。如果觉得教程文件看着难受，可以到 [LTCatt/PCL2Help](https://github.com/LTCatt/PCL2Help) 提交 Pull Request。感谢您的反馈～

**Comment by LTCatt** [comment]
可以使用 Grid 来自适应长宽，自行百度 WPF 的 Grid 教程 =。=
