### ISSUE TITLE
添加一键更新已安装模组的功能

### ISSUE THREAD

**Issue by Hatsushigure** [Hex-Dragon/PCL2#1365]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

在模组管理页面添加更新模组的选项，参考 HMCL ~~[doge]~~

### 原因

现在更新模组比较麻烦，需要先搜索最新版下载，再删除旧版。希望可以直接在管理页面一键完成这个操作。

**Comment by youzi-2333** [comment]
与 #102 重复，感谢您的反馈～

下次提交新 Issue 前，请先在 Issues 页面搜索，感谢配合。

**Comment by Hatsushigure** [comment]
> 与 #102 重复，感谢您的反馈～
> 
> 下次提交新 Issue 前，请先在 Issues 页面搜索，感谢配合。

az 搜过，但没搜出来...可能是没看到吧
