### ISSUE TITLE
添加强制更新功能，不更新不给用

### ISSUE THREAD

**Issue by Chinese-Cyq20100313** [Hex-Dragon/PCL2#1366]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

为了防止dddd的情况再次发生
建议添加强制更新功能，并添加恶意降级检测，防止利用旧版BUG，或者热修补（

### 原因

（示例）
由于目前可以PCL2降级和选择是否更新没有任何限制，所以现在可以通过降级来利用旧版BUG
可以通过强制升级来防止BUG复现，确保所有反馈的内容是最新版本的BUG

（隔壁BakaXL就是 [更新] | [或者更新]

**Comment by iPodtouch6557** [comment]
好像pcl2对于极其老旧的版本有限制的，我就遇到过（~alpha1.2用到2.0.5发布~）
但是对于较旧的版本，比如我现在用的2.3.2，没有
~最后，别急着加，我还没处理好windefender误报删除的事呢~

**Comment by LTCatt** [comment]
PCL 可以在 **必要的情况下** 强制要求更新，但目前还没遇到这种情况 =。=

**Comment by iPodtouch6557** [comment]
> PCL 可以在 **必要的情况下** 强制要求更新，但目前还没遇到这种情况 =。=

那为啥修复了启动令牌的事不强制更新呢，还是我不知道？

**Comment by youzi-2333** [comment]
> 那为啥修复了启动令牌的事不强制更新呢，还是我不知道？

Minecraft 的 Token 会在 24 小时后吊销，而且如果在此以后重新使用 PCL2 用相同登录方式启动了 Minecraft，同样会吊销旧的 Token。即使拿到了 Token 也没啥用，毕竟帮别人解决了崩溃的问题，那个人自然而然就会再次启动游戏，内群里面的 Token 也没用了……

再说这又不是国防部密码，盗了就盗了……（）
