### ISSUE TITLE
支持下载ftb整合包

### ISSUE THREAD

**Issue by aaronliu0130** [Hex-Dragon/PCL2#137]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

整合包下载增加ftb源，可以参考gdlauncher和删掉之前的multimc

### 原因

我需要这个功能来玩新的ftb整合包。很多人都有ftb整合包的需求，但如果没有这个功能，就不能不用ftb垃圾启动器了。
或者也可以换到gdlauncher或者自己编译个multimc
救命qt找不到我的库

**Comment by LTCatt** [comment]
因为 FTB 整合包有额外的需求（例如更新）， **且可能存在法律问题** ，暂时不考虑制作相关兼容。

**Comment by aaronliu0130** [comment]
😢

**Comment by aaronliu0130** [comment]
法律问题是什么来着？

**Comment by LTCatt** [comment]
唔，考虑到其他启动器有的已经做了，感觉还是可以考虑一下的 =。=
