### ISSUE TITLE
支持直接导入本地自定义主页文件

### ISSUE THREAD

**Issue by WForst-Breeze** [Hex-Dragon/PCL2#1370]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

如题，目前 PCL2 仅支持从 PCL2 文件夹下的 Custom.xaml 文件中加载主页布局。希望可以直接支持直接导入本地自定义主页文件，而不用经历需要先 **打开 PCL2 文件夹** 再 **将文件拖入并改名为 Custom.xaml** 再 **刷新** 的繁琐过程。

### 原因

1. 方便用户直接且快捷地使用从互联网上下载获取的自定义主页
2. 提高更换效率

**Comment by 212112111zwl** [comment]
建议支持将xaml文件拖入pcl2窗口以导入自定义主页文件（并自动刷新）
