### ISSUE TITLE
同时启动多个pcl时出现调用目标发生异常

### ISSUE THREAD

**Issue by sb250AAA** [Hex-Dragon/PCL2#1371]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

多次启动pcl出现很多这样的对话框，关都关不完（使用右键关闭所有窗口也无法关闭）
![捕5获](https://user-images.githubusercontent.com/121080352/221404250-030be114-71e6-4736-8034-769defafd1cd.JPG)

### 重现步骤

1.使用连点器多次点击pcl任务栏快捷方式（连点器间隔设置为最大）

### 日志与附件

[Log.txt](https://github.com/Hex-Dragon/PCL2/files/10833435/Log.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10833436/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10833437/Log2.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10833438/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10833439/Log5.txt)

**Comment by youzi-2333** [comment]
首先，`HRESULT` 通常是系统配置问题，不是 PCL2 的；其次，PCL2 不支持多开；连按多次 Enter 确实可以多开，但是这被归为“刻意卡的 Bug”不会处理。感谢您的反馈～
