### ISSUE TITLE
在玩mc的时候突然动不了，任何按键失效，wasd偶尔可用

### ISSUE THREAD

**Issue by Chormore-EDGE** [Hex-Dragon/PCL2#1373]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

玩minecraft突然按键用不了，检查了按键绑定没啥问题，也不知道咋回事只能按esc，wasd偶尔能按几下

### 重现步骤

我也不知道，玩着玩着就动不了了
_备注：这个bug是在我玩第三方服务器突然出现的，只能关游戏再启动才好，然后过一段时间又双缀出现_

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10835721/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10835722/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10835723/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10835724/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10835725/Log2.txt)

**Comment by Chormore-EDGE** [comment]
额...忘说了，版本我用的是1.19.3

**Comment by iPodtouch6557** [comment]
自己的事，~我玩十个小时都没遇到过~

**Comment by Chormore-EDGE** [comment]
好吧，我研究研究，关了

**Comment by Chormore-EDGE** [comment]
关闭聊天

**Comment by Chormore-EDGE** [comment]
- [ ]
