### ISSUE TITLE
整合包导出功能。

### ISSUE THREAD

**Issue by wsd-baobao** [Hex-Dragon/PCL2#1377]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

把一个整合包单独打包来方便分享。

### 原因

（示例）
我需要这个功能来分享自制的整合包。很多人都有和朋友联机的需求，但如果没有这个功能，就不能方便的对整合包进行分享，不利于游戏的发展。

**Comment by Chormore-EDGE** [comment]
**下次提交issues别那么客气就行了**怎么说呢，你这个和mod另存为很像，可以加

**Comment by dargoncat** [comment]
与 #98 重复

**Comment by iPodtouch6557** [comment]
关了吧，重复了，我老早以前就见过两个重复了的

**Comment by Chiloven945** [comment]
6
