### ISSUE TITLE
模组搜索界面无法显示模组来源

### ISSUE THREAD

**Issue by qndm** [Hex-Dragon/PCL2#1378]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

模组搜索界面没有显示模组来源
![屏幕截图_20230228_210247](https://user-images.githubusercontent.com/69710718/221862077-55676c27-f1f9-43f6-9185-d2fec6165881.png)

### 重现步骤

1、点击下载
2、点击[Mod]
3、随便搜个模组（例如Create），等待加载完成，可以发现没有显示模组来源

### 日志与附件

（不要问为什么只有一个，因为怕是缓存之类的问题就把缓存和日志都删了，但还是有这个问题）
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10850799/Log1.txt)

**Comment by 212112111zwl** [comment]
我也不会显示，清除缓存等基本操作过后依然不会……

**Comment by WForst-Breeze** [comment]
基本确认问题存在，这是 #1375 的后续讨论，感谢您的反馈~

**Comment by LTCatt** [comment]
仅在打开调试模式时才会显示来源
