### ISSUE TITLE
下载时显示未能找到路径

### ISSUE THREAD

**Issue by Uriakgnay** [Hex-Dragon/PCL2#1382]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

下载时无法找到路径,下载任何东西无论整合包,mod,游戏本体都是
下载整合包文件失败
→ 文件下载失败：G:\我的世界\灵雪的童话养老生存整合包\灵雪的童话养老生存整合包\.minecraft\versions\All the Magic Spellbound - ATMS\原始整合包.zip
未能找到路径“C:\Users\18323\AppData\Local\Temp\PCL\Download\2305_2397_832780.tmp”的一部分。（https://media.forgecdn.net/files/4087/823/Spellbound-2.3.0.zip）
远程服务器返回错误: (404) 未找到。（https://edge.forgecdn.net/files/4087/823/Spellbound-2.3.0.zip）
→ 未能找到路径“C:\Users\18323\AppData\Local\Temp\PCL\Download\2305_2397_832780.tmp”的一部分。
   在 PCL.ModNet.NetFile.Thread(NetThread Info)
错误类型：System.IO.DirectoryNotFoundException

### 重现步骤

1、点击下载
2、出现问题

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10878461/Log1.txt)

**Comment by Chormore-EDGE** [comment]
还是怀疑路径问题，把安装路径换英文路径（不带中文）试试
qwq但我觉得八成不是这个问题

**Comment by Chiloven945** [comment]
能不能带个图片啊（）

**Comment by Chiloven945** [comment]
不是路径，PCL支持非英文路径的，应该是权限问题，报错System.IO.DirectoryNotFoundException，给管理员权限运行看看

**Comment by WForst-Breeze** [comment]
请将 PCL2 更新至最新版本，并检查问题是否依然存在，感谢您的反馈~
```
[12:55:56.061] [Start] 程序版本：Release 2.4.4（272）
```

**Comment by WForst-Breeze** [comment]
自反馈提交日算起，您未能在8天内完成信息补充。请您在一周内尽快完成上述信息补充，否则此反馈将会被关闭，感谢您的支持和理解~

**Comment by Chormore-EDGE** [comment]
![image](https://user-images.githubusercontent.com/114737601/224466392-069718d4-4aa7-441d-9d25-b31e388fdcad.png)
zhe'g这个bug在2.5.1无法复现

**Comment by WForst-Breeze** [comment]
超时关闭，可随时在此处补充，感谢您的反馈~
