### ISSUE TITLE
游戏窗口标题在全局设置之后不能把单个版本的游戏窗口标题改为默认

### ISSUE THREAD

**Issue by Ethanqwq** [Hex-Dragon/PCL2#1388]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

可以把默认改成—个准确的文字或符号

### 原因

在玩一些整合包的时候，一些整合包会有固定标题。然后我自己也设了标题，就会导致标题一直在闪

**Comment by WForst-Breeze** [comment]
您的意思可能是：在修改了全局游戏窗口标题后，允许设置单个版本的游戏窗口标题为默认
已初步确认，感谢您的反馈~

**Comment by LTCatt** [comment]
额……不太好做，想不出来合适的 UI 咋折腾。
手动改成整合包自定义的标题吧…………抱歉（
