### ISSUE TITLE
建议在文件名里直接体现详细版本号

### ISSUE THREAD

**Issue by iPodtouch6557** [Hex-Dragon/PCL2#1398]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

就是把原来的
![image](https://user-images.githubusercontent.com/118656946/222934865-8c189f98-b0d6-4e4d-8995-6b11c13bb5e6.png)
**直接替换成无需修改文件名就有的**，例如
![image](https://user-images.githubusercontent.com/118656946/222935042-d2021adf-948b-41f1-9b46-0f39be7ce2ce.png)

### 原因

（示例）
这项优化让我可以更方便地显示不同版本
我有时会多个pcl版本混着用，如果没这个功能我还得手动标（）

**Comment by WForst-Breeze** [comment]
个人感觉没太大必要😐已初步确认，感谢您的反馈~

**Comment by WTP016-CN** [comment]
好像所有启动器自动更新的时候都没有这个功能的说……例如BakaXL和HMCL

**Comment by iPodtouch6557** [comment]
> 好像所有启动器自动更新的时候都没有这个功能的说……例如BakaXL和HMCL

HMCL实测有的，每次更新都改名字
BakaXL不改名，但是有详细版本

**Comment by hejiehao** [comment]
> > 好像所有启动器自动更新的时候都没有这个功能的说……例如BakaXL和HMCL
> 
> HMCL实测有的，每次更新都改名字
> BakaXL不改名，但是有详细版本

hmcl如果你把原来的文件名改掉就不会改名字

**Comment by LTCatt** [comment]
更新时改名会导致有的玩家的快捷方式失效，这是刻意的设计决策，抱歉（

**Comment by iPodtouch6557** [comment]
> 更新时改名会导致有的玩家的快捷方式失效，这是刻意的设计决策，抱歉（
可是为啥hmcl会改呢
