### ISSUE TITLE
古老的bug又复现了-MOD下载界面，标题文字偏移

### ISSUE THREAD

**Issue by Fenck** [Hex-Dragon/PCL2#1399]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

**部分**MOD下载界面，标题文字**偏移**
![屏幕截图 2023-03-05 105119](https://user-images.githubusercontent.com/121434335/222939071-b4fffd96-38c8-48f5-bc59-431f78cdf69c.png)

### 重现步骤

1、点击下载
2、点击Mod
3、搜索Dynamic-FPS
4、左键Dynamic-FPS

### 日志与附件

没必要

**Comment by IF-desu** [comment]
没必要

**Comment by Big-Cake-jpg** [comment]
无法复现，请确认启动器是否为最新版本。测试使用版本：快照版 2.5.0。
![image](https://user-images.githubusercontent.com/76810494/222939431-92258edc-1f4f-44d4-af9d-d154b6d5b931.png)

**Comment by IF-desu** [comment]
![image](https://user-images.githubusercontent.com/86994398/222939508-6e8f15d2-1e30-421c-9c79-cdb0fc94b80a.png)
同上

**Comment by IF-desu** [comment]
可能是系统字体的问题？

**Comment by iPodtouch6557** [comment]
啊，这个不是没处理完吗（）

**Comment by Big-Cake-jpg** [comment]
#1204 中已报告了这一问题，当前显示的状态是已修复。

可能是没修好？

**Comment by Big-Cake-jpg** [comment]
点错了（）

@Fenck 你目前的 PCL2 版本号为？（在 更多 -> 关于 页面查看）

**Comment by iPodtouch6557** [comment]
~啥玩意，删了又加~确实，好像是不是字体的锅

**Comment by WTP016-CN** [comment]
最新快照版 2.5.0 也无法复现
![图片](https://user-images.githubusercontent.com/66893541/222939775-5df1722e-bed4-4fed-bca3-052262baf857.png)

**Comment by WForst-Breeze** [comment]
根据观察反馈者 Mod 列表页面，反馈者使用的并非 2.5.0 版本，因为旧版本 Dynamic FPS 的类型标记为 **“杂项”**，在 2.5.0 版本中，该模组类型标签已经变为 **“改良” “性能优化”**。故此问题与 #1204 重复，且已于 Snapshot 2.5.0 修复完成，请再次检查您的启动器版本，并在下次提交 Issue 时留意检查项。

感谢您的反馈~
