### ISSUE TITLE
fabric报错缺少前置而崩溃时可以直接跳转到mod搜索页并搜索log中提示缺失的前置

### ISSUE THREAD

**Issue by IF-desu** [Hex-Dragon/PCL2#1400]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

如题，报错时可以选择跳转到mod搜索页搜索前置
![image](https://user-images.githubusercontent.com/86994398/222939307-c6c5b500-baf5-43b3-aae0-69c8f035e41c.png)
![image](https://user-images.githubusercontent.com/86994398/222939322-9fe3e3c9-6527-45a2-afff-2400489fd69b.png)

### 原因

毕竟太多人连xxx mod require yyy mod,which is missing这种报错都看不懂xwx

**Comment by LTCatt** [comment]
Fabric 的报错信息格式并不是作为 API 固定出现的，所以这样的功能并不能确保在未来可以稳定运行，暂时不会考虑……
