### ISSUE TITLE
添加一键复制版本功能

### ISSUE THREAD

**Issue by iPodtouch6557** [Hex-Dragon/PCL2#1401]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

在设置里添加一个“复制当前版本”按钮，点击后可以直接复制版本

### 原因

我需要这个功能来复制版本
我会把不同用途的同一版本分开下载，当我想把已有版本的东西直接放到新的版本里面时，这个就有用了（比如今天我想把玩生存的1.19.3分支出来玩MTR，这个就会让我更方便）
~因为我自己打开文件夹复制不知道为啥总是会把版本文件夹搞炸，说是没有json文件，可是明明他在文件夹里好好的，改了名也没用~

**Comment by LTCatt** [comment]
你可以自己在 versions 文件夹里复制并重命名 json 和 jar 文件……

**Comment by iPodtouch6557** [comment]
> 你可以自己在 versions 文件夹里复制并重命名 json 和 jar 文件……

哦哦哦哦哦
jar文件也要重命名啊（**************）
