### ISSUE TITLE
可以选择将PCL2配置文件以本地文件的形式储存

### ISSUE THREAD

**Issue by hejiehao** [Hex-Dragon/PCL2#1403]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

可以选择将PCL2配置文件以本地文件的形式储存而不是注册表储存

### 原因

这项优化让我可以更方便地迁移PCL2
如果没有这项优化，我每次都必须重新登录账户，让操作变得很麻烦

**Comment by LTCatt** [comment]
这是刻意的设计，为了避免玩家在无意中打包游戏文件夹时打包了包含账号信息的配置。
事实上，就算你导出了，也没法在另外一个电脑上导入，这是防止盗取账号信息 =。=

**Comment by xianhongtao** [comment]
芝士特性.exe
