### ISSUE TITLE
无法加载svg格式的资源工程图标

### ISSUE THREAD

**Issue by Chiloven945** [Hex-Dragon/PCL2#1409]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

Modrinth似乎支持上传svg格式的图片，比如说[MidnightControls](https://modrinth.com/mod/midnightcontrols)，但是PCL好像只支持加载位图

### 重现步骤

找到一个用svg格式为图标的资源

### 日志与附件

[02:53:40.885] 加载位图失败（*\AppData\Local\Temp\PCL\CompLogo\12673158267540459614.png3779）：参数无效。
   在 System.Drawing.Bitmap..ctor(Stream stream)
   在 PCL.MyBitmap..ctor(String FilePathOrResourceName)
错误类型：System.ArgumentException
[02:53:40.885] 读取资源工程图标失败（*\AppData\Local\Temp\PCL\CompLogo\12673158267540459614.png）：参数无效。
   在 System.Drawing.Bitmap..ctor(Stream stream)
   在 PCL.MyBitmap..ctor(String FilePathOrResourceName)
   在 PCL.MyCompItem._Closure$__6-1._Lambda$__0()
错误类型：System.ArgumentException
[02:53:40.885] 下载资源工程图标失败（https://cdn.modrinth.com/data/bXX9h73M/icon.svg）：参数无效。
   在 PCL.MyCompItem.LogoLoader(String Address)
错误类型：System.ArgumentException

**Comment by LTCatt** [comment]
不考虑支持，抱歉（

**Comment by Chiloven945** [comment]
机器人抽风了（
