### ISSUE TITLE
将已经设置的系统环境变量添加到自动识别java的路径

### ISSUE THREAD

**Issue by frshuov** [Hex-Dragon/PCL2#1414]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

启动器的自动搜索Java功能中，将系统的%JAVA_HOME%环境变量所指定的目录加入待搜索的目录。
又或者，将系统PATH都搜索一遍。

### 原因

这样做可以避免必须手动添加**已经在系统环境中可用的**Java。

用户可能会将jdk自行*解压安装*到一个随机的目录，例如（一个**常见**的情况）通过scoop安装的openjdk。
一般通过这些方式安装Java的用户会自行配置JAVA_HOME环境变量。可以直接识别这些变量或系统PATH变量。

**Comment by Chiloven945** [comment]
这个不错，等等龙猫

**Comment by LTCatt** [comment]
额，现在会查找啊？
