### ISSUE TITLE
游戏没有添加mod裸1.16.5版本还是崩溃了

### ISSUE THREAD

**Issue by douyuTVDD** [Hex-Dragon/PCL2#1415]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃不是 PCL2 的原因，请 **不要** 提交反馈。你可以在 QQ 群里或者论坛找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是游戏本身的问题，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

游戏没有添加mod裸1.16.5版本还是崩溃了，游戏没有添加mod裸1.16.5版本还是崩溃了，游戏没有添加mod裸1.16.5版本还是崩溃了
[错误报告-2023-2-21_18.09.21.zip](https://github.com/Hex-Dragon/PCL2/files/10899824/-2023-2-21_18.09.21.zip)

### 错误报告、日志与附件

[错误报告-2023-3-6_23.26.37.zip](https://github.com/Hex-Dragon/PCL2/files/10899810/-2023-3-6_23.26.37.zip)
[错误报告-2023-2-21_18.09.21.zip](https://github.com/Hex-Dragon/PCL2/files/10899831/-2023-2-21_18.09.21.zip)

**Comment by Chiloven945** [comment]
Log1~Log5呢……

**Comment by Chiloven945** [comment]
这个好像跟#1407都是LWJGL的问题，等等Collaborator
```
[18:09:17] [main/INFO] [STDERR/]: [org.lwjgl.system.Library:printError:424]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
```

**Comment by LTCatt** [comment]
HMCL 也有这个问题吗？
如果没有，上传一个 HMCL 导出的启动脚本？

**Comment by hejiehao** [comment]
> HMCL 也有这个问题吗？ 如果没有，上传一个 HMCL 导出的启动脚本？

正常hmcl把本地库路径改为预设就可以了，它会自动补全

**Comment by hejiehao** [comment]
我在hmcl的kook群也遇到过一样的实例，当时用hmcl就可以正常启动，但是用pcl2那边的人说不知道怎么操作

**Comment by LTCatt** [comment]
超时未回复，如果之后要补充可以继续回复（
