### ISSUE TITLE
2.4.5版本

### ISSUE THREAD

**Issue by hellominecraftlauncher** [Hex-Dragon/PCL2#1416]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

2.4.5版本中Java自动搜索无法搜索旧版本Java，部分旧电脑显卡需要

### 重现步骤

手动搜索后无Java

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10910132/Log1.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10910143/Log5.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10910135/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10910136/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10910137/Log4.txt)

**Comment by dargoncat** [comment]
如果是2.4.5的话，请更新到最新版重试
~不过我更趋向于是打错版本号了qwq~

**Comment by Chiloven945** [comment]
![image](https://user-images.githubusercontent.com/116699482/223498668-86fe3370-476e-41f4-ab4a-f9f2688e7ab7.png)
？
还有你的旧版本是指哪些，java7都能被搜到（
![image](https://user-images.githubusercontent.com/116699482/223499475-4af8418d-2a2e-4f63-ad2f-deb600393868.png)

**Comment by Chormore-EDGE** [comment]
只能这么说吧，远古机器就别考虑了，我这机器属于办公机器
![image](https://user-images.githubusercontent.com/114737601/223621637-ab7c595b-5619-42d2-b950-e8c80cac9197.png)

**Comment by Chormore-EDGE** [comment]
![image](https://user-images.githubusercontent.com/114737601/223622484-fb4f84e5-122f-47ac-9c60-71133c61ff82.png)
搜到Java7了，
![image](https://user-images.githubusercontent.com/114737601/223622576-d3092ea2-68f8-4b12-b57e-8ced84a926fe.png)
请问搜不到哪个Java版本，<如果远古Java可能搜不到，但是好像没人用>

**Comment by hellominecraftlauncher** [comment]
> ![图像](https://user-images.githubusercontent.com/116699482/223498668-86fe3370-476e-41f4-ab4a-f9f2688e7ab7.png)？ 还有你的旧版本是指哪些，java7都能被搜到（ ![图像](https://user-images.githubusercontent.com/116699482/223499475-4af8418d-2a2e-4f63-ad2f-deb600393868.png)

bellsoft jre8u362

**Comment by hellominecraftlauncher** [comment]
> ![图像](https://user-images.githubusercontent.com/114737601/223622484-fb4f84e5-122f-47ac-9c60-71133c61ff82.png)搜到Java7了， 请问搜不到哪个Java版本，<如果远古Java可能搜不到， ![图像](https://user-images.githubusercontent.com/114737601/223622576-d3092ea2-68f8-4b12-b57e-8ced84a926fe.png) 但是好像没人用>

2.5.1我这还是搜不到

**Comment by LTCatt** [comment]
自动搜索搜不到是正常的，可以手动添加，这和文件夹名有关，没法保证全部搜到……

**Comment by hellominecraftlauncher** [comment]
> 自动搜索搜不到是正常的，可以手动添加，这和文件夹名有关，没法保证全部搜到……

 文件名是javaw.exe，而且只要目录第一次搜索到两个同类型Java，下一次点击搜索也不会搜索到新Java（2.4.5到2.5.0都测了）必须卸载第一次搜索到的Java才能再继续自动搜索别的Java（搞得安装新Java就要直接把PCL注册表重置一下）我这么弄完后能搜索到了
