### ISSUE TITLE
模组下载列表出现多个相同模组

### ISSUE THREAD

**Issue by lizhuolun2010** [Hex-Dragon/PCL2#1417]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

模组下拉列表出现多个相同模组，并且下载量等都相同

### 重现步骤

1、搜索Xaero's MiniMap
2、点击1.19.2
*其他版本也出现了重复，如1.19.3、1.19.1

### 日志与附件

![image](https://user-images.githubusercontent.com/84306316/223892772-3b287a64-47a0-4799-9d39-e9d8488dcdae.png)

**Comment by Chormore-EDGE** [comment]
提供一下日志文件，然后等合作

**Comment by lizhuolun2010** [comment]
[](url)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10929516/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10929519/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10929520/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10929521/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10929522/Log2.txt)
这里是PCL2的5个日志文件
同时其他模组下载页面也出现了重复，如图
![image](https://user-images.githubusercontent.com/84306316/223969463-8416845e-334b-4efb-a242-3135024b750d.png)

**Comment by LTCatt** [comment]
与 #1330 重复
