### ISSUE TITLE
部分情况下填写正确仍然无法开始自定义下载

### ISSUE THREAD

**Issue by Chiloven945** [Hex-Dragon/PCL2#1421]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在部分情况下（例如粘贴链接时）即使自定义下载没有仍和报错还是无法开始下载文件
![image](https://user-images.githubusercontent.com/116699482/224294851-dd3d548c-458e-40a6-ac30-95c7f782faa3.png)
重新加载界面后恢复正常

### 重现步骤

粘贴下载链接

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10941171/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10941173/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10941174/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10941175/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10941176/Log5.txt)

**Comment by iPodtouch6557** [comment]
填写链接？？？
可以具体一点吗，哪个链接会出现……

**Comment by youzi-2333** [comment]
2.4.9 无法复现，可能是 2.5.1 的问题（抱歉我是公测用户……）
先等等别人，看看怎样复现罢（
链接：`https://www.mineimator.com/version/2.0.0/Mine-imator%202.0.0%20installer.exe`

**Comment by Chiloven945** [comment]
> 填写链接？？？ 可以具体一点吗，哪个链接会出现……

。。。你能不能仔细看一下，不是链接

**Comment by Chiloven945** [comment]
所有的都可以复现，不是单个链接的问题

**Comment by youzi-2333** [comment]
额，看来是存在这个问题的，（至少 2.5.X 有问题）PCL2 百宝箱代码又没有公开……

算了先看看龙猫咋处理吧（悲）

**Comment by Chiloven945** [comment]
离谱这gif咋加载不出来（

**Comment by Chiloven945** [comment]
https://user-images.githubusercontent.com/116699482/224314870-d9089851-3e57-41a6-b565-1ebfbfd638ba.mp4

**Comment by LTCatt** [comment]
已确认。
缓解方法：在网址最前面加一个任意字符然后删除即可下载 =。=

**Comment by Chiloven945** [comment]
> 已确认。 缓解方法：在网址最前面加一个任意字符然后删除即可下载 =。=

切换到其他选项卡再切换回来也可以捏（

**Comment by rumengchuxing062** [comment]
懒猫的致命Bug
