### ISSUE TITLE
按F12键可以显示联机入口

### ISSUE THREAD

**Issue by ZmdNotFound** [Hex-Dragon/PCL2#1422]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

快照版 2.5.1 联机入口被隐藏了，但是按 F12 键可以显示（虽然进不去）
不知道是不是龙猫特意设计的以及是不是个例，但还是反馈一下罢（

### 重现步骤

1、打开启动器
2、按下F12（取消功能隐藏）

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10941334/Log1.txt)

**Comment by youzi-2333** [comment]
额，我作为公厕用户……
算了先看看龙猫咋说吧（

**Comment by ZmdNotFound** [comment]
对了，完成后麻烦解锁一下活跃橙，谢谢。
识别码：EF02-3014-3368-A350

**Comment by LTCatt** [comment]
你的解锁码：pVR/udBQMaD0Kwofx27oaqL2NciEuwEk
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
