### ISSUE TITLE
离线登录姓名框输入特殊字符造成启动器闪退

### ISSUE THREAD

**Issue by Chen-Luan** [Hex-Dragon/PCL2#1424]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在离线登录-游戏用户名文本框内输入特殊字符（如下划线）导致启动器闪退

### 重现步骤

1、启动PCL2
2、在姓名框输入特殊字符

### 日志与附件

[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10941781/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10941782/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10941783/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10941785/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10941786/Log3.txt)

**Comment by Chiloven945** [comment]
未能复现捏（

**Comment by youzi-2333** [comment]
好神奇的 Bug……
由于 Log 无法发现相关信息，请上传录屏，感谢配合。

---

2.4.9 无法复现，根据源码，估计是在正则搜索的时候出了问题，或者是在调用 `SendKeys.SendWait` 时的问题……？

**Comment by youzi-2333** [comment]
这么说，在 2.5.1 往里面敲一个 `|` 就可以吗（？）
先加上待处理等龙猫吧，感谢您的反馈~
@LTCatt

**Comment by Chiloven945** [comment]
就离谱，但是我这边输入不会啊

**Comment by LTCatt** [comment]
无法复现。
有没有其他人可以使用 2.5.1 复现的？

**Comment by LTCatt** [comment]
先关了，如果有其他人可以复现再说 =。=

**Comment by LTCatt** [comment]
已修复。

**Comment by Chen-Luan** [comment]
（挖坟致歉）
是这样的，最近心血来潮在全收集主题，除了这个都齐了，强迫症开始难受了（）
识别码：11C9-6491-74CB-C53C

**Comment by LTCatt** [comment]
你的解锁码：ijEMKNYtuJDspR/gHzYHi8EpUsmeDrXx
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
