### ISSUE TITLE
找不到帮助文件 / 打开特定帮助页面报错

### ISSUE THREAD

**Issue by xingnengmao666** [Hex-Dragon/PCL2#1425]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

去帮助界面触发该bug

### 重现步骤

1、去帮助界面触发该bug
![屏幕截图 2023-03-10 202950](https://user-images.githubusercontent.com/88268143/224316890-ebb293a1-ea1a-47d4-bfac-b9329514dd9d.png)

### 日志与附件

给个链接吧，傻逼github传不了文件
https://wwbz.lanzoue.com/iOlxZ0psb81e

**Comment by Chormore-EDGE** [comment]
#1234 重复

**Comment by Chormore-EDGE** [comment]
但是很奇怪为啥2.5.1还会有（怀疑偷懒

**Comment by WorldHim** [comment]
补log
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10942148/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10942149/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10942145/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10942146/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10942147/Log5.txt)

**Comment by iPodtouch6557** [comment]
换个标题吧（）别再来这种的了

**Comment by Chiloven945** [comment]
~~哇塞第一个gamma级别的issues~~
但是咋触发这个bug呢，我试了几次没成功（

**Comment by youzi-2333** [comment]
日志乱码了……~~这件事情告诫我们一定要加 SyncLock~~
此反馈不应与 #1234 重复，因为日志中没有发现用户清理缓存。

不会是我那个 LTCatt/PCL2Help#275 LTCatt/PCL2Help#276 导致的吧（）

**Comment by YUANXINGlingyun** [comment]
做完了 :-)
想问问是啥原因

**Comment by LTCatt** [comment]
发下识别码（

**Comment by xingnengmao666** [comment]
D9FF-1A37-FAFA-6487

**Comment by xingnengmao666** [comment]
对了主题码会过期吗

**Comment by iPodtouch6557** [comment]
为什么做完还是固定的

**Comment by WForst-Breeze** [comment]
> 为什么做完还是固定的

2.5.1 尚未推送，请耐心等待

**Comment by shimoranla** [comment]
![Image](https://github.com/user-attachments/assets/9da2bf5f-3d30-4bc9-abdd-9162bd668507)

![Image](https://github.com/user-attachments/assets/e0f9df18-23f4-4138-91ec-f5ddafbc033a)

使用 Bandizip 打包出现乱码问题

也许把中文目录换成英文会更好？（主要是因为现在使用的压缩工具是 Bandizip）

>[!TIP]
>
>Powershell 自带的 Compress-Archive 没有这个问题

**Comment by xingnengmao666** [comment]
@LTCatt 炸个尸，换电脑了可否补发下我滴激活码，这是识别码82B0-B9A3-4993-0575

**Comment by LTCatt** [comment]
你的解锁码：/trWnmI2scQtW/Z8P6YsolfE/sQNH/On
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by xingnengmao666** [comment]
ok谢谢龙猫
&nbsp;


LFM-MC_Consle
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2025年7月15日(星期二) 下午3:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Meloong-Git/PCL] 找不到帮助文件 / 打开特定帮助页面报错 (Issue #1425)












LTCatt left a comment (Meloong-Git/PCL#1425)
 
你的解锁码：/trWnmI2scQtW/Z8P6YsolfE/sQNH/On
 在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by xingnengmao666** [comment]
@LTCatt 06B1-AC80-580A-89E5 再炸个尸……重装后不知为何识别码变了，感谢感谢

**Comment by LTCatt** [comment]
你的解锁码：ypkaf+vdXJYAwNa7qGUgbNVmzEBnPTC/
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
