### ISSUE TITLE
回车检测错误

### ISSUE THREAD

**Issue by Chiloven945** [Hex-Dragon/PCL2#1428]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

这个比较难阐述，我用情景模拟的方式来（

我想搜索名为“create”的模组，于是我在搜索栏输入了“cre”（在中文模式下），但是我突然忘记后面的内容是什么了，于是我决定先使用回车键确认我输入的内容
![屏幕录制-2023-03-10-204137](https://user-images.githubusercontent.com/116699482/224319395-1605c61a-11d9-4d40-8bab-f6292be37b75.gif)
但是我们这时候却发现，明明我用来确认我输入内容的回车操作被PCL识别成了进行搜索，所以说直接搜索了cre。但是正常情况下不应该检测这次回车操作，因为我们输入这次回车操作的原因是为了确定我们输入的内容而不是来搜索。造成 #1311 的原因是输入了两次回车，但是导致输入两次回车的就是这个bug，那么为什么这个bug会导致输入两次回车？

这次我们假设知道mod叫什么了，于是我输入了“create”，按下回车**用于确认输入内容**，再次按下回车**用于开始搜索**
在 #1311 这个bug还存在的情况下，那么就会直接报错因为我们输入了两次回车，但是我们会发现实际上我们应该只输入了一次回车用于搜索，但是PCL却搜索了两次，这是因为PCL把用于确认输入内容的回车也检测进去了，所以说这就直接导致输入了两次

除了模组/整合包搜索界面，在自定义下载界面会直接开始下载，在离线模式输入ID会直接导致启动游戏等等。但如果在弹出窗口内的输入栏输入则不会触发这个bug，意思说在任何按下回车键有操作（例如搜索，下载，启动）且不是弹窗的界面输入用于确认输入内容的回车键都会被识别

### 重现步骤

1.找到任何一个按下回车键有操作（例如搜索，下载，启动）且不是弹窗的界面
2.在此界面的输入框输入内容（有候选栏的输入模式），并按下回车确认输入内容
3.bug发生（用于确认输入内容的回车被意外检测）

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10942381/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10942375/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10942377/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10942379/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10942380/Log5.txt)

**Comment by iPodtouch6557** [comment]
曲线救国，直接把确认操作的enter取消掉吧

**Comment by Chiloven945** [comment]
> 曲线救国，直接把确认操作的enter取消掉吧

~~那你用个寂寞~~

**Comment by Chiloven945** [comment]
> 曲线救国，直接把确认操作的enter取消掉吧

~~ PCL那么多bug把PCL删了吧一劳永逸（~~

**Comment by Chiloven945** [comment]
D639-B070-FDA8-2A92
awa

**Comment by LTCatt** [comment]
你的解锁码：mU3ZG6b43yTpzBiGg23I+i69bX7OqWsD
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
