### ISSUE TITLE
安装1.19.4快照版本（fabric版）时，PCL2找不到这个版本的fabric api

### ISSUE THREAD

**Issue by King-ming136121** [Hex-Dragon/PCL2#1429]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

fabric api（courseforge页）有适用于1.19.4的快照版本，但PCL2找不到fabric api（以最新快照1.19.4rc2举例）

### 重现步骤

尝试安装1.19.4快照版本（1.19.4pre3及更高快照）

### 日志与附件

![image](https://user-images.githubusercontent.com/110441378/224450937-fd37b262-ce16-4b05-ab5b-bddfb182bfc2.png)

![image](https://user-images.githubusercontent.com/110441378/224451030-3871451a-73bd-44cd-919f-5801f234e14b.png)

**Comment by LTCatt** [comment]
![image](https://user-images.githubusercontent.com/40348278/226196420-5c56a77e-a684-422e-9219-15da842fffeb.png)

目前正使用 Modrinth 的列表，作者未上传 pre3 以及 rc 版本的 API，但有 1.19.4 的……大概不是我的问题 =。=
