### ISSUE TITLE
MOD下载界面索引超限异常：需为非负数

### ISSUE THREAD

**Issue by infidiotWolf** [Hex-Dragon/PCL2#1430]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

当Mod搜索没有结果时，点击下方“没有符合条件的结果”浮标会导致抛出此异常。
异常函数：PCL.PageDownloadMod.Load_OnFinish()
异常：索引超出范围。必须为非负值并小于集合大小。
异常类型：System.ArgumentOutOfRangeException
因为在抛出异常后下载界面会出现翻页按钮，所以我想这可能是因为结果返回-1值，显示列表时直接调用函数导致的。
解决办法：
1.去除”没有符合条件的结果“浮标的点击事件。
2.在找不到结果的情况下，额外增加对结果返回值的判断。
3.跑路（不是

另外如果这个Bug不是被重复提交的，请给一个活跃橙解锁码（因为重装系统导致隐藏主题丢失.jpg

### 重现步骤

因为github发电无法上传图片，所以口述。
在Mod下载界面搜索一个并不存在的Mod名，搜索完成后，点击下方“没有符合条件的结果”浮标，抛出异常。

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10947538/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10947539/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10947540/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10947541/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10947542/Log2.txt)

**Comment by Chormore-EDGE** [comment]
![image](https://user-images.githubusercontent.com/114737601/224466169-4cce2447-8d3c-4367-8ce5-6b3bfb38606b.png)
在原来已经标记完成的issue下再次要求解锁

**Comment by Chormore-EDGE** [comment]
![image](https://user-images.githubusercontent.com/114737601/224466217-0adbae6b-26b5-4916-bd5e-e3f6c6c82bac.png)
复现成功，版本为2.5.1

**Comment by Chormore-EDGE** [comment]
#1311 为啥完成了还是这个bug类型
