### ISSUE TITLE
关于因“指定的路径或文件名太长”而无法完成安装的问题

### ISSUE THREAD

**Issue by CN171-1** [Hex-Dragon/PCL2#1448]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在不进行任何设置的更改的情况下安装整合包“DawnCraft - An Adventure RPG Modpack”且安装地址为官方启动器文件夹地址时，会出现因“指定的路径或文件名太长”而无法完成安装的情况。
将“输入版本名称”的默认内容（DawnCraft - An Adventure RPG Modpack）改为“DawnCraft”后可以正常进行安装

### 重现步骤

1、点击下载页面并找到整合包搜索页面
2、搜索“DawnCraft - An Adventure RPG Modpack”
3、下载该整合包，并且在“输入版本名称”时不进行任何更改（安装路径为官方启动器文件夹）
4、安装并等待
复现成功截图：
![DU~F6_A8 81、点击下载页面并找到整合包搜索页面
2、搜索“DawnCraft - An Adventure RPG Modpack”
3、下载该整合包，并且在“输入版本名称”时不进行任何更改（安装路径为官方启动器文件夹）
4、安装并等待
复现成功截图：
NL NFD)9O4N](https://user-images.githubusercontent.com/110646806/224889739-3297d16c-f034-4f11-b701-b741a76e3b0e.png)

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10964001/Log1.txt)

**Comment by CN171-1** [comment]
建议可以将默认版本名称简化一下，以避免这个问题的出现

**Comment by gtf016** [comment]
即使手动修改默认版本名进行安装,依然报错

**Comment by CN171-1** [comment]
> 即使手动修改默认版本名进行安装,依然报错

我有个前提，是在官方启动器文件夹下进行安装（）

**Comment by CN171-1** [comment]
> > 即使手动修改默认版本名进行安装,依然报错
> 
> 我有个前提，是在官方启动器文件夹下进行安装（）

这样可以控制变量，让大家都可以复现.png

**Comment by LTCatt** [comment]
这不是我能解决的范畴，如果 MC 文件夹名太长也会导致这个问题。
![image](https://user-images.githubusercontent.com/40348278/225028730-b61f1f0b-5144-44b8-abd6-75120023945a.png)
应当向整合包作者反馈，让他尽量别用这么长的文件夹名……

**Comment by CN171-1** [comment]
那是否可以让PCL检测到文件名太长时给予提醒，以防止有人不清楚状况然后乱投反馈（？

**Comment by LTCatt** [comment]
这个真的不好做，各个地方都有这个问题，算了……

**Comment by CN171-1** [comment]
彳亍吧，龙猫辛苦了
