### ISSUE TITLE
对不对外开源的功能做一个简陋的替代品，以便于通过编译，用于配置actions自动编译。

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [Hex-Dragon/PCL2#1451]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

所有简单的闭源功能替代，不需要好看，能过编译，并且与被替代的功能在代码上行为相同。

### 原因

如题，配置actions后可有效降低工作量，也可防止无法通过编译的pr被蒙混过关，所以建议编写一个简陋的闭源功能替代品，用于自动化检查和调试等。

**Comment by LTCatt** [comment]
这个工作量实际上也不小，目前没有什么 PR 检查的需求，暂时还没必要 :(

**Comment by allMagicNB** [comment]
@LTCatt 现在已经有人替你做了 Actions 自动编译，你会同意开 Actions 板块吗（
