### ISSUE TITLE
任务栏图标透明

### ISSUE THREAD

**Issue by got991** [Hex-Dragon/PCL2#1456]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

任务栏图标透明

（使用了TranslucentTB）

### 重现步骤

1、打开启动器
2、观察图标

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10989101/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10989102/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10989103/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10989104/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10989105/Log1.txt)

**Comment by iPodtouch6557** [comment]
发个截图，我无法准确判断（）

**Comment by WForst-Breeze** [comment]
请在三周内补充相关截图，感谢您的反馈～

**Comment by Chiloven945** [comment]
离谱你说透明不给截图什么意思，~~我是不是得用脑电波和你的电脑沟通~~

**Comment by got991** [comment]
在部分情况下会重现（重启就解决了
