### ISSUE TITLE
强制重启电脑导致PCL重置

### ISSUE THREAD

**Issue by GBC034** [Hex-Dragon/PCL2#1460]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

电脑被强制重启之后PCL所有东西都被重置了（包括解锁码和主题）

### 重现步骤

1.打开PCL 2
2.强制重启电脑

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10998768/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10998770/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10998771/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10998773/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10998774/Log5.txt)

**Comment by GBC034** [comment]
然后识别码也被改了

**Comment by Chormore-EDGE** [comment]
![image](https://user-images.githubusercontent.com/114737601/225890910-3032d6fc-8775-47a2-b075-f7542e754a2f.png)
识别码在提交的log1-5没有被改变

**Comment by Chormore-EDGE** [comment]
![image](https://user-images.githubusercontent.com/114737601/225891259-f7bbdb75-e467-459e-9015-de8265864ae9.png)
嗯，看不懂

**Comment by youzi-2333** [comment]
Log5 中的 `System.Security.Cryptography` 意为：
当加密操作中出现错误时引发的异常。

并且在 Log5 中看到以下内容：
```
[15:09:55.355] [Start] 版本号从 0 升高到 284
```
版本号从 0 向上升，即表示在**这台电脑 / 这个操作系统**上首次运行 PCL2，因此，即使将注册表备份到这个系统中，识别码仍会更改。识别码更改后，则无法进行解密，则自然没法加载了……

所以我不太确定是不是强制重启导致的，多半是重装系统或换了一台电脑……
先关了，如果确实没有重装系统或更换电脑，可以联系重开。

**Comment by GBC034** [comment]
更新系统有没有可能导致此问题

**Comment by youzi-2333** [comment]
如果是 Windows 功能更新（例如 Win 10 升 Win 11 或 Win 11 21H2 升 Win 11 22H2），那么识别码可能会改变；只是小更新的话不会改变。重装系统后，识别码一定会改变。

#787 同样提到了这个问题……可以参考一下……

**Comment by WForst-Breeze** [comment]
如果您曾经解锁了主题秋怡金或活跃橙，可以在此处或通过爱发电私信龙猫并 **提供相关截图** 以重新获取解锁码~感谢支持~

**Comment by GBC034** [comment]
那应该不是电脑更新的问题，应该是电脑被突然断电的问题

**Comment by GBC034** [comment]
![image](https://user-images.githubusercontent.com/71167084/226086293-bcae56df-0d56-4515-b32a-b7dff91ed05f.png)
![image](https://user-images.githubusercontent.com/71167084/226086328-1e697798-6346-4355-a39e-1ea194f05607.png)

**Comment by GBC034** [comment]
电脑一直都是22H2，突然被断电之后启动发现被重置了（无奈）

**Comment by WForst-Breeze** [comment]
@LTCatt 打扰了，这里有个朋友想重新获取一下秋怡金和活跃橙解锁码，谢谢qwq

**Comment by LTCatt** [comment]
发识别码……

**Comment by GBC034** [comment]
8772-C005-8957-AD6E

**Comment by GBC034** [comment]
就是说，麻烦各位帮忙复现一下（注意备份!）

**Comment by LTCatt** [comment]
你的解锁码：yVc8QM/xYLRxoBZNqDrUiQbImM+F1WZK
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
