### ISSUE TITLE
Issue: Omniworld整合包安装失败

### ISSUE THREAD

**Issue by cloudw233** [Hex-Dragon/PCL2#1461]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

安装ominiworld整合包报错
详细信息如下
```shell
整合包安装失败
→ 解压整合包文件失败
→ 复制文件出错：C:\Users\QRZ20\AppData\Local\Temp\PCL\PackInstall\68675\overrides\resourcepacks\TinkersConstructGeneratedPartTextures\assets\materialis\textures\item\tool\psimetal_exosuit\boot_modifiers\tconstruct_embellishment_broken_kubejs_primomium.png -> C:\Users\QRZ20\Documents\Tencent Files\2031611695\FileRecv\Snapshot 2.2.10\.minecraft\versions\Omniworld\resourcepacks\TinkersConstructGeneratedPartTextures\assets\materialis\textures\item\tool\psimetal_exosuit\boot_modifiers\tconstruct_embellishment_broken_kubejs_primomium.png
→ 指定的路径或文件名太长，或者两者都太长。完全限定文件名必须少于 260 个字符，并且目录名必须少于 248 个字符。
   在 PCL.ModBase.CopyFile(String FromPath, String ToPath)
   在 PCL.ModBase.CopyDirectory(String FromPath, String ToPath)
   在 PCL.ModModpack._Closure$__6-0._Lambda$__0(LoaderTask`2 Task)
   在 PCL.ModLoader.LoaderTask`2._Closure$__12-0._Lambda$__0()
   在 PCL.ModBase.CopyFile(String FromPath, String ToPath)
错误类型：System.IO.PathTooLongException
```
![图片](https://user-images.githubusercontent.com/86039582/225939267-e3ddcd06-797d-485d-b02f-6a06756f8b2a.png)

### 重现步骤

- 安装[Ominiworld整合包](https://github.com/N-Wither/Omniworld/)

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11002565/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11002566/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11002567/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11002569/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11002570/Log2.txt)

**Comment by dargoncat** [comment]
与 #1448 实质重复
