### ISSUE TITLE
用名称给Java排序

### ISSUE THREAD

**Issue by gaojin20090517** [Hex-Dragon/PCL2#1471]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

用名称给Java排序
Java的顺序太乱了！
按数字顺序排序好吗？

### 原因

这项优化让我可以更方便地查找所需的java
有时需要自己选Java，长长的列表，要翻好几遍才能找到！！
操作十分甚至九分的麻烦

https://user-images.githubusercontent.com/125573915/226174758-b1f4e9c1-7fdb-4877-9684-108cf2411550.mp4

**Comment by Chormore-EDGE** [comment]
<正常人会装那么多Java jdk吗>
这建议如果不是装太多Java没啥必要qwq

**Comment by mcwuguodadi** [comment]
> <正常人会装那么多Java jdk吗>
> 
> 这建议如果不是装太多Java没啥必要qwq

_我是会装这么多的_单纯收集癖好罢了，有时候还会换用不同jvm的Java（比如说阿里巴巴 jvm的Java内存效率高，OpenJ9 jvm的Java能省很多内存（但是牺牲了加载速度），所以我赞成这个议题

**Comment by Chiloven945** [comment]
不是什么特殊情况的话8和17就够用了吧（
