### ISSUE TITLE
解密设置失败：UiLauncherThemeHide：调用的目标发生了异常

### ISSUE THREAD

**Issue by GBC034** [Hex-Dragon/PCL2#1474]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

尝试解锁神秘紫的时候发现神秘紫没解锁，倒是报了个错...

### 重现步骤

1、尝试解锁神秘紫
2、重启PCL

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11012901/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11012902/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11012904/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11012905/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11012906/Log5.txt)

**Comment by Chiloven945** [comment]
```
[09:17:01.833] 解密设置失败：UiLauncherThemeHide：调用的目标发生了异常。
→ 不正确的数据。

   在 3DC404F2.388B43F7(Exception 772866A5)
   在 3DC404F2.23E40669(Object[] 0B525BCD, Int32 270966B9)
   在 PCL.ModSecret.SecretDecrypt(String SourceString, String Key)
   在 PCL.ModSetup.Read(String Key, SetupEntry& E, McVersion Version)
   在 System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)
   在 System.Security.Cryptography.Utils._DecryptData(SafeKeyHandle hKey, Byte[] data, Int32 ib, Int32 cb, Byte[]& outputBuffer, Int32 outputOffset, PaddingMode PaddingMode, Boolean fDone)
   在 System.Security.Cryptography.CryptoAPITransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   在 System.Security.Cryptography.CryptoStream.FlushFinalBlock()
   在 System.Security.Cryptography.CryptoStream.Dispose(Boolean disposing)
   在 System.IO.Stream.Close()
错误类型：System.Security.Cryptography.CryptographicException
```
