### ISSUE TITLE
分类改动

### ISSUE THREAD

**Issue by fAaAtDoOoG** [Hex-Dragon/PCL2#1482]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

可以把复制识别码和输入解锁码放到设置->启动器->系统，和检查更新放在一起吗？放到关于和鸣谢容易让恶人误解

### 原因

我给我的hxd们推销PCL2，但是一堆人经常就找不到识别码：（（（（（（

**Comment by Chiloven945** [comment]
鸣谢你赞助了PCL啊（
不过操作逻辑上的确有点冲突……
