### ISSUE TITLE
啥BUG×2

### ISSUE THREAD

**Issue by rongjianuo** [Hex-Dragon/PCL2#1486]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://user-images.githubusercontent.com/119654171/227146270-4ed5d40a-7ea2-48e3-a9c9-12f4c1cb0065.png)
![image](https://user-images.githubusercontent.com/119654171/227146347-66cc9c7c-397a-4708-987f-b6ad8c5327ae.png)

### 重现步骤

1、点击帮助
2、往下滚，然后点击资源安装指南

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11048571/Log1.txt)

**Comment by LTCatt** [comment]
与 #1425 重复
