### ISSUE TITLE
允许自定义背景颜色，并支持背景颜色渐变

### ISSUE THREAD

**Issue by WForst-Breeze** [Hex-Dragon/PCL2#1487]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

如题，支持自定义背景颜色，并支持背景颜色渐变（可以仅在使用“自定义”主题时允许进行此自定义设置，毕竟个人感觉其他主题颜色和背景颜色搭配都还蛮不错的呢）

### 原因

目前 PCL2 虽然已支持自定义背景图片和是否启用彩色背景，但往往有时在使用 “自定义” 主题时背景颜色可能并不能很好地和启动器部分元素相搭配。

此时我通常会选择自己制作一个图片来解决这一问题（如下图），但是这会大大增加使用者的操作难度和繁琐程度，综上所述，希望可以添加类似于 “自定义” 主题的**自定义背景颜色**的个性化选项来解决这一问题（而且或许还可以考虑考虑顺手支持同样类似于 “ 自定义” 主题的背景颜色渐变！超酷哒~！）
![image](https://user-images.githubusercontent.com/110760354/227241246-9e29edf6-c9c5-4f37-8e4e-b469db09b7f7.png)

**Comment by LTCatt** [comment]
比较冗余了，算了 orz

**Comment by iPodtouch6557** [comment]
> 比较冗余了，算了 orz

就是说……随标题栏变化也不行吗
