### ISSUE TITLE
验证文件大小出现问题

### ISSUE THREAD

**Issue by xingnengmao666** [Hex-Dragon/PCL2#1488]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在下载Sodium Plus整合包时显示大小和对错误，并且显示核对错误，log骗不了人

![image](https://user-images.githubusercontent.com/88268143/227247294-48cc99e5-2cf1-4a4b-ac76-d3b8e774e09b.png)

### 重现步骤

1、点击下载->整合包->搜索Sodium Plus
2:下载即可触发

### 日志与附件

github祝你身体健康，又传不了文件

https://wwbz.lanzoue.com/ienYc0qx0hda

**Comment by Chiloven945** [comment]
![image](https://user-images.githubusercontent.com/116699482/227274773-5fc29e45-1386-4ccb-9db5-caa151f2be2c.png)
成功复现，请等待collaborator
另外我用其他启动器试了可以正常安装

**Comment by so1ve** [comment]
> 可以传文件啊…… 这里不写着的吗（ ![image](https://user-images.githubusercontent.com/116699482/227277206-d7c3f288-79e4-49c1-8551-b220d357b94f.png)

他说的或许是文件由于众所周知的原因难以传到GH上面罢（）

**Comment by xingnengmao666** [comment]
![image](https://user-images.githubusercontent.com/88268143/227459402-9aa23db5-5cee-467e-b582-4dbac8f6040d.png)
这个也是我发现的bug（喜

**Comment by LTCatt** [comment]
![image](https://user-images.githubusercontent.com/40348278/230608690-2b10eaab-b0a0-4fc0-b263-809cbb54cd1d.png)

该整合包文件存在问题，它确实要求文件大小为 128677，但文件实际大小为 128670，导致无法通过校验。
请向整合包作者反馈该问题。
