### ISSUE TITLE
在crashreport被占用时弹出提示以防不被打包

### ISSUE THREAD

**Issue by Chiloven945** [Hex-Dragon/PCL2#1490]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

如题
![image](https://user-images.githubusercontent.com/116699482/227500797-7d148be8-4333-48a8-a14f-ed9c536d61e5.png)
可以在文件被占用时提醒用户关闭占用的软件

### 原因

崩溃了会弹出弹窗，其中打开日志会打开crashreport，这时候一般会用记事本打开，如果不关闭记事本或者其他在浏览crashreport的程序PCL就无法把crashreport打包进去

**Comment by iPodtouch6557** [comment]
本来就有的（）

**Comment by Chiloven945** [comment]
这就很离谱了有些有有些没有（

**Comment by YUANXINGlingyun** [comment]
那这应当是 Bug ?

**Comment by iPodtouch6557** [comment]
> 这就很离谱了有些有有些没有（

麻烦你把没有的和有的（最好是一个文件夹并且差不多时间的）都提交1~2个样本给我看看

**Comment by iPodtouch6557** [comment]
> 我好像知道了，由于崩溃了会弹出弹窗，其中打开日志会打开错误报告，这时候一般会用记事本打开，直接导致占用文件PCL就无法把错误报告打包进去，所以说这就直接导致了错误报告无法被打包

我没明白（）举个例子？

**Comment by Chiloven945** [comment]
~~我讲得够明白了你还要我干什么~~
当崩溃时会出现崩溃弹窗，其中有三个按钮，如果用户选择了打开日志那么会用所选的默认软件打开crashreport（例如记事本），随后会再次出现此弹窗，在此之后很可能用户并不会关闭软件而是将软件挂着，回到Pcl很有可能再次点击导出错误报告，由于先前打开crashreport的软件占用了crashreport所以说PCL就无法将crashreport进行打包，就导致了错误报告没有crashreport

**Comment by iPodtouch6557** [comment]
> 当崩溃时会出现崩溃弹窗，其中有三个按钮，如果用户选择了打开日志那么会用所选的默认软件打开crashreport（例如记事本），随后会再次出现此弹窗，在此之后很可能用户并不会关闭软件而是将软件挂着，回到Pcl很有可能再次点击导出错误报告，由于先前打开crashreport的软件占用了crashreport所以说PCL就无法将crashreport进行打包，就导致了错误报告没有crashreport

懂得了，可不可以拿掉那个打开按钮？或者按你的也可以

**Comment by Chiloven945** [comment]
有可能有些人会有需求打开吧（

**Comment by iPodtouch6557** [comment]
> 



> 有可能有些人会有需求打开吧（

等等等？我先复现一下子

**Comment by iPodtouch6557** [comment]
> 那不是原本只需要按一下按钮的事情变成了 点击导出错误报告->另存为->打开文件夹->打开压缩包->打开文件

对不起等一下，我电脑刚刚发现一个木马（）好多程序被关掉了

**Comment by YUANXINGlingyun** [comment]
~~不修自好了？~~
猫猫你看看 @LTCatt

**Comment by Chiloven945** [comment]
> ~不修自好了？~ 猫猫你看看 @LTCatt

我说的是占用情况下（

**Comment by iPodtouch6557** [comment]
> > ~不修自好了？~ 猫猫你看看 @LTCatt
> 
> 我说的是占用情况下（

你是看不到那个edit按钮吗（）连发信息会炸邮箱的

**Comment by Chiloven945** [comment]
@iPodtouch6557 我在进行反馈你告诉我会炸邮箱？如果你不希望提醒的话你可以unsubscribe而不是叫我edit，而且我已经edit过title和这个issue了，上面写着的是占用情况下，你有许多方法防止你不被炸邮箱你来叫我不继续反馈？

**Comment by iPodtouch6557** [comment]
> @iPodtouch6557 我在进行反馈你告诉我会炸邮箱？如果你不希望提醒的话你可以unsubscribe而不是叫我edit，而且我已经edit过title和这个issue了，上面写着的是占用情况下，你有许多方法防止你不被炸邮箱你来叫我不继续反馈？

请你平静一点（）我想了想之后删了，你这不是……这是啥我不讲了

**Comment by Chiloven945** [comment]
> > @iPodtouch6557 我在进行反馈你告诉我会炸邮箱？如果你不希望提醒的话你可以unsubscribe而不是叫我edit，而且我已经edit过title和这个issue了，上面写着的是占用情况下，你有许多方法防止你不被炸邮箱你来叫我不继续反馈？
> 
> 请你平静一点（）我想了想之后删了，你这样子换别的的平台我真的直接骂了

你直接骂了？你叫我平静一点？意思说我在这里反馈问题，你自己不unsubscribe怪我发评论炸你邮箱？我只是在回复别人的问题你倒还不满意了，那么我相信之后谁都不愿意反馈了。如果你觉得你删了就没有任何问题的话，那么是不是我在监控下打你一巴掌然后我把监控视频删了那么是不是就没什么事情了？

**Comment by iPodtouch6557** [comment]
> > > @iPodtouch6557 我在进行反馈你告诉我会炸邮箱？如果你不希望提醒的话你可以unsubscribe而不是叫我edit，而且我已经edit过title和这个issue了，上面写着的是占用情况下，你有许多方法防止你不被炸邮箱你来叫我不继续反馈？
> > 
> > 
> > 请你平静一点（）我想了想之后删了，你这样子换别的的平台我真的直接骂了
> 
> 你直接骂了？你叫我平静一点？意思说我在这里反馈问题，你自己不unsubscribe怪我发评论炸你邮箱？我只是在回复别人的问题你倒还不满意了，那么我相信之后谁都不愿意反馈了。如果你觉得你删了就没有任何问题的话，那么是不是我在监控下打你一巴掌然后我把监控视频删了那么是不是就没什么事情了？

不吵了，不想看了，都删了吧

**Comment by iPodtouch6557** [comment]
> > ~不修自好了？~ 猫猫你看看 @LTCatt
> 
> 我说的是占用情况下（

对不起，我把两个人看成一个人了，对不起（）

**Comment by Chiloven945** [comment]
> > > ~不修自好了？~ 猫猫你看看 @LTCatt
> > 
> > 
> > 我说的是占用情况下（
> 
> 对不起，我把两个人看成一个人了，对不起（）

三思而后行吧……

**Comment by YUANXINGlingyun** [comment]
> 

就是在占用下测的

**Comment by LTCatt** [comment]
我记得这个应该已经修过了，没法复现的话先关了 =。=
