### ISSUE TITLE
更方便地切换版本

### ISSUE THREAD

**Issue by sleep80** [Hex-Dragon/PCL2#1492]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

将鼠标放在“启动游戏”按钮上时，向前或向后拖动鼠标滚轮可以快捷的切换版本。同时，应该有动画表示切换成功。

### 原因

直接在启动页面就能切换版本，不需要打开版本列表，多方便啊！

**Comment by Chiloven945** [comment]
听起来不错，但是可能容易误操作，特别是主页旁边的选项卡可以滑动时（

**Comment by iPodtouch6557** [comment]
> 听起来不错，但是可能容易误操作，特别是主页旁边的选项卡可以滑动时（ 一样的还是加个开关吧

像HMCL?

**Comment by quannen** [comment]
难道现在还不够方便吗？感觉没必要吧。如果真要加感觉咋的都别扭

**Comment by YUANXINGlingyun** [comment]
我的建议是等 #1368 出了后再看

**Comment by sleep80** [comment]
> 难道现在还不够方便吗？感觉没必要吧。如果真要加感觉咋的都别扭
其实现在挺不方便的，因为有的时候版本会被自动分类成不常用版本还得自己打开一个个找

**Comment by sleep80** [comment]
> > 难道现在还不够方便吗？感觉没必要吧。如果真要加感觉咋的都别扭

其实现在挺不方便的，因为有的时候版本会被自动分类成不常用版本还得自己打开一个个找

**Comment by LTCatt** [comment]
暂时不考虑，抱歉 orz
