### ISSUE TITLE
PCL II不等于PLC II

### ISSUE THREAD

**Issue by A-Minecraft-Server** [Hex-Dragon/PCL2#1493]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

主页的"PCL II"变成了"PLC II"

### 重现步骤

主页，有概率,就像"Minceraft"一样

### 日志与附件

![image](https://user-images.githubusercontent.com/122535460/227666977-9e34f8f3-532d-472f-a462-afe5bb5a0385.png)

**Comment by A-Minecraft-Server** [comment]
![image](https://user-images.githubusercontent.com/122535460/227667266-01de513f-4da6-45a2-8db8-0685dde9bf72.png)

**Comment by Chormore-EDGE** [comment]
请查看标题栏选项是否为默认

**Comment by A-Minecraft-Server** [comment]
![image](https://user-images.githubusercontent.com/122535460/227677720-87dbe5ba-da70-4146-962e-d944ff2932da.png)
是

**Comment by iPodtouch6557** [comment]
> ![image](https://user-images.githubusercontent.com/122535460/227677720-87dbe5ba-da70-4146-962e-d944ff2932da.png) 是

如果你是在看到默认按钮并且发现他是plc的情况下发现的，那么得问龙猫了

**Comment by Chormore-EDGE** [comment]
嗯《

**Comment by WForst-Breeze** [comment]
这是刻意的设计

**Comment by iPodtouch6557** [comment]
> 这是刻意的设计

~什么玩意~那么可不可以说明一下，99.999%的人都不知道

**Comment by Chiloven945** [comment]
> > 这是刻意的设计
> 
> ~什么玩意~那么可不可以说明一下，99.999%的人都不知道

那百分之99的人还不知道标题会变成minceraft你是不是也得说一下，那还叫什么彩蛋
