### ISSUE TITLE
错误类型：System.Collections.Generic.KeyNotFoundException

### ISSUE THREAD

**Issue by YUANXINGlingyun** [Hex-Dragon/PCL2#1497]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://user-images.githubusercontent.com/109946426/227703410-b20ef0db-8af0-47c1-89e3-e2bea410e212.png)
如图

### 重现步骤

加载附件中的 Custom.xaml

### 日志与附件

日志：
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11068292/Log1.txt)
主页文件：
（由于 Github 的憨憨限制问题，只能传 `txt` 格式的）
[Custom.txt](https://github.com/Hex-Dragon/PCL2/files/11068293/Custom.txt)

**Comment by YUANXINGlingyun** [comment]
我在研究如何做到让启动器主页菜单左侧有选择栏，然后就去仓库里找文件来学习，然后改了改文件就。。。

**Comment by LTCatt** [comment]
自定义主页导致的问题，不作为 Bug 处理
