### ISSUE TITLE
检查 Minecraft 窗口失败：拒绝访问。

### ISSUE THREAD

**Issue by heihee** [Hex-Dragon/PCL2#1501]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11069271/Log1.txt)
不影响正常游戏
[23:21:43.147] 检查 Minecraft 窗口失败：拒绝访问。
   在 System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   在 System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   在 System.Diagnostics.Process.GetProcessTimes()
   在 System.Diagnostics.Process.get_StartTime()
   在 PCL.ModWatcher.Watcher._Closure$__24-0._Lambda$__0(IntPtr hwnd, Int32 lParam)
   在 PCL.ModWatcher.Watcher.EnumWindows(EnumWindowsSub hWnd, Int32 lParam)
   在 PCL.ModWatcher.Watcher.TryGetMinecraftWindow()
   在 PCL.ModWatcher.Watcher.TimerWindow()
错误类型：System.ComponentModel.Win32Exception
[23:21:43.238] [Control] 普通弹窗：出现错误
检查 Minecraft 窗口失败：拒绝访问。
   在 PCL.ModWatcher.Watcher._Closure$__24-0._Lambda$__0(IntPtr hwnd, Int32 lParam)
   在 PCL.ModWatcher.Watcher.EnumWindows(EnumWindowsSub hWnd, Int32 lParam)
   在 PCL.ModWatcher.Watcher.TryGetMinecraftWindow()
   在 PCL.ModWatcher.Watcher.TimerWindow()
错误类型：System.ComponentModel.Win32Exception

### 重现步骤

不知

### 日志与附件

[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11069272/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11069273/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11069274/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11069275/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11069276/Log3.txt)

**Comment by youzi-2333** [comment]
您可以看 #1062 ，多半是杀软或反作弊 Mod 导致 PCL2 无法访问 Minecraft 窗口。如果安装了反作弊 Mod 的话可以上传一下 Mod 文件，感谢配合

**Comment by LTCatt** [comment]
原因确实是楼上说的那样。
之后加个弹窗提示一下吧 =。=

**Comment by 150149** [comment]
> 原因确实是楼上说的那样。 之后加个弹窗提示一下吧 =。=



> 原因确实是楼上说的那样。 之后加个弹窗提示一下吧 =。=

我可以提供反作弊文件，能否使用QQ发送，文件较大，我的QQ是1802796278

**Comment by LTCatt** [comment]
已 Reopen #1062 ，此 issue 与 #1062 重复
