### ISSUE TITLE
mod 更新时间错误

### ISSUE THREAD

**Issue by g-mph** [Hex-Dragon/PCL2#1502]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

模组 DynamicFPS 的更新时间不符合。
![image](https://user-images.githubusercontent.com/64201424/227750295-b8b9938f-6dcc-4a6b-b327-09d8fa4bb696.png)

### 重现步骤

1、点击下载
2、点击 Mod
3、搜索 DynamicFPS
4、查看时间

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11070546/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11070547/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11070548/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11070549/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11070550/Log5.txt)

**Comment by Chormore-EDGE** [comment]
![image](https://user-images.githubusercontent.com/114737601/227750465-e266a0a5-9923-4b4d-88b4-ed6b3deacff9.png)
![image](https://user-images.githubusercontent.com/114737601/227750468-5296252c-7653-4829-9c7a-851fbf2d2917.png)
嗯哼

**Comment by Chiloven945** [comment]
有没有种可能这是文件的更新时间而不是版本

**Comment by youzi-2333** [comment]
有没有种可能，这是文件的更新时间而不是版本，这可以说明 1.19.4 之前的版本可以在 1.19.4 上运行（~~不然它怎么可能那么快就更新 1.19.4~~）

先关了，如果确实有问题可以再找我……
