### ISSUE TITLE
.NET Framwork版本更新

### ISSUE THREAD

**Issue by xiaochenhao576** [Hex-Dragon/PCL2#1503]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

此应用仅支持.NET Framwork 4.6,应改成4.8

### 原因

.NET Framwork有比4.6更高的版本，导致频繁弹出4.6下载窗口，且无法使用

**Comment by xiaochenhao576** [comment]
也就是我装了4.8然后导致PCL用不了

**Comment by bwtx2023** [comment]
这是不可能的...

**Comment by quannen** [comment]
不可能啊，就像能在win7上运行的软件在win10上运行不了？！有日志吗？
（这不属于优化吧

**Comment by dargoncat** [comment]
> 不可能啊，就像能在win7上运行的软件在win10上运行不了？！有日志吗？ （这不属于优化吧

~无法运行应该是没有日志的.jpg~在win10上无法复现，已安装.NET Framework4.8或更高版本仍能打开PCL
![屏幕截图(9)](https://user-images.githubusercontent.com/121101691/227760458-f3f4bf78-7cf6-406b-a273-869b3b1b52a7.png)

**Comment by LTCatt** [comment]
系统环境问题无法修复。

**Comment by xiaochenhao576** [comment]
但是确实，我win10,双击PCL弹出.NET Offline Installer网页，进入安装程序却提示安装了更高版本



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年03月26日 12:05 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Hex-Dragon/PCL2] .NET Framwork版本更新 (Issue #1503) |

这是不可能的...

**Comment by LTCatt** [comment]
这个提示不是我可以修改的，这是微软强行添加的。我知道提示有误，但我没法修改它……
