### ISSUE TITLE
源码版本写错了？

### ISSUE THREAD

**Issue by gaojin20090517** [Hex-Dragon/PCL2#1505]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

更多→关于与鸣谢→Plain Craft Launcher 2
下方当前版本写的是2.4.9（281.50）
但是点击“查看源代码”，出来的已经是2.5.2了

2.4.9还是指的启动器版本？
那源码……

### 原因

应该是忘记改了

![屏幕截图 2023-03-26 135111](https://user-images.githubusercontent.com/125573915/227757971-3cb1922e-8562-46b4-910c-6717d9e9f5f5.png)
![屏幕截图 2023-03-26 135117](https://user-images.githubusercontent.com/125573915/227757974-a6ae5915-b3ac-4b1b-a471-8e201f2c50e0.png)

**Comment by WForst-Breeze** [comment]
您使用的是 Release 正式版，Github 中储存的为 Snapshot 快照版的源码，所以会有不同
