### ISSUE TITLE
下载模块出现重复项

### ISSUE THREAD

**Issue by MuchenFAB** [Hex-Dragon/PCL2#1513]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

起因:1.12.2没皮肤补丁 在最新版mod下载发现下载项重复但是源不同(一个为CF 一个为Mordinth)

### 重现步骤

1、点击mod下载
2、搜索Skin 第一二项为重复

### 日志与附件

![image](https://user-images.githubusercontent.com/104298593/227776063-33be7ca2-0de7-4045-b0cc-17996ee9d30f.png)

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11071578/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11071579/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11071581/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11071582/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11071583/Log5.txt)

**Comment by WForst-Breeze** [comment]
稳定复现，感谢您的反馈
![image](https://user-images.githubusercontent.com/110760354/227778331-0f8cd77f-7ff9-47aa-8e18-4a1cdb675efe.png)

**Comment by blibilijojo** [comment]
模组下载源并不一样，所支持的版本也有部分不一样。这个感觉问题不大，就是这个排序感觉有点问题，为啥两个相同名称的mod不紧挨着...或许可以提议一个相同模组在一起折叠的功能

**Comment by Chiloven945** [comment]
#1318 明确说明了这样做的原因，你可以明显看见下载源是不一样的

**Comment by LTCatt** [comment]
不是 bug……算了，之后再优化一下显示吧（叹气

**Comment by LTCatt** [comment]
存在技术问题，这个没啥办法隐藏其中一个……之后加个下载源筛选得了……
