### ISSUE TITLE
相同模组自动整合一起

### ISSUE THREAD

**Issue by blibilijojo** [Hex-Dragon/PCL2#1514]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

就是在有时候搜索的时候会出现以下结果
![A)LS_ D{HC60)04H}2B0W0F](https://user-images.githubusercontent.com/102420734/227781090-86af5c7b-9f38-4953-9a52-d192dc65c4ac.png)
![image](https://user-images.githubusercontent.com/102420734/227781189-2defc639-abf6-4c13-ad52-1bdc21ce7a31.png)
如图，3d皮肤层和3d立体机动装置会出现两个，而旅行者背包则出现了三个。
建议直接将名称相同的模组（应该不会出现撞名字这种事情吧），进行整合，将其整理为一个类似收藏夹的东西，样子肯定和模组不一样，不会显示日期标签之类的。默认为整体状态。接下来是我的两种设想：
1.点击将会向下展开出同名模组
2.点击将会进入一个下级目录，显示出同名的几个模组（万一只有两个就太空了感觉）
如果以上难以实现可以优化一下对于界面下模组的排序，将同名的的模组排在一起

### 原因

这项优化可以让我的搜索更加轻松舒适

**Comment by blibilijojo** [comment]
em，这算是新功能还是优化呢...

**Comment by Chiloven945** [comment]
#1318 明确说明了这样做的原因，不过添加下级目录也是挺不错的，就看龙猫愿不愿意了毕竟刚刚霍霍完这里的UI=。=

**Comment by LTCatt** [comment]
与 #1513 重复
