### ISSUE TITLE
禁用启用模组支持批量选择

### ISSUE THREAD

**Issue by blibilijojo** [Hex-Dragon/PCL2#1516]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

就像是Windows系统一样，shift可以批量选中文件，在这里可以批量启用和禁用就好了

### 原因

方便禁用启用模组

**Comment by Chiloven945** [comment]
PCL目前的mod管理操作界面类似于表单的那种感觉而不是文件资源管理器，如果要执行选择操作的话在UI上会冲突不太符合应用逻辑
相反我倒是觉得在前面加勾选之后执行操作倒是挺好，等待龙猫吧（

**Comment by blibilijojo** [comment]
> PCL目前的mod管理操作界面类似于表单的那种感觉而不是文件资源管理器，如果要执行选择操作的话在UI上会冲突不太符合应用逻辑 相反我倒是觉得在前面加勾选之后执行操作倒是挺好，等待龙猫吧（

建议两个都要

**Comment by iPodtouch6557** [comment]
好耶😆
