### ISSUE TITLE
可选提案）VR版本的Minecraft在安装完毕后自动补充文件

### ISSUE THREAD

**Issue by juzhige2018** [Hex-Dragon/PCL2#1517]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

VR版本下载并且安装核心后是没有原版文件支持的，这个是需要进行下载原版文件的，但是PCL暂时不支持该项目，我希望在识别到VR文件丢失的时候询问用户是否需要补充游戏文件，也可以顺便把这个功能推广到其他模式启动的游戏中，启动时检测文件完整并请求下载

### 原因

这个文件有时候会莫名其妙的丢失，PCL也无法进行文件补充下载，我只能打开官方启动器进行下载，非常麻烦

**Comment by LTCatt** [comment]
什么 VR 版本……
顺便传个 Log……

**Comment by juzhige2018** [comment]
游戏版本为1.18.2


零逸轩科技
***@***.***

零逸轩科技团队


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Hex-Dragon/PCL2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月26日(星期天) 晚上11:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Hex-Dragon/PCL2] 可选提案）VR版本的Minecraft在安装完毕后自动补充文件 (Issue #1517)





 
什么 VR 版本……
 顺便传个 Log……

**Comment by LTCatt** [comment]
我不知道你说的这个 VR 版本是啥意思……
以及如果下载不了，尝试启动一次并且上传 Log。

**Comment by LTCatt** [comment]
那如果之后能复现再说.jpg
