### ISSUE TITLE
Mod/整合包搜索记录搜索历史

### ISSUE THREAD

**Issue by Chormore-EDGE** [Hex-Dragon/PCL2#1526]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

额。，就比如加个
![image](https://user-images.githubusercontent.com/114737601/228532844-e467f40a-dde0-4b3b-9b29-98d060bbee00.png)
在
mod和整合包里面加个按钮（或者直接显示

### 原因

就是看一下记录（搜索mod的时候忘记哪个mod真的很麻烦:（

**Comment by Chormore-EDGE** [comment]
由于我是在周三发的issue，所以周五六日再能回(不会关吧

**Comment by youzi-2333** [comment]
就是 Mod 或整合包显示搜索记录？
感觉挺实用的，先看龙猫打不打算丢 Discussion 吧……
暂时搜不到重复 Issue（）

**Comment by Chiloven945** [comment]
嗯……感觉类似于选择框的那种UI显示搜索记录应该挺不错的

**Comment by youzi-2333** [comment]
离线启动的 ID 输入框已经能显示历史记录了，感觉这个功能做起来不难，但是适用性可能有点小（毕竟谁会不停的搜同一个 Mod）……
得看龙猫怎么考虑。

**Comment by iPodtouch6557** [comment]
> 离线启动的 ID 输入框已经能显示历史记录了，感觉这个功能做起来不难，但是适用性可能有点小（毕竟谁会不停的搜同一个 Mod）…… 得看龙猫怎么考虑。

我就会，我会把相同内容的版本分开来，复制黏贴又会炸文件（）

**Comment by LTCatt** [comment]
先丢进投票，如果之后票数低可能会拒绝，票数高就做 =。=

**Comment by LTCatt** [comment]
考虑制作较为复杂且适用面很小，投票票数也非常悲伤，暂不考虑制作……
