### ISSUE TITLE
1.16.1-Fabric游戏安装失败

### ISSUE THREAD

**Issue by snapshot6** [Hex-Dragon/PCL2#1530]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

下载1.16.1 fabric版本游戏时，过一会儿报错显示
“1.16.1-Fabric 0. 14.18安装失败:远程服务器返回错误: (404) 未找到。”

### 重现步骤

1、打开启动器
2、点击下载选项的自动安装
3、在正式版中找到1.16.1
4、安装预览中选择第一个Fabric和API
5、点击开始安装
6、显示错误
![image](https://user-images.githubusercontent.com/119095483/229034151-74650c53-c4ec-47a8-818d-4acccaec9658.png) #

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11118578/Log2.txt)

**Comment by snapshot6** [comment]
下载源也换过，都是显示这样的

**Comment by LTCatt** [comment]
已确认。

正确地址：https://cdn.modrinth.com/data/P7dR8mSH/versions/0.18.0%2Bbuild.387-1.16.1/fabric-api-0.18.0%2Bbuild.387-1.16.1.jar
错误地址：https://cdn.modrinth.com/data/P7dR8mSH/versions/0.18.0%2Bbuild.387-1.16.1/fabric-api-0.18.0%252Bbuild.387-1.16.1.jar
