### ISSUE TITLE
MOD管理功能扫描子文件夹MOD

### ISSUE THREAD

**Issue by zslingy** [Hex-Dragon/PCL2#1536]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

forge端的1.16.5和1.18.2有个chms（子文件夹MOD扫描器）MOD，在旧版本PCL2中可以扫描出子文件夹的MOD，更新两个版本之后就不行了，故希望猫猫把这个功能加回来或者放在设置选项里qwq

### 原因

这项优化让我可以更方便地管理MOD。
如果没有这项优化，我每次都必须点开MOD文件夹，让操作变得很麻烦。

**Comment by WForst-Breeze** [comment]
请见 #811 和 #1098，此功能已被移除，由于 .minecraft/mods 文件夹下创建的子文件夹内的 Mod 不被模组加载器（此为如 Forge、Fabric 类模组加载器行为，非 PCL2 行为）加载，因此在新版本中移除了此功能。但如果子文件夹名称为版本名则仍会读取并加载

感谢您的反馈

**Comment by zslingy** [comment]
https://www.mcmod.cn/class/5353.html
对的啊qwq
![image](https://user-images.githubusercontent.com/122713886/229261631-5af1dce0-32a3-42e4-b6df-2559de42462b.png)

**Comment by zslingy** [comment]
对的啊
![image](https://user-images.githubusercontent.com/122713886/229261659-b56f19a3-e7a7-4229-8a11-f5753f3b9969.png)

**Comment by WForst-Breeze** [comment]
好的好的，明白了，这边初步确认了，抱歉qwq……看看龙猫怎么想

**Comment by iPodtouch6557** [comment]
~机器人抽风了~

**Comment by youzi-2333** [comment]
umm 建议加了 chms Mod 之后（即 Mod 在 jar 中储存的名称包括 chms）再显示子文件夹的 Mod……
不过不知道可不可以实现（）

**Comment by LTCatt** [comment]
PCL 无法检测具体安装了哪些 Mod，所以 Mod 带来的行为改变不会被支持 Orz

**Comment by zslingy** [comment]
可是扫描子文件夹MOD是PCL原先就具有的功能不是嘛？

**Comment by WForst-Breeze** [comment]
> 可是扫描子文件夹MOD是PCL原先就具有的功能不是嘛？

关于移除这个功能的理由见上，因为一般情况下模组加载器不会加载子文件夹中的 Mod TwT
