### ISSUE TITLE
[优化] 将更新日志的网页改为 Biligame Wiki

### ISSUE THREAD

**Issue by youzi-2333** [Hex-Dragon/PCL2#1537]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

将设置页面版本右侧的“更新日志”按钮改为 Biligame Wiki。
#512 提及该问题被拒绝，但目前 Biligame Wiki 已较为完善，并且更新速度较快，格式也没有大问题，帮助库同样使用了该映像站，因此（应该）可以进行修改。

### 原因

这项优化方便部分地区访问 Minecraft 更新日志。
如果没有这项优化，国内部分地区可能无法访问 Minecraft Wiki。

**Comment by Chiloven945** [comment]
或许可以加个开关什么的（

**Comment by LTCatt** [comment]
更新日志涉及同步速度问题，新出的版本还是主站比较快。
暂时还是不考虑 =。=
