### ISSUE TITLE
PCL内测版本总是会被系统内置的防火墙阻止更新，使用几分钟后会被自动删除。

### ISSUE THREAD

**Issue by Coriodu** [Hex-Dragon/PCL2#1538]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

PCL内测版本总是会被系统内置的防火墙阻止更新，使用几分钟后会被自动删除。这是在上上个月就有的问题，希望龙猫能处理下。

版本	Windows 11 专业版
版本	22H2
操作系统版本	22624.1470

### 重现步骤

1.就是你刚使用时是不会被删除的，但2-5分钟后就被自动删除。
2.win11自带的安全软件在PCL更新时报毒。

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11128268/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11128273/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11128274/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11128275/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11128276/Log5.txt)

**Comment by WForst-Breeze** [comment]
请见 #666，此为误报，请在 Windows Defender 为 PCL2 添加排除项，参考 [将排除项添加到 Windows 安全中心](https://support.microsoft.com/zh-cn/windows/%E5%B0%86%E6%8E%92%E9%99%A4%E9%A1%B9%E6%B7%BB%E5%8A%A0%E5%88%B0-windows-%E5%AE%89%E5%85%A8%E4%B8%AD%E5%BF%83-811816c0-4dfd-af4a-47e4-c301afe13b26)
