### ISSUE TITLE
23w13a_or_b被错误地归类为预览版

### ISSUE THREAD

**Issue by Chiloven945** [Hex-Dragon/PCL2#1545]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如题
此版本应该为愚人节版本
![image](https://user-images.githubusercontent.com/116699482/229286257-17b69259-761c-4ba1-a0dd-28c99cc15ad0.png)
![image](https://user-images.githubusercontent.com/116699482/229286347-e7321238-cef3-4497-8d3b-0360ee161032.png)

### 重现步骤

打开下载页面

### 日志与附件

-

**Comment by Chormore-EDGE** [comment]
看来确实是

**Comment by xiaoyi4335yyds** [comment]
现在直接没了

**Comment by WForst-Breeze** [comment]
> 现在直接没了

请在 **设置-启动器-下载-版本列表获取** 选择 **尽量使用官方源**，即可第一时间获取到版本更新~

- 请注意，镜像源更新速度较慢，所以经常会出现看不到新版本的情况。如果您的网络环境较好，可以使用上述解决方案；如果网络环境不佳，推荐使用镜像源，但可能需要等待一段时间后才能下载最新版本。

**Comment by iPodtouch6557** [comment]
> > 现在直接没了
> 
> 请在 **设置-启动器-下载-版本列表获取** 选择 **尽量使用官方源**，即可第一时间获取到版本更新~
> 
> * 请注意，镜像源更新速度较慢，所以经常会出现看不到新版本的情况。如果您的网络环境较好，可以使用上述解决方案；如果网络环境不佳，推荐使用镜像源，但可能需要等待一段时间后才能下载最新版本。

之前的22w13oneblockatatime就好长一段时间以后才被归为愚人节版本，所以应该等等就好了……？
