### ISSUE TITLE
反馈界面有点奇怪(?)

### ISSUE THREAD

**Issue by Xx114514xX1819** [Hex-Dragon/PCL2#1548]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

启动器为最新版本，可以正常打开github（感觉左边好像少了什么）
![image](https://user-images.githubusercontent.com/114345474/229295958-a9caf273-f769-4f47-a9af-6e6bb6c17444.png)

### 重现步骤

1、点击更多
2、点击反馈

### 日志与附件

[Log.txt](https://github.com/Hex-Dragon/PCL2/files/11129793/Log.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11129794/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11129795/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11129796/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11129797/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11129792/Log5.txt)

**Comment by WForst-Breeze** [comment]
兄啊，你这启动器也不是最新版本啊（捂脸）最新版本是 2.5.2
```
[22:33:54.012] [Start] 程序版本：Snapshot 2.2.10（249）
```

**Comment by Xx114514xX1819** [comment]
不好意思，我脑子有点小问题，忘记是刚刚装的系统了
