### ISSUE TITLE
1.14.4-Fabric 0.14.18-OptiFine_G5安装失败

### ISSUE THREAD

**Issue by WangZhePanPan** [Hex-Dragon/PCL2#1549]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

1.14.4-Fabric 0.14.18-OptiFine_G5安装失败，显示远程服务器返回错误，（404）未找到
当时的截图：
![QQ截图20230401223825](https://user-images.githubusercontent.com/129606781/229296212-614836a1-2cd4-4414-8a16-d73c1f365a12.png)

### 重现步骤

1、点击“下载”
2、往下滚，然后点击“1.14.4”
3.然后点击“OptiFine”
4.然后点击“1.14.4 G5”
5.然后点击“Fabric”
6.然后点击“0.28.5”
7.然后点击“开始安装”

### 日志与附件

![QQ截图20230401223825](https://user-images.githubusercontent.com/129606781/229296264-83eb1960-eb3a-47b5-96d0-af87cb1bdc8f.png)

**Comment by hejiehao** [comment]
#1530

**Comment by YUANXINGlingyun** [comment]
应该也是地址的问题
@LTCatt

**Comment by youzi-2333** [comment]
本质和 #1530 一样吧……
如果修好之后仍然有这个问题，可以再提出（悲）……
