### ISSUE TITLE
可以从本地文件安装forge

### ISSUE THREAD

**Issue by hejiehao** [Hex-Dragon/PCL2#1550]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

可以从本地文件安装forge

### 原因

由于forge在pcl2中没有官方下载源，可能镜像源不是最新版本
这样可以确保forge为最新版本

**Comment by LTCatt** [comment]
![image](https://user-images.githubusercontent.com/40348278/229307697-c848f290-7e9e-4b97-a0b3-11ca8570b608.png)
可以在这里选用官方源……
考虑到适用面太小，不会考虑制作，抱歉 orz

**Comment by hejiehao** [comment]
> ![image](https://user-images.githubusercontent.com/40348278/229307697-c848f290-7e9e-4b97-a0b3-11ca8570b608.png) 可以在这里选用官方源…… 考虑到适用面太小，不会考虑制作，抱歉 orz

#1533

**Comment by LTCatt** [comment]
**版本列表** 会使用官方源。
