### ISSUE TITLE
自定义图片帮助

### ISSUE THREAD

**Issue by misividkoukou** [Hex-Dragon/PCL2#1551]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

感觉还是有必要在自定义图片那里写一个推荐的图片尺寸大小与支持格式（不然第一次用会十分迷糊）

### 原因

一个次要的小建议（

**Comment by YUANXINGlingyun** [comment]
等等,在哪里写?
~~帮助界面的话就不是在这里反馈了~~

**Comment by misividkoukou** [comment]
> 等等,在哪里写? ~帮助界面的话就不是在这里反馈了~

肯定是直接在pcl里面显示啊（话说帮助页面好像也没有关于这个的提示吧

**Comment by LTCatt** [comment]
PCL 的窗口大小可以调整，所以并没有一个标准的推荐尺寸……
