### ISSUE TITLE
1.5被错误地归类为预览版

### ISSUE THREAD

**Issue by Jingwen178** [Hex-Dragon/PCL2#1552]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如题
此版本应该为正式版
![image](https://user-images.githubusercontent.com/129640814/229330441-d5b1aaff-1eed-4f8b-a45e-e3d66135f1c0.png)

### 重现步骤

1、打开下载页面
2、向下滚
3、点击1.5版本
4、点击开始安装
5、打开启动页面
6、点击版本选择
7、向下滚

### 日志与附件

没有

**Comment by Chiloven945** [comment]
成功复现
![image](https://user-images.githubusercontent.com/116699482/229330670-3e8509cf-e42e-49d6-88b6-c6de0d0bff8f.png)

**Comment by WForst-Breeze** [comment]
稳定复现，感谢您的反馈~
![image](https://user-images.githubusercontent.com/110760354/229330807-cb6f0437-401f-47ba-94c9-094e6e1521bb.png)

![image](https://user-images.githubusercontent.com/110760354/229330800-81de446f-1606-4820-ae71-06bc71cbb115.png)

**Comment by LTCatt** [comment]
![image](https://user-images.githubusercontent.com/40348278/229337324-f61c5b24-fd84-4efa-9e3d-1fbbfc12c4e0.png)

这是因为 Mojang 手动将该版本标记为了快照版。
请向 Mojang 反馈该 Bug。
