### ISSUE TITLE
快捷切换联网更新主页和本地文件主页

### ISSUE THREAD

**Issue by WorldHim** [Hex-Dragon/PCL2#1554]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

希望加入快捷切换的按钮来切换各个主页来源或使多个主页以一定方式共存。
---
原始 Discussion: #1553；作者: @xianhongtao。

### 原因

现在联网更新的主页和用户自己写的主页不能共存，导致了使用不便，希望能加入快捷切换的按钮来切换各个主页来源或使多个主页以一定方式共存。

**Comment by LTCatt** [comment]
适用面太小，暂时不考虑，抱歉（

**Comment by xianhongtao** [comment]
不小啦，而且也不是很难，就把设置里的那几个切换按钮复制到主页就好了

**Comment by xianhongtao** [comment]
别放弃啊
