### ISSUE TITLE
explorer卡崩造成的PCL闪退

### ISSUE THREAD

**Issue by ccjjfdyqlhy** [Hex-Dragon/PCL2#1555]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

PCL窗口实例未响应数秒后闪退，输出错误报告

### 重现步骤

启动数个游戏实例至显卡出错被动触发explorer闪退后，PCL出现此BUG

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11131356/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11131359/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11131360/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11131361/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11131362/Log5.txt)

**Comment by Chormore-EDGE** [comment]
很正常啊，内存不足资源管理器就会GG，pcl自然也会GG

**Comment by youzi-2333** [comment]
参见 #685 ，`HRESULT` 不是 PCL 的问题，PCL 无法修复。
出现 `explorer` 或 `dwm` 等系统进程崩溃导致 PCL 崩溃的话也不好处理……之后让龙猫加个弹窗提示一下吧（悲）~~所以扯了这么多~~感谢您的反馈～
