### ISSUE TITLE
“龙猫一言”Copilot快照及其他更新预案（雾）

### ISSUE THREAD

**Issue by MeditatorLogic** [Hex-Dragon/PCL2#1557]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

1.把游戏下载源的版本自动检测一下，把4月1日发布的版本自动归类为“愚人节版本”
2.常逝照（我）搬（想）网（得）易（美）的联机方式？？？啊对了，能不能自动整一个盗版账号也能联机的那种？？？（就是只要登录电子邮箱号就能自动生成的账号）（要是有什么法律问题就别弄了）
3.往启动器里自动加几首滑稽的歌，愚人节的时候可以放
4.增加人品值为“-1”，并链接“屎黄皮肤”
………………………………（以下是重点）………………………………
###1.常逝在启动器里加一个forum，把内测群随便发的一些攻略或者自制皮肤、MOD放进来
###2.常逝在侩肇阪苯启动器街边右侧日志那里加一个“龙猫一言”离线AI语言对话系统，主要是用来装逼（恒星级大雾）

### 原因

说什么呢……
这是计划的一部分O.o

**Comment by YUANXINGlingyun** [comment]
???
~~感觉大概率会拒绝~~

**Comment by Chiloven945** [comment]
23年愚人节版本问题正在处理
任何功能需要用到服务器什么的比如说论坛基本上不会同意，这个有前车之鉴
如果你有多个问题可以尝试提交多个issue，或者说是先发个discussion问问情况

**Comment by LTCatt** [comment]
全部拒绝，抱歉（

**Comment by iPodtouch6557** [comment]
~6~

**Comment by YUANXINGlingyun** [comment]
6.jiff
