### ISSUE TITLE
启动器将JVM错误报为显卡不支持，并提供了不正确的建议

### ISSUE THREAD

**Issue by SolidBlock-cn** [Hex-Dragon/PCL2#1558]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

Minecraft在运行时，遇到JVM异常（如附件所示）。但启动器称是显卡不支持，这显然不正确。
且启动器的建议是替换为Java 8.0.51以下的版本，这一建议也是不正确的。对于显卡不支持的情况，应该首先尝试使用Minecraft官方启动器自动下载的Java版本，这可能就会支持。或者，在显卡设置中，确认java使用的是独显（如nvidia）而不是集显（如intel）（对于同时有独显和集显的情况，往往会默认使用集显）。显卡版本因人而异，不能简单地用Java的版本划分。且1.17开始，就不再支持Java 16以下的版本，就更不应该建议使用8.0.15以下的Java版本了。

### 重现步骤

1、点击xxxx
2、往下滚，然后点击xxxx

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11131796/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11131797/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11131798/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11131799/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11131800/Log1.txt)
[hs_err_pid8408.log](https://github.com/Hex-Dragon/PCL2/files/11131803/hs_err_pid8408.log)

**Comment by LTCatt** [comment]
EXCEPTION_ACCESS_VIOLATION 并不能提供足够的信息给启动器判断具体的崩溃原因，请补充完整的崩溃报告……

**Comment by SolidBlock-cn** [comment]
这个是jvm的错误，crash-reports文件夹中是没有的。只有hs_error开头的文件（我已经上传到本帖的附件了）。启动器的界面中，点击打开崩溃报告也是打开的这个文件。

**Comment by LTCatt** [comment]
PCL 会生成崩溃报告……

**Comment by SolidBlock-cn** [comment]
我还没有导出崩溃报告压缩包，然后电脑崩了。如有需要，我可以提供游戏日志，不过有20多兆。

**Comment by SolidBlock-cn** [comment]
我再次遇到了这个错误，以下是报告 。
[错误报告-2023-4-3,_周一_下午_12.33.31.zip](https://github.com/Hex-Dragon/PCL2/files/11134746/-2023-4-3._._._12.33.31.zip)

**Comment by LTCatt** [comment]
umm 那你现在知道崩溃的原因和解决方案了么

**Comment by SolidBlock-cn** [comment]
可能只是愚人节版本自身的bug，不过我也不确实为什么会变成jvm的错误。不过肯定的是不是显卡的问题，更不是java版本过新。

**Comment by YUANXINGlingyun** [comment]
那么应当增加一个启动愚人节版本时崩溃的提示（为了减少此类反馈）？

**Comment by LTCatt** [comment]
如果不知道崩溃的原因和解决方案，我也没法把它加进检测里 :(
如果之后情况有变再 Reopen 吧……
