### ISSUE TITLE
版本更新时Window defender阻止，提示携带Win32/Wacatac.H!ml

### ISSUE THREAD

**Issue by FSEPIC** [Hex-Dragon/PCL2#1562]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在版本Snapshot2.2.10(249.0)中更新，平台为Windows 11 22H2中，windows defender阻止更新。

- System.ComponentModel.Win32Exception感觉之所报这个错是windows defender阻止导致的
- Win32/Wacatac.H!ml是收集个人信息的木马病毒，该病毒藏在注册表中，且与文件相关联
- windows在2023/4/2刚刚更新至最新版

### 重现步骤

1、点击更新后出现

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11132219/Log1.txt)

**Comment by youzi-2333** [comment]
请将 PCL 添加至 Windows Defender 的排除项中。[将排除项添加到 Windows 安全中心](https://support.microsoft.com/zh-cn/windows/%E5%B0%86%E6%8E%92%E9%99%A4%E9%A1%B9%E6%B7%BB%E5%8A%A0%E5%88%B0-windows-%E5%AE%89%E5%85%A8%E4%B8%AD%E5%BF%83-811816c0-4dfd-af4a-47e4-c301afe13b26)
这不属于 PCL 的 Bug，龙猫也没法修，抱歉 Orz（

**Comment by FSEPIC** [comment]
> 请将 PCL 添加至 Windows Defender 的排除项中。[将排除项添加到 Windows 安全中心](https://support.microsoft.com/zh-cn/windows/%E5%B0%86%E6%8E%92%E9%99%A4%E9%A1%B9%E6%B7%BB%E5%8A%A0%E5%88%B0-windows-%E5%AE%89%E5%85%A8%E4%B8%AD%E5%BF%83-811816c0-4dfd-af4a-47e4-c301afe13b26) 这不属于 PCL 的 Bug，龙猫也没法修，抱歉 Orz（） 不过龙猫在每个公测版发布之前会向 Microsoft 汇报，以避免 Release 版本被误杀；快照版则不会（~总不能老是麻烦人家微软吧？~）

那确实，BTW，我尝试过把它加入排除项中，但是结果还是一样的。
