### ISSUE TITLE
PCL2设置中游戏选项中“启动选项”无法正常向下翻

### ISSUE THREAD

**Issue by 404nfwpz** [Hex-Dragon/PCL2#1563]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

PCL2设置中游戏选项中，使用鼠标翻到“启动选项”时如果继续向下翻会不受控制的突然加速，翻过去以后又恢复正常。

### 重现步骤

1、到设置页面选择“游戏”选项
2、往下滚，找到启动选项，继续向下翻
（我不知道这是不是我设备的原因。~~悲~~）

### 日志与附件

https://user-images.githubusercontent.com/98506236/229356942-28e2c891-737c-40d9-9f3a-a085b1432c35.mp4

**Comment by Chiloven945** [comment]
PCL应该会在滚动时自动对齐那些选项，所以说就没有平滑滚动的效果所以说看起来很快（
应该是吧

**Comment by LTCatt** [comment]
……要不要换个鼠标试试？这个看起来不是 PCL 导致的

**Comment by 404nfwpz** [comment]
> ......要不要换个鼠标试试？这个看起来不是 PCL 导致的

不会吧，我用触控板和别的鼠标也是这个效果

**Comment by LTCatt** [comment]
是否有其他人可以复现？
我更倾向于是个人的环境问题，而非 PCL 的问题……
如果有其他人可以复现再作修复，没有的话就先关了。

**Comment by Chiloven945** [comment]
稳定复现，使用触控板
而且任何的这种下拉栏和填写框都会触发
![屏幕录制-2023-04-09-142254](https://user-images.githubusercontent.com/116699482/230758010-07aeccfa-c2d3-41a3-8805-4b0708eabaea.gif)

https://user-images.githubusercontent.com/116699482/230758196-8e65692d-5c75-4b70-bb8b-baa2e3792952.mp4

**Comment by iPodtouch6557** [comment]
我猜想是对于对于自动对齐复选框的判定出了问题？

**Comment by LTCatt** [comment]
需要使用触摸设备才能触发？

**Comment by Chiloven945** [comment]
> 需要使用触摸设备才能触发？

鼠标都可以的

**Comment by iPodtouch6557** [comment]
> 如果 Issue 提的是 往下翻的时候 鼠标经过下拉框，向下的速度会变快，那么我可以复现…… 而且由于 鼠标悬浮在下拉框上方时 可以直接通过滚轮更改下拉框的选项，向下滚动时有可能意外的修改某些设置项（）还有可能卡死不动（这是由于这个下拉框选中了最后一个选项）
> 
> ~不传录屏了，中国移动把 GitHub 映像站封了，现在慢的要死~

总之是跟下拉框和自动对齐的问题吧
~嘿嘿嘿还好我用电脑~

**Comment by iPodtouch6557** [comment]
哦，对了，我现在不知咋搞的也能了，只能触控板

**Comment by 404nfwpz** [comment]
DC01-31FB-A0D5-213D
awa

**Comment by LTCatt** [comment]
你的解锁码：1HnElWqu1KGmGe0pCUw44U6cx557jZAX
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
