### ISSUE TITLE
java路径允许设置相对路径

### ISSUE THREAD

**Issue by Qian-F** [Hex-Dragon/PCL2#1568]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

在java路径处允许自定义或者选择使用绝对路径/相对路径

### 原因

打包分发客户端整合时可以减少关于使用java的相关问题

**Comment by LTCatt** [comment]
![image](https://user-images.githubusercontent.com/40348278/229602422-aa0af5ba-7b23-474b-9485-17379fc1a4bb.png)
