### ISSUE TITLE
添加自选下载源

### ISSUE THREAD

**Issue by Yexiaowei11** [Hex-Dragon/PCL2#1570]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

1.
自选下载源
MCBBS 下载源
官方 下载源
BMCLAPI 下载源
2.
修改界面语言

### 原因

添加下载源 给网络较差的地方的用户使用
添加界面语言方便国外用户使用

**Comment by YUANXINGlingyun** [comment]
界面语言的提案已被拒绝 ~~issue号多少来着~~
下载源的话...估计不会太有戏

**Comment by WForst-Breeze** [comment]
1. 自选下载源：
MCBBS 源是 BMCLAPI 的一个特别镜像，由于合作域名无法绑定，所以只好独立域名运作，其目录结构和提供的API内容和BMCLAPI 完全一致，所以只分成镜像源和官方源足矣（见 [BMCLAPI Doc](https://bmclapidoc.bangbang93.com/#api-_)）

2. 修改界面语言：#119

感谢您的反馈~
