### ISSUE TITLE
快照版更新说启动器更新失败系统时间不准确，下载验证未通过。

### ISSUE THREAD

**Issue by HimiluKi** [Hex-Dragon/PCL2#1571]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

无论是打开pcl后弹出的更新还是自己检查更新输入更新密钥后更新都无法更新，都显示系统时间不准确。但是我开启了自动设置时间，且关闭尝试过。同时进行过重启、完全删除pcl、下载2.3.0和群里的2.2.10、询问群友等各种尝试。均无法更新。

### 重现步骤

1、点击检查更新
2、输入更新密钥
3、启动器更新失败，系统时间不准确

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11148084/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11148085/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11148086/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11148087/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11148088/Log1.txt)

**Comment by iPodtouch6557** [comment]
请在windows设置-时间和语言-设置与时间里点击同步时间，一般可以解决

**Comment by HimiluKi** [comment]
> 

我描述中说过试过了

**Comment by bwtx2023** [comment]
用的啥运营商的宽带？

**Comment by iPodtouch6557** [comment]
> > 
> 
> 我描述中说过试过了

是同步时间，不是自动设置

**Comment by HimiluKi** [comment]
> > > 
> > 
> > 
> > 我描述中说过试过了
> 
> 是同步时间，不是自动设置，不信你看
> 
> ![image](https://user-images.githubusercontent.com/118656946/229965236-29799de2-4bf6-4109-bfcf-75a3e4d05da5.png)

这个同步我也试过了，不过自动设置时区我没有，我这个地方是黑的点不了。不知道怎么打开自动设置时区

**Comment by HimiluKi** [comment]
> 用的啥运营商的宽带？

联通

**Comment by HimiluKi** [comment]
> > > 
> > 
> > 
> > 我描述中说过试过了
> 
> 是同步时间，不是自动设置，不信你看
> 
> ![image](https://user-images.githubusercontent.com/118656946/229965236-29799de2-4bf6-4109-bfcf-75a3e4d05da5.png)

刚刚网上搜了下把自动设置时区也打开了，打开之后同步时间，然后去更新，还是提示时间不对。

**Comment by iPodtouch6557** [comment]
发个截图我看看，这有助于我判断问题

**Comment by HimiluKi** [comment]
> 发个截图我看看，这有助于我判断问题
![QQ截图20230405181834](https://user-images.githubusercontent.com/129856819/230052938-bb8faac2-258e-4ff8-9635-06540f4e55a6.png)
![QQ截图20230405181903](https://user-images.githubusercontent.com/129856819/230052952-57376d8a-d3aa-4627-a4e9-ee6405300c21.png)

**Comment by HimiluKi** [comment]
> 可以试试与 [时间](https://time.is) 对一下 ~我曾经用这个解决过cloudflare问题~

![QQ截图20230405190845](https://user-images.githubusercontent.com/129856819/230063516-84c7bdb7-d5d9-4f8c-85bf-cb7fde4bb513.png)
怎么让系统变成这个时间，卡不住那0.2秒（）

**Comment by iPodtouch6557** [comment]
同步时间

**Comment by youzi-2333** [comment]
……两分钟以内的误差应该都可以的吧？
而且这个 403 报错其实不一定是系统时间不准确（他说的是“可能”），也有可能是更新码多了一个空格（）

**Comment by HimiluKi** [comment]
> 

哈哈，空格这种情况也是考虑过的。就是实在没办法了才来这里反馈。

**Comment by HimiluKi** [comment]
> ……两分钟以内的误差应该都可以的吧？ 而且这个 403 报错其实不一定是系统时间不准确（他说的是“可能”），也有可能是更新码多了一个空格（）
哈哈，空格这种情况也是考虑过的。就是实在没办法了才来这里反馈。

**Comment by HimiluKi** [comment]
![QQ截图20230405193806](https://user-images.githubusercontent.com/129856819/230070330-2ec43cf4-ee91-4f2e-bc84-f0b744e4ee5d.png)
怎么好像越搞越差了，现在我连输码界面都打不开了。也没下杀毒软件。

**Comment by HimiluKi** [comment]
![QQ截图20230405194527](https://user-images.githubusercontent.com/129856819/230070969-193358c5-ad3f-4643-ac94-ebe384f773ae.png)
又回到了这个情况，输了码之后显示这个。同步之后也没用。

**Comment by HimiluKi** [comment]
草，问题解决了。我连手机热点就可以更新了，是wifi的问题草。
