### ISSUE TITLE
能否保证JavaWrapper.jar在所有机器上都是相同的文件

### ISSUE THREAD

**Issue by 150149** [Hex-Dragon/PCL2#1578]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

能否保证JavaWrapper.jar在所有机器上都是相同的文件，我是反作弊的开发者，我在制作反作弊的过程中获取MOD列表的时候，会将加载的Jar都进行一次Hash校验，但是我发现JavaWrapper.jar像是每台机器上的Hash都不一致，我们无法确定该文件是否被恶意修改，因此我们希望能保证JavaWrapper.jar在所有机器上都是相同的文件

### 原因

能否保证JavaWrapper.jar在所有机器上都是相同的文件，我是反作弊的开发者，我在制作反作弊的过程中获取MOD列表的时候，会将加载的Jar都进行一次Hash校验，但是我发现JavaWrapper.jar像是每台机器上的Hash都不一致，我们无法确定该文件是否被恶意修改，因此我们希望能保证JavaWrapper.jar在所有机器上都是相同的文件

**Comment by LTCatt** [comment]
JavaWrapper 已确保使用相同 PCL 版本时是相同的文件，如果你发现文件不一样一定是对方没有更新 PCL。
