### ISSUE TITLE
添加对已安装模组的中文名称识别

### ISSUE THREAD

**Issue by WForst-Breeze** [Hex-Dragon/PCL2#158]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

如题，对 Mod 管理中 Mod 列表里列出的模组的文件名旁添加对于该模组的中文名称显示功能，这一点可以看一下 [Hello Minecraft! Launcher](https://gitee.com/huanghongxun/HMCL/) ！
![qwq](https://user-images.githubusercontent.com/110760354/192219263-c2b91240-a498-4702-8f64-2ae704cccba2.png "HMCL中的此功能，这里特地用了模组文件名前没有中文的整合包作为演示")

### 原因

此功能可以更加方便玩家直接查看整合包内的模组，当模组文件名前没有标注中文名称时，有这个功能做辅助可以提高查看效率！即使不能使全部模组都被标注其中文名称，但也至少可以让玩家了解该整合包中的主要和热门模组以方便玩家更好地进行游戏。

**Comment by kong-que-dnf123** [comment]
快一年了欸......
