### ISSUE TITLE
PCL图标显示不正确

### ISSUE THREAD

**Issue by Walkers58792** [Hex-Dragon/PCL2#1580]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

图标分辨率低 且与正常图标不一样 正常图标有PCL三个字母 我的图标只有一个P 而且很糊

### 重现步骤

没招

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11155729/Log2.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11155730/Log1.txt)

**Comment by hejiehao** [comment]
新版不是变成了一个p吗

**Comment by Big-Cake-jpg** [comment]
请提供能体现问题所在的屏幕截图。
