### ISSUE TITLE
自定义主页错误

### ISSUE THREAD

**Issue by misividkoukou** [Hex-Dragon/PCL2#1582]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我在编写我们服务器的整合包时遇见了如下问题：pcl2显示
![image](https://user-images.githubusercontent.com/121597192/230020121-22abe57b-1375-4e48-ba86-457efe11f5e4.png)
但我不认为这个文件具有问题（也许吧
 <local:MyCard Title="Areocraft整合包使用说明">
    <StackPanel Margin="25,40,23,15"> 
    
 <TextBlock TextWrapping="Wrap"
                 Text="整合包版本号：230405a   |   整合包制作：misivid_koukou" />

 <TextBlock TextWrapping="Wrap" 
                 Text="请保持启动器—PCL2为最新公开版（当然内测用户可以将它改为内测版)" />

        <local:MyButton Margin="0,8,0,10" Width="250" Height="35" ColorType="Highlight"
                   Text="ac" EventType="弹出窗口" EventData="666"/>

    </StackPanel>
</local:MyCard>
    
<local:MyCard Title="百宝箱">
    <StackPanel Margin="25,40,23,15">

       <local:MyButton Margin="0,8,0,10" Width="250" Height="35" ColorType="Highlight"
                   Text="打开 MCBBS" EventType="打开网页" EventData="https://www.mcbbs.net/" />

<local:MyButton Margin="0,8,0,10" Width="250" Height="35" ColorType="Highlight"
                   Text="打开 Wiki" EventType="打开网页" EventData="https://minecraft-zh.gamepedia.com/Minecraft_Wiki" ToolTip="点击打开 Minecraft Wiki！" />

<local:MyButton Margin="0,8,0,10" Width="250" Height="35" ColorType="Highlight"
                   Text="打开 B 站" EventType="打开网页" EventData="https://www.bilibili.com/" />

<local:MyButton Margin="0,8,0,10" Width="250" Height="35" ColorType="Highlight"
                   Text="打开 chuckbase" EventType="打开网页" EventData="https://www.chunkbase.com/apps/seed-map" ToolTip="点击打开 Minecraft seed map！" />

<local:MyButton Margin="0,8,0,10" Width="250" Height="35" ColorType="Red"
                   Text="百宝箱" EventType="打开网页" EventData="https://www.bilibili.com/video/BV1GJ411x7h7/?spm_id_from=333.337.search-card.all.click" />

    </StackPanel>
</local:MyCard>
    
    
<local:MyCard Title="快捷启动">
    <StackPanel Margin="25,40,23,15">
  
        <TextBlock TextWrapping="Wrap"
                 Text="Areocraft游戏版本仍旧为1.19.2，用1.19.4版本暂时会出现无法进入服务器的现象，如有其他问题请咨询管理。" />

        <local:MyButton Margin="0,8,0,0" Width="250" Height="35"
                 Text="使用 1.19.2 进入 Areocraft" EventType="启动游戏" EventData="1.19.2-Fabric 0.14.19-OptiFine_I1|mc.hypixel.net"  />

        <local:MyButton Margin="0,8,0,0" Width="250" Height="35"
                 Text="使用 1.19.4 进入 Areocraft" EventType="启动游戏" EventData="1.19.4-Fabric 0.14.19-OptiFine_I3|mc.hypixel.net"  />

    </StackPanel>
</local:MyCard>
而影响使用的是这一行窗口弹出代码

        <local:MyButton Margin="0,8,0,10" Width="250" Height="35" ColorType="Highlight"
                   Text="ac" EventType="弹出窗口" EventData="666"/>
他可以正常显示在自定义页面上但无法正常使用（上文报错）

此问题在2.5.1正式版被发现并在截止于2023年4月5日的最新pcl2内测版被发现

### 重现步骤

大概率把主页文件复制过去试试ac那一个选项就好了吧（

### 日志与附件

[Custom.txt](https://github.com/Hex-Dragon/PCL2/files/11156627/Custom.txt)
说明：因为github不支持xaml文件，所以改为txt上传

**Comment by YUANXINGlingyun** [comment]
不排除因为没有窗口文字导致的错误

**Comment by LTCatt** [comment]
EventData 格式有误，请自行检查弹窗的 EventData 格式
