### ISSUE TITLE
pcl使系统无法更改显示设置

### ISSUE THREAD

**Issue by sanqianxing3313** [Hex-Dragon/PCL2#1583]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在我的电脑上，每当使用pcl2开启minecraft时，系统便会提示无法更改显示设置，无法切换显卡，造成不好的游戏体验
![K(H2T L%( 9K~ZYZ{`QM3_G](https://user-images.githubusercontent.com/122138336/230022698-c59f3a09-7c46-46dc-8346-208b62f2bfae.png)

### 重现步骤

1.开启pcl2
2.点击开始游戏
3.提示无法更改显示设置

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11156628/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11156629/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11156630/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11156632/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11156633/Log5.txt)

**Comment by LTCatt** [comment]
这应当不是我能解决的技术问题 :(
换句话说，我不知道这是怎么引起的，也不知道怎么修复它，所以压根没办法……

**Comment by LTCatt** [comment]
根据英伟达的说明，这可能是由于 PCL 启动的 MC 使用了特定的显卡模式，只能关闭程序解决。
https://www.nvidia.com/content/Control-Panel-Help/vLatest/zh-cn/mergedProjects/nv3dCHS/Closing_Blocking_Programs.htm
