### ISSUE TITLE
minecraft出现错误，然后错误分析有了错误报告，谁能解决一下

### ISSUE THREAD

**Issue by 149441** [Hex-Dragon/PCL2#1584]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃不是 PCL2 的原因，请 **不要** 提交反馈。你可以在 QQ 群里或者论坛找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是游戏本身的问题，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

minecraft出现错误，然后开始错误分析

### 错误报告、日志与附件

[错误报告-2023-04-05_15.58.42.zip](https://github.com/Hex-Dragon/PCL2/files/11156679/-2023-04-05_15.58.42.zip)

**Comment by 149441** [comment]
> 问题 不是提问的地方！

这里不是反馈的网站吗？

**Comment by YUANXINGlingyun** [comment]
但这里是启动器的仓库

**Comment by 149441** [comment]
那哪里才是真正反馈的地方，第一次用这个网站

**Comment by YUANXINGlingyun** [comment]
请到 **QQ群** 或 discussion 版块来提问

**Comment by WForst-Breeze** [comment]
这里是处理 PCL2 建议和 Bug 的页面，请移步 Discussions 提问板块进行求助，感谢您的反馈~
