### ISSUE TITLE
部分模组在MR与CF上支持版本不一致的情况下没有被分离

### ISSUE THREAD

**Issue by RawDiamondMC** [Hex-Dragon/PCL2#1587]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

#1318 没写好，有漏网之鱼...

### 重现步骤

搜索winver.jar

### 日志与附件

![image](https://user-images.githubusercontent.com/112449001/230067174-165aea8b-998b-4677-947f-5ef1a630df01.png)
只有CF上的，推测被合并了
https://modrinth.com/mod/winver/versions
https://www.curseforge.com/minecraft/mc-mods/winver/files

**Comment by LTCatt** [comment]
它在双边支持相同的版本，均为 Fabric / Quilt 1.17 - 1.19。
![image](https://user-images.githubusercontent.com/40348278/230328041-e2f1c122-2eb2-4c0e-93e0-0e4207e350b7.png)
![image](https://user-images.githubusercontent.com/40348278/230328093-d994187a-4fd4-49f4-8dba-6ed8c84c2e2c.png)
