### ISSUE TITLE
.mrpack类型打包的整合包提供支持

### ISSUE THREAD

**Issue by HarayamaRese** [Hex-Dragon/PCL2#1589]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

加入对.mrpack类型打包的整合包提供支持

### 原因

（示例）
我需要这个功能来xxxx。很多人都有xxxx的需求，但如果没有这个功能，就不能xxxx了。
.mrpack类型打包的整合包无法导入到pcl中

**Comment by Chiloven945** [comment]
![image](https://user-images.githubusercontent.com/116699482/230097800-be8701bb-b32a-41d9-b8e1-49914deea9fe.png)
PCL支持mrpack类型整合包的安装
