### ISSUE TITLE
[更多]中显示版本号仍是2.5.2

### ISSUE THREAD

**Issue by RedStone-Noob** [Hex-Dragon/PCL2#1593]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

版本号不对

### 重现步骤

1、点击更多
2、关于界面

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11179154/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11179155/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11179156/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11179158/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11179159/Log5.txt)

**Comment by iPodtouch6557** [comment]
截图？？？

**Comment by WForst-Breeze** [comment]
您用的不就是 2.5.2 吗（
```
[21:16:42.421] [Start] 程序版本：Release 2.5.2（286）
[21:16:42.426] [Start] 识别码：59F6-E227-558D-5BE2
```
