### ISSUE TITLE
存档移植

### ISSUE THREAD

**Issue by ForsakenWarden** [Hex-Dragon/PCL2#1597]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

将低版本存档（如1.12）移植到高版本（如1.19）

### 原因

很多电脑萌新需要这个功能，他们很多都不知道存档的位置在哪，找到后该放到哪里，我当时也是弄了好久才知道的，所以需要这个功能

**Comment by Chormore-EDGE** [comment]
![image](https://user-images.githubusercontent.com/114737601/230702197-78fe1fea-5b50-44d7-ad08-5a2c0844fe21.png)
快捷fang's方式里面有啊，而且网上有教程的

**Comment by Chormore-EDGE** [comment]
而且存档移植万一出了什么问题(存档）那存档不废了吗

**Comment by WForst-Breeze** [comment]
版本设置-概览-快捷方式-存档文件夹
