### ISSUE TITLE
“自动进入服务器” 在最新快照失效

### ISSUE THREAD

**Issue by hejiehao** [Hex-Dragon/PCL2#1598]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

可以在启动游戏的时候直接进入存档，服务器或realms

### 原因

无法设置mc参数，最新的[23w14a](https://www.minecraft.net/en-us/article/minecraft-snapshot-23w14a)已经可以通过添加mc参数在启动游戏的时候直接进入存档，服务器或realms

**Comment by Chormore-EDGE** [comment]
额，隔壁hmcl好像有直接进入服务器的功能，不知道pcl有没有

**Comment by hejiehao** [comment]
> 额，隔壁hmcl好像有直接进入服务器的功能，不知道pcl有没有
> 

都有的

**Comment by Chiloven945** [comment]
![image](https://user-images.githubusercontent.com/116699482/230709382-9c267722-6ff0-4104-9b7b-ba1ca41451ce.png)

**Comment by LTCatt** [comment]
考虑到这个特性的使用者都是高级玩家，可以直接通过修改文件来启用，不需要启动器这边进行支持。
会视作 `“自动进入服务器” 在最新快照失效` 这个 Bug 来修一修。

**Comment by hejiehao** [comment]
> 考虑到这个特性的使用者都是高级玩家，可以直接通过修改文件来启用，不需要启动器这边进行支持。
> 会视作 `“自动进入服务器” 在最新快照失效` 这个 Bug 来修一修。

怎么修改文件，不是添加mc参数吗？
