### ISSUE TITLE
使用github actions自动关闭超时issue

### ISSUE THREAD

**Issue by RawDiamondMC** [Hex-Dragon/PCL2#1602]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

如题。

### 原因

目前超时issue的处理方式是人工关闭，配置个actions可以减少工作量。

### 备注

实际上我是能直接扔pr的，但是因为要设github token所以就先扔个issue了。

如果龙猫觉得能做的话我就去扔pr了。

**Comment by LTCatt** [comment]
根据 issue 的触发难度，有的可能会多等等，所以不太适合自动的超时关闭……

**Comment by deep-dark-forest** [comment]
我认为可以只自动关闭标签为“等待反馈者”“需要社区帮助”“需要社区帮助”的issue
