### ISSUE TITLE
更改更新时弹出输入更新密钥的弹窗内容

### ISSUE THREAD

**Issue by LxHTT** [Hex-Dragon/PCL2#1607]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

就是更新的弹窗。。。  
~~不知道正式版有没有~~  
 - 目前还会提示在**内群**获取密钥，但实际上已经移到**爱发电**了（  
 - 就是如果需要输入密钥的话，可以在弹窗里加一个按钮`获取密钥`，点击后打开爱发电网页。

### 原因

这项优化让一些不太清楚的用户可以更方便地进行更新。~~减少伯特工作量~~
如果没有这项优化，可能会让用户的更新体验变得比较麻烦。

**Comment by LTCatt** [comment]
已经在最新版修改过了
