### ISSUE TITLE
启动日志菜单会紧挨着自定义主页菜单

### ISSUE THREAD

**Issue by TuanZiGit** [Hex-Dragon/PCL2#1610]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

开启调试模式后，启动日志菜单会紧挨着自定义主页的菜单，会盖在上面一点。
![image](https://user-images.githubusercontent.com/46892455/230718111-0cdefc0f-6263-43cb-b90d-c8fa65d8a43e.png)
建议在两个板块中间增加空隙。

### 原因

这玩意不符合MyCard堆叠的排列方式啊……

**Comment by LTCatt** [comment]
你可以自己在最后一张卡片下面加 15 的 Margin……
