### ISSUE TITLE
版本下载页面的设计风格同步mod下载

### ISSUE THREAD

**Issue by TuanZiGit** [Hex-Dragon/PCL2#1612]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在版本下载页面优化选择卡片，同步MOD页面的风格，比如版本类型，发布时间，支持的加载器及版本范围等
![image](https://user-images.githubusercontent.com/46892455/230718568-d07e0687-ac94-4564-a576-85209731f78f.png)
![image](https://user-images.githubusercontent.com/46892455/230718578-f60af179-e44f-412d-b9af-a4f90ab36c03.png)

### 原因

看起来很怪

**Comment by TuanZiGit** [comment]
对了可以再加一个版本搜索功能，有的时候那种较早的预览版比较难找

**Comment by Chiloven945** [comment]
你这改了我感觉看起来更怪了（
![image](https://user-images.githubusercontent.com/116699482/230723064-834e689d-506b-4932-aec1-528c8c4a3134.png)
版本下载界面是跟mod详情页内的版本选择一样的，分一个级大概是：
顶级: Minecraft、Mod
子级: 版本......
你可以这样理解？

**Comment by LTCatt** [comment]
暂时没必要，改那个的话会很卡，并且收益不大……
