### ISSUE TITLE
在已安装mod列表里搜索有下载源的mod，获取对应图标替换红石灯

### ISSUE THREAD

**Issue by TuanZiGit** [Hex-Dragon/PCL2#1613]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

如题，在版本的已安装mod列表内根据mod的信息自动前往mod网站索取对应图标保存并替换红石灯，为避免空间过大，可以使用滚动缓存（我这么叫），即缓存超过一定数量的图标后删除最不常使用的图标/最早缓存的图标。

### 原因

看文件名眼瞎了

**Comment by WForst-Breeze** [comment]
不会很花吗（）看看龙猫怎么想

**Comment by Chiloven945** [comment]
如果单纯替换就很丑（
比如说下载整合包会把整合包的图片拿来当版本图片就非常难看还没有圆角什么的
而且图片应该没有什么用处吧（

**Comment by LTCatt** [comment]
这需要分别获取每个 Mod 的信息，API 调用量太大了，不会做的 Orz
