### ISSUE TITLE
啥时候能上线gitee?

### ISSUE THREAD

**Issue by sleep80** [Hex-Dragon/PCL2#1616]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

Gitee和github的功能差不多，也有issue啥的，而且最关键的是gitee不需要魔法就可以访问，龙猫能否考虑下？

### 原因

Gitee相比github国内用户访问更方便，这样有助于pcl的问题和建议变得更多，更有利于pcl的发展。

**Comment by Chiloven945** [comment]
github是国际通用的，并且功能应该要方便许多
还有就是访问门槛应该不是很低吧，当然如果门槛太低的话实际上会加大负担因为可能有很多的反馈都是无用的

**Comment by sleep80** [comment]
访问门槛并不等于提问门槛，有些人来github是为了有事没事找点乐事凑个热闹

**Comment by LTCatt** [comment]
nope :(

**Comment by Chiloven945** [comment]
> 访问门槛并不等于提问门槛，有些人来github是为了有事没事找点乐事凑个热闹

但是这两点是成正比的，真正愿意去做利于社区事情的人才会去想办法达到这个门槛，而且这点也并不是主要原因

**Comment by trustedinster** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/103629945/d3f99465-7266-4012-b253-887206333b54)
