### ISSUE TITLE
1.19-exp1等快照版本并非pcl特别提供

### ISSUE THREAD

**Issue by sleep80** [Hex-Dragon/PCL2#1617]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在pcl的版本列表中，1.19-exp1这个快照版本是"pcl特别提供”的，但是我们却在prism启动器的版本列表中找到了这个版本。

### 原因

比版本并非pcl特别提供，与事实不符。

**Comment by LTCatt** [comment]
PCL 可以提供，其他启动器也可以提供啊……
但其他启动器提供了，不代表这就不是 PCL 提供的啊……

**Comment by Chiloven945** [comment]
我怎么没看到1.19-exp1在列表里面（

**Comment by sleep80** [comment]
请注意“特别”这两个字。这个词的意思不就是只有pcl启动器才提供的意思吗？

**Comment by sleep80** [comment]
或者说稍微改一下也行，这样子很容易给人带来误解引起争议

**Comment by LTCatt** [comment]
特别提供 ≠ 独家提供，它只是表示官方列表没有提供，又没说不让其他启动器提供了……这有点钻牛角尖了吧……

**Comment by Chiloven945** [comment]
> 请注意“特别”这两个字。这个词的意思不就是只有pcl启动器才提供的意思吗？

特别的意思有：
1.不一般，与众不同。
2.格外。
3.特地，特意。
4.尤其。
此处应为1，但此意并不意味着只有或者说是绝对的

**Comment by lovelysheepfield** [comment]
> 特别提供 ≠ 独家提供，它只是表示官方列表没有提供，又没说不让其他启动器提供了……这有点钻牛角尖了吧……

~~你直接说鲁迅≠周树人得了（~~
额这样其实真的会带来很多误解，那如果真的官方列表没有提供就能叫做特别提供那么是不是forge和fabric也可叫pcl特别提供？

**Comment by WForst-Breeze** [comment]
怎么突然变成辩论了……🤔

此处的 特别提供 指的是以下两点：
- 官方启动器未收录此版本
- PCL2 为玩家准备了这个版本的安装渠道

那么来点阅读理解：特别提供一词想表达的含义是什么？并非是指**只有** PCL2 收录了这个版本，而是 PCL2 为了方便玩家游玩而**特地**为玩家准备的版本安装渠道。您可以品一下，把这个语境中的“特别”换成“特地”，是不是就好理解多了？也就是说，别的启动器当然也可以**特别**或者说**特地**为玩家提供这个版本，两者并不构成冲突矛盾的关系

其次不要偷换概念，Fabric 和 Forge 的安装基本是主流第三方启动器都会有的功能，也就是说这个功能已经是第三方启动器的基本要求之一了，并非 “特别提供”

**Comment by lovelysheepfield** [comment]
> 怎么突然变成辩论了......🤔
> 
> 此处的 特别提供 指的是以下两点：
> 
> * 官方启动器未收录此版本
> * PCL2 为玩家准备了这个版本的安装渠道
> 
> 那么来点阅读理解：特别提供一词想表达的含义是什么？并非是指**只有** PCL2 收录了这个版本，而是 PCL2 为了方便玩家游玩而**特地**为玩家准备的版本安装渠道。您可以品一下，把这个语境中的"特别"换成"特地"，是不是就好理解多了？也就是说，别的启动器当然也可以**特别**或者说**特地**为玩家提供这个版本，两者并不构成冲突矛盾的关系
> 
> 其次不要偷换概念，Fabric 和 Forge 的安装基本是主流第三方启动器都会有的功能，也就是说这个功能已经是第三方启动器的基本要求之一了，并非 “特别提供”

  谁偷换概念了？不是龙猫和@chiloven945他们自己说的“特别”就是指官方启动器其没有的吗？那forge和fabric官方启动器没有说特别提供不是很正常嘛

**Comment by WForst-Breeze** [comment]
> 谁偷换概念了？不是龙猫和@Chiloven945他们自己说的“特别”就是指官方启动器其没有的吗？那forge和fabric官方启动器没有说特别提供不是很正常嘛

冷静……可能是我的表述引起您误解了，向您道歉，不过您看看我的后半句给出了相应的解释🙁

**Comment by Chiloven945** [comment]
> > 特别提供 ≠ 独家提供，它只是表示官方列表没有提供，又没说不让其他启动器提供了……这有点钻牛角尖了吧……
> 
> ~你直接说鲁迅≠周树人得了（~ 额这样其实真的会带来很多误解，那如果真的官方列表没有提供就能叫做特别提供那么是不是forge和fabric也可叫pcl特别提供？

这个特别提供存在的时间非常久远，从我2020年使用PCL以来都一直存在且没有任何争议，而且我相信在未来也没有任何可以争议的点，如果非要抓住这一点不放的话，那么我认为这个讨论就是完全没有意义的了

**Comment by Chiloven945** [comment]
> > 怎么突然变成辩论了......🤔
> > 此处的 特别提供 指的是以下两点：
> > 
> > * 官方启动器未收录此版本
> > * PCL2 为玩家准备了这个版本的安装渠道
> > 
> > 那么来点阅读理解：特别提供一词想表达的含义是什么？并非是指**只有** PCL2 收录了这个版本，而是 PCL2 为了方便玩家游玩而**特地**为玩家准备的版本安装渠道。您可以品一下，把这个语境中的"特别"换成"特地"，是不是就好理解多了？也就是说，别的启动器当然也可以**特别**或者说**特地**为玩家提供这个版本，两者并不构成冲突矛盾的关系
> > 其次不要偷换概念，Fabric 和 Forge 的安装基本是主流第三方启动器都会有的功能，也就是说这个功能已经是第三方启动器的基本要求之一了，并非 “特别提供”
> 
> 谁偷换概念了？不是龙猫和@Chiloven945他们自己说的“特别”就是指官方启动器其没有的吗？那forge和fabric官方启动器没有说特别提供不是很正常嘛

forge与fabric均是模组加载器而不是特殊的客户端，显然这里所说的特别提供是基于游戏本体版本上的讨论而不是其他的附加内容，此处的特别所表达的与众不同的对立方是官方启动器，而且这也并不代表其他启动器不能站在官方启动器的对立面
