### ISSUE TITLE
明明购买了minecraft也创建了档案却提示为购买或未创建档案

### ISSUE THREAD

**Issue by SmailPangCN** [Hex-Dragon/PCL2#1620]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://user-images.githubusercontent.com/120291214/230751909-6e94e120-37b2-45ce-8bee-50dbc5797cfb.png)
![image](https://user-images.githubusercontent.com/120291214/230751930-985d91f9-639d-443a-9ca1-32fa07580f82.png)

### 重现步骤

1、使用微软账号登陆

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11184698/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11184699/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11184700/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11184701/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11184702/Log5.txt)

**Comment by iPodtouch6557** [comment]
印象中有人反映过……
是不是pcl没有及时同步或是网络问题？

**Comment by lovelysheepfield** [comment]
试过其他启动器了没？

**Comment by WForst-Breeze** [comment]
请在官网登陆后稍等几分钟再试，与 PCL2 无关，感谢您的反馈
