### ISSUE TITLE
1192版本无法启动

### ISSUE THREAD

**Issue by LI-WO** [Hex-Dragon/PCL2#1621]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

点开始游戏加载时一直卡在等待游戏窗口出现的步骤

### 重现步骤

点击开始游戏

### 日志与附件

[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11184800/Log5.txt)

**Comment by iPodtouch6557** [comment]
应该是卡一会就会好，一般是电脑问题
upload一个截图看看？

**Comment by LI-WO** [comment]
> 应该是卡一会就会好，一般是电脑问题 upload一个截图看看？

![image](https://user-images.githubusercontent.com/121917689/230758900-6fdc4b67-9ab2-4367-a8fc-df589580ac07.png)

**Comment by LI-WO** [comment]
试了6分钟，进不去

**Comment by iPodtouch6557** [comment]
是一直卡着就不动弹？

**Comment by iPodtouch6557** [comment]
不是，为啥标题会是1192版，~按mojang的版本编号思路没这版本吧~

**Comment by LTCatt** [comment]
游戏问题一般和启动器无关。如果其他启动器能正常启动再考虑是 PCL 的问题。

**Comment by Bandysol** [comment]
> 不是兄弟改个标题吧，为啥标题会是1192版，~按mojang的版本编号思路没这版本吧~

他可能想说：1.19.2

**Comment by LI-WO** [comment]
> 游戏问题一般和启动器无关。如果其他启动器能正常启动再考虑是 PCL 的问题，请先尝试使用其他启动器复现。

hmcl试了，可以打开

**Comment by LTCatt** [comment]
在 HMCL 中导出一个启动脚本传上来？
![image](https://user-images.githubusercontent.com/40348278/231967306-96716ad5-3854-4005-9d8f-e425cd726c80.png)

**Comment by LTCatt** [comment]
请尽快回复，否则可能因为超时关闭 :(

**Comment by LTCatt** [comment]
如果要补充可以继续回复，先关了（

**Comment by GZXH622** [comment]
> 

我和他的问题一样都是卡等待游戏窗口出现 这是我的启动脚本
[启动 1.19.2-生电.zip](https://github.com/Hex-Dragon/PCL2/files/11513595/1.19.2-.zip)

**Comment by LTCatt** [comment]
@GZXH622 可以单独开个新 issue，并且在 HMCL 中导出一个启动脚本传上来
![image](https://user-images.githubusercontent.com/40348278/231967306-96716ad5-3854-4005-9d8f-e425cd726c80.png)
