### ISSUE TITLE
PCL可能会错误的加载未出现的xaml的控件

### ISSUE THREAD

**Issue by LTDove** [Hex-Dragon/PCL2#1622]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

测试主页文件时
刷新后 PCL出现了第9行，位置2上的开始标记"Menu"与结束标记“StackPanel“不匹配。第9行，位置9
问题是
在测试的主页文件中我没写入“StackPanel“
以下是源码
<Menu>
<MenuItem Header="114514">
</MenuItem>
<Menu>

### 重现步骤

不知道怎么重现
之前写主页时加载也会出现结束标记不匹配

### 日志与附件

网络问题 无法上传 有需要联系QQ：2487215845

**Comment by LTDove** [comment]
诶

    
<Menu>
<MenuItem Header="114514" >
</MenuItem>
<Menu>

**Comment by LTDove** [comment]
`不`
    
<Menu>
<MenuItem Header="114514" >
</MenuItem>
<Menu>
``

**Comment by LTDove** [comment]
```
<!-- 这是 PCL2 的主页自定义文件。你可以通过修改这个文件来自定义 PCL2 主页：添加文本、打开网页、启动游戏，等等。
     如果你倒腾这个文件把 PCL2 玩炸了，把这个文件直接删除就行了。
     如果你懂得 WPF 的布局文件编写，你甚至可以做出不少的新玩意儿…… -->
    
<Menu>
<MenuItem Header="114514" >
</MenuItem>
<Menu>

```

**Comment by LTDove** [comment]
就这样 没出现StackPanel

**Comment by iPodtouch6557** [comment]
我也不懂这玩意
但是我怀疑是不是**你或者pcl2**对代码的理解有误

**Comment by LTCatt** [comment]
![V JBNT2{ZK6U0 6M~ {RK{F](https://user-images.githubusercontent.com/40348278/230764668-8a36f2c6-af74-4062-838b-bd3d1118940a.png)
应为 /Menu 结尾

**Comment by iPodtouch6557** [comment]
果然是作者的问题
