### ISSUE TITLE
将反馈以及新功能投票加到百宝箱里

### ISSUE THREAD

**Issue by iPodtouch6557** [Hex-Dragon/PCL2#1623]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

把更多里的最下面两个与github相关的按钮移到百宝箱里，然后在一个mycard里塞下两个按钮
![image](https://user-images.githubusercontent.com/118656946/230763645-f0848c03-c2ef-447c-847f-a365dc64e483.png)

### 原因

这项优化可以使界面更清晰，整合性更强

**Comment by LTCatt** [comment]
它们是重要性更强的功能，不应放进百宝箱。
