### ISSUE TITLE
UI错误 - 加载动画没有在加载后隐藏

### ISSUE THREAD

**Issue by 212112111zwl** [Hex-Dragon/PCL2#1624]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

估计是那种没法复现但就是有几率碰到的bug……
![image](https://user-images.githubusercontent.com/121177845/230764463-5be812af-74b1-41cf-9da7-854dc56f6e4e.png)

### 重现步骤

我是搜了rad2整合，进去往下翻就看到了这个……

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11185110/Log1.txt)

**Comment by iPodtouch6557** [comment]
`[17:06:56.381] [Comp] 从 Modrinth 获取到了 0 个工程（已获取 0 个，共 0 个）
[17:06:56.864] [Comp] 从 CurseForge 获取到了 15 个工程（已获取 15 个，共 15 个）
[17:06:56.864] [Comp] 去重后累计新增结果 15 个
[17:06:56.864] [Comp] 总结果数需求最少 40 个，仅获得了 15 个
[17:06:56.864] [Comp] 无法继续加载，将强制结束
[17:06:56.886] [Comp] 开始可视化整合包列表，已储藏 15 个结果，当前在第 1 页`是这个问题吧

**Comment by LTCatt** [comment]
（不是强制结束的原因）
需要一个比较稳定的复现方法才能考虑修复……先挂着看看能不能找到办法吧 Orz

**Comment by iPodtouch6557** [comment]
录个成功复现的视频，在蓝奏云平台传一个视频下载，把链接发给我，~我github看不了视频~
或者直接放过来也行

**Comment by 212112111zwl** [comment]
> 录个成功复现的视频

又重新尝试在相同环境下复现bug，没成功……

**Comment by iPodtouch6557** [comment]
> > 录个成功复现的视频
> 
> 又重新尝试在相同环境下复现bug，没成功……
 
~多复现几次~是不是就是说不稳定，不必现

**Comment by LTCatt** [comment]
很头疼，挂了半个月了也没回复，没救。
就算复现了，也必须要开调试模式才能有页面加载动画相关的 Debug 信息……估计修复无望，先关了 =。=

**Comment by WForst-Breeze** [comment]
有人在 #3027 复现了，但可惜没开调试模式，需不需要把需要社区复现 Label 加回来？不然这个问题关键词不太好搜🤔

**Comment by JingHai-Lingyun** [comment]
加回来罢

**Comment by LTCatt** [comment]
加了 Tag，但还是同样的问题，得开调试模式复现 Orz

**Comment by kong-que-dnf123** [comment]
~草了怎么把动画速度拉到0.1X搜索都没有加载动画直接就加载出来了~

**Comment by JingHai-Lingyun** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/109946426/4a4f3170-3607-404f-bdfa-893ebe1448cb)
[调试模式 Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15351489/Log1.txt)

**Comment by WForst-Breeze** [comment]
那我先 Reopen 了？

**Comment by LTCatt** [comment]
log 里未见异常，还是需要一个稳定的触发方式。

备注：后续其他的重复 issue 都没有开调试模式，不过都是在 PageDownloadCompDetail 出的问题，难道不是 MyPageRight 的通用 bug？
