### ISSUE TITLE
PCL II 快照版2.5.3在更多中点击反馈显示不是最新版

### ISSUE THREAD

**Issue by OperatorRosmontis** [Hex-Dragon/PCL2#1625]
### 检查项

- [ ] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

更新PCL II 最新快照版2.5.3后，发现在更多中点击反馈显示不是最新版，然后点击检查更新发现也提示不是最新版，更新下载的也是2.5.3，我估↑计↓这↗是↘个→bug←！

### 重现步骤

1、点击更多
2、点击反馈

### 日志与附件

![Snipaste_2023-04-09_18-02-05](https://user-images.githubusercontent.com/61570274/230766531-5f4ca965-8abb-484c-a002-04b8da0ee75a.png)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11185181/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11185182/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11185183/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11185184/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11185185/Log5.txt)

**Comment by bwtx2023** [comment]
截图呢

**Comment by WForst-Breeze** [comment]
稳定复现（）
![image](https://user-images.githubusercontent.com/110760354/230767340-070d36d9-3c0e-4d71-af6c-2a4785443e67.png)

**Comment by Chiloven945** [comment]
嗯……
![image](https://user-images.githubusercontent.com/116699482/230767391-62886980-e438-4b06-9e49-8e967386020e.png)

**Comment by hellominecraftlauncher** [comment]
稳定复现，跟新了N次还是这样
![屏幕截图 2023-04-09 182707](https://user-images.githubusercontent.com/120797993/230767556-3e169ea7-1f61-44d2-9c50-24477bb941e1.png)

**Comment by LTCatt** [comment]
已重新发布 2.5.3，修复 #1625 和 #1626 
已更新 2.5.3 的话会再次自动更新，然后提示没有更新日志，这是正常的 =。=

**Comment by OperatorRosmontis** [comment]
B83E-5061-655B-6CE6

**Comment by LTCatt** [comment]
你的解锁码：PZ48sxtkRAdXEGYDoF0ZduH3S8eQEFUk
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by Nightingale0504** [comment]
90B2-41D4-A069-5B5E

**Comment by LTCatt** [comment]
你的解锁码：xOY1FKOkYgGDPum2tYGchZTyvBIFi3xV
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
