### ISSUE TITLE
在筛选来源（Modrinth 或 CurseForge）后无法正常搜索到部分资源

### ISSUE THREAD

**Issue by WForst-Breeze** [Hex-Dragon/PCL2#1626]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

请见此视频：

https://user-images.githubusercontent.com/110760354/230767634-bc0874c3-3223-4162-825a-46efc23fc165.mp4

以 Forgero 为例，当不筛选来源时，可以正常搜索到来自 MR 和 CF 的两个 Forgero Mod。而当选择来源后，却无法正常搜索到此 Mod

### 重现步骤

搜索部分 Mod（已知有问题的有 Forgero 双渠道均可复现、Beautified Chat Modrinth 可复现）并筛选来源，问题复现

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11185223/Log1.txt)

**Comment by LTCatt** [comment]
已重新发布 2.5.3，修复 #1625 和 #1626 
已更新 2.5.3 的话会再次自动更新，然后提示没有更新日志，这是正常的 =。=

**Comment by WForst-Breeze** [comment]
需要活跃橙解锁码 DD75-9A3B-887B-9C6B 谢谢orz！

**Comment by LTCatt** [comment]
识别码 DD75-9A3B-887B-9C6B 的土豆码是：【CD118HC4ke1xQ0KLVoe7ZeBDOduoqj5fwIOLeR9t4gSzgeqQUZcnH7jq3uZCObZAkC0cjE6I3AGyWoWoh58H2jI2Agpp#VGhlbWU5】
在【更多 → 关于与鸣谢 → 输入土豆码】中使用，谢谢支持～
