### ISSUE TITLE
启动器更新问题

### ISSUE THREAD

**Issue by hellominecraftlauncher** [Hex-Dragon/PCL2#1628]
### 检查项

- [ ] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [ ] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我介入我下一个人的issue再做详细描述，感觉像是下载更新服务器的文件有问题
更新后我打开了PCL文件夹，然后发现此文件夹在下载了PCL后凭手速复制出来后，下载的PCL缺还是没更新前的版本
请求龙猫检查一下服务器更新库文件是否是新更新的版本

### 重现步骤

1、点击设置——启动器
2、往下滚，然后点击检查更新

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11185224/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11185225/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11185226/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11185227/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11185228/Log5.txt)
[点击更新后的PCL.zip](https://github.com/Hex-Dragon/PCL2/files/11185234/PCL.zip)

**Comment by iPodtouch6557** [comment]
语病有点多……没看懂啊

**Comment by LTCatt** [comment]
与 #1625 实质性重复
