### ISSUE TITLE
异常启动

### ISSUE THREAD

**Issue by Bandysol** [Hex-Dragon/PCL2#1631]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在按重现步骤执行后，会出现一个一直无响应的游戏窗口。

PS：应该有运气成分，不是谁都能在窗口出现的10ms前按下取消的。

### 重现步骤

启动游戏，然后在一段时间后点取消

### 日志与附件

[19:09:44.701] [Launch] 已取消启动
[19:09:44.711] [Launch] 已启动游戏进程：C:\Program Files\Java\jre1.8.0_291\bin\javaw.exe

完整文件（在2319行）：[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11185693/Log3.txt)

**Comment by LTCatt** [comment]
……太难触发了，也不好修，算了………………

**Comment by Bandysol** [comment]
又来了
[11:54:27.715] [Launch] 已取消启动
[11:54:27.755] [Launch] 已启动游戏进程：C:\Program Files\Java\jre1.8.0_291\bin\javaw.exe
在803行：[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11292101/Log1.txt)
