### ISSUE TITLE
启动器更新问题，无法更新

### ISSUE THREAD

**Issue by anmicuis0rorschach** [Hex-Dragon/PCL2#1632]
### 检查项

- [ ] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

无法更新，显示安装安装更新失败，自动更新下载文件已损坏。
![截图](https://user-images.githubusercontent.com/130346343/230851271-a27b62be-5fa1-4cfa-b9fc-5a4251009161.png)

### 重现步骤

1、点击检查更新
2、输入更新密钥更新，进度条到一半就会触发

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11188611/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11188612/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11188613/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11188615/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11188616/Log5.txt)

**Comment by iPodtouch6557** [comment]
可以试一试把PCL2一切相关文件，注册表、基本文件，只要相关的都删掉（不建议）
我咋没这事

**Comment by LTCatt** [comment]
重新下载一个吧……
我也不清楚咋回事，但似乎只有你出了问题……

**Comment by Chiloven945** [comment]
嗯……上次重新更新的时候应该是自动更新就报错了，我重开PCL后点更新就没什么问题了（

**Comment by LTCatt** [comment]
有其他人可以稳定复现么？

**Comment by anmicuis0rorschach** [comment]
错误的，我版本很新，更新的问题找到了，不知道因为什么电脑把pcl2从白名单移出来了，我听龙猫的重新下了一次更新报毒又出现这种情况，移进白名单第二次恢复正常了
