### ISSUE TITLE
存在jdk20时 “自动选择合适的java”倾向使用jdk20启动1.19.2游戏并失败

### ISSUE THREAD

**Issue by Dave12138** [Hex-Dragon/PCL2#1635]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

当jdk8，open jdk19，open jdk20同时存在时
使用“自动选择合适的java”启动1.19.2的游戏会选择jdk20
然后不出意料地启动失败了
`[104月2023 23:18:44.848] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 20 by Oracle Corporation; OS Windows 10 arch amd64 version 10.0`
看起来需要更新一下
[latest.log](https://github.com/Hex-Dragon/PCL2/files/11191464/latest.log)

### 原因

如果自动选择合适的java选择了不合适的java，选择器的生涯就要结束了罢，只好发出很大的更新糊弄过去了（？

**Comment by Chiloven945** [comment]
建议安装一下17因为17是长期支持版本，我记得如果有17是会更倾向于选择17的

**Comment by Dave12138** [comment]
> 建议安装一下17因为17是长期支持版本不太容易出现问题，我记得如果有17是会更倾向于选择17的
这样的吗
我下载20的时候看见
JDK 17 has been superseded. Please visit [jdk.java.net](https://jdk.java.net/) for the current version.

Older releases, which do not include the most up to date security vulnerability fixes and are no longer recommended for use in production
就顺手把17删了
