### ISSUE TITLE
启动器更新失败：安装更新失败

### ISSUE THREAD

**Issue by YUANXINGlingyun** [Hex-Dragon/PCL2#1641]
### 检查项

- [ ] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://user-images.githubusercontent.com/109946426/231467487-05d8ff9f-7820-485e-b20a-01fe08193296.png)
如图
~~说是更新解决问题但是不让我更新啊~~ 

### 重现步骤

将启动器从 2.5.2 更新至 2.5.3 时触发

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11211744/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11211745/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11211746/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11211742/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11211743/Log5.txt)

**Comment by LTCatt** [comment]
不要在临时文件夹或者压缩包里运行 PCL

**Comment by YUANXINGlingyun** [comment]
哦，我懂了，是`尝试解压文件失败：文件“D:\Minecraft\MinecraftServer\Luncher\Plain Craft Luncher\PCL\Plain Craft Launcher 2.exe”已经存在。`的问题

那要不要考虑为这种情况制作一个优化，以提醒用户删除掉`.\PCL`中的`Plain Craft Luncher 2.exe`文件？
@LTCatt

**Comment by LTCatt** [comment]
![image](https://user-images.githubusercontent.com/40348278/231966376-7925ada0-19b7-4a05-a213-4a8003562d33.png)

什么鬼……

**Comment by z0z0r4** [comment]
我也遇到了这个…但重启启动器就能解决

**Comment by YUANXINGlingyun** [comment]
en 重启后就提示 update 2.5.3 好了

**Comment by iPodtouch6557** [comment]
~插句题外话，其实你文件夹里的 launcher 拼错了，拼的全是 luncher~
想请教一下为什么会有另一进程使用？

**Comment by LTCatt** [comment]
已尝试修复，之后再看好没好……

**Comment by YUANXINGlingyun** [comment]
行，之后升级时再看看
66BE-3538-653B-7022 给下码~

**Comment by LTCatt** [comment]
你的解锁码：XZ3uENj9U3Ng2whXhVmONtBwHlmx8IQg
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by LTCatt** [comment]
再发个 Log？

**Comment by iPodtouch6557** [comment]
这……一个bug还得再修一遍
而且我没有相关情况，直接更新的

**Comment by Chiloven945** [comment]
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11470971/Log5.txt)

**Comment by LTCatt** [comment]
@Chiloven945 你的 Bug 不是这个问题，而是因为在自动静默更新的过程中又手动更新了导致的，建议单开一个新 issue，附上你的那个 log

**Comment by LTCatt** [comment]
算了，修了，不用新开 issue 了 =。=

**Comment by JingHai-Lingyun** [comment]
@LTCatt 抱歉在这里打扰你
我重装了下系统，麻烦重给下码 
识别 EFF5-99DA-7296-A203

**Comment by LTCatt** [comment]
你的解锁码：nI2JIneHVN/BeAxmZi2f3yNyQ+NNwsNN
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
