### ISSUE TITLE
mod 收藏功能以及一键安装

### ISSUE THREAD

**Issue by xujie784442670** [Hex-Dragon/PCL2#1645]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

建议添加MOD收藏功能,并且收藏的mod可以进行分组,玩家在切换游戏版本时,可以一键下载一个或多个分组下对应当前游戏版本的mod,如果mod在当前版本下不存在,则提示出来

### 原因

每次在玩新版本时,总是需要一个个去搜索对应版本的mod,真的很繁琐

**Comment by Chiloven945** [comment]
#487 拒绝了收藏的功能
mod批量安装大概率也可能不会同意（
