### ISSUE TITLE
Java提示优化

### ISSUE THREAD

**Issue by Kc2353** [Hex-Dragon/PCL2#1650]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

![捕获0001](https://user-images.githubusercontent.com/130827856/232199125-8930214f-44fa-4d29-a29a-3e6c41480a7e.PNG)

我已移动了Java，导致无法检测到该Java，但是该信息具有误导性。

### 原因

======================================

建议将标题更改为"目标Java未检测到".

**Comment by LTCatt** [comment]
请作为 Bug 反馈重新提交，并上传 Log
