### ISSUE TITLE
MOD”iris Shaders“分类列表有误！

### ISSUE THREAD

**Issue by King-ming136121** [Hex-Dragon/PCL2#1652]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

1.19.2的iris Shaders误出现在最新正式版1.19.4版本中

### 重现步骤

打开启动器，依次点下载-Mod-搜索iris shaders，并找到该模组，选1.19.4版本即可

### 日志与附件

![image](https://user-images.githubusercontent.com/110441378/232206932-72640d37-c1d4-428a-9269-bbe2d486f353.png)
![image](https://user-images.githubusercontent.com/110441378/232207443-9ae658b2-ff84-45e5-bf87-92eb07f9790a.png)
![image](https://user-images.githubusercontent.com/110441378/232207471-9b7f6c02-3b64-4e57-9685-b29b7724ea97.png)

**Comment by YUANXINGlingyun** [comment]
![image](https://user-images.githubusercontent.com/109946426/232209319-9a49ed94-84cb-49f7-9acf-05de1aae98c1.png)
它支持 1.19.4

**Comment by hejiehao** [comment]
> ![image](https://user-images.githubusercontent.com/109946426/232209319-9a49ed94-84cb-49f7-9acf-05de1aae98c1.png)
> 它支持 1.19.4

可是这个文件只支持1.19.1和1.19.2
展开的是1.19.4但给的不是1.19.4的那个文件
这会让不知情的玩家误下载了个错误的版本导致mc崩溃

**Comment by YUANXINGlingyun** [comment]
e 那就是分类错误了
@LTCatt

**Comment by iPodtouch6557** [comment]
（类型选择错误，是其他bug……）
原网页甚至还没有1.19.3文件（指curseforge）
反馈情况属实，已确认，感谢反馈

**Comment by hejiehao** [comment]
> （类型选择错误，是其他bug……）
> 原网页甚至还没有1.19.3文件（指curseforge）
> 反馈情况属实，已确认，感谢反馈
> 

https://www.curseforge.com/minecraft/mc-mods/irisshaders/files/all?filter-game-version=2020709689%3A9550

**Comment by WForst-Breeze** [comment]
稳定复现，已初步确认问题存在，等待开发者处理，感谢您的反馈
btw，如无必要请不要@龙猫，我们都能看到你们的讨论的

**Comment by hellominecraftlauncher** [comment]
> > ![image](https://user-images.githubusercontent.com/109946426/232209319-9a49ed94-84cb-49f7-9acf-05de1aae98c1.png)
> > 它支持 1.19.4
> 
> 可是这个文件只支持1.19.1和1.19.2 展开的是1.19.4但给的不是1.19.4的那个文件 这会让不知情的玩家误下载了个错误的版本导致mc崩溃

hmcl的kook上面一堆因为这个崩溃的

**Comment by hejiehao** [comment]
> > > ![image](https://user-images.githubusercontent.com/109946426/232209319-9a49ed94-84cb-49f7-9acf-05de1aae98c1.png)
> > > 它支持 1.19.4
> > 
> > 可是这个文件只支持1.19.1和1.19.2 展开的是1.19.4但给的不是1.19.4的那个文件 这会让不知情的玩家误下载了个错误的版本导致mc崩溃
> 
> hmcl的kook上面一堆因为这个崩溃的

劝你们装mod先看看mod描述写了什么以及看supported version

**Comment by hellominecraftlauncher** [comment]
> > > > ![image](https://user-images.githubusercontent.com/109946426/232209319-9a49ed94-84cb-49f7-9acf-05de1aae98c1.png)
> > > > 它支持 1.19.4
> > > 
> > > 
> > > 可是这个文件只支持1.19.1和1.19.2 展开的是1.19.4但给的不是1.19.4的那个文件 这会让不知情的玩家误下载了个错误的版本导致mc崩溃
> > 
> > 
> > hmcl的kook上面一堆因为这个崩溃的
> 
> 劝你们装mod先看看mod描述写了什么以及看supported version

没事，以前HMCL也这样过，估计是启动器获取的版本问题，又或者百科出了问题

**Comment by King-ming136121** [comment]
> 稳定复现，已初步确认问题存在，等待开发者处理，感谢您的反馈 btw，如无必要请不要@龙猫，我们都能看到你们的讨论的



> > > > > ![image](https://user-images.githubusercontent.com/109946426/232209319-9a49ed94-84cb-49f7-9acf-05de1aae98c1.png)
> > > > > 它支持 1.19.4
> > > > 
> > > > 
> > > > 可是这个文件只支持1.19.1和1.19.2 展开的是1.19.4但给的不是1.19.4的那个文件 这会让不知情的玩家误下载了个错误的版本导致mc崩溃
> > > 
> > > 
> > > hmcl的kook上面一堆因为这个崩溃的
> > 
> > 
> > 劝你们装mod先看看mod描述写了什么以及看supported version
> 
> 没事，以前HMCL也这样过，估计是启动器获取的版本问题，又或者百科出了问题

好吧！

**Comment by King-ming136121** [comment]
> > > > > ![image](https://user-images.githubusercontent.com/109946426/232209319-9a49ed94-84cb-49f7-9acf-05de1aae98c1.png)
> > > > > 它支持 1.19.4
> > > > 
> > > > 
> > > > 可是这个文件只支持1.19.1和1.19.2 展开的是1.19.4但给的不是1.19.4的那个文件 这会让不知情的玩家误下载了个错误的版本导致mc崩溃
> > > 
> > > 
> > > hmcl的kook上面一堆因为这个崩溃的
> > 
> > 
> > 劝你们装mod先看看mod描述写了什么以及看supported version
> 
> 没事，以前HMCL也这样过，估计是启动器获取的版本问题，又或者百科出了问题

现在HMCL下载这个mod时也出现这个问题......Bakaxl不知道有没有......

**Comment by King-ming136121** [comment]
> > > > > ![image](https://user-images.githubusercontent.com/109946426/232209319-9a49ed94-84cb-49f7-9acf-05de1aae98c1.png)
> > > > > 它支持 1.19.4
> > > > 
> > > > 
> > > > 可是这个文件只支持1.19.1和1.19.2 展开的是1.19.4但给的不是1.19.4的那个文件 这会让不知情的玩家误下载了个错误的版本导致mc崩溃
> > > 
> > > 
> > > hmcl的kook上面一堆因为这个崩溃的
> > 
> > 
> > 劝你们装mod先看看mod描述写了什么以及看supported version
> 
> 没事，以前HMCL也这样过，估计是启动器获取的版本问题，又或者百科出了问题

现在问题已经被龙猫看见，就等处理了

**Comment by hellominecraftlauncher** [comment]
> > > > > > ![image](https://user-images.githubusercontent.com/109946426/232209319-9a49ed94-84cb-49f7-9acf-05de1aae98c1.png)
> > > > > > 它支持 1.19.4
> > > > > 
> > > > > 
> > > > > 可是这个文件只支持1.19.1和1.19.2 展开的是1.19.4但给的不是1.19.4的那个文件 这会让不知情的玩家误下载了个错误的版本导致mc崩溃
> > > > 
> > > > 
> > > > hmcl的kook上面一堆因为这个崩溃的
> > > 
> > > 
> > > 劝你们装mod先看看mod描述写了什么以及看supported version
> > 
> > 
> > 没事，以前HMCL也这样过，估计是启动器获取的版本问题，又或者百科出了问题
> 
> 现在HMCL下载这个mod时也出现这个问题......Bakaxl不知道有没有......

预览版HMCL还是测试版HMCL

**Comment by King-ming136121** [comment]
> > > > > > > ![image](https://user-images.githubusercontent.com/109946426/232209319-9a49ed94-84cb-49f7-9acf-05de1aae98c1.png)
> > > > > > > 它支持 1.19.4
> > > > > > 
> > > > > > 
> > > > > > 可是这个文件只支持1.19.1和1.19.2 展开的是1.19.4但给的不是1.19.4的那个文件 这会让不知情的玩家误下载了个错误的版本导致mc崩溃
> > > > > 
> > > > > 
> > > > > hmcl的kook上面一堆因为这个崩溃的
> > > > 
> > > > 
> > > > 劝你们装mod先看看mod描述写了什么以及看supported version
> > > 
> > > 
> > > 没事，以前HMCL也这样过，估计是启动器获取的版本问题，又或者百科出了问题
> > 
> > 
> > 现在HMCL下载这个mod时也出现这个问题......Bakaxl不知道有没有......
> 
> 预览版HMCL还是测试版HMCL

测试版3.5.3.230

**Comment by King-ming136121** [comment]
> > > > > > > > ![image](https://user-images.githubusercontent.com/109946426/232209319-9a49ed94-84cb-49f7-9acf-05de1aae98c1.png)
> > > > > > > > 它支持 1.19.4
> > > > > > > 
> > > > > > > 
> > > > > > > 可是这个文件只支持1.19.1和1.19.2 展开的是1.19.4但给的不是1.19.4的那个文件 这会让不知情的玩家误下载了个错误的版本导致mc崩溃
> > > > > > 
> > > > > > 
> > > > > > hmcl的kook上面一堆因为这个崩溃的
> > > > > 
> > > > > 
> > > > > 劝你们装mod先看看mod描述写了什么以及看supported version
> > > > 
> > > > 
> > > > 没事，以前HMCL也这样过，估计是启动器获取的版本问题，又或者百科出了问题
> > > 
> > > 
> > > 现在HMCL下载这个mod时也出现这个问题......Bakaxl不知道有没有......
> > 
> > 
> > 预览版HMCL还是测试版HMCL
> 
> 测试版3.5.3.230

**Comment by hellominecraftlauncher** [comment]
> > > > > > > > ![image](https://user-images.githubusercontent.com/109946426/232209319-9a49ed94-84cb-49f7-9acf-05de1aae98c1.png)
> > > > > > > > 它支持 1.19.4
> > > > > > > 
> > > > > > > 
> > > > > > > 可是这个文件只支持1.19.1和1.19.2 展开的是1.19.4但给的不是1.19.4的那个文件 这会让不知情的玩家误下载了个错误的版本导致mc崩溃
> > > > > > 
> > > > > > 
> > > > > > hmcl的kook上面一堆因为这个崩溃的
> > > > > 
> > > > > 
> > > > > 劝你们装mod先看看mod描述写了什么以及看supported version
> > > > 
> > > > 
> > > > 没事，以前HMCL也这样过，估计是启动器获取的版本问题，又或者百科出了问题
> > > 
> > > 
> > > 现在HMCL下载这个mod时也出现这个问题......Bakaxl不知道有没有......
> > 
> > 
> > 预览版HMCL还是测试版HMCL
> 
> 测试版3.5.3.230
[HMCL.zip](https://github.com/Hex-Dragon/PCL2/files/11239629/HMCL.zip)
预览版试试

**Comment by WForst-Breeze** [comment]
请注意：请善用 Edit 功能，如此反馈动态过多，会被锁定

**Comment by King-ming136121** [comment]
> 请注意：请善用 Edit 功能，如此反馈动态过多，会被锁定

问题已经在PCL2上不会复现，可关闭或忽略luess
![image](https://user-images.githubusercontent.com/110441378/232227723-afc9fad8-578c-4cf7-91ca-d72166e8e630.png)

**Comment by iPodtouch6557** [comment]
我到现在还有一个1.19.2和1.19.4

**Comment by LTCatt** [comment]
推测作者设置有误或 API 问题，如果目前部分人是正常的那九成是 API 问题了，那就忽略了吧……

**Comment by sssohp** [comment]
现在NeoForge1.21.3中又出现了一样的问题

<img width="1389" height="932" alt="Image" src="https://github.com/user-attachments/assets/e2019a0e-96d3-4d3d-aeba-ad377d8c04f2" />
