### ISSUE TITLE
增加透明背景

### ISSUE THREAD

**Issue by misividkoukou** [Hex-Dragon/PCL2#1653]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

透明背景以至于可以更大程度的看到背景图片....

### 原因

（示例）
我需要这个功能来看到背景图片。很多人都有看到背景图片的需求，但如果没有这个功能，就不能看到更多的背景图片了。
（doge

**Comment by misividkoukou** [comment]
这里的透明背景指的是白色方框（文本的背景）

**Comment by iPodtouch6557** [comment]
1.没听懂
2.对内容初步理解的回复是：可以设置不透明选项，勉强能用吧

**Comment by Chormore-EDGE** [comment]
这不就和 #131 以及类似问题一样吗

**Comment by WForst-Breeze** [comment]
已初步确认，请等待开发者进一步考虑，感谢您的反馈
（备注：反馈者意为允许设置侧边栏以及 MyCard 为透明色，仅显示图标及文字

**Comment by LTCatt** [comment]
由于目前 MyCard 卡片阴影的实现原理是在背后叠加一个灰色层，提高卡片透明度会让卡片变灰，所以不好实现 :(

**Comment by 212112111zwl** [comment]
那同时提高灰色层的透明度？

**Comment by iPodtouch6557** [comment]
其实吧……会造成其他的问题，还是少麻烦的好
