### ISSUE TITLE
主页使用关闭按钮关闭游戏，jar无法删除正在被使用

### ISSUE THREAD

**Issue by hellominecraftlauncher** [Hex-Dragon/PCL2#1655]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我启动一次后，突然想修改东西，但是
我点击PCL的删除，系统弹出该文件正在被使用
![屏幕截图 2023-04-15 195701](https://user-images.githubusercontent.com/120797993/232218893-1a55cf6f-701d-43d7-8413-15c1f36182b0.png)
可能是进程存在后台，但不知道为什么点了关闭按钮这个jar还在被使用（我确定任务栏没显示mc进程，仅在任务管理器找到javaw.exe）

### 重现步骤

1、启动一个游戏，推荐加载慢的
2、启动到第二阶段到第三阶段或者更往后，点PCL的关闭按钮
3、找到mod管理，随便删除一个mod，弹出文件正在被使用

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11239311/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11239313/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11239314/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11239315/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11239316/Log5.txt)

**Comment by Chormore-EDGE** [comment]
这个bug不好评价，~~主要 #1094 已经做完了~~，是不是Java或者你单纯电脑不好

**Comment by hellominecraftlauncher** [comment]
> 这个bug不好评价，~主要 #1094 已经做完了~，是不是Java或者你单纯电脑不好

换了个Java一样，要不看看日志用的Java是不是和你一个？

**Comment by hellominecraftlauncher** [comment]
> 这个bug不好评价，~主要 #1094 已经做完了~，是不是Java或者你单纯电脑不好

我的游戏Java（G：/Java/Java8/bin/javaw.exe）启动路径和你不一样

**Comment by Chormore-EDGE** [comment]
不了解了，我没这个问题

**Comment by WForst-Breeze** [comment]
您可以等待片刻后再次尝试，看看还有没有此问题？

**Comment by LTCatt** [comment]
文件被其他程序占用，并非是启动器导致的。
