### ISSUE TITLE
1.7.10自定义皮肤出错

### ISSUE THREAD

**Issue by gaojin20090517** [Hex-Dragon/PCL2#1656]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

1.7.10自定义皮肤出错

### 重现步骤

自定义皮肤
打开1.7.10
皮肤出错

### 日志与附件

皮肤
![惊讶史蒂夫](https://user-images.githubusercontent.com/125573915/232232235-1084c828-883d-4a8a-9ba7-f839f3ec4300.png)

已添加
![image](https://user-images.githubusercontent.com/125573915/232232017-5dee3b8f-2c97-48ad-861f-ec86ac81a19d.png)

游戏截图
![image](https://user-images.githubusercontent.com/125573915/232232309-3dc51fb6-8cf4-4466-b05f-d7448937e875.png)
![image](https://user-images.githubusercontent.com/125573915/232232311-824faafe-a4c3-4c39-b488-521d7cd1b318.png)
![image](https://user-images.githubusercontent.com/125573915/232232351-d235e185-2ea1-480a-af90-31193f56feab.png)

日志
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11239808/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11239809/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11239805/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11239806/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11239807/Log5.txt)

**Comment by iPodtouch6557** [comment]
啊这没法看了
测试一下那些版本会出这些问题？如果最高到1.8的话，那就应该是mojang皮肤算法更改的事情了
~还有您不睡觉吗（虽然我为了一个破ppt也在熬夜）~

**Comment by youzi-2333** [comment]
额，Mojang 似乎在 1.8 和 1.13 都改了一下皮肤，所以渲染不了……
要不让 PCL 自动编辑一遍皮肤，那这样就是个新功能（？）

**Comment by gaojin20090517** [comment]
是的，分开导入皮肤资源包














在 2023-04-16 00:08:42，"柚子柚子" ***@***.***> 写道：

额，Mojang 似乎在 1.8 和 1.13 都改了一下皮肤，所以渲染不了……
要不让 PCL 自动编辑一遍皮肤，那这样就是个新功能（？）

**Comment by LTCatt** [comment]
![image](https://user-images.githubusercontent.com/40348278/233797273-e99fc7b9-4a85-4063-9e74-2fd877c450b7.png)

已修复。
