### ISSUE TITLE
打开日志文件目录日常

### ISSUE THREAD

**Issue by hellominecraftlauncher** [Hex-Dragon/PCL2#1657]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

游戏崩溃后，他打开了PCL缓存的一个日志，而不是游戏崩溃的日志

### 重现步骤

1、启动游戏
2、游戏崩溃
3、查看日志

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11239872/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11239873/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11239874/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11239875/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11239876/Log5.txt)

**Comment by iPodtouch6557** [comment]
没懂啊，是：打开的不是crashlog，而是pcl2自己的文件 吗

**Comment by hellominecraftlauncher** [comment]
> 没懂啊，是：打开的不是crashlog，而是pcl2自己的文件 吗

打开了PCL2的html缓存日志并非crash.log或者laste.log

**Comment by iPodtouch6557** [comment]
> > 没懂啊，是：打开的不是crashlog，而是pcl2自己的文件 吗
> 
> 打开了PCL2的html缓存日志并非crash.log或者laste.log

请问应该打开啥呢

**Comment by hellominecraftlauncher** [comment]
> > > 没懂啊，是：打开的不是crashlog，而是pcl2自己的文件 吗
> > 
> > 
> > 打开了PCL2的html缓存日志并非crash.log或者laste.log
> 
> 请问应该打开啥呢（就只是问一下别误会）

装了模组是crash.txt
没装模组是laste.exe
（请勿一直回复，容易类似被归档处理）

**Comment by iPodtouch6557** [comment]
看来这确实是个bug……

**Comment by LTCatt** [comment]
游戏如果自己没有生成崩溃报告，就会打开最相关的一个日志文件，WAI。
