### ISSUE TITLE
引进新的mod/整合包下载源

### ISSUE THREAD

**Issue by zhang5249130** [Hex-Dragon/PCL2#1658]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

引进国内的模组/整合包下载源，以提升下载速度

### 原因

部分地区因网络延迟问题，使用curseForge下载源加载不出模组/整合包列表，或是下载时速度太慢
国内还有挺多下载源的，希望往后能引进

**Comment by zhang5249130** [comment]
补充：虽然新版引进了Modrinth，但是速度仍不理想

**Comment by YUANXINGlingyun** [comment]
~~我不太理解，国内 CF 的加载速度还是很好的（倒是 MR 会慢一点）~~
已初步确认，感谢您的反馈

**Comment by Big-Cake-jpg** [comment]
> ~我不太理解，国内 CF 的加载速度还是很好的（倒是 MR 会慢一点）~ 如果仅仅是部分地区的话，可能不太会制作对部分地区的优化 已初步确认，感谢您的反馈

太原电信实测 MR 比 CF 快，而且网站体验也更好，CF 在我电脑上加载时会显得很卡。

**Comment by Chiloven945** [comment]
关键是国内的资源网站并没有提供API，所以说这个东西也不太好说
但是我下载还是蛮快的虽然CF有时候会突然卡着（

**Comment by LTCatt** [comment]
没有其他可用的国内的 API
