### ISSUE TITLE
疑似音乐播放功能占用大量内存导致崩溃

### ISSUE THREAD

**Issue by MJIFmc** [Hex-Dragon/PCL2#1659]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11241089/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11241090/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11241091/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11241092/Log1.txt)

### 重现步骤

1、打开PCL2的音乐播放,内存占用率会越来越高
2、过一段时间内存占用超过4G,出现"锟斤拷烫烫烫"错误,内存不足

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11241088/Log2.txt)

**Comment by MJIFmc** [comment]
![image](https://user-images.githubusercontent.com/110874026/232272075-6cbbbdf6-d2ab-4ba4-8c98-c46c5ac3a95b.png)

**Comment by LTCatt** [comment]
传一下你放的是啥音乐？

**Comment by youzi-2333** [comment]
```
[09:41:12.855] [Music] 播放开始：C:\Users\MJIF\Desktop\PCL\Musics\卡农原版.mp3
[09:46:09.089] [Music] 播放开始：C:\Users\MJIF\Desktop\PCL\Musics\卡农原版.mp3
[09:51:05.317] [Music] 播放开始：C:\Users\MJIF\Desktop\PCL\Musics\卡农原版.mp3
[09:56:01.515] [Music] 播放开始：C:\Users\MJIF\Desktop\PCL\Musics\卡农原版.mp3
[10:00:57.765] [Music] 播放开始：C:\Users\MJIF\Desktop\PCL\Musics\卡农原版.mp3
```
由此得知音乐时长约 4 分 57 秒（？）
*（内心：又不是 4 小时 57 分钟，内存占用不会太高吧）*

**Comment by iPodtouch6557** [comment]
一般是设备问题，~因为我昨天晚上做PPT做了三个半小时，全程都在放音乐，都没崩~

**Comment by MJIFmc** [comment]
> 一般是设备问题，~因为我昨天晚上做PPT做了三个半小时，全程都在放音乐，都没崩~

我16G的内存给它占满(

**Comment by MJIFmc** [comment]
> 传一下你放的是啥音乐？

[卡农原版.zip](https://github.com/Hex-Dragon/PCL2/files/11260627/default.zip)

**Comment by LTCatt** [comment]
无法复现，循环播放了半个小时内存占用没有任何增加……
