### ISSUE TITLE
导出启动脚本里的--accessToken是XXXXX正常启动没问题

### ISSUE THREAD

**Issue by maolingfeng1** [Hex-Dragon/PCL2#1661]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

导出启动脚本里的--access
Token是XXXXX，uuid也没问题，
![image](https://user-images.githubusercontent.com/121140962/232272575-c8631073-0b01-4a6a-907a-53dc48224c60.png)
正常启动没问题
我觉得并不是网络问题，因为我正常启动都可以

### 重现步骤

1，选择游戏版本
2，导出启动脚本
3，打开游戏
4，尝试登录hypixel提示无正版验证

### 日志与附件

[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11241289/Log5.txt)

**Comment by iPodtouch6557** [comment]
token本来就被故意设为了XXXXX吧……
反而是没有XXX不对

**Comment by maolingfeng1** [comment]
> token本来就被故意设为了XXXXX吧…… 反而是没有XXX不对

不对啊，token登录是要明文的，不像是开发者模式里显示的token是自动隐藏的

**Comment by maolingfeng1** [comment]
> > token本来就被故意设为了XXXXX吧…… 反而是没有XXX不对
> 
> 不对啊，token登录是要明文的，不像是开发者模式里显示的token是自动隐藏的

所以导出的token必须是明文，但是我导出来的是eyxxxxxxxx什么的，所以是有问题的，我uuid都是对的，就只是登录所需要的token是xxx

**Comment by LTCatt** [comment]
启动脚本出于安全考虑刻意删除了登录凭证，无法正版登录 :(
