### ISSUE TITLE
Minecraft 尚未加载完成，可能已崩溃

### ISSUE THREAD

**Issue by admin64github** [Hex-Dragon/PCL2#1662]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃不是 PCL2 的原因，请 **不要** 提交反馈。你可以在 QQ 群里或者论坛找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是游戏本身的问题，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

Minecraft 尚未加载完成
log1的第200行左右

### 错误报告、日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11241345/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11241347/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11241348/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11241349/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11241350/Log5.txt)

**Comment by YUANXINGlingyun** [comment]
`[13:40:42.352] [Start] 程序版本：Snapshot 2.5.2（285）`
更新到最新版（2.5.3）还会有这个问题嘛

**Comment by iPodtouch6557** [comment]
都没更新版本不要反馈qwq
请升级后确认bug是否存在

**Comment by LTCatt** [comment]
如果其他启动器可以正常启动，请上传其他启动器的启动脚本……
![652ea70f2536640170677af9905403bc_231967306-96716ad5-3854-4005-9d8f-e425cd726c80](https://user-images.githubusercontent.com/40348278/232286595-447a4c1b-f651-4d65-ab34-7f620d0d2742.png)

**Comment by YUANXINGlingyun** [comment]
此反馈已经一周了，请及时补充信息以避免反馈超时关闭
@admin64github

**Comment by LTCatt** [comment]
超时关闭，如果有需要可以继续回复 :(
