### ISSUE TITLE
添加一个模组创作栏目，让模组创作者在PCL上发布模组

### ISSUE THREAD

**Issue by wuzhi718** [Hex-Dragon/PCL2#1665]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [ ] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

如果可以的话我觉得这是一个挺重要的点，可以让模组制作者在上面发布模组并获取收益，可以让更多人愿意留在PCL而不是网易（我个人的看法，勿喷）

### 原因

驱动壮大不能只靠喜欢，也需要商业模式，如果能让大家在上面消费并支持喜欢的创作者可以让他们持续产出优质内容，我觉得这是网易在做的，（这也只是我的设想，勿喷）大多数人都嫌麻烦，不会愿意去下载这下载那的，未来越来越多的人可能会流到那边，再加上我们这边一些各种各样的问题，能够聚集大多数玩家的，联机方便的，我感觉才能长远

**Comment by iPodtouch6557** [comment]
龙猫很忙，这个功能太过宏大，你还要他搞个模组网站他不得24h以闪电侠般的速度敲代码才忙的过来
同时pcl是搞minecraft的，不是搞商业的，这严重超出范畴了
而且印象中有人反馈过类似的……但是具体上有点不同

**Comment by YUANXINGlingyun** [comment]
龙猫说过：
不会使用云端类的功能，因为无法抵御攻击（详见 #340）
还有不会制作这种云平台（详见 #1047）

**Comment by wuzhi718** [comment]
确实，这不是一个人能搞的

**Comment by Chiloven945** [comment]
PCL是启动器不是资源分享平台（
