### ISSUE TITLE
在1.19.4中，游戏崩溃后无法显示有问题的mod

### ISSUE THREAD

**Issue by tcybsw** [Hex-Dragon/PCL2#1666]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃不是 PCL2 的原因，请 **不要** 提交反馈
- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是游戏本身的问题，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在1.19.4-Fabric 0.14.18-OptFine_I3中，游戏崩溃后无法显示有问题的mod，自己估计是启动器与Carpet模组有问题，但是同一模组在HMCL启动器上却没有任何问题

### 错误报告、日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11241991/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11241992/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11241993/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11241994/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11241995/Log5.txt)

**Comment by tcybsw** [comment]
谢谢大佬

**Comment by tcybsw** [comment]
注：“同一模组”是指我直接把模组文件转移到HMCL启动器上，谢谢

**Comment by hejiehao** [comment]
optifabric与Carpet冲突

**Comment by hejiehao** [comment]
不会说你在HMCL上没装fabric吧

**Comment by WForst-Breeze** [comment]
```
 Mixin apply for mod optifabric failed optifabric.compat.carpet.extra-new-mixins.json:LevelRendererExtraMixin from mod optifabric -> net.minecraft.class_761: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure
```
此次崩溃原因为 Carpet Extra 模组与 Optifabric 冲突，与启动器无关，我不清楚您在 HMCL 中尝试启动时是否安装了这两个模组，因为理论上无论在哪个起动器上启动都会崩溃

**Comment by Chiloven945** [comment]
![image](https://user-images.githubusercontent.com/116699482/232315050-b922a8b1-0bf7-48a3-9fc4-28708b1b6186.png)
如果需要光影功能的话可以尝试使用Sodium加上Iris Shader

**Comment by LTCatt** [comment]
请上传完整的错误报告文件，以便添加相关错误的自动识别 :)

**Comment by tcybsw** [comment]
抱歉，我在其他启动器上没加OptFine，我的问题，主要是没有显示有问题的mod，我实在是不是很懂
[错误报告-2023-4-17_9.54.28.zip](https://github.com/Hex-Dragon/PCL2/files/11245465/-2023-4-17_9.54.28.zip)

**Comment by WorldHim** [comment]
作者原意：PCL的模组冲突分析不显示有问题的模组，~~并且在其他启动器上可以启动~~（此处作者已确认非PCL问题）。
