### ISSUE TITLE
[Bug] 提示框二次弹出时颜色的问题

### ISSUE THREAD

**Issue by youzi-2333** [Hex-Dragon/PCL2#1667]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在 `Release 2.5.2` 中，让同一个提示弹出两次，此时第二次提示会左右摇晃，但在摇晃时会从“白色”逐渐转向“其应有颜色”。
如果是刻意的设计就关了吧……

https://user-images.githubusercontent.com/106497113/232309499-42eab581-4787-4e24-b667-977801794f1d.mp4

### 重现步骤

1. **在 Release 版本中**打开 `设置 -> 启动器`；往下滚，点击两次“输入解锁码”（这一步是为了搞出左下角提示）
2. 发现错误

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11242251/Log1.txt)

**Comment by WForst-Breeze** [comment]
应该是刻意的设计，看看龙猫怎么说吧，感谢您的反馈

**Comment by Chiloven945** [comment]
看起来像是在提醒你点的这个东西就是这个提示的亚子（

**Comment by youzi-2333** [comment]
> 看起来像是在提醒你点的这个东西就是这个提示的亚子（

不是已经有左右摇晃了吗……这玩意怎么看都像是个 Bug……

**Comment by Chiloven945** [comment]
> > 看起来像是在提醒你点的这个东西就是这个提示的亚子（
> 
> 不是已经有左右摇晃了吗……这玩意怎么看都像是个 Bug……

提示出现的时候往左了一次，出现同样的之后可能为了提醒你所以说往左了两次吧……

**Comment by LTCatt** [comment]
是刻意的设计（
