### ISSUE TITLE
[Bug] 在安装 Mod 加载器的版本设置中可以点出“不可使用 Mod”

### ISSUE THREAD

**Issue by youzi-2333** [Hex-Dragon/PCL2#1668]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在安装 Mod 加载器的版本中，打开版本设置，在**选中“设置”页面的情况下**点击“Mod 管理”的下面一点，有可能点到“该版本不可使用 Mod”

https://user-images.githubusercontent.com/106497113/232310376-d03bc87f-5f6c-4b12-ab67-3a6c7cb8d22f.mp4

### 重现步骤

1. 找到一个装了 Forge 或 Fabric 的版本；
2. 点击“版本设置”；
3. 选中“设置”；
4. 点击“Mod 管理”的下面；
5. 出现错误。

### 日志与附件

没必要了吧……
而且 Log 里面含有服务器 QQ 群号啥的，怕被说成是广告 qnq

**Comment by WForst-Breeze** [comment]
稳……稳定复现，感谢您的反馈，这又是什么神奇bug…… o_O
![image](https://user-images.githubusercontent.com/110760354/232312497-d3ce08cc-2678-4df2-a832-0f22a38332b1.png)

**Comment by youzi-2333** [comment]
~~我在修客户端 Bug 的时候瞎点一通点出来的……~~
这应该是做两个不同情况的 UI、但又没有做到同一张布局里面（~~也就是偷懒了~~）导致的，把其中一个情况隐藏了，但是仍然产生了几个像素的可以点的区域（吧）

**Comment by Chiloven945** [comment]
有很大的印象很久之前触发过（

**Comment by youzi-2333** [comment]
umm 现在要一个活跃橙还来得及吗（）
`D820-7953-A438-7E66`

**Comment by LTCatt** [comment]
你的解锁码：SKotjnkXd8tT4eQJbnBib2va39c7mV9n
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
