### ISSUE TITLE
[新功能] 对符合一定条件的版本，直接将其归类到“愚人节版本”

### ISSUE THREAD

**Issue by youzi-2333** [Hex-Dragon/PCL2#1669]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

如题，将 4 月 1 日发布的、不符合常规版本命名规则（在下面有解释）的快照版自动归为愚人节版本。迄今为止还没有 4 月 1 日更新的正常快照版，因此版本命名规则仅为保险起见。

常规命名规则大致是这样：
| 正则 | 示例 | 备注 |
| --- | --- | --- |
| `^\d{2}w\d{2}\w$` | 13w16a | 形如 22w13oneblockatatime 的版本不会被识别 |
| `^1\.\d+(\.\d+)?-pre\d{1,2}$` | 1.12.2-pre6 | pre 后面最多跟 2 位版本号 |
| `^1\.\d+(\.\d+)?-rc\d{1,2}$` | 1.16.2-rc1 | rc 后面最多跟 2 位版本号 |
| `^1\.\d+(\.\d+)?\sPre-Release\s\d{1,2}$` | 1.14 Pre-Release 5 | Pre-Release 后面最多跟 2 位版本号 |

除此之外，应该只有 Combat Test 以及 1.0.0-rc2-2 不会被正则搜索到……

### 原因

这个功能能够自动归类愚人节版本，否则必须要每年手动更新一次（已经连续两年了……）

**Comment by Chiloven945** [comment]
这个就怕Mojang不按套路出牌了，比如说又搞一个新的版本类型什么的（

**Comment by LTCatt** [comment]
目前手动添加即可，做这个花的时间都够我手动添加到 MC 凉凉了 =。=
