### ISSUE TITLE
版本安装完成后提示动画缺失

### ISSUE THREAD

**Issue by Chiloven945** [Hex-Dragon/PCL2#1670]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在完成版本安装后跳出的提示没有淡入动画

https://user-images.githubusercontent.com/116699482/232315558-327c7a81-9d6d-4874-99f6-cf6a4b55421d.mp4

### 重现步骤

安装任意版本

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11242415/Log1.txt)

**Comment by LTCatt** [comment]
因为那时候在处理文件，大概率会卡一下，把动画的时间卡掉了……没啥办法，真不好修……

**Comment by Chiloven945** [comment]
的确，好像就是处理很多文件的时候例如移动到回收站也会卡（
