### ISSUE TITLE
启动前执行命令问题

### ISSUE THREAD

**Issue by QianQiuawa** [Hex-Dragon/PCL2#1674]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

高级启动设置里的启动前执行命令执行Seversync（自动同步mod）会出现无法使用的问题 会使其在pcl所在目录重新创建sync的文件夹 但是只有在.minecraft目录下运行才会进行覆盖旧的mod等文件夹  目前mcmod上并无关于pcl2的解决办法 只能使用hmcl进行完成此项操作 望采纳

### 原因

这个功能可以使腐竹在不让玩家反复下载新的客户端的前提下 更新mod列表和config等文件 因为现在的pcl无法实现 以至于pcl2不能成为一些服务器客户端的启动器

**Comment by youzi-2333** [comment]
没太看懂，ServerSync 不是 Minecraft Mod 吗，您那边怎么运行的（）
顺便传个 Log……

**Comment by sleep80** [comment]
> 没太看懂，ServerSync 不是 Minecraft Mod 吗，您那边怎么运行的（） 顺便传个 Log……

换个label罢

**Comment by QianQiuawa** [comment]
不是的 这个按理说不算是一个mod 它是需要在启动游戏前运行一次来同步mod 如图是mcmod中的一个教程 如果在pcl中启动前输入此命令没有任何用处......这句命令是让启动器在启动前运行.minecraft中的serversync.jar来同步mod 同步后再进行启动 我当时有使用pcl2运行过（在启动时加上了jar的路径） 但是会在pcl2的同目录进行运行 这样根本达不到同步mod的目的.....






1463162438
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Hex-Dragon/PCL2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月18日(星期二) 晚上10:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Hex-Dragon/PCL2] 启动前执行命令问题 (Issue #1674)





  
没太看懂，ServerSync 不是 Minecraft Mod 吗，您那边怎么运行的（） 顺便传个 Log……
  
换个label罢

**Comment by youzi-2333** [comment]
首先可以尝试楼上说的，使用相对路径看看行不行，具体语法如下
![image](https://user-images.githubusercontent.com/106497113/232967675-25ad303d-37c8-470f-8eb6-b42cd2191e4a.png)

如果还不行的话，把可执行文件（`.exe` 或 `.bat`）传一下，我怀疑是这个程序的问题……

**Comment by LTCatt** [comment]
已修复

**Comment by LTCatt** [comment]
已修复

**Comment by QianQiuawa** [comment]
这....我前两天没看见发的邮件......我现在还要再提供相关文件吗

活跃橙主题qwq:0DA2-2317-19F9-1470

**Comment by LTCatt** [comment]
已经修好了 =。=

你的解锁码：3CWSxgurq80PWNzW3/xDYUeRsIPUQScd
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
