### ISSUE TITLE
改进已经添加微软账号后登录失败的弹窗内容

### ISSUE THREAD

**Issue by sleep80** [Hex-Dragon/PCL2#1675]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

如果我已经添加成功了微软账号，那表示登陆时我是有minecraft正版的。但是如果过了一些天我在打开pcl启动器，但是此时可能因为一些原因（比如我的Xbox game pass已经过期，或者账号被盗）登录失败，然而此时pcl还是会提示添加微软账号时的错误提示:“你可能没有购买minecraft或者你没有在官网创建档案”。我建议改成“你可能没有购买minecraft且你的Xbox game pass已经过期，或者你的账号已经被盗”

### 原因

没有为什么，就是有的时候让人看到“你没有在官网创建档案”会很迷惑

**Comment by iPodtouch6557** [comment]
其实吧……我不知道pcl是否能对你说的改进的情况做检测……
但是其实把这内容加了也很好，原来的有几率误导人

**Comment by sleep80** [comment]
> 其实吧……我不知道pcl是否能对你说的改进的情况做检测…… 但是其实把这内容加了也很好，原来的有几率误导人

检测其实不难的，他只要识别到你的账号已经添加了但是还是登录失败了那么就会出现新提示

**Comment by Chiloven945** [comment]
你可能未购买 Minecraft，或者你的 Xbox Game Pass 已过期，或者您的网络及微软登录服务器出现问题
盗号的可能性比较低，倒是微软服务器嗝屁和网络被墙的几率更大一点（

**Comment by youzi-2333** [comment]
交 PR 了（#1678），可以等龙猫看看……

**Comment by lovelysheepfield** [comment]
Xbox game pass那边的建议提一下，因为现在又很多的人贪便宜用xbox game pass……而且这个过期了自己也不知道，就以为是pcl的问题
