### ISSUE TITLE
名为Create+的整合包被错误地指向机械动力

### ISSUE THREAD

**Issue by Chiloven945** [Hex-Dragon/PCL2#1676]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://user-images.githubusercontent.com/116699482/232807507-c09a87ce-ba67-48a3-b4fa-cbee9bab739c.png)
该整合包的mc百科及mcbbs链接均被指向模组机械动力的界面，且该整合包的信息为机械动力的信息而不是此整合包

### 重现步骤

搜索此整合包

### 日志与附件

.

**Comment by WorldHim** [comment]
已初步确认，感谢您的反馈。
![](https://user-images.githubusercontent.com/68632311/233027103-5f3ed074-0cb7-4f9a-a895-cf51184da915.png)
