### ISSUE TITLE
导入整合包键位错误

### ISSUE THREAD

**Issue by maomian0** [Hex-Dragon/PCL2#1677]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

导入1.19.4MCBBS整合包，使用PCL2启动后，键位不是整合包作者设置的，而是默认键位
多次测试依旧如此，确认使用HMCL启动器无此BUG

### 重现步骤

1、导入1个1.19.4设置好键位的MCBBS整合包
2、安装完成后启动
3、打开键位设置，发现不是导入整合包设置好的键位

### 日志与附件

[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11263908/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11263909/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11263910/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11263912/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11263914/Log3.txt)

**Comment by WorldHim** [comment]
方便把整合包发一下吗？

**Comment by maomian0** [comment]
附件过大无法上传
将整合包调整后问题消失
真令人摸不到头脑。。。

**Comment by maomian0** [comment]
![F3M{}I}}XQO{TV_607SA2EM](https://user-images.githubusercontent.com/125042531/233079205-43b5a16b-a8da-4fc8-ba39-eac4bc31edbb.png)
![UMO_{ VXSI$@_ H)RELO505](https://user-images.githubusercontent.com/125042531/233079212-1cde6da7-f171-4d58-a8f9-8d3dc5bd6225.png)

**Comment by iPodtouch6557** [comment]
我看见HMCL在启动时那个iris栏三个按钮是被change过的（重置按钮可用）
但PCL不是

**Comment by maomian0** [comment]
下载后可以分别导入PCL启动一次看下，删除后HMCL启动一次看下按键设置

**Comment by maomian0** [comment]
可以发录的视频吗

**Comment by maomian0** [comment]
可以视频复现一下

**Comment by maomian0** [comment]
好像是PCL缓存的锅，直接加载了上次的配置文件，删除版本并重启PCL后重新安装无该问题
但如果使用PCL启动过同名同位置文件夹，然后删除后重新安装有新配置文件的，bug会复现

**Comment by WForst-Breeze** [comment]
那就看看龙猫怎么说吧…… BTW 补充信息请尽量使用 Edit 编辑功能
