### ISSUE TITLE
将Release Candidate版本的描述改为候选版1.x.x-rc[n]

### ISSUE THREAD

**Issue by iPodtouch6557** [Hex-Dragon/PCL2#1680]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

![image](https://user-images.githubusercontent.com/118656946/233091604-7050a559-9619-4faa-bafa-92c2167d8cf1.png)

这也是预发布版的话其实不准确，rc版与Pre版不一样

### 原因

~这样才能让玩家知道自己玩的是rc版（~
其实主要是这样不准确

**Comment by iPodtouch6557** [comment]
~之前提交了十几个issue全被关了，这个竟然惊人地被采用了~
所以优化是不是拿不了活跃橙
1114-D9AA-D51B-A57E

**Comment by WForst-Breeze** [comment]
> 所以优化是不是拿不了活跃橙

是的
