### ISSUE TITLE
PCL 的 Java选择 模块出现问题

### ISSUE THREAD

**Issue by RimacC2-EV** [Hex-Dragon/PCL2#1682]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在添加新Java/JDK【我是添加了新JDK预览版本（zip.格式）】后，（或开机后首次打开PCL后），PCL有概率检测不出所有曾经安装的Java/JDK。
![image](https://user-images.githubusercontent.com/125170682/233360618-ec59fba9-6fef-4079-871b-493aac629b9f.png)
没错，又是我，我又来反馈那些比较不容易出现的BUG了（经常倒腾PCL，不知道是不是被玩炸了，还有上次那个显示不正确的BUG，我到现在还没复现出来）

### 重现步骤

1、向（此电脑-下载中）添加新Java/JDK（或在电脑性能不佳的情况下启动PCL，加载很久的那种）
2、打开PCL，点击设置-游戏Java-自动搜索
3、有时会看到（未找到可用的Java）警告。

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11286017/Log1.txt)

**Comment by RimacC2-EV** [comment]
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11286094/Log1.txt)
现在PCL（在我手动导入Java/JDK后）可以检测成功了，所以说这个BUG不容易复现······

**Comment by LTCatt** [comment]
与 #1496 是同样的 Bug……确实不知道该怎么修，抱歉（
