### ISSUE TITLE
版本名称显示错误？

### ISSUE THREAD

**Issue by 212112111zwl** [Hex-Dragon/PCL2#1683]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

又是一个十分离奇的bug
首先，我更改了一个版本的名称，改成了 大写的BASE

然后，我又进行了修改，改成了 只有首字母大写的Base
第一次更改报错，是系统IO exception
我关闭了当时打开的文件资源管理器窗口，又试了一遍，显示更改成功

我关闭了启动器，过一会儿又打开了
点进版本设置，版本名称显示是大写的BASE
我尝试改名，但说我与现有文件夹重复（见图）
当时我版本列表里没有其他名为Base或BASE的版本

随后我退回启动器主页，进入版本列表，该版本名称又变成了 只有首字母大写的Base

### 重现步骤

见上

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11286191/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11286192/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11286193/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11286194/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11286196/Log2.txt)
![image](https://user-images.githubusercontent.com/121177845/233366915-2dfc20f1-776f-415c-be1d-a079e0044ad6.png)
![image](https://user-images.githubusercontent.com/121177845/233366937-e4df1110-66ad-4256-b85f-8485367b7837.png)

**Comment by 212112111zwl** [comment]
怀疑是大小写的问题？

**Comment by iPodtouch6557** [comment]
复现失败，咋改都不报错，都是修改成功
我担心你是在其中做了啥像这个bug一样离奇的事情~比如被Rick诈骗~
检查一下反馈列表……？

**Comment by LTCatt** [comment]
怀疑是文件占用或者大小写里 Windows 不识别的问题，一来难复现二来影响不大，算了……
