### ISSUE TITLE
更改.minecraft文件夹的属性为隐藏再改回只读后PCL2失去访问权限

### ISSUE THREAD

**Issue by YIXINGAlien666** [Hex-Dragon/PCL2#1684]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

PCL2显示无权限无法访问

### 重现步骤

1、在“用户-appdata-roaming”中找到.minecraft文件夹，属性设置为“隐藏-应用至子文件夹”
2、之后再将文件夹设置为“只读”，并启动PCL2弹出红色框显示pcl2无权限访问，
3、管理员权限运行后再启动游戏，显示无法访问libraries-org-lwjgl-lwjgl-3.2.2-lwjgl3.2.2-native-windows.jar，bug类型为System.UnauthorizedAccessException

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11286411/Log2.txt)

**Comment by LTCatt** [comment]
自己操作导致的问题无法处理。

**Comment by YIXINGAlien666** [comment]
对不起我操作失误的问题，劳烦您了（很对不起







                       
原始邮件
                       
                     

发件人："龙腾猫跃"< ***@***.*** &gt;;

发件时间：2023/4/21 3:58

收件人："Hex-Dragon/PCL2"< ***@***.*** &gt;;

抄送人："YIXINGAlien666"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [Hex-Dragon/PCL2] 更改.minecraft文件夹的属性为隐藏再改回只读后PCL2失去访问权限 (Issue #1684)




 
自己操作导致的问题无法处理。
