### ISSUE TITLE
正版登录失败

### ISSUE THREAD

**Issue by trcy1** [Hex-Dragon/PCL2#1685]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在正版登录的时候显示错误退出，然后就直接变成这个鬼样子了，无法重新登录。

### 重现步骤

1、点击xxxx
2、往下滚，然后点击xxxx

### 日志与附件

![QQ图片20230421175828](https://user-images.githubusercontent.com/127933113/233607701-105486ff-86e8-4882-87be-50bf0690ae33.png)

**Comment by iPodtouch6557** [comment]
刷新，刷新，刷新……
这个问题被反馈过多次了，请补充信息，以便我们确认是不是刷新的问题qwq……

**Comment by trcy1** [comment]
> 

可不可以上传视频啊？用文字解释太麻烦了。

**Comment by so1ve** [comment]
> > 
> 
> 可不可以上传视频啊？用文字解释太麻烦了。

可以，复制粘贴到输入框等上传完就行

**Comment by trcy1** [comment]
> > > 
> > 
> > 
> > 可不可以上传视频啊？用文字解释太麻烦了。
> 
> 可以，复制粘贴到输入框等上传完就行

好的

**Comment by trcy1** [comment]
> 刷新，刷新，刷新...... 这个问题被反馈过多次了，请补充信息，以便我们确认是不是刷新的问题qwq......

https://user-images.githubusercontent.com/127933113/233616763-2b953456-ba27-49d5-b009-04a84c2f84ca.mp4

**Comment by bwtx2023** [comment]
在官网登录一下账号再试，不行的话再试试其他启动器（HMCL / BakaXL 等）登录是否成功，还不行的话大概是网络问题了

**Comment by trcy1** [comment]
> 在官网登录一下账号再试，不行的话再试试其他启动器（HMCL / BakaXL 等）登录是否成功，还不行的话大概是网络问题了

好吧

**Comment by bwtx2023** [comment]
你执行了上述步骤之后问题有解决吗？

**Comment by LTCatt** [comment]
这不是启动器引发的问题，无法修复。
