### ISSUE TITLE
PCL2 使用 32 位的 JRE 时会尝试分配 2G 以上的内存导致启动失败

### ISSUE THREAD

**Issue by Ayx03** [Hex-Dragon/PCL2#1687]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

PCL2 会尝试在使用 32 位的 JRE 时分配 2GB 以上的内存，导致游戏无法启动
![](https://user-images.githubusercontent.com/75155322/233612832-811ee0c0-f48b-4d24-bc40-f42d7fef2505.png)
![](https://user-images.githubusercontent.com/75155322/233613081-a40700e6-edf4-4b53-b905-89f190f3c63c.png)

### 重现步骤

- 安装 32 位的 JRE 和兼容的游戏
- 「游戏 Java」设置为 32 位 JRE 或使启动器自动选择到 32 位 Java
- 启动前确保空闲内存大于 2G
- 「游戏内存」设置为「自动配置」

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11294890/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11294892/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11294885/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11294887/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11294888/Log5.txt)

**Comment by YUANXINGlingyun** [comment]
之前有个好像?

**Comment by LTCatt** [comment]
嗯……把你的所有 Java 列表，以及内存设置截个图？
此外，有在设置或者版本设置指定使用 Java 吗？

**Comment by Ayx03** [comment]
@LTCatt 使用自动选择或手动选择 32-bit 的 JRE 效果相同
https://user-images.githubusercontent.com/75155322/233613182-a2295d26-5d64-42d9-9fc5-47ac4486b741.png

**Comment by LTCatt** [comment]
加一下 QQ 1043137532，原因就写这个标题……
