### ISSUE TITLE
在自动下载Java前询问是否手动选择（

### ISSUE THREAD

**Issue by misividkoukou** [Hex-Dragon/PCL2#1688]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

众所周知，pcl2似乎在一些时候并不能检测到已有的Java……所以在没有检测到Java前询问一下总是好的（

### 原因

呜~~~~~

**Comment by LTCatt** [comment]
现在会询问啊？
