### ISSUE TITLE
预览版改为泥土

### ISSUE THREAD

**Issue by Chormore-EDGE** [Hex-Dragon/PCL2#1690]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

无

### 原因

![image](https://user-images.githubusercontent.com/114737601/233645357-ae653a5c-59bf-4ddc-84ae-e7bb59869e83.png)

**Comment by Chiloven945** [comment]
感觉这样识别度就降低了好多（

**Comment by iPodtouch6557** [comment]
> 感觉这样识别度就降低了好多（

习惯就好啦
还有也要适当跟进国际版

**Comment by LTCatt** [comment]
Mojang 有个鬼的审美，不改（点头

**Comment by Chormore-EDGE** [comment]
答辩审美
