### ISSUE TITLE
单独分类combat test的测试版本

### ISSUE THREAD

**Issue by misividkoukou** [Hex-Dragon/PCL2#1694]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

哎哟，你干嘛~
真的好难找哦

### 原因

哎哟~~

**Comment by WForst-Breeze** [comment]
Combat Test 版本现在后续更新杳无音信……感觉不太可能会被采纳，不过看看龙猫怎么想吧？已初步确认，感谢您的反馈~
