### ISSUE TITLE
支持在文件夹列表中隐藏官方启动器文件夹

### ISSUE THREAD

**Issue by fhh1224** [Hex-Dragon/PCL2#1696]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

可以隐藏官方启动器文件夹

### 原因

被月亮端占用，因此不需要从官方启动器文件夹启动

**Comment by iPodtouch6557** [comment]
可以是隐藏任意文件夹功能，不止官方文件夹

**Comment by LTCatt** [comment]
隐藏后没有一个比较好的方法让它恢复显示，并且估计这个功能也没多少人会用，还是算了 =。=
