### ISSUE TITLE
指令缺失

### ISSUE THREAD

**Issue by 2448856886** [Hex-Dragon/PCL2#1697]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

添加forge后在开启作弊的情况下输入正常指令显示指令无效

### 重现步骤

1.安装1.16.5的Minecraft
2安装forge
3正常启动游戏

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11300714/Log1.txt)

**Comment by 2448856886** [comment]
lssue

**Comment by 2448856886** [comment]
lssue

**Comment by WForst-Breeze** [comment]
这个问题以前也有人出现过……不过当时我们没能复现成功，按理讲不是启动器的问题

请上传相关录屏、截图，使用 其他启动器 启动游戏是否问题依然存在？

**Comment by hellominecraftlauncher** [comment]
概率性复现，约为37.11%左右

**Comment by Super-XiaoNian** [comment]
Missing required option(s) [accessToken, version]?

**Comment by hejiehao** [comment]
>  Missing required option(s) [accessToken, version]?

accessToken will be hidden in the logs

**Comment by LTCatt** [comment]
这不是启动器 **可能** 导致的 Bug，问题只可能来源于游戏本身。
