### ISSUE TITLE
愚人节菜单的跳关

### ISSUE THREAD

**Issue by MinecraftSTL** [Hex-Dragon/PCL2#1699]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我跳过了抓按钮的过程

### 重现步骤

等到愚人节
启动PCL2
按回车

### 日志与附件

我觉得复现足够简单了

**Comment by iPodtouch6557** [comment]
不简单qwq
请补充信息

**Comment by MinecraftSTL** [comment]
[http://a1.qpic.cn/psc?/V53r72CY4fvcAM0kRJLp4PZl8k0wbBhR/ruAMsa53pVQWN7FLK88i5mQjuSyayl*pqLWlTuPHYPDuXFwefm01G*D60sVTKT0uoLYPfaMDTF*ml8F3pMuUIzZyIzr8jD9mVi3GQeujMqw!/b&ek=1&kp=1&pt=0&bo=OARwBTgEcAUWECA!&tl=1&vuin=2811054427&tm=1682161200&dis_t=1682161614&dis_k=36d5405ac6f9f77c5d5d7324eb121595&sce=50-1-1&rf=4-0](爱发电也有相关信息)

**Comment by iPodtouch6557** [comment]
最新版按enter只会出现蓝色提示  木大！
