### ISSUE TITLE
UUID不同导致某些mod无法正常运行

### ISSUE THREAD

**Issue by hellominecraftlauncher** [Hex-Dragon/PCL2#1700]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

希望添加修改UUID功能，要不有些依赖UUID的模组就没法使用，比如BQ、通量网络等依赖UUID的
如果UUID变动，即使你ID是1，这些模组会把你的ID识别成2，从而失去超管等特权

### 原因

这个功能可以方便离线玩家无法用外置、正版的情况下UUID不一样导致游戏失去模组超管特权

**Comment by YUANXINGlingyun** [comment]
与 #169 的本质相同，您可以前往 #298 为其投票！
