### ISSUE TITLE
在 Snapshot 2.5.3 版本中无法加载 1.19.2 离线皮肤

### ISSUE THREAD

**Issue by ExpertPbSeal** [Hex-Dragon/PCL2#1707]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

**声明：本人已知晓关于离线皮肤加载的警告，版本隔离已打开。**
提交理由：之前正常的功能现在失效了，且理论上它不应该失效，这不是bug还是啥？（悲叹

在启动器最新快照版本 Snapshot 2.5.3 的 1.19.2 中加载离线皮肤，游戏提示PCL2内置的皮肤包为“适用于新版本的包”，经确认为包文件“pack.mcmeta”中变量"pack_format"被启动器修改至“10“所致。然而，在将该变量手动修改至适于1.19.2 的“9”后再次启动游戏，发现启动器将该变量再次改回“10”。于游戏进行中将该变量手动修改至“9”并重载皮肤包，发现皮肤正常显示。

建议：启动游戏时增加对版本号的判断，对于版本 1.19.2 使用"pack_format"值为“9”的皮肤包。
_至少我不在意启动器体积增加（_
![image](https://user-images.githubusercontent.com/79563897/233837729-653db7c9-0ffc-49bf-9775-aaff7901993f.png)

### 重现步骤

在老版本启动器 Release 2.4.9 ，版本 1.19.2 中加载离线皮肤，皮肤正常显示。在启动器最新快照版本 Snapshot 2.5.3 的同一版本中加载离线皮肤，游戏提示PCL2内置的皮肤包为“适用于新版本的包”，且皮肤无法正常显示。在关闭游戏后将该变量手动修改至适于1.19.2 的“9”并再次启动游戏，发现启动器将该值再次改回“10”，离线皮肤无法正常显示。

### 日志与附件

不认为启动器日志会对于该问题提供帮助。
Release 2.4.9：
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11303597/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11303599/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11303600/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11303602/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11303603/Log1.txt)
Snapshot 2.5.3：
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11303605/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11303606/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11303607/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11303608/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11303609/Log2.txt)

**Comment by iPodtouch6557** [comment]
其实我觉得这不叫解决方案……

**Comment by youzi-2333** [comment]
总感觉和那个 1.19.3+ 无法加载的 Bug 实质重复，但是这是 2.5.3 开始的 Bug，先让龙猫看看吧……
我也没有快照版，没法复现（叹气）

标题建议：`在 2.5.3 版本中无法加载 1.19.2 离线皮肤`

**Comment by Chiloven945** [comment]
实测在1.19.2可以使用自定义皮肤，且版本为10
![image](https://user-images.githubusercontent.com/116699482/233840208-d2e3333a-098c-4c47-91f4-54e4faad29cf.png)

**Comment by ExpertPbSeal** [comment]
> 实测在1.19.2可以使用自定义皮肤，且版本为10 ![image](https://user-images.githubusercontent.com/116699482/233840208-d2e3333a-098c-4c47-91f4-54e4faad29cf.png)
> 
> > 总感觉和那个 1.19.3+ 无法加载的 Bug 实质重复，但是这是 2.5.3 开始的 Bug，先让龙猫看看吧…… 我也没有快照版，没法复现（叹气）
> > 标题建议：`在 2.5.3 版本中无法加载 1.19.2 离线皮肤`
> 
> 应该不是重复，因为Mojang在1.19.3才加入了新的皮肤导致了原有算法的失效

这个是正式版吧？

**Comment by Chiloven945** [comment]
……
![image](https://user-images.githubusercontent.com/116699482/233842959-803a7847-e8ef-4bdd-963f-b5fc8b3a4e4e.png)

**Comment by ExpertPbSeal** [comment]
我这边是这个配置
![image](https://user-images.githubusercontent.com/79563897/233843464-5e4ecac1-e9be-4247-906d-998081921a19.png)
但是
![image](https://user-images.githubusercontent.com/79563897/233843632-e6790880-688b-488c-90c9-18a22e70d1ee.png)
**我真的谢谢你Mojang**

**Comment by ExpertPbSeal** [comment]
所以真正的原因是：**Minecraft默认禁用来自高版本的资源包导致皮肤无法加载**
但还是改一下吧，不然真的折磨一众打死不看资源包状态的玩家（

**Comment by ExpertPbSeal** [comment]
所以真正的原因是：**Minecraft默认禁用来自高版本的资源包导致皮肤无法加载**
但还是改一下吧，不然真的折磨一众打死不看资源包状态的玩家（

Github为什么又双叒挂了（

从 Windows 版邮件发送

发件人: ClovenBugle
发送时间: 2023年4月23日星期日 下午9:37
收件人: Hex-Dragon/PCL2
抄送: Peter Wang; Author
主题: Re: [Hex-Dragon/PCL2] 在 Snapshot 2.5.3 版本中无法加载 1.19.2 离线皮肤 (Issue #1707)

……

**Comment by Chiloven945** [comment]
> 我这边是这个配置 ![image](https://user-images.githubusercontent.com/79563897/233843464-5e4ecac1-e9be-4247-906d-998081921a19.png) 但是 ![image](https://user-images.githubusercontent.com/79563897/233843632-e6790880-688b-488c-90c9-18a22e70d1ee.png) **我真的谢谢你Mojang**

嗯……看起来需要手动启用（

**Comment by ExpertPbSeal** [comment]
（发表于4.23.22:00）
所以真正的原因是：**Minecraft默认禁用来自高版本的资源包导致皮肤无法加载**
但还是改一下吧，不然真的折磨一众打死不看资源包状态的玩家（

_我谢谢你Github,谢谢你Windows邮箱_

**Comment by ExpertPbSeal** [comment]
才发现 Snapshot 2.5.3 **从1.19到1.19.4的皮肤包加载都出了问题** （悲
但1.19.4报告为“适用于**旧**版本的资源包”，所以Bugjump你到底在幹嘛。。。

要不我再发个issue让在
![image](https://user-images.githubusercontent.com/79563897/233987355-5dfb7b39-48f5-4956-b35c-8c3b847e85e3.png)
添加一句“若离线自定义皮肤加载失败请尝试手动启用皮肤包”，亦或是写个帮助文件？~再或者等#1288搞好？先让自定义皮肤跑起来再说？~

**Comment by 212112111zwl** [comment]
我也显示适用于新版本，但能正常加载

**Comment by ExpertPbSeal** [comment]
离谱，我这里全都默认禁用，改了再进去还是禁用，如图
https://user-images.githubusercontent.com/79563897/233843632-e6790880-688b-488c-90c9-18a22e70d1ee.png
是不是启动器版本原因？

> 我也显示适用于新版本，但能正常加载

**Comment by ExpertPbSeal** [comment]
而且不加载皮肤包皮肤一样没法显示

**Comment by WForst-Breeze** [comment]
1.19.3+ 皮肤无法自定义是已知问题，属于另一个 Issue，最好不要在这里**过多地**讨论，否则会由于过于热门而锁定本 Issue

**Comment by Chiloven945** [comment]
一般你自己装载过新或过旧的版本时重启游戏不会使资源包失效，或者说是更改导致了失效，还有就是请善用edit功能

**Comment by ExpertPbSeal** [comment]
@WForst-Breeze 感谢提醒！还有,赞美 @LTCatt !这是我的识别码：CFB3-D047-EAF6-3CE8

**Comment by iPodtouch6557** [comment]
> @WForst-Breeze 感谢提醒！还有,赞美 @LTCatt !这是我的识别码：CFB3-D047-EAF6-3CE8

不要乱@哦

**Comment by LTCatt** [comment]
你的解锁码：l4HoLAUI5yTrgBddCvLDJNPX4IoyNaIi
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
