### ISSUE TITLE
1.0版本分类不同

### ISSUE THREAD

**Issue by gaojin20090517** [Hex-Dragon/PCL2#1709]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

1.0版本在下载界面属于正式版，图标是草方块
下载之后在版本选择界面属于远古版本，图标是圆石，分类在不常用版本

![image](https://user-images.githubusercontent.com/125573915/233839969-57350ba3-6707-48b1-ae14-c0425e5b264d.png)
![image](https://user-images.githubusercontent.com/125573915/233840005-8e410e2c-1f0a-41f1-a570-b340335d8ee1.png)

### 原因

只要统一一下，个人认为既然是1.0版本了，就放在正式版里面吧

**Comment by LTCatt** [comment]
因为 Mojang 的分类方式与 PCL 的不同 =。=
问题不大其实…………
