### ISSUE TITLE
把快照版，Optifine版本，可安装mod的版本，常规版本，远古版本，愚人节版本，curseforge整合包分开排列

### ISSUE THREAD

**Issue by gaojin20090517** [Hex-Dragon/PCL2#1710]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

能不能把快照版，Optifine版本，可安装mod的版本，常规版本，远古版本，愚人节版本，curseforge整合包分开排列

看着也齐整，像下载界面一样分类，图标也统一下载版本的样式

### 原因

好乱啊qwq

快照版不知道自己应该在哪里
![image](https://user-images.githubusercontent.com/125573915/233840696-16c8701d-e53c-4e7c-b4aa-37461919ae6a.png)
![image](https://user-images.githubusercontent.com/125573915/233840713-a261486a-c578-44f7-ba97-ccb72362144b.png)

**Comment by Chiloven945** [comment]
标题建议更改为“将版本选择列表按版本类型分类”

**Comment by LTCatt** [comment]
暂时不会……抱歉（
