### ISSUE TITLE
特定版本下的正版皮肤显示异常

### ISSUE THREAD

**Issue by UmouLs** [Hex-Dragon/PCL2#1711]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

单人世界 正版皮肤加载异常
具体表现：1.19.3以下正常加载正版皮肤
1.19.3以上重置为默认角色中的一个
更换正版皮肤概率能暂时解决问题 无mod
启动器皮肤可以正常刷新
刷新皮肤后启动游戏无法解决该问题

### 重现步骤

打开启动器登录游戏或刷新皮肤后登录游戏 

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11305207/Log2.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11305213/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11305214/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11305215/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11305216/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11305217/Log1.txt)

**Comment by Chiloven945** [comment]
与 #1288 重复，你可以于 #1596 为其投票

**Comment by LTCatt** [comment]
网络问题，与启动器无关（

**Comment by UmouLs** [comment]
> 网络问题，与启动器无关（

呃 确定吗
进入多人服务器的皮肤是正常加载的 没有切换过网络且从多人切到单人就又是默认皮肤了
用HMCL在单人和多人均不会出现这种问题

**Comment by UmouLs** [comment]
> 网络问题，与启动器无关（

如果是网络问题 多人游戏皮肤正常加载 未退出游戏的前提下在单人又加载不出来
1.19.3以上加载正常 1.19.3以下不会出现加载错误感觉有点说不通
