### ISSUE TITLE
获取微软正版皮肤失败

### ISSUE THREAD

**Issue by MNWZ211** [Hex-Dragon/PCL2#1712]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

打开启动器出现报错
<img width="578" alt="屏幕截图 2023-04-24 200149" src="https://user-images.githubusercontent.com/80450278/233991928-9e223259-9e64-4111-8c38-cbda57c9d3da.png">
<img width="578" alt="屏幕截图 2023-04-24 200149" src="https://user-images.githubusercontent.com/80450278/233991938-df0f0c94-291a-49cd-811e-237bb8e2476f.png">

### 重现步骤

1、点击xxxx
2、往下滚，然后点击xxxx
1、点击启动器
2、出现报错

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11310266/Log1.txt)

**Comment by LTCatt** [comment]
无法重现，可能是其他软件占用导致……（例如杀毒软件正在扫描导致占用）
在有更多人反馈前暂时不处理 Orz
