### ISSUE TITLE
模组下载页面可以筛选模组支持的平台(Forge/Fabric/Quilt/LiteLoader)

### ISSUE THREAD

**Issue by Xibeilius** [Hex-Dragon/PCL2#1714]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

搜索下载模组的时候，希望添加一个筛选模组可以支持的平台的选项，比如我只想看Fabric平台的模组，或者我只想看Forge平台的模组。

### 原因

下载好一个游戏版本后，模组加载器就已经确定为Forge或者Fabric或者其他什么的了，这时候搜索模组，如果支持根据加载器平台筛选，会方便很多。比如我下载了加载器Fabric版本的游戏，下载模组时，我不想看Forge平台的模组，只想看支持Fabric的模组。
如果没有这个功能，我很多情况下会感觉到类似“啊这个模组看起来不错，害怎么只支持Forge，还不如一开始别搜出来”的困扰。

**Comment by Chiloven945** [comment]
cf的API只允许在选择版本后进行加载器筛选……

**Comment by Xibeilius** [comment]
> cf的API只允许在选择版本后进行加载器筛选……

啊这，是我不懂了，那这样的话，就很难办了。
