### ISSUE TITLE
添加游戏时长记录功能

### ISSUE THREAD

**Issue by MaguaguaX** [Hex-Dragon/PCL2#1717]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

您好，龙腾猫跃。我是一位pcl2的忠实使用者
我想提出一个pcl2的更新建议：
请问能否添加一个mc游戏时长记录
功能如下：
1，记录每一个版本的游戏时长
2，记录总游戏时长
3，能有一个列表看到各个版本的游戏时长并可排序。（排序功能例如：按时长排序，按版本名称排序，按版本加入日期排序。均选择升序降序排序。）
4，可以选择性删除特定版本的游戏时长。(同时也会影响到总游戏时长记录）
5，就算删除了某个版本，但是那个版本的游戏时长也可以选择性保留/删除。

### 原因

我发现目前我能接触到的启动器都没有记录游戏时长的功能
当然，如果要做出这样的功能，一做就尽量做到最好。全方位考虑。

在室友玩steam游戏的时候，无意中谈论到游戏时长，
我在想，为什么mc没有游戏时长记录呢。

所以我提出了这个更新建议。

**Comment by LTCatt** [comment]
不打算制作 Orz

**Comment by MCSteve123** [comment]
感觉不错，但Steam游戏时间记录是基于云存档的，所以在任何设备上玩都可以记录，但PCL不会制作云服务，所以换台设备就全清空了……？

**Comment by WorldHim** [comment]
> 感觉不错，但Steam游戏时间记录是基于云存档的，所以在任何设备上玩都可以记录，但PCL不会制作云服务，所以换台设备就全清空了……？

其实每个世界内有独立的统计信息可以查询游戏时长，路径为 `<存档根目录>/stats/<UUID>.json`，命名空间 ID 为 `minecraft:play_time`。
