### ISSUE TITLE
建议将正版账户的功能按钮改为常驻并用正常颜色显示

### ISSUE THREAD

**Issue by xitieshiz2** [Hex-Dragon/PCL2#1719]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

![image](https://user-images.githubusercontent.com/75575551/234845184-65c6c111-9f66-4f4a-9038-ba42984fc68c.png)
如图，目前正版账户的功能按钮只有鼠标挪到对应区域才会显示，且在部分配色/背景下很难注意到，建议将其改为常驻且用正常颜色显示
离线账户的皮肤功能也建议同步为这种按钮

### 原因

目前版本的功能按钮在部分配色/背景下很难注意到

**Comment by iPodtouch6557** [comment]
我认为……还可以将littleskin的那两个按钮做成常驻

**Comment by Chiloven945** [comment]
加开关应该更好点

**Comment by LTCatt** [comment]
修改了配色，应该看得清了
