### ISSUE TITLE
pcl2的issue无法使用github for Android发起

### ISSUE THREAD

**Issue by deep-dark-forest** [Hex-Dragon/PCL2#1722]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

pcl2的issue无法使用github for Android发起。而且，我已经确定这不是github的锅——我已经甚至自己创建了个存储库然后创建了几个问题模板，结果显示我创建的这些问题模板都是可以用github安卓版发起的。但是当我试图用手机安卓版github发起issue时，却只找到了两个链接选项。

### 原因

对于电脑不在身边的发起issue太麻烦了！

**Comment by iPodtouch6557** [comment]
改一下标题……
还有，其实是可以交discussion的，但是交了就交了吧……
~另外，我不会复现该bug的，因为我没有任何app端的github，我也永远不会用安卓手机~

**Comment by sleep80** [comment]
![Screenshot_20230427_213054](https://user-images.githubusercontent.com/122155884/234877774-5a9f9896-e3f8-4115-aa37-15461b3e7dc3.jpg)
刚刚趋势了一下，自己创建的仓库里面的问题模板确实可以用github手机版发起

**Comment by Chormore-EDGE** [comment]
~好像也不是pcl2issue的锅~
这个bug谁会复现啊
现在都是用电脑和网页github
~安卓github很冷门~

**Comment by Chormore-EDGE** [comment]
![image](https://user-images.githubusercontent.com/114737601/234885868-5642cca9-e174-4bc2-a4d1-dd7831bd979e.png)
https://github.com/mobile没有安卓选项
~众所周知因为一些原因Googleplay在国内要一些方法~

**Comment by LTCatt** [comment]
这应当是 GitHub 的问题
