### ISSUE TITLE
添加字体大小设置

### ISSUE THREAD

**Issue by MINECRAFTGUIYU** [Hex-Dragon/PCL2#1724]
### 检查项

- [x] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

在设置-个性化中添加字体大小设置（最好可以做条），其范围包括启动器页面、用户名、mod名称等

### 原因

昨天更新的新用户页面中的正版登录显示名称太大了，可以加个设置调一下，应该不止我一个人认为字体太大了罢。

**Comment by iPodtouch6557** [comment]
emmm……我就不认为字体太大了（）去设置程序改fontsize其实很烦
但是也不是不可以

**Comment by MINECRAFTGUIYU** [comment]
> 
这玩意还可以改第一次知道（）加个条条感觉更好小白适应

**Comment by YUANXINGlingyun** [comment]
会导致 UI **适配问题**吧? 在字体较大的时候

**Comment by MINECRAFTGUIYU** [comment]
> 会导致 UI **适配问题**吧? 在字体较**大**的时候

这个具体如果龙猫处理的话得看龙猫有啥办法了awa

**Comment by LTCatt** [comment]
会导致严重的 UI 适配问题，不考虑制作。

**Comment by Crotina** [comment]
@LTCatt 
其实不用考虑ui问题，给弹个警告算了
