### ISSUE TITLE
一键改名mod

### ISSUE THREAD

**Issue by AstuyuAwA** [Hex-Dragon/PCL2#1728]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [x] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

在mod管理栏里面，搞一个一键将所有mod命名加上中文译名的功能，比如把example.jar改成[示例]example.jar

### 原因

这样可以把mod文件夹变得让人更能读懂

**Comment by Chiloven945** [comment]
这意味着要识别所有mod的ID之后再使用API指向到对应的模组，再去mc百科获取中文译名
目前下载是默认有译名的，但是有些没有的话就是真的没有了

**Comment by AstuyuAwA** [comment]
有些整合包的mods就是没有带译名，这就是为什么我想要这个功能

**Comment by Chiloven945** [comment]
> 有些整合包的mods就是没有带译名，这就是为什么我想要这个功能

那我的建议倒是把这个issue更改为“下载整合包mod时为mod加上中文译名”

**Comment by LTCatt** [comment]
不考虑制作，抱歉……
