### ISSUE TITLE
愚人节版本改名后下载出现自动分类错误

### ISSUE THREAD

**Issue by xtrackc1437** [Hex-Dragon/PCL2#1733]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

今天下载了23w13a_or_b 下载好之后打开版本选择发现分类到“快照”了...

(也不知道发生了什么反正感觉是bug（

### 重现步骤

1、下载23w13a_or_b
2、打开版本选择 发现自动分类将其分类至“快照”

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11358108/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11358109/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11358110/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11358111/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11358112/Log2.txt)

Log3~5没什么用 都是很早之前的了

![image](https://user-images.githubusercontent.com/67376014/235278573-4453dcf0-80ec-42ec-9194-63b31876fe8d.png)

**Comment by WorldHim** [comment]
您反馈的 bug 应在 #1643 中已修复，请尝试刷新列表，若仍无法使用请反馈。

**Comment by xtrackc1437** [comment]
> 您反馈的 bug 应在 #1643 中已修复，请尝试刷新列表，若仍无法使用请继续反馈。

使用刷新之后 23w13a_or_b依然分类在常规版本里...

**Comment by iPodtouch6557** [comment]
复现失败
……

**Comment by xtrackc1437** [comment]
今天再次下载了一遍，同样分类为快照（图中23w13a_or_b_orig2）

![image](https://user-images.githubusercontent.com/67376014/235334521-e0e43b51-2d01-495f-8902-f34ca65798cb.png)

**Comment by xtrackc1437** [comment]
再次测试了一下，发现下载愚人节版本时修改了版本名 都会被误分为快照

![image](https://user-images.githubusercontent.com/67376014/235334701-32827494-d178-492f-8951-5a0810dd8bcf.png)
全部分类错误且刷新无法消除

**Comment by iPodtouch6557** [comment]
很好很好，复现成功……
![image](https://user-images.githubusercontent.com/118656946/235356124-d551c2b7-1349-4faf-a7aa-41cf558bfc63.png)
[Log.txt](https://github.com/Hex-Dragon/PCL2/files/11361425/Log.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11361427/Log1.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11361431/Log3.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11361428/Log2.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11361432/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11361434/Log5.txt)

**Comment by WorldHim** [comment]
难道 PCL 用版本名分类。？

**Comment by youzi-2333** [comment]
@LTCatt

**Comment by iPodtouch6557** [comment]
这bug都多久了还没见龙猫有反应……

**Comment by xtrackc1437** [comment]
求一个活跃橙解锁码 谢谢
D20A-F7E7-66B1-3245
@LTCatt

**Comment by LTCatt** [comment]
你的解锁码：hDjd78HC3RckSKTSS1eQPmvpsb1hr42/
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
