### ISSUE TITLE
分类错误

### ISSUE THREAD

**Issue by duan666888** [Hex-Dragon/PCL2#1734]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

本来1.7.1  1.7  1.6.3  1.6是原版，在版本列表里显示的是快照

### 重现步骤

1、点击版本选择，不常用版本
2、往下滚就看到了

### 日志与附件

[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11358187/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11358188/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11358189/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11358190/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11358191/Log4.txt)
![image](https://user-images.githubusercontent.com/124878842/235279611-90548073-cbe0-4ae2-bf26-73504e0e4f73.png)
![image](https://user-images.githubusercontent.com/124878842/235279633-1665c561-4ea7-4569-ad38-c5ec3fc7d66b.png)
![image](https://user-images.githubusercontent.com/124878842/235279652-fad209bc-5d4b-47c4-8f92-85c8c4866b7c.png)
![image](https://user-images.githubusercontent.com/124878842/235279664-8d436b62-9616-435c-ac21-44cba3c867c5.png)
![image](https://user-images.githubusercontent.com/124878842/235279675-fbe0f0de-e435-4b74-8299-493557d4ca51.png)

**Comment by iPodtouch6557** [comment]
不对啊…………………………
按理来说1.8以前的版本都是用正式版的编号思路来编号预发布版……也就是说1.7和1.7.1都是预发布版
但是在下载源里却归类为正式版……

**Comment by WorldHim** [comment]
试试使用官方源会不会出现此问题？

**Comment by IF-desu** [comment]
这些版本的确不是正式版，具体怎么说看wiki罢

**Comment by IF-desu** [comment]
wiki对于1.6.3的解释https://minecraft.fandom.com/zh/wiki/Java%E7%89%881.6.3

**Comment by IF-desu** [comment]
这些版本并不属于正式版

**Comment by YUANXINGlingyun** [comment]
机器人的连接好不稳定。。。
又一个 Label 不对的反馈
