### ISSUE TITLE
使用最新版启动时崩溃，换成旧版就能正常启动

### ISSUE THREAD

**Issue by gusuruofan** [Hex-Dragon/PCL2#1735]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃不是 PCL2 的原因，请 **不要** 提交反馈。你可以在 QQ 群里或者论坛找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是游戏本身的问题，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

使用最新版pcl启动整合包时MC进程出现后约两秒就崩溃了，换回旧版的pcl就启动成功了

### 错误报告、日志与附件

[错误报告-2023-4-28_22.19.42.zip](https://github.com/Hex-Dragon/PCL2/files/11358661/-2023-4-28_22.19.42.zip)

**Comment by WorldHim** [comment]
能否提供整合包文件

**Comment by gusuruofan** [comment]
邮件发送吗？&nbsp;


2222
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月29日(星期六) 下午4:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Hex-Dragon/PCL2] 使用最新版启动时崩溃，换成旧版就能正常启动 (Issue #1735)





 
能否提供整合包文件

**Comment by gusuruofan** [comment]
可以提供，但其中含有付费mod，可能无法公开传播

**Comment by WorldHim** [comment]
额，如果不方便的话可以先自行排查，如一个个安装mod确认是否是mod冲突。

**Comment by gusuruofan** [comment]
用旧版的PCL可以正常打开

**Comment by gusuruofan** [comment]
应该不是mod冲突

**Comment by WorldHim** [comment]
好像是有关 optifine 和 java 的问题，可以试试禁用 optifine 或选择低版本 java。
另：forge 对高版本 java 的支持不好，建议使用低版本 java。

**Comment by LTCatt** [comment]
![image](https://user-images.githubusercontent.com/40348278/235306461-176c247a-5790-4d10-8310-dc9cb09cc52d.png)

上传 HMCL 导出的启动脚本

**Comment by gusuruofan** [comment]
[启动.txt](https://github.com/Hex-Dragon/PCL2/files/11359336/default.txt)
把bat改成txt了，不能直接上传bat

**Comment by LTCatt** [comment]
加一下 QQ：1043137532，原因写 issue #1735

**Comment by LTCatt** [comment]
已确认是 Mod 导致部分 Java 不能启动，无法修复
