### ISSUE TITLE
近期从启动器下载的新版本全部都报错

### ISSUE THREAD

**Issue by lazy-11g** [Hex-Dragon/PCL2#1737]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃不是 PCL2 的原因，请 **不要** 提交反馈。你可以在 QQ 群里或者论坛找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是游戏本身的问题，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

近期在启动器里面下载了好几个版本，以及整合包，结果都启动不了，一启动就崩溃
但是之前在启动器里面下载的整合包和版本就没有这些问题

### 错误报告、日志与附件

[错误报告-29-04-2023_6.25.40_pm.zip](https://github.com/Hex-Dragon/PCL2/files/11358936/-29-04-2023_6.25.40_pm.zip)
[错误报告-29-04-2023_6.30.36_pm.zip](https://github.com/Hex-Dragon/PCL2/files/11358937/-29-04-2023_6.30.36_pm.zip)
另一个是在pcl2新下载的1.19.4版本没有装模组，一个是在pcl2新下载的整合包的崩溃日志（我近期在pcl2下载的所有整合包都启动不了，而以前则没有遇到过这些问题，所以只能怀疑是启动器出了问题了），都是第一次启动就崩溃

**Comment by YUANXINGlingyun** [comment]
请先尝试使用其他启动器（[下载](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)）进行一下启动，如果其他启动器未出现崩溃，才能说明是 PCL2 的问题

请在尝试后回复启动情况

**Comment by lazy-11g** [comment]
> 请先尝试使用其他启动器（[下载](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)）进行一下启动，如果其他启动器未出现崩溃，才能说明是 PCL2 的问题 如果确认是 PCL2 的问题，请来补充 如果是游戏本身的问题并想获得帮助，请到[讨论板块](https://github.com/Hex-Dragon/PCL2/discussions)发帖询问

我用hmcl启动器试过了，暂时并没有出现这种问题

**Comment by LTCatt** [comment]
![image](https://user-images.githubusercontent.com/40348278/235306461-176c247a-5790-4d10-8310-dc9cb09cc52d.png)

上传 HMCL 导出的启动脚本

**Comment by lazy-11g** [comment]
![QQ截图20230429220555](https://user-images.githubusercontent.com/132079060/235307061-44d95639-58a8-49a7-afab-9478d2a1ceb0.png)
这个东西怎么上传，拖拽上传不了啊

**Comment by lazy-11g** [comment]
> ![image](https://user-images.githubusercontent.com/40348278/235306461-176c247a-5790-4d10-8310-dc9cb09cc52d.png)
> 
> 上传 HMCL 导出的启动脚本
[sel.zip](https://github.com/Hex-Dragon/PCL2/files/11359352/sel.zip)

**Comment by LTCatt** [comment]
加一下 QQ：1043137532，原因写 issue https://github.com/Hex-Dragon/PCL2/issues/1737

**Comment by LTCatt** [comment]
也可以尝试手动在设置里选择 C:\\Program Files\\Common Files\\Oracle\\Java\\javapath_target_3479000\\java.exe 来启动，看看能不能跑

**Comment by LTCatt** [comment]
由于未回复暂时关闭，有需要可以继续回复。
