### ISSUE TITLE
对于左下角的跳出提示进行优化

### ISSUE THREAD

**Issue by YUANXINGlingyun** [Hex-Dragon/PCL2#1738]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

1. 将左下角的跳出提示停留时间略微增长
2. 点击左下角任意一条跳出提示，将所有的提示关闭

### 原因

优化 1 有助于观察部分信息
我记得 优化 2 原来是有的来着，啥时候删掉了

**Comment by iPodtouch6557** [comment]
还是点击对应提示删除对应提示吧，这样更好一点

**Comment by YUANXINGlingyun** [comment]
> 还是点击对应提示删除对应提示吧，这样更好一点

也行

**Comment by LTCatt** [comment]
点击删除反而和预期行为不一致，这是刻意的设计 :(
