### ISSUE TITLE
确定版本号

### ISSUE THREAD

**Issue by Bandysol** [Hex-Dragon/PCL2#1739]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

将检查更新后的提示更改为“当前启动器已为最新版（版本号）,无需更新！”
或者是在 设置->启动器->系统 中显示启动器版本。

### 原因

方便确定版本，不需要每次都要打开Log文件。

**Comment by iPodtouch6557** [comment]
这玩意吧……
在更多——关于与鸣谢里有……

**Comment by Bandysol** [comment]
但是太不明显了

**Comment by 212112111zwl** [comment]
可以在启动动画显示pcl图标的时候下面加一行版本号？

**Comment by Chormore-EDGE** [comment]
![image](https://user-images.githubusercontent.com/114737601/235333156-f3cbdd42-c344-40e4-8262-942e1f0e02ed.png)
建议在这右下角加一个V.n.n.n或版本vn.n.n

**Comment by youzi-2333** [comment]
> 建议在这右下角加一个 V.n.n.n 或版本 vn.n.n

这样不太美观吧，而且 Textbox 控件也不好加这个……
你可以交个 Issue 看看
