### ISSUE TITLE
在 版本选择 页面中，可以拖拽不同的版本以更改其排列顺序

### ISSUE THREAD

**Issue by tlwsy** [Hex-Dragon/PCL2#1741]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在版本选择页面可以拖拽不同的版本，以更改游戏版本的排列顺序

### 原因

我在版本选择里面有将近50个不同的版本，不能方便地更改不同游戏版本的排列顺序会导致难以找到我需要的游戏版本
有看到在功能投票中提议添加搜索框的，但是依然不如直接更改版本的排列顺序来得方便

**Comment by LTCatt** [comment]
可以添加收藏夹。
改排序不好做，收益也不大，算了…………抱歉（
