### ISSUE TITLE
自定义离线皮肤加载不了是怎么回事希望大大能看看

### ISSUE THREAD

**Issue by 520yunchen** [Hex-Dragon/PCL2#1746]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![~)SWX}H5(VP J)VDE{R8$@X](https://user-images.githubusercontent.com/132180772/235336966-cab203e9-240c-4969-b8d7-1f07aa308858.png)

### 重现步骤

1、点击设置
2、然后点击自定义离线皮肤
3加载自定义皮肤

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11360639/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11360640/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11360641/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11360642/Log4.txt)

**Comment by YUANXINGlingyun** [comment]
![image](https://user-images.githubusercontent.com/109946426/235337340-f7762347-1bbf-4acd-969e-181ed275e5fc.png)
复现成功（调试模式下）
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11360649/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11360651/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11360652/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11360653/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11360654/Log2.txt)

**但还是等我确认下是不是权限的问题

**Comment by 520yunchen** [comment]
> ![图像](https://user-images.githubusercontent.com/109946426/235337340-f7762347-1bbf-4acd-969e-181ed275e5fc.png)复现成功（调试模式下） [log3.txt log4](https://github.com/Hex-Dragon/PCL2/files/11360649/Log3.txt).txt log5.txt [log1.txt](https://github.com/Hex-Dragon/PCL2/files/11360653/Log1.txt) [log2](https://github.com/Hex-Dragon/PCL2/files/11360654/Log2.txt)[.txt](https://github.com/Hex-Dragon/PCL2/files/11360651/Log4.txt)
> 
> ~但还是等我确认下是不是权限的问题~ **好的并不是**

那是怎么回事

**Comment by YUANXINGlingyun** [comment]
这我就不知道了，给个暂时的解决方法：
把你的皮肤文件放置在其他的目录下面，然后再试试导入
~（也就是说猜测是这个目录的特性）~

**Comment by 520yunchen** [comment]
> 这我就不知道了，给个暂时的解决方法： 把你的皮肤文件放置在其他的目录下面，然后再试试导入 ~（也就是说猜测是这个目录的特性）~

没有

**Comment by 520yunchen** [comment]
> 这我就不知道了，给个暂时的解决方法： 把你的皮肤文件放置在其他的目录下面，然后再试试导入 ~（也就是说猜测是这个目录的特性）~

没用

**Comment by Chiloven945** [comment]
未能复现……

**Comment by YUANXINGlingyun** [comment]
**懂了！**
由于 PCL2 在目录中创建并使用 `CustomSkin.png` 来加载自定义皮肤，所以会导致文件名已经是 `CustomSkin.png` 的图片加载失败
或许可以为这个报错写一段专门的提示？

**Comment by 520yunchen** [comment]
> **懂了！** 由于 PCL2 在目录中创建并使用 `CustomSkin.png` 来加载自定义皮肤，所以会导致文件名已经是 `CustomSkin.png` 的图片加载失败 或许可以为这个报错写一段专门的提示？

啥意思

**Comment by LTCatt** [comment]
![image](https://user-images.githubusercontent.com/40348278/235346371-6c3617e7-8381-4127-87aa-7a268e9e3c57.png)
你的电脑里有这个文件夹么……

**Comment by 520yunchen** [comment]
> ![image](https://user-images.githubusercontent.com/40348278/235346371-6c3617e7-8381-4127-87aa-7a268e9e3c57.png) 你的电脑里有这个文件夹么……

好像是没有

**Comment by LTCatt** [comment]
![image](https://user-images.githubusercontent.com/40348278/235352529-8464a533-939e-4024-bbd1-6261df96f402.png)

在文件浏览器的这里输入 %APPDATA% 然后回车，再点一下这个地方，这里显示的路径是什么（
以及，进入的文件夹里有没有 PCL 文件夹

**Comment by 520yunchen** [comment]
C:\Users\韵琛\AppData\Roaming

> ![image](https://user-images.githubusercontent.com/40348278/235352529-8464a533-939e-4024-bbd1-6261df96f402.png)
> 
> 在文件浏览器的这里输入 %APPDATA% 然后回车，再点一下这个地方，这里显示的路径是什么（ 以及，进入的文件夹里有没有 PCL 文件夹
C:\Users\韵琛\AppData\Roaming是这个好像是没有pcl文件夹的

**Comment by 520yunchen** [comment]
就是有没有什么比较好的解决办法
