### ISSUE TITLE
启动器打不开弹出这个怎么解决

### ISSUE THREAD

**Issue by Atriddlc** [Hex-Dragon/PCL2#1747]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃不是 PCL2 的原因，请 **不要** 提交反馈。你可以在 QQ 群里或者论坛找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是游戏本身的问题，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

下完主题快照版启动器打开弹出这个。

### 错误报告、日志与附件

![捕获](https://user-images.githubusercontent.com/132187654/235339123-5b92cc20-9170-4788-a720-561bc646c5ba.PNG)

**Comment by bwtx2023** [comment]
正式版能打开吗？

如果正式版也不能打开，请尝试重装官方原版系统，也可直接升级到 Win10 ，系统会自动替换文件的

**Comment by YUANXINGlingyun** [comment]
根据 `System.Xml.XmlException` 询问下启动器主页菜单的 Custom.xaml 有吗，有的话删掉试试？

**Comment by Atriddlc** [comment]
所以说还是系统文件的问题吗，要更系统吗

**Comment by Atriddlc** [comment]
正式版也打不开

**Comment by Atriddlc** [comment]
@YUANXINGlingyun 去启动器文件夹里找这个然后删掉吗

**Comment by YUANXINGlingyun** [comment]
对的

**Comment by LTCatt** [comment]
这应该是系统环境问题，我没法解决 Orz
试试装个新点的系统吧……

---

@YUANXINGlingyun 如果你不知道解决方案可以不用强行说的，最近几个 issue 你提的解决方案或者假设的问题原因就没有一个是对的……

**Comment by Atriddlc** [comment]
启动器在其他文件夹打开也是这样，不过谢谢各位大佬指点，我改天更系统试试。

**Comment by Atriddlc** [comment]
至少我现在已经知道这跟系统有关系就够了
