### ISSUE TITLE
在版本正在下载时避免误判

### ISSUE THREAD

**Issue by iPodtouch6557** [Hex-Dragon/PCL2#1748]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在下载时点开版本列表，会把下载中的版本误判成错误的版本
检测到如果那个“错误的版本”正在下载时，不把它当成错误版本来对待，而是隐藏
~话说这是bug还是优化~

### 原因

这项优化会避免用户进行错误的检查
要不然就会这样……

<img width="589" alt="捕获" src="https://user-images.githubusercontent.com/118656946/235356547-13cf9851-5ec7-4c4b-a10a-325198b3ad01.PNG">
（图片中的所谓“错误的版本”是正在下载的一个版本，我在尝试复现其他issue时发现的）

**Comment by WorldHim** [comment]
这个算bug吧。因为是把下载中的版本作为错误版本了。

**Comment by YUANXINGlingyun** [comment]
> 这个算bug吧。因为是把下载中的版本作为错误版本了。

这个其实应该算优化，因为这种情况只是因为下载过程中 PCL2 启动器未检测到必要文件（因为还没下好）所以错误

**Comment by iPodtouch6557** [comment]
> > 这个算bug吧。因为是把下载中的版本作为错误版本了。
> 
> 这个其实应该算优化，因为这种情况只是因为下载过程中 PCL2 启动器未检测到必要文件（因为还没下好）所以错误

好了不要辩论了（）

**Comment by Chiloven945** [comment]
> 这个其实应该算优化，因为这种情况只是因为下载过程中 PCL2 启动器未检测到必要文件（因为还没下好）所以错误

显然是一个bug，触发这个bug的时候调试模式会跳出提示报错
当然是bug或否并不重要，能修复才是最重要的

**Comment by iPodtouch6557** [comment]
> > 这个其实应该算优化，因为这种情况只是因为下载过程中 PCL2 启动器未检测到必要文件（因为还没下好）所以错误
> 
> 显然是一个bug，触发这个bug的时候调试模式会跳出提示报错 当然是bug或否并不重要，能修复才是最重要的

我都说了别辩论了，这几种情况我都考虑过（）
