### ISSUE TITLE
无法检索有在中文目录下的java

### ISSUE THREAD

**Issue by wnhlwzx** [Hex-Dragon/PCL2#1749]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在中文目录下，pcl2无法识别java，手动也不行，用pcl挺久了，以前Java目录一直有中文，不知道是那个版本就不行了

### 重现步骤

java在有中文的目录下，使用pcl2搜索java

### 日志与附件

![Plain Craft Launcher 2　 2023_4_30 22_03_43](https://user-images.githubusercontent.com/109027999/235357213-d945f1da-bbda-4551-a2cc-b421635bceba.png)

**Comment by LTCatt** [comment]
上传日志文件

**Comment by IF-desu** [comment]
![image](https://user-images.githubusercontent.com/86994398/235561503-bfefff1a-bb22-44c8-acbc-3bc2c5bb0f7b.png)

**Comment by IF-desu** [comment]
再尝试一下

**Comment by IF-desu** [comment]
> ![image](https://user-images.githubusercontent.com/86994398/235561503-bfefff1a-bb22-44c8-acbc-3bc2c5bb0f7b.png)

关掉 (6)

**Comment by iPodtouch6557** [comment]
我是可以手动导入，但是自动导入搜不到……
另附log看看？（log1从61行看到167行就行）
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11369992/Log1.txt)

**Comment by LTCatt** [comment]
该 issue 将暂时关闭，如有需要请在评论里继续补充出现错误的日志文件
