### ISSUE TITLE
将单个Mod的下载列表中优先列出相同 Mod 加载器的部分

### ISSUE THREAD

**Issue by infidiotWolf** [Hex-Dragon/PCL2#1755]
### 检查项

- [x] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在Mod下载页面中，当点击单个Mod时，其弹出的可选版本会将检索条件中选定的版本移至最上层并展开。
可以通过检索条件中的Mod加载器版本，Mod文件本身的版本（alpha/beta/release) 对其进行进一步排序，而不是仅仅通过更新时间对版本进行排序。

### 原因

如果你也失误将Forge模组下载到Fabric客户端下，你就理解了。

**Comment by Chiloven945** [comment]
![image](https://user-images.githubusercontent.com/116699482/235440068-263aa173-b265-4352-98c1-313cb971dc45.png)
游戏版本根据筛选置顶已支持，但mod加载器置顶还未支持，你可以更改一下issue

**Comment by YUANXINGlingyun** [comment]
Mod 加载器那种有可能实现
但对于 Mod 版本（A/B/R）无法实现，因为API不支持 ~或者说压根就没有检索 A/B/R 的选项啊~

**Comment by LTCatt** [comment]
A/B/R 的排序没啥意义，现在都获取不全 =。=
相同 mod 加载器倒是可以做

**Comment by LTCatt** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/5a7cf6d2-879b-496e-9b87-39f4639b8196)
