### ISSUE TITLE
安装整合包时Optifine的安装与否

### ISSUE THREAD

**Issue by x-yingcan-x** [Hex-Dragon/PCL2#1757]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [x] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在设置里加上安装整合包时关于Optifine的处理：不改变/自动安装/自动清除（并导向镁/铷）/弹窗提示（自己选择）

### 原因

有时候装完整合包才发现optifine被直接安装进去了（而不是作为模组加载），问题是你想装镁/铷，而且你还不能选择是否安装optifine，只能单独下一个客户端然后倒腾文件

**Comment by Chiloven945** [comment]
你可以在mods文件夹内手动删除optifine及optifabric然后再安装钠/镁/铷/iris等等

**Comment by x-yingcan-x** [comment]
（建议先看一眼原因再评论）有时候是optifine直接安装进去了，要在装之前就把整合包文件里optifine那一条删掉

**Comment by Chiloven945** [comment]
optifine只有在没有其他mod加载器的时候才会直接注入进本体，在其他情况均会作为类似于mod加载，至少在PCL上安装版本是这样的
从整合包安装出现这种情况一般就是整合包作者已经将游戏本体准备好了，这时候PCL也无法更改什么东西

**Comment by Chiloven945** [comment]
把这个close了再提交一个应该会好一点……？

**Comment by Chiloven945** [comment]
这个挺离谱的，我不知道为什么forge直接注入到游戏本体里，但是fabric却作为jar包存在……

**Comment by x-yingcan-x** [comment]
反正是确定有这个BUG了，只能说希望早日修复
