### ISSUE TITLE
安装 Forge+Optifine 时会无视 Forge 将 Optifine 注入游戏本体

### ISSUE THREAD

**Issue by x-yingcan-x** [Hex-Dragon/PCL2#1760]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

（猜测）全版本通病，Forge与Optifine一起安装时，Optifine没有作为mod存在，而是直接注入本体

### 重现步骤

1、安装带有 Optifine 的整合包/自动下载随意选一个MC版本，选 Forge+Optifine
2、安装完成后，显示有 Optifine，mods里无 Optifine，或无效（指删除这个模组文件并没有真正删除Optifine）

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11366326/Log1.txt)

**Comment by Chiloven945** [comment]
感觉是安装方法的问题，optifine有两种安装方法，一种是直接注入另一种就是模组加载，forge似乎用的是直接注入
如果是这样的话那么可以加个选择的，因为有可能会出现 #1757 这种问题（

**Comment by Big-Cake-jpg** [comment]
如果 Forge 和 OptiFine 混合安装时 OptiFine 选择了注入安装，可能会导致该核心无法被其他启动器启动。因此，在进行混合安装时，启动器应选择将 OptiFine 作为模组安装。

**Comment by LTCatt** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/035a919e-2978-40eb-8342-9ab6da56a749)
虽然忘了具体是咋回事，但之前已经证实了如果将 OptiFine 作为 Mod 安装，特定版本的 Forge 将无法识别 OptiFine……

@Big-Cake-jpg 理论上这不会导致其他启动器无法启动，因为这并没有对 json 进行破坏性更改，如果出现该问题可以向对应启动器作者提交反馈
