### ISSUE TITLE
MCBBS 整合包规范：服务器自动更新整合包无法正常下载内容

### ISSUE THREAD

**Issue by bwtx2023** [Hex-Dragon/PCL2#1768]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

来自其他启动器创建的 MCBBS v2 整合包在设置了更新服务器 API 地址之后，PCL2 不会自动下载来自更新服务器的文件。

正确的行为应当是检查整合包更新，然后自动更新整合包。（取决于整合包是否设置始终保持最新版本）。

附，若 始终保持整合包为最新版本 设置为 开 ，应当在每次启动该核心之前都检查一遍更新。

### 重现步骤

1. 从其他启动器导出一份带有 更新 API 地址 的 MCBBS v2 整合包文件
2. 在 PCL2 内导入该整合包
3. 检查发现 PCL2 不会自动下载来自服务器的内容，且启动游戏以后依然如此

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11371032/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11371028/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11371029/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11371030/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11371031/Log5.txt)

**Comment by LTCatt** [comment]
由于目前 MCBBS v2 整合包规范缺乏开发文档，在他们那边打算补上文档之前都没法继续制作该规范的额外特性。
