### ISSUE TITLE
Java增加发行版名称/分类，能根据游戏版本设置默认的java而非自动选择

### ISSUE THREAD

**Issue by ANMSakura** [Hex-Dragon/PCL2#1769]
### 检查项

- [x] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

![QQ图片20230502173636](https://user-images.githubusercontent.com/132195516/235632288-d9eedf60-7f9e-4261-ab89-e751c07b1948.png)
👆阴间绘图

### 原因

这项优化让我可以更方便地选取对应的java。
如果没有这项优化，我每次都得看一遍阴间绘图，让操作变得很麻烦。

**Comment by bwtx2023** [comment]
虽然但是，一般没有人会同时安装这么多发行版吧...

**Comment by ANMSakura** [comment]
> 虽然但是，一般没有人会同时安装这么多发行版吧...

的确，但有这种需求的人也的确挺不方便的，正常人都只用Oracle JDK一个也不会因为这个功能有什么变化。不过或许也有人从8到21全下了，也可以自定义分类区分常用和非常用(程序员一般是8,11,17和最新，就可以把11和最新拉进不常用分区里)。然后自定义显示名字倒是可能也有人用到。

**Comment by LTCatt** [comment]
暂时不考虑制作，抱歉（
