### ISSUE TITLE
启动器微软登陆皮肤显示正确，但进入游戏后皮肤显示为原版，重启、重新登陆等无法解决

### ISSUE THREAD

**Issue by chengnanlover** [Hex-Dragon/PCL2#1770]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

启动器微软登陆皮肤显示正确，但进入游戏后皮肤显示为原版，重启、重新登陆等无法解决

### 原因

如果没有这项优化，我每次都必须使用原版皮肤。

**Comment by SuoHouDaiShi** [comment]
这个是因为游戏本身的问题，等待一会就可以加载出来了，也可以安装CustomSkinLoader模组

**Comment by chengnanlover** [comment]
> 

没有用，玩半个小时都一直是原版皮肤，且切换其他版本也是如此

**Comment by bwtx2023** [comment]
上传 Log

**Comment by chengnanlover** [comment]
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11372349/Log4.txt)
[Log5.txt](https://github.com/Hex
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11372354/Log1.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11372355/Log3.txt)
-Dragon/PCL2/files/11372350/Log5.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11372353/Log2.txt)

**Comment by LTCatt** [comment]
网络问题，不在启动器解决范围内
