### ISSUE TITLE
下载minecraft版本时间显示有误

### ISSUE THREAD

**Issue by slientaurora** [Hex-Dragon/PCL2#178]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在minecraft自动安装，手动安装时，版本发行时间显示为xxxx年xx年xx的格式

### 重现步骤

1、点击下载
2、点击自动安装
3、在minecraft版本下载时显示xxxx年xx年xx

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/9692741/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/9692742/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/9692743/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/9692744/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/9692745/Log5.txt)
![image](https://user-images.githubusercontent.com/96624317/193458363-966fd617-118d-4d9d-b6bb-08b74fbe6e1d.png)

**Comment by WTP016-CN** [comment]
请确认 Windows 中区域格式设置是否设置有误

**Comment by slientaurora** [comment]
无误，系正确年月日格式

**Comment by slientaurora** [comment]
![image](https://user-images.githubusercontent.com/96624317/193458773-1c16af41-0a03-4ed2-8c6b-feee838cc82e.png)

**Comment by Big-Cake-jpg** [comment]
问题还存在吗？或者其他人能尝试复现一下吗？

**Comment by slientaurora** [comment]
存在

**Comment by slientaurora** [comment]
内群有个人的是xxxx/xx/xx的形式

**Comment by youzi-2333** [comment]
抱歉在这里插一句
没看过PCL2这部分的源代码，自己也没有出现过这种bug，但是我自己玩vb的时候有过类似的问题，调用Date.Today.ToLongDateString的时候会返回xxxx年xx月xx日的情况
所以这玩意应该不难修吧（

**Comment by LTCatt** [comment]
![image](https://user-images.githubusercontent.com/40348278/198835995-1caa97e0-1728-4b69-a829-9a83e07e2e14.png)

我查了查这一部分的源代码已经准确指定格式了，我不知道为啥会发生这种情况，并且也没法重现。
姑且重新整理了一下这部分的代码，如果这次更新后依然有这个 Bug，可能得远程解决了……

**Comment by slientaurora** [comment]
对了，启动器的个性化能否解锁一下
识别码CA8A-7961-261B-6F74

**Comment by slientaurora** [comment]
不幸的，经过多次更新还是有这个bug，我电脑也换了还是有这问题哈哈哈

**Comment by LTCatt** [comment]
先加我 QQ 1043137532，原因写 issue #178，我看看能不能修

**Comment by LTCatt** [comment]
再次检查了代码，应该只可能是系统问题，不知道咋修，如果有其他人可以复现再说……

**Comment by SALTWOOD** [comment]
也许可以手动实现，不用自带的.ToString？

**Comment by kong-que-dnf123** [comment]
~只能说是“系统的格式在PCL之上了”~
