### ISSUE TITLE
添加刷新正版登录功能

### ISSUE THREAD

**Issue by NotMonika** [Hex-Dragon/PCL2#1782]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

如果一个正版账号登录时间过长，token会失效，导致出现“无效的会话”，只有重启启动器才有用。
可我不想总是重启启动器。
可以添加一个按钮，允许我们自己刷新正版token。

### 原因

我需要这个功能来刷新正版。很多人都有刷新正版的需求，但如果没有这个功能，就不能刷新正版了。

**Comment by xxtg666** [comment]
重启启动器不就几秒钟的事么……

**Comment by iPodtouch6557** [comment]
> 重启启动器不就几秒钟的事么……

但是确实有懒人不愿把这几秒花在重启启动器上~比如我~所以也是有用的

**Comment by LTCatt** [comment]
需要一个 token 失效导致登录失败的 log

**Comment by LTCatt** [comment]
由于超时未回复暂时关闭，若有需要可以继续回复
