### ISSUE TITLE
折叠任意可以折叠的 MyCard，在其回弹时会连带上面的 MyCard 一起回弹

### ISSUE THREAD

**Issue by iPodtouch6557** [Hex-Dragon/PCL2#1783]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如标题
看看视频表述一下

https://user-images.githubusercontent.com/118656946/235849726-3f7c3f14-49ce-4043-8bf9-6b12970e1d71.mp4

### 重现步骤

就像视频一样，可以1:1去还原了做做…

### 日志与附件

[Log.txt](https://github.com/Hex-Dragon/PCL2/files/11380146/Log.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11380147/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11380148/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11380149/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11380150/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11380151/Log5.txt)

**Comment by LTCatt** [comment]
已知，但是很难修，算了 Orz
