### ISSUE TITLE
增加设置搜索功能

### ISSUE THREAD

**Issue by huhujieshuo** [Hex-Dragon/PCL2#1785]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

希望能在设置中加入搜索功能

### 原因

我经常忘记设置的功能位置，如果加入搜索功能就方便些，谢谢！（我恨缓存文件夹设置位置！）

**Comment by youzi-2333** [comment]
缓存文件夹不就是“启动器”里面么……
感觉没多大必要，看龙猫怎么想（

**Comment by huhujieshuo** [comment]
主要是缓存设置就几行，容易被忽略

**Comment by LTCatt** [comment]
没有太大必要……并且还特别难做……算了，抱歉 Orz
