### ISSUE TITLE
将缓存文件夹的设置加入选择界面

### ISSUE THREAD

**Issue by huhujieshuo** [Hex-Dragon/PCL2#1786]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

将缓存文件夹设置时加入选择页面，就像下载时的选择下载位置一样。

### 原因

这项优化让我可以更方便地设置缓存的位置，如果没有这项优化，我每次都必须都复制路径，让操作变得很麻烦。

**Comment by LTCatt** [comment]
考虑到这个文件夹一般也就只会设置一次，似乎没太大必要……
