### ISSUE TITLE
意外地在 舒适物品 Mod 名称后添加了 “全版本” 字样，但该模组并不支持全版本

### ISSUE THREAD

**Issue by WForst-Breeze** [Hex-Dragon/PCL2#1792]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

rt，意外地在 舒适物品 Mod 名称后添加了 “全版本” 字样，但该模组并不支持全版本，仅支持 1.12 及以上版本，疑似 ModData.txt 中出现问题。

*EDIT：去 CF 看了一下，这里的 “全版本” 表达的是这个版本的 Comforts 支持 Fabric/Forge/Quilt **加载器***

### 重现步骤

在资源下载中搜索 舒适物品 即可

### 日志与附件

![image](https://user-images.githubusercontent.com/110760354/236618432-736fefd0-365d-4a3f-a90e-5ca549dd3f3b.png)

**Comment by youzi-2333** [comment]
所以你是打算交 pr 吗（
感觉它写的确实不清楚，容易把 mc 全版本和加载器全版本支持搞混……

**Comment by WForst-Breeze** [comment]
是的（）刚刚交完忘编辑了，已提交 Pr #1793

**Comment by LTCatt** [comment]
已在 #1793 回复
