### ISSUE TITLE
部分mod会不显示加载器

### ISSUE THREAD

**Issue by iPodtouch6557** [Hex-Dragon/PCL2#1797]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

就像这张图
![image](https://user-images.githubusercontent.com/118656946/236628601-bae7d2d4-44b8-4a60-bba2-3c0ea2ac74c9.png)

### 重现步骤

示例
1、在 下载- mod 里搜索“信息显示”
2、往下滚，找到如图的模组

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11412498/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11412499/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11412500/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11412501/Log5.txt)
[Log.txt](https://github.com/Hex-Dragon/PCL2/files/11412502/Log.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11412503/Log1.txt)

###附注

我不知道这是不是mc百科的事……源自 #1793 提交

**Comment by iPodtouch6557** [comment]
~草这标题笑死我了~

**Comment by WForst-Breeze** [comment]
这些旧 Mod 大部分作者在上传的时候没有注明所需的 Mod 加载器，如下图
![image](https://user-images.githubusercontent.com/110760354/236629044-c36075d5-8676-47c2-b330-6b6c2ea1955c.png)
正常情况下是酱紫的：
![image](https://user-images.githubusercontent.com/110760354/236629066-cae7a11e-1ae6-4c20-8606-58e1ee1af86b.png)
所以 PCL2 也不会显示加载器，影响不大，毕竟低版本的**大部分**都是 Forge（）

还有一种情况就是，这个 Mod 支持多个 Mod 加载器，PCL2 也不会显示

**Comment by iPodtouch6557** [comment]
那么……关了？
