### ISSUE TITLE
在下载页面增加Java下载选项

### ISSUE THREAD

**Issue by misividkoukou** [Hex-Dragon/PCL2#1801]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

在下载页面增加Java下载选项，像游戏一样

### 原因

我搜过了，没有，但是真正有没有我不知道，因为我从来没有搜索到我想要的issue（

**Comment by LTCatt** [comment]
如果缺失 Java 现在会自动提示下载，无需手动处理。

**Comment by WForst-Breeze** [comment]
这里先改成拒绝 label 了，要不然有时候搜不着（

**Comment by Cycloneeeeee** [comment]
这样用户可以实行高度个兴化，带来最好的体验
