### ISSUE TITLE
有时PCL2占用内存异常增加

### ISSUE THREAD

**Issue by MJIFmc** [Hex-Dragon/PCL2#1802]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

几个M的PCL2嘛...打开时占100M,开一会变700M,1G的都有,甚至把自己卡崩了
我还是怀疑和音乐播放有关系(?

### 重现步骤

1、打开PCL2,内存占用约为100M
2、十几分钟到几个小时后,出现内存不足"错误,占用超过700M

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11414077/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11414078/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11414079/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11414080/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11414081/Log1.txt)
![截图-错误](https://user-images.githubusercontent.com/110874026/236661458-0c21fa7a-cf8b-497f-9497-5cb7ece65ce9.PNG)
![截图-任务管理器占用](https://user-images.githubusercontent.com/110874026/236661469-7cdcf996-72a4-4329-9575-800a41bf081d.PNG)

**Comment by WForst-Breeze** [comment]
原始 Issue #1659，不播放音乐看看问题是否依然存在

**Comment by iPodtouch6557** [comment]
~我挂机两三个小时边玩花雨庭边放音乐也没卡崩~
我更倾向于这是个人问题，我就没有这类情况

**Comment by LTCatt** [comment]
尝试在关闭音乐播放后看看能不能复现？
因为我这里没法重现，所以只能看你那行不行了 =。=

**Comment by MJIFmc** [comment]
我觉得有可能是因为PCL2和某些应用同时运行导致的,就说我当时开着QQ,QEMU和剪映
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11523960/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11523961/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11523962/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11523963/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11523964/Log2.txt)

**Comment by MJIFmc** [comment]
另外附上我的系统信息:用户： MJIF (管理)
计算机： DESKTOP-UN04KIP
主机： DESKTOP-UN04KIP (192.168.202.1, 192.168.58.1, 192.168.1.103)

系统： Windows 10 Enterprise LTSC 2021 v6.2.9200
系统用户： Windows 用户
系统单位：
系统语言： 3072
系统本地语言： 中文(简体，中国)
系统 ID：

IE 版本： 9.11.19041.0

Socket 描述： WinSock 2.0
Socket 状态： Running

CPU 名称： Intel(R) Core(TM) i5-9500 CPU @ 3.00GHz
CPU 厂家： GenuineIntel
CPU 速度： 2999
CPU 系统、模型、分级： 6, 14, 10
CPUs: 6
CPU 标记：
FPU onboard
Virtual Mode Extension
Debugging Extension
Page Size Extension
Time Stamp Counter
Model Specific Registers
Physical Address Extension
Machine Check Exception
CMPXCHG8 instruction supported
On-chip APIC hardware supported
Fast System Call
Memory Type Range Registers
Page Global Enable
Machine Check Architecture
Conditional Move Instruction Supported
Page Attribute Table
36-bit Page Size Extension
CLFLUSH instruction supported
Debug Store
Thermal Monitor and Software Clock
MMX supported
Fast Floating Point Save and Restore
Streaming SIMD Extensions Supported
Streaming SIMD Extensions 2
Self-Snoop
Thermal Monitor Supported

物理内存总数： 16657040 KB
物理内存可用： 8412124 KB
虚拟内存总数： 2097024 KB
虚拟内存可用： 1955444 KB
页面文件总数： 27667088 KB
页面文件可用： 5483052 KB
使用内存： 49%
PSPR 内存使用： 28680 KB
PSPR 内存页错误： 47903
PSPR 最大使用内存： 28776 KB
PSPR 使用页面文件： 14744 KB
PSPR 最大使用页面文件： 16584 KB

驱动器列表：
C:\ - Fixed, 名称： 'Windows' on NTFS, 总数： 101822 MB, 可用数： 22097 MB
D:\ - Fixed, 名称： '' on NTFS, 总数： 385665 MB, 可用数： 96203 MB

**Comment by LTCatt** [comment]
> 尝试在关闭音乐播放后看看能不能复现？ 因为我这里没法重现，所以只能看你那行不行了 =。=

↑

**Comment by MJIFmc** [comment]
> > 尝试在关闭音乐播放后看看能不能复现？ 因为我这里没法重现，所以只能看你那行不行了 =。=
> 
> ↑
目前的表现全部是在音乐播放开启情况下的,而且详细错误都提到了音乐播放
就说这玩意出现是概率性事件...我先试试

**Comment by MJIFmc** [comment]
> > > 尝试在关闭音乐播放后看看能不能复现？ 因为我这里没法重现，所以只能看你那行不行了 =。=
> > 
> > 
> > ↑
> > 目前的表现全部是在音乐播放开启情况下的,而且详细错误都提到了音乐播放
> > 就说这玩意出现是概率性事件...我先试试



> > 尝试在关闭音乐播放后看看能不能复现？ 因为我这里没法重现，所以只能看你那行不行了 =。=
> 
> ↑

出现了!PCL莫名卡死,提示"程序主时钟错误,内存不足"
(未开音乐播放,但是启动原先可以启动的游戏版本)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11524039/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11524040/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11524041/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11524042/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11524043/Log2.txt)
![捕获](https://github.com/Hex-Dragon/PCL2/assets/110874026/1991d796-c18c-4bcf-99c7-10686e9d2e09)

![启动进度卡的位置](https://github.com/Hex-Dragon/PCL2/assets/110874026/89004c4c-964b-4639-a1de-94d1ee11a18b)

**Comment by MJIFmc** [comment]
程序主时钟出错：引发类型为“System.OutOfMemoryException”的异常。
你的电脑运行内存不足，导致 PCL 无法继续运行。请在关闭一部分不需要的程序后再试。
————————————
详细错误信息：
   在 PCL.ModBase.Log(Exception Ex, String Desc, LogLevel Level, String Title)
   在 PCL.ModMain.TimerMain()
   在 PCL.ModMain._Closure$__._Lambda$__129-0()
错误类型：System.OutOfMemoryException

是否反馈此问题？如果不反馈，这个问题可能永远无法得到解决！
[16:21:42.173] [Control] 按下按钮：反馈
[16:21:42.174] [Control] 普通弹框返回：1
[16:21:42.248] [System] 诊断信息：
操作系统：Microsoft Windows 10 企业版 LTSC
剩余内存：3541 M / 16266 M
DPI：96（100%）
MC 文件夹：C:\Users\MJIF\Desktop\.minecraft\
文件位置：C:\Users\MJIF\Desktop\
[16:21:42.248] [System] 执行外部命令：explorer.exe "C:\Users\MJIF\Desktop\PCL\"
[16:21:42.299] [System] 正在打开网页：https://github.com/Hex-Dragon/PCL2/issues/
[16:21:52.885] [Net] 获取网络结果：https://meta.fabricmc.net/v2/versions，最大超时 30000
[16:22:36.644] [Loader] 加载器 DlFabricList Bmclapi 状态改变：Loading
[16:22:36.644] [Net] 获取网络结果：https://bmclapi2.bangbang93.com/fabric-meta/v2/versions，最大超时 10000
[16:22:36.706] [Net] 获取网络结果：https://meta.fabricmc.net/v2/versions，最大超时 4000
[16:22:37.190] [Loader] 加载器 DlFabricList Bmclapi 状态改变：Finished
[16:22:37.192] [Loader] 加载器 DlFabricList Official 状态改变：Aborted
[16:22:37.192] [Loader] 加载器 DlFabricList Main 状态改变：Finished
[16:22:47.397] [Loader] 加载线程 DlFabricList Official (60) 已中断但线程正常运行至结束，输出被弃用（最新线程：-1）

**Comment by LTCatt** [comment]
PCL 的内存占用是多少？看日志像是启动 MC 才导致内存满的

**Comment by LTCatt** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/7f1a1f7e-60e5-483f-bd4e-f27d2a53b130)
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/7bac62d9-72cc-401e-b269-bdb95225bed5)
启动 MC 时的这个 15G 内存分配是你自己调的吧……这不崩才怪……

考虑到至今没有任何人能够复现音乐播放时内存占用增大的情况，暂时关闭，如果有其他人能复现再处理。
