### ISSUE TITLE
关于崩溃日志查看问题

### ISSUE THREAD

**Issue by HappyMC-Dev** [Hex-Dragon/PCL2#1803]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

当minecraft崩溃后，PCL会进行崩溃分析，那么在崩溃分析会话窗口弹出前，再次点击启动游戏。那么崩溃分析会话弹出后（划重点），点击查看日志，那么就不是崩溃的Minecraft日志，而是刚启动的Minecraft的日志。

### 重现步骤

1、点击启动游戏
2、（启动完成）想办法把Minecraft搞崩溃
3、（Minecraft崩溃，PCL进行分析）在分析结束前，再次点击启动游戏
4、（PCL重新启动游戏）（崩溃分析会话窗口弹出）点击查看日志
5、（弹出xxx.log，那么可以发现这个并不是崩溃的Minecraft日志，而是重新启动的Minecraft的日志）

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11414110/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11414111/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11414112/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11414113/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11414115/Log1.txt)

**Comment by LTCatt** [comment]
技术上无法解决。
