### ISSUE TITLE
安装 Forge 时疑似没有正确预下载 Relams Jar

### ISSUE THREAD

**Issue by sdtthdsr7u** [Hex-Dragon/PCL2#1805]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

下载 Forge 27.0.60失败
→ 安装 Mod 加载器（方式 A）失败
→ 安装新 Forge 版本失败
→ Forge 安装器出错，日志结束部分为：
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60)
	at oolloo.jlw.Wrapper.main(Wrapper.java:53)
   在 PCL.ModDownloadLib._Closure$__36-0._Lambda$__7(LoaderTask`2 Task)
   在 PCL.ModLoader.LoaderTask`2._Closure$__12-0._Lambda$__0()
   在 PCL.ModDownloadLib.ForgeInjector(String Target, LoaderTask`2 Task, String McFolder)
   在 PCL.ModDownloadLib._Closure$__36-0._Lambda$__7(LoaderTask`2 Task)

### 重现步骤

用自动下载下带forge的1.14.3，失败，其他版本的都可以，hmcl也正常

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11414417/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11414418/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11414419/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11414420/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11414421/Log2.txt)

**Comment by hejiehao** [comment]
你这个应该是网络不好

**Comment by sdtthdsr7u** [comment]
什么叫没有正确预下载

**Comment by sdtthdsr7u** [comment]
是在安装mod加载器方式a时出错

**Comment by LTCatt** [comment]
已确认这是 Forge 安装过程的问题，这会导致 1.14.3 Forge 可能无法安装， **但已在 1.14.4 Forge 中修复** ，因此不作处理
