### ISSUE TITLE
替换购买minecraft的链接

### ISSUE THREAD

**Issue by deep-dark-forest** [Hex-Dragon/PCL2#1806]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

MC已经锁国区了，在国内MC官网买不了minecraft了.......干脆移除得了
![image](https://user-images.githubusercontent.com/131975043/236670835-0774a0d8-5939-4a31-8662-8da1354115e3.png)

### 原因

minecraft官网已经无法购买正版MC，点链接进去也是白跑一趟

**Comment by WForst-Breeze** [comment]
换到 [Xbox 的购买链接](https://www.xbox.com/zh-cn/games/store/minecraft-java-bedrock-edition-for-pc/9nxp44l49shj)应该可以考虑，移除基本不可能，看看龙猫怎么想吧

**Comment by deep-dark-forest** [comment]
> 换到 [Xbox 的购买链接](https://www.xbox.com/zh-cn/games/store/minecraft-java-bedrock-edition-for-pc/9nxp44l49shj)应该可以考虑，移除基本不可能，看看龙猫怎么想吧

Xbox那边也不太行了，至少用支付宝无法完成购买......

**Comment by deep-dark-forest** [comment]
我也要活力橙（
89E8-175A-58E2-01FC

**Comment by deep-dark-forest** [comment]
额我这个算bug吗？如果是的话给个活跃橙呗

**Comment by LTCatt** [comment]
勉强算吧 =。=

你的解锁码：Vb5Sm74/vEi2snfnMw+lpenab4IyX/gy
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
