### ISSUE TITLE
“你知道吗”条目修改

### ISSUE THREAD

**Issue by TheXiaoma** [Hex-Dragon/PCL2#1808]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

由于正版登录界面已更改，故"你知道吗"当中的“右键头像可以更换皮肤”应当更改为新的方法或删除

### 原因

避免对他人造成不必要的误导

**Comment by TheXiaoma** [comment]
可以拿个活跃橙吗qwq

**Comment by WForst-Breeze** [comment]
> 可以拿个活跃橙吗qwq

待此 Issue 处理完成后，发送识别码即可获取活跃橙

**Comment by LTCatt** [comment]
你的解锁码：fex9HkP6HA25KT1PkM8KKZt3DG6YZo1u
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by deep-dark-forest** [comment]
这个为啥算bug？

**Comment by iPodtouch6557** [comment]
> 这个为啥算bug？

因为这是一个开发者的疏忽……可以算bug

**Comment by deep-dark-forest** [comment]
> > 这个为啥算虫？
> 
> 因为这是一个开发者的疏忽......可以算虫

那我[1806](https://github.com/Hex-Dragon/PCL2/issues/1806)为啥不能算bug？

**Comment by deep-dark-forest** [comment]
> > > 这个为啥算虫？
> > 
> > 
> > 因为这是一个开发者的疏忽......可以算虫
> 
> 那我[1806](https://github.com/Hex-Dragon/PCL2/issues/1806)为啥不能算bug？

“你知道吗”是因为mojang修改了皮肤系统然后才导致过时的，算bug；但是我[1806](https://github.com/Hex-Dragon/PCL2/issues/1806)是因为微软把MC锁国区才导致以前的链接用不了了，为啥我不能算bug？

**Comment by iPodtouch6557** [comment]
> > > > 这个为啥算虫？
> > > 
> > > 
> > > 因为这是一个开发者的疏忽......可以算虫
> > 
> > 
> > 那我[1806](https://github.com/Hex-Dragon/PCL2/issues/1806)为啥不能算bug？
> 
> “你知道吗”是因为mojang修改了皮肤系统然后才导致过时的，算bug；但是我[1806](https://github.com/Hex-Dragon/PCL2/issues/1806)是因为微软把MC锁国区才导致以前的链接用不了了，为啥我不能算bug？

你自己交的优化，我可不背锅……其实你那个能算bug，是你自己交的有问题
还有，此类无关话题少一点，易被锁conversation

**Comment by deep-dark-forest** [comment]
> > > > > 这个为啥算虫？
> > > > 
> > > > 
> > > > 因为这是一个开发者的疏忽......可以算虫
> > > 
> > > 
> > > 那我[1806](https://github.com/Hex-Dragon/PCL2/issues/1806)为啥不能算bug？
> > 
> > 
> > “你知道吗”是因为mojang修改了皮肤系统然后才导致过时的，算bug；但是我[1806](https://github.com/Hex-Dragon/PCL2/issues/1806)是因为微软把MC锁国区才导致以前的链接用不了了，为啥我不能算bug？
> 
> 你自己交的优化，我可不背锅……其实你那个能算bug，是你自己交的有问题 还有，此类无关话题少一点，易被锁conversation

但是，这个issue交的优化，龙猫把优化label换成了bug标签......

**Comment by WForst-Breeze** [comment]
此 Issue 处理工作已完成，请避免讨论无关内容，否则此 issue 将被锁定。感谢您的理解

**Comment by Chiloven945** [comment]
请不要多次quote，已经quote了五次了……
