### ISSUE TITLE
右下角下载圆钮存在色差

### ISSUE THREAD

**Issue by Xiao-laoshu** [Hex-Dragon/PCL2#1814]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在下载Mod等资源时，右下角的下载“↓”圆形图标存在色差，指上半圆与下半圆存在细节性颜色偏差（具体图片如图）

### 重现步骤

①下载任意资源时弹出的右下角下载圆钮存在色差
②若不重启应用，切换主题无法使显示正常
③重启应用能恢复正常显示，但有概率复现

### 日志与附件

[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11415270/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11415271/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11415272/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11415273/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11415274/Log3.txt)
![图片2](https://user-images.githubusercontent.com/132833140/236685101-1cb1a04d-305f-48d1-a67a-e3594c58c105.png)
![图片3](https://user-images.githubusercontent.com/132833140/236685102-d76c1f4a-7d67-45ab-9a80-7aa31595874e.png)
![图片4](https://user-images.githubusercontent.com/132833140/236685105-21f17361-0c50-4105-9e8b-9a07db82ece3.png)

**Comment by WForst-Breeze** [comment]
这是个进度条（

**Comment by Chiloven945** [comment]
你是不是看不到他在动（
