### ISSUE TITLE
在下载 版本/整合包 时不在版本列表里显示

### ISSUE THREAD

**Issue by 212112111zwl** [Hex-Dragon/PCL2#1815]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [ ] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

貌似记得有人提到过，但记不清了.jpg

下载整合包/版本时，会在版本列表里也显示此版本，而且有时对该版本分类和描述错误，会造成歧义。
（正在下载RLcraft时，版本列表错误地显示其为原版minecraft）

可以等安装好整合包/版本后再在版本列表里显示

### 原因

见上

**Comment by WForst-Breeze** [comment]
#1748？两者描述的情况有些差异，不过感觉整体意思差不多，此 Issue 提及内容可以作为其解决方案参考之一，先开着（

**Comment by 212112111zwl** [comment]
> 我眼睁睁看你把那个复选框取消了，一点也不夸张
不全选就提交不了issue呀……

**Comment by iPodtouch6557** [comment]
> > 我眼睁睁看你把那个复选框取消了，一点也不夸张
> 
> 不全选就提交不了issue呀……

不可能，我就见过不勾复选框就交issue的小天才

**Comment by WForst-Breeze** [comment]
不勾选检查项无法提交 issue，除非反馈者进行编辑。

也烦请二位尽可能减少讨论无关内容，否则此 Issue 可能会被锁定😕
