### ISSUE TITLE
【优化建议】优化切换正版账户流程

### ISSUE THREAD

**Issue by WForst-Breeze** [Hex-Dragon/PCL2#1825]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

> 原始 Discussion #1824 by @Terlity，正好我的想法和这位朋友雷同（笑）就正好交个 Issue~

允许单击头像**直接可以进入**账户列表并进行账号切换&添加账号操作，而避免进行 **先点击右下角的切换账户图标->单击下拉框->选择目标账户** 的繁琐操作。

或许可以做成类似这样的……？简单用帮助页面做了一个粗糙的示例，具体的设计决定您可以再考虑考虑
![image](https://github.com/Hex-Dragon/PCL2/assets/110760354/ddcbfd3b-e2a0-4952-9318-a0f8aa52dc99)

### 原因

绝大部分多账户玩家用户迫切需要。

现在的操作流程体验下来整体感觉有一些奇怪，也有一些繁琐，或许可以通过以上想法实现优化切换流程、简化操作步骤的目的。

**Comment by mcwuguodadi** [comment]
看起来确实方便了一些

**Comment by LTCatt** [comment]
不会加单独的界面，但确实还能优化一下……下个版本我再寻思寻思

**Comment by KaoYUG** [comment]
或许可以在启动页的空白区域加个菜单……？
![image](https://github.com/Hex-Dragon/PCL2/assets/112395666/ea78f3ae-8543-44c9-9cf9-fc21c60a2565)

**Comment by iPodtouch6557** [comment]
这不好……我们还指望自定义主页呢

**Comment by KaoYUG** [comment]
> 这不好……我们还指望自定义主页呢

或许可以改成像设置、更多那样滚动式的，能装很多版块的那种

**Comment by mcwuguodadi** [comment]
> 这不好……我们还指望自定义主页呢

点击切换账号按钮之后空白区域出现一个彩蛋列着可以切换的账号，然后背景变暗，点击菜单以外的地方或者选择任意一个账号收起菜单，这样不就不会影响自定义主页了？

**Comment by KaoYUG** [comment]
> > 这不好……我们还指望自定义主页呢
> 
> 点击切换账号按钮之后空白区域出现一个菜单列着可以切换的账号，背景变暗，点击菜单以外的地方或者选择任意一个账号收起菜单，这样不就不会影响自定义主页了？

或者直接加到这里，做个滚动式的头像+用户名菜单
![image](https://github.com/Hex-Dragon/PCL2/assets/112395666/4ed64905-9fc6-4702-843f-f3fbfd64ee27)

**Comment by Chiloven945** [comment]
> > 这不好……我们还指望自定义主页呢
> 
> 或许可以改成像设置、更多那样滚动式的，能装很多版块的那种

给旁边塞太多东西反倒会显得拥挤冗余

**Comment by Chiloven945** [comment]
如果要把切换账号做到单机玩家头像的话那么其他两个换皮肤和修改信息也得做进去，因为这三个是同级的关系，只把账号切换做进去感觉有点不平衡的样子……

**Comment by FangFuJi1991** [comment]
做成像steam那样子的点击头像登录（？
![image](https://github.com/Hex-Dragon/PCL2/assets/103358064/4ea45972-254e-4580-84d6-dd4aa4274f7e)

**Comment by Bunnui** [comment]
做也一个管理账户的窗口，管理账户的时候直接占用整个界面，左上角弄个返回就行。在启动的时候从列边框中选中一个账户

**Comment by Bunnui** [comment]
类似于这种的窗口，主页添加一个账户相关的按钮，点击就切换到账户管理器界面
![image](https://github.com/Hex-Dragon/PCL2/assets/37466008/8da0e594-3216-4601-bc5d-23a604941ae1)

**Comment by Bunnui** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/37466008/0fda444a-ad9e-4cff-9722-00f31b34f86d)

**Comment by WTP016-CN** [comment]
可以参考一下隔壁 BakaXL 的（
我觉得做的挺不错的
![图片](https://github.com/Hex-Dragon/PCL2/assets/66893541/869d452c-6951-4925-bb8d-d507e32cacd8)

**Comment by SALTWOOD** [comment]
> 这不好……我们还指望自定义主页呢

加个弹出式菜单，类似版本设置页面
