### ISSUE TITLE
关于微软正版登入

### ISSUE THREAD

**Issue by angelkawaii4** [Hex-Dragon/PCL2#1826]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

当我退出登入后，重新登入时，出现年龄限制，但微软网站并无显示年龄低于18

### 重现步骤

1、点击切换账号
2、重新登入刚刚的账号
3、出现年龄限制提示

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11460062/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11460063/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11460066/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11460068/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11460069/Log5.txt)

**Comment by LTCatt** [comment]
年龄限制提示并非启动器可以解决，这是微软提供的反馈
