### ISSUE TITLE
1.PCL内存占用实在过大，动画效果不好

### ISSUE THREAD

**Issue by HanXiaozeng** [Hex-Dragon/PCL2#1830]
### 检查项

- [x] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

为何说它占用内存过大？1个四点多kb的软件占用内存实在太大吧...
动画效果:如果说打开其他占用内存高的应用的话，pcl的动画效果就像卡成ppt了！建议修改！
![屏幕截图 2023-05-12 210628](https://github.com/Hex-Dragon/PCL2/assets/110365422/778d3515-954c-49e1-915a-ec687df49cb1)

### 原因

没啥...

**Comment by WForst-Breeze** [comment]
近期出现了多例反应 PCL2 内存占用过大的反馈（#1659，#1802，#1830）

**Comment by mcwuguodadi** [comment]
麻烦上传一下日志以供进一步排查

**Comment by iPodtouch6557** [comment]
我还是那句话：我更倾向于是个人问题，我没这情况

**Comment by iPodtouch6557** [comment]
那么把1802先关了吧……把它归并到这里

**Comment by Big-Cake-jpg** [comment]
7161.9 MB 约等于 7 GB，请检查 PCL2 的子进程列表内是否存在与 Java / JDK / Zulu 有关的进程或 Minecraft 是否为刚刚启动。

以及，每个反馈只应当提及一个问题以方便龙猫与协作者处理，如“内存占用量异常升高”应属于“Bug 反馈”，“动画效果优化”应属于“优化”类别。

**Comment by Chiloven945** [comment]
标题建议更改为“PCL内存异常占用”
还有就是不要在标题加1.什么的，动画效果也是内存占用异常的问题所以说不需要在标题特殊说明

**Comment by LTCatt** [comment]
这个内存占用应该是任务管理器把 MC 的内存算到 PCL 上导致的……
考虑到提交者没有上传日志，也没有补充日志，无法确认原因，暂时关闭。

**Comment by MJIFmc** [comment]
> 这个内存占用应该是任务管理器把 MC 的内存算到 PCL 上导致的…… 考虑到提交者没有上传日志，也没有补充日志，无法确认原因，暂时关闭。
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11523948/Log2.txt)

这就离谱了...我完全没有打开任何MC,就拿来放音乐,仍然出现问题,我可以上传日志
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11523950/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11523951/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11523954/Log5.txt)

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11523953/Log1.txt)
我觉得有可能是因为PCL2和某些应用同时运行导致的,就说我当时开着QQ,QEMU和剪映

**Comment by MJIFmc** [comment]
另外附上我的系统信息:用户： MJIF (管理)
计算机： DESKTOP-UN04KIP
主机： DESKTOP-UN04KIP (192.168.202.1, 192.168.58.1, 192.168.1.103)

系统： Windows 10 Enterprise LTSC 2021 v6.2.9200
系统用户： Windows 用户
系统单位： 
系统语言： 3072
系统本地语言： 中文(简体，中国)
系统 ID： 

IE 版本： 9.11.19041.0

Socket 描述： WinSock 2.0
Socket 状态： Running

CPU 名称： Intel(R) Core(TM) i5-9500 CPU @ 3.00GHz
CPU 厂家： GenuineIntel
CPU 速度： 2999
CPU 系统、模型、分级： 6, 14, 10
CPUs: 6
CPU 标记：
	FPU onboard
	Virtual Mode Extension
	Debugging Extension
	Page Size Extension
	Time Stamp Counter
	Model Specific Registers
	Physical Address Extension
	Machine Check Exception
	CMPXCHG8 instruction supported
	On-chip APIC hardware supported
	Fast System Call
	Memory Type Range Registers
	Page Global Enable
	Machine Check Architecture
	Conditional Move Instruction Supported
	Page Attribute Table
	36-bit Page Size Extension
	CLFLUSH instruction supported
	Debug Store
	Thermal Monitor and Software Clock
	MMX supported
	Fast Floating Point Save and Restore
	Streaming SIMD Extensions Supported
	Streaming SIMD Extensions 2
	Self-Snoop
	Thermal Monitor Supported

物理内存总数： 16657040 KB
物理内存可用： 8412124 KB
虚拟内存总数： 2097024 KB
虚拟内存可用： 1955444 KB
页面文件总数： 27667088 KB
页面文件可用： 5483052 KB
使用内存： 49%
PSPR 内存使用： 28680 KB
PSPR 内存页错误： 47903
PSPR 最大使用内存： 28776 KB
PSPR 使用页面文件： 14744 KB
PSPR 最大使用页面文件： 16584 KB

驱动器列表：
	C:\ - Fixed, 名称： 'Windows' on NTFS, 总数： 101822 MB, 可用数： 22097 MB
	D:\ - Fixed, 名称： '' on NTFS, 总数： 385665 MB, 可用数： 96203 MB

**Comment by LTCatt** [comment]
@MJIFmc 大哥，你的 issue 在 #1802 啊，你去那里补充啊，去其他人的 issue 下面补充干啥

**Comment by MJIFmc** [comment]
> @MJIFmc 大哥，你的 issue 在 #1802 啊，你去那里补充啊，去其他人的 issue 下面补充干啥

OK我这就去

**Comment by MJIFmc** [comment]
> ### 检查项
> * [x]  我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
> * [x]  我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
> * [x]  我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。
> 
> ### 描述
> 为何说它占用内存过大？1个四点多kb的软件占用内存实在太大吧... 动画效果:如果说打开其他占用内存高的应用的话，pcl的动画效果就像卡成ppt了！建议修改！ ![屏幕截图 2023-05-12 210628](https://user-images.githubusercontent.com/110365422/237979765-778d3515-954c-49e1-915a-ec687df49cb1.png)
> 
> ### 原因
> 没啥...

可以看看你具体打开了其他什么应用
