### ISSUE TITLE
播放音乐时默认播放最新加入的音乐文件

### ISSUE THREAD

**Issue by iPodtouch6557** [Hex-Dragon/PCL2#1831]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

如题，这玩意不要再加一个复选框了吧……

### 原因

这样可以让我更方便听到自己最新加的音乐
很多人都习惯把新音乐文件拖进 music 文件夹后马上打开 PCL 听音乐，而且他们往往希望可以优先听到自己最新加的音乐

**Comment by LTCatt** [comment]
意义不大，算了 =。=
