### ISSUE TITLE
垃圾清理小问题

### ISSUE THREAD

**Issue by hellominecraftlauncher** [Hex-Dragon/PCL2#1835]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

这个清理垃圾有的时候莫名清理了1234个垃圾，我没怎么玩游戏，怎么游戏还多日志了，所以我疑似是PCL的检测垃圾的时候出了点问题

### 原因

优化可以让PCL检测垃圾的时候不会莫名的增多

**Comment by LTCatt** [comment]
它清理了这么多就是这么多……不要揣测这个有 Bug，然后又没有日志没有复现方法
