### ISSUE TITLE
运行游戏时显示”检查Minecraft窗口失败“

### ISSUE THREAD

**Issue by AuroralMoss** [Hex-Dragon/PCL2#1836]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如题, 弹出显示如下日志中错误的弹窗时游戏已正常运行, 关闭弹窗后方正常弹出"成功启动".

### 重现步骤

这似乎不是普遍问题, 但无法确认是否由于我的本地问题造成, 在打开任意版本时, 在我的PCL2客户端上这一问题都会出现.

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11468774/Log1.txt)

**Comment by Chiloven945** [comment]
```
[11:13:45.357] 检查 Minecraft 窗口失败：ID 为 1155964 的进程当前未运行。
   在 System.Diagnostics.Process.GetProcessById(Int32 processId, String machineName)
   在 PCL.ModWatcher.Watcher._Closure$__24-0._Lambda$__0(IntPtr hwnd, Int32 lParam)
   在 PCL.ModWatcher.Watcher.EnumWindows(EnumWindowsSub hWnd, Int32 lParam)
   在 PCL.ModWatcher.Watcher.TryGetMinecraftWindow()
   在 PCL.ModWatcher.Watcher.TimerWindow()
错误类型：System.ArgumentException
```

**Comment by LTCatt** [comment]
应当是本地权限问题导致，PCL 无法获取正确的 PID……加了个临时补丁，之后至少不会报错了，大概
