### ISSUE TITLE
启动后快速取消会直接触发游戏崩溃

### ISSUE THREAD

**Issue by hellominecraftlauncher** [Hex-Dragon/PCL2#1838]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。
- 补充：我立马发现启动时候关闭PCL游戏的脚本会继续运行，所以如果参数没有变动，PCL就直接运行脚本文件了

### 描述

目前仅在fabric1.16.5遇到，启动瞬间我点取消，PCL直接检测游戏报错，没有可分析的文件
另外，这个bug的概率约在23%左右，能修就修吧。另外，如果快速取消，游戏依旧会启动（实验第三次后游戏窗口弹出）

### 重现步骤

下一个带fabric和API的1.16.5
启动游戏瞬间取消掉
左下角显示已取消启动/检测到游戏崩溃，错误分析已开始

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11468838/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11468839/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11468840/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11468841/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11468842/Log5.txt)

**Comment by Chiloven945** [comment]
未能复现……

**Comment by LTCatt** [comment]
上传的日志中没有启动任何游戏的记录，请上传有效的日志
