### ISSUE TITLE
启动的设置小bug

### ISSUE THREAD

**Issue by hellominecraftlauncher** [Hex-Dragon/PCL2#1839]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

根据我1分前的问题，我立马发现启动时候关闭PCL游戏的脚本会继续运行，所以如果参数没有变动，PCL就直接运行脚本文件了

### 原因

没什么大问题，主要针对某些时候PCL被强制关闭（像alt+f4这样的）后log被占用无法写入日志

**Comment by iPodtouch6557** [comment]
这是bug，不要乱交category

**Comment by hellominecraftlauncher** [comment]
> 这是bug，不要乱交category

我是根据我的想法提交的，有时候不准确

**Comment by LTCatt** [comment]
请使用修改功能将内容合并到 #1838
