### ISSUE TITLE
JVM参数输入框大小自适应

### ISSUE THREAD

**Issue by Anythingteam** [Hex-Dragon/PCL2#1840]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

JVM参数输入框大小自适应，默认为1行，输入框会随着输入字符的增加而拓展高度，可以设定某个停止自适应的极限行数（比如20行），更加方便观看

### 原因

这项优化让我可以更方便地查看JVM参数

**Comment by LTCatt** [comment]
现有 UI 框架不咋好做

**Comment by iPodtouch6557** [comment]
又双叒叕……
![image](https://github.com/Hex-Dragon/PCL2/assets/118656946/74d7897d-4372-4c33-89a7-1fd226910c40)
