### ISSUE TITLE
对联机功能的亿点小建议

### ISSUE THREAD

**Issue by SYSTEMWEBMONKEY** [Hex-Dragon/PCL2#1844]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

（不是广告！！！）联机其实就是将游戏开放在局域网内的某个端口上，如果你有公网IP的话......醒醒，别做梦了，普通人怎么可能有公网IP呢？有种东西叫做内网穿透，可以将某个端口映射到公网上，从而达到公网的效果。如果能调用一个内网穿透服务商的API的话，那是不是能联机了呢......当然行！我找到一个叫做MossFrp的内网穿透，就有自己的API，还可以调用，API文档详见https://github.com/MossFrp/MossFrpBackend-Docs/blob/main/APIDOC.yml
最重要的：免费！免费！免费！
主要靠自己签到获得积分来进行穿透
我想对龙腾猫跃说：可以进Q群1072507973或找3501103680了解一下

### 原因

我需要这个功能来联机。很多人都有和小伙伴一起玩的需求，但如果没有这个功能，就不能联机了。

**Comment by SYSTEMWEBMONKEY** [comment]
这个办法是能行得通的，有一个开服器（魔改一下就能变成联机模块）就是用的MossFrpAPI，延迟挺低，行得通

**Comment by SYSTEMWEBMONKEY** [comment]
期望猫猫能做这个功能

**Comment by bwtx2023** [comment]
Octo Network 不依赖于第三方 Frp 方案，而是使用自有 P2P + Relay 方案

在做了在做了.jpg

**Comment by SYSTEMWEBMONKEY** [comment]
OOK

**Comment by SYSTEMWEBMONKEY** [comment]
> Octo Network 不依赖于第三方 Frp 方案，而是使用自有 P2P + Relay 方案
> 
> 在做了在做了.jpg

捉到你了

**Comment by SYSTEMWEBMONKEY** [comment]
> 

其实我觉得免费高效最重要awawawawawawa

**Comment by SYSTEMWEBMONKEY** [comment]
你同意我的思路吗
@bwtx2023

**Comment by WForst-Breeze** [comment]
方法思路可行，不过很遗憾 PCL2 的联机核心暂时不会考虑使用您提及的相关技术😥 感谢您对 PCL2 的热心建议与支持🥳

**Comment by iPodtouch6557** [comment]
你这人不会讲话啊，能不能用一下edit……还有不要乱@，也不要乱awa
~而且龙猫和猫猫是两个人，猫猫是那个做了IOI然后乱搞付费的那个~

**Comment by LTCatt** [comment]
@WForst-Breeze 不用太敏感，没有明显违规的留着就行 =。=
