### ISSUE TITLE
下载mod时版本下拉菜单版本不全

### ISSUE THREAD

**Issue by HHWMR** [Hex-Dragon/PCL2#1845]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

进入mod下载页面，下拉版本版本菜单，显示不完整
![image](https://github.com/Hex-Dragon/PCL2/assets/123556110/2463f47c-7699-48f1-b444-70e19c7797d5)

### 重现步骤

进入mod下载页面，下拉版本版本菜单

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11469663/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11469664/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11469665/Log5.txt)
[Log.txt](https://github.com/Hex-Dragon/PCL2/files/11469666/Log.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11469667/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11469668/Log2.txt)

**Comment by WForst-Breeze** [comment]
您指的 显示不完整 具体是什么呢🤔
