### ISSUE TITLE
下载的版本无法改名，会提示访问被拒绝

### ISSUE THREAD

**Issue by jeremysun0324** [Hex-Dragon/PCL2#1846]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

下载的版本无法改名，会提示 D:\.minecraft\versions\1.19.2-服务器端\”的访问被拒绝。
   在 PCL.PageVersionOverall.BtnDisplayRename_Click(Object sender, EventArgs e)
错误类型：System.IO.IOException

### 重现步骤

1.下载一个版本
2.尝试更改他的版本名

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11469727/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11469728/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11469729/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11469730/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11469731/Log2.txt)

**Comment by iPodtouch6557** [comment]
必须下载后马上改名是吗

**Comment by LTCatt** [comment]
“访问被拒绝” 是系统或者其他软件拒绝了 PCL 的访问，并非 PCL 的问题 :/
