### ISSUE TITLE
当多个下载任务进行时无法关闭失败的下载任务

### ISSUE THREAD

**Issue by Chiloven945** [Hex-Dragon/PCL2#1848]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

当多个下载任务中有一个下载任务失败时无法关闭失败的下载任务
![屏幕录制-2023-05-14-105000](https://github.com/Hex-Dragon/PCL2/assets/116699482/dfae684d-a0e7-4723-9218-07c2d0459592)

### 重现步骤

1.开始多个下载任务
2.使其中一个下载任务失败
3.尝试关闭该下载任务

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11471009/Log1.txt)
日志的最后面

**Comment by mcwuguodadi** [comment]
![QQ截图20230514105859](https://github.com/Hex-Dragon/PCL2/assets/82522552/e6e0d373-c0ea-47e9-be26-3e2daef18604)

稳定复现，感谢反馈~
