### ISSUE TITLE
在高分辨率高dpi的情况下，启动器启动图标和动画没有缩放，但启动器界面正常

### ISSUE THREAD

**Issue by iranftoy** [Hex-Dragon/PCL2#1852]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在高分辨率高dpi的情况下，启动器启动图标和动画没有缩放，但启动器界面正常
希望启动时的图标能适配屏幕分辨率和dpi，并且正常缩放

### 原因

我是4k的屏幕，dpi 250%，每次启动看到图标都很难受

**Comment by youzi-2333** [comment]
我没有 4k 屏幕，也没有 250% 那么高的 DPI……
感觉是 WPF 的问题。

**Comment by LTCatt** [comment]
WPF 的 Bug，无法修复 :/
