### ISSUE TITLE
无法安装 MultiMC 整合包

### ISSUE THREAD

**Issue by pangzong2011** [Hex-Dragon/PCL2#1853]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在导入整合包后，图标和版本归类为原版
但之后又显示为fabric版本，启动为原版

### 重现步骤

导入该整合包，等待导入完毕（后面我也不清楚是不是重现的步骤）
下载，手动安装包，点击了fabric安装，返回版本选项，归类为fabric版本
但该版本游玩时为原版
hmcl导入的整合包
整合包获取加我QQ:783885990

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11471233/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11471235/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11471236/Log5.txt)
[Log.txt](https://github.com/Hex-Dragon/PCL2/files/11471237/Log.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11471238/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11471239/Log2.txt)

**Comment by WForst-Breeze** [comment]
PCL2 貌似无法成功安装 MultiMC 整合包，大致表现为无法安装模组加载器。
使用 MultiMC 进行安装并启动游戏，一切正常。

**Comment by LTCatt** [comment]
可以将整合包传到网盘 =。=

**Comment by pangzong2011** [comment]
https://share.weiyun.com/JFK8akTN

**Comment by pangzong2011** [comment]
F76B-E983-9108-E9D9 解锁活跃橙
阿巴阿巴阿巴阿巴

**Comment by iPodtouch6557** [comment]
标记为完成后即可取码qwq
