### ISSUE TITLE
报错弹窗优化

### ISSUE THREAD

**Issue by pangzong2011** [Hex-Dragon/PCL2#1855]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在被任务管理器所结束的mc进程后
pcl2弹出窗口表示mc出现了错误，这是你自己导致的错误，就大概作成这个样子
![QQ图片20230514140856](https://github.com/Hex-Dragon/PCL2/assets/127648649/a844f7c0-8d5d-44b5-9d6c-741f27990d28)
或者就不显示出现错误的弹窗，阿巴阿巴

### 原因

按照原先的设计可能会被其他人错误的认为mc出现了问题

**Comment by LTCatt** [comment]
这是 MC 认定的手动触发的崩溃，PCL 只是把它显示出来而已 =。=
