### ISSUE TITLE
将自定义主页分为离线与在线模式

### ISSUE THREAD

**Issue by youzi-2333** [Hex-Dragon/PCL2#186]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

自定义主页分为离线与在线模式，离线模式下读取Custom.xaml，在线模式下从服务器获取xaml文档。
我的想法：先显示离线主页，然后尝试从指定的URL下载在线主页，如果不成功就一直显示离线主页，成功则显示在线主页。

### 原因

我需要这个功能来制作整合包。整合包需显示服务器公告，但如果服务端脱机或崩溃，或者客户端脱机，则主页就啥都没有……

**Comment by youzi-2333** [comment]
希望不要丢Discussions，服务器还有好多人等着qwq

**Comment by Big-Cake-jpg** [comment]
你指的是缓存主页文件吗？如果是的话，与 #40 重复。

**Comment by youzi-2333** [comment]
艹，#40 这个Issue标题起的，不点进去我都不知道

**Comment by youzi-2333** [comment]
……抱歉，这是我的理解问题，我指的是，在联网主页下载完成之前，使用本地的文件作为主页；主页下载完成之后，自动切换回联网下载的主页。

现在咋办，Reopen 还是重新交一个 Issue（

**Comment by mcwuguodadi** [comment]
> ……抱歉，这是我的理解问题，我指的是，在联网主页下载完成之前，使用本地的文件作为主页；主页下载完成之后，自动切换回联网下载的主页。
> 
> 现在咋办，Reopen 还是重新交一个 Issue（

智能切换主页么？是个好想法

**Comment by mcwuguodadi** [comment]
啊，这个issue怎么有11个月没人管呢（思索）

**Comment by youzi-2333** [comment]
> 智能切换主页么？是个好想法

理解成智能切换主页也行……
@LTCatt

**Comment by LTCatt** [comment]
现在只要成功加载了一次之后就会读取缓存，没有必要再单独加个离线模式
