### ISSUE TITLE
文本小修改？

### ISSUE THREAD

**Issue by Chen-Luan** [Hex-Dragon/PCL2#1861]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

mod下载界面这里是不是应该改成`目标MC版本`之类的？

![屏幕截图 2023-05-15 123429](https://github.com/Hex-Dragon/PCL2/assets/62653664/0784a6bb-896a-4e87-96d1-6aef1cf9e2bb)

### 原因

这可能是一个错别字？

**Comment by Chiloven945** [comment]
标题就不要出现问号之类的了，而且请在标题就概括性地说出文本修改的地方
