### ISSUE TITLE
PCL2在登录正版账号时出现提示：“Plain Craft Launcher 2 启动器 未响应”

### ISSUE THREAD

**Issue by Liuchengrailtransit** [Hex-Dragon/PCL2#1862]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![屏幕截图 2023-05-15 133321](https://github.com/Hex-Dragon/PCL2/assets/110364400/4079576b-4c28-403f-8eae-b07ba8bd1400)

虽然会出现提示但并不影响启动器使用，一会之后会自动恢复
本人电脑内存16GB，不太认为是电脑问题导致的

### 重现步骤

1、点击正版
2、选择添加新账号
3、点击登录
4、启动器自动打开登录界面
5、登录界面打开后或登陆中时   有   概   率   出现这种情况，注意是有概率不是一定

### 日志与附件

显示[Uploading Log1.txt…]()了，但是貌似我看不到，不太清楚是什么问题
留个备用链接以防万一
链接：https://pan.baidu.com/s/1ZU6ltNsv5rqPnEyfk5tUGQ?pwd=1234 
提取码：1234
PS：上传的时候不知道为啥log1显示上传失败就没上传

**Comment by LTCatt** [comment]
这是浏览器卡了，我没法修……
