### ISSUE TITLE
更新报错（对不起我检查项第一个说谎了）

### ISSUE THREAD

**Issue by LBacteria** [Hex-Dragon/PCL2#1863]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在输入解锁码更新后报错
![20230516174020](https://github.com/Hex-Dragon/PCL2/assets/108278294/4832d26c-2ce6-4c2c-8c70-a32236760030)

### 重现步骤

1、在爱发电私信问龙猫要更新秘药
2、输入更新秘药
3、过一会更新报错

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11486299/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11486300/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11486301/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11486302/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11486304/Log5.txt)

**Comment by YUANXINGlingyun** [comment]
怀疑网络问题？~~1M的文件才下载1K…~~

**Comment by lovelysheepfield** [comment]
可以点击第一个检查项前面的钩取消勾选

**Comment by Chormore-EDGE** [comment]
> 可以点击第一个检查项前面的钩取消勾选

![image](https://github.com/Hex-Dragon/PCL2/assets/114737601/dfcf92f6-cecb-428d-869d-c7b312cc536e)
带*不能不勾吧....

**Comment by Chiloven945** [comment]
请不要在标题加括号，这非常影响阅读
你可以在具体内容内概述

**Comment by LTCatt** [comment]
现在尝试更新能否重现这一错误？
如果可以重现，加 QQ 1043137532，原因写 issue 1863。

**Comment by LTCatt** [comment]
由于未回复暂时关闭，有需要可以继续回复。
