### ISSUE TITLE
在Java15及以上使用ZGC替换G1GC

### ISSUE THREAD

**Issue by ANMSakura** [Hex-Dragon/PCL2#1864]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

ZGC有垃圾回收的停顿时间不超过10ms、垃圾回收的停顿时间不会随着内存使用量变化、最大支持16TB的堆、返回未使用内存给操作系统等优点。相比G1GC性能更佳

### 原因

见描述

**Comment by ZZZank** [comment]
我个人不推荐这么干，现阶段的ZGC对CPU核心数以及内存量的要求比G1GC高非常多，换用ZGC对核心数不多或者内存紧张的设备来说是负优化。而且ZGC的低停顿对服务端才用处很大，在客户端上其实会降低帧数

**Comment by ANMSakura** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/132195516/de179db8-236f-49b0-9505-4e4a5d1a23d6)
![image](https://github.com/Hex-Dragon/PCL2/assets/132195516/49361986-95cd-4f09-a310-a3b6d7fd1bf8)
问了俩AI，似乎ZGC对于MC的确不大合适
