### ISSUE TITLE
主动设定-Xmn的值为固定值或者总分配量的固定百分比

### ISSUE THREAD

**Issue by ZZZank** [Hex-Dragon/PCL2#1874]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

让-Xmn的值可以自己设置，其实就三点
- 主动设定-Xmn的具体数值
- 在想要设定的-Xmn值大于分配内存时提醒
- 以及一个可以不弄，但很希望有的功能：以百分比形式设定-Xmn，启动时具体的-Xmn值按照 最大内存*百分比 确定

### 原因

现在-Xmn 的值是固定的256m，这在最大内存比较少时没什么问题。
但是高版本Java的GC机制（据我的测量）大多偏向于节约内存，会为了压低内存用量而高频触发GC，比如这样：
![image](https://github.com/Hex-Dragon/PCL2/assets/47418975/616d7f76-2442-4be2-9ac8-54c00e8d6a42)
上面这张图里是-Xmn256m，-Xmx6g的情况，Java拼命降低内存用量，导致实际用到的内存（2.6g，这时Java自己设定的软上限为2.8g）还不到分配（共6g）的一半。

然后我通过PCL导出了启动脚本，手动修改-Xmn为4g，结果为：
![image](https://github.com/Hex-Dragon/PCL2/assets/47418975/a36fd68f-8e01-47e9-9798-ed536e3e6065)
不仅GC变少了（每0.9秒一次变成每5秒一次），CPU占用也有一定降低.
（这个CPU占用其实有问题，具体数值不对，但“占用降低”这个趋势是对的）

**Comment by youzi-2333** [comment]
其实吧……
我感觉有第三个就可以了……

---

这个设定应当只针对高版本 Java，并且根据作者的 `-Xmn4g -Xmx6g`，这个百分比可以设置在 2/3 即 60% 到 70%，也可以在游戏设置中添加这个选项。

**Comment by ZZZank** [comment]
> 其实吧…… 我感觉有第三个就可以了……

第一点其实是为了应对明显知道所需-Xmn大小的情况，以及一些其他特殊情况的。第二点是为一和三兜底，因为-Xmn大于-Xmx时Java会拒绝启动。所以我希望三点都有（

> 这个设定应当只针对高版本 Java

也不一定，我查过Java在GC方面的更新，结论是G1GC总体结构基本不变。鉴于我的测试里用的就是Java17+G1GC，我觉得这个-Xmx的改动可以一路惠及到Java8甚至更早的版本。

> 这个百分比可以设置在 2/3 

这个2/3是我通过加载时内存占用以及游戏内内存占用算出的，如果别人有更好的可以换掉。
另外，强制-Xmx与-Xmn为同一个值似乎可以带来比这个还要好的性能表现，只是调高-Xmx会使内存用量总体上升，而且我没什么时间测（
另另外，最好能在调-Xmx时提醒内存占用可能升高，防止内存紧张的设备乱调，搞得性能反而更差。

**Comment by LTCatt** [comment]
考虑到它的用途，应该不需要加入设置。现在 Xmn 的值会从 256M 改为 Xmx 的一半……
