### ISSUE TITLE
我认为这个游戏异常应该可以正常给出错误来源

### ISSUE THREAD

**Issue by MinecraftSTL** [Hex-Dragon/PCL2#1875]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

![PCL给出的错误提示](https://github.com/Hex-Dragon/PCL2/assets/53145859/ef6a946e-7117-4c1c-8158-6c92d4d23885)
![日志中的信息](https://github.com/Hex-Dragon/PCL2/assets/53145859/e09fc33e-4942-4d20-bc53-2da271afc23a)

[latest.log](https://github.com/Hex-Dragon/PCL2/files/11521969/latest.log)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11521970/Log1.txt)

### 原因

这项优化让我可以更方便地排查错误。
如果没有这项优化，我每次都必须翻日志，让操作变得很麻烦。

**Comment by ZZZank** [comment]
PCL认出了是注入失败，却没给出具体mod，这应该算启动器的功能bug而非优化吧？🤔

**Comment by MinecraftSTL** [comment]
> PCL认出了是注入失败，却没给出具体mod，这应该算启动器的功能bug而非优化吧？🤔

或许是，但是在某些情况下是能给出的，我也不知道是pcl2的问题，还是这个日志不合规

**Comment by MinecraftSTL** [comment]
不过也有道理，如果真的抓不到名称应该给出的是另一个错误提示

**Comment by MinecraftSTL** [comment]
14CB-5A82-B26A-9205

**Comment by Chiloven945** [comment]
标题就不要写认为了，是什么就是什么……

**Comment by MinecraftSTL** [comment]
> 标题就不要写认为了，是什么就是什么……

但是问题就是是的是我认为，我也不知道实际上是什么啊

**Comment by LTCatt** [comment]
你的解锁码：zh8xCwtbGk/nULj+IVWi3t9Jg6n0g/Q9
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by Chiloven945** [comment]
> > 标题就不要写认为了，是什么就是什么……
> 
> 但是问题就是是的是我认为，我也不知道实际上是什么啊

无法确定问题是什么可以先交discussion问情况之后再转到issue

**Comment by MinecraftSTL** [comment]
> > > 标题就不要写认为了，是什么就是什么……
> > 
> > 
> > 但是问题就是是的是我认为，我也不知道实际上是什么啊
> 
> 无法确定问题是什么可以先交discussion问情况之后再转到issue

你说得对，但是我终于有活跃橙了

**Comment by Chiloven945** [comment]
> 你说得对，但是我终于有活跃橙了

这和问题有什么关系呢，而且请不要连续quote，非常影响查看

**Comment by MinecraftSTL** [comment]
> > 你说得对，但是我终于有活跃橙了
> 
> 这和问题有什么关系呢，而且请不要连续quote，非常影响查看

关系就是以后大概是用不到了，而且我点击"Quote reply"的效果就是这样的

**Comment by iPodtouch6557** [comment]
自己动手删，或者不要quote

**Comment by MinecraftSTL** [comment]
> 自己动手删，或者不要quote reply，直接回

但是我觉得连续quote可以清楚地表达交流过程，没有多少影响查看
自己删太麻烦了，但是直接回就看不出来我回的哪一条

**Comment by WForst-Breeze** [comment]
此 Issue 处理工作已完成，请各位朋友尽可能避免过多进行与 Issue 提及内容无关的讨论，否则此 Issue 可能会被锁定
