### ISSUE TITLE
在游戏主体程序关闭但启动器显示游戏仍在运行时启用mod会导致mod直接丢失

### ISSUE THREAD

**Issue by RuanQwQ** [Hex-Dragon/PCL2#1876]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

  如题，在启动一些大型整合包时

  如我的世界：地球2.0，OdysseyCraft，贪婪

  关闭游戏后点击mod列表的未启用mod时仍显示**切换Mod状态失败，请尝试关闭正在运行的游戏后再试**，多次点击仍然如此，再次打开mod列表时mod直接没了（寄），文件夹里的mod文件直接消失，.disabled没有，.jar也没有。我已经丢了好几个不认识的mod了，对游玩十分不利，例如直接导致任务书的重要核心模组丢失却因为找不到名字干着急）（

### 重现步骤

  在此之前，先让启动器处在游戏关闭但仍能检测到游戏的错误状态
 1.先点击版本设置
 2.然后点击mod列表
 3.找到事先准备好用于测试的未启用mod
 4.点击它
 5.显示”切换Mod状态失败，请尝试关闭正在运行的游戏后再试”
 6.重新进入启动器或刷新界面
 7.寄嘞

### 日志与附件

这是启动器的显示
[新建压缩(zipped)文件夹.zip](https://github.com/Hex-Dragon/PCL2/files/11522675/zipped.zip)

**Comment by LTCatt** [comment]
请上传日志文件。

---

@bwtx2023 这个连日志都没传……别丢待处理啊……

**Comment by bwtx2023** [comment]
> 请上传日志文件。

看岔了不好意思（

**Comment by youzi-2333** [comment]
请在 7 天内补充日志文件（`PCL\Log[1-5].txt`），否则 Issue 将被关闭，感谢配合。

**Comment by LTCatt** [comment]
超过 10 天不回就可以关了 =。=

如果有需要可以继续回复。
