### ISSUE TITLE
首次启动部分远古版本不会自动设置语言为简体中文

### ISSUE THREAD

**Issue by Pigmud** [Hex-Dragon/PCL2#1877]
### 检查项

- [x] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

首次启动部分早期远古版本不会自动设置语言，拿1.1做的测试，具体的受影响版本范围没有测试

### 重现步骤

1、下载已经加入其他语言的远古版mc（如1.1）
2、启动游戏

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11522832/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11522833/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11522834/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11522835/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11522836/Log5.txt)

**Comment by iPodtouch6557** [comment]
你确定把那个自动设语言的设置开开了？

**Comment by MJIFmc** [comment]
可以在1.8.9中确认

**Comment by Pigmud** [comment]
> 你确定把那个自动设语言的设置开开了？
开了，检查过

**Comment by Pigmud** [comment]
> 你确定把那个自动设语言的设置开开了？

开了，检查过

**Comment by Pigmud** [comment]
现在好像又行了。。。
