### ISSUE TITLE
没有缓存文件夹的访问权限

### ISSUE THREAD

**Issue by Chormore-EDGE** [Hex-Dragon/PCL2#1883]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如图
![image](https://github.com/Hex-Dragon/PCL2/assets/114737601/edfaa50c-45a0-4aeb-b39a-20171aa7c3cd)

### 重现步骤

一点开就出来了（

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11524540/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11524541/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11524542/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11524545/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11524546/Log5.txt)

**Comment by youzi-2333** [comment]
您那边是不是改了 `%temp%\PCL` 路径的权限设置……
在文件管理器的路径栏里面输入上面这串东西，按回车，退回上一级，把 PCL 文件夹删掉试试？

**Comment by Chormore-EDGE** [comment]
没改~不会~

**Comment by Chormore-EDGE** [comment]
而且我意外的发现pcl2缀双开了
（

**Comment by LTCatt** [comment]
你的解锁码：9H2wPp+mB/RmSB43lkGY7NIlY65jqo7o
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
