### ISSUE TITLE
在下载页面新版本介绍连接中允许选择跳转至b站镜像网站

### ISSUE THREAD

**Issue by FQO3** [Hex-Dragon/PCL2#1884]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在下载页面里，每个功能后面都有个“更新日志”点进去会跳转到fandom里mc的wiki，但考虑到部分用户（比如我）有时候无法正常连接这个网站或连接时间过慢，提议在设置页面增加“更新日志跳转至bilibili镜像wiki”

### 原因

如果没这项优化，我家网本来就不好，这还是个外国网站，所以每次看日志都得手动在b站镜像wiki里搜索打开对应界面，特别不人性……

**Comment by LTCatt** [comment]
更新日志需要有时效性，镜像站的更新速度较慢，所以不考虑 :(
