### ISSUE TITLE
下载模组把灰色字识别成中文名

### ISSUE THREAD

**Issue by Pigmud** [Hex-Dragon/PCL2#1893]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

<img width="626" alt="image" src="https://github.com/Hex-Dragon/PCL2/assets/115208957/bb18d8f2-7ac7-4187-b867-79b7479859f3">
<img width="460" alt="image" src="https://github.com/Hex-Dragon/PCL2/assets/115208957/e62d0592-49ba-46fc-b169-39c11929c3d7">
不知道怎么解释原因

### 重现步骤

下载carpet mod（现在只发现了这一个受影响的mod）

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11565703/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11565704/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11565705/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11565706/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11565707/Log5.txt)

**Comment by Pigmud** [comment]
503F-2832-B8B5-D19A

**Comment by LTCatt** [comment]
你的解锁码：gX2jrsygBlcdPMR9XD/GmW7HXhessquX
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
