### ISSUE TITLE
CraftifyMOD版本错误

### ISSUE THREAD

**Issue by YINGBS** [Hex-Dragon/PCL2#1895]
### 检查项

- [x] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

Craftify模组版本Forge最高为1.12.2，但我搜索为Modrinth,1.18.2,Forge也能搜索到Craftify这个模组，可能其他MOD也有这个BUG

### 重现步骤

1、点击下载
2、点击MOD
3、版本选择1.18.2
4、加载器选择Forge
4、来源选择Modrinth
5、往下滚
6、点击Craftify，点击1.18.2
(可以看到加载器全部都是Fabric)

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11573784/Log1.txt)

**Comment by LTCatt** [comment]
https://www.curseforge.com/minecraft/mc-mods/craftify/files?gameVersionTypeId=1
CurseForge 上该模组 Forge 版本最高为 1.12.2，没有问题

**Comment by dargoncat** [comment]
![无标题](https://github.com/Hex-Dragon/PCL2/assets/121101691/6b925053-5892-4e51-a63c-01fca92820a6)
有问题吧。。。这选的Modrinth来源，mod加载器forge，mc版本1.18.2，按理来说是没有匹配mod的
