### ISSUE TITLE
版本隔离问题

### ISSUE THREAD

**Issue by 147183** [Hex-Dragon/PCL2#1896]
### 检查项

- [ ] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃不是 PCL2 的原因，请 **不要** 提交反馈。你可以在 QQ 群里或者论坛找人求助，但这里并不是你求助的地方。
- [ ] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是游戏本身的问题，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [ ] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [ ] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我打开版本隔离后，还加了个灾变模组，游戏就崩溃了

### 错误报告、日志与附件

[错误报告-2023-5-26_18.16.52.zip](https://github.com/Hex-Dragon/PCL2/files/11574296/-2023-5-26_18.16.52.zip)

**Comment by YUANXINGlingyun** [comment]
这不是 PCL2 的问题，并且我已于 #1897 中回复

ps. 若已发 Discussion 帖子，并未确认是 PCL2 的 Bug，请不要发 Bug Issue 帖子

**Comment by WForst-Breeze** [comment]
移步 #1897
