### ISSUE TITLE
添加选择渲染器功能

### ISSUE THREAD

**Issue by afhw** [Hex-Dragon/PCL2#1904]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

emmmm,可以添加渲染器选择的功能在高级选项设置里吗，例如像OpenGL，Vulkan，软渲染器这些渲染器吗

### 原因

我需要这个功能来启动一些Minecraft客户端。在使用PCL2现有的渲染器的情况下，有几率出现例如Minecraft文字乱码，背景消失等情况。

**Comment by xxtg666** [comment]
这个功能是mod实现的吧

**Comment by Xzhong2023** [comment]
> 这个功能是mod实现的吧
@xxtg666 
我觉得不是因为hcml是在启动器中直接设置的

**Comment by Xzhong2023** [comment]
@afhw 你可以用hcml

**Comment by wyc-26** [comment]
目前 Mojang 更新了对 Vulkan 的支持，遂重开本 Issue

**Comment by LTCatt** [comment]
游戏内可以切换的话，没有太大必要在启动器中再添加一个更改功能 :/
