### ISSUE TITLE
在“设置-游戏-高级设置”里加上一句话“以下设置如果随意修改，可能导致游戏无法启动。”

### ISSUE THREAD

**Issue by TyphoonCorporation** [Hex-Dragon/PCL2#1907]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在“设置-游戏-高级设置”里加上一句话“以下设置如果随意修改，可能导致游戏无法启动。”

### 原因

这项优化可以防止我们误修改游戏设置。

**Comment by LTCatt** [comment]
没有必要。
