### ISSUE TITLE
部分正式版下载完在‘版本选择’中显示的其他类别

### ISSUE THREAD

**Issue by zhanglaoMC** [Hex-Dragon/PCL2#1908]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我在下载正式版中的1.3.2（1.4也有，1.5.2没有）后，在‘版本选择’列表中想试玩一下旧版，显示是远古版本
（我搜过，没人提交过这个特性）我并不知道其他比较老的正式版有没有，
然后我下载了‘正式版’中的1.7版本，发现1.7下载完毕后这个版本又显示为快照版了
--
建议将这些版本归类为快照、远古版本 或者将他们改回正式版在‘版本选择’列表

### 重现步骤

下载1.7,1.4这些老版本后在‘版本选择’列表可能会显示上述一样显示远古版本

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11583470/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11583471/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11583472/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11583473/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11583474/Log5.txt)

**Comment by zhanglaoMC** [comment]
不知道有没有重复

**Comment by pangzong2011** [comment]
我记得好像之前有人说过，可能是mj的原因？

**Comment by youzi-2333** [comment]
并不是 Mojang 的原因。PCL 会自动将 Minecraft 1.4.X 及以下的版本归为远古版本，这应该是刻意的设计……

![image](https://github.com/Hex-Dragon/PCL2/assets/106497113/7222d1f8-d927-402b-94d2-23a08163b5f7)

这里面这些版本都是 release 或 snapshot，没有 alpha 这种鬼东西，并且 ChatGPT 给出的结果也是“1.5 版本及以下可以被称为远古版本”。
综上，暂不考虑处理该 Issue，如有异议可以艾特龙猫让他看看（
