### ISSUE TITLE
PCL2无法自定义1.19.4及以上版本Minecraft的窗口名称

### ISSUE THREAD

**Issue by Cast245** [Hex-Dragon/PCL2#1909]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在1.19.3及以下版本的Minecraft，PCL2可以自定义游戏窗口名称，但在1.19.4时，PCL2则无法更改窗口名称，结果如以下图片显示，希望能够修复一下。
![游戏窗口名称](https://github.com/Hex-Dragon/PCL2/assets/122718145/ae28a5e1-c9fc-483a-a1df-2622ff23642f)
![pcl2设定](https://github.com/Hex-Dragon/PCL2/assets/122718145/31ef24af-8826-48ae-99de-ef33acc52bd2)

注：此PCL2版本为最新快照版2.6.0，测试客户端为Minecraft1.19.4 fabric(有mod)版本，使用电脑系统为windows7。

### 原因

可以完善PCL的设置，让这项功能可以适用于所有Minecraft版本中。

**Comment by iPodtouch6557** [comment]
自定义在1.19.3生效吧

**Comment by Cast245** [comment]
@iPodtouch6557 但是1.19.4以上就没法用

**Comment by WForst-Breeze** [comment]
Win 10 无法复现，1.20 pre-6 与 1.19.4 均无法成功复现
![image](https://github.com/Hex-Dragon/PCL2/assets/110760354/9f80ccec-c8bb-4fae-a117-b411e5e77468)

**Comment by LTCatt** [comment]
请先启动一次 Minecraft，然后上传 PCL 启动器日志。这是 Bug 不是优化，你选错模板了……

**Comment by Cast245** [comment]
@LTCatt log-log5的文件如下
[log.txt](https://github.com/Hex-Dragon/PCL2/files/11592379/log.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11592383/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/
[Log3.txt](https://github.com/Hex-Dragon/PC
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11592388/Log4.txt)
L2/files/11592386/Log3.txt)
files/11592384/Log2.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11592390/Log5.txt)

**Comment by Cast245** [comment]
@LTCatt log文件如下
[log.txt](https://github.com/Hex-Dragon/PCL2/files/11592405/log.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11592409/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11592410/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11592411/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11592413/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11592417/Log5.txt)

**Comment by LTCatt** [comment]
无法复现，怀疑为客户端/mod导致，如果有其他人也出现了这个问题再考虑修复 =。=
