### ISSUE TITLE
[优化] 启动游戏时，若找不到合适 Java，自动刷新 Java 列表

### ISSUE THREAD

**Issue by youzi-2333** [Hex-Dragon/PCL2#1911]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

启动 MC 时，如果没有合适的 Java，那么自动刷新 Java 列表以寻找适用的 Java。

### 原因

这样可以避免装了 Java 但没有刷新列表，然后启动失败的问题。

我也不知道新版本有没有加这个功能……

**Comment by bwtx2023** [comment]
借楼，现在新安装 Java 以后 PCL2 有概率找不到新安装的 Java ，需要重启启动器才能找到，如果可以的话也一并解决了吧

**Comment by LTCatt** [comment]
会自动刷新 Java 列表。



> 借楼，现在新安装 Java 以后 PCL2 有概率找不到新安装的 Java ，需要重启启动器才能找到，如果可以的话也一并解决了吧
Windows 提供给程序的环境变量是在程序启动的时候一次性提供的，所以启动后的更改无法获取，没有办法。
