### ISSUE TITLE
[优化] 为控件显示 / 隐藏添加动画

### ISSUE THREAD

**Issue by youzi-2333** [Hex-Dragon/PCL2#1912]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

目前，控件出入时没有动画（例如“启动前执行命令”输入文本后，下方会弹出一个复选框，此时没有出现动画），建议添加

https://github.com/Hex-Dragon/PCL2/assets/106497113/b1a8b7fa-7069-4464-b493-fff188cf48bb

### 原因

这项优化可以使 PCL 动画更加丝滑……

**Comment by LTCatt** [comment]
不方便做，影响也不大，算了 =。=
