### ISSUE TITLE
“千万别点”按钮只能显示一半

### ISSUE THREAD

**Issue by Mcenahle** [Hex-Dragon/PCL2#1915]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在更新为PCL2快照版：2.6.2后，更多-百宝箱中的“千万别点”按钮只能显示一半。

### 重现步骤

1、点击“更多”标题；
2、点击“百宝箱”；
3、然后你就会发现“千万别点”按钮只能显示一半。
<img width="608" alt="屏幕截图 2023-05-28 211704" src="https://github.com/Hex-Dragon/PCL2/assets/85427807/17cecfe4-9e6a-4a11-b22f-197236ece34f">

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11584652/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11584654/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11584655/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11584656/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11584657/Log5.txt)

**Comment by WForst-Breeze** [comment]
窗口拉宽点就好了，很早之前也有一个类似问题被拒了，感觉这个也不太会优化（）看看龙猫怎么想，感谢您的反馈~

**Comment by blibilijojo** [comment]
> 窗口拉宽点就好了，很早之前也有一个类似问题被拒了，感觉这个也不太会优化（）看看龙猫怎么想，感谢您的反馈~

肯定会处理的，毕竟在软件设定好的最小窗口所有功能都应该能正常使用的

**Comment by Cast245** [comment]
@wforst-breeze 这玩意拉升了以后pcl的部分自定义主页会直接没法加载

**Comment by Cast245** [comment]
本来想反馈的结果被抢先了（寄（虽然我有活跃橙皮肤

**Comment by iPodtouch6557** [comment]
> 啊啊啊我的活跃橙还是没拿到(就差它了)

请不要在这里乱搞活跃橙的事TwT

**Comment by McenahleDevelop** [comment]
我的PCL识别码：3A36-1F2C-7A32-D237。麻烦给一下活跃橙解锁密钥，谢谢！！

**Comment by Mcenahle** [comment]
我的PCL识别码：3A36-1F2C-7A32-D237。麻烦给一下活跃橙解锁密钥，谢谢！！

**Comment by LTCatt** [comment]
你的解锁码：wPclwEURaJ7tWRGPSP1adTVceEdMD4Ze
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by Mcenahle** [comment]
新识别码：**61B6-4FB2-DD08-9A58**

**Comment by LTCatt** [comment]
你的解锁码：1dQit4uK7mhwnnbe2dl5Ym9tY2CjtSiN
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
