### ISSUE TITLE
自定义Java使用的垃圾回收器

### ISSUE THREAD

**Issue by idhaname** [Hex-Dragon/PCL2#1916]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

可以在高级设置里面增加一个下拉框，让用户选择使用哪个回收器

BakaXL的自定义Java回收器选项
![图片](https://github.com/Hex-Dragon/PCL2/assets/68469786/206398cf-2343-4737-9fa6-5099243ef70c)

实操时（貌似）添加JVM参数即可，例如：
-XX:+UseSerialGC
-XX:+UseParNewGC
-XX:+UseConcMarkSweepGC
-XX:+UseParallelGC
-XX:+UseParallelOldGC
-XX:+UseG1GC

### 原因

来源于Issue: #1864 
建议给高级用户一个选项，以使不同配置用户能够自定义Java所使用的垃圾回收器以获得最佳性能，而不用手动添加JVM参数

**Comment by LTCatt** [comment]
如果有需要可以自行修改 JVM 参数。会用这个的玩家太少了，不打算做 =。=
