### ISSUE TITLE
启动器更新失败

### ISSUE THREAD

**Issue by czt0221** [Hex-Dragon/PCL2#1917]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

更新失败， #1641 中说是修了，但还是存在，每次更新都会触发，重启就可以正常更新

### 重现步骤

1、点击设置
2、点击启动器
3、往下滚，然后点击检查更新

### 日志与附件

<img width="960" alt="1" src="https://github.com/Hex-Dragon/PCL2/assets/110171389/7694204f-0ca3-4b84-8168-4056cefc0d8f">

**Comment by LTCatt** [comment]
上传日志

**Comment by Chiloven945** [comment]
估计也是在自动更新的时候手动更新……

**Comment by czt0221** [comment]
额，我的日志1-5已经被最新的覆盖了，昨天晚上没有保留，下次遇到再来，抱歉打扰了
