### ISSUE TITLE
回声洞有话过期了

### ISSUE THREAD

**Issue by blibilijojo** [Hex-Dragon/PCL2#1918]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

今天辗转反侧，毫无睡意，打开软件，查看回声洞，乐。
看到一句话“你可以点击下面的红框”之类的话，但是最新版本的“千万别点”已经到上边了！
这算是个bug吗，我的新主题有希望了！

### 重现步骤

em，总不能一直点吧......龙猫自己看吧

### 日志与附件

1

**Comment by WForst-Breeze** [comment]
初步确认，感谢您的反馈
![image](https://github.com/Hex-Dragon/PCL2/assets/110760354/34bbefc4-19dd-4fad-8f82-bce364ef5911)

**Comment by blibilijojo** [comment]
> 初步确认，感谢您的反馈 ![image](https://user-images.githubusercontent.com/110760354/241568060-34bbefc4-19dd-4fad-8f82-bce364ef5911.png)

我擦？！你是点了n次还是用的其他啥的

**Comment by WForst-Breeze** [comment]
动画速度调到最大，刷这玩意很快的😉

**Comment by blibilijojo** [comment]
> > 我擦？！你是点了n次还是用的其他啥的
> 
> 动画速度调到最大，刷这玩意很快的wink

擦

**Comment by blibilijojo** [comment]
@LTCatt 虽然不知道这算不算是bug，但是确实修了对吧，虽然更新通告里没说着个是bug，但是人的梦想总是要有的，万一实现了呢，还是说一下，我的PCL识别码：903F-A55C-75C7-97DC。

**Comment by LTCatt** [comment]
你的解锁码：FJYVrbC9Ue7oY2AtIXtThxpg6dZVjbal
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

算啊，标签是 Bug，我没改就算……

**Comment by blibilijojo** [comment]
> 你的解锁码：FJYVrbC9Ue7oY2AtIXtThxpg6dZVjbal 在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
> 
> 算啊，标签是 Bug，我没改就算……

咖喱嘎多，龙猫桑。（doge）
