### ISSUE TITLE
关于播放动画时字体模糊的问题

### ISSUE THREAD

**Issue by reana-ovo** [Hex-Dragon/PCL2#1919]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

现在我只能关闭动画才能看清文字，为什么要做一个字体从模糊到清晰的动画，我不理解，而且还时间巨长，UI动画结束完一秒才能看清字。而且你滚动界面的时候也模糊，整个突出一个看着头疼，我感觉我眼睛都要花了。最离谱的是左上角PCL Ⅱ的标题也是糊的，截个图给你看看。
![图片](https://github.com/Hex-Dragon/PCL2/assets/20798393/274ea8dc-2c21-48bd-ba3c-c8ecab926930)

### 原因

保护眼睛，人人有责

**Comment by LTCatt** [comment]
这是 WPF 的一些内置抗锯齿特性导致的，我试过关掉，结果更瞎眼了……没办法就
