### ISSUE TITLE
蹩脚的交互体验

### ISSUE THREAD

**Issue by reana-ovo** [Hex-Dragon/PCL2#1920]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

不知道从哪里说起，比如说主界面右侧的大片空白，版本选择和版本设置按钮在底下作为两个相同大小的按钮，我不知道这样做的意义是什么，版本设置完全可以在主界面作为一个更显眼的快捷入口方便用户设置当前的游戏版本，右侧大片空白本来能够将皮肤与披风、修改信息、切换账号这些功能集成（就是现在鼠标悬停在头像上出现的那三个）。比如我进入管理mod界面却不能跳转到下载mod界面；比如我选择了版本但版本选择界面却只有.minecraft文件夹才有已选中的高亮提示，而我选择的版本却只显示在主界面开始游戏底下的小字，给版本设置的个性化图标也完全不显示在主页上；比如我新安装了一个版本或者新安装了一个整合包但是却不会自动选择。虽然说有很灵动的动画效果，但是这些基础的交互体验给我一种很糟糕的感觉，但怎么说呢，往好的方向想，还是比某B开头的启动器好一点？（

### 原因

可能作者没有功夫关心这些使用体验方面的问题，但是还是希望有朝一日能够改善一下。

**Comment by Chiloven945** [comment]
没有任何东西是完美的
看看龙猫怎么说，部分所提到的功能已经在discussion页面了，你可以为其投票

**Comment by ZZZank** [comment]
糟糕吗？我觉得已经是著名启动器里的体验翘楚了😂
> 版本设置完全可以在主界面作为一个更显眼的快捷入口方便用户设置当前的游戏版本

这个指的应该是版本选择吧，但“选择”与“设置”的使用频率其实并没有很大差别，两个明显而且等大的按钮应该是足够的。
话说，H某某L倒是有个，但是有反馈说交互割裂（
> 右侧大片空白本来能够将皮肤与披风、修改信息、切换账号这些功能集成

空白的本意是让用户自定义主页，以及闲着无聊时看自己设定的壁纸。而且原来的方法风评也不错，放这些账号功能的话带不来多少体验提升。
不过现在这样确实限制颇多，放点功能挺好的，只是我还是希望自定义程度不要降低
> 我进入管理mod界面却不能跳转到下载mod界面

好建议，不妨新开个issue说这一点，这么多点对一起不利于开发者处理。
> 我选择了版本但版本选择界面却只有.minecraft文件夹才有已选中的高亮提示

？这说的我完全听不懂。
"已选中的高亮提示"指的应该是界面左边的吧，那个是多文件夹用的，用来分类，以及避免频繁移动mc本体。
<img width="507" alt="image" src="https://github.com/Hex-Dragon/PCL2/assets/47418975/9f29cd52-13fa-4d5b-bb61-bdae05da2316">

> 而我选择的版本却只显示在主界面开始游戏底下的小字，给版本设置的个性化图标也完全不显示在主页上

这个看个人喜好，我觉得指明“开始游戏”对新用户比较友好，个性化图标有点波坏整体和谐
> 比如我新安装了一个版本或者新安装了一个整合包但是却不会自动选择

有吗，不记得自己碰到过这情况

**Comment by LTCatt** [comment]
> 关于右侧大片空白

目前用于自定义主页，之后还会放新东西的，大概快了 =。=

> 给版本设置的个性化图标也完全不显示在主页上

试着加过，很丑

> 进入管理mod界面却不能跳转到下载mod界面

> 选择了版本但版本选择界面却只有.minecraft文件夹才有已选中的高亮提示

> 新安装了一个版本或者新安装了一个整合包但是却不会自动选择

这三项都可以单独开新 issue，可以做 =。=
一堆东西写在一个 issue 里并不方便处理，这个 issue 就先关了……

**Comment by reana-ovo** [comment]
> 糟糕吗？我觉得已经是著名启动器里的体验翘楚了😂

那确实，只能说我对这方面还是要求比较高

> 这个指的应该是版本选择吧，但“选择”与“设置”的使用频率其实并没有很大差别，两个明显而且等大的按钮应该是足够的。 话说，H某某L倒是有个，但是有反馈说交互割裂（

两个功能都不是一个层级的并且有重复文字明显不能放在一起更别说等大的按钮，我的建议是可以将其中一个改为图标形式放在界面的边角

> 空白的本意是让用户自定义主页，以及闲着无聊时看自己设定的壁纸。而且原来的方法风评也不错，放这些账号功能的话带不来多少体验提升。 不过现在这样确实限制颇多，放点功能挺好的，只是我还是希望自定义程度不要降低

自定义是好事，但是得放在有良好的交互体验之后，这得分清主次

> 好建议，不妨新开个issue说这一点，这么多点对一起不利于开发者处理。

嗯，我开这个issue提这些主要是为了看看开发者有没有意向或者时间去解决这些问题，如果有的话我会把这些问题都单独开issue

> ？这说的我完全听不懂。 "已选中的高亮提示"指的应该是界面左边的吧，那个是多文件夹用的，用来分类，以及避免频繁移动mc本体。 <img alt="image" width="507" src="https://user-images.githubusercontent.com/47418975/241672484-9f29cd52-13fa-4d5b-bb61-bdae05da2316.png">

就是选择版本中右边的部分没有高亮显示，用户没法知道自己当前选择了哪个版本，要退回主页才能看见

> 这个看个人喜好，我觉得指明“开始游戏”对新用户比较友好，个性化图标有点波坏整体和谐

个性化图标不一定必须要显示在按钮上啊，思维不能这么死板，只要能够在主页接受到这个信息就可以了，方便用户快速确认自己选择的版本

> 有吗，不记得自己碰到过这情况

确实是这样的

**Comment by reana-ovo** [comment]
> 目前用于自定义主页，之后还会放新东西的，大概快了 =。=

还是建议把交互体验先放首位，自定义都可以慢慢来，毕竟大多数人也不是为了打开启动器看壁纸的对吧

> 试着加过，很丑

看你怎么加了，加在按钮上那肯定是不行的

> 这三项都可以单独开新 issue，可以做 =。= 一堆东西写在一个 issue 里并不方便处理，这个 issue 就先关了……

那我有空给你单独写几个

**Comment by iPodtouch6557** [comment]
我之前提过几个抠细节的交互方案，比如下载页相关的，但是被拒了，所以你的建议里十之八九会不予采纳TwT……
