### ISSUE TITLE
无法直接关闭软件

### ISSUE THREAD

**Issue by jillkyo520** [Hex-Dragon/PCL2#1923]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

千万别点后,无法关闭界面,一定要打开任务管理器才能关闭.在单位电脑上就可以直接点XX关闭.

### 重现步骤

1、点击千万别点
2、点确定

### 日志与附件

[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11591815/Log5.txt)

**Comment by NoGod3524** [comment]
<img width="608" alt="7987a283c9abda8b34ccdf4cbc36e6c" src="https://github.com/Hex-Dragon/PCL2/assets/124627035/f5785f37-f0f4-4d61-a5f2-c160db1b50ed">
不会理会关于按下这个按钮后的任何bug，不行你可以提交一个优化申请

**Comment by jillkyo520** [comment]
好吧,只能忍着下次不会再不小心点到他

**Comment by g-mph** [comment]
这边建议按下Alt+F4
