### ISSUE TITLE
在有64位java的情况下会自动选择32位java

### ISSUE THREAD

**Issue by huaji-ershi** [Hex-Dragon/PCL2#1927]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃不是 PCL2 的原因，请 **不要** 提交反馈。你可以在 QQ 群里或者论坛找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是游戏本身的问题，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如题,同时有32位和64位java的情况下会自动选择32位的

### 错误报告、日志与附件

![image](https://github.com/Hex-Dragon/PCL2/assets/116952542/c5c8f39e-da3c-469d-9f7a-029c6836cbc8)

**Comment by YUANXINGlingyun** [comment]
按理来说不应发生，请提供更多信息
如： Bug 复现方式，是否为自动分配等

ps.你选错反馈模板了

**Comment by huaji-ershi** [comment]
试了一下,只成功复现了几次,感觉应该是小概率bug
![{T~1L}2HX1RVXHE_@)(9@_4](https://github.com/Hex-Dragon/PCL2/assets/116952542/e84fd3be-77e4-4d8e-82eb-0843256dde47)

**Comment by huaji-ershi** [comment]
java设置是自动选择的
![GKSYD I~%$OJVG@S9)J{4KM](https://github.com/Hex-Dragon/PCL2/assets/116952542/c591a147-8e5c-4dca-b47f-09ef05fa8e93)
![CAQD%IUNV2BN4W4YMG66W$6](https://github.com/Hex-Dragon/PCL2/assets/116952542/60a3b76b-ff48-4ffa-88f8-0ae803aecd89)

**Comment by huaji-ershi** [comment]
1.12.2版本正常打开游戏就会这样
别的版本没有试(

**Comment by huaji-ershi** [comment]
1.7.10和1.14.4也会这样

**Comment by huaji-ershi** [comment]
![XE4SM}W5JXW O3YJO61 `R5](https://github.com/Hex-Dragon/PCL2/assets/116952542/195ed4bc-8a77-48c1-b62c-2640fe17914a)

**Comment by LTCatt** [comment]
上传日志

**Comment by huaji-ershi** [comment]
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11607735/Log1.txt)

**Comment by LTCatt** [comment]
你把 java 放到了 MC 文件夹里，PCL 会优先选用 MC 文件夹/版本文件夹里的 java
