### ISSUE TITLE
mc游玩一段时间闪退

### ISSUE THREAD

**Issue by jillkyo520** [Hex-Dragon/PCL2#1929]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃不是 PCL2 的原因，请 **不要** 提交反馈。你可以在 QQ 群里或者论坛找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是游戏本身的问题，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

说我的显卡驱动存在问题,导致游戏无法正常运行,可是用win10商店的mc启动器是可以游玩的.我尝试更新了显卡驱动程序到最新版本,升级了java,但是问题依旧.

### 错误报告、日志与附件

[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11598391/Log5.txt)

**Comment by zkitefly** [comment]
你提供的日志中并没有有效信息，请提供游戏崩溃日志

**Comment by bwtx2023** [comment]
补充游戏崩溃后导出的错误报告

**Comment by youzi-2333** [comment]
请尽快补充相关信息，10 天未补充信息的 Issue 将会被关闭，感谢配合

**Comment by LTCatt** [comment]
超时关闭，若有需要可以继续回复
