### ISSUE TITLE
可视化 Mod 列表出错：无效的索引访问一个元素或与数据库冲突

### ISSUE THREAD

**Issue by Kusuria** [Hex-Dragon/PCL2#1932]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

这个问题出现在最新快照版 Snapshot 2.6.2（294.0）
Mod页搜索时弹出错误窗口 但似乎不影响使用

### 重现步骤

无法复现
（等待社区有人能够复现）

### 日志与附件

https://mclo.gs/XVyftDL
( 对不起 只是窗口信息 :< )

**Comment by bwtx2023** [comment]
你干了啥写一下

**Comment by Kusuria** [comment]
还未输入及搜索，在选定搜索框后

**Comment by bwtx2023** [comment]
差点忘了，补充一下 PCL 文件夹内的启动器日志

**Comment by Kusuria** [comment]
Aww…
logs are lost and unrecoverable,
thank you kindly <3
