### ISSUE TITLE
建议把游戏登录方式位置调整至概览区域中

### ISSUE THREAD

**Issue by baguotao233** [Hex-Dragon/PCL2#1936]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

我希望把游戏登录方式位置调整至概览中可以更快完成登陆方式的切换操作，而且像某些服务器比较特殊，有的不支持正版，有的要求第三发登录，希望调整至概览区域方便快速切换

### 原因

这项优化让我可以更方便地调整登录方式。
如果没有这项优化，我每次都必须先点击，再点击，再下拉，再点击，让操作变得很麻烦。

**Comment by WForst-Breeze** [comment]
第三方登录全局设置会做的，可见 #57，也许可以完成您提及的部分需求。感谢您的反馈~

**Comment by LTCatt** [comment]
暂时不计划，它属于服务器设置，抱歉 :(
