### ISSUE TITLE
PCL2启动器本身（不是Minecraft窗口）的窗口问题

### ISSUE THREAD

**Issue by niguolaiap** [Hex-Dragon/PCL2#1938]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

出现这个 Bug 后，启动器无法再使用拖动改变窗口位置和大小
只有重新启动 PCL2 才可恢复

### 重现步骤

使用 Windows 任务管理器的窗口选项
点击“最大化”，这个 Bug 在此时就已经出现

### 日志与附件

无法上传文件
1.日志中没有包含该 Bug 的记录
2.GitHub显示“无法处理该文件”

**Comment by Chiloven945** [comment]
~啊自闭了~
你写好是PCL的窗口问题就没有人去怀疑是Minecraft的窗口问题了，所以说不需要在标题特殊说明，如果你还是觉得有人会这样做可以在正文说明
