### ISSUE TITLE
内存优化后电脑出现卡顿

### ISSUE THREAD

**Issue by ShineSunsun** [Hex-Dragon/PCL2#1940]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

使用内存优化功能的过程或之后出现较大卡顿以及大部分程序未响应（需要一定时间完全恢复）

### 重现步骤

1、点击更多-百宝箱-内存优化
2、等待内存优化完成
3、通常在等待内存优化完成的过程中或弹出内存优化完成的提示后触发

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11621388/Log1.txt)

**Comment by Chiloven945** [comment]
挺正常的，因为毕竟是实验性的功能，况且减少内存的确会出现性能问题

**Comment by LTCatt** [comment]
正常情况 =。=
