### ISSUE TITLE
PCL2.6.2快照版无法使用

### ISSUE THREAD

**Issue by Ailzr** [Hex-Dragon/PCL2#1943]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

2.6.2快照版打不开
2.6.1正式版可以正常使用
系统版本是Windows11 22H2

### 重现步骤

打开PCL启动器(2.6.2快照版)无任何反应。

### 日志与附件

未自动创建PCL文件夹

**Comment by LTCatt** [comment]
已修复，查看爱发电私信重新下载即可
