### ISSUE TITLE
“版本隔离”提示框位置显示错误

### ISSUE THREAD

**Issue by amd64github** [Hex-Dragon/PCL2#1944]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

“版本隔离”提示框完全超出PCL2窗口

### 重现步骤

1、打开PCL
2、将PCL窗口移至屏幕右侧
3、在“设置”--“游戏”中找到“版本隔离”
4、展开”版本隔离“
5、将鼠标移至“隔离非正式版”上
6、发现此项的说明在PCL窗口左边

### 日志与附件

此bug无需日志

**Comment by YUANXINGlingyun** [comment]
吾，已初步确认
该位置选项提示都会出现在错误位置上
![image](https://github.com/Hex-Dragon/PCL2/assets/109946426/178cd5ac-2f7d-4d63-862f-8b5630628a8d)
![image](https://github.com/Hex-Dragon/PCL2/assets/109946426/14d31eca-a6f2-4522-99cc-0bfb3467acf2)
![image](https://github.com/Hex-Dragon/PCL2/assets/109946426/8239cafc-7451-47de-86e4-7778d9ba690b)

**Comment by Chiloven945** [comment]
应该是只要提示超出屏幕都会以错误的位置显示，但部分没有这个问题，我这边是Java选择是正常位置

**Comment by amd64github** [comment]
解锁 活跃橙 直接在这里发识别码吗
2F29-1487-6648-49D9

**Comment by LTCatt** [comment]
你的解锁码：3nADLCh2PhurL6bYU/QoeYDl2ckCwllD
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
