### ISSUE TITLE
在更改皮肤选择文件对文件右键会导致PCL2崩溃

### ISSUE THREAD

**Issue by wdnmd23333fdhsuidus** [Hex-Dragon/PCL2#1945]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在选择皮肤界面对着任意文件右键会让PCL2冻结一段时间后崩溃

### 重现步骤

https://github.com/Hex-Dragon/PCL2/assets/81455657/ff22c729-2b22-4242-b95d-1f80d8c2159f

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11626431/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11626433/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11626435/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11626436/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11626439/Log2.txt)

**Comment by wdnmd23333fdhsuidus** [comment]
https://github.com/Hex-Dragon/PCL2/assets/81455657/9f87a9b3-08c2-4c27-974e-63686ab58504

**Comment by Chiloven945** [comment]
无法复现……
请尝试排除系统问题？

**Comment by youzi-2333** [comment]
无法复现，Log 中也没有详细的相关信息。
即使 Bug 真实存在，也不是 PCL 的问题，因为 PCL 通过调用系统方法来选择文件。
也许是第三方应用创建了过多的右键菜单项，内存不足导致的崩溃，可以用一些杀软进行管理……
ChatGPT 回答是读取文件出错，但是我感觉不像……

**Comment by LTCatt** [comment]
系统环境问题，无法修复
