### ISSUE TITLE
在更新报错窗口新增“去爱发电下载选项”

### ISSUE THREAD

**Issue by deep-dark-forest** [Hex-Dragon/PCL2#1950]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

![image](https://github.com/Hex-Dragon/PCL2/assets/131975043/de46f6a2-7dbc-470f-ae5c-46573d77c070)
在这个窗口，新增一个按钮，点击以后将会打开龙猫的爱发电主页-动态，https://afdian.net/a/LTCat?tab=feed

### 原因

如果更新失败了，那么就去爱发电官网下载个最新版替换即可，要不然更新失败了还需要手动打开爱发电搜索龙猫，特别麻烦

**Comment by LTCatt** [comment]
手动替换文件即可，无需去爱发电重新下载
