### ISSUE TITLE
下载进度百分比问题

### ISSUE THREAD

**Issue by Bandysol** [Hex-Dragon/PCL2#1956]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

同时进行两个下载任务，其中一个完成后，下载总进度百分比不是未完成的下载任务的百分比。

### 重现步骤

1.开启两个下载任务
2.其中一个完成
3.观察左侧的“总进度”和下载任务的百分比
（建议使用大小相差巨大的文件）

### 日志与附件

好像用不着，需要再发

**Comment by LTCatt** [comment]
这是预期情况。这样的话，在后台挂着的时候，你才能通过任务栏进度条看到综合进度。

**Comment by TuanZiGit** [comment]
没清理旧的任务进度？
