### ISSUE TITLE
按已下载大小显示进度

### ISSUE THREAD

**Issue by Bandysol** [Hex-Dragon/PCL2#1957]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在下载任务中提示已下载大小，就像这样：
（3.3GB\10GB）

### 原因

Emmmmm，都算出来下载百分比了，加一个应该不难吧
可以直接 文件大小*百分比 （bushi

**Comment by LTCatt** [comment]
很多 MC 安装任务的总文件大小是实时变化的，所以这并不能在所有情况下反应下载进度，反而会带来误导。
