### ISSUE TITLE
给了管理员权限了但补全文件时还是不够权限

### ISSUE THREAD

**Issue by michicken** [Hex-Dragon/PCL2#1958]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我已经给了管理员权限了，但是启动游戏时补全文件还是提示不够权限。
![image](https://github.com/Hex-Dragon/PCL2/assets/87221035/84d32c17-830c-4dc0-a48d-809f8b25ed24)
![image](https://github.com/Hex-Dragon/PCL2/assets/87221035/6111bbc3-3fa2-4510-b651-9f97d7b17798)

### 重现步骤

1、补全文件
2、报错，无法启动，所有版本都一样

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11641842/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11641843/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11641844/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11641845/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11641846/Log1.txt)

**Comment by LTCatt** [comment]
没有权限不是我可以解决的问题。
尝试把这个文件夹删了
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/5fe42d03-cebd-4b8a-841b-6c94db1354ae)

 如果还是不行我也没办法……
