### ISSUE TITLE
增加主页刷新功能

### ISSUE THREAD

**Issue by Chormore-EDGE** [Hex-Dragon/PCL2#1959]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在启动页面增加一个刷新按钮

### 原因

有助于刷新新闻主页，每次关闭打开挺麻烦的

**Comment by iPodtouch6557** [comment]
除非是自己做的没这功能，或者自己不会做，还是有必要的
但是bugjump页面是有这个的

**Comment by WForst-Breeze** [comment]
你可以通过在主页添加一个 `EventType="刷新主页"` 的按钮来获取一个可以刷新主页的按钮，Light Beacon 的新闻主页有此功能。个人感觉不太会添加（
