### ISSUE TITLE
加入ARM64启动支持

### ISSUE THREAD

**Issue by GBC034** [Hex-Dragon/PCL2#1960]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

在Windows ARM的系统上启动Minecraft

### 原因

Mojang在23w16a中加入了对Windows ARM64的支持
微软在OpenJDK中贡献了对Windows ARM的支持

**Comment by LTCatt** [comment]
我没有 WoA 的设备能用于测试，所以抱歉暂时不考虑 :(

**Comment by i486-DX9** [comment]
……
骁龙845/855有设备可以刷WoA
