### ISSUE TITLE
启动器自动搜索JAVA时有时搜不到以前搜得到的JAVA

### ISSUE THREAD

**Issue by ShineSunsun** [Hex-Dragon/PCL2#1962]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

普遍出现在打开启动器后的自动后台搜索JAVA中，有时需要手动点击好几次“自动搜索JAVA”才能找到其他原先未找到的JAVA（我说怎么运行不了1.8,只剩个JDK17了）

### 重现步骤

无

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11642316/Log1.txt)

**Comment by WForst-Breeze** [comment]
注：日志自 723 行起为反馈者提及的问题出现段

**Comment by LTCatt** [comment]
这是个已知但无法修复的 Bug……我真没办法.jpg
