### ISSUE TITLE
增加服务器端下载，并自动配置服务器启动脚本

### ISSUE THREAD

**Issue by zc20512** [Hex-Dragon/PCL2#1963]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

可以直接在PCL2中开启服务器

### 原因

我需要这个功能来开服。很多人都有开服的需求。也可以在作者同意的情况下直接将现成开服器并入PCL2.

**Comment by iPodtouch6557** [comment]
**LAUNCHER!**
以及重复了

**Comment by WForst-Breeze** [comment]
PCL2 是启动器，这是开服工具的工作，超出了 PCL2 的 范畴
