### ISSUE TITLE
最新PCL会被莫名其妙删除

### ISSUE THREAD

**Issue by wuxinkuliu** [Hex-Dragon/PCL2#1970]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

电脑开机之后所有文件夹都找不到启动器

### 重现步骤

每次电脑关机再开启pcl就会消失

### 日志与附件

[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11644557/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11644558/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11644559/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11644560/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11644561/Log3.txt)

**Comment by wuxinkuliu** [comment]
已确认杀毒软件包括系统自带没有任何删除提示。

**Comment by WorldHim** [comment]
> 已确认杀毒软件包括系统自带没有任何删除提示。

你的意思是：重启电脑后原存在于处的 PCL 启动器本体消失？
建议自查杀毒软件（没有提示不代表杀毒软件没采取措施

**Comment by wuxinkuliu** [comment]
![uTools_1685842452714](https://github.com/Hex-Dragon/PCL2/assets/78304869/b525431c-1a6b-4f06-8e81-af80a57de7f1)
![屏幕截图 2023-06-04 093530](https://github.com/Hex-Dragon/PCL2/assets/78304869/82d69836-b3b1-43f2-994c-20cfa8750658)

**Comment by wuxinkuliu** [comment]
所有方法都尝试了，还添加了信任重启之后依然消失，电脑不关机就没事

**Comment by WForst-Breeze** [comment]
您是否在 Windows Defener 中添加排除项？现在 WD 会静默删除 PCL2 快照版而不留下任何提示

**Comment by wuxinkuliu** [comment]
我现在尝试一下，明天反馈处理结果

**Comment by LTCatt** [comment]
也可以用火绒添加自定义防护，可以在程序删除 PCL 时显示提示并且拦截。
但总之这个不是我能解决的问题，抱歉 :/

**Comment by iPodtouch6557** [comment]
近期 #666 有人给出了极为详细的原因和解决办法，可以自己去翻翻看
