### ISSUE TITLE
打开Minecraft时错误提示您的我的世界账户不可用

### ISSUE THREAD

**Issue by WJC20120518** [Hex-Dragon/PCL2#1973]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃不是 PCL2 的原因，请 **不要** 提交反馈。你可以在 QQ 群里或者论坛找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是游戏本身的问题，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

打开Minecraft时错误提示您的我的世界账户不可用

### 错误报告、日志与附件

打开Minecraft时错误提示您的我的世界账户不可用

**Comment by bwtx2023** [comment]
上传启动器日志和相关截图

**Comment by WJC20120518** [comment]
e







                       
原始邮件
                       
                     

发件人："bwtx1981"< ***@***.*** &gt;;

发件时间：2023/6/4 13:30

收件人："Hex-Dragon/PCL2"< ***@***.*** &gt;;

抄送人："WJC20120518"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [Hex-Dragon/PCL2] 打开Minecraft时错误提示您的我的世界账户不可用 (Issue #1973)




 
上传启动器日志和相关截图
 
&mdash;

**Comment by FangFuJi1991** [comment]
应该是微软服务器日常抽风（应该吧

**Comment by WJC20120518** [comment]
你是？龙猫吗







                       
原始邮件
                       
                     

发件人："FangFuJi"< ***@***.*** &gt;;

发件时间：2023/6/4 13:52

收件人："Hex-Dragon/PCL2"< ***@***.*** &gt;;

抄送人："WJC20120518"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [Hex-Dragon/PCL2] 打开Minecraft时错误提示您的我的世界账户不可用 (Issue #1973)




 
应该是微软服务器日常抽风（应该吧
 
&mdash;

**Comment by FangFuJi1991** [comment]
> 你是？龙猫吗 原始邮件 发件人："FangFuJi"< ***@***.*** &gt;; 发件时间：2023/6/4 13:52 收件人："Hex-Dragon/PCL2"< ***@***.*** &gt;; 抄送人："WJC20120518"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;; 主题：Re: [Hex-Dragon/PCL2] 打开Minecraft时错误提示您的我的世界账户不可用 (Issue #1973) 应该是微软服务器日常抽风（应该吧 &mdash; Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

no，你但凡看下我名字

**Comment by WJC20120518** [comment]
《防腐剂》







                       
原始邮件
                       
                     

发件人："FangFuJi"< ***@***.*** &gt;;

发件时间：2023/6/4 13:57

收件人："Hex-Dragon/PCL2"< ***@***.*** &gt;;

抄送人："WJC20120518"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [Hex-Dragon/PCL2] 打开Minecraft时错误提示您的我的世界账户不可用 (Issue #1973)




  
你是？龙猫吗 原始邮件 发件人："FangFuJi"< @.*** &gt;; 发件时间：2023/6/4 13:52 收件人："Hex-Dragon/PCL2"< @.*** &gt;; 抄送人："WJC20120518"< @.*** &gt;;"Author"< @.*** &gt;; 主题：Re: [Hex-Dragon/PCL2] 打开Minecraft时错误提示您的我的世界账户不可用 (Issue #1973) 应该是微软服务器日常抽风（应该吧 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
no，你但凡看下我名字
 
&mdash;

**Comment by bwtx2023** [comment]
不要直接在邮件App里回复，上 GitHub 网页或者 Mobile 端回复

**Comment by LTCatt** [comment]
这不是启动器可以修复的问题 :(
