### ISSUE TITLE
希望龙猫给pcl添加签名证书

### ISSUE THREAD

**Issue by nhx100218** [Hex-Dragon/PCL2#1974]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

给PCL添加签名证书，不知道要不要很多money，或者让用户自己颁发根机构证书，目前只有属性里可以看到版权

### 原因

不添加证书老是在执行更新，内存优化 (新)等弹出位置发布者的黄色框，而且经常动不动被杀毒软件杀掉_(例如Windows安全中心)_，现在B站上很多自签名证书软件，不知道可不可以
![屏幕截图 2023-06-04 190126](https://github.com/Hex-Dragon/PCL2/assets/104252001/faa1f4ef-7f74-466f-a59c-66e302798809)
![屏幕截图 2023-06-04 190156](https://github.com/Hex-Dragon/PCL2/assets/104252001/15fc70f6-c8c3-4e42-ab0c-2183cc96887a)
![屏幕截图 2023-06-04 190146](https://github.com/Hex-Dragon/PCL2/assets/104252001/95d2db0a-03bd-4248-93f8-5dd83bcd8b29)
![image](https://github.com/Hex-Dragon/PCL2/assets/104252001/d531efd3-60b1-4e8b-9650-b14669bcae3d)

**Comment by bwtx2023** [comment]
一张签名挺贵的来着，我记得之前启动器联盟有合资购买过证书，后来不知为何被吊销了

**Comment by LTCatt** [comment]
……@ZhaiSoul 救

**Comment by Louis-ZYH** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/115140320/3e6e4144-5403-4c44-8792-804a67494547)
已经吃上了

**Comment by LTCatt** [comment]
由于 PCL 快照版更新的加密系统限制，快照版无法添加数字证书，不过倒是给正式版折腾上了 =。=

**Comment by nhx100218** [comment]
我的PCL识别码：CADF-5029-3E4A-8CE4。麻烦龙猫给一下活跃橙解锁密钥，谢谢！！！

**Comment by WForst-Breeze** [comment]
> 我的PCL识别码：CADF-5029-3E4A-8CE4。麻烦龙猫给一下活跃橙解锁密钥，谢谢！！！

很抱歉，优化建议无法获得活跃橙
