### ISSUE TITLE
自定义游戏标题会bug

### ISSUE THREAD

**Issue by Chormore-EDGE** [Hex-Dragon/PCL2#1976]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

改完名字：如图
![image](https://github.com/Hex-Dragon/PCL2/assets/114737601/36083164-6fac-4d09-bc1a-9d871bc75aca)
会在《Minecraft*1.19.3》之间来回切换

### 重现步骤

1、改名称（添加标签）
![image](https://github.com/Hex-Dragon/PCL2/assets/114737601/83d16886-ff5f-405c-a68d-61e77faf9054)

2、启动，进入服务器
3.观察标题栏

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11645593/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11645594/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11645595/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11645596/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11645597/Log5.txt)

**Comment by LTCatt** [comment]
这是因为高版本 MC 自己会尝试反复设置标题，没有办法解决。
