### ISSUE TITLE
程序所在文件夹时间在程序启动时被修改

### ISSUE THREAD

**Issue by qingju32** [Hex-Dragon/PCL2#1980]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

由于程序没有给出放置位置的提示，认为是个绿色软件就没有新建文件夹来存放它，而是将其放在了如图所示的位置。
现在每次启动程序时，所有文件夹的修改时间都会被刷新一遍。
<img width="713" alt="Snipaste_2023-06-05_21-26-15" src="https://github.com/Hex-Dragon/PCL2/assets/40858189/20a2d180-4915-4470-8458-c0e8142de4e3">

### 重现步骤

版本	Windows 11 专业版
版本	22H2
安装日期	‎2023/‎3/‎12
操作系统版本	22631.1830
体验	Windows Feature Experience Pack 1000.22642.1000.0

Plain Craft Launcher 2
当前版本：Snapshot2.6.2(294.0)

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11653023/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11653024/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11653025/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11653026/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11653027/Log5.txt)

**Comment by iPodtouch6557** [comment]
我也亲眼见过并验证过我的 win10 会出现这个问题，但是只影响 PCL 运行时用到的文件夹，如存放本体的文件夹，或是 .minecraft 文件夹
但是这个问题看上去好像不太大，我个人认为除非有必要其实不用管，毕竟一般人不注意这个

**Comment by qingju32** [comment]
能直接移动exe吗？它老是改我其他文件夹肯定不行，关键没提示。

**Comment by qingju32** [comment]
解锁皮肤

**Comment by qingju32** [comment]
这么严重的bug居然被你们忽略了，再见！

**Comment by WForst-Breeze** [comment]
> 这么严重的bug居然被你们忽略了，再见！

由于此问题不影响启动器正常使用，因此被忽略。如果您有相关信息表明此问题会使得启动器无法完成某些操作或功能，可以在下方补充，我们会继续受理

**Comment by qingju32** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/40858189/4ef9cdef-f6de-4c5f-943d-9501e6e3b311)
好了好了，开玩笑的
