### ISSUE TITLE
搜不到 `通用拼音搜索` mod

### ISSUE THREAD

**Issue by L-dyy** [Hex-Dragon/PCL2#1982]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

搜索不到特定mod？确认了没有任何多余的空格，直接从cf上复制的
![image](https://github.com/Hex-Dragon/PCL2/assets/55521032/ca6698c4-7c44-4501-ae3d-095153a2988b)

### 重现步骤

1、复制 Just Enough Characters
2、下载 -> mod -> 搜索框中输入 -> Just Enough Characters -> 搜索

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11654214/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11654217/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11654218/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11654219/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11654220/Log5.txt)

**Comment by LTCatt** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/f95f81e0-28d9-44fa-8c0b-cf01f8a6fa03)

搜得到，只是因为傻逼 curseforge 的排序问题，它甚至不在前几页……得多加点筛选条件……
这个我也没办法修，curseforge 的脑残算法

**Comment by L-dyy** [comment]
oh, 这真的太酷了，这完全符合我对Curseforge的想象。
