### ISSUE TITLE
memory clear

### ISSUE THREAD

**Issue by hellominecraftlauncher** [Hex-Dragon/PCL2#1984]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

win11在文件路径后面加了--memory后，管理员运行，进程不显示，任务管理器没有，建议优化一下

### 原因

建议在内存清理途中加一个GUI显示内存清理中或者是内存清理中的通知框（有一个兼容win7的，可参考openfrp）

**Comment by Yue-cn** [comment]
首先，我不背这锅。
其次，我们家App 压根就没有这功能。**你是在哪听的**
还有，您是刚用Github？

**Comment by hejiehao** [comment]
wow，上学的时候语文0分还是根本连语文都没学过

**Comment by SuoHouDaiShi** [comment]
首先 这玩意是有效果的 您压根就是不愿意切换到“性能”选项卡看一眼内存使用率
其次 你确定你学过语文？什么是**“静默”**你难道不知道？
最后 _如果不会用Github或者认为Github是一个论坛，_那就请你**别用Github了**，还是去_贴吧_吧

https://github.com/Hex-Dragon/PCL2/assets/119282947/fe7278f9-a161-4131-83a9-d2f509a8be16
