### ISSUE TITLE
【安全】建议暂时禁用 Curseforge 下载渠道以避免恶意模组进一步传播，或在下载前给予用户强提醒以告知危险性。

### ISSUE THREAD

**Issue by LittleCircleOO** [Hex-Dragon/PCL2#1990]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

6月7日上午，已有多个模组作者发布公告，警告玩家 Curseforge 上潜在的安全漏洞，截至几个小时前，数十种模组及其整合包，主要是在1.16.5、1.18.2和1.19.2上的模组已被更新，包括恶意文件。
详情请见：
1. [!ALERT! Security vulnerability in the CurseForge and Bukkit platform](https://prismlauncher.org/news/cf-compromised-alert/)
2. [目前请不要在CurseForge下载模组或整合包](https://www.bilibili.com/read/cv24184930)
3. [【紧急/扩散】不要从 Curseforge 下载模组或者整合包](https://www.bilibili.com/video/av784527437/)
4. [\[警告\] 黑客团体正在使用病毒攻击MC资源网站](https://www.bilibili.com/video/av699620234/)

目前已知 Curseforge 上的以下模组/整合包已受到影响：
* Dungeons Arise
* Sky Villages
* Better MC modpack series
* ~~Fabuously Optimized~~ (Found to not be compromised)
* Dungeonz
* Skyblock Core
* Vault Integrations
* AutoBroadcast
* Museum Curator Advanced
* Vault Integrations Bug fix
* Create Infernal Expansion Plus - Mod removed from CurseForge
建议在漏洞得到修补前，临时禁用 Curseforge 源的下载渠道；或在用户尝试使用 Curseforge 时给出强提醒。

### 重现步骤

目前在下载页，仍可通过 Curseforge 下载模组与整合包；建议及时转向 Modrinth 下载源。

### 日志与附件

暂无

**Comment by YUANXINGlingyun** [comment]
这个漏洞涉及安全性问题
@LTCATT

**Comment by Chiloven945** [comment]
o我刚刚发了个讨论

**Comment by LittleCircleOO** [comment]
> o我刚刚发了个讨论 Fabuously Optimized已被确认为无任何影响
> 
> ## ![image](https://user-images.githubusercontent.com/116699482/244021361-0a38c356-853e-478b-8f3a-f9a248e42b53.png)
> 完全禁用我倒觉得没必要，可以通过发公告的方式来进行提示

初步构想是将 Modrinth 设为默认，当用户切换为 Curseforge 时给予警告提示。

**Comment by Chiloven945** [comment]
> 初步构想是将 Modrinth 设为默认，当用户切换为 Curseforge 时给予警告提示。

但是大多数的mod及整合包目前都只上传于curseforge，目前来说modirinth还是没有curseforge全面的

**Comment by iPodtouch6557** [comment]
这个紧急加了并且发布后没多久可能就被修复了，所以即时性过强，大概率会拒绝
除非这个安全问题严重到非加这个不可……

**Comment by iPodtouch6557** [comment]
其实还是即时性过强的问题……
