### ISSUE TITLE
在下载自定义文件处加一个打开目标文件夹的按钮

### ISSUE THREAD

**Issue by xtrackc1437** [Hex-Dragon/PCL2#1992]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

就在下载自定义文件夹 选择文件夹那里，加一个一键打开目标文件夹的快捷键

### 原因

这样可以 ~~让PCL下载器更好用~~
这样一个小功能加进去应该也不费力吧(猜测

**Comment by bwtx2023** [comment]
不是已经有了吗
