### ISSUE TITLE
关闭游戏后背景音乐报错

### ISSUE THREAD

**Issue by hhhh17488** [Hex-Dragon/PCL2#2001]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

关闭游戏后出现
看起来像背景音乐出了问题

### 重现步骤

在关闭游戏后随缘出现
非常随缘

### 日志与附件

![Snipaste_2023-06-08_21-37-10](https://github.com/Hex-Dragon/PCL2/assets/110822585/813ece10-bf1d-471f-9f2f-ee516cded41d)
[Log.txt](https://github.com/Hex-Dragon/PCL2/files/11688974/Log.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11688975/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11688976/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11688977/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11688978/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11688979/Log5.txt)

**Comment by youzi-2333** [comment]
错误是从 NAudio 那里抛出来的，大概率修不好……

以下是 ChatGPT 给出的回答，可以用作参考。
> “NoDriver calling waveOutRestart”的错误通常是由于音频设备驱动程序问题引起的。您可能需要更新音频驱动程序或安装新的音频驱动程序。您还可以尝试在程序中改变音频输出设备来确定问题是否与您当前使用的音频设备相关。此外，您可以在程序中添加异常处理程序来捕获和记录错误，以帮助进一步排除问题所在。

**Comment by LTCatt** [comment]
无法解决，这是外部的报错 :(
