### ISSUE TITLE
无法进行多人游戏？

### ISSUE THREAD

**Issue by MM-Rabbit** [Hex-Dragon/PCL2#2004]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

和账号被封的情况一模一样，无法多人游戏。

### 重现步骤

1、启动Minecraft 1.16.5

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11704179/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11704181/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11704182/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11704183/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11704184/Log1.txt)
![awa](https://github.com/Hex-Dragon/PCL2/assets/118085239/ec304c9d-b81a-41b4-9c12-7dd793848381)
[1.16.5.zip](https://github.com/Hex-Dragon/PCL2/files/11704202/1.16.5.zip)

**Comment by MM-Rabbit** [comment]
就离谱

**Comment by WForst-Breeze** [comment]
#2003 提及了该问题，非 PCL2 问题，HMCL 离线模式也会出现该问题。在 #2003 中，我给出了两种解决方案，可以作临时参考。先开着看看龙猫怎么说

**Comment by LTCatt** [comment]
处理这个超出启动器范围了 :/
