### ISSUE TITLE
加入繁體中文

### ISSUE THREAD

**Issue by YuXuan2611** [Hex-Dragon/PCL2#2005]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

加入繁體中文的語言選項

### 原因

我需要这个功能来加入繁體中文。

**Comment by youzi-2333** [comment]
您好，

#119 提及该问题被拒绝。因涉及页面重新布局、下载源国际适配、第三方网站国际适配、翻译等问题，暂时不计划制作。

下次提交 Issue 前，请先在 Issues 页面搜索，也可以参考 #1930 检查是否有重复内容，感谢您的反馈~

**Comment by JingHai-Lingyun** [comment]
繁体中文呢...
我认为与 #119 提及的多(国外)语言有点区别
