### ISSUE TITLE
PCL登录窗口字体问题

### ISSUE THREAD

**Issue by HanXiaozeng** [Hex-Dragon/PCL2#2010]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

看图片

![image](https://github.com/Hex-Dragon/PCL2/assets/110365422/f1130376-47d2-463d-8433-7026b647433a)
![image](https://github.com/Hex-Dragon/PCL2/assets/110365422/6b078fa9-2f11-4ad4-9c4f-ef8c4c25e49f)

### 原因

这个字体看着就不舒服

**Comment by iPodtouch6557** [comment]
印象中我是正常的，可能是你的屏幕分辨率的问题

**Comment by HanXiaozeng** [comment]
***@***.***

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年6月10日 7:47
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [Hex-Dragon/PCL2] PCL登录窗口字体问题 (Issue #2010)


印象中我是正常的，可能是你的屏幕分辨率的问题

―

**Comment by JingHai-Lingyun** [comment]
浏览器窗口放太大了?

**Comment by HanXiaozeng** [comment]
并没有放太大，我的窗口大小没有改动

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年6月10日 11:21
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [Hex-Dragon/PCL2] PCL登录窗口字体问题 (Issue #2010)


浏览器窗口放太大了?

―

**Comment by LTCatt** [comment]
这个网页是微软提供的，我没有办法 :/
