### ISSUE TITLE
头像下面有毛边

### ISSUE THREAD

**Issue by quannen** [Hex-Dragon/PCL2#2012]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在更新登录模块后，头像下面出现了毛边。

### 原因

强迫症晚期震怒

**Comment by quannen** [comment]
![Plain Craft Launcher 2　 2023_6_10 11_13_51](https://github.com/Hex-Dragon/PCL2/assets/118090890/3a13effd-0190-4610-a42d-bdd2678e38be)

**Comment by JingHai-Lingyun** [comment]
皮肤导致的?

**Comment by quannen** [comment]
以前没有
