### ISSUE TITLE
输入字符串的格式不正确 无法打开启动器

### ISSUE THREAD

**Issue by KIJINSEIJA47** [Hex-Dragon/PCL2#2019]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

打开pcl弹出窗口未知错误输入字符串的格式不正确。

### 重现步骤

打开启动器

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11712198/Log1.txt)

**Comment by WorldHim** [comment]
请上传错误截图。
可以试试清空配置文件夹。（即删除与启动器本体同一目录下的 `PCL` 文件夹）

**Comment by youzi-2333** [comment]
> Conversion from string "776.8" to type 'Double' is not valid.

不应该啊……
先参考楼上方法试试？

**Comment by LTCatt** [comment]
重新下载启动器，文件可能已经损坏了。

**Comment by KIJINSEIJA47** [comment]
已尝试删除appdata/local下的pcl文件和重新下载整合 还是弹出一样的窗口

**Comment by KIJINSEIJA47** [comment]
![捕获](https://github.com/Hex-Dragon/PCL2/assets/84613469/034d59c3-8756-4a20-a43f-4cacd1950ada)
