### ISSUE TITLE
“功能隐藏”bug

### ISSUE THREAD

**Issue by Creeper-JXC** [Hex-Dragon/PCL2#2022]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

如果选“更多”会连着启动一起隐藏

### 原因

（示例）
这项优化让我可以更方便地xxxx。
如果没有这项优化，我每次都必须xxxx，让操作变得很麻烦。

**Comment by JingHai-Lingyun** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/109946426/b96a41d5-bff9-4174-8653-3fe7378b727e)
无法复现，请提供更多信息

**Comment by WForst-Breeze** [comment]
如果你预先隐藏了 “下载” 和 “设置”，此时点击 “更多” 会隐藏所有页面。这是刻意的设计
