### ISSUE TITLE
增加自定义xaml控件

### ISSUE THREAD

**Issue by RedStone-Noob** [Hex-Dragon/PCL2#2029]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

在PCL自定义xaml这方面增加控件
比如combobox、textedit

好像这个东西很冷门qwq

### 原因

我认为PCL2在自定义这方面遥遥领先，所以希望做成特色qwq

**Comment by LTCatt** [comment]
没办法实现控件的加载，你可以试试用资源绑定？

**Comment by RedStone-Noob** [comment]
不是这个意思

我是说提供一些PCL2风格的控件







                       
原始邮件
                       
                     

发件人："龙腾猫跃"< ***@***.*** &gt;;

发件时间：2023/6/11 17:32

收件人："Hex-Dragon/PCL2"< ***@***.*** &gt;;

抄送人："RedStone-Noob"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [Hex-Dragon/PCL2] 增加自定义xaml控件 (Issue #2029)




 
没办法实现控件的加载，你可以试试用资源绑定？

**Comment by LTCatt** [comment]
你可以直接用 MyComboBox 和 MyTextBox 来把它们放出来，但是放出来之后没法写代码也发挥不了实际作用啊（
