### ISSUE TITLE
屑龙猫忘记更新release了

### ISSUE THREAD

**Issue by RedStone-Noob** [Hex-Dragon/PCL2#2030]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

release未及时更新

### 重现步骤

点开github仓库,看release

### 日志与附件

这是githubbug(恼

**Comment by JingHai-Lingyun** [comment]
没错啊 最新2.6.2
外面显示的是最后的正式版 (Release) , 即 2.6.1

**Comment by WForst-Breeze** [comment]
戳啦，已经更新辣，2.6.2 是 pre release
![image](https://github.com/Hex-Dragon/PCL2/assets/110760354/3b8516a4-8652-49da-9482-923cbe25291c)

**Comment by RedStone-Noob** [comment]
你这不也...








                       
原始邮件
                       
                     

发件人："风释清然SC"< ***@***.*** &gt;;

发件时间：2023/6/11 17:11

收件人："Hex-Dragon/PCL2"< ***@***.*** &gt;;

抄送人："RedStone-Noob"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [Hex-Dragon/PCL2] 屑龙猫忘记更新release了 (Issue #2030)




 
戳啦，已经更新辣，2.6.2 是 pre release
