### ISSUE TITLE
安装 OptiFine/Forge 失败：值不能为 null

### ISSUE THREAD

**Issue by Anruicat** [Hex-Dragon/PCL2#2031]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

下载 OptiFine 1.20 I5 pre3失败
→ 等待原版下载失败
→ 值不能为 null。
参数名: path
   在 PCL.ModDownloadLib._Closure$__18-0._Lambda$__1(LoaderTask`2 Task)
   在 PCL.ModLoader.LoaderTask`2._Closure$__12-0._Lambda$__0()
错误类型：System.ArgumentNullException

### 重现步骤

1、点击OptiFine 1.20 I5 pre3
2、点击安装，就这么简单的触发了。
能给个隐藏皮肤么（

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11714483/Log1.txt)
![屏幕截图 2023-06-11 193639](https://github.com/Hex-Dragon/PCL2/assets/121781099/f656cf90-c825-4022-b7ba-1f6d6bebbbd5)

**Comment by LBZiXL** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/115980764/75327137-2960-403b-91a9-0540dec63e68)
我这没问题呀

**Comment by youzi-2333** [comment]
> [19:40:43.992] [UI] 弹出提示：1.20-OptiFine_I5_pre3 安装成功！

这不是成功了么……
让龙猫看看前面几次失败能不能修好吧.jpg

**Comment by LTCatt** [comment]
无法复现，需要一个稳定的重现方法才能想办法修复 :/

**Comment by LTCatt** [comment]
考虑是偶发情况，如果有其他人也出现这个问题再考虑修复，抱歉 :/

**Comment by LTCatt** [comment]
@iwjsyt @zhanglaoMC @PaperDemiurge @Anruicat 
如果可以稳定出现这个报错，加我 QQ 1043137532，原因写 issue 2031

**Comment by hellominecraftlauncher** [comment]
> @iwjsyt @zhanglaoMC @PaperDemiurge @Anruicat 如果可以稳定出现这个报错，加我 QQ 1043137532，原因写 issue 2031

 那个1.12.2 G6 pre1的那个问题何杰豪说是下载地址不对，您看看能不能弄一下
正确的：https://bmclapi2.bangbang93.com/optifine/1.12.2/HD_U_G6/pre1
错误的：https://bmclapi2.bangbang93.com/optifine/1.12.2/HD_U_G6pre1

**Comment by hellominecraftlauncher** [comment]
用错误的地址是not found，正确的是正常下载optifine install

**Comment by LTCatt** [comment]
不是这个原因（叹气

**Comment by iPodtouch6557** [comment]
> 用错误的地址是not found

可是我用两个链接下载都下载到了（

**Comment by hellominecraftlauncher** [comment]
> > 用错误的地址是not found
> 
> 可是我用两个链接下载都下载到了（

![Uploading QQ截图20230723095425.png…]()

**Comment by LTCatt** [comment]
@hellominecraftlauncher 大哥，这个我都修过了，我说了这个 issue 不是这个原因，咋还头铁啊
真的，搞不懂不用硬来 github 秀

**Comment by NAILE114514** [comment]
一样什么版本都下载不了

**Comment by youzi-2333** [comment]
> 一样什么版本都下载不了

请确认 PCL 是最新版（`设置 => 启动器 => 检查更新`），并且确认报错是“值不能为 null”。
