### ISSUE TITLE
[优化] 重新安排百宝箱按钮的位置

### ISSUE THREAD

**Issue by youzi-2333** [Hex-Dragon/PCL2#2032]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

目前，在“内存优化”功能推出后，百宝箱按钮**在默认窗口大小下**已经超出范围。
需要将其改为两排，~~或者将千万别点按钮删除~~。
#1955 提及该问题，但是关掉了，我就重新提一下……

### 原因

增加观感，并且降低操作难度，避免用户拉大窗口导致操作麻烦……

**Comment by Chiloven945** [comment]
与 #1915 重复
