### ISSUE TITLE
高分屏下很糊

### ISSUE THREAD

**Issue by TuanZiGit** [Hex-Dragon/PCL2#2034]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在2560x1440下开启150%缩放后打开PCL，界面会显得很糊。

### 重现步骤

1. 使用高分辨率屏幕并切换缩放大于100%。
2. 打开PCL2
3. 糊.jpg

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11716515/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11716511/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11716512/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11716513/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11716514/Log5.txt)

**Comment by LTCatt** [comment]
发几张截图啊……

**Comment by TuanZiGit** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/46892455/ca7b9805-b839-4374-a821-7fa240ef38b5)
![image](https://github.com/Hex-Dragon/PCL2/assets/46892455/7ae4f014-8cce-4cbf-b2a4-7b816a8de868)
![image](https://github.com/Hex-Dragon/PCL2/assets/46892455/90ba5252-fdd1-472f-ac0a-ba6644acd5bc)

**Comment by LTCatt** [comment]
其他人有这个问题么……我咋感觉像是个例（
你右键属性看看高分屏行为？调调 exe 的属性看看行不行？

**Comment by TuanZiGit** [comment]
`高分屏行为->应用程序` 下会出现尺寸异常

**Comment by LTCatt** [comment]
我觉得是你的个别问题……挂了这么多天也没有人能复现……
能改属性解决就算了，如果其他人也出现了再说 :/

**Comment by SALTWOOD** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/105980161/1fe959ce-b9ec-42bd-a947-9e3de3d5f9b9)
复现成功，表现为2560x1440 + 150% 文字模糊不清
但是125%似乎不会

**Comment by LTCatt** [comment]
不知道怎么修，谁知道的话帮帮忙……

**Comment by LSGtorch** [comment]
笔记本电脑，使用其他软件时出现过类似情况

> 比如vape v4的注入界面

解决方法：
1.右键该exe文件，点击“属性”
2.点击上方“兼容性”

3.点击下方“更改高DPI设置”
![image](https://github.com/Hex-Dragon/PCL2/assets/115522101/94af07eb-1b66-44d8-863b-9cac50abea31)

4.勾选下方“替代高DPI缩放行为”
![image](https://github.com/Hex-Dragon/PCL2/assets/115522101/6d75cd6d-8ee0-4029-8447-f82620cfb8f6)

不知道行不行，建议试试

**Comment by LTCatt** [comment]
@TuanZiGit 试试楼上的做法管用么？
