### ISSUE TITLE
强制使用JAVA按钮不管用

### ISSUE THREAD

**Issue by Anythingteam** [Hex-Dragon/PCL2#2039]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/Hex-Dragon/PCL2/assets/103157696/3d054698-f3c8-4095-bea9-c424f1639825)
这个问题需要接着幽灵JDK21来看
既然JAVA已经不存在，那点击强制使用后应该提示“JAVA不存在”或是其他什么
它现在则是点了以后窗口消失，但马上出现。。。

https://github.com/Hex-Dragon/PCL2/assets/103157696/d166da8f-ffd3-4584-a01c-524445677fe3

### 重现步骤

1、无需描述，看描述即可

### 日志与附件

[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11723023/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11723024/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11723025/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11723026/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11723027/Log3.txt)

**Comment by LTCatt** [comment]
你可以直接和 #2038 合并……
