### ISSUE TITLE
资源下载版本分类选项中无 1.20.1

### ISSUE THREAD

**Issue by WForst-Breeze** [Hex-Dragon/PCL2#2044]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如题，资源下载版本分类中无 1.20.1。

不知道是同步一下最新版本号还是再等等……？毕竟手动输入版本号也不是不能用（）看您怎么想好啦~

### 重现步骤

前往查看 **下载-资源-Mod/整合包-版本** 即可

### 日志与附件

![image](https://github.com/Hex-Dragon/PCL2/assets/110760354/6c458aa4-1f2c-4f6d-8888-28e7d638029b)

**Comment by Chiloven945** [comment]
不一般不是主要的版本都不会有吗🤔
