### ISSUE TITLE
部分mod需要JDK11报错时的错误分析检测优化

### ISSUE THREAD

**Issue by SorrowRain** [Hex-Dragon/PCL2#2048]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

部分低版本mod/整合包需要JDK11运行，PCL2无法检测，会自动选择JRE8
启动报错后无法检测到错误原因，可以根据报错日志关键句优化检测。

关键句：`Caused by: java.lang.UnsupportedClassVersionError: icyllis/modernui/forge/MixinConnector has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

[错误报告-2023-6-15_12.34.18.zip](https://github.com/Hex-Dragon/PCL2/files/11759993/-2023-6-15_12.34.18.zip)

### 原因

这项优化让我可以更方便地xxxx。
如果没有这项优化，我每次都必须xxxx，让操作变得很麻烦。

**Comment by zkitefly** [comment]
正好我想要添加……

**Comment by zkitefly** [comment]
已发 PR ：https://github.com/Hex-Dragon/PCL2/pull/2055

使用了两个关键词定位：
```
java.lang.UnsupportedClassVersionError: icyllis/modernui/forge/MixinConnector has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

java.lang.RuntimeException: java.lang.NoSuchMethodException: no such method: sun.misc.Unsafe.defineAnonymousClass(Class,byte[],Object[])Class/invokeVirtual
```
