### ISSUE TITLE
PCL对于Java 17以上启动出现错误

### ISSUE THREAD

**Issue by lyk3335** [Hex-Dragon/PCL2#2050]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃不是 PCL2 的原因，请 **不要** 提交反馈。你可以在 QQ 群里或者论坛找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是游戏本身的问题，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

出现弹窗显示无法创建JVM

### 错误报告、日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11766605/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11766606/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11766607/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11766608/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11766609/Log1.txt)
![18950e176e9809e2c53441d92998a8b6ba32146e554d7d0d416f35c86ac1290eQzpcVXNlcnNcODYxMzhcQXBwRGF0YVxSb2FtaW5nXERpbmdUYWxrXDE2ODA1OTM0MF92MlxJbWFnZUZpbGVzXDE2ODY4OTQzODI4MjVfNTkyQURBQTctOTE2NS00OTgwLUFENzEtMEZCNkM3QThCRjBBLnBuZw==](https://github.com/Hex-Dragon/PCL2/assets/103364718/61d1ed71-cf05-442d-b669-efab9c5d7598)

**Comment by lyk3335** [comment]
实际是JVM参数问题

**Comment by MCfans001** [comment]
现在搞明白为什么了吗，怎么才能解决，我也开始走前辈的老路了qwq

**Comment by burningtnt** [comment]
重装 Java 即可，你的 Java 损坏了
