### ISSUE TITLE
游戏窗口自定义大小出现问题

### ISSUE THREAD

**Issue by yanhanv** [Hex-Dragon/PCL2#2051]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

启动器，自定义游戏窗口大小。
![image](https://github.com/Hex-Dragon/PCL2/assets/74033012/624986ae-1bf4-498c-b8e1-f7760b44d292)

### 重现步骤

无

### 日志与附件

1
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11768993/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11768994/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11768995/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11768996/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11768997/Log4.txt)

**Comment by youzi-2333** [comment]
> 这个数值没法完全精确，因为不同系统环境下窗口标题栏和边框的大小不一致……所以大致是对的就行了 Orz ——龙腾猫跃（#1077）

不过根据截图，这个差的有点远吧……？

**Comment by LTCatt** [comment]
1.12.2 Forge 会导致高度设置无效，这是 Forge 的 Bug
