### ISSUE TITLE
Java自动选择有问题

### ISSUE THREAD

**Issue by Sinecre88888** [Hex-Dragon/PCL2#2052]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

就是启动Forge 1.12.2的时候，Java是自动选择，但我启动MC报错了，手动选择Java8再尝试启动MC，正常了
 Java压根没自动选择8

### 重现步骤

1. 
![1](https://github.com/Hex-Dragon/PCL2/assets/95292146/74056b18-9113-4df5-a2b9-9ca0b0a662a8)
2.
![2](https://github.com/Hex-Dragon/PCL2/assets/95292146/0a1ebf5d-1e9c-4b57-8aea-8d1bdfe643f9)
3.
![3](https://github.com/Hex-Dragon/PCL2/assets/95292146/130ed66d-be16-494d-9bb1-f9b6f0c03a4e)

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11770445/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11770448/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11770449/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11770450/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11770451/Log2.txt)

**Comment by LTCatt** [comment]
上传错误报告

**Comment by Sinecre88888** [comment]
> 上传错误报告
但我点击了“导出错误报告”按钮后，PCL目录并没有找到相关的zip文件

**Comment by youzi-2333** [comment]
> [20:53:11.069] [Crash] RawOutput.log 分类为 ExtraLog

从日志上看，PCL 把 `RawOutput.log` 分类为 `ExtraLog`，而不是正常的 `MinecraftLog`……
不知道啥问题。

**Comment by Sinecre88888** [comment]
> > [20:53:11.069] [Crash] RawOutput.log 分类为 ExtraLog
> 
> 从日志上看，PCL 把 `RawOutput.log` 分类为 `ExtraLog`，而不是正常的 `MinecraftLog`…… 不知道啥问题。

所以说这个bug没法修？看来龙猫的编程水平还得有待进步啊........白提交lssues了

**Comment by Sinecre88888** [comment]
活跃橙

**Comment by Sinecre88888** [comment]
所以活跃橙怎么弄doge

**Comment by youzi-2333** [comment]
识别码是 `D06D-3708-B2A8-4ADC` 吗……

**Comment by Sinecre88888** [comment]
> 上传错误报告

所以活跃橙怎么弄doge

**Comment by youzi-2333** [comment]
识别码是 `D06D-3708-B2A8-4ADC` 吗……

**Comment by Sinecre88888** [comment]
> 上传错误报告

245A-6BFA-A4BC-AD3A
活跃橙doge

**Comment by LTCatt** [comment]
你的解锁码：tdL63TsHCHzwxQ4q5zNbdk5+yoScVE5/
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by LTCatt** [comment]
你的解锁码：L5ajTSWdAJ62hVYfonl5YAbb0sLmeQ7S
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by w1024jk** [comment]
D45D-BAAE-E535-1AC9
