### ISSUE TITLE
登入失败:null

### ISSUE THREAD

**Issue by o7hx** [Hex-Dragon/PCL2#2056]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

进入服务器,游玩一段时间后会掉线,然后再点击登陆会显示登陆失败:null
只能关闭游戏重新启动才能正常登陆

### 重现步骤

1、打开游戏进入服务器
2、等待掉线或过一段时间后退出服务器
3,   再次点击进入服务器就进不去了

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11772627/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11772628/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11772629/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11772630/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11772631/Log1.txt)

**Comment by Chiloven945** [comment]
明显就不是PCL的问题而是自己网络的问题……

**Comment by o7hx** [comment]
我别的启动器就不会遇到

**Comment by LTCatt** [comment]
与启动器无关
