### ISSUE TITLE
正版登录不弹窗

### ISSUE THREAD

**Issue by zhang5249130** [Hex-Dragon/PCL2#2059]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/Hex-Dragon/PCL2/assets/96641164/5666d7f2-07e7-48d1-946c-7bbbc4f8b6fa)
图片见上，登录卡在5%，没有登陆弹窗，也没有弹出浏览器，就卡在这里
重启程序、重新下载PCL故障依旧
用的最新快照版

### 重现步骤

1、点击“登录”按钮

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11778314/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11778315/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11778316/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11778317/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11778318/Log5.txt)

**Comment by zhang5249130** [comment]
补充一下，不止一次这样了。之前也是突然登录卡柱，但是过几天自己又好了。现在又不行了

**Comment by JingHai-Lingyun** [comment]
从日志上来看只执行了微软登录步骤 1 之后就没有继续往下执行 2~5
```log
[16:04:48.683] [Control] 按下按钮：登录
[16:04:48.698] [Loader] 加载器 Loader Login Ms 状态改变：Loading
[16:04:48.714] [Launch] 登录方式：正版（尚未登录）
[16:04:48.717] [Launch] 开始微软登录步骤 1
[16:04:49.216] [Animation] 两个动画帧间隔 500 ms
[16:04:52.210] [Login] 已将登录窗口切换至浏览器
[16:04:53.710] [Control] 按下单选按钮：更多
```
难道你把登录取消了？从这个日志分析不出来为什么只执行了步骤 1

**Comment by LTCatt** [comment]
我怀疑是环境问题，导致浏览器出不来……
如果有其他人也出现这个问题再考虑修复。

**Comment by zhang5249130** [comment]
还有一个问题，在#2087，希望各位可以看看

**Comment by LTCatt** [comment]
考虑是偶发情况，如果有其他人也出现这个问题再考虑修复，抱歉 :/
