### ISSUE TITLE
1.5.2 以下版本json玩家名称参数前面多了两个减号 “--”

### ISSUE THREAD

**Issue by HowardZHY** [Hex-Dragon/PCL2#206]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

用户名前面会多两个横杠--

### 重现步骤

一键安装原版1.5.2以下
任意用户名，启动进入服务器会发现名字异常
原因是--username 参数未正确设置

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/9744234/Log1.txt)

**Comment by LTCatt** [comment]
![image](https://user-images.githubusercontent.com/40348278/198835376-2a0691d0-983b-4c81-8fde-d4f3b8271df9.png)

这是 Mojang 的问题，它在这里加了两个杠，但没有在游戏里去掉……

**Comment by HowardZHY** [comment]
官方启动器启动1.5.2以下用户名完全正常，与官方启动器的行为不一致就是自己的问题，不要甩给mojang

**Comment by HowardZHY** [comment]
{"assetIndex": {"id": "pre-1.6", "sha1": "3d8e55480977e32acd9844e545177e69a52f594b", "size": 74091, "totalSize": 49505710, "url": "https://launchermeta.mojang.com/v1/packages/3d8e55480977e32acd9844e545177e69a52f594b/pre-1.6.json"}, "assets": "pre-1.6", "complianceLevel": 0, "downloads": {"client": {"sha1": "465378c9dc2f779ae1d6e8046ebc46fb53a57968", "size": 5564661, "url": "https://launcher.mojang.com/v1/objects/465378c9dc2f779ae1d6e8046ebc46fb53a57968/client.jar"}, "server": {"sha1": "f9ae3f651319151ce99a0bfad6b34fa16eb6775f", "size": 2360903, "url": "https://launcher.mojang.com/v1/objects/f9ae3f651319151ce99a0bfad6b34fa16eb6775f/server.jar"}, "windows_server": {"sha1": "49fded489aae76e012048c3c81dcc323384ef781", "size": 2542151, "url": "https://launcher.mojang.com/v1/objects/49fded489aae76e012048c3c81dcc323384ef781/windows_server.exe"}}, "id": "1.5.2", "javaVersion": {"component": "jre-legacy", "majorVersion": 8}, "libraries": [{"downloads": {"artifact": {"path": "net/minecraft/launchwrapper/1.5/launchwrapper-1.5.jar", "sha1": "5150b9c2951f0fde987ce9c33496e26add1de224", "size": 27787, "url": "https://libraries.minecraft.net/net/minecraft/launchwrapper/1.5/launchwrapper-1.5.jar"}}, "name": "net.minecraft:launchwrapper:1.5"}, {"downloads": {"artifact": {"path": "net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar", "sha1": "6065cc95c661255349c1d0756657be17c29a4fd3", "size": 61311, "url": "https://libraries.minecraft.net/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar"}}, "name": "net.sf.jopt-simple:jopt-simple:4.5"}, {"downloads": {"artifact": {"path": "org/ow2/asm/asm-all/4.1/asm-all-4.1.jar", "sha1": "054986e962b88d8660ae4566475658469595ef58", "size": 214592, "url": "https://libraries.minecraft.net/org/ow2/asm/asm-all/4.1/asm-all-4.1.jar"}}, "name": "org.ow2.asm:asm-all:4.1"}, {"downloads": {"artifact": {"path": "net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar", "sha1": "39c7796b469a600f72380316f6b1f11db6c2c7c4", "size": 208338, "url": "https://libraries.minecraft.net/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar"}}, "name": "net.java.jinput:jinput:2.0.5"}, {"downloads": {"artifact": {"path": "net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar", "sha1": "e12fe1fda814bd348c1579329c86943d2cd3c6a6", "size": 7508, "url": "https://libraries.minecraft.net/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar"}}, "name": "net.java.jutils:jutils:1.0.0"}, {"downloads": {"artifact": {"path": "org/lwjgl/lwjgl/lwjgl/2.9.0/lwjgl-2.9.0.jar", "sha1": "5654d06e61a1bba7ae1e7f5233e1106be64c91cd", "size": 994633, "url": "https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl/2.9.0/lwjgl-2.9.0.jar"}}, "name": "org.lwjgl.lwjgl:lwjgl:2.9.0", "rules": [{"action": "allow"}, {"action": "disallow", "os": {"name": "osx", "version": "^10\\.5\\.\\d$"}}]}, {"downloads": {"artifact": {"path": "org/lwjgl/lwjgl/lwjgl_util/2.9.0/lwjgl_util-2.9.0.jar", "sha1": "a778846b64008fc7f48ead2377f034e547991699", "size": 173360, "url": "https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl_util/2.9.0/lwjgl_util-2.9.0.jar"}}, "name": "org.lwjgl.lwjgl:lwjgl_util:2.9.0", "rules": [{"action": "allow"}, {"action": "disallow", "os": {"name": "osx", "version": "^10\\.5\\.\\d$"}}]}, {"downloads": {"classifiers": {"natives-linux": {"path": "org/lwjgl/lwjgl/lwjgl-platform/2.9.0/lwjgl-platform-2.9.0-natives-linux.jar", "sha1": "2ba5dcb11048147f1a74eff2deb192c001321f77", "size": 569061, "url": "https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl-platform/2.9.0/lwjgl-platform-2.9.0-natives-linux.jar"}, "natives-osx": {"path": "org/lwjgl/lwjgl/lwjgl-platform/2.9.0/lwjgl-platform-2.9.0-natives-osx.jar", "sha1": "6621b382cb14cc409b041d8d72829156a87c31aa", "size": 518924, "url": "https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl-platform/2.9.0/lwjgl-platform-2.9.0-natives-osx.jar"}, "natives-windows": {"path": "org/lwjgl/lwjgl/lwjgl-platform/2.9.0/lwjgl-platform-2.9.0-natives-windows.jar", "sha1": "3f11873dc8e84c854ec7c5a8fd2e869f8aaef764", "size": 609967, "url": "https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl-platform/2.9.0/lwjgl-platform-2.9.0-natives-windows.jar"}}}, "extract": {"exclude": ["META-INF/"]}, "name": "org.lwjgl.lwjgl:lwjgl-platform:2.9.0", "natives": {"linux": "natives-linux", "osx": "natives-osx", "windows": "natives-windows"}, "rules": [{"action": "allow"}, {"action": "disallow", "os": {"name": "osx", "version": "^10\\.5\\.\\d$"}}]}, {"downloads": {"artifact": {"path": "org/lwjgl/lwjgl/lwjgl/2.9.1-nightly-20130708-debug3/lwjgl-2.9.1-nightly-20130708-debug3.jar", "sha1": "884511652c756fac16b37236f863f346bd1ea121", "size": 996625, "url": "https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl/2.9.1-nightly-20130708-debug3/lwjgl-2.9.1-nightly-20130708-debug3.jar"}}, "name": "org.lwjgl.lwjgl:lwjgl:2.9.1-nightly-20130708-debug3", "rules": [{"action": "allow", "os": {"name": "osx", "version": "^10\\.5\\.\\d$"}}]}, {"downloads": {"artifact": {"path": "org/lwjgl/lwjgl/lwjgl_util/2.9.1-nightly-20130708-debug3/lwjgl_util-2.9.1-nightly-20130708-debug3.jar", "sha1": "fb693ba4e22a85432a32e8a048893dc7a92f42ac", "size": 173338, "url": "https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl_util/2.9.1-nightly-20130708-debug3/lwjgl_util-2.9.1-nightly-20130708-debug3.jar"}}, "name": "org.lwjgl.lwjgl:lwjgl_util:2.9.1-nightly-20130708-debug3", "rules": [{"action": "allow", "os": {"name": "osx", "version": "^10\\.5\\.\\d$"}}]}, {"downloads": {"classifiers": {"natives-osx": {"path": "org/lwjgl/lwjgl/lwjgl-platform/2.9.1-nightly-20130708-debug3/lwjgl-platform-2.9.1-nightly-20130708-debug3-natives-osx.jar", "sha1": "a9b83ad85742cad09c3574a91b0423bac3f7a0f5", "size": 458181, "url": "https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl-platform/2.9.1-nightly-20130708-debug3/lwjgl-platform-2.9.1-nightly-20130708-debug3-natives-osx.jar"}}}, "extract": {"exclude": ["META-INF/"]}, "name": "org.lwjgl.lwjgl:lwjgl-platform:2.9.1-nightly-20130708-debug3", "natives": {"linux": "natives-linux", "osx": "natives-osx", "windows": "natives-windows"}, "rules": [{"action": "allow", "os": {"name": "osx", "version": "^10\\.5\\.\\d$"}}]}, {"downloads": {"classifiers": {"natives-linux": {"path": "net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar", "sha1": "7ff832a6eb9ab6a767f1ade2b548092d0fa64795", "size": 10362, "url": "https://libraries.minecraft.net/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar"}, "natives-osx": {"path": "net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-osx.jar", "sha1": "53f9c919f34d2ca9de8c51fc4e1e8282029a9232", "size": 12186, "url": "https://libraries.minecraft.net/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-osx.jar"}, "natives-windows": {"path": "net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar", "sha1": "385ee093e01f587f30ee1c8a2ee7d408fd732e16", "size": 155179, "url": "https://libraries.minecraft.net/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar"}}}, "extract": {"exclude": ["META-INF/"]}, "name": "net.java.jinput:jinput-platform:2.0.5", "natives": {"linux": "natives-linux", "osx": "natives-osx", "windows": "natives-windows"}}, {"downloads": {"classifiers": {"natives-linux": {"path": "net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar", "sha1": "7ff832a6eb9ab6a767f1ade2b548092d0fa64795", "size": 10362, "url": "https://libraries.minecraft.net/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar"}, "natives-osx": {"path": "net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-osx.jar", "sha1": "53f9c919f34d2ca9de8c51fc4e1e8282029a9232", "size": 12186, "url": "https://libraries.minecraft.net/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-osx.jar"}, "natives-windows": {"path": "net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar", "sha1": "385ee093e01f587f30ee1c8a2ee7d408fd732e16", "size": 155179, "url": "https://libraries.minecraft.net/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar"}}}, "extract": {"exclude": ["META-INF/"]}, "name": "net.java.jinput:jinput-platform:2.0.5", "natives": {"linux": "natives-linux", "osx": "natives-osx", "windows": "natives-windows"}}], "mainClass": "net.minecraft.launchwrapper.Launch", "minecraftArguments": "${auth_player_name} ${auth_session} --gameDir ${game_directory} --assetsDir ${game_assets}", "minimumLauncherVersion": 4, "releaseTime": "2013-04-25T15:45:00+00:00", "time": "2013-04-25T15:45:00+00:00", "type": "release"}

**Comment by HowardZHY** [comment]
这是官方启动器1.5.2的json,玩家名称前没有两个杠

**Comment by LTCatt** [comment]
已修复，需要用修复后的版本重新安装才生效

**Comment by HowardZHY** [comment]
手动把json里的错误符号删掉也行吧

**Comment by LTCatt** [comment]
可以
