### ISSUE TITLE
添加一个自动备份功能，让玩家可以定期备份他们的Minecraft世界和存档。这样玩家在遇到问题或崩档时可以恢复数据。

### ISSUE THREAD

**Issue by mc-doge666** [Hex-Dragon/PCL2#2061]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

添加一个自动备份功能，让玩家可以定期备份他们的Minecraft世界和存档，资源包等。这样玩家在遇到问题或崩档时可以恢复数据。
1. 定期备份：启动器应该提供一个选项，允许用户设置备份的频率，例如每天、每周或每月。用户可以根据自己的需求选择适合他们的备份频率。

2. 备份存储位置：启动器应该允许用户选择备份存储的位置。这可以是本地计算机上的特定文件夹，也可以是云存储服务（如Google Drive、Dropbox等）。

3. 自动备份策略：启动器应该根据备份频率自动执行备份操作。这可以通过检测上次备份的时间戳来确定何时执行备份。如果上次备份超过了设定的频率，启动器将自动触发备份。

4. 增量备份：为了减少备份所需的存储空间和时间，启动器可以使用增量备份策略。这意味着只备份自上次备份以来发生更改的文件或数据。这样可以更高效地进行备份，并节省存储空间。

5. 恢复功能：启动器应该提供一个简单的界面，允许用户从备份中选择并恢复特定的世界或存档。用户可以浏览备份列表，并选择要恢复的特定备份版本。

6. 保留备份历史：启动器可以提供一个选项，允许用户设置保留备份历史的时间。这可以帮助用户限制备份文件的数量和存储空间占用。

### 原因

让玩家可以定期备份他们的Minecraft世界和存档，资源包等。这样玩家在遇到问题或崩档时可以恢复数据。

**Comment by WForst-Breeze** [comment]
个人感觉这个功能对启动器而言稍许有些小复杂，让龙猫斟酌斟酌吧。已初步确认，感谢您的反馈~

**Comment by Chiloven945** [comment]
备份的话目前建议还是使用模组，可以达成许多功能，至于云储存上传的话，dropbox与googledrive国内鲜有人用，而国内的云储存似乎基本上没有提供这种自动储存的，基本上无法通过第三方软件访问云储存内容

**Comment by LTCatt** [comment]
可以考虑使用备份 mod，启动器不会做这个，抱歉 :(
