### ISSUE TITLE
允许在自定义文件下载完成后自动打开或运行

### ISSUE THREAD

**Issue by Chiloven945** [Hex-Dragon/PCL2#2063]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

提供一个可选项决定文件是否在下载后自动打开或运行。

### 原因

方便用户使用：自动打开下载文件可以节省用户的操作步骤，提高使用效率。用户不需要手动找到下载文件并进行打开操作，可以直接查看和使用下载的内容。

提升用户体验：自动打开下载文件可以带来更好的用户体验。用户无需花费额外的时间和精力去查找和打开文件，特别适用于一些常见的下载文件类型，如文档、图片、音频等。

~没搞懂为什么GPT要说降低出错风险和减少用户疑虑~

**Comment by LTCatt** [comment]
用途不大，暂不考虑 :/
