### ISSUE TITLE
增加第三方披风支持

### ISSUE THREAD

**Issue by Nakagawa-Chinatsu** [Hex-Dragon/PCL2#2065]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### **希望增加第三方披风选项**
添加对 [minecraftcapes.net](http://minecraftcapes.net) (为主)或其他披风支持的披风模组以及其披风修改(跳转网站)的支持，而不是单独为optifine披风

_提案_：

- 添加对应模组链接下载按钮
- (获取披风列表并支持选择更改(当然游戏里默认是可以修改披风的))
- 跳转至官网链接按钮
- 若增加功能，[minecraftcapes.net](http://minecraftcapes.net)相关的披风模组及设置帮助文档我会尽可能第一时间出稿(算是一份贡献吧)

### 原因

增加此功能以方便更多无optifine而使用第三方披风的玩家更改披风，并满足部分玩家无法承担optifine披风费用而又希望使用披风的需求，增加引导指向

**Comment by WForst-Breeze** [comment]
Optifine 披风选项都已经拒绝了，这种需要加载特定 Mod 才会显示的披风感觉采纳概率不大 :( 已初步确认，感谢您的反馈~
