### ISSUE TITLE
隐藏主题BUG

### ISSUE THREAD

**Issue by Pinkie-OYYT** [Hex-Dragon/PCL2#2066]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

无法获取滑稽彩隐藏主题！

### 重现步骤

1、开启PCL2。
2、弹出新版本重新解锁滑稽彩，并且我重新解锁了N遍，重启一次就会再次消失滑稽彩主题！

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11780643/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11780644/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11780645/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11780646/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11780647/Log5.txt)

**Comment by Pinkie-OYYT** [comment]
@LTCatt

**Comment by youzi-2333** [comment]
请**再次重启计算机**，按下 `Win + R`，输入 `regedit`，点击确定，上方地址栏输入 `HKEY_CURRENT_USER\Software\PCL`，按回车，找到右侧 `SystemHelpVersion` 的值，看一下是多少？

![无标题](https://github.com/Hex-Dragon/PCL2/assets/106497113/54c6e5b0-9b61-493b-90bc-84efb286510f)

另外，除非其他协作者的处理有误，否则请不要 @ 龙猫，感谢配合。

**Comment by LTCatt** [comment]
发送上述注册表中 SystemLastVersionReg 的值。

**Comment by 404nfwpz** [comment]
PCL会不会是没有权限改注册表了

**Comment by youzi-2333** [comment]
> PCL会不会是没有权限改注册表了

`HKCR` 注册表键理论上是不用管理员权限的……

**Comment by 404nfwpz** [comment]
> 

我之前写c++的时候搞注册表用system是要admin的啊

**Comment by LTCatt** [comment]
超时先关了，之后有需要可以继续回复
