### ISSUE TITLE
添加Minecraft手动安装页面版本细分

### ISSUE THREAD

**Issue by Grey-Wind** [Hex-Dragon/PCL2#2070]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

把Minecraft手动安装页面正式版版本细分
类似Forge、Fabric的下载页面
不然每次下载都很乱，找的很抓狂

### 原因

全部在一起太繁琐，不美观，查找不便

**Comment by WForst-Breeze** [comment]
现在感觉分的还蛮清楚的，没太听懂您的需求是什么，是想加个搜索框吗？
![image](https://github.com/Hex-Dragon/PCL2/assets/110760354/2712a949-df15-467e-87a8-2d21f3d7447e)

**Comment by Grey-Wind** [comment]
> 现在感觉分的还蛮清楚的，没太听懂您的需求是什么，是想加个搜索框吗？ ![image](https://user-images.githubusercontent.com/110760354/246767690-2712a949-df15-467e-87a8-2d21f3d7447e.png)

emm
我的意思是Minecraft页面也像Forge页面一样有版本细分，而不是正式版包含一切

**Comment by LTCatt** [comment]
因为 MC 的一个大版本里就没有多少小版本，所以外面分了大类之后就不太有必要进一步细分了 =。=

**Comment by Grey-Wind** [comment]
> 因为 MC 的一个大版本里就没有多少小版本，所以外面分了大类之后就不太有必要进一步细分了 =。=

好吧。。。
