### ISSUE TITLE
在取消删除版本时会被错误的标记为bug

### ISSUE THREAD

**Issue by misividkoukou** [Hex-Dragon/PCL2#2074]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在取消删除版本时会被错误的标记为bug

### 重现步骤

详见视频

### 日志与附件

见下

**Comment by misividkoukou** [comment]
为啥github插入不了视频了，直接变成小窗口播放？

**Comment by WForst-Breeze** [comment]
可以复现，步骤为：

https://github.com/Hex-Dragon/PCL2/assets/110760354/1917a1de-1c05-4411-9edc-967c22ddb362

**Comment by misividkoukou** [comment]
好吧，就是这样子的，话说为啥这个sb360不能上传视频了
