### ISSUE TITLE
安装原版不会自动创建launcher_profile.json

### ISSUE THREAD

**Issue by hejiehao** [Hex-Dragon/PCL2#2076]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在游戏未启动之前不会创建launcher_profile.json

### 原因

这项优化让我可以更方便地安装mod加载器。
如果没有这项优化，我每次都必须启动一次游戏才可以手动安装其他mod加载器，让操作变得很麻烦。
![image](https://github.com/Hex-Dragon/PCL2/assets/98140773/3d0ed463-f338-48bc-8e84-2c23d8000b76)

### 建议

每次创建.minecraft文件夹时自动创建launcher_profile.json

**Comment by hejiehao** [comment]
可以领活跃橙吗？
96DD-E404-71E8-FC8D

**Comment by LTCatt** [comment]
你的解锁码：W0xMqwpkAZyIOCJmVImf4D0CCfghqTYh
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
