### ISSUE TITLE
PCL2 1.16.1 Fabric下载源问题

### ISSUE THREAD

**Issue by George-Edge** [Hex-Dragon/PCL2#2079]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃不是 PCL2 的原因，请 **不要** 提交反馈。你可以在 QQ 群里或者论坛找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是游戏本身的问题，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在1.16.1 Fabric的下载中，在PCL2下.minecraft\libraries\net\fabricmc\intermediary\1.16.1目录中，intermediary-1.16.1.jar文件是错误的，无法被启动器和游戏加载（加载时会报错）。下载时并未报错和提示，游戏重新安装仍然无法打开，删除后补全也一样，初步判定为下载源问题。用压缩软件打开，会显示”不可预料的压缩文件末端"（其他版本此文件不会出现问题）。fabric官网下载1.16.1不会出现问题，其他启动器均未出现此问题。目前只发现1.16.1一个版本

此问题可被复现

### 错误报告、日志与附件

![1](https://github.com/Hex-Dragon/PCL2/assets/123910830/11fa9913-a2a9-44c3-8dab-c565979cbbbc)
![2](https://github.com/Hex-Dragon/PCL2/assets/123910830/4519c291-0ae7-4237-8332-3d3be996771e)
![3](https://github.com/Hex-Dragon/PCL2/assets/123910830/8bcde911-3216-4127-8173-2958a08f6ff1)

**Comment by George-Edge** [comment]
[Log.txt](https://github.com/Hex-Dragon/PCL2/files/11800689/Log.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11800690/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11800692/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11800691/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11800693/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11800694/Log5.txt)

**Comment by hejiehao** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/98140773/234266c7-1348-43e7-a7f6-768bd1108dda)
上面是HMCL安装的，下面是PCL安装的
但是无论HMCL换哪个源都可以正常启动，而PCL换哪个源都无法启动

**Comment by LTCatt** [comment]
https://download.mcbbs.net/maven/net/fabricmc/intermediary/1.16.1/intermediary-1.16.1.jar
@bangbang93 MCBBS 源的这个文件有问题，根本打不开 =。=

**Comment by zkitefly** [comment]
https://www.bangbang93.com/topic/211/mcbbs-%E6%BA%90%E7%9A%84%E4%B8%80%E4%B8%AA%E6%96%87%E4%BB%B6%E6%9C%89%E9%97%AE%E9%A2%98

**Comment by bangbang93** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/3430784/a7479585-6dc6-464a-875b-fe7385a942c4)
应该可以了

**Comment by George-Edge** [comment]
issue要求解锁

**Comment by iPodtouch6557** [comment]
识别码

**Comment by George-Edge** [comment]
1C0E-DD5D-7D03-1597

**Comment by LTCatt** [comment]
你的解锁码：3Zbl3HIzG1J47ZjEM+Tf6IUSfveNX4Bx
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
