### ISSUE TITLE
在自定义主页中使用控件MyRadioBox时，其Checked属性无法更新

### ISSUE THREAD

**Issue by tool-derp** [Hex-Dragon/PCL2#2080]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在自定义主页custom.xaml文件中粘贴以下代码，然后点击选项2，两个选项的动画改变，但是Checked属性没有发生改变
< local:MyRadioBox x:Name="Option1" Text="选项1" Checked="True"/>
< local:MyRadioBox x:Name="Option2" Text="选项2" />
< TextBlock Text="{Binding Path=Checked, ElementName=Option1}"/>
< TextBlock Text="{Binding Path=Checked, ElementName=Option2}"/>
![image](https://github.com/Hex-Dragon/PCL2/assets/78005438/b7c5d84e-8029-447b-9997-e068834fcd23) ![image](https://github.com/Hex-Dragon/PCL2/assets/78005438/63c1737f-966c-4f20-878b-c17fcf3427a0)

### 重现步骤

1、在自定义主页制作粘贴<local:MyRadioBox x:Name="Option" Text="选项"/>和< TextBlock Text="{Binding Path=Checked, ElementName=Option}"/>
2、刷新主页然后点击选项

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11805812/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11805813/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11805814/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11805815/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11805816/Log2.txt)

**Comment by youzi-2333** [comment]
WPF 自带的控件是可以更新的，代码如下：
```xaml
<ListBox>
    <ListBoxItem>
        <RadioButton x:Name="WpfOption1" Content="选项 1" GroupName="group1" IsChecked="True" />
    </ListBoxItem>
    <ListBoxItem>
        <RadioButton x:Name="WpfOption2" Content="选项 2" GroupName="group1" />
    </ListBoxItem>
    <ListBoxItem>
        <RadioButton x:Name="WpfOption3" Content="选项 3" GroupName="group1" />
    </ListBoxItem>
</ListBox>
<TextBlock Text="{Binding Path=IsChecked, ElementName=WpfOption1}"/>
<TextBlock Text="{Binding Path=IsChecked, ElementName=WpfOption2}"/>
<TextBlock Text="{Binding Path=IsChecked, ElementName=WpfOption3}"/>
```
但是 PCL 的没法更新，这应该算一个 Bug。

不过龙猫会不会修就是另一个故事了.jpg

**Comment by tool-derp** [comment]
嗯，，用不了PCL的自己用控件模板自定义外观做了一个很像的，功能能用了但是牺牲了动画效果(´-ι_-｀)
![image](https://github.com/Hex-Dragon/PCL2/assets/78005438/cb4baa18-53ba-4b24-85e1-d2fd3b2bd2ab)
看不出来有什么区别吧！()

**Comment by LTCatt** [comment]
MyRadioBox 的 Checked 不是 WPF 依赖属性，不支持 Binding 动态绑定 :(
