### ISSUE TITLE
开启游戏时会弹出“Java 兼容性警告”，且我使用的是正确的Java

### ISSUE THREAD

**Issue by SharpClawsawa** [Hex-Dragon/PCL2#2085]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

开始游戏时每一次都会弹出“你在设置中手动指定了使用 Java 17，但当前至少需要 Java 17。
如果强制使用该 Java，可能导致游戏崩溃。
你也可以将 游戏 Java 设置修改为 自动选择合适的 Java。”
点击自动选择合适的Java会让我进入Java官网去下载Java
但是强制使用该Java却不会崩溃

### 重现步骤

疑似是在使用和最低要求版本相同的Java时会弹出此弹窗

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11816758/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11816759/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11816760/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11816761/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11816762/Log1.txt)

**Comment by LTCatt** [comment]
与 #2038 实质性重复，是同一个原因引起的
