### ISSUE TITLE
百宝箱最小宽度按钮显示不全

### ISSUE THREAD

**Issue by sssysy** [Hex-Dragon/PCL2#2086]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

最小宽度百宝箱的按钮"千万别点"显示不全

### 重现步骤

1、把启动器窗口调至最小
2、点更多，然后就看得到"千万别点"按钮显示不全
![QQ截图20230621204046](https://github.com/Hex-Dragon/PCL2/assets/79786006/74958903-b0d2-4920-91e0-7cd4713b770d)

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11817617/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11817618/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11817619/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11817620/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11817621/Log2.txt)

**Comment by youzi-2333** [comment]
与 #1915 重复，感谢您的反馈。
