### ISSUE TITLE
关于为什么要频繁登录账号引出的问题

### ISSUE THREAD

**Issue by zhang5249130** [Hex-Dragon/PCL2#2087]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

之前的#2059提到了登录不弹窗，其实正常来讲我不大用得上登录，但是有个问题实在棘手
那就是自己的登录状态会无缘无故消失，这个也就罢了，关键是他提示我没解锁了（这就是为什么我总是频繁要解锁码）就非常离谱

已检查
电脑没有还原卡/还原软件
没有设置自动清理垃圾，也没有自己手动清理（甚至连杀毒软件都没有）
去appdata文件夹查看有PCL文件夹，且未设置为只读
除上述故障和#2059的登录不弹窗，其他一切正常（MC正常打开使用，解锁的隐藏皮肤还在，设置也没有变动）

另外，我朋友也有这个问题
![mmexport1687393559548](https://github.com/Hex-Dragon/PCL2/assets/96641164/13028a73-7ed1-4ed0-94f0-f0b1b1c20886)
图片见上，我亲自帮他安装的PCL（当然已分享23.33档给朋友）快照版，使用littleskin登录（我用的是微软登录），还是有这个现象

希望修一下吧，要不是edge浏览器可以帮我自动登录微软账号不然我都要F了

### 重现步骤

1、打开PCL

### 日志与附件

额......我用手机反馈的，要我的或者朋友的log和我说一下

**Comment by zhang5249130** [comment]
实在抱歉龙猫和各协助者，但是问题实在太多了（无奈）

**Comment by JingHai-Lingyun** [comment]
先补log,谁出问题补谁的

**Comment by bwtx2023** [comment]
重启电脑之后打开注册表编辑器，定位到 HKEY_CURRENT_USER\Software\PCL ，看看有没有成功定位，如果成功了请截图整个窗口

**Comment by LTCatt** [comment]
> 关键是他提示我没解锁了（这就是为什么我总是频繁要解锁码）就非常离谱

你解锁的主题会自行重置？如果是这样的话，只有两种可能：
1. 你电脑上有其他程序会自动清理注册表，删掉了 PCL 存储的数据
2. 你的主板识别码会自行变更，导致 PCL 加密校验失败

无论是上述哪种情况，也都会导致正版登录信息消失，并且这不是我能够处理的问题 :/
