### ISSUE TITLE
自定义下载优化

### ISSUE THREAD

**Issue by pangzong2011** [Hex-Dragon/PCL2#2088]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

我之前遇到过下载文件无后缀且无法使用
我希望在“下载自定义文件”的描述中加入一句
如遇到下载后文件无法使用且无后缀可尝试手动加入后缀

### 原因

解决一些麻烦

**Comment by LTCatt** [comment]
作为高级功能，这个应该是用户自己折腾的事情.jpg
