### ISSUE TITLE
两个建议

### ISSUE THREAD

**Issue by zhang5249130** [Hex-Dragon/PCL2#2093]
### 检查项

- [x] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

我又来了......

1 希望添加一个功能，使一个或多个模组可以一次性添加到多个开启了版本隔离的Minecraft
2 对于开启了“隔离所有版本”的PCL，再把模组放进游戏根目录下的mods文件夹会弹出提醒

### 原因

1 对于不想把所有存档挤在一个Minecraft的我，有十几个相同版本的Minecraft（有些Minecraft使用的模组不同故都开启了版本隔离（PCL中“隔离所有版本”）），加载模组又要一个一个翻找，复制，粘贴，再找下一个Minecraft文件夹，复制，粘贴......
2 由于隔离所有版本，再加上我用的Minecraft版本鱼龙混杂（我大概有80多个Minecraft），再加上模组加载器不尽相同，这么无脑的放置模组未免会放错，导致游戏崩溃
提示：第二个建议如果麻烦那就算了吧，反正这也只是帮一下我同学（而已）

**Comment by WForst-Breeze** [comment]
⭐ 请尽量避免在一个 Issue 中提及多个反馈项目~

第一条看看龙猫怎么想吧。对于第二条，玩家都开启了隔离所有版本了，只要不进行单独的版本设置，就不会加载根目录 mods 文件夹中的 mod，也就不会对其余版本的加载和启动造成任何影响，所以加个提示显得有些画蛇添足了 :/ 已初步确认，感谢您的反馈~

**Comment by LTCatt** [comment]
umm 你可以直接把 mod 拖进 PCL 窗口，操作会简单一点……
这些功能还是不适合直接做进启动器，抱歉啦 :/
