### ISSUE TITLE
为启动器内链接打开加一个确认窗口

### ISSUE THREAD

**Issue by gyc123456-1** [Hex-Dragon/PCL2#2099]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

就像MC里面一样，点开任何链接多一个确认，显示链接和复制、打开和取消选项

### 原因

有时候浏览器没打开，不小心点到一个链接，浏览器打开加载等半天，有点烦

**Comment by LTCatt** [comment]
对大多数人来说应该没太大必要，加一步确认实际上也增加了额外的麻烦 :/
