### ISSUE TITLE
在检测Java时不应对JAVA_HOME环境变量中的Java进行符号链接检查

### ISSUE THREAD

**Issue by frshuov** [Hex-Dragon/PCL2#2103]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

用户可能会安装Oracle JDK但日常使用用其他方法安装的Java。
这些Java可能是以符号链接配置的，例如（一个**常见**的情况）通过scoop安装的openjdk。
对于用户自行在JAVA_HOME中指定的Java，不应在Java列表中过滤。

### 原因

我曾在使用PCL2时发现PCL2无法检测到使用scoop安装的openjdk。
我当时提交了一个功能请求（#1414）建议增加自动搜索PATH和JAVA_HOME环境变量的功能。
当时龙猫说有这个功能，我以为是我没注意，然后手动添加了之后给覆盖了。

但是现在在一台新的主机上仍无法检测。查看日志发现，PCL确实检测了环境变量中的Java，但是因为“该Java包含符号链接”给忽略掉了。

这显然是为了避免重复的Java，但对于用户**自行**配置的Java则不该有此问题。
过滤符号链接时应对环境变量的Java单独处理或设置白名单。

**Comment by LTCatt** [comment]
Java 在使用部分安装程序安装时会同时生成符号连接并且加进环境变量，没有啥好的办法解决 :/
