### ISSUE TITLE
基于新的.NET重新构建PCL2

### ISSUE THREAD

**Issue by Victor-Alex** [Hex-Dragon/PCL2#2104]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

.NET 6.0的性能个人感觉提升非常明显，值得升级，微软也提供了很多迁移教程和工具
.NET Framework 4独有的特性好像也不是很多，而且大部分也有新的替代
当然也不急，.NET 8.0也快发布了，到时候估计又是一波升级

### 原因

PCL2启动还是有明显的卡顿感，运行速度在中低配的电脑上有时会变慢
之前用的一些应用有从.net framework 4升级到.net 6.0的，感觉确实变快了
而且等以后更新的版本出现了，迁移的难度会更大

**Comment by LTCatt** [comment]
迁移到新版本会导致老操作系统的电脑直接无法使用，没法 =。=

**Comment by bwtx2023** [comment]
> 迁移到新版本会导致老操作系统的电脑直接无法使用，没法 =。=

.NET 6 不是支持 Win7 的吗，如果安装不了说明用户补丁没打

况且在这些电脑上也不能正常安装 .NET Framework 4.6.2 （会报证书问题）

**Comment by Victor-Alex** [comment]
或者可以直接重构出PCL3？以后老版本还支持旧系统，但不进行功能更新
反正按照现在的趋势，新的java和mc不支持老旧系统是迟早的事

**Comment by zkitefly** [comment]
> 或者可以直接重构出PCL3？以后老版本还支持旧系统，但不进行功能更新
> 反正按照现在的趋势，新的java和mc不支持老旧系统是迟早的事

重构不太可能，因为龙猫没有那么多的精力去做（
