### ISSUE TITLE
2.6.2更新失败

### ISSUE THREAD

**Issue by quannen** [Hex-Dragon/PCL2#2106]
### 检查项

- [ ] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在2.6.2版本向2.6.3更新时没有权限，可是已经使用管理员身份

### 重现步骤

不知

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11856010/Log2.txt)
没错，都在这里

**Comment by LTCatt** [comment]
删掉 D:\minecraftuse\PCL\Plain Craft Launcher 2.exe 试试……
没权限我真的没办法 :/
