### ISSUE TITLE
未将对象引用到设置对象的实例

### ISSUE THREAD

**Issue by MythicAqua** [Hex-Dragon/PCL2#2107]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述
更新完pcl快照版后
![image](https://github.com/Hex-Dragon/PCL2/assets/122416024/76b225cd-5a3a-43fd-b37a-708a955bd4e4)

### 重现步骤

1、打开PCL 点击启动游戏

### 日志与附件

[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11856076/Log5.txt)
[Log.txt](https://github.com/Hex-Dragon/PCL2/files/11856077/Log.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11856078/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11856079/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11856080/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11856081/Log4.txt)

**Comment by LTCatt** [comment]
已重新发布 2.6.3 更新修复此 Issue。

**Comment by MythicAqua** [comment]
这个能算活跃橙嘛;w;
识别码是 0196-E03A-897E-2E97

**Comment by LTCatt** [comment]
你的解锁码：OA1MdtDsHQzrmgmk2oT/kr5aDdY0+R/E
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
