### ISSUE TITLE
在生成启动脚本时询问是否运行后关闭窗口

### ISSUE THREAD

**Issue by IKUN05648** [Hex-Dragon/PCL2#2108]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

让用户设置在生成的启动脚本运行后**是否自动关闭**
人话：脚本里的java.exe**换不换**成javaw.exe?

### 原因

脚本启动让人很烦的是在运行脚本后会留下一个窗口，如果给用户选择是否设置脚本运行后关闭窗口，体验一定会好一点

**Comment by youzi-2333** [comment]
在批处理或命令提示符中运行 Java，`java.exe` 和 `javaw.exe` 唯一的区别就是是否在控制台输出日志……如果在 运行 窗口中运行 Java，那么它们的区别就是是否弹出控制台；因此，您的意思应当是“脚本最后是否添加 `pause` 命令”。

但是这种简单的操作如果加一个弹窗，那么用户操作会变得更加麻烦，而且龙猫最近也忙着修 Bug，大概率不会制作……

**Comment by LTCatt** [comment]
你可以自己删掉最后的 pause……
