### ISSUE TITLE
隐藏禁用mod

### ISSUE THREAD

**Issue by DoubtedYapper71** [Hex-Dragon/PCL2#2110]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在mod管理中添加一个隐藏禁用/启用mod

### 原因

有时可能需要在禁用/启用mod中翻阅
当禁用mod多时，翻阅会变得麻烦

**Comment by LTCatt** [comment]
与 #679 重复
