### ISSUE TITLE
mod列表排序

### ISSUE THREAD

**Issue by Luck1076** [Hex-Dragon/PCL2#2111]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

希望启动器内的mod列表取消大小写字母分别排序,类似在windows资源管理器中的样式,而非大写字母排序一次,小写字母排序一次

### 原因

这项优化让我可以更方便地查找mod或者更新mod。
如果没有这项优化，找mod会翻好多遍(才不是眼瞎呢),让操作变得很麻烦。

**Comment by LTCatt** [comment]
没啥必要吧，暂时不打算更改……找 Mod 不是有搜索么……
