### ISSUE TITLE
删除 设置-个性化-功能隐藏 中的“邮箱显示”选项

### ISSUE THREAD

**Issue by mclvlc** [Hex-Dragon/PCL2#2113]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

![image](https://github.com/Hex-Dragon/PCL2/assets/89335488/5850ef20-2e90-4ce5-a5f3-69d8150e4345)
现在这个功能没用了（更新后即使是快照版也没把这个功能取消），现在版本启动页面并不会显示邮箱了，希望删除

### 原因

强迫症

**Comment by LTCatt** [comment]
好像第三方登录还是会……之后有空看看

**Comment by mclvlc** [comment]
试了试真的会...
