### ISSUE TITLE
更新日志未更改

### ISSUE THREAD

**Issue by gyc123456-1** [Hex-Dragon/PCL2#2115]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/Hex-Dragon/PCL2/assets/69791212/57e5bd8c-e954-41cb-a9c6-0af861748097)

### 重现步骤

旧版向上更新

### 日志与附件

日志不用吧。。。

**Comment by LTCatt** [comment]
？有啥问题么，本来就没有啥新的主要更新内容啊？
