### ISSUE TITLE
真正让启动游戏时可以切换版本

### ISSUE THREAD

**Issue by gyc123456-1** [Hex-Dragon/PCL2#2116]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

比如在启动游戏的取消按钮旁边加个返回之内的，然后让游戏启动作为像下载一样的后台任务

### 原因

既然这个版本已经修复了这个bug，可以试试把这个功能加进去，在连续启动多个游戏的时候有帮助

**Comment by LTCatt** [comment]
很难做，暂不考虑 :/
