### ISSUE TITLE
mod搜索功能优化建议：不同来源搜索速度不一致的问题

### ISSUE THREAD

**Issue by blibilijojo** [Hex-Dragon/PCL2#2120]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

- 我在使用 PCL 2 启动器的 mod 搜索功能时，发现它有两个来源，分别是 CurseForge 和 Modrinth。默认情况下，它会同时从两个来源搜索 mod，但是这样有一个问题：如果其中一个来源的搜索速度很慢，它就会一直等待慢的来源，导致即使另一个来源的结果已经出来了，也还要等待很久才能显示出来。
- 我希望 PCL 2 启动器能够优化这个功能，让它能够更快地显示出 mod 搜索结果，不用等待慢的来源。我认为这样可以提高用户的搜索效率和体验，也可以让用户更容易找到自己想要的 mod。
- 我有两个优化的想法，分别是：
  - 当检测到一个来源慢于另一个来源过长时间（比如 5 秒），提示用户慢的来源是哪一个，然后推荐用户单独选择快的来源进行搜索。这样可以让用户知道是哪个来源导致了搜索延迟，也可以让用户自己决定是否要继续等待或者切换来源。
  - 在前面的基础上，当检测到一个来源慢于另一个来源过长时间（比如 3 秒），自动忽略掉慢的来源，只显示快的来源的搜索结果。这样可以让用户更快地看到搜索结果，不用再等待慢的来源。但是这样可能对一些用户造成困扰，因为他们可能想要看到两个来源的全部结果。所以这个功能可以改为设置中默认关闭，用户可以选择是否要开启。

### 原因

- 我需要这项优化，因为我觉得现在的 mod 搜索功能太慢了，影响了我的游戏体验。我经常想要下载一些 mod 来玩我的世界，但是每次搜索都要等很久才能看到结果，有时候甚至会卡住不动。我觉得这样很浪费时间和流量，也很影响我的心情。
- 我认为这项优化对其他玩家也有好处，因为我想很多玩家都会遇到类似的问题。如果 PCL 2 启动器能够优化 mod 搜索功能，让它更快更智能地显示出结果，那么就可以提升玩家们的搜索效率和体验，也可以让玩家们更容易找到自己想要的 mod。我觉得这样对 PCL 2 启动器的口碑和用户量都有好处。
- 我没有参考其他启动器或软件的类似功能，因为我没有找到其他启动器或软件有这样的功能。我只是根据自己的需求和想法提出了这些优化方案。如果有其他启动器或软件有更好的解决方法，我也很乐意听取和学习。

**Comment by blibilijojo** [comment]
哈哈，其实这个文本（标题和正文全是）是让ai生成的，不过想法是我的想法，不得不说ai的逻辑确实清晰。

**Comment by LTCatt** [comment]
如果一个来源死活加载不出来 PCL 会显示单来源的结果的。
没法做到你说的功能，因为两个来源间的结果是会互相影响的，单纯临时禁用一个来源会导致之后换页出问题 =。=
实在不行你可以手动切来源啊）
