### ISSUE TITLE
取消启动不会结束游戏进程的BUG还能触发

### ISSUE THREAD

**Issue by 3cxc** [Hex-Dragon/PCL2#2121]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我知道 #1631 已经说明了这个问题,而且龙猫也在正式版2.6.0的时候修复了
但是，我在快照版2.6.3测试时发现，进度条没到100%之前取消启动是没事的
但到了100%时再取消启动就又出现了 :(

以防万一，我又跑回了正式版2.6.0测试，结果也能触发
(这样启动的MC无法通过PCL来关闭，只能手动关闭)

### 重现步骤

启动游戏,在进度条到100%的时候点取消

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11858588/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11858589/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11858590/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11858591/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11858592/Log5.txt)

**Comment by LTCatt** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/5635f7cf-38cf-4cc4-a184-65bfb50d5a0e)
这其实是这个 java 导致的……
算了之后判断一下尽量不用这个 java（

**Comment by 3cxc** [comment]
确实是这个Java导致的问题...切换成Java17就无此问题了
但神奇的是启动选项选择"自动选择合适的Java",却优先选择这个Java(我的电脑上是有JAVA17的)
这可能也是个问题

**Comment by LTCatt** [comment]
你重新点一下自动搜索试试？应该重新搜索之后就没有这个 Java 了？
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/c261a685-ebb8-400a-9103-b394d4662528)

试过之后记得回复（

**Comment by 3cxc** [comment]
![QQ截图20230715192129](https://github.com/Hex-Dragon/PCL2/assets/81449257/52bdad75-5671-4dd8-9c65-089f1e7cbe29)
刷新后确实已经没有了这个JAVA @LTCatt

**Comment by 3cxc** [comment]
同时取消启动不会再出现游戏窗口了（确实没有再用那个JAVA了）
