### ISSUE TITLE
为 mod 搜索结果添加可以跳转到已加载页面的分页功能

### ISSUE THREAD

**Issue by mclvlc** [Hex-Dragon/PCL2#2122]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

第一次问了显示所有mod结果有xx页，龙猫回答说api不支持显示所有页面数量，我就想既然不能显示所有页面那可不可以显示已加载的页面跳转，（在 mod 搜索页面的底部添加一个分页栏，搜索引擎那样。）

### 原因

换页面麻烦

**Comment by youzi-2333** [comment]
抱歉没看懂……
请尽可能详细描述您需要的新功能，感谢配合。

**Comment by blibilijojo** [comment]
在我苦思冥想之后好像明白你的意思了，你的意思就是：
- 在 mod 搜索页面的底部添加一个分页栏。，搜索引擎那样。
对吧

**Comment by mclvlc** [comment]
> 在我苦思冥想之后好像明白你的意思了，你的意思就是：
> 
> * 在 mod 搜索页面的底部添加一个分页栏。，搜索引擎那样。
>   对吧

对对对对对

**Comment by mclvlc** [comment]
> 在我苦思冥想之后好像明白你的意思了，你的意思就是：
> 
> * 在 mod 搜索页面的底部添加一个分页栏。，搜索引擎那样。
>   对吧

上次我的issue是龙猫回答的，他说api不支持显示所有页面，顺便把那个关了，这回提出issue的时候简短了一些

**Comment by mclvlc** [comment]
> 在我苦思冥想之后好像明白你的意思了，你的意思就是：
> 
> * 在 mod 搜索页面的底部添加一个分页栏。，搜索引擎那样。
>   对吧

上次我是想说显示所有mod结果一共有xx页

**Comment by mclvlc** [comment]
> 在我苦思冥想之后好像明白你的意思了，你的意思就是：
> 
> * 在 mod 搜索页面的底部添加一个分页栏。，搜索引擎那样。
>   对吧

我就想，既然不能显示所有页面那能不能显示已加载的页面

**Comment by youzi-2333** [comment]
> 既然不能显示所有页面那能不能显示已加载的页面

技术上是可以的，就是看龙猫做不做……

另外，如果有其它信息需要补充，请尽量使用 Edit 功能（可以看 https://github.com/Hex-Dragon/PCL2/discussions/1592#discussioncomment-5552180 ），感谢……

**Comment by mclvlc** [comment]
> > 既然不能显示所有页面那能不能显示已加载的页面
> 
> 技术上是可以的，就是看龙猫做不做……
> 
> 另外，如果有其它信息需要补充，请尽量使用 Edit 功能（可以看 [#1592 (comment)](https://github.com/Hex-Dragon/PCL2/discussions/1592#discussioncomment-5552180) ），感谢……

感谢！（我是github小白...）

**Comment by blibilijojo** [comment]
em，标题还是简介一些好，你看我这个咋样“为 mod 搜索结果添加可以跳转到已加载页面的分页功能”

**Comment by mclvlc** [comment]
> em，标题还是简介一些好，你看我这个咋样“为 mod 搜索结果添加可以跳转到已加载页面的分页功能”

可以！！！ 本人表达不好（

**Comment by blibilijojo** [comment]
> > em，标题还是简介一些好，你看我这个咋样“为 mod 搜索结果添加可以跳转到已加载页面的分页功能”
> 
> 可以！！！ 本人表达不好（

哈哈，其实我是找ai写的说....ai的逻辑还是不错的

**Comment by LTCatt** [comment]
现在往回跳可以跳前一页和第一页，已经可以满足绝大多数需求了 =。=
