### ISSUE TITLE
PCL 2 启动器主题颜色优化建议

### ISSUE THREAD

**Issue by blibilijojo** [Hex-Dragon/PCL2#2123]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

主题用完之后颜色会改变，但是左下角的任务提示的颜色不会改变，就会导致很违和的现象出现，之前用极客蓝的时候还没看出来，现在一换成其他颜色才发现这么违和（这是不是简间接说明了其实大部分人都不用蓝色以外的主题）。
![image](https://github.com/Hex-Dragon/PCL2/assets/102420734/2405795e-0f27-400f-ad03-f89e72809e31)

### 原因

单纯这样很违和，难看

**Comment by LTCatt** [comment]
弹出提示是绿色（完成），蓝色（提示），红色（错误），这个不会随着主题改变 :/
