### ISSUE TITLE
百宝箱中的小bug

### ISSUE THREAD

**Issue by Isw-9** [Hex-Dragon/PCL2#2125]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在 更多-百宝箱-百宝箱 中先将光标放置在清理游戏垃圾按钮上，再将光标移至千万别点按钮上，清理游戏垃圾的说明框不会消失
![Screenshot 2023-06-26 085613](https://github.com/Hex-Dragon/PCL2/assets/130830720/c9f0902f-3e70-4506-a092-04d4111b06d1)

### 原因

只是感觉很强迫，几乎没有优先度

**Comment by TheLeiPu** [comment]
我没这bug，你确定是最新？

**Comment by LTCatt** [comment]
这是 WPF 的底层问题，无法修复 :/
