### ISSUE TITLE
无法拖动Mods到Mod管理中

### ISSUE THREAD

**Issue by Dino-doge** [Hex-Dragon/PCL2#2127]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

拖动mod到 管理mod 界面 时，鼠标样式为x，无法安装

### 重现步骤

1、打开PCL2主程序
2、点击<版本设置>
3、点击<MOD 管理>
4、在文件资源管理器将某个jar模组文件拖动到此，指针样式为x
![Uploading kirsmin_2023-06-26_15-42-28.png…]()

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11865720/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11865723/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11865724/Log3.txt)

**Comment by bwtx2023** [comment]
不要使用管理员身份运行 PCL2 。

这是系统问题， PCL2 无法解决。

**Comment by LTCatt** [comment]
详见 #2531，已修复，如果要活跃橙可以给 =。=
@Pigeon0v0 这种问题之后还是留给我看一下吧，别直接 close 了……

**Comment by Dino-doge** [comment]
issue B4AE-C0FC-1BAF-1C93

**Comment by Dino-doge** [comment]
issue

**Comment by LTCatt** [comment]
你的解锁码：u5DqcnYdGjzhpQlqJdXUBKnQaxADS/GF
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by Pigeon0v0** [comment]
> 详见 #2531，已修复，如果要活跃橙可以给 =。=
> 
> @Pigeon0v0 这种问题之后还是留给我看一下吧，别直接 close 了……

👌
