### ISSUE TITLE
下载页面安装1.12.2版本时，PCL2无法找到14.23.5.2847以下版本的Forge

### ISSUE THREAD

**Issue by SuoHouDaiShi** [Hex-Dragon/PCL2#2133]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

第一次使用PCL2安装1.12.2版本时，PCL2无法找到14.23.5.2847以下版本的Forge，必须要使用其他启动器进行一次该版本Forge游戏的下载才能正常识别到14.23.5.2847以下版本的Forge。

### 重现步骤

0-1.确保你没有安装过任何一个1.12.2的整合包或者版本，如果有，请删除它
0-2.如果执行了步骤0-1，请删除PCL2和PCL.ini文件并重新下载PCL2
1.打开PCL2，切换到下载选项卡
2.点击正式版，找到1.12.2
3.点击它，选择Optifine和Forge，此时你会发现，Forge没有低于14.23.5.2847以下的版本
4.下载另外一个启动器，安装1.12.2和任意一个低于14.23.5.2847版本的Forge
5.重新启动PCL2，能够正常下载14.23.5.2847以下版本的Forge

### 日志与附件

![6LOKR`0{(THNV(Q_1_6A$9T](https://github.com/Hex-Dragon/PCL2/assets/119282947/e4642f0e-322d-48e4-8345-205cab46870b)
![LYOM V_SSX6%~$L1ZE5@$PE](https://github.com/Hex-Dragon/PCL2/assets/119282947/576ce4f2-1ea5-42fa-8f37-40e015aaeffb)

**Comment by youzi-2333** [comment]
那是因为你选了 Optifine G5，它与 Forge 14.23.5.2847 以下的版本不兼容……

**Comment by youzi-2333** [comment]
额，……那应该是以前出现过类似案例吧，因为不兼容导致的（部分）Mod 异常啊，渲染异常啊，启动失败啊，卡顿啊，阿巴阿巴这一堆问题，导致龙猫决定把它设置为不兼容（

**Comment by SuoHouDaiShi** [comment]
> 额，……那应该是以前出现过类似案例吧，因为不兼容导致的（部分）Mod 异常啊，渲染异常啊，启动失败啊，卡顿啊，阿巴阿巴这一堆问题，导致龙猫决定把它设置为不兼容（

那也得，但是这样以后PCL2就能正常安装了）
