### ISSUE TITLE
下载forge失败

### ISSUE THREAD

**Issue by iwjsyt** [Hex-Dragon/PCL2#2136]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

下载 Forge 36.2.34失败
→ 获取 Mod 下载器支持库文件失败
→ 值不能为 null。
参数名: path
   在 PCL.ModDownloadLib._Closure$__37-1._Lambda$__3(LoaderTask`2 Task)
   在 PCL.ModLoader.LoaderTask`2._Closure$__12-0._Lambda$__0()
错误类型：System.ArgumentNullException

### 重现步骤

1、点击下载
2、往下滚，然后点击自动安装
3、点击正式版
5、往下滚，点击1.16.5
6、点击forge
7、任意点击一个版本的forge
7、开始安装

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11888802/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11888804/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11888805/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11888806/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11888810/Log5.txt)

**Comment by youzi-2333** [comment]
感觉和 #2031 类似。

> 考虑是偶发情况，如果有其他人也出现这个问题再考虑修复。——龙腾猫跃

（话说如果这个 Issue 处理了，那么 2031 的提交者能拿到活跃橙么……）

**Comment by iwjsyt** [comment]
我现在怎么才能下forge



在 2023-06-28 10:50:08，"柚子柚子" ***@***.***> 写道：

感觉和 #2031 类似。

考虑是偶发情况，如果有其他人也出现这个问题再考虑修复。——龙腾猫跃

（话说如果这个 Issue 处理了，那么 2031 的提交者能拿到活跃橙么……）

**Comment by iwjsyt** [comment]
每次都是这样



在 2023-06-28 16:01:43，"龙腾猫跃" ***@***.***> 写道：

与 #2031 相同。
你每次安装都必定出现这个问题吗？
使用 HMCL 可以正常安装吗？

**Comment by iwjsyt** [comment]
pcl2不行，但HMCL可以正常安装



在 2023-06-28 16:01:43，"龙腾猫跃" ***@***.***> 写道：

与 #2031 相同。
你每次安装都必定出现这个问题吗？
使用 HMCL 可以正常安装吗？

**Comment by iwjsyt** [comment]
下载 OptiFine 1.16.5 G8失败
→ 安装 OptiFine（方式 A）失败
→ 安装新版 OptiFine 版本失败
→ 安装器运行出错，末行为 at oolloo.jlw.Wrapper.main(Wrapper.java:24)
在 PCL.ModDownloadLib._Closure$__18-0._Lambda$__5(LoaderTask`2 Task)
在 PCL.ModLoader.LoaderTask`2._Closure$__12-0._Lambda$__0()
在 PCL.ModDownloadLib.McDownloadOptiFineInstall(String BaseMcFolderHome, String Target, LoaderTask`2 Task)
在 PCL.ModDownloadLib._Closure$__18-0._Lambda$__5(LoaderTask`2 Task)



在 2023-06-28 16:01:43，"龙腾猫跃" ***@***.***> 写道：

与 #2031 相同。
你每次安装都必定出现这个问题吗？
使用 HMCL 可以正常安装吗？

**Comment by iwjsyt** [comment]
下载 Forge 36.2.34失败
→ 获取 Mod 下载器支持库文件失败
→ 值不能为 null。
参数名: path
在 PCL.ModDownloadLib._Closure$__37-1._Lambda$__3(LoaderTask`2 Task)
在 PCL.ModLoader.LoaderTask`2._Closure$__12-0._Lambda$__0()
错误类型：System.ArgumentNullException



在 2023-06-28 16:01:43，"龙腾猫跃" ***@***.***> 写道：

与 #2031 相同。
你每次安装都必定出现这个问题吗？
使用 HMCL 可以正常安装吗？

**Comment by iwjsyt** [comment]
forge和optifine



在 2023-06-28 16:01:43，"龙腾猫跃" ***@***.***> 写道：

与 #2031 相同。
你每次安装都必定出现这个问题吗？
使用 HMCL 可以正常安装吗？

**Comment by iwjsyt** [comment]
都下不了



在 2023-06-28 16:01:43，"龙腾猫跃" ***@***.***> 写道：

与 #2031 相同。
你每次安装都必定出现这个问题吗？
使用 HMCL 可以正常安装吗？

**Comment by PaperDemiurge** [comment]
同样的问题，我试了一下隔壁bakaxl也抽了这个风

**Comment by PaperDemiurge** [comment]
下载 Forge 35.1.37失败
→ 获取 Mod 下载器支持库文件失败
→ 值不能为 null。
参数名: path
   在 PCL.ModDownloadLib._Closure$__37-1._Lambda$__3(LoaderTask`2 Task)
   在 PCL.ModLoader.LoaderTask`2._Closure$__12-0._Lambda$__0()
错误类型：System.ArgumentNullException

**Comment by bwtx2023** [comment]
> 同样的问题，我试了一下隔壁bakaxl也抽了这个风

如果可以的话，去隔壁也交一个反馈（

**Comment by iwjsyt** [comment]
所以现在该怎么办



在 2023-07-02 17:51:20，"bwtx1981" ***@***.***> 写道：

同样的问题，我试了一下隔壁bakaxl也抽了这个风

如果可以的话，去隔壁也交一个反馈（

**Comment by zkitefly** [comment]
> 所以现在该怎么办 在 2023-07-02 17:51:20，"bwtx1981" ***@***.***> 写道： 同样的问题，我试了一下隔壁bakaxl也抽了这个风 如果可以的话，去隔壁也交一个反馈（ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

下载 Forge 安装器手动安装 Forge

**Comment by hellominecraftlauncher** [comment]
补充一下，PCL安装部分用HMCL导出包的optifine最新版，再导入PCL也会这样（别问我为啥不是叫issue，想交屏蔽，日志已丢）

**Comment by hejiehao** [comment]
> 补充一下，PCL安装部分用HMCL导出包的optifine最新版，再导入PCL也会这样，是1.12.2 G6 pre1（别问我为啥不是叫issue，想交屏蔽，日志已丢）

我记得这个版本的Optifine下载地址是错误的，正确的是https://bmclapi2.bangbang93.com/optifine/1.12.2/HD_U_G6/pre1

**Comment by hejiehao** [comment]
但是PCL的确是https://bmclapi2.bangbang93.com/optifine/1.12.2/HD_U_G6pre1

**Comment by hellominecraftlauncher** [comment]
> 但是PCL的却是https://bmclapi2.bangbang93.com/optifine/1.12.2/HD_U_G6pre1

是因为单纯少一个斜杠吗

**Comment by LTCatt** [comment]
与 #2031 重复，先 Reopen #2031 吧
