### ISSUE TITLE
部分回声洞仍然有问题

### ISSUE THREAD

**Issue by nlywto5b** [Hex-Dragon/PCL2#2137]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/Hex-Dragon/PCL2/assets/118055561/d452bdcc-ff71-4dd4-a8fd-19c65cde7fed)
如图，这条回声洞虽然字改了，但箭头没改，可能会误导部分用户

### 重现步骤

点击回声洞

### 日志与附件

不需要日志

**Comment by youzi-2333** [comment]
这……行吧，再让龙猫改一下（

**Comment by nlywto5b** [comment]
活跃橙
识别码：718C-7F6D-592F-3948

**Comment by LTCatt** [comment]
你的解锁码：CZqYdEBglmI9L3j6JVnjNbzJvQgKN6l1
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
