### ISSUE TITLE
[Bug] 多次启动下载任务，总进度远大于分项进度

### ISSUE THREAD

**Issue by youzi-2333** [Hex-Dragon/PCL2#2138]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如题，启动几个下载任务，等它们完成，然后启动一个自定义下载，此时总进度远大于分项进度；但是它们的差距会逐渐减小，并最终同时到 100%。
![image](https://github.com/Hex-Dragon/PCL2/assets/106497113/552ceaa2-3e71-47ed-bbc6-ca3dca35ccf3)

### 重现步骤

1. 随便启动个下载任务
2. 等待它完成
3. 打开自定义下载，再随便下载一个文件
4. Bug 出现

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11891020/Log1.txt)

**Comment by LTCatt** [comment]
……无法复现，有啥明显稳定的复现方式么

**Comment by Bandysol** [comment]
复现成功，Log：
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12091781/Log1.txt)

可能跟#1631差不多，是由于旧下载结束时新下载开始，程序没有重置下载百分比，以为旧和新是一起开始的，按#1956中说的预期行为工作。

**Comment by youzi-2333** [comment]
我很明确，几个下载任务不是同时进行，然后其中一个先完成了……
今天又出现这种情况
![image](https://github.com/Hex-Dragon/PCL2/assets/106497113/ce432afa-2854-4c56-ac5b-9f00322160f0)

**Comment by LTCatt** [comment]
由于无法复现，盲修了一下，看看下个版本还能不能复现，如果能复现再上传复现时的 log
