### ISSUE TITLE
无法同时安装1.20.1和1.19.4

### ISSUE THREAD

**Issue by Bandysol** [Hex-Dragon/PCL2#2139]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在同时安装1.19.4和1.20.1时，安装进度一直卡住不动，尝试关闭1.19.4安装任务时，启动器闪退

### 重现步骤

同时下载安装1.19.4和1.20.1

### 日志与附件

看了一下，差不多都是这样的错误。可能是1.20.1和1.19.4一起复制文件导致的？

[21:52:21.501] 获取文件 SHA1 可重试失败：E:\bf\D\PCL2(.minecraft)\原版\.minecraft\assets\objects\e8\e87cf2ab1472de6941912ad097396a65356900d9：数据错误(循环冗余检查)。

   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.ReadCore(Byte[] buffer, Int32 offset, Int32 count)
   在 System.IO.FileStream.Read(Byte[] array, Int32 offset, Int32 count)
   在 System.Security.Cryptography.HashAlgorithm.ComputeHash(Stream inputStream)
   在 PCL.ModBase.GetAuthSHA1(String FilePath)
错误类型：System.IO.IOException

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11895570/Log2.txt)

**Comment by LTCatt** [comment]
同 #2140
