### ISSUE TITLE
1.19.4安装失败

### ISSUE THREAD

**Issue by Bandysol** [Hex-Dragon/PCL2#2140]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

安装1.19.4+OptiFine I4时出错

### 重现步骤

安装1.19.4+OptiFine I4

### 日志与附件

安装失败：文件“E:\bf\D\PCL2(.minecraft)\原版\.minecraft\assets\objects\e9\e956e0986b597ec1b7d1db720dc8aec3a0642630”正由另一进程使用，因此该进程无法访问此文件。 → 文件下载失败：E:\bf\D\PCL2(.minecraft)\原版\.minecraft\assets\objects\e9\e956e0986b597ec1b7d1db720dc8aec3a0642630 https://download.mcbbs.net/assets/e9/e956e0986b597ec1b7d1db720dc8aec3a0642630 https://resources.download.minecraft.net/e9/e956e0986b597ec1b7d1db720dc8aec3a0642630 https://bmclapi2.bangbang93.com/assets/e9/e956e0986b597ec1b7d1db720dc8aec3a0642630 → 下载资源文件（副加载器）失败 → 下载原版资源文件失败 → 下载原版 1.19.4失败

[22:55:26.276] 合并文件出错（e956e0986b597ec1b7d1db720dc8aec3a0642630）：文件“E:\bf\D\PCL2(.minecraft)\原版\.minecraft\assets\objects\e9\e956e0986b597ec1b7d1db720dc8aec3a0642630”正由另一进程使用，因此该进程无法访问此文件。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.File.InternalDelete(String path, Boolean checkHost)
   在 PCL.ModNet.NetFile.Merge()
错误类型：System.IO.IOException

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11896246/Log1.txt)

**Comment by zkitefly** [comment]
单纯是网络问题

**Comment by LTCatt** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/db46fb9c-01d6-4151-b14d-5321231f6d43)
你的硬盘出问题了——
