### ISSUE TITLE
由于操作系统或显卡存在问题,导致出现错误

### ISSUE THREAD

**Issue by terryaxe** [Hex-Dragon/PCL2#2144]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在游戏关闭后,关闭游戏按钮未消失,点击后弹出报错,启动器崩溃
![_4OM}A00ZC`(G~1LP__VMBT](https://github.com/Hex-Dragon/PCL2/assets/108184807/24183f58-b6ff-4e4c-8f34-e565295bce63)

### 重现步骤

未稳定触发

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11905793/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11905794/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11905795/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11905796/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11905797/Log5.txt)

**Comment by terryaxe** [comment]
话说这是电脑的问题吗(

**Comment by bwtx2023** [comment]
如果不能稳定复现的话可能不是很好修…

**Comment by youzi-2333** [comment]
都说了 `COMException` 是操作系统或显卡的问题……
这个真的没法修（因为 PCL 内部不会丢出这个错误），抱歉 Orz（
