### ISSUE TITLE
程序出现未知错误：找不到字段:“System.Reflection.Emit.OpCodes.et_Une”

### ISSUE THREAD

**Issue by pantool1** [Hex-Dragon/PCL2#2146]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

下载MineCraft时，点击版本后，报错：程序出现未知错误：找不到字段:“System.Reflection.Emit.OpCodes.et_Une”......
![屏幕截图 2023-06-30 003559](https://github.com/Hex-Dragon/PCL2/assets/66538816/2766e740-8025-4046-bff5-9a019f7c2131)

### 重现步骤

1、点击xxxx
2、往下滚，然后点击xxxx

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11908254/Log1.txt)

**Comment by LTCatt** [comment]
考虑系统环境问题或者 PCL 文件损坏，这个不是代码导致的问题 :/
