### ISSUE TITLE
[Bug] 检查更新错误

### ISSUE THREAD

**Issue by Zhou-Shilin** [Hex-Dragon/PCL2#2149]
### 检查项

- [x] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

设置-启动器-系统-检查更新 显示当前是“最新正式版本**2.6.1**”
但GitHub Release上发布的最新正式版为[2.6.3](https://github.com/Hex-Dragon/PCL2/releases/tag/2.6.3)
另见日志与附件中的截图
  
_注：我认为我的网络环境没有问题，毕竟我可以流畅的打开GitHub和******_

### 重现步骤

1、进入设置-启动器-系统板块
2、点击检查更新

### 日志与附件

![image](https://github.com/Hex-Dragon/PCL2/assets/86581525/73a594d3-7fcb-49be-8cac-330c48f3a116)

 ### 补充信息

`计算机\HKEY_CURRENT_USER\SOFTWARE\PCL\SystemLastVersionReg`的值为`phF3x4O3d3k=`
不知道是否有用

**Comment by JingHai-Lingyun** [comment]
![bug2149](https://github.com/Hex-Dragon/PCL2/assets/109946426/b642f077-5644-4182-a19e-f5fed3cd4781)
稳定复现
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11912972/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11912974/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11912975/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11912976/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11912977/Log4.txt)

**Comment by youzi-2333** [comment]
[【PCL 更新】咋还有这么多 Bug 啊？](https://www.bilibili.com/read/cv24553314)

……还没推到正式版呢，别急（）

**Comment by Zhou-Shilin** [comment]
> [【PCL 更新】咋还有这么多 Bug 啊？](https://www.bilibili.com/read/cv24553314)
> 
> ……还没推到正式版呢，别急（）

可是测试版？ 我有赞助激活码正式版用不了qwq

**Comment by JingHai-Lingyun** [comment]
我也是

**Comment by iPodtouch6557** [comment]
发个电（）
