### ISSUE TITLE
PCL正式版以及测试版无法选择游戏版本或改变目录

### ISSUE THREAD

**Issue by trgh311** [Hex-Dragon/PCL2#2152]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在我的电脑上无法选择游戏版本和改变目录   测试版和正式版都一样
如果是我没有设置好......那我也没办法

### 重现步骤

1、点击启动
2、就没了（只有启动游戏没有选择版本）

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11915483/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11915485/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11915486/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11915487/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11915488/Log5.txt)
![错误图片](https://github.com/Hex-Dragon/PCL2/assets/122618636/dd98e56b-60ee-42d2-919b-7258ff214847)

**Comment by youzi-2333** [comment]
请确认 `设置——个性化——往下拉——功能隐藏` 中所有选框均**没有**被选中。

**Comment by trgh311** [comment]
可我的PCL2没有功能隐藏这一栏

**Comment by LTDove** [comment]
那不就是隐藏了吗
按f12暂时解除隐藏

**Comment by trgh311** [comment]
......已经解决问题了  没有按f12   我是直接删除PCL文件夹
