### ISSUE TITLE
将奔溃日志分析弹窗中的一句话加粗或以显眼的符号或排版显现建议

### ISSUE THREAD

**Issue by zkitefly** [Hex-Dragon/PCL2#2153]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

![image](https://github.com/Hex-Dragon/PCL2/assets/64117916/7bb3d94e-6bb6-4c57-a483-5f1f9e5befd4)

### 原因

希望能让一些人长长眼睛（

**Comment by LTCatt** [comment]
没救，侠客咋样都是侠客

**Comment by Steven-Jim** [comment]
> 没救，侠客咋样都是侠客

能不能把确定按钮**去掉**
:(
这样或许他会看到按钮

**Comment by JingHai-Lingyun** [comment]
> 能不能把确定按钮去掉

那样的话不想查看或者导出的话就没法关闭弹窗了貌似

**Comment by Deep-Dark-Forest** [comment]
就不能加个强制等待让用户等几秒才能点按钮吗？

**Comment by Open-KFC** [comment]
那么想立刻重新开游戏的用户要~气死了，被个启动器拦在外边~
