### ISSUE TITLE
错误的下载.NET支持库

### ISSUE THREAD

**Issue by Bandysol** [Hex-Dragon/PCL2#2154]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在启动后，错误地下载.NET支持库。安装支持库提示已有支持库。

### 重现步骤

启动启动器？

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11923882/Log1.txt)

**Comment by LTCatt** [comment]
这是系统环境问题，我无法解决 :/
