### ISSUE TITLE
使用外置登录服务器，并使用网络代理时，启动器提示：连接登录服务器超时

### ISSUE THREAD

**Issue by yige233** [Hex-Dragon/PCL2#2168]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我在一台国内服务器上搭建了一个外置登录验证服务器，但因为服务器没备案，只能用ip连接。裸连的状态下，可以正常通过该外置登录启动游戏。然后我在电脑上启动了V2rayN，它为我的系统设置了一个代理服务器。之后我再次启动PCL2，并尝试通过外置登录启动游戏，但启动器在几秒钟内就弹出了`连接登录服务器超时`的提示。

![image](https://github.com/Hex-Dragon/PCL2/assets/34409561/8ba59bc4-a580-437e-b3e2-020e521ca56c)

图中，左上角的窗口是V2rayN的，可以看到它确实有接管连接到验证服务器的请求，并且采用了直接连接的策略。

左下角是验证服务器的log，它对于登录请求都给出了200的响应，所以我认为不是验证服务器的问题。

右边就是启动器报错的弹窗。

关掉系统代理后，就能正常启动了。

用来HMCL最新稳定版试了下，v2rayN能正常接管hmcl发出的请求，并且也是采取直连策略，可以正常启动游戏。

### 重现步骤
1、用v2rayN为系统设置代理服务器
2、为PCL设置一个使用ip作为地址的外置登录验证服务器
3、启动游戏

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11936122/Log1.txt)

**Comment by youzi-2333** [comment]
…自制服务器往往会有更多离奇的问题（

**Comment by LTCatt** [comment]
登录失败原始错误信息：网络请求失败（http://<ip地址>:5401/yggdrasil/authserver/authenticate，基础连接已经关闭: 连接被意外关闭。）
→ 基础连接已经关闭: 连接被意外关闭。

`http://<ip地址>:5401/yggdrasil/authserver/authenticate`
你这第三方服务器设置的是什么鬼玩意儿

**Comment by yige233** [comment]
> 登录失败原始错误信息：网络请求失败（http://<ip地址>:5401/yggdrasil/authserver/authenticate，基础连接已经关闭: 连接被意外关闭。） → 基础连接已经关闭: 连接被意外关闭。
> 
> `http://<ip地址>:5401/yggdrasil/authserver/authenticate` 你这第三方服务器设置的是什么鬼玩意儿

这个明显是我给我的ip打的码呀（麻了

另：我又把相同的验证服务器搬到了另一台可以用域名的机器上进行了测试（同样是V2rayN设置了系统代理，并且在V2rayN中确认了连接是走直连），结果是套了ssl之后可以登录，而去掉了ssl后就会出现我issue中描述的问题

这下没有给任何东西打码了，希望能够引起一些关注

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11949288/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11949289/Log2.txt)

@LTCatt

**Comment by LTCatt** [comment]
说真的，这个是 .net 的底层错误，应该不是我能处理的范围……
