### ISSUE TITLE
模组名称丢失问题

### ISSUE THREAD

**Issue by Chiloven945** [Hex-Dragon/PCL2#2170]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如题
![image](https://github.com/Hex-Dragon/PCL2/assets/116699482/618909c5-7b73-4a30-b1df-bb63ef4b99fb)
![image](https://github.com/Hex-Dragon/PCL2/assets/116699482/8b5a8194-256b-468c-bc69-7cd3e420ded0)

### 重现步骤

搜索ETF

### 日志与附件

*

**Comment by JingHai-Lingyun** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/109946426/7c88d5c2-8625-400a-b443-c64a16bdf90e)
成功复现，感谢您的反馈
