### ISSUE TITLE
模组列表不应该分离大小写排序

### ISSUE THREAD

**Issue by FlameFire26** [Hex-Dragon/PCL2#2172]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

PCL 2.6.1→2.6.3
Mod 管理页面的排序由以前Aa→Zz变成A→Z→a→z
例 Axx axx Bxx cxx 现在变成 Axx Bxx axx cxx
希望更改回以前的样式

### 原因

如果这样，我每次都必须来回翻找，让操作变得很麻烦。
因为不可能知道每个模组作者开头用的是大写还是小写

**Comment by Chiloven945** [comment]
我的建议是无视大小写，因为这似乎并不必要（？

**Comment by FlameFire26** [comment]
是这个意思，我描述有点过了
