### ISSUE TITLE
远古rd阶段的Minecraft似乎可以用Open JDK 22启动而不导致崩溃

### ISSUE THREAD

**Issue by MM-Rabbit** [Hex-Dragon/PCL2#2177]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

rd阶段的Minecraft似乎兼容目前以来发布的所有java，建议可以直接使用Open JDK 22启动rd阶段的Minecraft而不是弹出兼容性警告。

### 原因

这可以让考古的Minecraft玩家有着更好的体验（没啥用？
让PCL2更加美观（？）

**Comment by LTCatt** [comment]
……没啥用
