### ISSUE TITLE
PCL2启动时报错

### ISSUE THREAD

**Issue by AndyGuo12345** [Hex-Dragon/PCL2#2179]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

<img width="331" alt="1688604271283" src="https://github.com/Hex-Dragon/PCL2/assets/109961296/45533694-2ba4-44a4-a51d-dc7723be3bf1">
在双击启动PCL2后报错

### 重现步骤

1、在双击启动PCL2后报错

### 日志与附件

PCL文件夹未生成

**Comment by AndyGuo12345** [comment]
@LTCatt 大概什么时候能修好呢？

**Comment by WForst-Breeze** [comment]
> 大概什么时候能修好呢？

不用着急，一般会在下个快照版修复完成，一般在几周至一个月不等

**Comment by LTCatt** [comment]
PCL 找不到自己这个文件在哪……你这有点闹鬼了……
我严重怀疑是你的系统环境问题，应该非常个别，我也不知道咋修 orz
