### ISSUE TITLE
若 %APPDATA% 路径中存在中文，且系统代码页为 UTF-8，则无法启动 MC

### ISSUE THREAD

**Issue by LTCatt** [Hex-Dragon/PCL2#218]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![ZRLJE01FGM2_$}AWDK2K{B6](https://user-images.githubusercontent.com/40348278/195784383-1e4a76a7-f4db-407d-b4c0-3541e821fd98.png)

**Comment by Louis-ZYH** [comment]
hhh，自己提issue自己处理…………
