### ISSUE TITLE
无故报错

### ISSUE THREAD

**Issue by OJLike** [Hex-Dragon/PCL2#2180]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃不是 PCL2 的原因，请 **不要** 提交反馈。你可以在 QQ 群里或者论坛找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是游戏本身的问题，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

官方启动器没问题 pcl就只装了个api 报错 尝试了删掉重装 还是一样

### 错误报告、日志与附件

[游戏崩溃前的输出.txt](https://github.com/Hex-Dragon/PCL2/files/11963248/default.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11963250/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11963251/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11963252/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11963253/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11963255/Log5.txt)

**Comment by OJLike** [comment]
[错误报告-2023-7-6_9.30.35.zip](https://github.com/Hex-Dragon/PCL2/files/11969803/-2023-7-6_9.30.35.zip)

**Comment by OJLike** [comment]
[启动脚本hmcl.zip](https://github.com/Hex-Dragon/PCL2/files/11969858/hmcl.zip)

**Comment by hejiehao** [comment]
> [启动脚本hmcl.zip](https://github.com/Hex-Dragon/PCL2/files/11969858/hmcl.zip)

先在HMCL里安装Fabric再导出

**Comment by OJLike** [comment]
[启动脚本.zip](https://github.com/Hex-Dragon/PCL2/files/11974998/default.zip)

**Comment by LTCatt** [comment]
你用 HMCL 启动的和用 PCL 启动的不是同一个 MC……

**Comment by OJLike** [comment]
不是叫我在hmcl里安装再导出吗:)

**Comment by LTCatt** [comment]
PCL 不是启动不了某个版本么，用 HMCL 启动 **同一个版本** ，然后上传启动脚本

**Comment by LTCatt** [comment]
请尽快回复并补充 :/

**Comment by LTCatt** [comment]
由于太长时间没有回复先关闭了，如果有需要可以继续在这下面回复
