### ISSUE TITLE
Minecraft 1.5.2 及以下版本会出现无声音的情况

### ISSUE THREAD

**Issue by zkitefly** [Hex-Dragon/PCL2#2182]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [x] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

原因是 MJ ~(SB)~ 关闭了 `http://s3.amazonaws.com/MinecraftResources` 下载通道，导致游戏自身无法从此处下载资源文件，其中就包括声音文件，然后就没声音了

基本上 HMCL 也有这个问题，使用 MMC 没有问题（因为他们专门做了个外部下载的）

解决方法也很简单，下载 assets 到版本文件夹的 `resources` 文件夹（不是 `resourcepacks` 哈）即可修复（就是手动帮 MC 下载资源）

这个文件夹：

![image](https://github.com/Hex-Dragon/PCL2/assets/64117916/caf32806-b06a-4bc4-95de-e6502decaa2f)

![image](https://github.com/Hex-Dragon/PCL2/assets/64117916/f0b9d79d-755c-47df-b955-38ace88a0891)

这些文件：
![image](https://github.com/Hex-Dragon/PCL2/assets/64117916/58828bf3-8f45-4b8b-af8b-0b764b2e6ecb)

### 重现步骤

1.下载一个 1.5.2 及以下版本
2.启动游戏
3.发现没声音（

### 日志与附件

X

**Comment by iPodtouch6557** [comment]
有道理:/

**Comment by youzi-2333** [comment]
额，就是说需要让 PCL 帮 MC 把老版本的 resources 给补全……？
还有就是，自信点，把删除线去掉（

**Comment by zkitefly** [comment]
> 额，就是说需要让 PCL 帮 MC 把老版本的 resources 给补全……？ 还有就是，自信点，把删除线去掉（

是的

**Comment by LTCatt** [comment]
但是现在有这个文件的下载源么（

**Comment by zkitefly** [comment]
> 但是现在有这个文件的下载源么（

就是这里的文件：
![image](https://github.com/Hex-Dragon/PCL2/assets/64117916/d5f23a58-d95c-48c4-ad34-87fc7319144d)

**Comment by zkitefly** [comment]
找到好的解决方法了：

只要读到  assetIndex json 里面有 `map_to_resources` 值，就将 assetsDir 弄到版本文件夹的 `resource` 文件夹就行了，然后 HMCL 应该就会往 assetsDir ，也就是 `resource` 文件夹里下东西了

![image](https://github.com/huanghongxun/HMCL/assets/64117916/cb148c53-4fd0-483f-8bc4-51c777aa6aff)
![image](https://github.com/huanghongxun/HMCL/assets/64117916/87123672-2d64-4def-a259-4758905147a3)
![image](https://github.com/huanghongxun/HMCL/assets/64117916/e61fe116-609e-4ef3-9f90-1bc58d386089)
![image](https://github.com/huanghongxun/HMCL/assets/64117916/3db11715-f30f-4e25-a926-bcfa025a16d9)
