### ISSUE TITLE
带--memory参数时无法启动PCL2

### ISSUE THREAD

**Issue by plants13** [Hex-Dragon/PCL2#2183]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

很简单 如题
且Log1~5.txt中没有任何内容更新

### 重现步骤

任选其一：
1.创建快捷方式，在目标末尾加 --memory参数 启动，观察到任务管理器短暂出现启动器进程然后消失
2.所在目录中启动cmd 输入"Plain Craft Launcher 2.exe" --memory 回车 现象一致

### 日志与附件

传了也没啥用 根本没有内容更新
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11963883/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11963885/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11963887/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11963888/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11963889/Log5.txt)

**Comment by youzi-2333** [comment]
那是因为带了 `--memory` 参数，PCL 把内存优化好之后，就直接自动退出了……

**Comment by plants13** [comment]
啊？我还以为是执行完然后继续启动流程。。。这个是不是应该在你知道吗和百宝箱按钮里注明一下？

**Comment by youzi-2333** [comment]
不用说明了吧……只要自己用一下就知道了，毕竟 ToolTip 的内容还是要以简为主（
