### ISSUE TITLE
当使用 fabric 启动 minecraft 弹出模组错误弹窗时，只要不取消错误界面，PCL 会一直停在启动时的界面

### ISSUE THREAD

**Issue by iPodtouch6557** [Hex-Dragon/PCL2#2184]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如题，游戏已经出现了错误并甩出了错误弹窗，这就说明现在无法启动游戏，然而PCL却显示还在等待游戏窗口出现……
只要不点取消这个界面就能再显示个114514年（）
其实我不太确定这个问题是不是有问题了，但我还是打算先交了，看看再说，如果出问题的情况跟我要反馈的问题不太一样的话，我再改

### 重现步骤

1、启动一个带有_无法正确加载的fabric mod_的版本
2、等待其弹出fabric错误弹窗
3、再观察启动页左侧，会发现该问题
4、取消窗口才会检测到错误，直接取消则不会

### 日志与附件

附件：一个图片
![image](https://github.com/Hex-Dragon/PCL2/assets/118656946/8f423f6f-0e25-4df6-943c-615d77da8fd2)

五个log（第一个好像是远古时期的doge）
[Log.txt](https://github.com/Hex-Dragon/PCL2/files/11964947/Log.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11964948/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11964949/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11964950/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11964952/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11964953/Log5.txt)

**Comment by LTCatt** [comment]
正常情况，Fabric 在这之前不会给出足以判定崩溃的信息
