### ISSUE TITLE
PCL2疑似无法识别/错误的识别注册表备份的内容

### ISSUE THREAD

**Issue by Kandkchina** [Hex-Dragon/PCL2#2186]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

使用一个来自Snapshot 2.4.3（也许是？）版PCL2备份的注册表内容（Windows 10）并尝试在Snapshot 2.6.3（Windows 11）的环境下对注册表进行覆盖，Snapshot 2.6.3内的正版设置及隐藏主题解锁全部被重置。
使用Snapshot 2.6.3备份的注册表项在同版本下打开正常。

### 重现步骤

1、使用Snapshot 2.4.3（Windows 10）备份一份PCL2的注册表设置项（帮助-->启动器-->备份启动器设置）
2、将备份的注册表文件拷贝至Snapshot 2.6.3（Windows 11）的环境下，覆盖注册表项
3、启动PCL2，BUG复现完成

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11966566/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11966567/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11966568/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11966570/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11966571/Log5.txt)

**Comment by LTCatt** [comment]
出于安全考虑，登录信息与部分解锁信息即使备份也无法跨系统迁移 :/
