### ISSUE TITLE
在 启动游戏 的时候，触发一遍 内存优化 功能，再启动游戏

### ISSUE THREAD

**Issue by zkitefly** [Hex-Dragon/PCL2#2187]
### 检查项

- [x] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

在点击 启动游戏 的时候，触发一遍 内存优化 功能，再启动游戏

### 原因

能在启动游戏的时候，优化下内存再启动，或许好一点？

**Comment by dargoncat** [comment]
好像可以在PCL启动参数里面加--memory自动优化内存吧（~一般来说不都是开了启动器就开MC的吗~）

**Comment by zkitefly** [comment]
:thinking: 确实

**Comment by zkitefly** [comment]
不过我想在点 启动游戏 的时候触发 优化内存 其他时候不想触发 :thinking:

**Comment by youzi-2333** [comment]
额，内存优化要管理员权限，不知道这样会不会使 PCL 启动变得更加麻烦……

> 好像可以在PCL启动参数里面加--memory自动优化内存吧（~一般来说不都是开了启动器就开MC的吗~）

首先 `--memory` 优化好之后就直接退出了，~~其次 PCL 是音乐播放器和文件下载器~~

**Comment by zkitefly** [comment]
内存优化 功能会自动索要管理员权限的好像，点那个同意不就行了（
 做个不默认开启的开关，想开的开？

**Comment by iPodtouch6557** [comment]
> 好像可以在PCL启动参数里面加--memory自动优化内存吧（~一般来说不都是开了启动器就开MC的吗~）

好吧，我是二般人……我会开pcl专门听音乐

**Comment by MM-Rabbit** [comment]
> > 好像可以在PCL启动参数里面加--memory自动优化内存吧（~一般来说不都是开了启动器就开MC的吗~）
> 
> 好吧，我是二般人……我会开pcl专门听音乐

我会用它折腾和下载文件awa

**Comment by youzi-2333** [comment]
……请勿过多讨论 Issue 无关内容，否则 Issue 可能会被锁定（禁止发言），感谢配合 qwq

**Comment by hellominecraftlauncher** [comment]
不是-memory吗，我用--memory没法启动

**Comment by SALTWOOD** [comment]
> 不是-memory吗，我用--memory没法启动

是静默启动的，而且这个功能说实话没啥用
可以让用户选择是否在启动游戏前内存清理

**Comment by youzi-2333** [comment]
> 是静默启动的，而且这个功能说实话没啥用

额，你觉得没啥用，但是对于整合包作者其实用处挺大的，可以使用自定义主页直接内存优化（运行中程序对自身应该有读权限）

> 可以让用户选择是否在启动游戏前内存清理

这不是就在做吗.jpg

**Comment by SALTWOOD** [comment]
> > 是静默启动的，而且这个功能说实话没啥用
> 
> 额，你觉得没啥用，但是对于整合包作者其实用处挺大的，可以使用自定义主页直接内存优化（运行中程序对自身应该有读权限）
那确实是，我做整合包的，但因为是modrinth格式不包含启动器所以没想到（
感觉可以把这个功能放显眼些

**Comment by miner233** [comment]
最好加一个设置，默认在启动游戏时不进行内存优化，但是可以在设置中开启这个功能。

**Comment by YunzeWu** [comment]
倒也可以，不然在启动时都要管理员权限，还要不要做人了？？？

**Comment by hellominecraftlauncher** [comment]
有些服务器的PCL需要预启动反作弊，而又需要PCL作启动器，可能这点方便吧
