### ISSUE TITLE
[优化] 由于内存不足导致游戏崩溃的文案修改

### ISSUE THREAD

**Issue by youzi-2333** [Hex-Dragon/PCL2#2189]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

目前，内存不足导致游戏崩溃的文案如下：

![文案.jpg](https://github.com/Hex-Dragon/PCL2/assets/106497113/23fcf1f8-8bc4-4608-84c1-d9372fee2340)

希望在第二段第二行（或第一行）引导用户前往 `更多 -> 百宝箱 -> 内存优化` 进行优化，再重新启动游戏。

不交 pr 的原因是，我感觉 pr 的 merge 比较麻烦，所以让龙猫自己改一改算了……

### 原因

这样可以方便更多用户了解内存优化功能，同时帮助游戏正常运行。

**Comment by JingHai-Lingyun** [comment]
优化文字后建议直接加上内存优化的执行按钮
