### ISSUE TITLE
宽度和高度必须为非负值

### ISSUE THREAD

**Issue by Godspeeddoge** [Hex-Dragon/PCL2#2196]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

PCL程序突然崩溃 在点击下载（出现几率更高）/设置/更多界面操作时会出现
包括：停留在界面突然出现错误 一点进去就出现错误 点击下载时出现错误 与界面互动时（上划下滑点击）出现错误

### 重现步骤

1、点击下载
2、点击自动安装/Mod/资源包的任意一个选项
3.列表出现 点击下载时或者往下翻的时候
4.程序崩溃  

错误程序描述
标题：锟斤拷烫烫烫
描述：程序出现位置错误：宽度和高度必须为非负值
错误类型：System.ArgumentException

是否反馈此问题？如果不反馈，这个问题可能永远无法解决

在一次打开中，在设置选项栏里面也会出现此错误
已在正式版2.6.2出现此问题 于2023/07/08更新至正式版2.6.3仍然出现此问题

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11987254/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11987255/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11987256/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11987257/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11987258/Log1.txt)

**Comment by LTCatt** [comment]
加一下 QQ 1043137532，备注写 issue 2196……

备注：疑似下载页面有一个 Border 出现了负数宽高，可能是 MyListItem.RectBack

**Comment by Godspeeddoge** [comment]
已经加你并且发你了视频了

**Comment by LTCatt** [comment]
寻思了半天没看出来哪有问题，实在整不会了，如果有第二例再尝试修复 :/
