### ISSUE TITLE
[优化] 内存优化不重复提权

### ISSUE THREAD

**Issue by youzi-2333** [Hex-Dragon/PCL2#2197]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

目前，使用正常方式启动 PCL，内存优化会要求权限。
但是如果再次优化，会再次要求权限。本来已经要过权限了，理论上已经有足够权限进行优化。
建议在二次优化时，不进行重复提权。

### 原因

这样可以使操作变得方便一点，毕竟提权要点一个 PCL 窗口的“确定”，还要点一个 UAC 窗口的“是”……

### 技术信息

如果可以的话，在提权函数运行成功后，直接将启动器“有权限”的字段标记为 True；如果这样提权不能保留权限的话，那么可以参考以前联机提权所使用的“使用管理员身份重启”。

**Comment by bwtx2023** [comment]
但是使用管理员身份重启会导致拖拽功能失效…

**Comment by youzi-2333** [comment]
> 但是使用管理员身份重启会导致拖拽功能失效…

额，理论上不会的吧……
你说的是文件拖进窗口还是窗口位置移动？

**Comment by jocemod** [comment]
管理员身份不会使拖拽功能失效吧，我用管理员启动pcl2年了，没出过问题

**Comment by WForst-Breeze** [comment]
> 额，理论上不会的吧…… 你说的是文件拖进窗口还是窗口位置移动？

你可以试一下，将文件拖进 PCL2 窗口指针会显示禁止符号（

**Comment by youzi-2333** [comment]
> 你可以试一下，将文件拖进 PCL2 窗口指针会显示禁止符号（

好吧，确实是这样，而且这应该是 Windows 的问题（

**Comment by jocemod** [comment]
windows1022H2不会，应该是后面的更新有改过

**Comment by jocemod** [comment]
我普通管理员身份运行没事，system身份运行时无法拖拽，但普通管理员身份也可运行内存优化

**Comment by LTCatt** [comment]
技术上没有办法，除非真的要重启 PCL……还是算了……:/

**Comment by iPodtouch6557** [comment]
我倒是很奇怪，点开内存优化，只要啥都不干，就能降下一半……后来发现是我的管理员提示不知何时被关了（）
