### ISSUE TITLE
在系统语言为法语的情况下无法启动

### ISSUE THREAD

**Issue by KMSGo** [Hex-Dragon/PCL2#2203]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如题，在Windows语言为法语的时候，PCL2无法启动

![image](https://github.com/Hex-Dragon/PCL2/assets/47738260/ef925b8f-dd53-44b9-bc4c-24fd3f9328e5)

### 重现步骤

1、将Windows语言设置为法语
2、启动PCL2

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11994458/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11994459/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11994455/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11994456/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11994457/Log5.txt)

**Comment by WForst-Breeze** [comment]
```
[13:04:43.374] [Start] 程序版本：Release 2.6.1（293）
```
请确保启动器版本为最新版

**Comment by KMSGo** [comment]
Release 2.6.3 bug修了
