### ISSUE TITLE
让音乐播放进度条变得更加明显并且支持拖动

### ISSUE THREAD

**Issue by deep-dark-forest** [Hex-Dragon/PCL2#2205]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

让进度条更明显一些......我给出一种可行的方案》？
![image](https://github.com/Hex-Dragon/PCL2/assets/131975043/567d9667-6fc6-4d20-bfd8-0dcbb663fcbc)
瞎画的，外面那一圈就是音乐进度条，鼠标靠近时还会变粗并且可以拖拽来改变现在是播放的几分几秒，不知道行不行

### 原因

现在这个进度条有点费眼睛，而且不能拖拽，有点麻烦

**Comment by deep-dark-forest** [comment]
进度条更明显估计是没辙了，因为还需要涉及到主题色问题......

**Comment by WForst-Breeze** [comment]
这个功能的原始 Issue 就是在外圈加进度条，结果估计是报看，就做成了现在的样子

**Comment by deep-dark-forest** [comment]
哦，六角龙机器人好像坏掉了
