### ISSUE TITLE
 为什么打开启动器显示会 以一种访问权限不允许的方式做了一个访问套接字的尝试

### ISSUE THREAD

**Issue by MCmaodou** [Hex-Dragon/PCL2#2208]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃不是 PCL2 的原因，请 **不要** 提交反馈。你可以在 QQ 群里或者论坛找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是游戏本身的问题，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

以一种访问权限不允许的方式做了一个访问套接字的尝试

### 错误报告、日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11997583/Log1.txt)

**Comment by JingHai-Lingyun** [comment]
你的网络问题？

**Comment by Chiloven945** [comment]
截图，而且这种情况一般均为网络问题，请尝试检查你的网络

**Comment by youzi-2333** [comment]
请爱发电私信发送 `更新 [你的识别码]` 将 PCL 升级至最新版本再试。

**Comment by Bandysol** [comment]
龙猫换网址了吧，然后旧版的网址就出错。

**Comment by youzi-2333** [comment]
umm 确实大概率是换网址了（2.3.0 之后应该没这问题）

另外，请 @MCmaodou 尽快补充信息，07/20 之前未回复将被关闭，感谢配合。

**Comment by LTCatt** [comment]
过老的版本已不支持自动更新
