### ISSUE TITLE
自定义下载报错无法消除

### ISSUE THREAD

**Issue by misividkoukou** [Hex-Dragon/PCL2#2212]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

自定义下载网址写错了就没法消除报错了

### 重现步骤

1、选择百宝箱按钮
2、随便搞点东西上
3，删了
4，出现了bug

### 日志与附件

浏览器不支持上传，谁给我发个edge安装包？

**Comment by Chiloven945** [comment]
#1235
请尝试更新你的启动器

**Comment by misividkoukou** [comment]
但是事实上这个bug在最新版pcl中依旧存在

**Comment by youzi-2333** [comment]
不太确定是不是刻意设计。……先让龙猫看看吧.jpg

**Comment by LTCatt** [comment]
无法重现，其他人能重现么

**Comment by MM-Rabbit** [comment]
![屏幕截图 2023-07-10 192653](https://github.com/Hex-Dragon/PCL2/assets/118085239/1b9d1d8f-ca5e-442b-88f3-216ebf0206a0)
@LTCatt 我可以复现

**Comment by MM-Rabbit** [comment]
> ![屏幕截图 2023-07-10 192653](https://user-images.githubusercontent.com/118085239/252324906-1b9d1d8f-ca5e-442b-88f3-216ebf0206a0.jpg) @LTCatt 我可以复现

不要理那个PCL 2.4.4，文件夹懒得改了，是2.6.3

**Comment by youzi-2333** [comment]
大概意思就是，文本框里面输入点东西，再删掉，它还是会说网址无效……

**Comment by iPodtouch6557** [comment]
> 大概意思就是，文本框里面输入点东西，再删掉，它还是会说网址无效……

是的，我也发现了（
就是从默认状态（空状态）开始，输错一遍网址后，只要你的网址没有输对，它就会永远显示网址无效

**Comment by LTCatt** [comment]
这是刻意的设计……
