### ISSUE TITLE
建议包

### ISSUE THREAD

**Issue by NebulaTechs** [Hex-Dragon/PCL2#2214]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

一.，可以增加一些程序命令，如下
1，/launch 启动主面板
2，/install 下载页面
3，/setting 设置
4，/offmc 关闭正在运行的MC
5，/launchmc 启动MC
6，/exit 退出
7，/hide 隐藏(至托盘，下面有相关建议)
二，可以用ctrl+H快速隐藏/显示PCL主面板及Minecraft。

### 原因

一，可以给敲惯了命令行的人一点点偷懒的机会。。。
二，可以让X些人在上班时摸鱼。。。

**Comment by Big-Cake-jpg** [comment]
为什么好好的图形界面摆在那里不用要去用命令行……

**Comment by Big-Cake-jpg** [comment]
> 还有:能不能出一个毛玻璃主题？[试探]

不要在一个 Issue 内提出多个建议。且高斯模糊效果可能会导致严重的性能问题，对较为老旧的一些机器来说不友好。

**Comment by LTCatt** [comment]
不考虑制作，抱歉（

**Comment by WForst-Breeze** [comment]
> 可以用ctrl+H快速隐藏/显示PCL主面板及Minecraft。这个还是建议做一下。

猜你想要：Win+D

**Comment by iPodtouch6557** [comment]
> 可以用ctrl+H快速隐藏/显示PCL主面板及Minecraft。这个还是建议做一

so请不要把多条建议坨进一个issue里……
