### ISSUE TITLE
GLFW ERROR 65543错误 仅在pcl2启动器出现

### ISSUE THREAD

**Issue by diamondpig** [Hex-Dragon/PCL2#2215]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

当我打开1.17.1及以上的版本时 会出现GLFW ERROR 65543错误  但是当我使用HMCL及其他启动器时 却能启动成功   我的OPENGL为最新版本 显卡是i3-4160核显

### 重现步骤

1、打开1.17及以上版本
2、然后出现错误

### 日志与附件

![QQ图片20230710143443](https://github.com/Hex-Dragon/PCL2/assets/105978046/4d25fd47-9164-4f47-80b3-47aadba138b5)

关闭此错误时出现
![QQ图片20230710143448](https://github.com/Hex-Dragon/PCL2/assets/105978046/18afcaee-0ed0-416b-81c6-559d023e5103)

**Comment by diamondpig** [comment]
还有 我的显卡驱动也是最新版

**Comment by Chiloven945** [comment]
Log1~Log5不发怎么给你解决问题

**Comment by diamondpig** [comment]
> Log1~Log5不发怎么给你解决问题

好
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11999349/Log5.txt)

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11999343/Log1.txt)
[Log2.txt](https://github.com/Hex-D
[Log3.txt](https://github.com/H
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11999348/Log4.txt)
ex-Dragon/PCL2/files/11999346/Log3.txt)
ragon/PCL2/files/11999345/Log2.txt)

**Comment by diamondpig** [comment]
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11999360/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11999361/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11999364/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11999365/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11999366/Log5.txt)
忘记发log1-log5了
