### ISSUE TITLE
能不能出一个毛玻璃主题？[试探]

### ISSUE THREAD

**Issue by NebulaTechs** [Hex-Dragon/PCL2#2216]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

#2214 可以默认关闭，并在打开前弹出警告。。。

### 原因

更加好看

**Comment by Chiloven945** [comment]
WPF应该可以实现毛玻璃，但是龙猫不大可能会去做新的主题，这很费时费力

**Comment by LTCatt** [comment]
不考虑制作，抱歉（
