### ISSUE TITLE
自定义下载错误报错

### ISSUE THREAD

**Issue by misividkoukou** [Hex-Dragon/PCL2#2218]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

麻烦有的管理不要没有证实就关issue好不好，我的启动器是最新版本2.6.3内测版

### 重现步骤

1、选择百宝箱自定义下载文本框
2、随便搞点东西上
3，删了
4，出现了bug

### 日志与附件

无

**Comment by Chiloven945** [comment]
你已经交了一个issue了请不要反馈重复的问题
