### ISSUE TITLE
加入循环执行内存优化的选项

### ISSUE THREAD

**Issue by MM-Rabbit** [Hex-Dragon/PCL2#2221]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

每次玩大型整合包或数据包时经常会遇到内存不够的问题啊，就这么启动游戏，进地图玩几下就得自己手动打开PCL2进行内存优化，不知可不可以添加一个循环执行内存优化的功能，不用了还可以退出循环；最好能够添加每次执行完内存优化时的延时功能，就是每次执行完内存优化等待几秒再开始进行下一次内存优化。这对我、一些经常玩整合包的玩家以及一些腐竹会有帮助，所以还是希望龙猫可以加一下，应该也不难吧？在py就是一个while True循环，再加time.sleep函数，最后检测按键或是按钮触发break？（不会.NET）

### 原因

这可以帮助我、一些经常玩整合包的玩家或是一些腐竹有着更加好的内存优化体验，让内存优化功能更加实用。
（不过如果龙猫实在不想加就不加吧，毕竟我也知道龙猫没做的新功能实在是太多了qwq）

**Comment by bwtx2023** [comment]
内存优化貌似会把 MC 也给优化进 SWAP 吧…

**Comment by MM-Rabbit** [comment]
我也不求别的了，就是想随便出个功能意思一下就行qwq

**Comment by LTCatt** [comment]
你可以使用 --memory 函数启动 PCL，加一个计划任务就行
