### ISSUE TITLE
外观优化

### ISSUE THREAD

**Issue by NebulaTechs** [Hex-Dragon/PCL2#2222]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

<img width="600" alt="屏幕截图 2023-07-10 202615" src="https://github.com/Hex-Dragon/PCL2/assets/126944988/9e53ba3d-d56e-42d8-aa85-6a5792ffec1c">
这样或许有点丑，建议取消对主题色的遮盖，变成再点击时任意主题时显示这段文字。

### 原因

（示例）
这项优化让我可以更方便地xxxx。
如果没有这项优化，我每次都必须xxxx，让操作变得很麻烦。

**Comment by youzi-2333** [comment]
这样会让玩家看到的时候尝试点一下，然后发现不能改，然后非常生气……

大概率不会改.jpg

**Comment by youzi-2333** [comment]
这不是技术的问题，毕竟是“优化”，要让用户操作、理解等各个方面都要简便，改的更奇怪了那还不如不改……
到时候看龙猫想法（

**Comment by iPodtouch6557** [comment]
> 这不是技术的问题，毕竟是“优化”，要让用户操作、理解等各个方面都要简便，改的更奇怪了那还不如不改…… 到时候看龙猫想法（

我认为可以不要遮盖，在正式版直接把不透明度以下的部分变成文本加按钮，然后适配的好看一点

**Comment by LTCatt** [comment]
没啥必要改……
