### ISSUE TITLE
整合包最近更新显示错误

### ISSUE THREAD

**Issue by BlackRiceXY** [Hex-Dragon/PCL2#2223]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/Hex-Dragon/PCL2/assets/37988566/894f419d-9f38-4059-b38c-bc23cf9dbd6e)
![image](https://github.com/Hex-Dragon/PCL2/assets/37988566/6f89b279-d0af-4d08-98d4-b0c3c3b6fdcc)
整合包最近更新里外显示不同，外面会减少一天

### 重现步骤

无

### 日志与附件

无

**Comment by BlackRiceXY** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/37988566/89cd426c-dc21-4302-90b3-0b2c3f4aa0c4)
![image](https://github.com/Hex-Dragon/PCL2/assets/37988566/58853f29-95d7-48de-b870-b8f75b46f58e)

**Comment by MM-Rabbit** [comment]
> 稳定复现，确实有点奇怪...

不过好像别的整合包不会有这样的Bug？

**Comment by MM-Rabbit** [comment]
> > > 稳定复现，确实有点奇怪...
> > 
> > 
> > 不过好像别的整合包不会有这样的Bug？
> 
> 还是说这只是个个例？

不过All the Mods 8好像也有类似的Bug...等管理员或者龙猫看看怎么说吧

**Comment by youzi-2333** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/106497113/44722e49-e76f-4594-b4d1-94c59d9c62c4)

应该是外面那个时间的问题……我感觉没法修（

---

额，@MM-Rabbit 请使用 GitHub 的 Edit 功能（右上角三个点——Edit），不要发那么多 Comment，会炸别人邮箱的……
