### ISSUE TITLE
背景图片使用智能自适应方式出现问题。

### ISSUE THREAD

**Issue by Altria7** [Hex-Dragon/PCL2#2224]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我有两张背景图片，使用智能自适应时其中一张图片适应异常，如下图一。该图片的属性如下图二。
<img width="608" alt="屏幕截图 2023-07-10 220325" src="https://github.com/Hex-Dragon/PCL2/assets/95865658/51cd95d5-eeb6-4147-9314-65cb4774e157">
<img width="331" alt="屏幕截图 2023-07-10 221324" src="https://github.com/Hex-Dragon/PCL2/assets/95865658/6c58f5be-7a20-48fb-bbce-7dbf938e34ec">

### 重现步骤

1、将背景图片适应方式设置为智能。
2、将该图片设置为背景图片。(该图片见附件)

### 日志与附件

![88643173_p0](https://github.com/Hex-Dragon/PCL2/assets/95865658/b0ff6154-871e-4e0f-9d66-db886ebea631)

**Comment by youzi-2333** [comment]
稳定复现，感谢您的反馈。

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12009361/Log1.txt)

**Comment by Altria7** [comment]
> 稳定复现，感谢您的反馈。
> 
> [Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12009361/Log1.txt)

识别码:43F0-9BD6-E42C-8B93

**Comment by LTCatt** [comment]
你的解锁码：AJ7nC7XyRYtJeECkNxTmGFqcTrvqPQAA
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
