### ISSUE TITLE
[优化] 主题色的单选选项优化

### ISSUE THREAD

**Issue by youzi-2333** [Hex-Dragon/PCL2#2227]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

目前，如果我选中 A 主题，然后在 B 主题色选项上悬浮鼠标，那么 B 选项的颜色是 A 颜色。

建议改为 B 选项的颜色是 B 颜色，即任意选项颜色就是该主题色，方便用户理解。
如果合适，可以在悬浮 1 秒以上时，自动应用该主题颜色的预览，鼠标挪开时恢复原主题。

### 原因

这样可以方便用户判断主题的颜色……

**Comment by LTCatt** [comment]
由于适用范围较小，且投票票数也很低，暂不考虑制作
