### ISSUE TITLE
[优化] 优化mod更新时间显示

### ISSUE THREAD

**Issue by 212112111zwl** [Hex-Dragon/PCL2#2231]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在mod更新时间在一小时之内时显示具体分钟数
![image](https://github.com/Hex-Dragon/PCL2/assets/121177845/ec4642a4-ab5f-4eb9-b17b-ad1f3da7f7e4)

### 原因

0小时看起来很奇怪呀
就是不知道api支不支持精确到分钟了

**Comment by youzi-2333** [comment]
Modrinth API 是支持精确到微秒的……
```json
{"id":"ssUbhMkL","slug":"gravestones","...":"...","published":"2020-10-21T22:19:51.707450Z","updated":"2023-06-18T07:52:45.604747Z","approved":"2020-10-21T22:19:51.707450Z","queued":null,"...":"...","flame_anvil_user":null,"color":7037535}
```

**Comment by LTCatt** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/ec1c5cc7-6ad7-4ea9-a537-0f4ae1f2e5d0)
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/0bd1bba1-6ccd-47f8-b54d-35992f107403)
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/8a861c73-1191-4d1c-bf20-d6174bc944c3)

无法复现，可能太偶发了，我也搞不懂咋回事……
