### ISSUE TITLE
安装 OptiFine/Forge 失败：Invalid or corrupt jarfile / 序列不包含任何元素

### ISSUE THREAD

**Issue by Xx114514xX1819** [Hex-Dragon/PCL2#2232]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

下载 Forge 36.2.39失败
→ 安装 Mod 加载器（方式 A）失败
→ 安装新 Forge 版本失败
→ 序列不包含任何元素
   在 PCL.ModDownloadLib._Closure$__37-0._Lambda$__7(LoaderTask`2 Task)
   在 PCL.ModLoader.LoaderTask`2._Closure$__12-0._Lambda$__0()
   在 PCL.ModDownloadLib.ForgeInjector(String Target, LoaderTask`2 Task, String McFolder)
   在 PCL.ModDownloadLib._Closure$__37-0._Lambda$__7(LoaderTask`2 Task)
错误类型：System.InvalidOperationException

(在朋友电脑上稳定复现)

### 重现步骤

1、点击下载
2、选择1.16.5
3、选择forge36.2.39+optifine G8
4、点击开始安装

### 日志与附件

![下载](https://github.com/Hex-Dragon/PCL2/assets/114345474/bd5a9673-46a0-43f3-ac99-a2e698ac3b1e)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12023482/Log5.txt)
[Log.txt](https://github.com/Hex-Dragon/PCL2/files/12023483/Log.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12023484/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12023485/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12023486/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12023487/Log4.txt)

**Comment by zkitefly** [comment]
似乎是 JavaWrapper 的问题？

**Comment by bwtx2023** [comment]
LTCatt 分配给了 00II00 .jpg

**Comment by LTCatt** [comment]
无法复现，其他人能重现这个问题吗？

**Comment by Xx114514xX1819** [comment]
又试了一次，能复现，我怀疑是和我电脑上的zulujava有关，我一共安装了三个版本的java，分别是8 11 17

**Comment by Xx114514xX1819** [comment]
在我一个安装了zulujava的朋友电脑上能复现，但在一个安装了oraclejava的朋友电脑上据他所说不能复现

**Comment by 00ll00** [comment]
我看log里好像用zulujava启动成功过？
是只有在1.16.5 + forge36.2.39 + optifine G8的情况下会触发吗

**Comment by Xx114514xX1819** [comment]
其它组合没试过，发现装不了以后就去用HMCL了

**Comment by Xx114514xX1819** [comment]
我用HMCL下载了一个同样的1.16.5后用PCL可以正常运行，说明只是安装游戏有问题

**Comment by Xx114514xX1819** [comment]
实测1.16.5只带optifine G8不带forge能正常安装游戏

**Comment by Xx114514xX1819** [comment]
1.16.5只带forge安装成功??????????????

**Comment by Chiloven945** [comment]
未能复现，我用的也是zulu的jdk

**Comment by llhk12345** [comment]
完美复现
这是我的log
![image](https://github.com/Hex-Dragon/PCL2/assets/139436575/69b1dd0f-1cec-45ed-a4d5-09b49184b20a)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12036336/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12036337/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12036338/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12036339/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12036340/Log5.txt)

**Comment by llhk12345** [comment]
我开着梯子能安装成功但是没开梯子却不行（?）这是我的log

![image](https://github.com/Hex-Dragon/PCL2/assets/139436575/61b78c1f-ae9c-420d-934c-ce4c18689dda)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12036383/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12036384/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12036385/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12036386/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12036387/Log5.txt)

**Comment by Xx114514xX1819** [comment]
（?）我开着梯子也突然可以安装了，难道是网络的问题？可是隔壁HMCL不开梯子可以安装啊
![image](https://github.com/Hex-Dragon/PCL2/assets/114345474/688732f0-476b-47da-a2da-1d202db515ed)

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12036428/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12036430/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12036431/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12036432/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12036433/Log5.txt)
[Log.txt](https://github.com/Hex-Dragon/PCL2/files/12036434/Log.txt)

**Comment by deep-dark-forest** [comment]
所以@00ll00 是谁

**Comment by 00ll00** [comment]
如果能复现的话试试直接在命令行执行 `java -jar JavaWrapper.jar` 会发生什么？（用zulu的java.exe）

**Comment by Xx114514xX1819** [comment]
C:\Users\T1502>java -jar JavaWrapper.jar
Error: Unable to access jarfile JavaWrapper.jar
![image](https://github.com/Hex-Dragon/PCL2/assets/114345474/5967d370-3579-4f24-a210-5c6e87f4503c)

**Comment by Xx114514xX1819** [comment]
C:\Users\T1502>java -jar C:\Users\T1502\AppData\Roaming\PCL\JavaWrapper.jar
jlw: releasing native file to 'C:\Users\T1502\AppData\Local\Temp\libjlw-1.3.2.dll'.
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
        at oolloo.jlw.Wrapper.main(Wrapper.java:45)
![image](https://github.com/Hex-Dragon/PCL2/assets/114345474/9af0dfd4-9bff-44f1-b255-3957ba712c91)

**Comment by Xx114514xX1819** [comment]
已重装系统，java是原来的，目前安装游戏不再出现上述问题，但是运行java -jar JavaWrapper.jar 指令的结果和上次无区别，可是这个问题在没重装系统的朋友电脑上依旧稳定复现（朋友电脑上的PCL是稳定版）
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12207461/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12207462/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12207463/Log5.txt)
[Log.txt](https://github.com/Hex-Dragon/PCL2/files/12207464/Log.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12207465/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12207466/Log2.txt)

**Comment by FuturaICG** [comment]
成功复现。
![586L65{OH9SK}HT R0O5 2](https://github.com/Hex-Dragon/PCL2/assets/142072318/c7901edf-875f-4b48-a168-4506d6bf5aa6)

这是我的LOG。
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12326532/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12326533/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12326534/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12326535/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12326536/Log3.txt)

**Comment by 00ll00** [comment]
> C:\Users\T1502>java -jar C:\Users\T1502\AppData\Roaming\PCL\JavaWrapper.jar jlw: releasing native file to 'C:\Users\T1502\AppData\Local\Temp\libjlw-1.3.2.dll'. Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3 at oolloo.jlw.Wrapper.main(Wrapper.java:45) ![image](https://user-images.githubusercontent.com/114345474/254560081-9af0dfd4-9bff-44f1-b255-3957ba712c91.png)

这个报错是意料之中的，因为没有给wrapper提供主类。这样的话看起来不像是wrapper炸了，毕竟wrapper.jar可以被jvm正常加载并运行。

好像目前所有触发这个问题的都是在win11系统下安装Optifine/Forge的时候，让win11的龙猫研究研究。

🏃(

**Comment by LTCatt** [comment]
先加了个不使用 Java Wrapper 的重试，如果还是不行那就只能是 Zulu Java 的 bug 了……

**Comment by TaiMiao** [comment]
识别码

**Comment by allMagicNB** [comment]
> B7E3-7CDE-B86A-1270

？你要怎么证明作者是你？

**Comment by Ad-closeNN** [comment]
> B7E3-7CDE-B86A-1270

？这不是别人ghost开的issue吗你怎么放出识别码了...如果你有已打上`完成` `Bug`标签的issue请去到那条issue发你的识别码

**Comment by allMagicNB** [comment]
> > B7E3-7CDE-B86A-1270
> 
> ？这不是别人ghost开的issue吗你怎么放出识别码了...如果你有已打上`完成` `Bug`标签的issue请去到那条issue发你的识别码

你也不看看 ghost 有几条 Issue（

**Comment by JingHai-Lingyun** [comment]
> B7E3-7CDE-B86A-1270

这不是你的 Issue，如果你有已打上 `Bug` `完成` 标签的 Issue 请去到那条 Issue 发你的识别码。

---

> ？你要怎么证明作者是你？

对社区用户稍微友好一点，别一上来就一股质问的语气，即使人家确实有不懂的做错了的地方……

**Comment by allMagicNB** [comment]
> > B7E3-7CDE-B86A-1270
> 
> 这不是你的 Issue，如果你有已打上 `Bug` `完成` 标签的 Issue 请去到那条 Issue 发你的识别码。
> 
> ---
> 
> > ？你要怎么证明作者是你？
> 
> 对社区用户稍微友好一点，别一上来就一股质问的语气，即使人家确实有不懂的做错了的地方……
> 

？我怎么你了？

**Comment by allMagicNB** [comment]
> 你的确有股讽刺的语气在里面…… 

请不要过度理解谢谢

> 显然别人没有恶意，就算是恶意也不会来这里只评论个识别码……

是没有恶意，是不叫恶意，如果这个 Issue 确实是他的，那是正常行为，但是我让他证明，那句话就不知道为什么被过度理解了。

**Comment by Chiloven945** [comment]
> 请不要过度理解谢谢
> 是没有恶意，是不叫恶意，如果这个 Issue 确实是他的，那是正常行为，但是我让他证明，那句话就不知道为什么被过度理解了。

从事实进行分析：对于”如何证明这是你的“这一点，很明显地能够看出来这是一个不必要且冗余的问题。首先，如果仔细浏览了这个issue，那么完全可以发现issue汇报者并非评论者，故而推断为讽刺；其次，就算的确没有任何嘲讽及恶意于其中，这也不是一个妥善的回复语气。因而判断应该做的正确行为为以陈述的语气回答。

**Comment by allMagicNB** [comment]
> 首先，如果仔细浏览了这个issue，那么完全可以发现issue汇报者并非评论者，故而推断为讽刺

那么，为什么肯定不是？我原来的号被封了，我原来的号注销了，为什么不可能？

> 其次，就算的确没有任何嘲讽及恶意于其中，这也不是一个妥善的回复语气。因而判断应该做的正确行为为以陈述的语气回答。

基于上面，我只是询问。

**Comment by WForst-Breeze** [comment]
请保持冷静，停止讨论无关内容，谢谢各位 🙏🏻

**Comment by sulingjiang** [comment]
> B7E3-7CDE-B86A-1270

我们无法确定这个 Issue 所有权是否归您，所以这边是没办法解锁的，抱歉

**Comment by sulingjiang** [comment]
> B7E3-7CDE-B86A-1270

我们无法确定这个 Issue 所有权是否归您，所以这边是没办法解锁的，抱歉

**Comment by sulingjiang** [comment]
>如果仔细浏览了这个issue，那么完全可以发现issue汇报者并非评论者，故而推断为讽刺；

温馨提示：ghost 是已注销用户

**Comment by TaiMiao** [comment]
这个注销的账号就是我的账号，以下是我能找到的所有证据![Screenshot_2024-08-08-15-15-15-107_com.netease.mobimail.png](https://github.com/user-attachments/assets/5d4639d0-9eec-48f3-a7bd-4acec06fdf95)

![Screenshot_2024-08-08-15-14-34-758_com.netease.mobimail.png](https://github.com/user-attachments/assets/aaa87070-872e-4785-8054-d0d34326b85f)

![Screenshot_2024-08-08-15-12-37-800_com.netease.mobimail.png](https://github.com/user-attachments/assets/58517da4-e925-409d-85b5-92894aedf108)

**Comment by LTCatt** [comment]
你的解锁码：AK9EvGKKzKtWva5SJc5LcrdlA8hDbBGQ
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
