### ISSUE TITLE
[BUG]部分版本的Forge启动时无法正确识别Java

### ISSUE THREAD

**Issue by SALTWOOD** [Hex-Dragon/PCL2#2233]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在启动部分版本Forge的情况下(例如1.16.5,Forge36.2.20)，这些forge版本只能使用较旧的Java8启动，但是启动器自动选择Java即使已经安装Java8（较新版的）也会提示“未找到Java”而不是提示“Java兼容性警告”

只有在强制指定版本Java时才会提示提示“Java兼容性警告”

长话短说：将不兼容的Java当作未安装Java处理并弹窗。
期望的修复：在启动游戏时的弹窗应为“Java兼容性警告”而不是“未找到Java”弹窗。

### 重现步骤

1、启动游戏（此处以Create：Above and Beyond整合包举例，因为此bug在启动该整合包时发现；使用Forge36.2.20也能复现）
2、提示“未找到Java”，取消游戏启动。
3、打开版本设置->设置，指定JRE8 (8.0.361)
4、提示“Java兼容性警告”，复现成功

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12025370/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12025371/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12025372/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12025367/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12025369/Log5.txt)

**Comment by SALTWOOD** [comment]
注：此Issue有别于#2194。因为#2194的问题是启动1.12.2时自动选择了Java17，而本Issue的问题是启动部分版本Forge时将“不兼容的Java”当作“未安装Java”处理并弹窗。

**Comment by youzi-2333** [comment]
不太确定是不是重复。
先让龙猫看看吧.jpg

**Comment by LTCatt** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/f8b8f1ef-cee0-4d85-a122-b89fd827ae20)
已确认

**Comment by SALTWOOD** [comment]
这能算活跃橙吗*
B38F-03D9-C7ED-DD1B
谢谢（

**Comment by LTCatt** [comment]
你的解锁码：Nm6279UD88J2RXfJ9x2H4qqemA/r3HBs
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by SALTWOOD** [comment]
电脑主板换了，最近还有几次硬件升级，PCL2现在数据重置了（但这次换的是主板，估计后面不会变了）
再求一次活跃橙
44B0-8452-17A5-D9DA

**Comment by LTCatt** [comment]
你的解锁码：N53ipvSp0LftPfGlaM0ROCnVfeYB5bbs
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
