### ISSUE TITLE
正版登录皮肤无法更换

### ISSUE THREAD

**Issue by zolara** [Hex-Dragon/PCL2#2234]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

使用正版登陆方式，已在官网换过皮肤，并且挂了代理，进入游戏后仍然是默认皮肤，各个版本均有此问题。

### 重现步骤

无特殊步骤

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12025670/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12025672/Log2.txt)

**Comment by zkitefly** [comment]
重启启动器，然后在账户头像点刷新，然后再试试？

**Comment by WForst-Breeze** [comment]
等待一段时间后再试

**Comment by biancqy** [comment]
+1

**Comment by rechalow** [comment]
正版皮肤是根据启动时UUID进行计算的，MC会从官网上通过你的UUID来Get到你的皮肤数据，因此几乎不存在是启动器的问题。如果你出现了未修改皮肤的情况，应该是官网未刷新成功。

**Comment by mogorou** [comment]
如果您的游戏版本在1.19及以上，请尝试用官方启动器来更改皮肤。我也遇到这种情况，却不知道是怎么回事，但我用官启修改皮肤后是正常的。

**Comment by SALTWOOD** [comment]
请尝试刷新缓存，并尝试重新登陆
也许有用

**Comment by WorldHim** [comment]
离线服无效。
