### ISSUE TITLE
curseforge整合包安装会缺少mod

### ISSUE THREAD

**Issue by xumcdgg** [Hex-Dragon/PCL2#2241]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

安装curseforge时，安装完成后的游戏版本会1缺少整合包内原有的bug。我现在的版本是快照2.6.3版本

### 重现步骤

将下好的curseforge整合包拖入启动器窗口

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12040188/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12040189/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12040190/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12040191/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12040192/Log1.txt)

**Comment by WForst-Breeze** [comment]
麻烦补充整合包文件，谢谢！

**Comment by LTCatt** [comment]
应该是 #2199 导致，下个版本更新之后如果还这样再说吧
