### ISSUE TITLE
支持 NeoForge 的下载和安装

### ISSUE THREAD

**Issue by xphost008** [Hex-Dragon/PCL2#2244]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

请添加新版的forge下载链接：https://maven.neoforged.net/#/releases/net/neoforged/forge/
最近不是Lex和团队决裂了嘛，因此files.minecraftforge.net这个网址已经是名副其实的废弃了。
上述下载链接为最新版的Forge下载链接，里面不仅有installer，还有universal。
目前【2023/7/14 11:00】，其最新版本号为47.1.8版本。

请尝试将其添加到PCL下载中！非常感谢！

如果可以的话，您可以选择尝试【不需要forge-installer-bootstrapper】来下载forge试试的！（说笑的，不说了……）

### 原因

【目前来说】没有多少人需要这个东西，但假如在不久的将来Mojang更新了新的正式版本，而files.minecraftforge.net没有更新，那我可不知道怎么硕了捏！

**Comment by rechalow** [comment]
https://neoforged.net/
这是新forge的博客地址，，

**Comment by Big-Cake-jpg** [comment]
暂无国内镜像源，可能需要联系 bangbang93 添加镜像。

已确认，感谢您的反馈。

**Comment by rechalow** [comment]
刚刚又一次看了files.minecraftforge.net的官网，它也更新了47.1.8，只是……
你会发现两者的changelog居然不一样！这说明他们还是不同的分支情况的！

**Comment by LTCatt** [comment]
先多等等看看情况.jpg

**Comment by RawDiamondMC** [comment]
建议把标题中的“最新版Forge”替换为“NeoForge”
这个是已经确定的名称

**Comment by rechalow** [comment]
> 建议把标题中的“最新版Forge”替换为“NeoForge” 这个是已经确定的名称
已修改

**Comment by zkitefly** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/64117916/dada7772-04b4-4d23-bc5e-cc470bf9a497)
?

**Comment by rechalow** [comment]
> ![image](https://user-images.githubusercontent.com/64117916/256981340-dada7772-04b4-4d23-bc5e-cc470bf9a497.png) ?

[见此](https://www.mcbbs.net/thread-1456936-1-1.html)

**Comment by rechalow** [comment]
如果可以的话，您可以将其放在讨论里面。

**Comment by LTCatt** [comment]
坦白的说，启动器不可能这么快支持 NeoForge。
首先，它没有官方的 API。
而目前 Forge 的官方源是直接正则网页内容的，但一个新项目的官网随时可能修改，所以即使用正则匹配来实现”官方源“，它也非常、非常不稳定。
其次，在这时候，还需要等待 BMCLAPI 实现它的对应 API，否则国内的下载依然很成问题。
这些原因综合起来，这玩意儿不太可能在最近一两个月内部署上就。多等等吧。

**Comment by got991** [comment]
官方api:     GET
https://maven.neoforged.net/api/maven/latest/version/releases/net%2Fneoforged%2Fforge?filter={version}
格式:     
{"isSnapshot":false,"version":"1.20.1-47.1.70"}
下载：https://maven.neoforged.net/release/net/neoforged/forge/{version} 或 https://maven.neoforged.net/snapshot/net/neoforged/forge/{version}

**Comment by LTCatt** [comment]
@bangbang93 看看多久能折腾上 BMCLAPI？

**Comment by bangbang93** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/3430784/b5b6b078-01cd-48c8-9095-2ece5d4f161e)
BakaXL也来催我了，最快这个月上线吧

**Comment by zkitefly** [comment]
> ![image](https://github.com/Hex-Dragon/PCL2/assets/3430784/b5b6b078-01cd-48c8-9095-2ece5d4f161e)
> BakaXL也来催我了，最快这个月上线吧

顺便把 quilt 加上呗 qwq

**Comment by bangbang93** [comment]
> > ![image](https://user-images.githubusercontent.com/3430784/261220682-b5b6b078-01cd-48c8-9095-2ece5d4f161e.png)
> > BakaXL也来催我了，最快这个月上线吧
> 
> 顺便把 quilt 加上呗 qwq
quilt的同步比neoforge复杂一点，先把neoforge搓了

**Comment by bangbang93** [comment]
已上线 <https://bmclapidoc.bangbang93.com/#api-Neoforge>

**Comment by RawDiamondMC** [comment]
> 已上线 https://bmclapidoc.bangbang93.com/#api-Neoforge

好耶

**Comment by rechalow** [comment]
> 已上线 https://bmclapidoc.bangbang93.com/#api-Neoforge

好耶好耶，希望PCL2尽快接入啦！！

**Comment by got991** [comment]
yes!

**Comment by LTCatt** [comment]
等 BMCLAPI 支持 Quilt 之后和 Quilt 支持一起做 =。=

**Comment by z0z0r4** [comment]
等 quilt 可有的好等了

**Comment by burningtnt** [comment]
目前 NeoForge Installer 与原 Forge 几乎一模一样，但可通过读取 !/META-INF/NEOFORGE.SF 来区分

此外，NeoForge 计划于 1.20.2 版本发布时更改 Installer 逻辑，**可能**不再能与原 Forge Installer 兼容

来源：NeoForge Discord
![image](https://github.com/Hex-Dragon/PCL2/assets/88144530/ef34a1fc-f038-4f67-af55-6d8c25035cf2)

**Comment by z0z0r4** [comment]
> 目前 NeoForge Installer 与原 Forge 几乎一模一样，但可通过读取 !/META-INF/NEOFORGE.SF 来区分
> 
> 此外，NeoForge 计划于 1.20.2 版本发布时更改 Installer 逻辑，**可能**不再能与原 Forge Installer 兼容
> 
> 来源：NeoForge Discord
> ![image](https://github.com/Hex-Dragon/PCL2/assets/88144530/ef34a1fc-f038-4f67-af55-6d8c25035cf2)
> 

草了，等爆

**Comment by got991** [comment]
Hmmp
还得等quilt...

**Comment by zkitefly** [comment]
NeoForge 20.2 改变了版本号规则，会炸（

![image](https://github.com/Hex-Dragon/PCL2/assets/64117916/b5f12b71-7e81-4b44-9d3b-224a5eb3542d)

**Comment by RawDiamondMC** [comment]
> NeoForge 20.2 改变了版本号规则，会炸（
> 
> ![image](https://user-images.githubusercontent.com/64117916/280434733-b5f12b71-7e81-4b44-9d3b-224a5eb3542d.png)

个人认为，Neo应该提早做了...

**Comment by allMagicNB** [comment]
> > ![image](https://user-images.githubusercontent.com/64117916/256981340-dada7772-04b4-4d23-bc5e-cc470bf9a497.png) ?
> 
> [见此](https://www.mcbbs.net/thread-1456936-1-1.html)

NeoForged是项目名，NeoForge是这个项目的产物

**Comment by iPodtouch6557** [comment]
请把鸽子捉回来

**Comment by HowardZHY** [comment]
都9个月了，还不支持，整合包还无法安装

**Comment by JingHai-Lingyun** [comment]
@LTCatt 考虑先给 NeoForge 做一下？Quilt 那边……

**Comment by wuliaodexiaoluo** [comment]
qulit什么时候能上线。。。。

**Comment by deep-dark-forest** [comment]
> qulit什么时候能上线。。。。

额![Screenshot_20240314_184129.jpg](https://github.com/Hex-Dragon/PCL2/assets/131975043/9bccf24d-19c4-4bee-88f8-46e084b876f7)

**Comment by zkitefly** [comment]
93 哥说 quilt 那边的问题不解决就搞不了

**Comment by wuliaodexiaoluo** [comment]
建议要不然先不等了？
不然等到 Quilt API Fix 掉这个问题，可能 Minecraft 已经更新到 1.23 了。。。
到时候 新版本就没有 Forge 可以用了

**Comment by rumengchuxing062** [comment]
所以 quilt api那边到底什么bug
要不neoforge先做了再说

**Comment by wuliaodexiaoluo** [comment]
> @bangbang93 93哥现在搞好了吗？

好不了一点，因为 Qulit API 的 Bug 貌似还没 Fix 。另外请不要随便 @ 93哥

**Comment by HowardZHY** [comment]
先崩管quilt了，neoforge的优先级应该是最首要的

**Comment by PaintNinja** [comment]
您好，我是 MinecraftForge 团队的成员。我想澄清一些事情。

NeoForge 并非 Forge 的重命名。它是一个独立的项目，在较新版本中与 Forge mods 不兼容。如果您想支持 NeoForge，请将其作为一个选项，而不是 Forge 的替代品。

Forge 并没有被放弃。我们将继续发布现有版本的更新，并快速添加对新版本 Minecraft 的支持。

(抱歉有语法错误，我不会说中文，所以用了翻译器）

**Comment by PaintNinja** [comment]
If that is the case, I apologise for the confusion. Must've been a translation error or misunderstanding on my part

**Comment by JingHai-Lingyun** [comment]
no problem

**Comment by allMagicNB** [comment]
> If that is the case, I apologise for the confusion. Must've been a translation error or misunderstanding on my part

There is indeed ambiguity in the expression of the author of this issue, but what we will discuss later is to add rather than replace :)

**Comment by zkitefly** [comment]
楼主写的是把 NeoForge 看成是新 Forge，Forge 停更

确实表达有误

这里是单纯加入 NeoForge 的支持，不会视为 Forge 的新版本

**Comment by wuliaodexiaoluo** [comment]
> 您好，我是 MinecraftForge 团队的成员。我想澄清一些事情。
> 
> NeoForge 并非 Forge 的重命名。它是一个独立的项目，与新版本 Forge 的内容不兼容。如果你想支持 NeoForge，请将其作为一个选项，但不要移除 Forge。
> 
> Forge 并没有被放弃。我们将继续发布现有版本的更新，并快速添加对新版本 Minecraft 的支持。
> 
> (抱歉有语法错误，我不会说中文，所以用了翻译器）

I'm still wondering why 1.20.4 still has Forge
Why minecraftforge have not a api?
The official source used now is the regular website content, and it is possible that one day yours change the official website, and then the regular explodes

**Comment by rechalow** [comment]
> > 您好，我是 MinecraftForge 团队的成员。我想澄清一些事情。
> > NeoForge 并非 Forge 的重命名。它是一个独立的项目，与新版本 Forge 的内容不兼容。如果你想支持 NeoForge，请将其作为一个选项，但不要移除 Forge。
> > Forge 并没有被放弃。我们将继续发布现有版本的更新，并快速添加对新版本 Minecraft 的支持。
> > (抱歉有语法错误，我不会说中文，所以用了翻译器）
> 
> I'm still wondering why 1.20.4 still has Forge Why minecraftforge have not a api? The official source used now is the regular website content, and it is possible that one day yours change the official website, and then the regular explodes

正常的Forge一直都很反对第三方启动器自动安装Forge的好吧……
现在是NeoForge主动《想》开API给第三方启动器接入，而不是Forge
你要这么想好像也没错……

**Comment by burningtnt** [comment]
> If that is the case, I apologise for the confusion. Must've been a translation error or misunderstanding on my part

Actually, in some of the players' mind, They do consider NeoForge an alternative of Forge. We are still trying our best to change their incorrect mind.

By the way, most of the collaborator of the PCL2 project could understand English. Feel free to speak it as it could express your thought much more clearly :)

**Comment by HowardZHY** [comment]
还推迟，优先级应该是尽可能快的

**Comment by allMagicNB** [comment]
> 还推迟，优先级应该是尽可能快的 

目前最主要的事情是修 Bug，更何况这只是**支持下载**，如果你想使用的话可以直接去官网下载 Jar 文件进行安装，PCL 可以识别到它的……

**Comment by SALTWOOD** [comment]
目前的 OpenBMCLAPI 中已经有了 NeoForge 的文件，建议先加进去支持

Quilt 的话，那边的 API 确实有问题（已证实），我去 OpenBMCLAPI群里问了也是得到了肯定的答复（至少我的 OpenBMCLAPI 节点没发现有同步 Quilt 的文件）

另外，93 也要上班的，况且 MCBBS 也早炸了，OpenBMCLAPI 每天都90%多的负载，也请不要再催了

**Comment by Tianpao512** [comment]
隔壁的HMCL已经支持Neoforge了 可以参考一下代码

**Comment by allMagicNB** [comment]
> 隔壁的HMCL已经支持Neoforge了 可以参考一下代码

别水贴

**Comment by Pigeon0v0** [comment]
#4045 Done

**Comment by xphost008** [comment]
2E97-2E0C-4038-BE81
thanks！

**Comment by LTCatt** [comment]
[新功能] 类不会解锁活跃橙，抱歉（
