### ISSUE TITLE
JVM虚拟机参数选项(将参数添加在"XXX\XXX\java.exe"后面)

### ISSUE THREAD

**Issue by IamSGZhenYun** [Hex-Dragon/PCL2#2247]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

现在JVM参数只能加载头和最尾巴上，建议加入添加到"XXX\XXX\java.exe"后面
例如:"C:\\Program Files\\Java\\jre-1.8\\bin\\java.exe" -参数

### 原因

玩某些服务器需要配置特定的AuthlibInjector，这个东西通常需要被配置在JVM参数中，但是我尝试了添加在JVM参数头，发现游戏无法启动。又尝试添加在参数尾，发现没有生效。导出启动脚本后将参数添加在"XXX\XXX\java.exe"后就生效了。

**Comment by LTCatt** [comment]
位置加错了，这是个 bug

**Comment by IamSGZhenYun** [comment]
啊原来是bug吗？（所以是不是有活跃橙了

**Comment by iPodtouch6557** [comment]
> 啊原来是bug吗？（所以是不是有活跃橙

是的，只要龙猫以bug的名义修复了该issue（就是说只要这个issue同时含有 bug 和 完成 两个label，就能拿活跃橙）
但是它还没被处理完，所以现在发解锁码没有用滴

**Comment by IamSGZhenYun** [comment]
好了已完成了可以解锁活跃橙了罢（
0964-D37B-36C9-CB37

**Comment by LTCatt** [comment]
你的解锁码：ty9tIF62Z8dRf91pGy/NHvkAMs0kt3h5
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
