### ISSUE TITLE
微软登录使用系统浏览器登录功能网址错误

### ISSUE THREAD

**Issue by fhh1224** [Hex-Dragon/PCL2#2248]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

系统浏览器登录时没有见到启动器提示的链接格式，"code=XXXX"在官网中变成“client_id=XXXX”

### 重现步骤

选择使用正版登录
点击使用系统浏览器登录
填写空白页链接

### 日志与附件

![image](https://github.com/Hex-Dragon/PCL2/assets/99572573/5acfca2a-5450-4306-9d15-6095325a6ec3)

**Comment by youzi-2333** [comment]
虽然我没有买过正版，但是我用自己的微软账号登录，没这个问题……
请在登录步骤完成后，等待网页变为空白，然后再把地址栏的网址复制到框中。

**Comment by zkitefly** [comment]
试试在浏览器的无痕模式登录看看

**Comment by LTCatt** [comment]
你这是卡了，登录网页加载不出来
