### ISSUE TITLE
1.16.5下载安装forge36.2.39下载安装失败

### ISSUE THREAD

**Issue by yruh** [Hex-Dragon/PCL2#2249]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

下载 Forge 36.2.39失败
→ 安装 Mod 加载器（方式 A）失败
→ 安装新 Forge 版本失败
→ Forge 安装器出错，日志结束部分为：
Caused by: java.lang.ClassNotFoundException: java.sql.Time
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 14 more
   在 PCL.ModDownloadLib._Closure$__37-0._Lambda$__7(LoaderTask`2 Task)
   在 PCL.ModLoader.LoaderTask`2._Closure$__12-0._Lambda$__0()
   在 PCL.ModDownloadLib.ForgeInjector(String Target, LoaderTask`2 Task, String McFolder)
   在 PCL.ModDownloadLib._Closure$__37-0._Lambda$__7(LoaderTask`2 Task)

### 重现步骤

1、点击1.16.5
2、往下滚，然后点击安装Forge36.2.39
3.安装

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12049410/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12049411/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12049412/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12049413/Log4.txt)

**Comment by youzi-2333** [comment]
```
[18:23:41.117] [Download] ForgeInstall-36.2.39_74096 1049#：出错，基础连接已经关闭: 发送时发生错误。
你的网络环境不佳，导致难以连接到服务器。请检查网络，多重试几次，或尝试使用 VPN。
————————————
详细错误信息：
→ 由于远程方已关闭传输流，身份验证失败。
   在 PCL.ModNet.NetFile.Thread(NetThread Info)
错误类型：System.IO.IOException
```
大概率是你的网络问题……
把网线插好（或者检查 WiFi 连接是否稳定）再试？

**Comment by yruh** [comment]
https://github.com/Hex-Dragon/PCL2/assets/81079318/57b14577-20b3-43f1-8354-ec738517312f


https://github.com/Hex-Dragon/PCL2/assets/81079318/56dcb7ed-fd79-4b02-b410-a9f231c1e686

![QQ截图20230714211430](https://github.com/Hex-Dragon/PCL2/assets/81079318/6043ce1e-ae0b-4521-b1a5-5b977cbcf5be)
我我现在只要是安装1.1 2.2以上的Forge就百分百失败挂VPN也不可以，其他启动器就可以成功

**Comment by yruh** [comment]
识别码：AC81-DCD3-373D-1AC2

**Comment by LTCatt** [comment]
你的解锁码：/SWPPhTe++eYKukQSzmPDvx//kJ4vR/6
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
