### ISSUE TITLE
[优化] 在下载页面添加“找不到版本”的帮助按钮

### ISSUE THREAD

**Issue by youzi-2333** [Hex-Dragon/PCL2#2250]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在自动安装页面的合适位置，添加一个无边框按钮（文本类似“找不到游戏版本？”），点击后弹出弹窗，内容类似“请选择需要安装的 Minecraft”，按钮如下：

1. `Java 版`，点击后自动将下载源改为官方，然后刷新版本列表；
2. `其他版本`，点击后弹出新弹窗，说明无法安装；
3. `取消`。

### 原因

这样可以方便用户快速确定该问题的原因，并方便自行排查。

**Comment by Bandysol** [comment]
我看了N遍都没看懂你想表达什么
自动安装里的版本为什么会有 找不到游戏版本 的提示啊？我是没遇到过

**Comment by youzi-2333** [comment]
谁跟你说过这里面已经有这个东西了……
有了我还交毛线反馈……
搞不懂.jpg

**Comment by Bandysol** [comment]
是为了 因为使用镜像源而没有最新版本 和 想要玩基岩版 的情况做提示是吧，我懂了

**Comment by WorldHim** [comment]
意为：优化下载逻辑，在镜像源没有所需版本时，让用户选择更换为官方源；当所需版本非启动器支持版本时，提示用户无法安装。

**Comment by youzi-2333** [comment]
…我讲的够清楚了吧（
我的意思是说，例如麻将更新了 1.21 版本，然后玩家得知之后，非常高兴，打开下载页面，结果发现没有 1.21，这时候就会有一批玩家过来交 Issue；如果玩家想要白嫖基岩版，然后下了个 PCL，但是发现没有基岩版，也有可能过来交 Issue。这两个问题同为“找不到游戏版本”，如果在下载页面加一个按钮，那么玩家就可以点击该按钮以解决问题，具体这个按钮的逻辑我就写在上面……

**Comment by iPodtouch6557** [comment]
或者……直接声明一下，没有基岩版；以及在使用镜像源时提示更新可能不同步

**Comment by LTCatt** [comment]
目前的默认下载源设置是 `当官方源缓慢时切到镜像源` ，所以如果因为是镜像源而找不到新版本，一定是下列两种情况之一：
· 当前网络连接官方源非常缓慢，所以自动切了镜像源
· 玩家自己修改了设置，优先使用镜像源
在这两种情况下，似乎都没有什么必要做出额外处理……
至于基岩版……这个常识问题懒得折腾了……
