### ISSUE TITLE
在版本设置中添加不更改游戏窗口标题的选项

### ISSUE THREAD

**Issue by daniqwq233** [Hex-Dragon/PCL2#2252]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

添加一个选项可以在版本设置中选择不修改游戏窗口标题

### 原因

目前最新版本启动器只能在全局模式下留空游戏窗口标题选项来不更改游戏窗口标题，在版本设置中的游戏窗口标题选项下留空则会使用全局设置，而当大部分版本需要修改而只有一个版本无需修改时没有办法单独禁用一个版本的游戏窗口标题修改。所以建议添加一个选项可以在版本设置中选择不修改游戏窗口标题。目前最新版本启动器只能在全局模式下留空游戏窗口标题选项来不更改游戏窗口标题，在版本设置中的游戏窗口标题选项下留空则会使用全局设置，而当大部分版本需要修改而只有一个版本无需修改时没有办法单独禁用一个版本的游戏窗口标题修改。所以建议添加一个选项可以在版本设置中选择不修改游戏窗口标题。

**Comment by LTCatt** [comment]
感觉所说情况的适用范围很窄，“当大部分版本需要修改而只有一个版本无需修改” 的话给那个版本单独改成 MC 原始标题也行……？
