### ISSUE TITLE
启动器图标会被认为是未响应

### ISSUE THREAD

**Issue by TuanZiGit** [Hex-Dragon/PCL2#2254]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在个性化中启用PCL启动图标，在启动过程中多点几下图标就会发现——白啦！寄啦！未响应啦！然后正常启动……

### 重现步骤

如上

### 日志与附件

wtf，没记录

**Comment by WorldHim** [comment]
无法复现，请上传log。建议再上传bug录屏。

**Comment by Bandysol** [comment]
你电脑太卡了吧

**Comment by hejiehao** [comment]
拿一个内存4GB的老电脑可能复现这个问题

**Comment by LTCatt** [comment]
这个我没法修……
