### ISSUE TITLE
自动安装/版本选择搜索支持

### ISSUE THREAD

**Issue by dannisyang53** [Hex-Dragon/PCL2#2257]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

在`下载`>`自动安装`页面和`版本选择`页面顶部添加一个`搜索栏`，用于搜索特定版本

### 原因

我需要这个功能来搜索特定版本。
- 很多人都有下载特定版本的需求，有些 Mod 、资源包、数据包仅支持特定版本，如果没有这个功能，下载特定版本会变得比较麻烦。
- 很多人可能安装了很多版本，如果没有这个功能，选择特定版本会变得比较困难。

**Comment by SALTWOOD** [comment]
支持，有同样的需求

**Comment by dannisyang53** [comment]
> 支持，有同样的需求。 但是除非快照版否则我认为直接翻比打字搜快 倒是可以在版本选择加一个（？

确实，要不我再加一个（？

**Comment by LTCatt** [comment]
#548 #838
