### ISSUE TITLE
自定义下载进度条与文件下载进度不同

### ISSUE THREAD

**Issue by XueQian17654** [Hex-Dragon/PCL2#2259]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/Hex-Dragon/PCL2/assets/137385975/f5839f20-40fd-4ddc-85bb-40de2505ce1a)

### 重现步骤

1、多次启动自定义下载

### 日志与附件

None

**Comment by SALTWOOD** [comment]
已经是bug了，在修
