### ISSUE TITLE
隐藏主题功能缺陷

### ISSUE THREAD

**Issue by dsz1714** [Hex-Dragon/PCL2#226]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

更新PCL2之后，解锁的隐藏主题被重置。

### 重现步骤

任何时候重启/更新后都可能出现。（在同一设备上，没有删除任何PCL2文件）

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/9791672/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/9791674/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/9791675/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/9791676/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/9791677/Log5.txt)

**Comment by LTCatt** [comment]
检查注册表是否被其他软件清理，或者系统是否有还原功能
