### ISSUE TITLE
修改游戏窗口标题功能不起作用

### ISSUE THREAD

**Issue by NorLorikein** [Hex-Dragon/PCL2#2260]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

版本 : 1.20.1 , Fabric 0.14.21
PCL2 启动选项中 游戏窗口标题功能无效
在游戏启动后还是原版的标题
已经确认PCL2在游戏启动后还在后台稳定运行
并且安装的mod中没有修改标题的功能
我尝试将标题修改为最简单的123，也是不起作用的

### 重现步骤

1、点击设置
2、启动选项 将游戏窗口标题设置为123
3、启动游戏，发现窗口标题还是为原版标题

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12063265/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12063266/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12063267/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12063268/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12063269/Log1.txt)

**Comment by iPodtouch6557** [comment]
好像是因为1.19以上的版本会自己强行修改窗口标题……会导致抽风
记得是重复了

**Comment by LTCatt** [comment]
#1976 
Mod 可能**被动地**导致标题被反复修改，这是 MC 的一个 Bug
