### ISSUE TITLE
格式化 json对象失败

### ISSUE THREAD

**Issue by Faraday512** [Hex-Dragon/PCL2#2261]
### 检查项

- [x] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在启动、下载、登录、帮助页面全部都出现格式化json对象失败的问题

### 重现步骤

启动就会触发

点击登录时触发

点击下载 获取版本列表时触发

点击更多 触发很多这样的弹窗

### 日志与附件

[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12063294/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12063295/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12063296/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12063297/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12063298/Log3.txt)

**Comment by LTCatt** [comment]
我怀疑是系统环境问题，这个代码不是 PCL 的部分报的错，我没法修 :/
