### ISSUE TITLE
可通过将mp3拖入pcl2内来播放或者存入pcl2/musics文件夹中

### ISSUE THREAD

**Issue by pangzong2011** [Hex-Dragon/PCL2#2262]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

可以将MP3文件拖入pcl2中后自动播放该音乐或者存入music文件夹中或者存入且立即播放

### 原因

更便捷

**Comment by SALTWOOD** [comment]
首先，这个功能可以有，但是：
1.龙猫忙于别的，可能会拒绝/放弃
2.这个功能用的时候很有用似的，但是正常很少用到（就我而言）

**Comment by LTCatt** [comment]
不太常用的排到低优先级估计也没空做……先关了吧，抱歉 orz
