### ISSUE TITLE
游戏崩溃时检测路径是否存在中文

### ISSUE THREAD

**Issue by abc15616545561** [Hex-Dragon/PCL2#2265]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

有些人习惯用中文的方法去命名游戏、版本、Java的文件夹结果就是可能会这样:
[Render thread/INFO]: [STDERR]: Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: Failed to locate library: lwjgl.dll [in thread "Render thread"]
所以建议在游戏崩溃时去检测是否存在中文路径并弹出提醒框

### 原因

这样可以方便节约所有人的时间

**Comment by youzi-2333** [comment]
umm 不应该啊，我的游戏命名很多都是中文，没这个问题……
#416 应该修好了，请检查 PCL 版本是否为最新版

**Comment by LTCatt** [comment]
更新 PCL，再次启动，上传具体的错误报告

**Comment by abc15616545561** [comment]
已解决，群友快照版PCL2非最新版
