### ISSUE TITLE
头像显示空白

### ISSUE THREAD

**Issue by xxxfhy** [Hex-Dragon/PCL2#2272]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

头像显示空白，在调试模式下刷新显示加载位图失败，参数无效，最后却提示已成功刷新头像，且有小概率能成功刷新。

### 重现步骤

右键刷新头像

### 日志与附件

[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12067527/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12067528/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12067529/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12067530/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12067531/Log4.txt)

**Comment by zkitefly** [comment]
网络问题

https://api.mojang.com/users/profiles/minecraft/xxxfhy

你试试你能访问这个链接吗↑

**Comment by xxxfhy** [comment]
可以直连
{
    "id": "019b28e36e8a46a0bfae89c61f3e7e04",
    "name": "xxxfhy"
}
但是有时出现：
![Snipaste_2023-07-17_18-42-07](https://github.com/Hex-Dragon/PCL2/assets/40598925/5b21f5eb-1893-4cf0-943b-c185a987f2f7)

---
另：信息的显示补全

**Comment by xxxfhy** [comment]
附上参数无效图
![image](https://github.com/Hex-Dragon/PCL2/assets/40598925/ceede339-0375-4fa8-865d-2b84597ea0f7)
