### ISSUE TITLE
建议添加“战斗更新”的快照

### ISSUE THREAD

**Issue by Mcenahle** [Hex-Dragon/PCL2#2275]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在“版本下载列表”添加“战斗更新”的快照。

### 原因

这项优化可以让玩家们获取“战斗更新”的快照。

**Comment by zkitefly** [comment]
有资源吗

**Comment by Mcenahle** [comment]
> 有资源吗？（version json 和 version jar）
> 
> 我记得 愚人节版本 一栏有吗？

愚人节版本 一栏没有”战斗更新“内容。
下面是我收集到的文件。
[json.zip](https://github.com/Hex-Dragon/PCL2/files/12070111/json.zip)
jar文件压缩包下载地址：https://windowsuseful.lanzoul.com/iR3CX12rzk9a

**Comment by SALTWOOD** [comment]
可以有
但资源难找

**Comment by LTCatt** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/6dac83ea-847c-483a-a51f-a7e81d980d65)

**Comment by iPodtouch6557** [comment]
所以是没有人发现这个版本吗……大家的样子咋都是在探讨如何下载的问题（

**Comment by SALTWOOD** [comment]
但是为什么没有Combat Test 7呢

**Comment by Mcenahle** [comment]
> 但是为什么没有Combat Test 7呢

Combat Test 7、Combat Test 7b是秘密发布的版本，
Combat Test 7 json文件下载地址：https://piston-data.mojang.com/v1/objects/3ad450f458149702ec3dd7655af44ab422a83e72/client.jar
Combat Test 7b json文件下载地址：https://archive.org/download/Combat_Test_7ab/1_16_combat-2.zip
Combat Test 7c json文件下载地址：https://piston-data.mojang.com/experiments/combat/2557b99d95588505e988886220779087d7d6b1e9/1_16_combat-3.zip

**Comment by LTCatt** [comment]
有 7c 就够了 =。=
