### ISSUE TITLE
自定义主页（联网更新）支持多个主页

### ISSUE THREAD

**Issue by l1294966922** [Hex-Dragon/PCL2#2276]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

自定义主页联网更新可以输入多个链接，然后多个主页列下来一起显示（如果本地主页也能一起显示就更好了）。
或者本地自定义主页添加事件实现直接显示链接中的主页功能，再或者方便的切换主页功能

### 原因

这个功能对我们这种找到多个喜欢的主页的人很友好，而且目测实现难度不大（应该吧，如果大的话当我没说qwq）

**Comment by SALTWOOD** [comment]
没必要
盲猜忽略/拒绝

**Comment by LTCatt** [comment]
之后会考虑做一个默认联网主页列表的，现在还是算了……
