### ISSUE TITLE
搜索MOD时在搜索框输入带有Better的MOD名称会搜到其他名字带有Better的MOD(没有自己搜索的MOD)

### ISSUE THREAD

**Issue by Jay2353Network** [Hex-Dragon/PCL2#2277]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

搜索MOD时，在搜索框输入带有Better的MOD名称会搜到其他名字带有Better的MOD(没有自己搜索的MOD)

### 重现步骤

1、点击下载。
2、点击MOD。
3、在名称框输入Better XXX。
4、会出现一大堆名称带有Better的MOD。

### 日志与附件

[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12076543/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12076545/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12076547/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12076548/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12076549/Log4.txt)

**Comment by SALTWOOD** [comment]
这不是bug吧，就是这么设计的

**Comment by WorldHim** [comment]
有可能该 mod 在 cf 和 mr 上的名称与你查找的不同？试试更换关键词。
会出现其他含 `Better` 的 mod 应该是正常现象。~~毕竟如果全字匹配可能想搜的反而搜不到~~

**Comment by SALTWOOD** [comment]
搜模组肯定不可能全字匹配吧，搜不到可能是网站的锅

**Comment by LTCatt** [comment]
搜不到是 API 的锅

**Comment by iPodtouch6557** [comment]
可能是搜索逻辑的问题，搜索逻辑应该是……任意匹配？但是前方一致和完全匹配搜索起来挺麻烦的
