### ISSUE TITLE
在被WindowsDefender删除PCL2程序后，无法正确的启动游戏到主界面。

### ISSUE THREAD

**Issue by EssentialCuber** [Hex-Dragon/PCL2#2280]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

**7/17，准备进游戏发现PCL2消失了，咨询群友后发现，可能是被WindowsDefender删除了，恰好头天晚上我删除了火绒，wdf自动开启了 (合理，这很wdf）
重新下载后，发现配置文件似乎有点异常，设置的内容都被重置了，例如版本隔离和默认中文没有打开。
点击进入游戏，发现如下界面**
![image](https://github.com/Hex-Dragon/PCL2/assets/111330534/294e17f7-b642-461d-970a-05d0ad5c56bd)
**遂返回启动器，发现自动进入服务器功能并没有被开启。**
![image](https://github.com/Hex-Dragon/PCL2/assets/111330534/19b3395b-db63-4297-b638-ccd2decda7f6)
**并且，假如有自动重连服务器的mod，那么在此处点击返回服务器列表，游戏会直接退掉，而非返回列表。**
![image](https://github.com/Hex-Dragon/PCL2/assets/111330534/be51a3b1-b0c8-473f-805e-a39886775d44)
**7/18，重新安装了所有的内容，包括新建了一个端，也无济于事。遂放弃，等修复办法。**

### 重现步骤

**复现可能并不容易？尝试卸载火绒然后重启电脑？idk.**

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12082102/Log2.txt)

**Comment by Chiloven945** [comment]
提供一下游戏的log

**Comment by EssentialCuber** [comment]
> 

sure.

[latest.log](https://github.com/Hex-Dragon/PCL2/files/12089493/latest.log)

**Comment by EssentialCuber** [comment]
> 提供一下游戏的log

这是游戏日志.
[latest.log](https://github.com/Hex-Dragon/PCL2/files/12089499/latest.log)

**Comment by bwtx2023** [comment]
更新启动器后再试

**Comment by EssentialCuber** [comment]
> 更新启动器后再试

是最新版本
![image](https://github.com/Hex-Dragon/PCL2/assets/111330534/0de65045-15db-4841-bd79-fcce48fd7a8b)
BTW，将Windows最近的更新卸载掉后，我在wdf的历史记录中找到了这个威胁记录。
![image](https://github.com/Hex-Dragon/PCL2/assets/111330534/0f4d8c1b-ec5b-4985-9084-89064f9a9f8d)
不知为何，我在最新版本的Windows没有查找到这个历史，它就是单纯的移除了软件，但是并没有通知和记录，我认为这同时也是一个wdf的bug。
现在我的问题已经解决，但是我觉得，可能龙猫需要稍微考虑下这种特殊情况？

**Comment by EssentialCuber** [comment]
熬夜失去了脑子！之前测试用的PCL是旧版本，我并没有发现这个问题所在！我是笨蛋！
