### ISSUE TITLE
模组下载的漏洞：容易使游戏崩溃

### ISSUE THREAD

**Issue by BugTD** [Hex-Dragon/PCL2#2282]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

# 模组下载问题
在下载模组时，如果其有支持所以版本的***all***版本，那么pcl将会默认下载该版本。
这将使游戏崩溃。例如Magic lib的最新版本拥有all版本，那么游戏不会打开，而回崩溃输出：
	 - Mod 'MagicLib for 1.14.4' (magiclib-1_14_4) 0.7.346+e235d92-stable requires any 1.14.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	 - Mod 'MagicLib for 1.15.2' (magiclib-1_15_2) 0.7.346+e235d92-stable requires any 1.15.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	 - Mod 'MagicLib for 1.16.5' (magiclib-1_16_5) 0.7.346+e235d92-stable requires any 1.16.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	 - Mod 'MagicLib for 1.17.1' (magiclib-1_17_1) 0.7.346+e235d92-stable requires any 1.17.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	 - Mod 'MagicLib for 1.18.2' (magiclib-1_18_2) 0.7.346+e235d92-stable requires any 1.18.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	 - Mod 'MagicLib for 1.19.2' (magiclib-1_19_2) 0.7.346+e235d92-stable requires version 1.19.2 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	 - Mod 'MagicLib for 1.19.3' (magiclib-1_19_3) 0.7.346+e235d92-stable requires version 1.19.3 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	 - Mod 'MagicLib for 1.19.4' (magiclib-1_19_4) 0.7.346+e235d92-stable requires version 1.19.4 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!

### 重现步骤

1.下载一个最新更新中包含all的模组（例如 Magic lib）
2.启动游戏
3.游戏崩溃
*举例崩溃日志*
	 - Mod 'MagicLib for 1.14.4' (magiclib-1_14_4) 0.7.346+e235d92-stable requires any 1.14.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	 - Mod 'MagicLib for 1.15.2' (magiclib-1_15_2) 0.7.346+e235d92-stable requires any 1.15.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	 - Mod 'MagicLib for 1.16.5' (magiclib-1_16_5) 0.7.346+e235d92-stable requires any 1.16.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	 - Mod 'MagicLib for 1.17.1' (magiclib-1_17_1) 0.7.346+e235d92-stable requires any 1.17.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	 - Mod 'MagicLib for 1.18.2' (magiclib-1_18_2) 0.7.346+e235d92-stable requires any 1.18.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	 - Mod 'MagicLib for 1.19.2' (magiclib-1_19_2) 0.7.346+e235d92-stable requires version 1.19.2 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	 - Mod 'MagicLib for 1.19.3' (magiclib-1_19_3) 0.7.346+e235d92-stable requires version 1.19.3 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	 - Mod 'MagicLib for 1.19.4' (magiclib-1_19_4) 0.7.346+e235d92-stable requires version 1.19.4 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12091094/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12091095/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12091096/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12091097/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12091098/Log1.txt)

**Comment by BugTD** [comment]
建议：官方下载源添加Github，不自动下载带有all字样的jar文件

**Comment by zkitefly** [comment]
> 建议：官方下载源添加Github，不自动下载带有all字样的jar文件

github没好的api，没办法，你有什么方法吗

**Comment by zkitefly** [comment]
> > 建议：官方下载源添加Github，不自动下载带有all字样的jar文件
> 
github的话，你怎么将该模组指引到github仓库，总得有标签把，而且没啥好的 api 用，每个模组都不一样，没办法，你有什么方法吗

**Comment by zkitefly** [comment]
哦还有，这个似乎是这个模组的问题，不是pcl的问题

**Comment by SALTWOOD** [comment]
这个是模组的问题，和PCL无关

**Comment by LTCatt** [comment]
这个是 Mod 自身标注的问题
