### ISSUE TITLE
安装 OptiFine 时选择 Java 8 可能导致安装失败

### ISSUE THREAD

**Issue by HeizeQiuren** [Hex-Dragon/PCL2#2286]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

对于安装OptiFIne：
出错提示：
下载 OptiFine 1.20.1 I5失败
→ 安装 OptiFine（方式 A）失败
→ 安装新版 OptiFine 版本失败
→ 安装器运行出错，末行为 	at oolloo.jlw.Wrapper.main(Wrapper.java:24)
   在 PCL.ModDownloadLib._Closure$__18-0._Lambda$__5(LoaderTask`2 Task)
   在 PCL.ModLoader.LoaderTask`2._Closure$__12-0._Lambda$__0()
   在 PCL.ModDownloadLib.McDownloadOptiFineInstall(String BaseMcFolderHome, String Target, LoaderTask`2 Task)
   在 PCL.ModDownloadLib._Closure$__18-0._Lambda$__5(LoaderTask`2 Task)
在我的世界其他版本以及同一我的世界不同Optifine版本均出现此种情况。

对于启动器备份：
导出启动器注册表后，由于Optifine不能正确安装而尝试删除原启动器，下载新启动器，但是新启动器按理来说只需要替换掉旧启动器一切照旧，但是出现了背景消失、个性化消失、变为锁定状态无法更新快照版PCL等现象，游戏窗口大小等个性化均消失，但游戏路径保存完好。

### 重现步骤

莫名其妙的就出现了安装不上（？
目前使用启动器版本为爱发电最新正式版
旧版本时也出现Optifine安装失败

### 日志与附件

下载 OptiFine 1.20.1 I5失败
→ 安装 OptiFine（方式 A）失败
→ 安装新版 OptiFine 版本失败
→ 安装器运行出错，末行为 	at oolloo.jlw.Wrapper.main(Wrapper.java:24)
   在 PCL.ModDownloadLib._Closure$__18-0._Lambda$__5(LoaderTask`2 Task)
   在 PCL.ModLoader.LoaderTask`2._Closure$__12-0._Lambda$__0()
   在 PCL.ModDownloadLib.McDownloadOptiFineInstall(String BaseMcFolderHome, String Target, LoaderTask`2 Task)
   在 PCL.ModDownloadLib._Closure$__18-0._Lambda$__5(LoaderTask`2 Task)

**Comment by LTCatt** [comment]
上传启动器日志

**Comment by HeizeQiuren** [comment]
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12100563/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12100564/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12100566/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12100568/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12100569/Log1.txt)

**Comment by HeizeQiuren** [comment]
已检测出BUG所在，在设置中手动换至JAVA18后安装正常，选择“自动选择合适的JAVA”后自动选择JAVA8，手动选择JAVA8后触发失败。
初步诊断未正确自动选择JAVA
HMCL经检测后功能正常

**Comment by HeizeQiuren** [comment]
> 上传启动器日志

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12100643/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12100644/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12100645/Log3.txt)

（才发现有log文件） 经分析得出自动选择JAVA出现错误，由LOG1.txt中测试得：
手动选择JAVA17、18等安装未出现错误，自动选择合适的JAVA会自动选择JAVA8，导致新版optifine安装失败。
今早测试HMCL未出现此等问题。

**Comment by LTCatt** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/8ae38f3b-6248-4607-8372-71ab25e30c94)
在这里打开调试模式，然后再触发一次安装失败，再重新上传日志……抱歉（

**Comment by SALTWOOD** [comment]
具体的Java版本？8.0.381无法复现

**Comment by HeizeQiuren** [comment]
> 具体的Java版本？8.0.381无法复现
当时启动器日志以全部上传，现在由于个人电脑问题，系统由Windows11，DEV版本回滚至Windows10 22H2，个人数据全部清空，未保留日志等文件。
根据以往上传日志文件Log3，第230行可知，自动选择了Java8 8.0.60，且安装目录并不是我自己安装，而是网易我的世界自动安装的Java8-JRE，不是JDK。
当时我在甲骨文官网下载Java9至Java19所有版本的SDK；在java.com下载java8，获取的JDK。系统Path变量Java16-Java19均尝试过。
目前在新的电脑上已经安装网易我的世界并且选择了JAVA8.0.60JRE，目前未出现错误，目前未自己部署JAVA，所有JAVA均为PCL或网易自己安装。未设置任何系统环境变量。
目前可用JAVA：（均为自动导入）
JRE 8 8.0.51(PCL)　x64
JRE 8 8.0.60(网易)  x64
JDK11 11.16.1 (PCL)x64
JDK17 17.0.5 (StellarisCraft_v1.1.6整合包自带）x64
JDK17 17.0.3 (PCL)x64
JDK 1717.0.2 (网易)x64
当时可用JAVA：
JRE 8 (8.0.60)，64 位 (网易）
JDK 17 (17.0.5)　64位（自己部署）（手动导入）
JDK 17 (17.0.2)，64 位　（网易）
JDK 18 (18.2.1)，64 位　（自己部署）（手动导入）
JDK 8 (8.0.202)，64 位（自己部署）（手动导入）
JDK 19 (19.0.1)，64 位　（自己部署）（手动导入）
JDK 11 (11.0.17)，64 位（我的世界正版启动器部署）
JDK 11 (11.0.12)，64 位（自己部署）（手动导入）
JDK 12 (12.0.2)，64 位（自己部署）（手动导入）
JDK 10 (10.0.2)，64 位（自己部署）（手动导入）
JDK 16 (16.0.2)，64 位（自己部署）（手动导入）
JDK 9 (9.0.4)，64 位（自己部署）（手动导入）
JDK 13 (13.0.2)，64 位（自己部署）（手动导入）
JDK 14 (14.0.2)，64 位（自己部署）（手动导入）
JDK 15 (15.0.2)，64 位（自己部署）（手动导入）

**Comment by HeizeQiuren** [comment]
> 具体的Java版本？8.0.381无法复现

当时启动器日志以全部上传，现在由于个人电脑问题，系统由Windows11，DEV版本回滚至Windows10 22H2，个人数据全部清空，未保留日志等文件。
根据以往上传日志文件Log3，第230行可知，自动选择了Java8 8.0.60，且安装目录并不是我自己安装，而是网易我的世界自动安装的Java8-JRE，不是JDK。
当时我在甲骨文官网下载Java9至Java19所有版本的SDK；在java.com下载java8，获取的JDK。系统Path变量Java16-Java19均尝试过。
目前在新的电脑上已经安装网易我的世界并且选择了JAVA8.0.60JRE，目前未出现错误，目前未自己部署JAVA，所有JAVA均为PCL或网易自己安装。未设置任何系统环境变量。
目前可用JAVA：（均为自动导入）
JRE 8 8.0.51(PCL)　x64
JRE 8 8.0.60(网易)  x64
JDK11 11.16.1 (PCL)x64
JDK17 17.0.5 (StellarisCraft_v1.1.6整合包自带）x64
JDK17 17.0.3 (PCL)x64
JDK 1717.0.2 (网易)x64
当时可用JAVA：
JRE 8 (8.0.60)，64 位 (网易）
JDK 17 (17.0.5)　64位（自己部署）（手动导入）
JDK 17 (17.0.2)，64 位　（网易）
JDK 18 (18.2.1)，64 位　（自己部署）（手动导入）
JDK 8 (8.0.202)，64 位（自己部署）（手动导入）
JDK 19 (19.0.1)，64 位　（自己部署）（手动导入）
JDK 11 (11.0.17)，64 位（我的世界正版启动器部署）
JDK 11 (11.0.12)，64 位（自己部署）（手动导入）
JDK 12 (12.0.2)，64 位（自己部署）（手动导入）
JDK 10 (10.0.2)，64 位（自己部署）（手动导入）
JDK 16 (16.0.2)，64 位（自己部署）（手动导入）
JDK 9 (9.0.4)，64 位（自己部署）（手动导入）
JDK 13 (13.0.2)，64 位（自己部署）（手动导入）
JDK 14 (14.0.2)，64 位（自己部署）（手动导入）
JDK 15 (15.0.2)，64 位（自己部署）（手动导入）

**Comment by HeizeQiuren** [comment]
可能是我电脑的问题，Windows１１　DEV版本本身就有许多不兼容的地方，其他应用有时也会出现问题，或许是系统内核与上层软件访问之间的问题（（
现在回滚至Windows１０　２２Ｈ２用的还行

**Comment by LTCatt** [comment]
由于已无人可以复现，暂时关闭
