### ISSUE TITLE
在辅助功能中添加选项：默认使用UTF-8

### ISSUE THREAD

**Issue by NewZealand33** [Hex-Dragon/PCL2#2287]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在设置-启动器-辅助功能-游戏语言中添加一个选项：默认使用UTF-8代码

### 原因

在无法使用UTF-8代码的情况下进入Minecraft可能产生乱码，需要在语言中关闭“强制使用UTF-8”，新手玩家可能不会操作。添加这个选项可以更好的排查问题，同时帮助新手玩家入门。

**Comment by zkitefly** [comment]
这个我认为做成帮助文档更好点，而且 PCL2 有针对中文路径的问题做调整

**Comment by LTCatt** [comment]
这应该是玩家自己决断的问题 :/

**Comment by hejiehao** [comment]
> 这个我认为做成帮助文档更好点，而且 PCL2 有针对中文路径的问题做调整

这个好像跟中文路径没什么关系

**Comment by NewZealand33** [comment]
> 这应该是玩家自己决断的问题 :/

那要不把乱码问题加到帮助库里吧;)
