### ISSUE TITLE
mod下载界面添加Github下载源。选择mod当前或all版本的功能。更多Github或bilibili上的mod搜索或模组申报入口。

### ISSUE THREAD

**Issue by BugTD** [Hex-Dragon/PCL2#2288]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

对于一个mod，可以通过其在mc百科里的资料查询到它的Github仓库。
然后可使用`/repos/:owner/:repo/releases/:id`的githubapi来获取其发布版本。
可在原有的mod版本选择中加上all和正常mod的区别，此功能不会改变页面布局。
在原有的打开cf、md、mcmod的位置上再增加打开Github的功能（如果该mod有Github页），即使上个功能未实现，也可以让玩家自己在github中下载。
有些mod可能只在bilibili或Github或其他平台发布（比如bakadanmaku），这时可以添加模组申报入口，让创作者添加下载源（如lanzoui）

### 原因

#2282 issue所提出的问题。此issue是对该issue的补充，并细化了该增加的内容。
#2282 内容概括：pcl2可能会自动下载一个mod的all版本，而这将导致游戏崩溃。
这是mod下载bug的修复，且这项功能将会给想要自定义用户更大的选择余地

**Comment by LTCatt** [comment]
GitHub 没有固定 API，且国内访问情况极差，不会考虑制作此功能，抱歉
