### ISSUE TITLE
增加清除PCL2所有数据的功能

### ISSUE THREAD

**Issue by FangFuJi1991** [Hex-Dragon/PCL2#230]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

把所有PCL2的不可在PCL2或PCL2文件夹里删除的设置清除，还原到出厂状态。

### 原因

之前想把自己的PCL2变成刚下载时那种状态，可是没看到有这种功能就来反馈了

**Comment by Big-Cake-jpg** [comment]
为何不考虑删除 PCL 的注册表呢……

**Comment by LTCatt** [comment]
暂不考虑制作……
