### ISSUE TITLE
启动器现在需要更新时，还是会有很多人根据启动器的提示来内群里面“.更新”伯特，把这个改改吧，让他们去爱发电私信你

### ISSUE THREAD

**Issue by Primitive-society** [Hex-Dragon/PCL2#2300]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

内群伯特受到管控导致无法正常反应

### 原因

群友就不用单独@提醒它去爱发电了

**Comment by LTCatt** [comment]
这是老版本的提示，新版本已经修改了
