### ISSUE TITLE
启动时崩溃

### ISSUE THREAD

**Issue by UPbixiong** [Hex-Dragon/PCL2#2303]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

正版登录后点击一半取消后无法启动游戏

### 重现步骤

1、点击登陆游戏
2、到一半时点击取消
3,点击其他按钮，PCL2崩溃或启动一直卡在初始化

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12116515/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12116516/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12116517/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12116518/Log4.txt)

**Comment by zkitefly** [comment]
```
[13:08:32.909] [Minecraft] 自引用的继承版本：1.12.2
[13:08:32.912] 没有访问版本文件夹的权限：对路径“D:\MCLDownload\Game\.minecraft\versions\1.12.2\PCL\CheckPermission”的访问被拒绝。
PCL 的权限不足。请尝试右键 PCL，选择以管理员身份运行。
————————————
详细错误信息：
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.File.InternalDelete(String path, Boolean checkHost)
   在 PCL.ModBase.CheckPermissionWithException(String Path)
   在 PCL.ModMinecraft.McVersion.Check()
错误类型：System.UnauthorizedAccessException
```

```
[13:08:36.684] [Minecraft] 自引用的继承版本：1.12.2
[13:08:36.684] 写入文件失败：D:\MCLDownload\Game\.minecraft\versions\1.12.2\PCL\Setup.ini/Logo: pack://application:,,,/images/Blocks/Anvil.png：已添加了具有相同键的项。
   在 System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   在 System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   在 PCL.ModBase.WriteIni(String FileName, String Key, String Value)
错误类型：System.ArgumentException
```

emm，要不你试试右键给 PCL 管理员权限？

**Comment by youzi-2333** [comment]
请尽快补充相关信息，两天后仍未补充 Issue 将会被关闭，感谢配合。
