### ISSUE TITLE
添加JVM参数头(-javaagent)后无法启动游戏

### ISSUE THREAD

**Issue by IamSGZhenYun** [Hex-Dragon/PCL2#2306]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃不是 PCL2 的原因，请 **不要** 提交反馈。你可以在 QQ 群里或者论坛找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是游戏本身的问题，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

添加JVM参数头(-javaagent:"D:\RIP_TEMP\Assets\authlib-injector.jar"=http://127.0.0.1:14250/yggdrasil/409609032/77114517833647104)后游戏无法启动
但是换了HMCL添加相同的参数后 游戏却可以正常启动

### 错误报告、日志与附件

[Log.zip](https://github.com/Hex-Dragon/PCL2/files/12122927/Log.zip)

**Comment by zkitefly** [comment]
```
[17:26:24.861] [Crash] 以下为游戏输出的最后一段内容：
获取请求API
http://127.0.0.1:14250/yggdrasil/409609032/77114517833647104
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(Unknown Source)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: org/objectweb/asm/ClassVisitor
	at org.tlsp.mc.AgentMain.premain(AgentMain.java:43)
	... 6 more
Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.ClassVisitor
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 7 more
FATAL ERROR in native method: processing of -javaagent failed
Exception in thread "main" 
```

:thinking:

**Comment by IamSGZhenYun** [comment]
> ```
> [17:26:24.861] [Crash] 以下为游戏输出的最后一段内容：
> 获取请求API
> http://127.0.0.1:14250/yggdrasil/409609032/77114517833647104
> java.lang.reflect.InvocationTargetException
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(Unknown Source)
> 	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(Unknown Source)
> Caused by: java.lang.NoClassDefFoundError: org/objectweb/asm/ClassVisitor
> 	at org.tlsp.mc.AgentMain.premain(AgentMain.java:43)
> 	... 6 more
> Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.ClassVisitor
> 	at java.net.URLClassLoader.findClass(Unknown Source)
> 	at java.lang.ClassLoader.loadClass(Unknown Source)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
> 	at java.lang.ClassLoader.loadClass(Unknown Source)
> 	... 7 more
> FATAL ERROR in native method: processing of -javaagent failed
> Exception in thread "main" 
> ```
> 
> 🤔
> 
> 正常的 yggdrasil api 不是像这样的吗？ ![image](https://user-images.githubusercontent.com/64117916/255158060-6606bcd3-8b3a-47d5-9779-8859d005fc82.png)

是的 但是我这个是用的本地的
![image](https://github.com/Hex-Dragon/PCL2/assets/113534038/772f4554-3714-4e4d-8f0b-8be79688cd44)

**Comment by LTCatt** [comment]
PCL 自带 Authlib-Injector 支持，不需要自己设置 JVM 参数……
