### ISSUE TITLE
游戏突然崩溃因为内存不足，但是之后删除不了mods了

### ISSUE THREAD

**Issue by lgy120866** [Hex-Dragon/PCL2#231]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃不是 PCL2 的原因，请 **不要** 提交反馈。你可以在 QQ 群里或者论坛找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是游戏本身的问题，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

还有就是我删除了一个文件D:\.minecraft\versions\1.12.2-Forge_14.23.5.2859-LiteLoader-OptiFine_G5\config\ftbquests

### 错误报告、日志与附件

[Uploading latest.log…]()
[Uploading 2022-10-16-3.log.gz…]()

**Comment by Big-Cake-jpg** [comment]
日志未上传完成

**Comment by dongge0210** [comment]
他人好像不见了

**Comment by lgy120866** [comment]
OK



在 2022-10-16 23:44:29，"Big_Cake" ***@***.***> 写道：

日志未上传完成
