### ISSUE TITLE
执行 Java 检查无法获取输出时重试 / 添加一个选项“不自动移除没有通过 Java 检查的 Java ”

### ISSUE THREAD

**Issue by RawDiamondMC** [Hex-Dragon/PCL2#2312]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

我发现在我这里的情况是这样的：
PCL2 有时获取的到输出值，有时无法获取，导致导入时检查通过，过段时间检测不到了，自动移除了 Java。
因此我有两个方案（写在标题了），第一个有可能retry也获取不到有效 Java 的输出，第二个就没啥问题。
因为只要导入时有效就行，后续的自动移除才是最烦的。

**Comment by LTCatt** [comment]
后续不可能不移除啊，我都没法检测这个 java 的具体信息了，检测结果也是无效，留着反而其他人的会出问题……单独为了极少数人的一个无法修复的 bug 加一个设置甚至改变**原本的正常行为**是不太可能的……
说真的我觉得是你的系统问题，重装一下试试吧……
