### ISSUE TITLE
使用 Authlib-Injector 登录时跨服务器使用了缓存

### ISSUE THREAD

**Issue by mike-brown8** [Hex-Dragon/PCL2#2313]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在使用A皮肤站的一个实例登录后，再切换另一个使用B皮肤站登录的实例，启动器没有退出A皮肤站的登录状态，反而将A皮肤站的登录信息应用于B皮肤站，导致登录不能成功，并且间接导致不能同时登录多个皮肤站。

### 重现步骤

1、点击xxxx
2、往下滚，然后点击xxxx

### 日志与附件

和日志没关系

**Comment by zkitefly** [comment]
确实是这样

**Comment by LTCatt** [comment]
请上传包含这两次登录和启动的日志

**Comment by mike-brown8** [comment]
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12138018/Log1.txt)
第一次启动使用的是QSJTcraft Skin，第二次启动使用的是LittleSkin

**Comment by LTCatt** [comment]
我没有其他能测试的 Authlib 服务器…………
谁帮帮忙提供一两个用 Authlib 的我好测试 =。=？

**Comment by mike-brown8** [comment]
HMCL3和BakaXL？

________________________________

**Comment by LTCatt** [comment]
我是说皮肤站……

**Comment by kong-que-dnf123** [comment]
> 我是说皮肤站......
NameMC呢？

**Comment by kong-que-dnf123** [comment]
> > 我是说皮肤站......
> > NameMC呢？

https://zh-cn.namemc.com/

**Comment by mike-brown8** [comment]
littlesk.in / qsjtcraft skin / 统一通行证的核心
________________________________
发件人: 龙腾猫跃 ***@***.***>
发送时间: 2023年9月12日 9:41
收件人: Hex-Dragon/PCL2 ***@***.***>
抄送: Mike Brown ***@***.***>; Author ***@***.***>
主题: Re: [Hex-Dragon/PCL2] Authlib-Injector错误的使用了账户 (Issue #2313)


我是说皮肤站……

―

**Comment by LTCatt** [comment]
namemc 只能查询，不是 authlib 服务器
其他的除了 littleskin 还是没找到网站……

**Comment by WorldHim** [comment]
> namemc 只能查询，不是 authlib 服务器 其他的除了 littleskin 还是没找到网站……

[红石皮肤站](https://mcskin.cn/)？

**Comment by zkitefly** [comment]
> > > namemc 只能查询，不是 authlib 服务器 其他的除了 littleskin 还是没找到网站……
> > 
> > 
> > [红石皮肤站](https://mcskin.cn/)？
> 
> 进不去？

其实你搜一下就能找到很多个

https://www.google.com/search?q=Blessing+Skin

**Comment by kong-que-dnf123** [comment]
> > > > namemc 只能查询，不是 authlib 服务器 其他的除了 littleskin 还是没找到网站……
> > > 
> > > 
> > > [红石皮肤站](https://mcskin.cn/)？
> > 
> > 
> > 进不去？
> 
> 其实你搜一下就能找到很多个
> 
> https://www.google.com/search?q=Blessing+Skin

谷歌浏览器？？？

**Comment by zkitefly** [comment]
> > > > > namemc 只能查询，不是 authlib 服务器 其他的除了 littleskin 还是没找到网站……
> > > > 
> > > > 
> > > > [红石皮肤站](https://mcskin.cn/)？
> > > 
> > > 
> > > 进不去？
> > 
> > 
> > 其实你搜一下就能找到很多个
> > https://www.google.com/search?q=Blessing+Skin
> 
> 谷歌浏览器？？？

怎么了

**Comment by kong-que-dnf123** [comment]
> > > > > > namemc 只能查询，不是 authlib 服务器 其他的除了 littleskin 还是没找到网站……
> > > > > 
> > > > > 
> > > > > [红石皮肤站](https://mcskin.cn/)？
> > > > 
> > > > 
> > > > 进不去？
> > > 
> > > 
> > > 其实你搜一下就能找到很多个
> > > https://www.google.com/search?q=Blessing+Skin
> > 
> > 
> > 谷歌浏览器？？？
> 
> 怎么了

不用加速器的话谷歌网址在国内不是打不开吗

**Comment by zkitefly** [comment]
> > > > > > > namemc 只能查询，不是 authlib 服务器 其他的除了 littleskin 还是没找到网站……
> > > > > > 
> > > > > > 
> > > > > > [红石皮肤站](https://mcskin.cn/)？
> > > > > 
> > > > > 
> > > > > 进不去？
> > > > 
> > > > 
> > > > 其实你搜一下就能找到很多个
> > > > https://www.google.com/search?q=Blessing+Skin
> > > 
> > > 
> > > 谷歌浏览器？？？
> > 
> > 怎么了
> 
> 不用加速器的话谷歌网址在国内不是打不开吗

你认为龙猫没梯子🪜？

**Comment by kong-que-dnf123** [comment]
> > > > > > > > namemc 只能查询，不是 authlib 服务器 其他的除了 littleskin 还是没找到网站……
> > > > > > > 
> > > > > > > 
> > > > > > > [红石皮肤站](https://mcskin.cn/)？
> > > > > > 
> > > > > > 
> > > > > > 进不去？
> > > > > 
> > > > > 
> > > > > 其实你搜一下就能找到很多个
> > > > > https://www.google.com/search?q=Blessing+Skin
> > > > 
> > > > 
> > > > 谷歌浏览器？？？
> > > 
> > > 
> > > 怎么了
> > 
> > 
> > 不用加速器的话谷歌网址在国内不是打不开吗
> 
> 你认为龙猫没梯子🪜？

O

**Comment by LTCatt** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/c186f04a-3c97-4e51-805d-1665db902699)
更换皮肤站会触发刷新登录失败，然后自动重新登录获取了正确的 AccessToken……我确实没发现哪里有问题？
如果需要进一步测试的话，需要两个能进的服务器……虽然能搜出来皮肤站网站，但没有服务器 IP（

**Comment by JingHai-Lingyun** [comment]
Authlib：https://skin.ywzj.org.cn:8880
对应使用的服务器 IP：`101.132.254.49:25565`

---

注：由于这是个反作弊极其严格的机械动力服务器，在不添加专门的 Mod 的前提下好像会被白名单刷掉
只要不是提示 `验证用户名失败` 之类的就算成功（可用此登录进服）

**Comment by LTCatt** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/e59da5ea-2b1f-4bf5-b554-8ec312cda2bd)
进不去

**Comment by mike-brown8** [comment]
尝试http连接，而非ssl

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by JingHai-Lingyun** [comment]
> 进不去

..
悲

**Comment by LTCatt** [comment]
[JingHai-Lingyun](https://github.com/JingHai-Lingyun) 的服务器没问题，还需要一个 Authlib 网站和对应的服务器 IP（

**Comment by FQO3** [comment]
https://skin.tdogmc.top/

**Comment by JingHai-Lingyun** [comment]
服务器 @FQO3

**Comment by FQO3** [comment]
https://star-skin.cn/api/yggdrasil
https://skin.tdogmc.top/api/yggdrasil

**Comment by JingHai-Lingyun** [comment]
需要对应的测试服务器
~~草手滑hide了~~

**Comment by FQO3** [comment]
em……那没有了……

**Comment by PAKingdom** [comment]
https://github.com/Hex-Dragon/PCL2/issues/2313#issuecomment-1714006122
Authlib：https://www.mcpa.top
认证服务器地址：https://www.mcpa.top/api/yggdrasil
(如果需要注册账户请注意有隐藏 **reCAPTCHA** 请注意浏览器是否能访问 https://recaptcha.net/

测试账户(跟随issues状态启用) 仅供测试 Authlib-Injector

USERNAME test@test.test
PASSWORD 1qaz2wsx3edc

使用 1.7.10 原版进入
(只允许CNIP接入机房封禁海外) **play.mcpa.top:33371**
进入服务器卡住显示 **登录中** or **logging in...** 即为成功

**Comment by PAKingdom** [comment]
我注意到 https://github.com/Hex-Dragon/PCL2/issues/2313#issuecomment-1822977281 的服务器已不提供服务(MOTD无返回)又开了台server

Authlib：https://littleskin.cn
认证服务器地址：https://littleskin.cn/api/yggdrasil

使用 1.7.10 原版进入
(只允许CNIP接入机房封禁海外) **play.mcpa.top:12003**



请注意[此处](https://github.com/Hex-Dragon/PCL2/issues/2313#issuecomment-1974518016)测试服务器连接信息已变更 
总共提供两款验证方式。两个服务器接入点 服务器接入点开启至此issues关闭

---

我个人补充一下 **可能** 的复现流程，希望能帮到开发者
 **但是恕我直言，我无法复现此问题**

使用PCL2启动一次后，PCL2会吧他认定为**第三方服务器**
启动游戏时并没有去获取新的TOKEN(或者检测第三方登录地址发生变化) 就导致了切换时使用的是旧的皮肤站TOKEN 
(使用A认证登录后 换B认证登录 会使用A认证的信息启动游戏 由此引发此故障)
