### ISSUE TITLE
我明明已经换为了PCL赞助版，不知道为什么第二天再看就是非赞助版了

### ISSUE THREAD

**Issue by zhihuan137** [Hex-Dragon/PCL2#2321]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

第一天我赞助了龙猫，换成了PCL2赞助版，然后一天把主题获得了几个，其中包括极客蓝。第二天发现我的PCL文件夹里只剩下了PCL2的解锁极客蓝的那个版本。然后在回收站里找到了赞助版，奇怪的是，我并没有把他送进回收站。第三天，我的PCL2直接重回了赞助前使用的那个。就挺离谱的，不知道是不是电脑原因，如果是的话，很抱歉冒犯到了你。

### 重现步骤

每天点今日人品

### 日志与附件

没有

**Comment by iPodtouch6557** [comment]
，怀疑是 #666

**Comment by youzi-2333** [comment]
不可能是 PCL 的问题……

**Comment by zhihuan137** [comment]
> 怀疑是 #666

感谢!确认了是#666 ,和他们的情况十分相似
