### ISSUE TITLE
很奇怪，在游戏崩溃之后，启动器会消失不见

### ISSUE THREAD

**Issue by RZZCCCP** [Hex-Dragon/PCL2#2323]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如标题所示，我的是赞助版。在游戏当中模组冲突，亦或者是其他的原因导致游戏闪退。pcl启动器会莫名其妙消失（在垃圾桶里面也看不到）就像我根本没下过这个软件一样，除了启动器消失不见以外，其他的文件都正常存在，安全软件也没有任何警告。可以排除安全软件的错误删除

### 重现步骤

1.在游戏当中，使用一些不支持的光影或材质包
2.导致游戏闪退
3.游戏闪退之后,打开原启动器位置,就会发现启动器消失不见

### 日志与附件

没有任何报错文件

**Comment by JingHai-Lingyun** [comment]
见 #666

**Comment by youzi-2333** [comment]
同上。……
请尝试打开 Windows 安全中心 -> 病毒和威胁防护 -> 病毒和威胁防护设置 -> 添加或删除排除项 -> 添加排除项，将 PCL 添加进排除项。
