### ISSUE TITLE
我的世界无缘无故无法用pcl2启动（启动失败），但官方启动器可以正常启动游戏

### ISSUE THREAD

**Issue by Gubwin** [Hex-Dragon/PCL2#2324]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃不是 PCL2 的原因，请 **不要** 提交反馈。你可以在 QQ 群里或者论坛找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是游戏本身的问题，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

只显示启动失败，并且时好时坏

### 错误报告、日志与附件

更新日志·不小心，清理电脑时清除了，暂时没有这方面的日志

**Comment by youzi-2333** [comment]
发错误报告……

**Comment by Xzhao233** [comment]
我以前用Win7的时候也会有这种情况

**Comment by bwtx2023** [comment]
> 我以前用Win7的时候也会有这种情况

如果你能复现请提供复现所用游戏版本和操作步骤等相关信息，如果不能复现请不要回复无关信息，已经在好几个 Issues / Discussions 下面看见你这样了…

**Comment by youzi-2333** [comment]
请尽快补充相关信息，四天后仍未补充 Issue 将会被关闭，感谢配合。
