### ISSUE TITLE
关于拖拽功能

### ISSUE THREAD

**Issue by Element49** [Hex-Dragon/PCL2#2325]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

如果拖拽一个正常的整合包zip文件进PCL界面，PCL会自动安装。
但是如果拖拽一个其他不能安装的整合包，PCL会提示“无法确定应当执行的文件拖拽操作”，
Appdata/Local/Temp/PCL/CrashAnalyzer目录里会有拖拽的文件的残留备份没有被删除
重启也没用，必须手动删除

### 原因

这项优化可以减少PCL占用的空间。
如果没有这项优化，我需要手动删除里面的文件。

**Comment by youzi-2333** [comment]
其实 `更多 -> 百宝箱 -> 清理游戏垃圾` 可以清除缓存……
不过让 PCL 自动把无法安装的整合包缓存删掉也挺好的（
![image](https://github.com/Hex-Dragon/PCL2/assets/106497113/5aa4bf99-e34d-4ecc-9f8c-28114c1fee09)

**Comment by LTCatt** [comment]
上传能触发这个bug的整合包，和触发了这个bug的PCL日志

**Comment by Element49** [comment]
好像是拖拽任何一个文件都可以
都会自动复制到Temp目录里
知道有这个清理缓存功能了

**Comment by LTCatt** [comment]
它没有自动清理是一个 Bug，别自己关了喂（
