### ISSUE TITLE
在mod管理添加撤销选项

### ISSUE THREAD

**Issue by LBZiXL** [Hex-Dragon/PCL2#2326]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

像在资源管理器里按Ctrl+Z可以撤销一步更改一样在mod管理里增加一个撤销更改的按钮。
![image](https://github.com/Hex-Dragon/PCL2/assets/115980764/4e91fed6-e9a8-4b72-a2de-b2b369261c96)
在这添加一个按钮。

### 原因

这项优化让我可以更方便地管理mod。
如果没有这项优化，如果误删mod还必须跑回收站，让操作变得很麻烦。

**Comment by LBZiXL** [comment]
同时在mod管理里按Ctrl+Z也能撤销

**Comment by zkitefly** [comment]
为啥不打开模组文件夹执行撤销操作呢？

**Comment by LBZiXL** [comment]
那还要PCL的mod管理干啥

**Comment by zkitefly** [comment]
有啊，方便得开关模组

**Comment by youzi-2333** [comment]
我记得以前有一个 启用 / 禁用全部 Mod 前弹窗确认，被拒绝了……
这个 Issue 应该不重复。

**Comment by LBZiXL** [comment]
> 有啊，方便得开关模组
为啥不打开模组文件夹执行开关mod呢？

**Comment by LBZiXL** [comment]
> 有啊，方便得开关模组

为啥不打开模组文件夹执行开关mod操作呢？

**Comment by LTCatt** [comment]
这个功能带来的改进不大，做着又贼麻烦，算了……
