### ISSUE TITLE
PCL 错误报告无法导出

### ISSUE THREAD

**Issue by yznqzty** [Hex-Dragon/PCL2#2327]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在 Minecraft 报错之后**强制关闭** Minecraft ，之后 PCL 触发了检测错误，虽然这一切跟 PCL 没有任何关系，但是导出错误报告对话框按钮点不动。
如需视频，请联系我。（由于 GitHub 的大小限制和文件限制，所以未能上传视频）

### 重现步骤

1.  打开 PCL
2.  启动游戏，版本：1.20.1-Forge_47.1.0-OptiFine_I5
3.  出现报错，信息：
`GLFW error 65546: Cannot make current with a window that has no OpenGL ES context

Please make sure you have up-to-date drivers (see aka.ms/mcdrivers for instructions)`
4.  强制关闭 Minecraft

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12136295/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12136288/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12136289/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12136290/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12136291/Log5.txt)
[LatestLaunch.bat.txt](https://github.com/Hex-Dragon/PCL2/files/12136293/LatestLaunch.bat.txt)
[错误报告.zip](https://github.com/Hex-Dragon/PCL2/files/12138029/default.zip)

**Comment by zkitefly** [comment]
这个能稳定复现吗？

日志中并没有点按导出按钮执行的日志

**Comment by yznqzty** [comment]
安装时用的是推荐版本。

**Comment by zkitefly** [comment]
> 安装时用的是推荐版本。

optifine HD_U_I5 推荐的 forge 版本是 47.0.35

**Comment by yznqzty** [comment]
额...看看这个。
![QQ截图20230723142021](https://github.com/Hex-Dragon/PCL2/assets/135207045/e177f64d-cbb5-4da0-a6e4-55c01d38928d)

**Comment by zkitefly** [comment]
> 额...看看这个。
> ![QQ截图20230723142021](https://github.com/Hex-Dragon/PCL2/assets/135207045/e177f64d-cbb5-4da0-a6e4-55c01d38928d)

那个是 forge 稳定版推荐版本不是 optifine 推荐的版本

**Comment by zkitefly** [comment]
一般来说是 optifine 去兼容 forge 而不是反过来

**Comment by yznqzty** [comment]
啊这...

**Comment by youzi-2333** [comment]
看 Log3 末尾像是 PCL 崩了……
不知道啥问题，应该是偶发情况修不了（吧

**Comment by LTCatt** [comment]
……可以重现么？
我没在日志里看到点击“导出错误报告”按钮这一项，你有没有真的点那个导出按钮？

**Comment by LTCatt** [comment]
由于太长时间没有回复先关闭了，如果有需要可以继续在这下面回复
