### ISSUE TITLE
为PCL2开发简易模式GUI?

### ISSUE THREAD

**Issue by ChiLinCN** [Hex-Dragon/PCL2#2330]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

简易模式 某种意义上来讲 就是只剩下启动器最核心的功能:启动页 割去自定义主页的右侧区 只剩下启动器左侧核心功能区 而其他功能页只在完整PCL2模式下可用
在简易模式中无法切换其他页面 只有启动页的功能可用(简易模式和完整模式切换按钮在最小化按钮旁边放置)

### 原因

很大一部分时间打开启动器只会为了纯粹的启动minecraft 不会干其他事情(比如下模组)

**Comment by pangzong2011** [comment]
意义不大，盲猜要关，另外一提，好像可以通过启动器页面（是这个页面吧没记清）关闭启动器的功能，应该可以满足你的简洁需求了

**Comment by pangzong2011** [comment]
意义不大，盲猜要关，另外一提，好像可以通过启动器选项的页面（是这个页面吧没记清）关闭启动器的功能，应该可以满足你的简洁需求了

**Comment by ChiLinCN** [comment]
> 意义不大，盲猜要关，另外一提，好像可以通过启动器选项的页面（是这个页面吧没记清）关闭启动器的功能，应该可以满足你的简洁需求了

会带着自定义主页一起消失(包括显示自定义主页的区域)

**Comment by ChiLinCN** [comment]
(怎么说呢 又感觉自己的这个提议有点牵强...? 只是为了简洁?)

**Comment by Yue-cn** [comment]
根据需求，我认为他可能想要的是像某个Rust开发的启动器的首页UI差不多，仅保留User Profile和一些操作

**Comment by WForst-Breeze** [comment]
见 #2329 的回复，可以使用功能隐藏来基本实现需求，大概率不会做（

**Comment by Yue-cn** [comment]
根据楼主的需求，差不多这个样
![image](https://github.com/Hex-Dragon/PCL2/assets/79188080/8bd92bd9-d839-4e4a-a232-f9f90ebbc43a)

**Comment by Steve-xmh** [comment]
你可能会需要：https://github.com/Steve-xmh/scl

**Comment by ChiLinCN** [comment]
> 你可能会需要：https://github.com/Steve-xmh/scl
> 
> 随便给你补充一个截图当参考： ![](https://user-images.githubusercontent.com/39523898/208238006-900bd5fe-f9f7-42a9-b726-da829162fbed.png)

az 那看起来 这个提议算是废了.jpg

**Comment by LTCatt** [comment]
暂不考虑 :/
