### ISSUE TITLE
游戏窗口设置最大化(其他没试验过)对新版本无效

### ISSUE THREAD

**Issue by DXJLSFB139** [Hex-Dragon/PCL2#2331]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在PCL2中更改设置中的“游戏窗口设置”为最大化，游戏启动后仍然处于初始状态

### 重现步骤

1、点击设置
2、将“游戏窗口”改为最大化
3、启动游戏
4、无法窗口成最大化

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12138276/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12138278/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12138279/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12138280/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12138281/Log5.txt)
![fk](https://github.com/Hex-Dragon/PCL2/assets/105050068/1bdb4d3d-aa18-432c-9ccd-cd2a4d25478a)
![fk2](https://github.com/Hex-Dragon/PCL2/assets/105050068/38ff3d23-e353-4e28-a710-e2d6d13981ce)

**Comment by pangzong2011** [comment]
如果是因为窗口放大但没达到预定的尺寸，可以关了，之前的issue提到过，不可能完美达到的预定设置窗口大小，如果是大小没变当我没说（笑）

**Comment by youzi-2333** [comment]
……我没这个问题，请再次确认设置是否配置为“最大化”

> 如果是因为窗口放大但没达到预定的尺寸，可以关了，之前的issue提到过，不可能完美达到的预定设置窗口大小，如果是大小没变当我没说（笑）

描述里面已经特别明确的说过了，“游戏窗口”设定设为最大化，又不是自定义……（叹气

**Comment by LTCatt** [comment]
能否稳定重现？
如果可以重现，录一下启动时的视频传上来……如果文件太大传不了可以传网盘（

**Comment by DXJLSFB139** [comment]
在我这可以复现(每次都这样
视频:https://luhuiyuan.lanzoub.com/iqwBX13dkj3a

**Comment by LTCatt** [comment]
添加了相关 log，等下一个版本再看看……

**Comment by lin15266115** [comment]
我也遇到了类似的问题，但是只有一个版本会这样，而且后面装的同样的版本也没有问题
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12230555/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12230556/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12230557/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12230559/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12230560/Log4.txt)

**Comment by DXJLSFB139** [comment]
BUG已经解决，在最新版本
