### ISSUE TITLE
PCL2错误分析游戏崩溃

### ISSUE THREAD

**Issue by 596wjr** [Hex-Dragon/PCL2#2332]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我点击游戏主页面客户端右下角退出游戏，PCL2提示Minecraft崩溃
注：客户端有mod

### 重现步骤

（也许需要使用特定的mod）
点击主页面退出游戏

### 日志与附件

[错误报告-2023-7-23_20.14.32.zip](https://github.com/Hex-Dragon/PCL2/files/12138723/-2023-7-23_20.14.32.zip)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12138725/Log1.txt)

**Comment by youzi-2333** [comment]
不知道是哪个大聪明 Mod 作者，给 Minecraft 搞了个 `-1073740940` 的返回值……

---

我目前有两个解决思路：
- 在 返回值 > 0 时才分析崩溃，否则不分析；
- 如果 Minecraft 最后一个输出正常（即类似 `[20:13:54] [Render thread/INFO]: Stopping!`），则不分析崩溃。

**Comment by LTCatt** [comment]
> 不知道是哪个大聪明 Mod 作者，给 Minecraft 搞了个 `-1073740940` 的返回值……
> 
> 我目前有两个解决思路：
> 
> * 在 返回值 > 0 时才分析崩溃，否则不分析；
> * 如果 Minecraft 最后一个输出正常（即类似 `[20:13:54] [Render thread/INFO]: Stopping!`），则不分析崩溃。

其他原因导致的崩溃都可能会出现你说的情况，返回值可能 <0，也可能输出 MC 正常关闭时的 Log，不能作为判断标准。
我觉得这个 issue 应该交给导致这个错误返回值的啥玩意儿，而不是启动器……
