### ISSUE TITLE
模组管理界面长按左键并滑动以多选模组

### ISSUE THREAD

**Issue by Chiloven945** [Hex-Dragon/PCL2#2333]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在模组管理界面，对其中一个模组长按右键的时候滑动，自动选择所有光标经过的模组。

### 原因

方便……?
因为目前的全选功能在模组比较多的情况下，要批量删除一些模组的话只能挨个挨个点，所以说会方便点？

**Comment by LTCatt** [comment]
仔细寻思了一下，暂时不考虑制作快速选择相关的功能，这些都超出启动器范畴了：它不是 Mod 管理器，也不是文件管理器……
抱歉 :/

**Comment by LTCatt** [comment]
……顺手做了
