### ISSUE TITLE
回声洞更新

### ISSUE THREAD

**Issue by jocemod** [Hex-Dragon/PCL2#2335]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

回声洞有一条“你一定要点击下面的‘千万别点‘”’，而现在“千万别点”按钮在回声洞的上面
![image](https://github.com/Hex-Dragon/PCL2/assets/88583380/b0edc2fa-d5c9-4198-8761-1ac0e2a3607c)

这条有个没用的/n

### 原因

无

**Comment by iPodtouch6557** [comment]
#2158 已修复该问题，请确认你的版本是否更新至2.6.4
