### ISSUE TITLE
在HTTP代理需要密码认证时，弹出用户名及密码框而不是显示远程服务器错误

### ISSUE THREAD

**Issue by mywwzh** [Hex-Dragon/PCL2#2339]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在Windows设置打开需要认证的HTTP代理后，PCL2会由于代理服务器返回HTTP ERROR 407而提示原程服务器错误。
建议像vscode那样，弹出代理的用户名和密码输入框。
![屏幕截图 2023-07-24 152634](https://github.com/Hex-Dragon/PCL2/assets/126879177/a53d6738-9d34-4de4-9ce5-9f0245abcbe0)

### 原因

（示例）
如果没有这项优化，那么我必须在每次下载前关闭代理，而有时不开代理根本下不了mod或整合包.......

**Comment by bwtx2023** [comment]
我觉得大概率不会为你这种个别情况适配…
