### ISSUE TITLE
通过命令行启动PCL2

### ISSUE THREAD

**Issue by zengyuxiang0921** [Hex-Dragon/PCL2#2343]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [ ] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [ ] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

可以通过cmd或powershell启动PCL2
比如：

- install <version> <modloader>
- run <mc_name> <lauch_type> <name>
- change_skin <skin_location>
- add_mods <mod_loacation>
- delete_mods <mod_name>
- disable_mods <mod_name>
- auto_in_sever <ip>
- jvm_head <type> <parameter_head>
- java_loacation <java_loacation>
- version_quarantine <mc_name>
- default_mc_ram <mc_name> <bytes>

用参数运行时不用gui

### 原因

添加命令行参数后可以轻松地用.bat启动游戏，不用一大堆jvm参数了。
还可以自制启动器。

**Comment by zkitefly** [comment]
这个功能好像被拒了，不过我找不到那个issue了（

**Comment by bwtx2023** [comment]
套个壳不能叫自制启动器…

个人认为实用价值不大

**Comment by bwtx2023** [comment]
> 套个壳不能叫自制启动器…
> 
> 个人认为实用价值不大

先过了等龙猫看看然后留个记录

**Comment by miner233** [comment]
这不是实用价值大不大的问题了，是真的没有必要。
做一个 Minecraft 启动器就是为了简化启动流程，而使用命令行却使原本简化的启动流程变得相对复杂了起来。
如果你真想 ~~在别人面前装 X~~ 使用命令行的话，建议直接使用 cmd 调用 java.exe 运行 Minecraft.jar 再一个个写参数进去。
如果你要下载 Minecraft 的话，你直接用 cmd 自带的命令通过 url 下载就可以了，没有必要再用什么 “启动器” 套个壳。
所以，通过命令行启动 PCL2 的功能可以说是 “一般用户不会用，大佬用户用不上”，应该不会有几个人用的，真的毫无必要。
