### ISSUE TITLE
PCL2 无法检测Java 

### ISSUE THREAD

**Issue by RimacC2-EV** [Hex-Dragon/PCL2#2347]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

目前的PCL (Ver.2.6.3) 无法识别Java 20.0.2.
<img width="647" alt="image" src="https://github.com/Hex-Dragon/PCL2/assets/125170682/d7940fbf-d0c4-4c14-8157-ac33db40ea3e">
<img width="760" alt="image" src="https://github.com/Hex-Dragon/PCL2/assets/125170682/8f060ec3-9895-4e7b-a263-d1c7c222def2">

### 重现步骤

1、在https://www.oracle.com/java/technologies/downloads/#java17中下载并安装Java 20.0.2
2、启动PCL2，点击Java（自动搜索）
3、在之后的列表中搜索，无法发现已安装的Java 20.0.2
（Java（JDK/JRE) 的新版本无法检测相关BUG可能每隔一段时间就会出现）

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12171383/Log1.txt)

**Comment by zkitefly** [comment]
你输入在 CMD中输入并回车 `D:\MinecraftVersions\Java\jdk-20.0.2\bin\java.exe -version` ，并将输出内容截图

**Comment by RimacC2-EV** [comment]
<JAVA_HOME>/lib/ext exists, extensions mechanism no longer supported; Use -classpath instead.
.Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
······也许我环境变量没弄，但我还没学过Java······

**Comment by iPodtouch6557** [comment]
我记得是PCL尚未添加相关适配来着（？）

**Comment by RimacC2-EV** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/125170682/83273cdc-35f3-4145-afa9-76729dfb9825)
<img width="470" alt="image" src="https://github.com/Hex-Dragon/PCL2/assets/125170682/b380eb66-a7a1-42fe-b7f0-450eb7716bc3">
<img width="760" alt="image" src="https://github.com/Hex-Dragon/PCL2/assets/125170682/57c3d2d9-c7ac-4e68-973d-906e5fa5f1bb">
确实，JDK 20.0.2最近才发布

**Comment by RimacC2-EV** [comment]
也许我环境变量没弄，但我还没学过Java······
![image](https://github.com/Hex-Dragon/PCL2/assets/125170682/adb2d45d-f495-4965-a35e-b556f5787a46)

**Comment by RimacC2-EV** [comment]
@zkitefly 
![image](https://github.com/Hex-Dragon/PCL2/assets/125170682/6a59e7ad-2b8f-46ff-8ed7-dfb5a647a30d)

**Comment by WangSimele** [comment]
我也有过类似的报错，但提示内容不一样，它是说在高版本的JDK与Minecraft越来越不兼容，所以停止使用，也是提示Java存在异常，从最新快照2.6.4复现的

**Comment by iPodtouch6557** [comment]
麻烦改一下标题：PCL 无法识别 Java20.0.2 以上版本的Java
