### ISSUE TITLE
在Mod搜索页搜索老版本会出现其他版本

### ISSUE THREAD

**Issue by mc-124** [Hex-Dragon/PCL2#2352]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在mod搜索页搜索老版本minecraft（如1.0）时会出现其他版本的mod（如 Goat Drop Food，这个模组似乎只支持1.19.1-Fabric）

### 重现步骤

1、点下载，点Mod
2、版本那直接输入1.0或1.1等远古版本
3、搜索
4、有概率看到一些版本不对的mod

### 日志与附件

[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12179312/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12179313/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12179315/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12179316/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12179317/Log4.txt)

**Comment by WForst-Breeze** [comment]
作者自己标的 O_o 与 PCL 无关
![image](https://github.com/Hex-Dragon/PCL2/assets/110760354/15b4856d-9f3e-4054-ad2c-01db43c1d838)
