### ISSUE TITLE
PCL2快照版2.6.4无法检测出1.17.1游戏崩溃

### ISSUE THREAD

**Issue by Franklzz2010** [Hex-Dragon/PCL2#2353]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

游戏启动时崩溃后PCL2认为游戏正常退出 没有显示“Minecraft出现错误”弹窗

### 重现步骤

1、启动游戏（版本：MTR）
2、启动游戏时游戏崩溃
3、游戏崩溃 游戏窗口消失 PCL2未弹窗

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12182501/Log1.txt)
Minecraft游戏文件（崩溃的那个版本 开启版本隔离）：链接：https://pan.baidu.com/s/1sCUFgVIuTIKexSIH3FdlWQ 提取码：PCL2

**Comment by Franklzz2010** [comment]
> [latest.log](https://github.com/Hex-Dragon/PCL2/files/12183210/latest.log) 这是latest.log 这样就不需要忍受度盘的极致的下载体验

游戏文件太大了 1.6个G GitHub上没法上传 lol

**Comment by youzi-2333** [comment]
mc 返回值不对，PCL 应该没法判断吧……
除非 PCL 可以读日志，然后发现游戏扔出来的异常（

**Comment by zkitefly** [comment]
这个能稳定复现吗？

**Comment by Franklzz2010** [comment]
> 这个能稳定复现吗？

可以的

**Comment by LTCatt** [comment]
你的 PCL 日志里没有找到 MC 崩溃的描述啊？传错了？

**Comment by LTCatt** [comment]
由于太久未回复暂时关闭，若有需要可以继续在这里回复
