### ISSUE TITLE
Mod 管理在下边栏加全选功能

### ISSUE THREAD

**Issue by Chiloven945** [Hex-Dragon/PCL2#2354]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

目前的模组选择界面点击模组除红石灯以外的区域会自动选择模组，而不是禁用。
将全选按钮更改为多选，后触发多选，按钮变更为全选，弹出选择框
![image](https://github.com/Hex-Dragon/PCL2/assets/116699482/0763fd28-edb5-4643-a57a-47d497618b4e)
（未选择且弹出提示框时，可以显示“已选择0个模组”或者提示性文本“多选模组”什么什么的）

总的来说，就是不启动多选功能时为之前正常的点击禁用、再点击启用，而要启动时，点击多选按钮，进入多选模式，先前的多选按钮变为全选（或者在下方的提示栏添加全选）

### 原因

在不影响使用的情况下兼容新旧两种操作方式。
虽说目前可以通过点击红石灯来对单个模组进行开关调整，但是由于红石灯的占地太小，如果想单个启用禁用有点不太符合直觉…

**Comment by Chiloven945** [comment]
还有就是建议加个反选？不太想开多个issue，龙猫看到同意了直接加就可以（

**Comment by LTCatt** [comment]
在下边栏加全选应该就差不多吧……

**Comment by Chiloven945** [comment]
我想的是改成触发式的（）
点击按钮才启用多选的功能

**Comment by LTCatt** [comment]
如果改啥东西都要 ”兼容老操作方式“ 的话那还是毁灭得了……

**Comment by iPodtouch6557** [comment]
> 如果改啥东西都要 ”兼容老操作方式“ 的话那还是毁灭得了……

……就像mojang在1.9更新时拒绝玩家提议的old_pvp就是避免出了bug两个都得修，翻倍增加工作量（）所以在此也提醒大家，别再提议“新操作方式兼容旧方式了”
