### ISSUE TITLE
下载失败

### ISSUE THREAD

**Issue by Herobrlxj** [Hex-Dragon/PCL2#2355]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

下载失败

### 重现步骤

1、点击1.16.5的版本
2、往下滚，然后点击forge的版本任一一个

### 日志与附件

下载 Forge 36.2.33失败
→ 获取 Mod 下载器支持库文件失败
→ Value cannot be null.
Parameter name: path
   at PCL.ModDownloadLib._Closure$__37-1._Lambda$__3(LoaderTask`2 Task)
   at PCL.ModLoader.LoaderTask`2._Closure$__12-0._Lambda$__0()
错误类型：System.ArgumentNullException

**Comment by bwtx2023** [comment]
上传启动器日志

**Comment by youzi-2333** [comment]
超时关闭，如有信息需要补充可以继续提出。
