### ISSUE TITLE
关于启动脚本

### ISSUE THREAD

**Issue by XLX9200** [Hex-Dragon/PCL2#2356]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

用脚本启动游戏，但丢失所有进度

### 重现步骤

1、导出游戏启动脚本
2、用脚本打开游戏
3.正常进入游戏
4.全部进度丢失

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12190509/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12190510/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12190511/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12190513/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12190514/Log2.txt)

**Comment by niuyuhao0818** [comment]
可以上传启动脚本吗

**Comment by SALTWOOD** [comment]
请顺带上传脚本
也许你可以检查生成脚本时的账号信息与正常启动时使用的账号信息是否一致
而且生成脚本时也有声明，使用脚本启动可能会导致无法登录

**Comment by SALTWOOD** [comment]
请顺带上传脚本
也许你可以检查生成脚本时的账号信息与正常启动时使用的账号信息是否一致
而且生成脚本时也有声明，使用脚本启动可能会导致无法登录

**Comment by XLX9200** [comment]
[启动 1.16.5-失落的城市.txt](https://github.com/Hex-Dragon/PCL2/files/12192488/1.16.5-.txt)

**Comment by hejiehao** [comment]
为什么你认为全部进度丢失？

**Comment by XLX9200** [comment]
一进入游戏就开始弹成就，一看全没了

**Comment by youzi-2333** [comment]
PCL 导出的启动脚本会将 Token 打码，无法正常登录 Minecraft 账户。

直接点“启动游戏”按钮，只要按一下鼠标就行了，为啥要费那么大力气按两下鼠标打开启动脚本……

**Comment by zkitefly** [comment]
> PCL 导出的启动脚本会将 Token 打码，无法正常登录 Minecraft 账户。
> 
> 直接点“启动游戏”按钮，只要按一下鼠标就行了，为啥要费那么大力气按两下鼠标打开启动脚本……

我觉得导出启动脚本不应该做过滤处理的呀，毕竟这个是用来启动游戏用的？

**Comment by SALTWOOD** [comment]
> > PCL 导出的启动脚本会将 Token 打码，无法正常登录 Minecraft 账户。
> > 直接点“启动游戏”按钮，只要按一下鼠标就行了，为啥要费那么大力气按两下鼠标打开启动脚本……
> 
> 我觉得导出启动脚本不应该做过滤处理的呀，毕竟这个是用来启动游戏用的？

防止被恶意程序读取盗号

**Comment by zkitefly** [comment]
assteToken 不是 24 小时过期吗

**Comment by youzi-2333** [comment]
应该是为了防止崩溃去 PCL 内群提问，然后群友要他发启动脚本，结果他这样导出发群里，然后被盗号……

**Comment by hejiehao** [comment]
> 

我觉得要盗号就不会用这种手法了
