### ISSUE TITLE
[优化] 导出启动脚本时弹出提示

### ISSUE THREAD

**Issue by youzi-2333** [Hex-Dragon/PCL2#2359]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在版本设置中导出启动脚本时，弹窗提示 `导出的启动脚本仅限调试使用，不建议用于启动游戏`。

### 原因

帮助玩家理解启动脚本不能用于启动游戏，否则登不上账号……

**Comment by hejiehao** [comment]
似乎对于使用离线账号的玩家来说这个提示完全没有必要

**Comment by WTP016-CN** [comment]
> 似乎对于使用离线账号的玩家来说这个提示完全没有必要

应该可以加一个针对使用正版登录的玩家才弹出的条件
我觉得可行

**Comment by LTCatt** [comment]
```
                If Setup.Get("LoginType") = McLoginType.Legacy Then
                    Hint("正在导出启动脚本……")
                Else
                    Hint("正在导出启动脚本……（注意，使用脚本启动可能会导致登录失效！）")
                End If
```
现在的已经有这个意思了，没啥必要改
