### ISSUE TITLE
针对部分 CurseForge Mod 中分开 Fabric/Quilt 和 Forge 版本中描述标签的大小写区分

### ISSUE THREAD

**Issue by WTP016-CN** [Hex-Dragon/PCL2#2360]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

修正大小写为 Fabric 和 Quilt 版本。

### 原因

~~帮助库都要求大小写规范表示，那界面大小写肯定不能放过了~~
这里的 Fabric 和 Quilt 没有规范大小写，既不好看也不美观（废话
目前只找到 Neat 这一个模组，至于其他模组我也不是很清楚了
![image](https://github.com/Hex-Dragon/PCL2/assets/66893541/57e52af4-d811-4429-ba9c-bef11ca250e4)

**Comment by hejiehao** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/98140773/f737a89d-3d80-491b-bbcc-6b1ef972e6f5)

**Comment by WTP016-CN** [comment]
> ![image](https://user-images.githubusercontent.com/98140773/256805152-f737a89d-3d80-491b-bbcc-6b1ef972e6f5.png)

但这里的 Quilt 还有问题……
