### ISSUE TITLE
[优化]对各个MC实例独立“Java兼容性警告”设置

### ISSUE THREAD

**Issue by SALTWOOD** [Hex-Dragon/PCL2#2361]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

对各个MC实例独立“Java兼容性警告”设置，以允许单独为某个Minecraft实例开启或关闭“Java兼容性警告”设置

### 原因

LabyMod4所有版本都需要使用Java 17+，但是PCL2识别出1.12.2使用Java 8并在每次启动时都弹出兼容性警告，但是在全局设置中开启“忽略Java兼容性警告”则会导致所有版本的Minecraft启动时都不会弹出兼容性警告。

**Comment by SALTWOOD** [comment]
虽然凭我的经验很可能被拒绝/放弃，但请龙猫考虑一下
确实没有在Issues发现类似的请求
建议可以识别或标记非标准Minecraft核心以允许自定义Java版本而不检查兼容性（？）

**Comment by LTCatt** [comment]
这个 Mod 让原本不支持 Java 17 的版本变得支持 Java 17 了？

**Comment by SALTWOOD** [comment]
LabyMod4是一个大范围修改Minecraft的PVP客户端，它的所有版本都需要Java 17+
不是一个单独的模组

**Comment by SALTWOOD** [comment]
它不像Lunar、Badlion一定需要单独的启动器，所以PCL2能够启动它，但是PCL2会把它当作普通的MC处理
其实就是加一个选项而已啦（
