### ISSUE TITLE
[优化]添加对更多输入的支持

### ISSUE THREAD

**Issue by SALTWOOD** [Hex-Dragon/PCL2#2362]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

支持触摸输入的滚动操作（可以通过按住并拖拽触摸笔来拖动页面）
还可以考虑支持键盘Tab键选中，Enter确定甚至接入手柄操作（？

### 原因

目前大多数页面不支持触摸输入的滚动操作（比如数位板无法通过按住并拖拽笔来拖动页面，必须按住笔上的拖动按钮模拟鼠标滚轮输入）
对触摸屏玩家不太友好（毕竟Minecraft还可以通过安装模组支持触摸和手柄操作）

**Comment by LTCatt** [comment]
我无法测试……所以做不了……
