### ISSUE TITLE
[建议] 为Log日志增加脱敏处理

### ISSUE THREAD

**Issue by Paimon-Kawaii** [Hex-Dragon/PCL2#2363]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

建议给Log日志加个脱敏处理的功能ww

### 原因

不是很重要的功能，但是几乎每个issue都会带上相应的log日志，所以还是建议将log进行脱敏处理

**Comment by zkitefly** [comment]
我想起来 PCL2 有对 assteToken 做脱敏处理，不过建议做的极致一点，如果检测到例如崩溃日志导出里头有 assteToken ，就将其替换成脱敏符号，这样防止有模组在 log 里面展示 assteToken

**Comment by LTCatt** [comment]
这种东西没有一个统一的标准的，很难做……你不好判断一个玩意儿是否属于敏感内容，或者把它和谐了会不会导致丢失 Debug 所需的重要信息……
