### ISSUE TITLE
添加“无边框窗口化全屏”选项

### ISSUE THREAD

**Issue by InfinityWolfly** [Hex-Dragon/PCL2#2364]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

如题。

### 原因

这项优化让我可以更方便地在全屏时切换窗口。
如果没有这项优化，我每次都必须（操作），让操作变得很麻烦。

**Comment by SALTWOOD** [comment]
这好像是Mod功能？

**Comment by LTCatt** [comment]
这只有安装 Mod 才能实现，启动器做不到

**Comment by InfinityWolfly** [comment]
但是Watt Toolkit可以实现这个功能
![image](https://github.com/Hex-Dragon/PCL2/assets/132419357/da1bf50a-009b-4967-9569-85aefbace2a4)

**Comment by LTCatt** [comment]
说真的，第三方实现无边框全屏很蛋疼，不管咋说这种技术方案太超出启动器的范畴了……

**Comment by hejiehao** [comment]
> 但是Watt Toolkit可以实现这个功能 ![image](https://user-images.githubusercontent.com/132419357/256978752-da1bf50a-009b-4967-9569-85aefbace2a4.png)

什么原理？把上面那个框搞出屏幕显示范围以及把任务栏隐藏？

**Comment by InfinityWolfly** [comment]
> 

并不
就是单纯的去除边框
原理是让Windows不为它渲染边框

**Comment by InfinityWolfly** [comment]
> > 但是Watt Toolkit可以实现这个功能 ![image](https://user-images.githubusercontent.com/132419357/256978752-da1bf50a-009b-4967-9569-85aefbace2a4.png)
> 
> 什么原理？把上面那个框搞出屏幕显示范围以及把任务栏隐藏？

并不
就是单纯的不渲染边框
