### ISSUE TITLE
PCL2在没有音乐时仍尝试获得音乐路径

### ISSUE THREAD

**Issue by Madvikfut** [Hex-Dragon/PCL2#2366]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

当Music文件夹被清空时,PCL2仍然尝试获取音乐路径.

### 重现步骤

在Music中放入多首ogg格式的音乐,然后刷新背景音乐,PCL2提示无法播放后点击'清空背景音乐'.
已经发现只放一首ogg格式的音乐不能触发这个Bug.
(不过好像无关紧要?....)

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12206102/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12206103/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12206104/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12206105/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12206106/Log5.txt)

**Comment by youzi-2333** [comment]
我这里的 ogg 可以播放啊……
几个 Log 翻了一遍也看不出啥问题……
请再次复现该问题，然后重新上传 Log。

**Comment by Madvikfut** [comment]
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12208397/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12208398/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12208399/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12208400/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12208401/Log5.txt)
重新复现了一下,问题仍然存在.......
不过应该不会有正常人像我这么干吧.....

**Comment by Madvikfut** [comment]
话说是不是反馈bug会给个主题啊
不知道怎么解锁((bushi

**Comment by youzi-2333** [comment]
是的，请在 设置 => 启动器 => 复制识别码 将你的识别码贴在这里，龙猫会给你解锁码的……

**Comment by Madvikfut** [comment]
888B-22CC-74E5-2F19
好耶

**Comment by LTCatt** [comment]
你的解锁码：j6+x2sDzq2ia4+eU1Rr2ByWe1AbJinqH
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
