### ISSUE TITLE
建议添加一个“关闭文件补全”以忽略无法下载的缺失文件，并继续启动MC

### ISSUE THREAD

**Issue by Sinecre88888** [Hex-Dragon/PCL2#2367]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

我希望能在PCL2的设置——游戏中加入勾选项“关闭文件补全”，我1.12.2整合包水星迫降因无法下载缺失文件而导致启动失败，建议加入此功能，忽略无法下载的缺失文件，并继续启动MC（无论MC能不能运行都一律忽略）
![QQ截图20230729115637](https://github.com/Hex-Dragon/PCL2/assets/95292146/681a3336-01d5-481e-b125-ff3614befd84)

### 原因

见描述

**Comment by Sinecre88888** [comment]
还有我手动下载缺失文件并放在指定目录，仍然没有用，还是报错

**Comment by WForst-Breeze** [comment]
版本设置-设置-高级启动选项-文件校验-关闭

**Comment by Sinecre88888** [comment]
> 版本设置-设置-高级启动选项-文件校验-关闭

关了啊，没用

**Comment by WForst-Breeze** [comment]
抱歉，看错了qwq……

**Comment by LTCatt** [comment]
你错误删除了整个 libraries 文件夹，这个文件夹是不能全删的，这会导致 OptiFine 无法启动，必须重新安装这个版本
