### ISSUE TITLE
内存优化会优化正在运行的java版服务器的内存

### ISSUE THREAD

**Issue by Anythingteam** [Hex-Dragon/PCL2#2368]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

服务器Xms和Xmx均为16GB，空载时内存优化前任务管理器中占用为16000mb，优化占用后为100mb；建议加个警告界面之类的，不然如果服务器有玩家在线会导致突然服务器卡顿

### 重现步骤

1。开启一个java版服务器
2. 进行内存优化

### 日志与附件

无

**Comment by zkitefly** [comment]
启动器又不是启动服务器端，怎么知道你在启动服务器（

我感觉会被拒（

**Comment by Anythingteam** [comment]
补充一下，指电脑运行mc服务器时点击内存优化。这种情况下优化内存可能导致服务器由于内存被其他程序占用导致缺少内存出现崩溃，异常，严重卡顿等。而玩家却不知情

**Comment by WTP016-CN** [comment]
服务端和客户端的程序名都是 javaw.exe
这不好识别吧（

**Comment by hejiehao** [comment]
似乎应该是先优化再启动服务器

**Comment by LTCatt** [comment]
这是系统级 API，我无法指定让它不处理某个进程，技术上无法实现 :/
