### ISSUE TITLE
允许不再显示清理游戏垃圾的警告

### ISSUE THREAD

**Issue by Anythingteam** [Hex-Dragon/PCL2#2373]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

![QQ截图20230729161035](https://github.com/Hex-Dragon/PCL2/assets/103157696/8c92e171-9185-4532-9a3d-3174d32f5589)
估计有什么违禁词，只能发图片了

### 原因

方便操作

**Comment by WForst-Breeze** [comment]
不是违禁词，应该就是你短时间内提交 Issue 频率太高了（
