### ISSUE TITLE
版本隔离默认开启

### ISSUE THREAD

**Issue by Anythingteam** [Hex-Dragon/PCL2#2375]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

使pcl2默认开启版本隔离，若检测到游戏文件夹有未隔离的版本，将提示玩家并让玩家选择是否隔离

### 原因

版本隔离已经成为许多人共同的选择

**Comment by LTCatt** [comment]
版本隔离的默认设置不太可能能修改，这会导致更萌新的玩家集体懵逼……

**Comment by hejiehao** [comment]
提示版本隔离似乎已经有了
