### ISSUE TITLE
在进行内存优化前弹出警告窗口

### ISSUE THREAD

**Issue by Anythingteam** [Hex-Dragon/PCL2#2381]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在进行内存优化前弹出警告窗口，先说明这会导致其他java程序的内存也被优化

### 原因

避免由于不知情情况下进行内存优化导致一些程序受影响

**Comment by LTCatt** [comment]
所有程序都会……但如果你卡那也不是因为程序被优化了卡，是硬盘速度不够快卡的……
没有太大必要加警告窗口……
