### ISSUE TITLE
增加个性化序列号 

### ISSUE THREAD

**Issue by weiweiaigaoshi** [Hex-Dragon/PCL2#2384]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

在个性化里添加输入序列号，再添加验证，有两种解决方式，1.验证电脑名2.验证有几个隐藏主题（想不出还有验证方式），把序列号搞乱一些，在把个性化的自定义恢复成重装前的样子。

### 原因

因为我重装电脑（把所有盘的文件删除了），导致PCL2的隐藏主题没了，所以我想到了个性化序列号。

**Comment by zkitefly** [comment]
我记得......主题没了就是没了好像（

**Comment by WTP016-CN** [comment]
按我的经验，龙猫多半会拒绝……但还是先挂在这里吧
