### ISSUE TITLE
导入curseforge整合包时不能正确加载该包的设置

### ISSUE THREAD

**Issue by ShenXuan233** [Hex-Dragon/PCL2#2385]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

导入curseforge整合包时不能正确加载该包的设置，例如视频设置，键位绑定，材质包等

### 重现步骤

1、点击xxxx
2、往下滚，然后点击xxxx

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12209847/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12209848/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12209849/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12209850/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12209852/Log5.txt)

**Comment by zkitefly** [comment]
能上传你安装的整合包安装包吗

**Comment by ShenXuan233** [comment]
> 方便上传你安装的整合包的安装包吗？

https://wwgs.lanzoub.com/ibtD513ybp5a 上传不了大于25MB的文件，我传到蓝奏云里了

**Comment by zkitefly** [comment]
我能了解下 该包的设置 是哪些设置吗，我好像没看到啥设置呀（

难道我看错了？

**Comment by hejiehao** [comment]
你指的是options.txt？

**Comment by ShenXuan233** [comment]
> 我能了解下 该包的设置 是哪些设置吗，我好像没看到啥设置呀（
> 
> 难道我看错了？
![Base Profile Screenshot 2023 07 31 - 13 23 42 52](https://github.com/Hex-Dragon/PCL2/assets/54285600/cfd41a53-1c49-4fdb-ad94-0582dd08fb8e)
![Base Profile Screenshot 2023 07 31 - 13 23 58 12](https://github.com/Hex-Dragon/PCL2/assets/54285600/69fe8fe1-4280-42c0-8c96-074888f9f199)
键位绑定和资源包，这个是正常的（只截了一部分）

**Comment by ShenXuan233** [comment]
> 我能了解下 该包的设置 是哪些设置吗，我好像没看到啥设置呀（
> 
> 难道我看错了？

这是我从curseforge启动器安装的
![Base Profile Screenshot 2023 07 31 - 13 23 42 52](https://github.com/Hex-Dragon/PCL2/assets/54285600/decf981e-09fb-468a-8b11-445289f98e78)
![Base Profile Screenshot 2023 07 31 - 13 23 58 12](https://github.com/Hex-Dragon/PCL2/assets/54285600/adf62a0d-3454-4f87-85e8-6dabfc996d83)
这是从pcl2安装的
![Base Profile Screenshot 2023 08 01 - 12 22 38 39](https://github.com/Hex-Dragon/PCL2/assets/54285600/54dbf1f7-ea81-4adf-bf47-1932c64cdb79)
![Base Profile Screenshot 2023 08 01 - 12 22 54 91](https://github.com/Hex-Dragon/PCL2/assets/54285600/66e1850d-7bb2-4462-8892-e8263fb8b586)
