### ISSUE TITLE
Mod下载添加支持筛选NeoForge功能

### ISSUE THREAD

**Issue by WangSimele** [Hex-Dragon/PCL2#2394]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

灵感来源自Modrinth。现在即便PCL还为支持自动安装NeoForge，但可以通过NeoForge官网下载他们的安装器进行手动安装，但希望提前添加个Mod下载的NeoForge筛选，即支持筛选NeoForge的模组，现在Modrinth网站的Mod下载界面，他们的筛选功能现在支持筛选NeoForge，也同样保留原有的MinecraftForge，希望PCL添加个像Modrinth这样的功能。
![image](https://github.com/Hex-Dragon/PCL2/assets/140716447/c99e5c37-25c8-450d-a6a7-7f1a37a68faf)

### 原因

这项功能有利于知道某个Mod是否支持NeoForge以及是否能在NeoForge正常运行，因为某些Mod还未适配新的NeoForge，添加这个功能，有利于大幅度减小了在NeoForge运行模组是的各种问题

**Comment by LTCatt** [comment]
需要等待 CurseForge 支持

**Comment by zkitefly** [comment]
看到网页搜索有 NeoForge 了，不知道 API 有了没有

![image](https://github.com/Hex-Dragon/PCL2/assets/64117916/563ff6e9-7b94-4807-b29b-ea0b02ea5d9d)

**Comment by LTCatt** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/73cb2003-9cae-49e9-9b1a-10864181d9f9)
CurseForge 的 API 还不支持 NeoForge……

**Comment by zkitefly** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/64117916/e100874d-b6fe-4bf7-a00b-ec0fbb0f4a27)

**Comment by hejiehao** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/98140773/aaac0dd9-8394-404a-b5f1-f1cc09a6d939)
似乎已经支持了
这个是 Rubidium Extra 返回来的， Modid 是 654373 ，FileID 是 4740935

**Comment by hejiehao** [comment]
![image](https://img.kookapp.cn/assets/2023-10/YyZXSo2GxA0ux0nc.png)
想不到 CurseForge 竟然偷偷背着我们加入了 NeoForge 筛选功能
[Bookshelf+NeoForge.txt](https://github.com/Hex-Dragon/PCL2/files/12793138/Bookshelf%2BNeoForge.txt)
把 modLoaderType 设置成 6 之后返回的结果

**Comment by zkitefly** [comment]
一个缺德的事情来了...

![image](https://github.com/Hex-Dragon/PCL2/assets/64117916/f80aa2f9-1db7-4a6d-bee4-fc71ad7d0ec9)

![image](https://github.com/Hex-Dragon/PCL2/assets/64117916/172ba41b-a947-40ba-9dd3-3523499a8b52)

![image](https://github.com/Hex-Dragon/PCL2/assets/64117916/778dbb84-9107-4d51-af4d-e9d311a745a7)

用 ![image](https://github.com/Hex-Dragon/PCL2/assets/64117916/af9d85c2-ce93-4145-8053-440541db9418) 搜索 Bookshelf 且限制为 NeoForge 得出的 json 文件，其中里面的数据正是带 NeoForge 的：[Bookshelf+NeoForge](https://img.kookapp.cn/attachments/2023-10/03/651c163d86ab9.json)

**Comment by zkitefly** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/64117916/ffd5a0fc-35cc-4b40-9da9-22183fc1e106)

**Comment by burningtnt** [comment]
经典文档更新不及时
