### ISSUE TITLE
[新功能] 帮助文档自动同步

### ISSUE THREAD

**Issue by youzi-2333** [Hex-Dragon/PCL2#2396]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

每次启动 PCL 时，尝试从 GitHub 获取最新的帮助文档，保存到缓存，并在用户切出帮助页面时自动刷新。如果获取失败，则使用内置帮助。

### 原因

这样可以方便用户快速获取最新的帮助文档。

**Comment by SALTWOOD** [comment]
> 没必要吧

有这样的必要，可以同步最新的信息

**Comment by SALTWOOD** [comment]
没必要直接获取失败就用内置的，可以在获取失败之后尝试调用缓存

**Comment by SALTWOOD** [comment]
但是记得网络操作要单独一个线程，尤其是GitHub这种国内访问很慢的网站

**Comment by WForst-Breeze** [comment]
帮助库中如有新页面或有页面的大篇幅改动，常常会有一些问题（措辞、排版等）和未完善的内容，尽管在 merge 之前会进行 review，但以上问题还是不可避免的（）所以个人认为手动同步还是最稳妥的

**Comment by LTCatt** [comment]
除此之外，github 在国内的访问情况嘛……
