### ISSUE TITLE
[优化] 一个控件支持运行多个 Event

### ISSUE THREAD

**Issue by youzi-2333** [Hex-Dragon/PCL2#2397]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

允许控件运行多个 Event，例如 `EventType="安装整合包|启动游戏" EventData="{path}整合包.zip|游戏版本"` 安装整合包后启动游戏。

### 原因

这样可以方便制作整合包、客户端等。

**Comment by LTCatt** [comment]
寻思了一下，很不好做，EventData 的参数数量是可变的，并且这个执行的前后顺序并不能像你想像的那样，有的是多线程并行的，没有前后顺序……
