### ISSUE TITLE
支持面向Microsoft账户的Windows单点登录

### ISSUE THREAD

**Issue by idhaname** [Hex-Dragon/PCL2#2404]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

就类似于[Android](https://developers.google.cn/identity/one-tap/android/overview?hl=zh-cn)、[iOS](https://support.apple.com/zh-cn/HT210318)、[Firefox](https://support.mozilla.org/zh-CN/kb/windows-sso)的“一键登录”功能，可以让用户使用本机微软账户快速登录到启动器

### 原因

这样用户就可以使用电脑上登录的微软账户进行快速登录，而无需输入账户密码
（前提是电脑上登录的和购买MC的微软账户要是同一个）

个人建议如果真要做的话，可以先把 #127 的微软登录优化做完后再来考虑这个功能

**Comment by youzi-2333** [comment]
这个做出来的话就无敌了……

不过要看技术上能不能实现.jpg

**Comment by hejiehao** [comment]
这玩意要申请，不好搞

**Comment by idhaname** [comment]
https://help.minecraft.net/hc/en-us/articles/16254801392141p
https://aka.ms/mce-reviewappid

优化 #127 的前提就是申请Azure应用访问正版验证API，所以才要说等微软登录优化完后再来做这个功能

**Comment by LTCatt** [comment]
太难做了这个……
