### ISSUE TITLE
关于1.7.10的英特尔显卡渲染BUG

### ISSUE THREAD

**Issue by ccjj11** [Hex-Dragon/PCL2#2410]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

使用英特尔显卡进入我的世界时，可能会出现花屏和纯色屏的问题。

经过搜索发现，这是因为英特尔新版显卡不再支持旧版OpenGL所导致的。

然而，经过测试发现，在相同的场景下，bakaXL启动器没有出现任何花屏和纯色屏的现象，而PCL2启动器则会出现这些问题。考虑到仍有玩家在使用1.7.10版本的我的世界，希望PCL2启动器能像bakaXL启动器一样修复这个花屏和纯色屏的问题。

### 重现步骤

1.使用最新版英特尔显卡驱动的电脑加载启动1.7.10版本的我的世界
2.进入单人游戏，手持物品
3.移动一段距离摇晃下视角
4.复现√

### 日志与附件

使用英特尔显卡进入我的世界时，可能会出现花屏和纯色屏的问题。

经过搜索发现，这是因为英特尔新版显卡不再支持旧版OpenGL所导致的。

然而，经过测试发现，在相同的场景下，bakaXL启动器没有出现任何花屏和纯色屏的现象，而PCL2启动器则会出现这些问题。考虑到仍有玩家在使用1.7.10版本的我的世界，希望PCL2启动器能像bakaXL启动器一样修复这个花屏和纯色屏的问题。

此外，希望PCL2能继续保持其简单易用的操作界面

1.使用最新版英特尔显卡驱动的电脑加载启动1.7.10版本的我的世界
2.进入单人游戏，手持物品
3.移动一段距离摇晃下视角
4.复现√

**Comment by hejiehao** [comment]
你的电脑里有独显吗？

**Comment by ccjj11** [comment]
有的，但是我希望可以像bakaXL启动器那样，自动处理这个渲染问题，比较省心一点

**Comment by hejiehao** [comment]
> 有的，但是我希望可以像bakaXL启动器那样，自动处理这个渲染问题，比较省心一点

你指的是启动游戏时自动使用独显渲染？

**Comment by ccjj11** [comment]
我希望使用PCL2启动器启动1.7.10的游戏，不会花屏，或者纯色屏，这个好像是openGL的问题，我看到HMCL可以选择软渲染器启动，也可以修复这个情况，我们PCL2可以做一个嘛

**Comment by ccjj11** [comment]
我刚测试了一下发现HMCL的软渲染器启动的1.7.10非常卡，性能很差，还是希望模仿bakaXL启动器那样修复这个情况_(:з」∠)_

**Comment by ccjj11** [comment]
软渲染器只有10~30fps
bakaXL修复的更好，而且没有影响性能

**Comment by ccjj11** [comment]
补充是使用最新版英特尔显卡驱动运行forge版本1614的1.7.10我的世界_(:з」∠)_

**Comment by zkitefly** [comment]
那问题就是 BakaXL 是做了什么才不会这样的呢

难道是 Java 版本？

**Comment by zkitefly** [comment]
如果你有 NVIDIA 显卡，在 NVIDIA 控制面板里按图里顺序改成「高性能 NVIDIA 处理器」，然后点下面的「应用」，最后重启电脑 ![](https://img.kookapp.cn/assets/2023-06/LHqkHeKbD90pr0aw.png)

**Comment by ccjj11** [comment]
![~ `QNQ`A4)2QU2}XPG93%4U](https://github.com/Hex-Dragon/PCL2/assets/53486257/6ba9ccb6-185c-4e20-ad8e-0cdd1f017d99)
![%M1F~F}O`LIB6OJI5`%X5ZW](https://github.com/Hex-Dragon/PCL2/assets/53486257/149b26ff-74d3-49c8-9a50-890002742551)
![B53%N%)580USE~}$J7@E58D](https://github.com/Hex-Dragon/PCL2/assets/53486257/ce61ce22-4c71-4e79-a9c6-7639012acd1a)

**Comment by LTCatt** [comment]
上传启动后的 PCL 日志
使用 BakaXL 启动并上传对应的启动脚本

**Comment by bwtx2023** [comment]
PCL 日志：启动器目录下 PCL 文件夹内的 Log1-5.txt
BakaXL 启动脚本：包含在启动器目录下 BakaXL 文件夹内 Log 文件夹里面的最新 Log 文件，先启动一次再拿出最新的就不用找了

（Off Topic）建议在其他场合不要踩一捧一，容易招骂，也让人对 PCL 用户群体印象不太好...

**Comment by ccjj11** [comment]
[PCL2Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12246881/PCL2Log5.txt)
[BakaXL.zip](https://github.com/Hex-Dragon/PCL2/files/12246955/BakaXL.zip)
我确实做的不对，体验了一下baka 也没有想象的难用，可能是第一次使用baka会直接跟PCL2的简洁性作比较有点过分了，这样做也会给PC2招黑，深感错误给baka道歉，也给PCL2团队道歉，以下是PCL2的log与baka启动器启动后的bakaXL文件夹，希望两个启动器都能共同学习优点，共同进步

**Comment by ccjj11** [comment]
[[2023_08_03_12_48_13]BakaXL_Log.txt](https://github.com/Hex-Dragon/PCL2/files/12246961/2023_08_03_12_48_13.BakaXL_Log.txt)
抱歉这个才是，需要关闭baka启动器才会加载新的文件夹

**Comment by ccjj11** [comment]
[BakaXL.zip](https://github.com/Hex-Dragon/PCL2/files/12246990/BakaXL.zip)
完整的，

**Comment by LTCatt** [comment]
先更新一下 PCL……
这个应该不是启动器的问题……先关了 :/
