### ISSUE TITLE
[Bug] “更多”页面侧边栏背景不合时宜地出现

### ISSUE THREAD

**Issue by Xiaolv114518** [Hex-Dragon/PCL2#2416]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在设置了 `设置` 页面只显示一个子页面， `更多` 页面只显示 `帮助` 子页面的情况下，启动 PCL2 ，先切换到 `设置` 页面，再切换到 `更多（帮助）` 页面，此时侧边栏背景仍会出现，如图。
![image](https://github.com/Hex-Dragon/PCL2/assets/141309773/0199b003-649e-4ade-97e7-82f132d73aa9)

### 重现步骤

1、在 `设置 → 个性化 → 功能隐藏` 选项卡中，先勾选 `设置` 和 `更多` ，再分别取消勾选 `设置 子页面` 的任意一个复选框和 `帮助` 复选框，如图。
![image](https://github.com/Hex-Dragon/PCL2/assets/141309773/9d08b28c-c6ab-49ff-9e36-6a6db72c06a8)

2、重启 PCL2 ，先切换到 `设置` 页面，再切换到 `更多（帮助）` 页面，此时侧边栏背景仍会出现，Bug 被触发。

### 日志与附件

https://wwqt.lanzoum.com/iUip514ah0le
我这边网络环境不好，没法直接上传，所以上传到蓝奏云了

**Comment by LTCatt** [comment]
你的解锁码：kn9VW/erEh+yYyV6IACOtRMOtovmqwUr
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by LTCatt** [comment]
你的解锁码：z3P1Tq31u9m9H7juiQwkml8GNHiXcsjp
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
