### ISSUE TITLE
模组列表中只有部分模组可以正常读取，其它模组显示没权限访问被拒绝

### ISSUE THREAD

**Issue by Mondoawa** [Hex-Dragon/PCL2#2417]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

模组列表中只有部分模组可以正常读取，其它模组显示没权限访问被拒绝，已经给了管理员权限

### 重现步骤

1、使用管理员启动PCL2
2、点击1.20.1-Fabric-0.14.21版本设置
3、点击Mod管理
4、部分mod无权限访问

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12248924/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12248925/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12248926/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12248927/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12248928/Log5.txt)

**Comment by zkitefly** [comment]
PCL 的权限不足。请尝试右键 PCL，选择以管理员身份运行。

**Comment by Mondoawa** [comment]
使用管理员身份运行后还是无法读取

**Comment by hejiehao** [comment]
> PCL 的权限不足。请尝试右键 PCL，选择以管理员身份运行。

![image](https://github.com/Hex-Dragon/PCL2/assets/98140773/a452dc5d-b92c-4ad6-984a-64c3d55241c8)

**Comment by zkitefly** [comment]
那其他版本的模组管理是可以的是吗

**Comment by hejiehao** [comment]
[调权限教程.zip](https://github.com/Hex-Dragon/PCL2/files/12249193/default.zip)
你试试调一下权限

**Comment by Mondoawa** [comment]
emm...调权限应用时部分文件说应用失败，访问被拒绝，但是多了一个mod可以读取了，应该是我电脑的问题或微软系统的bug

**Comment by hejiehao** [comment]
> emm...调权限应用时部分文件说应用失败，访问被拒绝，但是多了一个mod可以读取了，应该是我电脑的问题或微软系统的bug

截个图？

**Comment by Mondoawa** [comment]
![屏幕截图 2023-08-03 174134](https://github.com/Hex-Dragon/PCL2/assets/127531383/20ab2a6f-d6c0-4372-91ad-b65f10fdd479)

**Comment by hejiehao** [comment]
> ![屏幕截图 2023-08-03 174134](https://user-images.githubusercontent.com/127531383/258071277-20ab2a6f-d6c0-4372-91ad-b65f10fdd479.png)

你右键“开始”，点“磁盘管理”，截图我看看

**Comment by Mondoawa** [comment]
![屏幕截图 2023-08-03 175133](https://github.com/Hex-Dragon/PCL2/assets/127531383/c753c320-082f-43a4-8de2-8fc55d85fa80)

**Comment by LTCatt** [comment]
系统环境问题，与启动器无关

**Comment by Yizhouuu** [comment]
> 系统环境问题，与启动器无关

请问具体是什么系统环境问题？
