### ISSUE TITLE
对版本列表的一些修正

### ISSUE THREAD

**Issue by TanChenyu** [Hex-Dragon/PCL2#2418]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

1. 让Combat Test的部分版本能够自动安装Fabric（如Combat Test 7c，在安装器里显示为1.16_combat-3）
2. 将远古版本c0.31改为c0.31 20100130并修正wiki链接

### 原因

第1条：这项优化让我可以更方便地为Combat Test安装Fabric。如果没有这项优化，我每次都必须手动重命名版本以安装Fabric，让操作变得很麻烦。
第2条：修复wiki链接404的bug

**Comment by TanChenyu** [comment]
感觉没修啊，是在快照修的吗？

**Comment by LTCatt** [comment]
还没推送到正式版 :/
