### ISSUE TITLE
登录正版账户后，启动PCL报错；PCL会自动注入文件到我不希望它注入的官方文件夹

### ISSUE THREAD

**Issue by CoolLKKPS** [Hex-Dragon/PCL2#2421]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

---问题 1---
在登录正版账户后，再次启动PCL后就会发生这个错误对话框：
Plain Craft Launcher 2.exe - Bad Image
C:\Windows\assembly\NativeImages_........._64\Present.........\.........\PresentationFramework.Aero2.ni.dll is either not designed to run on Windows or it contains an error. Error status 0xc0e90002.
 ! 系统环境是Windows 11最新版，无IE支持，在此之后登出账号并将界面【切换为】离线启动时，再打开客户端也依旧能触发这个问题，怀疑是加载人物皮肤时出现的问题。
---问题 2---
当Roaming文件夹下有 .minecraft 文件夹时，PCL会自动注入文件至该文件夹并不经过用户同意，这种行为非常不礼貌。

### 重现步骤

你只需要根据我的描述即可重现步骤；
有所补充，发生问题时我安装了LabyMod Launcher并启动了游戏。

### 日志与附件

**Comment by zkitefly** [comment]
关于第二点，你是指什么文件呢，PCL文件夹吗，有些文件和文件夹是为了方便PCL索引文件用的，不会造成什么不良影响

**Comment by zkitefly** [comment]
> 是PCL将一些文件注入到官方游戏安装目录中，这表明PCL已经使用了这个目录 无论是否有影响，这些文件本就不是它原本所属会提供的文件，因为那个目录是官方启动器所创建的，而官方启动器也允许玩家自定义安装目录，换言之，那个目录是属于官方启动器的，而PCL是第三方启动器而不是插件或MOD

你在版本管理里面设置游戏目录为其他的就行了，盲猜你设置游戏目录为官方启动器的目录

**Comment by zkitefly** [comment]
你只要不使用这目录，他应该就不会注入文件了吧

**Comment by LTCatt** [comment]
1 / 你的系统存在问题，部分 dll 文件损坏，与 PCL 无关
2 / PCL 会尝试检测官启文件夹并且列入游戏文件夹列表，暂时不打算加入禁止此功能的设置，因为这对绝大多数的玩家都没有必要

**Comment by SuoHouDaiShi** [comment]
我觉得可能是因为C盘是绝对值罢）
