### ISSUE TITLE
程序出现未知错误:无法找到指定文件 在 PCL.Modsecret.SecretOnApplicationstart0 在 PCL.Application.Application Startup(Object sender, StartupEventArgs e) 错误类型: System.lO.FileNotFoundException

### ISSUE THREAD

**Issue by 2131414421** [Hex-Dragon/PCL2#2425]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

打不开启动器，删除重装也没用，点击反馈问题只给我跳转到github页面和打开Documents

### 重现步骤

1、点击Plain Craft Launcher 2.exe
2、然后
![屏幕截图 2023-08-05 140222](https://github.com/Hex-Dragon/PCL2/assets/108124577/2c49e6a6-2e34-4ca0-a2e1-a1d6b863f12f)

### 日志与附件

重装了之后就一个exe文件，找不到啊

**Comment by zkitefly** [comment]
> 点击反馈问题只给我跳转到github页面和打开Documents

关于这一点，pcl的反馈是转到 github 上的哦

**Comment by zkitefly** [comment]
如果可以的话，请上传启动器日志

**Comment by LTCatt** [comment]
你把 PCL 放在哪了……哪个文件夹下面？
PCL 找不到自己的文件……

**Comment by 2131414421** [comment]
> 你把 PCL 放在哪了......哪个文件夹下面？ PCL 找不到自己的文件......

抱歉，我现在才看到这条消息，我产生这个问题后把PCL卸载后重装了，所以文件夹里只有一个本体
![屏幕截图 2023-08-05 185320](https://github.com/Hex-Dragon/PCL2/assets/108124577/66f2e910-6fc7-45c2-afe9-c2a4e678b9e2)

**Comment by 2131414421** [comment]
> 你把 PCL 放在哪了......哪个文件夹下面？ PCL 找不到自己的文件......

今天下午我玩其它游戏也有报错，我玩GTA5的时候游戏运行两三分钟就无报错直接闪退了，我看在网上查找教程试着用DirectX修复软件检测了DirectX和c++发现 c++ 2015-2022 有问题，然后我尝试手动卸载并修复时弹出ROGLiveService或AcPowerNotification正在运行无法卸载，然后我把电脑上所有与华硕有关的软件卸载之后发现c++ 2015-2022中要修复的文件全部都可以卸载修复了，我也是下午出去之后刚吃完饭回家，就试着看看能不能再打开一次，结果PCL不报错了，我想难道是华硕的锅？
