### ISSUE TITLE
打开 背景音乐-游戏启动后自动暂停播放，退出后自动开启播放 设置后退出游戏有时会弹出 线程执行失败 错误

### ISSUE THREAD

**Issue by MTfriday** [Hex-Dragon/PCL2#2428]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![错误弹窗](https://github.com/Hex-Dragon/PCL2/assets/66195653/9b044ee0-2e93-414d-bb85-085412716b83)
![设置界面](https://github.com/Hex-Dragon/PCL2/assets/66195653/2d89e2f8-3b16-4589-95b3-cad1d482e6a7)

### 重现步骤

我也不知道这个bug怎么触发的……
可能是偶发性错误吧（长时间运行MC后更容易触发？）

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12267471/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12267467/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12267468/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12267469/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12267470/Log5.txt)

**Comment by LTCatt** [comment]
#1753
