### ISSUE TITLE
关于java选择的功能优化建议

### ISSUE THREAD

**Issue by ohxihh** [Hex-Dragon/PCL2#2429]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

有个实用的小功能建议，期待pcl能做一下
java选择，能以pcl所在路径为起始路径，指定java路径，

![X46PVCH3IXYDOH4 9}FPT88](https://github.com/Hex-Dragon/PCL2/assets/123002302/23c96802-3993-4782-ad1b-01a01ea6878e)

### 原因

主要是方便作为整合包或者服务器启动器，
因为各个游戏版本可能需要的java版本可能并不相同
这个功能方便了java直接内置到客户端里，打开pcl时固定调用此java，就不用玩家装安装java了

**Comment by bwtx2023** [comment]
直接把 Java 放进版本文件夹，PCL 就会优先调用了...
