### ISSUE TITLE
刷新自定义主页联网获取到的图片

### ISSUE THREAD

**Issue by HaNWorkspace** [Hex-Dragon/PCL2#2432]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

自定义主页布局Xaml文件中，添加一个可以刷新所有联网获取的图片的功能
可以添加一项按钮的EventType刷新主页的所有联网获取到的图片，或是在刷新主页时一起更新联网获取的图片？

### 原因

我在自定义主页布局Xaml文件中，使用了<Image>并在 Source 使用了一个提供图片的Api网址
但我发现似乎除 重新启动PCL2 外，没有办法刷新所获取到的图片
这使得我必须重新启动PCL2以刷新图片
有了这项优化，我可以更方便的完成这项操作，而不是通过重启PCL2的方式刷新图片

**Comment by LTCatt** [comment]
Source 是 WPF 的底层行为，我无法控制 :/
