### ISSUE TITLE
隐藏更多选项的“帮助”后，暂时关闭隐藏功能后侧边栏无法帮助

### ISSUE THREAD

**Issue by HaNWorkspace** [Hex-Dragon/PCL2#2436]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在设置里设置隐藏帮助后，在“更多”选项卡按F12暂时关闭隐藏功能，侧边栏原本该显示帮助的位置显示为空，但仍可以点击该位置显示帮助页面
“功能隐藏”截图
![image](https://github.com/Hex-Dragon/PCL2/assets/69073248/86f8fffa-c816-47df-9197-62bf365b2642)
“更多”页截图（暂时关闭隐藏功能）
![image](https://github.com/Hex-Dragon/PCL2/assets/69073248/d3b4516d-6bbd-48a8-9cd7-e849a3294ad6)
点击侧边栏空白处截图
![image](https://github.com/Hex-Dragon/PCL2/assets/69073248/81b89c55-d6eb-4751-b9d7-6e79c3cb6cad)

### 重现步骤

1、在功能隐藏处勾选更多子页面中的“帮助”
2、打开“更多”页面
3、按F12暂时关闭隐藏功能

### 日志与附件

[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12269632/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12269633/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12269634/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12269635/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12269636/Log4.txt)

**Comment by JingHai-Lingyun** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/109946426/8821718f-b16c-415c-8b49-67fe44576824)
无法复现，请提供更多信息

**Comment by HaNWorkspace** [comment]
这是一份复现了该bug的完整录像

**Comment by NaOH-HaN** [comment]
PCL识别码 3EC6-DC1D-F561-4291
