### ISSUE TITLE
可以生成启动脚本

### ISSUE THREAD

**Issue by LiuBinzhe** [Hex-Dragon/PCL2#244]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

希望PCL可以像HMCL一样生成游戏的启动脚本，bat格式和psl格式。

### 原因

我需要这个功能来生成启动脚本，这个功能可以让我们在不打开启动器的情况下直接启动游戏。

**Comment by wjlfish** [comment]
看看
PCL\LatestLaunch.bat
这个文件可以满足你的要求吗

**Comment by LiuBinzhe** [comment]
不能，打开显示游戏正在启动，请稍候。
Error opening zip file or JAR manifest missing : authlib-injector.jar
Error occurred during initialization of VM
agent library failed to init: instrument
游戏已退出。
请按任意键继续. . .
@wjlfish

**Comment by LiuBinzhe** [comment]
不能，打开显示：
游戏正在启动，请稍候。
Error opening zip file or JAR manifest missing : authlib-injector.jar
Error occurred during initialization of VM
agent library failed to init: instrument
游戏已退出。
请按任意键继续. . .
@wjlfish

**Comment by wjlfish** [comment]
> 
这感觉就不是启动器的问题了啊，拿着这个报错去百度一下吧，也许和路径有中文有关呢~

**Comment by LiuBinzhe** [comment]
好

**Comment by wjlfish** [comment]
> 好

看，俺的就可以正常启动
![image](https://user-images.githubusercontent.com/47003490/196729035-565a4e41-6fa0-4c8a-9c0c-43f5b1a79e9f.png)

**Comment by LiuBinzhe** [comment]
😮

**Comment by LiuBinzhe** [comment]
![image](https://user-images.githubusercontent.com/115980764/196736023-65df452c-2dd6-4f3f-8025-2c0ff4d0527e.png)
原来是游戏错误了，谢谢

**Comment by wjlfish** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月19日(星期三) 晚上11:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Hex-Dragon/PCL2] 可以生成启动脚本 (Issue #244)





 

 原来是游戏错误了，谢谢

**Comment by HowardZHY** [comment]
导出的错误报告已包含启动脚本

**Comment by Broken-Deer** [comment]
建议不要学明月庄主
