### ISSUE TITLE
在搜索帮助时，键入拼音会显示与之无关的帮助条目

### ISSUE THREAD

**Issue by NorthZeroD** [Hex-Dragon/PCL2#2440]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在最新快照2.6.4版本的启动器中，在更多-帮助-搜索帮助，若在搜索框中键入某个汉字的拼音，会列出与此拼音无关的帮助条目。
如：输入"kai"，搜索列表会列出 "安装数据包" "原版百科" 这两个帮助条目，与"kai"并没有关联。
<img width="608" alt="image" src="https://github.com/Hex-Dragon/PCL2/assets/141613738/46bd9f4c-c20a-4c7d-9ed1-76b0526fd5e1">
"you"
<img width="608" alt="image" src="https://github.com/Hex-Dragon/PCL2/assets/141613738/1fc11887-3357-49dc-a7af-4a189b53d9b9">
我认为应该想方法使用更精确的搜索逻辑。

### 重现步骤

1、点击"更多"
2、侧边栏点击"帮助"
3、右侧页面点击"搜索帮助"，在搜索框键入汉字的拼音，如"kai" "you"

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12273208/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12273209/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12273210/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12273211/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12273212/Log5.txt)

**Comment by NorthZeroD** [comment]
awa

**Comment by zkitefly** [comment]
我记得搜索功能并没有拼音搜索

**Comment by LTCatt** [comment]
kai 是字母 k 匹配到了 datapack 中的 k，还有 wiki 的 i……
没有搜索结果的时候这种低精度匹配无法避免 =。=
拼音搜索不会做的.jpg
