### ISSUE TITLE
游戏自定义内存最高只能64G

### ISSUE THREAD

**Issue by StarlingLin** [Hex-Dragon/PCL2#2444]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在设置-游戏-游戏内存-自定义中，即使将滑动条拖满也只是64G，我希望能够至少提升到96G或者128G。

### 原因

现在DDR5内存时代部分台式机已经到达96G、128G、192G，比如我本人是96G（48Gx2），而当我去玩一些超大的整合包、存档时，我希望能够调用更多的内存来提升游戏体验（已经有超出64G的情况）

**Comment by zkitefly** [comment]
我记得游戏内存调的过高会导致崩溃的（

**Comment by LTCatt** [comment]
目前的情况看来暂无必要……
