### ISSUE TITLE
2.6.3帮助页面下载的xaml代码中有2.6.4才有的事件类型

### ISSUE THREAD

**Issue by UFAGUWHGIQAHUIAGUIWAJFAIUYFUGW** [Hex-Dragon/PCL2#2454]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

2.6.3帮助页面下载的xaml代码中有2.6.4才有的事件类型
（好像不用管，到2.6.4版本就好了？）

### 重现步骤

1、点击更多
2、往下滚，然后点击加入帮助文件夹的xaml代码
3、往下滚，然后点击切换到下载页面按钮

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12299869/Log2.txt)
[XAML%20格式.txt](https://github.com/Hex-Dragon/PCL2/files/12299884/XAML.20.txt)

**Comment by youzi-2333** [comment]
正常，因为下载到的代码都是最新的……
