### ISSUE TITLE
reese的钠视频界面mod下载中的sodium mod下载引导可能需要改善 

### ISSUE THREAD

**Issue by xiao-qwq** [Hex-Dragon/PCL2#2455]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在mod下载中搜"reese的钠视频界面"时，在下载界面中会有一个sodium的下载引导，但引导的界面是courseforge的sodium,这个里面只有1.16.5版本的sodium,而真正需要的是modrinth的全版本sodium,希望能更改下引导
![image](https://github.com/Hex-Dragon/PCL2/assets/72390180/da269382-4eec-4f61-93b0-a01bb76bc9c1)
![image](https://github.com/Hex-Dragon/PCL2/assets/72390180/7dc160da-97ff-4817-9047-c8156b0ffeed)
![image](https://github.com/Hex-Dragon/PCL2/assets/72390180/315bee42-c356-4d6f-9b13-6d1970e35870)

### 原因

（示例）
这项优化让我可以更方便地xxxx。
如果没有这项优化，我每次都必须xxxx，让操作变得很麻烦。

**Comment by xiao-qwq** [comment]
原因
这项优化让我可以更方便地下载这个mod。
如果没有这项优化，我每次都必须单独再去访问modrinth版本的sodium，让操作变得很麻烦。

**Comment by Chiloven945** [comment]
这个实际上是作者的问题，作者在Curseforge上发布内容，但是Curseforge上的Sodium已经不再更新

**Comment by LTCatt** [comment]
这是 mod 作者的问题，你可以向 mod 作者反馈
