### ISSUE TITLE
希望下载引导分类，在同一个mod下分为forge版,fabric版等等版本

### ISSUE THREAD

**Issue by xiao-qwq** [Hex-Dragon/PCL2#2456]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

例如在rei物品管理器mod的下载,点开含双版本的时候会出现"前置mod:XXX API...""可选版本:[forge 1.17.1] V6.x.x    [fabric 1.17.1] V6.x.x" 如图:
![image](https://github.com/Hex-Dragon/PCL2/assets/72390180/73e5dcc8-3ece-43f6-9db3-cc8645dafa14)
出现了两种不同版本，希望是对这一类型的做点更改，变成把forge和fabric版本隔离开，变成forge一栏，fabric一栏的形式,如图:
![image](https://github.com/Hex-Dragon/PCL2/assets/72390180/0ae27400-51bc-4076-bb72-dad25a03fec5)

### 原因

这项优化让我可以更方便地找到我需要的mod，而且更简洁明了,也为后续的新模组加载做准备，因为出了新的加载器会导致这类常用mod的新版mod列表更混乱
如果没有这项优化，我偶尔可能会无法分清forge/fabric的模组，导致下错

**Comment by scattered-leaves** [comment]
或者通过不同底色、图标等方式明显区分forge版和fabric版

**Comment by iPodtouch6557** [comment]
这个功能的意义主要是为眼瞎的人服务，就是看都不看就直接点下载的，确实从一定意义上可以避免一些类似于崩溃的问题……

**Comment by Chiloven945** [comment]
> 这个功能的意义主要是为眼瞎的人服务，就是看都不看就直接点下载的那类人 确实从一定意义上可以避免一些类似于崩溃的问题……

有些前置只针对单个加载器，所以说如果标注不明显经常会出现fabric装成forge模组的情况

**Comment by mike-brown8** [comment]
建议支持类似Curseforge App的一键安装最合适版本的功能，同时支持整合同名mod，从Modrinth安装优先，如果没有则从Curseforge安装，类似下面这样的界面：
<注：这里选了默认CurseForge>
<注：Aa作为版本不同的优选示例>
|名称|版本|来源|安装||
| -- | -- | -- | -- | -- |
|Fabric API|1.0.0|Modrinth & CurseForge|`自动安装[C]`|`手动`|
|Mishang UC|1.0.0|Modrinth|`自动安装[M]`|`手动`|
|Aa|1.0.2|Modrinth & CurseForge[旧]|`自动安装[M]`|`手动`|

预览：
![屏幕截图 2023-09-19 174439](https://github.com/Hex-Dragon/PCL2/assets/87358498/6cbf5ca5-dcd6-4f3f-8e07-27e79853f207)
（仅为示例，并无其他意思）

**Comment by Louis-ZYH** [comment]
此外最好折叠标UNUSED版本的mod（可能有新版本兼容性问题）

**Comment by Chiloven945** [comment]
预期按理来说应该是这样的？
![image](https://github.com/user-attachments/assets/97d06dd6-2c54-4836-a3d2-7c3c73f0a5b0)

**Comment by LTCatt** [comment]
这是为了一起解决有的 Mod 的 Forge 和 Fabric 前置不一样的问题……
