### ISSUE TITLE
打开游戏时进度条卡住

### ISSUE THREAD

**Issue by bili325887326** [Hex-Dragon/PCL2#2457]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在我打开我这个整合包时 不知道是因为我电脑配置不行还是什么其他原因 启动游戏的进度条总是卡在大约90%的地方 然后就动不了

### 重现步骤

打开pcl
点开我自制整合包
进度条卡住

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12305470/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12305471/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12305472/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12305474/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12305475/Log2.txt)

**Comment by Chiloven945** [comment]
不是PCL的问题，请检查你自己的游戏。

**Comment by zkitefly** [comment]
怀疑是你自己的整合包 Mod 过多导致，且日志并没有显示任何报错

![image](https://github.com/Hex-Dragon/PCL2/assets/64117916/d3411df9-e2d7-4918-bfa7-edd8d9c38884)

**Comment by SALTWOOD** [comment]
怀疑是整合包模组过多导致冲突或加载时间过久，有条件请多等一会或者发一下整合包以方便排查问题。
