### ISSUE TITLE
Modrinth的插件可在mod下载中被搜索

### ISSUE THREAD

**Issue by Chiloven945** [Hex-Dragon/PCL2#2458]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/Hex-Dragon/PCL2/assets/116699482/b14b2dd2-60c4-4205-8043-7bfd710c2931)
![image](https://github.com/Hex-Dragon/PCL2/assets/116699482/0e41c34c-c256-49cc-895e-0da1838de708)
![image](https://github.com/Hex-Dragon/PCL2/assets/116699482/324e8023-94fe-4872-a65f-37c76fb93b8c)

如果在mod下载界面搜索一个插件的话能搜索到modrinth中任何的插件的（即使不支持任何mod loader）
感觉是modrinthAPI的问题

### 重现步骤

搜索任意插件

### 日志与附件

-

**Comment by zkitefly** [comment]
怎么说呢，我测试了几俩个启动器，都是会出现这个玩意，怀疑是 API 的问题，不是启动器的问题

![image](https://github.com/Hex-Dragon/PCL2/assets/64117916/6418e70d-e613-4efb-a5ce-ea2abf2591b5)

![image](https://github.com/Hex-Dragon/PCL2/assets/64117916/049c6526-1ccc-4233-8e3e-f13cca3672de)

**Comment by Chiloven945** [comment]
数据包也能
![image](https://github.com/Hex-Dragon/PCL2/assets/116699482/c1e5f0d7-35ff-4fb0-8298-a8e57f7ea377)

**Comment by hejiehao** [comment]
通过所使用的Mod加载器来修这个？

**Comment by SALTWOOD** [comment]
部分插件支持Fabric/Forge加载器，希望可以保留（毕竟有些插件在单人游戏中确实起效）

**Comment by Chiloven945** [comment]
> 部分插件支持Fabric/Forge加载器，希望可以保留（毕竟有些插件在单人游戏中确实起效）

这个应该肯定，毕竟某种意义上它们也算模组（

------

> 通过所使用的Mod加载器来修这个？

一些较旧版本的模组没有标注为什么加载器，因为那个时候只有forge。不过鉴于这个问题只出现在cf上，所以说只需要使mr来源且没有使用任何mod加载器的屏蔽掉。
