### ISSUE TITLE
[Bug] 功能隐藏后，按 F12 有概率无法加载次要页面的选项

### ISSUE THREAD

**Issue by youzi-2333** [Hex-Dragon/PCL2#2461]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

将部分功能隐藏，按下 F12，此时启动器左侧的次要页面选项有概率不被加载，但是可以点击。

截图没了，反正就是 游戏 个性化 启动器 这些选项变成了一片空白，切到 更多 页面，再切回去就好了………………

### 重现步骤

1. 开启功能隐藏，将 个性化、启动器 设置全部隐藏
2. 在设置页面按下 F12
3. 问题出现

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12317861/Log1.txt)
[Setup.ini](https://github.com/Hex-Dragon/PCL2/files/12317862/Setup.ini.txt)

**Comment by LTCatt** [comment]
与 #2436 实质为同一个 bug
