### ISSUE TITLE
无法加载设置为只读的背景图片

### ISSUE THREAD

**Issue by idhaname** [Hex-Dragon/PCL2#2464]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

将背景图片的属性更改为只读后，打开PCL2或点击 设置-个性化-刷新背景图片 即报错“访问被拒绝”，即使根据提示以管理员身份运行也没用
![图片](https://github.com/Hex-Dragon/PCL2/assets/68469786/d47cd482-1724-4ca3-ba8d-cd2ba801df29)

### 重现步骤

右键放在PCL\Pictures下的图片文件，点击属性，勾选上“只读”并应用
![图片](https://github.com/Hex-Dragon/PCL2/assets/68469786/542e73d7-12a9-4dbe-88db-59febfc90679)
随后打开PCL2或点击 设置-个性化-刷新背景图片 即可看到报错，若将图片取消勾选只读则恢复正常

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12319250/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12319249/Log2.txt)

**Comment by LTCatt** [comment]
自己作的不处理 =。=

**Comment by hejiehao** [comment]
> 

好像微信是只读的
