### ISSUE TITLE
在 Mod 下载和管理页面添加 客户端需装/服务端需装 显示

### ISSUE THREAD

**Issue by Wind-Rise** [Hex-Dragon/PCL2#2467]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

在下载时弹出资源管理器时，我需要对文件进行重命名以达到快速标记MOD的目的
因此，我希望PCL II能在MOD详情页的单个文件下载按钮右侧添加一个S和C的按钮或者图标
### 举例
在按下S时，PCL II可以自动将文件的开头第一个字母设定为S(Server)
在按下C时，PCL II可以自动将文件的开头第一个字母设定为C(Client)
### 表现
假设我需要下载一个名为CREATE（机械动力）的MOD
进入详情页，找到该MOD
在按下S时，PCL II弹出的资源管理器中对文件的命名
从默认的"**[机械动力] create-1.18.2-0.5.1.c.jar**"**变为"S-机械动力-create-1.18.2-0.5.1.c.jar**"
同理，在按下C时，PCL II弹出的资源管理器中对文件的命名
从默认的"**[机械动力] create-1.18.2-0.5.1.c.jar**"变为"**C-机械动力-create-1.18.2-0.5.1.c.jar**"
### 就像下面这样
![auto](https://github.com/Hex-Dragon/PCL2/assets/119858176/be1ecfea-1829-4cf1-9d6e-0fb69630eb26)

或者后续也可以给龙猫来一个Pull Request？（小声）
我的代码很屎（超小声）

### 原因

我是一个(划掉)很多私服的腐竹，在收集MOD的时会优先选择通过PCL II进行MOD检索以及下载。我非常高兴PCL II提供了一个前往MCMOD/CourseForge等网站的按钮，可以让我快速检索该MOD是否需要服务器和客户端双端安装等细节。

但在下载时弹出资源管理器时，我需要对文件进行重命名以达到快速标记MOD的安装需求，这就会显得相对繁琐。
因此，我希望PCL II能在MOD详情页的单个文件下载按钮右侧添加一个S和C的按钮

**Comment by SALTWOOD** [comment]
不一定会加，毕竟PCL是针对客户端
可能会拒绝（？

**Comment by LTCatt** [comment]
暂不考虑，抱歉

**Comment by LTCatt** [comment]
经过了一些调查，Mod 作者错误标注 仅客户端/仅服务端 的情况实际上非常多，所以从 CF/Modrinth 获取到的信息也经常有误。

不过，现在已经有一个 Mod 实现了识别功能：https://www.mcmod.cn/class/16080.html
它的实现方式是……它 **手动维护** 了一份列表，列出了所有被 Mod 作者错误标注的 Mod……
![image](https://github.com/user-attachments/assets/9c5ede5b-a235-43db-90a3-e6e5a7a983d6)

考虑到 API 提供的信息都不够准确，由 PCL 来做类似的事情（手动维护列表）也不太现实，不再考虑制作该功能。如果有需要可以自行下载上面提到的这个 Mod。

**Comment by Wind-Rise** [comment]
？我的issue怎么突然活了然后又突然似了

**Comment by Wind-Rise** [comment]
好吧，学业问题一直没关注，感谢

**Comment by TeaClearInkII** [comment]
我写了一个脚本，比那个mod好用，虽然不一定准确，但是可以减少大量工作[我的世界模组端属分析工具](https://github.com/TeaClearInkII/Minecraft-ModSide-Analyzer)以及[文件夹内容比较工具](https://github.com/TeaClearInkII/Folder-Comparator-GUI)

**Comment by Wind-Rise** [comment]
？先说句谢谢贡献，但是我的issue怎么又突然活了然后又突然似了（
