### ISSUE TITLE
离线正版皮肤导致的玩家存档回溯问题

### ISSUE THREAD

**Issue by Epc997** [Hex-Dragon/PCL2#2469]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

一开始玩的整合包，发现的问题是：在游戏途中保存并退出到标题界面，再进入游戏就发现自己的位置不对了，身上的东西也都不对了，似乎回到过去了。
重下了个纯净的游戏，未安装任何mod。测试了一下，确认是正版皮肤的问题。
游戏版本1.12.2+Forge+Optifine。

### 重现步骤

1、离线账户起个名字比如说我叫D，皮肤是默认的史蒂夫头像，启动游戏，新建一个世界，进去之后走开一段距离，撸一块木头，然后退出游戏。
2、这时我想换个离线皮肤，我点头像 - 离线皮肤 - 正版皮肤，输入一个正版玩家名比如我输入Dog，回到启动器首页我发现头像变成了狗，很好。
3、然后我启动游戏，进入刚才的世界发现我位置在出生点，身上什么东西也没有。
4、按Esc保存并退出到标题画面，然后再进入刚才的世界，神奇的是我又回到步骤1的位置了，身上东西也回来了。
5、尝试过只改离线账户的名字不改皮肤，并未发现类似的问题，只改名字并不会新建一个角色。

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12324325/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12324327/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12324328/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12324329/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12324330/Log5.txt)

**Comment by youzi-2333** [comment]
ummmmmmmm 正版皮肤本来的设置是 uuid 和皮肤会同时更改，造成回档也正常……
不知道能不能修。

**Comment by LTCatt** [comment]
无解，没法修 =、=
