### ISSUE TITLE
添加默认设置关闭自动跳跃

### ISSUE THREAD

**Issue by ShiroNeri4u** [Hex-Dragon/PCL2#2470]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

就像辅助功能里游戏语言可以设置中文一样，为游戏设置关闭自动跳跃

### 原因

每次安装新游戏(选择了版本隔离的情况下)总是需要到设置里去设置关闭自动跳跃,尽管Mojang在1.20版本以上默认禁用了自动跳跃

**Comment by Chiloven945** [comment]
跟 #1353 比较相似？

**Comment by ShiroNeri4u** [comment]
看起来相似，但在有mod的情况下option文本共享可能会出问题，因为按键绑定也是记录在option里的，这个建议仅针对高版本中的自动跳跃选项

**Comment by ShiroNeri4u** [comment]
> 跟 #1353 比较相似？

虽然相似但还是有区别的，自动跳跃仅仅是一个选项并非整个配置文件
