### ISSUE TITLE
切换页面可以卡出未删减完的联机模块

### ISSUE THREAD

**Issue by shiyang0510** [Hex-Dragon/PCL2#2471]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在快照版2.6.4龙猫新增【切换页面】这一项自定义功能，我在测试个人自定义主页时意外发现，将 `local:MyButton` 这一控件中的
`EventData` 设置为`EventData="3|3"` 就会卡出联机页面（下图所示）
---
![img.png](https://gitee.com/csy0519/pcl-KZ/raw/main/BBNC(_J%60%5BA%5BG%60W6ISJH)PTT.png)
---

### 原因

这项优化，可以使玩家更好的使用自定义主页\
没有这项优化，就会导致自定义主页的模块并不完整\
用户体验不够舒适

**Comment by zkitefly** [comment]
顺便上传下日志吧，方便龙猫修

**Comment by shiyang0510** [comment]
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12326666/Log1.txt)

**Comment by iPodtouch6557** [comment]
可以复现，文件太大扔蓝奏云吧，https://wwig.lanzoub.com/iTSzy1572lxa （里面混了个音乐文件别管，我用的旧文件夹，懒得删）
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12327471/Log1.txt)
log在此~

**Comment by SALTWOOD** [comment]
这个估计勉强算Bug，复现成功

**Comment by LTCatt** [comment]
反正没法用……
