### ISSUE TITLE
更好的个性化主页

### ISSUE THREAD

**Issue by yznqzty** [Hex-Dragon/PCL2#2473]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

基于 #1369
希望能增加几个内置的主页预设
能够设置更好的个性化设置肯定更好
（一点小意见：能够支持 `HTML`、`CSS`和`JavaScript`当然最好）

### 原因

主页太空，个性化程度不太高...

**Comment by LTCatt** [comment]
之后会开放投稿的，下个版本已经加了几个预设了，还没发 =。=

**Comment by yznqzty** [comment]
那更好的主页（个性化程度更高的）呢？

**Comment by JingHai-Lingyun** [comment]
期待中...
现有的个性化主页不太好做一些复杂的界面
