### ISSUE TITLE
”打开帮助“ 按钮在打开网上的主页时发送的 Http 请求中缺少一些 Header

### ISSUE THREAD

**Issue by Light-Beacon** [Hex-Dragon/PCL2#2476]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

”打开帮助“ 按钮发送的Header
![image](https://github.com/Hex-Dragon/PCL2/assets/49828867/3ca2533b-19ce-433b-b7a8-49eb511746ea)
正常打开联网更新主页发送的Header
![image](https://github.com/Hex-Dragon/PCL2/assets/49828867/862a96db-d846-4e36-9aac-7b3ae045fc8f)

### 重现步骤

可以用下边的代码测试：
```XAML
<local:MyButton Text="打开" EventType="打开帮助" EventData="https://news.bugjump.net/News.json" />
```

### 日志与附件

无

**Comment by SALTWOOD** [comment]
缺了Host？
