### ISSUE TITLE
1.12.2窗口分辨率错误

### ISSUE THREAD

**Issue by Echo-Yuanye** [Hex-Dragon/PCL2#2478]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我在设置中将游戏窗口设为自定义：1600*900，但启动1.12.2窗口大小不是1600*900，通过导出启动脚本可以看到游戏实际的大小是861*1598，其它的任何版本都没有出现这个情况，只有1.12.2出现了，且重下也是一样，不是后来才出现的问题，刚设置完就出现了

### 重现步骤

有什么步骤吗？单纯就是把游戏窗口设为1600*900
![屏幕截图 2023-08-12 224625](https://github.com/Hex-Dragon/PCL2/assets/142103233/39ee6470-646b-47ce-a2f7-1b352e829091)
打开1.12.2实际上是
![屏幕截图 2023-08-12 224817](https://github.com/Hex-Dragon/PCL2/assets/142103233/4f567ed2-915d-43a2-bfa1-ce07813c8a0f)
通过启动脚本可以看到
![屏幕截图 2023-08-12 224943](https://github.com/Hex-Dragon/PCL2/assets/142103233/a94df614-5290-4c24-90d9-e5fa8354fefd)
启动脚本
[启动 1.12.2-Forge_14.23.5.2860-OptiFine_G5.zip](https://github.com/Hex-Dragon/PCL2/files/12327578/1.12.2-Forge_14.23.5.2860-OptiFine_G5.zip)

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12327581/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12327582/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12327583/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12327584/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12327585/Log5.txt)

**Comment by zkitefly** [comment]
应该是故意的，应该是剔除窗口边框大小

**Comment by SALTWOOD** [comment]
你写错了，是1598ⅹ861
是故意剔除边框吧

**Comment by Echo-Yuanye** [comment]
> 你写错了，是1598ⅹ861 是故意剔除边框吧
应该是我写错了，反正启动游戏后，游戏窗口像图片那样很扁，肯定不是我设置的大小

**Comment by SALTWOOD** [comment]
Forge版本？

**Comment by Echo-Yuanye** [comment]
> Forge版本？

重下换一个forge版本也是一样

**Comment by Echo-Yuanye** [comment]
1.12.2大小：
![屏幕截图(107)](https://github.com/Hex-Dragon/PCL2/assets/142103233/d59ec02b-170f-4a48-a68e-5de044cb4e8f)
1.20.1大小：
![屏幕截图(108)](https://github.com/Hex-Dragon/PCL2/assets/142103233/80fd1601-44b9-46bf-b82c-61f1832b1f9b)

**Comment by SALTWOOD** [comment]
复现成功，但是原版无法复现

**Comment by SALTWOOD** [comment]
这个问题估计与PCL无关

**Comment by Echo-Yuanye** [comment]
> 复现成功，但是原版无法复现 似乎是1.12.2Forge通病，我以前也遇见过

好吧

**Comment by SALTWOOD** [comment]
你在调整大小时悬停鼠标，有提示的
关了吧

**Comment by Echo-Yuanye** [comment]
> 你在调整大小时悬停鼠标，有提示的 关了吧

第一次用，怎么关

**Comment by SALTWOOD** [comment]
Close issue，下面

**Comment by SALTWOOD** [comment]
右边的小箭头，点灰色圆圈加一个斜杠的

**Comment by Echo-Yuanye** [comment]
> Close issue，下面



> 右边的小箭头，点灰色圆圈加一个斜杠的

thanks
