### ISSUE TITLE
PCL2启动设置移动

### ISSUE THREAD

**Issue by IKUN05648** [Hex-Dragon/PCL2#2482]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在启动页的左侧，弄一个按钮，打开后会有PCL2设置里的（单独的页面）

### 原因

在闲着没事，打开PCL2时，总感觉少了什么，仔细一看却发现没什么东西是缺的，直到今天，才发现...启动页的左边，是不是有点空啊

**Comment by IKUN05648** [comment]
描述里是“打开后会有PCL2设置里的启动选项“，没写上去

**Comment by zkitefly** [comment]
那个页面是用来自定义主页的
