### ISSUE TITLE
模组包选装模组列表

### ISSUE THREAD

**Issue by zleeeeeee** [Hex-Dragon/PCL2#2483]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [x] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

**#安装模组包时，选装模组做一个列表，加上多选**
有些模组包选装模组很多，比如“Create Extra Full 1.2.0”
有了这项优化可以**更快选择选装模**组然后可以**更快安装好模组包**
没有这优化每次安装选装**模组较多**的模组包，想要或者不想要哪个模组还要一个一个点

### 原因

（示例）
这项优化让我可以更方便地xxxx。
如果没有这项优化，我每次都必须xxxx，让操作变得很麻烦。

**Comment by zleeeeeee** [comment]
好吧。。。因为我的视力原因误认为“原因”文字框仅仅作为格式提示

**Comment by LTCatt** [comment]
选装内容还没有统一的交互方面的 API 约定，暂不考虑
