### ISSUE TITLE
1.8.9启动时出现bug

### ISSUE THREAD

**Issue by superlxy** [Hex-Dragon/PCL2#2491]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/Hex-Dragon/PCL2/assets/142217764/25dc691e-19ba-41ee-aac0-86895b2d30f9)
![image](https://github.com/Hex-Dragon/PCL2/assets/142217764/8e004712-42c7-4db3-b9c9-ae3a19fd3d43)
如图所示，可以启动打开但界面出现错乱，pcl启动器没有出现崩溃等提示

### 重现步骤

1、点击启动PCL1.8.9
2、打开就出现了如图所示的情况

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12333631/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12333633/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12333635/Log3.txt)

**Comment by superlxy** [comment]
刚刚又试了一下发现所有1.8.x和1.7的版本都会出现一样的问题

**Comment by superlxy** [comment]
好像低版本都会这样，不知道怎么回事，求解

**Comment by iPodtouch6557** [comment]
请问是否有安装模组加载器等修改原 Minecraft 内容的东西？还是说纯原版就行？
另外ps：纯原版复现失败
![image](https://github.com/Hex-Dragon/PCL2/assets/118656946/b23003d0-2dff-4fa9-96d4-8f01d4234922)

**Comment by hejiehao** [comment]
装个Forge
~~你会发现反而装个Forge就可以了~~

**Comment by iPodtouch6557** [comment]
安装了一个1.8.9的forge仍然复现失败（未安装mod）
![image](https://github.com/Hex-Dragon/PCL2/assets/118656946/072ebebe-d179-4059-b9c9-2f90caf802d6)
1.7.10同样失败
![image](https://github.com/Hex-Dragon/PCL2/assets/118656946/5a43be61-ebd9-441c-be71-b370bafc9694)
我再看看日志里你有装什么mod吧

**Comment by hejiehao** [comment]
不是，我说的是你装个Forge就可以修这个问题（

**Comment by iPodtouch6557** [comment]
就是纯原版出错，装个forge就好了是吧

**Comment by hejiehao** [comment]
> 就是纯原版出错，装个forge就好了是吧 edit：看日志里启动1.8.9时用的是Java17，指定一个java8？

对，装个Forge就好了

**Comment by superlxy** [comment]
> 请问是否有安装模组加载器等修改原 Minecraft 内容的东西？还是说纯原版就行？ 另外PS：纯原版复现失败 ![image](https://user-images.githubusercontent.com/118656946/260420789-b23003d0-2dff-4fa9-96d4-8f01d4234922.png)

没有装，纯原版

**Comment by hejiehao** [comment]
> > 请问是否有安装模组加载器等修改原 Minecraft 内容的东西？还是说纯原版就行？ 另外PS：纯原版复现失败 ![image](https://user-images.githubusercontent.com/118656946/260420789-b23003d0-2dff-4fa9-96d4-8f01d4234922.png)
> 
> 没有装，纯原版

你试一下装个Forge

**Comment by LTCatt** [comment]
这应该不是启动器导致的问题……

**Comment by iPodtouch6557** [comment]
> 这应该不是启动器导致的问题……

提供理论支持：Betacraft启动b1.9-1.5时期的版本会出现类似但不完全一样的情况
可能是Minecraft本题的问题
