### ISSUE TITLE
赞助名单建议

### ISSUE THREAD

**Issue by SuoHouDaiShi** [Hex-Dragon/PCL2#2493]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

对赞助名单中**疑似个人信息**的用户名进行脱敏处理。
例如下图：
![exp1](https://github.com/Hex-Dragon/PCL2/assets/119282947/d13d5b21-de93-4855-92b3-714bd144ef04)

### 原因

PCL2 2.6.3正式版中的赞助名单有一些爱发电用户名称**疑似个人隐私信息**，给某些人创造了可乘之机。
![exp3](https://github.com/Hex-Dragon/PCL2/assets/119282947/7bd5ecf6-05b8-4b9b-bd6f-5dd4571c2ab9)
![exp4](https://github.com/Hex-Dragon/PCL2/assets/119282947/614203f6-1761-4b16-81c0-eb57420a5bb2)
![exp2](https://github.com/Hex-Dragon/PCL2/assets/119282947/4db78bba-5bd1-45cd-bdbd-6d34114de7f2)
（无意间发现的

**Comment by SuoHouDaiShi** [comment]
不对啊，这样一想工作量反而变大了，草

**Comment by Chiloven945** [comment]
自己不保护好个人信息还指望别人=。=
这群人是有多不知道现在这个时代信息有多重要
