### ISSUE TITLE
在删除了一个列入收藏夹的版本后快速使用相同名称重装该版本，有可能导致这个新安装的版本被自动列入收藏夹

### ISSUE THREAD

**Issue by iPodtouch6557** [Hex-Dragon/PCL2#2495]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在删除了一个列入收藏夹的版本后快速使用相同名称重装该版本，有可能导致这个新安装的版本被自动列入收藏夹
例如，我安装了一个整合包叫Antimatter chemistry，使用了AC1.4.4的名称，由于未知原因的崩溃我删除重装了版本，我在删除时并未撤销其收藏夹
然后我就发现重装后莫名其妙把我重新装的那个版本列入收藏夹了
（另有崩溃问题见 #2496 ）

### 重现步骤

1、安装一个版本，将其加入收藏夹
2、删除该版本，并使用相同名称再下载一个完全相同的版本（比如我删除了一个装载forge的1.8.9并使用1.8.9-Forge的名称，那就装载相同的版本、mod加载器、以及使用相同名称）（建议速度快一点）
3、bug复现

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12335860/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12335861/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12335864/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12335865/Log4.txt)

**Comment by weiqi114514** [comment]
我有一次卸载了一个在收藏夹的版本然后在回收站还原也会重新在收藏夹里

**Comment by zkitefly** [comment]
这，特意的可能不会修？
