### ISSUE TITLE
默认在PCL配置文件夹下创建自定义下载文件夹

### ISSUE THREAD

**Issue by iPodtouch6557** [Hex-Dragon/PCL2#2498]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

例如：我的PCL程序文件路径为C:\Users\23333\Desktop\新建文件夹\，此时的PCL配置文件夹就在 Desktop\新建文件夹\PCL，那么就默认把自定义下载的目标文件夹设为PCL文件夹下的Downloads

### 原因

这项优化可以把下载整齐化和规范化，省的某些人不知道把文件下载到哪里去找不着
也不用动脑子想放在哪个文件夹合适

**Comment by LTCatt** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/da826dc5-9416-4b24-84fc-7ec308e12c3a)
这都找不到文件放哪了还是埋了吧……
