### ISSUE TITLE
在“下载”-“Minecraft”中添加版本收藏功能

### ISSUE THREAD

**Issue by FloriLilio** [Hex-Dragon/PCL2#2499]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

类似这样
![图示](https://github.com/Hex-Dragon/PCL2/assets/135401008/1feb007f-c03d-429a-a529-e1b6acec4ac5)

### 原因

mc版本数量日益增多
这项优化让我可以更方便地下载需要的mc版本。
如果没有这项优化，我每次都必须展开“正式版”列表，一直滚动直到找到想要的比较老的版本，让操作变得很麻烦。

**Comment by hejiehao** [comment]
好像搜索功能被拒了，这个盲猜会被拒

**Comment by SALTWOOD** [comment]
能加而且不难，看需求量吧估计

**Comment by LTCatt** [comment]
没啥需求量……
