### ISSUE TITLE
windows系统内存泄漏后无法启动mincraft

### ISSUE THREAD

**Issue by UPbixiong** [Hex-Dragon/PCL2#2501]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

启动到等待游戏窗口出现时报错

### 重现步骤

1、系统蓝屏（报错码：memory_****）
2、重启跳过磁盘检测
3、启动MC

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12341064/Log2.txt)

**Comment by zkitefly** [comment]
这关 PCL 什么事？

**Comment by SALTWOOD** [comment]
没有其他日志吗？我没记错的话日志是1最新5最老哦
如果能稳定复习顺带提供蓝屏代码
不能稳定复现可能神来了都修不好
大概率是你电脑的问题

不过还是等龙猫过来看看吧.png
