### ISSUE TITLE
如果多开Minecraft，打开启动器点击右下角的"关闭运行中的Minecraft"，那么其他的运行的Minecraft将无法从启动器关闭

### ISSUE THREAD

**Issue by Haoxingniceboy** [Hex-Dragon/PCL2#2505]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

双开或多开minecraft，那么，如果从启动器关闭一个运行中的minecraft，那么其他运行中的minecraft则无法从启动器关闭
如果我开一个1.19版本的Minecraft和再开1.20版本的Minecraft，那么启动器关闭的则是1.20，而1.19则无法从启动器强制关闭
多开也是按照先后顺序关闭第一个Minecraft
如果开1.19版本的Minecraft和再开1.19版本的Minecraft，那么启动器关闭的也是第二个1.19版本的Minecraft，而另一个1.19版本的Minecraft则无法从启动器强制关闭。

### 重现步骤

1、点击启动任意版本的Minecraft
2、再点击启动任意版本的Minecraft
3、在启动完成后在PCL2的启动页面的右下角关闭一个Minecraft
4、关闭Minecraft选项将不见，另一个运行中的Minecraft则无法从启动器强制关闭！

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12354179/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12354181/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12354182/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12354183/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12354184/Log5.txt)

**Comment by Chormore-EDGE** [comment]
是不是和#1223 一样

**Comment by iPodtouch6557** [comment]
> 是不是和#1223 一样

他本人的意思是：这是一个bug，单独关闭不是预期行为
所以不重复

**Comment by Haoxingniceboy** [comment]
OH
yes，sorry






                       
原始邮件
                       
                     

发件人："刘宇儿"< ***@***.*** &gt;;

发件时间：2023/8/16 10:37

收件人："Hex-Dragon/PCL2"< ***@***.*** &gt;;

抄送人："XinG Hao"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [Hex-Dragon/PCL2] 如果多开Minecraft，打开启动器点击右下角的"关闭运行中的Minecraft"，那么其他的运行的Minecraft将无法从启动器关闭 (Issue #2505)




  
是不是和#1223 一样
  
他本人的意思是：这是一个bug，单独关闭不是预期行为
 所以不重复

**Comment by Chormore-EDGE** [comment]
噢
懂了
正常是全部关闭
而现在是单独关闭？

**Comment by iPodtouch6557** [comment]
对，他本人是这个意思，本来单独关闭的功能并未加入，而且他也是作为bug交的issue

**Comment by Chormore-EDGE** [comment]
~感觉bug要被当新功能了.gif~

**Comment by youzi-2333** [comment]
无法复现。请确认两个 Minecraft 都使用 PCL 启动，并且启动第一个游戏后没有关闭过 PCL。

**Comment by LTCatt** [comment]
实质与 #1223 重复
