### ISSUE TITLE
屏幕关闭再次打开后Minecraft游戏无声音

### ISSUE THREAD

**Issue by Zojekin** [Hex-Dragon/PCL2#2506]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

正常启动后游戏内声音正常，但电脑息屏（未休眠）再次打开继续游戏会发现游戏内没有声音。

### 重现步骤

1 正常启动游戏
2 保持游戏运行，等待屏幕关闭（不是休眠）
3 再次打开，会发现没有声音

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12354332/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12354333/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12354334/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12354335/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12354336/Log2.txt)

**Comment by JingHai-Lingyun** [comment]
这... 不是启动器~~能解决~~的问题吧

**Comment by zkitefly** [comment]
盲猜是游戏的问题，与启动器无关

你试试用其他的启动器看看有没有问题

**Comment by got991** [comment]
你的显示器带音频吗
~~可能是神奇的问题~~
我之前把HDMI线拔了再插上就会这样

**Comment by SALTWOOD** [comment]
是笔记本还是台式
如果音响与显示器分开正常是不会这样的
一体式的则是因为显示器关闭之后与电脑断开连接，自然音响也不会工作
而应用程序不会在重新连接音频输出设备之后自动继续

参考MP3拔掉耳机插回去没声音，差不多的意思

归根究底要么是Minecraft 要么是系统的锅（也许是）

等一个有write access的人来看看.bmp

**Comment by SALTWOOD** [comment]
好像与PCL2无关，真的有需求去[MOJIRA](bugs.mojang.com)反馈（不是

**Comment by youzi-2333** [comment]
这……………………
启动器多半解决不了……
也可以看楼上说法，参考切换蓝牙耳机没有声音，差不多一个道理……

要不让龙猫看看？

**Comment by LTCatt** [comment]
这个不是启动器导致的问题 :/
