### ISSUE TITLE
支持导入 schematic / nbt / schem 文件

### ISSUE THREAD

**Issue by got991** [Hex-Dragon/PCL2#2507]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

拖入 schematic / nbt / schem 文件，添加该文件到所有存档的schematics文件夹

### 原因

~~反正就是懒得自己放进去~~
可以更方便的导入结构文件

**Comment by SALTWOOD** [comment]
等龙猫.png
确实有很多人有这样的需求

**Comment by Big-Cake-jpg** [comment]
大概率不会做。

**Comment by zkitefly** [comment]
这不就是 nbt 编辑器了吗（不知道🤷‍♀️

**Comment by Chiloven945** [comment]
资源包都被拒绝了别说原理图这种基本上很少人用上的东西了

**Comment by SALTWOOD** [comment]
不一定会做
