### ISSUE TITLE
[FUNC]支持自定义“版本设置”中的“快捷方式”

### ISSUE THREAD

**Issue by SALTWOOD** [Hex-Dragon/PCL2#2508]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [x] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

允许用户自定义“版本设置”中的“快捷方式”，以支持如replay_recordings、shaderpacks、resourcepacks、schematics等文件夹的打开

~或是支持更多的“快捷方式”？~ 似乎更麻烦（

### 原因

手动打开文件夹真的很麻烦，添加此功能可以更方便导入文件。
对有特殊需求的玩家比较友好

**Comment by LTCatt** [comment]
适用的人员范围小，收益更小，暂不考虑制作 :/

**Comment by JingHai-Lingyun** [comment]
或许你可以考虑使用自定义主页来完成此项操作？
令打开文件夹按钮 `Eventdata="{verpath}/文件夹名字"` 就能完成~
