### ISSUE TITLE
自定义主页内local:MyTextButton的属性Foreground在光标扫过后失效

### ISSUE THREAD

**Issue by IambicCave** [Hex-Dragon/PCL2#2510]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

local:MyTextButton的属性Foreground工作时会受到光标影响，即光标扫过后（高亮后）无法恢复原本设定的颜色，而是变成黑色。我录制了GIF作为详细过程。

### 重现步骤

1、Custom.xaml中写入如：
<local:MyCard Title="标题" Margin="0,0,0,15" CanSwap="True" IsSwaped="True">
    <StackPanel Margin="25,40,23,15">
        <local:MyTextButton Margin="0,8,15,0" HorizontalAlignment="Left" Background="{DynamicResource ColorBrush3}" Foreground="#FFFFFF" Text="文本" EventType="复制文本" EventData="复制内容" />
    </StackPanel>
</local:MyCard>
2、光标移动到TextButton的位置

### 日志与附件

![1](https://github.com/Hex-Dragon/PCL2/assets/79430466/a9232498-733e-403f-9819-b6c79d10e8c2)

**Comment by SALTWOOD** [comment]
问题似乎出在 MyTextButton.vb

**Comment by SALTWOOD** [comment]
![1692190012659](https://github.com/Hex-Dragon/PCL2/assets/105980161/87341e95-587e-4053-8059-4817535b31ce)

Controls/MyTextButton.vb, 60-72行（似乎是）
[快速跳转](https://github.com/Hex-Dragon/PCL2/tree/main/Controls/MyTextButton.vb#70-72)

**Comment by LTCatt** [comment]
它并不支持自定义 Foreground 属性（即使你这样写它不会报错），新版帮助文档会把它的 Foreground 相关描述删了 :/
