### ISSUE TITLE
[BUG] Runtime Invoke 线程执行失败

### ISSUE THREAD

**Issue by SALTWOOD** [Hex-Dragon/PCL2#2517]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

刚更新完就出问题
就一个弹窗，取消之后也没啥事
看了日志估计和音乐播放有关
也许是因为以前设置了音乐播放的原因

### 重现步骤

1、启动游戏
2、在启动器右下角出现强制关闭游戏按钮时关闭游戏（或取消启动）
3、弹窗提示

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12375241/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12375243/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12375244/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12375245/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12375246/Log5.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12375247/Log2.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12375248/Log1.txt)

**Comment by SALTWOOD** [comment]
似乎更新前的2.6.4没有这个问题，龙猫大大可以查查最近的更改

**Comment by LTCatt** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/09e29d06-a549-4996-8793-eaf55437e9ec)
已确认

**Comment by kndxhz** [comment]
刚想提交就看见了，我今天出现了好多次这个报错😥

**Comment by SuoHouDaiShi** [comment]
> 刚想提交就看见了，我今天出现了好多次这个报错😥

估计是龙猫把啥东西搞炸了就这样了 等修复吧

**Comment by SALTWOOD** [comment]
> 刚想提交就看见了，我今天出现了好多次这个报错😥

临时修复方法：先在音乐文件夹放一个音乐文件，然后回到启动器，把背景音乐里的游戏启动后开始播放音乐和游戏未运行时播放音乐关掉，再把音乐文件删了

反正我这么整就好了，各位是不是以前也设置过音乐播放？

**Comment by SuoHouDaiShi** [comment]
> > 刚想提交就看见了，我今天出现了好多次这个报错😥
> 
> 临时修复方法：先在音乐文件夹放一个音乐文件，然后回到启动器，把背景音乐里的游戏启动后开始播放音乐和游戏未运行时播放音乐关掉，再把音乐文件删了
> 
> 反正我这么整就好了，各位是不是以前也设置过音乐播放？

那你这么一说我倒想到了一个_可能触发BUG的原因_
因为**以前设置过音乐播放**，且**勾选**了`启动游戏时自动暂停，退出游戏时自动播放`的选项
但是后来<del>偷懒</del>用**PCL自带的清空音乐文件夹的按钮删除了音乐**
2.6.5的更新`可能`是**更改了一部分的**音乐播放逻辑
导致了**隐藏的音乐模块仍然勾选**`启动游戏时自动暂停，退出游戏时自动播放`这一项
但是人`Musics文件夹`**没有任何的音乐文件**
PCL2**仍然尝试**播放音乐
导致了**这个BUG的出现**

注：我**没写过**`VB`代码，所以这玩意<del>纯属瞎猜</del>要骂**骂轻点**（run

**Comment by SNWCreations** [comment]
我这里也出现了此Bug，情况与 #2558 一致。
很奇怪，就这两天才出现的。
记得特别古早的时候设置过音乐播放，但相关设置早已被清除。
不确定是否由这个导致。
插个眼，期待后续修复。

**Comment by GuGKai** [comment]
> 好像更新之前的2.6.4没有这个问题，龙猫大大可以查查最近的更改

W我也复现这个报错了，你游玩的时候游戏能正常运行吗
