### ISSUE TITLE
PCL又出问题了？问什么登录时会脚本错误

### ISSUE THREAD

**Issue by poiuy321754** [Hex-Dragon/PCL2#2518]
### 检查项

- [x] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在登陆微软账户到minecraft时，会提示脚本错误
![屏幕截图 2023-08-18 124728](https://github.com/Hex-Dragon/PCL2/assets/142563631/2e611844-e776-4cbf-859b-5365079b18b7)

### 重现步骤

免费版
1.点击微软账户
2.添加账户并正常登录
3.登录过程中提示
快照版
1.点击正版
2.添加账户并正常登录
3.登录过程中提示

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12375434/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12375435/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12375436/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12375437/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12375438/Log2.txt)

**Comment by Pigeon0v0** [comment]
无法复现

**Comment by zkitefly** [comment]
这个是调用浏览器时出现的问题，请在弹出登录网页时点击下面的按钮转至系统浏览器登录
