### ISSUE TITLE
我不知道发生了什么？

### ISSUE THREAD

**Issue by 2104liao** [Hex-Dragon/PCL2#2520]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

没什么影响

### 重现步骤

关闭游戏就有提示

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12377412/Log1.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12377436/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12377437/Log5.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12377438/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12377439/Log3.txt)

**Comment by zkitefly** [comment]
网络问题与 pcl 无关
