### ISSUE TITLE
batmc无法启动

### ISSUE THREAD

**Issue by Gongqinlang** [Hex-Dragon/PCL2#2521]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

打开bat会直接说游戏已结束

### 重现步骤

1.打开pcl
2.在little skin上创建2个人物，分别为1和2
3.以little skin登录
4.使用角色1进入游戏并退出游戏
5.在版本设置中下滑找到并点击“导出启动脚本（导出bat）
6.打开，然后关闭这个启动脚本
7.通过pcl使用角色2打开minecraft
8.关闭minecraft和pcl
9.打开启动脚本
10.查看启动脚本内容

### 日志与附件

无

**Comment by zkitefly** [comment]
请上传启动器日志和游戏日志

**Comment by youzi-2333** [comment]
超时关闭，若有更多信息补充，请继续提出。
