### ISSUE TITLE
下载界面下，展开手动安装包列表会使顶部“Minecraft”字样消失

### ISSUE THREAD

**Issue by Chocowheat** [Hex-Dragon/PCL2#2523]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

下载界面下，展开手动安装包列表会使顶部“Minecraft”字样消失
![1](https://github.com/Hex-Dragon/PCL2/assets/139761995/0b75c0eb-d644-4ad6-8b1b-8d3987c50101)
![2](https://github.com/Hex-Dragon/PCL2/assets/139761995/01efe2fa-dafe-413b-91eb-55bdcbd51891)

### 重现步骤

1、点击"下载"页面
2、然后点击"手动安装包"

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12379190/Log1.txt)

**Comment by zkitefly** [comment]
我认为这个是刻意的行为🤔

**Comment by LTCatt** [comment]
预期行为
