### ISSUE TITLE
点击顶部[更多]时弹出界面切换报错

### ISSUE THREAD

**Issue by HeJinDing-aipiao** [Hex-Dragon/PCL2#2536]
### 检查项

- [ ] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![c50f23889ad4818af57c3ca729e0ea7d](https://github.com/Hex-Dragon/PCL2/assets/72332681/e4f37cf8-4654-4ec9-a5c7-668507e977e3)

### 重现步骤

1、点击顶部栏的 [更多]
2、弹出报错框

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12385773/Log3.txt)

**Comment by George-Lvqr** [comment]
从来都没有遇到过,而且无法复现,似乎是极其小的概率问题?

**Comment by zkitefly** [comment]
等等，不是，你怎么用这么老的版本（Snapshot 2.2.14）

**Comment by hejiehao** [comment]
充钱充的太少？

**Comment by George-Lvqr** [comment]
> 充钱充的太少？
不是,这跟充钱有什么关系?我不信他换成最新正式版的PCL还会有这种问题.

**Comment by hejiehao** [comment]
> > 充钱充的太少？
> > 不是,这跟充钱有什么关系?我不信他换成最新正式版的PCL还会有这种问题.

我担心你就冲了6块6毛6

**Comment by LTCatt** [comment]
大概率是老版本 PCL 不兼容新版新闻主页导致，非启动器本身问题
