### ISSUE TITLE
搜索 Mod 时重置条件未重置“来源”

### ISSUE THREAD

**Issue by g-mph** [Hex-Dragon/PCL2#2537]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

搜索 Mod 时重置条件未重置“来源”这个条件。

### 重现步骤

1.点击“下载”
2.点击“Mod”
3.将“来源”改为 CurseForge 或 Modrinth
4.点击“重置条件”

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12385886/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12385887/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12385888/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12385889/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12385890/Log2.txt)

**Comment by hejiehao** [comment]
什么都会重置，就是来源不会重置

**Comment by Chiloven945** [comment]
成功复现。

**Comment by g-mph** [comment]
@LTCatt 那……活跃橙？
识别码 FF56-27A7-BEA3-42B9
感谢~

**Comment by LTCatt** [comment]
你的解锁码：o8TNKMY8fUg7FuwcKC9QQ/UfLsCPUBPZ
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
