### ISSUE TITLE
2.6.5优化内存后出现问题

### ISSUE THREAD

**Issue by MoIei** [Hex-Dragon/PCL2#2538]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在正常模式下点击优化内存，设置里游戏面板的已使用内存的文字和数字就会不显示

### 重现步骤

1，点击更多
2，点击百宝箱
3，点击内存优化
4，等待优化完成
5，点击设置
6，往下划，查看游戏内存状态

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12386365/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12386366/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12386367/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12386368/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12386369/Log5.txt)

**Comment by LTCatt** [comment]
#2526 #1924
