### ISSUE TITLE
可以订阅整合包，整合包有新版本发布时会通知

### ISSUE THREAD

**Issue by gyspyw** [Hex-Dragon/PCL2#2541]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

当整合包有新版本发布时，PCL2会在主界面提示，类似原有的游戏更新提示功能。

### 原因

  我需要这个功能来实时了解整合包更新并下载。很多人都有及时下载最新整合包版本的需求，但如果没有这个功能，就不能及时了解整合包更新了。
  有了这个功能，那些经常更新的整合包有新版本时，玩家会知晓。

**Comment by zkitefly** [comment]
看起来不错

**Comment by LTCatt** [comment]
由于 CurseForge 可能有潜在的 API 限制，暂时不考虑 :/
