### ISSUE TITLE
下载倒计时

### ISSUE THREAD

**Issue by XLX9200** [Hex-Dragon/PCL2#2545]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在下载页增加下载完成倒计时

### 原因

这项优化让我可以更方便地知道各项下载内容需要多少时间

**Comment by AnnualfireCHW** [comment]
实际上这一优化可能不必要。因为很多的下载倒计时并不准确。具体的速度取决于您的网络。如果网络环境波动较大，可能出来的速度就不准确，并且还会增加计算的功耗。

**Comment by SALTWOOD** [comment]
可以做，不难
但是如上，可能因为网络不稳定导致偏差过大（但是别的软件也这样我觉得无所谓）
同时人类自带一种“倒计时心理”，即使是一个99%的进度条也会使人更愿意等待（我在说什么？
反正就是可以加

**Comment by LTCatt** [comment]
做不出来，不难个鬼，根本没法预测（

**Comment by SALTWOOD** [comment]
当我没说（
忘了忘了相关与文件操作的进度条制作难度不一样了（

**Comment by AnnualfireCHW** [comment]
> 做不出来，不难个鬼，根本没法预测（

那你可以参考一下类似于FDM和edge浏览器是怎么做到预测的？

**Comment by AnnualfireCHW** [comment]
> 做不出来，不难个鬼，根本没法预测（

理论上你可以通过一些方法进行预测，比如算出当前的网速，再根据剩余的文件数量大小相除得到剩余的时间，并且不断更新。唯一的缺点是增加算力，并且可能会引入新的bug。不过如果这能给玩家带来好的体验。那也是可以。

**Comment by hejiehao** [comment]
怎么去获取总大小？

**Comment by AnnualfireCHW** [comment]
但是人家好像只是想要下载倒计时，而不是安装倒计时



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月22日(周二) 凌晨3:46
收件人: ***@***.***&gt;;
抄送: "Unlimited ***@***.******@***.***&gt;;
主题: Re: [Hex-Dragon/PCL2] 下载倒计时 (Issue #2545)




 
PCL 的下载任务不止是下载，还有 安装 ，并且一次下载涉及上千个文件，大小有的只有几 K，有的十几二十 M，这要怎么估算？

**Comment by AnnualfireCHW** [comment]
话说，你竟然是基于这个语言开发，你可以试试微软的UWP，作为你的一个测试版，里面就有控件(开玩笑的)



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月22日(周二) 凌晨3:46
收件人: ***@***.***&gt;;
抄送: "Unlimited ***@***.******@***.***&gt;;
主题: Re: [Hex-Dragon/PCL2] 下载倒计时 (Issue #2545)




 
PCL 的下载任务不止是下载，还有 安装 ，并且一次下载涉及上千个文件，大小有的只有几 K，有的十几二十 M，这要怎么估算？

**Comment by zkitefly** [comment]
> 但是人家好像只是想要下载倒计时，而不是安装倒计时
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年8月22日(周二) 凌晨3:46 收件人: ***@***.***&gt;; 抄送: "Unlimited ***@***.******@***.***&gt;; 主题: Re: [Hex-Dragon/PCL2] 下载倒计时 (Issue #2545) PCL 的下载任务不止是下载，还有 安装 ，并且一次下载涉及上千个文件，大小有的只有几 K，有的十几二十 M，这要怎么估算？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

问题就是无法获取准确的文件总大小
