### ISSUE TITLE
删除存档时出现错误

### ISSUE THREAD

**Issue by AnnualfireCHW** [Hex-Dragon/PCL2#2546]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

当以管理员权限运行PCL时(使用内存优化作者的弹窗中推荐这么做),新建的存档无法删除，即使手动定位到了存档的位置。包括整个版本也无法删除。只能通过一些强制性手段删除文件,即使以管理员权限运行文件删除，但这仍不起作用。除非要使用很麻烦的提权。
由于以往的bug提交很多，我没有办法一个一个看，只能做到看前四个板块没有类似的问题，望理解。

### 重现步骤

请看描述。以管理员方式运行PCL启动器就会出现存档和文件夹无法删除。

### 日志与附件

[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12391072/Log4.txt)

**Comment by AnnualfireCHW** [comment]
严格的来讲，这可能是Windows的问题，但PCL可以做到优化这一问题。例如可以以另一种用户身份创建文件夹，而不是以管理员身份。

**Comment by AnnualfireCHW** [comment]
> 创建文件夹和使用的权限应该没有影响，未见其他类似报告，考虑是系统配置问题

不是？？这个问题。PCL明明可以修复和解决，什么是系统配置问题，没明白你的意思。而且与权限竟然没有影响。那为什么未使用管理员权限就可以删除文件夹存档？你可以自己试试。

**Comment by AnnualfireCHW** [comment]
> 创建文件夹和使用的权限应该没有影响，未见其他类似报告，考虑是系统配置问题

当一个程序以管理员权限运行，那么在这个程序里新建文件夹打开其他程序的操作都是基于管理员权限。这次微软的开发文档中提到过。现在。但你可以通过特殊的方法以普通的用户身份去新建文件夹。并且并不麻烦。
如果你继续选择表示这与你的PCL没有关系，那么可以当我没说。

**Comment by LTCatt** [comment]
如果有其他人可以重现再考虑修复，看看其他人能不能吧……我真的怀疑是你的权限问题（

**Comment by AnnualfireCHW** [comment]
你好！经我测试，重启后问问题消失
对你带来的困扰我表示抱歉
是权限问题，但不只是我，我身边的小伙伴都有这样的问题，不然就我一个我也不会上报。这或许以你的应用程序无关，而是WINDOWS权限管理，我将会继续延研究问题的原因



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月22日(周二) 凌晨3:48
收件人: ***@***.***&gt;;
抄送: "Unlimited ***@***.******@***.***&gt;;
主题: Re: [Hex-Dragon/PCL2] 删除存档时出现错误 (Issue #2546)




 
如果有其他人可以重现再考虑修复，看看其他人能不能吧……我真的怀疑是你的权限问题（

**Comment by SALTWOOD** [comment]
不稳定复现，专门试的时候没用
