### ISSUE TITLE
辅助功能：默认设置为中文，请勿修改forceUnicodeFont

### ISSUE THREAD

**Issue by LeComte909** [Hex-Dragon/PCL2#2547]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

问题简述：
启动器开启辅助功能-默认设置为中文功能后会修改unicode字体设置
详情描述：
开启该功能后会在整合包安装后第一次启动将forceUnicodeFont:false修改为true
此功能会导致使用font制作的图形资源包失效

### 原因

此项功能导致大量使用PCL启动器的玩家在使用整合包时无法显示使用font制作的图形，增添不必要的麻烦

**Comment by zkitefly** [comment]
https://github.com/Hex-Dragon/PCL2/discussions/546#discussioncomment-4364439

**Comment by zkitefly** [comment]
等等，我感觉还是开着让龙猫看看啊（

**Comment by SALTWOOD** [comment]
同意，强制Unicode会导致部分文字/资源包出现错误
而且美不美观应由用户决定

**Comment by LeComte909** [comment]
mc本身就是默认打开的Unicode字体的，我们整合包专门给他关了，你再给他打开不合适吧

**Comment by SALTWOOD** [comment]
MC默认似乎不是打开Unicode的，PCL确实应该加上这个选项以满足部分用户的需求（比如我就关了
但也请不要带太大的情绪

**Comment by mcwuguodadi** [comment]
我也想把这个功能去掉或者是给一个自由开关的选项
我也是一个整合包作者，个人做整合包的时候会使用的界面尺寸为3（Large），这是关闭强制启用Unicode字体才能设置的，不然和2一样
整合包的大多数自定义UI都是围绕界面尺寸3更改的，开启Unicode会导致整个UI混乱

**Comment by SALTWOOD** [comment]
墙裂建议能单独设置，否则UI尺寸也会无效进而导致UI超界

**Comment by FangFuJi1991** [comment]
支持，受够了自动开unicode字体，因为我觉得unicode字体更好看些，但是每当我安装新游戏时，都他妈给我开了unicode字体，得调回去，并且pcl2里面是没有开不开自动设置字体的选项。所以支持
