### ISSUE TITLE
自定义背景支持视频或实况壁纸

### ISSUE THREAD

**Issue by wuzhuoyi114514** [Hex-Dragon/PCL2#2548]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [x] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

自定义背景现在只支持图片 而且不可以实况壁纸
这让我一个wallpeper用户难 受 死 了
所以我建议 增加视频和实况壁纸功能（
这样 我就happy了（bushi

### 原因

自定义背景现在只支持图片 而且不可以实况壁纸
这让我一个wallpeper用户难受死了，让操作变得很麻烦。

**Comment by SALTWOOD** [comment]
需求不大，可能不会做

**Comment by mcwuguodadi** [comment]
需求不大，可能不会做
还有你应该投“新功能提案”板块

**Comment by SALTWOOD** [comment]
> 需求不大，可能不会做 还有你应该投“新功能提案”板块

Collaborator可以改tag吧

**Comment by SALTWOOD** [comment]
对渣机不友好，面向用户群体窄，最主要是花里胡哨
能启动Minecraft才是最关键的，其他没必要整那么多

**Comment by youzi-2333** [comment]
背景支持视频……是不是类似 #862？

**Comment by mcwuguodadi** [comment]
> 背景支持视频……是不是类似 #862？

不是，他应该指的是像BakaXL的实况视频功能
软件可以与wallpaper engine之类的软件联动，实现启动器的背景和桌面的动态背景相同

**Comment by wuzhuoyi114514** [comment]
是的
