### ISSUE TITLE
为什么PCL2会自我销毁？

### ISSUE THREAD

**Issue by yanik2333** [Hex-Dragon/PCL2#2549]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

首先，PCL2在我电脑上对吧，而且我也确认了PCL2是最新版本!
然后，反病毒程序也没查到PCL2，也没报病毒显示，结果我一重启，就不知道为什么PCL2好好的消失了。。。
系统:Windows 11 (已确保最新版本)
反病毒程序：火绒安全(而且我将PCL2加入信任区也没用)
表现:静默自毁，并没有提示与日志!

##我将PCL2加入白名单也没用！！！火绒的安全日志中没有删除PCL2的日志信息（更别说PCL2的日志

### 重现步骤

重启就无了

### 日志与附件

没有日志，日志压根找不到。
也没出现。

**Comment by yanik2333** [comment]
我附加一下我的PCL2日志文件吧
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12392520/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12392521/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12392522/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12392523/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12392524/Log5.txt)

**Comment by yanik2333** [comment]
这是_**火绒安全**_日志中**全部日期**的
[火绒安全日志 - ALL.txt](https://github.com/Hex-Dragon/PCL2/files/12392538/-.ALL.txt)

**Comment by yanik2333** [comment]
另外在Windows自带的事件查看器中未找到PCL2的错误报告

**Comment by yanik2333** [comment]
此现象在这台电脑已经发生了很多次了，其他应用都不会自我销毁这现象，唯独PCL2会自我销毁，乐
我而且也不经常关机的，怕PCL2又被自我销毁了，再声明一件事:"我电脑中没有病毒!我已经复查过了!"
今天5:30睡的(熬了，也验证了PCL2的存在性
今天10:00左右，就发现不在了(我直接盖上电脑，电脑直接睡眠了，而且我也保存了我必要的文件
之前也频繁出现，现在是第四次了，白名单也反复添加了很多次，火绒连加之前都没报毒（是后面觉得要加白名单，就加了个白名单，结果还来
所以
在折磨下去拉倒换启动器吧...

**Comment by yanik2333** [comment]
哦对，最重要的忘说了。
我一般启动启动器的方式是使用**快捷方式**启动的
**_是放在任务栏上的快捷方式。_**

**Comment by yanik2333** [comment]
再次声明，快捷方式是没有问题的，有必要调查PCL2!

**Comment by beipull** [comment]
#666 
这种情况大概率是Windows Defender误报

**Comment by yanik2333** [comment]
并不是误报，甚至连报告都没有报告，而且Windows Defender没在运作!（图中的"不用执行任何操作"）
![QQ图片20230821140405](https://github.com/Hex-Dragon/PCL2/assets/76595546/cd72c604-dcd3-4de0-83f5-af7c2ea1883b)

![QQ图片20230821140400](https://github.com/Hex-Dragon/PCL2/assets/76595546/9f14ebe9-8831-4a0d-985a-3a0206f6585b)

**Comment by zkitefly** [comment]
这是一个奇怪的事情，感觉很诡异

**Comment by SALTWOOD** [comment]
确实诡异，能提供更多信息吗？
试试开监控软件看看是否有程序动手动脚

**Comment by yanik2333** [comment]
好的，我试图查看一下

**Comment by yanik2333** [comment]
OK，根本查不到删除记录，真的莫名其妙...

**Comment by yanik2333** [comment]
我再查一下病毒吧，全盘扫描ing

**Comment by SALTWOOD** [comment]
影子系统？

**Comment by yanik2333** [comment]
> 影子系统？

家用电脑用影子系统????what are you thinking?

**Comment by yanik2333** [comment]
这个或许有用
![image](https://github.com/Hex-Dragon/PCL2/assets/76595546/595fc02e-821f-4073-bd02-fa24e13072fd)

**Comment by SALTWOOD** [comment]
试试

**Comment by SALTWOOD** [comment]
> ![IMG_0113](https://user-images.githubusercontent.com/141309773/261941420-fbf648ce-5b66-4f67-9cbf-ba1078a3fee6.jpeg) 从官方文档里截的，希望能帮到你

楼主已尝试图中的方法，显然没有效果

**Comment by yanik2333** [comment]
> ![IMG_0113](https://user-images.githubusercontent.com/141309773/261941420-fbf648ce-5b66-4f67-9cbf-ba1078a3fee6.jpeg) 从官方文档里截的，希望能帮到你

感谢你的帮助，不过，Windows Defender已经不在工作了，因此，火绒在帮助我的Windows系统反病毒，现在在尝试运用火绒的高级保护规则试试能不能抓到“间谍软件“

**Comment by yanik2333** [comment]
请不要再提Windows Defender了，它已经不在运作了！截图有据
![image](https://github.com/Hex-Dragon/PCL2/assets/76595546/96d59da4-e066-4383-818b-9ea1dcadc16f)
这是查杀报告
![5WF@ZO)T8EHWLFRE@U_H1_0](https://github.com/Hex-Dragon/PCL2/assets/76595546/d23c4eaa-eef8-41e0-9376-be1a7809634e)

**Comment by q1145808079** [comment]
我也遇到这个问题了，晚上开了一晚上mc在挂机，第二天起床看的时候pcl启动器直接没了，游戏还在那挂着，我的电脑跟楼主一样都是用火绒，然后没找到删除的记录，我再找下系统日志，再看下情况

**Comment by WorldHim** [comment]
PCL 是不会也不可能删除本体的。。除了更新时新版会删除旧版。。。如果你还是不相信是安全软件的问题，可以尝试卸载wd在内的所有安全软件。
