### ISSUE TITLE
[BUG]提示文字不随页面移动消失

### ISSUE THREAD

**Issue by Roser7419** [Hex-Dragon/PCL2#2552]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在带有文字提示的设置框处稍作停留，会出现对应提示
在使用滚轮对页面进行滚动后该提示不会消失，而是会停留在当前位置
一定程度的移动鼠标就可以解除，但是这个程度也不是很确定
![图片](https://github.com/Hex-Dragon/PCL2/assets/121746494/847c7559-ecc7-4e83-b20c-98fabc0bfa90)

### 重现步骤

在任何稍作停留会出现文字提示的地方触发该提示，然后用滚轮滑

### 日志与附件

其实这里面好像没有这玩意，这些Log大概就只会展示我到处试这个Bug的历程
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12393155/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12393157/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12393158/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12393160/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12393161/Log5.txt)

**Comment by SALTWOOD** [comment]
成功复现
但这几乎算是大多数WPF应用的通病（？

**Comment by SALTWOOD** [comment]
而且那叫Tooltip吧

**Comment by Roser7419** [comment]
这方面名词什么的我不是很懂啦（

**Comment by mcwuguodadi** [comment]
成功复现，感谢反馈~

**Comment by Yue-cn** [comment]
~这个问题确定点击一下还会保留吗？~
我的建议是，能改就改吧
![Animation (33)](https://github.com/Hex-Dragon/PCL2/assets/79188080/d58b51f4-ae34-4cb4-8095-cbf7b7c0111a)

**Comment by mcwuguodadi** [comment]
> ~这个问题确定点击一下还会保留吗？~
> 我的建议是，能改就改吧
> ![Animation (33)](https://github.com/Hex-Dragon/PCL2/assets/79188080/d58b51f4-ae34-4cb4-8095-cbf7b7c0111a)
> 

点一下就消失了.jpg

**Comment by MCSteve123** [comment]
为啥我复现不出来？这BUG还没修啊

**Comment by SALTWOOD** [comment]
> 为啥我复现不出来？这BUG还没修啊

鼠标悬浮在一些按钮上，等提示文字显示出来后滑动滚轮

**Comment by iPodtouch6557** [comment]
神奇，在我的常用电脑上无法复现，在另一台电脑上就复现了……

**Comment by Roser7419** [comment]
解一个活跃橙，识别码如下
2E64-439B-B0B5-4B82

**Comment by Roser7419** [comment]
主题 2E64-439B-B0B5-4B82

**Comment by LTCatt** [comment]
你的解锁码：19AQJ518TQVVt0+Mi7fqXJx9/anfJnx2
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
