### ISSUE TITLE
忽略阻止提示并继续添加Java

### ISSUE THREAD

**Issue by GTEMYee** [Hex-Dragon/PCL2#2554]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

附图
![AddJavaBlocked](https://github.com/Hex-Dragon/PCL2/assets/117887221/49737f55-b206-45af-bb40-2432de3fe0fb)

### 原因

我只是用来运行Minecraft，而不是再下载jdk来运行
有什么mod出现兼容问题能证明一下
我一直在用jre，也没有什么崩溃问题
如果要强制添加需要修改 Windows注册表
而且还有很多一部分人不知道什么是 Windows注册表
也会造成一部分麻烦

**Comment by LTCatt** [comment]
PCL 支持 **自动下载** JDK 17，没有任何必要非要使用 JRE……

**Comment by GTEMYee** [comment]
> PCL 支持 **自动下载** JDK 17，没有任何必要非要使用 JRE……

那有什么能表明jdk比jre更好呢

**Comment by LTCatt** [comment]
部分 JRE 不兼容 Forge，或者在安装 Forge / OptiFine 的时候会导致崩溃，具体哪些 JRE 有问题还难确定规律，才这样折腾的，希望能理解 Orz
