### ISSUE TITLE
更新日志不再只查看当前版本的更新内容

### ISSUE THREAD

**Issue by QianLiZhiWaiovo** [Hex-Dragon/PCL2#2557]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

PCL更新后的更新日志不再只查看当前PCL版本的更新内容，而是查看从更新前的PCL一直到现在的PCL的更新内容

### 原因

一目明了的查看从这个版本更新后增加了什么功能（算是一个小优化吧doge）

**Comment by zkitefly** [comment]
为啥不去 github、B 站和爱发电看更新日子呢

**Comment by SALTWOOD** [comment]
似乎代码里有组成，在FormMain.xaml.vb

**Comment by LTCatt** [comment]
没啥必要，非想看可以去爱发电或者 B 站……
