### ISSUE TITLE
下载原版支持库文件卡住

### ISSUE THREAD

**Issue by HolyIwater** [Hex-Dragon/PCL2#2561]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

下载原版游戏或者整合包，下载其他文件都很顺利，到了下载原版支持库文件那里就一直卡住不动，下载速度为0，一直卡住直到超时显示错误。
昨天是下载.json文件下载不下来支持库能下载下来，今天是支持库下载不下来了。只能玩之前已经下载的游戏版本。其他启动器下载应该没有问题。
这个问题很多人都遇到了，都没有解决。非常需要解决，整合包需要下载，希望作者可以看到并尽快解决，谢谢！！！

### 重现步骤

就是原版或者整合包界面直接点下载

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12403871/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12403872/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12403873/Log3.txt)

**Comment by HolyIwater** [comment]
希望作者快点解决，秋梨膏！！！

**Comment by wcfe666** [comment]
我也发生了同样的情况，希望解决！
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12404246/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12404250/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12404251/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12404252/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12404253/Log5.txt)

**Comment by Yue-cn** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/79188080/073ee1a7-0912-4d92-8c24-648e35434ea1)
确定**不是**您的网络环境不佳吗？

**Comment by Yue-cn** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/79188080/4f1c6e96-cc33-4d61-bef1-5ca97dfbe81c)
![image](https://github.com/Hex-Dragon/PCL2/assets/79188080/13116539-74f3-420b-a52c-d7b893b33b7d)
重试没有次数限制吗？@#

**Comment by Yue-cn** [comment]
有尝试更换下载源吗？
![image](https://github.com/Hex-Dragon/PCL2/assets/79188080/eaf55120-6cb3-481c-b77e-b971954230a2)

**Comment by wcfe666** [comment]
我这边是打不开这个网址的
![Snipaste_2023-08-22_11-29-01](https://github.com/Hex-Dragon/PCL2/assets/61238734/caecfb4c-38a5-4544-9d29-169242ef8a8c)

**Comment by zkitefly** [comment]
> 我这边是打不开这个网址的
> ![Snipaste_2023-08-22_11-29-01](https://github.com/Hex-Dragon/PCL2/assets/61238734/caecfb4c-38a5-4544-9d29-169242ef8a8c)
> 

护网行动导致的，你可以换 dns 或改 hosts 或开梯子

**Comment by xiaomuzhaozi** [comment]
我也是这样一开始是原版json下载失败，后面更新过后就变成原版支持库下载失败，用梯子可以下载，但是总不能一直挂着梯子玩吧，之前都不需要梯子的，能修复好吗

**Comment by zkitefly** [comment]
> 我也是这样一开始是原版json下载失败，后面更新过后就变成原版支持库下载失败，用梯子可以下载，但是总不能一直挂着梯子玩吧，之前都不需要梯子的，能修复好吗

因为最近的护网行动导致部分地区访问微软的服务会失败（就包括 mc 的下载服务）要么改 dns 或改 hosts 或挂梯子，要么等到大概九月份

这个与 pcl 无关
