### ISSUE TITLE
版本设置 - Mod 管理 菜单的更改

### ISSUE THREAD

**Issue by LimeBow-Studios** [Hex-Dragon/PCL2#2565]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

喜欢原本的左键禁用mod的功能，是否可以改为：左键依然可以禁用/开启Mod，右键打开一个类似于Windows右键菜单的菜单，在这个菜单加入Mod管理相关的选项（例如向HMCL一样的检测mod更新的功能等...）

### 原因

这项优化让我可以更方便地管理mod。
如果没有这项优化，我每次都必须点击左键选择窗口最下方的菜单才能管理mod，让操作变得很麻烦。

**Comment by zkitefly** [comment]
或许可以看看但感觉不会去做

**Comment by Yue-cn** [comment]
像这样？ （我前端很垃的）
![image](https://github.com/Hex-Dragon/PCL2/assets/79188080/cd9d264a-fcfa-48bf-8692-1dd6ed065c5b)

**Comment by SALTWOOD** [comment]
可以看看但估计不会做
要是有能力可以试试看能不能交pr

**Comment by LTCatt** [comment]
没有必要情况下不考虑添加右键菜单……

**Comment by AnnualfireCHW** [comment]
> 没有必要情况下不考虑添加右键菜单......

每次提的建议总是拒绝放弃.....
我还是用回以前的版本吧。

**Comment by AnnualfireCHW** [comment]
> 没有必要情况下不考虑添加右键菜单......
我才发现我说的有问题不是右键菜单。是你现在版本下方会浮动出一个菜单选项，可以把它移移到右健点击的时候再触发并添加百科选项。

**Comment by zkitefly** [comment]
我认为还是要兼顾一下易用性的？

**Comment by AnnualfireCHW** [comment]
> 没有必要情况下不考虑添加右键菜单......

才发现你起来的这么早。是这样。当前版本模组管理列表中点击下方会展现浮动菜单。我的意思是将它移成右健的时候出现，而不是左键。左键保留原来快速禁用。将原本右键的百科菜单移到下方的浮动条上。

**Comment by AnnualfireCHW** [comment]
> 我认为还是要兼顾一下易用性的？

我提的建议就是在增加易用性。而且需要符合交互逻辑。大部分软件都是右键弹菜单。左键进行操作。

**Comment by Yue-cn** [comment]
不太可能了。要兼顾一下触摸屏，左击打开菜单是可以接受了

**Comment by AnnualfireCHW** [comment]
> 不太可能了。要兼顾一下触摸屏，左击打开菜单是可以接受了

触摸屏？谁玩电脑版的Minecraft需要用触摸屏？很少吧？

**Comment by AnnualfireCHW** [comment]
> 不太可能了。要兼顾一下触摸屏，左击打开菜单是可以接受了

可以参考手机上的交互逻辑，把触摸屏。改成长按弹出菜单。而不是点击。否则你看看Microsoft。他就为了强制统一键鼠用户和触屏用户，白墙是在Windows 11上进行这个交互逻辑。导致两方阵营都不舒适。如果要以牺牲键鼠用户的体验来成全触摸屏用户的话。多少有点不可理喻了。

**Comment by AnnualfireCHW** [comment]
> 不太可能了。要兼顾一下触摸屏，左击打开菜单是可以接受了

况且使用群体较少。也不太可能为触摸屏做优化。但我不知道这次更新添加了菜单到底是为什么。

**Comment by AnnualfireCHW** [comment]
> 或许可以看看但感觉不会去做

那为啥作者在这次更新中添加了菜单呢？:(

**Comment by Yue-cn** [comment]
拜托，是压根没写针对于ContextMenu的样式
![image](https://github.com/Hex-Dragon/PCL2/assets/79188080/0920447e-b7e0-4749-8827-7e573028df57)
