### ISSUE TITLE
[BUG]回声洞投稿造成加载预设主页失败

### ISSUE THREAD

**Issue by dannisyang53** [Hex-Dragon/PCL2#2568]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如题，当使用`回声洞`预设主页加载某些回声洞投稿时弹出“加载自定义主页失败”，弹窗截图见附件。

（似乎是因为投稿以`(`开头？）

### 重现步骤

1. 依次点击`设置`>`个性化`
2. 往下滚，找到`主页`
3. 点击`预设`
4. 在`主页预设`下拉栏中选择`回声洞`
5. 点击`启动`
6. 反复点击`回声洞`右上角的的刷新按钮

### 日志与附件

- 日志：[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12405637/Log1.txt)
- 截图：
![echo](https://github.com/Hex-Dragon/PCL2/assets/81854978/7e4f22cb-0571-45ea-b95a-7dde608729eb)

**Comment by Yue-cn** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/79188080/ffef036e-689a-4371-a754-94c9c736f264)

**Comment by dannisyang53** [comment]
@LTCatt 识别码 5890-62D7-6AF0-28F0 拿个活跃橙 十分感谢

**Comment by LTCatt** [comment]
你的解锁码：CG1ciy4Qe3gQ568XS9BmT7re3LiQHjn8
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
