### ISSUE TITLE
版本增多

### ISSUE THREAD

**Issue by yusili111** [Hex-Dragon/PCL2#2575]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

可以在下载界面增加例如error422的阴间版本

### 原因

单纯的想玩

**Comment by zkitefly** [comment]
那资源在哪

**Comment by SALTWOOD** [comment]
资源在哪？
安全性如何保证？
有需求的人会自己装，这些东西本身就在法律的灰色地带，怎么加？

**Comment by WForst-Breeze** [comment]
这些不是 Mojang 发布的 Minecraft 版本，PCL2 基本不可能提供下载服务

**Comment by SALTWOOD** [comment]
不是官方的东西几乎不会加，要是因为这些东西玩家电脑中毒咋办？

**Comment by youzi-2333** [comment]
PCL 不会加入对 Minecraft 衍生作品的支持，Error 422 应该与基岩版同样属于衍生作品，不是用启动器来启动的……吧（

**Comment by iPodtouch6557** [comment]
ERR422已被验证为安全，哪怕是会被杀毒软件拦截的危险版，可以上bilibili看看，搜@普通的史蒂夫
但是这个属于衍生版，不建议加，要加也可以加一点远古版

**Comment by mcwuguodadi** [comment]
PCL 不会加入对 Minecraft 衍生作品的支持，它终究是启动Minecraft Java Edition官方的版本

**Comment by iPodtouch6557** [comment]
> PCL 不会加入对 Minecraft 衍生作品的支持，它终究是启动Minecraft Java Edition官方的版本 像error442之类的属于衍生版本，是不会加入启动器的 而且也没有一个下载源能让启动器下载这些版本

下载源是一回事，要不要加是一回事……
我还是那个态度，不建议加，要玩的话自己安装，别找PCL

**Comment by LTCatt** [comment]
暂不考虑，抱歉
