### ISSUE TITLE
[Bug] 切换页面 Event 出错：未将对象引用设置到对象的实例

### ISSUE THREAD

**Issue by youzi-2333** [Hex-Dragon/PCL2#2578]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我在帮助文档内，将 EventType 设为 切换页面，EventData 是 `7|2`，报错如下：

```
程序出现未知错误：未将对象引用设置到对象的实例。
   在 PCL.PageVersionMod.RefreshList(Boolean ForceReload)
   在 PCL.PageVersionMod.PageOther_Loaded()
   在 PCL.PageVersionMod._Lambda$__R0-1(Object a0, RoutedEventArgs a1)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   在 System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   在 MS.Internal.LoadedOrUnloadedOperation.DoWork()
   在 System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   在 System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   在 System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   在 System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
错误类型：System.NullReferenceException
```

出错之后，整个 PCL 彻底卡住不动，`Alt + F4` 关不掉，任务栏关不掉，只能通过任务管理器关闭，并且关闭后，没有正常的退出输出。

由于其症状、报错内容与 #2577 均不相同，因此我又交了一个 Issue……

### 重现步骤

1. 设置一个自定义帮助文档，内容如下；
2. 点击 “Mod 管理” 选项；
3. Bug 出现。

```xaml
<local:MyCard Title="管理 Mod" Margin="0,0,0,15">
    <StackPanel Margin="25,40,23,15">
        <local:MyListItem Margin="-5,2,-5,8" Title="Mod 管理" Info="打开 Mod 管理页面"
            Logo="pack://application:,,,/images/Blocks/CommandBlock.png"
            EventType="切换页面" EventData="7|2" Type="Clickable" />
    </StackPanel>
</local:MyCard>
```

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12414123/Log1.txt)
[Log1.txt（调试模式）](https://github.com/Hex-Dragon/PCL2/files/12414133/Log1.txt)

---

![image](https://github.com/Hex-Dragon/PCL2/assets/106497113/ee85f2b0-cc0b-49fd-b0cb-f0ec884cac98)

**Comment by Yue-cn** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/79188080/4bf87748-dce8-40ca-a129-963a7d11a5f4)

**Comment by Yue-cn** [comment]
切换到页面 7 均会炸，估计是没传入对应版本而造成的 Null 值。
（VB.NET 没有Nullable类型吗）

**Comment by youzi-2333** [comment]
额，确实好像是 null 值的问题，但是我看源码里面写了，会自动选择 FormMain 中选中的游戏版本？

**Comment by LTCatt** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/865d3149-3e45-43d4-bd30-64d051fa595a)
不会受理 切换页面 的参数错误导致的 bug，抱歉 :/
