### ISSUE TITLE
在启动器更新时报“文件包含病毒或潜在的垃圾软件”时，提供一个跳转到对应帮助条目的按钮

### ISSUE THREAD

**Issue by mcwuguodadi** [Hex-Dragon/PCL2#2583]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在启动器更新时报“无法成功完成操作，因为文件包含病毒或潜在的垃圾软件”时，提供一个跳转到“将”PCL添加到Windows安全中心白名单“帮助条目的按钮

因为在内群经常有人询问该问题如何解决，我希望提供一个按钮让用户自行解决问题
帮助板块太冷门了以至于很多人不知道解决方案，而且”PCL添加到Windows安全中心白名单“的帮助条目截图太大了也不好截图给提问的内群用户

### 原因

添加该功能能让用户自行解决问题，不需要依靠其他用户的帮助
[有一些人就算在群里发截图想要受到帮助的时候也没有人愿意提供帮助导致无法更新启动器.jpg]

**Comment by zkitefly** [comment]
问题是怎么跳转🤔

**Comment by mcwuguodadi** [comment]
> 问题是怎么跳转🤔

跳转到更多-帮助-启动器-将PCL添加到Windows安全中心白名单
应该能做到吧.jpg

**Comment by Yue-cn** [comment]
假若是附加文件被拦截了，可以提示，但主文件都起飞了，如何打开浏览器？

**Comment by LTCatt** [comment]
ummm 我不确定具体被拦截的时候触发的报错信息，有被拦截的时候的 log 么？

**Comment by SuoHouDaiShi** [comment]
> ummm 我不确定具体被拦截的时候触发的报错信息，有被拦截的时候的 log 么？

我被拦截过，等会去补一张图
（另外这是系统报毒拦截，应该没有Log罢……

**Comment by mcwuguodadi** [comment]
> > ummm 我不确定具体被拦截的时候触发的报错信息，有被拦截的时候的 log 么？
> 
> 我被拦截过，等会去补一张图
> （另外这是系统报毒拦截，应该没有Log罢……
> 
> Edit：图片
> ![图片](https://github.com/Hex-Dragon/PCL2/assets/119282947/b7007a1a-68fe-45cb-8269-a3567209e062)
> ![图片](https://github.com/Hex-Dragon/PCL2/assets/119282947/cf28a41c-2df1-4585-ad3a-e023dcfed6f3)
> ![图片](https://github.com/Hex-Dragon/PCL2/assets/119282947/3005d9d7-3486-48e5-a6d6-a4fa0d5f5b39)
> 这玩意在解压出来的一瞬间就会被拦截，无法打开，所以没有Log……

他指的是在启动器的下载界面里报的错。。。

**Comment by SuoHouDaiShi** [comment]
> > > ummm 我不确定具体被拦截的时候触发的报错信息，有被拦截的时候的 log 么？
> > 
> > 
> > 我被拦截过，等会去补一张图
> > （另外这是系统报毒拦截，应该没有Log罢……
> > Edit：图片
> > ![图片](https://user-images.githubusercontent.com/119282947/270145788-b7007a1a-68fe-45cb-8269-a3567209e062.png)
> > ![图片](https://user-images.githubusercontent.com/119282947/270145793-cf28a41c-2df1-4585-ad3a-e023dcfed6f3.png)
> > ![图片](https://user-images.githubusercontent.com/119282947/270145797-3005d9d7-3486-48e5-a6d6-a4fa0d5f5b39.png)
> > 这玩意在解压出来的一瞬间就会被拦截，无法打开，所以没有Log……
> 
> 他指的是在启动器的下载界面里报的错。。。

我认为这个应该差不多的吧，更新的时候我也报过错，也长这样
（后来添加排除项就没事了

**Comment by mcwuguodadi** [comment]
> ummm 我不确定具体被拦截的时候触发的报错信息，有被拦截的时候的 log 么？

![Image_1695533854099.jpg](https://github.com/Hex-Dragon/PCL2/assets/82522552/bf1cab8d-f588-4020-b0b1-0fe1fc2fae94)

emmm，这个?（在内群里翻到的聊天图片）
