### ISSUE TITLE
PCL2登录微软账户时未响应

### ISSUE THREAD

**Issue by beiweiaran** [Hex-Dragon/PCL2#2587]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

挂了VK加速器后打开PCL2启动器,点击登录微软账户后登录界面未响应,PCL2启动器也未响应

### 重现步骤

1、启动VK加速器并加速Hypixel
2、启动PCL
3、在PCL中点击登录微软账户
4、登录界面未响应、PCL2未响应

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12419783/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12419785/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12419787/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12419788/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12419789/Log5.txt)

**Comment by hejiehao** [comment]
`[21:29:02.172] [Launch] 微软登录完成`

**Comment by SALTWOOD** [comment]
不像是PCL2的问题
更像是系统或是网络

**Comment by LTCatt** [comment]
这不是启动器导致的问题，可能是 webview 的 bug……我没啥办法修 :/
