### ISSUE TITLE
在退出游戏时出现错误

### ISSUE THREAD

**Issue by lidongxun967** [Hex-Dragon/PCL2#2589]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

退出任何游戏时都会弹出此错误，有时启动期间也会有错误
![image](https://github.com/Hex-Dragon/PCL2/assets/89326292/ea4d16d9-f32d-48ef-8b73-76cc015819d3)

### 重现步骤

1、启动任何游戏
2、启动完成后关闭游戏，即可复现

### 日志与附件

[log.txt](https://github.com/Hex-Dragon/PCL2/files/12421445/log.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12421446/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12421447/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12421441/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12421443/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12421444/Log5.txt)

**Comment by SuoHouDaiShi** [comment]
#2517 重复的Issues 自行关闭 点灰色的那个圆圈

**Comment by SuoHouDaiShi** [comment]
龙猫，捉！（
