### ISSUE TITLE
自定义主页“清理垃圾”功能出现bug

### ISSUE THREAD

**Issue by kndxhz** [Hex-Dragon/PCL2#2591]
### 检查项

- [x] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

自定义xaml文件出现错误

https://github.com/Hex-Dragon/PCL2/assets/113306265/0d3bd3a7-cda8-4614-856a-ccc1d1984210

### 重现步骤

自定义xaml文件并粘贴如下代码

```
<local:MyCard Title="基础功能" Margin="0,0,0,15" CanSwap="True" IsSwaped="True">
    <StackPanel Margin="25,40,23,15">
   
        <!-- 这是第一行 -->
        <StackPanel Orientation="Horizontal" HorizontalAlignment="Center">

            <local:MyButton Margin="0,0,10,0" Width="140" Height="35" HorizontalAlignment="Left" Padding="13,0,13,0"
                        Text="内存优化" EventType="内存优化" />

            <local:MyButton Margin="0,0,10,0" Width="140" Height="35" HorizontalAlignment="Left" Padding="13,0,13,0"
                        Text="今日人品" EventType="今日人品" />
            <local:MyButton Margin="0,0,10,0" Width="140" Height="35" HorizontalAlignment="Left" Padding="13,0,13,0"
                        Text="清理垃圾" EventType="清理垃圾" />
        </StackPanel>
    </StackPanel>
</local:MyCard>
```

由pcl的教学文件删改而来

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12422981/Log1.txt)

**Comment by kndxhz** [comment]
不知道为什么现在试又可以了🙄，概率性事件？

**Comment by kndxhz** [comment]
> 不知道为什么现在试又可以了🙄，概率性事件？

刚刚又触发一遍，重启了PCL又好了，真是概率性事件

**Comment by kndxhz** [comment]
顺带提一嘴能不能加个自定义主页回声洞，喜欢看网友奇奇怪怪的留言的同时保持主页的实用

**Comment by kndxhz** [comment]
900A-B20F-7C0B-408C
求个活跃橙awa

**Comment by LTCatt** [comment]
你的解锁码：9hjiGhnX+hcZXn82nRNA7Zjt0H7X0sjI
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by kndxhz** [comment]
> 你的解锁码：9hjiGhnX+hcZXn82nRNA7Zjt0H7X0sjI 在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

由于蓝屏导致识别码变更，重新请求一个活跃橙awa
`5FA6-15F3-AD5F-FD56`

**Comment by LTCatt** [comment]
你的解锁码：924Ip7gRoogKT+OUPBWuYNsuxfUI2cNU
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by kndxhz** [comment]
> 你的解锁码：924Ip7gRoogKT+OUPBWuYNsuxfUI2cNU 在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

硬盘掉盘重装导致识别码变更，麻烦龙猫了
`7BC7-A892-BD43-7DE3`

**Comment by LTCatt** [comment]
你的解锁码：tymDXwo7j42ngu68t8LrjZnFB85sZrMF
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by kndxhz** [comment]
换主板导致识别码变更，抱歉
`` 4F67-5EA9-DDD7-C180 ``

**Comment by LTCatt** [comment]
你的解锁码：O2HQsH4Y7sh5hurj63GZnD12/vRAba4U
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
