### ISSUE TITLE
自动安装修改 Minecraft 版本时如有修改版本名称则不重置版本名称

### ISSUE THREAD

**Issue by sssysy** [Hex-Dragon/PCL2#2593]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在 下载 - 自动安装 内选择了一个 Minecraft 版本后，并重命名版本名称。
此时如果想切换 Minecraft 版本会重置版本名称为新选择的 Minecraft 版本名称。
可以加个判断，如果没有修改默认名称则MC版本更改时自动更改版本名称，否则保留原来的版本名称
----
随便点击一个版本并重命名
![image](https://github.com/Hex-Dragon/PCL2/assets/79786006/8b5ac4e9-518f-4b76-9d96-1cd3e377188d)
重新选择一个MC版本后版本名称会被重置
![image](https://github.com/Hex-Dragon/PCL2/assets/79786006/813e896f-2e2e-4bc4-915e-e2ea15eeee41)

### 原因

（示例）
这项优化让我可以更方便地设置和命名版本名。
如果没有这项优化，我每次都必须重新输入我想要的版本名称，如果名称过长会让操作变得很麻烦。

**Comment by zkitefly** [comment]
为什么不在返回前复制一下名称然后再返回呢

**Comment by sssysy** [comment]
有可能我不知道重选版本会重置名称所以直接改MC版本呢？
不过确实这个优化挺小的，不改也并不会影响什么。
改了可能会更方便一点。

**Comment by zkitefly** [comment]
看看龙猫怎么说👀

**Comment by SALTWOOD** [comment]
不一定会做，从逻辑上来说，切换版本可以视作取消一个版本的安装转而去安装另一个版本
毕竟可以复制粘贴，不一定

**Comment by LTCatt** [comment]
暂不考虑，抱歉 :/
