### ISSUE TITLE
从开始菜单中拖拽文件至PCL窗口，会出现“接取拖拽失败”错误

### ISSUE THREAD

**Issue by MCSteve123** [Hex-Dragon/PCL2#2594]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如题。
启动PCL后，从开始菜单中拖拽一个文件（如3D查看器）至PCL2窗口中，弹窗报错，且提示操作系统存在问题。
暂时只有MS官方的软件拖拽会报错|（如3D查看器），其它后期安装的软件不会出现问题（如git）

以下是一些截图：
![图片1](https://github.com/Hex-Dragon/PCL2/assets/121204926/5c865fca-c966-44a7-9f1f-6c0bb34f4f25)
![图片2](https://github.com/Hex-Dragon/PCL2/assets/121204926/204fc48f-517c-45dd-b720-3b1a23afbe67)
![图片3](https://github.com/Hex-Dragon/PCL2/assets/121204926/e3e33d3e-441e-4794-97aa-5106f478382a)

虽然这东西没啥用，但还是交一下反馈吧.jpg
也希望lm做得更好！

### 重现步骤

1、打开PCL
2、打开开始菜单
3、从开始菜单中拖拽出3D查看器或其它程序，并把它放入PCL窗口中
4、报错啦！寄！

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12426165/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12426166/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12426168/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12426169/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12426170/Log5.txt)

**Comment by zkitefly** [comment]
az，谁没事从开始菜单里面拖拽东西至 PCL 啊？！

**Comment by MCSteve123** [comment]
> az，谁没事从开始菜单里面拖拽东西至 PCL 啊？！
> 
> 让龙猫看看，不过肯定会被拒

所以啊，就是交个反馈，实际上意义感觉不大……
不过总也算BUG嘛，交一下总是好的

**Comment by SALTWOOD** [comment]
复现成功
但是正常没人会拖开始菜单的文件

**Comment by MCSteve123** [comment]
> 复现成功 但是正常没人会拖开始菜单的文件

我也不会，本来只是手滑了……

**Comment by LTCatt** [comment]
不知道咋修，修了也没啥意义，算了吧
