### ISSUE TITLE
遊戲無法開啓

### ISSUE THREAD

**Issue by GhostShadow0316** [Hex-Dragon/PCL2#2596]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃不是 PCL2 的原因，请 **不要** 提交反馈。你可以在 QQ 群里或者论坛找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是游戏本身的问题，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

自從更新之後就不能開MC了

### 错误报告、日志与附件

[错误报告-2023-8-24_Thu_03.51.40_PM.zip](https://github.com/Hex-Dragon/PCL2/files/12426937/-2023-8-24_Thu_03.51.40_PM.zip)

**Comment by Yue-cn** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/79188080/76ec86bb-6ba3-4361-8798-8f51ddf08b84)

鋻定完畢，非 PCL 問題不能放在這裏，尚且 Issue 開頭的幾個 Checkbox 壓根沒勾，速速Close

**Comment by zkitefly** [comment]
非 PCL2 问题

尝试在桌面右键此电脑 -- 属性 -- 高级系统设置，然后按图里的顺序改成「自动管理所有驱动器分页文件大小」，改完后点三个「确定」，不要点右上角的叉，重启电脑 
![](https://img.kookapp.cn/assets/2023-03/bGbLMNRnws1020j1.png)
