### ISSUE TITLE
清理游戏垃圾后Xearo小地图的标点数据也被清除

### ISSUE THREAD

**Issue by CZYLIULIU** [Hex-Dragon/PCL2#2597]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

最新的快照中 点击 __更多\百宝箱\清理游戏垃圾__ 后 `Xearo's map` & `Xearo's World Map` 的标点数据也被清除了 但是加载的地图信息任然存在

### 重现步骤

点击`更多\百宝箱\清理游戏垃圾`

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12427160/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12427161/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12427162/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12427163/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12427164/Log5.txt)

**Comment by zkitefly** [comment]
Xearo's map & Xearo's World Map 的标点数据存在哪里

**Comment by CZYLIULIU** [comment]
`.\minecraft\veision\%版本名%\XaeroWaypoints\`（开启版本隔离）

**Comment by CZYLIULIU** [comment]
不好意思 可能是我修改了 世界文件夹的名称导致路径无法识别 问题已经解决了 谢谢
