### ISSUE TITLE
正版登录后，我已在官网更改账号密码，但是启动器仍任可以正常使用此账号

### ISSUE THREAD

**Issue by LXAHLX** [Hex-Dragon/PCL2#2598]
![微信截图_20230824170648](https://github.com/Hex-Dragon/PCL2/assets/117422453/385e2b3d-8861-4d5d-91d9-70dcf5ecae3a)
![微信截图_20230824170555](https://github.com/Hex-Dragon/PCL2/assets/117422453/30b33f7b-8a5f-4d9f-83d7-bba6b4674d33)
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我有一个好朋友开了个服务器，他有三个正版，我帮他建造，他也给我用他的正版，但是后来他改了密码，但是我并不知情照常用PCL2快照版。后来我才知道他改了正版密码，但是我这里仍然能使用它的正版启动，我在官方启动器上试过这个正版账号，原先的密码已经登陆不了，并且我在游戏试过能够登录要求正版的服务器（Hyp，2B2T），我觉得这个比较严重

### 重现步骤

1、点击正版
2、然后点击登录
3、用系统浏览器登陆
4、拖拽网址至PCL2
5、完成操作

### 日志与附件

如图所示是登陆并启动后进入Hyp
![微信截图_20230824170637](https://github.com/Hex-Dragon/PCL2/assets/117422453/07eb6082-065c-492b-807b-77088c49012c)

**Comment by SALTWOOD** [comment]
你试试还能不能登录正版验证的服务器
要是还行就可能是微软特性
否则就是假登录

**Comment by LXAHLX** [comment]
> 
可以在Hyp登陆并不是特性

**Comment by LXAHLX** [comment]
可以在Hyp登陆并不是特性

**Comment by LXAHLX** [comment]
> 你试试还能不能登录正版验证的服务器 要是还行就可能是微软特性 否则就是假登录

可以

**Comment by zkitefly** [comment]
他是通过登录 Microsoft xbox，然后通过他来获取 mojang 的 token，可能需要等 24 小时后 pcl 重新刷新 Microsoft xbox 时就失效？

**Comment by MCSteve123** [comment]
> 他是通过登录 微软 xbox，然后通过他来获取 mojang 的 token，可能需要等 24 小时后 pcl 重新刷新 微软 xbox 时就失效？
> 
> 因为改微软账户的密码不代表 mojang 的 accessTokens 会失效（好像是这样？）

意思是token没变就能一直登录？
那我要是想办法获取token并发给别人，是不是就可以实现对方借号登录？（这样可以防止别人盗微软账号？）

**Comment by zkitefly** [comment]
> > 他是通过登录 微软 xbox，然后通过他来获取 mojang 的 token，可能需要等 24 小时后 pcl 重新刷新 微软 xbox 时就失效？
> > 
> > 因为改微软账户的密码不代表 mojang 的 accessTokens 会失效（好像是这样？）
> 
> 意思是token没变就能一直登录？
> 那我要是想办法获取token并发给别人，是不是就可以实现对方借号登录？（这样可以防止别人盗微软账号？）

是的，accessTokens 过了 24 小时就会过期，需要重新刷新账户才能获取

pcl 这样操作就别想了，我记得 pcl 导出注册表的登录信息在别人的设备上导入是无效的。

**Comment by MCSteve123** [comment]
Collaborator来上个标签？还是说这是巨硬的问题，做不了？

**Comment by LXAHLX** [comment]
> 他是通过登录 微软 xbox，然后通过他来获取 mojang 的 token，可能需要等 24 小时后 pcl 重新刷新 微软 xbox 时就失效？
> 
> 因为改微软账户的密码不代表 mojang 的 accessTokens 会失效（好像是这样？）

我这样一直用了半个月

**Comment by LXAHLX** [comment]
> > > 他是通过登录 微软 xbox，然后通过他来获取 mojang 的 token，可能需要等 24 小时后 pcl 重新刷新 微软 xbox 时就失效？
> > > 因为改微软账户的密码不代表 mojang 的 accessTokens 会失效（好像是这样？）
> > 
> > 
> > 意思是token没变就能一直登录？
> > 那我要是想办法获取token并发给别人，是不是就可以实现对方借号登录？（这样可以防止别人盗微软账号？）
> 
> 是的，accessTokens 过了 24 小时就会过期，需要重新刷新账户才能获取
> 
> pcl 这样操作就别想了，我记得 pcl 导出注册表的登录信息在别人的设备上导入是无效的。

我这样用了半个月了直到现在

**Comment by LXAHLX** [comment]
> Collaborator来上个待处理？还是因为巨硬的问题，做不了？ （俩Collaborator回的问题，一个也不上标签，炸裂）

建议这样，目前没有解决办法

**Comment by zkitefly** [comment]
看看龙猫这么说（

**Comment by LTCatt** [comment]
你应该向 mojang 或者微软反馈，这不是启动器导致的 :/

**Comment by LXAHLX** [comment]
> 你应该向 mojang 或者微软反馈，这不是启动器导致的 :/

a?(颤抖

**Comment by LXAHLX** [comment]
> 你应该向 mojang 或者微软反馈，这不是启动器导致的 :/

我只不过是想要个隐藏主题QNQ
