### ISSUE TITLE
主页预设的回声洞无法刷新

### ISSUE THREAD

**Issue by CZYLIULIU** [Hex-Dragon/PCL2#2599]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在最新的快照（截止至2023/8/24）中 主页预设的回声洞无法刷新

### 重现步骤

我的具体操作
https://github.com/Hex-Dragon/PCL2/assets/104607365/66fbb06b-43bc-4226-a1af-c910ec57ad50

### 日志与附件

无

**Comment by zkitefly** [comment]
上传启动器日志

**Comment by CZYLIULIU** [comment]
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12428422/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12428423/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12428424/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12428426/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12428428/Log2.txt)

**Comment by hejiehao** [comment]
你好像都没有点刷新按钮

**Comment by CZYLIULIU** [comment]
刷新按钮在哪里？ 那啥我的意思是说像百宝箱里面的回声洞点击文本就可以刷新的功能

**Comment by hejiehao** [comment]
> 刷新按钮在哪里？ 那啥我的意思是说像百宝箱里面的回声洞点击文本就可以刷新的功能

![image](https://github.com/Hex-Dragon/PCL2/assets/98140773/9b7ada6b-b377-4317-9bf9-aec9e3b09d30)

**Comment by CZYLIULIU** [comment]
:) 我是煞笔

**Comment by CZYLIULIU** [comment]
对不起 pcl的开发者们 我今天 脑子有点不好使
