### ISSUE TITLE
音乐播放器的新BUG？

### ISSUE THREAD

**Issue by SuoHouDaiShi** [Hex-Dragon/PCL2#2601]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

**我知道这可能是我耳机不支持的原因导致的，但还是交个反馈看看**
**我知道这可能是我耳机不支持的原因导致的，但还是交个反馈看看**
**我知道这可能是我耳机不支持的原因导致的，但还是交个反馈看看**

<del>emmm，不知道说啥</del>
![图片](https://github.com/Hex-Dragon/PCL2/assets/119282947/2c81a13f-8eb9-4292-a624-f03e9466277d)

### 重现步骤

**我知道这可能是我耳机不支持的原因导致的，但还是交个反馈看看**
**我知道这可能是我耳机不支持的原因导致的，但还是交个反馈看看**
**我知道这可能是我耳机不支持的原因导致的，但还是交个反馈看看**

1.打开PCL2并播放音乐
2.右键任务栏上的声音图标，选空间音效，改成`用于耳机的 Windows Sonic`
![图片](https://github.com/Hex-Dragon/PCL2/assets/119282947/8e1ef144-6f89-4642-95a8-22aaa82a41cf)
3.等待PCL2切换音乐完成
4.再次右键任务栏上的声音图标，选空间音效，改成`关闭`
![图片](https://github.com/Hex-Dragon/PCL2/assets/119282947/b463a77b-1143-46b8-a353-4e8a0c9b0296)
5.BUG出现
![图片](https://github.com/Hex-Dragon/PCL2/assets/119282947/b6a42591-5793-4be9-8281-b3cb259a45c0)

### 日志与附件

日志文件：
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12428749/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12428750/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12428752/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12428753/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12428754/Log1.txt)

附：视频操作

https://github.com/Hex-Dragon/PCL2/assets/119282947/4277b9a8-ff71-403e-8aaa-c141c01ea011

**Comment by LTCatt** [comment]
#1753 
@zkitefly 多看一下是不是重复再标待处理……这个 issue 在常见问题列表里都
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/35673c96-b5b0-495a-9018-3c67ecf2c21a)

**Comment by zkitefly** [comment]
> #1753 @zkitefly 多看一下是不是重复再标待处理……这个 issue 在常见问题列表里都 ![image](https://user-images.githubusercontent.com/40348278/263217802-35673c96-b5b0-495a-9018-3c67ecf2c21a.png)

ok，当时脑袋热（
