### ISSUE TITLE
启动器更新检测不及时

### ISSUE THREAD

**Issue by blibilijojo** [Hex-Dragon/PCL2#2603]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

![image](https://github.com/Hex-Dragon/PCL2/assets/102420734/a6c5d0d1-568c-4913-a126-1aaf7dc861a6)
老问题了，每次打开启动器哪怕更新了都不会提示，都是看更新通知之后才知道更了才检测更新，挺坑的，起码加个启动时检测更新吧，每次都更新了两天了，启动器用了好几次了，看了GitHub或者bilibili才知道更新了。

### 原因

方便更新

**Comment by Yue-cn** [comment]
就是有，只是说因下载缓慢而造成的一种假象罢了。:(

**Comment by zkitefly** [comment]
应该的 CDN 缓存问题，不过让龙猫看看qwq

**Comment by blibilijojo** [comment]
> 就是有，只是说因下载缓慢而造成的一种假象罢了。:(

不能吧，他更新提示都没有，我只要主动点检测更新然后确认不到十秒就下载好了

**Comment by Yue-cn** [comment]
？你这是快照版

**Comment by hejiehao** [comment]
> 应该的 CDN 缓存问题，不过让龙猫看看qwq

应该不是CDN缓存的问题吧
我用快照版也要经常手动点“检查更新”

**Comment by SALTWOOD** [comment]
CDN缓存问题，无法解决:/

**Comment by zkitefly** [comment]
> 感觉不像是CDN的问题，要是CDN的问题“检查更新”点了也没啥用。（话说，我怎么记得这玩意好像不是cdn？）

不是 oss 吗（？

**Comment by LTCatt** [comment]
补充 log

**Comment by blibilijojo** [comment]
> 补充 log

em，提交哪一个部分

> 补充 log

好的，因为我已经更新到最新版了，所以我去爱发电上重新下了一下旧版快照，版本为2.3.0，应该和新版关于更新方面是一样的。启动器更新设置为：在有新版本时自动下载(更新快照版可能需要更新密钥)
执行以下的操作：打开PCL2，未显示更新，关闭PCL2。再打开，依旧没显示，点击检查更新，输入更新密钥，更新成功。
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12438410/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12438413/Log4.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12438414/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12438415/Log2.txt)
