### ISSUE TITLE
查看了更多-帮助页面后，页面状态会重置

### ISSUE THREAD

**Issue by iPodtouch6557** [Hex-Dragon/PCL2#2606]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如题，点开一个任意的帮助文档，浏览完后会发现页面自动跳转到了最上面
修复可能意义不大，但是看着就是难受.jpg

### 重现步骤

1、打开更多-帮助
2、往下滚到底，然后展开卡片，点击任意一个**非弹窗或链接的**帮助页面
3、退出帮助页面，bug复现

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12435189/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12435190/Log2.txt)

**Comment by Yue-cn** [comment]
跳转到新页面后上一个页面的状态会被重置

**Comment by youzi-2333** [comment]
> 跳转到新页面后上一个页面的状态会被重置

额，是的，目前我发现的唯一一个特例就是 Mod / 整合包 下载页面……

**Comment by LTCatt** [comment]
不同的帮助页面实际上是同一个页面，所以没法保留状态 =。=
