### ISSUE TITLE
预设主页的回声洞无法换行

### ISSUE THREAD

**Issue by iPodtouch6557** [Hex-Dragon/PCL2#2608]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如图所示的这条回声洞在百宝箱里有四行，但在主页里换行被空格代替
<img width="411" alt="image" src="https://github.com/Hex-Dragon/PCL2/assets/118656946/0e2adf45-dbfb-4b43-bc78-46e46b8cacce">

### 重现步骤

如上，目前已知这一条

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12436989/Log1.txt)

**Comment by iPodtouch6557** [comment]
换电脑了，随便找个issue来交个解锁码……

1337-5FBD-D237-50B9

**Comment by LTCatt** [comment]
你的解锁码：F0Rdr3tKm/SIHGl7FlDbctFx0BcyujS2
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
