### ISSUE TITLE
[BUG]在其他电脑上安装pcl而且安装位置在可移动设备上带到其他电脑

### ISSUE THREAD

**Issue by weiqi114514** [Hex-Dragon/PCL2#2609]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

无法下载mod，版本且打开更多帮助界面会卡住

### 重现步骤

在其他电脑上安装pcl而且安装位置在可移动设备上带到其他电脑

### 日志与附件

[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12438263/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12438259/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12438260/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12438261/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12438262/Log3.txt)

**Comment by zkitefly** [comment]
可能是你的移动设备的问题，例如速度等

**Comment by hejiehao** [comment]
为什么会找不到文件呢？编码问题？权限问题？

**Comment by LTCatt** [comment]
估计是移动设备的问题……没法修也
