### ISSUE TITLE
《你知道吗》优化

### ISSUE THREAD

**Issue by 3132321887** [Hex-Dragon/PCL2#2612]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

龙猫可以把每次启动时的《你知道吗》换个地方吗awa，因为有的时候启动一些低版本的游戏时时间太短了，看不到

### 原因

其实不优化也没什么啦，只是很好奇那写了些啥而已awa

**Comment by LTCatt** [comment]
暂不考虑……

**Comment by MCSteve123** [comment]
话说现在好像有了《你知道吗》预设主页了
