### ISSUE TITLE
隐藏主题Bug-启动99次后无法解锁

### ISSUE THREAD

**Issue by 3132321887** [Hex-Dragon/PCL2#2614]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

口头不好讲清楚,龙猫可以看看我的[视频](https://www.bilibili.com/video/BV1zu4y1X7Ux)
反正就是启动了99次之后无法解锁全成就

### 重现步骤

启动99次

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12439145/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12439147/Log3.txt)

**Comment by hejiehao** [comment]
好像是启动PCL2 100次？

**Comment by 3132321887** [comment]
我这里启动了105次。。。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月25日(星期五) 晚上8:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Hex-Dragon/PCL2] 隐藏主题Bug-启动99次后无法解锁 (Issue #2614)





 
好像是启动PCL2 100次？

**Comment by LTCatt** [comment]
不是这个条件
