### ISSUE TITLE
自定义下载添加最大线程数或下载速率限制

### ISSUE THREAD

**Issue by Yweiwu30** [Hex-Dragon/PCL2#2616]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

如题，在自定义下载选项里添加线程或速率限制的设置

### 原因

有时候在某些服务器下载时请求太多会被ban掉

**Comment by zkitefly** [comment]
https://github.com/Hex-Dragon/PCL2/issues/1004

**Comment by LTCatt** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/9e22b216-c73a-47ae-874c-a583810ce475)
你可以手动在下载时修改这些设置，但暂时不考虑为自定义下载独立添加设置，抱歉（
