### ISSUE TITLE
返回顶部按钮点击之后有概率无法回顶

### ISSUE THREAD

**Issue by funnyyyyyyyy** [Hex-Dragon/PCL2#2618]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我主页平时都开着调试模式和新闻 但是当我点击返回顶部后再点击调试的那一长串东西就无法回顶 而且返回顶部按钮确实被按下去了（缩小了一圈）

### 重现步骤

1、先到最底部
2、点击返回主页后马上点击日志

### 日志与附件

[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12444429/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12444430/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12444431/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12444432/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12444433/Log3.txt)

**Comment by LTCatt** [comment]
刻意触发的、影响不大的 bug 不会修复，抱歉 :/
