### ISSUE TITLE
预设主页

### ISSUE THREAD

**Issue by funnyyyyyyyy** [Hex-Dragon/PCL2#2619]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

可不可以把预设主页上列表的东西改成多选 小孩子才做选择 我全都要！

### 原因

这项优化让我可以更方便地van耍PCL2的各种想看的东西。
如果没有这项优化，我每次都必须一个一个的切换，让操作变得很麻烦。

**Comment by iPodtouch6557** [comment]
大概率拒绝……可能会导致适配方面的问题

**Comment by LTCatt** [comment]
暂不考虑……
