### ISSUE TITLE
爱发电的蛋疼的玩意

### ISSUE THREAD

**Issue by funnyyyyyyyy** [Hex-Dragon/PCL2#2620]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我有两个设备 一个在学校一个在家 结果我抱着试一试的心态先解锁了家里电脑的PCL2快照主题 今天来学校又解锁了另一个PCL2的快照主题
寄 

### 重现步骤

啊？

### 日志与附件

啊？

**Comment by zkitefly** [comment]
啊，所以呢？

**Comment by funnyyyyyyyy** [comment]
所以可能就有白嫖的嫌疑

**Comment by funnyyyyyyyy** [comment]
要是把快照版发给别人 然后再把他的解锁码复制过来就能升级了

**Comment by iPodtouch6557** [comment]
那你也不是拿这个交issue啊……

**Comment by funnyyyyyyyy** [comment]
啊

**Comment by so1ve** [comment]
想吐槽可以去discussion

**Comment by LTCatt** [comment]
考虑到有人有两台设备，允许使用两个识别码，再换就会被临时禁用，或者管理员人工介入调查 :/
