### ISSUE TITLE
添加一个额外下载项，使forge与fabric可以兼容

### ISSUE THREAD

**Issue by ren-jian1748** [Hex-Dragon/PCL2#2621]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

岷叔前两天发了一个MOD介绍视频，提到这个MOD可以使forge和fabric兼容，具体参考这个
https://www.bilibili.com/video/BV1MF41117D8/?spm_id_from=333.999.0.0&vd_source=44d6b8b98b80bb6f99eb6b0507d399ec
我觉得这个可以作为一个额外下载项放在自动安装里面

### 原因

这项优化让我可以更方便地加载MOD
如果没有这项优化，我每次都必须手动安装Fabric，让操作变得很麻烦。

**Comment by iPodtouch6557** [comment]
感觉得等等……毕竟这个玩意是新出的

**Comment by Pigeon0v0** [comment]
这个玩意儿很明显还不是很稳定...

如果是我我不会做（

**Comment by LTCatt** [comment]
这种第三方内容暂不考虑……

**Comment by LTCatt** [comment]
这种第三方内容暂不考虑……
