### ISSUE TITLE
账户问题

### ISSUE THREAD

**Issue by hamiguatang** [Hex-Dragon/PCL2#2623]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在第三方登录状态时切换到未登录的正版再返回无法再次使用第三方登录

### 重现步骤

保证处于第三方登录状态例如：little skin并切换到正版账号并尝试登录后返回离线模式

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12444815/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12444816/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12444817/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12444818/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12444819/Log5.txt)

**Comment by zkitefly** [comment]
总感觉这个是网络问题...

![image](https://github.com/Hex-Dragon/PCL2/assets/64117916/826191db-fbce-4afb-a403-697adb7337e9)

**Comment by LTCatt** [comment]
你的描述没怎么听懂……能分步骤说清楚点么

**Comment by MCSteve123** [comment]
> 你的描述没怎么听懂……能分步骤说清楚点么

大概翻译一下，对不对我不知道：
1、登录littleskin
2、从littleskin更换至正版账号
3、从正版账号切换至离线（原文是“尝试登录”，所以可能是在弹出登录界面的状态下切换至离线？）
4、尝试切换至littleskin，结果失败

我也不知道对不对，可以去试试？

**Comment by youzi-2333** [comment]
> 大概翻译一下，对不对我不知道： 1、登录littleskin 2、从littleskin更换至正版账号 3、从正版账号切换至离线（原文是“尝试登录”，所以可能是在弹出登录界面的状态下切换至离线？） 4、尝试切换至littleskin，结果失败
> 
> 我也不知道对不对，可以去试试？

按照这个步骤无法复现……

**Comment by iPodtouch6557** [comment]
请尽快补充复现步骤相关的信息，否则将会因超时未回复而关闭

**Comment by LTCatt** [comment]
由于长时间未回复暂时关闭，若有需要可以在这里继续回复
