### ISSUE TITLE
模组管理列表里更改选项

### ISSUE THREAD

**Issue by AnnualfireCHW** [Hex-Dragon/PCL2#2627]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在考虑**交互逻辑**和**用户习惯**的基础上。可以将左键弹出菜单更改为右键。并将左键保持原来的**启用/禁用**功能。而右键原有的百科搜索功能也可以放到菜单里（应该不难）。原来的贴子已被关闭，我没有办法编辑补充说明。我此次的问题与之前并不一样。仅是更改功能，而不是添加功能。

### 原因

可以用来快速的操作。
#2626

**Comment by LTCatt** [comment]
在使用例如 PCL 的 **工具类软件** 的时候，绝大多数用户 **没有** 按右键的习惯，因此要尽量避免使用右键

**Comment by AnnualfireCHW** [comment]
> 在使用例如 PCL 的 **工具类软件** 的时候，绝大多数用户 **没有** 按右键的习惯，因此要尽量避免使用右键

好吧，既然你不准备优化这个功能那我就回退到之前的版本了。
话说原来的快速禁用安装真的那么难?好像，而且新加出来的这个菜单真的一点用都没有。移除，我也可以到文件夹里进行操作。

**Comment by AnnualfireCHW** [comment]
> 在使用例如 PCL 的 **工具类软件** 的时候，绝大多数用户 **没有** 按右键的习惯，因此要尽量避免使用右键

而且我身边很多人都认为这个新加出来的菜单的设计逻辑有问题。它极大地降低我们的效率

**Comment by LTCatt** [comment]
你可以点左边的红石灯快速启用/禁用（
