### ISSUE TITLE
回声洞出现错误的换行符

### ISSUE THREAD

**Issue by MCSteve123** [Hex-Dragon/PCL2#2628]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如题。

截图：
![换行符截图](https://github.com/Hex-Dragon/PCL2/assets/121204926/d929d9f8-9e06-4962-afcb-1ae39c1e3301)

### 重现步骤

1、使劲点回声洞
2、重复第一步，直到刷出带特殊字符的回声洞
（ps：这玩意比较难刷，好像全洞只有一个……）

### 日志与附件

应该没必要，需要我再发……

**Comment by Chiloven945** [comment]
*看起来是刻意所为

**Comment by MCSteve123** [comment]
> *看起来是刻意所为

也许吧，但是.md文件的“*”是加粗，比如这个：*这是粗体*

**Comment by MCSteve123** [comment]
> *看起来是刻意所为

但是.md文件里“*”是有用的

比如**粗体**和*斜体*

**Comment by MCSteve123** [comment]
> *看起来是刻意所为

.md文件的星号是有用的
比如**粗体**和*斜体*

**Comment by zkitefly** [comment]
“*”类似于一种对话，提示？

例如下面这张图片（我随便找的 Undertale 的图片对话场景）

![image](https://github.com/Hex-Dragon/PCL2/assets/64117916/29a94b71-344a-4788-a580-4de7393b8a54)

总之应该就是这样可以设计的

**Comment by Yue-cn** [comment]
*/n* 是纯属打错，原为"\n"，有换行的作用。
而"*" 是某游戏特有的聊天方式。
（上次是因为引号而炸掉的

**Comment by MCSteve123** [comment]
> _/n_ 是纯属打错，原为"\n"，有换行的作用。 而"*" 是某游戏特有的聊天方式。 （上次是因为引号而炸掉的

看来需要让lm改改

**Comment by zkitefly** [comment]
然后描述中的是 /n，换行符是

**Comment by MCSteve123** [comment]
请加一下label谢谢

**Comment by MCSteve123** [comment]
实际上，我在3天前就发现了这个问题，但是反应太慢刷掉了……

**Comment by MCSteve123** [comment]
话说正式版能用活跃橙吗

**Comment by zkitefly** [comment]
> 话说正式版能用活跃橙吗

不能

**Comment by MCSteve123** [comment]
> > 话说正式版能用活跃橙吗
> 
> 不能

好吧，只能攒钱发12.34档了……

**Comment by MCSteve123** [comment]
好了，12.34档好了，等完成之后给个活跃橙吧，谢谢：8E45-9B1E-FED2-06F9

**Comment by LTCatt** [comment]
你的解锁码：4bzaQ+CCkTEP5EBWz0YLRa+r73zZb6Tn
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by MCSteve123** [comment]
@LTCatt 我识别码好像变了……能重新给一个吗89F7-3C8F-41F8-434F

**Comment by LTCatt** [comment]
你的解锁码：rgFcF9wfRsuhqAZ/Vnz+VGcdSE27pW/e
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by iPodtouch6557** [comment]
啊……不知道是不是没修净
<img width="401" alt="image" src="https://github.com/Hex-Dragon/PCL2/assets/118656946/d94335a8-5b76-4227-ae3e-980fcb329c9b">

**Comment by zkitefly** [comment]
> 啊……不知道是不是没修净
> <img width="401" alt="image" src="https://github.com/Hex-Dragon/PCL2/assets/118656946/d94335a8-5b76-4227-ae3e-980fcb329c9b">
> 

这个※是正常的
