### ISSUE TITLE
支持导入&导出模组及其配置文件

### ISSUE THREAD

**Issue by G-Lemon** [Hex-Dragon/PCL2#2629]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [x] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

在版本设置-Mod管理页面中增加"Mod&配置一键导出"按钮

### 原因

有时候给朋友分享模组时, 朋友对模组不熟悉, 无法更好的配置模组设置
新增这个功能可以更快捷的入手模组

**Comment by zkitefly** [comment]
你为什么不直接将 config 文件夹打包呢

而且 Mod 的配置文件可能还不在这里面呢（

我认为是不会加的（

**Comment by Pigeon0v0** [comment]
与导出整合包功能性质重复

**Comment by LTCatt** [comment]
实质上就是导出整合包……
