### ISSUE TITLE
清理游戏垃圾时偶尔有奇怪的进程占用导致失败

### ISSUE THREAD

**Issue by kipper3832** [Hex-Dragon/PCL2#2631]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

有时连清几下都会有此占用导致失败，等一会再清就没事了
原因放附件里了

### 重现步骤

左键单击"清理游戏垃圾"键

### 日志与附件

22:14:53.026] [Control] 按下按钮：清理游戏垃圾
[22:14:53.071] [Control] 普通弹窗：清理确认
即将清理游戏日志、错误报告、缓存等文件。
虽然应该没人往这些地方放重要文件，但还是问一下，是否确认继续？

在完成清理后，PCL 将自动重启。
[22:14:57.197] [Control] 按下按钮：确定
[22:14:57.198] [Control] 普通弹框返回：1
[22:14:57.234] 清理垃圾失败：文件“C:\Users\right\AppData\Local\Temp\PCL\CompLogo\1044977592404291931.png1177”正由另一进程使用，因此该进程无法访问此文件。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.File.InternalDelete(String path, Boolean checkHost)
   在 PCL.ModBase.DeleteDirectory(String Path, Boolean IgnoreIssue)
   在 PCL.ModBase.DeleteDirectory(String Path, Boolean IgnoreIssue)
   在 PCL.PageOtherTest._Closure$__._Lambda$__15-0()
错误类型：System.IO.IOException

**Comment by zkitefly** [comment]
看起来是清理 pcl 的图片缓存时出错？

**Comment by kipper3832** [comment]
唔得
