### ISSUE TITLE
单选框（或者复选框）识别区域总是向右大出一段距离

### ISSUE THREAD

**Issue by iPodtouch6557** [Hex-Dragon/PCL2#2637]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

该问题早在 Dev 0.0.0 就出现了……但是不确定是不是PCL的问题，就先扔个issue
在鼠标移到一个单选或复选框的右侧时，视觉上鼠标并未碰到这个框，但是却是“鼠标碰到了复选框”的外观，并且可以操作
<img width="427" alt="image" src="https://github.com/Hex-Dragon/PCL2/assets/118656946/67b24e11-054c-4919-b305-d91ae1e3fdc7">

### 重现步骤

1、随便找一个复选框或单选框
2、把鼠标移到其右侧一段距离，就可复现

### 日志与附件

复现很容易，要我传log我再补吧

**Comment by MCSteve123** [comment]
复现成功，可以在离线皮肤处最右边按钮测试

**Comment by MCSteve123** [comment]
等一个Collaborator来上Label~

**Comment by zkitefly** [comment]
我觉得这是正常的，龙猫肯定会拒

**Comment by iPodtouch6557** [comment]
主要是我认为这跟复选框的实际外观不符，但我觉得可能并非龙猫能修复的问题，不过先扔个issue再说

**Comment by MCSteve123** [comment]
要不Collaborator先来加个`待处理`吧

**Comment by hejiehao** [comment]
你指的是像这样？

https://github.com/Hex-Dragon/PCL2/assets/98140773/8ac34dca-f95d-4c6d-8cb0-47effa048dc3

**Comment by MCSteve123** [comment]
> 你指的是像这样？
> 
>  2023-08-29.16-14-23.mp4

应该是的

**Comment by MCSteve123** [comment]
有没有人看看我的两个存储库啊……我特喵挂了好几个月了，一个watch都没有！
（虽然两个都没协议，但是已经有一个开源项目在做了喂）

**Comment by MCSteve123** [comment]
> 为什么我们必须看你的repo？ 另外，我看可以，但你不应该在这里发……

没说必须，只是找人看看，另外我也没地方给别人看啊，我身边没有人会编程……

**Comment by iPodtouch6557** [comment]
感觉确实不是PCL可以解决的问题，因为Windows系统设置也这样……

**Comment by LTCatt** [comment]
这是刻意的，为了增加操作容错……
