### ISSUE TITLE
意外的可以通过留空文本标题栏来实现空标题

### ISSUE THREAD

**Issue by iPodtouch6557** [Hex-Dragon/PCL2#2638]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如题
我认为标题设置里有了“无”这个选项就不应当允许空的自定义标题栏

### 重现步骤

1、在 _设置-个性化-标题栏_ 里选中 _文本_ 选项
2、留空文本标题栏
3、bug复现，并且空白状态可以保留

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12460949/Log1.txt)

**Comment by MCSteve123** [comment]
应该不会修，没必要

**Comment by MCSteve123** [comment]
@LTCatt 一个多小时了，一个Collaborator都没来，你是不是应该负点责任啊……

**Comment by MCSteve123** [comment]
> @LTCatt 一个多小时了，一个Collaborator都没来，你是不是应该负点责任啊……

要么多几个Collaborator，搁那摆了一堆反馈，没人管可真虾头

**Comment by hejiehao** [comment]
> > @LTCatt 一个多小时了，一个Collaborator都没来，你是不是应该负点责任啊……
> 
> 要么多几个Collaborator，搁那摆了一堆反馈，没人管可真虾头

人家只是自愿的啊，他们没有义务去管这个

**Comment by MCSteve123** [comment]
> > > @LTCatt 一个多小时了，一个Collaborator都没来，你是不是应该负点责任啊……
> > 
> > 
> > 要么多几个Collaborator，搁那摆了一堆反馈，没人管可真虾头
> 
> 人家只是自愿的啊，他们没有义务去管这个

知道啊但是一个人都没有，实在有点尴尬……

**Comment by hejiehao** [comment]
> @LTCatt 一个多小时了，一个Collaborator都没来，你是不是应该负点责任啊……

龙猫也不是24小时在线的啊

**Comment by MCSteve123** [comment]
> > @LTCatt 一个多小时了，一个Collaborator都没来，你是不是应该负点责任啊……
> 
> 龙猫也不是24小时在线的啊

（我也没让他立刻处理）

**Comment by hejiehao** [comment]
看 #775

**Comment by MCSteve123** [comment]
懂，我只是觉得有点怪，因为两天前的Iusse半小时内就有人管了

**Comment by MCSteve123** [comment]
@hejiehao 咱要不把这一堆讨论删了，看着太吓人了

**Comment by LTCatt** [comment]
我觉得这个可以留空才是符合直觉的……
