### ISSUE TITLE
无意中发现的头像BUG

### ISSUE THREAD

**Issue by Enigma-Soul** [Hex-Dragon/PCL2#2641]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

离线版更改皮肤的时候，头像发生偏移

### 重现步骤

1、点击设置中的游戏
2、点击离线皮肤
3、点击自定义，更改皮肤
4、上传皮肤选择steven
5、打开主页，头像就偏移了
PS：正版没事

### 日志与附件

[Log.txt](https://github.com/Hex-Dragon/PCL2/files/12462516/Log.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12462518/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12462519/Log2.txt)
<其他的被删除了，没有调用>

**Comment by Enigma-Soul** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/119654171/a560434d-5da2-4753-914e-431f65db3ef5)
![image](https://github.com/Hex-Dragon/PCL2/assets/119654171/5a18c28b-05b2-4ec1-a4f8-2cdda5382af3)

**Comment by zkitefly** [comment]
会不会是细手臂？

**Comment by Enigma-Soul** [comment]
?

**Comment by Enigma-Soul** [comment]
不是

**Comment by Yue-cn** [comment]
请发出皮肤原图，便于查看是偏移到哪的问题 :)

**Comment by Enigma-Soul** [comment]
Enigma_Soul，正版皮肤，保存一下...

**Comment by MCSteve123** [comment]
> Enigma_Soul，正版皮肤，保存一下...

未能重现，要不提供一下更精确的重现方法？

**Comment by LTCatt** [comment]
无法复现，提供一个其他人可以复现的方法？

**Comment by Enigma-Soul** [comment]
1，下载皮肤
![连锁方块](https://github.com/Hex-Dragon/PCL2/assets/119654171/02b5f661-96ed-49b0-89bc-be3285b4f6be)

2，上传

**Comment by Enigma-Soul** [comment]
使用某个正版玩家的皮肤就不行

**Comment by Enigma-Soul** [comment]
还要补充啥信息啊？

**Comment by Enigma-Soul** [comment]
我的皮肤真好看？

**Comment by iPodtouch6557** [comment]
> 我的皮肤真好看？

lol

**Comment by WTP016-CN** [comment]
> 还要补充啥信息啊？

无法复现，提供一个其他人可以复现的方法

**Comment by LTCatt** [comment]
复现出来了，不用补充信息了（

**Comment by LTCatt** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/d62c718c-a90d-422c-91ef-4c14d04efa30)
这应该是这张图片的原因，它有一些很诡异的 DPI 设定……我不知道咋修

**Comment by Enigma-Soul** [comment]
@LTCatt 你可以想一想为什么正版皮肤不会偏移，通过这个修一下🤣

**Comment by LTCatt** [comment]
因为正版皮肤的图片设定是标准的，但这是一张设定非常不标准的图片
