### ISSUE TITLE
Minecraft1.20.1支持JDK19.0.2

### ISSUE THREAD

**Issue by Minecraft22H2** [Hex-Dragon/PCL2#2643]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

手动将游戏Java设置为JDK19 (19.0.2)  后 ，启动Minecraft1.20.1时启动器弹出“设置中制定了使用Java19，但当前版本需要Java17~18,这可能导致游戏崩溃”，但游戏正常启动，未出现崩溃现象。

### 重现步骤

1、手动将游戏Java设置为JDK19 (19.0.2）64位。
2、启动Minecraft 1.20.1。
3、启动过程中弹出“设置中制定了使用Java19，但当前版本需要Java17~18,这可能导致游戏崩溃”。
4、游戏正常启动，未出现崩溃现象。

### 日志与附件

[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12470777/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12470778/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12470779/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12470780/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12470781/Log3.txt)

**Comment by hejiehao** [comment]
可能

**Comment by zkitefly** [comment]
https://github.com/Hex-Dragon/PCL2/issues/309

**Comment by Minecraft22H2** [comment]
> #309

PCL2并未自动选择JDK19

**Comment by zkitefly** [comment]
> > #309
> 
> PCL2并未自动选择JDK19

我认为pcl不选择jdk19是正确的，高版本java并不适合mc

**Comment by MCSteve123** [comment]
应该是PCL没有把JDK19列入支持1.20.1的JAVA版本吧……

**Comment by Minecraft22H2** [comment]
> 应该是PCL没有把JDK19列入支持1.20.1的JAVA版本吧......

是的

**Comment by MCSteve123** [comment]
所以lm不在？

**Comment by hejiehao** [comment]
> 应该是PCL没有把JDK19列入支持1.20.1的JAVA版本吧……

神奇的是你如果只安装Forge就不会弹出这个提示，但是如果你安装了Forge和OptiFine就会弹出这个提示

**Comment by MCSteve123** [comment]
> > 应该是PCL没有把JDK19列入支持1.20.1的JAVA版本吧……
> 
> 神奇的是你如果只安装Forge就不会弹出这个提示，但是如果你安装了Forge和OptiFine就会弹出这个提示

懂了，PCL是觉得Opti和Forge组合之后会让JDK版本变低！1+1<2！
