### ISSUE TITLE
当多选框（比如Java选择）在窗口最下面时，PCL会强制把弹出来的选项列表向下顶出窗口

### ISSUE THREAD

**Issue by iPodtouch6557** [Hex-Dragon/PCL2#2646]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如题
看截图体会
<img width="515" alt="image" src="https://github.com/Hex-Dragon/PCL2/assets/118656946/f31e1a30-a7eb-4ca9-99eb-65fa30304989">

### 重现步骤

1、将一个多选框往下滚到窗口最底下（比如主页预设）
2.点击它，即可复现
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12473867/Log1.txt)

### 日志与附件

传错了，到重现步骤里了（

**Comment by MCSteve123** [comment]
重现成功
![image](https://github.com/Hex-Dragon/PCL2/assets/121204926/8290b3a8-b1a3-44d7-8e88-642ad08c92b4)

**Comment by MCSteve123** [comment]
重现成功
![image](https://github.com/Hex-Dragon/PCL2/assets/121204926/ff45f48f-f417-488c-aea9-f8ee0978c6d9)

**Comment by LTCatt** [comment]
这是预期行为……
