### ISSUE TITLE
添加更便捷的页面拖拽

### ISSUE THREAD

**Issue by iPodtouch6557** [Hex-Dragon/PCL2#2648]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

![image](https://github.com/Hex-Dragon/PCL2/assets/118656946/8f3f13e0-d0d2-4d2a-ab2f-adbe265d4c4e)
比如……就像这样
当然也可以加鼠标中键上下滚动

### 原因

我需要这个功能来更方便的滚动页面。很多人都有滚动页面的需求，但如果没有这个功能，就会有不方便。

**Comment by zkitefly** [comment]
怎么尽提这些不太可能加入的功能呢（

**Comment by LTCatt** [comment]
暂不考虑，抱歉
