### ISSUE TITLE
下载管理界面

### ISSUE THREAD

**Issue by lvjiajjjlzy** [Hex-Dragon/PCL2#265]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

下载管理界面，左侧进度百分比可能异常，下载完成的进度也不会消失

### 重现步骤

下载东西就好了

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/9839095/Log1.txt)

**Comment by lvjiajjjlzy** [comment]
![image](https://user-images.githubusercontent.com/103650510/197385191-b75edd88-e527-4740-a327-3ded4c093277.png)

**Comment by LTCatt** [comment]
具体描述一下重现步骤，光是一句 “下载东西就好了” 可重现不出来……

**Comment by LTCatt** [comment]
长期未回复关闭

**Comment by WForst-Breeze** [comment]
#853 出现相似问题
