### ISSUE TITLE
主页预设“你知道吗？”不会随着hints.txt的更改而变动

### ISSUE THREAD

**Issue by lyzzs10** [Hex-Dragon/PCL2#2650]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

**启动**界面”**你知道吗？**“栏目无法随着在PCL文件夹内**hints.txt**的自定义而改变
并且启动游戏界面的你知道吗发生了改变

### 重现步骤

1、在PCL文件夹下新建hints.txt以自定义”你知道吗？“
2、在设置→个性化→主页→预设
3、将“主页预设”改为”你知道吗？“
4、回到“启动”界面，此时”启动“界面的”你知道吗？“不会随着hints.txt的更改而更改，而启动游戏中的你知道吗发生了改变

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12482322/Log1.txt)

**Comment by lyzzs10** [comment]
lssue

**Comment by lyzzs10** [comment]
lssue 6740-FCF7-11ED-6B9D

**Comment by LTCatt** [comment]
你的解锁码：ETUwtLvDNNqc5sjeP1E+OXPxjiCO/Lga
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by lyzzs10** [comment]
Issue 36AA-DB51-5696-C4E5

**Comment by LTCatt** [comment]
识别码 36AA-DB51-5696-C4E5 的土豆码是：【CD11DDOJUPZoZzzxUCSXZxPb+JmUtkD0+/VS8D9EX2XMw7847hAa7fG0oO9tf/mBKvb6ULtvQnjCQ5NhGsE5+YooNQpp#VGhlbWU5】
在【更多 → 关于与鸣谢 → 输入土豆码】中使用，谢谢支持～
