### ISSUE TITLE
音乐播放器将office（word,powerpoint,excel）文件误识别为音乐文件

### ISSUE THREAD

**Issue by JIAZIYI007** [Hex-Dragon/PCL2#2651]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在查bug的时候，我发现office文件会被自动识别音乐文件，并提示无法播放。如下图所示：
![屏幕截图 2023-08-31 143611](https://github.com/Hex-Dragon/PCL2/assets/92246404/a0fee023-485b-46d5-8f6a-9c5550797d16)
然而，非office文件不会误识别，会提示未检测到可用的背景音乐，如下图所示。
![屏幕截图 2023-08-31 143732](https://github.com/Hex-Dragon/PCL2/assets/92246404/4a79537a-3d7f-4e15-b7ef-73df3477a1fa)
（音乐文件夹里有文件，但不是音乐文件）
希望龙猫能解决这个bug。

### 重现步骤

1、进入设置-个性化
2、往下滚，然后点击背景音乐中的打开文件夹
3、新建一个office文档（powerpoint、excel、word）
4、在pcl上点击刷新背景音乐

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12483262/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12483263/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12483264/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12483265/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12483266/Log5.txt)

**Comment by JIAZIYI007** [comment]
log1和log2里有记录

**Comment by JIAZIYI007** [comment]
11

**Comment by JIAZIYI007** [comment]
为什么

**Comment by zkitefly** [comment]
> 为什么

什么为什么，你自己关的哦

**Comment by hejiehao** [comment]
reopen?

**Comment by MCSteve123** [comment]
把它reopen啊，不然lm看不见

**Comment by Chiloven945** [comment]
首先为什么会在放音乐的文件夹放文档……
PCL不可能弄个可能是音频文件的列表挨个筛查一遍然后看看是不是音频文件然后再选择报错吧……

**Comment by kong-que-dnf123** [comment]
说实话这东西不如当一个“优化”提案，毕竟谁没事会往音乐文件里塞文档（）
充其量就算是龙猫偷懒没有给music文件夹塞个自检而已（bushi）

**Comment by burningtnt** [comment]
…… 我估计 PCL2 就是调用了 VB 的音乐播放 API……，然后一个 try-catch 捕获错误……
这样做是为了防止有 VB 支持的音乐格式，但 PCL2 无法识别，坏处是某些根本不可能是音乐格式的也会被播放

建议：不做更改，保持原样

**Comment by JingHai-Lingyun** [comment]
应该不会有人（故意）把非音乐文件塞到 /PCL/Musics 里吧。。。
同意楼上

**Comment by LTCatt** [comment]
WAI
