### ISSUE TITLE
安装 MMC 整合包时读取 instance.cfg 的相关可使用的参数

### ISSUE THREAD

**Issue by zkitefly** [Hex-Dragon/PCL2#2655]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

我发现 PCL 在安装 MMC 整合包时并不会按照 instance.cfg 的设置进行，例如 JvmArgs 等

### 原因

一些整合包会需要这些设置，不的话该整合包无法使用

### 其他

放一张自定义命令的图

![image](https://github.com/Hex-Dragon/PCL2/assets/64117916/eda113a1-d2e9-4fdb-a0df-8b1dc2296d95)

```
预执行命令会在实例开始之前运行，后执行命令会在实例结束之后运行。
它们均会在在本启动器的工作目录执行，并带有以下额外环境变量：
$INST_NAME - 实例名称
$INST_ID - 实例 ID (其文件夹名)
$INST_DIR - 实例的绝对路径
$INST_MC_DIR - Minecraft 的绝对路径
$INST_JAVA - 运行所使用的 Java 可执行文件
$INST_JAVA_ARGS - 运行所使用的命令行参数
包装命令允许使用一个额外的包装程序来运行游戏（例如Linux上的 "optirun"）
```

**Comment by WTP016-CN** [comment]
可行

**Comment by LTCatt** [comment]
有什么用了这个东西的整合包示例吗？

**Comment by zkitefly** [comment]
这个是 TeaCon 2023 使用到的整合包（旧的）

https://archive.teacon.cn/2023/modpack/TeaCon2023.zip
