### ISSUE TITLE
启动器个性化功能丢失

### ISSUE THREAD

**Issue by 1027NASA** [Hex-Dragon/PCL2#2662]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

无个性化更能[https://img1.imgtp.com/2023/09/03/diLqZKDf.png](url)
且更换启动器放回原目录无效

### 重现步骤

1、点击设置
2、可见没有个性化功能

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12504917/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12504919/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12504920/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12504921/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12504922/Log5.txt)

**Comment by zkitefly** [comment]
按一下 F12 看看？

**Comment by hejiehao** [comment]
~~疑似骗活跃橙的~~

**Comment by iPodtouch6557** [comment]
这个可能是“急切想要”活跃橙的，要不就是真的出问题了，但是似乎使用信息未补全
而且更魔幻的一点是，log4无法下载.jpg

**Comment by hejiehao** [comment]
> 这个可能是“急切想要”活跃橙的，要不就是真的出问题了，但是log里似乎并未提供相关内容 而且更魔幻的一点是，log4无法下载.jpg 以及这几个log的时间极为相近，就几分钟

![image](https://github.com/Hex-Dragon/PCL2/assets/98140773/4d21a752-9dbe-47df-b7fa-53b2a038725c)

**Comment by iPodtouch6557** [comment]
好吧，个人问题，卡bug了

**Comment by iPodtouch6557** [comment]
另外建议加个等待反馈者……？

**Comment by LTCatt** [comment]
按 F12 检查是否在功能隐藏设置中把个性化关了
