### ISSUE TITLE
在Mod管理添加迁移Mod选项

### ISSUE THREAD

**Issue by IKUN05648** [Hex-Dragon/PCL2#2668]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

在版本设置，Mod管理，选择Mod的时候可以迁移Mod到指定的版本（最好做成版本列表那样的界面，可以当我没说）
![图片](https://github.com/Hex-Dragon/PCL2/assets/130807276/6a6660ea-ff27-41a3-b134-78728fedaccf)

### 原因

有时候在PCL2下载Mod时，一个不小心...**版 本 选 错 了**啊 啊 啊 啊 啊 啊
所以如果加入这个功能，就会非常方便qwq（每次移动Mod老麻烦了）

**Comment by LTCatt** [comment]
用处不大，暂不考虑，抱歉（
