### ISSUE TITLE
模组搜索栏的版本输入框可以写入任意文字

### ISSUE THREAD

**Issue by JJJJGGGG1** [Hex-Dragon/PCL2#2673]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/Hex-Dragon/PCL2/assets/120172412/6c5dae08-74e1-4db1-9018-46e771c597be)
![image](https://github.com/Hex-Dragon/PCL2/assets/120172412/7155f20e-fbeb-447f-9ae3-ab6aa54a7a13)
![image](https://github.com/Hex-Dragon/PCL2/assets/120172412/2fb6df13-14f8-49d2-90b9-521f2105b3dd)

### 重现步骤

1、打开下载--资源--Mod页面
2、在版本输入框随便写点啥

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12558036/Log1.txt)

**Comment by zkitefly** [comment]
本来就可以，这是为了输入折叠项里面没有的版本

**Comment by JJJJGGGG1** [comment]
但是为什么中文和英文也可以输入啊
谁家MC版本号有中文啊（测试版有英文字母）

**Comment by zkitefly** [comment]
:thinking: 

确实应该限制一下文本输入类型

**Comment by LTCatt** [comment]
没有必要改这个……有啥意义么
