### ISSUE TITLE
<“版本选择”允许直接转路径>提案

### ISSUE THREAD

**Issue by kong-que-dnf123** [Hex-Dragon/PCL2#2675]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在<_版本选择_>的<_添加已有文件夹_>方面请求支持
**在文件夹列表中直接修改文件夹列表指向路径**

### 原因

这项优化让我可以更方便地在服务器更新时重新导入服务器文件。
如果没有这项优化，我每次都必须将**原来的文件夹<移出列表>然后重新<添加已有文件夹>**，让操作变得很麻烦。
![image](https://github.com/Hex-Dragon/PCL2/assets/120994373/eceeeaca-d343-4ca2-b261-9312cf0de7a8)

**Comment by zkitefly** [comment]
确实可以？🤔

**Comment by LTCatt** [comment]
一般不需要此类选项，暂时不考虑，抱歉 :/
