### ISSUE TITLE
希望在安装游戏时增加 选择安装钠版本的选项。

### ISSUE THREAD

**Issue by AomiRaku** [Hex-Dragon/PCL2#2682]
### 检查项

- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

希望在安装游戏时增加 选择安装钠版本的选项，方便fabric用户快速安装钠模组。
（这个界面）
![image](https://github.com/Hex-Dragon/PCL2/assets/33995671/240f7612-f7d1-464c-a37d-774dea915988)

### 原因

方便fabric用户快速安装钠模组。基本上大部分fabric玩家都会安装钠。但如果没有这个功能，每次都必须手动安装，比较麻烦。

**Comment by kong-que-dnf123** [comment]
好想法
接下来就是看龙猫的预期值了（）

**Comment by LTCatt** [comment]
不会通过将常用 Mod 加入自动安装列表的申请，要不然这个列表只会越来越长……
