### ISSUE TITLE
下载界面中铷·扩展的前置mod为Embeddium

### ISSUE THREAD

**Issue by wenjianjiaya** [Hex-Dragon/PCL2#2683]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

铷·扩展前置是铷，也可以用Embeddium代替，但下载界面铷·扩展为Embeddium，现在铷比Embeddium效果好，前置应显示效果更好的铷

### 重现步骤

1、点击下载
2、搜索铷·扩展，点击
3、前置mod错误

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12567631/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12567632/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12567633/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12567634/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12567630/Log5.txt)

**Comment by hejiehao** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/98140773/7f4e37cb-0f77-4a10-86c8-4bb24d7a4ebf)
![image](https://github.com/Hex-Dragon/PCL2/assets/98140773/a4b4ea25-1d09-4f9b-ab28-f78c9fe1f1e2)
API 返回来的是 Embeddium

**Comment by wenjianjiaya** [comment]
&nbsp;


文件夹呀
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月10日(星期天) 下午2:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Hex-Dragon/PCL2] 下载界面中铷·扩展的前置mod为Embeddium (Issue #2683)





 

 
 API 返回来的是 Embeddium

**Comment by hejiehao** [comment]
> &nbsp; 文件夹呀 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年9月10日(星期天) 下午2:26 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [Hex-Dragon/PCL2] 下载界面中铷·扩展的前置mod为Embeddium (Issue #2683) API 返回来的是 Embeddium — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

？

**Comment by wenjianjiaya** [comment]
？？？
&nbsp;


文件夹呀
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月10日(星期天) 下午2:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Hex-Dragon/PCL2] 下载界面中铷·扩展的前置mod为Embeddium (Issue #2683)





  
&nbsp; 文件夹呀 @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2023年9月10日(星期天) 下午2:26 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [Hex-Dragon/PCL2] 下载界面中铷·扩展的前置mod为Embeddium (Issue #2683) API 返回来的是 Embeddium — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
？

**Comment by LTCatt** [comment]
你应该让原作者修改……
