### ISSUE TITLE
支持安装快照版本的模组

### ISSUE THREAD

**Issue by yeexyee** [Hex-Dragon/PCL2#2684]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

很多支持库都有支持快照版本的版本，这不得加一下？

### 原因

（示例）
这项优化让我可以更方便地下载模组。
如果没有这项优化，我每次都必须用HMCL下载，让操作变得很麻烦。

**Comment by hejiehao** [comment]
怎么不支持快照版本了？

**Comment by yeexyee** [comment]
> 

大哥，我说的是PCL2不支持自动下载快照版本中的模组啊（

**Comment by hejiehao** [comment]
> > 
> 
> 大哥，我说的是PCL2不支持自动下载快照版本中的模组啊（

![image](https://github.com/Hex-Dragon/PCL2/assets/98140773/431acabe-50fe-4cc2-a23f-769db14154de)

**Comment by yeexyee** [comment]
> > > 
> > 
> > 
> > 大哥，我说的是PCL2不支持自动下载快照版本中的模组啊（
> 
> ![image](https://user-images.githubusercontent.com/98140773/266830012-431acabe-50fe-4cc2-a23f-769db14154de.png)

我说的是除了这个B以外，每次都跟着fabric官方更新能没快照版吗，其他支持库也有啊（

**Comment by yeexyee** [comment]
TMD，为啥别的也有啊（
