### ISSUE TITLE
可以更换主题的正式版

### ISSUE THREAD

**Issue by yeexyee** [Hex-Dragon/PCL2#2685]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

为已经赞助过的用户提供可以更换主题的特别正式版（代码套用就行了）

### 原因

（示例）
这项优化让我可以更方便地更换主题。
如果没有这项优化，我每次都必须等待快照，让操作变得很麻烦。

**Comment by yeexyee** [comment]
龙猫给我活跃橙！！！！！！

**Comment by hejiehao** [comment]
#2553

**Comment by hejiehao** [comment]
> 龙猫给我活跃橙！！！！！！

放弃吧，要 Bug 类的才有活跃橙

**Comment by yeexyee** [comment]
超

**Comment by kong-que-dnf123** [comment]
@HexDragon-Bot 我就在想连 #2553 都来了不应该是“重复”而不是“忽略”吗.......
