### ISSUE TITLE
添加检测是否为 服务端mod

### ISSUE THREAD

**Issue by RaukaRur** [Hex-Dragon/PCL2#2689]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

在mod列表中添加按钮 查询是否为服务端mod

### 原因

有些整合包并没有给出官方服务端 自己从整合包里面扣mod去mcmods搜是否为服务端mod 实在是麻烦
PCL能不能起到一个对接mcmods来自动查询是否为服务端mod

**Comment by kong-que-dnf123** [comment]
估计得先等等
毕竟对接这东西不说好不好查 _（有的mod我直接查显示没有 点了百度搜索才在百度里出现这个MOD.....）_
关键这东西会不会需要 **“第三方（MCMOD）”**？

**Comment by LTCatt** [comment]
mod 作者不一定会正确填写这个信息，没法
