### ISSUE TITLE
PCL闪退

### ISSUE THREAD

**Issue by ErrorFitLX** [Hex-Dragon/PCL2#2693]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在启动器界面时突然闪退，启动器原图标文件会闪没，但是文件会保留，需要重新下载启动器原图标文件
我已经连续下载5次启动器原图标文件了，第4次坚持了较长时间，第5次还未闪退

### 重现步骤

完全随机，可能下一秒，也可能过一段时间

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12614583/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12614584/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12614585/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12614586/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12614587/Log5.txt)

**Comment by LTCatt** [comment]
#666
