### ISSUE TITLE
生成的主页教学文件有问题

### ISSUE THREAD

**Issue by ItIsNotAPlayer** [Hex-Dragon/PCL2#2695]
### 检查项

- [x] 我已在 [Issues 页面](https://githubfast.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://githubfast.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

<img width="576" alt="屏幕截图 2023-09-16 175654" src="https://github.com/Hex-Dragon/PCL2/assets/102716584/75a8fc66-9738-4982-ac2d-888cde9c843c">

启动器版本：快照2.6.8

### 重现步骤

1、点击设置 -> 个性化 -> 主页 -> 生成教学文件
2、刷新主页
3、无法加载文件

### 日志与附件

[Log1.txt](https://githubfast.com/Hex-Dragon/PCL2/files/12640376/Log1.txt)

**Comment by JingHai-Lingyun** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/109946426/84c60c40-c6f9-41e9-9209-ebbb4aab7149)
确认此 Bug 存在并导致尝试进入 `帮助>个性化>自定义主页与帮助 XMAL 格式` 时报错
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12641784/Log1.txt)

**Comment by iPodtouch6557** [comment]
已确认问题存在，
![image](https://github.com/Hex-Dragon/PCL2/assets/118656946/a1402429-268f-4117-a131-c62ae223abd7)
附上log
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12642120/Log1.txt)

**Comment by kong-que-dnf123** [comment]
这不会是新版本把这个误删了吧
![image](https://github.com/Hex-Dragon/PCL2/assets/120994373/f8b1ac36-b20f-4f4e-a2c0-340ca07f475f)

**Comment by kong-que-dnf123** [comment]
还有你这个 _<D:\Minecraft\MinecraftServer\Luncher\Plain Craft Luncher\PCL\hints.txt>_.......
这不是 **自定义《你知道吗》** 的时候让我们创建的文件吗？？？
![image](https://github.com/Hex-Dragon/PCL2/assets/120994373/cafbc0d9-23f0-4047-bf23-587cd8178ade)

**Comment by kong-que-dnf123** [comment]
> 还有你这个 _<D:\Minecraft\MinecraftServer\Luncher\Plain Craft Luncher\PCL\hints.txt>_....... 这不是 **自定义《你知道吗》** 的时候让我们创建的文件吗？？？ ![image](https://user-images.githubusercontent.com/120994373/268487680-cafbc0d9-23f0-4047-bf23-587cd8178ade.png)

![image](https://github.com/Hex-Dragon/PCL2/assets/120994373/56ab8256-9cda-4568-8d6f-b21f07be0129)
