### ISSUE TITLE
建议添加注册表项区分赞助版和正式版

### ISSUE THREAD

**Issue by SuoHouDaiShi** [Hex-Dragon/PCL2#2696]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

我是一个<del>臭</del>做整合包的，因为PCL2的条款是**不允许使用**快照版启动器进行整合包发布的，所以我的电脑中有着快照版也有正式版……
因为快照版已经达到了**23.33及以上**的档位，所以**理应来说**我在整合包的那个启动器**不应该弹出**赞助提示，但是目前PCL2**尚未实现**这一功能，所以在每次启动游戏时我都能看见赞助提示
例如这样：
![图片](https://github.com/Hex-Dragon/PCL2/assets/119282947/28c9288b-f189-43f2-a49c-6f525beb72f6)
所以我认为应该添加一个注册表项，大概思路如下：
在PCL2的注册表目录添加一个`DoesUserIsBooster`值，如果**未输入**23.33元档位的解锁码，该值为`0`，但**如果输入了**23.33元档位的解锁码，该值为`1`，当值为`0`的时候，所有在该电脑下的启动器会**包含**赞助提示（包括6.66、12.34元档位的快照版）；当该值为`1`，所有在该电脑下的启动器**隐藏**赞助提示。
导出的注册表值不应该包含这一项。（如果实现了）

### 原因

<del>这个建议真的会被采纳吗</del>
<del>我交这个Issue只是为了让我电脑里的PCL稍微文静那么一丢丢（bushi</del>
这项优化能够让**已赞助**的整合包作者**隐藏**赞助提示，方便查看游戏输出等。

**Comment by SALTWOOD** [comment]
支持
但是也可以不打包启动器吧

**Comment by hejiehao** [comment]
> 但是也可以不打包启动器吧

看上面应该也有一些整合包的README所以需要启动器

**Comment by LTCatt** [comment]
正式版代码中不包含检测是否输入解锁码的部分，因为正式版没咋加壳，代码会被反编译，所以这个没辙……

**Comment by SuoHouDaiShi** [comment]
> 正式版代码中不包含检测是否输入解锁码的部分，因为正式版没咋加壳，代码会被反编译，所以这个没辙……

好吧QAQ
