### ISSUE TITLE
通过shift批量选择mod

### ISSUE THREAD

**Issue by zhiqin14** [Hex-Dragon/PCL2#2697]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在版本设置中的mod管理中选择mod时按住shift不能批量选择，希望改成与explorer一样的操作方式

### 原因

这项优化让我可以更方便地对mod进行操作。
如果没有这项优化，我每次都必须挨个点击（特别是在mod多的情况下），让操作变得很麻烦。

**Comment by kong-que-dnf123** [comment]
在这个几乎无序的mod列表里滑动选中真的有用处吗（？）

**Comment by hejiehao** [comment]
> 在这个几乎无序的mod列表里滑动选中真的有用处吗（？）

不是无序的

**Comment by kong-que-dnf123** [comment]
> > 在这个几乎无序的mod列表里滑动选中真的有用处吗（？）
> 
> 不是无序的

他不是根据名字首字母顺序来排序吗......
那么顺序不就会随首字母而浮动吗...

**Comment by hejiehao** [comment]
> > > 在这个几乎无序的mod列表里滑动选中真的有用处吗（？）
> > 
> > 
> > 不是无序的
> 
> 他不是根据名字首字母顺序来排序吗...... 那么顺序不就会随首字母而浮动吗...

那不就是有序的咯
而且还可以
![image](https://github.com/Hex-Dragon/PCL2/assets/98140773/09d3fe97-3e2b-4bc2-b12e-451a50809c59)

**Comment by kong-que-dnf123** [comment]
> > > > 在这个几乎无序的mod列表里滑动选中真的有用处吗（？）
> > > 
> > > 
> > > 不是无序的
> > 
> > 
> > 他不是根据名字首字母顺序来排序吗...... 那么顺序不就会随首字母而浮动吗...
> 
> 那不就是有序的咯 而且还可以 ![image](https://user-images.githubusercontent.com/98140773/268493745-09d3fe97-3e2b-4bc2-b12e-451a50809c59.png)

可我喜欢给mod前面加批注，然后就乱了...

**Comment by JingHai-Lingyun** [comment]
PCL2 以模组首字符的顺序进行排序
---
另外 请不要**过多**的讨论与本 Issue 无关的内容，以防 Issue 被锁定

**Comment by LTCatt** [comment]
如果做了 #2333 就不需要这个了

**Comment by LTCatt** [comment]
仔细寻思了一下，暂时不考虑制作快速选择相关的功能，这些都超出启动器范畴了：它不是 Mod 管理器，也不是文件管理器……
抱歉 :/
