### ISSUE TITLE
爱发电私信更新密钥错误

### ISSUE THREAD

**Issue by ACGPlanck** [Hex-Dragon/PCL2#2699]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

大约半个月以前重装了一次系统，当时爱发电私信更新密钥的时候发现无论怎么输更新命令和识别码，回复的密钥都是错误的。今天又试了一次，结果它回复了正确的密钥，如下图所示。

这合理吗.png

<img width="531" alt="fc1ed2a9b42d517bc8ba112830eebc2" src="https://github.com/Hex-Dragon/PCL2/assets/116817880/5e60942c-985c-4933-9a90-3e1cef52afb2">
<img width="531" alt="d858fb7b83ce9c56eff417c5678700b" src="https://github.com/Hex-Dragon/PCL2/assets/116817880/13e0adfd-05b1-462d-bcf3-b721e509235d">

### 重现步骤

爱发电输入解锁命令（有概率触发）

### 日志与附件

本issue不属于PCL本体的bug。

**Comment by kong-que-dnf123** [comment]
这种非PCL的东西还是用Disc吧（？）

**Comment by LTCatt** [comment]
爱发电发【人工】我才能去看……
