### ISSUE TITLE
联机失败

### ISSUE THREAD

**Issue by teyechengyu** [Hex-Dragon/PCL2#270]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

这边写找不到指定的文件，可是我的联机模块还在，没有被杀

### 重现步骤

1、点击联机
2、输入索引码
3.点击创建房间
4.输入端口号
随后给权限后就能看到这一幕

### 日志与附件

[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/9843559/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/9843560/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/9843561/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/9843562/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/9843563/Log3.txt)
![Uploading 56c0580760e2bea2bb028ff822b9171.jpg…]()
![Uploading 7a044ce12fe992518203ced313829c1.jpg…]()

**Comment by Big-Cake-jpg** [comment]
图片未上传完成，请重新上传

**Comment by Big-Cake-jpg** [comment]
？

**Comment by teyechengyu** [comment]
怎么重新发

**Comment by teyechengyu** [comment]
![7a044ce12fe992518203ced313829c1](https://user-images.githubusercontent.com/116417209/197319087-449e9608-be2a-4799-bddc-57457d72f7de.jpg)
![56c0580760e2bea2bb028ff822b9171](https://user-images.githubusercontent.com/116417209/197319088-3aa9059f-b523-4ef2-984e-4e83fbfa96fa.jpg)

**Comment by teyechengyu** [comment]
这样行吗

**Comment by Big-Cake-jpg** [comment]
你可以使用记事本/VSCode等文本编辑器打开 `HiPer 联机模块.vbs` 文件并把内容展示出来吗

**Comment by teyechengyu** [comment]
打开啥？

**Comment by teyechengyu** [comment]
我QQ是2183142636

**Comment by Big-Cake-jpg** [comment]
> 你可以使用记事本/VSCode等文本编辑器打开 `HiPer 联机模块.vbs` 文件并把内容展示出来吗

^

**Comment by teyechengyu** [comment]
ok

**Comment by teyechengyu** [comment]
createobject("wscript.shell").run """C:\Users\yejia\AppData\Roaming\PCL\?机模?\HiPer ?机模?.exe"" v", 0

**Comment by teyechengyu** [comment]
显示这个、

**Comment by LTCatt** [comment]
> createobject("wscript.shell").run """C:\Users\yejia\AppData\Roaming\PCL?机模?\HiPer ?机模?.exe"" v", 0

把这个文件的内容直接作为附件发出来，不要复制粘贴。
内容里出现了莫名其妙的问号，我不确定是文件本身就有问号还是其他问题。

**Comment by teyechengyu** [comment]
不支持文件怎么办

**Comment by Big-Cake-jpg** [comment]
将后缀名改为 `.txt` 再上传

**Comment by LTCatt** [comment]
所以等你传文件了就.jpg

**Comment by LTCatt** [comment]
……传的是那个 vbs 文件，不是 exe 文件
把后缀改成 .txt 就能传

**Comment by LTCatt** [comment]
……传的是那个 vbs 文件，不是 exe 文件
把后缀改成 .txt 就能传

**Comment by teyechengyu** [comment]
[HiPer 联机模块.txt](https://github.com/Hex-Dragon/PCL2/files/9887708/HiPer.txt)

**Comment by teyechengyu** [comment]
ok了

**Comment by zkitefly** [comment]
这里可以推荐使用 gsudo 来获取权限

可能在某些平台使用 gsudo 可能无法正常运行，此时可以尝试提示用户以管理员权限启动PCL2

[（参考 HMCL 获取管理员权限）](https://github.com/huanghongxun/HMCL/pull/1763/files#diff-79ec9b3d490c0d2e5446c7c391bd76cb8a3950f1b0f9aa6d9e01ce72d93413f7)

**Comment by LTCatt** [comment]
我不确定修没修好，如果下个版本依然有这个问题，再重新发一次那个文件 =。=
