### ISSUE TITLE
增加第三方服务端下载

### ISSUE THREAD

**Issue by GLaDOS117** [Hex-Dragon/PCL2#2701]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

增加Forge/Paper服务端下载

### 原因

可以快速下载服务端，方便本地架设

**Comment by JingHai-Lingyun** [comment]
PCL2 是启动器，此功能超出了启动器的范畴。请见 #108
---
另外，下次提交 Issue 时请参考 #2663 中的内容，先进行内容检索
