### ISSUE TITLE
[Bug] 删除客户端时 UI 假死

### ISSUE THREAD

**Issue by JingHai-Lingyun** [Hex-Dragon/PCL2#2702]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

当一个客户端有大量文件，操作系统无法立即删除，需要一定时间时
启动器的 UI 会在点击 确定 后进入一种假死的状态

### 重现步骤

删除一个非常臃肿的客户端

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12656112/Log2.txt)

**Comment by LTCatt** [comment]
等它卡一卡吧……
