### ISSUE TITLE
回声洞刷新出现自定义“你知道吗”的内容

### ISSUE THREAD

**Issue by kong-que-dnf123** [Hex-Dragon/PCL2#2704]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

**版本：快照版3.6.8（305.0）**
如图所示，我的“百宝箱”中的回声洞出现了我自定义“你知道吗”的内容
_（又及：预设中能挂在主页的“回声洞”尚未测试）_
![image](https://github.com/Hex-Dragon/PCL2/assets/120994373/e1967e26-3f91-4862-80be-a284147374e0)
这里是经测试成功刷出第二次
![image](https://github.com/Hex-Dragon/PCL2/assets/120994373/eb17e06c-791d-451c-9686-dea0c31c597a)
这里是我为了编辑“你知道吗”自设的文件
![image](https://github.com/Hex-Dragon/PCL2/assets/120994373/f1edde28-9272-43ab-a43f-d9b6ab1e057d)

### 重现步骤

1、以自定义“你知道吗”的方式开始设置hints.txt（可能设的越多概率越高）
2、在百宝箱中的“回声洞”中反复点击以刷新
3、刷新 直到“你知道吗”所定义的信息出现

### 日志与附件

_（又及：不知道应该扔哪个就全扔进来了......）_
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12663357/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12663358/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12663359/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12663360/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12663364/Log5.txt)

**Comment by kong-que-dnf123** [comment]
已二次测试成功，如图，主页的“回声洞”也会刷新出现hints.txt的文件
![image](https://github.com/Hex-Dragon/PCL2/assets/120994373/e3362702-4a69-42bf-bbc3-817439a595d5)


_（又及：根据刷新，只有log1和log2修改时间改变，遂仅上传这两份文件）_
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12663961/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12663962/Log2.txt)

**Comment by JingHai-Lingyun** [comment]
快照版 3.6.8（雾

**Comment by kong-que-dnf123** [comment]
@LTCatt _这个可以要活跃橙吗......_
识别码：6864-C2F8-4D3C-F1A4

**Comment by LTCatt** [comment]
你的解锁码：18O85j02KvLcKBREQq+tcLkdWZpTkAVe
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
