### ISSUE TITLE
[HMCL KOOK]不符合规范的 json

### ISSUE THREAD

**Issue by hellominecraftlauncher** [Hex-Dragon/PCL2#2705]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

这几个月老是看到这个不符合规范的json，看着也没人提个issue，就凑巧填一个
虽然当时我知道Forge、Optifine在1.13+的一些改动，使PCL安装的游戏有时候无法由HMCL启动（属于是混启动器问题，不过有人喜欢）
然后我就询问了一下，因为PCL安装的时候有一个参数是1.13+不需要的，但是PCL还是创建，但HMCL安装不会，所以产生了分歧（纯记忆，书面文件找到后用Edit补充进去）

### 原因

混启动器的人更好的结合PCL和HMCL来更加方便的使用

**Comment by JingHai-Lingyun** [comment]
> 截图呢？ 日志呢？ ？？？？

拜托 这是优化反馈

**Comment by LTCatt** [comment]
请具体描述是什么玩意儿出了问题，啥不兼容了，如果有互不兼容的版本把复现方法和版本文件传上来，你这样写我只能给你算一卦

**Comment by zkitefly** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/64117916/53484908-a9f0-484d-8bd8-431196a2fc5d)

其实当时想发的，可是因为 Zeker 说他也不太确定，也没人尝试，就直接忘了

![image](https://github.com/Hex-Dragon/PCL2/assets/64117916/2d5b61f8-7c20-4733-af00-844067bc0d08)

[minecraft-exported-crash-info-2023-09-16T13-21-18.zip](https://github.com/Hex-Dragon/PCL2/files/12700652/minecraft-exported-crash-info-2023-09-16T13-21-18.zip)

**Comment by zkitefly** [comment]
> `version json` 多出的 `minecraftArguments` 属性会导致 官启 和 HMCL 无法正确识别 1.13+ 的参数
> 
> PCL的自动安装会把 version json 里的 minecraftArguments 属性留下，但是当 HMCL 识别到version json里有 minecraftArguments 属性时，会把所有原来 arguments 属性里的 games 属性转移到 minecraftArguments 里，因为官启当识别到存在 minecraftArguments 时不会再读取 arguments 了
> 
> 可是PCL2的 `minecraftArguments' 属性是空的，导致缺失了forge所需要的 JVM 参数，这样 HMCL 和官启就启动游戏失败了。
> 
> >引用了@ZekerZhayard的解释
> 
> [minecraft-exported-crash-info-2023-05-23T13-36-41.zip](https://github.com/Hex-Dragon/PCL2/files/11830750/minecraft-exported-crash-info-2023-05-23T13-36-41.zip)
> 
> ![image](https://github.com/Hex-Dragon/PCL2/assets/64117916/57b8781a-50d8-4c01-bca9-4b21497d2cf7)

这个是当时存档的，因为不确定，所以就没法，到后面就忘了这回事

这边建议测试下？

**Comment by hellominecraftlauncher** [comment]
> 请具体描述是什么玩意儿出了问题，啥不兼容了，如果有互不兼容的版本把复现方法和版本文件传上来，你这样写我只能给你算一卦

具体是在HMCL KOOK的崩溃分析频道看到的，以及，可以参考一下这个zkitefly的回复，他这个涵盖了我要说的问题

**Comment by hellominecraftlauncher** [comment]
这个功劳算zkitefly的还是。。龙猫

**Comment by hellominecraftlauncher** [comment]
行，我的识别码：37B5-8AD2-D44C-97BB

**Comment by LTCatt** [comment]
你的解锁码：57ZbNikRlcjPBu4vxrCWiGUKZtOI/v2u
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by HomoobyDX** [comment]
更换机器换识别码了，龙猫能否再发一下
新的识别码：70CC-996A-802E-2137

**Comment by LTCatt** [comment]
你的解锁码：PNLxFTDAV+mo8Fg9QAVzO0RS1/Q5VxGB
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
