### ISSUE TITLE
未将对象引设置对象的实例

### ISSUE THREAD

**Issue by pptawa** [Hex-Dragon/PCL2#2706]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

开不起来）

### 重现步骤

1、点击xxxx
2、往下滚，然后点击xxxx

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12679523/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12679524/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12679525/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12679526/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12679527/Log1.txt)

**Comment by JingHai-Lingyun** [comment]
```log
崩溃分析失败：未将对象引用设置到对象的实例。
   在 PCL.CrashAnalyzer.GetAnalyzeResult(Boolean IsHandAnalyze)
   在 PCL.CrashAnalyzer.Output(Boolean IsHandAnalyze, List`1 ExtraFiles)
   在 PCL.ModWatcher.Watcher._Lambda$__32-0()
错误类型：System.NullReferenceException
```
可见于 Log1~3
但是你这描述和重现步骤？

**Comment by pptawa** [comment]
8D8C-20EA-6C80-5C07

**Comment by LTCatt** [comment]
你的解锁码：NI+q4oiEqsqrtJYAbsbYYVfE7XFmkNl+
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
