### ISSUE TITLE
模组跳转时展开跳转前展开的版本

### ISSUE THREAD

**Issue by WorldHim** [Hex-Dragon/PCL2#2712]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

例如 打开前置模组时展开打开前展开的版本 及 返回原模组时展开原来展开的版本

### 原因

便于选择模组版本

**Comment by ZZZank** [comment]
好拗口。是不是这个意思：
在mod下载页面里，进入一个模组的详细页面，然后展开某一个版本，通过“前置”部分跳转到另一个模组的页面。
希望跳转之后的页面能把前一个模组页面里展开过的版本也展开，其中“展开过的版本”可以指用来跳转的“前置”部分所属的版本

**Comment by JingHai-Lingyun** [comment]
是的

**Comment by WorldHim** [comment]
`A2DF-FF80-5D7F-10A7`

**Comment by LTCatt** [comment]
你的解锁码：7S8sqKn9c93yrdR6lbn709VWp0+ULqzF
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
