### ISSUE TITLE
游戏直接崩溃，卡住两分钟左右游戏窗口关闭，PCL启动器关闭

### ISSUE THREAD

**Issue by xxswyb** [Hex-Dragon/PCL2#2714]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

玩nomi时候（10分钟左右）忽然电脑卡住，不能进行任何有效操作，两分钟左右之后，电脑正常恢复，游戏崩溃，pcl崩溃。
注：游戏并没有产生崩溃的log

### 重现步骤

1、打开任意游戏（RLC，原版Fabric生电端成功率较高）
2、游玩一定时间
3、游戏崩溃，2-5分钟后电脑恢复，启动器有概率自动关闭。

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12715735/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12715736/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12715737/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12715738/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12715739/Log2.txt)

**Comment by LTCatt** [comment]
这个不是启动器导致的问题
