### ISSUE TITLE
自定义主页卡片内滚轮判定问题

### ISSUE THREAD

**Issue by Beggarfish** [Hex-Dragon/PCL2#2716]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

当主页面溢出后对带有内容溢出可使用滚轮的卡片内容，不会优先让鼠标选中的卡片进行滚轮操作，而是对主页进行滚轮操作，希望能改进成鼠标选中可使用滚轮操作的卡片优先进行滚轮操作

```
<ScrollViewer Grid.Column="1" VerticalScrollBarVisibility="Hidden" Height="200">
<local:MyCard Title="测试" Grid.Column="1" Margin="0,0,0,0" CanSwap="false" IsSwaped="false">
		<StackPanel Margin="14,30,14,10">
   <!-- 我这里有非常多的内容，可以让内容溢出而显示滚轮 -->
	      </StackPanel>
            </local:MyCard>
</ScrollViewer>
```

### 原因

这项优化让我可以更方便地制作更好的主页。
如果没有这项优化，我每次都必须使用鼠标进行滚轮操作，让操作变得很麻烦。

**Comment by LTCatt** [comment]
这是 WPF 内置逻辑，不好改 =。=
