### ISSUE TITLE
游戏设置锁定使用的java，不要自动更改

### ISSUE THREAD

**Issue by Har2** [Hex-Dragon/PCL2#2717]
### 检查项

- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

每隔一段时间我整合包的游戏设置中使用的java就会从我选定的java版本变成使用全局设置
导致它用java19启动了1.7.10的整合包，无法正常打开游戏
个人猜测是启动时因未知原因未找到设定的java，故自动变动为使用全局设置
建议锁定功能锁定到绝对路径上，不检测是否有javaw.exe

### 原因

这项优化让我不用每次启动游戏都检查java版本是否被自动更换。

**Comment by Pigeon0v0** [comment]
你可以给全局设置选择自动选择（

**Comment by Har2** [comment]
我就是全局自动选择，他自动给我选了错误的版本，导致我打不开游戏，弱zhi动选择(

**Comment by Har2** [comment]
> 你可以给全局设置选择自动选择（



> 你可以给全局设置选择自动选择（

我全局设置就是自动选择，它自动给我选择了错误的版本，导致我打不开，弱z(h)i动选择

**Comment by JingHai-Lingyun** [comment]
> 每隔一段时间我整合包的游戏设置中使用的java就会从我选定的java版本变成使用全局设置
在版本设置中单独设置的？
听起来是个 Bug？

**Comment by zkitefly** [comment]
请上传启动器日志 Log(1~5).txt

**Comment by Har2** [comment]
> 请上传启动器日志 Log(1~5).txt
最近5次使用没有遇到上述情况，还是贴在这里了
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12755111/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12755116/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12755117/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12755119/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12755123/Log5.txt)

**Comment by zkitefly** [comment]
看起来是偶然现象？

**Comment by LTCatt** [comment]
没法稳定复现比较蛋疼，算了……可能是 #1496 导致的

**Comment by Har2** [comment]
> 没法稳定复现比较蛋疼，算了……可能是 #1496 导致的

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12776361/Log1.txt)
又发生了，这次的Log能看出问题吗

**Comment by LTCatt** [comment]
已确认
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/a055e3bb-0e78-47d6-8156-95b78480122d)

**Comment by LTCatt** [comment]
已在 2.6.8 修复，该更新尚未推送到正式版
