### ISSUE TITLE
“老帐号迁移”修改与跟进

### ISSUE THREAD

**Issue by Louis-ZYH** [Hex-Dragon/PCL2#2718]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

*详见https://help.minecraft.net/hc/en-us/articles/360050865492-Minecraft-Java-Edition-Account-Migration-FAQ （请自备翻译器）（此文章与下文指出文章都将于10月19日删除！）
2023年9月19日，Mojang账户迁移至Microsoft账户时间截止，所有未迁移的Mojang账户，其所属Minecraft游戏信息均已清空。但根据问答页面信息，在2023年12月18日前，未迁移的用户有最后一次机会————可以在该文章（https://help.minecraft.net/hc/en-us/articles/4403183382541 ） （需机翻）的指导下验证其所属Mojang账户，一旦验证成功，微软将为用户指定的Microsoft账户授予一份新的Minecraft Java & 基岩版，但原有所有游戏信息不予保留。
希望PCL2跟进官方信息。
![image](https://github.com/Hex-Dragon/PCL2/assets/115140320/0aade26e-1a30-453f-93d8-fd7b1b12f2bb)

### 原因

详见描述。

**Comment by deep-dark-forest** [comment]
交个pr改下链接？

**Comment by Louis-ZYH** [comment]
> 交个pr改下链接？

 我不会啊

**Comment by JingHai-Lingyun** [comment]
> （此文章与下文指出文章都将于10月19日删除！）

时效性过强了感觉

**Comment by deep-dark-forest** [comment]
> > （此文章与下文指出文章都将于10月19日删除！）
> 
> 时效性过强了感觉 ~本来已经准备好发 PR 的但又回过头来了~

等一下，文章在10月19失效但是

> 在2023年12月18日前，

**Comment by Louis-ZYH** [comment]
> > > （此文章与下文指出文章都将于10月19日删除！）
> > 
> > 
> > 时效性过强了感觉 ~本来已经准备好发 PR 的但又回过头来了~
> 
> 等一下，文章在10月19失效但是，在12月18日之前有mojang账号的人还是可以迁移 所以，这会导致10月19日之后12月18日之前的人可以迁移但是不知道怎么弄
> 
> 把文章转载到一个新的链接？或者在启动器里弹窗简单告诉用户怎么做？

也可以直接把文章翻译下来加进帮助页面，微软这设置的属实是过于rz了

**Comment by Louis-ZYH** [comment]
> > > > （此文章与下文指出文章都将于10月19日删除！）
> > > 
> > > 
> > > 时效性过强了感觉 ~本来已经准备好发 PR 的但又回过头来了~
> > 
> > 
> > 等一下，文章在10月19失效但是，在12月18日之前有mojang账号的人还是可以迁移 所以，这会导致10月19日之后12月18日之前的人可以迁移但是不知道怎么弄
> > 把文章转载到一个新的链接？或者在启动器里弹窗简单告诉用户怎么做？
> 
> 也可以直接把文章翻译下来加进帮助页面，微软这设置的属实是过于rz了

但是我不是很懂帮助库编辑，所以还请大佬指教😃

**Comment by Louis-ZYH** [comment]
[Mojang账户迁移后流程解答.txt](https://github.com/Hex-Dragon/PCL2/files/12754579/Mojang.txt)
个人试着翻译了一下（ChatGPT翻译真的准）

**Comment by zkitefly** [comment]
或许可以？

**Comment by zkitefly** [comment]
或许可以？

**Comment by JingHai-Lingyun** [comment]
我开始做个镜像

**Comment by JingHai-Lingyun** [comment]
那... 改改弹窗的文案？

**Comment by deep-dark-forest** [comment]
> 我看了下源码，这个 `老账号迁移` 是打开 `https://www.minecraft.net/zh-hans/account-security` 来迁移的，你提供的文章中也是说去这里迁移的，所以**我认为没什么必要**，最多是弄个 tooltip，鼠标移上去就会有提示？
> 
> ![image](https://github.com/Hex-Dragon/PCL2/assets/64117916/b06681a9-b01b-4c50-b951-139d483b9010)
> 
> ![image](https://github.com/Hex-Dragon/PCL2/assets/64117916/36c679b0-7b07-435d-82c2-69ebfebe5a49)
> 
> 

也不用，可以把那个什么让你的年龄大于18岁的那个弹窗改一下

**Comment by Louis-ZYH** [comment]
> 那... 改改弹窗的文案？

也可以，提醒一下这时候迁移不保留原有数据

**Comment by Louis-ZYH** [comment]
请问这个能领活跃橙吗？如果能的话，这是我的识别码：2A94-6F3E-189C-0232

**Comment by LTCatt** [comment]
这个也可以算 bug……
你的解锁码：MgZI/VPU8AJucTt2dY8oocYoGdrMw33C
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
