### ISSUE TITLE
音乐报错时只提示一次信息

### ISSUE THREAD

**Issue by deep-dark-forest** [Hex-Dragon/PCL2#2720]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

https://github.com/Hex-Dragon/PCL2/assets/131975043/b037ff95-37b4-4cc4-a3c6-de2260d5643c

注意看，如果我使用了不支持的音乐格式左下角就会一直提示，导致左下角红乎乎一片......

### 原因

提示一遍就行了提示很多次太影响视觉了

**Comment by zkitefly** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/64117916/3192e361-1f3e-4737-9842-388a30396270)

**Comment by deep-dark-forest** [comment]
> ![image](https://user-images.githubusercontent.com/64117916/271281549-3192e361-1f3e-4737-9842-388a30396270.png)

请认真看视频。“crreative1-6”完成以后会重来一遍，无限循环

**Comment by deep-dark-forest** [comment]
> 有没有一种可能
> _谁会一直在文件夹里放一堆不支持的音乐啊......._
> 就算修估计也得推迟

如果是第一次用pcl2的音乐播放功能不知道不支持.ogg格式的音乐呢……

**Comment by JingHai-Lingyun** [comment]
> 如果是第一次用pcl2的音乐播放功能不知道不支持.ogg格式的音乐呢……

没啥人用 `.ogg` 吧 ~~这个格式比较冷门，据我所知只有Minecraft 材质文件用~~

**Comment by zkitefly** [comment]
或许可以改一下？

**Comment by LTCatt** [comment]
看到之后就别放就行了，没有必要修复……
