### ISSUE TITLE
PCL显示java版本过高

### ISSUE THREAD

**Issue by kuankqaq** [Hex-Dragon/PCL2#2721]
### 检查项

- [ ] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃基本不是 PCL 的原因，请 **不要** 提交反馈。你可以在论坛或社区找人求助，但这里并不是你求助的地方。
- [x] **我已尝试使用 HMCL 启动，HMCL 没有出现问题。** 如果 HMCL 也无法启动就不是 PCL 导致的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在启动1.19.2时PCL自动选择java时显示java版本过高，而指定jdk时没有出现问题

### PCL 错误报告、日志与附件

https://wwqu.lanzouq.com/iZ7IM1a57pyd

**Comment by zkitefly** [comment]
自行修改 Java 为 JDK 17

**Comment by LTCatt** [comment]
所以为啥 close 了？

**Comment by kuankqaq** [comment]
不到啊

**Comment by JingHai-Lingyun** [comment]
reopen 把

**Comment by Louis-ZYH** [comment]
JDK17的模组兼容性更好，是得改进一下PCL2的Java自动选择了

**Comment by LTCatt** [comment]
PCL 会 *优先选择* 和 MC 在同一个文件夹的 Java，你把这个 Java 和 MC 都放到同一个文件夹下了
