### ISSUE TITLE
修改屏幕分辨率导致自定义背景自适应方式错误

### ISSUE THREAD

**Issue by Gaobaiawa** [Hex-Dragon/PCL2#2723]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

这个bug貌似是有概率的，我之前经常碰到(电脑配置太垃圾了)，但是刚才想测试的时候又不行了，其实主要是想混个隐藏主题，当然，这个bug是真实存在的，如果已经被修复了，求龙猫大大别喷我，我害怕.....
这个bug在其他程序中也经常出现
当你（设置-屏幕中更改）使用1920x1080分辨率时添加一张图片，如果这时直接去设置将分辨率修改为1280x720，那么pcl2窗口会变得很大，背景图片也会跟着变大，但这是很正常的
这个bug会导致背景图片的自适应方式方式变得错误，即使你重新修改回1920x1080

### 重现步骤

0、设置系统分辨率为1920x1080
1、设置一个背景图
2、然后关闭pcl2
3、修改系统分辨率为1280x720
4、（重启貌似概率会高一些？不清楚，我没有测试重启）
5、打开pcl2观查背景图，会发现自适应变得很怪，即使手动修改也没用，只能把背景文件夹里的图片重新放一遍
6、这个在新版概率似乎变得很低，如果已经被修复了求龙猫大大别喷我，我只是想混个隐藏主题，如果测试不行就算了，也许被修复了呢.....(小声),其实主要是我自己测试没有出现，我也不清楚

### 日志与附件

没有日志哦，或许只是个建议呢，我就放我自己的背景图片咯
![2022_1228_031630](https://github.com/Hex-Dragon/PCL2/assets/123546075/76f6fd4e-1796-4fa4-96db-89b6ce6e6912)
还有我上一次的日志,虽然知道这玩意传上去100%用不到,也没有用
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12752299/Log5.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12752300/Log4.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12752301/Log3.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12752302/Log2.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12752303/Log1.txt)

**Comment by zkitefly** [comment]
https://github.com/Hex-Dragon/PCL2/issues/2224

有可能已解决？

**Comment by LTCatt** [comment]
#2224
