### ISSUE TITLE
支持local:MyHint根据主题颜色变色

### ISSUE THREAD

**Issue by MCSteve123** [Hex-Dragon/PCL2#2726]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

如题
我用了活跃橙，但是却惊奇的发现提示条依然是蓝色的……
![image](https://github.com/Hex-Dragon/PCL2/assets/121204926/58d27180-605e-42f4-9646-f3f4b06c08af)
可能有人会说改了之后提示条和警告条长的一样，但是lm可以顺带改一下警告条的材质……？

### 原因

看着舒服点

**Comment by iPodtouch6557** [comment]
我觉得这是预期内的情况啊

**Comment by LTCatt** [comment]
MyHint 的颜色是表示 “提示” 或 “警告”，所以不会变色
