### ISSUE TITLE
搜索mod出现403错误

### ISSUE THREAD

**Issue by lieyanxd** [Hex-Dragon/PCL2#2727]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

无法搜索mod，出现远程服务器返回错误。

### 重现步骤

1.点击下载-mod
2.搜索一个mod

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12765143/Log2.txt)

**Comment by SALTWOOD** [comment]
无法复现，请尝试切换网络，抑或是提供更详细的步骤。

**Comment by zkitefly** [comment]
你能访问 `https://api.modrinth.com/` 和 `https://optifine.net/downloads` 吗

**Comment by lieyanxd** [comment]
如步骤所说，点开mod下载并搜索formfix（泡沫修复的mod）会出现该问题。不过有时候不会出现。WiFi正确连接。




?
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Hex-Dragon/PCL2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月30日(星期六) 凌晨0:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Hex-Dragon/PCL2] 搜索mod出现403错误 (Issue #2727)





 
无法复现，请尝试切换网络，抑或是提供更详细的步骤。

**Comment by lieyanxd** [comment]
> 你能访问 `https://api.modrinth.com/` 和 `https://optifine.net/downloads` 吗

可以访问

**Comment by zkitefly** [comment]
那我感觉是 Modrinth 的问题，不是 PCL 的问题

**Comment by SALTWOOD** [comment]
无法稳定复现可能不会修复:(
