### ISSUE TITLE
分析器错误

### ISSUE THREAD

**Issue by Turtle9999** [Hex-Dragon/PCL2#2729]
### 检查项

- [ ] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃基本不是 PCL 的原因，请 **不要** 提交反馈。你可以在论坛或社区找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用 HMCL 启动，HMCL 没有出现问题。** 如果 HMCL 也无法启动就不是 PCL 导致的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

网易和PCL都报错：
分析C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machie.config时出错，分析器返回0x80004005。
c盘满了，就用优化大师和腾讯管家清出来20个G

### PCL 错误报告、日志与附件

![image](https://github.com/Hex-Dragon/PCL2/assets/123610059/d4c60572-4dc7-4ed8-a2ae-954923e32245)

混斤拷烫烫烫
×
程序出现未知错误:"System.Windows.Media.Fonts"的类型初始值设定项引
发异常。
由于操作系统或显卡存在问题，导致出现错误。请尝试重启PCL,
详细错误信息:
"System.MarvinHash"的类型初始值设定项引发异常。一文件”
c:xwindows\Microsoft.NET\Framework64\v4.0.30319\configlmachine.config"中元索""附近的XML无效。
一对COM组件的调用返回了错误HRESULTE_FAIL。在PCL.ModSecret.SecretOnApplicationstarto
在PCL.Application.Application_Startup(Object sender,startupEventArgs e)
错误类型: System.Runtime.Interopservices.COMException
是否反馈此问题?如果不反馈，这个问题可能永远无法得到解决!
是(Y)
否(N)
[PCL.zip](https://github.com/Hex-Dragon/PCL2/files/12772848/PCL.zip)

### HMCL 启动脚本

[minecraft-exported-logs-2023-09-30T08-23-12.log](https://github.com/Hex-Dragon/PCL2/files/12772852/minecraft-exported-logs-2023-09-30T08-23-12.log)

**Comment by zkitefly** [comment]
重新安装 .NET Framework 看看？

**Comment by Turtle9999** [comment]
> 重新安装.净框架看看？

如何安装aaa

**Comment by Turtle9999** [comment]
> 重新安装.净框架看看？

之前下载个PCL直接就能启动

**Comment by zkitefly** [comment]
> > 重新安装.净框架看看？
> 
> 如何安装aaa

https://dotnet.microsoft.com/zh-cn/download/dotnet-framework/thank-you/net462-offline-installer

**Comment by Turtle9999** [comment]
> > > 重新安装.净框架看看？
> > 
> > 
> > 如何安装aaa
> 
> [https://dotnet.microsoft.com/zh-cn/download/dotnet-framework/thank-you/net462-offline-installer ](https://dotnet.microsoft.com/zh-cn/download/dotnet-framework/thank-you/net462-offline-installer)

已经安装了这个版本或更高的版本

**Comment by WorldHim** [comment]
看到过类似的错误，但是应该是win7的问题啊🤔

**Comment by Pigeon0v0** [comment]
上述无果的话尝试重置 / 重装系统

**Comment by LTCatt** [comment]
COMException 并非启动器导致的，这是系统问题，我无法修复

**Comment by Turtle9999** [comment]
我重置了一下系统，现在好了
