### ISSUE TITLE
打开PCL后随便点击一个按钮，会卡1-2秒钟不动

### ISSUE THREAD

**Issue by ThriftyAgenda61** [Hex-Dragon/PCL2#273]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

打开PCL后随便点击一个按钮，会卡1-2秒钟不动

### 原因

卡卡的很难受的

**Comment by bwtx2022** [comment]
上传PCL日志（PCL\Log1-5.txt）

**Comment by ThriftyAgenda61** [comment]
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/9845462/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/9845463/Log2.txt)

**Comment by xxtg666** [comment]
是不是电脑性能不太够

**Comment by LTCatt** [comment]
日志中没有任何异常，怀疑只是电脑性能问题……
有没有其他异常表现，例如某些版本正常但是某些版本会卡？如果都卡的话应该单纯只是性能问题……

**Comment by LTCatt** [comment]
日志中没有任何异常，怀疑只是电脑性能问题……
有没有其他异常表现，例如某些版本正常但是某些版本会卡？如果都卡的话应该单纯只是性能问题……

**Comment by ThriftyAgenda61** [comment]
应该是我的问题。感谢回复与支持
