### ISSUE TITLE
使用在MCBBS下载的整合包时出错

### ISSUE THREAD

**Issue by EMUMUI** [Hex-Dragon/PCL2#2730]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

因为文件过大所以只能通过留下下载地址这个方式给您。
整合包下载地址为:https://pan.baidu.com/s/1jBWGkx5qdaWeYJLbEZK8QQ?pwd=ls3b
密码是:ls3b
下载forge或者OptiFine时会卡在4%进度不动，然后提示错误。
报错:
游戏安装失败
→ 下载 OptiFine 1.20.1 I6pre6失败
→ 下载 OptiFine 主文件失败
→ 文件下载失败：H:\Users\AppData\Local\Temp\PCL\Cache\Code\1.20.1-OptiFine_HD_U__I6_pre6_1454
远程服务器返回错误: (404) 未找到。（https://download.mcbbs.net/optifine/1.20.1/HD_U_I6pre6）
远程服务器返回错误: (404) 未找到。（https://bmclapi2.bangbang93.com/optifine/1.20.1/HD_U_I6pre6）
文件大小不足，获取结果为 16，要求至少为 65536。（https://optifine.net/downloadx?f=preview_OptiFine_1.20.1_HD_U__I6_pre6.jar&x=78c058f6de405e24a445026f540f8aec）
远程服务器返回错误: (404) 未找到。（https://optifine.cn/download/preview_OptiFine_1.20.1_HD_U__I6_pre6.jar）
→ 文件大小不足，获取结果为 16，要求至少为 65536。
   在 PCL.ModNet.NetFile.Thread(NetThread Info)

### 重现步骤

1、点击版本选择
2、然后点击左侧的导入整合包
3、点击田园时光然后点击打开

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12774652/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12774653/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12774659/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12774675/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12774714/Log5.txt)

**Comment by zkitefly** [comment]
https://github.com/Hex-Dragon/PCL2/issues/80

:thinking: :
