### ISSUE TITLE
启动时出错

### ISSUE THREAD

**Issue by WenhuarenNB** [Hex-Dragon/PCL2#2735]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我每次启动的时候，都会出现一个失败报告，内容是这样
![image](https://github.com/Hex-Dragon/PCL2/assets/146603292/afbfd22e-ac1a-43b7-b1cc-10ac5a146d2d)
![image](https://github.com/Hex-Dragon/PCL2/assets/146603292/f030b87f-fdde-4bca-903a-d7ce713f36d5)
![image](https://github.com/Hex-Dragon/PCL2/assets/146603292/718af2df-9317-422a-bced-3ec2d4e7900a)

### 重现步骤

点击启动

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12775936/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12775938/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12775939/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12775940/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12775941/Log5.txt)

**Comment by Big-Cake-jpg** [comment]
#2734
