### ISSUE TITLE
minecraft启动失败

### ISSUE THREAD

**Issue by furrystars** [Hex-Dragon/PCL2#2736]
### 检查项

- [ ] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

无法打开游戏

### 重现步骤

正版登录点击启动游戏

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12776072/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12776073/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12776074/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12776075/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12776076/Log5.txt)

**Comment by lactobionicAcid** [comment]
今天工信部抽风了，api封了
解决方法是随便找个梯子  打开全局加速  然后启动一遍正版

**Comment by RadishTower** [comment]
我应该也是这个问题，无法正常启动，原版的也连接不上服务器

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12776265/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12776266/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12776267/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12776268/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12776264/Log1.txt)

**Comment by Big-Cake-jpg** [comment]
#2734

**Comment by lactobionicAcid** [comment]
Discussion:#2738
