### ISSUE TITLE
无法设置未知成员"PCL.MyIconTextButton.ColorType"

### ISSUE THREAD

**Issue by shimenga** [Hex-Dragon/PCL2#2739]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/Hex-Dragon/PCL2/assets/77818664/f74e0156-edc2-4ae8-b7c8-7d4467f7b4b5)

### 重现步骤

1、点击更多
2、往下滚，然后点击个性化里的定义主页与帮助XAML格式

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12776585/Log1.txt)

**Comment by WorldHim** [comment]
补充：生成的教学文件同样有此问题。

**Comment by SALTWOOD** [comment]
复现成功
![image](https://github.com/Hex-Dragon/PCL2/assets/105980161/927ed7c8-6f45-4635-8248-5c32f58a0282)

**Comment by LTCatt** [comment]
#2695
