### ISSUE TITLE
启动时.Net报错

### ISSUE THREAD

**Issue by imfine2333** [Hex-Dragon/PCL2#2751]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在启动启动器时显示.net报错窗口并且无法处理

### 重现步骤

1、点击PCL主程序
2、出现弹窗

### 日志与附件

![屏幕截图(35)](https://github.com/Hex-Dragon/PCL2/assets/109073573/dff38380-d4ab-42f8-9026-842859399f23)

**Comment by WorldHim** [comment]
请提供更多信息

**Comment by LTCatt** [comment]
这是系统问题，我没法解决 :/
