### ISSUE TITLE
搜索Java时不显示Azul Zulu

### ISSUE THREAD

**Issue by winver1234** [Hex-Dragon/PCL2#2752]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我在装了Zulu21之后尝试用PCL的Java搜索功能自动搜索Zulu，结果并没有搜到，打开PCL日志一看，是搜到了Zulu，但是Java列表不显示Zulu，而原版Java21可以被搜到。

### 重现步骤

1.下载Zulu21并安装
2.打开PCL2，在设置→游戏→游戏Java，点击自动搜索

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12817521/Log3.txt)

**Comment by Chiloven945** [comment]
手动添加。

**Comment by TianBoxv587** [comment]
还有dragonwell

**Comment by TianBoxv587** [comment]
> 还有dragonwell

应该是因为源代码运行遍历时没有SearchEntry.Contains("zulu")和SearchEntry.Contains("dragonwell")

**Comment by ShenxPresent** [comment]
我也遇到了类似的问题，但是我手动添加显示
![image](https://github.com/Hex-Dragon/PCL2/assets/53565917/03d0e407-c5bb-473f-8709-42854190f826)

**Comment by hejiehao** [comment]
> 我也遇到了类似的问题，但是我手动添加显示 ![image](https://user-images.githubusercontent.com/53565917/273171067-03d0e407-c5bb-473f-8709-42854190f826.png)

你试一下 JDK

**Comment by burningtnt** [comment]
PCL 已经给出了解决方案，怎么还有问题？

**Comment by ShenxPresent** [comment]
> 我也遇到了类似的问题，但是我手动添加显示 ![image](https://user-images.githubusercontent.com/53565917/273171067-03d0e407-c5bb-473f-8709-42854190f826.png)

感谢回答，解决了

**Comment by JingHai-Lingyun** [comment]
> Issue

请发送你的 PCL 识别码来换取活跃橙解锁码

**Comment by winver1234** [comment]
Issue 0B4A-ED17-D632-9FC0

**Comment by LTCatt** [comment]
你的解锁码：sTaz1jyS4SBjje59paJHDeMgiR8q5cyj
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
