### ISSUE TITLE
连崩惨案

### ISSUE THREAD

**Issue by f13T2ach** [Hex-Dragon/PCL2#2753]
### 检查项

- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

mc崩溃，我认了。PCL异常分析崩溃，认不了一点。
版本2.6.8.0 mc版本3D Shareware v1.34 显卡是牙膏经典核显
```
[21:46:25.291] [Crash] 步骤 2：准备日志文本完成，找到游戏日志、虚拟机日志用作分析
[21:46:25.291] [Crash] 步骤 3：分析崩溃原因
[21:46:25.306] [Crash] 可能的崩溃原因：Intel驱动不兼容导致EXCEPTION_ACCESS_VIOLATION
[21:46:25.306] [Crash] 步骤 3：分析崩溃原因完成，找到 1 条可能的原因
[21:46:25.306] [Crash]  - Intel驱动不兼容导致EXCEPTION_ACCESS_VIOLATION
[21:46:25.338] 崩溃分析失败：未将对象引用设置到对象的实例。
   在 PCL.CrashAnalyzer.GetAnalyzeResult(Boolean IsHandAnalyze)
   在 PCL.CrashAnalyzer.Output(Boolean IsHandAnalyze, List`1 ExtraFiles)
   在 PCL.ModWatcher.Watcher._Lambda$__32-0()
错误类型：System.NullReferenceException
```
1. 声明字符串变量是未赋空值就应用变量
2. 未用new初始化对象

### 重现步骤

1. 屏蔽显卡
2. 装3D Shareware v1.34，或者其它会发生异常的版本都行(?)
3. 新建一个世界（所有难度都一样）
4. boom!

### 日志与附件

[这是日志Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12819234/Log1.txt)

**Comment by f13T2ach** [comment]
逆向出来的函数是空的，靠你自己了。如果是显卡驱动问题的话，为啥pcl会因为显卡驱动问题导致异常分析失败...

**Comment by youzi-2333** [comment]
翻了一圈代码也没看出啥问题（主要是 Log 里面没有注明代码的行数，不好判断问题在哪里）我把 PCL 更新到 2.6.8 手动结束了个进程也没问题，正常弹出 `Minecraft 出现错误` 了，估计是偶发情况。看看龙猫能不能修……

**Comment by LTCatt** [comment]
#2706
