### ISSUE TITLE
程序出现未知错误

### ISSUE THREAD

**Issue by 11kun** [Hex-Dragon/PCL2#2755]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/Hex-Dragon/PCL2/assets/147077677/7e10aabb-3ab1-4bd5-b5b0-25400140f7e8)

### 重现步骤

pcl2打不开，更新win系统在点击就直接报错

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12819971/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12819972/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12819973/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12819976/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12819977/Log2.txt)

**Comment by JingHai-Lingyun** [comment]
PCL2 需要 .Net Framework 4.6.2，[点此下载](https://support.microsoft.com/zh-cn/topic/-net-framework-4-6-2-%E8%84%B1%E6%9C%BA%E5%AE%89%E8%A3%85%E7%A8%8B%E5%BA%8Fwindows-9dce3874-a9e5-9b11-289d-5594824aafe0)

**Comment by 11kun** [comment]
@JingHai-Lingyun 有两个是安装脱机的还是安装没有脱机的

**Comment by kong-que-dnf123** [comment]
> @JingHai-Lingyun 有两个是安装脱机的还是安装没有脱机的

脱机包是exe文件，没说脱机的是msu文件
 _（其实可以都试试）_

**Comment by youzi-2333** [comment]
就按照上面说的，装个 .NET Framework 4.6.2，再重新启动 PCL 试试，然后在这里说一下能不能正常启动了（

**Comment by LTCatt** [comment]
系统问题，不是启动器导致的 =。=
