### ISSUE TITLE
Minecraft 出现错误，游戏崩溃无法启动

### ISSUE THREAD

**Issue by Nephino** [Hex-Dragon/PCL2#2756]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃基本不是 PCL 的原因，请 **不要** 提交反馈。你可以在论坛或社区找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用 HMCL 启动，HMCL 没有出现问题。** 如果 HMCL 也无法启动就不是 PCL 导致的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

点击启动游戏后，读条结束就崩溃，无法启动游戏

latest.log 中发现有：`java.lang.UnsatisfiedLinkError: Failed to locate library: lwjgl.dll [in thread "Render thread"]`的错误
网络上搜索认为是中文路径的原因，然而 lwjgl 的路径如下：`C:\Users\Nephino\AppData\Roaming\.minecraft\versions\1.20.1-Fabric 0.14.23\natives-windows-x86_64\lwjgl.dll`

### PCL 错误报告、日志与附件

[错误报告-2023-10-7_14.15.58.zip](https://github.com/Hex-Dragon/PCL2/files/12836944/-2023-10-7_14.15.58.zip)

### HMCL 启动脚本

[HMCL启动脚本.zip](https://github.com/Hex-Dragon/PCL2/files/12836946/HMCL.zip)

**Comment by Nephino** [comment]
另外补充：
在一次未知原因的崩溃后，卡巴斯基报毒并隔离了 pcl 和 javawrapper.jar 。我尝试恢复无果，于是重新在群内下载了 pcl 并放回原位，之后便开始出现前述报错。
其间我尝试过将 version 下（已开启版本隔离）的文件全部删除并重新安装 minecraft ，问题依旧存在。

**Comment by LTCatt** [comment]
lwjgl.dll 应当位于 `.minecraft\versions\1.20.1-Fabric 0.14.22\1.20.1-Fabric 0.14.22-natives\` 而不是 `.minecraft\versions\1.20.1-Fabric 0.14.23\natives-windows-x86_64\`
并且你的 PCL 版本太老了，更新一下再说

**Comment by Nephino** [comment]
> lwjgl.dll 应当位于 `.minecraft\versions\1.20.1-Fabric 0.14.22\1.20.1-Fabric 0.14.22-natives\` 而不是 `.minecraft\versions\1.20.1-Fabric 0.14.23\natives-windows-x86_64\` 并且你的 PCL 版本太老了，更新一下再说

问题解决了，确实可能是 PCL 版本过老的问题。
