### ISSUE TITLE
多账号切换增强

### ISSUE THREAD

**Issue by JackieJK** [Hex-Dragon/PCL2#2760]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在切换不同认证服务器下的不同账号时非常不方便，希望参考hmcl改进相关逻辑。

### 原因

在现有版本切换不同认证服务器下的不同账号十分不方便。

**Comment by LTCatt** [comment]
啥意思？是第三方登录用了多个服务器么？

**Comment by JackieJK** [comment]
> 啥意思？是第三方登录用了多个服务器么？

是的，多个账号多个服务器

**Comment by LTCatt** [comment]
#57
