### ISSUE TITLE
在 Mod/整合包 详情加载完之前返回，导致“可视化工程下载列表出错”

### ISSUE THREAD

**Issue by 212112111zwl** [Hex-Dragon/PCL2#2761]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

启动器弹窗提示报错，错误出现在log的444行（真巧

### 重现步骤

我也不知道哪里出错了，但错误出现在下载页面，具体看log应该就知道了

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12840614/Log1.txt)

**Comment by JingHai-Lingyun** [comment]
~~正好下 Mod 的时候触发了这个 Bug~~
### 目前我发现的重现步骤如下
1. 进入下载 Mod / 整合包 页面
2. 点击打开一个之前没浏览过的 Mod / 整合包
3. 返回下载选择页面，Bug 出现
### 日志
[正常模式.txt](https://github.com/Hex-Dragon/PCL2/files/12844681/default.txt)
[调试模式.txt](https://github.com/Hex-Dragon/PCL2/files/12844682/default.txt)

**Comment by kong-que-dnf123** [comment]
_感觉就是他在返回的同时后台还在加载，加载完了要显示但是没地方给他显示了（）_

**Comment by SuoHouDaiShi** [comment]
![图片](https://github.com/Hex-Dragon/PCL2/assets/119282947/332762e4-8ea9-41d4-8a2b-292c0895bf97)
复现成功
附件：Log
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/13059841/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/13059842/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/13059843/Log5.txt)
[Log.txt](https://github.com/Hex-Dragon/PCL2/files/13059844/Log.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13059845/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/13059846/Log2.txt)
