### ISSUE TITLE
启动器启动异常报错

### ISSUE THREAD

**Issue by lZiMUl** [Hex-Dragon/PCL2#2765]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

启动器启动异常报错

### 重现步骤

启动器启动异常报错

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12858399/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12858400/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12858401/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12858402/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12858403/Log5.txt)

**Comment by JingHai-Lingyun** [comment]
Log1
```
[07:23:46.156] 可视化工程下载列表出错：Object variable or With block variable not set.
   在 Microsoft.VisualBasic.CompilerServices.Symbols.Container..ctor(Object Instance)
   在 Microsoft.VisualBasic.CompilerServices.NewLateBinding.ObjectLateInvokeDefault(Object Instance, Object[] Arguments, String[] ArgumentNames, Boolean ReportErrors, Boolean[] CopyBack)
   在 PCL.PageDownloadCompDetail.Load_OnFinish()
错误类型：System.NullReferenceException
```
#2761
