### ISSUE TITLE
自动跳转.NET并且进不了软件

### ISSUE THREAD

**Issue by puppet717** [Hex-Dragon/PCL2#2769]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

打开后会自动跳转到.NET下载界面并自动关闭pcl2，删除重新下载或者重启电脑都不行，java卸载重装也是一样，hmcl可以照常启动

### 重现步骤

双击启动会自动跳转浏览器并且下载.NET

### 日志与附件

..

**Comment by kong-que-dnf123** [comment]
_那会不会是PCL认为你本身就缺这个东西运行不了呢........_

**Comment by Louis-ZYH** [comment]
_建议先检查一下你电脑里.NET装没装好…………_

**Comment by puppet717** [comment]
> _建议先检查一下你电脑里.NET装没装好…………_

下载安装net后显示已经安装过了

**Comment by LTCatt** [comment]
卸载新版本 .net 重装

**Comment by shhjtvp** [comment]
我是Windows10，我删除了KB5011048更新后可以正常启动了。https://support.microsoft.com/zh-cn/topic/microsoft-net-framework-4-8-1-%E9%80%82%E7%94%A8%E4%BA%8E-windows-10-%E7%89%88%E6%9C%AC-21h2-windows-10-%E7%89%88%E6%9C%AC-22h2-windows-11-%E7%89%88%E6%9C%AC-21h2-windows-server-2022-desktop-azure-editions-azure-stack-21h2-%E5%92%8C-azure-stack-22h2-kb5011048-277f9c30-7add-4150-b774-5e3667e02256

**Comment by Pigeon0v0** [comment]
KB5011048 是用于 Win10 21H2 以上和 Win11 21H2 以上的安装 .NET Framework 4.8.1 的更新，这个更新理论上不会引发任何问题。

建议检查自己的电脑环境是不是有问题。

**Comment by XiaoMouTuiKui** [comment]
> 我是Windows10，我删除了KB5011048更新后可以正常启动了。https://support.microsoft.com/zh-cn/topic/microsoft-net-framework-4-8-1-%E9%80%82%E7%94%A8%E4%BA%8E-windows-10-%E7%89%88%E6%9C%AC-21h2-windows-10-%E7%89%88%E6%9C%AC-22h2-windows-11-%E7%89%88%E6%9C%AC-21h2-windows-server-2022-desktop-azure-editions-azure-stack-21h2-%E5%92%8C-azure-stack-22h2-kb5011048-277f9c30-7add-4150-b774-5e3667e02256 (可对其他人没用...)

今天我朋友也吐槽自己pcl这样，我折腾了半天卸载重装装新版本net都试过了，最后也是卸载KB5011048后好了
