### ISSUE TITLE
可视化工程下载列表出错: 未设置对象变量或 With 块

### ISSUE THREAD

**Issue by zjr233** [Hex-Dragon/PCL2#2770]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

启动器弹窗提示报错

### 重现步骤

下载MOD页面出现错误出现

### 日志与附件

[Log.txt](https://github.com/Hex-Dragon/PCL2/files/12881988/Log.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12881989/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12881990/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12881991/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12881992/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12881993/Log5.txt)

**Comment by kong-que-dnf123** [comment]
#2761
![image](https://github.com/Hex-Dragon/PCL2/assets/120994373/0971360f-ed80-4aae-93ea-844eada436a3)
