### ISSUE TITLE
为未来的联机模块添加类似于服务器的功能

### ISSUE THREAD

**Issue by BaiYing886** [Hex-Dragon/PCL2#2772]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

在未来三家启动器合作推出联机后，我建议可以加入服务器的这个分支功能，在打开联机选项菜单的时候会有一个‘服务器联机’之类的选项，进入后就是一个面板服务器的界面(UI)
(当然，也是从朋友口中得知的马上要推出了)
其实也只需要一个文件管理以及配置文件就足够了，该部分代码在一些开源的项目里有，不必要从头开始，获得授权即可。
同时可以在页面内添加推荐服务器，让玩家在页面点击服务器名称或图标就可以获得该服务器的介绍且可以一键下载对应服务器版本或客户端并加入游戏而无需启动。
就比如我自己开的服务器：mc.pillowdream.top       .\*-pwp-*/.
这就是我的建议，虽然这可能有一些早了。

### 原因

在加入该功能后，联机就不单单只是存档，可以是服务器，让想用服务器插件或mod却不知道怎么搭建服务器又或者更方便的去使用联机。而加入推荐服务器，这让玩家可以方便快捷的进入那些优质好玩的服务器，也是对萌新玩家的帮助，毕竟有的人看了教程也只是半懂的状态。
这个建议我也会向其余两个启动器提交的，真的想得到回复，哪怕是拒绝pap.

**Comment by LTCatt** [comment]
去问 TT 别问我.jpg

**Comment by BaiYing886** [comment]
> 去问 TT 别问我.jpg

你帮我问问呗，我懒awa
