### ISSUE TITLE
下载新MC版本之后无法在启动器的版本列表显示

### ISSUE THREAD

**Issue by orangeZSCB** [Hex-Dragon/PCL2#2781]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

下载一个新Minecraft版本之后有几率无法在启动器版本列表显示，需要重启之后才可以解决。
使用的版本为正式版本2.6.7
（这也算一个小小Bug吧，应该可以解锁主题吧（（（（（（（（

### 重现步骤

1、点击 下载 菜单按钮
2、往下滚，然后随意点击一个版本下载
3、等待下载完毕
4、下载完毕之后在主页打开版本列表，发现没有此版本
5、重启启动器，发现新下载版本。

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12903502/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12903505/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12903503/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12903504/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12903506/Log5.txt)

**Comment by DreamUniverse843** [comment]
2.6.9 未能复现。
请尝试更新一下你的启动器，或者再详细描述一下你的操作流程。
**确定不是版本被折叠了嘛，宝？**

**Comment by 596wjr** [comment]
尝试刷新一下

**Comment by orangeZSCB** [comment]
> 2.6.9 未能复现。 请尝试更新一下你的启动器，或者再详细描述一下你的操作流程。 **确定不是版本被折叠了嘛，宝？**

当时是我朋友的电脑，Ta下载了一个1.17.1，下载版本之后版本列表**未出现新的版本**，启动器为**最新的正式版2.6.7（点击“检查更新”之后跳出的提示）**，我记得当时我的朋友点击开始下载之后点到了**启动器顶部别的菜单**，并且版本**未折叠**，可能就像楼上@596wjr说的是下载完版本后启动器没有能自动刷新导致的版本无法显示。
好了，破案了，就是没刷新捣的鬼（恼

**Comment by SALTWOOD** [comment]
那就关 issue 吧

**Comment by JingHai-Lingyun** [comment]
等下 没自动刷新是个 Bug

**Comment by orangeZSCB** [comment]
> 等下 没自动刷新是个 Bug

那么是不是可以解锁主题了呢（（（（（（（（（（（（（啊我满脑子都在想主题呢为什么

**Comment by LTCatt** [comment]
无法复现，需要一个稳定的复现方法？

**Comment by wuliaodexiaoluo** [comment]
复现成功了
调试模式下的日志文件
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14730857/Log1.txt)
