### ISSUE TITLE
拖入崩溃日志文件无法执行分析

### ISSUE THREAD

**Issue by DreamUniverse843** [Hex-Dragon/PCL2#2783]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如题。
拖入日志文件后光标变为禁止符号，无法进行日志分析。

### 重现步骤

将日志直接拖入 PCL 界面即可。

### 日志与附件

无关联日志。
PCL 对拖入事件根本没有响应。

**Comment by DreamUniverse843** [comment]
使用的已为最新快照版 2.6.9，但依然不可用。

**Comment by hejiehao** [comment]
你使用了管理员启动 PCL2 吗？

**Comment by kong-que-dnf123** [comment]
> 使用的已为最新快照版 2.6.9，但依然不可用。

~然后你就自己关了...（？）~

**Comment by DreamUniverse843** [comment]
> > 使用的已为最新快照版 2.6.9，但依然不可用。
> 
> ~然后你就自己关了...（？）~

看到 Discussion 里面有说下次更新会修正就关了......
