### ISSUE TITLE
联机设置没删干净

### ISSUE THREAD

**Issue by idhaname** [Hex-Dragon/PCL2#2784]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如图，使用自定义主页的切换页面功能可以切换到联机模块的相关页面
![图片](https://github.com/Hex-Dragon/PCL2/assets/68469786/5d9d3903-7cca-48ea-9f8a-bf582d99fcdc)

### 重现步骤

    <local:MyCard Title="事件 4：其他事件类型" Margin="0,0,0,15" CanSwap="True" IsSwaped="False">
	    <StackPanel Margin="25,40,23,15">
		<local:MyButton Margin="0,5,0,6" Width="250" Height="35"
                        Text="联机关于与反馈" EventType="切换页面" EventData="2|6"/>
                <local:MyButton Margin="0,5,0,6" Width="250" Height="35"
                        Text="在联机页面里的联机设置" EventType="切换页面" EventData="2|4"/>
                <local:MyButton Margin="0,5,0,6" Width="250" Height="35"
                        Text="在设置页面里的联机设置" EventType="切换页面" EventData="3|3"/>
	    </StackPanel>
    </local:MyCard>
在custom.xaml里填上如上内容，然后点击主页的对应按钮即可

### 日志与附件

这个就没必要交日志了吧……

**Comment by hejiehao** [comment]
~~龙猫表示反正都没发用~~

**Comment by kong-que-dnf123** [comment]
当你试图点击里面的设置时...
 _（龙猫：我们删了，但没完全删）_
![image](https://github.com/Hex-Dragon/PCL2/assets/120994373/ef408194-2148-4d7f-baa5-d0ae7d3d0897)

**Comment by SuoHouDaiShi** [comment]
> 当你试图点击里面的设置时... _（龙猫：我们删了，但没完全删）_ ![image](https://user-images.githubusercontent.com/120994373/275313791-ef408194-2148-4d7f-baa5-d0ae7d3d0897.png)

<del>遥遥领先</del>

**Comment by kong-que-dnf123** [comment]
> > 当你试图点击里面的设置时... _（龙猫：我们删了，但没完全删）_ ![image](https://user-images.githubusercontent.com/120994373/275313791-ef408194-2148-4d7f-baa5-d0ae7d3d0897.png)
> 
> ~遥遥领先~

~~他甚至在我点“lol”和“Hiper”时就会直接闪退~~

**Comment by SuoHouDaiShi** [comment]
测试成功，感谢反馈~
![图片](https://github.com/Hex-Dragon/PCL2/assets/119282947/a6628a23-b196-41d3-8f64-e2eb06c38a8d)
![图片](https://github.com/Hex-Dragon/PCL2/assets/119282947/e410d040-3bcc-4668-bbe8-d9a525e6ca6a)
另：
---日志文件---
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12909048/Log5.txt)
[Log.txt](https://github.com/Hex-Dragon/PCL2/files/12909049/Log.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12909050/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12909051/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12909053/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12909054/Log4.txt)
---Xaml文件内容---
```
<local:MyCard Title="Test Panel" Margin="0,0,0,15" CanSwap="False" IsSwaped="False">
    <StackPanel Margin="25,40,23,15">
	<local:MyButton Margin="0,5,0,6" Width="250" Height="35"
                    Text="FEEDBACK" EventType="切换页面" EventData="2|6"/>
            <local:MyButton Margin="0,5,0,6" Width="250" Height="35"
                    Text="SETTINGS" EventType="切换页面" EventData="2|4"/>
            <local:MyButton Margin="0,5,0,6" Width="250" Height="35"
                    Text="SETTINGS 2" EventType="切换页面" EventData="3|3"/>
    </StackPanel>
</local:MyCard>
```
---<del>呼叫支援</del>---
@LTCatt
@youzi-2333 
@Big-Cake-jpg

**Comment by LTCatt** [comment]
功能实际无法使用，不会处理
