### ISSUE TITLE
检测是否正确打开系统代理

### ISSUE THREAD

**Issue by Gaobaiawa** [Hex-Dragon/PCL2#2787]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

检测代理是否正确打开，内容如下：
 
如果代理服务器可以访问，那么不弹出警告，如果无法访问，那么弹出警告，内容为“您设置的代理服务器似乎无法访问，是否关闭系统代理”下面有三个按钮，一个"不再提示"（如果点击则永远不弹出此弹窗），一个"忽略"（如果点击则不执行任何操作，并且关闭这个弹窗）一个"确认"（如果点击，关闭系统代理）
 
代码简单实现：
内容由chatgpt-4生成，我只检查了一小部分
'导入必要的命名空间
Imports System.Net
Imports System.Windows.Forms

'创建一个类来封装代理检测和弹窗逻辑
Public Class ProxyDetector

    '定义一个方法来检测系统代理设置
    Public Shared Function DetectProxy(proxyUrl As String) As Boolean
        '获取系统默认的代理对象
        Dim proxy As IWebProxy = WebRequest.GetSystemWebProxy()
        '如果代理对象不为空，并且有代理地址，则尝试访问指定的代理服务器地址
        If proxy IsNot Nothing AndAlso proxy.GetProxy(New Uri("http://www.bing.com")) IsNot Nothing Then
            '创建一个WebRequest对象，设置代理和超时时间
            Dim request As WebRequest = WebRequest.Create(proxyUrl)
            request.Proxy = proxy
            request.Timeout = 5000 '5秒
            Try
                '发送请求，并获取响应
                Dim response As WebResponse = request.GetResponse()
                '如果没有发生异常，则说明代理服务器可以访问，返回True
                Return True
            Catch ex As Exception
                '如果发生异常，则说明代理服务器无法访问，返回False
                Return False
            End Try
        Else
            '如果代理对象为空或没有代理地址，则返回False
            Return False
        End If
    End Function

    '定义一个方法来显示错误弹窗
    Public Shared Sub ShowErrorDialog()
        '创建一个对话框对象
        Dim dialog As New Form()
        '设置对话框的标题和大小
        dialog.Text = "错误"
        dialog.Size = New Size(400, 200)
        '创建一个标签对象，用于显示错误信息
        Dim label As New Label()
        label.Text = "您设置的代理服务器似乎无法访问，是否关闭系统代理"
        label.AutoSize = True
        label.Location = New Point(20, 20)
        '创建三个按钮对象，分别对应不再提示，忽略和确认的功能
        Dim button1 As New Button()
        button1.Text = "不再提示"
        button1.Location = New Point(50, 100)
        Dim button2 As New Button()
        button2.Text = "忽略"
        button2.Location = New Point(150, 100)
        Dim button3 As New Button()
        button3.Text = "确认"
        button3.Location = New Point(250, 100)
        '为每个按钮添加点击事件的处理方法
        AddHandler button1.Click, AddressOf Button1_Click
        AddHandler button2.Click, AddressOf Button2_Click
        AddHandler button3.Click, AddressOf Button3_Click
        '将标签和按钮添加到对话框中
        dialog.Controls.Add(label)
        dialog.Controls.Add(button1)
        dialog.Controls.Add(button2)
        dialog.Controls.Add(button3)
        '显示对话框，并阻塞当前线程，直到对话框关闭
        dialog.ShowDialog()
    End Sub

    '定义一个方法来处理不再提示按钮的点击事件
    Private Shared Sub Button1_Click(sender As Object, e As EventArgs)

        '关闭对话框，并设置一个标志位，表示不再检测代理或显示弹窗
        Dim dialog As Form = CType(sender, Control).FindForm()
        dialog.Close()
        My.Settings.NoProxyCheck = True
    End Sub

    '定义一个方法来处理忽略按钮的点击事件
    Private Shared Sub Button2_Click(sender As Object, e As EventArgs)
        '关闭对话框，并继续运行程序（这里你可以添加其他逻辑）
        Dim dialog As Form = CType(sender, Control).FindForm()
        dialog.Close()
    End Sub

    '定义一个方法来处理确认按钮的点击事件
    Private Shared Sub Button3_Click(sender As Object, e As EventArgs)
        '关闭对话框，并调用一个方法来关闭系统代理设置（这个方法需要你自己实现）
        Dim dialog As Form = CType(sender, Control).FindForm()
        dialog.Close()
        DisableProxy()
    End Sub

End Class

'在主程序中，调用上面定义的类的方法，进行代理检测和弹窗显示（如果需要）
Sub Main()
    '如果没有设置不再提醒标志位，则进行代理检测
    If Not My.Settings.NoProxyCheck Then
        '如果检测到代理打开，并且代理服务器无法访问，则显示错误弹窗
        If ProxyDetector.DetectProxy("http://www.example.com") = False Then
            ProxyDetector.ShowErrorDialog()
        End If
    End If
    '运行其他程序逻辑（这里你可以添加其他代码）
End Sub

### 原因

此优化用于检测代理服务器是否正常关闭，比如开着加速器强制关机，那么开机后系统代理仍然会打开，但是加速器已经关闭了，所以代理服务器会无法响应，导致无法上网
没啥了，就今天看到报错的时候突然想到了这个，然后就想着开个issuse，主题我来咯~
![Q)1{_)KCXN$CRK 6TOK_UGD](https://github.com/Hex-Dragon/PCL2/assets/123546075/8846f7b5-6361-41d3-b7a7-02d9701fca1f)

**Comment by Gaobaiawa** [comment]
也不知道这次会不会通过，要是通过了踢我一下，没通过就算了，已经第四次了

**Comment by SuoHouDaiShi** [comment]
理论可行，但是大概率不会做（
另外优化反馈不在解锁主题的范畴之内（（（

另：你可以自己Clone一个仓库，在后端添加对应模块试试？

**Comment by Gaobaiawa** [comment]
> 理论可行，但是大概率不会做（
> 另外优化反馈不在解锁主题的范畴之内（（（
> 
> 另：你可以自己Clone一个仓库，在后端添加对应模块试试？
> 
> 诶等等，似乎重复了，#1228

那个我在发之前看了，没有重复，那个是添加一个代理转向，就是减少网络延迟的🥰

**Comment by Gaobaiawa** [comment]
啊？优化反馈不能解锁主题？唉我的主题第四次又没了

**Comment by LTCatt** [comment]
超出启动器范畴了……
