### ISSUE TITLE
pcl2打不开，后台能看见，过几秒就没了

### ISSUE THREAD

**Issue by xiaolaotou8** [Hex-Dragon/PCL2#279]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

pcl2突然打不开，点击pcl2无响应，后台看见过几秒就没了，试过很多种方法，都不行

### 重现步骤

1、点击pcl2
2、后台出现
3、过几秒无了

### 日志与附件

没有日志，pcl2都打不开
[新建 文本文档 (2).txt](https://github.com/Hex-Dragon/PCL2/files/9846285/2.txt)

**Comment by LTCatt** [comment]
PCL2 有没有在同目录下生成 PCL 文件夹，里面有没有日志文件
如果连文件夹都没有生成，那就是系统环境的问题，我没有办法解决
如果有，把里面的日志文件传上来

**Comment by LTCatt** [comment]
但看日志这不是能用么

**Comment by lvjiajjjlzy** [comment]
还有开机后根本无法启动的bug

**Comment by LTCatt** [comment]
开机第一次无法启动？如果是那个 bug 的话再单开一个 issue……
然后这个 issue，你传的日志是可以使用的，上传一个你说的 “后台能看见，过几秒就没了” 的日志……

**Comment by xiaolaotou8** [comment]
谢谢，我已经解决。解决办法升级了系统
