### ISSUE TITLE
检索模组时点前置会有一定几率无法加载

### ISSUE THREAD

**Issue by xynsf** [Hex-Dragon/PCL2#2792]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

下载模组时，选中前置进入加载页面，有一定几率会一直加载，触发规律不详，反正就是不给加载，重新点进去有时会加载出来有时会保持原样，重点在退出下载界面到启动界面时才弹出错误弹窗

### 重现步骤

1、点击下载，随机搜一个模组（选中版本和加载方式，出bug时是附魔灌注台，1.20.1，forge全选）
2、然后点击附魔灌注台，出现目标版本1.20.1forge，此时下载后点击前置Puzzles Lib卡在Puzzles Lib的加载页面
3、此时双击左上角然后点击启动回到启动界面，等待一会bug弹窗提示

### 日志与附件

[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/13053470/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13053471/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/13053472/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/13053473/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/13053474/Log4.txt)

**Comment by JingHai-Lingyun** [comment]
模组页面出bug弹窗是 #2761

**Comment by SuoHouDaiShi** [comment]
Log5：
```
[20:05:52.248] [Download] createaddition-1.20.1-1.1.1.jar 1633#：出错，由于速度过慢断开链接，下载 1037 B，消耗 1281 ms。
   在 PCL.ModNet.NetFile.Thread(NetThread Info)
错误类型：System.TimeoutException
```
在第506行发现的

**Comment by xynsf** [comment]
> Log5：
> 
> ```
> [20:05:52.248] [Download] createaddition-1.20.1-1.1.1.jar 1633#：出错，由于速度过慢断开链接，下载 1037 B，消耗 1281 ms。
>    在 PCL.ModNet.NetFile.Thread(NetThread Info)
> 错误类型：System.TimeoutException
> ```
> 
> 在第506行发现的

谢谢大佬，但是我还是没看懂，是我的问题还是启动器的问题·····

**Comment by xynsf** [comment]
毕竟在其他启动器就没这个情况，从官网下也没这个情况

**Comment by DreamUniverse843** [comment]
> > Log5：
> > 
> > ```
> > [20:05:52.248] [Download] createaddition-1.20.1-1.1.1.jar 1633#：出错，由于速度过慢断开链接，下载 1037 B，消耗 1281 ms。
> >    在 PCL.ModNet.NetFile.Thread(NetThread Info)
> > 错误类型：System.TimeoutException
> > ```
> > 
> > 在第506行发现的
> 
> 谢谢大佬，但是我还是没看懂，是我的问题还是启动器的问题·····
> 

网络速度过慢断开连接，是你的网络问题...
你下其他的 mod 试试呢

**Comment by youzi-2333** [comment]
我感觉确实像是网络问题。
不知道咋处理比较好.jpg

**Comment by SuoHouDaiShi** [comment]
> 我感觉确实像是网络问题。 不知道咋处理比较好.jpg

<del>给PCL2开个加速线路(bushi)</del>
先关了issue看看？

**Comment by LTCatt** [comment]
实质是 #2761 加上网络问题……
