### ISSUE TITLE
关于版本个性化设置

### ISSUE THREAD

**Issue by ItIsNotAPlayer** [Hex-Dragon/PCL2#2796]
### 检查项

- [X] 我已在 [Issues 页面](https://githubfast.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://githubfast.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://githubfast.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

对于版本个性化设置的布局的一些小建议：
1. 版本名和版本描述是两个填文字的地方用的是按钮，然后弹窗出来，不能直接用文本框吗
2. 图标和分类都是长的下拉框，可不可以把它俩改到同一行去，反正拉出来的选项文字都不长

### 原因

感觉现在版本个性化设置的布局设计有点反直觉🤔

**Comment by LTCatt** [comment]
用文本框的话“加入收藏夹”就单独一个按钮杵在那了更难看，并且修改版本名使用文本框那打一个字修改一次会很折腾人，工作量也比较大
两个下拉框是单纯统一化的设计……
