### ISSUE TITLE
待一个人教我怎么删除建议

### ISSUE THREAD

**Issue by xynsf** [Hex-Dragon/PCL2#2797]
···

**Comment by xynsf** [comment]
目标是：让每一个人提起mc都会说pcl2而不是sb网易

**Comment by xynsf** [comment]
教萌新了解使用pcl2太折磨了

**Comment by xynsf** [comment]
一个两个还好，几十个一个一个教简直要给我整废了，教一遍还教不会

**Comment by deep-dark-forest** [comment]
~~你不知道自己研发一个文件格式有多困难吗~~
此外，这个功能大概率会被拒绝，因为这不是启动器应该做的事。而且如果真有人用这种格式的整合包的话整得挺像是强制人家用pcl2启动器似的，如果有人用这种格式做了一个整合包，下载下来发现只有pcl2才能打开，但是他用的又不是pcl2启动器，这就真的很麻烦……

**Comment by burningtnt** [comment]
你在成为网易

**Comment by burningtnt** [comment]
无论与之前的重复不重复，你这都不是一个好注意

**Comment by xynsf** [comment]
换个思路，还是导出为zip但是导完了改个后缀，实现了

**Comment by burningtnt** [comment]
？你是想让大家看 PCL2 试图搞垄断，但是搞的很不成功

**Comment by xynsf** [comment]
是推广不是垄断···

**Comment by burningtnt** [comment]
只会让 PCL2 失去用户

**Comment by DreamUniverse843** [comment]
所以你这种“推广”的意义在何？
既然都是 zip 格式压缩包文件为什么要多此一举改掉后缀名？~~真的会让人觉得你在强迫用户用 PCL 2~~
而且启动器本来就不是 PCL 2 一家~~总不能强迫所有人都来用 PCL 2 吧~~

> 
> 目标是：让每一个人提起mc都会说pcl2而不是sb网易

~~插一句，你 PCL 2 只能跑在 Windows 环境下，照你这逻辑其他平台的用户别玩了？~~

**Comment by WForst-Breeze** [comment]
个人感觉完全没必要，mcbbs 格式整合包已经是很易于安装和导出的格式了，动动手就能导出，拖进启动器就能安装，还想要多方便？具体说说你的期望吧……

**Comment by xynsf** [comment]
https://github.com/WForst-Breeze
没事，不提了，怎么删意见教教我

**Comment by DreamUniverse843** [comment]
> https://github.com/WForst-Breeze
> 没事，不提了，怎么删意见教教我
> 

你自己 Close Issue 就可以了，机器人会把你的意见打上忽略标签
或者 Collaborator 看到了来处理

**Comment by xynsf** [comment]
好的谢谢
