### ISSUE TITLE
1.8.9幸运方块整合包出现崩溃

### ISSUE THREAD

**Issue by HM666huanmeng** [Hex-Dragon/PCL2#2798]
### 检查项

- [ ] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃基本不是 PCL 的原因，请 **不要** 提交反馈。你可以在论坛或社区找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用 HMCL 启动，HMCL 没有出现问题。** 如果 HMCL 也无法启动就不是 PCL 导致的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

这个整合包我只是进行一个测试，并未真正游玩过，然而它却崩了。具体描述是：名称为forge-1.8.9-11.15.1.2318-1.8.9.jar的 Mod导致游戏出了错。
此整合包有四个模组（luckyblock、loot++、PotionCore、YoutubersLuckyblock）

### PCL 错误报告、日志与附件

[错误报告-2023-10-21_上午_8.52.06.zip](https://github.com/Hex-Dragon/PCL2/files/13059341/-2023-10-21_._8.52.06.zip)

**Comment by HM666huanmeng** [comment]
LssueB11D-55AE-4FE7-5E5C

**Comment by JingHai-Lingyun** [comment]
请注意，此 Issue 为无效 Issue，无法获得活跃橙解锁码
