### ISSUE TITLE
加回“启动时自动加载IOI联机模块”

### ISSUE THREAD

**Issue by SttjY** [Hex-Dragon/PCL2#280]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在联机-设置里重新加回“启动时自动加载IOI联机模块”

### 原因

没有这项优化每次使用IOI进行联机都得先打开IOI按钮才能开始加载，让使用IOI联机变得更麻烦

**Comment by LTCatt** [comment]
删除这个主要是考虑 IOI 存在未解决的内存泄露 bug，可能在无意中占用很多内存……
