### ISSUE TITLE
退出游戏后启动器提示线程执行失败

### ISSUE THREAD

**Issue by Fhy1024** [Hex-Dragon/PCL2#2800]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

启动了Fabric 1.19的版本，正常游戏，单击菜单页面的退出游戏后，启动器提示错误
pcl个性化设置了主页、背景图片和左上角文字，没有设置别的东西

### 重现步骤

1、点击启动游戏
2、然后点击退出游戏

### 日志与附件

[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/13059768/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/13059769/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13059770/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/13059771/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/13059772/Log3.txt)
![image](https://github.com/Hex-Dragon/PCL2/assets/123815384/0057c4ac-b29b-46b3-9969-64f7bc80e544)

**Comment by SuoHouDaiShi** [comment]
#2517

**Comment by kong-que-dnf123** [comment]
WC那不对啊
 #2517 不是已经被修好了吗

**Comment by kong-que-dnf123** [comment]
斯
~龙猫现在还没有迁移到正式版吗~

**Comment by Fhy1024** [comment]
我都好久没用pcl了，之前似乎也没有过这个问题，今天打开pcl更新了之后就这样了

**Comment by SuoHouDaiShi** [comment]
关重复issue要用not planned，，

**Comment by Fhy1024** [comment]
c用github不太熟老点错
