### ISSUE TITLE
[HMCL KOOK]JVM启动参数问题

### ISSUE THREAD

**Issue by HomoobyDX** [Hex-Dragon/PCL2#2801]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

原话：如果是通过 installer 安装的 forge，那么 forge-1.12.2-14.23.5.2859.jar 这玩意儿在 -cp 参数的位置是在 launchwrapper-1.12.jar 前面的，但是通过 PCL 安装了之后就跑到后面去了
因为 launchwrapper 和 forge 的 jar 里都有 log4j2.xml
并且如果不指定 xml 的位置，那么 log4j2 是按照 -cp 里的顺序读取 log4j2.xml
那么这样就会读到 launchwrapper 而不是 forge 里的 log4j2.xml
导致一些 forge 里的涉及到 log4j2 的参数会失效
因为 forge 的 log4j2.xml 里的 debug.log 的输出等级是 DEBUG
但是 launchwrapper 的 latest.log 输出等级是 INFO
然后又因为 -Dlegacy.debugClassLoading=true -Dlegacy.debugClassLoadingFiner=true 参数带来的日志输出的等级是 DEBUG
导致 PCL 这个 -cp 的顺序没法输出对应的 DEBUG 信息
（希望尽快融合正式版）

### 原因

jvm参数因为安装方式不同，导致-cp参数位置不同，进而无法使用调试jvm参数（例如：-Dlegacy.debugClassLoading=true -Dlegacy.debugClassLoadingFiner=true）
调整此项后会帮助崩溃分析员更好分析一些崩溃问题等等

**Comment by ZekerZhayard** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/41327811/29f0af2a-2fbe-4296-bc3d-ddec237dd1a5)


在解决某些用户的问题的时候需要用到 `-Dlegacy.debugClassLoading=true -Dlegacy.debugClassLoadingFiner=true` 之类的参数，如果是正常情况下，那么会在 debug.log 或者 fml-client-latest.log 之类的地方输出 DEBUG 等级的 class transformer 相关的信息，但是因为上述原因，导致 PCL 启动的游戏没法输出。

当事人的日志：
[错误报告-2023-10-21_13.04.18.zip](https://github.com/Hex-Dragon/PCL2/files/13059904/-2023-10-21_13.04.18.zip)

**Comment by LTCatt** [comment]
所以要解决的话应该怎么折腾？

**Comment by JingHai-Lingyun** [comment]
把 `-cp` 往前挪？

**Comment by ZekerZhayard** [comment]
> 所以要解决的话应该怎么折腾？

因为目前应该不能通过 PCL 修改已安装游戏的模组加载器版本，所以只讨论新安装游戏的情况下该怎么办。

我建议是当用户同时安装 Forge 和 OptiFine 时，version json 中的 libraries 的顺序应当是 Forge 的 libraries 在最前面，OptiFine 其次，原版在最后，并且每个模组加载器内部的 libraries 顺序也应该与原生 installer 生成的顺序一致。

**Comment by LTCatt** [comment]
我记得现在的顺序是因为，用默认顺序部分 OptiFine+Forge 版本会导致崩溃……
如果可以的话我觉得最好改成和 HMCL 完全一样的顺序，我问问先

**Comment by LTCatt** [comment]
@huanghongxun

**Comment by burningtnt** [comment]
黄鱼几百年没上过过线了
如果炸鸭不来处理，那我可能就得开源码看一看

**Comment by burningtnt** [comment]
当 OptiFine 被安装时，HMCL 会记录以下 Patch 信息：
```java
new Version(
        LibraryAnalyzer.LibraryType.OPTIFINE.getPatchId(), // Patch ID
        remote.getSelfVersion(), // Patch Version
        10000, // Patch Priority
        new Arguments().addGameArguments("--tweakClass", "optifine.OptiFineTweaker"), // Patch Game Arguments
        LibraryAnalyzer.LAUNCH_WRAPPER_MAIN, // Patch Main Class
        libraries // Patch libraries
);
```

当 Forge 被安装时，HMCL 会记录以下 Patch 信息：
```java
installProfile.getVersionInfo()
    .setPriority(30000) // Patch Priority
    .setId(LibraryAnalyzer.LibraryType.FORGE.getPatchId()) // Patch ID
    .setVersion(selfVersion) // Patch Version
```

当 HMCL 需要写入 Version 到 version.json 中时，会按照 Patch Priority 从小到大的顺序依次合并 Patch 信息，其中，对于 Game Libraries 的部分处理是直接将拼接。因此，Forge 的 Game Libraries 将会放在 OptiFine 之后（这一步不会去重）。
当启动游戏时，会按照如下逻辑拼接 -cp 参数：
```java
default Set<String> getClasspath(Version version) {
    Set<String> classpath = new LinkedHashSet<>();
    for (Library library : version.getLibraries())
        if (library.appliesToCurrentEnvironment() && !library.isNative()) {
            File f = getLibraryFile(version, library);
            if (f.exists() && f.isFile())
                classpath.add(f.getAbsolutePath());
        }
    return classpath;
}
```
解释：按照拼接好的 Game Libraries 顺序先去重，后直接按找原来的顺序拼接为 -cp。

**Comment by LTCatt** [comment]
按照描述来看没有发现问题啊……MC 原版的 cp 确实在 Forge 前面……

![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/b1fe500f-5ae5-48cf-85f2-6a702969d9d5)
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/14735211-719f-4e3c-8f73-703bec206385)
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/99a3deff-c5dc-4ff1-a31a-c21c6ce1f214)

**Comment by ZekerZhayard** [comment]
这是因为 PCL 安装的时候 json 就错了，官启只是严格按照 json 决定启动参数
如果你用官方的 forge 安装器安装，那么启动的时候 forge 相关的 jar 就会在 classpath 前面

**Comment by zkitefly** [comment]
在 Linux 测试

[1.12.2-forge-1.12.2-14.23.5.2860-cmd.txt](https://github.com/Hex-Dragon/PCL2/files/14892271/1.12.2-forge-1.12.2-14.23.5.2860-cmd.txt)

![image](https://github.com/Hex-Dragon/PCL2/assets/64117916/f4ef9a3d-f576-4fe5-8c3a-3e6d732ac400)

**Comment by LTCatt** [comment]
楼上用 1.12.2 Forge 官方安装器装的 json，它用了 `inheritsFrom` 属性，所以它必须有一个原版 1.12.2 版本作为继承，而 PCL 和 HMCL 的安装方式会把 json 合并……
我的意思是，反馈者的问题是 `如果是通过 installer 安装的 forge，那么 forge-1.12.2-14.23.5.2859.jar 这玩意儿在 -cp 参数的位置是在 launchwrapper-1.12.jar 前面的，但是通过 PCL 安装了之后就跑到后面去了` 导致的，但我测试后没有发现这个情况，所以应当不会出现反馈者描述的问题

**Comment by ZekerZhayard** [comment]
反馈者就是我。。。
我的意思就是：PCL 安装的 forge 的 -cp 的顺序和官方安装器安装的 forge 的 -cp 行为不一致
