### ISSUE TITLE
[BUG] 程序出现未知错误：序列不包含任何匹配元素

### ISSUE THREAD

**Issue by SuoHouDaiShi** [Hex-Dragon/PCL2#2807]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

点击启用模组，出现错误窗口（没来得及截图Orz
<del>（应该会很罕见吧</del>
另附：Log1最后一行，程序关闭返回值为`FAIL`，估计是崩了
`[18:02:44.516] [System] 程序已退出，返回值：Fail`

### 重现步骤

1.搜索任意模组
2.点击并禁用
3.不要点击刷新，清空搜索栏
4.找到刚刚禁用的模组，此时红石灯状态应为亮起并非熄灭（如果熄灭，请从第1步重复执行直到复现成功）
5.点击该模组，点启动
6.<del>吐一地ERROR</del>BUG出现

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/13062890/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/13062891/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/13062892/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/13062893/Log5.txt)
[Log.txt](https://github.com/Hex-Dragon/PCL2/files/13062894/Log.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13062895/Log1.txt)

可以直接定位Log1看看，因为Log1更改时间是最新的

**Comment by LTCatt** [comment]
修了（
不过我看那个崩溃分析结果也有问题，可以再交个 issue……

**Comment by SuoHouDaiShi** [comment]
@LTCatt 那个，这几天电脑硬盘炸了，换了盘重装了系统，所以……重新发下解锁码（
097A-9248-9F1A-BFE9

上次发到一个优化 Issue 上去了……

**Comment by LTCatt** [comment]
你的解锁码：kCqbXzYvxgSVoy3pZ3LifuKew/1cwCvI
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
