### ISSUE TITLE
内存优化把我电脑卡死了

### ISSUE THREAD

**Issue by RainbowTaro2022** [Hex-Dragon/PCL2#2814]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

我刚刚点了一下内存优化，结果电脑卡住了.
希望把逻辑修改一下

### 原因

以后点击内存优化的时候不要让电脑卡住

**Comment by burningtnt** [comment]
请给出复现步骤

**Comment by JingHai-Lingyun** [comment]
目前已知内存优化会导致使用机械硬盘的设备有一小段时间的卡顿
![image](https://github.com/Hex-Dragon/PCL2/assets/109946426/bf21b568-2cc4-4f97-ab7a-75339ce5bacc)
