### ISSUE TITLE
在新版本更新时pcl启动器会跑掉

### ISSUE THREAD

**Issue by the-autumn-sky** [Hex-Dragon/PCL2#2815]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

我将pcl启动器放在桌面, 桌面设置"网格对齐/不自动排列", 在每次pcl自动更新后, 启动器都不会在原来的位置, 而是在桌面左侧列的尾部

### 原因

每一次自动更新都会导致pcl启动器在桌面上乱跑,非常麻烦

**Comment by burningtnt** [comment]
猜测问题：PCL 是把原文件删除，然后把新文件拷过去
介于 PCL2 只支持 Windows，这个功能大概可以靠 Windows API 解决

**Comment by JingHai-Lingyun** [comment]
确认有这个现象
但... 这貌似不是 PCL 能解决的问题？

**Comment by burningtnt** [comment]
是可以解决的

**Comment by JingHai-Lingyun** [comment]
看龙猫咋说 =-=

**Comment by LTCatt** [comment]
我没法解决这个问题……这是 windows 导致的

**Comment by WorldHim** [comment]
可以在桌面放快捷方式而不是 PCL 本体
