### ISSUE TITLE
[Bug] 索引超出范围：必须为非负值或小于集合大小

### ISSUE THREAD

**Issue by JingHai-Lingyun** [Hex-Dragon/PCL2#2822]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/Hex-Dragon/PCL2/assets/109946426/f6a21868-1ab2-4d7d-ac73-b07365a4e935)
尝试复现 #2821 时意外整出来的

### 重现步骤

> 注：此处 1-6 同 #2821
1. 在音乐目录中塞2个及以上歌曲
2. 音乐播放器放一首歌
3. 把所有歌删了（正在播放的删不了）
4. 右键换歌
5. 关闭错误弹窗
6. 在切换时删除最后一首歌
7. 点击右下角的音乐按钮

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13195476/Log1.txt) 从 `628` 行往下看

**Comment by WorldHim** [comment]
最好在 #2821 下评论而不是新交一个吧。

**Comment by JJJJGGGG1** [comment]
这个我第一次也整出来过，就是没有截图
