### ISSUE TITLE
在有任务正在自定义下载时，下载报错提醒无法被关闭

### ISSUE THREAD

**Issue by deep-dark-forest** [Hex-Dragon/PCL2#2825]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

https://github.com/Hex-Dragon/PCL2/assets/131975043/53dfe5de-cf85-4903-baf2-ae7f7eaa7a2a

当有一自定义下载任务正在进行时，其他自定义下载任务的报错提醒无法关闭

### 重现步骤

首先先用自定义下载下载一个文件A，在文件A下载着的时候，再下载另一个文件B，如果文件B下载出错，那么文件B的报错提醒在文件A下载结束前无法被关闭

### 日志与附件

这个bug是我几天前发现的，当时想反馈，还录了屏，**但是**
当时github怎么也打不开，所以就没反馈，然后现在突然能打开了，录屏还在，但是log却凉凉了（被新日志替换掉了）。。。

**Comment by LTCatt** [comment]
已在新版本修复

**Comment by LTCatt** [comment]
因为没有 log，这个 issue 的原因不可查，不知道是属于 #1848、#3007 还是 #3870……抱歉只能丢个重复了（
