### ISSUE TITLE
关于模组下载时两个同样的模组却能以.disabled和.jar并存导致的空间多占用问题

### ISSUE THREAD

**Issue by liuchenxi12** [Hex-Dragon/PCL2#2827]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

虽然没有多少人会重复下载模组，也不会在意这些空间。
就希望龙猫能在下载模组的时候检查有没有重名但不同后缀的，或是MD5校验？

### 原因

空间不够，在mods文件夹里面发现了一堆同名不同后缀的模组

**Comment by JingHai-Lingyun** [comment]
类似 #2494（#2502）

**Comment by burningtnt** [comment]
重复了，下一次提出建议的时候请先仔细搜索是否有重复的 Issue
