### ISSUE TITLE
罕见情况下更改游戏启动窗口功能模块失灵

### ISSUE THREAD

**Issue by Cpcvoice** [Hex-Dragon/PCL2#2835]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在更改游戏启动窗口的功能模块中，将选项设置为【以854*480的窗口运行Minecraft】（即默认大小选项），在不重启启动器的情况下第二次运行1.16.5版本，1.16.5版本的游戏窗口并没有按照所设置选项（即默认大小选项）执行，而是保持上一次游戏退出时的窗口（即保持游戏默认选项）
注：设置选项如若是【与启动器窗口大小一致】或【自定义大小】，也是上述所说情况

### 重现步骤

1.打开PCL2启动器
2.将更改游戏窗口模块中的选项设置为以854*480的窗口运行Minecraft（即默认大小选项）
3.运行下载好的1.16.5版本（第一次运行）
4.1.16.5版本的游戏窗口成功按照所设置选项（即默认大小选项）执行
5.按F11，使得1.16.5版本的游戏窗口为全屏后退出游戏
6.再次启动1.16.5版本（第二次运行）
7.1.16.5版本的游戏窗口并未按照所设置选项执行，而是保持上一次游戏退出时的窗口大小（即保持游戏默认选项）

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/13235521/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/13235522/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/13235523/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13235527/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/13235528/Log2.txt)

**Comment by youzi-2333** [comment]
成功复现，感谢您的反馈。

（不知道有没有重复 Issue，我这边检索式为 `is:issue 游戏窗口 ` 搜不到）

**Comment by LTCatt** [comment]
个别版本设置不了是 MC 或者 Forge 的 bug
