### ISSUE TITLE
将爱发电私信获取到的快照版本调整为一个相对较新的版本

### ISSUE THREAD

**Issue by Don-Trueno** [Hex-Dragon/PCL2#2836]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

（因意外删除导致需要重新下载后发现）
当前解锁码已调整到为通过爱发电私信获取。
然而在爱发电私信里下载的快照版本中的点击获取识别码按钮，或输入错误的解锁码后。
启动器仍然提示需要复制进内群或联系罗伯特。
这也导致了新用户在新下载快照版后，仍然会到赞助群尝试更新的问题。
可通过将爱发电私信获取到的快照版本调整为一个相对较新的版本解决。

### 原因

优化新用户的使用体验

**Comment by JingHai-Lingyun** [comment]
旧版问题无法解决

**Comment by JingHai-Lingyun** [comment]
这样啊 ~~看起来和本 Issue 的标题和内容完全是两回事的样子~~
