### ISSUE TITLE
支持 curseforge的显示 alpha 文件选项

### ISSUE THREAD

**Issue by qwq2023qwq** [Hex-Dragon/PCL2#2837]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

请添加curseforge的显示 alpha 文件选项
玩部分Mod需要一些指定alpha 版本的Mod，然而下载中并不会显示这些版本

### 原因

我需要这个功能来下载指定alpha 版本的Mod。很多玩过Mod的人都有下载指定alpha 版本的Mod的需求，但如果没有这个功能，就不能在启动器内下载了。

**Comment by hejiehao** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/98140773/d1709fdb-3887-4887-ad4d-774ffbda9cd5)
这不是支持吗？
