### ISSUE TITLE
建议新增本地 mod 仓库系统

### ISSUE THREAD

**Issue by qksuki** [Hex-Dragon/PCL2#2838]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

类似于 maven 的仓库系统，可选新增 mod 仓库系统，本地存储常用 mod。可选增加历史版本，版本选择。

### 原因

在安装整合包时，一些下载量高的模组往往会被重复安装。例如ae、jei、玉等知名模组，在整合包中必不可少。但是每次安装整合包时，都需要重新从网络获取下载，颇为耗时。这一点在科技整合包中尤为明显，都是类似的 mod，但是每次安装整合包时都需要重新从网络获取。同时这个系统也可以解决下载 mod 都需要从网络获取的问题。

如此之后，第一次下载 mod 会在本地存储文件，之后获取 mod 只需要从本地仓库中复制一份到对应的游戏版本文件即可。

对于 mod 的更新，则可以获取 mod 的新版本后添加到本地仓库中，或者是覆盖旧版 mod 文件，具体抉择可以使用设置或者内置决定。

这对我非常有帮助，使用 pcl 的时间中有大量是在等待 mod 的下载。求求了，这真的是史诗级功能 :/

**Comment by JingHai-Lingyun** [comment]
“添加 Mod 收藏夹”
重复 #487 可到 #1646 投票

**Comment by JingHai-Lingyun** [comment]
不同版本呢？
**类似** #487（#1646）

**Comment by qksuki** [comment]
> 不同版本呢？如果都放在本地有点臃肿 **类似** #487（#1646）

我提到了两种方案，添加到历史版本文件夹中，当然这会使本地仓库随时间而臃肿。另外就是新版本覆盖，不过考虑到一些 beta 版本甚至是 release 版本特有的 bug 而需要回退版本的情况，我还是偏向第一种的。另外 mod 仓库也不会太大吧，就算一些 mod 更新十分频繁，塞了好几个版本，也不会比下几个包来的大。但是最好还是放在设置中让用户自由选择吧。

在 mod 面板中对特定 mod 或者是全局设置的选择版本的选项卡，可以选择最新版、某一特定版本等。

**Comment by zkitefly** [comment]
~总感觉会被关掉~

**Comment by LTCatt** [comment]
暂不考虑，抱歉（

**Comment by qksuki** [comment]
> 暂不考虑，抱歉（

哭哭
