### ISSUE TITLE
游戏启动/关闭音乐播放器自动设置音量

### ISSUE THREAD

**Issue by JJJJGGGG1** [Hex-Dragon/PCL2#2840]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

音乐播放器可以自动在游戏启动后将音量设置为为XX%并在关闭后设置为XX%

### 原因

这个优化对于喜欢用其他音乐代替原版背景音乐的人更方便
不至于没有启动时声音小的听不见也不至于启动后盖住游戏内其他声音

**Comment by zkitefly** [comment]
感觉可行:thinking:

**Comment by LTCatt** [comment]
适用面太小，暂时不考虑，抱歉（
