### ISSUE TITLE
樱花披风汉化

### ISSUE THREAD

**Issue by 596wjr** [Hex-Dragon/PCL2#2845]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

目前启动器里樱花披风显示为Cherry Blossom
![image](https://github.com/Hex-Dragon/PCL2/assets/116290244/6daf8cba-9bf9-403d-b35b-900be442b44b)

### 原因

（至少在一个纯中文的软件里突兀的一个英文不太好看吧，这个披风拥有者也不少）

**Comment by LTCatt** [comment]
据说有人看还是没汉化？我没这个披风所以没法测试……

**Comment by JingHai-Lingyun** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/109946426/bbfffda3-36f3-47cd-84fe-9f9b18aed1ca)
yap. 没好

**Comment by LTCatt** [comment]
借了个号，这次真修了

**Comment by 596wjr** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/116290244/ae17e36e-8710-40e5-ba69-9c5a1ca42eb1)
![image](https://github.com/Hex-Dragon/PCL2/assets/116290244/a8aa9f9e-e9e5-4bbb-9bd0-e5db2f1518a2)
讲个笑话

**Comment by Light-Beacon** [comment]
> ![image](https://github.com/Hex-Dragon/PCL2/assets/116290244/ae17e36e-8710-40e5-ba69-9c5a1ca42eb1)
> 
> ![image](https://github.com/Hex-Dragon/PCL2/assets/116290244/a8aa9f9e-e9e5-4bbb-9bd0-e5db2f1518a2)
> 
> 讲个笑话
> 
> 

有没有一种可能...更新还没发

**Comment by 596wjr** [comment]
那就…解锁个隐藏主题？

**Comment by WorldHim** [comment]
> 那就…解锁个隐藏主题？

请发识别码

**Comment by 596wjr** [comment]
> > 那就...解锁个隐藏主题？
> 
> 请发识别码

7482-1132-CD4C-917D

**Comment by LTCatt** [comment]
你的解锁码：dQNFUo2fXQnnIKU8MAMWaVjMzRzM5/8G
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
