### ISSUE TITLE
自定义崩溃分析规则

### ISSUE THREAD

**Issue by burningtnt** [Hex-Dragon/PCL2#2846]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

允许玩家自定义崩溃分析规则，如在游戏崩溃后读取游戏文件夹下的 ./crash-analysis-rule.json 来获取对应的正则表达式与提示语，若正则表达式匹配日志则显示自定义的提示语。

### 原因

整合包通常有特有的、常见的崩溃，整合包作者可以通过这个功能来解决用户的常见问题。

**Comment by burningtnt** [comment]
搜索了 Issue 列表，注意到有关于添加“游戏结束后命令”的内容，但感觉不太一样

**Comment by JingHai-Lingyun** [comment]
> 搜索了 Issue 列表，注意到有关于添加“游戏结束后命令”的内容，但感觉不太一样

两回事

**Comment by LTCatt** [comment]
你如果觉得有什么崩溃是可以被分析的可以自己交 issue，我会加进去的 =。=
自定义这个不现实，肯定要写代码的……

**Comment by burningtnt** [comment]
> 你如果觉得有什么崩溃是可以被分析的可以自己交 issue，我会加进去的 =。=

整合包崩溃的特征是独立无二的，并不是跨整合包通用的，比如在某个整合包中，如果看到了：
```
java.util.ConcurrentModificationException: null
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719) ~[?:?] {}
	at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:741) ~[?:?] {}
	at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(GoalSelector.java:132) ~[?:?]
```

那我就应该提醒用户在 JVM 参数中添加 `-D<modpackid>.fixes.goal_selector_cme_fix=enable`。
这个过程可以在加入次功能后全自动完成


> 自定义这个不现实，肯定要写代码的……

并不是，我是指通过正则表达式来给出一些简单的崩溃分析规则

**Comment by LTCatt** [comment]
适用面很窄……
