### ISSUE TITLE
mod导致崩溃时添加一键禁用导致崩溃的mod的按钮

### ISSUE THREAD

**Issue by Fish-LP** [Hex-Dragon/PCL2#2851]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

mod导致崩溃时会提示类似

> xxx导致了崩溃

这里添加一键禁用导致崩溃的mod的按钮 **或者** 自己选哪些mod禁用

### 原因

（示例）
这项优化让我可以更愉快地van游戏。
如果没有这项优化，我每次都必须
关闭这个框框去mod设置禁用这些特难记的modID(老是忘记
这让操作变得很麻烦。

**Comment by burningtnt** [comment]
某些崩溃无法由简单的禁用对应模组解决

**Comment by Fish-LP** [comment]
可以方便排除不是吗



发送自我的手机。



-------- 原始信息 --------
发件人： Burning_TNT ***@***.***>
日期: 2023/11/5 14:44 (GMT+08:00)
收件人： Hex-Dragon/PCL2 ***@***.***>
抄送： Fish-LP ***@***.***>, Author ***@***.***>
主题： Re: [Hex-Dragon/PCL2] mod导致崩溃时添加一键禁用导致崩溃的mod的按钮 (Issue #2851)


某些崩溃无法由简单的禁用对应模组解决

**Comment by JingHai-Lingyun** [comment]
PCL 的崩溃分析模块的准确率达不到 100%.......（可能偶尔带来意外的禁用？
看龙猫咋说

---

题外话，@Fish-LP 不建议使用邮箱回复，因为我们有可能看到一堆无关的信息

**Comment by youzi-2333** [comment]
PCL 的崩溃分析原理大致是从日志里面搜各种 mod ID 的关键字，可能会导致很多无关 mod 被搜出来，可能会导致正常的 mod 被禁用。而且前置 mod 被禁用还会导致更多的问题……不知道会不会做

**Comment by LTCatt** [comment]
和楼上观点一致，暂不考虑 =。=

**Comment by Fish-LP** [comment]
不是有日志类型吗 看error的话会不会好一点
₍˄·͈༝·͈˄*₎◞ ̑̑


发送自我的手机。
