### ISSUE TITLE
切换页面鼠标提前悬浮于左边栏选项卡时，选择框会超出左边栏

### ISSUE THREAD

**Issue by WForst-Breeze** [Hex-Dragon/PCL2#2853]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

语文水平有限（）看视频吧

https://github.com/Hex-Dragon/PCL2/assets/110760354/189cda38-47b4-4d01-a8ca-b06cdfc54dc4

这里动画速度调为了 0.3x，但事实上正常速度下这个现象也很明显

### 重现步骤

正常速度下使用帮助库会更易于复现：
1. 点击进入任意帮助库页面
2. 鼠标挪动至左边栏的大致位置
3. esc 退出该页面，问题复现

### 日志与附件

见描述部分视频

**Comment by burningtnt** [comment]
感觉无关紧要（？

**Comment by JingHai-Lingyun** [comment]
确认问题存在

**Comment by LTCatt** [comment]
这个我知道，但是贼难修，并且正常动画速度下也很难看出来，所以摆了（
