### ISSUE TITLE
添加对整合包的更新

### ISSUE THREAD

**Issue by Tion-ttz** [Hex-Dragon/PCL2#2854]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

添加一个按钮，实现
识别是什么整合包 → 下载新版的整合包 → 复制旧存档和配置 → 删除旧整合包
引用了部分JingHai-Lingyun的话

### 原因

当一个玩家打开启动器想玩一个早期的minecraft的整合包时，这个包很有可能是不稳定的，有很多bug，急需更新。又或是这个包更新很快。玩家需要去更新他的包。
他会 下载新版的整合包 → 复制旧存档和配置 → 删除旧整合包 这些操作会比较麻烦，而且如果整合包的作者更新快的话，就经常要重复上述操作。

至少我认为是很麻烦的...

**Comment by JingHai-Lingyun** [comment]
此贴讨论于 https://github.com/Hex-Dragon/PCL2/discussions/103#discussioncomment-6586431

**Comment by LTCatt** [comment]
很多时候整合包新旧版本并不兼容，还是交给玩家自己手动折腾为好……并且这玩意儿做着贼难收益也低，新旧文件冲突了又咋办……
