### ISSUE TITLE
没有加任何模组只加了Forge却报错说模组冲突是怎样(我没有HMCL)

### ISSUE THREAD

**Issue by 23998886688RdHy** [Hex-Dragon/PCL2#2861]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃基本不是 PCL 的原因，请 **不要** 提交反馈。你可以在论坛或社区找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用 HMCL 启动，HMCL 没有出现问题。** 如果 HMCL 也无法启动就不是 PCL 导致的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

[错误报告-2023-11-6_20.47.19.zip](https://github.com/Hex-Dragon/PCL2/files/13277375/-2023-11-6_20.47.19.zip)

### PCL 错误报告、日志与附件

[错误报告-2023-11-6_20.47.19.zip](https://github.com/Hex-Dragon/PCL2/files/13277382/-2023-11-6_20.47.19.zip)

### HMCL 启动脚本

本人未使用过HMCL启动器
[错误报告-2023-11-6_20.47.19.zip](https://github.com/Hex-Dragon/PCL2/files/13277427/-2023-11-6_20.47.19.zip)
[错误报告-2023-11-6_20.47.19.zip](https://github.com/Hex-Dragon/PCL2/files/13277439/-2023-11-6_20.47.19.zip)

**Comment by 23998886688RdHy** [comment]
说是我用HMCL试过了实际上我根本就没有HMCL

**Comment by burningtnt** [comment]
`java.lang.UnsatisfiedLinkError: org.lwjgl.openal.AL10.nalGetSourcei(II)I`
