### ISSUE TITLE
更改 Minecraft Wiki 链接

### ISSUE THREAD

**Issue by Light-Beacon** [Hex-Dragon/PCL2#2865]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

需要将版本更新日志等 Minecraft Wiki 的链接中的 `https://minecraft.fandom.com/zh/wiki/` 替换为 `https://zh.minecraft.wiki/w/`。

### 原因

Minecraft Wiki 已从 Fandom 迁至 Weird Gloop，原来站点基本废弃。

**Comment by hejiehao** [comment]
6
~~这出现顺序好像不太对~~
已经有 PR 处理这件事了
#2864

**Comment by Light-Beacon** [comment]
哦 淦 才发现有pr了

**Comment by JingHai-Lingyun** [comment]
没事

**Comment by zkitefly** [comment]
我把他打开并链接到这里吧

**Comment by SadEPa0628** [comment]
啊..我刚才还创建个一样问题的议题，当时咋没看到这个
