### ISSUE TITLE
[优化] CurseForge 访问链接优化

### ISSUE THREAD

**Issue by youzi-2333** [Hex-Dragon/PCL2#2866]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

当 CurseForge 访问失败时，将其访问链接改为 IP 直连后重试。

### 原因

1. 可以免去 DNS 解析的步骤，减少访问时间；
2. 根据 itdog 网站测速结果，北京地区可能存在 curseforge 解析为回环地址的情况，而 IP 直连则没有访问问题。目前 modrinth 没有发现此问题。

---

不太确定能不能行，毕竟 IP 直连的话，.NET 提供的 http 请求函数可能会认为 SSL 证书地址不准确，导致安全问题……

**Comment by LTCatt** [comment]
我不太确定这样做会不会导致其他问题？

**Comment by youzi-2333** [comment]
（个人认为）理论上不会导致其它问题，除了 SSL 证书可能会被判定为不安全…

另外有些网站 IP 直连可能会丢个 400 或者别的错误拒绝访问，我这边也不方便测试……要是有人能测试的话可以帮忙试试.jpg

**Comment by burningtnt** [comment]
CurseForge 使用 IPv6，如果使用 IP 直连 `https://[2606:4700::6811:c734]/` 会直接被 403 Forbidden
这个方案可以送走了

**Comment by LTCatt** [comment]
结果一样。这也确实会导致 CDN 分布不动……
