### ISSUE TITLE
为每个版本添加独立的窗口设置

### ISSUE THREAD

**Issue by Alex6357** [Hex-Dragon/PCL2#2868]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

为每个版本添加独立的窗口设置，现在只能在全局设置

### 原因

有一个用来玩的版本，一个用来录制的版本，一个要全屏，一个要最大化，有单独设置就不用每次进游戏再调了

**Comment by LTCatt** [comment]
感觉需求不大，暂时不考虑制作
