### ISSUE TITLE
官方启动器文件夹中莫名出现新启动器

### ISSUE THREAD

**Issue by lloana10010** [Hex-Dragon/PCL2#2869]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

删除官方启动器文件夹中的其他版本后，会出现新的一个版本，图标为红石块，信息为：Forge8.9.0.775

### 重现步骤

1、在官方启动器文件夹（出现的时候用的）中下载任意版本，只下载Minecraft，不下载forge或optifine或其他
2、下载完毕后，在plc2版本选择中找到官方启动器文件夹一组，点开后把里面下载好的版本删除
3、删除后应该会出现一个新版本，红石块图标的

### 日志与附件

[Forge8.9.0.775.zip](https://github.com/Hex-Dragon/PCL2/files/13328001/Forge8.9.0.775.zip)
这是本文件
[photo.zip](https://github.com/Hex-Dragon/PCL2/files/13328009/photo.zip)
这是照片
[rizhi.zip](https://github.com/Hex-Dragon/PCL2/files/13328010/rizhi.zip)
这是日志（好像无关……）

**Comment by JingHai-Lingyun** [comment]
红石块图标的？
这在 PCL 意味着异常（缺失 Jar/Json）的版本

**Comment by burningtnt** [comment]
官方启动器是怎么删除版本的？会不会是官起没有删除干净

**Comment by LSGtorch** [comment]
开调试模式再发日志试试（ ）

**Comment by hejiehao** [comment]
> 红石块图标的？ 这在 PCL 意味着异常（缺失 Jar/Json）的版本

其实用 1.6.1 的 Forge 8.9.0.775 手动安装也会出现红石块

**Comment by hejiehao** [comment]
> 官方启动器是怎么删除版本的？会不会是官起没有删除干净

~~不是用 PCL2 删除的吗？~~

**Comment by lloana10010** [comment]
> 你确定你没装伪造？把官启的创建版本页面截个图？

我这里是之前下了个1.6版本的Minecraft（没有安装其他的了，具体哪个版本没仔细看），删除后出现的

**Comment by lloana10010** [comment]
> 官方启动器是怎么删除版本的？会不会是官起没有删除干净

可能是意外出现，删了之后就好了吧…….-.-

**Comment by hejiehao** [comment]
> > 官方启动器是怎么删除版本的？会不会是官起没有删除干净
> 
> 可能是意外出现，删了之后就好了吧…….-.-

你是不是跑过一个长得像这个样子的东西
![image](https://github.com/Hex-Dragon/PCL2/assets/98140773/7e33f52c-d3a1-4cb1-a83b-d9e6743d6f40)

**Comment by lloana10010** [comment]
> 开调试模式再发日志试试( )

光标放在版本一列上，右边有垃圾桶的图标

**Comment by lloana10010** [comment]
> > > 官方启动器是怎么删除版本的？会不会是官起没有删除干净
> > 
> > 
> > 可能是意外出现,删了之后就好了吧…….-.-
> 
> 你是不是跑过一个长得像这个样子的东西 ![image](https://user-images.githubusercontent.com/98140773/282304601-7e33f52c-d3a1-4cb1-a83b-d9e6743d6f40.png)

没有，我是自动安装后删除的

**Comment by lloana10010** [comment]
> 开调试模式再发日志试试( )

我感觉日志就根本没有用，pcl2根本识别不了这个

**Comment by lloana10010** [comment]
> 开调试模式再发日志试试( )

我感觉日志是没有用的，启动都启动不了……ε=(´ο｀*)))唉

**Comment by hejiehao** [comment]
> > > > 官方启动器是怎么删除版本的？会不会是官起没有删除干净
> > > 
> > > 
> > > 可能是意外出现,删了之后就好了吧…….-.-
> > 
> > 
> > 你是不是跑过一个长得像这个样子的东西 ![image](https://user-images.githubusercontent.com/98140773/282304601-7e33f52c-d3a1-4cb1-a83b-d9e6743d6f40.png)
> 
> 没有，我是自动安装后删除的

官启有自动安装？

**Comment by lloana10010** [comment]
> > > > > 官方启动器是怎么删除版本的？会不会是官起没有删除干净
> > > > 
> > > > 
> > > > 可能是意外出现,删了之后就好了吧…….-.-
> > > 
> > > 
> > > 你是不是跑过一个长得像这个样子的东西 ![image](https://user-images.githubusercontent.com/98140773/282304601-7e33f52c-d3a1-4cb1-a83b-d9e6743d6f40.png)
> > 
> > 
> > 没有，我是自动安装后删除的
> 
> 官启有自动安装？

啊...我用的pcl2下载到了官起文件夹

**Comment by LTCatt** [comment]
打开官启 MC 文件夹下的 versions，看看有没有这个子文件夹？

**Comment by lloana10010** [comment]
> 打开官启 MC 文件夹下的 versions，看看有没有这个子文件夹？
[versions.zip](https://github.com/Hex-Dragon/PCL2/files/13349803/versions.zip)
有

**Comment by LTCatt** [comment]
这玩意儿不是 PCL 安装的，文件创建日期都是 2023/7/24
