### ISSUE TITLE
无法使用PCL2安装/启动快照23w45a版本

### ISSUE THREAD

**Issue by Don-Trueno** [Hex-Dragon/PCL2#2871]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在反馈该bug前，我已经一定程度上自行尝试，但无法解决这一问题

如题，使用PCL2下载快照版本23w45a时，提示合并文件出错（3608722543847655288247fa525a1fa049a5aa08），但**检查后发现`assets/objects/36/`文件夹下并不存在此文件**。

另有提示“需要管理员权限”，然而**无论右键选择“以管理员权限运行”，还是在“属性-兼容性选项”中设置“使用管理员权限运行此程序”**，仍会出现相同报错。

后来使用 BakaXL 成功下载并运行了，尽管如此，**同一实例文件夹使用PCL2打开时，依旧出现相同报错**。

### 重现步骤

1. 使用PCL2的下载功能下载23w45a快照版本（下载源任意）。
2. 等待错误弹窗出现

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13328639/Log1.txt)

**Comment by hejiehao** [comment]
我这灰常正常
日志显示权限不足

**Comment by JingHai-Lingyun** [comment]
我这里无法复现此 Bug
根据日志所述，PCL 对 `G:\Minecraft\.minecraft\assets\objects\36\3608722543847655288247fa525a1fa049a5aa08` 没有访问权限
尝试以管理员模式启动 PCL（右键 > 以管理员身份运行） 或如楼上所述换个目录试试

**Comment by Don-Trueno** [comment]
> 我这里无法复现此 Bug 根据日志所述，PCL 对 `G:\Minecraft\.minecraft\assets\objects\36\3608722543847655288247fa525a1fa049a5aa08` 没有访问权限 尝试以管理员模式启动 PCL（右键 > 以管理员身份运行） 或如楼上所述换个目录试试

两种操作都进行了，否则不会将其作为bug提交。

自己可确定的是这一文件并不存在，同样的目录可以用BakaXL打开而不需要重新补全文件。
![issus2871](https://github.com/Hex-Dragon/PCL2/assets/109446735/3e6d5403-8e50-4a23-b253-afe316c639ab)

**Comment by hejiehao** [comment]
> > 我这里无法复现此 Bug 根据日志所述，PCL 对 `G:\Minecraft\.minecraft\assets\objects\36\3608722543847655288247fa525a1fa049a5aa08` 没有访问权限 尝试以管理员模式启动 PCL（右键 > 以管理员身份运行） 或如楼上所述换个目录试试
> 
> 两种操作都进行了，否则不会将其作为bug提交。
> 
> 自己可确定的是这一文件并不存在，同样的目录可以用BakaXL打开而不需要重新补全文件。 ![issus2871](https://user-images.githubusercontent.com/109446735/282351808-3e6d5403-8e50-4a23-b253-afe316c639ab.png)

你怎么知道 BakaXL 没有补全文件

**Comment by Don-Trueno** [comment]
> 你怎么知道 BakaXL 没有补全文件

问题表述已经写过了：**后来使用 BakaXL 成功下载并运行了，尽管如此，同一实例文件夹使用PCL2打开时，依旧出现相同报错。**

作为issue反馈是因为我希望能解决这一问题，而不是还得将自己的问题复述若干次，单论要能启动游戏的话事实上我已经可以使用BakaXL进行了，只是不习惯BakaXL的页面风格而已。

**Comment by hejiehao** [comment]
> > 你怎么知道 BakaXL 没有补全文件
> 
> 问题表述已经写过了：**后来使用 BakaXL 成功下载并运行了，尽管如此，同一实例文件夹使用PCL2打开时，依旧出现相同报错。**
> 
> 作为issue反馈是因为我希望能解决这一问题，而不是还得将自己的问题复述若干次，单论要能启动游戏的话事实上我已经可以使用BakaXL进行了，只是不习惯BakaXL的页面风格而已。

然后你能证明 BakaXL在启动游戏的时候没有补全文件？

**Comment by Don-Trueno** [comment]
> 然后你能证明 BakaXL 在启动游戏的时候没有补全文件？

你如果能说明BakaXL把游戏所需要的assets放在另一文件夹了，并知道如何解决，那请你直接说。
否则我不想浪费时间和你纠缠，也不想讨论BakaXL怎么就启动成功了。
我可能又需要重复一下：作为issue反馈是因为我希望能**解决**这一问题。

**Comment by JingHai-Lingyun** [comment]
等龙猫来看看把，别聊的太过于热门以至于被锁了

**Comment by hejiehao** [comment]
其实你可以尝试一下把 36 文件夹删掉

**Comment by LTCatt** [comment]
`Access to the path 'G:\Minecraft\.minecraft\assets\objects\36\3608722543847655288247fa525a1fa049a5aa08' is denied.`
这是系统权限问题，不是启动器导致的，也无法修复。删除文件夹也不行那我也没办法……

**Comment by kong-que-dnf123** [comment]
_把PCL这个程序移到别的盘里呢......._
_会不会是G盘本身的问题呢......_ ~（比如G盘本身没有权限）~

**Comment by Don-Trueno** [comment]
> `Access to the path 'G:\Minecraft\.minecraft\assets\objects\36\3608722543847655288247fa525a1fa049a5aa08' is denied.` 这是系统权限问题，不是启动器导致的，也无法修复。删除文件夹也不行那我也没办法……

更进一步检查发现此文件系新方块trial spawner的sound1.ogg音效文件。怀疑下载源缺失此文件，因为使用BakaXL下载时该文件依然处于缺失状态。
已通过”高级启动设置“中的”关闭文件校验“选项临时解决了这一问题……

**Comment by LTCatt** [comment]
不是下载原因，这个报错是 windows 拒绝访问

**Comment by hejiehao** [comment]
> > `Access to the path 'G:\Minecraft\.minecraft\assets\objects\36\3608722543847655288247fa525a1fa049a5aa08' is denied.` 这是系统权限问题，不是启动器导致的，也无法修复。删除文件夹也不行那我也没办法……
> 
> 23w36a版本依然打不开，现象与前面完全相同，更进一步检查发现一直出错的文件其实是新方块trial spawner的sound1.ogg音效文件。 怀疑真正原因是下载源缺失此文件，因为使用BakaXL下载时该文件依然处于缺失状态。 已通过”高级启动设置“中的”关闭文件校验“选项临时解决了这一问题……

你都在说官方源都不行了，我觉得跟镜像源没有关系

**Comment by JingHai-Lingyun** [comment]
**现在能确认的是**：官方源/镜像源 下载没问题（我这里可以正常下载），**是你磁盘的问题**

**Comment by Don-Trueno** [comment]
感谢各位提的建议啦，也抱歉打扰到各位。原因终于找到了，挺无语的：
之前在别人的推荐下给火绒安装了一个自定义规则，这之后便无法在任何地方创建以"360"开头的文件，表现为以各种理由拒绝访问（“你没有权限…”、“你需要xxx的权限才能…”和“该文件正在被占用”）。
已将该自定义规则移除。

这里是查到的日志：
![2](https://github.com/Hex-Dragon/PCL2/assets/109446735/6bcd162a-080d-40c1-8d1a-7391b7a8819d)

**Comment by JingHai-Lingyun** [comment]
原来如此
~~正常的文件被防360的防掉了 6~~

**Comment by kong-que-dnf123** [comment]
~反360系列软件~
挺直接的（）
