### ISSUE TITLE
意外的自动获取 Java 失败

### ISSUE THREAD

**Issue by JingHai-Lingyun** [Hex-Dragon/PCL2#2872]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

换了一台新电脑，把 Minecraft 文件都挪了过去
没有装 Java 想着说用 PCL 自动下载
在启动的时候获取 Java 一段时间后，忽然提示 `没有可用的 Java，已取消启动`

### 重现步骤

在一台没有装任何 Java 的电脑上用 PCL 启动 1.20.2 并自动下载 Java17

### 日志与附件

[Log1-2.txt](https://github.com/Hex-Dragon/PCL2/files/13329839/Log1-2.txt)
翻到最底下左右即可见
> 注: 文件仅为 Log1 从那台新电脑上发过来被 Windows 重命名了 :)

**Comment by burningtnt** [comment]
你这个 Java 还能启动吗？会不会是被 Windows Defender 误杀了，导致 java -version 都启动不了？

**Comment by JingHai-Lingyun** [comment]
可以滴（第二次登录就启动好了..
