### ISSUE TITLE
允许用户以下拉框的形式选择要加载的本地主页文件

### ISSUE THREAD

**Issue by JingHai-Lingyun** [Hex-Dragon/PCL2#2873]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

_Discussed in #2870_ 
现在有了预设主页，感觉下拉框选择方式挺不错的
能不能给本地主页也做出类似这样的多选内容，然后通过类似下面这样的注释头来显示主页名字/作者？
```xml
<!--
pcl-page-config
title:测试主页
anthor:test
-->
```

### 原因

在自己拥有多个 xaml 主页文件并且经常需要切换的时候
每次都需要将旧的文件修改名字或移动
然后再放置新的文件并命名为 Custom.xaml
这未免有些麻烦

**Comment by LTCatt** [comment]
对绝大多数用户都用不上这个功能，所以应该不会考虑做……
