### ISSUE TITLE
1.19以上版本Java自动选择建议优先选择更高版本的Java而不是JDK17

### ISSUE THREAD

**Issue by BringBackMC** [Hex-Dragon/PCL2#2876]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

如果系统存在Java17和更高版本的Java共存，希望修改为1.19版本以上优先选择更高版本的Java而不是优先选择JDK17

### 原因

经常因为网易的JDK17而导致PCL2优先选择了JDK17，而不是JDK21（听说JDK21能提升游戏流畅性）因为能用PCL文件夹来优先选择，所以这个优化不急，只是希望

**Comment by JingHai-Lingyun** [comment]
请不要重复开启 Issue，如发现填写错误可在发起后修改
后续请移步 #2877
