### ISSUE TITLE
允许用户自定义导出启动脚本时的第一行文字

### ISSUE THREAD

**Issue by deep-dark-forest** [Hex-Dragon/PCL2#2880]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

允许用户自定义这个：
![image](https://github.com/Hex-Dragon/PCL2/assets/131975043/10cc7348-d321-43dd-8ca0-b10b8e05a506)
“游戏正在启动，请稍候。”
我觉得可以在选择启动脚本保存位置之前弹出一个文本框让用户输入自己想要的第一行文字

### 原因

感觉多多少少有点用，尤其是对于那些不懂启动脚本工作原理的人来说

**Comment by zkitefly** [comment]
为啥不能自己改呢，感觉意义不大

不过可以让龙猫看看

**Comment by deep-dark-forest** [comment]
> 为啥不能自己改呢，感觉意义不大
> 
> 不过可以让龙猫看看

万一有人不知道这东西可以改txt格式呢（

**Comment by SALTWOOD** [comment]
面向用户群体窄，调试作用而非启动游戏左右，而且又不是不能自己改，你改一改行字的时间和龙猫加这个功能的时间差好几倍，几乎不可能通过。

**Comment by deep-dark-forest** [comment]
> 面向用户群体窄，调试作用而非启动游戏作用，而且又不是不能自己改，你改一改行字的时间和龙猫加这个功能的时间差好几倍，几乎不可能通过。

但是吧了解怎么改这个东西的时间可能和龙猫加这个功能的时间差不多，对于有些对电脑一窍不通的人来说

**Comment by deep-dark-forest** [comment]
>而且又不是不能自己改，你改一改行字的时间和龙猫加这个功能的时间差好几倍

有些不认同，就比如现在大家都很需要的整合包导出功能，是不是自己又不能换启动器，自己换个hmcl的时间和龙猫加这个功能的时间差好几倍（
