### ISSUE TITLE
system.io.filenotfoundexception问题（文件路径并没有非法字符）

### ISSUE THREAD

**Issue by Think-noodles** [Hex-Dragon/PCL2#2885]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

程序出现未知错误：无法找到指定文件。
在PCL.ModSecret.SecretOnApplicationStarto
在PCL.Application.Application＿Startup（Object sender， StartupEventArgs e)
错误类型：System.IO.FileNotFoundException
是否反馈此问题？如果不反馈，这个问题可能永远无法得到解决！

### 重现步骤

1、清理了c盘里的软件配置文件appdate
2、点击pcl

### 日志与附件

没了

**Comment by JingHai-Lingyun** [comment]
日志..... 没了？

**Comment by LTCatt** [comment]
请补充日志文件

**Comment by Chiloven945** [comment]
你这……给AppData删了，你删里面的temp没问题你全部给删了的话不炸才怪……

**Comment by LTCatt** [comment]
考虑大概率和 PCL 无关，且暂时没回复，先关了 =。=

**Comment by SuoHouDaiShi** [comment]
![图片](https://github.com/Hex-Dragon/PCL2/assets/119282947/7349a4d9-d66a-445a-a65a-0267b952e2fe)
估计是他自己的问题，看了 Appdata 目录里面**的的确确有 PCL 的文件夹，点开之后发现一个名为 libjlw.dll 的动态链接库文件，再参考 lib 含有库的意思，结合 `System.IO.FileNotFoundException` 这一串信息，很有可能这个 libjlw.dll 是 PCL 的重要文件，所以是操作者本人操作不当的问题……**
