### ISSUE TITLE
HMCL导出的整合包无法导入PCL2

### ISSUE THREAD

**Issue by IMSB-IMSB** [Hex-Dragon/PCL2#2888]
### 检查项

- [ ] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

HMCL导出的整合包导入PCL2时提示“该整合包未提供游戏版本信息，无法安装！”

### 重现步骤

1、从HMCL导出整合包
2、将压缩包拖入PCL2

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13402841/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/13402842/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/13402843/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/13402844/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/13402845/Log5.txt)

**Comment by youzi-2333** [comment]
五个日志都翻了一遍，没发现问题……

请将问题再进行复现，然后重新发送这些日志，同时请一并发送整合包文件。

**Comment by hejiehao** [comment]
Log2.txt 有写

**Comment by JingHai-Lingyun** [comment]
> Log2.txt 有写，但是 Log2.txt 的启动器不是最新版

照这样看，启动器更新下看看还会不会出现问题？

**Comment by burningtnt** [comment]
请尽快上传导出的整合包文件，方便判断是 HMCL 还是 PCL2 的问题

**Comment by youzi-2333** [comment]
> Log2.txt 有写，但是 Log2.txt 的启动器不是最新版

抱歉，我眼瞎了（

**Comment by LTCatt** [comment]
这是由于 modpack.json 中没有 gameVersion 信息
需要上传整合包或者整合包下载地址

**Comment by IMSB-IMSB** [comment]
> 这是由于 modpack.json 中没有 gameVersion 信息 需要上传整合包或者整合包下载地址

链接：https://pan.baidu.com/s/1IIuqWsjW6gd5TWSR5Zbp_Q?pwd=1111 
提取码：1111

**Comment by IMSB-IMSB** [comment]
> 请尽快上传导出的整合包文件，方便判断是 HMCL 还是 PCL2 的问题

链接：https://pan.baidu.com/s/1IIuqWsjW6gd5TWSR5Zbp_Q?pwd=1111 
提取码：1111

**Comment by burningtnt** [comment]
> > 请尽快上传导出的整合包文件，方便判断是 HMCL 还是 PCL2 的问题
> 
> 链接：https://pan.baidu.com/s/1IIuqWsjW6gd5TWSR5Zbp_Q?pwd=1111 提取码：1111

拒绝百度网盘

**Comment by IMSB-IMSB** [comment]
> > > 请尽快上传导出的整合包文件，方便判断是 HMCL 还是 PCL2 的问题
> > 
> > 
> > 链接：https://pan.baidu.com/s/1IIuqWsjW6gd5TWSR5Zbp_Q?pwd=1111 提取码：1111
> 
> 拒绝百度网盘

我用夸克网盘分享了「无人入眠4.zip」，点击链接即可保存。打开「夸克APP」，无需下载在线播放视频，畅享原画5倍速，支持电视投屏。
链接：https://pan.quark.cn/s/bffa0c17ddd2

**Comment by burningtnt** [comment]
需要登录才能下载，不考虑

**Comment by HomoobyDX** [comment]
我下的最后的夸克网盘，打开modpack.json发现只有一个name
![image](https://github.com/Hex-Dragon/PCL2/assets/120797993/0a0b8246-1f25-47bd-8513-287a37fa4b81)

**Comment by hejiehao** [comment]
下载个整合包难如登天

**Comment by IMSB-IMSB** [comment]
> 下载个整合包难如登天

我怎么搞啊，回复里说文件太大不让上传，想用蓝奏云来着却要米才让我上传，我应该拿什么渠道:(

**Comment by HomoobyDX** [comment]
可以选择联系QQ群

**Comment by zkitefly** [comment]
> > 下载个整合包难如登天
> 
> 我怎么搞啊，回复里说文件太大不让上传，想用蓝奏云来着却要米才让我上传，我应该拿什么渠道:(

https://wenshushu.cn

**Comment by burningtnt** [comment]
@LTCatt 已经在 HMCL 最新快照版做测试，其导出的整合包不包含 modpack.json
说明，当事人的整合包与 HMCL 无关，可以关闭本 Issue 了

**Comment by JingHai-Lingyun** [comment]
不包含 modpack.json 可还行 :(

**Comment by burningtnt** [comment]
没想到吧，当事人的整合包根本不是 HMCL 导出的 ![image](https://github.com/Hex-Dragon/PCL2/assets/88144530/e8d05fc5-9c59-4eb2-bc38-64e069e78d3e)

**Comment by burningtnt** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/88144530/747bf82d-2339-4459-aac4-ac48671824d7)
从源代码上看，HMCL 从未往 modpack.json 写入过东西
