### ISSUE TITLE
加入自定义软件打开日志

### ISSUE THREAD

**Issue by hehetoshang** [Hex-Dragon/PCL2#2890]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

由于某些电脑的记事本有些问题，所以使用有问题的记事本打开文件的时候pcl会报错，所以我希望可以加入自定义软件打开日志的功能（我电脑更改txt、log打开方式后，第二天打开方式又丢失了）

### 原因

这项优化让我可以让我直接查看日志。
如果没有这项优化，我每次都必须更改打开方式，让操作变得很麻烦。

**Comment by JingHai-Lingyun** [comment]
感觉适用面比较小...
~~怎么看怎么像#2887的后续~~

**Comment by LTCatt** [comment]
系统问题不由启动器解决
