### ISSUE TITLE
下拉菜单淡入淡出不受动画速度限制

### ISSUE THREAD

**Issue by PDY111** [Hex-Dragon/PCL2#2894]
### 检查项

- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

---
下拉菜单淡入淡出不受设置>启动器>调试选项>动画速度限制

[video](https://wwvp.lanzoue.com/iJeHZ1fs0ira)

### 原因

仅是美化与强迫症

**Comment by JingHai-Lingyun** [comment]
根据反馈描述提供的视频，反馈者想要描述的是一个 Bug：
即使加快 / 减慢了动画速度，下拉菜单的淡入淡出速度仍然为 1.0x

---

确认现象于 2.6.10 版本中存在

**Comment by LTCatt** [comment]
这个动画是 Windows 提供的，无法修改速度 :/
