### ISSUE TITLE
PCL自启动

### ISSUE THREAD

**Issue by zhang5249130** [Hex-Dragon/PCL2#2896]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

如题中所说，非常简单，只需要实现PCL随电脑自动启动，并启动MC就行...

### 原因

本人有一台电脑专门玩MC的（虽然配置不高...），如果可以直接让PCL自启那就最好了
（之前试过通过导出的脚本+service实现自启，但是登录后无法进入多人服务器）
（大晚上的真的不知道有没有与其重复的建议啊，各位如果有看到类似的那就把我的close掉吧...）

**Comment by LTCatt** [comment]
若有需要可以自行将 PCL 添加到开始菜单的 `启动` 文件夹，不考虑在启动器内添加支持，抱歉
