### ISSUE TITLE
Minecraft错误提交器

### ISSUE THREAD

**Issue by gi199** [Hex-Dragon/PCL2#2897]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

在更多-百宝箱选项卡中添加“MC错误提交器”点击并描述并上传Log即可上传

### 原因

（示例）
我需要这个功能来提交更多的MC错误

**Comment by zkitefly** [comment]
感觉可以 🤔

**Comment by burningtnt** [comment]
？你把错误报告提交到哪里呢？

**Comment by JingHai-Lingyun** [comment]
提交了之后识别判定样例貌似不好整...

**Comment by zkitefly** [comment]
或许可以提交到 https://mclo.gs ？

**Comment by JingHai-Lingyun** [comment]
emm 好主意，不过他是想贡献日志给崩溃分析模块的...

**Comment by LTCatt** [comment]
如果有日志你觉得能交可以直接开 issue，我会处理的
但启动器内就没必要加这个功能了……

**Comment by iPodtouch6557** [comment]
记得以前有来着 但是后来金数据转github之后因为访问性问题删了
