### ISSUE TITLE
安装Enigmatica 9：Expert 时候出现错误

### ISSUE THREAD

**Issue by xiaobian663** [Hex-Dragon/PCL2#2899]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

龙猫大大您好：在安装Enigmatica 9：Expert 时候出现错误
整合包安装失败
→ 下载 Mod失败
→ 文件下载失败：D:\minectft\.minecraft\versions\Enigmatica 9：Expert - E9E\mods\EmendatusEnigmatica-2.1.5-build.61+mc1.19.2.jar
远程服务器返回错误: (404) 未找到。（https://media.forgecdn.net/files/4551//EmendatusEnigmatica-2.1.5-build.61%2Bmc1.19.2.jar）
→ 远程服务器返回错误: (404) 未找到。
在 PCL.ModNet.NetFile.Thread(NetThread Info)
错误类型：System.Net.WebException
麻烦您看下是否是下载源错误的问题 如果是 烦请修复下

### 重现步骤

使用在curseforge下载的整合包和在启动器中下载安装均出错 整合包版本为1.15.1

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13464344/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/13464345/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/13464346/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/13464347/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/13464348/Log5.txt)

**Comment by JingHai-Lingyun** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/109946426/a105b2d1-caad-4ec4-82b5-73634f54df17)
初步确认问题存在，我接着排查下是不是源的问题

---

另附一小提示：整合包的 **MC 版本**为 1.19.2（内含 1.15.1 结尾的）

**Comment by JingHai-Lingyun** [comment]
好了确认了 是源的问题
错误的地址：https://media.forgecdn.net/files/4551//EmendatusEnigmatica-2.1.5-build.61%2Bmc1.19.2.jar
正确的地址：https://media.forgecdn.net/files/4551/0/EmendatusEnigmatica-2.1.5-build.61%2Bmc1.19.2.jar
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;↑
此处少了个 `0`

**Comment by hejiehao** [comment]
fileId 为 4551000

**Comment by JingHai-Lingyun** [comment]
在 CurseForge 下的应该不会出事
![image](https://github.com/Hex-Dragon/PCL2/assets/109946426/365ef8e0-7d3b-4250-ac4f-53154f58b032)
那个 `0` 是在的

**Comment by hejiehao** [comment]
如果用 Python 表示应该像这样子 `https://edge.forgecdn.net/files/%d/%d/%s" %(fileId / 1000, fileId % 1000, fileName)`
