### ISSUE TITLE
hmcl无法启动由pcl下载的Minecraft

### ISSUE THREAD

**Issue by afhw** [Hex-Dragon/PCL2#2901]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我的由pcl2下载的minecraft版本无法在hmcl中启动
![285635369-d5aaee22-d691-4bef-bcce-bb12f52e30ab](https://github.com/Hex-Dragon/PCL2/assets/124336808/105be38b-ac3d-44fa-8b09-e9e35bac9dee)

### 重现步骤

1、在pcl2中下载一个1.12.2的forge+opifine版本
2、在hmcl中启动这个版本

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/13466164/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/13466165/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/13466166/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13466167/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/13466168/Log2.txt)

**Comment by burningtnt** [comment]
已有相同的 Issue
#2801 #2705
