### ISSUE TITLE
在窗口大小修改时连带修改鼠标悬停提示框

### ISSUE THREAD

**Issue by MCSteve123** [Hex-Dragon/PCL2#2902]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

如题，在修改窗口大小时，鼠标悬停的提示框是不会改变大小的，对于大屏不太友好……
![小窗口](https://github.com/Hex-Dragon/PCL2/assets/121204926/ecfeb7fd-0bff-4748-a5a4-d26b3dd4a2ac)
![大窗口](https://github.com/Hex-Dragon/PCL2/assets/121204926/3e4eadf1-c2dd-4fae-877a-1b6b4cc3dfaa)
和周围参照物对比可以发现，窗口大小不会改变提示大小

### 原因

这项优化让很多人可以更方便地用大屏玩游戏。
如果没有这项优化，很多人每次都必须瞪着不怎么灵活的眼珠子看屏幕，让操作变得很费眼睛。
而且这样更加符合直觉

**Comment by burningtnt** [comment]
这个悬浮框…… 似乎是 Windows 控制的（？）

**Comment by MCSteve123** [comment]
我不到啊，我也不会VB

**Comment by LTCatt** [comment]
感觉会变大小反而会很怪……算了……
