### ISSUE TITLE
“Minecraft 新手指南” 无法正确跳转

### ISSUE THREAD

**Issue by SALTWOOD** [Hex-Dragon/PCL2#2903]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如题目，会自动跳转至 Biligame，但可能是因为 URL 变动，已无法显示对应的页面
原指向地址：[https://wiki.biligame.com/mc/教程](https://wiki.biligame.com/mc/教程)
现自动重定向至：[https://wiki.biligame.com/wiki/首页](https://wiki.biligame.com/wiki/首页)

恰好现在 Minecraft 中文 Wiki 迁移了，建议更改为[https://zh.minecraft.wiki/教程](https://zh.minecraft.wiki/教程)

### 重现步骤

更多 -> 帮助 -> Minecraft -> Minecraft 新手指南

### 日志与附件

莫得

**Comment by JingHai-Lingyun** [comment]
> 会自动跳转至 Biligame，但可能是因为 URL 变动，已无法显示对应的页面 

BiliWiki MC 板块没了已经

---

> 功能已经实现：#2864 #2865 请关闭本 Issue

这个是新手指南页面的 和 #2864 不太一样

**Comment by burningtnt** [comment]
我猜龙猫已经顺便把这个地方解决了.jpg

**Comment by JingHai-Lingyun** [comment]
应该把

**Comment by SALTWOOD** [comment]
那就等龙猫看看吧，我也是胡乱翻才注意到
这个应该是被写进某个特定的文件的，忘记改也不是不可能（？

**Comment by SALTWOOD** [comment]
看了下源码似乎找不到对这一段的定义，PR是不可能了，等龙猫亲自过来看看

**Comment by LTCatt** [comment]
https://github.com/LTCatt/PCL2Help/commit/c5d47690df611750b515c590a5ea16601d79f7e6

**Comment by burningtnt** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/88144530/1cbc75d5-0ed0-4d87-968b-dec232fd0692)
