### ISSUE TITLE
运行最新PCL2正式版提示“已经阻止此发布者在你的计算机上运行软件”

### ISSUE THREAD

**Issue by LanYangYang-114** [Hex-Dragon/PCL2#2904]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

运行PCL2出现“已经阻止此发布者在你的计算机上运行软件”提示且没有运行按钮（见附件1），点击窗口上的“未知发布者”会弹出数字签名详细信息，窗口内显示“证书已被颁发者直接吊销”（见附件2），根据[微软社区的问答](https://answers.microsoft.com/zh-hans/windows/forum/all/%e5%a6%82%e4%bd%95%e5%8f%96%e6%b6%88%e9%98%bb/b5ccd82c-8155-49cf-9323-61bbb7004f28)试图取消阻止发布者，发现系统并没有任何未受信任的发布者（见附件3），测试没有数字签名的老版本PCL可以直接运行（见附件4）
这台电脑没改过安全性相关的设置，更新了最新的windows更新，禁用了Windows 安全中心，系统信息见附件5

### 重现步骤

1、从爱发电页面下载最新的正式版PCL2 (2.6.10)
2、使用文件资源管理器自带的解压功能解压下载的压缩包
3、运行Plain Craft Launcher 2.exe

### 日志与附件

![附件1](https://github.com/Hex-Dragon/PCL2/assets/84030410/65f94891-2b06-4758-940a-0c5d410608a1)
![附件2](https://github.com/Hex-Dragon/PCL2/assets/84030410/aa916429-a21a-4cb0-930a-e89a773d573b)
![附件3](https://github.com/Hex-Dragon/PCL2/assets/84030410/b07d4446-ae56-4833-a94d-26126f3f287a)
![附件4](https://github.com/Hex-Dragon/PCL2/assets/84030410/e2a40ab9-70b0-4766-bacb-8219762b5a4f)
![附件5](https://github.com/Hex-Dragon/PCL2/assets/84030410/8b803294-f681-46c9-8fec-afa1cedd7232)

**Comment by ZhaiSoul** [comment]
搞定了搞定了，之前的签名到期了，现在应该好了

**Comment by LTCatt** [comment]
umm 如果提交者 @LanYangYang-114 确认问题已经解决可以自行 Close as Completed

**Comment by LanYangYang-114** [comment]
问题似乎还在，我这边点进数字签名提示的依然是被吊销
（我是替朋友提交反馈的，他电脑上才有这个问题，

**Comment by LanYangYang-114** [comment]
刚才不小心手抖给Close了...总之这个问题似乎还在，我这边点进数字签名提示的依然是被吊销，可能要重新签名一次？
![附件1](https://github.com/Hex-Dragon/PCL2/assets/84030410/2f8fb319-61e7-4661-bb44-220fc05d1c8a)
（我是替朋友反馈的，他电脑上才有这个问题，我虚拟机和物理机怎么搞都不会被阻止运行，我晚点问问他那边现在能不能打开）

**Comment by ZhaiSoul** [comment]
之前的版本证书已经到期了，没有办法，只能下新版

**Comment by ZhaiSoul** [comment]
> > umm 如果提交者 @LanYangYang-114 确认问题已经解决可以自行 Close as Completed
> 
> 呃 那个说解决了的貌似不是 Author

因为我是证书提供者…已经更换Actions构建的证书了，已经与龙猫进行了沟通。

**Comment by LanYangYang-114** [comment]
> 之前的版本证书已经到期了，没有办法，只能下新版

意思是说在下一个版本才会修复证书问题对吧，我以为说的是现在直接搞定了（现在依旧是吊销状态）

**Comment by JingHai-Lingyun** [comment]
看起来是的 . . .

**Comment by LTCatt** [comment]
https://afdian.net/p/0164034c016c11ebafcb52540025c377
更新了重新签名的 2.6.10 正式版
