### ISSUE TITLE
最小化久了点继续播放音乐报错

### ISSUE THREAD

**Issue by mc-124** [Hex-Dragon/PCL2#2910]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

见标题与日志 应该是个小毛病

### 重现步骤

暂停音乐播放，最小化，隔一晚上后点继续播放，出错

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13487554/Log1.txt)

**Comment by JingHai-Lingyun** [comment]
1056行
```
Runtime Invoke 4097#：线程执行失败：NoDriver calling waveOutRestart
   在 PCL.ModMusic._Closure$__._Lambda$__14-0()
   在 PCL.ModBase._Closure$__113-0._Lambda$__0()
错误类型：NAudio.MmException
```
NAudio 的 Bug，技术上无法处理。参考 #1753 #2348
