### ISSUE TITLE
Fabric有可能会加载mods目录下的.disabled（被禁用的mod）文件

### ISSUE THREAD

**Issue by mc-124** [Hex-Dragon/PCL2#2911]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

建议把这些被禁用的mod移动到别的地方，我已经试过，把disabled文件移走后游戏就会正常，放回去mods里面就又会报错

### 原因

这项优化避免了在fabric中禁用部分mod导致的意外错误
fabric不知道为什么会加载这玩意真服了
forge没事，quilt那些不知道

**Comment by burningtnt** [comment]
Fabric 原版不会加载 .jar 的模组。如果你确信他会加载，你可以前往 https://kook.top/Kx7n3t 上传错误报告获取帮助。请关闭本 Issue

**Comment by JingHai-Lingyun** [comment]
> 你可以前往 https://kook.top/Kx7n3t 上传错误报告获取帮助
这里是 PCL 社区，拜托

---

> Fabric 原版不会加载 .jar 的模组
这个反馈是在询问为什么 .jar.disabled 模组会被加载

---

综上所述，我的建议是 @mc-124 reopen 这个反馈，并等待进一步处理
另把启动失败的日志和启动器日志传上来看看？

**Comment by burningtnt** [comment]
> > 你可以前往 https://kook.top/Kx7n3t 上传错误报告获取帮助
> 
> 这里是 PCL 社区，拜托

那你整一个 PCL2 为主导的崩溃解决渠道？GitHub Issue Template **已经明确** 拒绝了游戏崩溃

> 
> > Fabric 原版不会加载 .jar 的模组
> 
> 这个反馈是在询问为什么 .jar.disabled 模组会被加载
> 
> 综上所述，我的建议是 @mc-124 reopen 这个反馈，并等待进一步处理 另把启动失败的日志和启动器日志传上来看看？

这与本 Issue 无关？

**Comment by WForst-Breeze** [comment]
上传崩溃报告及启动器日志。

使用其他启动器此问题能否复现？

**Comment by mc-124** [comment]
额我原本是想让PCL把禁用的mod移别的地方的

**Comment by mc-124** [comment]
不好意思，由于没能及时看到这条消息，日志已经刷没了
