### ISSUE TITLE
预设主页历史上的今天文字错误

### ISSUE THREAD

**Issue by DF4C4407** [Hex-Dragon/PCL2#2912]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

历史上的今天主页文字显示乱码
![屏幕截图 2023-11-28 210032](https://github.com/Hex-Dragon/PCL2/assets/150013616/0d7c6fc9-027f-43a1-8f4f-5cefd3e0629b)

### 原因

这项优化可以让我更方便的获取知识（活力橙

**Comment by JingHai-Lingyun** [comment]
因此，你无法获得活跃橙

**Comment by burningtnt** [comment]
所以， @hsuchenghao 请尽快修复此问题

**Comment by hsuchenghao** [comment]
已Fix，感谢你提交了这个问题，虽然你交错了地方
