### ISSUE TITLE
Mod 管理页面中 “安装 Mod” 按钮点击没有反应

### ISSUE THREAD

**Issue by LTCatt** [Hex-Dragon/PCL2#2914]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

2.6.11，Mod 管理页面中 “安装 Mod” 按钮点击没有反应

**Comment by SALTWOOD** [comment]
好奇这个按钮本应实现什么功能？
打开 .jar 文件，跳转到模组下载页面还是什么？

**Comment by JingHai-Lingyun** [comment]
是打开 .jar 文件并安装好像
