### ISSUE TITLE
Snapshot 2.6.11 更新日志缺失

### ISSUE THREAD

**Issue by LTCatt** [Hex-Dragon/PCL2#2915]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/a6ac5184-a978-49f6-a794-dffe6de8b0af)

**Comment by kong-que-dnf123** [comment]
何止是缺日志啊
~我都没有显示Snap能更新到2.6.110啊（）~
![image](https://github.com/Hex-Dragon/PCL2/assets/120994373/3281a4dc-080f-4148-9fcc-0d4b846c3f7f)
![image](https://github.com/Hex-Dragon/PCL2/assets/120994373/48edd905-0644-4b09-9434-3d4f090e855d)

**Comment by JingHai-Lingyun** [comment]
我这边是可以的，你再试试看？

**Comment by kong-que-dnf123** [comment]
> 我这边是可以的，你再试试看？

把PCL重开了 有更新了（喜
![image](https://github.com/Hex-Dragon/PCL2/assets/120994373/ac0d1c0e-4e29-406f-b6c0-33d7a6493a61)
