### ISSUE TITLE
《多个》 加载帮助xaml文件失败：无法设置未知成员“PCL.MyListltem.PaddingRight”

### ISSUE THREAD

**Issue by kong-que-dnf123** [Hex-Dragon/PCL2#2917]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

版本：Snapshot 2.6.11（309.0）
![image](https://github.com/Hex-Dragon/PCL2/assets/120994373/525a7d80-f74f-4197-b97b-772c92721eb6)

没错这个问题又双叒出现了，甚至一次出现好几个 ~（太多了就不发图了哪些有问题看重现步骤2333）~

### 重现步骤

1、点击“设置”
2、点击“帮助”
目前复现出的问题有： **指南-整合包制作指南**   ； **MINECRAFT-安装光影**  ； **启动器-参与完善PCL帮助库**  ；  **个性化-自定义帮助界面**  ；  **个性化-整合包制作指南**

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13502215/Log1.txt)

**Comment by kong-que-dnf123** [comment]
~这帮助库估计以后更新一次龙猫就得重写一次了（悲~

**Comment by LTCatt** [comment]
额……新版本删除了 PaddingRight 属性，把所有这个属性删掉就行了
