### ISSUE TITLE
功能与个性化的综合建议

### ISSUE THREAD

**Issue by TatleCat** [Hex-Dragon/PCL2#2918]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

1, 新功能:
  在主页, 可保存多个皮肤预设, 拥有自己的皮肤库并更方便的选择与更换

2, 模组列表优化
  可选择是否显示模组备注 [模组文件名]
  添加回模组列表中的删除按钮
  可以选择仅看 启用/禁用 的模组
  更好的排序: 按安装顺序排列
  自动或手动标注哪些模组依赖哪些前置
  
  无所谓的功能: 显示该模组是否在客户端/服务端需装
  
3, 主页与个性化建议
  可同时存在多个主页预设. 如: "回声洞"+"你知道吗"
  启动器背景可选择映射桌面,兼容模糊效果. 预计需求: 额外的模糊效果,如亚克力等
  文本及内容白底可自定义颜色/透明度/添加模糊效果
  可在主页以合适角度预览皮肤模型,同时兼容披风而非仅头像
  预计需求: 额外的模糊效果, 如亚克力等
<img width="106" alt="屏幕截图 2023-11-30 154916" src="https://github.com/Hex-Dragon/PCL2/assets/128877938/d7d63e2d-ef03-4078-914a-f4e0b93f3f5e"><img width="105" alt="屏幕截图 2023-11-30 154804" src="https://github.com/Hex-Dragon/PCL2/assets/128877938/14772a68-512b-40b0-9c7a-da1635e72d3c">

4, 下载
  筛选加载器可选择是否不屏蔽其他模组
  如选择Fabric, 将优先显示此类, 其他模组标红 [或其他方式处理]
  增添 光影/材质/数据包 的下载与安装选项
    
5, 其他
  关闭启动器后自动清理日志等垃圾
  游戏窗口标题是否可以显示FPS或CPU/GPU/内存的占用?

### 原因

建议1: 新功能需求

建议2: 有时候,对模组的认识更偏向于自己的备注
           为了更方便删除,否则必须执行额外的步骤
           更方便查找与确认        更方便查找与确认
           
建议3: 功能优化需求+美化需求+可自定性小+腻了 [这会有人喷我吗...]

建议4: 功能优化需求.

建议5: 无所谓

**Comment by burningtnt** [comment]
0. 请关闭本 Issue，并拆分为多个独立的 Issue
1. 未找到重复 Issue，可以迁移到功能投票、
2. #683 #2700 但其中“可选择是否显示模组备注 [模组文件名]”、“自动或手动标注哪些模组依赖哪些前置”和“添加回模组列表中的删除按钮”暂无重复项
3. #2873 已被拒绝
4. “筛选加载器可选择是否不屏蔽其他模组”无重复项，但“光影/材质/数据包 的下载与安装选项”已有，于 #2768 #1095
5. 这个功能可不好做。需要根据 PID 拿窗口 HWND，再去动态的改。不如你直接安装某些带有相关功能的模组

**Comment by LTCatt** [comment]
游戏窗口标题是否可以显示FPS或CPU/GPU/内存的占用
添加回模组列表中的删除按钮

这两条单独重新开 issue，其他的都与已有重复或者不打算做 =。=

**Comment by burningtnt** [comment]
抱歉，我刚刚又搜索了一次，在 #343

**Comment by burningtnt** [comment]
啊？这个提交太快是 PCL2 为了防止重复提交的吗……

**Comment by burningtnt** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/88144530/b5fe74e6-cfbd-4818-812d-beb42c65e985)
你牛
