### ISSUE TITLE
游戏窗口标题是否可以显示FPS或CPU/GPU/内存的占用

### ISSUE THREAD

**Issue by burningtnt** [Hex-Dragon/PCL2#2919]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

#2918 游戏窗口标题是否可以显示FPS或CPU/GPU/内存的占用

### 原因

/

**Comment by burningtnt** [comment]
https://github.com/Hex-Dragon/PCL2/issues/2918#issuecomment-1833445236 龙猫已认可，请 Collaborator 更改标签

**Comment by WorldHim** [comment]
@TatleCat

**Comment by LTCatt** [comment]
考虑到社区讨论结果，该功能应该留给 mod 实现，PCL 实现的付出与收益不成正比，且投票票数也很少，暂不考虑制作该功能 :/
