### ISSUE TITLE
主页预设与更好的个性化背景

### ISSUE THREAD

**Issue by TatleCat** [Hex-Dragon/PCL2#2923]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

可同时存在多个主页预设. 如: "回声洞"+"你知道吗"

  仅修改启动器背景透明度,即以桌面为背景. 兼容模糊效果.
  文本及内容白底可自定义颜色/透明度/使用模糊效果
  例图:
<img width="1280" alt="屏幕截图 2023-11-30 165140" src="https://github.com/Hex-Dragon/PCL2/assets/128877938/c45a224c-3c17-450e-a501-240cbf41f7d2">

### 原因

外观建议,低优先级也没事＞︿＜

**Comment by JingHai-Lingyun** [comment]
> 可同时存在多个主页预设. 如: "回声洞"+"你知道吗"

如果你需要的话我可以给你发写好的本地文件

**Comment by TatleCat** [comment]
> > 可同时存在多个主页预设.如: "回声洞"+"你知道吗"
> 
> 如果你需要的话我可以给你发写好的本地文件
> 
> 另，再次提醒下，不要在一个 Issue 内提交多个提案。社区和开发者处理起来挺头大的

好, 谢谢ouo
