### ISSUE TITLE
可更新Fabric加载器及其API

### ISSUE THREAD

**Issue by TatleCat** [Hex-Dragon/PCL2#2925]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

可更新MC已有的Fabric加载器及其API版本

### 原因

‏​

**Comment by JingHai-Lingyun** [comment]
#220 请到 #227 投票

**Comment by JingHai-Lingyun** [comment]
给个提示，今晚上你交了好多反馈，但多数都重复/无效
或许你该阅读阅读 [反馈前的注意事项 —— PCL 社区文档](https://pcl-doc.rth1.app/guide.html)

**Comment by TatleCat** [comment]
> 给个提示，今晚上你交了好多反馈，但多数都重复/无效 或许你该阅读阅读 [反馈前的注意事项 —— PCL 社区文档](https://pcl-doc.rth1.app/guide.html)

awa

**Comment by hejiehao** [comment]
更新 Fabric API 有点像 #102
