### ISSUE TITLE
Microsoft Defender 报毒 PCL2 有 MSIL/CryptInject!MSR

### ISSUE THREAD

**Issue by RransZormers** [Hex-Dragon/PCL2#2928]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

<img width="845" alt="Snipaste_2023-12-01_16-30-42" src="https://github.com/Hex-Dragon/PCL2/assets/77564471/9bd7304a-38ac-498f-9fb1-94ed264306ec">
报毒如上图所示，目前还不确定具体原因，可能是误报，也可能是 bug 所致，目前我已切换其他 Minecraft 启动器

### 重现步骤

在软件启动时被 Windows Defender 提示含有病毒

### 日志与附件

由于 Log 文件中含有隐私信息，我会在稍后上传

**Comment by JingHai-Lingyun** [comment]
参考 #666
你可以尝试把 PCL 启动器放到除 C盘/桌面 的地方或添加排除项来避免这个问题

**Comment by LTCatt** [comment]
先检查你的启动器文件和官方下载的一不一样，如果不一样可能是被感染的病毒文件，如果一样就是误报
