### ISSUE TITLE
1.12.2forge14.23.5.2860无法启动游戏

### ISSUE THREAD

**Issue by Rakkaun** [Hex-Dragon/PCL2#2929]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃基本不是 PCL 的原因，请 **不要** 提交反馈。你可以在论坛或社区找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用 HMCL 启动，HMCL 没有出现问题。** 如果 HMCL 也无法启动就不是 PCL 导致的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在点击启动游戏后没有出现游戏窗口,直接提示minecraft出现错误，在1.20.1以及其他版本是正常启动，唯有1.12.2forge无论有无mod都无法启动

### PCL 错误报告、日志与附件

[错误报告-2023-12-1_21.33.58.zip](https://github.com/Hex-Dragon/PCL2/files/13527172/-2023-12-1_21.33.58.zip)

### HMCL 启动脚本

[txt.zip](https://github.com/Hex-Dragon/PCL2/files/13527196/txt.zip)

**Comment by burningtnt** [comment]
Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\Administrator\AppData\Roaming\PCL\libjlw-1.3.2.dll: Can't find dependent libraries
从启动器日志上来看，你的电脑是 ARM64 架构。我不清楚 PCL2 是否对 ARM64 架构做了适配

**Comment by LTCatt** [comment]
请在 #1108 上传日志
