### ISSUE TITLE
无法正常识别部分远古版本以及远古 ModLoader

### ISSUE THREAD

**Issue by SuoHouDaiShi** [Hex-Dragon/PCL2#2931]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

Mouse Tweaks 模组无法识别 b1.7.3-Risugami's ModLoader 版本的发行版，该版本是基于 Risugami's ModLoader 的 beta-1.7.3 的 Minecraft
![图片](https://github.com/Hex-Dragon/PCL2/assets/119282947/a2ad6778-6d32-4238-89a3-30752b5abd59)

### 重现步骤

1.点击下载
2.点击 "Mod"
3.搜索 Mouse Tweaks
4.进入详情，BUG 出现

### 日志与附件

![图片](https://github.com/Hex-Dragon/PCL2/assets/119282947/a2ad6778-6d32-4238-89a3-30752b5abd59)
<del>先不传日志了</del>
**需要日志请回复，看到了会传**

**Comment by LTCatt** [comment]
不需要日志（

**Comment by SuoHouDaiShi** [comment]
<del>这下不能是罕见情况了吧（</del>

**Comment by SuoHouDaiShi** [comment]
@LTCatt 那啥，换硬盘重装系统了，激活码重新给一下……
EB2B-8E65-9C86-BD6E

**Comment by LTCatt** [comment]
你的解锁码：8umgJtHMh2D7Hlife8BnaB/vHf5r/cep
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
