### ISSUE TITLE
（一定要看看呀！很简单的！很有意义的！）mod下载器搜索界面中添加一键下载按钮

### ISSUE THREAD

**Issue by GOhaochen** [Hex-Dragon/PCL2#2933]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [x] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

一些实例
1.在鼠标悬停mod图标上方时，显示一键下载按钮
![111111](https://github.com/Hex-Dragon/PCL2/assets/98160605/390ff270-d2f2-4f8f-a891-84ecb3275ae0)
2.（如果有）点击后自动下载主页中已选择版本的版本正式版mod
3.（如果没有）尝试下载测试版，如果仍然没有，显示弹窗，有几个选项-取消、打开下载页面 等
![222222](https://github.com/Hex-Dragon/PCL2/assets/98160605/891affa7-f4f5-4791-854b-6c1b0b1aefab)

### 原因

这个功能虽然存在感不是很高，但是能十分有效的缩短大量下载mod的时间，简化下载过程，提高玩家体验

**Comment by JingHai-Lingyun** [comment]
有点像之前见过的一个（等我找下帖子

**Comment by kong-que-dnf123** [comment]
> 有点像之前见过的一个（等我找下帖子

大多数都是关于**MOD收藏夹**的（被拒）
有一个是 #1645 但是那里因为有**收藏夹提案**而 _“重复”关闭_
而那里所给的**<重新提交单独的关于一键下载的issue>建议**好像原issue主至今没提交（）

**Comment by JingHai-Lingyun** [comment]
> 而那里所给的 <重新提交单独的关于一键下载的issue>建议 好像原issue主至今没提交（）
好了 有一键下载提议了（笑

**Comment by Pigeon0v0** [comment]
同楼上，这个功能会导致逻辑变得太傻瓜了，会降低玩家的研究动力

而且你还得想办法往 UI 里加按钮...

**Comment by LTCatt** [comment]
加载文件列表需要一个中转画面，这个不好做

**Comment by GOhaochen** [comment]
好的感谢评论的朋友和龙猫，我的考虑不周，打扰各位了！
