### ISSUE TITLE
在启动器主页主题预设中添加Bing壁纸

### ISSUE THREAD

**Issue by GOhaochen** [Hex-Dragon/PCL2#2937]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

较为简单，可以使用bing 壁纸api，每天更新，给用户带来新鲜感

### 原因

给用户带来新鲜感，美化主页

**Comment by burningtnt** [comment]
Bing 壁纸本身没有公开的 API，虽然有第三方的更新源（如 [TimothyYe/bing-wallpaper](https://github.com/TimothyYe/bing-wallpaper)），但这可能会侵犯到必应的版权
