### ISSUE TITLE
#2867的Bug解决后仍存在问题

### ISSUE THREAD

**Issue by LSGtorch** [Hex-Dragon/PCL2#2938]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

前两天我刚反馈了#2867 这个bug 
今天更新了pcl，再次尝试
点击清空背景
![image](https://github.com/Hex-Dragon/PCL2/assets/115522101/01caf56b-72e9-4828-b5d6-9e8e5b147c5e)
点击确定
![image](https://github.com/Hex-Dragon/PCL2/assets/115522101/9de7b1e5-e621-4b53-bbe5-d08ed0d6a2c4)

查看文件夹后发现
整个Picture文件夹消失了（）
所以就是找不到文件夹才报错了

重启pcl后picture文件夹再次出现
so 在清空背景图片之后在自动生成文件夹即可

### 重现步骤

清空背景图片
确定

### 日志与附件

部分日志：
[20:50:34.722] [Control] 按下按钮：清空背景图片
[20:50:34.736] [Control] 普通弹窗：警告
即将删除背景图片文件夹中的所有文件。
此操作不可撤销，是否确定？
[20:50:46.170] [Control] 按下按钮：确定
[20:50:46.171] [Control] 普通弹框返回：1
[20:50:46.402] 刷新背景图片时出现未知错误：未能找到路径“E:\OneDrive - gyf0814\纯净端\PCL\Pictures”的一部分。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileSystemEnumerableIterator`1.CommonInit()
   在 System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   在 System.IO.Directory.GetFiles(String path, String searchPattern)
   在 Microsoft.VisualBasic.FileIO.FileSystem.FindPaths(FileOrDirectory FileOrDirectory, String directory, String wildCard)
   在 Microsoft.VisualBasic.FileIO.FileSystem.FindFilesOrDirectories(FileOrDirectory FileOrDirectory, String directory, SearchOption searchType, String[] wildcards, Collection`1 Results)
   在 Microsoft.VisualBasic.FileIO.FileSystem.FindFilesOrDirectories(FileOrDirectory FileOrDirectory, String directory, SearchOption searchType, String[] wildcards)
   在 PCL.ModMain.BackgroundRefresh(Boolean IsHint, Boolean Refresh)
错误类型：System.IO.DirectoryNotFoundException
[20:50:46.419] [Animation] 两个动画帧间隔 235 ms
[20:50:46.483] [Control] 普通弹窗：出现错误
刷新背景图片时出现未知错误：未能找到路径“E:\OneDrive - gyf0814\纯净端\PCL\Pictures”的一部分。
   在 PCL.ModMain.BackgroundRefresh(Boolean IsHint, Boolean Refresh)
错误类型：System.IO.DirectoryNotFoundException

是否反馈此问题？如果不反馈，这个问题可能永远无法得到解决！
[20:52:18.211] [Control] 按下按钮：取消
[20:52:18.212] [Control] 普通弹框返回：2
[20:52:18.272] [UI] 弹出提示：背景图片已清空！

**Comment by LSGtorch** [comment]
龙猫是不是没测试就发了（）

**Comment by burningtnt** [comment]
哈哈哈 笑死了，龙猫怕不是把代码改成删除整个 Pictures 了（

**Comment by JingHai-Lingyun** [comment]
可能是的...

**Comment by kong-que-dnf123** [comment]
> ~龙猫估计是在清除的时候设置清除指定后缀名（比如.jpg .png之类的）~
>所以直接设置成清楚文件夹里 **所有** 东西就差不多了（）

~所以选择了更简便的直接清文件夹（）~
