### ISSUE TITLE
[优化] Mod 管理页面允许单击切换模组（启用/禁用）状态

### ISSUE THREAD

**Issue by SALTWOOD** [Hex-Dragon/PCL2#2939]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

以前还有的，现在更新之后 Mod 列表每行模组信息的左边变成了模组的图标，取代了原来的红石灯按钮，现在已无法通过点击切换模组状态。

### 原因

方便切换模组状态，不必傻傻地用多选模式选单个模组，然后启用禁用还要按不一样的按钮……
建议是把原先的单击切换加回来、加一排复选框或者加一个进入多选模式的按钮。

**Comment by JingHai-Lingyun** [comment]
给图标做个原来的按钮效果？

**Comment by SALTWOOD** [comment]
> 给图标做个原来的按钮效果？

就是想这么干，但是你也知道 PCL2 代码不全
~~PR 是不可能 PR 的，这辈子都不可能 PR 的~~

或者我的建议是直接把进入多选独立开来

**Comment by Anyplez** [comment]
也可以加一个类似“按住ctrl点击模组可快速激活”的功能

**Comment by JingHai-Lingyun** [comment]
现在按住 Ctrl 是多选

**Comment by allMagicNB** [comment]
不对啊，这？
