### ISSUE TITLE
[快照版 2.6.11] Fabric的Mod页面更新 带有前置mod 的 mod 的 前置mod 可能有bug

### ISSUE THREAD

**Issue by Ad-closeNN** [Hex-Dragon/PCL2#2941]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在内测版**v2.6.11**、Fabric中，尝试更新mod的前置出现崩溃
![Snipaste_2023-12-03_10-36-16](https://github.com/Hex-Dragon/PCL2/assets/103355026/e7387a18-7221-44bc-bfcb-7f195069c9a8)

### 重现步骤

1、点击版本设置
2、点击Mod管理
3、随便找个需要前置的mod，右键
4、点击**Mod下载页面**
5、选择MC版本
6、点击Mod的前置
7、触发报错

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13537929/Log1.txt)

**Comment by JingHai-Lingyun** [comment]
#2913
