### ISSUE TITLE
希望兼容MultiMC的mod安装格式

### ISSUE THREAD

**Issue by dls01011** [Hex-Dragon/PCL2#2943]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

希望兼容MultiMC的mod安装格式

### 原因

不想安装MultiMC但有些mod只有MultiMC支持希望pcl2能代替它

**Comment by Pigeon0v0** [comment]
#1853 ？

**Comment by JingHai-Lingyun** [comment]
模组 模组

**Comment by Pigeon0v0** [comment]
举个例子什么 Mod 只能 MultiMC 装

**Comment by hejiehao** [comment]
> 模组？你确定不是模组包 模组只要有对应的加载器（Forge，Fabric之类的）就可以加载吧，哪有什么 MultiMC 格式

不会说的是这个吧 https://www.curseforge.com/minecraft/mc-mods/prevent-crappy-launcher

**Comment by JingHai-Lingyun** [comment]
呃 这种情况下 PCL 不认（毕竟魔改

**Comment by dls01011** [comment]
但MultiMC支持希望pcl能集成一下这个功能，至少希望能识别文件夹
________________________________
发件人: 凌云 ***@***.***>
发送时间: 2023年12月4日 15:21
收件人: Hex-Dragon/PCL2 ***@***.***>
抄送: dls01011 ***@***.***>; Author ***@***.***>
主题: Re: [Hex-Dragon/PCL2] 希望兼容MultiMC的mod安装格式 (Issue #2943)


呃 这种情况下 PCL 不认（毕竟魔改

―

**Comment by dls01011** [comment]
[https://res.cdn.office.net/assets/mail/file-icon/png/generic_16x16.png]Cursed-Fabric-BTW-MultiMC.rar<https://1drv.ms/u/s!AtCP8ODBaCAxhR8d_zJab0vokrW2>

________________________________
发件人: 龙腾猫跃 ***@***.***>
发送时间: 2023年12月8日 17:56
收件人: Hex-Dragon/PCL2 ***@***.***>
抄送: dls01011 ***@***.***>; Author ***@***.***>
主题: Re: [Hex-Dragon/PCL2] 希望兼容MultiMC的mod安装格式 (Issue #2943)


既然版本识别不了，上传一下具体的样本？

―

**Comment by JingHai-Lingyun** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/109946426/ba3ff826-946a-4758-ba69-88534336ad99)
..

**Comment by hejiehao** [comment]
> ![image](https://private-user-images.githubusercontent.com/109946426/289235900-ba3ff826-946a-4758-ba69-88534336ad99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMTQ2ODQsIm5iZiI6MTcwMjExNDM4NCwicGF0aCI6Ii8xMDk5NDY0MjYvMjg5MjM1OTAwLWJhM2ZmODI2LTk0NmEtNDc1OC1iYTY5LTg4NTM0MzM2YWQ5OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwOVQwOTMzMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZjVkNTcwYjgwYzYwM2NhYzhmN2RhNzIzZDNmM2ZlNWU0NTQwZjU4NWNiMTM0MzMyN2I0N2Q3OTUzNmEwM2I2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8HDduJldw_qTyuRWJUtWFLQyX_rUZzTVL7HMWeo6XGY) 你这用邮件发了个什么上来..

似乎他发到是这个 https://1drv.ms/u/s!AtCP8ODBaCAxhR8d_zJab0vokrW2

**Comment by WorldHim** [comment]
[Cursed-Fabric-BTW-MultiMC.rar](https://1drv.ms/u/s!AtCP8ODBaCAxhR8d_zJab0vokrW2)

**Comment by JingHai-Lingyun** [comment]
看 MCMOD 感觉好冷门..
![image](https://github.com/Hex-Dragon/PCL2/assets/109946426/4bb75034-c45e-4e32-9d36-0d33a0a35020)

**Comment by LTCatt** [comment]
Fabric 1.5.2？

**Comment by JingHai-Lingyun** [comment]
> Fabric 1.5.2？

我看 Bilibili 上有人的视频，那个 GUI 和贴图看着就挺远古的
据 [BV1ZQ4y1x7Pg](https://www.bilibili.com/video/BV1ZQ4y1x7Pg/) 说是十多年前开发的，不知道为啥又有关注度了

**Comment by LTCatt** [comment]
我到时候再看看啥情况

**Comment by LTCatt** [comment]
看了看，这个整合包太特殊了，有点超出范围了，暂时不考虑支持……
