### ISSUE TITLE
删除PCL注册表项后识别码变更

### ISSUE THREAD

**Issue by MCSteve123** [Hex-Dragon/PCL2#2944]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如题
石墨文档中有这样一段话：
> 识别码是 PCL 根据**电脑硬件信息**生成的编号，每个人均不相同

但当将**注册表项**删除后，识别码就变更了（比如从`ABCDE-ABCDE-ABCDE-ABCDE`变成了`EDCBA-EDCBA-EDCBA-EDCBA`）
众所周知，注册表不是硬件，对吧

### 重现步骤

去把PCL注册表删了
（用正式版，快照版会死的很惨，所有隐藏主题全没，而且识别码变了，活跃橙和欧皇紫都不能用了……）

### 日志与附件

这没必要传日志吧（而且我也不敢试第二遍了）

**Comment by MCSteve123** [comment]
> PCL2 不会在第一次生成识别码的时候掺入了时间作为因子吧…… 后续只读取而不重新生成

所以我们需要lm给个答复，改识别码还是改文档

**Comment by MCSteve123** [comment]
> PCL2 不会在第一次生成识别码的时候掺入了时间作为因子吧…… 后续只读取而不重新生成

毕竟生成识别码那块没开源

**Comment by mc-124** [comment]
有可能是根据wmic csproduct get UUID的返回值与主板ID生成的

**Comment by MCSteve123** [comment]
等lm说话吧
这玩意谁也没办法
> PCL2的代码只有龙猫和上帝知道，可是龙猫忘记了。
> _——回声洞_

话说有没有大怨种去逝过这条反馈，毕竟这东西我再也不敢尝试第二遍了

**Comment by lactobionicAcid** [comment]
Identify这项似乎是PCL2第一次启动时随机产生的？🤔

**Comment by LTCatt** [comment]
删除注册表会导致丢失数据，这是预期中的
