### ISSUE TITLE
在下载界面搜索mod时，选择版本出现错误

### ISSUE THREAD

**Issue by mstower520** [Hex-Dragon/PCL2#2947]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在下载界面里的下载mod选项里选择对应的版本搜索模组点击进去下载时，他给我置顶的版本和我所选的版本不符。

![M0OCTX8YR8WVLQA_`3QS{(M](https://github.com/Hex-Dragon/PCL2/assets/75670483/9e59c80f-eea0-43f6-bd45-53972ee9805d)

![BB(`700WAOLECUQA4OA WSB](https://github.com/Hex-Dragon/PCL2/assets/75670483/c33d753b-26b2-429a-a8b0-91e3eb6ce638)

### 重现步骤

1、点击下载
2、点击mod
3、搜索mod并选择版本
4、点击想要的mod进去
5、发现bug所在

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13542570/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/13542573/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/13542574/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/13542575/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/13542576/Log5.txt)

**Comment by JingHai-Lingyun** [comment]
无法复现（使用相同 Mod & 版本选择器）...

**Comment by JingHai-Lingyun** [comment]
> 这个选定的版本是指你现在启动游戏选定的版本，Mod 搜索筛选只是筛选 Mod 有没有这个版本。。

呃？这玩意好像是选定筛选的版本吧
~~草~~ 想测试的时候咋怎么都不展示目标版本了...

**Comment by mstower520** [comment]
> 这个选定的版本是指你现在启动游戏选定的版本，Mod 搜索筛选只是筛选 Mod 有没有这个版本。。

但是我游戏版本选的也是1.20.1，就很奇怪，我也想过是这个原因，还特地多切换了几次版本，还是这样，就第一次选了1.18.2后就固定在1.18.2了

**Comment by JingHai-Lingyun** [comment]
目前的现象就是推荐固定为第一次搜索的时候所用的版本和ModLoader...
