### ISSUE TITLE
更多-帮助-指南内的“整合包制作指南”无法打开

### ISSUE THREAD

**Issue by Zhang12334** [Hex-Dragon/PCL2#2949]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

整合包制作指南无法打开，显示出现错误
![6e3e0757492118ada492ad60c06696dd](https://github.com/Hex-Dragon/PCL2/assets/105694975/36560a23-d229-45fc-bf48-1fa1849cd3fd)

### 重现步骤

1、打开PCL2
2、点击更多
3.点击指南内的“整合包制作指南”
4.炸！

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13555372/Log1.txt)

只有LOG1，确定bug复现后关闭pcl上传的（因为第三方登陆服务器涉及服务器内部网站所以登陆部分删了下和bug无关内容 tks

**Comment by JingHai-Lingyun** [comment]
已经于 #2917 修复，请等待下次更新
