### ISSUE TITLE
mod管理支持按标签搜索

### ISSUE THREAD

**Issue by xiaoyuanjun233** [Hex-Dragon/PCL2#2953]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

![QQ图片20231206011649](https://github.com/Hex-Dragon/PCL2/assets/125738947/9417f5fe-93bd-4911-8209-14cf81da2282)
l例如根据模组上的标签筛选

### 原因

若加入这个功能我可以很清晰的知道我的整合包各个模组类型的数量

**Comment by LTCatt** [comment]
可以让搜索允许搜索标签上的文字，但筛选应该不会做 =。=
