### ISSUE TITLE
快照版2.6.11无法根据选择的版本准确推荐mod

### ISSUE THREAD

**Issue by wjsw3369** [Hex-Dragon/PCL2#2954]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在下载页面搜索mod时无法准确的推荐选择的版本，比如从1.20.1的存档切换了一个1.20.3的存档，去搜索mod，不论怎么筛选，点开的都是1.20.1的，关闭后再打开就是1.20.3的，但再换成1.20.1的存档筛选1.20.1的mod，点开搜索的还是推荐1.20.3的，最后的现在无论怎么筛选还是选择版本现在不显示推荐了，重新打开后再搜索又显示了，

### 重现步骤

1、主页选择一个游戏存档版本"如1.20.1"
2、前往下载页去搜索mod，搜1.20.1的mod，点开mod正常显示"所选版本：1.20 .1 Fabric"
3、在主页选择另一个游戏存档版本"如1.20.3"
4、前往下载页去搜索mod，搜1.20.3的mod，点开mod仍然显示"所选版本：1.20 .1 Fabric"

最后那个不显示所选版本不确定如何具体复刻方式，

所有版本好像都是，我试过的几个版本都是，都需要重启启动器才能换成正常搜索选的的版本的

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13578198/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/13578199/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/13578200/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/13578195/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/13578197/Log5.txt)

**Comment by JingHai-Lingyun** [comment]
欸？看起来和 #2947 很像
我也发现了有推荐版本和搜索版本不匹配的现象，甚至有时候不给推荐了（雾

**Comment by wjsw3369** [comment]
哦是的，#2947被关闭了我没有看到，可以参考下我这个尝试复刻，我这大概率都是这样的
