### ISSUE TITLE
显示模组内置的图片

### ISSUE THREAD

**Issue by wjsw3369** [Hex-Dragon/PCL2#2955]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

最新的快照版2.6.11在mod管理中可以显示mod的图片，但有些不能显示，一般mod都有内置的图片，希望可以直接显示mod内置的图片，也就不用联网搜索了

### 原因

如自制mod和部分地区在锻造平台上的mod，都不会显示图片，而模组基本都内置的有图片，就可以不联网就能显示图片更好区分

**Comment by wjsw3369** [comment]
自制mod现在也不会显示，我是指通过显示模组内置的图片，这样基本上都能显示，

**Comment by LTCatt** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/ec05b343-a754-4558-96d2-56af1e26dc3d)
Mod 的内置 Logo 不是方形的
