### ISSUE TITLE
在mod管理中选择mod进行删除操作时出现应用程序未响应的情况

### ISSUE THREAD

**Issue by DWYhhh** [Hex-Dragon/PCL2#2956]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在mod管理中选择mod进行删除操作时出现应用程序未响应的情况
![20231206_181958 00-00-10 20231206-183022266](https://github.com/Hex-Dragon/PCL2/assets/127036944/c7670a90-22f7-4a8c-8a9c-146ca23ff91e)
![20231206_181958 00-00-15 20231206-183035770](https://github.com/Hex-Dragon/PCL2/assets/127036944/2202c807-fc35-4ee7-b701-49cad149b48f)
![20231206_181958 00-00-18 20231206-183053347](https://github.com/Hex-Dragon/PCL2/assets/127036944/58a77907-ede8-4ba8-b56e-500911c34ee1)
![20231206_181958 00-00-20 20231206-183040887](https://github.com/Hex-Dragon/PCL2/assets/127036944/3f9d620a-5b38-450f-98fb-a66a118523b7)
![20231206_181958 00-00-20 20231206-183055448](https://github.com/Hex-Dragon/PCL2/assets/127036944/a231a899-607c-4101-abc6-c6e37ee42a7b)
[20231206_181958.zip](https://github.com/Hex-Dragon/PCL2/files/13580303/20231206_181958.zip)

### 重现步骤

1、点击版本设置
2、然后点击mod管理
3、选中mod
4、点击删除

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13579959/Log1.txt)

**Comment by JingHai-Lingyun** [comment]
Log2（~5）传一下，这 Log1 里头啥信息没有

**Comment by DWYhhh** [comment]
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/13580727/Log5.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/13580728/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/13580731/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/13580732/Log4.txt)

**Comment by DWYhhh** [comment]
源
Plain Craft Launcher 2 启动器

摘要
Stopped responding and was closed

日期
‎2023/‎12/‎6 18:15

状态
未报告

描述
A problem caused this program to stop interacting with Windows.
错误的应用程序路径:	D:\Program Files\Release 2.1.4\Plain Craft Launcher 2.exe

问题签名
问题事件名称:	AppHangB1
Application Name:	Plain Craft Launcher 2.exe
Application Version:	2.6.11.0
Application Timestamp:	656375fc
Hang Signature:	8ee3
Hang Type:	134217728
OS 版本:	10.0.22631.2.0.0.768.99
区域设置 ID:	2052
Additional Hang Signature 1:	8ee333cdcac8e5ab4edc1fa4f934ed6a
Additional Hang Signature 2:	535c
Additional Hang Signature 3:	535ca444e893114a48975f4e132796be
Additional Hang Signature 4:	8ee3
Additional Hang Signature 5:	8ee333cdcac8e5ab4edc1fa4f934ed6a
Additional Hang Signature 6:	535c
Additional Hang Signature 7:	535ca444e893114a48975f4e132796be

**Comment by JingHai-Lingyun** [comment]
我看日志到最后按下 `带图标的按钮：删除` 就没了...
貌似不太好分析咋回事..

**Comment by DWYhhh** [comment]
有一种可能是使用了一些美化软件，修改了文件资源管理器的配置，导致执行删除操作时出问题。之前有些时候通过应用内的打开xx文件夹按钮，打开文件资源管理器也有概率出现文件资源管理器未响应的现象。

https://winmoes.com/tools/12948.html
有可能是这个软件造成的问题

**Comment by burningtnt** [comment]
既然你是当事人，那不如你亲自把那个工具卸载，再试一次。
以及，龙猫你最好改一改，否则万一资源管理器一崩，PCL2 也得连着崩

**Comment by WForst-Breeze** [comment]
停用美化软件后再试

**Comment by DWYhhh** [comment]
刚才试了，回复正常了。

**Comment by DWYhhh** [comment]
刚才试了，回复正常了。

**Comment by burningtnt** [comment]
最好改一改，把 IO 操作移动到单独的线程，否则万一资源管理器一崩，PCL2 也得连着崩

**Comment by JingHai-Lingyun** [comment]
理论上第三方插件等引起的异常 PCL 不修..

**Comment by WForst-Breeze** [comment]
看看龙猫怎么说

**Comment by LTCatt** [comment]
第三方问题不修（
