### ISSUE TITLE
下载整合包时“分析Mod加载器支持库文件”卡住

### ISSUE THREAD

**Issue by YocyCraft** [Hex-Dragon/PCL2#2959]
### 检查项

- [ ] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

下载整合包的时候进度在图上这里卡住不动了，试了挂梯子和不挂梯子都出现这个问题，而且都是卡在同样的进度节点上。
![`AJSYMO9}V%8EHP95232T9B](https://github.com/Hex-Dragon/PCL2/assets/80801884/86a9603b-647f-4e9a-84c7-ee544577fcd7)

### 重现步骤

1、下载整合包All the mods 9

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13611722/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/13611724/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/13611725/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/13611726/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/13611727/Log5.txt)

**Comment by JingHai-Lingyun** [comment]
Log1 Ln 15395~15439
看到大量超时（`错误类型：System.TimeoutException`）
这是由于网络问题导致的，请自行优化网络或使用加速器等方式

**Comment by LTCatt** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/e1103732-dcb7-4f42-b277-e48461101828)
看了看， 是文件下载卡了，这个没法
