### ISSUE TITLE
无法下载1.20.3-1.20.4版本的Forge

### ISSUE THREAD

**Issue by WangSimele** [Hex-Dragon/PCL2#2960]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

改了下issue，1.20.3-1.20.4版本的Forge均无法下载

### 重现步骤

复现log1：在启动器内下载-选择下载1.20.3Forge 49.0.1+的任意版本的Forge
复现log2：在启动器内下载-选择下:1.20.4 Forge 49.0.4+的任意版本的Forge

### 日志与附件
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13625178/Log1.txt)(下载1.20.3Forge 49.0.1+时所弹出的报错log）
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/13683968/Log2.txt)（下载1.20.4Forge 49.0.4+时所弹出的报错log）

**Comment by JingHai-Lingyun** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/109946426/e324c4df-52b1-4d81-b218-539b33a53124)
成功复现
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13622808/Log1.txt)
另：无法使用 HMCL 测试，那边加载不出来 Forge 安装选项（提示没有可用的版本）

**Comment by hejiehao** [comment]
> ![image](https://github.com/Hex-Dragon/PCL2/assets/109946426/e324c4df-52b1-4d81-b218-539b33a53124)
> 成功复现
> [Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13622808/Log1.txt)
> 另：无法使用 HMCL 测试，那边加载不出来 Forge 安装选项（提示没有可用的版本）
> 

你可能需要手动下载 Forge
可能是因为镜像源未同步

**Comment by JingHai-Lingyun** [comment]
> 可能是因为镜像源未同步

OK 切到官方源就有了，HMCL安装成功

**Comment by WangSimele** [comment]
> > 可能是因为镜像源未同步
> 
> OK 切到官方源就有了，HMCL安装成功

我刚才去改了下issue，因为这并不是只有1.20.4版本的Forge无法安装，而是1.20.3-1.20.4的Forge都无法安装，并且报错原因一样

**Comment by lingyunawa** [comment]
我的妈耶这 Title 咋长成这个样子了

**Comment by WangSimele** [comment]
> 我的妈耶这 Title 咋长成这个样子了

新改的，因为问题复现的内容不一样，一个是404，一个是使用Forge安装器出错......

**Comment by WangSimele** [comment]
@LTCatt 那我现在能不能领取活跃橙主题？

**Comment by JingHai-Lingyun** [comment]
> LTCatt 那我现在能不能领取一下活跃橙？

可以，请发你的 PCL 识别码

**Comment by WangSimele** [comment]
> > LTCatt 那我现在能不能领取一下活跃橙？
> 
> 可以，请发你的 PCL 识别码

识别码是9D31-2A30-DEB2-5F38

**Comment by WangSimele** [comment]
@LTCatt

**Comment by LTCatt** [comment]
你的解锁码：9lMVozyOPKq1hYs1jeNkpYGVSWt0uoWN
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by WangSimele** [comment]
> 你的解锁码：9lMVozyOPKq1hYs1jeNkpYGVSWt0uoWN 在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持~

你好，由于我的一次重装系统而又没有备份，导致丢失了所有主题，需要重新解锁，请问能否再给一个解锁码？谢谢！
我的识别码:F9DF-4360-4BE3-2141
@LTCatt

**Comment by LTCatt** [comment]
识别码 F9DF-4360-4BE3-2141 的土豆码是：【CD11nAQm0mlTnTPUQBk%kOfr/kgljfSktl+0ux+auX+VHqtQePovPJ6eBTugNA5KoYGj5SGQZjPl5RTuCQONmiE0jwpp#VGhlbWU5】
在【更多 → 关于与鸣谢 → 输入土豆码】中使用，谢谢支持～
