### ISSUE TITLE
mod管理页查看mod后保持进度

### ISSUE THREAD

**Issue by FQO3** [Hex-Dragon/PCL2#2961]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在版本设置的mod管理页面，右键某个mod进入详情页面（mod下载页面）并退出后，希望可以保持浏览进度，不要每次都翻到顶部，还要重新滑下来。

### 原因

当我们在逐一检查mod前置时需要依次点开mod的下载页来查看前置是否已经装载。但每次退出后都要重新滑下来，很烦人……
而且mod一多就眼晕，要么就得再搜索，希望可以予以改进。

**Comment by youzi-2333** [comment]
印象里好像有人反馈过，但是搜不到重复 issue……

先待处理再说.jpg
