### ISSUE TITLE
MFn233主页在“预设主页”中打开失败

### ISSUE THREAD

**Issue by MCSteve123** [Hex-Dragon/PCL2#2963]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如题
如果手动输入[GitHub仓库中提供的网址](https://cdn.jsdelivr.net/gh/MFn233/PCL-Mainpage@latest/Custom.xaml)的话是没问题的，但是预设主页下拉框选择就崩。（似乎是换了下载源）
---
![image](https://github.com/Hex-Dragon/PCL2/assets/121204926/4da5129b-69cd-4d53-831c-210dbff747dc)

### 重现步骤

1、点击设置
2、点击个性化
3、在“预设主页”中选择“简单主页”
4、返回主页，寄！

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13623321/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/13623322/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/13623323/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/13623324/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/13623326/Log5.txt)

**Comment by MCSteve123** [comment]
确定了，GitHub下载源和这里的界面不一样……

**Comment by MCSteve123** [comment]
@MFn233 你是不是换下载源了

**Comment by JingHai-Lingyun** [comment]
这个 CDN 好像是 @MFn233 朋友的..

**Comment by JingHai-Lingyun** [comment]
欸 不对啊 我这里还正常啊
![image](https://github.com/Hex-Dragon/PCL2/assets/109946426/184c47dd-316d-4c3a-bad5-dff6229cd6b8)

**Comment by MCSteve123** [comment]
网络没问题，现在问题更严重了：用新下载源时，浏览器能下载，PCL又不行了（用了联网更新）……
![image](https://github.com/Hex-Dragon/PCL2/assets/121204926/eec7d6b4-a867-49f7-af7a-3d271f68fedf)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13623544/Log1.txt)

**Comment by MCSteve123** [comment]
一个两边都没有，现在又成PCL问题了

**Comment by WorldHim** [comment]
> 一个两边都没有，现在又成PCL问题了
> （wearclub关了，jsdelivr崩了？）

试试 `fastly.jsdelivr.net`

**Comment by MCSteve123** [comment]
有人复现吗

**Comment by MCSteve123** [comment]
> > 一个两边都没有，现在又成PCL问题了
> > （wearclub关了，jsdelivr崩了？）
> 
> 试试 `fastly.jsdelivr.net`

不行，PCL还炸
浏览器表示正常

**Comment by MCSteve123** [comment]
> 一个两边都没有，现在又成PCL问题了 （wearclub关了，jsdelivr崩了？）

wearclub浏览器和PCL瞬间崩掉，直接网络错误，估计是换链接了

**Comment by WorldHim** [comment]
> 有人复现吗

其实你应该提交到作者那里去

**Comment by MCSteve123** [comment]
> > 有人复现吗
> 
> 其实你应该提交到作者那里去

问题是浏览器打得开……只有PCL不行……

**Comment by MCSteve123** [comment]
# bug情况一览
## 他人复现
无
## 本人复现
|平台|wearclub|jsdelivr|
|---|---|---|
|浏览器|显示网络错误，推测已更换链接|可以使用|
|PCL|显示无法连接，推测已更换链接|可以使用|

注：PCL本来jsdelivr不能用，现在又神奇地好了……

---
请各位帮助修改

**Comment by JingHai-Lingyun** [comment]
我：浏览器/PCL W/J 均正常

**Comment by MCSteve123** [comment]
> 我：浏览器/PCL W/J 均正常

就离了个大谱……不过无论如何应该改一下链接

**Comment by JingHai-Lingyun** [comment]
或许该让 @MFn233 和龙猫 ~~(先不@)~~ 看看？

**Comment by MCSteve123** [comment]
MFn很久上线的，学业忙

**Comment by WorldHim** [comment]
实测用预设没有问题

**Comment by WorldHim** [comment]
> > 我：浏览器/PCL W/J 均正常
> 
> 就离了个大谱……不过无论如何应该改一下链接

jsdelivr 墙内表现并不是很好，因地区和运营商差异较大

**Comment by kong-que-dnf123** [comment]
请问现在是否还是打不开
~不排除意外的可能性了只能（）~

**Comment by MFn233** [comment]
大家好，作者本人也复现了这个问题：）

目前只能先联系sipc.ink，让他修复cdn问题，

如果想要正常使用的话，去我的仓库里下载并离线使用吧。。

**Comment by MFn233** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/103323756/9d19f57d-1bc9-436b-bc3b-31008b9ec3fe)
![image](https://github.com/Hex-Dragon/PCL2/assets/103323756/973d03cc-88e7-421f-bc4f-a3fa775f0266)
已证实大概率和PCL2自身有关。。。

**Comment by SIPC** [comment]
看了一下,可能是你这边开了VPN
然后我这边cdn开了地区限制
(现在关掉了)

**Comment by JingHai-Lingyun** [comment]
@MCSteve123 确认下是否可以再次复现该问题

**Comment by MCSteve123** [comment]
> @MCSteve123 确认下是否可以再次复现该问题

仍存在，双端均无法打开

**Comment by kong-que-dnf123** [comment]
>如果手动输入[GitHub仓库中提供的网址](https://cdn.jsdelivr.net/gh/MFn233/PCL-Mainpage@latest/Custom.xaml)的话是没问题的
-----------------------------------------------------------------------------------------------------------------------------
我现在这里是什么情况呢，你在初始问题里提供的https://cdn.jsdelivr.net/gh/MFn233/PCL-Mainpage@latest/Custom.xaml网站我在STEAM++没开的时候如图所示
![image](https://github.com/Hex-Dragon/PCL2/assets/120994373/9610d10f-ea75-43d1-b89d-ef9d3503194b)
反而开启加速（我加速了“国外验证码平台”和“GITHUB”的所有东西）就能正常下载了............
说明提供的网址是从github读取出来的？

**Comment by SIPC** [comment]
> > @MCSteve123 确认下是否可以再次复现该问题
> 
> 仍存在： wearclub双端无法打开（主页预设） cdn.jsdelivr浏览器正常，PCL接收0B报错（GitHub链接） fastly.jsdelivr双端正常（@WorldHim 提供的加速版本）

那大概率是本地问题了吧

**Comment by SIPC** [comment]
看了一下, cdn貌似被江苏移动劫持了
![image](https://github.com/Hex-Dragon/PCL2/assets/92251518/a950aa35-9c91-4f74-bcbc-e4dfba1044c1)

**Comment by SIPC** [comment]
挺怪的，https被劫持了 http可以正常访问
(被江苏反诈拦了)

**Comment by MCSteve123** [comment]
> 看了一下, cdn貌似被江苏移动劫持了 ![image](https://private-user-images.githubusercontent.com/92251518/289340464-a950aa35-9c91-4f74-bcbc-e4dfba1044c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxODg4MTMsIm5iZiI6MTcwMjE4ODUxMywicGF0aCI6Ii85MjI1MTUxOC8yODkzNDA0NjQtYTk1MGFhMzUtOWM5MS00Zjc0LWJjYmMtZTRkZmJhMTA0NGMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDA2MDgzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkNDIxMWYyMDBlMGNlMWU5ZDM0NGRmODk4Yzk2Nzk3ZDc3ZDQzODcwYzBhMDhiYzkyNDY2MDc1NjU5NzIxN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cnzLYgaHU4NbQo-Yn9ZYZ7cpb9ImBvTsT1uZYyZEIPs)

浙江嘉兴移动下载正常……

**Comment by MCSteve123** [comment]
现在这个BUG已经进入混沌领域……
（我只有周末在线，其他时间找不到的）

**Comment by WorldHim** [comment]
> >如果手动输入[GitHub仓库中提供的网址](https://cdn.jsdelivr.net/gh/MFn233/PCL-Mainpage@latest/Custom.xaml)的话是没问题的
> -----------------------------------------------------------------------------------------------------------------------------
> 我现在这里是什么情况呢，你在初始问题里提供的https://cdn.jsdelivr.net/gh/MFn233/PCL-Mainpage@latest/Custom.xaml  网站我在 **STEAM++** 没开的时候如图所示
> ![image](https://github.com/Hex-Dragon/PCL2/assets/120994373/9610d10f-ea75-43d1-b89d-ef9d3503194b)
> 反而开启加速（我加速了“国外验证码平台”和“GITHUB”的所有东西）就能正常下载了............
> 说明提供的网址是从github读取出来的？

我记得 watt toolkit 是有加速
jsdelivr 的

**Comment by JingHai-Lingyun** [comment]
> 说明提供的网址是从github读取出来的？

jsdelivr 的 /gh/... 就是去 Github 取文件加速

**Comment by MFn233** [comment]
我决定去discussion里面说。。。顺便艾特龙猫过来解决

**Comment by LTCatt** [comment]
根据 #2974 ，我下个版本把链接换成 https://gitee.com/mfn233/PCL-Mainpage/raw/main/Custom.xaml 吧……
如果 Gitee 能稳定代理的话，之后其他主页其实都可以迁移过去？

**Comment by IKUN05648** [comment]
刚刚我试还不行，现在可以了
![屏幕截图 2023-12-12 032743](https://github.com/Hex-Dragon/PCL2/assets/130807276/191aa59b-f031-47d2-bcc2-435d69fa5f7d)
![屏幕截图 2023-12-12 032803](https://github.com/Hex-Dragon/PCL2/assets/130807276/8f857556-e5c1-43ca-9ad5-d995bb90d760)

**Comment by JingHai-Lingyun** [comment]
> 如果 Gitee 能稳定代理的话，之后其他主页其实都可以迁移过去？

Gitee 最大的麻烦就是请求多了可能会封仓库开源权限
