### ISSUE TITLE
更改禁用mod的贴图

### ISSUE THREAD

**Issue by FQO3** [Hex-Dragon/PCL2#2965]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

更改禁用模组的贴图，或者将禁用的模组标红或黑白。
由于现在可以获取mod的

### 原因

（示例）
这项优化让我可以更方便地xxxx。
如果没有这项优化，我每次都必须xxxx，让操作变得很麻烦。

**Comment by FQO3** [comment]
不好意思，不小心按回车了

**Comment by JingHai-Lingyun** [comment]
？

**Comment by burningtnt** [comment]
请你手动点 "Reopen"

**Comment by hejiehao** [comment]
nb

**Comment by JingHai-Lingyun** [comment]
好好好
后续讨论请移步 #2966
