### ISSUE TITLE
想办法让禁用mod更显眼

### ISSUE THREAD

**Issue by FQO3** [Hex-Dragon/PCL2#2966]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

更改禁mod组的贴图，或者将禁用的mod名称标红或图标改为黑白。
由于现在可以获取mod的贴图，部分模组贴图比较混乱，例如：
![image](https://github.com/Hex-Dragon/PCL2/assets/111474347/4b927881-bc5f-4b17-85e4-01f71e7b979d)

如果禁用mod只在它的右下角加一个小图标不易辨认
建议将其更改为：
![image](https://github.com/Hex-Dragon/PCL2/assets/111474347/28b0224b-035b-48f2-8787-033f471dfa72)

### 原因

这个优化可以让mod冲突玩家更好的寻找和禁用mod，在禁用错mod时更好的找到被禁用的mod。
要不真的很费眼……

**Comment by WorldHim** [comment]
只有我觉得在模组名后面加个 `[禁用]` 很丑吗😕
感觉还是把 禁用 单独用和模组英文名字、版本号一样的格式列出好一点

**Comment by JingHai-Lingyun** [comment]
感觉还好吧。。。

**Comment by LTCatt** [comment]
我想个其他办法吧……

**Comment by Anyplez** [comment]
新版页面什么都好，就是禁用的标志远不如以前明显

**Comment by xiaoniaoawa** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/112697401/5a56d099-9000-436a-9ba9-1a1f2465626e)

试试这样？

**Comment by JingHai-Lingyun** [comment]
> 试试这样？

~~断点啊断点（恼~~
