### ISSUE TITLE
从网站获取本地Mod信息失败：已添加了具有相同键的项

### ISSUE THREAD

**Issue by ZmdNotFound** [Hex-Dragon/PCL2#2967]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

当我打开任意版本的Mod管理时，Mod图标不能被正确显示。
在调试模式下，同时会显示两条信息：
```
[调试模式]从Modrinth获取本地Mod信息失败：已添加了具有相同键的项。
[调试模式]从CurseForge获取本地Mod信息失败：已添加了具有相同键的项。
```
![Bug截图](https://github.com/Hex-Dragon/PCL2/assets/103509379/b6234abc-c5c8-4eda-b77b-5c966463903a)
系统防火墙 __处于关闭状态__。
同时尝试了给予PCL管理员权限以及使用科学上网均无果。
__P.S. 由于我手头只有这一台电脑，不排除设备差异及网络原因，望谅解。__

### 重现步骤

1. 打开启动器（调试模式）
2. 选择任意一个安装了一些Mod的版本
3. 打开版本设置 -> Mod管理
4. 稍候出现提示

### 日志与附件

见下
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13624260/Log1.txt)

**Comment by JingHai-Lingyun** [comment]
Log1 Ln 113
```
[21:28:16.432] 从 Modrinth 获取本地 Mod 信息失败：已添加了具有相同键的项。
   在 System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   在 System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   在 PCL.ModMod._Closure$__6-0._Lambda$__0()
错误类型：System.ArgumentException
[21:28:30.887] [Mod] 从 CurseForge 获取到 50 个本地 Mod 的对应信息
[21:28:30.888] 从 CurseForge 获取本地 Mod 信息失败：已添加了具有相同键的项。
   在 System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   在 System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   在 PCL.ModMod._Closure$__6-0._Lambda$__2()
错误类型：System.ArgumentException
```

**Comment by JingHai-Lingyun** [comment]
Log1 Ln 113
```
[21:28:16.432] 从 Modrinth 获取本地 Mod 信息失败：已添加了具有相同键的项。
   在 System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   在 System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   在 PCL.ModMod._Closure$__6-0._Lambda$__0()
错误类型：System.ArgumentException
[21:28:30.887] [Mod] 从 CurseForge 获取到 50 个本地 Mod 的对应信息
[21:28:30.888] 从 CurseForge 获取本地 Mod 信息失败：已添加了具有相同键的项。
   在 System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   在 System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   在 PCL.ModMod._Closure$__6-0._Lambda$__2()
错误类型：System.ArgumentException
```

**Comment by FQO3** [comment]
我的好像只提示了一次欸？
`[23:13:05.983] [Mod] 从 CurseForge 获取到 33 个本地 Mod 的对应信息
[23:13:05.998] 从 CurseForge 获取本地 Mod 信息失败：已添加了具有相同键的项。
   在 System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   在 System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   在 PCL.ModMod._Closure$__6-0._Lambda$__2()
错误类型：System.ArgumentException
[23:13:06.069] [Report] FPS 64, 动画 20, 下载中 0（0 B/s）`

**Comment by JingHai-Lingyun** [comment]
> 我的好像只提示了一次欸？
注意，两次提示不同源（提供的日志中一次 MR 一次 CF）

**Comment by LTCatt** [comment]
实质上好像是 #2916
