### ISSUE TITLE
切换版本再搜索后所选版本与页面版本不一致

### ISSUE THREAD

**Issue by ZLXL1234** [Hex-Dragon/PCL2#2968]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

mod详细页面显示的所选版本与搜索框选择的搜索版本不一致

### 重现步骤

1、搜索mod中选择任意版本
2、任意点进去一个mod并下载
3、返回到mod界面
4、更换版本
5、任意点进去一个mod，显示所选版本为第一步所选的

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13624286/Log1.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/13624290/Log3.txt)

**Comment by ZLXL1234** [comment]
![23-12-09_22-01-53](https://github.com/Hex-Dragon/PCL2/assets/149988734/d06e2794-c5d0-4fee-98e8-cfc3ae67c088)

**Comment by ZLXL1234** [comment]
> ![23-12-09_22-01-53](https://private-user-images.githubusercontent.com/149988734/289275960-d06e2794-c5d0-4fee-98e8-cfc3ae67c088.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMzA4NjMsIm5iZiI6MTcwMjEzMDU2MywicGF0aCI6Ii8xNDk5ODg3MzQvMjg5Mjc1OTYwLWQwNmUyNzk0LWM1ZDAtNGZlZS05OGU4LWNmYzNhZTY3YzA4OC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwOVQxNDAyNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTBhY2U3M2M1OTJjOTA2ZTc5NzM0NjRjZDlmMjNkMGI5OTUwYWM2MGM3OWIzMzFiZGVmNTAwOTRiMTkzNTVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.saPbN0S5gPe5PagG6Tvy5vHPLYdQ_pBAyiwV0Z40BtI) [ ![23-12-09_22-01-53](https://private-user-images.githubusercontent.com/149988734/289275960-d06e2794-c5d0-4fee-98e8-cfc3ae67c088.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMzA4NjMsIm5iZiI6MTcwMjEzMDU2MywicGF0aCI6Ii8xNDk5ODg3MzQvMjg5Mjc1OTYwLWQwNmUyNzk0LWM1ZDAtNGZlZS05OGU4LWNmYzNhZTY3YzA4OC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwOVQxNDAyNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTBhY2U3M2M1OTJjOTA2ZTc5NzM0NjRjZDlmMjNkMGI5OTUwYWM2MGM3OWIzMzFiZGVmNTAwOTRiMTkzNTVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.saPbN0S5gPe5PagG6Tvy5vHPLYdQ_pBAyiwV0Z40BtI) ](https://private-user-images.githubusercontent.com/149988734/289275960-d06e2794-c5d0-4fee-98e8-cfc3ae67c088.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMzA4NjMsIm5iZiI6MTcwMjEzMDU2MywicGF0aCI6Ii8xNDk5ODg3MzQvMjg5Mjc1OTYwLWQwNmUyNzk0LWM1ZDAtNGZlZS05OGU4LWNmYzNhZTY3YzA4OC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwOVQxNDAyNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTBhY2U3M2M1OTJjOTA2ZTc5NzM0NjRjZDlmMjNkMGI5OTUwYWM2MGM3OWIzMzFiZGVmNTAwOTRiMTkzNTVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.saPbN0S5gPe5PagG6Tvy5vHPLYdQ_pBAyiwV0Z40BtI) [ ](https://private-user-images.githubusercontent.com/149988734/289275960-d06e2794-c5d0-4fee-98e8-cfc3ae67c088.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMzA4NjMsIm5iZiI6MTcwMjEzMDU2MywicGF0aCI6Ii8xNDk5ODg3MzQvMjg5Mjc1OTYwLWQwNmUyNzk0LWM1ZDAtNGZlZS05OGU4LWNmYzNhZTY3YzA4OC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwOVQxNDAyNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTBhY2U3M2M1OTJjOTA2ZTc5NzM0NjRjZDlmMjNkMGI5OTUwYWM2MGM3OWIzMzFiZGVmNTAwOTRiMTkzNTVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.saPbN0S5gPe5PagG6Tvy5vHPLYdQ_pBAyiwV0Z40BtI)

**Comment by JingHai-Lingyun** [comment]
#2947

**Comment by ZLXL1234** [comment]
但是点击侧面按钮刷新后有时可以恢复，有时不行

**Comment by ZLXL1234** [comment]
应该不是有时，是高向低可以，低向高不行

**Comment by ZLXL1234** [comment]
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13624353/Log1.txt)

**Comment by ZLXL1234** [comment]
> #2947

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13624353/Log1.txt)
