### ISSUE TITLE
选择文件夹时如果退出会导致pcl崩溃

### ISSUE THREAD

**Issue by czchangzhi** [Hex-Dragon/PCL2#2970]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

下载mod或选择已有文件夹时如果没有选择文件夹而是退出窗口会导致pcl崩溃

### 重现步骤

1.版本选择
2.添加已有文件夹
3.在文件夹中进行搜索（什么都行）
4.退出搜索界面至普通文件夹界面
5.不选择文件直接退出选择文件夹（即右上角的“×”）
6.崩辣！

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/13626927/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/13626928/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/13626929/Log5.txt)
[Log.txt](https://github.com/Hex-Dragon/PCL2/files/13626930/Log.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13626931/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/13626932/Log2.txt)

**Comment by WorldHim** [comment]
无法复现，日志里也没有问题

**Comment by JingHai-Lingyun** [comment]
无法复现，这可能是系统问题...

**Comment by LTCatt** [comment]
和 #2970 疑似重复
