### ISSUE TITLE
PCL2 Release分支 数字签名被吊销

### ISSUE THREAD

**Issue by xiaoniaoawa** [Hex-Dragon/PCL2#2971]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

见 ([https://www.bilibili.com/read/cv28431940]) 

### 重现步骤

不用触发，安全中心会帮你速度卸载PCL2

### 日志与附件

PCL2压根打不开，不需要log（即答

**Comment by JingHai-Lingyun** [comment]
#2904
重新签名了 2.6.10，事故原因是打包用 Action 使用的签名证书过期，已经更换了新的签名证书

**Comment by xiaoniaoawa** [comment]
> #2904 重新签名了 2.6.10，事故原因是打包用 Action 使用的签名证书过期，已经更换了新的签名证书

好嘞（）我去吧iessues给关掉去

**Comment by JingHai-Lingyun** [comment]
来个人 Label 重复下...

**Comment by xiaoniaoawa** [comment]
> 来个人 Label 重复下...
> 
> 另 @xiaoniaoawa 你的 Bilibili 专栏最好在开头的地方醒目标注下 “问题已解决” 等字样（怕等下有人以为问题还存在 a.a.

加好了，然后...记得关注下PCL x8的加群申请（）（）（）

**Comment by JingHai-Lingyun** [comment]
加群申请等管理吧 :)
另外说明下我不是开发人员，只是社区贡献者 a.a.
