### ISSUE TITLE
[19:55:01.870] [Download] Win10_x64.iso 882#：出错，解密操作失败，请参见内部异常。 → 无法解密指定的数据。

### ISSUE THREAD

**Issue by rumengchuxing062** [Hex-Dragon/PCL2#2973]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

没有啥表现，就只是在下载文件时会在日志里写入解码失败
并且怀疑可能会导致文件下载失败
网络环境为WiFi，支持IPv4/IPv6双栈访问（默认IPv4）
Powershell的wget命令貌似也有类似错误

### 重现步骤

1、点击更多
2、百宝箱
3、自定义下载
4、开始下载

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13627892/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/13627893/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/13627894/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/13627890/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/13627891/Log5.txt)

**Comment by JingHai-Lingyun** [comment]
Log1 频繁看见
```
[Download] Win10_x64.iso：出错，解密操作失败，请参见内部异常。
→ 无法解密指定的数据。
   在 PCL.ModNet.NetFile.Thread(NetThread Info)
```
还有两次
```
[Download] Win10_x64.iso：出错，设备未就绪。

   在 PCL.ModNet.NetFile.Thread(NetThread Info)
错误类型：System.IO.IOException
```

**Comment by burningtnt** [comment]
怀疑是网络不稳定，导致数据不完整

**Comment by WorldHim** [comment]
请给出下载链接

**Comment by JingHai-Lingyun** [comment]
**省流：日志里看到的下载链接均无法使用（403）**

---

日志里看到 [下载链接 1](https://down.xitongtiandi.net/bjxt/20231130/Win10_x64.iso?sign=088d43d89456aed21774b9ff7146ba31&t=6575adad&timestamp=6575a6a5&auth_key=c29eb7ee3d49c05cf90232559e176275) 不过好像验证数据过期了，Openresty 回了个 403
还见 [下载链接 2](https://www.xitongtiandi.net/s/down?sid=17529) 不过也 403

**Comment by deep-dark-forest** [comment]
网络有问题，或者链接寄了
试试别的下载器？

**Comment by deep-dark-forest** [comment]
额不建议使用迅雷等下载软件来判定是否是启动器问题（
因为迅雷啥的会对下载进行加速的，但是pcl2不会，所以可能会出现pcl2报错其他下载器正常的情况……

**Comment by burningtnt** [comment]
请更改 Label 到“等待反馈者“

**Comment by LTCatt** [comment]
并非启动器导致。该文件被 Windows 加密过。
