### ISSUE TITLE
建议在已安装的mc版本中添加“版本搜索”功能

### ISSUE THREAD

**Issue by Mcenahle** [Hex-Dragon/PCL2#2978]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在已安装的mc版本中添加“版本搜索”功能。
<img width="977" alt="屏幕截图 2023-12-11 195710 - 2" src="https://github.com/Hex-Dragon/PCL2/assets/85427807/6df183c4-0151-4f81-b64e-e2aec875fc48">

### 原因

这项优化让我可以更方便地搜索版本。
如果没有这项优化，我每次都必须手动找版本，让操作变得很麻烦（，且容易让我的鼠标滑轮趋势）。

**Comment by LTCatt** [comment]
#548
