### ISSUE TITLE
PCL2右键窗口不透明

### ISSUE THREAD

**Issue by IKUN05648** [Hex-Dragon/PCL2#2979]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [x] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在PCL2里设置透明度后，右键窗口不更改
![屏幕截图 2023-12-12 035229](https://github.com/Hex-Dragon/PCL2/assets/130807276/175f0c63-89ad-4302-af08-e51021616dfc)

### 原因

如果设置透明度的话，一定是要整个透明的，如果右键窗口不透明的话，就会影响整体的感受（视觉统一感），强烈建议优化。

**Comment by WorldHim** [comment]
右键菜单
