### ISSUE TITLE
关闭“调试选项”后，弹出的信息依然是“部分调试信息将在刷新或启动器重启后切换显示!”

### ISSUE THREAD

**Issue by Mcenahle** [Hex-Dragon/PCL2#2980]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

<img width="977" alt="屏幕截图 2023-12-11 200516" src="https://github.com/Hex-Dragon/PCL2/assets/85427807/5625a5c3-de93-4470-ad88-1e1b5bc5bf4d">

### 重现步骤

1、开启“调试选项”
2、转到“设置” - “启动器”，然后关闭“调试选项”。

### 日志与附件

这个貌似不要日志文件了吧...

**Comment by JingHai-Lingyun** [comment]
从在调试转为取消调试有可能会有部分信息仍然以调试的方式记录/显示
我觉得没问题

**Comment by WorldHim** [comment]
“**切换**显示”
感觉应该是预期内的行为，插眼。

**Comment by LTCatt** [comment]
WAI
