### ISSUE TITLE
左边栏白色背景宽度错误

### ISSUE THREAD

**Issue by liu-zhou-L** [Hex-Dragon/PCL2#2982]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

启动器侧边栏，当鼠标移动至栏目上时，显示的选中效果长度异常
![螢幕擷取畫面 2023-12-13 010603](https://github.com/Hex-Dragon/PCL2/assets/61187892/1daf8795-80ef-461c-9d83-59f2e2ed33f0)
![螢幕擷取畫面 2023-12-13 010610](https://github.com/Hex-Dragon/PCL2/assets/61187892/5312fcfc-0d0b-4a0e-a658-e57abac63606)

### 重现步骤

鼠标移至启动器侧边栏栏目上

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13651280/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/13651283/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/13651284/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/13651285/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/13651286/Log5.txt)

**Comment by JingHai-Lingyun** [comment]
嘶... 这个 Bug 貌似很难复现
我之前也有一次发现侧边栏的背景伸缩异常，不过切换下页面就好了

**Comment by LTCatt** [comment]
这个 bug 没有稳定的复现方法……如果谁能稳定复现的话才能修……

**Comment by John-is-playing** [comment]
复现成功，只是几率问题，重新开个几十次就行，概率相对于其他概率BUG大一些
![BUG复现1](https://github.com/Hex-Dragon/PCL2/assets/108605883/2706c08a-4aaf-4a7a-a489-d5f25f19b391)
![BUG复现2](https://github.com/Hex-Dragon/PCL2/assets/108605883/6a21c08f-9479-4860-ad2c-9547699c2cb6)
[Log.txt](https://github.com/Hex-Dragon/PCL2/files/13761499/Log.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13761500/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/13761501/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/13761502/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/13761503/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/13761504/Log5.txt)

**Comment by John-is-playing** [comment]
> 复现成功，只是几率问题，重新开个几十次就行，概率相对于其他概率BUG大一些 ![BUG复现1](https://private-user-images.githubusercontent.com/108605883/292666208-2706c08a-4aaf-4a7a-a489-d5f25f19b391.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0MTQ2NTcsIm5iZiI6MTcwMzQxNDM1NywicGF0aCI6Ii8xMDg2MDU4ODMvMjkyNjY2MjA4LTI3MDZjMDhhLTRhYWYtNGE3YS1hNDg5LWQ1ZjI1ZjE5YjM5MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNFQxMDM5MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZTM5NGE2ZDNkYjdhNDRmZjlmY2FiY2FjMWYwYzY0MTQ2NmRhZWQ4YzM5ZmU3NmExNmUyYTZhMjA4MGQxZTUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._Hb1Ah90gPlw4C-eIYvGPKJkFWWBTPaiWb5KX5Gq2eg) ![BUG复现2](https://private-user-images.githubusercontent.com/108605883/292666211-6a21c08f-9479-4860-ad2c-9547699c2cb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0MTQ2NTcsIm5iZiI6MTcwMzQxNDM1NywicGF0aCI6Ii8xMDg2MDU4ODMvMjkyNjY2MjExLTZhMjFjMDhmLTk0NzktNDg2MC1hZDJjLTk1NDc2OTljMmNiNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNFQxMDM5MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mM2JmZTkyYWNhZWYxMjRjOGQ4NTk1NjJkZjA0ZTIxNDllYmE4NmZmZGViZjM0YTAwNGIwMzBkOGUzZDJiODEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Q8ZseNHvI-wu3MYfES_w3PJTlgAR7h073bQGsGOsky0) 日志.txt 日志1.txt 日志2.txt 日志3.txt 日志[4.txt](https://github.com/Hex-Dragon/PCL2/files/13761503/Log4.txt) [日志](https://github.com/Hex-Dragon/PCL2/files/13761501/Log2.txt)[5.txt](https://github.com/Hex-Dragon/PCL2/files/13761499/Log.txt)

日志重新上传一下
[Log.txt](https://github.com/Hex-Dragon/PCL2/files/13761506/Log.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13761507/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/13761508/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/13761509/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/13761510/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/13761511/Log5.txt)

**Comment by burningtnt** [comment]
#3042 感谢 @HaoTian22 给出的稳定复现步骤！

**Comment by allMagicNB** [comment]
> > 复现成功，只是几率问题，重新开个几十次就行，概率相对于其他概率BUG大一些 ![BUG复现1](https://private-user-images.githubusercontent.com/108605883/292666208-2706c08a-4aaf-4a7a-a489-d5f25f19b391.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0MTQ2NTcsIm5iZiI6MTcwMzQxNDM1NywicGF0aCI6Ii8xMDg2MDU4ODMvMjkyNjY2MjA4LTI3MDZjMDhhLTRhYWYtNGE3YS1hNDg5LWQ1ZjI1ZjE5YjM5MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNFQxMDM5MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZTM5NGE2ZDNkYjdhNDRmZjlmY2FiY2FjMWYwYzY0MTQ2NmRhZWQ4YzM5ZmU3NmExNmUyYTZhMjA4MGQxZTUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._Hb1Ah90gPlw4C-eIYvGPKJkFWWBTPaiWb5KX5Gq2eg) ![BUG复现2](https://private-user-images.githubusercontent.com/108605883/292666211-6a21c08f-9479-4860-ad2c-9547699c2cb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0MTQ2NTcsIm5iZiI6MTcwMzQxNDM1NywicGF0aCI6Ii8xMDg2MDU4ODMvMjkyNjY2MjExLTZhMjFjMDhmLTk0NzktNDg2MC1hZDJjLTk1NDc2OTljMmNiNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNFQxMDM5MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mM2JmZTkyYWNhZWYxMjRjOGQ4NTk1NjJkZjA0ZTIxNDllYmE4NmZmZGViZjM0YTAwNGIwMzBkOGUzZDJiODEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Q8ZseNHvI-wu3MYfES_w3PJTlgAR7h073bQGsGOsky0) 日志.txt 日志1.txt 日志2.txt 日志3.txt 日志[4.txt](https://github.com/Hex-Dragon/PCL2/files/13761503/Log4.txt) [日志](https://github.com/Hex-Dragon/PCL2/files/13761501/Log2.txt)[5.txt](https://github.com/Hex-Dragon/PCL2/files/13761499/Log.txt)
> 
> 日志重新上传一下
> [Log.txt](https://github.com/Hex-Dragon/PCL2/files/13761506/Log.txt)
> [Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13761507/Log1.txt)
> [Log2.txt](https://github.com/Hex-Dragon/PCL2/files/13761508/Log2.txt)
> [Log3.txt](https://github.com/Hex-Dragon/PCL2/files/13761509/Log3.txt)
> [Log4.txt](https://github.com/Hex-Dragon/PCL2/files/13761510/Log4.txt)
> [Log5.txt](https://github.com/Hex-Dragon/PCL2/files/13761511/Log5.txt)
> 

@John-is-playing 那个，Log.txt是你激活隐藏主题时Dev 0.4.4留下的，无任何帮助，不必上传，可以直接删掉Log.txt的

**Comment by ZmdNotFound** [comment]
从 更多 页面切到 下载 页面后意外触发此bug 目前未复现

![截图](https://github.com/Hex-Dragon/PCL2/assets/103509379/1a971ecc-19f5-43af-be2f-fe73cb490fe3)

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14791705/Log1.txt)

调试模式开 Bug相关日志在 2220 行前后

**Comment by allMagicNB** [comment]
@LTCatt 考虑 Pin 下吗？

**Comment by mc-124** [comment]
无意间再次复现
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15092972/Log1.txt)
从更多快速点到下载那有概率复现

应该是因为错误判断了页面导致的，因为更多和下载的宽度一样，正常来说侧边栏不需要动

**Comment by LTCatt** [comment]
`RectLeftBackground`

**Comment by wuliaodexiaoluo** [comment]
UnPin?

**Comment by allMagicNB** [comment]
> UnPin?

还没更新呢，先别急。

**Comment by Michaelshenmo** [comment]
复现成功
在版本文件夹添加一个更长的地址（原来的也要稍短）

**Comment by wuliaodexiaoluo** [comment]
还没更新

**Comment by allMagicNB** [comment]
> 复现成功
> 在版本文件夹添加一个更长的地址（原来的也要稍短）

早修完了，不需要复现了。

**Comment by liu-zhou-L** [comment]
82FF-7DEC-64CA-8860

**Comment by LTCatt** [comment]
你的解锁码：Un06+9Hu2UJKmBrsVFc8VBls0xR4Ax5A
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
