### ISSUE TITLE
在选择模组前置mod时PCL出现错误

### ISSUE THREAD

**Issue by hamiguatang** [Hex-Dragon/PCL2#2983]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

当点击前置mod时出现报错

### 重现步骤

1、下载星系（GlactiCraft）
2、在mod列表中找到（AsmodeusCore[GlactiCraft Addons Library]）
3、点击后面的详情
4、点击前置mod星系

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13654171/Log1.txt)

**Comment by JingHai-Lingyun** [comment]
#2913
