### ISSUE TITLE
优化 Mod 管理中的界面

### ISSUE THREAD

**Issue by GOhaochen** [Hex-Dragon/PCL2#2984]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

原本样子：

![image](https://github.com/Hex-Dragon/PCL2/assets/98160605/aa7351fc-821e-49ef-a35a-fdc3af4fbec2)

（建议）修改后的样子,有点粗糙，见谅！

![image](https://github.com/Hex-Dragon/PCL2/assets/98160605/ce4fa14c-4941-4ca2-ae97-c5d21031f853)

### 原因

小幅度优化就能提高此页面的美观性
~~(强迫症会很舒适)~~

**Comment by GOhaochen** [comment]
（补充建议）

1. 将按钮与搜索框合并
2. 在“安装mod”按钮下添加一行小字【（将mod拖入此窗口可实现同样功能）】，提示不知道此功能的用户

![image](https://github.com/Hex-Dragon/PCL2/assets/98160605/b8798f40-27f9-45a7-b31c-a506ed1686a1)

**Comment by GOhaochen** [comment]
龙猫辛苦！

**Comment by JingHai-Lingyun** [comment]
第三个按钮加小字的话可能要动控件了... 感觉不会做
平分空间可能有戏 加个待处理看看

**Comment by Pigeon0v0** [comment]
平分空间没啥意义，既然这里平分了其他地方为啥不平分

加小字应该加个 Tip 就可以了

**Comment by LTCatt** [comment]
做更新的时候我看着办吧 =。=

**Comment by GOhaochen** [comment]
龙猫回我！龙猫心里有我！！！！！！！！！！！！！！！！:)

**Comment by LTCatt** [comment]
寻思了一下，暂时先不动 UI，之后如果有机会在大改 UI 的时候一起改吧
