### ISSUE TITLE
失效模组后缀兼容 .old

### ISSUE THREAD

**Issue by Anyplez** [Hex-Dragon/PCL2#2985]
### 检查项

- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [x] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

希望能识别更多格式的失效模组，比如 .jar.old 格式的模组，激活的话就是变回 .jar 
如果可以的话增加一个功能自定义失效模组的后缀

### 原因

有些启动器或者模组管理器，处理旧版本模组或模组失效时是在后面加old后缀，pcl识别不了这个后缀的模组，只能翻文件夹改。模组少还好能一个一个改，多的话改起来太麻烦，希望能从根源上解决

**Comment by Anyplez** [comment]
github的app版还不会用浪费了好多操作cry

**Comment by GOhaochen** [comment]
我认为有用
还可以解决扩展名冲突的问题

**Comment by LTCatt** [comment]
可以添加 .old 的兼容，自定义就算了

**Comment by JingHai-Lingyun** [comment]
自定义确实有点奇怪.png

**Comment by Anyplez** [comment]
> 可以添加 .old 的兼容，自定义就算了

龙猫，主题怎么解锁呀，是在这层回复设备码么

**Comment by JingHai-Lingyun** [comment]
对的 在这里发送你的 PCL 识别码

**Comment by WForst-Breeze** [comment]
很抱歉，优化建议无法获得活跃橙
