### ISSUE TITLE
下载Emendatus Enigmatica mod时失败

### ISSUE THREAD

**Issue by nageih** [Hex-Dragon/PCL2#2987]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

下载Emendatus Enigmatica mod的[1.19.2-2.1.5](https://www.curseforge.com/minecraft/mc-mods/emendatus-enigmatica/files/4439106)版本以及包含该版本模组的整合包时出现问题，经测试1.19.2-2.1.0没有问题

### 重现步骤

1、下载该模组版本
2、下载失败

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/13661329/Log2.txt)

**Comment by JingHai-Lingyun** [comment]
Log2 Ln 304
```
[21:43:17.023] [Download] 已禁用的下载源：https://media.forgecdn.net/files/4551//EmendatusEnigmatica-2.1.5-build.61%2Bmc1.19.2.jar
```
又一个下载地址中（`/4551/0/`）的 `0` 不见了

---

另还见到 Log2 Ln 281
```
[21:43:11.545] 识别 Minecraft 版本时出错：版本 json 不规范（XTY）
→ 未将对象引用设置到对象的实例。
   在 PCL.ModMinecraft.McVersion.VisitListener()
   在 PCL.ModMinecraft.McVersion.CloneListener()
   在 PCL.ModMinecraft.McVersion.VisitListener()
错误类型：System.NullReferenceException
```

**Comment by nageih** [comment]
既然issue重复，我close？

**Comment by JingHai-Lingyun** [comment]
等下 还有另一个 Bug
或许可以这个关了开新的？

**Comment by LTCatt** [comment]
和 #2899 重复
识别版本应该是那个 json 就是不规范……如果你觉得应该得能识别可以再开一个新 issue
