### ISSUE TITLE
#2917的问题在2.6.11版本复现

### ISSUE THREAD

**Issue by FQO3** [Hex-Dragon/PCL2#2988]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

与 #2917 完全相同的bug再次出现
![image](https://github.com/Hex-Dragon/PCL2/assets/111474347/2e49e9f9-8bb4-42c5-9886-1264e51c211a)

### 重现步骤

1、点击“设置”
2、点击“帮助”
目前复现出的问题有： 指南-整合包制作指南 ； MINECRAFT-安装光影 ； 启动器-参与完善PCL帮助库 ； 个性化-自定义帮助界面 ； 个性化-整合包制作指南

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13667009/Log1.txt)

**Comment by kong-que-dnf123** [comment]
虽然但是
#2917 问题不就出现于2.6.11吗（）
