### ISSUE TITLE
关于版本隔离

### ISSUE THREAD

**Issue by skybeach-None** [Hex-Dragon/PCL2#2992]
### 检查项

- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [x] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [x] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 原因

有时一个存档需要在多个版本打开，但是我又不想在其它版本看到这些存档

**Comment by JingHai-Lingyun** [comment]
我记得好早之前看到过这个提议，龙猫当时说自己复制存档吧
我找下帖子

**Comment by JingHai-Lingyun** [comment]
找到了 #1870

> 龙猫：在这些版本内关闭版本隔离即可

**Comment by WorldHim** [comment]
要实现文件夹内容互通 win 可以用 `mklink`
