### ISSUE TITLE
java8和17均安装但启动1.17以下版本时仍失败

### ISSUE THREAD

**Issue by xwh1412** [Hex-Dragon/PCL2#3001]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

1.17以上版本都可以启动，但是1.17以下的所有版本都无法启动，Java8和Java17都按正常步骤安装运行

### 重现步骤

1、下载1.17以下版本
2、启动显示失败

### 日志与附件

[错误报告-2023-12-16_17.41.20.zip](https://github.com/Hex-Dragon/PCL2/files/13692280/-2023-12-16_17.41.20.zip)

**Comment by burningtnt** [comment]
已有重复反馈
