### ISSUE TITLE
启动器主页显示错误

### ISSUE THREAD

**Issue by SadEPa0628** [Hex-Dragon/PCL2#3002]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

这啥啊这是
![image](https://github.com/Hex-Dragon/PCL2/assets/120295331/2f4fcbd1-6c14-4524-8286-f3cec5ac2ec0)
 （如果问题重复这是我的疏忽...）

### 重现步骤

1、双击Plain Craft Launcher 2.exe

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13692680/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/13692681/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/13692682/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/13692683/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/13692679/Log5.txt)

**Comment by JingHai-Lingyun** [comment]
这**不是** PCL 的问题，只是图片未加载出来罢了
你或许该等待一段时间，如问题无法解决请去 [Light-Beacon/PCL2-NewsHomepage](https://github.com/Light-Beacon/PCL2-NewsHomepage) 投递反馈而不是这里！

**Comment by burningtnt** [comment]
有什么问题吗？

**Comment by JingHai-Lingyun** [comment]
> 有什么问题吗？

版本开头图没了.png

**Comment by SadEPa0628** [comment]
呃..我想过，我要去反馈啦

**Comment by JingHai-Lingyun** [comment]
去吧
下次记得找对反馈的地方

**Comment by SadEPa0628** [comment]
我想不出这块的代码是咋写的，我不知道这是哪个的问题

**Comment by JingHai-Lingyun** [comment]
>我想不出这块的代码是咋写的，我不知道这是哪个的问题

预设主页均为第三方内容，你可以在 #2528 帖找到对应的作者

**Comment by SadEPa0628** [comment]
🤣
![image](https://github.com/Hex-Dragon/PCL2/assets/120295331/cb6b2bf9-e3be-4625-937e-5a57ea163a5c)
那我就呃，，，算是同样遇到问题的用户，让最亮的信标意识到问题严重性[doge]
