### ISSUE TITLE
关于使用replaymod compatible版Sodium后使用PCL下载官方Sodium后出现的启动器报错问题

### ISSUE THREAD

**Issue by yizhi9jiyan9** [Hex-Dragon/PCL2#3006]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

使用replaymod compatible版Sodium后使用PCL下载官方Sodium后启动器出现System.NullReferenceException报错

### 重现步骤

1、在Replay官网下载replaymod compatible版Sodium并放入mods文件夹
2、在PCL提供的下载中下载官方Sodium
3、启动器出现上述日志报错

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13694717/Log1.txt)

**Comment by yizhi9jiyan9** [comment]
其实是废话（x

**Comment by WorldHim** [comment]
#2916
