### ISSUE TITLE
当有下载任务出现错误，但仍有正常下载的任务时无法关闭错误任务，只会在正常下载任务全部结束时关闭

### ISSUE THREAD

**Issue by UserNameiiiii** [Hex-Dragon/PCL2#3007]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如果有两个下载任务，一个下载任务出现403错误码，一个任务正常下载，那么错误的任务无法手动关闭，只有其他任务下载完才会关闭

### 重现步骤

1.准备两个下载任务，一个出现了403错误，一个正常下载。
2.当尝试关闭错误任务时会关不掉。

### 日志与附件

见下面的回复

**Comment by MCSteve123** [comment]
请发文件，而非切片……

**Comment by UserNameiiiii** [comment]
抱歉，我还以为是把一整个文本的内容发进去，原来全发进去也叫切片，抱歉。







                       
原始邮件
                       
                     

发件人："根号谈"< ***@***.*** &gt;;

发件时间：2023/12/17 18:21

收件人："Hex-Dragon/PCL2"< ***@***.*** &gt;;

抄送人："UserNameiiiii"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [Hex-Dragon/PCL2] 当有下载任务出现错误，但仍有正常下载的任务时无法关闭错误任务，只会在正常下载任务全部结束时关闭 (Issue #3007)




 
请发文件，而非切片……

**Comment by JingHai-Lingyun** [comment]
提交 Log 的时候直接上传文件
另：别用邮箱回复...

**Comment by MCSteve123** [comment]
> 提交 Log 的时候直接上传文件 另：别用邮箱回复...
> 
> 话说 这 Bug 咋又出现了 附：文件形式的日志 [Log-issue3007.txt](https://github.com/Hex-Dragon/PCL2/files/13695724/Log-issue3007.txt)

我就记得这玩意之前有过，还真有……

**Comment by LTCatt** [comment]
日志中没有发现问题……你点了三次开始下载，也只关闭了三次错误卡片……
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/a8d447dd-298d-4d28-9729-1158a2e8f402)
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/0b348f09-0b92-4475-ae86-c429d29b60de)

有其他人能复现吗？

**Comment by Chiloven945** [comment]
这个问题之前不是反馈过了嘛，也修复了

**Comment by WForst-Breeze** [comment]
昨晚我可以复现，先安装一个整合包，在过程中再用度盘链接下载一个文件爆 403 错误，这时候下载详情页面报错的卡片无法关闭🤔

**Comment by UserNameiiiii** [comment]
现在又出现了。（我昨天刚注册的号，现在还不知道怎么用Github回复...）







                       
原始邮件
                       
                     

发件人："ClovenBugle"< ***@***.*** &gt;;

发件时间：2023/12/18 3:22

收件人："Hex-Dragon/PCL2"< ***@***.*** &gt;;

抄送人："UserNameiiiii"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [Hex-Dragon/PCL2] 当有下载任务出现错误，但仍有正常下载的任务时无法关闭错误任务，只会在正常下载任务全部结束时关闭 (Issue #3007)




 
这个问题之前不是反馈过了嘛，也修复了

**Comment by UserNameiiiii** [comment]
（由于我不会用Github回复,所以使用邮箱）我复现一下，我用步骤记录器进行记录，这次的错误任务错误码是404







                       
原始邮件
                       
                     

发件人："龙腾猫跃"< ***@***.*** &gt;;

发件时间：2023/12/18 1:59

收件人："Hex-Dragon/PCL2"< ***@***.*** &gt;;

抄送人："UserNameiiiii"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [Hex-Dragon/PCL2] 当有下载任务出现错误，但仍有正常下载的任务时无法关闭错误任务，只会在正常下载任务全部结束时关闭 (Issue #3007)




 
日志中没有发现问题……你点了三次开始下载，也只关闭了三次错误卡片……
 image.png (view on web)
 image.png (view on web)
 
有其他人能复现吗？

**Comment by UserNameiiiii** [comment]
@LTCatt （我这里用这种方式只是因为不知道怎么回复）我这边复现一下，错误码是404：
[步骤.zip](https://github.com/Hex-Dragon/PCL2/files/13699624/default.zip)

**Comment by burningtnt** [comment]
> @LTCatt （我这里用这种方式只是因为不知道怎么回复）我这边复现一下，错误码是404： [步骤.zip](https://github.com/Hex-Dragon/PCL2/files/13699624/default.zip)

你的屏幕截图没有打包进去

**Comment by UserNameiiiii** [comment]
> > @LTCatt （我这里用这种方式只是因为不知道怎么回复）我这边复现一下，错误码是404： [步骤.zip](https://github.com/Hex-Dragon/PCL2/files/13699624/default.zip)
> 
> 你的屏幕截图没有打包进去

emm,我不知道咋打包

**Comment by burningtnt** [comment]
> emm,我不知道咋打包

按照你上传的 htm 文件所请求的图片，你应当打包和 htm 同属一个文件夹下的所有文件。

**Comment by UserNameiiiii** [comment]
> > emm,我不知道咋打包
> 
> 按照你上传的 htm 文件所请求的图片，你应当打包和 htm 同属一个文件夹下的所有文件。

步骤生成器就给我一个mnt网页文件，没有其他的

**Comment by burningtnt** [comment]
> 步骤生成器就给我一个mnt网页文件，没有其他的

那么就手动截图 / 录屏，以证明你的结论：“当有下载任务出现错误，但仍有正常下载的任务时无法关闭错误任务，只会在正常下载任务全部结束时关闭”

**Comment by JingHai-Lingyun** [comment]
传录屏罢

**Comment by UserNameiiiii** [comment]
> 传录屏罢 传上来之后可以把之前的 comment 全都 hide as outdated 了

您自己实践一下不就知道是不是真的了吗（

**Comment by kong-que-dnf123** [comment]
这个复现行吗......
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13717208/Log1.txt)

https://github.com/Hex-Dragon/PCL2/assets/120994373/8a94718a-a8f0-4ccb-a11c-33c70e43bf86

**Comment by UserNameiiiii** [comment]
> 这个复现行吗...... [Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13717208/Log1.txt)
> 
>  default.mp4

终于有人复现了...

**Comment by wzhziheng** [comment]
复现了

**Comment by wzhziheng** [comment]
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15263224/Log1.txt)

https://github.com/Hex-Dragon/PCL2/assets/74056542/3049f35a-a504-409c-ac01-3eb394329d06

关不掉

**Comment by Deep-Dark-Forest** [comment]
是否考虑与#2825 重复？

**Comment by LTCatt** [comment]
不确定是不是一个原因，修的时候再说（

**Comment by kong-que-dnf123** [comment]
> [Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15263224/Log1.txt)
> 
>  QQ.20240509214213.mp4 
> 关不掉

👍
