### ISSUE TITLE
关于连接登录服务器超时的问题

### ISSUE THREAD

**Issue by HeyHuangHi** [Hex-Dragon/PCL2#3009]
### 检查项

- [ ] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我使用火狐浏览器，在littleskin建立了账号、创建了角色且用户名为纯英文，在浏览器内存储了密码。设置第三方登录后，无论是复制粘贴还是自己键入输入密码之后，点击“启动游戏”，都会出现“连接登录服务器超时”的报错。使用了加速器、换了中国移动的流量热点，都无法解决这个问题。
![Uploading 图片_20231218132255.png…]()

### 重现步骤

1、打开PCL，输入邮箱账号
2、打开火狐浏览器，点击右上角三道杠，点击“密码”
3、往下滑，找到littleskin.cn，点击进入
4、点击“密码”旁边的复制按钮
5、进入PCL，在密码框右键，点击“粘贴”
6、点击“启动游戏”按钮

### 日志与附件

[Uploading Log1.txt…]()
[Uploading Log2.txt…]()

**Comment by HeyHuangHi** [comment]
我将杀毒软件（360）关闭、电脑网络的所有防火墙也关闭了，没有任何作用

**Comment by JingHai-Lingyun** [comment]
你的图片 & 日志没有传上来，请等待 `Uploading XXX` 字样消失后再提交

**Comment by rumengchuxing062** [comment]
检查一下你的登录地址是否正确，是否将注册地址错误的填到登录地址，以及访问登陆地址确认启动前你是可以正常连接到服务器

**Comment by WorldHim** [comment]
看样子不是 pcl 问题
超时先关了，如有需要可继续反馈
