### ISSUE TITLE
支持IPV6联机

### ISSUE THREAD

**Issue by FUTURE16524** [Hex-Dragon/PCL2#301]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

检出是否支持IPV6，如果支持获取地址，然后手动输入端口号得到一个直接联机的IP地址
（感觉这个功能非常好做，加上UI不超过一个小时？但是能大大增加小白直接联机的可能性）

### 原因

如果有这个功能使用PCL2联机的人数会大大增加，同时降低玩家联机成本和学习难度，HiPer收费较高（对于学生而言）并且目前ipv6已经基本进入千家万户，很多人都有IPV6联机的需求，但如果没有这个功能，在联机使用体验即使有HiPer收费的情况下依然比较稀碎。本人参与了两周的HiPer售后以及一些IPV6联机的实验，发现hiper出现bug超级多且30%需要远程协助解决，但是ipv6目前没有失败过（证明https://shimo.im/docs/5rk9dplRrYuYXjqx）如果可以添加将感激不尽

第一次写这么正式的文章好紧张鸭！~

**Comment by FUTURE16524** [comment]
刚刚写完时提交突然未响应，又重新写了一遍挂了梯子才交上：(

**Comment by LTCatt** [comment]
@ffip 你看看？我搞不懂……

**Comment by ffip** [comment]
您好 @FUTURE16524,

我是HiPer项目负责人阿猫(Cato Sweeney)感谢您喜欢PCL作品及对HiPer的支持与热爱。

首先就本文所论：
1.关于文中所属IPV6部分

官方答复：

抛开NAT6、安全性、对等性、QOS的现实情况不谈，PCL及HiPer并不阻止用户使用IPV6进行联机或组网,用户可以通过自我学习研究自行组网及解决以上问题达到联机。

2.**在联机使用体验即使有HiPer收费的情况下依然比较稀碎。本人参与了两周的HiPer售后以及一些IPV6联机的实验，发现hiper出现bug超级多且30%需要远程协助解决**

官方答复：

HiPer官方售后团队我并未发现有您的存在，
暂时无法得知您的售后方式、方法以及所遇到的问题统计。
我并不知道HiPer的BUG超级多的结论从何而来，
若有我不介意您在本ISSUE直接提出。
**另远程协助处理售后为我司为所有用户提供更好的售后服务体验的方式，**
其目的在于为了更快更好的解决用户问题，而不是让用户自己去折腾问题如何解决。

若您仍存在疑问，您可发送邮件到 service@the.bb 或 电话联系 0816-2899090 (北京时间 8:30~24:00)

**Comment by LTCatt** [comment]
umm 感觉你的意思是让 PCL2 检测是否是 IPv6，但这个（我觉得）应该是玩家自己的事情……
（况且我没有用过 IPv6 联机，不清楚其中的问题，也没法测试）

**Comment by MinecraftSTL** [comment]
HiPer，Frp，ipv6都是联机方式且均可外置，只是目前选择了HiPer作为内置方式之一而已，如果有IPV6联机需求可以自行尝试相关方案或寻求其他外置工具

**Comment by FUTURE16524** [comment]
本人主要意图是希望简化IPV6联机流程，并没有贬低HIPer联机方式，只是认为联机仍有改进空间并提出改进建议和降低联机花费（如果涉及公司方利益可以私信本人邮箱3212772632@qq.com）
