### ISSUE TITLE
下载问题

### ISSUE THREAD

**Issue by wjdgz** [Hex-Dragon/PCL2#3010]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

使用PC l的模组下载的时候，他的前置模组直接提示Bug，如果不提交提交这可能永久存在。

### 重现步骤

将性能优化模组下载1.12.2的然后从PC l主页点版本设置。点模组管理。点击性能优化模组的详情。此时会自动弹出此模组的前置模组。然后再点击这个前置模组就会报错。

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/13700182/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/13700183/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/13700184/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/13700185/Log5.txt)
[Log.txt](https://github.com/Hex-Dragon/PCL2/files/13700186/Log.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13700187/Log1.txt)

**Comment by JingHai-Lingyun** [comment]
#2913 已修复，请等待下次更新
