### ISSUE TITLE
向PCL2快速发送很多无用消息会导致PCL2闪退

### ISSUE THREAD

**Issue by UserNameiiiii** [Hex-Dragon/PCL2#3011]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

运行附件程序，鼠标放到PCL窗口上并按下P附件程序会导致PCL2闪退（PCL2并没有详细记录log）

### 重现步骤

1.运行附件程序
2.鼠标放到PCL窗口上并按下P触发附件程序

### 日志与附件

[触发程序.zip](https://github.com/Hex-Dragon/PCL2/files/13701114/default.zip)
[步骤.zip](https://github.com/Hex-Dragon/PCL2/files/13701118/default.zip)

**Comment by JingHai-Lingyun** [comment]
正常来讲不会有人故意向 PCL 发送大量信息吧？
感觉这个反馈就....很....emm....故意...

**Comment by UserNameiiiii** [comment]
（Github不知道咋回复所以邮箱）那是为什么PCL2没记录LOG,而BakaXL启动器却成功记录？







                       
原始邮件
                       
                     

发件人："凌云"< ***@***.*** &gt;;

发件时间：2023/12/18 16:20

收件人："Hex-Dragon/PCL2"< ***@***.*** &gt;;

抄送人："UserNameiiiii"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [Hex-Dragon/PCL2] 向PCL2快速发送很多无用消息会导致PCL2闪退 (Issue #3011)




 
正常来讲不会有人故意向 PCL 发送大量信息吧？
 感觉这个反馈就....很....emm....故意...

**Comment by UserNameiiiii** [comment]
​消息不等于信息吧，虽然消息可以发送，信息也可以发送，但一个是发送给用户一个是发送给窗口...







                       
原始邮件
                       
                     

发件人："凌云"< ***@***.*** &gt;;

发件时间：2023/12/18 16:20

收件人："Hex-Dragon/PCL2"< ***@***.*** &gt;;

抄送人："UserNameiiiii"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [Hex-Dragon/PCL2] 向PCL2快速发送很多无用消息会导致PCL2闪退 (Issue #3011)




 
正常来讲不会有人故意向 PCL 发送大量信息吧？
 感觉这个反馈就....很....emm....故意...

**Comment by UserNameiiiii** [comment]
我之前还试过用附件程序瞄准360急救箱窗口，360急救箱窗口当时就未响应了，还试过向360主窗口发送WM_DESTROY消息，360主窗口当时就报错了，但是进程好好的







                       
原始邮件
                       
                     

发件人："凌云"< ***@***.*** &gt;;

发件时间：2023/12/18 16:20

收件人："Hex-Dragon/PCL2"< ***@***.*** &gt;;

抄送人："UserNameiiiii"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [Hex-Dragon/PCL2] 向PCL2快速发送很多无用消息会导致PCL2闪退 (Issue #3011)




 
正常来讲不会有人故意向 PCL 发送大量信息吧？
 感觉这个反馈就....很....emm....故意...

**Comment by UserNameiiiii** [comment]
另外，在千万别点中的PCL2变得不稳定了，用附件程序都能给PCL2来个"类仍有类似的窗口"这样的错误...

**Comment by JingHai-Lingyun** [comment]
日志先发上来看看吧
千万别点本来就是个彩蛋，不稳定很正常，且不会受理任何有关其的 Issue
~~别用邮箱...一堆无用内容...~~

**Comment by UserNameiiiii** [comment]
> 日志先发上来看看吧 千万别点本来就是个彩蛋，不稳定很正常，且不会受理任何有关其的 Issue ~别用邮箱...一堆无用内容...~

日志：
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/13701529/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/13701531/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/13701532/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/13701533/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13701534/Log1.txt)

**Comment by UserNameiiiii** [comment]
> 日志先发上来看看吧 千万别点本来就是个彩蛋，不稳定很正常，且不会受理任何有关其的 Issue ~别用邮箱...一堆无用内容...~

补充3、4日志：
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/13701553/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/13701554/Log4.txt)

**Comment by UserNameiiiii** [comment]
在千万别点中的PCL2又出新的错误类型了，直接调用到Null里面了...
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13701634/Log1.txt)

**Comment by LTCatt** [comment]
需要用户主动刻意触发的 Bug 不会受理，抱歉（

**Comment by UserNameiiiii** [comment]
真·及时止损（理由都没来的及编是吧（））







                       
原始邮件
                       
                     

发件人："龙腾猫跃"< ***@***.*** &gt;;

发件时间：2023/12/18 17:08

收件人："Hex-Dragon/PCL2"< ***@***.*** &gt;;

抄送人："UserNameiiiii"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [Hex-Dragon/PCL2] 向PCL2快速发送很多无用消息会导致PCL2闪退 (Issue #3011)




 
Closed #3011 as not planned.

**Comment by kong-que-dnf123** [comment]
> 在千万别点中的PCL2又出新的错误类型了，直接调用到Null里面了... [Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13701634/Log1.txt)

~？“千万别点”还有这种整活吗......~

**Comment by UserNameiiiii** [comment]
> > 在千万别点中的PCL2又出新的错误类型了，直接调用到Null里面了...[日志 1.txt](https://github.com/Hex-Dragon/PCL2/files/13701634/Log1.txt)
> 
> ~？"千万别点"还有这种整活吗......~

其实，在PCL出现PCL对话框的时候使用提供软件也会直接报错就比如枚举类型无效、Null、仍有类似的窗口啥的（~话说这个已经被作者删掉的东西你是咋找到的）

**Comment by kong-que-dnf123** [comment]
>（~话说这个已经被作者删掉的东西你是咋找到的）
在你的日志52行到75行，你自己搞出来的啊......
```
[17:02:27.379] [Control] 普通弹窗：警告
PCL 作者不会受理由于点击千万别点造成的任何 Bug。
这是最后的警告，是否继续操作？
[17:02:29.334] [Control] 按下按钮：确定
[17:02:29.340] [Control] 普通弹框返回：2
[17:02:40.408] [System] 诊断信息：
操作系统：Microsoft Windows 10 专业版
剩余内存：3308 M / 7120 M
DPI：96（100%）
MC 文件夹：D:\天政\PCL2\.minecraft\
文件位置：D:\天政\PCL2\
[17:02:40.413] 程序出现未知错误：未将对象引用设置到对象的实例。
   在 System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
错误类型：System.NullReferenceException
[17:02:42.085] [Animation] 两个动画帧间隔 2890 ms
[17:02:43.095] [Animation] 两个动画帧间隔 1469 ms
[17:02:43.374] [System] 收到关闭指令
[17:02:43.903] [Animation] 两个动画帧间隔 1016 ms
[17:02:44.676] [System] 程序已退出，返回值：Success

```

**Comment by UserNameiiiii** [comment]
> > （~话说这个已经被作者删掉的东西你是咋找到的）
> 
> 在你的日志52行到75行，你自己搞出来的啊......
> 
> ```
> [17:02:27.379] [Control] 普通弹窗：警告
> PCL 作者不会受理由于点击千万别点造成的任何 Bug。
> 这是最后的警告，是否继续操作？
> [17:02:29.334] [Control] 按下按钮：确定
> [17:02:29.340] [Control] 普通弹框返回：2
> [17:02:40.408] [System] 诊断信息：
> 操作系统：Microsoft Windows 10 专业版
> 剩余内存：3308 M / 7120 M
> DPI：96（100%）
> MC 文件夹：D:\天政\PCL2\.minecraft\
> 文件位置：D:\天政\PCL2\
> [17:02:40.413] 程序出现未知错误：未将对象引用设置到对象的实例。
>    在 System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    在 System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
>    在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> 错误类型：System.NullReferenceException
> [17:02:42.085] [Animation] 两个动画帧间隔 2890 ms
> [17:02:43.095] [Animation] 两个动画帧间隔 1469 ms
> [17:02:43.374] [System] 收到关闭指令
> [17:02:43.903] [Animation] 两个动画帧间隔 1016 ms
> [17:02:44.676] [System] 程序已退出，返回值：Success
> ```

你咋看出来的？

**Comment by kong-que-dnf123** [comment]
>你咋看出来的？

翻日志瞎看啊

**Comment by UserNameiiiii** [comment]
> > 你咋看出来的？
> 
> 翻日志瞎看啊

就这段日志，能看出来啥...

**Comment by LTCatt** [comment]
不要在 issue 里版聊……github 不是聊天的地儿……
