### ISSUE TITLE
我尽力了 真的很想玩

### ISSUE THREAD

**Issue by 01senile** [Hex-Dragon/PCL2#3013]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃基本不是 PCL 的原因，请 **不要** 提交反馈。你可以在论坛或社区找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用 HMCL 启动，HMCL 没有出现问题。** 如果 HMCL 也无法启动就不是 PCL 导致的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

就是点开始游戏之后说检测到microsoft出现错误 很抱歉你的游戏出现一些问题

### PCL 错误报告、日志与附件

[错误报告-2023-12-19_9.43.17.zip](https://github.com/Hex-Dragon/PCL2/files/13711683/-2023-12-19_9.43.17.zip)

**Comment by JingHai-Lingyun** [comment]
```
Caused by: java.lang.module.ResolutionException: Module optifine reads another module named optifine
```
Optifine 重了？

**Comment by burningtnt** [comment]
你装了俩 OptiFine

在 2023-12-19 13:55:18，01senile ***@***.***> 写道：


检查项
我所启动的游戏不是整合包，且未安装任何 Mod。 安装 Mod 后的游戏崩溃基本不是 PCL 的原因，请 不要 提交反馈。你可以在论坛或社区找人求助，但这里并不是你求助的地方。
我已尝试使用 HMCL 启动，HMCL 没有出现问题。 如果 HMCL 也无法启动就不是 PCL 导致的问题，请 不要 提交反馈。下载 HMCL
我已在 Issues 页面 和 常见&难检反馈及问题列表 中搜索，确认了这一 Bug 未被提交过。
描述

就是点开始游戏之后说检测到microsoft出现错误 很抱歉你的游戏出现一些问题

PCL 错误报告、日志与附件

错误报告-2023-12-19_9.43.17.zip

HMCL 启动脚本

No response

**Comment by 01senile** [comment]
> ```
> Caused by: java.lang.module.ResolutionException: Module optifine reads another module named optifine
> ```
> 
> Optifine 重了？
我下载了个光影 所以下了个optifine 然后没干别的 就上不去了

**Comment by burningtnt** [comment]
盲猜 PCL2 已经下了一个 OptiFine，然后你又自己下了

在 2023-12-19 14:03:01，01senile ***@***.***> 写道：


Caused by: java.lang.module.ResolutionException: Module optifine reads another module named optifine


Optifine 重了？
我下载了个光影 所以下了个optifine 然后没干别的 就上不去了

**Comment by JingHai-Lingyun** [comment]
如果你在安装新 Minecraft 版本的时候选择了 OptiFine，又通过其他方式（PCLMod下载/Optifine官网下载等）再次安装了 Optifine，将导致此问题。
如果你是 Forge/Fabric 客户端，到客户端下的 mods 文件夹删除一个 OptiFine 即可。

**Comment by LTCatt** [comment]
请完成检查项，确认 HMCL 可以启动这个版本，再来交 issue

**Comment by 01senile** [comment]
好的&nbsp;我明白了&nbsp;我看看




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Hex-Dragon/PCL2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月19日(星期二) 下午3:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Hex-Dragon/PCL2] 我尽力了 真的很想玩 (Issue #3013)





 
如果你在安装新 Minecraft 版本的时候选择了 OptiFine，又通过其他方式（PCLMod下载/Optifine官网下载等）再次安装了 Optifine，将导致此问题。
 如果你是 Forge/Fabric 客户端，到客户端下的 mods 文件夹删除一个 OptiFine 即可。

**Comment by burningtnt** [comment]
如果你有其他问题，可以前往 (HMCl KOOK 频道)[https://kook.top/Kx7n3t] 或 (HMCL Discord 频道)[https://discord.gg/v8pZmN2Euh] 获取进一步的帮助

**Comment by JingHai-Lingyun** [comment]
链接括弧反了.png
