### ISSUE TITLE
启动器链接到 Wiki 的网址改为新网站

### ISSUE THREAD

**Issue by FlameFire26** [Hex-Dragon/PCL2#3014]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

Minecraft Wiki 更新为 `https://zh.minecraft.wiki/` ，PCL 中指向原 Wiki 的链接也应更改。（如：下载新版本中各版本右侧“更新日志”按钮所跳转的网站）

### 原因

无

**Comment by JingHai-Lingyun** [comment]
https://github.com/Hex-Dragon/PCL2/issues/2865 已经修改了所有 Wiki 指向，但还未推送至正式版，请等待下次更新
短时间内你可以参考迁移通知中 **我们需要你的帮助** 一部分的指引，使用浏览器扩展来重定向到新的 Wiki 页面

**Comment by deep-dark-forest** [comment]
@JingHai-Lingyun 额您知道您是Contributor吗？下次看到这种重复的问题可以直接添加错“重复标签”，这样就没必要麻烦其他人再看一遍了（

**Comment by JingHai-Lingyun** [comment]
额？
Contributor 是没法改标签的...
能改标签的是 Collaborator

**Comment by deep-dark-forest** [comment]
> 额？
> Contributor 是没法改标签的...
> ~~仔细看看~~ 能改标签的是 Collaborator

不好意思，我的眼睛瞎掉了……

**Comment by hejiehao** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/98140773/8d93b67f-e98c-4f4e-83b9-c62631f2c22c)
![image](https://github.com/Hex-Dragon/PCL2/assets/98140773/fc2d2d34-a653-4a17-932c-9238db83519c)
很大差别的

**Comment by deep-dark-forest** [comment]
> ![image](https://github.com/Hex-Dragon/PCL2/assets/98140773/8d93b67f-e98c-4f4e-83b9-c62631f2c22c)
> ![image](https://github.com/Hex-Dragon/PCL2/assets/98140773/fc2d2d34-a653-4a17-932c-9238db83519c)
> 很大差别的

额，我当然知道这些区别，只不过我的眼睛出现了问题……
