### ISSUE TITLE
更新后不再出现“由于未满足Mod的依赖项，导致游戏退出”

### ISSUE THREAD

**Issue by xiaoyuanjun233** [Hex-Dragon/PCL2#3016]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![QQ截图20231220194929](https://github.com/Hex-Dragon/PCL2/assets/125738947/3f78fb44-1516-42ed-bd05-ff23fa62141a)
![QQ截图20231220194952](https://github.com/Hex-Dragon/PCL2/assets/125738947/3b2c9f92-cf4e-419a-9fe1-e5128789b7e8)

### 重现步骤

启动游戏，mod列表中若存在未安装前置的mod，将会向图2一样一直卡在步骤“等待游戏窗口出现”并非更新前图1这样“由于未满足Mod的依赖项，导致游戏退出”

### 日志与附件

无

**Comment by burningtnt** [comment]
打开任务管理器，能看到后台有 `javaw.exe` 进程吗？

**Comment by xiaoyuanjun233** [comment]
> 打开任务管理器，能看到后台有 `javaw.exe` 进程吗？

无

**Comment by JingHai-Lingyun** [comment]
那是游戏还未启动，只有启动了之后因为崩溃才会分析出是为什么（上方 1 图是分析器分析到缺少前置）

**Comment by xiaoyuanjun233** [comment]
> 那是游戏还未启动，只有启动了之后因为崩溃才会分析出是为什么（上方 1 图是崩溃分析器分析到缺少前置）

问题是之前游戏会启动，然后崩溃分析，神奇的是现在缺少前置游戏都不会启动
