### ISSUE TITLE
這個檔案並不安全，因此遭到 Chrome 封鎖。

### ISSUE THREAD

**Issue by player10783** [Hex-Dragon/PCL2#3017]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![螢幕擷取畫面 2023-12-20 200629](https://github.com/Hex-Dragon/PCL2/assets/90902717/0cda3cbe-f67e-4d4b-8ab6-a662c5feade3)

### 重现步骤

1.Download
2.Windows Defender 和 Chrome 會快速封鎖和刪除

### 日志与附件

none

**Comment by burningtnt** [comment]
请在 Windows Defender 和 Chrome 中忽略警告
