### ISSUE TITLE
部分电脑疑似无法进行微软登录

### ISSUE THREAD

**Issue by LTCatt** [Hex-Dragon/PCL2#3018]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在 #2767 修复后，部分电脑疑似无法进行微软登录。
![Cache_2fb16d0f9511c475](https://github.com/Hex-Dragon/PCL2/assets/40348278/a5f6d0a7-a8c2-4669-913c-30824ced9c14)

如果你遇到了相同的报错，请使用正式版 2.6.10 再次尝试，不管正式版能否正常登录，都请回复这个 issue（最好一并留下 QQ 号以便后续测试），我需要确认这是因为 #2767 导致的……

正式版下载地址：https://afdian.net/p/0164034c016c11ebafcb52540025c377

### 重现步骤

使用 Snapshot 2.6.11+ 进行微软登录。

**Comment by JingHai-Lingyun** [comment]
Snapshot 2.6.12 新加账号 & 登录已加账号，未见 SSL/TLS 异常
QQ 1913532130

**Comment by burningtnt** [comment]
补充：请给出你所在的地理位置信息（精确到省级行政区）和运营商信息（移动/联通/电信）

**Comment by LTCatt** [comment]
找了好几个受害者确认，看起来这个证书异常是随机的，在挂梯子后都能恢复正常，虽然原因不明但应该不是新版本的问题，关了 :)

**Comment by JingHai-Lingyun** [comment]
怪怪的，PCL D 群里好几次看到 SSL/TLS 无效了...

**Comment by allMagicNB** [comment]
> 怪怪的，PCL D 群里好几次看到 SSL/TLS 无效了...

非常好微软，让我的脑子旋转（

**Comment by LTCatt** [comment]
我到时候把强制验证成功做成设置吧……

**Comment by xiaoniaoawa** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/112697401/4db91b94-f84f-4e2f-bfad-19f973132c9e)
北京联通CHINA169-BJ China Unicom Beijing Province Network复现失败

**Comment by LTCatt** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/e592df6e-a1e6-4d39-920b-f55f69b9107b)
添加了默认开启的验证证书选项，如果其他玩家遇见该问题，请尝试先让他们关掉它，看看能不能得到改善……

**Comment by LTCatt** [comment]
在多个独立来源验证了，即使在不开梯子的情况下，**仅仅关闭 SSL 证书校验就能成功登录。**

比起压根登录不上，游戏都进不去，还是让玩家至少能进去比较好……
所以验证设置改为了默认关闭，如果有需要可以自行开启。
