### ISSUE TITLE
取消更多子页面勾选会错误地勾选最后两项

### ISSUE THREAD

**Issue by FQO3** [Hex-Dragon/PCL2#3019]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

首先庆祝一下，龙猫又更新了一次pcl！然后我就快乐的重测了一下我的#2989
额……虽然上次的复现方法失效了……但这回更离谱了，以至于我已经无法使用文字进行描述了……请看我发b站的视频吧……
[https://www.bilibili.com/BV1Je411r7qc/](https://www.bilibili.com/BV1Je411r7qc)
（ps：龙猫是不是又没测试就发了……）
啊对……我才发现更新日志上把的#2989写成#2983了……（也不算啥大问题，懒得再开一个issue了）
![image](https://github.com/Hex-Dragon/PCL2/assets/111474347/37aa762f-f4a3-45bc-bf88-4fe2f33439bc)

### 重现步骤

打开设置中的个性化-功能隐藏
然后对着【更多 子页面】一顿输出就能发现bug了

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13738561/Log1.txt)

**Comment by burningtnt** [comment]
~哈哈哈哈哈，看了视频，好抽象啊~

**Comment by kong-que-dnf123** [comment]
我丢等等我功能隐藏呢？！？！？！
![image](https://github.com/Hex-Dragon/PCL2/assets/120994373/0e7c9859-4ba3-4ac4-a3b4-e6a64313ef49)

**Comment by FQO3** [comment]
轻按f12谢谢

**Comment by iPodtouch6557** [comment]
> 我丢等等我功能隐藏呢？！？！？！ ![image](https://private-user-images.githubusercontent.com/120994373/292614068-ff7196fb-4102-4084-a2d4-3e7707cc35b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzNDg3OTMsIm5iZiI6MTcwMzM0ODQ5MywicGF0aCI6Ii8xMjA5OTQzNzMvMjkyNjE0MDY4LWZmNzE5NmZiLTQxMDItNDA4NC1hMmQ0LTNlNzcwN2NjMzViMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyM1QxNjIxMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZTIyMTEwZWJmY2ViNTY2Y2ViZjliMTY0OTZlMWNmN2UxOWU5ZTg0MzUyYzljNmI5MzRiZDFhYjYyYmFlYjEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eEJ5OouhHT8YDbAHGxA9NmjY0VJaovZ9b_uwp_HRo4I)
哈哈 我的也被我隐藏了

**Comment by FQO3** [comment]
啊不是……你确定你改了？？？？？？？？？？？？？？？？？？？？？？？？

**Comment by JingHai-Lingyun** [comment]
没修好？
