### ISSUE TITLE
更新后默认为空白主页

### ISSUE THREAD

**Issue by xiaobaimc** [Hex-Dragon/PCL2#3021]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

我在更新完pcl后，弹出来的主页是空白的，由于我用习惯了自定义主页，看到一片空白的时候脑子直接宕机（doge
摸索了一会发现主页设置在更新之后自己改为空，就很奇怪
![image](https://github.com/Hex-Dragon/PCL2/assets/113223243/6ecea45a-5c31-4733-93e7-bf188a7485bd)

### 原因

优化不优化无所谓，就只是单纯想说一下（手动狗头）

**Comment by LTCatt** [comment]
历史中的今天 主页因为网络原因暂时关掉了，如果之前选的是这个会被自动重置

**Comment by xiaobaimc** [comment]
> 历史中的今天 主页因为网络原因暂时关掉了，如果之前选的是这个会被自动重置

不是，我的是自定义主页

**Comment by JingHai-Lingyun** [comment]
呃？reopen 然后尝试复现下？
~~我更新了.. 没存旧版.. 没法帮忙了..~~

**Comment by kong-que-dnf123** [comment]
我的联网更新主页没有问题......
![image](https://github.com/Hex-Dragon/PCL2/assets/120994373/a5b08f50-e596-4a46-8214-e6830decc9cf)

**Comment by kong-que-dnf123** [comment]
刚刚拿了另外一个PCL看看
没有消失但是
**主页是最新新闻预设名咋成“你知道吗”了啊。。。**
![image](https://github.com/Hex-Dragon/PCL2/assets/120994373/7a616b6a-873c-43ae-8f65-0074e57814fd)

![image](https://github.com/Hex-Dragon/PCL2/assets/120994373/578b543a-8b8d-4f70-9e06-05dd4e48dd8c)

↓ 这个是视频文件 我不知道为啥它就变成链接了哈麻烦点一下awa ↓
https://github.com/Hex-Dragon/PCL2/assets/120994373/ca0ddec0-9e09-4c31-ba8a-e13c12550bbd
---------------------------------------------------------------------------------------------------------------------------------------------
更新前日志：
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13758294/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/13758295/Log2.txt)
更新后日志：
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13758297/Log1.txt)

**Comment by WForst-Breeze** [comment]
> 刚刚拿了另外一个PCL看看
> 没有消失但是
> **主页是最新新闻预设名咋成“你知道吗”了啊。。。**

这感觉应该是另一个问题，请单开 issue

**Comment by SALTWOOD** [comment]
无法复现，猜测是因为删除了项目但是项目索引未变更导致溢出（也许？

**Comment by iPodtouch6557** [comment]
预设新闻主页未发现问题，log还是待会再说

**Comment by rumengchuxing062** [comment]
已尝试，未能成功复现（2.2.14-2.6.12）
可否提供你自定义主页的文件

**Comment by LTCatt** [comment]
下次更新的时候我顺便看一眼吧，估计找不到原因……

**Comment by JingHai-Lingyun** [comment]
额 补充一嘴o
有个很意外的现象，我的主页是 新闻主页 但是设置里头显示的是 **你知道吗？**
PCL Release 2.6.12 (311.50)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13801959/Log1.txt)
