### ISSUE TITLE
删除Mojang账户迁移

### ISSUE THREAD

**Issue by Mcenahle** [Hex-Dragon/PCL2#3022]
### 检查项

- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

删除Mojang账户迁移

### 原因

目前，Mojang账户迁移已被微软停用。因此，此功能已经不再被大家所需要。

**Comment by iPodtouch6557** [comment]
建议加个过渡期 即点击mj登录时提示该功能被移除了 过两三个快照或一个正式版移除
直接删有的老玩家心情可能不大好 当然这些情绪与PCL2开发没有问题的话（指一大群人发discussions询问）也就删吧

**Comment by deep-dark-forest** [comment]
"majong"账户

**Comment by iPodtouch6557** [comment]
> "majong"账户

真的是麻将账户啊
