### ISSUE TITLE
管理员权限启动失败

### ISSUE THREAD

**Issue by radish-andy** [Hex-Dragon/PCL2#3025]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在2023.12.23晚正在开心的玩，这时我打开启动器点击内存优化弹出如图
![1](https://github.com/Hex-Dragon/PCL2/assets/119546929/711223cb-75f5-4c69-be49-742ea1594b89)
随后我认为是我没有用管理员启动随后.......
![2](https://github.com/Hex-Dragon/PCL2/assets/119546929/e172c5a6-5702-4473-a33f-10a3e05789a3)

### 重现步骤

1、点击内存优化
我不确定是不是所有人都这样，但我的确是这样的

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13756947/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/13756948/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/13756949/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/13756950/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/13756951/Log5.txt)

**Comment by radish-andy** [comment]
其他的软件用管理员启动都没有问题

**Comment by burningtnt** [comment]
你是联想电脑吗？如果是，那么你的账户名称是 Administrator 吗？如果不是，那就说明你的管理员权限实际并不是真正的管理员权限。

**Comment by radish-andy** [comment]
本人是华硕电脑

**Comment by radish-andy** [comment]
账户是微软登陆的

**Comment by burningtnt** [comment]
看起来这并不是 HMCL 的问题。为方便沟通，你可以来 HMCL 的 KOOK 频道或 Discord 频道，直接提问即可

**Comment by radish-andy** [comment]
啊？HMCL？

**Comment by burningtnt** [comment]
草，脑子串线了

**Comment by radish-andy** [comment]
6

**Comment by burningtnt** [comment]
那这样，你按下 Win+R 键，输入 cmd，按下回车，在弹出的黑色窗口中输入 `net users` 命令，按回车，截图

**Comment by radish-andy** [comment]
![Uploading QQ截图20231223105043.png…]()

**Comment by radish-andy** [comment]
上传2.5年

**Comment by burningtnt** [comment]
> Uploading QQ截图20231223105043.png…

请等到 `Uploading XXX` 字样消失后再发送，否则图片不会上传成功。

**Comment by radish-andy** [comment]
![QQ截图20231223105043](https://github.com/Hex-Dragon/PCL2/assets/119546929/438ac5da-a7c2-4a0d-853e-d41d62ec95aa)

**Comment by burningtnt** [comment]
哈哈哈哈哈哈哈哈，果然猜对了。

你关闭这个黑色窗口，按下 Windows 键，输入 cmd，右键“命令提示符”，以管理员权限打开
在弹出的黑色窗口中输入 `net users Administrator /active:Y`，按下回车。
随后，窗口应当提示“命令成功完成”

之后，请回到 Windows 登录界面，在左下角选中 Administrator 登录。
登陆后，将 PCL2 添加至防火墙白名单，再退出登录，回到原来你那个“肖晓”账户，再登录进去试试

**Comment by JingHai-Lingyun** [comment]
如果还有后续的话 转到 Discussion 提问大区吧

**Comment by burningtnt** [comment]
好主意，不过，似乎没有一键转移。要不你把 Issue 关了，再让当事人去创建一个？

**Comment by radish-andy** [comment]
妈妈生的

**Comment by JingHai-Lingyun** [comment]
可以 但是我关不了...
另请友好交流

**Comment by radish-andy** [comment]
啊？

**Comment by radish-andy** [comment]
要干嘛？

**Comment by radish-andy** [comment]
你们给我整傻了

**Comment by burningtnt** [comment]
请先关闭本 Issue，再来这里解决：#3028
