### ISSUE TITLE
Mod管理选项卡模组过多搜索卡死

### ISSUE THREAD

**Issue by Harvey2433** [Hex-Dragon/PCL2#3029]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在版本设置内的模组选项卡下，模组数量非常多时执行搜索会导致PCL主程序无响应直至退出

### 重现步骤

1、找一个模组非常多的游戏客户端（模组数量280以上）
2、打开版本设置，点击Mod管理选项卡，然后使用系统自带输入法在搜索框使用拼音输入
3、PCL主程序无响应并退出

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13758868/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/13758871/Log2.txt)

**Comment by burningtnt** [comment]
经典主线程 IO…… 龙猫你不考虑变成异步的？

**Comment by xiaobaimc** [comment]
这不就是我之前提的issue吗，上次版本更新就说修复了，怎么还在( •̀ ω •́ )

**Comment by JingHai-Lingyun** [comment]
地址指向不对...

**Comment by Harvey2433** [comment]
啥时候能修好

**Comment by Harvey2433** [comment]
隐藏主题解锁 B6BE-BE3D-67CC-4FCA

**Comment by LTCatt** [comment]
你的解锁码：nhmK3ISiWEJe+T8mus6Dt7rBtPTbe8DR
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
