### ISSUE TITLE
点击空白处关闭弹出窗口

### ISSUE THREAD

**Issue by mei-iem** [Hex-Dragon/PCL2#3030]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

举个例子：
![反馈提示](https://github.com/Hex-Dragon/PCL2/assets/97957593/aaeef277-2466-4fd2-aa48-4593d90d7d6e)
此时点击弹出窗口旁边的暗色部分来关闭这个弹出窗口，等效于点击“取消”

### 原因

（不是示例）
这项优化让我可以更方便地_关闭窗口_。
如果没有这项优化，我每次都必须_点击取消_，让操作变得很麻烦。

**Comment by burningtnt** [comment]
可能会导致用户意外的关闭窗口

**Comment by mei-iem** [comment]
> 可能会导致用户意外的关闭弹出式窗口

或许可以为部分重要的弹出式窗口设置不允许点击空白处关闭，并给出“必须选择一项”的提示
因为等效于取消，所以不会有影响吧

**Comment by LTCatt** [comment]
不考虑，这不是预期的交互行为 =。=
