### ISSUE TITLE
更新优化

### ISSUE THREAD

**Issue by wuzhuoyi114514** [Hex-Dragon/PCL2#3031]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在产生问题时，先进行一次更新检查是否有**更新的版本**
（更新可以解决99%的问题）

### 原因

114514191810不知道

**Comment by WForst-Breeze** [comment]
事实上，如果启动器不是最新版本，是没法通过 PCL 打开反馈网页的🧐

**Comment by SuoHouDaiShi** [comment]
按照你的意思，这个功能似乎已经有了🤔

**Comment by wuzhuoyi114514** [comment]
但是打不开github就有脑瘫找群（

**Comment by JingHai-Lingyun** [comment]
有些特定问题要在特定版本下才会复现...
考虑检查后加个选项是否更新罢...

**Comment by iPodtouch6557** [comment]
知道这些东西的直接输网址 不知道的拦不住脑残……目前还是觉得可以加一个 没啥必要但是其实
