### ISSUE TITLE
检查 Java 均意外失败

### ISSUE THREAD

**Issue by JingHai-Lingyun** [Hex-Dragon/PCL2#3033]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

意外的在检查 Java 时全部检查失败（ Java 正常，手动检查结果见附件图片，另日志里也有正常检查的部分）
补充：版本为 PCL Release 2.6.10

### 重现步骤

未知...

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13760879/Log1.txt)

![image](https://github.com/Hex-Dragon/PCL2/assets/109946426/56d83af3-49e4-45bd-b852-2b3f82e418e8)

**Comment by MCSteve123** [comment]
PCL运行的命令不是和手动的命令一样吗，咋就不行呢

**Comment by MCSteve123** [comment]
好吧，无法复现（

**Comment by kong-que-dnf123** [comment]
在 行150~161：
```
[12:43:50.305] 位于 D:\YWZJ1201Client\jre\bin\ 的 Java 存在异常：尝试运行该 Java 失败
   在 PCL.ModJava.JavaEntry.Check()
   在 PCL.ModJava._Closure$__16-0._Lambda$__0()
错误类型：System.ApplicationException
[12:43:50.306] 位于 D:\YWZJ1165Client\jre\bin\ 的 Java 存在异常：尝试运行该 Java 失败
   在 PCL.ModJava.JavaEntry.Check()
   在 PCL.ModJava._Closure$__16-0._Lambda$__0()
错误类型：System.ApplicationException
[12:43:50.383] 位于 E:\Java\jdk-17\bin\ 的 Java 存在异常：尝试运行该 Java 失败
   在 PCL.ModJava.JavaEntry.Check()
   在 PCL.ModJava._Closure$__16-0._Lambda$__0()
错误类型：System.ApplicationException
```

PCL不小心没运行开Java还是什么初始化没反应过来啥的~（毕竟后面都正常了）~

**Comment by iPodtouch6557** [comment]
> PCL不小心没运行开Java还是什么初始化没反应过来啥的 ~（毕竟后面都正常了）~

和我之前遇到的错误一样，但是电脑不在手边，log就再说吧

**Comment by LTCatt** [comment]
这个 issue 是因为在未知条件下，PCL 尝试运行 java -version，但 java 不会给予 PCL 任何 stdout 输出（可以理解为在 cmd 运行 java -version 但窗口里没有任何输出，java 运行完直接结束了）
尝试过在出现这个 issue 的电脑上直接用 cmd 跑，结果是正常的，并不知道为什么 PCL 跑就拿不到输出……
如果有人有头绪可以说一下，但我确实不知道咋整

**Comment by iPodtouch6557** [comment]
问一下author是不是必然情况，以及出现概率大概多少？
有可能是临时抽风，这样就没必要修了

**Comment by JingHai-Lingyun** [comment]
偶然现象......
很奇怪，我也不知道怎么复现......

**Comment by iPodtouch6557** [comment]
> 偶然现象...... 很奇怪，我也不知道怎么复现......

那我也遇到过:)
这就不影响使用了，没必要修

**Comment by LTCatt** [comment]
与 #1496 重复
