### ISSUE TITLE
“欧皇彩”主题在重启启动器后错误的设置为上一次使用的任何主题

### ISSUE THREAD

**Issue by HopiHopy** [Hex-Dragon/PCL2#3036]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

例如我上一个正在使用的主题是“跳票红”，我再将主题改为“欧皇彩”，关闭启动器重新启动，主题就变成了“跳票红”
其他的任何主题都没有这类情况发生

### 重现步骤

1、使用“欧皇彩”主题
2、重启启动器

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13765986/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/13765987/Log2.txt)

**Comment by SuoHouDaiShi** [comment]
并未复现成功……
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/13766362/Log2.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13766363/Log1.txt)

**Comment by allMagicNB** [comment]
PCL2 Snapshot 2.6.12（310.0）未成功复现，推测为个人系统原因或`Setup.ini`因为某种问题未更新
