### ISSUE TITLE
缓存 Mod Hash 计算结果

### ISSUE THREAD

**Issue by computer-drive** [Hex-Dragon/PCL2#3037]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

加入一个设置功能，用于开关显示mod图标，并且加入缓存。

### 原因

在新版本打开一个版本的mod管理界面时，和先前不同的是，当mod过多时，加载的时间比以前更长了，除此之外，也变得更卡了，因此我希望加入设置和缓存功能

**Comment by LTCatt** [comment]
设置和图标都有缓存，加载时间变长是因为要计算 Mod 的 Hash，之后可以给这个加个缓存

**Comment by HomoobyDX** [comment]
或许和bakaxl的模组索引一样的效果？
