### ISSUE TITLE
Mod 管理页面没有返回顶部按钮

### ISSUE THREAD

**Issue by LTCatt** [Hex-Dragon/PCL2#3038]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

Mod 管理页面向下滚动足够距离后返回顶部按钮没有出现。

**Comment by WorldHim** [comment]
label 是不是错了
