### ISSUE TITLE
在mod下载，管理中添加客户端需装, 服务端需装 标签

### ISSUE THREAD

**Issue by MeowHua** [Hex-Dragon/PCL2#3039]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

类似于mc百科运行环境: 客户端需装, 服务端需装标签

### 原因

自己制作没有服务端的整合包，有很多客户端需装mod一个个排查很麻烦，也经常会服务端模组列表不兼容这种不方便排查是那个mod。

**Comment by JingHai-Lingyun** [comment]
#2467
