### ISSUE TITLE
安装的不在CurseForge/Modrinth上且不含mcmod.info的模组被错误识别

### ISSUE THREAD

**Issue by HowardZHY** [Hex-Dragon/PCL2#3041]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/Hex-Dragon/PCL2/assets/96782166/e7c63708-1884-459e-a30c-7c2c8bb271c8)
1. LiteLoader 被错误识别，来源不明的西班牙语描述
2. LiteMod WECUI 为客户端Mod，被错误识别为服务器
3. TMI物品管理器被错误识别，来源不明的西班牙语描述
有没有关闭自动模组识别的选项？

### 重现步骤

1、安装1.7.10及之前的老版本
2、安装一些老Mod

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13777013/Log1.txt)

**Comment by JingHai-Lingyun** [comment]
> LiteMod WECUI 为客户端Mod，被错误识别为服务器

那个是 Mod 平台所设置的 Mod 分类，不是指服务端模组

> TMI物品管理器被错误识别，来源不明的西班牙语描述

应该是作者就设置了简介为这样？

**Comment by LTCatt** [comment]
“服务器” 是 Mod 作者设置的标签，意思是服务器相关类型，不是错误识别
那个 Too Many Items Mod 我没找到，发下 Mod 文件？

**Comment by HowardZHY** [comment]
> “服务器” 是 Mod 作者设置的标签，意思是服务器相关类型，不是错误识别 那个 Too Many Items Mod 我没找到，发下 Mod 文件？

https://www.mcmod.cn/class/42.html

**Comment by HowardZHY** [comment]
除此之外，似乎不能正常识别1.7.2以前的高清修复和1.8.9/1.12.2preview版的高清修复

**Comment by HowardZHY** [comment]
补充：高清修复和LiteLoader的识别错误疑似因为有人在CurseForge私自上传过，由于违反许可被删除project，但似乎还能通过API查到信息。

**Comment by HowardZHY** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/96782166/985d4978-0c7c-4e62-a33e-b8d48078b5d8)
![image](https://github.com/Hex-Dragon/PCL2/assets/96782166/791039cd-4037-45bd-87bd-fe9658ed3cdf)

**Comment by deep-dark-forest** [comment]
~~诈尸（确信）~~
能查到信息……能下载吗

**Comment by HowardZHY** [comment]
> ~诈尸（确信）~ 能查到信息……能下载吗

访问转到Curseforge均为404
