### ISSUE TITLE
启动器下载更新完成后没有自动重启

### ISSUE THREAD

**Issue by 3cxc** [Hex-Dragon/PCL2#3044]
### 检查项

- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

版本号2.6.10
在点击更新启动器之后迟迟没有重启启动器
打开文件夹一看早就下载完了
不知道是因为什么原因导致的 **~~(还是说只有旧版才会这样？)~~**

### 重现步骤

更新启动器

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13778950/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/13778946/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/13778947/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/13778948/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/13778949/Log5.txt)

**Comment by LTCatt** [comment]
似乎是在下载更新过程中又手动点击了下载更新导致的

**Comment by 3cxc** [comment]
似乎是的 ~(为什么能在下载更新的时候再点击啊)~

**Comment by JingHai-Lingyun** [comment]
呃 是的...
现在下载的时候连下载进度都没掉了...
然后就~~可能~~会有人以为没下然后再去点击...

**Comment by 3cxc** [comment]
> 呃 是的... 现在下载的时候连下载进度都没掉了... 然后~就可能~会有人以为没下，然后再去点击...（我就是...）

下载进度不是在右下角可以看到吗？

**Comment by JingHai-Lingyun** [comment]
> 下载进度不是在右下角可以看到吗？

很奇怪,没掉了...

**Comment by 3cxc** [comment]
> > 下载进度不是在右下角可以看到吗？
> 
> 很奇怪,没掉了...

它有时候可以出现，是我的问题吗（或者这又是一个问题？

**Comment by WForst-Breeze** [comment]
结合 #3605，似乎 PCL 将新版本错误地安装至了 PCL 配置文件夹中了
```
[21:28:46.268] [System] 无需清理目标更新文件：E:\PCL2\PCL\Plain Craft Launcher 2.exe
```
```

[10:20:26.996] [System] 无需清理目标更新文件：.PCL\Plain Craft Launcher 2.exe
```
