### ISSUE TITLE
在第三方登录选项中更改或移除[设置为LittleSkin]按钮

### ISSUE THREAD

**Issue by Ultimate-remake** [Hex-Dragon/PCL2#3045]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

建议更改或移除在[PCL2主界面]→[版本设置]→[设置]的服务器板块内选择[**第三方登录：Authlib Injector 或 LittleSkin**]选项后
出现的[**设置为 LittleSkin**]按钮
![QQ截图20231227215619](https://github.com/Hex-Dragon/PCL2/assets/102960238/09bb3bec-12fb-47d0-9d80-84fe98627a79)

### 原因

根据我们服务器大部分使用第三方登录的玩家反馈给管理的问题，发现这个按钮对玩家有极大的误导性
因为我们服务器使用的是正版登录和服务器自行搭建的外置登录两种登录方式，没有正版的玩家会去选择使用外置登录
在填写好注册及认证服务器地址后将此按钮误以为是[确定]的按钮(尽管我们专门为PCL2写了设置外置登录教程)
导致自动填写为LittleSkin的地址而无法进入服务器
很多服务器都有自行搭建的登录站，不止LittleSkin一个，所以我希望在未来的更新里更改或移除这个按钮

望开发者采纳

**Comment by burningtnt** [comment]
- 更改 `第三方登录：Authlib Injector 或 LittleSkin` 为 `第三方登录：Authlib Injector`
- 移除 `设置为 LittleSkin` 按钮
- 添加 `预设` 按钮，于认证服务器输入框右侧，点击后可展开下拉列表，包括 LittleSkin 等

**Comment by Ultimate-remake** [comment]
> * 更改  为`第三方登录：Authlib Injector 或 LittleSkin``第三方登录：Authlib Injector`
> * 移除  按钮`设置为 LittleSkin`
> * 添加 按钮，于认证服务器输入框右侧，点击后可展开下拉列表，包括 LittleSkin 等`预设`

这样也可以

**Comment by JingHai-Lingyun** [comment]
预设？
照这样或许可以允许玩家保存常用的 AuthLib 服务器？

**Comment by burningtnt** [comment]
> 预设？
> 照这样或许可以允许玩家保存常用的 AuthLib 服务器？

我设想中的预设是 PCL2 内部硬编码的几个常用服务器 URL
不过，如果可以实现保存玩家常用的 Authlib Injector，也是不错的，不够，那就是另一个 Feature 了

**Comment by LTCatt** [comment]
与 #57 一起处理，到时候把 Little Skin 独立出去，先关了

**Comment by WorldHim** [comment]
> By the way，这玩意儿的官方名称叫做 authlib-injector

有区别吗

**Comment by LiteCat0905** [comment]
> 与 #57 一起处理，到时候把 Little Skin 独立出去，先关了

所以呢 到现在也没删掉，这个littleskin按钮真的害人不浅，这三天各各找我说登不上
跟他整了半天才发现他点了那个该死的按钮。。。
真的会被气死 要不就做一个提示什么的 💔

**Comment by LTCatt** [comment]
我可以先加一个确认弹窗

**Comment by deep-dark-forest** [comment]
？为啥是not planned？

**Comment by LTCatt** [comment]
因为 issue 主楼的 `在第三方登录选项中更改或移除[设置为LittleSkin]按钮` 是 not planned

**Comment by iPodtouch6557** [comment]
这只是一个提示而已，真正的与 #57 合并做
