### ISSUE TITLE
Mod图标显示添加开关

### ISSUE THREAD

**Issue by JJJJGGGG1** [Hex-Dragon/PCL2#3046]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在设置-个性化中添加禁止显示Mod图标的按钮

### 原因

这项优化可以让模组数量多显示图标时不会卡死

**Comment by JingHai-Lingyun** [comment]
类似 #3037

**Comment by LTCatt** [comment]
如果你卡死了，请用 Bug 反馈模板交 Bug，并附上日志，这不一定是图标导致的
