### ISSUE TITLE
主页设置中"Custom.xaml"首字母未大写

### ISSUE THREAD

**Issue by Ad-closeNN** [Hex-Dragon/PCL2#3048]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

![image](https://github.com/Hex-Dragon/PCL2/assets/103355026/e94a2723-fde7-4764-bac2-03d47cd2397b)
custom.xaml没大写，点击“生成教学文件”生成的是大写的Custom.xaml。

### 原因

可能会让小白误解为要小写的custom.xaml

**Comment by WorldHim** [comment]
读取的主页文件不是大小写敏感的吧？不过确实应该改一下

**Comment by burningtnt** [comment]
Windows 系统下文件路径大小写不敏感
不过，介于教程和实际不匹配，建议改一下
