### ISSUE TITLE
为每一个版本添加统计游玩时长

### ISSUE THREAD

**Issue by sakura-ender** [Hex-Dragon/PCL2#3051]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

在版本选择的地方可以显示每个版本的游戏时长

### 原因

单纯想知道玩了多久某个实例，为日后可能的PCL年度总结做准备（今年你玩了多久的xx实例等等）

**Comment by hejiehao** [comment]
#1717

**Comment by sakura-ender** [comment]
> #1717

抱歉没搜索到
