### ISSUE TITLE
备份注册表失效

### ISSUE THREAD

**Issue by Harry-Murray** [Hex-Dragon/PCL2#3054]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

点击备份启动器设置中的备份注册表，命令行闪退，PCL文件夹中午REG文件

### 重现步骤

1、打开PCL
2、点击更多
3、搜索“备份”
4、点击“备份启动器设置”
5、下滑点击“备份注册表”

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13797801/Log1.txt)

**Comment by Harry-Murray** [comment]
> 有REG文件吗？

没有

**Comment by JingHai-Lingyun** [comment]
无法复现（于 v2.6.12 | 310.0） 请提供更多信息

**Comment by allMagicNB** [comment]
我目前正式版中备份正常，快照版也是
应该是环境原因

**Comment by Harry-Murray** [comment]
> 无法复现（于 v2.6.12 | 310.0） 请提供更多信息

Uploading bandicam 2023-12-30 20-38-07-979.mp4…

**Comment by allMagicNB** [comment]
有点像#1796

**Comment by allMagicNB** [comment]
关键是，这也没多大意义。批处理不行，人工备份就行啊

**Comment by Harry-Murray** [comment]
> 关键是，这也没多大意义。批处理不行，人工备份就行啊
是这样的，我只是反馈一下

**Comment by allMagicNB** [comment]
正常备用会调用
`cmd.exe, /C reg export HKEY_CURRENT_USER\Software\PCL PCLRegBackup.reg`
你在这等我，我去给你写个脚本

**Comment by burningtnt** [comment]
@Harry-Murray 你按下 Windows + R 键，输入 cmd，按回车，在弹出的黑色窗口中输入下面这一行命令，然后按回车，截图
`cmd.exe, /C reg export HKEY_CURRENT_USER\Software\PCL PCLRegBackup.reg`

**Comment by allMagicNB** [comment]
[PCLBackup.txt](https://github.com/Hex-Dragon/PCL2/files/13798098/PCLBackup.txt)
好了，参考了你的日志

**Comment by Harry-Murray** [comment]
> [PCLBackup.txt](https://github.com/Hex-Dragon/PCL2/files/13798098/PCLBackup.txt) 好了，参考了你的日志

谢谢

**Comment by allMagicNB** [comment]
> @Harry-Murray 你按下 Windows + R 键，输入 cmd，按回车，在弹出的黑色窗口中输入下面这一行命令，然后按回车，截图 `cmd.exe, /C reg export HKEY_CURRENT_USER\Software\PCL PCLRegBackup.reg`

虽然但是，你这是生成在`C:\Users\用户名`下的方法

**Comment by allMagicNB** [comment]
> > [PCLBackup.txt](https://github.com/Hex-Dragon/PCL2/files/13798098/PCLBackup.txt) 好了，参考了你的日志
> 
> 谢谢

后面会让你按按键继续，你把那个界面截屏发上来

**Comment by Harry-Murray** [comment]
> > > [PCLBackup.txt](https://github.com/Hex-Dragon/PCL2/files/13798098/PCLBackup.txt) 好了，参考了你的日志
> > 
> > 
> > 谢谢
> 
> 后面会让你按按键继续，你把那个界面截屏发上来

![%7B1D2F71CB-6130-4eaf-BB35-F6E02DB264F8%7D](https://github.com/Hex-Dragon/PCL2/assets/88035350/6a374791-a7e9-4af7-952f-b1658064bf45)

**Comment by allMagicNB** [comment]
右键以管理员身份运行啊

> > > > [PCLBackup.txt](https://github.com/Hex-Dragon/PCL2/files/13798098/PCLBackup.txt) 好了，参考了你的日志
> > > 
> > > 
> > > 谢谢
> > 
> > 
> > 后面会让你按按键继续，你把那个界面截屏发上来
> 
> ![%7B1D2F71CB-6130-4eaf-BB35-F6E02DB264F8%7D](https://private-user-images.githubusercontent.com/88035350/293461984-6a374791-a7e9-4af7-952f-b1658064bf45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5NDIyNTIsIm5iZiI6MTcwMzk0MTk1MiwicGF0aCI6Ii84ODAzNTM1MC8yOTM0NjE5ODQtNmEzNzQ3OTEtYTdlOS00YWY3LTk1MmYtYjE2NTgwNjRiZjQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDEzMTIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmMjcwMTk2OTVkZGQyZjE3ZjM3N2ZkMWNhNWYyMzA2MDE3OTc1YzU5NWMwOTkyOTJmZjY3M2ZiYjUxZTJlZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nZPi0Cyxld3z9FO2Elp83GMIpUt4VclFPNiDNZxfiFI)

**Comment by burningtnt** [comment]
和管理员不管理员的无关。 @Harry-Murray 你按下 Windows + R 键，输入 cmd，按回车，在弹出的黑色窗口中输入下面这一行命令，然后按回车，截图
`echo %PATH%`

**Comment by allMagicNB** [comment]
> > > > [PCLBackup.txt](https://github.com/Hex-Dragon/PCL2/files/13798098/PCLBackup.txt) 好了，参考了你的日志
> > > 
> > > 
> > > 谢谢
> > 
> > 
> > 后面会让你按按键继续，你把那个界面截屏发上来
> 
> ![%7B1D2F71CB-6130-4eaf-BB35-F6E02DB264F8%7D](https://private-user-images.githubusercontent.com/88035350/293461984-6a374791-a7e9-4af7-952f-b1658064bf45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5NDIzODYsIm5iZiI6MTcwMzk0MjA4NiwicGF0aCI6Ii84ODAzNTM1MC8yOTM0NjE5ODQtNmEzNzQ3OTEtYTdlOS00YWY3LTk1MmYtYjE2NTgwNjRiZjQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDEzMTQ0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViMTkyMTFlMTRkMmQ2NzczZTVhZTBiZmU5ZDM2MGRlY2NkNDUzMDE4NmIxY2U0NzE4OThlY2JiZmU5ZTk4YmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vOvMVUpK6XIyO2e3xhmbkhxa8JaT4ANEYo5n5iPz5i0)

啥系统啊？？？Reg命令无法调用

**Comment by allMagicNB** [comment]
@JingHai-Lingyun 关了吧，这是个人的系统原因

**Comment by allMagicNB** [comment]
@Harry-Murray 百度搜reg命令无效怎么解决

**Comment by burningtnt** [comment]
……

@Harry-Murray 你按下 Windows + R 键，输入 cmd，按回车，在弹出的黑色窗口中输入下面这一行命令，然后按回车，截图
`echo %PATH%`

@LTCatt 考虑把 reg 命令改成绝对路径

**Comment by allMagicNB** [comment]
三种可能，系统受损，Path值丢失或者reg.exe被“优化”

**Comment by WorldHim** [comment]
> ……
> 
> @Harry-Murray 你按下 Windows + R 键，输入 cmd，按回车，在弹出的黑色窗口中输入下面这一行命令，然后按回车，截图
> `echo %PATH%`
> 
> @LTCatt 考虑把 reg 命令改成绝对路径

谁会把这种命令用绝对路径啊。。而且用绝对路径会导致很多问题，比如有些系统盘不是c盘
既然是系统变量的问题就不属于 pcl 的事了。

**Comment by allMagicNB** [comment]
[PCLBackup.txt](https://github.com/Hex-Dragon/PCL2/files/13798192/PCLBackup.txt)
@Harry-Murray 再试试
