### ISSUE TITLE
阻止用户以系统CLSID命名版本文件夹

### ISSUE THREAD

**Issue by idhaname** [Hex-Dragon/PCL2#3055]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [x] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

例如我把版本文件夹命名为114514.{20D04FE0-3AEA-1069-A2D8-08002B30309D}（即此电脑的CLSID）
此时PCL2能够正常安装并启动游戏，但是资源管理器无法查看版本文件夹（使用命令行能够发现文件夹下内容正常）
点击PCL2中的版本文件夹按钮或双击资源管理器中的该文件夹时会打开相应的CLSID所代表的特殊文件夹（此处为此电脑）；点击存档文件夹时会打开“我的文档”（%userprofile%\documents\）
你也可以改为{8E908FC9-BECC-40f6-915B-F4CA0E70D03D}（即网络和共享中心）还有别的CLSID
![图片](https://github.com/Hex-Dragon/PCL2/assets/68469786/cd2982f3-f251-4cd8-9f8f-7f2913c66a2b)
![图片](https://github.com/Hex-Dragon/PCL2/assets/68469786/e9dccc04-13bf-409a-a792-ddadff327b8d)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/13798293/Log2.txt)

### 原因

尽管游戏能正常启动，但既然文件夹不能命名为CON、NUL等，那CLSID也理应ban掉
（虽然应该不会有多少用户会闲得把文件夹命名为一些奇怪的名称的）

**Comment by LTCatt** [comment]
需要刻意触发的不修复
