### ISSUE TITLE
mod列表会错误的识别出已经在curseforge上下架的模组

### ISSUE THREAD

**Issue by XiaoQiAWA** [Hex-Dragon/PCL2#3056]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

mod列表将已经下架的模组识别为有封面的模组，点详细信息会提示“远程服务器返回错误”，点击“转到curseforge”会发现curseforge上没有该模组
![image](https://github.com/Hex-Dragon/PCL2/assets/154889886/b3a13dc5-dae0-49c5-ab14-fb1b370caf9b)
![image](https://github.com/Hex-Dragon/PCL2/assets/154889886/c098972e-3a52-48a9-b1db-aa9d752b3a4e)

### 重现步骤

1、点击版本设置
2、点击mod列表
3、点击详细信息

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13800092/Log1.txt)

**Comment by zkitefly** [comment]
感觉这是 api 的问题，得给这个 api 屁股

可以试试在获取完 jar 信息后尝试确认该模组是否存在，否则不让点进去

**Comment by deep-dark-forest** [comment]
那么，如果有些整合包包含的模组下载链接失效了咋办

**Comment by XiaoQiAWA** [comment]
> 那么，如果有些整合包包含的模组下载链接失效了咋办

我不道啊

**Comment by iPodtouch6557** [comment]
> 那么，如果有些整合包包含的模组下载链接失效了咋办

整合包自己的问题，我们也没办法，只能等作者更新

**Comment by iPodtouch6557** [comment]
无法复现，正式版2.6.12搜不到

**Comment by XiaoQiAWA** [comment]
> 无法复现，正式版2.6.12搜不到

![image](https://github.com/Hex-Dragon/PCL2/assets/154889886/46b8ecfc-5ee4-4576-af3a-980058ee0078)
我这边可以复现，版本写的是最新快照版2.6.12

**Comment by XiaoQiAWA** [comment]
> 无法复现，正式版2.6.12搜不到

可能要特定的模组，可是它太大了，上传不了

**Comment by WorldHim** [comment]
疑似与 #3041#issuecomment-1872504681 重复

**Comment by iPodtouch6557** [comment]
> 可能要特定的模组，可是它太大了，上传不了

反正我这不行（叹
名称我就用的这个，前半段就搜出不来了

**Comment by XiaoQiAWA** [comment]
> 疑似与 [#3041 (comment)](https://github.com/Hex-Dragon/PCL2/issues/3041#issuecomment-1872504681) 重复，应为 cf api 问题

但是我这边是1.20.1高版本

**Comment by WorldHim** [comment]
> 但是我这边是1.20.1高版本

如果是 api 问题就与版本无关

**Comment by LTCatt** [comment]
与 #3041 实质重复
