### ISSUE TITLE
新添加一个 EventType 以支持直接在自定义主页文件里切换登录方式

### ISSUE THREAD

**Issue by SuoHouDaiShi** [Hex-Dragon/PCL2#3057]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

可以像这么写：
"EventType"="切换登录方式" "EventData"="仅正版登录|Littleskin登录"

#3034 Collaborator 让我提的（）

### 原因

我这个整合包作者是真的不想让玩家点进版本设置去切换，搞不好出什么幺蛾子不得是我的事……

**Comment by LTCatt** [comment]
暂不考虑，强行切换到版本没配置过的登录方式会炸，切换已配置的登录方式那为啥不直接在首页左侧选呢……
要从自定义主页里传入一个登录方式配置还是有点太折腾了（
