### ISSUE TITLE
PCL快照版LWJGL错误（？）

### ISSUE THREAD

**Issue by XD19193** [Hex-Dragon/PCL2#3058]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我们目前也不清楚这是什么BUG,只知道类似情况报错十分一致,并且出现LWJGL字眼
这个BUG可以说是。。。额,千遍万化？
正式版PCL与官方启动器与HMCL全部可以正常启动
今天可能快照版进得去MOD版进不去其他的
可能明天就变成快照版全报废或者全都进得去
尝试过修复LWJGL以及一切我们寻找到的办法，甚至重装系统
在外网发现类似报错案例，但是对我的修复完全没有任何帮助

### 重现步骤

0，我们也不知道怎么复现，或者说我什么也没做他就出现了（？）
---接下来是我启动的步骤---
1,正版登录
2,启动
3,游戏报错/今天这个版本可以进去了
    3,1 进不去
        3.1.1出现内容一样的报错
        3.1.2出现乱码，然后闪退，出现报错不同的LOG（小概率事件，我们目前仅遇见两次）
    3.2进得去
        3.2.1进得去：可以部分游戏，forge无法正常加载
        3.2.2进得去：可以完全正常游戏，如果安装OP在游戏内F3可能会闪退

### 日志与附件

[错误报告-2023-12-31_13.52.12.zip](https://github.com/Hex-Dragon/PCL2/files/13800393/-2023-12-31_13.52.12.zip)
今日的BUG报错，之前也试过其他各种其他操作，所以启动器记录有点乱
其他所有的报错文件跟他如出一辙
这次启动的是1.20.4纯净版
[新建文本文档.txt](https://github.com/Hex-Dragon/PCL2/files/13800398/default.txt)
我们自己整理的一些类似情况

**Comment by WorldHim** [comment]
hmcl 也会复现说明不是 pcl 问题。

**Comment by XD19193** [comment]
我说的是除了PCL快照版其他的启动器一切都正常不是说

**Comment by XD19193** [comment]
网上找到的其他参考案例修复方法对我们都没用，而且求助过很多人了，根本没用

**Comment by WorldHim** [comment]
> 我说的是除了PCL快照版其他的启动器一切都正常不是说

原版也会有问题吗？
先试试换个 java

**Comment by XD19193** [comment]
哥你倒是看看我反馈啊，只要是他能启动的全部都有可能（每天随机一次）有问题，所有办法都试过了,JAVA都换过800次了，我们这个问题跟网上找到的还不完全一样

**Comment by WorldHim** [comment]
> 哥你倒是看看我反馈啊，只要是他能启动的全部都有可能（每天随机一次）有问题，所有办法都试过了,JAVA都换过800次了，我们这个问题跟网上找到的还不完全一样

你已经启动了的游戏有 90% 不是 pcl 的问题。
我能给出的解决方案无非换 java，换驱动，重装，换电脑。
而且我也复现不了 bug，我也没办法

**Comment by XD19193** [comment]
不是，怎么说呢，可能今天能启动MOD跟纯净版启动不了整合包，明天可能就变成了能启动整合包跟纯净版启动不了MOD版

**Comment by XD19193** [comment]
而且这个问题只在PCL快照版出现，PCL正式版都没有出现过

**Comment by WorldHim** [comment]
> 而且这个问题只在PCL快照版出现，PCL正式版都没有出现过

你要是觉得是快照版的问题我就先挂着看看其他人怎么说吧

**Comment by Pigeon0v0** [comment]
我觉得只是凑巧你碰到的都用的快照版...

实际上正式版这种情况我也碰到不少，但一直比较玄学

你可以试试看再次碰到这个问题的时候让他用别的启动器试试，同一个核心同一个 Java

**Comment by rumengchuxing062** [comment]
比对了你提供的json版本文件和官版json文件，发现其大小不一致，怀疑是网络问题导致json不完整
![image](https://github.com/Hex-Dragon/PCL2/assets/110439412/01c96dce-052e-4979-a291-563416a94fba)
带（2）的是你提供的json，另一个为官版

**Comment by rumengchuxing062** [comment]
经过反复测试，无论是你提供的json还是官版json都可以正常启动
Microsoft OpenJDK17没有出现任何问题，可否告知你使用的Java版本，最好能提供无法启动的Java

**Comment by rumengchuxing062** [comment]
如果日志没错的话，你需要更新一下你的PCL版本然后再次启动，你使用的PCL是2.2.10版，最新版是2.6.13

**Comment by XD19193** [comment]
官网下载的JAVA21

**Comment by rumengchuxing062** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/110439412/5e03ec84-db8a-4c91-a003-0c076ad54ca1)

**Comment by XD19193** [comment]
之前试过，更新的最新版，但是更新后仍然出现问题，重装后我也懒得更新了

**Comment by rumengchuxing062** [comment]
是Oracle JDK 还是 Oracle OpenJDK
如果是前者，可以考虑切到OpenJDK，并将版本降到17

**Comment by rumengchuxing062** [comment]
因为这个问题有点特殊，最好是你使用的Java打包发过来

**Comment by XD19193** [comment]
百度云盘正在上传

**Comment by XD19193** [comment]
链接：https://pan.baidu.com/s/1Lj5dXDXfj3jfMYE5rOLivw 
提取码：ujy6

**Comment by rumengchuxing062** [comment]
稍等

**Comment by rumengchuxing062** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/110439412/fa37c66e-a50a-4880-beaf-ef3a1e44a45b)
百度网盘除了慢貌似没有特点了
https://www.wenshushu.cn/
要不用这个吧

**Comment by rumengchuxing062** [comment]
https://www.wenshushu.cn/
要不用这个？百度太慢了。。。

**Comment by XD19193** [comment]
https://f.wss.ink/f/d1fnlyuk5w8 复制链接到浏览器打开
发过去了

**Comment by rumengchuxing062** [comment]
![Uploading image.png…]()
成功跌破0B/s

**Comment by rumengchuxing062** [comment]
成功跌破0B/s

**Comment by XD19193** [comment]
惨哈哈哈哈

**Comment by rumengchuxing062** [comment]
经过连续测试仍未出现任何问题，该bug无法复现

**Comment by XD19193** [comment]
麻了，遇见无解的玩应了

**Comment by rumengchuxing062** [comment]
3.1.2出现乱码，然后闪退，出现报错不同的LOG（小概率事件，我们目前仅遇见两次）
日志是否有留档，发我一下

**Comment by XD19193** [comment]
没有，这个BUG12号左右就发现了，中途电脑还经历过一次重装系统，已经找不到了

**Comment by rumengchuxing062** [comment]
CPU RAM 显卡 以及驱动版本和操作系统信息也提供给我

**Comment by rumengchuxing062** [comment]
有没有修改过jvm参数

**Comment by XD19193** [comment]
没有任何自己改过的

**Comment by rumengchuxing062** [comment]
只能看看硬件能不能从这里找到突破口了，如果都没问题的话可以宣告无解了

**Comment by rumengchuxing062** [comment]
Minecraft 是别人导出的还是自己下的

**Comment by XD19193** [comment]
MIC Windows10家庭中文版
版本：10.0.19045版本19045
系统类型：基于X64
处理器:intel（R）core(TM)i7-9740H CPU@2.60GHz 2592MH

**Comment by rumengchuxing062** [comment]
还是一直用的21

**Comment by rumengchuxing062** [comment]
问题很玄学

**Comment by XD19193** [comment]
电脑上之前用的好好地JAVA7,JAVA8,JAVA17,JAVA18也全部报废

**Comment by rumengchuxing062** [comment]
镜像是不是官版（从microsoft官网下载或者使用msdn）

**Comment by XD19193** [comment]
不是镜像，电脑是笔记本，出厂自带了个正版，我是直接有个本地重置选项重置的

**Comment by XD19193** [comment]
优先官方下载

**Comment by rumengchuxing062** [comment]
你可能需要重新安装操作系统（不要选重置计算机或者全新启动，直接用镜像重新安装）

**Comment by rumengchuxing062** [comment]
这类问题已经超出了社区支持范围了

**Comment by rumengchuxing062** [comment]
你可以去learn.microsoft.com寻求帮助

**Comment by WorldHim** [comment]
还是把这个问题转到 discussions 去吧。。issue 里就别聊了

**Comment by XD19193** [comment]
好的，感谢帮助

**Comment by rumengchuxing062** [comment]
@WorldHim 问题已经超出社区支持范围，bug无法复现且没有合适解决办法，麻烦关闭这个Issue
