### ISSUE TITLE
[BUG] 未成功识别部分 MOD 的前置模组

### ISSUE THREAD

**Issue by SuoHouDaiShi** [Hex-Dragon/PCL2#3059]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如图
![图片](https://github.com/Hex-Dragon/PCL2/assets/119282947/625f67c5-dc8e-4fd0-b2bc-64facb170fba)
未正常识别 ModernUI 需要的前置模组 Forge Config API Port

### 重现步骤

1.在模组下载页中搜索 ModernUI，来源改成 Modrinth
2.BUG 出现

### 日志与附件

![图片](https://github.com/Hex-Dragon/PCL2/assets/119282947/f2412453-3ac1-4cb1-9971-969ac7e85c7a)
### 需要日志请回复，看到了会传

**Comment by rumengchuxing062** [comment]
麻烦提交日志
![image](https://github.com/Hex-Dragon/PCL2/assets/110439412/56dbdd75-5192-4eba-ad53-4b783fd792e9)
检查你的PCL版本，2.6.13可以识别到依赖

**Comment by SuoHouDaiShi** [comment]
> 麻烦提交日志 ![image](https://private-user-images.githubusercontent.com/110439412/293505579-56dbdd75-5192-4eba-ad53-4b783fd792e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwMjY1MzYsIm5iZiI6MTcwNDAyNjIzNiwicGF0aCI6Ii8xMTA0Mzk0MTIvMjkzNTA1NTc5LTU2ZGJkZDc1LTUxOTItNGViYS1hZDUzLTRiNzgzZmQ3OTJlOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjMxMjMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIzMVQxMjM3MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYzhhNzc4MmFkZTIxMDg1ZTI3YzljMWUzMzc2NDM1MGRjZjk3NDUyYjNjNmMxNWQ1ZTNlNmRiMzNlN2FkZGU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6T4hWJvAkWvYq9qld8Gc0sj5gyOmIM4hHoLpYAf-u1U) 检查你的PCL版本，2.6.13可以识别到依赖

稍等 传一下 顺带更新 PCL

**Comment by rumengchuxing062** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/110439412/fe7328fb-c792-466e-bb1e-db3e95dc7049)
根据MC百科相关信息
该依赖仅适用于安装了Fabric/Quilt加载器的Minecraft版本，推测Forge无需安装，1.20.1一下的版本只有基于Forge的版本，因此推测1.20.1一下版本无需安装，并非启动器问题

**Comment by SuoHouDaiShi** [comment]
> ![image](https://private-user-images.githubusercontent.com/110439412/293505657-fe7328fb-c792-466e-bb1e-db3e95dc7049.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwMjY3NDIsIm5iZiI6MTcwNDAyNjQ0MiwicGF0aCI6Ii8xMTA0Mzk0MTIvMjkzNTA1NjU3LWZlNzMyOGZiLWM3OTItNDY2ZS1iYjFlLWRiM2U5NWRjNzA0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjMxMjMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIzMVQxMjQwNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hODU4YWVkZTM2MDE4ZDgxZGRmNDFkODlmZDk4MmY1MmViNzk3ZTYzN2IyOGIzNzNhMWZhYWYxYzk2YjQ1OTRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NW0MeHFgmNFazYOjFS09wqcLfpoCuovBKVEFm3opqAw) 根据MC百科相关信息 该依赖仅适用于安装了Fabric/Quilt加载器的Minecraft版本，推测Forge无需安装，1.20.1一下的版本只有基于Forge的版本，因此推测1.20.1一下版本无需安装，并非启动器问题

我这个就是 Fabric 版本啊（）

**Comment by rumengchuxing062** [comment]
@SuoHouDaiShi 抱歉PCL快照版没有2.6.13版本
以及你可以看看PCLmod列表下面的字
有注明是Forge还是Fabric
![image](https://github.com/Hex-Dragon/PCL2/assets/110439412/b2190b29-af1d-46e9-8f34-8c0507dd3572)
1.20及以下的版本没有适用于Fabric/Quilt加载器得Mod版本
所以1.20及以下的版本无需安装此依赖

**Comment by SuoHouDaiShi** [comment]
> @SuoHouDaiShi 抱歉PCL快照版没有2.6.13版本 以及你可以看看PCLmod列表下面的字 有注明是Forge还是Fabric ![image](https://private-user-images.githubusercontent.com/110439412/293505839-b2190b29-af1d-46e9-8f34-8c0507dd3572.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwMjY5MzAsIm5iZiI6MTcwNDAyNjYzMCwicGF0aCI6Ii8xMTA0Mzk0MTIvMjkzNTA1ODM5LWIyMTkwYjI5LWFmMWQtNDZlOS04ZjM0LThjMDUwN2RkMzU3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjMxMjMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIzMVQxMjQzNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZDM3OTg4ODZiNDgwMWVhZTM0MzU0NjEzYTM5ZWI1NjkwMWIxZjk3MjRlNzkzNzRmYmM2MmRmMWYxOTk5MTA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NSpa7nEdVKhnWO12MCNQcwyanQWrOceNggNTuL64WpA) 1.20及以下的版本没有适用于Fabric/Quilt加载器得Mod版本 所以1.20及以下的版本无需安装此依赖

我是 1.20.1+Fabric，这个模组要装的（）

**Comment by rumengchuxing062** [comment]
1.20.1不是有识别么

**Comment by rumengchuxing062** [comment]
那个前置mod不就是吗

**Comment by SuoHouDaiShi** [comment]
那估计就是我网络问题了，关了（
