### ISSUE TITLE
主页预设选项显示错误

### ISSUE THREAD

**Issue by JingHai-Lingyun** [Hex-Dragon/PCL2#3061]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我的主页是 **Light-Beacon 新闻主页** 但是设置里显示的是 **你知道吗？**

### 版本
Release 2.6.12（311.50）

### 重现步骤

任意设置非 **你知道吗？** 主页之后重启 PCL
查看预设下拉选项框，变为 **你知道吗？**

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13801966/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/13801967/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/13801963/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/13801964/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/13801965/Log5.txt)

**Comment by JingHai-Lingyun** [comment]
回看了下 https://github.com/Hex-Dragon/PCL2/issues/3021#issuecomment-1868227078 也发现此问题

**Comment by youzi-2333** [comment]
怀疑是 `UiCustomPreset` 出了问题，但是全局搜索只有一个结果，看看龙猫咋说
