### ISSUE TITLE
--memory参数只在以管理员身份运行时有效

### ISSUE THREAD

**Issue by allMagicNB** [Hex-Dragon/PCL2#3062]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

不用管理员身份运行会报错如图
![image](https://github.com/Hex-Dragon/PCL2/assets/116283787/67eb1091-2c35-45a5-83f3-212ed6f442e7)
如果是真静默运行，那么报错不该有提示框，应该直接加个提权UAC申请

### 原因

没有管理员权限时会报错，无法执行优化，不如把报错换成UAC申请

**Comment by youzi-2333** [comment]
感觉不太可能实现，提权一般是重新启动应用程序，要是出现别的问题导致循环启动就麻烦了（类似递归调用），得加个参数判断是不是重启的……目前暂时没搜到重复 issue

建议标题改为：

```md
使用 `--memory` 参数进行内存优化时自动提权
```

### 技术信息

https://github.com/Hex-Dragon/PCL2/blob/fa054d9a9e3b44d592a6dacb84912fa8e25cabb7/Plain%20Craft%20Launcher%202/Application.xaml.vb#L35-L48

将以上代码中第 `36` 行后面插入：
```vb.net
If Not IsAdmin() Then '判断权限
    If e.Args(1).StartsWith("--restart") Then
        '重启了权限还是不够，直接毙了
        Environment.Exit(-1)
    RunAsAdmin("--memory --restart") '这是第一次启动，给它提个权试试
```

按照 author 的说法，`--memory` 是静默优化内存，因此第 `41` 行的弹窗应该也要改掉……具体看龙猫觉得咋改比较好

**Comment by allMagicNB** [comment]
> 感觉不太可能实现，提权一般是重新启动应用程序，要是出现别的问题导致循环启动就麻烦了（类似递归调用），得加个参数判断是不是重启的……目前暂时没搜到重复 issue
> 
> 建议标题改为：
> 
> ```
> 使用 `--memory` 参数进行内存优化时自动提权
> ```
> 
> ### 技术信息
> https://github.com/Hex-Dragon/PCL2/blob/fa054d9a9e3b44d592a6dacb84912fa8e25cabb7/Plain%20Craft%20Launcher%202/Application.xaml.vb#L35-L48
> 
> 将以上代码中第 `36` 行后面插入：
> 
> ```vbnet
> If Not IsAdmin() Then '判断权限
>     If e.Args(1).StartsWith("--restart") Then
>         '重启了权限还是不够，直接毙了
>         Environment.Exit(-1)
>     RunAsAdmin("--memory --restart") '这是第一次启动，给它提个权试试
> ```
> 
> 按照 author 的说法，`--memory` 是静默优化内存，因此第 `41` 行的弹窗应该也要改掉……具体看龙猫觉得咋改比较好

可以不用重启的，我记得可以调用某个API

**Comment by rumengchuxing062** [comment]
建议插个runas

**Comment by rumengchuxing062** [comment]
这个应该算bug吧，有没有谁把优化标签去掉换成bug

**Comment by allMagicNB** [comment]
> 建议插个runas

呃呃呃这个真没法用
![image](https://github.com/Hex-Dragon/PCL2/assets/116283787/e2ef96d6-f795-4ae1-b1ce-d22516308887)

**Comment by allMagicNB** [comment]
> 这个应该算bug吧，有没有谁把优化标签去掉换成bug

不是bug

**Comment by LTCatt** [comment]
这个提示就是为了指导使用 -memory 参数的使用者进行正确配置的，没有必要修改 =。=

**Comment by youzi-2333** [comment]
> 这个应该算bug吧，有没有谁把优化标签去掉换成bug

这个不是 bug，内存优化本身就是要管理员权限的，这是对于没权限处理方式的优化
