### ISSUE TITLE
打开启动器时检测同级目录下是否有modpack.zip，有则自动安装整合包

### ISSUE THREAD

**Issue by FortyTwoCn** [Hex-Dragon/PCL2#3066]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

望启动PCL2时候检测同级目录下是否有modpack.zip有则自动安装整合包

### 原因

让一些纯电脑小白更方便的安装整合包

**Comment by rumengchuxing062** [comment]
感觉没有必要，另外我觉得如果要这么改应该改成指定目录比如PCL\Modpacks

**Comment by rumengchuxing062** [comment]
并且这个百度就知道了，而且如果忘记删了就会执行二次安装

**Comment by hejiehao** [comment]
~~这听起来有点像 HMCL~~

**Comment by JingHai-Lingyun** [comment]
呃 HMCL 是支持如果同目录下有 Modpack.zip 就安装的
看看 PCL 也装上？

**Comment by rumengchuxing062** [comment]
如果要加的话只用Modpack.zip这个文件名也太绝对了

**Comment by rumengchuxing062** [comment]
建议改成PCL\ModPacks文件夹

**Comment by rumengchuxing062** [comment]
@youzi-2333 在吗，来改下标签

**Comment by allMagicNB** [comment]
我觉得应该是每次启动时检测某个文件夹有没有整合包，然后弹出提示框询问要不要安装……

**Comment by rumengchuxing062** [comment]
但是这样一个一个跳不太可能
我觉得应该是有一个页面来管理这个文件夹，每个ModPack都可以选择安装或删除
就看龙猫会不会做了
话说在座的各位都没有权限改label吗

**Comment by allMagicNB** [comment]
> 但是这样一个一个跳不太可能 我觉得应该是有一个页面来管理这个文件夹，每个ModPack都可以选择安装或删除 就看龙猫会不会做了 话说在座的各位都没有权限改label吗

凌云有

**Comment by LTCatt** [comment]
直接把整合包文件拖进 PCL 窗口就能安装了，我没想到这种功能有什么使用场景？

**Comment by JingHai-Lingyun** [comment]
> 直接把整合包文件拖进 PCL 窗口就能安装了，我没想到这种功能有什么使用场景？

e.g. HMCL 同样支持，这样在发送给别人或当服务器官方端时能直接安装
不过总感觉在 #98 做完后再做比较好...

**Comment by Blalala6868** [comment]
> 直接把整合包文件拖进 PCL 窗口就能安装了，我没想到这种功能有什么使用场景？

极致体积的傻瓜式懒人包，因为整合包的体积要比无论再怎么压缩的普通懒人包的体积都要小

![image](https://github.com/Hex-Dragon/PCL2/assets/85837864/7c3e031c-8df5-4e57-8a42-de6c6e7923fd)
