### ISSUE TITLE
下载->Mod->搜索Mod->版本 输入框会出现渲染错误

### ISSUE THREAD

**Issue by allMagicNB** [Hex-Dragon/PCL2#3067]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/Hex-Dragon/PCL2/assets/116283787/38a4228a-e720-4403-ae41-e002dedd7572)
（检索框移到了中间且未与候选框对齐）
![image](https://github.com/Hex-Dragon/PCL2/assets/116283787/b1598667-a578-4a42-95ef-4c6038f13791)
（检索框不完整）

### 重现步骤

(1)切到Mod下载页面
![image](https://github.com/Hex-Dragon/PCL2/assets/116283787/4091a100-9d54-4885-9a4d-f344fd83fa89)
(2)①点击搜索框右边的展开小按钮，输入“1”（现所有版本号都是1开头），出现输入框边框不完整
![image](https://github.com/Hex-Dragon/PCL2/assets/116283787/f29b20cd-4e0f-456a-86b5-dac2e2ecb892)
②输入一个真实存在的版本，点击搜索框右边的展开小按钮，直接按删除键删除输入框内容，出现位置错误
![image](https://github.com/Hex-Dragon/PCL2/assets/116283787/205554dd-4ee3-4da1-a35a-ef5e45cf957e)

### 日志与附件

显示错误和日志无关，无需日志

**Comment by JingHai-Lingyun** [comment]
日志还是发来吧看动画

**Comment by allMagicNB** [comment]
> 日志还是发来吧看动画

啊这，等我下

**Comment by allMagicNB** [comment]
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13804557/Log1.txt)
正式版 2.6.12（311.50）

**Comment by hejiehao** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/98140773/907f8085-971b-4d5e-b109-71b52617234a)
![image](https://github.com/Hex-Dragon/PCL2/assets/98140773/c861258e-6815-4a61-8585-3de14291b3bd)
我这里也复现了

**Comment by WorldHim** [comment]
是否与 #2982 实质相同🤔

**Comment by allMagicNB** [comment]
> 是否与 #2982 实质相同🤔

不太一样（虽然 #2982 我也遇到过）
但是我这概率比他大（目前仍未遇到复现失败）

**Comment by allMagicNB** [comment]
> 是否与 #2982 实质相同🤔

不太一样 ～虽然 #2982 我也遇到过～
但是我这概率更高，现在能稳定复现

**Comment by JingHai-Lingyun** [comment]
> 是否与 https://github.com/Hex-Dragon/PCL2/issues/2982 实质相同🤔

两个控件...

**Comment by allMagicNB** [comment]
~才发现两个图片的解释搞反了233~

**Comment by allMagicNB** [comment]
C8E1-2894-7178-8666

**Comment by allMagicNB** [comment]
隐藏主题解锁
C8E1-2894-7178-8666

**Comment by allMagicNB** [comment]
C8E1-2894-7178-8666

**Comment by iPodtouch6557** [comment]
回复不会很及时，是人工的，请耐心等待

**Comment by allMagicNB** [comment]
> 回复不会很及时，是人工的，请耐心等待

虽然但是，我从早上七八点等到现在，快9个小时了

**Comment by iPodtouch6557** [comment]
> > 回复不会很及时，是人工的，请耐心等待
> 
> 虽然但是，我从早上七八点等到现在，快9个小时了

几天也有可能{}

**Comment by burningtnt** [comment]
获取隐藏主题又不是啥“PCL2 有严重后门，可导致黑客入侵”的急事

**Comment by LTCatt** [comment]
你的解锁码：tMMjc/YebbE4WlEhz1w7feFaDoPXuM3n
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
