### ISSUE TITLE
启动时等待窗口出现时启动其他Java软件会被检测为启动完毕

### ISSUE THREAD

**Issue by qianmo2233** [Hex-Dragon/PCL2#3068]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

问题如题

对于游戏窗口的识别存在问题

### 重现步骤

1、点击启动游戏
2、在等待游戏窗口出现时启动其他带有窗口的Java
软件（图中是IDEA）

### 日志与附件

<img width="361" alt="71abe29bc0578b22f176e3c6e3d47489" src="https://github.com/Hex-Dragon/PCL2/assets/62180110/97e25f75-7552-4a17-8232-bd860b3ffb78">

**Comment by burningtnt** [comment]
又是一个仅根据进程文件名检测所导致的问题……

**Comment by qianmo2233** [comment]
看到了说是没法修，就关了

也不是什么大问题

**Comment by JingHai-Lingyun** [comment]
欸 如果启动时检测窗口 Title 包含 `Minceraft {version}` 或者为 `启动器里的自定义 Title` 的话是不是可以做到识别是否是 MC 窗口

**Comment by burningtnt** [comment]
> 欸 如果启动时检测窗口 Title 包含 Minceraft {version} 或者为 启动器里的自定义 Title 的话是不是可以做到识别是否是 MC 窗口

…… 自定义 Title 也是靠检测进程 exe 文件名来找到 Minecraft 窗口的

**Comment by qianmo2233** [comment]
> 欸 如果启动时检测窗口 Title 包含 `Minceraft {version}` 或者为 `启动器里的自定义 Title` 的话是不是可以做到识别是否是 MC 窗口

那要约定格式了，启动器应该是不好控制Minecraft会是什么标题

**Comment by JingHai-Lingyun** [comment]
PCL 启动器支持自定义标题来着
原版就是 `Minecraft {version}`（或包含其）

**Comment by WorldHim** [comment]
> 欸 如果启动时检测窗口 Title 包含 `Minceraft {version}` 或者为 `启动器里的自定义 Title` 的话是不是可以做到识别是否是 MC 窗口

https://github.com/Hex-Dragon/PCL2/issues/3052#issuecomment-1872840019
