### ISSUE TITLE
增加下载暂停和下载断点续传

### ISSUE THREAD

**Issue by ZLXL1234** [Hex-Dragon/PCL2#3069]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

1.增加暂停功能，可以让用户在发现下载速度慢或者卡顿时切换网络、镜像源，或者改变下载并发线程或下载限速
2.支持断点续传，在PCL运行时间中自动保存中断下载的文件的进度，而不是直接报错后全部重新下载

### 原因

这项优化将使我能够更方便下载游戏，模组或整合包（特别那些大整合包）
如果没有这项优化，当遇到网络不稳定导致下载中断时，都必须重新开始整个下载过程，这不仅浪费时间，而且当下载的文件较大时，这种重复下载会极大地影响用户体验。优化后可以让任务因故中断后，无需从头开始，直接从断点继续下载，提高下载效率

**Comment by ZLXL1234** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/149988734/a4263be3-638d-4fd4-811b-00ec1e112762)
比如这样
~~粗略的ps技术~~

**Comment by ZLXL1234** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/149988734/cf31ea8e-ab23-420d-a3bd-acc0bc3e7384)
比如这样
~~粗略的ps技术~~

**Comment by WForst-Breeze** [comment]
金数据时此内容曾被提及，但当时被拒绝，看看龙猫现在怎么想

**Comment by LTCatt** [comment]
技术上极难实现，不考虑，抱歉
