### ISSUE TITLE
1.20 Fabric 0.15.3版本的OptiFine-Pre5名称错误

### ISSUE THREAD

**Issue by BringBackMC** [Hex-Dragon/PCL2#3070]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在Minecraft 1.20的Fabric版本中的OptiFine名称被错误的写成了MalibrewLib
并且进入该Mod的详情页面提示远程服务器返回错误
但在1.20.1及以上和1.19.4及以下版本没有该问题
问题出现在PCL的2.6.12版本中

### 重现步骤

1、安装1.20 Fabric的最新版本并安装OptiFine和OptiFabric的最新版本
2、版本设置
3、Mod管理
Mod管理中的OptiFine名称错误

### 日志与附件

a

**Comment by kong-que-dnf123** [comment]
emmm······
这个代替了原Opt的MalibrewLib甚至他的Curseforge反馈的也是404错误.......
![image](https://github.com/Hex-Dragon/PCL2/assets/120994373/ad490fb2-d306-4c43-a5fc-ff44aa174bf0)

[这个是MalibrewLib的modmc界面](https://www.mcmod.cn/class/2298.html)
还有这玩意是一个......Fabric的小插件库集合？
![image](https://github.com/Hex-Dragon/PCL2/assets/120994373/b537f21d-2ca7-4c69-9c88-7288cb1fadce)

---------------------------------------------------------------------------------------------------------------------------------------------
_又及：咋自己关了？_

**Comment by BringBackMC** [comment]
Bot说我和#3041重复
