### ISSUE TITLE
设置：mod管理的mod标题显示文件名

### ISSUE THREAD

**Issue by xingchen-Forever** [Hex-Dragon/PCL2#3073]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

mod列表的旧版红石灯和文件名格式，我喜欢这种风格，因为所有的mod我会自己备注一些东西以及我干嘛用的，现在的新版mod列表会看起来很混乱（文件名变成了灰色小字，以及一些封面，描述等等），虽然可能大多数人喜欢这种风格，但是请为其添加一个切换开关，因为这个问题，我不得不使用旧版（2.6.10）并禁止更新

### 原因

这项优化让我可以更方便地管理我的mod。
如果没有这项优化，这使得mod不够直观，让操作变得很麻烦。

**Comment by LTCatt** [comment]
会考虑加入在标题显示文件名的设置

**Comment by LTCatt** [comment]
加了个设置。
![image](https://github.com/user-attachments/assets/2c3038ec-7e0d-4d6d-bdeb-538065d7a265)
---
![image](https://github.com/user-attachments/assets/e08832d0-e4bc-468d-9702-56e35e15e322)
