### ISSUE TITLE
mod下载中，Neoforge下载源和Fabric下载源未区分

### ISSUE THREAD

**Issue by iPodtouch6557** [Hex-Dragon/PCL2#3074]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如题，看图感受一下
<img width="525" alt="image" src="https://github.com/Hex-Dragon/PCL2/assets/118656946/bf5d567b-79d9-4b2f-9bc9-acf87e512fe5">
<img width="638" alt="image" src="https://github.com/Hex-Dragon/PCL2/assets/118656946/12cead23-6c7a-47bd-a2f5-bacd5dc30a01">
其实我知道neoforge自动下载源没做出来，但是我希望分离出来，以便误导用户，省去一些麻烦

### 重现步骤

1、mod 分类选择  _(例如)_  1.20.4 fabric
2、找到  _(例如)_  Appleskin，
3、bug复现

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/13829666/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/13829668/Log3.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13829669/Log1.txt)

**Comment by WForst-Breeze** [comment]
NeoForge 做了肯定要一口气把 Quilt 也做了，看看龙猫怎么想吧

**Comment by iPodtouch6557** [comment]
区分一下，打个前站就行了，应该不难吧……
