### ISSUE TITLE
“lazy-language-loader”mod 下载资源工程图标失败

### ISSUE THREAD

**Issue by kong-que-dnf123** [Hex-Dragon/PCL2#3075]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述
如题所示——

`下载资源工程图标失败（https://media.forgecdn.net/avatars/thumbnails/432/64/64/256/637669432467479015.png）→ 远程服务器返回错误: (404) 未找到。
`

```
[20:54:10.425] 下载资源工程图标失败（https://media.forgecdn.net/avatars/thumbnails/432/64/64/256/637669432467479015.png）：直接下载文件失败（https://media.forgecdn.net/avatars/thumbnails/432/64/64/256/637669432467479015.png）。
→ 远程服务器返回错误: (404) 未找到。
   在 PCL.ModNet.NetDownload(String Url, String LocalFile)
   在 PCL.MyCompItem.LogoLoader(String Address)
   在 System.Net.WebClient.DownloadFile(Uri address, String fileName)
   在 PCL.ModNet.NetDownload(String Url, String LocalFile)
错误类型：System.Net.WebException
```
以下是PCL图片表现
![image](https://github.com/Hex-Dragon/PCL2/assets/120994373/eab3abf4-0191-45dc-8319-fdb270befcf8)
![image](https://github.com/Hex-Dragon/PCL2/assets/120994373/7f0972a4-4ca3-4ad5-832d-fb6245566506)
以下是modmc和Curseforge的表现
![image](https://github.com/Hex-Dragon/PCL2/assets/120994373/99bfcb46-1f8a-4b8e-8a4d-c9e93c5b5923)
![image](https://github.com/Hex-Dragon/PCL2/assets/120994373/c3c3caa1-d07e-4d49-bcf6-526787e2da5e)

### 重现步骤

1、点击“下载” “Mod下载”
2、搜索“lazy-language-loader”
3、加载结束，调试信息弹出错误
4（追加）、点击进入此mod，调试信息同样报错

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13830031/Log1.txt)

**Comment by JingHai-Lingyun** [comment]
这是 CF 上的 `https://media.forgecdn.net/avatars/432/256/637669432467479015.png`
这是日志的   `https://media.forgecdn.net/avatars/thumbnails/432/64/64/256/637669432467479015.png`
对比发现启动器多加了个 `thumbnails` 和 `/64/64` 其余无异
貌似是 forgecdn 改了语法？
