### ISSUE TITLE
正版登录1.20.1 启动失败

### ISSUE THREAD

**Issue by ChaosZ7** [Hex-Dragon/PCL2#3077]
### 检查项

- [ ] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

1.20.1版本正版登录时启动失败，但可离线登录，低版本可正版登录和离线登录都可以正常启。
<img width="598" alt="屏幕截图 2024-01-05 124258" src="https://github.com/Hex-Dragon/PCL2/assets/102021960/a4647881-6bee-4272-b34c-5a6c4f65dbcb">
[](url)

### 重现步骤

1、点击xxxx
2、往下滚，然后点击xxxx

### 日志与附件

[错误报告-2024-1-5_12.42.00.zip](https://github.com/Hex-Dragon/PCL2/files/13838064/-2024-1-5_12.42.00.zip)

**Comment by ChaosZ7** [comment]
用的笔记本电脑联线小新pro14, cpu：5800H、GPU：核显 驱动版本（最新）31.0.12044.47003。 前两天下载了amd驱动软件后才产生的问题

**Comment by JingHai-Lingyun** [comment]
启动器日志发来看看

**Comment by burningtnt** [comment]
> 启动器日志发来看看

他已经发了，我看了，就是显卡驱动报错

**Comment by burningtnt** [comment]
按照当事人的描述，难不成，正版登录和离线登录走的不是同一张显卡？

**Comment by JingHai-Lingyun** [comment]
挺奇怪的... 为啥1.20.1离线就可以呢?

**Comment by WorldHim** [comment]
> 按照当事人的描述，难不成，正版登录和离线登录走的不是同一张显卡？

就一个核显怎么会走其他显卡

**Comment by LTCatt** [comment]
这应当不是启动器的问题 :/
