### ISSUE TITLE
[PCL2预览版2.6.12-BUG]经过一番操作后 使用自定义主页的 切换页面类 按钮跳转到 MOD管理 页面会导致PCL2完全卡死

### ISSUE THREAD

**Issue by Bill233666** [Hex-Dragon/PCL2#3080]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

版本:PCL2预览版2.6.12
问题:
       起因：我想更换一下MC实例文件夹的名字。
       遇到的问题：重新起名后在自定义主页里通过 “切换页面” 类型按钮跳转到 “Mod管理” 页面时发生了致命错误，导致PCL2程序完全卡死并且报错让我反馈，只能通过任务管理器关闭PCL2进行重启。
      已知的解决方法:按正常流程，在版本设置里打开"Mod管理"。
期望:
       这个快捷按钮我很常用，而且我经常有更换文件夹名的需求，希望可以修复一下！

### 重现步骤

1、在主页新建一个按钮，类型：切换页面 ，7|2（mod管理）。
2、在版本选择页面中新添加一个包含完整我的世界实例的文件夹，确保PCL2能识别到实例文件夹里的我的世界版本，并且这个我的世界版本必须是带有MOD加载器的实例。
3、在PCL2里选择有MOD加载器版本的我的世界实例
![8](https://github.com/Hex-Dragon/PCL2/assets/103619120/84825e44-a753-4663-9b39-3c14c0399ef2)
4、返回主页
5、点击 提前在主页设置好的 "切换页面"类按钮——>"Mod管理页面"
![9](https://github.com/Hex-Dragon/PCL2/assets/103619120/20fc069c-29f9-4865-92f8-a674e122f38f)

6、开始报错！PCL2未正确打开"Mod管理"页面，而是**强制跳转**，没有进行mod文件夹的检查或识别！
![10](https://github.com/Hex-Dragon/PCL2/assets/103619120/0f2a517c-3e60-44b6-aad3-c1eaafcddffa)
![11](https://github.com/Hex-Dragon/PCL2/assets/103619120/ed65b381-4ada-4b34-92dc-be2c4f02c8c4)

7、程序完全卡死！无法点击！

完整流程图:
1.PCL2已经先识别了"D:\Minecraft\ttt\1.20.1NeoForge"文件夹下的的MC实例
![1](https://github.com/Hex-Dragon/PCL2/assets/103619120/c5858bb6-7a13-4ecf-8962-f9296b268154)
2.关闭PCL2并且给名为"ttt"的文件夹重命名成"PCL2MCinstance"
![2](https://github.com/Hex-Dragon/PCL2/assets/103619120/78244320-3b86-4666-a061-91747eb34ac6)
3.命名完成
![3](https://github.com/Hex-Dragon/PCL2/assets/103619120/e757358a-a3da-4b01-8552-5d295fe26b26)
4.打开PCL2正常显示 无效的Minecraft文件夹巴拉巴拉...
![4](https://github.com/Hex-Dragon/PCL2/assets/103619120/9bcb7cf5-3e78-442c-96ec-1239c0de6f07)
5.选择“版本选择”按钮
![5](https://github.com/Hex-Dragon/PCL2/assets/103619120/d160ea25-9dd2-4063-9b76-33dafbdad7f6)
6.添加已有文件夹
![6](https://github.com/Hex-Dragon/PCL2/assets/103619120/ab57b88b-ff72-4ea7-b832-63dafaedd2c7)
7.选择“D:\Minecraft\PCL2MCinstance\1.20.1NeoForge”
![7](https://github.com/Hex-Dragon/PCL2/assets/103619120/10426e74-70d1-43a3-97ac-73e318dbd4b3)
8.回到PCL2选择点击“1.20.1-NeoForge-47.1.84”我的世界实例（此实例完好无缺，完全可正常运行）
![8](https://github.com/Hex-Dragon/PCL2/assets/103619120/9189703b-c8aa-4c94-b877-e89311afe902)
9.回到“启动”页面，点击“主页”里的“Mod管理页面”(这是我设置的自定义主页按钮，它在我没有做这些操作的时候完全可以正常运作。具体Custom.xaml看最后的配图)
![9](https://github.com/Hex-Dragon/PCL2/assets/103619120/a839a1ac-1951-4611-a091-1a540e28d5d4)
10.本应正常显示在"Mod管理"页面里的mod全部失踪，并且弹出名为“锟斤拷烫烫烫”的错误提示窗。
![10](https://github.com/Hex-Dragon/PCL2/assets/103619120/de7b2142-faed-455c-9291-de4c537509f4)
11.点击"是"则会弹出PCL2自己的错误提示弹窗，并且程序完全卡死！
![11](https://github.com/Hex-Dragon/PCL2/assets/103619120/c73d513c-8206-4dce-bc67-e6c169b9d1d8)
这是我自定义主页的配置文件:
![12](https://github.com/Hex-Dragon/PCL2/assets/103619120/ab21a726-ed85-4647-9637-f45b068ab27e)

### 日志与附件

LOG2报错的日志（报错！）
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/13843406/Log2.txt)
LOG3修改前的日志（无报错）
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/13843417/Log3.txt)

**Comment by JingHai-Lingyun** [comment]
Log2 160 行
```
[22:34:44.704] [Control] 按下按钮：Mod管理页面
[22:34:44.707] [Control] 执行自定义事件：切换页面, 7, 2
[22:34:44.734] [Control] 切换主要页面：VersionSetup, 2
```
按下按钮后开始切换页面，随后报错（169 行）
```
[22:34:44.945] 程序出现未知错误：未将对象引用设置到对象的实例。
   在 PCL.PageVersionMod.RefreshList(Boolean ForceReload)
   在 PCL.PageVersionMod.PageOther_Loaded()
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   在 System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   在 MS.Internal.LoadedOrUnloadedOperation.DoWork()
   在 System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   在 System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   在 System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   在 System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
错误类型：System.NullReferenceException
```

---

题外话... 图片有点多... 我加载了半天还没加载好...

**Comment by LTCatt** [comment]
由自定义事件触发的强制页面跳转 **并不完全支持跳转到 Mod 管理页面** ，这个事件会强制进行跳转，所以部分页面可能会导致崩溃，由此引起的崩溃也不会修复 :/
