### ISSUE TITLE
为Mod下载页面添加自动匹配进行多选下载功能和下载后显示"已安装"功能和MOD管理页面添加自动检测更新功能

### ISSUE THREAD

**Issue by Bill233666** [Hex-Dragon/PCL2#3082]
### 检查项

- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

在Prism启动器里下载mod可以多选，并且还会显示已安装的mod。如图:
![Snipaste_2024-01-06_09-22-45](https://github.com/Hex-Dragon/PCL2/assets/103619120/f557df40-55e2-4824-903f-8bbcb645d5ad)

蓝色选中的为将要下载已选择的mod，黑色框框的为已下载mod。

![Snipaste_2024-01-06_09-27-59](https://github.com/Hex-Dragon/PCL2/assets/103619120/cfd5063a-62c4-4e0a-978b-d5947d644a13)

检测更新↑

我希望PCL2在未来有能力的话（感觉没能力）也可以增加这几项功能，这样可以帮助整合包作者快速进行整合包的制作！
要添加的功能：
1.mod下载添加多选mod下载（自动检测已选择的mc实例并进行检查是否为FORGEmod还是Fabricmod来进行自动选择下载方式）
2.mod下载后显示已下载 （通过PCL2下载的mod显示该显示已安装，其他的可以不显示，若其他实例未安装则取消显示）
3.mod管理页面的mod检查更新按钮 
### 原因

我需要这个功能来进行快速的制作整合包和防止mod的重复下载。很多人都有下载多个mod和mod更新的需求。

**Comment by zkitefly** [comment]
添加多选 Mod 下载没有相同的 Issue，不过有个类似的 Mod 一键下载 Issue: https://github.com/Hex-Dragon/PCL2/issues/2933
检测更新: https://github.com/Hex-Dragon/PCL2/issues/102

Mod 下载后显示已下载提示功能我觉得可以让龙猫看看

**Comment by LTCatt** [comment]
暂不考虑，制作难度挺高的，但相对的改善却不大……
