### ISSUE TITLE
未发布mod的显示错误

### ISSUE THREAD

**Issue by Bi2Nb9O3-Studio** [Hex-Dragon/PCL2#3084]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

PCL版本 : `Snapshot 2.6.12(310.0)` <br>
# 表现
显示为对应不正确的mod详细信息。
(如MCreator Link=>Tanky's Creatures)

![27c7ee8ea09931097c38b4001a8a59af](https://github.com/Hex-Dragon/PCL2/assets/92721357/091a2a46-65eb-4ba8-8be7-fe3fec5e34e1)

### 重现步骤

在mod文件夹中放入未在Curseforge/Modrinth发布的模组

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13849407/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/13849408/Log2.txt)

**Comment by LTCatt** [comment]
#3041
