### ISSUE TITLE
点击"关闭 minecraft"按钮使 mod 数据丢失

### ISSUE THREAD

**Issue by junugo** [Hex-Dragon/PCL2#3085]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

启动mc，然后点击 **"关闭 minecraft"** 后会导致 mod 的数据丢失（或许是因为PCL强制关闭了MC?）**~~(还是我的电脑特性)~~**
如果使用MC的退出按钮或者关闭窗口，下次打开仍然会保留mod的数据
~~我使用关闭minecraft按钮后发现我的投影配置消失了，非常气愤，一气之下把别的可能的mod全干了，然后发现只加投影mod也一样~~

### 重现步骤

1、启动1.20.1 fabric（以及一些mod）
2、在个人世界或多人服务器用mod做一些操作（如[FeyFriends](https://www.mcmod.cn/class/7417.html)添加好友，或[Litematica](https://www.mcmod.cn/class/2261.html)添加原理图，调整各类mod的配置等）
3、使用PCL关闭mc
4、再次启动mc
5、数据丢失
6、庆祝一下 **~~(能被龙猫看到已经很高兴了，不修也可以)~~ (bushi)**

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13849559/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/13849560/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/13849555/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/13849557/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/13849558/Log5.txt)

**Comment by mc-124** [comment]
游戏进程似乎还没来得及保存就被杀了，应该与PCL2无关

**Comment by mc-124** [comment]
点击游戏窗口的关闭其实游戏进程会保存配置后再关闭，但是PCL2的关闭是游戏来不及保存就被杀死了

**Comment by junugo** [comment]
> 点击游戏窗口的关闭其实游戏进程会保存配置后再关闭，但是PCL2的关闭是游戏来不及保存就被杀死了

所以可以通过更改关闭游戏的方式来使得它和关闭按钮一个效果？或者提供强制关闭和普通关闭两种方式？
在PCL里关闭一次后导致我之前的mod配置直接归零真的太**~~开心~~**悲哀了

**Comment by JingHai-Lingyun** [comment]
按理来说就算你强制关闭 MC（`taskkill` / 任务管理器）也不应导致配置文件（`/config`）或其他文件丢失吧....

**Comment by burningtnt** [comment]
数据丢失很正常，说不定那个时候你的游戏正在操作文件呢。这不是 PCL2 的问题

**Comment by mc-124** [comment]
> 点击游戏窗口的关闭其实游戏进程会保存配置后再关闭，但是PCL2的关闭是游戏来不及保存就被杀死了

这似乎做不到，minecraft没有接口去专门从外部关闭游戏，只能强制杀死

**Comment by junugo** [comment]
但是我在第一次打开并调整配置后用退出按钮关闭，第二次打开会存在更改的配置，此时使用PCL关闭，第三次打开时第一次的调整也会丢失 **~~（这使我头脑风暴）~~**
或许可以改进？（那我投进优化建议）

**Comment by burningtnt** [comment]
这不是 PCL2 的问题

**Comment by burningtnt** [comment]
请永远仅在游戏卡死时使用 PCL2 强制结束游戏，一般情况下请回到游戏主菜单，点推出游戏按钮

**Comment by junugo** [comment]
> > 点击游戏窗口的关闭其实游戏进程会保存配置后再关闭，但是PCL2的关闭是游戏来不及保存就被杀死了
> 
> 这似乎做不到，minecraft没有接口去专门从外部关闭游戏，只能强制杀死

然而使用windows的关闭窗口时会保留配置，能否使用类似C++的SendMessage(hwnd, WM_SYSCOMMAND, SC_CLOSE, 0);等方式向窗口发送关闭消息？

**Comment by mc-124** [comment]
> 但是我在第一次打开并调整配置后用退出按钮关闭，第二次打开会存在更改的配置，此时使用PCL关闭，第三次打开时第一次的调整也会丢失 **~（这使我头脑风暴）~** 或许可以改进？（那我投进优化建议）

不行的，你投了龙猫也不鸟你或拒绝

**Comment by mc-124** [comment]
> > > 点击游戏窗口的关闭其实游戏进程会保存配置后再关闭，但是PCL2的关闭是游戏来不及保存就被杀死了
> > 
> > 
> > 这似乎做不到，minecraft没有接口去专门从外部关闭游戏，只能强制杀死
> 
> 然而使用windows的关闭窗口时会保留配置，能否使用类似C++的SendMessage(hwnd, WM_SYSCOMMAND, SC_CLOSE, 0);等方式向窗口发送关闭消息？

就算实现了，PCL2的体积就上去了

**Comment by junugo** [comment]
> > 但是我在第一次打开并调整配置后用退出按钮关闭，第二次打开会存在更改的配置，此时使用PCL关闭，第三次打开时第一次的调整也会丢失 **~（这使我头脑风暴）~** 或许可以改进？（那我投进优化建议）
> 
> 不行的，你投了龙猫也不鸟你或拒绝

龙猫偷懒 ~~（bushi）~~
增加一个小型的底层事件应该不会花费太多的代码 ~~（我不知道，这不是我熟悉的C++）~~

**Comment by LTCatt** [comment]
这不是启动器导致的问题 :/

**Comment by junugo** [comment]
> 这不是启动器导致的问题 :/

自行修复会被龙猫打吗awa ~~(bushi)~~
![image](https://github.com/Hex-Dragon/PCL2/assets/115913410/2800dc76-d110-4cf8-8ab6-638ce593aaf3)

**Comment by LTCatt** [comment]
你如果有能力修复可以直接交 PR
