### ISSUE TITLE
删除mod时出错

### ISSUE THREAD

**Issue by gaipian19** [Hex-Dragon/PCL2#3088]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

报错

### 重现步骤

我在游戏版本mod页快速点击删除触发了这个bug

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13850279/Log1.txt)

**Comment by LTCatt** [comment]
请尝试在 2.6.13 中复现……

**Comment by gaipian19** [comment]
谢谢，已解决
