### ISSUE TITLE
通过maven仓库的形式保存mod, 并通过命令行参数传入modlist进行加载

### ISSUE THREAD

**Issue by lycc193** [Hex-Dragon/PCL2#3089]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

forge和fabric都支持通过命令行参数传递modlist文件 而不是 扫描version/mods/文件夹 进行加载
希望启动器添加maven仓库的读取/创建，在下载/安装整合包时 下载到仓库并转换modlist文件进行加载
详细信息在隔壁（
https://github.com/huanghongxun/HMCL/issues/2627#issue-2068718315

### 原因

相同版本的mod文件只需要下载一份，节省了下载流量和磁盘空间，同时便于整合包的mod更新

**Comment by burningtnt** [comment]
https://github.com/huanghongxun/HMCL/issues/2627

**Comment by JingHai-Lingyun** [comment]
对玩家的要求过高，并且实现了使用的人也应当很少
大概率不会做...

**Comment by LTCatt** [comment]
超出范畴了，暂不考虑，抱歉 Orz
