### ISSUE TITLE
[Bug?] 部分模组适用版本显示异常（疑似 Modrinth 特有 Bug？）

### ISSUE THREAD

**Issue by liubanlaobanzhang** [Hex-Dragon/PCL2#3091]
### 检查项

- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/Hex-Dragon/PCL2/assets/83630926/89a69ca3-84de-4514-912c-aec8fcf072d4)
如你所见，可选版本里面有 `Fabric 1.20.1` 版本，
![image](https://github.com/Hex-Dragon/PCL2/assets/83630926/e700ea66-a963-49bc-811c-00db74560e61)
但标头就是显示 `Forge 1.19` ……

### 重现步骤

1. 在下载界面进入 Mod 选项卡
2. 搜索ingameime
![image](https://github.com/Hex-Dragon/PCL2/assets/83630926/8a93fa4f-d84e-4079-8525-5d485502e27a)

……没了

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13852438/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/13852439/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/13852440/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/13852441/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/13852442/Log5.txt)

**Comment by liubanlaobanzhang** [comment]
备注：疑似 Modrinth 特有 Bug？

**Comment by burningtnt** [comment]
疑似数据源问题？

**Comment by WForst-Breeze** [comment]
稳定复现，添加筛选条件后可以显示 Fabric，而未添加时则显示 Forge
![image](https://github.com/Hex-Dragon/PCL2/assets/110760354/64affcf7-118a-46dc-a261-7d4e1f66740f)
![image](https://github.com/Hex-Dragon/PCL2/assets/110760354/de7b500e-c531-4ffc-8dc0-ac065e2473a1)
![image](https://github.com/Hex-Dragon/PCL2/assets/110760354/b8567627-dec2-4e49-8ec5-960a0ce4a275)

**Comment by liubanlaobanzhang** [comment]
对了 一个 issue 之外的小问题
这个主题在龙猫改完 BUG 之后我在这里要一下解锁码就行是吧（
![image](https://github.com/Hex-Dragon/PCL2/assets/83630926/f2f06603-e7ae-4099-8ea0-53e5dffdb566)
需要识别码吗？

**Comment by zkitefly** [comment]
> 对了 一个 issue 之外的小问题 这个主题在龙猫改完 BUG 之后我在这里要一下解锁码就行是吧（ ![image](https://private-user-images.githubusercontent.com/83630926/294745319-f2f06603-e7ae-4099-8ea0-53e5dffdb566.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2MTQ5NDgsIm5iZiI6MTcwNDYxNDY0OCwicGF0aCI6Ii84MzYzMDkyNi8yOTQ3NDUzMTktZjJmMDY2MDMtZTdhZS00MDk5LThlYTAtNTNlNWRmZmRiNTY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA3VDA4MDQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5OTJjZTJjZmE0NWQ2MWJmMDA0NmIzMTJhNjJhMmJjY2QzYjYwNWVlNmFmMGJiYjZlMzU0NGM5ODcyZDk0ZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fj07mpyJe1dmhzpEIfrT0iBJ2q3SQ6XTLuwyaxGzfDY) 需要识别码吗？

需要

**Comment by liubanlaobanzhang** [comment]
好的谢谢（

> > 对了 一个 issue 之外的小问题 这个主题在龙猫改完 BUG 之后我在这里要一下解锁码就行是吧（ ![image](https://private-user-images.githubusercontent.com/83630926/294745319-f2f06603-e7ae-4099-8ea0-53e5dffdb566.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2MTQ5NDgsIm5iZiI6MTcwNDYxNDY0OCwicGF0aCI6Ii84MzYzMDkyNi8yOTQ3NDUzMTktZjJmMDY2MDMtZTdhZS00MDk5LThlYTAtNTNlNWRmZmRiNTY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA3VDA4MDQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5OTJjZTJjZmE0NWQ2MWJmMDA0NmIzMTJhNjJhMmJjY2QzYjYwNWVlNmFmMGJiYjZlMzU0NGM5ODcyZDk0ZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fj07mpyJe1dmhzpEIfrT0iBJ2q3SQ6XTLuwyaxGzfDY) 需要识别码吗？
> 
> 需要

谢谢

**Comment by LTCatt** [comment]
看了看，Modrinth 不会把 Alpha 状态的文件支持的加载器标出来，这个 Mod 里所有 Fabric 的版本都是 Alpha 版的，所以 Modrinth 没有给出它支持 Fabric 的信息 =。=
