### ISSUE TITLE
加载 Mod 列表 UI 失败：指定的 Visual 已经是另一个 Visual 的子级或者已经是 CompositionTarget 的根

### ISSUE THREAD

**Issue by WEDFVV** [Hex-Dragon/PCL2#3092]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

打开mod管理报错

### 重现步骤

1、点击版本设置
2、mod管理

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13852612/Log1.txt)

**Comment by burningtnt** [comment]
版本为 2.6.13，可见：
```
加载 Mod 列表 UI 失败：指定的 Visual 已经是另一个 Visual 的子级或者已经是 CompositionTarget 的根。
   在 PCL.PageVersionMod.RefreshResult(List`1 Mods)
   在 PCL.PageVersionMod.LoadUIFromLoaderOutput()
错误类型：System.ArgumentException
```

**Comment by allMagicNB** [comment]
关键部分：
```
[16:03:47.829] 加载 Mod 列表 UI 失败：指定的 Visual 已经是另一个 Visual 的子级或者已经是 CompositionTarget 的根。
   在 System.Windows.Media.VisualCollection.Add(Visual visual)
   在 System.Windows.Controls.UIElementCollection.AddInternal(UIElement element)
   在 PCL.PageVersionMod.RefreshResult(List`1 Mods)
   在 PCL.PageVersionMod.LoadUIFromLoaderOutput()
错误类型：System.ArgumentException
[16:03:47.843] [Control] 普通弹窗：出现错误
加载 Mod 列表 UI 失败：指定的 Visual 已经是另一个 Visual 的子级或者已经是 CompositionTarget 的根。
   在 PCL.PageVersionMod.RefreshResult(List`1 Mods)
   在 PCL.PageVersionMod.LoadUIFromLoaderOutput()
错误类型：System.ArgumentException

是否反馈此问题？如果不反馈，这个问题可能永远无法得到解决！
```

**Comment by burningtnt** [comment]
看起来像是文档树构建的时候，有个子节点被挂到两个父下面了……

**Comment by allMagicNB** [comment]
**未复现成功**
![Screenshot_20240107_161510_youqu.android.todesk_edit_477788675845843.jpg](https://github.com/Hex-Dragon/PCL2/assets/116283787/fce5c4ea-3b63-48bf-90a4-61b3f2a966a6)


推测为点太快了？启动了两次

**Comment by SALTWOOD** [comment]
复现成功，确认不是个别现象

**Comment by allMagicNB** [comment]
issue标题不太具体，是要安装了mod再进去才会触发

**Comment by SALTWOOD** [comment]
建议改为：“**指定的 Visual 已经是另一个 Visual 的子级或者已经是 CompositionTarget 的根。**”
复现方法疑似：将**同一个**模组复制两份

**Comment by LTCatt** [comment]
> 复现方法：将**同一个**模组复制两份，然后保证两个模组文件**一个被启用一个被禁用**
> 
> > malilib-fabric-1.20.2-0.17.0.jar
> > malilib-fabric-1.20.2-0.17.0.jar.disabled

正常操作下不会出现这种情况吧……

**Comment by burningtnt** [comment]
> 正常操作下不会出现这种情况吧……除非刻意触发……

倒也不至于。如果用户在 PCL2 里先禁用了这个模组，然后忘记了，再去下载了一份，就爆炸了
还是有必要修的

**Comment by xhahello** [comment]
我在搞一个1.20.1的存档，下了两个malilib，他就报错了，但是我两个都是malilib都是启用的a

**Comment by JingHai-Lingyun** [comment]
总结：新的 UI 没法解析一个 Mod 存在了两次的情况

**Comment by iPodtouch6557** [comment]
> 复现方法：将**同一个**模组复制两份，然后保证两个模组文件**一个被启用一个被禁用**
> 
> > malilib-fabric-1.20.2-0.17.0.jar
> > malilib-fabric-1.20.2-0.17.0.jar.disabled

啊，我这么干都两三年了……就是崩了mod重装，然后也没失败

**Comment by allMagicNB** [comment]
……要么下载时检测`Mod名.jar.disabled`是否存在，存在的话提示下
要么就优化显示UI……加载每个Mod时检测同目录下有无存在同样的`Mod名.jar.disabled`（若已经是`.jar.disabled`就检测不包含`.disabled`的）

**Comment by allMagicNB** [comment]
还是有必要修的，短短几天已经有三四个issue提到的都是此事了，证明还真的会有人这么做（

**Comment by WorldHim** [comment]
> ……要么下载时检测`Mod名.jar.disabled`是否存在，存在的话提示下
> 要么就优化显示UI……加载每个Mod时检测同目录下有无存在同样的`Mod名.jar.disabled`（若已经是`.jar.disabled`就检测不包含`.disabled`的）

这个只能算是阻断 bug 发生而没有实质性的进行修复。。

**Comment by 596wjr** [comment]
> > 复现方法：将**同一个**模组复制两份，然后保证两个模组文件**一个被启用一个被禁用**
> > > malilib-fabric-1.20.2-0.17.0.jar
> > > malilib-fabric-1.20.2-0.17.0.jar.disabled
> 
> 正常操作下不会出现这种情况吧……除非刻意触发……

事实上，正常情况下更新mod不删除旧版本而是禁用旧版本就会这样...

**Comment by TanChenyu** [comment]
> > 复现方法：将**同一个**模组复制两份，然后保证两个模组文件**一个被启用一个被禁用**
> > > malilib-fabric-1.20.2-0.17.0.jar
> > > malilib-fabric-1.20.2-0.17.0.jar.disabled
> 
> 正常操作下不会出现这种情况吧……除非刻意触发……

下GTNH的附加文件时会有这个情况

**Comment by SadEPa0628** [comment]
我最近也有，严重影响使用了

**Comment by SadEPa0628** [comment]
> 我最近也有，严重影响使用了

在搜索mod的地方打了个字就卡住崩溃了

**Comment by SadEPa0628** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/120295331/f02e7a28-a117-4dd9-8fb6-d13622c4d509)

**Comment by allMagicNB** [comment]
> > 我最近也有，严重影响使用了
> 
> 在搜索mod的地方打了个字就卡住崩溃了

你这和打字没关系，就是有重复Mod

**Comment by LiteCat0905** [comment]
我有一个100%报错的方法，将Mod拖入Mod列表，之后PCL会开始加载Mod列表在加载还没出现Mod列表的时候点击返回按钮回到主页后提示该错误

**Comment by LiteCat0905** [comment]
> > 复现方法：将**同一个**模组复制两份，然后保证两个模组文件**一个被启用一个被禁用**
> > > malilib-fabric-1.20.2-0.17.0.jar
> > > malilib-fabric-1.20.2-0.17.0.jar.disabled
> 
> 正常操作下不会出现这种情况吧……除非刻意触发……

![image](https://github.com/Hex-Dragon/PCL2/assets/101038478/2d1119d5-9c11-47bb-a87b-f9bde17a03df)
有1点破防了，他现在刚输入就炸了 甚至弹框都奇怪起来了！然后PCL就崩了

**Comment by pig52** [comment]
出现该错误后如果在搜索栏搜索会直接闪退:(
应该是新版本才有的，更新前未发现此问题
[22:09:40.679] 程序出现未知错误：指定的 Visual 已经是另一个 Visual 的子级或者已经是 CompositionTarget 的根。
   在 System.Windows.Media.VisualCollection.Add(Visual visual)
   在 System.Windows.Controls.UIElementCollection.AddInternal(UIElement element)
   在 PCL.PageVersionMod.RefreshResult(List`1 Mods)
   在 PCL.PageVersionMod.SearchRun()
   在 PCL.MySearchBox.Text_TextChanged(Object sender, TextChangedEventArgs e)
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.Controls.Primitives.TextBoxBase.OnTextContainerChanged(Object sender, TextContainerChangedEventArgs e)
   在 System.Windows.Controls.TextBox.OnTextContainerChanged(Object sender, TextContainerChangedEventArgs e)
   在 System.Windows.Documents.TextContainerChangedEventHandler.Invoke(Object sender, TextContainerChangedEventArgs e)
   在 System.Windows.Documents.TextContainer.EndChange(Boolean skipEvents)
   在 System.Windows.Documents.TextRangeBase.EndChange(ITextRange thisRange, Boolean disableScroll, Boolean skipEvents)
   在 System.Windows.Documents.TextRange.ChangeBlock.System.IDisposable.Dispose()
   在 System.Windows.Documents.TextEditorTyping.DoTextInput(TextEditor This, String textData, Boolean isInsertKeyToggled, Boolean acceptControlCharacters)
   在 System.Windows.Documents.TextEditorTyping.OnTextInput(Object sender, TextCompositionEventArgs e)
   在 System.Windows.Controls.Primitives.TextBoxBase.OnTextInput(TextCompositionEventArgs e)
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   在 System.Windows.Input.InputManager.ProcessStagingArea()
   在 System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   在 System.Windows.Input.TextCompositionManager.PostProcessInput(Object sender, ProcessInputEventArgs e)
   在 System.Windows.Input.InputManager.RaiseProcessInputEventHandlers(ProcessInputEventHandler postProcessInput, ProcessInputEventArgs processInputEventArgs)
   在 System.Windows.Input.InputManager.ProcessStagingArea()
   在 System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   在 System.Windows.Input.TextCompositionManager.PostProcessInput(Object sender, ProcessInputEventArgs e)
   在 System.Windows.Input.InputManager.RaiseProcessInputEventHandlers(ProcessInputEventHandler postProcessInput, ProcessInputEventArgs processInputEventArgs)
   在 System.Windows.Input.InputManager.ProcessStagingArea()
   在 System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   在 System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   在 System.Windows.Interop.HwndKeyboardInputProvider.ProcessTextInputAction(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
错误类型：System.ArgumentException
[22:09:40.814] [System] PCL 已崩溃：
程序出现未知错误：指定的 Visual 已经是另一个 Visual 的子级或者已经是 CompositionTarget 的根。
   在 PCL.PageVersionMod.RefreshResult(List`1 Mods)
   在 PCL.PageVersionMod.SearchRun()
   在 PCL.MySearchBox.Text_TextChanged(Object sender, TextChangedEventArgs e)
错误类型：System.ArgumentException

**Comment by allMagicNB** [comment]
> 出现该错误后如果在搜索栏搜索会直接闪退:(
> 应该是新版本才有的，更新前未发现此问题

不要复制粘贴搞那么长……
如果真的需要传输这么长的内容，也请单独粘贴到一个或多个文件里，然后再上传……

**Comment by junugo** [comment]
我成功报错了，但是还是成功显示出了页面？我先是正常的，然后去mod下载的搜索界面搜索了一些内容，回来就发生这个报错

**Comment by w2w2e2wq** [comment]
遇到了,日志如下
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14261965/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14261966/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14261976/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14261977/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14261978/Log5.txt)

**Comment by ruattd** [comment]
补充一个复现方式
同一个 Mod 的两个不同版本丢进一个端的 mods 文件夹，稳定触发

**Comment by WEDFVV** [comment]
请求解锁隐藏主题qwq

**Comment by SALTWOOD** [comment]
> 请求解锁隐藏主题qwq

sensei，给识别码龙猫才能给你开（

**Comment by WEDFVV** [comment]
直接发这里会不会不好（）

**Comment by WEDFVV** [comment]
> > 请求解锁隐藏主题qwq
> 
> sensei，给识别码龙猫才能给你开（

直接发这里会不会不好？）

**Comment by Deep-Dark-Forest** [comment]
> > 请求解锁隐藏主题qwq
> 
> sensei，给识别码龙猫才能给你开（

？log1.txt里面不已经有识别码了吗

**Comment by LTCatt** [comment]
你的解锁码：EK5V63ErMPDkp0CaJv5C1asY9DgugHDw
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by WEDFVV** [comment]
谢谢！

**Comment by wuliaodexiaoluo** [comment]
> 直接发这里会不会不好？）

识别码不会暴露任何信息
解锁码也只有你一个人能用

**Comment by WEDFVV** [comment]
> > 直接发这里会不会不好？）
> 
> 识别码不会暴露任何信息 解锁码也只有你一个人能用

嗯嗯，感谢解答
