### ISSUE TITLE
窗口过小时 Mod 拼接名称过长导致覆盖关闭按钮

### ISSUE THREAD

**Issue by JingHai-Lingyun** [Hex-Dragon/PCL2#3094]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

Mod 的中文名和英文名过长时，在下载详情页的拼接标题 `中文(英文)` 会过长。
当窗口较小时将直接覆盖关闭按钮

### 重现步骤

1、将窗口缩小
2、Mod 下载页搜索 ingameime
3、打开蓝色图标的那个 Forge 重制版
4、观察标题

### 日志与附件

![image](https://github.com/Hex-Dragon/PCL2/assets/109946426/264e8c3e-e603-4e7e-8c4e-9834d78dc0c9)

**Comment by burningtnt** [comment]
哈哈哈哈哈哈哈

**Comment by iPodtouch6557** [comment]
> 哈哈哈哈哈哈哈，或许可以把超出部分改为 "..."？

或者如果标题控件可以做到的话，加一个淡出的视觉效果，然后为 一 X 留出足够空间，避免覆盖
~这年头谁还用forge啊我都是fabric，除非某些整合包没办法，这个输入法修复我是用fabric版的~

**Comment by allMagicNB** [comment]
目前要做的就是替换成“…”的地方往左挪点，把最小化和关闭按钮完整的展示出来

**Comment by allMagicNB** [comment]
> 哈哈哈哈哈哈哈，或许可以把超出部分改为 "..."？

已经是了

**Comment by iPodtouch6557** [comment]
> > >哈哈哈哈哈哈哈，或许可以把超出部分改为 "..."？
> >
> 已经是了

好像确实已经是了，哈哈哈哈

**Comment by JingHai-Lingyun** [comment]
换了个电脑，来要一下新的解锁码
4673-07CB-8399-2740

**Comment by LTCatt** [comment]
你的解锁码：6oOlu2cM71kDiOksqaHda4Sjw0TRVpBx
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
