### ISSUE TITLE
模组加载失败

### ISSUE THREAD

**Issue by lsinda** [Hex-Dragon/PCL2#3098]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![e0b114907929a3114e433d49d2e232cb](https://github.com/Hex-Dragon/PCL2/assets/140962801/912a9230-4b62-42de-ba10-1b8e500a2fd2)

### 重现步骤

1.我先查看了模组列表然后就提示加载失败

### 日志与附件

![e0b114907929a3114e433d49d2e232cb](https://github.com/Hex-Dragon/PCL2/assets/140962801/b3d6487b-068f-4e81-825e-7e3a2286a5d7)

**Comment by hejiehao** [comment]
#3092
