### ISSUE TITLE
勾选功能隐藏>主页面>更多后取消子页面勾选行为有误

### ISSUE THREAD

**Issue by FQO3** [Hex-Dragon/PCL2#3099]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

这是我第三次开这个bug的issue了……我也不知道说啥了
重现办法和#3019一样
要是不想改就算了吧……

### 重现步骤

具体请看#3019
请看我发b站的视频吧……
https://www.bilibili.com/BV1Je411r7qc

### 日志与附件

[空.txt](https://github.com/Hex-Dragon/PCL2/files/13853694/default.txt)

**Comment by JingHai-Lingyun** [comment]
2.6.13 已经修复了，我测试了，已经不会自动勾选（取消勾选）
你是不是没更新？

**Comment by FQO3** [comment]
我更新了呀？

**Comment by FQO3** [comment]
https://github.com/Hex-Dragon/PCL2/assets/111474347/2b45aa92-8ac1-466c-a770-972c6eb4ea2a

**Comment by JingHai-Lingyun** [comment]
呃 这种情况还真的没修好。。。
即 勾选 主页面:更多 后取消勾选 更多 子页面:的前三项

**Comment by LTCatt** [comment]
……确实头疼，不要阴阳怪气

**Comment by kong-que-dnf123** [comment]
总之现在的问题应该是 **勾选前面三项后自动勾选“反馈”与“新功能投票”，若“反馈”与“新功能投票”取消一个则会自动取消前面三项**
~（至少已经不会反选了是个好消息）~
这个我觉得就是机制了
理论上单一个显示的时候会直接代替“更多”出现在上面
而“反馈”和“新功能投票”点了是直接跳转到网站啊......

**Comment by kong-que-dnf123** [comment]
> 总之现在的问题应该是 **勾选前面三项后自动勾选“反馈”与“新功能投票”，若“反馈”与“新功能投票”取消一个则会自动取消前面三项** ~（至少已经不会反选了是个好消息）~ 这个我觉得像机制了 理论上单一个显示的时候会直接代替“更多”出现在上面 而“反馈”和“新功能投票”点了是直接跳转到网站啊......

~昨天一更新完我就测试出来这事了，然后我就把它当网页直接跳转机制没管......~

**Comment by allMagicNB** [comment]
> > 总之现在的问题应该是 **勾选前面三项后自动勾选“反馈”与“新功能投票”，若“反馈”与“新功能投票”取消一个则会自动取消前面三项** ~（至少已经不会反选了是个好消息）~ 这个我觉得像机制了 理论上单一个显示的时候会直接代替“更多”出现在上面 而“反馈”和“新功能投票”点了是直接跳转到网站啊......
> 
> ~昨天一更新完我就测试出来这事了，然后我就把它当网页直接跳转机制没管......=.=~

确实，我也觉得是网页跳转机制……

**Comment by LTCatt** [comment]
哦这个确实是 WAI，不能单独留一个在那，因为那俩玩意儿没有对应的 UI 页面，点击标签之后切不过去，特意加的这个判断（
