### ISSUE TITLE
关于下载页面mod前置显示优化的建议

### ISSUE THREAD

**Issue by Fei-yao** [Hex-Dragon/PCL2#3114]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在mod Oculus的下载页面中显示的前置只有“铷”一项，在MC百科中描述为 铷 和 Embeddium 二选一安装
我的建议是为部分mod的前置添加额外描述，例如在将该mod的前置显示改为
前置 Mod（二选一）
Embeddium
铷

### 原因

可以提升使用体验

**Comment by burningtnt** [comment]
此未下载源数据，PCL2 无法做自己的标注

在 2024-01-10 13:44:29，Fei-yao ***@***.***> 写道：


检查项
我已在 Issues 页面 和 常见&难检反馈及问题列表 中搜索，确认了这一建议未被提交过。
我已查看 功能投票页面，确认了这一建议未在投票列表中。
描述

在mod Oculus的下载页面中显示的前置只有“铷”一项，在MC百科中描述为 铷 和 Embeddium 二选一安装
我的建议是为部分mod的前置添加额外描述，例如在将该mod的前置显示改为
前置 Mod（二选一）
Embeddium
铷

原因

可以提升使用体验

**Comment by youzi-2333** [comment]
确实，这个大概率是下载源没标清楚的问题……

话说这不是两个都有么

![image](https://github.com/Hex-Dragon/PCL2/assets/106497113/57f240df-0ed1-4b5e-8e65-e8206df9cc5e)

**Comment by LTCatt** [comment]
API 尚不支持此类标注
