### ISSUE TITLE
管理员身份运行时，无法通过拖拽文件来导入文件

### ISSUE THREAD

**Issue by blblkang** [Hex-Dragon/PCL2#3117]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如题，在普通模式启动时则可以拖拽文件

### 重现步骤

1、点击"以管理员身份运行"
2、尝试拖拽mod/整合包文件至启动器，失败

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13887205/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/13887207/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/13887209/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/13887210/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/13887212/Log5.txt)

**Comment by JingHai-Lingyun** [comment]
#2531 ....
这东西很难解决...

**Comment by deep-dark-forest** [comment]
很好，六角龙机器人又出bug了

**Comment by kong-que-dnf123** [comment]
重复了但是没关.jpg
~我还以为我github没加载完卡了~

**Comment by allMagicNB** [comment]
> #2531 ....
> 这东西很难解决...

涉及到Windows系统的设计……

**Comment by allMagicNB** [comment]
您是**完全不看**对吗
![Screenshot_20240111_131341.jpg](https://github.com/Hex-Dragon/PCL2/assets/116283787/91c2d55c-71c4-486c-885d-48fbdfa677f3)

**Comment by blblkang** [comment]
> 您是**完全不看**对吗？
> ![Screenshot_20240111_131341.jpg](https://github.com/Hex-Dragon/PCL2/assets/116283787/91c2d55c-71c4-486c-885d-48fbdfa677f3)
> 
> 

对不起，搜了一圈，真的没看见

**Comment by allMagicNB** [comment]
> > 您是**完全不看**对吗？
> > ![Screenshot_20240111_131341.jpg](https://github.com/Hex-Dragon/PCL2/assets/116283787/91c2d55c-71c4-486c-885d-48fbdfa677f3)
> > 
> > 
> 
> 对不起，搜了一圈，真的没看见

我是指[常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930)

**Comment by blblkang** [comment]
> > > 您是**完全不看**对吗？
> > > ![Screenshot_20240111_131341.jpg](https://github.com/Hex-Dragon/PCL2/assets/116283787/91c2d55c-71c4-486c-885d-48fbdfa677f3)
> > > 
> > > 
> > 
> > 对不起，搜了一圈，真的没看见
> 
> 我是指[常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 

我可能是瞎了（
