### ISSUE TITLE
mod列表无法打开

### ISSUE THREAD

**Issue by hinatamiyabi** [Hex-Dragon/PCL2#3119]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

弹出下面如图所示错误窗口

### 重现步骤

1、点击mod管理

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/13898107/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/13898108/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/13898109/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/13898110/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13898111/Log1.txt)
<img width="941" alt="Snipaste_2024-01-11_15-25-24" src="https://github.com/Hex-Dragon/PCL2/assets/104922774/411d4bb6-e1d0-4b25-822f-dbde18483bd3">

**Comment by JingHai-Lingyun** [comment]
#3092在修了，等等吧
