### ISSUE TITLE
删除/重命名版本后没有重置设置缓存，导致原版本的设置被复用

### ISSUE THREAD

**Issue by xiaoniaoawa** [Hex-Dragon/PCL2#3120]
### 检查项

- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

给版本添加收藏 - 卸载版本 - 安装同名版本 - 查看收藏列表

### 重现步骤

1. 卸载一个已经收藏的版本（下图以“CodingPi”为演示）
![image](https://github.com/Hex-Dragon/PCL2/assets/112697401/a563e91a-70d2-4778-b7b7-72bafb272782)

2. 安装同名版本
![image](https://github.com/Hex-Dragon/PCL2/assets/112697401/d2241ad3-1081-4faa-8bd7-8723b4d7c7d9)

3. 你会发现这个版本又在收藏夹里出现了
![image](https://github.com/Hex-Dragon/PCL2/assets/112697401/4b6e9805-c799-4f99-818d-1b48246f73e0)

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/13899304/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/13899305/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/13899306/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13899307/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/13899309/Log2.txt)

注：此处log并无实际参考作用

**Comment by zkitefly** [comment]
我感觉这样更好？

**Comment by JingHai-Lingyun** [comment]
我记得这个Bug很早修过来着，咋又来了

**Comment by kong-que-dnf123** [comment]
就很奇怪
我用**版本选择**的垃圾桶标识删除就不行
用**版本设置→删除版本**就能复现（

**Comment by kong-que-dnf123** [comment]
> 就很奇怪 我用**版本选择**的垃圾桶标识删除就不行 用**版本设置→删除版本**就能复现（

而且用这种方式卡出的收藏版本除非重新收藏一遍否则重新打开就没在收藏栏里了（

**Comment by iPodtouch6557** [comment]
> 我记得这个Bug很早修过来着，咋又来了

就是我的issue

**Comment by iPodtouch6557** [comment]
> 就很奇怪 我用**版本选择**的垃圾桶标识删除就不行 用**版本设置→删除版本**就能复现（

#2495 我用垃圾桶复现的，而且可以一直在收藏夹里
