### ISSUE TITLE
curseforge下载源无法正常下载

### ISSUE THREAD

**Issue by mcyes6** [Hex-Dragon/PCL2#3121]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

PCL搜索整合包时，未能搜索出curseforge源的资源。但是其它启动器（BakaXL）可以正常搜索curseforge源并下载，这是一个新问题

### 重现步骤

1、点击下载
2、然后点击整合包

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13904325/Log1.txt)

**Comment by Pigeon0v0** [comment]
大概率是你自己的网络问题

BakaXL 能拉取资源列表是因为两者请求资源的方式不同

BakaXL 在拉取资源列表时走了他们的 API，而这个 API 服务器对 CurseForge 的连通性比较好（不过实际能不能下载还得看你自己网络），简单来说就是给你中转了一下

而 PCL 是直接在你本地网络请求 CurseForge 资源列表，你自己连不上那就是连不上了

PCL 不会设置任何云服务，当然也包括这类服务了...

**Comment by JingHai-Lingyun** [comment]
最近 CurseForge 被部分地区墙了...
没办法
