### ISSUE TITLE
搜索 Mod 时可能会搜到整合包

### ISSUE THREAD

**Issue by ltdz1376666** [Hex-Dragon/PCL2#3123]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

搜索Mod时，搜索到了Fabulously Optimized整合包，点击后出现错误

### 重现步骤

1、点击下载
2、点击mod
3，版本选择1.20.1Fabric
4，翻到第四页
5，发现了Fabulously Optimized整合包
6，点击
7，崩了

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13915804/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/13915805/Log2.txt)

**Comment by zkitefly** [comment]
https://github.com/Hex-Dragon/PCL2/issues/2916

**Comment by ltdz1376666** [comment]
#2916跟这个不是一个bug吧？我这个是在mod搜索里搜到了一个整合包
![屏幕截图 2024-01-12 153105](https://github.com/Hex-Dragon/PCL2/assets/147720318/02c7ab6b-9002-48f5-9be7-6015efad8881)
![屏幕截图 2024-01-12 153110](https://github.com/Hex-Dragon/PCL2/assets/147720318/231bac04-9d11-4629-9a10-d5699803de2c)

**Comment by allMagicNB** [comment]
> #2916跟这个不是一个bug吧？我这个是在mod搜索里搜到了一个整合包
> ![屏幕截图 2024-01-12 153105](https://github.com/Hex-Dragon/PCL2/assets/147720318/02c7ab6b-9002-48f5-9be7-6015efad8881)
> ![屏幕截图 2024-01-12 153110](https://github.com/Hex-Dragon/PCL2/assets/147720318/231bac04-9d11-4629-9a10-d5699803de2c)
> 

养成良好习惯，引用时左右两端加空格

**Comment by allMagicNB** [comment]
**复现成功**
我大致看了下，不太可能是Modrinth API的锅

**Comment by zkitefly** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/64117916/d47197ee-21f0-40d1-ba53-63d58ff66fa5)

![image](https://github.com/Hex-Dragon/PCL2/assets/64117916/b0bb7b98-d723-4202-8a59-3bc18751030f)

:thinking:

**Comment by allMagicNB** [comment]
啊这

**Comment by allMagicNB** [comment]
emmmm……好像真是API的锅？

**Comment by zkitefly** [comment]
> emmmm……好像真是API的锅？

不过我觉得 PCL 可以去筛选，不然会报错

**Comment by allMagicNB** [comment]
> > emmmm……好像真是API的锅？
> 
> 不过我觉得 PCL 可以去筛选，不然会报错

但是这仨里边就PCL点进去会报错……

**Comment by zkitefly** [comment]
> > > emmmm……好像真是API的锅？
> > 
> > 
> > 不过我觉得 PCL 可以去筛选，不然会报错
> 
> 但是这仨里边就PCL点进去会报错……

对啊，所以我就说建议修

**Comment by allMagicNB** [comment]
> > > > emmmm……好像真是API的锅？
> > > 
> > > 
> > > 不过我觉得 PCL 可以去筛选，不然会报错
> > 
> > 
> > 但是这仨里边就PCL点进去会报错……
> 
> 对啊，所以我就说建议修

额，我去Discord频道问问？

**Comment by allMagicNB** [comment]
**having the error fetching mods issue again**
——再次出现获取模组错误的问题
emmm，看起来不是第一次了

**Comment by allMagicNB** [comment]
龙猫挂第三方吧（
省事

**Comment by allMagicNB** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/116283787/c2358a65-ce34-4dfe-bb43-62b4497a08ef)
OK，Modrinth那边的bug已经修了，重现失败（

**Comment by zkitefly** [comment]
> ![image](https://private-user-images.githubusercontent.com/116283787/296532292-c2358a65-ce34-4dfe-bb43-62b4497a08ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyMTIyMDEsIm5iZiI6MTcwNTIxMTkwMSwicGF0aCI6Ii8xMTYyODM3ODcvMjk2NTMyMjkyLWMyMzU4YTY1LWNlMzQtNGRmZS1iYjQzLTYyYjQ0OTdhMDhlZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNFQwNTU4MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOTczZTU2NmVmMTViMThiYTc4MWIyMGQ2ZmQ1ODA1YTQyZDhjMzI4ZmU5NjIwNWViNzQyNzgwOGExY2E1MGM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Id6OxJros7U7nsTqNe01lknqAUBrLFvEOcW9IvJcgis) OK，Modrinth那边的bug已经修了，重现失败（

确实，其他启动器也ok了

**Comment by allMagicNB** [comment]
就是API的bug，还有必要修吗？
不过Modrinth官方处理bug的速度还挺快的，不想Moja**AndBugs

**Comment by WorldHim** [comment]
那我关了🙄
