### ISSUE TITLE
希望能在导出的bat启动脚本里加入我在“版本设置--设置--自定义游戏标题”设置的自定义标题

### ISSUE THREAD

**Issue by AnonCN** [Hex-Dragon/PCL2#3126]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

希望能在导出的bat启动脚本里加入
用户在“版本设置--设置--自定义游戏标题”设置的自定义标题

### 原因

我在一个服务器双开mc，并且为了减少启动带来的时间，我通常通过bat快速启动
但是我仍然希望通过自定义的窗口名称快速确定我现在正在使用账户，并且我每个账户的属性不同，我会使用不同的mod，因此游戏本体互相分离，使用{user}这个自定义不太好用
于是我发现了pcl可以自定义窗口标题，并且确认运行完全正常
但是我将这个设置好后再次导出BAT脚本文件并进行启动，发现我设置的自定义标题在BAT脚本程序的运行过程中没有实现
我本人是个菜鸟看不懂命令行，希望开发者可以加入我提出的一个应该毫无价值的建议

**Comment by LTCatt** [comment]
技术上无法实现，修改窗口标题必须要 PCL 本体保持运行，否则只能用 Mod 实现
