### ISSUE TITLE
下载1.0正式版时会弹出错误提示框：“创建文件夹链接失败，游戏可能会没有声音：未能找到路径”

### ISSUE THREAD

**Issue by Oumikerlong** [Hex-Dragon/PCL2#3127]
### 检查项

- [x] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在下载中选择Minecraft1.0正式版进行安装，过程中会弹出错误提示：“创建文件夹链接失败，游戏可能会没有声音：未能找到路径”。打开游戏发现正如提示中的那样，游戏没有声音。本人在启动器中进入过该版本的设置页面，尝试补全文件会弹出与上述相同的错误提示，补全文件似乎无法解决这个问题。
启动器版本：2.6.13（最新）   该错误位于本人上传文件中：[10:52:06.283] [Control]

### 重现步骤

1、点击“下载”；
2、往下滚，然后点击“1.0”；
3、点击“开始安装”；
4、在下载过程中会出现错误弹窗：“创建文件夹链接失败，游戏可能会没有声音：未能找到路径”。之后下载会结束；
5、启动下载的游戏游戏没有声音。
注；补全文件功能似乎无法解决这个问题，尝试补全文件会弹出与上述一致内容的弹窗。
启动器版本：2.6.13（最新）   该错误位于本人上传文件中：[10:52:06.283] [Control]

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13926427/Log1.txt)

**Comment by Oumikerlong** [comment]
> ### 检查项
> * [x]  **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
> * [x]  我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
> * [x]  我已在 [Issues 页面](https://githubfast.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://githubfast.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。
> 
> ### 描述
> 在下载中选择Minecraft1.0正式版进行安装，过程中会弹出错误提示：“创建文件夹链接失败，游戏可能会没有声音：未能找到路径”。打开游戏发现正如提示中的那样，游戏没有声音。本人在启动器中进入过该版本的设置页面，尝试补全文件会弹出与上述相同的错误提示，补全文件似乎无法解决这个问题。 启动器版本：2.6.13（最新） 该错误位于本人上传文件中：[10:52:06.283] [Control]
> 
> ### 重现步骤
> 1、点击“下载”； 2、往下滚，然后点击“1.0”； 3、点击“开始安装”； 4、在下载过程中会出现错误弹窗：“创建文件夹链接失败，游戏可能会没有声音：未能找到路径”。之后下载会结束； 5、启动下载的游戏游戏没有声音。 注；补全文件功能似乎无法解决这个问题，尝试补全文件会弹出与上述一致内容的弹窗。 启动器版本：2.6.13（最新） 该错误位于本人上传文件中：[10:52:06.283] [Control]
> 
> ### 日志与附件
> [Log1.txt](https://githubfast.com/Hex-Dragon/PCL2/files/13926427/Log1.txt)

#

**Comment by Oumikerlong** [comment]
现在使用PCL2下载Minecraft1.5.2及更老的版本都会出现这个问题

**Comment by JingHai-Lingyun** [comment]
我 2.6.13 实测下载 Minecradt 1.0 没有问题。
看日志发现你把文件夹放在了桌面，换个目录试试看有没有问题

**Comment by LTCatt** [comment]
这是权限问题，不要放在桌面或 C 盘

**Comment by zkitefly** [comment]
> 这是权限问题，不要放在桌面或 C 盘；如果可能，使用管理员权限启动 PCL

我认为可以改一下这个报错提示
