### ISSUE TITLE
支持mod加载器的更换版本（升级或降级）

### ISSUE THREAD

**Issue by whystars** [Hex-Dragon/PCL2#3129]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

可以实现在已经安装完成的版本中升级或更改加载器版本，比如1.20.1 Fabric版本是0.14.x，我希望可以通过pcl更改Fabric版本为0.15.x。

### 原因

（示例）
我需要这个功能来更新我的mod loader。很多人都有这样的需求，但如果没有这个功能，就不能兼容更新Fabric版本的mod了。

**Comment by whystars** [comment]
麻烦大家顶一顶

**Comment by whystars** [comment]
这个功能非常重要啊

**Comment by JingHai-Lingyun** [comment]
#220，请到 #227 投票
