### ISSUE TITLE
添加PCL2 Lite功能

### ISSUE THREAD

**Issue by mike-brown8** [Hex-Dragon/PCL2#3130]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

建议添加一个导出整合包包含PCL2 Lite启动器的功能，就是PCL2把除了启动、版本选择和文件补全之外的功能全部删除，并且只能使用导出者设置的登录方式进行游戏的登录和启动。
如果能导出这样的整合包有以下好处：
1. 大幅缩小整合包体积（启动器和mod等文件自带，但是没游戏资源文件的占用了，初次启动自动下载）
2. 避免玩家登录方式错误（曾经有个玩家用离线模式强进Littleskin验证的服务器，进不去在服务器群里消息刷屏[差点99+]一类的）
3. 保证整合包稳定（尽可能避免玩家私自添加mod，造成客户端不稳定和以及作弊行为）
4. 可能还有更多优点（例如：[BV1mb4y1T7DS](https://www.bilibili.com/video/BV1mb4y1T7DS/)）

### 原因

我和其他一些服主需要整合包打包功能，又害怕别人不会安装、装好了瞎搞（不带脑子），而其他启动器不支持这个功能。PCL2界面简单，解释清晰，参数优质，功能强大，如果加上这个功能，能成为PCL2的一大其他启动器无法可比的亮点。

**Comment by WForst-Breeze** [comment]
通过功能隐藏是否能满足大部分需求？

**Comment by mike-brown8** [comment]
> 通过功能隐藏是否能满足大部分需求？

也许能，但是挡不住那些知道F12但又喜欢乱搞的玩家（例如早期的我）

**Comment by JingHai-Lingyun** [comment]
> 只能使用导出者设置的登录方式进行游戏的登录和启动

版本设置 - 设置 - 服务器 - 登录方式 可以指定登录方式

---

资源文件你如果删掉了 PCL 会自动补全回来的
其余的内容均可以通过功能隐藏解决

**Comment by WForst-Breeze** [comment]
#2330 已拒绝

**Comment by mike-brown8** [comment]
好的，我去尝试一下，谢谢。
