### ISSUE TITLE
自动安装前置依赖模组

### ISSUE THREAD

**Issue by RainbowTaro2022** [Hex-Dragon/PCL2#3133]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [x] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [x] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

如果我下载了带依赖的mod，启动游戏之后会自动帮我下载前置依赖mod

### 原因

很多自制整合包以前都需要手动下前置mod，自动下前置省去了一点时间

**Comment by JingHai-Lingyun** [comment]
#179
