### ISSUE TITLE
加载Mod列表UI失败:指定的Visual已经是另一个Visual 的子级或者已经是CompositionTarget的根。

### ISSUE THREAD

**Issue by Lonely0906** [Hex-Dragon/PCL2#3138]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

无法加载这个存档的mod 只能加载部分 大概是ui的文件坏了
![AG%XK0D L$Z5`D58 S61F2S](https://github.com/Hex-Dragon/PCL2/assets/144258500/ce69df86-0e25-4cc5-8858-083661201297)

### 重现步骤

1、点击版本设置
2、往下滚，然后点击mod管理
3、就会出现以下几句话：
加载Mod列表UI失败:指定的Visual已经是另一个Visual 的子级或者已经是CompositionTarget的根。
在PCL.PageVersionMod.RefreshResult(L ist' 1 Mods)
在PCL.PageVersionMod.LoadUlFroml oader0utput()
错误类型: System.ArgumentException

是否反馈此问题?如果不反馈，这个问题可能永远无法得到解决! 

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13930327/Log1.txt)

**Comment by Lonely0906** [comment]
日志我也不知道是哪个  应该不是这个

**Comment by burningtnt** [comment]
已有重复 Issue，感谢反馈
