### ISSUE TITLE
指定登录方式后的图标与正常图标不一致

### ISSUE THREAD

**Issue by Harry-hq** [Hex-Dragon/PCL2#3139]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

游戏登录状态图标不对

### 重现步骤

1、点击版本设置
2点击设置
3、往下滚，然后点击登录方式，选择仅正版登录

### 日志与附件 不好意思太久没上线
![{F0DFE46F-F1DB-496e-A7FA-D6D1847414ED}](https://github.com/Hex-Dragon/PCL2/assets/156567744/3cd46614-b334-4062-9b7b-7679c187e49a)

###补充：
![屏幕截图 2024-02-18 194011](https://github.com/Hex-Dragon/PCL2/assets/156567744/1ea92f27-921c-4c4c-a8d4-0d7f35ac9fa8)
这一个图标不一致

**Comment by hejiehao** [comment]
图片都没上传上来

**Comment by WForst-Breeze** [comment]
重新上传截图

**Comment by allMagicNB** [comment]
**未成功复现**
![image](https://github.com/Hex-Dragon/PCL2/assets/116283787/c40005ce-f66f-4e53-93a9-38e0fde6c14f)

**Comment by Lei-Zhilong** [comment]
> **未成功复现** ![image](https://private-user-images.githubusercontent.com/116283787/296539740-c40005ce-f66f-4e53-93a9-38e0fde6c14f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyMzA1MzUsIm5iZiI6MTcwNTIzMDIzNSwicGF0aCI6Ii8xMTYyODM3ODcvMjk2NTM5NzQwLWM0MDAwNWNlLWY2NmYtNGU1My05M2E5LTM4ZTBmZGU2YzE0Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNFQxMTAzNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMjc3ODRjN2QyNjk3MTAyN2FiNzQ1NzVkYzEwN2IwNzYyNGU4MzkyYjIyNjAyOTIyN2Q0MGVmZGQ0YTk1NmQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aGcTJYEzsAhiiq2fKiRi6jOiLq5qYIKTNdMXPPP2DvM)

为什么我的可以
![image](https://github.com/Hex-Dragon/PCL2/assets/109223701/0e576356-a05c-4131-83b3-7c8dace81c08)

**Comment by iPodtouch6557** [comment]
哪个图标不对啊（虽然没正版）

**Comment by hejiehao** [comment]
> 哪个图标不对啊（虽然没正版）

~~突然想显摆一下我的正版~~
![image](https://github.com/Hex-Dragon/PCL2/assets/98140773/a74d6db7-82c0-4a79-8c0f-ba84491478ce)
难道他说是和这个图标有差别？
![image](https://github.com/Hex-Dragon/PCL2/assets/98140773/7ad7ecb3-484c-450f-b9a4-1d4dfa524aef)

**Comment by JingHai-Lingyun** [comment]
> 难道他说是和这个图标有差别？

应该是的

**Comment by allMagicNB** [comment]
……所以现在要等作者反应，以指出是哪里出问题？
总觉得把issue丢下就跑而不是协助不太好……
@Harry-hq

**Comment by iPodtouch6557** [comment]
1.更加详细的描述哪个图标出问题
2.传完你那没传上来的图片
（又及，不要水活跃橙）
谢谢配合

**Comment by LTCatt** [comment]
> > 哪个图标不对啊（虽然没正版）
> 
> ~突然想显摆一下我的正版~ ![image](https://private-user-images.githubusercontent.com/98140773/296548523-a74d6db7-82c0-4a79-8c0f-ba84491478ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NjU4NjQsIm5iZiI6MTcwNTU2NTU2NCwicGF0aCI6Ii85ODE0MDc3My8yOTY1NDg1MjMtYTc0ZDZkYjctODJjMC00YTc5LThjMGYtYmE4NDQ5MTQ3OGNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDA4MTI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjOWNlYTk2ODNkYjNmMDYxZDgwMDk2YzExNTNjMTZmYjI4NTQ1MThhNzg3NzBkYTJlYzU2YTA0YzVlNTBlZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GJrnw64nr-lqfa51Ekzf72fQBXJlgJbEcfWxo5jkXrg) 难道他说是和这个图标有差别？ ![image](https://private-user-images.githubusercontent.com/98140773/296548509-7ad7ecb3-484c-450f-b9a4-1d4dfa524aef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NjU4NjQsIm5iZiI6MTcwNTU2NTU2NCwicGF0aCI6Ii85ODE0MDc3My8yOTY1NDg1MDktN2FkN2VjYjMtNDg0Yy00NTBmLWI5YTQtMWQ0ZGZhNTI0YWVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDA4MTI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3YjYyMWU2YTYyYjAwMDU4NzI3MGFmNTNmOWYyYTc1OTY3MWNjODJlMWRmNDRkMzQ3ZTU5MTUzYzY3OTRiM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._aITHuprcr518wqeT9N1oF7UBslzRcLH5xIxboULu5E)


感觉是

**Comment by Harry-hq** [comment]
不好意思，太久没上线
![{F0DFE46F-F1DB-496e-A7FA-D6D1847414ED}](https://github.com/Hex-Dragon/PCL2/assets/156567744/875d47a2-8bc7-4c50-9a05-8903567d0d51)
是这一个蹦出来了老版本微软登录的图标

**Comment by Harry-hq** [comment]
> > 哪个图标不对啊（虽然没正版）
> 
> ~突然想显摆一下我的正版~ ![image](https://private-user-images.githubusercontent.com/98140773/296548523-a74d6db7-82c0-4a79-8c0f-ba84491478ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMTM2NjUsIm5iZiI6MTcwNjAxMzM2NSwicGF0aCI6Ii85ODE0MDc3My8yOTY1NDg1MjMtYTc0ZDZkYjctODJjMC00YTc5LThjMGYtYmE4NDQ5MTQ3OGNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDEyMzYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5NjA1ZjU1OTQxNjg4NTk4ZGFhMWY2MDQ4NjU2NTgxYjZlNjliZDFlZmY1NjhjZWFlYTRhZTdjNTUxZmY2ZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SE51sBZJfQyaTGnylvTuDnLy3uHMWi3mH-b_nt3fhI4) 难道他说是和这个图标有差别？ ![image](https://private-user-images.githubusercontent.com/98140773/296548509-7ad7ecb3-484c-450f-b9a4-1d4dfa524aef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMTM2NjUsIm5iZiI6MTcwNjAxMzM2NSwicGF0aCI6Ii85ODE0MDc3My8yOTY1NDg1MDktN2FkN2VjYjMtNDg0Yy00NTBmLWI5YTQtMWQ0ZGZhNTI0YWVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDEyMzYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxYzJkMGVlZGU1OGY3MTYxYjE4OGRjYTUzZjdiMjY4NWUxM2JlZDAwZTc5ZmZlM2JkMGMwZGU5OGQ1YzlkZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hPlqDNO73Faey649oSUqEE3h_i3OBqhjRt30uB9oEf8)

是的

**Comment by allMagicNB** [comment]
顺便把离线的也统一一下？

**Comment by allMagicNB** [comment]
离线登录的图标好像也不太一样……

**Comment by Harry-hq** [comment]
可不可以帮忙解锁（识别码：33DA-1EC0-94B9-013E）

**Comment by LTCatt** [comment]
你的解锁码：/QHyTZXx6LJg1kar6K5fb6thmwdMd7Pc
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by Harry-hq** [comment]
电脑换了（识别码：B19B-97E2-6425-CD49）

**Comment by LTCatt** [comment]
你的解锁码：BpWL1alvizaaGJNSLxNMyXw1zn9LptyQ
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by Harry-hq** [comment]
识别码 7888-1FA9-4589-556C
