### ISSUE TITLE
PCL2自动下载的1.17.1有BUG，无法启动

### ISSUE THREAD

**Issue by CharaMac** [Hex-Dragon/PCL2#314]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在PCL2自动下载里下载1.17.1版本+Forge+OptiFine启动会崩溃，无论哪个版本（都试过了，都不行）。而我在HMCL和Forge、OptiFine官网下载的jar却能用。估计是文件下载源出错了

### 重现步骤

1、点击xxxx
2、往下滚，然后点击xxxx

### 日志与附件

[2022-11-03-1.log.gz](https://github.com/Hex-Dragon/PCL2/files/9925356/2022-11-03-1.log.gz)
[2022-11-03-2.log.gz](https://github.com/Hex-Dragon/PCL2/files/9925358/2022-11-03-2.log.gz)
[2022-11-03-3.log.gz](https://github.com/Hex-Dragon/PCL2/files/9925359/2022-11-03-3.log.gz)
[debug.log](https://github.com/Hex-Dragon/PCL2/files/9925360/debug.log)
[debug-1.log.gz](https://github.com/Hex-Dragon/PCL2/files/9925361/debug-1.log.gz)
[debug-2.log.gz](https://github.com/Hex-Dragon/PCL2/files/9925362/debug-2.log.gz)
[debug-3.log.gz](https://github.com/Hex-Dragon/PCL2/files/9925363/debug-3.log.gz)
[latest.log](https://github.com/Hex-Dragon/PCL2/files/9925364/latest.log)

**Comment by CharaMac** [comment]
不怎么严重的BUG，但是对没梯子上官网，不用HMCL的人（我）影响太大了，我还要上网课，就因为这个问题我浪费了一下午的休息时间

**Comment by CharaMac** [comment]
（求主题求主题🙏）

**Comment by LTCatt** [comment]
issue 模板错了，换 minecraft 崩溃的模板重新交……
