### ISSUE TITLE
加载 Mod 列表 UI 失败:指定的 Visual 已经是另一个 Visual 的子级或者已经是 CompositionTarget 的根

### ISSUE THREAD

**Issue by TowableSpace694** [Hex-Dragon/PCL2#3143]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

点击mod管理后报:加载 Mod 列表 UI 失败:指定的 Visual 已经是另一个 Visual 的子级或者已经是 CompositionTarget 的根

### 重现步骤

1、创建两个不同但是开启了版本隔离的forge版minecraft
2、创建几个模组 随即关闭一部分
3. 打开文件夹 把mods复制到另外一个mc版本(没启动前)
4. 点到mod管理后报错"加载 Mod 列表 UI 失败:指定的 Visual 已经是另一个 Visual 的子级或者已经是 CompositionTarget 的根.在PCLPageVersionMod.RefreshResult(List1 Mods)在PCLPageVersionMod.LoadUIFromLoaderOutput()错误类型: System.ArgumentException"

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13931576/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/13931577/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/13931578/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/13931579/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/13931580/Log5.txt)

**Comment by allMagicNB** [comment]
……
![Screenshot_20240111_132021.jpg](https://github.com/Hex-Dragon/PCL2/assets/116283787/02459b75-d349-45e8-b1e5-89ea019f4fa8)
又来一个没认真看的

**Comment by allMagicNB** [comment]
好好好，甚至看都不看，你隔壁就是重复
![Screenshot_20240114_212904.jpg](https://github.com/Hex-Dragon/PCL2/assets/116283787/d67db846-dcd6-4f92-be51-fecaeb9f54b8)
