### ISSUE TITLE
PCL启动器自定义应该可以自选颜色

### ISSUE THREAD

**Issue by ColorColourful** [Hex-Dragon/PCL2#3145]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

PCL启动器自定义应该可以自选颜色

### 原因

（示例）
这项优化让我可以更方便地xxxx。
如果没有这项优化，我每次都必须xxxx，让操作变得很麻烦。

**Comment by JingHai-Lingyun** [comment]
#401 拒绝，抱歉

**Comment by ColorColourful** [comment]
Issue

**Comment by allMagicNB** [comment]
> Issue
> 
> 

我知道你在想什么，优化建议拿不到活跃橙
