### ISSUE TITLE
加载 Mod 列表 UI 失败：指定的 Visual 已经是另一个 Visual 的子级或者已经是 CompositionTarget 的根

### ISSUE THREAD

**Issue by axnut123** [Hex-Dragon/PCL2#3146]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

点击1.16.5的forge与optfine版本的mod管理时，出现了错误。
[00:20:33.502] [Control] 普通弹窗：出现错误
加载 Mod 列表 UI 失败：指定的 Visual 已经是另一个 Visual 的子级或者已经是 CompositionTarget 的根。
   在 PCL.PageVersionMod.RefreshResult(List`1 Mods)
   在 PCL.PageVersionMod.LoadUIFromLoaderOutput()
错误类型：System.ArgumentException
请查看程序是否有问题。

### 重现步骤

下载1.12.2的forge与optfine（B)
装点模组，游玩
下载1.16.5的forge与optfine（在A）
下载模组(1.16.5)，在另一个mc文件夹（称为B）下载
启动1.16.5（A，在这个文件夹中有其他低版本模组，我不知道这有没有影响）
然后下载1.16.5的forge与optfine（在B）
再打开B文件夹的模组管理，出现错误。
（应该是这样，最详细的了)

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13932222/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/13932225/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/13932226/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/13932227/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/13932228/Log5.txt)

**Comment by JingHai-Lingyun** [comment]
#3092
~~你是第7个来反馈的~~

**Comment by axnut123** [comment]
我在上传完成之后想继续看看有没有错误，还是出现了。我趁机录制了视频（因为不能上传大于10mb的文件，所以只能用网盘了，对带来的麻烦感到抱歉）。链接：https://pan.baidu.com/s/1-fptipE0pudxz2tna9iOBQ?pwd=pcl2 
提取码：pcl2
