### ISSUE TITLE
modloader版本管理

### ISSUE THREAD

**Issue by DSLZL** [Hex-Dragon/PCL2#3148]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

类似HMCL的modloader版本管理，可更新或者更换版本

### 原因

有时候mod需要更加新的版本，但是又不想再下一份本体占用空间

**Comment by burningtnt** [comment]
已有重复 Issue，感谢您的反馈

**Comment by DSLZL** [comment]
搜索不到啊😂
