### ISSUE TITLE
加载MOD列表时发生错误！

### ISSUE THREAD

**Issue by FanrklinCN** [Hex-Dragon/PCL2#3151]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我启动游戏后游戏报错，然后用PCL的Mod管理功能删除冲突mod，随后一个错误提示弹了出来

### 重现步骤

1、点击版本设置
2、然后点击Mod管理

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/13957387/Log2.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13957390/Log1.txt)

**Comment by kong-que-dnf123** [comment]
```
#于log2，行1726~1734
[09:21:19.321] [Control] 按下带图标按钮：删除
[09:21:19.743] 删除 Mod 出现未知错误：序列不包含任何匹配元素
   在 System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   在 PCL.PageVersionMod.DeleteMods(IEnumerable`1 ModList)
错误类型：System.InvalidOperationException
[09:21:19.762] [Control] 普通弹窗：出现错误
删除 Mod 出现未知错误：序列不包含任何匹配元素
   在 PCL.PageVersionMod.DeleteMods(IEnumerable`1 ModList)
错误类型：System.InvalidOperationException
```
仅删除mod问题方面似乎与#2807类似........

**Comment by kong-que-dnf123** [comment]
```
#于log2，行1683~1694
[09:20:30.853] 加载 Mod 列表 UI 失败：指定的 Visual 已经是另一个 Visual 的子级或者已经是 CompositionTarget 的根。
   在 System.Windows.Media.VisualCollection.Add(Visual visual)
   在 System.Windows.Controls.UIElementCollection.AddInternal(UIElement element)
   在 PCL.PageVersionMod.RefreshResult(List`1 Mods)
   在 PCL.PageVersionMod.LoadUIFromLoaderOutput()
错误类型：System.ArgumentException
[09:20:30.879] [Mod] 从 CurseForge 获取到 0 个本地 Mod 的对应信息
[09:20:31.089] [Control] 普通弹窗：出现错误
加载 Mod 列表 UI 失败：指定的 Visual 已经是另一个 Visual 的子级或者已经是 CompositionTarget 的根。
   在 PCL.PageVersionMod.RefreshResult(List`1 Mods)
   在 PCL.PageVersionMod.LoadUIFromLoaderOutput()
错误类型：System.ArgumentException
```
这个问题与 #3092 重复

**Comment by allMagicNB** [comment]
可能没有权限或者已经被删除了

**Comment by JingHai-Lingyun** [comment]
#3092 的等更新
#2807 的等龙猫再来看一眼？

**Comment by allMagicNB** [comment]
> #3092 的等更新
> #2807 的确认下文件删之前还在吗

或者说文件在C盘没权限？

**Comment by kong-que-dnf123** [comment]
顺便提一句
```
#于log2，行66~70
[09:09:58.741] 版本 json 可用性检查失败（D:\PCL2\.minecraft\versions\[LB]LuzhouMTRserver1.18.2\）：未找到版本 json 文件：D:\PCL2\.minecraft\versions\[LB]LuzhouMTRserver1.18.2\[LB]LuzhouMTRserver1.18.2.json
   在 PCL.ModMinecraft.McVersion.ReflectCode()
   在 PCL.ModMinecraft.McVersion.RegisterCode()
   在 PCL.ModMinecraft.McVersion.Check()
```
这个为什么会有一个**json文件未找到啊**

**Comment by allMagicNB** [comment]
> 顺便提一句
> ```
> #于log2，行66~70
> [09:09:58.741] 版本 json 可用性检查失败（D:\PCL2\.minecraft\versions\[LB]LuzhouMTRserver1.18.2\）：未找到版本 json 文件：D:\PCL2\.minecraft\versions\[LB]LuzhouMTRserver1.18.2\[LB]LuzhouMTRserver1.18.2.json
>    在 PCL.ModMinecraft.McVersion.ReflectCode()
>    在 PCL.ModMinecraft.McVersion.RegisterCode()
>    在 PCL.ModMinecraft.McVersion.Check()
> ```
> 这个为什么会有一个**json文件未找到啊**

我也看到了，但是没在意（

**Comment by SuoHouDaiShi** [comment]
> #3092 的等更新 #2807 的确认下文件删之前还在吗

我是 #2807 Auther，我非常确认在复现过程中文件没有被删除……

**Comment by JingHai-Lingyun** [comment]
呃 不是，我是说这条反馈的作者确认下相似 2807 那个Bug文件还在么

**Comment by allMagicNB** [comment]
> > #3092 的等更新 #2807 的确认下文件删之前还在吗
> 
> 我是 #2807 Auther，我非常确认在复现过程中文件没有被删除……

Author（纠正

**Comment by xiaoniaoawa** [comment]
这bug我没遇到，但是遇到了个新bug（）（）（）
很草，在写issue了
