### ISSUE TITLE
进入世界几秒后卡死

### ISSUE THREAD

**Issue by haotian188977** [Hex-Dragon/PCL2#3152]
### 检查项

- [ ] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃基本不是 PCL 的原因，请 **不要** 提交反馈。你可以在论坛或社区找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用 HMCL 启动，HMCL 没有出现问题。** 如果 HMCL 也无法启动就不是 PCL 导致的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

进入世界几秒后卡死，重新打开世界也有同样问题

### PCL 错误报告、日志与附件

[错误报告-2024-01-16_10.21.41_PM.zip](https://github.com/Hex-Dragon/PCL2/files/13958205/-2024-01-16_10.21.41_PM.zip)

**Comment by allMagicNB** [comment]
你确定你有用友商的HMCL启动？

**Comment by JingHai-Lingyun** [comment]
```
[22:21:08] [IO-Worker-4/WARN]: Saving oversized chunk [10, 9] (19504682 bytes} to external file C:\pcl2\.minecraft\versions\1.20.4\saves\新的世界\entities\c.10.9.mcc
```

日志提示这个区块文件过大，我觉得是地图问题导致的

**Comment by allMagicNB** [comment]
> ```
> [22:21:08] [IO-Worker-4/WARN]: Saving oversized chunk [10, 9] (19504682 bytes} to external file C:\pcl2\.minecraft\versions\1.20.4\saves\新的世界\entities\c.10.9.mcc
> ```
> 
> 日志提示这个区块文件过大，我觉得是地图问题导致的

所以不是PCL2的问题？

**Comment by burningtnt** [comment]
文件内大量可见 Can't keep up，疑似是电脑配置较差

**Comment by LTCatt** [comment]
考虑有安装 Mod，应当不是启动器导致
如果 HMCL 没有这个问题再开
