### ISSUE TITLE
无效的URL

### ISSUE THREAD

**Issue by lsinda** [Hex-Dragon/PCL2#3160]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![屏幕截图 2024-01-19 164331](https://github.com/Hex-Dragon/PCL2/assets/140962801/42d73472-f3dd-43d9-b4e0-bc7f49f89fa6)

### 重现步骤

![屏幕截图 2024-01-19 164331](https://github.com/Hex-Dragon/PCL2/assets/140962801/27ab894e-1e56-4661-9244-345ba333f9b4)

### 日志与附件

出了点问题

**Comment by allMagicNB** [comment]
日志呢？浮现方式呢？打“等待反抗者”label吧

**Comment by LTCatt** [comment]
这估计是系统环境问题，重装一下系统吧……

**Comment by allMagicNB** [comment]
后续需要重装找不到方向找我吧（
免费援助

**Comment by WorldHim** [comment]
dotnet/wpf#197

**Comment by SALTWOOD** [comment]
这么久了还没回？要不先关掉

**Comment by allMagicNB** [comment]
没事不急（

**Comment by LTCatt** [comment]
超时先关了，有需要可以在这里继续回复

**Comment by allMagicNB** [comment]
（等待Author reopen？
