### ISSUE TITLE
在 “启动” 界面合理位置处添加 Mod列表

### ISSUE THREAD

**Issue by Tncent** [Hex-Dragon/PCL2#3161]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

将选择的版本的 Mod 列表快捷显示至主页而不是“藏”在版本设置中 ，或者在版本选择中将鼠标悬浮至版本按钮上方时在右侧显示内部Mod列表

### 原因

有些时候游玩不同的服务器需要换不同的客户端，一般Mod服会更新多个版本Mod并分发，而自定义的名字会随着版本更新而越来越臃肿，如果能后在选择前或者启动前显示Mod列表就棒极了 （虽然我觉得如果能够比较两个不同游戏版本的Mod版本就更好了

**Comment by allMagicNB** [comment]
启动界面除了右边的空白页几乎没地方了。单独再搞，但考虑到页面的简洁性……通过概率不大，而且多点两次不至于累死吧

**Comment by JingHai-Lingyun** [comment]
比较 Mod........ 感觉有点超出启动器的范畴了

**Comment by allMagicNB** [comment]
> 比较 Mod........ 感觉有点超出启动器的范畴了

确实啊，你说主页就那么点空间怎么加呢？

**Comment by Tncent** [comment]
> 启动界面除了右边的空白页几乎没地方了。单独再搞，但考虑到页面的简洁性……通过概率不大，而且多点两次不至于累死吧
我版本太多了QAQ，每次上PCL都要反复去版本列表一个一个点然后在看版本设置去看Mod列表

**Comment by LTCatt** [comment]
暂时不考虑，这个使用面太小了，抱歉……
