### ISSUE TITLE
下载自定义文件时，如果文件名和链接地址为空则重置窗口颜色和提示

### ISSUE THREAD

**Issue by rumengchuxing062** [Hex-Dragon/PCL2#3166]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

下载自定义文件时，如果文件名和链接地址为空则重置窗口颜色和提示
![image](https://github.com/Hex-Dragon/PCL2/assets/110439412/885b6f50-3558-41fe-90fb-14dfc1d8ed8e)

### 原因

看着很不舒服，并且想要重置窗口还必须下载一次文件

**Comment by allMagicNB** [comment]
暂未发现重复issue，但是感觉有点没必要

**Comment by rumengchuxing062** [comment]
你不难受么
（令我想起了 Error）

**Comment by rumengchuxing062** [comment]
(多加个判断符的事（或许）不至于懒到不愿意做吧)

**Comment by allMagicNB** [comment]
> (多加个判断符的事（或许）不至于懒到不愿意做吧)

如果真是这么省事的话会修，但是百分百不止这个步骤

**Comment by rumengchuxing062** [comment]
好用为什么不用

**Comment by LTCatt** [comment]
确实感觉没必要啊……
