### ISSUE TITLE
允许在主页的登录界面选择第三方登录

### ISSUE THREAD

**Issue by LBZiXL** [Hex-Dragon/PCL2#317]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

我希望可以自定义主页的登录选项。
比如，我平常用正版登录，外置登录和离线，但是PCL2的登录方式里面要么是正版，要么是外置，能不能让PCL2的启动界面可以同时出现正版和外置，其他的也一样。（就像 正版登录或离线登录 一样，一个启动界面同时有正版和离线。）

### 原因

我需要这个功能来登录。我不知道有没有人有自定义主页的登录选项的需求，但如果没有这个功能，也可以没有。

**Comment by LTCatt** [comment]
……没听懂这是具体要个啥

**Comment by LiuBinzhe** [comment]
比如，我平常用正版登录和外置登录，但是PCL2的登录方式里面要么是正版，要么是外置，能不能让PCL2的启动界面可以同时出现正版和外置，其他的也一样。（就像 正版登录或离线登录 一样，一个启动界面同时有正版和离线。）

**Comment by LTCatt** [comment]
与 57# 实质重复
