### ISSUE TITLE
为旧版本Minecraft提供Legacy Fabric等自动安装选项

### ISSUE THREAD

**Issue by InputHappy123** [Hex-Dragon/PCL2#3171]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

添加Legacy Fabric、Legacy Fabric API、Babric的自动安装选项
完善自动安装

### 原因

看起来启动器支持更加全面吧（

**Comment by LTCatt** [comment]
现已不再考虑专门为 MC 1.9- 追加新功能，抱歉
