### ISSUE TITLE
加入mod时将：是否要将“这些”mod……改成：是否要将“这个”mod

### ISSUE THREAD

**Issue by xhahello** [Hex-Dragon/PCL2#3177]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

拖入单个mod时换成上面的这句话：是否要将“这个”文件作为mod安装进****

### 原因

看着有一点不舒服，不改就算了吧

**Comment by allMagicNB** [comment]
没必要这么严谨……

**Comment by xiaoniaoawa** [comment]
但是拽进去一堆的话谁知道是哪个 :(

**Comment by allMagicNB** [comment]
> 但是拽进去一堆的话谁知道是哪个 :(

取数量（或者数组成员数？

**Comment by xhahello** [comment]
所以那个什么 活跃的什么的那个颜色（doge，获取的具体流程是什么a

**Comment by allMagicNB** [comment]
> 所以那个什么 活跃的什么的那个颜色（doge，获取的具体流程是什么a

首先，你不要期盼了，只有反馈的是Bug才有活跃橙[doge]
