### ISSUE TITLE
多几个启动按钮

### ISSUE THREAD

**Issue by zhaixianyu** [Hex-Dragon/PCL2#3183]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [x] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [x] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

可以添加多个启动按钮，能单独设置版本、游戏路径、账号。

### 原因

在游玩不同版本/mod的场景流畅切换
当前版本要切换需要点击版本选择再返回启动界面，比较繁琐。
生成的启动脚本会出现正版验证失效的情况。

**Comment by JingHai-Lingyun** [comment]
账号（登录）部分： #3057 拒绝

**Comment by allMagicNB** [comment]
六角龙机器人又发电了……
