### ISSUE TITLE
加载Mod列表UI失败：指定的Visual 已经是另一个Visual的子级或者已经是CompositionTarget的根。

### ISSUE THREAD

**Issue by computer-drive** [Hex-Dragon/PCL2#3184]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/Hex-Dragon/PCL2/assets/86357024/ce9b0cf3-bbef-4bff-9590-9149a1b5ef1b)

排查后发现：
1.只在这个游戏中打开mod列表报错，其他游戏没有此现象
2.如果将mod文件夹移动到其他版本的mod文件夹下，同样会报错

### 重现步骤

1.启动PCL
2.点击版本设置(游戏已自动选择:fabric1.20.1)
3.点击Mod管理
4.报错

### 日志与附件

https://share.weiyun.com/1bYtyk8m

**Comment by hejiehao** [comment]
#3092

**Comment by allMagicNB** [comment]
您可以在写描述时看看反馈列表……

**Comment by JingHai-Lingyun** [comment]
来个人关了.....
~~想要权限~~

**Comment by allMagicNB** [comment]
> 来个人关了.....
> ~~想要权限~~

~~只有更换待处理标签的破贡献者~~

**Comment by hejiehao** [comment]
> > 来个人关了.....
> > ~想要权限~
> 
> ~只有更换待处理标签的破贡献者~

Contributor 还能更换待处理标签吗？

**Comment by JingHai-Lingyun** [comment]
~~没.....~~

**Comment by allMagicNB** [comment]
> ~~没.....~~

那能干啥（

**Comment by hejiehao** [comment]
> > ~没.....~
> 
> 那能干啥（

~~显得 Commit 给 PCL2 的人很 NB~~
