### ISSUE TITLE
为什么正版登录加入不了正版服务器？

### ISSUE THREAD

**Issue by PlayerX32K** [Hex-Dragon/PCL2#3185]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

正版登录后，可以正常打开游戏和游玩单人游戏，但是再加入正版服务器（像是Hypixel 2B2T等）服务器是显示“无法进行身份验证”，因为您的启动器很好用，还因为用别的启动器（包括官启）也需要Java，所以从刚玩mc没正版时就用的pcl，现在有正版了却体验不到正版服务器，希望龙腾猫越大大及时修复，谢谢！
P.S.不知道是不是电脑问题，希望给一个解答

### 重现步骤

1.启动游戏（正版登录）
2.选择一个正版服务器（我选的2B2T，版本适用）
3.加入
4.一脸懵逼的看着上面写着“抱歉，暂时无法验证身份”（恼）

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14037982/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14037984/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14037985/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14037988/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14037989/Log5.txt)

**Comment by PlayerX32K** [comment]
无语了

**Comment by allMagicNB** [comment]
请发请发提问或讨论，而不是issue

**Comment by hejiehao** [comment]
“抱歉，暂时无法验证身份”是游戏上写的吗？

**Comment by WForst-Breeze** [comment]
是无法连接到身份验证服务器吗，挂梯子试试

非启动器问题，先关闭了

**Comment by JingHai-Lingyun** [comment]
请先参考 PCL 启动器内置帮助库 > Minecraft > 多人游戏常见问题 自行排查
也请使用 HMCL 操作，若 HMCL 仍然不行，再来补充

**Comment by allMagicNB** [comment]
```
[19:49:48.655] 获取微软正版皮肤失败（PlayerX32K）：获取结果失败，远程服务器返回错误: (403) 已禁止。（https://sessionserver.mojang.com/session/minecraft/profile/1ad2242475864608832f1185a6542080）
→ 远程服务器返回错误: (403) 已禁止。
```
这皮肤都没获取到……就是网络原因

**Comment by kong-que-dnf123** [comment]
Bot又又又出bug乐是吧一个小时了还没关
