### ISSUE TITLE
UI边角阴影显示错误

### ISSUE THREAD

**Issue by littleZ-233** [Hex-Dragon/PCL2#3186]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如题，UI边角阴影处存在细线。重启了很多次还是如此，版本是快照2.6.13，不清除具体是哪个版本出现的这个问题。虽然不是特别明显，也不影响使用，但最好还是改一下吧（，辛苦了
![image](https://github.com/Hex-Dragon/PCL2/assets/77787807/e42081cf-62bd-48fa-a33b-b356a2fb2571)
![image](https://github.com/Hex-Dragon/PCL2/assets/77787807/adcd0874-9316-4336-9397-6c1f68687a69)
![image](https://github.com/Hex-Dragon/PCL2/assets/77787807/debca622-b0eb-4339-bcc6-78b4ac916fd3)

### 重现步骤

无触发条件

### 日志与附件

[Log.txt](https://github.com/Hex-Dragon/PCL2/files/14038827/Log.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14038828/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14038829/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14038830/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14038831/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14038832/Log5.txt)

**Comment by burningtnt** [comment]
阴影绘制出问题了

**Comment by iPodtouch6557** [comment]
我印象里似乎反馈来着 说是wpf的问题

**Comment by LTCatt** [comment]
WPF 在高分屏下的像素缩放问题，没法解决 :/
