### ISSUE TITLE
[按钮位置错乱]更多>启动器>"微软登录卡死或失败的解决方案">"第二种问题解决方案"的第一个按钮

### ISSUE THREAD

**Issue by Zetrey** [Hex-Dragon/PCL2#3188]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

更多>启动器>"微软登录卡死或失败的解决方案">"第二种问题解决方案"，打开就能看到按钮位置错误，不需要调节窗口大小，该bug会导致按钮与正文重叠

### 重现步骤

1、点击更多>启动器
2、往下滚，然后点击微软登录卡死或失败的解决方案
3、点击第二种问题解决方案

### 日志与附件

[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14041958/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14041959/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14041960/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14041961/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14041962/Log4.txt)
![image](https://github.com/Hex-Dragon/PCL2/assets/78598969/8b95969d-e5d3-45ec-a176-7ab76e9b88ae)

**Comment by JingHai-Lingyun** [comment]
```xml
        <Grid Margin="0,20,0,4">
            <TextBlock TextWrapping="Wrap" Margin="0,15,0,4" Width="200"
                        Text="2. 按下键盘上的 Windows + R 键，打开运行界面，输入 services.msc 打开服务管理程序。" HorizontalAlignment="Left" />
            <local:MyButton MinWidth="170" Height="35" Padding="10,0" Margin="0,5,20,8" HorizontalAlignment="Left"
                        Text="复制 services.msc 命令" EventType="复制文本" EventData="services.msc" />
            <Image Margin="250,0,0,0" HorizontalAlignment="Center" Source="https://img.z0z0r4.top/local/2022/07/10/1/10.Service.png" />
        </Grid>
```

这里有张图片的，但是图床炸掉了...... 我感觉是这个原因

**Comment by youzi-2333** [comment]
@z0z0r4 不会图床又炸了吧

这次是 `img.z0z0r4.top` 出了问题，我访问的时候报 `服务器或代理查找失败`

**Comment by WForst-Breeze** [comment]
帮助库问题，已提交 Issue 到 LTCatt/PCL2Help#346

**Comment by allMagicNB** [comment]
> 帮助库问题，已提交 Issue 到 LTCatt/PCL2Help#346

那关了？毕竟不是PCL本身的问题

**Comment by allMagicNB** [comment]
总之现在应该**备案掉了**

**Comment by z0z0r4** [comment]
@WForst-Breeze Should be clous
