### ISSUE TITLE
关于点击pcl2启动器自动跳转.NET Framework的下载页面这件事

### ISSUE THREAD

**Issue by Lansxh** [Hex-Dragon/PCL2#3189]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在点击启动器后，pcl自动跳转.NET Framework的下载页面，下载.NET Framework 4.6.2 Offline Installer并安装后弹出以下窗口
![bug反馈](https://github.com/Hex-Dragon/PCL2/assets/156696629/adc7746c-3e0a-480f-94ea-f6dc2b7bd28a)
重新点击启动器，仍然自动跳转并下载
并且尝试.NET Framework的多个版本，重复卸载和安装后仍未得到解决方案

### 重现步骤

1、双击启动器
2、出现pcl图标并自动跳转到.NET Framework的下载页面

### 日志与附件

[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14042760/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14042761/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14042762/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14042763/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14042764/Log4.txt)

**Comment by xiaogu2022** [comment]
是否解决

**Comment by xiaogu2022** [comment]
是否已解决

**Comment by wuyuncheng-26** [comment]
> 是否已解决

这不是打了拒绝标签嘛？

**Comment by xiaogu2022** [comment]
我也出问题了
是忽略了
问下那位自己解决了没

**Comment by xiaogu2022** [comment]
你有这个问题吗
帮忙解决下

**Comment by wuyuncheng-26** [comment]
> 我也出问题了 是忽略了 问下那位自己解决了没

重装系统也许是最好的解决方案（？
也许是 PCL 误判定？

**Comment by Pigeon0v0** [comment]
> 你有这个问题吗
> 
> 帮忙解决下
> 
> 

重装系统
