### ISSUE TITLE
下载提示证书无效

### ISSUE THREAD

**Issue by ZeroCore-Zero** [Hex-Dragon/PCL2#3191]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

下载时无法下载，提示：
下载原版 1.16.4失败
→ 下载原版资源文件失败
→ 下载资源文件（副加载器）失败
→ 基础连接已经关闭: 未能为 SSL/TLS 安全通道建立信任关系。
→ 根据验证过程，远程证书无效。
   在 PCL.ModNet.NetFile.Thread(NetThread Info)
错误类型：System.Security.Authentication.AuthenticationException

### 重现步骤

在 下载-自动安装 中选择1.16.4原版+fabric+fabric api 
点击下载

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14049744/Log1.txt)

**Comment by hejiehao** [comment]
MCBBS 挂了吧

**Comment by ZeroCore-Zero** [comment]
> MCBBS 挂了吧

我在两台电脑上都试了，一台没问题一台就这样

**Comment by JingHai-Lingyun** [comment]
SSL/TLS 无效，类似 #3018

**Comment by allMagicNB** [comment]
> SSL/TLS 无效，类似 #3018

自信点，等于 #3018 的问题

**Comment by WorldHim** [comment]
看到一个玄学方法…用官启下载一次游戏后，再用 pcl 就能正常下载…不知道有没有用…

**Comment by hejiehao** [comment]
从日志里看，游戏似乎是从 MCBBS 下载的

**Comment by allMagicNB** [comment]
> 看到一个玄学方法…用官启下载一次游戏后，再用 pcl 就能正常下载…不知道有没有用…

反正怎么说都对离线玩家不太友好（？
