### ISSUE TITLE
[PCL统一通行证问题] 在链接地址处会自动删减"/"导致特殊语言（如SpringBoot）通行证服务器无法登录

### ISSUE THREAD

**Issue by N1ngYu** [Hex-Dragon/PCL2#3194]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

优化一下链接栏 不要自动删减"/"啊喂（SpringBoot挺难绷的）
日志如下：
[21:17:27.266] 加载线程 Loader Launch (35) 发生运行时错误：获取启动参数失败
→ 无法连接到第三方登录服务器（https://pass.bkr.xiaoyi311.eu.org/api/yggdrasil）
→ 获取结果失败，远程服务器返回错误: (404) 未找到。（https://pass.bkr.xiaoyi311.eu.org/api/yggdrasil）
→ 远程服务器返回错误: (404) 未找到。
   在 PCL.ModLaunch.McLaunchStart(LoaderTask`2 Loader)
   在 PCL.ModLoader.LoaderTask`2._Closure$__13-0._Lambda$__0()
   在 PCL.ModLaunch.McLaunchArgumentsJvmNew(McVersion Version)
   在 PCL.ModLaunch.McLaunchArgumentMain(LoaderTask`2 Loader)
   在 PCL.ModLoader.LoaderTask`2._Closure$__13-0._Lambda$__0()
   在 PCL.ModNet.NetGetCodeByRequestRetry(String Url, Encoding Encode, String Accept, Boolean IsJson, String BackupUrl)
   在 PCL.ModLaunch.McLaunchArgumentsJvmNew(McVersion Version)
   在 System.Net.HttpWebRequest.GetResponse()
   在 PCL.ModNet.NetGetCodeByRequestOnce(String Url, Encoding Encode, Int32 Timeout, Boolean IsJson, String Accept)
错误类型：System.Net.WebException
[21:17:27.267] [Loader] 加载器 Loader Launch 状态改变：Failed
[21:17:27.292] [Control] 普通弹窗：启动失败
Minecraft 启动失败：获取启动参数失败
→ 无法连接到第三方登录服务器（https://pass.bkr.xiaoyi311.eu.org/api/yggdrasil）
→ 获取结果失败，远程服务器返回错误: (404) 未找到。（https://pass.bkr.xiaoyi311.eu.org/api/yggdrasil）
→ 远程服务器返回错误: (404) 未找到。
   在 PCL.ModLaunch.McLaunchStart(LoaderTask`2 Loader)
   在 PCL.ModLaunch.McLaunchArgumentsJvmNew(McVersion Version)
   在 PCL.ModLaunch.McLaunchArgumentMain(LoaderTask`2 Loader)
   在 PCL.ModLoader.LoaderTask`2._Closure$__13-0._Lambda$__0()
   在 PCL.ModNet.NetGetCodeByRequestRetry(String Url, Encoding Encode, String Accept, Boolean IsJson, String BackupUrl)
   在 PCL.ModLaunch.McLaunchArgumentsJvmNew(McVersion Version)
   在 PCL.ModNet.NetGetCodeByRequestOnce(String Url, Encoding Encode, Int32 Timeout, Boolean IsJson, String Accept)
错误类型：System.Net.WebException
（实测HMCL无此问题，必须加上/才可正常访问

### 原因

玩服务器没通行证我玩不了啊呜呜呜呜呜呜呜呜

**Comment by N1ngYu** [comment]
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14052916/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14052917/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14052948/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14052920/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14052921/Log5.txt)

**Comment by N1ngYu** [comment]
完成了呢...这个可以兑换主题吗？ 识别码：F6C1-C465-2DEB-D48C

**Comment by LTCatt** [comment]
你的解锁码：Y3mOeafKJ3BZEE3XmloJImyaQ4DGbDJ8
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
