### ISSUE TITLE
正版账号无法显示皮肤，且错误链接显示不全以至于无法访问，重启等方法全没用

### ISSUE THREAD

**Issue by MXT-dudu** [Hex-Dragon/PCL2#3197]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

正版账号无法显示皮肤，且错误链接显示不全以至于无法访问，重启等方法全没用

### 重现步骤

点击启动器后自动弹出

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14061682/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14061684/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14061685/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14061687/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14061688/Log2.txt)

**Comment by allMagicNB** [comment]
截个屏看看？

**Comment by allMagicNB** [comment]
推测是个人网络原因

**Comment by kxkl2077** [comment]
可以用这个修改hosts，然后再试试能不能显示皮肤等问题
https://www.dogfight360.com/blog/475/

**Comment by MXT-dudu** [comment]
@allMagicNB

**Comment by allMagicNB** [comment]
？

**Comment by MXT-dudu** [comment]
@allMagicNB 为啥我发不了图片啊，链接复制了就消失

**Comment by allMagicNB** [comment]
> @allMagicNB 为啥我发不了图片啊，链接复制了就消失

没加载出来而已？我也不知道，Win+Shift+S截屏之后直接粘贴到回复框里啊

**Comment by burningtnt** [comment]
> 为啥我发不了图片啊，链接复制了就消失

等 Uploading 字样消失后再发送

**Comment by MXT-dudu** [comment]
屏幕截图 2024-01-26 154904.png

**Comment by MXT-dudu** [comment]
![Uploading 屏幕截图 2024-01-26 154904.png…]

**Comment by burningtnt** [comment]
等 Uploading 字样消失后再发送

**Comment by MXT-dudu** [comment]
> 等 Uploading 字样消失后再发送

什么意思啊？Uploading 字样消失的话链接也没了呀

**Comment by MXT-dudu** [comment]
> > @allMagicNB 为啥我发不了图片啊，链接复制了就消失
> 
> 没加载出来而已？我也不知道，Win+Shift+Sscreenshot屏之后直接粘贴到回复框里啊

笔记本怎么办

**Comment by burningtnt** [comment]
> 什么意思啊？Uploading 字样消失的话链接也没了呀

把消息粘贴到回复框后，会看到 `[Uploading XXXXXX]`，随后等到 Uploading 消失，就可以点 Comment 上传了

**Comment by allMagicNB** [comment]
算了吧，这是单抽的网络问题，关了……？

**Comment by MXT-dudu** [comment]
> 算了吧，这是单抽的网络问题，关了......？

晚上刚好要重装一下电脑，到时候再看吧

**Comment by MXT-dudu** [comment]
[
![Uploading 屏幕截图 2024-01-26 154904.png…]()
](url)

**Comment by MXT-dudu** [comment]
> > Uploading 字样消失的话链接也没了呀
> 
> 把消息粘贴到回复框后，会看到 ，随后等到 Uploading 消失，就可以点 Comment 上传了`[Uploading XXXXXX]`

会了，谢了

**Comment by MXT-dudu** [comment]
@allMagicNB 
<img width="581" alt="屏幕截图 2024-01-26 154904" src="https://github.com/Hex-Dragon/PCL2/assets/157788806/be4dbe7c-b327-49be-80b2-2dfbc6a22f37">就是这样的

**Comment by burningtnt** [comment]
送走吧，网络问题

**Comment by allMagicNB** [comment]
可是一个协作者也没有……

**Comment by MXT-dudu** [comment]
> 送走吧，网络问题

但是其他的东西都能正常运行啊，游戏内除了没皮肤都正常的啊……

**Comment by allMagicNB** [comment]
> > 送走吧，网络问题
> 
> 但是其他的东西都能正常运行啊，游戏内除了没皮肤都正常的啊……

那我出个小bug整个启动器还能全崩了？

**Comment by MXT-dudu** [comment]
> > > 送走吧，网络问题
> > 
> > 
> > 但是其他的东西都能正常运行啊，游戏内除了没皮肤都正常的啊……
> 
> 那我出个小bug整个启动器还能全崩了？

好吧

**Comment by allMagicNB** [comment]
没有完成的不要Close as complete……

**Comment by MXT-dudu** [comment]
> 没有完成的不要Close as complete……

新人，理解一下……那现在怎么办……重装电脑有用吗

**Comment by allMagicNB** [comment]
> > 没有完成的不要Close as complete……
> 
> 新人，理解一下……那现在怎么办……重装电脑有用吗

基本没多大用，反正是网络问题

**Comment by MXT-dudu** [comment]
> > > 没有完成的不要Close as complete……
> > 
> > 
> > 新人，理解一下……那现在怎么办……重装电脑有用吗
> 
> 基本没多大用，反正是网络问题
彳亍

**Comment by MXT-dudu** [comment]
> > > 没有完成的不要Close as complete……
> > 
> > 
> > 新人，理解一下……那现在怎么办……重装电脑有用吗
> 
> 基本没多大用，反正是网络问题

彳亍

**Comment by WorldHim** [comment]
> 没有完成的不要Close as complete……

bot 会改过来的

**Comment by allMagicNB** [comment]
> > 没有完成的不要Close as complete……
> 
> bot 会改过来的

确实，这样也算是最省事的方案
~~但是Bot会挂啊，前几天刚没一次~~

**Comment by deep-dark-forest** [comment]
> > > 没有完成的不要Close as complete……
> > 
> > bot 会改过来的
> 
> 确实，这样也算是最省事的方案
> ~~但是Bot会挂啊，前几天刚没一次~~

~~没事啊，挂了就挂了呗，协作者这不来了吗~~
