### ISSUE TITLE
删除正版登录账号后账号仍存在于框内

### ISSUE THREAD

**Issue by MGWtino0** [Hex-Dragon/PCL2#3198]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

删除正版账号后账号仍存在于框内，点击登录后报错

### 重现步骤

启动PCL2后，在已经完成正版登录的情况下，点击切换账号：
![image](https://github.com/Hex-Dragon/PCL2/assets/140265892/ecb4e39a-7012-4459-aa3a-55bd96a562d1)

先选择已经登录的正版账号，
再在下拉栏内将已登录的正版登录账号删除：
![image](https://github.com/Hex-Dragon/PCL2/assets/140265892/84c558dd-fca7-4210-b481-684e22d7015e)
![image](https://github.com/Hex-Dragon/PCL2/assets/140265892/a9b78ade-a00d-487c-9a4c-3063ffab8dbe)
![image](https://github.com/Hex-Dragon/PCL2/assets/140265892/656d7047-f8ef-4aae-b242-302298aabf24)
此时框内正版账号仍显示，但正版账号已被删除
点击登录：
![屏幕截图 2024-01-26 184534](https://github.com/Hex-Dragon/PCL2/assets/140265892/7b0441bf-8753-4c8f-9cf5-0bf879725239)

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14063996/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14063998/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14063999/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14064000/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14064001/Log5.txt)

**Comment by allMagicNB** [comment]
成功复现（复现界面和Author描述的截屏一样，故不再重新发送

**Comment by SALTWOOD** [comment]
**成功复现**

**Comment by allMagicNB** [comment]
识别码是这个吗？
009C-425F-F321-6751

**Comment by MGWtino0** [comment]
是的

**Comment by LTCatt** [comment]
你的解锁码：taYcCzuhRabFh9T/Iacs3SWVhC/HCloy
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
