### ISSUE TITLE
支持玩家投稿主题

### ISSUE THREAD

**Issue by GOhaochen** [Hex-Dragon/PCL2#3202]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

允许玩家制作主题，并在GitHub页面上投稿主题，经过龙猫和公投的判定后合格的在下一个版本中允许使用特定方式激活并使用
实现本功能需要龙猫提供一个主题模板以及相应的代码模板

### 原因

提高玩家参与感，加强玩家的粘性

**Comment by zkitefly** [comment]
额

https://github.com/Hex-Dragon/PCL2/discussions/2528

**Comment by allMagicNB** [comment]
没必要，本身的设置能改多少呢？

**Comment by allMagicNB** [comment]
> 额
> 
> https://github.com/Hex-Dragon/PCL2/discussions/2528
> 
> ~~你是 2G 网吗~~

#2528 是自定义主页……~~算主题吗~~（？

**Comment by zkitefly** [comment]
> > 额
> > #2528
> > ~你是 2G 网吗~
> 
> #2528 是自定义主页……~算主题吗~（？

哦，原来是主题吗，我看错了了（抱歉

**Comment by allMagicNB** [comment]
但是有点没必要，主题能改的又有多少呢？

**Comment by deep-dark-forest** [comment]
不过加这个功能你确定不会导致主题色功能被不合理使用？相避免只能加在快照版中，但是快照版的用户相对较少……

**Comment by allMagicNB** [comment]
> 不过加这个功能你确定不会导致主题色功能被不合理使用？相避免只能加在快照版中，但是快照版的用户相对较少……

你这一说我觉得龙猫不通过的概率上升至100%
确实有可能会被滥用，而且主题不是快照版独占吗……顶多是快照版用户互相搞着玩玩？

**Comment by iPodtouch6557** [comment]
之前龙猫不是承诺过把主题功能进行大改吗，建议先把那个画出来的饼填了再说，
等龙猫怎么看，我觉得挂个暂缓处理吧

**Comment by deep-dark-forest** [comment]
> 之前龙猫不是承诺过把主题功能进行大改吗，建议先把那个画出来的饼填了再说，
> 等龙猫怎么看，我觉得挂个暂缓处理吧

“暂缓处理”

**Comment by iPodtouch6557** [comment]
> > 之前龙猫不是承诺过把主题功能进行大改吗，建议先把那个画出来的饼填了再说，
> > 等龙猫怎么看，我觉得挂个暂缓处理吧
> 
> “暂缓处理”有这个标签吗

投票中 前身就是 暂缓处理

**Comment by allMagicNB** [comment]
> > 之前龙猫不是承诺过把主题功能进行大改吗，建议先把那个画出来的饼填了再说，
> > 等龙猫怎么看，我觉得挂个暂缓处理吧
> 
> “暂缓处理”有这个标签吗

有个`推迟`

**Comment by Light-Beacon** [comment]
主题就顶栏和配色，自定义能改的就挺多的了...

**Comment by LTCatt** [comment]
暂时不考虑…………
