### ISSUE TITLE
增加打开上次错误日志的快捷方式

### ISSUE THREAD

**Issue by BlankAo** [Hex-Dragon/PCL2#3205]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

增加一个按钮，点击可以打开上次错误日志。

### 原因

有时候游戏闪退并弹出错误日志，但是重进就好了，这时便想根据错误日志，找到不稳定的mod/方块/玩家操作等，所以需要一个打开上次错误日志的快捷方式。

**Comment by allMagicNB** [comment]
没必要，说明这个是小概率错误，你复现一下看看喽

**Comment by WorldHim** [comment]
👀

**Comment by LTCatt** [comment]
适用的时间太少了……
