### ISSUE TITLE
启动游戏后桌面出现，一个乱码文件夹

### ISSUE THREAD

**Issue by ycxuan0517** [Hex-Dragon/PCL2#3209]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

启动游戏后，桌面上自动出现了一个名为“绗戠瑧杞‐娓告垙”的文件夹，里面（路径为Desktop\绗戠瑧杞‐娓告垙\Minecraft\.minecraft\versions\1.20.4-Forge_49.0.22\1.20.4-Forge_49.0.22-natives）中仅有一个名为“jna4967472991871597987.dll”的文件，游戏关闭后该文件消失，但文件夹仍然存在，删除文件夹后再次启动游戏，文件夹重新生成在桌面上。
![bug](https://github.com/Hex-Dragon/PCL2/assets/89504031/464f4f5d-f46e-4255-ab94-24d0b2da8283)

### 重现步骤

1、点击“启动游戏”
2、桌面上出现名为“绗戠瑧杞‐娓告垙”的文件夹

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14074906/Log1.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14074907/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14074908/Log5.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14074909/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14074910/Log3.txt)

**Comment by burningtnt** [comment]
看起来这像个游戏本地库的临时解压文件

**Comment by ycxuan0517** [comment]
补充一下背景：三个多月没玩了，今天打开后（已经更新）发现之前下载的版本全都无法启动，显示Minecraft出现错误，但卸载重新下载后可以正常启动了，所以没有提交相关Issues（但我存档都没了……），重新下载后才出现了本Issues提到的问题。

**Comment by iPodtouch6557** [comment]
我盲猜几种情况
1.跟官启的各类设置有关
2.误删文件夹
3.中病毒
4.硬件损坏
另外，一些文件时间长了确实会出现魔幻错误

**Comment by xiaoniaoawa** [comment]
> 看起来这像个游戏本地库的临时解压文件

![image](https://github.com/Hex-Dragon/PCL2/assets/112697401/e87ec68b-3043-49c5-a1fd-a72b0b5a853a)
我尝试把这段文本以Windows中文默认编码（GBK）保存，并以UTF-8打开，得到了“笑笑轩\游戏”，直接破案：他电脑中文用户名+他这个整合的mod里有需要释放临时文件的玩意扔错地方了

原因重现：
`[12:03:51.906] [Launch] Minecraft 文件夹：C:\Users\yjian\Desktop\笑笑轩\游戏\Minecraft\.minecraft\`
可以看到他的游戏目录为`Desktop\笑笑轩\游戏`
游戏里有个mod本意估计也是往`笑笑轩\游戏\Minecraft\.minecraft\`扔，但是因为编码问题，被扔到了`绗戠瑧杞‐娓告垙\Minecraft\.minecraft\`，而这个文件夹不存在，于是好心人Java创建了一份，就导致桌面出现了这玩意

**Comment by allMagicNB** [comment]
……总之，关了吧，加个第三方，另外尽量在游戏目录中不要出现中文……

**Comment by allMagicNB** [comment]
> ![image](https://github.com/Hex-Dragon/PCL2/assets/112697401/e87ec68b-3043-49c5-a1fd-a72b0b5a853a)
> 我尝试把这段文本以Windows中文默认编码（GBK）保存，并以UTF-8打开，得到了“笑笑轩\游戏”，直接破案：他电脑中文用户名+他这个整合的mod里有需要释放临时文件的玩意扔错地方了
> 
> 原因重现：
> `[12:03:51.906] [Launch] Minecraft 文件夹：C:\Users\yjian\Desktop\笑笑轩\游戏\Minecraft\.minecraft\`
> 可以看到他的游戏目录为`Desktop\笑笑轩\游戏`
> 游戏里有个mod本意估计也是往`笑笑轩\游戏\Minecraft\.minecraft\`扔，但是因为编码问题，被扔到了`绗戠瑧杞‐娓告垙\Minecraft\.minecraft\`，而这个文件夹不存在，于是好心人Java创建了一份，就导致桌面出现了这玩意
> 
> 所以龙猫把这个iessue给close吧，他应该去这个mod的仓库下面提iessue @LTCatt 

emm，ie ssue？

**Comment by allMagicNB** [comment]
> 笑死了，那大概就是 Java 没能正确处理系统路径编码

不是Java吧，是Mod搞的（

**Comment by zkitefly** [comment]
> > 笑死了，那大概就是 Java 没能正确处理系统路径编码
> 
> 不是Java吧，是Mod搞的（

Mod 不就是用 Java 写的吗？

**Comment by burningtnt** [comment]
> > 笑死了，那大概就是 Java 没能正确处理系统路径编码
> 
> 不是Java吧，是Mod搞的（

Mod 做 IO 操作的时候肯定是通过 `java.nio.Path` 或者 `java.io.File` 的，这俩会把 Java 内部的 `java.lang.String` 转成路径，至于编码，则是 Java 自己处理（这样才能“一次编译，跨平台运行”）

**Comment by allMagicNB** [comment]
> > > 笑死了，那大概就是 Java 没能正确处理系统路径编码
> > 
> > 不是Java吧，是Mod搞的（
> 
> Mod 做 IO 操作的时候肯定是通过 `java.nio.Path` 或者 `java.io.File` 的，这俩会把 Java 内部的 `java.lang.String` 转成路径，至于编码，则是 Java 自己处理（这样才能“一次编译，跨平台运行”）

所以搞半天是Java的Bug？

**Comment by xiaoniaoawa** [comment]
是的（（（

Tips: Get Outlook for iOS<https://aka.ms/o0ukef> Here!
________________________________
发件人: allMagic ***@***.***>
发送时间: Tuesday, January 30, 2024 7:32:13 PM
收件人: Hex-Dragon/PCL2 ***@***.***>
抄送: xiaoniao_ ***@***.***>; Comment ***@***.***>
主题: Re: [Hex-Dragon/PCL2] 启动游戏后桌面出现，一个乱码文件夹 (Issue #3209)


笑死了，那大概就是 Java 没能正确处理系统路径编码

不是Java吧，是Mod搞的（

Mod 做 IO 操作的时候肯定是通过 java.nio.Path 或者 java.io.File 的，这俩会把 Java 内部的 java.lang.String 转成路径，至于编码，则是 Java 自己处理（这样才能“一次编译，跨平台运行”）

所以搞半天是Java的Bug？

―
