### ISSUE TITLE
1.20.3+ 使用低版本 JRE 8 无法安装 Forge

### ISSUE THREAD

**Issue by vcvcOTZ** [Hex-Dragon/PCL2#3211]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

1.20.4与1.20.3使用自动安装安装forge时报错，其余版本我试下来基本都可以安装 下载源选择官方源
表现为先卡在→ 安装 Mod 加载器（方式 A）60% 后重新读条卡在38% 然后就会报错失败

![image](https://github.com/Hex-Dragon/PCL2/assets/29010818/39b1b435-548f-41f5-aafc-10c9c103eb5b)
![image](https://github.com/Hex-Dragon/PCL2/assets/29010818/06b7946d-66fe-4142-a76f-6af9b2f291fb)
![image](https://github.com/Hex-Dragon/PCL2/assets/29010818/171a664a-ad08-4a63-9b28-3330402e4b09)

### 重现步骤

1、自动安装选中1.20.4或1.20.3 forge选中最新版本
2、点击开始安装

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14075004/Log1.txt)

**Comment by allMagicNB** [comment]
这是个人网络原因，和启动器没有关系

**Comment by vcvcOTZ** [comment]
> 这是个人网络原因，和启动器没有关系

我在下载时已经使用了vpn 且为何仅有这两个版本不能安装？

**Comment by allMagicNB** [comment]
成功复现，但是还暂时不确定为PCL的问题

**Comment by allMagicNB** [comment]
**HMCL未出现此Bug**

**Comment by LTCatt** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/cebe890f-6853-424b-b82c-74561be37354)
无法复现，可能真的是网络原因？

**Comment by allMagicNB** [comment]
或许我一开始的猜想就是对的……

**Comment by vcvcOTZ** [comment]
尝试用朋友的电脑安装 确实无法复现 是否是因为我电脑java环境的问题？

**Comment by allMagicNB** [comment]
> 尝试用朋友的电脑安装 确实无法复现 是否是因为我电脑java环境的问题？

这个，Java环境没多大影响……

**Comment by allMagicNB** [comment]
可能会是吧……这是个`.jar`的Forge安装包……

**Comment by allMagicNB** [comment]
只有两种可能
⒈Java问题：执行`.jar`安装包时Java出错
⒉网络问题：下载到的`.jar`文件不完整

**Comment by allMagicNB** [comment]
测试出来了，更换使用的Java后成功下载

**Comment by allMagicNB** [comment]
总觉得应该改进下自动选择……

**Comment by LTCatt** [comment]
umm 需要测试一下哪些 Java 会安装不了……

**Comment by allMagicNB** [comment]
> umm 需要测试一下哪些 Java 会安装不了……

我电脑九个Java，要我来吗（@LTCatt

**Comment by allMagicNB** [comment]
（发在这个回复里然后编辑，失败为粗体）
JRE8（8.0.51），64位，微软原生启动器自动安装
JRE8（8.0.401），64位，Java官网下载页面下载安装
JRE8（8.0.401），64位，JDK安装目录中带的JRE
JDK8（8.0.401），64位，Oracle官网下载安装
JDK16（16.0.1），64位，微软原生启动器自动安装
JDK17（17.0.10），64位，Oracle官网Java下载页面下载安装
JDK17（17.0.10），64位，微软的OpenJDK项目（HMCL在没有Java时会推荐安装这个）
JDK17（17.0.8），64位，微软原生启动器自动安装
JDK21（21.0.2），64位，Oracle官网Java下载页面下载安装
已测试到1项

**Comment by allMagicNB** [comment]
从Author的日志来看，也是使用的JRE8（8.0.51），其他安装均正常

**Comment by LTCatt** [comment]
会不会是 JRE 8 中版本比较低的安不了？

**Comment by allMagicNB** [comment]
> 会不会是 JRE 8 中版本比较低的安不了？

我找找历史版本试试……？

**Comment by allMagicNB** [comment]
[Java历史版本安装包下载](https://www.oracle.com/java/technologies/downloads/archive/)

**Comment by allMagicNB** [comment]
草，Java8u51安装包炸了

**Comment by SALTWOOD** [comment]
复现成功，表现为Java Runtime Environment 8 Update 51 安装 1.20.3_Forge-49.0.2 时 出错

下载 Forge 49.0.2失败
→ 安装 Mod 加载器（方式 A）失败
→ 安装新 Forge 版本失败
→ 运行 Forge 安装器失败
→ Forge 安装器出错，日志结束部分为：
  Processor failed, invalid outputs:
    C:\Users\SALTWOOD\AppData\Local\Temp\PCL\Install\1322651306\libraries\net\minecraft\client\1.20.3-20231205.124940\client-1.20.3-20231205.124940-srg.jar
      Expected: 9802dcc5ca3e0160fb1c03fdbd8070e05d7b9e6b
      Actual:   ce4ab2a9b4693a95b98426be7f1d51dce0b921bc
false
   在 PCL.ModDownloadLib._Closure$__37-0._Lambda$__7(LoaderTask`2 Task)
   在 PCL.ModLoader.LoaderTask`2._Closure$__13-0._Lambda$__0()
   在 PCL.ModDownloadLib._Closure$__37-0._Lambda$__7(LoaderTask`2 Task)
   在 PCL.ModDownloadLib.ForgeInjector(String Target, LoaderTask`2 Task, String McFolder, Boolean UseJavaWrapper)
   在 PCL.ModDownloadLib._Closure$__37-0._Lambda$__7(LoaderTask`2 Task)


[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14082112/Log1.txt)

**Comment by allMagicNB** [comment]
已测试Java8u202，**安装成功**

**Comment by allMagicNB** [comment]
总结：**Forge安装器从49.0.1开始不支持JRE8u51及以下的JRE8**

**Comment by allMagicNB** [comment]
> > 总结：**Forge安装器从49.0.1开始不支持JRE8u51及以下的JRE8** @LTCatt 
> 
> 好奇相同条件下其他启动器可否安装成功

反正HMCL的自动选择没啥问题，我试试

**Comment by hejiehao** [comment]
> > > 总结：**Forge安装器从49.0.1开始不支持JRE8u51及以下的JRE8** @LTCatt
> > 
> > 
> > 好奇相同条件下其他启动器可否安装成功
> 
> 反正HMCL的自动选择没啥问题，我试试

逝逝 ForgeWrapper

**Comment by zkitefly** [comment]
> HMCL：安装成功，Java选择了JRE8u51，猜测Java选项只是启动游戏时使用的Java

你可以去 HMCL 导出的日志查看使用的是什么 JVM 安装

**Comment by allMagicNB** [comment]
> > HMCL：安装成功，Java选择了JRE8u51，猜测Java选项只是启动游戏时使用的Java
> 
> 你可以去 HMCL 导出的日志查看使用的是什么 JVM 安装

日志在哪……

**Comment by allMagicNB** [comment]
> > HMCL：安装成功，Java选择了JRE8u51，猜测Java选项只是启动游戏时使用的Java
> 
> 你可以去 HMCL 导出的日志查看使用的是什么 JVM 安装

全都是英文……

**Comment by allMagicNB** [comment]
> > HMCL：安装成功，Java选择了JRE8u51，猜测Java选项只是启动游戏时使用的Java
> 
> 你可以去 HMCL 导出的日志查看使用的是什么 JVM 安装

全都是英文……

**Comment by hejiehao** [comment]
> > > HMCL：安装成功，Java选择了JRE8u51，猜测Java选项只是启动游戏时使用的Java
> > 
> > 
> > 你可以去 HMCL 导出的日志查看使用的是什么 JVM 安装
> 
> 全都是英文……

那你发给我吧

**Comment by allMagicNB** [comment]
[hmcl-exported-logs-2024-01-29T22-26-38.log](https://github.com/Hex-Dragon/PCL2/files/14085515/hmcl-exported-logs-2024-01-29T22-26-38.log)

**Comment by hejiehao** [comment]
C:\\Program Files\\Java\\jdk-17\\bin\\java.exe

**Comment by allMagicNB** [comment]
~~草，突然发现查找java.exe一个一个看就可以找到了~~

**Comment by zkitefly** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/64117916/036201ff-4854-44b3-9d8c-ab2e211f695c)

我认为你应该在全局和特定游戏设置中选择 Java 路径

**Comment by allMagicNB** [comment]
> ![image](https://github.com/Hex-Dragon/PCL2/assets/64117916/036201ff-4854-44b3-9d8c-ab2e211f695c)
> 
> 我认为你应该在全局和特定游戏设置中选择 Java 路径

有没有一种可能，这就是全局

**Comment by zkitefly** [comment]
> > ![image](https://private-user-images.githubusercontent.com/64117916/300498069-036201ff-4854-44b3-9d8c-ab2e211f695c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1Mzk1NzYsIm5iZiI6MTcwNjUzOTI3NiwicGF0aCI6Ii82NDExNzkxNi8zMDA0OTgwNjktMDM2MjAxZmYtNDg1NC00NGIzLTlkOGMtYWIyZTIxMWY2OTVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDE0NDExNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjMTFlYjBjZTQ4ZmRjMTY1Nzc4NGZlNTQ5NDliMzc5ODU4YzgzY2VjZmY3NWQ4YTRjOWM5OTdhYTFkNWQ2YzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q6s5vgFgn0PA-4cdu6V8SF5nDDaTBhn_jLqs75wnoic)
> > 我认为你应该在**全局和特定**游戏设置中选择 Java 路径
> 
> 有没有一种可能，这就是全局

**Comment by allMagicNB** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/64117916/300498069-036201ff-4854-44b3-9d8c-ab2e211f695c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1Mzk1NzYsIm5iZiI6MTcwNjUzOTI3NiwicGF0aCI6Ii82NDExNzkxNi8zMDA0OTgwNjktMDM2MjAxZmYtNDg1NC00NGIzLTlkOGMtYWIyZTIxMWY2OTVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDE0NDExNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjMTFlYjBjZTQ4ZmRjMTY1Nzc4NGZlNTQ5NDliMzc5ODU4YzgzY2VjZmY3NWQ4YTRjOWM5OTdhYTFkNWQ2YzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q6s5vgFgn0PA-4cdu6V8SF5nDDaTBhn_jLqs75wnoic)
> > > 我认为你应该在→**全局和特定**←游戏设置中选择 Java 路径
> > 
> > 有没有一种可能，这就是全局
> 
> 

我都没下载下来怎么调整特定游戏设置？？？

**Comment by hejiehao** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/98140773/cc5873bb-a491-4db6-8097-a451b45f091d)
发了神马玩应

**Comment by hejiehao** [comment]
如果把其他 Java 卸载，只留下 JRE8u51，会发生什么？

**Comment by allMagicNB** [comment]
> 如果把其他 Java 卸载，只留下 JRE8u51，会发生什么？

……虚拟机：你好

**Comment by zkitefly** [comment]
看了下源码，似乎 HMCL 是根据自身使用的 Java 来安装 Forge 的

![image](https://github.com/Hex-Dragon/PCL2/assets/64117916/6f8ccc73-0787-4ea4-8a5e-92a2375d5981)

![image](https://github.com/Hex-Dragon/PCL2/assets/64117916/036201ff-4854-44b3-9d8c-ab2e211f695c)

![image](https://github.com/Hex-Dragon/PCL2/assets/64117916/3bd70bbf-124b-4819-b413-8db656fe5191)

**Comment by allMagicNB** [comment]
> 看了下源码，似乎 HMCL 是根据自身使用的 Java 来安装 Forge 的
> 
> ![image](https://github.com/Hex-Dragon/PCL2/assets/64117916/6f8ccc73-0787-4ea4-8a5e-92a2375d5981)
> 
> ![image](https://github.com/Hex-Dragon/PCL2/assets/64117916/036201ff-4854-44b3-9d8c-ab2e211f695c)
> 
> ![image](https://github.com/Hex-Dragon/PCL2/assets/64117916/3bd70bbf-124b-4819-b413-8db656fe5191)
> 

看了眼taskmgr，还真是（

**Comment by allMagicNB** [comment]
> 如果把其他 Java 卸载，只留下 JRE8u51，会发生什么？

HMCL会叫你下载微软的OpenJDK

**Comment by SALTWOOD** [comment]
> > 如果把其他 Java 卸载，只留下 JRE8u51，会发生什么？
> 
> HMCL会叫你下载微软的OpenJDK

改源码让它强制使用？

**Comment by allMagicNB** [comment]
> > > 如果把其他 Java 卸载，只留下 JRE8u51，会发生什么？
> > 
> > HMCL会叫你下载微软的OpenJDK
> 
> 改源码让它强制使用？

……HMCL直接炸

**Comment by SALTWOOD** [comment]
@allMagicNB 那改源码让 HMCL 用别的 Java 安装？或者手动命令行（

**Comment by allMagicNB** [comment]
> @allMagicNB 那改源码让 HMCL 用别的 Java 安装？或者手动命令行（

……你看我像会Java的样吗？

**Comment by zkitefly** [comment]
> > @allMagicNB 那改源码让 HMCL 用别的 Java 安装？或者手动命令行（
> 
> ……你看我像会Java的样吗？

你只需要在终端输入 `C:\Program Files\Java\jre1.8.0_51\bin\java.exe -jar HMCL.exe` 就可以指定这个 Java 来启动 HMCL

**Comment by allMagicNB** [comment]
> > > @allMagicNB 那改源码让 HMCL 用别的 Java 安装？或者手动命令行（
> > 
> > ……你看我像会Java的样吗？
> 
> 你只需要在终端输入 `C:\Program Files\Java\jre1.8.0_51\bin\java.exe -jar HMCL.exe` 就可以指定这个 Java 来启动 HMCL

我HMCL没在同个目录下，我试试（

**Comment by allMagicNB** [comment]
成功……地失败了
![image](https://github.com/Hex-Dragon/PCL2/assets/116283787/afba69ef-8208-47e4-96b9-2e84bcff965b)

**Comment by zkitefly** [comment]
> 成功……地失败了 ![image](https://private-user-images.githubusercontent.com/116283787/300703448-afba69ef-8208-47e4-96b9-2e84bcff965b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1OTcwMTEsIm5iZiI6MTcwNjU5NjcxMSwicGF0aCI6Ii8xMTYyODM3ODcvMzAwNzAzNDQ4LWFmYmE2OWVmLTgyMDgtNDdlNC05NmI5LTJlODRiY2ZmOTY1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMFQwNjM4MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOWRhNjZkZmE5OTBjMmQ4YWEyOWUxMTgyMGMxZDQ5YTdkNzNlNDc2YzIzOWZjYzlkMjA5MzgzZmUwN2Y1ODljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ec1MoG4Mm_6HcqABz5jnWvCFAbH2ZrqIj3Q33vUhbXc)

日志

**Comment by vcvcOTZ** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/29010818/24efac26-3647-4cba-87da-fed2c000bce6)

**Comment by allMagicNB** [comment]
> ![image](https://private-user-images.githubusercontent.com/29010818/300707071-24efac26-3647-4cba-87da-fed2c000bce6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1OTc4OTMsIm5iZiI6MTcwNjU5NzU5MywicGF0aCI6Ii8yOTAxMDgxOC8zMDA3MDcwNzEtMjRlZmFjMjYtMzY0Ny00Y2JhLTg3ZGEtZmVkMmMwMDBiY2U2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDA2NTMxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxMTljZTJkYThlNjA3Yzk3N2I3ZjczYTA2ZmYzNzc1YWUyNDViZjY0N2ZkYmU3YjEyN2I2OTRjMGE1ZTY5NGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RJjI7GuZ3kTOduk7kXo9tRmw3FByPTT6a7t576r2lec)

你想表达什么？

**Comment by zkitefly** [comment]
似乎和PCL的输出差不多？

**Comment by vcvcOTZ** [comment]
对 都是校验出错

**Comment by zkitefly** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/64117916/5b6c4be1-88d1-444f-9cb6-ff443b9ba462)

![image](https://github.com/Hex-Dragon/PCL2/assets/64117916/590f5d7e-b823-4aa0-8210-5adcd4e83638)

**Comment by vcvcOTZ** [comment]
基本上确定是java版本的问题了

**Comment by allMagicNB** [comment]
Forge校验自己文件时出错？

**Comment by zkitefly** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/64117916/d51549f9-b8ea-4652-91cd-b89d8f1b9130)

**Comment by 1753449579** [comment]
使用JDK 18
![000](https://github.com/Hex-Dragon/PCL2/assets/90882660/1517c828-25e0-4576-a444-5718b341c1f6)

**Comment by zkitefly** [comment]
> 使用JDK 18
> ![000](https://github.com/Hex-Dragon/PCL2/assets/90882660/1517c828-25e0-4576-a444-5718b341c1f6)
> 

看起来是你的网络问题导致，并不是安装器出错？

**Comment by 1753449579** [comment]
> > 使用JDK 18
> > ![000](https://private-user-images.githubusercontent.com/90882660/302593640-1517c828-25e0-4576-a444-5718b341c1f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMTk4ODgsIm5iZiI6MTcwNzIxOTU4OCwicGF0aCI6Ii85MDg4MjY2MC8zMDI1OTM2NDAtMTUxN2M4MjgtMjVlMC00NTc2LWE0NDQtNTcxOGIzNDFjMWY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDExMzk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0NmY0NmM5MjE5ZmMwMWM2ZWNhOTE2NzZhNGUyMmE5ZDlkNmFjOGU2YWFkOGRhMWJhMmQ3MWE3Yzc2ZTlhZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lWH1qglw-8Dcxr28xXFHzQEuiXm4oh9BcHN3rARCooI)
> 
> 看起来是你的网络问题导致，并不是安装器出错？

ok，谢谢大佬，确实是网络问题

**Comment by allMagicNB** [comment]
感觉主要都是我在测试……电脑里面一堆不同版本的JRE8，又怕啥时候又要复现用到，不敢卸载……

**Comment by vcvcOTZ** [comment]
识别码:8E76-044B-B6C4-E6B7  谢谢

**Comment by LTCatt** [comment]
你的解锁码：dCq9lHJgdYtyiA2kdwWXrrQRWWm6a4oy
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
