### ISSUE TITLE
我选择了下载使用官方源, 但请求的还是mcbbs 为什么?

### ISSUE THREAD

**Issue by you-hengh** [Hex-Dragon/PCL2#3213]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我选择了下载使用官方源, 但请求的还是mcbbs 为什么?

![2024-01-28_14-43-33](https://github.com/Hex-Dragon/PCL2/assets/34816426/4798e98d-1d19-4e41-a510-2bbb5be08e2a)

最终下载是失败的

PCL 版本

![2024-01-28_14-47-44](https://github.com/Hex-Dragon/PCL2/assets/34816426/eb70737a-4270-44f0-b3a6-bf7f2a2606fc)

### 重现步骤

就是下载安装游戏版本

### 日志与附件

下载原版 1.20.1失败
→ 下载原版资源文件失败
→ 下载资源文件（副加载器）失败
→ 基础连接已经关闭: 未能为 SSL/TLS 安全通道建立信任关系。
→ 根据验证过程，远程证书无效。
   在 PCL.ModNet.NetFile.Thread(NetThread Info)
错误类型：System.Security.Authentication.AuthenticationException

**Comment by allMagicNB** [comment]
这个应该放讨论吧……毕竟那是**尽量使用官方源**

**Comment by Tactsohg** [comment]
同遇到此问题，看了眼源码，原版Assets下载部分走的是MCBBS->官方源->BMCL API这样的**固定下载源顺序**，不会受此选项影响，所以无论如何都会先走MCBBS源下载，如果资源文件很多超过2000个的话就会强制失败。

等一个修复。

**Comment by zkitefly** [comment]
> > 同遇到此问题，看了眼源码，原版Assets下载部分走的是MCBBS->官方源->BMCL API这样的**固定下载源顺序**，不会受此选项影响，所以无论如何都会先走MCBBS源下载，如果资源文件很多超过2000个的话就会强制失败。
> > 等一个修复。
> 
> 那这么说这个选项就是摆设喽？怪不得我看有些人在b站上说pcl即使是换成官方源也不好使，但是官方启动器却能用

并不是，如果其中一个下载源下载失败了，会跳转至下一个下载源，直至全部都试过（应该吧

**Comment by allMagicNB** [comment]
> > > 同遇到此问题，看了眼源码，原版Assets下载部分走的是MCBBS->官方源->BMCL API这样的**固定下载源顺序**，不会受此选项影响，所以无论如何都会先走MCBBS源下载，如果资源文件很多超过2000个的话就会强制失败。
> > > 等一个修复。
> > 
> > 那这么说这个选项就是摆设喽？怪不得我看有些人在b站上说pcl即使是换成官方源也不好使，但是官方启动器却能用
> 
> 并不是，如果其中一个下载源下载失败了，会跳转至下一个下载源，直至全部都试过（应该吧

要不然你猜为什么是“尽量”[doge]

**Comment by Tactsohg** [comment]
> > 同遇到此问题，看了眼源码，原版Assets下载部分走的是MCBBS->官方源->BMCL API这样的**固定下载源顺序**，不会受此选项影响，所以无论如何都会先走MCBBS源下载，如果资源文件很多超过2000个的话就会强制失败。
> > 等一个修复。
> 
> 那这么说这个选项就是摆设喽？怪不得我看有些人在b站上说pcl即使是换成官方源也不好使，但是官方启动器却能用

选项本身应该还是有用的，这块大概是忘记改了，又刚好在这次大规模报错遇到了。

**Comment by Tactsohg** [comment]
> > > 同遇到此问题，看了眼源码，原版Assets下载部分走的是MCBBS->官方源->BMCL API这样的**固定下载源顺序**，不会受此选项影响，所以无论如何都会先走MCBBS源下载，如果资源文件很多超过2000个的话就会强制失败。
> > > 等一个修复。
> > 
> > 
> > 那这么说这个选项就是摆设喽？怪不得我看有些人在b站上说pcl即使是换成官方源也不好使，但是官方启动器却能用
> 
> 并不是，如果其中一个下载源下载失败了，会跳转至下一个下载源，直至全部都试过（应该吧

请检查https://github.com/Hex-Dragon/PCL2/blob/8c8b1066bff6476a14437a14bc16a281e25145bd/Plain%20Craft%20Launcher%202/Modules/Minecraft/ModMinecraft.vb#L2188C40-L2188C59

**Comment by deep-dark-forest** [comment]
> > > > 同遇到此问题，看了眼源码，原版Assets下载部分走的是MCBBS->官方源->BMCL API这样的**固定下载源顺序**，不会受此选项影响，所以无论如何都会先走MCBBS源下载，如果资源文件很多超过2000个的话就会强制失败。
> > > > 等一个修复。
> > > 
> > > 那这么说这个选项就是摆设喽？怪不得我看有些人在b站上说pcl即使是换成官方源也不好使，但是官方启动器却能用
> > 
> > 并不是，如果其中一个下载源下载失败了，会跳转至下一个下载源，直至全部都试过（应该吧
> 
> 要不然你猜为什么是“尽量”[doge]

但是这个尽量有点太……还有就是pcl宁可用mcbbs也不用官方源意思是说mcbbs能正常下载？

**Comment by zkitefly** [comment]
> > > > > 同遇到此问题，看了眼源码，原版Assets下载部分走的是MCBBS->官方源->BMCL API这样的**固定下载源顺序**，不会受此选项影响，所以无论如何都会先走MCBBS源下载，如果资源文件很多超过2000个的话就会强制失败。
> > > > > 等一个修复。
> > > > 
> > > > 
> > > > 那这么说这个选项就是摆设喽？怪不得我看有些人在b站上说pcl即使是换成官方源也不好使，但是官方启动器却能用
> > > 
> > > 
> > > 并不是，如果其中一个下载源下载失败了，会跳转至下一个下载源，直至全部都试过（应该吧
> > 
> > 
> > 要不然你猜为什么是“尽量”[doge]
> 
> 但是这个尽量有点太……还有就是pcl宁可用mcbbs也不用官方源意思是说mcbbs能正常下载？

因为 mcbbs 稳定快速（除了这次），毕竟 PCL 不是专为国内使用者的吗

**Comment by Tactsohg** [comment]
> > > 同遇到此问题，看了眼源码，原版Assets下载部分走的是MCBBS->官方源->BMCL API这样的**固定下载源顺序**，不会受此选项影响，所以无论如何都会先走MCBBS源下载，如果资源文件很多超过2000个的话就会强制失败。
> > > 等一个修复。
> > 
> > 
> > 那这么说这个选项就是摆设喽？怪不得我看有些人在b站上说pcl即使是换成官方源也不好使，但是官方启动器却能用
> 
> 并不是，如果其中一个下载源下载失败了，会跳转至下一个下载源，直至全部都试过（应该吧

根据日志的输出情况，在下载资源文件时，是在所有资源文件都下载失败后才会切换下一个下载源的，而如果资源文件失败超过2000个就直接强制结束弹出报错了（这部分我没有查看代码的逻辑，因为我不熟悉VB.net语言，研究起来太头疼了= =）。

**Comment by Tactsohg** [comment]
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14076080/Log1.txt)

放一个启动器日志在这里，总之问题在于，资源文件过多时下载失败不会尝试切换下载源（也许应该每个下载源单独设置一个失败计数器？这样至少能保证尝试过所有的下载源），而且设置中的官方源优先选项不会对资源下载生效。

**Comment by deep-dark-forest** [comment]
我建议简单粗暴直接选什么下载源就是什么下载源，然后mcbbs和bmclapi可以共用一个选项，不然有点乱

**Comment by allMagicNB** [comment]
> 我建议简单粗暴直接选什么下载源就是什么下载源，然后mcbbs和bmclapi可以共用一个选项，不然有点乱

不要合吧，如果其中一个出错，用户不想绕弯路直接下载，会想要单独选项的……

**Comment by SALTWOOD** [comment]
建议：“仅官方源”、“仅MCBBS”、“仅BMCLAPI”、“自动选择”，不要使用“尽量使用官方源”这样表达模糊、逻辑容易出问题的设计

**Comment by allMagicNB** [comment]
> 建议：“仅官方源”、“仅MCBBS”、“仅BMCLAPI”、“自动选择”，不要使用“尽量使用官方源”这样表达模糊、逻辑容易出问题的设计

但是这样改对小白不友好

**Comment by SALTWOOD** [comment]
> > 建议：“仅官方源”、“仅MCBBS”、“仅BMCLAPI”、“自动选择”，不要使用“尽量使用官方源”这样表达模糊、逻辑容易出问题的设计
> 
> 但是这样改对小白不友好

小白会知道选用什么源？这个已经属于对有基础的人的设置了
小白是能下就行，默认自动选择即可

**Comment by allMagicNB** [comment]
> > > 建议：“仅官方源”、“仅MCBBS”、“仅BMCLAPI”、“自动选择”，不要使用“尽量使用官方源”这样表达模糊、逻辑容易出问题的设计
> > 
> > 但是这样改对小白不友好
> 
> 小白会知道选用什么源？这个已经属于对有基础的人的设置了
> 小白是能下就行，默认自动选择即可

所以仅仅只是增加高级选项？

**Comment by SALTWOOD** [comment]
@allMagicNB 就是说，PCL2 现在这个“下载来源”设置本身就有很多不合理之处，我的意见是直接把这个选项改成具体的下载源选择，小白没有需求（只要能下载就行）那就默认“自动选择”，这个源不行就换一个，有需求的人会自己调节。

增加一个高级选项，作用重叠，不好

现在已经叠了三层回复了，不要再叠了

**Comment by allMagicNB** [comment]
> @allMagicNB 就是说，PCL2 现在这个“下载来源”设置本身就有很多不合理之处，我的意见是直接把这个选项改成具体的下载源选择，小白没有需求（只要能下载就行）那就默认“自动选择”，这个源不行就换一个，有需求的人会自己调节。
> 
> 增加一个高级选项，作用重叠，不好
> 
> 现在已经叠了三层回复了，不要再叠了

不是，本身PCL2的三个下载选项都是自动选择……

**Comment by SALTWOOD** [comment]
> > @allMagicNB 就是说，PCL2 现在这个“下载来源”设置本身就有很多不合理之处，我的意见是直接把这个选项改成具体的下载源选择，小白没有需求（只要能下载就行）那就默认“自动选择”，这个源不行就换一个，有需求的人会自己调节。
> > 增加一个高级选项，作用重叠，不好
> > 现在已经叠了三层回复了，不要再叠了
> 
> 不是，本身PCL2的三个下载选项都是自动选择……

所以就是这个意思，改成手动自动结合，别啥都PCL做完了用户没有一点选择权（？

**Comment by Tactsohg** [comment]
你们不会觉得选了“尽量使用官方源”后依然优先使用镜像源是刻意设计的吧，这是个bug，而且只有部分文件会触发这个bug，修好了就正常用了。

**Comment by deep-dark-forest** [comment]
“仅bmclapi”我感觉不应该被添加吧，因为bmcl承受不住那么大的流量

**Comment by Tactsohg** [comment]
哦我傻了，那个改下载源的选项叫“版本列表获取”，所以根本不会影响下载各种文件的下载源顺序= =那没事了。

**Comment by vcvcOTZ** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/29010818/4764970f-96da-4705-b59b-36948d895cb9)
感觉弄成hmcl这样就挺好的 给用户个选择

**Comment by you-hengh** [comment]
> ![image](https://private-user-images.githubusercontent.com/29010818/300490119-4764970f-96da-4705-b59b-36948d895cb9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1NzYwMzQsIm5iZiI6MTcwNjU3NTczNCwicGF0aCI6Ii8yOTAxMDgxOC8zMDA0OTAxMTktNDc2NDk3MGYtOTZkYS00NzA1LWI1OWItMzY5NDhkODk1Y2I5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDAwNDg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyOTQ0YjgyODJjZTg2NWEzNDlkYzg1NzA1MWY3ODU5NzY5MWNhOTQzZmU4YmZkMjYzOWZmZDFlZjg3Yzg2NmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z0ONnVj0m4YS4TyBRh5n2PdBCq_uU7crvh6D7Fwjr1s) 感觉弄成hmcl这样就挺好的 给用户个选择

没什么用, 我用hcml下载了  同样下载不下来 一样还是请求mcbbs

**Comment by zkitefly** [comment]
> > ![image](https://private-user-images.githubusercontent.com/29010818/300490119-4764970f-96da-4705-b59b-36948d895cb9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1NzYwMzQsIm5iZiI6MTcwNjU3NTczNCwicGF0aCI6Ii8yOTAxMDgxOC8zMDA0OTAxMTktNDc2NDk3MGYtOTZkYS00NzA1LWI1OWItMzY5NDhkODk1Y2I5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDAwNDg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyOTQ0YjgyODJjZTg2NWEzNDlkYzg1NzA1MWY3ODU5NzY5MWNhOTQzZmU4YmZkMjYzOWZmZDFlZjg3Yzg2NmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z0ONnVj0m4YS4TyBRh5n2PdBCq_uU7crvh6D7Fwjr1s) 感觉弄成hmcl这样就挺好的 给用户个选择
> 
> 没什么用, 我用hmcl下载了  同样下载不下来 一样还是请求mcbbs

He个这个问题已经有 pr 在修了

**Comment by deep-dark-forest** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/29010818/300490119-4764970f-96da-4705-b59b-36948d895cb9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1NzYwMzQsIm5iZiI6MTcwNjU3NTczNCwicGF0aCI6Ii8yOTAxMDgxOC8zMDA0OTAxMTktNDc2NDk3MGYtOTZkYS00NzA1LWI1OWItMzY5NDhkODk1Y2I5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDAwNDg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyOTQ0YjgyODJjZTg2NWEzNDlkYzg1NzA1MWY3ODU5NzY5MWNhOTQzZmU4YmZkMjYzOWZmZDFlZjg3Yzg2NmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z0ONnVj0m4YS4TyBRh5n2PdBCq_uU7crvh6D7Fwjr1s) 感觉弄成hmcl这样就挺好的 给用户个选择
> > 
> > 没什么用, 我用hmcl下载了  同样下载不下来 一样还是请求mcbbs
> 
> 这个问题已经有 pr 在修了
> 
> 但，如果取消自动选择下载源并选择官方源，重启启动器后是一定只向官方源下载（？

但，hmcl的问题处理效率可能会非常高（

**Comment by burningtnt** [comment]
> 但，hmcl的问题处理效率可能会非常高（

所以赶紧开源 PCL2，一群人写代码肯定比一个人快

**Comment by WorldHim** [comment]
> > 但，hmcl的问题处理效率可能会非常高（
> 
> 所以赶紧开源 PCL2，一群人写代码肯定比一个人快

生计

**Comment by SALTWOOD** [comment]
> > 但，hmcl的问题处理效率可能会非常高（
> 
> 所以赶紧开源 PCL2，一群人写代码肯定比一个人快

~龙猫也要生存的啊~

**Comment by SALTWOOD** [comment]
所以……要不要加一个issue请求允许选择下载源？

**Comment by rumengchuxing062** [comment]
PCL2现在就是开源的，不然你猜猜，为什么反馈移到了GitHub的Issues

**Comment by rumengchuxing062** [comment]
> > 但，hmcl的问题处理效率可能会非常高（
> 
> 所以赶紧开源 PCL2，一群人写代码肯定比一个人快

PCL2现在就是开源的，不然你猜猜，为什么反馈移到了GitHub的Issues

**Comment by xhahello** [comment]
“仅官方源”、“仅MCBBS”、“仅BMCLAPI”、“自动选择”这样子可以，小白一般没这个胆子去动，把这个放高级设置里，然后不要在每次重启时刷新这个设置

**Comment by burningtnt** [comment]
> PCL2现在就是开源的，不然你猜猜，为什么反馈移到了GitHub的Issues

很抱歉，PCL2 目前仅仅是放出了部分源代码
如果是一个开源项目，意味着人人都可以在遵循开源许可证的前提下自己修改 PCL2，并发布自己的版本

**Comment by deep-dark-forest** [comment]
> > 但，hmcl的问题处理效率可能会非常高（
> 
> 所以赶紧开源 PCL2，一群人写代码肯定比一个人快

部分开源不等于完全开源的（
你要是不理解直接看主题色和解密游戏没开源就不算完全开源

**Comment by deep-dark-forest** [comment]
> > > 但，hmcl的问题处理效率可能会非常高（
> > 
> > 所以赶紧开源 PCL2，一群人写代码肯定比一个人快
> 
> PCL2现在就是开源的，不然你猜猜，为什么反馈移到了GitHub的Issues

部分开源不等于完全开源的（
你要是不理解直接看主题色和解密游戏没开源就不算完全开源

**Comment by Tactsohg** [comment]
所以这个bug能加急修么挺影响使用的，哪怕提高一下2000次的失败上限发布个紧急patch也行啊，mcbbs都下线一个多星期了= =
大家都开始传“用正版启动器下载一遍再用PCL2就正常了”这种奇奇怪怪的偏方了= =

**Comment by burningtnt** [comment]
> 大家都开始传“用正版启动器下载一遍再用PCL2就正常了”这种奇奇怪怪的偏方了= =

这个是因为官方启动器从官方源把游戏资源下载好了…… 所以 PCL2 校验一遍，就没有再去 BMCLAPI 下这一堆文件

**Comment by Tactsohg** [comment]
> 这个是因为官方启动器从官方源把游戏资源下载好了…… 所以 PCL2 校验一遍，就没有再去 BMCLAPI 下这一堆文件

所以MC官方源真的有墙吗？我已经很久没有遇到官方源下不了东西的情况了。

**Comment by rumengchuxing062** [comment]
> > 这个是因为官方启动器从官方源把游戏资源下载好了…… 所以 PCL2 校验一遍，就没有再去 BMCLAPI 下这一堆文件
> 
> 所以MC官方源真的有墙吗？我已经很久没有遇到官方源下不了东西的情况了。

部分地区有，你可能不属于这个部分地区（我也是）

**Comment by deep-dark-forest** [comment]
> > 这个是因为官方启动器从官方源把游戏资源下载好了…… 所以 PCL2 校验一遍，就没有再去 BMCLAPI 下这一堆文件
> 
> 所以MC官方源真的有墙吗？我已经很久没有遇到官方源下不了东西的情况了。

没有全部墙，但是我这被墙了（
就好比vscode官网理论上来讲中国大陆允许访问在我这也被墙了……

**Comment by qqwxm8753000** [comment]
图酱说了，要先用官方启动器启动一遍游戏

**Comment by burningtnt** [comment]
> 图酱说了，要先用官方启动器启动一遍游戏

你在胡扯

**Comment by deep-dark-forest** [comment]
> > 图酱说了，要先用官方启动器启动一遍游戏
> 
> 你在胡扯

【当我的PCL罢工，才知道官方启动器的强大！-哔哩哔哩】 https://b23.tv/QZCdTH3

**Comment by EX3124** [comment]
> > > 图酱说了，要先用官方启动器启动一遍游戏
> > 
> > 
> > 你在胡扯
> 
> 【当我的PCL唤醒，才知道官方启动器的强大！-哔哩哔哩】https://b23.tv/QZCdTH3

不知道你是怎么来到github的,可能是这会运营商dns污染没这么严重.
然后这个视频很多点都是错的,当然这是个营销号,也不能奢求营销号给的点都是对的.

用官启能成功的原因只是 官启只有官方源,不会因为启动器逻辑问题下载失败
如果运营商dns污染不严重,你可以在官方源下载完游戏资源.
此时,启动器也可以从官方源下载完游戏资源,仅此而已.

**Comment by 8MiYile** [comment]
@burningtnt @EX3124 那个视频 我已经用我们这边的官号评论长文了 可以去点赞一下
八蓝米科技Company的

**Comment by deep-dark-forest** [comment]
> > > > 图酱说了，要先用官方启动器启动一遍游戏
> > > 
> > > 
> > > 你在胡扯
> > 
> > 
> > 【当我的PCL唤醒，才知道官方启动器的强大！-哔哩哔哩】https://b23.tv/QZCdTH3
> 
> 不知道你是怎么来到github的,可能是这会运营商dns污染没这么严重. 然后这个视频很多点都是错的,当然这是个营销号,也不能奢求营销号给的点都是对的.
> 
> 用官启能成功的原因只是 官启只有官方源,不会因为启动器逻辑问题下载失败 如果运营商dns污染不严重,你可以在官启下载完游戏资源. 此时,第三方启动器看到了 官启下载的资源 ,直接使用了 官启下载的资源,仅此而已.

非常抱歉让您误解了我的意思。我也误解了前面两位的意思，“你在胡扯”我本以为是 @burningtnt 想表达“图酱没发过这个视频，你在胡扯”这个意思，所以我就发了个这个视频的链接。然后不知为啥就被误解成了“这个视频是错误的”。我以后也会尽量避免这种表述不清的评论，非常抱歉

**Comment by burningtnt** [comment]
> > @burningtnt @EX3124 那个视频 我已经用我们这边的官号评论长文了 可以去点赞一下 八蓝米科技Company的
> 
> 从技术角度来讲，你的评论和那个视频里提出的问题其实是两回事，只要是全新安装的情况（比如视频中那样在新电脑上装MC），目前最新版的PCL2 Release 2.6.13绝对无法直接安装1.16以上的任何版本，这是PCL2本身的问题，与BMCLAPI压力大不大无关。 但是但是可以通过先安装1.15.2然后再安装高版本的方式解决，笑死，比先用官启启动一遍解决问题还好笑，我在想要不要发个视频吐槽了。 图酱提供的解决方案是完全有效的，可能有些人ky不分场合到处乱刷会比较烦人吧，但还不至于说胡扯。

我必须要指出，PCL2 目前毫无安装高版本方面的问题
对于您的问题，如果你确认自己无法安装，可以提出 Issue 并上传启动器日志。我相信 PCL2 社区能够找到根本原因

此外，请保持友善交流

**Comment by Tactsohg** [comment]
> 我必须要指出，PCL2 目前毫无安装高版本方面的问题 对于您的问题，如果你确认自己无法安装，可以提出 Issue 并上传启动器日志。我相信 PCL2 社区能够找到根本原因
> 
> 此外，请保持友善交流

**PCL2 目前毫无安装高版本方面的问题**
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14208440/Log1.txt)
这是我在**删除.minecraft以及%APPDATA%/.minecraft文件夹后**使用PCL2连续下载5次1.20.4全部失败的日志
根本原因我已经在issue中提到过了，再重复一遍吧
PCL2在下载assets时使用的是固定的下载源顺序，MCBBS->官方源->BMCLAPI
[ModMinecraft.vb#L2188C40-L2188C59](https://github.com/Hex-Dragon/PCL2/blob/8c8b1066bff6476a14437a14bc16a281e25145bd/Plain%20Craft%20Launcher%202/Modules/Minecraft/ModMinecraft.vb#L2188C40-L2188C59)
[ModDownload.vb#L944](https://github.com/Hex-Dragon/PCL2/blob/8c8b1066bff6476a14437a14bc16a281e25145bd/Plain%20Craft%20Launcher%202/Modules/Minecraft/ModDownload.vb#L944)
在全新安装的情况下，所需要下载的文件数量庞大，并且它们全部会**首先使用MCBBS源**来进行下载，正如日志中那样，你会看到一大堆向MCBBS的请求和报错，然后触发以下代码中的2000次下载失败报错。
[ModNet.vb#L1478C72-L1478C76](https://github.com/Hex-Dragon/PCL2/blob/8c8b1066bff6476a14437a14bc16a281e25145bd/Plain%20Craft%20Launcher%202/Modules/Base/ModNet.vb#L1478C72-L1478C76)

龙猫在B站说PCL2下载失败是MCBBS维护、官方源有墙、BMCLAPI压力大导致的，包括你们当中很多人也是这样认为的，那么请告诉我，我提供的日志中，PCL2在下载assets资源文件时有没有请求过MCBBS以外的下载源，这个一星期前就已经大量存在的下载失败问题，究竟是不是PCL2自身导致的问题。
我写出PCL2下载高版本有问题是因为我分析了日志、查看了代码并进行了多次不同条件下的下载实验，您又是基于什么写下**PCL2 目前毫无安装高版本方面的问题**的呢？

**Comment by burningtnt** [comment]
> 我写出PCL2下载高版本有问题是因为我分析了日志、查看了代码并进行了多次不同条件下的下载实验，您又是基于什么写下PCL2 目前毫无安装高版本方面的问题的呢？

抱歉，这是我的问题。这个 Issue 我之前没仔细看（因为我积极维护的是隔壁启动器），没有注意到 PCL2 有 2000+ 失败触发强制结束

原评论我会隐藏，避免误解，但本评论不会隐藏，以给未来的自己一个警告

**Comment by 8MiYile** [comment]
@Tactsohg 其实吧，当他能说出`mcbbs下载源是mcbbs自己做的`这番言论的时候，我才说了那种话

**Comment by OstiumAxioma** [comment]
> > > > > > 同遇到此问题，看了眼源码，原版Assets下载部分走的是MCBBS->官方源->BMCL API这样的**固定下载源顺序**，不会受此选项影响，所以无论如何都会先走MCBBS源下载，如果资源文件很多超过2000个的话就会强制失败。
> > > > > > 等一个修复。
> > > > > 
> > > > > 
> > > > > 那这么说这个选项就是摆设喽？怪不得我看有些人在b站上说pcl即使是换成官方源也不好使，但是官方启动器却能用
> > > > 
> > > > 
> > > > 并不是，如果其中一个下载源下载失败了，会跳转至下一个下载源，直至全部都试过（应该吧
> > > 
> > > 
> > > 要不然你猜为什么是“尽量”[doge]
> > 
> > 
> > 但是这个尽量有点太……还有就是pcl宁可用mcbbs也不用官方源意思是说mcbbs能正常下载？
> 
> 因为 mcbbs 稳定快速（除了这次），毕竟 PCL 不是专为国内使用者的吗

MCBBS已经死了,现在彻底下不了了

**Comment by LTCatt** [comment]
主楼的问题是因为该选项只影响版本列表的获取，不影响资源下载，它的描述都是 ”版本列表获取“……
关于楼下提出的问题已移步 #3383 修复。

**Comment by FeyXieXzf** [comment]
> 所以赶紧开源 PCL2，一群人写代码肯定比一个人快

对对对，赶紧开源，就几个主题色和解密有什么好混淆的，MC启动器是用来启动MC又不是用来玩解密小游戏的

**Comment by FeyXieXzf** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/52984443/db3cc24a-46fc-4dad-abf1-dc392a30d22b)
我的妈呀，你这是MC启动器吗
这防反混淆能跟原神比一比了

**Comment by rumengchuxing062** [comment]
> > 所以赶紧开源 PCL2，一群人写代码肯定比一个人快
> 
> 对对对，赶紧开源，就几个主题色和解密有什么好混淆的，MC启动器是用来启动MC又不是用来玩解密小游戏的

请问扣掉主题和解密对修改和查阅源代码有什么影响吗？

**Comment by FeyXieXzf** [comment]
有啊，要么你自己比较比较PCL的反编译/混淆结果和公开出来的代码？（我指的是扣掉的不仅仅是主题色和解谜游戏）

**Comment by FeyXieXzf** [comment]
恕我不能理解消息框和左下角提示这两函数有什么好混淆的

**Comment by Pigeon0v0** [comment]
请不要在此 Issue 下方继续回复无关内容，可以移步 Discussion 或以其他方式私聊

**Comment by wuliaodexiaoluo** [comment]
> 有啊，要么你自己比较比较PCL的反编译/混淆结果和公开出来的代码？（我指的是扣掉的不仅仅是主题色和解谜游戏）

有没有可能，反编译只是根据软件在运行过程中的操作来生成可能的代码，同一种功能可能会有好几种可能的实现代码，而反编译软件可能会优化代码逻辑，使其看起来更方便阅读
详见 [这里](https://www.zhihu.com/question/400436990)

**Comment by FeyXieXzf** [comment]
这点常识我当然知道，但请你先自己比较比较再发表意见
