### ISSUE TITLE
在 Mod 搜索中出现数据包

### ISSUE THREAD

**Issue by hejiehao** [Hex-Dragon/PCL2#3218]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/Hex-Dragon/PCL2/assets/98140773/4ccd9dfc-f29d-4d35-86a4-d59cd436f226)

### 重现步骤

1、点击下载
2、点击 Mod
3、来源选择 Modrinth，名称输入 `purpurpacks`，然后点击搜索
4、选择第一个，非 Mod Version 的为数据包

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14082426/Log1.txt)

**Comment by allMagicNB** [comment]
很明显为API的锅……？

**Comment by hejiehao** [comment]
> 很明显为API的锅……？

#2458 插件也修了呀，可是好像没修数据包

**Comment by zkitefly** [comment]
![image](https://github.com/HMCL-dev/HMCL/assets/64117916/7af4c8e6-6ed6-4a60-ada0-474d3be3dd17)

问了下，说是正常行为，
