### ISSUE TITLE
[转 QQ 群友] 被 Notron 360 订阅检测到威胁

### ISSUE THREAD

**Issue by SuoHouDaiShi** [Hex-Dragon/PCL2#3219]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

启动 PCL2 时，被 Notron 360 订阅检测到 Bad Reputation Application 的恶意请求，阻止了 PCL2 启动（已经添加到白名单）
<del>疑似是未删干净的联机模块所致？</del>

### 重现步骤

<del>这种东西还要步骤吗</del>
1.启动你的 Notron 360 订阅
2.在 Notron 360 软件中将 PCL2 主体加入信任名单
3.启动 PCL2，被拦截

### 日志与附件

![6{5K%@VA0`TT3(M}C PS${9_tmb](https://github.com/Hex-Dragon/PCL2/assets/119282947/bb10766f-ac17-4068-a600-0b27f27c922d)
![0VS1A(TE9Y5 S4K% G`~TD0_tmb](https://github.com/Hex-Dragon/PCL2/assets/119282947/c41cade0-df51-46da-985f-f9fc9a6dffec)
检测报告：
https://www.virustotal.com/gui/file/608eb10319f73d7e7ad012a47fc83da722a359b12aa73eb29092245f7540f6f4

**Comment by allMagicNB** [comment]
首先，这个不是个Bug
其次，我觉得它应该放讨论

**Comment by SuoHouDaiShi** [comment]
> 首先，这个不是个Bug 其次，我觉得它应该放讨论

懂了
