### ISSUE TITLE
PCL2无法安装从网络路径拖动的模组文件

### ISSUE THREAD

**Issue by zhang5249130** [Hex-Dragon/PCL2#3221]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![无标题](https://github.com/Hex-Dragon/PCL2/assets/96641164/928cd180-5a5e-414e-857d-e0ea6dd7cce7)
PCL2在从一个网络路径（以\\起头的文件夹）时，会自动定位到用户的桌面，然后把网络路径照抄上去（？）

### 重现步骤

从一个网络路径拖动模组进PCL2，原文件路径举例:\\example\c\.minecraft\mods

### 日志与附件

[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14091555/Log4.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14091556/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14091557/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14091558/Log3.txt)

**Comment by zkitefly** [comment]
干嘛拖网络路径（

**Comment by allMagicNB** [comment]
未能找到路径……网络驱动器断连了？

**Comment by allMagicNB** [comment]
> 干嘛拖网络路径（

你可曾听过路由器当NAS？

**Comment by zhang5249130** [comment]
没有啊，两台电脑间是直接用网线相连，没有经过路由器

**Comment by allMagicNB** [comment]
> 没有啊，两台电脑间是直接用网线相连，没有经过路由器

……好新奇的想法，使我的脑子旋转

**Comment by allMagicNB** [comment]
> 没有啊，两台电脑间是直接用网线相连，没有经过路由器

你试试能不能把文件传过去？

**Comment by zhang5249130** [comment]
ping也不丢包

**Comment by allMagicNB** [comment]
> 亲测可行

那你把模组拖到本地再拖进PCL2试试

**Comment by zhang5249130** [comment]
![无标题](https://github.com/Hex-Dragon/PCL2/assets/96641164/3f6acccc-8e42-470b-9762-2cb0d0c12058)

**Comment by zhang5249130** [comment]
本地路径拖进去可以

**Comment by allMagicNB** [comment]
> ![无标题](https://github.com/Hex-Dragon/PCL2/assets/96641164/3f6acccc-8e42-470b-9762-2cb0d0c12058)
> 

PCL2应该无法直接读取那台电脑的文件

**Comment by zhang5249130** [comment]
注意看第一张图

**Comment by zhang5249130** [comment]
第一张图的路径很奇怪

**Comment by zhang5249130** [comment]
他在网络路径前面又加了个本地路径

**Comment by zhang5249130** [comment]
这分明就是PCL的问题

**Comment by allMagicNB** [comment]
> 这分明就是PCL的问题

……就是会这样的，这是Windows的问题

**Comment by allMagicNB** [comment]
> 这分明就是PCL的问题

你去HMCL试试啊

**Comment by zhang5249130** [comment]
![无标题](https://github.com/Hex-Dragon/PCL2/assets/96641164/1b9a3d80-b39c-48fe-b472-39bd21327ac7)
没话说了吧，HMCL都行

**Comment by burningtnt** [comment]
> 没话说了吧，HMCL都行

HMCL 是 JavaFX 处理的，根本不需要做考虑

**Comment by allMagicNB** [comment]
> ![无标题](https://github.com/Hex-Dragon/PCL2/assets/96641164/1b9a3d80-b39c-48fe-b472-39bd21327ac7)
> 没话说了吧，HMCL都行

那你去试BakaXL啊

**Comment by zhang5249130** [comment]
也可以（）

**Comment by SALTWOOD** [comment]
建议改为：**从网络路径拖动模组文件时，PCL2无法安装**

**Comment by allMagicNB** [comment]
> 建议改为：**从网络路径拖动模组文件时，PCL2无法安装**

确实，这个标题容易引起一些误会（

**Comment by LTCatt** [comment]
适用面太小了，并且我自己也没有复现环境，暂时不考虑，抱歉（

**Comment by allMagicNB** [comment]
> 适用面太小了，并且我自己也没有复现环境，暂时不考虑，抱歉（

~~路由器搭NAS~~

**Comment by SALTWOOD** [comment]
> 适用面太小了，并且我自己也没有复现环境，暂时不考虑，抱歉（

\\127.0.0.1\即可复现

**Comment by zhang5249130** [comment]
> > 适用面太小了，并且我自己也没有复现环境，暂时不考虑，抱歉（
> 
> \\127.0.0.1\即可复现

\\localhost也可以

**Comment by zhang5249130** [comment]
https://github.com/Hex-Dragon/PCL2/assets/96641164/2886ff56-c9f6-4101-afe4-3c2b1da1bbfa

**Comment by LTCatt** [comment]
这个适用面确实太小了（

**Comment by zhang5249130** [comment]
实际上，我还是希望他被修复的:(

**Comment by zhang5249130** [comment]
(经试验，不论连接协议，http 和ftp，只要是在文件资源管理器的某个网络路径拖拽进PCL加载的模组均会报错)

**Comment by zhang5249130** [comment]
https://github.com/Hex-Dragon/PCL2/assets/96641164/f8479cd3-7037-487a-9ab6-3dc06045c3c1
