### ISSUE TITLE
加载 Mod 列表 UI 失败：指定的 Visual 已经是另一个 Visual 的子级或者已经是 CompositionTarget 的根。

### ISSUE THREAD

**Issue by chengfeng30121** [Hex-Dragon/PCL2#3226]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我看过Issue了，并未涉及两个相同mod一个启用一个禁用的情况，我怀疑是meteor client.jar搞得鬼，明明它在mods文件夹里，无论是启用还是禁用，都不显示。把它移除就好了。但是如果不把它移除，就会报错。
版本：1.19.2 Fabric
登录：正版验证
mod数量（启用+未启用）：16个
版本文件夹：[1.19.2 meteor.zip](https://github.com/chengfeng30121/tuchuang/raw/main/zip/3.zip?download=)
PCL文件夹：[PCL.zip](https://github.com/chengfeng30121/tuchuang/raw/main/zip/2.zip?download=)
日志：（见PCL文件夹下的Log1.txt）
报错详情：
[11:09:23.979] 加载 Mod 列表 UI 失败：指定的 Visual 已经是另一个 Visual 的子级或者已经是 CompositionTarget 的根。
   在 System.Windows.Media.VisualCollection.Add(Visual visual)
   在 System.Windows.Controls.UIElementCollection.AddInternal(UIElement element)
   在 PCL.PageVersionMod.RefreshResult(List`1 Mods)
   在 PCL.PageVersionMod.LoadUIFromLoaderOutput()
错误类型：System.ArgumentException
[11:09:24.010] [Control] 普通弹窗：出现错误
加载 Mod 列表 UI 失败：指定的 Visual 已经是另一个 Visual 的子级或者已经是 CompositionTarget 的根。
   在 PCL.PageVersionMod.RefreshResult(List`1 Mods)
   在 PCL.PageVersionMod.LoadUIFromLoaderOutput()
错误类型：System.ArgumentException

是否反馈此问题？如果不反馈，这个问题可能永远无法得到解决！

### 重现步骤

1、下载版本文件夹，解压，添加至PCL2
2、点击版本设置，进入mod管理，复现成功

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14106868/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14106871/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14106873/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14106874/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14106875/Log5.txt)

**Comment by allMagicNB** [comment]
#3092

**Comment by allMagicNB** [comment]
但是是同个报错啊

**Comment by chengfeng30121** [comment]
不是的，你可以下载并加载，你可以看到，没有mod是重复的

**Comment by chengfeng30121** [comment]
这个是特定mod引起的锅，不是重复mod导致的BUG

**Comment by allMagicNB** [comment]
emm，确实，也有些重复Mod不会报错……

**Comment by chengfeng30121** [comment]
？？？

**Comment by chengfeng30121** [comment]
这不是重复mod啊！

**Comment by chengfeng30121** [comment]
没有重复的

**Comment by allMagicNB** [comment]
不是，我是说，这个Bug的复现方式还不太稳定

**Comment by chengfeng30121** [comment]
哦，所以有解决方法吗？

**Comment by allMagicNB** [comment]
> 哦，所以有解决方法吗？

我先看看能不能复现……

**Comment by chengfeng30121** [comment]
能复现吗？

**Comment by allMagicNB** [comment]
能显示啊
![image](https://github.com/Hex-Dragon/PCL2/assets/116283787/e7c7eca5-3afe-4ee0-9613-5ad4cadd8562)

**Comment by chengfeng30121** [comment]
我的PCL2看不到。
那你是哪个mod看不到？

**Comment by allMagicNB** [comment]
再说了
![image](https://github.com/Hex-Dragon/PCL2/assets/116283787/06ab3fa2-c9e2-4624-84eb-996655bdac8a)
还说没有重复Mod

**Comment by chengfeng30121** [comment]
？

**Comment by chengfeng30121** [comment]
我有一个版本，也是这样，有重复版本，投影重复，NBTEditor重复，就是没报错

**Comment by allMagicNB** [comment]
你上传的压缩包就是有重复Mod

**Comment by chengfeng30121** [comment]
哦，删掉就没事了

**Comment by chengfeng30121** [comment]
问题解决，谢谢

**Comment by allMagicNB** [comment]
……不要Close as complete
谁来搞一下换成重复（与#3092 重复）
