### ISSUE TITLE
无法显示curseforge mod和optifabric下载列表，浏览器可以打开官网，挂梯子没用

### ISSUE THREAD

**Issue by WangLing33233** [Hex-Dragon/PCL2#3227]
### 检查项

- [ ] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

无法显示curseforge mod和optifabric下载列表，浏览器可以打开官网，挂梯子没用
![屏幕截图 2024-01-31 133018](https://github.com/Hex-Dragon/PCL2/assets/158018574/b7dac8ff-a011-46a5-a03a-bbb27a8524bc)![屏幕截图 2024-01-31 133033](https://github.com/Hex-Dragon/PCL2/assets/158018574/ff35946c-de94-4c25-8121-ec91b6e0bd8e)
![屏幕截图 2024-01-31 133104](https://github.com/Hex-Dragon/PCL2/assets/158018574/510be974-5c1b-4dd1-88d6-4e1bd6f641ab)

### 重现步骤

就是打开mod下载界面
![屏幕截图 2024-01-31 133033](https://github.com/Hex-Dragon/PCL2/assets/158018574/aecdc8ca-bc9f-4821-89e7-8c1a252b52f0)
![屏幕截图 2024-01-31 133104](https://github.com/Hex-Dragon/PCL2/assets/158018574/80a9f26e-1d69-4627-a1df-53b5386ded5f)

### 日志与附件

![屏幕截图 2024-01-31 133033](https://github.com/Hex-Dragon/PCL2/assets/158018574/07c0287c-b1ee-43b2-b9a3-0349b9f0bd6b)
![屏幕截图 2024-01-31 133104](https://github.com/Hex-Dragon/PCL2/assets/158018574/97852b34-5144-4618-99e4-15296c613a5b)
![屏幕截图 2024-01-31 133018](https://github.com/Hex-Dragon/PCL2/assets/158018574/bd15c632-61eb-4b7f-9906-6d4a9faa9879)

**Comment by zkitefly** [comment]
请上传日志

**Comment by allMagicNB** [comment]
《和网络环境无关》

**Comment by allMagicNB** [comment]
首先，Forge用户页面和Forge API不是一个东西
其次，**未复现成功**
![image](https://github.com/Hex-Dragon/PCL2/assets/116283787/b11f6a83-b2fd-493e-9e36-4a981cf557df)

**Comment by allMagicNB** [comment]
还有，挂梯子≠加速器

**Comment by burningtnt** [comment]
超时时间问题，浏览器默认超时是 60000ms，远高于 PCL

**Comment by allMagicNB** [comment]
> 超时时间问题，浏览器默认超时是 60000ms，远高于 PCL

翻译：一分钟（

**Comment by SALTWOOD** [comment]
超时时间不一样？~~梯子得开全局~~ **未复现成功**

**Comment by SALTWOOD** [comment]
网络波动，以前能用就说明PCL没有问题，不算bug，关了吧

**Comment by allMagicNB** [comment]
> 超时时间不一样？~~梯子得开全局~~ **未复现成功**

你看一下他下面的任务栏，UU**加速器**

**Comment by SALTWOOD** [comment]
> > 超时时间不一样？~梯子得开全局~ **未复现成功**
> 
> 你看一下他下面的任务栏，UU**加速器**

行吧……我更偏向网络波动，不是PCL的问题（

**Comment by rumengchuxing062** [comment]
尝试完毕，未能复现
以及能打开[CurseForge](https://www.curseforge.com)不等于能够打开[CurseForge API](https://api.curseforge.com)

**Comment by allMagicNB** [comment]
个人网络原因，关了
