### ISSUE TITLE
PCL最新版无法分析MC Fabric的报错

### ISSUE THREAD

**Issue by xhahello** [Hex-Dragon/PCL2#3228]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在老版本中，PCL可以在关闭fabric报错窗口后弹出窗口给出fabric的解决方案，在一次更新后（记不清是哪个版本了）这个功能没了，弹出的窗口中没有解决方案

### 重现步骤

用任何方式把fabric整报错

### 日志与附件

这个bug应该不用上传Log

**Comment by zkitefly** [comment]
上传日志

**Comment by zkitefly** [comment]
难道是 Fabric 崩溃弹窗支持中文后PCL不支持抓取？

我觉得这没必要（

你都看得懂了

**Comment by WForst-Breeze** [comment]
> 难道是 Fabric 崩溃弹窗支持中文后PCL不支持抓取？

先前测试过，并不是这样的，即使是旧版本 fabric 也同样不能分析出来🤔

**Comment by xhahello** [comment]
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14110648/Log1.txt)
我用optifabric的良好兼容性触发了一下，但是我好像记得以前版本不兼容他也会出现fabric白窗口，现在直接是PCL说“检测到 Minecraft 出现错误，错误分析已开始”

**Comment by xhahello** [comment]
我用optifabric的良好兼容性触发了一下，但是我好像记得以前版本不兼容他也会出现fabric白窗口，现在直接是PCL说“检测到 Minecraft 出现错误，错误分析已开始”

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14110749/Log1.txt)

**Comment by zkitefly** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/64117916/7add5866-80a1-4764-bb4f-f0436fe8432c)

我猜的果然没错

但，我觉得没必要修吧，都中文了你还看不懂（

**Comment by rumengchuxing062** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/110439412/4b4c51be-5152-4d66-a870-34c1647bcfd1)
但是最后一次PCL没有把错误信息打印出来。。。

**Comment by zkitefly** [comment]
> ![image](https://private-user-images.githubusercontent.com/110439412/301137650-4b4c51be-5152-4d66-a870-34c1647bcfd1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2OTk1NTgsIm5iZiI6MTcwNjY5OTI1OCwicGF0aCI6Ii8xMTA0Mzk0MTIvMzAxMTM3NjUwLTRiNGM1MWJlLTUxNTItNGQ2Ni1hODcwLTM0YzE2NDdiY2ZkMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMVQxMTA3MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZjMyOTYyYTY2Mzc3YjlmNGU1OWI4OGJjNzNkYTk0OGUzZmYyNTY2MDZiMjZjZWMxZjE5Mzg4OGRiMWU4OTlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZUurzVy06eaiLJIFDipX6iX1hEK7Dn-Cj6G-0Z-3d4s) 但是最后一次PCL没有把错误信息打印出来。。。

有必要吗（

**Comment by xhahello** [comment]
close了吧

**Comment by zkitefly** [comment]
我去加了，看看龙猫这么说

**Comment by xhahello** [comment]
issues A826-507F-256F-800B
谢谢（梦寐以求的color

**Comment by xhahello** [comment]
隐藏主题（睡了

**Comment by WorldHim** [comment]
> issues A826-507F-256F-800B
> 谢谢（梦寐以求的color

issue 尚未解决，请等待标签改为 `完成`。

**Comment by allMagicNB** [comment]
> issues A826-507F-256F-800B
> 谢谢（梦寐以求的color

回复 Issue 要求解锁主题是`回复 Issue` 要求解锁主题

**Comment by rumengchuxing062** [comment]
> issues A826-507F-256F-800B
> 谢谢（梦寐以求的color

请等待 `member` 将 label:处理中 改成 label:完成 时回复issue要求解锁

**Comment by SALTWOOD** [comment]
在 JVM 参数后面加上`-Duser.language=en -Duser.region=US`可以改成英文，但是似乎还是没办法分析错误……

**Comment by LTCatt** [comment]
崩溃分析优化不算 bug，抱歉（

**Comment by rumengchuxing062** [comment]
> 崩溃分析优化不算 bug，抱歉（

貌似你也没写优化不算
你只是写了向存储库提交issue或者pull request，待龙猫标记为已完成后回复issue要求解锁

**Comment by WForst-Breeze** [comment]
> 貌似你也没写优化不算 你只是写了向存储库提交issue或者pull request，待龙猫标记为已完成后回复issue要求解锁

![image](https://github.com/Hex-Dragon/PCL2/assets/110760354/502af440-6ee9-4eaa-adcf-976c893dbb15)

**Comment by rumengchuxing062** [comment]
> > 貌似你也没写优化不算 你只是写了向存储库提交issue或者pull request，待龙猫标记为已完成后回复issue要求解锁
> 
> ![image](https://private-user-images.githubusercontent.com/110760354/313384453-502af440-6ee9-4eaa-adcf-976c893dbb15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5NDUzODksIm5iZiI6MTcxMDk0NTA4OSwicGF0aCI6Ii8xMTA3NjAzNTQvMzEzMzg0NDUzLTUwMmFmNDQwLTZlZTktNGVhYS1hZGNmLTk3NmM4OTNkYmIxNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMFQxNDMxMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MWI5NGYzYWNhMmQ0YjIyOGE1ZDVkNzMwZTY5MGY2ODA3MWI0ZDViN2E3Y2FlNGIzNzVkMTNhNTQyZDkxZjhmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.H7_xe_bK_6xxKAUfRR-6Yx68x9itAD8FUjLHnXxMozM)

6
