### ISSUE TITLE
Authlib Injector 第三方登录文本乱码

### ISSUE THREAD

**Issue by Eric20130702** [Hex-Dragon/PCL2#3230]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

问题不大，但是那个验证怎么变火星文了？？？

### 重现步骤

<img width="224" alt="屏幕截图 2024-01-31 154715" src="https://github.com/Hex-Dragon/PCL2/assets/125123650/c01ec58f-e9a9-418d-a8bc-067a9b691c60">
第三方登录LittleSkin的时候就出了

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14108782/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14108783/Log4.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14108784/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14108785/Log2.txt)

**Comment by allMagicNB** [comment]
截屏看看？估计编码问题

**Comment by rumengchuxing062** [comment]
[18:49:05.134] [Start] 程序版本：Beta 1.4.8（180）
这TM是认真的吗？？？？

**Comment by allMagicNB** [comment]
服务器公告都提示更新了，Author不是故意不更新吗？
```
[18:49:08.112] [Server] 显示公告 999：当前程序的大多数功能已无法正常使用，请尽快更新到最新版！
新版中大多数 Bug 都已修复，并且还有一大堆新功能！
并且新版能自动更新了，所以这是最后一次手动更新了！最！后！一！次！
你只需要下载最新版，然后替换掉 PCL 这一个文件就行！
[18:49:08.170] [Control] 普通弹窗：上古版本 PCL 已被弃用
当前程序的大多数功能已无法正常使用，请尽快更新到最新版！
新版中大多数 Bug 都已修复，并且还有一大堆新功能！
并且新版能自动更新了，所以这是最后一次手动更新了！最！后！一！次！
你只需要下载最新版，然后替换掉 PCL 这一个文件就行！
```

**Comment by WForst-Breeze** [comment]
`
[18:49:05.134] [Start] 程序版本：Beta 1.4.8（180）
`
请将 PCL 更新至最新版本
