### ISSUE TITLE
日志分析优化

### ISSUE THREAD

**Issue by zhang5249130** [Hex-Dragon/PCL2#3232]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

当玩家拖拽一个完全正常的日志时，PCL应显示别的信息，而不是纯粹的显示“无法分析错误原因”
做一个这样的判断应该很简单吧，只需要检查最后一部分是否有“shutting down”字样就行了！

### 原因

没有为啥，觉得这样很别扭

**Comment by allMagicNB** [comment]
加个判定，然后呢？然后怎么说呢？继续报分析错误？

**Comment by zhang5249130** [comment]
这得看龙猫咋写了...

**Comment by zhang5249130** [comment]
似乎也不难啊，不是吗？

**Comment by allMagicNB** [comment]
有必要吗？

**Comment by zhang5249130** [comment]
...

**Comment by zhang5249130** [comment]
(也只是一个优化)

**Comment by allMagicNB** [comment]
没必要或者没什么用的优化就别提了，你看看现在处理中的Bug有多少……

**Comment by LTCatt** [comment]
没有必要……
