### ISSUE TITLE
对于打开启动器的调试模式显示条的优化

### ISSUE THREAD

**Issue by GOhaochen** [Hex-Dragon/PCL2#3233]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

护身符：
![image](https://github.com/Hex-Dragon/PCL2/assets/98160605/cbeea527-6df6-4dcd-ac61-7f9fd1d7e6b8)
自证没有类似的新功能提案
原版
![屏幕截图 2024-02-01 155514](https://github.com/Hex-Dragon/PCL2/assets/98160605/daa9eede-aa83-4799-a801-0d6d8c0b3e06)

目标：将此条改为弹窗，并支持不再提示、前往关闭两个功能
![屏幕截图 2024-02-01 160122](https://github.com/Hex-Dragon/PCL2/assets/98160605/38843b8d-cd06-40c8-909c-71598ca1735e)

### 原因

这项优化让可以让调试模式的主页美观一些。

**Comment by burningtnt** [comment]
没啥意义，这只会让想开调试的人多一个步骤

**Comment by LTCatt** [comment]
开启调试模式后的这个提示已经足够让用户知晓，没有必要添加一个额外步骤

**Comment by GOhaochen** [comment]
> 开启调试模式后的这个提示已经足够让用户知晓，没有必要添加一个额外步骤

但是每次启动都会弹出次提示，我设计的弹窗可以让它不再提示
