### ISSUE TITLE
将部分MC版本和JAVA整合进PCL中

### ISSUE THREAD

**Issue by GOhaochen** [Hex-Dragon/PCL2#3234]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

建议将MC的部分版本，如1.12.2，1.18.1，1.20.1以及最新MC正式版及Java整合入PCL中
或者另起一个单独的版本
自证无重复：
![image](https://github.com/Hex-Dragon/PCL2/assets/98160605/2b4072a7-4f22-4a06-aa5d-7849be3e4b36)

### 原因

因为PCL的下载是从服务器及镜像站抓取，但难免有服务器抽风的时候，所以建议将他们整合进启动器，可以保证游戏的正常下载和启动

**Comment by WForst-Breeze** [comment]
整合最新版又怎么做到呢？MC 的更新频率和 PCL 的并不吻合，感觉这样启动器会无缘无故增加很大没有必要的体积🧐

**Comment by LTCatt** [comment]
暂不考虑，抱歉（
