### ISSUE TITLE
允许用户自定义启动器四个按钮的图标

### ISSUE THREAD

**Issue by GOhaochen** [Hex-Dragon/PCL2#3235]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

允许用户在设置-个性化-标题栏-按钮分别上传ico图标，
例如：
![屏幕截图 2024-02-01 163521](https://github.com/Hex-Dragon/PCL2/assets/98160605/373a9054-835b-4377-9f31-3b31c093ef40)

自证无重复：
![image](https://github.com/Hex-Dragon/PCL2/assets/98160605/3c2836f9-eec0-4096-b628-e0c24e686380)

### 原因

（示例）
我需要这个功能来xxxx。很多人都有xxxx的需求，但如果没有这个功能，就不能xxxx了。

**Comment by LTCatt** [comment]
暂不考虑，抱歉……

**Comment by GOhaochen** [comment]
...
