### ISSUE TITLE
natives 文件夹路径包含特殊字符导致无法启动

### ISSUE THREAD

**Issue by xiaohei20** [Hex-Dragon/PCL2#3236]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃基本不是 PCL 的原因，请 **不要** 提交反馈。你可以在论坛或社区找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用 HMCL 启动，HMCL 没有出现问题。** 如果 HMCL 也无法启动就不是 PCL 导致的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

这个问题是由于在游戏运行时尝试加载一个缺失的类。在这个例子中，缺失的类是 com.mojang.blaze3d.systems.RenderSystem。
_自己的解决方式但没有成功：项目中包含了最新版本的 com.mojang.blaze3d 库_
已使用版本补全
已重新安装Java

### PCL 错误报告、日志与附件

[错误报告-2024-2-1_16.50.03.zip](https://github.com/Hex-Dragon/PCL2/files/14122522/-2024-2-1_16.50.03.zip)

### HMCL 启动脚本

由于时间紧迫所以咱是无法上传

**Comment by burningtnt** [comment]
这是由于 LWJGL 初始化失败导致的

**Comment by burningtnt** [comment]
在 控制面板 -- 时钟和区域 -- 区域 -- 管理 -- 更改系统区域设置 里面上面选「中文（简体，中国）」，并且把下面那个勾去掉

**Comment by rumengchuxing062** [comment]
> 这是由于 LWJGL 初始化失败导致的
> 
> 在 控制面板 -- 时钟和区域 -- 区域 -- 管理 -- 更改系统区域设置 里面上面选「中文（简体，中国）」，并且把下面那个勾去掉 ![image](https://private-user-images.githubusercontent.com/88144530/301443817-34d79981-43a5-44b4-985f-4369f6319d23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NDA3OTMsIm5iZiI6MTcwNjg0MDQ5MywicGF0aCI6Ii84ODE0NDUzMC8zMDE0NDM4MTctMzRkNzk5ODEtNDNhNS00NGI0LTk4NWYtNDM2OWY2MzE5ZDIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDAyMjEzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2ZjIzNTAyNzQyODA1ODMxNmU0NmIxOGYyZDcxMzExODBjN2U1NWYwZTMzNTVlODcxZjg2ZTg4YTk1NjJjMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GjLA009YApsuGBQy-r-E66l5XHWlWMWs_E-YLk3OW-8)

测试结果：启用UTF-8支持最多只能是PCL在检查Java版本时失败，不会影响启动（CMD脚本除外）
测试字符：minecraft 我的世界 、 ？？？ ：��Ϸ���˳���
包括特殊字符在内的多个字符都没有触发错误

报错包含了 File/Folders does not exist，还有大量的Failed retrieving info for group graphics和初始化失败，找不到类或者无法创建临时文件的问题，可以尝试下删掉临时文件（cmd 键入 rd /s /q %TEMP%）
另外检查下驱动版本，如果版本太旧可以更新一下
也可以试试 -XX:-UseCompressedOops

**Comment by burningtnt** [comment]
> > 这是由于 LWJGL 初始化失败导致的
> > 在 控制面板 -- 时钟和区域 -- 区域 -- 管理 -- 更改系统区域设置 里面上面选「中文（简体，中国）」，并且把下面那个勾去掉
> 
> 测试结果：启用UTF-8支持最多只能是PCL在检查Java版本时失败，不会影响启动（CMD脚本除外） 测试字符：minecraft 我的世界 、 ？？？ ：��Ϸ���˳��� 包括特殊字符在内的多个字符都没有触发错误
> 
> 报错包含了 File/Folders does not exist，还有大量的Failed retrieving info for group graphics和初始化失败，找不到类或者无法创建临时文件的问题，可以尝试下删掉临时文件（cmd 键入 rd /s /q %TEMP%） 另外检查下驱动版本，如果版本太旧可以更新一下 也可以试试 -XX:-UseCompressedOops

请仔细阅读日志，日志中有
`java.io.IOException: JNA temporary directory 'F:\mc\?\.minecraft\versions\1.22 24w05a\1.22 24w05a-natives' does not exist`
很显然，是 Java 没能正确处理中文路径编码导致的问题

**Comment by rumengchuxing062** [comment]
> > > 这是由于 LWJGL 初始化失败导致的
> > > 在 控制面板 -- 时钟和区域 -- 区域 -- 管理 -- 更改系统区域设置 里面上面选「中文（简体，中国）」，并且把下面那个勾去掉
> > 
> > 
> > 测试结果：启用UTF-8支持最多只能是PCL在检查Java版本时失败，不会影响启动（CMD脚本除外） 测试字符：minecraft 我的世界 、 ？？？ ：��Ϸ���˳��� 包括特殊字符在内的多个字符都没有触发错误
> > 报错包含了 File/Folders does not exist，还有大量的Failed retrieving info for group graphics和初始化失败，找不到类或者无法创建临时文件的问题，可以尝试下删掉临时文件（cmd 键入 rd /s /q %TEMP%） 另外检查下驱动版本，如果版本太旧可以更新一下 也可以试试 -XX:-UseCompressedOops
> 
> 请仔细阅读日志，日志中有 `java.io.IOException: JNA temporary directory 'F:\mc\?\.minecraft\versions\1.22 24w05a\1.22 24w05a-natives' does not exist` 很显然，是 Java 没能正确处理中文路径编码导致的问题

设置过中文路径，但是在默认ASCII解码下没有任何问题

**Comment by burningtnt** [comment]
> 设置过中文路径，但是在默认ASCII解码下没有任何问题

这个问题和 JVM、系统都有关，你的电脑上不出错 != 别人电脑上不出错

**Comment by allMagicNB** [comment]
> 这个问题和 JVM、系统都有关，你的电脑上不出错 != 别人电脑上不出错

~~你这个 != 让我想起了易语言的不等号怎么输入~~

**Comment by rumengchuxing062** [comment]
> > 设置过中文路径，但是在默认ASCII解码下没有任何问题
> 
> 这个问题和 JVM、系统都有关，你的电脑上不出错 != 别人电脑上不出错

UTF-8 默认是没有勾选的，正经人也不会去调这个吧
~~（貌似只要和Beta有关的Microsoft都不会默认勾选）~~

**Comment by Tactsohg** [comment]
> 请仔细阅读日志，日志中有 `java.io.IOException: JNA temporary directory 'F:\mc\?\.minecraft\versions\1.22 24w05a\1.22 24w05a-natives' does not exist` 很显然，是 Java 没能正确处理中文路径编码导致的问题

![image](https://github.com/Hex-Dragon/PCL2/assets/117257181/3f318758-34d7-4d7f-bfcf-3140c35060d6)
![image](https://github.com/Hex-Dragon/PCL2/assets/117257181/b219893a-f84a-4e76-837b-3a67c7199a68)
这不是因为路径本身有异常字符么……看不出来是什么编码= =

**Comment by rumengchuxing062** [comment]
怕不是加密目录

**Comment by rumengchuxing062** [comment]
> ![image](https://private-user-images.githubusercontent.com/117257181/301735151-3f318758-34d7-4d7f-bfcf-3140c35060d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NTUxOTIsIm5iZiI6MTcwNjg1NDg5MiwicGF0aCI6Ii8xMTcyNTcxODEvMzAxNzM1MTUxLTNmMzE4NzU4LTM0ZDctNGQ3Zi1iZmNmLTMxNDBjMzUwNjBkNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMlQwNjIxMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lM2Y1MzMxNjQ4ZWY0MmM4YTgwMjBlMjJiZDcwODIzMWE2YzlmMGJhOTJmNWJhN2I5ZjE4YWIzNWFhOGI0Yzc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AHFw_T03Qpo22W7sf15zKNRjKOgymSrrAts4gPlmfKU) ![image](https://private-user-images.githubusercontent.com/117257181/301735162-b219893a-f84a-4e76-837b-3a67c7199a68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NTUxOTIsIm5iZiI6MTcwNjg1NDg5MiwicGF0aCI6Ii8xMTcyNTcxODEvMzAxNzM1MTYyLWIyMTk4OTNhLWY4NGEtNGU3Ni04MzdiLTNhNjdjNzE5OWE2OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMlQwNjIxMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZGZiZDg3NWRjNTg0MDM1MTJlZDBjMTQyMmUxNDgyMTMyNWI2ZWJhYmFkZWIwMWFkNzFjMTZmODkzMGI4ZTA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rB4dLTiZJpKWfWYb1_I11tGRoxuSR_SoXRgDhpGxMQM) 这不是因为路径本身有异常字符么……~看不出来是什么编码= =~是零宽连字（zero width joiner）

猜一手 ASCII （GBK）

**Comment by Tactsohg** [comment]
哦这个是因为jlw不会处理-D里面的特殊字符导致jna找不到路径……但是java.library.path也是-D的啊？natives是放在游戏目录里的，如果游戏目录有特殊字符（比如英文系统里的中文目录名还有这个issue的zwj字符）就不可能会打得开，这个jlw根本就处理了个寂寞嘛……

**Comment by hejiehao** [comment]
> > 这个问题和 JVM、系统都有关，你的电脑上不出错 != 别人电脑上不出错
> 
> ~你这个 != 让我想起了易语言的不等号怎么输入~

应该没有语言是这样输入的吧
`≠`

**Comment by allMagicNB** [comment]
> > > 这个问题和 JVM、系统都有关，你的电脑上不出错 != 别人电脑上不出错
> > 
> > ~你这个 != 让我想起了易语言的不等号怎么输入~
> 
> 应该没有语言是这样输入的吧
> `≠`

有的，易语言就是，碰到`！=`自动替换成`≠`

**Comment by hejiehao** [comment]
> > > > 这个问题和 JVM、系统都有关，你的电脑上不出错 != 别人电脑上不出错
> > > 
> > > 
> > > ~你这个 != 让我想起了易语言的不等号怎么输入~
> > 
> > 
> > 应该没有语言是这样输入的吧
> > `≠`
> 
> 有的，易语言就是，碰到`！=`自动替换成`≠`

你要直接输入 `≠` 会发生什么

**Comment by hejiehao** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/98140773/267544e1-f289-4ea9-a9f3-e869edf40252)
我们这个 Python 它不行了
>有的，易语言就是，碰到！=自动替换成≠

你这个是中文冒号在 Python 也会爆炸

**Comment by allMagicNB** [comment]
> ![image](https://github.com/Hex-Dragon/PCL2/assets/98140773/267544e1-f289-4ea9-a9f3-e869edf40252)
> 我们这个 Python 它不行了
> >有的，易语言就是，碰到！=自动替换成≠
> 
> 你这个是中文叹号在 Python 也会爆炸

但是易语言是半角和全角混搭也可以识别到然后替换

**Comment by hejiehao** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/98140773/fb02f7f8-d4f9-4f0c-b1be-38778819d2bf)
垃圾 Java 毫无体验

**Comment by rumengchuxing062** [comment]
太久没回复了，有没有 Collaborator 过来关一下

**Comment by allMagicNB** [comment]
> 太久没回复了，有没有 Collaborator 过来关一下

才两天你急啥
急急复急急

**Comment by iPodtouch6557** [comment]
超时关闭吧

**Comment by Tactsohg** [comment]
啊？这么大个bug不修的吗？挪一下启动器解压natives的位置就可以了来着。

**Comment by allMagicNB** [comment]
> 啊？这么大个bug不修的吗？挪一下启动器解压natives的位置就可以了来着。

首先你得证明HMCL没有出现问题

**Comment by iPodtouch6557** [comment]
问题在于author不回复

**Comment by Tactsohg** [comment]
> 首先你得证明HMCL没有出现问题

啊？HMCL也出现相似的问题就可以不修了吗，我测试了下HMCL和BakaXL在有特殊字符的路径下打开确实也会出问题，直接找不到主类了，PCL2还是因为用了jlw才能找到主类进入游戏的，但是因为-D路径的特殊字符不会被jlw处理所以还是一样会报错打不开（题主的情况）
所以真的不修吗？？？

**Comment by Tactsohg** [comment]
> 问题在于author不回复

不知道你们在等author回复啥= =我以为把问题原因帮你们找出来你们就会看的欸

**Comment by WForst-Breeze** [comment]
确实我个人也没看懂在等待回复啥，挂个待处理先

**Comment by Pigeon0v0** [comment]
> 我测试了下HMCL和BakaXL在有特殊字符的路径下打开确实也会出问题，直接找不到主类了，PCL2还是因为用了jlw才能找到主类进入游戏的，但是因为-D路径的特殊字符不会被jlw处理所以还是一样会报错打不开
> 

这可以算是刻意触发的 BUG 了

**Comment by Tactsohg** [comment]
> 这可以算是刻意触发的 BUG 了

英文系统下使用中文路径也会触发这个bug哦，说到底pcl2引入jlw不就是为了避免特殊字符路径引发问题嘛，解决一半算什么= =

**Comment by WForst-Breeze** [comment]
@LTCatt 这里有个待处理

**Comment by LTCatt** [comment]
基于报错 `JNA temporary directory 'F:\mc\?\.minecraft\versions\1.22 24w05a\1.22 24w05a-natives' does not exist` ，这应当是第三方组件无法正常处理 UTF-8 下中文编码导致的，请向该组件提交反馈，我修不了（
natives 解压的文件夹是约定俗成的规范，不是想换就换的。

**Comment by Tactsohg** [comment]
> 基于报错 `JNA temporary directory 'F:\mc\?\.minecraft\versions\1.22 24w05a\1.22 24w05a-natives' does not exist` ，这应当是第三方组件无法正常处理 UTF-8 下中文编码导致的，请向该组件提交反馈，我修不了（ natives 解压的文件夹是约定俗成的规范，不是想换就换的。

不修就不修吧……但是并不是这个问题啊喂，第三方组件才不背锅= =

首先路径中的问号是零宽连字不是中文，然后这个路径是-Djna.tmpdir传进去的，java里获取到的就是解析错误的路径所以当然会报错。
本质上还是java的锅，它没法正常解析JVM参数中的特殊字符（但是Program参数中的就可以正常解析，真神奇= =），这部分本来是交由jlw去处理了嘛但是jlw只会处理-cp不会处理-D（而且-Djava.library.path一开始就设置好了根本轮不到jlw处理），所以才导致了这个报错（以及再次吐槽一下在mc这种一定会有-Djava.library.path并且natives跟cp放同一目录的情况下jlw真就用了跟没用一样= =）

至于**natives解压的文件夹是约定俗成的规范**，倒是很好奇哪来的这个规范，至少官启的解压文件夹是在%APPDATA%\\.minecraft\\bin下面呢，跟规范也不一样嘛= =

**Comment by LTCatt** [comment]
又看了看，反馈者用的是 Snapshot 2.4.8（280），已经落后了 32 个版本号了，在这期间 jlw 是更新过的，我不确定更新的过程中有没有修复这个问题。
可以用新版本复现吗？

**Comment by allMagicNB** [comment]
炸了炸了，我用了Emoji当目录（
[错误报告-2024-2-20_17.39.17.zip](https://github.com/Hex-Dragon/PCL2/files/14342433/-2024-2-20_17.39.17.zip)

**Comment by allMagicNB** [comment]
@LTCatt

**Comment by LTCatt** [comment]
010 看看 java launch wrapper 能处理这个么？

**Comment by allMagicNB** [comment]
> 010 看看 java launch wrapper 能处理这个么？

刚才试了下用原Author中间的符号，推测出应该是想隐藏文件夹然后插入的Unicode控制字符
![image](https://github.com/Hex-Dragon/PCL2/assets/116283787/10b89ea0-9576-4cdd-a633-c1b2afef8fd5)
@LTCatt

**Comment by allMagicNB** [comment]
日志：[错误报告-2024-2-20_18.32.58.zip](https://github.com/Hex-Dragon/PCL2/files/14343109/-2024-2-20_18.32.58.zip)

**Comment by allMagicNB** [comment]
盲猜Author想让文件夹从物理上隐藏，将文件夹名称改为不可见的字符（即Unicode控制字符），将文件夹图标改为透明图标
然后在更改文件夹名称的时候随便选控制字符时正好选到了ZWJ（Zero Width Joiner，零宽连字）控制字符，最后导致Java无法识别

**Comment by 00ll00** [comment]
wrapper不太能救这个。Java 底层加载库的函数使用的字符串处理函数有问题，即使把参数里的中文字符串处理正确了在加载库文件的时候也会炸。

经测试把native文件夹搬到全英文路径可以正常启动，不知道有没有其他影响。

**Comment by kong-que-dnf123** [comment]
> > 010 看看 java launch wrapper 能处理这个么？
> 
> 刚才试了下用Author提供的错误报告里PCL2日志中的符号，推测出应该是想隐藏文件夹然后插入的Unicode控制字符 
这样可以插入Unicode控制字符 @LTCatt

~你让我想起我微机电脑大半年打不开游戏就是因为我在‘PCL和游戏’的外包文件夹插Uni隐藏字符和透明图标试图隐藏文件夹~
