### ISSUE TITLE
第一次点击更多->反馈时，启动器弹出的弹窗中添加检查项并添加三秒倒计时

### ISSUE THREAD

**Issue by allMagicNB** [Hex-Dragon/PCL2#3240]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

经实际验证，大多数提交反馈 Issue 的 Author 都不会依据检查项来检查，而是无脑打勾，导致了很多重复 Issue
可以考虑在第一次点击这个按钮时，先弹出一个只有三秒之后才能关闭的提示，内容大概像“提交反馈前，请……”这样
然后点击关闭之后再到常规点击执行的函数

### 原因

加入一个弹窗可以提醒反馈者进行检查，三秒让反馈者仔细阅读检查项，只在第一次点击按钮时弹窗不会让反馈者后续反馈觉得麻烦
虽然：
“没救，侠客咋样都是侠客” ——龙腾猫跃
但是总能给 Collaborator 减轻一些压力吧（

**Comment by zkitefly** [comment]
在 GitHub Issue 编辑页面？

**Comment by allMagicNB** [comment]
> 在 GitHub Issue 编辑页面？
> 
> 我不记得官方有过这种东西？

就在启动器内部 更多->反馈 按钮

**Comment by rumengchuxing062** [comment]
> ### 检查项
> * [x]  我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
> * [x]  我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。
> 
> ### 描述
> 经实际验证，大多数提交反馈 Issue 的 Author 都不会依据检查项来检查，导致了很多重复 Issue
> 
> ### 原因
> 加入一个弹窗可以提醒反馈者进行检查，三秒让反馈者仔细阅读检查项，只在第一次点击按钮时弹窗不会让反馈者后续反馈觉得麻烦 虽然： “没救，侠客咋样都是侠客” ——龙腾猫跃 但是总能给 Collaborator 减轻一些压力吧（

我觉得就一次也不太现实，他们可能第一次会看，第二次可能就忘了

**Comment by rumengchuxing062** [comment]
而且描述也不清楚，害得我第一次看到时以为你在建议龙猫黑GitHub给这个页面加html\js代码

**Comment by allMagicNB** [comment]
~~看不清楚是你自己的事了，不要怪别人说不清楚，自己琢磨琢磨~~

**Comment by allMagicNB** [comment]
> > ### 检查项
> > * [x]  我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
> > * [x]  我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。
> > 
> > ### 描述
> > 经实际验证，大多数提交反馈 Issue 的 Author 都不会依据检查项来检查，导致了很多重复 Issue
> > 
> > ### 原因
> > 加入一个弹窗可以提醒反馈者进行检查，三秒让反馈者仔细阅读检查项，只在第一次点击按钮时弹窗不会让反馈者后续反馈觉得麻烦 虽然： “没救，侠客咋样都是侠客” ——龙腾猫跃 但是总能给 Collaborator 减轻一些压力吧（
> 
> 我觉得就一次也不太现实，他们可能第一次会看，第二次可能就忘了

忘了也没辙，这只是减少重复反馈的出现概率

**Comment by WForst-Breeze** [comment]
实际上能挡住的重复反馈数量几乎为0，以前金数据时候还强制搜索后才能反馈都挡不住，更别提这个了

**Comment by allMagicNB** [comment]
> 实际上能挡住的重复反馈数量几乎为0，以前金数据时候还强制搜索后才能反馈都挡不住，更别提这个了

~~好歹能挡一些是一些~~

**Comment by LTCatt** [comment]
真没啥用（

**Comment by allMagicNB** [comment]
> 真没啥用（

好吧，看起来真的什么都挡不住
