### ISSUE TITLE
关于Isometric Renders-0.4.5+1.20 关闭其缺少前置提示弹窗后，PCL显示：启动成功

### ISSUE THREAD

**Issue by yizhi9jiyan9** [Hex-Dragon/PCL2#3241]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在isometric-renders-0.4.5+1.20版本中 如未下载其前置“oωo (owo-lib)”会显示其自带的弹窗
在关闭弹窗后
PCL提示：启动成功
等待一会后并无游戏弹窗(废话)

### 重现步骤

1、下载isometric-renders-0.4.5+1.20
2、不下载其前置oωo (owo-lib)并直接启动游戏
3、显示缺少前置的弹窗后直接关闭弹窗
4、PCL2提示：启动成功

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14136367/Log1.txt)

**Comment by rumengchuxing062** [comment]
应该是[Issue #3328](https://github.com/Hex-Dragon/PCL2/issues/3228)导致的衍生问题

**Comment by rumengchuxing062** [comment]
不过依据原则还是测一测试试

**Comment by rumengchuxing062** [comment]
Mod 缺少依赖项没有输出报错，在点击Close后自动退出了
[2024-02-02-1.log](https://github.com/Hex-Dragon/PCL2/files/14136452/2024-02-02-1.log)

**Comment by rumengchuxing062** [comment]
没有Error，Exit Code 为0，已知只有Code!=0才会触发错误检测

**Comment by rumengchuxing062** [comment]
这个不是PCL的问题，你可以 Close 掉了

**Comment by allMagicNB** [comment]
没有完成最好不要Close as open……

**Comment by rumengchuxing062** [comment]
（雾）
