### ISSUE TITLE
在 PCL Mod\整合包 搜索框中输入奇长无比的字符会卡在正在获取 Mod\整合包 列表，并且反复几次搜索还能卡出奇高无比的CPU占用（>90%）

### ISSUE THREAD

**Issue by rumengchuxing062** [Hex-Dragon/PCL2#3242]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

卡在正在获取 Mod\整合包 列表，并且缓步提高CPU占用，删除后刷新仍然保持高CPU占用
只有搜索框有用，版本号那个卡不出来
~（突发奇想这个搜索框能不能卡个Bug）~

### 重现步骤

1、点击下载
2、点击 Mod\整合包
3、在搜索框打出奇长无比的字符（这里我用的反复复制粘贴 CON ）

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14136797/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14136793/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14136794/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14136795/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14136796/Log5.txt)

~懒猫你要不顺便写个判断符让版本号只能输入数字（雾）~

**Comment by allMagicNB** [comment]
而且这关于API吧，要看服务器响应

**Comment by rumengchuxing062** [comment]
> 你删除了你又没有重新搜索，当然还在搜索中

删了然后也点了搜索，列表是加载出来了，但是CPU占用还在那

**Comment by rumengchuxing062** [comment]
> 而且这关于API吧，要看服务器响应

没响应PCL会显示无法获取 xxx 的搜索结果，或者提示响应超时

**Comment by allMagicNB** [comment]
> > 你删除了你又没有重新搜索，当然还在搜索中
> 
> 删了然后也点了搜索，列表是加载出来了，但是CPU占用还在那
> 

确定是PCL的占用？截图下

**Comment by allMagicNB** [comment]
而且这应该属于优化吧，谁会搜索那么长……这是故意触发

**Comment by rumengchuxing062** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/110439412/225c94eb-d4d1-4474-9298-d03ba020c558)
我举报，PCL用我的电脑挖矿

**Comment by rumengchuxing062** [comment]
~还有天理吗！还有王法吗！~

**Comment by rumengchuxing062** [comment]
~懒猫：VB特性~

**Comment by allMagicNB** [comment]
> ~还有天理吗！还有王法吗！~

~~天理在原神那边，出门左拐~~

**Comment by rumengchuxing062** [comment]
> ~天理在原神那边，出门左拐~

~进不去，怎么想我都进不去吧.jpg~

**Comment by allMagicNB** [comment]
你确定这时候不是因为PCL2在发送过长数据到API时占用的CPU？

**Comment by rumengchuxing062** [comment]
> 你确定这时候不是因为PCL2在发送过长数据到API时占用的CPU？

发数据又不吃CPU，不然你交Issue为什么浏览器没有卡到爆

**Comment by rumengchuxing062** [comment]
> 你确定这时候不是因为PCL2在发送过长数据到API时占用的CPU？

~我觉得你可以去学学网络开发，然后你就不会有这个疑问了（bushi~

**Comment by allMagicNB** [comment]
> > 你确定这时候不是因为PCL2在发送过长数据到API时占用的CPU？
> 
> 发数据又不吃CPU，不然你交Issue为什么浏览器没有卡到爆

要处理数据发送

**Comment by rumengchuxing062** [comment]
> 你确定这时候不是因为PCL2在发送过长数据到API时占用的CPU？

而且吃CPU是API吃，API要处理数据然后发回，客户端只是解析结果而已，而且空值不可能吃CPU的说

**Comment by rumengchuxing062** [comment]
> > > 你确定这时候不是因为PCL2在发送过长数据到API时占用的CPU？
> > 
> > 
> > 发数据又不吃CPU，不然你交Issue为什么浏览器没有卡到爆
> 
> 要处理数据再发送，人家API也有格式的

叠加数据不会吃CPU
这对计算机来说就像1+1=2一样简单，并且我发这个Issue是为了让龙猫也做个限制，就算是处理占用CPU总不可能撤销处理也要吃CPU吧，并且这也算Bug

**Comment by allMagicNB** [comment]
> > 你确定这时候不是因为PCL2在发送过长数据到API时占用的CPU？
> 
> 而且吃CPU是API吃，API要处理数据然后发回，客户端只是解析结果而已，而且空值不可能吃CPU的说

我说，PCL2处理请求URL的时候

**Comment by rumengchuxing062** [comment]
> 要处理数据再发送，人家API也有格式的

你写字为什么不会卡

**Comment by rumengchuxing062** [comment]
> > > 你确定这时候不是因为PCL2在发送过长数据到API时占用的CPU？
> > 
> > 
> > 而且吃CPU是API吃，API要处理数据然后发回，客户端只是解析结果而已，而且空值不可能吃CPU的说
> 
> 我说的是PCL2处理请求URL的时候

就简单的叠加，
get(url=server+str(input))这样
处理过程就是
https://api.curseforge.com/search?words=input

**Comment by allMagicNB** [comment]
> > 要处理数据再发送，人家API也有格式的
> 
> 你写字为什么不会卡

你不想想那要处理多长啊，碰到符号还要转换

**Comment by allMagicNB** [comment]
> > > > 你确定这时候不是因为PCL2在发送过长数据到API时占用的CPU？
> > > 
> > > 
> > > 而且吃CPU是API吃，API要处理数据然后发回，客户端只是解析结果而已，而且空值不可能吃CPU的说
> > 
> > 我说的是PCL2处理请求URL的时候
> 
> 就简单的叠加，
> get(url=server+str(input))这样
> 处理过程就是
> https://api.curseforge.com/search?words=input

啊不不不，你忽略了符号

**Comment by rumengchuxing062** [comment]
> > > 要处理数据再发送，人家API也有格式的
> > 
> > 
> > 你写字为什么不会卡
> 
> 你不想想那要处理多长啊，碰到符号还要转换

就算真这样，这也是个Bug

**Comment by allMagicNB** [comment]
已知的、故意触发的……不算Bug

在电脑系统或程序中隐藏着的一些未被发现的缺陷或问题，人们也叫它“bug”

**Comment by allMagicNB** [comment]
版本号估计是先检查是否存在，不存在就不加入

**Comment by rumengchuxing062** [comment]
计算机的算力不会太低，人类都可以流畅的完成抄课文，计算机为什么不能流畅的叠加数据

**Comment by rumengchuxing062** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/110439412/c936afe9-0dd5-4dc7-bcb6-1a806c3ee217)

**Comment by rumengchuxing062** [comment]
@allMagicNB 这串字符比之前的还长，Python只用了<0.1秒就完成了，所以不存在什么转换吃CPU什么的

**Comment by rumengchuxing062** [comment]
真的吃CPU的话，Python只能在几秒后给出结果

**Comment by allMagicNB** [comment]
> @allMagicNB 这串字符比之前的还长，Python只用了<0.1秒就完成了，所以不存在什么转换吃CPU什么的

我说，转成网页格式

**Comment by WForst-Breeze** [comment]
请各位讨论时善用 Edit

**Comment by rumengchuxing062** [comment]
> > @allMagicNB 这串字符比之前的还长，Python只用了<0.1秒就完成了，所以不存在什么转换吃CPU什么的
> 
> 我说，转成网页格式

API发回来的是json好吗

**Comment by allMagicNB** [comment]
> > > @allMagicNB 这串字符比之前的还长，Python只用了<0.1秒就完成了，所以不存在什么转换吃CPU什么的
> > 
> > 我说，转成网页格式
> 
> API发回来的是json好吗

发送时转换……

**Comment by LTCatt** [comment]
请不要版聊，冷静讨论，提 issue 的目的不是为了在争论中赢过对方

**Comment by LTCatt** [comment]
将文本框的最大允许字符数从 10000 下调到了 1000
