### ISSUE TITLE
拖入mod文件相关问题

### ISSUE THREAD

**Issue by endercatone** [Hex-Dragon/PCL2#3246]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

当通过某些软件(如firefox浏览器的下载窗口等传入路径为file:///xxx)拖入mod文件时，当文件名包含`+`时，会变成空格，导致无法找到文件

### 重现步骤

1、在firefox浏览器等下载一个包含+号的mod文件
2、直接通过下载窗口拖动到PCL窗口
3、出现报错"拖入的文件不存在："

![图片](https://github.com/Hex-Dragon/PCL2/assets/80958388/b4efedbd-a345-49ff-912f-eadff6f9722e)
![图片](https://github.com/Hex-Dragon/PCL2/assets/80958388/011e0733-61a2-43b5-afad-65e4e3970221)

### 日志与附件

相关日志：
```
[23:19:35.844] [System] 接受文本拖拽：file:///C:/Users/endercat/Downloads/ImmediatelyFast-Fabric-1.2.10+1.20.4.jar
[23:19:35.845] [System] 接受文件拖拽：C:\Users\endercat\Downloads\ImmediatelyFast-Fabric-1.2.10 1.20.4.jar 等 1 个文件
[23:19:35.877] [UI] 弹出提示：拖入的文件不存在：C:\Users\endercat\Downloads\ImmediatelyFast-Fabric-1.2.10 1.20.4.jar
```

**Comment by youzi-2333** [comment]
从第一行日志看，拖入文件未被 url 编码，但是 PCL 进行了 url 解码导致了加号变成空格。

https://github.com/Hex-Dragon/PCL2/blob/8c8b1066bff6476a14437a14bc16a281e25145bd/Plain%20Craft%20Launcher%202/FormMain.xaml.vb#L834-L839

使用在线解码工具，也同样出现了这个问题，这是由于空格会被 url 编码为 `+`，PCL 误将未被编码的文本进行了解码。

不过确实挺难判断传入文本有没有被编码过……我的想法是在找不到文件时把源字符串拿来，再尝试读取一遍……

**Comment by rumengchuxing062** [comment]
交了个PR，看看猫猫会不会合并

**Comment by rumengchuxing062** [comment]
但为什么我可以
![image](https://github.com/Hex-Dragon/PCL2/assets/110439412/8f7bfd93-f789-4d6e-a9f8-71d664c850d6)
@youzi-2333 你试过了没

**Comment by allMagicNB** [comment]
Author你要不然直接把完整日志上传上来吧……

**Comment by rumengchuxing062** [comment]
@endercatone 传一下完整日志，以方便我确定这个Issue是否有效，从而决定PR是否必要

**Comment by WForst-Breeze** [comment]
不需要传日志了，火狐浏览器可以复现，Edge 无法复现，留意反馈者描述为：`直接通过下载窗口拖动到PCL窗口`

本人复现日志可见：
Edge：
```
[15:16:35.601] [System] 接受文件拖拽：H:\Mydownload\sodium-fabric-0.5.8+mc1.20.4 (1).jar 等 1 个文件
[15:16:35.601] [System] 文件为 jar/litemod 格式，尝试作为 Mod 安装
[15:16:35.609] [Control] 普通弹窗：Mod 安装确认
是否要将这些文件作为 Mod 安装到 1.20.4-Fabric 0.15.6？
```

火狐：
```
[15:17:15.233] [System] 接受文本拖拽：file:///H:/Mydownload/sodium-fabric-0.5.8+mc1.20.4(1).jar
[15:17:15.233] [System] 接受文件拖拽：H:\Mydownload\sodium-fabric-0.5.8 mc1.20.4(1).jar 等 1 个文件
[15:17:15.252] [UI] 弹出提示：拖入的文件不存在：H:\Mydownload\sodium-fabric-0.5.8 mc1.20.4(1).jar
```

**Comment by allMagicNB** [comment]
> 不需要传日志了，火狐浏览器可以复现，Edge 无法复现，留意反馈者描述为：`直接通过下载窗口拖动到PCL窗口`
> 
> 本人复现日志可见：
> Edge：
> ```
> [15:16:35.601] [System] 接受文件拖拽：H:\Mydownload\sodium-fabric-0.5.8+mc1.20.4 (1).jar 等 1 个文件
> [15:16:35.601] [System] 文件为 jar/litemod 格式，尝试作为 Mod 安装
> [15:16:35.609] [Control] 普通弹窗：Mod 安装确认
> 是否要将这些文件作为 Mod 安装到 1.20.4-Fabric 0.15.6？
> ```
> 
> 火狐：
> ```
> [15:17:15.233] [System] 接受文本拖拽：file:///H:/Mydownload/sodium-fabric-0.5.8+mc1.20.4(1).jar
> [15:17:15.233] [System] 接受文件拖拽：H:\Mydownload\sodium-fabric-0.5.8 mc1.20.4(1).jar 等 1 个文件
> [15:17:15.252] [UI] 弹出提示：拖入的文件不存在：H:\Mydownload\sodium-fabric-0.5.8 mc1.20.4(1).jar
> ```

所以……这算是第三方吗？

**Comment by rumengchuxing062** [comment]
> > 不需要传日志了，火狐浏览器可以复现，Edge 无法复现，留意反馈者描述为：`直接通过下载窗口拖动到PCL窗口`
> > 本人复现日志可见：
> > Edge：
> > ```
> > [15:16:35.601] [System] 接受文件拖拽：H:\Mydownload\sodium-fabric-0.5.8+mc1.20.4 (1).jar 等 1 个文件
> > [15:16:35.601] [System] 文件为 jar/litemod 格式，尝试作为 Mod 安装
> > [15:16:35.609] [Control] 普通弹窗：Mod 安装确认
> > 是否要将这些文件作为 Mod 安装到 1.20.4-Fabric 0.15.6？
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 火狐：
> > ```
> > [15:17:15.233] [System] 接受文本拖拽：file:///H:/Mydownload/sodium-fabric-0.5.8+mc1.20.4(1).jar
> > [15:17:15.233] [System] 接受文件拖拽：H:\Mydownload\sodium-fabric-0.5.8 mc1.20.4(1).jar 等 1 个文件
> > [15:17:15.252] [UI] 弹出提示：拖入的文件不存在：H:\Mydownload\sodium-fabric-0.5.8 mc1.20.4(1).jar
> > ```
> 
> 所以……这算是第三方吗？

可能是FireFox的编码问题，算第三方但是可以解决

**Comment by rumengchuxing062** [comment]
@WForst-Breeze 先打个第三方的标签

**Comment by rumengchuxing062** [comment]
> 不需要传日志了，火狐浏览器可以复现，Edge 无法复现，留意反馈者描述为：`直接通过下载窗口拖动到PCL窗口`

留意了，但是用的 Edge
