### ISSUE TITLE
我想知道这个正式版的 .zip 包，为什么不放在 release 页面的 assets 里?

### ISSUE THREAD

**Issue by ohjunk2001** [Hex-Dragon/PCL2#3249]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

1. 把发布的安装包放在 release 页面的 assets
2. 希望日后发布软件能区分一下版本比如，Pre-alpha，Alpha，Beta，Stable 等
，

### 原因

这样做更加规范一点

当然，开源是一件很耗费精力的事情

如果，你觉得这么做，是在浪费你宝贵的时间和精力，请当我没说

最后，向你致敬

**Comment by allMagicNB** [comment]
并且已经区分了版本啊
快照版（Snapshot）和正式版（Release）

**Comment by allMagicNB** [comment]
综上所述，**龙猫只会公开正式版，不会公开快照版**
那能公开的就只剩一个正式版了
那既然只剩一个版本，又为何还要藏那么深的文件夹？
更何况确实没必要一个版本套俩文件夹里，这样的操作只会减缓软件使用者的下载速度

**Comment by hejiehao** [comment]
> 综上所述，**龙猫只会公开正式版，不会公开快照版** 那能公开的就只剩正式版了 那既然只剩一个版本，又为何还要藏那么深的文件夹？ 更何况确实没必要一个版本套俩文件夹里，这样的操作只会减缓软件使用者的下载速度

他说的应该是这个吧
<img width="1279" alt="QQ截图20240203092841" src="https://github.com/Hex-Dragon/PCL2/assets/98140773/6c6d3686-a39e-41ac-8589-471652876b6f">

**Comment by allMagicNB** [comment]
> > 综上所述，**龙猫只会公开正式版，不会公开快照版** 那能公开的就只剩正式版了 那既然只剩一个版本，又为何还要藏那么深的文件夹？ 更何况确实没必要一个版本套俩文件夹里，这样的操作只会减缓软件使用者的下载速度
> 
> 他说的应该是这个吧
> <img width="1279" alt="QQ截图20240203092841" src="https://github.com/Hex-Dragon/PCL2/assets/98140773/6c6d3686-a39e-41ac-8589-471652876b6f">
> 

~~《安装包》……~~

**Comment by hejiehao** [comment]
> > > 综上所述，**龙猫只会公开正式版，不会公开快照版** 那能公开的就只剩正式版了 那既然只剩一个版本，又为何还要藏那么深的文件夹？ 更何况确实没必要一个版本套俩文件夹里，这样的操作只会减缓软件使用者的下载速度
> > 
> > 
> > 他说的应该是这个吧
> > <img alt="QQ截图20240203092841" width="1279" src="https://private-user-images.githubusercontent.com/98140773/302004764-6c6d3686-a39e-41ac-8589-471652876b6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5MjQyNjksIm5iZiI6MTcwNjkyMzk2OSwicGF0aCI6Ii85ODE0MDc3My8zMDIwMDQ3NjQtNmM2ZDM2ODYtYTM5ZS00MWFjLTg1ODktNDcxNjUyODc2YjZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDAxMzI0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4MGI0YzJjYjM0YTg5OTJmNjJlOGFjZTA5MWViY2U1NWRhNjU5YzFlYTY5ZTRkOTJkMmExYTM4ODk4OGFlYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ByjJjdId0I73W4VJl7m-dSk_x3o_rpEETv__karht_I">
> 
> ~《安装包》……~ 这样子也不统一啊，比如有的时候是快照版更新，正式版没有……

把快照版设置成 Set as a pre-release？

**Comment by allMagicNB** [comment]
感觉还是没必要，还是要多点一次才能下载……

**Comment by hejiehao** [comment]
> 感觉还是没必要，还是要多点一次才能下载……

放 exe 就行

**Comment by allMagicNB** [comment]
🤔

**Comment by allMagicNB** [comment]
> 把快照版设置成 Set as a pre-release？

反正目前改了会造成版本不对应……

**Comment by allMagicNB** [comment]
反正，龙猫不放应该是有道理的……

**Comment by xxtg666** [comment]
说不定是考虑到有人不会用 github

**Comment by allMagicNB** [comment]
> 说不定是考虑到有人不会用 github

不会用那为什么不直接选择蓝奏云盘下载（

**Comment by rumengchuxing062** [comment]
因为 GitHub 服务器在新加坡，直接发release就会有人以为只有这个方法可以下载，然后因为下载困难发Issue

**Comment by iPodtouch6557** [comment]
> 因为 GitHub 服务器在新加坡，直接发release就会有人以为只有这个方法可以下载，然后因为下载困难发Issue

顺便问下，所以是否挂vpn新加坡最快

**Comment by allMagicNB** [comment]
> > 因为 GitHub 服务器在新加坡，直接发release就会有人以为只有这个方法可以下载，然后因为下载困难发Issue
> 
> 顺便问下，所以是否挂vpn新加坡最快

GitHub硕大的一个公司啊，怎么会只有一台服务器呢（

**Comment by iPodtouch6557** [comment]
> > > 因为 GitHub 服务器在新加坡，直接发release就会有人以为只有这个方法可以下载，然后因为下载困难发Issue
> > 
> > 
> > 顺便问下，所以是否挂vpn新加坡最快
> 
> GitHub硕大的一个公司啊，怎么会只有一台服务器呢（

所以美国的也能用啊 就是想看看能不能更快

**Comment by WorldHim** [comment]
先别急着 close 啊，问下龙猫（

**Comment by allMagicNB** [comment]
> 先别急着 close 啊，问下龙猫（

龙猫搞这么多年有他的道理（

**Comment by hejiehao** [comment]
> > 先别急着 close 啊，问下龙猫（
> 
> 龙猫搞这么多年有他的道理（

那也得把道理问出来先（

**Comment by rumengchuxing062** [comment]
> 顺便问下，所以是否挂vpn新加坡最快

GitHub 有 CDN 和泛播，理论上挂国外访问速度都很快

**Comment by rumengchuxing062** [comment]
> GitHub硕大的一个公司啊，怎么会只有一台服务器呢（

GitHub Web Server 只有一台，其他的交给 CDN 处理

**Comment by iPodtouch6557** [comment]
> > 顺便问下，所以是否挂vpn新加坡最快
> 
> GitHub 有 CDN 和泛播，理论上挂国外访问速度都很快

有的不可以 试过了

**Comment by LTCatt** [comment]
没啥太大用，毕竟大家下 PCL 几乎不会去 GitHub 下吧……反而我发更新会又多一个步骤 Orz

**Comment by allMagicNB** [comment]
> 没啥太大用，毕竟大家下 PCL 几乎不会去 GitHub 下吧……反而我发更新会又多一个步骤 Orz

对啊，基本都是去蓝奏云盘（
