### ISSUE TITLE
增加新用户自定义启动器位置

### ISSUE THREAD

**Issue by shaoxiu** [Hex-Dragon/PCL2#3253]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

打开启动器时，检测 **是否已有注册表** && 附近 **是否有 `.minecraft/` 文件夹**。若为第一次打开启动器且附近无整合包，则弹窗询问用户需要将启动器放置何目录，并自动在桌面新增快捷方式。

### 原因

在 PCL 的一群看到还是有人分不清快捷方式和应用程序时想到的。或许他们更需要一个类似 MCL installer 指定路径的操作方式。

**Comment by allMagicNB** [comment]
整合包检测不到的，除非把每个都解压……

**Comment by allMagicNB** [comment]
而且

###没必要

**Comment by iPodtouch6557** [comment]
> 整合包检测不到的，除非把每个都解压……

比如PCL把我的错误报告识别成了mod（

**Comment by allMagicNB** [comment]
实在不行的话
![Screenshot_20240203_155639.jpg](https://github.com/Hex-Dragon/PCL2/assets/116283787/c5d0e8a8-8d96-497e-b937-c2fb1f14705d)

**Comment by rumengchuxing062** [comment]
你就这么告诉他，你要是实在不会就别玩了，我很确信就算有了 installer 还是有问题频繁出现

**Comment by rumengchuxing062** [comment]
> 你就这么告诉他，你要是实在不会就别玩了，我很确信就算有了 installer 还是有问题频繁出现

要不你看看为什么会有这么多重复反馈，他们要是不会仔细阅读帮助你就算把所有东西都做成 installer 他们还是不会

**Comment by rumengchuxing062** [comment]
另外你这个应该选择新功能而不是优化

**Comment by allMagicNB** [comment]
你就把他们供着吧，该不会的还是不会

**Comment by Pigeon0v0** [comment]
倒是可以检测启动器当前运行目录是否在桌面 / 浏览器之类的下载目录，如果在的话提醒用户转移

**Comment by LTCatt** [comment]
没啥用，真萌新到那个程度的玩家你提示他换目录他大概率根本搞不懂该换到哪 =。=

**Comment by allMagicNB** [comment]
> 倒是可以检测启动器当前运行目录是否在桌面 / 浏览器之类的下载目录，如果在的话提醒用户转移

在桌面的话没事啊，文件夹直接隐藏

**Comment by allMagicNB** [comment]
> 没啥用，真萌新到那个程度的玩家你提示他换目录他大概率根本搞不懂该换到哪 =。=

真·萌新对于反馈的检查项也是这样的
~~直接秒掉了待处理~~

**Comment by rumengchuxing062** [comment]
> 在桌面的话没事啊，文件夹直接隐藏

汝可听闻过 Permission denied 的说
