### ISSUE TITLE
版本文件丢失

### ISSUE THREAD

**Issue by DevilPPPP** [Hex-Dragon/PCL2#3255]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

电脑未关机，一段时间重新都登陆PCL2的时候所有的版本文件全部不见了·，包括存档，当我重新下载版本的时候，存档是以前的，现在无法找到存档，但MOD存在，这是怎么造成的？如何找到最新存档？

### 重现步骤

1、点击xxxx
2、往下滚，然后点击xxxx

### 日志与附件

![Uploading D9@}I688$7MD[W2C~LYGPHV.png…]()

**Comment by allMagicNB** [comment]
请等待`Uploading xxx`字样消失后再发……

**Comment by allMagicNB** [comment]
这应该不是PCL2的问题，你可以发Discussion……

**Comment by Pigeon0v0** [comment]
自行使用文件搜索工具搜索 .minecraft 目录

**Comment by allMagicNB** [comment]
> 自行使用文件搜索工具搜索 .minecraft 目录

例如：Everything

**Comment by DevilPPPP** [comment]
搜索了，所有文件我都翻了遍，都没找到

> 自行使用文件搜索工具搜索 .minecraft 目录

**Comment by allMagicNB** [comment]
> 搜索了，所有文件我都翻了遍，都没找到
> 
> > 自行使用文件搜索工具搜索 .minecraft 目录
> 
> 

去开Discussion

**Comment by DevilPPPP** [comment]
> 自行使用文件搜索工具搜索 .minecraft 目录

未找到

**Comment by hejiehao** [comment]
怎么感觉用了其他启动器

**Comment by WorldHim** [comment]
后续讨论请移步 #3256

**Comment by DevilPPPP** [comment]
> 这应该不是PCL2的问题，你可以发Discussion......

目前确定不是微软问题，只能是PCL2

**Comment by DevilPPPP** [comment]
> 怎么感觉用了其他启动器

只有PCL2

**Comment by DevilPPPP** [comment]
> 

搜索了，未找到，数据恢复也没找到

**Comment by allMagicNB** [comment]
找找回收站

**Comment by DevilPPPP** [comment]
> 找找回收站

没用

**Comment by allMagicNB** [comment]
要么就误删要么就不是你删的

**Comment by DevilPPPP** [comment]
> 要么就误删要么就不是你删的

不可能，根本就没动过，模组的设置还在，只是版本文件及里面的存档没了

**Comment by allMagicNB** [comment]
> > 要么就误删要么就不是你删的
> 
> 不可能，根本就没动过，模组的设置还在，只是版本文件及里面的存档没了

你是不是没开版本隔离然后开了

**Comment by DevilPPPP** [comment]
> > > 要么就误删要么就不是你删的
> > 
> > 
> > 不可能，根本就没动过，模组的设置还在，只是版本文件及里面的存档没了
> 
> 你是不是没开版本隔离然后开了

版本隔离了

**Comment by allMagicNB** [comment]
> > > > 要么就误删要么就不是你删的
> > > 
> > > 
> > > 不可能，根本就没动过，模组的设置还在，只是版本文件及里面的存档没了
> > 
> > 你是不是没开版本隔离然后开了
> 
> 版本隔离了

存档发上来

**Comment by DevilPPPP** [comment]
> > > > > 要么就误删要么就不是你删的
> > > > 
> > > > 
> > > > 不可能，根本就没动过，模组的设置还在，只是版本文件及里面的存档没了
> > > 
> > > 
> > > 你是不是没开版本隔离然后开了
> > 
> > 
> > 版本隔离了
> 
> 存档发上来

现在重新下了版本文件

**Comment by Pigeon0v0** [comment]
不要版聊，这不是 PCL 的问题

**Comment by allMagicNB** [comment]
> 不要版聊，这不是 PCL 的问题

我还以为这里是Discussion（
都转Discussion了Author的后续还是发到Issue里……

**Comment by DevilPPPP** [comment]
> 不要版聊，这不是 PCL 的问题

哥们儿你怎么证明不是，其他地方也有人出现过问题，都没有解决方案

**Comment by allMagicNB** [comment]
> > 不要版聊，这不是 PCL 的问题
> 
> 哥们儿你怎么证明不是，其他地方也有人出现过问题，都没有解决方案

你怎么就证明是了🤣

**Comment by DevilPPPP** [comment]
> > > 不要版聊，这不是 PCL 的问题
> > 
> > 
> > 哥们儿你怎么证明不是，其他地方也有人出现过问题，都没有解决方案
> 
> 你怎么就证明是了🤣

搜索引擎找不到，数据恢复找不到，微软杀毒也都检查了，你说还有什么可能，HMCL都没出现过这个问题，1年没玩存档版本文件都在🤣🤣🤣

**Comment by allMagicNB** [comment]
> 搜索引擎找不到，数据恢复找不到，微软杀毒也都检查了，你说还有什么可能，HMCL都没出现过这个问题，1年没玩存档版本文件都在🤣🤣🤣

我也不想版聊啊，可是你有直接性证据吗？

**Comment by DevilPPPP** [comment]
> > 搜索引擎找不到，数据恢复找不到，微软杀毒也都检查了，你说还有什么可能，HMCL都没出现过这个问题，1年没玩存档版本文件都在🤣🤣🤣
> 
> 我也不想版聊啊，可是你有直接性证据吗？

我也只想解决问题，找到存档，我也不想版聊，那你有直接证据不是PCL2的问题吗，我上面那个不是证据吗

**Comment by allMagicNB** [comment]
都别说了，既没有直接性证据证明不是PCL2做的
# 也没有直接性证据证明是PCL2做的

**Comment by DevilPPPP** [comment]
> 都别说了，既没有直接性证据证明不是PCL2做的
> 
> # 也没有直接性证据证明是PCL2做的
那你能告诉我这种情况到底咋弄

**Comment by allMagicNB** [comment]
> > 都别说了，既没有直接性证据证明不是PCL2做的
> > 
> > # 也没有直接性证据证明是PCL2做的
> 那你能告诉我这种情况到底咋弄

你说我要跟你讲多久你才去Discussion聊

**Comment by WForst-Breeze** [comment]
请友善冷静讨论，这里是解决问题的地方，不是吵架的地方

这个问题不是 PCL 导致的，因为 PCL 不会无故删除文件（除非是清理游戏垃圾，但一般来讲没人会在这些地方放重要文件或者存档）只能是系统或者硬件问题，请到 Discussion 中求助

**Comment by allMagicNB** [comment]
> 请各位友善冷静讨论，这里是解决问题的地方，不是吵架的地方
> 
> 这个问题不是 PCL 导致的，因为 PCL 不会无故删除文件（除非是清理游戏垃圾，但一般来讲没人会在这些地方放重要文件或者存档）只能是系统或者硬件问题，请到 Discussion 中求助

我也在想啊，但是都单独开了Discussion作者还是要把后续发到这条Issue里……

**Comment by iPodtouch6557** [comment]
给它上锁
