### ISSUE TITLE
启动器报毒

### ISSUE THREAD

**Issue by lsinda** [Hex-Dragon/PCL2#3257]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![183f75bc4c9cdee5c8010ecd06b3ab85](https://github.com/Hex-Dragon/PCL2/assets/140962801/3e3c2470-7d44-4487-bce9-f9008183020f)
ne

### 重现步骤

作者你好可以把源代码发给我吗？plas，或者发到我的邮箱 
放心不外传，如果我外传你的源代码你可以删除我的帖子
这是我的qq邮箱：417354560@qq.com 

### 日志与附件

![183f75bc4c9cdee5c8010ecd06b3ab85](https://github.com/Hex-Dragon/PCL2/assets/140962801/e384265e-2d03-4c30-8181-067c8869c96c)

**Comment by allMagicNB** [comment]
外传了删帖有啥用？

**Comment by lsinda** [comment]
> 外传了删帖有啥用？ 还有，你要源码做啥？除了主题系统其它源码都是公开的

哦，谢谢

**Comment by lsinda** [comment]
源代码好像无法下载，下载就报错

**Comment by allMagicNB** [comment]
> 源代码好像无法下载，下载就报错
> 
> 

……个人网络原因吧，总不可能源码都报错
