### ISSUE TITLE
高版本安装OptiFine与Mod Loader时给予用户提醒

### ISSUE THREAD

**Issue by LTCatt** [Hex-Dragon/PCL2#3258]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

详见：https://github.com/MCLF-CN/docs/issues/6

**Comment by SALTWOOD** [comment]
可以让用户考虑用sodium替代

**Comment by LTCatt** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/ef0f010b-5662-4bb4-818e-bf2e479d14b1)
加了个小提示
