### ISSUE TITLE
PCL无法启动

### ISSUE THREAD

**Issue by TMXQWQ** [Hex-Dragon/PCL2#3260]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/Hex-Dragon/PCL2/assets/122204742/56cb0e96-f0e0-4b16-99f8-bdf2538e2f23)
使用了管理员权限，依然无法启动

切换了工作目录，无法确定（一样的报错）

### 重现步骤

1、启动PCL

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14155763/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14155764/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14155765/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14155766/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14155767/Log2.txt)

**Comment by allMagicNB** [comment]
你要不然加我QQ我来给你看看？
这应当不是PCL2的问题
654972012

**Comment by xhahello** [comment]
有没有 Collaborator 过来关一下

**Comment by rumengchuxing062** [comment]
@TMXQWQ 右键PCL，选择属性-安全选项卡-点击高级，在弹出的对话框内检查是否有Users，是否有执行权限，再检查你的账户是否有执行权限，另外不建议在以下目录存放PCL
硬盘根目录
Users文件夹下的任何目录
Temp目录，这些目录需要高权限执行

**Comment by rumengchuxing062** [comment]
@WForst-Breeze 来关一下

**Comment by allMagicNB** [comment]
可以尝试放到其他分区，比如D盘

**Comment by TMXQWQ** [comment]
试过了（U盘里）



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年02月04日 14:55 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Hex-Dragon/PCL2] PCL无法启动 (Issue #3260) |

可以尝试放到其他分区，比如D盘

**Comment by TMXQWQ** [comment]
我是管理员，在桌面和U盘里运行，以前可以正常运行，最近出现的。这几天可以正常运行。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年02月04日 14:47 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Hex-Dragon/PCL2] PCL无法启动 (Issue #3260) |

@TMXQWQ 右键PCL，选择属性-安全选项卡-点击高级，在弹出的对话框内检查是否有Users，是否有执行权限，再检查你的账户是否有执行权限，另外不建议在以下目录存放PCL
硬盘根目录
Users文件夹下的任何目录
Temp目录，这些目录需要高权限执行

**Comment by JingHai-Lingyun** [comment]
请不要在桌面或 C 盘运行 PCL，在这些地方需要非常高的权限运行应用，会导致此错误
