### ISSUE TITLE
能否为PCL添加一个绑定git功能

### ISSUE THREAD

**Issue by north-dt** [Hex-Dragon/PCL2#3265]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

接入git后，先用电脑一号将文件传到GitHub，再在电脑2号上下载文件，玩家可在每次玩完游戏（或仅在特殊情况）使用git提交新版本，就不用担心进度不一致的情况

### 原因

有时我们可能因一些原因玩不到MC，例如我马上要回家过年，家里的台式搬不走，但是我有一个笔记本能带过去。这时候如果用U盘拷过去就会面临一些问题

**Comment by allMagicNB** [comment]
已经说过了，
# 不可能绑定云服务

**Comment by burningtnt** [comment]
Git 不善于追踪二进制文件

**Comment by allMagicNB** [comment]
还有，GitHub是开源社区
# 不是网盘

**Comment by rumengchuxing062** [comment]
抱歉，但是 GitHub 访问困难（针对境内），并且有提交限制，WebSite限制提交大小为25M，Git限制为100M，另外大量Raw\Git 请求会加重 GitHub 服务器的负荷，并导致存储库被禁用\删除\关闭 Raw 服务\封禁GitHub账户\IP限制，并可能连带PCL的存储库\开发者账号\Collaborator 账号\和所有参与此Issue的账号被封禁

**Comment by rumengchuxing062** [comment]
另外也增加了安全风险

**Comment by rumengchuxing062** [comment]
另外请善用 Microsoft Onedriver 网盘，USB驱动器，手机，其他网盘

**Comment by allMagicNB** [comment]
建议使用私人网盘软件，压缩`.minecraft`文件夹之后上传即可，要用再下载回来

**Comment by allMagicNB** [comment]
> 另外请善用 Microsoft Onedriver 网盘，USB驱动器，手机，其他网盘

《微软 一个司机》

**Comment by rumengchuxing062** [comment]
> 建议使用私人网盘软件，压缩`.minecraft`文件夹之后上传即可，要用再下载回来

直接把.minecraft放到Onedrive同步目录不是更好？

**Comment by rumengchuxing062** [comment]
@WForst-Breeze 这个没有可能实现吧。。。。

**Comment by WForst-Breeze** [comment]
那我也不能替龙猫做决断啊（

**Comment by rumengchuxing062** [comment]
> 那我也不能替龙猫做决断啊（

~我觉得打个忽略就行了，GitHub不是给你当云存档使得，GitHub可能会因为这个功能发Issue警告（之前春运抢票就因为插件作者用 GitHub Raw，使得 GitHub 在春运期间被CC了）~

**Comment by rumengchuxing062** [comment]
而且GitHub境内也不稳定，同步失败肯定有人发Issue，这不就是在增加我们的工作量么。。。。

**Comment by rumengchuxing062** [comment]
你如果觉得不能替龙猫做决定，那就挂着看龙猫怎么说

**Comment by allMagicNB** [comment]
> 那我也不能替龙猫做决断啊（

![Screenshot_20240205_145039.jpg](https://github.com/Hex-Dragon/PCL2/assets/116283787/6a5a809a-3b0b-4c46-aa4f-8f40a4171fee)
……

**Comment by allMagicNB** [comment]
> > 建议使用私人网盘软件，压缩`.minecraft`文件夹之后上传即可，要用再下载回来
> 
> 直接把.minecraft放到Onedrive同步目录不是更好？
> 而且你不太可能没有Microsoft账号

啊不不不，有没有一种可能，OneDrive要开梯子

**Comment by SALTWOOD** [comment]
1. git 不是这么用的啊喂(#`O′)
2. 国内不稳定，做了也很难用，一堆人发 issue 说用不了
3. Onedrive 不香？

**Comment by rumengchuxing062** [comment]
> > > 建议使用私人网盘软件，压缩`.minecraft`文件夹之后上传即可，要用再下载回来
> > 
> > 
> > 直接把.minecraft放到Onedrive同步目录不是更好？
> > 而且你不太可能没有Microsoft账号
> 
> 啊不不不，有没有一种可能，OneDrive要开梯子

开个der的梯子，我裸连都能上

**Comment by allMagicNB** [comment]
> > 啊不不不，有没有一种可能，OneDrive要开梯子
> 
> 开个der的梯子，我裸连都能上

裸连也不是很乐观

**Comment by rumengchuxing062** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/110439412/2f67697e-7421-41b3-9619-e900c0537eb3)
![image](https://github.com/Hex-Dragon/PCL2/assets/110439412/9e32d40a-73d4-4548-bd5f-7ff4376fd93e)
~ha 略感疲惫~
你看我可没开梯子，我能上啊

**Comment by rumengchuxing062** [comment]
> 裸连也不是很乐观

福州移动很宽松，MoJang API就没见他禁过

**Comment by allMagicNB** [comment]
> > 裸连也不是很乐观
> 
> 福州移动很宽松，MoJang API就没见他禁过

善用Hide，另外
~~Mojang的“j”不是大写（~~

**Comment by WForst-Breeze** [comment]
不要版聊，watch 了这个仓库的人的邮箱会炸的

**Comment by allMagicNB** [comment]
> 不要版聊，watch 了这个仓库的人的邮箱会炸的

~~你不觉得是某个人没有善用Edit吗~~

**Comment by SALTWOOD** [comment]
差不多得了，干脆锁了吧（？）邮箱炸了登不进去了（悲）

**Comment by LTCatt** [comment]
不考虑制作，抱歉
