### ISSUE TITLE
[优化]自定义主页中使用列表项作为联网帮助页面入口时，若已指定标题，则不报错

### ISSUE THREAD

**Issue by Xiaolv114518** [Hex-Dragon/PCL2#3266]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

现在，自定义主页中使用列表项作为联网帮助页面入口时 会因为要获取信息导致卡死 而报错，而对应的列表项也是空白，如图。
![image](https://github.com/Hex-Dragon/PCL2/assets/141309773/1c84dcc5-c3bd-460d-979b-5ed4005b490d)
此时的部分源代码如下：
![image](https://github.com/Hex-Dragon/PCL2/assets/141309773/6d7d46ef-01cb-4775-9de9-ab6b51c58aff)
所以我自己给该列表项指定了标题和信息，且该列表项可以正常显示我指定的标题和信息，如图。
![image](https://github.com/Hex-Dragon/PCL2/assets/141309773/58a0f9c4-6644-44b4-a02f-9c948cb1ece7)
此时的部分源代码如下：
![image](https://github.com/Hex-Dragon/PCL2/assets/141309773/98c2bedc-37e6-457b-9099-172b8ae397e6)
但 PCL 在我已经指定了标题和信息时，**加载主页仍然会获取该联网帮助的信息，导致报错**，如图。
![image](https://github.com/Hex-Dragon/PCL2/assets/141309773/31aa2fe8-5bbe-4531-8b1b-595dfc67c9cb)
因此我觉得可以在加载这种列表项之前**先判定是否已指定了 Title，如果有，就直接加载指定的 Title、Info 和 Logo，如果没有再报错。**

### 原因

如果没有这项优化，我每次都必须先把报错弹窗点掉，让体验变得很不好。

**Comment by rumengchuxing062** [comment]
请提供日志文件，以及检查版本，未能复现所述Bug

**Comment by rumengchuxing062** [comment]
@WForst-Breeze 打个label:等待反馈者

**Comment by rumengchuxing062** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/110439412/fa911ae7-9502-4e47-82f2-0e21d8501391)
@Xiaolv114518 百宝箱内没有对应键值

**Comment by rumengchuxing062** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/110439412/ee350684-9db3-4f0e-84c8-53306c1cfd42)
根本加载不了

**Comment by rumengchuxing062** [comment]
@Xiaolv114518 你看看版本是不是最新的（2.6.13）

**Comment by rumengchuxing062** [comment]
复现成功，确实有必要修
@WForst-Breeze 来打个label？

**Comment by rumengchuxing062** [comment]
> > @Xiaolv114518 你看看版本是不是最新的（2.6.13）
> 
> 是的 ![image](https://private-user-images.githubusercontent.com/141309773/302182806-8433df79-c257-486d-b88b-d49e5e0ece39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMTA3MTgsIm5iZiI6MTcwNzExMDQxOCwicGF0aCI6Ii8xNDEzMDk3NzMvMzAyMTgyODA2LTg0MzNkZjc5LWMyNTctNDg2ZC1iODhiLWQ0OWU1ZTBlY2UzOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNVQwNTIwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNjIxMWYzODlkZGNiOTlhYjRkOTcwMTA5NDBmMjljYzdmYTUwM2U1MmVmOWE1MzcxZWJiMGFlYTZmODMyNTk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3CYdf4oSl5GvtN3wfBYx5X6AAeTtKiQF88Sbl46KjWM)

~看错Issue标题了~

**Comment by allMagicNB** [comment]
> 识别码：BE7F-6BE5-3501-7CA2 求活跃橙主题解锁码，谢谢 （我知道我领过了，但是我换了电脑然后懒得找管理）

你应该去#2416

**Comment by LTCatt** [comment]
你的解锁码：3wmkhRx5DXsqOqeLHRLB3hwWNdnj6ovW
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
