### ISSUE TITLE
有三个模组没有列出前置模组

### ISSUE THREAD

**Issue by TzAAnvil** [Hex-Dragon/PCL2#3267]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

1.(1.19.2)"精妙存储Sophisticated Storage"没列出前置模组"精妙核心Sophisticated Core";
2.(1.19.2)"更多桶MoreBuckets"没列出前置模组"Cucumber Library";
3.(1.19.2)"动态的树：夸克附属DynamicTreesQuark"没列出前置模组"动态的树/有活力的树Dynamic Trees"

### 重现步骤

1、主界面点击下载
2、点击Mod
3、点击搜索-名称
4、输入模组名
5、点击搜索
6、找到搜索结果下同名模组并点击
7、打开"1.19.2"版本
8、1.19.2版本顶端没列出前置模组

### 日志与附件

![1](https://github.com/Hex-Dragon/PCL2/assets/158990547/d515f052-9fb5-47e7-bcae-78d4ec1263a2)
![2](https://github.com/Hex-Dragon/PCL2/assets/158990547/cd3d7ccc-9662-4b10-90e1-6892792b2aaf)
![3](https://github.com/Hex-Dragon/PCL2/assets/158990547/3f63de9e-6260-46f6-8e93-275b2131eb10)

**Comment by zkitefly** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/64117916/832e809a-359b-4ecb-8675-72157f588c02)

![image](https://github.com/Hex-Dragon/PCL2/assets/64117916/d5afd47d-9bb2-4ce8-bff8-0cb69c85e229)

**Comment by zkitefly** [comment]
可能需要上传日志？

**Comment by hejiehao** [comment]
我看看 API 返回来了什么

**Comment by rumengchuxing062** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/110439412/5bc8efec-a5e8-4a79-8e2e-760f4111361e)
![image](https://github.com/Hex-Dragon/PCL2/assets/110439412/c5097215-760e-4398-a642-c4fa7f219765)
![image](https://github.com/Hex-Dragon/PCL2/assets/110439412/5aaa8521-fd46-478c-9d6a-4989af0fbae7)
与PCLwu无关，是作者没有设置Mod关系

**Comment by rumengchuxing062** [comment]
我这边测试下，如果是有依赖没设置，我会跟Mod作者联系处理

**Comment by hejiehao** [comment]
这是 API 返回来的结果
[Dynamic Trees.json](https://github.com/Hex-Dragon/PCL2/files/14161949/Dynamic.Trees.json)
[Sophisticated Storage.json](https://github.com/Hex-Dragon/PCL2/files/14161950/Sophisticated.Storage.json)
[More Bukkets.json](https://github.com/Hex-Dragon/PCL2/files/14161951/More.Bukkets.json)

**Comment by rumengchuxing062** [comment]
已确认精妙存储缺少依赖设置，正在跟Mod作者联系

**Comment by hejiehao** [comment]
但是 Dynamic Trees 是 [Dynamic Trees](https://modrinth.com/mod/dynamictrees) 还是 [Dynamic Trees - Quark](https://modrinth.com/mod/dynamic-trees-quark) 呢？

**Comment by allMagicNB** [comment]
所以是作者上传的信息问题，打第三方加忽略，完活

**Comment by hejiehao** [comment]
> 所以是作者上传的信息问题，打第三方加忽略，完活

More Bukkets 不是

**Comment by rumengchuxing062** [comment]
> > 所以是作者上传的信息问题，打第三方加忽略，完活
> 
> More Bukkets 不是

这个是他网络问题

**Comment by hejiehao** [comment]
> > > 所以是作者上传的信息问题，打第三方加忽略，完活
> > 
> > 
> > More Bukkets 不是
> 
> 这个是他网络问题

这个还是得等日志才能确认

**Comment by zkitefly** [comment]
> > > 所以是作者上传的信息问题，打第三方加忽略，完活
> > 
> > 
> > More Bukkets 不是
> 
> 这个是他网络问题

应该不是，如果是，那这个列表它就显示不出了

**Comment by rumengchuxing062** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/110439412/a5e1918f-13e1-4fd9-85d5-7a3e14d3b3da)
已经和精妙存储的作者反馈了这个问题

**Comment by LTCatt** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/32b460cf-54b9-4c8b-9d49-7639488f84d7)
我这有显示前置啊？

**Comment by rumengchuxing062** [comment]
第一个有，第二个1.19.2以上的版本Mod作者忘记在CurseForge上设置前置依赖了，modrinth也没有这个Mod，第三个1.19.2没有前置
我已经在Mod的GitHub存储库发了个Issue跟作者反馈了这个问题

**Comment by LTCatt** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/7f67eab7-1d0f-4901-9311-2afd10b24b02)
最后一个作者设置的是 Optional Dependency，是可选的，所以 PCL 没有显示
综上所有三个 mod 的显示都没有问题，关了 =。=

**Comment by rumengchuxing062** [comment]
@TzAAnvil 精妙存储无法显示前置Mod的问题，Mod 开发者已经在 CurseForge 添加前置Mod信息，现在PCL上已经可以检索到前置信息了

**Comment by hejiehao** [comment]
API 更新没？
