### ISSUE TITLE
在从本地文件中切到预设会多弹一次报错

### ISSUE THREAD

**Issue by ghost** [Hex-Dragon/PCL2#3270]
### 检查项

- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在从本地文件中切到预设会多弹一次报错

建议选定之后不要再加载本地文件了......

### 重现步骤

点击设置-个性化-使用本地文件
转到启动界面报错后，再按上面的方法切到预设，随便选一个
再切到启动页面，会弹一次报错，之后就不会出现这个问题

### 日志与附件

![image](https://github.com/Hex-Dragon/PCL2/assets/110439412/1fe15580-0877-4a1b-bfc0-8b7803f8ce9f)
![image](https://github.com/Hex-Dragon/PCL2/assets/110439412/14ac9045-4ce2-47ec-a817-39c0bbb39ab0)
![image](https://github.com/Hex-Dragon/PCL2/assets/110439412/6bf6ffa4-afb0-44d7-a27a-a4f4ca4cd4c7)
![image](https://github.com/Hex-Dragon/PCL2/assets/110439412/e68f9361-0048-472b-958b-8d324ced1e84)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14161599/Log1.txt)

**Comment by allMagicNB** [comment]
龙猫：这个在#3266 修复的时候会一起修的

**Comment by SALTWOOD** [comment]
而且都不影响接下来使用，可以关了（？

**Comment by rumengchuxing062** [comment]
> 龙猫：这个在#3266 修复的时候会一起修的

我若不指定info，阁下该如何应对

**Comment by rumengchuxing062** [comment]
> 而且都不影响接下来使用，可以关了（？

但总归是个Bug

**Comment by rumengchuxing062** [comment]
@SALTWOOD 这么有闲情啊，那你去把 #3268 关了吧

**Comment by allMagicNB** [comment]
> @SALTWOOD 这么有闲情啊，那你去把 #3268 关了吧

贡献者关不了

**Comment by rumengchuxing062** [comment]
那谁去喊下youzi-2333关了它。。。

**Comment by SALTWOOD** [comment]
> @SALTWOOD 这么有闲情啊，那你去把 #3268 关了吧

我又不是Collaborator，我只是一个Contributor

**Comment by SALTWOOD** [comment]
> > 而且都不影响接下来使用，可以关了（？
> 
> 但总归是个Bug

那确实是，如果真的不是重复放着也不错（我在说什么）

**Comment by SALTWOOD** [comment]
干脆来个collab先打上待处理？

**Comment by zkitefly** [comment]
> 干脆来个collab先打上待处理？

已经关了

还有，不要版聊
