### ISSUE TITLE
建议在没有前置信息时加个提示，该版本在CurseForge没有前置Mod信息，对于可选前置，可以在Mod前置列表上显示可选

### ISSUE THREAD

**Issue by rumengchuxing062** [Hex-Dragon/PCL2#3271]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

建议在没有前置信息时加个提示，该版本在CurseForge没有前置Mod信息，对于可选前置，可以在Mod前置列表上显示可选

### 原因

我没记错的话，我已经连续两次看到PCL没有显示前置依赖的Issue了

**Comment by allMagicNB** [comment]
那你说我限定只显示CurseForge的模组然后挨个点进去会怎么样？

**Comment by rumengchuxing062** [comment]
> 那你说我限定只显示CurseForge的模组然后挨个点进去会怎么样？

只显示又不是只请求，而且你是搜索Mod的结果只显示CurseForge，又没说前置一定得是CurseForge

**Comment by allMagicNB** [comment]
~~反正你这个描述就很迷~~

**Comment by rumengchuxing062** [comment]
> ~反正你这个描述就很迷，普通模组没有前置的也要显示？~

直接全扫过去，全部版本都没有前置就不显示，有就显示，我不信有作者会不负责任到全版本有前置却都不设置前置依赖信息

**Comment by allMagicNB** [comment]
> 没必要，而且不好看（

嘴上这么说，身体加个待处理（

**Comment by rumengchuxing062** [comment]
> 没必要，而且不好看（


~你只需要负责过就行，UI怎么设计让猫来搞~

**Comment by LTCatt** [comment]
没啥必要……
