### ISSUE TITLE
Mod 搜索界面快速连续点击刷新会导致CPU短暂高占用和PCL卡死

### ISSUE THREAD

**Issue by rumengchuxing062** [Hex-Dragon/PCL2#3272]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

PCL卡死，CPU高占
建议加刷新限制，比如限制在没加载完成前禁止刷新，对API有好处
~对你的计算机也有好处~

### 重现步骤

1.点击下载
2.选择Mod
3.这次不需要任何字符，快速连续点击刷新，然后看到CPU占用快速走高，PCL无响应卡死

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14162663/Log1.txt)
~高达3M的日志~

**Comment by rumengchuxing062** [comment]
实测只有 Mod 列表可以，其他都不行

**Comment by hejiehao** [comment]
话说回来 PCL2 的 CurseForge API Key 用的是龙猫自己生成的还是 CurseForge App 的？

**Comment by allMagicNB** [comment]
> 话说回来 PCL2 的 CurseForge API Key 用的是龙猫自己生成的还是 CurseForge App 的？

日志或者抓包看看？

**Comment by SuoHouDaiShi** [comment]
复现成功
![图片](https://github.com/Hex-Dragon/PCL2/assets/119282947/ac6b54f3-4ee9-43ba-b4f4-66edcd2e602c)
<del>这应该算是刻意触发？而且我用的是连点器点击才能复现成功的……</del>
<del>看了一下你日志，这么多盘符，快说，是不是存了 10TB 的学习资料</del>

**Comment by hejiehao** [comment]
日志应该不会写这种比较敏感的信息

**Comment by allMagicNB** [comment]
> 日志应该不会写这种比较敏感的信息

那就抓包？

**Comment by hejiehao** [comment]
Modrinth 有 Ratelimits

**Comment by allMagicNB** [comment]
> > > 日志应该不会写这种比较敏感的信息
> > 
> > 那就抓包？
> 
> 这玩应应该加密了吧

翻源码？

**Comment by zkitefly** [comment]
这是故意找茬吗？

**Comment by hejiehao** [comment]
> 这是故意找茬吗？

~~不知道是不是为了活力橙~~

**Comment by allMagicNB** [comment]
> > 这是故意找茬吗？
> 
> ~~不知道是不是为了活力橙~~

Author拿过了

**Comment by rumengchuxing062** [comment]
> <del>这应该算是刻意触发？而且我用的是连点器点击才能复现成功的……</del>
> <del>看了一下你日志，这么多盘符，快说，是不是存了 10TB 的学习资料</del>
> 

都是Python代码
～给你看你能不能看懂还是问题～

事实上没什么，我也不知道，我只知道这块机械硬盘装上去就这么多分区，我平常用硬盘就三个可能性，看issue要下日志，写代码，玩游戏

**Comment by rumengchuxing062** [comment]
用连点器说明你太逊了，我都是用鼠标点出来的

**Comment by zkitefly** [comment]
不要版聊（

**Comment by rumengchuxing062** [comment]
> > 这是故意找茬吗？
> 
> ~~不知道是不是为了活力橙~~

是为了拿个协作者权限

**Comment by rumengchuxing062** [comment]
> 这是故意找茬吗？

不找茬何以发现bug，如果每个人都按开发者的思路来，那么自从几个版本前就不会有bug了

**Comment by LTCatt** [comment]
刻意触发的 Bug 不处理
