### ISSUE TITLE
Minecraft 1.20.4+Fabric LittleSkin登录 无法进入存档

### ISSUE THREAD

**Issue by CreatingCat** [Hex-Dragon/PCL2#3273]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃基本不是 PCL 的原因，请 **不要** 提交反馈。你可以在论坛或社区找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用 HMCL 启动，HMCL 没有出现问题。** 如果 HMCL 也无法启动就不是 PCL 导致的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

LittleSkin登录，MC启动正常，无任何模组，存档加载完后游戏崩溃闪退，无任何模组，Fabric 0.15.5~0.15.6皆是如此。

### PCL 错误报告、日志与附件

[错误报告-2024-2-5_周一_19.40.06.zip](https://github.com/Hex-Dragon/PCL2/files/14165136/-2024-2-5_._19.40.06.zip)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14165139/Log1.txt)

### HMCL 启动脚本

[HCML.txt](https://github.com/Hex-Dragon/PCL2/files/14165226/HCML.txt)
请改为ps1格式(HCML无法导出为bat格式)

**Comment by allMagicNB** [comment]
请问Minecraft出120版本了？

**Comment by allMagicNB** [comment]
资源包？[1.18.1]MASA全家桶汉化包.zip

**Comment by CreatingCat** [comment]
> 资源包？[1.18.1]MASA全家桶汉化包.zip

不是，我试过把全部资源包都卸了还是一样。

**Comment by allMagicNB** [comment]
> > 资源包？[1.18.1]MASA全家桶汉化包.zip
> 
> 不是，我试过把全部资源包都卸了还是一样。

但是日志里还是有，你找找？

**Comment by CreatingCat** [comment]
> > > 资源包？[1.18.1]MASA全家桶汉化包.zip
> > 
> > 
> > 不是，我试过把全部资源包都卸了还是一样。
> 
> 但是日志里还是有，你找找？

一样的

**Comment by zkitefly** [comment]
```
java.lang.NoSuchMethodError: 'java.lang.String com.mojang.authlib.properties.Property.getValue()'
```

Authlib-injector 的问题，与 PCL 无关

**Comment by allMagicNB** [comment]
加第三方啊

**Comment by allMagicNB** [comment]
加第三方啊@zkitefly
