### ISSUE TITLE
当没有播放设备时音乐播放器报错

### ISSUE THREAD

**Issue by JJJJGGGG1** [Hex-Dragon/PCL2#3277]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

开始播放时左下角刷屏 播放音乐失败 （歌名.mp3） : BadDeciceld calling waveOutOpen
稍等一会弹出错误框
![image](https://github.com/Hex-Dragon/PCL2/assets/120172412/1104a542-a793-44ac-b2cc-bb039cc9da97)

### 重现步骤

1、将所有播放设备禁用或拔出
2、确认右下角声音图标显示红色×
3、打开PCL2
4、播放音乐

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14176954/Log1.txt)

**Comment by JJJJGGGG1** [comment]
BadDeciceld calling waveOutOpen和NoDriver calling waveOutRestart是一样的吗（

**Comment by allMagicNB** [comment]
反正这是NAudio的Bug，要让别人修（

**Comment by allMagicNB** [comment]
不对啊，这个没有重复，可以考虑加第三方进#1930

**Comment by SALTWOOD** [comment]
> 不对啊，这个没有重复，可以考虑加第三方进#1930

报错结果一致，只是复现步骤不同
没有设备播放，网易云也报错，个人偏向刻意触发的样子

**Comment by WorldHim** [comment]
可以优化一下显示信息？
毕竟像线扯掉了，无线耳机没电了都是很正常的事情

**Comment by JJJJGGGG1** [comment]
没法通过除连接耳机之外的方法关掉这个报错，暂停、刷新都没用，一直刷屏很烦人的

**Comment by WorldHim** [comment]
> 没法通过除连接耳机之外的方法关掉这个报错，暂停、刷新都没用，一直刷屏很烦人的

那我还是重开 issue 吧

**Comment by zkitefly** [comment]
> 复现了一下，发现了新报错，但是截图的时候PCL2闪退了

可以上传日志，可能日志记录了

**Comment by JJJJGGGG1** [comment]
重试了几次截到了
![image](https://github.com/Hex-Dragon/PCL2/assets/120172412/e7593597-f616-48be-94d9-7fedbd6295ab)

**Comment by JJJJGGGG1** [comment]
日志可能有帮助，自己查看了是日志突然中断，没有退出的记录
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14221518/Log1.txt)

**Comment by ZS2147483647** [comment]
没有音乐播放设备怎么着也不可能播放成功吧

**Comment by WForst-Breeze** [comment]
@LTCatt 这里有个待处理
