### ISSUE TITLE
清理游戏垃圾弹出窗口叙述问题

### ISSUE THREAD

**Issue by WForst-Breeze** [Hex-Dragon/PCL2#3283]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如图，我并没有修改缓存文件夹，但当去清理游戏垃圾时仍会显示“你已将缓存文件夹**手动修改为**xxxx”

![image](https://github.com/Hex-Dragon/PCL2/assets/110760354/0ffa87b9-6815-4214-b591-22b4b6dd24c9)
![image](https://github.com/Hex-Dragon/PCL2/assets/110760354/39c8bf8e-9b72-4c14-a680-67e70c558af5)

此处叙述易使一些不太明白的萌新不敢继续进行操作，因为它们可能不知道这个路径到底是什么含义，就算知道也会下意识去检查自己的启动器系统设置，最后一头雾水。

### 重现步骤

百宝箱 - 清理游戏垃圾

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14193018/Log1.txt)

**Comment by allMagicNB** [comment]
感觉可以分为一个显示Bug和一个优化建议……

**Comment by allMagicNB** [comment]
《可能是崩溃™启动器2》

**Comment by LTCatt** [comment]
在 2.4.1 加了点日志输出，请等待 2.4.1 更新后，使用该版本复现，然后上传日志

**Comment by allMagicNB** [comment]
> 在 2.4.1 加了点日志输出，请等待 2.4.1 更新后，使用该版本复现，然后上传日志

2.4.1？返祖回到刚有联机但马上又没了的版本？
![网页捕获_20-2-2024_22132_afdian net](https://github.com/Hex-Dragon/PCL2/assets/116283787/d41d71f4-4738-4085-af2c-76553a49e356)

**Comment by LTCatt** [comment]
写错了，2.6.14

**Comment by wuliaodexiaoluo** [comment]
![图片](https://github.com/Hex-Dragon/PCL2/assets/160083863/dd55f1eb-595a-4510-a23e-9315ccda7c86)
```
[17:58:43.600] [Start] 程序版本：Snapshot 2.6.14（314）
...
[17:58:54.886] [Test] 当前缓存文件夹：C:\Users\Menhe\AppData\Local\Temp\PCL\，默认缓存文件夹：C:\Users\Menhe\AppData\Local\Temp\PCL\
[17:58:54.920] [Control] 普通弹窗：清理确认
即将清理游戏日志、错误报告、缓存等文件。

你已将缓存文件夹手动修改为：C:\Users\Menhe\AppData\Local\Temp\PCL\
清理过程中，将删除该文件夹中的所有内容，且无法恢复。请确认其中没有除了 PCL 缓存以外的重要文件！

在完成清理后，PCL 将自动重启。
[17:59:00.990] [Control] 按下按钮：确定
[17:59:00.993] [Control] 普通弹框返回：1
[17:59:01.390] [Control] 普通弹窗：缓存已清理
清理了 64 个文件！
PCL 即将自动重启……
[17:59:02.595] [Control] 按下按钮：确定
[17:59:02.595] [Control] 普通弹框返回：1
[17:59:03.041] [System] 程序已退出，返回值：Success
```
确实有，没改还能弹这个提示
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14383902/Log2.txt)
