### ISSUE TITLE
允许单独初始化高级启动选项设置

### ISSUE THREAD

**Issue by WForst-Breeze** [Hex-Dragon/PCL2#3284]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

目前的设置要想初始化就得把这个页面的所有设置一起初始化，希望可以允许单独初始化高级启动选项设置（即 JVM 参数设置）。

### 原因

尽管有提示，但依旧防不住有时候 JVM 参数改炸了不好改回来。一用左边选项卡的初始化整个页面的设置都得重新做，有些繁琐。

其他的设置内容不必有单独的初始化选项，毕竟其他内容都比较好改。🤔

**Comment by allMagicNB** [comment]
感觉可以，专门针对小白乱搞的结果（

**Comment by LTCatt** [comment]
为 JVM 参数头添加了单独的重置按钮
