### ISSUE TITLE
我在PCL2里下载Mods / Minecraft的时候遇到了问题：以一种访问权限不允许的方式做了一个访问套接字的尝试。

### ISSUE THREAD

**Issue by HuanMeng6** [Hex-Dragon/PCL2#3285]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在我的（本人的）电脑上，打开PCL2的最新测试版本是，点 [下载] 时。会出现如标题所述的情况，点反馈是还会提醒：“你的PCL不是最新版，因此无法提交反馈。”其实已经是最新版本了（Snapshot2.6.8）。

### 重现步骤

1、点击下载就会看到如上画面
2、找到 [设置] [活跃橙] 右键也会看到如上画面。

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14193533/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14193537/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14193539/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14193542/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14193549/Log2.txt)

**Comment by allMagicNB** [comment]
你确定是最新版本？

**Comment by HuanMeng6** [comment]
是的

**Comment by allMagicNB** [comment]
> 是的

现在的最新版本是2.6.13

**Comment by HuanMeng6** [comment]
是测试版本

**Comment by allMagicNB** [comment]
> 是测试版本

你快照版自己都没更新，最新是`2.6.13`

**Comment by allMagicNB** [comment]
关了关了
~~自以为是的Author~~

**Comment by HuanMeng6** [comment]
我在检查更新是输入了龙猫的更新密钥，然后到4.15%后就更新不了了

**Comment by allMagicNB** [comment]
> 我在检查更新是输入了龙猫的更新密钥，然后到4.15%后就更新不了了

个人网络原因

**Comment by HuanMeng6** [comment]
换了网络也不行，我家就两个网（一个5G网，一个普通网络）

**Comment by Pigeon0v0** [comment]
自己系统 / 网络问题

**Comment by allMagicNB** [comment]
停停停，这不该是Issue里讨论的问题了
你要讨论就去开Discussion

**Comment by allMagicNB** [comment]
停停停，这不该是Issue里讨论的问题了
你要讨论就去开Diacussion
