### ISSUE TITLE
允许直接在PCL内“永久”删除mod及版本文件（而非移入回收站

### ISSUE THREAD

**Issue by kong-que-dnf123** [Hex-Dragon/PCL2#3290]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

PCL删除mod及版本文件时
可在确认删除询问窗口时新增一条“永久删除”
点击后再次弹出 **红色窗口** “您确定要永久删除XX吗？这份文件将会离开您很久（真的很久！）”

### 原因

现在删除文件时都默认为 **“移动至回收站”** ~且无法更改~（如图）
![image](https://github.com/Hex-Dragon/PCL2/assets/120994373/f34d8ca6-c98a-4187-9510-7fac1e6eed9a)
然后我搞什么 _与好友简易联机啊_ 、 _对服务器客户端mod文件调整啊_ 、 _~版本bug复现测试啊~_ 等等等等
然后我回收站就一堆东西乐...（如图）
![image](https://github.com/Hex-Dragon/PCL2/assets/120994373/87df54fd-7640-4987-81ec-233a0b1a625d)
~会不会占太多空间没想过 但是真的不想处理去一点一点二次永删了（躺平）~

**Comment by JingHai-Lingyun** [comment]
按住 Shift 还是 Alt 还是 Ctrl 可以直接删没掉来着...

**Comment by allMagicNB** [comment]
可以考虑`Shift+删除按钮`来永久删除，并且加个提示（
