### ISSUE TITLE
正版皮肤不显示

### ISSUE THREAD

**Issue by MengLWither** [Hex-Dragon/PCL2#3298]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

皮肤头像没有显示，刷新还弹出了“皮肤文件已损坏”的消息

![9914975e8adad13e75b0af73b0b0ac11](https://github.com/Hex-Dragon/PCL2/assets/159559171/3b62c92b-93c2-4df1-9c79-8fca00b8cea8)

### 重现步骤

点击“刷新头像”

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14223538/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14223540/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14223541/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14223542/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14223543/Log1.txt)

**Comment by MengLWither** [comment]
自己的皮肤和其他玩家的皮肤也都是不显示的

**Comment by JingHai-Lingyun** [comment]
```
[23:07:25.962] 加载位图失败（C:\Users\Withe\AppData\Local\Temp\PCL\Cache\Skin\3773685741233406709.png）：参数无效。
   在 System.Drawing.Bitmap..ctor(Stream stream)
   在 PCL.MyBitmap..ctor(String FilePathOrResourceName)
错误类型：System.ArgumentException
[23:07:25.964] 皮肤文件已损坏：C:\Users\Withe\AppData\Local\Temp\PCL\Cache\Skin\3773685741233406709.png：参数无效。
   在 System.Drawing.Bitmap..ctor(Stream stream)
   在 PCL.MyBitmap..ctor(String FilePathOrResourceName)
   在 PCL.MySkin.Load()
错误类型：System.ArgumentException
```

嘶.... 这个日志看起来和 #3115 好像啊，只是出现在不同的地方
这报错 D 群里看到好多了
