### ISSUE TITLE
允许强制使用java19

### ISSUE THREAD

**Issue by 2293369701** [Hex-Dragon/PCL2#330]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我用刚更新的启动器使用java19启动游戏，它显示没有找到java17，但java19是可以运行游戏的，后来我在设置里要求使用java19，但还是说未找到java17，怎么设置它都不用java19启动游戏，被迫下载了java17

### 重现步骤

1、下载java19
2、卸载java17
3、启动游戏

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/9945001/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/9945002/Log2.txt)

**Comment by SorrowRain** [comment]
由于JDK19启动高版本mc仍可能出现游戏崩溃等问题，PCL2 2.4.1版本会在此时自动选择JDK17-18，**且始终不会选择JDK19（即使你的电脑里只有JDK19可用）**
如果希望使用JDK19启动游戏，你可以在**设置-游戏-游戏Java**选项中手动选择**JDK19**，此时PCL2会自动使用JDK19启动游戏。
由于JDK19兼容性较差，我们还是推荐使用JDK17启动游戏。

**Comment by 2293369701** [comment]
> 由于JDK19启动高版本mc仍可能出现游戏崩溃等问题，PCL2 2.4.1版本会在此时自动选择JDK17-18，且始终不会选择JDK19**（即使你的电脑里只有**JDK19可用）如果希望使用JDK19启动游戏，你可以在“设置-游戏**-游戏Java**”选项中手动选择JDK19，此时PCL2会自动使用**JDK19**启动游戏。由于JDK19兼容性较差，我们还是推荐使用JDK17启动游戏。

当电脑里只有java19时，选择java19还是会要求下载java17，无法启动，还是希望能修复该问题

**Comment by SorrowRain** [comment]
> > 由于JDK19启动高版本mc仍可能出现游戏崩溃等问题，PCL2 2.4.1版本会在此时自动选择JDK17-18，且始终不会选择JDK19**（即使你的电脑里只有**JDK19可用）如果希望使用JDK19启动游戏，你可以在“设置-游戏**-游戏Java**”选项中手动选择JDK19，此时PCL2会自动使用**JDK19**启动游戏。由于JDK19兼容性较差，我们还是推荐使用JDK17启动游戏。
> 
> 当电脑里只有java19时，选择java19还是会要求下载java17，无法启动，还是希望能修复该问题

草，我复现的时候忘记刷新PCL2的java缓存了，见鬼

这边复现成功了，已确认bug存在并加入待处理列表，麻烦啦——

**Comment by LTCatt** [comment]
PCL2 没有找到 Java 19，尝试手动添加进去？

**Comment by 2293369701** [comment]
> PCL2 没有找到 Java 19，尝试手动添加进去？
> 
> 此外，1.18+ Forge+OptiFine 或 Fabric 最高只兼容到 Java 18。

我不是这个意思，我是说在电脑里只有java19时，找到并选择java19后启动游戏会要求下载java17而不启动游戏，必须下载java17后才能强制使用java19启动，可是就是没有安装java17我才用java19，不然直接使用java17就行了，希望改为在设置中选择java19后不再要求下载java17

**Comment by 2293369701** [comment]
lssue
