### ISSUE TITLE
安装洞口填充器之后崩溃

### ISSUE THREAD

**Issue by RainbowTaro2022** [Hex-Dragon/PCL2#3305]
### 检查项

- [ ] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃基本不是 PCL 的原因，请 **不要** 提交反馈。你可以在论坛或社区找人求助，但这里并不是你求助的地方。
- [ ] **我已尝试使用 HMCL 启动，HMCL 没有出现问题。** 如果 HMCL 也无法启动就不是 PCL 导致的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我安装了洞口填充器之后就崩溃了

### PCL 错误报告、日志与附件

[错误报告-2024-2-11_6.13.47.zip](https://github.com/Hex-Dragon/PCL2/files/14230676/-2024-2-11_6.13.47.zip)

**Comment by allMagicNB** [comment]
请尝试使用HMCL启动

**Comment by hejiehao** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/98140773/e4acad1b-457d-44dc-935e-54dc0334d5b2)

**Comment by burningtnt** [comment]
Hole Filler Mod 与您的 Forge 版本不兼容，这不是 PCL2 的问题

如有更多问题，可以来 _______ 求助

**Comment by allMagicNB** [comment]
> Hole Filler Mod 与您的 Forge 版本不兼容，这不是 PCL2 的问题
> 
> 如有更多问题，可以来 _______ 求助

HMCL KOOK频道（

**Comment by hejiehao** [comment]
内啥，为什么一开始不关了它？

**Comment by allMagicNB** [comment]
> 内啥，为什么一开始不关了它？

那个选项也不是必选啊（

**Comment by WForst-Breeze** [comment]
>  我已尝试使用 HMCL 启动，HMCL 没有出现问题。 

此选项为必选

```
Failure message: Hole Filler Mod (hole_filler_mod) has failed to load correctly
```

非 PCL 问题，感谢反馈

**Comment by allMagicNB** [comment]
~~还是自作聪明大佬~~
