### ISSUE TITLE
检测不到某.minecraft文件夹时不直接将其移除

### ISSUE THREAD

**Issue by wowsunlei** [Hex-Dragon/PCL2#3307]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在版本选择界面添加.minecraft文件夹后，如果某时检测不到，只是提示而非自动移除

### 原因

我在U盘中装有mc，并将.minecraft文件夹添加到PCL中。但如果有时没有插入U盘，这个.minecraft文件夹会在PCL版本选择界面被移除，此后再次需要使用时还得再次添加，不太方便。

**Comment by MCSteve123** [comment]
为啥要在U盘里啊（读取又慢还发烫

**Comment by SALTWOOD** [comment]
建议改为：**[优化] 当自定义版本文件夹不可用时不将其移除**

**Comment by LTCatt** [comment]
不太好改。
如果保留并且显示在文件夹列表，那需要单独为文件夹列表做很多特判，让它不能被打开和枚举。
如果保留但不显示在文件夹列表，那这个错误项又没法删。
……还是算了吧……
