### ISSUE TITLE
建议登录失败时直接给出解决方案

### ISSUE THREAD

**Issue by ZS2147483647** [Hex-Dragon/PCL2#3308]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在提示后面加上:'如果你确定你的账号没问题,那么就是mojang服务器寄了,你需要到Microsoft Store下载Minecraft Launcher并登录你的账号之后再返回pcl重新登录'(最好能加一个快速通道前往官启)
可以考虑把两个网页链接去了因为用到的人少而且一般这时候mc官网是被禁止访问的(开蓝灯都上不去)
![814ff7048f84749e22530319aeb4dca](https://github.com/Hex-Dragon/PCL2/assets/121028009/b69a234c-3167-43c9-8b61-6e2a516d88af)

### 原因

出这种问题的人往往不是账号问题而是网络问题,这样可以更有利于用户发挥主观能动性自己解决问题

**Comment by allMagicNB** [comment]
6，丢人得光速关闭

**Comment by ZS2147483647** [comment]
突然发现改了我印象中还停留在之前的样子抱歉哈

**Comment by ZS2147483647** [comment]
> 6，丢人得光速关闭

没什么丢人的就是突然发现不对

**Comment by hejiehao** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/98140773/0a22eaf5-51e1-49fa-9d8d-8328fc8cc8a0)
纪念一下

**Comment by allMagicNB** [comment]
> ![image](https://github.com/Hex-Dragon/PCL2/assets/98140773/0a22eaf5-51e1-49fa-9d8d-8328fc8cc8a0)
> 纪念一下

~~你怎么那么爱鞭尸~~

**Comment by ZS2147483647** [comment]
哦吼吼吼吼吼吼

**Comment by ZS2147483647** [comment]
我申请对这条issue进行删除操作

**Comment by ZS2147483647** [comment]
纯属眼瞎没看见

**Comment by WForst-Breeze** [comment]
没关系的，下次注意就好
