### ISSUE TITLE
推荐用户使用 GraalVM Java

### ISSUE THREAD

**Issue by ajdgsu** [Hex-Dragon/PCL2#331]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

最近了解到一个性能更好的java衍生版本 GraalVM Java ，一言蔽之就是性能比原版java更好，内存使用更少。

介绍: https://zhuanlan.zhihu.com/p/106555993?utm_id=0

下载: https://github.com/graalvm/graalvm-ce-builds

### 原因

我知道这种东西不需要修改pcl2任何东西，就已经可以正常使用了。我的意思只是说可以在pcl2里提及这个java的衍生版本性能更好，推荐下载这个版本，不然我认为应该没几个人知道这玩意。

还有顺便提一句如果github直连下载慢的话可以用jsDelivr下载，具体可以自行搜索方法。

**Comment by SorrowRain** [comment]
对于大部分玩家而言，不同版本的Java兼容就已经够难理解的了，使用一个稳定且易于下载的Java就足够了。

如果在PCL2内推荐GraalVM Java，这玩家可能会陷入疑惑。

综上，PCL2暂时仍仅提供Oracle Java的下载入口，感谢反馈。
