### ISSUE TITLE
正版账号登录有问题

### ISSUE THREAD

**Issue by ikunfddssxs** [Hex-Dragon/PCL2#3314]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

有时候用离线账号玩游戏，玩完之后把启动器一关闭，正版账号无法游玩游戏，需要重新修改档案。还有一个bug，在你每次登录的时候，它都需要重新修改档案。

### 重现步骤

1、使用离线登录，在把启动器一关，正版登录就需要重新修改档案。
2、如果你用新电脑登录正版账号，那么就要重新修改档案了。

### 日志与附件

正版账号登录有问题，没有日志

**Comment by allMagicNB** [comment]
好歹传个截屏

**Comment by wuliaodexiaoluo** [comment]
测试未能复现

**Comment by allMagicNB** [comment]
@ikunfddssxs 请及时补全信息

**Comment by LTCatt** [comment]
这应当不是启动器的问题，如果你确认是启动器的问题，请补充日志
