### ISSUE TITLE
Java映像损坏

### ISSUE THREAD

**Issue by ZM-2000** [Hex-Dragon/PCL2#3315]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

当我将安装过OptiFine的1.20.4版本启动后,，出现Java映像损坏的报错，但是确认后游戏能正常启动
![11](https://github.com/Hex-Dragon/PCL2/assets/159763146/94def25a-aa21-4ed5-969d-a0aeb3bd22a4)

### 重现步骤

1、每次电脑开机后在PCL2主界面启动安装过OptiFine的1.20.4版本游戏时
2、会弹出以上报错弹窗
![11](https://github.com/Hex-Dragon/PCL2/assets/159763146/b0c2698a-773f-4894-a065-35cc462c5f38)

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14237383/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14237385/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14237387/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14237388/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14237390/Log5.txt)

**Comment by allMagicNB** [comment]
dll损坏，请删除`java-runtime-beta`文件夹后重新使用官启启动游戏，官启会自动重新安装
