### ISSUE TITLE
是否能够添加 HMCL 提供的 `从互联网下载整合包` 功能

### ISSUE THREAD

**Issue by RainyHallways** [Hex-Dragon/PCL2#3317]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

启动器将本地的客户端文件打包(用户选择打包内容)并生成一个汇总json
用户通过输入托管链接来获取客户端和其更新

### 原因

服主或者整合包作者等可能会需要此功能
并且同一协议(指上方描述)能够更好的跨应用使用

**Comment by deep-dark-forest** [comment]
意义不大，hmcl好像也支持直链，还不如用pcl2里面的自定义下载器下载完以后再导入

**Comment by allMagicNB** [comment]
意义不大，相当于自定义下载套个壳

**Comment by RainyHallways** [comment]
> 意义不大，hmcl的这个功能好像也只支持直链，还不如用pcl2里面的自定义下载器下载完以后再导入

和自定义下载不一样（
不然我也不会提这个Issue(

**Comment by RainyHallways** [comment]
和PCL内置的自动安装差不多，读取json来下载文件（

**Comment by deep-dark-forest** [comment]
那我误解了，抱歉

**Comment by zkitefly** [comment]
> 和PCL内置的自动安装差不多，读取json来下载文件（

直接下载一个整合包再自动安装不是更好？

**Comment by zkitefly** [comment]
我记得更新整合包功能被拒绝过？

先让龙猫看看（

**Comment by RainyHallways** [comment]
> > 和PCL内置的自动安装差不多，读取json来下载文件（
> 
> 直接下载一个整合包再自动安装不是更好？

这样可以多平台适用（
安卓的 FCL 和Windows的 HMCL PMCL 等启动器都能够同时支持。再者，单个整合包太大了(动不动就上G级)无论放云存储(单次下载量太大)还是网页托管(带宽)都是个难事（

**Comment by RainyHallways** [comment]
> 我记得更新整合包功能被拒绝过？
> 
> 先让龙猫看看（

这个功能和你想的更新整合包功能可能不同，具体查看下方链接（
https://docs.hmcl.net/modpack/serverpack.html

**Comment by RainyHallways** [comment]
这样可以直接给服务器玩家丢一个PCLⅡ启动器(Mb级)然后通过链接下载服务器客户端(G级)（

**Comment by zkitefly** [comment]
> > 我记得更新整合包功能被拒绝过？
> > 先让龙猫看看（
> 
> 这个功能和你想的更新整合包功能可能不同，具体查看下方链接（ https://docs.hmcl.net/modpack/serverpack.html

https://github.com/Hex-Dragon/PCL2/pull/1771

**Comment by RainyHallways** [comment]
> > > 我记得更新整合包功能被拒绝过？
> > > 先让龙猫看看（
> > 
> > 
> > 这个功能和你想的更新整合包功能可能不同，具体查看下方链接（ https://docs.hmcl.net/modpack/serverpack.html
> 
> #1771

上述`整合包`并不是MC BBS整合包（

**Comment by RainyHallways** [comment]
整体逻辑为通过链接先读取根目录下的.json文件，然后通过json文件内的path信息来下载overrides里面提供的文件并校验哈希(以此来进行后续的更新操作，就和PCL内的自动安装差不多)

**Comment by RainyHallways** [comment]
> 你猜 MCBBS 整合包更新是怎么实现的？

我的问题（

**Comment by Pigeon0v0** [comment]
相关 #1768
