### ISSUE TITLE
使用 urlscheme 快速下载文件

### ISSUE THREAD

**Issue by JingHai-Lingyun** [Hex-Dragon/PCL2#3318]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

PCL 是否能支持一个 urlscheme 来做到在网页上点击下载链接后自动使用 PCL 多线程下载器下载自定义链接

### 原因

我希望能通过此提议+浏览器插件实现自动化快速下载

**Comment by allMagicNB** [comment]
没必要，PCL2本质是启动器而不是下载器
