### ISSUE TITLE
模组及整合包搜索翻页按钮意外地呈现未激活颜色

### ISSUE THREAD

**Issue by WForst-Breeze** [Hex-Dragon/PCL2#3319]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如题如下图，正常情况应为图2，而错误的情况呈现的颜色为图1。本以为是翻页翻到头了，结果一点还能继续往下翻（

![image](https://github.com/Hex-Dragon/PCL2/assets/110760354/e4c673cc-2bac-440d-9484-f8f20c9d9d9f)

![image](https://github.com/Hex-Dragon/PCL2/assets/110760354/19191f59-3ac3-4df6-9257-cfb59eb4cddd)

### 重现步骤

于 Mod 或整合包搜索页面翻页即可

### 日志与附件
调试模式已开启
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14258123/Log1.txt)

上个日志太长了，补一个短的，翻到第 9 页问题复现：[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14258228/Log1.txt)

**Comment by LTCatt** [comment]
需要一个稳定的复现方法，我虽然也遇到过，但真开着 VS 复现的时候半天复现不出来……

**Comment by LBZiXL** [comment]
感觉一直翻页就很稳定，我翻到第21页出现此问题。
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15485982/Log1.txt)

又试了一次，结果第3页就复现了
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15486012/Log1.txt)

又又试了一次，这次第9页就复现了
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15486048/Log1.txt)

我发现只要翻页的时候没有出现`正在加载mod列表`动画，就会出现这个Bug。
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15486114/Log1.txt)

**Comment by LTCatt** [comment]
依然无法重现，并且在代码上也说不通。

这是唯一一处修改按钮样式的代码：
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/2f63b570-d2a2-4445-95e7-f34d04e2ee37)
它与 Page 变量的值相关，如果 Page > 1，那么两个按钮都应该显示。
但即使是楼上复现成功的 Log 中，这时候的 Page 也是 2，那就不应该出现问题。
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/26a1295c-e017-41aa-b712-23716fb952d4)

如果谁能研究清楚的话就能修了，或者丢个 PR，我搞不懂一点……

**Comment by allMagicNB** [comment]
？我刚又试了下，还是第三页，还是未激活……？

**Comment by allMagicNB** [comment]
似乎有时候翻页是瞬间加载完成的……可能按快点就能复现？

**Comment by allMagicNB** [comment]
试出来规律了，在点击下一页后返回顶部时快速下滑鼠标滚轮。

**Comment by allMagicNB** [comment]
@LTCatt

**Comment by LTCatt** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/9ec98ce0-f899-41f1-8cf8-b0c781c9e192)
![OHH3_(D@6S~2 {81E RLJUB](https://github.com/Hex-Dragon/PCL2/assets/40348278/dc216342-382c-4706-b6f0-35dff4bdd95c)

**Comment by LTCatt** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/a13be25d-4303-4e8e-9b99-c004cd763bf9)
我释怀的笑。
在完全不知道为什么的情况下，尝试设置 IsEnabled=True 时，它实际上被修改了，但获取却只能获取到 False。
不读取这个值硬改就修好了。

**Comment by JingHai-Lingyun** [comment]
实例更新不完全罢…… ~~年度最好玩 Bug 属于是~~

**Comment by Open-KFC** [comment]
>似乎有时候翻页是瞬间加载完成的……可能按快点就能复现？

会不会是下面那个翻页的逻辑里面会把它父控件的 IsEnabled 设成 False 然后 100ms 后再设置回 True ，然后上面这段代码跑的太快直接在它两次设置的中间执行关于子控件 IsEnabled 的逻辑了（
