### ISSUE TITLE
添加内置 NBT 查看器/编辑器

### ISSUE THREAD

**Issue by WForst-Breeze** [Hex-Dragon/PCL2#3321]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

如题，添加内置 NBT 查看器/编辑器（图：HMCL）
![image](https://github.com/Hex-Dragon/PCL2/assets/110760354/026541d4-4bdc-4caf-baa7-e1094b1210bb)

### 原因

*~部分有调试存档内容的玩家可能需要，尽管这可能超出了启动器的范畴。~*

事实是我估计隔壁出完这个功能后早晚会有人来交这个提案，所以就先交了得了，如果拒绝了就当留个档丢表格里了 (⌐■_■)，对大家的打扰十分抱歉！Orz

**Comment by allMagicNB** [comment]
PCL2的定位是小白化MC启动器……
不对啊，直接让有需求的去用HMCL不得了（

**Comment by zkitefly** [comment]
其实这个功能没必要，在 Glavo 出完该功能后，我问怎么不加个按钮，他说：

> 没有适合的地方放，本身也没希望让所有人都知道，当一个隐藏的高级功能就行了。

**Comment by WForst-Breeze** [comment]
> 其实这个功能没必要。
> 
> 在 Glavo 出完该功能后，我问怎么不加个按钮，他说：
> 
> > 没有适合的地方放，本身也没希望让所有人都知道，当一个隐藏的高级功能就行了。 [HMCL-dev/HMCL#2689](https://github.com/HMCL-dev/HMCL/issues/2689)
> 
> ~或许我应该把更新日志的如何使用的那段话删掉？~

赞成，这个功能感觉能用到的时候很少，制作这个功能的付出和回报差异太大

**Comment by LTCatt** [comment]
不考虑（
