### ISSUE TITLE
MyTextButton 比 TextBlock 的文字要高两像素

### ISSUE THREAD

**Issue by Light-Beacon** [Hex-Dragon/PCL2#3324]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如题

![image](https://github.com/Hex-Dragon/PCL2/assets/49828867/9550b23f-67b2-44f4-89e9-f7b47cef9b2b)

### 重现步骤

测试用主页代码：
```xaml
<local:MyCard>
  <StackPanel Margin="25,20">
    <TextBlock> 普通文本 <local:MyTextButton Text="文本按钮"
        EventType="刷新主页"/> 普通文本 </TextBlock>
  </StackPanel>
</local:MyCard>
```

### 日志与附件

*无需提供*

**Comment by LTCatt** [comment]
这个还是自行调整吧 orz
