### ISSUE TITLE
换硬盘后游戏初次运行后消失了

### ISSUE THREAD

**Issue by NOIZ02** [Hex-Dragon/PCL2#3325]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

电脑换了新硬盘，把旧硬盘的pcl2.exe及数据和存档文件迁移到新盘了
初次打开exe时没有任何问题，关闭后发现.exe文件消失了
同时.minecraft文件夹里的所有游戏版本一并消失
正版登录的账号和解锁的全部主题什么的也没了
再次从爱发电下载了一次游戏之后直接把旧盘里的数据和游戏存档塞进去
打开倒是有游戏版本了，进了版本选择界面发现又没东西了
*主要是心疼解锁的全主题

### 重现步骤

1、点击pcl2.exe
2、点击版本选择（可能直接显示文件被迁移然后.exe文件消失）
3、显示无可用版本后关闭游戏
4、打开.minecraft文件夹发现下载的所有游戏版本全部消失

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14269944/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14269947/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14269948/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14269949/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14269950/Log5.txt)

**Comment by Light-Beacon** [comment]
被误报毒了吧，放进杀软信任区看看

**Comment by Ad-closeNN** [comment]
> 被误报毒了吧，心动杀软信任区看看
> 
> > 对于Microsoft Defender和360等杀毒软件误报，请在Windows安全中心和杀毒软件中添加修复项或白名单，具体教程见PCL内置帮助库。

这也会一并带走`.minecraft`文件夹的吗
~~还有~~`心动`~~是什么, 应该是~~`先到`~~吧~~

**Comment by allMagicNB** [comment]
应该是搬迁的时候没有搬`.minecraft`文件夹……
