### ISSUE TITLE
尝试安装与当前选择版本加载器不同的  mod 时弹出警告提示框而不是自动切换版本

### ISSUE THREAD

**Issue by xxtg666** [Hex-Dragon/PCL2#3328]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

~~如题，在 Forge 客户端安装了 Sinytra Connector 后，如果尝试下载安装 fabric mod 时应该不自动切换到其他版本~~
请查看下方 comments

### 原因

选中一个 Forge 客户端后在下载 mod 界面搜索一个 fabric mod 第一次点击下载时会自动切到安装了 Fabric 的版本，没看清容易安装错

**Comment by deep-dark-forest** [comment]
那pcl怎么识别是否安装了这个模组？

**Comment by xxtg666** [comment]
可以根据文件名识别？或者手动标记

**Comment by WForst-Breeze** [comment]
此内容为 mod 行为，类似内容参见 #1536

**Comment by xxtg666** [comment]
是的，我提出这个issue也是因为今天在给整合包加mod的时候加完启动游戏发现没有装上，才想起来PCL自动切到别的版本下载了

**Comment by deep-dark-forest** [comment]
那我觉得这个模组的一些事情可以写入帮助文档

**Comment by JingHai-Lingyun** [comment]
> PCL 无法检测具体安装了哪些 Mod，所以 Mod 带来的行为改变不会被支持 Orz —— LTCatt 于 #1536 

我的看法是 PCL 很大概率不会支持 Sinytra Connector（信雅互联）所带来的 Forge-Fabric 串通
这种客户端本质上还是 Forge 客户端

**Comment by xxtg666** [comment]
我有一个想法，在选中 Forge 客户端后尝试下载 Fabric mod （其他加载器同理）时，弹出一个不兼容警告的提示框，给两个选项“我知道我在做什么”和“切换版本”。原来自动切换版本的设计提示有点不明显，容易没看见

**Comment by LTCatt** [comment]
> 选中一个 Forge 客户端后在下载 mod 界面搜索一个 fabric mod 第一次点击下载时会自动切到安装了 Fabric 的版本

理论上不会，除非没有任何适宜的版本

**Comment by xxtg666** [comment]
请看录屏

https://github.com/Hex-Dragon/PCL2/assets/68174188/f95eac7d-a472-4fb1-8fa2-b467bcd5fc9c

**Comment by burningtnt** [comment]
我盲猜一下，这个地方的选中文件夹没有设定目标，是自动让 Windows 选中上一次打开的地方的

**Comment by xxtg666** [comment]
> 我盲猜一下，这个地方的选中文件夹没有设定目标，是自动让 Windows 选中上一次打开的地方的

在上面的测试中，当我尝试下载该 mod 的 forge 版本时，会自动切换到安装了 Forge 的游戏版本的 mod 文件夹（这没必要录屏了不信的自己去试试）

**Comment by LTCatt** [comment]
这是以 “你选择的是哪个版本的 Mod” 优先，而非 “你选择的是哪个 MC 版本” 优先，WAI

**Comment by xxtg666** [comment]
那这个东西就不能加个配置项吗…

**Comment by gezinfly** [comment]
https://github.com/Hex-Dragon/PCL2/issues/4418#issue-2449763944
https://github.com/Hex-Dragon/PCL2/issues/4418#issuecomment-2270218140
草草草，关闭了的也能回复吗……我见识少了（悲）

> 感觉可以做成一个设置选项，即设置是否下载 mod 时自动选择合适的版本文件夹

我也希望加一个配置项，并且给出了具体想法。

另外
> 我似乎看懂了…… 其实整体还是信雅互联的问题，

我不同意这个观点
因为当我没看清楚版本，尝试将1.20.4的mod安装至1.21的MC时，被几乎无感静默跳转至别的版本，结果出现了严重问题，我排查了半天。这不仅是连接器，同一个加载器的不同版本间也会出现跳转。这种“野mod”流窜到别的版本的隐患十分危险。

所以我建议加强提示并给出一个可以关闭该功能的配置项。

**Comment by gezinfly** [comment]
> 这是以 “你选择的是哪个版本的 Mod” 优先，而非 “你选择的是哪个 MC 版本” 优先，WAI

我理解这种优先级设置，但是这不能消除
>因为当我没看清楚版本，尝试将1.20.4的mod安装至1.21的MC时，被几乎无感静默跳转至别的版本，结果出现了严重问题，我排查了半天。这不仅是连接器，同一个加载器的不同版本间也会出现跳转。这种“野mod”流窜到别的版本的隐患十分危险。

的隐患

**Comment by gezinfly** [comment]
所以我要回在一个被忽略的地方，然后等着被继续忽略吗？这太怪了

**Comment by JingHai-Lingyun** [comment]
@LTCatt 再看看？

**Comment by xxtg666** [comment]
~~半年前的issue竟然又活了~~

**Comment by wuyuncheng-26** [comment]
个人感觉 PCL 不会专门兼容信雅互联……

**Comment by gezinfly** [comment]
> 个人感觉 PCL 不会专门兼容信雅互联……

我也觉得，毕竟这种mod检测起来有难度，而且时时更新不利于维护。所以我一直拖到发现别的问题，才来提交想法。

**Comment by xxtg666** [comment]
这个问题的主题不是兼容 Connector，是给用户一个选择设定下载mod位置的优先级

**Comment by LTCatt** [comment]
这个可能还是做 #2420 比较好……
