### ISSUE TITLE
关于PCL2加上基岩版的那些事.....

### ISSUE THREAD

**Issue by HAONI1028** [Hex-Dragon/PCL2#333]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

我觉得PCL可以加一个基岩版，这样不仅可以提高PCL的质量，同时变得更加方便！

———————其他建议————————————

#将那个联机模块给弄好

### 原因

这项优化让所有人可以更方便地去使用PCL。
如果没有这项优化，大家每次都必须很麻烦的去一个一个地打开，让操作变得很麻烦。也很烦人！！！！

**Comment by youzi-2333** [comment]
似乎与 #81 重复，先等回复吧……

**Comment by King-ming136121** [comment]
基岩版似乎可以直接在微软商店下载，并自己设置到桌面上，不需要跟Java版一样得用启动器打开，再说龙猫在lsslse 
 https://github.com/Hex-Dragon/PCL2/issues/81重复过了！不会出此功能......

**Comment by SorrowRain** [comment]
PCL2不会提供基岩版相关功能，基岩版本质是一个UWP应用，在windows上点击即可启动。

总之，感谢反馈（
