### ISSUE TITLE
无法正确获得极客蓝

### ISSUE THREAD

**Issue by qffylqwq** [Hex-Dragon/PCL2#3330]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

极客蓝主题的解密过程需要访问mcbbs，但mcbbs正在关站维护

### 原因

https://s2.ax1x.com/2020/02/06/16Crod.png
https://www.bilibili.com/opus/889391876255252536?spm_id_from=333.999.0.0

**Comment by allMagicNB** [comment]
极客蓝的获取方式早就公布了，随便找找都有，你是想拿主题还是解谜呢？

**Comment by xxtg666** [comment]
至少mcbbs目前还没有宣布停止运营，再等等看吧
