### ISSUE TITLE
将PCL内置的备份功能放到更好找（显眼）的位置

### ISSUE THREAD

**Issue by infinityAEE** [Hex-Dragon/PCL2#3331]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

可以将原在  更多-帮助-启动器-备份启动器设置  移动到  设置-启动器-备份（新开菜单）

### 原因

大部分人不会认真看PCL的帮助界面，所以这个实用的功能没有多少人发现……

**Comment by allMagicNB** [comment]
没必要吧，真正有备份需求的人才会找这里……

**Comment by zkitefly** [comment]
看看龙猫怎么说...

**Comment by LTCatt** [comment]
#1834
