### ISSUE TITLE
[优化] `启动前执行命令` Tooltip 添加命令行所在目录

### ISSUE THREAD

**Issue by youzi-2333** [Hex-Dragon/PCL2#3332]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

检索式：`is:issue 命令` `is:issue tooltip`（难检反馈：`命令` `启动前`）

如题，在 启动前执行命令 选项的 Tooltip 中添加一句：

```
执行命令时，命令行所在的目录是当前的 .minecraft 文件夹。
```

### 原因

这样可以方便用户调试命令的问题所在。例如，

命令：`cmd /C "{path}PCL\SyncHelp.bat"`

`PCL\SyncHelp.bat`：
```
@echo off
cd Help
git pull https://github.com/LTCatt/PCL2Help
git push
```

此时很难排查出问题的原因。添加了这些内容，就可以方便用户排查。

**Comment by allMagicNB** [comment]
感觉可以……话说只要插个cd /d不就可以自由转换了（

**Comment by LTCatt** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/8b08f7d4-4451-47b3-9f3e-53309f8f9226)
