### ISSUE TITLE
过长的信息会在较小的窗口大小下显示不全

### ISSUE THREAD

**Issue by bhop0** [Hex-Dragon/PCL2#3334]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

个人认为，显示较长的信息时可以换行显示。

### 原因

![image](https://github.com/Hex-Dragon/PCL2/assets/146635994/51d7e7b1-1561-46f3-820d-d6dc278b946c)
一部分信息难以直接查看。在上方图片中，我将窗口拉长到了将近显示器的2/3才能看到**省略**的错误信息。

**Comment by allMagicNB** [comment]
你这站着说话不腰疼……让龙猫怎么改

**Comment by youzi-2333** [comment]
暂未发现重复（检索式：`is:issue 换行 -label:"· Bug"`）……

其实我觉得这个看日志就行了，真要改的话，把 `GetExceptionSummary` 改成 `ExFull` 应该就行，但是要看 Hint 的代码是否支持多行提示的显示

https://github.com/Hex-Dragon/PCL2/blob/8c8b1066bff6476a14437a14bc16a281e25145bd/Plain%20Craft%20Launcher%202/Modules/Base/ModBase.vb#L2534-L2536

**Comment by bhop0** [comment]
> Edit:好像鼠标移到提示上一会就可以看到全部信息了
快照2.6.13，不起效

> 你这站着说话不腰疼……让龙猫怎么改 话说不是直接看日志就行了吗？
呃

![image](https://github.com/Hex-Dragon/PCL2/assets/146635994/c3054499-c77a-4084-94a6-714e6f19182f)

![image2](https://github.com/Hex-Dragon/PCL2/assets/146635994/ca52feab-f834-491d-8c3a-783d04f4348b)

如图所示，图一为现在的消息样式。

**Comment by bhop0** [comment]
好

**Comment by bhop0** [comment]
我只是希望能改进，如果不愿意改或者没有精力，可以直接关闭，因为这种情况本身就非常罕见，很难触发

**Comment by JingHai-Lingyun** [comment]
我觉得把长路径直接模糊（中间部分改成 /../）掉就好把？

**Comment by youzi-2333** [comment]
> 我觉得把长路径直接模糊（中间部分改成 /../）掉就好把？

umm 这个不是不行，但是这样需要改掉很多很多的函数调用，而且分析错误的时候也有可能需要看路径是否有问题，……我感觉不如自动换行（

**Comment by deep-dark-forest** [comment]
> 我觉得把长路径直接模糊（中间部分改成 /../）掉就好把？

路径很有用的好不好（

**Comment by bhop0** [comment]
> > 我觉得把长路径直接模糊（中间部分改成 /../）掉就好把？
> 
> 路径很有用的好不好（

多数情况下用不到，但是一些罕见的错误（我也不知道是什么）可能会用到，所以还是不省略好

**Comment by JingHai-Lingyun** [comment]
> 路径很有用的好不好（

仅在 Hint 中模糊，日志仍然可见

**Comment by LTCatt** [comment]
暂时没啥必要改，并且也不好改……Orz
