### ISSUE TITLE
可选择是否忽略整合包中无法下载的模组

### ISSUE THREAD

**Issue by bhop0** [Hex-Dragon/PCL2#3335]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

![image](https://github.com/Hex-Dragon/PCL2/assets/146635994/754a7578-122a-437a-83e7-5bbe01d38ead)
如图，下载部分整合包时，部分模组无法找到，**直接终止**了整合包的下载与安装。

### 原因

每次终止安装无法重新开始，并且如果遇见，就需要**手动下载**整合包文件并且**手动去除**其中无法下载的模组，或者**手动下载**其中列出的模组。

**Comment by deep-dark-forest** [comment]
我记得隔壁的6个字母的启动器会在下载整合包时如果有链接失效的模组会重定向，也许pcl可以参考一下

**Comment by zkitefly** [comment]
这个是整合包的问题吧

而且，建议上传启动器日志

**Comment by bhop0** [comment]
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14309036/Log1.txt)
第321行和第561行
