### ISSUE TITLE
进入PCL2后需要登录账号才能修改玩家配置，但是登录窗口会不定时卡死

### ISSUE THREAD

**Issue by Eric115411** [Hex-Dragon/PCL2#3336]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

进入启动器会弹出登录窗口，我尝试不用VPN登录会卡死，用了VPN后还是会卡死，但是直接关闭窗口可以正常使用，但是修改玩家数据仍需要登录

### 重现步骤

1、登录窗口
2、在登录窗口输入账号
3、窗口卡死

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14307118/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14307120/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14307121/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14307122/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14307123/Log5.txt)
![屏幕截图 2024-02-16 135631](https://github.com/Hex-Dragon/PCL2/assets/160209321/86bfc256-f201-4b5d-989c-5a8fb47dc5a6)

**Comment by allMagicNB** [comment]
这就是网络原因吧……

**Comment by burningtnt** [comment]
要么是网络问题，要么是 Windows 的这个 WebView 本身就有问题。与 PCL2 无关。
请尝试使用其他浏览器打开该网页

**Comment by hejiehao** [comment]
Webview 问题吧

**Comment by allMagicNB** [comment]
那么应该是系统的原因，与PCL2无关

**Comment by JingHai-Lingyun** [comment]
已知如果通过 Github 进行微软登录在 WebView 中会产生 JavaScript 脚本报错

**Comment by youzi-2333** [comment]
那应该是系统问题，先关了……

如果有问题可以继续提出
