### ISSUE TITLE
自定义皮肤不可用

### ISSUE THREAD

**Issue by ZincWeirdo0050** [Hex-Dragon/PCL2#3337]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在PCL最新快照，登录正版游戏账号，点击按钮“皮肤与披风”，再点击按钮“刷新头像”。几秒后，有时显示红底白字“获取微软正版皮肤失败【……】：直接下载文件失败【……】”；有时则成功获取。进入游戏后，不论是否成功获取，进入游戏后自身皮肤总为默认。

### 重现步骤

1、登录正版游戏账号（使用的皮肤为自定义）。
2、点击头像下的“皮肤与披风”，再点击“刷新头像”。几秒后，可能显示红底白字“获取微软正版皮肤失败【……】：直接下载文件失败【……】”。

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14308442/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14308444/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14308445/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14308446/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14308447/Log5.txt)

**Comment by allMagicNB** [comment]
网络问题
