### ISSUE TITLE
【进入游戏皮肤为默认，经反复多次不同检查无误】刷新皮肤报错：皮肤文件已损坏  (....皮肤文件路径） ：参数无效

### ISSUE THREAD

**Issue by FuriNahida** [Hex-Dragon/PCL2#3338]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

    问题：设置皮肤后进入游戏仍为默认皮肤，PCL2启动器主页面皮肤无显示。**而刷新皮肤报错：皮肤文件已损坏  (....皮肤文件路径） ：参数无效**
    已测：经过反复的、多次的、不同方位的检查，全方面不同角度的试验，包括检查：1.Minecraft.net皮肤设置正确无误，2.更换不同皮肤进入游戏测试；3.官方启动器启动后进入游戏测试，4.其他第三方启动器包括hmcl启动游戏测试等，进入游戏后都是默认史蒂夫皮肤。5.删了皮肤文件路径再加皮肤进去测试。以上方法均无效，问题依旧存在
    而除了PCL2启动器会报错其他启动器都是没有任何反应，故来此反馈期盼解决。

### 重现步骤

（前情：我之前有一段时间因为系统问题来回做了三四次系统，后来再开PCL2后就出现这个问题了）
1、在启动器中登录正版账号
2、待登录后能够看到皮肤头像未刷新出
3、光标悬停再空白头像上，点击“皮肤与披风”，点击“刷新头像”
4、左下角显示：皮肤文件已损坏(....皮肤文件路径） ：参数无效
5、启动游戏后进入世界无论单人多人都是默认原版皮肤

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14309285/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14309280/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14309282/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14309283/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14309284/Log2.txt)

**Comment by allMagicNB** [comment]
#3289

**Comment by burningtnt** [comment]
你能下载 http://textures.minecraft.net/texture/d178dc487d1fef3e18ba5b07c65edb2dd08dacc694dc8a5eb20eaf370b927892 这个文件嘛？

**Comment by allMagicNB** [comment]
> 你能下载 http://textures.minecraft.net/texture/d178dc487d1fef3e18ba5b07c65edb2dd08dacc694dc8a5eb20eaf370b927892 这个文件嘛？

我这边访问正常，估计又是一个下载皮肤下载到反诈宣传页面了😂

**Comment by FuriNahida** [comment]
> 你能下载 http://textures.minecraft.net/texture/d178dc487d1fef3e18ba5b07c65edb2dd08dacc694dc8a5eb20eaf370b927892 这个文件嘛？

啧，进去后还真是反诈宣传页面，那请问怎么解决呢？

**Comment by allMagicNB** [comment]
> > 你能下载 http://textures.minecraft.net/texture/d178dc487d1fef3e18ba5b07c65edb2dd08dacc694dc8a5eb20eaf370b927892 这个文件嘛？
> 
> 啧，进去后还真是反诈宣传页面，那请问怎么解决呢？

挂梯子
或者移民（

**Comment by FuriNahida** [comment]
> > > 你能下载 http://textures.minecraft.net/texture/d178dc487d1fef3e18ba5b07c65edb2dd08dacc694dc8a5eb20eaf370b927892 这个文件嘛？
> > 
> > 
> > 啧，进去后还真是反诈宣传页面，那请问怎么解决呢？
> 
> 挂梯子 或者移民（

好的感谢。顺便问一句，后续这个有办法解决么？还是以后每次都要挂梯子了

**Comment by allMagicNB** [comment]
> 好的感谢。顺便问一句，后续这个有办法解决么？还是以后每次都要挂梯子了

只能等待你的运营商，要不然基本只能挂梯子了

**Comment by FuriNahida** [comment]
> > 好的感谢。顺便问一句，后续这个有办法解决么？还是以后每次都要挂梯子了
> 
> 只能等待你的运营商，要不然基本只能挂梯子了 Edit:要讨论更多内容的话推荐前往Discussion提问

这边挂了梯子不会被拦了，刚才好了一下，刷出来了，一进游戏发现又没皮肤了，，

**Comment by FuriNahida** [comment]
> > 好的感谢。顺便问一句，后续这个有办法解决么？还是以后每次都要挂梯子了
> 
> 只能等待你的运营商，要不然基本只能挂梯子了 Edit:要讨论更多内容的话推荐前往Discussion提问

然后我刷新了一下皮肤又回到那个问题了，但是网址不会被拦

**Comment by FuriNahida** [comment]
> > > 好的感谢。顺便问一句，后续这个有办法解决么？还是以后每次都要挂梯子了
> > 
> > 
> > 只能等待你的运营商，要不然基本只能挂梯子了 Edit:要讨论更多内容的话推荐前往Discussion提问
> 
> 这边挂了梯子不会被拦了，刚才好了一下，刷出来了，一进游戏发现又没皮肤了，，

请问这个该怎么解决

**Comment by allMagicNB** [comment]
> > 这边挂了梯子不会被拦了，刚才好了一下，刷出来了，一进游戏发现又没皮肤了，，
> 
> 请问这个该怎么解决

去Discussion发提问……

**Comment by JingHai-Lingyun** [comment]
请不要多次发帖，你应该善用 Edit 功能
