### ISSUE TITLE
[BUG] 错误地识别了某 Mod 所需要的 ModLoader

### ISSUE THREAD

**Issue by SuoHouDaiShi** [Hex-Dragon/PCL2#3339]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

众所周知，NeoForge 是新兴的 ModLoader，而鉴于它的发布时间较晚，未涉及到 1.20 及以前的版本，而在 PCL 中搜索 `Collective` 模组的时候，错误的将该模组 1.18.2 的 6.82 版本识别为了 Forge / Fabric / Qulit / **NeoForge** 版本，很容易误导玩家。在 CurseForge 平台上，**作者并未将该版本标注为 NeoForge 兼容版本。**

### 重现步骤

1.点击“下载”
2.点击“Mod”
3.在搜索框中输入“Collective”并搜索
4.点击“Collective”模组
5.找到该模组的 1.18.2 6.82 版本，BUG 出现
![图片](https://github.com/Hex-Dragon/PCL2/assets/119282947/b5ab9c71-25c1-450a-84b7-c9b7349ea652)
![图片](https://github.com/Hex-Dragon/PCL2/assets/119282947/dbc93699-01c1-4e8f-abd9-194f540ca44d)

### 日志与附件

![图片](https://github.com/Hex-Dragon/PCL2/assets/119282947/b5ab9c71-25c1-450a-84b7-c9b7349ea652)
![图片](https://github.com/Hex-Dragon/PCL2/assets/119282947/dbc93699-01c1-4e8f-abd9-194f540ca44d)
## 需要日志就回复，看到了会传

**Comment by hejiehao** [comment]
让我康康这个 jb API 在干什么（）

**Comment by allMagicNB** [comment]
发下日志吧，看看请求的啥API网址（

**Comment by hejiehao** [comment]
https://api.curseforge.com/

**Comment by SuoHouDaiShi** [comment]
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14310175/Log1.txt)

**Comment by JingHai-Lingyun** [comment]
Log 里是看不出来的返回了什么的...
CurseForge 请求接口不是通过参数访问...

**Comment by hejiehao** [comment]
[collective.json](https://github.com/Hex-Dragon/PCL2/files/14310207/collective.json)

**Comment by allMagicNB** [comment]
```
"gameVersions":["Fabric","1.18.2","NeoForge","Forge","Quilt"]
```
……我的沉默震耳欲聋

**Comment by WForst-Breeze** [comment]
那就关了先，感谢您的反馈

**Comment by allMagicNB** [comment]
加个`第三方`Label吧？
