### ISSUE TITLE
在 更多 页侧边栏加入“向社区提问”按钮

### ISSUE THREAD

**Issue by Ad-closeNN** [Hex-Dragon/PCL2#3341]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

如题，在`更多`的侧边栏加上`向社区提问`的按钮，直接导向[Discussions](https://github.com/Hex-Dragon/PCL2/discussions)页面
`原图`
![image](https://github.com/Hex-Dragon/PCL2/assets/103355026/3e3b166a-537e-40d5-9302-310107d07fa2)
`改图`
![image](https://github.com/Hex-Dragon/PCL2/assets/103355026/d0425601-31e7-473c-8836-71c19e3cd12b)

### 原因

`新功能提问`导向的是具有筛选器的`Discussions`，有些人以为Discussions就只有投票，而没有发现可以提问
另外，还能直接查看到Discussions，不用再次点击图标
~~当然不加也可以我知道龙猫忙~~

**Comment by LTCatt** [comment]
比较冗余，暂不考虑

**Comment by allMagicNB** [comment]
~~小白都直接发Issue了，那么要这个按钮有何用~~

**Comment by deep-dark-forest** [comment]
> `新功能提问`

是什么东西啊（
