### ISSUE TITLE
对所有Hint添加鼠标悬浮在上面时的提示

### ISSUE THREAD

**Issue by allMagicNB** [Hex-Dragon/PCL2#3342]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

对所有`Hint`函数添加提示，内容为`Hint`的**完整**内容

### 原因

在出现#3334 时，若要查看**完整**报错信息，则必须前往日志查看，添加提示可以鼠标悬浮在上面时显示完整提示文本

**Comment by bhop0** [comment]
非常好建议

**Comment by LTCatt** [comment]
会显示不下的唯一情况就是长报错，对普通用户而言看报错的前半部分就够了，对高级用户而言本来就会去翻 log，所以做了也没啥用……

**Comment by allMagicNB** [comment]
> 会显示不下的唯一情况就是长报错，对普通用户而言看报错的前半部分就够了，对高级用户而言本来就会去翻 log，所以做了也没啥用……

但是有的时候路径/文件名过长，且报错内容都被堆在后面了的时候只看前半部分根本不够……@LTCatt
