### ISSUE TITLE
正式版不能输入解锁码

### ISSUE THREAD

**Issue by ZeroCore-Zero** [Hex-Dragon/PCL2#3347]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

正式版不能输入解锁码，也不能升降级成快照版orz
感觉可以修改一下让正式版也可以解锁，或者提供一个更换成快照版的选项

### 原因

赞助之后想要输入解锁码，但提示正式版不能输入解锁码，导致无法解锁（悲

**Comment by allMagicNB** [comment]
额……让我想想

**Comment by iPodtouch6557** [comment]
应该不会受理，是有什么问题才导致你不肯下一个快照版啊

**Comment by ZeroCore-Zero** [comment]
> 应该不会受理，是有什么问题才导致你不肯下一个快照版啊

我也找不到什么地方能单独下载一个快照版啊qwq

**Comment by allMagicNB** [comment]
> > 应该不会受理，是有什么问题才导致你不肯下一个快照版啊
> 
> 我也找不到什么地方能单独下载一个快照版啊qwq

爱发电私信回复`下载`

**Comment by wuliaodexiaoluo** [comment]
> 我也找不到什么地方能单独下载一个快照版啊qwq

6.66档回复下载，>=12.34群里面下一份然后更新
如果没有回复，说明自动回复寄了
自动下载要过服务器的sign签名，正式版更新不需要密钥，你让龙猫怎么整，正式版没有做加密诶

**Comment by WForst-Breeze** [comment]
给这个上个待处理好了，不过感觉不会做（
> 感觉可以修改一下让正式版也可以解锁，或者提供一个更换成快照版的选项

**Comment by allMagicNB** [comment]
> 给这个上个待处理好了，不过感觉不会做（
> > 感觉可以修改一下让正式版也可以解锁，或者提供一个更换成快照版的选项

确实，这样风险比较大

**Comment by LTCatt** [comment]
不会做，会被破的 orz

**Comment by allMagicNB** [comment]
不对啊这不应该加`拒绝/放弃`Label吗（

**Comment by ZeroCore-Zero** [comment]
> > 我也找不到什么地方能单独下载一个快照版啊qwq
> 
> 6.66档回复下载，>=12.34群里面下一份然后更新 如果没有回复，说明自动回复寄了 自动下载要过服务器的密钥验证，正式版更新不需要密钥，你让龙猫怎么整，正式版没有做加密诶，反编译不是很轻松么

多谢orz
