### ISSUE TITLE
重命名版本时使用过长的名称可能会导致重命名错误

### ISSUE THREAD

**Issue by bhop0** [Hex-Dragon/PCL2#3348]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/Hex-Dragon/PCL2/assets/146635994/66f2613a-23f2-463f-8690-afbdb4577b71)
![image](https://github.com/Hex-Dragon/PCL2/assets/146635994/252c0b68-6dbb-4fad-b088-cefd27517a93)
![image](https://github.com/Hex-Dragon/PCL2/assets/146635994/e40e5471-3584-4de2-8e62-1c7a6b252a89)

如图。这可能是因为过长的路径导致的，也就是说，如果存放游戏的文件夹名称过长，就**有可能**触发。
这只是一种较为极端的情况，**多数情况下不会触发，也没有必要修复**。
在本人的环境下，触发时游戏本体的绝对路径：
C:\Users\七个字的用户名\Desktop\Misc\Games\Minecraft\PCL\.minecraft\versions\版本名称\版本名称.jar/.json
上限为91个字符。超过就会出现类似图三的报错。

### 重现步骤

在此之前，最好将启动器和游戏存放在一个长名称的文件夹内
例如：“一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十”
1、打开版本设置
2、点击修改版本名
3、随意输入（确保字符的数量足够）
4、点击确定
如果绝对路径足够长，就可以触发。

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14318939/Log1.txt)
88行到100行

**Comment by allMagicNB** [comment]
首先PCL2已经给出了解决方法

**Comment by bhop0** [comment]
> 已经给出了解决方法

限制版本名称字符数量？

**Comment by allMagicNB** [comment]
#1448

**Comment by bhop0** [comment]
这都能重？
