### ISSUE TITLE
在更新pcl快照版后无法正常启动游戏（显示已启动，但见不到游戏界面）

### ISSUE THREAD

**Issue by Lacennon** [Hex-Dragon/PCL2#3351]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在更新pcl快照版后无法正常启动游戏（显示已启动，但见不到游戏界面）

### 重现步骤

似乎无法重现，所以我会说明我的信息：
版本 : PCL Snapshot 2.6.13 1.20 fabric 0.14.21
mod : Allmusic , JEI , 附魔描述 ， 伽马工具 ， miniHUD , 钠 , Appleskin , ysm , 投影 , Do a barrel roll , ESSENTIAL 及其所有运行库 

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14320797/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14320798/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14320799/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14320800/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14320801/Log2.txt)

**Comment by allMagicNB** [comment]
你等等啊你
~~急急国王~~

**Comment by Lacennon** [comment]
等了五六分钟了，还要等吗（

**Comment by Lacennon** [comment]
nvm（

**Comment by allMagicNB** [comment]
首先，Issue模板类型错误

**Comment by hejiehao** [comment]
所以龙猫应该要做显示游戏日志功能
