### ISSUE TITLE
MOD列表加载错误

### ISSUE THREAD

**Issue by XK123furru** [Hex-Dragon/PCL2#3355]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

mod列表加载错误，列表mod与添加的mod不付并弹出弹窗内容如下
出现错误
加载 Mod 列表 UI失败:指定的Visual已经是另一个Visual的子级或者已经是CompositionTarget的根。
在 PCL.PageVersionMod.RefreshResult(List`1 Mods)在PCL.PageVersionMod.LoadUIFromLoaderOutput()错误类型:System.ArgumentException
是否反馈此问题?如果不反馈，这个问题可能永远无法得到解决!

### 重现步骤

1、点击版本设置
2、点击mod管理

### 日志与附件

[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14321373/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14321374/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14321375/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14321376/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14321377/Log3.txt)

**Comment by allMagicNB** [comment]
#3092
