### ISSUE TITLE
PCL2无法正确地自动识别部分原生启动器安装的愚人节版本

### ISSUE THREAD

**Issue by allMagicNB** [Hex-Dragon/PCL2#3360]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/Hex-Dragon/PCL2/assets/116283787/39085023-969b-4289-9286-3494929d4bd7)
![image](https://github.com/Hex-Dragon/PCL2/assets/116283787/2932ea5a-dfb8-4ee5-bca9-153d6678ec32)
![image](https://github.com/Hex-Dragon/PCL2/assets/116283787/3e96e1c8-6106-4dc0-ba60-f1942aa399bc)

### 重现步骤

1、使用官启下载并启动愚人节版本
2、查看PCL2中官方启动器文件夹的版本列表

### 日志与附件

日志内可见大量的
```
[XX:XX:XX.XXX] [Minecraft] 无法完全确认 MC 版本号的版本：XXX
```
除此之外，**并无可用信息**

**Comment by mc-124** [comment]
似乎没有任何一种能100%确定Minecraft版本的方法……
JSON内的releaseTime time download 之类的可能可以确定版本的会随着~~bugjump~~ mojang修复~~bug~~特性而更新，assets和libraries只能确定大概的版本

**Comment by allMagicNB** [comment]
> 似乎没有任何一种能100%确定Minecraft版本的方法…… JSON内的releaseTime time download 之类的可能可以确定版本的会随着~bugjump~ mojang修复~bug~特性而更新，assets和libraries只能确定大概的版本

Json内的ID可以

**Comment by mc-124** [comment]
> > 似乎没有任何一种能100%确定Minecraft版本的方法…… JSON内的releaseTime time download 之类的可能可以确定版本的会随着~bugjump~ mojang修复~bug~特性而更新，assets和libraries只能确定大概的版本
> 
> Json内的ID可以

ID能改，在改版本名时ID就会被修改，这个可以在1.12原版端复现
目前只能100%确定安装了任意加载器的版本的版本，因为加载器会在JSON内留下clientVersion

**Comment by mc-124** [comment]
> > > > 似乎没有任何一种能100%确定Minecraft版本的方法…… JSON内的releaseTime time download 之类的可能可以确定版本的会随着~bugjump~ mojang修复~bug~特性而更新，assets和libraries只能确定大概的版本
> > > 
> > > 
> > > Json内的ID可以
> > 
> > 
> > ID能改，在改版本名时ID就会被修改，这个可以在1.12原版端复现 目前只能100%确定安装了任意加载器的版本的版本，因为加载器会在JSON内留下clientVersion
> 
> 但是HMCL识别正常为完全版本号 ![image](https://private-user-images.githubusercontent.com/116283787/305709707-b58489e0-b24d-4f34-b5cf-e205a43540f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNTQ4ODIsIm5iZiI6MTcwODI1NDU4MiwicGF0aCI6Ii8xMTYyODM3ODcvMzA1NzA5NzA3LWI1ODQ4OWUwLWIyNGQtNGYzNC1iNWNmLWUyMDVhNDM1NDBmMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxOFQxMTA5NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZjk3YTMyNDg1MGY0MGY3NjEzNzA0OTQ2MDY2ZDAxMmIzYzU0ZGQ5Njg5MzNjODU2MWViMjliNDRhMGEwNGQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.m5Q9ILy4u8JFt1TPE7R0F-qepzvT2tUsrLe4p54rpK0) ![image](https://private-user-images.githubusercontent.com/116283787/305709644-a41de74f-a97a-4d3b-a026-10f7b8bb6645.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNTQ4ODIsIm5iZiI6MTcwODI1NDU4MiwicGF0aCI6Ii8xMTYyODM3ODcvMzA1NzA5NjQ0LWE0MWRlNzRmLWE5N2EtNGQzYi1hMDI2LTEwZjdiOGJiNjY0NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxOFQxMTA5NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zY2Y2NDA5OTE2N2NhNTJkMzExZWFhNzM3YzIyOWJiNjBmOWFmYmFjYmQxN2ZjYzFhYTFkYTM1YWUzZmIzNjlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gfoMK0CSPZZ66RHsHaavhrnRKxN2olPlYZ9xNiv4NzI) ![image](https://private-user-images.githubusercontent.com/116283787/305709608-0486e2c3-9a3a-4235-909d-93def65a8f12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNTQ4ODIsIm5iZiI6MTcwODI1NDU4MiwicGF0aCI6Ii8xMTYyODM3ODcvMzA1NzA5NjA4LTA0ODZlMmMzLTlhM2EtNDIzNS05MDlkLTkzZGVmNjVhOGYxMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxOFQxMTA5NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ODc0ZDQ4NWVmNzBlM2ViZmRiOTg5NDg0NDNkN2FjZWQ0NjIxNTlmMDM3MjcxZmIxNGVkYTJmODY1M2VmNTU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IzQlOcniieu57znFayra_KXlA_03l-fYsDu9XJp6i14) ![image](https://private-user-images.githubusercontent.com/116283787/305709677-0aa2ae3a-91d0-40af-8d71-a5d9ec2cd3a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNTQ4ODIsIm5iZiI6MTcwODI1NDU4MiwicGF0aCI6Ii8xMTYyODM3ODcvMzA1NzA5Njc3LTBhYTJhZTNhLTkxZDAtNDBhZi04ZDcxLWE1ZDllYzJjZDNhNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxOFQxMTA5NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNjkzMmQ4ZTgzZWNlZGJmNmE3ZDg5MGMyMTA4MzFjNzE2ZGZhMDdlYjQzNjBmMTkyMzI5YjdlYWY1M2Q3MmRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.b-d-k66N_sviYtLiXwx84aiRmxcBLHmgW6h2wwXwrmI)

这是没法识别直接显示id了 你改个id它的版本号也跟着变，还是没法确定绝对版本号

**Comment by mc-124** [comment]
这个issues很可能被猫打上[拒绝/放弃]+[需要社区帮助]，或者直接学HMCL摆烂直接显示id

**Comment by allMagicNB** [comment]
> 这个issues很可能被猫打上[拒绝/放弃]+[需要社区帮助]，或者直接学HMCL摆烂直接显示id

但是HMCL显示的不是版本ID而是版本名，你猜猜为什么名字没分大小写ID也没分大小写，但是下面的版本名就有大小写了呢？
话说别版聊，要聊去Discussion开讨论

**Comment by mc-124** [comment]
> > 这个issues很可能被猫打上[拒绝/放弃]+[需要社区帮助]，或者直接学HMCL摆烂直接显示id
> 
> 但是HMCL显示的不是版本ID而是版本名，你猜猜为什么名字没分大小写ID也没分大小写，但是下面的版本名就有大小写了呢？ 话说别版聊，要聊去Discussion开讨论

~~瞎了~~

**Comment by mc-124** [comment]
我去看看有没有什么解决办法

**Comment by mc-124** [comment]
有没有较老的原版JSON（如几年前的）

**Comment by allMagicNB** [comment]
后续讨论转到#3361

**Comment by LTCatt** [comment]
可能能借由 #3294 一并解决……

**Comment by allMagicNB** [comment]
@LTCatt 咋换 Label 了（

**Comment by LTCatt** [comment]
批量迁移标签的时候迁移错了……

**Comment by LTCatt** [comment]
#3294 实现后已经可以识别大多数愚人节版本了，现在还不能识别的是：2018/4 及其之前且并非通过 PCL 安装的愚人节版本
考虑到这已经是极小的一部分了，并且实现起来至少 100 行起步，完善识别意义也不是很大（又不是不能启动），确实没什么必要再做了……
