### ISSUE TITLE
背景图片加载错误

### ISSUE THREAD

**Issue by ling-314** [Hex-Dragon/PCL2#3365]
### 检查项

- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

当我打开存放启动器背景图片的文件夹（PCL\Pictures），Windows会产生Thumbs.db文件，而PCL会读取该文件夹下所有文件，导致无法显示背景图片
![Snipaste_2024-02-19_08-52-11](https://github.com/Hex-Dragon/PCL2/assets/124340980/f2dc5883-93da-417a-93d3-61a8908adbb5)
可以限制能够当做背景图片的图片类型（如png，jpg），或者直接跳过Thumbs.db文件

### 原因

每次想要关闭这项提示时，都需要进入文件夹，打开“隐藏受保护的操作系统文件”，删掉文件，再关闭，非常麻烦

**Comment by mc-124** [comment]
是PCL的毛病，让龙猫过滤下即可

**Comment by wuliaodexiaoluo** [comment]
> 每次想要关闭这项提示时，都需要进入文件夹，打开“隐藏受保护的操作系统文件”，删掉文件，再关闭，非常麻烦

为什么我没有生成

**Comment by xxtg666** [comment]
我没遇到过，不过确实应该加一个后缀名过滤

**Comment by LTCatt** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/643ee1ad-b514-4f7b-b201-6e34ccdddea3)
你更新了吗

**Comment by ling-314** [comment]
PCL提示是最新正式版2.6.13

**Comment by allMagicNB** [comment]
[Log1.txt](https://githu@LTCatt .com/Hex-Dragon/PCL2/files/14338944/Log1.txt)
@LTCatt 你那几行代码好像是发布后写的或者没用

**Comment by allMagicNB** [comment]
@LTCatt 过来看下，这里有个刚复活的待处理
