### ISSUE TITLE
mod管理报错，不显示已安装全部模组

### ISSUE THREAD

**Issue by xynsf** [Hex-Dragon/PCL2#3367]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

弹窗
![T9{D49N62V199`UNXE_FXDJ](https://github.com/Hex-Dragon/PCL2/assets/122205486/2f732dc5-aee0-4b08-855f-901e3e487588)
![Uploading O5`1IG47Z96F(N8)6]271QI.png…]
![I_B6294MHFG58(O4@MXQ%{7](https://github.com/Hex-Dragon/PCL2/assets/122205486/09f2eabd-3e92-4a55-8a2c-47606c5f7572)
()

### 重现步骤

1、往mods里丢模组
2、出现弹窗

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14326371/Log1.txt)
log2~5缺失 
![DMYRL%RX)QDT)Z_L$2CN~_B](https://github.com/Hex-Dragon/PCL2/assets/122205486/de79a67f-8d86-4bb3-a5f7-636f76b5b15d)

**Comment by allMagicNB** [comment]
#3092
