### ISSUE TITLE
beta1.7.3无法启动安装babric版本

### ISSUE THREAD

**Issue by xynsf** [Hex-Dragon/PCL2#3369]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

启动时显示无法补全界面
![CE4)V_6DDK1~B2$FE%_ N{T](https://github.com/Hex-Dragon/PCL2/assets/122205486/6f04a101-5c2b-4455-afe1-78dc77032f29)

### 重现步骤

1、安装babric，启动安装babric版本
2、等待，报错

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14326396/Log1.txt)
log2~5丢失
![DMYRL%RX)QDT)Z_L$2CN~_B](https://github.com/Hex-Dragon/PCL2/assets/122205486/a711791a-9da3-46c0-9b19-88f5b6c1d1e5)

**Comment by allMagicNB** [comment]
MCBBS挂了，不关PCL2事

**Comment by xynsf** [comment]
所以是没有办法启动了么

**Comment by allMagicNB** [comment]
> 所以是没有办法启动了么
> 

切换`设置->启动器->下载->版本列表获取`选项就可以了

**Comment by xynsf** [comment]
版本列表获取是选的平衡

**Comment by allMagicNB** [comment]
> 版本列表获取是选的平衡
> 

那就选`尽量使用官方源`，还是不行的话要么用梯子要么试试用官启装一遍再试

**Comment by xynsf** [comment]
> > 版本列表获取是选的平衡
> 
> 那就选`尽量使用官方源`，还是不行的话要么用梯子要么试试用官启装一遍再试

没梯子咋办

**Comment by Pigeon0v0** [comment]
你现在更新到最新版启动器就能正常安装了...

**Comment by Pigeon0v0** [comment]
哦不对 Babric 现在不受 PCL 支持，你自己从其他渠道下了补全文件吧
