### ISSUE TITLE
1.18.2启动失败

### ISSUE THREAD

**Issue by digkimn** [Hex-Dragon/PCL2#3370]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃基本不是 PCL 的原因，请 **不要** 提交反馈。你可以在论坛或社区找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用 HMCL 启动，HMCL 没有出现问题。** 如果 HMCL 也无法启动就不是 PCL 导致的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

1.18.2启动失败

### PCL 错误报告、日志与附件

[错误报告-2024-2-19_12.41.57.zip](https://github.com/Hex-Dragon/PCL2/files/14326610/-2024-2-19_12.41.57.zip)

### HMCL 启动脚本

无

**Comment by allMagicNB** [comment]
请尝试使用HMCL启动器启动

**Comment by Ad-closeNN** [comment]
~~我用记事本打开怎么是乱码，vs code打开能看但还有部分�?~~
你们看的日志是正常的吗

**Comment by allMagicNB** [comment]
> ~~我用记事本打开怎么是乱码，vs code打开能看但还有部分�?~~
> 你们看的日志是正常的吗

自信点就是不正常的

**Comment by Ad-closeNN** [comment]
> > ~我用记事本打开怎么是乱码，vs code打开能看但还有部分�?~ 你们看的日志是正常的吗
> 
> 在右下角切换编码

要选啥编码，记事本选utf8同样乱码，vs选utf8就没那么多不正常字符了...

**Comment by Ad-closeNN** [comment]
e，要不试试安装Java21或者补全游戏或者重装版本

**Comment by allMagicNB** [comment]
别试了，让Author重新上传

**Comment by zkitefly** [comment]
在 控制面板 -- 时钟和区域 -- 区域 -- 管理 -- 更改系统区域设置 里面上面选「中文（简体，中国）」，并且把下面那个勾去掉 ![](https://img.kookapp.cn/assets/2023-03/zsLRF3LrcD0we0hj.png)

**Comment by Ad-closeNN** [comment]
> 在 控制面板 -- 时钟和区域 -- 区域 -- 管理 -- 更改系统区域设置 里面上面选「中文（简体，中国）」，并且把下面那个勾去掉 ![](https://camo.githubusercontent.com/e1f94e2d36097b4881432199682efaedf66df1b8d23733a64173da9ec6625b3b/68747470733a2f2f696d672e6b6f6f6b6170702e636e2f6173736574732f323032332d30332f7a734c5246334c72634430776530686a2e706e67)

win10有这个吗，他的是win10（日志里面的）~~又好像是Win 11的~~

```
-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: **Windows 10** (amd64) version 10.0
	Java Version: 1.8.0_401, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5516128624 bytes (5260 MB) / 5905580032 bytes (5632 MB) up to 5905580032 bytes (5632 MB)
```

```
[11:01:42.654] [Control] 按下按钮：提交新反馈
[11:01:42.654] [Control] 普�?�弹框返回：1
[11:01:42.919] [System] 诊断信息�?
操作系统：Microsoft Windows 11 家庭中文�?
剩余内存�?5358 M / 16183 M
DPI�?144�?150%�?
MC 文件夹：D:\PCL II\.minecraft\
文件位置：D:\PCL II\
```

**Comment by zkitefly** [comment]
> win10有这个吗，他的是win10（日志里面的）

一般情况下是有的

**Comment by wuliaodexiaoluo** [comment]
>win10有这个吗，他的是win10（日志里面的）又好像是Win 11的

这玩意是Win10 1809还是1903就有了

**Comment by Ad-closeNN** [comment]
那就等待Author

**Comment by Ad-closeNN** [comment]
> > win10有这个吗，他的是win10（日志里面的）又好像是Win 11的
> 
> 这玩意是Win10 1809还是1903就有了 怕不是塞了二进制数据进去 Microsoft Visual Studio 根本打不开，全是乱码 ~为毛图片都是404啊~ ![图片](https://private-user-images.githubusercontent.com/160083863/305820631-c38a961c-4220-498f-b5f2-66099ea1bf99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMjUxNjEsIm5iZiI6MTcwODMyNDg2MSwicGF0aCI6Ii8xNjAwODM4NjMvMzA1ODIwNjMxLWMzOGE5NjFjLTQyMjAtNDk4Zi1iNWYyLTY2MDk5ZWExYmY5OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxOVQwNjQxMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMDYyMDNjMzZlZTQ3ODZlMzg2ZmUwODcxNDViNzIyNWY4YWI4N2FhODY4MDcyOTQ1ZTFjYmY2NmRlMDM5MzQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FfZrVQIZvN8-CdCP4e_mJO17PZb6OafFuiQQFG130dk)

UTF8的？调成UTF8至少能看懂

**Comment by wuliaodexiaoluo** [comment]
> UTF8的？调成UTF8至少能看懂

没差
UTF-8/UTF-16/GBK/GB18013都试过了 Visual Studio Code 除了英文和数字其他都是乱码

**Comment by hejiehao** [comment]
> > win10有这个吗，他的是win10（日志里面的）又好像是Win 11的
> 
> 这玩意是Win10 1809还是1903就有了 怕不是塞了二进制数据进去 Microsoft Visual Studio 根本打不开，全是乱码 ~为毛图片都是404啊~ ![图片](https://private-user-images.githubusercontent.com/160083863/305820631-c38a961c-4220-498f-b5f2-66099ea1bf99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMzM1NDYsIm5iZiI6MTcwODMzMzI0NiwicGF0aCI6Ii8xNjAwODM4NjMvMzA1ODIwNjMxLWMzOGE5NjFjLTQyMjAtNDk4Zi1iNWYyLTY2MDk5ZWExYmY5OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxOVQwOTAwNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZTI5MTg3NTk1MTJmOGFkNGYxNjdiOWU2YzY3MGRkMjFjOTBhNTc2MGI5NzJkY2Q0YTFjOTUwN2M1ZTc4ZDNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Vsesad3Qxb1tHQrsZUi88xYxrcdaVTrfTjjPQkiuZEs)

竟然还有人用 IDE 来看日志👀

**Comment by Ad-closeNN** [comment]
> 竟然还有人用 IDE 来看日志👀

原来这是IDE 吗, 我就说怎么不像VS Code.jpeg

**Comment by wuliaodexiaoluo** [comment]
> 竟然还有人用 IDE 来看日志👀

顺手而已，刚好IDE开了，就用IDE了，不然其他时候习惯用Visual Studio Code

**Comment by mc-124** [comment]
这应该是文件损坏了，GPT4.0自己跑了一堆py脚本后跟我说无能为力，我尝试了code的所有编码也都是乱码

**Comment by Ad-closeNN** [comment]
Author不看邮箱吗，等4h了.png

**Comment by wuliaodexiaoluo** [comment]
估计是不在线

**Comment by mc-124** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/138775126/a179f71f-8dab-49f4-a5c5-b33a54144437)

**Comment by mc-124** [comment]
> Author不看邮箱吗，等4h了.png
> 
> EDIT: #3343 (2 days ago) #3314 (last week) 很久没回了

这种估计不遇到第二个bug都不上github的（

**Comment by JingHai-Lingyun** [comment]
请别急

**Comment by Ad-closeNN** [comment]
> ![image](https://private-user-images.githubusercontent.com/138775126/305907989-a179f71f-8dab-49f4-a5c5-b33a54144437.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMzcwMjUsIm5iZiI6MTcwODMzNjcyNSwicGF0aCI6Ii8xMzg3NzUxMjYvMzA1OTA3OTg5LWExNzlmNzFmLThkYWItNDlmNC1hNWM1LWIzM2E1NDE0NDQzNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxOVQwOTU4NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYjk2ZTQzMGRlYmQ0ZmQ5YTk5OWYyZTA1NmZlZGViYTA3ZmEyYTcwOTA4NWY1MTRiYzJhYjVhNGU5MTM0MDk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.V_tlWQvfqAqwcNApeYjwHh5rncJ1fAh1oetYPweKpm4)

https://github.com/Hex-Dragon/PCL2/issues/3370#issuecomment-1951740432
我回过了... 正版3.5也是这样
![image](https://github.com/Hex-Dragon/PCL2/assets/103355026/3d623064-6de3-4f3c-ad4d-0e0285769aa1)

**Comment by wuliaodexiaoluo** [comment]
```log
Java 淇℃伅锛欽RE 8 (8.0.401)锛?64 浣嶏細D:\Program Files (x86)\Java\bin\
```
认真看了一遍，他貌似是Java8启动1.18.2

**Comment by wuliaodexiaoluo** [comment]
![图片](https://github.com/Hex-Dragon/PCL2/assets/160083863/b961bcbd-f13f-47b5-88ed-17e61319bb54)
文心一言也是这个回答
看这个应该是从Mojang下载的java，有出现网络错误，怀疑是网络波动没下全

**Comment by mc-124** [comment]
> ![图片](https://private-user-images.githubusercontent.com/160083863/305911160-b961bcbd-f13f-47b5-88ed-17e61319bb54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMzc3MjAsIm5iZiI6MTcwODMzNzQyMCwicGF0aCI6Ii8xNjAwODM4NjMvMzA1OTExMTYwLWI5NjFiY2JkLWYxM2YtNDdiNS04OGVkLTE3ZTYxMzE5YmI1NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxOVQxMDEwMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOTI4ZDhmMjRmMmYwNTdmYjA4YTAzOGZhZjZlZjlkYjVkMTE2MDI1ZDQ0ZWFlZGQ3NWEwOTk2NjNhNTdjMDY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.I0vRFLlCpry8ptCFax2q9ULZ90zw7gddyS1nxVeCVXk) 文心一言也是这个回答 看这个应该是从Mojang下载的java，有出现网络错误，怀疑是网络波动没下全

G4曰：
![image](https://github.com/Hex-Dragon/PCL2/assets/138775126/c1210dca-2b3d-4ab4-adad-dfba8dc473eb)

**Comment by mc-124** [comment]
> ```
> Java 淇℃伅锛欽RE 8 (8.0.401)锛?64 浣嶏細D:\Program Files (x86)\Java\bin\
> ```
> 
> 认真看了一遍，他貌似是Java8启动1.18.2

不是，他是拿的jdk17
PCL2日志：
```log
[12:41:54.220] [Launch] Java 淇℃伅锛欽DK 17 (17.0.3)锛?64 浣嶏細C:\Users\椤烘壙\AppData\Roaming\.minecraft\cache\java\java-runtime-gamma\windows-x64\java-runtime-gamma\bin\
```
bugjump的Java版本列表：
```json
"java-runtime-gamma": [
            {
                "availability": {
                    "group": 5199,
                    "progress": 100
                },
                "manifest": {
                    "sha1": "f3e086257efca1a662f7276c415e3a9879c90ee9",
                    "size": 82289,
                    "url": "https://piston-meta.mojang.com/v1/packages/f3e086257efca1a662f7276c415e3a9879c90ee9/manifest.json"
                },
                "version": {
                    "name": "17.0.8",
                    "released": "2023-09-15T08:28:43+00:00"
                }
            }
        ],
```

**Comment by wuliaodexiaoluo** [comment]
我们是不是应该转讨论了，这版聊有点严重了。。。。。。

**Comment by mc-124** [comment]
可以，我去创个

**Comment by mc-124** [comment]
#3373

**Comment by LTCatt** [comment]
这不是启动器的问题，请重新安装 java

**Comment by LTCatt** [comment]
该 issue 已确认为 #3343
