### ISSUE TITLE
下载Java时，网络不佳使用高校源的Java

### ISSUE THREAD

**Issue by wuliaodexiaoluo** [Hex-Dragon/PCL2#3374]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

已经出现了网络波动java下不全导致启动不了的Issue
#3370 （应该是）
可以考虑换成高校源

### 原因

换境内高校源不会出现网络波动下不全问题，只需要多写个解压就行
清华大学开源软件镜像站

JDK 17(32位)
https://mirrors.tuna.tsinghua.edu.cn/Adoptium/17/jre/x32/windows/OpenJDK17U-jre_x86-32_windows_hotspot_17.0.10_7.zip
JDK 17(64位)
https://mirrors.tuna.tsinghua.edu.cn/Adoptium/17/jdk/x64/windows/OpenJDK17U-jdk_x64_windows_hotspot_17.0.10_7.zip
JDK 8(64位)
https://mirrors.tuna.tsinghua.edu.cn/Adoptium/8/jdk/x64/windows/OpenJDK8U-jdk_x64_windows_hotspot_8u402b06.zip
JDK 8(32位)
https://mirrors.tuna.tsinghua.edu.cn/Adoptium/8/jdk/x32/windows/OpenJDK8U-jdk_x86-32_windows_hotspot_8u402b06.zip

荆楚理工和南大镜像源存档命名和清华大学基本一致
暂时没有其他镜像站有adoptium的存档（中科大只有DEB包）

荆楚理工镜像站域名:https://mirrors.jcut.edu.cn/
南京大学镜像站域名:https://mirror.nju.edu.cn/
境内服务器下载就别拉多线程下载器了，不然镜像站给请求炸了都有可能 ~重蹈12306覆辙？~

好处是很稳定（高校源耐造（或许？）），不会像Mojang那样不稳定和被墙
被撤销的条件只能是不维护和停止开源（几乎不可能）

让 Microsoft 分担下压力
https://aka.ms/download-jdk/microsoft-jdk-17.0.10-windows-x64.zip

**Comment by wuliaodexiaoluo** [comment]
（话说这算不算新功能）

**Comment by mc-124** [comment]
有没有linux的这些

**Comment by mc-124** [comment]
> （话说这算不算新功能）

大概…算吧

**Comment by allMagicNB** [comment]
等一下，这样有个问题，你说他Java如果更新了，那么这个网址就下载的就不是最新版了

**Comment by mc-124** [comment]
> 等一下，这样有个问题，你说他Java如果更新了，那么这个网址就下载的就不是最新版了

~~这个总能放个版本url列表到PCL2服务器了吧（~~

**Comment by allMagicNB** [comment]
我去他们交流区问了下，他们说管理员会不太乐意（

**Comment by WAAutoMaton** [comment]
个人建议是通过 bittorrent 或类似的 p2p 功能实现此类资源下载.

高校开源镜像站可能无力承担 jre 流量.

**Comment by Harry-Chen** [comment]
> 好处是很稳定（高校源耐造），不会像Mojang那样不稳定和被墙
被撤销的条件只能是不维护和停止开源（几乎不可能）

请不要滥用开源软件镜像站，我们会封禁所有的潜在异常流量。

**Comment by ZhiShengYuan** [comment]
请不要滥用开源软件镜像站，我们也会封禁所有的潜在异常流量。

**Comment by deep-dark-forest** [comment]
这……真的算是滥用吗

**Comment by allMagicNB** [comment]
> 这……真的算是滥用吗

开源镜像站的初衷只是为了提供方便，而不是给多用户的程序拿来DDos打进黑洞用的

**Comment by ZhiShengYuan** [comment]
> 这……真的算是滥用吗

至少我认为是?

**Comment by karuboniru** [comment]
> 这……真的算是滥用吗

建议留一个口子让用户自己选从哪儿下，硬编码地址只会重蹈 https://github.com/tuna/collection/issues/190 覆辙

**Comment by MCSteve123** [comment]
> > 这……真的算是滥用吗
> 
> 建议留一个口子让用户自己选从哪儿下，硬编码地址只会重蹈 [tuna/collection#190](https://github.com/tuna/collection/issues/190) 覆辙

PCL的下载源选项都是“尽量使用官方源”和“尽量使用镜像源”，在一方连接不佳时也会自己换源的啊

**Comment by wuliaodexiaoluo** [comment]
> PCL的下载源选项都是“尽量使用官方源”和“尽量使用镜像源”，在一方连接不佳时也会自己换源的啊

BMCL API 直接把java版本列表的url重定向到了 Mojang 服务器
等于说你怎么搞都是从Mojang下

**Comment by wuliaodexiaoluo** [comment]
> 等一下，这样有个问题，你说他Java如果更新了，那么这个网址就下载的就不是最新版了

就这个链接，并且Minecraft不要求最新版吧。。。。

**Comment by allMagicNB** [comment]
> > 等一下，这样有个问题，你说他Java如果更新了，那么这个网址就下载的就不是最新版了
> 
> 就这个链接，并且Minecraft不要求最新版吧。。。。

别人镜像站管理员都出来说不能了，你又干啥？
这个链接在镜像源更新时可能会失效

**Comment by wuliaodexiaoluo** [comment]
> 个人建议是通过 bittorrent 或类似的 p2p 功能实现此类资源下载.
> 
> 高校开源镜像站可能无力承担 jre 流量. 承担此类流量也并非开源镜像站的建设目的.

提议不错，但是P2P不太可能全在线就是了
~我也认为高校服务器有点悬~

**Comment by ZhiShengYuan** [comment]
> > 等一下，这样有个问题，你说他Java如果更新了，那么这个网址就下载的就不是最新版了
> 
> 就这个链接，并且Minecraft不要求最新版吧。。。。 拉个选项吧，反正你要真想用他们也拦不住你，可以考虑不用多线程下载

只是温馨提示：扛不住我们可能会直接给你们的下载抬走(like 403掉)

**Comment by wuliaodexiaoluo** [comment]
> 请不要滥用开源软件镜像站，我们也会封禁所有的潜在异常流量。

手贱多次补全的ban了就行，基本上就下一次不至于

**Comment by wuliaodexiaoluo** [comment]
> > > 等一下，这样有个问题，你说他Java如果更新了，那么这个网址就下载的就不是最新版了
> > 
> > 
> > 就这个链接，并且Minecraft不要求最新版吧。。。。 拉个选项吧，反正你要真想用他们也拦不住你，可以考虑不用多线程下载
> 
> 只是温馨提示：扛不住我们可能会直接给你们的下载抬走(like 403掉)

那我岂不是得被骂死，还是算了

**Comment by wuliaodexiaoluo** [comment]
> 只是温馨提示：扛不住我们可能会直接给你们的下载抬走(like 403掉)

b站不干了，我们没办法。。。。

**Comment by ZhiShengYuan** [comment]
> > 只是温馨提示：扛不住我们可能会直接给你们的下载抬走(like 403掉)
> 
> b站不干了，我们没办法。。。。 拉个服务器超级费钱，对于给你们造成的服务器压力，我们在只能尽力优化掉 ~（找其他人分摊伤害）~ 不过如果在预计范围内的话，可能长期不会用到（基本都备好了Java），加这个功能只是Mojang API不稳定

我出于个人的建议是:优先考虑集成类似P2P的实现，如果真的要使用镜像站也请不要将其排在第一的位置并且使用非浏览器的UA表明你们是自动程序

**Comment by Harry-Chen** [comment]
> > 请不要滥用开源软件镜像站，我们也会封禁所有的潜在异常流量。
> 
> 手贱多次补全的ban了就行，基本上就下一次不至于

我们并不关心单独的用户行为，但每个人下一次，集合起来的流量就是巨大的。

此软件的行为是不合适的，如果实施并影响到其他用户，各大教育镜像站均会加以封禁。请考虑使用商业镜像站。

**Comment by wuliaodexiaoluo** [comment]
> 我出于个人的建议是:优先考虑集成类似P2P的实现，如果真的要使用镜像站也请不要将其排在第一的位置并且使用非浏览器的UA表明你们是自动程序

基本上不会优先请求（或许是的），应该是优先 Mojang API，P2P看龙猫会不会写，请求默认使用VB的UA，应该不会改

**Comment by wuliaodexiaoluo** [comment]
考虑了一下，我觉得还是不太合适，我还是关了吧
