### ISSUE TITLE
给mojang java补全文件

### ISSUE THREAD

**Issue by mc-124** [Hex-Dragon/PCL2#3376]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

反正~~bugjump~~ mojang的java有文件列表，给它也做个补全文件应该也可以的吧…
识别哪个java是mojang java应该也没多难…
要忽略就忽略吧…这种反正也错误不多见

### 原因

像 #3370 就应该是下载的mojang java损坏，补全mojang java可以避免java文件损坏导致的错误

**Comment by allMagicNB** [comment]
直接增加个补全Java是不是更干脆（

**Comment by mc-124** [comment]
> 直接增加个补全Java是不是更干脆（

不不不，只有mojang的java有文件列表，别的java不一定找得着（

**Comment by mc-124** [comment]
> 有 hash 吗？

好像有

**Comment by LTCatt** [comment]
这个应该超出启动器的范畴了，并且绝大多数用户不会遇到这个问题，反而会拖慢启动
