### ISSUE TITLE
设置页面中法律信息仍然是2016-2023

### ISSUE THREAD

**Issue by heerxingen** [Hex-Dragon/PCL2#3377]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

Copyright @龙腾猫跃 2016 - 2023 ， AII Rights Reserved.
应为
Copyright @龙腾猫跃 2016 - 2024 ， AII Rights Reserved.
（对吧？）

### 重现步骤

1、点击设置
2、往下滚，然后点击法律信息
3、看其他信息第二行

### 日志与附件

无

**Comment by allMagicNB** [comment]
首先你的©打成了@
其次我感觉龙猫会把这个定义为优化

**Comment by heerxingen** [comment]
sorry我用的OCR（所以有点偏差
emmm好像你说的也有道理
但是似乎改不了了

**Comment by allMagicNB** [comment]
> sorry我用的OCR（所以有点偏差 emmm好像你说的也有道理 但是似乎改不了了

右上角三个点->Edit

**Comment by WForst-Breeze** [comment]
此为预期之外的问题，应为 bug

**Comment by allMagicNB** [comment]
> 此为预期之外的问题，应为 bug

但是我上次交的自动识别愚人节版本错误龙猫还换了个优化来着

**Comment by LTCatt** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/7f84ec62-23a4-4fc9-847f-cfe6b0c8b9d1)
你没更新吧

**Comment by allMagicNB** [comment]
>你没更新吧

![image](https://github.com/Hex-Dragon/PCL2/assets/116283787/7c4ce257-c393-44d6-beb3-5f806d422716)
~~龙猫你是不是早就改了但是忘了~~

**Comment by heerxingen** [comment]
我用的是快照版2.6.13（
刚才查了说是最新版啊（）
龙猫你是不是用的2.6.14.jpg

**Comment by WForst-Breeze** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/110760354/c6613577-2260-4c59-91e0-2cb4ad509c85)
![image](https://github.com/Hex-Dragon/PCL2/assets/110760354/77cffd56-6d6b-4561-be1e-9c646874c165)

**Comment by allMagicNB** [comment]
龙猫都已经修好了，这个Issue还有用吗……

**Comment by heerxingen** [comment]
那就close as completed?
虽然最新版明显没有修（）

**Comment by allMagicNB** [comment]
> 那就close as completed?
> 虽然最新版明显没有修（）

从龙猫发的IDE截图里已经看到修了

**Comment by iPodtouch6557** [comment]
也许是更改了但还未同步好

**Comment by LTCatt** [comment]
哦，改的版本还没上传过，那就当是因为这个 issue 修了吧（

**Comment by iPodtouch6557** [comment]
> 哦，改的版本还没上传过，那就当是因为这个 issue 修了吧（

6，幸存者偏差

**Comment by heerxingen** [comment]
> 哦，改的版本还没上传过，那就当是因为这个 issue 修了吧（

那这个isuue能给活跃橙吗.jpg
我的识别码是5807-9E91-E736-7CBE

**Comment by LTCatt** [comment]
你的解锁码：G+8Kf6iV1kWQLS/OASjIB2LeIy5aUXO0
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by heerxingen** [comment]
本回复用于重新解锁隐藏主题所以如果看到的话划走就可以了！
<img width="957" height="368" alt="Image" src="https://github.com/user-attachments/assets/32fbee22-7052-4597-8f40-7421e2b53581" />
