### ISSUE TITLE
添加 ipfs 等 p2p 网络支持用于下载 mc

### ISSUE THREAD

**Issue by NaHCO3-code** [Hex-Dragon/PCL2#3378]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

添加可选开启的 p2p 网络支持（如 ipfs），在 mc 官方源和第三方镜像源失效时，从 p2p 网络中拉取文件。

与此同时，可以将自己电脑内的文件提供给其他需要的玩家。

### 原因

最近 mcbbs 下载源关停，官方源不稳定，mc 下载困难。

很多人都有下载 mc 的需求，但碍于网络环境，下载十分困难。

**Comment by allMagicNB** [comment]
你这异想天开啊你

**Comment by deep-dark-forest** [comment]
~~这人的头像咋这么像你~~
Pcl是mc启动器，甚至连下载器都不是，我记得之前有关于自定义下载支持更多下载链接的都被拒了

**Comment by Pigeon0v0** [comment]
个人意见是去找 BMCLAPI 那边说说...
