### ISSUE TITLE
支持自定义下载源

### ISSUE THREAD

**Issue by ArgonTeam** [Hex-Dragon/PCL2#3381]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

在设置-启动器-版本列表获取中添加自定义下载源，更方便的下载Minecraft，而不会被缓慢的下载速度劝退

### 原因

MCBBS不是寄了吗，顺带把下载源也关了。能不能让爱好者自建BMCLAPI节点，然后使用自定义下载源更好的下载Minecraft.

**Comment by deep-dark-forest** [comment]
自行搭建下载源是不是需要啥服务器之类的东西
如果需要的话可能也没有人愿意用爱发电吧

**Comment by burningtnt** [comment]
直接用 BMCLAPI 即可，因此我才提出了 https://github.com/MCLF-CN/docs/issues/10 以提升 BMCLAPI 节点的收益

**Comment by deep-dark-forest** [comment]
> 直接用 BMCLAPI 即可，因此我才提出了 https://github.com/MCLF-CN/docs/issues/10 以提升 BMCLAPI 节点的收益

无经济能力的人看到广告也不会赞助的…等到各大启动器全部移除mcbbs源以后bmclapi的压力又要上涨，有炸的风险

**Comment by hejiehao** [comment]
> > 直接用 BMCLAPI 即可，因此我才提出了 [MCLF-CN/docs#10](https://github.com/MCLF-CN/docs/issues/10) 以提升 BMCLAPI 节点的收益
> 
> 无经济能力的人看到广告也不会赞助的…等到各大启动器全部移除mcbbs源以后bmclapi的压力又要上涨，有炸的风险

卖广告，广告提供商不就会给 93 哥钱吗？

**Comment by burningtnt** [comment]
> 无经济能力的人看到广告也不会赞助的…等到各大启动器全部移除mcbbs源以后bmclapi的压力又要上涨，有炸的风险

这里的广告不是给 BMCLAPI 的。
如果我是一个服务器的服主，那么这种广告就可以用于宣传我的服务器。

**Comment by zkitefly** [comment]
我在想，可以支持修改 API Root 吗

**Comment by LTCatt** [comment]
当前环境下面需求不大，如果真的有需求，也可以自己编译修改源码 =。=
