### ISSUE TITLE
mod给出错误

### ISSUE THREAD

**Issue by theGoBin** [Hex-Dragon/PCL2#3384]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

当搜索某些mod时，如Geode（晶洞），检索版本号1.19.1，将给出适用于1.19.2的版本并且不兼容

### 重现步骤

1、设定版本1.19.1，搜索Geode+/Enchanting Infuser
2、点击，可见可选1.19.1的版本标注了1.19.2的字样
3、下载并加载报错
![屏幕截图 2024-02-20 143902](https://github.com/Hex-Dragon/PCL2/assets/123287166/5397bcd8-2376-4707-ad87-2b6540cd4d5e)
![屏幕截图 2024-02-20 143934](https://github.com/Hex-Dragon/PCL2/assets/123287166/c18d605c-d5ef-4626-ad9b-1001b107e918)

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14340465/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14340467/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14340468/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14340469/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14340470/Log5.txt)

**Comment by allMagicNB** [comment]
你的Minecraft版本是1.19.1，这与PCL2怎么都扯不上关系吧，顶多改良下Mod安装

**Comment by WForst-Breeze** [comment]
这是模组作者的标记，与 PCL 无关
![image](https://github.com/Hex-Dragon/PCL2/assets/110760354/4df1cc83-ef1a-4d2d-8c38-0fb6d54e3202)
