### ISSUE TITLE
移除 Mod/整合包 下载页面的 MCBBS 跳转

### ISSUE THREAD

**Issue by liubanlaobanzhang** [Hex-Dragon/PCL2#3385]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

![image](https://github.com/Hex-Dragon/PCL2/assets/83630926/fbc243c8-30e1-40b2-899d-c3e0c53b4773)
MCBBS 宣布停运，是否考虑移除`转到MCBBS`按钮？

### 原因

一部分人还不知道MCBBS倒了
也许这样会好点？
或者省点请求量？
……

**Comment by allMagicNB** [comment]
本身就在移除了=。=

**Comment by liubanlaobanzhang** [comment]
我说的不是下载源
是MCBBS跳转按钮一类的……🤔
（虽然但是看到你这个我觉得我的Issue已经是废话了）

**Comment by liubanlaobanzhang** [comment]
额……那个……识别码：1334-157B-B695-283C（

**Comment by allMagicNB** [comment]
> 额……那个……识别码：1334-157B-B695-283C（

不好意思，优化没有活跃橙（笑
