### ISSUE TITLE
版本隔离时ip通用

### ISSUE THREAD

**Issue by misividkoukou** [Hex-Dragon/PCL2#3392]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

版本隔离时ip通用，且这个功能可以选择开启

### 原因

没有麻烦

**Comment by allMagicNB** [comment]
![774734469ae89a31e42d5e995637dd01](https://github.com/Hex-Dragon/PCL2/assets/116283787/61823673-3d91-4da8-af86-04a23a51c7a2)
只有你的光猫有唯一IP，其他都是NAT转换，也并不存在一个设备用两个IP（除非两张网卡）

**Comment by burningtnt** [comment]
你是指游戏内服务器 IP？

在 2024-02-21 11:04:18，misividkoukou ***@***.***> 写道：


检查项
我已在 Issues 页面 和 常见&难检反馈及问题列表 中搜索，确认了这一提案未被提交过。
我已查看 功能投票页面，确认了这一提案未在投票列表中。
我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……
描述

版本隔离时ip通用，且这个功能可以选择开启

原因

没有麻烦

**Comment by allMagicNB** [comment]
或者说我理解错了？你想要服务器列表独立存放？
但是这样也没有实际作用，除非你一天要玩十几个客户端版本要求不同的服务器

**Comment by misividkoukou** [comment]
就是多人游戏保存的游戏ip可以通用到每个版本

**Comment by WForst-Breeze** [comment]
即版本隔离同步服务器列表

**Comment by allMagicNB** [comment]
隔离版本而不隔离服务器列表？

**Comment by JingHai-Lingyun** [comment]
我记得之前有个版本隔离但不隔离存档的提议，被拒绝了来着

**Comment by LTCatt** [comment]
技术上无法实现
