### ISSUE TITLE
预设主页"Minecraft新闻"加载失败

### ISSUE THREAD

**Issue by L-circle-mc** [Hex-Dragon/PCL2#3393]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![屏幕截图 2024-02-21 084722](https://github.com/Hex-Dragon/PCL2/assets/134784879/451711c7-b87d-4032-a935-7c41400255ab)
![屏幕截图 2024-02-21 084758](https://github.com/Hex-Dragon/PCL2/assets/134784879/1ebbf226-b38b-4897-aad9-3e5eec434821)

### 重现步骤

在选择预设主页后回到"启动"栏，会提示自定义主页加载失败

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14353677/Log1.txt)

**Comment by allMagicNB** [comment]
暂时无法复现……

**Comment by WForst-Breeze** [comment]
@Light-Beacon 

这应是第三方主页问题，非 PCL 问题

**Comment by Light-Beacon** [comment]
已修复
