### ISSUE TITLE
{time}替换标记未正确补全

### ISSUE THREAD

**Issue by Ad-closeNN** [Hex-Dragon/PCL2#3395]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在`设置→游戏→高级启动选项→启动前执行命令`中设置`{time}`变量(PCL自带的显示时间的变量)后，PCL未自动补全，而是将{time}作为字符串输出了

假设填的是`echo {user} / {login} / Minecraft {name} ({version}) / %DATE% [{time}] / {uuid} / Java Path: {java} >> "{path}PCL\LaunchLog\LOGS.txt"`，在`LOGS.txt`里面除了`{time}`没有被PCL替换外，其他的变量全都被PCL替换了

LOGS.txt:
```shell
Ad_closeNN / 正版 / Minecraft rd-132211 (rd-132211) / 2024/02/21 周三 {time} / a7fada4946904e81b54e0809f6bbd74f / Java Path: C:\Program Files\Java\jre-1.8\bin\ 
```

假设填的是`mkdir {time}`(创建文件夹)，也没有正确创建
```shell
[14:52:12.120] [Launch] 正在执行全局自定义命令：mkdir {time}
```
而`mkdir {java}`是替换了java path
```shell
[14:53:04.337] [Launch] 正在执行全局自定义命令：mkdir C:\Program Files\Java\jre-1.8\bin\
```

![image](https://github.com/Hex-Dragon/PCL2/assets/103355026/9955e952-44f6-4268-a70e-da705ca45732)

### 重现步骤

1、点击设置
2、往下滚，然后点击`启动前执行命令`的输入框
3、输入与`{time}`相关的cmd语法
4、启动游戏，然后发现{time}并未正确补充

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14355502/Log1.txt) （PCL的）

[LOGS.txt](https://github.com/Hex-Dragon/PCL2/files/14355465/LOGS.txt) （自己的）

**Comment by allMagicNB** [comment]
测试用命令：
```
cd.. & echo {path} {minecraft} {verpath} {verindie} {java} {user} {login} {uuid} {name} {time} {version}>info.txt
```
执行完会在当前文件夹的上一层目录（即PCL2所在的目录）中生成`info.txt`

**Comment by Ad-closeNN** [comment]
> 测试用命令：
> 
> ```
> cd.. & echo {path} {minecraft} {verpath} {verindie} {java} {user} {login} {uuid} {name} {time} {version}>info.txt
> ```
> 
> 执行完会在当前文件夹的上一层目录（即PCL2所在的目录）中生成`info.txt`

D:\众 多 m c 版 本\1.12.1\ D:\众 多 m c 版 本\1.12.1\.minecraft\ D:\众 多 m c 版 本\1.12.1\.minecraft\versions\rd-132211\ D:\众 多 m c 版 本\1.12.1\.minecraft\versions\rd-132211\ C:\Program Files\Java\jre-1.8\bin\ Ad_closeNN 正版 a7fada4946904e81b54e0809f6bbd74f rd-132211 **{time}** rd-132211

这个time没有显示当前时间（15:41）

**Comment by LTCatt** [comment]
你的解锁码：eueybZ+oRm2V2HJeIdIm5O1YGiSUA70J
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by Ad-closeNN** [comment]
那个...PCL升级到2.6.14后不知道啥原因主题、微软登录信息没了，然后识别码也改了帮弄个新的解锁码吧qwq EC19-410C-3B4E-EFBC

<details>
<summary>新优化</summary>

额还有**当前的系统时间**建议改为**当前的系统日期、时间**
![image](https://github.com/Hex-Dragon/PCL2/assets/103355026/c69aa926-68a8-4dd5-ac64-fdf5b92ffb4b)
</details>

**Comment by LTCatt** [comment]
你的解锁码：Ol6jdKJqJNdwmvPX+89ZI84Z0g52vVQd
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
