### ISSUE TITLE
由于MCBBS关站，第三方登录：统一通行证的“查看简介”需替换或删除为新链接

### ISSUE THREAD

**Issue by Ad-closeNN** [Hex-Dragon/PCL2#3397]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

~~龙猫改一天Bug了休息下吧~~

在版本设置→设置→服务器→登录方式改为`第三方登录：统一通行证`
点击`查看简介`，发现跳转的是MCBBS的链接。但因为mcbbs关站，[链接](https://www.mcbbs.net/thread-729821-1-1.html)不可用，需将其改为新的链接（比如[石墨文档](https://shimo.im/)？）或直接将按钮删除（~~貌似不太好~~)。

网页时光机由于mcbbs的等级规则无法查看当时的[快照](https://web.archive.org/web/20230527042547/https://www.mcbbs.net/thread-729821-1-1.html)
![image](https://github.com/Hex-Dragon/PCL2/assets/103355026/cdcdb967-1f96-4713-a57f-a3b23bf879ef)

### 原因

因为MCBBS关站，链接失效

**Comment by allMagicNB** [comment]
删除或替换新链接……

**Comment by Ad-closeNN** [comment]
是的...因为edit多了怕吵到别人...
