### ISSUE TITLE
在个性化隐藏功能中，勾选“个性化”后，左下角提示需要更改

### ISSUE THREAD

**Issue by deep-dark-forest** [Hex-Dragon/PCL2#3399]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在个性化隐藏功能中，勾选“个性化”后，将左下角提示“改不回来了”改为“只能修改ini配置文件”

### 原因

这会给很多萌新带来困扰，都被吓的不敢点了（
同时，“改不回来了”也不是一种严谨的说法

**Comment by allMagicNB** [comment]
重新下载并不能根本地解决原因，修改ini配置文件才可以……

**Comment by deep-dark-forest** [comment]
哦，抱歉，我去改一下

**Comment by WForst-Breeze** [comment]
难道这样不会看起来更复杂更不敢点了吗（

换言之，这个警告的目的就是为了避免萌新好奇勾上之后改不回来的

**Comment by burningtnt** [comment]
“改不回来了”更有威慑力，能挡住不少不理解本功能的人

**Comment by allMagicNB** [comment]
有种“你不懂就别乱动”的感觉……

**Comment by deep-dark-forest** [comment]
> ### 检查项
> 
> - [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
> - [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。
> 
> ### 描述
> 
> 在个性化隐藏功能中，勾选“个性化”后，将左下角提示“改不回来了”改为“只能修改ini配置文件”
> 
> ### 原因
> 
> 这会给很多萌新打开困扰，都被吓的不敢点了（

**Comment by LTCatt** [comment]
暂不考虑更改 =。=
