### ISSUE TITLE
升级版本后识别码改变，微软账号登录信息、隐藏主题丢失

### ISSUE THREAD

**Issue by Ad-closeNN** [Hex-Dragon/PCL2#3404]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

**我知道这个Bug提交过（#3316 #1474），但是都埋到下面了不好意思再打扰3316 1474的反馈者们了**

从2.6.13升级到2.6.14，识别码被改变，微软账号登录信息丢失、隐藏主题
当尝试解锁神秘紫的时候与#3316 和#1474 的错误一模一样

### 识别码
2.6.14: EC19-410C-3B4E-EFBC
2.6.13 **及以下版本**: B29F-05CD-6000-91C3 (#3395有记录)

### 重现步骤

1、将PCL升级至2.6.14，发现显示了禁止分享的弹窗和微软登录信息、主题的丢失
2、尝试用Dev 0.4.4解锁神秘紫，重启PCL2.6.14后再次弹出禁止分享的弹窗
3、去到个性化发现神秘紫依然未解锁

### 日志与附件

很抱歉两个版本(2.6.13→2.6.14)升级时的Log已经被刷掉了

[Dev0.4.4Log.txt](https://github.com/Hex-Dragon/PCL2/files/14363160/Log.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14363161/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14363155/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14363157/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14363158/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14363159/Log5.txt)
[2.6.14隔离版.txt](https://github.com/Hex-Dragon/PCL2/files/14363176/2.6.14.txt)
[2.6.13隔离版.txt](https://github.com/Hex-Dragon/PCL2/files/14363178/2.6.13.txt)

**Comment by Ad-closeNN** [comment]
~~先睡一觉希望明早看到的不是`Close as not planned`:(~~

**Comment by LTCatt** [comment]
简单地说，之前生成识别码时，获取信息可能失败，导致识别码获取到的 “机器 ID” 全部都为 0，这会使得这部分机器有可能拥有相同的识别码。
2.6.14 修复了这个信息获取 Bug，现在获取到的 “机器 ID” 不会为全 0 了，但这也导致原本出 Bug 的机器在更新后识别码发生改变，这是不可避免的 :/

**Comment by Frepidation** [comment]
2.8.10还是有这个问题（估计lt不想解决了。。。）
