### ISSUE TITLE
更改对{date}、{time}替换标记的描述

### ISSUE THREAD

**Issue by allMagicNB** [Hex-Dragon/PCL2#3405]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

![image](https://github.com/Hex-Dragon/PCL2/assets/116283787/ff2f883b-e3d8-4d4e-aab2-b736e947c154)
目前的描述只有“当前的系统时间”，但是{date}替换标记指的是当前的系统日期，可以改为“当前的系统日期、时间”

### 原因

描述的不够准确，时间并不能指日期

**Comment by allMagicNB** [comment]
或者也可以直接让这俩独立，但是提示可能会超过窗口

**Comment by Ad-closeNN** [comment]
我想知道龙猫注意到了没有
![image](https://github.com/Hex-Dragon/PCL2/assets/103355026/d94c4af2-04c8-4c44-a1a9-2f8c89cb4e26)

**Comment by JingHai-Lingyun** [comment]
> 我想知道龙猫注意到了没有

应该没有，这个你应该像这样新开 Issue 的

**Comment by Ad-closeNN** [comment]
> > 我想知道龙猫注意到了没有
> 
> 应该没有，这个你应该像这样新开 Issue 的

睡得太晚，懒得开了
不过allmagicNB居然发现了这个得优化
