### ISSUE TITLE
下载器支持其它下载链接类型

### ISSUE THREAD

**Issue by MCSteve123** [Hex-Dragon/PCL2#3407]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

投票页面搜了“自定义下载”，没有

---
支持PCL下载此类下载链接：`https://adl.easebar.com/d/g/yhtj/c/lostlightcspc`，该链接本应下载萤火突击的exe文件，但实际上却下载了一个无后缀的html文件，而浏览器不会有这种问题
~如果要解析html文件一类的操作就别做了，龙猫已经够忙了~

### 原因

（示例）
这项优化让我可以更方便地下载。
如果没有这项优化，我每次都必须从浏览器下载，让操作变得很麻烦。

**Comment by allMagicNB** [comment]
后缀名改下试试；

**Comment by allMagicNB** [comment]
这是一个页面，并不是真正的下载链接

**Comment by Ad-closeNN** [comment]
好像还要解析一层吧？我从浏览器看确实是`https://adl.easebar.com/d/g/yhtj/c/lostlightcspc`这个在下载，而到IDM看是`https://h75na.gdl.easebar.com/LostLight_global_netease_20231215.exe`
![image](https://github.com/Hex-Dragon/PCL2/assets/103355026/d99cbb3d-f1c2-4c9f-beb4-6395f7b298c3)

**Comment by WForst-Breeze** [comment]
如果需要解析一层那就上个待处理好了，但感觉估计不会做

**Comment by allMagicNB** [comment]
不不不，这个网址是后面才跳转到下载链接的

**Comment by allMagicNB** [comment]
如果真的要下载的话，可以先让它跳转到下载链接，再复制下载链接给PCL2下载

**Comment by Ad-closeNN** [comment]
浏览器无法解析这个，那怎么获取下载直链
除了浏览器下载都是下载器下载了，那下载器能获取直链为什么还要PCL下载...

**Comment by allMagicNB** [comment]
> 浏览器无法解析这个，那怎么获取下载直链
> 除了浏览器下载，其他都是下载器下载了，那下载器能获取直链为什么还要PCL下载...

谁跟你讲这叫解析了？这是重定向，由网页重定向到下载网址。
再说，Edge浏览器对下载项右键可以复制网址，也没说一定要下载器啊

**Comment by Ad-closeNN** [comment]
那我删掉这个吧，chrome确实能复制下载链接
大意了，chrono下载器复制的居然还是https://adl.easebar.com/d/g/yhtj/c/lostlightcspc

**Comment by deep-dark-forest** [comment]
我记得几年前有个吵的热火朝天的issue讨论过这个问题，不过好像那个issue被删了

**Comment by Ad-closeNN** [comment]
> 我记得1年前有个吵的热火朝天的issue讨论过这个问题，不过好像那个issue被删了

网页时光鸡可以看吗

**Comment by deep-dark-forest** [comment]
#764 ？

**Comment by allMagicNB** [comment]
> #764？

不一样

**Comment by deep-dark-forest** [comment]
https://github.com/Hex-Dragon/PCL2/issues/764#issuecomment-1368643670

![Screenshot_20240221_131232.jpg](https://github.com/Hex-Dragon/PCL2/assets/131975043/4d293586-d44a-4768-80e2-de26ce0e3e60)

龙猫说过不会对自定义下载进行优化了吧……是我理解错了？

**Comment by allMagicNB** [comment]
> https://github.com/Hex-Dragon/PCL2/issues/764#issuecomment-1368643670
> 
> ![Screenshot_20240221_131232.jpg](https://github.com/Hex-Dragon/PCL2/assets/131975043/4d293586-d44a-4768-80e2-de26ce0e3e60)
> 
> 龙猫说过不会对自定义下载进行优化了吧……是我理解错了？

主题不一样（
我再看看……

**Comment by allMagicNB** [comment]
“自定义下载此前就接到过相同反馈，我已经表示过不会进行扩展了。”——LTCatt

**Comment by deep-dark-forest** [comment]
OK，close！
