### ISSUE TITLE
JDK16自动下载问题

### ISSUE THREAD

**Issue by PatrickChen608273** [Hex-Dragon/PCL2#3410]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在没有JDK16时启动高版本，JDK16下载安装完成之后仍然卡在获取Java步骤，需要取消然后再次启动游戏

### 重现步骤

1、安装一个高级版本，比如1.19.2
2、不安装Java 16，直接启动
3、选择自动下载Java
4、等待几分钟，在游戏 Java下拉框下面点自动搜索，可以看到已经有了，但是启动游戏界面还卡在获取 Java步骤，且等待很久也没有出现游戏窗口

### 日志与附件

日志中无法体现该问题

**Comment by allMagicNB** [comment]
谁跟你说日志没法体现了？

**Comment by Ad-closeNN** [comment]
更正一下小错误，是java17
![image](https://github.com/Hex-Dragon/PCL2/assets/103355026/3e4cf573-1cf7-40a6-9776-01187d712799)

**Comment by Ad-closeNN** [comment]
未复现成功，请上传日志
![image](https://github.com/Hex-Dragon/PCL2/assets/103355026/1bb7cd92-2f53-47ee-b54c-c48727831e22)

**Comment by PatrickChen608273** [comment]
有可能是因为快照版无此问题，公测版应该是有的

**Comment by allMagicNB** [comment]
> 有可能是因为快照版无此问题，公测版应该是有的

上传日志=。=
没有日志鉴定原因**无异于闭眼开车**

**Comment by Ad-closeNN** [comment]
？我就不信这跟PCL版本有关...
不过说实话我没开梯子下载java确实慢，我差点也怀疑下载不了
![image](https://github.com/Hex-Dragon/PCL2/assets/103355026/689cd041-61d0-4f43-9c2a-bb9696dc2d21)
![image](https://github.com/Hex-Dragon/PCL2/assets/103355026/a2df36e8-e7cf-4d74-a2e2-ab5e5da45890)
![image](https://github.com/Hex-Dragon/PCL2/assets/103355026/a72bf15e-d633-4ef6-b79f-0dc693189e94)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14374991/Log1.txt)

<details>
<summary>题 外 话</summary>
第一张image: 昨天晚上的蜜雪冰城限时回归
</details>

**Comment by wuliaodexiaoluo** [comment]
可能是因为带Mod启动慢了点，显示问题导致Author认为一直卡在获取Java，实际上已经在启动了（众所周知bugjump自1.17开始Minecraft启动巨慢无比，带Mod会加重这个问题）

**Comment by hejiehao** [comment]
> 可能是因为带Mod启动慢了点，显示问题导致Author认为一直卡在获取Java，实际上已经在启动了（众所周知bugjump自1.17开始Minecraft启动巨慢无比，带Mod会加重这个问题）

~~PCL2 怎么能欺骗我们呢？~~
