### ISSUE TITLE
关于模组列表显示

### ISSUE THREAD

**Issue by Beethoven1231** [Hex-Dragon/PCL2#3413]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

这个bug较为奇怪
这是我出问题的mod，合成冲突消除NoMoreRecipeConflict 的链接
MC百科：https://www.mcmod.cn/class/630.html
旧版CF：https://legacy.curseforge.com/minecraft/mc-mods/stimmedcow-nomorerecipeconflict/files
将这个Mod添加至Mod文件夹，发现PCl并未成功识别
![image](https://github.com/Hex-Dragon/PCL2/assets/122965323/5aeb57a5-5004-4c62-a8e2-4f32df381f03)
![image](https://github.com/Hex-Dragon/PCL2/assets/122965323/f89a6e18-7b2f-4192-8776-2a44f9a2a02f)
但CF桌面端识别出来了
![image](https://github.com/Hex-Dragon/PCL2/assets/122965323/3f171488-01a9-405e-a299-6b0b9a0aadb7)
不过这个mod本身好像也存在问题，就是当CF桌面端点进去，点击跳转网页时用新版打开就404了
![image](https://github.com/Hex-Dragon/PCL2/assets/122965323/f51a5bd9-9a66-49b7-a01f-3ce8cfee6e1b)

还有一个mod，叫ZeroCore，PCl成功识别，但并未显示其图标
![image](https://github.com/Hex-Dragon/PCL2/assets/122965323/1de133c5-14dc-47ca-879a-f6ac8a1d4c44)

### 重现步骤

无

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14382823/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14382824/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14382825/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14382827/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14382828/Log5.txt)

**Comment by deep-dark-forest** [comment]
#3208

**Comment by Beethoven1231** [comment]
> ~#3208~ 当我没说

啊？这俩不一样吧

**Comment by JingHai-Lingyun** [comment]
ZeroCore 我这里能显示图标
![image](https://github.com/Hex-Dragon/PCL2/assets/109946426/29866cfe-6fd7-4a5b-88bd-b3588f3a941e)

**Comment by allMagicNB** [comment]
你先看看HMCL和BakaXL能不能正常识别？

**Comment by allMagicNB** [comment]
或者说你把你使用的 Mod 发上来

**Comment by Beethoven1231** [comment]
[mod.zip](https://github.com/Hex-Dragon/PCL2/files/14383097/mod.zip)

**Comment by wuliaodexiaoluo** [comment]
ZeroCore 2 Mod 图标识别信息成功但图标未加载，复现成功

![图片](https://github.com/Hex-Dragon/PCL2/assets/160083863/32b37ede-b085-4fe9-91d5-696b9603d728)
![图片](https://github.com/Hex-Dragon/PCL2/assets/160083863/9172961b-51d7-44fd-8972-db2e13420cda)
![图片](https://github.com/Hex-Dragon/PCL2/assets/160083863/a70aa1a8-6f4d-48be-94be-7f59e34511ff)

但从CurseForge的搜索结果来看，我怀疑这玩意到底有没有图标
网络为有限连接，CurseForge可以链接，没有报错，运营商：中国移动

**Comment by wuliaodexiaoluo** [comment]
> NoMoreRecipeConflict 由于不存在新版 CurseForge / Modrinth 上，无法识别应该是意料中的行为
> 
> ZeroCore 我这里能显示图标

你说有没有一种可能，它指的是 ZeroCore2？
![图片](https://github.com/Hex-Dragon/PCL2/assets/160083863/ebbbaab9-ec7d-4af0-a9f9-2cc864eef881)
BakaXL无法加载图标，估计这个Mod本身就是没有图标的

第一个Mod，BakaXL也没有检索到相关信息，可以确认API没有对应没有信息

**Comment by JingHai-Lingyun** [comment]
那关了，这不是 PCL 的问题

**Comment by kong-que-dnf123** [comment]
算第三方吗（？）

**Comment by allMagicNB** [comment]
首先，Jar 文件下有一张`logo.png`是正常的图标……？
