### ISSUE TITLE
JVM参数长度限制

### ISSUE THREAD

**Issue by 596wjr** [Hex-Dragon/PCL2#3422]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

JVM参数有1000字符长度限制，无法输入很长的参数

### 原因

（修改过的示例）
这项优化让我可以更方便地启动qulit。
如果没有这项优化，我每次都必须用HMCL，让操作变得很麻烦。

**Comment by allMagicNB** [comment]
请等待PCL2对 Quilt 的支持

**Comment by zkitefly** [comment]
你想输入什么 JVM  参数，这么长？

**Comment by hejiehao** [comment]
这个描述跟原因有什么关系吗？

**Comment by hejiehao** [comment]
> 你想输入什么 JVM 参数，这么长？

classpath?

**Comment by 596wjr** [comment]
> 这个描述跟原因有什么关系吗？

我觉得有关系吧，pcl目前不支持qulit，启动qulit会崩溃，通过添加（修改）一些参数（或许）可以实现启动qulit端

**Comment by zkitefly** [comment]
这个问题应该是从 https://github.com/Hex-Dragon/PCL2/issues/3242#issuecomment-1953115385 引进的

或许应该解除 JVM 参数设置框的字符数限制？

看看龙猫怎么说

**Comment by hejiehao** [comment]
> > 这个描述跟原因有什么关系吗？
> 
> 我觉得有关系吧，pcl目前不支持qulit，启动qulit会崩溃，通过添加（修改）一些参数（或许）可以实现启动qulit端

发一下游戏崩溃报告？

**Comment by JingHai-Lingyun** [comment]
启动 Quilt 是支持的，只是不支持识别 Quilt 端和安装
请发送你的崩溃日志来帮助我们定位问题

**Comment by allMagicNB** [comment]
> 这个问题应该是从 [#3242 (comment)](https://github.com/Hex-Dragon/PCL2/issues/3242#issuecomment-1953115385) 引进的
> 
> 或许应该解除 JVM 参数设置框的字符数限制？
> 
> 看看龙猫怎么说

经证实，Release 2.6.13未限制字数，但Snapshot 2.6.14限制了字数为1000B

**Comment by 596wjr** [comment]
> 启动 Quilt 是支持的，只是不支持识别 Quilt 端和安装 请发送你的崩溃日志来帮助我们定位问题

https://596wjr.lanzouw.com/i70KV1p9vich
(跑题了吧

**Comment by wuliaodexiaoluo** [comment]
1000 - 188 = 812
我不明白是什么参数812字节都写不下

**Comment by wuliaodexiaoluo** [comment]
```
Suppressed: java.lang.NullPointerException: Cannot invoke "java.nio.file.Path.resolve(String)" because "gameDir" is null
```

你是不是 --gameDir参数传入了一个空值

**Comment by 596wjr** [comment]
> 启动 Quilt 是支持的，只是不支持识别 Quilt 端和安装 请发送你的崩溃日志来帮助我们定位问题



> > > 这个描述跟原因有什么关系吗？
> > 
> > 
> > 我觉得有关系吧，pcl目前不支持qulit，启动qulit会崩溃，通过添加（修改）一些参数（或许）可以实现启动qulit端
> 
> PCL2 支持启动 Quilt，请确认你没有安装其他模组。

我觉得吧，这个issue的关注点应该是JVM参数长度而不是qulit无法启动

**Comment by LTCatt** [comment]
提高到了 4000
