### ISSUE TITLE
没有Java时启动游戏未经用户同意就自动开始下载一部分Java

### ISSUE THREAD

**Issue by Ad-closeNN** [Hex-Dragon/PCL2#3425]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述
**虽然我不知道这是不是一个bug~~可能有意而为~~，但是这确实占用了我的硬盘空间(**

如题，当电脑没Java时启动游戏，会弹出是否下载Java的弹窗，但是没有点击`自动下载`一样会开始下载**一部分**Java，跟点击`自动下载`按钮一样。而到要手动你点“自动下载”的按钮的时候（也就是没有“下载速度 xxMB/s的时候），Java早已经下好了，存在
`C:\Users\$USERNAME$\AppData\Roaming\.minecraft\runtime\java-runtime-gamma-snapshot\bin`，点击“自动下载”后就会...~~额我也不知道应该是部署吧~~然后就直接启动游戏了

这对想自己安装别的java（比如zulu）非常不友好，因为你在一瞬间就少了那么几十MB的空间（

`都开始自动下载了何必显示这个弹窗 干脆直接写个弹窗提示条 写着“你的电脑上没有可用Java，PCL已开始自动下载Java`

![image](https://github.com/Hex-Dragon/PCL2/assets/103355026/a132857f-ba35-4371-aaae-159ee1bde0ee)

### 重现步骤

1、删掉你电脑上的所有java
2、下载随便一个mc版本（我用1.19.2测试的）
3、点击启动游戏
4、挂机 别点任何按钮
5、能看见PCL已经在开始下载Java了

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14394049/Log1.txt)

**Comment by Dave12138** [comment]
开了个沙盒复现了一下，发现纯净原版游戏不会触发，至少1.20.6、1.19.2、1.12.2不会
![1.20.6纯净](https://github.com/Hex-Dragon/PCL2/assets/35069593/9ad26dda-0775-4976-a239-747cd7d7b5f7)
有forge则会触发，fabric(1.19.2)不会
![1.12.2](https://github.com/Hex-Dragon/PCL2/assets/35069593/2e2c542d-9440-410d-a5c9-a9fc83a155f9)
（方式A会弹窗要求J8，所以上图是1.12.2）
<s>真神奇啊，好像和ad说的还不太一样</s>

**Comment by LTCatt** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/f35422e8-ee04-4f97-9b3e-070c02eaa7ba)
就反馈者提交的日志而言没有发现异常，是在点击确认之后才开始下载的。
截图中显示有下载速度是在下载资源文件，并非是在下载 Java。
如果有其他线索可以继续回复。

-------

@Dave12138 你的复现能传日志么（

**Comment by Dave12138** [comment]
如果没记错的话这👇应该是有/没有forge分别启动一次的日志
[LogUnexpectedDownloading.txt](https://github.com/Hex-Dragon/PCL2/files/15332332/LogUnexpectedDownloading.txt)

**Comment by LTCatt** [comment]
这个 log 里下载的是 MC 支持库文件，不是 java

**Comment by Dave12138** [comment]
> 这个 log 里下载的是 MC 支持库文件，不是 java

我也刚注意到其实自动下载Java根本不会在启动进度下一行显示速度——我的图和ad的图应该都是在下支持库。

可以推测一下发生了什么：ad删了java，新装游戏启动，提示没有java时点击自动下载，然后取消了启动（此时java还在下）。
随后再次启动，PCL又提示没有java（此时之前的java快下完了），可以看到显示的速度其实是在下支持库。

**Comment by LTCatt** [comment]
考虑到反馈者的 log 中是这样的：
1. 先确认下载了一次 Java
2. 取消启动
3. 重新启动，没有确认下载 Java

这时第一步要求下载的 Java 还没有下载完，所以反馈者误认为出了这个 bug……
考虑到这个情况，作为另一个 bug 完成了修复。

**Comment by Ad-closeNN** [comment]
新电脑麻烦再给一下谢谢啦
F006-AF44-77A0-1E58

**Comment by LTCatt** [comment]
你的解锁码：ziECUB3v/DZClJQOf6IV545Z4Dj0QbNl
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
