### ISSUE TITLE
issue检查项跳转mcbbs

### ISSUE THREAD

**Issue by Usercyk** [Hex-Dragon/PCL2#3426]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

啊就是提交bug的issue那里，有一个“下载其他启动器”的链接，跳转到mcbbs了……
建议改改模板
不知道其他模板有没有这个问题，未测试

### 重现步骤

1、点击new issue
2、点击下载或登录时卡住或失败
3、点击下载其他启动器

### 日志与附件

无

**Comment by Usercyk** [comment]
我也知道这个issue比较抽象但是（

**Comment by zkitefly** [comment]
改成什么链接比较好？

**Comment by deep-dark-forest** [comment]
要是有人能自己做个静态网页跳转到其他两家的官网就好了

**Comment by wuliaodexiaoluo** [comment]
> 要是有人能自己做个静态网页，里面有两个跳转到其他两家的官网的按钮就好了

GitHub Raw，或者GitHub Page？

**Comment by wuliaodexiaoluo** [comment]
> 改成什么链接比较好？

改成双链接得了

**Comment by Ad-closeNN** [comment]
~~干脆不要链接了，直接黑字不要链接~~

**Comment by deep-dark-forest** [comment]
> > 要是有人能自己做个静态网页，里面有两个跳转到其他两家的官网的按钮就好了
> 
> GitHub Raw，或者GitHub Page？
> 或者干脆拆分成两个链接

GitHub Page国内访问性很差，最好用gitee page，但是我还没成年，爱能莫助……

**Comment by iPodtouch6557** [comment]
~爱莫能助吧~

**Comment by wuliaodexiaoluo** [comment]
> GitHub Page国内访问性很差，最好用gitee page，但是我还没成年，爱能莫助……

我有Gitee账号，但是我感觉没必要了

**Comment by deep-dark-forest** [comment]
> > GitHub Page国内访问性很差，最好用gitee page，但是我还没成年，爱能莫助……
> 
> 我有Gitee账号，但是我感觉没必要 就为了下载开个GiteePage，还不如把下载重定向到Releases 至于GitHubPages，你都能上GitHub了，还怕这Pages访问不了，实在不行干脆双链接

额有道理，我去写个

**Comment by wuliaodexiaoluo** [comment]
> > > GitHub Page国内访问性很差，最好用gitee page，但是我还没成年，爱能莫助……
> > 
> > 
> > 我有Gitee账号，但是我感觉没必要 就为了下载开个GiteePage，还不如把下载重定向到Releases 至于GitHubPages，你都能上GitHub了，还怕这Pages访问不了，实在不行干脆双链接
> 
> 额有道理，我去写个

某Collaborator已经发了

**Comment by deep-dark-forest** [comment]
https://2launchers.vercel.app/

**Comment by zkitefly** [comment]
算了，还是弄成双链接吧（

**Comment by Ad-closeNN** [comment]
> https://2launchers.vercel.app/ 嗯我代码水平也就这样了

加个_blank（在新标签页打开）就更行了

**Comment by hejiehao** [comment]
> https://2launchers.vercel.app/ 嗯我代码水平也就这样了

你这个要两步呀

**Comment by wuliaodexiaoluo** [comment]
> > https://2launchers.vercel.app/ 嗯我代码水平也就这样了
> 
> 你这个要两步呀

两步就两步，要求不要太高，你没给人钱就不应该要求这么多，而且你不得看意愿吗

**Comment by Ad-closeNN** [comment]
要不去...discussion开讨论？

**Comment by wuliaodexiaoluo** [comment]
#3430

**Comment by hejiehao** [comment]
> > > https://2launchers.vercel.app/ 嗯我代码水平也就这样了
> > 
> > 
> > 你这个要两步呀
> 
> 两步就两步，要求不要太高，你没给人钱就不应该要求这么多，而且你不得看意愿吗

那怎么不直接在 Issue 模板里写 [下载 HMCL](https://hmcl.huangyuhui.net/) [下载 BakaXL](https://www.bakaxl.com/) 呢？
~~这个 https://2launchers.vercel.app/ 里面的 BakaXL 链接似乎写错了~~

**Comment by wuliaodexiaoluo** [comment]
> > > > https://2launchers.vercel.app/ 嗯我代码水平也就这样了
> > > 
> > > 
> > > 你这个要两步呀
> > 
> > 
> > 两步就两步，要求不要太高，你没给人钱就不应该要求这么多，而且你不得看意愿吗
> 
> 那怎么不直接在 Issue 模板里写 [下载 HMCL](https://hmcl.huangyuhui.net/) [下载 BakaXL](https://www.bakaxl.com/) 呢？ ~这个 https://2launchers.vercel.app/ 里面的 BakaXL 链接似乎写错了~

去讨论聊OK

**Comment by wuliaodexiaoluo** [comment]
@zkitefly 记得切Label

**Comment by hejiehao** [comment]
> @zkitefly 记得切Label

等龙猫合了先吧
~~不知道 Bot 在 Issue 标记成已完成后会有什么反应~~

**Comment by deep-dark-forest** [comment]
> > @zkitefly 记得切Label
> 
> 
> 
> 等龙猫合了先吧
> 
> ~~不知道 Bot 在 Issue 标记成已完成后会有什么反应~~

不对啊不应该在pr里关issue吗

**Comment by wuliaodexiaoluo** [comment]
> > @zkitefly 记得切Label
> 
> 等龙猫合了先吧 ~不知道 Bot 在 Issue 标记成已完成后会有什么反应~

Close As Completed

**Comment by hejiehao** [comment]
> > > @zkitefly 记得切Label
> > 
> > 
> > 等龙猫合了先吧 ~不知道 Bot 在 Issue 标记成已完成后会有什么反应~
> 
> Close As Completed 切处理中 PR管不了Issue

PR 合了就关了
