### ISSUE TITLE
允许`“联网更新”主页预设`对已输入的下载地址进行记忆

### ISSUE THREAD

**Issue by kong-que-dnf123** [Hex-Dragon/PCL2#3431]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

如图，现在的“联网更新”只有一个输入网址的地方，可通过加入**下拉框** 等方式对自己已输入的主页网址进行记忆
![image](https://github.com/Hex-Dragon/PCL2/assets/120994373/3364ab24-1592-45cb-833e-fe37991fdf00)

### 原因

在`自定义预设投稿区` 里面有**几个**我很~上心~ 但是没转正的预设，
目前情况下只能透过拷贝粘贴下载地址重新读取而不能快捷切换

**Comment by deep-dark-forest** [comment]
就是相当于自定义预设？

**Comment by kong-que-dnf123** [comment]
> 就是相当于自定义预设？

我觉得是更侧重于“存档”...

**Comment by LTCatt** [comment]
很少会使用到这个功能，暂不考虑，抱歉
