### ISSUE TITLE
自动打开官方启动器，并且自动下载一个游戏版本

### ISSUE THREAD

**Issue by XYLCS-Studio** [Hex-Dragon/PCL2#3437]
### 检查项

- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

首先自动打开官方启动器，然后自动下载一个MC JAVA游戏版本

### 原因

MCBBS不是寄了吗，于是我们都换到官方源，但这个官方语言也是非常的缓慢，但如果先到官方启动器下载一个MC Java版本，然后再在PCL下载的时候就会快了很多，如果能自动打开官方启动器，自动下载MC Java版本，那么这将让我们能够流畅下载任何游戏版本

**Comment by XYLCS-Studio** [comment]
这个可能很难写也很麻烦，所以呢，你也可以关闭此提案但是留个言，谢谢（

**Comment by allMagicNB** [comment]
没必要，这只是个玄学方法，没人证明原理
而且如果要下载的是离线用户呢？

**Comment by JingHai-Lingyun** [comment]
并没有实际证据证明打开了官方启动器就**一定**能正常下载
所以关了 Orz...

**Comment by XYLCS-Studio** [comment]
> 没必要，这只是个玄学方法，没人证明原理 而且如果要下载的是离线用户呢？

我试过，非常可以这虽然看起来像个玄学方法，但是真的有效 而且离线用户也能下。

**Comment by XYLCS-Studio** [comment]
怎么说呢，原理就是他把你添加了进了白名单里面类似的原理，然后它就能让你快速下载

**Comment by allMagicNB** [comment]
> 怎么说呢，原理就是他把你添加了进了白名单里面类似的原理，然后它就能让你快速下载

有办法证明吗？

**Comment by burningtnt** [comment]
说得好，但你很显然没写过一行代码，所以你这个基本上就是在瞎猜

**Comment by allMagicNB** [comment]
还是问问龙猫吧，咱也没有直接拒绝的权力，上面那位纯属乱搞

**Comment by deep-dark-forest** [comment]
> 怎么说呢，原理就是他把你添加了进了白名单里面类似的原理，然后它就能让你快速下载

让我来引用一条针对我的已删除评论…
![Screenshot_20240227_203953_com.huawei.petalmail.jpg](https://github.com/Hex-Dragon/PCL2/assets/131975043/aa76e06a-7a55-4c14-8f6b-d021c3cb242d)

**Comment by LTCatt** [comment]
更新后已经修复了
