### ISSUE TITLE
更改隐藏主题的链接(图片->MCBBS)

### ISSUE THREAD

**Issue by jinshastudios** [Hex-Dragon/PCL2#3446]
### 检查项

- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

MCBBS关站后解谜无法正常进行

### 重现步骤

推理过程网页无效

### 日志与附件

No Files

**Comment by deep-dark-forest** [comment]
给疑惑不解的人：
#3390
