### ISSUE TITLE
无法通过镜像源安装 Forge

### ISSUE THREAD

**Issue by LTCatt** [Hex-Dragon/PCL2#3447]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

注意这可能包含了多个 Bug？

下载 Forge 47.2.18失败
→ 下载 Mod 加载器主文件失败
→ 文件下载失败：C:\Users\10431\AppData\Local\Temp\PCL\Cache\Code\ForgeInstall-47.2.18_1486
远程服务器返回错误: (429) Too Many Requests。（https://bmclapi2.bangbang93.com/maven/net/minecraftforge/forge/1.20.1-47.2.18/forge-1.20.1-47.2.18-installer.jar）
获取到的片大小不一致：线程结果为 5974618 B，任务结果为 5908803B，起点为 5305387B。（https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.20.1-47.2.18/forge-1.20.1-47.2.18-installer.jar）
→ 文件 MD5 应为 68cbc4fb111526a56cc3090493b55d9d，实际为 3c3aafdb397208ef2c6e7f39320af1e9
   在 PCL.ModNet.NetFile.Merge() 位置 F:\Projects\Plain Craft Launcher 2\本体代码\Plain Craft Launcher 2\Modules\Base\ModNet.vb:行号 1328

### 日志与附件

[Log1 - 副本.txt](https://github.com/Hex-Dragon/PCL2/files/14453931/Log1.-.txt)

**Comment by allMagicNB** [comment]
文件校验出错了？大小也不对，MD5也不对

**Comment by deep-dark-forest** [comment]
```
远程服务器返回错误: (429) Too Many Requests
```
为啥会这样？

**Comment by zkitefly** [comment]
> ```
> 远程服务器返回错误: (429) Too Many Requests
> ```
> 为啥会这样？bmclapi的问题？

可能是 https://github.com/Hex-Dragon/PCL2/issues/3452

**Comment by zhongbai2333** [comment]
PCL2下载的（BMCLAPI）Forge安装器和Forge官网下载的安装器不一致，Forge官网下载的安装器比PCL2下载的安装器多两个选项，以下是截图：
PCL2版本：
![bfbdacdaafa6cb9d8f27bdb7aeedd91f](https://github.com/Hex-Dragon/PCL2/assets/54356787/5f9c9138-91f0-41ee-961c-031fa5a522f5)
官网版本：
![06a2c4eb3c6767c2d2db36cd34709300](https://github.com/Hex-Dragon/PCL2/assets/54356787/be23c875-32ce-42a9-8fd1-f9c40e27edcc)

**Comment by zkitefly** [comment]
改文件的原因可能是：

![image](https://github.com/Hex-Dragon/PCL2/assets/64117916/318e2e6c-a4e6-453b-8d6c-45ccd4a3157b)

**Comment by deep-dark-forest** [comment]
额，是forge把bmclapi给改了还是forge改了bmclapi没跟上

**Comment by burningtnt** [comment]
> 额，是forge把bmclapi给改了还是forge改了bmclapi没跟上

Forge 改了，但 BMCLAPI 没同步

**Comment by zkitefly** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/64117916/59499718-5705-498f-b509-7902940f9418)

![image](https://github.com/Hex-Dragon/PCL2/assets/64117916/4129ab04-816f-4a10-8b11-5b67888c125e)

**Comment by LTCatt** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/480553b6-c46c-450f-add0-1ac853aebe8e)
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/edeea84b-26af-493a-8cc1-3d0ca926959a)

确认是 BMCLAPI 的 Forge 没更新导致 @bangbang93

**Comment by zkitefly** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/64117916/1f7b8e2b-bcc5-4997-85ac-f1f5025bb627)

节点应该同步了

**Comment by bangbang93** [comment]
> ![image](https://private-user-images.githubusercontent.com/40348278/309289417-480553b6-c46c-450f-add0-1ac853aebe8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzMDMzODQsIm5iZiI6MTcwOTMwMzA4NCwicGF0aCI6Ii80MDM0ODI3OC8zMDkyODk0MTctNDgwNTUzYjYtYzQ2Yy00NTBmLWFkZDAtMWFjODUzYWViZThlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDE0MjQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwMGQ0N2UzNDdkOTE1MzliZmYwN2ZhZGRmODhiY2IwM2VjZGFlNGM0OGRkMDkyNDVkZGMxMzdmY2EzNmYzNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2RwqksJt18S2OSuJ59SYDKR-CA6QeEvNKwEuJ920P7U) ![image](https://private-user-images.githubusercontent.com/40348278/309289462-edeea84b-26af-493a-8cc1-3d0ca926959a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzMDMzODQsIm5iZiI6MTcwOTMwMzA4NCwicGF0aCI6Ii80MDM0ODI3OC8zMDkyODk0NjItZWRlZWE4NGItMjZhZi00OTNhLThjYzEtM2QwY2E5MjY5NTlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDE0MjQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxODc5N2FhZDBhMzgzOWU3MjQ4OTUwMzUzYzhjODk0MWQzZDQxNmIzYmNjNmU4MjcwMzJhZDNkYWJhZWVmMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4tyJmMYxphH-MAFjn91Slb-qePgxPB0aM_eikWrGSMI)
> 
> 确认是 BMCLAPI 的 Forge 没更新导致 @bangbang93

40位是个sha1，你跟md5能对上那不就有鬼了

**Comment by zkitefly** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/64117916/47706027-32cc-4eae-aa68-3fbdd121df52)

**Comment by hamiguatang** [comment]
为什么我用HMCL就安装成功了？？

**Comment by allMagicNB** [comment]
> 为什么我用HMCL就安装成功了？？

BMCLAPI 分配的节点不同

**Comment by zkitefly** [comment]
> 为什么我用HMCL就安装成功了？？

因为 HMCL 不对下载下来的 installer 文件进行校验，直接用（

**Comment by Jiahongoffical** [comment]
补充：”尽量使用官方源”设置中也存在此问题

**Comment by LTCatt** [comment]
BMCLAPI 同步应该已经完成了，后续安装失败可能是其他的原因，见 #3462

**Comment by LTCatt** [comment]
依然有一个镜像源没有同步完，据 bangbang 说等一天它再次同步就彻底好了
