### ISSUE TITLE
Minecraft出现错误

### ISSUE THREAD

**Issue by Tamato0** [Hex-Dragon/PCL2#3448]
### 检查项

- [ ] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃基本不是 PCL 的原因，请 **不要** 提交反馈。你可以在论坛或社区找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用 HMCL 启动，HMCL 没有出现问题。** 如果 HMCL 也无法启动就不是 PCL 导致的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

启动PCL时出现Minecraft出现错误窗口

### PCL 错误报告、日志与附件

[debug.log](https://github.com/Hex-Dragon/PCL2/files/14454589/debug.log)
[latest.log](https://github.com/Hex-Dragon/PCL2/files/14454594/latest.log)
[PCL 启动器日志.txt](https://github.com/Hex-Dragon/PCL2/files/14454596/PCL.txt)
[游戏崩溃前的输出.txt](https://github.com/Hex-Dragon/PCL2/files/14454597/default.txt)

**Comment by zkitefly** [comment]
怎么日志是空的？

还有，建议尝试使用 hmcl 等其他启动器测试是否和日志表现的错误一致，如果也报错，将该启动器日志日志上传

**Comment by Tamato0** [comment]
[PCL 启动器日志.txt](https://github.com/Hex-Dragon/PCL2/files/14456023/PCL.txt)
我放了新的日志，hmcl是可以正常启动的

**Comment by Tamato0** [comment]
已解决，文件命名为中文字符问题
