### ISSUE TITLE
[BUG] 更新 PCL 之后，之前所有解锁的隐藏主题已被重置

### ISSUE THREAD

**Issue by SuoHouDaiShi** [Hex-Dragon/PCL2#3451]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

<del>我不好说</del>
将 PCL 内测版从 2.6.10 更新到 2.6.14 后，所有解锁过的隐藏主题会被重置……
<del>还好不是主力机</del>

另外：
能申请理赔解锁的主题吗？（

### 重现步骤

1.准备 2.6.10 内测版的 PCL，然后立即更新 PCL 到 2.6.14
2.重新启动 PCL，延迟出现，启动后正版账户登录信息被重置，解锁的主题被重置
3.BUG 出现

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14457044/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14457045/Log2.txt)

**Comment by JingHai-Lingyun** [comment]
#3404 
> 简单地说，之前生成识别码时，获取信息可能失败，导致识别码获取到的 “机器 ID” 全部都为 0，这会使得这部分机器有可能拥有相同的识别码。
2.6.13 在此后热更新了一个版本，修复了这个信息获取 Bug，现在获取到的 “机器 ID” 不会为全 0 了，但这也导致原本出 Bug 的机器在更新后识别码发生改变，这是不可避免的，同时也导致了 #3316……
所以，这确实没办法 :/ —— LTCatt

**Comment by SuoHouDaiShi** [comment]
好好好
