### ISSUE TITLE
部分高校源不允许使用浏览器 UA 直接下载

### ISSUE THREAD

**Issue by LTCatt** [Hex-Dragon/PCL2#3452]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

部分高校源不允许使用浏览器 UA 直接下载，导致游戏下载失败。

**Comment by 8MiYile** [comment]
你小子的UA这么奇葩 难怪会不让下载 哪怕是 `PCL2/x.x.x` 就这样写 就行了
