### ISSUE TITLE
Version Check：线程执行失败：索引超出范围

### ISSUE THREAD

**Issue by Const001** [Hex-Dragon/PCL2#3453]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

提示，点击取消后不加载游戏列表

### 重现步骤

1.拷贝到U盘
2.运行

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14459416/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14459417/Log2.txt)

[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14459420/Log5.txt)

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14459418/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14459419/Log4.txt)
![image](https://github.com/Hex-Dragon/PCL2/assets/99626739/5f926739-4e7e-4522-b253-b65c90e81449)

**Comment by allMagicNB** [comment]
打开下调试模式再尝试复现？

**Comment by deep-dark-forest** [comment]
请更改标题

**Comment by Silverteal** [comment]
问题最早出现在`Log5.txt`，5432四个日志文件兼有问题。
错误的上下文位于`[Loader] 加载器 Minecraft Version List 状态改变：Finished`后

**Comment by LTCatt** [comment]
由于没人能复现先关了，之后有其他人复现再说
