### ISSUE TITLE
在Mod管理再次按下Ctrl+A后取消全选

### ISSUE THREAD

**Issue by Ad-closeNN** [Hex-Dragon/PCL2#3454]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

如题，`版本设置`→`Mod管理`里面，按下Ctrl+A即可全选，但是**没法**再次按下Ctrl+A来取消全选，只能去点**取消选择**才能退出全选。希望在`版本设置`→`Mod管理`里面按下Ctrl+A全选后，再次按下Ctrl+A能取消全选。

### 原因

#2334 为我们带来了更方便的Mod全选功能
但是...没有再次按下Ctrl+A以取消全选的功能
~~有点难受~~

**Comment by allMagicNB** [comment]
没必要喽，刷新一下就可以直接取消了

**Comment by JingHai-Lingyun** [comment]
文件资源管理器的操作也是只有 Ctrl + A 选中全部，并不存在再按一次取消全选的功能
挂着看看吧，但我感觉大概率不会做

**Comment by deep-dark-forest** [comment]
没有任何作用，取消全选不比全选简单多了，~~毕竟前者可以退出重进~~
