### ISSUE TITLE
给 MyTextButton 加下划线

### ISSUE THREAD

**Issue by iPodtouch6557** [Hex-Dragon/PCL2#3455]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

自从换了新新闻主页构建器，每次都得愣一秒才反应过来。对比太小了，在某些场合不认真看会被误以为是正文
<img width="190" alt="image" src="https://github.com/Hex-Dragon/PCL2/assets/118656946/92e8881d-bb26-44b4-a069-6a7ed73ba425">

### 原因

这项优化让我可以更方便地观看文本按钮
如果没有这项优化，我每次都必须得盯着看一会

**Comment by LTCatt** [comment]
可以修改 TextBlock 属性加下划线，PCL 中它用于部分按钮，不好加下划线
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/7a31f857-d7b8-4a26-9d05-3a361adae6b5)

**Comment by iPodtouch6557** [comment]
那好吧，我去找第三方……
