### ISSUE TITLE
帮助页面 完善PCL帮助库的使用GitHub Desk获取帮助库

### ISSUE THREAD

**Issue by shiyang0510** [Hex-Dragon/PCL2#3456]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在【更多】-【启动器】-【参与完善PCL帮助库】-【使用GitHub Desk获取帮助库】打开会出现错误
![QQ截图20240301231032](https://github.com/Hex-Dragon/PCL2/assets/125178599/3fd83165-d44d-4166-95a4-99f1e06d04d7)

### 重现步骤

1、点击【更多】
2、点击【启动器】
3、点击【参与完善PCL帮助库】
4、点击【使用GitHub desktop获取帮助库】
5、会出现报错行号“7” 行位置“150”

### 日志与附件

![Uploading QQ截图20240301231032.png…]()

**Comment by shiyang0510** [comment]
[Uploading Log1.txt…]()

**Comment by shiyang0510** [comment]
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14462860/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14462861/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14462862/Log5.txt)

**Comment by shiyang0510** [comment]
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14462869/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14462870/Log2.txt)

**Comment by shiyang0510** [comment]
有活力橙么 BFC3-B7F2-B46C-DB1A

**Comment by shiyang0510** [comment]
有活力橙么awa

**Comment by allMagicNB** [comment]
> 有活力橙么awa

请发送识别码

**Comment by shiyang0510** [comment]
BFC3-B7F2-B46C-DB1A

**Comment by SYBass** [comment]
> > 有活力橙么awa
> 
> 请发送识别码
BFC3-B7F2-B46C-DB1A

**Comment by LTCatt** [comment]
你的解锁码：9ERMkJFP4Pz9BvO1TghkYQXl7P/Q09HZ
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by SYBass** [comment]
> 你的解锁码：9ERMkJFP4Pz9BvO1TghkYQXl7P/Q09HZ 在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

谢谢龙猫大大！
