### ISSUE TITLE
2024.03.02使用pcl2时发现

### ISSUE THREAD

**Issue by pawnmaker** [Hex-Dragon/PCL2#3460]
### 检查项

- [ ] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

游戏安装失败
→ 下载 Forge 36.2.39失败
→ 下载 Mod 加载器主文件失败
→ 文件下载失败：C:\Users\ASUS\AppData\Local\Temp\PCL\Cache\Code\ForgeInstall-36.2.39_935
https://bmclapi2.bangbang93.com/maven/net/minecraftforge/forge/1.16.5-36.2.39/forge-1.16.5-36.2.39-installer.jar
https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.16.5-36.2.39/forge-1.16.5-36.2.39-installer.jar
→ 文件 SHA1 应为 7cc2776cf1ed2e1fdeda1a6543bdcd2ef76631bd，实际为 7af595ae043ead57b00bb042d253fdfdcfc7e055
   在 PCL.ModNet.NetFile.Merge()

### 重现步骤

1、点击下载-整合包-Jetpack Cat
2、点击安装

ps：单独在curseforge网站上下载整合包v4.2，拖拽到pcl2安装同样也出现此类现象，但该问题只出现了3月2日上午，前一天直接下载安装没有出现问题。

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14467878/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14467879/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14467880/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14467881/Log4.txt)

**Comment by allMagicNB** [comment]
#3447

**Comment by JingHai-Lingyun** [comment]
看起来是 #3447？

**Comment by pawnmaker** [comment]
尝试过先安装1.16.5，再安装forge36.2.39，显示无法下载。同样尝试直接1.16.5+forge36.2.39，但依旧无法安装成功

**Comment by Ad-closeNN** [comment]
遇到了(
![image](https://github.com/Hex-Dragon/PCL2/assets/103355026/938e25e8-e039-4cbb-bfa8-0d80c85c8e58)

**Comment by zkitefly** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/64117916/9e8fb858-6a54-498c-a957-abf0b1488705)

**Comment by qsgry** [comment]
遇到了
![Uploading {6733BBD7-3590-4f24-AA2B-79EFBAE03CE3}.png…]()

**Comment by pawnmaker** [comment]
> ![image](https://private-user-images.githubusercontent.com/64117916/309437959-9e8fb858-6a54-498c-a957-abf0b1488705.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzNTQ0NDIsIm5iZiI6MTcwOTM1NDE0MiwicGF0aCI6Ii82NDExNzkxNi8zMDk0Mzc5NTktOWU4ZmI4NTgtNmE1NC00OThjLWE5NTctYWJmMGIxNDg4NzA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAyVDA0MzU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyYmU5YzAzY2UzOTg0N2MyNDlkMmYwNjdkM2RlYjE0MTYwZDk5YmZmOGNlY2NkN2I3N2RjM2Y1NTFkYTU2NDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qISEook26c9ZUwdyrUPVbKKGpwzwAjrUmSryhuwi-tU)
> 
> 奇怪，不应该啊

刚才尝试了其他版本，同样安装不了froge，同时发现pcl2没有之前froge的推荐版本

**Comment by burningtnt** [comment]
别急别急，BMCLAPI 那边在同步，现在压力很大。请大家耐心等待，错峰下载

**Comment by pawnmaker** [comment]
14:59汇报，现在可以正常下载MOD加载器，但是无法安装MOD加载器（方式A），在站内暂时没有找到解决方法，是否还是因为同步的原因？

**Comment by LTCatt** [comment]
后转 #3462

**Comment by allMagicNB** [comment]
> 后转 #3462

@LTCatt 不对啊这个只是单抽的下载出错
