### ISSUE TITLE
自定义主页的教学文件中“事件 4：其他事件类型”一段没有换行

### ISSUE THREAD

**Issue by GCatMew000** [Hex-Dragon/PCL2#3461]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

为“事件 4：其他事件类型”一段添加 `TextWrapping="Wrap"`

### 原因

没有换行的话要把窗口拉很大（其实也没有多大）才能看完整
![屏幕截图 2024-03-02 112240](https://github.com/Hex-Dragon/PCL2/assets/161859603/e1180273-95ec-4746-99b5-922ff957dfb9)
![屏幕截图 2024-03-02 112351](https://github.com/Hex-Dragon/PCL2/assets/161859603/fb4420f0-0966-4b1b-bc6a-1d37596e08f0)

**Comment by allMagicNB** [comment]
你应该去帮助库提交 Issue……

**Comment by Ad-closeNN** [comment]
应该去帮助库提交吧?
有能力的话提交pr就行（工作量其实没多大）

**Comment by GCatMew000** [comment]
ok

**Comment by allMagicNB** [comment]
不对啊，你直接到帮助库里面看不得了？

**Comment by LTCatt** [comment]
在帮助库下开 issue

**Comment by WorldHim** [comment]
> 在帮助库下开 issue

生成的教学文件 源文件在本仓库吧？

**Comment by allMagicNB** [comment]
> > 在帮助库下开 issue
> 
> 生成的教学文件 源文件在本仓库吧？ #3475

![image](https://github.com/Hex-Dragon/PCL2/assets/116283787/f7431d74-0679-48ac-89e7-19653a2a8181)
帮助库也有，还用了个第三方 CDN https://cdn.jsdelivr.net/gh//LTCatt/PCL2Help@latest/个性化/XAML%20格式.xaml
