### ISSUE TITLE
无法安装 Forge

### ISSUE THREAD

**Issue by Frenqy** [Hex-Dragon/PCL2#3462]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

 安装1.18.2+Forge40.2.9及以上时稳定出现，已测试HMCL能正常安装，已测试java8和java17均报错

部分日志截图:
![image](https://github.com/Hex-Dragon/PCL2/assets/28777951/fc318a89-dc04-4e58-8bda-cb509b014ced)

### 重现步骤

1、下载界面选择1.18.2并选择forge40.2.9或以上版本进行安装

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14467931/Log1.txt)

**Comment by allMagicNB** [comment]
#3447

**Comment by LTCatt** [comment]
并非 #3447 ，reopen

**Comment by allMagicNB** [comment]
~~误判了~~

**Comment by LTCatt** [comment]
Forge 修改了安装方法，导致 @bangbang93 大佬的 ForgeInstaller 炸了，等待第三方修复

**Comment by LTCatt** [comment]
将发布紧急更新修复此问题
