### ISSUE TITLE
使用 Java 8 启动 MC 1.12.2- 时窗口大小有误

### ISSUE THREAD

**Issue by ZS2147483647** [Hex-Dragon/PCL2#3463]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在高分辨率下(3200*2000)jre8加载的较低版本的游戏界面大小会出现问题
1.测试环境:win11专业版26063
2.分辨率如上,缩放比例为200%
3.所使用jre8(8.0.351),jdk17(17.0.5)为甲骨文官网下载的
3.经测试,1.12.2,1.11.2,1.10.2,1.9.2,1.8.2,1.7.2,1.6.2大小为设置大小的2倍(各边长度,如果是面积的话就是4倍),jdk17为正常大小
   1.13.2及以上无此问题
   1.0,1.1,1.2.2,1.3.2,1.4.2,1.5.2无法使用jdk17启动,使用jre8启动无此问题

### 重现步骤

启动游戏
观察界面大小
切换jdk17
再次观察
切换版本,重复操作

### 日志与附件

稍后上传
详见#658 和#856

**Comment by ZS2147483647** [comment]
[Uploading Log1.txt…]()

**Comment by ZS2147483647** [comment]
经过测试,hmcl启动1.12.2时无此问题

**Comment by ZS2147483647** [comment]
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14468039/Log1.txt)

**Comment by ZS2147483647** [comment]
这是个老bug,我曾经提交过但由于没有足够的测试导致了高版本出现了其他问题于是回滚,这次进行全面测试,可以进行针对性调整

**Comment by zkitefly** [comment]
有点没看懂，来几张图？（

**Comment by LTCatt** [comment]
如果 PCL 会触发，HMCL 不会触发的话，上传一下 PCL 和 HMCL 对应的启动脚本？

**Comment by ZS2147483647** [comment]
呃，抱歉，我好像不太知道您说的是哪个文件，麻烦您告诉我一下具体操作，谢谢😜

**Comment by ZS2147483647** [comment]
呃，抱歉，我好像不太知道您说的是哪个文件，麻烦您告诉我一下具体操作，谢谢😜

**Comment by ZS2147483647** [comment]
我需要文件的相对路径和具体名称，另外，是只要1.12.2一个版本的还是所有版本都要

**Comment by JingHai-Lingyun** [comment]
启动脚本获取方式：
1. PCL：指定版本 -> 左下角版本设置 -> 高级管理 -> 导出启动脚本
2. HMCL：指定版本 -> 左侧点进去 -> 左下角管理 -> 生成启动脚本
均会询问你将脚本保存到哪里去，找一个自己好找的位置就行

**Comment by burningtnt** [comment]
猜测是由于你装了两个 Java 8，而两款启动器分别用了不同 Java 启动导致的……

**Comment by ZS2147483647** [comment]
是这样的，pclJava选择界面里有2个Java，而hmclJava选择界面里有4个Java

**Comment by ZS2147483647** [comment]
这4个Java分别有两个8和17，看起来每两个8和1 是一模一样的

**Comment by ZS2147483647** [comment]
我会在21:00之前完成启动脚本上传，但是受到开学影响，还望在明天上午之前告知我所有应该做的，谢谢

**Comment by ZS2147483647** [comment]
有人在悄悄喵我欸

**Comment by ZS2147483647** [comment]
兄弟们,我需要帮助,我的Java好像出了些问题
![image](https://github.com/Hex-Dragon/PCL2/assets/121028009/bd0b035c-3353-4de4-b918-c0055f090660)
![image](https://github.com/Hex-Dragon/PCL2/assets/121028009/d3c9f91d-234f-4822-92dc-593857ebd9f7)

![image](https://github.com/Hex-Dragon/PCL2/assets/121028009/d248705a-503b-4457-a01a-dadf6d5f8c7b)
![image](https://github.com/Hex-Dragon/PCL2/assets/121028009/31689883-29e7-42c5-a980-6e8cc35e4e46)
但是我在C盘根本没找到那个Java的源文件,他好像是凭空出现的

**Comment by ZS2147483647** [comment]
1.12.2hmcl(使用hmcl最新版v3.5.5.236)使用无根和正常kdk17会出现相反的问题(大小缩小为0.5倍)
[启动脚本.zip](https://github.com/Hex-Dragon/PCL2/files/14469330/default.zip)

**Comment by ZS2147483647** [comment]
我猜hmcl应该是考虑到这个问题但是一刀切了,pcl是被我发现之后一刀切了然后回滚

**Comment by ZS2147483647** [comment]
> 1.12.2hmcl(使用hmcl最新版v3.5.5.236)使用无根和正常kdk17会出现相反的问题(大小缩小为0.5倍) [启动脚本.zip](https://github.com/Hex-Dragon/PCL2/files/14469330/default.zip)

熟悉的配方同样的味道,和我上次提交这个bug调整后一模一样

**Comment by burningtnt** [comment]
基本上已经破案了，就是 Java 选择不一样的问题……

你这个 Java 安装也是挺恐怖的。JAVA_HOME 里面又套了一个 JRE8 装了个新 Java

**Comment by ZS2147483647** [comment]
> 基本上已经破案了，就是 Java 选择不一样的问题……
> 
> 你这个 Java 安装也是挺恐怖的。JAVA_HOME 里面又套了一个 JRE8 装了个新 Java
部分正确，不过问题是pcljre8异常，jdk17正常，hmcl所有jre8正常 所有jdk17异常

**Comment by ZS2147483647** [comment]
大家参看#658和#856就知道怎么回事了

**Comment by allMagicNB** [comment]
你这不就是DPI自动缩放吗？

**Comment by ZS2147483647** [comment]
> 你这不就是DPI自动缩放吗？

并不是所有的版本会这样，应该和Java有关

**Comment by LTCatt** [comment]
根据测试，这个 bug 并不是对所有 Java 8 有效。
JRE 8u51~8u192 没有问题，JRE 8u221~8u322 有问题，JRE 10 没有问题。
现在把对应的修复范围限定在了 JRE 8u200+……
