### ISSUE TITLE
修正“离线皮肤”选项的提示

### ISSUE THREAD

**Issue by allMagicNB** [Hex-Dragon/PCL2#3464]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

（忽略一下做测试时用的龙猫的皮肤）
![image](https://github.com/Hex-Dragon/PCL2/assets/116283787/d77fbd3d-2ed5-4d40-a48f-e2f3a522c74b)
此处`离线皮肤`中的提示中并未提及`正版皮肤`选项也不保证有效，启动 1.19.2+ 后才会发现
![image](https://github.com/Hex-Dragon/PCL2/assets/116283787/19c2e4bf-2763-4e3c-b482-7da6e724fcf9)

还有个问题，1.19.2 这个版本是支持自定义皮肤的……

可以考虑改为`由于技术原因，除 随机 外的其他选项暂时仅保证对 1.19.2 及以前的版本有效！ `

### 原因

修改描述错误，避免让小白还以为能用（

**Comment by allMagicNB** [comment]
算了还是等龙猫受理后再让龙猫换`Label`吧（

**Comment by LTCatt** [comment]
这俩描述也没太大区别，到时候直接重做这个功能得了 =。=
