### ISSUE TITLE
[锟斤拷烫烫烫]程序出现未知错误:调用的目标发生了异常

### ISSUE THREAD

**Issue by LBZiXL** [Hex-Dragon/PCL2#3467]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

程序出现未知错误:调用的目标发生了异常
“System.Windows.Media.Fonts”的类型初始值设定项引发异常
“MS.Internal.FontCache.Util"的类型初始值设定项引发异常
无效的 URI: URI 方案无效。
在 PCLApplication.Application Startup(Object sender
StartupEventArgs e)
错误类型: System.UriFormatException
是否反馈此问题?如果不反馈，这个问题可能永远无法得到解决!
![image](https://github.com/Hex-Dragon/PCL2/assets/115980764/8611dde9-9dc3-4fa6-8c7d-6816e7226295)

### 重现步骤

1、打开PCL

### 日志与附件

[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14468484/Log5.txt)
[Log.txt](https://github.com/Hex-Dragon/PCL2/files/14468485/Log.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14468486/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14468487/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14468488/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14468489/Log4.txt)

**Comment by xxtg666** [comment]
你上传的日志里没有该问题相关的报错，有没有相关的截图/录屏？

**Comment by LBZiXL** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/115980764/25a980de-ca73-4bfd-a56c-efaefa8a7860)

**Comment by LBZiXL** [comment]
> 你上传的日志里没有该问题相关的报错，有没有相关的截图/录屏？

![image](https://github.com/Hex-Dragon/PCL2/assets/115980764/ba0ed8a6-0630-4234-b408-a6f888d5149a)

**Comment by xxtg666** [comment]
是最近突然遇到的这个问题，还是以前也有过？可能是系统问题，等龙猫来看看吧

**Comment by LBZiXL** [comment]
> 是最近突然遇到的这个问题，还是以前也有过？可能是系统问题，等龙猫来看看吧

突然遇到

**Comment by allMagicNB** [comment]
你复现后上传日志啊……

**Comment by allMagicNB** [comment]
你可以试试`sfc /scannow`

**Comment by LTCatt** [comment]
我也觉得这应该是系统问题，看起来是程序找不到微软雅黑字体了

**Comment by allMagicNB** [comment]
[Fonts.zip](https://github.com/Hex-Dragon/PCL2/files/14468748/Fonts.zip)
解压它然后到`设置->个性化->字体`安装

**Comment by LBZiXL** [comment]
> 你复现后上传日志啊……

PCL直接没日志了，sfc /scannow没用。那个Fonts.zip能不能发到网盘里，Github下载不下来

**Comment by deep-dark-forest** [comment]
https://pan.huang1111.cn/s/mbdls1

**Comment by deep-dark-forest** [comment]
额评论不小心删了，你去邮箱里看下（
~我没网盘，懒得注册，只能用我朋友的账号了~

**Comment by LBZiXL** [comment]
> 额评论不小心删了，你去邮箱里看下（ ~我没网盘，懒得注册，只能用我朋友的账号了~

邮箱没有啊

**Comment by deep-dark-forest** [comment]
s://pan.huang1111.cn/s/Kb7XSY

**Comment by LBZiXL** [comment]
> [Fonts.zip](https://github.com/Hex-Dragon/PCL2/files/14468748/Fonts.zip) 解压它然后到`设置->个性化->字体`依次安装3个字体文件

安装字体后还是没有解决

**Comment by LTCatt** [comment]
……重装吧这个

**Comment by zccxcsfsdfdf** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/162008970/37a9bc08-dec0-47db-b124-ddee2ac690d4)
我复现了这个问题，解决方法是切换用户启动，貌似是系统的问题

**Comment by WanghanchenOnGithub** [comment]
我是微软账户，怎么新建啊？

**Comment by hejiehao** [comment]
> 我是微软账户，怎么新建啊？

off-topic?

**Comment by allMagicNB** [comment]
还是修一下吧？这几天已经很多人来反馈这玩意了……

**Comment by WanghanchenOnGithub** [comment]
同意修一下

**Comment by LTCatt** [comment]
我再看一看，就是完全不知道咋回事就是了……

**Comment by allMagicNB** [comment]
应该是切换输入法后造成的？

**Comment by LTCatt** [comment]
实质原因似乎是因为电脑的 path 或 windir 环境变量存在问题，导致 WPF 出现 Bug。
基于 [StackOverflow](https://stackoverflow.com/questions/10094197/wpf-window-throws-typeinitializationexception-at-start-up/10094280) 的调查进行了缓解性修复。
