### ISSUE TITLE
在获取mod名字时如果获取到${modname}就直接显示mod文件名

### ISSUE THREAD

**Issue by mc-124** [Hex-Dragon/PCL2#3470]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在版本设置的mod管理那里如果获取mcmod.info等获取到${modname}就直接改为显示mod的jar文件名

### 原因

有些聪明的mod作者没整名字，整了个${modname}进去，让我没法分辨这是哪个mod
![image](https://github.com/Hex-Dragon/PCL2/assets/138775126/90970e6d-17e3-4f09-b1de-08e311526cf2)
![image](https://github.com/Hex-Dragon/PCL2/assets/138775126/8bc4cb89-f4e5-43b4-9b6c-7a389d70c1e9)

**Comment by burningtnt** [comment]
这是模组本身 Gradle 脚本写的有问题吧？

**Comment by mc-124** [comment]
> 这是模组本身 Gradle 脚本写的有问题吧？

应该是 这种mod不少

**Comment by mc-124** [comment]
如果没法从api获取mod的图标，是否可以显示mod内置的图标

**Comment by hejiehao** [comment]
> 如果没法从api获取mod的图标，是否可以显示mod内置的图标

你怎么知道 Mod 内置的图标在哪？

**Comment by zkitefly** [comment]
> 如果没法从api获取mod的图标，是否可以显示mod内置的图标

龙猫说mod提供的icon.png可能过大，所以不考虑

**Comment by zkitefly** [comment]
> > 如果没法从api获取mod的图标，是否可以显示mod内置的图标
> 
> 你怎么知道 Mod 内置的图标在哪？

有固定路径

**Comment by hejiehao** [comment]
> > > 如果没法从api获取mod的图标，是否可以显示mod内置的图标
> > 
> > 
> > 你怎么知道 Mod 内置的图标在哪？
> 
> 有固定路径

Fabric Mod 可以在 fabric.mod.json 里写，Forge 找不到和这个有关的信息

**Comment by MCSteve123** [comment]
~作者偷懒，启动器还得想方设法解决~

**Comment by mc-124** [comment]
e 只有交bug和pr才能解锁隐藏主题是吗

**Comment by allMagicNB** [comment]
> e 只有交bug和pr才能解锁隐藏主题是吗

是的
