### ISSUE TITLE
mod“配置界面（configured）”下载bug

### ISSUE THREAD

**Issue by METzX** [Hex-Dragon/PCL2#3472]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

下载该mod时，fabric版本下只有1.19但是forge版本下存在fabric及neoforge的其他版本

### 重现步骤

mod下载界面搜索配置界面

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14469273/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14469274/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14469275/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14469276/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14469277/Log1.txt)

**Comment by deep-dark-forest** [comment]
mod作者传错了，与pcl无关

**Comment by allMagicNB** [comment]
不对啊，偶然间发现另一个 Bug

**Comment by METzX** [comment]
> 不对啊，偶然间发现另一个 Bug

啊？怎么说？

**Comment by allMagicNB** [comment]
这个模组并没有标注仅限`Forge`，但是PCL2把它错识别为了Forge版

**Comment by deep-dark-forest** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/131975043/f1bde623-ec4a-4671-a563-40863830261a)
![image](https://github.com/Hex-Dragon/PCL2/assets/131975043/61382006-e0e6-4516-8e32-df2bb998ce3e)

[configured fabric](https://www.curseforge.com/minecraft/mc-mods/configured-fabric/files/all?page=1&pageSize=20)实际上已经停止维护，后续的该模组所有版本都被上传到了[这里](https://www.curseforge.com/minecraft/mc-mods/configured/files/all?page=1&pageSize=20)，因此pcl的描述确实存在问题，不应该描述为“forge版”

**Comment by METzX** [comment]
> 这个模组并没有标注仅限`Forge`，但是PCL2把它错识别为了Forge版

啊哈 我就说点进curseforge和mc百科他也没分两个

**Comment by METzX** [comment]
> ~mod作者传错了，与pcl无关~ 我傻了抱歉

哈哈
