### ISSUE TITLE
移除手动下载 OptiFine 快照版本的“更新日志”按钮

### ISSUE THREAD

**Issue by allMagicNB** [Hex-Dragon/PCL2#3473]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

OptiFine 的快照版本并没有更新日志，所以`更新日志`按钮点进去是`File not found.`
<details>

<summary>就像这样</summary>

[![image](https://github.com/Hex-Dragon/PCL2/assets/116283787/7336c9a4-8d0b-4645-9f79-a16a91b9befb)](https://www.bilibili.com/video/BV1GJ411x7h7/ "更新日志")

</details>

### 原因

OptiFine 的快照版本没有日志，所以这个按钮在它们上面也没有，点进去还只能看到`File not found.`

**Comment by zkitefly** [comment]
这是因为 optifine 官网删除了大部分的快照版，其中就包括日志，但 bmclapi 的文件没有删除

**Comment by allMagicNB** [comment]
但是线现在这个按钮点击后是转向官网的

**Comment by Silverteal** [comment]
可能难以/无法判断哪些版本已经删除，或者代价过大。
鉴于此功能使用率不高，可以暂缓

**Comment by allMagicNB** [comment]
不是，**所有**快照版本都没有Changelog

**Comment by WorldHim** [comment]
> 不是，**所有**快照版本都没有Changelog

应改为 Minecraft 快照版本对应的 OptiFine

**Comment by zkitefly** [comment]
> > 不是，**所有**快照版本都没有Changelog
> 
> 应改为 Minecraft 快照版本对应的 OptiFine

不，他指的是 optifine 的测试版本（

**Comment by LTCatt** [comment]
有的，只是有些版本 OptiFine 官方删了
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/c6624610-0f24-4a01-a43b-c20a5cd0be1b)
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/2779cbfa-12c6-4a3d-ab14-47944e50685c)

**Comment by allMagicNB** [comment]
额我不是指这个版本

**Comment by allMagicNB** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/116283787/89d8b600-a31d-4a60-9e83-53c6a0a97b5c)
@LTCatt 我指的是这个`快照版本`，我刚才试过了，打开都是`File not found.`……

**Comment by LTCatt** [comment]
OptiFine 在发布新正式版之后就会删除此前快照版的更新日志，包括这些
