### ISSUE TITLE
正版登录失败

### ISSUE THREAD

**Issue by nicettlhy** [Hex-Dragon/PCL2#3477]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

正版登录总是卡在最后登录百分比90多时，微软登录正常

### 重现步骤

1、点击正版登录
2、输入个人信息，等待pcl加载登录百分比
3、登录失败

### 日志与附件

[Log.txt](https://github.com/Hex-Dragon/PCL2/files/14469424/Log.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14469425/Log1.txt)

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14469426/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14469428/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14469429/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14469430/Log5.txt)

**Comment by allMagicNB** [comment]
？？？
你给我说清楚，正版登录=微软登录
其次，你可以试试关掉`设置->启动器->验证 SSL 证书`选项再试试

**Comment by kong-que-dnf123** [comment]
～正版登录现在不只有微软登录吗～
～还是你没通过更新把mojang登录移除啊？～

**Comment by HomoobyDX** [comment]
他的意思可能是登录live.microsoft.com正常吧

**Comment by rumengchuxing062** [comment]
> 他的意思可能是登录live.microsoft.com正常吧

事实上，Microsoft和minecraft都是走login.live.com

**Comment by wuliaodexiaoluo** [comment]
两周了，coll过来关下

**Comment by WForst-Breeze** [comment]
超时关闭，如有补充可以在下方继续评论，感谢反馈
