### ISSUE TITLE
下载失败弹窗关闭bug

### ISSUE THREAD

**Issue by yangzimugreg** [Hex-Dragon/PCL2#3479]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

当同时有多个下载任务，其中一个出现失败弹窗，那么它关闭后会在一瞬间重新置顶出现，无法彻底关闭。
在尝试复现一个bug时发现。
创建了九个整合包任务，一个成功，两个愣住手动取消，剩下的只有没有进行的下载任务时关闭。

### 重现步骤

同时创建多个大概率下载失败的整合包下载任务，并等待一个任务失败，之后关闭失败弹窗。
（有时会反应较慢，我创建了本体及1-8号任务，4号创建了文件夹，但下载任务弹窗过了很久才出现）

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14469507/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14469510/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14469512/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14469515/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14469516/Log5.txt)

**Comment by deep-dark-forest** [comment]
像是#2825

**Comment by yangzimugreg** [comment]
抱歉没有搜到
复现版本为最新版（快照2.6.15）

**Comment by allMagicNB** [comment]
能发张截图吗……

**Comment by yangzimugreg** [comment]
1-4为任务创建顺序。
<img width="831" alt="1" src="https://github.com/Hex-Dragon/PCL2/assets/161196998/9530ab44-daa1-465c-8f77-ec47d7d0b1a6">
上图为错误生成，基本都与forge加载器与网络有关。
<img width="799" alt="2" src="https://github.com/Hex-Dragon/PCL2/assets/161196998/85d5c74f-2d9e-4146-aac5-be8c9da83920">
上图为可以关闭。
<img width="822" alt="3" src="https://github.com/Hex-Dragon/PCL2/assets/161196998/1730650b-2501-4ffb-84b7-e16ca3489539">
<img width="824" alt="4" src="https://github.com/Hex-Dragon/PCL2/assets/161196998/2b122649-c03e-4dc8-95dd-00ffd1c6279a">
<img width="824" alt="5" src="https://github.com/Hex-Dragon/PCL2/assets/161196998/9c5dda3d-64ce-4597-81b6-451622a81f82">
最后一张为延迟截图截出。

**Comment by yangzimugreg** [comment]
![无标题视频——使用Clipchamp制作](https://github.com/Hex-Dragon/PCL2/assets/161196998/2ea1c7bb-40c8-4419-abb6-2e3c3c041721)
[2024_3_2 22_26_50 - Screen - 无标题视频.webm](https://github.com/Hex-Dragon/PCL2/assets/161196998/d8f93260-630e-4495-b3fb-3ffeb986a30a)

**Comment by yangzimugreg** [comment]
![无标题视频——使用Clipchamp制作](https://github.com/Hex-Dragon/PCL2/assets/161196998/59781635-ad9a-4732-ba5d-13371e0944ae)
gif同视频

**Comment by yangzimugreg** [comment]
![无标题视频——使用Clipchamp制作](https://github.com/Hex-Dragon/PCL2/assets/161196998/52da20e8-bcb7-4539-b6d6-63d06ee4c154)

**Comment by yangzimugreg** [comment]
gif发不出

**Comment by deep-dark-forest** [comment]
等等那这情况不就和我#2825 一样吗

**Comment by yangzimugreg** [comment]
我确实记得之前有过这个情况，但消失了一段时间。

**Comment by hejiehao** [comment]
> 等等那这情况不就和我#2825 一样吗@LTCatt

这似乎没有修好

**Comment by deep-dark-forest** [comment]
那直接reopen#2825啊

**Comment by hejiehao** [comment]
> 那直接reopen #2825 啊

万一要活跃橙呢？

**Comment by deep-dark-forest** [comment]
> > 那直接reopen #2825 啊
> 
> 
> 
> 万一要活跃橙呢？

那重复的issue能拿活跃橙吗？

**Comment by JingHai-Lingyun** [comment]
算旧版修了的 Bug，在新版本又出现了，没修干净

**Comment by kong-que-dnf123** [comment]
#3007 ...?
~我刚刚看#3007以为是reopen结果是压根没修完...~

**Comment by kong-que-dnf123** [comment]
啊？乱了乱了.jpg
![image](https://github.com/Hex-Dragon/PCL2/assets/120994373/4a52e933-3e56-42e0-8b5f-937eded5a8bf)
![image](https://github.com/Hex-Dragon/PCL2/assets/120994373/83178d22-15cf-44e8-aaa8-9a426870f3a7)

**Comment by LTCatt** [comment]
ok，应该是 #3007
