### ISSUE TITLE
将Optifabric加入下载-手动安装包列表

### ISSUE THREAD

**Issue by xhahello** [Hex-Dragon/PCL2#3481]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

将Optifabric加入下载-手动安装包列表

### 原因

更方便

**Comment by allMagicNB** [comment]
有没有一种可能人家只是个Mod？

**Comment by deep-dark-forest** [comment]
没必要的，curseforge上能搜到，那这么说sodium也要加

**Comment by allMagicNB** [comment]
不太可能会加，但是没有重复也不是个人原因我没啥理由可以关（
龙猫要不考虑改下`Collaborator`能做的事（

**Comment by LTCatt** [comment]
确实没必要列进去。
这种可以留给我关，多确认一下也没啥问题 =。=
