### ISSUE TITLE
支持在启动器中访问modrinth collections

### ISSUE THREAD

**Issue by deep-dark-forest** [Hex-Dragon/PCL2#3485]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

支持在启动器中访问modrinth collections，可以等支持数据包和光影下载后添加本功能
![image](https://github.com/Hex-Dragon/PCL2/assets/131975043/edadf0ba-c5c9-4689-9a4d-96cd414782e1)

### 原因

我需要这个功能来访问modrinth collections，如果没有这个功能，我每次都需要打开浏览器，特别麻烦

**Comment by zkitefly** [comment]
有 API 吗

**Comment by deep-dark-forest** [comment]
好像没（

**Comment by hejiehao** [comment]
我研究一下

**Comment by hejiehao** [comment]
有没有一些公开的 Collection？

**Comment by deep-dark-forest** [comment]
我看了文档好像不支持collection (

**Comment by hejiehao** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/98140773/529d29ed-ae80-4f75-a023-8cd3743cab5e)
