### ISSUE TITLE
建议将“更多”侧边栏的“反馈”和“新功能投票”改为和其它标签对齐

### ISSUE THREAD

**Issue by azaz-az** [Hex-Dragon/PCL2#3491]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

![image](https://s11.ax1x.com/2024/03/03/pFBQZQ0.png)

显然，如图所示，“反馈”和“新功能投票”并未与其他标签对齐，建议改为对齐的

### 原因

这项优化让我看着更舒服。
如果没有这项优化，每次看到就会很难受

**Comment by hejiehao** [comment]
> 我没看出来……

我用瞪眼法看出来了它们往左偏了一点

**Comment by hejiehao** [comment]
<img width="769" alt="QQ截图20240303160647" src="https://github.com/Hex-Dragon/PCL2/assets/98140773/81fef48d-1f50-40d4-b015-e1f104a80582">

**Comment by kong-que-dnf123** [comment]
我猜应该是下面那两个是直接网页跳转
所以没有『选中时』左边多出来的那个指定你选中的页面的那个小块

**Comment by allMagicNB** [comment]
@LTCatt

**Comment by az7627** [comment]
申请解锁主题“活跃橙”。D1D1-119C-5C8B-EA0A

**Comment by LTCatt** [comment]
你的解锁码：MaSRUQvxirTB2rFKoZ22IgIv1jFTJ+ZO
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
