### ISSUE TITLE
Alibaba Dragonwell 21版本 无法添加JAVA 

### ISSUE THREAD

**Issue by penjun71** [Hex-Dragon/PCL2#3493]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

添加Alibaba Dragonwell JAVA21 时提示，该java 存在异常，无法使用：检查JAVA失败 
版本字符串部分太短或太长

### 重现步骤

手动添加报错，自动添加无法识别

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14473256/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14473257/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14473258/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14473259/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14473260/Log5.txt)

**Comment by JingHai-Lingyun** [comment]
Log1 见

```
[22:12:34.078] [Java] 检查失败的 Java 输出：E:\MC\JAVA21\bin\java.exe
openjdk version "21.0.2.0.2" 2024-01-16
openjdk runtime environment (alibaba dragonwell standard edition)-21.0.2.0.2+13-ga (build 21.0.2.0.2)
openjdk 64-bit server vm (alibaba dragonwell standard edition)-21.0.2.0.2+13-ga (build 21.0.2.0.2, mixed mode, sharing)

[22:12:34.091] 该 Java 存在异常，无法使用：检查 Java 失败（E:\MC\JAVA21\bin\javaw.exe）
→ 版本字符串部分太短或太长。
   在 PCL.ModJava.JavaEntry.Check()
   在 PCL.PageSetupLaunch.BtnArgumentJavaSelect_Click(Object sender, EventArgs e)
   在 System.Version.VersionResult.SetFailure(ParseFailureKind failure, String argument)
   在 System.Version.TryParseVersion(String version, VersionResult& result)
   在 System.Version.Parse(String input)
   在 System.Version..ctor(String version)
   在 PCL.ModJava.JavaEntry.Check()
错误类型：System.ArgumentException
```

**Comment by JingHai-Lingyun** [comment]
草 Github 怎么默认 Ctrl+Enter 关帖了

**Comment by burningtnt** [comment]
不过这个确实太长了……

对比 Bellsoft JDK：

```
openjdk version "11.0.21" 2023-10-17 LTS
OpenJDK Runtime Environment (build 11.0.21+10-LTS)
OpenJDK 64-Bit Server VM (build 11.0.21+10-LTS, mixed mode)
```
