### ISSUE TITLE
删除游戏文件夹UI两个取消按钮

### ISSUE THREAD

**Issue by ShiroNeri4u** [Hex-Dragon/PCL2#3495]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![QQ截图20240304130649](https://github.com/Hex-Dragon/PCL2/assets/89512817/4215e454-d44d-4bd7-bfbb-a5e02678125a)
2个取消按钮？

### 重现步骤

1、选择删除游戏文件夹即可

### 日志与附件

无

**Comment by allMagicNB** [comment]
#1987
这是刻意的设计
