### ISSUE TITLE
无法正常重命名版本

### ISSUE THREAD

**Issue by hamiguatang** [Hex-Dragon/PCL2#3497]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/Hex-Dragon/PCL2/assets/143095655/74acd3cb-e4c7-423e-9b11-215b82b011ac)

### 重现步骤

1、点击版本设置
2、往下滚，然后点击重命名

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14516916/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14516917/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14516921/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14516923/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14516924/Log5.txt)

**Comment by zkitefly** [comment]
用管理员权限启动pcl看看？

**Comment by hamiguatang** [comment]
ok解决了
