### ISSUE TITLE
模组自动更新

### ISSUE THREAD

**Issue by Akasa114** [Hex-Dragon/PCL2#3501]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

我设想是否可以在后台对包内所有已有mod进行目标版本搜索，有新文件则予以替换，这样就等同于更新了mod文件

### 原因

很多人玩自组整合包的时候都会遇到时间跨度过大，mod版本有新有旧，就可能会导致莫名的错误。
然而一个一个去检查和更新太耗费时间，正好PCL2有在下载mod的时候优先显示目标版本的功能，
通过这样的功能就免去大量的检查，而且这个功能可以说龙猫已经做了一半了，相信比新构筑一个功能简单些
（龙猫我下半年就高三了，明年这个功能有可能实现吗（/(ㄒoㄒ)/~~）

**Comment by allMagicNB** [comment]
#102

**Comment by allMagicNB** [comment]
服了这破机器人了

**Comment by deep-dark-forest** [comment]
这个模组更新功能已经在`处理中`了，在你高考之前肯定能出（
