### ISSUE TITLE
优化同时安装Optifabric和Sodium时的崩溃提示

### ISSUE THREAD

**Issue by CiLuQwQ** [Hex-Dragon/PCL2#3502]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

这两个Mod不兼容是非常典型的，这样改可以帮到很多玩家。
同时安装这两个模组时，由于目前Optifabric与Sodium是fabric.mod.json级的不兼容，所以会直接崩溃。然而目前的形式很多玩家理解不了（详见原因部分），所以我建议改为下面这几种：
### 方案一：
将Fabric提供的“其它原因”显示出来，也就是
```shell
更多信息：
	 - 模组 'Sodium' (sodium) 0.5.8+mc1.20.4 与 模组 'OptiFabric' (optifabric) 的 任意版本 不兼容，但已经安装了的版本是 1.14.3！
```
这样玩家就可以知道这两个模组任意版本都不兼容
### 方案二：
明确显示出来Optifabric与Sodium不兼容

### 原因

目前出现这种状况这种状况PCL2会显示
```shell
Minecraft 出现错误
Fabric 提供了以下解决方案：
 - 将 模组 'Sodium' (sodium) 0.5.8+mc1.20.4 替换为与这一模组兼容的 任意版本：
	 - optifabric 1.14.3
```
上面写到要替换为与optifabric兼容的任意版本，但实际上是要删除，很多人理解不了还以为Sodium哪个版本可以与Optifine兼容

**Comment by deep-dark-forest** [comment]
意义不大的，冲突的模组千千万，pcl不可能都给出解决方案

**Comment by allMagicNB** [comment]
我也不敢拒绝啊¯\\_(ツ)\_/¯
还是让龙猫看看？

**Comment by zkitefly** [comment]
我感觉可以弄方案一 :thinking:

**Comment by WorldHim** [comment]
方案二中 PCL2 的显示实质上是判断逻辑有误吧

**Comment by JingHai-Lingyun** [comment]
应该是 PCL 崩溃分析模块的逻辑问题
看样子在遇到 `不兼容` 文本的时候固定会返回要求安装兼容的版本

**Comment by LTCatt** [comment]
这是 Fabric 生成的处理建议信息有误，PCL 只是把 Fabric 的建议信息显示了出来，不像是启动器这边的 bug……
