### ISSUE TITLE
安装整合包后能自动选择整合包内的图标

### ISSUE THREAD

**Issue by aaa154152151** [Hex-Dragon/PCL2#3503]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [x] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在安装好新的整合包以后想要pcl2能自动选择整合包内的图标文件来替换默认的丝绸/铁砧

### 原因

仅为一项不重要的优化
球球龙猫顺手加上吧

**Comment by allMagicNB** [comment]
从哪安装？

**Comment by WForst-Breeze** [comment]
反馈者意为允许用户手动安装整合包时自动将原始整合包中储存的图标文件（如有）设置为版本图标

但哪个整合包会在压缩文件里放图标文件呢🤔

**Comment by aaa154152151** [comment]
![屏幕截图 2024-03-09 144526](https://github.com/Hex-Dragon/PCL2/assets/142656481/b9b5ec41-3a80-4b3f-a416-da4e2a3c6654)
嗯...

**Comment by aaa154152151** [comment]
![屏幕截图 2024-03-09 144526](https://github.com/Hex-Dragon/PCL2/assets/142656481/47c338f4-31ed-4eb2-a251-e90dcea802a9)

**Comment by allMagicNB** [comment]
> ![屏幕截图 2024-03-09 144526](https://github.com/Hex-Dragon/PCL2/assets/142656481/47c338f4-31ed-4eb2-a251-e90dcea802a9)
> 

这个位置不固定，我刚刚下载的准备尝试的整合包在这个位置就没有
看起来……只能联网查询？
不过用处不大，不太可能被通过

**Comment by aaa154152151** [comment]
en...用处的确不算很大，联网查询就太多余了
那就随缘吧
