### ISSUE TITLE
当因为java过高或过低时也尝试自动下载java

### ISSUE THREAD

**Issue by Ad-closeNN** [Hex-Dragon/PCL2#3504]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

当因这种情况导致java崩溃时让用户自己手动安装其他java而**不是PCL自动下载JRE8**
![image](https://github.com/Hex-Dragon/PCL2/assets/103355026/eda94608-8537-4fb9-956d-396748846522)

### 原因

忘记点“让PCL自动下载”的时候还要点一遍启动，实在太麻烦了

**Comment by Ad-closeNN** [comment]
应该说是优化才对（

**Comment by allMagicNB** [comment]
我没看懂……

**Comment by Ad-closeNN** [comment]
> 我没看懂……

就是...出现这个页面的时候加个“自动下载”的按钮

**Comment by allMagicNB** [comment]
好像这个提示最多只支持三个按钮……

**Comment by Ad-closeNN** [comment]
> 好像这个 MyMsgBox 最多只支持三个按钮……

那再弹个msgbox?不过这样显得有点啰嗦

**Comment by mc-124** [comment]
> > 好像这个 MyMsgBox 最多只支持三个按钮……
> 
> 那再弹个msgbox?不过这样显得有点啰嗦

我觉得可以显示第一个后再显示第二个自动下载java，按键整个[自动下载][取消][不再弹出]
感觉这样可以没那么啰嗦

**Comment by LTCatt** [comment]
错误分析不一定准确，所以不会接后续的自动化处理 :/
