### ISSUE TITLE
[优化] 对于 Minecraft 内存溢出错误同时粘贴报错信息和提示

### ISSUE THREAD

**Issue by wuliaodexiaoluo** [Hex-Dragon/PCL2#3510]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在 Minecraft 内存溢出进行错误诊断时显示建议的同时显示 java.lang.OutOfMemoryError:xxxx

### 原因

PCL 对于内存溢出的建议太过笼统，内存太小，但实际上有部分 OOM 不是由配置的物理内存太小导致的
比如 OpenJ9 运行 1.12.2 不设置 DirectByteBuffer 也会 OOM，这部分需要调整 DirectByteBuffer 设置

**Comment by allMagicNB** [comment]
本身上传错误报告时错误报告就有了，而且大多数小白都看不懂

**Comment by plpako** [comment]
我不知道我是不是这个问题，自动分配内存分16G会闪退，说是内存不足，自定义内存越小越不容易闪退，但是越小越卡
[Uploading 错误报告-2024-3-11_13.07.09.zip…]()

**Comment by allMagicNB** [comment]
> 我不知道我是不是这个问题，自动分配内存分16G会闪退，说是内存不足，自定义内存越小越不容易闪退，但是越小越卡
> [Uploading 错误报告-2024-3-11_13.07.09.zip…]()
> 

如果你需要求助，请单独开 Discussion
