### ISSUE TITLE
[优化] 添加 -XX:MaxDirectMemorySize=256M 解决部分原版 Minecraft 版本运行在 OpenJ9 虚拟机上出现 Out Of Memory Error

### ISSUE THREAD

**Issue by wuliaodexiaoluo** [Hex-Dragon/PCL2#3511]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

全局设置的 JVM 参数添加-XX:MaxDirectMemorySize=256M

### 原因

经过证明添加此参数不会出现 OpenJ9 运行原版 Minecraft 加载本地地图时出现内存溢出错误，且暂时没有发现添加参数后对 
 Hotspot 虚拟机造成任何影响

**Comment by allMagicNB** [comment]
有特殊需求的人会自己去加……

**Comment by LTCatt** [comment]
有关于它的更多技术细节吗？例如为什么加它就不会溢出……？

**Comment by wuliaodexiaoluo** [comment]
> 有关于它的更多技术细节吗？例如为什么加它就不会溢出……？

你觉得我像是能看得懂 C 和 Java 的人吗？

至于问题原因，我可以给个猜测，或许是OpenJ9为了提高启动速度而延长了GC回收间隔，然后本来不太够用的 Direct Memory 不够用了

**Comment by wuliaodexiaoluo** [comment]
> 有特殊需求的人会自己去加……

说不定就有小白听从了 B 站 Up 的建议换 OpenJ9

**Comment by allMagicNB** [comment]
> direct ByteBuffer可以通过-XX:MaxDirectMemorySize来设置，此参数的含义是当Direct ByteBuffer分配的堆外内存到达指定大小后，即触发Full GC。注意该值是有上限的，默认是64M，最大为sun.misc.VM.maxDirectMemory()，在程序中可以获得-XX:MaxDirectMemorySize的设置的值。
[原文在此](https://www.cnblogs.com/laoqing/p/10380536.html)

**Comment by rumengchuxing062** [comment]
> 有关于它的更多技术细节吗？例如为什么加它就不会溢出……？

看了眼文档，貌似就类似于PCL的内存自动清理

所以这个设置是为了避免gc触发后符合98%的时间用于gc而只回收了不到2%从而返回oom

**Comment by ailelix** [comment]
在PCL 2.7.0中该参数已经加入了默认JVM参数中
然而在我的使用中，该参数反而会导致`Out of Memory错误`
去掉该参数后运行正常
并且发现游戏内F3数据`Direct Buffers: +301.861MiB`
我没学过Java，但猜测该数据与`MaxDirectMemory`有关？
所以这里斗胆讨论一下引入该JVM参数是否正确

### 使用版本：
`Oracle JDK 21.02`
`PCL 2.7.0 (319.50)`
`Minecraft 1.16.5 Fabric`

### 电脑配置：
> CPU: Ryzen 5800X
> RAM: 8Gx2@3200Mhz
> GPU: Nvidia 2080Ti
> OS: Win11 23H2

### Mod列表：
```
Fabric 0.15.9
Fabric API 0.42.0+1.16

Sodium fabric-mc1.16.5-0.2.0+build.4
Iris mc1.16.5-1.4.5

Cloth Config 4.17.101-fabric
Malilib fabric-1.16.5-0.10.0-dev.21+arne.8
Architectury 1.32.68

Tweakeroo fabric-1.16.5-0.10.0-dev.20210917.191839
MiniHud fabric-1.16.5-0.19.0-dev.20210917.191825
RoughlyEnoughItems 5.12.385
VoxelMap 1.10.15_for_1.16.5
MouseTweaks fabric-mc1.16.5-2.22
InventoryHUD fabric-[1.16.2-1.16.5]-3.4.1
Hwyla fabric-1.16.2-1.9.23-79
can-i-mine-this-block 1.0.2
```

**Comment by allMagicNB** [comment]
……？
@LTCatt

**Comment by wuliaodexiaoluo** [comment]
用 OpenJDK 完全没问题啊。。。
这边建议最好不要用 Oracle JDK（看看wy的1.12.2多卡就知道了

**Comment by ailelix** [comment]
> 用 OpenJDK 完全没问题啊。。。（因为我用的是 OpenJDK ，所以基本上是优先考虑 OpenJDK，Oracle JDK 忘记尝试了） 这边建议最好不要用 Oracle JDK（看看wy的1.12.2多卡就知道了 另外 1.16.5 建议降下版本

测试了OpenJDK 21.02，`DirectBuffer`仍然达到~300MiB

**Comment by wuliaodexiaoluo** [comment]
那这可能不是参数问题了
我这边 OpenJDK 没有任何问题

**Comment by JingHai-Lingyun** [comment]
或许考虑仅在使用 OpenJDK 9 启动时默认应用此参数？

**Comment by LTCatt** [comment]
见 #3651

**Comment by allMagicNB** [comment]
> 为什么我用就没问题
> 为什么你们都是 Out Of Memory Error

不要只参考你一个人的环境……

**Comment by burningtnt** [comment]
-XX 开头的参数是非标准参数。让启动器直接内置他们是完全错误的。

**Comment by allMagicNB** [comment]
> -XX 开头的参数是非标准参数。让启动器直接内置他们是完全错误的。

正解（

**Comment by wuliaodexiaoluo** [comment]
就。。。就无语
________________________________
发件人: allMagic ***@***.***>
发送时间: 2024年4月8日 20:24
收件人: Hex-Dragon/PCL2 ***@***.***>
抄送: wuliaodexiaoluo ***@***.***>; Author ***@***.***>
主题: Re: [Hex-Dragon/PCL2] [优化] 添加 -XX:MaxDirectMemorySize=256M 解决部分原版 Minecraft 版本运行在 OpenJ9 虚拟机上出现 Out Of Memory Error (Issue #3511)


-XX 开头的参数是非标准参数。让启动器直接内置他们是完全错误的。

正解（

―

**Comment by wuliaodexiaoluo** [comment]
根据 ailelix 提供的日志来看，参数是没问题的，但是我给定的参数配置的 Direct Memory 还是太小了。。。。

**Comment by burningtnt** [comment]
堆外内存对于原生 Minecraft，仅用于存储贴图等纹理资源。
但请注意，如果用户安装了高分辨率材质等，256MB 的堆外内存肯定是不够的。

这个 Issue 开始就错了：如果堆外内存不够，应当降低堆内存分配，而不是在这里添加什么非标准的 JVM 参数来限制堆外内存分配。

**Comment by wuliaodexiaoluo** [comment]
>这个 Issue 开始就错了：如果堆外内存不够，应当降低堆内存分配，而不是在这里添加什么非标准的 JVM 参数来限制堆外内存分配。

事实上这个 Issue 的目的是为了添加参数强制设定 OpenJ9 的堆外内存分配，默认情况下 OpenJ9 应该是分配了 64M 且不会自动增加（也可能会比这大，但有一点是几乎可以确定 OpenJ9 似乎并不会增加堆外内存分配）
或许这个参数堆大点（比如 32768M ?)

**Comment by burningtnt** [comment]
这个 Issue 开始就错了：如果堆外内存不够，应当降低堆内存分配，而不是在这里添加什么非标准的 JVM 参数来限制堆外内存分配。

**Comment by allMagicNB** [comment]
这个 Issue 开始就错了：如果堆外内存不够，应当降低堆内存分配，或降低材质，而不是在这里添加什么非标准的 JVM 参数来限制堆外内存分配。

**Comment by wuliaodexiaoluo** [comment]
你们要这么认为我还真就没办法
