### ISSUE TITLE
[Bug] 在手动删除版本文件后识别到版本文件丢失时仍然可以点击版本设置

### ISSUE THREAD

**Issue by wuliaodexiaoluo** [Hex-Dragon/PCL2#3515]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

删除版本文件后仍然可以进入版本设置，点击删除版本还会弹出
```
[12:48:17.407] 删除版本 1.19 失败：未能找到目录“E:\iis\api\.minecraft\versions\1.19\”。
   在 Microsoft.VisualBasic.FileIO.FileSystem.DeleteDirectoryInternal(String directory, DeleteDirectoryOption onDirectoryNotEmpty, UIOptionInternal showUI, RecycleOption recycle, UICancelOption onUserCancel)
   在 PCL.PageVersionOverall.BtnManageDelete_Click(Object sender, EventArgs e)
错误类型：System.IO.DirectoryNotFoundException
```

### 重现步骤

1.切换到任意版本
2.文件资源管理器打开版本文件夹，删除
3.启动页面点击版本设置，点击删除版本

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14582422/Log1.txt)

**Comment by allMagicNB** [comment]
故意找茬呢？

**Comment by wuliaodexiaoluo** [comment]
> 故意找茬呢？ 已经算是故意触发了……

~什么都故意触发只会害了你OK~

**Comment by JingHai-Lingyun** [comment]
> 故意找茬呢？

友好交流，谢谢

**Comment by LTCatt** [comment]
不考虑从资源管理器手动删除后触发的 bug……抱歉（
这种确实类似手动触发 :/

**Comment by wuliaodexiaoluo** [comment]
至少做个刷新吧。。。。。。
