### ISSUE TITLE
LittleSkin外置登录失败

### ISSUE THREAD

**Issue by seyen777** [Hex-Dragon/PCL2#3518]
### 检查项

- [x] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

这个问题，启动器给出了三个原因
可是，我在尝试了之后，仍然无法正常启动，而在3月12日，LittleSkin在维护，可视为LittleSkin的问题。但是在3月14日LittleSkin已维护完成，启动游戏仍然失败。
![屏幕截图 2024-03-14 214218](https://github.com/Hex-Dragon/PCL2/assets/140573596/01065ec7-abf1-4e06-b0d7-743017ee77ea)

### 重现步骤

1. 在启动器中登录LittleSkin外置登录
2. 启动游戏，然后便出现问题

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14603178/Log1.txt)

**Comment by JingHai-Lingyun** [comment]
Log1 Ln83 提示：
```
[21:34:43.922] 登录失败原始错误信息：网络请求失败（https://littleskin.cn/api/yggdrasil/authserver/authenticate，远程服务器返回错误: (403) 已禁止。）
{"error":"ForbiddenOperationException","errorMessage":"\u8f93\u5165\u7684\u90ae\u7bb1\u4e0e\u5bc6\u7801\u4e0d\u5339\u914d"}
```
解码 errorMessage 得到 `输入的邮箱和密码不匹配`
你确定键入了正确的邮箱和密码吗
