### ISSUE TITLE
[优化] 对 HexDragon-Bot 正文部分加入补充描述

### ISSUE THREAD

**Issue by wuliaodexiaoluo** [Hex-Dragon/PCL2#3520]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

正文加入 ```如果要发表评论，请尽量不要发送类似 **支持** 等无关内容```

### 原因

因为对帖子发布新的讨论会自动 Subscribe 一次，每次有新的内容都会发电子邮件给 Subscribe 这个帖子的人
而一堆人发类似 **支持** 或者 **+1** 等各种与功能无关的内容，给 Subscribe 这个帖子的人造成了极其严重的打扰

**Comment by allMagicNB** [comment]
“没救，侠客咋样都是侠客”——LTCatt

**Comment by LTCatt** [comment]
同上，没用的，回这种东西的人根本不会看

**Comment by deep-dark-forest** [comment]
![Image_1710506798773.png](https://github.com/Hex-Dragon/PCL2/assets/131975043/ce6a87a4-bbdc-4ef6-a243-f830b03e81c5)

**Comment by WForst-Breeze** [comment]
请不要发送带有不友善或攻击性等破坏社区交流和谐的内容 @deep-dark-forest

**Comment by deep-dark-forest** [comment]
> 请不要发送带有不友善或攻击性等破坏社区交流和谐的内容 @deep-dark-forest 

抱歉，我只是来开个玩笑
