### ISSUE TITLE
背包快捷键无法正常使用

### ISSUE THREAD

**Issue by dinnermodee** [Hex-Dragon/PCL2#3523]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

当我们使用鼠标侧键(鼠标按键4、5)作为快捷栏快捷键时,打开背包将无法使用
该快捷键移动对应物品.此bug严重影响游玩pvp类游戏时的游戏体验,我们将无法快速调整该物品位置.

### 重现步骤

1. 将某个快捷栏键位设置为鼠标侧键(鼠标按键4、5).
2. 打开背包.
3. 将某个物品移到除刚刚鼠标侧键之外的背包格子内.
4. 用鼠标侧键(鼠标按键4、5)点击此物品.
5. 我们会发现物品不会移动至鼠标侧键(鼠标按键4、5)快键键所在的快捷栏位置(如果是其他按键的话物品会移至该快捷键所绑定的快捷栏格子内).

### 日志与附件

![image](https://github.com/Hex-Dragon/PCL2/assets/163526566/8dc2711a-7746-42b7-9e56-1ab8e78b0dd9)
![image](https://github.com/Hex-Dragon/PCL2/assets/163526566/c66fff94-965c-465a-86b8-1f1676341f6e)

**Comment by JingHai-Lingyun** [comment]
这应该不是 PCL 启动器的问题？

**Comment by rumengchuxing062** [comment]
请尽量避免使用鼠标操作快捷栏
以及这并不是PCL的问题，如果您认为这是可能存在的特性，请向 mojang 报告此问题

**Comment by deep-dark-forest** [comment]
请补充日志，并尝试使用其他启动器是否出错
请collaborater把标签改为“等待反馈者”

**Comment by allMagicNB** [comment]
这显然与 PCL2 并无关系……
你可以试试使用 HMCL 启动的游戏复现，并上传启动脚本

**Comment by allMagicNB** [comment]
> 请补充日志，并尝试使用其他启动器是否出错
> 请collaborater把标签改为“等待反馈者”

是 Collaborator（

**Comment by Silverteal** [comment]
根据描述，这显然并非启动器问题。请参见鼠标生产商和Mojang Bug Tracker.
