### ISSUE TITLE
把老版PCL2弹窗特效加回来

### ISSUE THREAD

**Issue by Afdian-User-1145** [Hex-Dragon/PCL2#3527]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

把现在的弹窗特效和原来的弹窗_（说实话，那不能叫“弹”窗）_特效全加回来让大家选择

### 原因

**感觉以前的特效很养眼**_**（我身边的玩PCL的人都这么说）**_**，而且工程量和难度真的很小很小**（除非龙猫你把源代码给弄丢了 就又得重新做了 az）

**Comment by allMagicNB** [comment]
这到底是进化还是反向进化……
话说能给张图吗

**Comment by WForst-Breeze** [comment]
弹窗动画是在 2.4.5 重做的，回退的概率不大（

**Comment by allMagicNB** [comment]
想到个法子可以下载到之前的 Release（
就是在 Code 中筛选发布 Tag

**Comment by iPodtouch6557** [comment]
确实，以前好看，但是习惯了也懒得改回去

**Comment by LTCatt** [comment]
不会回退或者加入设置，抱歉 :/

**Comment by Afdian-User-1145** [comment]
看来只能退化力（悲）
