### ISSUE TITLE
[优化] 取消 SSL 证书签名校验时弹出警告

### ISSUE THREAD

**Issue by wuliaodexiaoluo** [Hex-Dragon/PCL2#3528]
### 检查项

- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [x] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

弹出一个警告好让用户知道他们在做什么，避免某些小白在非必须关闭的情况下因为某些不太懂的好心人建议被带歪取消SSL校验

### 原因

因为关闭 SSL 证书签名校验是一个风险性较高的操作，登录部分有个需要重复使用的敏感数据：refresh_token

**Comment by allMagicNB** [comment]
本身鼠标悬停到上面就有提示……

**Comment by wuliaodexiaoluo** [comment]
> 本身鼠标悬停到上面就有提示……

你会认真看解释吗，而且这个解释也不清晰，只是写了会提高安全性但没有对潜在的风险做解释

**Comment by LTCatt** [comment]
意义不大……
