### ISSUE TITLE
[Bug] 游戏窗口标题设置项描述错误

### ISSUE THREAD

**Issue by wuliaodexiaoluo** [Hex-Dragon/PCL2#3531]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

启动器设置的游戏窗口标题设置项描述错误

### 重现步骤

1、点击设置
2、找到游戏窗口标题选项
3、根据提示设置窗口标题，但不要按类似{user}:的格式而是直接使用类似{user}的格式，在附件图片可以看到没有:照样可以正常显示

### 日志与附件

![image](https://github.com/Hex-Dragon/PCL2/assets/160083863/f33e8181-6c38-4e3b-b1d6-3aea970a9293)
![image](https://github.com/Hex-Dragon/PCL2/assets/160083863/935acd25-5909-4436-b603-848a5567b72f)

**Comment by zkitefly** [comment]
或许你理解错了， `：` 是不需要添加的

**Comment by allMagicNB** [comment]
冒号是用来解释说明作用的……

**Comment by wuliaodexiaoluo** [comment]
主要是没写明白，很容易产生误解

**Comment by allMagicNB** [comment]
> 主要是没写明白，很容易产生误解 

本身就是个高级选项，试一试就知道了呗
¯\\_(ツ)\_/¯
