### ISSUE TITLE
添加整合包导出功能

### ISSUE THREAD

**Issue by QianLiZhiWaiovo** [Hex-Dragon/PCL2#3533]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

在版本设置中添加一个整合包导出功能，点击就可将当前版本转化为整合包格式生成

### 原因

由于我经常和朋友一起玩整合包，有时候自己弄整合包就不好导出，用HMCL的话有时候其他启动器的识别不出来，所以我建议添加一个整合包导出的功能

**Comment by allMagicNB** [comment]
#98（#100）
