### ISSUE TITLE
做个添加后六角龙机器人就会自动锁定评论区的标签

### ISSUE THREAD

**Issue by Deep-Dark-Forest** [Hex-Dragon/PCL2#3535]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

做个添加后六角龙机器人就会自动锁定评论区的标签，移除标签后自动解锁评论区

### 原因

最近有些issue/discussion都需要我们去锁定评论区，但是pcl2社区中人数最多的collaborator根本没这个权限，想锁定评论区还需要找最亮的信标，从而拖慢处理效率
而且一旦遇到那种里面有恶意辱骂的issue/discussion想锁定都不行，还需要等龙猫或最亮的信标

**Comment by MCSteve123** [comment]
这玩意要做这么久吗（疑惑

**Comment by wuliaodexiaoluo** [comment]
应该是在测试，也可能是龙猫没空写
大家砸了100多条反馈，现在还有36个还没 Fix，是个人应该没时间写才对

**Comment by allMagicNB** [comment]
突然发现了个东西，加个 `投票中` Label 后 Bot 就会锁定（

**Comment by kong-que-dnf123** [comment]
> 突然发现了个东西，加个 `投票中` Label 后 Bot 就会 Lock（

一直都是进入投票状态后自动锁原帖子啊...?

**Comment by Deep-Dark-Forest** [comment]
> 突然发现了个东西，加个 `投票中` Label 后 Bot 就会 Lock（

你才知道啊（

**Comment by wuliaodexiaoluo** [comment]
然后讨论里面多了个投票

**Comment by MCSteve123** [comment]
> 然后讨论里面多了个投票

人们对着一个投票里的BUG提案陷入沉思（

**Comment by WorldHim** [comment]
> 突然发现了个东西，加个 `投票中` Label 后 Bot 就会 Lock（

说明锁定其实是好做的而且已经有实现了
所以没做真就是忘记了呗🤔

**Comment by MCSteve123** [comment]
> > 突然发现了个东西，加个 `投票中` Label 后 Bot 就会 Lock（
> 
> 说明锁定其实是好做的而且已经有实现了 所以没做真就是忘记了呗🤔

没想过要做这种东西，毕竟没考虑过某些人口嗨

**Comment by LTCatt** [comment]
* bug 了，正在修

**Comment by LTCatt** [comment]
https://github.com/Hex-Dragon/PCL2/discussions/4938
完事
