### ISSUE TITLE
推荐出错 或者 未显示前置?

### ISSUE THREAD

**Issue by kong-que-dnf123** [Hex-Dragon/PCL2#3536]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我在下载“wawla”模组是用的是搜索功能推荐下载，下载成功进入游戏未起效，回到mod页向下滚动才发现搜索功能并未推荐前置且推荐并非该MC版本的最新版
![image](https://github.com/Hex-Dragon/PCL2/assets/120994373/6071dd9b-6b30-4bc8-a8d0-f30ac2c23e1b)
![image](https://github.com/Hex-Dragon/PCL2/assets/120994373/758b55be-8482-44ac-b8fd-fdba66eea2e6)

### 重现步骤

1、进入“下载”→“MOD”
2、搜索处输入“信息”并指定版本为“1.12.2 forge”
3、选择“Wawla高亮显示”
4、检查PCL首推mod并向下查阅该版本的所有mod

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14626860/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14626861/Log2.txt)

**Comment by rumengchuxing062** [comment]
请尝试刷新再试，这可能是cf得bug

**Comment by kong-que-dnf123** [comment]
>请尝试刷新再试，这可能是cf得bug
可这份日志就是我重开一遍复现的啊...?

**Comment by rumengchuxing062** [comment]
> > 请尝试刷新再试，这可能是cf得bug
> 
> 可这份日志就是我重开一遍复现的啊...?

稍后我尝试复现下

**Comment by wuliaodexiaoluo** [comment]
根据复现，该前置为5-6年前发布的，1.14.1 以下版本猜测因为旧版本 Curse Forge 不支持设置加载器信息，所以 Mod 作者没有指定加载器信息，这应当不是 PCL 的问题
详见 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930#user-content-fnref-2-b46456abd09641be15531bba03f24444)
