### ISSUE TITLE
建议在启动游戏的过程中依然可以打开版本选择/设置

### ISSUE THREAD

**Issue by aishiniwo159** [Hex-Dragon/PCL2#3538]
### 检查项

- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在开游戏的过程中只能等游戏开启或者取消才能看版本选择/设置 这样有点不方便(bushi 希望可以改一下(? 那样就可以在启动游戏的过程中修改一些东西了

### 原因

（示例）
这项优化让我可以更方便地xxxx。
如果没有这项优化，我每次都必须xxxx，让操作变得很麻烦。

**Comment by allMagicNB** [comment]
您要修改啥？这是故意挡住怕你们乱搞的
