### ISSUE TITLE
[优化] 对于前置 Mod 跳过 Mod 加载器类型判断始终显示在前置 Mod 栏

### ISSUE THREAD

**Issue by wuliaodexiaoluo** [Hex-Dragon/PCL2#3539]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

对于前置 Mod 跳过加载器类型判断，并始终显示在前置 Mod 栏

### 原因

可以解决早期 CurseForge 不支持设置 Mod 加载器信息，导致指定加载器后可能不会显示前置 Mod 而被用户误认为没有前置或者PCL识别不了前置 Mod

**Comment by allMagicNB** [comment]
请问如果不同版本有不同依赖的话，怎么显示？

**Comment by wuliaodexiaoluo** [comment]
> 请问如果不同版本有不同依赖的话，怎么显示？

把加载器类型那段调大点或者换个地方放

**Comment by wuliaodexiaoluo** [comment]
另外 #3536 已经证明不是 PCL 问题，打个忽略标签

**Comment by LTCatt** [comment]
PCL 应当没有这个问题。
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/ce67bc0f-a80b-4b26-8b70-cd5030461919)
对于 #3536，是因为作者只标注了 2.6.275 有前置，其他版本**并没有标注有前置**。

**Comment by kong-que-dnf123** [comment]
>对于 https://github.com/Hex-Dragon/PCL2/issues/3536，是因为作者只标注了 2.6.275 有前置，其他版本并没有标注有前置。

您好，我是 #3536 的Author
那请问“细节搜索”为 `1.12.2 Forge` 时只显示较旧的2.6.274而不是较新2.6.275也是因为MOD作者并未在下载源里标注 `适用于Forge` 吗?

**Comment by WForst-Breeze** [comment]
> 您好，我是 #3536 的Author
> 那请问“细节搜索”为 `1.12.2 Forge` 时只显示较旧的2.6.274而不是较新2.6.275也是因为MOD作者并未在2.6.275的下载源里标注 `适用于Forge` 吗?

应该是这样的，您可以去 CurseForge 原始页面查看作者是否进行了标记

**Comment by LTCatt** [comment]
> 您好，我是 #3536 的Author 那请问“细节搜索”为 `1.12.2 Forge` 时只显示较旧的2.6.274而不是较新2.6.275也是因为MOD作者并未在2.6.275的下载源里标注 `适用于Forge` 吗?

是的……这作者标的简直一坨
