### ISSUE TITLE
[优化] 搜索 Mod 时优先展示和使用来自 Modrinth 的工程结果而不是优先展示和使用来自 CurseForge 的工程结果

### ISSUE THREAD

**Issue by wuliaodexiaoluo** [Hex-Dragon/PCL2#3540]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

提升来自 Modrinth 的工程结果的权重，对 CurseForge 重复工程进行降权

### 原因

部分在 CurseForge 没有加载器信息的 Mod 可以在 Modrinth 找到加载器信息，但是 PCL 似乎优先使用了来自 CurseForge 的工程信息，导致本来可以识别到的前置信息无法识别和展示

**Comment by LTCatt** [comment]
即使出现这种情况，也是因为 Mod 作者在其中一个平台里没有给出正确的前置信息，不是 PCL 的问题 :/
