### ISSUE TITLE
JAVA虚拟机创建失败

### ISSUE THREAD

**Issue by iridium1234** [Hex-Dragon/PCL2#3549]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

原本认为是整合包（GTNH）出现问题 但是在重新下载整合包后发现不能创建虚拟机这个问题仍然存在 
（未对整合包内内容做出改变）
遂尝试其他版本 问题仍然复现
换过各种版本的java 均不能启动
尝试过的版本有：1.7.10 1.12.2
就报了一个unrecongnized option:--add-opens
在删除启动项中的“--add-opens”后仍然报这个
1.19.2和1.20.1没有报创建虚拟机失败 但是也不能启动游戏

### 重现步骤

不能启动任何版本的游戏
1.打开启动器
2.点击启动游戏

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14720225/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14720226/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14720227/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14720228/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14720229/Log2.txt)

**Comment by wuliaodexiaoluo** [comment]
安装整合包导致的 Minecraft 崩溃问题不予受理，抱歉

**Comment by iridium1234** [comment]
原版也存在此问题

**Comment by iridium1234** [comment]
1.19.2和1.20.1为纯净原版

**Comment by wuliaodexiaoluo** [comment]
> 原版也存在此问题

请提供 Minecraft 日志信息

**Comment by iridium1234** [comment]
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14720796/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14720797/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14720798/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14720799/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14720800/Log2.txt)

**Comment by wuliaodexiaoluo** [comment]
此类文件并非 Minecraft 日志
请再次尝试启动游戏，出现崩溃后点击导出日志
PCL 提供的日志是非常简短，无法确定问题

**Comment by iridium1234** [comment]
> 此类文件并非 Minecraft 日志 请再次尝试启动游戏，出现崩溃后点击导出日志 PCL 提供的日志过于简短，无法确定问题

uh 此问题在刚刚得到了一种非常奇异的解决方式（
我运行了一下HMCL 发现HMCL不能识别到游戏文件
看到你的回复后 重新尝试重启游戏 发现：它 能 跑 了！

**Comment by iridium1234** [comment]
额 所有版本都能跑了 似乎是 解决了
如果再有问题我就再提吧
