### ISSUE TITLE
建议添加客户端自动更新功能

### ISSUE THREAD

**Issue by weold957** [Hex-Dragon/PCL2#3550]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

通过添加更新按钮下载云端（使用者搭建）压缩包或对比文件并更新客户端。 （暂时没什么思路emmm）

### 原因

我需要这个功能来更新服务器的客户端。很多腐竹都有这样的需求，但如果没有这个功能，很多腐竹更新会麻烦一点。呜呜呜呜好可怜。

**Comment by zkitefly** [comment]
https://github.com/Hex-Dragon/PCL2/issues/1768

建议使用第三方工具实现该功能

**Comment by HomoobyDX** [comment]
补充：mcpatch可以做到这个
