### ISSUE TITLE
正版登陆启动失败离线能用

### ISSUE THREAD

**Issue by rstyin** [Hex-Dragon/PCL2#3556]
### 检查项

- [ ] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

按正版验证的登陆，提示Systeam.Net.SocketException

### 重现步骤

1、正版验证登录
2、提示目标计算机积极拒绝，无法连接

### 日志与附件

无日志

**Comment by allMagicNB** [comment]
个人网络原因……

**Comment by zkitefly** [comment]
https://github.com/Hex-Dragon/PCL2/issues/3543

**Comment by allMagicNB** [comment]
别，这不是建议

**Comment by rstyin** [comment]
> 个人网络原因......谢谢但我连接网络，我知道问题出在哪了我挂加速器了
