### ISSUE TITLE
mod消失

### ISSUE THREAD

**Issue by tyjdog** [Hex-Dragon/PCL2#3558]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

安装完mod后，进入minecraft发现mod列表中没有刚刚安装的mod，在找寻一番后发现，版本隔离自动跳转到了关闭

### 原因

如果没有这项优化，我每次都必须每次安装mod后查看版本隔离选项，并关闭，让操作变得很麻烦。

**Comment by allMagicNB** [comment]
估计是你自己重置了或者 PCL2 的配置文件丢失……
