### ISSUE TITLE
在选择mod后关闭保存窗口后未响应

### ISSUE THREAD

**Issue by ZLXL1234** [Hex-Dragon/PCL2#3559]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

关闭选择保存位置窗口后会导致程序未响应

### 重现步骤

1.进入mod下载
2.进入任意模组
3.选择一项下载
4.在弹出选择保存位置窗口后立刻关闭此窗口
5.此时整个界面有小概率无法选中、被拖动、交互，甚至闪退

### 日志与附件

下面

**Comment by ZLXL1234** [comment]
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14731884/Log3.txt)

**Comment by Deep-Dark-Forest** [comment]
请避免将错误日志直接放在issue正文，这会非常影响阅读体验

**Comment by ZLXL1234** [comment]
已修改

**Comment by allMagicNB** [comment]
请上传所有日志

**Comment by ZLXL1234** [comment]
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14731919/Log3.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14731920/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14731921/Log2.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14731922/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14731923/Log5.txt)

**Comment by allMagicNB** [comment]
自己电脑原因，我没复现出来
得有稳定复现方式或者多人反馈才会再修吧……

**Comment by LTCatt** [comment]
这很有可能是 Windows 的 bug……先不说怎么复现，我也不知道怎么修……

**Comment by LTCatt** [comment]
由于两周无人能够复现暂时关闭，如果有任何其他人可以复现再做考虑 :/
