### ISSUE TITLE
添加暂时关闭壁纸的功能

### ISSUE THREAD

**Issue by MCSteve123** [Hex-Dragon/PCL2#3565]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

现在PCL的壁纸只要导入就不能在启动器里关，唯一的办法是删除壁纸，但如果我想暂时不使用壁纸，就还得删了以后再加（
实在麻烦（特别是要开PCL透明时很挡视线）

### 原因

这项优化让我可以更方便地暂时关闭壁纸。
如果没有这项优化，我每次都必须删除壁纸后等要用了再加回来，让操作变得很麻烦。

**Comment by allMagicNB** [comment]
加个 `.disabled` 不得了（

**Comment by MCSteve123** [comment]
不会VB就不交，我还是比较老实的（）

**Comment by Silverteal** [comment]
没有必要，使用频率不高，确有需要修改文件后缀名即可

**Comment by LTCatt** [comment]
适用面不广，暂不考虑，抱歉
