### ISSUE TITLE
安装正确兼容forge的opifine后启动游戏显示“opifine不兼容”

### ISSUE THREAD

**Issue by bolindong** [Hex-Dragon/PCL2#3566]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在自动下载中选择正确的forge和opifine，原版运行正常，但是一旦加上模组就会报错“opifine不兼容”

### 重现步骤

1.正确安装opifine，并下载opifine下方的“推荐forge版本”
2.启动游戏，一切正常
3.安装模组，启动时报错“opifine与forge版本不兼容”

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14735000/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14735001/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14735002/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14735003/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14735004/Log1.txt)

**Comment by allMagicNB** [comment]
请上传错误报告

**Comment by zkitefly** [comment]
> 请上传错误报告，并尝试使用 HMCL 启动并上传 HMCL 的日志与启动脚本，也把崩溃后 HMCL 的界面传一下（

hmcl的非游戏退出页面截图是没用的，应该导出崩溃信息

**Comment by wuliaodexiaoluo** [comment]
经过测试,，这不是 PCL 问题，HMCL 和 BakaXL 均无法启动由 PCL 下载的核心
至于为什么没有试其他启动器下载的核心
~因为 HMCL 显示不兼容 Forge，BakaXL 安装报错 ~

**Comment by wuliaodexiaoluo** [comment]
因为 OptiFine 过于激进的优化手段，导致 ModLoader 和其他 Mod 对 OptiFine 有极其严重的兼容性问题
所以这不是 PCL 的问题

**Comment by wuliaodexiaoluo** [comment]
安装 Mod/Modloader 导致的 Minecraft 崩溃问题不予受理
详见 Minecraft 崩溃 Issue 模板的检查项
建议贴个第三方然后关了

**Comment by wuliaodexiaoluo** [comment]
2 weeks ago 
又能 Close  了

**Comment by JingHai-Lingyun** [comment]
超时关闭
