### ISSUE TITLE
检测JAVA失败，错误类型：System.ComponentModel.Win32Exception

### ISSUE THREAD

**Issue by Shan-Mao** [Hex-Dragon/PCL2#3567]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

Java 8
异常的Java
该Java存在异常，无法使用:检查Java失败(C:\Program FilesUJavayjre-1.8binljavaw.exe)→请求的操作需要提升。
    在PCL.ModJava.JavaEntry.Check()
    在PCL.PageSetupLaunch.BtnArgumentJavaSelect_Click(Object sender, EventArgs e)
    在PCL.ModBase.ShellAndGetOutput(String FileName, String Arguments,Int32 Timeout, String WorkingDirectory)
    在PCL.ModJava.JavaEntry.Check()
错误类型:System.ComponentModel.Win32Exception

Java16
异常的Java
该Java存在异常，无法使用:检查Java失败(C:\Program FilesUJavaljdk-16.0.2\binljavaw.exe)请求的操作需要提升。
    在PCL.ModJava.JavaEntry.Check()
    在PCL.PageSetupLaunch.BtnArgumentJavaSelect_Click(Object sender, EventArgs e)
    在PCL.ModBase.ShellAndGetOutput(String FileName, String Arguments, Int32 Timeout,String WorkingDirectory)
    在PCL.ModJava.JavaEntry.Check(
错误类型:System.ComponentModel.Win32Exception

Java17
异常的Java
该Java存在异常，无法使用:检查Java失败(C:\Program Files\Javaljdk-17\binljavaw.exe)→请求的操作需要提升。
    在PCL.ModJava.JavaEntry.Check()
    在PCL.PageSetupLaunch.BtnArgumentJavaSelect_Click(Object sender, EventArgs e)
    在PCL.ModBase.ShellAndGetOutput(String FileName, String Arguments,Int32 Timeout, String WorkingDirectory)
    在PCL.ModJava.JavaEntry.Check()
错误类型:System.ComponentModel.Win32Exception

Java21
异常的Java
该Java存在异常，无法使用:检查Java失败(C:\Program Files\Javaljdk-211binljavaw.exe)→请求的操作需要提升。
    在PCL.ModJava.JavaEntry.Check()
    在PCL.PageSetupLaunch.BtnArgumentJavaSelect_Click(Object sender, EventArgs e)
    在PCL.ModBase.ShellAndGetOutput(String FileName, String Arguments, Int32 Timeout, tring WorkingDirectory)
    在PCL.ModJava.JavaEntry.Check()
错误类型:System.ComponentModel.Win32Exception

### 重现步骤

1、自动检测Java失败
2、手动检测错误、
       5小时前可以正常打开游戏
3、存在过将pcl2添加到steam中

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14735637/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14735639/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14735640/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14735641/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14735642/Log1.txt)

**Comment by allMagicNB** [comment]
尝试以管理员身份启动 PCL2？

**Comment by Shan-Mao** [comment]
@allMagicNB 搜索到安装的Java

**Comment by Shan-Mao** [comment]
issue

**Comment by allMagicNB** [comment]
想啥呢

**Comment by Shan-Mao** [comment]
> 想啥呢

怎么不算呢

**Comment by allMagicNB** [comment]
要是龙猫修完了才有完成，你这不算数，没有活跃橙

**Comment by Shan-Mao** [comment]
> 要是龙猫修完了才有完成，你这不算数，没有活跃橙

这样哦，我还以为有机会有了呢
