### ISSUE TITLE
(优化) 整合包安装 Forge版本自定义

### ISSUE THREAD

**Issue by FenoX-A** [Hex-Dragon/PCL2#3568]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

发现问题 ：有些整合包需要特殊或更高的Forge版本，但是直接安装整合包时，如果整合包没有对应的设置，pcl2就会根据推荐的forge版本直接下载并安装，这可能会导致整合包无法启动。
暂时的解决方案 ： 下载合适的Forge版本 将mod文件迁移过去
建议优化： 安装整合包时启用高级设置选项 可以自定义解释器版本及其他设置。

### 原因

这项优化使安装程序更灵敏，有助于处理更多的错误。也可以进一步添加(自动识别版本什么的) 。
我在Gun fire survival-1.7 整合包中发现了此问题（如果是我的设备问题请告知）。

**Comment by JingHai-Lingyun** [comment]
这应该是作者配置的问题？

**Comment by allMagicNB** [comment]
方便发下下载下来的整合包吗（

**Comment by wuliaodexiaoluo** [comment]
修改加载器版本可能导致兼容性问题，龙猫不会做的，抱歉

**Comment by Silverteal** [comment]
修改加载器相关的新功能还在投票中 #220

**Comment by zkitefly** [comment]
本质是 https://github.com/Hex-Dragon/PCL2/issues/220 （？）

**Comment by allMagicNB** [comment]
> 本质是 #220 （？）

#220 是更新，这是在安装整合包的时候就更改需要安装的 Forge……

**Comment by allMagicNB** [comment]
算了，不太可能重复，换个 `待处理`？

**Comment by LTCatt** [comment]
请向该整合包作者反馈

**Comment by leiming2333** [comment]
后续我会出一个教程切换版本

**Comment by FenoX-A** [comment]
> 修改加载器版本可能导致兼容性问题，龙猫不会做的，抱歉 至于加载器版本，这应当是作者的问题，您应该联系整合包作者处理
> 请向该整合包作者反馈
> 这应该是作者配置的问题？

统一回复 
这是一个自定义 且 高级设置选项 目的是 排除兼容性问题 合理使用 并不会 导致兼容性问题 
这是一个优化选项 目的在于 作者没有设置版本时进行自定义 
我不是在报告一个bug ，且没有针对性 ，这只是一个优化选项 不是启动器的问题 。
另外 
请理解我的意思之后 再进行回复。

**Comment by FenoX-A** [comment]
> > 统一回复
> > 这是一个自定义 且 高级设置选项 目的是 排除兼容性问题 合理使用 并不会 导致兼容性问题
> > 这是一个优化选项 目的在于 作者没有设置版本时进行自定义
> > 我不是在报告一个bug ，且没有针对性 ，这只是一个优化选项 不是启动器的问题 。
> > 另外
> > 请理解我的意思之后 再进行回复。
> 
> 但是这种情况你可能更应该去找整合包的作者反馈……

所以这才叫优化选项 >高级设置 尽管整合包可能出现了问题 但是启动器任然可以使用这项设置来排除这个错误

**Comment by wuliaodexiaoluo** [comment]
> 统一回复 这是一个自定义 且 高级设置选项 目的是 排除兼容性问题 合理使用 并不会 导致兼容性问题 这是一个优化选项 目的在于 作者没有设置版本时进行自定义 我不是在报告一个bug ，且没有针对性 ，这只是一个优化选项 不是启动器的问题 。 另外 请理解我的意思之后 再进行回复，同时希望把bug标签和第三方标签删除。

这个问题完全可以和整合包作者反馈，并且大部分整合包使用最新版 Forge 都能正常加载，如果需要特殊版本但没有在整合包内标记是整合包作者的问题
PCL 没有义务为整合包问题做任何处理，社区提供的服务是高级用户的志愿行为，这一点您应当知悉
另外允许调整整合包 Forge 会被小白误操作导致安装错误的版本，这是有可能导致的兼容性问题
