### ISSUE TITLE
新功能：参数拼接，合并参数（含开发思路）

### ISSUE THREAD

**Issue by EnderLight3336** [Hex-Dragon/PCL2#3570]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

1.可以在指定index处进行拼接
2.可以在指定string以及指定出现次数进行拼接
3.可以指定在第几个空格处进行拼接
4.可以进行同类型的参数合并，如原参数包含-cp xxx，第二参数包含-cp nnn，则拼接为-cp xxx nnn
拜托，这真的很酷欸，cool！
----
开发思路：
（java ver）
对传入参数进行处理，按不在引号内的空格分割并传入list1，且将-xx的index传入map<int ,string> int为-xx的index，str为-xx，然后上面的功能就比较好整了，注：list至少为有序可变集合，map为键值映射表

### 原因

这个功能真的很酷欸
，并且很实用

**Comment by WorldHim** [comment]
将一长串参数分割成多个小段显示，在处理时合并？
不过适用面不高……

**Comment by Silverteal** [comment]
这和PCL2有什么关系？没看明白

**Comment by LTCatt** [comment]
适用面不广，暂不考虑，抱歉

**Comment by WorldHim** [comment]
> 这和PCL2有什么关系？没看明白

可以用在 jvm 参数里
