### ISSUE TITLE
[Bug] OptiFine Mod.toml 声明了一个不存在的类导致 Forge 在加载 OptiFine 时报 Mod Not Found 错误

### ISSUE THREAD

**Issue by wuliaodexiaoluo** [Hex-Dragon/PCL2#3573]
### 检查项

- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [x] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

Forge 49.0.3x 版本无法正常加载 OptiFine

### 原因

Forge 49.0.3x 版本无法正常加载 OptiFine，会导致 Forge 在加载 OptiFine 时报错，因为加入版本 json 文件并且类型为 Library 因此删除后仍会下载

**Comment by allMagicNB** [comment]
![Screenshot_20240327_123846.jpg](https://github.com/Hex-Dragon/PCL2/assets/116283787/f34ac095-e37c-493c-be78-498ca115b889)

OptiFine 官方都这么标注了，也只能说明是他们的问题……

**Comment by allMagicNB** [comment]
至于高版本 Mod Loader 与 OptiFine 同时安装时弹出提示##3258

**Comment by wuliaodexiaoluo** [comment]
但这个问题确实需要处理。等支持 OptiFine 移除和提示上线估计得一段时间
这段时间内 PCL 可以继续安装同时带有 Forge 和 OptiFine 版本，或者从其他渠道安装带有 Forge 和 OptiFine 版本

**Comment by allMagicNB** [comment]
目前要处理的仅为取消链接？

**Comment by wuliaodexiaoluo** [comment]
只需要删掉对 OptiFine 主文件 （Libraries\optifine）的 cp 链接，OFLauncher可以不管
这样 Forge 就可以跳过加载直接进入游戏

**Comment by LTCatt** [comment]
这应当是 OptiFine 那边的问题……

**Comment by rumengchuxing062** [comment]
> 这应当是 OptiFine 那边的问题….

应该不是，modloader报的是 not found，不是failed to init
但是 forge 那边有没有停摆我不知道，可能交 issue 页没人管

**Comment by zkitefly** [comment]
那个问题是 Forge 那边搞的，具体可以看 https://github.com/HMCL-dev/HMCL/issues/2975 

目前我们讨论有两种方案（@burningtnt）

1. 在安装 OptiFine 前，将 mod.toml 删除，然后再安装（或者安装完会后将 libraries 的 OptiFine installer.jar 的 mod.toml 删除）
2. 打一个 javaagent 进去强行让 ClasspathLocator 禁用
3. 打一个类进入 OptiFine 的 JAR，标上 @Mod("optifine")

还在继续讨论中...

**Comment by burningtnt** [comment]
> 这应当是 OptiFine 那边的问题……

这个问题其实是 Forge 和 OptiFine 两个人撞到一起了（

OptiFine 从 1.13 - 1.14 的一个版本开始，JAR 中包含 mod.toml。但因为 Forge 在非开发环境禁用 ClasspathLocator + mods 文件夹下的模组有 ITransformationService 时不读取 mod.toml 两个逻辑，没出错。

1.19.4 的时候 Forge 在非开发环境不再禁用 ClasspathLocator，然后就爆炸喽

**Comment by wuliaodexiaoluo** [comment]
但是让 OptiFine 那边改掉也不太现实。。。。。
总不可能撤掉旧版本的发布吧。。。

**Comment by wuliaodexiaoluo** [comment]
> 1. 在安装 OptiFine 前，将 META-INF\mod.toml 删除，然后再安装（或者安装完会后将 libraries 的 OptiFine installer.jar 的 META-INF\mod.toml 删除）
> 2. 打一个 javaagent 进去强行让 ClasspathLocator 禁用
> 3. 打一个类进入 OptiFine 的 JAR，标上 `@Mod("optifine")`

把文件打进去会被反作弊掐掉的吧

**Comment by burningtnt** [comment]
> 把文件打进去会被反作弊掐掉的吧

如果反作弊会检查 OptiFine 的哈希，那 (1),(3) 方案都会寄。
(2) 不会寄，因为修改发生在 JVM 运行时。并且，在不使用黑魔法的前提下，Java 应用检测不到 javaagent 的存在。唯一风险时可能因为 Forge 做代码调整而直接崩游戏。

因此，我倾向于先等 Forge 那边回复。如果他们愿意修改，那就好办了，只修改已发布的这几个版本就好。如果不愿意，那…… 到时候再说。

**Comment by wuliaodexiaoluo** [comment]
我去问下 Optifine 那边怎么说

**Comment by wuliaodexiaoluo** [comment]
Forge 如果不愿意搞我去问问 OptiFine 能不能撤回有问题的发行版
打文件进去和参数禁用删文件这个放到最后再说

**Comment by burningtnt** [comment]
> Forge 如果不愿意搞我去问问 OptiFine 能不能撤回有问题的发行版
> 打文件进去和参数禁用删文件这个放到最后再说

撤回是不可能的。

By the way， 你这个标题写的也不对。应改为：
`[Bug] 1.20.4 OptiFine 和 Forge 有兼容性问题`

**Comment by wuliaodexiaoluo** [comment]
> 撤回是不可能的。
> 
> By the way， 你这个标题写的也不对。应改为： `[Bug] 1.20.4 OptiFine 和 Forge 有兼容性问题`

兼容性问题不是报 Failed to init 吗？
这个是 Not Found

**Comment by burningtnt** [comment]
> 兼容性问题不是报 Failed to init 吗？
> 这个是 Not Found

本质是 Forge 和 OptiFine 有兼容性问题。具体请看我的解释

**Comment by wuliaodexiaoluo** [comment]
方案一可以排除了。我用 jar 解压删掉 mods.toml 然后再重新打包成 jar 文件，结果是在启动过程中 Forge 报错崩溃

**Comment by burningtnt** [comment]
> 方案一可以排除了。我用 jar 解压删掉 mods.toml 然后再重新打包成 jar 文件，结果是在启动过程中 Forge 报错崩溃

我这边测试没有任何问题。请你提供崩溃信息或 latest.log

**Comment by wuliaodexiaoluo** [comment]
#3678

**Comment by allMagicNB** [comment]
不对啊，直接扔 `mods` 文件夹作为 Mod 加载也行啊？

**Comment by burningtnt** [comment]
> 不对啊，直接把 OptiFine 扔 `mods` 文件夹作为 Mod 加载也行啊？

请阅读 https://github.com/HMCL-dev/HMCL/issues/2975 ，我已经给出了完整的分析

**Comment by wuliaodexiaoluo** [comment]
> 不对啊，直接把 OptiFine 扔 `mods` 文件夹作为 Mod 加载也行啊？

几个世纪前 PCL 是这么搞得，我也不知道为什么改成用 classpath 加载了

**Comment by zkitefly** [comment]
https://github.com/MinecraftForge/MinecraftForge/issues/9899

forge 修复了这个问题，试试新的 forge 版本？

**Comment by wuliaodexiaoluo** [comment]
那旧版本怎么说，继续打参数？还是归到 1930？

**Comment by zkitefly** [comment]
> 那旧版本怎么说，继续打参数？还是归到 1930？

旧版本应该不行（

**Comment by wuliaodexiaoluo** [comment]
那就是 PCL 这边不为旧版本无法加载 OptiFine 做调整？

**Comment by zkitefly** [comment]
如果愿意为旧版本做兼容就做，不想做就关掉吧

话说试过了吗

**Comment by wuliaodexiaoluo** [comment]
还没，这台计算机的 PCL 有点 Bug，jlw 目录会指定到并不存在的软盘驱动器

**Comment by allMagicNB** [comment]
……压根就不是只有 `49.0.3X`，而是在 `49.0.50` 之前的版本都有问题

**Comment by LTCatt** [comment]
Forge 修复了的话确实可以关了……

**Comment by allMagicNB** [comment]
但是这压根不是我们这边的问题啊（

**Comment by wuliaodexiaoluo** [comment]
能解决就得想办法，不作为不是什么好事
