### ISSUE TITLE
UI错误 - 版本列表在删除了某一过长文件夹后设置按钮错位

### ISSUE THREAD

**Issue by MuchenFAB** [Hex-Dragon/PCL2#3576]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在Snapshot2.6.15版本中 删除了过长的游戏实例文件夹后 会出现设置按钮和阴影与白色渲染区错位
重新进入后问题消失

### 重现步骤

1、主页面点击版本选择
2、强制删除任意文件夹（可以是空的）
3、两次确认后指针移动到任意版本文件夹即可呈现此Bug

### 日志与附件

Log如下
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14809165/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14809167/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14809168/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14809169/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14809170/Log5.txt)
预览图如下
错位发生前![image](https://github.com/Hex-Dragon/PCL2/assets/104298593/7f370a11-2062-4f94-be6f-9fc7ff139007)
错位发生后![image](https://github.com/Hex-Dragon/PCL2/assets/104298593/ce44ced9-5621-4520-8b58-2ce9d6329b7d)

**Comment by allMagicNB** [comment]
#2982
