### ISSUE TITLE
自定义主页支持Markdown语法

### ISSUE THREAD

**Issue by MCSteve123** [Hex-Dragon/PCL2#3577]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

希望xaml自定义主页能添加一个markdown的标签，使用markdown进行编写，特别是文字部分（xaml令人头疼）

### 原因

（示例）
我需要这个功能来xxxx。很多人都有xxxx的需求，但如果没有这个功能，就不能xxxx了。

**Comment by MCSteve123** [comment]
~求丢投票，已经被xaml磋磨死了~

**Comment by allMagicNB** [comment]
推荐使用@Light-Beacon 的主页构建器

**Comment by MCSteve123** [comment]
> 推荐使用 Light-Beacon/HomepageBuilder

能在启动器原生支持一部分当然更好（

**Comment by allMagicNB** [comment]
看看龙猫咋说，不过大概率会被拒绝就是了（

**Comment by WForst-Breeze** [comment]
自定义主页的目标用户群体主要是有一定技术基础的人群，且自定义主页已经有了较完善的教程，个人认为这应当并非 PCL 的服务范畴

**Comment by wuliaodexiaoluo** [comment]
Markdown 需要自写额外的解释器，我认为龙猫一定会打```拒绝/放弃```的 Label

**Comment by LTCatt** [comment]
暂不考虑，抱歉（
