### ISSUE TITLE
下载部分Forge整合包时出现失败

### ISSUE THREAD

**Issue by 0916NINELEAVE** [Hex-Dragon/PCL2#3582]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

主要出现在下载Forge时及MC本体时  如All the mods 7 - To the sky整合包下载时便反复失败十几次  但在HMCL下载同样版本的同样整合包就没有出现这种问题

### 重现步骤

1.在下载页面中选中“整合包”选项
2.选择任意版本forge整合包
3.下载并等待进度至91%左右（下载forge阶段）
4.弹出窗口提示下载失败

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14811662/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14811664/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14811665/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14811666/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14811667/Log5.txt)

**Comment by allMagicNB** [comment]
可能是部分节点问题

**Comment by JingHai-Lingyun** [comment]
应该是 BMCLAPI 不稳定导致的

**Comment by hejiehao** [comment]
似乎是网络问题

**Comment by allMagicNB** [comment]
> 似乎是网络问题

可是我看到了 404

**Comment by allMagicNB** [comment]
你试试访问一下这个网址
https://bmclapi2.bangbang93.com/v1/objects/2e9a3e3107cca00d6bc9c97bf7d149cae163ef21/client.jar

**Comment by hejiehao** [comment]
顺便试试这个？ https://piston-data.mojang.com/v1/objects/2e9a3e3107cca00d6bc9c97bf7d149cae163ef21/client.jar

**Comment by 0916NINELEAVE** [comment]
@allMagicNB 你的网址我没问题  下载不到一秒钟就好了
@hejiehao 但是你的网址我会报错

**Comment by 0916NINELEAVE** [comment]
@allMagicNB 你的网址我没问题  下载不到一秒钟就好了
@hejiehao 但是你的网址我会报错

**Comment by 0916NINELEAVE** [comment]
@allMagicNB 你的网址我没问题  下载不到一秒钟就好了
@hejiehao 但是你的网址我会报错

**Comment by allMagicNB** [comment]
你现在再去安装试试？

**Comment by 0916NINELEAVE** [comment]
> 你现在再去安装试试？

试过了  还是不行   然后HMCL依旧可以（哭）

**Comment by wuliaodexiaoluo** [comment]
感觉像是超过了设定的 HTTP 连接数上限制？
试复现，没成功.jpg

**Comment by wuwenjun9939** [comment]
没有吧，我能下载啊（可能是开挂的关系吧）
![image](https://github.com/Hex-Dragon/PCL2/assets/110022109/5f0da32a-3260-4a15-9193-f4682fbbf5eb)

**Comment by wuwenjun9939** [comment]
不对，开挂的时候，文件不一样
![image](https://github.com/Hex-Dragon/PCL2/assets/110022109/fa011a06-a70e-4270-88cb-4da26aca4372)

**Comment by wuliaodexiaoluo** [comment]
> 不对，开挂的时候，文件不一样 ![image](https://private-user-images.githubusercontent.com/110022109/318608895-fa011a06-a70e-4270-88cb-4da26aca4372.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMjY0NTUsIm5iZiI6MTcxMjAyNjE1NSwicGF0aCI6Ii8xMTAwMjIxMDkvMzE4NjA4ODk1LWZhMDExYTA2LWE3MGUtNDI3MC04OGNiLTRkYTI2YWNhNDM3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMlQwMjQ5MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMjBmYzVlMDdmYTcwZGZjMWIxMGYwODlmYWEyNDU3NGVmZGU5MjQ0MTJiN2YyNjM2YjU2ZjE5ZDZhODJlNGE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OItJ5NFwbJuZ1RyXH4s9-atT1GGJNWhd6RQzIlIX38A)

我也不知道怎么说，但有的节点是 Hash 文件名，有的是 client，我怀疑是这个的问题
@bangbang93 能不能修改下文件名策略

**Comment by bangbang93** [comment]
网盘节点没有办法指定文件名。不过下载文件名这种东西不应该是启动器写文件前就确定的吗，应该没有启动器会使用`content-disposition`头吧

**Comment by wuwenjun9939** [comment]
> ```
> https://bmclapi7.melon.icu:443/download/58f800d623e9b48c24eb83b7c8d4b49279111e9e?name=1.20.3.json&s=sXYRRkaY_hE7cvi1ber0iEPxkOM&e=luhwbi4y
> ```
> 
> 用脚本反复 HTTP 请求后应该是这个节点出问题了 这个节点貌似是被 gfw 墙了，浏览器访问都是 RST
> 
> ![image](https://private-user-images.githubusercontent.com/160083863/318645891-76a07c0d-bb69-4270-b423-fb22a57030bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNDgyOTEsIm5iZiI6MTcxMjA0Nzk5MSwicGF0aCI6Ii8xNjAwODM4NjMvMzE4NjQ1ODkxLTc2YTA3YzBkLWJiNjktNDI3MC1iNDIzLWZiMjJhNTcwMzBiYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMlQwODUzMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOTYwNDk4ZTgwYmZkMDdkMzhlMTc0NTBjNWU3ZjI5MWZlOTRkYmY3ZmU1MTRkYzBjZTEzMDY2MWI2YjEzMDNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rOVJAdYx5F7Gs7QcNrczOqFyDhK4ey5PffAVzNn5PyA)
> 
> ![image](https://private-user-images.githubusercontent.com/160083863/318646250-4dbbb390-ca24-47a3-8b3a-9a5d2bdec8df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNDgyOTEsIm5iZiI6MTcxMjA0Nzk5MSwicGF0aCI6Ii8xNjAwODM4NjMvMzE4NjQ2MjUwLTRkYmJiMzkwLWNhMjQtNDdhMy04YjNhLTlhNWQyYmRlYzhkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMlQwODUzMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YmZlYjNjMjA3YjMzOTRhNDIyMjQ5YjdhNjI0MWRlNDRlZjk0MzIwMDk1ODc3ZTdjNDUyNmRlNjdkMDcyYjM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wQ4lmJPbJqv6mhtpxG1SraXkRLFOi9SVG9Iw17iYFpI)

难不成是因为我开挂的原因？（为啥我Ctrl+F5好几遍都没事呢）

**Comment by wuwenjun9939** [comment]
而且，网页打开是这样的
![image](https://github.com/Hex-Dragon/PCL2/assets/110022109/fe87b919-93dc-47cd-a04b-8eb05ad57c99)

**Comment by shixiaogaoya** [comment]
我也出现了这个问题，但是我开挂也没解决，就很烦，之前中间好了两天，现在又不行了

**Comment by JingHai-Lingyun** [comment]
嘶.... 挺奇怪的，PCL会有问题但是HMCL不会.....
按理来说不应该啊，两家用的都是 BMCLAPI 或官方源

**Comment by wuliaodexiaoluo** [comment]
后续讨论转 #3597

**Comment by allMagicNB** [comment]
总不可能是节点那边搞限定 UserAgent 了？

**Comment by wuliaodexiaoluo** [comment]
好像是，我尝试了 CC （实际上是测试节点可用性）然后被 BMCLAPI 拉入黑名单，Python Requests 默认的 UA 会被掐连接

**Comment by wuliaodexiaoluo** [comment]
研究了半天也没研究出来啥问题，只能定为大量请求被 BMCLAPI 拉入黑名单

**Comment by allMagicNB** [comment]
综上讨论结果，这应当不是 PCL 的问题，先关了……
如果您认为不是的话，可以继续 Comment……
