### ISSUE TITLE
更精准地表述“关于与鸣谢”中的作者部分

### ISSUE THREAD

**Issue by Silverteal** [Hex-Dragon/PCL2#3583]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

![1711798695474](https://github.com/Hex-Dragon/PCL2/assets/67404722/d65e1b7a-20f3-4aff-bd8e-94b4d9041799)
将图示内容的第二行修改为“Plain Craft Launcher 作者，几乎全部代码都是这一个人敲的。”

### 原因

discussions #3487 提到的表述问题虽然无伤大雅，但修改得更准确也同样方便  
我想这应该是顺手的事，故提交此问题。

**Comment by LTCatt** [comment]
建议之后少提这种 issue，改这个字我还得加进更新日志、写 commit 来源，浪费几分钟，不改一会儿又要被扣帽子还不得不改，纯纯拉我血压

**Comment by Silverteal** [comment]
> 建议之后少提这种 issue，改这个字我还得加进更新日志、写 commit 来源，浪费几分钟，不改一会儿又要被扣帽子还不得不改，纯纯拉我血压，并且改这个对优化启动器功能没有一丁点帮助……

很遗憾在凌晨1点听到这个消息，我会考虑，祝您一切顺利……
