### ISSUE TITLE
添加设置“快速开关模组”

### ISSUE THREAD

**Issue by NormalZombie** [Hex-Dragon/PCL2#3584]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

在设置中添加“快速开关模组”选项，能够将版本设置-Mod管理变为旧版的样式，即红石灯图标+单击即可开关模组

### 原因

大部分玩家都会安装不少模组，我最初选择PCL的核心原因就是动画流畅且利于管理模组。但现在模组全都显示它的图标，开关还得多点一个按钮...作为一个安装的模组全都没有图标的速通玩家，我只能看着一堆灰色框框陷入沉思...

**Comment by allMagicNB** [comment]
#2333＆#2697
> 仔细寻思了一下，暂时不考虑制作快速选择相关的功能，这些都超出启动器范畴了：它不是 Mod 管理器，也不是文件管理器……
> 抱歉 :/

**Comment by allMagicNB** [comment]
#2939

**Comment by allMagicNB** [comment]
额
![image](https://github.com/Hex-Dragon/PCL2/assets/116283787/ba605c02-bc6c-4c2c-a133-c7ef9854a60c)

**Comment by allMagicNB** [comment]
#3073
