### ISSUE TITLE
[虽重但提]为各种`因电脑特殊原因`无法正常启动游戏提供`JAVA下载`功能

### ISSUE THREAD

**Issue by kong-que-dnf123** [Hex-Dragon/PCL2#3585]
### 检查项

- [ ] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

如题，添加手动下载JAVA

### 原因

虽然搜过已经有过很多提过拒绝的...
但是对于某些电脑有特别原因还是有一定必要
如电脑由于显卡原因对于部分JAVA无法正常启动
![image](https://github.com/Hex-Dragon/PCL2/assets/120994373/9dce3f52-2761-4d21-9d67-b636cbb4914f)
此时由于我的电脑存在“无法启动”的JAVA导致无法触发自动下载
（比如我这台电脑JRE8-80302，JRE8-80341，JDK8-80302皆失败）
最后只能手动下载JAVA以试出了成功启动的JAVA（JRE8-80401） ~（整挺好，第一次手动下载就成功了）~
顾对于电脑较为特殊的应提供手动下载JAVA

--------------------------------------------------------------------------------------------------------------------------------
又及：
如果真的考虑的话还是reopen #1801 比较好吧...

**Comment by Pigeon0v0** [comment]
可以考虑直接调用启动器下载 Java，从 BMCLAPI 拉的 Java 是 8u51 还是 8u60

**Comment by wuliaodexiaoluo** [comment]
BMCLAPI 的 Java 版本列表 Url 指向的是 Mojang API
Mojang API 分别提供了  8u51、8u74 、 8u202
但只有 8u51 是 Windows 版本，其他的 8u74/8u202 为 Linux/Unix 平台

**Comment by wuliaodexiaoluo** [comment]
BMCLAPI 的 Java 版本列表 Url 指向的是 Mojang API
Mojang API 分别提供了 8u51、8u74 、 8u202
但只有 8u51 是 Windows 版本，其他的 8u74/8u202 为 Linux/Unix 平台

EDIT:如果需要选择版本就需要合适的下载源，但是 Microsoft OpenJDK 不提供 JDK8 链接，Oracle OpenJDK8 是 32 位版本，Adoptium OpenJDK 使用的是 GitHub Release 作为下载服务器，IB J9 OpenJDK 与 ModLoader 和 Mod 的兼容性又极差，走高校镜像站流量太大那边会下掉 Adoptium 镜像或者 403，会影响其他人使用

综上所述龙猫不太可能制作

**Comment by LTCatt** [comment]
特殊原因需要下载特定版本的 java 我也没有下载源啊 =。=
这种还是手动处理的好……
