### ISSUE TITLE
[优化] 在整合包的 Mod 下载部分时设置最大超时时间，到达这个时间直接跳过然后要求 User 手动下载

### ISSUE THREAD

**Issue by wuliaodexiaoluo** [Hex-Dragon/PCL2#3586]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

部分 ModPack 的 Mod 可能无法正常下载，会一直卡在 Mod 下载

### 原因

如果关闭 PCL 会因为 PCL 版本列表显示问题会出现无法加载未完成的下载的版本，导致磁盘在一瞬间少了几十几百兆
并且调试模式下日志会有很多的
```
[15:34:20.752] [Report] FPS 62, 动画 0, 下载中 3（0 B/s）
```
就有点影响阅读日志

**Comment by allMagicNB** [comment]
可以想象下已经下载了 99%，之后突然啪的一下，失败了，前功尽弃了

**Comment by wuliaodexiaoluo** [comment]
> 可以想象下已经下载了 99%，之后突然啪的一下，失败了，前功尽弃了

要不然跳过这个 Mod ？

**Comment by hejiehao** [comment]
> > 可以想象下已经下载了 99%，之后突然啪的一下，失败了，前功尽弃了
> 
> 要不然跳过这个 Mod ？

这不 HMCL 操作

**Comment by LTCatt** [comment]
下载卡了不应该是由启动器强制结束的，应该等玩家看到后自行决定等待还是叉了……
`无法加载未完成的下载的版本` 那是另一个 bug 导致的。
