### ISSUE TITLE
[优化] 使用重命名版本文件夹功能时，使用临时目录执行操作替代在 .minecraft\versions 文件夹执行操作

### ISSUE THREAD

**Issue by wuliaodexiaoluo** [Hex-Dragon/PCL2#3587]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

使用 %Temp%\PCL 或 %APPDATA%\PCL 等 PCL 使用的文件夹替代直接在  .minecraft\versions 执行重命名操作
因为 PCL 改变版本名的操作的方式是这样的
1.12.2 ---> Minecraft\ 1.12.2_Temp
Minecraft\ 1.12.2_Temp ---> Minecraft\ 1.12.2
这样 BakaXL 在检查版本文件更改时会报错崩溃 (没有更新路径)

### 原因

这个功能可能会导致部分启动器崩溃 (BakaXL)

**Comment by LTCatt** [comment]
这应该是 BakaXL 的 bug 吧……
没道理不让人改文件夹名啊（

**Comment by allMagicNB** [comment]
BakaXL 的 Repo 现在 Open 的 Issue 都不知道多少个了（

**Comment by wuliaodexiaoluo** [comment]
> 这应该是 BakaXL 的 bug 吧…… 没道理不让人改文件夹名啊（

额，我好像没说不让改
我指的是执行重命名的版本文件夹先 **扔到临时目录**，完成后再扔回来

**Comment by wuliaodexiaoluo** [comment]
> BakaXL 的 Repo 现在 Open 的 Issue 都不知道多少个了（

120 个。。。。

**Comment by hejiehao** [comment]
我认为如果这个 Issue 的目的只是为了让 BakaXL 不崩溃，那么我觉得还是由 BakaXL 那边处理比较好

**Comment by wuliaodexiaoluo** [comment]
或许之后就有了？
而且相交比 tt 那个大鸽子（提交的 Issue 基本都不看的 [#664](https://github.com/BakaXL-Launcher/BakaXL/issues/664)），我觉得在这里发 Issue 更可能解决问题
