### ISSUE TITLE
建议：补全文件按钮可以补全mod加载器支持库以及相关文件

### ISSUE THREAD

**Issue by LDTchara** [Hex-Dragon/PCL2#3588]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

如标题所述。

### 原因

这项优化让我可以更方便地在多个电脑之间使用同一版本的mc。
如果没有这项优化，我每次都必须重新下一遍对应版本&mod加载器的mc才能使用原来的版本，或者重新安装对应版本然后重新装模组和调配置并浪费114514小时，让操作变得很麻烦。
（相关事例：我把能正常启动的1.20.1 forge47.2.20的mc用U盘传输到另一台电脑上，结果另一台电脑打不开该版本mc，尝试补全文件无果，重下了个相同版本的MC然后原来那个打不开的mc就好使了。后来发现补全文件只能补全MC本体的文件于是便提交了这个issue）

**Comment by Pigeon0v0** [comment]
你如果复制了整个 .minecraft 文件夹不会打不开的

**Comment by wuliaodexiaoluo** [comment]
不可能吧。。。。
导出崩溃日志给下？

**Comment by LDTchara** [comment]
> 不可能吧。。。。 导出崩溃日志给下？ 还是说你只是拷贝了 versions ？

对，versions里的那个版本文件夹

**Comment by hejiehao** [comment]
我建议 https://github.com/Hex-Dragon/PCL2/discussions/100

**Comment by LDTchara** [comment]
> 我建议 #100

懒得整成整合包

**Comment by LTCatt** [comment]
技术上无法实现，Mod Loader 支持库是现场编译的，只能重新安装不能补全

**Comment by LDTchara** [comment]
让启动器检测Libraries文件夹里的文件是否缺失，缺失就重新编译（）

**Comment by LTCatt** [comment]
建议你想跨电脑使用的话导出整合包或者把 libraries 文件夹一起拷了……
