### ISSUE TITLE
意外弹出MC更新提示

### ISSUE THREAD

**Issue by WForst-Breeze** [Hex-Dragon/PCL2#359]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

打开PCL2时，弹出 22w44a 和 22w45a 的更新提示，但是这些提示**以前已经弹出过了**。
由于这个bug触发是一次性的，所以可能无法提供更多有用的信息……如果我所提供的这一点点信息无法让您确认此bug的话，很抱歉>n<

### 重现步骤

可能无法复现……这个bug的触发很意外，导致我没来得及开调试模式。抱歉啦……

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/9981827/Log2.txt)

**Comment by LTCatt** [comment]
……额，但你传的日志里根本没这个弹窗

**Comment by WForst-Breeze** [comment]
草，是玄学，我上传完附件还特地下载一边来确认没传错。怎么又变成别的日志了……蒜了蒜了

**Comment by WForst-Breeze** [comment]
今天这个问题又出现了，这里补充一下log，开了调试模式了已经qwq：
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10148131/Log1.txt)

**Comment by LTCatt** [comment]
umm 我估计是你获取到了老的游戏版本信息， **很可能是获取到了老的缓存** 导致的，而不是启动器的问题……
还有其他人也有这个情况吗？如果是普遍现象我可能得重新想个办法检测，如果是个别现象就算了。

**Comment by LTCatt** [comment]
没有其他人出现这个情况吗？
再等几天如果还是没有的话我就关了 =。=

**Comment by dongge0210** [comment]
我这个没有发生

**Comment by Louis-ZYH** [comment]
你难道没有注意到那个“清除缓存”按钮吗？？？？？？？？？？？

**Comment by LBZiXL** [comment]
我之前也发生过（怎么现在我才看到这个议题）

**Comment by LTCatt** [comment]
没法复现啊，还是太玄学了……算了（头秃
