### ISSUE TITLE
赞助版自定义主页预设（Minecraft新网）无法加载

### ISSUE THREAD

**Issue by scattered-leaves** [Hex-Dragon/PCL2#3590]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

<img width="617" alt="image" src="https://github.com/Hex-Dragon/PCL2/assets/121725066/32418ef0-b081-4e4b-8357-9e1fd7010157">
拨测结果https://boce.aliyun.com/detect/http/dc16f1cfb4624ec7a33ba93fa5023525
大部分返回403错误

### 重现步骤

赞助版：
设置->个性化->主页
选择预设，选中“Minecraft新网”后返回主页

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14819936/Log1.txt)

**Comment by wuliaodexiaoluo** [comment]
自定义主页预设问题不予受理，请自行联系作者，感谢反馈

**Comment by wuliaodexiaoluo** [comment]
```
[14:02:35.272] [Start] 程序版本：Snapshot 2.6.8（305）
```

以及您使用的程序版本过旧了，Minecraft 新闻已经切域名了

**Comment by wuliaodexiaoluo** [comment]
@allMagicNB 来 Closed 一下
