### ISSUE TITLE
“更多”页面侧边栏显示错误

### ISSUE THREAD

**Issue by DoubtedYapper71** [Hex-Dragon/PCL2#3594]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![98f5b1c1e336df266abe490f5ceaf87c](https://github.com/Hex-Dragon/PCL2/assets/107922760/a6d4fdb9-a978-4eab-815f-d7c53ecc0c69)
如图

### 重现步骤

打开启动器后先打开下载页面，再打开更多页面可以触发

### 日志与附件

[Log.txt](https://github.com/Hex-Dragon/PCL2/files/14836446/Log.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14836449/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14836452/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14836453/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14836454/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14836455/Log5.txt)

**Comment by burningtnt** [comment]
#3402 ，感谢您的反馈

**Comment by JingHai-Lingyun** [comment]
#2982 #3042，重复啦
