### ISSUE TITLE
给世界改名后下载mod无法锁定该世界mod文件夹

### ISSUE THREAD

**Issue by xuyunfengshuai** [Hex-Dragon/PCL2#3595]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

比如下载1.20.4后改名为“帅哥”下载mod时无法自动锁定该世界mod文件夹

### 重现步骤

给世界改汉字名在下载对应游戏版本mod

### 日志与附件

[Uploading Log1.txt…]()

**Comment by allMagicNB** [comment]
请等待 `Uploading XXX` 字样消失后再进行下一步操作……

**Comment by wuliaodexiaoluo** [comment]
```
[08:39:11.870] [Comp] 允许 Forge：True，允许 Fabric：False
[08:39:11.870] [Comp] 使用当前版本的 mods 文件夹作为默认下载位置（As）
```
没有复现成功.jpg 可能是没有更新的旧版本

**Comment by wuliaodexiaoluo** [comment]
这个，可能是没开版本隔离（也可能是删过 Setup.ini 自己忘了
不管怎么样建议 Closed 掉

**Comment by LTCatt** [comment]
由于长期未回复且提供的信息不足暂时关闭，若有需要可以在这里继续回复
