### ISSUE TITLE
下载mod页面缺失1.20.5快照版本

### ISSUE THREAD

**Issue by xxtg666** [Hex-Dragon/PCL2#3599]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

mod对应的curseforge页面上有1.20.5-Snapshot版本，而PCL2不显示
![image](https://github.com/Hex-Dragon/PCL2/assets/68174188/97ad7655-56fc-4391-8bb1-ee200bf046b2)
![image](https://github.com/Hex-Dragon/PCL2/assets/68174188/8be1555c-c9a7-4f0b-af6c-2bd047360272)

### 重现步骤

打开任意一个mod的下载界面

### 日志与附件

（这不需要日志吧？

**Comment by xxtg666** [comment]
HMCL是有的，推测PCL是根据服务器上的版本号信息匹配自身数据库中的版本信息，而HMCL直接使用服务器上的原始信息
![image](https://github.com/Hex-Dragon/PCL2/assets/68174188/684085e0-7328-4571-8890-60f8153d6369)

**Comment by LTCatt** [comment]
看了看，CurseForge 把它放进了 `latestFiles`，但没放进 `latestFilesIndexes`
或许可以想办法合并一下，头疼

**Comment by LTCatt** [comment]
好了好了把这俩玩意儿并了并
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/4ea3b1a9-92d4-4db8-9319-e3e7f8db20bc)
