### ISSUE TITLE
24w14a 以上版本要求 Java21

### ISSUE THREAD

**Issue by JingHai-Lingyun** [Hex-Dragon/PCL2#3601]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

https://www.minecraft.net/zh-hans/article/minecraft-snapshot-24w14a

> The game now requires Java 21

24w14a 开始要求 Java 21 来启动游戏

**Comment by allMagicNB** [comment]
@LTCatt
