### ISSUE TITLE
罕见情况下，pcl自动更新错误的下载更新至PCL数据文件夹导致无法重启

### ISSUE THREAD

**Issue by scattered-leaves** [Hex-Dragon/PCL2#3605]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我遇到果两次，毫无前兆，启动PCL2后无特殊操作，无任何提示，过段时间后自动更新关闭
由于该部分代码未公开，我无法通过分析代码为龙猫提供帮助

### 重现步骤

无法重现

### 日志与附件

日志已手动消敏
pcl2所在位置使用"."代替，其他敏感内容使用"*"代替
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14861008/Log1.txt)

**Comment by WForst-Breeze** [comment]
没太明白，意思是启动 PCL 后 **没有弹出更新提示弹窗** 但 **开始了启动器更新** 且 **右下角没有更新进度** 吗？

`导致无法重启` 是什么意思呢🤔

**Comment by scattered-leaves** [comment]
> 没太明白，意思是启动 PCL 后 **没有弹出更新提示弹窗** 但 **开始了启动器更新** 且 **右下角没有更新进度** 吗？
> 
> `导致无法重启` 是什么意思呢🤔

是的

**Comment by WForst-Breeze** [comment]
> 是的

看完日志感觉这个复现有点困难😥

“导致无法重启” 是什么意思呢

**Comment by allMagicNB** [comment]
```
[10:20:18.173] [System] 更新已开始，静默：True
[10:20:18.174] [Server] 重要等级 2，更新公告 True
[10:20:18.174] [Loader] 加载器 PCL 服务 状态改变：Finished
[10:20:18.178] [Loader] 加载器 启动器更新 状态改变：Loading
```

**Comment by scattered-leaves** [comment]
> ```
> [10:20:18.173] [System] 更新已开始，静默：True
> [10:20:18.174] [Server] 重要等级 2，更新公告 True
> [10:20:18.174] [Loader] 加载器 PCL 服务 状态改变：Finished
> [10:20:18.178] [Loader] 加载器 启动器更新 状态改变：Loading
> ```
额。。但我主要要反馈的问题是自动更新下载后完成后关闭了旧版本但一直不重启

**Comment by youzi-2333** [comment]
嘶……从日志看上去，好像是 PCL 没有正确退出，然后在结尾加了几个空行就退了……

不太确定是不是偶发问题，要不重新复现一遍再看看？

**Comment by scattered-leaves** [comment]
> 嘶……从日志看上去，好像是 PCL 没有正确退出，然后在结尾加了几个空行就退了……
> 
> 不太确定是不是偶发问题，要不重新复现一遍再看看？

已尝试，无法复现

**Comment by allMagicNB** [comment]
#3044

**Comment by allMagicNB** [comment]
请发送完整日志……

**Comment by scattered-leaves** [comment]
> 请发送完整日志……

由于尝试复现时未备份日志，已被覆盖，已上传日志来自Windows记事本缓存，读取日志时已确认PCL2已结束运行

**Comment by allMagicNB** [comment]
> > 请发送完整日志……
> 
> 由于尝试复现时未备份日志，已被覆盖，已上传日志来自Windows记事本缓存，读取日志时已确认PCL2已结束运行

可以上传所有日志（Log1～5）

**Comment by scattered-leaves** [comment]
> > > 请发送完整日志……
> > 
> > 
> > 由于尝试复现时未备份日志，已被覆盖，已上传日志来自Windows记事本缓存，读取日志时已确认PCL2已结束运行
> 
> 可以上传所有日志（Log1～5）

上传的日志已经是完整的了，其他的日志已被覆盖，现在有的日志已经无意义了
但是，我认为可能与PCL2所在路径有关，因此我重新消敏并上传了已上传的日志
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14861478/Log4.txt)
