### ISSUE TITLE
如果mod在官网的原名不是中文，在完全加载前会有乱码

### ISSUE THREAD

**Issue by yangzimugreg** [Hex-Dragon/PCL2#3607]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![screenshot-1712216540894](https://github.com/Hex-Dragon/PCL2/assets/161196998/8bc22bb0-700b-428f-a397-c6ab5a90bc8a)
![screenshot-1712216558152](https://github.com/Hex-Dragon/PCL2/assets/161196998/c14826d8-881f-4451-80d5-11ba6e9402f4)

### 重现步骤

下载(https://www.curseforge.com/minecraft/mc-mods/time-speed-mod)，并反复刷新（也许有很多mod容易触发）

### 日志与附件

[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14863107/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14863109/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14863110/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14863111/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14863112/Log3.txt)

**Comment by Chiloven945** [comment]
感觉是西里尔字母的锅……

**Comment by yangzimugreg** [comment]
描述有误：至少中英文都正常
另外除了最显眼的字符有bug，其它字符正常。

**Comment by siki666** [comment]
感觉PCL2有点怠惰式加载
我经常需要按一遍刷新才能完全加载
这中间很多问题以前都没发现过的

**Comment by LTCatt** [comment]
![image](https://github.com/user-attachments/assets/01c8ff21-8a33-49df-b237-fe802f6a1124)
无法复现

**Comment by lactobionicAcid** [comment]
这个模组的 mods.toml 文件存在字符丢失......
然后被 PCL 使用 GB18030 编码了，变成了完全不可读的中文乱码......
```
[[mods]]
    modId="b3m"
    version="1.20-01"
    displayName="Вращение Земли Майнкрафт�?ка�?"
```

**Comment by LTCatt** [comment]
umm 我楼上的图就是直接用 mods.toml 读到的数据加载的，也没看到乱码啊……
