### ISSUE TITLE
可一键筛选可更新模组，且可一键更新

### ISSUE THREAD

**Issue by Xiaoqianghepipi** [Hex-Dragon/PCL2#3608]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

在Mod管理中可勾选“仅显示可更新的模组”，并加上按钮“一键更新所有模组”可以一键更新所有可以更新的模组，在更新完毕后旧模组放在同一文件夹并移动到回收站

### 原因

我需要这个功能来更加快捷更新所有模组。很多人都有一键更新所有模组的需求，但如果没有这个功能，就不能很方便的一键更新模组了了。

**Comment by allMagicNB** [comment]
目前版本只要全选就会自动更新有更新的 Mod……

**Comment by Silverteal** [comment]
在Mod管理页面选择“全选”，点击“更新”即可。
