### ISSUE TITLE
版本设置>>>mod管理界面>>>无法拖入mod用于在此版本添加该mod

### ISSUE THREAD

**Issue by FCXRDSS** [Hex-Dragon/PCL2#3609]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

版本设置>>>mod管理界面>>>无法拖入mod用于在此版本添加该mod
但是手动移入mod文件夹PCL可以识别到mod

### 重现步骤

版本设置>>>mod管理界面>>>无法拖入mod用于在此版本添加该mod
放入mod文件夹PCL可以识别

### 日志与附件

https://github.com/Hex-Dragon/PCL2/assets/136197412/197ca3e6-f02a-48cd-8f69-08580ffdabb1

**Comment by allMagicNB** [comment]
您是否使用了管理员权限启动启动器？

**Comment by allMagicNB** [comment]
@FCXRDSS

**Comment by FCXRDSS** [comment]
> 您是否使用了管理员权限启动启动器？


https://github.com/Hex-Dragon/PCL2/assets/136197412/5b7ec243-73f4-4271-b07c-54c4bbea30df

启用了的呀

**Comment by allMagicNB** [comment]
启用了就无法使用拖放功能

**Comment by FCXRDSS** [comment]
嗯...这是为什么的

**Comment by allMagicNB** [comment]
> 嗯...这是为什么的

你试试不用管理员行不行

**Comment by FCXRDSS** [comment]
行了

**Comment by allMagicNB** [comment]
#2531

**Comment by wuliaodexiaoluo** [comment]
> 嗯...这是为什么的

UAC 的姊妹技术 UIPI 禁止了不同权限下的进程通讯行为（你可以理解为你打算去另一个学校找你的朋友，但因为你不是这个学校（权限组）所以保安不让你进），在启用UAC的情况下 Windows 资源管理器默认是 Users 权限组，以管理员权限启动的 PCL 是 Administrators 权限组，所以进程通讯被 UAC 掐掉了

**Comment by Pigeon0v0** [comment]
> 解决这个问题的最好办法是把 UAC 关掉或者以普通权限执行 PCL 程序

解决办法并不是关掉 UAC，而恰恰相反...
