### ISSUE TITLE
littleskin皮肤应用于正版登录时尺寸不匹配？（可能与启动器无关）

### ISSUE THREAD

**Issue by VolgaRiver1211** [Hex-Dragon/PCL2#3610]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

https://github.com/Hex-Dragon/PCL2/assets/166012044/66754cbb-f6dd-4e12-9050-02ae1df193e0
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14865117/Log4.txt)

### 重现步骤

正版登录，修改皮肤。。。

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14865116/Log3.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14865120/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14865121/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14865123/Log2.txt)

**Comment by allMagicNB** [comment]
能给下皮肤地址吗？

**Comment by JingHai-Lingyun** [comment]
看了眼提到的皮肤，是 128x128 的

**Comment by allMagicNB** [comment]
你去官网试试能不能使用

**Comment by wuliaodexiaoluo** [comment]
128x128 。。。
这不是官方推荐的尺寸，强行应用可能会出现显示不全的问题，如果官网不能应用就是真的不能用了

**Comment by LTCatt** [comment]
正版登录不支持使用超出尺寸限制的皮肤……
不过如果这是因为 PCL 没有检测皮肤尺寸的话那可以作为 bug 修复

**Comment by LTCatt** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/21ae186e-87b3-4fd9-8364-70e11e6c9470)
PCL 不允许上传这个皮肤啊 =。=

**Comment by allMagicNB** [comment]
先看看官方和 API 支不支持吧……

**Comment by wuliaodexiaoluo** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/160083863/0fa46372-b0e3-4621-8f49-899c15fc93ac)
官网不支持上传这个尺寸的皮肤，应该是超了

**Comment by allMagicNB** [comment]
> 官网不支持上传这个尺寸的皮肤，应该是超了

试试 API

**Comment by wuliaodexiaoluo** [comment]
> > 官网不支持上传这个尺寸的皮肤，应该是超了
> 
> 试试 API

给我点时间

**Comment by LTCatt** [comment]
那应该不是 PCL 的 bug 了 =。=

**Comment by JingHai-Lingyun** [comment]
应该不是，不知道为什么有人上传这种超规格的皮肤
这种情况下只能 LittleSkin 内用
~~我曾经见到过有人发了2048x2048的~~

**Comment by wuliaodexiaoluo** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/160083863/ef45b115-980a-4dd5-8ae4-fa7a80835879)
试了下 API 保存，API 给返了个 405.......

**Comment by JingHai-Lingyun** [comment]
后续聊转#3618

**Comment by Silverteal** [comment]
根据authlib-injector的服务端规范，对于皮肤站而言是允许使用尺寸为64x64或64x32整数倍的皮肤的（以下称为高清皮肤）。但是mojang官方不支持上传高清皮肤。原版游戏不支持读取高清皮肤，安装authlib-injector或者custom skin loader后即可读取。
