### ISSUE TITLE
Launch Custom Setup 2-Bug

### ISSUE THREAD

**Issue by MKhezhenhao** [Hex-Dragon/PCL2#3626]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

装载并点击Launch Custom Setup 2后，打开PCL 2需要重新解锁滑稽彩，重新解锁后，再次点击Launch Custom Setup 2，仍然需要重新解锁

### 重现步骤

1.打开并关闭Launch Custom Setup 2
2.打开PCL 2
3.弹出需要重新解锁滑稽彩
4.重新解锁滑稽彩
5.再次打开并关闭Launch Custom Setup 2
6.打开PCL 2
7.仍然需要重新解锁滑稽彩

### 日志与附件

![屏幕截图 2024-04-06 153804](https://github.com/Hex-Dragon/PCL2/assets/166205691/5bb7e1c1-8c9f-4eb3-8335-9e9d19cc8b6a)
Launch Custom Setup 2(https://afdian.net/p/01a50e74a93811e98e6d52540025c377)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14892937/Log1.txt)

**Comment by Silverteal** [comment]
？

**Comment by Silverteal** [comment]
请上传描述中的“Launch Custom Setup 2”和启动器日志

**Comment by allMagicNB** [comment]
日志呢？
~~还有，这是啥玩意啊……~~

**Comment by Ad-closeNN** [comment]
Launch Custom Setup 2是啥啊...必应搜不到

**Comment by burningtnt** [comment]
那玩意儿，不会是 PCL2 隐藏主题破解器吧……

**Comment by Ad-closeNN** [comment]
> 那玩意儿，不会是 PCL2 隐藏主题破解器吧……

听名字不像

**Comment by hejiehao** [comment]
> 那玩意儿，不会是 PCL2 隐藏主题破解器吧……

6，祝他好运

**Comment by MKhezhenhao** [comment]
> > 那个玩意儿，不会是PCL2隐藏主题破解器吧……
> 
> 6、祝他运势好

不是，解锁的是这个(https://pan.baidu.com/s/1ifcSpcybM0Ma2mZC7QIFqg)
提取码：9ci4

**Comment by wuliaodexiaoluo** [comment]
```
[15:59:49.852] [Control] 普通弹窗：重新解锁提醒
由于新版 PCL 修改了滑稽彩的解锁方式，你需要重新解锁滑稽彩。
多谢各位的理解啦！
```
因为龙猫修改了滑稽彩解锁方式（在 4 月 1 那天点到启动按钮解锁）

如果是神秘紫无法解锁
见 #3316 
Im 发布了一项修复性更新，解决了识别码可能重复的问题，请等待龙猫解决这个问题

**Comment by Silverteal** [comment]
旧版本启动器不受支持，请勿使用。如果必须使用，请在新版本中通过帮助->备份启动器设置->备份注册表，完成使用旧版本后恢复注册表。
