### ISSUE TITLE
PCL2异常更改options.txt文件

### ISSUE THREAD

**Issue by jinshastudios** [Hex-Dragon/PCL2#3627]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在启动时会因为无法创建options.ini导致options.txt内容被强制重置的问题
即便已经修改完下次启动依然会重置

### 重现步骤

重新开启PCL2并启动游戏就可以触发

### 日志与附件

![Snipaste_2024-04-06_16-47-48](https://github.com/Hex-Dragon/PCL2/assets/76798363/06cde61a-e990-4f70-b847-fb24780fb0af)

**Comment by allMagicNB** [comment]
#3616
