### ISSUE TITLE
更新mod时错误的给1.20.2MC选择了Sodium0.5.8

### ISSUE THREAD

**Issue by FQO3** [Hex-Dragon/PCL2#3628]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在1.20.2提示更新Sodium并更新后启动报错：不支持该版本Sodium

![image](https://github.com/Hex-Dragon/PCL2/assets/111474347/63b74387-b12d-4850-9c6e-d1ae54e31ff8)

![image](https://github.com/Hex-Dragon/PCL2/assets/111474347/a211cd7a-05f1-42dd-b7a5-f66058d9ddeb)

同理还有铟

![image](https://github.com/Hex-Dragon/PCL2/assets/111474347/2d36486b-9a7a-4441-91e1-e742999fe3df)

### 重现步骤

1. 下载MC1.20.2
2. 安装sodium0.5.3
3. 安装铟1.0.27
4. 去mod管理更新这两个mod
5. 再次启动提示不兼容
6. 复现完毕

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14893300/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14893301/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14893297/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14893298/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14893299/Log5.txt)

**Comment by mc-124** [comment]
大概是CurseForge或Modrinth的问题

**Comment by hejiehao** [comment]
我看看 API

**Comment by hejiehao** [comment]
<img width="769" alt="6f00c8d7f835d4a8a67d25ff29bfe856" src="https://github.com/Hex-Dragon/PCL2/assets/98140773/a8996126-119a-4a2b-a767-d48fa9e98522">
🤔

**Comment by mc-124** [comment]
close掉吧

**Comment by hejiehao** [comment]
应该是 CurseForge 问题

**Comment by mc-124** [comment]
> 应该是 CurseForge 问题

我感觉更有可能是作者自己整错

**Comment by hejiehao** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/98140773/2f4ccc58-e81f-468d-9780-eb93cc70c623)
![image](https://github.com/Hex-Dragon/PCL2/assets/98140773/3253ebe2-5cb4-458f-8286-990348298121)
![image](https://github.com/Hex-Dragon/PCL2/assets/98140773/c02051a4-f264-4bbf-acca-bad7f5173f09)

**Comment by JingHai-Lingyun** [comment]
curseforge api 有问题

**Comment by mc-124** [comment]
这机器人搞什么

**Comment by LTCatt** [comment]
这是作者自己勾了 1.20.2，可以找 mod 作者反馈

**Comment by wuliaodexiaoluo** [comment]
Mod 作者在 GitHub 勾选了限制只有向 Repo 提交过 Pull Request 才能提交 Issue
我现在也没有合适的办法给 Mod 作者反馈
________________________________
发件人: 龙腾猫跃 ***@***.***>
发送时间: 2024年4月7日 0:54
收件人: Hex-Dragon/PCL2 ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [Hex-Dragon/PCL2] 更新mod时错误的给1.20.2MC选择了Sodium0.5.8 (Issue #3628)


这是作者自己勾了 1.20.2，可以找 mod 作者反馈

―

**Comment by wuliaodexiaoluo** [comment]
算了我直接把作者 @ 过来看吧
@jellysquid3 
To give you a brief explanation, the 0.5.8 version of Sodium was mistakenly marked as 1.20.2, but in fact this is the version that works with 1.20.4
Please fix it
Thanks
