### ISSUE TITLE
[BUG] 在删除一个 .minecraft 文件夹的时候，二次确认窗口有两个“取消选项”

### ISSUE THREAD

**Issue by SuoHouDaiShi** [Hex-Dragon/PCL2#3629]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![图片](https://github.com/Hex-Dragon/PCL2/assets/119282947/1b2d90e1-a492-4734-9e71-68b98a878d2a)
如图所示（

### 重现步骤

1、在 PCL 启动页点击版本设置
2、右键任意一个 .minecraft 文件夹，点删除
3、弹出的二次确认窗口中有两个“取消键”

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14893303/Log1.txt)

**Comment by allMagicNB** [comment]
#1436
