### ISSUE TITLE
模组更新功能建议

### ISSUE THREAD

**Issue by Qian-F** [Hex-Dragon/PCL2#3632]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

1. 将旧版本模组文件添加后缀 xxx.jar.old 并留在模组文件夹中方便回滚
2. 增加一个可选模组更新界面标明更新后的版本号和更新源，让用户可以选择更新哪些模组

### 原因

1. 如果没有这项优化，我每次出现模组冲突都必须从回收站中找回旧版本mod，让操作变得很麻烦。
2. 可以让模组更新操作更高效

**Comment by JingHai-Lingyun** [comment]
> 1. 将旧版本模组文件添加后缀 xxx.jar.old 并留在模组文件夹中方便回滚

回滚.... 我估计不太可能做。如果你更新了好几次会留下太多无用文件的

> 2. 增加一个可选模组更新界面标明更新后的版本号和更新源，让用户可以选择更新哪些模组

目前可更新的 Mod 会有 ![image](https://github.com/Hex-Dragon/PCL2/assets/109946426/bbd37c2d-76ed-47cf-a960-acd6a3770244) 标志，鼠标覆盖上去之后会显示版本对比，右键可以查看更新日志

---

先加一个待处理看看咋说吧。另外，我们**不建议**将多个请求交在一个 Issue 中

**Comment by Qian-F** [comment]
1. 不是启动器回滚，是方便玩家手动回滚，丢在回收站有点麻烦了（不过这个问题也不是很大）
2. 整合包模组过多时（比如200+/300+）可能用户并不愿意一个一个看，而且增加一个可选界面明显效率更高

**Comment by LTCatt** [comment]
1. 没啥必要，反而越更新列表越长
2. 和 #683 合并了
