### ISSUE TITLE
下载版本时添加版本描述

### ISSUE THREAD

**Issue by MGWtino0** [Hex-Dragon/PCL2#3633]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

当用户下载一个mc版本时，在版本下载界面添加简要描述，以便玩家获知版本的相关信息和新内容；或者添加跳转链接为用户提供获知版本信息的途径（让玩家自己去看新版本更了什么
具体位置在这个界面 可以加个按钮弹出新版本介绍的提示框 也可以写简单的描述
![image](https://github.com/Hex-Dragon/PCL2/assets/140265892/e5f234a5-548f-4857-8d2e-41672da95a97)
介绍的内容可以是：新的方块、物品、生物等；修复的~~特性~~漏洞；较大的技术性更改（如使用的Java版本、生成与刷新机制）
不过工作量好像有点多……（
~~建议跳转至wiki或者官网介绍（~~

### 原因

许多mc玩家（包括本人）看到新版本更新时，常常不知道版本更新内容。
这可能对玩家的生存产生障碍；也会干扰玩家的判断：
*“我是否应该下载这个版本？”*
这个问题时不时困扰我，由于我玩mc断断续续，时常不知道新内容 *（大概是我的问题）* ，因而觉得让玩家清楚版本特色是有必要的。

**Comment by JingHai-Lingyun** [comment]
目前你可以在这里找到版本更新日志（Minecraft Wiki）
![image](https://github.com/Hex-Dragon/PCL2/assets/109946426/eada5717-0fcf-4337-8640-1de8be9d27a7)

**Comment by LTCatt** [comment]
暂不考虑……抱歉（
