### ISSUE TITLE
最新版2.7启动时会重置我mc的全部设置

### ISSUE THREAD

**Issue by Funodite** [Hex-Dragon/PCL2#3637]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/Hex-Dragon/PCL2/assets/131584095/ae024bfb-d56b-47e2-bbfd-6e5df205ee00)

### 重现步骤

1、点击xxxx
2、往下滚，然后点击xxxx

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14896198/Log1.txt)

**Comment by JingHai-Lingyun** [comment]
#3616 请等待更新
