### ISSUE TITLE
 Minecraft 崩溃

### ISSUE THREAD

**Issue by MandyJo1** [Hex-Dragon/PCL2#3638]
### 检查项

- [ ] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃基本不是 PCL 的原因，请 **不要** 提交反馈。你可以在论坛或社区找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用 HMCL 启动，HMCL 没有出现问题。** 如果 HMCL 也无法启动就不是 PCL 导致的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

Minecraft 崩溃

### PCL 错误报告、日志与附件

[错误报告-2024-4-7_下午_04.48.40.zip](https://github.com/Hex-Dragon/PCL2/files/14896500/-2024-4-7_._04.48.40.zip)

**Comment by wuliaodexiaoluo** [comment]
因为安装整合包导致的崩溃问题不予受理，抱歉
感谢反馈

**Comment by wuliaodexiaoluo** [comment]
另外根据日志信息，这可能是目录包含零宽连字导致的，建议重命名目录

**Comment by JingHai-Lingyun** [comment]
日志可见 `Illegal char <?> at index 38` 
由于你的目录中包含非法字符（零宽连字符等）导致的无法启动，请尝试更换目录
这不是 PCL 启动器的问题

**Comment by allMagicNB** [comment]
> 日志可见 `Illegal char <?> at index 38` 
> 由于你的目录中包含非法字符（零宽连字符等）导致的无法启动，请尝试更换目录
> 这不是 PCL 启动器的问题

不，现在在修了，这是由于 `natives` 文件夹路径无法被 Java 所识别
所以这应当为重复……

**Comment by allMagicNB** [comment]
#3236

**Comment by JingHai-Lingyun** [comment]
看着不是 natives...
![image](https://github.com/Hex-Dragon/PCL2/assets/109946426/14af9856-66b7-4818-a2fa-b47c58bd4849)

**Comment by wuliaodexiaoluo** [comment]
我要不发个 Issue 允许临时目录启动？
