### ISSUE TITLE
关于使用外置皮肤站登录生成的第三方库文件以及wrapper文件被猫反作弊拦截的问题

### ISSUE THREAD

**Issue by WuGuovo** [Hex-Dragon/PCL2#3639]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

皮肤站生成登录的文件是authlib injector的jar第三方库文件，hmcl那边是因为把该文件放到了appdata里面所以不会被拦截，希望pcl也能修改一下存放路径避免反作弊拦截，javawrapper.jar文件和作者沟通了一下是是用来解决带特殊字符的文件夹没法启动 MC 的一个文件，不知道该文件能否用和上面的第三方库文件一样修改文件路径来避免被反作弊拦截

### 原因

因为服里玩家经常被反作弊拦截进不去服务器，所以希望能优化一下这个功能，最主要是每个玩家生成的该文件sha1值都不一样，没办法加白来让反作弊绕过该文件

**Comment by WuGuovo** [comment]
> 不对啊......SHA1 值不一样？ 可能是版本不同造成的，使用最新版即可

但是外置登录的第三方库文件好像没法没法这样过滤，我再尝试一下吧

**Comment by allMagicNB** [comment]
> 等等，为什么外置登录要生成第三方库？难不成你们那边的 authlib-injector 是一个 Fork，直接把玩家的数据写到 JAR 里了？

也许是说 authlib-injector 本体（

**Comment by wuliaodexiaoluo** [comment]
> > 也许是说 authlib-injector 本体（
> 
> 我很好奇反作弊是怎么读到 javaagent 的 EDIT: 关联 #3573

调用命令吧
jps -v 可以查看 jvm 参数的说

**Comment by LTCatt** [comment]
我看了看代码，现在 java wrapper 和第三方登录库都是放在 appdata 的啊？
是不是因为你的玩家没有更新 PCL，或者老版本 PCL 残留了那些文件在 MC 文件夹？

**Comment by LTCatt** [comment]
由于无回复且没有发现问题暂时关闭，有需要可以继续回复
