### ISSUE TITLE
检测不到已下载的JAVA11问题！

### ISSUE THREAD

**Issue by WaterDouble** [Hex-Dragon/PCL2#3640]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在java官网下载完Java11后无法正常识别，导致一些整合包无法正常游玩。

### 重现步骤

1、点击xxxx
2、往下滚，然后点击xxxx

### 日志与附件

无

**Comment by allMagicNB** [comment]
请尝试手动添加……

**Comment by WaterDouble** [comment]
已安装 尝试下载安装了两次并无卵用...

**Comment by allMagicNB** [comment]
发日志和 Java 安装路径

**Comment by LTCatt** [comment]
请补充日志

**Comment by wuliaodexiaoluo** [comment]
估计是不会来了，建议如果复现不了直接 Close 掉吧

**Comment by allMagicNB** [comment]
超时关闭，如果继续反馈请继续 Comment 所缺的信息。
