### ISSUE TITLE
部分前置mod没有正常显示

### ISSUE THREAD

**Issue by M3GCh1na** [Hex-Dragon/PCL2#3641]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

部分mod要求在安装了modA时，才会有前置modB，此类前置mod目前无法正常显示
例如：在安装了Sodium时，才会要求安装Indium

### 重现步骤

以Contniuity（纹理连接）为例
1、点开Mod下载页面，搜索Continuity
2、点开下载页面，没有提示要求Indium
![}RAIBG5~{YBDJ EX{UZA98P](https://github.com/Hex-Dragon/PCL2/assets/148378837/5e9f4188-d1f6-4029-b790-32587c51d86c)
3、在Modrinth或MC百科打开该mod，提示在安装了Sodium后同时要求安装Indium
![0U8TNH)YKKB`2MUZ{ITB7~S](https://github.com/Hex-Dragon/PCL2/assets/148378837/b85a3fb3-8335-4b32-a59a-0579b0b8e395)
![I%L8IC8G82~EFHFG7_ZRV}J](https://github.com/Hex-Dragon/PCL2/assets/148378837/2e064716-5be8-42a0-9ab1-5bb768b5f1a1)

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14897301/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14897302/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14897303/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14897304/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14897305/Log2.txt)

**Comment by allMagicNB** [comment]
哥你干啥呢

**Comment by M3GCh1na** [comment]
> 哥你干啥呢

刚写完然后点开常见问题一看发现已经有了，这东西能删掉吗

**Comment by burningtnt** [comment]
无需删除，直接关闭即可

**Comment by allMagicNB** [comment]
> 无需删除，直接关闭即可

~~他可能觉得这是黑历史~~
没事，谁还每个黑历史啊（

**Comment by M3GCh1na** [comment]
> > 无需删除，直接关闭即可
> 
> ~他可能觉得这是黑历史~ 没事，谁还没个黑历史啊（

还真是，主要是排查一晚上为啥纹理连接没效果然后才发现有个前置没装，寻思这回让我发现bug了结果成了小丑

**Comment by wuliaodexiaoluo** [comment]
#3267 
Collaborator 切下重复标签
