### ISSUE TITLE
[功能优化建议] 在win中支持快捷方式

### ISSUE THREAD

**Issue by chenxi-Eumenides** [Hex-Dragon/PCL2#3642]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

win中，能够识别文件夹的快捷方式，正常访问快捷方式对应的文件或文件夹。

## 当前版本

无法识别第一张图的快捷方式，只能使用第二图的软链接：

![image](https://github.com/Hex-Dragon/PCL2/assets/76398980/ffea9d4e-2da1-4cd7-b647-12597cfa7518)
![image](https://github.com/Hex-Dragon/PCL2/assets/76398980/9b3cdb05-3ff5-4227-8c4a-c89f71fc7dc3)

## 建议提出背景

目前，我的.minecraft文件夹内的各个文件夹被单独在另一处进行存储与管理，方便我使用pcl启动器（用win）与prism启动器（用linux）。

由于不同启动器.minecraft文件夹内的内容并不一致，所以我无法直接添加一个公共的.minecraft文件夹，只能分别链接里面的versions等文件夹。

添加该功能后，我能够直接在资源管理器中创建文件夹的快捷方式，通过快捷方式的方式链接versions等文件夹。

## 当前替代方案

目前我在win中使用powershell的New-Item命令创建软连接进行使用，这不太方便（即使只需要设置一次就行）。

（当然我在linux中使用mklink，但众所周知，linux的终端体验比win实在好太多了）

**Comment by allMagicNB** [comment]
其实这个快捷方式是个拓展名为 `lnk` 的文件……

**Comment by burningtnt** [comment]
？？？？？你直接添加游戏文件夹不就好了

**Comment by JingHai-Lingyun** [comment]
呃？没太听懂是啥意思

**Comment by burningtnt** [comment]
> 呃？没太听懂是啥意思

意思是让 Windows 的 .lnk 快捷方式可以被 PCL2 看作符号链接

**Comment by allMagicNB** [comment]
> > 呃？没太听懂是啥意思
> 
> 意思是让 Windows 的 .lnk 快捷方式可以被 PCL2 看作软链接。
> 
> 既然你都知道软链接是什么了，干嘛还嫌麻烦呢？

软链接的创造需要命令行，他是想不用指令，更方便点。

**Comment by LTCatt** [comment]
适用范围太小了，暂不考虑，抱歉 Orz
