### ISSUE TITLE
用pcl2自动安装的Fabric无法加载模组，但游戏正常运行

### ISSUE THREAD

**Issue by lee750717** [Hex-Dragon/PCL2#3646]
### 检查项

- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

用pcl2自动安装的Fabric版本启动后不会加载任何模组，但游戏正常运行，即使你添加了模组

### 重现步骤

1、进入pcl2启动器，并点击下载
2、点击1.20.1，并点击Fabric
3、点击“0.15.9”版本
4、点击开始安装
5、等待安装完成后，切换版本并下载一些模组(指不冲突的模组)
6、启动游戏

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14900855/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14900856/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14900857/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14900858/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14900862/Log5.txt)

**Comment by wuliaodexiaoluo** [comment]
这应该是 Fabric 跳过加载了
没有崩溃就不是 PCL 的问题。PCL 不会也不可能干涉 Mod 加载（在 Mod 管理禁用的除外）

**Comment by lee750717** [comment]
用hmcl下载一个整合包，可以正常使用；而使用pcl2下载同一个整合包，模组不能加载

**Comment by JingHai-Lingyun** [comment]
发一下游戏的日志[^1]看看？
[^1]: PCL启动器 > 版本设置 > 快捷方式 > 版本文件夹 > 找到 `logs` 文件夹 > 找到你启动后没有 Mod 那次的启动日志 zip

**Comment by lee750717** [comment]
[latest.log](https://github.com/Hex-Dragon/PCL2/files/14900964/latest.log)
没有压缩包，只有一个log

**Comment by JingHai-Lingyun** [comment]
我需要完整的启动日志，请再尝试通过 PCL 和 HMCL 分别启动一次，然后发送相应的日志

**Comment by wuliaodexiaoluo** [comment]
BakaXL 也不行
估计是 Fabric Bug

**Comment by lee750717** [comment]
因为用hmcl安装能正常加载，所以我来这里

**Comment by lee750717** [comment]
由hmcl安装，由pcl或者hmcl启动可以正常加载模组；
由pcl安装，由pcl或者hmcl启动都可正常加载模组

**Comment by wuliaodexiaoluo** [comment]
这貌似 Minecraft 连 Fabric 都识别不到

**Comment by lee750717** [comment]
此为hmcl安装，hmcl运行
[2024-04-08-1.log.gz](https://github.com/Hex-Dragon/PCL2/files/14901117/2024-04-08-1.log.gz)
[2024-04-08-2.log.gz](https://github.com/Hex-Dragon/PCL2/files/14901118/2024-04-08-2.log.gz)
第一次启动由于模组版本问题导致报错
第二次启动成功

**Comment by lee750717** [comment]
此为hmcl安装，pcl2运行
[2024-04-08-3.log.gz](https://github.com/Hex-Dragon/PCL2/files/14901139/2024-04-08-3.log.gz)

**Comment by lee750717** [comment]
皆成功加载模组

**Comment by JingHai-Lingyun** [comment]
很奇怪，我没看到 Mod 加载信息（六个 Minecraft 日志均如此）
貌似 Minecraft 没有加载 Fabric 或日志不完整
我无法在 `PCL 安装 Minecraft 1.20.1 + Fabric 0.15.9 + 自动选择 FabricAPI 并启动` 情况下复现此问题
---
附我的日志
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14901142/Log1.txt)
[latest.log](https://github.com/Hex-Dragon/PCL2/files/14901144/latest.log)

**Comment by lee750717** [comment]
PCL 安装 Minecraft 1.20.2 + Fabric 0.15.9 + 自动选择 FabricAPI 并启动也能复原

**Comment by lee750717** [comment]
PCL 安装 Minecraft 1.20.1 + Fabric 0.15.9 + 自动选择 FabricAPI 并启动是我第一次发现这个Bug时的配置，
目前已删除；使用hmcl安装后可以使用

**Comment by lee750717** [comment]
但最后两个模组加载成功，且能正常使用

**Comment by lee750717** [comment]
但最后两次启动模组都加载成功，且可以正常使用

**Comment by lee750717** [comment]
但最后两次启动，模组都加载成功，且可以正常使用

**Comment by 1wwwe2** [comment]
> PCL 安装 Minecraft 1.20.1 + Fabric 0.15.9 + 自动选择 FabricAPI 并启动是我第一次发现这个Bug时的配置， 目前已删除;使用hmcl安装后可以使用

我也是这个配置，目前跟楼主一样的情况

**Comment by wuliaodexiaoluo** [comment]
我也是，并且我这里连 Fabric 都识别不到，显示是原版。。。

**Comment by JingHai-Lingyun** [comment]
> C:\Users\liyiz\Desktop\mc\.minecraft\versions\1.20.1-TCS优化整合包V2.0-fabric-导入包\

发一下这个整合包？看看是不是特定包文件的问题

**Comment by Zi-Gao** [comment]
我这里也是同样的问题

**Comment by lee750717** [comment]
不是包的问题，自己配模组也一样

**Comment by lee750717** [comment]
> 此为hmcl安装，hmcl运行 [2024-04-08-1.log.gz](https://github.com/Hex-Dragon/PCL2/files/14901117/2024-04-08-1.log.gz) [2024-04-08-2.log.gz](https://github.com/Hex-Dragon/PCL2/files/14901118/2024-04-08-2.log.gz) 第一次启动由于模组版本问题导致报错 第二次启动成功

此为hmcl下载的Fabric0.15.9,pcl2和hmcl都能正常启动游戏并加载模组

**Comment by LTCatt** [comment]
已确认，正在调查中，参考 #3651

**Comment by LTCatt** [comment]
已确认是 #3651 导致，在更新 PCL 后重新安装 Fabric 即可

**Comment by 1wwwe2** [comment]
找了一下午原因，又摸了一下午鱼

**Comment by Simushz** [comment]
如果我没猜错的话，你是不是下载完游戏没打开过，直接就安装模组了，全都安装好后才进游戏？
我的建议是，下载完游戏和frabic-api之后打开一次然后再打mod

**Comment by wuliaodexiaoluo** [comment]
这个 issue 开发者已经贴出原因了，是错误的构建版本导致无法正常加载 Fabric，而不是没有启动导致的
请不要给出错误的建议，以及不要挖坟，谢谢
