### ISSUE TITLE
[Bug] 2.7.1 更改版本号后没有进行判断导致可以反复更新 PCL

### ISSUE THREAD

**Issue by wuliaodexiaoluo** [Hex-Dragon/PCL2#3647]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/Hex-Dragon/PCL2/assets/160083863/b9cb3114-6b77-45a4-a852-b6b18dcd5acf)
![image](https://github.com/Hex-Dragon/PCL2/assets/160083863/198095ae-4f8b-4325-8504-4ab25e48798e)
![image](https://github.com/Hex-Dragon/PCL2/assets/160083863/24ad92b5-0859-457d-9b17-fd814fa885c8)
![image](https://github.com/Hex-Dragon/PCL2/assets/160083863/1e9b45a3-5b4a-4372-9869-ab80f5542923)

龙猫你是不是忘记写判断符了。。。。
这个 Issue 不处理也罢，但下次请记得写判断符（
[没写更新日志](https://github.com/Hex-Dragon/PCL2/discussions/3645#discussioncomment-9040953)

### 重现步骤

1、打开设置
2、点击启动器选项卡
3、点击检查更新
4、完成更新后再次点击检查更新仍然可以更新

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14900834/Log3.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14900835/Log1.txt)

**Comment by JingHai-Lingyun** [comment]
我看着是好了？
Snapshot 2.7.0 更新之后正常的切换到了 2.7.1
你再试试看

**Comment by allMagicNB** [comment]
未能复现

**Comment by SolitudeSun** [comment]
你看看log1.txt，版本还是2.7.0，是因为更新下载了PCL2，但是文件没替换成功，所以能反复更新
