### ISSUE TITLE
[Bug] 2.7.1 没有更新日志

### ISSUE THREAD

**Issue by wuliaodexiaoluo** [Hex-Dragon/PCL2#3648]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

没有更新日志

### 重现步骤

打开 PCL

### 日志与附件

这个不需要日志吧。。。。。

**Comment by LTCatt** [comment]
见 https://github.com/Hex-Dragon/PCL2/discussions/3651
