### ISSUE TITLE
64 位系统上，在只有 32 位 Java 时自动安装 64 位 Java

### ISSUE THREAD

**Issue by zhangyankang521** [Hex-Dragon/PCL2#3649]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃基本不是 PCL 的原因，请 **不要** 提交反馈。你可以在论坛或社区找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用 HMCL 启动，HMCL 没有出现问题。** 如果 HMCL 也无法启动就不是 PCL 导致的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。
- [x] 由1.12.2 forge导致的bug

### 描述

我玩mod时提示内存不足，当时用的是1.12.2，forge版本14.23.5.2860，使用hmcl就没这情况，把全部mod卸载后也会出现这种情况，不是模组问题
流程：先启动1.12.2-Forge_14.23.5.2860，然后新建一个世界，接着进入后就会崩溃
我的电脑配置很高，不可能出现内存不够的情况，我试过清除所有后台，但都无济于事

### PCL 错误报告、日志与附件

[错误报告-2024-4-8_14.32.41.zip](https://github.com/Hex-Dragon/PCL2/files/14901803/-2024-4-8_14.32.41.zip)

### HMCL 启动脚本

[启动脚本.zip](https://github.com/Hex-Dragon/PCL2/files/14901867/default.zip)

**Comment by xinyihl** [comment]
Memory: 161027192 bytes (153 MB) / 483393536 bytes (461 MB) up to 1073741824 bytes (1024 MB)
看看你 pcl `设置 > 游戏 > 游戏内存` 设置自动分配的多少，你这就分配了1G

**Comment by wuliaodexiaoluo** [comment]
这好像是个 bug

**Comment by zhangyankang521** [comment]
> 内存：161027192字节（153 MB）/483393536字节（461 MB）最多1073741824字节（1024 MB） 看看你pcl`设置 > 游戏 > 游戏内存`设置自动分配的多少，你这就分配了1G

可是内存都拉满后也会这样

**Comment by zhi-xia** [comment]
笑死，我跟你报错一模一样，昨天晚上还玩着的，今天就进不去了。不过我换台电脑，把游戏版本文件夹直接拷过去能运行。但是游戏回档了。。。

**Comment by LTCatt** [comment]
等下，这个是因为用了 32 位的 Java 导致只能分配 1G 内存，和 #3651 无关……
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/93d6d1c6-1ef8-4729-9a7d-9dbe84c179db)

发一下你的 Java 列表？

**Comment by zhangyankang521** [comment]
我试试看选择64位java会不会有问题

**Comment by wuliaodexiaoluo** [comment]
然后在 32 位系统上弹出了一个巨大的提示框：

### 此应用无法在你的电脑上运行
> 若要找到合适你的电脑的版本，请咨询软件发布者

**Comment by LTCatt** [comment]
不打算支持 32 位了……

**Comment by wuliaodexiaoluo** [comment]
> 不打算支持 32 位了……

我很肯定很快就有一堆的 Issue 报说 32 位习题无法运行
所以我觉得需要给 Issue 模板加个检查项

**Comment by LTCatt** [comment]
建议你不要“很肯定”，现在 32 位用户基本已经没有了，MC 都不支持 32 位了……

**Comment by Ad-closeNN** [comment]
笑死，没钱买硬件
![image](https://github.com/Hex-Dragon/PCL2/assets/103355026/6afc9cac-0fd1-477e-a600-686b6f818fea)

**Comment by LTCatt** [comment]
因为最新版 MC 已经不支持 32 位了，所以启动器依然保持 32 位支持没有什么必要了。不会删除现有的 32 位支持，只是不会再额外为 32 位进行修复和调整。
这个问题怎么说都没到需要加 issue 检查项的地步。

**Comment by Ad-closeNN** [comment]
> 因为最新版 MC 已经不支持 32 位了，所以启动器依然保持 32 位支持没有什么必要了。不会删除现有的 32 位支持，只是不会再额外为 32 位进行修复和调整。 这个问题怎么说都没到需要加 issue 检查项的地步。

也就是启动器后续发布的版本依然可以在32位系统上运行，但是关于仅使用32位系统而触发的bug却不修复？

**Comment by LTCatt** [comment]
是这么回事（

**Comment by wuliaodexiaoluo** [comment]
> 笑死，没钱买硬（悲） 

这配置足够装 64 位了。。。
你不装那 1GB 内存岂不是浪费掉了。。。
