### ISSUE TITLE
关于 PCL2 在打开调试模式时性能损耗过大的问题

### ISSUE THREAD

**Issue by Louis-ZYH** [Hex-Dragon/PCL2#365]
### 检查项

- [x] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

机型：Dell Inspiron 15 3543
CPU：Intel(R) Celeron 3205U 1.5Ghz 双核双线程
内存：4GB DDR3L 单通道笔记本内存 + 4 ~ 16GB 虚拟内存
硬盘：希捷 500GB 5400转机械硬盘
系统：Windows 10 21H2 x64 某精简优化版，无任何杀毒软件

问题：在开启调试模式时，目测帧数相较于未开启调试模式时有超过 30% 的下降，按钮点击延时目测已超过1秒（未开启添加延 迟，动画速度 1x），希望予以优化。

### 原因

这项优化可以让我更流畅地使用 PCL2 ，同时使用调试模式的实时日志快速确认各类问题。
如果没有这项优化，我每次都必须手动调慢动画速度和结束后台程序，让操作变得很麻烦。

**Comment by Louis-ZYH** [comment]
Snapshot 2.4.1（267.0）和正式版 Release 2.4.2（268.50）均有此问题，但快照版问题似乎更为严重。

**Comment by LTCatt** [comment]
需要补充日志

**Comment by Louis-ZYH** [comment]
[未开启调试模式.txt](https://github.com/Hex-Dragon/PCL2/files/9993914/default.txt)
[已开启调试模式.txt](https://github.com/Hex-Dragon/PCL2/files/9993915/default.txt)

**Comment by LTCatt** [comment]
日志里没有与这个 Bug 相关的有效线索，并且我自己也无法复现这个情况。
考虑到描述中提到 `按钮点击延时目测已超过1秒（动画速度 1x）` ，如果触发了这个 Bug，应该是相当明显的。
挂需要社区帮助是想问问 **有没有其他人也有这个情况？**
没有线索且无法本地复现的话我不好修……

**Comment by Xiaoganghei** [comment]
在我的N4500处理器电脑上也同样出现过这种问题

**Comment by LTCatt** [comment]
……我觉得可能需要录屏什么的来找找线索。
Log 里完全体现不出来……

**Comment by Louis-ZYH** [comment]
说实话，我不希望通过录屏体现问题，因为录屏软件通常会占用不少系统资源（对我而言），手头最近也没什么手机之类的……
考虑到我这台电脑的性能已经到了极其低下的程度，有概率是个别情况，主流电脑基本无法复现……
尝试先从我自己这里找找原因吧，实在不行尝试精简代码……
Sorry，但我尽力了。

**Comment by LTCatt** [comment]
我觉得应该是个别问题……没法复现的话我也没法修复……悲。
