### ISSUE TITLE
咋回事啊模组都不加载了

### ISSUE THREAD

**Issue by mg12308002** [Hex-Dragon/PCL2#3652]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃基本不是 PCL 的原因，请 **不要** 提交反馈。你可以在论坛或社区找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用 HMCL 启动，HMCL 没有出现问题。** 如果 HMCL 也无法启动就不是 PCL 导致的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我的所有整合包启动后都无mod加载，都是原版

### PCL 错误报告、日志与附件

暂时没有

### HMCL 启动脚本

暂时没有

**Comment by wuliaodexiaoluo** [comment]
该版本为开发中版本，包含了大量没有测试的功能
包括 #3511 #2801 等破坏性改动

**Comment by mg12308002** [comment]
就是我今天发现pcl上所有整合包安装后都无法加载mod，只加载出原版，我用hmcl试了一下就可以，求快速修复

**Comment by LTCatt** [comment]
使用错误版本（版本号错误显示为 2.7.0）的正式版用户现已可以正常更新。该错误版本存在严重问题，请务必进行更新！
如果使用该错误版本安装了 Fabric，请在更新后重新安装 Fabric。该错误版本安装的 Fabric 已确认无法加载 Mod（https://github.com/Hex-Dragon/PCL2/issues/3646）。
