### ISSUE TITLE
模组无法加载，急！求修复！

### ISSUE THREAD

**Issue by mg12308002** [Hex-Dragon/PCL2#3653]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

模组无法加载，急！求修复！

### 重现步骤

1.安装任意整合包
2.启动游戏
3.发现无mod加载

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14903990/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14903991/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14903992/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14903993/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14903994/Log5.txt)

**Comment by JingHai-Lingyun** [comment]
Fabric 版 Mod 加载问题参见 #3651，https://github.com/Hex-Dragon/PCL2/issues/3652#issuecomment-2042349033

>使用错误版本（版本号错误显示为 2.7.0）的正式版用户现已可以正常更新。该错误版本存在严重问题，请务必进行更新！
如果使用该错误版本安装了 Fabric，请在更新后重新安装 Fabric。该错误版本安装的 Fabric 已确认无法加载 Mod（#3646）。

**Comment by mg12308002** [comment]
> Fabric 版 Mod 加载问题参见 #3651，[#3652 （comment）](https://github.com/Hex-Dragon/PCL2/issues/3652#issuecomment-2042349033)
> 
> > 使用错误版本（版本号错误显示为 2.7.0）的正式版用户现已可以正常更新。该错误版本存在严重问题，请务必进行更新！
> > 如果使用该错误版本安装了 Fabric，请在更新后重新安装 Fabric。该错误版本安装的 Fabric 已确认无法加载 Mod（#3646）。

我用的是2.7.1，无法加载mod‘

**Comment by JingHai-Lingyun** [comment]
啊？确认你是否**重装**了受 #3651 影响的 Fabric 版
确认重装了的话 Minecraft 的日志发来看看？

**Comment by mg12308002** [comment]
谢谢，重装整合包后可以了
