### ISSUE TITLE
[优化] Issue 模板增加允许 Author 填写使用版本的文本框

### ISSUE THREAD

**Issue by wuliaodexiaoluo** [Hex-Dragon/PCL2#3654]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

增加可以填写版本号和版本类型的文本框

### 原因

因为没有这种要求 Author 一般不会贴出使用版本
而 Collaborator 和大部分 Author 都是赞助过龙猫的人，尝试复现 Bug 会优先并且只尝试 Snapshot 版本
而有些 Bug 可能只存在于特定版本类型（比如 Snapshot 2.6.2 的 Mod 搜索 Bug，Release 没有这个问题，和错误的 Release 版本导致 #3511 给定参数过早应用在 Release 版本引发的衍生 Issue，以及 #3647 #3648，这部分 Issue 只能在 Release 版本复现）
处理 #3647 的两位 Collaborators 应该是都只尝试了 Snapshot 版本，因为只有 Release 才有这个问题，两个 Collaborators 一致认为这个问题可能不存在
这也方便过滤（日志因为版本号没有明显标识很容易会被掠过，往往是看了两三遍才发现版本号不对劲）

**Comment by allMagicNB** [comment]
日志会有的，没有必要

**Comment by wuliaodexiaoluo** [comment]
>这也方便过滤（日志因为版本号没有明显标识很容易会被掠过，往往是看了两三遍才发现版本号不对劲）

看清解释了么。。。。
另外我在 #3647 也给了日志，不过你似乎卡也没看就用 Snapshot 版本尝试复现了的说

**Comment by allMagicNB** [comment]
> >这也方便过滤（日志因为版本号没有明显标识很容易会被掠过，往往是看了两三遍才发现版本号不对劲）
> 
> 看清解释了么。。。。
> 另外我在 #3647 也给了日志，不过你似乎看也没看就用 Snapshot 版本尝试复现了的说

不是，日志开头都看不见，那
# 谁会在意那短短的一行版本啊？

**Comment by wuliaodexiaoluo** [comment]
标题显眼点，看不到主要是滑太快加上不是特别显眼

**Comment by allMagicNB** [comment]
算了，反正给龙猫看看，也没重复
不过我感觉至少有 99.99999％ 的概率会被关

**Comment by LTCatt** [comment]
暂不考虑，一方面让提交 issue 变得更麻烦了，这起不到筛选的作用反而会让一些想提交的人懒得整，另一方面有人不传 log 的也不会去填版本号的……

**Comment by allMagicNB** [comment]
> 另一方面有人不传 log 的也不会去填版本号的……

这种人，唉……自以为是地认为这些东西没用，加了 `等待反馈者` Label 让补充信息后，又能有几个会补充信息……
