### ISSUE TITLE
管理员运行时无法识别文件拖动

### ISSUE THREAD

**Issue by KangxiDictionary** [Hex-Dragon/PCL2#3656]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

以管理员运行PCL II让后在任意本来支持文件拖动的位置拖动就会发现鼠标指针变为"禁止"

### 重现步骤

1.以管理员启动
2.任意支持文件拖动的位置将文件拖到PCL II上
3.bug出现

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14917314/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14917315/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14917316/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14917317/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14917318/Log5.txt)

**Comment by JingHai-Lingyun** [comment]
请见 #2531
