### ISSUE TITLE
我启动MCE时候崩溃

### ISSUE THREAD

**Issue by RainbowTaro2022** [Hex-Dragon/PCL2#3658]
### 检查项

- [ ] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃基本不是 PCL 的原因，请 **不要** 提交反馈。你可以在论坛或社区找人求助，但这里并不是你求助的地方。
- [ ] **我已尝试使用 HMCL 启动，HMCL 没有出现问题。** 如果 HMCL 也无法启动就不是 PCL 导致的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我升级了一些mod，然而当我启动的时候崩溃了

### PCL 错误报告、日志与附件

[crash-2024-04-10_08.23.51-client.txt](https://github.com/Hex-Dragon/PCL2/files/14925534/crash-2024-04-10_08.23.51-client.txt)
[crash-2024-04-10_08.25.30-client.txt](https://github.com/Hex-Dragon/PCL2/files/14925535/crash-2024-04-10_08.25.30-client.txt)
[crash-2024-04-10_08.21.08-client.txt](https://github.com/Hex-Dragon/PCL2/files/14925536/crash-2024-04-10_08.21.08-client.txt)

**Comment by wuliaodexiaoluo** [comment]
请使用 HMCL 启动
另外升级 Mod 导致的崩溃是 Mod 问题
另外提供下 PCL 日志
另外你应该检查下 Java 版本，你可能是使用了错误的版本运行（例如 JDK 17 运行 1.12.2）

**Comment by wuliaodexiaoluo** [comment]
有没有人加个 Label:等待反馈者

**Comment by LTCatt** [comment]
安装 Mod 后的游戏崩溃基本不是 PCL 的原因，请 **不要** 提交反馈。你可以在论坛或社区找人求助，但这里并不是你求助的地方。

**Comment by Deep-Dark-Forest** [comment]
另，根据#1930，请不要这样起标题……
![Screenshot_20240410_185319.jpg](https://github.com/Hex-Dragon/PCL2/assets/131975043/60b56d55-4852-4184-9752-861376f09790)
