### ISSUE TITLE
建议支持CurseForge和Modrinth的材质包.数据包.光影下载源

### ISSUE THREAD

**Issue by Liwenhan225225** [Hex-Dragon/PCL2#3663]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [x] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

这样可以大幅度减低找材质包.数据包.光影的困难 找材质包.数据包.光影就不麻烦了

### 原因

我需要这个功能来降低下载数据包.材质包.光影的困难。很多人都有这个需求，但如果没有这个功能，就不能更方便下载材质包.数据包.光影了

**Comment by Liwenhan225225** [comment]
> ### 检查项
> * [x]  我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
> * [x]  我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
> * [x]  我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……
> 
> ### 描述
> 这样可以大幅度减低找材质包和数据包的困难 找材质包和数据包就不麻烦了
> 
> ### 原因
> 我需要这个功能来降低下载数据包和材质包的困难。很多人都有这个需求，但如果没有这个功能，就不能更方便下载材质包和数据包了

**Comment by JingHai-Lingyun** [comment]
材质包 #44 投票到 #1095
光影包 #396 投票到 #2768
数据包 #2991 投票到 #2994
