### ISSUE TITLE
启动器隐藏主题滑稽彩动画显示异常

### ISSUE THREAD

**Issue by Xiakeya** [Hex-Dragon/PCL2#3664]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如题，动画显示卡顿，帧数很低，调节调试选项中的动画速度仍未改善，其他动画如点击，切换，提示显示正常。
显卡是Geforce 4070Ti

### 重现步骤

打开启动器

### 日志与附件

https://github.com/Hex-Dragon/PCL2/assets/166595133/42c9a1fd-dff1-4a9d-8937-9fc354bf8b7b

**Comment by Xiakeya** [comment]
尤其是橙色过来的时候很明显

**Comment by JingHai-Lingyun** [comment]
使用滑稽彩导致卡顿 & 掉帧 & 占用过大：无法解决或优化此类问题。
请见 #1575 #1590 #2336
