### ISSUE TITLE
特定情况下，“更多”页面的侧边栏会窄一点

### ISSUE THREAD

**Issue by moyujunaimoyu** [Hex-Dragon/PCL2#3665]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

启动PCL后先点“下载”再点“更多”，“更多”的侧边栏就会显示的窄一点

录了一个复现视频
https://github.com/Hex-Dragon/PCL2/assets/125355634/2ed4ad8d-7b28-42e9-927d-1ba58f9d2e66

### 重现步骤

1.启动PCL
2.切换到“设置”
3.切换到“更多”

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14929946/Log1.txt)

**Comment by Ad-closeNN** [comment]
#2982 #3594

**Comment by JingHai-Lingyun** [comment]
是的，请见 #2982
