### ISSUE TITLE
建议"下载模组时自动下载某mod的前置模组"

### ISSUE THREAD

**Issue by Chormore-EDGE** [Hex-Dragon/PCL2#3669]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

第一次启动的时候自动开启/关闭

### 原因

每次下载一堆套娃前置太麻烦了

**Comment by allMagicNB** [comment]
#179
