### ISSUE TITLE
模组下载界面下面还是有“正在获取mod列表”

### ISSUE THREAD

**Issue by pumpkinmc** [Hex-Dragon/PCL2#3671]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我语文不好，请看图片
![QQ截图20240412100552](https://github.com/Hex-Dragon/PCL2/assets/148406068/8c785473-0ced-4822-9de0-6df77bf779e7)

### 重现步骤

我不到啊，我在模组下载界面搜“G键合成表”就这样了

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14953146/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14953147/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14953148/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14953150/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14953151/Log5.txt)

**Comment by Ad-closeNN** [comment]
未复现成功

BTW:
5个Log都搜过`G键合成表`了，怎么就是搜不到呢...
![image](https://github.com/Hex-Dragon/PCL2/assets/103355026/f3e72294-c5d2-403a-9fe9-2b150ff5a297)

**Comment by allMagicNB** [comment]
打开 `调试模式` 再尝试复现，然后上传新的 Log

**Comment by wuliaodexiaoluo** [comment]
这都几个世纪前都 Bug 怎么还能复现成功啊喂!

**Comment by ccyy512** [comment]
> **未复现成功**
> 
> BTW: 增值税： 5个Log都搜过`G键合成表`了，怎么就是搜不到呢... ![image](https://private-user-images.githubusercontent.com/103355026/321838272-f3e72294-c5d2-403a-9fe9-2b150ff5a297.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMTQzNjksIm5iZiI6MTcxMzAxNDA2OSwicGF0aCI6Ii8xMDMzNTUwMjYvMzIxODM4MjcyLWYzZTcyMjk0LWM1ZDItNDAzYS05ZmU5LTJiMTUwZmY1YTI5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxM1QxMzE0MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDFhNzU3MmE5Mzc1NjRlOWU4MzBiZDc5YWZkNjA5ZGEyN2MyN2U3OGZhNTE4ZTVjYTQ0ZWQzNDg1MWQwNDk1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aOO6MOmQfwe5rQJwhkMgOrj9k70jOEhfRnS8427PhPE)

抱歉我貌似就搜了一个“G”。。。。

**Comment by Ad-closeNN** [comment]
所以说复现成功了吗各位

**Comment by wuliaodexiaoluo** [comment]
这个问题我实在是没办法在调试模式下复现。。。。

**Comment by Greenturtle2024** [comment]
无法复现的bug最难解决。

**Comment by mc-124** [comment]
群里又有人卡出来了
![image](https://github.com/Hex-Dragon/PCL2/assets/138775126/8880012c-fd09-48de-848b-8682eee91cbe)

**Comment by JingHai-Lingyun** [comment]
需要日志

**Comment by allMagicNB** [comment]
> 需要日志

还要开调试模式

**Comment by ccyy512** [comment]
> 群里又有人卡出来了 ![image](https://private-user-images.githubusercontent.com/138775126/324334506-8880012c-fd09-48de-848b-8682eee91cbe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzODAxNTEsIm5iZiI6MTcxNDM3OTg1MSwicGF0aCI6Ii8xMzg3NzUxMjYvMzI0MzM0NTA2LTg4ODAwMTJjLWZkMDktNDhkZS04NDhiLTg2ODJlZWU5MWNiZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOVQwODM3MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZjQzNWU5MDdhNzY1M2IxNTc3Yzg1NDQ4ZDdlOGFiZWE5MTZmYzYzZmFjNzhlZDM5ZjA3ZTliMWUwZTQ3NzhiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nUGnmiKRZsPLFHjwE5D81Q4q2apQMvDQyq83OpFSEg8)

好奇怪的bug....

**Comment by LTCatt** [comment]
好像是 #1624
