### ISSUE TITLE
检索mod时输入版本第一个点会消失

### ISSUE THREAD

**Issue by maybethisisaname** [Hex-Dragon/PCL2#3672]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我在检索mod时在mod版本处填1.20.1时 会显示成1 20.1 第一个"."消失 要重新改一遍才能够打出1.20.1

### 重现步骤

1、点击下载->mod->版本填版本号
2.触发bug

### 日志与附件

[Uploading Logs.zip…]()

**Comment by allMagicNB** [comment]
你日志都没传上来……
请等待 `Uploading XXX` 字样消失后再进行下一步操作。

**Comment by wuliaodexiaoluo** [comment]
完全没问题啊，我这边都是正常的

**Comment by Silverteal** [comment]
未能复现，请尝试切换输入法

**Comment by Greenturtle2024** [comment]
没bug啊！
