### ISSUE TITLE
增加深色主题

### ISSUE THREAD

**Issue by ZhangJinyuJerry** [Hex-Dragon/PCL2#3675]
### 检查项

- [ ] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [ ] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [x] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

在设置-启动器中新增主题选项，建议为浅色、深色和跟随系统
（其实已经有过了，但是并没有人投票）

### 原因

因为电脑是深色主题，所以白的不太好看。
（其实已经有过了，但是并没有人投票）

**Comment by allMagicNB** [comment]
#131

**Comment by ZhangJinyuJerry** [comment]
> #131

嘤嘤嘤……好吧
