### ISSUE TITLE
自定义下载时报错

### ISSUE THREAD

**Issue by ZhangJinyuJerry** [Hex-Dragon/PCL2#3676]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述
![屏幕截图 2024-04-13 100109](https://github.com/Hex-Dragon/PCL2/assets/158539001/453c47a8-c24e-4344-98a2-65a1979fcaab)
下载了十几秒后报错

### 重现步骤

1、点击菜单栏更多-百宝箱
2、点开百宝箱
3、找到自定义下载，填写下载链接[10GB文件](http://vipspeedtest8.wuhan.net.cn:8080/download?size=10737418240)
4、点击下载
5、等待十几秒后报错

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14964969/Log1.txt)

建议：
在报错后运用单线程下载重新下载

idm下载此文件截图：
![屏幕截图 2024-04-13 100407](https://github.com/Hex-Dragon/PCL2/assets/158539001/8018e02c-83b9-4248-b96e-534107234f6c)

**Comment by ZhangJinyuJerry** [comment]
图传错了
![屏幕截图 2024-04-13 100109](https://github.com/Hex-Dragon/PCL2/assets/158539001/668ae0d7-66a8-495d-98c7-000d965227f8)

**Comment by Deep-Dark-Forest** [comment]
请尝试把链接复制粘贴到浏览器，尝试能否下载
大概率和PCL无关

**Comment by ZhangJinyuJerry** [comment]
> 请尝试把链接复制粘贴到浏览器，尝试能否下载 大概率和PCL无关

可以下载啊

**Comment by ZhangJinyuJerry** [comment]
http://vipspeedtest8.wuhan.net.cn:8080/download?size=10737418240
这是文中提到的下载链接

**Comment by ZhangJinyuJerry** [comment]
> http://vipspeedtest8.wuhan.net.cn:8080/download?size=10737418240 这是文中提到的下载链接

下载链接也是从网上找的

**Comment by ZhangJinyuJerry** [comment]
让我试一试从浏览器上下载

**Comment by Silverteal** [comment]
源服务器不支持断点续传。
