### ISSUE TITLE
同一 Mod 在不同 MC 版本下使用了相同的更新检查缓存

### ISSUE THREAD

**Issue by HMwancheng** [Hex-Dragon/PCL2#3680]
### 检查项

- [x] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

同下

### 重现步骤

1.安装MC1.20.1,IRIS对应版本任意旧版
2.安装MC1.20.4
3.将IRIS 从1.20.1MOD文件夹移动到1.20.4文件夹（开启版本隔离）
4.自动更新MOD

弹出以下报错
有不兼容的模组！ (Incompatible mods found!)
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
确定了一种可能的解决方法，这样做可能会解决你的问题：
	 - 移除 模组 'Iris' (iris) 1.6.17 (D:\xxx\Minecraft\.minecraft\versions\1.20.4-Fabric 0.15.10\mods\iris-mc1.20.1-1.6.17.jar)。

此处可以看出IRIS mod自动更新出错，1.6.17确实为最新版本，但MC版本号对应错误

### 日志与附件

[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14966966/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14966967/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14966968/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14966969/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14966970/Log3.txt)

**Comment by allMagicNB** [comment]
自动更新不应当更新 Mod 的适用版本

**Comment by allMagicNB** [comment]
算了还是让龙猫看看……

**Comment by HMwancheng** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/91036325/b7c3696d-dde1-4c2d-b2f9-bd61e6f5d752)
然而很多mod仍然更新了适用版本

![image](https://github.com/Hex-Dragon/PCL2/assets/91036325/b17f7a9f-36d2-4748-889b-87f50fb2106e)
此MOD 自动更新了MC适用版本

![image](https://github.com/Hex-Dragon/PCL2/assets/91036325/c9aa31da-c830-49b6-bcda-9cbf6b4ca387)
这一个mod又没有更新到适用的版本

**Comment by HMwancheng** [comment]
应该；逻辑上不会出现这种情况吧🫥

**Comment by LTCatt** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/71e2f1a6-5248-4e65-9ddf-5371b8ac975f)

疑似是因为作者先传了 1.20.4，再传了个 1.20.1，导致 1.20.1 成了最新版本……
具体原因还没看，先记一下 =。=

**Comment by HMwancheng** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/91036325/613bc958-07be-446b-ab90-fbe341440a99)
这样的话是不是也可以同时解释为什么这一个MOD也没有更新到最新版的原因🤣

**Comment by wuliaodexiaoluo** [comment]
这个。。。。我先去问问 Modrinth 怎么说

**Comment by HomoobyDX** [comment]
我觉得可以保持HMCL那种更新后禁用旧版本模组（省去用户还要去回收站找旧文件）（提一嘴）

**Comment by wuliaodexiaoluo** [comment]
钠这个是作者乱标版本的问题

**Comment by allMagicNB** [comment]
> 钠这个是作者乱标版本的问题

喂你要不要看看他在说什么

**Comment by wuliaodexiaoluo** [comment]
> 钠扩展

坏了我瞎了（EdgeHTML 渲染真的有问题，看不太清楚

**Comment by LTCatt** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/5b82c23c-415a-42fe-a513-cd42fe69f803)
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/50ec1cf4-0693-40a2-acfa-eadcafaf6641)

因为这俩 mod 作者更新，这俩 mod 现在都复现不出来问题了……

![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/87c3f575-29d7-4bd4-af25-4ab26724a942)

如果谁现在可以重现这个 bug 才能接着看怎么修 orz

**Comment by HMwancheng** [comment]
仿佛在测试复现时发现一个新问题

想知道自动更新是否会对应MC版本号
这是我的测试
1.在1.20.1将所有MOD更新到最新
![image](https://github.com/Hex-Dragon/PCL2/assets/91036325/3c9a110c-5173-4f3a-b637-6c0fc5ef86a4)

2.下载1.20.4
![image](https://github.com/Hex-Dragon/PCL2/assets/91036325/e2289112-ff30-45f8-a189-a6d74d8a1d6a)

3.将 1.20.1 MOD文 件夹内所有 MOD 复制一份到1.20.4
![image](https://github.com/Hex-Dragon/PCL2/assets/91036325/e8c5177f-c6ce-4676-9f57-688b954e7d72)

4.切换版本到1.20.4
问题：所有MOD均无法自动更新
![image](https://github.com/Hex-Dragon/PCL2/assets/91036325/785147c7-e546-43a7-9d0b-37b694e2f471)

确认MOD有对应版本
![image](https://github.com/Hex-Dragon/PCL2/assets/91036325/317880c7-7c17-4640-99d4-ea9a47066faf)

**Comment by LBZiXL** [comment]
好像这个Bug又出现了
我这个明明是1.20.4的MC，PCL会自动把Mod更新为1.20.6的最新版，导致MC崩溃
![image](https://github.com/Hex-Dragon/PCL2/assets/115980764/e214a8b0-63c1-4d5a-9760-427604cd74cb)
可是modrinth上有1.20.4的最新版（4.0.9b），PCL却更新为1.20.6的（4.0.9b）
![image](https://github.com/Hex-Dragon/PCL2/assets/115980764/676c19c8-c63d-4253-a229-b41b2cdbcda6)

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15470090/Log1.txt)

**Comment by LTCatt** [comment]
似乎是 IMBlocker 作者错误把它标记为了支持 1.20.4，现在筛选 1.20.4 只有一个版本，但楼上的截图有两个版本
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/36de5dd9-9a39-4e2e-8bed-a7b48d2f6f43)
