### ISSUE TITLE
更新后变卡

### ISSUE THREAD

**Issue by fuyuenm** [Hex-Dragon/PCL2#3681]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

上次更新后，除了每次进入整合包设置会变成默认（已修复的），玩大型整合包以前有80到90帧，现在只有60帧，玩小型整合包以前有200帧，现在也只有60帧，注意，我没有开锁帧，现在开发者大大修复这个问题

### 重现步骤

每次进入都这样
[无.txt](https://github.com/Hex-Dragon/PCL2/files/14967194/default.txt)

### 日志与附件

[无.txt](https://github.com/Hex-Dragon/PCL2/files/14967197/default.txt)

**Comment by allMagicNB** [comment]
关于卡顿，PCL 基本无法进行优化

**Comment by mc-124** [comment]
PCL2好像没有能影响Client性能的东西吧？

**Comment by LTCatt** [comment]
请上传日志

**Comment by Silverteal** [comment]
> 上次更新后，除了每次进入整合包设置会变成默认（已修复的），玩大型整合包以前有80到90帧，现在只有60帧，玩小型整合包以前有200帧，现在也只有60帧，注意，我没有开锁帧，现在开发者大大修复这个问题

中译中：
上次更新后，除了“每次进入整合包设置会变成默认”的已修复问题外，还有“整合包帧率大幅下降到60帧左右”的问题，已确认帧率没有锁定（存疑），请开发者修复此问题

**Comment by fuyuenm** [comment]
[quarry-debug-2024-04-12-3.log.gz](https://github.com/Hex-Dragon/PCL2/files/14969446/quarry-debug-2024-04-12-3.log.gz)

**Comment by fuyuenm** [comment]
[quarry-debug-2024-04-13-1.log.gz](https://github.com/Hex-Dragon/PCL2/files/14969453/quarry-debug-2024-04-13-1.log.gz)
[quarry-debug-2024-04-12-3.log.gz](https://github.com/Hex-Dragon/PCL2/files/14969456/quarry-debug-2024-04-12-3.log.gz)
这是大型整合包的

**Comment by fuyuenm** [comment]
[2024-04-13-1.log.gz](https://github.com/Hex-Dragon/PCL2/files/14969458/2024-04-13-1.log.gz)
这是小型的

**Comment by fuyuenm** [comment]
感谢开发者大大的关注，谢谢

**Comment by allMagicNB** [comment]
也发下 PCL2 的日志

**Comment by fuyuenm** [comment]
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14969488/Log5.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14969489/Log4.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14969490/Log3.txt)

**Comment by fuyuenm** [comment]
很抱歉开发者大大，因为我的原因给你添加了麻烦，目前问题已解决，我不小心开了垂直同步，抱歉，希望没有给你增添太多麻烦。
