### ISSUE TITLE
在界面中显示所有的Java版本

### ISSUE THREAD

**Issue by ZhangJinyuJerry** [Hex-Dragon/PCL2#3682]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

在界面中显示所有的Java版本，并可以对Java进行卸载。

### 原因

磁盘没空间力

**Comment by allMagicNB** [comment]
首先提一嘴，
# PCL 既不是你的 Java 管理器，也不是你的磁盘清理大师

**Comment by zkitefly** [comment]
感觉不太行，不过先让龙猫看看

**Comment by Pigeon0v0** [comment]
目前就是会显示所有的，卸载的话看看龙猫怎么想了

**Comment by kong-que-dnf123** [comment]
~JAVA默认装C盘结果PLC2没权限删除.jpg~

**Comment by LTCatt** [comment]
#874

**Comment by allMagicNB** [comment]
> #874

这里还包括了一个卸载，不过没啥用就是了（
