### ISSUE TITLE
NeoForge下载

### ISSUE THREAD

**Issue by SnifferGX** [Hex-Dragon/PCL2#3683]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

NeoForge已发布多时，请尽快提供PCL2内自动安装方式。

### 原因

（示例）
我需要这个功能来xxxx。很多人都有xxxx的需求，但如果没有这个功能，就不能xxxx了。
我需要这个功能来下载NeoForge。很多人都有下载Neoforge的需求，但如果没有这个功能，就不可以更快捷地使用NeoForge了。

**Comment by allMagicNB** [comment]
![Screenshot_20240414_120139.jpg 眼瞎可以去治治](https://github.com/Hex-Dragon/PCL2/assets/116283787/af6e2aa8-fce0-4c2a-9b33-b832f09b782e)

**Comment by allMagicNB** [comment]
眼瞎可以去治治
