### ISSUE TITLE
远古版本下载，资源文件夹创建失败

### ISSUE THREAD

**Issue by misividkoukou** [Hex-Dragon/PCL2#3684]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

与另一个issue不同，此问题在
u盘无管理权限
U盘有管理权限
本地磁盘无管理权限
本地磁盘有管理权限
全部出现，且1.20版本pre5预发布下载时未出现此类问题
![DPL%)T8BBBUB3C HF9N2AII](https://github.com/Hex-Dragon/PCL2/assets/121597192/3483ca8f-ccd3-463a-8186-49b565a40379)
且补全文件时出现错误，但启动器仍然表示补全成功
![}SI`R$XHL`1B48Q9PS{)GB](https://github.com/Hex-Dragon/PCL2/assets/121597192/cfda16f9-8934-4a6f-9869-b9a9b6a87388)
见此图左下角
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14969428/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14969429/Log2.txt)

### 重现步骤

选择自动安装或手动下载客户端皆出现此类问题

### 日志与附件

日志只有1,2在上面

**Comment by allMagicNB** [comment]
#3368

**Comment by misividkoukou** [comment]
最终发现这个问题与#3368无关，与硬盘有关

**Comment by allMagicNB** [comment]
确认下是否可以解决，无法解决再继续 Comment 说句

**Comment by misividkoukou** [comment]
这个issue我不知道发什么好了，明显的此问题在磁盘文件系统为NTFS时不会出现，但在FAT32与exFAT会出现（但是为什么正式版就没问题呢？)

**Comment by misividkoukou** [comment]
如果其他版本下载正常而远古版异常应该算bug吧？

**Comment by misividkoukou** [comment]
还有这一个issue应该包含两个bug，第一个是资源文件夹创建失败，第二个是出现错误时启动器依然提示补全成功？

**Comment by zkitefly** [comment]
低版本需要将 resources 文件夹（也就是资源文件夹）拷贝一份至游戏文件夹中，PCL 使用的方案是软链接的方式链接，可能是 FAT32 与 exFAT 不支持软链接？

**Comment by zkitefly** [comment]
可能不属于 PCL 的问题，自己磁盘系统不同导致无法创建软链接？

**Comment by allMagicNB** [comment]
请确认#3368 最后解决的方式是否可以解决

**Comment by allMagicNB** [comment]
> 可能不属于 PCL 的问题，自己磁盘系统不同导致无法创建软链接？

但是 PCL 应该要为这种情况做出不同措施

**Comment by zkitefly** [comment]
要不还是放弃软链接的方式吧，直接拷贝一份又不是不行

**Comment by allMagicNB** [comment]
> 要不还是放弃软链接的方式吧，直接拷贝一份又不是不行

浪费空间（

**Comment by jeke573** [comment]
1

**Comment by JingHai-Lingyun** [comment]
请不要水帖，谢谢。

**Comment by LTCatt** [comment]
现在不再创建符号链接了……

**Comment by misividkoukou** [comment]
@LTCatt ，求个活跃橙的解锁码 
~~虽然有点久远~~
识别码：AB25-FBF8-748F-4D6E

**Comment by LTCatt** [comment]
你的解锁码：ErudO2c4A9w4g1nCVIj47WrNUQFw9l+E
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
