### ISSUE TITLE
[Bug] Snapshot 2.7.1 没有更新日志

### ISSUE THREAD

**Issue by wuliaodexiaoluo** [Hex-Dragon/PCL2#3688]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

对没错，就是没有更新日志
（龙猫你这么懒吗？）
检索式 ：
is:issue is:open 日志 快照
is:issue is:closed 日志 快照

### 重现步骤

这个更新一下就有了

### 日志与附件

![image](https://github.com/Hex-Dragon/PCL2/assets/160083863/8d96ad47-aa59-4062-9547-73ed84c01b39)

**Comment by allMagicNB** [comment]
> 该版本尚未完成开发，所以没有修改版本号，导致了 #3647、#3648 。
LTCatt in #3651

**Comment by hejiehao** [comment]
https://www.bilibili.com/opus/917725363188006921?spm_id_from=333.999.0.0

**Comment by wuliaodexiaoluo** [comment]
你说有没有可能，#3647、#3648 是 Release 版本存在的问题
有没有可能我是从 Snapshot 2.7.0 更新到 Snapshot 2.7.1 呢
恕我抱歉我实在是没理解打个 Label:重复 的意思，这并没有与任何 Issue 重复

**Comment by wuliaodexiaoluo** [comment]
> https://www.bilibili.com/opus/917725363188006921?spm_id_from=333.999.0.0

有没有可能我指的 PCL 没有显示日志

**Comment by allMagicNB** [comment]
> 你说有没有可能，#3647、#3648 是 Release 版本存在的问题
> 有没有可能我是从 Snapshot 2.7.0 更新到 Snapshot 2.7.1 呢
> 恕我抱歉我实在是没办法理解打个 Label:重复 的意思，这并没有与任何 Issue 重复

但你并未在此中强调只有 Release 版有此错误

**Comment by wuliaodexiaoluo** [comment]
## 2.7.1 正式版更新错误的情况说明

#3651 标题足够清晰了，如果你坚持认为 Issue 重复，我只能让龙猫来处理了

**Comment by JingHai-Lingyun** [comment]
按理来说发 Release 的时候 Snapshot 的日志和 Release 的日志是一起写的......，或许 #3648 #3651 适用于本 Issue 的重复判定？
@LTCatt 打扰一下过来看看？

**Comment by LTCatt** [comment]
已确认，应当下一个版本会自然修复
