### ISSUE TITLE
1.20.4版本设置自定义游戏窗口标题失效

### ISSUE THREAD

**Issue by GhostBone** [Hex-Dragon/PCL2#3689]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

#### 如图，正版登录游戏后并没有设置的效果，具体的游戏版本设置中是空的，即为全局设置。经测试1.19.4不会出现此现象，1.20.4版本会出现此问题。
------------------------------------------
![Screenshot 2024-04-14 142020](https://github.com/Hex-Dragon/PCL2/assets/40034700/18d2af0d-2a65-48cf-9e99-de18d49364f4)

![Screenshot 2024-04-14 223844](https://github.com/Hex-Dragon/PCL2/assets/40034700/8c050920-41ca-4815-885d-4dd60af4d5fc)
------------------------------------------
- PCL版本:  snapshot 2.7.1 (320.0)
- MC版本:  1.20.4
- fabric版本:  0.15.9

### 重现步骤

1、设置全局‘游戏窗口标题‘
2、正常启动游戏

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14971163/Log2.txt)

**Comment by allMagicNB** [comment]
```
[22:48:36.610] [Launch] [21284] 要求窗口标题：MC  1.20.4  Ghost_bone  正版
```
日志里是正常的……

**Comment by GhostBone** [comment]
> ```
> [22:48:36.610] [Launch] [21284] 要求窗口标题：MC  1.20.4  Ghost_bone  正版
> ```
> 
> 日志里是正常的……

那是什么情况

**Comment by allMagicNB** [comment]
```
[22:48:36.610] [Launch] [21284] 要求窗口标题：MC  1.20.4  Ghost_bone  正版
```
从日志上看没错啊……有人能复现吗？

**Comment by allMagicNB** [comment]
你重新试试？

**Comment by GhostBone** [comment]
> 你重新试试？

我重新安装了最新的fabric v0.15.10，此版本为第一个1.20.4正式fabric，之后能成功显示自定义游戏窗口标题。非常感谢你的回复(●'◡'●)
