### ISSUE TITLE
整合包版本名加入版本号

### ISSUE THREAD

**Issue by Misaka299** [Hex-Dragon/PCL2#3690]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

为整合包的默认命名添加版本号。我要升级整合包版本时去下载新版本，第二次需要自己命名。
而且最尴尬的是，我有时候不知道上个版本号是多少，如果版本多起来的话。容易不知道该删那个。

### 原因

~（示例）~
这项优化让我可以更方便地管理自己同一个整合包的不同版本。
如果没有这项优化，我每次都必须在下载新版本时手动区分命名，让操作变得很麻烦。

**Comment by wuliaodexiaoluo** [comment]
"versionId": "1.4.1"
感觉不是很需要，直接覆盖安装不好吗？
@allMagicNB 挂个待处理先

**Comment by LTCatt** [comment]
这个应该不会有太多玩家需要……暂时不考虑，抱歉 orz
