### ISSUE TITLE
登录微软账户时字体大小问题

### ISSUE THREAD

**Issue by HanXiaozeng** [Hex-Dragon/PCL2#3693]
### 检查项

- [ ] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

我不太清楚，这个反馈也有可能是一个BUG。
Lenovo 20wj 22631.3447
重现：找到启动项的正版按钮点击登录即可。
当然可能是我的笔记本电脑的问题，它的出场分辨率是200%这也许就是出错的原因；
最大可能是内置由IE浏览器进行联网,IE浏览器可能不适配高分辨率，但这是微软的问题。
如何解决？请看这个网站 https://learn.microsoft.com/zh-cn/microsoft-edge/webview2/get-started/winforms
方法就是将原先使用IE浏览器调用的链接改为Microsoft Edge，这样问题就成功解决了！😊
可以稍微改一改代码哦~
对了，这些错误可能只有笔记本用户才有，当然也可以当作一个小建议以后再改也完全没问题。

### 原因

更美观

**Comment by allMagicNB** [comment]
截个屏看看？

**Comment by Pigeon0v0** [comment]
Win7 / 8.1 / 早期版本 Win10 用户不一定有 WebView2

**Comment by wuliaodexiaoluo** [comment]
见 #122 
会考虑使用 Oauth 设备流，可以调其他浏览器

**Comment by wuliaodexiaoluo** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/160083863/cfaf872c-6fe6-432b-abf9-9459f51ce349)
他应该是指这个（笔记本调不到 200%，所以用 175% 替代
这个应该是 Internet Explorer 自适应问题
也就是说这个 Issue 可能可以关了？

**Comment by allMagicNB** [comment]
> ![image](https://github.com/Hex-Dragon/PCL2/assets/160083863/cfaf872c-6fe6-432b-abf9-9459f51ce349)
> 他应该是指这个（笔记本调不到 200%，所以用 175% 替代
> 这个应该是 Internet Explorer 自适应问题
> 也就是说这个 Issue 可能可以关了？

本身就是指这个，请勿 Comment 无用信息

**Comment by wuliaodexiaoluo** [comment]
我寻思着你不是要截图吗
另外这个 Issue 的建议等 #122 做了就解决了，完全可以打个重复关掉

**Comment by allMagicNB** [comment]
> 我寻思着你不是要截图吗
> 另外这个 Issue 的建议等 #122 做了就解决了，完全可以打个重复关掉

我要的是 Author 那边的截图……
#122 不会这么快就做好的……

**Comment by wuliaodexiaoluo** [comment]
> 我要的是 Author 那边的截图…… #122 不会这么快就做好的……

你现在提了也不可能在 122 搞完之前搞好

**Comment by allMagicNB** [comment]
> > 我要的是 Author 那边的截图…… #122 不会这么快就做好的……
> 
> 你现在提了也不可能在 #122 搞完之前搞好
> 这个功能和 #122 重复了

别叫，这应该是 DPI 缩放问题

**Comment by HanXiaozeng** [comment]
主要还是烦人的微软搞的鬼......

**Comment by HanXiaozeng** [comment]
好咧，我关了！
