### ISSUE TITLE
自定义主页代码导入整合包 无反应

### ISSUE THREAD

**Issue by wkea** [Hex-Dragon/PCL2#3695]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

自定义主页  我尝试了<local:MyButton Margin="0,5,0,6" Width="250" Height="35"
                    Text="安装整合包" EventType="导入整合包" />
                    
                    和<local:MyButton Margin="0,5,0,6" Width="250" Height="35"
                    Text="安装整合包" EventType="导入整合包" EventData="C:\Users\WKEA\Downloads\Compressed\CityLifereloaded.zip"/> 
                    均没有反应

### 重现步骤

使用<local:MyButton Margin="0,5,0,6" Width="250" Height="35"
                    Text="安装整合包" EventType="导入整合包" />

创建自定义主页无反应

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/15001641/Log3.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15001642/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/15001644/Log2.txt)

**Comment by allMagicNB** [comment]
又没这个类型……

**Comment by wkea** [comment]
> 又没这个类型......

**Comment by wkea** [comment]
> 又没这个类型......

![i](https://github.com/Hex-Dragon/PCL2/assets/52775998/e3a66da0-b853-46ec-ab79-35842b60076e)
![2](https://github.com/Hex-Dragon/PCL2/assets/52775998/4b1cec5c-9184-43f6-83ad-64cd313171c8)

教学文件 和 github上面代码是过时的吗 还是说 根本不存在

**Comment by wkea** [comment]
> 又没这个类型……

再使用 这段代码时
```
<local:MyButton Margin="0,5,0,6" Width="250" Height="35"
Text="安装整合包" EventType="导入整合包" />
```
并不会触发这个弹窗
```
 Case Else
                    MyMsgBox("未知的事件类型：" & Type & vbCrLf & "请检查事件类型填写是否正确，或者 PCL 是否为最新版本。", "事件执行失败")
```

**Comment by allMagicNB** [comment]
那你试试教学主页的导入整合包？

**Comment by wkea** [comment]
> ~可能是我记错了~ 那你试试教学主页的导入整合包？

教学主页没给这个示例 XD
教学中只是提了一下

**Comment by JingHai-Lingyun** [comment]
这个 EventType 确实没有反应
~~又是什么奇奇怪怪的 Bug~~

**Comment by wkea** [comment]
打算做一个 随机推荐整合包的自定义首页 通过首页安装整合包 发现有这个功能的 qwq 然后没反应

**Comment by wkea** [comment]
`[02:51:52.452] [Control] 按下按钮：安装整合包
[02:51:52.452] [Control] 执行自定义事件：导入整合包, C:\Users\WKEA\Downloads\Compressed\CityLifereloaded.zip, 测试安装, 
[02:51:53.118] [Control] 按下按钮：安装整合包
[02:51:53.118] [Control] 执行自定义事件：导入整合包, C:\Users\WKEA\Downloads\Compressed\CityLifereloaded.zip, 测试安装, 
[02:51:53.265] [Control] 按下按钮：安装整合包
[02:51:53.265] [Control] 执行自定义事件：导入整合包, C:\Users\WKEA\Downloads\Compressed\CityLifereloaded.zip, 测试安装, `
