### ISSUE TITLE
支持Windows 自动HDR

### ISSUE THREAD

**Issue by Xisen-XJX** [Hex-Dragon/PCL2#3696]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

官方启动器在打开时，Windows会提示支持自动HDR并且可以正常激活HDR效果，希望PCL也可以支持这一功能

### 原因

支持自动HDR之后可以有更好的游戏画面，并且兴许可以修复这个Windows开启HDR时启动游戏导致的bug：
进入游戏后显示器变回SDR，但退出游戏后HDR画面异常（只有鼠标指针有HDR效果，其他画面都是SDR，就得到了一个很亮很亮的鼠标指针）
（当然这个可能是MC1.20.1本身的问题）

**Comment by JingHai-Lingyun** [comment]
我没支持HDR的设备，也没找到重复的帖子，先加个待处理看看

**Comment by wuliaodexiaoluo** [comment]
大概率会被拒

**Comment by LTCatt** [comment]
这应该是 MC 做的事，不是启动器做的事情（
