### ISSUE TITLE
不能补全

### ISSUE THREAD

**Issue by RainbowTaro2022** [Hex-Dragon/PCL2#3698]
### 检查项

- [x] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

那边是没有嘛？

### 重现步骤

点开始游戏以后就这样了

### 日志与附件

![image](https://github.com/Hex-Dragon/PCL2/assets/42478088/840b1340-7d70-4fdb-8521-f38ef7063b66)

**Comment by Deep-Dark-Forest** [comment]
请补全日志
根据截图，大概率为您的网络问题

**Comment by allMagicNB** [comment]
估计是部分 BMCLAPI 节点问题或者自身网络问题

**Comment by wuliaodexiaoluo** [comment]
见 #3020
这个问题事实上是版本 json 文件提供的 Path 信息和 Forge Maven 服务器上存储的文件名不一致导致的

**Comment by wuliaodexiaoluo** [comment]
这边建议挂个待处理

**Comment by LTCatt** [comment]
不是 #3020，这是一个已修复 bug，反馈者应该没有更新

**Comment by wuliaodexiaoluo** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/160083863/00ffe248-e2e5-4d47-bbf1-028726cfb981)
![image](https://github.com/Hex-Dragon/PCL2/assets/160083863/adcb440e-2a00-4e2c-a8ca-5a13d4ade8ac)
[log3.txt](https://github.com/Hex-Dragon/PCL2/files/15038593/log3.2.txt)
那这怎么算？Snapshot 版没修好？
还是本来就补全不了

**Comment by zkitefly** [comment]
你是不是把这个位置的文件删了

![image](https://github.com/Hex-Dragon/PCL2/assets/64117916/f32806d5-0b30-436e-a846-1c20e0b10a0e)

**Comment by LTCatt** [comment]
如果补全补这个是 libraries 文件夹删了导致的，这个补不了，不能删这个文件夹里的所有东西

**Comment by RainbowTaro2022** [comment]
要怎么办？

**Comment by RainbowTaro2022** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/42478088/d18face4-67a8-47ab-95f5-f7250fa9c295)
应该是client，不是universal

**Comment by RainbowTaro2022** [comment]
应该加一个重建libraries文件夹的功能

**Comment by LTCatt** [comment]
那个文件是安装 forge 的时候 forge 安装器动态生成的，**只能通过安装 forge 来生成，除此之外没有渠道进行补全**

**Comment by zkitefly** [comment]
> 那个文件是安装 forge 的时候 forge 安装器动态生成的，**只能通过安装 forge 来生成，除此之外没有渠道进行补全**

不能在发现该文件不见的时候重新执行安装 Forge 操作补全吗

**Comment by wuliaodexiaoluo** [comment]
> > 那个文件是安装 forge 的时候 forge 安装器动态生成的，**只能通过安装 forge 来生成，除此之外没有渠道进行补全**
> 
> 不能在发现该文件不见的时候重新执行安装 Forge 操作补全吗

搞不好 Forge 可能会覆盖掉版本文件。。。

**Comment by LTCatt** [comment]
这个很麻烦，真的很麻烦……
