### ISSUE TITLE
自动内存优化（为了对低配党好一点）

### ISSUE THREAD

**Issue by chanzuiyu** [Hex-Dragon/PCL2#3700]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

当内存超出一定配额后，自动执行内存清理

### 原因

本人低配党，目前莫得买高配的，不然一下子就(错误代码: Out of Memory)

**Comment by mc-124** [comment]
我记得下个版本添加了自动清理
不过不是根据内存的
根据内存的话……PCL2挂在后台玩着玩着一下巨卡你受得了？
大概率忽略

**Comment by chanzuiyu** [comment]
> 我记得下个版本添加了自动清理 不过不是根据内存的 根据内存的话......PCL2挂在后台玩着玩着一下巨卡你受得了？ 大概率忽略

油道理
