### ISSUE TITLE
微软账户登录优化

### ISSUE THREAD

**Issue by zkitefly** [Hex-Dragon/PCL2#3702]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

https://github.com/HMCL-dev/HMCL/pull/2986

在该 PR 中，解决了以往需要 [“请前往 Minecraft 官网 登录您的 Minecraft 账号后，稍等片刻即可使用 PCL 正常登录”](https://github.com/Hex-Dragon/PCL2/discussions/1930#:~:text=%E8%AF%B7%E5%89%8D%E5%BE%80%20Minecraft%20%E5%AE%98%E7%BD%91%20%E7%99%BB%E5%BD%95%E6%82%A8%E7%9A%84%20Minecraft%20%E8%B4%A6%E5%8F%B7%E5%90%8E%EF%BC%8C%E7%A8%8D%E7%AD%89%E7%89%87%E5%88%BB%E5%8D%B3%E5%8F%AF%E4%BD%BF%E7%94%A8%20PCL%20%E6%AD%A3%E5%B8%B8%E7%99%BB%E5%BD%95) 这个问题

解决方法是需要在获取到授权后先访问该 API `https://api.minecraftservices.com/entitlements/mcstore` 然后再访问账户信息相关内容（相关文档 https://wiki.vg/Microsoft_Authentication_Scheme#Checking_Game_Ownership ）

就类似于帮你去 minecraft.net 登录了一遍（应该吧）

经过测试，该方法已经有很多人所测试成功

### 原因

减少登录失败的情况

**Comment by zkitefly** [comment]
注：该方案解决的是在 `微软登录步骤 6` 访问 `https://api.minecraftservices.com/minecraft/profile` 有时候会返回空值的情况，在这个步骤前面访问 `https://api.minecraftservices.com/entitlements/mcstore` 再执行就会返回内容

**Comment by allMagicNB** [comment]
这应当是一个 Bug 导致无法登录……

**Comment by allMagicNB** [comment]
https://github.com/Hex-Dragon/PCL2/blob/main/Plain%20Craft%20Launcher%202%2FModules%2FMinecraft%2FModLaunch.vb#L953-L976

**Comment by zly2006** [comment]
> 就类似于帮你去 minecraft.net 登录了一遍（应该吧）

没有，只是完整走一遍官启流程，本质原因应该是ojng那屎山缓存逻辑
