### ISSUE TITLE
[Bug] 自动补全的 OptiFine 大小与手动安装和官网下载的 OptiFine 不一致且无法被作为 mod 安装到 mods 文件夹或链接到 classpath

### ISSUE THREAD

**Issue by wuliaodexiaoluo** [Hex-Dragon/PCL2#3703]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

PCL 自动补全的 OptiFine 大小是 6.5M，但手动安装的大小和官网标定大小均为 7.0M
并且自动补全的 OptiFine 直接安装到 mods 会导致 Minecraft 崩溃（这个问题终于找到原因了）

### 重现步骤

1.下载带有 Forge + OptiFine 的版本
2.下载只带 Forge 的版本（出现问题的环境：Minecraft 1.20.4 Forge 49.0.31）
3.把 PCL 安装的 OptiFine 复制到只带 Forge 的 mods 文件夹里
4.启动游戏，游戏崩溃

### 日志与附件

[PCL 安装的 OptiFine](https://github.com/Hex-Dragon/PCL2/files/15046866/OptiFine-1.20.4_HD_U_I7.zip)
[官网 OptiFine](https://github.com/Hex-Dragon/PCL2/files/15046868/OptiFine_1.20.4_HD_U_I7.zip)
（均为 jar，zip只是因为 GitHub 不让传

**Comment by allMagicNB** [comment]
你倒是给个复现环境啊……

**Comment by wuliaodexiaoluo** [comment]
jdk 17
官版 zulu 均可

**Comment by allMagicNB** [comment]
我是说 Minecraft 版本

**Comment by wuliaodexiaoluo** [comment]
> 我是说 Minecraft 版本

1.20.4 Forge 49.0.31

**Comment by allMagicNB** [comment]
里边的 patch 文件夹没了

**Comment by hejiehao** [comment]
我感觉是故意的

**Comment by allMagicNB** [comment]
就是故意的
+

**Comment by wuliaodexiaoluo** [comment]
PCL 自动安装本来就是没有 Patch 的，不然大小就是和 OptiFine 官网标定的 7.0M 接近或一致了
![image](https://github.com/Hex-Dragon/PCL2/assets/160083863/1ca6e454-5be5-4927-a834-2265272f6ade)

**Comment by burningtnt** [comment]
差异肯定不止这点，否则 OptiFine 不可能跑不起来……

**Comment by allMagicNB** [comment]
> 差异肯定不止这点，否则 OptiFine 不可能跑不起来……

是的，我刚才比较压缩包时发现 `src` 文件夹的内容也不同……

**Comment by wuliaodexiaoluo** [comment]
我不知道怎么说，
https://bmclapi2.bangbang93.com/maven/com/optifine/1.20.4/OptiFine_1.20.4_HD_U_I7.jar
文件是从 bmclapi 请求过来的，但我尝试请求几次都是 6.9M....

**Comment by allMagicNB** [comment]
不对啊，谁让你这样乱搞的？PCL 原本把它当作库来使就没出差错你把它当作 Mod 来搞？

**Comment by wuliaodexiaoluo** [comment]
完事你把 mods.toml 删掉后让玩家对着 
### Minecraft 出现问题 
这个窗口发呆？

**Comment by allMagicNB** [comment]
> 完事你把 mods.toml 删掉后让玩家对着
> 
> ### Minecraft 出现问题
> 这个窗口发呆？

喂，那是 HMCL 的解决方案

**Comment by wuliaodexiaoluo** [comment]
谁说 HMCL 的方法龙猫不能用的？？？
