### ISSUE TITLE
在查找 Java 时排除网络驱动器

### ISSUE THREAD

**Issue by Pigeon0v0** [Hex-Dragon/PCL2#3705]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

如题，在进行 Java 查找时排除来自网络驱动器的 Java。

### 原因

使用来自网络驱动器的 Java 可能导致意外情况发生，应尽可能避免使用，同时疑似会拖慢 Java 查找速度。

**Comment by Pigeon0v0** [comment]
附：[Win32 API](https://learn.microsoft.com/zh-cn/windows/win32/api/fileapi/nf-fileapi-getdrivetypea)

**Comment by LTCatt** [comment]
补充日志

**Comment by Pigeon0v0** [comment]
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15050119/Log1.txt)

**Comment by LTCatt** [comment]
感觉没有必要进行类似处理……毕竟一方面没有报错，一方面可能也有人真的需要……先不做吧 orz

**Comment by FFDVDGD** [comment]
> 感觉没有必要进行类似处理…… 毕竟一方面没有报错，一方面可能也有人真的需要…… 先不做吧 orz

做一下这个功能吧，龙猫大大
