### ISSUE TITLE
CleanroomLoader兼容性问题

### ISSUE THREAD

**Issue by EringMantis831** [Hex-Dragon/PCL2#3707]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在安装基于CRL的整合包时，启动器会出现严重的兼容性问题：无法安装。
目前已知同样存在此问题的启动器还有HMCL，而PrismLauncher与MultiMC并不存在此问题。
链接: https://pan.baidu.com/s/1ydOcVT9J6Iun0hZI9KpFPw?pwd=12ab

### 重现步骤

安装基于CRL的整合包即可，然而很明显这种包没几个。
附有下载链接，请自便

### 日志与附件

·

**Comment by allMagicNB** [comment]
#3003（#3004）

**Comment by hejiehao** [comment]
似乎是 https://github.com/Hex-Dragon/PCL2/discussions/3004 ？
