### ISSUE TITLE
无法点击游戏中按钮，分辨率不正确

### ISSUE THREAD

**Issue by linux1145** [Hex-Dragon/PCL2#3711]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

无法点击游戏

启动游戏全屏后出现
![image](https://github.com/Hex-Dragon/PCL2/assets/146413137/af41b26c-1126-46e8-8672-968eb4c2b21a)

### 重现步骤

直接启动游戏后有几率出现此bug
部分时候多重启几次游戏可以解决

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/15048848/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/15048849/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/15048850/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/15048851/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15048852/Log1.txt)

**Comment by zkitefly** [comment]
这是游戏问题，与 PCL 无关

**Comment by linux1145** [comment]
用另一个没mod原版也有几率出现
