### ISSUE TITLE
[Bug] 在下载过程中更改版本文件名，触发安装失败后版本文件无法在 PCL 内版本列表展示

### ISSUE THREAD

**Issue by wuliaodexiaoluo** [Hex-Dragon/PCL2#3712]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

疑似 #2781 没有修复完全
~这个刷新到底有没有用啊~

### 重现步骤

1、随便下一个版本
2、在资源管理器里面改名
3、触发下载失败后，该版本文件夹仍在 Versions 且包含 json，PCL 也为其创建了 PCL 的配置文件夹，但在版本列表没有显示这个版本

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15050224/Log1.txt)

**Comment by allMagicNB** [comment]
截屏下文件夹和 PCL2 选择版本界面

**Comment by allMagicNB** [comment]
不对，故意触发的 Bug PCL 不会为此做出措施

**Comment by kong-que-dnf123** [comment]
下载期间改掉文件夹的名字...是这样吗？
然后我就改出了个报错还改出了个“错误的版本”
```
安装游戏失败
→ Minecraft json 有误，地址：D:\Launcher\JE\PCL\.minecraft\versions\1.20.4-Fabric 0.15.10\1.20.4-Fabric 0.15.10.json，前段内容：
   在 PCL.ModDownloadLib.InstallMerge(String OutputFolder, String MinecraftFolder, String OptiFineFolder, Boolean OptiFineAsMod, String ForgeFolder, String ForgeVersion, String FabricFolder, String LiteLoaderFolder)
   在 PCL.ModDownloadLib._Closure$__57-0._Lambda$__1(LoaderTask`2 Task)
   在 PCL.ModLoader.LoaderTask`2._Closure$__13-0._Lambda$__0()
```
![image](https://github.com/Hex-Dragon/PCL2/assets/120994373/eeec36e5-7e2a-4ae4-9dab-51e572a68c38)


--------------------------------------------------------------------------------------------------------------------------------------------
以及我通过观察资源管理器时是改名的一瞬间PCL又新建了个原来版本名字的文件夹~（我刻意用的Fabric触发版本隔离方便改名.jpg）~，在报错之后又给再次创建的文件夹删了.......

**Comment by wuliaodexiaoluo** [comment]
问题是 PCL 识别到了文件夹，但没有在里面展示，复制再粘贴都没用的那种
![image](https://github.com/Hex-Dragon/PCL2/assets/160083863/03ad435c-9ebe-4794-9943-f62ec586619a)
![image](https://github.com/Hex-Dragon/PCL2/assets/160083863/69f99cb9-421e-4c53-9b20-869558439b7a)

**Comment by wuliaodexiaoluo** [comment]
你可能需要快点

**Comment by kong-que-dnf123** [comment]
Cool我给内部的json文件名改的与文件夹同名直接PCL表示找到这个版本的json了
![image](https://github.com/Hex-Dragon/PCL2/assets/120994373/970b56a8-e28c-41cf-89e5-7277d3ea7d42)
![image](https://github.com/Hex-Dragon/PCL2/assets/120994373/8ecd7e4b-d626-4307-8e33-107e1a3f1ae9)
![image](https://github.com/Hex-Dragon/PCL2/assets/120994373/7de990d3-7c77-44b0-8a23-c080c35e02f6)

**Comment by wuliaodexiaoluo** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/160083863/1efcc781-2d58-482d-9c0e-a9e566e59d45)
我怎么改怎么刷都显示不了一点

**Comment by allMagicNB** [comment]
其实是 PCL 在版本文件夹下创建了 `.pclignore` 文件让搜索时忽略而已

**Comment by wuliaodexiaoluo** [comment]
就无语，版本文件有 json 为什么忽略。。。

**Comment by allMagicNB** [comment]
> 就无语，版本文件有 json 为什么忽略。。。

你别无语，你先让我无语下，
# 你是天天没 Bug 找 Bug 天天找茬吗？你为啥要在下载时给文件夹改个名？你又为什么这样出问题了要来反馈？

**Comment by JingHai-Lingyun** [comment]
友好交流，谢谢

**Comment by WForst-Breeze** [comment]
我们在这里的目的是解决问题，而不是发生口角和争斗。为了避免不必要的冲突，**请务必保证冷静友善交流**。

**Comment by wuliaodexiaoluo** [comment]
> > 就无语，版本文件有 json 为什么忽略。。。
> 
> 你别无语，你先让我无语下，
> 
> 没事了我没话说了.jpg

#2781 等价于这个 Issue
如果真算故意的 #2781 为什么要被处理（#2781 的触发方式是中断下载，不也是故意的？

**Comment by allMagicNB** [comment]
> > > 就无语，版本文件有 json 为什么忽略。。。
> > 
> > 你别无语，你先让我无语下，
> > 
> > 没事了我没话说了.jpg
> 
> #2781 等价于这个 Issue
> 如果真算故意的 #2781 为什么要被处理（#2781 的触发方式是中断下载，不也是故意的？

人家又不是手动触发，是全程通过 PCL 操作触发，你才是通过手动触发

**Comment by kong-que-dnf123** [comment]
等一下补全文件不会补json吗？
我改了json的名字，按补全文件没有对json进行修改

此时运行游戏会正常开启但会有一个检查失败

然后精彩的就来了
---
我重开后调试模式弹出无效的MC，但是版本选择图标正常，右键可进入版本设置但是内部图标变成了代表错误的红石块，左键点击版本弹出文件夹路径（左键点击一个错误的MC时就会这样）
第二次重开这个MC才被正常计入“错误的版本”里

笑

**Comment by kong-que-dnf123** [comment]
等一下补全文件不会补json吗？
我改了json的名字，按补全文件没有对json进行修改

此时运行游戏会正常开启但会有一个检查失败

然后精彩的就来了
---
我刷新MC（你是切概述啊还是回到版本选择啊都行）调试模式弹出无效的MC，但是版本选择图标正常，右键可进入版本设置但是内部图标变成了代表错误的红石块，左键点击版本弹出文件夹路径（左键点击一个错误的MC时就会这样）
重开PCL这个MC才被正常计入“错误的版本”里

笑

**Comment by wuliaodexiaoluo** [comment]
这个 Bug 就够离谱的
