### ISSUE TITLE
支持对Quilt的下载

### ISSUE THREAD

**Issue by lienting885** [Hex-Dragon/PCL2#3714]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

在“自动安装”页面添加下载Quilt及其相关mod(如QuiltStandardLibraries  QuiltLoom  QuiltMappings  QuiltedFabricAPI等)的选项，上述mod也请在“mod下载”页面添加。在“手动安装”页面添加Quilt的jar安装包。在“整合包下载”页面添加对Quilt整合包的支持。

### 原因

我需要这个功能来下载Quilt及相关整合包和mod。很多人都有下载Quilt及相关整合包和mod，但如果没有这个功能，就不能下载Quilt及相关整合包和mod了。

**Comment by allMagicNB** [comment]
#48
