### ISSUE TITLE
动画bug

### ISSUE THREAD

**Issue by mc-124** [Hex-Dragon/PCL2#3715]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

更多页面的左侧栏大小不正常

### 重现步骤

尝试复现3710时从下载点到更多，就触发这个bug了，我也不知道为什么（

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15051185/Log1.txt)
[视频，经过zip二次压缩的7z](https://github.com/Hex-Dragon/PCL2/files/15051188/Plain.Craft.Launcher.2024-04-21.16-27-55_2.zip)

**Comment by allMagicNB** [comment]
#2982
