### ISSUE TITLE
数字签名问题

### ISSUE THREAD

**Issue by ProgrammerMAX114514** [Hex-Dragon/PCL2#3718]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

PCL2之前有数字签名，现在打开显示未知发布者

### 重现步骤

1.打开控制面板，将用户账户控制设置更改为始终通知
2.找到PCL2，右键，以管理员身份运行
3.显示未知发布者
![image](https://github.com/Hex-Dragon/PCL2/assets/143252860/0653dbbb-1d5a-48dd-9bc6-3f501c1e9004)

### 日志与附件

这个问题没有日志

**Comment by youzi-2333** [comment]
https://github.com/Hex-Dragon/PCL2/issues/1974#issuecomment-1602072845 ：

> 由于 PCL 快照版更新的加密系统限制，快照版无法添加数字证书，不过倒是给正式版折腾上了 =。=

请确认您的 PCL 版本是正式版（

**Comment by hejiehao** [comment]
> [#1974 (comment)](https://github.com/Hex-Dragon/PCL2/issues/1974#issuecomment-1602072845) ：
> 
> > 由于 PCL 快照版更新的加密系统限制，快照版无法添加数字证书，不过倒是给正式版折腾上了 =。=
> 
> 请确认您的 PCL 版本是正式版（

似乎正式版也没有

**Comment by allMagicNB** [comment]
#3651

**Comment by LTCatt** [comment]
2.7.1.1 因为是紧急更新的所以没有来得及签名（

**Comment by allMagicNB** [comment]
> 2.7.1.1 因为是紧急更新的所以没有来得及签名（

在#3651 里边加一段吧，我进去看的时候找来找去就是没找到说没有数字签名，但我还记得有
