### ISSUE TITLE
游戏版本的下载路径

### ISSUE THREAD

**Issue by yuanniiguilai** [Hex-Dragon/PCL2#3720]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

希望可以自定义游戏版本的下载路径

### 原因

这项优化让我可以更方便地下载游戏文件，因为c盘空间小，想要在D盘下次
如果没有这项优化，我每次都必须清理C盘，让操作变得很麻烦

**Comment by yuanniiguilai** [comment]
对不起，第一句的最后是下载，我手快打错了，对不起对不起对不起

**Comment by JingHai-Lingyun** [comment]
已经可以修改客户端安装的位置
1. 在你想要放置客户端的位置新建一个 `.minecraft` 文件夹
2. 启动器 -> 左下角 -> 版本选择
3. 添加或导入 -> 添加已有文件夹
4. 选择你刚才创建的那个 `.minecraft` 文件夹
5. 给这个文件夹（分类）起个名字
6. 接下来的客户端下载和安装都将放在这个新文件夹内

---

对于已经在 C 盘内的客户端：
复制整个 `versions` 文件夹内的内容到新 `.minecraft` 文件夹的 `versions` 文件夹内即可
然后旧的其他东西都可以删掉了

---

> 对不起，第一句的最后是下载，我手快打错了，对不起对不起对不起

你可以使用 Edit 功能修改你曾经发出去的话：右上角 `...` -> Edit，改完之后按 `update comment`

**Comment by yuanniiguilai** [comment]
谢谢你
