### ISSUE TITLE
登录正版账号或启动游戏无法正常运行报错

### ISSUE THREAD

**Issue by ZiChuan7** [Hex-Dragon/PCL2#3723]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![dcd34878ab26f71fd95830c4629c3630](https://github.com/Hex-Dragon/PCL2/assets/167798869/b8d87c00-972a-4430-b3e0-ae79808198fc)

### 重现步骤

1、点击xxxx
2、往下滚，然后点击xxxx

### 日志与附件

![Uploading dcd34878ab26f71fd95830c4629c3630.png…]()

**Comment by allMagicNB** [comment]
请发送日志，也请等 `Uploading xxx` 字样小消失后再 Comment

**Comment by wuliaodexiaoluo** [comment]
`Xerr 2148916227`

这个 XSTS 错误代码代表 Microsoft 账户被执行了强制登录禁令（也就是你的 Microsoft 账户被设置为禁止登录）
你应该检查下账户年龄设置，如果这是子女账户，请登录 Microsoft Family 查看账户是否被错误的配置成了禁止登陆

**Comment by allMagicNB** [comment]
自身账户有问题的怎么也登录不了吧……

**Comment by JingHai-Lingyun** [comment]
参见 https://github.com/rtm516/MCXboxBroadcast/issues/10#issuecomment-1444958278 ，这可能是由于你的账户有强制登陆禁令导致的

**Comment by wuliaodexiaoluo** [comment]
问题是这个错误代码只对应了强制登陆禁令
没有第二种可能了....

**Comment by wuliaodexiaoluo** [comment]
这个 Issue 掐了吧
https://github.com/Hex-Dragon/PCL2/discussions/3722#discussioncomment-9197168

**Comment by zkitefly** [comment]
https://github.com/HMCL-dev/HMCL/issues/889

**Comment by wuliaodexiaoluo** [comment]
有没有可能 Xerr 结尾是227？

**Comment by zkitefly** [comment]
> 有没有可能 Xerr 结尾是227？

https://github.com/PojavLauncherTeam/PojavLauncher/issues/4819

试试 https://support.xbox.com/help/errors/xbox-360/error-code-8015d003 ？
