### ISSUE TITLE
mod管理功能将sb_objectsblocks错误识别为geckolib的更高版本

### ISSUE THREAD

**Issue by Dave12138** [Hex-Dragon/PCL2#3725]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

mod管理功能将[geckolib](https://www.curseforge.com/minecraft/mc-mods/geckolib)识别为[security breach objects, blocks & more](https://modrinth.com/mod/security-breach-objects,-blocks-more)
此时表现为mod名称识别错误
![image](https://github.com/Hex-Dragon/PCL2/assets/35069593/2f11116a-8d44-4229-9bf7-cbde14ea82fd)
点击升级，启动器会下载sb_objectsblocks（127MB），后删除geckolib（967KB）

### 重现步骤

1、安装geckolib
2、在mod管理界面选择geckolib
3、点击升级

### 日志与附件

[Log.txt](https://github.com/Hex-Dragon/PCL2/files/15074784/Log.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15074786/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/15074790/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/15074791/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/15074793/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/15074795/Log5.txt)

**Comment by Dave12138** [comment]
值得一提的是，[七天前就有关于这个问题的讨论了](https://bbs.mcmod.cn/thread-18151-1-1.html)

**Comment by JingHai-Lingyun** [comment]
感谢反馈，附一份我的带调试模式的复现日志
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15074869/Log1.txt)
~~这又是什么奇奇怪怪的 Bug~~

**Comment by allMagicNB** [comment]
似乎不止有这个 Mod 识别错误，可否改下标题一块修了？@LTCatt

**Comment by LTCatt** [comment]
Modrinth API 有识别问题，我先去交个反馈

**Comment by LTCatt** [comment]
https://api.modrinth.com/v2/version_file/29dccfe1f985d3efdcd56d24ce4fe0ccc28cee7f 返回了错误的文件。
已经向 Modrinth 提交了反馈，PCL 会上线一个临时修复。

**Comment by Dave12138** [comment]
![img](https://s2.loli.net/2024/05/18/ydEcxFBnJr1IXLk.webp)
疯狂暗示（

**Comment by JingHai-Lingyun** [comment]
> 疯狂暗示（

请发你的识别码

**Comment by Dave12138** [comment]
044A-D0AA-7ECE-F0B9

**Comment by LTCatt** [comment]
你的解锁码：2RqPNlAd27fcNXajtS49v5hOC0HFTQ3S
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by Dave12138** [comment]
![](https://s2.loli.net/2024/05/19/sJR4o1hxXGnKZge.webp)
![](https://s2.loli.net/2024/05/19/qw9pI42Yt7FD5QG.webp)
坏了，它复发了(Snapshot 2.7.3)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15368796/Log1.txt)

**Comment by allMagicNB** [comment]
@LTCatt

**Comment by Dave12138** [comment]
理所当然地，下载mod是筛选限制为Modrinth源不会出现这种问题，但在不了解来源的人眼里是这样的：
![](https://s2.loli.net/2024/05/19/rCHwnX6T4DkcOtL.webp)
