### ISSUE TITLE
更多页面左侧菜单栏背景填充位置异常

### ISSUE THREAD

**Issue by Gaobaiawa** [Hex-Dragon/PCL2#3726]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

by pclx5的3498961553用户反馈（非本人）
我要主题，主题，隐藏主题！
开学勿踢20018 18:25:11
打开启动器

开学勿踢20018 18:25:17
弹出更新1.20.5rc3

开学勿踢20018 18:25:20
我点了更新

开学勿踢20018 18:25:27
就一直加载

开学勿踢20018 18:25:34
然后我转到了更多

开学勿踢20018 18:25:40
百宝箱

开学勿踢20018 18:25:42
下载了个东西

开学勿踢20018 18:25:47
就发现了
切换到其他页面再切换回来就又好了
![Image_1713867875807](https://github.com/Hex-Dragon/PCL2/assets/123546075/4bb40781-c2f3-4ee5-87a1-ec49bdd6b4bc)
![Image_1713867874107](https://github.com/Hex-Dragon/PCL2/assets/123546075/aed53867-5c1f-4a34-a5d4-e74388acfd9e)
![Image_1713867872698](https://github.com/Hex-Dragon/PCL2/assets/123546075/69066393-8f04-465a-8a94-0a5933423d7c)

### 重现步骤

开学勿踢20018 18:25:11
打开启动器

开学勿踢20018 18:25:17
弹出更新1.20.5rc3

开学勿踢20018 18:25:20
我点了更新

开学勿踢20018 18:25:27
就一直加载

开学勿踢20018 18:25:34
然后我转到了更多

开学勿踢20018 18:25:40
百宝箱

开学勿踢20018 18:25:42
下载了个东西

开学勿踢20018 18:25:47
就发现了
切换到其他页面再切换回来就又好了

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15075407/Log1.txt)
我不知道剩下的四个，他只给了我一个
给个主题吧，plzzzz

**Comment by JingHai-Lingyun** [comment]
#2982 重复，很抱歉，您无法获得主题。
