### ISSUE TITLE
[优化] 使用 OptiFine Installer 替代自动安装的 OptiFine 支持库

### ISSUE THREAD

**Issue by wuliaodexiaoluo** [Hex-Dragon/PCL2#3727]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

我也不知道 PCL 这只有 6.5M 还只能链接到 classpath 的 OptiFine 到底是哪来的
不过据我观察 OptiFine Installer 实际上是等价于自动安装的 OptiFine 支持库

### 原因

这个和 #3573 有点关系
因为自动安装的 OptiFine 只能打 args 禁用，搞不好就是第二个 #3511 
改成 OptiFine Installer 就可以删文件和打文件（怎么看怎么比打 args 好，至少证明了不会报错）

**Comment by allMagicNB** [comment]
没啥必要就是了，但还是等等龙猫吧……

**Comment by wuliaodexiaoluo** [comment]
所以有人能告诉我
这只有 6.5M 还只能链接到 classpath 的 OptiFine 到底是哪来的吗？

**Comment by allMagicNB** [comment]
> 先等 #3573 再看做不做，#3573 解决了就没必要做

@LTCatt
