### ISSUE TITLE
启动前执行命令的一个问题

### ISSUE THREAD

**Issue by candybits** [Hex-Dragon/PCL2#3728]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

已开启版本隔离，使用高级启动选项中的启动前执行命令，输出结果为.minecraft文件夹，而不是版本文件夹。
直接在版本文件夹中运行该mod可以正常读取配置与输出。

### 原因

使用serversync同步mod时，开启版本隔离后，并不会在版本文件夹中的config中寻找配置与输出，而是直接在.minecraft文件夹中读取该mod的配置与需要同步的mods文件夹。启动前执行命令尝试过使用{verpath}与{verindie}都是读取的.minecraft文件夹，希望开启版本隔离后可以读取与输出版本文件夹而不是只能.minecraft文件夹。

**Comment by wuliaodexiaoluo** [comment]
请提供日志
另外这是 Bug

**Comment by JingHai-Lingyun** [comment]
参见 #3546，不过由于该作者长期未补充信息而关闭，你可以直接在这里补充以下信息

---

https://github.com/Hex-Dragon/PCL2/issues/3546#issuecomment-2011563509 ：
根据您的描述，我理解为此Issue实际上描述了一个“启动前执行命令的上下文与版本隔离状态不符”的问题。
作为临时措施，请您尝试先在脚本中切换上下文到文件所在目录。
具体操作为：在脚本第一行加入：
`cd /d %~dp0`

另也请补充日志

**Comment by candybits** [comment]
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15087814/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/15087815/Log2.txt)

**Comment by wuliaodexiaoluo** [comment]
你是不是没开版本管理
`--gameDir "D:\游戏\PCL\.minecraft" `

**Comment by candybits** [comment]
开启了，这个是我测试未开启版本隔离时开启游戏测试的。

**Comment by candybits** [comment]
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15087916/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/15087919/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/15087920/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/15087921/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/15087922/Log5.txt)
补充5个家里的电脑上的log，上面的是另外一台电脑。中间应该都测试过关闭与开启版本隔离。

**Comment by JingHai-Lingyun** [comment]
```
log1 第 464 行，第一回上传的
[12:12:30.210] [Launch] 正在执行版本自定义命令："C:\Program Files\Java\jre-1.8\bin\java.exe" -jar "D:\游戏\PCL\.minecraft\versions\RLCraft\serversync-3.6.0-all.jar" progress-only
```
看起来好像没有问题？

**Comment by candybits** [comment]
这里是我将版本文件夹中config的配置复制过来一份来测试同步的位置，依然同步在.minecraft文件夹。

**Comment by wuliaodexiaoluo** [comment]
Snapshot 2.7.1 调试模式下未能复现
Release 2.7.1 调试模式下依旧未能复现

**Comment by wuliaodexiaoluo** [comment]
容我问一句，你开的是什么模式的版本隔离
![image](https://github.com/Hex-Dragon/PCL2/assets/160083863/8740bacd-3bd5-435f-be9e-9cf3dc3a630f)
这里起码有四个隔离模式

**Comment by candybits** [comment]
很奇怪，我这里是稳定复现，开启的隔离所有版本。

**Comment by candybits** [comment]
![QQ图片20240424130019](https://github.com/Hex-Dragon/PCL2/assets/52438993/5eb9e040-f958-4d0c-8c05-f699d6bebe5d)可以正常打开。
![QQ图片20240424130307](https://github.com/Hex-Dragon/PCL2/assets/52438993/8eb22f59-4f0e-4012-bb7b-69896cb99464)
全局版本隔离设置。
![QQ图片20240424130343](https://github.com/Hex-Dragon/PCL2/assets/52438993/1029548b-2524-4b9a-b57f-fe2f6eca63af)
单独的版本隔离。
![QQ图片20240424130402](https://github.com/Hex-Dragon/PCL2/assets/52438993/22eba185-81a2-4504-bebf-238385ac8dd3)
启动前执行命令。

**Comment by JingHai-Lingyun** [comment]
又想了想，应该是执行位置的问题。根据 PCL 启动前执行命令的 ToolTip
![image](https://github.com/Hex-Dragon/PCL2/assets/109946426/8681acad-561d-49c6-8456-33ffe3302028)
的最后一行说明，这不是 Bug。

---

你可以通过使用脚本而不是直接执行命令的方式来在正确的路径下启动
提供一个示例

```batch
REM 根据传入参数切换路径
cd /d %1

REM 下面放你的脚本主内容
```

然后通过 `脚本名.bat {verindie}` 的方式启动
