### ISSUE TITLE
多人游戏正版登录失败

### ISSUE THREAD

**Issue by luduting** [Hex-Dragon/PCL2#3729]
### 检查项

- [ ] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

正版进入服务器时登录失败，显示离线皮肤，没有正版认证

### 重现步骤

用PCL2启动游戏后多人游戏输入Wdsj.net

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15088335/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/15088336/Log2.txt)

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/15088377/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/15088378/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/15088379/Log5.txt)

**Comment by allMagicNB** [comment]
一般来讲，这个问题与 PCL2 无关

**Comment by allMagicNB** [comment]
试试用 HMCL

**Comment by JingHai-Lingyun** [comment]
Log2 第 223 行提示
```
[20:21:28.844] [Launch] 登录方式：Microsoft
```
你成功的以微软登录方式启动了客户端。
对于无法加入服务器的情况，这大概率不是 PCL 启动器的问题
另，如有需要，请移步 [Discussion 提问板块发帖提问](https://github.com/Hex-Dragon/PCL2/discussions/new?category=%E6%8F%90%E9%97%AE)

不过提到了 `显示离线皮肤` 所以还是先挂在这里好了

**Comment by wuliaodexiaoluo** [comment]
根据服务器官方公告，你需要完成正版验证才能显示皮肤
[官方公告](https://bbs.wdsj.net/d/373)
具体操作：
登录服务器后使用 `/zb ms Microsoft 账户电子邮件`
连接 zb.wdsj.net 完成验证

**Comment by JingHai-Lingyun** [comment]
那这就不是 PCL 的问题了

**Comment by luduting** [comment]
OK感谢感谢



在 2024-04-24 15:52:30，"无聊的小洛" ***@***.***> 写道：

根据服务器官方公告，你需要完成正版验证才能显示皮肤
官方公告
具体操作：
登录服务器后使用 /zb ms Microsoft 账户电子邮件
连接 zb.wdsj.net 完成验证

**Comment by wuliaodexiaoluo** [comment]
对
