### ISSUE TITLE
右下角按钮消失了悬浮提示还在

### ISSUE THREAD

**Issue by iPodtouch6557** [Hex-Dragon/PCL2#3734]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

<img width="217" alt="image" src="https://github.com/Hex-Dragon/PCL2/assets/118656946/93dd3f8e-8249-468b-99b7-2c707362b8e8">

### 重现步骤

1、打开下载
2、在下载任务完成前，将鼠标悬浮到上面出现提示
3、等到按钮消失即可复现

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15110595/Log1.txt)

**Comment by JingHai-Lingyun** [comment]
怎么感觉是 WPF 或者 Windows 的特性

**Comment by iPodtouch6557** [comment]
像是，但是反馈了再说（

**Comment by mc-124** [comment]
是WPF的bug，应该是没能触发鼠标移出事件，代码应该可以通过其它控件的鼠标进入事件调用一个刷新函数把一些没触发移出事件但是已经触发过了进入事件的控件状态刷掉
