### ISSUE TITLE
游戏窗口

### ISSUE THREAD

**Issue by cbs001** [Hex-Dragon/PCL2#3737]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

如果你在设置-系统-屏幕中，修改了屏幕的缩放比例（比如我设置成了200%），那么此时默认就会启动一个很小的游戏窗口。对一些特殊的屏幕不太方便

### 原因

这项优化让我可以更方便地启动游戏窗口。

**Comment by dargoncat** [comment]
![捕获](https://github.com/Hex-Dragon/PCL2/assets/121101691/f425ca46-0464-4e85-af0e-72bbb1dc0613)
？设置有啊

**Comment by JingHai-Lingyun** [comment]
该 Issue 的作者貌似是希望在高分屏下自动调整游戏窗口的大小，以适应高分屏？
我找找看有没有重复的先

**Comment by allMagicNB** [comment]
@LTCatt 这不用处理直接关……？

**Comment by LTCatt** [comment]
这是我自己已经发现了并且修了的 bug……只是还没更新也没人交……
