### ISSUE TITLE
部分mod更新时错误更新为其他mod

### ISSUE THREAD

**Issue by Tony0531** [Hex-Dragon/PCL2#3738]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

目前版本为1.12.2，游玩整合包时使用自带更新功能发现ae2和其他一个mod匹配升级错误，升级后会加入新mod并移除原mod
![屏幕截图 2024-04-26 192144](https://github.com/Hex-Dragon/PCL2/assets/37492100/3e6cc1a0-5a94-424b-9311-83d8fd1774f1)
![屏幕截图 2024-04-26 192138](https://github.com/Hex-Dragon/PCL2/assets/37492100/cb996a61-7b81-4496-8bc9-4043c62fc90c)

### 重现步骤

1.安装水星迫降重置版（1.12.2）
2.升级ae2mod和如图mod

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/15129950/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/15129951/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/15129954/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15129955/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/15129956/Log2.txt)

**Comment by allMagicNB** [comment]
#3725

**Comment by LTCatt** [comment]
这似乎是 Modrinth 的另一个 bug，但目前我重现不出来，很特么奇怪

**Comment by allMagicNB** [comment]
总不可能 Mod 文件损坏了吧（

**Comment by LTCatt** [comment]
如果一周后依然无人可以复现就关了（

**Comment by Tony0531** [comment]
之前用的是这个整合包，但我今天重新安装试了一下发现没有问题了
https://pan.baidu.com/s/171IZKYkbuP9JB9IGO1Q-6g?pwd=feng

**Comment by LBZiXL** [comment]
我这个明明是1.20.4的MC，PCL会自动把Mod更新为1.20.6的最新版，导致MC崩溃
![image](https://github.com/Hex-Dragon/PCL2/assets/115980764/e214a8b0-63c1-4d5a-9760-427604cd74cb)

**Comment by JingHai-Lingyun** [comment]
@LBZiXL 你这个是 #3680

**Comment by LTCatt** [comment]
由于无人能复现暂时关闭
