### ISSUE TITLE
1.20.5从本版本开始正式版开始要求 **### `Java 21`** 以及 64 位操作系统

### ISSUE THREAD

**Issue by china8028** [Hex-Dragon/PCL2#3740]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/Hex-Dragon/PCL2/assets/149222241/605428a5-c370-4148-a477-ba4625a1d950)
https://www.oracle.com/cn/java/technologies/downloads/#jdk21-windows Java：请从此在更新时获取Java

### 重现步骤

1.20.5从本版本开始正式版开始要求 **### `Java 21`** 以及 64 位操作系统

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/15132637/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/15132638/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/15132639/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15132640/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/15132641/Log2.txt)

**Comment by zkitefly** [comment]
https://github.com/Hex-Dragon/PCL2/issues/3601

**Comment by wuliaodexiaoluo** [comment]
你打错了
这个实际上是 #3735

**Comment by zkitefly** [comment]
> 你打错了 这个实际上是 #3735

啥？

这个是不会选择 22 及以上版本，21 会选择的
