### ISSUE TITLE
无法正常安装版本为24w14potato的mod整合包

### ISSUE THREAD

**Issue by NewbieXvwu** [Hex-Dragon/PCL2#3741]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

安装版本为24w14potato的mod整合包会报错

报错摘要，详细的请看日志文件：
→ 无法从传输连接中读取数据: 远程主机强迫关闭了一个现有的连接。
→ 远程主机强迫关闭了一个现有的连接。
   在 PCL.ModNet.NetFile.Thread(NetThread Info)
错误类型：System.Net.Sockets.SocketException
[23:42:22.343] [Download] Thunder.json 2084#：开始，起始点 0，https://piston-meta.mojang.com/v1/packages/ec627769ebe6f149e961832832e954ac18fd069f/24w14potato.json
[23:42:22.410] [Watcher] 新建下载管理卡片：Modrinth 整合包安装：Thunder 
[23:42:22.421] [Animation] 两个动画帧间隔 1015 ms
[23:42:22.441] [Download] Thunder.json 2084#：出错，基础连接已经关闭: 发送时发生错误。
你的网络环境不佳，导致难以连接到服务器。请检查网络，多重试几次，或尝试使用 VPN。

### 重现步骤

1、打开安装mod整合包的界面
2、在版本中填入24w14potato
3、随便选择一个整合包安装，我测试了"Thunder"和"POTATO UPDATE"，版本选择24w14potato
4、下载会报错

（我已确定BakaXL在安装完全相同的整合包时不会出错，且我的网络连接良好，未使用任何VPN，且反复重试无效，且已确定该issue未重复提交）

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15132798/Log1.txt)
我可以确定问题所在的是这个日志，故仅上传该文件。

**Comment by allMagicNB** [comment]
网络问题
