### ISSUE TITLE
在点击更多按钮时，可能会导致左侧功能栏显示异常

### ISSUE THREAD

**Issue by Zwj58** [Hex-Dragon/PCL2#3744]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![屏幕截图 2024-04-27 152231](https://github.com/Hex-Dragon/PCL2/assets/114843425/e8d5ce41-ebcd-415d-aac9-90fa73608c71)

### 重现步骤

1、点击更多按钮

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/15137430/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/15137431/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/15137432/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15137433/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/15137434/Log2.txt)

**Comment by allMagicNB** [comment]
#2982
