### ISSUE TITLE
建议在下载Minecraft的页面添加模组“钠”的下载安装

### ISSUE THREAD

**Issue by WYC-E** [Hex-Dragon/PCL2#3747]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [x] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

建议在下载Minecraft的页面添加模组“钠”的下载安装
![image](https://github.com/Hex-Dragon/PCL2/assets/133771901/34404673-07c7-498a-95ba-eb68150c137b)

### 原因

（示例）
这项优化让我可以更方便地安装钠。
如果没有这项优化，我每次都必须去下载模组的地方安装钠，让操作变得很麻烦。

**Comment by allMagicNB** [comment]
这只是个模组，不至于不至于

**Comment by allMagicNB** [comment]
#2682

**Comment by WYC-E** [comment]
lssue解锁 FA66-6E47-A4E7-19E9
