### ISSUE TITLE
从启动器下载curseforge整合包时，会把材质包安装在mods文件夹内

### ISSUE THREAD

**Issue by ItIsNotAPlayer** [Hex-Dragon/PCL2#375]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

从启动器下载curseforge整合包时，会把材质包安装在mods文件夹内，安装了2次整合包都是这样。未启动过的版本，版本文件夹里貌似没有resourcepacks文件夹。希望在安装整合包时可以把材质包正确地安装在resourcepacks文件夹内。

### 原因

装整合包时要手动把材质包从mods文件夹移动到resourcepacks文件夹内，比较麻烦

**Comment by bwtx2022** [comment]
最好能提交启动器日志

**Comment by LTCatt** [comment]
具体是哪个整合包？

**Comment by ItIsNotAPlayer** [comment]
整合包是Low Res Trailer Recreation

**Comment by ItIsNotAPlayer** [comment]
整合包Promo-Cinematic也有这个问题，把材质包安装到mods文件夹中了，而且相较于用curseforge安装的少了两个材质包

**Comment by ItIsNotAPlayer** [comment]
Low Res Trailer Recreation和Promo-Cinemtic似乎都有这个问题

**Comment by ItIsNotAPlayer** [comment]
82EC-72FD-BF99-00D2

**Comment by LTCatt** [comment]
你的解锁码：n73Zy14pDIQ1l9fXJtlyOADKq6ADzVhY
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
