### ISSUE TITLE
xaml问题，使用纯文本进行打开文件操作报错

### ISSUE THREAD

**Issue by Hatoomu** [Hex-Dragon/PCL2#3750]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在按钮代码下重现没有出现问题，文本套用之后点击将出现如下报错：
![image](https://github.com/Hex-Dragon/PCL2/assets/112040923/9a244414-6742-4918-bf7e-3ac1c8924e6d)

### 重现步骤

1.点击文字弹出普通错误信息
使用到的主页代码：

<local:MyCard Title="标题" Margin="0,0,0,15">
    <StackPanel Margin="0,12,0,10">
    <StackPanel Orientation="Horizontal" HorizontalAlignment="Right" >
				<local:MyButton Margin="0,4,0,10" Width="200" Height="35"
                    Text="打开 PCL 日志" EventType="打开文件" EventData="Log1.txt" ToolTip="PCL 的日志文件就在 PCL 文件夹内，且名为 Log1.txt" />
                <local:MyTextButton Margin="5,0,0,0 " FontSize="24"
					Text="打开 PCL 日志" EventType="打开文件" HorizontalAlignment="Center" EventData="‪Log1.txt" ToolTip="文件位于pcl内" />
                   </StackPanel>
                </StackPanel>
</local:MyCard>

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15137973/Log1.txt)

**Comment by allMagicNB** [comment]
字面意思，就是不存在，日志在程序主体同路径下的 `PCL` 文件夹内，并不是与 PCL 在同一个文件夹，才导致的找不到

**Comment by Hatoomu** [comment]
> 字面意思，就是不存在，日志在程序主体同路径下的 `PCL` 文件夹内，并不是与 PCL 在同一个文件夹，才导致的找不到

这不是路径问题，我添加了可以执行的按键作为参考，对照组已经附带，关于这部分是可以省略的并且成功打开的，它并不是一个路径问题，相关操作步骤log1当中也有记录，当然，它可以被忽略

**Comment by allMagicNB** [comment]
就是路径问题好吗？更换 EventData 为 `PCL\Log1.txt` 顺利解决

**Comment by Hatoomu** [comment]
> 就是路径问题好吗？更换EventData 即可`PCL\Log1.txt`顺利解决

显然你并没有试过，我甚至填写了完整路径

**Comment by Hatoomu** [comment]
> 就是路径问题好吗？更换EventData 即可`PCL\Log1.txt`顺利解决

![image](https://github.com/Hex-Dragon/PCL2/assets/112040923/5040a585-4a37-4fc5-bf97-94a0579ff517)

**Comment by allMagicNB** [comment]
不对，你插个换行啥意思？

**Comment by allMagicNB** [comment]
不是你没事为啥插个换行进去？

**Comment by kong-que-dnf123** [comment]
我的建议是要不我先翻翻文件再说...?

**Comment by wuliaodexiaoluo** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/160083863/4fd98503-10da-4245-a31c-6bc93b7f7a8d)
MyTextButton 我这边是相对路径和绝对路径都不行

@LTCatt 来看下？

**Comment by allMagicNB** [comment]
……？中间明明插了个换行符啊，去掉换行符再补个空格就不报错了

**Comment by allMagicNB** [comment]
@LTCatt

**Comment by wuliaodexiaoluo** [comment]
就很奇怪
我重写了代码的 EventData，发现 MyButton 和 MyTextButton 都不能用相对路径
但问题是程序是在这里启动的，那么操作路径也应该是这个目录，但 .\PCL\log1.txt 和 PCL\log1.txt 都是 Exception
难不成是系统问题？（Win 10 19H9  x86 专业工作站版本）

**Comment by allMagicNB** [comment]
> 就很奇怪
> 我重写了代码的 EventData，发现 MyButton 和 MyTextButton 都不能用相对路径
> 但问题是程序是在这里启动的，那么操作路径也应该是这个目录，但 .\PCL\log1.txt 和 PCL\log1.txt 都是 Exception
> 难不成是系统问题？（Win 10 19H9  x86 专业工作站版本）

发上来文件

**Comment by wuliaodexiaoluo** [comment]
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15158795/Log1.txt)
[Custom.txt](https://github.com/Hex-Dragon/PCL2/files/15158800/Custom.txt)

**Comment by allMagicNB** [comment]
不对，这明明是在与程序同路径下的 `PCL` 文件夹中打开的……
![image](https://github.com/Hex-Dragon/PCL2/assets/116283787/b1f2ca11-3ec2-4d5f-a24f-836487b6747e)

**Comment by Hatoomu** [comment]
> 不对，这明明是在与程序同路径下的 `PCL` 文件夹中打开的…… ![image](https://private-user-images.githubusercontent.com/116283787/327084659-b1f2ca11-3ec2-4d5f-a24f-836487b6747e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2MjM5OTUsIm5iZiI6MTcxNDYyMzY5NSwicGF0aCI6Ii8xMTYyODM3ODcvMzI3MDg0NjU5LWIxZjJjYTExLTNlYzItNGQ1Zi1hMjRmLTgzNjQ4N2I2NzQ3ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMlQwNDIxMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZjMxNTQ3ZGM5NzNlNGM1YTQ0YTgwYzhmMTZhZGUxMzliNGJlMzc1MGUxNTdjYTAzODlmZWM4NTY4YzA4MzVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.H0bMRnhIBvLPvtaymFl4QuWgzjADlt87baHLzRML1_g)

我的问题基本解决了，感谢support，关于路径由于用不了完整路径我用了`...\`进行解决

**Comment by allMagicNB** [comment]
那……关了？

**Comment by JingHai-Lingyun** [comment]
在处理中的反馈…… 不动了吧

**Comment by allMagicNB** [comment]
> 在处理中的反馈…… 不动了吧

问题是这没问题啊

**Comment by wuliaodexiaoluo** [comment]
这个问题。。。。可能专属于 x86_32

**Comment by JingHai-Lingyun** [comment]
@LTCatt 打扰一下过来看看？

**Comment by LTCatt** [comment]
我等到统一修 issue 的时候会来看的……

**Comment by LTCatt** [comment]
没啥问题，我加了个 log 以显示尝试打开的实际路径
