### ISSUE TITLE
建议增加一键更新所有mod的按钮

### ISSUE THREAD

**Issue by hydhydhyd** [Hex-Dragon/PCL2#3752]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在mod管理页面添加一键更新所有mod的按钮

### 原因

这项优化让我可以更方便地批量更新模组。
如果没有这项优化，我需要点击每个mod上非常小的更新按钮，让操作变得很麻烦。

**Comment by youzi-2333** [comment]
不是全选再更新就行了吗……？

**Comment by hydhydhyd** [comment]
> 不是全选再更新就行了吗……？
> 
> ![image](https://private-user-images.githubusercontent.com/106497113/326181738-598c3760-bccf-4cea-a10b-fb37d0f8b515.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyMjU2NjQsIm5iZiI6MTcxNDIyNTM2NCwicGF0aCI6Ii8xMDY0OTcxMTMvMzI2MTgxNzM4LTU5OGMzNzYwLWJjY2YtNGNlYS1hMTBiLWZiMzdkMGY4YjUxNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyN1QxMzQyNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNmMwNTRiZmY5MDQzYWZhZjMwYTMyMmNlZmI1ZTIwZDIyYTBmMjZjMjI3NDU5YzgzYmE4MjI1ZWExOTFmNmE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bHrXYtjtAtKvxF7tClp68d_T0iVk7qeVVBwOQOGkuOA)

我是傻逼
