### ISSUE TITLE
在升级 Mod 后禁用旧版本 Mod 而不是删除

### ISSUE THREAD

**Issue by allMagicNB** [Hex-Dragon/PCL2#3754]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在升级某个或某些 Mod 后，不删除旧版本 Mod，而是将它禁用。

### 原因

目前版本更新 Mod 功能还不太稳定，而且此举动也可以给那些乱更新最后给游戏搞崩了的小白一个后路。

**Comment by LTCatt** [comment]
放回收站了，禁用更新多了满屏禁用更头疼
