### ISSUE TITLE
Minecraft 崩溃

### ISSUE THREAD

**Issue by andy33bb** [Hex-Dragon/PCL2#3755]
### 检查项

- [ ] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃基本不是 PCL 的原因，请 **不要** 提交反馈。你可以在论坛或社区找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用 HMCL 启动，HMCL 没有出现问题。** 如果 HMCL 也无法启动就不是 PCL 导致的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

无法启动 版本隔离和java都没有问题 并且我的朋友们进行了测试而且可以启动 但是我无法启动

### PCL 错误报告、日志与附件

[错误报告-2024-4-28_14.44.38.zip](https://github.com/Hex-Dragon/PCL2/files/15141148/-2024-4-28_14.44.38.zip)

**Comment by JingHai-Lingyun** [comment]
```
[14:44:35] [main/INFO]: [org.lwjgl.system.Library:printError:424]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[14:44:35] [main/INFO]: [org.lwjgl.system.Library:printError:426]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[14:44:35] [main/INFO]: [org.lwjgl.system.Library:printError:428]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
```

你的 LWJGL 找不到一个动态库了……

**Comment by zkitefly** [comment]
在 控制面板 -- 时钟和区域 -- 区域 -- 管理 -- 更改系统区域设置 里面上面选「中文（简体，中国）」，并且把下面那个勾去掉 https://img.kookapp.cn/assets/2023-03/zsLRF3LrcD0we0hj.png

**Comment by andy33bb** [comment]
> ```
> [14:44:35] [main/INFO]: [org.lwjgl.system.Library:printError:424]: [LWJGL] Failed to load a library. Possible solutions:
> 	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
> 	b) Add the JAR that contains the shared library to the classpath.
> [14:44:35] [main/INFO]: [org.lwjgl.system.Library:printError:426]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
> [14:44:35] [main/INFO]: [org.lwjgl.system.Library:printError:428]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
> ```
> 
> 你的 LWJGL 找到了一个动态库了……

请问这个问题我该怎么解决呢

**Comment by andy33bb** [comment]
> 在 控制面板 -- 时钟和区域 -- 区域 -- 管理 -- 更改系统区域设置 里面上面选「中文（简体，中国）」，并且把下面那个勾去掉 https://img.kookapp.cn/assets/2023-03/zsLRF3LrcD0we0hj.png
> 
> 如果不行，就把路径改成全英文的，不要有中文

问题解决了 真的十分感谢大佬的帮助！
