### ISSUE TITLE
程序出现未知错误：无法找到指定文件

### ISSUE THREAD

**Issue by ED-no-tear** [Hex-Dragon/PCL2#3756]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

打不开PCL+报错

### 重现步骤

不是很清楚，之前还好好的
突然就打不开了
<img width="317" alt="屏幕截图 2024-04-28 190817" src="https://github.com/Hex-Dragon/PCL2/assets/142851855/802c4c68-33f6-4706-a57d-341dddf49129">

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15141521/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/15141524/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/15141525/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/15141527/Log4.txt)

[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/15141528/Log5.txt)

**Comment by zkitefly** [comment]
https://github.com/Hex-Dragon/PCL2/issues/2993 ？

**Comment by JingHai-Lingyun** [comment]
无法从日志中找到任何有用信息，这通常不是 PCL 的问题……

**Comment by mc-124** [comment]
无法确定为什么报错，因为错误发生在ModSecret.vb，这个文件没有开源……只能找龙猫来看看了

**Comment by allMagicNB** [comment]
#2885？

**Comment by mc-124** [comment]
@ED-no-tear 你近期有没有删除什么文件夹？

**Comment by wuliaodexiaoluo** [comment]
@LTCatt

**Comment by LTCatt** [comment]
从 #2885 和 #2993 看这个问题一般不是 PCL 导致的……看反馈者有没有删啥吧

**Comment by ED-no-tear** [comment]
重启就修好了（（（（
