### ISSUE TITLE
下载forge时报错

### ISSUE THREAD

**Issue by mouyu15** [Hex-Dragon/PCL2#3757]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

下载整合包时一切正常,直到下载forge时无法下载

### 重现步骤

搜索Cisco's Fantasy Medieval RPG [Ultimate]
下载任何版本

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15141655/Log1.txt)

**Comment by dargoncat** [comment]
[10:34:25.962] [Start] 程序版本：Release 2.6.1（293）
请**更新至最新版**后重试

**Comment by JingHai-Lingyun** [comment]
我这边没有问题，请更新你的 PCL 启动器，然后再次尝试

**Comment by wuliaodexiaoluo** [comment]
没找到任何一个与之匹配的 Issue
可能是个新 Bug，但这边无法复现

**Comment by dargoncat** [comment]
> 没找到任何一个与之匹配的 Issue 可能是个新 Bug，但这边无法复现 建议检查下 Java

```
[10:34:25.962] [Start] 程序版本：Release 2.6.1（293）
```
人家没更新。。。现在是2.7.1

**Comment by allMagicNB** [comment]
#3462

**Comment by allMagicNB** [comment]
在此期间修了很多无法安装 Forge 的 Bug，估计更新下就好了……
如果更新后还是没好的话，请补充新的日志文件（最好开下调试模式）。

**Comment by wuliaodexiaoluo** [comment]
> 人家没更新。。。现在是2.7.1

```
Caused by: java.lang.IllegalArgumentException: argument type mismatch
```
虽然但是你见过哪个 Issue 修复过这个类型的错误？

**Comment by dargoncat** [comment]
> > 人家没更新。。。现在是2.7.1
> 
> ```
> Caused by: java.lang.IllegalArgumentException: argument type mismatch
> ```
> 
> 虽然但是你见过哪个 Issue 修复过这个类型的错误？

你是真不看上面collaborator的回复啊。。。 #3462

**Comment by wuliaodexiaoluo** [comment]
认真看了下 3642 日志
```
Caused by: java.lang.IllegalArgumentException: argument type mismatch
````
确定是 #3462
@allMagicNB 打重复标签
