### ISSUE TITLE
安装1.20.4-Forge_49.0.49-optifine卡881.53%

### ISSUE THREAD

**Issue by hesongkai-0** [Hex-Dragon/PCL2#3758]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

安装卡住为78.53%

### 重现步骤

安装1.20.4-Forge_49.0.49-optifine

### 日志与附件

[PCL.zip](https://github.com/Hex-Dragon/PCL2/files/15141923/PCL.zip)

**Comment by allMagicNB** [comment]
你先别急，卡一个小时再来反馈

**Comment by hesongkai-0** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/162005289/c6c996e7-e9de-4e3c-89ed-ef00c7a34a57)

**Comment by hesongkai-0** [comment]
已经卡一个小时没动静

**Comment by allMagicNB** [comment]
别叫，日志有记录时间的

**Comment by JingHai-Lingyun** [comment]
尝试用最新版的 PCL 再进行一次安装，然后如果卡住了发一下最新的日志？

**Comment by allMagicNB** [comment]
> 尝试用最新版的 PCL 再进行一次安装，然后如果卡住了发一下最新的日志？
> 
> ---
> 
> >别叫
> 
> 友好交流，谢谢

```
[19:22:40.066] [Start] 程序版本：Snapshot 2.7.1（320）
```
你要不要看看你在说什么

**Comment by mc-124** [comment]
optifine installer无响应？感觉会被打第三方

**Comment by hesongkai-0** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/162005289/db6182c0-7101-44b5-8c00-382dabec73cb)

**Comment by JingHai-Lingyun** [comment]
我感觉是网络的问题然后下载到的 Installer 不全导致的

**Comment by mc-124** [comment]
> 我感觉是网络的问题然后下载到的 Installer 不全导致的

下载不全的话JVM是没法打开的吧

**Comment by JingHai-Lingyun** [comment]
也有可能……

**Comment by allMagicNB** [comment]
你有没有打开 `关闭文件校验` 选项？

**Comment by Deep-Dark-Forest** [comment]
考虑改一下标题？

**Comment by wuliaodexiaoluo** [comment]
此为部分 BMCLAPI 节点没有断点续传导致 OpriFine 不全导致的
~那么大一个 ZipFile Invaild LOC Header 为什么不关掉~

**Comment by wuliaodexiaoluo** [comment]
#3657

**Comment by wuliaodexiaoluo** [comment]
>下载不全的话JVM是没法打开的吧
OF自身问题？

那个 Error 不就是打不开了。。。
广义上的打不开是指用不了，Error 是包括在内的

**Comment by hesongkai-0** [comment]
确实，而且我非常确定OF是目前是完整的
他可以下载，而且能进行运行，他只是报错,他的报错内容在我上一张的图片里

**Comment by hesongkai-0** [comment]
而且我用的是官方源

**Comment by wuliaodexiaoluo** [comment]
>确实，而且我非常确定OF是目前是完整的
他可以下载，而且能进行运行，他只是报错,他的报错内容在我上一张的图片里

那不是 OptiFine 运行了，那是 Fabric 报错了

>而且我用的是官方源

PCL 还没有自定义下载源的选项，那个是加载版本列表的选择

**Comment by allMagicNB** [comment]
所以，你有没有打开 `关闭文件校验`？

**Comment by wuliaodexiaoluo** [comment]
> 所以，你有没有打开 `关闭文件校验`？

安装还能关闭文件校验？？？

**Comment by allMagicNB** [comment]
> > 所以，你有没有打开 `关闭文件校验`？
> 
> 安装还能关闭文件校验？？？

他这是大概率是下载不完整导致的

**Comment by wuliaodexiaoluo** [comment]
93哥那边还没修好？
如果是的话
https://github.com/Hex-Dragon/PCL2/issues/3657#issuecomment-2053746442

**Comment by wuliaodexiaoluo** [comment]
@JingHai-Lingyun 给你发了封邮件你看看
你发过去的邮件被当垃圾邮件，Outlook 的 Web 版本搜不到垃圾，要不是我用 EdgeHTML 登录旧版本 Outlook 我估计也看不到

**Comment by LTCatt** [comment]
是 #3657，要等到下一个版本更新后才能定位问题
