### ISSUE TITLE
下载自定义文件这个功能的bug

### ISSUE THREAD

**Issue by xhyyd2022** [Hex-Dragon/PCL2#3759]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

多次下载从一个超过缓存的文件会下载一个文件名相同的随机大小的文件并且从每一个链接下载下来软件大小一直是相同的目前个人测试300~500个字节

### 重现步骤

在下载自定义文件当中重复尝试两到三次下载同一个超过缓存大小的文件

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15143174/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/15143175/Log2.txt)

**Comment by wuliaodexiaoluo** [comment]
多线程不就是文件碎片么。。。。
