### ISSUE TITLE
点击新版本更新提示的下载导致PCL崩溃

### ISSUE THREAD

**Issue by jhqwqmc** [Hex-Dragon/PCL2#3761]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

见标题

### 重现步骤

1、打开pcl，等待更新提示弹出
2、点击下载

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15151158/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/15151161/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/15151162/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/15151164/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/15151153/Log5.txt)

**Comment by allMagicNB** [comment]
#3742

**Comment by JingHai-Lingyun** [comment]
草啦，忘了查重了
