### ISSUE TITLE
mc1.20.4~1.20.6进入不了服务器

### ISSUE THREAD

**Issue by uddqerw** [Hex-Dragon/PCL2#3762]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

进入不了服务器

### 重现步骤

1.启动游戏
2.点击多人游戏
3.点击添加服务器
4.输入服务器地址
5.点击连接

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15158680/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/15158682/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/15158683/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/15158684/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/15158685/Log5.txt)

**Comment by allMagicNB** [comment]
？发个截屏

**Comment by allMagicNB** [comment]
一般此类问题往往不是 PCL 的问题，而是你自身网络环境和服务器的问题……

**Comment by uddqerw** [comment]
![mc](https://github.com/Hex-Dragon/PCL2/assets/168087725/22e385de-5232-4f86-a54f-631f376a8dc4)

**Comment by allMagicNB** [comment]
字面意思

**Comment by JingHai-Lingyun** [comment]
请确认你是否以正版登录启动游戏，如果是，请重新启动 PCL 启动器和你的 Miencraft 客户端
此服务器仅限正版登录加入

**Comment by wuliaodexiaoluo** [comment]
请检查是否使用服务器要求的登录方式登录服务器

**Comment by uddqerw** [comment]
那是我用spigot构建的服务器，我不知道他的登录方式啊

**Comment by JingHai-Lingyun** [comment]
你自己的服务器？那默认为正版登录模式
想要切换到离线登录模式：
1. 找到 server.properties 文件
2. 修改 online-mode 为 false
3. 重启服务器

**Comment by wuliaodexiaoluo** [comment]
> > 请检查是否使用服务器要求的登录方式登录服务器
> 
> 先别下结论好吗？还有可能是 AccessToken 过期了。

AccessToken 不是每次 PCL 启动都刷一遍有效期长达 1 day 么

**Comment by allMagicNB** [comment]
> > > 请检查是否使用服务器要求的登录方式登录服务器
> > 
> > 
> > 先别下结论好吗？还有可能是 AccessToken 过期了。
> 
> AccessToken 不是每次 PCL 启动都刷一遍有效期长达 1 day 么

我期间要是不关闭 PCL，直接让电脑睡眠呢？

**Comment by wuliaodexiaoluo** [comment]
谁家好人睡眠一整天啊！！！！
