### ISSUE TITLE
添加NeoForge的自动安装功能

### ISSUE THREAD

**Issue by Ro1GYzL** [Hex-Dragon/PCL2#3765]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

像Forge和Fabric一样可以自动安装NeoForge

### 原因

因为Forge停止更新了，新版本的虚无世界只能使用NeoForge，以后很多人会用到

**Comment by JingHai-Lingyun** [comment]
#2244

**Comment by wuliaodexiaoluo** [comment]
> 因为Forge停止更新了

首先，重了
其次，谁告诉你 Forge 停止更新啊喂！
https://github.com/Hex-Dragon/PCL2/issues/2244#issuecomment-2034484005
