### ISSUE TITLE
安装Optifine出现错误的概率性问题

### ISSUE THREAD

**Issue by BeiChenP** [Hex-Dragon/PCL2#3770]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

安装游戏的Optifine时，会卡在6%，然后有概率出现错误

### 重现步骤

1、选1.18.x任意版本
2、安装版本（要安装Optifine）
3、Optifine安装会卡在6%，只需要等待

### 日志与附件

下载 OptiFine 1.18.2 H9失败
→ 安装 OptiFine（方式 A）失败
→ 运行 OptiFine 安装器失败
→ 安装器运行出错，末行为 错误: 找不到或无法加载主类 optifine.Installer
   在 PCL.ModDownloadLib._Closure$__18-0._Lambda$__5(LoaderTask`2 Task)
   在 PCL.ModLoader.LoaderTask`2._Closure$__13-0._Lambda$__0()
   在 PCL.ModDownloadLib._Closure$__18-0._Lambda$__5(LoaderTask`2 Task)
   在 PCL.ModDownloadLib.McDownloadOptiFineInstall(String BaseMcFolderHome, String Target, LoaderTask`2 Task, Boolean UseJavaWrapper)
   在 PCL.ModDownloadLib._Closure$__18-0._Lambda$__5(LoaderTask`2 Task)

**Comment by allMagicNB** [comment]
#3657
