### ISSUE TITLE
下载大量mod时提示获取任务栏进度出错

### ISSUE THREAD

**Issue by Casper233** [Hex-Dragon/PCL2#3771]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

获取任务栏进度出错：集合已修改；可能无法执行枚举操作。
   在 System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   在 System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   在 System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   在 PCL.ModNet.LoaderDownload.get_Progress()
   在 PCL.ModLoader.LoaderCombo`1.get_Progress()
   在 PCL.ModLoader.LoaderTaskbarProgressGet()
错误类型：System.InvalidOperationException

### 重现步骤

1、在下载多个mod时再下载mod可能会出现（？怪

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15176997/Log1.txt)
注：在2309行

**Comment by allMagicNB** [comment]
感觉有点偏手动触发了……

**Comment by Casper233** [comment]
阿巴阿巴
我来请求下“活跃橙”啦
thanks

**Comment by LTCatt** [comment]
你的解锁码：835sflvzVBFGwoD3VF2/+XYiD1j3KAKC
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by Casper233** [comment]
好嘞
谢谢~

**Comment by lactobionicAcid** [comment]
快照版 2.8.9 版本复现。
[Log1.txt](https://github.com/user-attachments/files/17479315/Log1.txt)

**Comment by WorldHim** [comment]
于快照版 2.8.10 复现。
[Log1.txt](https://github.com/user-attachments/files/17878767/Log1.txt)
Ln 981 - 997
```
[14:36:59.145] 获取任务栏进度出错：集合已修改；可能无法执行枚举操作。
   在 System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   在 System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   在 System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   在 PCL.ModNet.LoaderDownload.get_Progress()
   在 PCL.ModLoader.LoaderCombo`1.get_Progress()
   在 System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   在 System.Linq.Enumerable.Average(IEnumerable`1 source)
   在 PCL.ModLoader.LoaderTaskbarProgressGet()
错误类型：System.InvalidOperationException
[14:36:59.152] [Mod] 等待 Mod 更新完成后才能继续加载 Mod 列表：E:\Minecraft\Client\Purpur\.minecraft\versions\1.18.2-Forge_40.2.21\mods\
[14:36:59.165] [Control] 普通弹窗：出现错误
获取任务栏进度出错：集合已修改；可能无法执行枚举操作。
   在 PCL.ModNet.LoaderDownload.get_Progress()
   在 PCL.ModLoader.LoaderCombo`1.get_Progress()
   在 PCL.ModLoader.LoaderTaskbarProgressGet()
错误类型：System.InvalidOperationException
```
