### ISSUE TITLE
支持一些老旧Modloader的支持

### ISSUE THREAD

**Issue by lienting885** [Hex-Dragon/PCL2#3772]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

请添加一些对于老旧整合包和老旧Modloader的支持(如MITE使用的CoreMod)。PCL2会把这些游戏版本错误的识别为原版游戏，导致游戏可能无法运行。

### 原因

（示例）
我需要这个功能来支持对MITE的支持。很多人都有游玩老旧整合包的需求，但如果没有这个功能，就不能识别老旧整合包了。

**Comment by JingHai-Lingyun** [comment]
请说明是什么 ModLoader
另，对于 Clearroom 请见 #3003

**Comment by lienting885** [comment]
MITE(Minecraft Is Too Easy)使用的就是非常古老的CoreMod(详见http://xfl03.gitee.io/coremodtutor/1.1.html)

**Comment by lienting885** [comment]
Fabric,Forge均为ModLoader

**Comment by hejiehao** [comment]
他应该想问“是什么 ModLoader”，而不是“什么是 ModLoader”

**Comment by lienting885** [comment]
MITE使用的就是CoreMod(详见https://xfl03.gitbook.io/coremodtutor及https://github.com/xfl03/CoreModTutor)

**Comment by hejiehao** [comment]
装个 Forge

**Comment by lienting885** [comment]
不是,我的意思是一些整合包PCL2识别不了,装Forge干嘛

**Comment by hejiehao** [comment]
发一下整合包

**Comment by lienting885** [comment]
比如MITE振金(文件太大上传不了）

**Comment by hejiehao** [comment]
发网盘

**Comment by lienting885** [comment]
https://wwk.lanzoup.com/iflL11xbneeh

**Comment by lienting885** [comment]
https://wwk.lanzoup.com/iflL11xbneeh

**Comment by allMagicNB** [comment]
那些玩意基本没啥人用……

**Comment by LTCatt** [comment]
抱歉，PCL 不再考虑对 1.11 之前的版本进行额外支持工作 Orz
