### ISSUE TITLE
怀疑pcl2会自己删除自己

### ISSUE THREAD

**Issue by WYC-E** [Hex-Dragon/PCL2#3775]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

怀疑pcl2会自己删除自己
pcl2的.exe程序有时会突然消失
pcl2也在白名单里
![image](https://github.com/Hex-Dragon/PCL2/assets/133771901/0c3bda3b-28ca-4488-99d6-e07d2072a3e9)
![image](https://github.com/Hex-Dragon/PCL2/assets/133771901/56cd6e62-e206-43b8-abbf-6e5d9ce55676)
已经出现了好多次了，最近一次实在2024,05,02
但是杀毒软件日志里也没有记录
![image](https://github.com/Hex-Dragon/PCL2/assets/133771901/30cfc07b-5300-48d8-a8b5-a4fe886bfd17)
![image](https://github.com/Hex-Dragon/PCL2/assets/133771901/d3210431-8da1-4c5b-a206-96e009a72119)
![image](https://github.com/Hex-Dragon/PCL2/assets/133771901/44e9034f-159c-4ad2-afdf-a5e03ae3f207)

### 重现步骤

咱不知道如何触发的
有时pcl2本体就会突然消失

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/15188649/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/15188650/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/15188651/Log5.txt)
[Log.txt](https://github.com/Hex-Dragon/PCL2/files/15188653/Log.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15188655/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/15188656/Log2.txt)

**Comment by WYC-E** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/133771901/6a3a476d-9b3f-48ac-8f66-27a0f1a56490)
它压根就没开啊

**Comment by JingHai-Lingyun** [comment]
即使 Windows Defender 没有开，也仍然有可能直接（静默）删除启动器。
请参见 #56 #666 或 PCL 内置帮助库

**Comment by wuliaodexiaoluo** [comment]
你信微软会断扫描不如信明天世界末日

**Comment by iPodtouch6557** [comment]
![IMG_9825](https://github.com/Hex-Dragon/PCL2/assets/118656946/32334d50-2400-445b-ac94-b42cc38ef37b)
![IMG_9824](https://github.com/Hex-Dragon/PCL2/assets/118656946/5980ba84-696f-4b41-8d6c-3b7432d86901)
![IMG_9824](https://github.com/Hex-Dragon/PCL2/assets/118656946/36ef1df5-aa86-4ffc-a9ea-9519e1eed91a)
