### ISSUE TITLE
mod更新BUG

### ISSUE THREAD

**Issue by Ilovepcl2** [Hex-Dragon/PCL2#3777]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

1.20.1的geckolib4.2.3版本更新后变成security breach objects, blocks & more的1.06beta版本

### 重现步骤

1、更新geckolib4.2.3
2、更新后名称虽然是geckolib4.4.4但mod管理显示的是security breach objects, blocks & more的1.06beta版本

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15197801/Log1.txt)

**Comment by JingHai-Lingyun** [comment]
#3725
