### ISSUE TITLE
连续启动、取消启动游戏会导致PCL崩溃

### ISSUE THREAD

**Issue by TheMyceliumOfAntan** [Hex-Dragon/PCL2#3778]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

连续启动游戏(到等待游戏窗口出现步骤)后取消启动游戏会导致PCL崩溃

### 重现步骤

1、点击启动游戏
2、当到等待游戏窗口出现步骤时取消启动
3、切换版本
4、重新启动游戏
5、重复几次后PCL崩溃

https://github.com/Hex-Dragon/PCL2/assets/104728663/01b13285-1c5d-47e5-af96-a252255770a4

### 日志与附件

（不知道为啥日志传不上来就丢蓝奏了）
https://wwi.lanzoup.com/iFwXI1xjwgcj

**Comment by Ad-closeNN** [comment]
感觉是360的问题，把PCL误判了 
关掉360再复现试试？

**Comment by allMagicNB** [comment]
有人能复现吗？

**Comment by mc-124** [comment]
大概率是360识别到游戏然后搞什么内存清理把PCL2误杀了。视频中游戏已经加载进内存后被360发现，然后360清理内存，PCL2进程被杀死

**Comment by JingHai-Lingyun** [comment]
尝试把 360 关掉后再次启动试试看，这应该不是 PCL 的问题

**Comment by SALTWOOD** [comment]
尝试把360关掉，如果还是有这样的问题，确保其他机器能复现。要是也能基本是因为快速点击导致，这种龙猫不管；要是不能复现龙猫可能会来看看

**Comment by wuliaodexiaoluo** [comment]
```
[19:02:02.633] [Java] 排序后的 Java 优先顺序：
[19:02:02.633] [Java]  - JDK 18 (18.0.0)，64 位，手动导入：J:\Program Files\Java\jdk-18\bin\
[19:02:02.633] [Java]  - JDK 17 (17.0.3)，64 位：C:\Users\tmoam\AppData\Roaming\.minecraft\runtime\java-runtime-gamma\bin\
[19:02:02.633] [Java]  - JDK 17 (17.0.3)，64 位：C:\Users\tmoam\AppData\Roaming\LabyMod\runtime\java-runtime-gamma\bin\
[19:02:02.633] [System] 执行外部命令并等待返回结果：J:\Program Files\Java\jdk-18\bin\java.exe -version
```

这没有报错，日志到这里戛然而止，我认为是有程序终止了 PCL

**Comment by WForst-Breeze** [comment]
```
[14:44:57.285] [Control] 普通弹窗：提示
若在游戏启动后立即关闭启动器，崩溃检测、更改游戏标题等功能将失效。
如果想保留这些功能，可以选择让启动器在游戏启动后隐藏，游戏退出后自动关闭。
```

作者将启动器可见性设置为了 “游戏启动后立即关闭”

**Comment by Ad-closeNN** [comment]
> ```
> [14:44:57.285] [Control] 普通弹窗：提示
> 若在游戏启动后立即关闭启动器，崩溃检测、更改游戏标题等功能将失效。
> 如果想保留这些功能，可以选择让启动器在游戏启动后隐藏，游戏退出后自动关闭。
> ```
> 
> 作者将启动器可见性设置为了 “游戏启动后立即关闭”

Author不看提示就确认？不太可能...

**Comment by allMagicNB** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/116283787/7207642f-d113-4ace-9574-f3bbbf2c1255)

**Comment by LTCatt** [comment]
考虑视频里的情况应该是 360 加速球干的……
如果没有其他证据说明不是它干的那就不处理 =。=
