### ISSUE TITLE
下载时顺带解决 Minecraft 1.13以下，1.7.10以上版本无声 问题

### ISSUE THREAD

**Issue by Hamster-github** [Hex-Dragon/PCL2#3779]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

考虑下载1.13以下，1.7.10以上版本时进行操作，若为64位版JAVA，将1.13以上版本的64位OpenAL.dll粘贴到版本文件夹并改名为OpenAL64.dll；若为32位版JAVA，将1.13以上版本的32位OpenAL.dll粘贴到版本文件夹并改名为OpenAL32.dll。如此可以解决部分音量合成器中无Minecraft导致的无声问题(此问题在我打1.8.9PVP时发现，经测试，发现问题波及到了1.12.2，两个主要版本，不可忽略)[参考](https://www.bilibili.com/read/cv19271520/)(问题并非100%触发)

### 原因

我需要这个功能来解决 Minecraft 1.13以下，1.7.10以上版本无声 问题。很多人都有打1.8.9PVP\玩1.12.2的需求，但如果没有这个功能，就不能在问题发作时，在1.13以下，1.7.10以上版本中听到声音了。

**Comment by wuliaodexiaoluo** [comment]
高版本 OpenAL 在低版本 Minecraft 使用可能会导致兼容性问题，龙猫应该不会考虑

**Comment by wuliaodexiaoluo** [comment]
> 高版本 OpenAL 在低版本 Minecraft 使用可能会导致兼容性问题，龙猫应该不会考虑

这个 Bug 应该反馈到 Mojang 那边，而不是反馈到 PCL 这边处理

**Comment by wuliaodexiaoluo** [comment]
Mojang BugTracker 已受理此问题
详见 https://bugs.mojang.com/browse/MC-9974
此为 OpenAL 在初始化过程中失败
请在游戏启动后按下 F3+T 来重新初始化 OpenAL
这个问题会被反馈到 1930 要求添加，感谢反馈

**Comment by JingHai-Lingyun** [comment]
1. 强制修改 OpenAL 组件可能导致兼容性问题
2. 参见 Mojang BugTracker https://bugs.mojang.com/browse/MC-9974
![image](https://github.com/Hex-Dragon/PCL2/assets/109946426/4f659b0d-585f-4181-ab17-60203b1dc9b6)
你始终可以通过游戏内按下 `F3+T` 来解决

并且受影响的版本均为较早期版本，综合来看，先关了。感谢反馈
