### ISSUE TITLE
[BUG]加载自定义主页失败：向类型为"System.Windows.Controls.UIElementCollection"的集合中添加值引发了异常。

### ISSUE THREAD

**Issue by SuoHouDaiShi** [Hex-Dragon/PCL2#3783]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![图片](https://github.com/Hex-Dragon/PCL2/assets/119282947/653bc43a-dc7c-4cb2-ade9-7d1ecb88c0fd)
怎么说（

### 重现步骤

1.编写一个标准的 Xaml 主页布局
2.在主页布局的任意位置输入`&`这个字符并保存
3.重载主页，出现第一次报错：
![BHW4(Z674Z$ JNGRZ WNVX4](https://github.com/Hex-Dragon/PCL2/assets/119282947/ece10335-72ae-42f1-8a88-5babe0c3f1f1)
4.去掉`&`这个字符并保存
5.重载主页，出现此报错：
![I9C31{CX)TMAG`DXXMV}Q I](https://github.com/Hex-Dragon/PCL2/assets/119282947/8d237839-c73f-427c-93ee-3aa0b8932233)

### 日志与附件

PCL 日志：
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15209140/Log1.txt)

**Comment by allMagicNB** [comment]
发主页文件

**Comment by SuoHouDaiShi** [comment]
> 发主页文件

《我们不支持此类文件，请尝试打包成 *.zip 后重试》

而且日志里有 Xaml 的源文件啊……

**Comment by allMagicNB** [comment]
你改后缀名不得了

**Comment by SuoHouDaiShi** [comment]
> 你改后缀名不得了

不是哥们，你直接看 Log1.txt 里（559 行开始至 612 行）的不就行了？而且改后缀名会损坏文件头……
![S }L{QX5VURBK%QUQ`UJD W](https://github.com/Hex-Dragon/PCL2/assets/119282947/9947072b-8bc6-439a-84fa-4291cf9fbcd2)

**Comment by allMagicNB** [comment]
这原本就是串文本，后缀名只是用来识别类型的，不存在什么损坏。

**Comment by SuoHouDaiShi** [comment]
[扣1复活牢大（Xaml 文件）.zip](https://github.com/Hex-Dragon/PCL2/files/15209160/1.Xaml.zip)

**Comment by SuoHouDaiShi** [comment]
ok我的问题 查了

**Comment by wuliaodexiaoluo** [comment]
多了个点

**Comment by SuoHouDaiShi** [comment]
确实 我看到了（
