### ISSUE TITLE
Timeless and Classics Guns 时没有显示前置模组

### ISSUE THREAD

**Issue by qwertyuioi114514** [Hex-Dragon/PCL2#3790]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![EA1EBF16BEAD2DFBF4A0B364BF56193D](https://github.com/Hex-Dragon/PCL2/assets/168945453/36cbc50b-030d-40dd-987f-b26d81b99e45)
如图，它没有显示任何前置模组

### 重现步骤

1、点击下载，输入Timeless and Classics Guns 点击
2、你会发现只有版本，没有前置mod!

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15211567/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/15211568/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/15211569/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/15211570/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/15211571/Log5.txt)

**Comment by Ad-closeNN** [comment]
?
![image](https://github.com/Hex-Dragon/PCL2/assets/103355026/75c0bf8b-eda9-4be9-a283-5b4bb2924372)

**Comment by allMagicNB** [comment]
![Screenshot_20240505_103458_com.microsoft.emmx.jpg](https://github.com/Hex-Dragon/PCL2/assets/116283787/6bc32e90-16e2-4224-8528-ac86b70b7c6b)

**Comment by allMagicNB** [comment]
这应该是作者都没填导致的

**Comment by Ad-closeNN** [comment]
> 这应该是作者都没填导致的

不太可能。为什么我能加载出来

**Comment by WForst-Breeze** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/110760354/a3e01528-150f-4849-8822-34c13ed78e8f)

请检查你的网络环境

**Comment by Ad-closeNN** [comment]
先上label`等待反馈着`吧

**Comment by LBZiXL** [comment]
![PixPin_2024-05-05_13-05-18](https://github.com/Hex-Dragon/PCL2/assets/115980764/8bc7d15c-2fda-48df-a1fe-f3e982557b86)
因该是你网络原因，我这都能加载出来

**Comment by wuwenjun9939** [comment]
绝对是你网络问题
![image](https://github.com/Hex-Dragon/PCL2/assets/110022109/fd57d7cc-8fd7-46e9-ae9a-64ed02dfec69)

**Comment by hejiehao** [comment]
Log2.txt L322
```
[09:12:28.211] [Comp] 491264 文件列表中还需要获取信息的前置 Mod：289380，549225
```

**Comment by LTCatt** [comment]
估计是网络问题，没人能复现，反馈者也不回，先关了
