### ISSUE TITLE
[Bug] 加载 Minecraft 版本列表失败：索引超出范围。必须为非负值并小于集合大小。

### ISSUE THREAD

**Issue by wuliaodexiaoluo** [Hex-Dragon/PCL2#3791]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

弹出报错

### 重现步骤

不知道怎么复现的，可能是在离开某个页面后快速点击另一个页面

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15211865/Log1.txt)
![ee50f8b7861bfb1cc24def7d6b545343](https://github.com/Hex-Dragon/PCL2/assets/160083863/2e0aae7b-c401-4637-91ed-13a106f8c2e9)

**Comment by allMagicNB** [comment]
需要复现方式

**Comment by wuliaodexiaoluo** [comment]
关键是我也不知道我咋复现的，我就是下个版本然后戳进版本列表然后就炸了

**Comment by wuliaodexiaoluo** [comment]
坏了，要变成 #2196 了

**Comment by JingHai-Lingyun** [comment]
22204 行
```
[13:47:42.718] 加载 .minecraft 版本列表失败：索引超出范围。必须为非负值并小于集合大小。
参数名: index
   在 System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   在 PCL.ModMinecraft.McVersionListLoad(LoaderTask`2 Loader)
错误类型：System.ArgumentOutOfRangeException
```
从日志上来看不是 2196

**Comment by wuliaodexiaoluo** [comment]
> 22204 行（~怎么日志这么长啊~）
> 
> ```
> [13:47:42.718] 加载 .minecraft 版本列表失败：索引超出范围。必须为非负值并小于集合大小。
> 参数名: index
>    在 System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
>    在 PCL.ModMinecraft.McVersionListLoad(LoaderTask`2 Loader)
> 错误类型：System.ArgumentOutOfRangeException
> ```
> 
> 从日志上来看不是 2196

问 zk ，zk 知道我昨天在你不在的时候都干了什么
~我指的是如果没人复现就只能和 #2196 一样成为 PCL 的未解之谜了~

**Comment by LTCatt** [comment]
因为没法复现进行了一点盲修，如果之后又出现了再说
