### ISSUE TITLE
[Bug] 勾选关闭文件校验后 PCL 仍会尝试补全 Libraries ，即使文件存在于文件夹下且文件名称与修改前完全相同

### ISSUE THREAD

**Issue by wuliaodexiaoluo** [Hex-Dragon/PCL2#3792]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

勾选关闭文件校验后 PCL 仍会尝试补全 Libraries

### 重现步骤

替换掉 Libraries 内的 OptiFine，PCL 依旧会尝试补全文件

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15212225/Log1.txt)

**Comment by allMagicNB** [comment]
这是文件校验的人设置，而不是补全的设置。

**Comment by wuliaodexiaoluo** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/160083863/bb77b148-047f-4cc8-bb2d-7f107926772c)
提示上写了不校验文件是否修改，如果还是补全请问那修改的意义何在

**Comment by Ad-closeNN** [comment]
~~不校验≠不补全~~

**Comment by allMagicNB** [comment]
检查文件是否存在≠校验已有的文件是否一致。

**Comment by wuliaodexiaoluo** [comment]
评价：所以不校验的逻辑是什么？文件大小与文件 hash 与未修改前的文件完全一致？这怎么可能？

**Comment by allMagicNB** [comment]
你这都不是修改了，直接给删了

**Comment by allMagicNB** [comment]
> 评价：所以不校验的逻辑是什么？文件大小与文件 hash 与未修改前的文件完全一致？这怎么可能？

怎么不可能？你以为这些信息差不到？

**Comment by wuliaodexiaoluo** [comment]
> > 评价：所以不校验的逻辑是什么？文件大小与文件 hash 与未修改前的文件完全一致？这怎么可能？
> 
> 怎么不可能？你以为这些信息差不到？

完全一致：与 json 提供的大小和 hash 一致，已知在不借助外部因素的情况下修改文件 hash 一定会变化

**Comment by LTCatt** [comment]
呃，你这个 log 有一万多行，实在找不过来，具体是哪个文件被替换了？

**Comment by wuliaodexiaoluo** [comment]
optifine 和 launchwapper-of

**Comment by wuliaodexiaoluo** [comment]
猫，你改动标签前先慎重考虑下，会炸邮箱的（

**Comment by wuliaodexiaoluo** [comment]
补完了，如果有缺再 @我，没有的话烦请换个标签

**Comment by LTCatt** [comment]
没看出来是哪儿引发的，干脆把整个代码重构了一下……
如果下个版本更新之后还是这样，传下新版本的 log（
