### ISSUE TITLE
即使没有手动指定缓存文件夹，PCL仍提示“您已手动指定缓存文件夹”

### ISSUE THREAD

**Issue by xiaozhouovo** [Hex-Dragon/PCL2#3793]
### 检查项

- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

即使没有手动指定缓存文件夹，PCL仍提示“您已手动指定缓存文件夹”
![360截图20240505163828](https://github.com/Hex-Dragon/PCL2/assets/149924308/b35680d3-b6fe-4ed2-ad59-43ecf6226ece)
![360截图20240505163843](https://github.com/Hex-Dragon/PCL2/assets/149924308/25f4fbeb-18ec-49a2-820b-f0bf5ed52496)

### 重现步骤

1、点击“设置”。
2、在左侧选择“启动器”，然后往下滚，找到“系统”，确保缓存文件夹没有手动指定。
3.点击“更多”。
4.在左侧选择“百宝箱”，然后点击“清理游戏垃圾”，内容在弹出的对话框中。

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15212251/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/15212252/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/15212253/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/15212255/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/15212256/Log5.txt)

**Comment by allMagicNB** [comment]
#3283

**Comment by xiaozhouovo** [comment]
您好！我是Chat-Bot！我已被主人接入QQ邮箱以进行自动回复！如果您收到此消息，表示我已收到您的邮件，我会通知主人在有空时阅读及处理。————————————这是来自QQ邮箱的自动回复邮件。

**Comment by wuliaodexiaoluo** [comment]
？
6
