### ISSUE TITLE
在MC1.20以上版本中无法正常保存世界

### ISSUE THREAD

**Issue by xiaozhouovo** [Hex-Dragon/PCL2#3794]
### 检查项

- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在1.20以上版本中无法正常保存世界，一直卡在“保存世界中”，无法通过“X”关闭窗口，且使用强制关闭后未保存最后的更改。
补充：1.未加载任何Mod或数据包，纯原版启动（这件事源于和其他朋友联机）
2.我朋友使用其他启动器尝试（同一版本），未出现问题，它的配置和我的相当。
3.这件事发生在2024年4月20日
4.保存时间统计：朋友（BakaXL最新预览版）：27秒        我（PCL最新版）：13分46秒（仍未保存完毕，等不及才关的）

### 重现步骤

1、启动1.20以上版本的MC
2、进入一个世界（建议使用新存档尝试），保存并退出

### 日志与附件

此问题已被其他人反馈过，但仍未处理（检查项是被逼着勾的）
![360截图20240505163843](https://github.com/Hex-Dragon/PCL2/assets/149924308/562727c6-e9c4-43e7-89d8-02d0d6792379)
由于时间过久，无法提供日志，但可参照此反馈：https://github.com/Hex-Dragon/PCL2/issues/3746

**Comment by allMagicNB** [comment]
能提供启动脚本吗……

**Comment by xiaozhouovo** [comment]
> 能提供启动脚本吗......

时间太久了，当时没有保存

**Comment by allMagicNB** [comment]
那你现场复现一遍再给喽

**Comment by xiaozhouovo** [comment]
> 那你现场复现一遍再给喽

好吧，等我吃饭回来

**Comment by xiaozhouovo** [comment]
> 那你现场复现一遍再给喽

请问启动脚本在哪里，需要开调试模式吗

**Comment by allMagicNB** [comment]
不用，启动后 PCL 主程序同路径下 PCL 文件夹中的那个脚本
HMCL 是进到版本设置中导出启动脚本

**Comment by xiaozhouovo** [comment]
[LatestLaunch.zip](https://github.com/Hex-Dragon/PCL2/files/15212438/LatestLaunch.zip)
是这个吧
![image](https://github.com/Hex-Dragon/PCL2/assets/149924308/a16797b6-a129-42bd-ba49-7622dcbebe1a)
已经保存3分钟了

**Comment by allMagicNB** [comment]
HMCL 的呢？

**Comment by xiaozhouovo** [comment]
> HMCL 的呢？

啊

**Comment by xiaozhouovo** [comment]
> HMCL 的呢？

我没有HMCL

**Comment by xiaozhouovo** [comment]
> HMCL 的呢？

我只有PCL，需要下一个吗

**Comment by allMagicNB** [comment]
你下一个，把程序放到 PCL 程序所在的同一个文件夹下，选择你的版本，启动，然后生成启动脚本。

**Comment by xiaozhouovo** [comment]
[hmcl.zip](https://github.com/Hex-Dragon/PCL2/files/15212500/hmcl.zip)
可以正常保存
![360截图20240505163843](https://github.com/Hex-Dragon/PCL2/assets/149924308/423d8302-4eaf-4197-b86b-7f1bf2c090ca)

**Comment by xiaozhouovo** [comment]
> 你下一个，把程序放到 PCL 程序所在的同一个文件夹下，选择你的版本，启动，然后生成启动脚本。

[hmcl.zip](https://github.com/Hex-Dragon/PCL2/files/15212508/hmcl.zip)
可以正常保存
![360截图20240505163843](https://github.com/Hex-Dragon/PCL2/assets/149924308/e75e9241-7da8-440c-a5be-2df20c58c442)

**Comment by LTCatt** [comment]
把附件贴到原 issue #3746，这个先关了
