### ISSUE TITLE
夜间模式！

### ISSUE THREAD

**Issue by Ender-Elaina-Theater** [Hex-Dragon/PCL2#3795]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

只需要弄一个开关>^<
可以调整面板的背景色为夜间色（一直都是白色）就好了>^<

### 原因

因为每次夜晚关灯的时候点开PCL都会被吃一口闪光弹，所以有了这个想法...
想了想应该可以实现的...所以就发了出去...

**Comment by JingHai-Lingyun** [comment]
这个基本上要重新设计所有界面，工作量太大了，我猜我都不会做……” ——龙腾猫跃
请见 #131
