### ISSUE TITLE
CraftTweaker下载页面前置显示错误

### ISSUE THREAD

**Issue by Fei-yao** [Hex-Dragon/PCL2#3798]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

图片在附件区
如图，Forge 1.18.2的CrT并不需要JEITweaker作为前置，Fabric 1.18.2的CrT也不需要Faux Custom Entity Data作为前置
目前暂未发现其他mod的下载页面出现该问题

### 重现步骤

在下载页面搜索CraftTweaker，展开版本列表，1.14.4往上均有此问题

### 日志与附件

![QQ图片20240506131312](https://github.com/Hex-Dragon/PCL2/assets/155740989/533d3c81-dadb-4d51-bf53-5654b2599281)

**Comment by allMagicNB** [comment]
![Screenshot_20240506_133224_com.microsoft.emmx.jpg](https://github.com/Hex-Dragon/PCL2/assets/116283787/830bda63-e21b-4e2d-a28e-5cffac4cacba)

作者在 CurseForge 页面就这么写的。
