### ISSUE TITLE
[Bug] PCL 可能会错误的将 jlw 目录指定到并不存在\无法写入的驱动器上

### ISSUE THREAD

**Issue by wuliaodexiaoluo** [Hex-Dragon/PCL2#3799]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

PCL 可能会错误的将 jlw 目录指定到并不存在\无法写入的驱动器上
我甚至不知道怎么指定到软盘驱动器上的

### 重现步骤

这个建议虚拟机复现

### 日志与附件

![image](https://github.com/Hex-Dragon/PCL2/assets/160083863/791ce01c-9031-4823-87d1-73f7ec34bfda)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/15218659/Log3.txt)
问题是 jlw 无法释放导致的，在 2910 行

**Comment by LTCatt** [comment]
`Environment.GetLogicalDrives()` 返回了 `A:\`，我也不知道咋回事

**Comment by allMagicNB** [comment]
@LTCatt 好像给修炸了……？
