### ISSUE TITLE
支持下载和安装 Modrinth 上的 Mod、整合包

### ISSUE THREAD

**Issue by LTCatt** [Hex-Dragon/PCL2#38]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

支持下载和安装 [Modrinth](https://modrinth.com/) 上的 Mod 与整合包。

### 原因

Modrinth 作为新兴的网站，目前已经差不多能用了。

**Comment by iPodtouch6557** [comment]
啊

**Comment by RawDiamondMC** [comment]
好耶

**Comment by TsaiTou2926** [comment]
啥時候支援

**Comment by iPodtouch6557** [comment]
这是我玩考古玩到的第一个支持的页面（）

**Comment by KomoZH** [comment]
考古

**Comment by RyogiMutsuki** [comment]
@KomoZH 请不要挖坟，谢谢
