### ISSUE TITLE
mc1.20.6 java下载问题

### ISSUE THREAD

**Issue by helloiwff** [Hex-Dragon/PCL2#3802]
### 检查项

- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在下载好mc1.20.6后，若电脑未安装java，会自动提示下载java17，而非java21

### 重现步骤

1.电脑没有安装任何java
2.下载mc1.20.6
3.启动mc1.20.6

### 日志与附件

[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/15229631/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15229632/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/15229633/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/15229634/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/15229635/Log4.txt)

**Comment by allMagicNB** [comment]
你不是在更新前出现的这个问题吗？

**Comment by allMagicNB** [comment]
> 见 #3735
> 请等待更新发布

你要不要先看看日志？

**Comment by wuliaodexiaoluo** [comment]
> > 见 #3735
> > 请等待更新发布
> 
> 你要不要先看看日志？

Snapshot 2.7.2 还没发布的说

**Comment by wuliaodexiaoluo** [comment]
#3601
<details>
<summary> Off Topic </summary>
知道是重复就行，不要动不动就   你要不

就算其他人 Comment 错误的信息，也请不要以这种几乎等同于反对的的问题来抨击他人观点
你可以换种表达法，诸如 `看下日志` 等等，我真的搞不懂有那么多表达法，你为何要选择带有攻击性的语言
我认为龙猫肯定不希望 Collaborator 和 User 或者社区志愿者吵起来，所以请调整一下你的态度

</details>

**Comment by allMagicNB** [comment]
没攻击啊，给个建议得了，想多了

**Comment by allMagicNB** [comment]
作者明显是在版本更新前触发的 Bug，你看都不看日志就先说是#3735

**Comment by wuliaodexiaoluo** [comment]
Edit 过了，#3601 #3735 都贴一遍，免得遗漏了

**Comment by allMagicNB** [comment]
不对，日志里边压根没东西，而且所有日志开头都可以看到安装了 Java……
算了，@helloiwff 你要继续反馈的话请上传正确的日志。
