### ISSUE TITLE
回归联机！小收点费也行！！！

### ISSUE THREAD

**Issue by johnjq1** [Hex-Dragon/PCL2#3803]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

回归联机！小收点费也行！！！

### 原因

这项优化让我可以更方便地联机。
如果没有这项优化，我每次都必须开内网穿透，让操作变得很麻烦。

**Comment by allMagicNB** [comment]
等某个代理结束吧……

**Comment by allMagicNB** [comment]
https://www.bilibili.com/read/cv25865336/

**Comment by johnjq1** [comment]
Oh right！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月7日(周二) 中午1:12
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Hex-Dragon/PCL2] 回归联机！小收点费也行！！！ (Issue #3803)




 
https://www.bilibili.com/read/cv25865336/

**Comment by wuliaodexiaoluo** [comment]
请尽可能避免在社区 Issue 等公开页面谈论这个东西，有可能会被 wy 警告

**Comment by allMagicNB** [comment]
> 请尽可能避免在社区 Issue 等公开页面谈论这个东西，有可能会被 wy 警告

我说了吗？你咋不看看你自己说得有多明显？

**Comment by wuliaodexiaoluo** [comment]
没说你
