### ISSUE TITLE
在Mod管理中添加规范文件命名功能

### ISSUE THREAD

**Issue by RandomEnch** [Hex-Dragon/PCL2#3804]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在 版本设置-Mod管理 中可以将未按照 设置-启动器-Mod命名风格 命名的模组文件一键重命名为规范文件名

### 原因

这项优化让我可以更方便地管理Mod文件夹
如果没有这项优化，安装整合包后重命名大量的英文模组十分麻烦

**Comment by WForst-Breeze** [comment]
#1728 是否可以满足需求？鉴于可能存在除 #1728 之外的需求（如中文方括号批量修改为英文方括号等），先初步确认等龙猫怎么看，感谢反馈

**Comment by LTCatt** [comment]
使用面太小了，抱歉 Orz
