### ISSUE TITLE
[转载 #3806][Bug] 启动失败：线程从等待状态中断

### ISSUE THREAD

**Issue by wuliaodexiaoluo** [Hex-Dragon/PCL2#3807]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

启动报错
（可能是个 Bug）

### 重现步骤

转载 #3806 

### 日志与附件

![329732710-fdd44bab-3e19-4a00-abc5-17621cebdf3c](https://github.com/Hex-Dragon/PCL2/assets/160083863/756bbbcf-606c-49a7-81ef-8ae83c7205a1)
[log1.txt](https://github.com/Hex-Dragon/PCL2/files/15280661/Log1.txt)

**Comment by LTCatt** [comment]
由于无人能复现暂时关闭。
