### ISSUE TITLE
OptiFine安装失败

### ISSUE THREAD

**Issue by Eromongno** [Hex-Dragon/PCL2#3808]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

OpitiFine安装失败I6以下可以正常安装

### 重现步骤

1、点开始安装
2、往进度条走到80%卡住不动

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15281592/Log1.txt)

**Comment by allMagicNB** [comment]
#3657
