### ISSUE TITLE
PCL2以管理员身份运行时，拖拽添加mod或整合包功能失效

### ISSUE THREAD

**Issue by CreativeEVW** [Hex-Dragon/PCL2#3811]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

<img width="679" alt="1" src="https://github.com/Hex-Dragon/PCL2/assets/120068696/d3b57f79-c893-4b9e-a6cb-4483e4b01e3f">
<img width="706" alt="2" src="https://github.com/Hex-Dragon/PCL2/assets/120068696/15c14fb7-def6-41a3-ace6-37ec0636f534">
如图拖拽时鼠标显示禁止符号（无法截屏）

### 重现步骤

1、右键以管理员身份运行（或属性兼容性设置以管理员身份运行）
2、拖拽mod或整合包进入PCL窗口

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15283247/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/15283248/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/15283249/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/15283250/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/15283251/Log5.txt)

**Comment by JingHai-Lingyun** [comment]
#2531，暂时没有一个可行的解决方式，Orz……
