### ISSUE TITLE
mod下载列表里 部分1.20.6mod不正常显示

### ISSUE THREAD

**Issue by 4goten** [Hex-Dragon/PCL2#3813]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

搜索部分已适配1.20.6的mod搜不到 只能搜到前版本 如 1.20.5 1.20.4 但是没有1.20.6 但是已知他更新了
在筛选里添加条件1.20.6版本 再次搜索相同的mod 可以出现1.20.6版本的

### 重现步骤

1、下载资源 - sodium
2、找不到1.20.6版本
3、添加版本条件 1.20.6
4、出现1.20.6下载版本
5、删掉条件 1.20.6
6、再次搜索时 sodium不再显示1.20.6 

### 日志与附件

无需上传log

**Comment by allMagicNB** [comment]
请不要自以为是，请上传日志文件和截屏演示。

**Comment by JingHai-Lingyun** [comment]
测了一下，双平台的结果不一样：Sodium 于 Modrinth 上有 1.20.6 但是 CurseForge 没有
不知道合并的时候出了什么事情……
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15285014/Log1.txt)

**Comment by LTCatt** [comment]
```
[11:59:02.603] [Comp] 从 CurseForge 获取到了 11 个工程（已获取 11 个，共 11 个）
[11:59:02.756] [Comp] 从 Modrinth 获取到了 32 个工程（已获取 32 个，共 32 个）
[11:59:02.757] [Comp] 将 Sodium (sodium) 与 Sodium (sodium) 认定为相似工程
[11:59:02.757] [Comp] 将 Sodium Extra (sodium-extra) 与 Sodium Extra (sodium-extra) 认定为相似工程
```
确实和相似认定有关。
btw 语气不用这么硬，大家也是出于善意才来叫 issue 的嘛（

**Comment by LTCatt** [comment]
CurseForge 追加了 1.20.6 Sodium，现已无法复现
