### ISSUE TITLE
重新添加设置删除游戏内容到回收站/永久删除的选项

### ISSUE THREAD

**Issue by TanChenyu** [Hex-Dragon/PCL2#3815]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

如题，在启动器设置里添加一个选项“将删除内容放至回收站”之类的
我记得以前有过这样的功能

### 原因

主要是每次都要手动清回收站很麻烦……我经常删东西

**Comment by allMagicNB** [comment]
按住 `Shift` 键后点击删除即可永久删除而不经过回收站

**Comment by Deep-Dark-Forest** [comment]
应该是与 #3290 重复才对

**Comment by allMagicNB** [comment]
不对，感觉可以看看……？要不然每次都得按 `Shift`

**Comment by Deep-Dark-Forest** [comment]
那 reopen #3290 啊

**Comment by allMagicNB** [comment]
> 那 reopen #3290 啊

这俩给的设置方式方式又不同

**Comment by allMagicNB** [comment]
> 那 reopen #3290 啊

这俩给的设置方式又不同

**Comment by TanChenyu** [comment]
> > 那 reopen #3290 啊
> 
> 这俩给的设置方式又不同

reopen吧，我觉得那个issue的设置更好
