### ISSUE TITLE
[转发] 删除mod时PCL报错是怎么回事

### ISSUE THREAD

**Issue by LTCatt** [Hex-Dragon/PCL2#3816]
### Discussed in https://github.com/Hex-Dragon/PCL2/discussions/3769

<div type='discussions-op-text'>

<sup>Originally posted by **GCatMew000** May  1, 2024</sup>
删除mod（bellsandwhistles-0.4.5+1.20.1-FABRIC.jar）时PCL报错“`程序出现未知错误：未将对象引用设置到对象的实例`” 且之后**无法复现**？
<del>就离谱，有没有人知道怎么回事
<p>Log 1-5 文件如下

> [Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15173994/Log1.txt)
> [Log2.txt](https://github.com/Hex-Dragon/PCL2/files/15173996/Log2.txt)
> [Log3.txt](https://github.com/Hex-Dragon/PCL2/files/15173997/Log3.txt)
> [Log4.txt](https://github.com/Hex-Dragon/PCL2/files/15173998/Log4.txt)
> [Log5.txt](https://github.com/Hex-Dragon/PCL2/files/15173999/Log5.txt)
</div>

**Comment by allMagicNB** [comment]
@wuliaodexiaoluo Like This

**Comment by wuliaodexiaoluo** [comment]
？？？

**Comment by iPodtouch6557** [comment]
建议把油箱通知关了，除非你的Github有非常重要的工作信息
另外
![image](https://github.com/Hex-Dragon/PCL2/assets/118656946/8266cfc4-eece-431c-9948-a467c819bb8e)
~在那个年代你有概率被剪头~

**Comment by wuliaodexiaoluo** [comment]
《油箱》
我就是打错了不至于啊

**Comment by JingHai-Lingyun** [comment]
不建议在 Issue 帖子内聊，如有需要请到 Discussion 区或者使用其他平台聊

**Comment by allMagicNB** [comment]
> ？？？
> #3810 的 Comment 我看到了，建议不要重复提示，真的，邮箱够乱了

那你 Unwatch 呗
