### ISSUE TITLE
添加建立自定义mod标签功能

### ISSUE THREAD

**Issue by 578448983** [Hex-Dragon/PCL2#3817]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

增加mod标签功能，允许玩家建立自定义标签并将mod归类到标签下，在mod管理页面可直接操作，可收起标签下内容方便查看。能根据标签批量改mod名。

### 原因

（示例）
方便对mod的归类整理，大幅降低制作整合包的人力成本，利于根据标签分类排查冲突等

**Comment by JingHai-Lingyun** [comment]
> 这玩意儿做着太麻烦了，并且会用上这个功能的人也不算太多，可以自己改改文件名啥的也不影响，还是算了，优先级更高的新功能还多着去呢……

参见 #277

**Comment by allMagicNB** [comment]
#277
