### ISSUE TITLE
第三方登录更改 “注册链接” 后点击 “注册” 弹出的网页还是未更改前的 “注册链接”

### ISSUE THREAD

**Issue by allMagicNB** [Hex-Dragon/PCL2#3819]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

就很奇怪，改注册链接之后点主页的注册按钮，打开的是之前设置的本应被覆盖的网址……？

### 重现步骤

1. 点击版本设置
2. 选择第三方登录选项
3. 随便填填链接
![image](https://github.com/Hex-Dragon/PCL2/assets/116283787/b3359182-a778-40cf-9b66-e5f993c748a3)

4. 启动游戏
5. 关闭游戏
6. 更换注册链接
![image](https://github.com/Hex-Dragon/PCL2/assets/116283787/45cd8004-5e94-471f-8f43-469555ff0374)

7. 点击主页 “注册” 按钮，然后就跳转到了奇怪的地方
![image](https://github.com/Hex-Dragon/PCL2/assets/116283787/6cdb8919-c5c1-453d-9832-a8bf54b8f900)

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15286750/Log1.txt)

**Comment by kong-que-dnf123** [comment]
我感觉像littleskin设置完就给锁这个登陆方式了.jpg
