### ISSUE TITLE
Mod下载界面Curseforge源和modrinth源的模组版本区分

### ISSUE THREAD

**Issue by Water-Yuan** [Hex-Dragon/PCL2#3822]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在Mod下载界面中，在“来源”设置为“全部”时，搜索mod后有时会同时显示Curseforge源和Modrinth源的Mod。
但不同的作者在两个平台更新mod的速度不同，可能会导致一些mod在Curseforge上较新，另一些mod在Modrinth上较新，此时分别点开并人为区分比较耗时。
建议在“来源”设置为“全部”时，合并名称完全相同的mod列表，并在详细版本选择中添加[Curseforge] [Modrinth]的标签进行区分。
![PixPin_2024-05-13_19-24-44](https://github.com/Hex-Dragon/PCL2/assets/169665025/48faa727-eca9-4625-bcdb-0eaca5b9908c)

### 原因

这项优化让我可以更方便地下载所需mod。
如果没有这项优化，我每次都必须点开版本并区分，让操作变得很麻烦。

**Comment by Water-Yuan** [comment]
> 确实有做合并啊，只不过这是两个的描述不同没合并而已（

所以建议合并来优化体验（

**Comment by allMagicNB** [comment]
#1513

**Comment by LTCatt** [comment]
这个我可以再寻思一下合并算法能不能优化，这俩应该可以视作相同工程的

**Comment by allMagicNB** [comment]
> 这个我可以再寻思一下合并算法能不能优化，这俩应该可以视作相同工程的

@LTCatt 那你 Reopen #1513 啊（

**Comment by LTCatt** [comment]
#1513 是 mod 支持的版本不一样所以不合并，这个 issue 里 mod 支持的版本似乎是一样的

**Comment by LTCatt** [comment]
该 Mod 在 Modrinth 上未标记支持 NeoForge，在 CurseForge 上标记支持 NeoForge，所以没有合并，WAI
