### ISSUE TITLE
更新出现bug了

### ISSUE THREAD

**Issue by shabuleke** [Hex-Dragon/PCL2#3823]
### 检查项

- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

输入密钥更新后报错

### 重现步骤

1、输入密钥
2、等待下载完成
3、下载完成后自动弹出报错并关闭PCL

### 日志与附件

![mmexport1715602844524](https://github.com/Hex-Dragon/PCL2/assets/132280121/1caa21c4-7636-43c4-ae92-e8d1f8bb1299)
![mmexport1715604913695](https://github.com/Hex-Dragon/PCL2/assets/132280121/3ec391c0-de8f-4926-8d2c-d29858c6ce58)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15297082/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/15297085/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/15297086/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/15297087/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/15297088/Log5.txt)

**Comment by allMagicNB** [comment]
你确定这更新密钥是你的？
可否提供爱发电截图？

**Comment by shabuleke** [comment]
![mmexport1715604026353](https://github.com/Hex-Dragon/PCL2/assets/132280121/e7157c51-8e7a-4f69-b3c5-d7c53e16aea0)

**Comment by shabuleke** [comment]
的确是我的

**Comment by shabuleke** [comment]
重新下载再更新都不行

**Comment by allMagicNB** [comment]
包含你识别码的截屏，还有日志

**Comment by shabuleke** [comment]
9625-CC8C-301D-37A8

**Comment by shabuleke** [comment]
这是我识别码

**Comment by shabuleke** [comment]
日志我不知道咋看啊

**Comment by shabuleke** [comment]
![Uploading mmexport1715604585709.png…]()

**Comment by allMagicNB** [comment]
你重新发一遍 `更新 9625-CC8C-301D-37A8`，然后再用新的更新密钥更新。

**Comment by allMagicNB** [comment]
等 `Uploading XXX` 字样消失后再发送……

**Comment by burningtnt** [comment]
**等 Uploading XXX 字样消失后再发送……**

**Comment by shabuleke** [comment]
![Uploading mmexport1715604913695.png…]()

**Comment by allMagicNB** [comment]
# 你先别急

**Comment by allMagicNB** [comment]
另外，你可以想好要说什么再一次性发出来
~~我的邮箱~~

**Comment by shabuleke** [comment]
我现在的问题是一更新下载完就立马弹错误界面

**Comment by shabuleke** [comment]
![Uploading mmexport1715604913695.png…]()

**Comment by shabuleke** [comment]
而且不知道为什么图片发不出来了，一发出来就是正在上传

**Comment by allMagicNB** [comment]
发日志，PCL2 程序同路径下 `PCL` 文件夹内的 `Log1~5.txt`

**Comment by shabuleke** [comment]
弹的错误界面就是问题里的那个图片

**Comment by shabuleke** [comment]
我找到了

**Comment by shabuleke** [comment]
稍等

**Comment by allMagicNB** [comment]
……6

**Comment by shabuleke** [comment]
[Uploading Log1.txt…]()

**Comment by shabuleke** [comment]
这显示正在上传是怎么回事

**Comment by ZZZank** [comment]
发送得太急了，发送图片之类的文件要等上传完成，再发送

**Comment by shabuleke** [comment]
这样啊，之前急过头了

**Comment by shabuleke** [comment]
这要等多久才能上传成功啊

**Comment by burningtnt** [comment]
以你裸连 GitHub 的速度，估计几分钟

**Comment by shabuleke** [comment]
......

**Comment by ZZZank** [comment]
图里两行是分别上传的两个文件，上面的是成功的，下面的还没上传完。参照一下
![image](https://github.com/Hex-Dragon/PCL2/assets/47418975/68769913-626f-47cb-ad48-87b9e5aa94a0)
以及，Github不是聊天群，发短而没有信息量的消息很不好。

**Comment by shabuleke** [comment]
明白了

**Comment by shabuleke** [comment]
[Uploading Log1.txt…]()

**Comment by shabuleke** [comment]
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/15296883/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/15296884/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/15296887/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/15296888/Log5.txt)

**Comment by shabuleke** [comment]
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15297061/Log1.txt)

**Comment by allMagicNB** [comment]
完全没看出来有啥问题……

**Comment by shabuleke** [comment]
那我这是咋回事啊

**Comment by shabuleke** [comment]
而且我发现我下游戏主体也是失败的
![mmexport1715649372891](https://github.com/Hex-Dragon/PCL2/assets/132280121/dca1b69b-7f8b-4b29-ab78-8a4ad0a807e3)

**Comment by JingHai-Lingyun** [comment]
不正确的数据通常是由于源数据异常导致的
确认你正确的使用了更新密钥，请**完整复制**密钥并粘贴入询问弹窗中。

无法安装的问题应当在更新之后即解决

---

另请善用 Edit 功能，如果你写错了什么，请点击右上角 `...` -> `Edit` 修改后确认。
如果无用信息过多可能导致反馈帖被锁定。

**Comment by shabuleke** [comment]
我已经重新试过好几遍了，记录里也能看的出来，甚至更新密钥我都重新获取过，就是不行

**Comment by Fadfaruvet** [comment]
出现相同问题![mmexport1715653728458.png](https://github.com/Hex-Dragon/PCL2/assets/149254902/68a63afb-654f-4b89-87ae-bd41bada9dfd)

![mmexport1715653725678.png](https://github.com/Hex-Dragon/PCL2/assets/149254902/fb47ff5f-1214-4d28-8863-4075cd8d4064)

![Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15301864/Log1.txt)

![Log2.txt](https://github.com/Hex-Dragon/PCL2/files/15301866/Log2.txt)

![Log3.txt](https://github.com/Hex-Dragon/PCL2/files/15301868/Log3.txt)

![Log4.txt](https://github.com/Hex-Dragon/PCL2/files/15301870/Log4.txt)

![Log5.txt](https://github.com/Hex-Dragon/PCL2/files/15301872/Log5.txt)

**Comment by JingHai-Lingyun** [comment]
鉴于有第二个人发生此问题，让龙猫看看吧

**Comment by kong-que-dnf123** [comment]
两者的日志都是在更新包疑似下载成功后报错（原2.6.8的更新载体都已收到了更新关闭指令）`[System] 已由于更新强制结束程序`
那么问题理应出现在运行重更新时失败...

<details>
<summary>题外话</summary>

~为什么我第一反应又觉得是因为识别码崩盘导致前后不一致从而解锁快照版失败的原因.jpg~

---
</details>

**Comment by shabuleke** [comment]
lssue

**Comment by allMagicNB** [comment]
> lssue

发送识别码

**Comment by shabuleke** [comment]
9625-CC8C-301D-37A8

**Comment by shabuleke** [comment]
> > 问题
> 
> 无线识别码

9625-CC8C-301D-37A8

**Comment by LTCatt** [comment]
你的解锁码：LaWbp+ixlhCSl7JqGFlpdsWdfhYu8VY2
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by shabuleke** [comment]
解锁码

**Comment by Pearl-Luo** [comment]
> 解锁码

你不发新的识别码龙猫怎么帮你解锁...

**Comment by shabuleke** [comment]
识别码7C66-5D42-81A0-7F18

**Comment by shabuleke** [comment]
着急过头了

**Comment by shabuleke** [comment]
毕竟电脑刚修好，还要搬家

**Comment by shabuleke** [comment]
求新的解锁码

**Comment by wyc-26** [comment]
GitHub 不是版聊……

**Comment by Pearl-Luo** [comment]
> 求新的解锁码

@shabuleke 请不要频繁的进行催促，毕竟龙猫也不是 24 小时在线，切急勿躁

**Comment by LTCatt** [comment]
你的解锁码：SCKuO/VW9xlPkDI4nyKjV3o7Q5PimJ3+
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
