### ISSUE TITLE
PCL2快速点击删除mod时导致PCL崩溃

### ISSUE THREAD

**Issue by jfglzs** [Hex-Dragon/PCL2#3824]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

使用1.12.2lite加载器 Optifine 最新 在删除mod时(点击速度较快)PCL2出现了崩溃！弹出log1.txt日志

### 重现步骤

do
1、打开PCL
2、选择1.12.2版本
3，删除mod
4，弹出LOG1日志
Done

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15294737/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/15294739/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/15294740/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/15294741/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/15294742/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15294743/Log1.txt)

**Comment by allMagicNB** [comment]
#3816
