### ISSUE TITLE
下载自定义文件直接打开下载文件

### ISSUE THREAD

**Issue by Leonmmcoset** [Hex-Dragon/PCL2#3826]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

可以下载完弹出个窗口啥的

### 原因

这样就不用打开文件夹再往里面找了
（PCL下载器）

**Comment by allMagicNB** [comment]
恕我直言，PCL 是 Minecraft 启动器，并非为下载器，同时龙猫已表明不会为自定义下载做拓展，而且目前来说这个功能也没啥用……总之这点事还不至于整出个弹窗……

顺嘴一提，如果你是为了活跃橙来提交反馈的，活跃橙需要提交 Bug 反馈，而不是优化或新功能提议。如果不是，你可以忽略这段话。

**Comment by JingHai-Lingyun** [comment]
目前你可以在下载前直接点击下载按钮边上的打开文件夹按钮打开你指定的目录。
但…… 正如上述内容，PCL 是 Minecraft 启动器，即使制作这个功能优先级也很低

**Comment by JingHai-Lingyun** [comment]
啊，等等。对于标题中提到的 `直接打开下载文件`，#2063 放弃 / 拒绝
