### ISSUE TITLE
无法进入游戏

### ISSUE THREAD

**Issue by xiaoshazizizizizizizi** [Hex-Dragon/PCL2#3829]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/Hex-Dragon/PCL2/assets/61924682/ce3623c7-cb84-43eb-973c-cc9b79677098)

### 重现步骤

打不开

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15321485/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/15321487/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/15321488/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/15321489/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/15321490/Log5.txt)

**Comment by xiaoshazizizizizizizi** [comment]
[错误报告-2024-5-15_20.37.47.zip](https://github.com/Hex-Dragon/PCL2/files/15321528/-2024-5-15_20.37.47.zip)

**Comment by burningtnt** [comment]
你按教程里的步骤截个显卡型号的图看看 https://jingyan.baidu.com/article/9080802219bcfcbc91c80fe0.html

**Comment by JingHai-Lingyun** [comment]
我感觉不是 PCL 的问题……

**Comment by xiaoshazizizizizizizi** [comment]
> 你按教程里的步骤截个显卡型号的图看看 https://jingyan.baidu.com/article/9080802219bcfcbc91c80fe0.html

![image](https://github.com/Hex-Dragon/PCL2/assets/61924682/21290084-753a-4e38-86ea-8fe4d34a5095)

**Comment by burningtnt** [comment]
> > 你按教程里的步骤截个显卡型号的图看看 https://jingyan.baidu.com/article/9080802219bcfcbc91c80fe0.html
> 
> ![image](https://private-user-images.githubusercontent.com/61924682/330808213-21290084-753a-4e38-86ea-8fe4d34a5095.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NzczMjEsIm5iZiI6MTcxNTc3NzAyMSwicGF0aCI6Ii82MTkyNDY4Mi8zMzA4MDgyMTMtMjEyOTAwODQtNzUzYS00ZTM4LTg2ZWEtOGZlNGQzNGE1MDk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDEyNDM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4ODIxOTI4YmZmNDJkOTYxZDBiNGZkMWE3YmEyOTE0NGIwZWE2MGZhOWUwNGFiMTI1MDI0NjRmODYxY2ZjN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wPmKpfL7vnvLLQUez7y7YBAl4tnf4nqYLIxv0Ws3p8g)

在 NVIDIA 控制面板里按图里顺序改成「高性能 NVIDIA 处理器」，然后点下面的「应用」，最后重启电脑 https://gitcode.net/chearlai/kookfiles/-/raw/master/assets/2023-06/LHqkHeKbD90pr0aw.png
不改全局设置也可以，选择 “程序设置”，添加游戏进程所用的 java 并设置为高性能

**Comment by xiaoshazizizizizizizi** [comment]
> > > 你按教程里的步骤截个显卡型号的图看看https://jingyan.baidu.com/article/9080802219bcfcbc91c80fe0.html
> > 
> > 
> > ![图像](https://private-user-images.githubusercontent.com/61924682/330808213-21290084-753a-4e38-86ea-8fe4d34a5095.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NzczMjEsIm5iZiI6MTcxNTc3NzAyMSwicGF0aCI6Ii82MTkyNDY4Mi8zMzA4MDgyMTMtMjEyOTAwODQtNzUzYS00ZTM4LTg2ZWEtOGZlNGQzNGE1MDk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDEyNDM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4ODIxOTI4YmZmNDJkOTYxZDBiNGZkMWE3YmEyOTE0NGIwZWE2MGZhOWUwNGFiMTI1MDI0NjRmODYxY2ZjN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wPmKpfL7vnvLLQUez7y7YBAl4tnf4nqYLIxv0Ws3p8g)
> 
> 在 NVIDIA 控制面板里按图里顺序改成「高性能 NVIDIA 处理器」，然后点下面的「应用」，最后重启电脑[https://gitcode.net/chearlai/kookfiles/-/raw/master/assets/ 2023-06/LHqkHeKbD90pr0aw.png](https://gitcode.net/chearlai/kookfiles/-/raw/master/assets/2023-06/LHqkHeKbD90pr0aw.png) 不改全局设置也可以，选择“程序设置”，添加游戏进程所用的java并设置为性能

一直是高性能，没改过

**Comment by xiaoshazizizizizizizi** [comment]
> > > 你按教程里的步骤截个显卡型号的图看看https://jingyan.baidu.com/article/9080802219bcfcbc91c80fe0.html
> > 
> > 
> > ![图像](https://private-user-images.githubusercontent.com/61924682/330808213-21290084-753a-4e38-86ea-8fe4d34a5095.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NzczMjEsIm5iZiI6MTcxNTc3NzAyMSwicGF0aCI6Ii82MTkyNDY4Mi8zMzA4MDgyMTMtMjEyOTAwODQtNzUzYS00ZTM4LTg2ZWEtOGZlNGQzNGE1MDk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDEyNDM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4ODIxOTI4YmZmNDJkOTYxZDBiNGZkMWE3YmEyOTE0NGIwZWE2MGZhOWUwNGFiMTI1MDI0NjRmODYxY2ZjN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wPmKpfL7vnvLLQUez7y7YBAl4tnf4nqYLIxv0Ws3p8g)
> 
> 在 NVIDIA 控制面板里按图里顺序改成「高性能 NVIDIA 处理器」，然后点下面的「应用」，最后重启电脑[https://gitcode.net/chearlai/kookfiles/-/raw/master/assets/ 2023-06/LHqkHeKbD90pr0aw.png](https://gitcode.net/chearlai/kookfiles/-/raw/master/assets/2023-06/LHqkHeKbD90pr0aw.png) 不改全局设置也可以，选择“程序设置”，添加游戏进程所用的java并设置为性能

一直是高性能，没改过
![image](https://github.com/Hex-Dragon/PCL2/assets/61924682/9a35842e-7359-4922-82a2-5c9fa61856ae)

**Comment by burningtnt** [comment]
…… 那你升级显卡驱动去。
无论如何，这不是 PCL2 的问题

**Comment by xiaoshazizizizizizizi** [comment]
> 我感觉不是 PCL 的问题……

我也不是很懂，几年前没补票玩的1.17版本还没问题，今天补票了发现正版这块进不去了，官方启动器倒是没问题

**Comment by xiaoshazizizizizizizi** [comment]
> …… 那你升级显卡驱动去。 无论如何，这不是 PCL2 的问题

好的，谢谢
