### ISSUE TITLE
音乐播放器导致的报错，新版本依然有的问题

### ISSUE THREAD

**Issue by SzJu** [Hex-Dragon/PCL2#3831]
### 检查项

- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![屏幕截图 2024-05-16 175521](https://github.com/Hex-Dragon/PCL2/assets/169128312/26b4dcf4-30b9-421a-9985-d9ac51535fb6)

### 重现步骤

1、启动器播放音乐到一半，停止且不关闭启动器
2、关闭电脑时选择休眠而不是关机
3、启动电脑
4、左键点击“没有被关掉的PCL2启动器”右下角的播放器控制按钮

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15334216/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/15334217/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/15334218/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/15334219/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/15334220/Log5.txt)

**Comment by allMagicNB** [comment]
#1753
