### ISSUE TITLE
PCL启动不了：无法调用目标

### ISSUE THREAD

**Issue by GuanyuChan** [Hex-Dragon/PCL2#3832]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

就今天打开游戏的时候，就出现了这个Bug,（图片在附件）

然后即使我重新安装启动器，同是一个结果

### 重现步骤

这个是我今天按开启动器的时候就有的。。。

### 日志与附件

![屏幕截图 2024-05-16 195804](https://github.com/Hex-Dragon/PCL2/assets/146720906/734a3ca1-051f-40c4-a3b2-7d2395669275)

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15334743/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/15334744/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/15334753/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/15334754/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/15334756/Log5.txt)

**Comment by allMagicNB** [comment]
你这应该还不是最新版吧？

**Comment by youzi-2333** [comment]
日志翻了一遍，没看出有啥问题……

请确保启动器版本为最新，如果问题仍然存在，请重新上传日志

**Comment by GuanyuChan** [comment]
这个是按开启动器的应用就出现的报错，而且我也更新到快照的最新版了...日志还要吗

**Comment by JingHai-Lingyun** [comment]
> 参见 #2885

你是否删除了 C:\Users\用户名\AppData\Roaming\PCL 这个文件夹或内部文件

> 参见 #2993，但此例提供的截图不太一样

这应该不是 PCL 的问题，也没法修

**Comment by GuanyuChan** [comment]
沒有

**Comment by GuanyuChan** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/146720906/f24848b2-6ec0-43b3-a700-83e2cf5c54d6)

**Comment by allMagicNB** [comment]
看起来不太像是 PCL 的原因……
总之先让龙猫看看？

**Comment by LTCatt** [comment]
在 2.7.3 中添加了更多的调试信息，如果在 2.7.3 更新后依然崩溃，请重新上传日志和报错截图，才能处理

**Comment by allMagicNB** [comment]
> 在 2.7.3 中添加了更多的调试信息，如果在 2.7.3 更新后依然崩溃，请重新上传日志和报错截图，才能处理

但是这像是还没运行到写入日志那部分的代码就报错了……

**Comment by Dave12138** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/35069593/ea9f4953-9958-42af-9373-78291bc4339b)
欸不是怎么我也

**Comment by allMagicNB** [comment]
> ![image](https://github.com/Hex-Dragon/PCL2/assets/35069593/ea9f4953-9958-42af-9373-78291bc4339b)
> 欸不是怎么我也

你这报错不一样

**Comment by JingHai-Lingyun** [comment]
> 欸不是怎么我也

这个应当是 #3823

**Comment by LTCatt** [comment]
反馈者能使用 2.7.3 复现么

**Comment by Michaelshenmo** [comment]
管理员运行cmd运行sfc /scannow试一下？

**Comment by GuanyuChan** [comment]
先说一下：
1，我是打不开启动器的，就直接卡在外面了，也复现不了
2，PCL提醒了我更新，我也照着更新
3，即使我重装PCL，也是同样的，就打不开

**Comment by LTCatt** [comment]
如果 2.7.3 能复现，就算没 log 也截个图……

**Comment by allMagicNB** [comment]
> 管理员运行cmd运行sfc /scannow试一下？

别误导，这是扫盘，基本上没啥用……

**Comment by LBZiXL** [comment]
> > 管理员运行cmd运行sfc /scannow试一下？
> 
> 别误导，这是扫盘，基本上没啥用……

扫盘不是 dir /s 吗？

**Comment by kong-que-dnf123** [comment]
额原来连开启图标都没有的窗口式报错也能见缝插针的写进去一点点日志吗...?

**Comment by LTCatt** [comment]
由于反馈者半个月没回先关了，有需要可以继续回

**Comment by GuanyuChan** [comment]
不知名的原因又可以了，也不过就是我把正式开一次然后换回快照版就好了，谢谢
