### ISSUE TITLE
动态归类各个版本

### ISSUE THREAD

**Issue by Michaelshenmo** [Hex-Dragon/PCL2#3838]
### 检查项

- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

如果不是手动前往下载，而是点击提示的更新时，会把原版本归类为“不常用版本”，希望可以根据启动该版本的比例动态调整归类，并且可以手动更改分类，而不是只能放在默认/收藏中

### 原因

这项优化让我可以更方便地选择我需要的版本。
如果没有这项优化，我每次都必须寻找我需要的版本，让操作变得很麻烦。

**Comment by LTCatt** [comment]
暂时做不过来，抱歉 orz
