### ISSUE TITLE
增加15周年纪念披风翻译

### ISSUE THREAD

**Issue by Light-Beacon** [Hex-Dragon/PCL2#3840]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

如题

**Comment by allMagicNB** [comment]
@LTCatt 这披风要等六月底才到 Java 里边，先不急（

**Comment by xiaoliyuanpp** [comment]
我发了一个Pull Requests
