### ISSUE TITLE
隐藏不可用的自动安装选项

### ISSUE THREAD

**Issue by LTCatt** [Hex-Dragon/PCL2#3841]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

如果一个自动安装选项明显不适用于当前情况就应该隐藏。
例如高版本中均不显示 LiteLoader。

### 原因

减轻新玩家负担。

**Comment by allMagicNB** [comment]
突然感觉这个做了会不会有一大堆小白来问怎么没这个没那个的（

**Comment by LTCatt** [comment]
应该不至于 =。=
