### ISSUE TITLE
在Mod列表中显示模组jar文件中的图标

### ISSUE THREAD

**Issue by Gxy20101221** [Hex-Dragon/PCL2#3843]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在Mod管理→Mod列表中显示模组jar文件中的图标

### 原因

这项优化可以让一些没有被收录的模组显示自己的图标

**Comment by allMagicNB** [comment]
#2955
