### ISSUE TITLE
微软正版账号登录失败

### ISSUE THREAD

**Issue by yuleguren** [Hex-Dragon/PCL2#3845]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

突然登陆失败，之前快照版换了正式版后为题依旧，挂了梯子也没用。

### 重现步骤

点击登录失败
![image](https://github.com/Hex-Dragon/PCL2/assets/55691263/c5461ee6-9186-4633-9e57-f7c3c936cbd2)

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15360291/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/15360293/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/15360294/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/15360295/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/15360296/Log5.txt)

**Comment by allMagicNB** [comment]
#3018

**Comment by JingHai-Lingyun** [comment]
> 参见 #3018 

![image](https://github.com/Hex-Dragon/PCL2/assets/109946426/3c249602-8914-415f-b2ea-6855c8d35c94)
添加了默认开启的验证证书选项，请尝试关掉它，看看能不能得到改善……

**Comment by allMagicNB** [comment]
看看关掉那个选项能不能登录成功

**Comment by xxtg666** [comment]
（建议出现这个错误的时候加一个尝试关闭验证SSL证书选项的提示

**Comment by allMagicNB** [comment]
> （建议出现这个错误的时候加一个尝试关闭验证SSL证书选项的提示

你去交个 Issue 喽（

**Comment by yuleguren** [comment]
ok了 谢谢大伙
