### ISSUE TITLE
微软登录出现 SSL 错误时显示提示：尝试关闭 `验证 SSL 证书` 选项

### ISSUE THREAD

**Issue by xxtg666** [Hex-Dragon/PCL2#3846]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

当微软登录出现该错误后
```
微软登录尝试失败：网络请求失败（https://user.auth.xboxlive.com/user/authenticate，基础连接已经关闭: 未能为 SSL/TLS 安全通道建立信任关系。）
→ 基础连接已经关闭: 未能为 SSL/TLS 安全通道建立信任关系。
→ 根据验证过程，远程证书无效。
```
在错误信息下方提示用户可以尝试在设置中关闭选项 `验证 SSL 证书`

### 原因

这个功能有人不知道
https://github.com/Hex-Dragon/PCL2/issues/3845

**Comment by allMagicNB** [comment]
不太可能有重（

**Comment by xxtg666** [comment]
~才发现`待处理`标签改成`等待确认`了，我刚才还在想是什么意思（~

**Comment by allMagicNB** [comment]
> ~才发现`待处理`标签改成`等待确认`了，我刚才还在想是什么意思（~

~~曾经龙猫改 Label 时还给机器人搞炸了~~
