### ISSUE TITLE
微软账户登录页面无法加载

### ISSUE THREAD

**Issue by kong-que-dnf123** [Hex-Dragon/PCL2#3849]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

共同点：`错误：对象不支持”addEventListener“属性或方法`
我今天登陆的时候突然发生问题，有时在我对login网页进行交互是突然弹出，有时却又不会弹出，附上一些图
![image](https://github.com/Hex-Dragon/PCL2/assets/120994373/715d9f89-3109-4fb1-8c0f-77a9a6202f4e)
![image](https://github.com/Hex-Dragon/PCL2/assets/120994373/e4281c4e-c5c1-415f-b61d-621667c7cef9)
![image](https://github.com/Hex-Dragon/PCL2/assets/120994373/b12e3d76-c159-4d93-88a2-dc3b622444c9)
z诸如此类...

### 重现步骤

1、在正版登陆时选择新账户登录
2、直接点击登录，进入微软登录临时网页，随后报错

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15363207/Log1.txt)

**Comment by JingHai-Lingyun** [comment]
这个好像是原生 Webview 的 Bug，会无限循环报错……

**Comment by kong-que-dnf123** [comment]
>如果报错了的话关也关不掉，得强制结束 PCL 进程…… 还是看看用什么方式缓解一下好了

其实亲测叉掉三次（目前为止都是固定弹三次）报错窗口就不弹了就尬在白屏了........
![image](https://github.com/Hex-Dragon/PCL2/assets/120994373/0c78e0ee-ab35-499f-a9bb-149e6a52c55d)

**Comment by LTCatt** [comment]
微软更新了登录网页，新版网页已经不支持 WebBrowser 了，在 #122 完成前暂时强制使用浏览器登录

**Comment by XoidRaven** [comment]
> 微软更新了登录网页，新版网页已经不支持 WebBrowser 了，在 #122 完成前暂时强制使用浏览器登录

请问一下应该如何使用浏览器登录？

**Comment by JingHai-Lingyun** [comment]
> > 微软更新了登录网页，新版网页已经不支持 WebBrowser 了，在 #122 完成前暂时强制使用浏览器登录
> 
> 请问一下应该如何使用浏览器登录？

下一次更新之前手动点击窗口下面的按钮使用系统浏览器登录，下一次更新后自动切系统浏览器

**Comment by JingHai-Lingyun** [comment]
我也不知道下个版本什么时候发行，暂时先手动点一下吧

**Comment by XoidRaven** [comment]
> 我也不知道下个版本什么时候发行，暂时先手动点一下吧

额，手动点是什么意思？我不知道应该如何进行网页登录

**Comment by JingHai-Lingyun** [comment]
> 额，手动点是什么意思？我不知道应该如何进行网页登录

我电脑不在身边，没法截图
在跳出的登录窗口的最下面有一个用系统浏览器登录的按钮，点击即可
