### ISSUE TITLE
启动1.20.6(Fabric)时PCL自动选择了不支持的Java23

### ISSUE THREAD

**Issue by xtrackc1437** [Hex-Dragon/PCL2#3851]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在自动选择Java版本的情况下，下载安装JDK23(EA)和Fabric 1.20.6
启动游戏时，PCL自动选择了JDK23，随后游戏启动失败并报错“使用的Java版本过高”
观察日志发现PCL并未限制Java的最高版本，导致选择了不兼容的Java23
``
[00:22:23.518] [Launch] Java 版本需求：最低 1.21.0.0，最高 999.999.999.999
``
以及
```
[00:41:24.769] [Loader] 加载器 下载资源文件（主加载器） 状态改变：Finished
[00:41:24.890] [Java] Java 检查输出：E:\java\jdk-23\bin\java.exe
openjdk version "23-ea" 2024-09-17
openjdk runtime environment (build 23-ea+21-1723)
openjdk 64-bit server vm (build 23-ea+21-1723, mixed mode, sharing)

[00:41:24.890] [Java] 最终选定的 Java：JDK 23 (23.0.0)：E:\java\jdk-23\bin\
[00:41:24.890] [Launch] 选择的 Java：JDK 23 (23.0.0)：E:\java\jdk-23\bin\
[00:41:24.890] [Loader] 加载器 获取 Java 状态改变：Finished
```

### 重现步骤

启用自动选择Java
确认安装了Java23和Fabric1.20.6
启动游戏
游戏崩溃

在我的两台机器上均可复现
也许是JDK23还在测试版的原因，但是它确实使PCL2出bug了(
我的测试结果是1.20.6目前只支持Java21-22

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15366120/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/15366121/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/15366122/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/15366127/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/15366126/Log5.txt)

**Comment by LTCatt** [comment]
由于 JDK 23 尚在测试，无法确认正式版的兼容情况，所以当前的更改是：当同时安装 JDK 21 和 23 时，PCL 会优先选择 21 而非 23。
如果 JDK 23 正式版依然不兼容，到时候才会添加不选择 JDK 23 的处理 :/
