### ISSUE TITLE
程序出现未知错误：未将对象引用设置到对象的实例。

### ISSUE THREAD

**Issue by DrMerl** [Hex-Dragon/PCL2#3852]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在游戏设置中删除Mod（Chunk fade in，1.20.1，Fabric）时弹窗提示：“程序出现未知错误：未将对象引用设置到对象的实例。”然后启动器退出，但是重启启动器以后Mod已经被禁用了

### 重现步骤

1、点击游戏设置
2、点击Mod管理
3、在Mod搜索框里输入“Chunk”或其他什么东西（我不知道）
4、点击禁用第一个Mod，
5、完成

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/15366453/Log3.txt)

**Comment by DrMerl** [comment]
启动器重启以后这个bug就没了，不知道为什么

**Comment by lactobionicAcid** [comment]
#3816
