### ISSUE TITLE
PCL2启动器与Windows11系统极大不兼容

### ISSUE THREAD

**Issue by klmyjy** [Hex-Dragon/PCL2#3853]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在无论是否装载最新补丁的Windows11系统环境下，下载PCL2启动器后，无论是否使用过PCL启动器，无论将其放在桌面还是C盘某一专用文件夹（未尝试放在其他盘），无论是否将其对应安全中心报错条目设置为“允许在设备上”，都将导致PCL启动器被系统认为是存在木马而误删

### 重现步骤

1、下载PCL2启动器
2、将其放置入C盘中某一专用文件夹
3、打开Windows安全中心
4、进行快速扫描
5、将对应PCL2启动器的问题，即附件提到的Trogan;Win32/Wacatac.B!ml设置为“允许在设备上”
6、等待一段时间，该段时间内可以随意启动PCL2并游玩MC
7、再次进入上述专用文件夹，发现PCL已被清理
8、再次打开Windows安全中心将查看到如附件展示的典型病毒防护历史记录

### 日志与附件

PCL文件夹日志以及Windows系统安全中心典型病毒防护记录如下：
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/15366509/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/15366511/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/15366512/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/15366513/Log5.txt)
[Log.txt](https://github.com/Hex-Dragon/PCL2/files/15366514/Log.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15366515/Log1.txt)
![屏幕截图 2024-05-19 025308](https://github.com/Hex-Dragon/PCL2/assets/170201873/17cd5540-afc6-4af8-8512-fb883d743891)

**Comment by lactobionicAcid** [comment]
#666

**Comment by Michaelshenmo** [comment]
去#666看，这不是只是Windows 11的问题

**Comment by klmyjy** [comment]
识别码
