### ISSUE TITLE
由拖动条导致的页面滚动

### ISSUE THREAD

**Issue by lactobionicAcid** [Hex-Dragon/PCL2#3854]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

将鼠标光标移至拖动条时，设置页面会滚动以使其完整出现在可视范围里。
启动器的高为750px或略高于750px时会“碰巧”出现如下图GIF所示的情况。

![diagram](https://github.com/Hex-Dragon/PCL2/assets/115075633/0aae5c50-ccd8-47d8-be09-ba7b228184b0)

~~这...算bug吗...?~~
部分拖动条的滚动触发不灵敏。这可能是该issue下唯一需要修复的部分了吧......

### 重现步骤

滚动设置页面，使得滚动条被顶部工具栏或底部遮住一部分。之后，将鼠标光标移上去。

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15366825/Log1.txt)

**Comment by lactobionicAcid** [comment]
附：该bug与启动器窗口尺寸有关

**Comment by Dave12138** [comment]
只是鼠标移到“最大线程数”的范围里，自动让最大线程数这一项完整出现在可视范围里了吧

这……算bug吗……
