### ISSUE TITLE
Minecraft启动失败:解压文件失败  -→文件"E:\1.8.9pcl2\133\.minecraft\libraries\tv\twitchltwitch-external-platform\4.5\twitch-external- platform-4.5-natives-windows-64.jar"正由另一进程使用， 因此该进程无法访问此文件。

### ISSUE THREAD

**Issue by 11xiaoyu11** [Hex-Dragon/PCL2#3855]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃基本不是 PCL 的原因，请 **不要** 提交反馈。你可以在论坛或社区找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用 HMCL 启动，HMCL 没有出现问题。** 如果 HMCL 也无法启动就不是 PCL 导致的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

Minecraft启动失败:解压文件失败
-→文件"E:\1.8.9pcl2\133\.minecraft\libraries\tv\twitchltwitch-external-platform\4.5\twitch-external- platform-4.5-natives-windows-64.jar"正由另一进程使用， 因此该进程无法访问此文件。
在PCL.ModLaunch.McL aunchStart(L oaderTask 2 Loader)
在PCL.ModLaunch.McL aunchNatives(L oaderTask 2 Loader)
在PCL.ModL oader.L oaderTask' 2. Closure$__ 13-0._ Lambda$__ 0()
错误类型: [System.0.l0Exception

### PCL 错误报告、日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15367409/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/15367410/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/15367411/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/15367412/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/15367413/Log5.txt)
![1](https://github.com/Hex-Dragon/PCL2/assets/146637518/06af8303-a84d-4d77-b72a-0f945dc627bf)

**Comment by allMagicNB** [comment]
这个你自己装个 `IOBit Unlocker` 右键看看啥进程占用了再解除占用吧……

**Comment by JingHai-Lingyun** [comment]
呃……？
日志看到中央目录结尾缺失
```
[10:52:05.830] 打开 Natives 文件失败（E:\1.8.9pcl2\133\.minecraft\libraries\tv\twitch\twitch-external-platform\4.5\twitch-external-platform-4.5-natives-windows-64.jar）：找不到中央目录结尾记录。
   在 System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   在 System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
   在 PCL.ModLaunch.McLaunchNatives(LoaderTask`2 Loader)
错误类型：System.IO.InvalidDataException
```
我怀疑这个文件损坏了

**Comment by allMagicNB** [comment]
> 呃……？
> 日志看到中央目录结尾缺失
> ```
> [10:52:05.830] 打开 Natives 文件失败（E:\1.8.9pcl2\133\.minecraft\libraries\tv\twitch\twitch-external-platform\4.5\twitch-external-platform-4.5-natives-windows-64.jar）：找不到中央目录结尾记录。
>    在 System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
>    在 System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
>    在 PCL.ModLaunch.McLaunchNatives(LoaderTask`2 Loader)
> 错误类型：System.IO.InvalidDataException
> ```
> 我怀疑这个文件损坏了

主要又不是这个问题

**Comment by 11xiaoyu11** [comment]
> 这个你自己装个 `IOBit Unlocker` 右键看看啥进程占用了再解除占用吧……

![1](https://github.com/Hex-Dragon/PCL2/assets/146637518/26f68b0f-631d-4f93-b3fd-6abac7cd07db)

**Comment by allMagicNB** [comment]
> > 这个你自己装个 `IOBit Unlocker` 右键看看啥进程占用了再解除占用吧……
> 
> ![1](https://github.com/Hex-Dragon/PCL2/assets/146637518/26f68b0f-631d-4f93-b3fd-6abac7cd07db)
> 

你再启动下试试？

**Comment by 11xiaoyu11** [comment]
> > > 这个你自己装个 `IOBit Unlocker` 右键看看啥进程占用了再解除占用吧……
> > 
> > 
> > ![1](https://private-user-images.githubusercontent.com/146637518/331844865-26f68b0f-631d-4f93-b3fd-6abac7cd07db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwODk1MjQsIm5iZiI6MTcxNjA4OTIyNCwicGF0aCI6Ii8xNDY2Mzc1MTgvMzMxODQ0ODY1LTI2ZjY4YjBmLTYzMWQtNGY5My1iM2ZkLTZhYmFjN2NkMDdkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOVQwMzI3MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNGVjZTIyMDZjM2YxMDMwYzA4ZGM1NGFhM2NkZjhiZDI1YTI0MGEzZWY2NGUwYTFjZTU0YzFjYjlmMWM0YzkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ReTqYX0Pz7QMk36H3WVBPpOeaiJk8wJ1fpfHARzgdco)
> 
> 你再启动下试试？
> 
> > > 这个你自己装个 `IOBit Unlocker` 右键看看啥进程占用了再解除占用吧......
> > 
> > 
> > ![1](https://private-user-images.githubusercontent.com/146637518/331844865-26f68b0f-631d-4f93-b3fd-6abac7cd07db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwODk1MjQsIm5iZiI6MTcxNjA4OTIyNCwicGF0aCI6Ii8xNDY2Mzc1MTgvMzMxODQ0ODY1LTI2ZjY4YjBmLTYzMWQtNGY5My1iM2ZkLTZhYmFjN2NkMDdkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOVQwMzI3MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNGVjZTIyMDZjM2YxMDMwYzA4ZGM1NGFhM2NkZjhiZDI1YTI0MGEzZWY2NGUwYTFjZTU0YzFjYjlmMWM0YzkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ReTqYX0Pz7QMk36H3WVBPpOeaiJk8wJ1fpfHARzgdco)
> 
> 你 好 ， 下 一 个 ？

![1](https://github.com/Hex-Dragon/PCL2/assets/146637518/7e731c94-c1aa-4400-9837-e4464b95bf28)

**Comment by allMagicNB** [comment]
不对，试试用 HMCL 启动？

**Comment by JingHai-Lingyun** [comment]
应该是第一次访问文件发现损坏然后尝试第二次访问的时候报错了
试试看 HMCL 能否启动

**Comment by 11xiaoyu11** [comment]
> 应该是第一次访问文件发现损坏然后尝试第二次访问的时候报错了 试试看 HMCL 能否启动

用hmcl启动这个pcl2我刚刚错误的这个.minecraft嘛
![2](https://github.com/Hex-Dragon/PCL2/assets/146637518/eea1e67b-4760-447f-8ab8-dee2b035ef5f)

**Comment by allMagicNB** [comment]
是，选择相同版本启动

**Comment by JingHai-Lingyun** [comment]
啊这…… 你的本地库损坏了。应该还是之前那个文件导致的
或许你可以试试看重新安装一个相同的版本，看看还不会出现此问题，如果不会那就是网络问题导致文件不全

**Comment by 11xiaoyu11** [comment]
> 是，选择相同版本启动
![3](https://github.com/Hex-Dragon/PCL2/assets/146637518/08bbc486-9582-4e7f-9333-d08f63838363)
![4](https://github.com/Hex-Dragon/PCL2/assets/146637518/cb7ec422-feee-4c56-9903-f9524e287831)
我看以前的里面的大小不一样，这个有什么办法能解决吗，我现在只要新建就是240kb

**Comment by allMagicNB** [comment]
？

**Comment by kong-que-dnf123** [comment]
>我看以前的里面的大小不一样，这个有什么办法能解决吗，我现在只要新建就是240kb

请问可以把两个jar文件上传一下吗...

**Comment by 11xiaoyu11** [comment]
> > 我看以前的里面的大小不一样，这个有什么办法能解决吗，我现在只要新建就是240kb
> 
> 请问可以把两个jar文件上传一下吗...

[Uploading 1.zip…]()

**Comment by kong-que-dnf123** [comment]
> Uploading 1.zip…

额那个你没传上来...
用edit重新上传，等“Uploading”消失再发试试...

**Comment by LTCatt** [comment]
确实是文件损坏导致的，把报错的那个 jar 删了，PCL 会重新下载
