### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by joebidensss** [Hex-Dragon/PCL2#3857]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

Error occurred during initialization of boot layer
java.nio.file.InvalidPathException: Illegal char <?> at index 66: C:\Users\weiji\Downloads\No Flesh Within Chest-Beta 0.2.1-hotfix1 ???\.minecraft\libraries/cpw/mods/bootstraplauncher/1.1.2/bootstraplauncher-1.1.2.jar

一直无法登陆显示这个

### 重现步骤

1、点击xxxx
2、往下滚，然后点击xxxx

### 日志与附件

请问这个如何解决?

**Comment by zkitefly** [comment]
在 控制面板 -- 时钟和区域 -- 区域 -- 管理 -- 更改系统区域设置 里面上面选「中文（简体，中国）」，并且把下面那个勾去掉 https://gitcode.net/chearlai/kookfiles/-/raw/master/assets/2023-03/zsLRF3LrcD0we0hj.png

**Comment by wuliaodexiaoluo** [comment]
@LTCatt 看起来 Libraries 也受到影响了，要不和 Natives 一样切个目录？

**Comment by LTCatt** [comment]
这个不一定是中文字符导致的……
请反馈者补充日志和崩溃报告

**Comment by wuliaodexiaoluo** [comment]
那估计得等死了
大部分等待反馈者的 issue 都有一个通性：交完就跑

**Comment by LTCatt** [comment]
建议没事别水无意义内容

**Comment by allMagicNB** [comment]
如果仍无法启动，请上传错误报告

**Comment by Silverteal** [comment]
玩家所使用的原始整合包应该是：https://github.com/Yorunina/No-Flesh-Within-Chest/releases/tag/0.2.1  
此整合包没有问题，并可以通过最新快照版正确安装并启动。

**Comment by LTCatt** [comment]
由于一周未回复且无人复现暂时关闭，若有需要可以继续在这里回复
