### ISSUE TITLE
错误地将 1.20.1 的 mod 更新为 1.20.4 的版本

### ISSUE THREAD

**Issue by Spturate** [Hex-Dragon/PCL2#3859]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我在启动器里面有1.20.1 和 1.20.4 的Fabric端，用启动器的更新Mod功能给1.20.1更新完后发现Mod全下载到1.20.4的了。

以前的Snapshot 2.7.1(320.0)版本完全不会出现更新好的模组出现版本对不上的情况（貌似5.13之前的版本都没这个问题就最新的两个有），可以看看我这个录下来的视频：https://www.bilibili.com/video/BV1Ei421S7Gn/

### 重现步骤

1、点击版本设置
2、Mod管理
3、选中能更新的模组进行更新
4、下载到的模组版本和游戏版本对应不上

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/15368330/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/15368331/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/15368332/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/15368333/Log5.txt)
[Log.txt](https://github.com/Hex-Dragon/PCL2/files/15368334/Log.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15368335/Log1.txt)

**Comment by Dave12138** [comment]
乍一看还觉得是#3680 但好像又不是一回事
2.7.2为了解决一些下错mod的问题调整了一下项目匹配，可能是修出新bug了（
一定是Modrinth 干的乆

**Comment by allMagicNB** [comment]
还是先给龙猫看看吧（

**Comment by LTCatt** [comment]
具体是哪些 mod？举几个错误的例子也好……

**Comment by Dave12138** [comment]
> 具体是哪些 mod？举几个错误的例子也好……

他视频里最耀眼的一个：Fabric API
![](https://s2.loli.net/2024/05/19/nifcK67mbxYoNd1.webp)

最熟悉的一个：（（（呐）））
![](https://s2.loli.net/2024/05/19/WB5ngVkx2iMtsAF.webp)

**Comment by Spturate** [comment]
> 具体是哪些 mod？举几个错误的例子也好......

有太多了，钠全家桶，锂，masa全家桶，自然音效，FabricAPI，模组菜单这些

**Comment by LTCatt** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/a17fb9a0-a21c-448a-af59-e4efb386b7d5)
无法复现，并且上传的 log 里也没有使用 2.7.3 更新 mod 的……
如果能用 2.7.3 复现请上传对应 log。

**Comment by LTCatt** [comment]
与 #3680 是同一个 bug 导致
