### ISSUE TITLE
[BUG] 点进一个 MOD 的下载页面时，仍旧会显示“正在获取版本列表”

### ISSUE THREAD

**Issue by SuoHouDaiShi** [Hex-Dragon/PCL2#3861]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如图
![图片](https://github.com/Hex-Dragon/PCL2/assets/119282947/81c042e6-29f3-489c-8461-8321e4922383)
记得之前好像有一个类似的 Issue，但是搜不到了……
总的来说就是在某个 Mod 的下载页面中除了正常的描述之外，还有一个“正在获取版本列表”的卡片提示出现，并且是“死的”状态……

### 重现步骤

不是很清楚哦……可能是快速点击导致的？
1. 切换到“下载”选项
2. 点击“Mod”
3. 随便搜个 Mod，我这里搜的是`第三人称射击`
4. 等待加载完成
5. 连续点击某个 Mod，当该 Mod 拥有前置模组时大概率会出现

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15369123/Log1.txt)
可以直接定位到第 437 行查看……

**Comment by SuoHouDaiShi** [comment]
应该和 #3671 是类似的吧……
不确定，他是在 MOD 列表，我是在 MOD 下载页……
先看看其他人咋说（

**Comment by allMagicNB** [comment]
#1624
