### ISSUE TITLE
部分快照版 PCL 无法自动更新

### ISSUE THREAD

**Issue by Jkkoi** [Hex-Dragon/PCL2#3862]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

PPCCLL中的启动器自动更新失效  _似乎已经很多个版本了_
每次都需要手动点击更新才会更新

### 重现步骤

1. 启动器更新设置为 `有新版本时自动下载`

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15369262/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/15369263/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/15369264/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/15369265/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/15369266/Log5.txt)

**Comment by allMagicNB** [comment]
这玩意好多人都发现了，但是没人在意（

**Comment by Michaelshenmo** [comment]
+1

**Comment by wuwenjun9939** [comment]
我可能是因为内测版的问题，所以可能不会出现这个？还是说两个版本都不会有这个设定？我也开了自动更新的说

**Comment by Jkkoi** [comment]
@LTCatt 龙猫能否解锁个主题_(:3 」∠ )  D5AB-83B0-6CC3-7192

**Comment by LTCatt** [comment]
你的解锁码：4qTfS8mIr6cxP1MvXsb+OgbPJ8zt9SyZ
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by JingHai-Lingyun** [comment]
Reopen by #4656

**Comment by wuwenjun9939** [comment]
我的快照版也没更...
怀疑是龙猫只做了正式版的自动更新（雾）

**Comment by wuwenjun9939** [comment]
@LTCatt 龙猫？？？这个没看见吗？

**Comment by tangge233** [comment]
> 龙猫？？？这个没看见吗？

我知道你很急，但你先别急。龙猫不是全职开发 PCL2，不能及时回复消息，打上等待确认 Tag 一定会看的。

**Comment by LTCatt** [comment]
更新提示编号忘改了，好了

**Comment by Jkkoi** [comment]
@LTCatt 龙猫能否再解锁个主题（）更新系统后识别码似乎变了，主题全部西内，要重新解锁  90A0-9611-9DC6-77F2

**Comment by LTCatt** [comment]
识别码 90A0-9611-9DC6-77F2 的土豆码是：【CD11qQDww1OMwqktCAw804HXlraLZ52Fs/P30%i%UmPWrRUKZOwmJf8riU+UbQ7joi1tXi86BtsGlBhIGszPmNo%awpp#VGhlbWU5】
在【更多 → 关于与鸣谢 → 输入土豆码】中使用，谢谢支持～
