### ISSUE TITLE
联机

### ISSUE THREAD

**Issue by Cyrilwuwu** [Hex-Dragon/PCL2#3864]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

pcl2更新后联机功能消失

### 重现步骤

1、点击设置
2、点击启动器
3、往下滚，点击检查更新
4、点击更新

### 日志与附件

[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/15371197/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/15371198/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15371199/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/15371200/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/15371201/Log3.txt)

**Comment by zkitefly** [comment]
？

**Comment by allMagicNB** [comment]
早没了，甚至还被当作是个 Bug？
