### ISSUE TITLE
正版登录进入游戏后皮肤与所选不一致

### ISSUE THREAD

**Issue by justimpart** [Hex-Dragon/PCL2#3865]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

正版登录皮肤出错，进入游戏后皮肤变为官方皮肤kai

### 重现步骤

正版登录
进入游戏
皮肤为kai

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15374224/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/15374225/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/15374226/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/15374227/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/15374228/Log5.txt)

**Comment by wuliaodexiaoluo** [comment]
麻烦登陆下官网查看皮肤有没有被应用，如果是修改过的皮肤那就是API的问题了

**Comment by Silverteal** [comment]
这可能是因为您的网络存在问题，导致游戏本体未能从身份认证服务器获取正确的皮肤。如果是这样，启动器无法解决此问题。

**Comment by allMagicNB** [comment]
一般来说，这个是受网络影响的……先关了（
如果有任何证据能有效证明这不是网络问题，可以继续 Comment
