### ISSUE TITLE
[优化]优化操作文件失败时的报错

### ISSUE THREAD

**Issue by wuliaodexiaoluo** [Hex-Dragon/PCL2#3866]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

将应当标记为文件损坏的文件标记为文件损坏而不是显示为文件正在由另一进程使用中这一模糊且片面的解释

### 原因

这有可能影响自查和社区志愿者处理问题
Like #3855

**Comment by LTCatt** [comment]
文件损坏是极度罕见且难以复现的情况，一般不会对这种极罕见错误做额外的报错优化，特别是做了这个优化也解决不了问题的情况……
