### ISSUE TITLE
下载失败提示无法关闭

### ISSUE THREAD

**Issue by MinecraftSTL** [Hex-Dragon/PCL2#3870]
### 检查项

- [ ] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [ ] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我下载游戏失败后无法关闭失败提示，从而无法重新下载（可以重启解决）

识别码：D213-E0EB-782F-D699

### 重现步骤

下载一大堆游戏版本
失败其中n个
重新点击下载
\* 此时会触发bug1：重新下载仍然保留失败提示而不会显示进度
如果再次失败，新的失败提示无法被关闭（不确定是否每次都这样，还是看日志吧）

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/15377892/Log3.txt)
底下那几条其实是分卷压缩（因为单文件大小限制），但是文件名A (n).zip应该是A.zip.00n（因为后缀名限制），是一段演示视频
[QQ2024520-215046-HD.zip](https://github.com/Hex-Dragon/PCL2/files/15377930/QQ2024520-215046-HD.zip)
[QQ2024520-215046-HD (2).zip](https://github.com/Hex-Dragon/PCL2/files/15377932/QQ2024520-215046-HD.2.zip)
[QQ2024520-215046-HD (3).zip](https://github.com/Hex-Dragon/PCL2/files/15377933/QQ2024520-215046-HD.3.zip)
[QQ2024520-215046-HD (4).zip](https://github.com/Hex-Dragon/PCL2/files/15377934/QQ2024520-215046-HD.4.zip)
[QQ2024520-215046-HD (5).zip](https://github.com/Hex-Dragon/PCL2/files/15377935/QQ2024520-215046-HD.5.zip)

**Comment by allMagicNB** [comment]
#3007

**Comment by MinecraftSTL** [comment]
> #3007

其描述"只会在正常下载任务全部结束时关闭"与我所见到的现象不同，在其他下载项结束后仍然无法关闭

**Comment by allMagicNB** [comment]
> > #3007
> 
> 其描述"只会在正常下载任务全部结束时关闭"与我所见到的现象不同，在其他下载项结束后仍然无法关闭

你退出下载界面呢？

**Comment by allMagicNB** [comment]
~~算了先给龙猫看看~~

**Comment by allMagicNB** [comment]
![Image_1723864004208.png](https://github.com/user-attachments/assets/e8017d0f-064c-4715-94ee-0b5f04cd4d9c)
