### ISSUE TITLE
添加启动游戏时自动进入某一存档选项

### ISSUE THREAD

**Issue by Alpha-Qian** [Hex-Dragon/PCL2#3871]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

参考自动进入服务器功能，在版本设置中添加自动进入某一存档选项，可以在选择框中选择存档。开启后在首页启动游戏下面的 版本号 改为 存档名+版本号（不完全相同也行qwq）

### 原因

在玩整合包和对于由于模组适用版本不同一个版本一个存档的玩家很方便，目前还是正版启动器的独有的功能

**Comment by allMagicNB** [comment]
#1598

**Comment by allMagicNB** [comment]
#2551
