### ISSUE TITLE
1.7.2-Forge_10.12.2.1161版本提示需要Java7

### ISSUE THREAD

**Issue by MOJANG-Minecraft** [Hex-Dragon/PCL2#3873]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

启动1.7.2-Forge_10.12.2.1161版本时需要Java7并且点击自动安装也无法下载，最后提示没用可用的Java，已取消启动

### 重现步骤

1.先下载1.7.2-Forge_10.12.2.1161版本
2.启动它
3.提示需要Java7
4.点击自动安装也不能安装成功

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/15389876/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/15389877/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/15389879/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15389881/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/15389882/Log2.txt)

**Comment by allMagicNB** [comment]
龙猫估计是搞自动下载的时候忘了 Java 7.jpg

**Comment by zkitefly** [comment]
mojang 并没有提供 Java 7

**Comment by MOJANG-Minecraft** [comment]
> 龙猫估计是搞自动下载的时候忘了Java 7.jpg

为什么后缀是.jpg

**Comment by LTCatt** [comment]
umm 你的 ID 不适合放在更新日志里，你要不要换一个 ID……
