### ISSUE TITLE
增加根据mod筛选整合包的选项

### ISSUE THREAD

**Issue by LykaM3** [Hex-Dragon/PCL2#3874]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

在整合包下载页面中增加“包含....mod”的筛选项

### 原因

可以根据自己喜欢的一个或多个mod来查找包含了这些mod的整合包，方便快速寻找对自己胃口的整合包

**Comment by LTCatt** [comment]
技术上无法实现
