### ISSUE TITLE
登录账号弹窗显示脚本错误

### ISSUE THREAD

**Issue by loongkc** [Hex-Dragon/PCL2#3877]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

稳定触发，每次登录都会出现，与网络无关，试过开不开VPN都弹
<img width="374" alt="image" src="https://github.com/Hex-Dragon/PCL2/assets/103474466/8d54d46c-968a-4c78-92b8-486c55505aab">
点击“是”后弹出
![image](https://github.com/Hex-Dragon/PCL2/assets/103474466/57b6bf11-629c-47da-82c5-2a3cc06b2e31)
再次点击“是”
![image](https://github.com/Hex-Dragon/PCL2/assets/103474466/9211f94b-1b44-451e-8e5e-7288eb669fd3)
url改变，点击三次后不弹出，但是微软账户登录界面是白的

### 重现步骤

1、点击登录
2、弹出Microsoft账户登录
3、弹出脚本错误

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/15398236/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/15398237/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/15398238/Log4.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15398239/Log1.txt)

**Comment by allMagicNB** [comment]
#3849
