### ISSUE TITLE
离线启动变成新人物，成就统计数据全部丢失

### ISSUE THREAD

**Issue by Tomalisa** [Hex-Dragon/PCL2#3879]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在启动器自动更新2.7.3之前：
离线启动，设置-离线皮肤-Alex，进入游戏后是经典Steve皮肤和大小，玩了很久

在启动器自动更新2.7.3之后：
离线启动，设置-离线皮肤-Alex，进入游戏后是一个机械手臂的黑人一样的东西，成就全部丢失，所有统计数据全部消失，给我恶心吐了；切换Steve 进入游戏后是Slim版Steve，一样全部数据丢失；切换随机，进入游戏后还是Slim版Steve，数据成就全部丢失。

角色名字没有变动过。
需要立刻解决此问题

### 重现步骤

1. 更新2.7.3
2. 复现完毕

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/15405276/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/15405277/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/15405278/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15405279/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/15405280/Log2.txt)

**Comment by allMagicNB** [comment]
什么游戏版本？

**Comment by Tomalisa** [comment]
1.20.1，上次启动就在几天前启动器没更新的时候，一直没问题，这次启动器更新之后出现的这个问题。

**Comment by allMagicNB** [comment]
咋感觉是 UUID 刷新了……

**Comment by allMagicNB** [comment]
不对，应该是 UUID 的生成规则变了
你是否有通过其它启动器启动过游戏？

**Comment by Tomalisa** [comment]
没有用其他启动器启动这个版本，我只用官方启动器启动过bedrock edition，这个版本是1.20.1 fabric，只用PCL2启动

**Comment by LTCatt** [comment]
看完了……
简单地说，这是由于原本的代码存在 bug（#3343），导致 2.7.1 生成的 UUID 实际上是错误的，在 2.7.2 修复这个 bug 后导致了 UUID 变化，所以这个 issue 没有办法被 “修复”，真的非常抱歉。

------

### 技术信息

如果默认 UUID 不符合性别条件，会触发截断处理。老代码在截断最后 5 位 ID 时的处理有问题，导致 UUID 丢失了一位 0。
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/ed7b9d15-3b5d-4883-ae6d-a50e1a146bbc)
如果这个错误的 UUID 符合性别条件，就会触发 #3343，导致游戏无法启动。
如果不符合性别条件，它会再次触发截断。但因为位数错误，将倒数第六位的 `F` 给放进了 UUID 中，错误地把倒数第五位的 0 变成了 F。
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/b3c4a57f-17c6-4b5c-bb04-7f47c7f55596)
但它却恰好又是一个合法的 UUID，#3343 没有触发，可以进入游戏。

在 2.7.2 中，这个错误截断的 bug 被修复了，使得部分 ID 在进入游戏时不会崩溃。但在本 issue 下，也导致原本错误地出现的 F 变成了正确的 0，UUID 发生了变化。
这是无法修复的，因为 “修复” 只能把现在正确的处理改成原本错误的处理……

------

### 影响面

很不幸，这是一个极端罕见的情况，仅当同时满足这些条件才会触发：
· 离线启动（按 60% 计）
· 使用 Steve/Alex 离线皮肤（按 20% 计）
· 第一次生成没有满足性别条件，导致进入错误的截断代码（1/2）
· 生成的倒数第五位 UUID 恰巧为 0，导致截断后 UUID 有误（1/16）
· 第二次生成依然没有满足性别条件，导致第三次 UUID 合法，但实际生成错误（1/2）

也就是说，预估只有 0.2% 不到的玩家会触发这个问题……

**Comment by allMagicNB** [comment]
有这运气，推荐去买彩票……

**Comment by Tomalisa** [comment]
我直接原地去世，不过这算法不好说，下面是身边科学统计：离线我觉得占比会比较多，因为我之前玩多人服务器的时候就是会用好多小号在不同地点当工具人，全服也是很多人这么用，然后Steve Alex 这个是离线默认选择的，工具人不会有人闲的去挑皮肤，其他的都差不都了。

**Comment by Tomalisa** [comment]
所以能不能修改这个UID让它变回我以前的那个，还是说被覆盖了无法返回了

**Comment by LTCatt** [comment]
因为目前 PCL 不支持自定义离线 UUID（#169），你可以尝试手动把存档文件夹里所有名字是老 UUID（000......F28C7）的文件重命名成新 UUID（000......028C5），这能恢复一部分进度……

**Comment by Tomalisa** [comment]
已经把advancements, playerdata, stats里面的文件替换完毕了，现在用正版账号继承进度，仍有个问题是离线Alex皮肤不是Alex本体，离线Steve是Slim Steve，这是feature还是bug？

**Comment by LTCatt** [comment]
新版离线皮肤使用 Steve/Alex 的行为并不清楚， #1288

**Comment by Tomalisa** [comment]
发现一个非常恐怖的事实，除了我的马、骆驼、羊驼（？）外，我的其他宠物（鹦鹉 狗 猫 等）全部不是我的宠物了，他们的主人已经消失了 现在我已经不能命令他们了，但是我是完全复制我的旧人物信息 为什么宠物不会认我呢？

**Comment by WorldHim** [comment]
> 发现一个非常恐怖的事实，除了我的马、骆驼、羊驼（？）外，我的其他宠物（鹦鹉 狗 猫 等）全部不是我的宠物了，他们的主人已经消失了 现在我已经不能命令他们了，但是我是完全复制我的旧人物信息 为什么宠物不会认我呢？

因为你的 uuid 改变了

**Comment by leyi-1** [comment]
我也遇到了，就离谱
