### ISSUE TITLE
PCL预览版不能读取之前的世界存档

### ISSUE THREAD

**Issue by fsmy1024** [Hex-Dragon/PCL2#3880]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在PCL2快照版中启动游戏后没有之前的存档，但在正式版启动可以看到。（选择的是同一个文件地址的版本，saves文件夹里也有之前的存档）

### 重现步骤

1、点击任意版本
2、启动，点击单人游戏后可以看到只有创建世界选项

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15410825/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/15410826/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/15410827/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/15410828/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/15410829/Log5.txt)

**Comment by allMagicNB** [comment]
你开没开版本隔离？

**Comment by allMagicNB** [comment]
不对，请仔细阅读版本隔离选项的解释
