### ISSUE TITLE
整合包导入失败

### ISSUE THREAD

**Issue by wavekoo** [Hex-Dragon/PCL2#3887]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

1.将整合包拖入pcl2窗口时提示无法确定执行的文件拖拽操作
2.在版本选择里导入整合包显示未能识别整合包种类
![IMG_20240524_143209](https://github.com/Hex-Dragon/PCL2/assets/170703949/08b77429-c966-4fac-8c09-2c592a598533)
![IMG_20240524_143224](https://github.com/Hex-Dragon/PCL2/assets/170703949/ff8b2685-3312-41aa-95f4-7f4987ed39ab)

### 重现步骤

1、点击xxxx
2、往下滚，然后点击xxxx

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/15428777/Log3.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15428778/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/15428779/Log2.txt)

**Comment by HomoobyDX** [comment]
你尝试打开压缩包看看里面的结构，把压缩包内部截个图发到这里

**Comment by wavekoo** [comment]
![Uploading IMG_20240524_162823.jpg…]()
