### ISSUE TITLE
游戏崩溃

### ISSUE THREAD

**Issue by eueutbu** [Hex-Dragon/PCL2#3888]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃基本不是 PCL 的原因，请 **不要** 提交反馈。你可以在论坛或社区找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用 HMCL 启动，HMCL 没有出现问题。** 如果 HMCL 也无法启动就不是 PCL 导致的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

游戏崩溃

### PCL 错误报告、日志与附件

[PCL2 启动器日志.txt](https://github.com/Hex-Dragon/PCL2/files/15431796/PCL2.txt)
[游戏崩溃前的输出.txt](https://github.com/Hex-Dragon/PCL2/files/15431797/default.txt)

**Comment by zkitefly** [comment]
发送**完整**的错误报告

**Comment by wuliaodexiaoluo** [comment]
看报错感觉像是是 mod 的 mixin 炸了，又感觉像是前置没装
这应该不是启动器问题

**Comment by allMagicNB** [comment]
```
[19:10:47.858] [Launch] 版本文件夹：E:\Utopian journey 3.0\versions\乌托邦探险之旅3.0\
```
![Screenshot_20240524_190529.jpg](https://github.com/Hex-Dragon/PCL2/assets/116283787/18017ba5-3fc8-4903-abd2-37057a76aebc)

**Comment by JingHai-Lingyun** [comment]
呃，既然如此……
如果你有需要的话，请移步 Discussion 大区开启讨论贴寻求支持（[快捷链接](https://github.com/Hex-Dragon/PCL2/discussions/new?category=%E6%8F%90%E9%97%AE)）
