### ISSUE TITLE
添加模组更新日志

### ISSUE THREAD

**Issue by HomoobyDX** [Hex-Dragon/PCL2#3889]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

某次更新模组列表时发现PCL只会显示正在更新模组不会告诉具体更新了哪些模组，如果因更新模组后导致了崩溃，导致用户不知道更新了哪些模组导致的问题，又要挨个排查等。如果加个模组更新菜单，可以清晰知道更新了哪些模组，崩溃后也知道是更新了哪些模组导致的崩溃

### 原因

让用户使用模组更新功能时知道更新了哪些模组，如果更新模组后出现问题可以更好的排查

**Comment by allMagicNB** [comment]
#679

**Comment by allMagicNB** [comment]
筛选下不就只有可更新的 Mod 了嘛（

**Comment by JingHai-Lingyun** [comment]
该作者貌似是希望加一个类似 ”模组更新历史“ 的玩意？

**Comment by LTCatt** [comment]
用途比较小，并且实际上可以从 log 或者回收站里看更新了哪些……暂时不考虑制作，抱歉 orz
