### ISSUE TITLE
复制错误信息

### ISSUE THREAD

**Issue by zhiqin14** [Hex-Dragon/PCL2#3890]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在mc错误崩溃后在错误分析窗口添加一个按钮复制错误信息

### 原因

在错误信息是英文的时候就可以便捷地复制信息放到翻译网站上，而不是自己手敲

**Comment by Pigeon0v0** [comment]
点查看日志
