### ISSUE TITLE
最新版2.7.3内存优化机制的问题

### ISSUE THREAD

**Issue by Hlwyefeng** [Hex-Dragon/PCL2#3891]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

2.7.3更新内存优化之后，在mod较多的整合包中，内存回收从以前不停的回收，变成了现在到一定阈值进行一次清理
在以前的回收机制，内存回收时low帧虽然会降低，但是也是趋于平稳的状态
新版的内存回收变成到阈值才清理之后，low帧确实提高了很多，但是在一些需要大量内存的整合包里，每次内存清理的时候就是游戏顿卡的时候，low帧会瞬间降到个位数，体验极差

### 原因

我更倾向于旧版的内存回收机制，或者说可以让用户进行选择
甚至出一个调整内存清理的阈值的选项，那些玩低版本的玩家，一般都是用着java8，内存在回收的时候low帧是非常低的，整体感觉上就是不流畅，高版本用新版java的体验就稍微好很多

**Comment by Hlwyefeng** [comment]
我有空录个对比视频

**Comment by JingHai-Lingyun** [comment]
#1874 修改了 Java 内存相关参数，这使 GC 的频率降低了

**Comment by Hlwyefeng** [comment]
> #1874修改了Java 内存相关参数，该GC 频率降低。 你指的是GC的时候会严重掉帧嘛
差不多吧，第一种的gc方法，虽然low帧低但是很平稳，新版的low帧稳定高了一倍多，但是一次性大幅清理内存导致掉帧严重

**Comment by LTCatt** [comment]
把 Xmx 从 50% 调整到了 15%
