### ISSUE TITLE
[BUG] 设置外置登录时的输入框错位；PCL 窗体在屏幕之外时下拉框错位

### ISSUE THREAD

**Issue by SuoHouDaiShi** [Hex-Dragon/PCL2#3896]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

折腾整合包的时候无意发现的……
![图片](https://github.com/Hex-Dragon/PCL2/assets/119282947/edd5a6f4-0942-4cbc-a2c4-5b020e184210)
将登录方式调整为`外置登录`就没有了这个问题
![图片](https://github.com/Hex-Dragon/PCL2/assets/119282947/794fc935-da4c-4a97-9f35-bece7c7ecbe4)
另外：
当 PCL 的一部分窗口位于屏幕之外时，会出现：
![图片](https://github.com/Hex-Dragon/PCL2/assets/119282947/32f532bc-c45c-4192-9705-70a7892cc6ee)
· ---
经过测试，发现 PCL 快照版 2.7.3 也同样存在此问题：
![图片](https://github.com/Hex-Dragon/PCL2/assets/119282947/41ecf8f2-4f28-4adc-bdaf-df0d336c4b2e)
![图片](https://github.com/Hex-Dragon/PCL2/assets/119282947/62aeb2d6-1ef9-413f-8ef5-01cbd02d963d)

### 重现步骤

BUG 1：
1.将某版本的登录方式改为`外置登录`
2.设置任意一个有效的外置验证服务器
3.返回
4.重新回到刚才的页面
5.将版本登录方式修改为`仅正版登录`
6.BUG 出现
· ---
BUG 2：
1.将 PCL 的部分窗体拖到屏幕之外
2.进入版本设置，将选择登录方式的下拉框点开
3.BUG 出现

### 日志与附件

[内测版 Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15442606/Log1.txt)
[正式版 Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15442636/Log1.txt)

**Comment by allMagicNB** [comment]
首先，那下拉框是为了让用户能够看到全部内容，不算 Bug 吧……

**Comment by LTCatt** [comment]
WPF 的 bug，无法修复（和窗口自定义大小的文本框错位是同一个 bug）
