### ISSUE TITLE
增加⌈主页面⌋按钮

### ISSUE THREAD

**Issue by 596wjr** [Hex-Dragon/PCL2#3897]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

如果打开了一个UI，比如下载模组页面，这时在左上角返回上一级右侧增加一个返回主页面的按钮

### 原因

比如说我点进了版本管理的Mod管理，右键某个模组，然后他需要一个前置，这个前置有需要另一个模组作为前置，然后我发现这个前置没有更新或者说别的什么原因，这时候我得点4次返回才能回到主菜单

**Comment by allMagicNB** [comment]
感觉适用面有点小……
可以改成长按返回键返回主页面（

**Comment by LTCatt** [comment]
目前我没有充裕时间制作用途不足够大的功能，抱歉
