### ISSUE TITLE
在PCL2中集成frp，实现在无公网IP条件下联机效果

### ISSUE THREAD

**Issue by CNZW-WTW** [Hex-Dragon/PCL2#3899]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

之前在上课的时候我就在想，PCL2怎么样才能实现在没有公网IP的条件下实现联机功能，想到了我的服务器也没有公网IP地址，是通过内网穿透实现公网访问的，所以我觉得PCL2可以内置frp或添加下载frp的功能，并在上方添加内网穿透的功能，设置好配置文件和启动命令后，可以一键启动frp内网穿透，因为平时我们使用frp时还需要另开一个cmd窗口，不够美观和简洁，集成到PCL2中就可以在调整好配置后快速启动，省去输命令的麻烦，一劳永逸
![微信截图_20240525205246](https://github.com/Hex-Dragon/PCL2/assets/146963503/002a5637-ff46-438d-b914-0278e5225883)

### 原因

我需要这个功能来**方便快速地联机**。很多人都有联机的需求，但如果没有这个功能，就不能和好朋友酣畅淋漓的⚦玩耍⚦(只能用史一样的冈易)了。

**Comment by JingHai-Lingyun** [comment]
#2128

**Comment by Deep-Dark-Forest** [comment]
PCL **不会**随意内置第三方程序……

**Comment by CNZW-WTW** [comment]
因为不同的内网穿透启动命令都不一样，所以如果添加这个功能，一定要可以自定义启动命令

**Comment by allMagicNB** [comment]
> PCL **不会** 随意内置第三方程序……

那你这话说的，仔细考虑下还行喽？

**Comment by allMagicNB** [comment]
这是 Plain Craft Launcher 2，不是 FRP Craft Launcher 2

**Comment by wuliaodexiaoluo** [comment]
> 因为不同的内网穿透启动命令都不一样，所以如果添加这个功能，一定要可以自定义启动命令

那个启动启动前执行命令就可以吧。。。
frpc 不会因为连不上炸掉的说

**Comment by wudiwudidream** [comment]
套框架可以

**Comment by wudiwudidream** [comment]
要授权的，有风险

**Comment by wudiwudidream** [comment]
况且如果说是官方整的内置联机分分钟把人整崩溃（局域网联机，网络强度差非常痛苦，7000多ms）

**Comment by allMagicNB** [comment]
@wudiwudidream 请一次性把话说完。

**Comment by wudiwudidream** [comment]
OK，不贱了，可以参考Python的socket，如果是java编写找类似的或者直接Python方便点，这要看每个版本游戏传输文件数量的最小值决定建立连接（这个操作无需其他，直接内网穿透效果，你的电脑=服务器，其他人电脑是发送者）

**Comment by wudiwudidream** [comment]
package cn.juwatech.network;

import java.io.*;
import java.net.*;

public class Server {
   

    public static void main(String[] args) {
   
        try {
   
            ServerSocket serverSocket = new ServerSocket(8080);
            System.out.println("服务器已启动，等待客户端连接...");

            // 等待客户端连接
            Socket clientSocket = serverSocket.accept();
            System.out.println("客户端已连接，地址：" + clientSocket.getInetAddress());

            // 获取输入流，读取客户端发送的数据
            BufferedReader reader = new BufferedReader(new InputStreamReader(clientSocket.getInputStream()));
            String message = reader.readLine();
            System.out.println("收到客户端消息：" + message);

            // 发送响应给客户端
            PrintWriter writer = new PrintWriter(clientSocket.getOutputStream(), true);
            writer.println("已收到消息：" + message);

            // 关闭流和连接
            writer.close();
            reader.close();
            clientSocket.close();
            serverSocket.close();

        } catch (IOException e) {
   
            e.printStackTrace();
        }
    }
}
java示例

**Comment by wudiwudidream** [comment]
package cn.juwatech.network;

import java.io.*;
import java.net.*;

public class Client {
   

    public static void main(String[] args) {
   
        try {
   
            Socket socket = new Socket("localhost", 8080);
            System.out.println("连接到服务器...");

            // 发送消息给服务器
            PrintWriter writer = new PrintWriter(socket.getOutputStream(), true);
            writer.println("Hello, Server!");

            // 接收服务器响应
            BufferedReader reader = new BufferedReader(new InputStreamReader(socket.getInputStream()));
            String response = reader.readLine();
            System.out.println("服务器响应：" + response);

            // 关闭流和连接
            writer.close();
            reader.close();
            socket.close();

        } catch (IOException e) {
   
            e.printStackTrace();
        }
    }
}
不过相比来说，这个是官方网络连接联机常用的代码，但是没有Python socket牛，这么点算java socket全部，还没Python socket内容那个大，因为本身就是可以用来爬东西的

**Comment by wudiwudidream** [comment]
所以十分丰富

**Comment by Pigeon0v0** [comment]
#1930
