### ISSUE TITLE
在版本mod界面更新mod时未联网，无法再进入mod界面

### ISSUE THREAD

**Issue by DownsStirp** [Hex-Dragon/PCL2#3900]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在未联网的情况下选择mod更新，mod管理界面会长期提示正在更新mod，但未提示更新失败；退出重进后仍旧提示正在更新mod，无法管理mod；重新联网后仍旧无法解决！！（如图）
![bug](https://github.com/Hex-Dragon/PCL2/assets/123857718/ea47cfce-b865-4fb6-96a3-390fd75f12bd)

https://github.com/Hex-Dragon/PCL2/assets/123857718/e5b0ea93-be4f-496e-9b79-0054d01b31b3

### 重现步骤

1、打开一个游戏的版本设置
2、打开mod管理
3、在断网的情况下选择一个mod进行更新

### 日志与附件

[log.zip](https://github.com/Hex-Dragon/PCL2/files/15443732/log.zip)

**Comment by DownsStirp** [comment]
现在好像又卡不出来了

**Comment by DownsStirp** [comment]
貌似要在网速极低的情况下才会出现

**Comment by Deep-Dark-Forest** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/131975043/6f4e9957-1fe2-44d2-8c79-13c2ec160bff)
根本没法复现啊...

**Comment by Silverteal** [comment]
您的问题可能为：Mod更新不能直观地取消。
如果您再次遇到类似的问题，请尝试点击“Mod管理”旁的刷新按钮，或者重新启动启动器。

**Comment by LTCatt** [comment]
由于无人能复现暂时关闭。
