### ISSUE TITLE
模组更新

### ISSUE THREAD

**Issue by rjdxxxxxccc** [Hex-Dragon/PCL2#3901]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

能不能出一个禁止指定模组更新的功能，每次更新都要取消勾选，在模组文件多的整合包中特别麻烦

### 原因

（示例）
这项优化让我可以更方便地禁止个别模组的更新。
如果没有这项优化，我每次都必须一个个挑出来取消勾选，让操作变得很麻烦。

**Comment by Deep-Dark-Forest** [comment]
> 如果没有这项优化，我每次都必须一个个挑出来取消勾选，让操作变得很麻烦。

？你是指全选以后又取消不想更新的 mod？

**Comment by LTCatt** [comment]
暂时不考虑，用途不是很宽泛，目前没有太多时间制作，抱歉
