### ISSUE TITLE
下载管理启动线程 0 出错：集合已修改；可能无法执行枚举操作

### ISSUE THREAD

**Issue by adsioho** [Hex-Dragon/PCL2#3902]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [ ] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

日志：
[10:02:25.931] 下载管理启动线程 0 出错：集合已修改；可能无法执行枚举操作。
   在 System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   在 System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   在 System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   在 PCL.ModNet.NetManagerClass._Lambda$__18-0(Int32 Id)
错误类型：System.InvalidOperationException
[10:02:30.163] [System] 诊断信息：
操作系统：Microsoft Windows 10 专业版
剩余内存：26726 M / 32578 M
DPI：96（100%）
MC 文件夹：F:\MC\.minecraft\
文件位置：F:\MC\
[10:02:30.164] [System] 执行外部命令：explorer.exe "F:\MC\PCL\"
[10:02:30.182] [System] 正在打开网页：https://github.com/Hex-Dragon/PCL2/issues/
[10:02:30.200] [System] 程序已退出，返回值：Fail

### 重现步骤

下载Puzzles lib和卓越火炬时出现的（同时下两个）（尝试多遍后无法复现）
虽然issue里有人提到过，但是似乎没有说明解决方法
pcl版本是正式版2,7,3

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15445781/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/15445782/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/15445783/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/15445784/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/15445785/Log5.txt)

**Comment by allMagicNB** [comment]
#3771

**Comment by allMagicNB** [comment]
emm，要解决的话，等正式版更新或者尽量不要一次性下太多 Mod（

**Comment by adsioho** [comment]
2个也不算多吧。。。况且log1里说了剩余文件 1

**Comment by allMagicNB** [comment]
这是极小概率事件，你能连续多次复现吗（
