### ISSUE TITLE
PCL2无法获取除MC本体外的版本列表

### ISSUE THREAD

**Issue by ASSR-ASS** [Hex-Dragon/PCL2#3903]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/Hex-Dragon/PCL2/assets/129626415/25adcea5-51aa-4b06-83f5-228f8c6c832e)
如图，PCL2无法获取除MC本体外的版本列表，（对于mod则modrinth侧有时无法获取或速度很慢，curseforge速度较慢但绝大多数时候能获取）只能下载和安装MC本体（速度极慢且下载速度一直显示为0）（两个启动器都是镜像源优先）
HMCL速度较慢，但是可以下载及安装MC及其附件，以及两个来源的mod

BakaXL直接无法使用（不和PCL2同时运行） #https://github.com/BakaXL-Launcher/BakaXL/issues/684

### 重现步骤

1、点击下载
2、
![image](https://github.com/Hex-Dragon/PCL2/assets/129626415/f8f01ff9-b136-4c32-bc29-227a7a08b1f7)
3、
![image](https://github.com/Hex-Dragon/PCL2/assets/129626415/1d8a7dfa-da04-4448-a050-fec4097af72b)
4、
![image](https://github.com/Hex-Dragon/PCL2/assets/129626415/f3b7b17a-0837-4fb0-9988-5352d946e220)
5、
![image](https://github.com/Hex-Dragon/PCL2/assets/129626415/b6f55612-2dbb-4a94-bcf0-f5c889d257a9)

### 日志与附件

https://github.com/ASSR-ASS/Temp-repo-for-files/blob/main/Github_issue-PCL2%E6%97%A0%E6%B3%95%E8%8E%B7%E5%8F%96%E9%99%A4MC%E6%9C%AC%E4%BD%93%E5%A4%96%E7%9A%84%E7%89%88%E6%9C%AC%E5%88%97%E8%A1%A8/Log1.txt
_在issue页面上传文件会消失=(_
_目录里只有log1_
![image](https://github.com/Hex-Dragon/PCL2/assets/129626415/f2255b75-34ca-42aa-ae9e-ed418459ebfd)

**Comment by allMagicNB** [comment]
像是 DNS 的问题

**Comment by hejiehao** [comment]
似乎是网络问题

**Comment by kong-que-dnf123** [comment]
~ 会不会是镜像源单方面炸了...? ~

**Comment by allMagicNB** [comment]
不管了先加个 `待处理`（

**Comment by LTCatt** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/d0f7c268-63b8-40f5-808f-712e17d153dd)
网络问题，啥都连不上
