### ISSUE TITLE
下载失败

### ISSUE THREAD

**Issue by xxccpp** [Hex-Dragon/PCL2#3904]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

下载失败，下载fabic和原版都不行，1.20.6也不行
报错
下载原版 1.20.1失败
→ 下载原版资源文件失败
→ 下载资源文件（副加载器）失败
→ 文件下载失败：D:\minecreaft\.minecraft\assets\objects\51\5100825275b5d57496ffb4b78c2e9a5904077c90
https://bmclapi2.bangbang93.com/assets/51/5100825275b5d57496ffb4b78c2e9a5904077c90
https://resources.download.minecraft.net/51/5100825275b5d57496ffb4b78c2e9a5904077c90
→ 文件大小应为 456868 B，实际为 416 B
   在 PCL.ModNet.NetFile.Merge()

### 重现步骤

下载1.20.1即出现

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15446454/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/15446455/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/15446456/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/15446457/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/15446458/Log5.txt)

**Comment by allMagicNB** [comment]
你打开下这个网址 https://bmclapi2.bangbang93.com/assets/51/5100825275b5d57496ffb4b78c2e9a5904077c90 ，然后截屏下

**Comment by xxccpp** [comment]
打开后开始下载文件
![image](https://github.com/Hex-Dragon/PCL2/assets/146406737/04ead4b1-733b-4ee7-ad18-4b6c316e7a45)

**Comment by allMagicNB** [comment]
> 打开后开始下载文件
> ![image](https://github.com/Hex-Dragon/PCL2/assets/146406737/04ead4b1-733b-4ee7-ad18-4b6c316e7a45)
> 

然后再试试下载呢？

**Comment by xxccpp** [comment]
没问题了

**Comment by allMagicNB** [comment]
？

**Comment by xxccpp** [comment]
已经可以下载运行了，不清楚什么情况

**Comment by LTCatt** [comment]
需要 2.7.3+ 调试模式下的复现 log，疑似是部分 OpenBMCLAPI 源返回了错误的信息导致。

**Comment by LTCatt** [comment]
由于反馈者本人无法复现，且无其他人能复现，暂时关闭
