### ISSUE TITLE
支持修改后版本的Minecraft启动

### ISSUE THREAD

**Issue by Mineqcycode** [Hex-Dragon/PCL2#3905]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

在启动界面里新建选项"启动其他版本"，用来启动类似于 Error422 等其他严重修改后的版本

### 原因

错误版本的Minecraft无法通过PCL启动，启动参数无法完全修改

**Comment by allMagicNB** [comment]
你这还不如整个脚本自己参数拼接来启动呢

**Comment by zkitefly** [comment]
这个版本可以在哪里获取我想了解一下

**Comment by JingHai-Lingyun** [comment]
> 错误版本的Minecraft无法通过PCL启动，启动参数无法完全修改

如果手动配置
![image](https://github.com/Hex-Dragon/PCL2/assets/109946426/15d7a7c3-a045-4bdc-a62f-781854e5cd53)
呢？

**Comment by burningtnt** [comment]
你到底要改多少东西…… 绝大部分都能够通过修改 version json 实现

**Comment by allMagicNB** [comment]
![Screenshot_20240526_161024_com.github.android.jpg](https://github.com/Hex-Dragon/PCL2/assets/116283787/60fc1d94-7f8a-4d6d-adcb-4f7df0bf2dff)

这描述是不是有点问题（

**Comment by LTCatt** [comment]
暂时不考虑支持特殊版本，若有特殊需求可以自己修改 PCL\LatestLaunch.bat，抱歉

**Comment by allMagicNB** [comment]
不对，这玩意双击 EXE 文件就能启动了啊……
