### ISSUE TITLE
"....会无法进入 Minecraft 1.18 以前的世界"写成了”....会无法进入 Minecraft 1.18 以后的世界“

### ISSUE THREAD

**Issue by scattered-leaves** [Hex-Dragon/PCL2#3907]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

![image](https://github.com/Hex-Dragon/PCL2/assets/121725066/06c44527-785c-431b-b94a-88567a689f83)
就写错字了

### 原因

写错字了

**Comment by LBZiXL** [comment]
没写错呀

**Comment by hejiehao** [comment]
确实应该是以后

**Comment by scattered-leaves** [comment]
不应该是以前吗

**Comment by LBZiXL** [comment]
> 不应该是以前吗

你要不自己试试

**Comment by scattered-leaves** [comment]
记错了，抱歉打扰了
