### ISSUE TITLE
Fabric安装器出现问题

### ISSUE THREAD

**Issue by xjsCHINA** [Hex-Dragon/PCL2#3909]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

手动安装中的Fabric 0.6.0.42&0.6.0.41下载会出现服务器报错(404)

### 重现步骤

1、PCL打开手动安装
2,  选择Fabric 0.6.0.42&0.6.0.41,下载

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15447888/Log1.txt)
![螢幕擷取畫面 2024-05-26 225043](https://github.com/Hex-Dragon/PCL2/assets/170874958/d67575f6-0d78-4be9-990a-3adedf533f6a)

**Comment by Deep-Dark-Forest** [comment]
像是bmclapi炸了……

**Comment by zkitefly** [comment]
> 像是bmclapi炸了……和PCL关系不大
> @xjsCHINA 你试一下其他启动器比如 HMCL 或者 BakaXL安装相同的fabric版本？

这个是 fabric 安装器

**Comment by zkitefly** [comment]
![Screenshot_2024-05-27-12-56-49-66_df198e732186825c8df26e3c5a10d7cd.jpg](https://github.com/Hex-Dragon/PCL2/assets/64117916/3a02f778-45d9-4fe5-9925-543523c79cef)


不是 PCL 的问题，maven 中并没有 jar 格式的安装器

**Comment by xjsCHINA** [comment]
> 像是bmclapi炸了......和PCL关系不大 你试一下其他启动器，比如 HMCL 或者 BakaXL安装相同的fabric版本？

可是HMCL没有手动安装,版本名称额不一样
![Uploading image.png…]()

**Comment by Deep-Dark-Forest** [comment]
抱歉，昨天晚上的评论并非我本人操作

**Comment by xjsCHINA** [comment]
我已经把这个问题反馈到fabricmc的GitHub里了

**Comment by SnowFox4004** [comment]
安装 `Forge` 整合包时也遇到了类似的问题，好像是bmclapi炸了
![404errorWhileDownloading](https://github.com/Hex-Dragon/PCL2/assets/101725770/a9786367-63de-48f8-9c9b-5a95afb96a93)
![image](https://github.com/Hex-Dragon/PCL2/assets/101725770/969301ac-3dc9-40e3-ba75-3caa8817a263)

**Comment by JingHai-Lingyun** [comment]
你这应当是另外一回事

**Comment by WorldHim** [comment]
> 安装 `Forge` 整合包时也遇到了类似的问题，好像是bmclapi炸了
> ![404errorWhileDownloading](https://github.com/Hex-Dragon/PCL2/assets/101725770/a9786367-63de-48f8-9c9b-5a95afb96a93)
> ![image](https://github.com/Hex-Dragon/PCL2/assets/101725770/969301ac-3dc9-40e3-ba75-3caa8817a263)

这是属于校园网联合镜像负责的镜像站

**Comment by wuliaodexiaoluo** [comment]
> 安装 整合包时也遇到了类似的问题，好像是bmclapi炸了`Forge` ![404errorWhileDownloading](https://private-user-images.githubusercontent.com/101725770/337829511-a9786367-63de-48f8-9c9b-5a95afb96a93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4OTEzNTgsIm5iZiI6MTcxNzg5MTA1OCwicGF0aCI6Ii8xMDE3MjU3NzAvMzM3ODI5NTExLWE5Nzg2MzY3LTYzZGUtNDhmOC05YzliLTVhOTVhZmI5NmE5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQyMzU3MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YmIyMmIzNWFlYWYxNGIwYjQ4YTFlNzQxYzA4NjY4ZDVkMWFmMTQyZDQwYzM3Y2Y5MjQ1OThkNTYwOTQ1MTE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.p2LKNENpHe3fY9sFX5tqHiFsgpaUr6Kelo1XSGDMo4A) ![image](https://private-user-images.githubusercontent.com/101725770/337829663-969301ac-3dc9-40e3-ba75-3caa8817a263.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4OTEzNTgsIm5iZiI6MTcxNzg5MTA1OCwicGF0aCI6Ii8xMDE3MjU3NzAvMzM3ODI5NjYzLTk2OTMwMWFjLTNkYzktNDBlMy1iYTc1LTNjYWE4ODE3YTI2My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQyMzU3MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NTI4NGM4YWRmMzcwMDc3MjlmZGRlZDllMzg0NmRiMjI1MGQyZDY1OGZlM2RjZjA1MTFhZGE1Nzg5MWNkMzdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xGp3K71JwptzFolcEzMmgObiFxxRP6-pmuJpvBHw61I)

![image](https://github.com/Hex-Dragon/PCL2/assets/160083863/39270db9-c05a-42e9-95d9-eefa1a7ac93a)
并没有炸，浏览器请求 https://mirrors.cernet.edu.cn/bmclapi/net/minecraftforge/forge/1.16.5-36.2.39/
目录下面确实有 forge-1.16.5-36.2.39-universal.jar 这个文件

**Comment by SnowFox4004** [comment]
> 并没有炸，浏览器请求 https://mirrors.cernet.edu.cn/bmclapi/net/minecraftforge/forge/1.16.5-36.2.39/
目录下面确实有 forge-1.16.5-36.2.39-universal.jar 这个文件

确实，重启电脑之后就正常了，但是重启前用一部在同一个网络下的手机访问也是404，可能是我的网络有点玄学

**Comment by xjsCHINA** [comment]
我建议龙猫现删除Fabric 0.6.0.42&0.6.0.41的下载窗口

**Comment by LTCatt** [comment]
这是一个中间版本，应该没啥人会去下，不管了（
