### ISSUE TITLE
离线模式登录皮肤经常性丢失

### ISSUE THREAD

**Issue by LinKin-tech** [Hex-Dragon/PCL2#391]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

离线模式，皮肤使用正版皮肤，经常性启动后皮肤丢失，启动之前需要刷新一下重新启动游戏才可以正常显示皮肤

### 重现步骤

不用刷新使用离线皮肤模式

### 日志与附件

皮肤丢失 无日志

**Comment by LinKin-tech** [comment]
no

**Comment by bwtx2022** [comment]
也许可以在本地缓存一个？

**Comment by LTCatt** [comment]
反馈者已自行 Close
