### ISSUE TITLE
启动pcl时报错

### ISSUE THREAD

**Issue by RDIIIIII** [Hex-Dragon/PCL2#3911]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

报错，音乐无法播放

### 重现步骤

应该直接启动pcl就行
不能每次都触发，试了几次成功了4次，不到

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15448628/Log1.txt)
![333903288-e1b2cd46-807f-4ede-bd5d-221b14601c5e](https://github.com/Hex-Dragon/PCL2/assets/170887016/14794a7d-71fa-4c9a-88b2-a0860cfdb199)

**Comment by allMagicNB** [comment]
第三方的 Bug，推荐去第三方那边叫人修

**Comment by allMagicNB** [comment]
#1753

**Comment by RDIIIIII** [comment]
o

**Comment by RDIIIIII** [comment]
那没事了
