### ISSUE TITLE
下载Minecraft 1.20.2时无法同时选择Forge与OptiFine.

### ISSUE THREAD

**Issue by WuZP-ui** [Hex-Dragon/PCL2#3914]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在PCL“下载”界面试图下载1.20.2时，会发现在下方菜单里无法同时选择OptiFine与Forge
![屏幕截图 2024-05-27 200713](https://github.com/Hex-Dragon/PCL2/assets/132270614/b4e5170d-6c22-45d0-bfb3-02ad43052305)

### 重现步骤

1、点击下载
2、展开“正式版”
3、点击“1.20.2”
4、会发现无法同时选择Forge和OptiFine

### 日志与附件

日志里没有记录此内容，猜测应该是下载源的探测出了问题

**Comment by wuliaodexiaoluo** [comment]
optifine 1.20.2 只有 preview 版本，PCL 不会展示 preview 版本（应该是）

**Comment by allMagicNB** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/116283787/2dadf9ae-2dcf-41c4-a71d-68cd79ee7fb2)
这俩压根就没有兼容的版本
