### ISSUE TITLE
希望pcl加一个主题转移功能

### ISSUE THREAD

**Issue by Gaobaiawa** [Hex-Dragon/PCL2#3918]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

换了新电脑，但是pcl2主题全没了，还需要一个一个解锁很麻烦，希望添加一个功能，以下是一个简单的实现方法
将激活码与主题绑定到一起，也就是类似账户，如果使用了激活码，那么同时解锁此激活码拥有的主题
并且在pcl2添加一个登出按键，登出后出现一个新的激活码，这个激活码拥有在这台电脑上拥有的主题，以及以前的激活码信息
阿巴阿巴…我也看不懂我在说什么

### 原因

我换新电脑，主题还要再解锁一遍，很麻烦感觉，虽然需求很小众但是…但是确实没啥大用

**Comment by allMagicNB** [comment]
#760
