### ISSUE TITLE
建议出一个彩虹色

### ISSUE THREAD

**Issue by wuwenjun9939** [Hex-Dragon/PCL2#3922]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

![image](https://github.com/Hex-Dragon/PCL2/assets/110022109/7ada3531-8066-497d-93a2-6beb2b0fe8ad)

### 原因

就是突然来了灵感（不会只有我这么说吧？）

**Comment by allMagicNB** [comment]
你自定义里边不是已经能调整了吗？

**Comment by wuwenjun9939** [comment]
我说的是，在
![image](https://github.com/Hex-Dragon/PCL2/assets/110022109/89d03edd-d55d-4a20-9cc0-2c4d402903a7)
再出一个....

**Comment by wuwenjun9939** [comment]
或者可以叫：蹦迪色（懂我意思了？）

**Comment by kong-que-dnf123** [comment]
增加概率很小 就算通过了优先级也极低...
![image](https://github.com/Hex-Dragon/PCL2/assets/120994373/9fb50474-7c03-4bcd-b12d-dd4da0227078)

**Comment by allMagicNB** [comment]
> 我说的是，在
> ![image](https://github.com/Hex-Dragon/PCL2/assets/110022109/89d03edd-d55d-4a20-9cc0-2c4d402903a7)
> 再出一个....

请参考滑稽彩和某个按钮可能触发的变色
