### ISSUE TITLE
啟動遊戲時顯示dark_roleplay, gdarp

### ISSUE THREAD

**Issue by hintooo** [Hex-Dragon/PCL2#3924]
### 检查项

- [ ] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

啟動遊戲時顯示dark_roleplay, gdarp

### 重现步骤

啟動遊戲時顯示dark_roleplay, gdarp

### 日志与附件

[crash-2024-05-29_18.29.36-client.txt](https://github.com/Hex-Dragon/PCL2/files/15482919/crash-2024-05-29_18.29.36-client.txt)

**Comment by wuwenjun9939** [comment]
chatgpt回复（但我是真人）
看起来这是一份Java程序的异常堆栈跟踪，似乎是Minecraft游戏在启动时遇到了一个问题。异常的根本原因是一个InvalidPathException，这意味着程序试图使用一个非法的路径访问文件系统。

异常信息表明问题发生在路径D:\.minecraft\versions\?托邦探?之旅3.0上。Windows操作系统不允许某些字符出现在文件路径中，比如<、>、?和:等。在这个特定的路径中，似乎有未知字符（被替换为<?>）引起了这个问题。

解决这个问题的方法可能包括：

确保游戏版本文件夹名称不包含任何非法字符。
检查是否有任何第三方修改器或插件导致这个问题，并考虑禁用它们。
尝试重新安装游戏或更新到最新版本。
由于我无法直接访问或修改您的计算机上的文件，您需要自行检查上述解决方案。如果问题持续存在，您可能需要寻求进一步的技术支持或联系游戏的开发者。

**Comment by zkitefly** [comment]
尝试在 控制面板 -- 时钟和区域 -- 区域 -- 管理 -- 更改系统区域设置 里面上面选「中文（简体，中国）」，并且把下面那个勾去掉

**Comment by LTCatt** [comment]
这是某个 mod 导致的崩溃，与 PCL 无关
