### ISSUE TITLE
一打开就弹出下载net的网站，下了又提示我已经是最新版本

### ISSUE THREAD

**Issue by adsdkklk** [Hex-Dragon/PCL2#3926]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

一打开pcl2就弹出下载net的网站然后pcl2就关闭了也没有报错也没有其他的什么提示，把net下下来安装又显示我已经是最新版本。现在不管是重启，删了重下，还是换个版本都是一样的情况。但我昨天又很正常。
![97bb700f540a189ce62c780f3202368e](https://github.com/Hex-Dragon/PCL2/assets/171164837/10a35c7f-5fae-408f-81a9-cc88c95fe3db)
![1628ad97423b73f25e993ad083284db0](https://github.com/Hex-Dragon/PCL2/assets/171164837/3bc1f41d-1f92-4664-a005-d09fae1e693c)
![d160a84599e242ec4915fc5efe76a6cc](https://github.com/Hex-Dragon/PCL2/assets/171164837/58edbcee-6bcd-44a1-b770-0238fbd06d8c)

### 重现步骤

打开pcl2

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15486585/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/15486587/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/15486588/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/15486589/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/15486590/Log5.txt)

**Comment by LTCatt** [comment]
先卸载新版本的 .net 再安装这个版本

**Comment by adsdkklk** [comment]
可是当我已经卸载掉net后，再下又还是显示我已经是最新版本。











------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Hex-Dragon/PCL2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月30日(星期四) 凌晨4:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Hex-Dragon/PCL2] 一打开就弹出下载net的网站，下了又提示我已经是最新版本 (Issue #3926)





 
先卸载新版本的 .net 再安装这个版本

**Comment by allMagicNB** [comment]
> > 先卸载新版本的 .net 再安装这个版本
> 可是当我已经卸载掉net后，再下又还是显示我已经是最新版本。

推荐重装原版

**Comment by adsdkklk** [comment]
重装原版是什么意思，是指重装net还是我的世界，如果是net我现在下那个好像都是一样的。如果是我的世界，是要我把我的世界删了重下吗？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Hex-Dragon/PCL2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月30日(星期四) 中午12:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Hex-Dragon/PCL2] 一打开就弹出下载net的网站，下了又提示我已经是最新版本 (Issue #3926)





   
先卸载新版本的 .net 再安装这个版本
    
可是当我已经卸载掉net后，再下又还是显示我已经是最新版本。
  
推荐重装原版

**Comment by Pigeon0v0** [comment]
重装系统
