### ISSUE TITLE
版本不对

### ISSUE THREAD

**Issue by wuwenjun9939** [Hex-Dragon/PCL2#3927]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/Hex-Dragon/PCL2/assets/110022109/c4c6aad7-3f27-4e8b-98c4-0f8f082cead0)

### 重现步骤

下载的预览版，谢谢

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/15492641/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/15492642/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/15492643/Log5.txt)
[Log.txt](https://github.com/Hex-Dragon/PCL2/files/15492644/Log.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15492645/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/15492646/Log2.txt)

**Comment by wuwenjun9939** [comment]
附最新版本照片
![image](https://github.com/Hex-Dragon/PCL2/assets/110022109/cbc83aec-32ab-4a61-ad98-f80e7a28b73f)

**Comment by wuwenjun9939** [comment]
而且，服务端可以下载，客户端下不了
![image](https://github.com/Hex-Dragon/PCL2/assets/110022109/bbcf0410-82c1-48c5-a773-a14f6ea8961f)

**Comment by kong-que-dnf123** [comment]
额请问具体是什么问题
我没看出来...

**Comment by wuwenjun9939** [comment]
> 额请问具体是什么问题 我没看出来...

就是说，1.21-pre1版本只在minecraft新闻上有，下载列表里面没有

**Comment by kong-que-dnf123** [comment]
>就是说，1.21-pre1版本只在minecraft新闻上有，下载列表里面没有

你要不试一下重新开启PCL 我这边是正常的啊
![image](https://github.com/Hex-Dragon/PCL2/assets/120994373/f0f4fa5e-59c4-4adc-b448-0dababa38f77)

**Comment by wuwenjun9939** [comment]
> > 就是说，1.21-pre1版本只在minecraft新闻上有，下载列表里面没有
> 
> 你要不试一下重新开启PCL 我这边是正常的啊 ![image](https://private-user-images.githubusercontent.com/120994373/335029984-f0f4fa5e-59c4-4adc-b448-0dababa38f77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwMzk3NzcsIm5iZiI6MTcxNzAzOTQ3NywicGF0aCI6Ii8xMjA5OTQzNzMvMzM1MDI5OTg0LWYwZjRmYTVlLTU5YzQtNGFkYy1iNDQ4LTBkYWJhYmEzOGY3Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMFQwMzI0MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YThmYTRjZmEwZmI1NTE2N2FkMDRiNjc2YzdmZTFiYWE0YzRiYTMzYWQ2MDRkYjBkZDhmODlkMmY3MmE5N2U5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0CbatdZbznUN50kR6goZME2v_FBHGte8y2OONGD8eiI)

![image](https://github.com/Hex-Dragon/PCL2/assets/110022109/1ac5a030-d001-41cf-b735-832ee797e998)
那就奇了怪了，难不成有少部分人收不到更新？况且，我重启过pcl一遍了，我再试试吧

**Comment by wuwenjun9939** [comment]
重启了，还是不行

**Comment by wuwenjun9939** [comment]
[pcl录屏（无法获取1.21-pre1）.zip](https://github.com/Hex-Dragon/PCL2/files/15493376/WinRAR.ZIP.zip)
要不你看看这个？

**Comment by allMagicNB** [comment]
换版本列表获取为优先使用官方源再试试
