### ISSUE TITLE
1.20及以上MC版本优先选择Java21及以上版本启动

### ISSUE THREAD

**Issue by LBZiXL** [Hex-Dragon/PCL2#3928]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

虽然1.20系的MC可以用Java17启动，但是有些mod不支持Java17。如果PCL自动选择了Java17就会导致游戏出错。
![image](https://github.com/Hex-Dragon/PCL2/assets/115980764/a76a4614-aa3e-4f37-98a5-40f17ea2e7fc)
虽然可以在版本设置里手动设置Java，但是我觉得**自动选择Java**这么优化一下更好。

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15501377/Log1.txt)

### 原因

。

**Comment by LTCatt** [comment]
Mod 需要特殊版本的 Java 的情况不在考虑范围内，抱歉
