### ISSUE TITLE
神秘紫无法解锁

### ISSUE THREAD

**Issue by somemouse** [Hex-Dragon/PCL2#3930]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如题（不知道是不是自己的原因）

### 重现步骤

1、从内群下载dev0.4.4，放到snapshot2.6.8版本的pcl2的文件夹里
2、打开dev0.4.4，帮助->开源许可，往下滑，点??????，左下角弹出???? ??? ????
3、打开pcl2，设置->个性化，发现神秘紫没有解锁
[s.zip](https://github.com/user-attachments/files/15508700/s.zip)

### 日志与附件

[Log.txt](https://github.com/user-attachments/files/15508601/Log.txt)
[Log1.txt](https://github.com/user-attachments/files/15508602/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/15508603/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/15508604/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/15508605/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/15508606/Log5.txt)

**Comment by Silverteal** [comment]
这是一个已知问题 #3316。
通过手动替换PCL注册表中`UiLauncherThemeHide2`的值，或许可以手动解锁之。
