### ISSUE TITLE
以管理员身份运行PCL时无法修改版本名

### ISSUE THREAD

**Issue by Xiaoxiangxzx** [Hex-Dragon/PCL2#3931]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

以管理员身份运行PCL修改版本名时报错
日志里的******是我自己码掉的路径
![QQ截图20240531134514](https://github.com/Hex-Dragon/PCL2/assets/119278153/6cd163fe-fb6a-4b97-baef-6749c7023022)

### 重现步骤

1、以管理员身份运行PCL
2、修改版本名

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/15508973/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/15508942/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/15508944/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/15508945/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/15508947/Log5.txt)

**Comment by Xiaoxiangxzx** [comment]
为什么log1.txt不是超链接啊

**Comment by Xiaoxiangxzx** [comment]
为什么log1.txt不是超链接啊

**Comment by Silverteal** [comment]
错误信息位于Log3.txt

**Comment by Xiaoxiangxzx** [comment]
> 错误信息位于Log3.txt 注意到版本文件夹路径较长，或许可以尝试在较浅路径下复现问题？

log5也有错误信息
log4是非管理员版本，其他我没看
浅路径的话我试下

**Comment by Xiaoxiangxzx** [comment]
[Log2.txt](https://github.com/user-attachments/files/15509324/Log2.txt)
[Log1.txt](https://github.com/user-attachments/files/15509325/Log1.txt)
浅路径，管理员运行可以重命名

**Comment by Xiaoxiangxzx** [comment]
刚才另外一个版本是管理员可以重命名，普通模式下不行
