### ISSUE TITLE
[BUG] 错误的向 Mod 添加了不正确的标记

### ISSUE THREAD

**Issue by SuoHouDaiShi** [Hex-Dragon/PCL2#3932]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

> ![图片](https://github.com/Hex-Dragon/PCL2/assets/119282947/4d03b3fc-de05-4853-b2b7-586cd25bf12a)
> 发起原因如图……

表现如图所示，错误的添加了 Mod 灰字的描述
![图片](https://private-user-images.githubusercontent.com/119282947/335507806-a0129d19-b4bd-4e3f-8e12-15945d88d098.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNDcyMjEsIm5iZiI6MTcxNzE0NjkyMSwicGF0aCI6Ii8xMTkyODI5NDcvMzM1NTA3ODA2LWEwMTI5ZDE5LWI0YmQtNGUzZi04ZTEyLTE1OTQ1ZDg4ZDA5OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQwOTE1MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTRlOGRkMWZiMTRlYzU2NTE3ZTc1MzExZDQxZmVkYWY0ODIyN2I3ZjU0MzRjYjMyNzAxMjE5ZDQ5MDdiN2MwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sf-Gdm317hdX332pLtgI-EZ3H1aTxx1vgCRlc9x2bV8)
![图片](https://private-user-images.githubusercontent.com/119282947/335507092-24de9538-c888-4cae-b457-9b31cd53f97e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNDcyMjEsIm5iZiI6MTcxNzE0NjkyMSwicGF0aCI6Ii8xMTkyODI5NDcvMzM1NTA3MDkyLTI0ZGU5NTM4LWM4ODgtNGNhZS1iNDU3LTliMzFjZDUzZjk3ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQwOTE1MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMzFhMWYxNWE4YzVjZWE3OWFjYWZkMTM5ZDU3Nzg2NjYwNTBkNWJmZDY3NWE2M2I4M2RlYWFlZTUyN2MwZWQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kPozyq_eus8ZQ3q_sw__R_2IZ9-McXsWrTbWi9iW2Hw)
而在对应的 Mod 页面中，作者并未添加有关`主页`或`Home`的字样：
![图片](https://private-user-images.githubusercontent.com/119282947/335507336-9387d07a-d1e0-4127-8537-f946641a9173.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNDcyMjEsIm5iZiI6MTcxNzE0NjkyMSwicGF0aCI6Ii8xMTkyODI5NDcvMzM1NTA3MzM2LTkzODdkMDdhLWQxZTAtNDEyNy04NTM3LWY5NDY2NDFhOTE3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQwOTE1MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTMxYTAxZTNiZTE5OTgxMjE0ZjBlOGRiZGE3ZTk1NjIxNGE5NDAxOThkOTI5YzhkNzI3N2RmNDRhZmI1ZjM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TEGUf-8tnlfmgRyd-vqaqxFZuD7UD_SpzgbOU1cXXfM)

### 重现步骤

1.下载 2.7.1.105 的 ModernUI
2.在对应版本的 Mod 管理器中查看，BUG 出现

### 日志与附件

我记得有个 Collaborator 说过日志里不会记录获取的请求吧……
忘了是谁了，反正先不传
## 需要日志就发个 Comment，看到了会传

**Comment by JingHai-Lingyun** [comment]
我看看是从什么地方弄得这个标记

**Comment by JingHai-Lingyun** [comment]
`modern-ui|现代化 UI (Modern UI) - 主页¨@modern-ui|现代化 UI (Modern UI)`

龙猫加的（
如果你认为这很奇怪的话改改标题和描述我挂待处理
没事的话关了罢

**Comment by SuoHouDaiShi** [comment]
那没事了（
