### ISSUE TITLE
卡顿bug反馈

### ISSUE THREAD

**Issue by qislu** [Hex-Dragon/PCL2#3938]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

卡顿,明显的卡顿

### 重现步骤

1、点击主页的版本设置
2、点击左上角后瞬间长按
卡顿出现

### 日志与附件

[Log5.txt](https://github.com/user-attachments/files/15516071/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/15516072/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/15516074/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/15516076/Log3.txt)
[Log4.txt](https://github.com/user-attachm

https://github.com/Hex-Dragon/PCL2/assets/171364455/3ac9cfc7-0167-4433-8045-87c9dcd19b74

ents/files/15516078/Log4.txt)

**Comment by allMagicNB** [comment]
这叫卡顿？这是在等你松鼠标按键

**Comment by LTCatt** [comment]
似乎也是加载主页的卡顿，0.4~0.7s，#3860
