### ISSUE TITLE
目录下更改版本名称后PCL2版本列表提示“未找到版本 json 文件”

### ISSUE THREAD

**Issue by WangZiLong0813** [Hex-Dragon/PCL2#3939]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在Windows资源管理器中更改版本名称后，PCL2提示“未找到版本 json 文件”，可以在版本选择>[某个版本]版本设置>设置，中添加选项 指定json文件 。

### 原因

这项优化让我可以更方便地 指定json文件 。
如果没有这项优化，我每次都必须  先复制json文件，再更改json文件与版本文件夹名称一致  ，让操作变得很麻烦。

**Comment by allMagicNB** [comment]
你怎么就不能用启动器改名称？
任何一个第三方启动器都会在改名的时候把版本 Json 和 Jar 名称一起改掉

**Comment by WangZiLong0813** [comment]
> 你怎么就不能用启动器改名称？ 任何一个第三方启动器都会在改名的时候把版本 Json 和 Jar 名称一起改掉

我不想更改 版本名称

**Comment by allMagicNB** [comment]
> > 你怎么就不能用启动器改名称？ 任何一个第三方启动器都会在改名的时候把版本 Json 和 Jar 名称一起改掉
> 
> 我不想更改 版本名称

？

**Comment by WangZiLong0813** [comment]
不想改版本名称，只想改json文件名称

**Comment by allMagicNB** [comment]
> 不想改版本名称，只想改json文件名称
> 

你不改版本名称你改 Json 干啥？

**Comment by WangZiLong0813** [comment]
复制的其他json文件，比如G的

**Comment by JingHai-Lingyun** [comment]
如果你修改了版本名称，需要同时修改 jar json 和 native 文件夹的名称以让 PCL 正确识别

**Comment by WangZiLong0813** [comment]
> 如果你修改了版本名称，需要同时修改 jar json 和 native 文件夹的名称以让 PCL 正确识别

是的
