### ISSUE TITLE
主页内容意外丢失

### ISSUE THREAD

**Issue by JingHai-Lingyun** [Hex-Dragon/PCL2#3941]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/Hex-Dragon/PCL2/assets/109946426/db07f2f4-5e46-4ba5-8462-87ea184860de)
原来选择的是新闻主页，配置的项目意外的修改了（这应该是 #3061 的再复现），但是
![image](https://github.com/Hex-Dragon/PCL2/assets/109946426/0f19c9dd-d0c4-4c1d-bff2-8dbffe22ee43)
主页上啥也没有……？

### 重现步骤

暂时不清楚如何复现
PCL 版本为 Release 2.7.3

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/15520144/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/15520145/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/15520146/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/15520147/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/15520148/Log5.txt)

**Comment by Louis-Harsune** [comment]
**### 找到疑点了：**
- Log4.txt，第47行开始：
```
[20:15:23.750] 个性化设置项存在异常，已被自动重置：未将对象引用设置到对象的实例。
在 PCL.PageSetupUI.Reload()
错误类型：System.NullReferenceException
[20:15:23.786] [UI] 刷新主题：0
[20:15:23.806] [UI] 刷新主题：0
[20:15:23.815] [Setup] 已初始化个性化设置！
[20:15:23.848] [Control] 普通弹窗：出现错误
个性化设置项存在异常，已被自动重置：未将对象引用设置到对象的实例。
在 PCL.PageSetupUI.Reload()
错误类型：System.NullReferenceException
```
Log4里写的版本号是**Snapshot 2.2.14（256）**，而其他所有Log都是**Release 2.7.3（323）**，按照日志时间可知：
- Log5——>Log4——>Log3——>Log2——>Log1

1.这里推测Authur应该是先在**Release 2.7.3**中有设置预设主页：
- Log5.txt，第14行：
`[20:12:34.813] [Page] 主页预设：每日整合包推荐`

2.随后Authur打开了**Snapshot 2.2.14**，但由于主页预设于[**Snapshot 2.6.5**（更新日志链接）](https://github.com/Hex-Dragon/PCL2/releases/tag/2.6.5)才加入，导致旧版本不认，直接重置了主页相关设置并保存；

3.随后当再打开**Release 2.7.3**时，PCL2自动读取了被旧版本重置的设置，见Log3.txt，第19行：
`[20:17:11.166] [Page] 实例化：清空自定义主页 UI，来源为空`

### **（从此开始不保证分析100%正确）**

4.见Log3.txt，第82行开始：
```
[20:18:39.551] [Page] 主页预设：Minecraft 皮肤推荐
[20:18:39.551] [Page] 主页自定义数据来源：联网全新下载
[20:18:39.556] [Loader] 加载器 自定义主页获取 状态改变：Loading
[20:18:39.565] [Net] 获取网络结果：https://forgepixel.com/pcl_sub_file/version，超时 10000ms
[20:18:39.620] [UI] 弹出提示：正在加载主页……
[20:18:40.102] [Page] 需要下载联网自定义主页，当前版本：5a9e2ad52aaea9048f71ec6d98638f9d，检查源：https://forgepixel.com/pcl_sub_file/version
[20:18:40.104] [Net] 获取网络结果：https://forgepixel.com/pcl_sub_file，超时 10000ms
[20:18:41.197] [Page] 已联网下载自定义主页，内容长度：20998，来源：https://forgepixel.com/pcl_sub_file
[20:18:41.199] [Page] 主页预设：Minecraft 皮肤推荐
[20:18:41.199] [Page] 主页自定义数据来源：联网缓存文件
[20:18:41.199] [Loader] 加载器 自定义主页获取 状态改变：Finished
[20:18:41.201] [Page] 实例化：加载自定义主页 UI，最终内容长度：21208
[20:18:41.391] [Page] 实例化：加载自定义主页 UI 完成
```
4.1.由此可见Authur重新设置了主页；
4.2.见Log3.txt，第127行开始：
```
[20:20:41.439] [Page] 主页自定义数据来源：联网全新下载
[20:20:41.444] [Page] 实例化：清空自定义主页 UI，来源为空
[20:20:41.444] [Loader] 加载器 自定义主页获取 状态改变：Loading
[20:20:41.445] [Net] 获取网络结果：http://forgepixel.cn/pcl_sub_file/version，超时 10000ms
[20:20:41.489] [UI] 弹出提示：正在加载主页……
[20:20:42.853] 联网获取自定义主页版本失败：获取结果失败，远程服务器返回错误: (404) 未找到。（http://forgepixel.cn/pcl_sub_file/version）
→ 远程服务器返回错误: (404) 未找到。
   在 PCL.ModNet.NetGetCodeByRequestOnce(String Url, Encoding Encode, Int32 Timeout, Boolean IsJson, String Accept, Boolean UseBrowserUserAgent)
   在 PCL.PageLaunchRight.OnlineLoaderSub(LoaderTask`2 Task)
   在 System.Net.HttpWebRequest.GetResponse()
   在 PCL.ModNet.NetGetCodeByRequestOnce(String Url, Encoding Encode, Int32 Timeout, Boolean IsJson, String Accept, Boolean UseBrowserUserAgent)
错误类型：System.Net.WebException
[20:20:42.853] [Page] 无法检查联网自定义主页版本，将直接下载，检查源：http://forgepixel.cn/pcl_sub_file/version
[20:20:42.853] [Net] 获取网络结果：http://forgepixel.cn/pcl_sub_file/，超时 10000ms
[20:20:43.511] [Net] 获取网络结果：http://forgepixel.cn/pcl_sub_file/，超时 30000ms
[20:20:44.741] 联网下载自定义主页失败（http://forgepixel.cn/pcl_sub_file/）：获取结果失败，远程服务器返回错误: (404) 未找到。（http://forgepixel.cn/pcl_sub_file/）
→ 远程服务器返回错误: (404) 未找到。
   在 PCL.ModNet.NetGetCodeByRequestRetry(String Url, Encoding Encode, String Accept, Boolean IsJson, String BackupUrl, Boolean UseBrowserUserAgent)
   在 PCL.PageLaunchRight.OnlineLoaderSub(LoaderTask`2 Task)
   在 System.Net.HttpWebRequest.GetResponse()
   在 PCL.ModNet.NetGetCodeByRequestOnce(String Url, Encoding Encode, Int32 Timeout, Boolean IsJson, String Accept, Boolean UseBrowserUserAgent)
错误类型：System.Net.WebException
[20:20:44.743] [Loader] 加载器 自定义主页获取 状态改变：Finished
[20:20:44.803] [Control] 普通弹窗：出现错误
联网下载自定义主页失败（http://forgepixel.cn/pcl_sub_file/）：获取结果失败，远程服务器返回错误: (404) 未找到。（http://forgepixel.cn/pcl_sub_file/）
→ 远程服务器返回错误: (404) 未找到。
   在 PCL.ModNet.NetGetCodeByRequestRetry(String Url, Encoding Encode, String Accept, Boolean IsJson, String BackupUrl, Boolean UseBrowserUserAgent)
   在 PCL.PageLaunchRight.OnlineLoaderSub(LoaderTask`2 Task)
   在 PCL.ModNet.NetGetCodeByRequestOnce(String Url, Encoding Encode, Int32 Timeout, Boolean IsJson, String Accept, Boolean UseBrowserUserAgent)
错误类型：System.Net.WebException
```
4.3.这里应该是网络问题导致主页同步失败；

5.随后在Log2.txt第25行、Log1第24行都能看见：
`[Page] 实例化：清空自定义主页 UI，来源为空`
5.1.具体原因不明， @JingHai-Lingyun ，可以试试删掉`[PCL2所在目录]/PCL/Setup.ini`设置文件，看看问题还有没有复现。

~_最后别tm把新版本设置装进旧版本谢谢…………_~

**Comment by Louis-Harsune** [comment]
### **复现！**

依照我刚才的分析，我拿了个**Snapshot 2.3.1**来：
![image](https://github.com/Hex-Dragon/PCL2/assets/115140320/3e1487b7-b714-4729-b98a-82b7104ce75c)
然后再打开我的**Snapshot 2.7.4**：
![image](https://github.com/Hex-Dragon/PCL2/assets/115140320/50ab1879-8e6c-4487-a689-c8e157785aa8)

### **自定义主页设置重置，此Bug成功复现！**

稳定复现方法：在**Snapshot 2.6.5及更新版本**中设置自定义主页，然后打开**低于Snapshot 2.6.5版本**的PCL2，并进入个性化设置，然后就会有如图1的弹窗警告；此时再打开**Snapshot 2.6.5及更新版本**的PCL2就会发现————**自定义主页消失，同时整个个性化设置均被重置！**

修复：重新设置自定义主页即可。

**Comment by JingHai-Lingyun** [comment]
那这个算作主页配置有内容但是不加载吧

**Comment by Louis-Harsune** [comment]
> 那这个算作主页配置有内容但是不加载吧 我开了 2.2.14 是因为 WD 吃了不吐我重新下的

这个我不知道，应该是吧~（我真不是砖业的）~

**Comment by Silverteal** [comment]
> ### **找到疑点了：**
> * Log4.txt，第47行开始：
> 
> ```
> [20:15:23.750] 个性化设置项存在异常，已被自动重置：未将对象引用设置到对象的实例。
> 在 PCL.PageSetupUI.Reload()
> 错误类型：System.NullReferenceException
> [20:15:23.786] [UI] 刷新主题：0
> [20:15:23.806] [UI] 刷新主题：0
> [20:15:23.815] [Setup] 已初始化个性化设置！
> [20:15:23.848] [Control] 普通弹窗：出现错误
> 个性化设置项存在异常，已被自动重置：未将对象引用设置到对象的实例。
> 在 PCL.PageSetupUI.Reload()
> 错误类型：System.NullReferenceException
> ```
> 
> Log4里写的版本号是**Snapshot 2.2.14（256）**，而其他所有Log都是**Release 2.7.3（323）**，按照日志时间可知：
> 
> * Log5——>Log4——>Log3——>Log2——>Log1
> 
> 1.这里推测Authur应该是先在**Release 2.7.3**中有设置预设主页：
> 
> * Log5.txt，第14行：
>   `[20:12:34.813] [Page] 主页预设：每日整合包推荐`
> 
> 2.随后Authur打开了**Snapshot 2.2.14**，但由于主页预设于[**Snapshot 2.6.5**（更新日志链接）](https://github.com/Hex-Dragon/PCL2/releases/tag/2.6.5)才加入，导致旧版本不认，直接重置了主页相关设置并保存；
> 
> 3.随后当再打开**Release 2.7.3**时，PCL2自动读取了被旧版本重置的设置，见Log3.txt，第19行： `[20:17:11.166] [Page] 实例化：清空自定义主页 UI，来源为空`
> 
> ~_最后别tm把新版本设置装进旧版本谢谢…………_~

抓个虫：应该是Author

**Comment by Silverteal** [comment]
2.2.14是不是内群里用于更新的版本来着，如果是的话估计得更新下

**Comment by Louis-Harsune** [comment]
> 2.2.14是不是内群里用于更新的版本来着，如果是的话这个问题应该比较烦，估计得更新下

如果真要这样更新到2.6.5足够，可以保证issue里提到的主页功能不炸（

**Comment by LTCatt** [comment]
由于这是老版本引起的，现已无法修复

**Comment by wuliaodexiaoluo** [comment]
>如果真要这样更新到2.6.5足够，可以保证issue里提到的主页功能不炸（

不，起码 2.7.4，因为龙猫又加了个

**Comment by LTCatt** [comment]
我顺手也加个后续兼容吧 =。=……
