### ISSUE TITLE
MC试玩版

### ISSUE THREAD

**Issue by Flying-Jerry** [Hex-Dragon/PCL2#3942]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

1.13及以上为什么下载后离线启动成试玩版了？网上也没人反馈

### 重现步骤

下载1.13及以上版本，离线启动

### 日志与附件

no日志

**Comment by allMagicNB** [comment]
截屏

**Comment by JingHai-Lingyun** [comment]
传你的 PCL 日志，我们需要查看里面的 Minecraft 客户端启动信息

**Comment by Flying-Jerry** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/106455290/85d528c8-92d9-47ea-b534-3f29d57eceba)
[PCL.zip](https://github.com/user-attachments/files/15520706/PCL.zip)

**Comment by allMagicNB** [comment]
哪里成试玩版了？

**Comment by Flying-Jerry** [comment]
> 哪里成试玩版了？

？啊？

**Comment by Flying-Jerry** [comment]
> 哪里成试玩版了？

额，听我说，我刚为了弄日志，把pcl文件夹删了，然后…………？

**Comment by Flying-Jerry** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/106455290/35672ac6-8f74-420e-a359-e4aec528721a)
删之前截的屏

**Comment by Flying-Jerry** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/106455290/72c16c5c-297a-47c1-bfb1-cf556a3f4a3f)
但是新启动后为什么名字后面加了一串看不懂的东西

**Comment by Silverteal** [comment]
还是请上传PCL日志
顺带问一下PCL版本：更多-关于与鸣谢

**Comment by qwertyuioi114514** [comment]
> ![image](https://private-user-images.githubusercontent.com/106455290/335783408-72c16c5c-297a-47c1-bfb1-cf556a3f4a3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMzMzNDYsIm5iZiI6MTcxNzIzMzA0NiwicGF0aCI6Ii8xMDY0NTUyOTAvMzM1NzgzNDA4LTcyYzE2YzVjLTI5N2EtNDdjMS1iZmIxLWNmNTU2YTNmNGEzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQwOTEwNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMjk2YmZjMzY2YmZiNDcyN2VlOWYxNmFkNzVmY2IyZWMwNzljZjVhMDcyM2Y5MDJjMjM3ZjFmM2YwZDIzZGZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SGgppmEYNSVzyux6johdLbhQMy5JjPz_nWLHUgFRW8U)但是新启动后为什么名字后面加了一串看不懂的东西
 是不是加了什么JVM参数？

**Comment by qwertyuioi114514** [comment]
> ### 检查项
> * [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。
> 
> ### 描述
> 1.13及以上为什么下载后离线启动成试玩版了？网上也没

> ![image](https://private-user-images.githubusercontent.com/106455290/335783172-35672ac6-8f74-420e-a359-e4aec528721a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMzM0OTIsIm5iZiI6MTcxNzIzMzE5MiwicGF0aCI6Ii8xMDY0NTUyOTAvMzM1NzgzMTcyLTM1NjcyYWM2LThmNzQtNDIwZS1hMzU5LWU0YWVjNTI4NzIxYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQwOTEzMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YWE4ZjY1MDYwZWNlMmEwOWE1MDJjNmJmN2FkYjQzNGQxMjU0NjZlODM0N2JmMTU0NmI4YzVlMDYzMzViZjk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uTO2ziWpWwSBXz54DzT-gZhAChldQo6OLScRz8-jvNg)删之前截的屏



> ![image](https://private-user-images.githubusercontent.com/106455290/335783172-35672ac6-8f74-420e-a359-e4aec528721a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMzM0OTIsIm5iZiI6MTcxNzIzMzE5MiwicGF0aCI6Ii8xMDY0NTUyOTAvMzM1NzgzMTcyLTM1NjcyYWM2LThmNzQtNDIwZS1hMzU5LWU0YWVjNTI4NzIxYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQwOTEzMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YWE4ZjY1MDYwZWNlMmEwOWE1MDJjNmJmN2FkYjQzNGQxMjU0NjZlODM0N2JmMTU0NmI4YzVlMDYzMzViZjk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uTO2ziWpWwSBXz54DzT-gZhAChldQo6OLScRz8-jvNg)删之前截的屏

![5957D1C660D2D7FD08D077D76EDF5326](https://github.com/Hex-Dragon/PCL2/assets/168945453/df6fb167-629e-4fd9-8578-14c2676bac1a)
你这mod数量不对啊，原版加了forge是2个mod 但是你这个有7个mod

**Comment by qwertyuioi114514** [comment]
> ![image](https://private-user-images.githubusercontent.com/106455290/335783172-35672ac6-8f74-420e-a359-e4aec528721a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMzM0OTIsIm5iZiI6MTcxNzIzMzE5MiwicGF0aCI6Ii8xMDY0NTUyOTAvMzM1NzgzMTcyLTM1NjcyYWM2LThmNzQtNDIwZS1hMzU5LWU0YWVjNTI4NzIxYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQwOTEzMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YWE4ZjY1MDYwZWNlMmEwOWE1MDJjNmJmN2FkYjQzNGQxMjU0NjZlODM0N2JmMTU0NmI4YzVlMDYzMzViZjk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uTO2ziWpWwSBXz54DzT-gZhAChldQo6OLScRz8-jvNg)删之前截的屏

![5957D1C660D2D7FD08D077D76EDF5326](https://github.com/Hex-Dragon/PCL2/assets/168945453/252e565b-eeb3-412c-9dc5-4aae2c12aa6c)
同样的forge版本，同样的离线进游戏，但是我只有2mod，你有7mod是不是mod的问题

**Comment by qwertyuioi114514** [comment]
> ![image](https://private-user-images.githubusercontent.com/106455290/335783172-35672ac6-8f74-420e-a359-e4aec528721a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMzM0OTIsIm5iZiI6MTcxNzIzMzE5MiwicGF0aCI6Ii8xMDY0NTUyOTAvMzM1NzgzMTcyLTM1NjcyYWM2LThmNzQtNDIwZS1hMzU5LWU0YWVjNTI4NzIxYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQwOTEzMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YWE4ZjY1MDYwZWNlMmEwOWE1MDJjNmJmN2FkYjQzNGQxMjU0NjZlODM0N2JmMTU0NmI4YzVlMDYzMzViZjk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uTO2ziWpWwSBXz54DzT-gZhAChldQo6OLScRz8-jvNg)删之前截的屏

![5957D1C660D2D7FD08D077D76EDF5326](https://github.com/Hex-Dragon/PCL2/assets/168945453/2fb6f2f6-6453-4f07-a737-b75d2023b259)
同样的版本，也是离线，但是你有7mod，我只有2mod，是不是这出问题了

**Comment by zkitefly** [comment]
> ![image](https://github.com/Hex-Dragon/PCL2/assets/106455290/35672ac6-8f74-420e-a359-e4aec528721a)
> 删之前截的屏

在 jvm 虚拟机参数中追加 --demo 参数即可

**Comment by Flying-Jerry** [comment]
> > ![image](https://private-user-images.githubusercontent.com/106455290/335783172-35672ac6-8f74-420e-a359-e4aec528721a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMzM0OTIsIm5iZiI6MTcxNzIzMzE5MiwicGF0aCI6Ii8xMDY0NTUyOTAvMzM1NzgzMTcyLTM1NjcyYWM2LThmNzQtNDIwZS1hMzU5LWU0YWVjNTI4NzIxYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQwOTEzMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YWE4ZjY1MDYwZWNlMmEwOWE1MDJjNmJmN2FkYjQzNGQxMjU0NjZlODM0N2JmMTU0NmI4YzVlMDYzMzViZjk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uTO2ziWpWwSBXz54DzT-gZhAChldQo6OLScRz8-jvNg)删之前截的屏
> 
> ![5957D1C660D2D7FD08D077D76EDF5326](https://private-user-images.githubusercontent.com/168945453/335791509-2fb6f2f6-6453-4f07-a737-b75d2023b259.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyOTA2ODYsIm5iZiI6MTcxNzI5MDM4NiwicGF0aCI6Ii8xNjg5NDU0NTMvMzM1NzkxNTA5LTJmYjZmMmY2LTY0NTMtNGYwNy1hNzM3LWI3NWQyMDIzYjI1OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMlQwMTA2MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ODE3MzYyYjAzZDk5YmFkZWEzNDRkZTNkOTQ3ZmM3NWUzNThjNWY2ZWE3ZDZhMDk1ZDVhMjBlZjcwYzExNTQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._P_YvOvso1BH9KfHcu5wPTAnDIFli6VYQKhSIDn4ink) 同样的版本，也是离线，但是你有7mod，我只有2mod，是不是这出问题了

不是的，mod跟这个没有关系。网上说可以进游戏前先断网，进去后再联网就不会了

**Comment by Flying-Jerry** [comment]
> 还是请上传PCL日志 理论上，演示模式应该通过版本设置的命令行参数传入 --demo选项时才会开启 顺带问一下PCL版本：更多-关于与鸣谢

额，抱歉，日志没了。。。版本是2.7.4正式版

**Comment by Flying-Jerry** [comment]
> 还是请上传PCL日志 理论上，演示模式应该通过版本设置的命令行参数传入 --demo选项时才会开启 顺带问一下PCL版本：更多-关于与鸣谢

但我不知道Demo是怎么加进去的。我是下了1.13及以上版本都有问题，应该不是版本设置吧。删了pcl文件夹又好了，是不是什么全局设定？

**Comment by Louis-Harsune** [comment]
> > 还是请上传PCL日志 理论上，演示模式应该通过版本设置的命令行参数传入 --demo选项时才会开启 顺带问一下PCL版本：更多-关于与鸣谢
> 
> 但我不知道Demo是怎么加进去的。我是下了1.13及以上版本都有问题，应该不是版本设置吧。删了pcl文件夹又好了，是不是什么全局设定？

怀疑是PCL文件夹里的LatestLaunch.bat里有试玩版启动参数

**Comment by Flying-Jerry** [comment]
> > > 还是请上传PCL日志 理论上，演示模式应该通过版本设置的命令行参数传入 --demo选项时才会开启 顺带问一下PCL版本：更多-关于与鸣谢
> > 
> > 
> > 但我不知道Demo是怎么加进去的。我是下了1.13及以上版本都有问题，应该不是版本设置吧。删了pcl文件夹又好了，是不是什么全局设定？
> 
> 怀疑是PCL文件夹里的LatestLaunch.bat里有试玩版启动参数

但是我没有添加，是他自己进去的？

**Comment by Flying-Jerry** [comment]
我记得好像pcl你知道吗有一个说的是Demo版。那pcl能不能添加一个自动识别，弄个弹窗提示是Demo版，让玩家自定是否Demo

**Comment by allMagicNB** [comment]
> 我记得好像pcl你知道吗有一个说的是Demo版。那pcl能不能添加一个自动识别，弄个弹窗提示是Demo版，让玩家自定是否Demo

那玩意只有手动更改高级选项里边的 JVM 参数才有

**Comment by Michaelshenmo** [comment]
是不是你启动了官方启动器的版本（玩过试玩版的）

**Comment by qwertyuioi114514** [comment]
用皮肤站登入试试吧

在 2024-06-02 09:08:20，Flying-Jerry ***@***.***> 写道：


删之前截的屏

同样的版本，也是离线，但是你有7mod，我只有2mod，是不是这出问题了

不是的，mod跟这个没有关系。网上说可以进游戏前先断网，进去后再联网就不会了
