### ISSUE TITLE
[新功能] 支持在整合包下载界面按模组加载器种类筛选

### ISSUE THREAD

**Issue by Louis-Harsune** [Hex-Dragon/PCL2#3943]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

参考Mod搜索筛选界面：
![image](https://github.com/Hex-Dragon/PCL2/assets/115140320/8b793041-bf7c-4770-b436-4c0f5305957d)
希望在整合包搜索筛选界面中也能有类似上述的模组加载器种类筛选。

### 原因

这个功能可以帮助我更快筛选所需的整合包，而不用一个个去分辨列表标识的模组加载器。

**Comment by JingHai-Lingyun** [comment]
双平台在网页上是支持按 ModLoader 筛选整合包的，不知道 API 有没有对应支持

**Comment by Louis-Harsune** [comment]
如果有搜索API方面的困难导致无法实现，我提个小小的建议（别打我）：
PCL2可以在整合包列表中标出对应的模组加载器，那么可不可以在选择加载器后先正常加载出所有整合包，然后对照筛选逐一过滤掉不符合要求的（

**Comment by LTCatt** [comment]
因为我觉得这个筛选没有太大作用……玩家在玩整合包的时候并不会太在意加载器种类 orz
