### ISSUE TITLE
NeoForge整合包的安装失败

### ISSUE THREAD

**Issue by Gugu2007** [Hex-Dragon/PCL2#3950]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我是最新版的内测PCL，版本为2.7.4，在安装NeoForge整合包的时候会显示出现了未知的mod安装器

### 重现步骤

![39ceb14b-b6a3-42e2-823a-98ddf24d3b75](https://github.com/Hex-Dragon/PCL2/assets/167621714/1cd13747-7c11-42ba-b59f-649a4d7eb86a)

### 日志与附件

无

**Comment by allMagicNB** [comment]
#2244

**Comment by Silverteal** [comment]
NeoForge 的自动安装尚未支持 #2244
