### ISSUE TITLE
增加对于Windows11窗口动画支持

### ISSUE THREAD

**Issue by jfglzs** [Hex-Dragon/PCL2#3951]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

增加任务栏的点击动画 和 弹出窗口的动画效果

### 原因

点击任务栏图标后一瞬间就弹出了 看着有点不舒服
还有一些外部的窗口动画

**Comment by wuliaodexiaoluo** [comment]
这。。。。
您应当检查您的 Windows 设置

**Comment by Deep-Dark-Forest** [comment]
> 这。。。。
> 您应当检查您的 Windows 设置

确实没动画啊

**Comment by wuwenjun9939** [comment]
https://github.com/Hex-Dragon/PCL2/assets/110022109/b8b7f77a-4561-49ba-b831-127694f03655

确实啊，我这2.7.4（内测版）也没动画（Windows功能拿来作对比）

**Comment by wuliaodexiaoluo** [comment]
> QQ.20240602125540.mp4 
> 确实啊，我这2.7.4（内测版）也没动画（Windows功能拿来作对比）

Audio?

**Comment by wuwenjun9939** [comment]
> > QQ.20240602125540.mp4
> > 确实啊，我这2.7.4（内测版）也没动画（Windows功能拿来作对比）
> 
> Audio?

我也不知道啊，突然就给我判定成audio了.....（这也算是发现的一个小特性/bug吧）

**Comment by LTCatt** [comment]
技术上不知道怎么做，之前试过，但 WPF 无边框窗口似乎很难做到……
