### ISSUE TITLE
PCL启动的mc无法被识别为游戏导致笔记本核显去渲染画面

### ISSUE THREAD

**Issue by Mathon01** [Hex-Dragon/PCL2#3955]
### 检查项

- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [ ] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在笔记本端启动mc 由于无固定的启动安装程序，电脑会调用核显运行，独显不干活，也就是电脑没认出或者识别不到这是个游戏，其他的软件可以指定显示的时候使用核显还是独显优先，PCL也可以使用独显渲染，但是在PCL启动的mc后，mc无法被识别，导致核显在渲染mc的画面，独显完全不工作。目前的应急方法是进入nv的控制面版把全局的显示输出调为独显，自动无法识别，望解决。

### 原因

（示例）
这项优化让我可以更方便地游玩mc而不用每次去切换渲染的显卡。
如果没有这项优化，我每次都必须进入nv的控制面板切换显卡，在游玩结束后再次切换回自动，让操作变得很麻烦。

**Comment by allMagicNB** [comment]
你看看哪个启动器启动的能被这玩意识别为游戏？

**Comment by Pigeon0v0** [comment]
手动在 Windows 图形设置设置 javaw.exe 为高性能

如果是 Win10 2004 之前的版本，更新系统再操作

**Comment by Mathon01** [comment]
我的意思是是否可以单独添加为使用高性能显卡，不是非要识别为游戏

**Comment by allMagicNB** [comment]
> 我的意思是是否可以单独添加为使用高性能显卡，不是非要识别为游戏

不能

**Comment by Mathon01** [comment]
好的，谢谢

**Comment by Mathon01** [comment]
感谢[Pigeon0v0](https://github.com/Pigeon0v0)，找到了javaw。把这个程序设为高性能就可以不用手动每次切换了
