### ISSUE TITLE
[Mod更新]在更新一个forge模组时错误地将其更新为fabric模组导致无法加载

### ISSUE THREAD

**Issue by MM-Rabbit** [Hex-Dragon/PCL2#3956]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在更新细节盔甲的1.16.5forge模组时错误地下载了1.17.1fabric的模组。

### 重现步骤

1. 下载细节盔甲模组的2.4+1.16.5-forge版本；
2. 点击更新
3. Bug复现

### 日志与附件

日志：
[Log1.txt](https://github.com/user-attachments/files/15524201/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/15524197/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/15524203/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/15524204/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/15524205/Log5.txt)
（日志关键位置索引：Log2.txt, Line 180）
附截图2张：
![屏幕截图 2024-06-02 123114](https://github.com/Hex-Dragon/PCL2/assets/118085239/1ea1b093-3ce5-4d36-bd06-cc23ac0eda08)
![屏幕截图 2024-06-02 123142](https://github.com/Hex-Dragon/PCL2/assets/118085239/6bec4509-f1f9-4045-b6c9-9ecc4788e5ee)

**Comment by JingHai-Lingyun** [comment]
1.17.1 这个版本的 Mod 看起来同时兼容 Forge 和 Fabric
![image](https://github.com/Hex-Dragon/PCL2/assets/109946426/e5cc4127-61f5-4bab-a850-1e66f7114076)
看到 2.6.1 有多个 Files
![image](https://github.com/Hex-Dragon/PCL2/assets/109946426/91cac2be-c5a2-4bca-89a0-6b1e90ad5da8)
貌似是更新成了 Primary 的

**Comment by wuwenjun9939** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/110022109/0d8a1cd4-982e-4a27-845f-724e1f05147a)
稳定复现

**Comment by wuliaodexiaoluo** [comment]
或许 #3628 ？

**Comment by JingHai-Lingyun** [comment]
这是同版本下不同文件的，和 #3628 还是有点区别的

**Comment by LTCatt** [comment]
请向 mod 作者反馈此问题，不应将不同加载器的版本传到同一个 versions 下，这是作者配置错了
