### ISSUE TITLE
建议改成直接转到某个版本的下载页面

### ISSUE THREAD

**Issue by wuwenjun9939** [Hex-Dragon/PCL2#3957]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

视频发不出来，打字的描述是：点击“Minecraft新闻”的下载按钮之后，跳转到相应的版本下载页面

### 原因

每次看见下载按钮兴奋的点进去之后.....居然还得自己手动点击相应版本下载....

**Comment by Deep-Dark-Forest** [comment]
视频可以传网盘？

**Comment by JingHai-Lingyun** [comment]
@Light-Beacon 看眼
但我如果没记错的话现在没有可行的方式直接跳转

**Comment by Light-Beacon** [comment]
不能直接跳转 这得让lm支持按钮下载特定版本

**Comment by Light-Beacon** [comment]
我新开一个Issue吧

**Comment by Light-Beacon** [comment]
已在 [Light-Beacon/PCL2-NewsHomepage#166](https://github.com/Light-Beacon/PCL2-NewsHomepage/issues/166) 重开
