### ISSUE TITLE
自定义主页显示徽章图片异常

### ISSUE THREAD

**Issue by RainC7** [Hex-Dragon/PCL2#3961]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

自定义主页显示图片异常，无法显示徽章内容（显示为一片空白）

### 重现步骤

1. 修改示例主页的图片Source
2. 刷新主页 - 无法显示

### 日志与附件
[Log1.txt](https://github.com/user-attachments/files/15525575/Log1.txt)

参考徽章链接：https://status.lynn6.top/api/badge/21/status?style=for-the-badge
![](https://status.lynn6.top/api/badge/21/status?style=for-the-badge)

主页文件内容：
```xaml
<local:MyCard Title="长宽属性、图片" Margin="0,0,0,15" CanSwap="True" IsSwaped="True">
	<StackPanel Margin="25,40,23,15">
        <TextBlock TextWrapping="Wrap" Margin="0,0,0,4" Width="320" HorizontalAlignment="Right"
                    Text="任意项目都可以添加 Width 与 Height 属性来控制宽高。HorizontalAlignment 属性可以控制对齐：Center 代表居中，Right 代表居右，例如这段文本就被居右了。" />
        <TextBlock TextWrapping="Wrap" Margin="0,0,0,6"
                    Text="Image 代表图片，你需要在它的 Source 属性中填写一个网址或文件路径，它会从该处获取图片并显示。通常需要使用 Height 限制它的高度。" />
		<Image Height="200" HorizontalAlignment="Center" Source="https://status.lynn6.top/api/badge/21/status?style=for-the-badge" />
	</StackPanel>
</local:MyCard>
```

**Comment by SuoHouDaiShi** [comment]
你这个日志里面没有写获取失败的内容…或许是其它原因导致的？

**Comment by SuoHouDaiShi** [comment]
你这个日志里面没有写获取失败的内容…或许是其它原因导致的？

**Comment by zkitefly** [comment]
难道不支持显示 svg 图片？

**Comment by allMagicNB** [comment]
这尼玛压根就不是图片

**Comment by SuoHouDaiShi** [comment]
这个我看了一下，是个类似于模板的东西，不是生成的 svg 或 png 图像……
你也可以考虑在浏览器中截图该徽章并上传至图床

**Comment by JingHai-Lingyun** [comment]
这不是图片，尝试手动截图之后将它挂载到什么地方去

**Comment by zkitefly** [comment]
https://github.com/Hex-Dragon/PCL2/issues/3115#issuecomment-1953030965
