### ISSUE TITLE
给某个版本重命名时,重命名失败

### ISSUE THREAD

**Issue by Aems-Shruod** [Hex-Dragon/PCL2#3962]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

并非恶性BUG，但是就是无法改名，提示没有权限。但是pcl2是以管理员模式运行的，只读被默认打开，但是我将其手动关闭后还是会被打开。
此bug是我发现整合包更新了，下载后给新版本命名为New Create2。随后在下载安装的过程中将旧版本的版本名修改为New Create1后触发bug，整合包也安装失败。随后多次弹出版本重命名的输入框。

### 重现步骤

1、点击版本设置
2、修改版本名，已经多次尝试稳定触发

### 日志与附件

[Log2.txt](https://github.com/user-attachments/files/15529958/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/15529959/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/15529960/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/15529961/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/15529962/Log1.txt)
![屏幕截图 2024-06-03 144620](https://github.com/Hex-Dragon/PCL2/assets/46645364/45a36015-9e48-43e7-a504-ddc39beb894b)
![屏幕截图 2024-06-03 150335](https://github.com/Hex-Dragon/PCL2/assets/46645364/e52e7ed2-b59e-435c-81b2-dfdcb290168a)
![屏幕截图 2024-06-03 150345](https://github.com/Hex-Dragon/PCL2/assets/46645364/d675a3b8-2f4d-4c13-ab78-1f0fc5b44f54)

**Comment by wuliaodexiaoluo** [comment]
麻烦添加下正在使用中的账户权限，然后再试试能不能重命名
如果不知道用户名，请使用 `whoami` 命令

**Comment by Aems-Shruod** [comment]
> 麻烦添加下正在使用中的账户权限，然后再试试能不能重命名 如果不知道用户名，请使用 命令`whoami`

所有的用户都给了完全控制

**Comment by Aems-Shruod** [comment]
> 麻烦添加下正在使用中的账户权限，然后再试试能不能重命名 如果不知道用户名，请使用 命令`whoami`

所有的用户都已经给了完全控制权限，还是一样的

**Comment by allMagicNB** [comment]
右键 PCL 然后以管理员身份运行

**Comment by Aems-Shruod** [comment]
> 右键 PCL 然后以管理员身份运行再试试

是以管理员启动的，视频太大了发不上来

**Comment by LDTchara** [comment]
检查版本文件夹有没有被占用，我试了一下解除占用之后就可以重命名了

**Comment by LDTchara** [comment]
简单说下原因：文件夹被其他软件占用了导致pcl2无法重命名

**Comment by allMagicNB** [comment]
……那大概是因为有游戏在运行中占用了文件夹和文件

**Comment by LDTchara** [comment]
我的那个无法重命名是因为explorer把版本文件夹占用了...太难绷了

**Comment by SALTWOOD** [comment]
我的设备也有类似问题，表现为部分从网络下载的文件无法删除

**Comment by JingHai-Lingyun** [comment]
我得到的结果是 Windows 下对一个满足夹内夹（或更多嵌套，最里面有一个文件）条件的文件夹进行操作时会报权限不足的问题

**Comment by LTCatt** [comment]
`访问被拒绝` 并非 PCL 导致的或者能解决的问题 Orz
