### ISSUE TITLE
让一个版本可以跟换forge，fabric，和optifine

### ISSUE THREAD

**Issue by EmmmmMCaa** [Hex-Dragon/PCL2#3966]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

打开版本设置可以更换forge 或者 fabric 或者optifine 的版本

### 原因

我需要这个功能来和盆友联机，不至于两人forge版本不一样再重新下载一个版本再把存档和模组移动到新的版本，对新手来说比较友好，更方便

**Comment by zkitefly** [comment]
https://github.com/Hex-Dragon/PCL2/issues/220
