### ISSUE TITLE
允许下载文件手动中断或被中断，断点续传

### ISSUE THREAD

**Issue by hapyle** [Hex-Dragon/PCL2#3969]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在下载文件时允许用户暂停下载
在下载文件时因网络问题被迫中断时允许用户继续下载而不是重新下载
就像浏览器那样

### 原因

刚刚用流量下载整合包刚好达到限额自动掐网
吞了半个G流量然后下载失败，如果有断点续传那就可以省不少事
<img width="608" alt="mmexport1717494032765" src="https://github.com/Hex-Dragon/PCL2/assets/153619262/86af8787-f74c-45f7-8cb6-54f160d270f0">

> 情景再现

**Comment by zkitefly** [comment]
https://github.com/Hex-Dragon/PCL2/issues/3069
