### ISSUE TITLE
内存优化无效

### ISSUE THREAD

**Issue by IKUNKunCaixu** [Hex-Dragon/PCL2#3970]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

点击内存优化后黑屏，未见优化有效

### 原因

（示例）
这项优化让我可以更方便地xxxx。
如果没有这项优化，我每次都必须xxxx，让操作变得很麻烦。
这样可以在游戏卡时方便提高fps，但在游戏占用高内存时却无法（中等偏下配置电脑）优化

**Comment by Deep-Dark-Forest** [comment]
这大概率是你使用的电脑性能太差导致的……

**Comment by allMagicNB** [comment]
> 这大概率是你使用的电脑性能太差导致的……

屁嘞，是硬盘太差

**Comment by WorldHim** [comment]
若仍有疑问请提交日志
