### ISSUE TITLE
最新版本的PCL2启动1.8.9的时候，游戏窗口变小了

### ISSUE THREAD

**Issue by MeditatorLogic** [Hex-Dragon/PCL2#3973]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我的电脑是苹果那个非常丧心病狂的5K（其他配置不咋样），屏幕特别大，所以启动游戏的时候对窗口大小有很强的要求。
在PCL2最后一次更新后，我尝试启动1.8.9游戏，当时窗口设置的是1920*1080，可是启动之后顶多只有1K的大小。然后我又改成了2560*1440，仍然只有不到1.4k的大小，直到我最后把窗口分辨率调到了3840*2160，游戏才恢复到差不多2K的窗口大小。但是我再次启动其他版本的时候，窗口变成了实打实的4K，然后我只能把窗口改回1920*1080，然后回到1.8.9，又双叒叕特别小……嘤嘤嘤……我是个强迫症，绝对忍不了手动拖拽窗口大小，可是每次玩1.8.9都是这样，非常麻烦！
这玩意他不会也开始跟1.12.2一样，窗口大小有强锁定了吧？

### 重现步骤

1、点击xxxx
2、然后点击xxxx
3、然后点击xxxx
4、然后点击xxxx
5、最后点击xxxx
得了，自己看一下后面附的图片就知道了

### 日志与附件

![image](https://github.com/Hex-Dragon/PCL2/assets/129654626/9a494f31-cecb-49d5-92a3-6b809ce8e9f5)
![Uploading image.png…]()

**Comment by MeditatorLogic** [comment]
还有这个github能不能在斜体识别上改一下？我就想打个乘号，他就给我识别了斜体……

**Comment by Pigeon0v0** [comment]
#3463

**Comment by MeditatorLogic** [comment]
您好，#3463不是说的1.12.2吗？那个上面说了有改不了的窗口强设定
但是我这个是1.8.9，而且是最新版本的启动器才出现的，之前一直没有这个问题，
而且这个是整个窗口等比例缩小，别的版本都没变化，不知道是啥原因，
别人好像也没有报告过这个问题……
您排查出来是和1.12.2一样的了？



在 2024-06-06 15:29:18，"Pigeon0v0" ***@***.***> 写道：

Closed #3973 as not planned.

**Comment by Pigeon0v0** [comment]
你再仔细看标题？

**Comment by MeditatorLogic** [comment]
哥！大哥！啥标题呀给个提示呗？



在 2024-06-06 16:59:07，"Pigeon0v0" ***@***.***> 写道：

你再仔细看标题？

**Comment by Pigeon0v0** [comment]
> 使用 Java 8 启动 MC 1.12.2- 时窗口大小有误

看见 - 没

**Comment by MeditatorLogic** [comment]
对呗，我那意思是现在1.8.9又出问题了跟之前1.12.2是一个原理？（那为啥之前用PCL2就没这个bug？

**Comment by MeditatorLogic** [comment]
啊，没事了，1.7.10也这样
