### ISSUE TITLE
更换 LICENSE

### ISSUE THREAD

**Issue by allMagicNB** [Hex-Dragon/PCL2#3975]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

更换 LICENSE

### 原因

现在有很多主流 LICENSE 拥有着完善的许可制度，可以更有效减少钻空子的人，规定使用源代码后能做什么和不能做什么，对商业用途也做出限制等等，总之相对于非专业人士写的更专业……
同时可以对部分 LICENSE 进行附加条款，比如不得称其为衍生作品，不得取用与原项目高度相似的项目名及缩写等等……

**Comment by Deep-Dark-Forest** [comment]
这需要专业人士来完成吧……
毕竟之前龙猫的 LICENSE 就说了需要专业人士来完善

**Comment by LTCatt** [comment]
主要是，在 [HiPer Minecraft Launcher](https://www.bilibili.com/read/cv19696374/) 的事之后，我对彻底开源持悲观态度。而现在的主流协议对这种事情的约束力并不强，需要添加附加条款。但添加附加条款这种事情，没有法律专业人士指导，我还是不太敢自己整……

**Comment by wuyuncheng-26** [comment]
现在 LICENSE 已经修改了，这个 issue 是不是可以改一下 label

**Comment by LTCatt** [comment]
还是可以看看有没有懂法律的来改改，留着吧 orz

**Comment by Silverteal** [comment]
阻止 HiPer MineCraft Launcher 以 HMCL 的名称混淆视听的方法是为 HMCL 注册商标，软件许可证无法直接为名称提供保障。

**Comment by allMagicNB** [comment]
> 阻止类似 `HiPer MineCraft Launcher 以 HMCL 的名称混淆视听`情况的方法是为名称注册商标，软件许可证无法直接为名称提供保障。

与 PUBG CHAMPIONS LEAGUE 重复。

**Comment by LTCatt** [comment]
![Image](https://github.com/user-attachments/assets/3642bc79-2610-4676-88ef-d1e783d0a97c)

**Comment by Silverteal** [comment]
> ![Image](https://github.com/user-attachments/assets/3642bc79-2610-4676-88ef-d1e783d0a97c)

那就没办法了 不知道PCL2/PCL II行不行

**Comment by allMagicNB** [comment]
> > ![Image](https://github.com/user-attachments/assets/3642bc79-2610-4676-88ef-d1e783d0a97c)
> 
> 那就没办法了 不知道PCL2/PCL II/全名Plain Craft Launcher行不行

与图片商标不符.jpeg

**Comment by SALTWOOD** [comment]
往图标加一个 II 或者加个 Launcher 字样？

**Comment by Tydecent** [comment]
`LICENSE`上说`开发者仍保留所有权利（All Rights Reserved）`,但后续又允许在遵守规则的情况下使用。
这实际上意味着目前所有的复制、修改、分发均属侵权。只不过作者说自己会睁一只眼闭一只眼。
