### ISSUE TITLE
自动选择Java出错

### ISSUE THREAD

**Issue by costpoem** [Hex-Dragon/PCL2#3976]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

自动选择Java出错

### 重现步骤

1、点击启动游戏
2、出错

### 日志与附件

[Uploading 新建文件夹 (2).zip…]()

**Comment by allMagicNB** [comment]
等待 `Uploading XXX` 字样消失后再发送

**Comment by costpoem** [comment]
[新建文件夹 (2).zip](https://github.com/user-attachments/files/15764806/2.zip)

**Comment by allMagicNB** [comment]
升级
