### ISSUE TITLE
基岩版

### ISSUE THREAD

**Issue by Shabby-LDN** [Hex-Dragon/PCL2#3981]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

我觉得“下载”那一栏可以增加一个“基岩版下载“，就可以更方便的启动基岩版

### 原因

这项优化让我可以更方便地启动基岩版。
如果没有这项优化，我每次都必须挂VPN到官方启动器去下载和启动，让操作变得很麻烦。
而且最近MC15周年，tiktok和twitch有披风，但只有基岩版有，所以有些玩家想穿披风游玩MC，就必须要到官方启动器去下载基岩版玩儿

**Comment by allMagicNB** [comment]
#81

**Comment by allMagicNB** [comment]
至于下载……自己挂梯子去，微软商店没法下载基本上咱这也没法下载
