### ISSUE TITLE
添加、移除与删除文件夹问题

### ISSUE THREAD

**Issue by Shabby-LDN** [Hex-Dragon/PCL2#3982]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

有一次我在版本文件夹里不小心添加了一个有重要资料的文件夹，我想把它移除pcl2，却发现根本移除不了，只能删除，作为一个强迫症来说，这是一个非常难受的问题，只能把里面的东西备份出来，再在pcl2中的删除文件夹后，再把备份的移到原来的路径

### 原因

这项优化让我可以更方便地移除文件夹。
如果没有这项优化，我每次都必须备份，删除，移回，让操作变得很麻烦。

**Comment by JingHai-Lingyun** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/109946426/a34e79e8-5ae8-4252-8211-fbe5877e970e)
？

**Comment by allMagicNB** [comment]
> 那不小心添加了官方启动器呢？

你的重要资料会放到官方启动器的游戏目录下？
