### ISSUE TITLE
URL打开基岩版的功能寄了？

### ISSUE THREAD

**Issue by MCSteve123** [Hex-Dragon/PCL2#3985]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

原本用PCL的`打开网页`打开`minecraft://`可以直接启动基岩版的，现在直接报错？（Chrome可用）
![image](https://github.com/Hex-Dragon/PCL2/assets/121204926/54bc41ac-2cc2-426c-ac4d-82908c03efee)

### 重现步骤

用MFn233的主页预设，选择“更多”，“启动基岩版”

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/15746592/Log1.txt)
一个够了，需要再传

**Comment by MCSteve123** [comment]
现在一定要以http开头了？

**Comment by WorldHim** [comment]
试试用 `Win`+`R` 输入 `minecraft://` 能否正常打开基岩版

**Comment by JingHai-Lingyun** [comment]
现在是要求网址必须是以 http 开头
https://github.com/Hex-Dragon/PCL2/blob/deca6b63028492ac57c4bb9099422cf29dd08dd3/Plain%20Craft%20Launcher%202/Modules/Base/ModBase.vb#L2189

另附一张 Debug 信息
![image](https://github.com/Hex-Dragon/PCL2/assets/109946426/e5cc03c2-3191-4ec3-8653-7b984b83289e)

**Comment by wifi-left** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/63381531/699b3211-46dc-4b09-8407-701029759427)

**Comment by MCSteve123** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/121204926/f406ba54-3691-4afa-872e-8d996684371d)

**Comment by Silverteal** [comment]
请尝试：
EventType：打开文件
EventData：start minecraft://

**Comment by MCSteve123** [comment]
> EventType `打开网页` 设计上只用于打开真正的网页。根据源代码中的建议，运行程序应该使用 EventType `打开文件`，因此请尝试：
> 
> EventType：`打开文件`
> 
> EventData：`cmd.exe /c start minecraft://` 或 EventData：`start minecraft://`
> 
> 我个人一直认为通过自定义事件来运行外部程序是一种比较dirty且unsafe的实现，不过上述参数应该能满足要求。

事实上不行（
![image](https://github.com/Hex-Dragon/PCL2/assets/121204926/941860e3-dfbc-4fd3-a071-ba21db5b6207)

**Comment by Silverteal** [comment]
> 事实上不行（

抱歉，我之前的回复有误，`EventData`应该为：
`cmd.exe /c start /b cmd.exe /c start minecraft://`

**Comment by MCSteve123** [comment]
> cmd.exe|/c start /b cmd.exe /c start minecraft://

~这玩意它弹黑框啊（虽然会自己关）~

**Comment by MCSteve123** [comment]
@LTCatt 换了硬盘需要一个新的活跃橙 28F4-95A2-73C5-494A

**Comment by LTCatt** [comment]
你的解锁码：CZET4HootmIou6pqEnwiGSlgFLYarAZb
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
