### ISSUE TITLE
添加新的快捷方式

### ISSUE THREAD

**Issue by SnifferGX** [Hex-Dragon/PCL2#3986]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

在版本设置→概述→快捷方式中添加新的内容，例如：资源包文件夹、截图文件夹……

### 原因

方便对存档访问、更改。

**Comment by JingHai-Lingyun** [comment]
#606 抱歉

**Comment by allMagicNB** [comment]
#2508
