### ISSUE TITLE
支持与FCL等安卓端启动器联机

### ISSUE THREAD

**Issue by zhqh202302** [Hex-Dragon/PCL2#3988]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

允许FCL玩家加入房间，允许与手机端启动器进行局域网联机

### 原因

有的人总是没有电脑的，手机+电脑更符合学生党的联机需要

**Comment by burningtnt** [comment]
联机与启动器无关。该怎么连，就怎么连

**Comment by allMagicNB** [comment]
怎么就不允许了？装个自定义联机吧
