### ISSUE TITLE
无法设置主题

### ISSUE THREAD

**Issue by Lincoln-zeng-cn** [Hex-Dragon/PCL2#3989]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

赞助过作者，但是无法获得隐藏的金色主题

### 重现步骤

1、按照赞助步骤赞助
2、按照领取步骤领取
无法获得主题

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/15750613/Log1.txt)
这个日志不一定能体现问题

**Comment by allMagicNB** [comment]
你是不是少复制了什么……

**Comment by Lincoln-zeng-cn** [comment]
![屏幕截图 2024-06-09 152153](https://github.com/Hex-Dragon/PCL2/assets/172161733/d6a4c3ef-3a34-4e50-b25d-8c7da812e7e8)
![屏幕截图 2024-06-09 152329](https://github.com/Hex-Dragon/PCL2/assets/172161733/2a29e292-b1de-4351-8a73-597d3ca3450d)
![屏幕截图 2024-06-09 152336](https://github.com/Hex-Dragon/PCL2/assets/172161733/c0136302-d391-4aaa-a85e-50c47e05b946)

**Comment by JingHai-Lingyun** [comment]
上传一下最新的日志

**Comment by Lincoln-zeng-cn** [comment]
哪个是最新的

**Comment by JingHai-Lingyun** [comment]
在你做完上述操作之后，关掉 PCL 并上传 Log1.txt

**Comment by Lincoln-zeng-cn** [comment]
[Log1.txt](https://github.com/user-attachments/files/15751032/Log1.txt)

**Comment by allMagicNB** [comment]
一眼最后一个等于号没输进去

**Comment by hejiehao** [comment]
> [Log1.txt](https://github.com/user-attachments/files/15751032/Log1.txt)

Not Found
![image](https://github.com/Hex-Dragon/PCL2/assets/98140773/f150acea-0878-4082-8f86-d7f73de9a62c)

**Comment by Lincoln-zeng-cn** [comment]
[Log1.txt](https://github.com/user-attachments/files/15751055/Log1.txt)

**Comment by hejiehao** [comment]
```
[15:23:30.765] [Other] 输入的解锁码：CoRaNvP2pD2nHm3harqslM+6W/uSuR0MIceX8SRVaEjBtIhj1NXjtWulmTx2uuUKZEpSqJycfSaNKmRgGLNYg=
```
漏了个等号

**Comment by Lincoln-zeng-cn** [comment]
[Log1.txt](https://github.com/user-attachments/files/15751061/Log1.txt)
还是不行呀

**Comment by wuliaodexiaoluo** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/160083863/96ed6c70-13c6-4945-b17a-5619b361f661)
如果没有敲错的话，可能 Author 复制的解锁码本身就是错的（包含不可见符）
Author 你重新复制一遍再试试？

**Comment by allMagicNB** [comment]
一眼把 `q` 抄成 `p` 了

**Comment by wuliaodexiaoluo** [comment]
![52ce6dfd5dde539983888febf74c71da](https://github.com/Hex-Dragon/PCL2/assets/160083863/434af5cb-622f-486b-95d9-42e866b6f46b)

最好让龙猫看看

**Comment by WorldHim** [comment]
似乎确实没啥问题🤔

**Comment by Lincoln-zeng-cn** [comment]
@WorldHim 你这是啥意思？

**Comment by WorldHim** [comment]
> @WorldHim 你这是啥意思？

就是说好像不是你的问题

**Comment by Lincoln-zeng-cn** [comment]
哦

**Comment by LTCatt** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/0c6a0dd0-b70f-40b7-a8e3-6258b2749dc6)
一个大写 i 打成了小写 L。
求求你用复制粘贴吧。
