### ISSUE TITLE
正式版中点击 “输入解锁码” 会导致启动器崩溃

### ISSUE THREAD

**Issue by Light-Beacon** [Hex-Dragon/PCL2#3990]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如题

### 重现步骤

点击 “输入解锁码”

### 日志与附件
[Log1 (2).txt](https://github.com/user-attachments/files/15751472/Log1.2.txt)

**Comment by wuliaodexiaoluo** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/160083863/bde961f1-f8a6-46bf-998c-81f734ef48ed)
Release 2.7.4 未复现
![image](https://github.com/Hex-Dragon/PCL2/assets/160083863/2174cdde-2b90-439c-82bd-aac11d63fbae)
而且。。。这怎么看怎么像是被第三方软件强制终止进程了

**Comment by Light-Beacon** [comment]
其实龙猫确认了，只是等他过来挂个优先级（

**Comment by wuliaodexiaoluo** [comment]
额，好吧

**Comment by mnbvcxz-2024** [comment]
貌似没有完全修复，版本2.7.4中点击 更多-关于与鸣谢-赞助者 中单击“输入解锁码”仍然会崩溃
[Log1.txt](https://github.com/user-attachments/files/15847537/Log1.txt)
