### ISSUE TITLE
已赞助，但不能使用主题

### ISSUE THREAD

**Issue by bcptdtptpwyx** [Hex-Dragon/PCL2#3993]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

已赞助，已输入更新秘钥，并升级至最高版本，但无法使用主题

### 重现步骤

1、点击设置
2、点击个性化
3、显示需要小小赞助一下作者，才能修改主题颜色(悲)......

### 日志与附件

![微信截图_20240609230035](https://github.com/Hex-Dragon/PCL2/assets/108409934/775707f8-95a8-4bae-a532-b85000102163)
![微信截图_20240609230904](https://github.com/Hex-Dragon/PCL2/assets/108409934/5e0b241d-7e18-41f8-9218-5a2b80282373)

**Comment by allMagicNB** [comment]
你开错了……这是正式版，不是赞助获得的快照版

**Comment by bcptdtptpwyx** [comment]
> 你开错了……这是正式版，不是赞助获得的快照版

之前快照也不行

**Comment by JingHai-Lingyun** [comment]
如果快照版仍然不行请修改正文后发一条信息和我们说

**Comment by allMagicNB** [comment]
> > 你开错了……这是正式版，不是赞助获得的快照版
> 
> 之前快照也不行

你截屏啊

**Comment by bcptdtptpwyx** [comment]
> > > 你开错了……这是正式版，不是赞助获得的快照版
> > 
> > 
> > 之前快照也不行
> 
> 你截屏啊

之前没用截屏，我现在没有安装包也退不回去

**Comment by bcptdtptpwyx** [comment]
> > > 你开错了……这是正式版，不是赞助获得的快照版
> > 
> > 
> > 之前快照也不行
> 
> 你截屏啊

之前没有截屏，现在没有安装包也退不回去

**Comment by allMagicNB** [comment]
> > > > 你开错了……这是正式版，不是赞助获得的快照版
> > > 
> > > 
> > > 之前快照也不行
> > 
> > 你截屏啊
> 
> 之前没有截屏，现在没有安装包也退不回去

你爱发电私信没有吗？你以为赞助了自动给你升级？

**Comment by bcptdtptpwyx** [comment]
> > > > > 你开错了……这是正式版，不是赞助获得的快照版
> > > > 
> > > > 
> > > > 之前快照也不行
> > > 
> > > 
> > > 你截屏啊
> > 
> > 
> > 之前没有截屏，现在没有安装包也退不回去
> 
> 你爱发电私信没有吗？ 你觉得赞助了自动给你升级？并不是，请在爱发电私信跟龙猫发送 ，然后按指引操作……`下载`

最新版是个正式版
