### ISSUE TITLE
curseforge导出的整合包中的光影用pcl2导入会下载到mod文件夹

### ISSUE THREAD

**Issue by ciaotanjiajun** [Hex-Dragon/PCL2#3995]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

用curseforge导出的整合包的光影pcl2会下载在mod文件夹下，出现这种情况的光影是发布在curseforge网站下的光影，而没在curseforge网站下发布的光影则不会
例如itt3和Complementary
这两款光影在同一个整合包，整合包用pcl2导入Complementary会出现在mod文件夹下，itt3则在shaderpacks文件夹下

### 重现步骤

导入curseforge格式的整合包

### 日志与附件

附件过大，还麻烦大佬点击链接下载测试[https://www.123pan.com/s/xFQrVv-NJUkd.html](url)

**Comment by Deep-Dark-Forest** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/131975043/580d30f5-2672-4868-b225-dbb0ca06e34d)
![image](https://github.com/Hex-Dragon/PCL2/assets/131975043/ad19593c-69e1-4dbb-aae2-d206529d17c6)

**Comment by Deep-Dark-Forest** [comment]
HMCL 一样能复现，不是启动器问题

**Comment by ciaotanjiajun** [comment]
我在hmcl导入没有问题，就只有pcl2会出现这情况

**Comment by ciaotanjiajun** [comment]
> 我在hmcl导入没有问题，就只有pcl2会出现这情况

原链接新增了导入视频[https://www.123pan.com/s/xFQrVv-NJUkd.html](url)

**Comment by Deep-Dark-Forest** [comment]
我们已经确认是这个整合包本身的问题了……
![Image_1717983540213.jpg](https://github.com/Hex-Dragon/PCL2/assets/131975043/1e9539a0-e2c2-4d2e-a031-17772dc39c94)

**Comment by zkitefly** [comment]
经测试，HMCL 并没有问题

PCL 出现了将 ComplementaryUnbound_r5.2.1.zip 放到 mods 文件夹的情况

**Comment by zkitefly** [comment]
劳烦问一句，PCL 版本是最新的吗

**Comment by ciaotanjiajun** [comment]
对的，pcl版本为2.7.4，整合包也是在curseforge应用程序上直接打包的

**Comment by hejiehao** [comment]
> HMCL 一样能复现，不是启动器问题 ![image](https://private-user-images.githubusercontent.com/131975043/338024363-9625e2d5-259e-4594-a356-5584316f2678.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMjA0MzIsIm5iZiI6MTcxODAyMDEzMiwicGF0aCI6Ii8xMzE5NzUwNDMvMzM4MDI0MzYzLTk2MjVlMmQ1LTI1OWUtNDU5NC1hMzU2LTU1ODQzMTZmMjY3OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMFQxMTQ4NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MzQ2NzgzMzQ5NzkyN2VmNjFhYmQxYTc2OWViOWI1Yjc4Y2NhYjMyZDhlYjY1ODdiYzAyYTZhYmE3ZWNmMWU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lnxTi4f6jm24izfpd3elMFIbLJV_Pm8jnIiylxWY_yk)

这应当在 https://github.com/HMCL-dev/HMCL/pull/2770 中已经修复

**Comment by ciaotanjiajun** [comment]
也许是的，我所使用的hmcl版本是3.5.8.248
今天发现这个bug才下载hmcl来测试的

> > HMCL 一样能复现，不是启动器问题![图像](https://private-user-images.githubusercontent.com/131975043/338024363-9625e2d5-259e-4594-a356-5584316f2678.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMjA0MzIsIm5iZiI6MTcxODAyMDEzMiwicGF0aCI6Ii8xMzE5NzUwNDMvMzM4MDI0MzYzLTk2MjVlMmQ1LTI1OWUtNDU5NC1hMzU2LTU1ODQzMTZmMjY3OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMFQxMTQ4NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MzQ2NzgzMzQ5NzkyN2VmNjFhYmQxYTc2OWViOWI1Yjc4Y2NhYjMyZDhlYjY1ODdiYzAyYTZhYmE3ZWNmMWU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lnxTi4f6jm24izfpd3elMFIbLJV_Pm8jnIiylxWY_yk)
> 
> 这应当在 [HMCL-dev/HMCL#2770](https://github.com/HMCL-dev/HMCL/pull/2770) 中已经修复
