### ISSUE TITLE
安装不了使用neoforge的整合包

### ISSUE THREAD

**Issue by wumingshiali** [Hex-Dragon/PCL2#3998]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

https://github.com/Hex-Dragon/PCL2/assets/157328007/765b367b-150a-4d12-b664-66a87d7e0887

### 重现步骤

安装nenforge整合包

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/15755879/Log1.txt)

**Comment by allMagicNB** [comment]
NeoForge 还没支持呢
