### ISSUE TITLE
让自定义主页在加载时使用缓存，避免页面空白

### ISSUE THREAD

**Issue by LTCatt** [Hex-Dragon/PCL2#40]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

让自定义主页可以在本地留下缓存，在加载结束前先使用缓存，这样右侧不会是空白的。

### 原因

目前每次打开 PCL2，都会从指定的网址下载自定义主页，在加载过程中主页右侧是空白的。
如果可以在加载时使用缓存，那在这时候右侧就不会空白了……

**Comment by iPodtouch6557** [comment]
拖了一年零三天终于完成了XD
