### ISSUE TITLE
[Bug] 模板 Label 丢失

### ISSUE THREAD

**Issue by wuliaodexiaoluo** [Hex-Dragon/PCL2#4001]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

Label 没了

### 重现步骤

创建一个新 issue

### 日志与附件

~拿不到 GitHub 服务端的日志~

**Comment by hejiehao** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/98140773/8122d702-13a4-4a2f-af82-74ca99f9829f)
