### ISSUE TITLE
在含有有问题的卡片的自定义主页中拉伸窗口会导致动画执行失败

### ISSUE THREAD

**Issue by Light-Beacon** [Hex-Dragon/PCL2#4003]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在卡片中 设置`CanSwap="False" IsSwaped="True"` 这样冲突的属性会导致展示该卡片时拉伸窗口时提示动画执行失败并折叠卡片

### 重现步骤

1、在 Custom.xaml 中创建属性冲突的卡片
```xaml
<local:MyCard Title="测试卡片" CanSwap="False" IsSwaped="True" >
<StackPanel Margin="40">
</StackPanel>
</local:MyCard>
```
2、打开PCL，选择在主页设置中选择读取本地文件，回到启动页面，拉伸窗口

### 日志与附件

[Custom.txt](https://github.com/user-attachments/files/15759403/Custom.txt)
[Log1.txt](https://github.com/user-attachments/files/15759410/Log1.txt)

**Comment by MM-Rabbit** [comment]
稳定复现
![屏幕截图 2024-06-10 181805](https://github.com/Hex-Dragon/PCL2/assets/118085239/e46d23e0-f57a-457f-9452-7c54de9e98b4)

**Comment by LTCatt** [comment]
非标准使用带来的 bug 不修 =。=

**Comment by WorldHim** [comment]
是否有必要在加载时就报错🤔

**Comment by LTCatt** [comment]
非标准使用本来就不考虑做兼容和修复 orz
