### ISSUE TITLE
dragonwell-8 jdk 无法自动识别

### ISSUE THREAD

**Issue by acaciachan** [Hex-Dragon/PCL2#4006]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

![Clip_2024-06-11_18-26-54](https://github.com/Hex-Dragon/PCL2/assets/73088428/69917a7a-b4b3-4322-aea9-4e41c6788c82)
如图，zulu的和openJDK的可以被自动识别，但是dragonwell不行，我点过“自动搜索”了。
复现方法：
https://dragonwell-jdk.io/#/index 下载dragonwell8 x86 64 windows版本;
解压之后放到 C:\Program Files\Java 文件夹里；
发现PCL启动器无法自动识别添加到列表里。

### 原因

这项优化让我可以更方便地选择。
如果没有这项优化，我每次都必须手动添加，让操作变得很麻烦。

**Comment by youzi-2333** [comment]
PCL 没这个关键字，不去搜这个 java……先让龙猫看看能不能加一下吧（

###### `is:issue java AND (搜索 OR 识别) AND 自动搜索`

**Comment by allMagicNB** [comment]
发日志

**Comment by youzi-2333** [comment]
我怀疑就是这玩意没这个关键字……怀疑是权限问题的话得看日志

https://github.com/Hex-Dragon/PCL2/blob/main/Plain%20Craft%20Launcher%202/Modules/Minecraft/ModJava.vb#L639-L704

**Comment by allMagicNB** [comment]
> By the way, if you put both versions in the same folder as the launcher, both can be searched.

Yes, because PCL will scans Java in the same folder as itself.

**Comment by acaciachan** [comment]
[Log1.txt](https://github.com/user-attachments/files/15787304/Log1.txt)

**Comment by LTCatt** [comment]
可以提供一下安装结束后 java 的完整路径吗？
我姑且先在检测关键词里加了个 dragon……

**Comment by acaciachan** [comment]
https://github.com/dragonwell-project/dragonwell8/releases
https://dragonwell-jdk.io/#/index
https://www.aliyun.com/product/dragonwell
看了一下阿里的java好像都是压缩包不是安装包，解压出来都是：
dragonwell-21.0.2.0.2+13-GA
dragonwell-17.0.11.0.12+9-GA
dragonwell-11.0.23.20+9-ga
dragonwell-8.19.20
这样的名字，关键词设置个dragonwell就行了吧
实在不行就弄个如果找到了java就在上级目录里查查别的文件夹有没有java.exe这样的思路之类的
包括但不限于比如在启动器附近的文件夹查找，具体现在是怎么搞得我也不清楚了
