### ISSUE TITLE
.gif当壁纸无法正确显示(图在评论)

### ISSUE THREAD

**Issue by cnyzq** [Hex-Dragon/PCL2#4007]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

让.gif可以正常当壁纸显示

### 原因

emmmmmmm......我怎么知道

**Comment by cnyzq** [comment]
![Uploading 2024-06-11.png…]()

**Comment by cnyzq** [comment]
![Uploading 2024-06-11.png…]()

**Comment by allMagicNB** [comment]
#116

**Comment by cnyzq** [comment]
emmmmmmm 没翻到啊

**Comment by cnyzq** [comment]
就当催改了

**Comment by allMagicNB** [comment]
#976

**Comment by cnyzq** [comment]
来个插件端口 让自己写呗

**Comment by cnyzq** [comment]
我感觉这样会有戏

**Comment by allMagicNB** [comment]
> 银捏？

推荐自己写 VB 和 WPF，现在的源码可以直接编译

**Comment by cnyzq** [comment]
OK
