### ISSUE TITLE
用户名为zmwdz出现游戏启动失败

### ISSUE THREAD

**Issue by skilahello** [Hex-Dragon/PCL2#4013]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃基本不是 PCL 的原因，请 **不要** 提交反馈。你可以在论坛或社区找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用 HMCL 启动，HMCL 没有出现问题。** 如果 HMCL 也无法启动就不是 PCL 导致的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

UUID报错IllegalArgumentException

### PCL 错误报告、日志与附件

[游戏崩溃前的输出.txt](https://github.com/user-attachments/files/15800224/default.txt)
[PCL 启动器日志.txt](https://github.com/user-attachments/files/15800226/PCL.txt)

**Comment by skilahello** [comment]
JDK--21--22出现问题

**Comment by skilahello** [comment]
处理UUID字符串0000000000003005998F50309B45FD5时出错

**Comment by skilahello** [comment]
问题出现在 fromStringLenient 方法中

**Comment by Silverteal** [comment]
或许可以尝试构建 [PCL-Community/PCL2-Uuid-Fix](/PCL-Community/PCL2-Uuid-Fix) 并启动，看看是否存在相同问题？
PCL的UUID格式一直比较怪

**Comment by skilahello** [comment]
使用zmwdz这个用户名发现了这个问题--测试其他的没有问题复现---可能还有其他用户名有这个问题

**Comment by Silverteal** [comment]
如果UUID是`0000000000003005998F50309B45FD5`的话，不难发现UUID字符串少了一位。

**Comment by skilahello** [comment]
是的--正式版中--使用其他用户名没有发现问题----只有zmwdz发现这个问题

**Comment by skilahello** [comment]
好的我试一下

**Comment by skilahello** [comment]
构建 [PCL-Community/PCL2-Uuid-Fix](https://github.com/PCL-Community/PCL2-Uuid-Fix) 并启动
使用zmwdz为用户名没有发现相关问题

**Comment by skilahello** [comment]
[Uuid-Fix] 根据用户名生成的离线 UUID：a4cbd3b0f8183c52ab44360aa83a7edb

**Comment by Silverteal** [comment]
注意到日志中的这一行：
`[15:06:45.403] [Launch] 正在构建自定义皮肤资源包，格式为：17`
玩家似乎设置了自定义皮肤。这可能也是导致问题的原因之一。

**Comment by skilahello** [comment]
我调整一下---保证和问题环境一致

**Comment by Silverteal** [comment]
哦，我猜是自定义资源包生成对应体型UUID的时候忘记补足最后五位的前导0了

**Comment by skilahello** [comment]
使用正式版，选择随机皮肤,可以正常启动
使用UUID-Fix版本，选择自定义皮肤，可以正常启动

也就是--正式版使用自定义皮肤--并且用户名为zmwdz--出现了启动失败

**Comment by skilahello** [comment]
[Log1.txt](https://github.com/user-attachments/files/15801258/Log1.txt)
UUID-Fix生成的Log

**Comment by RimacC2-EV** [comment]
<del>为啥你们都能发现这么诡异的Bug······能教教我吗</del>

**Comment by Silverteal** [comment]
我提交了PR #4018 尝试修复此问题

---
我完整复盘一下问题原因。造成此问题需要：

1. 使用离线模式启动，且离线皮肤选项是”自定义“
2. PCL根据用户名生成的默认UUID的体型和加载的离线皮肤体型不符
3. PCL迭代UUID生成符合体型的UUID时，最终生成产生物中存在前导0

造成问题的原因是作者改了上面忘了下面。
