### ISSUE TITLE
无法进行网络请求：未将对象引用设置到对象的实例

### ISSUE THREAD

**Issue by qbw101** [Hex-Dragon/PCL2#4015]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

复制网址后提示出现错误

### 重现步骤

1、点击登陆
2、然后在新打开的网页中输入账号和密码
3、将空白网页中的网址复制的对话框，点击登陆
4、提示错误

### 日志与附件

![屏幕截图 2024-06-12 210914](https://github.com/Hex-Dragon/PCL2/assets/106949188/1413dcc5-a736-4eac-ace3-e78e81fac7cb)
[Log1.txt](https://github.com/user-attachments/files/15805606/Log1.txt)

**Comment by LTCatt** [comment]
需要重现，看 log 似乎识别码变了？

**Comment by SALTWOOD** [comment]
报：Prism Launcher 也有类似的无法登录问题，怀疑是API改动？

**Comment by scp020** [comment]
本机win10家庭版，使用最新pcl2启动器，问题可以复现

**Comment by LTCatt** [comment]
依然无法复现，怀疑和这个相关：https://stackoverflow.com/questions/36475310/webrequest-create-throws-system-nullreferenceexception
反馈者的所有网络请求都抛出了这个异常，所以应该是底层相关的东西，和登录没有太大关系。
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/9db63a68-5f7c-468b-a6a3-505094572c84)
需要更多人的复现情况汇报，这可能和系统环境有关。

**Comment by Silverteal** [comment]
反馈者能否确认自己的.NET Framework版本？

**Comment by qbw101** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/106949188/13c9421c-ffb9-4c0f-8d98-6f32148f811c)
是这个吗？

**Comment by scp020** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/125243551/776effd1-e97f-4c34-9884-e3a4099001c1)

4.8.9037.0

**Comment by scp020** [comment]
> ![image](https://private-user-images.githubusercontent.com/106949188/339703321-13c9421c-ffb9-4c0f-8d98-6f32148f811c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNTU1ODIsIm5iZiI6MTcxODM1NTI4MiwicGF0aCI6Ii8xMDY5NDkxODgvMzM5NzAzMzIxLTEzYzk0MjFjLWZmYjktNGMwZi04ZDk4LTZmMzIxNDhmODExYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNFQwODU0NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MGIwZjQxYmI0ZDZiODYwYmY5ZTQxNGM2ZTg3MzQ4ODI1NzIxODY3NGI4N2FmYTQ4NzRkNDMxN2U2MGNlYjVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Wjii49EvdXXRdP1x60VHdBjXIOqonV4j-T4qjxbXBt4) 是这个吗？

不能这么看，你需要像我这样做，才能看到你的真正版本。

**Comment by Silverteal** [comment]
> ![image](https://private-user-images.githubusercontent.com/106949188/339703321-13c9421c-ffb9-4c0f-8d98-6f32148f811c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNTU3NzMsIm5iZiI6MTcxODM1NTQ3MywicGF0aCI6Ii8xMDY5NDkxODgvMzM5NzAzMzIxLTEzYzk0MjFjLWZmYjktNGMwZi04ZDk4LTZmMzIxNDhmODExYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNFQwODU3NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iODI3MDEwMTE3NzQwZWFmNWE3MGRlYzNmODA3MjMzYWVlYjRlZjdlNWY5YWMyNjhiYzBhNTE4YWYzNGJlNzhlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zYiJAUMh2MmguFMj_8kQ5yskMWZOvhbZ_g9A4zSPuvA)
> 是这个吗？

不是，根据Microsoft Learn，“最简单的方法是通过“控制面板”>“程序”>“程序和功能”进行检查，或者在“设置”中的“应用”>“已安装的应用”下进行检查。”

**Comment by Silverteal** [comment]
> ![image](https://private-user-images.githubusercontent.com/125243551/339704413-776effd1-e97f-4c34-9884-e3a4099001c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNTYwMDksIm5iZiI6MTcxODM1NTcwOSwicGF0aCI6Ii8xMjUyNDM1NTEvMzM5NzA0NDEzLTc3NmVmZmQxLWU5N2YtNGMzNC05ODg0LWUzYTQwOTkwMDFjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNFQwOTAxNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YzU4YmRmZGY0NzhjNWVlOWE4ZWEyZTNiZjkwNDk5MTFhNDAwMDJjN2Y0Njc1YWFjOWYyZTE0MjIyMzAzYTVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yy-h-LgQ_y-rNGPV8UDIT2QBu8ERrZdlj04gT6Aqq1c)
> 
> 4.8.9037.0

我问的不是这个，你这个是生成工具的版本

**Comment by qbw101** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/106949188/c85371e0-da8a-4aa7-ab10-e97dbfffd7b9)
这个？

**Comment by Silverteal** [comment]
> ![image](https://private-user-images.githubusercontent.com/106949188/339707648-c85371e0-da8a-4aa7-ab10-e97dbfffd7b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNTgwNTMsIm5iZiI6MTcxODM1Nzc1MywicGF0aCI6Ii8xMDY5NDkxODgvMzM5NzA3NjQ4LWM4NTM3MWUwLWRhOGEtNGFhNy1hYjEwLWU5N2RiZmZmZDdiOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNFQwOTM1NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNDc0MjhkYmFjZmRjNzVhYmFiYTdjMTE1ODQ5ODdlYWU2Nzg0MzQ5ZWQ3ZGUwM2Q5ZThiN2UxODdhOTM4YWMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.S4Q53kdFhin4bPdg9eZ82Z27anywMwqOxxOxLdAQ5kE)
> 这个？

呃..理论上应该是，但是这张图里没有，试试注册表那个方法？

**Comment by qbw101** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/106949188/55a023fd-0660-4390-b7f8-2d9bd390f605)
是这样子吗？

**Comment by Silverteal** [comment]
> 是这样子吗？
是；.NET Framework版本是4.8.1，应该没什么问题

**Comment by scp020** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/125243551/f1a50b33-9517-4356-b235-1116d1a14e87)

我跟他一样

**Comment by LTCatt** [comment]
@scp020 能否提供出错时的启动器日志？

**Comment by scp020** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/125243551/a2cee5b4-4036-40d6-a566-b1c1f9b34f86)

@LTCatt

**Comment by Pigeon0v0** [comment]
> ![image](https://github.com/Hex-Dragon/PCL2/assets/125243551/a2cee5b4-4036-40d6-a566-b1c1f9b34f86)
> 

麻烦提供文件

**Comment by allMagicNB** [comment]
> ![image](https://github.com/Hex-Dragon/PCL2/assets/125243551/a2cee5b4-4036-40d6-a566-b1c1f9b34f86)
> 
> @LTCatt 

发 Log1.txt～Log5.txt 而不是截屏

**Comment by scp020** [comment]
[Log4.txt](https://github.com/user-attachments/files/15846530/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/15846531/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/15846532/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/15846533/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/15846534/Log3.txt)

**Comment by Silverteal** [comment]
> ![image](https://private-user-images.githubusercontent.com/125243551/339971458-a2cee5b4-4036-40d6-a566-b1c1f9b34f86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0NDg1MjQsIm5iZiI6MTcxODQ0ODIyNCwicGF0aCI6Ii8xMjUyNDM1NTEvMzM5OTcxNDU4LWEyY2VlNWI0LTQwMzYtNDBkNi1hNTY2LWIxYzFmOWIzNGY4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNVQxMDQzNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMzhlNmVmYzI2NjgyNjA0MzgwYzI5MmIxMjhmMWJhZDExYjUxYWI3YTM4NGJmODcxNDgyMDdmY2NlODI3ZmVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.L9TxcKuQRCgoxr0VDhxQz97KfrmySEa2dXiXEK-YBAI)
> 
> @LTCatt

您是不是使用了 `Steamcommunity 302`，`Watt Toolkit` 或类似的工具？这类工具的特征是需要安装一个根证书。

**Comment by scp020** [comment]
> > ![image](https://private-user-images.githubusercontent.com/125243551/339971458-a2cee5b4-4036-40d6-a566-b1c1f9b34f86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0NDg1MjQsIm5iZiI6MTcxODQ0ODIyNCwicGF0aCI6Ii8xMjUyNDM1NTEvMzM5OTcxNDU4LWEyY2VlNWI0LTQwMzYtNDBkNi1hNTY2LWIxYzFmOWIzNGY4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNVQxMDQzNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMzhlNmVmYzI2NjgyNjA0MzgwYzI5MmIxMjhmMWJhZDExYjUxYWI3YTM4NGJmODcxNDgyMDdmY2NlODI3ZmVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.L9TxcKuQRCgoxr0VDhxQz97KfrmySEa2dXiXEK-YBAI)
> > @LTCatt
> 
> 您是不是使用了 `Steamcommunity 302`，`Watt Toolkit` ，`Dev Sidecar` 等域前置网络工具？这类工具的特征是需要安装一个根证书。

额，我没用，我甚至没听过这三个东西

**Comment by Silverteal** [comment]
那么请使用火绒（或者其它方式）打开您的hosts文件，并将其中不以井号开头的内容发上来

**Comment by allMagicNB** [comment]
基本断定@scp020 这位的 hosts 文件有问题

**Comment by scp020** [comment]
> 基本断定@scp020 这位的 hosts 文件有问题，与主题无关。

请问之前有没有解决这类问题的issue之类的，我该怎么解决

**Comment by Silverteal** [comment]
我不认为hosts文件是导致问题的原因，更有可能是本地运营商DNS墙了域名。
但可以确定的是和这个issue无关。

**Comment by scp020** [comment]
> > 请问之前有没有解决这类问题的issue之类的，我该怎么解决
> > 我不认为hosts文件是导致问题的原因，更有可能是本地运营商DNS墙了域名。
> 
> 但可以确定的是和这个issue无关。 可以尝试参照 #3505 操作

谢谢！！！

**Comment by LTCatt** [comment]
@scp020 的问题是自己系统或者网络配置的问题，不是 #4015 导致的

**Comment by SALTWOOD** [comment]
报：
Windows 10 22H2 19045.4529 复现失败，日志无异常，
![image](https://github.com/Hex-Dragon/PCL2/assets/105980161/df495da7-7992-4459-8afc-032e70cd1cac)

**Comment by MCSteve123** [comment]
Windows 22H2 19045.3393复现失败：无异常
截图：
![image](https://github.com/Hex-Dragon/PCL2/assets/121204926/baa59ee6-4960-4737-922b-8a69e5c5a3ed)
![image](https://github.com/Hex-Dragon/PCL2/assets/121204926/db87e02d-2bfd-4f1e-aee8-650213508f76)
日志：[Log1.txt](https://github.com/user-attachments/files/15856034/Log1.txt)

**Comment by youzi-2333** [comment]
这个是别人的 log，不仅仅是正版登录，任何涉及到网络请求的都炸了……

[Log1.txt](https://github.com/user-attachments/files/15866120/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/15866122/Log2.txt)

**Comment by MCSteve123** [comment]
> 这个是别人的 log，不仅仅是正版登录，任何涉及到网络请求的都炸了……
> 
> [Log1.txt](https://github.com/user-attachments/files/15866120/Log1.txt) [Log2.txt](https://github.com/user-attachments/files/15866122/Log2.txt) [Log3.txt](https://github.com/user-attachments/files/15866165/Log3.txt) [Log4.txt](https://github.com/user-attachments/files/15866169/Log4.txt) [Log5.txt](https://github.com/user-attachments/files/15866173/Log5.txt)

意思是获取网络主页、下载都不能用？

**Comment by LTCatt** [comment]
参考 https://stackoverflow.com/questions/2522160/webrequest-create-problem
请尝试重新安装 .net framework，这不是 PCL 导致的问题

**Comment by LTCatt** [comment]
要判断与此重复的 issue：
- 网络请求出现 NullReferenceException
- 堆栈中存在 WebRequest.get_PrefixList
