### ISSUE TITLE
允许自由切换自定义下载处于当前文件夹/绝对路径

### ISSUE THREAD

**Issue by iPodtouch6557** [Hex-Dragon/PCL2#4019]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

描述
这样在我迁移整个游戏文件是可以省一步操作
同样可以更加方便的管理电脑文件夹

原因
这项优化可以把下载更方便，不用到处挪动，顺带就更加让电脑整洁

### 原因

（示例）
这项优化让我可以更方便地xxxx。
如果没有这项优化，我每次都必须xxxx，让操作变得很麻烦。

**Comment by Deep-Dark-Forest** [comment]
#2498 和这个的区别是啥（

**Comment by iPodtouch6557** [comment]
我想魔改一下，但是想了还是提交个新的合适
原来的issue不是这个内容

**Comment by LTCatt** [comment]
适用面小的现在做不过来的，望理解 orz
