### ISSUE TITLE
下载管理启动线程 0 出错：集合已修改

### ISSUE THREAD

**Issue by chengzi-sc** [Hex-Dragon/PCL2#4021]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

启动时pcl崩溃

### 重现步骤

1、点击启动

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/15825385/Log1.txt)

**Comment by LTCatt** [comment]
Line 17285:
```
[00:24:29.763] 下载管理启动线程 0 出错：集合已修改；可能无法执行枚举操作。
   在 System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   在 System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   在 System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   在 PCL.ModNet.NetManagerClass._Lambda$__18-0(Int32 Id)
错误类型：System.InvalidOperationException
```
