### ISSUE TITLE
用已赞助的有关信息来取消请求赞助弹窗

### ISSUE THREAD

**Issue by Tomalisa** [Hex-Dragon/PCL2#4023]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

目前在普通PCL2启动器里，启动MC达到特定整数次数之后会跳出来请求赞助的弹窗，但是我已经赞助过PCL2 只是由于不想使用赞助版本启动器所以一直用的普通版，我想看看有没有什么方法可以在普通版本导入赞助信息，或者验证赞助者身份来取消普通版本的赞助提示弹窗？这弹窗要是真的能完成我必接着赞助更多

### 原因

这项优化让我可以更沉浸的启动mc，因为我需要经常切换本地账号工具人的原因，我启动次数会大大增加，所以时不时的一个弹窗会很难受（毕竟已经赞助过了 虽然不多），而且要狠心拒绝才能关闭窗口（这让我非常难过ono）

**Comment by LTCatt** [comment]
umm 所以是为啥不想用快照版……

**Comment by Tomalisa** [comment]
赞助版本启动器的额外界面不是很好看，然后很多版本的信息都要重新弄，和普通启动器不是同一个路径好像，所以就不想用了，不方便。

**Comment by LTCatt** [comment]
你直接替换文件就行了，会是同一个路径……
