### ISSUE TITLE
加入“手动输入内存数字以修改内存大小的功能”以增加拓展性和精确度

### ISSUE THREAD

**Issue by yuanlai202116** [Hex-Dragon/PCL2#4024]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

加入“手动输入内存数字以修改内存大小的功能”，比如图中的“10GB”，可以被点击并且可敲入数字修改大小例如20GB（建议支持小数或已MB作为单位），更精确，拓展性也更强
![屏幕截图 2024-06-14 0040152](https://github.com/Hex-Dragon/PCL2/assets/159740203/a3eb52f7-d3f1-43bf-b203-cc61468d2806)

### 原因

这项优化让我可以更精确地调整内存大小，并且可以分配比物理内存更大的内存让游戏运行。
比如我是16GB的电脑，有时需要分配大内存给游戏，HMCL可以输入“24000MB”甚至更高并且不会崩溃，而PCL只能设置16GB，再大就设置不了了。
如果没有这项优化，那么就无法分配大内存给MC，自定义空间下降，也无法精确调整大小，让操作变得很麻烦。
![屏幕截图 2024-06-14 005507](https://github.com/Hex-Dragon/PCL2/assets/159740203/9cf57c00-11f8-483b-b05a-8dd8b9ed6c14)

**Comment by LTCatt** [comment]
意义不大。
并且你内存一共就 16G，你分 20G 搞毛……
