### ISSUE TITLE
正式版2.7.4中点击更多--关于与鸣谢--赞助者中的输入解锁码按钮启动器会卡住然后闪退

### ISSUE THREAD

**Issue by mc7430** [Hex-Dragon/PCL2#4026]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

打开启动器点击更多--关于与鸣谢--赞助者中的输入解锁码按钮启动器会卡住然后闪退

### 重现步骤

1.打开启动器
2.点击更多
3.关于与鸣谢
4.找到赞助者那一栏
5.点击输入解锁码按钮

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/15833013/Log1.txt)

**Comment by mc7430** [comment]
系统为Windows11家庭版

**Comment by Ad-closeNN** [comment]
#3990
