### ISSUE TITLE
增加虚拟机检测 启动游戏时检测当前硬件是否为虚拟机

### ISSUE THREAD

**Issue by Zane54258** [Hex-Dragon/PCL2#4027]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

启动游戏时检测当前硬件，如果在硬件信息中检测出VMware、VirtualBox等字眼，即视为使用虚拟机启动Minecraft，启动时弹出警告询问是否仍要启动或者取消启动

### 原因

警告使用虚拟机启动游戏的玩家，用虚拟机启动Minecraft可能会导致无法正常启动或其他问题，提醒玩家建议使用实体电脑（物理机）启动Minecraft

**Comment by zkitefly** [comment]
怎么检测呢？🤔

**Comment by wuliaodexiaoluo** [comment]
硬件信息和硬件 id 并不能作为虚拟机检测的依据，因为这些信息是可以被修改的，并且虚拟机环境基本类似实体机，如果是显卡等硬件问题，想在虚拟机玩 mc 的人大概率也会搞显卡虚拟化

**Comment by Silverteal** [comment]
会使用虚拟机的玩家应该有这个能力判断在虚拟机启动的利弊和可能存在的问题，不必多此一举。

**Comment by Shiroiame-Kusu** [comment]
检测的意义是什么🤔

**Comment by Deep-Dark-Forest** [comment]
那关了吧，自己用的什么机应该清楚吧（
