### ISSUE TITLE
增加支持启动器设置48GB*2的内存条自定义96GB

### ISSUE THREAD

**Issue by KevinMKRL** [Hex-Dragon/PCL2#4028]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

我的内存条是英睿达的96GB DDR5 5200MHz我在启动器设置中自定义内存发现最大支持64GB的内存，我希望可以增加支持到96GB或者更高

### 原因

这项优化让我可以更流畅的游玩游戏和大型整合包

**Comment by zkitefly** [comment]
https://github.com/Hex-Dragon/PCL2/issues/4024

**Comment by allMagicNB** [comment]
没重呢，你是不是眼花了

**Comment by zkitefly** [comment]
抱歉看错了（

**Comment by JingHai-Lingyun** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/109946426/bdac3b75-7a08-455a-9240-e9b3b7d7b855)
关了（
