### ISSUE TITLE
什么项目这么臭（

### ISSUE THREAD

**Issue by shikukuya** [Hex-Dragon/PCL2#403]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![Uploading image.png…]()

### 重现步骤

1、在文件中查找
2、输入mymsg

### 日志与附件

没有（）

**Comment by xxtg666** [comment]
？
