### ISSUE TITLE
资源下载（模组和整合包下载）中版本筛选选项无 1.21

### ISSUE THREAD

**Issue by WForst-Breeze** [Hex-Dragon/PCL2#4031]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

每个正式版出来之后都会有的一个小问题，1.21 现已发布 qwq

### 重现步骤

下载-资源（模组/整合包）

### 日志与附件

此问题应当无需日志

**Comment by allMagicNB** [comment]
并不是，这是写死的列表，不是实时获取的。
要再加的话，先等等吧，说不定 1.21.1 就出来了……（

**Comment by WorldHim** [comment]
虽然但是这个应该是大版本（指模组/整合/资源包相对较为丰富的版本）才添加的，是否需要观察几天？

**Comment by WForst-Breeze** [comment]
> 并不是，这是写死的列表，不是实时获取的。

这点我是知道的

> 要再加的话，先等等吧，说不定 1.21.1 就出来了……（

并没有说现在就加（）按照麻酱的风格确实会这样，等下次 PCL 更新前依照 MC 最新版本加就好了

**Comment by SALTWOOD** [comment]
> I think we should wait. A developer on X expressed the possibility of 1.21.1.
> 
> [Java Edition 1.21.1 – Minecraft Wiki](https://minecraft.wiki/w/Java_Edition_1.21.1)

Maybe. But add 1.21 to the list is necessary too
