### ISSUE TITLE
自动安装1.21版本fabric选项无法使用

### ISSUE THREAD

**Issue by skybeach-None** [Hex-Dragon/PCL2#4032]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如题，fabric已更新1.21用版本

### 重现步骤

自动安装或手动安装

### 日志与附件

[log.zip](https://github.com/user-attachments/files/15838480/log.zip)

**Comment by allMagicNB** [comment]
截屏下？

**Comment by skybeach-None** [comment]
> 截屏下？

![image](https://github.com/Hex-Dragon/PCL2/assets/152578017/f6fd2b12-215e-42ed-8bb0-c25737a59091)

**Comment by allMagicNB** [comment]
上传日志

**Comment by skybeach-None** [comment]
> 上传日志

[log.zip](https://github.com/user-attachments/files/15838547/log.zip)

**Comment by allMagicNB** [comment]
应该是BMCLAPI 的问题，把 `设置 - 启动器 - 下载 - 版本列表获取` 改成 `尽量使用官方源（保证版本为最新，但加载非常缓慢）` 再试试

**Comment by skybeach-None** [comment]
> 应该是BMCLAPI 的问题，把 `设置 - 启动器 - 下载 - 版本列表获取` 改成 `尽量使用官方源（保证版本为最新，但加载非常缓慢）` 再重启启动器试试。

解决了
