### ISSUE TITLE
mc更新之后新版本总是不会显示在版本列表

### ISSUE THREAD

**Issue by skybeach-None** [Hex-Dragon/PCL2#4033]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/Hex-Dragon/PCL2/assets/152578017/cc09340b-88b6-4a17-98d3-a4c6d8c6ab34)
无法找到mc1.21

### 重现步骤

安装界面

### 日志与附件

[lg.zip](https://github.com/user-attachments/files/15839066/lg.zip)

**Comment by JingHai-Lingyun** [comment]
![d908545a806c9aab4e0920f9d4b8205c](https://github.com/Hex-Dragon/PCL2/assets/109946426/e9b7ce6b-c9ce-4a6c-a2ad-1652725c1c9d)
