### ISSUE TITLE
把三个主页面功能隐藏后，“启动”也会消失

### ISSUE THREAD

**Issue by WYC-E** [Hex-Dragon/PCL2#4035]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

 把三个主页面功能隐藏后，“启动”也会消失
把下载、设置、更多都隐藏后，启动也会消失

https://github.com/Hex-Dragon/PCL2/assets/133771901/0c55e26f-411d-4af7-8432-b8846d16c8ab

### 重现步骤

把下载、设置、更多都隐藏

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/15841485/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/15841486/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/15841487/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/15841488/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/15841489/Log5.txt)

**Comment by JingHai-Lingyun** [comment]
因为这时候没有可用的其他页面了，就隐藏掉了
但是这样导致了你不重启/F12没法回到首页，挂着……看看？

**Comment by LTCatt** [comment]
重启 PCL 后就行，毕竟都隐藏了也没必要一个启动单挂上面，WAI
