### ISSUE TITLE
重新打开PCL不会显示游戏已启动

### ISSUE THREAD

**Issue by skybeach-None** [Hex-Dragon/PCL2#4037]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

重新打开后右下角没有显示游戏已启动的标识
![image](https://github.com/Hex-Dragon/PCL2/assets/152578017/0cfb40f2-3b78-4e77-8420-d00d2929a3c3)

### 重现步骤

启动游戏，退出启动器，重新打开启动器

### 日志与附件

[Log.zip](https://github.com/user-attachments/files/15845513/Log.zip)

**Comment by allMagicNB** [comment]
#1243

**Comment by allMagicNB** [comment]
哥们为了个主题不至于这样啊哥们
