### ISSUE TITLE
添加curseforge整合包更新功能

### ISSUE THREAD

**Issue by Cool1446** [Hex-Dragon/PCL2#4039]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

希望可以像FTB启动器或者curseforge启动器那样可以直接检测到整合包的更新，可以一键更新到新版本，包括存档和设置

### 原因

目前需要手动更新整合包，并且如果不去curseforge查看甚至都不知道整合包已经更新了，emmm，其实就是懒。。。

**Comment by allMagicNB** [comment]
#2854
