### ISSUE TITLE
使用内存优化后出现的问题

### ISSUE THREAD

**Issue by MoIei** [Hex-Dragon/PCL2#4041]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

使用内存优化后不显示在桌面上的前台软件全部都会白屏，打开后需要一段时间才会响应，而短时间内多次使用内存优化会导致磁盘占用100%(我在使用两次后磁盘占用就达到百分百并且系统卡死)

### 重现步骤

在PCL 2.7.4版本里单次或多次点击"内存优化“即可复现

### 日志与附件

[Log3.txt](https://github.com/user-attachments/files/15846591/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/15846592/Log4.txt)
[Log1.txt](https://github.com/user-attachments/files/15846593/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/15846594/Log2.txt)

注：PCL根目录里并没有Log5.txt

**Comment by Silverteal** [comment]
我会建议你少点几次内存优化……
这属于一种刻意触发

**Comment by MoIei** [comment]
第一次点击后我的电脑已经出现磁盘占用100%了，但是等待1-2分钟就会降下来，但是降下来后再次点击内存优化后我的电脑就直接系统卡死，什么都没反应，只能强制重启

**Comment by hejiehao** [comment]
系统卡死是 Windows 文件资源管理器卡死吗？

**Comment by JingHai-Lingyun** [comment]
已知机械硬盘在内存优化的时候会带来高占用和系统卡顿

**Comment by MoIei** [comment]
我使用的是SATA固态硬盘

**Comment by MoIei** [comment]
并且使用检测工具没有检测到坏道，可以排除是磁盘损坏的可能

**Comment by MoIei** [comment]
> 系统卡死是 Windows 文件资源管理器卡死吗？
目前不能找出具体原因，因为触发后桌面就白屏提示未响应，无法继续操作

**Comment by allMagicNB** [comment]
你硬盘太慢了吧……

**Comment by Silverteal** [comment]
对**固态硬盘**执行**坏道扫描**极有可能会造成硬盘不可逆的损伤，不要尝试。

**Comment by MoIei** [comment]
> 你硬盘太慢了吧……
![dedb5775612dbf27bc4279c984bb175](https://github.com/Hex-Dragon/PCL2/assets/142684835/1eab6bcf-5971-4e09-902b-1d3cc003b60b)

**Comment by MoIei** [comment]
> **坏道扫描**是为机械硬盘设计的，对**固态硬盘**执行**坏道扫描**极有可能会造成硬盘不可逆的损伤，不要尝试。

我是已经发现这个问题后为了排除硬盘问题才进行的坏道检测

**Comment by MoIei** [comment]
![a26b7bd7459e1248e86cdd344968f9a](https://github.com/Hex-Dragon/PCL2/assets/142684835/4ebe413a-087b-45f7-a871-9973e7d0f102)


> 你硬盘太慢了吧……

**Comment by allMagicNB** [comment]
> ![a26b7bd7459e1248e86cdd344968f9a](https://github.com/Hex-Dragon/PCL2/assets/142684835/4ebe413a-087b-45f7-a871-9973e7d0f102)
> 
> 
> > 你硬盘太慢了吧……
> 
> 

右边 Write 呢？

**Comment by MoIei** [comment]
![ad3d6c65b0f7de20b2342b65c4095ec](https://github.com/Hex-Dragon/PCL2/assets/142684835/55cd3ca2-93e8-4113-bdcc-ad9153d23b5b)

**Comment by allMagicNB** [comment]
> ![ad3d6c65b0f7de20b2342b65c4095ec](https://github.com/Hex-Dragon/PCL2/assets/142684835/55cd3ca2-93e8-4113-bdcc-ad9153d23b5b)
> 

C 盘能测下吗

**Comment by MoIei** [comment]
![d973fd99e2cb51416d7a3684103effa](https://github.com/Hex-Dragon/PCL2/assets/142684835/bd2d40a7-ba0d-436b-b485-0c88eb08bf2f)

**Comment by Silverteal** [comment]
> 我是已经发现这个问题后为了排除硬盘问题才进行的坏道检测

无关，对固态硬盘执行坏道扫描不仅不能排除问题，还会造成硬盘损坏。因为固态硬盘没有道，也就没有坏道，反而坏道扫描会因为高强度的读写操作损坏主控芯片。

**Comment by MoIei** [comment]
> > 我是已经发现这个问题后为了排除硬盘问题才进行的坏道检测
> 
> 无关，对固态硬盘执行坏道扫描不仅不能排除问题，还会造成硬盘损坏。因为固态硬盘没有道，也就没有坏道，反而坏道扫描会因为高强度的读写操作损坏固态硬盘特有的主控芯片。

读写测试上来看我的固态硬盘目前还是没有问题的吧

**Comment by LTCatt** [comment]
这是电脑环境和配置问题，PCL 无法解决……
