### ISSUE TITLE
[建议]从源代码中移除“最新正式版.zip”

### ISSUE THREAD

**Issue by SALTWOOD** [Hex-Dragon/PCL2#4043]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

大部分来这里的人都是为了交 issue 或者下源代码的吧
加一个“最新正式版.zip”有点多余（？
而且我没记错的话，git 版本管理系统似乎并不适合存储二进制文件
也不知道对不对，龙猫您自己定夺（

### 原因

似乎可以加快拉取仓库（？

**Comment by allMagicNB** [comment]
加快拉取仓库速度纯属无稽之谈（

**Comment by SALTWOOD** [comment]
> 加快拉取仓库速度纯属无稽之谈，2 MB 能加快啥（

主要是没谁下罢，本着多余就可以砍的原则（

**Comment by Silverteal** [comment]
第一，Git不适合存储二进制这一观点不能绝对化。实际上只是提交对比差异的时候无法和纯文本一样逐行对比和快速合并变更。
第二，目前除了这里之外没有一个可靠的地方存储历史正式版。
第三，这个文件在正式版更新的时候疑似会用到

**Comment by wuliaodexiaoluo** [comment]
事实上，Release 的更新时请求的就是这个文件，龙猫扔这里面大概率是希望使用 GitHub Raw 来节约 COS 流量成本（国内 COS 提供商流量收的死贵）

至于 Git 不适合二进制 diff，其实并不影响 PCL

**Comment by WorldHim** [comment]
不考虑其他因素下还是 release 更适合塞附件

**Comment by Silverteal** [comment]
> 不考虑其他因素下还是 release 更适合塞附件

说实话很有道理。

**Comment by LTCatt** [comment]
目前还没有移除它并且换到其他地方更新的必要……
