### ISSUE TITLE
自动下载Java的显示错误

### ISSUE THREAD

**Issue by MoIei** [Hex-Dragon/PCL2#4044]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我电脑是只有Java8的，在安装1.19.2时PCL本应提示需要安装Java17，却显示需要下载Java8，我允许PCL自动下载后下载出来的是Java17，
![f5cfa05f972c9f60a6064dcc7af7014](https://github.com/Hex-Dragon/PCL2/assets/142684835/3579bafe-8ab8-4a1c-a8c8-1effcaee7ab7)

### 重现步骤

在未安装Java17的情况下自动下载1.19.2-Forge_43.4.0会弹出提示

### 日志与附件

[Log3.txt](https://github.com/user-attachments/files/15847656/Log
[Log5.txt](https://github.com/user-attachments/files/15847658/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/15847659/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/15847660/Log2.txt)
3.txt)
[Log4.txt](https://github.com/user-attachments/files/15847657/Log4.txt)

**Comment by MoIei** [comment]
![f5cfa05f972c9f60a6064dcc7af7014](https://github.com/Hex-Dragon/PCL2/assets/142684835/5b023c88-85f1-4d4b-991b-76de9c88d80d)

**Comment by JingHai-Lingyun** [comment]
只是**提示错误**还是下载的也是错误的？

**Comment by MoIei** [comment]
补充：自动下载游戏版本时我的电脑仅有Java8.0.51

**Comment by wuliaodexiaoluo** [comment]
请您注意下提示弹窗内的字符

### 未找到 Java 8 或更高版本

**Comment by MoIei** [comment]
补充：在没有Java的情况下安装带forge的高版本会直接提示错误，而安装带forge的低版本情况下会直接安装成功（可能是偶然事件，重新启动后就正常了）
![Uploading 49106288c
![830b7eec81014fa9b0d428ac0100b4c](https://github.com/Hex-Dragon/PCL2/assets/142684835/b32ca6b1-a1f4-497d-bbed-ec911ce3b882)
1383c09ad65940c979f468.png…]()

**Comment by MoIei** [comment]
补充：在没有Java的情况下安装带forge的高版本会直接提示错误，而安装带forge的低版本情况下会直接安装成功（可能是偶然事件，重新启动后就正常了）

**Comment by MoIei** [comment]
![49106288c1383c09ad65940c979f468](https://github.com/Hex-Dragon/PCL2/assets/142684835/edc41dfd-d07f-491b-a5e7-9fb2c016a9b0)
![830b7eec81014fa9b0d428ac0100b4c](https://github.com/Hex-Dragon/PCL2/assets/142684835/7421ecae-50ca-4300-aab0-6e0e0c2f3b3d)

**Comment by MoIei** [comment]
> 请您注意下提示弹窗内的字符
> 
> ### 未找到 Java 8 或更高版本

我觉得还是要注明具体版本比较好

**Comment by SALTWOOD** [comment]
> > 请您注意下提示弹窗内的字符
> > ### 未找到 Java 8 或更高版本
> 
> 我觉得还是要注明具体版本比较好

但与具体事实不冲突，建议关闭另开一个优化 issue
