### ISSUE TITLE
[建议] 在下载 Java 页面显示具体的版本

### ISSUE THREAD

**Issue by MoIei** [Hex-Dragon/PCL2#4046]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在下载任何带模组安装器的版本下且没有相应的Java版本时会提示”未找到Java8或以上版本“我建议细化到具体的版本如Java8，Java17等，另外既然PCL有这个能力去做到自动下载Java的话我觉得把Java下载新增到手动安装包目录里面可以大大提高便携性，还有在自动安装Java时我觉得可以让用户自主选择安装目录，若不自主选择就安装到默认目录，用户的可操作性会增加。

### 原因

上面的优化我认为可以大幅度提高便携性和体验性，对于每个版本都提示“未找到Java8及以上”这个界面我认为是有点潦草了，而主要的是希望能把Java下载添加到手动安装包的目录里，有的时候需要下载特定的Java或者需要把Java下载到别的地方就不需要在再去原本有的Java里面去拷贝到别的地方了。

**Comment by JingHai-Lingyun** [comment]
> 每个版本都提示“未找到Java8及以上”这个界面

实际上对于 Java 17，Java 21 版本检查不满足的时候就是显示对应缺失的 Java 版本号
一般来讲，这种情况下的下载都是用户在没有安装对应 Java 启动游戏的时候发生
对于那些有需求的用户，他们应当懂得如何手动下载并安装到自己指定的位置

不过还是挂着看看吧

**Comment by SALTWOOD** [comment]
建议改成：**[建议] 在下载 Java 页面显示具体的版本**

**Comment by MoIei** [comment]
> > 每个版本都提示“未找到Java8及以上”这个界面
> 
> 实际上对于 Java 17，Java 21 版本检查不满足的时候就是显示对应缺失的 Java 版本号 一般来讲，这种情况下的下载都是用户在没有安装对应 Java 启动游戏的时候发生 对于那些有需求的用户，他们应当懂得如何手动下载并安装到自己指定的位置
> 
> 我先看看有没有重复

我在安装1.19.2_forge版本时照样提示未找到Java8及以上的版本，没有显示具体缺失哪个版本的Java

**Comment by MoIei** [comment]
![f5cfa05f972c9f60a6064dcc7af7014](https://github.com/Hex-Dragon/PCL2/assets/142684835/59e4bd97-1b07-4aed-b1d6-5691cfccfa1c)

**Comment by MoIei** [comment]
> 建议改成：**[建议] 在下载 Java 页面显示具体的版本**

还有一个我更

> ### 检查项
> * [x]  我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
> * [x]  我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。
> 
> ### 描述
> 在下载任何带模组安装器的版本下且没有相应的Java版本时会提示”未找到Java8或以上版本“我建议细化到具体的版本如Java8，Java17等，另外既然PCL有这个能力去做到自动下载Java的话我觉得把Java下载新增到手动安装包目录里面可以大大提高便携性，还有在自动安装Java时我觉得可以让用户自主选择安装目录，若不自主选择就安装到默认目录，用户的可操作性会增加。
> 
> ### 原因
> 上面的优化我认为可以大幅度提高便携性和体验性，对于每个版本都提示“未找到Java8及以上”这个界面我认为是有点潦草了，而主要的是希望能把Java下载添加到手动安装包的目录里，有的时候需要下载特定的Java或者需要把Java下载到别的地方就不需要在再去原本有的Java里面去拷贝到别的地方了。

把Java下载添加到手动安装包的目录里这个提议我会把它添加到新功能的lssues里

**Comment by LTCatt** [comment]
这是 OptiFine/Forge 安装需要一个 Java，它确实是任意的 “Java 8 或更高版本” 都行，这是准确的描述。当需要特定版本 Java 的时候，PCL 会给出不同的提示信息。
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/dc3f9b40-c0b0-4ccf-be16-176ceb462173)
![image](https://github.com/Hex-Dragon/PCL2/assets/40348278/94c1f02e-0ecb-4454-a991-e835207b1487)
