### ISSUE TITLE
jvm参数头&用户选择JAVA优化版本（如：阿里云dragonwell）

### ISSUE THREAD

**Issue by Gluttonous-fish** [Hex-Dragon/PCL2#4049]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

可以增加几个勾选选项，如：启动游戏直接打开存档参数等

### 原因

优化体验

**Comment by JingHai-Lingyun** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/109946426/2f8393a0-497b-4a2a-a213-68b85dc669ef)
？

**Comment by Gluttonous-fish** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/152754131/24fe43bc-4485-4fe7-813d-91c2e4b86442)

**Comment by JingHai-Lingyun** [comment]
启动哪个存档呢？
有点类似 https://github.com/Hex-Dragon/PCL2/issues/2551

**Comment by allMagicNB** [comment]
#2551
