### ISSUE TITLE
使PCL能够更新游戏版本中已有的Fabric等模组加载器

### ISSUE THREAD

**Issue by whr-39** [Hex-Dragon/PCL2#4051]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

用户可以在版本设置中选择组件管理来更新或修改 Fabric、Forge 的版本

### 原因

我需要这个功能来更新游戏版本中已安装的模组加载器。比如我配置了一个游戏版本或者整合包，但是模组加载器出了新版本之后，该游戏版本将会无法添加一些需要更高模组加载器版本的模组。如果重新下载一个游戏版本来安装更高版本的模组加载器，将会耗费较多的时间精力，并且可能导致后面下载的游戏版本缺少原先版本中的一些数据。因此，更新游戏版本中已有的模组加载器是有必要的。

**Comment by JingHai-Lingyun** [comment]
#220 #227

**Comment by allMagicNB** [comment]
#220（）#227
