### ISSUE TITLE
在自动安装中, 1.7.10-pre4 版本无法选择安装 Forge

### ISSUE THREAD

**Issue by 3gf8jv4dv** [Hex-Dragon/PCL2#4057]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

When you select game version 1.7.10-pre4 in _Automatic Installation (自动安装)_ of PCL2, the Forge version cannot be selected, and the launcher gives the reason _No version available (没有可用版本)_. 

<details>
<summary>Preview</summary>

![](https://github.com/Hex-Dragon/PCL2/assets/158490944/5d7514c0-6849-4dbb-80a4-06eb164b4dec)

</details>

And in fact, MinecraftForge already provides Forge for 1.7.10-pre4.

By contrast, after selecting 1.7.2 or 1.7.10, you can select the Forge version normally.

### 重现步骤

_Using version 2.7.4 released by LTCatt._

1. Open the launcher
2. Go to `下载 - 自动安装 - 预览版`
3. Select `1.7.10-pre4`

### 日志与附件

[Log1.txt](https://gist.github.com/3gf8jv4dv/e29c22125392287b92dc5929d5a4b2d8)

**Comment by LTCatt** [comment]
能装了，但启动会崩，但 HMCL 启动也会崩，我不知道咋回事
