### ISSUE TITLE
（急）在补全文件出现问题时更换镜像站

### ISSUE THREAD

**Issue by microsoft365FNULNU** [Hex-Dragon/PCL2#406]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

如标题，在补全文件出现问题时更换镜像站
具体一点就是在下载镜像站点返回错误（404）或者下载速度过慢时更换下载镜像站点并重新下载。

不过呢你们可能发现一个“错误”：不是已经有这个功能了么？
注意——补全文件
mcbbs的1.12.2的optifine最新版本似乎没了
然而pcl2他只认bbs，导致他补全不了了，他进不去游戏了
其实准确来说这是个bug，不过我试过其他的启动器，一样的问题
劝大家最近尽量不要再转移1.12.2版本到其他文件夹了（至少在问题修复前）

### 原因

mcbbs的1.12.2的optifine最新版本似乎没了
然而pcl2他只认bbs，导致他补全不了了，他进不去游戏了
其实准确来说这是个bug，不过我试过其他的启动器，一样的问题

**Comment by LTCatt** [comment]
补充 Log

**Comment by LTCatt** [comment]
超时关闭，如有需要可以重新开 Issue
