### ISSUE TITLE
1、点击更多/关于与鸣谢 2、往下滚，然后点击输入解锁码 3、PCL2会先卡顿直到未响应

### ISSUE THREAD

**Issue by MCkklltt** [Hex-Dragon/PCL2#4061]
### 检查项

- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

1、点击更多/关于与鸣谢
2、往下滚，然后点击输入解锁码
3、PCL2会先卡顿直到未响应

### 重现步骤

1、点击更多/关于与鸣谢
2、往下滚，然后点击输入解锁码
3、PCL2会先卡顿直到未响应

### 日志与附件

无

**Comment by MCkklltt** [comment]
1、点击更多/关于与鸣谢
2、往下滚，然后点击输入解锁码
3、PCL2会先卡顿直到未响应

**Comment by Deep-Dark-Forest** [comment]
请补充日志

**Comment by WorldHim** [comment]
怀疑与 #3990 相同
检查一下是不是正式版

**Comment by allMagicNB** [comment]
一般来说，就是

**Comment by MCkklltt** [comment]
最新版


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年06月18日 19:20 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Hex-Dragon/PCL2] 1、点击更多/关于与鸣谢 2、往下滚，然后点击输入解锁码 3、PCL2会先卡顿直到未响应 (Issue #4061) |

怀疑与 #3990 相同
检查一下是不是正式版

**Comment by MCkklltt** [comment]
没有日志


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年06月18日 19:10 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Hex-Dragon/PCL2] 1、点击更多/关于与鸣谢 2、往下滚，然后点击输入解锁码 3、PCL2会先卡顿直到未响应 (Issue #4061) |

请补充日志

**Comment by WorldHim** [comment]
@MCkklltt 请确认你使用的是否为正式版

**Comment by wuliaodexiaoluo** [comment]
？重复（
