### ISSUE TITLE
正式版中点击“输入解锁码”会导致PCL2崩溃

### ISSUE THREAD

**Issue by nvhkphx** [Hex-Dragon/PCL2#4066]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

点击更多-关于与鸣谢选项卡中的”输入解锁码“选项后，并不会像设置-启动器选项卡中的”输入解锁码“选项一样点击后出现”正式版无法使用主题功能，若你获得了解锁码，请在快照版中使用！“的提示，而是会直接导致程序崩溃。
以下是对比：
![1](https://github.com/Hex-Dragon/PCL2/assets/169328095/76defc35-79a7-438a-b90d-b6f92cb3b917)
![2](https://github.com/Hex-Dragon/PCL2/assets/169328095/d0b4ca00-0a16-4d7f-ac8b-b9ffc6bc5b83)  （此时程序已经崩溃）

### 重现步骤

1.进入“更多”选项卡
2.点击“关于与鸣谢”
3.点击“赞助者”中的”输入解锁码“选项

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/15902174/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/15902175/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/15902244/Log3.txt)

**Comment by allMagicNB** [comment]
#3990
