### ISSUE TITLE
设置个性化自定义主页每日推荐整合包错误

### ISSUE THREAD

**Issue by AhQi27** [Hex-Dragon/PCL2#4067]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

设置个性化自定义主页每日推荐整合包错误
![3a364a6a6e4c4566c08c2d98caa11d80](https://github.com/Hex-Dragon/PCL2/assets/167623799/a25cda8b-daf6-4fef-8a0b-bf4c474bff80)

### 重现步骤

1、点击设置
2、然后点击个性化
3、主要--->预设--->每日整合包推荐
4、返回启动

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/15904021/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/15904022/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/15904017/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/15904018/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/15904019/Log5.txt)

**Comment by allMagicNB** [comment]
找第三方反馈去
@wkea

**Comment by wkea** [comment]
已修复
增加了一个提示信息
![image](https://github.com/Hex-Dragon/PCL2/assets/52775998/dd12f3c6-1ab9-4b3e-bdc8-0643cbf6c5b1)

**Comment by AhQi27** [comment]
> 找第三方反馈去 @wkea

好的
