### ISSUE TITLE
日志文件极大内存，且生成

### ISSUE THREAD

**Issue by Aaolsm** [Hex-Dragon/PCL2#4071]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![cc9a670c33a028cb7f4bcc23a9d3be7e](https://github.com/Hex-Dragon/PCL2/assets/142470287/16022c2a-28b5-4d5e-b79b-b1ad6006394e)

如图log文件后缀均为PCL2所产生

### 重现步骤

正常游戏自动产生，不出几天就会100+G

### 日志与附件

之前的已经删了目前是没几分钟又出现的，文件太大无法上传

**Comment by allMagicNB** [comment]
这关 PCL 什么事？

**Comment by Aaolsm** [comment]
> 这关 PCL 什么事？

这就是这个文件是PCL里下载的版本呀

**Comment by allMagicNB** [comment]
离谱，目测怀疑联想电脑管家误报
试试 HMCL 启动会不会出现这问题？

**Comment by Aaolsm** [comment]
> 离谱，目测怀疑联想电脑管家乱报…… 试试 HMCL 启动会不会出现这问题？

不是，我看文件了，log后缀都是这个文件里的，当时给我D盘干满了我才发现这个问题

**Comment by allMagicNB** [comment]
……先给龙猫看看

**Comment by LTCatt** [comment]
这是 MC 的 log，不是 PCL 的 log。
PCL 的 log 名字为 Log1/2/3/4/5.txt，只有这五个文件。
