### ISSUE TITLE
关于崩溃检测

### ISSUE THREAD

**Issue by Jacksong75** [Hex-Dragon/PCL2#4072]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

一部分的mod冲突会导致程序崩溃而没有ERROR输出，迷惑性极强，比如(https://github.com/GroovyMC/GroovyModLoader/issues/23)
以下是几种可行的解决办法
-记录最后一次或最近几次成功启动的mod名单（输出文件名列表即可）
-截取log最后一行，并且与mod名单比对，根据匹配率输出mod出错可能性（可能不是很灵，看见过相关issues）
-设立名单，将一部分容易出现疑难杂症的mod比对，更好的确定问题
-可以设立临时文件夹管理mod，每次启动前将禁用的mod移出文件夹，让使用者手动调试（看见过issues，适用面很窄，或许可以附带个脚本？）

### 原因

这项优化可以更方便地调试某些疑难杂症mod，至少能够在80%正确率下调试mod。
会让天天问的人少很多……

**Comment by youzi-2333** [comment]
这个好复杂啊……不过理论上可以做

> 记录最后一次或最近几次成功启动的mod名单（输出文件名列表即可）

其实可以做成 mod ID，避免 mod 被重命名（）

> 截取log最后一行，并且与mod名单比对，根据匹配率输出mod出错可能性（可能不是很灵，看见过相关issues）

感觉这个和堆栈分析很像……

> 设立名单，将一部分容易出现疑难杂症的mod比对，更好的确定问题

现在有一些名单，例如 `ModCrash` 里面的枚举：

```
        NightConfig的Bug
        ShadersMod与Optifine同时安装
```

不过没有把容易出问题的 Mod 名单单独拿出来做……确实可以试试

> 可以设立临时文件夹管理mod，每次启动前将禁用的mod移出文件夹，让使用者手动调试（看见过issues，适用面很窄，或许可以附带个脚本？）

没太理解，为啥要把禁用的 Mod 移出去……？

如果龙猫加进投票的话，我可以试试交个 pr（

**Comment by zkitefly** [comment]
> 其实可以做成 mod ID，避免 mod 被重命名（）is:issue 记录 mod

modid 也会重复的

**Comment by mc-124** [comment]
> > 其实可以做成 mod ID，避免 mod 被重命名（）is:issue 记录 mod
> 
> 一些模组的 modid 也会重复的

比较mod的sha-1？

**Comment by LTCatt** [comment]
这个有点复杂过头了，超出现在的限度了 orz
