### ISSUE TITLE
关于地图资源的下载

### ISSUE THREAD

**Issue by Shabby-LDN** [Hex-Dragon/PCL2#4076]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在下载那一栏的资源那儿可以加一个地图资源的下载

### 原因

这项优化让我可以更方便地下载地图。
如果没有这项优化，我每次都必须到一些网页上去下载地图，让操作变得很麻烦。

**Comment by JingHai-Lingyun** [comment]
#44 #135
