### ISSUE TITLE
pcl启动器消失

### ISSUE THREAD

**Issue by zhaonbnb** [Hex-Dragon/PCL2#4078]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

这个问题很奇怪，当我打开电脑，有概率找不到桌面上pcl启动器的快捷方式，而且打开pcl文件夹也找不到.exe的pcl启动器

### 重现步骤

1、打开电脑

### 日志与附件

无

**Comment by JingHai-Lingyun** [comment]
#66

**Comment by allMagicNB** [comment]
Windows Defender 或者其他杀毒软件干的。
