### ISSUE TITLE
增加mod译名仅为中文

### ISSUE THREAD

**Issue by WatchfulBand** [Hex-Dragon/PCL2#4080]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

增加mod译名仅为中文

### 原因

（示例）
我看见又有中文又有英文觉得很杂乱

**Comment by WForst-Breeze** [comment]
有些 mod 只有英文原名没有中文译名，这样的话个人感觉难道不会更乱吗🤔

**Comment by LTCatt** [comment]
暂不考虑，抱歉 orz
