### ISSUE TITLE
Mod 管理页面左下方提示信息遮挡Mod管理菜单

### ISSUE THREAD

**Issue by qndm** [Hex-Dragon/PCL2#4082]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

如图：
![屏幕截图 2024-06-22 203630](https://github.com/Hex-Dragon/PCL2/assets/69710718/11b45293-3d72-494c-aa81-530ae1862e57)
如果提示信息过长，那么就会遮挡Mod管理菜单  
希望当提示信息过长时自动折叠内容，当鼠标移到上面时自动展开，同时让信息停留时间可配置

### 原因

这项优化让我可以更方便地管理Mod。
如果没有这项优化，我每次都必须在更新Mod时等待提示信息消失才能完全显示操作栏，让操作变得很麻烦。

**Comment by allMagicNB** [comment]
你是不是开了调试模式……

**Comment by Deep-Dark-Forest** [comment]
> 同时让信息停留时间可配置

#1822？

**Comment by JingHai-Lingyun** [comment]
配置理论上是可以的
不过这个信息貌似确实有一点点长了，在窗口过小时体验不是太好

**Comment by Deep-Dark-Forest** [comment]
~~如果要配置的话重开我的 #1822 啊（~~

**Comment by qndm** [comment]
> 你是不是开了调试模式……
没有

**Comment by qndm** [comment]
有的Mod名字特别长，信息的位置又特别好……

**Comment by wuliaodexiaoluo** [comment]
建议把错误版本的提示信息也压缩下
1.12.2 等12个版本存在版本错误

**Comment by MCSteve123** [comment]
包括`Optifine与自动进入服务器不兼容`这段提示也很烦人，把取消启动给挡了

**Comment by LTCatt** [comment]
略微下移了一点并且增加了一点点透明度，现在应该会好一些 =。=
