### ISSUE TITLE
Mod 更新支持查看更新哪些Mod并支持选择Mod版本

### ISSUE THREAD

**Issue by qndm** [Hex-Dragon/PCL2#4083]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

当选中Mod时更新Mod（点更新按钮），弹出对话框显示要更新的Mod及当前/要更新的版本，同时支持更改要更新的版本，而不总是最新版本，之后才开始更新Mod  
可以配置选中多少Mod时才弹出对话框（0=总是弹出）

### 原因

这项优化让我可以更方便地更新Mod。
如果没有这项优化，我每次都必须查看PCL日志文件检查更新的Mod（特别是100+Mod的版本），让操作变得很麻烦，同时可以解决#4064 和#3956

**Comment by allMagicNB** [comment]
#679
