### ISSUE TITLE
远古版本有时候要正版登录

### ISSUE THREAD

**Issue by zec896219** [Hex-Dragon/PCL2#4084]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

远古版本有时候会有正版登录的步骤 甚至会登录失败

### 重现步骤

在正版登录页面启动远古版本有概率会登录失败

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/15936659/Log1.txt)

**Comment by JingHai-Lingyun** [comment]
> 在正版登录页面启动远古版本

是什么意思？

**Comment by zec896219** [comment]
在正版登录页面启动远古版本有概率登录失败

**Comment by zec896219** [comment]
远古版本也要正版登录吗

**Comment by JingHai-Lingyun** [comment]
登录失败？你所上传的日志内不包含所反馈的内容
请发送截图或者**完整的**启动器日志（Log1~5.txt）

**Comment by zec896219** [comment]
![屏幕截图 2024-06-22 213435](https://github.com/Hex-Dragon/PCL2/assets/173539970/17ba2f87-06b4-4fa9-b314-c90a3b0c9b8d)
这一会好像卡不出来了 有时候登录特别慢

**Comment by zec896219** [comment]
甚至失败

**Comment by JingHai-Lingyun** [comment]
登录不上和远古版本没关系，日志发来看看

**Comment by zec896219** [comment]
[Log1.txt](https://github.com/user-attachments/files/15937062/Log1.txt)
我过了几十分钟才启动启动器

**Comment by zec896219** [comment]
[Log1.txt](https://github.com/user-attachments/files/15937062/Log1.txt)
我过了几十分钟才启动启动器

**Comment by allMagicNB** [comment]
一般来说和网络环境有关

**Comment by Silverteal** [comment]
远古版本不会也不可能兼容微软的正版验证系统。那时候mojang都不存在呢  
但是你这个问题和远古版没关系，单纯是你请求登录次数太多被风控了

**Comment by allMagicNB** [comment]
点太快了，你先别急

**Comment by SALTWOOD** [comment]
建议关了
