### ISSUE TITLE
增加窗口贴边自动吸附（可能不是这么叫的？

### ISSUE THREAD

**Issue by erqianwu** [Hex-Dragon/PCL2#4088]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

普通的窗口在拖拽时靠近屏幕边框会有不同的操作，如拖动标题栏到屏幕顶端会最大化，拖动标题栏到屏幕左端会左右分屏，将窗口上部拉伸到顶端/下部拉伸到底端会将窗口上下铺满等，而截至![image](https://github.com/Hex-Dragon/PCL2/assets/149848353/87f52c2c-7a76-48b2-9409-5d47a3ffae51)仍然不支持此操作

### 原因

这项优化可以快捷地窗口最大化/分屏。
如果没有这项优化，我每次都必须手动拖拽窗口尺寸，且无法保证刚好合适，让操作变得很麻烦。

**Comment by kong-que-dnf123** [comment]
但是目前来说能“贴边放大”的一般都先是支持这种一键放大按钮的说...?
![image](https://github.com/Hex-Dragon/PCL2/assets/120994373/413552d2-0f1a-439b-9c98-acdcc768d7bf)

**Comment by erqianwu** [comment]
> 但是目前来说能“贴边放大”的一般都先是支持这种一键放大按钮的说...? ![image](https://private-user-images.githubusercontent.com/120994373/342018279-413552d2-0f1a-439b-9c98-acdcc768d7bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxMTIyMzMsIm5iZiI6MTcxOTExMTkzMywicGF0aCI6Ii8xMjA5OTQzNzMvMzQyMDE4Mjc5LTQxMzU1MmQyLTBmMWEtNDM5Yi05Yzk4LWFjZGNjNzY4ZDdiZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyM1QwMzA1MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OWNjZDZiOTJiNTFiYWNiNGFhNjhkMjdlZmQ2NGM1NzY3YzJjZmViZGZkN2MwYTg4YTg0MWZiMmI4ZTVjZGRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZawCXhL7dYPgmryyTmEkHacZiivEfU_7R0yRheD8u3U)

这个功能确实也缺

**Comment by MCSteve123** [comment]
PCL是无边框应用程序，外加圆角，应该无法实现

**Comment by MCSteve123** [comment]
话说这样“千万别点”里面的移动窗口内容岂不要坏？

**Comment by erqianwu** [comment]
没开发过软件，不了解这方面，但可以自定义标题栏的chrome（edge也行）也可以实现这个功能，或许可以参考下

> 话说这样“千万别点”里面的移动窗口内容岂不要坏？

**Comment by Silverteal** [comment]
启动器全屏有什么很大的必要性吗
如果没有的话，贴边估计也不会被考虑

**Comment by erqianwu** [comment]
全屏看着更舒服一点，并且有的主页在窗口模式看不全
贴边还可以快捷分屏

**Comment by allMagicNB** [comment]
你最大化启动器干啥？

**Comment by allMagicNB** [comment]
#90

**Comment by JingHai-Lingyun** [comment]
由于 PCL 窗口外面的阴影是龙猫直接糊上去的，这导致了窗口（系统层面）会比看起来的大一圈
即使支持了自动吸附，也会看起来非常奇怪的吧……

**Comment by allMagicNB** [comment]
先给龙猫看看

**Comment by LTCatt** [comment]
这是 Windows 的内置实现，做不了

**Comment by erqianwu** [comment]
> 这是 Windows 的内置实现，做不了

可以给个活跃橙吗（

**Comment by WForst-Breeze** [comment]
抱歉，优化建议无法获得活跃橙

**Comment by allMagicNB** [comment]
> > 这是 Windows 的内置实现，做不了
> 
> 可以给个活跃橙吗（

1. 你这不是 Bug
2. 完成了？打上完成 Label 了？

**Comment by LTCatt** [comment]
> > > 这是 Windows 的内置实现，做不了
> > 
> > 
> > 可以给个活跃橙吗（
> 
> 1. 你这不是 Bug
> 2. 完成了？打上完成 Label 了？

语气友好一点……
