### ISSUE TITLE
另辟蹊径在PCL内启动已安装的基岩版的方法

### ISSUE THREAD

**Issue by erqianwu** [Hex-Dragon/PCL2#4089]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 首先说一下，是针对minecraft://暂时失效导致的，不是代替官方启动器用的。
进入正题。
PCL2预设主题“简单主页”中有一个可以启动本地Minecraft基岩版的功能，而这个功能现已失效。
或许可以使用启动文件的方法，先让用户自己创建一个基岩版Minecraft的快捷方式，再去启动它，代码大致如下：
`<local:MyButton Margin="0,4,0,8" Width="200" Height="35"
                    Text="启动Minecraft基岩版" EventType="打开文件" EventData="C:\Users\***\Desktop\minecraft" />`
经本人测试，可以正常使用，且效果很好，**不需要很大精力就可以修复**。

---
![image](https://github.com/Hex-Dragon/PCL2/assets/149848353/32d6dee2-ad45-4871-8c2e-41748a638ccf)
于是就投到这里来了

### 原因

这项优化让我可以更方便地启动基岩版。
如果没有这项优化，用其他方式修复比这个耗费的精力多。

**Comment by Silverteal** [comment]
本仓库不接受预设主页反馈。

**Comment by erqianwu** [comment]
> 本仓库不接受预设主页反馈。 如有需要，可使用 `打开文件` `cmd.exe|/c start /b cmd.exe /c start minecraft://`

这是对minecraft://失效提的建议，主页只是个例子

**Comment by Silverteal** [comment]
PCL没有任何其他地方需要启动基岩版。

**Comment by erqianwu** [comment]
那为什么相似的[issue](https://github.com/Hex-Dragon/PCL2/issues/3985)都被标上了处理中

**Comment by Silverteal** [comment]
您的建议是对于预设主页本身的修改，而 #3985 是对于 PCL 主页执行行为的修改

**Comment by erqianwu** [comment]
哦那没事了
删了

**Comment by erqianwu** [comment]
诶issue怎么删啊

**Comment by Silverteal** [comment]
点击下方的 close as ignored
