### ISSUE TITLE
正式版不禁止关闭启动图标

### ISSUE THREAD

**Issue by lingyunawa** [Hex-Dragon/PCL2#4091]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

![image](https://github.com/Hex-Dragon/PCL2/assets/145236590/33e17a89-2d4e-45d6-acf0-c3cce041a2c8)

### 原因

开源版本可以，正式版的话……也应该可以把？

**Comment by MCSteve123** [comment]
~龙猫：把开源版的也给删了~

**Comment by hejiehao** [comment]
> ~龙猫：把开源版的也给删了~

~~我直接 Clone 下来~~
