### ISSUE TITLE
支持一键更新Mod

### ISSUE THREAD

**Issue by wuliaouwu** [Hex-Dragon/PCL2#4092]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

如果Mod有新的版本，在启动器里直接一键更新，而不是需要再次繁琐的下载和删除旧Mod文件

### 原因

我需要这个功能来在多个Mod更新时更新Mod。很多人都有更新Mod的需求，但如果没有这个功能，就不能方便的更新Mod了。

**Comment by Deep-Dark-Forest** [comment]
？最新版启动器已经有这个功能了啊

**Comment by wuliaouwu** [comment]
O.o
找了下，还真有
抱歉了
