### ISSUE TITLE
正版皮肤不显示

### ISSUE THREAD

**Issue by justimpart** [Hex-Dragon/PCL2#4094]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

正版皮肤怎么都不显示，皮肤、网络、离线都试过了全都显示不了，原来可以正常显示的存档也不能显示了，上次问了全是说是网络问题和api问题。网络我自己能改着试试，我又不是程序员api怎么修能说具体点吗，找了好长时间也没教程或者类似的问题

### 重现步骤

启动器内更改正版皮肤可以同步到官网，但就是读不了皮肤，离线模式也读取不了。来回改了几次连正常存档也读取不了了

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/15944358/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/15944359/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/15944360/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/15944361/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/15944362/Log5.txt)

**Comment by allMagicNB** [comment]
一眼给墙了，你这改网络实现不了，得用加速器啥的……

**Comment by MCSteve123** [comment]
请下载HMCL试一下：https://hmcl.huangyuhui.net/download

**Comment by SALTWOOD** [comment]
一眼墙了，建议VPN加速器HMCL之类的全都试试没问题再来
来个collaborator关了？

**Comment by SALTWOOD** [comment]
你要是真的想解决，请先去discussion问问

**Comment by LTCatt** [comment]
一般是网络问题。
