### ISSUE TITLE
更换 “Mod管理” 界面中 “安装Mod” 按钮的功能

### ISSUE THREAD

**Issue by 212112111zwl** [Hex-Dragon/PCL2#4095]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

当点击该按钮时，直接转到 下载mod 界面并自动匹配版本和mod加载器

### 原因

大部分mod安装都是直接从 下载mod 界面下载下来，这项优化可以让我更方便地下载mod
原按钮仅起到提示作用，没有实际用途

**Comment by Deep-Dark-Forest** [comment]
感觉不太行，因为这个按钮的名字叫做 “安装 Mod” 而不是 “下载 Mod”，是有原因的。因为可能有一些玩家自制没有上传到 curseforge 或 modrinth 的模组在下载 Mod 界面根本搜不到。

**Comment by Deep-Dark-Forest** [comment]
感觉不太行，因为这个按钮的名字叫做 “安装 Mod” 而不是 “下载 Mod”，是有原因的。因为可能有一些玩家自制没有上传到 curseforge 或 modrinth 的模组在下载 Mod 界面根本搜不到。

**Comment by 212112111zwl** [comment]
尽管这种情况存在，绝大多数mod安装都是通过pcl提供的下载界面下载到mod文件夹，小部分mod制作者肯定也知道将mod装入版本的方法，即将.jar文件复制到mods文件夹或拖入pcl窗口，那么这个按钮就没有了实际意义
不妨在按下按钮后弹出浏览文件的界面，在本地选择.jar文件

**Comment by Deep-Dark-Forest** [comment]
> 小部分mod制作者肯定也知道将mod装入版本的方法，即将.jar文件复制到mods文件夹或拖入pcl窗口

没太懂，为什么“小部分mod制作者肯定也知道将mod装入版本的方法，即将.jar文件复制到mods文件夹或拖入pcl窗口”？难道小部分mod制作者不能经常用HMCL等其他启动器吗（

**Comment by allMagicNB** [comment]
模组文件又不是只有 .jar 拓展名……

**Comment by allMagicNB** [comment]
先给龙猫看看反正……
不是你们都不换 Label 的？

**Comment by 212112111zwl** [comment]
“将.jar文件复制到mods文件夹或拖入pcl窗口” 是mc绝大多数mod最直接最常用的安装方法，.jar也是目前绝大多数mod最终打包成的格式。

mod制作者作为已经有开发或编辑mod内部文件能力的人肯定知道以上方法。你们讨论的情况都是可能的，但这个按钮不是用来照顾少部分有特殊需要的人的，尤其是放在mod管理这么显眼位置的按钮，它必然需要有一定的实际用途，不然干脆就删掉，能明白我的意思吧。

目前情况就是点一下这个按钮，它什么事情也不干，就弹出一行字告诉我可以将mod文件拖入pcl窗口，那我只要没有健忘症，最多只需要按一次这个按钮就知道了“将mod文件拖入pcl窗口可以安装它”这个功能，从而结束了按钮存在的意义。

然而，如果每次按下这个按钮，它能直接跳到人们最熟悉最常用的mod安装方式——在下载界面直接下载，并自动匹配版本和mod loader，那这个按钮才有了实际用途，并且对不想每次都自己在下载界面输入版本和mod loader的我提供了便利。

如果对 “小部分mod作者” 或 “萌新” 的特殊需要实在放心不下，可以既按照上述跳到下载界面，也弹出一行 “也可以直接拖入pcl窗口进行安装哦~”，这样两全其美

**Comment by Deep-Dark-Forest** [comment]
> mod制作者作为已经有开发或编辑mod内部文件能力的人肯定知道以上方法。

我不认同您的说法。“mod制作者”和普通玩家的数量谁会更多呢？“mod制作者”相比普通玩家终究还是太少了，而且他们知道又能怎么样呢，他们的模组通常又不是留着自用，肯定会分发给别人。而且“肯定知道”这种说法似乎过于绝对，有些“mod制作者”可能都不一定会知道怎么在PCL2启动器中安装模组，因为很多外国mod制作者可能都没听过什么是PCL2启动器，而至于普通玩家可能就更不知道了。

> 但这个按钮不是用来照顾少部分有特殊需要的人的

我不认为不知道可以拖拽mod的人在少数。如果这个按钮被移除，很多玩家会失去学习此功能的机会，可能永远不知道？

> 尤其是放在mod管理这么显眼位置的按钮，它必然需要有一定的实际用途，不然干脆就删掉，能明白我的意思吧。

这个按钮有一定的实际用途，那就是告诉那些不知道这个功能的人这个功能是存在的。相反，如果把这个按钮的功能改为“跳转到下载mod”页面，那么我完全可以直接手动操作到下载mod页面，这个按钮是完全多余的。

> 如果对 “小部分mod作者” 或 “萌新” 的特殊需要实在放心不下，可以既按照上述跳到下载界面，也弹出一行 “也可以直接拖入pcl窗口进行安装哦~”，这样两全其美

这样改可能更糟。如果我是真的想要拖拽mod并不想下载，那么我还需要手动返回；如果我是想下载mod而不是拖拽，每次左下角都在提醒真的会让人很烦。

**Comment by LTCatt** [comment]
> 我的建议是，保留这个按钮，同时把这个按钮的文本改为“从本地安装mod”，同时加入“下载并安装mod”按钮，点击后会跳转到mod下载界面并自动匹配版本和模组加载器。

我觉得这个方法比较好 =。=……

**Comment by LTCatt** [comment]
![image](https://github.com/user-attachments/assets/78436c75-5ae8-4022-a177-6f9fa92f4a86)
