### ISSUE TITLE
为每个mc版本设定java

### ISSUE THREAD

**Issue by gi-b716** [Hex-Dragon/PCL2#4096]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

为单独mc版本设定特定java

特别的是，这个优化不同于
![image](https://github.com/Hex-Dragon/PCL2/assets/78394473/c1c81e53-4adc-44ea-933f-0045b6cbf680)单个实例。这个java选择的依据是特定的minecraft版本，例如将所有mc1.20.1版本设定成某个java

### 原因

这项优化让我可以更方便地管理不同的java。
如果没有这项优化，每个版本我都必须手动调整相应java，让操作变得很麻烦。

**Comment by LTCatt** [comment]
适用面比较小，暂不考虑 orz
