### ISSUE TITLE
在百宝箱中的下载自定义文件中添加进度条、估算下载剩余时间

### ISSUE THREAD

**Issue by ZhaYi-Miao** [Hex-Dragon/PCL2#4097]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

## 进度条

就比如说在这里加一个进度条，啥颜色都彳亍，最好能让自定义（

![47c94836-390a-4582-900e-2eda82e2ccec](https://github.com/Hex-Dragon/PCL2/assets/165556161/1c0fa541-29ae-4208-b5c7-03b9420294cb)

## 剩余时间

也可以再加一个剩余的时间，根据 `t=s/v` 即可得出下载时间，不准也行，大概知道就可以

![fe8046fc-80c6-4dfa-a45c-d0aba6913264](https://github.com/Hex-Dragon/PCL2/assets/165556161/7c3017d9-ce97-459a-a6ed-4f594f4be297)

建议塞到这里

### 原因

我需要pcl能够在下载自定义文件时，在文件名下方显示进度条，广大用户都有监控下载进度的需求，以便更方便的了解文件下载的完成情况。如果没有这个功能，用户就无法直观地了解下载进度，只能在任务栏那一小扣扣里看进度，显得极其抽象，win11任务栏进度还只有小小的一条

完了怎么写出了ai味（

**Comment by JingHai-Lingyun** [comment]
下载时间本来就无法确定，再说不是有下载百分比了么...

**Comment by Deep-Dark-Forest** [comment]
本来就有下载进度条啊

**Comment by wuliaodexiaoluo** [comment]
下载速度受网络环境影响，也就是说即使算出来了最终用时也不一定符合计算结果，可能快也可能慢

**Comment by WForst-Breeze** [comment]
#2545
