### ISSUE TITLE
1.20.6版本forge兼容optifine

### ISSUE THREAD

**Issue by Charl3Z** [Hex-Dragon/PCL2#4098]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

forge 50.1.7 与 optifine hd u i9 pre1兼容，建议提供下载安装

### 原因

（示例）
这项优化让我可以更方便地xxxx。
如果没有这项优化，我每次都必须xxxx，让操作变得很麻烦。

**Comment by wuliaodexiaoluo** [comment]
![ad10c6a4c1f7a574ac18978eb063b254](https://github.com/Hex-Dragon/PCL2/assets/160083863/fb52a017-e62a-4ef5-a86c-1508c385b306)
官网并没有标注兼容的 Forge 版本

**Comment by allMagicNB** [comment]
兼容个屁哦

**Comment by wuliaodexiaoluo** [comment]
>兼容个屁哦

虽然您是本仓高贵的协作者，但我仍建议您放缓您的语气以避免不必要的冲突
