### ISSUE TITLE
mod下载界面无1.21

### ISSUE THREAD

**Issue by FFDVDGD** [Hex-Dragon/PCL2#4100]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在mod下载界面版本筛选中无1.21
![图片](https://github.com/Hex-Dragon/PCL2/assets/82321430/66c2d13f-7d63-47c5-8f57-36db7484782b)

### 重现步骤

1、点击xxxx
2、往下滚，然后点击xxxx

### 日志与附件

这个应该不用日志吧

**Comment by allMagicNB** [comment]
#4031
