### ISSUE TITLE
错误的mc百科检索

### ISSUE THREAD

**Issue by liyuxiang-lyx** [Hex-Dragon/PCL2#4104]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

Mace Port并没有被百科收录，但是
![屏幕截图 2024-06-26 210317](https://github.com/Hex-Dragon/PCL2/assets/84612542/46e865ca-8d3c-433d-927e-9fc1d23c466f)

### 重现步骤

1、搜索mace-port
2、点击Mace Port
3、点击“转到MC百科”

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/15988704/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/15988719/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/15988720/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/15988721/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/15988717/Log5.txt)

**Comment by liyuxiang-lyx** [comment]
出来的是Mace Backport

**Comment by wuliaodexiaoluo** [comment]
跳转链接：https://www.mcmod.cn/class/14137.html
可能只是 Mod 名称不对？

**Comment by allMagicNB** [comment]
不对个屁，这 Mod 作者改名了而已

**Comment by wuliaodexiaoluo** [comment]
> 不对个屁哦，这 Mod 作者改名了而已

有没有可能我想表达的意思是这两个有可能是同一种东西

**Comment by kong-que-dnf123** [comment]
Mace Port在Curseforge就叫这个名字 而在modMC里被改名成了Mace Backport
然而事实上Curseforge里还有一个Mace Combat Backport 但这个mod没被ModMC收录且有且仅有2个版本

题外话：
这搜索程序是不是出了点问题啊关于mod“Mace Combat Backport”我搜索“Mace Backport”就能搜到为什么直接搜“Mace Combat Backport”就搜不到啊？？？？？
![image](https://github.com/Hex-Dragon/PCL2/assets/120994373/37b6b0df-a1ad-4400-82b5-f08cfa9ad321)
![image](https://github.com/Hex-Dragon/PCL2/assets/120994373/20e52eda-31a1-4e76-a343-9c25f58de08b)

**Comment by allMagicNB** [comment]
那就是 MC百科 搞的

**Comment by allMagicNB** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/116283787/631745d4-5ae5-4a91-8ca5-3736a7bb4922)
已更正
