### ISSUE TITLE
未将对象的引用设置到对线的实例

### ISSUE THREAD

**Issue by Gcml-ssmol** [Hex-Dragon/PCL2#4105]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

具体表现为无法下载mod和mc版本，但是如果从已有的官方启动器启动的话则可以正常启动，初步判断不为java的问题，因为启动器可以正常启动，仅有下载无法正常下载

### 重现步骤

点击pcl2启动器上的下载则会显示”未将对象的引用设置到对线的实例“报错，刷新无用
![76f070ef8093b137d4302d69b93230d4](https://github.com/Hex-Dragon/PCL2/assets/173926928/38c8a94f-07e0-4096-9cfe-0cb4ba0974a1)
![4f4ef3e78e47eb62f571284fb145c195](https://github.com/Hex-Dragon/PCL2/assets/173926928/1715b2b2-fec8-455f-8197-db8ec1df5168)

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/15990502/Log1.txt)

**Comment by allMagicNB** [comment]
#4015
