### ISSUE TITLE
[也许是 BUG] 启动 PCL 后，产生了极度不正常的磁盘占用率……

### ISSUE THREAD

**Issue by SuoHouDaiShi** [Hex-Dragon/PCL2#4108]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

这不是最近放假了吗，电脑也给放开了，打算玩玩 MC
启动 PCL 后，磁盘占用率**直线上升至 100% 并居高不下**（目前发现**仅注销和重启**能够解决问题）
![图片](https://github.com/Hex-Dragon/PCL2/assets/119282947/f16370be-1844-45e2-b6f0-5365f2dda8c4)

### 重现步骤

我相信大家都会启动 PCL 的

### 日志与附件

日志应该没啥用吧……
[Log1.txt](https://github.com/user-attachments/files/16011436/Log1.txt)

**Comment by allMagicNB** [comment]
有其他什么能证明是 PCL 干的吗？

**Comment by SuoHouDaiShi** [comment]
> 有其他什么能证明是 PCL 干的吗？

磁盘占用率在 0% 的情况下启动 PCL 后才出现的使用率……我看看有空了补个录像吧

**Comment by LTCatt** [comment]
会不会是内存清理导致的？

**Comment by kong-que-dnf123** [comment]
请问是打开PCL立刻占用还是启动MC时大量占用？
或者说进入任务管理器看一下具体的PCL情况？
我这边如果是启动MC时的过度延迟是因为一个叫“OpenJDK”的程序爆了我剩余的内存和CPU...
![image](https://github.com/Hex-Dragon/PCL2/assets/120994373/511d0f1c-0e2b-4abc-963f-7eca7f34adbb)
![image](https://github.com/Hex-Dragon/PCL2/assets/120994373/227af330-7278-45ac-bd60-d701b310cd78)

**Comment by wuliaodexiaoluo** [comment]
![2720e58acf677801edd2b4b7dda80a37](https://github.com/Hex-Dragon/PCL2/assets/160083863/eb09e629-e006-4769-a61b-a282a878d733)
这应该是 USB 驱动器吧
如果是启动和文件扫描 Minecraft 出现的高 IO 占用，USB 驱动器的主控芯片不是为频繁刷写设计的，高 IO 是正常现象

**Comment by SuoHouDaiShi** [comment]
统一回复一下：
1. 未进行内存清理…
2. 是启动 PCL 导致的高度磁盘占用
3. 这是 USB 3.1 移动硬盘，并非 U 盘

另外，龙猫能不能尝试提高在低端电脑上的性能呢？

**Comment by JingHai-Lingyun** [comment]
看起来很奇怪

**Comment by LTCatt** [comment]
这不像是 PCL 的行为，很怪，其他启动器也会这样吗？

**Comment by SuoHouDaiShi** [comment]
经过实际测试，在电脑仅开启代理软件和启动器时，测试结果如下：
1. PCL 启动后磁盘占用率 100%，测试时长 10 秒，平均响应时间最高来到了 1103ms
2. HMCL 启动后磁盘占用率最高 94%，测试时长 10 秒，平均响应时间最高来到了 997ms
3. BakaXL 启动后磁盘占用率最高 100%，测试时长 10 秒，平均响应时间…37ms？

**Comment by SuoHouDaiShi** [comment]
还有一个奇怪的点，为什么获取来自 C 盘的 Java 会导致游戏所在的磁盘来到 100% 的占用率呢？

**Comment by wuliaodexiaoluo** [comment]
转 #4116 聊吧

**Comment by allMagicNB** [comment]
> 还有一个奇怪的点，为什么获取来自 C 盘的 Java 会导致游戏所在的磁盘来到 100% 的占用率呢？

你觉得游戏存档文件啥的不会改变？

**Comment by SuoHouDaiShi** [comment]
> > 还有一个奇怪的点，为什么获取来自 C 盘的 Java 会导致游戏所在的磁盘来到 100% 的占用率呢？
> 
> 你觉得游戏存档文件啥的不会改变？

可问题是那是**游戏启动过程中**，**并非游戏启动后**，你游戏都没开起来你存档怎么可能发生变化🤔

**Comment by wuliaodexiaoluo** [comment]
>可问题是那是游戏启动过程中，并非游戏启动后，你游戏都没开起来你存档怎么可能发生变化🤔

大概是文件校验

**Comment by allMagicNB** [comment]
> > > 还有一个奇怪的点，为什么获取来自 C 盘的 Java 会导致游戏所在的磁盘来到 100% 的占用率呢？
> > 
> > 你觉得游戏存档文件啥的不会改变？
> 
> 可问题是那是**游戏启动过程中**，**并非游戏启动后**，你游戏都没开起来你存档怎么可能发生变化🤔

游戏启动过程中游戏也会载入数据啥的

**Comment by LTCatt** [comment]
这我觉得是硬件性能问题……
