### ISSUE TITLE
无法下载整合包

### ISSUE THREAD

**Issue by Excalibur3486** [Hex-Dragon/PCL2#4109]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

无法安装整合包，包括原版

### 重现步骤

下载版本时，失败

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16011443/Log1.txt)

**Comment by youzi-2333** [comment]
似乎与 #3462 重复……

**Comment by Pigeon0v0** [comment]
首先，你自己网络就很烂（`Ln 2747` 起）

其次，访问被拒绝个人更觉得是系统问题（或者确实是 #3462 ）

**Comment by Pigeon0v0** [comment]
先等龙猫看看这个访问被拒绝是什么说法...

**Comment by LTCatt** [comment]
`java.nio.file.AccessDeniedException: C:\Users\ASUS\AppData\Local\Temp\forge_installer3273478987625865702`
Ln 19038
文件被拒绝访问，并非 PCL 的问题
