### ISSUE TITLE
自定义窗口大小失效

### ISSUE THREAD

**Issue by zhuluzyy** [Hex-Dragon/PCL2#4114]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

全屏进入游戏后退出,pcl窗口自定义大小失效.
另外在启动游戏时会有各种灵异事件,鼠标指针变大,windos开始菜单变小.游戏启动成功后灵异事件消失.

### 重现步骤

在pcl窗口边缘拖动调整大小,在设置,游戏,启动选项,窗口大小改为全屏,启动器可见性设为游戏启动后最小化,进入游戏退出后pcl窗口恢复默认大小

### 日志与附件

[Log3.txt](https://github.com/user-attachments/files/16027979/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16027980/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16027981/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/16027982/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16027983/Log2.txt)

**Comment by JingHai-Lingyun** [comment]
> 在pcl窗口边缘拖动调整大小

> 在设置,游戏,启动选项,窗口大小改为全屏

请问这两有联系吗？设置里头设置的是 MC 的窗口大小
如果你确认 PCL 窗口大小配置丢失了，尝试打开 `设置 -> 启动器 -> 高级选项` 中的 `调试模式` 然后再复现一次并录屏

**Comment by youzi-2333** [comment]
@zhuluzyy 请尽快补充信息，超过 10 天未补充信息将会被关闭，感谢（

**Comment by LTCatt** [comment]
由于长期未回复暂时关闭

**Comment by allMagicNB** [comment]
@JingHai-Lingyun 出来 Reopen

**Comment by JingHai-Lingyun** [comment]
> 转自 #4350 
> 演示视频太大,分卷压缩

[Log1.txt](https://github.com/user-attachments/files/16389699/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16389700/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16389696/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16389697/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16389698/Log5.txt)
[演示视频(请删除后缀名中的txt).z01.txt](https://github.com/user-attachments/files/16389875/txt.z01.txt)
[演示视频.zip](https://github.com/user-attachments/files/16389877/default.zip)

**Comment by LTCatt** [comment]
游戏版本：1.18, Fabric 0.15.7
有谁可以尝试复现吗？

**Comment by kong-que-dnf123** [comment]
精彩，PCL没恢复默认大小倒是给我谷歌浏览器干诈尸了（虽然是github界面但事实是作为谷歌浏览器打开的，谷歌浏览器其实也蚌到全屏但1/4画面 ~但我没来得及截图一个Alt+Tab两次未响应又回来了~ ）
![image](https://github.com/user-attachments/assets/43647608-9632-4052-aa2f-5d359904bab4)

**Comment by ZhangJinyuJerry** [comment]
> 精彩，PCL没恢复默认大小倒是给我谷歌浏览器干诈尸了（虽然是github界面但事实是作为谷歌浏览器打开的，谷歌浏览器其实也蚌到全屏但1/4画面 ~但我没来得及截图一个Alt+Tab两次未响应又回来了~ ）
> 
> 细节：开启全屏的时候 大概是游戏窗口即将出现的一瞬间 屏幕会紧随的进行一次大幅度缩放（因为我鼠标有一瞬间被放大且居于中央，以及第二次复现时虽然也卡了个谷歌浏览器1/4屏但是随着一次 **显卡重载** （别问为什么知道问就是每次玩游戏都这样一下然后PCL就以“显卡驱动不行”把我MC给爆了）我谷歌浏览器又回到全屏了
> 
> 资料： 版本 Windows 11 家庭中文版 版本号 23H2 安装日期 ‎2022/‎10/‎22 操作系统版本 22631.3880 体验 Windows Feature Experience Pack 1000.22700.1020.0 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz 2.42 GHz处理器 Intel显卡（显存大小128mb ![image](https://private-user-images.githubusercontent.com/120994373/352683670-43647608-9632-4052-aa2f-5d359904bab4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMDk4MDQsIm5iZiI6MTcyMjIwOTUwNCwicGF0aCI6Ii8xMjA5OTQzNzMvMzUyNjgzNjcwLTQzNjQ3NjA4LTk2MzItNDA1Mi1hYTJmLTVkMzU5OTA0YmFiNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOFQyMzMxNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYjg4ZjdhNWFmMjZiODE0ZTU0YzAyYjY2OTM4YTEyNTkxNDZjYWU2MjhkMTZhNjc5N2U4NWRmMWY0YzE2YjY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NH_dxgkA8UlFl_aUsBLNo49lOAY8Ll762mW2SRHts5w)

兄弟你是不是要把日志发出来

**Comment by kong-que-dnf123** [comment]
>兄弟你是不是要把日志发出来

日志+视频
（日志直接翻到最下面，其他的修改时间没变就不发了）
[Log1.txt](https://github.com/user-attachments/files/16406915/Log1.txt)
又及：我的现场表现为桌面有明显的显示误差 但是OBS记录仅仅为黑屏 如果需要我回头再用我的 ~（“超”高配2017年手机）~ 录一个
https://github.com/user-attachments/assets/aecd5d02-d06e-4908-aef8-c482cef6afdf

**Comment by LTCatt** [comment]
这是 MC 的问题，在全屏下它会修改显示器分辨率，导致所有窗口被缩小到和它一样的大小

**Comment by zhuluzyy** [comment]
有什么解决办法吗?

**Comment by LTCatt** [comment]
没有办法，这是 MC 的 bug，众所周知麻将不会修 bug（
装个无边框全屏 mod？

**Comment by allMagicNB** [comment]
> 没有办法，这是 MC 的 bug，众所周知麻将不会修 bug（
> 装个无边框全屏 mod？

是不会修历史版本的 Bug（

**Comment by zhuluzyy** [comment]
有办法了. 把 设置,游戏,启动选项,窗口大小改为默认再通过游戏f12改成全屏
还真是这个选项的问题😅
