### ISSUE TITLE
请求对MOD列表排序和升级图标改变

### ISSUE THREAD

**Issue by xiaoanTAT** [Hex-Dragon/PCL2#4115]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

如果标题所示，希望在启动器-版本设置-MOD管理-里面添加排序功能，如按文件排序一样能按照拼音字母，修改时间，占用大小，递增，递减排序，其主要述求是优先排序可升级的MOD在列表前面和给可升级的MOD升级图标改成更加显眼更大的图标并且升级图标可更改颜色对色弱用户较为亲切。

### 原因

更加快速的管理MOD列表

**Comment by wuliaodexiaoluo** [comment]
#2698

**Comment by JingHai-Lingyun** [comment]
排序在 #2698 拒绝掉了，图标改色的话……

**Comment by wuliaodexiaoluo** [comment]
> Mod 列表排序确实重了，修改升级图标暂时没发现有重复……

实际上，升级 Mod 并不是我们一致推荐的做法，虽然这可能解决部分问题，但是会导致更多的兼容性问题
让这些图标更显眼会误导操作，导致更多的无效 Issue
综合考虑上，这些更改都是弊大于利

**Comment by allMagicNB** [comment]
升级图标也没必要，做完筛选不就起到同样效果了？

**Comment by LTCatt** [comment]
做完筛选就好了。
如楼上讨论，对小白用户并不建议他们去升级，所以不会考虑把它整的更显眼。并且这也和色弱无关，这是亮度变化，没有饱和度变化，色弱不影响观察亮度变化。
