### ISSUE TITLE
无法显示所选版本下载框

### ISSUE THREAD

**Issue by MinecraftYYDS7** [Hex-Dragon/PCL2#4118]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在模组下载页中，没有[所选版本：xxx]的框。
无法快速地点击到具体的版本

### 重现步骤

在Mods下载页中，版本选择1.12.2Forge，来源选择Curseforge，在搜索框中回车以刷新条件。
此时，（我的PCL2上）鼠标手势、传送石碑、玉等Mods进入版本详情页时无法看到[所选版本：1.12.2Forge]的字样。
在搜索框中输入想要的Mod，大多数Mod都没有[所选版本：1.12.2Forge]的字样

### 日志与附件

[Log3.txt](https://github.com/user-attachments/files/16039177/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16039178/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16039180/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/16039181/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16039182/Log2.txt)
![屏幕截图(7)](https://github.com/Hex-Dragon/PCL2/assets/122857182/18e9ebfa-988c-4015-97b1-8b1909a81306)
![屏幕截图(8)](https://github.com/Hex-Dragon/PCL2/assets/122857182/8f157584-cf78-4914-91e7-d1eb9d8d2f18)
![屏幕截图(9)](https://github.com/Hex-Dragon/PCL2/assets/122857182/6468e917-3447-4f20-8cc6-e3084c62fec8)
![屏幕截图(10)](https://github.com/Hex-Dragon/PCL2/assets/122857182/c216fe44-9297-49ec-8f34-beaefde9fb1b)

**Comment by JingHai-Lingyun** [comment]
在目前的版本中不知道为什么有可能这个东西会失效，昨天做包的时候也遇到了
附可能有用的调试日志 [Log1.txt](https://github.com/user-attachments/files/16039203/Log1.txt)

**Comment by allMagicNB** [comment]
应由 Mod 作者未指定加载器所致

**Comment by wuliaodexiaoluo** [comment]
大概知道是什么问题了
因为早期不支持设置加载器，后期支持了也没设置，当这个 Mod 的检索条件不符合 1.12.2 、Forge 中任何一个值时就不会展示

**Comment by kong-que-dnf123** [comment]
> 大概知道是什么问题了 因为早期不支持设置加载器，后期支持了也没设置，当这个 Mod 的检索条件不符合 1.12.2 、Forge 中任何一个值时就不会展示

这个意思吗...?
https://github.com/Hex-Dragon/PCL2/issues/3539#issuecomment-2004787358
