### ISSUE TITLE
在版本管理添加投影文件夹快捷方式

### ISSUE THREAD

**Issue by vochant** [Hex-Dragon/PCL2#4119]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

（非必须：检测是否安装了投影模组，如有则）在版本管理的“快捷方式”一栏添加投影文件夹的入口

### 原因

生电玩家嘛……能快速打开投影文件夹还是能方便不少的

**Comment by allMagicNB** [comment]
#606
