### ISSUE TITLE
关于启动游戏但无法在pcl右下角显示关闭按钮

### ISSUE THREAD

**Issue by systemoslwb** [Hex-Dragon/PCL2#4120]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

启动游戏但无法在pcl右下角显示关闭按钮

### 重现步骤

1、点击启动游戏
2、游戏启动成功之后，关闭启动器
3.再次打开启动器，不显示关闭按钮

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16039677/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16039678/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16039679/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16039680/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16039682/Log5.txt)

**Comment by allMagicNB** [comment]
#1243
