### ISSUE TITLE
Java启动

### ISSUE THREAD

**Issue by Joey-zjh** [Hex-Dragon/PCL2#4121]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃基本不是 PCL 的原因，请 **不要** 提交反馈。你可以在论坛或社区找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用 HMCL 启动，HMCL 没有出现问题。** 如果 HMCL 也无法启动就不是 PCL 导致的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

当PCL启动一个新的版本，且它需要另一种已安装的Java时（从未用过），会启动失败。注：这个错误报告是为了模拟当时情况，让PCL强制使用当时的JAVA17做的。解决方法是进设置搜JAVA。

### PCL 错误报告、日志与附件

[错误报告-2024-6-29_18.19.03.zip](https://github.com/user-attachments/files/16039658/-2024-6-29_18.19.03.zip)

**Comment by Joey-zjh** [comment]
（我要主题）

**Comment by allMagicNB** [comment]
……复现请使用出问题时的相同环境进行复现，而非更改设置。

**Comment by wuliaodexiaoluo** [comment]
自动搜索好像确实有 bug（也可能是需要特定目录），上次用了自动搜索，同硬盘下的 Java 确实没扫出来

**Comment by allMagicNB** [comment]
@Joey-zjh 请不要提交反馈后对此不管不顾，请补充信息。

**Comment by allMagicNB** [comment]
> 自动搜索好像确实有 bug（也可能是需要特定目录），上次用了自动搜索，同硬盘下的 Java 确实没扫出来

又不是扫全盘……

**Comment by Joey-zjh** [comment]
已解决。重新自动搜索后改不回来。

**Comment by allMagicNB** [comment]
> 已解决。重新自动搜索后改不回来。

卸载你安装的 Java 21，然后让 PCL 重新扫描 Java，最后再重复你之前的操作。

**Comment by Joey-zjh** [comment]
修了？

**Comment by allMagicNB** [comment]
> 修了？

你在此期间有没有更新过 PCL 版本？

**Comment by JingHai-Lingyun** [comment]
（最新版本下）当 PCL 没有找到启动 Minecraft 所需要的 Java 的时候，会询问你是否要自动下载 Java。所以不应当出现启动失败的情况

**Comment by Joey-zjh** [comment]
[Log2.txt](https://github.com/user-attachments/files/16039755/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16039760/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16039761/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16039762/Log5.txt)
[Log.txt](https://github.com/user-attachments/files/16039763/Log.txt)
[Log1.txt](https://github.com/user-attachments/files/16039764/Log1.txt)

**Comment by Joey-zjh** [comment]
升过级。快照升了一下，刚试是会询问。
