### ISSUE TITLE
无主页时切换主页严重卡顿

### ISSUE THREAD

**Issue by WatchfulBand** [Hex-Dragon/PCL2#4122]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

某些时候无主页时切换主页严重卡顿，甚至卡死

### 原因

这项优化让我可以更方便地使用PCL2
如果没有这项优化，我每次卡死时都必须重新启动PCL2，让操作变得很麻烦。

**Comment by JingHai-Lingyun** [comment]
上传日志

**Comment by allMagicNB** [comment]
超时关闭
