### ISSUE TITLE
Forge的版本选项

### ISSUE THREAD

**Issue by ZXY-Baa** [Hex-Dragon/PCL2#4123]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在1.20.1Forge的安装选项中提供的Forge版本不是最新项
![屏幕截图 2024-06-29 221003](https://github.com/Hex-Dragon/PCL2/assets/124010960/cb7094b9-ef93-4513-b8f5-8b4a05a96cd1)
![屏幕截图 2024-06-29 221029](https://github.com/Hex-Dragon/PCL2/assets/124010960/b5cc67c1-4862-4d01-a2c7-8d8143895205)
![屏幕截图 2024-06-29 221045](https://github.com/Hex-Dragon/PCL2/assets/124010960/ff2b3ead-c115-459a-822c-62b39f84170e)
（怀疑接口被封了。。。。HMCL也是如此

### 重现步骤

1.20.1的游戏版本中Forge的安装选项

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16040758/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16040759/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16040760/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16040761/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16040762/Log5.txt)

**Comment by ZXY-Baa** [comment]
![屏幕截图 2024-06-29 221636](https://github.com/Hex-Dragon/PCL2/assets/124010960/a4eda6eb-6982-49eb-bee5-3e573154fadd)

**Comment by allMagicNB** [comment]
镜像源没更新，切换下版本列表加载源试试？

**Comment by Deep-Dark-Forest** [comment]
如果HMCL也是如此，说明不是PCL问题

**Comment by allMagicNB** [comment]
这种基本上就是镜像源导致的，你认为不是的话拿出证据再 Comment，反正先关了（
