### ISSUE TITLE
优化崩溃提示

### ISSUE THREAD

**Issue by CNShicy** [Hex-Dragon/PCL2#4124]
### 检查项

- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

请将“如果要寻求帮助……而不是发送这个窗口的截图”的字体调大调粗，使他更显眼
崩溃提示增加一个按钮，这个按钮可以直通mc百科崩溃解答站

### 原因

如果没有这项优化，有的人会选择性失明（
有了这项优化，可以大大减少我的工作时间

**Comment by JingHai-Lingyun** [comment]
> 请将“如果要寻求帮助……而不是发送这个窗口的截图”的字体调大调粗，使他更显眼

#2153 

另外一个…… 没找到类似反馈，挂着看看吧…… 但我感觉大概率不会做

**Comment by LTCatt** [comment]
直通解答站这种还是算了，有一种钦定的感觉……
