### ISSUE TITLE
支持启动图标颜色修改

### ISSUE THREAD

**Issue by MCSteve123** [Hex-Dragon/PCL2#4125]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

搜索：`category:功能投票 图标`、`is:issue 图标`没有类似内容

允许修改PCL启动图标颜色（可以把PCL图标转为灰度图像实现）
- 自定义（没啥好说的）
- 跟随主题（在启动时根据主题色染色，如果是渐变色，以拖动条的颜色值为准）

求过

---
另：我记得商标是可以交灰度图像的

### 原因

目前PCL的启动图标与主题长期存在割裂感，明明是活跃橙，打开时却是蓝色图标，有点违和

**Comment by allMagicNB** [comment]
#791
