### ISSUE TITLE
无法正确显示所有已安装的mod

### ISSUE THREAD

**Issue by laozhangchen** [Hex-Dragon/PCL2#4126]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

无法正确显示所有已安装的mod

### 重现步骤

启动pcl2后在下载界面下载mod到已安装的mc版本中，打开mod管理界面无法显示新安装的mod

### 日志与附件

[Log4.txt](https://github.com/user-attachments/files/16044740/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16044741/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/16044742/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16044743/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16044744/Log3.txt)

**Comment by allMagicNB** [comment]
截屏

**Comment by laozhangchen** [comment]
> 截屏

<img width="1080" alt="捕获" src="https://github.com/Hex-Dragon/PCL2/assets/174254287/885370f6-14d2-43bd-9e00-3a36f36d0fc4">

**Comment by laozhangchen** [comment]
> 截屏

<img width="615" alt="版本号" src="https://github.com/Hex-Dragon/PCL2/assets/174254287/3d87d627-4ab8-426b-9825-5a40c63dcea0">

<img width="1080" alt="344853726-885370f6-14d2-43bd-9e00-3a36f36d0fc4" src="https://github.com/Hex-Dragon/PCL2/assets/174254287/89c71387-69d2-4909-a2ff-acdc0b3431ad">

**Comment by allMagicNB** [comment]
> > 截屏
> 
> <img width="615" alt="版本号" src="https://github.com/Hex-Dragon/PCL2/assets/174254287/3d87d627-4ab8-426b-9825-5a40c63dcea0">
> 
> <img width="1080" alt="344853726-885370f6-14d2-43bd-9e00-3a36f36d0fc4" src="https://github.com/Hex-Dragon/PCL2/assets/174254287/89c71387-69d2-4909-a2ff-acdc0b3431ad">
> 

点下刷新

**Comment by JingHai-Lingyun** [comment]
尝试刷新一下页面（按钮位于左侧 `Mod 管理` 块的右方，鼠标放上去才显示）

**Comment by allMagicNB** [comment]
超时关闭。
