### ISSUE TITLE
增加“游戏启动后，启动器以图标形式最小化到任务栏右侧”选项

### ISSUE THREAD

**Issue by LemonCat233** [Hex-Dragon/PCL2#4129]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

希望启动器可以在游戏启动后变成像微信、qq那样以一个小图标的形式缩小到任务栏右侧区域。

### 原因

我在游玩过程中经常需要看其他窗口的内容，而现在的**启动器最小化**总会在高频率切屏的时候不小心切到启动器

如果启动器可以变成“任务栏右侧区域的小图标”，在游玩过程中会方便很多，特别是要对着一些截图和资料搓很复杂的东西的时候！

**Comment by allMagicNB** [comment]
#1161
