### ISSUE TITLE
PCL2MOD下载 没有1.21版本的选项

### ISSUE THREAD

**Issue by Hayden2018666** [Hex-Dragon/PCL2#4130]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

<img width="588" alt="image" src="https://github.com/Hex-Dragon/PCL2/assets/118903758/f9d32e07-13d8-4e7d-bdd4-d7bca0c84a73">
如图所示

### 原因

（示例）
这项优化让我可以更方便地安装新版本的MOD。
如果没有这项优化，我每次都必须开加速器上网，让操作变得很麻烦。

**Comment by allMagicNB** [comment]
#4031
