### ISSUE TITLE
回声洞某条疑似价值观导向错误

### ISSUE THREAD

**Issue by MCSteve123** [Hex-Dragon/PCL2#4132]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/Hex-Dragon/PCL2/assets/121204926/6b4af372-2d62-4408-9028-bf16ee4775ea)
pot player违反GPL v3开源协议，似乎不太符合开源精神？PCL作为半开源软件，似乎不太应该有这玩意

### 重现步骤

使劲点

### 日志与附件

无

**Comment by Pigeon0v0** [comment]
那你说比起 WMP 好不好用吧

有的时候其实别纠结很多，虽然在这个事情的基础上确实不应该推荐 PotPlayer，只能说无知者无罪

**Comment by LTCatt** [comment]
个人无意宣传价值观，回声洞来自用户投稿，不必上纲上线（

**Comment by wuliaodexiaoluo** [comment]
先不考虑什么协议什么价值观什么开源精神

### 这是回声洞

里面的东西当乐子看就行，没必要太纠结这些，总不可能你踩 WMP Microsoft 就会半夜三更来你家防火吧
