### ISSUE TITLE
cur'se'forge下载模组出现错误。 

### ISSUE THREAD

**Issue by Macn114514** [Hex-Dragon/PCL2#4136]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在Curseforge官网下载史诗战斗然后再。 PC L2中显示出来的是modrinth里面的。而在PCL2中下载的Curseforge史诗战斗仍然是modrinth中的不完整模组

### 重现步骤

1、点击显示为Curse forge的模组并下载。 
2、找到官网并再次下载Curse forge的史诗战斗 ，然后点击PC L2里面的mod管理找到史诗战斗
3、右键打开史诗战斗发现在PCL2中呈现的仍是mod rinth中的不完整模组

### 日志与附件

<img width="578" alt="image" src="https://github.com/Hex-Dragon/PCL2/assets/174391659/dc7b4c4d-b49e-46c9-8fb8-deaaee07144e">
<img width="575" alt="image" src="https://github.com/Hex-Dragon/PCL2/assets/174391659/2da3fc1d-1b12-4921-ab79-e6b06fc37ee3">
<img width="579" alt="image" src="https://github.com/Hex-Dragon/PCL2/assets/174391659/89c1c6bd-7289-4b7d-9a0d-c25afe69abc0">

**Comment by Pigeon0v0** [comment]
启动器日志

**Comment by Macn114514** [comment]
> 启动器日志

日志中并没有显示出这个的模组加载错误。 况且我也找不到那个的日志。

**Comment by Macn114514** [comment]
> 启动器日志
其实并不是使用模组错误而是显示的错误以及可能是镜像下载源的错误。

**Comment by kong-que-dnf123** [comment]
事实上在PCL内部通过Curse来源下载的史诗战斗转到详细信息也是Modrin'的（（（

**Comment by Macn114514** [comment]
但是!modrinth和Course forge里面的史诗战斗相比。
modrinth史诗战斗里的物品比Course forg 里面少很多。

**Comment by Macn114514** [comment]
so， What can I say

**Comment by Deep-Dark-Forest** [comment]
> 但是!modrinth和Course forge里面的史诗战斗相比。
> modrinth史诗战斗里的物品比Course forg 里面少很多。 

那这是模组的问题，和启动器无关

**Comment by Macn114514** [comment]
> > 但是！modrinth和Course forge里面的史诗战斗相比。 modrinth史诗战斗里的物品比Course forg 里面少很多。
> 
> 那这是模组的问题，和启动器无关

那我该怎么下到原版的呢？ QwQ

**Comment by kong-que-dnf123** [comment]
> > 但是!modrinth和Course forge里面的史诗战斗相比。
> > modrinth史诗战斗里的物品比Course forg 里面少很多。
> 
> 那这是模组的问题，和启动器无关

现在的问题不是无论什么来源的史诗战斗PCL都会识别为modrin的吗

**Comment by Macn114514** [comment]
> > > 但是！摩托车和球场里面的史诗战斗相比。
> > > 莫德林斯（Modrin th）史诗战斗里的物品比球场锻造里面少很多。
> > 
> > 
> > 那这是模组的问题，和启动器无关
> 
> 现在的问题不是无论什么来源的史诗战斗PCL都会识别为莫氏剂的吗
是的。况且识别之后就不是course forge了awa
是的

**Comment by LTCatt** [comment]
理论上不应该，它识别成了 Modrinth 版本代表它的 hash 和 Modrinth 上的文件一样，那就应该两个网站的文件是相同的啊？
感觉还是第三方的问题？

**Comment by Macn114514** [comment]
> 理论上不应该，它识别成了 Modrinth 版本代表它的 hash 和 Modrinth 上的文件一样，那就应该两个网站的文件是相同的啊？ 感觉还是第三方的问题？

那只能验证一下是不是第三方的原因了。 谁能发给我史诗战斗的原模组文件再下载一遍，在PCL2中识别，看会不会再变成 Modrinth

**Comment by Macn114514** [comment]
> 可能是 API 返回的信息不一样？ 我注意到搜索时可能出现重复

 可能是吧，毕竟存储的时候两个模组下载出来都是同样的标签
