### ISSUE TITLE
追随者披风翻译 

### ISSUE THREAD

**Issue by DoubtedYapper71** [Hex-Dragon/PCL2#4137]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

增加追随者披风翻译 

### 原因

统一

**Comment by Deep-Dark-Forest** [comment]
~~非常感谢某些人的好心 Review 导致#3885 白交了（~~

**Comment by allMagicNB** [comment]
早加了

**Comment by Deep-Dark-Forest** [comment]
> 早加了，有点问题而已，@Deep-Dark-Forest 你不要拿别人的 Issue 乱用

有点问题所以这个issue是个bug反馈

**Comment by Deep-Dark-Forest** [comment]
哦我傻了，#3885 Merge 以后还没发版呢
