### ISSUE TITLE
在 Win11 中 使用 PCL2 正式版 2.7.4 以管理员身份运行会导致在主页面拖进整合包文件显示禁止图标

### ISSUE THREAD

**Issue by Mxmilu666** [Hex-Dragon/PCL2#4140]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如题
在 PCL2 最新正式版 2.7.4 中
以管理员身份运行会导致在主页面拖进整合包文件显示禁止图标
普通用户可以正常导入

复现环境:
OS:Windows 11 专业版 23H2

### 重现步骤

1、以以管理员身份运行 PCL2
2、随便找一个整合包文件拖入

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16066656/Log1.txt)

**Comment by allMagicNB** [comment]
#2531
