### ISSUE TITLE
在版本描述被更改以后，仍能查看当前游戏版本号和模组加载器版本号

### ISSUE THREAD

**Issue by nathanlcl** [Hex-Dragon/PCL2#4141]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在版本设置-概述中，添加类似详信息的东西，以便在版本描述被更改以后，仍能查看当前游戏版本号和模组加载器版本号

### 原因

这项优化让我可以更方便地在我忘记版本号时为整合包添加额外的模组，如Fabulously Optimized这类性能优化整合包。
如果没有这项优化，我每次忘记版本号都必须前往版本文件夹中的json文件中查看，让操作变得很麻烦。

**Comment by JingHai-Lingyun** [comment]
某种意义上这个东西非常的奇怪，因为如果你修改了版本描述，你应当知道这会让你无法快捷查看该信息

**Comment by LTCatt** [comment]
适用范围不大，暂时不考虑，抱歉（

**Comment by WForst-Breeze** [comment]
为便于搜索重复反馈，故修改为 拒绝/放弃 Label~
