### ISSUE TITLE
升级赞助档位使用解锁码时启动器崩溃

### ISSUE THREAD

**Issue by LowEntropyYR** [Hex-Dragon/PCL2#4144]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

将解锁码复制好后，点击启动器关于与鸣谢中的输入解锁码按钮，启动器卡住，几秒钟后崩溃关闭。（PS：当时网络不太好，反复三四次都出现了这个bug）

### 重现步骤

1、点击更多
2、点击关于与鸣谢
3.下滚，点击输入解锁码

### 日志与附件

[Log5.txt](https://github.com/user-attachments/files/16070246/Log5.txt)

**Comment by allMagicNB** [comment]
#3990

**Comment by wuliaodexiaoluo** [comment]
请在快照版使用解锁码
快照版可以登录爱发电回复下载，点击自动回复给出的链接就行
