### ISSUE TITLE
提示正版登录失败，且使用魔法后亦不可以登录

### ISSUE THREAD

**Issue by Hamster-github** [Hex-Dragon/PCL2#4148]
### 检查项

- [ ] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

提示登陆失败，连接服务器超时。提示请检查网络环境是否良好。给出原因是操作 https://xsts.auth.xboxlive.com/xsts/authorize 超时。(如图1)
![屏幕截图 2024-07-03 070739](https://github.com/Hex-Dragon/PCL2/assets/119768794/a90b30e8-4146-46fa-9e49-689cf5154ad6)
                                                                                                 (图1)

魔法上网后，问题依旧。换上 Google DNS 后，问题依旧。求给出解决方案。

### 重现步骤

1.打开PCL启动器
2.登录正版
3.点击启动
4.复现成功

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16075084/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16075087/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16075088/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16075089/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16075090/Log5.txt)

**Comment by wuliaodexiaoluo** [comment]
Win+R 输入cmd，回车，输入 nslookup xsts.auth.xboxlive.com
截图窗口我看看

**Comment by allMagicNB** [comment]
使用 Google DNS ≠ 魔法（梯子）

**Comment by wuliaodexiaoluo** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/160083863/2ae2ed6c-aa50-4107-a1f8-4ae4c1f9a72f)
不知道什么情况，但可能和这个有关系

**Comment by allMagicNB** [comment]
那就#4147
