### ISSUE TITLE
通过[添加已有文件夹]添加文件夹后无法删除此文件夹

### ISSUE THREAD

**Issue by Kirito666233** [Hex-Dragon/PCL2#4149]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在进行重现步骤后可能会出现此问题：启动pcl软件后就自动在桌面上创建了一个名为[整合包]的文件夹，已尝试如下操作【重新删除pcl并用最新版，pcl文件夹完全删除，更换其他盘进行启动pcl】以上均依旧创建文件夹，并未测试删除pcl注册表是否会解决此问题

### 重现步骤

1、在桌面创建了一个文件夹，把pcl拖入文件夹中，双击启动
2、在桌面创建一个名为[整合包]的文件夹
3、版本选择-左侧【添加或导入】下的添加已有文件夹，把【整合包】文件夹添加进去
4、删除【整合包】文件夹，pcl关闭

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16076581/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16076583/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16076584/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16076585/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16076586/Log5.txt)

**Comment by Kirito666233** [comment]
目前在注册表中看见有名为SystemSystemCache，的项含有【C:\Users\YoshinoRinne\Desktop\整合包\PCL】，删除后恢复正常

**Comment by allMagicNB** [comment]
不能进 PCL 的版本文件夹里删掉？

**Comment by kong-que-dnf123** [comment]
我再试试，失败了...
![image](https://github.com/Hex-Dragon/PCL2/assets/120994373/8e802efd-55ab-4e4e-a718-0fa5812e5f6c)

**Comment by JingHai-Lingyun** [comment]
在 PCL 启动的时候删除掉所检查的文件夹导致 PCL 崩溃？

**Comment by lactobionicAcid** [comment]
楼主想表达的意思是每次打开PCL时都会在桌面上新建一个名为“整合包”的文件夹

`SystemSystemCache`是PCL启动器的缓存文件夹，每次启动时都会自动创建，所以这是正常现象
进入设置→启动器→缓存文件夹，把缓存的路径改了就好了

**Comment by JingHai-Lingyun** [comment]
待 Author 确认一下上述内容是否起到了帮助，如果是的话就可以关掉了
~~话说如果真是这样的话有那么一点点好笑... 咳咳 嗯 不好意思~~

**Comment by lactobionicAcid** [comment]
> 待 Author 确认一下上述内容是否起到了帮助，如果是的话就可以关掉了 ~话说如果真是这样的话有那么一点点好笑... 咳咳 嗯 不好意思~

Author 不是已经解决问题了吗？🤔 ~而且已经过去两周了...~

**Comment by JingHai-Lingyun** [comment]
超时关闭，如果有需要请继续回复
