### ISSUE TITLE
安装内存过大后不显示“已使用内存”字样

### ISSUE THREAD

**Issue by MediatorYang** [Hex-Dragon/PCL2#415]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

电脑装了32g内存，然后就不显示“已使用内存”了，换成16g之后就又好了

这是32g的
![2022_11_19](https://user-images.githubusercontent.com/118263842/202848626-c62aefe2-ffb5-4a00-8dea-5398f1c44e98.png)

这是16g的（换了一台电脑试的）
![屏幕截图 2022-11-19 193507](https://user-images.githubusercontent.com/118263842/202848783-34aea887-6982-4fc7-b06c-64a385abe412.jpg)

### 重现步骤

1.先装32g内存，
2.设置-游戏-游戏内存
然后就应该？

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10046868/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10046869/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10046870/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10046871/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10046872/Log1.txt)

**Comment by WTP016-CN** [comment]
请在其他使用 32G 的电脑上测试已确认其不为偶发问题

**Comment by LTCatt** [comment]
因为写不下……

**Comment by allMagicNB** [comment]
那为什么不把游戏分配文本放右边？ :thinking:
不对感觉好像有点怪。

**Comment by lactobionicAcid** [comment]
游戏分配不一定要一直跟着那个条，可以在向左运动到快要挡住已使用内存时停止运动……？
大概如下图所示

![Image](https://github.com/user-attachments/assets/b730830b-18b9-46d2-967a-44952c9fbc54)

**Comment by LTCatt** [comment]
之后有空重做一下这个 UI 吧……

**Comment by RyogiMutsuki** [comment]
我觉得可以把总内存改成剩余内存，然后拆三段显示，这样更直观一点

这个总内存其实意义不大，玩游戏根本就不会在意这个，只要游戏流畅就行
