### ISSUE TITLE
在无版本使用 Litteskin 登录时，点击注册账号按钮会导致报错

### ISSUE THREAD

**Issue by Mxmilu666** [Hex-Dragon/PCL2#4151]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/Hex-Dragon/PCL2/assets/82694310/ebb01769-75e1-45b4-9e63-48c2b9db9350)
如图

### 重现步骤

1、随便安装一个版本
2、版本内启用 Litteskin 登录
3、删除版本
4、点击注册账号按钮

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16076990/Log1.txt)

**Comment by allMagicNB** [comment]
`[12:09:47.815] [Start] 程序版本：Snapshot 2.6.8（305）`

**Comment by allMagicNB** [comment]
能在最新版复现的话请继续 Comment。

**Comment by Mxmilu666** [comment]
Snapshot 2.7.4 (325) 复现
[Log1.txt](https://github.com/user-attachments/files/16077470/Log1.txt)
