### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Tanxiangzhong** [Hex-Dragon/PCL2#4152]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃基本不是 PCL 的原因，请 **不要** 提交反馈。你可以在论坛或社区找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用 HMCL 启动，HMCL 没有出现问题。** 如果 HMCL 也无法启动就不是 PCL 导致的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

[Log3.txt](https://github.com/user-attachments/files/16077222/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16077223/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16077224/Log5.txt)

### PCL 错误报告、日志与附件

[Log5.txt](https://github.com/user-attachments/files/16077218/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/16077220/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16077221/Log2.txt)

### HMCL 启动脚本

[Log1.txt](https://github.com/user-attachments/files/16077213/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16077215/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16077216/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16077217/Log4.txt)

**Comment by allMagicNB** [comment]
请简要描述错误的具体内容。

**Comment by wuliaodexiaoluo** [comment]
```
[09:10:14.561] 合并文件出错（1.17.json）：文件“C:\Users\86139\AppData\Local\Temp\PCL\Download\224_228_975070.tmp”正由另一进程使用，因此该进程无法访问此文件。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   在 PCL.ModNet.NetFile.Merge()
错误类型：System.IO.IOException
```
不用等了，翻了下日志，大概率是想反馈这玩意，但问题是这完全解决不了

**Comment by allMagicNB** [comment]
鬼知道，反正先让龙猫看看（

**Comment by LTCatt** [comment]
请按照检查项要求重新提交一个反馈。
