### ISSUE TITLE
1.15.2版本fabric+高清修复 游戏错误

### ISSUE THREAD

**Issue by zec896219** [Hex-Dragon/PCL2#4153]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

进不去游戏

### 重现步骤

1.15.2版本fabric+高清修复

### 日志与附件

1

**Comment by allMagicNB** [comment]
装 OptiFabric 没？

**Comment by zec896219** [comment]
装了！！！！

**Comment by allMagicNB** [comment]
> 装了！！！！

发错误报告

**Comment by zec896219** [comment]
启动器自动下载的是OptiFabric1.15.2要用OptiFabric origins

**Comment by zec896219** [comment]
启动器没提示错误

**Comment by JingHai-Lingyun** [comment]
问题是什么，没有自动安装 OptiFabric Origins 还是安装后游戏崩溃还是什么

**Comment by zec896219** [comment]
没有自动安装 OptiFabric Origins 安装的是OptiFabric

**Comment by zec896219** [comment]
游戏进不去主界面

**Comment by JingHai-Lingyun** [comment]
我测试一下
另请善用 Edit 功能（在哪里？信息右上角 `...` -> `Edit`）而不是连续发送信息

**Comment by allMagicNB** [comment]
你得选自动安装。

**Comment by zec896219** [comment]
就是自动安装

**Comment by allMagicNB** [comment]
自动安装 OptiFabric……

**Comment by zec896219** [comment]
？

**Comment by JingHai-Lingyun** [comment]
@allMagicNB 麻烦暂停一下等我测试一下具体什么情况

**Comment by zec896219** [comment]
![屏幕截图 2024-07-03 182436](https://github.com/Hex-Dragon/PCL2/assets/173539970/7fd70a1f-c63c-414e-a8b6-acaca35a292b)

**Comment by allMagicNB** [comment]
我好像知道了

**Comment by zec896219** [comment]
![屏幕截图 2024-07-03 182741](https://github.com/Hex-Dragon/PCL2/assets/173539970/fa74c451-03ae-48ae-8508-4f35c0152669)

**Comment by zec896219** [comment]
这个可以

**Comment by JingHai-Lingyun** [comment]
OptiFabric 貌似并未完全兼容 OptiFine G6 于 1.15.2 版本
据此认定貌似应当 Revert 由 #3403 带来的修改

**Comment by allMagicNB** [comment]
……干脆把自动安装给删了，然后在同时安装 Fabric 和 OptiFine 时把 OptiFine 塞 mods 文件夹里吧。

**Comment by JingHai-Lingyun** [comment]
> 把 OptiFine 塞 mods 文件夹里

现在 OptiFine 就躺在那里呢……
![image](https://github.com/Hex-Dragon/PCL2/assets/109946426/26cab6a4-f633-4184-916b-5c24427087c3)

**Comment by wuliaodexiaoluo** [comment]
请各位控制下发帖数量，减少版聊，提 Issue 的目的不是为了在争辩中赢过对方
>？
请尽量减少无效发帖（不要只发符号啊喂！）

**Comment by allMagicNB** [comment]
所以改成啥样了（

**Comment by LTCatt** [comment]
Revert #3403

**Comment by zec896219** [comment]
F6F4-896D-ED9E-8FAE

**Comment by zec896219** [comment]
F6F4-896D-ED9E-8FAE

**Comment by LTCatt** [comment]
你的解锁码：dMzlTdN6zbq5FDp0l1p1N4HJwU3iE6Rk
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
