### ISSUE TITLE
在版本设置→概览中的“快捷方式”中增加“材质包文件夹”

### ISSUE THREAD

**Issue by zhu112233** [Hex-Dragon/PCL2#4154]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

如题

### 原因

我需要这个功能来快捷安装材质包。很多人都有安装材质包的需求，但如果没有这个功能，就不能快捷安装材质包了。

**Comment by allMagicNB** [comment]
#606
