### ISSUE TITLE
搜索Java时跳过网络驱动器

### ISSUE THREAD

**Issue by FFDVDGD** [Hex-Dragon/PCL2#4156]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

如题，在搜索Java时可选择跳过网络驱动器。

### 原因

在某些情况下（比如我把mc服务器硬盘通过raildrive挂载到本地时）可以大大缩短搜索所需时间以及简化Java列表。

**Comment by JingHai-Lingyun** [comment]
参见 #3705
如果真的很想要的话去那下面回复吧

**Comment by allMagicNB** [comment]
#3705

**Comment by Deep-Dark-Forest** [comment]
#3705
