### ISSUE TITLE
在选择披风界面添加对“追随者披风”的翻译

### ISSUE THREAD

**Issue by Hill23333** [Hex-Dragon/PCL2#4157]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

![image](https://github.com/Hex-Dragon/PCL2/assets/104297546/b23b79f8-e327-4b63-a956-d889ce7c4e82)

### 原因

如图，15周年纪念披风和紫色心型披风已经追加翻译，但是追随者披风没有。版本是最新的快照版

**Comment by allMagicNB** [comment]
加了，但是还没更新呢……
