### ISSUE TITLE
用户名带中文时依然无法启动 MC

### ISSUE THREAD

**Issue by ZHUANGYIXIE** [Hex-Dragon/PCL2#416]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃不是 PCL2 的原因，请 **不要** 提交反馈。你可以在 QQ 群里或者论坛找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是游戏本身的问题，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

只有1.18版本不能启动
[错误报告-2022-11-19_22.36.11.zip](https://github.com/Hex-Dragon/PCL2/files/10047221/-2022-11-19_22.36.11.zip)

### 错误报告、日志与附件

[错误报告-2022-11-19_22.36.11.zip](https://github.com/Hex-Dragon/PCL2/files/10047219/-2022-11-19_22.36.11.zip)

**Comment by bwtx2022** [comment]
建议尝试重装该版本

**Comment by LTCatt** [comment]
#353 重复

**Comment by LTCatt** [comment]
不对，这是 #218 没修好……

**Comment by LTCatt** [comment]
![image](https://user-images.githubusercontent.com/40348278/202915827-5fc2afbe-0353-4f68-9ec0-a60f80a534fe.png)
PCL2 已经判断了路径里有中文，自动换了个文件夹

![image](https://user-images.githubusercontent.com/40348278/202915839-d6b8676d-d391-4bb6-9999-3b13fcec4005.png)
但是 Wrapper 还没有这个检测，它会尝试解压到有中文的文件夹

**Comment by LTCatt** [comment]
![image](https://user-images.githubusercontent.com/40348278/202916038-cc20d268-3e41-473e-9361-50ca0f9d64d4.png)
参考路径 @00ll00

**Comment by 00ll00** [comment]
收到🌹

**Comment by 00ll00** [comment]
新增启动参数指定临时文件路径

[更新wrapper](https://github.com/00ll00/java_launch_wrapper/releases/tag/v1.3)

**Comment by LTCatt** [comment]
谢谢🌹
