### ISSUE TITLE
管理员身份运行时无法拖拽安装MOD

### ISSUE THREAD

**Issue by Wzq081001creator** [Hex-Dragon/PCL2#4161]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

当以管理员身份运行pcl2时，无法使用将MOD文件拖拽到pcl2窗口的方式安装mod。

### 原因

这项优化让我可以更方便地**拖拽安装mod**。
如果没有这项优化，我每次都必须**打开mod文件夹安装**，让操作变得很麻烦。

**Comment by JingHai-Lingyun** [comment]
#2531
