### ISSUE TITLE
快照版支持将PCL主题一键调整为当前Windows主题色

### ISSUE THREAD

**Issue by MCSteve123** [Hex-Dragon/PCL2#4162]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

叠甲：
 - 注意是**快照版**
 - **已在常见列表中检索**，发现类似内容但**似乎有所不同**

正文：
如题，作为使用壁纸引擎的用户，整个电脑主题色时不时会变（换壁纸就行），但是PCL不会变就有点搞……？
~我想这东西应该不难吧~

### 原因

我需要这个功能来将PCL主题一键调整为当前Windows主题色。很多人都有将PCL主题一键调整为当前Windows主题色的需求，但如果没有这个功能，就不能将PCL主题一键调整为当前Windows主题色了。

**Comment by LTCatt** [comment]
暂不考虑，过于超出启动器范畴了（

**Comment by MCSteve123** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/121204926/b860e853-1ef1-420b-9b35-14fc7e8498ee)
~突然发现这一套好像挺搭~
