### ISSUE TITLE
Mod下载界面内新版本检索有问题

### ISSUE THREAD

**Issue by shuixxing233** [Hex-Dragon/PCL2#4163]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

Mod下载里新版本会莫名其妙出现其他版本的（这个很早之前就有了，但那会我没提issue）

### 原因

（示例）
这项优化让我可以更方便地xxxx。
如果没有这项优化，我每次都必须xxxx，让操作变得很麻烦。

**Comment by shuixxing233** [comment]
![bandicam 2024-07-05 21-08-48-340](https://github.com/Hex-Dragon/PCL2/assets/121666305/0e8f9ade-02a3-41ad-a60b-fc9e8c6ecdb5)
如上图

**Comment by allMagicNB** [comment]
哥你语文不好好歹给个截图啊……

**Comment by allMagicNB** [comment]
大概率由傻逼作者导致……

**Comment by shuixxing233** [comment]
> 你语文不好的话好歹给个截图啊……

后面发了

**Comment by allMagicNB** [comment]
谁去 CurseForge 上看看？

**Comment by shuixxing233** [comment]
> 谁去 CurseForge 上看看？

![bandicam 2024-07-05 21-21-57-667](https://github.com/Hex-Dragon/PCL2/assets/121666305/81555c50-7db9-4940-b510-6d3a6f848741)
比较抽象的是原作者说1.16.5也能用，但是根据我测试压根用不了（而且这更新时间为啥对不上）

**Comment by Deep-Dark-Forest** [comment]
> 比较抽象的是原作者说1.16.5也能用，但是根据我测试压根用不了

这肯定是作者问题，与启动器无关

> 而且这更新时间为啥对不上

？curseforge上这更新日期是7月1日，PCL里说是4天前，今天是7月5日，四天前不就正好是7月1日吗（

**Comment by Deep-Dark-Forest** [comment]
![private-user-images.githubusercontent.com_346136248-81555c50-7db9-4940-b510-6d3a6f848741_edit_58404787652546.jpg](https://github.com/Hex-Dragon/PCL2/assets/131975043/269e5679-f7d1-4064-b29e-3e61067e7b26)

这个文件名中包括“1.16.4”，但是作者却设置了支持1.16.5和1.16.4，所以在启动器中这个版本在1.16.5和1.16.4中都出现过，是模组作者的问题，与PCL无关。

**Comment by wuliaodexiaoluo** [comment]
>比较抽象的是原作者说1.16.5也能用，但是根据我测试压根用不了（而且这更新时间为啥对不上）

实际上，Mod 要求 Fabric 0.15.10 以上版本运行，所以这不是 Mod 作者的问题，是 Author 自己的问题的说......
