### ISSUE TITLE
模组列表中多次出现重复的模组

### ISSUE THREAD

**Issue by SunyuxiaoMC** [Hex-Dragon/PCL2#4168]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

模组列表中多次出现重复的模组

### 重现步骤

https://github.com/Hex-Dragon/PCL2/assets/165477453/86991b25-3ebd-4d70-8775-628cbb0bab24

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16114849/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16114850/Log2.txt)

**Comment by JingHai-Lingyun** [comment]
这是刻意的行为，当来自 CurseForge 和来自 Modrinth 的模组（工程）元数据不同时不予以去重
参见 #1318
