### ISSUE TITLE
下载失败报错

### ISSUE THREAD

**Issue by Lmk2333** [Hex-Dragon/PCL2#4169]
### 检查项

- [ ] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我在下载乌托邦整合包（b站上的整合包）的时候一直发生错误，提示为：
整合包安装失败
→ 解压整合包文件失败
→ 块的长度与它的补集不匹配。
   在 PCL.ModBase.ExtractFile(String CompressFilePath, String DestDirectory, Encoding Encode)
   在 PCL.ModModpack.UnpackFiles(String InstallTemp, String FileAddress, LoaderBase Loader)
   在 PCL.ModModpack._Closure$__10-0._Lambda$__0(LoaderTask`2 Task)
   在 PCL.ModLoader.LoaderTask`2._Closure$__13-0._Lambda$__0()
错误类型：System.IO.InvalidDataException
我在HMCL启动器上也下载失败
但是我并未在网上搜索到跟我相同报错的人，求求解决一下

### 重现步骤

将乌托邦的整合包文件拖到pcl下载解压

### 日志与附件

[Log2.txt](https://github.com/user-attachments/files/16115295/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16115296/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16115297/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16115298/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/16115299/Log1.txt)

**Comment by hejiehao** [comment]
似乎是你的整合包损坏了

**Comment by JingHai-Lingyun** [comment]
怀疑是你的网络不好导致下载到的整合包不全，提供一下你的整合包文件

**Comment by Lmk2333** [comment]
https://pan.quark.cn/s/eaea50184e65#/list/share我下的是乌托邦3.2fix，更换了几个不同的网络环境但是进度条用远卡在12.78%，这是下载地址，文件有点大上传不了，压缩包文件也重新下过了QAQ

**Comment by LTCatt** [comment]
> 如果其他启动器也存在问题，证明并非 PCL 的问题，请 不要 提交反馈。
这是你的压缩包无法解压。
