### ISSUE TITLE
自定义主题无法实时更换

### ISSUE THREAD

**Issue by tu6133** [Hex-Dragon/PCL2#4171]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

更新至快照2.8.0 主题更换似乎出现了问题
![be61a606e7d04579b1282340580b4a09](https://github.com/Hex-Dragon/PCL2/assets/174873875/075ef91e-b3a1-4c82-9949-bc48797ba114)

### 重现步骤

1.点击设置
2.然后点击个性化中自定义主题
![1](https://github.com/Hex-Dragon/PCL2/assets/174873875/b9a524ee-ab20-41ff-a2b9-87f92cb8cc22)
3.拖动拖动色调/色点渐变/饱和度/亮度无反应
![2](https://github.com/Hex-Dragon/PCL2/assets/174873875/09f7e96b-0e3e-4c97-9638-0827ed344954)
4.点击其他任意主题后再恢复自定义才可显示更改自定义主题更改后的效果
![3](https://github.com/Hex-Dragon/PCL2/assets/174873875/ff0382f4-0dd7-46a3-86df-cb041c68c5f5)
![4](https://github.com/Hex-Dragon/PCL2/assets/174873875/026d310b-4603-4f10-8d2f-f77e881c673c)
5.切换至快照2.6.8可正常切换

### 日志与附件

[Log3.txt](https://github.com/user-attachments/files/16116182/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16116183/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16116184/Log5.txt)
[Log.txt](https://github.com/user-attachments/files/16116185/Log.txt)
[Log1.txt](https://github.com/user-attachments/files/16116186/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16116187/Log2.txt)

**Comment by JingHai-Lingyun** [comment]
实测除了透明度其他的都在 2.8.0 中无法即使更新，重启 PCL 后正常更新，但再做出改动仍然不响应
[调试模式 Log1.txt](https://github.com/user-attachments/files/16116197/Log1.txt)

**Comment by tu6133** [comment]
识别码2D62-C947-49CA-B78A

**Comment by tu6133** [comment]
2D62-C947-49CA-B78A 帮忙解锁下

**Comment by LTCatt** [comment]
你的解锁码：+DuTbsY5RMpHI9FfV05hNRJSedT3pT/E
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
