### ISSUE TITLE
[Bug][存档] jlw 临时目录可能指定到错误的驱动器上

### ISSUE THREAD

**Issue by sulingjiang** [Hex-Dragon/PCL2#4172]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

jlw 临时目录可能指定到软盘驱动器上
原 issue 因为小洛的账号被标记为 Spam User 导致被 delete 了，未知是否可以恢复，所以存个档
如果确认可恢复还麻烦大大关掉

### 重现步骤

虚拟机复现

### 日志与附件

拿不出手（暂时没法提供日志，不过已经打过处理中的 label 了）

**Comment by JingHai-Lingyun** [comment]
~~账户被 Takedown 了么…… 删掉的 Issue 貌似是不能恢复的……~~

Label 恢复为处理中，但无法知道原优先级，故不设置优先级 Label
作者指北： @wuliaodexiaoluo

<details>

<summary>旧信息历史</summary>

![image](https://github.com/Hex-Dragon/PCL2/assets/109946426/bab98b07-a549-46d7-bd8e-5bb8da1be5af)
![image](https://github.com/Hex-Dragon/PCL2/assets/109946426/16d2f5fd-3d78-4d77-9250-0abe547c604a)

</details>

**Comment by sulingjiang** [comment]
小洛的标记被移除了，Issue 也恢复了，就关掉了，很抱歉带来了不必要的打扰
