### ISSUE TITLE
提升性能：添加vulkan渲染方式

### ISSUE THREAD

**Issue by Arden233** [Hex-Dragon/PCL2#4174]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

添加多种渲染方式，dx，opengl，vulkan
最好还是添加vulkan渲染吧

如果可以的话，建议弄一个gc选择器，把gc选择图形化

### 原因

增加性能释放和利用率，更加贴合现代电脑，顺应历史发展潮流（主要是帧率会上升，内存使用降低

**Comment by hejiehao** [comment]
https://github.com/Hex-Dragon/PCL2/issues/1904
