### ISSUE TITLE
单击[输入解锁码]时崩溃

### ISSUE THREAD

**Issue by andypeng1** [Hex-Dragon/PCL2#4176]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我在更多 → 关于与鸣谢 → 输入解锁码时单击了[输入解锁码]按钮但是pcl2发生了闪退。

### 重现步骤

1、找到更多 → 关于与鸣谢
2、往下滚，然后点击[输入解锁码]按钮

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16116541/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16116542/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16116543/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16116544/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16116545/Log5.txt)

**Comment by andypeng1** [comment]
我已经确保我的pcl2是最新版本

**Comment by JingHai-Lingyun** [comment]
[调试模式 Log1.txt](https://github.com/user-attachments/files/16116555/Log1.txt)
此问题于快照版中发生，**不应当与 #3990 重复**

**Comment by andypeng1** [comment]
那我应当怎么做才能防止启动器闪退

**Comment by Deep-Dark-Forest** [comment]
> 那我应当怎么做才能防止启动器闪退
> 

或许只能等此 bug 被修复，即下个版本……

**Comment by andypeng1** [comment]
3A1C-8DEC-9031-E087 解锁

**Comment by LTCatt** [comment]
你的解锁码：2KuPwLZ5tGlm3o8PiaKyXokpoeiXZ74Z
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by andypeng1** [comment]
2E95-5137-B489-062D

**Comment by Light-Beacon** [comment]
> 2E95-5137-B489-062D
> 
> 

你的解锁码：+xes+hRekYqvpO/LxN5Q+thSWCscgaQy

**Comment by andypeng1** [comment]
好的👌
