### ISSUE TITLE
PCL2不能识别整合包加载器的beta版本

### ISSUE THREAD

**Issue by lactobionicAcid** [Hex-Dragon/PCL2#4179]
### 检查项

- [x] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

向PCL2导入[BlockFront整合包](https://www.curseforge.com/minecraft/modpacks/blockfront-world-war-ii)（NeoForge版本 21.0.42-beta）时，PCL2在整合包安装过程指向一个空的下载链接：
`https://bmclapi2.bangbang93.com/maven/net/neoforged/neoforge/21.0.42/neoforge-21.0.42-installer.jar`，
而正确的下载链接应该是：
`https://bmclapi2.bangbang93.com/maven/net/neoforged/neoforge/21.0.42-beta/neoforge-21.0.42-beta-installer.jar`。

可知PCL2启动器将该整合包的模组加载器识别为NeoForge 21.0.42，但在官网上仅有其对应的beta版本。

### 重现步骤

以[BlockFront整合包](https://www.curseforge.com/minecraft/modpacks/blockfront-world-war-ii)为例，
1. 下载该整合包的0.5.0.2a版本；
2. 下载完成后导入PCL2，PCL2提示游戏安装失败。

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16117173/Log1.txt)
整合包校验文件：[manifest.json](https://github.com/user-attachments/files/16117174/manifest.json)

**Comment by LTCatt** [comment]
```
[03:58:00.777] [ModPack] 整合包 NeoForge 版本：neoforge-21.0.42-beta
[03:58:00.781] [Download] 已清理合并安装缓存
[03:58:00.781] [Download] NeoForge 缓存：O:\pclCache\Install\739319890\versions\neoforge-21.0.42
[03:58:00.781] [Download] 对应的原版版本：1.21
[03:58:00.786] [Download] Forgelike 安装目标版本文件夹：O:\pclCache\Install\739319890\versions\neoforge-21.0.42\
[03:58:00.786] [Download] 检测为 NeoForge：21.0.42
```

**Comment by lactobionicAcid** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/115075633/6a631143-edad-4b21-a829-34fa3dbdb225)
以“-”为分隔符取第二段作为加载器版本...？🤔可否将这里改为去除前缀（neoforge-）后读取？
