### ISSUE TITLE
更新密钥已改成在爱发电获取，而PCL仍提示在PCL2内群获取

### ISSUE THREAD

**Issue by CN171-1** [Hex-Dragon/PCL2#418]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在设置中检查启动器更新时，PCL2提示请在内群输入.更新获取更新密钥，而Q群的.更新命令已在8月停止使用

### 原因

建议将提示改为请在爱发电输入.更新以获取更新密钥，如果不更改，可能会使新用户多走一圈弯路.png

**Comment by CN171-1** [comment]
![QQ图片20221120120119](https://user-images.githubusercontent.com/110646806/202885189-131dc19c-f0f8-43a3-98dd-5611f73473fc.png)
如图所示，启动器版本为2.4.0

**Comment by CN171-1** [comment]
az，才看到2.4.2改了

**Comment by Louis-ZYH** [comment]
6
