### ISSUE TITLE
Action 自动构建的 PCL2 会出现快照版提示

### ISSUE THREAD

**Issue by wuyuncheng-26** [Hex-Dragon/PCL2#4181]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

本来是想尝鲜一下 2.8.1（
下载了 [Release 2.8.1](https://github.com/Hex-Dragon/PCL2/actions/runs/9821379854/artifacts/1673876614) 后发现了这个 BUG
接着又测试了其他版本，发现除了 BETA 以外，其他的全部会出现这个提示（不只是 2.8.1）
不知道这是刻意的设计还是 BUG（

### 重现步骤

1、在 Action 内下载任意版本的 PCL（BETA 除外）
2、解压后运行即可发现快照版提示

### 日志与附件

![image](https://github.com/Hex-Dragon/PCL2/assets/122529705/ad411902-01ec-47f9-9ed8-6f178b60c9bd)
![image](https://github.com/Hex-Dragon/PCL2/assets/122529705/22714f10-7c58-4891-babf-79fa70cd0087)

**Comment by sulingjiang** [comment]
这其实是快照版扣掉部分代码，不影响的

**Comment by wuyuncheng-26** [comment]
> 这其实是快照版扣掉部分代码，不影响的

的确不影响，只是影响赞助者的权利（

**Comment by Pigeon0v0** [comment]
这又不能用主题...

**Comment by sulingjiang** [comment]
好像损失的只是优先体验？问题应该不大？

**Comment by wuyuncheng-26** [comment]
雀氏 不过这的确是 BUG（

**Comment by Pigeon0v0** [comment]
那你别开源了 一旦开源你自己编译一份都能优先体验...

**Comment by wuyuncheng-26** [comment]
虽然不能用主题，但主页上的这个提示不是以假乱真吗？
这要是赞助者看到了，是不是会觉得自己白赞助了（bushi
猜想罢了 大伙们别当真

**Comment by Deep-Dark-Forest** [comment]
感觉没问题，这个东西放在这太具有误导性了，不让转发……

**Comment by Mxmilu666** [comment]
我感觉有无都一样，毕竟都是开源的了，应该没人会拿快照版的 PCL 找优越感?(

**Comment by wuyuncheng-26** [comment]
> 我感觉有无都一样，毕竟都是开源的了，应该没人会拿快照版的 PCL 找优越感?( 并且开源版不是启动会弹窗吗，如果要改的话可以把开源版弹窗里面的内容移到提示那里

嗯 我是希望能够把这个快照版提示移除 换成开源版提示

**Comment by LTCatt** [comment]
由于开源版需要自己编译并且不允许公开传播，本质上这是基于研究目的使用的，所以不会为了开源版本而去修改特殊的行为，抱歉 :/

**Comment by wuyuncheng-26** [comment]
orz 好吧
