### ISSUE TITLE
PCL提示：可视化optfine安装列表出错：从字符串“”到类型“double”的转换无效

### ISSUE THREAD

**Issue by CHlaowei** [Hex-Dragon/PCL2#4183]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

bug提示输入字符串的格式不正确

### 重现步骤

1、在下载页自动安装任意版本
2、在附加安装时点击任意forge版本
3、报错

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16118234/Log1.txt)
[Log2(1).txt](https://github.com/user-attachments/files/16118235/Log2.1.txt)
[Log2.txt](https://github.com/user-attachments/files/16118236/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16118237/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16118238/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16118239/Log5.txt)
[Log1(1).txt](https://github.com/user-attachments/files/16118240/Log1.1.txt)

**Comment by allMagicNB** [comment]
权限问题

**Comment by LTCatt** [comment]
无法复现，需要更详细的复现方法

**Comment by allMagicNB** [comment]
在哪个 Log？

**Comment by sulingjiang** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/174881650/eafe73be-6f91-45d1-8a4d-ff5fb31aa60b)
[Log1.txt](https://github.com/user-attachments/files/16118657/Log1.txt)
已复现，并且还会崩启动器
1.16.1以上版本选中部分 OptiFine 可能导致此问题

**Comment by JingHai-Lingyun** [comment]
从 BMCLAPI 获取到的数据为空，随即导致了可视化失败。
由于在 NeoForge 制作过程中 bangbang93 给 Forge 和 NeoForge 加上了列表查询功能，不知道是不是因为那个导致的。

**Comment by Bdminton** [comment]
+1
![屏幕截图 2024-07-09 095531](https://github.com/Hex-Dragon/PCL2/assets/95528713/63be2b41-42b4-4e65-8706-a12b3979abfa)
[Log1.txt](https://github.com/user-attachments/files/16136061/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16136062/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16136063/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16136064/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16136065/Log5.txt)

**Comment by Bdminton** [comment]
关键是我也没装Optifine啊，是在装Forge的时候突然弹出来的

**Comment by wuliaodexiaoluo** [comment]
实际上是因为Forge 版本列表为空导致的，各种需要 Forge 做前置的组件都会弹出这个错误

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: 丝光沸石 ***@***.***>
发送时间: Tuesday, July 9, 2024 10:03:04 AM
收件人: Hex-Dragon/PCL2 ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [Hex-Dragon/PCL2] PCL提示：可视化optfine安装列表出错：从字符串“”到类型“double”的转换无效 (Issue #4183)


关键是我也没装Optifine啊，是在装Forge的时候突然弹出来的

―

**Comment by zhenhuenshi** [comment]
我是在OptiFine官网下载OptiFine_1.15.2_HD_U_G6但安装失败之后出现这个BUG的（第一次装，不知道是不是我自己的问题，之前好好的QAQ）

**Comment by SALTWOOD** [comment]
初步怀疑是 BMCLAPI 的问题，但因为 BMCLAPI 理论上只是个镜像……不知道是否官方能够复现。如果可以，可以联系 bangbang93 看看

**Comment by lwzminecraft** [comment]
[Log2.txt](https://github.com/user-attachments/files/16172498/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16172499/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16172501/Log4.txt)
[Log5.txt](https://github.com
![屏幕截图(2)](https://github.com/Hex-Dragon/PCL2/assets/96067843/99f9f045-c3f1-46dd-b1f0-3d0205e6ecdd)
/user-attachments/files/16172502/Log5.txt)
1.12.2安装forge出现此问题，optifine无此问题

**Comment by lwzminecraft** [comment]
> 初步怀疑是 BMCLAPI 的问题，但因为 BMCLAPI 理论上只是个镜像……不知道是否官方能够复现。如果可以，可以联系 bangbang93 看看
不是BMCL的问题，使用官方源也一样

**Comment by lwzminecraft** [comment]
![屏幕截图(3)](https://github.com/Hex-Dragon/PCL2/assets/96067843/e40570de-1c66-49eb-ba44-a70bd25ad160)
![屏幕截图(4)](https://github.com/Hex-Dragon/PCL2/assets/96067843/135cd224-37a0-42b6-9d78-0e6e384bc956)
此bug不影响forge的下载与安装

**Comment by CHlaowei** [comment]
识别码

**Comment by CHlaowei** [comment]
解锁码

**Comment by CleverBSOD** [comment]
这个issue一年之后竟然还有个回复

**Comment by FXDYJ** [comment]
草给一年后的我炸回来了

**Comment by LTCatt** [comment]
你的解锁码：Ulk09gOrQnrOgBs0D7TtX2imiWr3aVRH
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
