### ISSUE TITLE
根据@tangge233的提案（快速开发）

### ISSUE THREAD

**Issue by wudiwudidream** [Hex-Dragon/PCL2#4185]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

将PCL的VB代码转换成C/C++代码以便快速开发扩展以便支持自动调整界面的功能，以快速解决（https://github.com/Hex-Dragon/PCL2/pull/4145）问题、扩展等

### 原因

（示例）
我需要这个功能来xxxx。很多人都有xxxx的需求，但如果没有这个功能，就不能xxxx了。

**Comment by allMagicNB** [comment]
@tangge233 是你提议的吗？

**Comment by wudiwudidream** [comment]
他说的

**Comment by wudiwudidream** [comment]
我这边根据他的建议

**Comment by tangge233** [comment]
> @tangge233 是你提议的吗？

和我没关系……

**Comment by wudiwudidream** [comment]
@allMagicNB

**Comment by wudiwudidream** [comment]
是的

**Comment by burningtnt** [comment]
异想天开

**Comment by allMagicNB** [comment]
异想天开

**Comment by allMagicNB** [comment]
这种工程量不亚于重构，你自己再用 C 语言做一个 PCL 吧。

**Comment by LTCatt** [comment]
不会考虑更换开发语言，抱歉

**Comment by wudiwudidream** [comment]
嗯，好吧

**Comment by wudiwudidream** [comment]
@allMagicNB chatgpt不会用？

**Comment by wudiwudidream** [comment]
我在参考联机的那个文档

**Comment by allMagicNB** [comment]
> @allMagicNB chatgpt不会用？

你会用你自己造一个去，不要在这里浪费时间。

**Comment by allMagicNB** [comment]
> 我在参考联机的那个文档

没事咱能等，就是你啥时候重构？

**Comment by JingHai-Lingyun** [comment]
我们能理解您对某个功能的需求之大，但请别急。对于更换开发语言来说，开发者没有时间也没有必要更换。

另 @allMagicNB 请在社区中对待他人友好一点，谢谢。

**Comment by RimacC2-EV** [comment]
XDM有个问题

Microsoft 称 “在 Visual Studio 中单击几下即可将应用从 .NET Framework 升级到最新的 .NET”，
（https://learn.microsoft.com/zh-cn/dotnet/core/porting/upgrade-assistant-overview?WT.mc_id=dotnet-35129-website）。

不知道开发者/贡献者们有没有意愿······

**Comment by LTCatt** [comment]
开发者只需要点一下就能升级 .NET 版本，更新之后突然发现缺失 .NET 打开不了的用户要考虑的就多了.jpg

**Comment by JingHai-Lingyun** [comment]
是这样的... 更高版本的 .Net 意味着使用着旧操作系统的人可能会直接无法使用（.Net 不支持）

**Comment by allMagicNB** [comment]
#2104

**Comment by wudiwudidream** [comment]
@ [allMagicNB](https://github.com/allMagicNB) 在学

**Comment by RimacC2-EV** [comment]
PCL2本体：让我看看新版本程序编译好了没······WC突然猛增几百MB然后还要捆绑这个所谓的 .NET 的玩意？

我：摊上事了.jpg

**Comment by wudiwudidream** [comment]
@LTCatt  NET那个问题得去问虚幻引擎5、微软的官方文档，遇到过，创建文件的时候直接提示缺失：Microsoft 称 “在 Visual Studio 中单击几下即可将应用从 .NET Framework 升级到最新的 .NET”，
半真半假，用C++创建会提示NET 1.0/2.0缺失，最好在修复之前别干

**Comment by allMagicNB** [comment]
不想多说什么，想炸。

**Comment by wudiwudidream** [comment]
@RimacC2-EV 友情提醒，提示.NET请后退一个版本（BUG：会提示缺失NET1.0/2.0）

**Comment by LTCatt** [comment]
基于 @wudiwudidream 在 [#4145](https://github.com/Hex-Dragon/PCL2/pull/4145#issuecomment-2212379994) 警告后依然大量回复实质无意义内容，暂时封禁一个月
