### ISSUE TITLE
自定义局域网联机Mod版本分类错误

### ISSUE THREAD

**Issue by Ad-closeNN** [Hex-Dragon/PCL2#4186]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

Curseforge: https://www.curseforge.com/minecraft/mc-mods/lan-server-properties/files/all?page=1&pageSize=20
自定义局域网联机 Mod本身并不支持1.12以下的版本。可是PCL却错误地把它归类到全版本
![image](https://github.com/Hex-Dragon/PCL2/assets/103355026/93780e9e-65f5-4f90-98a2-5b3d6f45f609)
![image](https://github.com/Hex-Dragon/PCL2/assets/103355026/a96d24e7-91d1-448f-93b3-4458c567b6b5)
![image](https://github.com/Hex-Dragon/PCL2/assets/103355026/d38225a4-3838-441e-8b9f-c6cdefc59728)

### 重现步骤

1、点击下载
2、找到Mod
3、搜索`自定义局域网联机`
4、点进去，发现全部版本支持，但是实际只支持1.12-最新

### 日志与附件

这好像并不用日志吧。。

**Comment by allMagicNB** [comment]
一眼有点像作者的迷惑操作。

**Comment by LTCatt** [comment]
https://www.curseforge.com/minecraft/mc-mods/lan-server-properties/files/5438350
确实怪

**Comment by hejiehao** [comment]
![QQ_1720344238622](https://github.com/Hex-Dragon/PCL2/assets/98140773/e78b255d-090f-4914-9396-c4d40f1e12fa)
[CurseForge API.json](https://github.com/user-attachments/files/16118687/CurseForge.API.json)

**Comment by LTCatt** [comment]
向 CurseForge 提交了反馈：https://support.curseforge.com/en/support/tickets/257778（虽然你们看不了……）
