### ISSUE TITLE
"你知道吗？"中的内容需要进行 XAML 转义

### ISSUE THREAD

**Issue by Language-Changer** [Hex-Dragon/PCL2#4187]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

无论如何更改hints.txt，错误永远在如图所示的位置（行号为3，行位置为107）。

同时错误位置不明确，无法具体确定位置。

---
![image](https://github.com/Hex-Dragon/PCL2/assets/121141095/d1bc68fa-ca9f-4b89-abdd-2eaacf703115)

### 重现步骤

刷新自定义主页（自定义的 你知道吗？）使其出现错误。

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16119172/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16119173/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16119174/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16119175/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16119176/Log5.txt)

**Comment by kong-que-dnf123** [comment]
请问可否上传您的hints.txt文件？
~才不是不想试长度限制呢（~

**Comment by Language-Changer** [comment]
其实就是说我试了好多hints.txt，这是一部分

**Comment by Language-Changer** [comment]
[20:13:11.742] [Control] 按下图标按钮
[20:13:11.742] [Control] 执行自定义事件：刷新主页, /
[20:13:11.742] [Page] 要求强制刷新自定义主页
[20:13:11.742] [Page] 已清空自定义主页缓存
[20:13:11.742] [Page] 主页预设：你知道吗
[20:13:11.743] [Page] 实例化：加载自定义主页 UI 开始，最终内容长度：1143
[20:13:11.745] [Page] 加载失败的自定义主页内容：
<StackPanel xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" xmlns:local="clr-namespace:PCL;assembly=Plain Craft Launcher 2">
                            <local:MyCard Title="你知道吗？" Margin="0,0,0,15">
                                <TextBlock Margin="25,38,23,15" FontSize="13.5" IsHitTestVisible="False" Text="{" TextWrapping="Wrap" Foreground="{DynamicResource ColorBrush1}" />
                                <local:MyIconButton Height="22" Width="22" Margin="9" VerticalAlignment="Top" HorizontalAlignment="Right" 
                                    EventType="刷新主页" EventData="/"
                                    Logo="M875.52 148.48C783.36 56.32 655.36 0 512 0 291.84 0 107.52 138.24 30.72 332.8l122.88 46.08C204.8 230.4 348.16 128 512 128c107.52 0 199.68 40.96 271.36 112.64L640 384h384V0L875.52 148.48zM512 896c-107.52 0-199.68-40.96-271.36-112.64L384 640H0v384l148.48-148.48C240.64 967.68 368.64 1024 512 1024c220.16 0 404.48-138.24 481.28-332.8L870.4 645.12C819.2 793.6 675.84 896 512 896z" />
                            </local:MyCard></StackPanel>
[20:13:11.766] [Control] 普通弹窗：加载自定义主页失败
自定义主页内容编写有误，请根据下列错误信息进行检查：
“规则中的意外标记“None”:“{”中的“MarkupExtension ::= '{' @TYPENAME (Arguments)? '}'”。”，行号为“3”，行位置为“107”。

**Comment by allMagicNB** [comment]
@Language-Changer 发 hints.txt 而不是日志。

**Comment by Language-Changer** [comment]
不出意外的，是“{”出的问题，但是只会出现在行号为“3”，行位置为“107”。
---
[hints1.txt](https://github.com/user-attachments/files/16121439/hints1.txt)
[hints3.txt](https://github.com/user-attachments/files/16121440/hints3.txt)

**Comment by Language-Changer** [comment]
两个文件"{"出现在不同位置

**Comment by allMagicNB** [comment]
不是，哥们你找茬的吧……

**Comment by Language-Changer** [comment]
什么，无意间发现的 : D，一开始只是想找一下为什么会出错（ ：

**Comment by Language-Changer** [comment]
DEC6-885D-BB35-766F 解锁
白嫖一个活跃橙

**Comment by LTCatt** [comment]
你的解锁码：hLxcY6INmP9Q6r47EAdXJQXrwivkTmV4
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by Language-Changer** [comment]
5B4E-6EA0-7E03-3B96 解锁
换了一台电脑，希望重新激活“活跃橙”

**Comment by LTCatt** [comment]
识别码 5B4E-6EA0-7E03-3B96 的土豆码是：【CD11fS%mmFWy%ZDk5hFkie1d5v%93uYHqMzTI1ZeNmSHNanRS4A9rtu6rKoWTCmTGadh3b7FvMhkSjyTc97chwwnbwpp#VGhlbWU5】
在【更多 → 关于与鸣谢 → 输入土豆码】中使用，谢谢支持～
