### ISSUE TITLE
在下载界面无法正常获取

### ISSUE THREAD

**Issue by potatotatoer** [Hex-Dragon/PCL2#4190]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

下载选项都无法正常获取到资源数据，vpn也无法解决，进入游戏也不显示皮肤，然后在群里找到了修复登录办法，下载还是无法正常运作。

### 重现步骤

我不知道是如何触发的，在群里询问过，群员告诉我是pcl抽风了。

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16119490/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16119491/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16119492/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16119493/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16119494/Log5.txt)

**Comment by potatotatoer** [comment]
![屏幕截图(52)](https://github.com/Hex-Dragon/PCL2/assets/113622818/346aeb61-5b0e-4af7-b7c4-3772dac90169)
![屏幕截图(50)](https://github.com/Hex-Dragon/PCL2/assets/113622818/caae6dcd-d9f1-4e95-9212-8d8e9d6b85ca)
![屏幕截图(51)](https://github.com/Hex-Dragon/PCL2/assets/113622818/3c4760d5-87fa-4424-a959-1550c473a7b7)

**Comment by hejiehao** [comment]
似乎是你的网络问题

**Comment by LTCatt** [comment]
网络问题
