### ISSUE TITLE
安装forge报错

### ISSUE THREAD

**Issue by vuuiobo** [Hex-Dragon/PCL2#4192]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

弹框表示类型转换异常

### 重现步骤

1、点击1.8.9版本
2、点击安装forge
3、随便选择一个版本
4、报错

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16119866/Log1.txt)

**Comment by LTCatt** [comment]
都是 `IsOptiFineSuitForForge` 的报错，是 #4183
