### ISSUE TITLE
[Bug] 错误将 MMC 整合包识别为 CurseForge 整合包

### ISSUE THREAD

**Issue by youzi-2333** [Hex-Dragon/PCL2#4194]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

`is:issue (curseforge OR mmc) AND 整合包 `

如题，MMC 整合包被识别为 CurseForge 整合包。见附件。

### 重现步骤

1. 安装整合包

### 日志与附件

[Log2.txt](https://github.com/user-attachments/files/16121524/Log2.txt) 问题位于 Ln79。

[modpack.zip](https://github.com/user-attachments/files/16121554/modpack.zip)

由于文件太大，整合包根目录中的 .minecraft 文件夹被删除。

```
.minecraft\
 | - mods\
   | - xxx.jar
 | - icon.png
```

### 技术信息

`ModModpack.vb` Ln38：

```vb
If Archive.GetEntry("mmc-pack.json") IsNot Nothing Then PackType = 2 : Exit Try 'MMC 整合包
```

提前到 `manifest.json` 的判定前面也许可以修复该问题。

**Comment by zkitefly** [comment]
mmc 导出的整合包有 manifest.json 吗？

就算是检测成 cf 整合包也不会有啥问题呀

hmcl 有这样的情况吗

**Comment by xxtg666** [comment]
根据技术信息和整合包文件来看，MMC 整合包的根目录同时包含 `mmc-pack.json` 和 `manifest.json`，而且先判断的是这一段 `manifest.json` 中不包含 `addons` 节点，确实会误识别为CurseForge整合包
