### ISSUE TITLE
快照版在版本选择中右键删除文件夹会出现两个取消按钮（快照2.8.1）

### ISSUE THREAD

**Issue by BionicTuna40297** [Hex-Dragon/PCL2#4195]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在版本选择中，右键某一文件夹选择删除，弹出的删除警告中会出现两个“取消”选项

### 重现步骤

1、点击版本选择
2、右键文件夹列表中的任意一文件夹
3、选择删除

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16122351/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16122352/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16122353/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16122354/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16122355/Log5.txt)

**Comment by allMagicNB** [comment]
这是刻意的设计。

**Comment by wuliaodexiaoluo** [comment]
这是刻意的设计，为了避免有些人看都不看就按下删除按钮
