### ISSUE TITLE
[Bug] 补全文件时按下取消启动不会取消补全，并概率性导致启动器崩溃

### ISSUE THREAD

**Issue by wuliaodexiaoluo** [Hex-Dragon/PCL2#4196]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### Issues Discussion 暂未发现重复
检索式: is:closed 文件补全/启动器崩溃/闪退/崩溃

补全文件时按下取消启动不会取消补全，并概率性导致启动器崩溃

## 重现步骤

在补全文件 404 前按下取消按钮？（也可能不是这样？

### 整合包链接（直接解压，不要拖入 PCL 安装）
[「MinecraftRPG：最后战线」2019全系列整合-v1.0.0.zip - OneDrive 链接](https://1drv.ms/u/s!Ak9JDqVVP6qzhpF7c2EMgz_Im786bg?e=NBl976)
此链接在 Issue 完成前将尽力保证可用性

[「MinecraftRPG：最后战线」2019全系列整合-v1.0.0.zip - huang1111 网盘链接](https://pan.huang1111.cn/s/5VVgIl)
此网盘可能会出现文件损坏问题，仅建议无代理使用

### PCL 日志:
[PCL 日志.txt](https://github.com/user-attachments/files/16122792/PCL.txt)

**Comment by LTCatt** [comment]
……我测 1.87G，有没有精简点的版本

**Comment by wuliaodexiaoluo** [comment]
> ……我测 1.87G，有没有精简点的版本

这好像是N个版本+服务端叠在一起了来着，并且不是普通的整合包，内部整合包是基于 HMCL 格式+魔改原版客户端
因不清楚删除其他文件、更换版本类型对测试是否有影响，这里分别提供基于原包的删减版(748 M)和单独的重制版(272 M)
~日志内还有出现的补全文件列表为负数，不知道是不是这个的原因~

[[T.E.B.L.]重制版核心客户端[v1.0.4 ].rar - OneDrive 链接](https://1drv.ms/u/s!Ak9JDqVVP6qzhpp5WRC_jLSnSRA-Ew?e=ycfSvC)

[「MinecraftRPG：最后战线」2019全系列整合-v1.0.0.zip -（删减版） OneDrive 链接](https://1drv.ms/u/s!Ak9JDqVVP6qzhpF7c2EMgz_Im786bg?e=lKwcj3)

因为时间缘故其他网盘就不再上传了，有需要@我就行

至于更精简的版本，根据整合包作者的说法因其带有修改客户端的内容，无法提供类似 CurseForge 那样精简的整合包格式

**Comment by LTCatt** [comment]
没复现出来，并且日志里也没看见这是怎么崩溃的……
能稳定复现吗？

**Comment by LTCatt** [comment]
由于无法复现且日志中也没见着是咋崩的暂时关闭。
如果任何人可以复现，请上传日志，并说明一下是咋崩的……
