### ISSUE TITLE
PCL2快照版2.8.1，选择1.18.2forge安装报错！

### ISSUE THREAD

**Issue by MrBaiqwq** [Hex-Dragon/PCL2#4197]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在PCL2最新快照版2.8.1下载1.18.2时，选择安装forge时提示：可视化Optifine安装版本列表出错，从字符串到类型”“Double的转换无效，输入字符串的格式不正确，导致Optfine,forge安装列表为空，概率导致启动器崩溃

### 重现步骤

1.点击“下载”
2选择“自动安装”
3.找到“1.18.2”，点击
4选择“forge”

### 日志与附件

[Log3.txt](https://github.com/user-attachments/files/16126170/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16126171/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16126172/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/16126173/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16126174/Log2.txt)

**Comment by MrBaiqwq** [comment]
> ### 检查项
> * [x]  **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
> * [x]  我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
> * [x]  我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。
> 
> ### 描述
> 在PCL2最新快照版2.8.1下载1.18.2时，选择安装forge时提示：可视化Optifine安装版本列表出错，从字符串到类型”“Double的转换无效，输入字符串的格式不正确，导致Optfine,forge安装列表为空，概率导致启动器崩溃
> 
> ### 重现步骤
> 1.点击“下载” 2选择“自动安装” 3.找到“1.18.2”，点击 4选择“forge”
> 
> ### 日志与附件
> [Log3.txt](https://github.com/user-attachments/files/16126170/Log3.txt) [Log4.txt](https://github.com/user-attachments/files/16126171/Log4.txt) [Log5.txt](https://github.com/user-attachments/files/16126172/Log5.txt) [Log1.txt](https://github.com/user-attachments/files/16126173/Log1.txt) [Log2.txt](https://github.com/user-attachments/files/16126174/Log2.txt)

**Comment by MrBaiqwq** [comment]
补充描述，安装forge可以正常安装，只是安装列表显示空白，安装Optifine报告错误，并且启动器崩溃

**Comment by hejiehao** [comment]
https://github.com/Hex-Dragon/PCL2/issues/4183
