### ISSUE TITLE
主页（生成教学文件的 打开画图）

### ISSUE THREAD

**Issue by WatchfulBand** [Hex-Dragon/PCL2#4201]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

教学文件的 打开画图 仅适用于win11以下（包括win11旧版）win11打开会弹出 无法创建新文档（这一切都是win11画图变成UWP应用造成的）

### 原因

这项优化可以让写主页的人更方便地写主页，建议添加一下（我已经研究出来了）
<local:MyButton Margin="0,4,0,10" Height="35" HorizontalAlignment="Left" Padding="25,0,25,0"
       Text="打开画图" EventType="打开文件" EventData='cmd|/C "explorer shell:AppsFolder\Microsoft.Paint_8wekyb3d8bbwe!App"'

**Comment by WatchfulBand** [comment]
在末尾加上    />   抱歉，少打了

**Comment by wuliaodexiaoluo** [comment]
首先，这应该没啥用，其次，在我的计算机上他只是打开了个文档文件夹而不是 Issue 提到的画图

**Comment by wuliaodexiaoluo** [comment]
这种改法是否会造成在 Windows7、8、8.1、10 无法使用此功能？
<details>
<summary>这段话可能不太友好，介意的话可以不看</summary>
事实上优化建议的目的是为了更多人能够更好的使用 PCL，但现实是 Windows 11 用户比重其实并没有大于以上列出可能出问题的版本的用户总和，如果这项改动会使更多人出问题，龙猫一定会拒掉的。。
</details>

**Comment by Mineshelf-3j6zz0** [comment]
事实上画图PWA在Win11中有系统别名，就是PCL2教程使用的”mspaint.exe“(如下图)
![image](https://github.com/Hex-Dragon/PCL2/assets/112259707/fa95ba44-c624-48bf-b6bd-248f0dc6e63a)

我的电脑上实测输入mspaint可以在新版Win11中打开画图，PCL2中也正常
所以，搞不好是你的问题？

**Comment by wuliaodexiaoluo** [comment]
我觉得不会改成 PWA（UWP 应用）并且全版本通用的可能只有文件资源管理器。但问题是写进去有些地方可能太长了
如果要保证这个按钮继续可用并且不影响美观性的只能是改掉 EventType 的代码，可问题是楼主给的启动代码也不一定能用
这边建议看下应用程序别名配置有没有画图

**Comment by WatchfulBand** [comment]
但是我的Windows在PCL2里面用mspaint.exe就不能打开，必须用cmd调用shell才能打开

**Comment by WatchfulBand** [comment]
![Uploading 屏幕截图 2024-07-08 204221.png…]()

**Comment by WatchfulBand** [comment]
这是我的系统版本
![Uploading 屏幕截图 2024-07-08 202350.png…]()

**Comment by xxtg666** [comment]
我这里也没有问题可以正常打开，似乎是你系统的问题……？看看有没有别人和你一样的

**Comment by wuliaodexiaoluo** [comment]
你的图片没有上传上来，麻烦等 uploading 消失后再发送
另外图片可以合在一起发送，分开发会产生无效邮件，对其他人造成不必要的打扰

**Comment by LTCatt** [comment]
不如换成另一个不会造成这个问题的程序作为示例……？

**Comment by WatchfulBand** [comment]
PCL 识别码

**Comment by WatchfulBand** [comment]
3B93-3D80-E934-5BB5

**Comment by Deep-Dark-Forest** [comment]
> 3B93-3D80-E934-5BB5

抱歉，这是一个 `优化` 反馈，您无法获得活跃橙。
