### ISSUE TITLE
[Bug] 删除背景音乐有概率出错

### ISSUE THREAD

**Issue by youzi-2333** [Hex-Dragon/PCL2#4203]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

`is:issue (清空 OR 删除) AND 音乐 `

删除背景音乐时，有概率出现文件被另一进程占用的问题。

### 重现步骤

1. 开始播放音乐
2. 清空背景音乐
3. 出现错误
4. 再次清空，问题消失

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16130293/Log1.txt)

---

清空背景音乐时，如果出现问题就多重试几次，是否能解决此问题？

**Comment by LTCatt** [comment]
可以在 `ModBase.DeleteDirectory` 加个重试
