### ISSUE TITLE
下载forge时下载失败

### ISSUE THREAD

**Issue by RLlufee** [Hex-Dragon/PCL2#4209]
### 检查项

- [ ] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

下载minecraft1.16.5且forge版本为36.2.42，启动游戏时显示补全文件失败

### 重现步骤

1、下载1.16.5，forge版本36.2.42
2、下载完成后在版本设置中点击补全文件
3，等待

### 日志与附件

[Log2.txt](https://github.com/user-attachments/files/16138604/Log2.txt)

**Comment by allMagicNB** [comment]
#4183
