### ISSUE TITLE
不会正确给出前置

### ISSUE THREAD

**Issue by TjxTangjunxuan** [Hex-Dragon/PCL2#4210]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

当我下载好Ice and fire后启动游戏提示缺少前置citadel模组，但是我在下载Ice and fire时并没有告诉我要下载这个前置

### 重现步骤

1.下载1.20.1forge最新版
2.下载Ice and fire
3.报告出错，Citadel前置丢失
4.返回mod下载界面，并未找到需要下载此前置

还有其他mod也是如此，如下载Cull Leaves时并不会告诉我需要下载Midnightlib前置

### 日志与附件

仅是体验上的bug，对游戏影响不大。但是会有部分体验损失:(

**Comment by allMagicNB** [comment]
截屏

**Comment by TjxTangjunxuan** [comment]
![Uploading 9244417100B8F0ED051E88B539CF2C26.png…]()

**Comment by TjxTangjunxuan** [comment]
![9244417100B8F0ED051E88B539CF2C26](https://github.com/Hex-Dragon/PCL2/assets/129189788/eba01a4a-da61-4ea4-9eb6-8dbc41b1f4a5)

**Comment by allMagicNB** [comment]
你应该骂傻逼作者。

**Comment by JingHai-Lingyun** [comment]
此问题请向 Mod 作者反馈其未正确设置模组平台上的前置项

---

> 你应该骂傻逼作者

请文明一点谢谢

**Comment by allMagicNB** [comment]
> > 你应该骂傻逼作者
> 
> 请文明一点谢谢

不了谢谢
