### ISSUE TITLE
支持下载更多网站上的mod

### ISSUE THREAD

**Issue by WangYiBen0** [Hex-Dragon/PCL2#4211]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

支持下载在其他网站（如Github，现在masa停更，masa全家桶下载真的不方便QwQ）上的mod

~~但是我不知道Github爬虫能不能爬到（~~

### 原因

我需要这个功能来 下载masa全家桶等mod 。很多人都有 下载其他网站上mod 的需求，但如果没有这个功能，就不能 体现PCL II的优越性 了。

**Comment by hejiehao** [comment]
https://github.com/Hex-Dragon/PCL2/issues/2288
