### ISSUE TITLE
当 PCL 中音乐播放设置为 Minecraft 启动后播放时，自动将 Minecraft 中的音乐音量设为 0

### ISSUE THREAD

**Issue by Deep-Dark-Forest** [Hex-Dragon/PCL2#4212]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

当 PCL 中音乐播放设置为 Minecraft 启动后播放时，自动将 Minecraft 中的音乐音量设为 0
这或许可以通过修改 options.txt 实现

### 原因

把 PCL 音乐设置成这个选项的人通常是为了在游戏启动后播放自己想听的音乐，如果没有这个选项游戏自带音乐和 PCL 中播放的音乐会混在一起，每次都需要用户自己手动设置，让操作变得麻烦。

**Comment by Deep-Dark-Forest** [comment]
此issue与#2840不同，#2840是设置启动器音量，此issue是设置Minecraft音量。

**Comment by LTCatt** [comment]
这应该让用户手动设置（反正也不麻烦），自动设置会让很多人懵逼的
