### ISSUE TITLE
安装整合包时错误识别Neoforge版本

### ISSUE THREAD

**Issue by imfine2333** [Hex-Dragon/PCL2#4213]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

安装1.21Neoforge整合包时，错误识别Neoforge版本
（   大概表现为漏掉Beta字样）

### 重现步骤

1、安装版本为1.21的整合包
2、出现错误

### 日志与附件

![屏幕截图 2024-07-09 214437](https://github.com/Hex-Dragon/PCL2/assets/109073573/70dce8f2-ebcc-4123-9243-12e4c842542d)

**Comment by imfine2333** [comment]
已复现整合包：
All the mods 10
BlockFront - Historic Guns & Warfare

**Comment by imfine2333** [comment]
付ATM10的manifest.json(以免被忽略）
[manifest.json](https://github.com/user-attachments/files/16144324/manifest.json)

**Comment by WorldHim** [comment]
#4179
