### ISSUE TITLE
在没有主题功能的开源版本中，试图进行“极客蓝”主题解密主程序会崩溃

### ISSUE THREAD

**Issue by idhaname** [Hex-Dragon/PCL2#4215]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如题，在没有主题功能的开源版本中，试图进行“极客蓝”主题解密时主程序会崩溃
初步判断：由于主题功能被删掉，导致原本应该返回内容的System.Windows.FrameworkElement.ToolTip.get不返回数据

### 重现步骤

1、点击设置-个性化
2、点击“自定义”之前的一个主题（实为“极客蓝”主题）
3、程序崩溃

![QQ截图20240710021503](https://github.com/Hex-Dragon/PCL2/assets/68469786/2e0ac5d2-047d-462f-97bd-bea6e010f26d)
![QQ截图20240710021536](https://github.com/Hex-Dragon/PCL2/assets/68469786/ccdb9fb8-51f7-4ebf-9849-201196089cbb)
![QQ截图20240710021549](https://github.com/Hex-Dragon/PCL2/assets/68469786/bf6510a3-b8ea-4455-b6d0-a321264fed54)

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16147691/Log1.txt)

**Comment by Mxmilu666** [comment]
开源版本本来就是砍了主题的吧...

**Comment by wuliaodexiaoluo** [comment]
```
If LabLauncherTheme11Click.Visibility = Visibility.Collapsed OrElse LabLauncherTheme11Click.ToolTip.ToString.Contains("点击") Then
```
根据调试结果，是这一行代码的问题，但是没办法稳定复现

>开源版本本来就是砍了主题的吧...
如果这段代码和快照版的代码大差不差，那么在开源版出现的问题也一定会出现在快照版上

**Comment by SALTWOOD** [comment]
看龙猫怎么说，如果他觉得是个 bug 我就发 PR

**Comment by Mxmilu666** [comment]
大概看了一下，是因为 ToolTip 为 Nothing 报的 System.NullReferenceException
在快照版中，解锁这个主题需要解锁三个隐藏主题之后才能弹窗
应该是龙猫删了导致的 System.NullReferenceException
所以不可能出现在快照版上
(当然我是 .net 小白如果有什么不对的地方欢迎指出)

**Comment by SALTWOOD** [comment]
Tooltip 为 null，估计龙猫干的，关了罢

**Comment by LTCatt** [comment]
我顺手加个 null 检查吧，倒也不麻烦（
