### ISSUE TITLE
1.8.9的可视化optifine安装版本列表出错

### ISSUE THREAD

**Issue by clacry** [Hex-Dragon/PCL2#4216]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃基本不是 PCL 的原因，请 **不要** 提交反馈。你可以在论坛或社区找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用 HMCL 启动，HMCL 没有出现问题。** 如果 HMCL 也无法启动就不是 PCL 导致的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

这应该是一个新问题，我前一段时间安装的时候没出错，在其他反馈中我看到1.16.1+似乎也有此问题

### PCL 错误报告、日志与附件

出现错误
可视化 OptiFine 安装版本列表出错:从字符串“”到类型“Double”的转换无效。→输入字符串的格式不正确。在PCL,PageDownloadnstall.lsOptiFineSuitForForge(Dl0ptiFineListEntry OptiFineDlForgeVersionEntry Forge)
在PCL.PageDownloadInstall.0ptiFine_Loaded()错误类型:System.FormatException
是否反馈此问题?如果不反馈，这个问题可能永远无法得到解决!

[Log.txt](https://github.com/user-attachments/files/16154508/Log.txt)
[Log1.txt](https://github.com/user-attachments/files/16154509/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16154510/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16154511/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16154513/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16154514/Log5.txt)

**Comment by Pigeon0v0** [comment]
#4183
