### ISSUE TITLE
在检查更新时会重复使用同个缓存，导致不能及时更新

### ISSUE THREAD

**Issue by allMagicNB** [Hex-Dragon/PCL2#4217]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在第一次点击 “检查更新” 后，会从 COS 缓存最新版本号文件，之后再次检查并不会缓存最新版本号文件，而是读取之前的缓存，导致缓存之后 PCL 发布更新无法检测到更新。

### 重现步骤

1. 点击 “检查更新”
2. 等待 PCL 发布新版本
3. 再次点击 “检查更新”，发现提示是最新版本，没有更新提示弹窗

### 日志与附件

[Log3.txt](https://github.com/user-attachments/files/16155248/Log3.txt)

**Comment by allMagicNB** [comment]
@LTCatt

**Comment by Mxmilu666** [comment]
应该是 COS 缓存策略的锅？（

**Comment by JingHai-Lingyun** [comment]
这应该是 COS 缓存时间太久导致的
但如果不用缓存的话流量要爆炸了（
难搞

**Comment by allMagicNB** [comment]
> 这应该是 COS 缓存时间太久导致的
> 但如果不用缓存的话流量要爆炸了（
> 难搞

6 B 能炸？

**Comment by Silverteal** [comment]
原来这是 Bug 啊，我之前就发现了，还以为是防止暴刷的 Feature ……

**Comment by allMagicNB** [comment]
> 这是因为 PCL 只在启动时缓存最新版本信息，而点击“检查更新”时并不会刷新这个缓存，而是从本地的缓存中读取启动时获取的版本信息。

你最好先看看日志。

**Comment by Silverteal** [comment]
> > 这是因为 PCL 只在启动时缓存最新版本信息，而点击“检查更新”时并不会刷新这个缓存，而是从本地的缓存中读取启动时获取的版本信息。
> 
> 你最好先看看日志。

刚刚注意到日志中多次请求了Notice.cfg。那应该是启动器内置有QPS限制导致我上次测试未能发现。  

如果是这样（内置QPS限制）的话。这应该是WAI。
