### ISSUE TITLE
能不能添加一个屏蔽MCr模组的功能（

### ISSUE THREAD

**Issue by baotangJC** [Hex-Dragon/PCL2#4218]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

在下载模组搜索列表添加一个屏蔽MCr模组的功能，或者屏蔽作者也行，有的作者的模组全是MCr做的（
不能弄也没事，就是麻烦了点

### 原因

MCr模组问题太多（

**Comment by Pigeon0v0** [comment]
那要是有人想下呢

**Comment by baotangJC** [comment]
> 那要是有人想下呢

加个可以选择屏蔽或者不屏蔽的按钮（好麻烦）

**Comment by Pigeon0v0** [comment]
为了这个专门制作一个功能，我猜我都不会做.jpg

**Comment by hejiehao** [comment]
> > 那要是有人想下呢
> 
> 加个可以选择屏蔽或者不屏蔽的按钮（好麻烦）

不能因为你不想下载而专门添加一个按钮呀

**Comment by baotangJC** [comment]
不过这个功能也不重要，（毕竟可以自己去看是不是MCr模组
