### ISSUE TITLE
下载forge报错

### ISSUE THREAD

**Issue by 2448856886** [Hex-Dragon/PCL2#4222]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

安装forge时弹窗报错

### 重现步骤

1、点击自动安装
2、往下滚，然后点击forge

### 日志与附件

[Log.txt](https://github.com/user-attachments/files/16172270/Log.txt)
[Log1.txt](https://github.com/user-attachments/files/16172272/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16172274/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16172275/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16172276/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16172277/Log5.txt)

**Comment by kong-que-dnf123** [comment]
疑似 #4183 
```
[14:15:52.187] 可视化 OptiFine 安装版本列表出错：从字符串“”到类型“Double”的转换无效。
→ 输入字符串的格式不正确。
   在 Microsoft.VisualBasic.CompilerServices.Conversions.ToDouble(String Value, NumberFormatInfo NumberFormat)
   在 PCL.PageDownloadInstall.IsOptiFineSuitForForge(DlOptiFineListEntry OptiFine, DlForgeVersionEntry Forge)
   在 PCL.PageDownloadInstall.OptiFine_Loaded()
   在 Microsoft.VisualBasic.CompilerServices.Conversions.ParseDouble(String Value, NumberFormatInfo NumberFormat)
   在 Microsoft.VisualBasic.CompilerServices.Conversions.ToDouble(String Value, NumberFormatInfo NumberFormat)
错误类型：System.FormatException
[14:15:52.204] [Control] 普通弹窗：出现错误
可视化 OptiFine 安装版本列表出错：从字符串“”到类型“Double”的转换无效。
→ 输入字符串的格式不正确。
   在 PCL.PageDownloadInstall.IsOptiFineSuitForForge(DlOptiFineListEntry OptiFine, DlForgeVersionEntry Forge)
   在 PCL.PageDownloadInstall.OptiFine_Loaded()
错误类型：System.FormatException

```
