### ISSUE TITLE
旧版启动器自动消失，下载新版启动器无法识别原有存档、模组和光影等原先下载的东西

### ISSUE THREAD

**Issue by killa0132** [Hex-Dragon/PCL2#4223]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

原先的启动器不知道什么时候就自己消失了，但存档和配置文件一类的都还在，就只是没了个启动器而已。于是我在一周前重新下载了一个启动器，安装位置还是在同一个位置，但打开后发现无法识别到原先的.minecraft文件夹而重新生成l了一个.minecraft文件夹，自己便重新于“版本选择”中导入先前那个文件夹，导入后标题界面等显示正常，但实际打开后无法识别各个版本存档中的地图、模组和光影。有尝试过重启，转移存档等方法，均无效果。
![QQ图片20240711153751](https://github.com/Hex-Dragon/PCL2/assets/155339997/5163a2e1-2879-45c9-8b31-f52ff3671196)
![QQ图片20240711154201](https://github.com/Hex-Dragon/PCL2/assets/155339997/328fa1ad-eab6-4b06-a344-67a16a887fa1)
![QQ图片20240711154340](https://github.com/Hex-Dragon/PCL2/assets/155339997/d6a2b33b-4415-460f-83b9-0d9ddd3a6d7e)
![QQ图片20240711153803](https://github.com/Hex-Dragon/PCL2/assets/155339997/4bb4fb29-12a8-452b-8877-3b72bca32c49)
![QQ图片20240711153808](https://github.com/Hex-Dragon/PCL2/assets/155339997/4a8fc7fe-e0e6-4e80-b802-081cc4de80c9)

### 重现步骤

触发条件未知（真的，突然就这样了）

### 日志与附件

这是旧版留下的日志：
[Log1.txt](https://github.com/user-attachments/files/16173093/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16173095/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16173096/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16173098/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16173100/Log5.txt)
这是新版的日志：
[Log3.txt](https://github.com/user-attachments/files/16173107/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16173109/Log4.txt)
[Log1.txt](https://github.com/user-attachments/files/16173110/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16173111/Log2.txt)

**Comment by Pigeon0v0** [comment]
前往启动器设置，设置版本隔离为「隔离所有版本」

**Comment by Pigeon0v0** [comment]
补充：启动器消失问题见#666
