### ISSUE TITLE
在能够正常刷新正版皮肤的情况下，游戏内无法显示正版皮肤，请求帮助

### ISSUE THREAD

**Issue by freecube0209** [Hex-Dragon/PCL2#4226]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如题。在能够正常刷新正版皮肤的情况下，游戏内无法显示正版皮肤。考虑到可能是加载延迟，已经做了适当等待，不过无效。
已经尝试访问其他issues中提供的textures.minecraft.net和api.mojang.com相关网址进行测试，均可正常访问、下载。
已经确认过正版mojang网站上的皮肤设置正常。
可能有用的其他信息：网络环境方面，使用了Steamcommunity 302 ver. 12.1.38 工具中的我的世界api/官网修复功能。

### 重现步骤

1、点击PCL2启动器“皮肤与披风”-“刷新头像”
2、启动器显示正常刷新。进入任意版本的游戏（实验版本号：1.20.1）
3、创建或加载世界。发现为默认官方皮肤。

### 日志与附件

似乎无法正常上传txt文件。
我不清楚是我的Chrome浏览器问题还是别的什么GitHub问题，或者是我的操作问题。
总之，我把log文件传在这里了。如果获取不方便可以再和我说。
链接：https://pan.baidu.com/s/1XgY42orHMCmw1-epqbrjvg 
提取码：csti

**Comment by allMagicNB** [comment]
别用 Steamcommunity 302。

**Comment by Pigeon0v0** [comment]
是否安装了 Mod？

**Comment by freecube0209** [comment]
> 别用 Steamcommunity 302。

请详细说说？

**Comment by freecube0209** [comment]
> 是否安装了 Mod？

mod环境和原版环境都测试过了。都没有效果。

**Comment by allMagicNB** [comment]
Steamcommunity 302 是使用更改 hosts 文件进行代理的，一旦非正常关闭，hosts 可能会没改回来。

**Comment by freecube0209** [comment]
> Steamcommunity 302 是使用更改 hosts 文件进行代理的，一旦非正常关闭，hosts 可能会没改回来。

明白了，谢谢。我会留意host检查，另外有替代软件的话会进行替代。

**Comment by hejiehao** [comment]
这有可能是你的 Java 不信任 Steamcommunity 302 的证书导致的

**Comment by LTCatt** [comment]
与启动器无关（

**Comment by freecube0209** [comment]
> 这有可能是你的 Java 不信任 Steamcommunity 302 的证书导致的，请关闭 Steamcommunity 302 或者是将证书导入 Java `<Java 路径>\bin\keytool.exe -import -keystore <Java 路径>\lib\security\cacerts -storepass changeit -keypass changeit -file <证书路径>` ~如果你使用 Oracle Java 这个命令是没用的~

非常感谢！问题已解决！

**Comment by freecube0209** [comment]
> 与启动器无关（

已通过实验证实是Java不信任Steamcommunity302的证书导致。谢谢！

**Comment by freecube0209** [comment]
> > 这有可能是你的 Java 不信任 Steamcommunity 302 的证书导致的，请关闭 Steamcommunity 302 或者是将证书导入 Java `<Java 路径>\bin\keytool.exe -import -keystore <Java 路径>\lib\security\cacerts -storepass changeit -keypass changeit -file <证书路径>` ~如果你使用 Oracle Java 这个命令是没用的~
> 
> 非常感谢！问题已解决！

补充：经实验，关闭Steamcommunity 302 为稳妥解决方法。导入证书仍然可能会有奇怪的问题触发。
