### ISSUE TITLE
在回收站里直接拖放.jar文件来安装会 改变Mod名/无法安装Mod

### ISSUE THREAD

**Issue by Ad-closeNN** [Hex-Dragon/PCL2#4227]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

从回收站里找到删除过的`.jar.disabled`(`.jar`)文件，打开PCL的Mod管理，将jar.disabled(.jar)文件拖进PCL会发现已安装，但是实际上并没有安装上这个文件，而是直接将文件名改为`xxx.disabled`(`xxx.jar`)
这样会被改名+已关闭的mod这样做需要手动去mods里面改为xxx.jar.disabled
![image](https://github.com/Hex-Dragon/PCL2/assets/103355026/ce207084-8edd-48e7-bd4e-1aadbbef5626)
![image](https://github.com/Hex-Dragon/PCL2/assets/103355026/5f4f754e-ae80-4c6c-b33f-3797fd29946b)
![image](https://github.com/Hex-Dragon/PCL2/assets/103355026/ef4e1ba1-56f9-4282-9086-050c5775ed9a)

### 重现步骤

1、点击版本设置
2、然后点击Mod管理
3、随便选一个Mod，将其关闭并删除
4、打开回收站
5、将刚刚删除的Mod重新直接在回收站内拖回PCL
6、如果是关闭+删除了的话，发现并没有安装上，但是提示安装成功，在Mod管理里面根本找不到这个删掉的Mod（因为早就被改为xxx.disabled而不是xxx.jar.disabled）
6.1、如果是没关闭就删掉了的话，PCL会将其安装，并能正常显示和使用，但是Mod文件名（在资源管理器里面看的）会被改变

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16176048/Log1.txt)

**Comment by Mineshelf-3j6zz0** [comment]
从另外一个角度考虑，谁一般从回收站里给程序喂文件啊(

**Comment by lactobionicAcid** [comment]
引申bug：任何*.disabled文件都可以被拖放安装，即使不是模组文件

**Comment by Deep-Dark-Forest** [comment]
> 引申bug：任何*.disabled文件都可以被拖放安装，即使不是模组文件

`.disabled` 理论上算模组文件，只不过是被 PCL 禁用的

**Comment by SALTWOOD** [comment]
Windows的设定。会在你把文件拉入回收站时，将文件重命名，并且新建一个名字相似的文件来保存文件删除前的信息（例如文件原本的名字、大小等数据）

**Comment by Ad-closeNN** [comment]
那么现在只需解决无法识别的问题了

**Comment by LTCatt** [comment]
.net 下读取回收站的文件名只能依赖 Shell32 dll，而 PCL 目前没有引用这个文件，我觉得为了修这个 bug 去添加一个 dll 到程序体又麻烦又不太值得……
所以做了半个修复，如果拖拽安装 mod，PCL 会自动启用它，并且如果没有后缀名会为它自动添加 .jar……

**Comment by Ad-closeNN** [comment]
换了个新的硬盘，装了个全新的Win11
麻烦再给一下主题...谢啦
BCD8-51B2-3D97-1002

**Comment by LTCatt** [comment]
你的解锁码：DtoBnn9uDoPdZYhGyYXqtqFfduq0O71R
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by LTCatt** [comment]
现已禁止从回收站拖拽安装 Mod 文件，这样做的时候会提示将文件还原
