### ISSUE TITLE
可视化 Optifine 安装版本列表出错: 从字符串""到类型"Double"的转换无效

### ISSUE THREAD

**Issue by HOPE-LGNF** [Hex-Dragon/PCL2#4229]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在"自动安装"->"选择版本"-> 点击 1.20.x>版本>1.8.x 的版本->"forge"中进行选择会出现错误窗口,点击取消的话会出现更严重的事故(出现《锟斤拷烫烫烫》界面后启动器崩溃)
在1.20.x以上和1.8.x以下的版本反而没有此问题
![image](https://github.com/Hex-Dragon/PCL2/assets/159258343/833b24c6-cc13-46ba-8759-c8fa6cac3917)
![image](https://github.com/Hex-Dragon/PCL2/assets/159258343/e4a9ecf3-1a18-4291-91da-9b5a1622fe3f)

### 重现步骤

1、点击下载->自动安装
2、往下滚，然后点击1.20.x>版本>1.8.x的版本
3 进入安装界面后打开forge下拉栏
4 任意点击一个forge版本(未经过全面性测试,我点击的是最新版和任意一个版本)
5 出现错误

### 日志与附件

[Log.txt](https://github.com/user-attachments/files/16177420/Log.txt)
[Log1.txt](https://github.com/user-attachments/files/16177421/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16177423/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16177424/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16177425/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16177426/Log5.txt)

**Comment by Pigeon0v0** [comment]
#4183
