### ISSUE TITLE
自动安装中下载1.17.1 ;1.18.1 ;1.19.1选择安装forge时报错

### ISSUE THREAD

**Issue by Northconch** [Hex-Dragon/PCL2#4230]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

下载-自动安装中，选择1.17.1 ;1.18.1 ;1.19.1版本后选择安装forge后出现错误，错误描述如图。
尝试安装1.20.1选择forge不会报错
![7d528d42201916d6d9c072045cb5ad4e](https://github.com/Hex-Dragon/PCL2/assets/85122132/6f15bc7b-310a-43d5-a126-79ee17201e49)

### 重现步骤

1、点击下载，选择自动安装
2、在正式版中选择1.17.1
3、点击Forge，选择推荐版

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16177939/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16177940/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16177941/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16177943/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16177944/Log5.txt)

**Comment by allMagicNB** [comment]
#4183

**Comment by Deep-Dark-Forest** [comment]
#4183？
