### ISSUE TITLE
多开MC时崩溃查看日志优化

### ISSUE THREAD

**Issue by HomoobyDX** [Hex-Dragon/PCL2#4232]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

我开了3个MC，其中一个崩溃后，PCL弹minecraft出现错误，这都正常，但是我点查看日志却是我最后一个启动游戏的日志，而不是崩溃游戏的日志
虽然不知道什么原因导致的，比如我开3个MC时如果是第一个或者第二个崩了，点查看日志显示的是第三个MC的日志
下面是PCL的日志：
[Log1.txt](https://github.com/user-attachments/files/16184088/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16184117/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16184118/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16184119/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16184120/Log5.txt)

### 原因

崩溃弹出页面查看日志有误，在不想导出错误报告的情况下想直接点查看日志但是日志却是其他游戏的

**Comment by LTCatt** [comment]
PCL 无法分辨日志文件到底是哪个 MC 输出的，这个没办法 orz

**Comment by HomoobyDX** [comment]
我先设游戏A和游戏B（两个游戏的游戏文件夹不在一起）
PCL启动了游戏A以后，再在启动器-版本设置-打开游戏B的游戏文件夹，结果打开的内容是文档而不是游戏B的游戏文件夹，这能算bug吗，日志如下
[Log1.txt](https://github.com/user-attachments/files/16268099/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16268101/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16268102/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16268104/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16268107/Log5.txt)

**Comment by hejiehao** [comment]
这应该是 explorer.exe 的问题

**Comment by hejiehao** [comment]
PCL 获取到的路径好像有点问题

**Comment by HomoobyDX** [comment]
> 我先设游戏A和游戏B（两个游戏的游戏文件夹不在一起） PCL启动了游戏A以后，再在启动器-版本设置-打开游戏B的游戏文件夹，结果打开的内容是文档而不是游戏B的游戏文件夹，这能算bug吗，日志如下 [Log1.txt](https://github.com/user-attachments/files/16268099/Log1.txt) [Log2.txt](https://github.com/user-attachments/files/16268101/Log2.txt) [Log3.txt](https://github.com/user-attachments/files/16268102/Log3.txt) [Log4.txt](https://github.com/user-attachments/files/16268104/Log4.txt) [Log5.txt](https://github.com/user-attachments/files/16268107/Log5.txt)

问题找到了，是PCL获取路径时的斜杠存在两个，系统会重定向到一个其他的目录，我在注册表值LaunchFolders把斜杠去掉一个后恢复正常，可能无法复现

**Comment by LTCatt** [comment]
`[Launch] Minecraft 文件夹：F:\\MC\\服务器游玩\\[Java8]星辰计划-北境MC\\.minecraft\\`
这个 MC 文件夹是怎么被添加进去的？
这是一个 bug，可以新开一个 issue

**Comment by HomoobyDX** [comment]
我想先提一个问题，就是把注册表reg后缀改成txt后，里面显示LaunchFolders的内容是双斜杠吗
