### ISSUE TITLE
System.10.FileNotFoundException

### ISSUE THREAD

**Issue by jewel0723** [Hex-Dragon/PCL2#4236]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃基本不是 PCL 的原因，请 **不要** 提交反馈。你可以在论坛或社区找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用 HMCL 启动，HMCL 没有出现问题。** 如果 HMCL 也无法启动就不是 PCL 导致的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

Minecraft 启动失败:获取启动参数失败
→>释放 Java Wrapper 失败
在PCL.ModLaunch.McLaunchStart(LoaderTask`2 Loader)
在PCL.ModLaunch.ExtractJavaWrapper()
在PCL.ModLaunch.McLaunchArgumentsJvmNew(McVersion Version)
在PCL.ModLaunch.McLaunchArgumentMain(LoaderTask`2 Loader)
在PCL.ModLoaderLoaderTask`2.Closure$ 13-0.Lambda$ 0()
错误类型:System.10.FileNotFoundException

### PCL 错误报告、日志与附件

[Log1.txt](https://github.com/user-attachments/files/16189552/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16189553/Log2.txt)

### HMCL 启动脚本

![Uploading 0845ADDC00A5952A8B299BE8CC01CE50.png…]()

**Comment by hejiehao** [comment]
尝试使用管理员身份运行 PCL 后再启动

**Comment by jewel0723** [comment]
ok了


春性
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Hex-Dragon/PCL2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月12日(星期五) 下午2:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Hex-Dragon/PCL2] System.10.FileNotFoundException (Issue #4236)





 
尝试使用管理员身份运行 PCL 后再启动
