### ISSUE TITLE
启动器不能及时取消游戏

### ISSUE THREAD

**Issue by sdfsd-bsdf** [Hex-Dragon/PCL2#4237]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

启动游戏后，马上点击取消，有时可以成功取消游戏，但有时不能及时取消游戏，游戏任然会在后台运行。

### 重现步骤

1、点击启动
2、然后点击取消

### 日志与附件

[Log.txt](https://github.com/user-attachments/files/16190156/Log.txt)
[Log1.txt](https://github.com/user-attachments/files/16190159/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16190161/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16190162/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16190163/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16190164/Log5.txt)

**Comment by Pigeon0v0** [comment]
#2842

**Comment by sdfsd-bsdf** [comment]
可以激活一下我的pcl2启动器活力橙的外观吗？
识别码：59D1-5719-5DA1-0E9A
________________________________
发件人: Pigeon0v0 ***@***.***>
发送时间: 2024年7月12日 15:32
收件人: Hex-Dragon/PCL2 ***@***.***>
抄送: sdfsd-bsdf ***@***.***>; Author ***@***.***>
主题: Re: [Hex-Dragon/PCL2] 启动器不能及时取消游戏 (Issue #4237)


Closed #4237<https://github.com/Hex-Dragon/PCL2/issues/4237> as not planned.

―

**Comment by hejiehao** [comment]
> 可以激活一下我的pcl2启动器活力橙的外观吗？
识别码：59D1-5719-5DA1-0E9A

需要标记为完成才可以获取活力橙
