### ISSUE TITLE
自动检索该版本mod是否有更新

### ISSUE THREAD

**Issue by lieyanxd** [Hex-Dragon/PCL2#4238]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在启动游戏时自动检索安装的mod是否有更新（当然在设置里可以手动关掉）
很像Windows更新……
如果有更新，爬取mod新版本的明细，再让用户作出是否更新的选择

### 原因

有些mod在测试阶段存在bug，这样能方便mod的优化。

**Comment by Deep-Dark-Forest** [comment]
#102？

**Comment by Pigeon0v0** [comment]
适用面太小...

**Comment by LTCatt** [comment]
更新 mod 本来就是不推荐的操作，特别是整合包，所以暂不考虑……
