### ISSUE TITLE
应用自定义XAML后拉伸窗口导致"执行动画失败"

### ISSUE THREAD

**Issue by WHITECN2009** [Hex-Dragon/PCL2#4240]
### 检查项

- [ ] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

https://github.com/user-attachments/assets/2e0034f4-8b89-458c-80e5-a61c2bbb6073

↑触发演示视频↑
报错为"执行动画失败：Code | 31/1(0%)：未设置对象变量或 With 块变量"
补充自https://github.com/Hex-Dragon/PCL2/issues/4003
(这条issue的触发条件由[#4003](https://github.com/Hex-Dragon/PCL2/issues/4003)声明的"属性冲突的卡片"变更为任意XAML文件)

### 重现步骤

1.应用任意非预设的XAML自定义文件
2.拉伸窗口

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16195714/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16195717/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16195718/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16195720/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16195722/Log5.txt)
[Custom.txt](https://github.com/user-attachments/files/16195724/Custom.txt)

**Comment by WHITECN2009** [comment]
查了 https://github.com/Hex-Dragon/PCL2/issues/4003 提交过一次 但是他那个有前提 这次真是无意间发现的(

**Comment by LTCatt** [comment]
你定义了 CanSwap=false, IsSwaped = true
也就是这个卡片不允许折叠，但默认处于折叠状态……
这能对头才怪喂（

**Comment by WHITECN2009** [comment]
口阝可？
我这么瞎的吗(
打扰了对不起(
