### ISSUE TITLE
获取启动参数失败：释放 Java Wrapper 失败

### ISSUE THREAD

**Issue by clang3722** [Hex-Dragon/PCL2#4243]
### 检查项

- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![QQ_1720824482211](https://github.com/user-attachments/assets/1bf9cbf2-c369-4c0f-ac6f-557b6543f6c8)
昨天玩还是好好的，昨天晚上一启动就这样了，Java重新下载过新的22，也换过Java，甚至删除pcl配置文件夹和更换pcl主体，实在不知道该怎么办了（弱弱的提一句，hmcl可以启动游戏）

### 重现步骤

1、点击启动游戏
2、出现问题

### 日志与附件

[Log3.txt](https://github.com/user-attachments/files/16199852/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16199853/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16199854/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/16199855/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16199856/Log2.txt)

**Comment by clang3722** [comment]
启动参数我删除过没用

**Comment by allMagicNB** [comment]
右键以管理员身份运行，再重置下启动参数试试？

**Comment by clang3722** [comment]
> 右键以管理员身份运行，再重置下启动参数试试？

还是一样的

**Comment by LTCatt** [comment]
**缓解方式：**如果遇到此 bug，请尝试右键以管理员身份启动 PCL

**Comment by clang3722** [comment]
> **缓解方式：** 如果遇到此 bug，请尝试右键以管理员身份启动 PCL。 如果还是不行，我也不知道咋回事.jpg ![image](https://private-user-images.githubusercontent.com/40348278/348451001-16a4cd8e-61b1-44b7-b94d-556d90d01ebf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NDg4MzYsIm5iZiI6MTcyMDg0ODUzNiwicGF0aCI6Ii80MDM0ODI3OC8zNDg0NTEwMDEtMTZhNGNkOGUtNjFiMS00NGI3LWI5NGQtNTU2ZDkwZDAxZWJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDA1Mjg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiOWFjNGQ1ZGFiNjg3NzRhYmY0YzBiNzdmYjhmZmQ5MmNhMDc2YWJmZTYxZTA5MDNlMmNlMDRkOTBkYjE0OTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Im5h5RkAG19geAUCHpSw8c6Sz-o98vokR4DeRyBudD4)

好的，还是不行，但是可喜的是，隔壁bakaxl也启动不了，只有hmcl能启动(无论什么版本)

**Comment by LTCatt** [comment]
看起来就是单纯的没有权限释放文件，但我也不知道为啥突然就没权限了……
虽然 2.8.2 添加了释放失败的报错，不过如果之前 JLW 一直就没释放出来，只是不报错的话，也应该启动失败才对？

需要一个能复现的人在 QQ 上确认，如果能复现在这里发一下 QQ……

**Comment by clang3722** [comment]
> 看起来就是单纯的没有权限释放文件，但我也不知道为啥突然就没权限了…… 虽然 2.8.2 添加了释放失败的报错，不过如果之前 JLW 一直就没释放出来，只是不报错的话，也应该启动失败才对？
> 
> 需要一个能复现的人在 QQ 上确认，如果能复现在这里发一下 QQ……

我可以给你远控复现

**Comment by LTCatt** [comment]
QQ 1043137532 加一下我（

**Comment by LTCatt** [comment]
调查结果非常诡异……
提交者的电脑上已经存在 2023/7/11 版本的 JavaWrapper.jar，但 PCL 对那个 JavaWrapper.jar 却只有读取权限，没有写入权限，并且那个文件 **不知道为什么具有隐藏和只读属性** 。
![image](https://github.com/user-attachments/assets/db97fbdc-2738-45fe-ad57-f08c04df42d2)
![image](https://github.com/user-attachments/assets/ca136541-e323-4694-956e-3b06194901d5)
提交者手动删除该 JavaWrapper.jar 后，PCL 能够正常写入新版的 JavaWrapper.jar。

**Comment by LTCatt** [comment]
目前不知道为什么许多人的电脑上的这个文件都变成了只读隐藏文件，但 PCL 似乎虽然不能写入但可以删除它，目前的修复方式是……如果写入失败就把它删了重试，如果还失败就换个文件名，这样就不用覆盖了……这应当可以解决该问题，虽然不知道为什么。

**Comment by LTCatt** [comment]
目前的缓解方式：
1. 使用管理员权限启动
2. 在文件管理器中输入 `%APPDATA%\PCL` ，回车，然后删除其中的 JavaWrapper.jar 文件
![image](https://github.com/user-attachments/assets/a5aea466-5160-4978-91c8-f96b946a6182)

**Comment by allMagicNB** [comment]
> 2. 在文件管理器中输入 `%APPDATA%\PCL` ，回车，然后删除其中的 JavaWrapper.jar 文件
> ![image](https://github.com/user-attachments/assets/a5aea466-5160-4978-91c8-f96b946a6182)

或者懒人指令（Win + R 输入如下内容然后回车）：
```shell
del /f %APPDATA%\PCL\JavaWrapper.jar
```
