### ISSUE TITLE
PCL2无法启动

### ISSUE THREAD

**Issue by bqdbm** [Hex-Dragon/PCL2#4244]
### 检查项

- [ ] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

点击启动游戏后报错

### 重现步骤

1、点击启动游戏

### 日志与附件

详细错误信息：
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   在 PCL.ModBase.WriteFile(String FilePath, Byte[] Content, Boolean Append)
错误类型：System.UnauthorizedAccessException
[08:41:43.330] 加载线程 获取启动参数 (38) 发生运行时错误：释放 Java Wrapper 失败
   在 PCL.ModLaunch.ExtractJavaWrapper()
   在 PCL.ModLaunch.McLaunchArgumentsJvmNew(McVersion Version)
   在 PCL.ModLaunch.McLaunchArgumentMain(LoaderTask`2 Loader)
   在 PCL.ModLoader.LoaderTask`2._Closure$__13-0._Lambda$__0()
错误类型：System.IO.FileNotFoundException
[08:41:43.330] [Loader] 加载器 获取启动参数 状态改变：Failed
[08:41:43.330] [Loader] 加载器 Minecraft 启动 状态改变：Failed
[08:41:43.345] [Taskbar] Minecraft 启动 已移出任务列表
[08:41:43.361] [Launch] 错误：获取启动参数失败
→ 释放 Java Wrapper 失败
   在 PCL.ModLaunch.McLaunchStart(LoaderTask`2 Loader)
   在 PCL.ModLaunch.ExtractJavaWrapper()
   在 PCL.ModLaunch.McLaunchArgumentsJvmNew(McVersion Version)
   在 PCL.ModLaunch.McLaunchArgumentMain(LoaderTask`2 Loader)
   在 PCL.ModLoader.LoaderTask`2._Closure$__13-0._Lambda$__0()
错误类型：System.IO.FileNotFoundException
[08:41:43.361] Minecraft 启动失败：获取启动参数失败
→ 释放 Java Wrapper 失败
   在 PCL.ModLaunch.McLaunchStart(LoaderTask`2 Loader)
   在 PCL.ModLaunch.ExtractJavaWrapper()
   在 PCL.ModLaunch.McLaunchArgumentsJvmNew(McVersion Version)
   在 PCL.ModLaunch.McLaunchArgumentMain(LoaderTask`2 Loader)
   在 PCL.ModLoader.LoaderTask`2._Closure$__13-0._Lambda$__0()
错误类型：System.IO.FileNotFoundException
[08:41:43.361] 加载线程 Loader Launch (8) 发生运行时错误：获取启动参数失败
→ 释放 Java Wrapper 失败
   在 PCL.ModLaunch.McLaunchStart(LoaderTask`2 Loader)
   在 PCL.ModLoader.LoaderTask`2._Closure$__13-0._Lambda$__0()
   在 PCL.ModLaunch.ExtractJavaWrapper()
   在 PCL.ModLaunch.McLaunchArgumentsJvmNew(McVersion Version)
   在 PCL.ModLaunch.McLaunchArgumentMain(LoaderTask`2 Loader)
   在 PCL.ModLoader.LoaderTask`2._Closure$__13-0._Lambda$__0()
错误类型：System.IO.FileNotFoundException
[08:41:43.361] [Loader] 加载器 Loader Launch 状态改变：Failed
[08:41:43.408] [Control] 普通弹窗：启动失败
Minecraft 启动失败：获取启动参数失败
→ 释放 Java Wrapper 失败
   在 PCL.ModLaunch.McLaunchStart(LoaderTask`2 Loader)
   在 PCL.ModLaunch.ExtractJavaWrapper()
   在 PCL.ModLaunch.McLaunchArgumentsJvmNew(McVersion Version)
   在 PCL.ModLaunch.McLaunchArgumentMain(LoaderTask`2 Loader)
   在 PCL.ModLoader.LoaderTask`2._Closure$__13-0._Lambda$__0()
错误类型：System.IO.FileNotFoundException

**Comment by Ad-closeNN** [comment]
#4243
