### ISSUE TITLE
MMC整合包安装失败：不支持给定路径的格式

### ISSUE THREAD

**Issue by w2w2e2wq** [Hex-Dragon/PCL2#4248]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

整合包安装出现错误

### 重现步骤

1、将[整合包文件](https://www.123pan.com/s/vYf9-bljwv.html)拖至启动器
2、在使用默认版本名(1.20.4)后点击确定
3、错误出现

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16202153/Log1.txt)

**Comment by hejiehao** [comment]
似乎是压缩包里面有中文导致的

**Comment by hejiehao** [comment]
![QQ_1720875376204](https://github.com/user-attachments/assets/a2bf12a3-541c-459b-b0b4-bd818ef630f0)
有冒好

**Comment by LTCatt** [comment]
请向整合包作者反馈
