### ISSUE TITLE
增加同类模组附属包下载

### ISSUE THREAD

**Issue by frlbluespace** [Hex-Dragon/PCL2#4249]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

一键下载模组的附属包，比如模组扩展和优化模组的模组，另外支持下载zip类附属包，一个个找属实麻烦

### 原因

我需要这个功能来安装tacz枪包。但如果没有这个功能，就不能在短时间内找到它们了。

**Comment by youzi-2333** [comment]
总感觉有重复，但是搜不到…… `is:issue (附属 OR 优化) AND (mod OR 模组) AND 下载 `

**Comment by WForst-Breeze** [comment]
#953
