### ISSUE TITLE
在forge官网下载了forge的exe后下载forge后游戏启动不了了

### ISSUE THREAD

**Issue by BZDTS** [Hex-Dragon/PCL2#425]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

启动游戏启动不了

### 重现步骤

1、点击启动刚刚下载的1.19.2+forge
2、显示出错

### 日志与附件

[latest.log](https://github.com/Hex-Dragon/PCL2/files/10055083/latest.log)
[debug.log](https://github.com/Hex-Dragon/PCL2/files/10055084/debug.log)
[游戏崩溃前的输出.txt](https://github.com/Hex-Dragon/PCL2/files/10055160/default.txt)
《我连log1都没有》

**Comment by LTCatt** [comment]
补充上传：版本文件夹、Log1

**Comment by bwtx2022** [comment]
版本文件夹可在 PCL2 的版本设置中打开

Log1 位于 PCL 文件夹内

**Comment by DogEggWang** [comment]
遇到同样的问题，已经是最新版启动器。
通过启动器下载1.19.2Forge并安装（推荐版43.1.7和最新版43.1.57均尝试过），安装成功，启动失败。

[错误报告-2022-11-25_21.23.14.zip](https://github.com/Hex-Dragon/PCL2/files/10093073/-2022-11-25_21.23.14.zip)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10093078/Log1.txt)
[1.19.2-forge-43.1.7.zip](https://github.com/Hex-Dragon/PCL2/files/10093099/1.19.2-forge-43.1.7.zip)

**Comment by LTCatt** [comment]
@DogEggWang 你的这个是 #353 导致的
