### ISSUE TITLE
Mod和整合包下载的搜索选项”重置条件“

### ISSUE THREAD

**Issue by ArgonTeam** [Hex-Dragon/PCL2#4251]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在点击”重置条件“按钮时应当加载所有的mod或整合包列表，而不是仅清除”名称“”来源“”版本“”类型“里的选项。

### 原因

![屏幕截图 2024-07-14 133010](https://github.com/user-attachments/assets/afd8fa7a-bbdb-40ba-a07e-d07247025fb7)

这项优化让我可以更方便地重置条件。
如果没有这项优化，我每次都必须再次点击”搜索“，让操作变得很麻烦。

**Comment by allMagicNB** [comment]
一般情况下，重置条件之后是要输入新的条件再搜索的，而不是直接搜索。
如果重置条件后直接搜索，那么不仅这次搜索没有意义，还会浪费龙猫的 API Key 的请求次数。

**Comment by ArgonTeam** [comment]
你说的对，emmm
或许可以做一个按钮，用于返回原先已经加载的mod/整合包下载页面，而不是重新请求mod/整合包列表，浪费api key

**Comment by ArgonTeam** [comment]
> 你说的对，emmm 或许可以做一个按钮，用于返回原先已经加载的mod/整合包下载页面，而不是重新请求mod/整合包列表，浪费api key

这样能减少api key的开销，也能方便用户。

**Comment by allMagicNB** [comment]
热知识，只要是 CurseForge 上的 Mod，查询 Mod 信息也会消耗 API Key 的使用次数。

**Comment by ArgonTeam** [comment]
> 热知识，只要是 CurseForge 上的 Mod，查询 Mod 信息也会消耗 API Key 的使用次数。

我指的是返回已经加载的列表，而不是重新查询。

**Comment by ArgonTeam** [comment]
ah，没动静了

**Comment by Deep-Dark-Forest** [comment]
感觉可以……让龙猫看看

**Comment by JingHai-Lingyun** [comment]
缓存首页。

**Comment by LTCatt** [comment]
如果要直接重新加载会浪费请求，但做缓存的话又需要额外的工作量，基于目前这个功能没有太大需求，暂时不考虑，抱歉（
