### ISSUE TITLE
电脑内存足够，打开pcl2启动游戏后报错，内存不足

### ISSUE THREAD

**Issue by LCG1280** [Hex-Dragon/PCL2#4252]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![QQ图片20240714181932](https://github.com/user-attachments/assets/ab166640-989d-4ea0-946a-6c6859708840)

### 重现步骤

1启动pcl2（当前电脑剩余内存约30G）
2启动游戏（游戏分配12G）
3minecraft报错（内存已释放）
4.pcl2报错（如图）

### 日志与附件

[Log2.txt](https://github.com/user-attachments/files/16216495/Log2.txt)

**Comment by Deep-Dark-Forest** [comment]
使用其他启动器会发生这种情况吗？

**Comment by LCG1280** [comment]
另外一句，在使用上一个预览版的pcl2的时候，游戏启动是没有问题的

**Comment by LCG1280** [comment]
> 另外一句，使用上一个预览版本的pcl2的时候，游戏启动时没有问题

尝试将后台东西关一下，是可以启动游戏的

**Comment by hejiehao** [comment]
发一下 `D:\MC\.minecraft\versions\Create：Arcane Engineering\hs_err_pid12276.log`

**Comment by LCG1280** [comment]
[hs_err_pid12276.log](https://github.com/user-attachments/files/16216568/hs_err_pid12276.log)

**Comment by hejiehao** [comment]
> [hs_err_pid12276.log](https://github.com/user-attachments/files/16216568/hs_err_pid12276.log)

尝试在桌面右键`此电脑` -- `属性` -- `高级系统设置`，然后按图里的顺序改成`自动管理所有驱动器分页文件大小`，改完后点三个`确定`（不要点右上角的叉）然后重启电脑 ![Image](https://img.kookapp.cn/assets/2023-03/bGbLMNRnws1020j1.png)

**Comment by LCG1280** [comment]
> > [hs_err_pid12276.log](https://github.com/user-attachments/files/16216568/hs_err_pid12276.log)
> 
> 尝试在桌面右键`此电脑` -- `属性` -- `高级系统设置`，然后按图里的顺序改成`自动管理所有驱动器分页文件大小`，改完后点三个`确定`（不要点右上角的叉）然后重启电脑 ![Image](https://camo.githubusercontent.com/f2ab3a73f833e6e0539adf631d00252d0654f3b8a6beb75f8da6e4b7fa827881/68747470733a2f2f696d672e6b6f6f6b6170702e636e2f6173736574732f323032332d30332f6247624c4d4e526e7773313032306a312e706e67)

是自动的，显示已分配53096mb

**Comment by allMagicNB** [comment]
你应该调整你的内存分配设置。

**Comment by hejiehao** [comment]
Line 1314
```
TotalPageFile size 126166M (AvailPageFile size 23M)
```
这应该是系统问题，不是由 PCL 导致的
解决方案：emmm……可能需要关掉一部分程序或者手动调节分页文件大小

**Comment by allMagicNB** [comment]
所以说，HMCL 能启动吗？

**Comment by burningtnt** [comment]
如果 HMCL 也无法启动，请上传崩溃信息

**Comment by LCG1280** [comment]
现在暂时没法复现，因为关了一些东西能用了，就算把那个再打开也没用
我再试试

**Comment by LTCatt** [comment]
OutOfMemoryException 只能由系统报出，均与启动器无关 :/
