### ISSUE TITLE
对模组LanServerProperties(自定义局域网联机)的版本识别错误

### ISSUE THREAD

**Issue by EndlessEmptiness** [Hex-Dragon/PCL2#4253]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

当下载模组LanServerProperties, 1.20.1, Fabric页面中错误的将模组版本1.13(仅支持1.21)归入

### 重现步骤

1. 转到下载Mod页面
2. 搜索 "lan server properties"(不带双引号)
3. 转到1.20.1选项卡, 可以看到, 1.21-1.13-fabric(适用于mc1.21)被错误的归类

### 日志与附件

![issue-pcl2-0714](https://github.com/user-attachments/assets/424f48e9-8848-4676-bcab-b38374b262b4)

**Comment by WorldHim** [comment]
补一下日志
已确定非 CurseForge 问题
![](https://github.com/user-attachments/assets/c476b73b-282d-4f64-b18b-301a0bb1a4ce)

**Comment by allMagicNB** [comment]
#4186

**Comment by EndlessEmptiness** [comment]
> #4186

e..
抱歉，是我搜索不够完全（

**Comment by hejiehao** [comment]
![QQ_1720955699207](https://github.com/user-attachments/assets/93f9ed54-db4f-4d3c-91a1-ead51350c44b)
[Response.json](https://github.com/user-attachments/files/16216578/Response.json)
