### ISSUE TITLE
PCL 在更新完毕后会出现两个 PCL 窗口

### ISSUE THREAD

**Issue by superboy238** [Hex-Dragon/PCL2#4255]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

无

### 重现步骤

1、更新
2、没了

### 日志与附件

6

**Comment by allMagicNB** [comment]
日志呢？

**Comment by LTCatt** [comment]
请补充日志。
@allMagicNB 也请尽量少使用带攻击性的话……这是技术向平台……

**Comment by allMagicNB** [comment]
:thinking:

**Comment by SALTWOOD** [comment]
无法复现，请补充日志
可能的话请顺带补充更新前版本和更新后版本
该bug实际不会对体验造成过多影响，超时可能被关闭。

**Comment by allMagicNB** [comment]
多日未回复，先关了，如果补充信息了再开起来。
