### ISSUE TITLE
1.7.10 支持库文件 SHA1 校验有误

### ISSUE THREAD

**Issue by BOLTieKuai** [Hex-Dragon/PCL2#4256]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述
![QQ图片20240715095945](https://github.com/user-attachments/assets/a8c465b1-a147-4676-aeaf-06f45030b664)
使用HMCL可以进入，使用PCL2会出现补齐文件失败的问题。
到给出的网页手动下载文件补齐，按下启动按钮补齐目标文件会消失。
勾选关闭文件校验依旧无法启动。
似乎与该问题相似 /issues/3792

### 重现步骤

1.下载GTNH整合包
2.将PCL2拖入游戏文件夹内作为启动器
3.设置完毕，启动失败

### 日志与附件

[Log2.txt](https://github.com/user-attachments/files/16229417/Log2.txt)
[Log1.txt](https://github.com/user-attachments/files/16229418/Log1.txt)
[错误报告-2024-7-15_9.53.08.zip](https://github.com/user-attachments/files/16229439/-2024-7-15_9.53.08.zip)

**Comment by BOLTieKuai** [comment]
![Uploading 1.jpg…]()

**Comment by allMagicNB** [comment]
这是由于 Json 给的 Hash 值对不上导致的，你可以关闭强制校验后再启动试试。

**Comment by BOLTieKuai** [comment]
我已经勾选过“关闭文件校验”了

**Comment by allMagicNB** [comment]
> 我已经勾选过“关闭文件校验”了

截屏

**Comment by BOLTieKuai** [comment]
[错误报告-2024-7-16_8.24.21.zip](https://github.com/user-attachments/files/16241554/-2024-7-16_8.24.21.zip)
![@42V{@YDN3BP6V$SP1 QDQ](https://github.com/user-attachments/assets/a85d98ae-e9cf-423d-b139-9f8c35e9b06e)
![GL_232`G59GZI{JIIT0`ZRG](https://github.com/user-attachments/assets/306de4be-b2e6-418d-8850-0c658642bc94)
![P 4)XNA72UTQI4B{U$2W4VA](https://github.com/user-attachments/assets/3b8a7482-d68e-49df-b747-340591202451)
![V2S% $7EBZZHY {H2DQAMHR](https://github.com/user-attachments/assets/4d26a757-50f6-4605-9948-15bd6be6de1b)

**Comment by Pigeon0v0** [comment]
更改标题：部分整合包启动参数构建错误

**Comment by LTCatt** [comment]
请上传更早期的，包含首次报出文件下载失败的信息的日志

**Comment by BOLTieKuai** [comment]
我重新解压了一遍游戏并使用PCL首次启动，关闭文件校验，以下是PCL首次启动失败的日志，报告以及Log文件
![image](https://github.com/user-attachments/assets/b141a01b-73bf-44c6-ae2e-65559e22b101)
[错误报告-2024-7-16_14.39.11.zip](https://github.com/user-attachments/files/16244092/-2024-7-16_14.39.11.zip)
[Log1.txt](https://github.com/user-attachments/files/16244096/Log1.txt)

**Comment by LTCatt** [comment]
这个问题疑似是镜像源提供了错误的文件导致的。
你关闭了文件校验，所以 PCL 下载了这个错误的文件，从而导致启动失败。
所以我需要你最初的主楼截图里的那份 log，来确定是不是文件的问题……
**请上传更早期的，包含首次报出文件下载失败的信息的日志……**

**Comment by Silverteal** [comment]
主楼截图里这个这个sha1应为和sha1实际为不是一样的吗。

**Comment by BOLTieKuai** [comment]
我再次解压了一遍游戏，并且这次没有勾选“关闭文件校验”，以下是解压后首次启动的报错图还有log
![image](https://github.com/user-attachments/assets/ecec7ba9-fe84-4136-8a16-0a0fe44bfc4a)
[Log1.txt](https://github.com/user-attachments/files/16260178/Log1.txt)

**Comment by LTCatt** [comment]
![image](https://github.com/user-attachments/assets/8b678ae2-28a0-4979-8f63-7bab34e92362)
已确认 Mojang 官方提供的 `1.7.10.json` 中的 hash 错了一位数。文件正确的 hash 是 `0f674`，但这里错误写成了 `0f774`。
鬼知道脑残麻将到底是怎么把 hash 写错一位数的，特么不会是手打上去的吧？

考虑到这是 Mojang 的问题，我们这辈子都不能指望 Mojang 能给它修了，现在在考虑这到底怎么办……

**Comment by LTCatt** [comment]
同样无法复现，但这个 `0f774` 是从一个 json 里读取的……现在怀疑是反馈者安装的整合包的 json 有错误？
反馈者能发一下整合包下载地址吗？

**Comment by allMagicNB** [comment]
……不应该 `0f674` 是正确的，整合包版本 JSON `0f774` 才是错的吗？@LTCatt

**Comment by allMagicNB** [comment]
错误报告中有版本 JSON……

版本 JSON 切片：
```json
    {
      "name": "commons-codec:commons-codec:1.9",
      "downloads": {
        "artifact": {
          "path": "commons-codec/commons-codec/1.9/commons-codec-1.9.jar",
          "url": "https://libraries.minecraft.net/commons-codec/commons-codec/1.9/commons-codec-1.9.jar",
          "sha1": "9ce04e34240f774bc72680f8b843b1457383161a",
          "size": 263965
        }
      }
    }
```

实际 Hash：
```
9ce04e34240f674bc72680f8b843b1457383161a
```

**Comment by allMagicNB** [comment]
错误报告中有版本 JSON……

版本 JSON 切片：
```json
    {
      "name": "commons-codec:commons-codec:1.9",
  "downloads": {
    "artifact": {
      "path": "commons-codec/commons-codec/1.9/commons-codec-1.9.jar",
      "url": "https://libraries.minecraft.net/commons-codec/commons-codec/1.9/commons-codec-1.9.jar",
      "sha1": "9ce04e34240f774bc72680f8b843b1457383161a",
      "size": 263965
    }
  }
}
```

实际 Hash：
```
9ce04e34240f674bc72680f8b843b1457383161a
```

**Comment by LTCatt** [comment]
这应该是整合包作者的问题，整合包作者提供了错误的 json
