### ISSUE TITLE
用PCL开服务端

### ISSUE THREAD

**Issue by asadssaksjsi** [Hex-Dragon/PCL2#4258]
### 检查项

- [ ] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [ ] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

可以在PCL中一键下载MC服务端，就像启动客户端那样开服

### 原因

（示例）
我需要这个功能来搞基。很多人都有开服搞基的需求，但如果没有这个功能，就不能愉快的搞基了。

**Comment by allMagicNB** [comment]
用开服器去，这不应该是 PCL 具备的功能。

**Comment by hejiehao** [comment]
https://github.com/Hex-Dragon/PCL2/discussions/113
