### ISSUE TITLE
自动选择Java改善-忽略错误Java

### ISSUE THREAD

**Issue by al-wei** [Hex-Dragon/PCL2#4261]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

添加自动选择Java改善，忽略此类Java路径。这种java是大概率会导致游戏崩溃的，特别是整合包，然而这种Java安装绝对有的（当然其它程序也可能有安装“奇妙的”Java）。

C:\Program Files (x86)\Common Files\Oracle\Java\java8path
C:\Program Files (x86)\Common Files\Oracle\Java\java8path_target_891250

### 原因

不自动选择它们，减少因此类Java造成的崩溃。别的程序带的Java可能不知道怎么弄，至少吧这个路径去掉吧。

**Comment by Pigeon0v0** [comment]
javapath 的 Java 我咋记得老早以前是排除的...

**Comment by Pigeon0v0** [comment]
这里的 Java 因为是软链接，确实可能引发奇奇怪怪的问题

**Comment by allMagicNB** [comment]
有做软链接检测啊……？

**Comment by allMagicNB** [comment]
请给出检测出错的日志或截图。

**Comment by al-wei** [comment]
啊，这个路径是个举例，崩溃可能是其它程序的Java，但是东西被我删干净了，游戏日志我也没留，好几天前的事情了。
另外推荐个检测旧Java的功能，Java过低也会造成崩溃，特别是8_50这种可能电脑里有的，建议做个选择更高位的功能，我也觉得很神奇为什么启动器放着411不选，选50.

**Comment by allMagicNB** [comment]
> 啊，这个路径是个举例，崩溃可能是其它程序的Java，但是东西被我删干净了，游戏日志我也没留，好几天前的事情了。
> 另外推荐个检测旧Java的功能，Java过低也会造成崩溃，特别是8_50这种可能电脑里有的，建议做个选择更高位的功能，我也觉得很神奇为什么启动器放着411不选，选50.

那是故意的，因为官启就是用的 Java 8u51 启动的游戏，有时候不一定 Java 版本越高就越好。

**Comment by allMagicNB** [comment]
> > 啊，这个路径是个举例，崩溃可能是其它程序的Java，但是东西被我删干净了，游戏日志我也没留，好几天前的事情了。

那就看看其他人能不能复现。

> > 另外推荐个检测旧Java的功能，Java过低也会造成崩溃，特别是8_50这种可能电脑里有的，建议做个选择更高位的功能，我也觉得很神奇为什么启动器放着411不选，选50.
> 
> 那是故意的，因为官启就是用的 Java 8u51 启动的游戏，有时候不一定 Java 版本越高就越好。

**Comment by al-wei** [comment]
日志什么的我没保留，其它程序的Java，我也不知道是哪个程序带的，反正也被我删了，怕又选。我选择自动选择java主要是因为整合包，不然我还是会自己选择路径的。有时候自动选择还是更方便些。

**Comment by Pigeon0v0** [comment]
那还请尝试复现一下看看...

**Comment by al-wei** [comment]
低了真的对于整合包与模组而言可能是不太行，我前几天自动选择一次，没崩溃，但是和模组冲突日志循环，.log大小直接几十兆。玩整合包真得高点。

**Comment by al-wei** [comment]
这个高一点的Java功能，可以是一个选项，不一定要写死。

**Comment by al-wei** [comment]
其它程序的哪个Java没办法我前几天删干净了。

**Comment by allMagicNB** [comment]
你可以通过版本设置更改启动时所使用的 Java，另外，你可以试试用官启启动这个整合包，出现问题的话请找整合包作者反馈。
另外，这里不是即时通讯，请一次性把话说完，不然我们的邮箱就会炸掉。

**Comment by al-wei** [comment]
我就是哪个做整合包的

**Comment by al-wei** [comment]
我特意加pcl2，hmcl什么的的分离配置文件加到modpack.zip里，怕的就是有些人搞不定。

**Comment by al-wei** [comment]
我都会在整合包页面点名用哪些启动器有配置，其它自行设置。

**Comment by SALTWOOD** [comment]
此类为软链接，PCL已在代码中排除忽略。
要真能选上才是问题……
顺带，请补充日志，没日志就一句话修不了的哈

**Comment by LTCatt** [comment]
哦，这是 #4282
