### ISSUE TITLE
PCL客户端被Windows安全中心拦截无法启动

### ISSUE THREAD

**Issue by showill** [Hex-Dragon/PCL2#4263]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在被拦截后显示：

PUA:Win32/GameHack
警报级别：低
状态：活动
日期：2024/7/15 11:23
类别：潜在的垃圾软件
详细信息：这个程序具有可能有害的行为。

受影响的项目:
file: D:\MC\Plain Craft Launcher 2.exe

将文件夹添加入排除项即可解决，但终究还是有点麻烦

### 重现步骤

打开微软安全中心会显示类别为潜在的垃圾软件

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16230571/Log1.txt)
[Log2.txt](https://github.com/user
[Log4.txt](https://github.com/user-attachments/files/16230574/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16230575/Log5.txt)

-attachments/files/16230572/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16230573/Log3.txt)

**Comment by showill** [comment]
[Log1.txt](https://github.com/user-attachments/files/16230635/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16230636/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16230637/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16230638/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16230639/Log5.txt)

**Comment by hejiehao** [comment]
#666

**Comment by Louis-Harsune** [comment]
你用的是不是最新的2.8.3版本？据我所知，2.8.3是2.8.2的紧急修复版本，可能龙猫大大还没来得及给2.8.3加wd误报反馈，所以被wd误报应该是正常现象（

**Comment by showill** [comment]
> @showill 你用的是不是最新的2.8.3版本？据我所知，2.8.3是2.8.2的紧急修复版本，可能龙猫大大还没来得及给2.8.3加wd误报反馈，所以被wd误报应该是正常现象（

昨天被拦截后添加了排除项，进入了客户端发现了更新公告。今天换了一台电脑和昨天有同样的问题，然后就点击反馈，但是弹窗提示我不是最新版本，于是我又更新了一下尝试结果还是一样，才来发的贴子，我不确定我的版本，但可以确定的是pcl是上个月安装的。在问题出现前有没有自动更新我就不记得了
