### ISSUE TITLE
PCL2会闪退，而且主文件被删除

### ISSUE THREAD

**Issue by abcdesteve** [Hex-Dragon/PCL2#4264]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

今天已经遇到两次了
正常打开模组管理页面，放一会，然后切到其他软件，然后PCL2就莫名其妙被关掉了，最离谱的是PCL2主文件也被干掉了，但文件夹还在
开着火绒，关掉了windows defender，火绒也没有删除记录，应该不是杀软的问题
看了 pcl 的日志，也没有什么大问题

### 重现步骤

1.打开模组管理页面
2.切到其他软件
3.PCL就被干掉了

### 日志与附件

[Log2.txt](https://github.com/user-attachments/files/16231268/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16231269/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16231270/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16231271/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/16231272/Log1.txt)

**Comment by allMagicNB** [comment]
#666

**Comment by hejiehao** [comment]
> 然后PCL2就莫名其妙被关掉了

更新的时候自动重启了吧

**Comment by abcdesteve** [comment]
> > 然后PCL2就莫名其妙被关掉了
> 
> 更新的时候自动重启了吧

不是更新导致的，日志里面那两次更新是因为被删掉之后，我又重新下了一遍，更新完之后放在那里就会这样，而且比较随机

**Comment by abcdesteve** [comment]
> #666

但是按理说开了火绒之后，wd不是会自己关掉的吗？

**Comment by hejiehao** [comment]
要不试试火绒剑？

**Comment by Pigeon0v0** [comment]
反正和 PCL 没关系...

可能是你 WD 没关干净导致的...

**Comment by allMagicNB** [comment]
> > #666
> 
> 但是按理说开了火绒之后，wd不是会自己关掉的吗？

屁嘞，还是会后台暗箱操作（
