### ISSUE TITLE
获取头像以及uuid异常，但是登录正常

### ISSUE THREAD

**Issue by hanyixuanten** [Hex-Dragon/PCL2#4265]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/user-attachments/assets/966f92c0-02bc-405e-9935-4effaf2eee29)
![image](https://github.com/user-attachments/assets/a2c16981-acf9-4b4b-8dba-bea20366ac40)
![image](https://github.com/user-attachments/assets/ba6370e8-ff78-4f64-8284-32b865d6d666)
无法获取皮肤和uuid

### 重现步骤

1. 打开PCL
2. 弹出**下图**的错误提示
![image](https://github.com/user-attachments/assets/966f92c0-02bc-405e-9935-4effaf2eee29)
![image](https://github.com/user-attachments/assets/a2c16981-acf9-4b4b-8dba-bea20366ac40)
![image](https://github.com/user-attachments/assets/ba6370e8-ff78-4f64-8284-32b865d6d666)

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16233955/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16233956/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16233957/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16233958/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16233959/Log5.txt)

**Comment by hejiehao** [comment]
这应该是你的网络问题

**Comment by hanyixuanten** [comment]
好的

________________________________
发件人: 何杰豪 ***@***.***>
发送时间: 2024年7月15日 19:57
收件人: Hex-Dragon/PCL2 ***@***.***>
抄送: hanyixuanten ***@***.***>; Author ***@***.***>
主题: Re: [Hex-Dragon/PCL2] 获取头像以及uuid异常，但是登录正常 (Issue #4265)


这应该是你的网络问题

―
