### ISSUE TITLE
关于pcl2打开文件夹的bug

### ISSUE THREAD

**Issue by Albert-s-library** [Hex-Dragon/PCL2#4269]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

事先声明，我安装了windhawk的Classic Explorer navigation bar以更改win11文件资源管理器的导航栏，因为win11新版导航栏不支持拖拽复制，然后用pcl打开文件夹时会导致导航栏消失，80%的概率吧，其他大量形形色色的国内外软件均不会出现，断定是pcl2的问题，这不是大众问题，所以不强求修复

### 重现步骤

见上文

### 日志与附件

没啥

**Comment by allMagicNB** [comment]
你拿 HMCL 试试。

**Comment by Albert-s-library** [comment]
一样的，mc启动器的问题？

**Comment by allMagicNB** [comment]
都是 explorer 参数调用，一个出问题肯定多个都出问题。

**Comment by kong-que-dnf123** [comment]
欸等下现在关闭之后等待反馈者不会被替换成忽略了吗
