### ISSUE TITLE
爱发电网址迁移至 afdian.com

### ISSUE THREAD

**Issue by SuoHouDaiShi** [Hex-Dragon/PCL2#4271]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

![图片](https://github.com/user-attachments/assets/09f3998b-87b8-4554-ac9e-af673a84ef70)
ITDOG 的 ping 测试，能看出全国各地的延迟都不一样，还有解析失败的。使用 223.5.5.5 这个 DNS 地址则全部解析失败。

### 原因

如题，万一爱发电真跑了呢……

**Comment by XC084** [comment]
https://github.com/Hex-Dragon/PCL2/issues/4188#issuecomment-2228866587

**Comment by allMagicNB** [comment]
![Screenshot_20240716_083009_com.android.vending.jpg](https://github.com/user-attachments/assets/f440dc0a-125e-454a-93a5-52b3d55892c6)

打这个电话试试？

**Comment by yhgzs-111** [comment]
支持，且目前爱发电 (afdian.net) 目前已经无法正常打开，通过检测域名信息可以看到目前爱发电的 ICP 备案信息 (琼 ICP 备 18001024 号 – 1) 已经被注销。

来源：https://www.landiannews.com/archives/104953.html

**Comment by SuoHouDaiShi** [comment]
![图片](https://github.com/user-attachments/assets/190fdff4-e642-4b57-a7be-5d9fbd6bb892)
刚刚又看了一眼 ITDOG，测试出来的结果少部分地区解析出原 IP（即 154 开头的 IP），少部分解析出新 IP（104.17.96.0），其余响应超时

**Comment by lbyxiaolizi** [comment]
楼上的图是真的，去新网问了。估计是洗钱相关的问题
<img width="650" alt="Snipaste_2024-07-16_12-11-20" src="https://github.com/user-attachments/assets/2839396a-2141-4703-a694-e1821934e018">

**Comment by LTCatt** [comment]
问了站长，大概没跑路，人也还在，先等几天，如果几天还没打赢复活赛再说……

**Comment by Silverteal** [comment]
我个人建议你别急

**Comment by SuoHouDaiShi** [comment]
> 我个人建议你别急

我这也不知道怎么个事，反正应该……没多少人纯靠爱发电维持生计（
和龙猫所说的一样，几天后再看看

**Comment by Louis-Harsune** [comment]
![image](https://github.com/user-attachments/assets/88fb8311-fba9-4937-a5d3-e3c1a1cbca5f)
目前爱发电无法访问带来的影响如下：
1.龙猫目前无法获得任何赞助；
2.用户目前无法获得更新密钥、秋仪金解锁密钥、PCL2 QQ群验证码；
3.新用户无法赞助龙猫，进而无法获得PCL2快照版。
如果爱发电短期内不能访问的话，受最大影响的应该是后续的版本更新（因为要上爱发电获取更新密钥），龙猫可以考虑下应对措施，因为爱发电这次出事应该是涉及到赞助功能用于洗钱等资金操作的问题，短时间内很难恢复访问…………

**Comment by Louis-Harsune** [comment]
![image](https://github.com/user-attachments/assets/0978a33d-4974-459e-8ce8-038e1d7086e3)
还有个意外发现：，目前部分地区解析出的104开头的IP似乎托管在Cloudflare，本人尝试直接访问报错如下：
![image](https://github.com/user-attachments/assets/fdd24ff1-15c0-483f-b1b1-59e271a59c21)

**Comment by Louis-Harsune** [comment]
蒙了，7月18日晚再测…………：
全国大部分地区都至少有一个运营商解析出IP了，DNS改223.5.5.5的时候仍然全国不通，不过因为我人在上海，而上海全运营商拒绝解析，所以本人无法测试，如果有其它地区能帮忙测试最好……谢谢…………
![image](https://github.com/user-attachments/assets/d9d13124-250b-4f54-ae77-5bacbcddf687)
![image](https://github.com/user-attachments/assets/fc786ddb-8c93-4c82-8d0e-bd0695eebb60)

**Comment by ggzyx** [comment]
![image](https://github.com/user-attachments/assets/2d1f63c1-3495-4aae-b9ab-be4b90bcec3d)
我们上海完全连不上。现在我下载不了。龙猫能给个链接吗5555

**Comment by NaOH-HaN** [comment]
> ![image](https://private-user-images.githubusercontent.com/112259945/350173943-2d1f63c1-3495-4aae-b9ab-be4b90bcec3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNTEwNzYsIm5iZiI6MTcyMTM1MDc3NiwicGF0aCI6Ii8xMTIyNTk5NDUvMzUwMTczOTQzLTJkMWY2M2MxLTM0OTUtNGFhZS1iOWFiLWJlNGI5MGJjZWMzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOVQwMDU5MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZjAyZjMxZTEwNzhkNzFkZjFhYWMzMzUzZmE0NWQwMDUzYjA3Yjc0MTYwZmQyZmVmMDgzY2FmY2RmMGYwZWVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vRB2r7Hjtgcgxd0r8nIreg215VmtkWDKLgGwUqacuXA) 我们上海完全连不上。现在我下载不了。龙猫能给个链接吗5555

用afdian.com试试？

**Comment by Louis-Harsune** [comment]
> 用afdian.com试试？

卧槽，全国畅通
![image](https://github.com/user-attachments/assets/7bb1147b-d865-4a48-8ad9-b0d2c75354d6)
![image](https://github.com/user-attachments/assets/8236fe59-0c10-4dc3-8870-cf9e70fe8668)

**Comment by Louis-Harsune** [comment]
@LTCatt afdian.com完全可用

**Comment by LTCatt** [comment]
站长说这是临时方案，之后主站会恢复的，还是没必要改

**Comment by ggzyx** [comment]
ifdian.net也可用

**Comment by ggzyx** [comment]
爱发电的正式版下载地址改一下
还有github的

**Comment by model-err** [comment]
刚测的TCPPing，全红……
Ping也全部解析失败。
ifadian.net倒是能用，就是那个速度……近似不可用。
![image](https://github.com/user-attachments/assets/d2a6b9c8-4b71-4f2a-a324-8728ecfba440)
附上一张图

**Comment by model-err** [comment]
> @model-err
> 
> It is `afdian.net`, not `aifadian.net` It is `ifdian.net`, not `ifadian.net`
> 
> They currently have an alternative domain name `afdian.com`, you can try it.
看错了，抱歉（
又测了一下，afadian.net有解析，但是全国超时
ifdian.net倒能用

**Comment by Pigeon0v0** [comment]
现在应该需要更改为 `afdian.com` 了，官方已经私信了创作者...

**Comment by z0z0r4** [comment]
虽然已经结束了，但麻烦测试别用运营商 DNS，用 8.8.8.8 / 1.1.1.1 之类的，运营商 DNS 缓存会延迟很久，ITDOG 指定 DNS 默认 223.5.5.5 阿里 DNS 也没多好...楼上一直在灌图

**Comment by luduting** [comment]
> ![image](https://private-user-images.githubusercontent.com/112259945/350173943-2d1f63c1-3495-4aae-b9ab-be4b90bcec3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNjM0MDksIm5iZiI6MTcyNTE2MzEwOSwicGF0aCI6Ii8xMTIyNTk5NDUvMzUwMTczOTQzLTJkMWY2M2MxLTM0OTUtNGFhZS1iOWFiLWJlNGI5MGJjZWMzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMVQwMzU4MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MWVjNjEwOWMxZmMwODIyZTk3NTEzN2E3MTUxOTFjNzY0NGE5NjU0NjA3ODA3NzExNTExNTNlNmIzOGRiMDYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gL2q2NA5IWlf7rDUKr1aH4b_L5CwdHI-ss94qQ14Lz4) 我们上海完全连不上。现在我下载不了。龙猫能给个链接吗5555

https://wwwo.lanzouq.com/iU2Dv1tyy8uh 密码:pcl2

**Comment by SuoHouDaiShi** [comment]
@LTCatt 那个，这几天电脑硬盘炸了，换了盘重装了系统，所以……重新发下解锁码（
097A-9248-9F1A-BFE9

**Comment by MoYuan-CN** [comment]
歪，这是个优化的 Issue 的说
