### ISSUE TITLE
同时启动多个客户端的bug

### ISSUE THREAD

**Issue by Dainsleif233** [Hex-Dragon/PCL2#4272]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

同时用不同账户A和B启动同一个客户端，在A端打开一个世界并开启局域网联机，在B端多人游戏中查看，显示局域网世界的用户为B，加入世界，有两种情况：
1、A端提示异地登入，B端加入失败
2、正常加入世界，在世界中两个端的ID正常，此时B端退出世界，B端正常退出，A端提示服务器已关闭并跳转到多人联机界面

### 重现步骤

1、同时用不同账户A和B启动同一个客户端
2、在A端打开一个世界并开启局域网联机
3、在B端多人游戏中查看，显示局域网世界的用户为B，加入世界，有两种情况：
    （1）A端提示异地登入，B端加入失败
    （2）①正常加入世界，在世界中两个端的ID正常
             ②此时B端退出世界，B端正常退出，A端提示服务器已关闭并跳转到多人联机界面

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16243316/Log1.txt)

**Comment by allMagicNB** [comment]
用 HMCL 试试

**Comment by Silverteal** [comment]
`[12:54:57.877] [Skin] 由于离线皮肤设置，使用正版 UUID：UpSGE`
我一直说这个离线皮肤设置害人不浅……

两种情况的本质原因都是因为离线登录的客户端设置了“正版皮肤“，使用了正版的UUID，导致，你的A客户端和B客户端实际上使用了同一个UUID。这是游戏预期外的行为。

**Comment by Dainsleif233** [comment]
> 用 HMCL 试试。

测试了几遍没有出现这种情况

补充一点：测试时使用的是一个在线账户一个离线账户（ID不同），看日志初步判断可能是离线账户设置了和在线账户ID一致的“正版皮肤”，导致两个账户使用了同一个UUID

**Comment by allMagicNB** [comment]
HMCL 也设置了皮肤。

**Comment by Dainsleif233** [comment]
在HMCL中设置离线账户皮肤时没有看到“正版皮肤”选项，故离线账户使用默认皮肤

**Comment by Dainsleif233** [comment]
> HMCL 也设置了皮肤？

在HMCL中设置离线账户皮肤时没有看到“正版皮肤”选项，故离线账户使用默认皮肤

**Comment by Pigeon0v0** [comment]
都使用默认皮肤配置再试

**Comment by Silverteal** [comment]
我以为我已经说得很明白了

**Comment by allMagicNB** [comment]
算了先给龙猫看看，这是离线皮肤使用正版 UUID 的锅。

**Comment by LTCatt** [comment]
这个没法解决，要实现离线玩家用正版皮肤就只有这一个办法 =。=
要么把正版皮肤这个功能删了，要么这个就没得修，那还是这个没得修好点……
