### ISSUE TITLE
在下载整合包时到某一进度就卡住

### ISSUE THREAD

**Issue by collguys** [Hex-Dragon/PCL2#4274]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在安装整合包时到达某一进度（大约在下载fabric时）就会卡下载，长时间几K/S甚至0B/S
在安装前确认网络正常，但安装时所有应用均无法访问互联网
重复尝试了本地导入和pcl自带下载功能，均卡住

### 重现步骤

1、直接下载整合包
2、点进下载详情

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16244880/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16244882/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16244883/Log3.txt)
[Log4.txt](https://github.com/user-attachments/f
[Log5.txt](https://github.com/user-attachments/files/16244885/Log5.txt)
iles/16244884/Log4.txt)

**Comment by allMagicNB** [comment]
……这应该是在启动 Fabric 安装程序。

**Comment by allMagicNB** [comment]
HMCL 会不会卡？

**Comment by LTCatt** [comment]
由于长时间未回复暂时关闭
