### ISSUE TITLE
内置外文翻译功能及常见游戏bug库

### ISSUE THREAD

**Issue by Mechnology** [Hex-Dragon/PCL2#4275]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

在启动器的英文报错页面、mod下载页上的描述上用内置翻译功能，让用户简单的了解英文信息，而不是打开浏览器，用那个死难用的机翻网站。翻译功能可以考虑一下translate by Microsoft translator
加入常见报错bug库，由用户添加内容，内含bug解决办法

### 原因

是pcl用起来更优雅，而不是将浏览器上的mcbbs，谷歌翻译等作为pcl的辅助!

**Comment by hejiehao** [comment]
> 内置外文翻译功能

基于云服务，不会制作

> 常见游戏bug库

在崩溃之后 PCL 可能会给出常见的解决方案，如果需要扩充，请提交 Pull Request

**Comment by Silverteal** [comment]
> 内置外文翻译功能

如果您愿意付出三到五位数不等的人民币提供相关服务的 API 密钥以及相关的资质（如统一社会信用代码）的话，想必也是可以的。

> 常见游戏bug库

我尽量用你能明白的方式解释：
如果能提前收录bug，那它就不叫bug了
