### ISSUE TITLE
自定义版本隔离

### ISSUE THREAD

**Issue by DoubtedYapper71** [Hex-Dragon/PCL2#4276]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

让每一个文件夹都可以选择隔离/不隔离版本

### 原因

一些杂乱的版本单独放一个文件夹隔离，常玩的不需要隔离（如更新fabricloader）的文件夹设置不隔离

**Comment by DoubtedYapper71** [comment]
是每个mc文件夹自定义是否启用版本隔离

**Comment by hejiehao** [comment]
> 是每个mc文件夹自定义是否启用版本隔离

是这些文件夹吗？
![QQ_1721118065557](https://github.com/user-attachments/assets/320107de-fbaa-41b5-88f0-6c5fecf35b5d)

**Comment by DoubtedYapper71** [comment]
是的

**Comment by allMagicNB** [comment]
#959

**Comment by allMagicNB** [comment]
在版本单独设置中设置即可

**Comment by allMagicNB** [comment]
？机器人没了？

**Comment by Deep-Dark-Forest** [comment]
> ？机器人没了？

Close as not planned 只能让机器人打上“忽略”标签，想要打重复还得手动……
