### ISSUE TITLE
整合包安装信息存在问题：未将对象引用设置到对象的实例

### ISSUE THREAD

**Issue by goumo** [Hex-Dragon/PCL2#4277]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在最新版本中安装附件中的整合包时提示 **整合包安装信息存在问题：未将对象引用设置到对象的实例** ，但是在旧版本 PCL 或 HMCL 中可以正常安装 

（.minecraft 文件夹内为模组文件和整合包图标，我认为和报错无关所以没有上传）

### 重现步骤

1、将压缩包拖进启动器安装

### 日志与附件

[整合包安装信息.zip](https://github.com/user-attachments/files/16248839/default.zip)
[日志.zip](https://github.com/user-attachments/files/16248969/default.zip)

**Comment by goumo** [comment]
> The modpack you provided is missing the `instance.cfg` file.

That's all the files, and it's can be installed when using older versions of PCL

**Comment by goumo** [comment]
> Could you provide a rough version range?

around February

**Comment by lactobionicAcid** [comment]
HMCL 读取该整合包时似乎直接跳过了 `mmc-pack.json` 文件...
也就是说， HMCL 根本就没把这玩意作为 MultiMC 整合包读取。

_说明 PCL 对于整合包类型的检测还不够完善...?_

**Comment by goumo** [comment]
另一个 issue 也是冬季救援整合包，这也太巧了

我刚才试了下即使是 mmc 也不能导入，也就是说 `instance.cfg` 是必须的，由于发布时误删导致新版本 PCL 无法正确读取整合包，所以不应该由 PCL 背这口锅（
