### ISSUE TITLE
添加java路径复制功能

### ISSUE THREAD

**Issue by cucumbertw** [Hex-Dragon/PCL2#4278]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

在设置 > 游戏java 的下拉框中添加右键复制此java路径功能。没有这个功能，我无法快速的找到已经添加的java并检查（例如发生：无法找到此java的javaw.exe文件时）

### 原因

（示例）
我需要这个功能来xxxx。很多人都有xxxx的需求，但如果没有这个功能，就不能xxxx了。

**Comment by allMagicNB** [comment]
感觉不是很有必要……

**Comment by zkitefly** [comment]
可以在日志中拷贝吗

**Comment by LTCatt** [comment]
这个需求应该不大，暂时不考虑，抱歉（
