### ISSUE TITLE
在GitHub仓库页面添加“Sponsor”按钮

### ISSUE THREAD

**Issue by idhaname** [Hex-Dragon/PCL2#4279]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

如图，在GitHub仓库页面添加“Sponsor”按钮
![QQ_1721137440548](https://github.com/user-attachments/assets/66edcd21-cbfc-4d55-a7df-e601045ac6c0)
参考 #3560

### 原因

可以方便去到爱发电或者其他的赞助平台（如果以后有的话，参见 #4271）

**Comment by WorldHim** [comment]
#3560

**Comment by Deep-Dark-Forest** [comment]
要做也得等龙猫找到新的赞助平台以后……

**Comment by LTCatt** [comment]
等爱发电那稳定下来就加

**Comment by Deep-Dark-Forest** [comment]
@LTCatt 爱发电稳定下来了，那应该加了吧（
