### ISSUE TITLE
pcl闪退

### ISSUE THREAD

**Issue by vwot** [Hex-Dragon/PCL2#428]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

闪退未知代码

### 重现步骤

未知，pcl提示报告错误

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10066851/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10066852/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10066853/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10066854/Log4.txt)
[Uploading Log5.txt…]()

**Comment by LTCatt** [comment]
系统问题，不是 PCL 的问题。
