### ISSUE TITLE
我在更新了新版的PCL后文件自己提示存在病毒或垃圾文件，这很奇怪

### ISSUE THREAD

**Issue by dwdpwq** [Hex-Dragon/PCL2#4280]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

新版本的pcl会自己生成一个新的文件夹，但是当旧的PCL在他的上级目录时老的PCL无法启动会提示存在病毒或垃圾文件，而且我已经装载的整合包新版本没有自动识别到，以往不会这样

### 重现步骤

1、点击xxxx
2、往下滚，然后点击xxxx

### 日志与附件

[Log2.txt](https://github.com/user-attachments/files/16252094/Log2.txt)
[Log1.txt](https://github.com/user-attachments/files/16252095/Log1.txt)

**Comment by hejiehao** [comment]
#666
