### ISSUE TITLE
Optifine 对 1.8 和 1.9 的版本标记存在问题，导致部分整合包可能无法正确安装 Optifine

### ISSUE THREAD

**Issue by Silverteal** [Hex-Dragon/PCL2#4281]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

转发自 #4052

据 OpenBMCLAPI 成员反馈，Optifine 的分版本列表中将 1.8 和 1.9 分别标记为（实际上是错误的，但它就是这么写的） 1.8.0 和 1.9.0，导致安装整合包时可能无法正确下载上述两个版本的 Optifine。

具体地，安装整合包时，启动器会尝试请求`/optifine/1.8`，从而获取到空列表。而正确的列表是`/optifine/1.8.0`

**Comment by LTCatt** [comment]
@bangbang93 这个会不会在你那里做一下兼容更好……？

**Comment by bangbang93** [comment]
![image](https://github.com/user-attachments/assets/d3367c80-f079-4d7c-a791-e3a31e63ef1e)

optifine给的版本号就是这玩意
