### ISSUE TITLE
在1.20.1版本中下载forge失败的问题

### ISSUE THREAD

**Issue by PumpkinPeroxide** [Hex-Dragon/PCL2#4282]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

原是在PCL2.8.3版本中安装Minecraft1.20.1+forge版本时出现了：Forge 安装器出错错误，日志部分（log2~log3）提示为：找不到或无法加载主类 com.bangbang93.ForgeInstaller，尝试了1.20.1中其他版本的forge皆有此问题，而别的Minecraft版本的forge仍能够正常下载
随后更换了较早的PCL2.7.4版本，产生了相同的问题
尝试使用BakaXL以及HMCL启动器安装同版本的Minecraft及forge，皆能够正常下载

### 重现步骤

PCL版本2.7.4
1、点击下载，自动安装
2、选择正式版——1.20.1——Forge——最新版（47.3.5）——安装
3、直到下载Forge支持库文件、下载原版支持库文件等都正常
4、当到达“安装Forge文件（方式A）”项时，进度在大约6%时安装失败
具体提示为：
下载 Forge 47.3.5失败
→ 安装 Forge（方式 A）失败
→ 安装新 Forge 版本失败
→ 运行 Forge 安装器失败
→ Forge 安装器出错，日志结束部分为：
错误: 找不到或无法加载主类 com.bangbang93.ForgeInstaller
   在 PCL.ModDownloadLib._Closure$__35-0._Lambda$__7(LoaderTask`2 Task)
   在 PCL.ModLoader.LoaderTask`2._Closure$__13-0._Lambda$__0()
   在 PCL.ModDownloadLib._Closure$__35-0._Lambda$__7(LoaderTask`2 Task)
   在 PCL.ModDownloadLib.ForgelikeInjector(String Target, LoaderTask`2 Task, String McFolder, Boolean UseJavaWrapper, Boolean IsNeoForge)
   在 PCL.ModDownloadLib._Closure$__35-0._Lambda$__7(LoaderTask`2 Task)

在PCL版本2.8.3中略有不同，具体提示为：
下载 Forge 47.3.5失败
→ 安装 Forge（方式 A）失败
→ 安装新 Forge 版本失败
→ 运行 Forge 安装器失败
→ Forge 安装器出错，日志结束部分为：
错误: 找不到或无法加载主类 com.bangbang93.ForgeInstaller
   在 PCL.ModDownloadLib._Closure$__35-0._Lambda$__7(LoaderTask`2 Task)
   在 PCL.ModLoader.LoaderTask`2._Closure$__13-0._Lambda$__0()
   在 PCL.ModDownloadLib._Closure$__35-0._Lambda$__7(LoaderTask`2 Task)
   在 PCL.ModDownloadLib.ForgelikeInjector(String Target, LoaderTask`2 Task, String McFolder, Boolean UseJavaWrapper, Boolean IsNeoForge)
   在 PCL.ModDownloadLib._Closure$__35-0._Lambda$__7(LoaderTask`2 Task)

以上提示应均能在提交的log中寻找到

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16260733/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16260735/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16260736/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16260737/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16260738/Log5.txt)

**Comment by LTCatt** [comment]
更新

**Comment by LTCatt** [comment]
`1.20.1-Forge_47.0.0` 无法复现。
不是中文路径问题，不知道咋回事，需要第三方的复现来获取更多线索……

**Comment by allMagicNB** [comment]
像是 Java 问题？

**Comment by LTCatt** [comment]
```
[13:22:24.289] [Java] 排序后的 Java 优先顺序：
[13:22:24.289] [Java]  - JRE 8 (8.0.411)：C:\Program Files (x86)\Common Files\Oracle\Java\java8path_target_23754000\
[13:22:24.289] [Java]  - JRE 8 (8.0.411)：D:\Program Files\Java\bin\
[13:22:24.289] [Java]  - JDK 21 (21.0.1)：D:\Program Files\Zulu\zulu-21\bin\
[13:22:24.289] [Java]  - JDK 22 (22.0.1)：D:\Program Files (x86)\Java\jdk-22\bin\
[13:22:24.289] [Java] 最终选定的 Java：JRE 8 (8.0.411)：C:\Program Files (x86)\Common Files\Oracle\Java\java8path_target_23754000\
```

奇怪，PCL 现在应该会尽量不把 `java8path_target` 这种 Java 加进列表才对……
反馈者点一下自动搜索，然后再发一下 log？
![image](https://github.com/user-attachments/assets/bd6fca8d-c93d-4354-ade4-8042a12a767c)

**Comment by PumpkinPeroxide** [comment]
[Log1.txt](https://github.com/user-attachments/files/16267398/Log1.txt)

**Comment by PumpkinPeroxide** [comment]
现在进行下载都能够成功，无论是最新版还是47.0.0，奇怪……
以下是点击了自动搜索java后的日志内容
[Log1.txt](https://github.com/user-attachments/files/16267457/Log1.txt)

**Comment by LTCatt** [comment]
现在会特例排除路径含 `java8path_target_` 的 Java。
