### ISSUE TITLE
Quilt整合包显示Fabric

### ISSUE THREAD

**Issue by XiaLize** [Hex-Dragon/PCL2#4283]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

用HMCL安装了Quilt整合包之后返回PCL却显示Fabric
![屏幕截图 2024-07-17 164019](https://github.com/user-attachments/assets/cf5df82c-586f-46a7-ad6f-269ead642ea2)

### 重现步骤

用HMCL安装了Quilt整合包之后返回PCL却显示Fabric

### 日志与附件

114514

**Comment by allMagicNB** [comment]
Quilt 还没正式支持……
