### ISSUE TITLE
官启目录游戏的 Java 选择可能不正确

### ISSUE THREAD

**Issue by Pigeon0v0** [Hex-Dragon/PCL2#4286]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如果 `%appdata%\.minecraft\runtime` 下含有 Java，此时自动选择 Java 的行为是优先使用当前游戏目录下 Java，这可能会意外导致官启目录下的游戏使用错误的 Java 启动。

应当在游戏目录为官启目录时，降低当前目录的选择优先级。

### 重现步骤

1. 让 PCL 或其他启动器自动安装一个 Java，如 Java 21
2. 下载需要 Java 17 的 MC，如 1.20.1
3. 启动这个版本

### 日志与附件

[PCL 启动器日志(2).txt](https://github.com/user-attachments/files/16264296/PCL.2.txt)

日志来自 PCL 8 群群友（3525696203），Bug 本人发现

**Comment by allMagicNB** [comment]
<details>

<summary>前情提要</summary>

![Image_1721215297425.png](https://github.com/user-attachments/assets/9cf235f9-fdd9-49b3-b9f5-d098701d0b49)

</details>
