### ISSUE TITLE
正版登录时登陆失败:暂时无法连接到身份验证服务器，请稍后再试。

### ISSUE THREAD

**Issue by LvShuo233** [Hex-Dragon/PCL2#4288]
[latest.log](https://github.com/user-attachments/files/16277782/latest.log)
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

尝试登入所有服务器是出现此类错误，并且只有正版出现此问题，离线尝试进入服务器(例如:2b2t.xin)可以进入，而正版无论什么服务器都会出现此类错误。 连国服也无法进入，同样出现此类问题。
并且发现正版皮肤无法显示。

### 重现步骤

1.启动任意版本
2.选择多人游戏
3.随便新建一个服务器(mc.hypixel.net)(2b2t.org)
4.进入后就会弹出此类错误

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16276232/Log1.txt)
![Uploading 屏幕截图 2024-07-18 084834.png…]()

**Comment by allMagicNB** [comment]
用 HMCL 试试。

**Comment by mcwuguodadi** [comment]
这种问题一般是网络问题，微软的验证服务器一直都很烂：D
你这边或者是服务器那边任何一方连不上验证服务器就会这样
解决方案很简单，无法连接验证服务器的那一方挂梯/开加速器就可以

你这边连hypixel也会弹出此类错误，可以判断是你的网络问题

## 附件问题
截图都没传上来就发布了：D
这种问题上传的应该是Minecraft日志，而不是PCL2日志，PCL2一点问题都没有

**Comment by LvShuo233** [comment]
我这边连国服也会出现此类问题XD

**Comment by hejiehao** [comment]
发 latest.log 可能更有用（

**Comment by mcwuguodadi** [comment]
> 我这边连国服也会出现此类问题XD

有排除hosts文件吗？一般在`C:\Windows\System32\drivers\etc`目录下
用记事本打开看看有没有之前设置的mc相关的条目

**Comment by mcwuguodadi** [comment]
> This is a bit strange. And I would like to know what you mean by _国服_.

国服 means the Chinese version of Minecraft, which is hosted by NetEase
Its official website is [mc.163.com](https://mc.163.com)

**Comment by mcwuguodadi** [comment]
（按错了，sorry）

**Comment by LTCatt** [comment]
并非 PCL 的问题，参考：https://blog.csdn.net/pzysoft/article/details/62888780

**Comment by LvShuo233** [comment]
@LTCatt 能教我咋搞啊，自己搞总是出错误
![Uploading 屏幕截图 2024-11-03 155706.png…]()

**Comment by hejiehao** [comment]
你的截图没上传成功，请等待 `Uploading` 消失后再点击下面的绿色按钮 Comment

**Comment by LvShuo233** [comment]
@LTCatt 能教我咋搞啊，自己搞一大堆问题
![屏幕截图 2024-11-03 155706](https://github.com/user-attachments/assets/1c41d604-be24-4782-82d6-f65a8ff01482)
