### ISSUE TITLE
 Forge Minecraft崩溃 提示 Fabric 已给出解决方案

### ISSUE THREAD

**Issue by WatchfulBand** [Hex-Dragon/PCL2#4289]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在加入 Sinytra Connector(Forge和Fabric的共存) 模组的情况下 Fabric 模组报错会提示
![屏幕截图 2024-07-18 102706](https://github.com/user-attachments/assets/3ee907ba-9e24-45df-b531-aa9eb37b0600)
但这是 Sinytra Connector 与不兼容 Sinytra Connector 的 Fabric 模组一起加载 造成的
Log2里体现报错内容和具体信息

### 重现步骤

1、下载 Forge 1.20.1
2、加入 Sinytra Connector、钠、iris模组
3、启动游戏

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16276963/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16276964/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16276966/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16276967/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16276968/Log5.txt)

**Comment by Pigeon0v0** [comment]
信雅互联应该不会做特殊处理...

**Comment by allMagicNB** [comment]
就钠不兼容

**Comment by LTCatt** [comment]
请上传对应的错误报告

**Comment by Louis-Harsune** [comment]
应该是这个错误弹窗不看Minecraft实际装的是哪个模组加载器，而是看报错对应的模组是哪个加载器平台的吧…………
毕竟这里装载的是Fabric模组…………

**Comment by Silverteal** [comment]
Works as Expected

**Comment by HomoobyDX** [comment]
我想知道如果是信雅互联PCL会在版本列表显示什么加载器。如果显示是fabric那是不是错误报告就会按照fabric来输出错误提示

**Comment by Louis-Harsune** [comment]
> 我想知道如果是信雅互联PCL会在版本列表显示什么加载器。如果显示是fabric那是不是错误报告就会按照fabric来输出错误提示

版本列表应该还是显示Forge，因为这里的显示和Minecraft实际装载的模组加载器有关，信雅互联和对应的兼容API实际也都是Forge平台模组

**Comment by WatchfulBand** [comment]
[错误报告-2024-7-19_13.17.49.zip](https://github.com/user-attachments/files/16302412/-2024-7-19_13.17.49.zip)

**Comment by LTCatt** [comment]
![image](https://github.com/user-attachments/assets/f9df1717-b8db-4829-983f-bc3c05cabb3d)
这确实是 Fabric 的报错格式，暂时没必要修改 =。=
