### ISSUE TITLE
删除PCL内文件夹不要求删除其计算机上的文件夹

### ISSUE THREAD

**Issue by Miaoyww** [Hex-Dragon/PCL2#429]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

我想把它从PCL文件夹列表里删除，而不是把文件夹删除掉

### 原因

添加其他目录的minecraft文件夹时，不小心添加了一个其他的文件夹
不太想让PCL2文件夹列表里有多余的文件夹，用不到，看着还不舒服

**Comment by LTCatt** [comment]
![image](https://user-images.githubusercontent.com/40348278/203379171-a33ca765-4f37-422f-8fe7-dc08f361693d.png)
