### ISSUE TITLE
MyIconButton Theme Red 属性无效

### ISSUE THREAD

**Issue by litwak913** [Hex-Dragon/PCL2#4290]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

将 MyIconButton 的 Theme 属性指定为 Red 时，图标不显示。

### 重现步骤

1、使用附件中的 Custom.txt 作为自定义主页文件。

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16277531/Log1.txt)
[Custom.txt](https://github.com/user-attachments/files/16277543/Custom.txt)

**Comment by allMagicNB** [comment]
？谁告诉你能这么用的？

**Comment by litwak913** [comment]
> ？谁告诉你能这么用的？

https://github.com/Hex-Dragon/PCL2/blob/5bd8ac3870170b0acd4d81934227829f8e79ca84/Plain%20Craft%20Launcher%202/Resources/Custom.xaml#L370C1-L374C30

**Comment by allMagicNB** [comment]
```
[12:13:34.087] 刷新图标按钮动画状态出错：未将对象引用设置到对象的实例。
   在 PCL.ModBase.MyColor..ctor(Brush brush)
   在 PCL.ModBase.MyColor.op_Implicit(Brush bru)
   在 PCL.MyIconButton.RefreshAnim()
错误类型：System.NullReferenceException
```

**Comment by allMagicNB** [comment]
```
EventData="事件|REDButton"
```
？这是什么

**Comment by allMagicNB** [comment]
```svg
M149 873c47 47 101 83 162 109 63 26 130 40 199 40 69 0 136-13 199-40 61-25 115-62 162-109s83-101 109-162c26-63 40-130 40-199 0-69-13-136-40-199-25-61-62-115-109-162-46-46-101-83-162-109C648 13 580 0 511 0s-136 13-199 40c-61 25-115 62-162 109s-83 101-109 162C13 375 0 442 0 511s13 136 40 199c25 61 62 115 109 162zM97 511c0-228 185-414 414-414 228 0 414 185 414 414S740 926 511 926c-228 0-414-185-414-414z M539 244c-8-4-17-7-27-7-9 0-19 2-27 7-16 9-27 27-27 47 0 30 24 54 54 54 30 0 54-24 54-54 0-19-10-37-27-47zM566 732v-284c0-30-24-54-54-54-30 0-54 24-54 54v284c0 30 24 54 54 54 30 0 54-24 54-54z
```

**Comment by litwak913** [comment]
> ```
> M149 873c47 47 101 83 162 109 63 26 130 40 199 40 69 0 136-13 199-40 61-25 115-62 162-109s83-101 109-162c26-63 40-130 40-199 0-69-13-136-40-199-25-61-62-115-109-162-46-46-101-83-162-109C648 13 580 0 511 0s-136 13-199 40c-61 25-115 62-162 109s-83 101-109 162C13 375 0 442 0 511s13 136 40 199c25 61 62 115 109 162zM97 511c0-228 185-414 414-414 228 0 414 185 414 414S740 926 511 926c-228 0-414-185-414-414z M539 244c-8-4-17-7-27-7-9 0-19 2-27 7-16 9-27 27-27 47 0 30 24 54 54 54 30 0 54-24 54-54 0-19-10-37-27-47zM566 732v-284c0-30-24-54-54-54-30 0-54 24-54 54v284c0 30 24 54 54 54 30 0 54-24 54-54z
> ```
> 
> 你确定这是 SVG？

确定，将 Theme 设置为 Color 正常。

**Comment by LTCatt** [comment]
![image](https://github.com/user-attachments/assets/8d6c6a54-e765-4dc9-ae44-a7e629a95060)
已确认。

@allMagicNB 哥们，语气……别开局一个反问句……你就说 “是在哪里有写可以设置成 Red 的？” 语气都比 “？谁告诉你能这么用的？” 好得多，特别是在你没有调查这个 issue 的情况下直接来一句反问真的很扎眼（
