### ISSUE TITLE
[新功能] 增加多行的版本简介

### ISSUE THREAD

**Issue by youzi-2333** [Hex-Dragon/PCL2#4292]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

检索式：`is:issue -label:"· Bug" 游戏版本 AND 多行 AND (简介 OR 介绍) -label:完成`

根据 https://github.com/Hex-Dragon/PCL2/pull/4206#issuecomment-2233267531 以及群里讨论，建议在版本设置页面增加多行简介（过了的话会交 PR）如图。

@Pigeon0v0 @luolinlin768

![27b63a5f79f54fb85554b22ceecec38e](https://github.com/user-attachments/assets/17af4c0e-0ecc-423b-9d77-02b144eb9db0)

### 原因

这个功能可以方便整合包作者填写多行的、具体的简介。

**Comment by Pigeon0v0** [comment]
增加简介以后，原来的版本描述可以取简介第一行

建议格式例：1.20.1｜Fabric 0.15.3｜这是一行描述

**Comment by LTCatt** [comment]
实际上多行描述是很尴尬的一个状态。
玩家在找整合包的时候，看的是视频或者 CurseForge/Modrinth 上的描述，肯定不是整合包文件里的描述。
玩家安装的时候……玩家已经决定玩这个包了，描述显得更无关紧要。
要区别一个版本的话，现在自定义的整合包图标、版本名也已经足够了……

综上，我确实没觉得这玩意儿有啥用……玩家大概并不需要超过一行的内置版本描述。
大家怎么看……？

**Comment by youzi-2333** [comment]
我本来想的是能写些类似攻略的东西（

还有种方案，也类似于多行描述，就是导出整合包的时候把描述写到自定义主页上（不过会导出整合包的人应该会写主页……）而且只有带了启动器文件才能用主页。

整体来说适用人群似乎确实不大。

**Comment by Pigeon0v0** [comment]
有些整合包需要附带类似 QQ 群或者 KOOK 链接一类的东西，这个时候可能需要多行（？

**Comment by allMagicNB** [comment]
冷知识，简介=简短的介绍

**Comment by LTCatt** [comment]
楼上的情况应该都可以用自定义主页更好地解决。
如果玩家用的是 HMCL 的话，HMCL 也不会显示多行描述，这个提议也没用（

那还是关了吧 =。=
