### ISSUE TITLE
增加 Tag：社区测试中 / 社区处理中 / …

### ISSUE THREAD

**Issue by Pigeon0v0** [Hex-Dragon/PCL2#4293]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

如题，增加一些 Tag 用于标识社区状态。目前已有的 Tag 还不能准确标识状态（特别是 PR）。

目前大概需要「社区处理中」和「需要社区测试」这俩，如果大家有别的需要的再留个言（？

### 原因

同描述，方便标识

**Comment by allMagicNB** [comment]
可能还需要个 `等待合并`，标记已审查且无问题，就差合并的 PR。

**Comment by Deep-Dark-Forest** [comment]
> 可能还需要个 `等待合并`，标记已审查且无问题，就差合并的 PR。

这种龙猫一般会贴上处理中吧

**Comment by Pigeon0v0** [comment]
审查通过的会直接 Approve

**Comment by allMagicNB** [comment]
> 审查通过的会直接 Approve

你的 #3940 呢？

**Comment by LTCatt** [comment]
`等待合并` 可以使用 `等待处理` 标签。
添加了 `社区处理中` 标签。
