### ISSUE TITLE
我的世界pcl2启动器可以启动游戏但是进入世界就闪退QWQ

### ISSUE THREAD

**Issue by jdnja** [Hex-Dragon/PCL2#4294]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃基本不是 PCL 的原因，请 **不要** 提交反馈。你可以在论坛或社区找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用 HMCL 启动，HMCL 没有出现问题。** 如果 HMCL 也无法启动就不是 PCL 导致的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我可以让PCL2正常启动MC但是进入MC后MC回立即崩溃

### PCL 错误报告、日志与附件

[错误报告-2024-7-18_18.06.34.zip](https://github.com/user-attachments/files/16281576/-2024-7-18_18.06.34.zip)

### HMCL 启动脚本

这是什么东西

**Comment by allMagicNB** [comment]
这是一个启动器，请尝试用它启动你的游戏。

**Comment by Deep-Dark-Forest** [comment]
点击 [这里](https://hmcl.huangyuhui.net/download) 下载这个启动器后，尝试使用这个启动器启动，看看是否会闪退

**Comment by jdnja** [comment]
PCL2的启动脚本不行吗

**Comment by jdnja** [comment]
> 这是一个启动器，请尝试用它启动你的游戏。

必须要hmc的起动脚本吗

**Comment by Deep-Dark-Forest** [comment]
> > 这是一个启动器，请尝试用它启动你的游戏。
> 
> 必须要hmc的起动脚本吗
> 

是的。我们需要排除非启动器原因

**Comment by Deep-Dark-Forest** [comment]
![Screenshot_20240718_184132.jpg](https://github.com/user-attachments/assets/64721525-e1a8-4cca-abfb-4b8b41e8b49a)

**Comment by mcwuguodadi** [comment]
请仔细阅读检查项.gif
![QQ_1721299212595](https://github.com/user-attachments/assets/7b92fb10-5ae9-43de-848f-f95f52524c63)

**Comment by jdnja** [comment]
我试过了还是一样报错




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Hex-Dragon/PCL2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月18日(星期四) 晚上6:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Hex-Dragon/PCL2] 我的世界pcl2启动器可以启动游戏但是进入世界就闪退QWQ (Issue #4294)





 
请仔细阅读检查项.gif
 QQ_1721299212595.png (view on web)

**Comment by Deep-Dark-Forest** [comment]
> 我试过了还是一样报错

这是因为你使用的模组有问题。这不是 PCL 的问题。

**Comment by mcwuguodadi** [comment]
> 我试过了还是一样报错


这里引用一下检查项的第二条`如果 HMCL 也无法启动就不是 PCL 导致的问题，请 不要 提交反馈。`

**Comment by allMagicNB** [comment]
那就是你游戏的问题了。
