### ISSUE TITLE
下载游戏，在安装forge之类的同时下载其他所需的文件

### ISSUE THREAD

**Issue by guanjiao23456** [Hex-Dragon/PCL2#4295]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在安装forge等的同时下载还没有下载但是需要下载的文件

### 原因

可以节省时间

**Comment by mcwuguodadi** [comment]
你的意思是在安装forge的时候下载类似原版资源文件（？
这个功能不已经有了吗（？
![QQ_1721301109459](https://github.com/user-attachments/assets/42940c4f-61bf-4c0f-9252-3e142f16b8a0)
没太看懂你在表达什么...可以麻烦你举一个例子吗？

**Comment by guanjiao23456** [comment]
?那使我没更新？怎么我的没有

**Comment by Pigeon0v0** [comment]
没看明白，现在应该有了
