### ISSUE TITLE
PCL2启动器 for Linux

### ISSUE THREAD

**Issue by xnull666** [Hex-Dragon/PCL2#4297]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

如题

### 原因

为OIER打造一个Linux下的启动器吧

**Comment by tumuidle** [comment]
![QQ_1721311185829](https://github.com/user-attachments/assets/a4d05342-35e2-4a7a-978b-27a464857df7)

**Comment by hejiehao** [comment]
https://github.com/Hex-Dragon/PCL2/issues/54

**Comment by Pigeon0v0** [comment]
OIer 应该要有能力自己写一个
