### ISSUE TITLE
登录方式希望增加一个‘正版登录与外置登录’选项

### ISSUE THREAD

**Issue by CYun2024** [Hex-Dragon/PCL2#4299]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

通过增加这个选项以便在两个登录方式间快速切换，而不是每次到设置的设置中去调整

### 原因

因为我有一些服务器只支持正版登录，而有另一些好友服只支持外置登录，频繁进入设置切换有点麻烦，而使用两个独立的客户端又感觉没有必要，所以希望增加一个快速切换的选项 awa......

**Comment by Pigeon0v0** [comment]
#57 （投票#58 ）

**Comment by allMagicNB** [comment]
@Pigeon0v0 你再看一看？这指的是版本单独设置选项中的。

**Comment by Pigeon0v0** [comment]
这个应该会直接做成和其他验证方式同优先级...

**Comment by allMagicNB** [comment]
#1034
