### ISSUE TITLE
安装Mod自动安装前置并列出拓展Mod

### ISSUE THREAD

**Issue by maybethisisaname** [Hex-Dragon/PCL2#4303]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

安装一个有前置的Mod后自动安装前置 提供设置控制开关
在一个有拓展的Mod界面显示拓展Mod 默认折叠状态

### 原因

自动安装前置模组能够使安装Mod方面更加方便 节约时间 如果没有这个功能 需要安装mod本体后进入二级界面安装前置
显示拓展模组功能能够快速找到需要的模组 不用花时间去搜索 安装Mod的效率能提升 还不会错过自己可能感兴趣的mod

**Comment by allMagicNB** [comment]
#179

**Comment by allMagicNB** [comment]
拓展 Mod 的话……先给龙猫看看（

**Comment by WForst-Breeze** [comment]
扩展 Mod #953

**Comment by maybethisisaname** [comment]
> 扩展 Mod #953

那好吧 都被提过了...
