### ISSUE TITLE
Runtime Invoke 4693#：线程执行失败：NoDriver calling waveOutRestart

### ISSUE THREAD

**Issue by HOPE-LGNF** [Hex-Dragon/PCL2#4305]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

[22:48:09.431] [Control] 普通弹窗：出现错误
Runtime Invoke 4693#：线程执行失败：NoDriver calling waveOutRestart
   在 PCL.ModMusic._Closure$__._Lambda$__14-0()
   在 PCL.ModBase._Closure$__124-0._Lambda$__0()
错误类型：NAudio.MmException
备注: 我之前在pcl2中设置了音乐自动播放:
**打开启动器自动开始播放
游戏启动自动暂停播放,游戏退出自动开始播放**

### 重现步骤

1、在minecraft 1.18.2切换资源包卡在mojang studios未响应时点击结束进程
2、游戏进程结束,弹出错误弹窗

### 日志与附件

[Log.txt](https://github.com/user-attachments/files/16321450/Log.txt)
[Log1.txt](https://github.com/user-attachments/files/16321452/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16321453/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16321454/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16321455/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16321456/Log5.txt)

**Comment by JingHai-Lingyun** [comment]
#1753 #2348
