### ISSUE TITLE
下载时提示获取任务栏进度出错：集合已修改；可能无法执行枚举操作。

### ISSUE THREAD

**Issue by playerzxk** [Hex-Dragon/PCL2#4307]
### 检查项

- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我在下载1.16.5fabric的Iris1.4.5时，提示我说获取任务栏进度错误

### 重现步骤

1.点击下载，进入mod界面
2.点击版本输入框，输入1.16.5，模组加载器为fabric
3.点击列表第一个iris，下载Iris1.4.5
(注：触发概率可能很低)

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16322707/Log1.txt)

**Comment by allMagicNB** [comment]
```
[08:29:51.206] 获取任务栏进度出错：集合已修改；可能无法执行枚举操作。
   在 System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   在 System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   在 System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   在 PCL.ModNet.LoaderDownload.get_Progress()
   在 PCL.ModLoader.LoaderCombo`1.get_Progress()
   在 PCL.ModLoader.LoaderTaskbarProgressGet()
错误类型：System.InvalidOperationException
```

**Comment by allMagicNB** [comment]
#3771？

**Comment by Silverteal** [comment]
确实是#3771

**Comment by Deep-Dark-Forest** [comment]
Author 使用的 PCL 是最新版，难道那个 bug 复发了？要不 reopen #3881？

**Comment by LTCatt** [comment]
Reopen #3771
