### ISSUE TITLE
Minecraft运行中更新Mod导致“正在更新Mod”无法关闭

### ISSUE THREAD

**Issue by Louis-Harsune** [Hex-Dragon/PCL2#4310]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

当尝试一边运行Minecraft一边更新对应的模组，系统会弹出“文件被进程占用”弹窗，关闭该弹窗后PCL2会提示“替换旧版 Mod 文件时被主动取消：已取消该操作”，然后“正在更新Mod”将无法关闭，只能重启PCL2以恢复Mod管理界面。

### 重现步骤

1、正常启动Minecraft；
2、进入该Minecraft的模组管理界面，并尝试更新模组；
3、系统将弹出“文件被进程占用”弹窗，关闭该弹窗；
4、PCL2提示“替换旧版 Mod 文件时被主动取消：已取消该操作”，随后模组管理界面并未恢复，而是继续卡在“正在更新Mod”弹窗处。

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16323154/Log1.txt)
附系统报错弹窗和PCL2截图：
![image](https://github.com/user-attachments/assets/1ad9b672-ae3b-410f-b481-fe0651c9c786)
![image](https://github.com/user-attachments/assets/1266b8bd-f4c9-467a-bab0-ba2c950ed49a)

**Comment by JingHai-Lingyun** [comment]
[Debug Log1.txt](https://github.com/user-attachments/files/16323161/Log1.txt)
看起来 Finished 了但是 UI 没有做出改变

**Comment by Silverteal** [comment]
此时能否刷新 Mod 管理页面？

**Comment by Louis-Harsune** [comment]
> 此时能否刷新 Mod 管理页面？

不行，必须重启PCL2

**Comment by Louis-Harsune** [comment]
@LTCatt 2.8.7版本仍稳定复现
![image](https://github.com/user-attachments/assets/09052e69-16a0-4142-a134-50678a237ce6)
![image](https://github.com/user-attachments/assets/6ac14fc1-e4c8-4e07-be8d-5083b7b7d0db)

**Comment by LTCatt** [comment]
额，复现的话丢个 log 啊 orz

**Comment by Louis-Harsune** [comment]
第1569行开始：
![image](https://github.com/user-attachments/assets/86dbddc4-36bb-4267-828a-9fdc7620286a)
[Log1.txt](https://github.com/user-attachments/files/17113464/Log1.txt)

**Comment by Louis-Harsune** [comment]
@LTCatt 第1569行开始：
![image](https://github.com/user-attachments/assets/86dbddc4-36bb-4267-828a-9fdc7620286a)
[Log1.txt](https://github.com/user-attachments/files/17113464/Log1.txt)

**Comment by Louis-Harsune** [comment]
识别码：964D-DEEB-6DCD-F69F，谢谢啦！

**Comment by LTCatt** [comment]
你的解锁码：8hGCbzcO/2BjpES83EY1uqdFn2Os2DaD
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
