### ISSUE TITLE
能否加一个一键更新mod

### ISSUE THREAD

**Issue by teyechengyu** [Hex-Dragon/PCL2#4315]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

加一个一键更新mod，在版本管理中，可以选择更新的版本，在更新前检查mod是否有对应版本的，并向用户显示能更新的mod

### 原因

我在与朋友联机游玩mc时，常常会出现想玩新版本，却发现还需要把mod1个1个的找出来，然后更新，这样费时费力，最后只有妥协玩老版本

**Comment by lactobionicAcid** [comment]
该功能已实装，在 Mod 管理 → 全选 → 更新 即可更新全部 Mod 。
感谢您的反馈。

**Comment by RimacC2-EV** [comment]
我记得我之前有这么做过（直接拖动非想玩版本的Mod到想玩的版本的Mod文件夹并一键更新），结果成功了・・・・・・没有去刻意重下・・・・・・
________________________________
From: yeye ***@***.***>
Sent: Sunday, July 21, 2024 19:05
To: Hex-Dragon/PCL2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Hex-Dragon/PCL2] 能否加一个一键更新mod (Issue #4315)


检查项

  *    我已在 Issues 页面<https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+> 和 常见&难检反馈及问题列表<https://github.com/Hex-Dragon/PCL2/discussions/1930> 中搜索，确认了这一提案未被提交过。
  *    我已查看 功能投票页面<https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/>，确认了这一提案未在投票列表中。
  *    我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

描述

加一个一键更新mod，在版本管理中，可以选择更新的版本，在更新前检查mod是否有对应版本的，并向用户显示能更新的mod

原因

我在与朋友联机游玩mc时，常常会出现想玩新版本，却发现还需要把mod1个1个的找出来，然后更新，这样费时费力，最后只有妥协玩老版本

―

**Comment by allMagicNB** [comment]
全选后更新。

**Comment by Ad-closeNN** [comment]
不过有些Mod并没适配新版本...跨大版本的话可能会报错一大堆（如果没适配的Mod很多的话）
应该更新后再提示那些无需更新并提示是否去查看适配这个版本

**Comment by wuyuncheng-26** [comment]
我的选择是，做一下备份，然后把 Mod 全选更新
接下来启动游戏，大概率是会有报错的，估计是因为 Fabric 和 Fabric API 版本太低了
于是来到备份，全选并把报错的模组点掉，接着更新即可
未来能够更新 Fabric 和 Fabric API 就方便些了，直接无脑更（

**Comment by teyechengyu** [comment]
> 不过有些Mod并没适配新版本...跨大版本的话可能会报错一大堆（如果没适配的Mod很多的话） 应该更新后再提示那些无需更新并提示是否去查看适配这个版本

我的意思就是这个，不好意思我在这篇文章表达的不够清楚，可能重点不是很明确（因为这是抄我以前还没出一键更新时候写的），我想表达的重点就是，现在的一键升级升完后大概率报错，所以可以在升级之前先询问用户要升级到哪个版本，再检查mod是否有这个版本的，再告诉用户哪个mod可以更新，现在你们的讨论让我想到可以把更新api放到第一步（即优先级最高）

**Comment by Pigeon0v0** [comment]
之前有过讨论，更新 Mod 本来就是不推荐的行为
