### ISSUE TITLE
优化一键更新mod

### ISSUE THREAD

**Issue by teyechengyu** [Hex-Dragon/PCL2#4316]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

我建议可以将一键更新优化为：在更新前先询问用户要更新到哪个版本（并且我觉得“更新”应该既可以更新也可以后退）然后检查所选择的mod在用户选择的版本是否存在，能否更新，并将能更新的mod展示给用户看。基于许多用户反应更新后大概率报错，我猜测可能是API没更新，所以希望使api的更新优先级最高

### 原因

这项优化是基于许多玩家都反应会出现报错所提出的

**Comment by allMagicNB** [comment]
那就叫用户别更新，更新 Mod 原本就是不推荐的行为。

**Comment by JingHai-Lingyun** [comment]
询问版本：#4083 （另一种解释 https://github.com/Hex-Dragon/PCL2/issues/4238#issuecomment-2225798607 ）
后退的话暂时没有找到相关 Issue，鉴于本 Issue 耦合了过多条目，如果你需要的话，请单独开一个 Issue，但我感觉大概率不会做

---

更新 Fabric API：你可以直接更新那个模组
另一种解释 → 更新 Fabric：#220，请到 #227 投票
