### ISSUE TITLE
[Bug] 极低概率下 Mod 检索页面的底部可以继续下滑

### ISSUE THREAD

**Issue by wuliaodexiaoluo** [Hex-Dragon/PCL2#4318]
### 检查项

- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如图
![image](https://github.com/user-attachments/assets/3d9ccf0d-b8ba-4ed9-8f3c-e61bf3d67212)
对比正常情况:
![image](https://github.com/user-attachments/assets/2dfaa8f1-7ec0-4184-9257-c67ac8c25ca6)

### 重现步骤

下载 - Mod 页面

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16326995/Log1.txt)

**Comment by wuliaodexiaoluo** [comment]
> Is there any operation that can be reproduced? (Tried several times but could not reproduce :/)

The probability is extremely low and it would take a European to reproduce it (referring to someone with great luck)

**Comment by LTCatt** [comment]
也许是 #3671 的副作用。
顺带一提 #3671 不是 half fixed，压根还没修呢。

**Comment by LTCatt** [comment]
怀疑是 #1624 正好卡在了透明度接近 0 的时候
