### ISSUE TITLE
修改赞助作者按钮的链接

### ISSUE THREAD

**Issue by kuankqaq** [Hex-Dragon/PCL2#4319]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

修改赞助作者按钮的链接至b站主页或其他赞助平台

### 原因

爱发电平台疑似被封
无法访问网站

**Comment by JingHai-Lingyun** [comment]
#4721
