### ISSUE TITLE
崩溃提示优化：从 JSON 对象中尝试获取模组名字

### ISSUE THREAD

**Issue by lingyunawa** [Hex-Dragon/PCL2#4321]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

![ed5e2ca19fcc6286ad7be450b765f965](https://github.com/user-attachments/assets/abf0079e-0ef2-47db-86d8-c57f0e9d5f98)
[crash-2024-07-22_23.31.53-client.txt](https://github.com/user-attachments/files/16336337/crash-2024-07-22_23.31.53-client.txt)

这个 Mod 名显示…… 也不知道 NeoForge 为什么会往崩溃日志里面写 JSON 对象描述模组……

**Comment by JingHai-Lingyun** [comment]
Maybe not NeoForge-specific (*No Testing). My NeoForge version is 47.1.106

**Comment by JingHai-Lingyun** [comment]
Let me post it.

**Comment by LTCatt** [comment]
其实是正则有问题
![image](https://github.com/user-attachments/assets/7a140a5c-9cbb-4c8c-813f-60be28c8960b)
