### ISSUE TITLE
添加重启PCL按钮

### ISSUE THREAD

**Issue by FQO3** [Hex-Dragon/PCL2#4325]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在主页面或者某个方便的地方添加重启pcl按键

### 原因

因为minecraft很容易出现会话无效的提示，要求重启启动器和minecraft，每次我都要在文件夹翻很久找到pcl重新启动

**Comment by JingHai-Lingyun** [comment]
重启……我想不到有什么作用，通常来讲无效会话是由于启动时间过长导致 access_token 过期导致的。

**Comment by FQO3** [comment]
> 重启……我想不到有什么作用，通常来讲无效会话是由于启动时间过长导致 access_token 过期导致的。

就是为了解决access_token过期问题，有的时候长时间打开mc会导致这个问题，而唯一的办法就是重启pcl……但他真的很麻烦，我要从我的一堆目录下找到pcl的启动器，而无法从启动器内部直接解决

**Comment by Ad-closeNN** [comment]
“千万别点”需要这个，但是快捷方式确实能用

**Comment by LTCatt** [comment]
如果出现会话无效的提示，先尝试重启 MC，如果照旧请上传日志并提交为 issue。
PCL 应该会在每次启动时验证 access token 是否过期。

**Comment by FQO3** [comment]
我今天晚上测试一下，挂一晚上第二天应该就会出现过期。之前我试过必须重启pcl才可以（大概几个月前

**Comment by Pigeon0v0** [comment]
鉴于需要另开 Issue，先关了吧...

**Comment by Deep-Dark-Forest** [comment]
？龙猫没说过拒绝这个 issue 中提及的新功能

**Comment by JingHai-Lingyun** [comment]
AccessToken 不刷新已经另外交反馈（#4333）了，这个帖子目前需要龙猫确认的是是否要制作重启按钮

**Comment by LTCatt** [comment]
按 #4333 作为 bug 修，不加重启按钮 =。=

**Comment by allMagicNB** [comment]
#4333 修了之后就没必要了。
