### ISSUE TITLE
支持在自动安装时从多个下载源获取 Fabric API 等 Mod 信息

### ISSUE THREAD

**Issue by ZhangJinyuJerry** [Hex-Dragon/PCL2#4327]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

Fabric API
获取版本列表失败:连接服务器超时,已接收0B(https://api.modrinth.com/v2/project/fabric-api)

但我打开浏览器是可以正常显示的：
![屏幕截图 2024-07-24 135311](https://github.com/user-attachments/assets/13811acf-a8a9-4c7c-95f3-dbd9303941f6)

HMCL：
![屏幕截图 2024-07-24 140303](https://github.com/user-attachments/assets/2baab50b-3647-4e80-9c50-56e703a55839)

### 重现步骤

1、点击下载
2、随便点击一个版本
3、附加安装fabric
4、稍等一会，可以看到fabric api上有提示

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16357767/Log1.txt)
line 892:[13:48:30.052] [Net] 获取网络结果：https://api.modrinth.com/v2/project/fabric-api，超时 10000ms，要求 json

**Comment by JingHai-Lingyun** [comment]
用 PCL 的时候网络抽了罢，我这里一切正常

**Comment by Ad-closeNN** [comment]
https://github.com/Hex-Dragon/PCL2/discussions/4326#discussioncomment-10133622

**Comment by hejiehao** [comment]
> 日志与附件
[Log1.txt](https://github.com/user-attachments/files/16357767/Log1.txt)

Not Found

**Comment by JingHai-Lingyun** [comment]
#4338 同样报告此问题，Reopen 此 Issue

**Comment by allMagicNB** [comment]
怀疑是 UA 头问题。

**Comment by LTCatt** [comment]
两个反馈都没有有效日志……
如果反馈者能**稳定复现**才考虑是 Bug。

**Comment by JingHai-Lingyun** [comment]
*连通性不好* means the api url has DNS analysis or Connection Blockage problem. It may cause this issue in some area in China.

**Comment by ZhangJinyuJerry** [comment]
我又试了次可以证明
[Log1.txt](https://github.com/user-attachments/files/16367872/Log1.txt)

**Comment by ZhangJinyuJerry** [comment]
https://github.com/user-attachments/assets/dd7bcdaf-211d-42de-8961-9f3724c72b38

**Comment by ZhangJinyuJerry** [comment]
> > 怀疑是 UA 头问题。
> 
> 但并非所有用户都会遇到此问题。我更倾向于凌云的结论，_即连通性不好_。
> 
> 我在 _ITDOG_ 上检查了 Modrinth 的域名，注意到大陆上的某些地区/运营商经常遇到连接超时。

是的，正如你所说，我也试着用 _ITDOG_ 测试了一下，发现：
- 安徽滁州
- 福建泉州
- 江苏徐州
- 广东广州

**Comment by ZhangJinyuJerry** [comment]
> > 怀疑是 UA 头问题。
> 
> 但并非所有用户都会遇到此问题。我更倾向于凌云的结论，_即连通性不好_。
> 
> 我在 _ITDOG_ 上检查了 Modrinth 的域名，注意到大陆上的某些地区/运营商经常遇到连接超时。

是的，正如你所说，我也试着用 _ITDOG_ 测试了一下 _modrinth.com_ ，发现：
- 安徽滁州
- 福建泉州
- 江苏徐州
- 广东广州
- 吉林长春
- 贵州贵阳
- 江苏苏州
- 江西南昌
- 河北石家庄
- 云南昆明
- 黑龙江哈尔滨

### 在 _ITDOG_ 上 _ping_ _modrinth.com_ 的结果
**共11处丢包率100%**，并且可能所有获取失败的运行商是**中国电信**，以上11处运营商**都为中国电信**。并且只有**21处**运营商是中国电信运营商丢包率为0%，**其他运营商**所有丢包率**都等于0%**

![image](https://github.com/user-attachments/assets/6966b3e0-f74e-43fb-b74c-65d43f619620)

**Comment by ZhangJinyuJerry** [comment]
上面图2报403的是因为没通过人机测试

**Comment by allMagicNB** [comment]
草，JS 鉴权。

**Comment by LTCatt** [comment]
我觉得可以考虑把 Mod 部分的列表加载都同时用 CurseForge、Modrinth 和国内镜像源三个源来解决……

**Comment by Pigeon0v0** [comment]
#4291 Related

**Comment by ZhangJinyuJerry** [comment]
ok, 我随时等待修好

**Comment by HiTech0926** [comment]
我今天也遇到这个问题了，打开modrinth官网发现是cloudflare的防护页面。在浏览器等待该页面检测完毕，PCL2就能正常获取了。

**Comment by allMagicNB** [comment]
？谁家傻逼给 API 加 JS 鉴权

**Comment by HiTech0926** [comment]
> ？谁家傻逼给 API 加 JS 鉴权

应该不是刻意加的，cloudflare会对所有子域名生效。。。

**Comment by Pigeon0v0** [comment]
不会给 API 加 JavaScript 鉴权的...鉴权不了一点...

**Comment by allMagicNB** [comment]
……那就是玄学？

**Comment by Ad-closeNN** [comment]
![image](https://github.com/user-attachments/assets/6a00d3ff-8b13-407c-880f-0fb0dc526963)

**Comment by LTCatt** [comment]
如果谁遇到了这个问题，可以向 modrinth 交个反馈？我这里没法复现所以没法 orz

**Comment by Pigeon0v0** [comment]
建议更改标题：支持在自动安装时从多个下载源获取 Fabric API

**Comment by z0z0r4** [comment]
modrinth 不会也没有给 api.modrinth.com 添加 CF 盾

> 应该不是刻意加的，cloudflare会对所有子域名生效。。。

cloudflare 也不会自动对所有 DNS 解析生效，只有选择需要代理的才会生效

> [05:58:39.206] 加载线程 Fabric API List Loader (47) 发生运行时错误：连接服务器超时，已接收 0 B（https://api.modrinth.com/v2/project/fabric-api）

不是 cloudflare 的防护造成的，显然是根本没连上服务器...

应该被测试的不是 modrinth.com 而是 api.modrinth.com，应该使用的也不应该是 在线 Ping 而是 网站测速

确实有部分电信地区无法访问 api.modrinth.com

![image](https://github.com/user-attachments/assets/0138fb1e-dbb6-4d2f-a66d-76775ff1f6fa)

实际上来说，向 modrinth 提交反馈没有任何意义...

实测 [staging-api.modrinth.com](https://staging-api.modrinth.com/) 同样被这些地区屏蔽

~~相比之下 Curseforge 的表现是全绿的，AWS~~

**Comment by HiTech0926** [comment]
> modrinth 不会也没有给 api.modrinth.com 添加 CF 盾
> 
> > 应该不是刻意加的，cloudflare会对所有子域名生效。。。
> 
> cloudflare 也不会自动对所有 DNS 解析生效，只有选择需要代理的才会生效
> 
> > [05:58:39.206] 加载线程 Fabric API List Loader (47) 发生运行时错误：连接服务器超时，已接收 0 B（[https://api.modrinth.com/v2/project/fabric-api）](https://api.modrinth.com/v2/project/fabric-api%EF%BC%89)
> 
> 不是 cloudflare 的防护造成的，显然是根本没连上服务器...
> 
> 应该被测试的不是 modrinth.com 而是 api.modrinth.com，应该使用的也不应该是 在线 Ping 而是 网站测速
> 
> 确实有部分电信地区无法访问 api.modrinth.com
> 
> ![image](https://private-user-images.githubusercontent.com/78744121/352529010-0138fb1e-dbb6-4d2f-a66d-76775ff1f6fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwMDA2NTcsIm5iZiI6MTcyMjAwMDM1NywicGF0aCI6Ii83ODc0NDEyMS8zNTI1MjkwMTAtMDEzOGZiMWUtZGJiNi00ZDJmLWE2NmQtNzY3NzVmZjFmNmZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDEzMjU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxMWVjZDhmZGNkZTg1YWFmYWRjYmY2YmYxNmIxNWU0ZTExMzMxMGQzYWE3ZTg3ZjNlYzU2M2M4ZDI5MzljZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zKmFrwNtPXwareBKj7bQ6gQ6rrDd-s4RyU7ORZG2NsI)
> 
> 实际上来说，向 modrinth 提交反馈没有任何意义...
> 
> 实测 [staging-api.modrinth.com](https://staging-api.modrinth.com/) 同样被这些地区屏蔽
> 
> ~相比之下 Curseforge 的表现是全绿的，AWS~

但是我一直连不上的时候，打开网页发现是cf的js鉴权。等点了验证后发现刚好PCL也加载出来了啊……以前modrinth没有cf鉴权的

**Comment by HiTech0926** [comment]
> modrinth.com 有 CF 盾，**api.modrinth.com** 没有
> 
> 请不要，不要通过 modrinth.com 来检查 **api.modrinth.com**

@LTCatt 
模组下载也会出问题，可以基本确定就是modrinth的锅
![image](https://github.com/user-attachments/assets/d4f89340-54ea-46a0-8ada-04fe48778f1c)
此时访问modrinth是验证
![image](https://github.com/user-attachments/assets/fa1d876a-201f-4caf-9403-0a3b99f0801c)
过完验证，刷新pcl2，又能加载出来了
![image](https://github.com/user-attachments/assets/695ba41b-8057-4f3c-a9c0-7539efadf959)

**Comment by JingHai-Lingyun** [comment]
虽然事实体现出了通过 **modrinth.com** 的 CF Captcha 有助于访问 **api.modrinth.com**。
但从技术角度来说这非常奇怪，因为 api 接口是不可能套 Captcha 的

**Comment by LTCatt** [comment]
如果你觉得是 Modrinth 的问题，可以向 support@modrinth.com 发邮件，并附上这个 issue 的链接……
但这不是 PCL 导致的，所以我没法做点啥。

**Comment by HiTech0926** [comment]
> @HiTech0926
> 
> I tested it on my side and found that this may not be the case. Maybe your situation is just a coincidence? 🤔
> 
> And as @z0z0r4 said, will trigger Cloudflare verification, but will not.`modrinth.com``api.modrinth.com`

Cloudflare Captcha appears in China, but it does not appear when I open a VPN outside of mainland China.
在国内会出现Cloudflare Captcha，当我开启非大陆地区的VPN时，并不会出现Cloudflare Captcha。

**Comment by HiTech0926** [comment]
测试国内访问应该是没问题的
![QQ_1722015377659](https://github.com/user-attachments/assets/53268c6f-bb27-42b0-9137-c4f4bb67a622)
但是在电信网络中却出现了许多失败，其他网络就只有2个失败
![QQ_1722015410708](https://github.com/user-attachments/assets/25239bf9-b496-481c-a94e-2cb9df81edfc)
如下图，我所处地区山东青岛，测出来是失败，我这边也是失败
![image](https://github.com/user-attachments/assets/0550cd88-7f01-42d9-9fc3-47c64d1f0725)
![image](https://github.com/user-attachments/assets/12a9a669-fdeb-489f-b93e-5877452f63ef)


难道……和电信还有关系？

**Comment by JingHai-Lingyun** [comment]
我给 Modrinth Support 发了一封询问邮件，看看他们那边会如何回复。

**Comment by z0z0r4** [comment]
> > modrinth.com 有 CF 盾，**api.modrinth.com** 没有
> > 
> > 请不要，不要通过 modrinth.com 来检查 **api.modrinth.com**
> 
> @LTCatt 
> 模组下载也会出问题，可以基本确定就是modrinth的锅
> ![image](https://github.com/user-attachments/assets/d4f89340-54ea-46a0-8ada-04fe48778f1c)
> 此时访问modrinth是验证
> ![image](https://github.com/user-attachments/assets/fa1d876a-201f-4caf-9403-0a3b99f0801c)
> 过完验证，刷新pcl2，又能加载出来了
> ![image](https://github.com/user-attachments/assets/695ba41b-8057-4f3c-a9c0-7539efadf959)
> 
> 
> 

请你试试看访问 api.modrinth.com 而不是 modrinth.com

**Comment by ZhangJinyuJerry** [comment]
> 如果你觉得是 Modrinth 的问题，可以向 [support@modrinth.com](mailto:support@modrinth.com) 发邮件，并附上这个 issue 的链接...... 但这不是 PCL 导致的，所以我没法做点啥。

我来试试发一下

**Comment by ZhangJinyuJerry** [comment]
我前天去我老家，在我老家那边是正常的

**Comment by ZhangJinyuJerry** [comment]
![image](https://github.com/user-attachments/assets/baadc6c7-1284-45cc-972a-df0e1c65e6a0)

**Comment by ZhangJinyuJerry** [comment]
可能是验证了，只不过响应时间超过10s，就当做连接超时了

**Comment by ZhangJinyuJerry** [comment]
好了a   :)
