### ISSUE TITLE
添加全局快捷键

### ISSUE THREAD

**Issue by InfinityWolfly** [Hex-Dragon/PCL2#4328]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

一个很简单的想法：如果我只需要在启动界面按一下空格就可以启动游戏就好了。
可以很简单添加一个空格启动游戏的功能，
或者说给一个全局快捷键配置文件也可……

### 原因

我很懒。不想动鼠标。

**Comment by LTCatt** [comment]
按回车（
