### ISSUE TITLE
下载线程超出限制

### ISSUE THREAD

**Issue by JingHai-Lingyun** [Hex-Dragon/PCL2#4330]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/user-attachments/assets/05386aeb-8107-443d-b11a-a6c550c7d373)

### 重现步骤

在下载文件的时候调低下载线程数量
观察下载任务页

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16359545/Log1.txt)

**Comment by wuliaodexiaoluo** [comment]
这总不能中断下载吧，每个线程都有 Range 而且龙猫明确表示不考虑支持断点续传，现在切线程重新处理=断点续传，一周之内绝对有一堆人要求写断点续传

**Comment by JingHai-Lingyun** [comment]
看起来是对的，但是这个 UI…… 我感觉有点反直觉……

**Comment by allMagicNB** [comment]
事实上，多线程下载就是通过断点续传实现的。

**Comment by wuliaodexiaoluo** [comment]
> 事实上，多线程下载就是通过断点续传实现的。

虽然但是这样写就成用户认为的断点续传了，我们总不能去和用户谈技术吧，先不考虑懂不懂什么的，你谈完他们反而认为早就实现好的东西不愿意写，评价直接降一大截（

**Comment by allMagicNB** [comment]
你们聊半天都不换个 Label =。=

**Comment by LTCatt** [comment]
中途降低设置不在考虑范围内（
