### ISSUE TITLE
在littleskin登录时没有正版账户的披风选择

### ISSUE THREAD

**Issue by 4864185** [Hex-Dragon/PCL2#4335]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

更新之后以前的在little skin登录界面的正版披风选择按钮不见了

### 重现步骤

登录little skin之后在左边的按钮少了披风按钮

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16363397/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16363398/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16363399/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16363400/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16363401/Log5.txt)

**Comment by JingHai-Lingyun** [comment]
这是预期中的行为：LittleSkin 登陆时使用的角色皮肤/披风由提供服务的皮肤站决定

**Comment by Ad-closeNN** [comment]
> 回味了一下…… 你是不是想要一个快速到达皮肤站的按钮？如果是那样的话另外开一个 Issue，这个 Issue 主题和正文都不匹配。

点这个是能直接到皮肤站的user界面
![image](https://github.com/user-attachments/assets/a5d28ef2-2016-41c6-a8c5-b3faea6e0c12)
