### ISSUE TITLE
下载Mod界面标注对于不同运行环境的适用情况

### ISSUE THREAD

**Issue by XeF2i** [Hex-Dragon/PCL2#4336]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在mod详细信息一栏（即下载量、mod源的一栏）新增一项标注该mod对于服务端/客户端的适用情况，可以从MC百科详情栏的“运行环境”中获取
如果有能力也可以在mod筛选中添加快速筛选不同运行环境的必需/可装mod

### 原因

在配置/加入服务器时可以更方便地了解到哪项mod是对服务端/客户端无效的，以便于防止下载多余mod或缺失必需mod

**Comment by JingHai-Lingyun** [comment]
#2689 类似
