### ISSUE TITLE
可以通过修改日期获取欧皇彩隐藏主题

### ISSUE THREAD

**Issue by A20210110** [Hex-Dragon/PCL2#4337]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

通过修改日期获取欧皇彩隐藏主题

### 重现步骤

修改日期
点击今日人品
如果人品值不是100
继续修改的日期
再次点击今日人品
以此类推

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16364352/Log1.txt)

**Comment by lactobionicAcid** [comment]
这是刻意设计的吧......

**Comment by JingHai-Lingyun** [comment]
这应该是意料内的事情，PCL 的时间来自设备系统

> 你想被刷这个主题的骂？过河拆桥呢？

语气友好一点，谢谢。

**Comment by Pigeon0v0** [comment]
先关了，这没法修

**Comment by allMagicNB** [comment]
没事，没重呢

**Comment by allMagicNB** [comment]
> 先关了，这没法修

事实上只要 PCL 在打开时缓存时间信息变量也能做到。

**Comment by Ad-closeNN** [comment]
如果不用本地的话难道用NTP服务器手动校准时间？
那断网的怎么办，最后只能被迫使用本地时间...

**Comment by LTCatt** [comment]
这是刻意的游戏设计.jpg
