### ISSUE TITLE
下载fabric时fabricAPI无法被获取显示服务器超时 

### ISSUE THREAD

**Issue by yangxianshuo666** [Hex-Dragon/PCL2#4338]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

点击fabric fabricAPI一栏显示获取版本列表失败：连接服务器超时字样 

### 重现步骤

正常安装fabric

### 日志与附件

0

**Comment by JingHai-Lingyun** [comment]
先别关

**Comment by allMagicNB** [comment]
发日志

**Comment by allMagicNB** [comment]
怪，Reopen 哪个？

**Comment by JingHai-Lingyun** [comment]
请到 #4338 补充你的日志，感谢反馈。

**Comment by JingHai-Lingyun** [comment]
擦记混了
