### ISSUE TITLE
关于afdian.net无法访问的优化改动

### ISSUE THREAD

**Issue by 19707677707** [Hex-Dragon/PCL2#4340]
### 检查项

- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

将启动器赞助功能所指向的链接中afdian.net改为ifdian.net或者afdian.com

### 原因

（示例）
这项优化让我可以更方便地xxxx。
如果没有这项优化，我每次都必须xxxx，让操作变得很麻烦。
如果没有这项优化，每一次赞助或者领取赞助福利都需要手动修改地址，这项优化可以让使用者很方便的去使用赞助功能

**Comment by JingHai-Lingyun** [comment]
https://github.com/Hex-Dragon/PCL2/issues/4271
