### ISSUE TITLE
无法更改版本图标

### ISSUE THREAD

**Issue by shuguit** [Hex-Dragon/PCL2#4341]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

窗口直接报错：
在PCL.PageVersionOverrall.ComboDisplayLogo_SelectionChanged(Object sender,SelectionCangedEventArgs e)
错误类型：SystemUnauthorizedAccessException

### 重现步骤

1.在版本选择中，选择一个相应jar文件，json文件还有Setup.ini中的info,VersionFabric,VersionOptFine,VesionForge,VersionNeoForge,VersionOriginal变量都更改过的版本。
2.点击此版本的版本设置。
3.点击‘图标’，点‘自定义’。
4.把图片的网页链接复制到输入框，回车。
5.然后会发现此版本无法修改图标。

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16370619/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16370621/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16370623/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16370624/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16370626/Log5.txt)

**Comment by Ad-closeNN** [comment]
尝试使用管理员权限重新启动 PCL 并复现

**Comment by allMagicNB** [comment]
> 尝试使用管理员权限重新启动 PCL 并复现
> 右键 PCL，选择以管理员身份运行。

？

**Comment by hejiehao** [comment]
图片的网页链接是什么？

**Comment by shuguit** [comment]
尝试过了，以管理员身份运行的话，虽然更改成功了，但自此以后，每次更改图标都会更改成功然后报错
________________________________
发件人: Ad-closeNN ***@***.***>
发送时间: 2024年7月25日 12:55
收件人: Hex-Dragon/PCL2 ***@***.***>
抄送: shuguit ***@***.***>; Author ***@***.***>
主题: Re: [Hex-Dragon/PCL2] 无法更改版本图标 (Issue #4341)


尝试使用管理员权限重新启动 PCL 并复现
右键 PCL，选择以管理员身份运行。

―

**Comment by allMagicNB** [comment]
那就权限问题。

**Comment by hejiehao** [comment]
成功复现
[Log1.txt](https://github.com/user-attachments/files/16370741/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16370742/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16370744/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16370745/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16370746/Log5.txt)
<details><summary>图片</summary>
<p>

![image](https://github.com/user-attachments/assets/deb0560e-f6c5-46c9-8cbc-09c00e673ebe)
![image](https://github.com/user-attachments/assets/8e40dace-836a-4d7b-8252-2311d895010f)

</p>
</details>

**Comment by Ad-closeNN** [comment]
`C:\Users\a1816\AppData\Roaming\.minecraft\`下权限改为 Everyone 所有权限能解决吗
如果没法解决的话就在快捷方式启用管理员权限
![image](https://github.com/user-attachments/assets/2915b799-86ee-4d05-b880-fa235d6f305a)

**Comment by allMagicNB** [comment]
怪。体积小点的图片倒是可以。

**Comment by LTCatt** [comment]
我没法复现，推测是 Windows 防火墙把网络文件拦了。
考虑到在这里输入网络链接不是预期行为，或许没啥办法也没啥必要修？

**Comment by LTCatt** [comment]
Windows 防火墙可能会自动地把从网络下载的文件挂上只读或者添加其他访问限制。我怀疑是因为我把防火墙宰了，所以我这没复现出来……
后缀选择问题是 Windows 文件选择对话框的原生行为，我不太觉得有办法……
