### ISSUE TITLE
支持在Fabric/Quilt下自动安装Sodium和Iris Shaders（如果兼容的话）

### ISSUE THREAD

**Issue by i486-DX9** [Hex-Dragon/PCL2#4344]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

在”自动安装“中选择Fabric或Quilt后隐藏OptiFine选项，然后出现2个选项，一个是Sodium，另一个是Iris Shaders，两个都可以自己选择版本并在安装Minecraft的同时自动安装Sodium和Iris。（启动器会自动检查这两个有没有对要安装的MC版本具有兼容性，如不兼容将变为”没有可用版本“）

### 原因

在目前版本的PCL2中玩家可以在“下载→Mod”下自己安装Sodium和Iris（这比跑到Modrinth下自己下载方便）。
但是这依然不够方便，因为玩家还要确认下载，不如干脆一步到位。

**Comment by JingHai-Lingyun** [comment]
#311

**Comment by i486-DX9** [comment]
:(
