### ISSUE TITLE
将启动参数中-Dlog4j2.formatMsgNoLookups=true中的true改成True

### ISSUE THREAD

**Issue by Hill23333** [Hex-Dragon/PCL2#4347]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

如题，就是这么简单...
只是强迫症犯了，希望可以改一下，改成
```
-Dlog4j2.formatMsgNoLookups=True
```

### 原因

强迫症而已...其他的都是True就这一个是true 看着真的很不舒服
我自己试过了，改成True不影响游戏启动

**Comment by JingHai-Lingyun** [comment]
妈呀……

**Comment by LTCatt** [comment]
java 的 true 就是不大写的 =。=

**Comment by Hill23333** [comment]
那把其他几个True改成true也行 ，至少统一一下...
不过java里面true默认不大写我真的不知道，抱歉...
