### ISSUE TITLE
自定义窗口大小失效

### ISSUE THREAD

**Issue by zhuluzyy** [Hex-Dragon/PCL2#4350]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

全屏进入游戏后退出，pcl窗口自定义大小失效.
另外在启动游戏时会有各种灵异事件，鼠标指针变大，windos开始菜单变小.游戏启动成功后灵异事件消失.

### 重现步骤

在pcl窗口边缘拖动调整大小，在设置，游戏，启动选项，窗口大小改为全屏，启动器可见性设为游戏启动后最小化，进入游戏退出后pcl窗口恢复默认大小

### 日志与附件

[Log3.txt](https://github.com/user-attachments/files/16389696/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16389697/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16389698/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/16389699/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16389700/Log2.txt)
[演示视频(请删除后缀名中的txt).z01.txt](https://github.com/user-attachments/files/16389
[演示视频.zip](https://github.com/user-attachments/files/16389877/default.zip)
875/txt.z01.txt)
演示视频太大,分卷压缩

**Comment by JingHai-Lingyun** [comment]
补充你的 #4114 之后我们会重新开启那个。

**Comment by allMagicNB** [comment]
#4114
