### ISSUE TITLE
在启动器日志中输出 Windows 版本

### ISSUE THREAD

**Issue by Pigeon0v0** [Hex-Dragon/PCL2#4351]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在启动器日志中输出 Windows 版本，如 `Windows 11 专业工作站版 x64 23H2 Build 22635.xxxx` 

可以直接从系统拿数据？

### 原因

有助于在各种情况下解决问题，比如游戏因为编码问题崩溃时，可以直接判断是否可以引导去关闭系统 UTF-8 选项。

**Comment by Ad-closeNN** [comment]
貌似还得解决一下4332的问题（？
- #4332
