### ISSUE TITLE
存档和mod文件消失

### ISSUE THREAD

**Issue by Aofeng7** [Hex-Dragon/PCL2#4352]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

求助！所有存档消失。进入pcl后之前的主题被换为默认主题，许多设置变为默认，版本隔离关闭（一直开启没有手动关闭过）。打开游戏（1.21）发现mod版本错误。我下载了1.20.1和1.21两个版本，1.21存档和mod文件夹变为1.20.1中的文件。原1.21中的所有存档和mod消失.

### 重现步骤

未知

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16391014/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16391016/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16391017/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16391019/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16391020/Log5.txt)

**Comment by Aofeng7** [comment]
没有更换硬件。有更换网卡属性中的信道宽度2.4到5GHz

**Comment by Aofeng7** [comment]
[Log1.txt](https://github.com/user-attachments/files/16391145/Log1.txt)

**Comment by Ad-closeNN** [comment]
难不成1.20.1的关了版本隔离，1.21的开了版本隔离，现在1.21也没隔离了，只能用1.20.1的东西了？

**Comment by Pigeon0v0** [comment]
这不可能是 PCL 自己干的...

你可以开一个 Discussion 进行讨论，这个 Issue 暂时先关闭。如果确认是 PCL 存在的 Bug 再打开。

**Comment by Aofeng7** [comment]
好的谢谢
