### ISSUE TITLE
PCL2无法访问Modrinth

### ISSUE THREAD

**Issue by lee750717** [Hex-Dragon/PCL2#4354]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

PCL2无法访问Modrinth，即使退出重进，即使刷新
![image](https://github.com/user-attachments/assets/8d2019ef-2cf5-434f-891b-b27294d33379)，但我可以正常访问Modrnth
![image](https://github.com/user-attachments/assets/5211b423-27de-484f-bd98-e5bccf93b562)

### 重现步骤

搜索任意mod

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16392065/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16392067/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16392069/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16392071/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16392072/Log5.txt)

**Comment by allMagicNB** [comment]
能否打开下这个网页？
api.modrinth.com

**Comment by lee750717** [comment]
能
![image](https://github.com/user-attachments/assets/120fda97-5c11-4a09-915f-73d4391119ad)

**Comment by allMagicNB** [comment]
再搜索试试？

**Comment by Ad-closeNN** [comment]
难道PCL客户端请求的和浏览器的不一样（？

**Comment by lee750717** [comment]
等等，不是这pcl2耍我呢，我刚刚刷新10遍重进1遍不行，现在行了

**Comment by lee750717** [comment]
![image](https://github.com/user-attachments/assets/90440c8f-e599-4f53-9f62-3b16396b9e94)

**Comment by allMagicNB** [comment]
@lee750717 你在打开 api.modrinth.com 的时候有没有人机验证？

**Comment by lee750717** [comment]
没有

**Comment by lee750717** [comment]
没有

**Comment by lee750717** [comment]
现在行了

**Comment by Ad-closeNN** [comment]
close就行了不用reopen
