### ISSUE TITLE
下载Forge时，所以版本都无法安装

### ISSUE THREAD

**Issue by ikunfddssxs** [Hex-Dragon/PCL2#4356]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

点击下载，随便点击一个版本，点击Forge，点击开始安装，过一会就下载失败，

### 重现步骤

1、点击xxxx
2、往下滚，然后点击xxxx

### 日志与附件

下载 Forge 51.0.28失败
→ 下载 Mod 加载器支持库文件失败
→ 文件下载失败：C:\Users\张楚焓\Desktop\游戏\.minecraft\libraries\net\minecraftforge\forge\1.21-51.0.28\forge-1.21-51.0.28-client.jar
远程服务器返回错误: (404) 未找到。（https://download.mcbbs.net/maven/net/minecraftforge/forge/1.21-51.0.28/forge-1.21-51.0.28-client.jar）
远程服务器返回错误: (404) 未找到。（https://download.mcbbs.net/libraries/net/minecraftforge/forge/1.21-51.0.28/forge-1.21-51.0.28-client.jar）
远程服务器返回错误: (404) 未找到。（https://libraries.minecraft.net/net/minecraftforge/forge/1.21-51.0.28/forge-1.21-51.0.28-client.jar）
远程服务器返回错误: (404) 未找到。（https://bmclapi2.bangbang93.com/maven/net/minecraftforge/forge/1.21-51.0.28/forge-1.21-51.0.28-client.jar）
远程服务器返回错误: (404) 未找到。（https://bmclapi2.bangbang93.com/libraries/net/minecraftforge/forge/1.21-51.0.28/forge-1.21-51.0.28-client.jar）
→ 远程服务器返回错误: (404) 未找到。
   在 PCL.ModNet.NetFile.Thread(NetThread Info)
错误类型：System.Net.WebException

**Comment by JingHai-Lingyun** [comment]
![image](https://github.com/user-attachments/assets/f963e719-1776-46ba-9565-91f33e2c55aa)
51.0.28 版本的 Forge 太新了…… 各大源都还没有同步呢……

**Comment by allMagicNB** [comment]
等会就好了，镜像站还没同步呢。
~~另外，你是清朝来的吗？怎么还有 MCBBS……~~

**Comment by Ad-closeNN** [comment]
虽然说没同步，但是
```
[23:52:57.202] [UI] 弹出提示：1.21-Forge_51.0.28 安装成功！
```
重新试试看看能不能换到官方源？

**Comment by JingHai-Lingyun** [comment]
> 虽然说没同步，但是
> 
> ```
> [23:52:57.202] [UI] 弹出提示：1.21-Forge_51.0.28 安装成功！
> ```
> 
> 重新试试看看能不能换到官方源？

开了调试模式你会发现跳过了那个文件
![image](https://github.com/user-attachments/assets/2a07bb45-9f30-4cf2-ac4d-441c980ee92b)
~~然后会炸掉的~~ 很神奇的没有炸…… ~~抽象~~

**Comment by JingHai-Lingyun** [comment]
鉴于这不是 PCL 的问题，就先关掉了，如果后续镜像同步了之后还是不能正常下载再来补充。
