### ISSUE TITLE
f

### ISSUE THREAD

**Issue by CNXiaoquan** [Hex-Dragon/PCL2#4362]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

s

### 重现步骤

1、点击xxxx
2、往下滚，然后点击xxxx
s

### 日志与附件

f

**Comment by Ad-closeNN** [comment]
？请不要发送毫无意义的issue

**Comment by JingHai-Lingyun** [comment]
完全没有意义，不知道你在干什么……

**Comment by Chiloven945** [comment]
这种可以加删除tag的……
