### ISSUE TITLE
mod搜索增加根据当前版本搜索mod

### ISSUE THREAD

**Issue by ZhangJinyuJerry** [Hex-Dragon/PCL2#4363]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

具体如下图（P的）   :)
![屏幕截图 2024-07-28 111518](https://github.com/user-attachments/assets/3bb6bc27-fff2-4c23-9231-1573e888f0f9)

### 原因

这项优化让我可以更方便地下载当前版本的mod。
如果没有这项优化，我每次都必须自己选择，让操作变得很麻烦；如果不选择则可能搜索到没有适配当前版本的mod。

**Comment by JingHai-Lingyun** [comment]
这不就是我的 #4075 吗？

**Comment by ZhangJinyuJerry** [comment]
啊
