### ISSUE TITLE
PCL （prt sc）报错处理

### ISSUE THREAD

**Issue by lldxlzy** [Hex-Dragon/PCL2#4365]
### 检查项

- [ ] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃基本不是 PCL 的原因，请 **不要** 提交反馈。你可以在论坛或社区找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用 HMCL 启动，HMCL 没有出现问题。** 如果 HMCL 也无法启动就不是 PCL 导致的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在使用Windows 内测26040的时候录屏系统（prt sc）会绿屏或挤爆内存，建议在第一次运行的时候检查是不是内测版本，如果是，提示说你的系统是Windows内测，回发生错误

### PCL 错误报告、日志与附件

没有哈，因为绿屏报错后就没有存下任何报错信息
但幸好，在硬盘闪灯后我就关闭了录屏
下面是部分报错记录
详细错误信息：
   在 System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
   在 System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   在 System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   在 System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   在 System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
错误类型：System.OutOfMemoryException
[17:13:50.015] [System] 诊断信息：
操作系统：Microsoft Windows 11 企業版 Insider Preview
剩余内存：2510 M / 8078 M
DPI：144（150%）
MC 文件夹：D:\.minecraft\
文件位置：D:\
[17:13:50.015] 请在 https://github.com/Hex-Dragon/PCL2/issues 提交错误报告，以便于作者解决此问题！
[17:13:50.015] [System] 执行外部命令：D:\PCL\Log1.txt 
[17:13:51.023] [System] 程序已退出，返回值：Exception

### HMCL 启动脚本

没有hmcl哈

**Comment by lldxlzy** [comment]
注：hcml运行也是会的

**Comment by allMagicNB** [comment]
……预览体验计划本就在你参与时提醒过不稳定了。

**Comment by lldxlzy** [comment]
知道，但其他的特别稳定（原神都试了）

**Comment by Pigeon0v0** [comment]
你都用 Windows Insider Preview 了，应该要有不稳定的准备...

先看看

**Comment by allMagicNB** [comment]
另外，别发切片……
~~你再发切片我不保证你会不会成为切片。~~

**Comment by lldxlzy** [comment]
知道，但其他的特别稳定（原神都试了）

**Comment by lldxlzy** [comment]
giao!  才发现发了两遍
gfw这个【字幕缺失】

**Comment by lldxlzy** [comment]
> 另外，别发日志切片…… ~你再发切片我不保证你会不会成为切片。~

啊 ~你干嘛~ 你™

**Comment by Ad-closeNN** [comment]
说重点且有关的东西就行，不要水贴 ~~如果要水去Discussion水~~

**Comment by LTCatt** [comment]
`错误类型：System.OutOfMemoryException`
OutOfMemoryException 均并非 PCL 导致。

**Comment by PhantomPixel-0418** [comment]
哥们 你那是你内存满了

**Comment by TMXQWQ** [comment]
> 注：hcml运行也是会的

那关pcl什么事

**Comment by lldxlzy** [comment]
> 哥们 你那是你内存满了

~哥们~ 大哥 我平常可不会
除了~录视频~录剧本

**Comment by lldxlzy** [comment]
> > 注：hcml运行也是会的
> 
> 那关pcl什么事

~那确实不关pcl事儿~建议pcl提醒一下用户，另外爱发电又迁移到了ifadian上了

**Comment by lldxlzy** [comment]
另外大家没发现离别有个叫《int prt》

**Comment by lldxlzy** [comment]
> 另外大家没发现~离别~里边有个叫《int prt》

**Comment by JingHai-Lingyun** [comment]
此问题已给出结论，请勿继续回复无关信息

**Comment by TMXQWQ** [comment]
> 注：hcml运行也是会的

我用HTML就没有这种情况（仅限于我的电脑）
