### ISSUE TITLE
添加对 MCC 15周年披风的翻译

### ISSUE THREAD

**Issue by Hill23333** [Hex-Dragon/PCL2#4366]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在披风活动结束后会同步到Java版，因此可以提前加入相关翻译。

### 原因

如题

**Comment by allMagicNB** [comment]
……ID 都没出来都这么急。

**Comment by Deep-Dark-Forest** [comment]
会不会有点太早了。？

**Comment by allMagicNB** [comment]
@Deep-Dark-Forest 加第三方

**Comment by WForst-Breeze** [comment]
可以先挂着，啥时候出来了再翻译就行了

**Comment by wuyuncheng-26** [comment]
已有相关 PR，等待合并中（#4366）
