### ISSUE TITLE
对Listbox进行一系列优化

### ISSUE THREAD

**Issue by Hill23333** [Hex-Dragon/PCL2#4367]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

这次有两个小点子，希望采纳... ~~如果我看得懂pcl2源码的话我就fork自己改然后push了...（之后学学vb.net）~~
0.支持键盘选择（↑↓选择，enter选中/打开）
1.键盘首字母快速选择（比如有一个项叫1.21 键盘上输入1.21就会跳转）

### 原因

这两个点子都~~抄袭~~借鉴了explorer，但是真的很有用！

**Comment by allMagicNB** [comment]
一般不用 0. 当首个列表项的，这一般是前置条件用的……

**Comment by allMagicNB** [comment]
那么，这些功能你能说出他们的实际用途吗？我感觉不太可能会用到。

**Comment by Hill23333** [comment]
选择版本的时候直接输入版本就选到了很方便；包括选mod的时候

**Comment by Hill23333** [comment]
我个人认为是这样的

**Comment by Hill23333** [comment]
突然想到第一个建议可能真的没什么用... 但是第二个我还是认为很实用

**Comment by allMagicNB** [comment]
Mod 那边不是有个搜索框吗？

**Comment by Hill23333** [comment]
还要鼠标点一下... 并且这个功能不止在mod里面用 包括下新版本的时候可以一件定位

**Comment by allMagicNB** [comment]
……你多点一下会咋样。

**Comment by Hill23333** [comment]
额... 只是给个建议 加上后会更加方便啦！当然不加也行 如果你觉得这两个功能没有帮助可以关掉这个issue

**Comment by allMagicNB** [comment]
#540 #624？

**Comment by Hill23333** [comment]
我看了一下，其实并不一样

**Comment by Hill23333** [comment]
这是对所有listbox的优化，并不是仅限于一个地方

**Comment by Hill23333** [comment]
等一下

**Comment by Hill23333** [comment]
我看见了...工作量很大...

**Comment by Hill23333** [comment]
我会尝试自己实现，在实现之前我会把这个issue关闭

**Comment by allMagicNB** [comment]
Maybe he writes EPL too much and thinks everything is easy.

**Comment by Silverteal** [comment]
意义有限
