### ISSUE TITLE
版本 json 不规范（绿色版红石生电优化）未将对象引用设置到对象的实例.

### ISSUE THREAD

**Issue by Joining2843** [Hex-Dragon/PCL2#4373]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

游戏安装失败
→ 下载原版 1.19.4失败
→ 下载原版支持库文件失败
→ 分析原版支持库文件（副加载器）失败
→ 版本 json 不规范（绿色版红石生电优化）
→ 未将对象引用设置到对象的实例。
   在 PCL.ModMinecraft.McVersion.RevertAccount()
   在 PCL.ModMinecraft.McLibListGet(McVersion Version, Boolean IncludeVersionJar)
   在 PCL.ModMinecraft.McLibFix(McVersion Version, Boolean CoreJarOnly)
   在 PCL.ModDownloadLib._Closure$__6-0._Lambda$__1(LoaderTask`2 Task)
   在 PCL.ModLoader.LoaderTask`2._Closure$__13-0._Lambda$__0()
   在 PCL.ModMinecraft.McVersion.RevertAccount()
错误类型：System.NullReferenceException

### 重现步骤

1、点击绿色版红石生电优化
2、往下滚，然后点击1.19.4

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16411158/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16411162/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16411164/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16411165/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16411169/Log5.txt)

**Comment by allMagicNB** [comment]
用 HMCL 试试？

**Comment by Chiloven945** [comment]
未能复现。

**Comment by zkitefly** [comment]
https://github.com/Hex-Dragon/PCL2/issues/3710

看起来很像这个

**Comment by Joining2843** [comment]
也行@allMagicNB

**Comment by bangbang93** [comment]
https://bmclapi2.bangbang93.com/v1/packages/f6f28aebf8852f2bda5ba814d7c8bd06cb6275c7/3.json
这是个assets index，压根不是版本json

**Comment by LTCatt** [comment]
看起来像是版本 json 莫名其妙地只有恰好前 4KB 的内容，但 PCL 又确实获取到了具体的文件大小并且校验成功了。
之后有空看看。

**Comment by bangbang93** [comment]
重定向能够把整个过程中的所有url都记录打印吗，对于网盘节点最终拿到一个网盘的url，我也不知道是哪个节点
然后后续在规划的启动器下载失败的上报接口我也会需要整个重定向的历史来追踪节点的工作状态

**Comment by LTCatt** [comment]
不太行，PCL 的重定向是 .net 自动处理的，我看不到中间过程

**Comment by wuliaodexiaoluo** [comment]
> 不太行，PCL 的重定向是 .net 自动处理的，我看不到中间过程

是指 HttpClient 的自动重定向?
或许可以 `handler.AllowAutoRedirect = False ` 阻止自动重定向，但是这样要额外写代码来读处理 HTTP 状态码和请求头中的 Location 字段

**Comment by bangbang93** [comment]
https://stackoverflow.com/questions/7860188/httpclient-capture-a-list-of-all-redirects
有方案可以捕捉，不需要手动处理重定向

可以等我把启动器上报接口放出来再考虑

**Comment by kong-que-dnf123** [comment]
> #3710
> 
> 看起来很像这个

不一样吧这个是检测失败 https://github.com/Hex-Dragon/PCL2/issues/3710#issuecomment-2127959798 甚至都像是JSON下一半直接下崩给停了

**Comment by SALTWOOD** [comment]
> 不太行，PCL 的重定向是 .net 自动处理的，我看不到中间过程

 可以参考我的一个项目的写法，[此处](https://github.com/SaltWood-Studio/CSharp-OpenBMCLAPI/blob/9cd0deb31062761f8860fc9b22bebfe14d02f77d/CSharp-OpenBMCLAPI/Modules/Cluster.cs#L644-L691)
除此之外，我还发现了一篇 StackOverflow 的文章 https://stackoverflow.com/questions/7860188/httpclient-capture-a-list-of-all-redirects
