### ISSUE TITLE
[转发] 拖入整合包时候下载安装Forge失败

### ISSUE THREAD

**Issue by LTCatt** [Hex-Dragon/PCL2#4374]
### Discussed in https://github.com/Hex-Dragon/PCL2/discussions/4331

<div type='discussions-op-text'>

<sup>Originally posted by **shixiaogaoya** July 24, 2024</sup>
游戏安装失败
→ 下载 Forge 47.3.5失败
→ 安装 Forge（方式 A）失败
→ 安装新 Forge 版本失败
→ 运行 Forge 安装器失败
→ Forge 安装器出错，日志结束部分为：
	... 5 more
Caused by: java.nio.charset.UnsupportedCharsetException: GBK
	at java.nio.charset.Charset.forName(Unknown Source)
	at sun.nio.fs.Util.<clinit>(Unknown Source)
	... 18 more
   在 PCL.ModDownloadLib._Closure$__35-0._Lambda$__7(LoaderTask`2 Task)
   在 PCL.ModLoader.LoaderTask`2._Closure$__13-0._Lambda$__0()
   在 PCL.ModDownloadLib._Closure$__35-0._Lambda$__7(LoaderTask`2 Task)
   在 PCL.ModDownloadLib.ForgelikeInjector(String Target, LoaderTask`2 Task, String McFolder, Boolean UseJavaWrapper, Boolean IsNeoForge)
   在 PCL.ModDownloadLib._Closure$__35-0._Lambda$__7(LoaderTask`2 Task)</div>

[Log1.txt](https://github.com/user-attachments/files/16415567/Log1.txt)

**Comment by wuyuncheng-26** [comment]
`Caused by: java.nio.charset.UnsupportedCharsetException: GBK`
重点在这吧
初步猜测是编码问题

**Comment by Silverteal** [comment]
其实报错原因很明显了，重点是怎么解决。
比如把GBK换成cp936之类的

**Comment by LTCatt** [comment]
![image](https://github.com/user-attachments/assets/853becad-25b7-40b1-b905-568a5cb06856)
这似乎是系统环境问题，导致 JVM 无法加载 GBK 编码。
在有更多线索表明这是 PCL 导致的之前先暂时认为这和 PCL 无关……
