### ISSUE TITLE
没有安装重复mod, 可提示您安装了重复mod

### ISSUE THREAD

**Issue by Joining2843** [Hex-Dragon/PCL2#4376]
### 检查项

- [ ] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃基本不是 PCL 的原因，请 **不要** 提交反馈。你可以在论坛或社区找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用 HMCL 启动，HMCL 没有出现问题。** 如果 HMCL 也无法启动就不是 PCL 导致的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在1.20.1NeoForge47.1.216(我也不知道NeoForge版本)安装102mod情况下启动, 发生没有安装重复mod, 可提示您安装了重复mod的情况.

### PCL 错误报告、日志与附件

[Log1.txt](https://github.com/user-attachments/files/16421157/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16421159/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16421161/Log3.txt)
[Log5.txt](https://github.com/user-attachments/files/16421163/Log5.txt)
[错误报告-2024-7-30_9.56.47.zip](https://github.com/user-attachments/files/16421164/-2024-7-30_9.56.47.zip)
[Log4.txt](https://github.com/user-attachments/files/16421162/Log4.txt)

### HMCL 启动脚本

[脚本在这里面.zip](https://github.com/user-attachments/files/16421353/default.zip)

**Comment by JingHai-Lingyun** [comment]
```
[307月2024 09:56:26.634] [main/ERROR] [net.minecraftforge.fml.loading.UniqueModListBuilder/LOADING]: Found duplicate mods:
	Mod ID: 'rubidium' from mod files: rubidium-mc1.20.1-0.7.1.jar, embeddium-0.3.28+mc1.20.1.jar
```
Rubidium 和 Embeddium 只需要两个装一个就好了……
所以确实是重复了
