### ISSUE TITLE
Mod更新按钮不会在获取Mod更新信息后刷新

### ISSUE THREAD

**Issue by XeF2i** [Hex-Dragon/PCL2#4377]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在版本Mod界面若在Mod版本加载之前全选，则需要更新的Mod并不会提示更新
![f0770f179c25f17350c51a2cc80d44b](https://github.com/user-attachments/assets/1451166c-dde1-454f-a15a-cc1e2f386193)

### 重现步骤

1、点击版本设置-Mod管理
2、在加载好前快速全选Mod
注：若Mod已加载可以先清理启动器缓存

### 日志与附件

[Log3.txt](https://github.com/user-attachments/files/16421593/Log3.txt)
[Log1.txt](https://github.com/user-attachments/files/16421594/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16421595/Log2.txt)
在Log1与Log3中两次出现了此Bug
解决方案：可以在获取Mod更新信息后增加一次刷新按钮的操作

**Comment by JingHai-Lingyun** [comment]
在 Mod 更新信息加载好之前全选 Mod 导致无法一键更新全部 Mod

**Comment by wuliaodexiaoluo** [comment]
<details>
<summary>我的看法（可能不是很友好）</summary>

>在加载好前快速全选Mod

无意冒犯，但是我觉得有点卡时机的意味 <del>，Issue 被龙猫拒掉的概率 +10% </del>
>注：若Mod已加载可以先清理启动器缓存

无意冒犯，但是特殊条件 +1 <del>，Issue 被龙猫拒掉的概率 +20% </del>

>在版本Mod界面若在Mod版本加载之前全选，则需要更新的Mod并不会提示更新

这应该是预期行为，如果反复加载信息会导致一瞬间的 IO 爆炸和 CPU 占用的显著提高，如果没回收干净就算内存泄漏，文件被使用、损坏了会报错，热加载可能导致死锁或者类似 #3092 那样的 UI Bug，信息没刷新就不可能更新，就像你不可能让小学生做高中奥数，因为根本做不来（当然也不排除有神童能做出来）

<del> Issue 被龙猫拒掉的概率 +20% </del>

>解决方案：可以在获取Mod更新信息后增加一次刷新按钮的操作

如果重新选中能使此 Bug 的到解决，那这个按钮不太可能加上去
所以其实没啥用

<del> Issue 被龙猫拒掉的概率 +40% </del>

综合来看，龙猫拒掉的可能性高达 90%，约等于拒掉，而且就算打上了处理中的 Label 也不太可能是做 Issue 提到的修复方案，我觉得最多是阻止在加载完毕前选中 Mod (这也不太可能)

</details>

**Comment by XeF2i** [comment]
> 我的看法（可能不是很友好）(点击展示)

所以你应该好奇了这个奇怪的Bug是如何被发现的。事实上是因为本人电脑游戏等经常多开，比较着急，每次打开PCL都先去检查Mod更新（Ctrl+A）然后就切到别的界面等待加载。今天这次切回来看没有要更新的Mod就进入游戏了，结果发现模组菜单提示有更新...于是机缘巧合发现了这个Bug

不过我也没想到这个Bug能过

**Comment by XeF2i** [comment]
> 我的看法（可能不是很友好）(点击展示)

哦对还有占用问题，其实在获取Mod资源之后如果有更新在每个Mod处的更新小箭头是有刷新显示的，那应该也可以把全部更新的按钮刷新放到同一个回调函数里吧（.net我不太懂，如果不行那就算了）
