### ISSUE TITLE
无法连接到本地安全机构

### ISSUE THREAD

**Issue by jostatang** [Hex-Dragon/PCL2#4378]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/user-attachments/assets/5005b7ce-61d1-4307-92e6-52c6f83be317)

### 重现步骤

打开游戏也会这样，登录也这样

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16422748/Log1.txt)

**Comment by zkitefly** [comment]
疑似网络问题，试着挂个梯子再试？

**Comment by JingHai-Lingyun** [comment]
Win32Exception 不可能是 PCL 带来的……

**Comment by LTCatt** [comment]
这可能是 Windows 的配置问题，搜一下这个报错可能有用，但应当不是 PCL 引起

**Comment by Silverteal** [comment]
关于本地安全机构（LSA）的介绍较少。但同样的错误内容通常发生在“无法通过RDP连接到远程计算机”中。  

考虑到本地安全机构似乎同样是一项 Windows Server 和 Windows 11 的保护功能，这应该是网络层面的问题。

如果有可能，尝试在 Windows 安全中心 -> 设备安全性 -> 本地安全机构 中关闭本地安全机构（LSA）选项（如有）。但这不一定有用
