### ISSUE TITLE
OptiFine 安装失败（等待原版下载错误：复制文件出错）

### ISSUE THREAD

**Issue by LTCatt** [Hex-Dragon/PCL2#438]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

加载线程 等待原版下载 (54) 发生运行时错误：复制文件出错：D:\Minecraft\程序\.minecraft-test\versions\1.19.2-OptiFine_I1_pre4\1.19.2-OptiFine_I1_pre4.json -> C:\Users\LTCat\AppData\Local\Temp\PCL\Install\1.19.2-OptiFine_I1_pre4\versions\1.19.2\1.19.2.json
Caused By: 未能找到文件“D:\Minecraft\程序\.minecraft-test\versions\1.19.2-OptiFine_I1_pre4\1.19.2-OptiFine_I1_pre4.json”。
   在 PCL.ModBase.CopyFile(String FromPath, String ToPath) 位置 F:\Projects\Plain Craft Launcher 2\本体代码\Plain Craft Launcher 2\Modules\Base\ModBase.vb:行号 785
   在 PCL.ModDownloadLib._Closure$__15-0._Lambda$__1(LoaderTask`2 Task) 位置 F:\Projects\Plain Craft Launcher 2\本体代码\Plain Craft Launcher 2\Pages\PageDownload\ModDownloadLib.vb:行号 537
   在 PCL.ModLoader.LoaderTask`2._Closure$__12-0._Lambda$__0() 位置 F:\Projects\Plain Craft Launcher 2\本体代码\Plain Craft Launcher 2\Modules\Base\ModLoader.vb:行号 310
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   在 PCL.ModBase.CopyFile(String FromPath, String ToPath) 位置 F:\Projects\Plain Craft Launcher 2\本体代码\Plain Craft Launcher 2\Modules\Base\ModBase.vb:行号 778
错误类型：System.IO.FileNotFoundException

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10076541/Log1.txt)

**Comment by Louis-ZYH** [comment]
成，您活跃橙到手了
