### ISSUE TITLE
打开下载页时神奇的错误

### ISSUE THREAD

**Issue by WuDabin12358** [Hex-Dragon/PCL2#4380]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

打开下载页时出现错误

### 重现步骤

概率触发（约1/5）

### 日志与附件

[Log.txt](https://github.com/user-attachments/files/16426517/Log.txt)
[Log1.txt](https://github.com/user-attachments/files/16426518/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16426520/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16426522/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16426523/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16426524/Log5.txt)

**Comment by JingHai-Lingyun** [comment]
```log
[18:45:40.260] 程序出现未知错误：无法排序，原因是 IComparer.Compare() 方法返回不一致的结果。一个值与本身比较不相等，或者一个值与另外一个值重复比较生成不同的结果。IComparer:“System.Windows.Controls.Grid+SpanPreferredDistributionOrderComparer”。
   在 System.Array.SorterObjectArray.DepthLimitedQuickSort(Int32 left, Int32 right, Int32 depthLimit)
   在 System.Array.Sort(Array keys, Array items, Int32 index, Int32 length, IComparer comparer)
   在 System.Windows.Controls.Grid.EnsureMinSizeInDefinitionRange(DefinitionBase[] definitions, Int32 start, Int32 count, Double requestedSize, Double percentReferenceSize)
   在 System.Windows.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged)
   在 System.Windows.Controls.Grid.MeasureOverride(Size constraint)
   在 System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   在 System.Windows.UIElement.Measure(Size availableSize)
   在 System.Windows.ContextLayoutManager.UpdateLayout()
   在 System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   在 System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   在 System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   在 System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
错误类型：System.ArgumentException
```
？

**Comment by WuDabin12358** [comment]
log1,log4出现该错误

**Comment by LTCatt** [comment]
看起来是 WPF 引发了内部错误。
umm 反馈者能具体描述一下会有哪些页面会出现这个报错吗？还是随机的？

**Comment by WuDabin12358** [comment]
> 看起来是 WPF 引发了内部错误。 um 反馈者能具体描述一下会有哪些页面会出现这个报错吗？还是随机的？

在子页面下进行功能切换时有概念引发

**Comment by LTCatt** [comment]
呃，因为我这里不能复现，能上传复现视频吗？只看 log 我不太清楚是什么 UI 出了问题，多谢 orz

**Comment by WuDabin12358** [comment]
> 呃，因为我这里不能复现，能上传复现视频吗？只看 log 我不太清楚是什么 UI 出了问题，多谢 orz


https://github.com/user-attachments/assets/c1b56e10-0f3c-49b3-81f4-1783a2ddb9c3
以上为复现视频

另外，经过充分实验，发生概率在本机上实为约1/200    
_天知道之前我是怎么连续触发的(⇀‸↼‶)_

**Comment by WuDabin12358** [comment]
> > 呃，因为我这里不能复现，能上传复现视频吗？只看 log 我不太清楚是什么 UI 出了问题，多谢 orz
> 
> https://github.com/user-attachments/assets/c1b56e10-0f3c-49b3-81f4-1783a2ddb9c3 以上为复现视频
> 
> 另外，经过充分实验，发生概率在本机上实为约1/200 _天知道之前我是怎么连续触发的 (⇀‸↼‵‵)_

_奇怪，这个视频不能在Edge上直接播放，下载后正常_

**Comment by Silverteal** [comment]
翻译错误信息：
IComparer.Compare() 被错误地实现了，因为两个相同的值返回不相等，或者比较操作多次调用结果不同

[StackOverFlow](https://stackoverflow.com/questions/16435309/icomparer-issue) 上提出了两种可能：
- 没有为 NaN 进行正确的特判
- **由于其他线程对被比较对象的操作，被比较对象在比较过程中实际发生了变化**

**Comment by zeze-1121** [comment]
我点下载-mod

**Comment by zeze-1121** [comment]
我点下载-mod 显示 无法连接到 Modrinth，所以目前仅显示了来自 CurseForge 的内容，结果可能不全
请尝试使用 VPN 或加速器以改善网络。

**Comment by Silverteal** [comment]
> 我点下载-mod 显示 无法连接到 Modrinth，所以目前仅显示了来自 CurseForge 的内容，结果可能不全
> 请尝试使用 VPN 或加速器以改善网络。

与主楼问题无关，报错信息也没有问题。请问您为什么要发这个呢

**Comment by LTCatt** [comment]
这应当是 WPF 的 bug，无法修复
