### ISSUE TITLE
爱发电域名迁移后启动器“关于与鸣谢”页下赞助按钮的链接仍为旧域名 导致无法打开赞助页

### ISSUE THREAD

**Issue by ACGPlanck** [Hex-Dragon/PCL2#4383]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

现在爱发电域名已经更改为afdian.com，但启动器内赞助龙猫本人以及BMCLAPI镜像源的按钮仍然链接到旧域名afdian.net，因而无法打开赞助页面，按钮事实上已经失效，需要更改为新域名对应的链接。

### 重现步骤

1.在PCL启动器中点击“更多”“关于与鸣谢”；
2.点击“赞助作者”或“赞助镜像源“，即弹出错误链接的页面。

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16439595/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16439596/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16439597/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16439598/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16439599/Log5.txt)

**Comment by zkitefly** [comment]
https://github.com/Hex-Dragon/PCL2/issues/4271

等更新？
