### ISSUE TITLE
错误的mod更新提示

### ISSUE THREAD

**Issue by ZeroCore-Zero** [Hex-Dragon/PCL2#4386]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

PCL2提示我将地毯mod从1.20.6-1.4.141+v240429升级到24w18a-1.4.142+v240503，这将会导致游戏加载时崩溃
<img width="647" alt="photo" src="https://github.com/user-attachments/assets/100a3640-1375-45b6-bd95-52ac1c9a00b9">
游戏版本：Fabric1.20.6

### 重现步骤

使用fabric1.20.6客户端，安装carpet 1.20.6-1.4.141+v240429
1、版本设置->Mod管理
2、找到地毯mod，点击更新

### 日志与附件

![image](https://github.com/user-attachments/assets/a8e63e5e-80c6-4eb7-8119-e2efde18d5e0)

**Comment by JingHai-Lingyun** [comment]
在 Mod 上右键一下提供一下是哪个平台的信息

**Comment by JingHai-Lingyun** [comment]
请向 Mod 作者反馈此问题。

**Comment by Miaowuji1935** [comment]
但是为什么pcl选择了更新10个月的代替6个月前的
