### ISSUE TITLE
mod列表分组

### ISSUE THREAD

**Issue by zhuluzyy** [Hex-Dragon/PCL2#4390]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

mod管理中的mod列表. 可以把已下载的模组分组,批量启用,禁用,删除模组, 并可以折叠同组模组, 让模组列表更清爽,一目了然.(类似windows资源管理器,只不过可以自由分组)
最好能通过模组标签快速分组

### 原因

这项优化让我可以更方便地启用和禁用模组,并把相互关联的模组更好的绑定,避免出现禁用了前置模组而没有禁用依赖他的模组所导致的问题, 也可以更方便的排查模组错误与问题。
如果没有这项优化，我每次都必须一个一个禁用和启用, 在使用和制作大型整合包时会非常麻烦.

**Comment by JingHai-Lingyun** [comment]
#277 已拒绝，抱歉
