### ISSUE TITLE
在mod下载页面中curseforgr和Modrigth无法合并

### ISSUE THREAD

**Issue by genshincoder** [Hex-Dragon/PCL2#4392]
### 检查项

- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

搜索mod并下载时同一个mod的CurseForge和Modrigth源会被拆分成两个mod显示

### 重现步骤

1、启动PCL2
2、点击最上方的"下载"选项卡
3、点击右边的“Mod”按钮
4、输入一个在curseforge和modrinth均可下载的mod名称（如i18n）
5、点击搜索按钮
6、你应该就能看到重复的mod选项了

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16455403/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16455404/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16455405/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16455406/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16455407/Log5.txt)

**Comment by JingHai-Lingyun** [comment]
目前，对于支持的 Minecraft 主版本不一致的情况下，不会对 CurseForge 和 Modrinth 两个来源的 Mod 进行合并
参阅 #1318
