### ISSUE TITLE
建议添加mod下载页面允许使用缩写来搜索

### ISSUE THREAD

**Issue by genshincoder** [Hex-Dragon/PCL2#4393]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

mod下载界面可以识别mode的缩写（如应用能源---->>AE2等）

### 原因

这项优化让我可以更方便地查找一些mod。
如果没有这项优化，我每次都必须输入mod全称，有时还要在mcmod里面搜索这个Mod，这让操作变得很麻烦。

**Comment by hejiehao** [comment]
> 感觉很难实现……需要一个个录入

~~爬虫技术了解一下~~

**Comment by wuyuncheng-26** [comment]
> 感觉很难实现……~需要一个个录入~ 好吧不一定

那些你看到的模组中文名都是一个个录入的（https://github.com/Hex-Dragon/PCL2/blob/main/Plain%20Craft%20Launcher%202/Resources/ModData.txt）
缩写肯定是比中文翻译少很多的，应该能搞定（

**Comment by z0z0r4** [comment]
建议在下方列出来就行了...总共没几十个个

> > 感觉很难实现……~需要一个个录入~ 好吧不一定
> 
> 那些你看到的模组中文名都是一个个录入的 [`main`/Plain%20Craft%20Launcher%202/Resources/ModData.txt](https://github.com/Hex-Dragon/PCL2/blob/main/Plain%20Craft%20Launcher%202/Resources/ModData.txt?rgh-link-date=2024-08-02T12%3A54%3A19Z) 缩写肯定是比中文翻译少很多的，应该能搞定（

**Comment by genshincoder** [comment]
我的点子：可以直接爬mcmod录入

**Comment by SALTWOOD** [comment]
搜索一般是直接接入到网站的搜索引擎那里去的
感觉没啥必要做，说不定还会和网站的搜索结果冲突什么的

**Comment by wuliaodexiaoluo** [comment]
mcmod 没有 API，网站改版就炸

**Comment by z0z0r4** [comment]
> mcmod 没有 API，网站改版就炸

这个倒是无所谓，但这几个缩写没啥意义...

**Comment by LTCatt** [comment]
看了看，不是很好做，并且估计使用面也不大，目前先算了 orz
