### ISSUE TITLE
版本隔离设置未被保存

### ISSUE THREAD

**Issue by namehart** [Hex-Dragon/PCL2#4394]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

版本隔离设置未被保存

### 重现步骤

1. 打开PCL
1. 点开设置页面
1. 将原本的版本隔离由“关闭”变成“隔离可安装MOD版本和其他非正式版”
2. 关闭PCL
1. 打开PCL
1. 点开设置页面
2. 发现原来的版本隔离仍然为“关闭”
3. 进入游戏后发现版本隔离设置失效

### 日志与附件

自安装pcr以来，未成功写入任何日志文件 @

**Comment by wuyuncheng-26** [comment]
没有日志文件？离谱（



发自我的iPad


------------------ 原始邮件 ------------------
发件人: namehart ***@***.***&gt;
发送时间: 2024年8月2日 21:51
收件人: Hex-Dragon/PCL2 ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [Hex-Dragon/PCL2] 版本隔离设置未被保存 (Issue #4394)





 
检查项
  
 我已在 Issues 页面 和 常见&amp;难检反馈及问题列表 中搜索，确认了这一 Bug 未被提交过。
  
描述
 
版本隔离设置未被保存
 
重现步骤
  
打开PCL
 
点开设置页面
 
将原本的版本隔离由“关闭”变成“隔离可安装MOD版本和其他非正式版”
 
关闭PCL
 
打开PCL
 
点开设置页面
 
发现原来的版本隔离仍然为“关闭”
 
进入游戏后发现版本隔离设置失效
  
日志与附件
 
自安装pcr以来，未成功写入任何日志文件 @

**Comment by wuyuncheng-26** [comment]
没有日志文件很难分析

**Comment by youzi-2333** [comment]
既然没写入日志，那么 PCL 目录下存放配置文件的 `Setup.ini` 应当也无法写入。请尝试：

- 将 PCL 放到 C 盘以外的地方
- 把 PCL 程序相同目录下的 PCL 文件夹（如有）删除
- 右键 PCL，选择以管理员身份运行

不过我很疑惑，没有写入权限是怎么能成功打开 PCL 的……？

**Comment by xingnengmao666** [comment]
我已复现这个错误，只要把setup.ini调成只读，PCL2在重启后不会有任何报错，“版本隔离”也能正常切换，但是再次重进pcl2，便会回退到开启只读前的最后的设置
[Log3.txt](https://github.com/user-attachments/files/16479395/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16479396/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16479397/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/16479398/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16479399/Log2.txt)

**Comment by allMagicNB** [comment]
……你是不是故意找茬

**Comment by xingnengmao666** [comment]
是的（骄傲？

**Comment by hejiehao** [comment]
我倒是觉得可以让作者看看 Setup.ini 被设置成了只读

**Comment by xingnengmao666** [comment]
我就是这个意思（
因为我之前为了防止有些软件改ini，经常会这样办，就想到了这个办法……

**Comment by sulingjiang** [comment]
> 我倒是觉得可以让作者看看 Setup.ini 是否被设置成了只读

最好让他看下其他文件，搞不好其他的也是只读的

**Comment by wuyuncheng-26** [comment]
> 我已复现这个错误，只要把setup.ini调成只读，PCL2在重启后不会有任何报错，“版本隔离”也能正常切换，但是再次重进pcl2，便会回退到开启只读前的最后的设置 [Log3.txt](https://github.com/user-attachments/files/16479395/Log3.txt) [Log4.txt](https://github.com/user-attachments/files/16479396/Log4.txt) [Log5.txt](https://github.com/user-attachments/files/16479397/Log5.txt) [Log1.txt](https://github.com/user-attachments/files/16479398/Log1.txt) [Log2.txt](https://github.com/user-attachments/files/16479399/Log2.txt)

6，以制造 bug 为目标是吧

**Comment by allMagicNB** [comment]
……扬了它

**Comment by JingHai-Lingyun** [comment]
测了一下，现在 Setup.ini 没有权限读取的情况下只会引发 DEBUG 提醒
![image](https://github.com/user-attachments/assets/5b6a966f-0ad1-4633-b650-9c96b664c95e)
斯~

---

这个问题作为 `Setup.ini 没有权限读取时不报错` 修复？
给龙猫看看

**Comment by namehart** [comment]
谢谢，已经得到解决了。

**Comment by wuyuncheng-26** [comment]
所以应该是 PCL 权限不够，无法访问其他文件罢了（

**Comment by LTCatt** [comment]
现在写入失败的报错均会抛出更高严重程度的异常
