### ISSUE TITLE
libjlw-aarch64-1.4.0.dll: %1 不是有效的 Win32 应用程序。

### ISSUE THREAD

**Issue by Sunch233** [Hex-Dragon/PCL2#4396]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃基本不是 PCL 的原因，请 **不要** 提交反馈。你可以在论坛或社区找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用 HMCL 启动，HMCL 没有出现问题。** 如果 HMCL 也无法启动就不是 PCL 导致的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在Windows 11 ARM上使用PCL，并且使用Microsoft Build of OpenJDK 17/21 aarch64构建启动1.16以上版本，始终报错`libjlw-aarch64-1.4.0.dll: %1 不是有效的 Win32 应用程序。`

### PCL 错误报告、日志与附件

[错误报告-2024-8-3_0.58.07.zip](https://github.com/user-attachments/files/16473320/-2024-8-3_0.58.07.zip)

### HMCL 启动脚本

[HMCL启动脚本.zip](https://github.com/user-attachments/files/16473342/HMCL.zip)

**Comment by JingHai-Lingyun** [comment]
ARM 架构不兼容问题

**Comment by 00ll00** [comment]
NO😩

**Comment by wuyuncheng-26** [comment]
![image](https://github.com/user-attachments/assets/3a1a48d3-bd2e-449e-9fe6-72fef2774e79)
现在看来应该是失败了罢了（

**Comment by 00ll00** [comment]
当库加载失败时使用别的方式获取启动命令行，大概能够修好（搭的 win10 arm64 环境有问题 powershell 用不了，只在本地测了）

[更新wrapper](https://github.com/00ll00/java_launch_wrapper/releases/tag/v1.4.1)

**Comment by 00ll00** [comment]
> > 当库加载失败时使用别的方式获取启动命令行，大概能够修好（搭的 win10 arm64 环境有问题 powershell 用不了，只在本地测了）
> 
> WMIC? It is disabled by default on newer Windows (for this year’s commercial releases, it is 24H2). Should we consider using alternatives?
> 
> [WMI command line (WMIC) utility deprecation: Next steps | Windows IT Pro blog](https://techcommunity.microsoft.com/t5/windows-it-pro-blog/wmi-command-line-wmic-utility-deprecation-next-steps/ba-p/4039242)

确实有看到，但是新的那一套东西没看懂怎么用💦

**Comment by allMagicNB** [comment]
> > > 当库加载失败时使用别的方式获取启动命令行，大概能够修好（搭的 win10 arm64 环境有问题 powershell 用不了，只在本地测了）
> > 
> > WMIC? It is disabled by default on newer Windows (for this year’s commercial releases, it is 24H2). Should we consider using alternatives?
> > 
> > [WMI command line (WMIC) utility deprecation: Next steps | Windows IT Pro blog](https://techcommunity.microsoft.com/t5/windows-it-pro-blog/wmi-command-line-wmic-utility-deprecation-next-steps/ba-p/4039242)
> 
> 确实有看到，但是新的那一套东西没看懂怎么用💦

说白了要用 PowerShell，Vista 直接爆炸。

**Comment by 00ll00** [comment]
> > 当库加载失败时使用别的方式获取启动命令行，大概能够修好（搭的 win10 arm64 环境有问题 powershell 用不了，只在本地测了）
> 
> WMIC? It is disabled by default on newer Windows (for this year’s commercial releases, it is 24H2). Should we consider using alternatives?
> 
> [WMI command line (WMIC) utility deprecation: Next steps | Windows IT Pro blog](https://techcommunity.microsoft.com/t5/windows-it-pro-blog/wmi-command-line-wmic-utility-deprecation-next-steps/ba-p/4039242)

已改为使用 CIM cmdlet [更新wrapper](https://github.com/00ll00/java_launch_wrapper/releases)

感谢 @allMagicNB 的协助
