### ISSUE TITLE
仅PCL启动器无法连接Modrinth

### ISSUE THREAD

**Issue by OVCstudio** [Hex-Dragon/PCL2#4398]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

浏览器可裸连Modrinth，HMCL也可以，PCL会报错
![image](https://github.com/user-attachments/assets/14ef8290-2786-4620-904f-98c86332c24e)

### 重现步骤

不知如何在其他网络环境下复现
1、不挂梯子
2、设置DNS为114.114.114.114和101.198.198.198（某60安全DNS）
3、非管理员身份打开PCL
4、下载→Mod
5、出现报错提示

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16478950/Log1.txt)

**Comment by allMagicNB** [comment]
访问一次 api.modrinth.com？

**Comment by OVCstudio** [comment]
浏览器可以访问api.modrinth.com
出现6行代码

**Comment by allMagicNB** [comment]
然后再打开 PCL 试试？

**Comment by xingnengmao666** [comment]
![api modrinth com_360](https://github.com/user-attachments/assets/3787d4c7-c481-436c-8ecd-3158eaa6dff9)
![api modrinth com_运营商](https://github.com/user-attachments/assets/30af4569-4b55-4ca4-8c31-e756bec01000)
![api modrinth com_114](https://github.com/user-attachments/assets/0a4a5c0e-2b58-47be-8d3b-16c354420d18)
以上分别为360dns，各地运营商dns，114dns的itdog测试结果，访问并无很大问题

**Comment by hejiehao** [comment]
发大图的时候可以使用 Slash commands 中的 Details，就像这样
<details><summary>大图</summary>
<p>

![image](https://github.com/user-attachments/assets/ec27acd7-422d-4cd4-b0e5-4ec139fb82cb)


</p>
</details>

**Comment by JingHai-Lingyun** [comment]
怀疑与 #4327 同理

**Comment by LTCatt** [comment]
由于 #4327 可以解决该问题，并且也没有明朗的修复线索，暂时关掉
