### ISSUE TITLE
有关"关闭Minecraft"按钮的建议

### ISSUE THREAD

**Issue by Hui100120** [Hex-Dragon/PCL2#4403]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在启动Minecraft后，关闭PCL2再打开，左下角的"关闭Minecraft"按钮会消失。我希望可以在关闭PCL2再打开时可以见到这个按钮。

### 原因

这项优化让我可以更方便地关闭Minecraft。

**Comment by lactobionicAcid** [comment]
与#1243 重复。
