### ISSUE TITLE
希望增加更新mod后旧mod的备份或恢复功能

### ISSUE THREAD

**Issue by Tony0531** [Hex-Dragon/PCL2#4407]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

现在pcl自动更新mod之后，老mod会被置入回收站之中，如果需要备份要自己手动黏贴出来，恢复也是如此，还可能被误删除，希望可以增加一个自动备份和恢复选项。

### 原因

有助于排查因更新mod而引起的mod不兼容问题并方便恢复

**Comment by wuyuncheng-26** [comment]
见 https://github.com/Hex-Dragon/PCL2/issues/4238#issuecomment-2225798607
「更新 mod 本来就是不推荐的操作」
再说了，手动备份也不是一件麻烦事吧……

**Comment by allMagicNB** [comment]
> 见 https://github.com/Hex-Dragon/PCL2/issues/4238#issuecomment-2225798607
> 「更新 mod 本来就是不推荐的操作」
> 再说了，手动备份也不是一件麻烦事吧……

你这和主题有什么关系？我感觉你说的像龙猫造出来这个功能就不维护了似的。

**Comment by wuyuncheng-26** [comment]
> > 见 [#4238 (comment)](https://github.com/Hex-Dragon/PCL2/issues/4238#issuecomment-2225798607)
> > 「更新 mod 本来就是不推荐的操作」
> > 再说了，手动备份也不是一件麻烦事吧……
> 
> 你这和主题有什么关系……我感觉你说得像龙猫造出来这个功能就不维护了似的。

我的重点在最后一句……
正如 #3632 所说，把那堆旧文件都放在模组文件夹下显得会很乱
那些备份文件如果要恢复的话也很麻烦，这么想还不如手动

**Comment by WForst-Breeze** [comment]
与 #3632 需求相同，可以关闭

**Comment by allMagicNB** [comment]
但是可以不加到列表啊……

**Comment by WForst-Breeze** [comment]
行，那就再让龙猫看看

**Comment by LTCatt** [comment]
同 #3632 暂不考虑，没有必要……
