### ISSUE TITLE
又崩了（System.Windows.Media.Composition.DUCE.Channel.SyncFlush()）

### ISSUE THREAD

**Issue by wuwenjun9939** [Hex-Dragon/PCL2#4413]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

这回确实是内存不足.....吗？
这段错误信息表明您的计算机在尝试运行PCL（Point Cloud Library）时遇到了内存不足的问题。具体来说，系统抛出了一个 System.OutOfMemoryException 异常，这是.NET框架中的一个异常类，用于指示程序试图分配内存但系统无法满足请求的情况。

错误信息的堆栈跟踪显示了异常发生时的调用链。这里的关键部分是：

System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable<ChannelSet> channelSet)
System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
这些方法和调用通常与Windows图形用户界面（GUI）的操作有关，特别是在处理窗口更新和消息传递时。然而，它们并不直接指向内存分配失败的原因，而是显示了异常在系统中的传播路径。
（以上是chatgpt分析）

### 重现步骤

![image](https://github.com/user-attachments/assets/13e2ef26-35e9-4709-9672-ed188e3941a9)
我都不知道说啥了.....

### 日志与附件

[现在崩溃的文本.txt](https://github.com/user-attachments/files/16495165/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16495169/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16495170/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16495172/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16495173/Log5.txt)
[Log.txt](https://github.com/user-attachments/files/16495177/Log.txt)

**Comment by allMagicNB** [comment]
？Point Cloud Library

**Comment by lactobionicAcid** [comment]
```
Ln56437
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000722000000, 209715200, 0) failed; error='页面文件太小，无法完成操作。' (DOS error/errno=1455)
```
疑似是你的页面文件（虚拟内存）炸了，将其调高试试。

**Comment by wuwenjun9939** [comment]
> ？Point Cloud Library

chatgpt是这样的.....

**Comment by wuwenjun9939** [comment]
> ```
> Ln56437
> OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000722000000, 209715200, 0) failed; error='页面文件太小，无法完成操作。' (DOS error/errno=1455)
> ```
> 
> 疑似是你的页面文件（虚拟内存）炸了，将其调高试试。

我所有的设置都是默认的啊

**Comment by allMagicNB** [comment]
这个错误只能由系统抛出，应与 PCL 无关且 PCL 无法解决。
