### ISSUE TITLE
羽翼城

### ISSUE THREAD

**Issue by t57282** [Hex-Dragon/PCL2#4414]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

羽翼城大佬做的steam加速器和PCL2正版的皮肤一进游戏正版皮肤消失

### 原因

这怎么解决？我两边都已经发过问羽翼成那边没回我想给你们提一下这个问题

**Comment by lactobionicAcid** [comment]
加速器导致的，与 PCL 无关

**Comment by wuyuncheng-26** [comment]
我以前和作者问过了，steamcommunity302 的 mc 加速是有 bug 的，总之你的 mc 访问本来就没问题就不要开启那个选项

**Comment by hejiehao** [comment]
因为 Java 不信任 Steamcommunity 302 的证书
