### ISSUE TITLE
[关闭]增添MCC披风翻译

### ISSUE THREAD

**Issue by ArgonTeam** [Hex-Dragon/PCL2#4417]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

原披风名称: MCC 15th Year
翻译后: MCC 15周年披风

### 原因

麻烦增添一下xD

**Comment by ArgonTeam** [comment]
看错了，已关闭此issues。

**Comment by wuyuncheng-26** [comment]
已有相关 PR，等待合并中（https://github.com/Hex-Dragon/PCL2/pull/4415）
