### ISSUE TITLE
新增   【 启动器下载mod时，自动跳转到对应版本文件夹】   的开关，并 【为自动版本跳转追加更显著提示】

### ISSUE THREAD

**Issue by gezinfly** [Hex-Dragon/PCL2#4418]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [x] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

+ 开关就是一个开关，开关【下载mod时自动验证mod版本并选择选择对应的版本文件夹】功能。

+ 原有跳转功能，应该要视带有连接器的forge加载器也算fabric加载器（带其他连接器其他mod加载器同理）。
+ 提示方面，建议（可选）：
   + 给一个弹窗糊脸上，提示：“您当前下载mod的版本与当前所选版本不对应，是否自动选择正确的版本”、【复选框】“始终自动选择合适的版本”，【按钮】“帮我自动选择”“保持在当前版本”“保持并关闭版本检测”。
   + 提示音（我也不知道该用什么提示音）。

   + 增加设置页面设置项（单选框）“检测并自动选择mod对应的版本文件夹”：
     + “始终自动选择合适的版本”（描述：当您下载mod时，总是自动检测mod适用的Minecraft版本和mod加载器（如Fabric、Forge、LittleLoader……）类型，寻找并自动下载到适合的版本文件夹内。）
     + “弹窗提示我”（描述：当您下载mod时，总是自动检测mod适用的Minecraft版本和mod加载器（如Fabric、Forge、LittleLoader……）类型，当发现要下载mod与当前版本不匹配时，弹窗征求您本次的处置意见，可以选择保持现有版本，或让启动器自动选择合适的版本。）
     + “关闭该功能”（描述：当您下载mod时，不再检测mod适用的Minecraft版本和mod加载器（如Fabric、Forge、LittleLoader……）类型是与当前版本否匹配。）

### 原因

平时我总是使用信雅互联，在forge版本中安装fabric mod。
此时，由于我要下载的是fabric mod，所以会被启动器自动跳转到fabirc版本。跳转过程提示很小，仅有一个蓝色文字框；资源管理器地址栏很小，平时不小心就没看清。于是我常常把mod安装到错误的版本，同时导致两个版本的游戏出问题。

平时如果安装的mod版本与当前版本不匹配，也会被跳转，由于提示过小，常常未被察觉。于是mod就安装到了不受控的位置上。~~_类比位置不受控造成隐患的指针叫“**野指针**”_，我把这种位置不知道安装到哪里去的mod叫做“**野mod**”~~

以目前社区动向来看，以后加载器之间的互联恐怕会成为常态。而“野mod”容易随机到不同的版本炸存档，危害极大。

**Comment by JingHai-Lingyun** [comment]
提案内容好长…… 让我仔细查重一下，稍等

**Comment by gezinfly** [comment]
和[这个](https://github.com/Hex-Dragon/PCL2/discussions/2423)在实现上有少量冲突，修改了同一个东西的不同部分

**Comment by allMagicNB** [comment]
应该不会为新雅互联单独做适配。

**Comment by Pigeon0v0** [comment]
从我个人层面也不想做信雅互联等连接器 Mod 的专门适配...

**Comment by wuyuncheng-26** [comment]
我似乎看懂了……
其实整体还是信雅互联的问题，给一个 Forge 版本装了信雅互联，启动器并不知道它可以装 Fabric Mod 了
毕竟这个版本本质上还是 Forge 版本，启动器认为只能装 Forge Mod，要避免你这种情况还得专门适配信雅互联

**Comment by JingHai-Lingyun** [comment]
> 应该要视带有连接器的forge加载器也算fabric加载器（带其他连接器其他mod加载器同理）。

信雅互联等 Mod 的兼容，请参见 https://github.com/Hex-Dragon/PCL2/issues/1536#issuecomment-1492867085

> 标题：为自动版本跳转追加更显著提示

请参见 https://github.com/Hex-Dragon/PCL2/issues/3328#issuecomment-1949227153
这是以 “你选择的是哪个版本的 Mod” 优先，而非 “你选择的是哪个 MC 版本” 优先，WAI
如有需要去那边追加回帖，谢谢。

**Comment by Pigeon0v0** [comment]
那先关了...？

**Comment by wuyuncheng-26** [comment]
> 那先关了...？

en，我认为可以

**Comment by gezinfly** [comment]
> > 应该要视带有连接器的forge加载器也算fabric加载器（带其他连接器其他mod加载器同理）。
> 
> 信雅互联等 Mod 的兼容，请参见 [#1536 (comment)](https://github.com/Hex-Dragon/PCL2/issues/1536#issuecomment-1492867085)
> 
> > 标题：为自动版本跳转追加更显著提示
> 
> 请参见 [#3328 (comment)](https://github.com/Hex-Dragon/PCL2/issues/3328#issuecomment-1949227153) 这是以 “你选择的是哪个版本的 Mod” 优先，而非 “你选择的是哪个 MC 版本” 优先，WAI 如确有需要去那边追加回帖，谢谢。

谢谢，两个issue均被关闭，无法回复

**Comment by JingHai-Lingyun** [comment]
> 谢谢，两个issue均被关闭，无法回复

关闭的 Issue 不影响你回帖…… 直接发就好，帖子都没锁……
这个关咯

**Comment by gezinfly** [comment]
> > 谢谢，两个issue均被关闭，无法回复
> 
> 关闭的 Issue 不影响你回帖…… 直接发就好，帖子都没锁…… 这个关咯

我已回帖至https://github.com/Hex-Dragon/PCL2/issues/3328#issuecomment-1949227153，谢谢。

并对
> 其实整体还是信雅互联的问题

做了反驳
