### ISSUE TITLE
披风列表没有MCC15周年披风

### ISSUE THREAD

**Issue by lieyanxd** [Hex-Dragon/PCL2#4419]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在官网www.minecraft.net中登录后发现账户内已经收到了MCC15周年披风
但是在pcl2里的披风列表却没有MCC披风

### 重现步骤

1.正版账户里有MCC披风
2.在pcl2里登录正版，点击披风列表

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16504516/Log1.txt)
![QQ截图20240806103402](https://github.com/user-attachments/assets/90059da8-ff80-445c-bd7d-0460eac469a3)
![QQ截图20240806103415](https://github.com/user-attachments/assets/82176915-ae58-4316-97eb-4f097ad8e0e9)

**Comment by allMagicNB** [comment]
给日志

**Comment by JingHai-Lingyun** [comment]
重新登陆一下试试看？

**Comment by lieyanxd** [comment]
> 重新登陆一下试试看？

重新打开pcl2解决了问题（话说加载披风列表怎么不自动刷新呢

**Comment by allMagicNB** [comment]
龙猫到处用缓存导致的。
