### ISSUE TITLE
任务管理器结束java进程后提示Minecraft已崩溃

### ISSUE THREAD

**Issue by ArgonTeam** [Hex-Dragon/PCL2#4420]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

任务管理器结束java进程后提示Minecraft已崩溃

### 重现步骤

1、正常启动游戏
2、使用任务管理器结束游戏进程

### 日志与附件

[Log5.txt](https://github.com/user-attachments/files/16504607/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/16504608/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16504609/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16504610/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16504611/Log4.txt)

**Comment by allMagicNB** [comment]
¿你别太离谱

**Comment by JingHai-Lingyun** [comment]
发一下你的 **Minecraft 日志**
按理来说应当是 #1855 中的情况

**Comment by ArgonTeam** [comment]
[bandicam 2024-08-06 10-51-40-365.zip](https://github.com/user-attachments/files/16504666/bandicam.2024-08-06.10-51-40-365.zip)
复现一下，就像这样。github不支持上载avi文件，我只能压缩为zip。

**Comment by hejiehao** [comment]
> 发一下你的 **Minecraft 日志** 按理来说应当是 #1855 中的情况

#1855 只是手动触发了崩溃，而不是强制结束任务

**Comment by allMagicNB** [comment]
发 latest.log

**Comment by JingHai-Lingyun** [comment]
> #1855 只是手动触发了崩溃，而不是强制结束任务

那边说的是 `在被任务管理器所结束的mc进程后`

**Comment by ArgonTeam** [comment]
[latest.log](https://github.com/user-attachments/files/16504693/latest.log)
latest.log

**Comment by JingHai-Lingyun** [comment]
OptiFine 干嘛呢这是……
好像能优化但又好像优化不了，给龙猫看看吧

**Comment by ArgonTeam** [comment]
这跟optifine无关。不管什么版本，只要任务管理器结束进程，100%提示崩溃

**Comment by allMagicNB** [comment]
# 这已经属于故意找茬，给龙猫看什么？

**Comment by ArgonTeam** [comment]
emmm。。。

**Comment by allMagicNB** [comment]
@ArgonTeam 你现在去皮肤站解绑你的 access_token 还来得及。

**Comment by ArgonTeam** [comment]
![无标题](https://github.com/user-attachments/assets/6dfdd6f9-eb85-45ab-9f1b-da27e662d62e)
啥意思？我希望他这样显示

**Comment by ArgonTeam** [comment]
我使用的是正版登录

> ~你现在去皮肤站解绑你的 access_token 还来得及。~ 你是皮肤站登录吗？ 你的 access_token 不知道为什么露出来了。

**Comment by allMagicNB** [comment]
你把你刚发的 latest.log 删掉还来得及，别人可以用这里面的信息登录游戏。

**Comment by ArgonTeam** [comment]
> 你把你刚发的 latest.log 删掉还来得及，别人可以用这里面的信息登录游戏。

啪的一下就删了

**Comment by ArgonTeam** [comment]
[latest.log](https://github.com/user-attachments/files/16504782/latest.log)
wo'ch我重新处理了一下

**Comment by ArgonTeam** [comment]
byd我有点事情，明天才能继续处理这个issues。需要哪些信息我尽快上传。

**Comment by zkitefly** [comment]
尝试高版本能否复现？

在任务管理器里退出日志显示游戏返回的退出值是 1，所以我认为没啥好办法检测是啥东西让游戏退出，我认为被拒的概率很大

**Comment by allMagicNB** [comment]
所以呢？不是已经被拒了吗……

**Comment by ArgonTeam** [comment]
都是一样，版本没关系，我猜结束之后pcl不知道是为什么突然检测不到游戏日志，就报游戏崩溃

**Comment by allMagicNB** [comment]
> 都是一样，版本没关系，我猜结束之后pcl不知道是为什么突然检测不到游戏日志，就报游戏崩溃

……这是检测返回值的，返回值为 0 代表正常返回，返回其他值代表不正常。

**Comment by Pigeon0v0** [comment]
这属于刻意触发...

**Comment by allMagicNB** [comment]
~~没法，叫好几遍都死活不关~~
