### ISSUE TITLE
省流：希望作者大大能够提供一些尝试重置皮肤加载相关的操作用于尝试消除此bug的产生甚至是找到bug产生的原因从根源修复bug。

### ISSUE THREAD

**Issue by FloatingLifeFS** [Hex-Dragon/PCL2#4422]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

省流：希望作者大大能够提供一些尝试重置皮肤加载相关的操作用于尝试消除此bug的产生甚至是找到bug产生的原因从根源修复bug。

一编：
Firefly
该名字有自定义皮肤(firefly.png)bug于
1.20.1-Forge_47.0.35-OptiFine_I5
版本中无法正常加载(离线登录)(多次不同对照实践后得出结论为仅该名字有此问题)，即便添加了
万用皮肤补丁
模组也无济于事,反而会出现非默认皮肤的bug贴图皮肤，将其bug贴图源文件在文件名不变的前提下将文件本体替换成(firefly.png)的数据后，可以发现游戏内皮肤贴图也更为(firefly.png)的样式，但模型加载默认为'Steve(粗手臂模型)'，作为适配'Alex(细手臂模型)'的(firefly.png)贴图在'Steve(粗手臂模型)'上显示时胳膊处有未覆盖的贴图镂空。
二编：
Firefly_StarRail
该名字后续也出现了一样(一类)的问题，与上文一样且在1.20.1-Forge_xxx-OptiFine_xxx类版本(可能并不仅限于此)都会出现，但回忆后根据更多的经历对照思考，得出新的结论(例如):
 操作:用名称(1)离线登录后进入存档1并开启局域网连接(局域网内玩家可联机加入存档的世界)，PCL启动器再次用名称(2)启动同一个版本然后联机加入存档1的世界。注:无论是否添加万用皮肤补丁模组导致的结果都是一样(一类)的。
 结果:名称(2)在以后任何时候单人离线登录启动版本进入任意存档，自定义皮肤都不可能正常显示(依然其它名字显示正常)。(上述操作(PS:操作者自认为很sb)像是一种施放诅咒的行为。)
我尝试了所有我能够尝试的删除文件重置(删除注册表以及删除MC的所有文件,或许还有与此bug有关的文件我没有找到并删除)的办法也无济于事。
这次的操作我用名称1和2的实例复现并保留了PCL启动器的日志(之前的日志都丢了)。
希望作者大大能够提供一些尝试重置皮肤加载相关的操作用于尝试消除此bug的产生甚至是找到bug产生的原因从根源修复bug。

### 重现步骤

 操作:用名称(1)离线登录后进入存档1并开启局域网连接(局域网内玩家可联机加入存档的世界)，PCL启动器再次用名称(2)启动同一个版本然后联机加入存档1的世界。注:无论是否添加万用皮肤补丁模组导致的结果都是一样(一类)的。
 结果:名称(2)在以后任何时候单人离线登录启动版本进入任意存档，自定义皮肤都不可能正常显示(依然其它名字显示正常)。

### 日志与附件

[Log2.txt](https://github.com/user-attachments/files/16506269/Log2.txt)
[Log1.txt](https://github.com/user-attachments/files/16506270/Log1.txt)

**Comment by JingHai-Lingyun** [comment]
~~妈呀……又一个巨长的反馈……~~
容我仔细看看

**Comment by JingHai-Lingyun** [comment]
你的皮肤加载方式是 `正版玩家名字` 还是 `自定义文件`？我看到两个名字都有对应的正版 UUID

**Comment by FloatingLifeFS** [comment]
> 你的皮肤加载方式是 `正版玩家名字` 还是 `自定义文件`？我看到两个名字都有对应的正版 UUID
> 
> > 名称(2)在以后任何时候单人离线登录启动版本进入任意存档
> 
> 我没法理解这是怎么回事

是自定义文件

**Comment by FloatingLifeFS** [comment]
> > 你的皮肤加载方式是 `正版玩家名字` 还是 `自定义文件`？我看到两个名字都有对应的正版 UUID
> > > 名称(2)在以后任何时候单人离线登录启动版本进入任意存档
> > 
> > 
> > 我没法理解这是怎么回事
> 
> 是自定义文件

都是用的离线登录，再次启动同一版本可以理解为我双开启动了这个版本

**Comment by lactobionicAcid** [comment]
![image](https://github.com/user-attachments/assets/5d8fc8f0-5c6b-4ab0-ba67-3c2d356a01e5)
请尝试使用 1.19.2 以下的版本进行复现。_虽然我不能确定是这个导致的..._

**Comment by JingHai-Lingyun** [comment]
~~以下内容均属 Bug 的猜测，我也不知道为什么会发生这样的问题~~
我看到你使用了用户名 `1` 和 `2`，这与上述描述的不同，在此种情况下 Bug 仍然产生吗？
目前 PCL 使用了材质包来自定义皮肤，确认材质包加载了吗？

**Comment by youzi-2333** [comment]
根据我个人的理解，第一个问题是由于 PCL 目前还不支持高版本（1.19.3+）离线皮肤，请到 #1596 投票。

第二个问题参考 https://github.com/Hex-Dragon/PCL2/issues/4422#issuecomment-2270518376，确认材质包成功加载。

**Comment by wuliaodexiaoluo** [comment]
>模组也无济于事,反而会出现非默认皮肤的bug贴图皮肤，将其bug贴图源文件在文件名不变的前提下将文件本体替换成(firefly.png)的数据后，可以发现游戏内皮肤贴图也更为(firefly.png)的样式，但模型加载默认为'Steve(粗手臂模型)'，作为适配'Alex(细手臂模型)'的(firefly.png)贴图在'Steve(粗手臂模型)'上显示时胳膊处有未覆盖的贴图镂空。

因为 Minecraft 基于 UUID 来判断皮肤的适用模型，但是 1.19.3 开始 UUID 的生成规范变了，导致 PCL 现有的生成算法无法生成对 1.19.3 及以上版本来说有效的 UUID ，所以在强行使其显示的情况下可能存在渲染和贴图错误

>结果:名称(2)在以后任何时候单人离线登录启动版本进入任意存档，自定义皮肤都不可能正常显示(依然其它名字显示正常)。(上述操作(PS:操作者自认为很sb)像是一种施放诅咒的行为。)

如果是在另一个玩家视角内皮肤无法正常加载，这是因为万用皮肤补丁只对客户端登录的玩家生效，其他人看到的依旧也只能是默认皮肤

>我尝试了所有我能够尝试的删除文件重置(删除注册表以及删除MC的所有文件,或许还有与此bug有关的文件我没有找到并删除)的办法也无济于事。

文件修改和重载不可能解决此问题，因为解决问题的前提条件是 PCL 能够生成正确的 UUID ，但问题是这个生成算法本身（对于 1.19.3 及以上版本来说）就是错的，PCL 不太可能用错的算法生成有效的 UUID

> 结果:名称(2)在以后任何时候单人离线登录启动版本进入任意存档，自定义皮肤都不可能正常显示(依然其它名字显示正常)

这是预期行为，因为联机的自定义（指皮肤、披风）需要验证账号所有权并由验证服务器下发皮肤等资源文件，在没有登录的情况下无法从服务器获取到内容，所以会显示默认皮肤，至少在我看来这个逻辑并没有错误

**Comment by FloatingLifeFS** [comment]
> > 模组也无济于事,反而会出现非默认皮肤的bug贴图皮肤，将其bug贴图源文件在文件名不变的前提下将文件本体替换成(firefly.png)的数据后，可以发现游戏内皮肤贴图也更为(firefly.png)的样式，但模型加载默认为'Steve(粗手臂模型)'，作为适配'Alex(细手臂模型)'的(firefly.png)贴图在'Steve(粗手臂模型)'上显示时胳膊处有未覆盖的贴图镂空。
> 
> 因为 Minecraft 基于 UUID 来判断皮肤的适用模型，但是 1.19.3 开始 UUID 的生成规范变了，导致 PCL 现有的生成算法无法生成对 1.19.3 及以上版本来说有效的 UUID ，所以在强行使其显示的情况下可能存在渲染和贴图错误
> 
> > 结果:名称(2)在以后任何时候单人离线登录启动版本进入任意存档，自定义皮肤都不可能正常显示(依然其它名字显示正常)。(上述操作(PS:操作者自认为很sb)像是一种施放诅咒的行为。)
> 
> 如果是在另一个玩家视角内皮肤无法正常加载，这是因为万用皮肤补丁只对安装此补丁的客户端登录的玩家生效，其他人看到的依旧也只能是默认皮肤
> 
> > 我尝试了所有我能够尝试的删除文件重置(删除注册表以及删除MC的所有文件,或许还有与此bug有关的文件我没有找到并删除)的办法也无济于事。
> 
> 文件修改和重载不可能解决此问题，因为解决问题的前提条件是 PCL 能够生成正确的 UUID ，但问题是这个生成算法本身（对于 1.19.3 及以上版本来说）就是错的，PCL 不太可能用错的算法生成有效的 UUID
> 
> > 结果:名称(2)在以后任何时候单人离线登录启动版本进入任意存档，自定义皮肤都不可能正常显示(依然其它名字显示正常)
> 
> 这是预期行为，因为联机的自定义（指皮肤、披风）需要验证账号所有权并由验证服务器下发皮肤等资源文件，在没有登录的情况下无法从服务器获取到内容，所以会显示默认皮肤，至少在我看来这个逻辑并没有错误
> 
> > 省流：希望作者大大能够提供一些尝试重置皮肤加载相关的操作用于尝试消除此bug的产生甚至是找到bug产生的原因从根源修复bug。
> 
> 我认为 Issue 提到的解决方案不太可能解决此问题

但是我用没有重复启动版本进入同一联机存档的民资离线登录

> ### 检查项
> * [x]  我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。
> 
> ### 描述
> 省流：希望作者大大能够提供一些尝试重置皮肤加载相关的操作用于尝试消除此bug的产生甚至是找到bug产生的原因从根源修复bug。
> 
> 一编： Firefly 该名字有自定义皮肤(firefly.png)bug于 1.20.1-Forge_47.0.35-OptiFine_I5 版本中无法正常加载(离线登录)(多次不同对照实践后得出结论为仅该名字有此问题)，即便添加了 万用皮肤补丁 模组也无济于事,反而会出现非默认皮肤的bug贴图皮肤，将其bug贴图源文件在文件名不变的前提下将文件本体替换成(firefly.png)的数据后，可以发现游戏内皮肤贴图也更为(firefly.png)的样式，但模型加载默认为'Steve(粗手臂模型)'，作为适配'Alex(细手臂模型)'的(firefly.png)贴图在'Steve(粗手臂模型)'上显示时胳膊处有未覆盖的贴图镂空。 二编： Firefly_StarRail 该名字后续也出现了一样(一类)的问题，与上文一样且在1.20.1-Forge_xxx-OptiFine_xxx类版本(可能并不仅限于此)都会出现，但回忆后根据更多的经历对照思考，得出新的结论(例如): 操作:用名称(1)离线登录后进入存档1并开启局域网连接(局域网内玩家可联机加入存档的世界)，PCL启动器再次用名称(2)启动同一个版本然后联机加入存档1的世界。注:无论是否添加万用皮肤补丁模组导致的结果都是一样(一类)的。 结果:名称(2)在以后任何时候单人离线登录启动版本进入任意存档，自定义皮肤都不可能正常显示(依然其它名字显示正常)。(上述操作(PS:操作者自认为很sb)像是一种施放诅咒的行为。) 我尝试了所有我能够尝试的删除文件重置(删除注册表以及删除MC的所有文件,或许还有与此bug有关的文件我没有找到并删除)的办法也无济于事。 这次的操作我用名称1和2的实例复现并保留了PCL启动器的日志(之前的日志都丢了)。 希望作者大大能够提供一些尝试重置皮肤加载相关的操作用于尝试消除此bug的产生甚至是找到bug产生的原因从根源修复bug。
> 
> ### 重现步骤
> 操作:用名称(1)离线登录后进入存档1并开启局域网连接(局域网内玩家可联机加入存档的世界)，PCL启动器再次用名称(2)启动同一个版本然后联机加入存档1的世界。注:无论是否添加万用皮肤补丁模组导致的结果都是一样(一类)的。 结果:名称(2)在以后任何时候单人离线登录启动版本进入任意存档，自定义皮肤都不可能正常显示(依然其它名字显示正常)。
> 
> ### 日志与附件
> [Log2.txt](https://github.com/user-attachments/files/16506269/Log2.txt) [Log1.txt](https://github.com/user-attachments/files/16506270/Log1.txt)

三编：
补充说明，当换名字重复离线登录同一版本后进入联机后才会导致后续这个名字单独离线启动进入单人存档不能正常加载自定义皮肤，我猜想可能是因为在重复启动版本时两个名字进入同一存档世界(房主和成员)加载离线自定义皮肤时产生了文件冲突导致成员名字的皮肤加载出问题。重置版本后该名字也永久保留了此问题的存在，我想可能是某处保留了导致此问题出现的文件或者是程序代码等，我希望通过重置来消除此问题。
PS:我这个问题真的不是因为1.19.2版本以上的原因导致的，因为没有被“诅咒”过的名字的皮肤显示是正常的！

**Comment by JingHai-Lingyun** [comment]
仍然无法理解为何会发生，怀疑是特殊名字（UUID）导致的……

**Comment by FloatingLifeFS** [comment]
1.19版本也会出现此问题

**Comment by FloatingLifeFS** [comment]
我实在是不知道怎么描述这个问题了。
不如：我请求能够被提供如何彻底让电脑恢复至从未安装和启动过PCL启动器和MC的状态，(删除PCL注册表以及PCL启动器所在文件夹的全部与之相关的文件的操作我会，但貌似还有其它与PCL启动器和MC相关的文件藏在了我未知的某处)

**Comment by FloatingLifeFS** [comment]
我实在是不知道怎么描述这个问题了。
不如：我请求能够被提供彻底让电脑恢复至从未安装和启动过PCL启动器和MC的状态的操作。(删除PCL注册表以及PCL启动器所在文件夹的全部与之相关的文件的操作我会，但貌似还有其它与PCL启动器和MC相关的文件藏在了我未知的某处)

**Comment by allMagicNB** [comment]
> 我实在是不知道怎么描述这个问题了。
> 不如：我请求能够被提供彻底让电脑恢复至从未安装和启动过PCL启动器和MC的状态的操作。(删除PCL注册表以及PCL启动器所在文件夹的全部与之相关的文件的操作我会，但貌似还有其它与PCL启动器和MC相关的文件藏在了我未知的某处)

#235

**Comment by LTCatt** [comment]
如果使用了自定义文件的皮肤，请把该文件上传上来，以便我们重现

**Comment by LTCatt** [comment]
由于长期未回复暂时关闭。
如果想回了可以接着在这里回复，不需要重开一个 issue（
