### ISSUE TITLE
功能与个性化：增加一个新EventType用于刷新帮助库的xaml页面

### ISSUE THREAD

**Issue by Joker2184** [Hex-Dragon/PCL2#4423]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

刷新帮助库页面：增加一个新EventType，以支持在帮助库界面直接刷新xaml并展示 功能类似刷新主页

### 原因

刷新帮助库：目前在编写帮助库来为自玩服写些知识但是每次更新点什么就得从xaml界面退出然后点帮助的刷新再进去查看效果
这样很麻烦能不能提供一个刷新帮助来帮助我们可以更简洁的刷新页面（目前的刷新主页只能刷新主页文件

**Comment by lactobionicAcid** [comment]
PCL2 支持自定义“你知道吗”的内容，并且只要启动游戏就能看到......

**Comment by Deep-Dark-Forest** [comment]
> PCL2 支持自定义 “你知道吗?” 的内容，并且只要启动游戏或更换主页预设就能看到......

他说自定义回声洞而不是自定义“你知道吗”

**Comment by Deep-Dark-Forest** [comment]
> 支持回声洞自定义 做成类似你知道吗那样的添加文件后PCL读取并展示

#1021 已被拒
~~您自己交的 issue怎么都忘了~~

**Comment by Joker2184** [comment]
> > 支持回声洞自定义 做成类似你知道吗那样的添加文件后PCL读取并展示
> 
> #1021 已被拒 ~您自己交的 issue 怎么都忘了~ 为 “刷新帮助库页面” 添加 “等待确认”……

SORRY(忘了

**Comment by LTCatt** [comment]
按 F5 可以刷新本地帮助页面（不会重新下载联网帮助页面）。
将在 2.8.10 加入。
