### ISSUE TITLE
下载时卡住或失败

### ISSUE THREAD

**Issue by t57282** [Hex-Dragon/PCL2#4425]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

下原版的时候没有任何问题，下了个mod加载器 forge他就下载不了，进游戏也是没问题。
![屏幕截图 2024-08-06 170100](https://github.com/user-attachments/assets/43f619cd-0428-46b8-af74-38406fac3c9f)

### 重现步骤

1、点击游戏

### 日志与附件

[Log3.txt](https://github.com/user-attachments/files/16508195/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16508196/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16508197/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/16508198/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16508199/Log2.txt)

**Comment by t57282** [comment]
![屏幕截图 2024-08-06 171516](https://github.com/user-attachments/assets/9236db41-40bc-4bfa-857d-17670ed314bd)
下原版没加任何东西都是没问题的。

**Comment by Ad-closeNN** [comment]
这大概率是网络问题
![image](https://github.com/user-attachments/assets/ed22a909-6ba9-4f7e-af79-4b44432ca3d4)

**Comment by t57282** [comment]
这才是网络问题
![Uploading 屏幕截图 2024-08-06 181144.png…]()

**Comment by JingHai-Lingyun** [comment]
这是什么文件啊…… `.tsrg`

**Comment by Deep-Dark-Forest** [comment]
> 这才是网络问题
> ![Uploading 屏幕截图 2024-08-06 181144.png…]()
> 

你的截图未上传成功。
请在 Uploading XXXX 消失以后再点击绿色按钮

**Comment by t57282** [comment]
![Uploading 屏幕截图 2024-08-06 181144.png…]()

**Comment by t57282** [comment]
![屏幕截图 2024-08-06 181144](https://github.com/user-attachments/assets/43e7f147-12a0-45d2-b9ff-a4fa640a0790)

**Comment by JingHai-Lingyun** [comment]
虽然看起来像是网络错误，但是下载了一个非常奇怪的文件，仍然挂在这里给龙猫看看？

**Comment by t57282** [comment]
你没看它上面说的是返回错误

**Comment by wuyuncheng-26** [comment]
网络问题……？换个网试试

**Comment by wuliaodexiaoluo** [comment]
<details>
<summary>图片</summary>

![image](https://github.com/user-attachments/assets/b4419856-2584-4418-a76a-853566a204b6)

![image](https://github.com/user-attachments/assets/e02717bd-c21d-45eb-a8dc-72db5b210c08)

</details>

BMCLAPI 和 Mojang API 均没有提供这个文件，所以这个文件到底是什么？

**Comment by lactobionicAcid** [comment]
> BMCLAPI 和 Mojang API 均没有提供这个文件，所以这个文件到底是什么？

这是 Mappings [映射](https://fabricmc.net/wiki/zh_cn:tutorial:mappings)文件...?

**Comment by wuliaodexiaoluo** [comment]
>虽然看起来像是网络错误，但是下载了一个非常奇怪的文件，仍然挂在这里给龙猫看看？

这个奇怪的文件应该是对应版本 json 文件的 client.txt 文件，是 Minecraft 官方提供的混淆表，用于反编译文件后的类名转换
但很奇怪的是为什么到了 bmclapi 就变成了 `.tsrg` 后缀的文件

![image](https://github.com/user-attachments/assets/bebd950e-7ef6-485d-a01d-961e7e6a8f63)

**Comment by hejiehao** [comment]
Forge 行为

**Comment by wuyuncheng-26** [comment]
> > 虽然看起来像是网络错误，但是下载了一个非常奇怪的文件，仍然挂在这里给龙猫看看？
> 
> 这个奇怪的文件应该是对应版本 json 文件的 client.txt 文件，是 Minecraft 官方提供的混淆表，用于反编译文件后的类名转换 但很奇怪的是为什么到了 bmclapi 就变成了 `.tsrg` 后缀的文件

是时候 @bangbang93 来看看了

**Comment by bangbang93** [comment]
我没看懂，这到底是在下哪个文件

**Comment by lactobionicAcid** [comment]
BMCLAPI 上是有这个文件的，并且其请求格式和官方下载源是一样的，
`https://bmclapi2.bangbang93.com/v1/objects/0530a206839eb1e9b35ec86acbbe394b07a2d9fb/client.txt`

但是 PCL 向 BMCLAPI 请求了下面两个空地址...
`https://bmclapi2.bangbang93.com/maven/net/minecraft/client/1.21/client-1.21-mappings.tsrg`
`https://bmclapi2.bangbang93.com/libraries/net/minecraft/client/1.21/client-1.21-mappings.tsrg`

**Comment by t57282** [comment]
PCL 识别码

**Comment by hejiehao** [comment]
> PCL 识别码

请发送识别码以获取活跃橙

**Comment by t57282** [comment]
D945-8A40-8539-C218

**Comment by t57282** [comment]
> > PCL 识别码
> 
> 请发送识别码以获取活跃橙

D945-8A40-8539-C218

**Comment by t57282** [comment]
PCL 识别码：D945-8A40-8539-C218

**Comment by WForst-Breeze** [comment]
> PCL 识别码：D945-8A40-8539-C218

解锁码发送是龙猫手动操作的，可能需要等待一段时间，谢谢理解~！

**Comment by t57282** [comment]
好的龙猫辛苦了。

**Comment by LTCatt** [comment]
你的解锁码：QzucIDEdEQlrSNBauzkn83ywZXy6Xh4q
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
