### ISSUE TITLE
添加联机功能

### ISSUE THREAD

**Issue by liuyufan130722** [Hex-Dragon/PCL2#4426]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

建议添加一个联机功能，让在各地的朋友们一起游玩，添加如大厅里类似的界面，可以让玩家们交朋友，可以添加个人标签等元素。

### 原因

（示例）
我需要这个功能来联机。很多人都有一起联机的需求，但如果没有这个功能，我们就需要
搭建内网穿透或购买服务器来一起联机，这样大家可以以更低成本来进行联机。

**Comment by wuyuncheng-26** [comment]
猫曰：至于联机，因为网易还在继续代理中国版，我和 HMCL 的维护者都觉得还得谨慎一点……况且现在也有 Mod 支持联机了……咳咳。

**Comment by wuyuncheng-26** [comment]
@JingHai-Lingyun 在吗，来加个 label（

**Comment by wuliaodexiaoluo** [comment]
打重复（
