### ISSUE TITLE
[不是 PCL 的 Bug] lanzouv.com 疑似成为敏感词，在爱发电上显示不了

### ISSUE THREAD

**Issue by wuyuncheng-26** [Hex-Dragon/PCL2#4430]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/user-attachments/assets/168d8785-6a64-4e62-829e-c02436d50f52)
`***` 应为 `lanzouv.com`
被爱发电给当作敏感词消除了？

### 重现步骤

https://afdian.com/p/0164034c016c11ebafcb52540025c377
下载地址 1

### 日志与附件

![image](https://github.com/user-attachments/assets/89d5d8a3-9119-49d5-ad05-031d391095c5)

**Comment by wuyuncheng-26** [comment]
是我发现的 Bug，在群里说了一下，[hejiehao](https://github.com/hejiehao) 就直接发了（#4429）
真不是重复（

**Comment by wuyuncheng-26** [comment]
@LTCatt 麻烦龙猫大大了 orz

**Comment by hejiehao** [comment]
![image](https://github.com/user-attachments/assets/3de7acdc-d739-4453-8028-410aca1948e4)
看起来龙猫早就知道这玩应被和谐了

**Comment by hejiehao** [comment]
龙猫应该已经知道这玩应被和谐了

**Comment by wuyuncheng-26** [comment]
也许不是 `lanzouf.com`，毕竟蓝奏云那么多后缀（
