### ISSUE TITLE
整合包搜索界面中的Kitchen Sink类型被意外译为烹饪

### ISSUE THREAD

**Issue by Chiloven945** [Hex-Dragon/PCL2#4435]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

根据 Modrinth 的整合包筛选列表及筛选出的搜索结果来看，的确应为Kitchen Sink（水槽包）。
<img src="https://github.com/user-attachments/assets/678ef485-9da4-4212-a950-0bf577a782f7" height=300><img src="https://github.com/user-attachments/assets/9a521701-28a4-439c-9d40-dcac82042a54" height=300><img src="https://github.com/user-attachments/assets/85ec4d5c-c282-415c-bca9-50c2d57f9c8d" height=200>

### 重现步骤

整合包搜索界面。

### 日志与附件

_

**Comment by hejiehao** [comment]
水槽包这个翻译有点奇怪
我感觉翻译成大杂烩比较好（？

**Comment by Chiloven945** [comment]
> 水槽包这个翻译有点奇怪 我感觉翻译成大杂烩比较好（？

社区已有的翻译是水槽包，没记错的话

**Comment by hejiehao** [comment]
~~没想到 HMCL 的翻译和我想的翻译一样~~
