### ISSUE TITLE
能不能再设置（非版本设置）中添加全局使用xxx登录

### ISSUE THREAD

**Issue by woniusheji** [Hex-Dragon/PCL2#4442]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在设置里面（非版本设置）添加登录方式选项，版本设置中登录方式添加一个使用全局设置
我想用LittleSkin账号登录全部版本

### 原因

这项优化让我可以更方便地登录LittleSkin
如果没有这项优化，我每次下载一个版本都必须设置登录方式，让操作变得很麻烦。

**Comment by allMagicNB** [comment]
#57（#58）
