### ISSUE TITLE
Minecraft创建世界时，PCL提示提示游戏已崩溃，但游戏仍在正常创建世界

### ISSUE THREAD

**Issue by kmerc224** [Hex-Dragon/PCL2#4443]
### 检查项

- [ ] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃基本不是 PCL 的原因，请 **不要** 提交反馈。你可以在论坛或社区找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用 HMCL 启动，HMCL 没有出现问题。** 如果 HMCL 也无法启动就不是 PCL 导致的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

本人启动游戏时添加了模组：我的世界铁路、Fabric API、Architectury API；Mod加载器：Fabric；游戏版本：1.18.2
由于电脑配置不怎么好，创建世界、启动游戏时游戏总是会“未响应”一小段时间，但游戏仍可以正常游玩
但今天，我像往常一样创建世界去玩，游戏在创建世界时，同样未响应了一段时间，但PCL突然提示了游戏崩溃的信息，于是我想在Mod设置中减少一些模组但突然发现游戏已经进入了创建好的新世界。

### PCL 错误报告、日志与附件

[Log1.txt](https://github.com/user-attachments/files/16537331/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16537332/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16537334/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16537336/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16537337/Log5.txt)

### HMCL 启动脚本

[1.18.2.bat](https://github.com/user-attachments/files/16537327/1.18.2.txt)

**Comment by allMagicNB** [comment]
HMCL 会提示吗？

**Comment by JingHai-Lingyun** [comment]
Minecraft 日志[^1]发过来看看

[^1]:PCL 启动器 -> 版本设置 -> 版本文件夹 -> `logs` 文件夹 -> `latest.log` 或你触发 Bug 那次的日志压缩包

**Comment by kmerc224** [comment]
> Minecraft 日志[1](#user-content-fn-1-e6482e007f4645c03e6a31aad260ee96)发过来看看
> 
> ## Footnotes
> 1. PCL 启动器 -> 版本设置 -> 版本文件夹 -> `logs` 文件夹 -> `latest.log` 或你触发 Bug 那次的日志压缩包 [↩](#user-content-fnref-1-e6482e007f4645c03e6a31aad260ee96)

Minecraft已经正常运行了，应该不用发了吧，而且我的电脑也出现问题重装系统了，Minecraft日志应该已经不复存在了。我觉得可以把检测Minecraft崩溃或退出的方法改为检测javaw.exe进程

**Comment by JingHai-Lingyun** [comment]
Minecraft 正常的话那就关咯

---

> 把检测Minecraft崩溃或退出的方法改为检测javaw.exe进程

我不太清楚目前是什么检测方式，如果需要的话另外开优化反馈，感谢合作

**Comment by kmerc224** [comment]
对了我还想顺口说一句，我还遇到过javaw.exe进程已经结束了，PCL还不显示Minecraft已崩溃的信息

**Comment by kmerc224** [comment]
> Minecraft 正常的话那就关咯
> 
> > 把检测Minecraft崩溃或退出的方法改为检测javaw.exe进程
> 
> 我不太清楚目前是什么检测方式，如果需要的话另外开优化反馈，感谢合作

其实我也不懂，这种应该是概率发生的,也不用针对我来修BUG

**Comment by kmerc224** [comment]
> Minecraft 正常的话那就关咯
> 
> > 把检测Minecraft崩溃或退出的方法改为检测javaw.exe进程
> 
> 我不太清楚目前是什么检测方式，如果需要的话另外开优化反馈，感谢合作

其实我也不懂，这种应该是概率发生的,也不用针对我来修BUG

**Comment by allMagicNB** [comment]
没重就别关，重了先找出 Issue 编号。
