### ISSUE TITLE
自定义主页点击“回声洞”时不要刷新主页

### ISSUE THREAD

**Issue by lyzzs10** [Hex-Dragon/PCL2#4444]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

希望用XAML把回声洞放在主页上并点击刷新时，刷新的是整个主页而不是单独一项回声洞，因为刷新之后对主页的更改会被刷新回初始（如在高速下载里面输入的东西会消失、打开默认闭合的文本框在刷新之后会重新闭合等）

最好是和百宝箱里面的回声洞一样之刷新单个百宝箱而不是刷新整个主页页面

### 原因

~~这项优化让我可以更愉快的在主页上刷回声洞~~

**Comment by LTCatt** [comment]
不好实现，抱歉（
