### ISSUE TITLE
你的 赞助网页怎么还崩了

### ISSUE THREAD

**Issue by fufumo** [Hex-Dragon/PCL2#4445]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

点击关于鸣谢->赞助作者
网页打不开

### 重现步骤

点击关于鸣谢->赞助作者

### 日志与附件

No

**Comment by Ad-closeNN** [comment]
#4271

**Comment by allMagicNB** [comment]
你应该没有瞎，这个 Issue 已经置顶了，可是为什么你还是没看见？

**Comment by fufumo** [comment]
> 你应该没有瞎，这个 Issue 已经置顶了，可是为什么你还是没看见？

6，我确实没看见，但我现在无所谓了，就当我瞎了

**Comment by fufumo** [comment]
> #4271 afdian.net >> [afdian.com](https://afdian.com) 或者 [ifdian.net](https://ifdian.net) 下个版本就链接就正确了
> 
> ~话说author你是真的认真看了吗它其实就在置顶~ ![image](https://private-user-images.githubusercontent.com/103355026/356238937-79460cfe-5561-4427-9399-71f44a9b6f13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMjQxMjQsIm5iZiI6MTcyMzEyMzgyNCwicGF0aCI6Ii8xMDMzNTUwMjYvMzU2MjM4OTM3LTc5NDYwY2ZlLTU1NjEtNDQyNy05Mzk5LTcxZjQ0YTliNmYxMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQxMzMwMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDhmODg2NGI1OTZmN2YxNGVhYzA1MTVkZGZlYjllYzQ2MjhiNmZmNDg4Y2UxYTgwNzQ5ZWZiYWIyODgwZTJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dpUSc_5ryCWGHXoQE8W4N9dLqosvJZMBy-TRlKv1nOk)

因为我没有注意上面，我直接在搜索栏搜的，没搜到，就反馈了

**Comment by Ad-closeNN** [comment]
@fufumo 你试试点这个？
![image](https://github.com/user-attachments/assets/0eebda01-5360-4a70-9070-bb868cd34a1f)

**Comment by hejiehao** [comment]
> 你应该没有瞎

请不要辱骂别人
