### ISSUE TITLE
统一验证登录java最低版本判断修改

### ISSUE THREAD

**Issue by CrazyNutLz** [Hex-Dragon/PCL2#4446]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

        '统一通行证检测
        If Setup.Get("LoginType") = McLoginType.Nide Then
            '至少 Java 8u141
            MinVer = If(New Version(1, 8, 0, 141) > MinVer, New Version(1, 8, 0, 141), MinVer)
        End If

最低需要141及以上的java  并非统一验证文档中的101

### 重现步骤

1、点击xxxx
2、往下滚，然后点击xxxx

### 日志与附件

        '统一通行证检测
        If Setup.Get("LoginType") = McLoginType.Nide Then
            '至少 Java 8u141
            MinVer = If(New Version(1, 8, 0, 141) > MinVer, New Version(1, 8, 0, 141), MinVer)
        End If

最低需要141及以上的java  并非统一验证文档中的101

**Comment by CrazyNutLz** [comment]
> Please provide the source. 请提供消息来源。

emm  没啥具体的消息来源- -  服务器玩家这边的反馈和自己的测试  基本都要200+的java才能正常运行。。
可以测试一下

**Comment by allMagicNB** [comment]
https://login.mc-user.com:233/index/doc

**Comment by CrazyNutLz** [comment]
> > [login.mc-user.com:233/index/doc](https://login.mc-user.com:233/index/doc)
> 
> I have seen this but it says 8u101.

统一那边的文档和说明都N年没更新过了。。。我也再给那边反馈

**Comment by Ad-closeNN** [comment]
https://www.oracle.com/java/technologies/javase/javase8-archive-downloads.html

**Comment by Ad-closeNN** [comment]
我的方法有误？~~（大概率是我理解错了）~~ 还是说java 8u100+进到指定的服务器登录无效（
[Log1.txt](https://github.com/user-attachments/files/16550517/Log1.txt)
![image](https://github.com/user-attachments/assets/af2fd573-e24f-4068-90c4-8dae86ec49fe)
![image](https://github.com/user-attachments/assets/b63ae00b-291d-464c-8e62-5c3f2551446d)

**Comment by CrazyNutLz** [comment]
启动是可以正常启动的，启动器也可以正常登录，但是登陆后多人游戏左上角无法连接，服务器也无法进入
![{23FEF76E-7F64-2474-974F-04C861B98AA2}](https://github.com/user-attachments/assets/6e70d305-a421-47b7-8b84-26052c4554d3)
@Ad-closeNN

**Comment by CrazyNutLz** [comment]
![QQ20240809-000624](https://github.com/user-attachments/assets/7f6af6e9-dfba-47d6-bf54-979d46564a34)
![QQ20240809-000721](https://github.com/user-attachments/assets/61e383ad-23bd-4bda-a327-5a5b631ca3bd)

**Comment by CrazyNutLz** [comment]
![d9a7b9ebb8298ba512f83237f622ba98](https://github.com/user-attachments/assets/d6feea00-d50e-4773-aaa2-e46c50670056)
详细挨个测试了一下，最低版本141可以正常使用，131及以下就不行了，并不是文档中所说的101
@3gf8jv4dv

**Comment by CrazyNutLz** [comment]
识别码：5360-855E-F4F0-255F
谢谢龙猫大大  @LTCatt

**Comment by LTCatt** [comment]
你的解锁码：s8W9sHMsWUqAmYGJBtICpNFjBAWj7v0M
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
