### ISSUE TITLE
PCL快照版在当前文件夹有公测._cache_xxx文件时不会新生成而是直接读取

### ISSUE THREAD

**Issue by Joker2184** [Hex-Dragon/PCL2#4450]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

会让快照PCL变成公测版（

### 重现步骤

[测验文件夹：桌面]
1.启动公测版PCL 如果当前文件夹没有._cache_Plain xxxx这个文件时他会新生成一个文件（隐藏文件
2.如果复制一个快照版到桌面上启动 快照版貌似不会生成新的上述文件（
3.复制过去的快照版有几率在第一次启动时显示正常 有快照提示 版本号显示snapshot 第二次启动后快照提示消失 版本号变成release
（不知道算不算bug 问问想法

### 日志与附件

应该不需要不涉及log

**Comment by kong-que-dnf123** [comment]
._cache_不是病毒前缀码...
https://github.com/Hex-Dragon/PCL2/issues/2964#issuecomment-1858847051
