### ISSUE TITLE
BMCLAPI 某文件的请求数异常

### ISSUE THREAD

**Issue by LTCatt** [Hex-Dragon/PCL2#4452]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![3~DA$GX PDWBZ{T3V@{7`P5_tmb](https://github.com/user-attachments/assets/6a2fef73-fe1e-4a5f-af75-9aa09acc0681)

**Comment by LTCatt** [comment]
umm 需要一个和这个文件相关的 log……
PCL 在最极端情况下会每 256KB 分一个线程，除非文件 >500M 不然也不太会这样（

**Comment by ZeroWolf233** [comment]
~~不能是被打了罢~~

**Comment by LTCatt** [comment]
如果有 PCL 的 log 我再看看，先关了（

**Comment by SALTWOOD** [comment]
所以是怎么个问题？没看懂
