### ISSUE TITLE
pcl2管理员模式启动后无法更改背景图片显示没有权限

### ISSUE THREAD

**Issue by shehuizhuyi1991** [Hex-Dragon/PCL2#4453]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

<img width="336" alt="屏幕截图 2024-08-09 174933" src="https://github.com/user-attachments/assets/80b8e26c-83de-4db8-a121-a6d6d982bff4">
<img width="608" alt="屏幕截图 2024-08-09 174928" src="https://github.com/user-attachments/assets/b73b9f45-a9e1-421e-b887-675a52f66102">

### 重现步骤

1、手动删除文件夹中的图片后再添加新图片就会出现这种情况

### 日志与附件

[Log5.txt](https://github.com/user-attachments/files/16559503/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/16559504/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16559505/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16559506/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16559507/Log4.txt)

**Comment by kong-que-dnf123** [comment]
`[17:51:46.616] [Start] 管理员权限：False`
真给了管理员吗...?

**Comment by wuyuncheng-26** [comment]
看你这 log，并没有开启管理员权限啊

**Comment by SALTWOOD** [comment]
看样子并没有给予管理员权限。请检查以下此项：
1. 是否通过右键 PCL.exe **本体**使用管理员权限
2. 更换电脑、删除目录重新新建、给 PCL 挪一个窝

如果确定是用户侧问题的话就可以关了

**Comment by Deep-Dark-Forest** [comment]
超时关闭。
