### ISSUE TITLE
可以为PCL个性化-背景图片增加对GIF动画支持吗？

### ISSUE THREAD

**Issue by BabyYi99** [Hex-Dragon/PCL2#4454]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

可以给PCL拥有一个”动态壁纸“

### 原因

这样可以拥有一个动态的启动器...好看

**Comment by allMagicNB** [comment]
#116
