### ISSUE TITLE
对于 “缺少 Java 时自动下载” 的功能，似乎可以直接使用 Oracle 提供的 JDK 直链而非手动更新的链接。

### ISSUE THREAD

**Issue by RimacC2-EV** [Hex-Dragon/PCL2#4455]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在前几天（8月头几天）我尝试在缺少Java的情况下启动 Minecraft 1.21，并且让 PCL 自动下载了Java，但是它下载了 JDK 21.0.3，我记得那时候 JDK 21.0.4 都出了啊（）
![屏幕截图 2024-08-09 214923](https://github.com/user-attachments/assets/8d7d8eef-33e5-42b6-91dc-aa0fb7a356ef)
![屏幕截图 2024-08-09 215848](https://github.com/user-attachments/assets/e8195635-d077-4786-9022-143695820624)

或者多增加几个 JDK 的下载选项呗（
.zip：https://download.oracle.com/java/21/latest/jdk-21_windows-x64_bin.zip；
.exe：https://download.oracle.com/java/21/latest/jdk-21_windows-x64_bin.exe；
.msi：https://download.oracle.com/java/21/latest/jdk-21_windows-x64_bin.msi；
）

### 原因

这项优化让我们可以更方便地自定义下载 JDK 的类型。
如果没有这项优化，我每次都必须重新更新 JDK，让操作变得很麻烦。<del>但似乎这不是必须的操作</del>

**Comment by allMagicNB** [comment]
PCL 的 Java 补全依赖的是官启的补全方式。

**Comment by Dainsleif233** [comment]
> ~为什么一定要追求最新版本呢~ .exe 和 .msi 文件无法做到自动安装，需要用户手动点击下一步（也许是 目前 PCL 采用的是官启的补全方式 ![image](https://private-user-images.githubusercontent.com/122529705/356653652-1b39a4a9-6c31-49b8-9d2f-dabf234eebfb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMjAzMjEsIm5iZiI6MTcyMzIyMDAyMSwicGF0aCI6Ii8xMjI1Mjk3MDUvMzU2NjUzNjUyLTFiMzlhNGE5LTZjMzEtNDliOC05ZDJmLWRhYmYyMzRlZWJmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQxNjEzNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNjExYzkyZThmNGQ0YWYxN2E0MzM4MmQxMDM4ZGYyNzQ4M2Q3Mjg5YWU3MDZhODEzNjVmMTE2MzllMjJiNDg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Vrrh99UN2-WdLMuj6_f5Q2t2Zy8BRVyCsEFcSUZu-fk)

msi安装包可以用/quite参数静默安装，新版有新的优化，修了Bug，默认为用户提供最新版肯定是不会错的

**Comment by Dainsleif233** [comment]
> ### 检查项
> * [x]  我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
> * [x]  我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。
> 
> ### 描述
> 在前几天（8月头几天）我尝试在缺少Java的情况下启动 Minecraft 1.21，并且让 PCL 自动下载了Java，但是它下载了 JDK 21.0.3，我记得那时候 JDK 21.0.4 都出了啊（） ![屏幕截图 2024-08-09 214923](https://private-user-images.githubusercontent.com/125170682/356620938-8d7d8eef-33e5-42b6-91dc-aa0fb7a356ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMjA4MjYsIm5iZiI6MTcyMzIyMDUyNiwicGF0aCI6Ii8xMjUxNzA2ODIvMzU2NjIwOTM4LThkN2Q4ZWVmLTMzZTUtNDJiNi05MWRjLWFhMGZiN2EzNTZlZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQxNjIyMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMDY4MjM4YTYyZjA0MjMzZDI2NDBlOWI2Nzg1ODczMWI4NGU3YmQyNDU2ZmYzZDUwMjQ3ZjViYWZjNmFmOTJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ToRORU1loK83kbfapxbVRo6KvwjuIQde5tL8OdDqKLU) ![屏幕截图 2024-08-09 215848](https://private-user-images.githubusercontent.com/125170682/356620967-e8195635-d077-4786-9022-143695820624.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMjA4MjYsIm5iZiI6MTcyMzIyMDUyNiwicGF0aCI6Ii8xMjUxNzA2ODIvMzU2NjIwOTY3LWU4MTk1NjM1LWQwNzctNDc4Ni05MDIyLTE0MzY5NTgyMDYyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQxNjIyMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNDAzY2Q3NzIxOGQxOWViNzY0ZTI5NzcwODYwMjdmNGNjOTc5ODhkNzI0ZWI2MDlhNzA3MTljMTQ1ZDc3NGIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uZ28O2v5UPt4JjlkkfBLVXRuYbvddTu7VKSCyjXxp4E)
> 
> 或者多增加几个 JDK 的下载选项呗（ .zip：[https://download.oracle.com/java/21/latest/jdk-21_windows-x64_bin.zip；](https://download.oracle.com/java/21/latest/jdk-21_windows-x64_bin.zip%EF%BC%9B) .exe：[https://download.oracle.com/java/21/latest/jdk-21_windows-x64_bin.exe；](https://download.oracle.com/java/21/latest/jdk-21_windows-x64_bin.exe%EF%BC%9B) .msi：[https://download.oracle.com/java/21/latest/jdk-21_windows-x64_bin.msi；](https://download.oracle.com/java/21/latest/jdk-21_windows-x64_bin.msi%EF%BC%9B) ）
> 
> ### 原因
> 这项优化让我们可以更方便地自定义下载 JDK 的类型。 如果没有这项优化，我每次都必须重新更新 JDK，让操作变得很麻烦。~但似乎这不是必须的操作~

确实可以换成直链，不过这里提醒一点，OracleJDK 是闭源软件，建议启动器默认提供其他开源的JDK。

**Comment by JingHai-Lingyun** [comment]
给龙猫看看.png

**Comment by Pigeon0v0** [comment]
我记得是有相关 Issue 说使用来自 Mojang 的 Java 的，因为可以最大限度排除 Java 对游戏的影响

Java 新版本对游戏的优化是微乎其微的，更别说 Bug 修复了

**Comment by wuyuncheng-26** [comment]
> 确实可以换成直链，不过这里提醒一点，OracleJDK 是闭源软件，建议启动器默认提供其他开源的JDK。

你的意思是？OpenJDK？

**Comment by Dainsleif233** [comment]
> > 确实可以换成直链，不过这里提醒一点，OracleJDK 是闭源软件，建议启动器默认提供其他开源的JDK。
> 
> 你的意思是？OpenJDK？

是的，例如ZuluJDK、Microsoft Build of OpenJDK等

**Comment by RimacC2-EV** [comment]
> ~为什么一定要追求最新版本呢~ .exe 文件无法做到自动安装，需要用户手动点击下一步（也许是 目前 PCL 采用的是官启的补全方式 ![image](https://private-user-images.githubusercontent.com/122529705/356653652-1b39a4a9-6c31-49b8-9d2f-dabf234eebfb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyNTUxMzIsIm5iZiI6MTcyMzI1NDgzMiwicGF0aCI6Ii8xMjI1Mjk3MDUvMzU2NjUzNjUyLTFiMzlhNGE5LTZjMzEtNDliOC05ZDJmLWRhYmYyMzRlZWJmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMFQwMTUzNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ODM2MzA4YTI4ODE0NTU1NWRhNjcyODQwMjg5NDQ3YWUxN2M4ZWFhY2MzZGRmNzA4ZTA3OTA3ZGYwZWYzMDMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-hOTOdM_PhD-xn7HJCZHmWyGVk_bBhLMwm1IHrF4y6Q)

原来是这样吗？
我看自动补全的 Java 的签名是 Oracle Corporation，然而官启下载的 Java 是 Microsoft Corporation 的签名······

**Comment by LTCatt** [comment]
自动下载的是 Mojang 官方启动器使用的 Java，这样能最大程度的降低 Java 版本可能带来的不兼容问题，暂时不会修改，抱歉
