### ISSUE TITLE
更新 mod 并切换应用后，mod管理 界面总会重新加载

### ISSUE THREAD

**Issue by sinterde** [Hex-Dragon/PCL2#4457]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

希望在打开其他应用窗口和右键进入mod详情后，再返回mod列表的情景下减少重新加载mod列表的情况

### 原因

在mod管理界面，打开其他应用后返回pcl，大概率会让mod列表重新刷新。这在类似查看mod更新内容的情景下显得非常恼人（尤其是mod多的情况下会延长加载时间）

**Comment by LTCatt** [comment]
具体要怎么复现？

**Comment by wuyuncheng-26** [comment]
这算是 Bug 么……
这个操作是为了防止玩家切后台加 Mod 后不显示在 PCL 里吧

**Comment by sinterde** [comment]
研究了一下：
1. 使用更新按钮更新mod并等待页面刷新完成后，再切换到别的页面——如**查看更新内容**，**打开其他应用**，**右键mod进入下载界面**。再切换回pcl或mod管理界面，就能稳定触发刷新，刷新过一次后会恢复正常（之前更新已经刷新了一次，mod也显示是新版本了）

2. 上述的操作只会有一次异常刷新，而在之前的使用过程中我有过持续性异常刷新，既每查看一次更新内容跳转网页再返回pcl都会导致异常刷新（很频繁），不过暂时还没有复现

**Comment by SALTWOOD** [comment]
感觉是为了保证外部更改mods之后模组列表仍然同步？

**Comment by sinterde** [comment]
应该不是，因为在更新完后，已经刷新完成一次了，且只有更新完成后会触发这个bug，其他时候都是正常的

**Comment by sinterde** [comment]
> 感觉是为了保证外部更改mods之后模组列表仍然同步？

应该不是，因为在更新完后，已经刷新完成一次了，且只有更新完成后会触发这个bug，其他时候都是正常的
