### ISSUE TITLE
PCL2在登录正版账号时出错:Could not establish trust relationship for the SSL/TLS secure channel 

### ISSUE THREAD

**Issue by et0616** [Hex-Dragon/PCL2#4458]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在登录正版账号时显示Could not establish trust relationship for the SSL/TLS secure channel 查了一下好像是使用了无效或过期的SSL证书（https://cloud.tencent.cn/developer/ask/sof/104350028）
 

### 重现步骤

1、点击登录
2、按照正常流程输入微软账号密码后复制网址到PCL2，点击确定后弹出窗口:
![Capture](https://github.com/user-attachments/assets/6a0affc1-2ee9-4807-b2a8-cf184b8ce5f4)

### 日志与附件

[Log3.txt](https://github.com/user-attachments/files/16568255/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16568256/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16568257/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/16568258/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16568259/Log2.txt)

**Comment by wuyuncheng-26** [comment]
应该是你的网络问题，和 PCL 无关

**Comment by allMagicNB** [comment]
把 `设置->启动器->下载->验证 SSL 证书` 取消勾选。

**Comment by et0616** [comment]
> 应该是你的网络问题，和 PCL 无关

但是在同一局域网下的另一台电脑可以登录

**Comment by et0616** [comment]
> 把 `设置->启动器->下载->验证 SSL 证书` 取消勾选。

可以了,谢谢

**Comment by LTCatt** [comment]
考虑到进行证书校验确实在相当一部分网络环境下导致了登录失败，现在进行校验的设置会默认关闭。
如果你想要更高的安全性，可以手动开启。
