### ISSUE TITLE
启动失败（打开 Natives 文件失败：找不到中央目录结尾记录）

### ISSUE THREAD

**Issue by HL-hollow** [Hex-Dragon/PCL2#446]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我个人用pcl开1.8.9经常出现问题，同时部分群友也出现过这样的情况。
同样的游戏版本文件，我用pcl显示有进程被占用，用hmcl可以正常打开。
![{A 3_LZ{DE68OD}V3O_YGZD](https://user-images.githubusercontent.com/106107869/203883904-75671733-0d2c-4fdc-9a48-c85b9ef6eefa.png)
已经尝试过重启电脑，重装游戏，甚至换过一次系统，这个问题依然存在（悲。

### 重现步骤

1.点击“版本选择”
2.点击1.8.9（原版，无OptiFine，forge，farbic）
3.点击开始游戏（我是微软正版登录）
4.出现弹窗

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10088040/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10088041/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10088042/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10088043/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10088044/Log5.txt)

**Comment by LTCatt** [comment]
[09:56:28.380] [Launch] 无需解压：F:\MC\PCL2\.minecraft\versions\1.8.9\1.8.9-natives\twitchsdk.dll
[09:56:31.615] 打开 Natives 文件失败（F:\MC\PCL2\.minecraft\libraries\tv\twitch\twitch-external-platform\4.5\twitch-external-platform-4.5-natives-windows-64.jar）：找不到中央目录结尾记录。
   在 System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   在 System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
   在 PCL.ModLaunch.McLaunchNatives(LoaderTask`2 Loader)
错误类型：System.IO.InvalidDataException
[09:56:31.618] 加载线程 解压文件 (41) 发生运行时错误：文件“F:\MC\PCL2\.minecraft\libraries\tv\twitch\twitch-external-platform\4.5\twitch-external-platform-4.5-natives-windows-64.jar”正由另一进程使用，因此该进程无法访问此文件。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.File.InternalDelete(String path, Boolean checkHost)
   在 PCL.ModLaunch.McLaunchNatives(LoaderTask`2 Loader)
   在 PCL.ModLoader.LoaderTask`2._Closure$__12-0._Lambda$__0()
错误类型：System.IO.IOException
[09:56:31.619] [Loader] 加载器 解压文件 状态改变：Failed
[09:56:31.619] [Loader] 加载器 Minecraft 启动 状态改变：Failed

**Comment by LTCatt** [comment]
F:\MC\PCL2\.minecraft\libraries\tv\twitch\twitch-external-platform\4.5\twitch-external-platform-4.5-natives-windows-64.jar
上传一下这个文件？

**Comment by HL-hollow** [comment]
github不支持jar文件上传
我把后辍名改为zip
[twitch-external-platform-4.5-natives-windows-64.zip](https://github.com/Hex-Dragon/PCL2/files/10093712/twitch-external-platform-4.5-natives-windows-64.zip)

**Comment by LTCatt** [comment]
umm 试试删掉这个文件然后再启动？

**Comment by HL-hollow** [comment]
额，确实好了qwq

**Comment by HL-hollow** [comment]
额，确实好了（这么晚，为龙猫的头发担忧

**Comment by HL-hollow** [comment]
这大概是一年前左右的源文件，估计是那时的下载源有问题。
