### ISSUE TITLE
关于Windows Dev不久前遇到的问题

### ISSUE THREAD

**Issue by wudiwudidream** [Hex-Dragon/PCL2#4461]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

打开启动器会明显出现卡了一下出现两个的问题（通常是双击打开文件会这样），运行游戏之后会出现计算内存暴涨（跟Windows计算的不符），随后是游戏崩溃，有个日志文件在桌面，不过删除了，处理器：AMD Ryzen 5 4600U with Radeon Graphics 2.10 GHz，操作系统版本26120.1340，Windows 11 专业工作站版，版本号：24H2

### 重现步骤

1、点击pcl
2、双击（会有明显卡顿，导致会直接多开，所以可以用VB或其他使启动器仅启动一个）
3、启动游戏（在这个版本的Windows内会导致PCL计算内存暴涨，忽高忽低，并且与Windows显示的内存相差很大）
4、报错（有时候会在桌面生成日志，但也有可能是AMD）+黑屏（暂时不知道怎么回事）

### 日志与附件

[Log4.txt](https://github.com/user-attachments/files/16568709/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16568710/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/16568706/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16568707/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16568708/Log3.txt)

**Comment by wudiwudidream** [comment]
对了，还有一个黑屏日志文件，那个是没办法，但是可能是这个电脑的显示驱动问题（因为Windows也会黑屏）

**Comment by wudiwudidream** [comment]
黑屏时文件资源管理器没停，也没办法操作，但是，可能也有一些驱动间接影响PCL计算内存的算法

**Comment by wudiwudidream** [comment]
黑屏时文件资源管理器没停，也没办法操作，但是，可能也有一些驱动间接影响PCL计算内存的算法

**Comment by wudiwudidream** [comment]
Cumulative Update for Windows 11 Insider Preview (10.0.26120.1350) (KB5041871)更新之后会查看是否还有该问题

**Comment by Pigeon0v0** [comment]
用 Dev 你就得做好这样的准备...

至少等同步到 Beta / RP 再打开（？

**Comment by wudiwudidream** [comment]
***@***.***的自动回复邮件。

**Comment by wudiwudidream** [comment]
DEV反正没啥关系就是，这个不是Windows系统本来的问题
                       
原始邮件
                       
                     

发件人："Pigeon0v0"< ***@***.*** &gt;;

发件时间：2024/8/10 15:26

收件人："Hex-Dragon/PCL2"< ***@***.*** &gt;;

抄送人："wudiwudidream"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [Hex-Dragon/PCL2] 关于Windows Dev不久前遇到的问题 (Issue #4461)




 
用 Dev 你就得做好这样的准备...
 
至少等同步到 Beta / RP 再打开（？

**Comment by wudiwudidream** [comment]
跟Windows没有关系的，此日志文件没有任何有直接或间接关系于Windows的日志

**Comment by Pigeon0v0** [comment]
你觉得不是就不是吧...

**Comment by wudiwudidream** [comment]
确实没有






                       
原始邮件
                       
                     

发件人："Pigeon0v0"< ***@***.*** &gt;;

发件时间：2024/8/10 15:40

收件人："Hex-Dragon/PCL2"< ***@***.*** &gt;;

抄送人："wudiwudidream"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [Hex-Dragon/PCL2] 关于Windows Dev不久前遇到的问题 (Issue #4461)




 
你觉得不是就不是吧...

**Comment by hejiehao** [comment]
> 运行游戏之后会出现计算内存暴涨（跟Windows计算的不符）

截个图看看？

> 游戏崩溃

若你使用PCL2启动器，在游戏崩溃后在崩溃界面点左下角`导出错误报告`，然后把导出的压缩包整个发上来![image]https://img.kookapp.cn/assets/2023-03/CqLof1HzCe0g405l.png

**Comment by wudiwudidream** [comment]
对了，补充一个东西，AMD驱动程序和软件版本23.19.14.04（这个不是你们处理的，这个是AMD那边处理的），因为黑屏是因为这个，因为这个是有关驱动程序的，所以也可以怀疑是Windows的问题

                       
原始邮件
                       
                     

发件人："何杰豪"< ***@***.*** &gt;;

发件时间：2024/8/10 16:22

收件人："Hex-Dragon/PCL2"< ***@***.*** &gt;;

抄送人："wudiwudidream"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [Hex-Dragon/PCL2] 关于Windows Dev不久前遇到的问题 (Issue #4461)




  
运行游戏之后会出现计算内存暴涨（跟Windows计算的不符）
  
截个图看看？
  
游戏崩溃
  
若你使用PCL2启动器，在游戏崩溃后在崩溃界面点左下角导出错误报告，然后把导出的压缩包整个发上来

**Comment by wudiwudidream** [comment]
在重新复现


                       
原始邮件
                       
                     

发件人："何杰豪"< ***@***.*** &gt;;

发件时间：2024/8/10 16:22

收件人："Hex-Dragon/PCL2"< ***@***.*** &gt;;

抄送人："wudiwudidream"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [Hex-Dragon/PCL2] 关于Windows Dev不久前遇到的问题 (Issue #4461)




  
运行游戏之后会出现计算内存暴涨（跟Windows计算的不符）
  
截个图看看？
  
游戏崩溃
  
若你使用PCL2启动器，在游戏崩溃后在崩溃界面点左下角导出错误报告，然后把导出的压缩包整个发上来

**Comment by wudiwudidream** [comment]
这个情况是好了一点，因为当时是差到离谱
                       
原始邮件
                       
                     

发件人："何杰豪"< ***@***.*** &gt;;

发件时间：2024/8/10 16:22

收件人："Hex-Dragon/PCL2"< ***@***.*** &gt;;

抄送人："wudiwudidream"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [Hex-Dragon/PCL2] 关于Windows Dev不久前遇到的问题 (Issue #4461)




  
运行游戏之后会出现计算内存暴涨（跟Windows计算的不符）
  
截个图看看？
  
游戏崩溃
  
若你使用PCL2启动器，在游戏崩溃后在崩溃界面点左下角导出错误报告，然后把导出的压缩包整个发上来

**Comment by Pigeon0v0** [comment]
请前往 GitHub 回复，抑或是在回复邮件时删除引用内容...

**Comment by wudiwudidream** [comment]
[错误报告-2024-8-10_16.56.11.zip](https://github.com/user-attachments/files/16569030/-2024-8-10_16.56.11.zip)

**Comment by wudiwudidream** [comment]
没办法，github没法访问，对了，再补充一下，这个文件包括更换资源包错误，五边形材质包







                       
原始邮件
                       
                     

发件人："Pigeon0v0"< ***@***.*** &gt;;

发件时间：2024/8/10 16:40

收件人："Hex-Dragon/PCL2"< ***@***.*** &gt;;

抄送人："wudiwudidream"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [Hex-Dragon/PCL2] 关于Windows Dev不久前遇到的问题 (Issue #4461)




 
请前往 GitHub 回复，抑或是在回复邮件时删除引用内容...

**Comment by wudiwudidream** [comment]
发过去了，错误报告

**Comment by hejiehao** [comment]
> [错误报告-2024-8-10_16.56.11.zip](https://github.com/user-attachments/files/16569030/-2024-8-10_16.56.11.zip)

游戏崩溃的问题不是由 PCL 导致的，请尝试升级你的显卡驱动

**Comment by wudiwudidream** [comment]
这个显卡驱动是最新的，这个是肯定的






                       
原始邮件
                       
                     

发件人："何杰豪"< ***@***.*** &gt;;

发件时间：2024/8/10 17:15

收件人："Hex-Dragon/PCL2"< ***@***.*** &gt;;

抄送人："wudiwudidream"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [Hex-Dragon/PCL2] 关于Windows Dev不久前遇到的问题 (Issue #4461)




  
错误报告-2024-8-10_16.56.11.zip
  
游戏崩溃的问题不是由 PCL 导致的，请尝试升级你的显卡驱动

**Comment by sulingjiang** [comment]
>双击（会有明显卡顿，导致会直接多开，所以可以用VB或其他使启动器仅启动一个）

#1372

> 3、启动游戏（在这个版本的Windows内会导致PCL计算内存暴涨，忽高忽低，并且与Windows显示的内存相差很大）

依据我的理解，在创建窗口进程前 java 是 pcl 的子进程，所以总览会显示 pcl 和 java 的总使用内存

>4、报错（有时候会在桌面生成日志，但也有可能是AMD）+黑屏（暂时不知道怎么回事）

黑屏只能是显卡驱动或者系统问题，pcl 没有权限也不可能干涉硬件图形渲染，有权限干涉硬件图形渲染的只有在 cpu 持有内核态最高管理权限的应用程序，正常使用下的以管理员权限运行最多只能分配到用户态最高管理权限

驱动最新 ≈ 不稳定
windows dev = 随时可能炸
这 buff 直接叠满了

另，不要把 GitHub issues 当 sms 工具，会炸邮箱
以及回答之前没有回答的问题
汇编是单独指代汇编语言，你说的把 c 语言转成机器码是指编译

**Comment by wudiwudidream** [comment]
黑屏只能是显卡驱动或者系统问题，pcl 没有权限也不可能干涉硬件图形渲染，有权限干涉硬件图形渲染的只有在 cpu 持有内核态最高管理权限的应用程序，正常使用下的以管理员权限运行最多只能分配到用户态最高管理权限

驱动最新 ≈ 不稳定
这个看过了，已经不频繁了，我不开pycharm那些（整网站那些的在后台运行）






                       
原始邮件
                       
                     

发件人："苏灵"< ***@***.*** &gt;;

发件时间：2024/8/10 19:06

收件人："Hex-Dragon/PCL2"< ***@***.*** &gt;;

抄送人："wudiwudidream"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [Hex-Dragon/PCL2] 关于Windows Dev不久前遇到的问题 (Issue #4461)




  
双击（会有明显卡顿，导致会直接多开，所以可以用VB或其他使启动器仅启动一个）
  
#1372
  
3、启动游戏（在这个版本的Windows内会导致PCL计算内存暴涨，忽高忽低，并且与Windows显示的内存相差很大）
  
依据我的理解，在创建窗口进程前 java 是 pcl 的子进程，所以总览会显示 pcl 和 java 的总使用内存
  
4、报错（有时候会在桌面生成日志，但也有可能是AMD）+黑屏（暂时不知道怎么回事）
  
黑屏只能是显卡驱动或者系统问题，pcl 没有权限也不可能干涉硬件图形渲染，有权限干涉硬件图形渲染的只有在 cpu 持有内核态最高管理权限的应用程序，正常使用下的以管理员权限运行最多只能分配到用户态最高管理权限
 
驱动最新 ≈ 不稳定
 windows dev = 随时可能炸
 这 buff 直接叠满了
 
另，不要把 GitHub issues 当 sms 工具，会炸邮箱
 以及回答之前没有回答的问题
 汇编是单独指代汇编语言，你说的把 c 语言转成机器码是指编译

**Comment by Pigeon0v0** [comment]
等你啥时候能来 GitHub 回复，重新整理一下你的语言再打开这个 = =

**Comment by wudiwudidream** [comment]
你以为我想啊，一直掉线的，延迟太高了






                       
原始邮件
                       
                     

发件人："Pigeon0v0"< ***@***.*** &gt;;

发件时间：2024/8/10 19:20

收件人："Hex-Dragon/PCL2"< ***@***.*** &gt;;

抄送人："wudiwudidream"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [Hex-Dragon/PCL2] 关于Windows Dev不久前遇到的问题 (Issue #4461)




 
等你啥时候能来 GitHub 回复，重新整理一下你的语言再打开这个 = =

**Comment by wuyuncheng-26** [comment]
遇到这种情况先思考自己系统的问题
万一不是 PCL 的问题呢？
何况你用的还是 Dev 版
我建议还是重装回正常版本看看
PCL 那么多用户不可能都遇到这个问题，先考虑一下你自己系统的缺陷
你也别说日志里的和 Windows 无关了，你整个 PCL 都运行在 Windows 上，系统自身有 Bug 也不是没有可能
附：之前在预览版时已经把我电脑摄像头给噶了
~又附：哟，这不是上次那个把 GitHub 当 SMS 用的人吗~

**Comment by sulingjiang** [comment]
>你以为我想啊，一直掉线的，延迟太高了

猜你需要：steam++

**Comment by wuyuncheng-26** [comment]
> 你以为我想啊，一直掉线的，延迟太高了

请自行搜索相关解决方案
如 Watt Toolkit、steamcommunity302、FastGitHub、改 host 等方法

**Comment by wudiwudidream** [comment]
别，容易被封






                       
原始邮件
                       
                     

发件人："是小胖呀26"< ***@***.*** &gt;;

发件时间：2024/8/10 19:31

收件人："Hex-Dragon/PCL2"< ***@***.*** &gt;;

抄送人："wudiwudidream"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [Hex-Dragon/PCL2] 关于Windows Dev不久前遇到的问题 (Issue #4461)




  
你以为我想啊，一直掉线的，延迟太高了
  
请自行搜索相关解决方案
 如 Watt Toolkit、steamcommunity302、FastGitHub、改 host 等方法

**Comment by JingHai-Lingyun** [comment]
如果您有需要，请[在 Discussion 大区开帖询问](https://github.com/Hex-Dragon/PCL2/discussions/new?category=%E6%8F%90%E9%97%AE)
请勿在该帖内继续回复无关内容，也不要将 GitHub 当作 SMS（即时通讯）工具使用，感谢合作

**Comment by sulingjiang** [comment]
>你以为我想啊，一直掉线的，延迟太高了

实在想用请不要修改邮件原有字段，或者全删了再写

**Comment by wuyuncheng-26** [comment]
> 别，容易被封

？？？？？？？？
不是谁跟你说会被封的
你倒是试一下啊
想想我们这些人都这么干啥时候出过问题了

**Comment by wudiwudidream** [comment]
因为我是用VPN被封的

**Comment by wudiwudidream** [comment]
话说还有个情况类似的“就是说内存优化也太逆天了吧 #4459”

**Comment by sulingjiang** [comment]
> 话说还有个情况类似的“就是说内存优化也太逆天了吧 #4459”

这是允许版聊的讨论分区
如果你继续提交无用信息，我会考虑向龙猫请示再 ban 几个月

**Comment by wudiwudidream** [comment]
没有，因为是有关的，并且，我ban的时间是到8月15日的（这个是屏蔽）

**Comment by wuyuncheng-26** [comment]
> 因为我是用VPN被封的

你 IP 不纯净
再说我给你提供的这些选项和 VPN 无关，没有被封的可能
~你怕不是看了什么营销号的视频说用这些会被封~

> 话说还有个情况类似的“就是说内存优化也太逆天了吧 #4459”

你的这个 issue 和 #4459 毫无联系
#4459 作者的意思大概率是想说 PCL 的内存优化功能非常好用罢了
想要让龙猫做成一个单独的插件供大家使用

**Comment by wudiwudidream** [comment]
好，理解了

**Comment by wudiwudidream** [comment]
@sulingjiang 那个，提醒一下，龙猫使用的是屏蔽功能，不是ban的功能，因为ban不了，我15号才解封，结果现在就可以发消息了，而且ban账户这个功能的是封禁github的功能，除非直接踢出（还可以加回来的）

**Comment by wudiwudidream** [comment]
对了，帮忙将这个关了

**Comment by JingHai-Lingyun** [comment]
该帖已经关闭，请勿继续回复无关内容，感谢合作
