### ISSUE TITLE
MC渲染错误

### ISSUE THREAD

**Issue by XiaoyeTT666** [Hex-Dragon/PCL2#4462]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![minecraftUI渲染错误](https://github.com/user-attachments/assets/2245603f-72a4-4a3f-b3dd-a37075e7a9db)

### 重现步骤

启动

### 日志与附件

[Uploading Log1.txt…]()

**Comment by Deep-Dark-Forest** [comment]
使用 HMCL 启动器启动同一游戏是否会发生这个问题？
另外，您的日志未上传成功。请在 `Upload XXXX` 文字消失以后，再点击绿色按钮。

**Comment by JingHai-Lingyun** [comment]
无法从您的截图中看出任何渲染错误
请**详细描述**您遇到的问题，并按照上方他人提供的提示**重新上传**您的日志

**Comment by hejiehao** [comment]
> 无法从您的截图中看出任何渲染错误 请**详细描述**您遇到的问题，并按照上方他人提供的提示**重新上传**您的日志

应该是字体渲染

**Comment by wuyuncheng-26** [comment]
恐怕不是 PCL 的问题……

**Comment by mcwuguodadi** [comment]
请**详细描述**您的问题
如果您觉得**字体大小看不清**的问题，请在游戏选项-视频设置-调整界面大小点击选择Auto或者数字更大的界面大小
此外，这并非PCL2的问题

**Comment by SALTWOOD** [comment]
判断是因为MC的UI大小过小。与PCL无关。
同时，看图安装了机械动力，PCL不受理因为安装模组导致的问题。
来个 collaborator 关掉罢
