### ISSUE TITLE
特定版本游戏内“打开资源包文件夹”按钮无法指向正确文件，弹出Windows错误提示框

### ISSUE THREAD

**Issue by Water-Yuan** [Hex-Dragon/PCL2#4463]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

当下载版本1.8.9+最新版Forge（11.15.1.2318）时，点击“打开资源包文件夹”会弹出Windows的错误信息，信息中指示的错误表明目录中多了一个\，即“\E:\Minecraft\..."
![PixPin_2024-08-10_19-47-22](https://github.com/user-attachments/assets/de4815ec-6ae0-4ddd-8858-9e086bf60264)

### 重现步骤

1、下载版本1.8.9+最新推荐版Forge（无需下载任何mod），打开版本隔离
2、启动游戏后 选项-资源包-打开资源包文件夹
3、出现Bug

### 日志与附件

[Log5.txt](https://github.com/user-attachments/files/16569425/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/16569426/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16569427/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16569428/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16569429/Log4.txt)

**Comment by wuyuncheng-26** [comment]
Minecraft 的问题，恐怕与 PCL 无关

**Comment by allMagicNB** [comment]
来，你先用 HMCL 启动试试，看看会不会崩。

**Comment by mcwuguodadi** [comment]
这是老版本mc的问题，恐怕和PCL无关
我之前用其他启动器玩老版本也会出现这个问题

**Comment by Water-Yuan** [comment]
> 来，你先用 HMCL 启动试试，看看会不会崩。

![image](https://github.com/user-attachments/assets/0a08979f-9019-480c-b612-558e7f460a9d)

**Comment by JingHai-Lingyun** [comment]
很奇怪的在路径的开头多了一个 `\`，这应当不是 PCL 带来的问题
稍等，我记得有重复反馈，正在查询

**Comment by hejiehao** [comment]
这个我见过，我不太确定这个是不是 Java 导致的问题

**Comment by youzi-2333** [comment]
+1，我也看到过，in PCL2 x9。

![image](https://github.com/user-attachments/assets/9702e0d7-1264-4a44-9f1b-d953325f7a90)

我私了他一下，他说其他版本没问题。

> 反正我只在一个版本里遇见过这种事其他的版本没问题

**Comment by wuyuncheng-26** [comment]
JVM 参数加个-Djdk.lang.Process.allowAmbiguousCommands=true 试试？（#3868 解决方案）

**Comment by JingHai-Lingyun** [comment]
应该是与 #3868 同理的？
