### ISSUE TITLE
1.21等版本无法正常下载并安装neoforge

### ISSUE THREAD

**Issue by Uright-Xuqing233** [Hex-Dragon/PCL2#4464]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

1.21等版本无法正常下载并安装neoforge，隔壁hmcl已经完成修复了

### 重现步骤

1.21下载并安装neoforge

### 日志与附件

[Log2.txt](https://github.com/user-attachments/files/16569446/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16569447/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16569448/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16569449/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/16569450/Log1.txt)

**Comment by JingHai-Lingyun** [comment]
附带一个那边的帖子？

**Comment by wuyuncheng-26** [comment]
发个 HMCL 那边的 issue 看看

**Comment by Uright-Xuqing233** [comment]
HMCL更新日志里面有

**Comment by wuyuncheng-26** [comment]
```
[20:01:38.913] 加载线程 安装 NeoForge (56) 发生运行时错误：安装新 NeoForge 版本失败
→ 运行 NeoForge 安装器失败
→ NeoForge 安装器出错，日志结束部分为：
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.bangbang93.ForgeInstaller.main(ForgeInstaller.java:75)
Failed to run processor: java.nio.file.FileSystemException:C:\ProgramData\Temp\PCL\Install\885190034\versions\1.21\1.21.jar: 函数不正确。
See log for more details.
false
   在 PCL.ModDownloadLib._Closure$__35-0._Lambda$__7(LoaderTask`2 Task)
   在 PCL.ModLoader.LoaderTask`2._Closure$__13-0._Lambda$__0()
   在 PCL.ModDownloadLib._Closure$__35-0._Lambda$__7(LoaderTask`2 Task)
   在 PCL.ModDownloadLib.ForgelikeInjector(String Target, LoaderTask`2 Task, String McFolder, Boolean UseJavaWrapper, Boolean IsNeoForge)
   在 PCL.ModDownloadLib._Closure$__35-0._Lambda$__7(LoaderTask`2 Task)
```

**Comment by wuyuncheng-26** [comment]
https://github.com/HMCL-dev/HMCL/issues/3127

**Comment by hejiehao** [comment]
> [HMCL-dev/HMCL#3127](https://github.com/HMCL-dev/HMCL/issues/3127)

应该不是这个，这个只是无法获取 NeoForge 版本列表

**Comment by Uright-Xuqing233** [comment]
好吧我收回那句话，hmcl也有问题

**Comment by hejiehao** [comment]
这应该是你的系统问题

**Comment by Uright-Xuqing233** [comment]
啊？咋会

**Comment by wuyuncheng-26** [comment]
> ```
> Failed to run processor: java.nio.file.FileSystemException:C:\ProgramData\Temp\PCL\Install\1974939696\versions\1.21.1\1.21.1.jar: 函数不正确。
> ```
> 
> Usually this path should be `%Temp%`, not `%ProgramData%\Temp`. 通常这个路径应该是 `%Temp%`，而不是 `%ProgramData%\Temp`。
> 
> Have you modified your system’s environment variables? 您是否修改过系统的环境变量？

Good point

**Comment by zkitefly** [comment]
> ```
> Failed to run processor: java.nio.file.FileSystemException:C:\ProgramData\Temp\PCL\Install\1974939696\versions\1.21.1\1.21.1.jar: 函数不正确。
> ```
> Usually this path should be `%Temp%`, not `%ProgramData%\Temp`.
> 通常这个路径应该是 `%Temp%`，而不是 `%ProgramData%\Temp`。
> 
> Have you modified your system’s environment variables?
> 您是否修改过系统的环境变量？

https://github.com/Hex-Dragon/PCL2/blob/main/Plain%20Craft%20Launcher%202%2FPages%2FPageDownload%2FModDownloadLib.vb#L1998-L1998

这个不是环境变量的问题，是 pcl 的逻辑

**Comment by zkitefly** [comment]
楼主可以下载这个打开安装吗🤔

https://maven.neoforged.net/releases/net/neoforged/neoforge/21.1.4/neoforge-21.1.4-installer.jar

**Comment by Pigeon0v0** [comment]
@3gf8jv4dv 

When `%temp%` is unavailable due to some reasons like authority, PCL will turn to use `%programdata%\Temp`.

**Comment by Uright-Xuqing233** [comment]
我使用neoforge官方安装器可以正常安装并启动

**Comment by Uright-Xuqing233** [comment]
好吧，经过我的测试，是因为我使用了ImDisk然后更改了Temp环境变量，并将temp重定向到了randisk上，具体报错原因不清，如果有兴趣兼容那更好，不过我会先关闭这个issues

**Comment by Uright-Xuqing233** [comment]
> 好吧，经过我的测试，是因为我使用了ImDisk然后更改了Temp环境变量，并将temp重定向到了randisk上，具体报错原因不清，如果有兴趣兼容那更好，不过我会先关闭这个issues

还原后不会出现报错

**Comment by JingHai-Lingyun** [comment]
呃？
