### ISSUE TITLE
已安装的单个模组副信息过长导致无法点到升级图标

### ISSUE THREAD

**Issue by AlbertInf299** [Hex-Dragon/PCL2#4465]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

如图，示例的“C^2M引擎”模组的升级按钮被挤到最右侧，鼠标悬停在此处被模组管理UI遮挡，无法点击
![QQ图片20240810195333](https://github.com/user-attachments/assets/4f116383-8b8e-41de-9883-6db230a7e309)
![QQ图片20240810195545](https://github.com/user-attachments/assets/2ab8afbf-6fcc-49ea-baa6-7f2d679771d1)
我觉得可单独设置“升级Mod”界面来解决
![QQ图片20240810200553](https://github.com/user-attachments/assets/80f98150-c488-40dc-bb97-bd704fbc88fb)

### 原因

这项优化让我可以更方便地进行模组升级。
如果没有这项优化，我每次都必须重新下载最新版本的模组，让操作变得很麻烦。

**Comment by JingHai-Lingyun** [comment]
英文怎么会那么长……
我认为应该限制其 SubTitle 信息的长度

**Comment by AlbertInf299** [comment]
嘶，按道理说确实要限制
（忘了还能单选升级）

**Comment by allMagicNB** [comment]
不能挪个位吗？（

**Comment by wuyuncheng-26** [comment]
也许应该把更新图标移到最前面……

**Comment by Ascnbeta** [comment]
点击了模组后下方的UI也可以点击更新吧
![image](https://github.com/user-attachments/assets/36c80947-1496-4a0e-b401-9a23c519596d)

**Comment by Chiloven945** [comment]
或许可以在mod图标上方放一个更新按钮的叠加层？

**Comment by wuyuncheng-26** [comment]
@AlbertInf299 
![image](https://github.com/user-attachments/assets/3ab6d715-f515-4c76-8b27-eefe01729746)
您看看这样可以吗
把升级图标移到模组名前面

**Comment by zkitefly** [comment]
>  您看看这样可以吗 把升级图标移到模组名前面

我不认为这个可以，这样会有种必须升级的感觉，但升级并不是必须且推荐的

我认为可以将这图标移动到 Subname 和 版本号中间的那个地方

**Comment by AlbertInf299** [comment]
这个方案并不美观，也许要考虑别的位置

**Comment by JingHai-Lingyun** [comment]
看着 UI 很抽象…… 我认为还是应该限制 SubTitle 的英文那一段

**Comment by wuyuncheng-26** [comment]
个人感觉单独添加个 `更新 Mod` 按钮会导致

> > 您看看这样可以吗 把升级图标移到模组名前面
> 
> 我不认为这个可以，这样会有种必须升级的感觉，但升级并不是必须且推荐的，而且看的强迫症很难受
> 
> 我认为可以将这图标移动到 Subname 和 版本号中间的那个地方

好建议

**Comment by wuyuncheng-26** [comment]
可惜这个方案不行，因为 Subname 和 版本号属于一个元素，也不能硬拆开吧

**Comment by wuyuncheng-26** [comment]
![image](https://github.com/user-attachments/assets/771e1ee6-a39e-4390-a25d-50749be5ea4e)
也只能这样了
qwq 更丑了

**Comment by zkitefly** [comment]
![image](https://github.com/user-attachments/assets/065b791f-abb8-4af9-9649-f5c0ce5589c7)

这个地方可以吗 :thinking:

**Comment by wuyuncheng-26** [comment]
> 这个地方可以吗 🤔

Subname 和版本号属于一个元素
你要硬拆开它们也不是不行（
但不仅要改 XAML 还要改 VB 了

**Comment by WangYiBen0** [comment]
改到mod的tag后面行吗（就是那个[性能优化]什么的）

**Comment by LTCatt** [comment]
![image](https://github.com/user-attachments/assets/ee3aae0f-4f14-4a72-9db4-270e577b0a70)
自动适应 √

**Comment by AlbertInf299** [comment]
哇，解决了诶（不过直接省略也挺直接的hh）
我的识别码：55B5-32F5-4455-094B

**Comment by LTCatt** [comment]
你的解锁码：AhZzgn3GQdLdK/LlWBDI81xwPSG1lYyd
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
