### ISSUE TITLE
在下载特定Mod时发现版本错误

### ISSUE THREAD

**Issue by WangEarth** [Hex-Dragon/PCL2#4469]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

声明：未确认其他Mod是否会出现该Bug，已确认正式版与预览版均会出现该Bug
在下载Mod"更高级联机设置"时发现原1.20.4版本Mod被错误移动至1.20.6版本区域，原1.20.6版本Mod被错误移动至1.20.4版本区域，两个Mod版本错误互换

### 重现步骤

1、搜索Mod"更高级联机设置"
2、打开该Mod页面，打开1.20.6版本和1.20.4版本即可复现

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16571955/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16571956/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16571957/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16571959/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16571960/Log5.txt)

**Comment by allMagicNB** [comment]
一眼作者的问题

**Comment by WangEarth** [comment]
我不到啊，换电脑也这样啊

**Comment by WangEarth** [comment]
该不会是网络问题吧

**Comment by hejiehao** [comment]
你是指这两个？

**Comment by WangEarth** [comment]
对

**Comment by allMagicNB** [comment]
作者自己选的支持多个版本，文件名没改而已，用了崩了找作者去。

**Comment by hejiehao** [comment]
1.7.1-1.20.4-fabric 也可以在 1.20.6 上运行
1.7.1-1.20.6-fabric 也可以在 1.20.4 上运行

**Comment by WangEarth** [comment]
哦哦
