### ISSUE TITLE
联机相关选项没有删除干净

### ISSUE THREAD

**Issue by GADDQ** [Hex-Dragon/PCL2#447]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

设置中仍然可以找到联机选项卡，并仍可以设置

### 重现步骤

见描述

### 日志与附件

无

**Comment by LiuBinzhe** [comment]
![image](https://user-images.githubusercontent.com/115980764/203922076-71aed287-a27c-4936-93b7-e544e61f8cdf.png)
龙猫说过了，下个版本删。

**Comment by Louis-ZYH** [comment]
Github上已经有人提出Issues，主题是关闭对Hiper的各项支持
