### ISSUE TITLE
“关于”中提供的赞助链接没换

### ISSUE THREAD

**Issue by kipper3832** [Hex-Dragon/PCL2#4471]

**Comment by wuyuncheng-26** [comment]
#4271 下次更新时就有了

**Comment by Pigeon0v0** [comment]
如果发现重复了直接 Close 即可，不需要删除原有内容，因为你即使删除了也能看见历史修改，反而会造成不必要的困扰 = =

**Comment by Deep-Dark-Forest** [comment]
> 如果发现重复了直接 Close 即可，不需要删除原有内容，因为你即使删除了也能看见历史修改，反而会造成不必要的困扰 = =

如果他把历史记录也删了呢？

**Comment by kipper3832** [comment]
我都close了还来拷打wo...

**Comment by Pearl-Luo** [comment]
bot 诈尸了？
