### ISSUE TITLE
下载一个新版本后，将启动游戏的选中版本自动替换为新下载的版本

### ISSUE THREAD

**Issue by ThendJyc** [Hex-Dragon/PCL2#4475]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

下载一个新版本后，将启动游戏的选中版本自动替换为新下载的版本

### 原因

一般来说，下载一个版本后应该都会第一个启动吧
(还是只有我这样)

**Comment by wuliaodexiaoluo** [comment]
#4112
