### ISSUE TITLE
安装不了forge，什么版本都不行

### ISSUE THREAD

**Issue by ylsq1637** [Hex-Dragon/PCL2#4476]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

下载 Forge 51.0.30失败
→ 安装 Forge（方式 A）失败
→ 安装新 Forge 版本失败
→ 运行 Forge 安装器失败
→ Forge 安装器出错，日志结束部分为：
错误: 找不到或无法加载主类 com.bangbang93.ForgeInstaller
   在 PCL.ModDownloadLib._Closure$__35-0._Lambda$__7(LoaderTask`2 Task)
   在 PCL.ModLoader.LoaderTask`2._Closure$__13-0._Lambda$__0()
   在 PCL.ModDownloadLib._Closure$__35-0._Lambda$__7(LoaderTask`2 Task)
   在 PCL.ModDownloadLib.ForgelikeInjector(String Target, LoaderTask`2 Task, String McFolder, Boolean UseJavaWrapper, Boolean IsNeoForge)
   在 PCL.ModDownloadLib._Closure$__35-0._Lambda$__7(LoaderTask`2 Task)

### 重现步骤

1、点击xxxx
2、往下滚，然后点击xxxx

### 日志与附件

[Uploading Log1.txt…]()

**Comment by hejiehao** [comment]
没有成功上传日志，请在 Uploading Log1.txt 消失后再 Comment

**Comment by allMagicNB** [comment]
#4282

**Comment by JingHai-Lingyun** [comment]
需要日志确认是否是 #4282

**Comment by wuyuncheng-26** [comment]
日志上传失败，请重新上传一下

**Comment by SALTWOOD** [comment]
1. 检查 Java，尝试重新安装或更换 Java 版本
2. 重新上传日志
3. 换台电脑试试
4. 不然请把 issue 关了

**Comment by Deep-Dark-Forest** [comment]
超时关闭。
