### ISSUE TITLE
pcl被windows报告病毒

### ISSUE THREAD

**Issue by wunangege** [Hex-Dragon/PCL2#4477]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

pcl被windows报告病毒，希望解决

### 重现步骤

打开应用

### 日志与附件

没有

**Comment by allMagicNB** [comment]
#666
