### ISSUE TITLE
Mod 管理页更新功能存在问题

### ISSUE THREAD

**Issue by Juncylee** [Hex-Dragon/PCL2#4478]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在 版本设置 > Mod 管理 页面选中旧版本模组进行更新的功能十分便捷。然而，一些问题被注意到： Sodium 是 Indium 的前置模组，（截止报告问题前）适用于游戏版本1.20.2的 Sodium 最新版本为0.5.5、Indium 最新版本为1.0.30。然而0.5.5的 Sodium 最高只支援到1.0.28的 Indium。PCL2的快捷模组更新并未检测到此问题，若更新会导致游戏启动报错，回退旧版 Indium 后游戏可以正常启动。
此功能需要改进。
![tmpFF6E](https://github.com/user-attachments/assets/0c7094fd-aad6-4174-80bf-ff37839db8f7)
![tmp7068](https://github.com/user-attachments/assets/39f5b38b-71f8-43a3-9490-e45e8e368adf)
![屏幕截图 2024-08-12 185628](https://github.com/user-attachments/assets/83629718-fce2-453c-8149-9936bbcdf687)

### 原因

这项优化让用户可以更准确地更新模组，而无需在报错问题中纠结。
如果没有这项优化，用户每次都必须亲自检查存在问题的模组，让操作变得很麻烦。

**Comment by JingHai-Lingyun** [comment]
Mod 更新不会检查依赖项是否可用，这个功能只能做到升级至最新版本
https://github.com/Hex-Dragon/PCL2/blob/a6d6c97fd70df2f2eea53ff11baca4e2cf18b7b4/Plain%20Craft%20Launcher%202/Pages/PageVersion/PageVersionMod.xaml.vb#L405
已经明确给出警告，新 Mod 可能与老版本存档或其他 Mod 发生兼容性问题

**Comment by Deep-Dark-Forest** [comment]
![Screenshot_20240812_192840.jpg](https://github.com/user-attachments/assets/abed0a42-e9be-4bfb-9833-1261ff89c8d3)

modrinth 的 api 可以获取到模组的依赖项版本

**Comment by LTCatt** [comment]
技术上可行性不大，CurseForge 不会返回其他版本的 mod 信息，逐一进行检查需要的 API 请求量太大
