### ISSUE TITLE
关于mod下载项重复

### ISSUE THREAD

**Issue by zjriss** [Hex-Dragon/PCL2#4479]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在搜索一个mod或者直接浏览时，会有多个相同名字内容mod，但是下载东西完全一样，建议做一个去重

### 原因

优化让我可以更方便地下载mod
如果没有这项优化，我每次都必须自动省略那些重复的mod，让操作变得很麻烦，且会出现大量占用的情况。

**Comment by Deep-Dark-Forest** [comment]
这大概率是因为同一模组来自不同的平台

**Comment by hejiehao** [comment]
https://github.com/Hex-Dragon/PCL2/issues/1318

**Comment by Deep-Dark-Forest** [comment]
需要 author 提供截图以确认重复原因

**Comment by SALTWOOD** [comment]
无图无真相。看文字是因为不同的mod平台导致的来源冲突。
已有 issue #1318 ，来个 collaborator 关了罢

**Comment by Deep-Dark-Forest** [comment]
> 无图无真相。看文字是因为不同的mod平台导致的来源冲突。
> 已有 issue #1318 ，来个 collaborator 关了罢

没事，先等等 author 发一下图（

**Comment by SALTWOOD** [comment]
![图片](https://github.com/user-attachments/assets/9e563170-86ef-4975-90c7-d67e80e8505a)
@zjriss shi'zh是这样的吗？是的话可以关了。mod平台导致的来源冲突。

**Comment by Deep-Dark-Forest** [comment]
超时关闭。
