### ISSUE TITLE
just kidding

### ISSUE THREAD

**Issue by 114514kobe** [Hex-Dragon/PCL2#4481]
### 检查项

- [ ] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

kidding

### 重现步骤

1、点击xxxx
2、往下滚，然后点击xxxx

### 日志与附件

wad

**Comment by allMagicNB** [comment]
No kidding.

**Comment by Chiloven945** [comment]
just delete it

**Comment by hejiehao** [comment]
Go to Discussion

**Comment by 114514kobe** [comment]
sorry about that but how can i delete tihis pome thx

**Comment by wuliaodexiaoluo** [comment]
>just kidding

Please do not submit irrelevant content within an issue, as this may result in your GitHub account being temporarily blocked by the developer
If you want to make a joke, you can go to the discussion and create a post there

Have a nice day :)
