### ISSUE TITLE
导出崩溃报告中的 “游戏崩溃前的输出.txt” 可能乱码

### ISSUE THREAD

**Issue by allMagicNB** [Hex-Dragon/PCL2#4482]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如果游戏崩溃后的日志包含非 ASCII 字符，那么截取的 `游戏崩溃前的输出.txt` 可能乱码。

### 重现步骤

装个在崩溃时会输出非 ASCII 字符的模组加载器，然后让它报错。概率触发。

### 日志与附件

由 @ZekerZhayard 提供的崩溃报告样本：
[错误报告-2024-8-12_22.19.30.zip](https://github.com/user-attachments/files/16588409/-2024-8-12_22.19.30.zip)

**Comment by LTCatt** [comment]
![image](https://github.com/user-attachments/assets/3ffa8daa-19ca-43a9-804d-94039c92aae7)
PCL 获取到的日志已经是一个被错误解码的字符串了，这应该让 mod 加载器以正确的编码输出 log

**Comment by allMagicNB** [comment]
@LTCatt 有解决方式，在启动命令前加个 `chcp 65001>nul`，导出的启动脚本前也加一句这个，这个命令的作用是改变控制台的活动代码页至 65001（Unicode）。

**Comment by JingHai-Lingyun** [comment]
说不好改了活动代码页别的炸了……

**Comment by allMagicNB** [comment]
> 说不好改了活动代码页别的炸了……

你来测试，能炸算你牛逼，行不行？

**Comment by allMagicNB** [comment]
chcp 只是个命令，先开起来这个 Issue，我等会交 PR。
