### ISSUE TITLE
下载优化

### ISSUE THREAD

**Issue by KamisatoAyaka7** [Hex-Dragon/PCL2#4486]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

百宝箱的下载应该添加一个暂停功能

### 原因

这项优化可以让我更方便地下载；
如果没有{
    我这种先天网卡圣体下东西很恼火；
    windows后台总会有奇妙的程序使用资源，导致下载出问题；
}

**Comment by allMagicNB** [comment]
#3069
