### ISSUE TITLE
[Bug] 错误报告导出的启动脚本是 UTF-8 编码

### ISSUE THREAD

**Issue by wuliaodexiaoluo** [Hex-Dragon/PCL2#4488]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

错误报告内导出的脚本是 UTF-8 编码
~虽然好像也没啥人会用这个，jlw 好像也能理顺这些东西~
不知道为什么 PCL 导出启动脚本选项是 ANSI 编码，导出错误报告的启动脚本却是 UTF-8 编码

### 重现步骤

1、启动一次游戏并想办法让游戏 Crash (F3+C)
2、点击导出启动脚本
3、运行启动脚本，可以发现此时窗口内会出现乱码

### 日志与附件

声明:日志可能无法体现问题，因此不要只局限于日志
![image](https://github.com/user-attachments/assets/2b804042-1a3f-49dc-8f43-ec808a3d4c6d)
[Log1.txt](https://github.com/user-attachments/files/16598989/Log1.txt)

**Comment by wuliaodexiaoluo** [comment]
>ASCII 编码？

手快了，是 ASNI

**Comment by allMagicNB** [comment]
> >ASCII 编码？
> 
> 手快了，是 ASNI

你好像又手快了。

**Comment by hejiehao** [comment]
或许这是为了让其他语言的 Windows 都可以正确读取？

**Comment by allMagicNB** [comment]
这里的启动脚本是给人看的谢谢，不是给你启动用的。
