### ISSUE TITLE
无法更新PCL2

### ISSUE THREAD

**Issue by baoyangawa** [Hex-Dragon/PCL2#449]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

设置 → 启动器 → 检查更新，然后开始下载，下载一半了提示了一段更新错误
具体长这个样子：
![PC](https://user-images.githubusercontent.com/119054339/203989537-27a9fdad-7fba-4829-89e5-ba9f3dcf8453.jpg)

### 重现步骤

1、设置 → 启动器 → 检查更新，然后开始下载
2、下载一半了提示了一段更新错误
3、这是在很久没有打开PCL2更新，突然开启后出现的问题

### 日志与附件

[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10092889/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10092890/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10092891/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10092892/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10092893/Log3.txt)

**Comment by LTCatt** [comment]
字面意思，用管理员权限运行。

**Comment by baoyangawa** [comment]
> 字面意思，用管理员权限运行。

但是这是用管理员权限运行的样子欸，
不过刚刚从群（六群）里把快照版重新下了一次，用更新密钥之后是这个结果，进到存有五个log文件的那个文件夹里发现有一个最新版本的PCL2.exe，我把它剪切到外边并替换之后就好了
也不知道是什么原因导致的
![07ca43c5b1ed43cf9737addcf7b32d3](https://user-images.githubusercontent.com/119054339/204010778-f479df0e-adee-487b-bf8e-880af1084a0a.png)
![744a87fd072f669cbe4b47f92e95614](https://user-images.githubusercontent.com/119054339/204010787-2844cfeb-9b95-4ecb-8340-6492e2a85127.png)
（就是把图二中的PCL2.exe粘贴到图一里的位置，就显示更新完了）

**Comment by LTCatt** [comment]
这是因为 PCL 没有权限复制文件导致的……我没办法啊（

**Comment by baoyangawa** [comment]
> 这是因为 PCL 没有权限复制文件导致的……我没办法啊（

明白了，谢谢龙猫，现在已经正常玩上了（喜
