### ISSUE TITLE
可以把最新版本放在主页右边

### ISSUE THREAD

**Issue by 114514kobe** [Hex-Dragon/PCL2#4490]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

把最新版本的下载哦放在主页右边

### 原因

（示例）
这项优化让我可以更方便地查看最新版本。
如果没有这项优化，我每次都必须点进下载，让操作变得很麻烦。

**Comment by 114514kobe** [comment]
虽然有点多余.但对于那些萌新还是比较好

**Comment by hejiehao** [comment]
> 更方便地查看最新版本

你可能需要：https://github.com/Light-Beacon/PCL2-NewsHomepage

**Comment by wuyuncheng-26** [comment]
~？你不会修改主页吗~
主页预设里面有信标写的新闻主页
设置 -> 个性化 -> 自定义主页 -> 预设 -> Minecraft 新闻

**Comment by LTCatt** [comment]
暂时不作考虑，抱歉……
