### ISSUE TITLE
建议把这里的字体和这个箭头改一下，不然跟旁边比太突兀了

### ISSUE THREAD

**Issue by blqdswkl** [Hex-Dragon/PCL2#4493]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

这个小箭头与旁边的图标很不一样，“手动安装包”这几个字体也是，旁边的图标都是看起来比较圆润的，就这个尖尖的在这，感觉很割裂
![image](https://github.com/user-attachments/assets/5fcb6c6d-9fd2-4265-a9dd-fabcd9204c2c)

### 原因

这项优化可以让PCL的界面更加完美，美观
而且，改进这个应该不难...吧？

**Comment by allMagicNB** [comment]
没法，这是微软雅黑特色，改的话可能要换个 FontFamily，但是好像也没别的能用了……

**Comment by allMagicNB** [comment]
或者说直接把圆润的字体给删了（

**Comment by wuyuncheng-26** [comment]
![image](https://github.com/user-attachments/assets/334b93e9-c48c-4e43-bb45-7a6549d43a66)
？这不是很圆润吗
是你显卡驱动的问题吧

**Comment by ThendJyc** [comment]
而且打开手动安装包选项栏还没有动画过渡

**Comment by wuyuncheng-26** [comment]
那就是你的问题了
显卡驱动没打好的确会有这种情况



发自我的iPad


------------------ 原始邮件 ------------------
发件人: ThendJyc ***@***.***&gt;
发送时间: 2024年8月14日 12:56
收件人: Hex-Dragon/PCL2 ***@***.***&gt;
抄送: 是小胖呀26 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Hex-Dragon/PCL2] 建议把这里的字体和这个箭头改一下，不然跟旁边比太突兀了 (Issue #4493)





 
而且打开手动安装包选项栏还没有动画过渡

**Comment by wuliaodexiaoluo** [comment]
>这个小箭头与旁边的图标很不一样，“手动安装包”这几个字体也是，旁边的图标都是看起来比较圆润的，就这个尖尖的在这，感觉很割裂

![image](https://github.com/user-attachments/assets/faf5a247-2212-4272-85c9-407e8db4717b)

看不出来哪里不圆润了，硬要说的话，这个字太小了放在这有那么一点违和感

>而且打开手动安装包选项栏还没有动画过渡

猫曰：加入过多的动画效果可能会导致在低配电脑上严重卡顿

**Comment by Pigeon0v0** [comment]
你是 Win7 吧

**Comment by blqdswkl** [comment]
我win11
