### ISSUE TITLE
用pcl2下载文件，结果pcl2默认把后缀删除（这应该算bug）

### ISSUE THREAD

**Issue by maquedong123** [Hex-Dragon/PCL2#4494]
### 检查项

- [ ] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

用pcl2下载文件，结果pcl2默认把文件的后缀删除
例如：我下载一个pvz的解压包，pcl2默认把后面的zip删除了

### 重现步骤

1.找到下载链接
2.点击pcl2的更多-百宝箱-下载自定义文件
3.把链接填进去
4.开始下载
5.下载完发现后缀无了

### 日志与附件

无

**Comment by Ad-closeNN** [comment]
发发下载链接？

**Comment by maquedong123** [comment]
https://www.pvz.moe/resources/537/download @Ad-closeNN

**Comment by allMagicNB** [comment]
#84

**Comment by maquedong123** [comment]
草，有人投过了
