### ISSUE TITLE
选择具体版本和模组加载器后选择mod不会将符合的版本放在最上方

### ISSUE THREAD

**Issue by zhiqin14** [Hex-Dragon/PCL2#4497]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在选了版本和加载器后搜索mod不会将符合版本的mod放到最上方
可能只是个别（如等价交换），暮色森林就可以

### 重现步骤

在mod搜索中选好版本和加载器再搜索mod

![QQ截图20240814211045](https://github.com/user-attachments/assets/53548561-16ec-4698-ad15-c1dcd0b42469)
![QQ截图20240814211118](https://github.com/user-attachments/assets/40cfeb8f-0805-49bc-8000-ea48e576d86d)
![QQ截图20240814211056](https://github.com/user-attachments/assets/8361dad6-aa37-40d5-877e-0b288b84a263)

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16613541/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16613544/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16613545/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16613546/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16613547/Log5.txt)

**Comment by allMagicNB** [comment]
#4077

**Comment by zhiqin14** [comment]
> #4077

似乎不太一样呢w，我这个是已经选好版本的

**Comment by wuliaodexiaoluo** [comment]
#2190 
![image](https://github.com/user-attachments/assets/78f4a844-c968-41e8-a830-36ab59583a82)
![image](https://github.com/user-attachments/assets/fe6c0429-d9dc-451e-a132-99147e8045c3)

**Comment by SALTWOOD** [comment]
复现。算是新功能？

**Comment by wuliaodexiaoluo** [comment]
>复现。算是新功能？

这个是没有加载器信息导致的
