### ISSUE TITLE
自动更新mod旧版本没有删掉

### ISSUE THREAD

**Issue by Strange-cmd** [Hex-Dragon/PCL2#4499]
### 检查项

- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我在8月5日的时候遇到PCL2mod管理里面自动更新mod后旧版本没有删掉

### 重现步骤

1、点击版本设置
2、Mod管理
3、需要更新的Mod
4、更新

### 日志与附件

Log已被覆盖

**Comment by allMagicNB** [comment]
那你就复现之后再上传日志

**Comment by Deep-Dark-Forest** [comment]
超时关闭。
