### ISSUE TITLE
为“离线皮肤”功能增加实验性功能（或弃用功能）提示

### ISSUE THREAD

**Issue by Silverteal** [Hex-Dragon/PCL2#4500]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

当离线皮肤选项 **不为“随机”** 时，展示实验性功能/弃用功能提示

参考：

弃用功能：
```
离线皮肤设置功能已弃用，因为它在高版本使用效果不佳，并可能造成更换启动器时存档丢失等问题。
不建议您为新的存档继续使用该功能。您可以通过模组 Custom Skin Loader 或者皮肤站来获得更稳定的离线皮肤体验。
对于已经使用过离线皮肤功能的存档，请继续使用离线皮肤功能以避免存档丢失。
```

实验性功能：
```
离线皮肤设置是一项实验性功能，在高版本使用效果不佳，并可能造成更换启动器时存档丢失等问题。
您可以通过模组 Custom Skin Loader 或者皮肤站来获得更稳定的离线皮肤体验。
对于已经使用过离线皮肤功能的存档，请继续使用离线皮肤功能以避免存档丢失。
```

### 原因

离线皮肤功能历史上是一项方便的功能。但随着版本的更替，它简单粗暴地替换 UUID 的方式已经引发了一系列兼容性问题（有些是不当操作产生的——也可以认为是副作用提示不足），也没能继续跟进支持高版本和新的默认皮肤（#232/#297 和 #1288/#1596 ，接近两年的时间内一直处于投票状态）。我认为有必要向玩家展示使用该功能的风险，或者干脆放弃此功能。

附小部分使用“离线皮肤设置”功能导致的问题：
#3746 #3879 #4013 #4272

**Comment by LTCatt** [comment]
![image](https://github.com/user-attachments/assets/f82dfb1a-aaf3-411d-8cb7-374c9e8e7f04)
该选项将默认折叠并添加警告条
