### ISSUE TITLE
添加一次性更新所有mod的按钮

### ISSUE THREAD

**Issue by HelloTMC** [Hex-Dragon/PCL2#4502]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在 版本设置-mod管理 中当有mod需要更新时，会出现mod更新的按钮，但如果需要更新的mod很多会耗费时间。可以添加一个一次性更新所有mod的按钮，这样不用一个一个按，会更方便些。

### 原因

这项优化让我可以更方便地更新所有mod。
如果没有这项优化，我每次都必须分别点更新mod的按钮，让操作变得很麻烦。

**Comment by SALTWOOD** [comment]
更新全部模组可以全选点更新啊……硬制造需求好吗

**Comment by JingHai-Lingyun** [comment]
#3752
