### ISSUE TITLE
PCL2重命名游戏版本出现已存在目录

### ISSUE THREAD

**Issue by AptS-1547** [Hex-Dragon/PCL2#4504]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

复现视频链接：https://pan.quark.cn/s/f43992d09701
发现如开头是中文，且至少要两个字符为中文（连续），在~后面输入一个数字会报错
其他的名称我还没有尝试，我等下去测试

### 重现步骤

1.版本选择选择一个版本
2.重命名
3.像附件链接视频一样进行修改
4.bug复现

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16622503/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16622504/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16622505/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16622506/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16622507/Log5.txt)

**Comment by allMagicNB** [comment]
你就不能截个图或者直接上传视频吗……

**Comment by SALTWOOD** [comment]
能发图吗……请不要把视频发到网盘，压缩一下传视频或者截图就行

**Comment by AptS-1547** [comment]
请稍等，之前不了解反馈BUG的流程，不好意思

**Comment by Mxmilu666** [comment]
![test](https://github.com/user-attachments/assets/04107dd9-5383-423f-a71f-b2105a6e95fa)

已复现

**Comment by SALTWOOD** [comment]
似乎是因为Windows的机制导致的，叫**短文件名**

**Comment by AptS-1547** [comment]
> 似乎是因为 Windows 的机制导致的，叫**NTFS 8.3 短文件名**
> 
> > 打开注册表并打开此目录 HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem
> > 修改 NtfsDisable8dot3NameCreation 的值为1 。
> 
> 试一下这个方法，记得删掉原来的文件夹再试，有条件可以把 **versions** 挪走再尝试复现

此方法可用，谢谢

**Comment by SALTWOOD** [comment]
那就说明是 Windows 的短文件名导致的，与 PCL 无关，属于历史遗留

**Comment by AptS-1547** [comment]
新功能提交里面开是吗

> 那就说明是 Windows 的短文件名导致的，与 PCL 无关，属于历史遗留 倒是可以考虑开一个新的 issue，检查重命名的输入是否合法

**Comment by SALTWOOD** [comment]
算优化

**Comment by SALTWOOD** [comment]
这个tag是不是有点问题……？

**Comment by AptS-1547** [comment]
后面开了#4505的，issue关的时候默认就加上忽略了
