### ISSUE TITLE
建议增加修改版本名前检查是否和NTFS 8.3 短文件名冲突

### ISSUE THREAD

**Issue by AptS-1547** [Hex-Dragon/PCL2#4505]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

#4504 
历史遗留问题 **NTFS 8.3 短文件名** 可能会导致在修改版本名的时候出现报错
建议增加新的检查项目防止出现这类问题

### 原因

有可能让玩家不知所措
可能会让我这样不懂的人开个bug issue（

**Comment by SALTWOOD** [comment]
引自[维基百科](https://zh.wikipedia.org/wiki/8.3%E6%96%87%E4%BB%B6%E5%90%8D)：
> 例如："TextFile.Mine.txt"会转换成"TE021F~1.TXT"。

当玩家尝试使用类似 `xxx~1` 这样的格式命名版本时，会因为 Windows 的 `NTFS 8.3 文件名`导致错误。
因此，本人认为，有必要增加一个检测，防止出现此类意外情况。

**Comment by SALTWOOD** [comment]
顺带再次询问一下：是直接选择屏蔽**~**还是选择**检测 NTFS 8.3 文件名**？

**Comment by AptS-1547** [comment]
看各位大大哪个开发容易吧……幸苦了
我个人认为屏蔽波浪号相比于检测 NTFS 8.3 文件名 会不太好一点，但开发会更加麻烦（低头）
幸苦各位大大了

**Comment by genshincoder** [comment]
个人建议：直接屏蔽~加数字的组合

**Comment by SALTWOOD** [comment]
> 个人建议：直接屏蔽~加数字的组合

目前版本已经能够很好的防止此类情况的发生，没必要再改成这样
