### ISSUE TITLE
龙猫太帅了

### ISSUE THREAD

**Issue by shencike** [Hex-Dragon/PCL2#4507]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

虽然你很帅但是你真的很帅，修bug的时候也要注意身体哦，累坏了就没人修bug了，加油

但是我想要隐藏主题，龙猫哥哥应该不会拒绝吧......
识别码：01C0-9344-5BF6-C774

### 重现步骤

帅呆了

**Comment by SALTWOOD** [comment]
神经病，你以为你乱发 issue 很帅？这只会加重社区管理的难度和龙猫的压力……
赶紧自删，或者来个 collaborator 加一个”删除“罢

**Comment by JingHai-Lingyun** [comment]
# 很明显你不能通过此方式获得活跃橙解锁码
你需要提交一个有效的 Bug，或是发起一个有意义的 Pull Request，并等待帖子标记为完成后才能获取

---

> 神经病，你以为你乱发 issue 很帅？这只会加重社区管理的难度和龙猫的压力……

好啦好啦别对人家语气这么差，虽然最近乱七八糟的帖子多起来了但是我们还是能处理过来的

**Comment by sulingjiang** [comment]
>赶紧自删

Permission denied

**Comment by Deep-Dark-Forest** [comment]
> 赶紧自删

author 不能删除 issue

**Comment by SALTWOOD** [comment]
大概那个意思罢了

**Comment by wuyuncheng-26** [comment]
issue 是给你反馈 bug 用的，不是给你用来夸人的……
你就算再怎么使劲夸龙猫也不会给你的。。。
~神金，害我笑了一下~
