### ISSUE TITLE
进入服务器皮肤显示错误

### ISSUE THREAD

**Issue by magic-CH** [Hex-Dragon/PCL2#4508]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我用little skin登入服务器皮肤发生了变化

### 重现步骤

1、点击多人游戏
2、往下滚，然后点击minecraft服务器进去都是这样

### 日志与附件

无日志

**Comment by SALTWOOD** [comment]
上传几张截图看看？怎么样的显示错误，并且确定一下不是皮肤未上传成功/损坏

**Comment by JingHai-Lingyun** [comment]
上传 PCL 日志，服务器内的截图，和你的 LittleSkin 角色设置页面的截图

**Comment by Paper-white** [comment]
首先，如果你进入的不是littleskin鉴权的服务器，并且没有使用CustomSkinLoader模组，那么不会加载来自littleskin的材质

**Comment by LeiSureLyYrsc** [comment]
从你的“**都**”字表明出来你进的服务器应该是**离线**服务器，离线服务器不会加载任何皮肤/披风，除非服务器安装了**皮肤插件**从正版档案中获取到了皮肤，否则你的皮肤就是Minecraft原版提供的形象

解决办法:
1.安装CustomSkinLoader模组
2.进入有通过LittleSkin鉴权的服务器
3.更换LittleSkin鉴权
(↑这个几乎没可能，但也是一种解决方案）

你这个Issue游戏截图没给 ID没给，我只能靠推断尽可能为你解决问题了

(你最好还是给个游戏截图，并提供ID)

**Comment by SALTWOOD** [comment]
@magic-CH 补一下信息谢谢（

**Comment by ZeroWolf233** [comment]
有没有种可能，这服务器他就不支持little skin
还有如果你想要好好反馈问题请提供更多的资料，log日志和little skin的配置截图

**Comment by Deep-Dark-Forest** [comment]
超时关闭。
