### ISSUE TITLE
导出整合包功能

### ISSUE THREAD

**Issue by sensen1234** [Hex-Dragon/PCL2#4510]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

建议增加整合包导出功能，格式可以为mcbbs整合包等格式，没有导出整合包对整合包作者来说太困难了

### 原因

没有导出整合包对整合包作者来说太困难了

**Comment by sensen1234** [comment]
目前虽然能导出modrinth格式，但mcbbs格式的对整合包作者会更友好
可以添加一个导出启动器功能，导出来正式版启动器到压缩包里，用户双击启动器自动补全文件

**Comment by hejiehao** [comment]
Issue：https://github.com/Hex-Dragon/PCL2/issues/98
Pull Request：https://github.com/Hex-Dragon/PCL2/pull/4206

**Comment by hejiehao** [comment]
> 目前虽然能导出modrinth格式，但mcbbs格式的对整合包作者会更友好

https://github.com/Hex-Dragon/PCL2/issues/98

**Comment by SALTWOOD** [comment]
#98 , duplicate
重复，关了吧
