### ISSUE TITLE
无法将压缩包内的mod通过拖拽添加

### ISSUE THREAD

**Issue by WhiteXero** [Hex-Dragon/PCL2#4511]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

**我知道直接将压缩包里的文件拖进PCL而不解压很蠢，但我还是反馈一下**
![image](https://github.com/user-attachments/assets/23075a1b-231a-4b3e-a445-ede0d0db41a6)

### 重现步骤

将压缩包中的任意文件拖入PCL。

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16632196/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16632198/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16632200/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16632203/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16632197/Log5.txt)

**Comment by wuyuncheng-26** [comment]
~这确实挺蠢的~
拖进去的只能是 .jar 文件
你拖个 .zip 进去它肯定搞不定啊

**Comment by WhiteXero** [comment]
> ~这确实挺蠢的~ 拖进去的只能是 .jar 文件 你拖个 .zip 进去它肯定搞不定啊

是的所以确实蠢（
没有拖zip。就是在模组管理页面拖入jar文件

**Comment by WhiteXero** [comment]
建议把报错改一改就好了

**Comment by wuyuncheng-26** [comment]
> > ~这确实挺蠢的~ 拖进去的只能是 .jar 文件 你拖个 .zip 进去它肯定搞不定啊
> 
> 是的所以确实蠢（ 没有拖zip。就是在模组管理页面拖入jar文件

抱歉我刚刚理解错了 qwq

**Comment by allMagicNB** [comment]
你拖的什么玩意

**Comment by wuyuncheng-26** [comment]
> 你拖的什么玩意

好问题，他应该拖的是 .jar 吧，只是还在压缩包里

**Comment by WhiteXero** [comment]
> ~这确实挺蠢的~ .zip 里的文件还没被解压出来 路径都还没有呢

一般来说拖拽文件到压缩包外会先将文件解压到临时的路径下
例如我这个 C:\Users\White\AppData\Local\Temp\peazip-tmp\.ptmp4486DA\customskymod.jar

我认为只要把这个报错改一改就好了，毕竟不是程序bug（

**Comment by wuyuncheng-26** [comment]
> > ~这确实挺蠢的~ .zip 里的文件还没被解压出来 路径都还没有呢
> 
> 一般来说拖拽文件到压缩包外会先将文件解压到临时的路径下 例如我这个 C:\Users\White\AppData\Local\Temp\peazip-tmp.ptmp4486DA\customskymod.jar
> 
> 我认为只要把这个报错改一改就好了，毕竟不是程序bug（

好吧，确实是我说错了（
你要不试试压缩包里的其他模组？
也许可能是这个模组的问题呢（

**Comment by WhiteXero** [comment]
> 好吧，确实是我说错了（ 你要不试试压缩包里的其他模组？ 也许可能是这个模组的问题呢（

应该不是模组的问题 我觉得是PCL在处理这个拖拽文件的时候出的异常
放一下详细错误把

`[10:23:04.703] 接取拖拽事件失败：无效的 FORMATETC 结构 (异常来自 HRESULT:0x80040064 (DV_E_FORMATETC))
由于操作系统或显卡存在问题，导致出现错误。请尝试重启 PCL。
————————————
详细错误信息：
   在 System.Runtime.InteropServices.ComTypes.IDataObject.GetData(FORMATETC& format, STGMEDIUM& medium)
   在 System.Windows.DataObject.OleConverter.GetDataInner(FORMATETC& formatetc, STGMEDIUM& medium)
   在 System.Windows.DataObject.OleConverter.GetDataFromOleHGLOBAL(String format, DVASPECT aspect, Int32 index)
   在 System.Windows.DataObject.OleConverter.GetDataFromBoundOleDataObject(String format, DVASPECT aspect, Int32 index)
   在 System.Windows.DataObject.OleConverter.GetData(String format, Boolean autoConvert, DVASPECT aspect, Int32 index)
   在 System.Windows.DataObject.OleConverter.GetData(String format, Boolean autoConvert)
   在 PCL.FormMain.FrmMain_Drop(Object sender, DragEventArgs e)
错误类型：System.Runtime.InteropServices.COMException`

从压缩包拖放文件的时候，是会给出这个文件的临时路径的（例如图片中，拖放文件到CMD为例，CMD中的就是临时路径）
详细错误信息里的异常出在 IDataObject::GetData 方法这一块，且报错 DV_E_FORMATETC
根据Win32API的文档：

> DV_E_FORMATETC | pformatetcIn 的值无效。

> [in] pformatetcIn
> 指向 [FORMATETC](https://learn.microsoft.com/zh-cn/windows/desktop/api/objidl/ns-objidl-formatetc) 结构的指针，该结构定义在传递数据时要使用的格式、介质和目标设备。

个人猜测是 pformatetcIn 的指针这一块出了问题（也许是路径问题？）

**Comment by SALTWOOD** [comment]
我记得好像有重复（？
我去找找看

**Comment by wuyuncheng-26** [comment]
类似于 #4191？

**Comment by WhiteXero** [comment]
不一样吧
那个是需求拖入多个文件

**Comment by wuyuncheng-26** [comment]
@WhiteXero 可以告诉我你用的是哪款解压软件吗（

**Comment by WhiteXero** [comment]
> @WhiteXero 可以告诉我你用的是哪款解压软件吗（

peazip

**Comment by wuyuncheng-26** [comment]
要不换一款看看有没有同样的问题（
根据 #4191 来看有可能是解压软件本身的问题（
________________________________
发件人: ***@***.*** ***@***.***> 代表 十三 ***@***.***>
发送时间: 2024年8月15日 21:04
收件人: Hex-Dragon/PCL2 ***@***.***>
抄送: 是小胖呀26 ***@***.***>; Comment ***@***.***>
主题: Re: [Hex-Dragon/PCL2] 无法将压缩包内的mod通过拖拽添加 (Issue #4511)


@WhiteXero<https://github.com/WhiteXero> 可以告诉我你用的是哪款解压软件吗（

peazip

―

**Comment by LTCatt** [comment]
考虑到是 COMException，感觉是压缩软件的问题……
