### ISSUE TITLE
移除统一通行证验证选项

### ISSUE THREAD

**Issue by Pigeon0v0** [Hex-Dragon/PCL2#4513]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

直接移除统一通行证选项，抑或是作为 Authlib-Injector 的一个子项

### 原因

有以下几点理由：
- 统一通行证目前适用面极小，原使用者完全可以迁移至 LittleSkin 等基于 Authlib-Injector 方案的外置验证，且自由度更高。
- 绝大部分启动器已经放弃（或从未添加）对统一通行证的支持。
- 统一通行证和 Authlib-Injector 并排放置可能会增加用户理解成本。
- 根据 [yushijinhun 的评论](https://github.com/HMCL-dev/HMCL/pull/1744#issuecomment-1256263929)，统一通行证实质上为魔改的 Authlib-Injector 实现，且并未遵循上游 LICENCE。
- 在上一点的下文中，经过用户测试，可以通过添加特定地址的 Authlib-Injector 服务器来正常进行验证。

**Comment by SALTWOOD** [comment]
支持，没必要为了一个根本没啥新功能的东西加一个单独的选项，而且它还不遵守开源协议

**Comment by Pigeon0v0** [comment]
另外还有一些个人观点：

统一通行证这个 Doc 至今为止还有 CSS 问题，真的很难相信它还在持续更新...

**Comment by CrazyNutLz** [comment]
统一能用不就行了吗- - 有也是在这个地方放着。
如果本来没有可能没啥适配的必要，但是有没必要删掉

**Comment by Pigeon0v0** [comment]
> 统一能用不就行了吗- - 有也是在这个地方放着。 如果本来没有可能没啥适配的必要，但是有没必要删掉

这可能是一个冗余的选项，你没好好看主楼

**Comment by LTCatt** [comment]
我觉得就算是为了保持对既有玩家的兼容性，也没必要特意把一个选项给删了吧……
删这玩意儿并没有让什么功能变得更好，反而让现有的玩家（不管有多少）用不了了，所以我觉得是个负向改动（
