### ISSUE TITLE
爱发电网址迁移到ifdian.net

### ISSUE THREAD

**Issue by XiaLize** [Hex-Dragon/PCL2#4514]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

赞助作者跳转爱发电提示没有该网址或已经迁移到其他网址

### 重现步骤

选择赞助作者爱发电

### 日志与附件

![b8ab8807-5f40-47b9-baf8-5a6bb0d8407a](https://github.com/user-attachments/assets/ad6231c6-0e9e-44ed-8957-1199aef0ce19)

**Comment by SALTWOOD** [comment]
#4271

**Comment by wuliaodexiaoluo** [comment]
>爱发电网址迁移到ifdian.net

ifdian.net 并不是最终地址，afdian.com 才是
