### ISSUE TITLE
[优化] 移除设置为 LittleSkin 的按钮

### ISSUE THREAD

**Issue by wuliaodexiaoluo** [Hex-Dragon/PCL2#4518]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

移除第三方登录的设置为 LittleSkin 的按钮

### 原因

根据部分腐竹的反馈，这个按钮没有任何提示，连悬浮文本都没有，大多数萌新会被误导按这个按钮设置为 LittleSkin 登录，但这可能和腐竹要求的登录方式不符，并且 LittleSkin 的 API 地址并不长，完全可以手打，官方也提供了拖拽设置，因此完全没有必要再多个设置为 LittleSkin 的按钮

**Comment by wuyuncheng-26** [comment]
与 #3045 重复

**Comment by wuliaodexiaoluo** [comment]
等#57得等到猴年马月（

**Comment by allMagicNB** [comment]
@Deep-Dark-Forest 出来挨打

**Comment by Deep-Dark-Forest** [comment]
> @Deep-Dark-Forest 出来挨打

这种事情出现过不止一次……

**Comment by LTCatt** [comment]
![image](https://github.com/user-attachments/assets/cebd6ce0-63c4-4d31-ade2-20c7e86eb278)
