### ISSUE TITLE
删除Mod时弹出确认按钮

### ISSUE THREAD

**Issue by GOhaochen** [Hex-Dragon/PCL2#4520]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

![image](https://github.com/user-attachments/assets/15ecb5c4-81fb-422d-8f6d-5162d69ac2ee)
如图所示

### 原因

这样能减少误触的可能，为文件删除添加一道防线

**Comment by Ad-closeNN** [comment]
emmm没必要，能从回收站还原

**Comment by GOhaochen** [comment]
> emmm没必要，能从回收站还原

没有必要为了一个两个Mod翻回收站，直接防止误操作更香

**Comment by allMagicNB** [comment]
> > emmm没必要，能从回收站还原
> 
> 没有必要为了一个两个Mod翻回收站，直接防止误操作更香

没有必要为了一两个误删除的 Mod 防止误删除。

**Comment by LTCatt** [comment]
暂不考虑，抱歉

**Comment by i486-DX9** [comment]
BakaXL虽然是彻底删除，但至少给了你几秒做最后选择……
就是为了防止你误触

**Comment by wuliaodexiaoluo** [comment]
>BakaXL虽然是彻底删除，但至少给了你几秒做最后选择……
就是为了防止你误触

请不要在已经关闭的 Issue 内回复内容，否则您的账户可能会被暂时封禁
