### ISSUE TITLE
获取网站时失败

### ISSUE THREAD

**Issue by wuwenjun9939** [Hex-Dragon/PCL2#4521]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/user-attachments/assets/c923915f-591f-44b2-ab9c-7e1a3b115097)

### 重现步骤

打开之后直接崩溃

### 日志与附件

[Log3.txt](https://github.com/user-attachments/files/16644295/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16644296/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16644297/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/16644298/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16644299/Log2.txt)

**Comment by allMagicNB** [comment]
你用的什么主页

**Comment by wuyuncheng-26** [comment]
这是主页的问题啊。。。
可能你使用的主页的服务器崩了吧
与 PCL 无关

**Comment by wuwenjun9939** [comment]
> 你用的什么主页

emmm...最亮的信标（这回应该懂了）

**Comment by wuwenjun9939** [comment]
> 这是主页的问题啊。。。 可能你使用的主页的服务器崩了吧 与 PCL 无关

关键是，最亮的信标就在GitHub，我咋找他？

**Comment by allMagicNB** [comment]
@Light-Beacon

**Comment by wuyuncheng-26** [comment]
群号：828081791





------------------ 原始邮件 ------------------
发件人: wuwenjun9939 ***@***.***&gt;
发送时间: 2024年8月17日 18:01
收件人: Hex-Dragon/PCL2 ***@***.***&gt;
抄送: 是小胖呀26 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Hex-Dragon/PCL2] 获取网站时失败 (Issue #4521)





  
这是主页的问题啊。。。 可能你使用的主页的服务器崩了吧 与 PCL 无关
  
关键是，最亮的信标就在GitHub，我咋找他？

**Comment by youzi-2333** [comment]
信标的主页地址是 `https://news.bugjump.net`，而非 `http://pcl2.mc-news.top`。

您也可以在 `设置 -> 个性化 -> 主页` 中选择 `预设`，并选中 `Minecraft 新闻` 以加载主页，感谢您的反馈。

**Comment by wuliaodexiaoluo** [comment]
>[17:50:14.892] [Start] 程序版本：Snapshot 2.6.8（305）

请更新下启动器

**Comment by wuyuncheng-26** [comment]
建议：下次别用联网更新，用预设防止自己填错
