### ISSUE TITLE
切换版本时启动器报错

### ISSUE THREAD

**Issue by DistinctMedal42** [Hex-Dragon/PCL2#4523]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

程序出现未知错误:未将对象引用设置到对象的实例，
在PCL.Modsecret.ThemeCheckGold(String Code）
在PCL.PageLaunchRight.Init()
错误类型:System.NulReferenceException
是否反馈此问题?如果不反馈，这个问题可能永远无法得到解决!

### 重现步骤

在版本选择里切换版本时会出现这个bug

### 日志与附件

[Log.txt](https://github.com/user-attachments/files/16644785/Log.txt)
[Log1.txt](https://github.com/user-attachments/files/16644786/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16644787/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16644788/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16644789/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16644790/Log5.txt)

**Comment by allMagicNB** [comment]
#4517

**Comment by JingHai-Lingyun** [comment]
Log2 最底下见

<details>
<summary>详细日志内容</summary>

```
[19:59:01.303] [Minecraft] 启动按钮：Minecraft 版本：D:\Minecraft\-shot 2.6.8\.minecraft服务器\versions\1.20.1-Forge_47.3.5\
[19:59:01.579] [System] 诊断信息：
操作系统：Microsoft Windows 11 家庭版
剩余内存：10139 M / 16087 M
DPI：96（100%）
MC 文件夹：D:\Minecraft\-shot 2.6.8\.minecraft服务器\
文件位置：D:\Minecraft\-shot 2.6.8\
[19:59:01.581] 程序出现未知错误：未将对象引用设置到对象的实例。
   在 38BD0F1D.1B1872AE(Exception 38A30CC4)
   在 38BD0F1D.281B5D22(Object[] 74A83A95, Int32 30B57491)
   在 PCL.ModSecret.ThemeCheckGold(String Code)
   在 PCL.PageLaunchRight.Init()
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   在 System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   在 MS.Internal.LoadedOrUnloadedOperation.DoWork()
   在 System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   在 System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   在 System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   在 System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
错误类型：System.NullReferenceException
[19:59:39.245] [System] 诊断信息：
操作系统：Microsoft Windows 11 家庭版
剩余内存：9254 M / 16087 M
DPI：96（100%）
MC 文件夹：D:\Minecraft\-shot 2.6.8\.minecraft服务器\
文件位置：D:\Minecraft\-shot 2.6.8\
[19:59:39.245] [System] 执行外部命令：explorer.exe "D:\Minecraft\-shot 2.6.8\PCL\"
[19:59:39.381] [System] 正在打开网页：https://github.com/Hex-Dragon/PCL2/issues/
[19:59:39.536] [System] 程序已退出，返回值：Fail
```

</details>

看起来不太像是 PCL 的问题…… 但也不清楚怎么回事

**Comment by SALTWOOD** [comment]
PCL 经过那么久的开发已经很稳定了最近却出现两个和 `NullReferenceException` 有关的 Issue，不得不怀疑龙猫动了什么屎山……

**Comment by LTCatt** [comment]
这似乎是 VMP 壳的 bug。
报错的函数并不存在于 PCL 的代码中，try-catch 都捕获不到这个异常，也没法复现……
有具体的触发条件吗？或许也需要社区测试会触发问题的环境……？

**Comment by Silverteal** [comment]
如果问题一直出现，楼主可以尝试换成其他主题……

**Comment by lactobionicAcid** [comment]
似乎与 #4517 有一定的相关性...

**Comment by Silverteal** [comment]
> 似乎与 #4517 有一定的相关性...

考虑到有关函数的性质，可能是 VMP 对这部分进行附加的保护时进行了一些可能导致出现不稳定空引用的操作。

**Comment by bmmNbhjd** [comment]
~~脱了壳再试试能不能复现~~

**Comment by LTCatt** [comment]
确实同 #4517，转到那里去

**Comment by SALTWOOD** [comment]
> 这似乎是 VMP 壳的 bug。 报错的函数并不存在于 PCL 的代码中，try-catch 都捕获不到这个异常，也没法复现…… 有具体的触发条件吗？或许也需要社区测试会触发问题的环境……？

是否有其他版本或类型的壳可用？

**Comment by SALTWOOD** [comment]
> 这似乎是 VMP 壳的 bug。 报错的函数并不存在于 PCL 的代码中，try-catch 都捕获不到这个异常，也没法复现…… 有具体的触发条件吗？或许也需要社区测试会触发问题的环境……？

真不是我贬低什么的，也许可以去排查排查最近版本的更改？毕竟最近半个月突然冒出来三条都跟null reference exception有关
