### ISSUE TITLE
[优化] 查看日志使用 latest.log 而不是 hs_err_pid 文件

### ISSUE THREAD

**Issue by wuliaodexiaoluo** [Hex-Dragon/PCL2#4524]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

查看日志使用 latest.log 替代 hs_err_pid

### 原因

据我观察 hs_err_pid 应该是 JVM 堆栈报告
已发现 #4515 将此报告作为 Minecraft 崩溃日志提交到社区寻求帮助，但大部分协作者和贡献者应该是看不懂这玩意，无法及时给出有效的解决方案，最多只能走个形式（也就是按照 PCL 的建议去处理，或者按照崩溃一般处理流程处理），使用 latest.log 可能可以显著减缓此问题（至少大家看得懂）

**Comment by zkitefly** [comment]
导出和分析是两码事吧

**Comment by zkitefly** [comment]
游戏崩溃就 pcl 的打开游戏日志是 pcl 自己记录 mc 的日志输出，不是 latest.log 或 hs_err_pid.log

**Comment by Chiloven945** [comment]
~~给我一种把所有人骂了的感觉~~

**Comment by hejiehao** [comment]
https://github.com/Hex-Dragon/PCL2/issues/4515 的并不是 hs_err_pid.log

**Comment by JingHai-Lingyun** [comment]
hs_err_pid.log 是一个包含详细崩溃信息（包含崩溃简述、系统信息、堆栈信息等）的 Crash 日志
#4515 上传的不知道是啥~~野路子来的~~日志
暂没有发现相关反馈，挂个待处理看看

**Comment by LTCatt** [comment]
PCL 仅会在 logs 文件夹下没有有效的 log 文件时才会展示 hs_err。
