### ISSUE TITLE
下载特定整合包文件时出错

### ISSUE THREAD

**Issue by MandatedSleet19** [Hex-Dragon/PCL2#4525]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在PCL2上下载整合包 Adventure & Exploration Part2时启动器报错，无法安装。相同网络环境使用BakaXL启动器可正常安装。（不过没法正常启动）
在浏览器下载整合包文件后安装仍然失败。
使用PCL2启动器安装别的整合包正常。

### 重现步骤

见描述

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16645128/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16645129/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16645130/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16645131/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16645132/Log5.txt)

**Comment by Chiloven945** [comment]
```
[21:39:29.858] [Download] Adventure & Exploration Part2.jar 2675#：出错，基础连接已经关闭: 发送时发生错误。
你的网络环境不佳，导致难以连接到服务器。请检查网络，多重试几次，或尝试使用 VPN。
————————————
详细错误信息：
→ 无法从传输连接中读取数据: 远程主机强迫关闭了一个现有的连接。。
→ 远程主机强迫关闭了一个现有的连接。
   在 PCL.ModNet.NetFile.Thread(NetThread Info)
错误类型：System.Net.Sockets.SocketException
```
```
[21:39:36.303] 加载线程 解压整合包文件 (72) 发生运行时错误：指定的路径或文件名太长，或者两者都太长。完全限定文件名必须少于 260 个字符，并且目录名必须少于 248 个字符。
   在 System.IO.PathHelper.GetFullPathName()
   在 System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   在 System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry source, String destinationFileName, Boolean overwrite)
   在 PCL.ModBase.ExtractFile(String CompressFilePath, String DestDirectory, Encoding Encode)
   在 PCL.ModModpack.UnpackFiles(String InstallTemp, String FileAddress, LoaderBase Loader)
   在 PCL.ModModpack._Closure$__6-0._Lambda$__0(LoaderTask`2 Task)
   在 PCL.ModLoader.LoaderTask`2._Closure$__13-0._Lambda$__0()
错误类型：System.IO.PathTooLongException
```

**Comment by MandatedSleet19** [comment]
关于这个我改过文件名称，检查过目录还是不行，况且装别的整合包是可以的

**Comment by MandatedSleet19** [comment]
感谢

**Comment by JingHai-Lingyun** [comment]
这不是 碰呲了 的问题，先关了
