### ISSUE TITLE
[Bug] 无法安装愚人节版本: 1.RV-Pre1：从字符串 1.RV-Pre1 到类型 Integer 的转换无效

### ISSUE THREAD

**Issue by wuliaodexiaoluo** [Hex-Dragon/PCL2#4528]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

2.8.4 的开门红
无法安装 1.RV-Pre1

### 重现步骤

下载页面选择1.RV-Pre1然后安装

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16645654/Log1.txt)
![OFWX94GLEKKRA`D%L$L{4WT](https://github.com/user-attachments/assets/d614ba4c-305f-46a4-bb01-922b972b0f95)

**Comment by JingHai-Lingyun** [comment]
嗯，这不是整形……

**Comment by LTCatt** [comment]
你的解锁码：x1sM7YO4UOcF7Mj3gdKGOpPHi98+GQ2d
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
