### ISSUE TITLE
1.16.5opfineG8正式版和forge36.2.34下载错误

### ISSUE THREAD

**Issue by gumingxuan123** [Hex-Dragon/PCL2#453]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如标题

### 重现步骤

如标题

### 日志与附件

安装游戏失败
Caused By: 在某些文件和目录下未能完成操作。有关详细信息，请参阅该异常的 Data 属性。
   在 PCL.ModDownloadLib._Closure$__54-0._Lambda$__0(LoaderTask`2 Task)
   在 PCL.ModLoader.LoaderTask`2._Closure$__12-0._Lambda$__0()
错误类型：System.IO.IOException

**Comment by LTCatt** [comment]
补充完整日志文件

**Comment by dongge0210** [comment]
这家伙不看邮箱

**Comment by LTCatt** [comment]
超时关闭，如果有需要可以重新开一个 Issue。
