### ISSUE TITLE
优化回声洞投稿按钮

### ISSUE THREAD

**Issue by CJL114514** [Hex-Dragon/PCL2#4531]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

把那个投稿按钮从文字换成一个图标

### 原因

看着不爽

**Comment by wuyuncheng-26** [comment]
但是换成图标会占空间影响整体美观性……

**Comment by Chormore-EDGE** [comment]
~其实这玩意确实有点小~看能不能做吧

**Comment by Chiloven945** [comment]
很丑，估计会被拒

**Comment by LTCatt** [comment]
暂时没这打算……
