### ISSUE TITLE
导出错误报告失败

### ISSUE THREAD

**Issue by PhiseecodyHSP** [Hex-Dragon/PCL2#4534]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在快照版2.8.4，启动游戏崩溃报错后，点选“导出错误报告”，提示“导出错误报告失败：文件’PCL\Log1.txt‘正由另一进程使用，因此该进程无法访问此文件”，重启电脑依旧
附窗口截图↓
![屏幕截图 2024-08-18 124630](https://github.com/user-attachments/assets/8d818a85-d7dc-48e3-b679-12dbb5e20b10)

### 重现步骤

1.让你的Minecraft报错崩溃
2.启动器提示”Minecraft 出现错误“后选择“导出错误报告”

### 日志与附件

[Log3.txt](https://github.com/user-attachments/files/16647228/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16647229/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16647230/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/16647231/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16647232/Log2.txt)

**Comment by wuyuncheng-26** [comment]
有其他软件打开了日志吗
比如说记事本之类的

**Comment by Mxmilu666** [comment]
1.确认是否有其他程序正在使用该文件。可以通过关闭相关的程序来释放文件。

2.如果仍然无法确定哪个进程锁定了文件，可以使用第三方工具（如 Unlocker 或 Process Explorer）来找出并解锁被占用的文件。

**Comment by PhiseecodyHSP** [comment]
> 后台有其他软件打开了日志吗 比如说记事本之类的

应该是没有……我重启电脑后直接打开PCL导出错误报告还是提示这个，Log1在没有打开PCL的情况下也能直接拖到回收站

**Comment by PhiseecodyHSP** [comment]
并且后面我发现这个Log1怎么大小是0呢，跟这个有关吗？
![屏幕截图 2024-08-18 132703](https://github.com/user-attachments/assets/511aab0e-a730-4384-ae73-8d64e5a05cbf)

**Comment by wuyuncheng-26** [comment]
用 PowerToys 的 File Locksmith 看看是哪个进程打开了日志文件？

**Comment by allMagicNoNB** [comment]
确认存在此问题。

**Comment by PhiseecodyHSP** [comment]
> PowerToys

![image](https://github.com/user-attachments/assets/bf44a063-9f17-431b-8ab9-c711a3e4e913)

**Comment by PhiseecodyHSP** [comment]
> 1.确认是否有其他程序正在使用该文件。可以通过关闭相关的程序来释放文件。
> 
> 2.如果仍然无法确定哪个进程锁定了文件，可以使用第三方工具（如 Unlocker 或 Process Explorer）来找出并解锁被占用的文件。

应该是没有其它进程在占用Log1了

**Comment by PhiseecodyHSP** [comment]
> 用 PowerToys 的 File Locksmith 看看是哪个进程打开了日志文件？

![image](https://github.com/user-attachments/assets/66fe4d8a-8c79-4373-9908-a3ac23975cd3)

**Comment by wuyuncheng-26** [comment]
奇怪……
那可能确实是 PCL 产生的问题（
________________________________
发件人: ***@***.*** ***@***.***> 代表 PhiseecodyHSP ***@***.***>
发送时间: 2024年8月17日 22:35
收件人: Hex-Dragon/PCL2 ***@***.***>
抄送: 是小胖呀26 ***@***.***>; Comment ***@***.***>
主题: Re: [Hex-Dragon/PCL2] 导出错误报告失败 (Issue #4534)


PowerToys

image.png (view on web)<https://github.com/user-attachments/assets/bf44a063-9f17-431b-8ab9-c711a3e4e913>

―

**Comment by allMagicNoNB** [comment]
用了powertoys，显示只有pcl2在使用log1.txt。

**Comment by JingHai-Lingyun** [comment]
![image](https://github.com/user-attachments/assets/252b21b7-bd14-43bb-b7ce-5b19f9c2771b)
![image](https://github.com/user-attachments/assets/7735e0c0-199a-4594-bfc6-81093ac7522a)
确认产生了线程冲突

**Comment by PhiseecodyHSP** [comment]
所以可以给我解锁隐藏主题了嘛？谢谢！

识别码：016C-0CEE-C4CD-7628
















在 2024-08-19 20:38:18，"龙腾猫跃" ***@***.***> 写道：

Closed #4534 as completed.

**Comment by wuyuncheng-26** [comment]
@LTCatt

**Comment by wuliaodexiaoluo** [comment]
>所以可以给我解锁隐藏主题了嘛？谢谢！
识别码：016C-0CEE-C4CD-7628

麻烦下次删干净或者直接写，删一般般 GitHub 识别不到不会折叠的

**Comment by PhiseecodyHSP** [comment]
> > 所以可以给我解锁隐藏主题了嘛？谢谢！
> > 识别码：016C-0CEE-C4CD-7628
> 
> 麻烦下次删干净或者直接写，删一半 GitHub 识别不到不会折叠的

啊我是在邮箱里直接回复的，不好意思！
其实是我没理解好它说的回复识别码要求解锁是在哪里回复谁→←

**Comment by JingHai-Lingyun** [comment]
> https://shimo.im/docs/qKPttVvXKqPD8YDC

通过反馈解锁：反馈一个 Bug，且被采纳并实际制作（Issue 标签为“已完成”），然后在**该 Issue 下**回复 PCL 识别码。

---

你已经发送了识别码，等待龙猫回复您就好

**Comment by LTCatt** [comment]
你的解锁码：JUvX+KJssJYL9WaMwSsUuJXi9Q7ACbeM
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by wuwenjun9939** [comment]
> 你的解锁码：JUvX+KJssJYL9WaMwSsUuJXi9Q7ACbeM 在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

不对吧....好像我这还能复现
![image](https://github.com/user-attachments/assets/a4c6e653-627b-49c8-b749-b8aac777135d)

**Comment by wuwenjun9939** [comment]
[Log3.txt](https://github.com/user-attachments/files/16692168/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16692169/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16692170/Log5.txt)
[Log.txt](https://github.com/user-attachments/files/16692171/Log.txt)
（log1因为占用所以发不出来，等我一下）
[Log1.txt](https://github.com/user-attachments/files/16692184/Log1.txt)

**Comment by lactobionicAcid** [comment]
> 不对吧....好像我这还能复现

PCL 的下次更新会解决这个问题。~请坐和放宽...~

**Comment by wuwenjun9939** [comment]
> > 不对吧....好像我这还能复现
> 
> PCL 的下次更新会解决这个问题。~请坐和放宽...~

emmm我已经更新到了快照版2.8.4了....

**Comment by wuwenjun9939** [comment]
![image](https://github.com/user-attachments/assets/a45f13c6-f043-4b01-a72d-706b06bf268b)
![image](https://github.com/user-attachments/assets/a9ed6968-6aa6-46a0-8dc3-fb0e6204c060)

**Comment by Mxmilu666** [comment]
> > > 不对吧....好像我这还能复现
> > 
> > PCL 的下次更新会解决这个问题。~请坐和放宽...~
> 
> emmm我已经更新到了快照版2.8.4了....

下次更新，是下次，不是现在

**Comment by wuwenjun9939** [comment]
> > > > 不对吧....好像我这还能复现
> > > 
> > > 
> > > PCL 的下次更新会解决这个问题。~请坐和放宽...~
> > 
> > 
> > emmm我已经更新到了快照版2.8.4了....
> 
> 下次更新，是下次，不是现在

emmm，我理解错了还是龙猫没说清？？？
@[JingHai-Lingyun](https://github.com/JingHai-Lingyun) JingHai-Lingyun added [等待确认](https://github.com/Hex-Dragon/PCL2/labels/%E7%AD%89%E5%BE%85%E7%A1%AE%E8%AE%A4) and removed [新反馈](https://github.com/Hex-Dragon/PCL2/labels/%E6%96%B0%E5%8F%8D%E9%A6%88) labels [3 days ago](https://github.com/Hex-Dragon/PCL2/issues/4534#event-13921244430)
@[LTCatt](https://github.com/LTCatt) LTCatt added [处理中](https://github.com/Hex-Dragon/PCL2/labels/%E5%A4%84%E7%90%86%E4%B8%AD) [🟥 高](https://github.com/Hex-Dragon/PCL2/labels/%F0%9F%9F%A5%20%E9%AB%98) and removed [等待确认](https://github.com/Hex-Dragon/PCL2/labels/%E7%AD%89%E5%BE%85%E7%A1%AE%E8%AE%A4) labels [3 days ago](https://github.com/Hex-Dragon/PCL2/issues/4534#event-13921586932)
@[wuyuncheng-26](https://github.com/wuyuncheng-26) wuyuncheng-26 mentioned this issue [2 days ago](https://github.com/Hex-Dragon/PCL2/issues/4534#ref-issue-2472856562)
https://github.com/Hex-Dragon/PCL2/issues/4550
Closed
1 task
@[LTCatt](https://github.com/LTCatt) LTCatt closed this as [completed](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) [2 days ago](https://github.com/Hex-Dragon/PCL2/issues/4534#event-13929807882)
这个意思不就是解决了吗？我更新到2.8.4了啊，没错吧？下次更新的话...2.8.5？？？

**Comment by Mxmilu666** [comment]
> > > > > 不对吧....好像我这还能复现
> > > > 
> > > > 
> > > > PCL 的下次更新会解决这个问题。~请坐和放宽...~
> > > 
> > > 
> > > emmm我已经更新到了快照版2.8.4了....
> > 
> > 下次更新，是下次，不是现在
> 
> emmm，我理解错了还是龙猫没说清？？？
> @[JingHai-Lingyun](https://github.com/JingHai-Lingyun) JingHai-Lingyun added [等待确认](https://github.com/Hex-Dragon/PCL2/labels/%E7%AD%89%E5%BE%85%E7%A1%AE%E8%AE%A4) and removed [新反馈](https://github.com/Hex-Dragon/PCL2/labels/%E6%96%B0%E5%8F%8D%E9%A6%88) labels [3 days ago](https://github.com/Hex-Dragon/PCL2/issues/4534#event-13921244430)
> @[LTCatt](https://github.com/LTCatt) LTCatt added [处理中](https://github.com/Hex-Dragon/PCL2/labels/%E5%A4%84%E7%90%86%E4%B8%AD) [🟥 高](https://github.com/Hex-Dragon/PCL2/labels/%F0%9F%9F%A5%20%E9%AB%98) and removed [等待确认](https://github.com/Hex-Dragon/PCL2/labels/%E7%AD%89%E5%BE%85%E7%A1%AE%E8%AE%A4) labels [3 days ago](https://github.com/Hex-Dragon/PCL2/issues/4534#event-13921586932)
> @[wuyuncheng-26](https://github.com/wuyuncheng-26) wuyuncheng-26 mentioned this issue [2 days ago](https://github.com/Hex-Dragon/PCL2/issues/4534#ref-issue-2472856562)
> https://github.com/Hex-Dragon/PCL2/issues/4550
> Closed
> 1 task
> @[LTCatt](https://github.com/LTCatt) LTCatt closed this as [completed](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) [2 days ago](https://github.com/Hex-Dragon/PCL2/issues/4534#event-13929807882)
> 这个意思不就是解决了吗？我更新到2.8.4了啊，没错吧？下次更新的话...2.8.5？？？

请关注龙猫的爱发电，感谢

**Comment by JingHai-Lingyun** [comment]
此 Issue 于 2.8.4 发布后才标记为已完成，请 ~~坐和放宽，~~ 等待下一次版本发布

**Comment by wuwenjun9939** [comment]
> 此 Issue 于 2.8.4 发布后才标记为已完成，请 ~坐和放宽，~ 等待下一次版本发布

不过，好像是快照版才会有的bug，正式版没有唉
[错误报告-2024-8-21_21.56.51.zip](https://github.com/user-attachments/files/16692649/-2024-8-21_21.56.51.zip)

**Comment by Michaelshenmo** [comment]
> 此 Issue 于 2.8.4 发布后才标记为已完成，请 ~坐和放宽，~ 等待下一次版本发布

2.8.4仍然有这个bug
