### ISSUE TITLE
自动清理 libjlw.dll

### ISSUE THREAD

**Issue by JingHai-Lingyun** [Hex-Dragon/PCL2#4535]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

虽然这东西不大，也不会很经常更新，但…… 就看着不是很舒服
![image](https://github.com/user-attachments/assets/7a5007df-1ce9-4a6f-bf56-d5cb8b7450be)

**Comment by wuyuncheng-26** [comment]
![image](https://github.com/user-attachments/assets/d173b453-80e7-40b3-b384-c3545ac07836)
？我的咋没更新（

**Comment by LTCatt** [comment]
@00ll00 把文件名后面的版本号删了，每次都强制重新释放……？

**Comment by ZeroWolf233** [comment]
确实可以在每次启动的时候检测到有旧版本然后就把旧版本的删了

**Comment by 00ll00** [comment]
强制重新释放可能会由于老版本文件被正在运行的其他程序占用而失败（以前遇到过这种情况才改成现在这样的）；同理删除老版本文件也有这个问题。

由于 jlw 释放 dll 的路径是系统的临时文件目录或是用户调用时指定的临时文件目录，这个目录应该由系统或用户进行清理。因此建议由 PCL 的清理垃圾文件功能实现。

**Comment by LTCatt** [comment]
temp 文件夹本来就会被清理，那不管了（

**Comment by JingHai-Lingyun** [comment]
忽然看回到了这个 Issue
它释放在了我的 PCL 文件夹里……

<details>
<summary>图片</summary>

![image](https://github.com/user-attachments/assets/4d4819e7-304a-417d-b122-cc1dd3bcfa5c)

</details>

**Comment by LTCatt** [comment]
如果缓存文件夹释放失败就会释放到 PCL 文件夹作为 fallback（
