### ISSUE TITLE
自定义主页在改变PCL窗口大小时可能崩溃

### ISSUE THREAD

**Issue by StarlightGlimmer43** [Hex-Dragon/PCL2#4536]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

加载本地主页文件时如改变PCL窗口宽度会导致主页无法折叠的按钮（MyCard卡片中CanSwap为False的按钮）消失，但MyCard卡片中CanSwap为True的按钮与MyCard卡片不会消失。

### 重现步骤

预设：先将Custom.zip解压并放入PCL文件夹
1、点击设置
2、点击个性化
3、往下滚，然后点击主页中的”读取本地文件“
4、点击刷新文件
5、点击标题栏中的启动
6、等待1000ms
7、拖动启动器右侧边框
8、出现Bug

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16647739/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16647740/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16647741/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16647742/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16647743/Log5.txt）
[Custom.zip](https://github.com/user-attachments/files/16647746/Custom.zip)

**Comment by JingHai-Lingyun** [comment]
稍等，有个问题，按照你的描述，为什么给按钮设置 CanSwap 属性
另请重新上传你的 Custom.zip，此文件无法下载

**Comment by Deep-Dark-Forest** [comment]
超时关闭。
