### ISSUE TITLE
将热力集成识别为热力运输

### ISSUE THREAD

**Issue by Rhaaaaaast1** [Hex-Dragon/PCL2#4537]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/user-attachments/assets/1356a25a-cc11-4f03-b477-4c4ce01d9535)

### 重现步骤

1、点击xxxx
2、往下滚，然后点击xxxx
1

### 日志与附件

1

**Comment by wuliaodexiaoluo** [comment]
请提供日志

**Comment by SALTWOOD** [comment]
提供日志

**Comment by hejiehao** [comment]
当我点击下面的截图里的 `转到 Modrinth` 之后跳转到了 [Thermal Integration](https://modrinth.com/mod/thermal-integration)
<details><summary>截图</summary>
<p>

![image](https://github.com/user-attachments/assets/2ad3ff67-7374-4a8b-aa92-6612074aebd9)

</p>
</details>

**Comment by wuliaodexiaoluo** [comment]
@3gf8jv4dv 
When the information provided by the Author is not enough to determine the problem (for example, there is no log or the problem does not appear in the log), the label should be added to `等待反馈者`  instead of `等待确认`.

**Comment by wuliaodexiaoluo** [comment]
已确认 ModData 存在问题

修复 PR：#4540

**Comment by wuliaodexiaoluo** [comment]
>@wuliaodexiaoluo
>That label was added because it happened on my end. Maybe next time I should add some instructions.

If it can be reproduced, you can send the log instead of Author and added it to `等待确认`.
Some bugs may not be reproduced by everyone. If the developer does not have a log, the label will still be changed to `等待反馈者`.
