### ISSUE TITLE
local:MyIconTextButton元素ColorType改为Highlight后无变化

### ISSUE THREAD

**Issue by MFn233** [Hex-Dragon/PCL2#4538]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我知道 https://github.com/Hex-Dragon/PCL2/issues/2695 中有 ColorType 没法加的错误，但是现在能加了又不能用了

龙猫的教程页面显示的：
![image](https://github.com/user-attachments/assets/42690ad1-7830-41f4-a9ce-0b0fb90179db)

而源文件中写的：
![image](https://github.com/user-attachments/assets/c860137e-eb5a-45cf-a91e-7b853b96cecf)

对照组：
![image](https://github.com/user-attachments/assets/21bdc05d-ad5b-4fff-9ee9-1309512803e2)
![image](https://github.com/user-attachments/assets/0390e007-3f13-43af-88e3-11fc3cd39ede)

### 重现步骤

在Custom.xaml中编写如下内容：

```xaml
<local:MyIconTextButton Margin="0,5,0,6" Height="35"
    Text="高亮"
    LogoScale="0.8" ColorType="Highlight"
    Logo="M13.5,4A1.5,1.5 0 0,0 12,5.5A1.5,1.5 0 0,0 13.5,7A1.5,1.5 0 0,0 15,5.5A1.5,1.5 0 0,0 13.5,4M13.14,8.77C11.95,8.87 8.7,11.46 8.7,11.46C8.5,11.61 8.56,11.6 8.72,11.88C8.88,12.15 8.86,12.17 9.05,12.04C9.25,11.91 9.58,11.7 10.13,11.36C12.25,10 10.47,13.14 9.56,18.43C9.2,21.05 11.56,19.7 12.17,19.3C12.77,18.91 14.38,17.8 14.54,17.69C14.76,17.54 14.6,17.42 14.43,17.17C14.31,17 14.19,17.12 14.19,17.12C13.54,17.55 12.35,18.45 12.19,17.88C12,17.31 13.22,13.4 13.89,10.71C14,10.07 14.3,8.67 13.14,8.77Z" />
<local:MyIconTextButton Margin="0,5,0,6" Height="35"
    Text="无高亮"
    LogoScale="0.8"
    Logo="M13.5,4A1.5,1.5 0 0,0 12,5.5A1.5,1.5 0 0,0 13.5,7A1.5,1.5 0 0,0 15,5.5A1.5,1.5 0 0,0 13.5,4M13.14,8.77C11.95,8.87 8.7,11.46 8.7,11.46C8.5,11.61 8.56,11.6 8.72,11.88C8.88,12.15 8.86,12.17 9.05,12.04C9.25,11.91 9.58,11.7 10.13,11.36C12.25,10 10.47,13.14 9.56,18.43C9.2,21.05 11.56,19.7 12.17,19.3C12.77,18.91 14.38,17.8 14.54,17.69C14.76,17.54 14.6,17.42 14.43,17.17C14.31,17 14.19,17.12 14.19,17.12C13.54,17.55 12.35,18.45 12.19,17.88C12,17.31 13.22,13.4 13.89,10.71C14,10.07 14.3,8.67 13.14,8.77Z" />

```

正确加载Custom.xaml，出现：

![image](https://github.com/user-attachments/assets/2422d0ab-c15b-4b2e-9215-c8dc91c68d4b)

（长得一模一样）

### 日志与附件

无

**Comment by JingHai-Lingyun** [comment]
嘶…… 看了眼底层是强制使用一种颜色

**Comment by LTCatt** [comment]
额，其实是有一点点不一样的……
![image](https://github.com/user-attachments/assets/2422d0ab-c15b-4b2e-9215-c8dc91c68d4b)
你看下面的是不是蓝了一点点…………

新版本我把差异改得更明显了 Orz
