### ISSUE TITLE
regedit导入成功之后pcl识别不了解锁码

### ISSUE THREAD

**Issue by wuwenjun9939** [Hex-Dragon/PCL2#4539]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/user-attachments/assets/f8e97105-c7ed-4f3e-8c72-f8fb281f3327)
![image](https://github.com/user-attachments/assets/bd42caae-c814-40be-8630-b8a948087b5e)
![image](https://github.com/user-attachments/assets/172f21c4-b644-4d94-a3c5-839bff827685)

### 重现步骤

把pcl备份注册表，然后系统重装之后，导入

### 日志与附件

这个还有日志吗？

**Comment by Ad-closeNN** [comment]
因为你重装了所以导致识别码改变了

**Comment by wuwenjun9939** [comment]
> 因为你重装了所以导致识别码改变了

但是，我导入原始注册表了，这都不行吗？

**Comment by Ad-closeNN** [comment]
> > 因为你重装了所以导致识别码改变了
> 
> 但是，我导入原始注册表了，这都不行吗？

不行，导入的设置仅仅是PCL的设置（包括窗口标题之类的）

**Comment by wuliaodexiaoluo** [comment]
根据图片，你应该是少复制了或者多复制了，可以重新复制一下

>因为你重装了所以导致识别码改变了

>但是，我导入原始注册表了，这都不行吗？

没有更换计算机关键硬件的情况下，使用注册表可以恢复到原来的识别码，如果你在解锁活跃橙后备份了，导入注册表也可以恢复活跃橙

**Comment by Silverteal** [comment]
事实情况是，PCL问的是更新密钥，而你填写的是解锁码……
你的活跃橙解锁码应该还可以继续使用。
