### ISSUE TITLE
PCL2在Windows 7上停止运行

### ISSUE THREAD

**Issue by ZmdNotFound** [Hex-Dragon/PCL2#4542]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

（这是我一个朋友提供的bug，他不会访问github...）

在Windows 7上运行PCL2时，弹窗“Plain Craft Launcher 启动器 已停止工作”。电脑已经安装了.NET库。
![bug](https://github.com/user-attachments/assets/8acf30ff-2609-40c1-8d00-00f43a4aca07)

### 重现步骤

在一台Windows 7电脑上运行PCL2。
不一定能复现，但是出现该问题的电脑就一定能每次触发。

### 日志与附件

由于主程序未能启动，没有可提供的日志文件。

**Comment by wuyuncheng-26** [comment]
啥日志都没有。。。
可能很难分析故障原因

**Comment by wuyuncheng-26** [comment]
况且龙猫似乎说过 Win10 以下版本出现的故障不会修复吧
我查查看看有没有

**Comment by Pigeon0v0** [comment]
你**一定**没装 .NET Framework 4.6.2 或以上

**Comment by ZmdNotFound** [comment]
> 你**一定**没装 .NET Framework 4.6.2 或以上

感谢🙏 解决了
