### ISSUE TITLE
错误地将 %APPDATA% 中的 Java 识别为特定路径下的 Java

### ISSUE THREAD

**Issue by pggyoo** [Hex-Dragon/PCL2#4543]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

启动远古版本1.0后物品栏呈黑色，无法确认手持物品

### 重现步骤

1、下载远古版本1.0
2、正版登录
3. 生存模式下，物品栏呈黑色，创造模式下物品栏方块呈单色（物品栏空余区呈黑色）

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16650447/Log1.txt)

**Comment by AptS-1547** [comment]
这边看起来没有任何问题，可能是电脑导致的……？
<img width="1280" alt="image" src="https://github.com/user-attachments/assets/772d8328-16d2-42af-8345-474cd73e1780">
另外问问是远古版本b1.0还是正式版1.0，两个版本均在本设备上测试过无法复现

**Comment by ZeroWolf233** [comment]
1.0应该不算远古版本，算是正式版本罢

**Comment by ZeroWolf233** [comment]
![image](https://github.com/user-attachments/assets/35f22d4d-f118-48cf-aa54-117e79681591)
这个bug在我的电脑上也没有复现，初步怀疑为您电脑的显示问题，可以检查一下您的电脑在其他方面的显示
~~实在不行重启试试~~
从启动器的log看也没有啥异常

**Comment by wuliaodexiaoluo** [comment]
>[00:49:56.496] [Minecraft] 发现重复的支持库：[Native] 152 K | C:\Users\Great cake\AppData\Roaming\.minecraft\libraries\net\java\jinput\jinput-platform\2.0.5\jinput-platform-2.0.5-natives-windows.jar (2.0.5) 与 [Native] 152 K | C:\Users\Great cake\AppData\Roaming\.minecraft\libraries\net\java\jinput\jinput-platform\2.0.5\jinput-platform-2.0.5-natives-windows.jar (2.0.5)，已忽略其中之一

不知道是不是这个原因，但这两个所谓的重复文件其实是同一个文件？
<details>
<summary>不太可能的原因</summary>
不清楚是不是因为错误判断导致漏解压了
![image](https://github.com/user-attachments/assets/693922dd-3dbf-44df-9778-0d140f2e6aab)
</details>


>[00:49:56.706] [Java] 优先使用特定路径下的 Java：JRE 8 (8.0.202)：C:\Users\Great cake\AppData\Roaming\Badlion Client\Data\jre1.8.0_202\bin\

>[00:49:56.706] [Java]  - JRE 8 (8.0.51)：C:\Users\Great cake\AppData\Roaming\.minecraft\runtime\jre-legacy\bin\

这是软件 Java吗，如果是的话可以试试换成下面这个，如果还是不行建议更新下显卡驱动

**Comment by LTCatt** [comment]
`[00:49:56.706] [Java] 优先使用特定路径下的 Java：JRE 8 (8.0.202)：C:\Users\Great cake\AppData\Roaming\Badlion Client\Data\jre1.8.0_202\bin\`

这个不应该被识别为特定路径，这是个 bug……
至于楼主的问题应该不是启动器导致的 =。=

**Comment by wuliaodexiaoluo** [comment]
机器人一定是挂了吧（刷下 WebHook
