### ISSUE TITLE
版本隔离选项由（关闭）改为（隔离所有版本后）存档消失

### ISSUE THREAD

**Issue by pggyoo** [Hex-Dragon/PCL2#4544]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

版本隔离选项由（关闭）改为（隔离所有版本）后存档消失，再改回（关闭）后存档恢复显示
希望在修改选项后，在各个版本原版本存档正常显示，无需转移存档

### 重现步骤

1、下载pcl2启动器中任意版本（多个）,版本隔离选项为（关闭）
2、在各个版本中创建任意存档，关闭游戏
3.   版本隔离选项由（关闭）改为（隔离所有版本）
4.  重进游戏，存档消失（本人亲测，hmcl启动器未出现类似事件）

### 日志与附件

[Log2.txt](https://github.com/user-attachments/files/16650545/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16650546/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16650547/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16650548/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/16650549/Log1.txt)

**Comment by JingHai-Lingyun** [comment]
HMCL 貌似是会自动迁移客户端实例中会受 `版本隔离配置` 影响的文件和文件夹，但是我认为这样反而会在一个目录下有多客户端实例的时候造成混乱。
给龙漫看看怎么说……

**Comment by LTCatt** [comment]
这是预期的情况，并且如上所说……是这样的，不好改。
