### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by lkanke** [Hex-Dragon/PCL2#4545]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

一、2.8.3版本选择自动选取java 游戏版本是1.20 有时会选取java17 导致进不去游戏 发生过两次
二、更新pcl出错

### 重现步骤

1、点击xxxx
2、往下滚，然后点击xxxx

### 日志与附件

[Log3.txt](https://github.com/user-attachments/files/16651023/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16651024/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16651025/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/16651026/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16651028/Log2.txt)

**Comment by lkanke** [comment]
更新pcl时提示找不到pcl的程序

**Comment by lkanke** [comment]
emmmmm赞助前没有这样的情况，电脑是联想的笔记本，可能是我的联想管家搞的吧

**Comment by lkanke** [comment]
确实是Windows Defender的提示，但我的电脑的Windows Defender是Lenovo Anti-Virus powered by Huorong Security接管的，确实是赞助后更新快照版才出现的

**Comment by lkanke** [comment]
已经加在白名单了

**Comment by JingHai-Lingyun** [comment]
> 2.8.3版本选择自动选取java 游戏版本是1.20 有时会选取java17 导致进不去游戏 发生过两次

1.20 理论上可以通过 Java 17 启动，如果你确认这是 Bug，请上传崩溃日志

---

另一问题已由另一位社区协作者解答

请注意，不要短时间内发送多条短信息，如果你想要补充你上一句说的话，请使用 Edit 功能
该功能位于你的信息右上角 `···` 菜单中

**Comment by JingHai-Lingyun** [comment]
What？！1.21…… Oh it will cause crash.
Java 21 support begin at v2.7.0, i think this bug wont be fixed.

**Comment by lkanke** [comment]
emmmm因为我玩的版本比较多，所以一直开的都是自动选取java，更新pcl的快照版本前自动选取是没有问题的，更新后才出现了这个问题。

**Comment by lkanke** [comment]
识别码要求解锁

**Comment by lkanke** [comment]
就是活跃橙
