### ISSUE TITLE
将活跃橙的解锁码获取方式迁移/增加到爱发电

### ISSUE THREAD

**Issue by Chormore-EDGE** [Hex-Dragon/PCL2#4548]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

单纯增加一种获取识别码的方式，~上github还得挂加速器有点麻烦（）~考虑一下是否可以把活跃橙的识别码获取方式增加到爱发电，方便了一点点

### 原因

![Uploading 0f0142267f3dd30da89f04980a37e606_3627697594519893778.jpg…]()

**Comment by JingHai-Lingyun** [comment]
图没发上来，另外如何验证你的 GitHub 身份呢……

**Comment by Silverteal** [comment]
描述不清，可能指补发活跃橙

**Comment by Chormore-EDGE** [comment]
> 描述不清，可能指补发活跃橙

额...我是指在爱发电增加获取活跃橙的方法，类似于发送"更新"自动发送更新秘钥那种

**Comment by Silverteal** [comment]
你要的是解锁码还是识别码？

**Comment by Chormore-EDGE** [comment]
> 你要的是解锁码还是识别码？

~抱歉抱歉把解锁码错认成识别码了~，已经修改标题

**Comment by Ad-closeNN** [comment]
所以，怎么验证你是那条issue的author呢

**Comment by Silverteal** [comment]
活跃橙只有提交在源码库或帮助库有效的 Issue 或者 Pull Request 后才能获取，爱发电获取不是增加工作量吗

**Comment by Chormore-EDGE** [comment]
> 活跃橙只有提交在源码库或帮助库有效的 Issue 或者 Pull Request 后才能获取，爱发电获取不是增加工作量吗

有道理（关了）

**Comment by Chormore-EDGE** [comment]
.
