### ISSUE TITLE
PCL 在删除含有（或者安装过）低于1.5.2版本的文件夹的时候出现：未能找到路径“.minecraft\resources”的一部分

### ISSUE THREAD

**Issue by AptS-1547** [Hex-Dragon/PCL2#4549]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

1.0版本的安装会先创建一个链接文件夹：`./.minecraft/resources` 链接到 `./.minecraft\assets\virtual\legacy`
在删除游戏版本文件夹的时候，PCL会先删除 `assets` 和 `libraries` 文件夹
而后删除 `resources` 就会找不到原来的文件夹而报错

可以改为先删除 `resources` 后删除其他的

最高受影响mc版本：1.5.2
最低受影响mc版本：未知

### 重现步骤

1. 开一个新的 `minecraft` 游戏文件夹
2. 安装1.0版本
3. 在PCL内删除 `minecraft` 游戏文件夹
4. 报错 未能找到路径“.minecraft\resources”的一部分

### 日志与附件

![image](https://github.com/user-attachments/assets/8e232f45-da91-4f81-b01c-99f6e6bcfc86)
![image](https://github.com/user-attachments/assets/6ad83c86-adaa-4140-97e1-27ef243f7477)
--------------------------------
[Log1.txt](https://github.com/user-attachments/files/16657228/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16657229/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16657231/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16657225/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16657227/Log5.txt)

**Comment by AptS-1547** [comment]
~~HMCL就没这个问题了因为他们根本没有删除游戏文件夹功能XD~~

**Comment by Ad-closeNN** [comment]
复现成功
[Log1.txt](https://github.com/user-attachments/files/16657395/Log1.txt)

**Comment by AptS-1547** [comment]
> 复现成功 [Log1.txt](https://github.com/user-attachments/files/16657395/Log1.txt)
> 
> 还有这里为什么会有两个取消啊（ ![image](https://private-user-images.githubusercontent.com/103355026/359026445-9d60ef29-71bb-46ff-af05-c7dc3d9b37f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNTQ4NjQsIm5iZiI6MTcyNDA1NDU2NCwicGF0aCI6Ii8xMDMzNTUwMjYvMzU5MDI2NDQ1LTlkNjBlZjI5LTcxYmItNDZmZi1hZjA1LWM3ZGMzZDliMzdmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOVQwODAyNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZGVlOWI1NDA2YmQ2NTZmZjAwOGZmM2RlNTBhYTI0YTYwOGVmYzgwMGQzMWNjMzk3MTllNzA1ZjVlMmFjOTY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JIaNlUMoXRVfF79MUcRf8g3cKs5m-0gpKAsYajINHbE)

防止乱删.jpg

**Comment by Chormore-EDGE** [comment]
> 复现成功 [Log1.txt](https://github.com/user-attachments/files/16657395/Log1.txt)

+1
![image](https://github.com/user-attachments/assets/99178f80-ad8a-4708-b539-3fff5c654daf)
~之前上传不上去图片竟然是我没开加速器~

**Comment by AptS-1547** [comment]
还有一个小BUG：PCL2在下载的时候是会把1.0识别为正式版的
但是在选择版本中会显示为远古版
刚刚测试到1.3.1也会这样（

**Comment by AptS-1547** [comment]
> 我发现了一个不知道是不是bug，下载mc过程中调试模式显示复制已存在的文件失败，~但是最后安装成功了就很怪~这个提示占满了我整个pcl屏幕 ![image](https://private-user-images.githubusercontent.com/114737601/359032783-e8b826ea-aa6e-4f3a-a066-7eaef0f3b001.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNTYxNTMsIm5iZiI6MTcyNDA1NTg1MywicGF0aCI6Ii8xMTQ3Mzc2MDEvMzU5MDMyNzgzLWU4YjgyNmVhLWFhNmUtNGYzYS1hMDY2LTdlYWVmMGYzYjAwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOVQwODI0MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NzlhM2E3NzQ3MDQ5NDU2MmE5MThjZThiY2Q1ZjkzN2QwOTUzMzg4OGJhYmVjOTc2OWJiODA5ODdmOGJjNWMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Iy2k6AuumefD7QnyoW-uU6lCHyAqd_-Gh7CHFpPjshc) ~而没有任何进程占用这个文件，后面在安装其他版本的时候就好好的了~

可以开新的issue捏~（

**Comment by Deep-Dark-Forest** [comment]
> 复现成功
> [Log1.txt](https://github.com/user-attachments/files/16657395/Log1.txt)
> 
> 还有这里为什么会有两个取消啊（俩效果一样的
> ![image](https://github.com/user-attachments/assets/9d60ef29-71bb-46ff-af05-c7dc3d9b37f8)
> 

https://github.com/Hex-Dragon/PCL2/issues/1436

**Comment by wuliaodexiaoluo** [comment]
>PCL 在删除含有（或者安装过）低于 1.5.2 版本的文件夹的时候出现：未能找到路径“.minecraft\resources”的一部分

实际上如果跟我想的没有出入的话，PCL 应该是先把 assets 文件夹删了，然后在删除 resources 时，因为文件系统符号链接会把文件操作重定向到指定目录，所以删 resources 就相当于删 assets\virtual\legacy，但问题是 assets 文件夹已经被扬了，所以文件系统找不到文件直接丢了个 FileNotFound，然后导致了此 Bug
实际上修复此问题在理论上比较简单，只需要识别为 resources 时使用 DeleteFile 方法就可以删掉这个符号链接

**Comment by wuliaodexiaoluo** [comment]
![image](https://github.com/user-attachments/assets/2f13581b-961b-4dbd-a70a-8c7c1f8ad6b0)
由于 GetFiles 不支持设置选项来忽略某某文件，这玩意基本接近无解，除非扫之前先把 Symbol Link 删了

**Comment by AptS-1547** [comment]
识别码：704C-9845-1E6B-E628
龙猫大大幸苦了！

**Comment by LTCatt** [comment]
你的解锁码：aC0ht4T1yGRPZ38tJgiiYkRB9sENW/J8
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
