### ISSUE TITLE
模态弹窗弹出时覆盖层/弹窗标题意外的可以拖动窗体

### ISSUE THREAD

**Issue by JingHai-Lingyun** [Hex-Dragon/PCL2#4552]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如题

### 重现步骤

弹个窗，然后尝试按住模态覆盖层或弹窗标题，拖动观察

**Comment by LTCatt** [comment]
这是预期行为吧……？

**Comment by JingHai-Lingyun** [comment]
这很奇怪……
因为按理来说模态弹窗的时候是不能操作模态层以下的元素的，PCL 的 Drag 元素是头栏，头栏在模态层以下

**Comment by LTCatt** [comment]
这是特意加的处理，防止弹窗的时候没法拖动了 =。=

**Comment by JingHai-Lingyun** [comment]
行吧
