### ISSUE TITLE
即使按照教程去做依然没有改变

### ISSUE THREAD

**Issue by unlimitedares** [Hex-Dragon/PCL2#4553]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我的问题是在登录微软账户的时候出现了出现错误请重试，我也确实找到了帮助，但是没有用。我即使完成了所有操作，依然无法正常进入，提示还是出现错误请重试。

### 重现步骤

启动整合包时进入浏览器加载，100%触发这个问题。

### 日志与附件

这应该和日志没什么关系吧。

**Comment by Ad-closeNN** [comment]
> 出现错误请重试

方便截个错误代码那边的图吗
或者过几分钟试试，微软的服务器是这样的

**Comment by Mxmilu666** [comment]
1.请使用简洁明了的描述并且附带图片来反馈，我现在有点看不懂你描述的内容
2.如果登不上账号，请检查您的网络环境和是否购买了我的世界正版
感谢

**Comment by JingHai-Lingyun** [comment]
尝试使用加速器或 VPN，或过几分钟再尝试，微软的服务不是很稳定
这应当不是 PCL 的问题，如果仍然无法登录，请上传错误截图

**Comment by hejiehao** [comment]
> 这应该和日志没什么关系吧。

确实有点关系

**Comment by wuyuncheng-26** [comment]
您可以提供一下截图和日志吗，以便我们分析（

**Comment by wuliaodexiaoluo** [comment]
>出现错误请重试

请尝试在不挂代理的情况下再试一次，此问题可能为代理与服务器交互时出现问题（连接被重置，服务器拒绝响应等等）

**Comment by bmmNbhjd** [comment]
一般来说，PCL2无法干预也无法解决

**Comment by Deep-Dark-Forest** [comment]
超时关闭。
