### ISSUE TITLE
小愿望

### ISSUE THREAD

**Issue by f1amingQAQ** [Hex-Dragon/PCL2#4554]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

希望能将主页预设的一些功能整合进自定义功能中（如回声洞）；希望标题栏文字能够支持更多不同字体

### 原因

可以提高PCL的自定义程度

**Comment by hejiehao** [comment]
> 希望标题栏文字能够支持更多不同字体

https://github.com/Hex-Dragon/PCL2/issues/366

**Comment by tangge233** [comment]
不太理解你说的 `自定义功能` 指的是什么

**Comment by JingHai-Lingyun** [comment]
请详细描述您所称的 `自定义功能`

**Comment by SALTWOOD** [comment]
请尽可能详细描述你希望的功能/改进，不然让龙猫很难办……

**Comment by wuliaodexiaoluo** [comment]
>希望能将主页预设的一些功能整合进自定义功能中（如回声洞）

回声洞、自定义主题属于赞助者专有内容，不予考虑

>主页预设

主页预设需要投稿，可以使用联网更新替代

<details>
<summary>以下是可能涉及自定义功能的 Issue</summary>

> 兼容黑暗模式

#131

>自定义主题使用 RGB 等参数设定颜色

#401 

>为自定义主题设置自动变色

#562 

> 自带或允许打包主题音乐

#711

>图标跟随主题颜色变换

#791 

> 标题栏允许使用文本+图片混合

#840 

>增加隐藏主题

#1242 

>透明背景

#1653 

>支持自定义背景颜色/背景颜色渐变

#1487

>毛玻璃/模糊背景

#2216 

>允许玩家自定义/投稿主题

#3202 

</details>

**Comment by f1amingQAQ** [comment]
我的意思是希望能将主页预设的一些模块（如回声洞，你知道吗）作为一种模块允许玩家在本地文件“Custom.xaml”中进行修改添加，否则主页上只有这一个小小的模块显得很单调。

**Comment by tangge233** [comment]
![image](https://github.com/user-attachments/assets/1bd0c0db-7faa-476c-a9a4-42651e2b3cb9)

**Comment by tangge233** [comment]
![image](https://github.com/user-attachments/assets/69a24014-6541-474c-8de0-a279de472a28)

**Comment by wuliaodexiaoluo** [comment]
>我的意思是希望能将主页预设的一些模块（如回声洞，你知道吗）作为一种模块允许玩家在本地文件“Custom.xaml”中进行修改添加，否则主页上只有这一个小小的模块显得很单调。

照着教程去自己 DIY 一个谢谢
