### ISSUE TITLE
卡片展开动画回弹异常

### ISSUE THREAD

**Issue by chestnut-the** [Hex-Dragon/PCL2#4557]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

回弹动画异常

### 重现步骤

1、打开任意界面，要求卡片展开后高度大于窗口高度，图例为更多-帮助-百科/个性化
2、展开卡片并划至底部
3、关闭卡片再打开会发现动画异常

### 日志与附件

![PixPin_2024-08-20_15-37-58](https://github.com/user-attachments/assets/4f8f78ba-66db-428b-9aec-6496a4186e66)
![PixPin_2024-08-20_15-44-24](https://github.com/user-attachments/assets/af06ccb2-5299-4a06-9552-b6288ed5da44)

**Comment by bmmNbhjd** [comment]
感觉影响不大……
应该是说第一次展开卡片时不会让页面移动，但是滑倒最底下收起再展开会移动

**Comment by chestnut-the** [comment]
> 感觉影响不大…… 应该是说第一次展开卡片时不会让页面移动，但是滑倒最底下收起再展开会移动

之前PCL内置反馈的时候提过一次说会修 不过就没后文了

**Comment by wuliaodexiaoluo** [comment]
瞎检索了一番，好像没发现重复的？

**Comment by LTCatt** [comment]
这是因为滚动条滚到最下面的时候它会强制一直置于底部，不太好修，算了 =。=

**Comment by chestnut-the** [comment]
@LTCatt 
![recording](https://github.com/user-attachments/assets/036519a1-b1f9-4b94-85de-553f6394ea9e)
这个也是一样的原因吗

**Comment by chestnut-the** [comment]
![PixPin_2024-08-22_10-07-06](https://github.com/user-attachments/assets/fcc6ec1c-4fcb-4c69-9a94-3afc8fb71616)
@LTCatt 这个也是一样的原因吗

**Comment by wuliaodexiaoluo** [comment]
>这个也是一样的原因吗

请勿在已关闭的 Issue 内回复无效内容，也请不要随便@龙猫

**Comment by LTCatt** [comment]
是同样的原因。
这个不是无效内容，不要太在意了 =。=
