### ISSUE TITLE
删除Mod时同时删除不用的Mod储存的文件

### ISSUE THREAD

**Issue by IKUNKunCaixu** [Hex-Dragon/PCL2#4559]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

部分mod如xearo的世界地图或distance horizons会在本地留下大量文件，不用时还需定位手动删除这些文件。对于找不到的文件还会占用一些内存。

### 原因

对于想要将版本打包或下载打包好的版本的玩家来说这样不会占用更多时间

**Comment by bmmNbhjd** [comment]
好像没有特别声明数据存储位置……

**Comment by hejiehao** [comment]
怎么知道这些 Mod 的配置文件在哪里？

**Comment by JingHai-Lingyun** [comment]
Mod 的配置会以以下多种方式出现
- 以 Mod 名为名的文件夹
- 以 Mod 名为名的文件，其中可能是：
  - `.cfg` 结尾
  - `.json` 结尾
  - `.json5` 结尾

未找到类似反馈，但正如楼上所说，貌似无法确认 Mod 以什么方式存储配置文件

**Comment by SALTWOOD** [comment]
没有办法确认是哪些模组留下的文件
并且如果更新模组或者是手动安装新版本模组，还可能导致数据被误删除
在乎或者知道要去清理这些文件的自然会去清理。，总之就是没啥用

**Comment by LTCatt** [comment]
技术上无法实现
