### ISSUE TITLE
显示的不兼容当前使用的JAVA，重装JAVA成功启动一次之后还是提示 “Minecraft 出现错误”

### ISSUE THREAD

**Issue by mayikeGitHub** [Hex-Dragon/PCL2#4560]
### 检查项

- [ ] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃基本不是 PCL 的原因，请 **不要** 提交反馈。你可以在论坛或社区找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用 HMCL 启动，HMCL 没有出现问题。** 如果 HMCL 也无法启动就不是 PCL 导致的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

<img width="577" alt="1" src="https://github.com/user-attachments/assets/67a6c57b-01a4-412e-9cdf-1bdb836c51bc">

### PCL 错误报告、日志与附件

[Log1.txt](https://github.com/user-attachments/files/16687617/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16687619/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16687621/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16687623/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16687626/Log5.txt)

**Comment by bmmNbhjd** [comment]
先给错误报告

**Comment by bmmNbhjd** [comment]
```
[15:01:09.752] [Java] 优先使用特定路径下的 Java：JDK 21 (21.0.2)：C:\Users\马一可\AppData\Roaming\Badlion Client\Data\jdk-21.0.2\bin\
```

**Comment by mayikeGitHub** [comment]
错误报告:
[错误报告-2024-8-21_15.44.22.zip](https://github.com/user-attachments/files/16687879/-2024-8-21_15.44.22.zip)

**Comment by LTCatt** [comment]
#4543
