### ISSUE TITLE
下载不了生存测试

### ISSUE THREAD

**Issue by lvchong123** [Hex-Dragon/PCL2#4568]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

想下载下载不了，弹出
开始合并安装失败:从字符串“30_生存测试“到类型“Integer”的转换无效。
→输入字符串的格式不正确。
在PCL.ModDownloadLib.McInstallLoader(McInstallRequest Request, Boolean
DontFixLibraries)
在PCL.ModDownloadLib.McInstall(McInstallRequest Request)
错误类型:System.FormatException

### 重现步骤

下载生存测试

### 日志与附件

[Log5.txt](https://github.com/user-attachments/files/16708839/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/16708840/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16708841/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16708843/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16708844/Log4.txt)

**Comment by bmmNbhjd** [comment]
#4528
