### ISSUE TITLE
皮肤头像显示异常

### ISSUE THREAD

**Issue by Tr4velt0Here** [Hex-Dragon/PCL2#457]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

选择该皮肤时，在游戏中显示正常，在启动器中显示异常
![2022-11-27_09 30 44](https://user-images.githubusercontent.com/87561321/204115288-450f9876-97a7-4196-8524-5d2db5243f83.png)
![image](https://user-images.githubusercontent.com/87561321/204115303-fe0842f4-465f-4adf-ba38-9c3ee51ad571.png)

### 重现步骤

1、更换此皮肤即可
![--s-h-o-r-t---t-e-m-p-e-r-e-d---20134664](https://user-images.githubusercontent.com/87561321/204115320-eb49ae86-97f4-40c8-b526-b954c35ba574.png)

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10097332/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10097333/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10097334/Log3.txt)

**Comment by WForst-Breeze** [comment]
貌似并非PCL2的问题，您的皮肤底色是白色而非透明色。本人经测试在游戏中也无法正常显示该皮肤，具体您在游戏里为何显示正常这我不太清楚qwq……
![8b4fc949d742815a1c40a12cd2b8c2b](https://user-images.githubusercontent.com/110760354/204116148-92b74b34-8e1a-4591-a2e7-9b1a1195124d.png)

**Comment by Tr4velt0Here** [comment]
> 貌似并非PCL2的问题，您的皮肤底色是白色而非透明色。本人经测试在游戏中也无法正常显示该皮肤，具体您在游戏里为何显示正常这我不太清楚qwq…… ![8b4fc949d742815a1c40a12cd2b8c2b](https://user-images.githubusercontent.com/110760354/204116148-92b74b34-8e1a-4591-a2e7-9b1a1195124d.png)

懂了，感谢
