### ISSUE TITLE
下载 Mod 时 PCL2 偶然会错误的判断 Mod 所对应的 MC 版本

### ISSUE THREAD

**Issue by RimacC2-EV** [Hex-Dragon/PCL2#4571]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

下载 Mod 时 PCL2 偶然会错误的判断 Mod 所对应的 MC 版本。

在这个例子中，我尝试下载 ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric ，对应 MC 版本 1.20.1，但弹出的“下载”对话框 错误地指向 1.20.6

![image](https://github.com/user-attachments/assets/d5c9f0f1-7cb3-423e-9f96-278a37be5bbd)
![image](https://github.com/user-attachments/assets/8508135c-03e2-4bf6-9c36-fbdbe8320eac)

### 重现步骤

1、在 下载 列表 打开 “Mod” ，
2、搜索 Forge Config API Port 
3、找到 1.20.1 
4、尝试下载（如果可以，请预下载 1.20.6）
5、该问题应该会出现。

### 日志与附件

[Log3.txt](https://github.com/user-attachments/files/16721821/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16721822/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16721823/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/16721824/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16721825/Log2.txt)

**Comment by RimacC2-EV** [comment]
在这个例子中，PCL 版本为 2.8.3，HMCL 版本为 Dev 3.5.8.251

**Comment by bmmNbhjd** [comment]
因为部分 Mod 对其他小版本也兼容，所以你没有 1.20.1 就自动给你换到 1.20.6 喽

**Comment by bmmNbhjd** [comment]
#691

**Comment by JingHai-Lingyun** [comment]
虽然 fabric.mod.json 里确实标注了只支持 Minecraft 1.20.1
```json,diff
 "depends": {
     "fabricloader": ">=0.14.21",
     "fabric-api": ">=0.83.0",
!    "minecraft": "1.20.1",
     "java": ">=17"
   },
```
但同 #691，如有需要去那边下面回复即可

**Comment by RimacC2-EV** [comment]
<del>我选择了 1.20.1 版本的 Mod，但建议的版本是1.20.6，并且我同时拥有这两个版本</del>

**Comment by bmmNbhjd** [comment]
> <del>我选择了 1.20.1 版本的 Mod，但建议的版本是1.20.6，并且我同时拥有这两个版本</del>

发下版本列表

**Comment by RimacC2-EV** [comment]
兄弟们抱歉，之前突然无法复现，之后一直尝试，迄今为止也无法复现······

还辛苦各位白跑一趟······<del>等下次出Bug之后再讨论罢</del>
