### ISSUE TITLE
回声洞刷新

### ISSUE THREAD

**Issue by 1976llll** [Hex-Dragon/PCL2#4572]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

回声洞刷新有时会重复，建议改成已读过的不再出现

### 原因

这项优化让我可以更方便地看回声洞。
如果没有这项优化，我每次都必须多刷新一下，让操作变得很麻烦。

**Comment by wuyuncheng-26** [comment]
？那万一你哪一天真刷完了你就再也看不了，不是吗
再说这重复的概率很小……
只能说一部分是因为你运气不好了



------------------ 原始邮件 ------------------
发件人: 1976llll ***@***.***&gt;
发送时间: 2024年8月23日 15:26
收件人: Hex-Dragon/PCL2 ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [Hex-Dragon/PCL2] 回声洞刷新 (Issue #4572)





 
检查项
  
 我已在 Issues 页面 和 常见&amp;难检反馈及问题列表 中搜索，确认了这一建议未被提交过。
 
 我已查看 功能投票页面，确认了这一建议未在投票列表中。
  
描述
 
回声洞刷新有时会重复，建议改成已读过的不再出现
 
原因
 
这项优化让我可以更方便地看回声洞。
 如果没有这项优化，我每次都必须多刷新一下，让操作变得很麻烦。

**Comment by Deep-Dark-Forest** [comment]
> ？那万一你哪一天真刷完了你就再也看不了，不是吗

或许可以加一个重置按钮…？没发现有重复的，先给龙猫看看

**Comment by LTCatt** [comment]
意义不大，暂时不会做，抱歉
