### ISSUE TITLE
开始合并安装失败:从字符串“9-pre6"到类型“Integer“的转换无效，

### ISSUE THREAD

**Issue by 1976llll** [Hex-Dragon/PCL2#4573]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我在安装远古版mc考古的时候出来了这个弹窗
![513071DB68A9A0F60DFCA3206EC8173F](https://github.com/user-attachments/assets/c4864a79-6f5b-448c-95a3-a6c36ed60225)

### 重现步骤

1、点击下载
2、往下滚，然后点击远古版b1.9-pre6
3、点击开始安装

### 日志与附件

[Log3.txt](https://github.com/user-attachments/files/16725603/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16725606/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16725608/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/16725609/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16725610/Log2.txt)

**Comment by JingHai-Lingyun** [comment]
与 #4528 同理，请等待下一次更新
