### ISSUE TITLE
错误日志导出不来，关闭重启电脑也没用

### ISSUE THREAD

**Issue by YSSCMM** [Hex-Dragon/PCL2#4575]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![2164d77ddbd9cf17df8a37ef9538e102](https://github.com/user-attachments/assets/180a49c1-3b40-4349-99c5-de5f0ce7815f)

### 重现步骤

1、点击xxxx
2、往下滚，然后点击xxxx

### 日志与附件

.

**Comment by Ad-closeNN** [comment]
#4534

**Comment by JingHai-Lingyun** [comment]
……？
