### ISSUE TITLE
下载forge或补全文件时错误

### ISSUE THREAD

**Issue by yangshuzi-66** [Hex-Dragon/PCL2#4576]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

补全文件或下载整合包时会出现 另：下载mod或其他文件时会先卡在7%许久，再进行下载

### 重现步骤

1、点击对应版本
2、往下滚，然后点击补全文件
1.下载forge

### 日志与附件

![微信图片_20240823195211](https://github.com/user-attachments/assets/a13b18aa-24a5-4d52-9f1a-5d5278b965be)

**Comment by bmmNbhjd** [comment]
你访问下这几个网址搜索？

**Comment by sulingjiang** [comment]
>补全文件

你大概是把 libraries 整个删了，这个没办法补全的

**Comment by hejiehao** [comment]
你是否使用了🪜等工具？

**Comment by sulingjiang** [comment]
403 是节点问题，这个 PCL 解决不了

**Comment by Mxmilu666** [comment]
OpenBMCLAPI 最近因为被攻击封禁了境外 IP，请确保你没有挂梯子请求

**Comment by sulingjiang** [comment]
#3698
