### ISSUE TITLE
当千万别点触发了真·滑稽彩时过一段时间会卡着，然后无法正常关闭

### ISSUE THREAD

**Issue by NootFond** [Hex-Dragon/PCL2#4579]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

启动器无法正常关闭，爆出了一个4级错误（未崩溃），提示：
检查秋仪金失败:未将对象引用设置到对象的实例。
错误类型:System.NullReferenceException
之后点击反馈就卡死了

### 重现步骤

前置：正在更新mod
1.千万别点触发只有彩虹特效的pcl
2.等待一段时间
3.等颜色不闪烁时按关闭按钮
4.出现错误
5.点击反馈后卡死

### 日志与附件

[Log2.txt](https://github.com/user-attachments/files/16731865/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16731866/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16731867/Log4.txt)
![4929426874D5A1D7998D5EFFD7D0CA12](https://github.com/user-attachments/assets/b7217ee5-ad1d-49e1-830a-79790b691ad7)
![88E93C1D91FF5AFEEFA9950129A32890](https://github.com/user-attachments/assets/88142706-cc71-41cb-9635-52df4eb94e09)
![115FCD1764D840C94C0423CBB754F721](https://github.com/user-attachments/assets/eedc92a5-8e1a-4ed0-affe-ee67ede18051)

[Log5.txt](https://github.com/user-attachments/files/16731868/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/16731869/Log1.txt)

**Comment by lactobionicAcid** [comment]
PCL 作者不会受理由于点击千万别点造成的任何 Bug ......

**Comment by NootFond** [comment]
我忘看提示了完了，不好意思

**Comment by wuliaodexiaoluo** [comment]
这个问题实际上是 #4517 
如果能复现的话，你可以带着日志和详细的操作流程去 Issue 下面回复
