### ISSUE TITLE
添加一个主题市场

### ISSUE THREAD

**Issue by WangYiBen0** [Hex-Dragon/PCL2#4582]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

在github上（？）添加一个库，用于投稿自定义主题，并在启动器上添加一个一键导入主题的入口

### 原因

（示例）
我需要这个功能来调整主题。很多人都有copy别人创建的主题的需求，但如果没有这个功能，就不能这么干了。

**Comment by JingHai-Lingyun** [comment]
自定义……主题？您想要描述的是个性化中的 `基础 > 自定义（颜色主题）` 还是 `主页`？

**Comment by WangYiBen0** [comment]
基础 > 自定义（颜色主题）（如果能顺便支持一下主页也行啊）

**Comment by Deep-Dark-Forest** [comment]
https://github.com/Hex-Dragon/PCL2/issues/3202？

**Comment by WangYiBen0** [comment]
> #3202？
那是投稿，这是市场（）
我的意思是添加导入主题的功能（毕竟手动拖条真的是太折磨了，特别对于强迫症）

**Comment by Deep-Dark-Forest** [comment]
是不是可以简单理解成“增加名为‘自定义’的隐藏主题的配置导入/导出功能”（

**Comment by WangYiBen0** [comment]
> 是不是可以简单理解成“增加名为‘自定义’的隐藏主题的配置导入/导出功能”（

我觉得行

**Comment by bmmNbhjd** [comment]
推荐复制 PCL 文件夹下的 Setup.ini

**Comment by allMagicNB** [comment]
#315

**Comment by allMagicNB** [comment]
#1834

**Comment by LTCatt** [comment]
暂时不考虑，抱歉（
