### ISSUE TITLE
将音乐、背景图片等并入主题

### ISSUE THREAD

**Issue by WangYiBen0** [Hex-Dragon/PCL2#4583]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

如题，将诸类美化并入主题。

在【设置\个性化\基础\隐藏主题\自定义】中添加【音乐】【背景图片】等选项

### 原因

这项优化让我可以更方便地更换音乐/图片。
如果没有这项优化，我每次都必须手动更改，让操作变得很麻烦。

**Comment by Deep-Dark-Forest** [comment]
也就多点几下的事，没啥用……
