### ISSUE TITLE
个性化设置 未解锁秋仪金时 右键前往爱发电地址更新

### ISSUE THREAD

**Issue by Nm851104781224** [Hex-Dragon/PCL2#4584]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

因为之前爱发电域名从.net迁移成.com了 然而这个地方的前往爱发电页面尚未进行更新依然为afdian.net 所以右键进入后显然无法进入
![QQ20240824-203733](https://github.com/user-attachments/assets/983c055d-0041-4a99-af09-24c0f0967aee)

### 原因

很小的疏漏 没啥影响
偶然看见就提出来了 :)

**Comment by wuliaodexiaoluo** [comment]
#4532(#4533)
请等待更新

**Comment by Deep-Dark-Forest** [comment]
~~草，我又眼瞎了~~
