### ISSUE TITLE
mod界面选择优化

### ISSUE THREAD

**Issue by WangYiBen0** [Hex-Dragon/PCL2#4586]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

添加【反选】

支持热键的更改

### 原因

这项优化让我可以更方便地执行操作。
如果没有这项优化，我每次都必须一个一个选，让操作变得很麻烦。

**Comment by wuliaodexiaoluo** [comment]
>添加【反选】 

这个所谓的反选是什么意思？

**Comment by Deep-Dark-Forest** [comment]
> >添加【反选】 
> 
> 这个所谓的反选是什么意思？

比如说一共有 ABC 三个模组，我现在选中了 A，使用反选后就会选择 BC

**Comment by hejiehao** [comment]
> > 添加【反选】
> 
> 这个所谓的反选是什么意思？

参考 Windows 文件资源管理器的反向选择

<details><summary>Windows Explorer</summary>
<p>

![image](https://github.com/user-attachments/assets/228c4172-0f03-4a7f-b690-197b9c699b8b)


</p>
</details>

**Comment by WangYiBen0** [comment]
> > > 添加【反选】
> > 
> > 
> > 这个所谓的反选是什么意思？
> 
> 比如说一共有 ABC 三个模组，我现在选中了 A，使用反选后就会选择 BC（大概吧）



> > > 添加【反选】
> > 
> > 
> > 这个所谓的反选是什么意思？
> 
> 参考 Windows 文件资源管理器的反向选择
> 
> Windows Explorer

是的\(^o^)/

**Comment by WangYiBen0** [comment]
> > 添加【反选】
> 
> 这个所谓的反选是什么意思？

取消选择已选内容，选择未选内容

**Comment by wuyuncheng-26** [comment]
嘶哈，我可以理解为 A B C 全选上然后点掉 A 吗
那就不需要单独搞这个反选的功能了（

**Comment by wuliaodexiaoluo** [comment]
>嘶哈，我可以理解为 A B C 全选上然后点掉 A 吗
那就不需要单独搞这个反选的功能了（

Author 可能是想要选择很多不相连的 Mod？并且可能不是少数？

**Comment by WangYiBen0** [comment]
> > 嘶哈，我可以理解为 A B C 全选上然后点掉 A 吗
> > 那就不需要单独搞这个反选的功能了（
> 
> Author 可能是想要选择很多不相连的 Mod？并且可能不是少数？

对啊，比如你搞个生电整合包，里面放了masa全家桶和一堆优化mod，优化mod可能改变特性，所以选masa全家桶之后再反选禁用就很方便啊

**Comment by LTCatt** [comment]
选择之后可以长按拖动来反选。目前暂时没有进一步添加文件选择 QoL 的想法，这不是文件管理器……
