### ISSUE TITLE
相同mod警告

### ISSUE THREAD

**Issue by WangYiBen0** [Hex-Dragon/PCL2#4587]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在mod界面中，如果检测到相同的已启用的mod，则在最上方显示警告【此版本启用了相同mod，左键点击以禁用旧版本】并把相同mod标红

### 原因

这项优化让我可以更方便地检查mod。
如果没有这项优化，我每次都必须下滑看到底，让操作变得很麻烦。

#### Update

警告【此版本疑似启用了相同mod，左键点击以了解更多】，然后弹窗
【名为`name list`的mod存在多个，可能使游戏出现问题 [查看重名mod列表][不再提醒]】

**Comment by wuyuncheng-26** [comment]
也许可以交给龙猫看看……？
不过这方面的判定可能难了点

**Comment by wuliaodexiaoluo** [comment]
>在mod界面中，如果检测到相同的已启用的mod，则在最上方显示警告【此版本启用了相同mod，左键点击以禁用旧版本】并把相同mod标红

请问如何检测？用户提供的文件可能经过修改，因此几乎没有一点可信度

**Comment by Deep-Dark-Forest** [comment]
与 https://github.com/Hex-Dragon/PCL2/issues/2494 不重复

**Comment by WangYiBen0** [comment]
> 也许可以交给龙猫看看……？ 不过这方面的判定可能难了点

直接判mod名字，或者判官网地址

**Comment by WangYiBen0** [comment]
> > 在mod界面中，如果检测到相同的已启用的mod，则在最上方显示警告【此版本启用了相同mod，左键点击以禁用旧版本】并把相同mod标红
> 
> 请问如何检测？用户提供的文件可能经过修改，因此几乎没有一点可信度

看mod信息，至于改版……加个忽略选项就好了

**Comment by JingHai-Lingyun** [comment]
这应该是 #2494 的一种冲突解决方案？

**Comment by allMagicNB** [comment]
……开发者又要给用户擦屁股了。

**Comment by SALTWOOD** [comment]
可以考虑，但是建议可选
因为有些情况下根本没办法保证检测到就是对的

**Comment by allMagicNB** [comment]
> 可以考虑，但是建议可选
> 因为有些情况下根本没办法保证检测到就是对的

如果我检测 ModID 呢？

**Comment by SALTWOOD** [comment]
> > 可以考虑，但是建议可选
> > 因为有些情况下根本没办法保证检测到就是对的
> 
> 如果我检测 ModID 呢？

我写过一个模组叫 salty，结果发现跟一个 1.5.2 版本的模组冲突了 Mod ID

**Comment by allMagicNB** [comment]
> > > 可以考虑，但是建议可选
> > > 因为有些情况下根本没办法保证检测到就是对的
> > 
> > 如果我检测 ModID 呢？
> 
> 我写过一个模组叫 salty，结果发现跟一个 1.5.2 版本的模组冲突了 Mod ID

那么这不对吗？你进游戏没有报错？

**Comment by LTCatt** [comment]
技术原因无法实现准确检测，试着做过，很容易误报漏报（
