### ISSUE TITLE
无法识别某个版本的Minecraft

### ISSUE THREAD

**Issue by LikiaBili** [Hex-Dragon/PCL2#459]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如题，无法识别某些版本的Minecraft
我有一个之前玩了老久的整合包版本，然后就有一段时间没玩，想回来看看，结果找不到这个版本了。
后来我找了一下.minecraft文件夹，发现这个版本文件夹还是存在的，就PCL一直识别不出来，刷新了好几次了
版本json文件一致,版本PCL属性文件夹存在，版本已开启隔离
![image_2022-11-27_104449068](https://user-images.githubusercontent.com/103659676/204116934-2775596e-f275-4a10-be61-87b63b0a3509.png)
![image_2022-11-27_104544358](https://user-images.githubusercontent.com/103659676/204116974-35b4221c-12c4-4bb2-913d-e872480d8978.png)

### 重现步骤

1、点击版本选择
2、选择某个.minecraft文件夹

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10097399/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10097401/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10097402/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10097403/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10097404/Log2.txt)

**Comment by WForst-Breeze** [comment]
请补充整合包文件

**Comment by bwtx2022** [comment]
补充一下目录结构
