### ISSUE TITLE
无法导出崩溃报告

### ISSUE THREAD

**Issue by vocaloidkiss** [Hex-Dragon/PCL2#4593]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

无法导出崩溃报告

### 重现步骤

启动，崩溃后无法导出崩溃报告

### 日志与附件

![捕获](https://github.com/user-attachments/assets/eceaa121-c188-4944-9e12-9c060a4b6f40)

**Comment by Ad-closeNN** [comment]
#4534
