### ISSUE TITLE
导出错误报告时出错

### ISSUE THREAD

**Issue by OutHimic** [Hex-Dragon/PCL2#4594]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

首先是Minecraft出现错误
![image](https://github.com/user-attachments/assets/00ce0c63-54b4-4826-89d7-a7b94a7b554d)
在这个界面，“确定”按钮和“查看日志”按钮均能正常使用，
[日志文件](https://github.com/user-attachments/files/16739665/latest.log)
但是，当点击“导出错误报告“时，PCL2提示”出现错误“
![image](https://github.com/user-attachments/assets/e79206ec-c95c-4058-ad2b-8fd44a31c43d)
内容如下：
`
出现错误
--------------------
导出错误报告失败：文件"D:\Himic\PCL\PCL\Log1.txt"正在由另一进程使用，因此该进程无法访问该文件。
    在PCL.ModBase.GetEncoding(String FilePath)
    在PCL.CrashAnalyzer.Output(Boolean IsHandAnalyze, List`1 ExtraFiles)
错误类型：System.IO.IOException

是否反馈此问题？吴国不反馈，这个问题可能永远无法得到解决！
`

### 重现步骤

注：PCL2 版本快照版2.8.4
1、点击开始游戏，等待提示“Minecraft出现错误”；
2、点击“导出错误报告”，
3、选择保存位置并保存，随即提示“出现错误”。

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16739707/Log1.txt)

**Comment by Deep-Dark-Forest** [comment]
#4534
