### ISSUE TITLE
在版本设置中服务器设置选项中新增正版或第三方

### ISSUE THREAD

**Issue by zhuyanlei2010** [Hex-Dragon/PCL2#4607]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

在版本设置中服务器设置选项中新增正版或第三方

### 原因

服务器是第三方和正版融合，玩家小号需求

**Comment by hejiehao** [comment]
https://github.com/Hex-Dragon/PCL2/discussions/58 这个符不符合你的要求？

**Comment by zhuyanlei2010** [comment]
不太符合，因为我不想要离线

**Comment by Pigeon0v0** [comment]
> 不太符合，因为我不想要离线

那你可以考虑和玩家说一声，或者可以考虑让 #58 做成复选框可选的那种形式...
