### ISSUE TITLE
PCL2提示文件被占用

### ISSUE THREAD

**Issue by WangZiLong-WZL** [Hex-Dragon/PCL2#4615]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我正在修改整合包文件，PCL2报错后，提示导出日志文件，但之后PCL2提示Log1导出失败，文件被占用 
![aae5e6443970a4fe3032cb275e7d841c](https://github.com/user-attachments/assets/4027f352-93f4-41a0-8e63-3cf48ddc40d7)

### 重现步骤

1、点击<某个有问题的游戏整合包>
2、点击启动
3、PCL2报整合包问题
4、点击 导出错误报告
5、PCL2随后提示：出现错误
导出错误报告失败:文件“D:\MC\MC\PCL2\PCL\Log1.txt”正由另一进程使用，因此该进程无法访问
此文件。
在PCL.ModBase.GetEncoding(String FilePath)
在PCL.CrashAnalyzer.0utput(Boolean lsHandAnalyze, List`1 ExtraFiles)
错误类型:System.10.I0Exception

### 日志与附件

[Log2.txt](https://github.com/user-attachments/files/16781665/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16781666/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16781668/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16781669/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/16781674/Log1.txt)

**Comment by Pigeon0v0** [comment]
#4534

**Comment by WangZiLong-WZL** [comment]
既然按你的意思“重复”那说明这个bug已经被修好了，但为什么还是这样？

**Comment by WangZiLong-WZL** [comment]
很好，给我劝退了，你以为我要那活跃橙？我只要一个能启动游戏的启动器

**Comment by lactobionicAcid** [comment]
哥们 = =
PCL 没有热修复机制，现在的 Bug 修复了也不会合并到现在的版本的。
请耐心等待 PCL 下一次更新......

**Comment by WangZiLong-WZL** [comment]
这个bug哪个版本修的

**Comment by WangZiLong-WZL** [comment]
快照版 2.8.4还没合并？

**Comment by Deep-Dark-Forest** [comment]
#4534 上周才被 close as completed，而 2.8.4 是 11 天前发版的。。。

**Comment by hejiehao** [comment]
请等待更新

**Comment by wuliaodexiaoluo** [comment]
>既然按你的意思“重复”那说明这个bug已经被修好了，但为什么还是这样？

重复也可以是与现有正在进行修复的 Issue 重复，并且这个 Issue 确实是修了，只是没发版，更改还没应用，所以请耐心等待
