### ISSUE TITLE
启动游戏显示补全文件失败

### ISSUE THREAD

**Issue by ZJMJAMIE** [Hex-Dragon/PCL2#4625]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

当我启动一个游戏版本时，补全文件到一半的时候出现了报错，有时候还会严重的卡顿，在HMCL上能成功启动。

### 重现步骤

1、点击一个版本
2、然后再主界面启动
3、补全文件的时候报错，带有严重卡顿

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16790970/Log1.txt)

**Comment by wuliaodexiaoluo** [comment]
>[09:47:50.709] [Launch] 错误：补全文件失败
→ 下载支持库文件（主加载器）失败
→ 下载支持库文件失败
→ 文件下载失败：C:\Users\Jamie\curseforge\.minecraft\libraries\optifine\launchwrapper-of\2.3\launchwrapper-of-2.3.jar
远程服务器返回错误: (404) 未找到。（https://bmclapi2.bangbang93.com/maven/optifine/launchwrapper-of/2.3/launchwrapper-of-2.3.jar）
远程服务器返回错误: (404) 未找到。（https://bmclapi2.bangbang93.com/libraries/optifine/launchwrapper-of/2.3/launchwrapper-of-2.3.jar）
远程服务器返回错误: (404) 未找到。（https://libraries.minecraft.net/optifine/launchwrapper-of/2.3/launchwrapper-of-2.3.jar）
→ 远程服务器返回错误: (404) 未找到。

#114

**Comment by wuliaodexiaoluo** [comment]
别下载这个，这个是计算机病毒

**Comment by wuliaodexiaoluo** [comment]
@LTCatt @Light-Beacon

**Comment by zkitefly** [comment]
这个文件应该是在 optifine 安装时生成的，出现这个报错代表着你在安装 optifine 后删除过 libraries 文件夹，或者在拷贝版本的时候没有拷贝 libraries 文件夹……只能通过重装 optifine 解决
