### ISSUE TITLE
较低版本开启了版本隔离音频文件应该在版本文件下的文件夹里

### ISSUE THREAD

**Issue by zec896219** [Hex-Dragon/PCL2#4628]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

把资源文件放在resources文件夹里

### 原因

较低版本以下没有声音

**Comment by wuliaodexiaoluo** [comment]
> 把1.6.4版本以下的音频文件放在resources文件夹里

请提供具体日志，PCL 对于低版本的行为是使用软链挂载文件夹

**Comment by allMagicNB** [comment]
#3684

**Comment by LTCatt** [comment]
如果较低版本没有声音，请上传日志并补充具体版本等信息

**Comment by zec896219** [comment]
[Log1.txt](https://github.com/user-attachments/files/16797651/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16797654/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16797657/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/1679
[Log5.txt](https://github.com/user-attachments/files/16797661/Log5.txt)
7660/Log4.txt)
版本是1.4.7 hmcl可以把文件补充完整 其他版本我只测试过1.0版本也没有声音

**Comment by zec896219** [comment]
1.6以下就没有声音了

**Comment by LTCatt** [comment]
![image](https://github.com/user-attachments/assets/1a1b49b8-4dc8-45d8-b151-26b8b03450e5)

我不知道这是啥情况，如果 resource 文件夹没有加载，就不应该有语言选择，所以它确实加载成功了。
但是没声音……

**Comment by zkitefly** [comment]
备注：如果使用了上面的方法在游戏中仍然没有声音，可以试试在 jvm 参数中加入 betacraft 提高的修复方案（`-Dhttp.proxyHost=betacraft.uk`），一般都能恢复声音
