### ISSUE TITLE
mod下载中部分模组列表显示不完整

### ISSUE THREAD

**Issue by ZLXL1234** [Hex-Dragon/PCL2#4632]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

部分模组在版本分类中显示不完整，即使没有指定mod加载器
机械动力：
![image](https://github.com/user-attachments/assets/1547ec0a-033a-44c2-80f2-be1614175c36)
![image](https://github.com/user-attachments/assets/14ab9be0-f82b-47aa-b368-ce7348dfcb53)
暮色森林：
![image](https://github.com/user-attachments/assets/cbc29d5c-8361-47fe-9878-b2dc3f9beb75)

### 重现步骤

1、进入下载->mod
2、任意搜索一个模组
![image](https://github.com/user-attachments/assets/f6106329-8408-4f5c-aec1-f530c8d4a67f)
3、进入详情页
4、版本分类显示mod与modrinth/curseforge显示不一致

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16797363/Log1.txt)

**Comment by ZLXL1234** [comment]
特别是机械动力，没有显示1.20.1fabric的模组

**Comment by hejiehao** [comment]
Create≠Create Fabric

**Comment by ZLXL1234** [comment]
暮色森林那么多版本怎么只显示一个呢

**Comment by SALTWOOD** [comment]
> 暮色森林那么多版本怎么只显示一个呢

大概可以理解为推荐版本。别的过时的版本一般不建议用
