### ISSUE TITLE
所有游戏版本中的mod页面都显示未将对象引用设置到对象的示例

### ISSUE THREAD

**Issue by DistinctMedal42** [Hex-Dragon/PCL2#4633]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

所有游戏版本中的mod页面都显示未将对象引用设置到对象的示例，删除有关minecraft和pcl的所有文件再次安装还是这样，如图(https://github.com/user-attachments/assets/0aa8cdfe-99a8-49aa-ad56-ca3ce729db63)

### 重现步骤

游玩的时候停电过一次，再次打开pcl2所有版本都显示未将对象引用设置到对象的示例

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16798458/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16798459/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16798461/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16798462/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16798463/Log5.txt)

**Comment by lactobionicAcid** [comment]
疑似与 #3433 重复...
```
# Log1.txt Ln 68
[19:10:01.473] 读取本地 Mod 信息缓存失败，已重置：未将对象引用设置到对象的实例。
   在 PCL.ModMod.McModLoad(LoaderTask`2 Loader)
错误类型：System.NullReferenceException
[19:10:01.473] Mod 列表加载失败：未将对象引用设置到对象的实例。
   在 PCL.ModMod.McModLoad(LoaderTask`2 Loader)
错误类型：System.NullReferenceException
[19:10:01.473] 加载线程 Mod List Loader (20) 发生运行时错误：未将对象引用设置到对象的实例。
   在 PCL.ModMod.McModLoad(LoaderTask`2 Loader)
   在 PCL.ModLoader.LoaderTask`2._Closure$__13-0._Lambda$__0()
错误类型：System.NullReferenceException
```

**Comment by youzi-3222** [comment]
确实和 #3433 重复。但是 #3433 因为作者不提供信息关闭了……这个 issue 应该能处理。

要不也像 #3433 一样传一下 `mods` 文件夹？

**Comment by allMagicNB** [comment]
那就 Reopen #3433
