### ISSUE TITLE
添加mod自动命名功能

### ISSUE THREAD

**Issue by xiao0miao** [Hex-Dragon/PCL2#4638]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

有这样一个场景，你收到朋友发来的版本，mods文件夹中的mod命名是1.jar 2.jar…
这时pcl是可以识别出mod的信息的，所以，建议加一个自动命名功能，而不是只是在下载mod时帮你命名一次

建议给用户一个选项，让用户自己选择命名格式
我建议的命名格式是[mod名称]-[mc版本]-[mod加载器版本]-[mod版本]-[客户端需装/可选/无效]-[服务端需装/可选/无效].jar
这样我每次为整合包开服时只需要搜索带“服务端需装”和“服务端可选”的mod就可以了

### 原因

这项优化让我可以更方便地了解mod信息。
我有事会开mod服务器，如果没有这项优化，我每次都必须去mc百科看mod是客户端需装还是服务端需装，让操作变得很麻烦。

**Comment by SALTWOOD** [comment]
算是新功能？不过这种新功能适用范围也太小众了吧……

**Comment by JingHai-Lingyun** [comment]
格式化 Mod 名？请见 #1728 #3804
