### ISSUE TITLE
给自定义主页加更多控件

### ISSUE THREAD

**Issue by Ext1nguisher** [Hex-Dragon/PCL2#4639]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

可以给回声洞加入一个专门的控件复原百宝箱中的逐字出现效果，“你知道吗”同理。
同时，可以加入日志控件，像local:MyLog之类的。

### 原因

目前的’{hint}’提示法只能在刷新主页时更新内容，且有局限性。“你知道吗”同理。
日志控件目前只能通过打开调试模式实现，但是其实现非常局限，只能在最下方添加横跨左右固定宽度的card

**Comment by LTCatt** [comment]
暂时不考虑，抱歉（
