### ISSUE TITLE
模组More Culling的Mod icon图标被错误的替换为FPS减速器的Mod icon

### ISSUE THREAD

**Issue by Cai-kunkun** [Hex-Dragon/PCL2#4645]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

More Culling模组的icon图标被错误的替换为FPS减速器的icon微标
![image](https://github.com/user-attachments/assets/908459c7-83e8-4d33-a701-c8b15d8fa93b)

### 重现步骤

1、下载任意版本的More Culling模组
2、打开对应版本的Mod列表
3、找到More Culling模组

### 日志与附件

[Log5.txt](https://github.com/user-attachments/files/16814820/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/16814822/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16814823/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16814824/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16814826/Log4.txt)

**Comment by JingHai-Lingyun** [comment]
![image](https://github.com/user-attachments/assets/e7a97ae2-0bbf-4d96-ab9f-d7b71c90bcf9)
![image](https://github.com/user-attachments/assets/0523f3c8-4b7a-481b-8d7a-62a4a4933434)
不开启和开启调试模式的情况下，得到了不同的结果？

**Comment by LTCatt** [comment]
经过检查……在 CurseForge 上，这个文件和 FPS Reducer 的 hash 重了。
千年难遇啊文件 hash 重了。
这个修不了。

使用 HMCL 跳转到 CurseForge 也会定位到 FPS Reducer。
![image](https://github.com/user-attachments/assets/889017f6-ad52-400d-861b-42240c991405)
![image](https://github.com/user-attachments/assets/2c4a29c9-af0c-47f0-a1f8-86f0d43d7bcb)

**Comment by Cai-kunkun** [comment]
我去百年难遇啊....
