### ISSUE TITLE
将Mod搜索界面中来自curseforge和modrinth的两类模组做出明显区分

### ISSUE THREAD

**Issue by slf080120** [Hex-Dragon/PCL2#4648]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

将“Curseforge”和“Modrinth”字样做加大、加粗处理，并且放在显眼位置
有一些模组在Curse和Modrinth上均有资源，可以考虑将二者合并为一个页面

### 原因

此优化可以让使用者更加方便地寻找模组，规避了一些用户因搜索页出现2个同名模组而会不知道怎样选择的问题
如果没有作出区分，部分使用者可能会重复下载同一个模组。

**Comment by Deep-Dark-Forest** [comment]
> 有一些模组在Curse和Modrinth上均有资源，可以考虑将二者合并为一个页面

参见 #1318

**Comment by allMagicNB** [comment]
开发者又要为用户擦屁股喽

**Comment by LTCatt** [comment]
想了想好像没太大必要……这个信息对普通玩家而言并不重要（
