### ISSUE TITLE
在版本mod列表的mod详细信息中突出显示当前mod版本

### ISSUE THREAD

**Issue by xiao0miao** [Hex-Dragon/PCL2#4649]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

游戏版本的mod列表中右键点击mod可以打开类似下载界面的mod详细信息，希望可以突出显示一下当前安装的mod版本

### 原因

这项优化让我可以更方便地清楚我目前安装的mod版本。

**Comment by JingHai-Lingyun** [comment]
![image](https://github.com/user-attachments/assets/49fd3ef8-7ab7-4d6c-b677-31ea1fe551eb)
Mod 元素的第一行 ` 中文名(如有) |  英文名 | 版本号 ` 不就有么…… 
还能咋突出……

**Comment by xiao0miao** [comment]
> ![图像](https://private-user-images.githubusercontent.com/109946426/363250467-49fd3ef8-7ab7-4d6c-b677-31ea1fe551eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwNzUxOTMsIm5iZiI6MTcyNTA3NDg5MywicGF0aCI6Ii8xMDk5NDY0MjYvMzYzMjUwNDY3LTQ5ZmQzZWY4LTdhYjctNGQ2Yy1iNjc3LTMxZWExZmU1NTFlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgzMVQwMzI4MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OTY3NzdmZGZlZTRhMWIwNjllZmIyZDhjNWQwZTUzMzU5MTljMzJjMGJiZWMxY2E3MTU4ZDAzYzc1M2JlNDI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cGcayOdCKUXe65GZdJp0TW9xBsLM32PhLuKlNDRTKAw)Mod 元素的第一行 不就有么...... 还能咋突出......`中文名(如有) | 英文名 | 版本号`

我的意思是突出显示当前安装到版本

**Comment by JingHai-Lingyun** [comment]
安装到版本？

**Comment by xiao0miao** [comment]
> 安装到版本？

当前已经安装的mod，是安装过的

**Comment by LTCatt** [comment]
感觉没太大必要，算了吧 orz
