### ISSUE TITLE
版本放问题

### ISSUE THREAD

**Issue by ljy2231** [Hex-Dragon/PCL2#4650]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在正式版版本列表中，1.4.4直接跳到1.4.6然后才是1.4.5

### 重现步骤

1，点击下载
2，点击正式版
3，下滑
4，找到1.4.4

### 日志与附件

![1fdb570f877e8aeca69353dc8fc424c4](https://github.com/user-attachments/assets/b5d12c2d-fa67-43e9-be31-b63795205ad7)

**Comment by JingHai-Lingyun** [comment]
![image](https://github.com/user-attachments/assets/aff1c084-8a9e-4c12-96ec-9b71d729a9c2)
Mojang API 提供的就是这样的…… 给龙猫看看.png

**Comment by allMagicNB** [comment]
111真的不查重吗？

**Comment by allMagicNB** [comment]
#456

**Comment by JingHai-Lingyun** [comment]
诶……？
