### ISSUE TITLE
[Bug] PCL2 自动更新选项无效

### ISSUE THREAD

**Issue by wuliaodexiaoluo** [Hex-Dragon/PCL2#4656]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/user-attachments/assets/f9748022-f91e-435c-9c40-3777d34f2b3f)
如题，我的选项是自动下载更新
![image](https://github.com/user-attachments/assets/7006417d-3772-4074-8f56-f38007b1f01b)
但是 2.8.5 已经发布了，我的版本还留在 2.8.4 没有自动更新
查重暂时没找到

### 重现步骤

将更新设置为自动下载
等待版本更新后发现版本没有自动更新

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16823211/Log1.txt)

**Comment by PhantomPixel-0418** [comment]
试着重启下试试？
说不定就好了..

**Comment by allMagicNB** [comment]
Reopen #3862.

**Comment by JingHai-Lingyun** [comment]
> 漏了两个小版本

2.8.4，2.8.5 都是快照更新，正式版没有（
重开 #3862，这个先关了

**Comment by PhantomPixel-0418** [comment]
难怪我说）
只是漏了快照版没啥问题..
________________________________
发件人: 凌云 ***@***.***>
发送时间: 2024年8月31日 11:07
收件人: Hex-Dragon/PCL2 ***@***.***>
抄送: 幻影像素 ***@***.***>; Comment ***@***.***>
主题: Re: [Hex-Dragon/PCL2] [Bug] PCL2 自动更新选项无效 (Issue #4656)


漏了两个小版本

2.8.4，2.8.5 都是快照更新，正式版没有（
重开 #3862<https://github.com/Hex-Dragon/PCL2/issues/3862>，这个先关了

―
