### ISSUE TITLE
线程与下载文件数量不符

### ISSUE THREAD

**Issue by wuwenjun9939** [Hex-Dragon/PCL2#4657]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/user-attachments/assets/a9d25530-a1ae-4e3d-9608-b068855247b5)

### 重现步骤

随便下载一个整合包，打开下载页面就能看到

### 日志与附件

[Log4.txt](https://github.com/user-attachments/files/16823328/Log4.txt)
[Log.txt](https://github.com/user-attachments/files/16823330/Log.txt)
[Log1.txt](https://github.com/user-attachments/files/16823332/Log1.txt)
（剩下俩日志因为太大，所以上传不到GitHub上）

**Comment by JingHai-Lingyun** [comment]
下载线程是下载线程，和有多少文件是没有关系的
线程越多下载越快（即上方下载速度上限越高）

**Comment by wuwenjun9939** [comment]
> 下载线程是下载线程，和有多少文件是没有关系的 一个文件可以由多个线程下载其碎片，最终合并 线程越多下载越快（即上方下载速度上限越高）

但是，我好像能看到几个257（超线程）的....就是说：257/256（虽然只会闪烁几秒，但是，我眼尖）

**Comment by JingHai-Lingyun** [comment]
小跳变正常，线程数管理不是非常完美罢了

**Comment by LTCatt** [comment]
偶尔会超 1 个线程，问题不大。
多个线程可能同时下载 1 个文件。
WAI
