### ISSUE TITLE
当启动器不是最新版时，“反馈” “新功能投票” 窗口中添加 “检查更新” 按钮

### ISSUE THREAD

**Issue by WForst-Breeze** [Hex-Dragon/PCL2#4662]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

当用户启动器不是最新版时，点击 “反馈” “新功能投票” 选项后，弹出的窗口中添加 “检查更新” 按钮，允许用户直接通过点击该按钮进行更新

### 原因

可以大幅缩减用户操作步骤，节省用户操作时间，避免用户需要经过 **关闭窗口 → 设置 → 启动器 → 检查更新** 的繁琐操作步骤才可以进行更新

**Comment by LTCatt** [comment]
如果不是最新版，提示弹窗中现增加了更新选项。
