### ISSUE TITLE
PCL拉取文本失败切换主要页面失败

### ISSUE THREAD

**Issue by milan-a11y** [Hex-Dragon/PCL2#4663]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

无法切换主要页面一直冒错误

### 重现步骤

1、点击四个主页面其中一个概率出现出现场景MoD下载完毕之后且在搜索栏

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16823530/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16823531/Log2.txt)

**Comment by LTCatt** [comment]
有更详细的复现方式么？

<details><summary>Details</summary>
<p>

```
[13:13:48.534] [Control] 按下图标按钮
[13:13:48.725] [UI] 弹出提示：已将 [旅行地图] journeymap-1.20.4-5.10.0-fabric.jar 删除到回收站！
[13:13:50.192] [Control] 按下图标按钮：BtnTitleInner
[13:13:50.203] 切换主要页面失败（ID 0）：给定关键字不在字典中。
   在 System.ThrowHelper.ThrowKeyNotFoundException()
   在 System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   在 System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   在 PCL.PageVersionMod.ChangeAllSelected(Boolean Value)
   在 PCL.PageVersionMod.UnselectedAllWithAnimation()
   在 PCL.MyPageRight.PageOnExit()
   在 PCL.FormMain.PageChangeAnim(FrameworkElement TargetLeft, FrameworkElement TargetRight)
   在 PCL.FormMain.PageChangeActual(PageStackData Stack, PageSubType SubType)
错误类型：System.Collections.Generic.KeyNotFoundException
[13:13:50.208] [Control] 普通弹窗：出现错误
切换主要页面失败（ID 0）：给定关键字不在字典中。
   在 PCL.PageVersionMod.ChangeAllSelected(Boolean Value)
   在 PCL.PageVersionMod.UnselectedAllWithAnimation()
   在 PCL.MyPageRight.PageOnExit()
   在 PCL.FormMain.PageChangeAnim(FrameworkElement TargetLeft, FrameworkElement TargetRight)
   在 PCL.FormMain.PageChangeActual(PageStackData Stack, PageSubType SubType)
错误类型：System.Collections.Generic.KeyNotFoundException
```

</p>
</details>

**Comment by zfzr031** [comment]
> 有更详细的复现方式么？
> 
> Details
> ```
> [13:13:48.534] [Control] 按下图标按钮
> [13:13:48.725] [UI] 弹出提示：已将 [旅行地图] journeymap-1.20.4-5.10.0-fabric.jar 删除到回收站！
> [13:13:50.192] [Control] 按下图标按钮：BtnTitleInner
> [13:13:50.203] 切换主要页面失败（ID 0）：给定关键字不在字典中。
>    在 System.ThrowHelper.ThrowKeyNotFoundException()
>    在 System.Collections.Generic.Dictionary`2.get_Item(TKey key)
>    在 System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
>    在 PCL.PageVersionMod.ChangeAllSelected(Boolean Value)
>    在 PCL.PageVersionMod.UnselectedAllWithAnimation()
>    在 PCL.MyPageRight.PageOnExit()
>    在 PCL.FormMain.PageChangeAnim(FrameworkElement TargetLeft, FrameworkElement TargetRight)
>    在 PCL.FormMain.PageChangeActual(PageStackData Stack, PageSubType SubType)
> 错误类型：System.Collections.Generic.KeyNotFoundException
> [13:13:50.208] [Control] 普通弹窗：出现错误
> 切换主要页面失败（ID 0）：给定关键字不在字典中。
>    在 PCL.PageVersionMod.ChangeAllSelected(Boolean Value)
>    在 PCL.PageVersionMod.UnselectedAllWithAnimation()
>    在 PCL.MyPageRight.PageOnExit()
>    在 PCL.FormMain.PageChangeAnim(FrameworkElement TargetLeft, FrameworkElement TargetRight)
>    在 PCL.FormMain.PageChangeActual(PageStackData Stack, PageSubType SubType)
> 错误类型：System.Collections.Generic.KeyNotFoundException
> ```

删除mod后点击左上角返回立即触发

**Comment by LTCatt** [comment]
> 删除mod后点击左上角返回立即触发

没法复现

**Comment by zfzr031** [comment]
> > 删除mod后点击左上角返回立即触发
> 
> 没法复现

使用搜索得到mod，删除，返回，触发

**Comment by LTCatt** [comment]
ok
![image](https://github.com/user-attachments/assets/357cf5ea-655c-47b3-b57c-6feec22d21c0)
