### ISSUE TITLE
打开minecraft后，关闭pcl2再打开关闭minecraft的按钮消失

### ISSUE THREAD

**Issue by 4864185** [Hex-Dragon/PCL2#4664]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

打开minecraft后，关闭pcl2再打开关闭minecraft的按钮消失

### 重现步骤

1.打开任意minecraft
2.关闭pcl2
3.再打开pcl2后

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16824569/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16824570/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16824571/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16824572/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16824573/Log5.txt)

**Comment by wyc-26** [comment]
这是正常的，并非 Bug（

**Comment by Cai-kunkun** [comment]
是的

**Comment by Cai-kunkun** [comment]
但是当Minecraft崩溃的时候他会说xx原因

**Comment by LTCatt** [comment]
无法修复，新开启的 PCL 无法获得已开启的 MC 进程的输入输出流信息，也不好识别是不是 MC

**Comment by allMagicNB** [comment]
#1243
