### ISSUE TITLE
安装 CurseForge 整合包时未使用镜像源

### ISSUE THREAD

**Issue by lihansen136** [Hex-Dragon/PCL2#4665]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

当安装整合包后，显示报错：整合包安装失败
你的网络环境不佳，导致难以连接到服务器。请检查网络，多重试几次，或尝试使用 VPN。
————————————
详细错误信息：
→ 下载 Mod（主加载器）失败
→ 获取 Mod 下载信息失败
→ 网络请求失败（SendFailure，基础连接已经关闭: 发送时发生错误。，https://api.curseforge.com/v1/mods/files）
→ 基础连接已经关闭: 发送时发生错误。
→ 无法从传输连接中读取数据: 远程主机强迫关闭了一个现有的连接。。
→ 远程主机强迫关闭了一个现有的连接。
   在 PCL.ModNet.NetRequestRetry(String Url, String Method, Object Data, String ContentType, Boolean DontRetryOnRefused, Dictionary`2 Headers)
   在 PCL.ModModpack._Closure$__6-0._Lambda$__1(LoaderTask`2 Task)
   在 PCL.ModLoader.LoaderTask`2._Closure$__13-0._Lambda$__0()
   在 PCL.ModNet.NetRequestOnce(String Url, String Method, Object Data, String ContentType, Int32 Timeout, Dictionary`2 Headers, Boolean MakeLog, Boolean UseBrowserUserAgent)
错误类型：System.Net.Sockets.SocketException整合包安装失败

### 重现步骤

1.拖入整合包压缩文件
2.安装
3.显示报错

PS：hmcl能正常下载

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16823665/Log1.txt)
[Log3.txt](https://github.com/user-attachments/files/16823668/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16823669/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16823670/Log5.txt)
[Log2.txt](https://github.com/user-attachments/files/16823666/Log2.txt)

**Comment by lihansen136** [comment]
加速开启/关闭都没有用，已尝试重启

**Comment by LTCatt** [comment]
理论上应该 fallback 到镜像源才对，我看看咋回事

**Comment by lihansen136** [comment]
Uploading PCL error.mp4…

视频

**Comment by lihansen136** [comment]
发作视频
我用夸克网盘分享了「PCL error.mp4」，点击链接即可保存。打开「夸克APP」，无需下载在线播放视频，畅享原画5倍速，支持电视投屏。
链接：https://pan.quark.cn/s/91005860d671

**Comment by lihansen136** [comment]
Mod信息获取也是用的镜像源

**Comment by lihansen136** [comment]
识别码 1FCA-0F88-2695-A468
@LTCatt

**Comment by LTCatt** [comment]
你的解锁码：DfjfZMyW+5LKTkVHfqhCQVM76TJobkiz
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by z0z0r4** [comment]
注意，文件缓存当前覆盖率低，且仅缓存 gameid 432 和 classID 为 6 的 Mod 文件

**Comment by lihansen136** [comment]
识别码 989A-23E0-1318-E019
@LTCatt

**Comment by WRD1145** [comment]
识别码 93FA-36E6-E6B4-740A
@LTCatt

**Comment by WRD1145** [comment]
qwq重装系统没备份主题（）

**Comment by LTCatt** [comment]
你的解锁码：B0ei1aqPle/DW+9x4spOQUtOVC4UtIW0
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
