### ISSUE TITLE
[优化] FabricAPI自动下载添加curseforge下载源

### ISSUE THREAD

**Issue by MinecraftYYDS7** [Hex-Dragon/PCL2#4667]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

下载Fabric端时，PCL2会自动启用Fabric api下载。
**但是**这个下载**只能**modrith api下载。
**建议**添加curse镜像

### 原因

优化部分玩家的体验，加快下载速度。

**Comment by hejiehao** [comment]
https://github.com/Hex-Dragon/PCL2/issues/4327
