### ISSUE TITLE
当播放音乐时，插拔耳机线会报错

### ISSUE THREAD

**Issue by Q195za** [Hex-Dragon/PCL2#4670]
### 检查项

- [ ] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在Windows 8.1中播放音乐，重新热插拔耳机线，PCL会报错，右下角音乐图标卡死。
报错System.NullReferenceException
![Uploading PCL2Erreor.PNG…]()

### 重现步骤

1、播放音乐
2、重新插拔耳音响线
3、启动游戏

### 日志与附件

[Uploading Log2.txt…
[Uploading Log1.txt…]()
]()

**Comment by Ext1nguisher** [comment]
文件请等待`Uploading xxx`字样消失后再提交

**Comment by allMagicNB** [comment]
#1753 #4527

**Comment by JingHai-Lingyun** [comment]
需要日志或截图确认是哪一个（或都不是），但大概率应该是 #1753

**Comment by allMagicNB** [comment]
![Screenshot_20240901_115347.jpg](https://github.com/user-attachments/assets/2db52955-eb0a-4fc4-8e63-5b3bbfebd12a)

自作聪明。

**Comment by SALTWOOD** [comment]
#2238 和 #4517，基本确定是重复了

**Comment by Pigeon0v0** [comment]
长时间未补充 Log，且大概率为重复 Issue，先关了，如果有其他信息可以继续补充
