### ISSUE TITLE
PCL启动不了

### ISSUE THREAD

**Issue by Creeper-JXC** [Hex-Dragon/PCL2#4672]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

不知道是不是自己的问题
这个文件没有解包过，就是他自己打不开
![image](https://github.com/user-attachments/assets/c804352a-44c5-47d8-b29c-cbd26e3327b4)
换了路径也没用
仅限于这个文件,点了"是"按操作来还是打不开

### 日志与附件

[Plain Craft Launcher 2.zip](https://github.com/user-attachments/files/16828593/Plain.Craft.Launcher.2.zip)

**Comment by allMagicNB** [comment]
PCL 应当无法解决。

**Comment by hejiehao** [comment]
你的 PCL 是从哪来的？

**Comment by tangge233** [comment]
![image](https://github.com/user-attachments/assets/03a2e48d-23ae-4b7f-b179-faadacb87715)
您好，这是病毒文件。请及时对您的电脑进行杀毒。

**Comment by wyc-26** [comment]
~很难相信现在还能有人下错 PCL 的 🤣~
下载地址请去爱发电查看
https://afdian.com/p/0164034c016c11ebafcb52540025c377
~都找到 PCL 的 GitHub 了结果还没找到 PCL 的下载地址，佩服~

**Comment by Creeper-JXC** [comment]
不是下错的，之前一只用的是这个就是突然out了

**Comment by Creeper-JXC** [comment]
> 你的 PCL 是从哪来的？

群
![image](https://github.com/user-attachments/assets/2f5fbed3-2a93-4d1a-86bc-c97136a13672)
更新后的

**Comment by Creeper-JXC** [comment]
> ![image](https://private-user-images.githubusercontent.com/50769997/363488297-03a2e48d-23ae-4b7f-b179-faadacb87715.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxOTgyMTcsIm5iZiI6MTcyNTE5NzkxNywicGF0aCI6Ii81MDc2OTk5Ny8zNjM0ODgyOTctMDNhMmU0OGQtMjNhZS00YjdmLWIxNzktZmFhZGFjYjg3NzE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDEzMzgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0YmU5MzU0NjYzOWMwN2Y4NWJiMDdlYTQxMzg0MjA1MmQ5ZDRhZWNhNDk2ZDY4MGRiYTVhZGZlYTgwOWZhNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U5VVCglsxJZRbM6xSIbRaJthWqWMcAOHlJ4ai_lwALw)您好，这是病毒文件。请及时对您的电脑进行杀毒。 搜索了一下，这是感染型病毒，您需要使用某三位数字杀毒软件彻底杀除。 [详细分析请看此处](https://s.threatbook.com/report/file/8647e2b65ade9dd4590c42bc441dafb568fdd8a3fc8c8e21e5ddc571e3d05c5b)

我第一次用内测版windows会报毒

**Comment by Creeper-JXC** [comment]
> ~很难相信现在还能有人下错 PCL 的 🤣~ 下载地址请去爱发电查看 https://afdian.com/p/0164034c016c11ebafcb52540025c377 ~都找到 PCL 的 GitHub 了结果还没找到 PCL 的下载地址，佩服~
不是这样的ok？

**Comment by tangge233** [comment]
你提供的文件包含了感染型病毒（一种可以感染其它应用程序从而传播的病毒），请使用杀毒软件对您的计算机进行杀毒操作
PCL2 的误报目前仅限于 Windows 安全中心
