### ISSUE TITLE
将启动器窗口大小存储在文件而非注册表，以便分发整合包

### ISSUE THREAD

**Issue by LuckiQ** [Hex-Dragon/PCL2#4678]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

添加自定义PCL窗口大小的参数选项

例如：

启动器启动窗口大小：_____x_____    [  ]锁定窗口大小

勾选锁定窗口大小后，将不能再通过拖动窗口边框调整窗口大小

### 原因

在制作整合包专属主页的时候，发现PCL的窗口大小总是记忆上次关闭的大小。将整合包分发给玩家后在玩家的电脑上以默认窗口大小启动，这导致主页的页面排版设计在各玩家的电脑上的观感表现不一致

**Comment by allMagicNB** [comment]
你应该需要调整你的主页，而非 PCL。

**Comment by tangge233** [comment]
## PCL2 的窗口大小相关概念
PCL2 的窗口大小存储在注册表中，在每次修改 PCL2 窗口大小后都会保存进注册表。在未修改窗口的大小情况下，计算机上所有的 PCL2 的窗口大小都是一致的。如果没有使用过 PCL2 或者使用 PCL2 之后没有调整窗口大小，那么 PCL2 的窗口大小就是默认大小。
## 对于整合包的自定义主页
自定义主页的制作应当考虑玩家启动器界面的不同情况（有喜欢拉大界面的，也有喜欢默认的界面，当然还有其它各种情况）。作者应善于使用 Grid、StackPanel 等 WPF 布局控件做到页面自适应而不是去让玩家自适应……

**Comment by LTCatt** [comment]
或许可以考虑把窗口大小存储在 setup.ini 中？

**Comment by fangshifu233** [comment]
建议同步搞一个"文本跟随窗口大小改变"选项,因为我习惯把启动器放大,但是字体和选项图标无法放大,看着好不舒服 @LTCatt

**Comment by WForst-Breeze** [comment]
> 建议同步搞一个"文本跟随窗口大小改变"选项,因为我习惯把启动器放大,但是字体和选项图标无法放大,看着好不舒服

可以交个新的 Issue

**Comment by LTCatt** [comment]
现在 PCL 的窗口大小会存储在 PCL/Setup.ini 中
