### ISSUE TITLE
优化网络错误时的弹窗

### ISSUE THREAD

**Issue by ZHAOSBC** [Hex-Dragon/PCL2#468]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在出现各种因网络和服务器问题导致的游戏登陆失败以及整合包下载失败等问题的时候显示通俗易懂的提示和重试的按钮

### 原因

经常有人因为遇到这些问题后看不懂错误报告在群里提问，但是大多数时候只要重试一遍就能解决

**Comment by LTCatt** [comment]
嗯……大家可以补充一下具体的弹窗内容，我好针对性地修改……

**Comment by ZHAOSBC** [comment]
> 嗯……大家可以补充一下具体的弹窗内容，我好针对性地修改……

找到了一些 可能有一些不能通过弹窗解决（）
（第一个是QQ截图）
![QQ图片20221128173605](https://user-images.githubusercontent.com/119199014/204248840-ae5f4419-6aa9-4e88-a329-f299d1f72328.png)
![Screenshot_20221128_174843_net afdian afdian](https://user-images.githubusercontent.com/119199014/204248858-9e50826b-c0a8-4a36-8c54-bda11bfa2e04.png)
![Screenshot_20221128_175029_net afdian afdian](https://user-images.githubusercontent.com/119199014/204248875-12d05f71-d073-4481-a3c4-0f25be330f6c.png)
![Screenshot_20221128_175245_net afdian afdian](https://user-images.githubusercontent.com/119199014/204248885-8f0da230-8135-436b-bc8c-46cabdea7a40.png)
![Snipaste_2022-10-09_14-49-37](https://user-images.githubusercontent.com/119199014/204248915-32a6d363-42fb-4226-9c9c-281bdd81efe9.png)

**Comment by LTCatt** [comment]
![image](https://user-images.githubusercontent.com/40348278/206891707-a17429ec-3cd1-4ec3-bdf5-eb604dbb9fa7.png)
