### ISSUE TITLE
游戏窗口最大化选项无效

### ISSUE THREAD

**Issue by Jonck-lens** [Hex-Dragon/PCL2#4680]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

启动1.18.2（forge40.2.11）游戏版本，并在设置->窗口大小中选择最大化选项，但游戏窗口仍以默认大小显示（我的是873x508）

启动其他版本时，pcl似乎都会执行一个最大化游戏窗口的操作，但在此版本中，直到主界面进入也没有任何操作
我认为最有可能是因为pcl提前最大化操作（进入mojang界面前，有一段无响应时间，窗口任何操作均无效）

根据pcl日志，窗口加载仅仅1s左右就进行了最大化操作，受限于设备性能，10s左右才脱离无响应状态，此时窗口仍以默认大小显示

### 重现步骤

1. 窗口选择最大化
2. 启动一个加载耗时较长的版本

### 日志与附件

[Log1(273行手动注释).txt](https://github.com/user-attachments/files/16849335/Log1.273.txt)

**Comment by tangge233** [comment]
1.18.2-Forge_40.2.11 无 Mod 安装，无法复现

**Comment by Jonck-lens** [comment]
找了半天，现在确定很大概率是 Modern UI  这个mod的问题，这个mod似乎修改了原版游戏的许多内容。mod是开源的，希望开发者针对这个mod做出相关修改  https://github.com/BloCamLimb/ModernUI-MC

**Comment by wyc-26** [comment]
PCL 不会对特定的模组做适配吧……
之前记得有一个要求适配信雅互联的被批回去了

**Comment by LTCatt** [comment]
如果是 mod 的问题就先关了 =。=
