### ISSUE TITLE
登录时显示：基础连接已经关闭: 未能为 SSL/TLS 安全通道建立信任关系。）

### ISSUE THREAD

**Issue by HTTE-lx** [Hex-Dragon/PCL2#4682]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

[Log1.txt](https://github.com/user-attachments/files/16869440/Log1.txt)

### 重现步骤

1.点击登录
2.在弹出的页面中登录并到达空白页面
3.将空白页面的网址复制到PCL的输入框内
4.开始登录，并在35%处停顿，之后报错

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16869457/Log1.txt)

**Comment by tangge233** [comment]
问题重复： #3846

**Comment by HTTE-lx** [comment]
问题已解决，感谢您的指导
