### ISSUE TITLE
预设的新闻主页无法加载 而采用信标域名的版本可以加载（？

### ISSUE THREAD

**Issue by Joker2184** [Hex-Dragon/PCL2#4687]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

首先提一嘴 不确定是否为PCLbug 如果不是麻烦协助者close一下（（（
版本：[18:15:23.806] [Start] 程序版本：Release 2.8.3 (332)
目前测下来貌似 
预设部分的新闻主页获取不了{log1 域名显示为http://pcl.mcnews.thestack.top}
而采用联网更新的新闻主页则可以正常获取{https://news.bugjump.net/version}
同时也测试了其他预设皆可正常使用
LOG1 170行为其他预设测试
185行为预设新闻主页报错
251行为联网更新新闻主页

### 重现步骤

点击预设：新闻主页
公测版 2.8.3 

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16887863/Log1.txt)

**Comment by Joker2184** [comment]
[Log1.txt](https://github.com/user-attachments/files/16888280/Log1.txt)
升级快照 2.8.6 测试（依旧刷新不出来（（（（（

**Comment by LTCatt** [comment]
@Light-Beacon

**Comment by Light-Beacon** [comment]
真是离谱，我就没动这东西（
不过现在我换了个方式，应该好了
