### ISSUE TITLE
支持{hint}你知道吗替换标记远程获取

### ISSUE THREAD

**Issue by Joker2184** [Hex-Dragon/PCL2#4688]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

支持{hint}你知道吗替换标记远程获取
达成类似联网更新的效果

### 原因

奇怪的想法 用hint当回声洞用（不是
想法来源：
https://github.com/Hex-Dragon/PCL2/discussions/4624+自定义主页教程

<local:MyTextButton Text="{hint}" EventType="刷新主页" />
你也可以使用替换标记来获取随机内容：cave` 会被替换为一条随机的回声洞内容，hint 则是 “你知道吗” 的内容

需求：支持联网更新获取的同时获取一个自定义 你知道吗文件

联网更新 ->下载文件->PCL读取主页和自定义“你知道吗”hint.txt

目的：绑定{hint}替换标记 来实现伪回声洞效果 绑定后 PCL获取下载hint文件 然后搭配刷新主页用来显示主页编写人员想写的一些句子（

需求人群：服务器服主 和 主页编写者

**Comment by Joker2184** [comment]
测试了一下（替换标记+hints.txt能用（awa

**Comment by kong-que-dnf123** [comment]
事实上“你知道吗”刚出的时候就会有一定几率覆盖进回声洞里后来被修了（（
https://github.com/Hex-Dragon/PCL2/issues/2704#issuecomment-1725928578

**Comment by LTCatt** [comment]
通过服务器或者云函数来动态返回主页 xaml 即可。
