### ISSUE TITLE
联机设置诈尸 2.4.3

### ISSUE THREAD

**Issue by yuanquanya** [Hex-Dragon/PCL2#469]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

设置联机又出现了，而且我更新了2.4.3

### 重现步骤

1、点击设置
2、点击个性化
3.往下滑，打开隐藏设置
4.退出设置
4.摁f12恢复设置，打开后联机设置出现

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10100109/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10100110/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10100111/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10100112/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10100113/Log5.txt)

**Comment by yuanquanya** [comment]
我发现，直接f12也可以召唤联机

**Comment by WForst-Breeze** [comment]
已初步确认，的确直接按F12也可以使联机设置出现qwq

**Comment by yuanquanya** [comment]
这次又是删除了入口？

**Comment by LiuBinzhe** [comment]
神奇的事情

**Comment by yuanquanya** [comment]
感觉没彻底删

**Comment by yuanquanya** [comment]
要不然就是龙猫写了好几个

**Comment by LiuBinzhe** [comment]
好像只是把联机设置给隐藏了...

**Comment by yuanquanya** [comment]
确实

**Comment by LiuBinzhe** [comment]
额......龙猫不会这么大意吧

**Comment by yuanquanya** [comment]
确实

**Comment by yuanquanya** [comment]
但是要在一堆代码里找一些小东西确实不容易

**Comment by LiuBinzhe** [comment]
啊对对对

**Comment by Xiaoganghei** [comment]
6

**Comment by MinecraftSTL** [comment]
已核实，可能是用的之前写的隐藏功能，说不定之后要复用

**Comment by MinecraftSTL** [comment]
已核实，可能是用的之前写的隐藏功能，有可能是之后要复用这个界面

**Comment by dongge0210** [comment]
呢么f12开启联机要不要关掉呢

**Comment by MinecraftSTL** [comment]
> 

请仔细阅读，开启的是联机设置而不是联机

**Comment by Xiaoganghei** [comment]
emmm，所以这玩应是现在先删掉还是保留到新联机做完啊……

**Comment by LiuBinzhe** [comment]
先删掉吧.....毕竟里面是IOI和Hiper的联机设置......

**Comment by yuanquanya** [comment]
识别码 AC00-8115-2533-52E2
@LTCatt

**Comment by LTCatt** [comment]
你的解锁码：Riq9gZr1E3W5IMSs2OPu+wO3UFh7OH2R
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
