### ISSUE TITLE
添加"文本跟随窗口大小改变"选项

### ISSUE THREAD

**Issue by fangshifu233** [Hex-Dragon/PCL2#4690]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

1. 使用者或者用户启用此选项后,用户调整大小后文本跟随改变大小,例如用户放大2倍文本跟随放大2倍
2. 如果用户未启用此选项,用户调整大小文本不发生改变

### 原因

我习惯把启动器放大,但是字体和选项图标无法放大,看着好不舒服QAQ

**Comment by tangge233** [comment]
这样做的话 UI 适配会有亿点难度

**Comment by LTCatt** [comment]
技术上很难实现……

**Comment by JingHai-Lingyun** [comment]
WPF 不支持类似 CSS `vw` `vh` 单位（
