### ISSUE TITLE
整合包下载显示获取Forge详细信息失败 偶尔会出现MOD下载出错

### ISSUE THREAD

**Issue by HyaCatH** [Hex-Dragon/PCL2#4695]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

对整合包进行下载的时候显示如下画面 
<img width="584" alt="屏幕截图 2024-09-07 022115" src="https://github.com/user-attachments/assets/a0f16902-484d-4f5f-8d8d-6aec868d49bd">
错误信息如下：
游戏安装失败
→ 下载 Forge 36.2.20失败
→ 获取 Forge 详细信息失败
→ 获取结果失败（7，远程服务器返回错误: (403) 已禁止。，https://bmclapi2.bangbang93.com/forge/minecraft/1.16.5）
→ 远程服务器返回错误: (403) 已禁止。
   在 PCL.ModLoader.LoaderBase.WaitForExit(Object Input, LoaderBase LoaderToSyncProgress, Boolean IsForceRestart)
   在 PCL.ModDownloadLib._Closure$__35-0._Lambda$__0(LoaderTask`2 Task)
   在 PCL.ModLoader.LoaderTask`2._Closure$__13-0._Lambda$__0()
   在 PCL.ModDownload.DlSourceLoader[InputType,OutputType](LoaderTask`2 MainLoader, List`1 LoaderList, Boolean IsForceRestart)
   在 PCL.ModDownload.DlForgeVersionMain(LoaderTask`2 Loader)
   在 PCL.ModLoader.LoaderTask`2._Closure$__13-0._Lambda$__0()
   在 PCL.ModNet.NetGetCodeByRequestOnce(String Url, Encoding Encode, Int32 Timeout, Boolean IsJson, String Accept, Boolean UseBrowserUserAgent)
错误类型：System.Net.WebException

### 重现步骤

只要下载整合包 就显示下载失败，然后就会显示如上图所示画面

### 日志与附件

[Log2.txt](https://github.com/user-attachments/files/16911750/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16911751/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16911752/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16911754/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/16911756/Log1.txt)

**Comment by wuliaodexiaoluo** [comment]
>→ 获取结果失败（7，远程服务器返回错误: (403) 已禁止。，[https://bmclapi2.bangbang93.com/forge/minecraft/1.16.5）](https://bmclapi2.bangbang93.com/forge/minecraft/1.16.5%EF%BC%89)

请尝试不挂代理再试一次，BMCLAPI 因遭受大流量攻击暂时封禁了国外 IP

**Comment by allMagicNB** [comment]
> >→ 获取结果失败（7，远程服务器返回错误: (403) 已禁止。，[https://bmclapi2.bangbang93.com/forge/minecraft/1.16.5）](https://bmclapi2.bangbang93.com/forge/minecraft/1.16.5%EF%BC%89)
> 
> 请尝试不挂代理再试一次，这可能是 BMCLAPI 因遭受大流量攻击暂时封禁了国外 IP 导致的

你怎么确定当事人一定挂了代理？

**Comment by HyaCatH** [comment]
我是没有挂代理的 ，甚至我也尝试过挂代理，但是显示的画面是一样的，所以来进行反馈了

**Comment by HyaCatH** [comment]
> > → 获取结果失败（7，远程服务器返回错误: (403) 已禁止。，[https://bmclapi2.bangbang93.com/forge/minecraft/1.16.5）](https://bmclapi2.bangbang93.com/forge/minecraft/1.16.5%EF%BC%89)
> 
> 如果有挂代理，请尝试不挂代理再试一次，这可能是 BMCLAPI 因遭受大流量攻击暂时封禁了国外 IP 导致的

我是没有挂代理的 ，甚至我也尝试过挂代理，但是显示的画面是一样的，所以来进行反馈了

**Comment by HyaCatH** [comment]
> > → 获取结果失败（7，远程服务器返回错误: (403) 已禁止。，[https://bmclapi2.bangbang93.com/forge/minecraft/1.16.5）](https://bmclapi2.bangbang93.com/forge/minecraft/1.16.5%EF%BC%89)
> 
> 如果有挂代理，请尝试不挂代理再试一次，这可能是 BMCLAPI 因遭受大流量攻击暂时封禁了国外 IP 导致的

<img width="584" alt="屏幕截图 2024-09-07 132717" src="https://github.com/user-attachments/assets/23737a8b-f51c-4640-a20d-5dd809148919">
而且有的时候会卡在这个位置不动，否则就是显示我问题反映的那种报错

**Comment by wuliaodexiaoluo** [comment]
>而且有的时候会卡在这个位置不动，否则就是显示我问题反映的那种报错

这个是 #4697 
~但是龙猫可能不太想修~

**Comment by tangge233** [comment]
我这单独连接你们的日志中显示 403 的地址是可以正常访问的，莫非是访问太频繁给拒了？

**Comment by LTCatt** [comment]
![image](https://github.com/user-attachments/assets/c497c0fa-0b0b-4e34-b79d-8dbbcc033a55)
看起来是被 BMCLAPI 屏蔽了，不应该是我这里的问题……

**Comment by LTCatt** [comment]
@bangbang93

**Comment by bangbang93** [comment]
近期有攻击，屏蔽了一些ip段，过阵子会放出来

**Comment by HyaCatH** [comment]
我今天试了一下 可以下载了

**Comment by HyaCatH** [comment]
我今天试了一下 可以下载了
