### ISSUE TITLE
[Bug] 特定情况下下载 Forge 时会一直尝试请求官方源

### ISSUE THREAD

**Issue by wuliaodexiaoluo** [Hex-Dragon/PCL2#4697]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

特定情况下下载 Forge 时会一直尝试请求官方源，然后一直连不上，一直在那请求，这个时候下载速度显示为 0B/s，卡在那不动，也不报错也不干嘛，就只请求官方源，也没试试 BMCLAPI
很早之前就发现了，不过一直没时间弄
暂未发现重复

### 重现步骤

下载 Forge 时退掉代理或者裸连，有概率触发
~（怎么感觉有种故意触发的感觉）~

### 日志与附件

日志已经冲掉了.........

**Comment by allMagicNB** [comment]
冲掉了就再复现再发

**Comment by wuliaodexiaoluo** [comment]
[Log1.txt](https://github.com/user-attachments/files/16914116/Log1.txt)

第一次超时：6512 行，6s
第二次超时：6518 行，30s

如果浏览器请求一次 Forge Maven PCL 下载可以恢复，恢复下载使用的依旧是官方源

**Comment by LTCatt** [comment]
在多次超时后 PCL 会提高超时阈值，log 的情况也是在两个源之间轮换的，除了慢了点应该没啥问题？

**Comment by wuliaodexiaoluo** [comment]
>在多次超时后 PCL 会提高超时阈值，log 的情况也是在两个源之间轮换的，除了慢了点应该没啥问题？

额..... 这辈子装不完的那种慢吗？
