### ISSUE TITLE
当快速点击开始游戏与取消时，会弹出多个MC窗口，且关闭按键无法正常出现

### ISSUE THREAD

**Issue by PCL2ohhh** [Hex-Dragon/PCL2#4698]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

会有许多游戏窗口弹出，导致电脑变卡，并且不显示关闭按钮导致电脑变卡。

### 重现步骤

1.点击开始游戏
2.点击取消按钮
3.将以上步骤重复多次

### 日志与附件

[Log3.txt](https://github.com/user-attachments/files/16914309/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16914310/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16914314/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/16914316/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16914317/Log2.txt)

**Comment by allMagicNB** [comment]
闲的无聊是这样的

**Comment by JingHai-Lingyun** [comment]
进程未完全关闭导致的，电脑变卡是因为你的 RAM（内存）可用量不多了
依稀记得有个类似反馈来着，等我找找

**Comment by HeShanJR** [comment]
主要是获取Java成功后就无法取消启动了
