### ISSUE TITLE
主页重新加载失败

### ISSUE THREAD

**Issue by HeShanJR** [Hex-Dragon/PCL2#4699]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

主页重新加载失败

### 重现步骤

1.启动PCL2最新正式版2.8.6；
2.随便设置一个主页预设；
3.加载主页预设；
4.关闭pcl；
5.启动pcl；
6.等待主页加载完成；
7.刷新主页；
8.主页无论如何都不会加载完成。

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16915252/Log1.txt)
[Log3.txt](https://github.com/user-attachments/files/16915253/Log3.txt)
[Log2.txt](https://github.com/user-attachments/files/16915254/Log2.txt)
[Log4.txt](https://github.com/user-attachments/files/16915255/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16915256/Log5.txt)

**Comment by tangge233** [comment]
![image](https://github.com/user-attachments/assets/3a944957-9aef-47c1-85ed-9a817b54883d)

目前测试似乎已经正常了？

**Comment by allMagicNB** [comment]
![Screenshot_20240909_191340.jpg](https://github.com/user-attachments/assets/ad5a613b-ee06-4a50-95c8-21f1960210ab)

**Comment by Deep-Dark-Forest** [comment]
由于太长时间没有回复，先关了。
如果还有后续可以发到这里

**Comment by HeShanJR** [comment]
不是的，是刷新后主页是空白，等待30分钟内都没有出现提示框，左下角也没有提示，就是加载不出来。
