### ISSUE TITLE
在所有mod均为禁用的情况下从"全部"按钮切换至"禁用"按钮会突然出现"启用"按钮（启用(0)）

### ISSUE THREAD

**Issue by yizhi9jiyan9** [Hex-Dragon/PCL2#4701]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在所有mod均为禁用的情况下从全部切换至禁用会导致启用突然出现，但在全部mod启用的情况下其他tag栏无内容并不会出现上述情况

### 重现步骤

1、下载一些mod并全部禁用
2、点击"全部"
3、点击"禁用"
4、启用按钮会突然出现

### 日志与附件

https://github.com/user-attachments/assets/248260bd-96f1-4f9d-b172-7cc3213ea5eb

**Comment by JingHai-Lingyun** [comment]
……？你是否仍然认为这个是一个 Bug 且应当得到修复？
我看你自己关掉了反馈

**Comment by wuliaodexiaoluo** [comment]
>……？你是否仍然认为这个是一个 Bug 且应当得到修复？
我看你自己关掉了反馈

建议 Reopen 看看龙猫怎么说

**Comment by iPodtouch6557** [comment]
![image](https://github.com/user-attachments/assets/46931235-9c9c-4aef-9825-0e72976b6dcc)
![image](https://github.com/user-attachments/assets/dbb52880-6991-4ee5-a669-f8d34c479302)

**Comment by yizhi9jiyan9** [comment]
> ……？你是否仍然认为这个是一个 Bug 且应当得到修复？
> 我看你自己关掉了反馈

感觉在禁用的时候跳出启用或许是特意为之，以及没有动画导致这玩意很怪。或许添加一个动画更好（？）

**Comment by yizhi9jiyan9** [comment]
AECA-09A8-C86C-BDD7

**Comment by LTCatt** [comment]
你的解锁码：dVjJBjKFO+DMYioL9aUzIVVCeutDVr3Q
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
