### ISSUE TITLE
启动日志显示优化建议

### ISSUE THREAD

**Issue by Infdev-20100227** [Hex-Dragon/PCL2#4706]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

推荐将启动日志自动实时移动到最底部，而不是需要启动一遍后手动拉到最底再启动

### 原因

这项优化让我可以更方便地看到游戏在干嘛。
如果没有这项优化，我每次都必须启动一遍后手动拉到最底再启动，让操作变得很麻烦。

**Comment by LTCatt** [comment]
试了试，如果在启动过程中想翻一翻，这反而会把你一直拽到最下面，更难受了……还是算了……

**Comment by hejiehao** [comment]
做个自动滚动的选项？
