### ISSUE TITLE
对mod中的fabric.mod.json name重命名问题

### ISSUE THREAD

**Issue by Xiaohanmua** [Hex-Dragon/PCL2#4714]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

PCL2在mod管理界面时，对mod中的fabric.mod.json文件中的name进行更改时 PCL2的mod管理中的对此mod将会出错 即使改回原本modname此报错也有概率无法消除 报错为mod正由另一进程使用，因此改进程无法访问 PCL重启后此报错消失

### 重现步骤

PCL2在mod管理界面时，对mod中的fabric.mod.json文件中的name进行更改时 PCL2的mod管理中的对此mod将会出错 即使改回原本modname此报错也有概率无法消除 报错为mod正由另一进程使用，因此改进程无法访问 PCL重启后此报错消失

### 日志与附件

[Log2.txt](https://github.com/user-attachments/files/16990884/Log2.txt)
[Log1.txt](https://github.com/user-attachments/files/16990933/Log1.txt)

**Comment by Xiaohanmua** [comment]
> ### 检查项
> * [x]  我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。
> 
> ### 描述
> PCL2在mod管理界面时，对mod中的fabric.mod.json文件中的name进行更改时 PCL2的mod管理中的对此mod将会出错 即使改回原本modname此报错也有概率无法消除 报错为mod正由另一进程使用，因此改进程无法访问 PCL重启后此报错消失
> 
> ### 重现步骤
> PCL2在mod管理界面时，对mod中的fabric.mod.json文件中的name进行更改时 PCL2的mod管理中的对此mod将会出错 即使改回原本modname此报错也有概率无法消除 报错为mod正由另一进程使用，因此改进程无法访问 PCL重启后此报错消失
> 
> ### 日志与附件
> [Log2.txt](https://github.com/user-attachments/files/16990884/Log2.txt) [Log1.txt](https://github.com/user-attachments/files/16990933/Log1.txt)

**Comment by allMagicNB** [comment]
所以呢，你想让 PCL 在文件被占用时杀掉占用的进程然后再读取？

**Comment by Xiaohanmua** [comment]
> 所以呢，你想让 PCL 在文件被占用时杀掉占用的进程然后再读取？
以为这是bug 抱歉

**Comment by Xiaohanmua** [comment]
> 这应该是预期的行为。我猜您一定是使用存档程序打开了 .jar 文件并修改了目标文件。
> 
> 保存文件更改后，PCL 将自动检测文件更改并重新读取文件。此时，您的存档程序不应该被关闭，对吧？所以_另一个进程_实际上是你的存档器。
> 
> 如果我错了，请告诉我。
> 
> 这应该是预期的行为。我猜你肯定是使用一款压缩软件打开了 .jar 文件，并对目标文件进行了修改。
> 
> 当文件的修改被保存时，PCL 会自动检测到文件的变化并重新读取文件，这时候你的压缩软件应该还没关闭，对吧？所以 “另一进程” 其实就是你的压缩软件。
> 
> 如果我的判断有误，请告诉我。

确实是这样的 以为这是bug 抱歉  That's true, thought it was a bug, sorry
