### ISSUE TITLE
自动安装1.21.1版本forge会卡住或安装失败

### ISSUE THREAD

**Issue by xwga436213** [Hex-Dragon/PCL2#4715]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

自动安装1.21.1forge所有版本都会卡住

### 重现步骤

1、点击下载
2、点击自动安装
3、点击1.21.1
4、点击forge
5、点击开始安装

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16992339/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16992344/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16992348/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16992350/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16992351/Log5.txt)

**Comment by tangge233** [comment]
这个哥们的网络死活下载不下来这个文件……
`https://maven.minecraftforge.net/net/minecraftforge/forge/1.21.1-52.0.15/forge-1.21.1-52.0.15-shim.jar`

总结：下载源还没同步更新，官方源难以连接。过几天就好了。

**Comment by wuliaodexiaoluo** [comment]
>这个哥们的网络死活下载不下来这个文件……

卡下载是 #4697 
目前已知的: Forge Maven 和 Modrinth 一样，有时候莫名其妙的连不上但是浏览器访问后又能下载了。。。。

**Comment by allMagicNB** [comment]
> >这个哥们的网络死活下载不下来这个文件……
> 
> 卡下载是 #4697 
> 目前已知的: Forge Maven 和 Modrinth 一样，有时候莫名其妙的 PCL 下不了但是浏览器访问后又能下载了。。。。
> 

这个文件压根就不存在，手动访问也是 404。

**Comment by LTCatt** [comment]
https://maven.minecraftforge.net/net/minecraftforge/forge/1.21.1-52.0.16/forge-1.21.1-52.0.16-shim.jar
所对应的
https://bmclapi2.bangbang93.com/maven/net/minecraftforge/forge/1.21.1-52.0.16/forge-1.21.1-52.0.16-shim.jar
报 404

@bangbang93

**Comment by bangbang93** [comment]
shim是个什么文件？是在哪里出现的？

**Comment by LTCatt** [comment]
![image](https://github.com/user-attachments/assets/67fe1758-e3ae-40d4-a63d-04d27df310f9)

新版 Forge 安装器要求的，安装器 json 里就有

**Comment by LTCatt** [comment]
> https://maven.minecraftforge.net/net/minecraftforge/forge/1.21.1-52.0.16/forge-1.21.1-52.0.16-shim.jar 所对应的 https://bmclapi2.bangbang93.com/maven/net/minecraftforge/forge/1.21.1-52.0.16/forge-1.21.1-52.0.16-shim.jar 报 404
> 
> @bangbang93

这个文件报 404 是因为 BMCLAPI 自动把
https://bmclapi2.bangbang93.com/maven/net/minecraftforge/forge/1.21.1-52.0.16/forge-1.21.1-52.0.16-shim.jar
重定向到了
https://bmclapi2.bangbang93.com/maven/net/minecraftforge/forge/1.21.1-52.0.16/forge-1.21.1-52.0.16-shim-universal.jar

所以应该是 BMCLAPI 的某个替换规则导致的……

**Comment by bangbang93** [comment]
已修复
