### ISSUE TITLE
很罕见的情况下，切换设置分页面失败

### ISSUE THREAD

**Issue by YIEMM** [Hex-Dragon/PCL2#4721]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

无法打开设置页面，重新打开版本设置即可恢复
![F VW 8RJ$E @FB8F(XEO`W6](https://github.com/user-attachments/assets/af9a2467-894c-4a5b-9dc7-cc10ddf4c4a3)

### 重现步骤

1、点击版本设置
2、点击设置

### 日志与附件

[PCL.zip](https://github.com/user-attachments/files/17001406/PCL.zip)

**Comment by FQO3** [comment]
我成功复现了bug！
![image](https://github.com/user-attachments/assets/29c2e291-fa7b-4864-8338-9c3f67fced03)

**Comment by FQO3** [comment]
不行，捣鼓一个小时还是只能复现一次，后面尝试用鼠标宏点击按钮，已经把按钮点击时机卡到一致也无法再次复现
![image](https://github.com/user-attachments/assets/2021025a-c01c-4297-b730-b32340cd93df)
[Log1.txt](https://github.com/user-attachments/files/17088166/Log1.txt)
