### ISSUE TITLE
PCL2预览版随机报字符串错误。

### ISSUE THREAD

**Issue by bii20081Aztec** [Hex-Dragon/PCL2#4726]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

这个bug纯粹就是在游戏关闭时随机触发的，使用的是PCL2预览版或测试版。

### 重现步骤

此bug为随机bug，使用预览版就能大概率触发。

### 日志与附件

 
![屏幕截图 2024-09-14 212940](https://github.com/user-attachments/assets/0e241e5d-e1ac-4e4c-a2cd-78b136167e3c)

**Comment by wyc-26** [comment]
请上传日志文件
初步判断此并非 PCL 本身的问题

**Comment by tangge233** [comment]
看起来是音频设备改动导致的

**Comment by JingHai-Lingyun** [comment]
#1753 #2348，你的音频设备发生了改动，这是 NAudio 库的问题
