### ISSUE TITLE
PCL时不时自动重置

### ISSUE THREAD

**Issue by TIMER-err** [Hex-Dragon/PCL2#4728]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我发现我的PCL会自动丢失数据，具体症状为：PCL的识别码会在BE15-F5BF-C439-71B4和B55A-3D21-59D6-0DC6之间反复横跳，导致我的正版登录状态，解锁的主题以及快照版解锁状态重置。
这是BE15-F5BF-C439-71B4的解锁码：
iIOi1W8L8N3b6p3InOJPUJY/HUnNULsUCyofnP1HBKl56A2R5j8Gd5gEyVW47WgOw+21y/UqHvkT5B/paQ9yHA==
这是B55A-3D21-59D6-0DC6的解锁码：
iN0NSttiPIB+nmC5Qu+bBBFJxGG7nQRDJ7fV5aYq71d66SG1sjL9VmE9JNUOIu3++3TL3g4IHZ989Iw4bjGDkg==

启动器版本：Snapshot 2.8.4 (333)
最后附上启动器本体：
[Plain Craft Launcher 2.zip](https://github.com/user-attachments/files/17004000/Plain.Craft.Launcher.2.zip)

### 重现步骤

也许在我电脑上才会复现
每隔一段时间打开PCL就发生上述状况，也许需要重启设备

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/17004001/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17004002/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17004003/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17004004/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17004005/Log5.txt)

**Comment by JingHai-Lingyun** [comment]
非常奇怪…… Log1 和 Log2 中报告了两个不同的识别码，并都出现了解码错误
先给龙猫看看，但这可能是由于你的设备硬件变动带来的

**Comment by allMagicNB** [comment]
你是不是删注册表了？

**Comment by LTCatt** [comment]
设备硬件变动导致，非启动器问题

**Comment by TIMER-err** [comment]
之前改过mac网卡地址，但是最近没有硬件变动，也没有删注册表
