### ISSUE TITLE
不筛选时（包括来源时）有几率无法访问modrinth上的mod

### ISSUE THREAD

**Issue by WangYiBen0** [Hex-Dragon/PCL2#4729]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

版本：快照2.8.6 (335.0)
rt，不筛选时有时无法访问modrinth上的mod
但是在浏览器上访问上述网站完全正常，在HMCL中也能正常下载，启用筛选后也是正常的

### 重现步骤

1、在mod页面点击mod版本
2、点击保存

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/17004684/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17004685/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17004686/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17004687/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17004688/Log5.txt)

**Comment by xwga436213** [comment]
重新下载一次就好了

**Comment by tangge233** [comment]
你的网络环境不佳，无论是官方源还是镜像源都容易连接超时……

**Comment by WorldHim** [comment]
请确认你的网络环境没有问题

**Comment by WangYiBen0** [comment]
> 请确认你的网络环境没有问题

我在描述中写了

> 但是在浏览器上访问上述网站完全正常，在HMCL中也能正常下载

无网络环境问题

**Comment by wuliaodexiaoluo** [comment]
试试挂个代理？或许可能改善此问题？

**Comment by WangYiBen0** [comment]
> 试试挂个代理？或许可能改善此问题？

当时挂着[Watt Toolkits](https://github.com/BeyondDimension/SteamTools/)的System代理

**Comment by WangYiBen0** [comment]
其他代理模式也试过了

**Comment by WangYiBen0** [comment]
> 重新下载一次就好了

我已经重新启动PCL并再次试了不知道多少次了，无效

**Comment by WangYiBen0** [comment]
哦，重新启动PC后可用，但是仍有问题：在不筛选的情况下无法访问modrinth，但是筛选后可以正常访问并下载

**Comment by LTCatt** [comment]
> 哦，重新启动PC后可用，但是仍有问题：在不筛选的情况下无法访问modrinth，但是筛选后可以正常访问并下载

请补充这个情况的 log。
考虑可能是 #4334，也可能是单纯的网络抽搐……

**Comment by WangYiBen0** [comment]
好的，谢谢
