### ISSUE TITLE
Windows 7 启动PCL时窗口无法在可操作范围显示

### ISSUE THREAD

**Issue by XiaoPengqwq** [Hex-Dragon/PCL2#473]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我是一名**Windows7** 用户，之前每次启动PCL时PCL窗口都可以显示在屏幕中央，但是自从上个月开始，PCL启动器窗口无法在**Windows7** 中显示到正确的位置（即屏幕外），每次需要重新启动PCL主程序才能显示到正确的位置，虽然这个功能并不影响正常操作，但是很影响心情（破大防），建议看一下是不是启动时坐标搞错了qwq。感谢

### 重现步骤

1、在Windows 7 操作系统中第一次启动（一定是开机首次启动）
2、在菜单缩略图中可看到启动器样式，但在可操作界面内无法看到（即屏幕外）

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10100489/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10100491/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10100492/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10100493/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10100494/Log5.txt)

**Comment by LTCatt** [comment]
加我 QQ 1043137532，这个可能得远程处理……

**Comment by XiaoPengqwq** [comment]
刚刚重启了一下，发现这是一个概率性问题...

**Comment by XiaoPengqwq** [comment]
这就有点玄学了

**Comment by WForst-Breeze** [comment]
> 刚刚重启了一下，发现这是一个概率性问题...

请问您现在是否能复现此bug？如果暂时不能我这边就先加忽略 label 了，等什么时候可以复现了或许你可以再联系龙猫进行处理qwq

**Comment by XiaoPengqwq** [comment]
很抱歉，我现在暂时无法复现此问题，很抱歉为你们带来的问题，当未来我出现此问题时将会联系你们                                                   --小彭qwqXiao_Peng_qwq bilibili
