### ISSUE TITLE
无法访问modrinth/加载不了mod标题图片

### ISSUE THREAD

**Issue by wuqinlanjian** [Hex-Dragon/PCL2#4730]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

提示”无法连接到 Modrinth，所以目前仅显示了来自 CurseForge 的内容，请尝试使用 VPN 或加速器以改善网络。“
但modrinth可正常访问并下载
![image](https://github.com/user-attachments/assets/ccc9545f-f99d-4a68-b374-8f13bb0eed26)
有些mod下载页面不会显示标题图片
![image](https://github.com/user-attachments/assets/05c33fee-c48d-43e0-89b4-2b8ac3db5954)

### 重现步骤

1、点击下载
2、点击Mod
3、往下滚

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/17004727/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17004728/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17004729/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17004730/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17004731/Log5.txt)

**Comment by hejiehao** [comment]
🤔难道说换了 UA 还是不起作用？

**Comment by tangge233** [comment]
![image](https://github.com/user-attachments/assets/d27b4762-79cd-4eee-9e94-4f5f71ccbe42)

可能是一分钟内某个区域的请求数量太多了？毕竟国内是 NAT 环境。

**Comment by xxtg666** [comment]
有点玄学，我这里能下载modrinth的mod但是加载不出来图标

**Comment by WForst-Breeze** [comment]
应是 #4734 造成的问题？

**Comment by LTCatt** [comment]
Reopen #4334

**Comment by wuqinlanjian** [comment]
识别码 7AFF-EB12-A1F5-C100
@LTCatt

**Comment by Deep-Dark-Forest** [comment]
？应该是这 issue 应该被判定为重复了，不过 #4743 的 Merge 导致了这个 issue 被意外地 Close as completed。如果是这样的话，您无法获取活跃橙。

**Comment by LTCatt** [comment]
bot 挂错了，sry

**Comment by tangge233** [comment]
非常抱歉写错了 Close 语句导致了错误的判定

![399C0455AF4240E5D57C532CD5E2CB13](https://github.com/user-attachments/assets/90db0e4b-17d2-4ac1-9954-cb471d8a409d)
