### ISSUE TITLE
删除Mod 出现未知错误:未将对象引用设置到对象的实例。 在 PCL.PageVersionMod.DeleteMods(IEnumerable'1 ModList) 错误类型:System.NullReferenceException

### ISSUE THREAD

**Issue by XueLiMC** [Hex-Dragon/PCL2#4731]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我就是同时选择多个模组然后点删除就出现这个错误

### 重现步骤

1、点击版本设置
2、点击Mod管理
3、选择2个模组点击删除

### 日志与附件

[Log4.txt](https://github.com/user-attachments/files/17005124/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17005125/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/17005126/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17005127/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17005128/Log3.txt)

**Comment by Ad-closeNN** [comment]
#4691
