### ISSUE TITLE
Minecraft出现错误

### ISSUE THREAD

**Issue by xiaopai520** [Hex-Dragon/PCL2#4732]
### 检查项

- [ ] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃基本不是 PCL 的原因，请 **不要** 提交反馈。你可以在论坛或社区找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用 HMCL 启动，HMCL 没有出现问题。** 如果 HMCL 也无法启动就不是 PCL 导致的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

游戏一启动就马上弹出mine craft出现错误.

### PCL 错误报告、日志与附件

[17:35:31.447] [Download] 2001866021_168 194#：开始，起始点 0，https://bmclapi2.bangbang93.com/neoforge/meta/api/maven/details/releases/net/neoforged/neoforge
[17:35:31.472] [Download] -1798645995_172 193#：出错，远程服务器返回错误: (403) 已禁止。
   在 PCL.ModNet.NetFile.Thread(NetThread Info)
错误类型：System.Net.WebException

### HMCL 启动脚本

[游戏崩溃前的输出.txt](https://github.com/user-attachments/files/17005421/default.txt)
![屏幕截图 2024-09-15 184212](https://github.com/user-attachments/assets/04505bfa-68f9-4dbc-b38c-10ed90f35ce6)

**Comment by JingHai-Lingyun** [comment]
不知道为什么，我无法查看你的日志，请在崩溃的窗口中导出错误报告，并将 ZIP 发上来

**Comment by allMagicNB** [comment]
描述仅几字，汝文学大师？
日志不给全，问题不解决。

**Comment by HomoobyDX** [comment]
疑似被93封IP，如果你用HMCL启动游戏/下载游戏会不会出现这种情况

**Comment by LTCatt** [comment]
请上传 HMCL 的启动脚本。

**Comment by SALTWOOD** [comment]
看到 403……估计是 BMCLAPI 把你 IP ban 了，尝试黑魔法、重启路由器，或者更换版本列表获取策略
