### ISSUE TITLE
关于pcl2的1.8.9视频界面无法正常调整

### ISSUE THREAD

**Issue by Ling-qwq-T** [Hex-Dragon/PCL2#4733]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

forgr版的1.8.9启动后，游戏不在屏幕正中间出现，而是在右下角。全屏后，界面和字体模糊，视频界面固定成 中和自动之间（这对习惯了视频界面为中的PVP玩家非常不友好，非常不适应）。并且在游戏内也更加卡顿，人物名称和方块也发生了模糊。不知道是不是电脑的问题，但是我的分辨率和放大率一直没调过（1920*1080，150%）

### 重现步骤

1.打开pcl2
2.pcl2自动更新（pcl2设置里默认的）
3.启动1.8.9forge
4.游戏启动，并发生模糊

### 日志与附件

[Log3.txt](https://github.com/user-attachments/files/17005510/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17005512/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17005513/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/17005514/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17005515/Log2.txt)

**Comment by Ling-qwq-T** [comment]
![1](https://github.com/user-attachments/assets/5eecd10a-9453-4d04-b54e-5e4d4e2ccd6f)
这个是默认进入游戏 视频设置-其他 的图片
因为我不理解 全屏模式默认 是什么意思

**Comment by Ling-qwq-T** [comment]
@3gf8jv4dv 
这个是默认进入游戏 视频设置-其他 的图片
因为我不理解 全屏模式默认 是什么意思
![1](https://github.com/user-attachments/assets/11864023-0bd6-46cd-b56d-796b7c0c3ee0)

**Comment by Ling-qwq-T** [comment]
@3gf8jv4dv 是的
![1](https://github.com/user-attachments/assets/085f8f42-4658-4e07-9006-8cab58b822af)

**Comment by Ling-qwq-T** [comment]
@3gf8jv4dv 我发现了一个奇怪的现象，当我window设置里缩放调成125%或者100%是正常的（但设置里是这样说的：150%（推荐））

**Comment by Ling-qwq-T** [comment]
@3gf8jv4dv 但是我开全屏会有bug（只能最大化窗口）并且全屏后我无法看到，但是截屏却可以。
Tips：全屏时视屏画面似乎是正常的，但是显示不正常
这是我看到的：
![全屏](https://github.com/user-attachments/assets/bbcd8120-6168-4ebf-8753-f6171a1a5a4a)
这是F2截屏的：
![2024-09-17_08 56 00](https://github.com/user-attachments/assets/af4425c4-c9cc-43ec-ae73-312347e4a9af)

**Comment by Deep-Dark-Forest** [comment]
能否用其他启动器（比如 HMCL）启动相同的游戏，看看会不会发生这个问题？

**Comment by Ling-qwq-T** [comment]
我尝试过了

**Comment by Ling-qwq-T** [comment]
重装游戏也没有用

**Comment by Deep-Dark-Forest** [comment]
不，我是指用 HMCL 之类的其他启动器启动相同的游戏版本文件夹

**Comment by Ling-qwq-T** [comment]
> 不，我是指用 HMCL 之类的其他启动器启动相同的游戏版本文件夹

不，我确实是使用HMCL尝试启动一样的1.8.9版本

**Comment by Ling-qwq-T** [comment]
> 不，我是指用 HMCL 之类的其他启动器启动相同的游戏版本文件夹

但是有个奇怪的地方，我的HMCL仅仅检测到了我的外部文件夹（文件夹->version-> 1.8.9-forge 才是真正的版本）随后我尝试了多种办法（HMCL再下载一次1.8.9forge）（PCL2在下载一次1.8.9forge）等

**Comment by Ling-qwq-T** [comment]
> > 我发现了一个奇怪的现象，当我window设置里缩放调成125%或者100%是正常的（但设置里是这样说的：150%（推荐））
> 
> 我尝试调整此设置，但无法在仅安装 Forge 和 OptiFine 的情况下重现该行为。 我尝试过调整这个设置，但我在仅安装 Forge 和 OptiFine 的情况下无法复现这个现象。
> 
> 你先调整回 150%，打开游戏进入单人世界，切换到全屏后，按 F3 打开调试界面，查看右侧“Display”后面的值。如果您愿意，可以按 F2 截取屏幕截图并上传该屏幕截图。 你先调回 150%，打开游戏进入一个单人世界，切换全屏后，按 F3 打开调试屏幕，看下右边的 “Display” 后面的数值是多少。如果愿意，你可以按 F2 截图然后把这个截图传上来。

但是我开全屏会有bug（只能最大化窗口）并且全屏后我无法看到，但是截屏却可以。
Tips：全屏时视屏画面似乎是正常的，但是我这边显示不正常
这是我看到的：
全屏：
![全屏](https://github.com/user-attachments/assets/ba944874-5de6-45ef-8757-4b601460dfef)
这是F2截屏的：
![2024-09-17_08 56 00](https://github.com/user-attachments/assets/19f71e96-0883-4c2b-a319-602eea46d500)

**Comment by LTCatt** [comment]
这看起来更像是 Forge 或者 Windows 的问题……
如果 HMCL 没有这个问题的话，请使用同一个 Java 和 MC 版本，在 PCL 和 HMCL 分别导出启动脚本并上传。

**Comment by SALTWOOD** [comment]
全屏会跑到右下角我记得我见过（Forge的bug好像），尝试原版、其他电脑上能否复现

**Comment by Ling-qwq-T** [comment]
@SALTWOOD 是的，确实会跑到右下角

**Comment by Ling-qwq-T** [comment]
@LTCatt HMCL启动也有问题（悲

**Comment by Ling-qwq-T** [comment]
[PCL和HMCL启动脚本(bat在github会被和谐，所以压缩了).zip](https://githu.com/user-attachments/files/17089850/PCL.HMCL.bat.github.zip)
@LTCatt

**Comment by LTCatt** [comment]
那就没法了（瘫
