### ISSUE TITLE
[优化] 支持 webp 格式图标

### ISSUE THREAD

**Issue by wuliaodexiaoluo** [Hex-Dragon/PCL2#4734]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

虽然感觉可能麻烦但是希望支持下

### 原因

根据社区观察，Modrinth 的 Mod 图标中使用 webp 的占比正在上升，其中包括一些较火的 Mod
<details>
<summary>图片</summary>

![7)G6NG22~%`%EDK10P2F8@R](https://github.com/user-attachments/assets/1ef69c22-915a-4d83-80c8-632937340ee2)

</details>

**Comment by wuliaodexiaoluo** [comment]
或许新功能更合适？

**Comment by hejiehao** [comment]
疑似波及到了 #4730

**Comment by wuliaodexiaoluo** [comment]
>疑似波及到了 https://github.com/Hex-Dragon/PCL2/issues/4730

这种二合一的 Issue 分开比较好，免得龙猫漏看了

**Comment by allMagicNB** [comment]
我的评价是：https://github.com/Hex-Dragon/PCL2/issues/3115#issuecomment-1953030965

**Comment by allMagicNB** [comment]
并且 WebP 不是位图吗？本质上也就是压缩了的 PNG 而已。

**Comment by WForst-Breeze** [comment]
svg 支持：#553 #1409 #3115

但是这个问题范围已经影响到了正常使用，那就先初步确认一下 (｡•ᴗ-)

**Comment by LTCatt** [comment]
https://github.com/Hex-Dragon/PCL2/pull/4743#issuecomment-2352346043
