### ISSUE TITLE
关于"关闭Minecraft“按键

### ISSUE THREAD

**Issue by ThendJyc** [Hex-Dragon/PCL2#4735]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

PCL在启动游戏后，"启动"界面右下角会出现一个可以关闭所有正在运行的Minecraft的按键：
<img width="126" alt="image" src="https://github.com/user-attachments/assets/10145320-f0a2-462e-ad91-2b208676a344">
每次多开的时候用就很方便
结果有一次，我玩的时候一不小心把PCL关了
再打开就发现这个按键没了
于是啊
我就先用PCL启动了一个游戏
把PCL重启了之后再启动一个游戏
然后点击"关闭MInecraft"按键
发现只有最后一个启动的Minecraft关闭了
。。。
我不知道每次开启PCL检索一次Minecraft进程会不会卡顿啊
但是
就是
手动关20多个Minecraft真的很麻烦...

### 原因

能改的话尽量改一下吧
我觉得...

**Comment by Ad-closeNN** [comment]
- #1243 ？

**Comment by ThendJyc** [comment]
就算不能结束在开启PCL前启动的Minecraft或者其他启动器启动的Minecraft，好歹也不要在关闭PCL时把记录的Minecraft进程删除吧。

**Comment by Deep-Dark-Forest** [comment]
重启 PCL 以后 PCL 不会显示关闭 Minecraft 的按钮，参见 #1243
