### ISSUE TITLE
一些在窗口最底部的提示卡片可能会出现动画不加载的问题

### ISSUE THREAD

**Issue by wuqinlanjian** [Hex-Dragon/PCL2#4739]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

一些在窗口最底部的提示卡片可能会出现动画不加载的问题
https://wwsn.lanzouw.com/i6zB52a3c3of
具体视频下载链接

### 重现步骤

1、找到一个位于页面底部的提示卡片（如版本设置-设置-高级启动选项）
2、点击它

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/17008735/Log1.txt)
（只有一个log1）

**Comment by WForst-Breeze** [comment]
https://github.com/user-attachments/assets/56c6ae3a-8140-4f35-8705-21c3dc262fbb

如上，底部卡片展开时无动画
