### ISSUE TITLE
"千万别点"中标题栏显示错误

### ISSUE THREAD

**Issue by YeluoSoot** [Hex-Dragon/PCL2#4741]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

（话说这玩意发现了有啥用吗）
*本次反馈由于本人运气过差无法在"千万别点"重现"眼瞎白“效果
"千万别点"中触发”眼瞎白“效果后，更换”玄素黑“可以使标题栏正常变为黑色，其他主题未出现
*Log3.txt中为本次操作
![92WNS(CNCZ4F8~ZK PRH2IC](https://github.com/user-attachments/assets/9af4d6e8-f7e9-4119-b823-fca862b218a7)
![@J76@UK}82EY%QLT)UM83DP](https://github.com/user-attachments/assets/f245adc4-30d0-4f6e-b654-c613ef1b2152)

### 重现步骤

1、点击设置-百宝箱
2、点击千万别点-确定

### 日志与附件

[Log2.txt](https://github.com/user-attachments/files/17009119/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17009120/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17009121/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17009123/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/17009124/Log1.txt)

**Comment by tangge233** [comment]
![image](https://github.com/user-attachments/assets/fff0480b-e04e-435a-9668-766b977012e7)

**Comment by YeluoSoot** [comment]
对不起我是傻逼

**Comment by YeluoSoot** [comment]
对不起这个怎么删

**Comment by YeluoSoot** [comment]
对不起没看到抱歉这个怎么删

**Comment by YeluoSoot** [comment]
对不起在这里打扰到大家的时间对不起

**Comment by tangge233** [comment]
![image](https://github.com/user-attachments/assets/14e82e07-6523-47cd-9f9f-7d1c1254febf)

**Comment by YeluoSoot** [comment]
好的已经关闭了再次抱歉在这里打扰到各位再见
