### ISSUE TITLE
Curseforge模组应该使用爬虫而非官方API

### ISSUE THREAD

**Issue by cxim-xh** [Hex-Dragon/PCL2#4746]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

由于Curseforge的API时常出现查询结果缺失，建议配合使用爬虫而非仅依赖于官方API。爬取网页https://www.curseforge.com/minecraft/mc-mods/xxx/files/all以免提供所有可达的版本列表，在无法爬取时显示提示，以便使用浏览器人工爬取

### 原因

这项优化让我可以更方便地搜寻模组的历史版本。需要历史版本的模组的情况非常常见，尤其是在制作一些复杂的整合包时。
没有这项优化，我每次都必须去Curseforge网页上看，不仅让操作变得很麻烦，而且一不小心忘了可能就得多搞半天（我在这个问题已经浪费了至少20个小时的时间了）。
如果同意这些优化，我可能会提交一个PR来减少相关功能实现的工作量。
![image](https://github.com/user-attachments/assets/64a97504-5992-4187-86b9-5f93919c903e)

**Comment by zkitefly** [comment]
我认为龙猫不可能会接受🤔

**Comment by LTCatt** [comment]
这个玩意儿会大大增加 CurseForge API 的调用量（
