### ISSUE TITLE
自动分配的内存与全局设置不一致

### ISSUE THREAD

**Issue by hxabcd** [Hex-Dragon/PCL2#4752]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在启动页的 “版本设置-设置-游戏内存" 中，如果使用 “**自动配置**” 进行分配，会分配 **14.7 GB**，而选择 “**使用全局设置**” 时（此时全局配置为 “自动配置”）则会分配 **11.8 GB**，两个内存分配**不一致**，认为自动内存分配的逻辑存在一些不合理处。可能是全局配置的自动分配未按照安装的 Mod 量进行分配，而版本设置内则是根据安装的 Mod 量进行分配的。

全局设置：
![{673EAEE6-8BCE-4230-9867-A65B1CFB6C59}](https://github.com/user-attachments/assets/f9fb7422-ac03-4b77-992f-cb3b1ec6313b)

版本设置中选择 "使用全局设置“ 时：
![{8E863321-6029-4190-8F9D-7E6A285486BA}](https://github.com/user-attachments/assets/b02174b1-ecb5-4ce5-a8ec-4afa1889093d)

版本设置中选择 "自动配置“ 时：
![{CBC5E21B-3C4C-4113-944F-5E280CE9AB28}](https://github.com/user-attachments/assets/b4b38acc-0ba5-49e7-b1d2-7ad6aaa04095)

### 原因

导致全局设置选择的自动配置失去意义，无法正确地根据 mod 数量自动分配内存；同时也可能使内存需求小的分配了更多的内存，而内存需求大的分配了更少的内存。

**Comment by Deep-Dark-Forest** [comment]
这好像可以算 bug……？

**Comment by WorldHim** [comment]
没什么问题吧…

**Comment by tangge233** [comment]
看了眼代码，内存自动配置在单独版本和全局的计算方式有细微差别。
给龙猫看看再说（
<details>

这是全局的

![image](https://github.com/user-attachments/assets/7c7a9284-86ea-47ef-ad18-330987ab2d2a)

这是单独版本的

![image](https://github.com/user-attachments/assets/f728c93f-2e3d-4dcd-ab4f-2497a7740bdf)

</details>

**Comment by hxabcd** [comment]
9EEE-83F1-7375-C91F

**Comment by LTCatt** [comment]
你的解锁码：xB2P+3xVf4fgPXqjgLR8zUWTPbNfTUcn
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
