### ISSUE TITLE
用pcl2删除mod时提示出现未知错误：未将对象引用设置到对象的实例。

### ISSUE THREAD

**Issue by blacknail049** [Hex-Dragon/PCL2#4755]
### 检查项

- [ ] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃基本不是 PCL 的原因，请 **不要** 提交反馈。你可以在论坛或社区找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用 HMCL 启动，HMCL 没有出现问题。** 如果 HMCL 也无法启动就不是 PCL 导致的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

用pcl2的删除按钮的时候提示这个，但是模组似乎删除成功

出现错误
删除Mod出现未知错误：未将对象引用设置到对象的实例。
PCL.PageVersionMod.DeleteMods(IEnumerable'1 ModList)
错误类型：System.NullReferenceException
是否反馈此问题？如果不反馈，这个问题可能永远无法得到解决！
              反馈                                                   取消

### PCL 错误报告、日志与附件

[Log1.txt](https://github.com/user-attachments/files/17026497/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17026498/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17026499/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17026500/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17026501/Log5.txt)

**Comment by Ad-closeNN** [comment]
#4691
