### ISSUE TITLE
启动1.21时错误的认为游戏正确启动

### ISSUE THREAD

**Issue by jocemod** [Hex-Dragon/PCL2#4756]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

左下角同时弹出检测到 "检测到 Minecraft 出现错误，错误分析已开始……"和"1.21-Fabric 启动成功！"
难以复现

### 重现步骤

1、启动游戏
2、游戏崩溃
3、左下角同时弹出检测到 "检测到 Minecraft 出现错误，错误分析已开始……"和"1.21-Fabric 启动成功！"

### 日志与附件

[Log3.txt](https://github.com/user-attachments/files/17026547/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17026548/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17026549/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/17026550/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17026551/Log2.txt)

**Comment by WorldHim** [comment]
预期现象
