### ISSUE TITLE
删除 Mod 出现末知错误:未将对象引用设置到对象的实例。在PCL.PageVersionMod.DeleteMods(lEnumerable 1 ModList)错误类型:System.NullReferenceException

### ISSUE THREAD

**Issue by yusheng935** [Hex-Dragon/PCL2#4757]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

游戏内材质错误，退出尝试重装mod，删除时提示  “删除 Mod 出现末知错误:未将对象引用设置到对象的实例。在PCL.PageVersionMod.DeleteMods(lEnumerable 1 ModList)错误类型:System.NullReferenceException”
mod为机械动力fabric1.20.1

### 重现步骤

点击删除mod

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/17027693/Log1.txt)

**Comment by Ad-closeNN** [comment]
#4691
