### ISSUE TITLE
在检测到相同mod时询问是否删除旧版本

### ISSUE THREAD

**Issue by ThendJyc** [Hex-Dragon/PCL2#4762]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

因为PCL下载缓慢，所以一般会选择直接在浏览器或下载器下载来更新模组，所以当检测到相同模组时，可以询问是否删除较旧的版本

### 原因

PCL下载实在是太慢了啊啊啊啊

**Comment by ThendJyc** [comment]
或者也可以加一个打开模组更新下载地址的选项

**Comment by tangge233** [comment]
#4587

**Comment by ThendJyc** [comment]
但是现在PCL已经支持Mod更新了啊
没什么技术限制了

**Comment by xxtg666** [comment]
PCL下载很慢吗（？
~我一直把它当做高速下载器用来着~

**Comment by xxtg666** [comment]
龙猫在 8 月 25 日 对 #4587 的回复中说 
> 技术原因无法实现准确检测，试着做过，很容易误报漏报（

这个日期已经是在 mod 更新功能做出来之后很久了，所以应该就是这么个情况
