### ISSUE TITLE
在下载管理中结束任务后下载卡片再次出现

### ISSUE THREAD

**Issue by MacroMeng** [Hex-Dragon/PCL2#4766]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在下载BMC5时，进度条会在80%-90%区间范围内（大约）不动（至少很慢）(有时则是直接0B/s)，取消后PCL直接召唤《PCL已停止运行》。

### 重现步骤

1. 在下载-整合包内搜索BMC5；
2. 点击1.21.1[NeoForge][Beta]；
3. 下载该版本；
4. 在任意夜店，点击右下角“下载”页；
5. 点击任务右上角“X”，PCL有动画（细微的），但又开始下载；
6. 再次尝试取消，哐叽，PCL停止运行辣

### 日志与附件

[Log5.txt](https://github.com/user-attachments/files/17074714/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/17074715/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17074716/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17074717/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17074718/Log4.txt)

**Comment by tangge233** [comment]
```
[19:55:13.125] 获取文件 SHA1 失败：I:\Minecraft\.minecraft\versions\BMC5\mods\justenoughbreeding-neoforge-1.21.x-1.4.0.jar：未能找到文件“I:\Minecraft\.minecraft\versions\BMC5\mods\justenoughbreeding-neoforge-1.21.x-1.4.0.jar”。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   在 PCL.ModBase.GetFileSHA1(String FilePath)
错误类型：System.IO.FileNotFoundException
```
看起来是 `justenoughbreeding-neoforge-1.21.x-1.4.0.jar` 下载失败导致的

**Comment by LTCatt** [comment]
```
[Download] Pastel-Shaders-Universal-v1.200.zip：已完成，剩余文件 193
[Control] 按下图标按钮：BtnCancel
[Taskbar] 关闭下载管理卡片：CurseForge 整合包安装：BMC5 ，且移出任务列表
[Control] 切换主要页面：Launch, -1
[Page] 主页预设：Minecraft 新闻
[Page] 主页自定义数据来源：联网缓存文件
[Control] 按下附加按钮：下载管理
[Control] 切换主要页面：DownloadManager, 0
[Watcher] 新建下载管理卡片：CurseForge 整合包安装：BMC5 
[Control] 按下图标按钮：BtnCancel
[Taskbar] 关闭下载管理卡片：CurseForge 整合包安装：BMC5 ，且移出任务列表
[Loader] 加载器 CurseForge 整合包安装：BMC5  状态改变：Aborted
```
