### ISSUE TITLE
PCL2下载又删掉模组右键模组快速跳转下载页面之前出现错误

### ISSUE THREAD

**Issue by pangpang3356** [Hex-Dragon/PCL2#4768]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/user-attachments/assets/d9ab4f33-1898-4ad0-87be-fdc66fc08c5f)

### 重现步骤

大概是游戏设置mod管理删除了两个刚刚下载的史诗战斗模组然后右键史诗战斗模组出现的问题（之前启动游戏forge版本对不上所以删除下载启动游戏看看哪个版本对的上）

### 日志与附件

[Log5.txt](https://github.com/user-attachments/files/17078424/Log5.txt)
[Log4.txt](https://github.com/user-attachments/files/17078425/Log4.txt)
[Log1.txt](https://github.com/user-attachments/files/17078426/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17078427/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17078428/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17078429/Log4.txt)

**Comment by LTCatt** [comment]
#4691
