### ISSUE TITLE
删除mod

### ISSUE THREAD

**Issue by 1230b9** [Hex-Dragon/PCL2#4769]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

显示：  删除mod出现未知错误：未将对象引用到设置到对象的实例。
  在PCL.PageVersionMod.DeleteMods(IEnumerable`1 Modlist)
错误类型：System.NullReferenceException

### 重现步骤

1、删除mod时会弹出出现错误，但mod正常被删除。

### 日志与附件

[Log5.txt](https://github.com/user-attachments/files/17081524/Log5.txt)

**Comment by Pigeon0v0** [comment]
#4691
