### ISSUE TITLE
下载整合包并自定义版本名时出现两个重复的不重名版本

### ISSUE THREAD

**Issue by Water-Yuan** [Hex-Dragon/PCL2#4772]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

将整合包文件（我用的是.mrpack）拖入PCL窗口，输入自定义版本名后发现有两个版本正在下载，并且名称不同
![2024-09-21 18 35 32](https://github.com/user-attachments/assets/50269579-a514-442c-b0fa-645e31a47aaa)
![2024-09-21 18 30 46](https://github.com/user-attachments/assets/ed9dce5e-ac0e-4c69-b330-cfbee88cbf01)

### 重现步骤

1、获取一个.mrpack文件
2、拖入PCL窗口
3、自定义一个不同的版本名
4、开始下载后打开下载页面
5、发现两个名字不同的版本正在下载
![2024-09-21 18 30 46](https://github.com/user-attachments/assets/7e6140bb-3a1e-4066-acb7-ff4f00af0ddf)

### 日志与附件

[Log3.txt](https://github.com/user-attachments/files/17083765/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17083766/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17083767/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/17083768/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17083769/Log2.txt)

**Comment by allMagicNB** [comment]
这有问题吗？

**Comment by Water-Yuan** [comment]
> 你指的是一次拖放，两个下载？

是的

**Comment by Water-Yuan** [comment]
> 你指的是一次拖放，两个下载？

并且mod内容完全相同，唯一不同的只有版本名

**Comment by Water-Yuan** [comment]
> It looks more like you dragged the modpack file twice yourself. Please check.
> 
> 看起来更像是你自己将整合包拖拽了两次。请核实。
> 
> Details
> ```
> [18:30:16.366] [System] 接受文件拖拽：D:\Default\Downloads\SkyBlock整合包(解压)\SkyBlock-1.20.4 1.20.4.mrpack 等 1 个文件
> [18:30:16.367] [System] 文件为压缩包，尝试作为整合包安装
> [18:30:16.373] [ModPack] 整合包安装请求：D:\Default\Downloads\SkyBlock整合包(解压)\SkyBlock-1.20.4 1.20.4.mrpack
> [18:30:16.423] [ModPack] 整合包种类：Modrinth
> [18:30:16.432] [ModPack] 整合包 Fabric 版本：0.16.0
> [18:30:16.452] [Download] 已清理合并安装缓存
> [18:30:16.452] [Download] Fabric 缓存：C:\Users\Water\AppData\Local\Temp\PCL\Install\-1299330016\versions\fabric-loader-0.16.0-1.20.4
> [18:30:16.452] [Download] 对应的原版版本：1.20.4
> [18:30:16.455] [Loader] 加载器 Modrinth 整合包安装：SkyBlock-1.20.4  状态改变：Loading
> ```
> 
> ```
> [18:30:18.474] [System] 文件为压缩包，尝试作为整合包安装
> [18:30:18.474] [ModPack] 整合包安装请求：D:\Default\Downloads\SkyBlock整合包(解压)\SkyBlock-1.20.4 1.20.4.mrpack
> [18:30:18.501] [ModPack] 整合包种类：Modrinth
> [18:30:18.501] [ModPack] 整合包 Fabric 版本：0.16.0
> [18:30:18.530] [Download] 速度下限已提升到 2.4 M
> [18:30:18.544] [Control] 输入弹窗：输入版本名称
> ...
> [18:30:28.835] [Control] 按下按钮：确定
> [18:30:28.836] [Control] 输入弹框返回：Skyblock 1.20.4
> [18:30:28.841] [Download] Fabric 缓存：C:\Users\Water\AppData\Local\Temp\PCL\Install\620488739\versions\fabric-loader-0.16.0-1.20.4
> [18:30:28.841] [Download] 对应的原版版本：1.20.4
> [18:30:28.841] [Loader] 加载器 Modrinth 整合包安装：Skyblock 1.20.4  状态改变：Loading
> ```

"接受文件拖曳“只出现了一次，但是安装请求出现了两次，并且我记得我只拖曳了一次。这可能是源码的小bug吧（

**Comment by Water-Yuan** [comment]
并且16秒的这一次好像根本没有[Control]这个模块出现

**Comment by JingHai-Lingyun** [comment]
看了一下，目前部分整合包文件拖入后会直接安装（可能是有了默认名称），而不是等待输入名称后再进行安装
可能是没有处理好的原因

**Comment by Water-Yuan** [comment]
> 看了一下，目前部分整合包文件拖入后会直接安装（可能是有了默认名称），而不是等待输入名称后再进行安装 可能是没有处理好的原因

我也这么觉得

**Comment by Water-Yuan** [comment]
> @Water-Yuan
> 
> > "接受文件拖曳“只出现了一次
> 
> There was one less line copied just now. It has been edited and can be viewed again. You can also view the corresponding paragraph of Log1.txt to check.
> 
> 刚才少复制了一行，现已编辑，可以重新查阅。你也可以查看 Log1.txt 的对应段落进行检查。
> 
> > 并且16秒的这一次好像根本没有[Control]这个模块出现
> 
> I think this is the expected behavior. The current logic is that when there is no game instance with the same name in the _Instance Selection_ directory and the modpack name is legal, the launcher will automatically determine the name directly. If the above conditions are not met, the user will be asked to enter a new name.
> 
> 我认为是预期行为。目前的逻辑是，当 “版本选择” 目录中没有重名的游戏版本，且整合包名称合法的情况下，启动器将直接自动确定名称。若不符合上述条件，则会要求用户输入新名称。

问题是现在已经符合了上述条件（版本选择里无重名，整合包名称合法）并触发下载，但同时触发了“否”的结果：让我输入新名称，并且在确定后又触发了一次下载

**Comment by Water-Yuan** [comment]
> > 问题是现在已经符合了上述条件（版本选择里无重名，整合包名称合法）并触发下载，但同时触发了“否”的结果：让我输入新名称，并且在确定后又触发了一次下载
> 
> Your drag at 18:30:16 triggered the installation, and the corresponding folder was created in the game directory. Then you triggered another drag at 18:30:18, and because of the above factors, you were asked to enter a new name.
> 
> 你在 18:30:16 的这次拖拽触发了安装，此时启动器在游戏目录中创建了对应的文件夹。之后你在 18:30:18 又触发了一次拖拽，因为前述因素，所以会要求你输入新的名字。

上述日志中只有18:30:16有拖曳记录，18:30:18是直接“[System] 文件为压缩包，尝试作为整合包安装”，没有接受拖曳的记录，所以会不会其他的bug导致拖曳一次使得这一步重复了两次

**Comment by LTCatt** [comment]
![image](https://github.com/user-attachments/assets/d3c68a39-f3c5-46b3-baa5-89b1c685fe0c)
![image](https://github.com/user-attachments/assets/4b377a78-5941-4a65-8477-5ab24a1228c0)

PCL 确实收到了两个间隔 2s 的文件拖拽信息，从日志看是 WAI。
如果能 **复现** 所称的异常情况再处理。
