### ISSUE TITLE
搜索mod支持更多信息的检索

### ISSUE THREAD

**Issue by acaciachan** [Hex-Dragon/PCL2#4774]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

搜索mod不止可以搜索相关名字的mod，也可以搜索到mod的作者，依赖mod。
例如输入fabric api可以搜索到所有依赖fabric api的mod，搜masa可以搜索到所有masa做的mod。
最起码把搜索作者的功能加上，目前multiMC就有这样的功能
![PixPin_2024-09-21_21-19-53](https://github.com/user-attachments/assets/ead162d3-29ce-4aaa-8f56-ac55ff7984c8)
![PixPin_2024-09-21_21-20-10](https://github.com/user-attachments/assets/20ada30a-6469-44b8-90b9-7d8200f9070b)

### 原因

（示例）
这项优化让我可以更方便地xxxx。
如果没有这项优化，我每次都必须xxxx，让操作变得很麻烦。

**Comment by LTCatt** [comment]
API 并未提供类似功能。
如果说 MultiMC 可以做到，它是怎么搜索的？

**Comment by hejiehao** [comment]
https://docs.modrinth.com/#tag/projects 这个可以搜作者？

**Comment by LTCatt** [comment]
但 API 并不能作为搜索传入内容的一部分进行搜索，玩家输入的搜索内容我也没法判断是不是作者。
如果为了这个单独加个搜索框，或者整个搜索语法，感觉适用面和制作难度完全不对等……
先算了吧……
