### ISSUE TITLE
进入mod版本选择界面报错：格式化 json 对象失败

### ISSUE THREAD

**Issue by Silencesim** [Hex-Dragon/PCL2#4775]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

进入mod版本选择界面报错：格式化 json 对象失败。整合包界面无此问题。
![image](https://github.com/user-attachments/assets/53bd29ac-ff72-433d-97d2-d41eadeb2071)
![image](https://github.com/user-attachments/assets/cd5427f9-d8fa-4d0d-ba6d-03a679150bcc)

### 重现步骤

1、点击“下载-Mod”
2、点击任意一个Mod

### 日志与附件

[Log4.txt](https://github.com/user-attachments/files/17084709/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17084710/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/17084712/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17084713/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17084715/Log3.txt)

**Comment by JingHai-Lingyun** [comment]
```log
[23:49:50.983] 加载线程 Comp File (72) 发生运行时错误：格式化 json 对象失败： <!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title></title>
  <meta name="vi...(全长 541249 个字符)...
          );
        } catch (err) {}
        }
      })(); 
    });
</script>
</body>
</html>
   在 PCL.ModBase.GetJson(String Data)
   在 PCL.ModComp.CompFilesGet(String ProjectId, Boolean FromCurseForge)
   在 PCL.PageDownloadCompDetail._Lambda$__1-0(LoaderTask`2 Task)
   在 PCL.ModLoader.LoaderTask`2._Closure$__13-0._Lambda$__0()
```

获取到了以 HTML 为内容的信息…… 大概率是被反诈拦截了

**Comment by Silencesim** [comment]
> ```
> [23:49:50.983] 加载线程 Comp File (72) 发生运行时错误：格式化 json 对象失败： <!DOCTYPE html>
> <html lang="en">
> <head>
>   <meta charset="UTF-8">
>   <title></title>
>   <meta name="vi...(全长 541249 个字符)...
>           );
>         } catch (err) {}
>         }
>       })(); 
>     });
> </script>
> </body>
> </html>
>    在 PCL.ModBase.GetJson(String Data)
>    在 PCL.ModComp.CompFilesGet(String ProjectId, Boolean FromCurseForge)
>    在 PCL.PageDownloadCompDetail._Lambda$__1-0(LoaderTask`2 Task)
>    在 PCL.ModLoader.LoaderTask`2._Closure$__13-0._Lambda$__0()
> ```
> 
> 获取到了以 HTML 为内容的信息......大概率是被反诈拦截了 这看起来不是 PCL 导致的问题

突然又恢复正常了
