### ISSUE TITLE
电脑用户名有希腊语的时候无法使用Littleskin启动游戏

### ISSUE THREAD

**Issue by Crotina** [Hex-Dragon/PCL2#4777]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃基本不是 PCL 的原因，请 **不要** 提交反馈。你可以在论坛或社区找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用 HMCL 启动，HMCL 没有出现问题。** 如果 HMCL 也无法启动就不是 PCL 导致的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

之前装系统的时候设置了希腊语的用户名，然后用littleskin就无法启动了，而使用HMCL可以正常进入，第二次尝试的时候依然是这样，如果用户名是英语则两者都可以正常进游戏

如果手动往 C:\Users\ΣΚΛΑΝΒΕ\AppData\Roaming\PCL\（希腊语名称账户PCL文件夹）下放一个那个injector.jar，不论这个是哪里来的，都可以打开游戏，但是如果用HMCL启动游戏则不需要这一步

### PCL 错误报告、日志与附件

[错误报告-2024-9-22_0.21.04.zip](https://github.com/user-attachments/files/17085746/-2024-9-22_0.21.04.zip)

手动添加 authlib-injector.jar 之后启动的日志
[Log1.txt](https://github.com/user-attachments/files/17088004/Log1.txt)

这个 authlib-injector.jar
[authlib-injector.jar.txt](https://github.com/user-attachments/files/17088020/authlib-injector.jar.txt)

### HMCL 启动脚本

[script.txt](https://github.com/user-attachments/files/17085772/script.txt)

**Comment by Crotina** [comment]
![Untitled](https://github.com/user-attachments/assets/d50e5ce3-e47d-49f0-b5c2-3bffb144b16c)

即使启动器本身支持(一点)希腊语，这种问题也会出现

**Comment by allMagicNB** [comment]
？我不记得用户名能用希腊语，你是否在故意找茬？

**Comment by Crotina** [comment]
> ？我不记得用户名能用希腊语，你是否在故意找茬？

安装希腊语系统就有自带的希腊语输入法，就可以输入希腊语作为用户名，ξέρεις???

**Comment by allMagicNB** [comment]
事实上是由 #4703 导致。

**Comment by allMagicNB** [comment]
@Deep-Dark-Forest ？

**Comment by Crotina** [comment]
> 事实上是由 #4703 导致。

可是在环境完全相同的情况下，用户名是英语就能正常进去啊

**Comment by allMagicNB** [comment]
> > 事实上是由 #4703 导致。
> 
> 可是在环境完全相同的情况下，用户名是英语就能正常进去啊

鬼知道，看你日志我也只能得出你死活下载不下来 authlib-injector。

**Comment by Crotina** [comment]
> > > 事实上是由 #4703 导致。
> > 
> > 
> > 可是在环境完全相同的情况下，用户名是英语就能正常进去啊
> 
> 鬼知道，看你日志我也只能得出你死活下载不下来 authlib-injector。

是这样的，但是换成纯英文的用户名就不会有这个问题了，呃呃呃，不知道什么问题

**Comment by allMagicNB** [comment]
> > 鬼知道，看你日志我也只能得出你死活下载不下来 authlib-injector。
> 
> 是这样的，但是换成纯英文的用户名就不会有这个问题了，呃呃呃，不知道什么问题

那你再把日志发上来。

**Comment by WorldHim** [comment]
> > > > 事实上是由 #4703 导致。
> > > 
> > > 
> > > 可是在环境完全相同的情况下，用户名是英语就能正常进去啊
> > 
> > 鬼知道，看你日志我也只能得出你死活下载不下来 authlib-injector。
> 
> 是这样的，但是换成纯英文的用户名就不会有这个问题了，呃呃呃，不知道什么问题

路径问题（？
用希腊字母用户名可以正常补全文件吗

**Comment by allMagicNB** [comment]
> 路径问题（？
> 用希腊字母用户名可以正常补全文件吗

BMCLAPI 返回 403，能下下来才怪。

**Comment by Crotina** [comment]
> > 路径问题（？
> > 用希腊字母用户名可以正常补全文件吗
> 
> BMCLAPI 返回 403，能下下来才怪。
<img width="644" alt="屏幕截图 2024-09-22 034412" src="https://github.com/user-attachments/assets/a7b9551b-d294-4667-a91f-0d1bed3c6da4">

没想到吧

**Comment by allMagicNB** [comment]
> > > 路径问题（？
> > > 用希腊字母用户名可以正常补全文件吗
> > 
> > BMCLAPI 返回 403，能下下来才怪。
> <img width="644" alt="屏幕截图 2024-09-22 034412" src="https://github.com/user-attachments/assets/a7b9551b-d294-4667-a91f-0d1bed3c6da4">
> 
> 没想到吧
> 

发日志。

**Comment by Crotina** [comment]
[Log1.txt](https://github.com/user-attachments/files/17087925/Log1.txt)
这是用英语用户名登陆成功的日志（04:41左右）

**Comment by Crotina** [comment]
> Please check whether the authlib-injector.jar file exists in the C:\Users\KawaiiYooo\AppData\Roaming\PCL\ and C:\Users\ΣΚΛΑΝΒΕ\AppData\Roaming\PCL\ directories respectively.
> 
> > 可是在环境完全相同的情况下，用户名是英语就能正常进去啊
> 
> Maybe one user’s directory has this file and another doesn't... We need to check if that is the case.

如果手动在 C:\Users\ΣΚΛΑΝΒΕ\AppData\Roaming\PCL\ 下放置一个另一个账户的 authlib-injector.jar，是可以进入游戏的

[Log1.txt](https://github.com/user-attachments/files/17088004/Log1.txt)

[authlib-injector.jar.txt](https://github.com/user-attachments/files/17088020/authlib-injector.jar.txt)

但是它无法主动在这个目录下创建 authlib-injector.jar

**Comment by Pigeon0v0** [comment]
[Log1.txt](https://github.com/user-attachments/files/17088004/Log1.txt)
Ln 147 起：
```
[05:18:24.700] [Download] 463125865_145 264#：开始，起始点 0，https://bmclapi2.bangbang93.com/mirrors/authlib-injector/artifact/latest.json
[05:18:26.908] [Download] 463125865_145 264#：出错，远程服务器返回错误: (403) 已禁止。
   在 PCL.ModNet.NetFile.Thread(NetThread Info)
错误类型：System.Net.WebException
```

感觉实际上是 #4703 ，等下一个版本看看会不会好？

**Comment by Crotina** [comment]
> @Crotina
> 
> Will this problem still occur in Snapshot 2.8.7?

没有，如果不手动放置这个jar，还是进不去，同样的，环境不变，换成HMCL可以正常进入

**Comment by Deep-Dark-Forest** [comment]
@LTCatt 这里有个待处理

**Comment by LTCatt** [comment]
似乎是 #4703 。
在新版本中加了个修复，现在 authlib-injector.jar 会被尝试放到纯 ASCII 文件夹下。如果下个版本还能复现再看是不是其他原因吧……

**Comment by Crotina** [comment]
@LTCatt @LTCatt 
现在可以了吗awa
20B6-B13F-D520-97F0

**Comment by LTCatt** [comment]
你的解锁码：L8huDY65loKYcKoPx5qpUYRFx4nZHrIh
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
