### ISSUE TITLE
关闭版本隔离时添加弹窗提醒关闭版本隔离后的后果

### ISSUE THREAD

**Issue by shenbimicro233** [Hex-Dragon/PCL2#4778]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

- ### 将版本设置->概览->快捷方式的“版本文件夹”改为游戏文件夹，并跟随版本隔离的设置打开对应的文件夹
- ### 关闭版本隔离时添加弹窗提醒关闭版本隔离后的后果，让玩家更好理解在做什么

### 此项优化将更好的管理版本隔离前和版本隔离后的游戏文件夹管理（毕竟后面的存档文件夹和mod文件夹都跟随版本隔离设置了）

**Comment by LTCatt** [comment]
1. 游戏文件夹 ≠ 版本文件夹，一般说版本文件夹的时候就是特指 `versions/版本名`，WAI。
2. 可以
