### ISSUE TITLE
对背景音乐部分添加 歌词显示 功能

### ISSUE THREAD

**Issue by Crotina** [Hex-Dragon/PCL2#4780]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

这是我做的效果图
用户可以通过在music文件夹下放一个与歌曲同名的歌词文件来在启动器内显示歌词，也可以选择显示其它内容或者不显示
![111111111](https://github.com/user-attachments/assets/832656ee-7273-4c31-8dfd-03a661b9a124)
![222222222222](https://github.com/user-attachments/assets/7b537728-0252-48ed-ada2-a8dae964bbe2)

### 原因

我不知道

**Comment by JingHai-Lingyun** [comment]
在 Tooltip 里面放歌词很奇怪……

**Comment by Crotina** [comment]
> 在 Tooltip 里面放歌词很奇怪……

也可以放在别的位置。。。呃，自己设置嘛

**Comment by wuliaodexiaoluo** [comment]
>music文件夹下放一个与歌曲同名的歌词文件来在启动器内显示歌词

这貌似会误识为音乐文件。。。。
我不是很理解这个功能有什么用，因为都有文件了，显然关联到音乐播放器上是个更好的选择

<details>
<summary>Image</summary>

![image](https://github.com/user-attachments/assets/176d6185-1243-4519-a6b6-e977ae77808f)

</details>

>在 Tooltip 里面放歌词很奇怪……

问题是真的有人悬在按钮上就为了看个歌词吗.....
还是说打游戏打一半切出去悬在上面看歌词.....

>也可以放在别的位置。。。呃，自己设置嘛

增大工作量的做法，社区开发者的工作量已经足够大了

**Comment by LTCatt** [comment]
超出启动器范畴，暂不考虑，抱歉（

**Comment by SALTWOOD** [comment]
受众比较小，做了没啥用，PCL 是 **MC 启动器**，再塞东西就改名叫 *PCL 工具箱*得了……
