### ISSUE TITLE
Mod 下载原站不可用时未强制切换镜像源

### ISSUE THREAD

**Issue by JingHai-Lingyun** [Hex-Dragon/PCL2#4781]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

<details>
<summary>长图（测试对话）</summary>

![image](https://github.com/user-attachments/assets/74a47d92-8204-4dc0-a361-d79019fbeeda)

</details>
来自 @z0z0r4 联调测试结果

### 重现步骤

通过 host 禁用 Mod 下载主源，后下载 Mod 观察日志

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/17088256/Log1.txt)

**Comment by z0z0r4** [comment]
当前 Mod 镜像下载应该是 mod.mcmirror.top -> files.mcimirror.top -> 节点 -> 反代/网盘

**Comment by SALTWOOD** [comment]
已证实，通过携带特殊 UA 访问未在后端主控发现访问记录；抓包能证实一直在重试 forge

**Comment by LTCatt** [comment]
请上传一个有效的日志……

**Comment by Deep-Dark-Forest** [comment]
超时关闭。
