### ISSUE TITLE
优化背景图片设置

### ISSUE THREAD

**Issue by Crotina** [Hex-Dragon/PCL2#4782]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述
添加 轮流播放 ，可以设置多张背景图片来回切换，可以设置规则，顺序之类的
添加 视频背景 可以放置一个或多个视频作为启动器的背景
添加 动态背景 可以设置图片跟随光标运动(根据鼠标光标和启动器窗口的相对位置决定展示背景图的哪一部分)

### 原因
轮流播放：有很多好看的背景图，但一次只能用一张，太难受了，可以自己换就好了
视频背景：视频也好看
动态背景：我语文不好不知道怎么描述，就是很高级的样子

**Comment by JingHai-Lingyun** [comment]
- 轮流播放 & 视频背景 **拒绝** 于 #862
  > 龙猫：太超出启动器的范围了，抱歉（
- 背景模糊 与 #2918 第三条部分内容重叠

根据鼠标光标动态调整背景暂未发现重复反馈，但大概率也不会做……

**Comment by Deep-Dark-Forest** [comment]
https://github.com/Hex-Dragon/PCL2/issues/2548

**Comment by LTCatt** [comment]
超出启动器范畴，暂不考虑，抱歉
