### ISSUE TITLE
没有背景图片被使用的情况下背景图片的设置也会弹出

### ISSUE THREAD

**Issue by Crotina** [Hex-Dragon/PCL2#4783]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

这个bug没有什么实际上的影响，呃呃呃我也不知道为什么要上传这个
![step1](https://github.com/user-attachments/assets/2acca179-7741-4f24-8950-ee9f2924d02d)
![step2](https://github.com/user-attachments/assets/00f098a1-9342-4077-9790-a65e0a10bbab)

### 重现步骤

1、在PCL的picture文件夹放一个无法读取的文件(如mp4)
2、点击 刷新背景图片
3、PCL弹出错误提示
4、好啦

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/17088295/Log1.txt)

**Comment by allMagicNB** [comment]
故意找茬导致的

**Comment by Deep-Dark-Forest** [comment]
这是预期中的现象。点击“刷新背景图片”实际上是切换背景图片，而如果切换到了不是图片的文件就自然会报错。

**Comment by JingHai-Lingyun** [comment]
我个人偏向认为是用户故意引发错误……
已经说了是背景**图片**了，谁会无缘无故往里面放不是图片的内容……

**Comment by Crotina** [comment]
> 这是预期中的现象。点击“刷新背景图片”实际上是切换背景图片，而如果切换到了不是图片的文件就自然会报错。

但是他还是打开那些关于调整背景的内容啊...实际上没有图给他调

**Comment by allMagicNB** [comment]
> > 这是预期中的现象。点击“刷新背景图片”实际上是切换背景图片，而如果切换到了不是图片的文件就自然会报错。
> 
> 但是他还是打开那些关于调整背景的内容啊...实际上没有图给他调

你说得对，但这是故意找茬导致的
