### ISSUE TITLE
添加离线游戏名和版本分类文件夹

### ISSUE THREAD

**Issue by xiao0miao** [Hex-Dragon/PCL2#4787]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

我会加入很多mod服务器，这样服务器都提供很多整合包，但我也使用很多离线游戏名加入（开小号）这使我每次更换版本和游戏名都很麻烦，希望可以添加类似“自定义收藏夹”的功能

### 原因

.

**Comment by JingHai-Lingyun** [comment]
快速切换游戏名
![image](https://github.com/user-attachments/assets/a3acd084-ec01-4bdd-a3ac-6a08142f4f61)
版本收藏夹
![image](https://github.com/user-attachments/assets/ce6cf65f-fc3a-496b-b00a-2ef99ffa6221)
看看可以满足要求吗？或者详细描述 `自定义收藏夹` 是怎么自定义，收藏什么

**Comment by xiao0miao** [comment]
自定义是可以自己命名，收藏游戏版本和游戏名（游戏版本和游戏名不在同一个）

**Comment by LTCatt** [comment]
用途不大，此外版本分类也暂时不考虑，抱歉……
