### ISSUE TITLE
点击自动安装界面的任意版本后崩溃（程序出现未知错误：未将对象引用设置到对象的实例）

### ISSUE THREAD

**Issue by RawDiamondMC** [Hex-Dragon/PCL2#479]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

点击自动安装界面的1.19.2后未正常跳出界面，且PCL2崩溃。
PCL2版本2.4.2正式版。

### 重现步骤

1、点击”下载“
2、点击自动安装界面的”1.19.2“
3、PCL2崩溃

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10103157/Log1.txt)

**Comment by LiuBinzhe** [comment]
没有呀？我的PCL好好的

**Comment by LTCatt** [comment]
从日志看起来这个 Bug 相当奇怪，有人能复现么？

**Comment by DiamondPigeon** [comment]
> 从日志看起来这个 Bug 相当奇怪，有人能复现么？

而且没有任何表现...点了就崩

**Comment by DiamondPigeon** [comment]
后来又没事了，奇怪的很

**Comment by LTCatt** [comment]
估计很难复现……先当作极小概率的偶然事件吧……

**Comment by LTCatt** [comment]
#535
