### ISSUE TITLE
对调试模式下的主页日志添加导出

### ISSUE THREAD

**Issue by Crotina** [Hex-Dragon/PCL2#4790]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

可以通过右键主页日志来将其单独导出

### 原因

每次都要翻log去，现在直接导出这一段

**Comment by allMagicNB** [comment]
？

**Comment by allMagicNB** [comment]
来你跟我说说，这到底有什么用？导出之后不还是要找文件吗？这不是多此一举吗？

**Comment by Crotina** [comment]
> 来你跟我说说，这到底有什么用？导出之后不还是要找文件吗？这不是多此一举吗？

那就导出到一个比较方便的位置啊

**Comment by allMagicNB** [comment]
评价为：开发者不需要，普通用户也不需要，闲的人才需要

**Comment by LTCatt** [comment]
用途不大，log 里已经有了，暂时不考虑……
