### ISSUE TITLE
为在主页添加的回声洞使用和百宝箱里面的回声洞一样的交互

### ISSUE THREAD

**Issue by Crotina** [Hex-Dragon/PCL2#4796]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

为在主页添加的回声洞使用和百宝箱里面的回声洞一样的交互，而不是让主页的那个只能通过点右上角刷新来刷新（主页的那个连动画都少好多）

### 原因

（示例）
这项优化让我可以更方便地xxxx。
如果没有这项优化，我每次都必须xxxx，让操作变得很麻烦。

**Comment by Deep-Dark-Forest** [comment]
#4595

**Comment by Deep-Dark-Forest** [comment]
> 主页的那个连动画都少好多

参见 #4595

**Comment by LTCatt** [comment]
技术上不太好做，也没啥必要（
