### ISSUE TITLE
为愚人节版本添加发布日期

### ISSUE THREAD

**Issue by Crotina** [Hex-Dragon/PCL2#4797]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

![zozozozozo](https://github.com/user-attachments/assets/3737d0b2-dc56-46b0-8f47-2b79f3312335)

又不是每个愚人节版本都是XXw开头，这样我们就可以知道哪个版本是哪年的了

### 原因

（示例）
这项优化让我可以更方便地xxxx。
如果没有这项优化，我每次都必须xxxx，让操作变得很麻烦。

**Comment by Crotina** [comment]
@LTCatt 
@LTCatt 
20B6-B13F-D520-97F0
解锁一下谢谢

**Comment by Crotina** [comment]
> @LTCatt @LTCatt 20B6-B13F-D520-97F0 解锁一下谢谢

忘了，这不是bug

**Comment by allMagicNB** [comment]
我就说你怎么反馈那么勤奋，原来就是为了个主题
活跃橙只有反馈 Bug 能解决，但你这是优化……

**Comment by Crotina** [comment]
> 我就说你怎么反馈那么勤奋，原来就是为了个主题 活跃橙只有反馈 Bug 能解决，但你这是优化……

回复完才想起来
