### ISSUE TITLE
允许玩家为版本自定义分类

### ISSUE THREAD

**Issue by Crotina** [Hex-Dragon/PCL2#4802]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

目前只有预设的 可安装mod、常规版本、收藏夹那些，我的意思是，玩家应该可以自定义分类，这样可以避免一堆版本看着乱死了的情况，虽然 #4787 提到类似功能但是他的主旨好像不是这个

### 原因

（示例）
这项优化让我可以更方便地管理版本。
如果没有这项优化，会很乱

**Comment by LTCatt** [comment]
和 #4787 差不多
