### ISSUE TITLE
1.0.0 rc2-2的图标与下载页面上展示的图标不符

### ISSUE THREAD

**Issue by Crotina** [Hex-Dragon/PCL2#4803]
### 检查项

- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![1](https://github.com/user-attachments/assets/8f8ce4a3-844f-4bac-8ab2-615b739c05d7)

![2](https://github.com/user-attachments/assets/3e46ac15-6a56-44e5-8be5-a8ee29ecc020)

不过我觉得没有人会去玩这么低版本吧 (/▽＼)

### 重现步骤

1、下载
2、自动安装，往下滚，找到 预览版 的最后一个1.0.0 rc2-2
3、下载
4、在版本选择里面查看，
5、好了

(它的分类也有错)
### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/17090859/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17090860/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17090861/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17090862/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17090863/Log5.txt)

**Comment by LTCatt** [comment]
umm 它应该归类到远古版

**Comment by LTCatt** [comment]
目前下载界面的分类策略是，将 **正式版 1.0.0** 之前的所有版本归类成远古版。
如果 #4555 不是这样整的话应该 #4555 那边得改改（

**Comment by LTCatt** [comment]
刷新一次缓存就好了
