### ISSUE TITLE
下载时卡在 下载Forge主文件42%

### ISSUE THREAD

**Issue by mnbvcxz-2024** [Hex-Dragon/PCL2#4812]
### 检查项

- [ ] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在1.18.2-Forge_40.2.0 下载时会卡在 下载Forge主文件 42%
手动安装中也是卡在下载Forge主文件42%

### 重现步骤

1、点击下载-自动安装-正式版1.18.2-froge_40.2.0-开始安装
2、点击右下角 下载管理
3、yes sir！

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/17110640/Log1.txt)

**Comment by tangge233** [comment]
forge installer 一直下载不下来。从日志中可知镜像源恰好遇到过多请求错误，然后 PCL 一直在尝试官方源…

**Comment by mnbvcxz-2024** [comment]
> forge installer 一直下载不下来。从日志中可知镜像源恰好遇到过多请求错误，然后 PCL 一直在尝试官方源...

那有解决办法吗（现在）

**Comment by LTCatt** [comment]
2.8.7 已修复下载相关问题

**Comment by mnbvcxz-2024** [comment]
> 2.8.7 已修复下载相关问题
但是检查更新时显示最新正式版2.8.6🤔

**Comment by LTCatt** [comment]
2.8.7 目前仅有快照版更新，之后会推送到正式版（
