### ISSUE TITLE
PCL帮助库内置图床炸了

### ISSUE THREAD

**Issue by Joker2184** [Hex-Dragon/PCL2#4813]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

PCL帮助库内置图床炸了

### 重现步骤

帮助库 更新mod栏目
通过切换预设主页测试网络 正常获取
打开帮助库图片链接显示无法访问

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/17111977/Log1.txt)
![0be30c8d43546f729a16a3d67b90109d](https://github.com/user-attachments/assets/c7653442-be56-46af-af8f-5a5bd271e9c0)
![497ac26df26e3bae0a9bf157df765f02](https://github.com/user-attachments/assets/9a7019f4-8064-4fd9-bb70-eea5075e61c5)
![96473efadab3d8a7cfb1f3320a4e4ce7](https://github.com/user-attachments/assets/7bde8e34-8d46-4774-b0ce-16ba3ac1c05b)
![e169058f1b1bb25e5849ce80505d094b](https://github.com/user-attachments/assets/724e6ffd-2460-454c-ad8f-fe22248dfd96)

**Comment by LTCatt** [comment]
在帮助库交（
https://github.com/LTCatt/PCL2Help/issues/new
