### ISSUE TITLE
极为罕见

### ISSUE THREAD

**Issue by rzy05** [Hex-Dragon/PCL2#4822]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

极为罕见的时候，在启动游戏时切换其他窗口可能会卡住

### 重现步骤

1、点击启动某版本（我是1.20.1opt u16）
2，然后点击诸如设置之类

### 日志与附件

硬盘炸了:( 随便找个.log代替了
[新建 文本文档.log](https://github.com/user-attachments/files/17144858/default.log)

**Comment by Joker2184** [comment]
Troubleshooting any problem without the error log is like driving with your eyes closed.
在没有错误日志的情况下诊断任何问题无异于闭眼开车。

**Comment by Crotina** [comment]
Troubleshooting any problem without the error log is like driving with your eyes closed.

在没有错误日志的情况下诊断任何问题无异于闭眼开车。

Η αντιμετώπιση προβλημάτων χωρίς το αρχείο καταγραφής σφαλμάτων είναι σαν να οδηγείτε με κλειστά μάτια.

**Comment by SALTWOOD** [comment]
快速点击引起的 bug 不受理。而且没有 log
反正硬盘都坏了不然关了吧（

**Comment by wuliaodexiaoluo** [comment]
>极为罕见的时候，在启动游戏时切换其他窗口可能会卡住

我记得，当 PCL 窗口失去焦点时好像会中断 UI 渲染

**Comment by Deep-Dark-Forest** [comment]
超时关闭。
