### ISSUE TITLE
更好的下载源切换

### ISSUE THREAD

**Issue by Blalala6868** [Hex-Dragon/PCL2#4825]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

允许用户手动切换下载源或者优化下载源自动切换逻辑

### 原因

![image](https://github.com/user-attachments/assets/5997f1b8-1e68-41d1-8bf3-115e3c34d6ba)
https://github.com/Hex-Dragon/PCL2/discussions/4820#discussioncomment-10765562

这个 ~~傻逼~~ 不够智能的切换逻辑使得在有墙/特殊的网络环境下的所有用户都得傻等这3k+的文件都下载失败完才能正式开始走其它源下载游戏

**Comment by Joker2184** [comment]
设置->启动器->版本列表获取改为尽量使用官方源
~~不是能换用户手动切换吗~~
~~话说PCL应该不会考虑自动检测是否有网络代理的情况下 自动切换为其他源~~

**Comment by wyc-26** [comment]
那你来说说怎么检测代理？
别告诉我 IP 检测，人家外国也有用 PCL 的

**Comment by Deep-Dark-Forest** [comment]
> I think we need to give users the right to choose the download source.

如果是这样的话，请 reopen #3466

**Comment by Deep-Dark-Forest** [comment]
> > 如果是这样的话（允许用户更换文件下载源），请 reopen #3466
> 
> OK.

哎这个也别关啊，author 还说了 “优化下载源自动切换逻辑” 呢（

**Comment by Deep-Dark-Forest** [comment]
> 设置->启动器->版本列表获取改为尽量使用官方源
> ~~不是能换用户手动切换吗~~
> ~~话说PCL应该不会考虑自动检测是否有网络代理的情况下 自动切换为其他源~~

他说的是文件下载而不是版本列表获取，那个选项只对后者生效（

**Comment by Blalala6868** [comment]
> 设置->启动器->版本列表获取改为尽量使用官方源 ~不是能换用户手动切换吗~ ~话说PCL应该不会考虑自动检测是否有网络代理的情况下 自动切换为其他源~

![image](https://github.com/user-attachments/assets/d8f00325-295e-4880-819f-a233cbeb62cb)
版本列表源和下载源不是同一个东西

**Comment by LTCatt** [comment]
Reopened #3466
