### ISSUE TITLE
删除mod时显示出现未知错误

### ISSUE THREAD

**Issue by BleakScarf** [Hex-Dragon/PCL2#4827]
### 检查项

- [ ] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

点击删除mod就会出现未知错误
![a7f4cf4b-5ac8-4642-92f8-0db3833e4821](https://github.com/user-attachments/assets/6ea6da2f-81a9-462d-8e90-5cc7d778ec46)

### 重现步骤

1、点击主页的版本设置
2、点击Mod管理
3、选择一个mod点删除

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/17163177/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17163179/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17163180/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17163182/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17163183/Log5.txt)

**Comment by allMagicNB** [comment]
![Screenshot_20240927_191303.jpg](https://github.com/user-attachments/assets/e7b4d95d-e073-44ee-9495-6f60d2ef6fe7)

？哥们你是哪里不正常吗？

**Comment by JingHai-Lingyun** [comment]
此 Bug 修复于 2.8.7，2.8.7 目前只在 Snapshot（快照渠道）上推送，请等待后续更新

**Comment by allMagicNB** [comment]
> > ？哥们你是哪里不正常吗？
> 
> 语气别那么冲嘛，虽然提交者知道了有重复但是仍然想获得错误提示的帮助，那这个帖子就有存在的意义（虽然最终还是被关掉）

我不觉得会 Edit 的人不会 Close。
