### ISSUE TITLE
正版登录尝试失败：登录轮询失败

### ISSUE THREAD

**Issue by wanweishe** [Hex-Dragon/PCL2#4828]
### 检查项

- [x] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

9.26日左右自动更新到快照2.8.7后被要求账号重新登陆，并且按照步骤打开微软登录网址并接收验证码后成功，微软Minecraft登录网页显示成功，但PCL等待8秒左右却弹出失败，直到今天一直尝试登录，我一共有两个正版账号，账号01最开始登录的，成功了，现在出问题的是账号02
![正版登录失败01](https://github.com/user-attachments/assets/cddc3f5a-f7ae-4db6-af50-1931bc17e21d)
![正版登录失败02](https://github.com/user-attachments/assets/6e933ad3-e040-46e7-ab6c-53cc31c2d8cb)

### 重现步骤

1、微软网址登陆成功
2、PCL显示失败

### 日志与附件

[Log3.txt](https://github.com/user-attachments/files/17163768/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17163769/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17163770/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/17163773/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17163775/Log2.txt)

**Comment by allMagicNB** [comment]
@LTCatt @Pigeon0v0

**Comment by tangge233** [comment]
我怀疑是使用 `NetRequestMulty` 导致的，一会给你发一个不使用 `NetRequestMulty` 的版本你看看正不正常

**Comment by allMagicNB** [comment]
> 我怀疑是使用 `NetRequestMulty` 导致的，一会给你发一个不使用 `NetRequestMulty` 的版本你看看正不正常

别怀疑了，第一次请求慢点返回内容第二次再请求就会这么炸。

**Comment by JingHai-Lingyun** [comment]
鉴于有出现测试时未报错的现象，尝试使用上述版本鉴定问题关键点后再做操作。
感谢提交者配合

**Comment by Pigeon0v0** [comment]
这个问题我这没复现，等反馈者看看先 =。=

**Comment by tangge233** [comment]
@wanweishe  日志上传不成功，请重新上传

**Comment by Crotina** [comment]
啊？我完全没有这个情况，是不是因为所在地的问题，在中国可能会有连接问题

**Comment by tangge233** [comment]
可否尝试下使用 HMCL 能否正常登录？HMCL 和 PCL 都使用微软登录代码流登录 Minecraft 账号

**Comment by zkitefly** [comment]
这个是授权问题，不是 pcl 问题

这个的解决方法就是使用密码登录，相关文档：

https://docs.hmcl.net/launcher/use-password-login-microsoft-account.html

建议 pcl 做个检查，如果在这一步返回 400，则提示用户使用密码登录

**Comment by LTCatt** [comment]
可以判断 `AADSTS70000`

**Comment by zkitefly** [comment]
注：

 https://github.com/PrismLauncher/PrismLauncher/issues/2302

PrismLauncher 和 HMCL 等使用设备流登录的启动器都遇到了这个问题，而且上面的 issue 也多次提示使用密码登录

**Comment by EncVar** [comment]
轮询interval是5s
会不会是间隔时间太短了

**Comment by tangge233** [comment]
> 轮询interval是5s 会不会是间隔时间太短了

是报 `AADSTS70000` 错误。微软登录认证出问题了（要密码登录），在修了.jpg

**Comment by allMagicNB** [comment]
> 轮询interval是5s
> 会不会是间隔时间太短了

哥们，能不能不要不看上下文乱诊断啊……

**Comment by EncVar** [comment]
> > 轮询interval是5s
> > 会不会是间隔时间太短了
> 
> 哥们，能不能不要不看上下文乱诊断啊……

报错信息是设备码已经被使用
所以推断是轮询太快了
