### ISSUE TITLE
创建一个.minecraft文件夹

### ISSUE THREAD

**Issue by ZZJ-LBT** [Hex-Dragon/PCL2#483]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

应该在首页搞一个新建.minecraft文件夹的按钮。

### 原因

因为我要.minecraft文件夹。。。

**Comment by baguotao233** [comment]
PCL2在打开时会自动创建.minecraft文件夹，当然PCL2所在目录不能存在2个.minecraft，会产生冲突，因此该请求应该驳回

**Comment by ZZJ-LBT** [comment]
> PCL2在打开时会自动创建.minecraft文件夹，当然PCL2所在目录不能存在2个.minecraft，会产生冲突，因此该请求应该驳回

我不在PCL2根目录创建，在别的地方创建不行么？

**Comment by WForst-Breeze** [comment]
现在PCL2“添加已有文件夹”中选中一个文件夹，可以直接设置该文件夹为游戏文件夹（即使其并非为.minecraft）。这边先给您初步确认了，请等待等待开发者进一步考虑qwq

**Comment by ZZJ-LBT** [comment]
> 现在PCL2“添加已有文件夹”中选中一个文件夹，可以直接设置该文件夹为游戏文件夹（即使其并非为.minecraft）。这边先给您初步确认了，请等待开发者进一步考虑qwq

那还要自己创建，我选个路径让启动器自己创建一个呗QWQ

**Comment by LTCatt** [comment]
使用微软给你的右键新建文件夹……
