### ISSUE TITLE
动画速度更改时无法解锁玄素黑

### ISSUE THREAD

**Issue by Joker2184** [Hex-Dragon/PCL2#4830]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

就玄素黑貌似点不了（？
上连点器都解锁不了（
求其他人看看（？

### 重现步骤

玄素黑通过快速点击该选项解锁
目前测试貌似不能解锁（？

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/17164527/Log1.txt)

**Comment by Joker2184** [comment]
搭配连点器后的情况
https://github.com/user-attachments/assets/d280943b-23a6-4d23-bc9f-cb45d1251dda

**Comment by tangge233** [comment]
![image](https://github.com/user-attachments/assets/822af816-42e7-4f5e-b2df-ec5b348bd29b)

我这测试了下没问题。看了你的日志后……哥们点错选项了……

**Comment by Joker2184** [comment]
> ![image](https://private-user-images.githubusercontent.com/50769997/371546152-822af816-42e7-4f5e-b2df-ec5b348bd29b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0NDMzMzEsIm5iZiI6MTcyNzQ0MzAzMSwicGF0aCI6Ii81MDc2OTk5Ny8zNzE1NDYxNTItODIyYWY4MTYtNDJlNy00ZjVlLWIyZGYtZWM1YjM0OGJkMjliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDEzMTcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2OWQzZTlkMmI4YmQ4NDRlMTdhOTRiZTIzMTk1YTVmMjhjY2EzOGE3NWY1NTY2NTU1Y2NiZTkyN2I4ZjVkMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Di_ALABS805Lz3Uh_jy6K7JQTcrikQxpvzfUsvTQBkM)
> 
> 我这测试了下没问题。看了你的日志后……哥们点错选项了……

没有（稍等有视频

**Comment by Joker2184** [comment]
~~奇奇怪怪.jpg~~

**Comment by Joker2184** [comment]
log显示为龙猫蓝是因为不小心点到其他的了 然后日志貌似不会记录未解锁的UI radiobutton

**Comment by Joker2184** [comment]
草了（
动画的锅
当动画速度更改时玄素黑解锁就检测不到了（（（

**Comment by JingHai-Lingyun** [comment]
作为 `动画速度更改时无法解锁玄素黑` Reopen 并添加待处理标签

**Comment by Joker2184** [comment]
（P.s 有必要吗（（（？

**Comment by Joker2184** [comment]
不是 这玩意算Bug?(

**Comment by Joker2184** [comment]
A337-59A8-1C6C-23CA

**Comment by LTCatt** [comment]
你的解锁码：eZNVx5xcq7Mj1LpamM3/rMZkc2eZMxNz
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
