### ISSUE TITLE
获取启动参数失败 → 未将对象引用设置到对象的实例

### ISSUE THREAD

**Issue by lactobionicAcid** [Hex-Dragon/PCL2#4835]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

启动游戏时，启动失败并弹出提示窗 “Minecraft 启动失败：获取启动参数失败 → 未将对象引用设置到对象的实例”。

![image](https://github.com/user-attachments/assets/8a2ba112-56f8-4240-802b-30c5225f6eb1)

### 重现步骤

在正版登录的情况下，点击切换账号，重新使用正版登入一次；
将 PCL 启动器挂在后台（不要关闭）至少 10 分钟后，呼出 PCL 启动器并启动 Minecraft，可能触发该 Bug。

### 日志与附件

[Log1.txt（1）](https://github.com/user-attachments/files/17167721/Log1.txt)（从第 663 行开始）
[Log1.txt（2）](https://github.com/user-attachments/files/17173459/Log1.txt)（从第 309 行、第 575 行开始）

**Comment by JingHai-Lingyun** [comment]
有可能是新版登录带来的 Bug

**Comment by LTCatt** [comment]
没复现出来……
虽然重新启动了两次登录加载器确实是 bug 就是了（
