### ISSUE TITLE
打开老版本 PCL 后需要重新进行登录

### ISSUE THREAD

**Issue by Apple-alone** [Hex-Dragon/PCL2#4836]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

有些玩家已经登录过Minecraft了，更新后打开自动跳转到登录网页，真的有点麻烦

![image](https://github.com/user-attachments/assets/12662c0c-5eb4-4df8-b6a7-5d781ffe7445)

可以看到我已经是正版账号了，但是每次打开都要登录。。。。

我只想体验游戏，并不是来搞账号的。。。（因为我登录慢，其实我觉得不如之前的登录方式。。。）

### 重现步骤

每次打开PCL

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/17171549/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17171550/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17171551/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17171552/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17171553/Log5.txt)

**Comment by Pigeon0v0** [comment]
是更新完启动器之后要求登录，还是更新完以后每次启动游戏都要求登录？

**Comment by wuliaodexiaoluo** [comment]
目前根据我的复现结果，在每次打开 PCL 时都被要求重新登陆

![image](https://github.com/user-attachments/assets/28faa295-46ad-4f08-b70b-7c8b75c3ef9e)

[Log1.txt](https://github.com/user-attachments/files/17191591/Log1.txt)


服务器返回的错误内容是
>The provided value for the input parameter 'refresh_token' or 'assertion' is not valid. The token was issued for a different client id

**Comment by LTCatt** [comment]
这是因为你从来没有等到登录完全完成就取消了，只要完全完成一次就不会再弹了吧

**Comment by allMagicNB** [comment]
就之前的 client_id 和现在的不同导致的。

**Comment by wuliaodexiaoluo** [comment]
[Log.txt](https://github.com/user-attachments/files/17197860/Log.txt)


我这里还有一份登录完成的 Log5。。。
这个 Bug 现在我复现不了了。。。。

**Comment by LTCatt** [comment]
如果完全登录完成之后，2.8.8 还会复现，再传 log 考虑修复（

**Comment by HomoobyDX** [comment]
我今天意外用同一个版本的PCL（快照和正式版），打开启动器复现出来了（游戏已经进回收站了orz...）

**Comment by LTCatt** [comment]
复现出来了交个日志啊……

**Comment by HomoobyDX** [comment]
[PCL.zip](https://github.com/user-attachments/files/17210673/PCL.zip)
不确定游戏有没有永久删除，龙猫看一下这个是不是

**Comment by HomoobyDX** [comment]
日志补充：
[Log2.txt](https://github.com/user-attachments/files/17214465/Log2.txt)
[Log1.txt](https://github.com/user-attachments/files/17214466/Log1.txt)

**Comment by LTCatt** [comment]
上传的日志并不连续，这需要两个连续的日志，第一次完整完成网页登录，第二次重新打开 PCL 后报错。
注意：在使用新版本 PCL 登录后，再换回老版本 PCL，可以固定触发该情况，但这是正常的。只有 **一直使用新版本 PCL** 但还是触发该情况才是 bug。

**Comment by JingHai-Lingyun** [comment]
来自我的服成员，体现是上一天登录了之后第二天仍然请求登录

[Log1.txt](https://github.com/user-attachments/files/17228818/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17228822/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17228821/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17228820/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17228819/Log5.txt)

**Comment by LTCatt** [comment]
![image](https://github.com/user-attachments/assets/a2dff90c-26a0-4d53-8340-2d1e8bf1f997)
提交的日志里还是打开过了老版本 PCL，可能不在同一个文件夹下。
或许还是把开老版本作为 issue 修复吧……

**Comment by HomoobyDX** [comment]
补充一下我提交的：最开始老版本的PCL打开也要求重新登陆了一次，然后我没登陆，把PCL升级到最新的后又弹出了新版的登录，原先快照版启动器是完整登陆完毕的
快照版日志：
[Log1.txt](https://github.com/user-attachments/files/17234794/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17234796/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17234798/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17234799/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17234800/Log5.txt)

**Comment by Apple-alone** [comment]
有时候好像会GET失败，我看日志发现的

**Comment by Apple-alone** [comment]
> 这是因为你从来没有等到登录完全完成就取消了，只要完全完成一次就不会再弹了吧 ![图像](https://private-user-images.githubusercontent.com/40348278/372137483-03addb39-02b3-4258-854e-419822d30ea0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5MjY2NjIsIm5iZiI6MTcyNzkyNjM2MiwicGF0aCI6Ii80MDM0ODI3OC8zNzIxMzc0ODMtMDNhZGRiMzktMDJiMy00MjU4LTg1NGUtNDE5ODIyZDMwZWEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAzVDAzMzI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0MjE0Y2IzNWViZjM3MDQwYjE1ZmU1ZjgyNGNkMmM1MDExNDFmY2Q5NGU3NTNhYjJmNTgxY2EyOWY3NWUyN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7h_R5y_nERn6iv_8VYQZNxmsKfVgAO7pW8BFcD-AXVM)

这个是登录太久了登录不上，我网页那里也访问不进https://account.live.com

**Comment by Apple-alone** [comment]
来个解锁码！
