### ISSUE TITLE
更改版本名时的报错应该显示更多信息

### ISSUE THREAD

**Issue by Crotina** [Hex-Dragon/PCL2#4837]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

![1](https://github.com/user-attachments/assets/a470dde8-61f5-4299-a83a-0e23b589680c)

举个栗子，就像这样，当版本文件夹里面有什么东西在使用的时候，改名会失败，

**但是它给的报错信息并不能让我们知道该干什么**(对新手不太友好)

可以在报错信息里面加上一些可能导致问题的原因，至少这样可以让我们知道该去检查哪里

### 原因

这项优化让我可以更方便地检查可能存在的问题。
如果没有这项优化，我可能每次都必须重启电脑，让操作变得很麻烦。

**Comment by LTCatt** [comment]
这是微软提供的信息，我也没法获得更细节的原因 Orz
