### ISSUE TITLE
白屏

### ISSUE THREAD

**Issue by heiman114514** [Hex-Dragon/PCL2#4838]
### 检查项

- [ ] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃基本不是 PCL 的原因，请 **不要** 提交反馈。你可以在论坛或社区找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用 HMCL 启动，HMCL 没有出现问题。** 如果 HMCL 也无法启动就不是 PCL 导致的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在1.12.2及其他1.12中启动成功但是没有显示窗口(任务栏中或设置全屏为白屏)

### PCL 错误报告、日志与附件

[Log3.txt](https://github.com/user-attachments/files/17171981/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17171982/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17171983/Log5.txt)

**Comment by PhantomPixel-0418** [comment]
如果 HMCL 也无法启动就不是 PCL 导致的问题，请 **不要** 提交反馈。

**Comment by PhantomPixel-0418** [comment]
可能是因为中文用户名导致的问题

**Comment by allMagicNB** [comment]
![Screenshot_20240928_130113.jpg](https://github.com/user-attachments/assets/0f2a687d-1622-403c-b311-63933b13164b)

![Screenshot_20240928_130059.jpg](https://github.com/user-attachments/assets/5c88fd77-0dbe-4765-bfcc-f0649dcb7935)

**Comment by JingHai-Lingyun** [comment]
尝试使用 HMCL 启动和导出 HMCL 启动脚本，并补充信息

**Comment by heiman114514** [comment]
> Log3 这边最后是成功了啊 Log4 这边是因为mod错误 Log5 也没有啥有效信息啊 PS：我看了这么久也没看见啥东西，以后能不能上传对应的Log呢

没安装mod啊

**Comment by heiman114514** [comment]
> Log3 这边最后是成功了啊 Log4 这边是因为mod错误 Log5 也没有啥有效信息啊 PS：我看了这么久也没看见啥东西，以后能不能上传对应的Log呢

额好像发错了

**Comment by PhantomPixel-0418** [comment]
> 没安装mod啊

从你的这个日志上看出装了mod
以后记得上传对应的日志

**Comment by heiman114514** [comment]
> > 没安装mod啊
> 
> 从你的这个日志上看出装了mod 以后记得上传对应的日志

好的谢谢了，麻烦了

**Comment by PhantomPixel-0418** [comment]
@JingHai-Lingyun 可以 close 了吧
