### ISSUE TITLE
删除mood出现未知错误

### ISSUE THREAD

**Issue by love254** [Hex-Dragon/PCL2#4839]
### 检查项

- [ ] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![错误](https://github.com/user-attachments/assets/2b045e31-4c2b-495c-9faa-636886334935)

### 重现步骤

1、点击mood管理
2、然后删除mood

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/17172046/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17172047/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17172048/Log3.txt)

**Comment by JingHai-Lingyun** [comment]
此 Bug 修复于 2.8.7，2.8.7 目前只在 Snapshot（快照渠道）上推送，请等待后续更新

**Comment by love254** [comment]
好的，谢谢



在 2024-09-28 11:31:32，"凌云" ***@***.***> 写道：

此 Bug 修复于 2.8.7，2.8.7 目前只在 Snapshot（快照渠道）上推送，请等待后续更新
