### ISSUE TITLE
手动安装包动画

### ISSUE THREAD

**Issue by LiuBinzhe** [Hex-Dragon/PCL2#484]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

能不能给手动安装包的打开和收回添加一个动画。

### 原因

看着更丝滑！

**Comment by LiuBinzhe** [comment]
我记得之前有个人也说了，但是议题被忽略然后关掉了

**Comment by LTCatt** [comment]
……你知道就行
