### ISSUE TITLE
将模组里的icon微标显示出来

### ISSUE THREAD

**Issue by Cai-kunkun** [Hex-Dragon/PCL2#4842]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

部分模组是自己编写或来自非官方来源的模组或某一模组为修改版时，此模组文件内icon微标无法显示，会显示为
![image](https://github.com/user-attachments/assets/c0888902-d684-4c87-9eff-bd77c25a87de)
可以让模组内自带的icon微标显示出来
![image](https://github.com/user-attachments/assets/c98263fe-92dc-40b9-8e2e-49e95b163763)
有助于查找模组

### 原因

有助于查找模组

**Comment by lactobionicAcid** [comment]
#4815

**Comment by Cai-kunkun** [comment]
> #4815
好叭

**Comment by allMagicNB** [comment]
#2955
