### ISSUE TITLE
openbmclapi仪表盘

### ISSUE THREAD

**Issue by dd2024is2013** [Hex-Dragon/PCL2#4844]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

look at the picture 能上github不是网问题吧？

![捕获](https://github.com/user-attachments/assets/b4be46a1-7767-43d5-a718-8187e593d073)

### 重现步骤

1、点击openbmclapi仪表盘
2、回主页

### 日志与附件

我不懂
[Log1.txt](https://github.com/user-attachments/files/17172881/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17172882/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17172883/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17172884/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17172885/Log5.txt)

**Comment by Joker2184** [comment]
![QQ截图20240928140728](https://github.com/user-attachments/assets/b9922f54-944e-4b30-8115-1ca6c832cd79)
测试正常
请检查网络

**Comment by Dongyanmio** [comment]
这玩意套了个cf，部分地区访问异常应该是正常情况吧

**Comment by Mxmilu666** [comment]
因为此主页基于 `CloudFlare Worker` 由于一些原因，部分地区无法访问是正常现象，我们也在积极寻找别的解决方案，谢谢谅解(x

**Comment by dd2024is2013** [comment]
6

**Comment by JingHai-Lingyun** [comment]
这不是 PCL 的问题，请向主页作者寻求帮助，先关了 Orz……
