### ISSUE TITLE
添加最大化功能，并支持windows贴靠/分屏

### ISSUE THREAD

**Issue by Steven7559** [Hex-Dragon/PCL2#4846]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

在最小化和关闭按钮之间添加最大化/还原功能，支持窗口贴靠及分屏

### 原因

我需要这个功能来进行分屏/最大化。没有这个功能，就不能分屏/最大化了。

**Comment by JingHai-Lingyun** [comment]
- 最大化见 #90
- 贴边/分屏见 #4088
