### ISSUE TITLE
删除Mod

### ISSUE THREAD

**Issue by LemonGasRoot** [Hex-Dragon/PCL2#4847]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

自己看捏
![屏幕截图 2024-09-28 181011](https://github.com/user-attachments/assets/3fdedb9e-615e-4959-a74c-cc4abd126223)

### 重现步骤

1、安装两遍同样的不同版本的模组（我哪知道我怎么安上的？？？）
2、回到启动页面，点击版本设置
3、点击Mod管理，删除一个重复的模组
4、报错力！！！！！！！

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/17174022/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17174023/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17174024/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17174025/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17174026/Log5.txt)

**Comment by JingHai-Lingyun** [comment]
此 Bug 修复于 2.8.7，2.8.7 目前只在 Snapshot（快照渠道）上推送，请等待后续更新

**Comment by LemonGasRoot** [comment]
FUUUUUUUUUU (beep...)
