### ISSUE TITLE
pcl2打不开 短程主时钟执行异常

### ISSUE THREAD

**Issue by siwanbm** [Hex-Dragon/PCL2#4852]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![75D250F3CFB683B94E848BF96C20A55D](https://github.com/user-attachments/assets/23fc85be-c362-45bf-af05-2dab62adbc09)

### 重现步骤

1、点击xxxx
2、往下滚，然后点击xxxx
启动pcl2 就会这样  

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/17189575/Log1.txt)

**Comment by Pigeon0v0** [comment]
使用镜像更新系统
