### ISSUE TITLE
“音频设备变更”导致的音频播放失败

### ISSUE THREAD

**Issue by chezixiang** [Hex-Dragon/PCL2#4853]
### 检查项

- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我的电脑只有一个音响，没有连接蓝牙设备，但我在使用PCL的过程中（某次启动时）提示“由于音频设备变更，音乐播放功能在重启 PCL 后才能恢复！”
已尝试重启电脑和PCL2,无效
备注：我的Windows是英文版

### 重现步骤

1、打开PCL(如果打开过就不用了，这一步是为了创建Musics文件夹)
2、把MP3放进Musics文件夹
3、重启PCL
4、提示“由于音频设备变更，音乐播放功能在重启 PCL 后才能恢复！”
至少我的电脑是这样

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/17190301/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17190302/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17190304/Log3.txt)

我是用的全新PCL2,没有生成Log4~5.
我使用的MP3：
[minecraft.zip](https://github.com/user-attachments/files/17190356/minecraft.zip)

**Comment by Joker2184** [comment]
emm.jpg?
不算Bug吧....

**Comment by LTCatt** [comment]
Log 里没有看到那句提示。
如果可以复现，先复现一次，再重新上传 Log。如果不能，在缺少信息的情况下我没法去修……

**Comment by chezixiang** [comment]
[Log1.txt](https://github.com/user-attachments/files/17194165/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17194167/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17194168/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17194169/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17194170/Log5.txt)
这是复现后的log，貌似在我的这次启动中只有log1被修改了
（现在大家都不睡觉的吗）（小声）

**Comment by LTCatt** [comment]
在 2.8.8 中添加了相关日志，需要等到下次更新之后，再复现并上传 Log……
麻烦您了……

**Comment by chezixiang** [comment]
那就等着（）

**Comment by chezixiang** [comment]
[Log1.txt](https://github.com/user-attachments/files/17238889/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17238890/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17238891/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17238892/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17238893/Log5.txt)
在更新后复现了

**Comment by LTCatt** [comment]
```
[11:58:22.713] 播放音乐出现内部错误（H:\Genshin x MC\PCL\Musics\minecraft.mp3）：NoDriver calling acmFormatSuggest
   在 NAudio.Wave.Compression.AcmStream.SuggestPcmFormat(WaveFormat compressedFormat)
   在 NAudio.Wave.AcmMp3FrameDecompressor..ctor(WaveFormat sourceFormat)
   在 NAudio.Wave.Mp3FileReader.CreateAcmFrameDecompressor(WaveFormat mp3Format)
   在 NAudio.Wave.Mp3FileReader..ctor(Stream inputStream, FrameDecompressorBuilder frameDecompressorBuilder)
   在 NAudio.Wave.Mp3FileReader..ctor(String mp3FileName)
   在 NAudio.Wave.AudioFileReader.CreateReaderStream(String fileName)
   在 NAudio.Wave.AudioFileReader..ctor(String fileName)
   在 PCL.ModMusic.MusicLoop(Boolean IsFirstLoad)
错误类型：NAudio.MmException
```

确实是第三方问题。
Stackoverflow 上说可以装这个解决：https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc772567(v=ws.11)?redirectedfrom=MSDN
