### ISSUE TITLE
在“Mod管理”界面内有名字过长的mod时引起卡顿

### ISSUE THREAD

**Issue by Raisel0** [Hex-Dragon/PCL2#4854]
### 检查项

- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

打开Mod管理时，如果有名字过长的mod时会引发卡顿问题
例如 Minecraft Chromium 嵌入式框架 mod（mod链接：https://www.mcmod.cn/class/8644.html）
具体表现为：mod名称会不断在省略号处闪烁，卡顿问题出现，并且鼠标滚轮难以滚动界面，且只会在Mod管理界面出现，如果切换到“概览”或者“设置”栏，卡顿问题消失，删除名字过长的mod后问题也会消失
另外如果将窗口大小调整至足以显示完整mod名称此问题也可以解决...

### 重现步骤

1.点击“下载”
2.搜素任意一个名字较长的模组（我是在使用 Minecraft Chromium 嵌入式框架mod时出现的问题，可以尝试使用此mod重现 mod链接：https://www.mcmod.cn/class/8644.html）
3.安装完成后点击“启动”→“版本设置”→“Mod管理”
4.问题应该会出现，mod名称不断闪烁，界面出现卡顿
注意：如果无法复现可以将窗口调小至不足以显示完整mod名称就会出现...

### 日志与附件

[Log4.txt](https://github.com/user-attachments/files/17191919/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17191920/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/17191921/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17191923/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17191924/Log3.txt)

**Comment by JingHai-Lingyun** [comment]
已确认，上述步骤 4 中的问题均可以再现

[复现时所用的模组：mcef-fabric-2.1.4-1.20.1.jar.zip](https://github.com/user-attachments/files/17193183/mcef-fabric-2.1.4-1.20.1.jar.zip)

[调试模式 Log1.txt](https://github.com/user-attachments/files/17193195/Log1.txt)

<details>
<summary>Bug 体现时改变窗口大小发生的奇怪现象，大图</summary>

![image](https://github.com/user-attachments/assets/5a46f47a-15f4-4118-8ae7-f757f11b3224)

</details>

**Comment by Raisel0** [comment]
识别码要求

**Comment by LTCatt** [comment]
你的解锁码：XLjsyQ5Z+pczlP5ml+Wnq2WcLS1phcOb
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
