### ISSUE TITLE
联机界面可以通过其他方式打开

### ISSUE THREAD

**Issue by Aminos114514** [Hex-Dragon/PCL2#4859]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

联机界面通过页面跳转的方式激活

### 重现步骤

1、使用自定义主界面文件编辑主界面
2、输入”<local:MyButton Grid.Column="0" Height="35" Margin="0,0,10,10" ColorType="Red"
Text="XXXX” EventType="切换页面" ToolTip="跳转至“设置”" EventData="2|1"/>”
3、载入主界面
4、使用这个创建的按钮
5，来到了联机界面

### 日志与附件

[联机界面出现.txt](https://github.com/user-attachments/files/17197629/default.txt)

**Comment by Deep-Dark-Forest** [comment]
#2784
