### ISSUE TITLE
启用/禁用 Mod 时出现未知错误：索引必须位于该列表的界限内

### ISSUE THREAD

**Issue by EasyGuo114514** [Hex-Dragon/PCL2#4862]
### 检查项

- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我在正常使用pcl，发现游戏无法启动，于是准备删除新添加的mod，在点击禁用（或者删除）后出现
![PixPin_2024-10-01_10-11-55](https://github.com/user-attachments/assets/75be3391-5310-462d-9ef5-f6c5c27ec8e3)

### 重现步骤

无法重现!，

### 日志与附件

[Log3.txt](https://github.com/user-attachments/files/17198471/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17198472/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17198473/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/17198474/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17198475/Log2.txt)

**Comment by LTCatt** [comment]
EDMods.Insert OutOfRange
log3 Ln 1520

**Comment by WorldHim** [comment]
复现了

**Comment by EasyGuo114514** [comment]
WorldHim牛逼啊，还真能
![Uploading Clip_2024-10-01_20-57-04.png…]()

**Comment by Qiu-Quanzhi** [comment]
无意复现了，确实是在mod列表搜索过后的bug

**Comment by Cai-kunkun** [comment]
![image](https://github.com/user-attachments/assets/421e23b6-cde8-40cd-8010-d7290babcd71)
复现成功

**Comment by zhangzihan114514** [comment]
可以复现，我发布过了[https://github.com/Hex-Dragon/PCL2/issues/4900#event-14512842606](url)

**Comment by zhangzihan114514** [comment]
我有演示视频[EDMods.Insert OutOfRange
log3 Ln 1520](url)

**Comment by qffylqwq** [comment]
好几天前出现过......但是没反馈。今天有出现了，log如下

[21:31:41.477] [Control] 按下图标按钮
[21:31:41.483] [System] 执行外部命令：explorer.exe /select,"D:\.minecraft\versions\生电1.21\mods\[极简血量显示] Neat-1.21-38-FABRIC.jar.disabled"
[21:31:41.871] [Animation] 两个动画帧间隔 225 ms
[21:31:47.903] [Animation] 两个动画帧间隔 178 ms
[21:31:54.354] [Control] 按下图标按钮：BtnTitleMin
[21:32:00.647] NetRequestOnce 失败：连接服务器超时，请检查你的网络环境是否良好（操作超时，https://api.modrinth.com/v2/version_files）
你的网络环境不佳，导致难以连接到服务器。请检查网络，多重试几次，或尝试使用 VPN。
————————————
详细错误信息：
→ 操作超时
   在 System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   在 System.Net.HttpWebRequest.GetRequestStream()
   在 PCL.ModNet.NetRequestOnce(String Url, String Method, Object Data, String ContentType, Int32 Timeout, Dictionary`2 Headers, Boolean MakeLog, Boolean UseBrowserUserAgent)
错误类型：System.Net.WebException
[21:32:00.647] [Net] 发起网络请求（POST，https://mod.mcimirror.top/modrinth/v2/version_files），最大超时 30000
[21:32:00.979] NetRequestOnce 失败：服务器返回错误（ProtocolError，远程服务器返回错误: (404) 未找到。，https://mod.mcimirror.top/modrinth/v2/version_files）
null
→ 远程服务器返回错误: (404) 未找到。
   在 System.Net.HttpWebRequest.GetResponse()
   在 PCL.ModNet.NetRequestOnce(String Url, String Method, Object Data, String ContentType, Int32 Timeout, Dictionary`2 Headers, Boolean MakeLog, Boolean UseBrowserUserAgent)
错误类型：System.Net.WebException
[21:32:00.979] [Net] 发起网络请求（POST，https://api.modrinth.com/v2/version_files），最大超时 60000
[21:32:01.751] 加载位图失败（C:\Users\NightWillows\AppData\Local\Temp\PCL\CompLogo\12673158267540459614.png412）：参数无效。
   在 System.Drawing.Bitmap..ctor(Stream stream)
   在 PCL.MyBitmap..ctor(String FilePathOrResourceName)
错误类型：System.ArgumentException
[21:32:01.754] 读取本地 Mod 图标失败（C:\Users\NightWillows\AppData\Local\Temp\PCL\CompLogo\12673158267540459614.png）：参数无效。
   在 System.Drawing.Bitmap..ctor(Stream stream)
   在 PCL.MyBitmap..ctor(String FilePathOrResourceName)
   在 PCL.MyLocalModItem._Closure$__7-1._Lambda$__0()
错误类型：System.ArgumentException
[21:32:01.755] [Net] 直接下载文件：https://cdn.modrinth.com/data/bXX9h73M/icon.svg
[21:32:07.224] 加载位图失败（C:\Users\NightWillows\AppData\Local\Temp\PCL\CompLogo\12673158267540459614.png412）：参数无效。
   在 System.Drawing.Bitmap..ctor(Stream stream)
   在 PCL.MyBitmap..ctor(String FilePathOrResourceName)
错误类型：System.ArgumentException
[21:32:07.225] 读取本地 Mod 图标失败（C:\Users\NightWillows\AppData\Local\Temp\PCL\CompLogo\12673158267540459614.png）：参数无效。
   在 System.Drawing.Bitmap..ctor(Stream stream)
   在 PCL.MyBitmap..ctor(String FilePathOrResourceName)
   在 PCL.MyLocalModItem._Closure$__7-1._Lambda$__0()
错误类型：System.ArgumentException
[21:32:07.226] 下载本地 Mod 图标失败（https://cdn.modrinth.com/data/bXX9h73M/icon.svg）：参数无效。
   在 PCL.MyLocalModItem.LogoLoader(String LocalFileAddress)
错误类型：System.ArgumentException

**Comment by adsf7878** [comment]
不止，就是有问题，我的搜索栏是干净的启用mod也会有这种情况

**Comment by LTCatt** [comment]
已经知道怎么复现了就没有必要再发了，多谢各位

**Comment by fauilfd** [comment]
好家伙，我也复现了，添加模组呢，出错了，禁用就崩溃了，我这最少六次了
![A26DA6E2275A11AFFD5204AE2508FF6A](https://github.com/user-attachments/assets/23b99c0f-fa34-4c29-9795-712b2151d34a)

**Comment by EasyGuo114514** [comment]
赶紧!识别码

**Comment by LTCatt** [comment]
你的解锁码：ijRegYiZb+aR62BL6L9ocrAC7AqSj5sT
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by EasyGuo114514** [comment]
ok，谢了

**Comment by Txt-Text** [comment]
刚刚复现，跑到issue就看到有人提交过了，话说新版pcl问题真的有点多了，龙猫先专心修bug吧

**Comment by iceqiuqwq** [comment]
不止，使用筛选也会，我是在禁用列表启用mod也会出现这种情况

**Comment by iceqiuqwq** [comment]
还有就算不搜索也会出现这种情况，貌似只有特定mod才会

**Comment by Deep-Dark-Forest** [comment]
PCL 不具有热更新功能，请等待下次发版……

**Comment by 11419149** [comment]
![19707cad7ca0be8ba7c97d8cceddc4ed](https://github.com/user-attachments/assets/f38c3e9f-434d-45e0-80f2-7eb196097f36)
2.8.8没修
希望能修一下这个bug

**Comment by 11419149** [comment]
> 还有就算不搜索也会出现这种情况，貌似只有特定mod才会

可能吧，betterend mod复现了

**Comment by Ad-closeNN** [comment]
> 2.8.8没修 希望能修一下这个bug

PCL 的 更新**不是热更新**，这里指的**完成**是指代码修复完毕而不是版本推送完毕
请等待下次版本发布（如**2.8.9**）

**Comment by Deep-Dark-Forest** [comment]
2.8.9 已经发版，所以解锁评论区。
