### ISSUE TITLE
添加导出mod列表

### ISSUE THREAD

**Issue by ZXLQ114514** [Hex-Dragon/PCL2#4865]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

在版本设置/Mod管理中添加导出mod列表的选项,输出位置可以为游戏根目录或者PCL文件夹内,可以以txt形式或者其他格式(如果做的话)输出
我对其识别出来的信息格式为:[PCL2识别到的模组名]-[游戏版本+模组版本]-[原文件名]

### 原因

我需要这个功能来进行版本升级。我并不确定是否很多人都有在面对模组多的情况下更换游戏版本/解决模组名称乱码的需求，如果有这个功能，就可以方便的进行模组的对照/识别。

**Comment by allMagicNB** [comment]
整合包是干啥的

**Comment by LTCatt** [comment]
适用面不大，暂时不考虑，抱歉）
