### ISSUE TITLE
中文路径、中文用户名下打开启动器出错

### ISSUE THREAD

**Issue by h7f8** [Hex-Dragon/PCL2#4869]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在“百宝箱”中点击“清理游戏垃圾”后，出现“加载帮助列表UI失败”的错误
![BUG](https://github.com/user-attachments/assets/04b22e14-57d4-47ae-9d4a-34c3bba65707)
然后切换到PCL主界面，点击版本设置，出现“未能找到路径”的错误
![BUG2](https://github.com/user-attachments/assets/e4816728-0581-49d0-9c44-da8b591bbc71)

### 重现步骤

1、点击“更多”
2、然后点击“百宝箱”
3、再点击“清理游戏垃圾”

### 日志与附件

[Log5.txt](https://github.
[Log2.txt](https://github.com/user-attachments/files/17212955/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17212956/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17212957/Log4.txt)
[Log1.txt](https://github.com/user-attachments/files/17212954/Log1.txt)

**Comment by h7f8** [comment]
[Log5.txt](https://github.com/user-attachments/files/17213097/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/17213098/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17213099/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17213100/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17213101/Log4.txt)

**Comment by JingHai-Lingyun** [comment]
清理游戏垃圾错误的清除了第三方 dll 库文件

**Comment by Pigeon0v0** [comment]
建议修改标题：未能找到路径“C:\ProgramData\PCL\libwebp.dll”的一部分

刚刚没搜到 = =

**Comment by heiman114514** [comment]
已经修复啦

**Comment by Pigeon0v0** [comment]
@LTCatt 这个 BUG 影响面极其大，很大一部分更新到新版本的用户都炸了，我有个群除了联机问题问的就是这个问题...

能不能先推个紧急更新之类的来...

**Comment by LTCatt** [comment]
只要重启 PCL 就能解决、没有影响到下载-启动的主流程、不是大概率触发，其实就还好 Orz……
现在发一次全版本更新要一千多块……
我先挂一个 Pin 吧……

**Comment by tangge233** [comment]
出错用户的报错路径基本都是 ProgramData，缓存文件夹又炸？

**Comment by LTCatt** [comment]
缓解：在 C:\ProgramData\ 下创建名为 PCL 的文件夹，然后重启 PCL
