### ISSUE TITLE
切换游戏版本时遇到问题

### ISSUE THREAD

**Issue by cacheci** [Hex-Dragon/PCL2#4870]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

启动器版本：2.8.8.0
已确认文件可写入。（vscode和Windows记事本）
已确认文件权限正常。
已确认文件并非只读。
已使用管理员权限启动启动器重试。
从某次心血来潮更新了下启动器就出现了这个问题。本来怀疑是权限系统的问题，但是其他软件写入同一个文件就没有问题。
未知是微软屎山的锅还是启动器的问题。如果是微软的问题那就直接关了这个issue好了。

附：错误状态与 PCL.ini 权限
![image](https://github.com/user-attachments/assets/64419715-a48f-4e29-9cf5-0f278190b69a)
![image](https://github.com/user-attachments/assets/3be1ee4f-6904-432f-bd5a-02aa9d016748)

### 重现步骤

点击版本选择
切换游戏版本

### 日志与附件

详细错误信息：
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   在 System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   在 System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding)
   在 PCL.ModBase.WriteFile(String FilePath, String Text, Boolean Append, Encoding Encoding)
   在 PCL.ModBase.WriteIni(String FileName, String Key, String Value)
错误类型：System.UnauthorizedAccessException
[04:59:59.363] 写入文件失败（D:\Minecraft\.minecraft\PCL.ini → CardValue3:1.20.4:1.19.3:1.16.5:）：对路径“D:\Minecraft\.minecraft\PCL.ini”的访问被拒绝。
PCL 的权限不足。请尝试右键 PCL，选择以管理员身份运行。

**Comment by cacheci** [comment]
经过反复测试发现是由文件为隐藏文件导致引发 UnauthorizedAccessException 异常。
根据 [微软的说明](https://learn.microsoft.com/zh-cn/dotnet/api/system.io.filemode?view=net-8.0#--)：“如果该文件已存在但为隐藏文件，则将引发 [UnauthorizedAccessException](https://learn.microsoft.com/zh-cn/dotnet/api/system.unauthorizedaccessexception?view=net-8.0) 异常。”
以前隐藏文件都没问题的，现在好像有点问题。
可能是 c# 的 StreamWriter 导致的？不清楚如果要修是否需要更换写入方式啥的。
不是什么大问题，大不了解除隐藏就行了，但确实挺怪的。

**Comment by sulingjiang** [comment]
>以前隐藏文件都没问题的，现在好像有点问题。

微软脑子有包导致的
