### ISSUE TITLE
未能找到路径“C:\ProgramData\PCL\libwebp.dll”的一部分

### ISSUE THREAD

**Issue by Pigeon0v0** [Hex-Dragon/PCL2#4871]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

检索关键词：WebP 未能找到路径

在切换到一个有图片加载的页面时，会抛出这个报错，疑似是引入 WebP 导致的

Note: 转自 QQ 3262564401

### 重现步骤

切换到一个有图片加载的页面

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/17219720/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17219716/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17219717/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17219718/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17219719/Log5.txt)

Log1 Ln 58 84 193 等

**Comment by Ad-closeNN** [comment]
- #4869?

**Comment by Pigeon0v0** [comment]
GitHub 搜索挨打，大概是和 #4869 同一个...

**Comment by heiman114514** [comment]
我也是
