### ISSUE TITLE
在手动安装中添加使用本地的安装器进行安装

### ISSUE THREAD

**Issue by Bread-NiceCat** [Hex-Dragon/PCL2#4876]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

[cleanroom](https://www.mcmod.cn/class/9689.html)或者其他小众的forge分支有已修改的安装器，而pcl无法使用本地的安装器进行安装

### 原因

![54df61b114c8389d9f42f72ca3264a6e](https://github.com/user-attachments/assets/bbe83b3c-51dd-43ed-97dd-57769bf6116d)

**Comment by hejiehao** [comment]
Cleanroom 的话 https://github.com/Hex-Dragon/PCL2/discussions/3004

**Comment by JingHai-Lingyun** [comment]
- Cleanroom 请投票：#3004
- 其他情况下，你应当手动安装他们。因为那不是标准安装包，也很难兼容……
  安装之后你应当可以根据对应文档配置启动选项来用 PCL 启动

**Comment by LTCatt** [comment]
暂时不考虑提供此类选项，因为直接使用手动安装包已经可以满足需求。

**Comment by hejiehao** [comment]
重命名该版本？

**Comment by Bread-NiceCat** [comment]
> 重命名该版本？

即启动mc的jar被重命名过，而不是普通的1.12.2.jar之类的

**Comment by Pigeon0v0** [comment]
那你先用手动安装器装好了以后重命名不就完了 = =
