### ISSUE TITLE
新版本2.8.8启动器网页登录账号报错

### ISSUE THREAD

**Issue by asdnbg** [Hex-Dragon/PCL2#4878]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

启动器更新到最新版2.8.8后提示正版账号需要网页重新登录，但是网页登录成功了，启动器也提示网页登录成功，然后报错

### 重现步骤

1、点击登录
2、复制代码，到网页输入代码
3、微软正版登录后授权
4、跳转到启动器，提示网页登录成功
5、弹出报错提示，启动器登录失败

### 日志与附件

[Uploading Log1.txt…]()

**Comment by Ad-closeNN** [comment]
你的日志没传上来
