### ISSUE TITLE
看不懂英语

### ISSUE THREAD

**Issue by ergecfr** [Hex-Dragon/PCL2#4879]
### 检查项

- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

太卡了 动画没有以前流畅了

### 原因

这项优化让我可以更方便地使用。
如果没有这项优化，我每次都必须忍受卡卡的界面

**Comment by JingHai-Lingyun** [comment]
……？
请提供你的 PCL 日志以允许我们分析卡顿来源

**Comment by Cai-kunkun** [comment]
可以把动画关了

**Comment by kndxhz** [comment]
![image](https://github.com/user-attachments/assets/7f1c44df-8bd0-4a83-982d-0b4375807225)
请按照此步骤关闭动画，另外请把标题改一下

**Comment by Cai-kunkun** [comment]
建议改为“”很好的动画，使我的电脑卡顿“”

**Comment by JingHai-Lingyun** [comment]
请不要发送与  Issue 正文提到的 Bug 所无关的内容，感谢。
请 Author @ergecfr 根据 kndxhz 上述的方式尝试关闭动画之后看看是否会更加流畅

**Comment by baguotao233** [comment]
一些 7 代以前的 CPU 如果只有核显确实会卡，我也遇到过，这个属于设备性能问题，当然如果说有更好的电脑这个情况就不会出现（7 代前的 CPU 原版 1.18+ mc30p 都撑死了吧）

**Comment by Deep-Dark-Forest** [comment]
超时关闭。
