### ISSUE TITLE
在Windows设置里切换单声道音频会导致PCL播放下一首歌

### ISSUE THREAD

**Issue by Crotina** [Hex-Dragon/PCL2#4880]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在Windows设置里面切换单声道音频，PCL会自己播下一首歌

![image](https://github.com/user-attachments/assets/fb184fa5-1d12-4e8c-8052-650980061d62)

### 重现步骤

1、打开PCL并放置至少2首歌曲在music，然后开始播放
2、打开Windows设置
3、找到 轻松使用 > 音频
4、点击 "打开单声道音频按钮"
5、即使没有播放完，PCL也会自己开始下一个

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/17230175/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17230177/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17230178/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17230182/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17230183/Log5.txt)

**Comment by LTCatt** [comment]
同样是 NAudio 的音频设备切换问题，修不了（
