### ISSUE TITLE
模组与整合包版本筛选中无整数版本，除了1.21

### ISSUE THREAD

**Issue by WangYiBen0** [Hex-Dragon/PCL2#4882]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如题，没有1.20及以下的筛选条件，但有1.21

### 重现步骤

1、点击【下载】，在【资源】中选择【Mod】或【整合包】
2、查看条件，发现整版本只有1.21，而无1.20 1.19等

### 日志与附件

这就不用log了吧……
[Log1.txt](https://github.com/user-attachments/files/17230466/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17230457/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17230458/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17230460/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17230461/Log5.txt)

**Comment by JingHai-Lingyun** [comment]
参考上述内容，有需要的话你可以直接输入指定版本号来搜索
