### ISSUE TITLE
更新mod失败

### ISSUE THREAD

**Issue by vocaloidkiss** [Hex-Dragon/PCL2#4886]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

弹出提示：Mod 更新失败：文件 SHA1 应为 8744da69855746d4a7e5fc00de3de3c8af6f1e84，实际为 b50f6649b855e1fc4ad8ab6eb1b316a28f5fa33d → 文件下载失败：C:\Users\11960\AppData\Local\Temp\PCL\DownloadedMods\[自定义物品堆叠] stackitem64-1.1.1.jar.disabled 

### 重现步骤

启动器内更新mod

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/17240228/Log1.txt)

**Comment by JingHai-Lingyun** [comment]
草，请求了下载 .jar.disabled 文件…… 这样 SHA 值永远对不上……

**Comment by vocaloidkiss** [comment]
hhhh

**Comment by zkitefly** [comment]
按理说，文件名应该不影响 SHA1 计算的呀🤔

**Comment by vocaloidkiss** [comment]
已定位问题，[自定义物品堆叠] stackitem64-1.1.0.jar更新即使不加disabled也会失败
[Log1.txt](https://github.com/user-attachments/files/17245013/Log1.txt)

**Comment by pysio2007** [comment]
ModrinthAPI提供了两组Hash 指向同一个下载链接
https://api.modrinth.com/v2/project/qVtYMgSP/version
modrinth的返回结果是
```
      {
        "hashes": {
          "sha1": "8744da69855746d4a7e5fc00de3de3c8af6f1e84",
          "sha512": "e07ab79f8773f9d72101158576f66c5c0e072ec9340235d5010c776b19bf70e62d29e3a365040aa02b40122e77e73efb7d3ec93b6dd081688b5b980567592373"
        },
        "url": "https://cdn.modrinth.com/data/qVtYMgSP/versions/ZJfYNdXc/stackitem64-1.1.1.jar",
        "filename": "stackitem64-1.1.1.jar",
        "primary": true,
        "size": 19084,
        "file_type": null
      },
      {
        "hashes": {
          "sha512": "5a111f76b63fd6570230bd19f0c5daafa1b695eec8fd3913e765ebf58f04a87079f3e58f6fe72da9fad526bb924982805f006839669aa3c11ea2aef3238ea940",
          "sha1": "b50f6649b855e1fc4ad8ab6eb1b316a28f5fa33d"
        },
        "url": "https://cdn.modrinth.com/data/qVtYMgSP/versions/ZJfYNdXc/stackitem64-1.1.1.jar",
        "filename": "stackitem64-1.1.1.jar",
        "primary": false,
        "size": 19124,
        "file_type": null
      }
    ],
```
两个字段的size都不一样 但是指向的下载链接一样
其中 下面这一组的SHA1可以对上

**Comment by z0z0r4** [comment]
sha1错误，无解...

**Comment by vocaloidkiss** [comment]
可以给我码吗

**Comment by vocaloidkiss** [comment]
不是说无解嘛哈哈哈哈哈

**Comment by LTCatt** [comment]
向 Modrinth 那边发了个邮件 =。=

**Comment by vocaloidkiss** [comment]
好哦

**Comment by vocaloidkiss** [comment]
@LTCatt modrith那边改了，结果更新文件变成这个了
![屏幕截图 2024-10-10 115854](https://github.com/user-attachments/assets/fd225dd9-2b41-4cd4-8869-9ac59f7b9caf)
逆天

**Comment by LTCatt** [comment]
![image](https://github.com/user-attachments/assets/0683c7ea-b566-48a0-b943-6a7807205165)
无法重现？
发下出问题的 mod 文件试试

**Comment by vocaloidkiss** [comment]
现在估计换源成功了，之前文件不对指向的是realstevesleep，现在是正常的了

**Comment by vocaloidkiss** [comment]
再次出现此问题，Modrinth网站上不存在此模组该版本，但自动更新检测到了另外的模组
![图片](https://github.com/user-attachments/assets/2904298a-beea-4191-906d-ad83ec02c613)
![图片](https://github.com/user-attachments/assets/137c548d-e6f9-4579-bf6f-21152ab61a3a)

**Comment by vocaloidkiss** [comment]
@LTCatt

**Comment by vocaloidkiss** [comment]
[Uploading [世界生成优化]双端 noisium-fabric-2.3.0+mc1.21-1.21.1.zip…]()

**Comment by vocaloidkiss** [comment]
我认为我找的问题所在了，与PCL2无关，此模组作者在不定时挂羊头卖狗肉，将此模组在Modrinth下载地址换源为realstevesleep的
![图片](https://github.com/user-attachments/assets/b8b82e6f-12db-4477-8417-344034ad0b72)

**Comment by vocaloidkiss** [comment]
![图片](https://github.com/user-attachments/assets/4e4ccfc9-f235-4ad3-8c30-f55f200129be)
此模组作者回复
