### ISSUE TITLE
未知错误

### ISSUE THREAD

**Issue by zsz-of** [Hex-Dragon/PCL2#4888]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

显示未知错误，直接退出

### 重现步骤

在模组查看页面，禁用模组

### 日志与附件

[Log5.txt](https://github.com/user-attachments/files/17240720/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/17240721/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17240722/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17240723/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17240724/Log4.txt)

**Comment by Ad-closeNN** [comment]
- #4862
