### ISSUE TITLE
无光影可以正常启动mc但是在添加光影后载入地图时mc崩溃

### ISSUE THREAD

**Issue by waeefra** [Hex-Dragon/PCL2#4890]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃基本不是 PCL 的原因，请 **不要** 提交反馈。你可以在论坛或社区找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用 HMCL 启动，HMCL 没有出现问题。** 如果 HMCL 也无法启动就不是 PCL 导致的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

无光影可以正常启动mc但是在添加光影后载入地图时mc崩溃

### PCL 错误报告、日志与附件

[Log1.txt](https://github.com/user-attachments/files/17244089/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17244090/Log2.txt)

**Comment by tangge233** [comment]
HMCL 可以启动的话上传一下启动脚本

**Comment by SALTWOOD** [comment]
光影一般是电脑硬件问题，升级一下显卡驱动，试试 HMCL

**Comment by wuliaodexiaoluo** [comment]
>mc崩溃

请上传崩溃报告

**Comment by LTCatt** [comment]
请补充崩溃报告。
由于超时暂时关闭，可以继续在这里回复。
