### ISSUE TITLE
建议自定义主页.xaml可以调取某一服务器的基本信息

### ISSUE THREAD

**Issue by Inter-Knot-User** [Hex-Dragon/PCL2#4893]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

就比如{serverip="xxx".player}显示服务器玩家，{serverip="xxx".online}显示服务器是否在线

### 原因

我需要这个功能来显示服务器状态。很多人都有这个的需求，但如果没有这个功能，就不能显示服务器状态了。

**Comment by JingHai-Lingyun** [comment]
- #829 
   提到了此功能，已经被拒绝……
   > 这个提案太超出启动器的范围了……

**Comment by Inter-Knot-User** [comment]
> * [一个新的功能！使用 PCL2 启动器与 Minecraft 服务器交互！ #829](https://lgithub.xyz/Hex-Dragon/PCL2/issues/829)
>   提到了此功能，已经被拒绝……
>   > 这个提案太超出启动器的范围了……

收到（
