### ISSUE TITLE
我购买了minecraft，但是在登陆时提示没有购买minecraft

### ISSUE THREAD

**Issue by Windowsenthusiasts** [Hex-Dragon/PCL2#4896]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我完成了登录步骤，并且我有minecraft，但启动时提示我没有购买minecraft

### 重现步骤

1.点击登录
2.完成验证
3.等待登录步骤执行到5/6

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/17245927/Log1.txt)

**Comment by Deep-Dark-Forest** [comment]
#4174

**Comment by SALTWOOD** [comment]
是不是从 Google Play 购买的，是不是买基岩版送的 Java 版，打开官网登上账号看看也许能解决

**Comment by SALTWOOD** [comment]
是不是从 Google Play 购买的，是不是买基岩版送的 Java 版，打开官网登上账号看看也许能解决

**Comment by wuliaodexiaoluo** [comment]
> [22:30:31.484] NetRequestOnce 失败：服务器返回错误（ProtocolError，远程服务器返回错误: (400) 错误的请求。，
> https://login.live.com/oauth20_token.srf）
> {"error":"invalid_grant","error_description":"The provided value for the input parameter 'refresh_token' or 'assertion' is not valid. > The token was issued for a different client id","correlation_id":"e81ad481-99b1-4bc8-a20e-5ff4f9cba8bc"}
>→ 远程服务器返回错误: (400) 错误的请求。
>  在 System.Net.HttpWebRequest.GetResponse()
>   在 PCL.ModNet.NetRequestOnce(String Url, String Method, Object Data, String ContentType, Int32 Timeout, Dictionary`2 Headers, Boolean MakeLog, Boolean UseBrowserUserAgent)
错误类型：System.Net.WebException

不知道是否因为此问题导致的

**Comment by Windowsenthusiasts** [comment]
> 是不是从 Google Play 购买的，是不是买基岩版送的 Java 版，打开官网登上账号看看也许能解决

我是从Microsoft Store买的

**Comment by tangge233** [comment]
使用官方启动器登陆下后看看是否情况改善

**Comment by LTCatt** [comment]
![image](https://github.com/user-attachments/assets/28b3e076-978f-490f-bf3c-2c3d0c196ab5)
确实返回的是空，大概率不是 PCL 的问题。
请尝试在 HMCL 复现。
