### ISSUE TITLE
使用PCL2同时禁用多个模组会导致PCL2崩溃

### ISSUE THREAD

**Issue by andypeng1** [Hex-Dragon/PCL2#4897]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

多选一些mod，单击禁用时pcl2弹出报错
索引的目标必须在索引内

### 重现步骤

1、点击版本管理
2、然后点击mod管理
3、手动点击一些mod，再点击禁用

### 日志与附件

[Log.txt](https://github.com/user-attachments/files/17251118/Log.txt)
[Log1.txt](https://github.com/user-attachments/files/17251119/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17251120/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17251121/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17251122/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17251123/Log5.txt)

**Comment by Ad-closeNN** [comment]
- #4862
