### ISSUE TITLE
整合包安装问题

### ISSUE THREAD

**Issue by APIHHX** [Hex-Dragon/PCL2#4901]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

curseforge整合包文件拖入启动器窗口鼠标显示不可用

### 重现步骤

整合包文件拖入启动器窗口鼠标显示不可用

### 日志与附件

无日志

**Comment by hejiehao** [comment]
你是否使用了管理员身份启动 PCL？

**Comment by SALTWOOD** [comment]
是不是使用了管理员，是不是从压缩文件拖出来的
如果是的话，拖到桌面，不要用管理员启动 PCL，然后从桌面拖过去试试

**Comment by CLydq** [comment]
真的不是整合包本体包在压缩包内，你拖的压缩包内还有启动器这类非整合包安装必须的东西吗（

**Comment by APIHHX** [comment]
> 你是否使用了管理员身份启动 PCL？

是的，我是使用管理员运行的

**Comment by APIHHX** [comment]
> 你是否使用了管理员身份启动 PCL？

是的，我是使用管理员运行的

**Comment by APIHHX** [comment]
> 是不是使用了管理员，是不是从压缩文件拖出来的 如果是的话，拖到桌面，不要用管理员启动 PCL，然后从桌面拖过去试试

我是会安装整合包的，毕竟PCL2也用了快两年了 ，前端时间还可以的，这段时间突然就不行了

**Comment by APIHHX** [comment]
> 是不是使用了管理员，是不是从压缩文件拖出来的 如果是的话，拖到桌面，不要用管理员启动 PCL，然后从桌面拖过去试试

我是会安装整合包的，毕竟PCL2也用了快两年了 ，前端时间还可以的，这段时间突然就不行了

**Comment by JingHai-Lingyun** [comment]
> 是的，我是使用管理员运行的

由于 Windows UAC 的存在，PCL 以管理员身份启动时拖放会失效，这是已知问题
请将 PCL 以普通用户的身份启动，再拖放整合包文件
鉴于上述回复，以 `重复` 关闭此帖

参见：
- *需要社区帮助*&nbsp;&nbsp;&nbsp;#2531
