### ISSUE TITLE
forge无法进行局域网联机

### ISSUE THREAD

**Issue by OrangeCat847** [Hex-Dragon/PCL2#4910]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

你好，我的forge端1.19.2以后的版本均无法显示局域网房间（仅显示ipv6) fabric 正常 用的radmin进行联机
（已经影响了我的游戏体验）

### 重现步骤

1，进入游戏
2，打开多人游戏

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/17267803/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17267804/Log2.txt)

**Comment by Ad-closeNN** [comment]
这**不是***PCL的问题
- 第一种是Radmin这个本身的问题
- 第二种是IPv6协议栈的问题
