### ISSUE TITLE
热力系列 Mod 中文名显示错误

### ISSUE THREAD

**Issue by ChenMoFeiJin** [Hex-Dragon/PCL2#4916]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

CurseForge 上的 Thermal Expansion 基本信息显示为 `热力基本 | Thermal Foundation`
![image](https://github.com/user-attachments/assets/04e731b8-55fb-418b-a7ac-4777aebebe86)
但其对应的 Mod 文件都是是 Thermal Expansion
![image](https://github.com/user-attachments/assets/c633b033-e39d-48c4-bd43-b52c9eb8058c)
点击 `跳转到 CurseForge` 后进入的也是 Thermal Expansion 的界面

### 重现步骤

使用以下条件进行搜索，点击第一项：
- 名称：Thermal Expansion
- 来源：CurseForge
- 版本：1.20.1 任意 Mod 加载器
- 类型：全部

### 日志与附件

复现前已将老的日志文件删除，复现过程中仅生成了下面一个文件：
[Log1.txt](https://github.com/user-attachments/files/17269771/Log1.txt)

**Comment by ChenMoFeiJin** [comment]
E270-22D3-D286-8BFF

**Comment by LTCatt** [comment]
你的解锁码：wpQ+Fz6CDv10h1zPCEolrIbO8bMIDdr0
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
