### ISSUE TITLE
部分mod更新成另一个不同的mod

### ISSUE THREAD

**Issue by ExpertLotus9989** [Hex-Dragon/PCL2#4917]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/user-attachments/assets/845d3cae-573e-493d-8e2c-a7ac82820ddf)
右键打开更新日志会跳到Fps Reducer网页

### 重现步骤

1、点击mod管理
2、更新mod

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/17271278/Log1.txt)

**Comment by lactobionicAcid** [comment]
_被遗忘的 issue……_

可能与 #3738 重复……？

**Comment by LTCatt** [comment]
#4645
