### ISSUE TITLE
存档名称过长会被列入不常用版本

### ISSUE THREAD

**Issue by Xiaoganghei** [Hex-Dragon/PCL2#492]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://user-images.githubusercontent.com/118163634/204723767-12111a55-1034-4cc2-88bb-148a2dccbf3a.png)
如图，如果一个存档名称过长，就会出现被列入不常用版本这件事。并且我上面还下了一个下载方式一模一样的存档（1.19.2原版）
=。=

### 重现步骤

1.下载任意版本。
2.把名称搞得特别长！（我是直接输满了……）

### 日志与附件

无……我相信这并不需要日志的对吧
=。=

**Comment by LTCatt** [comment]
多个相同的原版版本只会保留一个

**Comment by Xiaoganghei** [comment]
哦哦
我还以为是名字过长的问题
