### ISSUE TITLE
关于内存优化

### ISSUE THREAD

**Issue by ThendJyc** [Hex-Dragon/PCL2#4920]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我不知道这个算不算Bug...... ：
如果你点击百宝箱中的内存优化
然后在PCL请求管理员时点"否"
PCL虽然会提示"获取管理员权限失败"
但还是会弹出"正在进行内存优化..."

### 重现步骤

点击百宝箱中的内存优化
在PCL请求管理员的弹窗中点"否"

### 日志与附件

[Log4.txt](https://github.com/user-attachments/files/17275700/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17275701/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/17275702/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17275704/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17275705/Log3.txt)

**Comment by kong-que-dnf123** [comment]
事实上你点击内存优化的那一刻起就已经弹出“正在进行内存优化”了
![image](https://github.com/user-attachments/assets/aac41238-4d57-4dab-b1df-00bd908f5fe6)

**Comment by ThendJyc** [comment]
我知道啊
这就是Bug的地方：）

**Comment by ThendJyc** [comment]
1C59-1430-1A9D-DCA6

**Comment by LTCatt** [comment]
你的解锁码：3uwq+vuZQSgoXYDeWsEQeevb3eadoeqz
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
