### ISSUE TITLE
添加重置设置为默认值选项

### ISSUE THREAD

**Issue by ThendJyc** [Hex-Dragon/PCL2#4922]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在"设置"页面中添加重置所有设置(或者某一部分设置)的选项

### 原因

我真的很想知道一些选项的默认选项是啥

**Comment by lactobionicAcid** [comment]
- #230 ?

**Comment by Deep-Dark-Forest** [comment]
> - #230 ?

这两个应该不一样，清除 PCL 所有数据应该会删除 PCL 文件夹里的音乐和图片，这个只是把设置还原了（应该吧）

**Comment by Deep-Dark-Forest** [comment]
好吧确实差不多……

**Comment by ThendJyc** [comment]
https://github.com/Hex-Dragon/PCL2/issues/230 这个指的不是把游戏文件什么的也全清除了吗.......

**Comment by Deep-Dark-Forest** [comment]
> https://github.com/Hex-Dragon/PCL2/issues/230 这个指的不是把游戏文件什么的也全清除了吗.......
> 

那不算是 PCL 的数据，因为如果你也用其他启动器也添加了相同的 Minecraft 文件夹就不是 PCL 数据了……（应该吧）

**Comment by WForst-Breeze** [comment]
你可以将鼠标悬浮于在左边栏选项上，在该选项右侧会出现重置按钮

**Comment by Deep-Dark-Forest** [comment]
> 反馈者意为允许重置「设置」中的设置项，而非初始化 PCL
> 
> 你可以将鼠标悬浮于在左边栏选项上，在该选项右侧会出现重置按钮

#230 反馈者也是重置**设置**中的设置项
> 把所有PCL2的不可在PCL2或PCL2文件夹里删除的**设置**清除，还原到出厂状态。
