### ISSUE TITLE
Mod版本更新错误

### ISSUE THREAD

**Issue by MNWZ211** [Hex-Dragon/PCL2#4925]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

模组 [Your Reputation](https://www.mcmod.cn/class/12123.html) 分别支持[玉 🔍](https://www.mcmod.cn/class/3482.html)和[What The Hell Is That](https://www.mcmod.cn/class/3471.html)两个版本的模组。目前支持”WTHIT“的最新版本为0.2.5，并且支持 ”“玉 🔍“的最新版本为0.2.4。**目前存档中使用的是”玉 🔍“模组（1.20.1），但Mod更新却提示需要将”Your Reputation“更新为”WTHIT“的0.2.5版本。** 如下图
<img width="437" alt="屏幕截图 2024-10-08 154212" src="https://github.com/user-attachments/assets/1bf659f2-aad4-4117-8aa1-027aee068f0f">
应该对这类模组判断一下。

已搜索了该模组的名称及查看了已打开的issue，如有类似关闭即可！

### 原因

~~（强迫症算吗[doge])））~~
优化后就没有这个错误了~~~

**Comment by LTCatt** [comment]
PCL 无法分辨此种情况（

**Comment by MNWZ211** [comment]
> PCL 无法分辨此种情况（

好的，还以为是这边的问题呢
