### ISSUE TITLE
整合包下载不成功

### ISSUE THREAD

**Issue by 99dee** [Hex-Dragon/PCL2#4928]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

下载整合包卡，然后跳出来

### 重现步骤

1、点击xxxx
2、往下滚，然后点击xxxx

### 日志与附件

![屏幕截图 2024-10-10 003813](https://github.com/user-attachments/assets/19a9033d-7f78-4aa2-87db-e42a30296489)
![屏幕截图 2024-10-10 003826](https://github.com/user-attachments/assets/44750593-123c-408b-a7bf-ec94191cf618)
游戏安装失败
→ 下载 Forge 36.2.34失败
→ 安装 Forge（方式 A）失败
→ 安装新 Forge 版本失败
→ 运行 Forge 安装器失败
→ Forge 安装器出错，日志结束部分为：
WARNING: Unknown module: cpw.mods.bootstraplauncher specified to --add-exports
����: �Ҳ������޷��������� com.bangbang93.ForgeInstaller
ԭ��: java.lang.ClassNotFoundException: com.bangbang93.ForgeInstaller
   在 PCL.ModDownloadLib._Closure$__35-0._Lambda$__7(LoaderTask`2 Task)
   在 PCL.ModLoader.LoaderTask`2._Closure$__13-0._Lambda$__0()
   在 PCL.ModDownloadLib._Closure$__35-0._Lambda$__7(LoaderTask`2 Task)
   在 PCL.ModDownloadLib.ForgelikeInjector(String Target, LoaderTask`2 Task, String McFolder, Boolean UseJavaWrapper, Boolean IsNeoForge)
   在 PCL.ModDownloadLib._Closure$__35-0._Lambda$__7(LoaderTask`2 Task)

**Comment by lactobionicAcid** [comment]
可能同 #4282，需要详细日志

**Comment by LTCatt** [comment]
请先触发一次这个问题，然后上传 PCL 文件夹中的 log1~5.txt

**Comment by LTCatt** [comment]
由于长时间未回复暂时关闭，如果有需要可以继续在这里回复
