### ISSUE TITLE
“清理游戏垃圾”不清理日志文件的选项

### ISSUE THREAD

**Issue by FlyModeZ** [Hex-Dragon/PCL2#4930]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

_**哦，天哪，你不知道日志里存着珍贵的聊天记录吗**_

### 原因

这项优化让我可以更方便地清理垃圾，而不是删除我的日志里的聊天记录。

如果有这项优化，我可以保留我珍贵的聊天记录。

**Comment by LTCatt** [comment]
清理就是清理……暂不考虑 orz
