### ISSUE TITLE
PCl在剩余内存充足的情况下因内存不足崩溃

### ISSUE THREAD

**Issue by Furry-XuanDan** [Hex-Dragon/PCL2#4931]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

PCL图标偏移，且在内存充足情况下崩溃.

### 重现步骤

启动多个整合包时，内存充足，但当启动日志中最后启动的整合包时，游戏先内存不足崩溃，【任务管理器显示还有大约一半左右内存】，游戏崩溃后，PCL也随之卡住，点击了一下窗口后崩溃，日志提示内存不足而崩溃，重新启动后PCL的图标位置偏移且图标显示异常,使用了TranslucentTB任务栏优化软件，未知是否与之有关，但在退出优化软件后问题依旧存在。尝试复现未成功。

### 日志与附件

[Log2.txt](https://github.com/user-attachments/files/17342808/Log2.txt)
[Log1.txt](https://github.com/user-attachments/files/17342809/Log1.txt)
![f6ae7c3ab25d9143b58d06c0f62f247e](https://github.com/user-attachments/assets/40f9dfaa-bd57-4d54-925b-f799cbe75132)
![5edaeff71a1e7b4fbaa8e3cd6718228a](https://github.com/user-attachments/assets/0af16caa-2876-4157-a1ef-4a3596e8c59c)

**Comment by lactobionicAcid** [comment]
与 #4252 重复；
这种情况一般为你的虚拟内存爆了。
