### ISSUE TITLE
关于修改版本描述

### ISSUE THREAD

**Issue by ThendJyc** [Hex-Dragon/PCL2#4932]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

<img width="666" alt="修改版本描述" src="https://github.com/user-attachments/assets/0b5f63d5-bde3-48b1-9d0e-ffeb0106cded">
我希望在保留默认版本描述的同时，在后面跟上自己的版本描述

### 原因

一般通过默认的版本描述就可以知道版本的基本信息
但一旦要对版本描述做修改就只能全部重打才能添加自己的版本描述
我希望可以选择在默认版本描述后添加自己的版本描述
例如：
1.20.1, Forge 47.3.0 | 最常用版本
|-- 默认版本描述---| |-添加的描述-|

**Comment by JingHai-Lingyun** [comment]
容我找找重复反馈在哪里…… 我处理过这个……
