### ISSUE TITLE
打开PCL时会自动弹出安装整合包

### ISSUE THREAD

**Issue by SakuraiMikoto** [Hex-Dragon/PCL2#4935]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

每次打开PCL都会弹出
自动安装
————————
PCL即将在当前文件夹下自动安装整合包
                                         [继续]  [取消]

### 重现步骤

1、打开Plain Craft Launcher 2.exe所在的目录
2、往目录内放置名为modpack.zip的整合包zip文件
3、打开PCL2

### 日志与附件

[Log4.txt](https://github.com/user-attachments/files/17348028/Log4.txt)
[Log1.txt](https://github.com/user-attachments/files/17348025/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17348026/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17348027/Log3.txt)
[Log5.txt](https://github.com/user-attachments/files/17348029/Log5.txt)

**Comment by tangge233** [comment]
emmmm

我和你在群里聊的应该是这个意思：

即使目录下的 modpack.zip 已经被安装过了，但是 PCL 仍旧会尝试请求安装

_HMCL 似乎不会出现此类情况_

**Comment by LTCatt** [comment]
安装完成后 modpack.zip 不是会删除么？

**Comment by tangge233** [comment]
> 安装完成后 modpack.zip 不是会删除么？

PCL 是这样的，但是用 HMCL 安装后并不会删除

**Comment by LTCatt** [comment]
没搞懂意思。所以现在是哪里和预期的行为不一样，预期的行为是什么？

**Comment by tangge233** [comment]
目录下存在 modpack.zip 但是使用了 HMCL 进行安装（HMCL 安装完成后并不会自动删除 modpack.zip），之后用户使用了 PCL 玩整合包，由于已经安装过了，于是用户在对话框选择取消…就是这种情况

**Comment by LTCatt** [comment]
我觉得这应该是 HMCL 那边处理……为什么要我这儿来判断 HMCL 有没有装过……

**Comment by SakuraiMikoto** [comment]
选择继续后自动下载，下载完毕后下次打开还是会出现这种情况。。我这个电脑还没装HMCL

**Comment by SakuraiMikoto** [comment]
是权限问题，但是。建议给自动安装根目录的modpack.zip一个开关，我只是想存在目录里我不是想安装。
