### ISSUE TITLE
在关闭游戏后立即禁用mod出现索引错误导致程序崩溃

### ISSUE THREAD

**Issue by ZOUYIQAQ** [Hex-Dragon/PCL2#4937]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在关闭游戏后立即禁用mod出现索引错误导致程序崩溃

### 重现步骤

关闭游戏后立即禁用mod
[Log2.txt](https://github.com/user-attachments/files/17350297/Log2.txt)

### 日志与附件

[Log3.txt](https://github.com/user-attachments/files/17350293/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17350294/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17350295/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/17350296/Log1.txt)

**Comment by Ad-closeNN** [comment]
#4862 已解决，下次更新会修复
