### ISSUE TITLE
允许在下载新版本时自定义描述

### ISSUE THREAD

**Issue by ThendJyc** [Hex-Dragon/PCL2#4942]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

允许在下载新的版本时就能自定义版本描述
例如：
![屏幕截图 2024-10-13 100600](https://github.com/user-attachments/assets/cdef4ec4-843f-4ed2-84aa-c008f824ae62)

### 原因

我经常需要在版本下载完成后再更改版本描述
非常麻烦

**Comment by LTCatt** [comment]
需求不大，暂时不考虑……
