### ISSUE TITLE
快照版2.8.8下重新出现<程序出现未知错误：索引必须位于该列表的界限内>

### ISSUE THREAD

**Issue by Txt-Text** [Hex-Dragon/PCL2#4943]
### 检查项

- [ ] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

删了个mod就这样了，，，有人提交过但bug又复现了，所以新开一个
pcl版本是最新的2.8.8快照，你说修了吗？如修
![PixPin_2024-10-13_10-01-36](https://github.com/user-attachments/assets/3e5fbd19-3213-4786-8721-4c14cffeb440)
![PixPin_2024-10-13_10-06-37](https://github.com/user-attachments/assets/649e1a67-b63f-4d32-87f9-8a5a048ea917)

### 重现步骤

复现方式这个issue底下有人说了
https://github.com/Hex-Dragon/PCL2/issues/4862

### 日志与附件

[Log4.txt](https://github.com/user-attachments/files/17352746/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17352747/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/17352748/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17352749/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17352750/Log3.txt)

**Comment by Ad-closeNN** [comment]
PCL 的 更新**不是热更新**，这里指的**完成**是指代码修复完毕而不是版本推送完毕
请等待下次版本发布（如**2.8.9）

**Comment by Txt-Text** [comment]
> PCL 的 更新**不是热更新**，这里指的**完成**是指代码修复完毕而不是版本推送完毕 请等待下次版本发布（如**2.8.9**）

如果上一个issue是一样的版本那就是我的问题，看提交时间是几周前就认为这期间更新过了
