### ISSUE TITLE
在mod管理的搜索框搜索时PCL卡死

### ISSUE THREAD

**Issue by Txt-Text** [Hex-Dragon/PCL2#4944]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在mod管理中搜索mod时pcl卡死（未响应），目前已多次重现，并非偶然
这次卡死的步骤：搜索了一个mod并禁用->点搜索框->卡死
其他几次也是差不多的步骤
![PixPin_2024-10-13_09-57-02](https://github.com/user-attachments/assets/4eef0592-61fd-4180-bf85-12d911b0390a)

### 重现步骤

经过多次被动重现，发现这几次卡死基本都是搜索过后（不知道与期间对mod有一些操作有无关系）再次点击搜索框或输入东西后可能触发

### 日志与附件

[Log5.txt](https://github.com/user-attachments/files/17352790/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/17352791/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17352792/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17352793/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17352794/Log4.txt)

**Comment by Txt-Text** [comment]
这次卡死的步骤：搜索了一个mod并禁用->点搜索框->卡死

**Comment by Ad-closeNN** [comment]
#4862

**Comment by Txt-Text** [comment]
> * [启用/禁用 Mod 时出现未知错误：索引必须位于该列表的界限内 #4862](https://github.com/Hex-Dragon/PCL2/issues/4862)
> * 和你的 [快照版2.8.8下重新出现<程序出现未知错误：索引必须位于该列表的界限内> #4943](https://github.com/Hex-Dragon/PCL2/issues/4943)

这个issue是不是close错了？pcl卡死这个我没有找到重复的，应该close的是https://github.com/Hex-Dragon/PCL2/issues/4943

**Comment by Ad-closeNN** [comment]
> > * [启用/禁用 Mod 时出现未知错误：索引必须位于该列表的界限内 #4862](https://github.com/Hex-Dragon/PCL2/issues/4862)
> > * 和你的 [快照版2.8.8下重新出现<程序出现未知错误：索引必须位于该列表的界限内> #4943](https://github.com/Hex-Dragon/PCL2/issues/4943)
> 
> 这个issue是不是close错了？pcl卡死这个我没有找到重复的，应该close的是#4943

```log
[10:01:22.849] 程序出现未知错误：索引必须位于该列表的界限内。
参数名: index
   在 System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   在 System.Collections.Generic.List`1.Insert(Int32 index, T item)
   在 PCL.PageVersionMod.EDMods(IEnumerable`1 ModList, Boolean IsEnable)
   在 PCL.MyIconButton.Button_MouseUp(Object sender, MouseButtonEventArgs e)
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   在 System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   在 System.Windows.Input.InputManager.ProcessStagingArea()
   在 System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   在 System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   在 System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   在 System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
错误类型：System.ArgumentOutOfRangeException
```

日志是这样显示的（不过有点不同

**Comment by Deep-Dark-Forest** [comment]
额，日志看起来差不多啊……先 reopen 一下吧……

**Comment by Txt-Text** [comment]
> 额，日志看起来差不多啊……先 reopen 一下吧……

这是因为同时触发了两个bug，pcl卡死重启后又干出了引索那个bug

**Comment by LTCatt** [comment]
实质重复，是同一个 bug 导致

**Comment by LTCatt** [comment]
卡顿问题得有稳定复现方法才能修……很尴尬（
