### ISSUE TITLE
pcl突然无缓存权限且minecraft无法创建世界

### ISSUE THREAD

**Issue by starjumpsama** [Hex-Dragon/PCL2#4945]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

以前不会出现，更换为测试版pcl后进入pcl时直接提示无权限，请以管理员运行，在管理员运行过一次后可以打开，但是依旧提示无缓存，进入游戏后无法创建世界（创建即闪退）

### 重现步骤

更新为测试版pcl
点击pcl，以管理员运行一次
再次点击

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/17352921/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17352923/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17352924/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17352925/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17352926/Log5.txt)

**Comment by LTCatt** [comment]
系统问题，PCL 无法解决
