### ISSUE TITLE
mod列表刷新后保留刷新前位置

### ISSUE THREAD

**Issue by Txt-Text** [Hex-Dragon/PCL2#4946]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

pcl被动刷新频率高的离谱，mod管理里面稍微一动就会触发刷新，一刷新就会跑到最上面，在理mod的时候尤其痛苦

### 原因

这项优化让玩家可以更方便地整理mod
如果没有这项优化，每次刷新后都必须重新下翻，让操作变得很麻烦

**Comment by JingHai-Lingyun** [comment]
没有找到相应反馈……
但是这个功能貌似实现起来会很复杂

---

个人理解这会需要持续监听滚动事件，可能会有额外性能开销？

**Comment by LTCatt** [comment]
实际是 #4457 导致。
修完 #4457 之后应该不需要这个功能（

**Comment by Txt-Text** [comment]
> 没有找到相应反馈…… 但是这个功能貌似实现起来会很复杂
> 
> 个人理解这会需要持续监听滚动事件，可能会有额外性能开销？

刷新前记录一次当前位置就行，不需要太复杂
