### ISSUE TITLE
下载器优化

### ISSUE THREAD

**Issue by kazukokawagawa** [Hex-Dragon/PCL2#4951]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

添加下载器自定义UA，就可以把上面那个百度网盘的警告删掉了，只是因为我看他不舒服！
百度网盘需要的UA为 LogStatistic

### 原因

这项优化让我可以更方便地下载黄油。
如果没有这项优化，我每次都必须下载百度网盘，让操作变得很麻烦。

**Comment by tangge233** [comment]
？PCL 不是下载器啊

**Comment by allMagicNB** [comment]
@3gf8jv4dv 龙猫说过**不会再继续优化自定义下载**。

**Comment by LTCatt** [comment]
![image](https://github.com/user-attachments/assets/1f06192d-3b12-4a14-9221-44c8e1256752)
加了个简单的处理 =。=
