### ISSUE TITLE
离线登录时强制要求正版登录(?

### ISSUE THREAD

**Issue by QijiaQ** [Hex-Dragon/PCL2#4952]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

**(可能仅限这台设备发生)**
选择 离线模式 启动游戏版本时(Loading), PCL 弹出了 要求正版登录的窗口(对不起这是一只离线狗)
尝试切换到正版 添加了不含有MC的账户, PCL 提示没有游戏(这是正常情况)
再切换到离线模式再启动, 仍然有 需要正版登录 的窗口 (证明了这不是显示/切换错误)
选择取消则取消启动
选择 试玩后, MC在进入任何模式时均使用demo-mode, 世界保存在存档文件Demo-World 里
多次重启PCL 后仍会发生

log中. 有两次[Net] 访问外部链接出现问题
第一个向 https://launchermeta.mojang.com/mc/game/version_manifest.json 发出的请求超时(10s) 并要求json 格式, log记录时间仅为 启动器启动后 不到1s (这个链接目前可以访问, 有内容)
第二个向 https://pcl2-server-1253424809.file.myqcloud.com/notice.cfg?sign=**** 发出的请求超时(10s), 同在1s内 (这个链接目前无法验证是否有内容, 浏览器返回403.)

(若这是Mojang 那边 对游戏文件使用了强制线上验证..请关掉这个Issue.谢谢.)

### 重现步骤

1. 启动PCL II (这里是Windows 版本, PCL2.exe)
(1.1. 选择任意一个版本)
2. 点击 启动游戏
(可能仅限这个客户端内.)

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/17357813/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17357814/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17357815/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17357816/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17357817/Log5.txt)

**Comment by tangge233** [comment]
请将您的系统区域换到中国，否则 PCL 不认为您的区域可以免费游玩 MC
