### ISSUE TITLE
在下载大型整合包时，返回启动界面会出现明显卡顿且选择登录方式界面需等待2秒及以上才能显示

### ISSUE THREAD

**Issue by Cx330zyq** [Hex-Dragon/PCL2#4954]
### 检查项

- [ ] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [ ] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

下载的整合包：Legendary Edition

### 重现步骤

1、现在大型整合包
2、在安装完成的一瞬间（或前几秒）点击开始

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/17364458/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17364459/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17364460/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17364461/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17364462/Log5.txt)

**Comment by Cx330zyq** [comment]
在其他情况也有，莫名其妙的

**Comment by LTCatt** [comment]
……能具体说明一下吗，或者录个视频并且上传当时的日志

**Comment by Cx330zyq** [comment]
额，正式版的，硬盘被格式化了，我也不知道怎么重现

**Comment by LTCatt** [comment]
如果能重现的话，可以录屏并且上传当时的日志，这样我才能定位到底是什么导致的问题……
现在先关了，之后可以继续在这下面回复（

**Comment by Cx330zyq** [comment]
（ok）（

**Comment by Cx330zyq** [comment]
刚发现个，在特定情况下，加载PCL更新日志会不显示

**Comment by Cx330zyq** [comment]
[Log1.txt](https://github.com/user-attachments/files/17378093/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17378094/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17378098/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17378101/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17378102/Log5.txt)
额如果说是下载（网络）的问题的话，他也没有显示正在下载

**Comment by Cx330zyq** [comment]
![image](https://github.com/user-attachments/assets/cd64477b-cae7-4292-9494-acacad98e889)
还有个文字不显示

**Comment by LTCatt** [comment]
如果能重现的话，可以 [录屏] 并且上传 [当时的日志]
没有录屏的话我也不知道是什么时间点它卡了啊……录屏的时候最好把精确到秒的时间也录进去 orz

后面那个在 https://github.com/Hex-Dragon/PCL2/discussions/4845 反馈 @Joker2184

**Comment by LTCatt** [comment]
……你可以传网盘然后贴到这里

**Comment by Cx330zyq** [comment]
我用夸克网盘分享了「屏幕录制 2024-10-15 212314.mp4」，点击链接即可保存。打开「夸克APP」，无需下载在线播放视频，畅享原画5倍速，支持电视投屏。
链接：https://pan.quark.cn/s/db3fa6fec8de

**Comment by Cx330zyq** [comment]
[Log1.txt](https://github.com/us
[Log2.txt](https://github.com/user-attachments/files/17394520/Log2.txt)
er-attachments/files/17394517/Log1.txt)
[Log3.txt](https://github
[Log5.txt](https://github.com/user-attachments/files/17394526/Log5.txt)
[Log4.txt](https://github.com/user-attachments/files/17394527/Log4.txt)
.com/user-attachments/files/17394522/Log3.txt)
日志是今天传的，视频是昨天录的，不过今天也发生了类似的BUG（

**Comment by LTCatt** [comment]
没看出来哪里卡了。是说主页半天加载不出来？

**Comment by Cx330zyq** [comment]
也可以这么说......不过如果它在下载为啥不显示，你点一下下载它才显示

**Comment by Joker2184** [comment]
> ![image](https://private-user-images.githubusercontent.com/184401359/376612781-cd64477b-cae7-4292-9494-acacad98e889.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMzU2MTgsIm5iZiI6MTcyOTIzNTMxOCwicGF0aCI6Ii8xODQ0MDEzNTkvMzc2NjEyNzgxLWNkNjQ0NzdiLWNhZTctNDI5Mi05NDk0LWFjYWNhZDk4ZTg4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOFQwNzA4MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04N2E5MzU2OTI3YjEyYjIwN2MzYzA4YjU2NmUyNjUyNTJjOTk3ZjQ2YTQ5MzNhYTU5Nzc3ZDE2MDVlMjI5ZWIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rxrAMKTibbYhHmjvnlxt6RbrYrH_bpRwgckdL-3JpCQ) 还有个文字不显示

think 太长了.jpg 让我看看怎么搞

**Comment by Cx330zyq** [comment]
额...确实每个都是

**Comment by Joker2184** [comment]
> 额...确实每个都是

信标有CDN 不会卡 

其余有三个主页为CF可能会卡

其中我和凌云即将换为国内对象存储来使预设访问加速.jpg
