### ISSUE TITLE
Windows10系统有几率重启会重置PCL

### ISSUE THREAD

**Issue by lihansen136** [Hex-Dragon/PCL2#4955]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

Windows10 22H2系统重启时有概率初始化PCL
设备名称	***
处理器	13th Gen Intel(R) Core(TM) i5-13500H   2.60 GHz
机带 RAM  16.0 GB (15.7 GB 可用)
设备 ID	3FEFDCB8-3B48-478F-B3E9-48737B5C005E
产品 ID	00391-70000-00000-AA270
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	没有可用于此显示器的笔或触控输入

原版系统
版本	Windows 10 专业工作站版
版本号	22H2
安装日期	‎2024/‎10/‎11
操作系统内部版本	19045.5011
体验	Windows Feature Experience Pack 1000.19060.1000.0

### 重现步骤

1.Windows10  22H2重启。
2.打开PCL，发现初始化了（小概率，目前遇到过两次，正常关机重启）

### 日志与附件

[Log5.txt](https://github.com/user-attachments/files/17378566/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/17378569/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17378570/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17378571/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17378573/Log4.txt)

**Comment by LTCatt** [comment]
这应该不是我这里的问题……是系统导致的 orz
