### ISSUE TITLE
启用mod时崩溃

### ISSUE THREAD

**Issue by Blalala6868** [Hex-Dragon/PCL2#4958]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/user-attachments/assets/70fa9cbb-6a96-4b0c-9ed8-f397429a4f44)

### 重现步骤

在模组管理界面的禁用选项卡下启用Exordium后崩溃

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/17383399/Log1.txt)

**Comment by lactobionicAcid** [comment]
与 #4862 重复。这个 Bug 会在 PCL 启动器的下一次更新中修复。
