### ISSUE TITLE
从隐藏主题切换到不包含特殊图案的主题时，主题图案非预期保留

### ISSUE THREAD

**Issue by lactobionicAcid** [Hex-Dragon/PCL2#4960]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

从任一隐藏主题切换到任一不包含特殊图案的主题时，左下角弹出提示 `加载图片失败（）：未将对象引用设置到对象的实例。`，同时前一个隐藏主题的图案在标题栏上非预期保留。

使用 跳票红 主题复现时可见以下效果：
![image](https://github.com/user-attachments/assets/35366f82-50de-4ef7-a89a-0a01fa43ab89)

_~这个 Bug 可能让 PCL 启动器变得更漂亮，好像没必要修？（~_

### 重现步骤

切换到任一隐藏主题，然后切换到 自定义 主题或默认的 5 个主题。

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/17384474/Log1.txt)

**Comment by kong-que-dnf123** [comment]
说实话还挺好看 ~（这下就可以自定义带水印的渐变色主题了~
![image](https://github.com/user-attachments/assets/82e5f61a-3b0f-471f-8473-f4bd192b4d19)

**Comment by Joker2184** [comment]
好看的.jpg 别修了

**Comment by Joker2184** [comment]
新bug还挺不错建议改一改添加到个性化里面

**Comment by MCSteve123** [comment]
建议加个功能可以使用隐藏主题的图案，我喜欢欧皇彩背景+极客蓝图案（

**Comment by ArgonTeam** [comment]
![屏幕截图 2024-11-01 081621](https://github.com/user-attachments/assets/1bc09c13-b585-4b0f-8375-cb831b663302)
shi'de是的，我也遇到了这些问题。希望龙猫能修复。
