### ISSUE TITLE
将Mod(模组)更新功能添加到百宝箱

### ISSUE THREAD

**Issue by MNWZ211** [Hex-Dragon/PCL2#4961]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

模组更新功能不仅可以用在单人存档，亦可在服务器中（模组文件夹）使用。
建议将此功能运用到检测服务器的模组文件是否存在更新，以方便替换和管理。

若采纳，位置合适即可。

### 原因

方便自建服务器习惯性的更新模组或替换等管理操作。

**Comment by LTCatt** [comment]
技术上做起来相当相当麻烦，并且估计也没多少人用……
