### ISSUE TITLE
加回[安装整合包时保留原始压缩包]这个选项

### ISSUE THREAD

**Issue by LrbsX** [Hex-Dragon/PCL2#4963]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

最新预览版移除了这个功能。但是对整合包分发者非常不友好。以后打包完了想导入启动器测试一下，结果本来打包好的包一下子就删了，还得重新打。请重新加回此功能。

### 原因

移除此功能对整合包分发者非常不友好。以后打包完了想导入启动器测试一下，结果本来打包好的包一下子就删了，还得重新打。因此请求重新加回此功能。

**Comment by LTCatt** [comment]
……我觉得这应该是用户自行处理的部分…………
