### ISSUE TITLE
正式版无法更新

### ISSUE THREAD

**Issue by kong-que-dnf123** [Hex-Dragon/PCL2#4965]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如图所示
![image](https://github.com/user-attachments/assets/1852d5a1-5ebc-4711-8303-032cba8fb741)
![image](https://github.com/user-attachments/assets/e3ab8310-b86d-475f-b3fc-5f9d2dc98b13)

### 重现步骤

1、打开PCL Release2.8.7(338.50)
2、更新

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/17395334/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17395335/Log2.txt)

**Comment by LTCatt** [comment]
由于第三方接口出现脑残问题，部分情况下正式版无法进行更新。

目前，如果你满足以下条件中任意一个，则 **可以** 正常更新：
- 在设置中选择了 `在有新版本时自动下载`
- 可以访问 GitHub
- 在启动器自动弹窗时选择更新

如果并未选择 `在有新版本时自动下载`，且无法访问 GitHub，则只能通过启动器的自动弹窗才能更新，手动检查更新会在下载时失败，且无法修复。
