### ISSUE TITLE
自定义自定义主页的加载目录

### ISSUE THREAD

**Issue by Ext1nguisher** [Hex-Dragon/PCL2#4966]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

目前自定义主页只能从PCL根目录下加载，且文件名只能为Custom.xaml
这对于我这种自定义主页作者极不友好，因为我需要使用git仓库，而我要debug只能把文件转移到PCL目录，很麻烦。
我总不能把PCL根目录作为git仓库吧......

### 原因

如上，我需要这个功能来做自定义主页的调试
如果没有这个功能，每次调试就需要转移文件，步骤繁琐

**Comment by LTCatt** [comment]
我觉得这是属于用户自行解决的问题……
你可以考虑用文件链接 orz

**Comment by Ext1nguisher** [comment]
> 文件链接
什么什么，能教教我吗   》？《
@LTCatt

**Comment by LTCatt** [comment]
https://learn.microsoft.com/zh-cn/windows-server/administration/windows-commands/mklink

**Comment by wuliaodexiaoluo** [comment]
>什么什么，能教教我吗 》？《

mklink /D [软链路径] [原始文件路径]

**Comment by Ext1nguisher** [comment]
啊？
还能这么玩！

**Comment by Ext1nguisher** [comment]
![image](https://github.com/user-attachments/assets/b266942b-ce12-4178-b43d-2d165aa7eb53)
呃呃呃呃 @LTCatt

**Comment by Ext1nguisher** [comment]
> @Ext1nguisher
> 
> `mklink` needs to be executed from the Windows command prompt. `mklink` 需要用 Windows 命令提示符执行。

我用的就是 cmd 啊，你是指 Windows powershell ?
I'm using windows command line already! Perhaps you mean Windows powershell?

**Comment by JingHai-Lingyun** [comment]
你用的分明是 Powershell...

**Comment by Ext1nguisher** [comment]
哦哦哦，它，那个`在终端中打开`，开的是他妈powershell
才发现，对不起

**Comment by hejiehao** [comment]
> 哦哦哦，它，那个`在终端中打开`，开的是他妈powershell 才发现，对不起

~~可以设置默认 Profile~~

**Comment by Ext1nguisher** [comment]
> > 哦哦哦，它，那个`在终端中打开`，开的是他妈powershell 才发现，对不起
> 
> ~可以设置默认 Profile~

lazy

**Comment by Ext1nguisher** [comment]
好了，现在软链能有了
但是，PCL好像读取不了软链。。。
硬链显示不能跨盘。。。。啊啊啊啊啊啊啊啊啊啊

**Comment by hejiehao** [comment]
<details><summary>图片</summary>
<p>

![image](https://github.com/user-attachments/assets/b7b1bb5e-b5a3-4ec6-b4ac-cb4f6d505eb9)

</p>
</details>

**Comment by hejiehao** [comment]
> > 什么什么，能教教我吗 》？《
> 
> mklink /D [软链路径] [原始文件路径]

`/D` 是 **目录**符号链接，不加 `/D` 才能链接**文件**
