### ISSUE TITLE
导出mod名称列表

### ISSUE THREAD

**Issue by Blalala6868** [Hex-Dragon/PCL2#4967]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

以文本形式导出模组名称列表

### 原因

几乎任何mod的issue提交都需要我们提供mod列表，一张张截图太麻烦了

**Comment by Blalala6868** [comment]
> Like this issue: 和这个有点像：
> 
> * [添加 导出Mod列表 功能 #2586](https://github.com/Hex-Dragon/PCL2/issues/2586)
> 
> Is it what you expected? 和你期望的一样吗？

我的期望是导出这样的纯文本列表，而不是modpack整合包
![image](https://github.com/user-attachments/assets/ba09a0fd-bc4f-4ccb-b6fd-bfe79799dabc)

**Comment by LTCatt** [comment]
这个暂时不考虑……
