### ISSUE TITLE
更新启动器意外导致窗口大小重置

### ISSUE THREAD

**Issue by JingHai-Lingyun** [Hex-Dragon/PCL2#4972]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 重现步骤

自 2.8.8 更新至 2.8.9

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/17432078/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17432075/Log2.txt)

**Comment by JingHai-Lingyun** [comment]
有朋友来提醒我说是 #4678 导致的，留着看看龙猫修不修

**Comment by LTCatt** [comment]
是 #4678，不会修（
