### ISSUE TITLE
把pcl2下载的java8换openjdk的最新版本

### ISSUE THREAD

**Issue by edgeless-player** [Hex-Dragon/PCL2#4974]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

如标题

### 原因

减少崩溃，有些模组已不支持051

**Comment by allMagicNB** [comment]
推荐给 Mojang 反馈。为什么？因为他们用的就是 Java 8u51。

**Comment by JingHai-Lingyun** [comment]
> 自动下载的是 Mojang 官方启动器使用的 Java，这样能最大程度的降低 Java 版本可能带来的不兼容问题，暂时不会修改，抱歉
- https://github.com/Hex-Dragon/PCL2/issues/4455#issuecomment-2280054400
