### ISSUE TITLE
同时进行内存优化和清理垃圾或者更新游戏导致皮肤损坏和可视化损坏等问题

### ISSUE THREAD

**Issue by huojianGET** [Hex-Dragon/PCL2#4975]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

报错
![QQ20241019-083224](https://github.com/user-attachments/assets/f8f876a7-bee3-4ace-b3d9-075a1e4a2614)
无法加载皮肤
下载等界面无法显示

### 重现步骤

1、同时进行内存优化和清理内存
2、报错
尝试删除pcl文件依旧报错

于是我从浏览器重新下载pcl，把它放在了一个新的文件夹
由于不是最新版，我选择了更新
更新完成后还是报错（现象一样）

### 日志与附件

[Log2.txt](https://github.com/user-attachments/files/17441835/Log2.txt)

[Log3.txt](https://github.com/user-attachments/files/17441836/Log3.txt)

[Log4.txt](https://github.com/user-attachments/files/17441833/Log4.txt)

[Log1.txt](https://github.com/user-attachments/files/17441834/Log1.txt)

**Comment by huojianGET** [comment]
补充：根据测试，出错后下载，更多，皮肤会出错，但游戏依旧可以启动

**Comment by huojianGET** [comment]
补充：出错后游戏依旧可以启动，但皮肤以及下载ui还是错误

**Comment by huojianGET** [comment]
抱歉，根据网上相关内容和不断尝试，我已解决提交的问题

**Comment by JingHai-Lingyun** [comment]
- 同 #4869
