### ISSUE TITLE
窗口过小+侧边栏超长时未有滚动条

### ISSUE THREAD

**Issue by JingHai-Lingyun** [Hex-Dragon/PCL2#4979]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

*转自 PCL 非官方社区群内*
![image](https://github.com/user-attachments/assets/12569ecb-c655-4349-b476-eec32a154308)

### 原因

接下来再加入收藏页面的话就彻底不可见了

**Comment by allMagicNB** [comment]
- #4224

**Comment by allMagicNB** [comment]
乐了
