### ISSUE TITLE
优化崩溃检测

### ISSUE THREAD

**Issue by MCSteve123** [Hex-Dragon/PCL2#4980]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

一个简单的模组无前置错误，但PCL没有发现……
~我不知道投bug还是投优化，干脆投优化算了~
附件：
[错误报告-2024-10-19_19.40.31.zip](https://github.com/user-attachments/files/17444872/-2024-10-19_19.40.31.zip)
![image](https://github.com/user-attachments/assets/94ed4ea5-7176-4842-89a7-c1c16c688b92)

### 原因

崩溃检测的问题

**Comment by wuliaodexiaoluo** [comment]
```
[19:40:22] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
ȷ����һ�ֿ��ܵĽ�����������������ܻ���������⣺
	 - ��װ yet_another_config_lib_v3������汾��?
������Ϣ��
	 - ģ�� 'AcryliCraft' (acrylic) 1.6.4 ��Ҫ yet_another_config_lib_v3 �� ����汾����û�а�װ����?
```

VSCode 显示日志乱码严重，初步判断为乱码导致检测有误

**Comment by SuoHouDaiShi** [comment]
> ```
> [19:40:22] [main/ERROR]: Incompatible mods found!
> net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
> ȷ����һ�ֿ��ܵĽ�����������������ܻ���������⣺
> 	 - ��װ yet_another_config_lib_v3������汾��?
> ������Ϣ��
> 	 - ģ�� 'AcryliCraft' (acrylic) 1.6.4 ��Ҫ yet_another_config_lib_v3 �� ����汾����û�а�װ����?
> ```
> 
> VSCode 显示日志乱码严重，初步判断为乱码导致检测有误

使用记事本打开日志时未出现乱码，记事本显示`latest.log`正在使用 ANSI 编码。
![图片](https://github.com/user-attachments/assets/adfd1730-45e2-426e-a6b8-07a590610fe7)

所谓的 ANSI 编码，其实就是：
```
ANSI 编码在不同的 Windows 系统中指代的是一种基于 ASCII 的扩展编码，用于表示各种字符，包括中文字符。不同的 Windows 系统可能会使用不同的 ANSI 编码页来表示特定字符集。

关于你提到的问题，VSCode 和记事本在处理编码时有所不同。VSCode 默认使用 UTF-8 编码来处理文本文件，而记事本默认使用系统的 ANSI 编码。如果你的日志文件是使用 ANSI 编码保存的，记事本可以正确读取和显示，而 VSCode 由于期望文件是 UTF-8 编码，可能会将中文字符错误地显示为 Unicode 替换码。
```
