### ISSUE TITLE
[转发] PCL 多线程疑似会高频主动断开连接

### ISSUE THREAD

**Issue by tangge233** [Hex-Dragon/PCL2#4981]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

@[PCL] 龙腾猫跃 PCL2 会主动断开下载 Mod 的连接？
具体是不到100ms就断开...显然不是超时之类的，我这CDN看到的是499
![a4352aa238529f6d828eee5be971bc49_720](https://github.com/user-attachments/assets/d902fec4-45cb-4652-93cf-88e77b1eaa60)
![ddcf248ead3c16ed17527e1d50ee7711](https://github.com/user-attachments/assets/93e908e0-87d9-4336-9497-1f4e777c9cd5)
![ee3d5828a830eb74a91a98f8ef3219ab](https://github.com/user-attachments/assets/b6a0d53f-3ce5-40e1-a3bc-b8c162b4a1dd)
基本上每秒都能产生几个这种情况的

<details>

![image](https://github.com/user-attachments/assets/52a51897-ba25-493c-841a-b0c524ada796)

</details>

GET /data/sk9knFPE/versions/d6aWp117/rhino-fabric-2001.2.2-build.18.jar HTTP/1.1

PCL2/2.8.8.50 Mozilla/5.0 AppleWebKit/537.36 Chrome/63.0.3239.132 Safari/537.36

该接口在正常工作

<details>

![image](https://github.com/user-attachments/assets/88d465f9-ff41-4c6b-abcf-a68a82f50120)

</details>

### 重现步骤

下载？

### 日志与附件

ask z0z0r4

**Comment by z0z0r4** [comment]
没有日志可以提供…但我CDN后台看的每秒都有这种 499，应该不难复现（x

**Comment by SALTWOOD** [comment]
499……是客户端断开连接还是服务端断的

**Comment by tianxiu2b2t** [comment]
499一般是CDN引起的

**Comment by z0z0r4** [comment]
> 499一般是CDN引起的

499 是 `服务器返回http头之前，客户端就提前关闭了http连接。`

```
/*
* HTTP does notdefine the code for the case when a client closed
* the connectionwhile we are processing its request so we introduce
* own code to logsuch situation when a client has closed the connection
* before we even tryto send the HTTP header to it
*/
#define NGX_HTTP_CLIENT_CLOSED_REQUEST 499

ngx_string(ngx_http_error_495_page), /* 495, https certificate error */
ngx_string(ngx_http_error_496_page), /* 496, https no certificate */
ngx_string(ngx_http_error_497_page), /* 497, http to https */
ngx_string(ngx_http_error_404_page), /* 498, canceled */
ngx_null_string,                     /* 499, client has closed connection */
```

**Comment by SALTWOOD** [comment]
也就是说是客户端发了请求数据没等回复就关了？

**Comment by JingHai-Lingyun** [comment]
挂个待确认等龙猫回复看看

**Comment by LTCatt** [comment]
还是需要一个能体现行为的日志……这个我都不知道从哪查起……

**Comment by LTCatt** [comment]
怪了，MCIM 不在多线程黑名单里，我记得我加了的啊……
现在加进多线程黑名单了，会强制进行单线程下载，看看下个版本会不会好
