### ISSUE TITLE
没有可用的服务端就不要创建服务端文件夹

### ISSUE THREAD

**Issue by z0z0r4** [Hex-Dragon/PCL2#4982]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

没有可用的服务端就不要创建服务端文件夹，如 rd-132211 根本没服务端但会产生一个 rd-132211 文件夹，里面是版本信息...

### 原因

看起来需要给不存在服务端的情况下加点逻辑？这些不该判成 ERROR 吧，正常情况...

![{068EB8DD-6B04-4EA2-9978-31966C310B45}](https://github.com/user-attachments/assets/5dc418d2-661b-46a5-ad84-3566727c8a83)

**Comment by LTCatt** [comment]
![image](https://github.com/user-attachments/assets/a671a688-cda5-4720-bd60-6926c73736c6)
