### ISSUE TITLE
索引错误

### ISSUE THREAD

**Issue by HanHanDeYaYa** [Hex-Dragon/PCL2#4983]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

启用或禁用mod报错索引错误

### 重现步骤

启用或禁用mod

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/17448032/Log1.txt)

**Comment by JingHai-Lingyun** [comment]
此 Bug 于 2.8.9（快照版，SnapShot）修复，还未推送至正式版
参考：
- #4862
- #4957
- #4962
- 等……
