### ISSUE TITLE
添加更新mod加载器的功能

### ISSUE THREAD

**Issue by QianLiZhiWaiovo** [Hex-Dragon/PCL2#4984]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

这个功能可以无需重新下载游戏版本就可以更新mod加载器，例如将fabric从0.1版本更新到0.2版本而无需从下载中再重新下载一个游戏版本

### 原因

主要是人比较懒[doge]，有时候通过更新模组功能更新模组后模组所支持的加载器也需要更新，但是我又不想从下载里面重新下载一个版本，不仅下载版本要花费比较长的时间（尤其是forge），而且如果模组太多重新搬运也麻烦

**Comment by Ad-closeNN** [comment]
- https://github.com/Hex-Dragon/PCL2/issues/220 
- #227
