### ISSUE TITLE
快速左右键点击背景音乐按钮背景音乐会卡住

### ISSUE THREAD

**Issue by team-furou-lblt** [Hex-Dragon/PCL2#4985]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

确保有PCL背景音乐
### 快速左右键点击右下角圆的按钮
背景音乐会卡住无法播放

### 重现步骤

1、快速左右键点击右下角音乐按钮

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/17448848/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17448849/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17448850/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17448851/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17448852/Log5.txt)

**Comment by SALTWOOD** [comment]
> 通过连点/快速点击刻意触发的 bug 不会受理，抱歉 :/

引自[龙猫的回答](https://github.com/Hex-Dragon/PCL2/issues/2576#issuecomment-1690408194)

**Comment by JingHai-Lingyun** [comment]
> 感觉还是 API 的状态更新存在延迟导致的，如果没有实际影响就算了

与以下反馈相同
- #2492
