### ISSUE TITLE
PCL日志 显示需要的为en_US 当前语言为en_us

### ISSUE THREAD

**Issue by Joker2184** [Hex-Dragon/PCL2#4988]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

就下了个1.21...
然后瞄了眼日志就...

### 重现步骤

嘶
先请其他人测一下吧

### 日志与附件

![QQ截图20241020165413](https://github.com/user-attachments/assets/9e6f2440-304b-4eb6-bd71-a9dd7113914a)
![QQ截图20241020165623](https://github.com/user-attachments/assets/b45cbdfd-a7b0-426b-8568-e9c821dc8e31)

**Comment by tangge233** [comment]
![image](https://github.com/user-attachments/assets/b1240550-a4f9-4911-8c2f-7a6a42e9a72f)
如果您的语言选项不为 `none` 并且存在 `saves` 文件夹，那就会直接使用现有语言

**Comment by Joker2184** [comment]
> ![image](https://private-user-images.githubusercontent.com/50769997/378171589-b1240550-a4f9-4911-8c2f-7a6a42e9a72f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MTU1MjEsIm5iZiI6MTcyOTQxNTIyMSwicGF0aCI6Ii81MDc2OTk5Ny8zNzgxNzE1ODktYjEyNDA1NTAtYTRmOS00OTExLThjMmYtN2E2YTQyZTlhNzJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDA5MDcwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3MjY2Y2QxNzUyNzNiNzhiOGY5NTFiOGYzMWYyYTk1NzYwMjE4ZGUyMDllZmE3YmU2YjJkOGQ2OTc1YWMzYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LDyUsfD2jxHna-s8UrvM0W4z_JlMFu9yVJ47wPDb_1Q) 如果您的语言选项不为 `none` 并且存在 `saves` 文件夹，那就会直接使用现有语言

嘶我看看

**Comment by Joker2184** [comment]
嘶正常了
