### ISSUE TITLE
PCL首页头像模糊不清

### ISSUE THREAD

**Issue by dojustme** [Hex-Dragon/PCL2#4993]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/user-attachments/assets/a443a036-ce61-4eed-af65-686fd0bde237)
皮肤源文件完好，minecraft内的玩家头颅也正常
尝试过刷新头像，重新登陆，均无效

### 重现步骤

启动PCL

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/17455214/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17455216/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17455217/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17455219/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17455220/Log5.txt)
![skin](https://github.com/user-attachments/assets/a94e7445-6d8d-4318-80b2-a3b1eb071fdb)
![screenshot](https://github.com/user-attachments/assets/f8f43a68-19f7-4b55-ac82-339aafb7f1a6)

**Comment by wuliaodexiaoluo** [comment]
```
[12:52:22.915] 加载图片失败（）：未将对象引用设置到对象的实例。
   在 PCL.MyBitmap.op_Implicit(MyBitmap Image)
   在 PCL.MyImage._Closure$__22-0._Lambda$__0()
   在 PCL.MyImage.TestRepository(String value)
错误类型：System.NullReferenceException
```
Line in 415

**Comment by dongjunming** [comment]
缓存文件路径？

**Comment by wuliaodexiaoluo** [comment]
> 缓存文件路径？

应该是在百宝箱有个清理缓存的选项，你试试看有没有用

**Comment by dongjunming** [comment]
> > 缓存文件路径？
> 
> 应该是在百宝箱有个清理缓存的选项，你试试看有没有用

很遗憾，我点了百宝箱-清理游戏垃圾，还是不行
看龙腾猫跃怎么修吧
[Log1.txt](https://github.com/user-attachments/files/17519913/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17519914/Log2.txt)

**Comment by ZeroWolf233** [comment]
网不好？看你刷新这么多遍，应该不是

**Comment by LTCatt** [comment]
无法复现，我这离线加载是正常的……
![image](https://github.com/user-attachments/assets/2b8879ee-ba9c-4282-b2a6-11c4be64b838)

还有其他人可以复现吗？

**Comment by JingHai-Lingyun** [comment]
提供一下你的屏幕大小和系统设置中的缩放率？

**Comment by dojustme** [comment]
> 测试了使用正版 ID 加载皮肤，自定义皮肤文件（Steve/Alex）都不能复现 Author 提供一下你的屏幕大小和系统设置中的缩放率？

![image](https://github.com/user-attachments/assets/918b3d90-c43f-4782-b411-acf0f65b8751)
屏幕分辨率为`1920×1080`，缩放率为`125%`

**Comment by wuliaodexiaoluo** [comment]
<details>
<summary>image</summary>

![image](https://github.com/user-attachments/assets/e938d6e1-bf97-43d2-afe1-7e08f2375d8c)
![image](https://github.com/user-attachments/assets/fe80de1b-98dd-4206-a557-d2460bdb5541)

</details>

这应该和显示设置没太大关系

**Comment by LTCatt** [comment]
由于两周依然没有第二个人能复现，考虑是个例问题，暂时关闭

**Comment by LiXiaoShanL** [comment]
我也是这个情况
<img width="1428" height="870" alt="Image" src="https://github.com/user-attachments/assets/7b29f74a-a0c2-4d3f-a8c5-81e82157a70a" />

[Log1.txt](https://github.com/user-attachments/files/21770813/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/21770810/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/21770811/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/21770809/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/21770812/Log5.txt)

<img width="64" height="64" alt="Image" src="https://github.com/user-attachments/assets/1640db5d-fa25-4c24-a2ad-9629a22e916b" />

貌似是极少数电脑才会有这种情况
本人电脑：华硕无畏15i

**Comment by MoYuan-CN** [comment]
重开传递给龙猫检查，但很可能非常难复现以至于无法修复

**Comment by LTCatt** [comment]
Bitmap 缩放模式是 WPF 控制的，不清楚如何在我的电脑上触发，也不清楚怎么修复……
