### ISSUE TITLE
为什么登录微软成功后，一直显示这个页面，也没有跳转

### ISSUE THREAD

**Issue by poyobi** [Hex-Dragon/PCL2#4994]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![一直加载](https://github.com/user-attachments/assets/b8bb4c2b-1e86-4e8d-8ec8-07f6b767947a)
![登录成功](https://github.com/user-attachments/assets/897922c8-2683-4149-94b5-9e8f4bbf27cd)

### 重现步骤

我在网页上登录微软号后，plc2启动器就不跳转启动游戏了

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/17460972/Log1.txt)

**Comment by tangge233** [comment]
是否遵循以下操作：
在弹出的浏览器窗口中输入 PCL2 提供的代码并单击“允许访问”
登录自己的微软账号
在授权页面允许 PCL2 访问你的账号数据

**Comment by poyobi** [comment]
输完代码后，就显示这个，然后就登录微软号了，并没有显示允许访问
![屏幕截图 2024-10-21 210407](https://github.com/user-attachments/assets/827a31cd-72db-46be-aced-a53fb6a8dc1a)

**Comment by JingHai-Lingyun** [comment]
登录完你的微软账户才会显示授权，如果卡在上面说明跳转 Github 鉴权时卡住了，尝试使用加速器或魔法等方式改善

**Comment by poyobi** [comment]
我也用了魔法，没有改善，还是一样

**Comment by poyobi** [comment]
并没有卡主，只是截图的时候刚刚好在加载，加载完就登录上微软号了，但pcl2还是登录不上

**Comment by tangge233** [comment]
尝试使用密码登陆…

**Comment by poyobi** [comment]
> 尝试使用密码登陆…

谢谢哥们，已经解决了
