### ISSUE TITLE
版本隔离弹窗取消无效bug

### ISSUE THREAD

**Issue by Vector-Syobon-812** [Hex-Dragon/PCL2#4995]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

同步骤
看起来没人交issue

### 重现步骤

1、点击设置
2、往下滚，然后更改版本隔离
3、弹窗选取消
4、重启pcl2
5、版本隔离已被更改

https://github.com/user-attachments/assets/606247b9-8547-4aff-82ee-366cfa7df244

### 日志与附件

[Log5.txt](https://github.com/user-attachments/files/17463518/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/17463519/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17463520/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17463521/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17463522/Log4.txt)

**Comment by Vector-Syobon-812** [comment]
是奇异搞笑的BUG呢，尽管我没帮上忙，但
我的识别码: 1651-A0B5-E837-7909
谢谢！

**Comment by LTCatt** [comment]
你的解锁码：Ip1YYcpya9046TeLTaO2CBuvrf14ijMH
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
