### ISSUE TITLE
Mod、整合包下载筛选界面添加1.21.3版本选项

### ISSUE THREAD

**Issue by Louis-Harsune** [Hex-Dragon/PCL2#4996]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

1.21.3版本已经于10月23日推出，并取代前一日发布的1.21.2，希望PCL2能予以跟进。
Mojang官网更新日志：https://www.minecraft.net/zh-hans/article/minecraft-java-edition-1-21-3
1.21.2更新日志：https://www.minecraft.net/zh-hans/article/minecraft-java-edition-1-21-2

### 原因

见上

**Comment by Joker2184** [comment]
哥们 
1.21.3了........
Minecraft 官网发布了 1.21.3 的更新日志：
https://www.minecraft.net/en-us/article/minecraft-java-edition-1-21-3
