### ISSUE TITLE
基于#4996 进一步添加1.21.3版本版本选项

### ISSUE THREAD

**Issue by Joker2184** [Hex-Dragon/PCL2#4997]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

无敌了......
三连击.........

Minecraft 官网发布了 1.21.3 的更新日志：
https://www.minecraft.net/en-us/article/minecraft-java-edition-1-21-3

### 原因

嘶 Bugjump 的锅

**Comment by LTCatt** [comment]
并入 #4996
