### ISSUE TITLE
通用的options设置

### ISSUE THREAD

**Issue by fyhbauyg** [Hex-Dragon/PCL2#4999]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- 
### 描述

在"设置/游戏"里面添加一个通用options/配置文件选项,
选择一个options.txt文件保存在pcl的配置文件夹，
每当安装新版本或整合包时自动替换/添加options,txt文件.

### 原因

更方便的游戏

**Comment by Chiloven945** [comment]
#1353
