### ISSUE TITLE
联机优化：使用新联机核心，以降低延迟、提高稳定性

### ISSUE THREAD

**Issue by LTCatt** [Hex-Dragon/PCL2#50]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

换用新的联机核心。

### 原因

现在的联机核心在网络差的时候容易连不上，并且部分时候延迟很高。

**Comment by lorki** [comment]
### 新模块流程

- [ ] 1.用户输入凭证 > 检测凭证对应的配置文件在本地是否存在
- [ ] 2. 如果存在 `hiper -config ./凭证.yml`
       如果不存在:
- [ ] 3.则请求  https://cert.mcer.cn/凭证.yml
- [ ] 4.请求成功 > 将文件保存到同路径下 | 后续步骤同2
- [ ] 5.请求失败或404 > 提示用户已超过下载时效或凭证无效 > 用户可选择 导入配置 或 确定（关闭窗口）
- [ ] 6.用户选择 导入配置 > 弹出文件打开对话框 > 读取文件内容 | 步骤同4

### 其它配置

- [ ] 用户服务协议: `https://mcer.cn/agreement`  隐私条款: `https://mcer.cn/privacy`
- [ ] 界面可显示当前网络在线时间（从启动网络到现在）
- [ ] 捕获网卡初始化错误 ``` {"level":"fatal","msg":"activate failed: Failed to find the tap device in registry with specified ComponentId 'tap0901', TAP driver may be not installed","time":"2022-08-03T20:56:43+08:00"} ```
- [ ] 将日志格式变更为json,向上面下载的配置末位加入以下内容
``` ymal
logging:
  format: json
```
- [ ] 另:将配置文件`配置.yml`变更成`config.yml`与`hiper.exe`放到一起，可以免参数启动hiper
- [ ] 如果网络启动成功，建议把密钥加密后保存到配置文件里面。然后凭证输入框内容变成8个⚪，如果启动从配置文件读到凭证，输入框就固定显示8个⚪。
- [ ] 设置项里面可以开启是否自动重启（遇到错误，类似守护功能）
- [ ] 启动状态最好由颜色区分（例如 启动中为橙色，正在运行为绿色，错误为红色）
- [ ] ip地址点击后复制到粘贴板（鼠标移动上去出现气泡提示：点击复制） - 最好能探测到游戏里面开放的端口，复制地址的时候带上游戏里面的端口号
- [ ] 安全可选项：允许IP准入/仅开放联机端口/封禁IP/其他用户加入提醒/访问日志统计等

**Comment by lorki** [comment]
新模块发布地址 https://gitcode.net/to/hiper/-/tree/master

**Comment by lorki** [comment]
*新增 通过扩展套件局域网广播玩家远程服务器地址 （免游戏内手动输入地址）
新模块发布地址 https://gitcode.net/to/hiper/-/tree/master/utils/minecraft-boradcast
例如远端玩家 6.6.9.9 开启游戏，使用端口26535 本地只需启动 mcb -addr 6.6.9.9:26535 即可完成局域网广播及登入（听说这样能离线使用）

**Comment by RX6950XTlikeMINECRAFT** [comment]
千万别想HMCL那样隔三差五炸几次啊啊啊

**Comment by lorki** [comment]
> 千万别想HMCL那样隔三差五炸几次啊啊啊

那个貌似都摆烂了，哎！
