### ISSUE TITLE
打开启动器后自动设置为无披风

### ISSUE THREAD

**Issue by LOVE9752** [Hex-Dragon/PCL2#5002]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

打开MC官网，设置为MCC披风，刷新页面仍是MCC披风，打开PCL，关闭（有时要多次打开关闭）。再打开MC官网，刷新（有时要多次打开关闭），显示为无披风而不是之前选定的MCC披风。皮肤不受影响，是我在用PCL更改了一次披风后才有的这个bug，以前没有（也可能我没注意）

### 重现步骤

具体为当登录PCL时，可能触发重置披风（皮肤不受影响），但在我使用PCL设置披风之前，没有过这个bug（可能有但我没注意）

### 日志与附件

[Log4.txt](https://github.com/user-attachments/files/17508017/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17508018/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/17508019/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17508020/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17508021/Log3.txt)

**Comment by ALiaoHaolong** [comment]
我昨天也遇到了类似的bug，通过PCL上传设置皮肤后，披风没了，上官网一看，披风钩了无。那如果每次在pcl设皮肤之后还要去官网改披风，那何不直接在官网改皮肤呢=D

**Comment by ChinioEGyet** [comment]
我也是前两天开始遇到这种情况。在**官网**、**官启**或是**pcl2**里改披风都是没有问题的，接着首次进游戏里也能显示有披风。但是，一旦关闭了启动器，下次再打开启动器，就会如题自动设置为无披风，pcl2和官启都是这样。在官网、官启或是pcl2里设置好披风之后访问 _https://sessionserver.mojang.com/session/minecraft/profile/<UUID>_ 可以看到玩家属性properties的value里的“CAPE”字段是有纹理和对应的url的，但是只要**下次一打开pcl2或者是官启**（没有启动游戏），value立即就会丢失“CAPE”字段，即自动设置为了无披风。重试了好多遍，每次都会丢失。~~还用hmcl试过了，hmcl似乎没有这个问题~~

**Comment by LOVE9752** [comment]
再补充一下，在PCL里换了披风后，当时有效，关闭启动器再次启动后，变成了无披风（官网和管启都是）

**Comment by LOVE9752** [comment]
这个bug在我清理了一次缓存垃圾后消失了。我不确定再换一次披风后，这个bug是否会再次出现

**Comment by LTCatt** [comment]
无法复现，有其他人能复现吗？
如果现在提交者和其他人都不能复现，我怎么怀疑是麻将服务器炸了一段时间……

**Comment by LOVE9752** [comment]
我也复现不了这个bug，当时不知道管启有没有这个bug，只知道PCL 有，既然有人说管启也有这个bug极有可能是mojang的问题

**Comment by LOVE9752** [comment]
这算是提交bug吗，能获得隐藏主题吗？

**Comment by wyc-26** [comment]
![image](https://github.com/user-attachments/assets/d932ace9-1bcb-4f54-9f7e-483d69c434b2)
被标记为 [完成] 才算
