### ISSUE TITLE
1.21.3有些MOD最新版本读不出来 但MOD官网已经更新

### ISSUE THREAD

**Issue by AYaogo** [Hex-Dragon/PCL2#5003]
### 检查项

- [ ] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

1.21.3正式版有些MOD已经更新到游戏最新版本 但是 有时候会读取不出来 

### 重现步骤

![7fd82d8bc8e1d822cc49e4a41ce2871c](https://github.com/user-attachments/assets/a5b759b4-e378-4d79-9f84-15b994cb4ec5)
![1cdbc3b81db35d606f980cac6dbb239f](https://github.com/user-attachments/assets/2322aa2d-9fd6-404f-b7fa-d816648f3093)
![3ba5760998a47eac2c748ff5d64bd29f](https://github.com/user-attachments/assets/af27dace-edb3-42cf-9e9b-e63650018fca)

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/17517613/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17517616/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17517617/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17517618/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17517619/Log5.txt)

**Comment by Chiloven945** [comment]
![image](https://github.com/user-attachments/assets/582c159d-7b53-4b16-a8a4-2e8012adc1d9)
未能复现。

**Comment by wwwrow** [comment]
pcl2应该是有延迟的，我也出现了这种情况

**Comment by LTCatt** [comment]
应该是 API 缓存导致的，这个不是我能解决的 orz
