### ISSUE TITLE
崩溃分析优化：排除单模组支持多版本的崩溃内容以准确分析

### ISSUE THREAD

**Issue by JingHai-Lingyun** [Hex-Dragon/PCL2#5006]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

[错误报告-10-25-2024_6.19.39_PM.zip](https://github.com/user-attachments/files/17520544/-10-25-2024_6.19.39_PM.zip)

IsoRender 导致的，无法准确提供信息

### 原因

优化崩溃分析能力

**Comment by LTCatt** [comment]
![image](https://github.com/user-attachments/assets/d26a67a3-6bf2-41d9-8a7f-e20d439f43bf)
因为 #4700 有乱码，不过可以分析了

**Comment by LTCatt** [comment]
草，和 #4980 重复，才发现，本着谁先交就是谁的的原则把这个关了吧……sorry
