### ISSUE TITLE
将mod拖入mod管理时

### ISSUE THREAD

**Issue by wwwrow** [Hex-Dragon/PCL2#5008]
### 检查项

- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

将mod使用pcl2删除后，回收站内该文件乱码

### 重现步骤

1、点击版本设置
2、往下滚，然后点击mod管理
3、然后点击删除名为[[预生成区块] Chunky-1.4.16.zip](https://github.com/user-attachments/files/17522821/Chunky-1.4.16.zip)的mod
4、打开回收站，该文件为乱码命名，**像该文件被修改过**

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/17522650/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17522652/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17522653/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17522655/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17522656/Log5.txt)

**Comment by JingHai-Lingyun** [comment]
什么意思？

**Comment by wwwrow** [comment]
mod删除后文件乱码

**Comment by wwwrow** [comment]
mod删除后文件乱码

**Comment by wwwrow** [comment]
有概率，有时行，有时不行

**Comment by lactobionicAcid** [comment]
与 #4227 重复？

**Comment by JingHai-Lingyun** [comment]
请 Author 确认是否想要反馈的内容是 #4227 的情况

**Comment by wwwrow** [comment]
哦，是的，抱歉我没有看到 #4227

**Comment by wwwrow** [comment]
不是的，删除后打开回收站mod名字就已经被改了

**Comment by SALTWOOD** [comment]
https://github.com/Hex-Dragon/PCL2/issues/4227#issuecomment-2240943461

看看是不是这样子的文件名
是的话就关了

**Comment by wwwrow** [comment]
文件名是的，但过程不是

**Comment by LTCatt** [comment]
能把回收站里的那个 mod 截个图么？
以及我这里没法复现，可能需要另一个人复现再处理 =。=
