### ISSUE TITLE
Gitee 主页预设无法加载

### ISSUE THREAD

**Issue by LTCatt** [Hex-Dragon/PCL2#5012]
### Discussed in https://github.com/Hex-Dragon/PCL2/discussions/5011

<div type='discussions-op-text'>

<sup>Originally posted by **MFn233** October 25, 2024</sup>
![image](https://github.com/user-attachments/assets/ee42db89-e08d-413c-ac60-8458214c6d36)
gitee坏事做尽
所以。。。

https://[raw.gitcode.com/MFn233/PCL-Mainpage/raw/main/Custom.xaml](https://raw.gitcode.com/MFn233/PCL-Mainpage/raw/main/Custom.xaml)</div>

**Comment by WorldHim** [comment]
不建议其他主页继续使用 Gitee raw
我曾经使用过 Gitee 作为图床，不出意外几天就封了
虽然不知道为什么这次过了很长时间才封，但还是建议相关主页也进行迁移

**Comment by LTCatt** [comment]
> 不建议其他主页继续使用 Gitee raw 我曾经使用过 Gitee 作为图床，不出意外几天就封了 虽然不知道为什么这次过了很长时间才封，但还是建议相关主页也进行迁移

@MFn233

**Comment by MFn233** [comment]
@LTCatt 改成gitcode.com的吧
就是我帖子里写的那个

**Comment by MFn233** [comment]
虽然还是raw..

**Comment by WorldHim** [comment]
> @LTCatt 改成gitcode.com的吧
> 就是我帖子里写的那个

gitcode 目前还没有限制嘛？不过还是不推荐使用第三方 git 来提供服务

**Comment by MFn233** [comment]
> > @LTCatt 改成gitcode.com的吧
> > 就是我帖子里写的那个
> 
> gitcode 目前还没有限制嘛？不过还是不推荐使用第三方 git 来提供服务

现在还没有，至少广告猫猫这么说的

**Comment by wuliaodexiaoluo** [comment]
>虽然还是raw..

Try Release?
如果这都限制的话那真没办法了

**Comment by MFn233** [comment]
> >虽然还是raw..
> 
> Try Release?
> 如果这都限制的话那真没办法了

好像真是个办法

**Comment by JingHai-Lingyun** [comment]
@WForst-Breeze 你的也麻烦改下，Gitee 都 403 了
![image](https://github.com/user-attachments/assets/b455d553-d467-4b23-ad6e-b9623867499d)

**Comment by LTCatt** [comment]
#4926 也是用的 Gitee

**Comment by WForst-Breeze** [comment]
实在抱歉……最近实在是腾不开时间，明天我会尽可能抽时间修改的

**Comment by WForst-Breeze** [comment]
现在换成了 Gitcode @LTCatt 
```
https://raw.gitcode.com/WForst-Breeze/WhatsNewPCL/raw/main/Custom.xaml
```

**Comment by ZeroWolf233** [comment]
离谱，gitcode的唯一用处，或许可以试试自己部署一个http服务来承载这个会更好？就是成本高点

**Comment by zkitefly** [comment]
可以试试 gitee pages？

**Comment by Light-Beacon** [comment]
换下新闻主页链接至 `https://pcl.mcnews.thestack.top`
_（已私聊，仅提醒）_

**Comment by JingHai-Lingyun** [comment]
额外支持信息：
Homeplaza-Of-PCL2 组织已经支持 OSS 加载，目前有两个主页正在测试中，也欢迎别的主页加入
详情请见
- #5014 
- https://github.com/HomePlaza-Of-PCL2/Discussions/discussions/2

**Comment by wuliaodexiaoluo** [comment]
>可以试试 gitee pages？

Gitee Page 貌似很早就不提供了吧

**Comment by LTCatt** [comment]
@Ext1nguisher 请更换为其他网站的地址

**Comment by Joker2184** [comment]
> 额外支持信息： Homeplaza-Of-PCL2 组织已经部署 OSS 加载服务，目前有两个主页正在测试中，也欢迎别的主页加入 详情请见
> 
> * [主页部署迁移计划 HomePlaza-Of-PCL2/Discussions#2](https://github.com/orgs/HomePlaza-Of-PCL2/discussions/2)

https://github.com/Hex-Dragon/PCL2/discussions/5058
