### ISSUE TITLE
标题颜色更改会保留前一个颜色的图案

### ISSUE THREAD

**Issue by Aminos114514** [Hex-Dragon/PCL2#5015]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

当你选择的颜色有图案时，更换其他没有图案的颜色时，图案将会保留而不是消失

### 重现步骤

1、点击设置
2、然后点击个性化
3、随机一个有图案的颜色
4、更换龙猫蓝等没有图案的颜色
5、图案将不会消失
![CED960A651D34945F2A9979240C925D7](https://github.com/user-attachments/assets/f0f3b6aa-c675-487f-b61b-4de7bc9a544d)

![E75D16DCC01FE8C60036A631DDE3F781](https://github.com/user-attachments/assets/1e0db3b3-6086-4e56-a189-88a2709e7a4f)
![377481A533946106527E5B352B039493](https://github.com/user-attachments/assets/2012e1ae-77a8-4cf4-9361-080391d463a4)

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/17529903/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17529904/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17529905/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17529906/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17529907/Log5.txt)
[Log.txt](https://github.com/user-attachments/files/17529908/Log.txt)

**Comment by lactobionicAcid** [comment]
与 #4960 重复...
