### ISSUE TITLE
自动搜索 Java 不会搜索名称仅包含数字的文件夹

### ISSUE THREAD

**Issue by freecube0209** [Hex-Dragon/PCL2#5016]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我在这个discussion里发了具体的情况，包含详细说明和log文件：
https://github.com/Hex-Dragon/PCL2/discussions/5013
主要问题就是对其他文件夹存放的非安装形式的openjdk无法扫描。目前通过在系统变量path里添加路径解决。
但是有佬建议我发个issue呈给龙猫看看，故有此issue。

### 重现步骤

见discussion。

### 日志与附件

见discussion。

**Comment by LTCatt** [comment]
无法搜索的 java 完整路径能发一下吗？PCL 在进行全盘搜索时，会检测文件夹名是否包含一系列的关键字，如果都没有就不会进入文件夹搜索

**Comment by freecube0209** [comment]
> 无法搜索的 java 完整路径能发一下吗？PCL 在进行全盘搜索时，会检测文件夹名是否包含一系列的关键字，如果都没有就不会进入文件夹搜索

好的。无法被搜索到的七个java路径如下：
D:\java\dragonwell\8\dragonwell-8.20.21\bin
D:\java\dragonwell\11\dragonwell-11.0.24.20+8-GA\bin
D:\java\microsoft\17\mojang-java-runtime-beta\bin
D:\java\microsoft\21\mojang-java-runtime-delta\bin
D:\java\oracle\8\mojang-jre-legacy\bin
D:\java\zulu\17\zulu17.54.21-ca-jdk17.0.13-win_x64\bin
D:\java\zulu\21\zulu21.38.21-ca-jdk21.0.5-win_x64\bin

可能是被我塞的太里面了？
