### ISSUE TITLE
对于"安装Mod"按钮的优化

### ISSUE THREAD

**Issue by 596wjr** [Hex-Dragon/PCL2#5019]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

这个可能和 #4095 有一些冲突，但我认为在Mod管理的安装mod按钮的功能应该是调用文件资源管理器选择一个jar文件安装，这样比“拖进启动器窗口”会更好一些
也可以说按照 #4095 那样把“从本地安装mod”改成这个功能

### 原因

如果没有这项优化，我每次都必须打开文件资源管理器，找到mod文件，让操作变得很麻烦。

**Comment by SALTWOOD** [comment]
现在 PCL 的模组下载功能那么发达，感觉就是删掉都没啥问题（？

**Comment by 596wjr** [comment]
> 现在 PCL 的模组下载功能那么发达，感觉就是删掉都没啥问题（？

你要知道，一些mod只在自己的官网上发布

**Comment by LTCatt** [comment]
转 #4095
