### ISSUE TITLE
在启动其中，遇见新版本后点击查看详情后，下载中无这个版本。

### ISSUE THREAD

**Issue by wrk-123** [Hex-Dragon/PCL2#502]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在启动器中，遇见新版本后点击查看详情后，下载中无这个版本。

### 重现步骤

1、打开启动器（确保MC发布了新版本且打开了版本提醒）
2、点击查看详情并查看网页（这里是1.19.3pre-3）
3、查看下载，没有这个版本。

### 日志与附件

[logs（可能log1log2有用，在版本升级后并未解决问题）.zip](https://github.com/Hex-Dragon/PCL2/files/10131584/logs.log1log2.zip)

**Comment by LTCatt** [comment]
下载源未更新，不是启动器的问题。
