### ISSUE TITLE
PCL切换主题时原来的纹理会保留

### ISSUE THREAD

**Issue by leipishu** [Hex-Dragon/PCL2#5020]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

切换PCL主题，如果从例如滑稽彩等有纹饰的主题转换为没有纹饰的例如龙猫蓝的主题会保留纹理，只有换成其他带纹理的主题时才会换纹理
例如：
![屏幕截图 2024-10-27 105837](https://github.com/user-attachments/assets/40ebedf0-09de-449a-a691-3a271b82aaa3)
换完以后
![屏幕截图 2024-10-27 105856](https://github.com/user-attachments/assets/c8fbd78d-fccd-480f-af07-dec9dcb7cbe0)

（我不知道这是不是刻意为之，如果是，请忽略）

### 重现步骤

1、换成像极客蓝/滑稽彩/神秘紫/跳票红等带有纹饰的主题
2、换成如龙猫蓝等颜色主题，纹饰将被保留

### 日志与附件

例如：
![屏幕截图 2024-10-27 105837](https://github.com/user-attachments/assets/40ebedf0-09de-449a-a691-3a271b82aaa3)
换完以后
![屏幕截图 2024-10-27 105856](https://github.com/user-attachments/assets/c8fbd78d-fccd-480f-af07-dec9dcb7cbe0)

**Comment by Ad-closeNN** [comment]
- #4960
