### ISSUE TITLE
给村民救援披风添加翻译

### ISSUE THREAD

**Issue by tiantian114514** [Hex-Dragon/PCL2#5029]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

给村民救援披风添加翻译

### 原因

让村民救援披风有翻译
![Uploading pcl2披风界面.png…]()

**Comment by tiantian114514** [comment]
识别码

**Comment by Ad-closeNN** [comment]
> 识别码


**优化** 类 issue **无法解锁**活跃橙
![image](https://github.com/user-attachments/assets/be9de3b7-ce6b-4d88-9b6a-f4984aac9884)
