### ISSUE TITLE
forge 1.16.5 2.34 Minecraft启动失败：补全文件失败

### ISSUE THREAD

**Issue by rinhau** [Hex-Dragon/PCL2#503]
### 检查项

- [ ] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

版本forge 1.16.5 2.34 ，带MOD和不带MOD都试了一遍，设置里面的三个选项的下载源也都试过了，梯子也开着关着都试过一遍，都是弹出这个窗口：

![image](https://user-images.githubusercontent.com/93511743/205163924-3823fb93-30f1-4fdc-b1d1-e06a101329ea.png)

更换HMCL启动器之后也是报错但是并不是由于补全文件失败而是别的原因：
![image](https://user-images.githubusercontent.com/93511743/205163661-29912411-deec-4ffd-aa08-17563db573e6.png)

### 重现步骤

1、点击启动游戏
2、然后补全文件进度一直卡在66.77，然后就发生上述弹窗

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10136289/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10136290/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10136291/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10136292/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10136293/Log5.txt)

**Comment by LTCatt** [comment]
需要重新安装，你安装的版本是损坏的。

**Comment by rinhau** [comment]
您好，我重新安装一个新的版本之后变成了这个窗口
![image](https://user-images.githubusercontent.com/93511743/205252118-278dca65-ad98-4905-a2d6-793d599fd365.png)



[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10139474/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10139475/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10139476/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10139477/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10139478/Log5.txt)
)

**Comment by LTCatt** [comment]
如果有需要的话按照游戏崩溃的模板重新开一个 issue
