### ISSUE TITLE
应该将版本直接移动至收藏夹

### ISSUE THREAD

**Issue by Crotina** [Hex-Dragon/PCL2#5031]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

应该直接将版本移动到收藏夹，这是当前的↓

![image](https://github.com/user-attachments/assets/e97e8c18-39ca-491e-b3a6-4fbd87d8175f)

应该直接移动到收藏夹，而不是在原来的分类里继续保留

### 原因

（示例）
这项优化让我可以更方便地管理版本。
如果没有这项优化，我删掉无用版本的时候可能给我收藏的误删了。

**Comment by LTCatt** [comment]
关于这个问题大家怎么想？
如果觉得收藏的版本应该从原列表移除（如本 issue 所说），选 ↑
如果觉得收藏的版本不应移除（保持现状），选 ↓
