### ISSUE TITLE
添加隐藏pcl2更新模组功能的选项

### ISSUE THREAD

**Issue by E0x72-21** [Hex-Dragon/PCL2#5033]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

隐藏模组更新功能和模组旁的更新提示图标
![image](https://github.com/user-attachments/assets/f07b39f5-4c33-4811-8cb1-8108a44edce2)

开关放在功能隐藏卡片下
![image](https://github.com/user-attachments/assets/1e7c2ebf-d089-48d1-8b4d-d138cd0cb355)

### 原因

防止整合包用户手贱更新模组导致整合包炸掉

**Comment by LTCatt** [comment]
不用 cc，挂 `等待确认` 标签后我就能看到了.jpg

**Comment by E0x72-21** [comment]
> 不用 cc，挂 `等待确认` 标签后我就能看到了.jpg

不懂就问这个cc是啥意思）
