### ISSUE TITLE
PC L启动器一直提示游戏Java不兼容， HMCL却可以直接启动

### ISSUE THREAD

**Issue by willla888** [Hex-Dragon/PCL2#5036]
### 检查项

- [ ] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃基本不是 PCL 的原因，请 **不要** 提交反馈。你可以在论坛或社区找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用 HMCL 启动，HMCL 没有出现问题。** 如果 HMCL 也无法启动就不是 PCL 导致的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

PC L1直提示游戏Java不兼容，HMCL却可以直接启动，希望调整，可以看附件（压缩包）

### PCL 错误报告、日志与附件

[错误报告-2024-10-31_9.15.28.zip](
![屏幕截图 2024-10-31 084844](https://github.com/user-attachments/assets/1ab531ad-c677-492d-9143-358e18e5f2d7)
https://github.com/user-attachments/files/17580645/-2024-10-31_9.15.28.zip)
![屏幕截图 2024-10-31 084722](https://github.com/user-attachments/assets/e37fc0c8-b8c5-41ff-8113-c1a9fb9dd686)
![屏幕截图 2024-10-31 084755](https://github.com/user-attachments/assets/ff8e8fb8-01eb-403d-9b49-042636b77a71)

### HMCL 启动脚本

[mai.zip](https://github.com/user-attachments/files/17580656/mai.zip)

**Comment by wuliaodexiaoluo** [comment]
PCL 选定

```
[09:15:04.829] [Java] 最终选定的 Java：JDK 21 (21.0.3)：E:\.minecraft\runtime\java-runtime-delta\bin\
[09:15:04.829] [Launch] 选择的 Java：JDK 21 (21.0.3)：E:\.minecraft\runtime\java-runtime-delta\bin\
```

HMCL 选定

```
 'C:\Program Files\Java\jdk-17.0.4\bin\java.exe'
```

可能为 #3547

**Comment by LTCatt** [comment]
实际崩溃原因：
```
Caused by: org.spongepowered.asm.mixin.throwables.ClassMetadataNotFoundException: java.util.function.Function
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:754) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
```

并非 #3547。

可能是不兼容 Java 21 导致的，但目前也没有遇到 Forge 1.19.2 (43.1.0) 不兼容 Java 21 的啊？
提交者手动选择 Java 17 启动看看会不会崩？

**Comment by Steven7559** [comment]
可以证实1.19.2forge不兼容JAVA21
https://pan.baidu.com/s/13y3zPxhZgb66CZsqlWIfEA?pwd=PCL1 密码：PCL1

**Comment by LTCatt** [comment]
![image](https://github.com/user-attachments/assets/e55ddcad-e9b3-48c1-ab55-dcf2292a6758)
我这里 Java 21 可以启动 1.19.2 Forge。
到底啥情况？

**Comment by Steven7559** [comment]
测试后，bellsoft 和 labymod 的java21能正常启动
是不是mojiang JAVA的问题？
https://www.123684.com/s/ENC6Vv-MPdyd

**Comment by Deep-Dark-Forest** [comment]
由于原作者太长时间没有回复，所以关闭此 Issue。
