### ISSUE TITLE
对海外网络环境的支持？

### ISSUE THREAD

**Issue by PlayMcBKuwu** [Hex-Dragon/PCL2#5038]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

```
INFO[0250] [1291784351 1ms] outbound/shadowsocks[proxy]: outbound connection to pcl2-server-1253424809.file.myqcloud.com:443
```
挂代理（中国台湾，台中市）打开 PCL II ~~帮助页面~~偶然看到的一条日志。
似乎是连接了腾讯云的存储服务。
**修正: 并非帮助页面之问题。**
> 腾讯云存储服务仅用于 PCL2 的公告与更新下发。

想问问，是否有对海外网络环境支持的打算？
比如，为海外网络添加如 Amazon S3 等存储服务方式 ~~虽然这很明显不可能~~。

顺便提一嘴，
中国台湾的网络似乎在连接官方源更快的时候仍然连接 BMCL API 下载。
```
INFO[0247] [3891077700 0ms] outbound/shadowsocks[proxy]: outbound connection to bmclapi2.bangbang93.com:443
```

### 原因

目前的情况对于部分地区的网络环境可能会很头痛，
比如距离中国大陆很近的中国香港、中国澳门和中国台湾等 DNS 污染现象较少以及没有 GFW 的地区。

**Comment by tangge233** [comment]
您好，感谢你的反馈。

帮助页目前是随启动器打包一同更新的，不会出现由于网络导致的加载问题。腾讯云存储服务仅用于 PCL2 的公告与更新下发。

另外关于海外仍旧使用 BMCLAPI 的问题请参考如下链接
#3466
#4833

**Comment by PlayMcBKuwu** [comment]
> 您好，感谢你的反馈。
> 
> 帮助页目前是随启动器打包一同更新的，不会出现由于网络导致的加载问题。腾讯云存储服务仅用于 PCL2 的公告与更新下发。PCL 也有使用 GitHub raw 作为更新源之一。
> 
> 另外关于海外仍旧使用 BMCLAPI 的问题请参考如下链接 #3466 #4833

~~海外更新 PCL II 恐成第二问题~~

**Comment by LTCatt** [comment]
PCL 的腾讯云主要用于更新检查，考虑到现在主要都是国内在用，暂时没有扩展支持的计划。
