### ISSUE TITLE
建议在自定义主页中添加一个可以让其他程序运行的环境

### ISSUE THREAD

**Issue by hongshitnl** [Hex-Dragon/PCL2#5039]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

如标题，在pcl中内置一个环境，其他程序可以在其中运行，pcl也可以从程序获取信息实时输出在pcl页面上（哪怕只搞一个cmd一样的终端也行啊）

### 原因

有这个功能，可以把很多功能集成在自定义主页上，比如实时翻译，甚至小游戏，可以让pcl自定义主页有更多玩法

**Comment by hongshitnl** [comment]
虽然我知道更新的gailv渺茫，但龙猫不能看都不看吧

**Comment by LTCatt** [comment]
过于超出启动器范围，不会考虑 :/
