### ISSUE TITLE
正版登录之后无法获得99次喜悦皮肤

### ISSUE THREAD

**Issue by AYaogo** [Hex-Dragon/PCL2#5045]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

正版登录之后无法获得99次喜悦皮肤

### 重现步骤

1、点击xxxx
2、往下滚，然后点击xxxx
![1](https://github.com/user-attachments/assets/47a5b6eb-ead8-43f4-98c5-7af6262cba76)

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/17605135/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17605136/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17605137/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17605138/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17605139/Log5.txt)

**Comment by Ad-Cat** [comment]
？
![image](https://github.com/user-attachments/assets/9b913cca-0f20-4005-b843-7a02eb33fdee)

**Comment by Ad-closeNN** [comment]
？
![image](https://github.com/user-attachments/assets/f5e22e9e-8263-46a4-9017-2e20fc56afbc)

**Comment by Joker2184** [comment]
不是鸽们

正版是跳票红啊（

99次喜悦是打开99次PCL

**Comment by AYaogo** [comment]
> 不是鸽们
> 
> 正版是跳票红啊（
> 
> 99次喜悦是打开99次PCL

对 失效了我打开不止99次

**Comment by ZeroWolf233** [comment]
这是99次启动PCL啊，关issues罢

**Comment by AYaogo** [comment]
> 贡献

我说的是打开99那个皮肤 正版账号登陆过后 打开99次获得不了这个皮肤

**Comment by Joker2184** [comment]
不一定要正版啊（哥们

我没登陆正版 都有

**Comment by JingHai-Lingyun** [comment]
你需要启动 99 次游戏，且不能取消启动，才可获得 `隐藏主题 铁杆粉`

---

反馈的内容不是 PCL 的 Bug，故此 Issue 将被关闭
如果需要更多帮助，请前往 Dicussion 提问大区发帖提问，谢谢

**Comment by allMagicNB** [comment]
谁告诉你能这么解锁？并且是启动 99 次 PCL 而非游戏。

**Comment by JingHai-Lingyun** [comment]
友好一点…… 谢谢……

**Comment by allMagicNB** [comment]
友好归友好，但我看到误导我就来气。
