### ISSUE TITLE
网络正常的情况下更新PCL2 从2.8.8正式版到2.8.9正式版失败

### ISSUE THREAD

**Issue by PMing-g** [Hex-Dragon/PCL2#5048]
### 检查项

- [ ] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

网络正常但无法正常下载PCL2更新

### 重现步骤

在PCL2 2.8.8版本
点击设置
点击启动器
点击检查更新
跳出发现新版本后点击更新
在下载界面会跳出错误弹窗
![a](https://github.com/user-attachments/assets/f1455f1a-6d18-4282-afed-0a59886b1ab6)

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/17605419/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17605420/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17605421/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17605422/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17605423/Log5.txt)

**Comment by ZeroWolf233** [comment]
看样子像是你那边github连不上？

**Comment by wuliaodexiaoluo** [comment]
https://github.com/Hex-Dragon/PCL2/issues/4965#issuecomment-2421578718

由于第三方问题，手动检查更新可能导致更新失败，请设置为在有更新时弹出提示，弹窗的自动更新可以将 PCL 更新到最新版本

**Comment by wuliaodexiaoluo** [comment]
如果有条件可以使用代理，或者可以尝试手动下载新版本进行替换

**Comment by PMing-g** [comment]
> 如果有条件可以使用代理，或者可以尝试手动下载新版本进行替换

感谢

**Comment by wuliaodexiaoluo** [comment]
如无其他需求可以自行关闭此 Issue，这可以减轻社区的处理压力
