### ISSUE TITLE
下载老版本服务端提示错误

### ISSUE THREAD

**Issue by zhangchengmcbedrock** [Hex-Dragon/PCL2#5050]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![屏幕截图 2024-11-02 150208](https://github.com/user-attachments/assets/7bd4fa0e-8454-4160-be27-ce71efbe971f)

### 重现步骤

1、点击下载
2、往下滚，然后点击老版本服务端下载按钮
然后提示构建失败

### 日志与附件

[Log4.txt](https://github.com/user-attachments/files/17605995/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17605996/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/17605997/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17605998/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17605999/Log3.txt)

**Comment by JingHai-Lingyun** [comment]
压根就没有服务端的情况下你希望它能下载下来什么……
这不是 Bug……
