### ISSUE TITLE
优化不存在服务端时的提示

### ISSUE THREAD

**Issue by JingHai-Lingyun** [Hex-Dragon/PCL2#5051]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

Related Issue:
- #5050

### 原因

现有的文本可能会导致用户认为这是一个意外错误或者 Bug

**Comment by LTCatt** [comment]
并入 #4982
