### ISSUE TITLE
启动器在 access_token 过期后依旧不会刷新 access_token

### ISSUE THREAD

**Issue by FQO3** [Hex-Dragon/PCL2#5053]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

（就说感觉哪次更新说是把这个bug修了……）
#4333 的问题在Snapshot 2.8.9(341.0 )依旧存在
![image](https://github.com/user-attachments/assets/6976a6a7-dcd4-4cc5-96b1-6b887ef55c0f)
![image](https://github.com/user-attachments/assets/c17a34e7-695c-4ae7-915b-9c7bc8084523)
![image](https://github.com/user-attachments/assets/82db37d6-a720-433f-8786-f5dd4e5a863e)
![image](https://github.com/user-attachments/assets/6393a825-2819-4c49-b578-d3a0db687733)

这可能是我碰巧遇到的，我今天没时间再等token过期一次了，找时间我再试一遍，但至少现在有这个问题……

### 重现步骤

1. 启动PCL
2. 等待token过期
3. 进入服务器提示过期，再次启动MC也一样
4. 和 #4333 一样查看token的过期时间

### 日志与附件

如下：
[Log1.txt](https://github.com/user-attachments/files/17607066/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17607067/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17607068/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17607069/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17607065/Log5.txt)

**Comment by allMagicNB** [comment]
@LTCatt 我都没看懂咋修的……

**Comment by LTCatt** [comment]
Ln 1986 应当重启登录加载器但是并没有重启……
```
[19:35:49.459] [Loader] 加载器 登录 状态改变：Loading
[19:35:49.459] [Loader] 加载器 补全文件 状态改变：Loading
[19:35:49.459] [Loader] 加载线程 登录 (85) 已启动
[19:35:49.459] [Download] 17.json：已加入列表，剩余文件 1
[19:35:49.459] [Loader] 加载器 下载支持库文件（主加载器） 状态改变：Loading
[19:35:49.459] [Launch] 登录加载已开始
[19:35:49.459] [Loader] 加载器 分析缺失支持库文件 状态改变：Loading
[19:35:49.459] [Launch] 登录加载已结束
[19:35:49.459] [Loader] 加载器 登录 状态改变：Finished
```

**Comment by FQO3** [comment]
申请补发活跃橙（换电脑了）识别码：4BB5-1DC7-6F2D-C273

**Comment by LTCatt** [comment]
你的解锁码：e7LO08bhKab0mscq4BgpUB/PpUZ/eWWw
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
