### ISSUE TITLE
希望可以提供linux版的软件

### ISSUE THREAD

**Issue by eden-chen3** [Hex-Dragon/PCL2#5056]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

为linux用户开发linux版的PCL2

### 原因

我明白用linux系统的人很少，用linux玩游戏的人更是少之又少，但我还是希望可以提供linux版的软件来满足这一部分人的需求

**Comment by JingHai-Lingyun** [comment]
很抱歉这无法做到，请参见：
- #54
