### ISSUE TITLE
版本设置-mod管理 页面无法加载来自curseforge的mod的图标

### ISSUE THREAD

**Issue by Hoicey522** [Hex-Dragon/PCL2#5062]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/user-attachments/assets/e1e9c016-6962-47e0-8df0-7171d444ccc9)
如图所示，刷新mod列表依然无法显示来自curseforge的mod的图标，网络能正常进入curseforge网站，电脑使用全局代理依然无法显示

### 重现步骤

1、点击版本设置
2、进入mod管理页面

### 日志与附件

[Log2.txt](https://github.com/user-attachments/files/17617141/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17617142/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17617143/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17617144/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/17617145/Log1.txt)

**Comment by Hoicey522** [comment]
![image](https://github.com/user-attachments/assets/e1d86f0c-721a-4865-b6de-c871dd576cb9)
版本为快照版2.8.9

**Comment by Hoicey522** [comment]
![image](https://github.com/user-attachments/assets/be28b513-6fbf-44de-968e-b7d94537152d)
1.21.1版本也无法加载出来

**Comment by Hoicey522** [comment]
[ModHash.zip](https://github.com/user-attachments/files/17619535/ModHash.zip)
我只能以压缩包的形式发送...github提示不支持

**Comment by Hoicey522** [comment]
之前有一个bug是所有mod都不显示图标的，修好了就正常显示，但不知为何现在会有部分显示不了

**Comment by LTCatt** [comment]
比较神秘，我在 2.8.10 加了点调试输出，等到新版本更新之后需要你在复现一次然后传 log，然后我这才能修，抱歉 orz

**Comment by Hoicey522** [comment]
那个invhud mod是cf独有的（另一个cf独有的mod Advanced XRay也无法显示图标），carpet mod 在modrinth有1.21.1版本，能正常显示；然后cf的carpet mod独有1.21.2版本也能显示图标，但是到了1.21.3又显示不了了。
似乎这个bug可能和版本有关？或者说仅来自cf？
其他来源的mod也无法显示图标：樱花版本的masa全家桶显示不了图标（从github下载）

**Comment by Hoicey522** [comment]
![image](https://github.com/user-attachments/assets/2a87b199-14fb-4ca3-a039-7618b4b16633)
![image](https://github.com/user-attachments/assets/80012435-0037-43f8-9cbc-f3ef2f23c177)

**Comment by LTCatt** [comment]
用了楼主传的缓存文件，还是无法复现，先关了

**Comment by Hoicey522** [comment]
> 用了楼主传的缓存文件，还是无法复现，先关了

我下回那个文件，又能复现了
![image](https://github.com/user-attachments/assets/c8db499b-8e3a-4b0b-b009-8fd64f99facf)

**Comment by Hoicey522** [comment]
要不等下一个版本更新了看看情况？我先把整个%TEMP%\PCL 上传在这里吧。
[PCL.zip](https://github.com/user-attachments/files/17647823/PCL.zip)

**Comment by LTCatt** [comment]
能补充提供一下出现问题的 mod 文件的完整路径么，包括它所在的文件夹路径

**Comment by Hoicey522** [comment]
![image](https://github.com/user-attachments/assets/9a8d1bbd-e77e-444c-adda-6033ef3048fe)

**Comment by LTCatt** [comment]
umm 缓存里包含文件的读写时间，这个实在没法在我这还原。
姑且加了个保底修复，应该可以在缓存异常时不使用缓存。

**Comment by LTCatt** [comment]
你的解锁码：8K+YhR7lU5aCfAsXLiRvD8yFnP8JNo9Z
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
之后在这个 issue 下回复就行

**Comment by Hoicey522** [comment]
![Image](https://github.com/user-attachments/assets/0e0b87ef-2b30-4ea5-8aa4-7dc91d1d535d)
问题再次复现
尝试使用百宝箱的清理游戏垃圾、清理电脑的临时文件依然这样子，保险起见我上传整个游戏文件夹。

[PCL启动器.zip](https://github.com/user-attachments/files/19719712/PCL.zip)

**Comment by LTCatt** [comment]
看起来你的 Modrinth 请求被 CloudFlare 拦截了，转 #5406
