### ISSUE TITLE
...

### ISSUE THREAD

**Issue by kclon666** [Hex-Dragon/PCL2#5070]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

无

### 重现步骤

1、点击xxxx
2、往下滚，然后点击xxxx

### 日志与附件

[Log2.txt](https://github.com/user-attachments/files/17660108/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17660109/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17660110/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17660111/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/17660112/Log1.txt)

**Comment by tangge233** [comment]
无效反馈，如果您需要活跃橙，请反馈一个 PCL 最新版本中真实存在的 Bug 或者给 PCL 提交一个有实际意义的 PR

**Comment by Joker2184** [comment]
无效反馈

**Comment by kclon666** [comment]
....



---Original---
From: ***@***.***&gt;
Date: Thu, Nov 7, 2024 18:48 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Hex-Dragon/PCL2] ... (Issue #5070)




 
无效反馈
