### ISSUE TITLE
 local:MyImage未知问题

### ISSUE THREAD

**Issue by Joker2184** [Hex-Dragon/PCL2#5072]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

使用Image 可以正常获取来自B站的图片
使用新的新的local:MyImage 报403
### 原因

![QQ截图20241108160824](https://github.com/user-attachments/assets/1163c359-678d-4302-abde-9b19ce26744a)

**Comment by Joker2184** [comment]
![QQ截图20241108161237](https://github.com/user-attachments/assets/892cd35d-4364-414a-bd15-7e8256a5bc6b)
[Log1.txt](https://github.com/user-attachments/files/17675374/Log1.txt)

**Comment by Joker2184** [comment]
算bug吗（（（
能活跃橙吗（（（

活跃橙 = 贡献者的象征（单纯喜欢攒

**Comment by wuliaodexiaoluo** [comment]
>> 报403
>
>算bug吗（（（
>能活跃橙吗（（（

~我感觉不太行(~
~大概率是拒绝/放弃（~

**Comment by Joker2184** [comment]
> > > 报403
> > 
> > 
> > 算bug吗（（（
> > 能活跃橙吗（（（
> 
> ~我感觉不太行(~ ~大概率是拒绝/放弃（~
> 
> 这个优化不算的，要求必须是 pr 或者 Bug

问问龙猫（（ abb

**Comment by LTCatt** [comment]
算 bug，这个不是预期行为 =。=

**Comment by Joker2184** [comment]
好喂
