### ISSUE TITLE
Mod 详情页面允许输入文本以筛选卡片

### ISSUE THREAD

**Issue by JingHai-Lingyun** [Hex-Dragon/PCL2#5075]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

实现一个简单的搜索框（仅文本输入）来筛选版本

### 原因

![image](https://github.com/user-attachments/assets/cb696bb8-64db-4100-8eca-15e7970432d7)
新版过长的列表可能对查找老旧版本或特定版本 Mod 带来困难

**Comment by LTCatt** [comment]
同 https://github.com/Hex-Dragon/PCL2/issues/5074#issuecomment-2464704637
