### ISSUE TITLE
TextButton设置Foreground 未在鼠标移上去后恢复颜色....

### ISSUE THREAD

**Issue by Joker2184** [Hex-Dragon/PCL2#5078]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

测试优化更新日志的UI....然后就颜色没了很突兀被凌云说了...
然后就发现了
![QQ截图20241109102714](https://github.com/user-attachments/assets/c29b633a-86c9-496a-b598-b99a622571a0)
![QQ截图20241109102554](https://github.com/user-attachments/assets/15940aa0-f802-4d1b-9ff1-a799d1aeaaba)
![QQ截图20241109102733](https://github.com/user-attachments/assets/35a65ed8-8bf2-45e9-bc16-eb3ac42ac450)

https://github.com/user-attachments/assets/ed2e9985-bad2-4922-87db-0838eeaa6287

### 重现步骤

设置一个带Foreground的TextButton
```
<local:MyTextButton Margin="4,4,4,0" Foreground="{DynamicResource ColorBrush2}" EventType="打开网页" EventData="https://github.com/Hex-Dragon/PCL2/discussions/5071">信息错误反馈</local:MyTextButton>
````

然后鼠标移上去

然后颜色就没有了....

### 日志与附件

不涉及启动器本体无需log

**Comment by WorldHim** [comment]
#2510

**Comment by Joker2184** [comment]
> #2510

重复但没修.jpg

考虑为这个加报错吗（
