### ISSUE TITLE
多项下载时出现崩溃

### ISSUE THREAD

**Issue by Aoi-Karlin** [Hex-Dragon/PCL2#5085]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在连续下载两个版本时，pcl2启动器会出现未响应（R2.8.9）

### 重现步骤

1、点下载
2、点自动安装
3、随便下载第一个版本
4、随便选第二个版本
按下确定安装后崩溃

### 日志与附件

[Log4.txt](https://github.com/user-attachments/files/17686389/Log4.txt)
[Log2.txt](https://github.com/user-attachments/files/17686390/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17686391/Log3.txt)
[Log1.txt](https://github.com/user-attachments/files/17686393/Log1.txt)
Log5：不存在（为上次启动时修改）

**Comment by Joker2184** [comment]
未能复现...

**Comment by Aoi-Karlin** [comment]
那就可能是我机器问题了（

**Comment by Aoi-Karlin** [comment]
但是在我的机器上好像能稳定复现？

**Comment by JingHai-Lingyun** [comment]
如果你在这之后找到了更多线索，随时欢迎你回来补充
两周之后如无回复此贴将会被关闭（不影响补充）

**Comment by Deep-Dark-Forest** [comment]
由于原作者太长时间没有回复，所以关闭此 Issue。
