### ISSUE TITLE
新的 Mod 详情页面可能会极大地增多页面内的卡片数量

### ISSUE THREAD

**Issue by xxtg666** [Hex-Dragon/PCL2#5087]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

对于 modrinth 上有些支持几乎全版本的数据包会出现这种现象：

<details>
<summary>多图预警</summary>

![image](https://github.com/user-attachments/assets/c3fffa88-b413-4a2c-aca4-e78a056656e3)

![image](https://github.com/user-attachments/assets/96e42617-d0bb-4cb7-8f73-a58fb697994a)

![image](https://github.com/user-attachments/assets/e1fba4b7-79c6-4af3-b0ba-9ca2721d462c)

![image](https://github.com/user-attachments/assets/c59c1280-dfdd-4980-b4c1-e6890131d3de)

![image](https://github.com/user-attachments/assets/24ee0fac-d0d3-42de-bfc6-a79a2d7726d3)

![image](https://github.com/user-attachments/assets/025dabb1-93fa-4817-8e29-32a6755aa2c3)

![image](https://github.com/user-attachments/assets/e9d6dc5e-84e8-4e57-8f6a-d9bd708f2728)

![image](https://github.com/user-attachments/assets/9943f16f-2400-4cfa-be35-2bf6d61a9845)

太多了后面不放了
</details>

如果文件相同的话是否可以合并一下卡片……？
比如显示一个 Fabric 1.16-1.21.3 这样的，毕竟也有一些mod是相同文件支持多个版本

### 原因

只是觉得下载页面东西越来越多了……

**Comment by JingHai-Lingyun** [comment]
参考资料
- #5074 
- #5075

**Comment by LTCatt** [comment]
我下个版本再考虑一下怎么改吧……确实想不到什么好的方案 =。=

**Comment by SALTWOOD** [comment]
有个想法，上面来一行展示 NeoForge Forge Fabric Quilt 的切换选项卡，然后每一页专门展示对应的加载器的？

**Comment by QianFuv** [comment]
![image](https://github.com/user-attachments/assets/f7eb3705-4698-49c9-ba7c-6515f28bb963)
或许可以参考一下 modrinth 的样式？

**Comment by LTCatt** [comment]
![image](https://github.com/user-attachments/assets/331a4694-944c-4548-b300-6e40242acfc1)
这样应该行了……
