### ISSUE TITLE
回退Mod下载详情界面

### ISSUE THREAD

**Issue by LogicWheat** [Hex-Dragon/PCL2#5088]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

将新版本更新的mod详情界面回退到旧版本的样式。
如果可以，还可以在下载的版本前加上对应加载器的图标。这样会更加直观和美观。
neo：狐狸，forge：铁砧，fabric：布料......

### 原因

新更新的mod详情界面相较于以前显然是不方便的。
在以前，用户只需要点进mod详情，点击版本，选择合适的加载器即可。
这显然是符合从粗分（mod版本）到细分（mod加载器）的直觉的，画面也更清爽简洁。
新版本更新后，用户需要在相同版本的不同加载器中选择。
看起来似乎更直观了，但却失去了逻辑性，还导致了mod详情界面内容数量的大幅提升。
这会导致下载时更难找到自己所需要的版本与加载器。
同时因为用户现在选择mod版本时需要兼顾mod加载器与游戏版本，会感到眼花缭乱。
而且经过实际体验与测试，我发现：下载到错误的mod版本的概率远高于以前。
综上，建议回退mod下载的详情界面。
感谢。

**Comment by wuliaodexiaoluo** [comment]
https://github.com/Hex-Dragon/PCL2/issues/5074#issuecomment-2464704637

**Comment by LTCatt** [comment]
转 #5087
