### ISSUE TITLE
拖拽下载mod

### ISSUE THREAD

**Issue by WangYiBen0** [Hex-Dragon/PCL2#5089]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

在mod页面拖拽mod到文件资源管理器中以下载到此处

### 原因

我需要这个功能来便捷地下载mod到别的地方以分享。

**Comment by JingHai-Lingyun** [comment]
![image](https://github.com/user-attachments/assets/5e701e40-15a5-4344-98ec-949f4d3f9218)
应当可以满足了？

**Comment by LTCatt** [comment]
见楼上。不打算做类似功能……
