### ISSUE TITLE
Fabric客户端间断性无法启动

### ISSUE THREAD

**Issue by K01sh1** [Hex-Dragon/PCL2#509]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃不是 PCL2 的原因，请 **不要** 提交反馈。你可以在 QQ 群里或者论坛找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是游戏本身的问题，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

fabric端这边经常间断性无法启动，也会有一段时间是forge端无法启动，一般二者只有一个可以启动

### 错误报告、日志与附件

[Uploading 错误报告-2022-12-2_17.38.34.zip…]()

**Comment by WForst-Breeze** [comment]
您的错误报告未能成功上传，请再次上传游戏错误报告及启动器日志文件，谢谢qwq

**Comment by LTCatt** [comment]
确实怀疑是 #472 ，并且啥附件都没上传上来，总之先关了吧 =。=
