### ISSUE TITLE
取消下载的按钮应该做大一点？

### ISSUE THREAD

**Issue by Crotina** [Hex-Dragon/PCL2#5091]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

现在下载页的取消下载按钮就是右上角的小叉叉，我觉得应该换成一个大一点的按钮

### 原因

（示例）
这项优化让我可以更方便地xxxx。
如果没有这项优化，我每次都必须点那个小叉叉，让操作变得很麻烦。

**Comment by SALTWOOD** [comment]
个人感觉没有很大的改进……等龙猫过来看看吧

**Comment by LTCatt** [comment]
这个应该不会影响什么，大家应该也找得到……
