### ISSUE TITLE
[Bug] 在下载执行过程中点击取消会报错：索引超出范围。必须为非负值并小于集合大小。

### ISSUE THREAD

**Issue by wuliaodexiaoluo** [Hex-Dragon/PCL2#5093]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

~梦回清朝了属于是~
```
[07:21:49.209] 尝试开始下载线程失败（7b82612898e03ec61a3f49f809db703cfcd90c46）：索引超出范围。必须为非负值并小于集合大小。
参数名: index
   在 System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   在 System.Collections.Generic.SynchronizedCollection`1.get_Item(Int32 index)
   在 PCL.ModNet.NetFile.TryBeginThread()
错误类型：System.ArgumentOutOfRangeException
```

第一次错误为 Line in 11930  ~（WForst-Breeze:?）~

这个问题是在调试开源版时出现的，用快照版测试后发现快照版也有这个问题
虽然看起来没啥影响（并不会导致任何问题？），但好像不符合预期？

### 重现步骤

1.随便下两个版本
2.然后在安装过半时都点击取消

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/17689688/Log1.txt)

**Comment by wuliaodexiaoluo** [comment]
网络环境上我这边连接 BMCLAPI 和 Mojang API 都是没有问题的
Issue 好像也没看到重的
至于测试其他启动器.......其他启动器应当不会有这个问题，所以为了节约时间直接跳过

**Comment by Joker2184** [comment]
复现成功

感觉单纯是速度快卡出来的

**Comment by LTCatt** [comment]
与 #3771 实质同一个 bug 导致
