### ISSUE TITLE
PCL2初始化错误，且不生成日志文件

### ISSUE THREAD

**Issue by 7310269373** [Hex-Dragon/PCL2#5095]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![微信图片_20241110101131](https://github.com/user-attachments/assets/14c7eb83-5945-4f2c-a821-4fddd53ccae5)
2024.11.09更新最新测试版，10号就这样了，有无网络代理和VPN均是，且不生成logX.txt

### 重现步骤

打开Plain Craft Launcher 2.exe

### 日志与附件

这是自上次更新以来的日志文件（从2024.11.09）
[Log3.txt](https://github.com/user-attachments/files/17689983/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17689984/Log4.txt)
[Log1.txt](https://github.com/user-attachments/files/17689985/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17689986/Log2.txt)

**Comment by ikun1221** [comment]
> ### 检查项
> * [x]  我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。
> 
> ### 描述
> ![微信图片_20241110101131](https://private-user-images.githubusercontent.com/117023880/384654965-14c7eb83-5945-4f2c-a821-4fddd53ccae5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMDgzODgsIm5iZiI6MTczMTIwODA4OCwicGF0aCI6Ii8xMTcwMjM4ODAvMzg0NjU0OTY1LTE0YzdlYjgzLTU5NDUtNGYyYy1hODIxLTRmZGRkNTNjY2FlNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQwMzA4MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMTk3ZjU4NjNiYWZiZDNlZTJhMjg1OWRmODZiY2FkYzg0N2ZjNDEyZDczZDNhZTFkZjQ2Y2JkMGQyNmJkYWEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.O3y627qFErVPGf59DrQpSer1lp7Uqtzw1kPS9l1A1tE) 2024.11.09更新最新测试版，10号就这样了，有无网络代理和VPN均是，且不生成logX.txt
> 
> ### 重现步骤
> 打开Plain Craft Launcher 2.exe
> 
> ### 日志与附件
> 这是自上次更新以来的日志文件（从2024.11.09） [Log3.txt](https://github.com/user-attachments/files/17689983/Log3.txt) [Log4.txt](https://github.com/user-attachments/files/17689984/Log4.txt) [Log1.txt](https://github.com/user-attachments/files/17689985/Log1.txt) [Log2.txt](https://github.com/user-attachments/files/17689986/Log2.txt)

需要复现

**Comment by Joker2184** [comment]
emmm
删掉注册表 缓存 PCL文件夹 然后重新下载PCL试试？

**Comment by ikun1221** [comment]
很奇怪，log里似乎没有问题

**Comment by 7310269373** [comment]
> emmm 删掉注册表 缓存 PCL文件夹 然后重新下载PCL试试？

注册表更改成了我重装系统前的备份文件，就可以启动了，不知道为什么

**Comment by Joker2184** [comment]
？？？

**Comment by lactobionicAcid** [comment]
与 #4517 重复。
_wow 竟然真的成功复现了，原来是注册表问题吗？_

**Comment by LTCatt** [comment]
转 #4517
