### ISSUE TITLE
音乐播放器导致PCL2崩溃

### ISSUE THREAD

**Issue by Gluoluo** [Hex-Dragon/PCL2#5096]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

点击播放后，pcl2会高频率尝试播放每一首音乐然后不断地弹出无法播放的提示，尽管它不能播放该格式并且会跳过，但最为常见的MP3格式也会被影响导致不能播放。在循环了一段时间后，会弹出“出现错误”的窗口，并且无法通过“取消”键来关闭！强制终止后，会再次循环触发以上bug。直至手动打开文件夹清空音频文件后才恢复正常。

### 重现步骤

1、首先使用一次程序的清空音乐文件功能。
2、接着把带有ogg,MP3格式的音频文件(共五个，按名称排序）复制到刚刚清空的文件夹中（第一个文件是ogg）。
3、然后点击右下角的播放按钮。

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/17690147/Log1.txt)

**Comment by JingHai-Lingyun** [comment]
看日志抛出了一堆来自 HRESULT:0xC00D36C4 的异常……

**Comment by Joker2184** [comment]
![bde5876156040971ed3ebff47bd01163](https://github.com/user-attachments/assets/c3eed445-d1d4-40c3-aad4-a04568bec0c7)
震撼（

老版本的压力测试百宝箱妇科了吗

**Comment by LTCatt** [comment]
```
播放音乐出现内部错误（D:\Minecraft\PCL\PCL\Musics\Mystery Within.ogg）：由于操作系统或显卡存在问题，导致出现错误。请尝试重启 PCL。
不支持给定的 URL 的字节流类型。 (异常来自 HRESULT:0xC00D36C4)
————————————
详细错误信息：
   在 NAudio.MediaFoundation.MediaFoundationInterop.MFCreateSourceReaderFromURL(String pwszURL, IMFAttributes pAttributes, IMFSourceReader& ppSourceReader)
   在 NAudio.Wave.MediaFoundationReader.CreateReader(MediaFoundationReaderSettings settings)
   在 NAudio.Wave.MediaFoundationReader..ctor(String file, MediaFoundationReaderSettings settings)
   在 NAudio.Wave.AudioFileReader.CreateReaderStream(String fileName)
   在 NAudio.Wave.AudioFileReader..ctor(String fileName)
   在 PCL.ModMusic.MusicLoop(Boolean IsFirstLoad)
错误类型：System.Runtime.InteropServices.COMException
```

这个还应该单独处理，看起来是不支持 ogg 导致的报错，提示有误

**Comment by LTCatt** [comment]
你的解锁码：oDT7+qHsgnwqCZyuuNdo9eorYT3vs8YE
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
