### ISSUE TITLE
在游戏窗口出现后弹出报错：线程执行失败

### ISSUE THREAD

**Issue by mmt2233** [Hex-Dragon/PCL2#5097]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

游戏窗口出现后PCL弹出报错

Runtime Invoke 6623#：线程执行失败：NoDriver calling waveOutRestart
   在 PCL.ModMusic._Closure$__._Lambda$__14-0()
   在 PCL.ModBase._Closure$__**132-0**._Lambda$__0()
错误类型：NAudio.MmException

版本：PCL2 Snapshot 2.8.10 (343.0)
加粗处与搜索到的已知反馈 #4956  中的 描述 不相同
版本与 #4956 同样 不 相同

### 重现步骤

目前无法再次触发这个Bug

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/17690365/Log1.txt)

**Comment by lactobionicAcid** [comment]
与 #1753 重复。这是 NAudio 的 Bug。
