### ISSUE TITLE
出现错误:WARNING: Unknown module: cpw.mods.bootstraplauncher specified to --add-exports

### ISSUE THREAD

**Issue by SongzqInChina** [Hex-Dragon/PCL2#5099]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃基本不是 PCL 的原因，请 **不要** 提交反馈。你可以在论坛或社区找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用 HMCL 启动，HMCL 没有出现问题。** 如果 HMCL 也无法启动就不是 PCL 导致的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

报错

### PCL 错误报告、日志与附件

[错误报告-2024-11-10_15.33.20.zip](https://github.com/user-attachments/files/17690628/-2024-11-10_15.33.20.zip)

### HMCL 启动脚本

[启动脚本.zip](https://github.com/user-attachments/files/17690654/default.zip)

**Comment by SongzqInChina** [comment]
问题来自网友

**Comment by SALTWOOD** [comment]
没有安装模组的原版出现了输出日志极少的崩溃……很罕见的情况。
看 Java 是 32 的，试试看使用 64 的 Java？

**Comment by wuliaodexiaoluo** [comment]
```Exception in thread "main" java.lang.UnsatisfiedLinkError: 'java.lang.String oolloo.jlw.NativeCommandLineLoader.getCommandLine()'
	at oolloo.jlw.NativeCommandLineLoader.getCommandLine(Native Method)
	at oolloo.jlw.NativeCommandLineLoader.load(NativeCommandLineLoader.java:78)
	at oolloo.jlw.Wrapper.main(Wrapper.java:37)

```

疑似为 jlw 的问题
日志内显示 PCL 为 Release 2.8.9，路径不包含任何中文字符，只有操作系统为 32 位系统....

**Comment by SALTWOOD** [comment]
又仔细分析了一下，严重怀疑是因为 32 位系统的问题。
请尝试在 64 位系统复现

**Comment by zkitefly** [comment]
重新安装该版本

**Comment by LTCatt** [comment]
考虑到环境问题，大家可能都不太能尝试重现，最好把原反馈者叫来才好办……
@00ll00 jlw 现在是不兼容 32 位么（

**Comment by wuliaodexiaoluo** [comment]
>考虑到环境问题，大家可能都不太能尝试重现，最好把原反馈者叫来才好办……

环境问题嘛，或许可以虚拟机？

**Comment by SongzqInChina** [comment]
要是这个人自己能反馈为什么还要找我😭

**Comment by SongzqInChina** [comment]
他说HMCL是可以启动的

**Comment by 00ll00** [comment]
> > 考虑到环境问题，大家可能都不太能尝试重现，最好把原反馈者叫来才好办…… @00ll00 jlw 现在是不兼容 32 位么（
> 
> 嘶……以前没注意到`UnsatisfiedLinkError`它是个 Error，我之前寻思 catch 了用备用方案🏃‍♂️
> 
> 至于 x86 的库好像是有些问题，过几天有空了研究下。

找到问题了，是 dll 导出函数的调用约定和 java 定义的不一样导致的；以及备用方案应该可以在 native 加载失败时使用上了。

[更新 wrapper](https://github.com/00ll00/java_launch_wrapper/releases/tag/v1.4.3)🌹
