### ISSUE TITLE
在模组文件名较长时单模组更新按钮被右侧按钮遮挡

### ISSUE THREAD

**Issue by QianFuv** [Hex-Dragon/PCL2#5101]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如题

### 重现步骤

1. 需要设置 Mod 管理样式为“标题显示文件名，详情显示译名”
2. 然后添加一个文件名很长的 Mod
3. 当这个更新按钮在此处时![PixPin_2024-11-10_21-50-30](https://github.com/user-attachments/assets/c9e24d5f-e349-45d9-a0c6-8824929efb48)
4. 鼠标移动到相应位置就会发现被挡住力（悲![PixPin_2024-11-10_21-50-14](https://github.com/user-attachments/assets/2e9c2981-bda8-4556-b626-8717003fc2c3)

### 日志与附件

这个和日志没啥关系

**Comment by hejiehao** [comment]
你的启动器版本是？

**Comment by QianFuv** [comment]
最新正式版 2.8.9

**Comment by wuliaodexiaoluo** [comment]
#4465 
请等待正式版更新

**Comment by QianFuv** [comment]
重复了啊 那我关闭这个issue

**Comment by hejiehao** [comment]
成功复现

<details><summary>截图</summary>
<p>

![image](https://github.com/user-attachments/assets/92545412-3ecd-49d9-bf98-ed9fdb7c9bf8)
![image](https://github.com/user-attachments/assets/bf9d90a0-e77b-4f63-8696-e68b2975beef)


</p>
</details>

**Comment by wuliaodexiaoluo** [comment]
> @wuliaodexiaoluo 提交者用的是 2.8.9，你引用的 Issue 是在 [2.8.7](https://github.com/Hex-Dragon/PCL2/releases/tag/2.8.7) 修复的。

大抵是我看错时间了（

**Comment by QianFuv** [comment]
芜湖！
俺的识别码：200C-946F-D1AF-7637

**Comment by LTCatt** [comment]
你的解锁码：SnIJvNXCOOtVxdU1lNe5xxLsQEw0VPPl
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
