### ISSUE TITLE
启动原版1.8.9后会发现材质包和文字都是乱码

### ISSUE THREAD

**Issue by tiantian114514** [Hex-Dragon/PCL2#5103]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

启动游戏（1.8.9）后会发现材质包和文字都是乱码

### 重现步骤

1.打开PCL2下载1.8.9原版
2.进入游戏
3.游戏主界面和进入游戏后材质包和文字都是乱码

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/17691224/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17691225/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17691226/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17691227/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17691228/Log5.txt)

**Comment by wuliaodexiaoluo** [comment]
>游戏主界面和进入游戏后材质包和文字都是乱码

如果界面显示内容为 口口口 之类的字样，请尝试文件补全

**Comment by LTCatt** [comment]
有尝试使用其他启动器吗？

**Comment by tiantian114514** [comment]
尝试过，都是一样的

**Comment by LTCatt** [comment]
如果其他启动器也一样，这个就不是 PCL 导致的问题……
