### ISSUE TITLE
在快照PCL版本中的Mod更新错误

### ISSUE THREAD

**Issue by lazyzyzyzy** [Hex-Dragon/PCL2#5104]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

Minecraft版本为1.21，PCL提示我更新vectorientation模组。但当我更新后，PCL却自动下载了该Mod的1.21.3版本。原本的Mod是1.21的最新版，升级到1.21.3后出现Bug（显示黑屏），我已经在1.21.3和1.21中启动游戏，确认不是Mod的问题。

### 重现步骤

1.下载Minecraft（Fabric）的1.21版本
2.安装vectorientation模组的1.21Fabric版本
3.打开PCL的Mod选择页面，提示更新Mod
4.更新后下载的是1.21.3的Mod，启动游戏后游戏卡住并黑屏

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/17691578/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17691579/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17691580/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17691581/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17691582/Log5.txt)

**Comment by lazyzyzyzy** [comment]
补充：出现Bug后启动游戏，会卡在进度条最后，但实际的GUI已经启用功能（按键可被交互，虽然看不见），全屏后黑屏游戏。

**Comment by SALTWOOD** [comment]
> 简单调查了一下。
> 
> `设置 → 启动器 → Mod 与整合包 → 下载源` 设置为 `尽量使用镜像源` （即使用 MCIM 镜像源）时，会错误匹配到 1.21.3 的 Mod。
> 
> 而选择另外两项（如果启动器选择从 CurseForge/Modrinth 获取），则不会匹配到错误的版本（以本 Issue 情况为例，实际上没有新版本，不会提示更新）。
> 
> Mod 本身在 CurseForge/Modrinth 上的版本标记都是恰当的，这方面应该没有争议。

怀疑是 MCIM 的问题，如果是的话就与 OpenMCIM 无关。
但这个选项理论上不会生效才对……z0z0r4 应该返校了，等他有空再让他处理罢.png

**Comment by wuliaodexiaoluo** [comment]
根据 Modrinth 和 CurseForge 的检索结果，如果忽略掉 Modrinth 那一堆标记了不同版本的 Release v1.1，那么 Mod 适用版本的标记应该是正确的
@z0z0r4 打扰一下，麻烦看看

**Comment by SALTWOOD** [comment]
让龙猫来加个第三方？

**Comment by SALTWOOD** [comment]
速：z0z0r4 已回，要求提供更具体的信息。

> @[后端][高中但走读]SaltWood_233 我借的手机没GitHub号…帮忙叫issue那边提高下具体参数…我自己测试的mr的更新接口没返回奇怪版本才对…post请求在pcl2点日志里啥参数都没

> 有这么反馈的我也是服了，照这么搞以后pcl2仓库的issue我只能一律忽略，让dev自己往我这边提issue…

> …收集个例子给我吧
> hash列表

![Screenshot](https://github.com/user-attachments/assets/34e35449-4941-4e5f-ba7f-36411f1fced4)

**Comment by lazyzyzyzy** [comment]
我这边可以复现啊，Mod是官方来源啊

**Comment by lazyzyzyzy** [comment]
啊，现在好像已经好了，不提示更新了。

**Comment by SALTWOOD** [comment]
> > 也就是说请求的哈希的模组和返回的模组没有一点关系，而且现在问题没了？
> 
> 简单地说，本 Issue 提及的 Mod 的问题现在没了；而几个小时前的新 Issue（#5113）提到的另一个 Mod 出现了类似的问题。我给的参数和结果是另一个 Mod 的。
> 
> 关于另一个 Mod 的问题，可以依次读下 #4886 和 #5113。

很奇怪的问题……抱歉以我的权限无能为力.png
~~我明早也得上学先跑了~~
MCIM 还任重而道远啊，不够稳定

**Comment by SALTWOOD** [comment]
按照目前的状况，应该是作者上传错文件导致的撞库，至少与PCL 无关

可以以“忽略”关闭
