### ISSUE TITLE
自定义帮助页面列表项支持切换特定模组下载页面

### ISSUE THREAD

**Issue by yynsz07** [Hex-Dragon/PCL2#5105]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

自定义帮助页面列表项按钮支持切换到特定模组下载页面，以实现”模组收藏夹“功能

### 原因

需要这个功能来不停查看某个喜欢的模组是否进行了更新，使得不用每次点击下载并输入模组名称来查找模组，也使得能够快速切换查看另一个喜欢的模组。其实此功能相当于在PCL主页面做了一个模组收藏夹。

**Comment by xinyihl** [comment]
- #1646 已经存在于功能投票中
- #4933 已存在相关 pr 但该功能优先级较低

**Comment by LTCatt** [comment]
#4933 已经覆盖了，暂时不考虑给帮助加这个……
