### ISSUE TITLE
游戏无法启动

### ISSUE THREAD

**Issue by rinhau** [Hex-Dragon/PCL2#511]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃不是 PCL2 的原因，请 **不要** 提交反馈。你可以在 QQ 群里或者论坛找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是游戏本身的问题，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

游戏无法启动，尝试了包括：重装整个MC，重装系统，重装JAVA，8 11 16 全都试了一边，还是不行，。

### 错误报告、日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10143743/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10143744/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10143745/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10143746/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10143747/Log5.txt)
[错误报告-2022-12-3_3.25.31.zip](https://github.com/Hex-Dragon/PCL2/files/10143751/-2022-12-3_3.25.31.zip)

**Comment by bwtx2022** [comment]
加我 QQ 1094728939 看看解决一下...

@LTCatt 这个问题貌似有点普遍性

**Comment by rinhau** [comment]
好的，已经申请，您看一下QQ 1015662232

**Comment by LTCatt** [comment]
我不确定这个 Bug 是否有普遍性，并且这是 JVM 报的错，就更蛋疼了……
如果能用 HMCL 成功启动，或者其他人可以复现，可以回复一下……

**Comment by ACGPlanck** [comment]
故障版本是1.16.5-forge-36.2.39吗？
我使用HMCL进行了测试，未发现异常。
附上启动器输出的日志和启动脚本。
[minecraft-exported-logs-2022-12-03T23-12-31.log](https://github.com/Hex-Dragon/PCL2/files/10146789/minecraft-exported-logs-2022-12-03T23-12-31.log)
[hmcl 1.16.5-forge 36.2.39.txt](https://github.com/Hex-Dragon/PCL2/files/10146791/hmcl.1.16.5-forge.36.2.39.txt)

**Comment by ACGPlanck** [comment]
PCL2未能复现bug，不过我用的是JDK17，不是Java 8，或许和这个有关。
另外，老哥启动失败后的暴躁已经快溢出屏幕了.jpg（笑）
“[03:06:08.862] [UI] 选择文件返回：E:\我*死你的*别崩溃了求你了\错误报告-2022-12-3_3.06.06.zip”

**Comment by bwtx2022** [comment]
> 我不确定这个 Bug 是否有普遍性，并且这是 JVM 报的错，就更蛋疼了……
> 
> 如果能用 HMCL 成功启动，或者其他人可以复现，可以回复一下……

根据之前的测试，出现这个错误的用户换用Zulu Java和其他启动器可以解决问题

这位我再看看（

**Comment by dongge0210** [comment]
我觉文件或者JVM可以看看

**Comment by LTCatt** [comment]
> 根据之前的测试，出现这个错误的用户换用Zulu Java和其他启动器可以解决问题
> 这位我再看看（

@bwtx2022 之前有过什么测试……？
这个 JVM 的报错太奇葩了，总觉得不像是启动器能导致的……

**Comment by bwtx2022** [comment]
> > 根据之前的测试，出现这个错误的用户换用Zulu Java和其他启动器可以解决问题
> > 这位我再看看（
> 
> @bwtx2022 之前有过什么测试……？ 这个 JVM 的报错太奇葩了，总觉得不像是启动器能导致的……

有这类问题的用户貌似换了个Java和启动器就好了，其实算不上是测试罢（

**Comment by rinhau** [comment]
大佬们，问题已经解决，谢谢！

**Comment by dongge0210** [comment]
要更新吗？
