### ISSUE TITLE
显卡问题导致PCL异常退出

### ISSUE THREAD

**Issue by EchoesOfDreams** [Hex-Dragon/PCL2#5110]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在使用别人做好的整合包进行多人游玩时，经常提示显卡驱动存在问题。升级过显卡驱动但是并不能解决报错信息，在玩其他整合包或者下载原版的时候从来没有出现这个错误，所以也就一直没有管。直到这次游玩的时候也和之前一样显卡问题导致游戏异常退出，但是PCL也退出了。同时弹出Log日志，提示提交issus，觉得这个bug似乎不太简单...

### 重现步骤

可能是这个整合包的作者的编辑能力有限...修改了一些不知道的地方或者是代码问题导致的bug，但是作者说自己运行这个整合包没有出现问题...感觉应该是针对电脑的硬件配置提示的错误，再加上整合包修改了代码之类的.....

### 日志与附件

[Log3.txt](https://github.com/user-attachments/files/17702590/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17702591/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17702592/Log5.txt)
[Log2.txt](https://github.com/user-attachments/files/17702593/Log2.txt)
[Log1.txt](https://github.com/user-attachments/files/17702594/Log1.txt)

**Comment by SALTWOOD** [comment]
1. 尝试更新显卡驱动。
2. 既然游戏异常退出了，启动器也异常退出，属于正常行为（因为是更深层次的驱动层面甚至硬件层面的，用户层面的程序不能也不该去管），最多做个崩溃重启啥的

**Comment by Deep-Dark-Forest** [comment]
由于原作者太长时间没有回复，所以关闭此 Issue。

**Comment by EchoesOfDreams** [comment]
非常抱歉现在才回复这条issus，更新显卡之后没有看到游戏异常退出和启动器异常退出。
之前启动器启动一直使用的集成显卡，之后修改了启动器的显卡为独显就不存在了。之前总是更新独显而忘记集显。
