### ISSUE TITLE
PCL2 将 Noisium 错误的更新为 Steve's Realistic Sleep

### ISSUE THREAD

**Issue by WinExp** [Hex-Dragon/PCL2#5113]
### 检查项

- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

MC版本为1.21.1 Fabric，检查模组更新时提示Noisium有更新版本，但实际下载的mod为 Steve's Realistic Sleep，且tooltip提示的最新版本也为 Steve's Realistic Sleep，不清楚其他mod有没有这个问题
![image](https://github.com/user-attachments/assets/0e785164-978a-45da-bede-c54c3ff24030)

### 重现步骤

1. 下载 1.21.1 Fabric
2. 下载 Noisium Mod
3. 检查更新

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/17732137/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17732133/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17732134/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17732135/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17732136/Log5.txt)

**Comment by tangge233** [comment]
Noisium 在 Modrinth 的 ID 是 `KuNKN7d2`
Steve's Realistic Sleep 在 Modrinth 的 ID 是 `ZPywkPEo`

日志中下载 `https://cdn.modrinth.com/data/KuNKN7d2/versions/u9GNQrei/stevesrealisticsleep-fabric-1.11.0%2Bmc1.21-1.21.1.jar` 成功

~~怎么 ID 错了还可以下载啊~~

**Comment by lazyzyzyzy** [comment]
我是 #5104 ，该情况跟我的相同（大概）

**Comment by SALTWOOD** [comment]
现在局势有亿点混乱……大多都是 MCIM 出现问题而官方源表现正常……

而负责 MCIM 的 zzr 现在又在学校，没法处理……
管不了，Open93AtHome 也没啥 bug 可以修，摆了.png

**Comment by z0z0r4** [comment]
> 看起来和 #5104 有点像。我试了下请求 MCIM 会出现这个问题，而官方源不会。
> 
> 相关：#4886

对于此 issue 的情况可否给出相关 api 请求 curl，根据你在上一个 issue 中所说的是已经无法复现

**Comment by LTCatt** [comment]
考虑与 #5104 重复？

**Comment by SALTWOOD** [comment]
> 是我发言欠妥，非常抱歉。
> 
> 但我仍然认为两个 issue 的原因是相似的。 #5104 之前确实能复现，但现在问题消失，不排除之前是 Mod 开发者最初设置错了版本而 MCIM 缓存了它。

按照5104的情况看，怕不是作者错误的把另外一个模组传上去，然后刚好官方那边的匹配机制跟MCIM的不一样，于是就导致MCIM这边把重复哈希的文件匹配了上去

既然这样子的话，那我觉得可以把5104关了

**Comment by SALTWOOD** [comment]
> > 现在局势有亿点混乱……大多都是 MCIM 出现问题而官方源表现正常……
> > 
> > 而负责 MCIM 的 zzr 现在又在学校，没法处理…… 管不了，Open93AtHome 也没啥 bug 可以修，摆了.png
> 
> 我觉得你既然没关系还是别在这黑了=。= 没人觉得和你有关系，你也不需要帮我处理这些

我不是在黑……你觉得我提你很烦我可以不提，但是这里又不是MCIM的仓库我在这里你应该管不着吧？

以及以目前的情况我怀疑是那边的匹配机制有点问题，5104的情况应该是因为官方和MCIM这边匹配的机制不一样，于是就把重复哈希的匹配了上去

**Comment by z0z0r4** [comment]
> 是我发言欠妥，非常抱歉。
> 
> 但我仍然认为两个 issue 的原因是相似的。 #5104 之前确实能复现，但现在问题消失，不排除之前是 Mod 开发者最初设置错了版本而 MCIM 缓存了它。

如果只是该mod的信息过期缓存...等我回家手动刷新就行了...

我还以为多大个事，怎么能搞得这么麻烦？

**Comment by xinyihl** [comment]
> 如果只是该mod的信息过期缓存...等我回家手动刷新就行了...
> 
> 我还以为多大个事，怎么能搞得这么麻烦？

手动刷新确实能解决问题，但作为一个公开的 api 提供者这样做明显是不负责任的

已经经过这么长的时间了它仍然没有自动刷新，是否存在逻辑上的问题

**Comment by z0z0r4** [comment]
> > 如果只是该mod的信息过期缓存...等我回家手动刷新就行了...
> > 我还以为多大个事，怎么能搞得这么麻烦？
> 
> 手动刷新确实能解决问题，但作为一个公开的 api 提供者这样做明显是不负责任的
> 
> 已经经过这么长的时间了它仍然没有自动刷新，是否存在逻辑上的问题
> 
> ps: 该问题不适合在 pcl 这里讨论，相关 issue 都可以标记为 `第三方`

虽然我也认为新上的同步逻辑有问题，但已经缓存的版本信息理论上是不需要更改的，因此根本不会当成需要刷新的数据...

**Comment by LTCatt** [comment]
从事实逻辑上，玩家在发现问题的时候肯定只可能知道这是启动器的问题，不知道这是 MCIM 的问题，所以交 issue 当然会交到我这儿来，我觉得这个 “奇怪的处理惯例” 并不可能改变。只能说，可以让社区在发现此类 issue 的时候，再去你那里交一个。
此外，PCL 并不可能将请求的完整信息写入日志。很多请求的返回内容相当大，全部写入会导致日志文件大到有时候无法打开，在有并发请求的时候还会造成巨大的性能消耗。我觉得既然社区已经提供了完整的复现步骤和对应出问题的 Mod，就已经可以独立构造请求并复现了。

**Comment by z0z0r4** [comment]
那么可以麻烦社区 contributior 在这种情况下往这边提一下 issue 提供一份示范请求吗？只知道个 api route，我没法去调查原因…

PCL2 的 mod 更新这类功能，我完全没用过，我本地连一个 mod 都没…

我之前确实有一直收到缺 mod 的情况，但现在就 modrinth 而言也收录了 80% 左右了…不太清楚原因，也没空调查，有xd愿意协助吗…？

~~我个人已经两年没启动过游戏了，c 端亲身体验为 0…当然也可以说我不负责，但我确实不咋参与这个圈子了…虽然在维护 mod 镜像，但我从最开始玩这个游戏到现在也对 mod 玩法从来没有兴趣…=_=~~

**Comment by z0z0r4** [comment]
> > 如果只是该mod的信息过期缓存...等我回家手动刷新就行了...
> > 
> > 我还以为多大个事，怎么能搞得这么麻烦？
> 
> 手动刷新确实能解决问题，但作为一个公开的 api 提供者这样做明显是不负责任的
> 
> 已经经过这么长的时间了它仍然没有自动刷新，是否存在逻辑上的问题
> 
> ps: 该问题不适合在 pcl 这里讨论，相关 issue 都可以标记为 `第三方`

看来我确实不负责任

~~毕竟突然发现其实可以回一组 "上游问题""同步间隔较长""请以官方源为准""镜像不保证准确性"…何必一天上14个钟的学还得来郁闷下自己周末咋处理这个 issue =` '=~~

**Comment by z0z0r4** [comment]
> > 如果只是该mod的信息过期缓存...等我回家手动刷新就行了...
> > 
> > 我还以为多大个事，怎么能搞得这么麻烦？
> 
> 手动刷新确实能解决问题，但作为一个公开的 api 提供者这样做明显是不负责任的
> 
> 已经经过这么长的时间了它仍然没有自动刷新，是否存在逻辑上的问题
> 
> ps: 该问题不适合在 pcl 这里讨论，相关 issue 都可以标记为 `第三方`

看来我确实不负责任

~~毕竟突然发现其实可以回一组 "上游问题""同步间隔较长""请以官方源为准""镜像不保证准确性"…何必一天上14个钟的学还得来郁闷下自己周末咋处理这个 issue =` '=~~

**Comment by Joker2184** [comment]
~~公式做题就是快~~

**Comment by xinyihl** [comment]
我认为的解决方案（我并不知道 MCIM 相关 api 的实现方式）
1. 对类似的 api 数据设置一个过期时间
2. 不对类似的 api 进行缓存

接下来的话可能有点尖锐
<details>

平心而论

我们在此讨论也就是为了解决这个别人提交的 issue

但我认为做镜像本事就是一种为爱发电的事并且同时也 100% 会遇到各种各样的问题

这不是一句话的事这是需要消耗很多精力的

那么当初你带头做了 MCIM  是否考虑了这一层

在开源社区你完全没必要提及你打了删除线的话，这里甚至有不少 “我要你的xx源码有什么用，给我构建” 这种人
</details>

**Comment by z0z0r4** [comment]
关于此 issue 调查结果我初步预计为是不可避免。为了我的个人名誉我需要声明：不是我的锅，我不知道是谁的

参考 [https://github.com/mcmod-info-mirror/mcim-sync](https://github.com/mcmod-info-mirror/mcim-sync) 的刷新逻辑可知道，只有在 `updated` 字段有所变化时，才会进一步拉取该 Mod 的所有版本信息。根据我的经历，作者无法在一个 mod 的版本已经发布的情况下，修改 Primary file，只能修改 additional files，因此我采取上述的同步逻辑

![image](https://github.com/user-attachments/assets/f0fc689e-b5a0-43ba-8161-fc7fde9b8818)

回到该 issue

参考 [https://api.modrinth.com/v2/project/KuNKN7d2](https://api.modrinth.com/v2/project/KuNKN7d2) 和 [https://mod.mcimirror.top/modrinth/v2/project/KuNKN7d2](https://mod.mcimirror.top/modrinth/v2/project/KuNKN7d2) 对比可知其中的日期相关字段无一更新，因此当然不需要更新这个 Mod 的任何信息（下载量等实时变化的数据不在守备范围之内）

```JSON
{
    "id": "KuNKN7d2",
    "slug": "noisium",
    "title": "Noisium",
    "published": "2023-10-30T16:01:00.818699Z",
    "updated": "2024-11-04T16:31:33.284303Z",
    "approved": "2023-11-01T03:54:07.304317Z",
    "queued": "2023-10-30T16:14:58.045792Z",
    ...
}
```

然而，根据 issue 的跟踪，作者修改了已发布版本的文件，可以得出 Modrinth 平台似乎可以以不为人知的方式，在不更新数据库内存储日期的情况下，修改该 project 内含的内容...

我不知道作者是如何做到的，我问其他 Mod 开发者也表示 Web 端是无法修改的，我认为这是特例，可能联系了管理员

**Comment by z0z0r4** [comment]
> 我认为的解决方案（我并不知道 MCIM 相关 api 的实现方式）
> 
> 1. 对类似的 api 数据设置一个过期时间
> 2. 不对类似的 api 进行缓存
> 
> 示范请求[3gf8jv4dv](https://github.com/3gf8jv4dv) 已经给出了 [#5113 (comment)](https://github.com/Hex-Dragon/PCL2/issues/5113#issuecomment-2475399611)
> 
> 接下来的话可能有点尖锐

我姑且，非常，不认可，你的解决方案，和你对我的观点。

除了不应该用删除线这点，我应该加粗，因为看来我非常需要充分传达自身的背景情况和个人看法

**Comment by z0z0r4** [comment]
> > 然而，根据 issue 的跟踪，作者修改了已发布版本的文件，可以得出 Modrinth 平台似乎可以以不为人知的方式，在不更新数据库内存储日期的情况下，修改该 project 内含的内容...
> 
> 我再次仔细看了下 #4886 和 [Steveplays28/noisium#43](https://github.com/Steveplays28/noisium/issues/43) 。Mod 开发者似乎是把错误发布的版本给移除了。想问下已发布的 Mod 版本是可以移除的吗？（虽然凭常识我觉得应该可以）

抱歉我逻辑好像有点错误，容我删除以上的推理...

**Comment by z0z0r4** [comment]
结案：同步逻辑没考虑版本可能删除的情况。我误会了...我以为是 Modrinth 特例下允许了该 Mod 作者修改 primary file

**Comment by JingHai-Lingyun** [comment]
转三方处理，这不是 PCL 的问题 😅

**Comment by z0z0r4** [comment]
已经修复，以后在同步中会处理这种情况，但过往数据需要全部重新拉取，会造成很大的负担，基本上主动进行全量刷新是不现实的...因此这个问题会拖上一段时间

任意 Mod 的版本列表将会在下次该 Mod 的更新被捕捉到的时候重新检查

**Comment by WinExp** [comment]
能要个主题吗 o.0
识别码：1F05-F92E-EF3C-8BFC

**Comment by LTCatt** [comment]
你的解锁码：NKQDe24NJtNc7/CE3R0nmngyiQ2A2wb2
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by z0z0r4** [comment]
modrinth 已经清理完了，curseforge 根本扫不动
