### ISSUE TITLE
在版本设置中修改版本隔离选项后点击取消后提示框反复弹出

### ISSUE THREAD

**Issue by LingXu268** [Hex-Dragon/PCL2#5118]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在版本设置中修改版本隔离选项后点击取消后提示框反复弹出，按ESC和取消均反复弹出，重启PCL2后故障仍然存在，已检查PCL2为最新版，任何可单独设置版本隔离选项的版本都能触发（无论游戏启动还是没启动）

### 重现步骤

1.点击任意版本的版本设置
2.点击设置
3.点击版本隔离，并修改选项
4.点击取消或按ESC，Bug触发

### 日志与附件

[Log4.txt](https://github.com/user-attachments/files/17778942/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17778943/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/17778944/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17778945/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17778946/Log3.txt)

**Comment by BasicMirror268** [comment]
补充：在触发该bug后退出PCL2，选项会被更改到你更改的选项而不是保留原样

**Comment by JingHai-Lingyun** [comment]
已确认。

> 在触发该bug后退出PCL2，选项会被更改到你更改的选项而不是保留原样

我测试的时候他保留了原样

**Comment by yjl214** [comment]
我也复现了

**Comment by LingXu268** [comment]
识别码

**Comment by LTCatt** [comment]
你的解锁码：C54iVJd942hmOEDnhbGzassQIFEsOFM/
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
