### ISSUE TITLE
第一次打开PCL启动器时有一个联机选项，然后我点击联机卡了一下又没了跳到了启动页

### ISSUE THREAD

**Issue by jzy0728** [Hex-Dragon/PCL2#5121]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

第一次打开PCL启动器时在上方选项栏有一个联机选项，然后我点击了一下选项栏上的联机点了接着卡了一下回到了主页

### 重现步骤

目前不知道，只不过我有几次重新安装PCL启动器才会出现联机选项

### 日志与附件

我不知道LOG1-5分别对应什么

**Comment by JingHai-Lingyun** [comment]
🕑 联机板块曾经于 [快照版 2.4.0](https://github.com/Hex-Dragon/PCL2/releases/tag/2.4.0) 加入，[快照版 2.5.1](https://github.com/Hex-Dragon/PCL2/releases/tag/2.5.1) 正式移除旧版联机（IOI/HiPer）入口

---

### ❇️有关新版联机（Octo Network）的公告，请参见 [快照版 2.6.11 更新日志](https://www.bilibili.com/read/cv28121157/)：

*“至于联机，因为网易还在继续代理中国版，我和 HMCL 的维护者都觉得还得谨慎一点……况且现在也有 Mod 支持联机了……咳咳。” ——龙腾猫跃*
BakaXL 现已于 2023 年 10 月 8 日将其部分服务与 Octo 章鱼网络进行对接，并对其可用性进行初步评估，待评估完成后，Octo 网络会全面对其他启动器开放[^1]


---

> 我不知道LOG1-5分别对应什么

### ❓PCL 的日志在哪里
在启动 PCL 后，它所在的文件夹中会生成一个名为 PCL 的文件夹。打开它，其中的 Log1.txt 至 Log5.txt 即为日志文件。
推荐你在提交日志前，先在“设置 → 启动器 → 调试选项”中打开调试模式，并重现 Bug。

[^1]: 请注意，Octo 开放不等价于 PCL 上线联机，具体信息以龙猫发布的消息为准，仅供参考。届时切勿散布任何未经相关启动器作者及服务提供方证实的信息。

**Comment by JingHai-Lingyun** [comment]
如果您仍然希望我们详细分析您遇到的问题，请上传您的 PCL 日志 Log1.txt ~ Log5.txt

**Comment by Deep-Dark-Forest** [comment]
由于原作者太长时间没有回复，所以关闭此 Issue。
