### ISSUE TITLE
在“进程优先级”中，添加“高于正常”和“低于正常”两个选项，优先级为：高>高于正常>正常>低于正常>低

### ISSUE THREAD

**Issue by CryRaSa** [Hex-Dragon/PCL2#5122]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

在“进程优先级”中，添加“高于正常”和“低于正常”两个选项，优先级为：高>高于正常>正常>低于正常>低

### 原因

把游戏进程调成高于正常，把OBS录屏软件的优先级调成高，这样可以为录屏软件提供更高的优先级，否则两个进程的优先级都为高

**Comment by shimoranla** [comment]
>把游戏进程调成高于正常，把OBS录屏软件的优先级调成高，这样可以为录屏软件提供更高的优先级，否则两个进程的优先级都为高

我记得没错的话，高=高于正常，低=低于正常

**Comment by Ad-closeNN** [comment]
![image](https://github.com/user-attachments/assets/6484efc1-1a67-48d7-ab7f-871215e03a05)

**Comment by Pigeon0v0** [comment]
感觉没有这个必要...

**Comment by LTCatt** [comment]
感觉适用面很小，普通玩家也会更纠结选项之间的区别……暂时不考虑 orz
