### ISSUE TITLE
修改版本名被拒绝访问

### ISSUE THREAD

**Issue by Hiujnqb** [Hex-Dragon/PCL2#5123]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我曾给过PCL启动器管理员权限且在检查无误后修改任提示拒绝访问

### 重现步骤

使用Release2.8.10修改版本名

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/17783951/Log1.txt)
![新建 PNG 图像](https://github.com/user-attachments/assets/84f54395-003f-4018-a824-724db2c85e4d)
![新建 PNG 图像 (2)](https://github.com/user-attachments/assets/8f6d9406-1b1e-4123-8860-8d6d37fa6116)

**Comment by Ad-closeNN** [comment]
- 按照 #3962 的方法试一下？

**Comment by ZeroWolf233** [comment]
看看有没有东西打开着这个文件夹或者文件夹里面的东西喔

**Comment by SALTWOOD** [comment]
- 检查一下文件夹的权限
- 删除重装实例
- 确保没有程序占用文件夹

**Comment by CaptLeaf** [comment]
管理员取得所有权试试

**Comment by ZeroWolf233** [comment]
> 我这里不知道为什么也出现这个情况了，文件夹权限按照一楼的issue设置了还是没用，并且版本是由PCL安装的 开了管理员，文件所有权设置everyone和当前账户也不行，不知道因为啥

检查是否有除PCL2外的进程占用着文件，或者强制解除文件占用试试
实在不行的话还有可能小概率是windows的啥子离谱bug我感觉

**Comment by HomoobyDX** [comment]
> > 我这里不知道为什么也出现这个情况了，文件夹权限按照一楼的issue设置了还是没用，并且版本是由PCL安装的 开了管理员，文件所有权设置everyone和当前账户也不行，不知道因为啥
> 
> 检查是否有除PCL2外的进程占用着文件，或者强制解除文件占用试试 实在不行的话还有可能小概率是windows的啥子离谱bug我感觉

这边解决了，问题在于explorer的调度问题（我是inside用户），不过火绒扫出来的占用是explorer.exe是为什么。我有点怀疑楼主的问题和我一样

**Comment by wuliaodexiaoluo** [comment]
>这边解决了，问题在于explorer的调度问题（我是inside用户），不过火绒扫出来的占用是explorer.exe是为什么。我有点怀疑楼主的问题和我一样

通常情况下，这是因为 Explorer 打开了此文件夹或文件夹的子目录

**Comment by Deep-Dark-Forest** [comment]
由于原作者太长时间没有回复，所以关闭此 Issue。

**Comment by RonitYon2112** [comment]
> ### 检查项
> * [x] 我已在[Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+)和[常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930)中搜索，确认了这一 Bug 未被提交过。
> 
> ### 描述
> 我曾给过PCL启动器管理员权限且在检查无误后修改任提示拒绝访问
> 
> ### 重现步骤
> 使用Release2.8.10修改版本名
> 
> ### 日志与附件
> [Log1.txt](https://github.com/user-attachments/files/17783951/Log1.txt) ![新建 PNG 图像](https://github.com/user-attachments/assets/84f54395-003f-4018-a824-724db2c85e4d) ![新建 PNG 图像 (2)](https://github.com/user-attachments/assets/8f6d9406-1b1e-4123-8860-8d6d37fa6116)[Log1.txt](https://github.com/user-attachments/files/17783951/Log1.txt)![新建 PNG 图像](https://github.com/user-attachments/assets/84f54395-003f-4018-a824-724db2c85e4d)![新建 PNG 图像 (2)](https://github.com/user-attachments/assets/8f6d9406-1b1e-4123-8860-8d6d37fa6116)

我遇到了相同的问题，我尝试在任务管理器重启文件资源管理器后问题消失

**Comment by RonitYon2112** [comment]
我遇到了相同问题，解决方法：任务管理器内重启文件资源管理器后问题消失
