### ISSUE TITLE
有关mod下载界面卡片过多导致索引速度大幅下降的3类解决方案建议

### ISSUE THREAD

**Issue by Water-Yuan** [Hex-Dragon/PCL2#5125]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

PCL最近版本更新后mod下载虽然能更方便地看不同加载器的mod了，但是如果我在玩1.16，想下载一个mod就要下滑好久，并且一堆文字也不美观，以下提供几种优化思路：
1.分成竖向的几栏
![QQ20241116-180008](https://github.com/user-attachments/assets/e7207b6d-fe3f-42fe-980c-be010efcded8)
2.卡片内部划分不同加载器成几个板块（横向如下，竖向同理，与1类似）
![QQ20241116-180305](https://github.com/user-attachments/assets/7e710bee-9139-40ab-8c3b-260feaf8971f)
3.(可能会有bug并且需要一定技术力)
在设置中增加一个“自动匹配mod加载器”的选项，开启后在下载界面只分类MC版本号，每个版本至多展示3个mod（Release Beta Alpha）自动合并Forge Neoforge Fabric的mod为同一选项，在用户选择下载时判断目前的版本加载器并下载对应版本

### 原因

这项优化让我可以更方便地下载mod。
如果没有这项优化，我每次都必须翻很久mod列表并把我的眼睛看花，让操作变得很麻烦。

**Comment by Water-Yuan** [comment]
顺便提一嘴，第二种我看到#5074有类似建议，但是因为不同版本的卡片默认折叠，所以可以不用特别在意卡片展开后的大小。
可以分别为三个加载器标上前置，就相当于在现在的版本基础上套一个上级菜单，并默认展开下级菜单

**Comment by wuliaodexiaoluo** [comment]
#5087

**Comment by JingHai-Lingyun** [comment]
MyCard 并排和嵌套会导致 UI 在特殊情况下看起来非常难受，并且并排会在窗口过小时带来麻烦……
上述约定俗成规范可参见 #4483 中部分内容

---

这应当作为 #5087 的解决方案提议，而不是一个新的帖子
故此关闭，你可以将建议整合、优化完之后发送到那边
感谢反馈！
