### ISSUE TITLE
[Bug] 第三方登录退出后直到下次打开启动器前不会再次登录或要求选择角色

### ISSUE THREAD

**Issue by wuliaodexiaoluo** [Hex-Dragon/PCL2#5131]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

https://pan.huang1111.cn/s/oXAGRi8

现在会缓存了，并且直接不登录了（

### 重现步骤

登录然后登出
然后启动游戏，PCL 直接在没登录的情况下用缓存继续了（

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/17788423/Log1.txt)

**Comment by sulingjiang** [comment]
你好像传错日志了?

**Comment by wuliaodexiaoluo** [comment]
[Log1.txt](https://github.com/user-attachments/files/17789639/Log1.txt)

这个问题同样是调试开源版本出现的（（（
