### ISSUE TITLE
在模组下载/管理页面标注模组类型（仅客户端/仅服务端/客户端和服务端）

### ISSUE THREAD

**Issue by lonelyicer** [Hex-Dragon/PCL2#5134]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

![image](https://github.com/user-attachments/assets/c3af6eb8-1e86-47eb-bdca-ed11bb9f7b00)

### 原因

筛选仅客户端模组，让制作整合包服务端更加方便。

**Comment by tangge233** [comment]
似乎 Modrinth 的 API 里只在[搜索](https://docs.modrinth.com/api/operations/searchprojects/#query-parameters)那有相关字段，其它地方没有返回此类信息？

**Comment by lonelyicer** [comment]
Modrinth的API在返回Project的详细信息的时候会返回server_side和client_side的支持状态，分别为`required`，`optional`，`unsupported`，`unknown`

**Comment by lonelyicer** [comment]
例如这样 https://[api.modrinth.com/v2/project/create](https://api.modrinth.com/v2/project/create)
```
{
    "client_side": "required",
    "server_side": "required",
    "game_versions": [
        "1.18.2",
        "1.19.2",
        "1.20.1"
    ],
    "id": "LNytGWDc",
    "slug": "create",
    "project_type": "mod"
}
```

**Comment by youzi-3222** [comment]
无论搜索 `/search` 还是获取详细信息 `/project` 都有该字段。

```jsonc
// https://api.modrinth.com/v2/project/P7dR8mSH
{
  "client_side": "optional",
  "server_side": "optional"
  // ...
}
```

```jsonc
// https://api.modrinth.com/v2/search?gravestones=Fabric
/*   1 */   {
                 // ...
/* 305 */        "client_side": "optional",
/* 306 */        "server_side": "optional",
                 // ...
            }
```

**Comment by allMagicNB** [comment]
那么如果有区别的话。
- #2863
- #3039
- #4336
这些是怎么重的？

**Comment by LTCatt** [comment]
……既然有这么多人提了那挂个投票吧

**Comment by LTCatt** [comment]
Reopen #2467
