### ISSUE TITLE
版本内mod下载界面跳转异常

### ISSUE THREAD

**Issue by Frepidation** [Hex-Dragon/PCL2#5138]
### 检查项

- [x] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [ ] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在版本设置内的mod管理里跳转下载界面后，选择在文件夹列表中没有的加载器和游戏版本的mod下载（该mod的加载器要与当前选择的加载器一致），会跳转到当前选择的版本的mod文件夹里。

### 重现步骤

1，先选择一个可以下载mod的版本，下载一个mod（用“Sodium”做演示）
2，在登录界面点版本设置
3，点mod管理
4，找到模组钠右键跳转至下载界面
5，选择在文件夹列表中没有的加载器和游戏版本的mod下载（该mod的加载器要与当前选择的加载器一致）
6，下载界面会跳转到\.minecraft\versions\（游戏版本）\mods而不是\.minecraft中，还有概率跳转到其他版本的mods文件夹（反正就是对不上）

### 日志与附件

[Log2.txt](https://github.com/user-attachments/files/17792587/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17792588/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17792589/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17792590/Log5.txt)
[Log.txt](https://github.com/user-attachments/files/17792583/Log.txt)
[Log1.txt](https://github.com/user-attachments/files/17792585/Log1.txt)

**Comment by wuliaodexiaoluo** [comment]
麻烦提供下版本隔离设置

**Comment by Frepidation** [comment]
![1](https://github.com/user-attachments/assets/4738a6f7-76bc-4d07-b29c-51bcbd47b1a6)
隔离所有版本

**Comment by allMagicNB** [comment]
那你预期中该跳到哪？为什么要跳到 .minecraft 文件夹？

**Comment by Frepidation** [comment]
比如我选择的1.20.6的mod，结果跳转到了1.20.1的mods文件夹，这是非常不正确的。我认为应该跳转到.minecraft文件夹而不是1.20.1的mods文件夹，这非常容易误导新手下错版本而导致不必要的麻烦......

**Comment by allMagicNB** [comment]
你知不知道 Forge 的小版本兼容机制？

**Comment by Frepidation** [comment]
> 你知不知道 Forge 的小版本兼容机制？

知道，但是有些mod的小版本并不兼容，比如1.20.1和1.20.6的mod。况且织物装载器和forge某些情况下小版本是混杂再一起的，非常容易弄混，既然存在，就要防止新手出错而导致不必要的麻烦......

**Comment by allMagicNB** [comment]
#691

**Comment by Frepidation** [comment]
> #691但是在这个版本中直接去下载mod并不会出现这类问题，（本人暂时发现，有误请海涵）只有上诉操作回导致此类问题出现，所以我认为是不是创作者修复的时候未修复完全......

**Comment by Frepidation** [comment]
> * [自动选择 Mod 下载文件夹时忽略了 MC 的最小版本 #691](https://github.com/Hex-Dragon/PCL2/issues/691)

感谢您的提醒

**Comment by wuliaodexiaoluo** [comment]
>我认为应该跳转到.minecraft文件夹而不是1.20.1的mods文件夹

虽然我认为这段逻辑可能有点问题，但是直接跳转到 .minecraft 文件夹并非最佳做法
因为 Minecraft 没有官方的开发文档（实际上官方也不可能提供这个东西），也没有任何规范有要求版本文件夹名、显示名称必须和游戏实际版本相同，所以实际上**任何名称**都是可以被接受的，即使这和实际版本没有任何关联，比起跳转错误，我认为这个更可能导致普通用户操作失误（（（
