### ISSUE TITLE
默认的版本隔离选项

### ISSUE THREAD

**Issue by SmallFox0305** [Hex-Dragon/PCL2#5151]
### 检查项

- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

将 设置-游戏-启动选项-版本隔离这一选项的默认值改成 “隔离所有版本”

### 原因

这项优化可以对新用户更友好。
如果没有这项优化， 会让很多第一次使用的玩家发出疑问 因为他们并不知道此功能 如果默认不隔离 当用户下载多个游戏版本时 所有游戏文件会堆到一起 导致存档、mod等重复或冲突 所以在此提出建议 将版本隔离默认值设为隔离所有版本 谢谢

**Comment by shimoranla** [comment]
#2375
