### ISSUE TITLE
启动不了2.0和无限

### ISSUE THREAD

**Issue by xjzmz** [Hex-Dragon/PCL2#5155]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃基本不是 PCL 的原因，请 **不要** 提交反馈。你可以在论坛或社区找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用 HMCL 启动，HMCL 没有出现问题。** 如果 HMCL 也无法启动就不是 PCL 导致的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

2.0和无限进不去

### PCL 错误报告、日志与附件

[Log.txt](https://github.com/user-attachments/files/17845198/Log.txt)

### HMCL 启动脚本

[Log1.txt](https://github.com/user-attachments/files/17845202/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17845206/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17845207/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17845209/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17845210/Log5.txt)

**Comment by shimoranla** [comment]
你提供的日志并非有效的 HMCL 启动脚本和崩溃报告
如果你仍然需要社区提供支持，请上传你的崩溃报告

**Comment by allMagicNB** [comment]
关了，网太差导致的。

**Comment by Deep-Dark-Forest** [comment]
由于原作者太长时间没有回复，所以关闭此 Issue。
