### ISSUE TITLE
离线皮肤支持1.19.2以上的版本

### ISSUE THREAD

**Issue by yuanbao-ctrl** [Hex-Dragon/PCL2#5158]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

我没有描述

### 原因

我不想在1.19.2以上的版本使用原版皮肤了，感觉原版皮肤很难看

**Comment by Ad-closeNN** [comment]
- https://github.com/Hex-Dragon/PCL2/issues/1288 (https://github.com/Hex-Dragon/PCL2/discussions/1596)
