### ISSUE TITLE
支持下载地图

### ISSUE THREAD

**Issue by yuanbao-ctrl** [Hex-Dragon/PCL2#5159]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

支持下载地图

### 原因

我需要这个功能来下载地图。很多人都有下载地图的需求，但如果没有这个功能，就不能下载地图了。

**Comment by wyc-26** [comment]
真有你的，35 分钟发了 3 个 Issue，还全是重复的

**Comment by Ad-closeNN** [comment]
- https://github.com/Hex-Dragon/PCL2/issues/44 https://github.com/Hex-Dragon/PCL2/issues/135

*存在语言问题，不会制作。*

---

另外，请在反馈前去 #1930 进行查重和
![image](https://github.com/user-attachments/assets/1fb1afce-82d4-4260-910e-84012876f4b1)
查重而不是发送重复 issue
