### ISSUE TITLE
支持自动解锁赞助者功能

### ISSUE THREAD

**Issue by baguotao233** [Hex-Dragon/PCL2#5160]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

PCL2的快照版挺好，可以抢先体验新功能，解锁皮肤等等功能·······
但是当用户更换电脑或者重装系统，你需要重新到爱发电获取更新码，23.33用户还要再额外获取一次解锁码
所以希望PCL2可以支持通过已经绑定过的正版MC（可以根据UUID确定是哪个账号）的用户自动解锁快照版功能，一定程度上可以防止共享/贩卖PCL2快照版权益，如果这个提案不好实现，也可以把更新码和解锁码合二为一，用户输入后就可以直接解锁全部功能

### 原因

（示例）
我需要这个功能来方便赞助者快捷解锁权益。很多人应该都需要这个需求，但如果没有这个功能，解锁快照版会十分麻烦且会出现PCL2权益被共享OR贩卖，并且解锁快照版你需要输入2次解锁码（包含23.33档的额外一次）

**Comment by wyc-26** [comment]
问题就是不是所有人都有正版账号啊（

**Comment by wyc-26** [comment]
更新码和解锁码是两种不同的概念 合并不了一点
再说那个啥隐藏主题也是通过解锁码解锁的

**Comment by tangge233** [comment]
>PCL2可以支持通过已经绑定过的正版MC（可以根据UUID确定是哪个账号）的用户自动解锁快照版功能

可能涉及云服务，大概率不会做……

>当用户更换电脑或者重装系统，你需要重新到爱发电获取更新码

重装系统可以通过备份和恢复注册表来解决重置问题

至于更换电脑的情况……听听龙猫怎么说……

**Comment by allMagicNB** [comment]
我认为，同一个微软账户可以在多台设备上的 PCL 登录。

**Comment by baguotao233** [comment]
> 我认为，同一个微软账户可以在多台设备上的 PCL 登录。

你考虑过一种问题吗？出借微软账号会导致其他人开挂骂人，导致账号被服务器ban掉或被mojang禁言，号主不清楚这一点吗？

**Comment by baguotao233** [comment]
> 问题就是不是所有人都有正版账号啊（

绑定一个外置账号不也是可以的 比如littleskin？

**Comment by baguotao233** [comment]
> 更新码和解锁码是两种不同的概念 合并不了一点 再说那个啥隐藏主题也是通过解锁码解锁的 EDIT：赞助 ¥12.34 的有更新码但没有解锁码 ![IMG_6547](https://private-user-images.githubusercontent.com/154735436/388936801-c847ba0d-687b-49f8-b9fe-600fd23cb16e.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyODQ4MDAsIm5iZiI6MTczMjI4NDUwMCwicGF0aCI6Ii8xNTQ3MzU0MzYvMzg4OTM2ODAxLWM4NDdiYTBkLTY4N2ItNDlmOC1iOWZlLTYwMGZkMjNjYjE2ZS5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjJUMTQwODIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjRmZGQwODY0NzhiOTdjZWIxMGEyY2MyNmY4NmNjMGRiODk3N2NkNjY4OTZkYzIxZDU3ZGQyNjdmNzZlZTk4YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Qhc7qCFQUHcqoHpTloilPrgm63ieNFrm8F_w9iZthyE)

这里特指的就是23.33档的用户，就不能认真看完issues吗..........

**Comment by baguotao233** [comment]
> > PCL2可以支持通过已经绑定过的正版MC（可以根据UUID确定是哪个账号）的用户自动解锁快照版功能
> 
> 可能涉及云服务，大概率不会做……
> 
> > 当用户更换电脑或者重装系统，你需要重新到爱发电获取更新码
> 
> 重装系统可以通过备份和恢复注册表来解决重置问题
> 
> 至于更换电脑的情况……听听龙猫怎么说……

如果说PCL2加一个注册表备份功能也是可以的，不然普通电脑小白哪里会备份（

**Comment by tangge233** [comment]
> 如果说PCL2加一个注册表备份功能也是可以的，不然普通电脑小白哪里会备份（

你可以在 帮助库 → 启动器 → 备份启动器设置 中使用“备份注册表”和“恢复注册表功能”
未来的版本会支持在设置页面中便捷地进行设置的导入导出 Orz

**Comment by wyc-26** [comment]
> > 更新码和解锁码是两种不同的概念 合并不了一点 再说那个啥隐藏主题也是通过解锁码解锁的 EDIT：赞助 ¥12.34 的有更新码但没有解锁码 ![IMG_6547](https://private-user-images.githubusercontent.com/154735436/388936801-c847ba0d-687b-49f8-b9fe-600fd23cb16e.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyODQ4MDAsIm5iZiI6MTczMjI4NDUwMCwicGF0aCI6Ii8xNTQ3MzU0MzYvMzg4OTM2ODAxLWM4NDdiYTBkLTY4N2ItNDlmOC1iOWZlLTYwMGZkMjNjYjE2ZS5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjJUMTQwODIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjRmZGQwODY0NzhiOTdjZWIxMGEyY2MyNmY4NmNjMGRiODk3N2NkNjY4OTZkYzIxZDU3ZGQyNjdmNzZlZTk4YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Qhc7qCFQUHcqoHpTloilPrgm63ieNFrm8F_w9iZthyE)
> 
> 这里特指的就是23.33档的用户，就不能认真看完issues吗..........

看完了，看不出来我那整段话的意思就是我反对合并两个码吗

**Comment by Deep-Dark-Forest** [comment]
> > 我认为，同一个微软账户可以在多台设备上的 PCL 登录。
> 
> 你考虑过一种问题吗？出借微软账号会导致其他人开挂骂人，导致账号被服务器ban掉或被mojang禁言，号主不清楚这一点吗？

你考虑过一种问题吗？如果我不出借，有两个电脑怎么办？

**Comment by baguotao233** [comment]
> > > 我认为，同一个微软账户可以在多台设备上的 PCL 登录。
> > 
> > 
> > 你考虑过一种问题吗？出借微软账号会导致其他人开挂骂人，导致账号被服务器ban掉或被mojang禁言，号主不清楚这一点吗？
> 
> 你考虑过一种问题吗？如果我不出借，有两个电脑怎么办？

我也没说是要限制单设备吧，只是能够减少非法出借的概率

**Comment by JingHai-Lingyun** [comment]
请坐和放宽。

#### 以下是我的个人意见

🟫 不对 合并解锁码和识别码 做评价
 -   可能会带来实现的麻烦，也可能会改进现有的操作逻辑

🟥 不赞同 将 PCL 敏感数据与微软账户绑定
 - 正如其他朋友所述：微软账户登录不可控 - 你无法确认是同一个人登录了多台设备；
       还是一个特别的账户在人群中传递，专门用来解锁赞助功能；抑或是其他的情况
 - 这个提议实现起来难度很大

**Comment by Pigeon0v0** [comment]
#315
