### ISSUE TITLE
打开PCL添加对小白的提示

### ISSUE THREAD

**Issue by Frepidation** [Hex-Dragon/PCL2#5163]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

用显眼的字在初次开启pcl时候写出注意事项？

### 原因

遇到过好多小白，将 PCL 放在 C 盘、我的文档或桌面......还有的直接扔到download里面（我红温了）。或许因该提示他们不能放在这个地方？（有类似的别喷我...我没找到）（-__-）

**Comment by Ad-closeNN** [comment]
放在 C 盘...或许有的人只有 C 盘呢...

剩下的文件夹...影响不大吧？

**Comment by tangge233** [comment]
PCL 目前只会在临时目录下提示用户存放的位置不正常……没放在其它位置已经很好了，对小白用户要求别太高，能跑就行（）

**Comment by Pigeon0v0** [comment]
理论上不影响使用都可以...

**Comment by LTCatt** [comment]
如果因为放这些地方影响使用了 PCL 会提示……
可以加个放桌面的提示（

**Comment by Hill23333** [comment]
![image](https://github.com/user-attachments/assets/a6c79461-234e-480f-8a79-5bf9a741dd85)
这个样子如何？提示语可以怎么改？

**Comment by ZeroWolf233** [comment]
> ![image](https://private-user-images.githubusercontent.com/104297546/389192658-a6c79461-234e-480f-8a79-5bf9a741dd85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1NDgxODUsIm5iZiI6MTczMjU0Nzg4NSwicGF0aCI6Ii8xMDQyOTc1NDYvMzg5MTkyNjU4LWE2Yzc5NDYxLTIzNGUtNDgwZi04YTc5LTViZjlhNzQxZGQ4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNVQxNTE4MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZmM4NDg4ZmZmYmU2ODNhYjNmYTZmYmRmMWFkODkzMjE5YmE1NDBjODA5ZjBjNDVkNGE0Y2Y5ZmY2MjAxNjU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2gOhqz3oyinwpTd_8xUC6EXIXRJn1AkgiPNiVjZ48EQ) 这个样子如何？提示语可以怎么改？

我倒是觉得可以再加一个不要把pcl2放下载文件夹里，小白一般都不知道下载文件夹在哪，可能下次就找不到pcl2了，可以在启动时判断是否在下载文件夹中(判断当前所在文件夹是否含有`download`, `下载`等词汇)，有的话就也弹出类似的提示不要把pcl2放在下载文件夹中

**Comment by LTCatt** [comment]
我觉得检查下载文件夹就没啥必要了……这个也不影响使用，并且确实会有人喜欢原地用……

**Comment by ZeroWolf233** [comment]
> 我觉得检查下载文件夹就没啥必要了……这个也不影响使用，并且确实会有人喜欢原地用……

emm，就是担心小白找不到，或许可以添加个下次不再提醒啥的(?

**Comment by LTCatt** [comment]
不太打算考虑，这个确实可以是正常行为。在第一次打开软件时弹一堆窗口提示也挺烦人的……

**Comment by LTCatt** [comment]
重新考虑了一下，对桌面添加提示也不太合适。
一方面，这不会影响实际的使用（如果没有权限会触发 `ModSecret.SecretOnApplicationStart` 中的环境检查提示）。
另一方面，对于这部分电脑小白，让他们把 PCL 挪到另一个地方并且建一个快捷方式，是比较复杂的一个操作。与其相对的，就放在桌面也没有啥影响……
所以还是算了……
