### ISSUE TITLE
建议给更新mod加一个忽略选项

### ISSUE THREAD

**Issue by li654300306** [Hex-Dragon/PCL2#5164]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

建议给更新mod加一个忽略选项

### 原因

（示例）
我需要这个功能来xxxx。很多人都有xxxx的需求，但如果没有这个功能，就不能xxxx了。
因为偶尔会把出问题的mod更新。比如当前版本不能用我可以选择忽略，

**Comment by hejiehao** [comment]
https://github.com/Hex-Dragon/PCL2/issues/3901
