### ISSUE TITLE
CurseForge 上有的模组 PCL 无法检测到其指定版本

### ISSUE THREAD

**Issue by JingHai-Lingyun** [Hex-Dragon/PCL2#5165]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

Resourceful Lib 没有 1.21 Fabric 版本（CF 源），但是在 CurseForge 上存在

### 重现步骤

搜索 1.21 Fabric Resourceful Lib
观察页面

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/17878417/Log1.txt)

**Comment by JingHai-Lingyun** [comment]
不对…… 这东西在 PCL 里找不到 1.21……
但是 [CurseForge 上](https://www.curseforge.com/minecraft/mc-mods/resourceful-lib)是有的……

**Comment by xxtg666** [comment]
![image](https://github.com/user-attachments/assets/dbb074a2-f53b-40fc-8ffc-f215f51e0d47)
（？

**Comment by JingHai-Lingyun** [comment]
……？缓存导致的吗……
