### ISSUE TITLE
启动器启动图片自定义

### ISSUE THREAD

**Issue by Cheesems** [Hex-Dragon/PCL2#5166]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

![image](https://github.com/user-attachments/assets/3936f26b-8b52-4f7d-90dc-9282d9177d31)
如题 启动PCL2时的启动图标自定义

### 原因

-好看(划  -可以给整合包制作者用 或者只开放资助用户  -增加自定义的空间

**Comment by shimoranla** [comment]
>-好看(划 -可以给整合包制作者用 或者只开放资助用户 -增加自定义的空间

显然这不大可能，如果图片本身就有问题应该会导致启动器无法启动（

btw： GitHub Markdown 允许使用 ~ 或 <del>文本</del> 来给文字加删除线

**Comment by hejiehao** [comment]
和 #791 类似
