### ISSUE TITLE
fabric

### ISSUE THREAD

**Issue by StrongerOwl9864** [Hex-Dragon/PCL2#5167]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

可以更新原minecraft的fabric版本。

### 原因

主要是因为fabric经常会出现fabric版本与模组不兼容的问题，但又不想再下载一个minecraft版本，所以希望可以直接替换原minecraft上的fabric。

**Comment by xinyihl** [comment]
#227 #220

**Comment by shimoranla** [comment]
你可以前往 #227 投票
