### ISSUE TITLE
导入整合包功能希望能允许不强制版本隔离

### ISSUE THREAD

**Issue by Jaanai-AAM** [Hex-Dragon/PCL2#5170]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [x] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

我更习惯每个包单开一个目录，然后从不开版本隔离，但是遇到导入整合包就只能被迫版本隔离，希望能给个设置，能够让导入的整合包变成非版本隔离的样式

### 原因

这项优化让我可以更方便地管理整合包的各种文件。
如果没有这项优化，我每次都必须多点几下进入versions里管理mod等文件，或者手动一个一个移动并且改成非版本隔离，让操作变得很麻烦。

**Comment by Pigeon0v0** [comment]
如有不适 尽快适应.jpg

**Comment by Pigeon0v0** [comment]
不对 版本独立设置里可以改回来的吧？（

**Comment by LTCatt** [comment]
整合包一般不考虑不隔离……抱歉（
