### ISSUE TITLE
模组不兼容后，pcl2报错乱码

### ISSUE THREAD

**Issue by wwwrow** [Hex-Dragon/PCL2#5171]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![报错](https://github.com/user-attachments/assets/34cf13d3-6a33-4ad5-a6ef-1f0d253abbfc)
1.fabric报错正常
2.点击退出后pcl2报错乱码
![报错pcl](https://github.com/user-attachments/assets/9205f319-1ad8-4104-b228-c9bde5524a2e)

### 重现步骤

找如图的mod(其他不兼容mod装在一起会不会没试过），装好后启动游戏，发现出现报错，在fabric的窗口点击退出，pcl2中的报错乱码，但是打开报错的txt文件后一切正常

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/17879904/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17879905/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17879906/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17879907/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17879908/Log5.txt)

**Comment by shimoranla** [comment]
感觉是 #4700 ?

**Comment by Louis-Harsune** [comment]
@wwwrow 请求导出的游戏错误报告，我需要对比原始log的编码格式和字节

**Comment by HomoobyDX** [comment]
应该是编码出现问题，这边建议先把错误报告传上来方便查看

**Comment by dannisyang53** [comment]
我这边也出现了类似的问题：
- Fabric 的报错信息
![屏幕截图 - Fabric](https://github.com/user-attachments/assets/c23ef9cc-84b1-4c36-bc2c-9e14c2f4ab02)
- PCL 的乱码弹窗
![屏幕截图 - PCL2](https://github.com/user-attachments/assets/84436e79-5a25-4f1a-a6eb-6fdadc681ecb)
一堆问号推测应该是用`utf-8`编码读取`gbk`编码造成的
- 导出的错误报告
[错误报告.zip](https://github.com/user-attachments/files/17976319/-2024-12-2_18.05.48.zip)
- 启动器日志
[Log1.txt](https://github.com/user-attachments/files/17976333/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17976336/Log2.txt)

**Comment by lactobionicAcid** [comment]
PCL 在读取除崩溃日志以外的 .log 文件时强制采用了 UTF-8 编码……🤔
<details>

https://github.com/Hex-Dragon/PCL2/blob/37561a842b432efcc5ce6c9edea93cfed5dd55f2/Plain%20Craft%20Launcher%202/Modules/Minecraft/ModCrash.vb#L86-L92

https://github.com/Hex-Dragon/PCL2/blob/37561a842b432efcc5ce6c9edea93cfed5dd55f2/Plain%20Craft%20Launcher%202/Modules/Minecraft/ModCrash.vb#L133-L138

</details>

**Comment by allMagicNB** [comment]
- #4482

**Comment by shimoranla** [comment]
> * [导出崩溃报告中的 “游戏崩溃前的输出.txt” 可能乱码 #4482](https://github.com/Hex-Dragon/PCL2/issues/4482)

反馈者使用的版本为 Snapshot 2.8.10
你所引用的 Issue 已经在 2.8.4 被修掉了（

**Comment by LTCatt** [comment]
同 https://github.com/Hex-Dragon/PCL2/issues/4700#issuecomment-2454569550
由于 MC 崩溃报告经常包含两种不同的编码，以任何一个编码读取都会导致另一部分内容乱码，所以无法处理。

**Comment by allMagicNB** [comment]
> 同 https://github.com/Hex-Dragon/PCL2/issues/4700#issuecomment-2454569550
> 由于 MC 崩溃报告经常包含两种不同的编码，以任何一个编码读取都会导致另一部分内容乱码，所以无法处理。

那么为什么其他人的错误报告中 `游戏崩溃前的输出.txt` 是乱码的？

**Comment by wwwrow** [comment]
我现在也不方便提供，可能等周末



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年12月04日 21:02 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Hex-Dragon/PCL2] 模组不兼容后，pcl2报错乱码 (Issue #5171) |

同 #4700 (comment)
由于 MC 崩溃报告经常包含两种不同的编码，以任何一个编码读取都会导致另一部分内容乱码，所以无法处理。

那么为什么其他人的错误报告中 游戏崩溃前的输出.txt 是乱码的？

**Comment by shimoranla** [comment]
换一种思路，既然 Fabric 可以自主给出中文的崩溃原因，那么 PCL 的弹窗其实没啥大用处
也就是这个东西可修可不修

**Comment by HomoobyDX** [comment]
据HMCL统计，fabric即使提供了中文崩溃原因还是有人不看，只看启动器的分析原因

**Comment by wwwrow** [comment]
[Uploading 错误报告-2024-12-6_18.00.29.zip…]()

**Comment by wwwrow** [comment]
[错误报告-2024-12-6_18.00.29.zip](https://github.com/user-attachments/files/18036410/-2024-12-6_18.00.29.zip)
所以是不能修了吗？

**Comment by LTCatt** [comment]
抱歉，这个确实没想出来啥好办法……
