### ISSUE TITLE
1.20.1mod界面forge与neoforge合并

### ISSUE THREAD

**Issue by zzz1123456** [Hex-Dragon/PCL2#5175]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

当版本选择1.20.1时选择forge或neoforge同时列出两个版本

### 原因

1.20.1的forge与neoforge几乎无差别，但是一些mod没有同时标注这种加载器，导致了1.20.1搜索mod极不方便，此项功能有助于1.20.1的模组搜索

**Comment by shimoranla** [comment]
>1.20.1的forge与neoforge几乎无差别，但是一些mod没有同时标注这种加载器，导致了1.20.1搜索mod极不方便，此项功能有助于1.20.1的模组搜索

wai，这好像会被当 Bug 的说

**Comment by LTCatt** [comment]
和 #5087 一起寻思吧
