### ISSUE TITLE
无法删除主页的下载地址（可能是bug吧）

### ISSUE THREAD

**Issue by newbeflash** [Hex-Dragon/PCL2#5182]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在主页选择联网更新后输入无法下载的地址，他会删不掉（貌似是bug吧,不是或者有相似的别骂我-_-）

### 重现步骤

> 点击设置
点击个性化
找到主页，点击联网更新
在下载地址输入无法正常获取下载的地址（比如https://gitee.com/my_com_cn/pcl_homepage/raw/master/Custom.xaml）
然后全选删除
之后顶部按钮“启动”“下载”“更多”等按钮随便点一个在切回来
然后发现没删掉（可能是bug？）

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/17904784/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17904785/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17904787/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17904788/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17904789/Log5.txt)
[Log.txt](https://github.com/user-attachments/files/17904790/Log.txt)

**Comment by newbeflash** [comment]
> 没有任何使用场景需要把这个删空吧……

但是不是留空 = 不更改吗？（感觉本来空的但是输入了之后没法清掉好难过。。）

**Comment by newbeflash** [comment]
请问可以要个活跃橙吗？谢谢啦QAQ（识别码:6155-A592-D7D4-4665）

> 唉，行吧……

**Comment by LTCatt** [comment]
你的解锁码：NVazFVxqmR+agD/dxTBWDEKBF5w2+XoM
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
