### ISSUE TITLE
支持获取mcpedl中的mod

### ISSUE THREAD

**Issue by Orangesmart** [Hex-Dragon/PCL2#5185]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

在搜索mod中，加入mcpedl的mod的内容

### 原因

这个功能可以获取更多mod

**Comment by tangge233** [comment]
暂时没有发现重复 Issue

但从寻找到的有关于基岩版内容的 Issue 来看，大概率不会考虑加入与基岩版有关的内容……

**Comment by SALTWOOD** [comment]
不会考虑与基岩版本相关的功能，好像

**Comment by LTCatt** [comment]
不考虑基岩版，抱歉
