### ISSUE TITLE
崩溃Mod高亮显示

### ISSUE THREAD

**Issue by GOhaochen** [Hex-Dragon/PCL2#5188]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

你还在为加了一堆Mod然后大面积崩溃而烦恼吗？
还在为对着崩溃日志抄写Mod名而崩溃吗？

快快让龙猫添加这个功能吧！、

在启动器已经明确了解是哪个/哪些Mod引发的崩溃时自动跳转到该版本的Mod列表，并将问题Mod高亮显示，让玩家一眼找到问题所在

### 原因

帮助玩家快速找到引发崩溃的Mod，提高玩家使用启动器的效率

**Comment by Hill23333** [comment]
#277 
#3327 
#3817 
#4390

**Comment by shimoranla** [comment]
>还在为对着崩溃日志抄写Mod名而崩溃吗？

请善用导出日志和 Ctrl+C Ctrl+V

>快快让龙猫添加这个功能吧！

~龙猫: Refused~

>在启动器已经明确了解是哪个/哪些Mod引发的崩溃时自动跳转到该版本的Mod列表，并将问题Mod高亮显示，让玩家一眼找到问题所在

识别结果: Mod net.optifine 引发了崩溃
事实上 Mod 引发的崩溃并不一定会显示实际名称，更多的是 net.xxx io.xxx com.xxx 这样的类名

**Comment by Pigeon0v0** [comment]
感觉不太可能做

**Comment by LTCatt** [comment]
事实：PCL 并不知道是准确的哪个 mod，这个 mod 文件名是从崩溃报告找出来的，而不是读的 mods 文件夹，并且经常错（
……主要是分析出来的也经常错
