### ISSUE TITLE
点击mod更新图标时，左键查看更新日志，右键更新

### ISSUE THREAD

**Issue by Lmy1503** [Hex-Dragon/PCL2#5189]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

现在pcl检测mod更新时基本只会检测一端（modrinth或是courseforge）可更新的mod，但是有时候mod更新只在一端，能不能再检测mod更新时候两个平台都检测一下

### 原因

我需要这个功能，尤其是再制作整合包更新的时候。

**Comment by LTCatt** [comment]
会检测两端的啊？如果哪个 mod 没检测到请具体指出（

**Comment by Lmy1503** [comment]
破案了，pcl里检测的最新mod和我用courseforge检测到的新版本不一样导致的，pcl里检测到的是modrinth最新版
![1](https://github.com/user-attachments/assets/49c5c704-d028-44e0-9ea6-f2dfe217dbbd)
![3](https://github.com/user-attachments/assets/5f6310af-935a-4a76-acd5-0866186198ec)

**Comment by Lmy1503** [comment]
破案了，pcl里检测的最新mod和我用courseforge检测到的新版本不一样导致的，pcl里检测到的是modrinth最新版
![1](https://github.com/user-attachments/assets/fc60bd65-1f26-4ea7-bc63-5b407d4e6752)
![3](https://github.com/user-attachments/assets/fa80eff2-4070-4e8c-98c6-fb87ea7712e5)

**Comment by JingHai-Lingyun** [comment]
双端都会检测，所以有时候 CurseForge 下到最新的还能更新，这是正常的

题外话
在 Mod 更新 Tooltip 里有标注么话说

**Comment by Lmy1503** [comment]
有的 ，可以直接看到mod版本的更新时间（右键查看更新信息），之前都没注意有这个功能，要不那个更新提示符号做个另外的颜色表示，不是很明显，而且这个位置在选mod的时候很容易误点

**Comment by LTCatt** [comment]
要不然改成左键查看更新日志，右键更新？

**Comment by JingHai-Lingyun** [comment]
可以，左键出来个变更内容详细的弹窗 + 问要不要更新，右键就跳过弹窗直接更新掉好了

**Comment by Lmy1503** [comment]
我觉得可以改成第一下点击就是选中mod，第二下再点击才会更新，有一个操作逻辑，防止手贱单点直接更新。这种可更新mod要选中才能点击更新。然后那个更新标志可以换个颜色，因为有点不明显，要是变成橙红色或是实心标志就好了

**Comment by LTCatt** [comment]
因为更新 mod 并不是推荐操作（不少情况下更新后反而会爆炸，然后普通玩家搞不懂），所以不会加强更新提示。
先改成左键查看更新日志，右键更新看看情况。

**Comment by Lmy1503** [comment]
赞同

**Comment by LTCatt** [comment]
umm 感觉这样对已经习惯了操作的用户而言也并不友好，还是左键更新右键查看日志吧，不过加了个更新前的确认弹窗……
![image](https://github.com/user-attachments/assets/1c5beed5-94d7-4762-80a4-eedfd17a8159)
