### ISSUE TITLE
支持Debug模式显示log1内容

### ISSUE THREAD

**Issue by Joker2184** [Hex-Dragon/PCL2#5192]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

启动PCL后实时显示Log1内容

### 原因

不想天天点log1查看检查源
同时使调试模式真正干到应该显示的东西而不是就一个登录部分（

~~能让显得PCL很酷（bushi~~

**Comment by shimoranla** [comment]
>同时使调试模式真正干到应该显示的东西而不是就一个登录部分（

Memoeies Used/Max Memories: 1.87G/2.0G

显然如果要整... 
起码要支持终端输出...
直接打印一些内容也容易一滑滑不到低

**Comment by SALTWOOD** [comment]
没必要。这样就需要引入一些新的功能，比如说控制台什么的，就需要特别写新代码。
以及，有如此详细的日志记录已经很不错了，
1. 随便找一个软件打开文本文件效果应该都会比在启动器内看更好吧？
2. 启动器里头看的话半天滑不到底，而且还可能因为 WPF 的一些固有特性炸掉

**Comment by Joker2184** [comment]
> * 个软件打开文本文件效果应该都会比在启动器内看更好吧？
> * 启动器里头看的话半天滑不到底，而且还可能因为 WPF 的一
回一下第一个
主要就不想打开（ 你需要点到PCL文件夹 再打开log1..... 如果临时还好 一直需要打开就烦了（

做新主页测个几十次挺难受的（ 有时候还会爆点反诈的东西出来（ 直接在启动器看不需要一直点点点了

**Comment by LTCatt** [comment]
会非常、非常卡。
WPF 的文字性能非常抽象。

**Comment by Joker2184** [comment]
o~
行...
