### ISSUE TITLE
当导入镜像源还未更新的版本的整合时，会导致游戏安装失败。

### ISSUE THREAD

**Issue by tucaoba2333** [Hex-Dragon/PCL2#5195]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 当导入镜像源还未更新的版本的整合时，会导致游戏安装失败。

> 游戏安装失败
> → 下载原版 1.21.4-rc2失败
> → 获取原版 json 文件下载地址失败
> → 无对应的 json 下载地址
>    at PCL.ModDownload.DlSourceLauncherOrMetaGet(String Original)
>    at PCL.ModDownloadLib._Closure$__5-0._Lambda$__0(LoaderTask`2 Task)
>    at PCL.ModLoader.LoaderTask`2._Closure$__13-0._Lambda$__0()

除非在 设置-启动器-下载-版本列表源中选择“仅在官方源加载缓慢时使用镜像源”或者“尽量使用官方源” 时，可以正确下载安装整合包。
由于该Bug时效性强，可能难以复现。

### 重现步骤

时间 2024/11/30 01:10:01 P.M.
1.确保 设置-启动器-下载-版本列表源 的选项为 “尽量使用镜像源”。
2.导入一个1.21.4 - Realease Candidate 2 并安装了Fabric Loader的整合包（MultiMC/Modrinth格式）。
3.游戏安装失败。

### 日志与附件

[Log2.txt](https://github.com/user-attachments/files/17961954/Log2.txt)

![89dc4e489bb72c1df1c9ea7b98c809f9](https://github.com/user-attachments/assets/3fb6304d-4c9f-4662-b0e7-b6de316ee416)

**Comment by tucaoba2333** [comment]
我认为最好还是做个fallback，不然可能会导致小白遇到~~令人困惑的事情~~
但是我并没有使用HMCL或者BakaXL测试；我平时使用Prism Launcher和ATLauncher，他们不可能遇到这类问题因为他们压根就不从镜像获取。
所以这可以被认为是镜像源更新太慢的问题，还是PCL的问题？

**Comment by Tianpao512** [comment]
可能是镜像源的问题 镜像源每天3点更新一次好像

**Comment by shimoranla** [comment]
基于 #5215 
建议给 ModLoader 和类似组件都加个 Fallback

**Comment by tucaoba2333** [comment]
要个主题x
2E97-14C7-5DC8-23C3

**Comment by LTCatt** [comment]
你的解锁码：w4UjMbRKvDNG4eOmVSFLUWGz8Ihhu/3q
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by Lunar-525** [comment]
> 你的解锁码：w4UjMbRKvDNG4eOmVSFLUWGz8Ihhu/3q 在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

我更换了电脑 麻烦重新下发一下主题：28DB-7BD5-DD4B-4A0F

**Comment by LTCatt** [comment]
你的解锁码：vrr1TVfkuj0Gk8aepTksE+dUJBDbhs32
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
