### ISSUE TITLE
自定义主页可以播放音乐

### ISSUE THREAD

**Issue by llsgllsg** [Hex-Dragon/PCL2#5197]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

自定义主页可以控制播放PCL文件夹中的音乐，或从网址获取mp3文件音乐并播放

### 原因

我需要这个功能来给自定义主页加入音乐。如果没有这个功能，就不能给自定义主页增加一些氛围感了。

**Comment by Deep-Dark-Forest** [comment]
……不确定技术上能不能实现？

**Comment by Ad-closeNN** [comment]
> 或从网址获取mp3文件音乐并播放
- #1380

**Comment by Joker2184** [comment]
LTCatt added 拒绝 / 放弃 and removed 等待确认 labels yesterday

**Comment by LTCatt** [comment]
暂不考虑，抱歉（
