### ISSUE TITLE
自定义主页加载图片失败

### ISSUE THREAD

**Issue by huoxingrNaNa** [Hex-Dragon/PCL2#5199]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

加载不了图片也不能下载。但是浏览器可以下载

### 重现步骤

![TCLE`HO@78F9V%5S`PR1IE2](https://github.com/user-attachments/assets/f381abb9-b02f-481a-9753-0f397d91df03)

### 日志与附件

无

**Comment by hejiehao** [comment]
用的哪个自定义主页？

**Comment by huoxingrNaNa** [comment]
读取本地文件




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Hex-Dragon/PCL2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月30日(星期六) 晚上10:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Hex-Dragon/PCL2] 自定义主页加载图片失败 (Issue #5199)





 
用的哪个自定义主页？

**Comment by Hill23333** [comment]
403...好奇怪
自己用PCL2的UA测试，可以访问。

**Comment by Hill23333** [comment]
> 哥们 神tm .ico 啊 PCL仅支持jpg png webp（only new MyImage控件）

为啥返回403？这很奇怪

**Comment by Hill23333** [comment]
我自己用PCL2的UA访问该链接没有返回403

**Comment by wuliaodexiaoluo** [comment]
这有可能是是 #5072 的副作用

**Comment by Hill23333** [comment]
> 这似乎是 #5072 的副作用

那就把这个issue标为重复？

**Comment by huoxingrNaNa** [comment]
b站可以。不知道
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Hex-Dragon/PCL2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月30日(星期六) 晚上10:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Hex-Dragon/PCL2] 自定义主页加载图片失败 (Issue #5199)





 
这似乎是 #5072 的副作用

**Comment by xxtg666** [comment]
可以发一下自定义主页加载这个图片时所用的代码看看

**Comment by Joker2184** [comment]
> 这似乎是 #5072 的副作用 当然也可能是服务器自主行为

应该 不太可能吧

**Comment by Hill23333** [comment]
![image](https://github.com/user-attachments/assets/8466776c-88d3-433c-b11d-53a7abc9293d)
成功复现

**Comment by Joker2184** [comment]
但是我那个应该只针对myimage控件不会影响下载

考虑作为新bug单开issue

**Comment by huoxingrNaNa** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Hex-Dragon/PCL2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月30日(星期六) 晚上10:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Hex-Dragon/PCL2] 自定义主页加载图片失败 (Issue #5199)





 
可以发一下自定义主页加载这个图片时所用的代码看看

**Comment by Hill23333** [comment]
疑似是因为多线程的原因？
我注意到进度条动了一动然后返回403的

**Comment by huoxingrNaNa** [comment]
不一定

**Comment by Hill23333** [comment]
![image](https://github.com/user-attachments/assets/0f08ac44-e4a5-44bb-85a0-cffa67d6f4cc)
使用类似的多线程下载器也返回403

**Comment by Joker2184** [comment]
嘶 那应该考虑服务器问题而不是PCL问题了

话说再怎么聊应该也要先来个log1看看吧

**Comment by huoxingrNaNa** [comment]
5个log

**Comment by Joker2184** [comment]
发log1.txt

**Comment by huoxingrNaNa** [comment]
单线程有没有返回403

**Comment by Joker2184** [comment]
你去设置拉到单线程看看？

**Comment by huoxingrNaNa** [comment]
![}R@OLY}{H%80O_SXTC(_D0U](https://github.com/user-attachments/assets/86720741-c7cb-4192-9ff6-10f80352a798)

**Comment by Hill23333** [comment]
![image](https://github.com/user-attachments/assets/4bddf78d-4678-4e3a-9e20-e4c759ed6391)
![image](https://github.com/user-attachments/assets/c55addb6-cfed-409b-b905-87fa7fafae86)

单线程也返回403

**Comment by huoxingrNaNa** [comment]
一样

**Comment by huoxingrNaNa** [comment]
[Log2.txt](https://github.com/user-attachments/files/17965783/Log2.txt)

**Comment by Joker2184** [comment]
要报完错关掉后的log1…
目前没看到有报错这个log

**Comment by JingHai-Lingyun** [comment]
是 **自定义主页** 带来的错误还是 **自定义下载** 带来的错误？

**Comment by huoxingrNaNa** [comment]
都有

**Comment by JingHai-Lingyun** [comment]
再次复现一下该 Bug，然后把 Log1-5.txt **全部传上来**

**Comment by mc-124** [comment]
经测试PCL2发的无头请求会导致403

**Comment by SALTWOOD** [comment]
估计是 #5072 导致的，也许可以考虑让龙猫来看看或者关掉？

**Comment by Light-Beacon** [comment]
应当是网站对请求头 Referer 做了白名单过滤

**Comment by Hill23333** [comment]
> 可能是网站对请求头 Referer 做了白名单过滤

我之前测试的时候也设置了Referer，并没有403

**Comment by Deep-Dark-Forest** [comment]
由于原作者太长时间没有回复，所以关闭此 Issue。
