### ISSUE TITLE
用秋仪金打开爱发电

### ISSUE THREAD

**Issue by shocean** [Hex-Dragon/PCL2#5202]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

右键秋仪金打开爱发电龙腾猫跃赞助画面

### 原因

这项优化让我可以更方便地打开龙腾猫跃赞助画面。如果没有这项优化，我每次都必须输入网址赞助，让操作变得很麻烦。

**Comment by shocean** [comment]
8D48-78F7-BAF5-6BC4

**Comment by Ad-closeNN** [comment]
- #4585

**Comment by Hill23333** [comment]
![image](https://github.com/user-attachments/assets/b3f99d64-dbd6-4c4c-818f-7bc43442c140)
这东西早就有了罢

**Comment by Ad-closeNN** [comment]
目前右键秋仪金（未解锁）时可以用默认浏览器打开 https://afdian.com/a/LTCat
![image](https://github.com/user-attachments/assets/8f39c75b-5168-4f87-acc6-95fdbef3c971)

但是解锁后没法右键打开：#4585
![image](https://github.com/user-attachments/assets/58e64940-beae-4f6c-b272-4c2e7e5da078)

请问 Author 是否指的是未解锁情况下右键打开的页面应为**https://afdian.com/a/LTCat/plan**而不是 LTCat 爱发电主页？

**Comment by allMagicNB** [comment]
凑活跃橙凑的

**Comment by allMagicNB** [comment]
你只有找出确实存在的 Bug 再反馈才有可能获得活跃橙。

**Comment by SALTWOOD** [comment]
重复，关了。
你这样发一堆奇奇怪怪的issue还立刻就带上识别码，很难不让人怀疑你是恶意开issue。

**Comment by JingHai-Lingyun** [comment]
按照与
- #4585

重复关掉了

**Comment by Joker2184** [comment]
优化标签 的 Issue 无法获得活跃橙
