### ISSUE TITLE
桌面的PCL2没法和任务栏的PCL2重叠

### ISSUE THREAD

**Issue by shocean** [Hex-Dragon/PCL2#5203]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

桌面的PCL2没法和任务栏的PCL2重叠

### 重现步骤

把PCL2添加到任务栏，点击桌面上的PCL2，会看到桌面的PCL2没法和任务栏的PCL2重叠。

### 日志与附件

[证据1](https://github.com/user-attachments/assets/d8261ee4-1190-4498-a325-bfece6d50f0b)

**Comment by shocean** [comment]
8D48-78F7-BAF5-6BC4

**Comment by Joker2184** [comment]
？？？？？ 

Windows问题 不属于PCL问题

来个Collaborator可以关了

**Comment by xxtg666** [comment]
无法复现

**Comment by Hill23333** [comment]
![image](https://github.com/user-attachments/assets/0a6b0f44-7530-41f4-a5e3-f2b6842e9dcd)
![image](https://github.com/user-attachments/assets/a3782cd4-142d-4db7-9ab1-4da02ea73c37)

你好是可以的（

请不要为了秋意金提交无用Issue

**Comment by lactobionicAcid** [comment]
如果你添加到任务栏的 PCL2 和桌面上的 PCL2 **不属于同一来源**，那么它们当然不会重叠到一起……

**Comment by allMagicNB** [comment]
鉴定为凑活跃橙凑的

**Comment by Deep-Dark-Forest** [comment]
> 请不要为了秋意金提交无用Issue

活跃橙（指正）

**Comment by SALTWOOD** [comment]
如果你继续开一些没有用的 issue，不仅无法帮助你获得活跃橙，还会被龙猫夹

没活可以咬打火机
