### ISSUE TITLE
PCL下载时

### ISSUE THREAD

**Issue by duzefang** [Hex-Dragon/PCL2#5215]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我在下载
1.21-Forge_51.0.33时
PCL显示严重错误
告诉我最好反馈
好像是网络

### 重现步骤

1、点击下载
2、选择1.21,添加Forge_51.0.33
3、安装

### 日志与附件

在类似这样的时候
![屏幕截图 2024-12-04 215641](https://github.com/user-attachments/assets/4682b9f0-58c6-4d7c-bc13-9259805464c2)

**Comment by duzefang** [comment]
刚刚那个图片也是下载一般卡在0B/s的图片

**Comment by lactobionicAcid** [comment]
在没有**错误日志**的情况下诊断任何问题无异于闭眼开车。——Apache官方文档

**Comment by duzefang** [comment]
[Log5.txt](https://github.com/user-attachments/files/18009393/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/18009395/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/18009397/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/18009398/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/18009399/Log4.txt)
是这些么

**Comment by shimoranla** [comment]
```
[19:26:48.473] 加载线程 DlForgeVersion Bmclapi (42) 发生运行时错误：没有可用版本
   在 PCL.ModDownload.DlForgeVersionBmclapiMain(LoaderTask`2 Loader)
   在 PCL.ModLoader.LoaderTask`2._Closure$__13-0._Lambda$__0()
[19:26:48.474] [Loader] 加载器 DlForgeVersion Bmclapi 状态改变：Failed
[19:26:48.489] 加载线程 DlForgeVersion 1.21.4 (32) 发生运行时错误：没有可用版本
   在 PCL.ModDownload.DlSourceLoader[InputType,OutputType](LoaderTask`2 MainLoader, List`1 LoaderList, Boolean IsForceRestart)
   在 PCL.ModDownload.DlForgeVersionMain(LoaderTask`2 Loader)
   在 PCL.ModLoader.LoaderTask`2._Closure$__13-0._Lambda$__0()
[19:26:48.489] [Loader] 加载器 DlForgeVersion 1.21.4 状态改变：Failed
```
这应该是 #5195 的另一种表现形式
请将版本获取来源改成尽量使用官方源或仅在官方源加载缓慢时改用镜像源来缓解此问题，或等待 bmclapi 同步

**Comment by duzefang** [comment]
![image](https://github.com/user-attachments/assets/29aab641-0b13-495b-9c5b-c8755fd32bed)

**Comment by LTCatt** [comment]
你的解锁码：UQP8e/jdPwYypBXJqBRYV1qFUzSzaQuM
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
