### ISSUE TITLE
内存只能分配32gb

### ISSUE THREAD

**Issue by 1259927406** [Hex-Dragon/PCL2#5216]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

手动内存分配只能到32gb 进度条拉满也就32gb，我电脑实际内存是64gb， 在设置的jvm参数头里 加入-Msm64G 也没有区别最大还是只能 32g启动，有什么方法么可以改良么 可以加我qq1259927406联系我
/
![{83643A5E-2E6B-452b-A080-1A6774490931}](https://github.com/user-attachments/assets/94d27149-1c05-4f0f-a769-0b59d07a3e44)

/

### 重现步骤

就是无法设置更高的内存

### 日志与附件

[Log4.txt](https://github.com/user-attachments/files/18010655/Log4.txt)
[Log1.txt](https://github.com/user-attachments/files/18010658/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/18010659/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/18010661/Log3.txt)

**Comment by Hill23333** [comment]
这属于feature，而不是一个bug

**Comment by 1259927406** [comment]
不管是不是什么feature不feature的  有啥办法能64g运行

**Comment by Hill23333** [comment]
![Screenshot_20241204_235421](https://github.com/user-attachments/assets/5472f637-cb00-4468-82ad-9e6897a2a4fe)

pcl 在设计上就不会让用户设置大于 32g 的内存。而且基于刚才其他人的回答，在未来pcl很大概率不会支持更多内存。

**Comment by 1259927406** [comment]
我是买了个材质包 卖家建议内存使用64g以上

**Comment by Hill23333** [comment]
> 我是买了个材质包 卖家建议内存使用64g以上

即便是4096x的材质也只需要分配 8g 内存即可。你的材质包有多大？

**Comment by SALTWOOD** [comment]
确实会有个别极端情况需要更多的内存，我有一个数据包就要求需要 50GB 的内存。
但是既然遇上极端情况了，为什么不自己更改启动参数呢？导出启动脚本然后再改一下应该也不会很难吧。
而且 MC 这东西……内存拉太满本身就有可能会炸

**Comment by shimoranla** [comment]
其实早些年前的版本是最大 64 GB
但是因为自动设置内存可能自动分配超过 64 GB 的内存导致游戏炸掉，所以只能调小一点（

**Comment by LTCatt** [comment]
需要注意的是，增加分配的内存不一定会提高性能，过高的内存反而可能会降低性能。
目前不考虑允许设置 32G 以上的内存，这可能导致游戏崩溃，但相对的几乎没有收益。
如果确实有需求可以自行导出启动脚本并且修改启动参数。
