### ISSUE TITLE
购买后未创建游戏档案，在登录时添加链接引导玩家创建

### ISSUE THREAD

**Issue by idhaname** [Hex-Dragon/PCL2#522]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

微软登录时未在官网创建游戏档案时，PCL2会报错“你可能没有在购买后去 Minecraft 官网创建游戏档案，或者没有购买 Minecraft”
建议像HMCL那样添加几个链接，引导玩家创建游戏档案

PCL2报错信息：
![PCL2报错信息](https://user-images.githubusercontent.com/68469786/205481673-9ba5587b-fe85-4668-8421-5035a9ef9361.jpg)
HMCL微软登录提示：
![HMCL微软登录提示](https://user-images.githubusercontent.com/68469786/205481663-f6a98b53-0839-4c76-b808-d891da644f56.png)

### 原因

这个信息也许会让小白一脸懵逼，不知道在哪里创建档案
有了这个功能就能方便的引导用户

PCL2相关日志：
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10148121/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10148122/Log4.txt)

**Comment by WForst-Breeze** [comment]
已经初步确认，感谢您的反馈~

**Comment by dongge0210** [comment]
log3.txt 中看出来微软登录步骤6开始发生404的错误随后的写了“Caused By: 远程服务器返回错误: (404) 未找到。”

**Comment by dongge0210** [comment]
log4也同样也写了
