### ISSUE TITLE
在使用JDK24时无法启动游戏

### ISSUE THREAD

**Issue by caicai7162** [Hex-Dragon/PCL2#5222]
### 检查项

- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在启动后会出现以下提示
![image](https://github.com/user-attachments/assets/bae6be02-376a-48e3-9a04-95f5d9fc891d)

### 重现步骤

1、点击设置
2、然后点击选择Java
3、选择JDK24
4、点击启动
5、点击启动游戏

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/18047627/Log1.txt)

**Comment by Sxcnbbb** [comment]
建议看一下这篇文章，版本太高容易出bug：[各Minecraft常见版本所需Java版本及其常见答疑](https://www.bilibili.com/opus/939387567592177669)

**Comment by Hill23333** [comment]
其他版本的java可以正常启动吗？因为这看起来像是opengl的问题。

**Comment by caicai7162** [comment]
> 其他版本的java可以正常启动吗？因为这看起来像是opengl的问题。 顺便把显卡型号发上来

从JDK14到JDK23来看是可以的 显卡是英伟达2070Super

**Comment by Hill23333** [comment]
无法复现。
使用jdk 24 (openjdk-24-ea+27_windows-x64_bin.zip SHA256: d3c4c15520262f2d3de174d973e37053081a8b627a66e8f4939419b4af8b4823)
启动1.21.4，成功。

**Comment by caicai7162** [comment]
我的Java版本是： openjdk-24-ea+18_windows-x64_bin.zip

**Comment by caicai7162** [comment]
可能高版本修复了这个问题
