### ISSUE TITLE
模组升级功能优化

### ISSUE THREAD

**Issue by Sxcnbbb** [Hex-Dragon/PCL2#5223]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

#### 在一些多模组的版本中，批量升级模组会发生许多不兼容的情况，所以能不能加入：
1. 在升级mod之前自动检查兼容性问题（如果可以，我觉得不大可能）
2. 如果发生兼容性错误可不可以**自动识别问题并且帮我更换mod**（比如fabric就会告诉我哪些mod需要替换/安装）
3. 实在不行可不可以**总结一下**需要安装/替换的mod（fabric端好像不行，forge大部分时候可以）

### 原因

看fabric给的报错窗口太费眼睛了（emm……）
更重要的是：***你知道升级完启动十几个不兼容是什么体验吗？心态都要崩了……***

**Comment by Pigeon0v0** [comment]
升级 Mod 本来就是不推荐的行为

其他参考 #5188 等
