### ISSUE TITLE
在 Github action build 中使用最新的 PCL2HELP 而不是上一个版本的 `Help.zip`

### ISSUE THREAD

**Issue by z0z0r4** [Hex-Dragon/PCL2#5226]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

每次 GitHub action build 时，使用最新的帮助库内容，直接从 https://github.com/LTCatt/PCL2Help 拉取

### 原因

内测也应该包括帮助库，以便确认帮助库是否有问题

没谁会去专门拉取，看最新帮助库，pr 合并之后大多情况就没人管了吧...再有错误多半是下次发版本的时候才有用户看到

放进 debug 版本也方便其他不参与帮助库撰写的用户检查

同时也方便检验 https://github.com/LTCatt/PCL2Help/issues/393 ，如果有问题可以及时撤销

**Comment by z0z0r4** [comment]
不熟vb编译...应该不需要动代码，只需要在 https://github.com/Hex-Dragon/PCL2/blob/b8eb669351517decaf3195771240b5d607272090/.github/workflows/build.yml 加上替换 `[Help.zip](https://github.com/Hex-Dragon/PCL2/blob/main/Plain%20Craft%20Launcher%202/Resources/Help.zip)` 的操作就行了吧？

**Comment by z0z0r4** [comment]
> 早就想做了。（

可以交给你吗...我说实话有点忙，不想糊 action（

大概 `wget https://github.com/LTCatt/PCL2Help/archive/refs/heads/master.zip` 就行了

**Comment by allMagicNB** [comment]
现在主要就是，这个选项要默认吗？

**Comment by z0z0r4** [comment]
不如说，内测版为什么不包括内测 PCL2HELP...（？

**Comment by wuliaodexiaoluo** [comment]
>现在主要就是，这个选项要默认吗？可能会稍微延长时间。

其实就几秒钟也不需要太在意

**Comment by tangge233** [comment]
可以额外编译一个使用最新帮助库的版本？

**Comment by z0z0r4** [comment]
建议默认，说的好像最终正式版没帮助库一样（）

**Comment by allMagicNB** [comment]
触发事件有想法挂哪吗？

**Comment by z0z0r4** [comment]
> 触发事件有想法挂哪吗？

触发事件是啥？

我的意思是只在 build 过程中，替换 `Help.zip` 用来编译，而不是自动更新 repo 里面的 `Help.zip`欸？

**Comment by allMagicNB** [comment]
现在的触发事件就是打开 PR 时或推送 Commit 时，自动执行一次编译。但是当帮助库更新时无法触发，因为两者不在同一 Repo 内。

**Comment by z0z0r4** [comment]
无所谓吧...我认为帮助库的更新频率可比这边触发 ci 的频率低多了

**Comment by z0z0r4** [comment]
机子到期时间：2025年1月7日
说实话很期待B站图床到底能不能用...我看看还续费不续费...
草，域名2025年01月10日也要到期了... 应该不会续了...

**Comment by LTCatt** [comment]
……如果有谁会做的话可以交 PR，我不会整 orz

**Comment by JingHai-Lingyun** [comment]
如果要帮助库更新也拉起 CI Build 的话，看 GraphQL 或者 RESTful API 支不支持这么干，可以的话配一个 Bot 的 PAT 模拟 workflow_dispatch 手动拉起构建

**Comment by allMagicNB** [comment]
> 如果要帮助库更新也拉起 CI Build 的话，**看 GraphQL 或者 RESTful API 支不支持这么干**，可以的话配一个 Bot 的 PAT 模拟 workflow_dispatch 手动拉起构建

……我又不是说不能实现，只是实现要龙猫自己才能整。

**Comment by z0z0r4** [comment]
well done

**Comment by z0z0r4** [comment]
欸，草，我不能自己 close 嘛...

**Comment by Pigeon0v0** [comment]
等 PR 合并了关联关掉
