### ISSUE TITLE
基于字段查找的前置模组自动检测及下载功能

### ISSUE THREAD

**Issue by GOhaochen** [Hex-Dragon/PCL2#5230]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

目前问题：如下图所示，一个前置MOD关联的MOD有很多，在添加MOD时一并下载的前置MOD很有可能被忘记，导致多加/漏加，这都会产生不必要的麻烦
![image](https://github.com/user-attachments/assets/8ff41b7b-de1c-46d4-9c9c-873bfe0cecba)
现在，我希望加入如下功能：
1.基于字段查找功能，在选择下载路径后自动检测是否有同名的前置MOD，
|  事件   | 对话框  | 按钮 |按钮 |
|  ----  | ----  | ---- | ---- |
| 有同名前置MOD  | 该文件夹下已有前置MOD，不需要在再下载了|确认| |
| 没有同名MOD  | 该文件夹下没有前置MOD，是否下载？| 立即自动下载|稍后手动下载|
| 有同名前置MOD但版本非最新  | 该文件夹下已有前置MOD，但版本较旧，是否更新？|立即更新| 稍后手动更新|

### 原因

一个前置MOD关联的MOD有很多，在添加MOD时一并下载的前置MOD很有可能被忘记，导致多加/漏加，这都会产生不必要的麻烦

**Comment by wuliaodexiaoluo** [comment]
#179 

事实上漏标/错标前置的 Mod 并不少

**Comment by GOhaochen** [comment]
> #179
> 
> 事实上漏标/错标前置的 Mod 并不少

所以添加了一个稍后手动下载的按钮，谢谢提醒！

**Comment by allMagicNB** [comment]
- #2494

**Comment by LTCatt** [comment]
转 #5235
