### ISSUE TITLE
搜索Java时增加小提示

### ISSUE THREAD

**Issue by MacroMeng** [Hex-Dragon/PCL2#5233]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 优化之处
在设置-游戏-游戏Java下点击自动搜索后PCL（应该）会开始在搜索Java,
但是这时点击下拉框不会有任何反应。
### 如何优化
搜索Java时，用户点击下拉框后，弹出一个小提示，如“仍在搜索Java，请等待。”etc.

### 原因

每次我搜索Java时都会十分慢 ~~*（鬼知道电脑里有什么东西）*~~ 所以有了这个功能我就 ~~*可以让PCL鬼畜*~~ 有消遣了qwq

**Comment by shimoranla** [comment]
>每次我搜索Java时都会十分慢 （鬼知道电脑里有什么东西） 所以有了这个功能我就 可以让PCL鬼畜 有消遣了qwq

大抵是目录太多了（

**Comment by LTCatt** [comment]
![image](https://github.com/user-attachments/assets/cbbb32c3-a285-4348-b066-52459fb056f4)
搜索的时候这不是会提示加载中么……
