### ISSUE TITLE
帮助库图片大爆炸

### ISSUE THREAD

**Issue by Joker2184** [Hex-Dragon/PCL2#5242]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

图片炸了

### 重现步骤

![Image_13556742343241](https://github.com/user-attachments/assets/346270eb-def4-4be8-87ba-0dd60245c5d2)

![Image_13764278377584](https://github.com/user-attachments/assets/2563eabb-ce44-4ea8-8cd7-870a1ffcca1e)

多台电脑 复现 

### 日志与附件

不需要应该打开帮助库就行

**Comment by LTCatt** [comment]
https://github.com/LTCatt/PCL2Help/pull/399
