### ISSUE TITLE
单人存档背包丢失

### ISSUE THREAD

**Issue by Taskkil** [Hex-Dragon/PCL2#5247]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

离线登录下皮肤选择随机（或者加载失败）时创建存档，当皮肤选择正版皮肤（或加载成功）后进入存档背包会丢失
但是在正版皮肤（或者加载成功）时创建存档，当使用随机皮肤（或者加载失败）时，会保留物品
备注：1.12.2，1.16.5均出现这个bug
![屏幕截图 2024-12-10 133914](https://github.com/user-attachments/assets/58343f5b-5c87-4f1c-b202-3c015d06e707)

### 重现步骤

1.在PCL的启动界面，点击头像
2.点击随机
3.返回到启动界面，启动游戏
4.在游戏里创建存档
5.随便拿点物品（比如挖个泥土），让背包改变
6.退出存档并退出游戏
7.回到PCL主界面
8.点击头像
9.点击正版皮肤
10.输入正版ID
11.刷新缓存
12.回到启动界面
13.启动游戏
14.进入存档
这时，背包里刚挖的泥土应该没了

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/18072673/Log1.txt)
![屏幕截图 2024-12-10 133914](https://github.com/user-attachments/assets/00a071ba-7f90-47ea-89ff-e58ed413b595)

**Comment by LTCatt** [comment]
切换离线皮肤会导致物品栏不共享，WAI，也无法修复
