### ISSUE TITLE
Win7系统点“清空背景图片”可能出错

### ISSUE THREAD

**Issue by G-mare** [Hex-Dragon/PCL2#5249]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

Win7系统点击“清空背景图片”有概率导致PCL2弹权限不足，即使以管理员身份运行也一样

<details>
  <summary>截图</summary>

  ![image](https://github.com/user-attachments/assets/428e7e9d-78f0-494c-bc92-a9a921f5b94f)
  ![image](https://github.com/user-attachments/assets/7c94a75c-908e-4972-8d1a-aba9983480bc)

</details>

注：不同于 #4453 

### 重现步骤

1. 打开PCL2启动器，进入 <PCL2程序位置>/PCL/Pictures 并随意复制一张图片到这个文件夹（**不要关闭文件夹！**）
2. 在启动器设置的个性化界面点击“清空背景图片”，随后启动器弹出权限不足的弹窗，可参考附件中的视频

不一定能复现，目前只在Win7遇到过

系统环境：Windows 7 SP1 + KB2813430 + .Net Framework 4.8

ps:如果后续不支持Win7就关闭issue吧

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/18074879/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/18074881/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/18074882/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/18074883/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/18074884/Log5.txt)

<details>
  <summary>视频</summary>
    
https://github.com/user-attachments/assets/1e2ae32f-9ec0-454f-9291-ccdd2ee3ae92

</details>

**Comment by shimoranla** [comment]
```
Access to the path 'C:\Users\Yoshino\Desktop\PCL\PCL\Pictures' is denied.
```

试试非管理员权限？


```
Could not find a part of the path 'C:\Users\Yoshino\Desktop\PCL\PCL\Pictures'.
```

这应该是上面错误的衍生错误

```
错误类型：System.IO.DirectoryNotFoundException

是否反馈此问题？如果不反馈，这个问题可能永远无法得到解决！
```
这个应该是非中文 .NET 运行时环境导致的

**Comment by G-mare** [comment]
> 试试非管理员权限？

不用管理员也一样，日志如下
[Log1.txt](https://github.com/user-attachments/files/18076056/Log1.txt)

**Comment by LTCatt** [comment]
权限问题，不要放在 C 盘或桌面
