### ISSUE TITLE
新版本快照多数帮助选项会出现报错

### ISSUE THREAD

**Issue by Nya-Evening** [Hex-Dragon/PCL2#5251]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

大多数帮助都会出现报错，mod,光影等帮助选项点击都会出现此类似的报错。但正版登录等选项并不会出现报错
![98eed0fbb1d68e2ceaf937ae190d37c](https://github.com/user-attachments/assets/49e7d468-49b3-4b91-91df-1049aa81fd5d)

### 重现步骤

1、点击更多，帮助
2、往下滚，然后点击安装光影，安装mod等选项会出现此报错

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/18091514/Log1.txt)

**Comment by Light-Beacon** [comment]
- https://github.com/Hex-Dragon/PCL2/issues/5242
- https://github.com/LTCatt/PCL2Help/pull/399
