### ISSUE TITLE
注册表主题引导

### ISSUE THREAD

**Issue by EggyPartyMc** [Hex-Dragon/PCL2#5253]
### 检查项

- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

1.当设备出现出现问题，注册表回档，PCL2主题将消失
2.部分时候别人将指定注册表项给你，你覆盖后，PCL2会新增主题

### 重现步骤

当回档注册表
当别人把部分注册表给你，你覆盖掉你的注册表

### 日志与附件

无

**Comment by shimoranla** [comment]
请上传日志文件

**Comment by Joker2184** [comment]
bro 

> 当别人把部分注册表给你，你覆盖掉你的注册表 

这玩意不能通用的

**Comment by Deep-Dark-Forest** [comment]
由于原作者太长时间没有回复，所以关闭此 Issue。
