### ISSUE TITLE
使用pcl启动mc时无法加载出3d的皮肤层

### ISSUE THREAD

**Issue by KernelC1130** [Hex-Dragon/PCL2#5264]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

使用pcl启动mc时无法加载出3d的皮肤层，加载3d皮肤层mod也不显示，用官方启动器启动却可以加载出来

### 重现步骤

用pcl启动mc进入世界

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/18134284/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/18134285/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/18134286/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/18134287/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/18134288/Log5.txt)

**Comment by KernelC1130** [comment]
[latest.log](https://github.com/user-attachments/files/18134463/latest.log)

**Comment by KernelC1130** [comment]
[latest.log](https://github.com/user-attachments/files/18134475/latest.log)
这是装了mod的 也是没有反应

**Comment by KernelC1130** [comment]
[latest.log](https://github.com/user-attachments/files/18134494/latest.log)

**Comment by Deep-Dark-Forest** [comment]
由于原作者太长时间没有回复，所以关闭此 Issue。
