### ISSUE TITLE
无法更改自定义版本图标

### ISSUE THREAD

**Issue by Norr32** [Hex-Dragon/PCL2#5265]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

无法更改自定义版本图标，更改预置图标仍弹出报错但正常设置。
已尝试管理员模式，放行Defender及其他杀软白名单

### 重现步骤

1、管理员模式打开PCL
2、打开版本设置
3、选择个性化 > 自定义，选择一个PNG文件
4、弹出如下窗口：

更改自定义版本图标失败（Hypiworld_TsuriNoGatsu）：PCL 的权限不足。请尝试右键 PCL，选择以管理员身份运行。
对路径“（隐去）\.minecraft\versions\Hypiworld_TsuriNoGatsu\PCL\Logo.png”的访问被拒绝。
————————————
详细错误信息：
   在 PCL.PageVersionOverall.ComboDisplayLogo_SelectionChanged(Object sender, SelectionChangedEventArgs e)
错误类型：System.UnauthorizedAccessException

5、此后图标变为红石块

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/18134348/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/18134345/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/18134346/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/18134347/Log4.txt)

**Comment by lactobionicAcid** [comment]
你加载的图片是否带有 “只读” 属性？

![image](https://github.com/user-attachments/assets/6fa0d47e-e9ce-44c8-bd5e-c2e7cc6d4dc5)

**Comment by JingHai-Lingyun** [comment]
如果你的图像文件有只读属性，将会导致 PCL 无论以什么身份启动都无法读取照片……
请确认你的文件没有设置此 Flag

**Comment by lactobionicAcid** [comment]
等下，这个 Bug 没有那么简单……
在设置了一个带有 “只读” 属性的图标后，如果尝试**更换为其他图标**，会弹出报错……🤔

即使文件不可读取，PCL 还是将其复制到版本文件夹下，这点或许才是要修的地方……？

![image](https://github.com/user-attachments/assets/3fd586fd-d3ee-4d66-b264-4761d8237281)

**Comment by lactobionicAcid** [comment]
> 即使文件不可读取，PCL 还是将其复制到版本文件夹下，这点或许才是要修的地方……？

@LTCatt 看看？

**Comment by LTCatt** [comment]
设只读出 bug 就不考虑了（
