### ISSUE TITLE
这只是一个bug[已解决]

### ISSUE THREAD

**Issue by MEMZCC** [Hex-Dragon/PCL2#5273]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

无

### 重现步骤
无

### 日志与附件

[Log.txt](https://github.com/user-attachments/files/18135715/Log.txt)
[Log1.txt](https://github.com/user-attachments/files/18135716/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/18135717/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/18135718/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/18135719/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/18135720/Log5.txt)

**Comment by JingHai-Lingyun** [comment]
## 你要反馈什么……
**详细描述**你遇到的问题，而不是随意填写 Issue  表单

---

## 尝试分析你的 Log2.txt 提供客户端崩溃支持
尝试禁用以下模组后再试
```
	Tinkers Innovation (tinkersinnovation), Version: 1.18.2-1.0.1
	Tinkers' Construct (tconstruct), Version: 3.7.2.167
```

**Comment by allMagicNB** [comment]
……转人工
