### ISSUE TITLE
无法打开下载界面

### ISSUE THREAD

**Issue by jeremysun0324** [Hex-Dragon/PCL2#529]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

打开下载界面会报错

### 重现步骤

直接打开下载界面就会

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10152608/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10152609/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10152610/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10152611/Log1.txt)
[Log2.txt](https://github.com/Hex-
Dragon/PCL2/files/101526
![屏幕截图 2022-12-05 171501](https://user-images.githubusercontent.com/81454513/205599347-f38da9f3-7009-49ba-8d57-35acb1f87779.png)
13/Log2.txt)

**Comment by LTCatt** [comment]
先更新到最新版再说
