### ISSUE TITLE
[简单UI调整]将Mod管理中的四个按钮填充满一行

### ISSUE THREAD

**Issue by GOhaochen** [Hex-Dragon/PCL2#5290]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

如标题所示，建议将Mod管理中的四个按钮填充满一行，以提高美观性
![image](https://github.com/user-attachments/assets/b979b444-552d-43c1-bc0a-954fe9c525d6)

### 原因

提高美观性，更大的按钮也有助于减少点击错误的概率

**Comment by BarbTurnip437** [comment]
智齿

**Comment by LTCatt** [comment]
之后如果有空这些 UI 会统一换成带图标的样式……现在先不改了
