### ISSUE TITLE
日志文件格式更改

### ISSUE THREAD

**Issue by BarbTurnip437** [Hex-Dragon/PCL2#5297]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

将日志格式由txt改为log
将中文标点改为英文标点加空格

### 原因

（示例）
这项优化让我可以更方便地阅读日志。
如果没有这项优化，我每次都必须更改文件名让[插件](https://github.com/log-inspector/LogInspector)识别，让操作变得很麻烦。
中文标点会让编辑器产生莫名其妙的高亮

**Comment by shimoranla** [comment]
>中文标点会让编辑器产生莫名其妙的高亮

如果是 VSCode，可以将光标悬浮在高亮部分上，然后在浮窗中点击禁止突出显示

**Comment by SALTWOOD** [comment]
没必要。如果嫌弃中文标点的高亮可以选择禁用提示而不是交一个无关痛痒的 issue。
~~说白了就是你的问题~~

**Comment by BarbTurnip437** [comment]
> > 中文标点会让编辑器产生莫名其妙的高亮
> 
> 如果是 VSCode，可以将光标悬浮在高亮部分上，然后在浮窗中点击禁止突出显示

:) 谢谢

**Comment by Pigeon0v0** [comment]
改为 .log 会直接导致移动端 QQ 阅读日志极为困难...

**Comment by shimoranla** [comment]
> 改为 .log 会直接导致移动端 QQ 阅读日志极为困难...

虽然不改读的也不顺利就是了，QQ 那个编辑器也不好用

**Comment by Pigeon0v0** [comment]
> ~虽然不改读的也不顺利就是了，QQ 那个编辑器也不好用~
> 
> 好像也不困难，除非在 QQ 自带的编辑器阅读文本 
> 
> 不过 MT 明显是个更好的选择

请你使用 iOS 设备

**Comment by shimoranla** [comment]
> 请你使用 iOS 设备

a?
失算了

（VME 50）

~The best to solve problem:mv /mobile/phone/ios /dev/null~(无恶意)

**Comment by LTCatt** [comment]
目前没有什么必要……
