### ISSUE TITLE
JVM内存超过一定数值，报错内存不足，导致 PCL 无法继续运行

### ISSUE THREAD

**Issue by fufu1013A** [Hex-Dragon/PCL2#5299]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

运行游戏时，JVM内存占用超过一定数值，pcl会报错：Crash Analyzer：线程执行失败：你的电脑运行内存不足，导致 PCL 无法继续运行。请在关闭一部分不需要的程序后再试。
引发类型为“System.OutOfMemoryException”的异常。
（错误分析在log2.txt文件最后）

### 重现步骤

1、游戏运行过程中，JVM内存占用过高，超过一定数值会直接报错。
2、点击百宝箱中的内存优化后，内存占用会下降，但还是会报错

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/18152382/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/18152383/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/18152384/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/18152385/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/18152386/Log5.txt)

**Comment by lactobionicAcid** [comment]
#4252
> OutOfMemoryException 只能由系统报出，均与启动器无关 :/
