### ISSUE TITLE
安装1.12.2-LiteLoader时报错

### ISSUE THREAD

**Issue by yy-619** [Hex-Dragon/PCL2#530]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在自动安装1.12.2的LiteLoader版本时报错：
该字符串未被识别为有效的 DateTime。

### 重现步骤

1、点击下载>正式版>1.12.2
2、然后点击LiteLoader>1.12.2
3、点击开始安装

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10152632/Log1.txt)

**Comment by LTCatt** [comment]
#386
