### ISSUE TITLE
请为有一定知识基础的人开放允许使用定制jre

### ISSUE THREAD

**Issue by fhnt5** [Hex-Dragon/PCL2#5305]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

请允许手动选择用户用jlink定制的jre启动游戏，可以加上严重警告提示但请不要禁止使用这种jre。若游戏崩溃，我会根据日志去重新定制jre

### 原因

我不想因为玩MC而装上太多完整的jdk，我只需要一个jdk用于开发，我想用jlink生成的jre来运行其他版本。

**Comment by Joker2184** [comment]
大概不会考虑

目前开发主要以修复BUG和投票的玩家最需功能为主

wait LTCatt

**Comment by LTCatt** [comment]
如果确实有需要，你可以查阅 PCL 的代码，新建几个特定文件名的文件来骗过 PCL 的检测，让它认为这是 JDK……
