### ISSUE TITLE
mod搜索手动删除版本号后提示“可视化Mod列表出错”

### ISSUE THREAD

**Issue by WitherStorm-WS** [Hex-Dragon/PCL2#5308]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

提示如下：
![image](https://github.com/user-attachments/assets/69172ba8-d4b5-4826-808d-272e32a4465e)

### 重现步骤

1. 点击下载
2. 点击Mod
3. 在清空版本号的情况下搜索Mod
4. Bug被触发

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/18209625/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/18209626/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/18209620/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/18209623/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/18209624/Log5.txt)

**Comment by JingHai-Lingyun** [comment]
没在日志里找到对应信息…… 但这应该是
- #5255
