### ISSUE TITLE
PCL2正式版应当以64位运行

### ISSUE THREAD

**Issue by GTEMYee** [Hex-Dragon/PCL2#531]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

我没有向龙腾猫跃捐助过
所以只能用正式版
以为PCL2启动器一直都是32位的

### 原因

64位操作系统应当运行64位程序

**Comment by dongge0210** [comment]
啊这 这不影响pcl2的体验.....
