### ISSUE TITLE
mojang办公室新披风没有译名

### ISSUE THREAD

**Issue by North-Melon** [Hex-Dragon/PCL2#5311]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

建议翻译为：Mojang办公室披风或办公室披风
![PixPin_2024-12-21_10-26-35](https://github.com/user-attachments/assets/e11e93d6-9df5-4049-9dd2-bdc30017f6e3)

### 原因

这项优化让我可以更方便地找到披风

**Comment by Ad-closeNN** [comment]
- #5260
