### ISSUE TITLE
[Feature] 允许通过拖动链接的形式安装整合包 \ Mod

### ISSUE THREAD

**Issue by wuliaodexiaoluo** [Hex-Dragon/PCL2#5319]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

允许通过拖动链接下载 Mod \ 整合包

### 原因

部分网络下载内容可能相对较慢，通过拖动链接使用多线程下载可以加速安装过程
虽然自定义主页也能实现类似效果，但比起启动器自动处理明显要麻烦不少
启动器也支持拖动链接来设置内容，例如 Yggdrasil 验证服务器的设置，所以理论上不是什么难事

**Comment by Hill23333** [comment]
> 通过拖动链接使用多线程下载可以加速安装过程

如果是拖动链接的话很有可能要做下载源处理，但是 MCIM 源一般不允许多线程下载

**Comment by wuliaodexiaoluo** [comment]
> > 通过拖动链接使用多线程下载可以加速安装过程
> 
> 通过此种情况下载 Mod / 整合包 很有可能要做下载源处理，但是 MCIM 源一般不允许多线程下载

这个 Mod 或整合包可以来自其他网站，并非只限定于 Modrinth/CurseForge

**Comment by Hill23333** [comment]
这样的话，判定是非常大的问题。
如果不是直链，将会非常难判断。
而且很有可能用户会拖入不知名链接然后引发一堆 issue

**Comment by SALTWOOD** [comment]
处理拖入链接本身的下载（访问）鉴权，要是 403 **很可能被用户误投issue**

**Comment by LTCatt** [comment]
暂时不考虑，抱歉
