### ISSUE TITLE
自定义下载任务文件无法下载时，需要等待10min以上才提示"无法下载"

### ISSUE THREAD

**Issue by Ext1nguisher** [Hex-Dragon/PCL2#5324]
### 检查项

- [ ] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如题，我自定义了一个下载任务，但该[文件链接](http://www.oldtimes-software.com/files/0x10c/0x10c.zip)是根本无法下载的。
我得知后，等待10min以上，PCL才提示超时"无法下载"。

### 重现步骤

1. 打开“更多”-“百宝箱”-“下载自定义文件”， 在“下载地址栏”内输入一个无法下载的链接
2. 点击“开始下载”按钮，记录下从按下按钮到显示“无法下载”提示的时间。

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/18229207/Log1.txt)
呃……其他(Log2~4)就不上传了，反正没关系……

**Comment by Joker2184** [comment]
[Log2.txt](https://github.com/user-attachments/files/18230032/Log2.txt)
测试 未复现

**Comment by Ext1nguisher** [comment]
> [Log2.txt](https://github.com/user-attachments/files/18230032/Log2.txt) 测试 未复现

收到，周末再试一次本机是否能够复现。

**Comment by lactobionicAcid** [comment]
成功复现。不挂梯子时，开始下载 **1~10 分钟**后提示无法连接到远程服务器。
具体等待的时间视**最大线程数**而定。

（挂梯子后则是在数秒内返回 404 Not Found）

[Log1.txt](https://github.com/user-attachments/files/18230625/Log1.txt)

**Comment by LTCatt** [comment]
WAI，如果链接不稳定 PCL 会以逐渐增加的超时时间尝试 5 次，尽量不失败（这是因为 MC 的下载不稳定才这样做的）

**Comment by Ext1nguisher** [comment]
虽然closed了，但是还是给点信息：
最大线程数：64
下载时没有用梯子

**Comment by Ext1nguisher** [comment]
> WAI，如果链接不稳定 PCL 会以逐渐增加的超时时间尝试数次，尽量不失败（这是因为 MC 的下载不稳定才这样做的）

那我任务可以在自定义下载中取消这个机制（指`增加的超时时间`) 因为`是因为 MC 的下载不稳定`吧。或者在设置中加个选项，比如`超时时间`，`是否递增`等
