### ISSUE TITLE
mod分类显示错误

### ISSUE THREAD

**Issue by DoubtedYapper71** [Hex-Dragon/PCL2#5329]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

mod分类中禁用mod中出现已启用mod

### 重现步骤

1.在禁用列表中任意启用mod
2.直接退出mod界面
3.回到mod见面后已启用mod仍然在禁用列表中

### 日志与附件

[Log.txt](https://github.com/user-attachments/files/18239668/Log.txt)
[Log1.txt](https://github.com/user-attachments/files/18239669/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/18239670/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/18239671/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/18239672/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/18239673/Log5.txt)

**Comment by LTCatt** [comment]
WAI，这是为了避免操作后被操作的 Mod 马上消失。直接退出不在此考虑范围内。
