### ISSUE TITLE
让我的世界出现错误界面可以复制

### ISSUE THREAD

**Issue by LiuBinzhe** [Hex-Dragon/PCL2#533]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

让PCL的出我的世界现错误界面可以复制，不然一个一个打单词太累了qwq.

### 原因

这项优化让我可以更方便地查看错误。
如果没有这项优化，我每次都必须手打单词，让操作变得很麻烦。

**Comment by WForst-Breeze** [comment]
感谢反馈，但是PCL2在游戏崩溃后的弹窗只会给一些可能的关键词或是可能的解决方案，我觉得直接看错误报告是查看错误一种更好的选择，但是这边还是先给您初步确认了qwq

**Comment by LTCatt** [comment]
错误报告中有相关内容。
PCL 的弹窗提供的错误信息也并不足以实际处理错误，没有必要复制。
