### ISSUE TITLE
考虑添加 崩溃日志管理/崩溃记录 功能

### ISSUE THREAD

**Issue by Aspy1** [Hex-Dragon/PCL2#5330]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

如题 在启动器设置界面添加这一功能。可以按日期/按PCL提取得到的关键词/按版本，对某次特定崩溃进行搜索，并定位到崩溃日志文件夹
此优化可以方便在制作整合包时排查不兼容情况

### 原因

（示例）
这项优化让我可以更方便地xxxx。
如果没有这项优化，我每次都必须xxxx，让操作变得很麻烦。

**Comment by shimoranla** [comment]
你是否需要
- #46
- 关联投票 #47

暂未发现重复

**Comment by Aspy1** [comment]
是需要的（
我自己有制作整合包的想法

**Comment by LTCatt** [comment]
暂时不考虑，抱歉（
