### ISSUE TITLE
希望支持多开启动器

### ISSUE THREAD

**Issue by xiaoanTAT** [Hex-Dragon/PCL2#5332]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

希望支持多开启动器，增加新mod或者附属的时候一个启动器用来着看本地mod详细转mc百科看MOD关联有哪些附属或者联动，另一个启动器用来下载mod。不然只能一个启动器怪麻烦的切启动器的界面切来切去的

### 原因

爱我的爱我的挖到啊啊我

**Comment by shimoranla** [comment]
>希望支持多开启动器

这会导致日志记录时产生线程冲突，导致多开的 PCL 无法写入日志
如果确实需要此功能请参考 https://multiple-pcl2.pages.dev/
但请注意，如果**多开部分**出现 Bug，我们无法提供**有效支持**

**Comment by BarbTurnip437** [comment]
> 希望支持多开启动器，增加新mod或者附属的时候一个启动器用来着看本地mod详细转mc百科看MOD关联有哪些附属或者联动，另一个启动器用来下载mod。不然只能一个启动器怪麻烦的切启动器的界面切来切去的
这个你可以改改改成用单开就可以实现的描述

**Comment by LTCatt** [comment]
多开会出很多未知 bug，暂不考虑……
