### ISSUE TITLE
1.21.1整合包，启动卡在“等待游戏窗口出现”，或者在创建存档时直接崩溃

### ISSUE THREAD

**Issue by LWhiteBasi1** [Hex-Dragon/PCL2#5333]
### 检查项

- [ ] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃基本不是 PCL 的原因，请 **不要** 提交反馈。你可以在论坛或社区找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用 HMCL 启动，HMCL 没有出现问题。** 如果 HMCL 也无法启动就不是 PCL 导致的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [ ] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

整合包为Remake & Remaster，后发现所有版本均有这样的问题，卡了30分钟“等待游戏窗口出现”。关闭一次版本隔离，重新安装Fabric-api后成功启动，但在单人游戏创建新世界时直接崩溃
![AAF6B17AE1DC9367B1DEFF5F96D01FC6](https://github.com/user-attachments/assets/73e338ce-964f-4120-919f-f9c29835c9ff)

### PCL 错误报告、日志与附件

![AAF6B17AE1DC9367B1DEFF5F96D01FC6](https://github.com/user-attachments/assets/ad56c234-2811-4c98-8736-fe67448bfa32)
没有启动的案例了，故没有错误日志

**Comment by shimoranla** [comment]
请勿在 Issue 页面反馈整合包崩溃问题，**这通常不是 PCL 引起的**，如果需要帮助，请在 Discussion 发帖**并附上崩溃报告**，感谢配合
