### ISSUE TITLE
1.19.1/2下载Opt高清修复时报错安装器出现问题

### ISSUE THREAD

**Issue by Leo54lij** [Hex-Dragon/PCL2#534]
### 检查项

- [x] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

下载 OptiFine 1.19.1 H9失败
Caused By: 安装 OptiFine（方式 A）失败
Caused By: 安装新版 OptiFine 版本失败
Caused By: 安装器运行出错，末行为 	at oolloo.jlw.Wrapper.main(Wrapper.java:22)
   在 PCL.ModDownloadLib._Closure$__17-0._Lambda$__5(LoaderTask`2 Task)
   在 PCL.ModLoader.LoaderTask`2._Closure$__12-0._Lambda$__0()
   在 PCL.ModDownloadLib.McDownloadOptiFineInstall(String BaseMcFolderHome, String Target, LoaderTask`2 Task)
   在 PCL.ModDownloadLib._Closure$__17-0._Lambda$__5(LoaderTask`2 Task)

### 重现步骤

无

### 日志与附件

下载 OptiFine 1.19.1 H9失败
Caused By: 安装 OptiFine（方式 A）失败
Caused By: 安装新版 OptiFine 版本失败
Caused By: 安装器运行出错，末行为 	at oolloo.jlw.Wrapper.main(Wrapper.java:22)
   在 PCL.ModDownloadLib._Closure$__17-0._Lambda$__5(LoaderTask`2 Task)
   在 PCL.ModLoader.LoaderTask`2._Closure$__12-0._Lambda$__0()
   在 PCL.ModDownloadLib.McDownloadOptiFineInstall(String BaseMcFolderHome, String Target, LoaderTask`2 Task)
   在 PCL.ModDownloadLib._Closure$__17-0._Lambda$__5(LoaderTask`2 Task)

**Comment by bwtx2022** [comment]
请上传启动器日志

**Comment by dongge0210** [comment]
人呢？

**Comment by LTCatt** [comment]
无日志+短期未回复暂时关闭
