### ISSUE TITLE
在下载mod时搜索席地而坐会出现报错

### ISSUE THREAD

**Issue by fenggua111** [Hex-Dragon/PCL2#5343]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

输入搜索内容后，然后出现报错，如若点击取消，内容会正常显示
![image](https://github.com/user-attachments/assets/938b78e9-e2f3-4fa6-b035-4b77a441b782)
![image](https://github.com/user-attachments/assets/8cc97505-c1a9-44a5-9f6a-caf30acffee6)

### 重现步骤

1、点击下载
2、点击资源模块中的mod
3、在搜索中输入席地而坐后出现报错

### 日志与附件

[Log2.txt](https://github.com/user-attachments/files/18265007/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/18265009/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/18265010/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/18265011/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/18265012/Log1.txt)

**Comment by xxtg666** [comment]
成功复现
![image](https://github.com/user-attachments/assets/7372b0a1-ce92-4a98-8bda-4c5f4b3f7b7a)

**Comment by xxtg666** [comment]
不好意思，忘记查重了 :(
https://github.com/Hex-Dragon/PCL2/issues/5255

**Comment by WitherStorm-WS** [comment]
我也是一个问题，现在解决了
