### ISSUE TITLE
主题颜色与启动游戏再取消后提示框“已取消启动”颜色不一致

### ISSUE THREAD

**Issue by zhyxy29** [Hex-Dragon/PCL2#5346]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

主题颜色与启动游戏再取消后提示框“已取消启动”颜色不一致，建议改成与主题同样的颜色

### 原因

（示例）
这项优化让我可以更方便地xxxx。
如果没有这项优化，我每次都必须xxxx，让操作变得很麻烦。

**Comment by Deep-Dark-Forest** [comment]
左下角提示的颜色本来就与主题色不同
