### ISSUE TITLE
没显示某个mod

### ISSUE THREAD

**Issue by wuwenjun9939** [Hex-Dragon/PCL2#5347]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/user-attachments/assets/6d6cd9cc-ffed-4744-bd7f-2f8e2cbab05b)
![image](https://github.com/user-attachments/assets/0fd4cdd9-d1b5-4bb7-8ad8-49fe9b2cf70b)

### 重现步骤

虽然cf（CurseForge）失效了，但是，能找到啊

### 日志与附件

这个怎么上传日志？？？

**Comment by shimoranla** [comment]
请检查 Modrinth 的图标，如果显示为火焰（默认图标），则为 Mod 作者没有上传图标

另外无论问题能否在日志中体现都要上传日志，认为日志无用只会增加社区负担
