### ISSUE TITLE
点击自动安装中的列表项导致启动器崩溃

### ISSUE THREAD

**Issue by fanaas** [Hex-Dragon/PCL2#535]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在pcl安装curseforge的整合包时下载失败
![屏幕截图 2022-12-06 173016](https://user-images.githubusercontent.com/88274974/205873530-f64d0cd1-20ff-4414-a87b-352b95cd2202.png)
在下载失败后点击下载栏选择版本时启动器崩溃
![屏幕截图 2022-12-06 173050](https://user-images.githubusercontent.com/88274974/205873655-2d0928ff-9ffe-40e4-ae7a-48a350c01d3c.png)
下载问题已经在hmcl启动器试过，下载正常没有问题
![Uploading 屏幕截图 2022-12-06 171829.png…]()

### 重现步骤

1、在curseforge下载整合包并丢给pcl解包
或者在下载栏搜索整合包下载
2、下载失败
3、选择下载栏，点击任意游戏版本，启动器崩溃

### 日志与附件

[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10164692/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10164694/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10164695/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10164696/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10164697/Log4.txt)

**Comment by fanaas** [comment]
下载失败后好像只有下载栏里的自动安装不能用，其他功能都正常

**Comment by LTCatt** [comment]
[17:30:24.526] [Control] 按下单选按钮：下载
[17:30:24.683] [Control] 切换主要页面：Download, -1
[17:30:24.699] [Loader] 加载器 DlOptiFineList Main 状态改变：Loading
[17:30:24.699] [Loader] 加载器 DlLiteLoaderList Main 状态改变：Loading
[17:30:24.699] [Loader] 加载器 DlFabricList Main 状态改变：Loading
[17:30:24.714] [Loader] 加载器 DlOptiFineList Official 状态改变：Loading
[17:30:24.714] [Loader] 加载器 DlLiteLoaderList Official 状态改变：Loading
[17:30:24.714] [Net] 获取网络结果：http://dl.liteloader.com/versions/versions.json，最大超时 10000
[17:30:24.714] [Loader] 加载器 DlFabricList Official 状态改变：Loading
[17:30:24.714] [Download] 刷新 Forge 推荐版本缓存开始
[17:30:24.714] [Loader] 加载器 源码获取 5631# 状态改变：Loading
[17:30:24.714] [Net] 获取网络结果：https://meta.fabricmc.net/v2/versions，最大超时 10000
[17:30:24.714] [Net] 获取客户端网络结果：https://optifine.net/downloads，最大超时 10000
[17:30:24.747] [Download] -1798645995_5630 5648#：开始，起始点 0，https://bmclapi2.bangbang93.com/forge/promos
[17:30:25.060] [Download] -1798645995_5630：文件大小 43854 B（42.8 K）
[17:30:25.092] [Download] -1798645995_5630：已完成，剩余文件 0
[17:30:25.092] [Loader] 加载器 源码获取 5631# 状态改变：Finished
[17:30:25.108] [Download] 刷新 Forge 推荐版本缓存成功
[17:30:26.321] [System] 诊断信息：
操作系统：Microsoft Windows 11 专业版 Insider Preview
剩余内存：8573 M / 16212 M
DPI：96（100%）
MC 文件夹：C:\Users\73223\AppData\Roaming\.minecraft\
文件位置：C:\Program Files (x86)\Plain Craft Launcher 2\
[17:30:26.321] 程序出现未知错误：未将对象引用设置到对象的实例。
   在 PCL.MyCard._Closure$__R18-5._Lambda$__R16(Object a0, MouseButtonEventArgs a1)
   在 PCL.MyListItem.Button_MouseUp(Object sender, MouseButtonEventArgs e)
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   在 System.Windows.UIElement.OnPreviewMouseUpThunk(Object sender, MouseButtonEventArgs e)
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   在 System.Windows.Input.InputManager.ProcessStagingArea()
   在 System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   在 System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   在 System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   在 System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by LTCatt** [comment]
Forge 安装失败是另外一个 Bug，可以再新开一个 Issue

**Comment by fanaas** [comment]
> 

我发现只有下载失败之后点击自动安装才会崩溃，其他时候应该是正常的

**Comment by LTCatt** [comment]
重现：
直接拖拽安装整合包，并触发 Forge 安装失败，此间不进行任何操作
进入下载页面，点击一个版本触发

原因完全不明，疑似是编译器 Bug

**Comment by RawDiamondMC** [comment]
草，这不就是我[#479](https://github.com/Hex-Dragon/PCL2/issues/479)的问题吗（

**Comment by LTCatt** [comment]
> 草，这不就是我[#479](https://github.com/Hex-Dragon/PCL2/issues/479)的问题吗（

确实……但这次至少知道怎么复现了

**Comment by fanaas** [comment]
龙猫大大能不能同时解锁一下我两个设备的bug反馈主题，谢谢了
1F89-45A8-FCC2-3743
ED14-C76D-B702-3A5F

**Comment by LTCatt** [comment]
第一个解锁码：582mJjhWL7rc1e+IRTStUn0/jf5kAAQK
第二个解锁码：qRGboqcdGwqK5muJC++aADAKk+glwddW
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
