### ISSUE TITLE
下载完成时出错：更新下载管理器显示失败

### ISSUE THREAD

**Issue by LBZiXL** [Hex-Dragon/PCL2#536]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

具体看截图
![image](https://user-images.githubusercontent.com/115980764/205950389-7a90eeaa-0f2c-4f51-a261-cf21822b2cf5.png)

### 重现步骤

12月29日更新：我（LBZiXL）根据后面重复的议题从新编写了重现步骤。
https://github.com/Hex-Dragon/PCL2/issues/648 的重现步骤：
一次性下载了以下游戏版本（原版）：1.4、1.5、1.6、1.7、1.8、1.9、1.10、1.11、1.12、1.13、1.14、1.15、1.16、1.17、1.18、1.19
https://github.com/Hex-Dragon/PCL2/issues/682 的重现步骤：
1.安装"GT New Horizons"整合包1.0.9.2（最早版本）
2.触发该bug
如果你出发了该bug，请在评论写下重现步骤！

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10167692/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10167694/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10167698/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10167701/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10167703/Log5.txt)

**Comment by dongge0210** [comment]
...

**Comment by dongge0210** [comment]
5个logs都大概翻了一边没找到

**Comment by LiuBinzhe** [comment]
@dongge0210 那这几个呢？
[Log4-LAPTOP-2B8IU6Q1.txt](https://github.com/Hex-Dragon/PCL2/files/10181909/Log4-LAPTOP-2B8IU6Q1.txt)
[Log5-LAPTOP-2B8IU6Q1.txt](https://github.com/Hex-Dragon/PCL2/files/10181911/Log5-LAPTOP-2B8IU6Q1.txt)
[Log1-LAPTOP-2B8IU6Q1.txt](https://github.com/Hex-Dragon/PCL2/files/10181912/Log1-LAPTOP-2B8IU6Q1.txt)
[Log1-LAPTOP-2B8IU6Q1-2.txt](https://github.com/Hex-Dragon/PCL2/files/10181914/Log1-LAPTOP-2B8IU6Q1-2.txt)
[Log2-LAPTOP-2B8IU6Q1.txt](https://github.com/Hex-Dragon/PCL2/files/10181915/Log2-LAPTOP-2B8IU6Q1.txt)
[Log3-LAPTOP-2B8IU6Q1.txt](https://github.com/Hex-Dragon/PCL2/files/10181916/Log3-LAPTOP-2B8IU6Q1.txt)

**Comment by LiuBinzhe** [comment]
我没有log了

**Comment by LTCatt** [comment]
那我只能勉强看看，没有 log 的话要修不太可能就是了……

**Comment by LiuBinzhe** [comment]
。。

**Comment by LTCatt** [comment]
我比较确定这确实是存在的 Bug，应当需要 **当不在下载管理页面时下载任务完成** 触发。
但我不确定具体的触发条件，谁看看能不能找到个稳定的重现方法？

**Comment by youzi-2333** [comment]
感觉跟下载页面没啥关系，毕竟是ModAnimation里面报出来的NullReferenceException，得看代码里哪出现null了（

**Comment by LBZiXL** [comment]
问一下，那个赢藏主题只有在内群反馈bug才会解锁吗？我都在Github反馈几个bug了

**Comment by youzi-2333** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }

**Comment by LBZiXL** [comment]
有人好像把重现步骤研究出来了 https://github.com/Hex-Dragon/PCL2/issues/595

**Comment by RawDiamondMC** [comment]
> 我比较确定这确实是存在的 Bug，应当需要 **当不在下载管理页面时下载任务完成** 触发。 但我不确定具体的触发条件，谁看看能不能找到个稳定的重现方法？

在下载页面触发的（
可能和显示哪个页面无关？

**Comment by WForst-Breeze** [comment]
> 问一下，那个赢藏主题只有在内群反馈bug才会解锁吗？我都在Github反馈几个bug了

直接在label为“完成”的你的反馈下把你的识别码发出来然后询问管理员就可以啦

**Comment by LBZiXL** [comment]
谢谢

**Comment by RawDiamondMC** [comment]
草，刚想发稳定卡bug方式（

**Comment by LTCatt** [comment]
> 草，刚想发稳定卡bug方式（

@RawDiamondMC  你也可以发……

**Comment by LTCatt** [comment]
先尝试进行了修复，不确定修没修掉，看下个版本好没好吧……
