### ISSUE TITLE
使用PCL2 Dev版本下载原版Minecraft 1.19.2时显示下载速度与剩余文件数为零2333

### ISSUE THREAD

**Issue by lgylxyyy** [Hex-Dragon/PCL2#541]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在下载游戏（版本：1.19.2）时发现下载速度和剩余文件数为零耶2333另外Windows 11滴Windows安全中心说Dev版本的PCL2是特洛伊木马耶114514
![BUG](https://user-images.githubusercontent.com/103111585/206330170-c5b92aeb-e765-42d0-aa42-f9dee8707a73.png)
![报毒](https://user-images.githubusercontent.com/103111585/206330225-f3533b30-5fc0-4d1f-80db-536216b48d94.png)

### 重现步骤

不知道，我就是正常下载的时候出现的、、、我又试着下载了个快照版也是这样///有可能是我挂网课网络不好。。。但是///文件一直在下载呀\\\

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10181234/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10181235/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10181236/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10181237/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10181238/Log5.txt)

**Comment by Big-Cake-jpg** [comment]
> 在下载游戏（版本：1.19.2）时发现下载速度和剩余文件数为零耶2333
请使用标准语言进行问题描述

> 另外Windows 11滴Windows安全中心说Dev版本的PCL2是特洛伊木马耶114514
该问题属于 Microsoft Defender 的误报，请尝试添加排除项。

**Comment by dongge0210** [comment]
所谓的白名单
也可以给微软发反馈

**Comment by dongge0210** [comment]
我也是Dev测试  bulid 25252

**Comment by dongge0210** [comment]
了解更多信息里有选项可以使他正常使用（保留在此设备上）

**Comment by bwtx2022** [comment]
WD 报毒是微软的问题，建议添加排除项

同时建议在下载时耐心等一等。

如果还是有问题请以更加正式的语言提交 Issue 。
