### ISSUE TITLE
optifine无法正常下载

### ISSUE THREAD

**Issue by Mrpotatopluto** [Hex-Dragon/PCL2#544]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

已确认我的启动器为最新版且我的网络环境没有问题，在下载安装optifine时出现错误。这种错误似乎并不是随时都可发生，三小时后我再次尝试便可下载成功。然而还是会时不时出现这样的问题且我确定不是我的网络环境所导致。在询问PCL内群管理员后前来反馈。附件已附PCL2log日志文件。

### 重现步骤

1、点击下载
2、选择下载1.16.5
3、向下滚，选择optifine版本
4、点击 开始下载
5、发生下载失败

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10183205/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10183207/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10183208/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10183209/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10183210/Log2.txt)

**Comment by bwtx2022** [comment]
你这个 Log 看起来并没有包含下载 OptiFine 的错误。

尝试下载失败以后不要重启启动器，直接上传 Log1-5 。

**Comment by Mrpotatopluto** [comment]
下载optifine出现的错误复现是有困难的。他总会偶然出现。正如我所述，三小时后便恢复正常下载。但我仍保留了一份发生错误时的PCL2截图，已通过邮箱回复给您

**Comment by Mrpotatopluto** [comment]
随github附上PCL2截图








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Hex-Dragon/PCL2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月8日(星期四) 晚上8:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Hex-Dragon/PCL2] optifine无法正常下载 (Issue #544)





 
你这个 Log 看起来并没有包含下载 OptiFine 的错误。
 
尝试下载失败以后不要重启启动器，直接上传 Log1-5 。

**Comment by bwtx2022** [comment]
> 下载optifine出现的错误复现是有困难的。他总会偶然出现。正如我所述，三小时后便恢复正常下载。但我仍保留了一份发生错误时的PCL2截图，已通过邮箱回复给您

在这里上传，不要发邮箱。

**Comment by LTCatt** [comment]
如果没有重现方式的话我没法修复……
如果你无法再次重现这个 Bug 那我也只能关了……

**Comment by LTCatt** [comment]
还在吗？
