### ISSUE TITLE
自动生成 options.txt 功能兼容 YOSBR Mod

### ISSUE THREAD

**Issue by GodGun968** [Hex-Dragon/PCL2#545]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过(应该没有)。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

整合包:Fabulously Optimized
生成的options.txt会使yosbr(mod)判断为有配置文件,所以无法释放默认设置

### 原因
关闭自动设置中文然后把游戏窗口改为游戏默认可以解决此问题,但是更希望能兼容一下
可以先读取yosbr文件夹中的的配置,再在其基础上更改/添加。
这项优化使我更方便地使用整合包。
如果没有这项优化，我每次安装整合包都必须手动设置，让操作变得很麻烦。

**Comment by LTCatt** [comment]
我看了看，这个不太应该是我这边处理的。
应该向 Mod 开发者交反馈，让它从 “如果文件存在就不复制” 改为 “合并两个文件”。
