### ISSUE TITLE
forge安装失败

### ISSUE THREAD

**Issue by fanaas** [Hex-Dragon/PCL2#549]
pcl安装forge整合包安装失败，其他启动器没有此问题
![屏幕截图 2022-12-09 111519](https://user-images.githubusercontent.com/88274974/206616271-a2071ea2-ef9b-40df-b017-6a
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10191523/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10191524/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10191525/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10191526/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10191527/Log5.txt)
bfe6d439f7.png)

**Comment by fanaas** [comment]
我通过修改版本名字可以正常下载

**Comment by LTCatt** [comment]
具体怎么修改版本名字就行了？


---
开始安装 Forge：--add-exports cpw.mods.bootstraplauncher/cpw.mods.bootstraplauncher=ALL-UNNAMED -Doolloo.jlw.tmpdir="C:\Users\73223\AppData\Roaming\PCL" -cp "C:\Users\73223\AppData\Local\Temp\PCL\Cache\forge_installer.jar;C:\Users\73223\AppData\Local\Temp\PCL\Cache\Code\ForgeInstall-40.1.69_24171" -jar "C:\Users\73223\AppData\Roaming\PCL\JavaWrapper.jar"  com.bangbang93.ForgeInstaller "C:\Users\73223\AppData\Local\Temp\PCL\Install\Better MC [PLUS] 1.18.2\
----
WARNING: Unknown module: cpw.mods.bootstraplauncher specified to --add-exports
There is no minecraft installation at: C:\Users\73223\AppData\Local\Temp\PCL\Install\Better MC [PLUS] 1.18.2"
false

**Comment by fanaas** [comment]
我认为
当名称为纯数字时下载成功，同时包含数字和空格下载失败
纯字母或符号且总位数小于等于3位成功，高于3位失败，包含空格且小于3位也失败
下载错误方式也不太一样
不包含空格仅字母符号的时候高于3位时的错误原因和包含空格时的错误原因也不一样
我把日志文件一并上传，如果日志只能看见最近一次的下载情况我就分次再上传一次
![屏幕截图 2022-12-09 173120](https://user-images.githubusercontent.com/88274974/206670769-7e015ad0-059a-4f66-ab84-5a8056699bfe.png)
![屏幕截图 2022-12-09 173145](https://user-images.githubusercontent.com/88274974/206670781-547f2bf0-5191-4175-89de-270574e0c2ff.png)
![屏幕截图 2022-12-09 173201](https://user-images.githubusercontent.com/88274974/206670785-1d0fdb02-e5ac-4b44-9fc5-f8846383a512.png)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10193493/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10193494/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10193496/Log5.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10193498/Log2.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10193500/Log1.txt)

**Comment by LTCatt** [comment]
我没法重现，可能得远程处理一下。
加我 QQ 1043137532，验证消息就说是 GitHub 的这个 Issue。

**Comment by fanaas** [comment]
问题通过重装Java解决了
