### ISSUE TITLE
PCL启动器被覆盖后会出现BUG

### ISSUE THREAD

**Issue by Xiaoganghei** [Hex-Dragon/PCL2#550]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

有一天，我的测试版PCL2意外消失了……（PCL2启动器一直在白名单里，不存在消失原因，但我还是会时常消失我的测试版……但是所有消失的启动器都在那一个文件夹中……）
起初我还没认为有什么事，然后我在PCL内群又下了一个测试版（在那之前我原本存放测试版的文件夹被我放进去了一个正式版的PCL2，版本为RELEASE2.3.0(257.50))然后，就出现了我意想不到的事情，我照常把原来的正式版PCL2删掉，把测试版的重新导入，但是PCL2测试版就出现了BUG……

https://user-images.githubusercontent.com/118163634/206593518-5f83ea6b-80b6-4ed7-99cf-492d9a63ebc3.mp4

详细就在这个视频里
没错，测试版PCL2直接就变成了正式版PCL2与测试版PCL2的结合体……

### 重现步骤

先进行删除测试版PCL2（应该这样也能起到用途吧=。=）
将原版PCL2加进去
进行启动，确保他是正式版（应该是这时将正式版文件导入了测试版PCL2文件中，造成PCL2文件混乱）
再将原版PCL2删掉，换为PCL2测试版

### 日志与附件

这里没什么可说的，就写一些必要状况吧。（应该不需要log吧……）
1.从始至终PCL正式版一直为RELEASE2.3.0(257.50)
2.从始至终PCL测试版一直为Snapshot 2.2.14（256.0）
3.在我的正式版中，我有将启动器改名。（但应该跟这无关）名字为：Plain Craft Launcher 2(创造101）（因为这是我在很久之前还没赞助时使用的，而当时我并不会在PCL测边框中添加其他快捷方式……）
4.我那个有问题的文件夹名字就是内测群中解压后的名字并未改变，且我的文件夹也没有被黑客或电脑木马攻击之类的，否则为什么只攻击我那一个文件夹，我有更多可以利用的更有用的东西啊……

最后，拜托龙猫，救救孩子吧……Orz

**Comment by LTCatt** [comment]
你的这个 PCL2 是老版本的，重新更新一下就行。

**Comment by Xiaoganghei** [comment]
哦哦
谢
