### ISSUE TITLE
impact的minecraftJava选择错误

### ISSUE THREAD

**Issue by FFDVDGD** [Hex-Dragon/PCL2#552]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃不是 PCL2 的原因，请 **不要** 提交反馈。你可以在 QQ 群里或者论坛找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是游戏本身的问题，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

启动impact1.16.5时选择过高的Java，实际需要Java8，手动选择Java8时正常启动。

### 错误报告、日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10191758/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10191759/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10191760/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10191761/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10191762/Log5.txt)

**Comment by Gcatawa** [comment]
好家伙，impact不是作弊mod吗？支持1.8.9的有吗给我来一份（doge），我要开杀戮光环（逃

**Comment by LTCatt** [comment]
我没有这个端，需要一个具体的兼容 java 范围我才能做修复（例如 Java 8~15 这种非常精确的范围）。以及不同大 MC 版本下，所需要的 Java 范围又有哪些。

**Comment by FFDVDGD** [comment]
1.16.5需要Java8

**Comment by LTCatt** [comment]
> 1.16.5需要Java8

需要一个具体的 **范围** ，我知道需要 Java 8，但更高的 Java 例如 9 啊 10 啊啥的最高到多少可以启动？

还有 1.16.5 以外的其他 MC 版本又需要什么范围？

如果你搞不懂可以让其他人去测试。我没有这个端。

**Comment by FFDVDGD** [comment]
那我试试

**Comment by FFDVDGD** [comment]
那我试试，不过真的有人用9、10之类的吗

**Comment by lim114514** [comment]
https://impactclient.net/
Impact 官网，热乎的。
除了Impact 非 Forge Mod 的版本，其他魔改客户端也会出现这种问题...
我的建议是增加一个类型（魔改客户端），提醒用户这是魔改客户端，需要自行选择版本。
顺带一提，魔改客户端大部分是作弊端，其实没必要管......

**Comment by lim114514** [comment]
> 好家伙，impact不是作弊mod吗？支持1.8.9的有吗给我来一份（doge），我要开杀戮光环（逃
纪狗气死我了（

**Comment by LTCatt** [comment]
> https://impactclient.net/ Impact 官网，热乎的。 除了Impact 非 Forge Mod 的版本，其他魔改客户端也会出现这种问题... 我的建议是增加一个类型（魔改客户端），提醒用户这是魔改客户端，需要自行选择版本。 顺带一提，魔改客户端大部分是作弊端，其实没必要管......

官网没有找到所需 Java 版本的部分。
我确实可以不管魔改端，但那样我会被挂圈冲塔——并且这事情已经发生过了，我也是被逼的。

**Comment by lim114514** [comment]
> > https://impactclient.net/ Impact 官网，热乎的。 除了Impact 非 Forge Mod 的版本，其他魔改客户端也会出现这种问题... 我的建议是增加一个类型（魔改客户端），提醒用户这是魔改客户端，需要自行选择版本。 顺带一提，魔改客户端大部分是作弊端，其实没必要管......
> 
> 官网没有找到所需 Java 版本的部分。 我确实可以不管魔改端，但那样我会被挂圈冲塔——并且这事情已经发生过了。我也是被逼的。

6

**Comment by LTCatt** [comment]
一周了，还在么……

**Comment by FFDVDGD** [comment]
还是懒，龙猫把这个issue删了吧，单独给出问题的版本设置就好了

**Comment by lim114514** [comment]
> 一周了，还在么……

?6
