### ISSUE TITLE
支持自动安装 Rift

### ISSUE THREAD

**Issue by RawDiamondMC** [Hex-Dragon/PCL2#559]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

自动安装界面增加Rift与Quilt（看2.4.3更新日志里没有所以加上了）。

### 原因

我需要制作Rift整合包。

**Comment by bwtx2022** [comment]
Rift 好像都死了罢

**Comment by bwtx2022** [comment]
关于 Quilt ，详见 #49

**Comment by RawDiamondMC** [comment]
> Rift 好像都死了罢

但是死了也不影响我用啊（

**Comment by RawDiamondMC** [comment]
LiteLoader不也支持吗（
