### ISSUE TITLE
更好的个性化自定义主题

### ISSUE THREAD

**Issue by TingChangHang** [Hex-Dragon/PCL2#562]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

在启动器个性化的自定义主题里添加自动变色（让色调渐变一直动）

### 原因

我想要这个功能增加启动器美观程度，没有的话自定义主题就怪怪的

**Comment by LiuBinzhe** [comment]
感觉龙猫那边......不会做......（毕竟给手动安装包添加缩回动画TA都那个不想......）
