### ISSUE TITLE
离线模式通过设置他人玩家名进入服务器数据一致

### ISSUE THREAD

**Issue by LY-muyan** [Hex-Dragon/PCL2#563]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

离线模式可通过输入他人的玩家名（离线玩家和正版账号玩家都行）进行游玩服务器，并且物品、服务器op权限等数据都和原玩家的数据一致
![屏幕截图 2022-12-11 012546](https://user-images.githubusercontent.com/72865570/206867840-9231b61b-febd-438c-a56b-3c1da9396386.png)
![屏幕截图 2022-12-11 012539](https://user-images.githubusercontent.com/72865570/206867845-bffb16d4-334e-4d17-8cad-6e8ccd011956.png)

### 重现步骤

1.选择离线
2.输入要游玩的玩家名
3.进入游戏

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10200620/Log3.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10200621/Log2.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10200622/Log1.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10200623/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10200624/Log5.txt)

**Comment by LY-muyan** [comment]
以上测试玩家名和服务器皆是我自己的私人服务器

**Comment by LTCatt** [comment]
与启动器无关。
离线模式本来就是这样的……

**Comment by LY-muyan** [comment]
这样啊.....那岂不是没法解决这个问题😂
