### ISSUE TITLE
能不能把崩溃信息写明白点啊喂

### ISSUE THREAD

**Issue by Sinetian** [Hex-Dragon/PCL2#564]
### 检查项

- [ ] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

最近我在KOOK上的一个群里看崩溃，突然发现，那是PCL的日志，结果看完之后~~血压飙升~~崩溃地发现，日志里竟然没写出来Java具体版本是啥……瞬间炸掉

### 原因

这项优化可以让人更方便的看懂，谢谢

**Comment by LTCatt** [comment]
我不知道你看到的是啥，但启动器日志里是有这一条的。
