### ISSUE TITLE
添加 同时启用"强制使用unicode字体" 复选框

### ISSUE THREAD

**Issue by GTEMYee** [Hex-Dragon/PCL2#565]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

![ForceUnicodeCheckBox](https://user-images.githubusercontent.com/117887221/206883261-54de79b8-6e16-44f3-858d-1d37afa6883e.jpg)
在"游戏语言"一行添加 同时启用"强制使用unicode字体" 复选框
并且在 默认设置中文 复选框不勾选时, 同时启用"强制使用unicode字体" 复选框不能勾选

### 原因

某些资源包要求禁止"强制使用unicode字体"
在默认设置中文情况下下载完新版本后直接启动只需要设置中文而不需要手动禁用"强制使用unicode字体"
我个人认为启用"强制使用unicode字体"已经不是Minecraft正常的样子了
甚至想去掉"强制使用unicode字体"这个按钮并锁定禁用"强制使用unicode字体"
[同时启用"强制使用unicode字体"]复选框在空配置下勾不勾选看大家的意见
(没错,我就是跟"强制使用unicode字体"有仇,但是1.12.2及以下版本可以理解)

**Comment by lim114514** [comment]
有些人喜欢用强制Unicode字体，还有一些人不喜欢...我之前提交过😂

**Comment by LTCatt** [comment]
讨论详见 [#546 ](https://github.com/Hex-Dragon/PCL2/discussions/546#discussioncomment-4364439)
