### ISSUE TITLE
在不支持 Quilt 的版本依然可以搜到 Quilt Mod

### ISSUE THREAD

**Issue by Louis-ZYH** [Hex-Dragon/PCL2#566]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

一、
![image](https://user-images.githubusercontent.com/115140320/206887916-4b67bd12-2376-4166-8d5a-2f0beffa5358.png)
如图，1.12.2不支持Quilt，但在Mod加载器选择项中仍然显示Quilt选项；
二、
![image](https://user-images.githubusercontent.com/115140320/206887981-6561afb5-8d88-4ab9-8a6f-0c7b864ce4cc.png)
![image](https://user-images.githubusercontent.com/115140320/206887968-b05af712-432c-441b-a8e9-c533c49392e3.png)
![image](https://user-images.githubusercontent.com/115140320/206888072-126337ae-64b5-49dc-a123-fa829e8c81e3.png)
如图，1.12.2+Quilt的搜索选项搜索出了很多Mod（这里我随便选了一个Mod），但Mod下标题显示为“Fabric 1.12.2+”，且在PCL2的1.12.2自动下载选项中并未提供Fabric和Fabric API的下载（提示没有可用版本）。

### 重现步骤

此 bug 并非偶发，只需要在Mod下载页的“版本”一栏选择“（任意一个不支持Quilt的MC版本，例：1.12.2）+Quilt”即可。

### 日志与附件

[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10201534/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10201535/Log5.txt)
[Log.txt](https://github.com/Hex-Dragon/PCL2/files/10201536/Log.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10201537/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10201538/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10201539/Log3.txt)

**Comment by Louis-ZYH** [comment]
@LTCatt
识别码 E2E6-471A-4F81-D052
求活跃橙解锁码，谢谢！

**Comment by Light-Beacon** [comment]
> @LTCatt 识别码 E2E6-471A-4F81-D052 求活跃橙解锁码，谢谢！

YNwJuNL14sFOibwhLy0b9JGV1G5SMGGA
