### ISSUE TITLE
关于版本隔离的提示

### ISSUE THREAD

**Issue by lim114514** [Hex-Dragon/PCL2#567]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

在设置中增加“不再提示未开启版本隔离”。

### 原因

我需要这个功能，有时候下载游戏，会弹出版本隔离的提示，这就很烦...

**Comment by LTCatt** [comment]
算了算了，没啥必要 Orz……
这种主要还是考虑到设置不能太臃肿，如果什么小问题都要加一个设置的话，设置就会过度繁杂和臃肿了，所以抱歉）

**Comment by bwtx2022** [comment]
我觉得没有理由不开启版本隔离罢（

除非你只玩原版（
