### ISSUE TITLE
皮肤导入读取有误

### ISSUE THREAD

**Issue by dangdang513** [Hex-Dragon/PCL2#568]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 重现步骤

1、点击设置
2、选择游戏
3.导入皮肤

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10201643/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10201644/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10201645/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10201646/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10201647/Log1.txt)

**Comment by LTCatt** [comment]
#424

**Comment by dangdang513** [comment]
> ### 检查项
> * [x] 我已点击 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)`设置 → 启动器 → 检查更新`
> * [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。
> 
> ### 描述
> ### 重现步骤
> 1、点击设置 2、选择游戏 3.导入皮肤
> 
> ### 日志与附件
> [日志 2.txt](https://github.com/Hex-Dragon/PCL2/files/10201643/Log2.txt) [日志 3.txt](https://github.com/Hex-Dragon/PCL2/files/10201644/Log3.txt) [日志 4.txt](https://github.com/Hex-Dragon/PCL2/files/10201645/Log4.txt) [日志 5.txt](https://github.com/Hex-Dragon/PCL2/files/10201646/Log5.txt) [日志 1.txt](https://github.com/Hex-Dragon/PCL2/files/10201647/Log1.txt)

随便找了一个，

> ### 检查项
> * [x] 我已点击 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)`设置 → 启动器 → 检查更新`
> * [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。
> 
> ### 描述
> ### 重现步骤
> 1、点击设置 2、选择游戏 3.导入皮肤
> 
> ### 日志与附件
> [日志 2.txt](https://github.com/Hex-Dragon/PCL2/files/10201643/Log2.txt) [日志 3.txt](https://github.com/Hex-Dragon/PCL2/files/10201644/Log3.txt) [日志 4.txt](https://github.com/Hex-Dragon/PCL2/files/10201645/Log4.txt) [日志 5.txt](https://github.com/Hex-Dragon/PCL2/files/10201646/Log5.txt) [日志 1.txt](https://github.com/Hex-Dragon/PCL2/files/10201647/Log1.txt)

**Comment by dangdang513** [comment]
有可能是我的皮肤文件有问题
