### ISSUE TITLE
允许在版本管理中添加自定义的版本分类

### ISSUE THREAD

**Issue by RawDiamondMC** [Hex-Dragon/PCL2#569]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

可以新建版本分类标签，同时把“可安装mod的版本”改成复选框形式。

### 原因

可以将Fabric，Forge分开，或把同一整合包的不同版本归到同一类。
改复选框是因为同时分类Fabric（自定义标签）和可安装mod的版本目前应该是不行的罢（有更好的方法也行）

**Comment by LTCatt** [comment]
考虑到制作难度和适用范围暂不处理，目前一年半得票数不到 500，应该也轮不上它了……

**Comment by RawDiamondMC** [comment]
> 考虑到制作难度和适用范围暂不处理，目前一年半得票数不到 500，应该也轮不上它了……

😭
