### ISSUE TITLE
在 下载 最大线程数 后增加自动下载线程

### ISSUE THREAD

**Issue by LBZiXL** [Hex-Dragon/PCL2#572]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

我每次调下载线程数都很迷茫，不知道调到多少。调少了，害怕下载速度变慢；调多了，害怕反而更卡顿。希望增加一个自动线程数选项，让PCL在不造成卡顿的情况下最大化下载速度。

### 原因

这项优化让我可以更方便地调整最大线程数。
如果没有这项优化，我每次都必须手动调，让操作变得很麻烦。

**Comment by WForst-Breeze** [comment]
已初步确认，感谢您的反馈~
但我**个人认为**这个功能其实意义不大，因为PCL2已经很**明确**告诉用户了64线程一般就够用了qwq
![image](https://user-images.githubusercontent.com/110760354/206968072-3ab8c65e-d72e-4949-b7d4-4115651d41f0.png)

**Comment by LTCatt** [comment]
推荐 64。

**Comment by LBZiXL** [comment]
哦
