### ISSUE TITLE
自定义功能隐藏快捷键

### ISSUE THREAD

**Issue by RawDiamondMC** [Hex-Dragon/PCL2#578]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在功能隐藏旁边增加自定义按键选项，默认为F12。

### 原因

1、可以换成顺手，好记的按键。
2、即使隐藏“功能隐藏”，知道快捷键的人也能把它恢复显示。

**Comment by WForst-Breeze** [comment]
已初步确认，感谢您的反馈~
但貌似并没有太大意义其实我个人觉得……看龙猫怎么想吧qwq
