### ISSUE TITLE
在下载管理和音乐播放按钮上添加一个进度条

### ISSUE THREAD

**Issue by WForst-Breeze** [Hex-Dragon/PCL2#580]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

如题，当PCL2正在下载文件或播放音乐时，在右下角的圆形按钮上添加一个环形进度条以清晰显示目前的下载进度或音乐的时间！

### 原因

部分用户可能需要，此功能可以清晰明了地显示出进度信息，免去了看下载进度还需要切到下载管理界面的麻烦
此功能曾在金数据的反馈中被提及，在这里搬过来qwq！

**Comment by YUANXINGlingyun** [comment]
忽然发现问题,这玩意优先级 label 哪去了
@LTCatt

**Comment by Chiloven945** [comment]
就我觉得如果真的加个进度条会很丑吗（

**Comment by WForst-Breeze** [comment]
> 就我觉得如果真的加个进度条会很丑吗（

到时候再具体看看啦，如果不美观当然会做调整或是放弃制作……qwq

**Comment by LTCatt** [comment]
![image](https://user-images.githubusercontent.com/40348278/230663813-98b4f5ba-3090-49a2-930d-9eb35c1ec789.png)

**Comment by Chiloven945** [comment]
说实话我感觉一个深色圆形慢慢放大是不是更好点
还有这个颜色应该可以调换一下深色感觉是已完成而浅色感觉是空的（

**Comment by iPodtouch6557** [comment]
> 说实话我感觉一个深色圆形慢慢放大是不是更好点 还有这个颜色应该可以调换一下深色感觉是已完成而浅色感觉是空的（

ui会冲突……而且也不好看
