### ISSUE TITLE
1.19.3Forge44.0.18安装错误

### ISSUE THREAD

**Issue by RawDiamondMC** [Hex-Dragon/PCL2#584]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在后台安装时弹出标题为“JavaWrapper.jar”（00II00又要修bug了）的错误弹窗（忘记截图了，所以没有内容）
然后PCL2报错：
![屏幕截图 2022-12-13 195540](https://user-images.githubusercontent.com/112449001/207311403-7737c55d-eaaa-47f9-a534-c8c3339d0f10.png)
注：这是在1.19.2-forge-43.2.0安装完毕后截图的，但bug发生时1.19.2-forge-43.2.0没有发生错误。

### 重现步骤

同时下载1.19.3Forge44.0.18和1.19.2Forge43.2.0（还没有测试是否能复现，如果有需要再测试）

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10217561/Log1.txt)

**Comment by RawDiamondMC** [comment]
我绝对不在点炒饭.jpg

**Comment by LTCatt** [comment]
是什么弹窗啊？

**Comment by RawDiamondMC** [comment]
> 是什么弹窗啊？

只记得是错误弹窗了（
当时忘记截图，但标题肯定是JavaWrapper.jar。
JavaWrapper.jar有没有什么扔日志的地方我去翻翻？（

**Comment by RawDiamondMC** [comment]
> > 是什么弹窗啊？
> 
> 只记得是错误弹窗了（ 当时忘记截图，但标题肯定是JavaWrapper.jar。 JavaWrapper.jar有没有什么扔日志的地方我去翻翻？（

内容能看出来是java报错内容，但是看不懂（

**Comment by RawDiamondMC** [comment]
> ……你可以放截图或者把内容发出来都行啊

都说了忘记截图了，怎么发啊，难不成重新变一个出来？
我先尝试复现（结果把[#536](github.com/Hex-Dragon/PCL2/issues/584)给复现出来了...）

**Comment by RawDiamondMC** [comment]
Forge版本44.0.18不见了？现在只有44.0.0和44.0.1

**Comment by RawDiamondMC** [comment]
@LTCatt 问一下JavaWrapper.jar在下载游戏的时候是干嘛用的，我看看能不能推理出来（毕竟bug发生时下载了很多版本，逐一排查太慢了）

**Comment by RawDiamondMC** [comment]
复现了！
虽然不知道是怎么复现的...

**Comment by RawDiamondMC** [comment]
woc又测出来其他bug...

**Comment by LTCatt** [comment]
所以你复现了倒是给个截图啊……
它的作用去看 @00ll00 的公开库就行

**Comment by RawDiamondMC** [comment]
> 所以你复现了倒是给个截图啊…… 它的作用去看 @00ll00 的公开库就行

我tm测出来第二种报错信息然后又忘记截图了......
等一下等一下.gif

**Comment by RawDiamondMC** [comment]
突然就测不出来了，明天再测

**Comment by RawDiamondMC** [comment]
奶奶滴，礼拜四开始不舒服，昨天干脆直接阳性了（恼）
今天我测一测

**Comment by LTCatt** [comment]
超时先关了，如果要补充可以继续在下面补充……
