### ISSUE TITLE
打开版本隔离后下载mod不会自动打开mods文件夹，而是.minecraft文件夹

### ISSUE THREAD

**Issue by LBZiXL** [Hex-Dragon/PCL2#585]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如题，在最新快照2.4.4中打开版本隔离后下载mod不会自动打开mods文件夹，而是.minecraft文件夹

### 重现步骤

1、点击一个mod
2、弹出的资源管理器窗口不是mods文件夹

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10218571/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10218572/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10218573/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10218575/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10218576/Log5.txt)

**Comment by Big-Cake-jpg** [comment]
无法复现，请确认你在主页选择的版本已安装 Mod 加载器。

**Comment by Big-Cake-jpg** [comment]
```
[21:47:05.618] [Download] 由于当前版本不兼容，使用当前的 MC 文件夹作为默认下载位置
```

**Comment by LBZiXL** [comment]
我确认已经安装了mod加载器，且问题是在更新PCL后出现的，之前一直打开的是mods文件夹

**Comment by Big-Cake-jpg** [comment]
还有人能尝试复现这个 Bug 吗，我这里无法复现。

**Comment by Louis-ZYH** [comment]
emmm……

**Comment by LTCatt** [comment]
你安装的版本的 Mod 加载器和版本号都要和你选择的 Mod 匹配，否则就不会选择该版本文件夹。
考虑到无法复现，暂时关闭。
