### ISSUE TITLE
MOD下载热力系列名称显示错误

### ISSUE THREAD

**Issue by Nothingness-Void** [Hex-Dragon/PCL2#589]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

热力系列模组显示名称均为热力膨胀
![image](https://user-images.githubusercontent.com/55913486/207405102-8f664270-fa1f-4dec-82ec-8224047b253f.png)

### 重现步骤

1、点击下载
2、搜索1.18.2 forge版本的 热力系模组
3、显示的多个不同模组均为热力膨胀

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10220638/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10220639/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10220641/Log3.txt)

**Comment by WForst-Breeze** [comment]
已初步确认，感谢您的反馈~
（这些模组的英文名称貌似也跟curseforge上的不一样呢……qwq
