### ISSUE TITLE
无法更改离线模式皮肤（1.19.3）

### ISSUE THREAD

**Issue by WForst-Breeze** [Hex-Dragon/PCL2#590]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在1.19.3版本中，离线模式玩家自定义皮肤资源包显示不兼容，且安装后仍无法正常显示皮肤
（HMCL已测试，无此问题）

### 重现步骤

1. 选择离线登录
2. 在设置-游戏-离线皮肤 选择自定义皮肤
3. 启动游戏版本 1.19.3（其他版本没有发现这个问题）
4. 进入游戏
5. 在 选项-资源包 发现游戏提示资源包不兼容
6. 手动安装 PCL2 Skin 资源包
7. 问题复现，皮肤仍为9个官方离线模式皮肤中的一个

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10223088/Log1.txt)
原始讨论： #588

**Comment by Big-Cake-jpg** [comment]
已确认 Bug 存在，感谢反馈。

**Comment by youzi-2333** [comment]
我去，差点就发起新issue了，还好我搜索一下……

**Comment by ComputerCPT** [comment]
如果等不及的话就把自定义皮肤材质中的pack.mcmeta 里的"pack_format"后的值从9改成12应该就可以用了
1.19.3的"pack_format"后的值是12，而不是启动器中的错误值9

**Comment by HANTON114514** [comment]
怎么改？

**Comment by HANTON114514** [comment]
ren pack.txt pack.mcmeta:你们今天谁也别拦着我，**今天就要干死这个pack.mcmeta

**Comment by HANTON114514** [comment]
《论改完12保存后又变9这件事》

**Comment by Sawdustlov** [comment]
为什么我改成12皮肤还是没变#？

**Comment by youzi-2333** [comment]
先确认保存了没有，如果保存了还没有成功，可能是因为1.19.3对玩家的改变，导致mc认为这是1.19.2的，然后把mcmeta自动改掉……
