### ISSUE TITLE
下载已存在文件查找失败：字符串的长度不能为零。

### ISSUE THREAD

**Issue by RawDiamondMC** [Hex-Dragon/PCL2#600]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

（我大概是有什么bug体质吧...）
开启启动器就崩溃了。
（开启了调试模式与添加延迟）

### 重现步骤

1、打开PCL2
2、崩溃

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10228322/Log2.txt)

**Comment by WorldHim** [comment]
虽然但是，有没有可能是你这个PCL路径的问题 `C:\$$$$\`

**Comment by LTCatt** [comment]
很奇怪……
你能不能重现这个 Bug？

**Comment by miner233** [comment]
我把 PCL2 放到了和你一样路径当中（C:\$$$$），不能复现此 Bug。

**Comment by RawDiamondMC** [comment]
> 我把 PCL2 放到了和你一样路径当中（`C:\$$$$`），不能复现此 Bug。

我怀疑原因是因为官方启动器目录下有一个错误的版本？@LTCatt

**Comment by LTCatt** [comment]
额，我是说你能不能重现？我重现不出来，如果你也没法重现我就没法修……

**Comment by RawDiamondMC** [comment]
> 额，我是说你能不能重现？我重现不出来，如果你也没法重现我就没法修……

因为这个issue是一个月前的，当时是打开就出现
现在我试一下复现（

**Comment by RawDiamondMC** [comment]
草，这bug不见了
算了先关掉吧谁复现出来再开（
