### ISSUE TITLE
littleskin登录皮肤不同步

### ISSUE THREAD

**Issue by In-clear-water-and-fog** [Hex-Dragon/PCL2#601]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

使用littleskin登录游戏，皮肤不同步，刷新没有用

### 重现步骤

1、打开游戏
2、加入世界
3不显示皮肤，且以确定mod不冲突

### 日志与附件

无

**Comment by LBZiXL** [comment]
这应该是littleskin的问题，不是PCL

**Comment by LBZiXL** [comment]
你试试HMCL启动器

**Comment by LTCatt** [comment]
请补充截图和日志，无什么无……

**Comment by In-clear-water-and-fog** [comment]
[](url)
![5NK)YVNZGW_5N4}9~G6V@_M](https://user-images.githubusercontent.com/112240825/207991726-0fb87e27-8c87-45b3-856c-85d9330e832f.png)
![_0MHL3Z@A_7(4Z$E5ZN2FF4](https://user-images.githubusercontent.com/112240825/207991734-edb407f3-caf8-4786-81eb-18cfe362fcd0.png)
![FA2NB0 AIP`VJ29JIZH5E`I](https://user-images.githubusercontent.com/112240825/207991824-60f76df8-a308-45ed-bb56-50bdbf0dfbf1.png)

**Comment by In-clear-water-and-fog** [comment]
就这样的

**Comment by LTCatt** [comment]
![image](https://user-images.githubusercontent.com/40348278/208039272-cae6e38e-8774-4de7-af6c-d1d568a65f53.png)

你需要右键选择刷新。

**Comment by wyy9sp** [comment]
> ![image](https://user-images.githubusercontent.com/40348278/208039272-cae6e38e-8774-4de7-af6c-d1d568a65f53.png)
> 
> 你需要右键选择刷新。

我也遇到了类似的问题，在little skin设置了新皮肤，而在pcl上显示的还是原来的皮肤，刷新也没有变化

**Comment by MoYuan-CN** [comment]
提交你的 PCL 启动器日志，游戏内的截图，使用 CustomSkinLoader (CSL) 的情况
