### ISSUE TITLE
PCL闪退后Plain Craft Launcher 2.exe被删除

### ISSUE THREAD

**Issue by creeper2556** [Hex-Dragon/PCL2#608]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

PCL启动游戏闪退后Plain Craft Launcher 2.exe被删除，Plain Craft Launcher 2.exe同目录下有javacore.20221216.104332.7688.0002.txt和Snap.20221216.104332.7688.0003.trc两个文件。

### 重现步骤

打开PCL启动游戏

### 日志与附件

[Log.txt](https://github.com/Hex-Dragon/PCL2/files/10242270/Log.txt)
[javacore.20221216.104332.7688.0002.txt](https://github.com/Hex-Dragon/PCL2/files/10242272/javacore.20221216.104332.7688.0002.txt)
[Snap.20221216.104332.7688.0003.trc.zip](https://github.com/Hex-Dragon/PCL2/files/10242319/Snap.20221216.104332.7688.0003.trc.zip)

**Comment by creeper2556** [comment]
我已经将PCL添加到杀毒软件的排除项中，且未在杀毒软件中找到杀除PCL的记录

**Comment by Big-Cake-jpg** [comment]
> 以及，请添加详细问题描述，如在启动器被删除之前你进行的操作等。

^

**Comment by creeper2556** [comment]
启动游戏

**Comment by Big-Cake-jpg** [comment]
> 启动游戏

无法复现。以及，这不属于详细的问题描述。

**Comment by creeper2556** [comment]
游戏时电脑蓝屏重启后启动游戏后PCL删除，游戏未启动成功

**Comment by creeper2556** [comment]
蓝屏代码：CRITICAL_PROCESS_DIED

**Comment by LTCatt** [comment]
这是系统故障导致，与 PCL 无关。
