### ISSUE TITLE
下载页面中 手动安装包按钮 选中反馈问题

### ISSUE THREAD

**Issue by AdmireLinK** [Hex-Dragon/PCL2#609]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在下载页面中点击手动安装包 再点击自动安装 再把手动安装包收回后 鼠标指到手动安装的反馈框异常
有复现失败概率 但多试几次应该能出来
展开后不点击自动安装直接收回则不会出现Bug
此为异常版:
![image](https://user-images.githubusercontent.com/64939678/208017685-34a3e033-e86d-474c-848e-eeda9361f48d.png)
此为正常版:
![image](https://user-images.githubusercontent.com/64939678/208017746-45a6ebe1-d9e4-401d-934d-a4be7fba950a.png)

### 重现步骤

1.在下载页面中点击手动安装包
2.点击自动安装
3.点击手动安装包
不行就多试几次

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10242531/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10242532/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10242533/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10242534/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10242535/Log5.txt)

**Comment by WForst-Breeze** [comment]
稳定复现，已初步确认，感谢您的反馈~

**Comment by AdmireLinK** [comment]
@LTCatt F5AC-3391-C450-4FBB 嘿嘿嘿🥵活跃橙🥵嘿嘿嘿🤤🤤

**Comment by LBZiXL** [comment]
e

**Comment by LTCatt** [comment]
你的解锁码：LfNp8+cr6O2oXUTgWaUTRtaJXRl7RDQr
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
