### ISSUE TITLE
使用自定义主页启动按钮启动游戏不会更改登录方式

### ISSUE THREAD

**Issue by infidiotWolf** [Hex-Dragon/PCL2#615]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在使用我自定义的主页来启动游戏时，登录方式不会更新。
当我特地指定当前版本使用Littleskin登录时，再用自定义主页启动一个使用微软登录的版本，就会使用Littleskin登录方式启动游戏。
嗯，就这样。
总而言之，说来话长，长话短说，我想你应该在启动游戏的时候先同步一次设置。
因为我还遇到了一些奇怪的报错，比如未找到Java什么的……

### 重现步骤

我想我描述的很详细了。

### 日志与附件

[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10251489/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10251490/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10251491/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10251492/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10251493/Log4.txt)

**Comment by infidiotWolf** [comment]
好的咱这里也是想白嫖个活跃橙
差一个隐藏主题全解锁
请问下一次更新会收到吗 还是我要留个识别码（）

**Comment by LTCatt** [comment]
你的解锁码：xVl5vf0JwAAlAuDgkK660t3bYZ5jeKz8
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by infidiotWolf** [comment]
你好，我希望再次解锁活跃橙主题。
我的识别码：D2F4-C72B-5F07-3C60

**Comment by LTCatt** [comment]
识别码 D2F4-C72B-5F07-3C60 的土豆码是：【CD11g0T2mPrjnb%Kl/2DVlhmgHSM1ujL1ndDWYWzzXNEWL8%84W4828O2mN1ADYeH9oYIdwE63goJKdT3juy92vSDApp#VGhlbWU5】
在【更多 → 关于与鸣谢 → 输入土豆码】中使用，谢谢支持～
