### ISSUE TITLE
自定义主页的Title一栏会在特殊情况下显示错误

### ISSUE THREAD

**Issue by ComputerCPT** [Hex-Dragon/PCL2#616]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在Cutsom.xaml的任意一<local:MyCard Title="文本" >行内添加CanSwap="True"及IsSwaped="True(或False)"属性后再添加HorizontalAlignment属性，会使“因点击而收起的”（指并非“IsSwaped='True'”默认折叠的）折叠卡片将在短暂延迟后突然团成一团。
<img width="609" alt="image" src="https://user-images.githubusercontent.com/120709135/208242115-1e584c10-e284-428d-bc06-bd088a779926.png">
（上图为HorizontalAlignment="Right"时的Bug效果）

### 重现步骤

1、在Cutsom.xaml的任意一<local:MyCard Title="文本" >行内添加CanSwap="True"及IsSwaped="False"属性后再添加HorizontalAlignment属性
2、保存Cutsom.xaml文件，在PCL2的 设置->个性化->自定义主页->本地文件->刷新主页
3、回到主页，单击使卡片收起
4、这个卡片的标题栏会团成一团

### 日志与附件

[Log.txt](https://github.com/Hex-Dragon/PCL2/files/10251692/Log.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10251694/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10251695/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10251696/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10251697/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10251698/Log5.txt)

**Comment by LTCatt** [comment]
不兼容在这个情况下设置 HorizontalAlignment。
考虑使用 Grid 的 * 来控制它的位置。
