### ISSUE TITLE
在mod下载界面中添加复制mod名称按钮

### ISSUE THREAD

**Issue by AliceLeader** [Hex-Dragon/PCL2#618]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

建议在mod下载界面中，使得mod的名字可以被复制，更加便于搜索此mod。
并且百科搜索按钮打开MC百科经常在名字正确但是有空格、lib后缀的情况下无法搜到对应的mod
可以的话，请试着在启动页上附带有百科类网站的链接按钮

### 原因

（示例）
这项优化让我可以更方便地xxxx。
如果没有这项优化，我每次都必须xxxx，让操作变得很麻烦。

**Comment by WForst-Breeze** [comment]
已初步确认，感谢您的反馈~

**Comment by AliceLeader** [comment]
提一点，可以将PCL2容易被报毒的信息加到反馈提交提醒中

**Comment by RawDiamondMC** [comment]
> 提一点，可以将PCL2容易被报毒的信息加到反馈提交提醒中

测试版本来就容易被报毒...只有正式版龙猫才会去整

**Comment by AliceLeader** [comment]
还有，可以试着在mod管理界面添加游戏启动，方便测试游戏问题来自那个mod

**Comment by LTCatt** [comment]
百科搜索按钮那个不是我能控制的东西……
总之 “在mod下载界面中添加复制mod名称按钮” 是可以的

**Comment by AliceLeader** [comment]
龙猫可以给主题吗
AB26-A7A3-1D82-7025

**Comment by WForst-Breeze** [comment]
> 龙猫可以给主题吗 AB26-A7A3-1D82-7025

优化建议是不给主题的哦~抱歉
