### ISSUE TITLE
mod管理有点大病

### ISSUE THREAD

**Issue by sunshinezxq** [Hex-Dragon/PCL2#620]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在版本设置的mod管理里，按下全部启用或者全部禁用会提示文件被占用，关掉PCL在打开才会执行刚刚的操作

### 重现步骤

1、点击版本设置
2、点击mod管理
3、点击全部启用或者禁用
4、显示文件被占用
5、对了，我是测试版

### 日志与附件

[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10252889/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10252890/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10252891/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10252892/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10252893/Log3.txt)

**Comment by Hatsushigure** [comment]
我没有出现这个问题。**将PCL2移动至其他文件夹**再次尝试？
截图:
![image](https://user-images.githubusercontent.com/65275829/208272621-78df4de2-6c3b-451c-a179-349d0a44f485.png)
![image](https://user-images.githubusercontent.com/65275829/208272635-962ed84f-a85c-43ce-9bf5-137d34b3f9f0.png)

**Comment by WorldHim** [comment]
日志3、4中显示找不到文件，然而PCL反馈文件被占用。就像是PCL改名后没有刷新，导致再次操作时按改名前的文件名执行，然后找不到原文件（因为已经改过名字了）。

**Comment by LTCatt** [comment]
没看出哪有问题，倒是更像页面没刷新……
到时候看看……

**Comment by sunshinezxq** [comment]
我怀疑是U盘的问题，游戏文件在U盘时就会产生我所说的问题，但在固态里就没这回事。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Hex-Dragon/PCL2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月19日(星期一) 凌晨0:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Hex-Dragon/PCL2] mod管理有点大病 (Issue #620)





 
没看出哪有问题，倒是更像页面没刷新……
 到时候看看……

**Comment by Louis-ZYH** [comment]
有   点   大   病

**Comment by sunshinezxq** [comment]
游戏文件搬到固态里就没事了

**Comment by WorldHim** [comment]
> 游戏文件搬到固态里就没事了

离谱，大概是U盘处理慢PCL2没反应过来？

**Comment by miner233** [comment]
我试了一下，我这里没有问题
你是不是启动游戏了？启动游戏后，Mod 文件会被 Minecraft 调用（占用）。
PCL2 的禁用/启用 Mod 功能是通过更改文件扩展名来实现的（将 .jar 扩展名更改为 .disabled 扩展名，说白了就是在文件名末尾添加 .disabled，让它不再是 .jar 文件，Minecraft 只能识别 .jar 文件的 Mod，要启用 Mod 的话就把 .disabled 去掉）。当文件正在被调用（占用）时，不能对这个文件进行修改。
当启动游戏时，我这里也不能启用/禁用。
![image](https://user-images.githubusercontent.com/110521837/209626292-25bdf9f9-7a1d-4da8-8d8d-ed6ca9bec428.png)
![image](https://user-images.githubusercontent.com/110521837/209626315-8ae0ff78-4934-441f-abd8-bf1f1ee4ae27.png)

**Comment by sunshinezxq** [comment]
游戏没开....

**Comment by sunshinezxq** [comment]
![image](https://user-images.githubusercontent.com/120849197/209636045-149065fb-dc48-42bc-8336-07a5ee8facd2.png)
![image](https://user-images.githubusercontent.com/120849197/209636076-312261af-4283-446d-9eaf-68a95835d9b2.png)
![image](https://user-images.githubusercontent.com/120849197/209636131-5b2f2a37-c783-4a28-9723-ac178d30231d.png)
![image](https://user-images.githubusercontent.com/120849197/209636198-ea415d1f-d042-4326-a72e-622727b612cf.png)
![image](https://user-images.githubusercontent.com/120849197/209636263-9f41d0ac-aaeb-4f6c-a497-95a5fce098fc.png)

**Comment by sunshinezxq** [comment]
![image](https://user-images.githubusercontent.com/120849197/209636401-8e9d5288-3343-4a60-94af-81364490d41c.png)

**Comment by sunshinezxq** [comment]
问题主要点不是在u盘吗qwq?

**Comment by sunshinezxq** [comment]
新发现，按下之后生效了，但是pcl嘴硬，还是亮的

**Comment by miner233** [comment]
啊...游戏没开...这又是什么离谱 Bug

**Comment by sunshinezxq** [comment]
ABD9-6D0A-34AF-3EE4

**Comment by LTCatt** [comment]
你的解锁码：WFUTUcSk+acZyxpLVnvfORWokJ9ojy68
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by sunshinezxq** [comment]
2EA9-6CC1-C51C-C0F3

**Comment by LTCatt** [comment]
你的解锁码：pTe0tv1dMQXWFtVEevm1lIyxRKEPUG8T
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
