### ISSUE TITLE
为 PCL2 界面添加键盘操作显示

### ISSUE THREAD

**Issue by maxelblack** [Hex-Dragon/PCL2#624]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

WPF 本身实现了多数界面的简单键盘操作，但 PCL2 的 UI 组件没有把它显示出来。
例如，用键盘在不同按钮间移动时，选中的按钮应当像鼠标悬停时一样高亮显示，同时显示自己的工具提示文本。

### 原因

1. 对于键盘党来说，用键盘操作某些地方会比用鼠标方便得多。
2. 对于有时用键盘点击 Enter 等键，若没有高亮显示会更容易误操作。
3. 这个建议在 PCL2 处于 Dev 版本时我曾经提过，但龙猫以“玩游戏没有鼠标怎么玩”的理由拒绝了，这里想说明一下，游戏里面也是支持键盘选中按钮之类的操作的...

**Comment by maxelblack** [comment]
本来想试试自己实现一下，然而现在我还没做到让垃圾 VS 认为 `PCL` 这个 namespace 是存在的...

**Comment by WForst-Breeze** [comment]
已初步确认，请等待开发者进一步考虑，感谢您的反馈~
（题外话：原来那个人是您啊hhhhh）

**Comment by LTCatt** [comment]
抱歉，这个真的不考虑，PCL2 的按钮是自制控件，并不支持默认的键盘导航。要重新实现这些逻辑需要重新设计所有界面，这个工作量和实现这个功能的收益完全不对等。
