### ISSUE TITLE
刷新音乐ui失败

### ISSUE THREAD

**Issue by Minecraftcyh** [Hex-Dragon/PCL2#625]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

放着背景音乐突然中断，跳过，然后放下一个，有时直接说找不到跳过好多个

### 重现步骤

1.播放音乐
2.突然跳过说找不到

### 日志与附件

[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10253229/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10253230/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10253231/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10253232/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10253233/Log3.txt)

**Comment by LTCatt** [comment]
上传的日志中没有找到这些报错。
重新复现一下，然后重新上传日志？

**Comment by LTCatt** [comment]
超时先关了，如果要补充可以继续在下面补充
