### ISSUE TITLE
Forge无可用版本

### ISSUE THREAD

**Issue by Grey-Wind** [Hex-Dragon/PCL2#628]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

下载页面任选版本都无Forge，手动安装也检测不到
![)J HQDDY2(O2KQ0QVM9J 8P](https://user-images.githubusercontent.com/98391767/208286706-afb08ff2-1d4e-4ec7-8554-43b16e9fecbe.png)
![LDIEU~AMI0Q2~DACALG)OSV](https://user-images.githubusercontent.com/98391767/208286710-d9b310b6-5711-4484-856a-1264f588ccc3.png)
![T9S1 PXC~ E8})L`OUA RUV](https://user-images.githubusercontent.com/98391767/208286716-40671dc2-aed6-4508-997c-f94ef16ccbd5.png)
![JY$3HH%$ 45{7_U$S$H)@S](https://user-images.githubusercontent.com/98391767/208286720-4a9d8449-acb7-44ce-90ae-56fcbd4cb5ea.jpg)

### 重现步骤

下载页面任选版本都无Forge，手动安装也检测不到
疑似Forge电脑版官网炸了，因为手机可以正常访问Forge，具体看描述内的图片

### 日志与附件

无

**Comment by WForst-Breeze** [comment]
Hmmmm....?
![image](https://user-images.githubusercontent.com/110760354/208286822-9ce7cc93-9b42-43cb-ac2e-85fa6a1b99b2.png)
![image](https://user-images.githubusercontent.com/110760354/208286830-88524bae-95d2-4634-a637-731473c55254.png)

**Comment by WForst-Breeze** [comment]
我这里一切正常，无法复现，不清楚是不是您那边的问题

**Comment by Grey-Wind** [comment]
我找到问题了
[这个](https://www.bilibili.com/read/cv9063550)教程的host文件修改会导致这个bug
`# Minecraft Forge Mod Devlopment Gradle Config Start`
`142.44.226.189 files.minecraftforge.net`
`#158.69.55.219 files.minecraftforge.net`
`99.84.226.87 libraries.minecraft.net`
`13.32.145.12 resources.download.minecraft.net`
`# Minecraft Forge Mod Devlopment Gradle Config End`
在添加以上代码后会导致报告不安全，还会有访问问题

**Comment by Grey-Wind** [comment]
所以要不要让龙猫在PCL内弄个检测hosts文件的控件，来防止这种问题

**Comment by WForst-Breeze** [comment]
感觉没太大必要……但还是看龙猫的意愿吧qwq

**Comment by Grey-Wind** [comment]
确实

**Comment by LTCatt** [comment]
你应该向那个教程的作者反馈，而不是我……
