### ISSUE TITLE
兼容 UTF-8 输出相关文件

### ISSUE THREAD

**Issue by char-46** [Hex-Dragon/PCL2#631]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

PCL2在 Windows 启用区域设置中的`Beta 版：使用 Unicode UTF-8 提供全球语言支持`选项后，输出的`LatestLaunch.bat`依然为 gbk 编码。并且未在 jvm 选项中加入`-Dfile.encoding=utf-8`。

### 原因

PCL 输出的`LatestLaunch.bat`文件和 Minecraft 输出的 log 文件都依然使用 gbk 编码，不能用记事本正常打开。
我今天遇到的玄学问题（中文路径下游戏起不来）可能也和这个有关。

**Comment by char-46** [comment]
4D06-CD73-E04F-05F2

**Comment by LTCatt** [comment]
你的解锁码：nndHO6zjY83sT3bYBGTFBDVZu6m/tQTQ
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
