### ISSUE TITLE
打不开了, 不知道是哪里有问题

### ISSUE THREAD

**Issue by Klosw** [Hex-Dragon/PCL2#633]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://user-images.githubusercontent.com/13143959/208299260-9ca2f463-c84b-4e84-8d97-5bd475eff2ac.png)  
这个怎么解决呢 

### 重现步骤

1、点击xxxx
2、往下滚，然后点击xxxx

### 日志与附件

没有生产日志哈哈

**Comment by iPodtouch6557** [comment]
跟我下面的一个老兄一样，建议看看我的，描述详细

**Comment by Big-Cake-jpg** [comment]
人家都给你写出来解决方案了，不能按照弹窗上写的做吗

**Comment by iPodtouch6557** [comment]
> 人家都给你写出来解决方案了，不能按照弹窗上写的做吗

是pcl2与系统冲突了，不是他的问题，跟我下面的一个人一样

**Comment by Klosw** [comment]
> 人家都给你写出来解决方案了，不能按照弹窗上写的做吗

有用我就不会发了.....

**Comment by Klosw** [comment]
> > 人家都给你写出来解决方案了，不能按照弹窗上写的做吗
> 
> 是pcl2与系统冲突了，不是他的问题，跟我下面的一个人一样
不知道为啥 今天 好了

**Comment by iPodtouch6557** [comment]
https://github.com/Hex-Dragon/PCL2/issues/666

**Comment by Klosw** [comment]
> #666
电脑重启后已经好了
