### ISSUE TITLE
MOD运行失败，经检查确认为Fabric及其API版本过老（望更新！！！）

### ISSUE THREAD

**Issue by kong-que-dnf123** [Hex-Dragon/PCL2#637]
### 检查项

- [ ] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃不是 PCL2 的原因，请 **不要** 提交反馈。你可以在 QQ 群里或者论坛找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是游戏本身的问题，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

下载1.16.4 
Fabric选择最新版
Fabric API选择唯一版本
开始下载
自我安装适用于1.16.4的Wurst
运行
错误
Fabric 及其API版本过老
望更新其最新版本
![Uploading 屏幕截图 2022-12-19 083511.jpg…]()

### 错误报告、日志与附件

[错误报告-2022-12-19_8.22.41.zip](https://github.com/Hex-Dragon/PCL2/files/10255052/-2022-12-19_8.22.41.zip)
[Uploading Log1.txt…]()

**Comment by Big-Cake-jpg** [comment]
除了错误报告的 zip 压缩包，一个文件都没传上来。

**Comment by kong-que-dnf123** [comment]
斯 现在传
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10255080/Log1.txt)

**Comment by kong-que-dnf123** [comment]
![Uploading 屏幕截图 2022-12-19 083511.jpg…]()

**Comment by Big-Cake-jpg** [comment]
```
[07:11:10.494] [Download] 版本 开G1.16.4 对应的资源文件索引为 1.16
```
~~挂端？那没事了~~

```
[08:06:08] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 **- Replace 'Java HotSpot(TM) 64-Bit Server VM' (java) 8 with version 16 or later.**
	 - Replace 'Minecraft' (minecraft) 1.16.4 with version 1.17-alpha.21.20.a or later.
	 **- Replace mod 'Fabric API' (fabric) 0.29.3+1.16 with version 0.33.4 or later.**
```
请先尝试将 Java 版本提升到 JDK 16。
