### ISSUE TITLE
自定义主页教学文件对“HorizontalAlignment”属性的描述不准确

### ISSUE THREAD

**Issue by ComputerCPT** [Hex-Dragon/PCL2#639]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在Custom.xaml文件中，“HorizontalAlignment”属性被归列在“ **全部通用** 的属性”里，但实则“HorizontalAlignment”属性**仅**与“CanSwap”属性为**False**时的 **<local:MyCard>卡片** _兼容_，**但是**与“CanSwap”属性为**Ture**时的 **<local:MyCard>卡片** _不兼容_。这条应在“HorizontalAlignment”属性后标注出来。

### 重现步骤

我想这并不需要重现

### 日志与附件

<img width="722" alt="image" src="https://user-images.githubusercontent.com/120709135/208332943-041f5c52-6a2e-4d43-86f4-6fc297fba204.png">
（龙猫你自己说的）

**Comment by LTCatt** [comment]
去 [LTCatt/PCL2Help](https://github.com/LTCatt/PCL2Help) 交反馈

**Comment by ComputerCPT** [comment]
> 去 [LTCatt/PCL2Help](https://github.com/LTCatt/PCL2Help) 交反馈

好
