### ISSUE TITLE
Mod添加失败

### ISSUE THREAD

**Issue by iamvapegod** [Hex-Dragon/PCL2#641]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在pcl2的游戏（高版本）版本设置界面中使用按钮【打开Mod文件夹】后添加Mod无法被游戏识别到。

### 重现步骤

1.进入pcl2
2.点击【版本设置】
3.点击【Mod文件夹】
4.添加Mod

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10256096/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10256097/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10256098/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10256099/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10256100/Log5.txt)

**Comment by LTCatt** [comment]
Mod 无法被游戏识别到并非启动器的问题
