### ISSUE TITLE
误判 Minecraft 存在问题

### ISSUE THREAD

**Issue by ZS2147483647** [Hex-Dragon/PCL2#643]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [x] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

我玩了一个整合包,他自带的启动器有些问题,但是放进pcl也无法启动提示mc有问题,补全文件也没救回来

### 原因

这项优化让我可以更方便地游玩各个mc版本的整合包[因为有些整合包的启动器就是不行]
不必害怕因各种原因导致游戏无法玩

**Comment by ZS2147483647** [comment]
> 整合包发来，还有错误报告

**Comment by ZS2147483647** [comment]
过不来,我上一下百度云

**Comment by ZS2147483647** [comment]
没有错误报告,只说minecraft有问题在右下角一个红色的

**Comment by ZS2147483647** [comment]
根本就没有尝试启动就说有问题哪来的错误报告

**Comment by ZS2147483647** [comment]
链接：https://pan.baidu.com/s/1JrjEqsavs5bGOzo3fpMH-A?pwd=0000 
提取码：0000

**Comment by bwtx2022** [comment]
发 cowtransfer.com

**Comment by ZS2147483647** [comment]
https://cowtransfer.com/s/1880c231ada248 点击链接查看 [ 1.19.2整合包晓铭改.zip ] ，或访问奶牛快传 cowtransfer.com 输入传输口令 qen88m 查看；

**Comment by ZS2147483647** [comment]
这两个平台有区别吗,上传还不是一样限速

**Comment by bwtx2022** [comment]
但是我下载不痛苦啊...

**Comment by bwtx2022** [comment]
根据测试，BakaXL 可以正常补全文件并启动游戏

确实是 PCL2 Bug

**Comment by bwtx2022** [comment]
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10275948/Log1.txt)

这里给出我测试过程中的 Log。

@ZS2147483647 请你也上传 PCL 文件夹中的 Log1-5

**Comment by ZS2147483647** [comment]
我不知道还是否有效
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10276070/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10276071/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10276073/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10276074/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10276076/Log5.txt)

**Comment by ZS2147483647** [comment]
这点也在说明现在的bug反馈是不够合理的

**Comment by ZS2147483647** [comment]
连文件都传不过去,还要用户二次上传

**Comment by ZS2147483647** [comment]
@LTCatt 谁都知道pcl好,我也承认pcl是最好的启动器没有之一,但软件本身并不能代表全部,你懂我的意思吗

**Comment by Big-Cake-jpg** [comment]
文件上传是 GitHub 那边的问题，我们无法解决。
另外，请你不要随意 at 龙腾猫跃

**Comment by LTCatt** [comment]
不知道为啥又重现不出来了……
目前怀疑是整合包里带了一个残缺的 PCL.ini 导致的。

@bwtx2022 你能稳定重现么？

**Comment by bwtx2022** [comment]
> 不知道为啥又重现不出来了……
> 
> 目前怀疑是整合包里带了一个残缺的 PCL.ini 导致的。
> 
> 
> 
> @bwtx2022 你能稳定重现么？

我有空再试试

**Comment by LTCatt** [comment]
https://ltcat.lanzoum.com/i5fTB0k5wena

**Comment by ZS2147483647** [comment]
嗨嗨嗨,我又满血复活了~~~
这个bug可以复现,但有些奇怪,请严格按照我的步骤操作
1.下载,解压[让他解压成一个文件夹包含着内部三个文件的样子]
2.将pcl2直接从别的地方复制过来
3.在pcl2中启动游戏,会显示minecraft存在问题
![image](https://user-images.githubusercontent.com/121028009/210934195-c07a636d-0795-450e-b18f-85bbed51dc8e.png)

**Comment by ZS2147483647** [comment]
但这并不稳定,复现完成退出后将整个大文件夹删除再还原就会发现启动成功,而且就算手动删除pcl.ini也可以启动

**Comment by ZS2147483647** [comment]
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10357451/Log1.txt)

**Comment by bwtx2023** [comment]
经过测试，第一次启动会报错，而第二次启动不会报错，两次启动前后 PCL.ini 内容没有发生变化
（由于性能关系我并没有让其启动完成，能正常下载大概就代表 PCL2 没有问题）

这里给出日志：
[第一次打开（不能正常启动-调试模式）.txt](https://github.com/Hex-Dragon/PCL2/files/10359194/-.txt)
[第二次打开（能正常启动-调试模式）.txt](https://github.com/Hex-Dragon/PCL2/files/10359199/-.txt)
[第一次启动（不能正常启动）.txt](https://github.com/Hex-Dragon/PCL2/files/10359196/default.txt)
[第二次启动（能正常启动）.txt](https://github.com/Hex-Dragon/PCL2/files/10359197/default.txt)

BakaXL 依然是一次启动成功
