### ISSUE TITLE
清理缓存可能误删版本重要文件

### ISSUE THREAD

**Issue by IceYi233** [Hex-Dragon/PCL2#645]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

更新版本（2.4.4 快照版）后在“设置-启动器-系统”中点击“清理缓存”按键（图一），反应了好长一段时间后显示清理出14.3G的缓存。再次重启PCL2时发现 原文件夹.minecraft 中所有游戏版本均显示为“错误的版本”，在“版本选择”一栏中均显示为“未找到版本json文件”（图二）。

打开各版本（使用了版本隔离）文件夹后发现缺少一些文件（图三），且mods(模组), config(配置), resourcepacks(资源包), shader packs(光影，仅对有Optifine的版本), screenshots(截屏)文件夹里的原始内容全部消失（图五）；saves(存档)里面各世界文件有所差异（图四）。

在原文件夹.minecraft 中出现了一个名为“PCL”的配置设置（图六），打开后如图七，记录了之前所有版本的名称。（其实上面那个json文件也不记得是清完缓存后出现的还是老早以前装启动器时就有的；包括这个名为“PCL”的配置设置也不太清楚是不是装启动器时就已经有了，求大佬顺便帮忙看一下）

现在想知道是否是启动器版本更新导致了这个问题，如果是的话该怎样修复那些缺失的组件和游戏原文件？望各位大佬帮忙查看

### 重现步骤

1、打开启动器，按“设置-启动器”点击
2、找到“系统”一栏，点击“清空缓存”按钮
3、等待清理完成后启动器自动重启，会发现版本全部无法运行
![e99ca58466d99b76e119d8ee0ae01cc](https://user-images.githubusercontent.com/121037817/208461707-6d3e90e6-1ddf-43fd-a6b4-85668b6261e1.jpg)

### 日志与附件

附图片

![e99ca58466d99b76e119d8ee0ae01cc](https://user-images.githubusercontent.com/121037817/208461752-45643af2-2c0f-482d-a7b5-d58fe6a88b6d.jpg)图一

![d3ab1e7e1719f1662af35e450db66d6](https://user-images.githubusercontent.com/121037817/208461833-04d0a791-1f24-4db5-902a-17273ee7dc3c.jpg)图二：所有版本均显示为错误的版本

![cef6892c8c51b16cd1f71cb12e4791c](https://user-images.githubusercontent.com/121037817/208462072-92d69afa-1d38-4050-b960-31a7948572f1.jpg)图三：整体对比；左为后来重新下的正常版本，右为清完缓存后有问题的版本

![52f7e2b9e5c9dbcd76d133ee82c92e5](https://user-images.githubusercontent.com/121037817/208462165-cebf4ccf-2ecf-4661-9e04-98972cf3417c.jpg)图四：saves(存档)对比；左为有问题的版本，右为正常版本

![65111288aa60ef98d1af71fd403db07](https://user-images.githubusercontent.com/121037817/208462230-46f643d7-c87d-446b-b1e8-a4ae2e95cbc6.jpg)图五：有问题的版本的mods文件夹，空的（原来装了一大堆mod）

![c1277b1c4ee7536c7410efd569a17da](https://user-images.githubusercontent.com/121037817/208462390-b5e8b2ff-eb3a-489d-91bd-5873bd5791b8.jpg)图六：多出现的“PCL”配置设置（不是太确定是否是清完缓存后刚出现的）

![3ec6fb73386e655ebd601beb205696e](https://user-images.githubusercontent.com/121037817/208462768-e4638037-12ce-4b11-a06f-0b8f88143be9.jpg)图七：“PCL”配置设置用记事本打开后

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10260616/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10260620/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10260624/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10260627/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10260637/Log5.txt)

**Comment by IceYi233** [comment]
补充：
为了获取日志文件，又在调试模式下重复进行了上述操作，虽然使用的是“设置-启动器-调试选项-调试模式”，但导致今天找出来并恢复的备份版本（1.16.5回测）出现了同样的情况，游戏又崩了。以下是模拟日志及一些截屏。

日志
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10261634/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10261635/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10261636/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10261637/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10261638/Log5.txt)

截屏

![48cfecdf6c337aab662356386ffb899](https://user-images.githubusercontent.com/121037817/208493167-ceb558b3-a319-48a9-bdf3-88f56024e439.jpg)1、调试模式下重复操作后，启动器重启后的主界面，与昨天第一次操作后重启的启动器界面一样，除了没有启动日志，因为昨天的操作不是在调试模式下进行的

![c6f791977b64d296da1224ba9cc0916](https://user-images.githubusercontent.com/121037817/208494254-c01f176e-9c05-48f7-85e8-619f5b63c56d.jpg)2、调试模式下重复操作后，备份版本（1.16.5回测）也出现了同样的问题

![37a1aeae7e6de9a8b7821aa58be099a](https://user-images.githubusercontent.com/121037817/208494448-69041395-002d-46fe-82e6-fbd785d825a4.jpg)3、重复操作前的1.16.5回测，正常状态，可以在启动器里被打开并进入游戏

![17d01ce4288f7c729b0e2ec14c0dd1e](https://user-images.githubusercontent.com/121037817/208494854-4fb22458-020a-487a-8cb6-f4c11b3eb600.jpg)4、重复操作后的1.16.5回测，与上图作对比，少了些文件，资源组件也是全部消失

![83af07bea6132c77c52e78c04936d54](https://user-images.githubusercontent.com/121037817/208495104-25beb399-d386-426e-9da4-0295807b475a.jpg)5、重复操作前的“PCL”配置设置里面的内容（与下图作对比，红色被圈的部分是参数有所改变，蓝色横线部分是操作前有但操作消失的部分）

![9e6e56a0014eb722d5ec8db66e139cc](https://user-images.githubusercontent.com/121037817/208495433-33cd0687-c6d0-46dc-a141-1552a17b04b6.jpg)6、重复操作后的“PCL”配置设置里面的内容（与上图作对比，可以看到“CardCount”和“CardKey1”两项参数发生了改变；原先“1.16.5回测”所在的“CardValue1”改变了。推测上图中“CardValue2”是无法运行的错误版本，而“CardValue1”和“Version”是可运行的正常版本）

**Comment by bwtx2022** [comment]
PCL.ini 是 PCL2 安装游戏时就会生成的，至于清理缓存导致的游戏打不开，个人认为是误删了文件，这部分的逻辑可能有点问题

版本 Json 和 Jar 是必不可少的。

**Comment by LTCatt** [comment]
这是因为你将缓存文件夹设置成了 MC 文件夹， 而 PCL2 在清理缓存的时候会删除缓存文件夹……
![image](https://user-images.githubusercontent.com/40348278/210634576-c249c497-fd29-4528-b95a-c81389c7f885.png)


我已经添加了一个警告弹窗，在手动修改了缓存文件夹时给出具体警告……

**Comment by LTCatt** [comment]
没有办法恢复，抱歉 Orz
