### ISSUE TITLE
切换选择的版本不会更换下载 Mod 的目标文件夹

### ISSUE THREAD

**Issue by DupeisTaken** [Hex-Dragon/PCL2#646]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在下载mod的时候文件夹不是“版本选择”选中的版本而是上一次存文件的文件夹。在之前的版本中，没有出现类似状况.
启动器版本: Snapshot 2.4.4

### 重现步骤

1. 先下崽一个版本的mod
2. 在”版本选择“中切换版本
3. 再次下崽东西，会发现文件夹仍然时原来的文件夹

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10260937/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10260938/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10260939/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10260940/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10260942/Log2.txt)

**Comment by DupeisTaken** [comment]
那么主题怎么获得呢qaq

**Comment by LBZiXL** [comment]
发送你的识别码

**Comment by DupeisTaken** [comment]
ECBC-C7E4-ACF0-C266

**Comment by LBZiXL** [comment]
然后龙猫就会给你解锁码

**Comment by LTCatt** [comment]
你的解锁码：FYaONDcFaT7GCHPm55/gunauUmnGiBgV
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by LTCatt** [comment]
你的解锁码：FYaONDcFaT7GCHPm55/gunauUmnGiBgV
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by DupeisTaken** [comment]
新电脑，新识别码（真的很喜欢活跃橙！！）3495-2B70-26CC-459A

**Comment by LTCatt** [comment]
你的解锁码：aREALZIEzXOqDuGmnM6EGk9lna6ZcCi3
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by DupeisTaken** [comment]
新电脑x2，新识别码（真的很喜欢活跃橙！！）8284-ABC8-6667-C930

**Comment by LTCatt** [comment]
你的解锁码：wl0qm0m9rvmwO0yOq3KIAFnJSsejFdmW
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by DupeisTaken** [comment]
识别码：677A-9B09-7C83-65A7 owo

**Comment by LTCatt** [comment]
你的解锁码：lJY8pcdlm9Y9vrVXgKDZV9Hh5xYZl1Dc
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by DupeisTaken** [comment]
# 识别码 2C1D-BA1B-2688-7689 owo

**Comment by LTCatt** [comment]
识别码 2C1D-BA1B-2688-7689 的土豆码是：【CD11X4%qITyiEh8Iw/lw+rIJh9GQcUKodU0VfvXhtQ8ujc%2bCRPPOdGGOwH%wyICEi/qLMHvr+RfUEjnodLHEyr6wpp#VGhlbWU5】
在【更多 → 关于与鸣谢 → 输入土豆码】中使用，谢谢支持～
