### ISSUE TITLE
若 Java 查找失败，会导致显示错误且循环查找

### ISSUE THREAD

**Issue by tumuidle** [Hex-Dragon/PCL2#651]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![CWBIVH_5%DV1DYZ$K_%OXFM](https://user-images.githubusercontent.com/62649962/208592352-a3f8e247-14f8-473c-8fab-f70edefc2663.png)

### 重现步骤

1、启动游戏

### 日志与附件

[Log.txt](https://github.com/Hex-Dragon/PCL2/files/10265691/Log.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10265692/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10265693/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10265695/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10265696/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10265697/Log5.txt)

**Comment by BaoHouxun** [comment]
《MCLDownload》
应给是网易我的世界的Java吧，
应该网易背锅
