### ISSUE TITLE
BGM设置的错误

### ISSUE THREAD

**Issue by AXNUT** [Hex-Dragon/PCL2#653]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

这个bug无关紧要，但是看上去还是很不舒服的。

### 重现步骤

1、点击打开文件夹
2、导入多个音乐
3、清空文件

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10266191/Log1.txt)

**Comment by bwtx2022** [comment]
详细描述问题表现

**Comment by LTCatt** [comment]
上传的日志中没有任何报错，请重新上传日志并描述问题。

顺带一提 @bwtx2022 这种应该标记成等待反馈者……

**Comment by bwtx2022** [comment]
> 上传的日志中没有任何报错，请重新上传日志并描述问题。
> 
> 
> 
> 顺带一提 @bwtx2022 这种应该标记成等待反馈者……

好好好（

**Comment by LTCatt** [comment]
超时先关了，如果要补充可以继续在下面补充
