### ISSUE TITLE
更改对于高版本的 Java 下载链接

### ISSUE THREAD

**Issue by maxelblack** [Hex-Dragon/PCL2#654]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

建议 PCL2 内置个巨硬 JDK 17 的下载链接给高版本用，官方版 Java 在 MC 高版本貌似问题挺多的。巨硬的那个网站实测在国内可访问，隔壁 HMCL 目前就在用。

### 原因

没啥原因，只是建议，非必需。
（目前我这里倒是没什么问题，但是总是看到有人用官方版 Java 启动游戏爆 JVM 错误）

**Comment by bwtx2022** [comment]
#104

**Comment by bwtx2022** [comment]
@LTCatt 这个我觉得确实需要解决一下，出现了 JVM 问题让用户重装 Zulu Java

**Comment by LTCatt** [comment]
HMCL 用的是啥下载链接？

**Comment by maxelblack** [comment]
> HMCL 用的是啥下载链接？

是 [Microsoft JDK](https://www.microsoft.com/openjdk) ，HMCL 直接跳转到了它的[下载页](https://learn.microsoft.com/en-us/java/openjdk/download)

**Comment by maxelblack** [comment]
> 这个我觉得确实需要解决一下，出现了 JVM 问题让用户重装 Zulu Java

Zulu 跟 Microsoft JDK 据说还是有差别，毕竟它是 Azure 的（懂的都懂），而且网站有时候有国内访问问题。
我的建议是一开始就直接跳转个 Microsoft JDK 链接让用户自己下载，Mojang 官方用的就是这个，应该相对会稳定很多。

**Comment by Moe23333** [comment]
嗯，Oracle JDK 似乎性能也较低（我个人目前使用的是 Eclipse Adoptium）

**Comment by maxelblack** [comment]
Oracle JDK 似乎对稳定性有极端的追求，结果适得其反了
当然我猜很多人爆 JVM 错误是因为 Mod 开发者都不用 Oracle JDK

**Comment by Moe23333** [comment]
> Oracle JDK 似乎对稳定性有极端的追求，结果适得其反了 当然我猜很多人爆 JVM 错误是因为 Mod 开发者都不用 Oracle JDK

确实，连 Fabric 的 Mod 开发文档「配置 Mod 开发环境」一节中，所给出的 JDK 下载链接都是 Eclipse Adoptium（

**Comment by Moe23333** [comment]
BTW，看了眼 [Forge 开发文档]里用的也是 Eclipse Adoptium...

[Forge 开发文档]: https://docs.minecraftforge.net/en/1.19.x/gettingstarted/

**Comment by LTCatt** [comment]
umm 所以对使用哪个 java 有啥定论么？
只考虑稳定性的话，哪个 java 不会导致 JVM 错误？

**Comment by maxelblack** [comment]
Forge 和 Fabric 官方指定的都是 Eclipse Adoptium ，MC 官方用的是 Microsoft JDK (同家的 Zulu JDK 据很多人体验同样稳定)
目前基本就确定在这两个之间选一个了，至于 #629 这个只能联系提出者本人来测试一下哪种更稳定一些，JVM 故障除了翻它的源码基本没办法找到具体故障原因

**Comment by maxelblack** [comment]
补充：Eclipse Adoptium 在国内下载最新版可能并不是很容易，因为官方给的是 GitHub Release 的下载链接

**Comment by bwtx2022** [comment]
`[11:49:00] [pool-3-thread-1/INFO] [minecraft/DataFixers]: Building unoptimized datafixer
[LWJGL] Platform/architecture mismatch detected for module: org.lwjgl
	JVM platform:
		Windows amd64 17.0.1
		OpenJDK 64-Bit Server VM v17.0.1+12-LTS by Microsoft
	Platform available on classpath:
		windows/x86
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
Exception in thread "Render thread" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException`

日志中出现该问题，根据用户反馈可以通过更新 PCL 的方式解决

**Comment by quannen** [comment]
可是我用的是Oracle JDK，从来不崩游戏，是我运气好吗(

**Comment by maxelblack** [comment]
> 可是我用的是Oracle JDK，从来不崩游戏，是我运气好吗(

可能是吧，我 Corretto 也从来不崩，很多人随我推荐用 Corretto 甚至都有 NoClassDefError 但我一点事都没

**Comment by quannen** [comment]
前段时间我朋友推荐我用Eclipse Adoptium，结果一天崩了5次(无语

**Comment by quannen** [comment]
就看运气

**Comment by maxelblack** [comment]
额... PCL2 优化好是指那一串附加 JVM 参数吗...其实你把它复制到 HMCL 的 JVM 附加参数里效果一样的...

**Comment by TheBejinning** [comment]
我说的优化好不是指别的,而是字体不乱码,那个hmcl微软雅黑乱码,自定义字体优化不完全,而且他们的回复我也看不懂🤣🤣🤣🤣🤣[pcl2社区说的都是人话,hmcl社区动不动就大篇代码和术语],游戏的话除了有一天玄学崩重启解决外我感觉官方jdk挺好,没啥问题

**Comment by bwtx2022** [comment]
OracleJDK的性能完全不如OpenJDK们

**Comment by HamsterYrc** [comment]
那怎么解释我的整合包openjdk启动不了？

**Comment by TheBejinning** [comment]
额,有没有大佬[简单]解释一下各版本jdk有什么区别与联系

**Comment by quannen** [comment]
Eclipse Adoptium在官网下载好慢，可是用PCL2下载能干到10Mbps(

**Comment by quannen** [comment]
我感觉要是改的话就改为Eclipse Adoptium
（速度.....还..还行？

**Comment by idhaname** [comment]
Eclipse Adoptium在国内有镜像源：[清华大学开源软件镜像站](https://mirrors.tuna.tsinghua.edu.cn/Adoptium/)

**Comment by LTCatt** [comment]
头秃，我要不然直接用 Mojang 的官方 Java 算了……

**Comment by HamsterYrc** [comment]
没下载java的我感觉可以做个弹窗让用户选择……

**Comment by quannen** [comment]
> 没下载java的我感觉可以做个弹窗让用户选择……

龙猫：工程量又增加了（笑

**Comment by HamsterYrc** [comment]
确实，联机就是个例子（

**Comment by maxelblack** [comment]
> 头秃，我要不然直接用 Mojang 的官方 Java 算了……

官方是个微软 JDK 的精简版，直接让用户下载微软 JDK 就好了，国内访问速度还挺好

**Comment by maxelblack** [comment]
@TheBejinning 关于 HMCL 的字体问题不能怪开发者......是 Java FX 那玩意比较魔幻，有些bug他们现在也救不了......
PCL 用的是 WPF 如果跟 Windows 不完美兼容才有问题

**Comment by iPodtouch6557** [comment]
我建议直接去搜jdk官网，虽然找到官方正确的页面有点烦，但是很保险
一般是这个链接下载：https://www.oracle.com/java/technologies/downloads/

**Comment by iPodtouch6557** [comment]
我建议直接去搜jdk官网，虽然找到官方正确的页面有点烦，但是很保险
一般我都是这个链接下载：https://www.oracle.com/java/technologies/downloads/

**Comment by maxelblack** [comment]
> 我建议直接去搜jdk官网，虽然找到官方正确的页面有点烦，但是很保险

我们已经讨论过 Oracle JDK 了，见上面的评论
总结起来 Oracle JDK 有性能较低、闭源、社区支持不好等很多缺点，虽然确实是能用的，但不适合作为默认选择来提供

**Comment by LTCatt** [comment]
这样看起来确实各有各的说法……那稳妥起见，在制作 #99 的时候还是直接使用 Mojang 官方提供的 Java 吧——Forge 什么的不可能连官启的 Java 都不兼容了吧 =。=
既然有 #99 了，那目前也没啥必要更改下载连接了，先关了？
