### ISSUE TITLE
离线模式的正版皮肤无法正确加载

### ISSUE THREAD

**Issue by highestokk1** [Hex-Dragon/PCL2#655]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在设置/游戏/离线皮肤中，正版皮肤输入正版玩家名无法得到皮肤
![捕获](https://user-images.githubusercontent.com/120703949/208611797-5768ec77-aaab-40d3-9a7a-550c93ad2ad4.PNG)
![捕获1](https://user-images.githubusercontent.com/120703949/208611803-ed87d0c8-6cc5-4e96-aec8-c2ccf48efff4.PNG)

### 重现步骤

1、点击设置
2、然后点击游戏
3，在离线皮肤选择框中，选中正版皮肤
4，输入正版玩家名
5，点击启动，发现皮肤未正确加载

### 日志与附件

在日志中，我并没有看到有关这个bug的报告

**Comment by highestokk1** [comment]
[15:51:43.181] [Net] 获取网络结果：https://sessionserver.mojang.com/session/minecraft/profile/f4f59ac621b44bfe90ff106b64c5d599，最大超时 30000
[15:51:44.143] 获取离线登录使用的正版皮肤失败（Zi__Min）：获取结果失败，远程服务器返回错误: (403) 已禁止。（https://sessionserver.mojang.com/session/minecraft/profile/f4f59ac621b44bfe90ff106b64c5d599）
→ 远程服务器返回错误: (403) 已禁止。

**Comment by highestokk1** [comment]
原来还是有日志的，我眼瞎没看到

**Comment by WForst-Breeze** [comment]
与 PCL2 无关，请检查您的网络连接或稍等一会儿后再尝试获取正版皮肤，感谢您的反馈~
