### ISSUE TITLE
我自己作死

### ISSUE THREAD

**Issue by ZS2147483647** [Hex-Dragon/PCL2#656]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我先安装了jdk19尝试启动mc,成了,证明pcl提示有误,jdk19可以正常启动游戏
然后把jdk19删了[此时依然指定jdk19,但是它已经被删了],启动游戏,居然又进了[确实是jdk19,没有改别的],然后mc卡住,pcl崩溃[太卡了没法截屏]
但是!!没有jdk他是怎么进的游戏,别管能不能玩他进了
还有一次提示内存不足崩溃,自动分配3G内存不够?那就多分点啊,真的不够了加个提示,不要搞心态啊

### 重现步骤

指定jdk19
进入1.19.2[成功]
保持指定jdk19不变,删除jdk19文件
再次进入[成功]
mc卡住,pcl崩溃

正常启动游戏[纯正常,没有任何操作]
内存不足,mc崩溃[自动分配了3G,我电脑是16G]

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10273585/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10273587/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10273588/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10273589/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10273590/Log5.txt)
[错误报告-2022-12-21_8.16.10.zip](https://github.com/Hex-Dragon/PCL2/files/10273598/-2022-12-21_8.16.10.zip)

**Comment by LTCatt** [comment]
自己作不管。
