### ISSUE TITLE
游戏窗口大小不对

### ISSUE THREAD

**Issue by ZS2147483647** [Hex-Dragon/PCL2#658]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

1.13以上是对的,1.12.2及以下不对

### 重现步骤

指定窗口大小[1920*1080]
启动1.13
正常
启动1.12.2
窗口从右下角出来并且非常巨大[电脑分辨率3200*2000,整个屏放不下]

### 日志与附件

![0fb5f7bb517e8e28ee56e3c93f87345](https://user-images.githubusercontent.com/121028009/208814440-769e66f6-4dbf-426d-85c3-74659bd92403.png)
![bcc3c15bb6f494739e2839f513966e1](https://user-images.githubusercontent.com/121028009/208814443-f81123de-5634-4fec-9827-7450a39c4dcc.png)
![2debe88beee534923fe56170f83d912](https://user-images.githubusercontent.com/121028009/208814448-0404eb19-437f-4876-a9d8-98634a125a9e.png)

**Comment by ZS2147483647** [comment]
1.12.2以下都这样,1.13以上都正常

**Comment by LTCatt** [comment]
补充启动后的日志文件

**Comment by ZS2147483647** [comment]
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10277210/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10277211/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10277212/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10277213/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10277215/Log5.txt)

**Comment by ZS2147483647** [comment]
是不是高分辨率兼容的问题

**Comment by ZS2147483647** [comment]
但是我怎么设置1.12.2版本及以下用高分辨率兼容模式运行呢

**Comment by ZS2147483647** [comment]
我调整了一下屏幕缩放,发现他的分辨率大约是4K级别,不是我想要的1920*1080
![image](https://user-images.githubusercontent.com/121028009/208896107-82aeccda-9427-4d0e-ad61-29c00141ee64.png)

**Comment by ZS2147483647** [comment]
这么大的画面肯定说没法玩的,而且我感觉在这个版本及一下的玩家不是少数

**Comment by ZS2147483647** [comment]
![image](https://user-images.githubusercontent.com/121028009/208896735-9a06cef8-58a6-440f-b13e-ee8364a7603c.png)
发现窗口大小是可以调的,但这样的效果肯定不对

**Comment by ZS2147483647** [comment]
> ![image](https://user-images.githubusercontent.com/121028009/208896735-9a06cef8-58a6-440f-b13e-ee8364a7603c.png)发现窗口大小是可以调的,但这样的效果肯定不对

分辨率大约是1700*1000

**Comment by MartPeggy** [comment]
高分屏貌似都这样，我这边的解决方法是换一个JVM

**Comment by MartPeggy** [comment]
JVM：Dragonwell-8.13.14
JVM参数：`-d64 -XX:+AggressiveOpts -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSConcurrentMTEnabled -XX:ParallelGCThreads=8 -Dsun.rmi.dgc.server.gcInterval=3600000 -XX:+UnlockExperimentalVMOptions -XX:+ExplicitGCInvokesConcurrent -XX:MaxGCPauseMillis=50 -XX:+AlwaysPreTouch -XX:+UseStringDeduplication -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -XX:-OmitStackTraceInFastThrow -XX:+OptimizeStringConcat -XX:+UseAdaptiveGCBoundary -XX:NewRatio=3 -Dfml.readTimeout=90 -XX:+UseFastAccessorMethods`

**Comment by ZS2147483647** [comment]
@LTCatt 活跃橙F16F-7E30-6978-709E

**Comment by LTCatt** [comment]
你的解锁码：8SVhVqf/lRQyxACVnwWTTEosYLj6sSMx
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by ZS2147483647** [comment]
谢谢,不过人品居然真的有0...

**Comment by LTCatt** [comment]
这应当不是 PCL 的问题，似乎是 Minecraft 或者 JVM 的 Bug，对这个 Issue 的修复反而造成了 #856。已将更改回滚。
