### ISSUE TITLE
输入23.33档次的解锁码显示该解锁码有误

### ISSUE THREAD

**Issue by geji233** [Hex-Dragon/PCL2#665]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

输入23.33档次的解锁码显示该解锁码有误

### 重现步骤

1.获取了爱发电私信的解锁码
2.复制粘贴
3.进入pcl2-更多-关于与鸣谢-输入解锁码-错误

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10276722/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10276723/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10276724/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10276725/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10276726/Log5.txt)

**Comment by quannen** [comment]
你是不是识别码打错了？？

**Comment by LTCatt** [comment]
自行查看石墨的帮助文档，重新提交识别码
