### ISSUE TITLE
PCL 文件离奇消失

### ISSUE THREAD

**Issue by LTCatt** [Hex-Dragon/PCL2#666]
最近收到多个关于 “PCL 文件自行消失” 的报告（例如 #524 、 #612 、 #640 ），并且还有愈演愈烈的奇妙趋势，所以在这征集相关线索。
@luoyuqi11 @iPodtouch6557 @AdmireLinK @ZiHengPlazy 

----

需要注意的是， **PCL 完全不可能删除自己** ，任何运行中的 exe 文件都根本没有删除自己的权限（唯一的例外是更新时，旧版 PCL 会要求下载到的新版 PCL 来帮忙删除自己）。
也就是说，如果你正在使用 **最新版本** 的 PCL，且 PCL 自行消失，那么 **一定** 代表着是 **你的电脑上的另外一个程序删除了 PCL** 。因此，这一定不是我可以修复的 Bug。

----

考虑到最近这个问题的报告频发，我需要收集相关的线索来确定到底是怎么回事。
如果你可以复现这个问题，可以尝试使用火绒剑等行为监测工具，来确定到底是哪个程序删除了 PCL。此外，也可以附上启动的游戏版本（万一是某些 Mod 或魔改端的问题呢）、电脑的厂商（例如 #640 中的电脑是联想的）、安装的杀毒软件等各种乱七八糟的线索，因为这个问题实在是毫无头绪，万一就找到线索了呢……
当然，能用火绒剑确定删除 PCL 的程序到底是啥自然是最好的……

**Comment by ZS2147483647** [comment]
雀氏,我的pcl也删除过两次,windowsdefender认为pcl是特洛伊木马,我的电脑只装了火绒,但问题是wd的实时保护是关了的,而且当我下回来时并固定开始时,pcl的快捷方式自动回到原来的文件夹,好像系统有记忆一样
![image](https://user-images.githubusercontent.com/121028009/208902117-b4b38bc1-7f5d-4f8a-b05d-f11f579bdce9.png)

**Comment by ZS2147483647** [comment]
至于火绒剑,额,还是算了吧

**Comment by luoyuqi11** [comment]
显示在wd上，界面是这样的 
![image](https://user-images.githubusercontent.com/96615187/208902619-71a79672-0f44-41d0-bbd3-4c6d651ceb5d.png)

**Comment by luoyuqi11** [comment]
确定的程序为Windows Defender

**Comment by luoyuqi11** [comment]
我去问问微软能不能解决吧

**Comment by luoyuqi11** [comment]
我是在更新完后出现的

**Comment by LTCatt** [comment]
umm 你们用的是快照版还是正式版？正式版我有向微软提交误报的反馈。

**Comment by luoyuqi11** [comment]
快照版

**Comment by iPodtouch6557** [comment]
> um 你们用的是快照版还是正式版？正式版我有向微软提交误报的反馈。

正式版 我没向龙猫发过电

**Comment by iPodtouch6557** [comment]
我是只有那个快捷方式被删除，PCL文件正常

**Comment by iPodtouch6557** [comment]
我很确定我已把pcl文件报告为安全，而且该bug又™不稳定了 现在我的pcl2很稳定

**Comment by quannen** [comment]
我的也是,回头一看是Windows Defender的误报，我真是够了。火绒那边一点反应都没有。360和Defender反应一样

**Comment by luoyuqi11** [comment]
这里建议龙猫跟微软报告一下

**Comment by quannen** [comment]
我加了排除区，也是对Defender无语了
我现在来尝试着去报告一下

**Comment by quannen** [comment]
我用的快照2.4.4

**Comment by luoyuqi11** [comment]
那就去报告吧

**Comment by iPodtouch6557** [comment]
> 我用的快照2.4.4

建议龙猫吧快照的版本号和正式版版本号分开

**Comment by LTCatt** [comment]
快照版的误报没有办法，因为更新后的快照版 MD5 不一样。
我对每个正式版的 PCL2 都提交了误报反馈，正式版应当不存在被 Defender 删除的情况。

**Comment by luoyuqi11** [comment]
那要怎么办，不能一直下吧

**Comment by quannen** [comment]
> 那要怎么办，不能一直下吧

可以添加排除区（defender

**Comment by Big-Cake-jpg** [comment]
> 那要怎么办，不能一直下吧

Windows 安全中心 -> 病毒和威胁防护 -> 病毒和威胁防护设置 -> 添加或删除排除项 -> 添加排除项

**Comment by iPodtouch6557** [comment]
> 

联想直接添加可以吗
awa

**Comment by quannen** [comment]
可以

发件人: ***@***.***>
发送时间: 2022年12月23日 8:25
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [Hex-Dragon/PCL2] PCL 文件离奇消失 (Issue #666)


联想直接添加可以吗
awa

―

**Comment by iPodtouch6557** [comment]
我的windows defender我不会开

**Comment by iPodtouch6557** [comment]
麦克菲也打不开，除非下载到一个真的有病毒的文件，但我已经半年没见过了

**Comment by iPodtouch6557** [comment]
今天又消失了……
我打开文件夹后一不留神，又没了，***
截图
![image](https://user-images.githubusercontent.com/118656946/209247944-cde657f3-520e-412c-b893-95da9ca42c69.png)
文件
[PCL - 副本.zip](https://github.com/Hex-Dragon/PCL2/files/10291158/PCL.-.zip)

**Comment by Louis-ZYH** [comment]
这个bug已经进入了混沌领域……

**Comment by Louis-ZYH** [comment]
疑惑.jpg

**Comment by iPodtouch6557** [comment]
啊这

https://user-images.githubusercontent.com/118656946/209248959-358114a5-8452-4c28-90d0-e085f3fc1606.mp4

**Comment by iPodtouch6557** [comment]
他就是自己消失
不说了，去花雨庭了…………

**Comment by quannen** [comment]
HMCL和BakaXL了解一下

**Comment by quannen** [comment]
胆怯.jpeg

**Comment by quannen** [comment]
诶，龙猫可以去问问TT702，看看为什么BakaXL不会被wd误杀
（至于为什么会这么想，是因为BakaXL好像也是基于.net的

**Comment by quannen** [comment]
虽然BakaXL并不开源............

**Comment by iPodtouch6557** [comment]
内部植入？

**Comment by quannen** [comment]
发错了……….考虑到源代码不一样，无法借鉴，所以我给删了

**Comment by LTCatt** [comment]
> 他就是自己消失 不说了，去花雨庭了…………

火绒加自定义规则看看是啥干的？

**Comment by quannen** [comment]
不用看了，就是wd干的Message ID: ***@***.***>

**Comment by quannen** [comment]
> > 他就是自己消失 不说了，去花雨庭了…………
> 
> 火绒加自定义规则看看是啥干的？

![208902619-71a79672-0f44-41d0-bbd3-4c6d651ceb5d](https://user-images.githubusercontent.com/118090890/209286343-814662f2-65ad-45a7-b757-6e9bbe9be68a.png)

**Comment by quannen** [comment]
借鉴一下不要介意@luoyiqi11

**Comment by luoyuqi11** [comment]
不介意，拿去

**Comment by quannen** [comment]
我电脑上wd直接自爆说自己删除了PCL2

**Comment by quannen** [comment]
都不用查

**Comment by luoyuqi11** [comment]
我是用火绒看到的

**Comment by LTCatt** [comment]
看起来确实是 Windows Defender 的锅，这个我真没办法……

**Comment by quannen** [comment]
所以在这里提供线索无奖..........

**Comment by 212112111zwl** [comment]
我今天也遇到了这个问题，但奇怪的是wd和火绒的防护记录里都没有找到关于pcl2的，但它就是离奇的不见了

**Comment by quannen** [comment]
> 我今天也遇到了这个问题，但奇怪的是wd和火绒的防护记录里都没有找到关于pcl2的，但它就是离奇的不见了

正常，习惯就好

**Comment by 212112111zwl** [comment]
> 我今天也遇到了这个问题，但奇怪的是wd和火绒的防护记录里都没有找到关于pcl2的，但它就是离奇的不见了

我用火绒加了一个自定义防护规则，用几天看看能不能拦截……

**Comment by ZiHengPlazy** [comment]
当时不是说放在桌面上会被删除么 现在看来跟桌面大概没关系了

**Comment by ZiHengPlazy** [comment]
> 雀氏,我的pcl也删除过两次,windowsdefender认为pcl是特洛伊木马,我的电脑只装了火绒,但问题是wd的实时保护是关了的,而且当我下回来时并固定开始时,pcl的快捷方式自动回到原来的文件夹,好像系统有记忆一样[我在前后都没有运行pcl或游戏,也就是说这个操作是完全静默的,火绒全盘扫描没报毒,wd把我的PVZβ6.25杀了也没爆出其它的来,以下是两次扫描wd对pcl的评价].至于火绒剑,还是算了吧[Redmi 15 PRO] ![image](https://user-images.githubusercontent.com/121028009/208902117-b4b38bc1-7f5d-4f8a-b05d-f11f579bdce9.png)

是的pvzβ也有相同的情况 会莫名其妙被删并且查不到日志

**Comment by 212112111zwl** [comment]
我设了火绒的自定义防护，结果每次一开机wd都会趁火绒没起来把pcl删了（好像是的）。我在关机前改了一下pcl2.exe的文件名和后缀，wd开机时竟然就没删

**Comment by Sitadhalur** [comment]
最新的版本仍会出现问题，已经连续三天每天都自动被删除了，快捷方式、开始菜单磁贴一并消失。关键这是完全静默的，电脑上只装了火绒，火绒隔离区和日志里完全没有记录，windows defender拦截记录里也空空如也。似乎越频繁使用，自动消失的概率越大

**Comment by Sitadhalur** [comment]
最新的版本仍会出现问题，版本为快照2.5.2(285.0)，系统是win11。在平时正常游玩时不会遇到问题，但是第二天一早启动电脑时就发现PCL2不见了，目前已经连续三天每天都自动被删除了，快捷方式、开始菜单磁贴一并消失(用exlorer patcher实现的win10磁贴)。只有快照版有此问题，电脑里dev 0.4.4,，alpha 1.5.6，正式版2.3.2都从未遇到问题。关键这是完全静默的，电脑上只装了火绒，火绒隔离区和日志里完全没有记录，windows defender拦截记录里也空空如也。此前有几个月没有玩MC，PCL2一直都是正常的，最近才频繁出现，似乎越频繁使用，自动消失的概率越大

**Comment by Sitadhalur** [comment]
我是把PCL2放在C盘的自建文件夹下的。离奇的是，我把曾很久以前允许的威胁Trojan/Win32/wacatac.b!ml（疑似PCL2报毒）不允许了之后，微软并没有删除PCL2，并且能够正常运行。目前它的完好状态是属于薛定谔的情况

**Comment by iPodtouch6557** [comment]
> 

快照会这样子是因为只有正式版才会提交安全样本，快照不会

**Comment by Adsicmes** [comment]
通过windows安全审计日志查到确实是`C:\ProgramData\Microsoft\Windows Defender\Platform\***\MsMpEng.exe`删除的PCL2

调查方法: 对PCL2所在文件夹下子目录与子文件启用它们的审核属性，以便在事件查看器中记录下文件操作记录
[Link](https://juejin.cn/s/windows%E6%96%87%E4%BB%B6%E5%88%A0%E9%99%A4%E8%AE%B0%E5%BD%95%E6%97%A5%E5%BF%97)

发现`MsMpEng.exe`对PCL2的exe执行了一个类型为DELETE的操作

调查相关信息的时候貌似`这个程序是只有在有写入可疑(可执行？)文件时会运行` [Link](https://blog.csdn.net/weixin_42156940/article/details/112958445)
也有其他资料显示这个文件似乎还会执行定期扫描，而且不幸的是没有办法更改定期扫描的周期

但是我认为在有写入可疑的时候是会执行的，因为我电脑中有两份PCL2，目录结构如下
```
Dir
├─ Plain Craft Launcher 2.exe *
└─ server
       └─ Plain Craft Launcher 2.exe
```
其中带`*`的是我经常使用启动游戏的，而`server`下的那个只作为备份，没有打开过，被删除的只有带`*`的那个文件，也就是我经常拿来启动游戏的。

如果在自己电脑上做改动有可能有效的方法可能有
- 组策略关闭windows defender [Link](https://blog.csdn.net/Castlehe/article/details/117818019)
- 火绒添加自定义防护策略，禁止删除PCL2的文件

我正在尝试第二种方法，第一种似乎在我电脑是没有效果，预计火绒的自定义防护规则会在电脑运行期间起作用，但如上面某位用户所说会在电脑启动时，火绒启动前删除文件。

如若第二种方法也没有效果，有一个折中的办法，就是写一份脚本，内容为将backup的PCL2复制到自己经常用的那个位置，并添加启动项，也可以做到类似防止删除的效果。

**Comment by Adsicmes** [comment]
我近期也频繁出现此类问题，正在寻求解决方法

**Comment by iPodtouch6557** [comment]
组策略修改了啥用也没，后来是装了个火绒之后一周就完全好了，并且没复发过，很魔幻……

**Comment by Louis-ZYH** [comment]
> 组策略修改了啥用也没，后来是装了个火绒之后一周就完全好了，并且没复发过，很魔幻……

很简单，Windows Defender在检测到其他安全软件之后就完全摆烂了（可以这么理解），防护功能完全托给安全软件

**Comment by Louis-ZYH** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/115140320/c3d1d7f0-9b63-4720-a7ca-902b3e505ad4)


> > 组策略修改了啥用也没，后来是装了个火绒之后一周就完全好了，并且没复发过，很魔幻……
> 
> 很简单，Windows Defender在检测到其他安全软件之后就完全摆烂了（可以这么理解），防护功能完全托给安全软件

上面是示例

**Comment by iPodtouch6557** [comment]
是一周之后才好的，所以很魔幻（

**Comment by SuoHouDaiShi** [comment]
系统：Windows 10 22H2 截图于2023年6月28日
不确保巨硬在以后的更新中砍掉排除项！不确保巨硬在以后的更新中砍掉排除项！！不确保巨硬在以后的更新中砍掉排除项！！！
正解：无需各种杀毒软件，只需要在MSDerfender里添加排除项就OK
请按照图示操作
![1](https://github.com/Hex-Dragon/PCL2/assets/119282947/89452898-85da-4c84-9547-c73a1a726993)
![2](https://github.com/Hex-Dragon/PCL2/assets/119282947/e7d9e86c-baa2-4090-b110-3046f2c1e209)
![3](https://github.com/Hex-Dragon/PCL2/assets/119282947/6ad62a0b-eaf7-44ad-90f4-d853f5fa69fb)
![4](https://github.com/Hex-Dragon/PCL2/assets/119282947/d52223bd-af4b-46a9-a344-78d263334c69)
![5](https://github.com/Hex-Dragon/PCL2/assets/119282947/45a349c0-6ff0-4dab-800a-e1c4d627df68)
![6](https://github.com/Hex-Dragon/PCL2/assets/119282947/5645a248-e8ce-4eac-99b7-7d22cfe985ad)
![7](https://github.com/Hex-Dragon/PCL2/assets/119282947/3e92020e-8505-4c66-9258-38c335c429fe)
![8](https://github.com/Hex-Dragon/PCL2/assets/119282947/47991499-e694-4bdd-82ad-7330839b1db6)

**Comment by iPodtouch6557** [comment]
我联想电脑没排除项这玩意，必须装火绒并且等一段时间才好

**Comment by iPodtouch6557** [comment]
另外补充，实在不能解决有一个不是办法的办法：复制一大堆副本，这样起码能顶一小段时间……

**Comment by wuyuncheng-26** [comment]
在这里提供几个方案：
1. **通过一些软件卸载** Windows 安全中心，可以在 GitHub 上找到这类软件
2. 给你的 Windows 安全中心**添加排除项**
3. 可以使用其他**靠谱**的杀毒软件顶替 Windows 安全中心

**Comment by wuliaodexiaoluo** [comment]
> 在这里提供几个方案：
> 
> 1. **通过一些软件卸载** Windows 安全中心，可以在 GitHub 上找到这类软件
> 2. 给你的 Windows 安全中心**添加排除项**
> 3. 可以使用其他**靠谱**的杀毒软件顶替 Windows 安全中心


就，你知道的，Windows Update 更新可能会包括 Microsoft Defender，然后你的 Defender 就又回来了

**Comment by clark-2468** [comment]
![image](https://github.com/user-attachments/assets/a8226f7e-6053-4298-9d2b-90f940e4bdf1)
用littleskin登录好像也会触发WD隔离
