### ISSUE TITLE
整合包搜索重置条件，版本会变成文字全部

### ISSUE THREAD

**Issue by fhh1224** [Hex-Dragon/PCL2#667]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在下载整合包页面的搜索整合包部分时，点击重置条件，版本框会变成文字全部

### 重现步骤

1、下载
2、整合包
3、重置条件

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10277866/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10277867/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10277868/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10277869/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10277870/Log5.txt)

**Comment by Big-Cake-jpg** [comment]
这不是正常行为吗……

**Comment by fhh1224** [comment]
> 这不是正常行为吗......
![image](https://user-images.githubusercontent.com/99572573/209024232-0c0182ce-8b48-446a-bc96-50a75e9e9a15.png)
点重置后就这样
![image](https://user-images.githubusercontent.com/99572573/209024250-131e910c-f643-4f16-ad45-f68011bdeab2.png)

**Comment by fhh1224** [comment]
Issue

**Comment by fhh1224** [comment]
活跃橙解锁 8F24-7F3D-BC5E-1BF6

**Comment by LTCatt** [comment]
你的解锁码：keuOzBmMvwInkVSZ8XQOfuWOrqavZjdC
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
