### ISSUE TITLE
启动脚本启动不完全！！！

### ISSUE THREAD

**Issue by Eraser-cn** [Hex-Dragon/PCL2#668]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

当使用启动脚本(LatestLaunch.bat)启动1.12.2forge我的世界的时候，一些mod将不会启动，导致游戏不完全，或直接崩溃！

### 重现步骤

1、打开启动脚本(LatestLaunch.bat)
2、过一段时间游戏启动，但有些mod并未加载

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10282539/Log1.txt)

**Comment by Big-Cake-jpg** [comment]
为什么要使用启动脚本启动......

**Comment by iPodtouch6557** [comment]
> 为什么要使用启动脚本启动......

确实会有人闲的没事用这个启动 我就试过（对了 既然没人用这个功能 不能删了吗）
（不能用最简洁的方式给用户最好的体验吗）

**Comment by Eraser-cn** [comment]
因为这是一个bug，如果得不到修复，不如砍掉！有些人是不想这么麻烦的，我直接把启动脚本放到桌面，一步启动！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月22日(星期四) 上午8:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Hex-Dragon/PCL2] 启动脚本启动不完全！！！ (Issue #668)





  
为什么要使用启动脚本启动......
  
确实会有人闲的没事用这个启动 我就试过（对了 既然没人用这个功能 不能删了吗）
 （不能用最简洁的方式给用户最好的体验吗）

**Comment by Big-Cake-jpg** [comment]
LatestLaunch.bat 脚本应该只是 PCL2 为了加快版本启动速度而缓存的启动参数，这样不必每一次都重新生成

**Comment by Eraser-cn** [comment]
我觉得&nbsp; !可能!&nbsp; &nbsp;未必，但我觉得应该优化一下，让玩家实现一键启动，因为启动器的初衷就是快速、便捷、方便的游玩，希望修复一下的。这是我的想法。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月22日(星期四) 上午9:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Hex-Dragon/PCL2] 启动脚本启动不完全！！！ (Issue #668)





 
LatestLaunch.bat 脚本应该只是 PCL2 为了加快版本启动速度而缓存的启动参数，这样不必每一次都重新生成

**Comment by LTCatt** [comment]
请上传生成的启动脚本和游戏版本 json

**Comment by Eraser-cn** [comment]
我已全部替换为txt形式
[LatestLaunch.txt](https://github.com/Hex-Dragon/PCL2/files/10284200/LatestLaunch.txt)
[launcher_profiles.txt](https://github.com/Hex-Dragon/PCL2/files/10284201/launcher_profiles.txt)

**Comment by LTCatt** [comment]
额，在版本设置里打开版本文件夹，上传那个 json……
![image](https://user-images.githubusercontent.com/40348278/209072175-c8c66743-ec4d-47d8-a6d1-7468685632cb.png)

此外，还需要你用 PCL 启动一次游戏，然后上传 Log1，这样 Log 里才有启动信息 =。=

**Comment by Eraser-cn** [comment]
启动是正常的，只是启动脚本。。。。。
[Piko-client-Namida - 副本.txt](https://github.com/Hex-Dragon/PCL2/files/10284388/Piko-client-Namida.-.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10284394/Log1.txt)

**Comment by LTCatt** [comment]
我觉得这不像是实际 Bug，更像你搞错了什么……
我没法重现，并且我也没看出哪有问题……
如果其他人也出现了再考虑修复吧……
