### ISSUE TITLE
下载带forge的游戏失败（可能有提交过的吧……）

### ISSUE THREAD

**Issue by MCZJHAndrew** [Hex-Dragon/PCL2#669]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://user-images.githubusercontent.com/121218409/209075421-2436dcef-20ab-4939-a7f6-60457fcb3e54.png)
下载游戏只要带forge就卡在这个阶段，都是在安装forge时停止的

### 重现步骤

1、只要下载带有forge的1.19版就有

### 日志与附件

[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10284497/Log5.txt)

**Comment by opopi5236** [comment]
有的有的，我的直接是啥forge都下不了，包括正式版和快照版

**Comment by LTCatt** [comment]
感觉你这个应该是 forge 的问题……

**Comment by opopi5236** [comment]
不知道为什么，在今天我的快照版又可以下了，同时我几个朋友的pcl也出现了同样的问题

**Comment by MCZJHAndrew** [comment]
> 不知道为什么，在今天我的快照版又可以下了，同时我几个朋友的pcl也出现了同样的问题

阿这……

**Comment by xuzehao2012** [comment]
我的话只有1.12
