### ISSUE TITLE
无法连接到服务器

### ISSUE THREAD

**Issue by linShuoVincent** [Hex-Dragon/PCL2#670]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

已排查原因，未将杀毒软件屏蔽启动器联网，且mcbbs、curseforge等论坛、模组下载网站正常访问，但是启动器一直报错无法连接远程服务器（包括但不限于pcl服务器、mcbbs）
![Plain_Craft_Launcher_2_专业版_YbsYUGNpcr](https://user-images.githubusercontent.com/97793269/209076884-c32609a6-7927-46e8-b740-50d5aa65363b.png)
![Plain_Craft_Launcher_2_专业版_GysEs0Zyd8](https://user-images.githubusercontent.com/97793269/209076889-affed451-900c-467b-89c0-f5c8d14c5c0c.png)
![Plain_Craft_Launcher_2_专业版_yWWIkTPIbA](https://user-images.githubusercontent.com/97793269/209076998-06c215ce-78b4-44dc-9a37-70d52b865132.png)

### 重现步骤

无意间出现，暂时今天有这个问题（2022.12.22）

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10284546/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10284547/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10284548/Log5.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10284596/Log2.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10284598/Log1.txt)

**Comment by linShuoVincent** [comment]
> 

LittleSkin,CF,mcbbs,mcmod当天都能正常访问但启动器无法连接（估计是启动器问题，版本2.4.4）

**Comment by LTCatt** [comment]
确实是你的网络问题，和启动器无关
（报错是统一的 500）
