### ISSUE TITLE
无法安装mod

### ISSUE THREAD

**Issue by Crushedfish4740** [Hex-Dragon/PCL2#671]
### 检查项

- [x] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我选择的版本是1.19.2，fabric版本是0.14.9，可是当我将mod文件拖到pcl的主界面时，pcl让我选择一个可安装mod的版本

### 重现步骤

1、安装一个1.19.2的版本，fabric版本为0.14.9
2、选择该版本
3、将mod文件拖入pcl的主界面

### 日志与附件

[Uploading Log1.txt…]()
[Uploading Log2.txt…]()
[Uploading Log3.txt…]()
[Uploading Log4.txt…]()
[Uploading Log5.txt…]()

**Comment by bwtx2022** [comment]
日志未上传完成，请重新上传

**Comment by Crushedfish4740** [comment]
日志在这里，上面那个不会改
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10291044/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10291045/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10291047/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10291048/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10291049/Log5.txt)

**Comment by Crushedfish4740** [comment]
日志在这里，上面那个不会改
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10291053/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10291055/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10291056/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10291058/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10291060/Log5.txt)

**Comment by LTCatt** [comment]
日志中没有找到这些提示。
尝试重现一次这个 Bug，然后再重新上传日志？

**Comment by Crushedfish4740** [comment]
> 日志中没有找到这些提示。 尝试重现一次这个 Bug，然后再重新上传日志？

我只能说那天我手气太好了，现在这个bug总是不出来

**Comment by LTCatt** [comment]
那先算了……如果之后复现出来了可以继续在这里回复
