### ISSUE TITLE
Fabric 崩溃误判 Forge 与 OptiFine 不兼容

### ISSUE THREAD

**Issue by Crushedfish4740** [Hex-Dragon/PCL2#675]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃不是 PCL2 的原因，请 **不要** 提交反馈。你可以在 QQ 群里或者论坛找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是游戏本身的问题，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

先用微软登录启动一次游戏，不要关闭它，再用离线登录启动一次游戏，游戏就会崩溃。
另外，pcl分析的崩溃原因也有问题。我用的版本是1.19.2，fabric版本为0.14.9，但pcl提示说是forge与optifine不兼容。

### 错误报告、日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10291191/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10291192/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10291193/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10291194/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10291195/Log5.txt)

**Comment by Big-Cake-jpg** [comment]
这不就是多开游戏导致的崩溃嘛（

**Comment by LTCatt** [comment]
导致崩溃的是 MossFrp Mod，并非启动器问题

**Comment by LTCatt** [comment]
你的解锁码：urt8cMYQX1A4J+LHERz9OGsJRmns9asu
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
