### ISSUE TITLE
Minecraft低版本打不开， 提示 “Minecraft 出现错误”

### ISSUE THREAD

**Issue by zhengtong15** [Hex-Dragon/PCL2#678]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃不是 PCL2 的原因，请 **不要** 提交反馈。你可以在 QQ 群里或者论坛找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是游戏本身的问题，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

1.12.2打不开，1.8也打不开，显示系统找不到指定的路径

### 错误报告、日志与附件

[错误报告-2022-12-23_上午_10.58.34.zip](https://github.com/Hex-Dragon/PCL2/files/10291815/-2022-12-23_._10.58.34.zip)
[错误报告-2022-12-23_上午_11.14.11.zip](https://github.com/Hex-Dragon/PCL2/files/10291816/-2022-12-23_._11.14.11.zip)

**Comment by zhengtong15** [comment]
1.18.2也打不开

**Comment by zhengtong15** [comment]
只有1.19及以上能打开
很奇怪

**Comment by ComputerCPT** [comment]
请留下你的下载路径

**Comment by zhengtong15** [comment]
?

**Comment by zhengtong15** [comment]
中间有变过路径

**Comment by zhengtong15** [comment]
我补过文件，但还不行

**Comment by LTCatt** [comment]
其他启动器可以启动吗？
如果可以的话，留一个 QQ，可能要远程解决……

**Comment by zhengtong15** [comment]
可以
我没QQ

**Comment by zhengtong15** [comment]
BakaXL可以

**Comment by zhengtong15** [comment]
ohhh
1.16.5可以了

**Comment by zhengtong15** [comment]
我又改变路径了

**Comment by zhengtong15** [comment]
都可以了
看来是路径问题

**Comment by zhengtong15** [comment]
没事了，谢谢
