### ISSUE TITLE
Mod 管理中允许筛选可更新/启用/禁用的 Mod

### ISSUE THREAD

**Issue by ComputerCPT** [Hex-Dragon/PCL2#679]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

在mod管理界面中的 管理卡片 中分别添加 筛选禁用模组 和 筛选启用模组 按键
点击后只显示 已禁用模组/已启用模组

### 原因

我需要这个功能来筛选出已被我禁用的模组后把不必要的模组删去节省内存，想必很多人都有这需求，但如果没有这个功能，就不能在游戏内部操作了。并且在文件夹中，系统不会因扩展名不同而区分已禁用模组和启用模组，使分类过程变得无比麻烦。

**Comment by xxtg666** [comment]
在文件夹中点第一行的类型进行排序不是更方便么

**Comment by ComputerCPT** [comment]
> 在文件夹中点第一行的类型进行排序不是更方便么

不一定每个人都知道，而且那样看不到模组简介，不易分辨一些从名字上看不出来作用的模组

**Comment by DuckDuckStudio** [comment]
> 在文件夹中点第一行的类型进行排序不是更方便么

对于需要筛选出需要更新的mod的情况呢？
