### ISSUE TITLE
启动整合包经常卡在白屏的加载页面

### ISSUE THREAD

**Issue by HanbingYueyu** [Hex-Dragon/PCL2#680]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

启动游戏的时候经常会白屏,卡着一直没反应,但是有的时候可以启动，日志和报告我都提交了。

还有一个问题就是pcl安装的整合包无法用hmcl启动,会直接报错,

### 重现步骤

启动游戏

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10292465/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10292466/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10292468/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10292469/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10292474/Log1.txt)
[错误报告-2022-12-23_14.14.25.zip](https://github.com/Hex-Dragon/PCL2/files/10292478/-2022-12-23_14.14.25.zip)

**Comment by xxtg666** [comment]
整合包mods多本来就要加载一会啊……一直白屏是游戏本身的问题，与PCL无关

**Comment by xxtg666** [comment]
我记得hmcl修改过版本json的来着？

**Comment by HanbingYueyu** [comment]
> 整合包mods多本来就要加载一会啊……一直白屏是游戏本身的问题，与PCL无关

不是时间的问题，是一直白屏等了十几分钟都没反应，正常启动的话只要一两分钟就可以了
不清楚和pcl启动器有没有关系，我同样的包用hmcl安装启动就不会出现卡白屏的问题

**Comment by LTCatt** [comment]
检查安装后的版本能否用 HMCL 启动？

> 还有一个问题就是pcl安装的整合包无法用hmcl启动,会直接报错,

这个 Bug 可以单独提交一个新 issue。附带上整合包的下载。

**Comment by HamsterYrc** [comment]
有人说是pcl联机自检有bug

**Comment by LTCatt** [comment]
PCL 目前没有联机功能，哪来的什么自检……

**Comment by HamsterYrc** [comment]
忘了说了，我也出现了这样的情况，并且那个整合包有170多个mod，卡白屏可以断网，出了mojang的logo就可以再把网开回来

**Comment by LTCatt** [comment]
这个我知道……这是 MC 的问题，不是 PCL 的……
