### ISSUE TITLE
背景音乐支持FLAC与更多的音频格式

### ISSUE THREAD

**Issue by Nasnda** [Hex-Dragon/PCL2#685]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

个性化背景音乐功能可以支持更多的音频格式

### 原因

PCL II背景音乐使用FLAC格式播放会出现"HRESULT:0x80070002"的错误代码

**Comment by Big-Cake-jpg** [comment]
咱没必要用 `.flac` 无损音质吧……

**Comment by Nasnda** [comment]
![Snipaste_2023-01-01_19-08-16](https://user-images.githubusercontent.com/121296760/210168568-b8699752-c1a7-4a63-ba27-dfcf1718ee16.png)
...

**Comment by Nasnda** [comment]
> 咱没必要用 无损音质吧......`.flac`

![Snipaste_2023-01-01_19-22-00](https://user-images.githubusercontent.com/121296760/210169004-7ec03100-7d71-4248-a856-138c51b22df7.png)

**Comment by LTCatt** [comment]
出现 `HRESULT` 异常应当是你的电脑的设置、驱动、环境等出现问题，不是 PCL 这边的问题……
你可以去谷歌一下看看。
