### ISSUE TITLE
自动分配内存相关问题

### ISSUE THREAD

**Issue by WratithCr** [Hex-Dragon/PCL2#688]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

不论PCL启动器中设置内存为多大或者是自动设置
进入游戏后F3查看到的java配置一直都是716MB

### 重现步骤

我也不清楚这个bug是什么情况，似乎和java设置也有关？
原本java分配内存不足还是小问题顶多卡顿，现在直接客户端崩掉了（

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10298318/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10298319/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10298320/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10298321/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10298322/Log5.txt)
![？](https://user-images.githubusercontent.com/121338387/209430435-81b4f01e-58f0-4620-821b-97b8b16950db.jpg)
![？？](https://user-images.githubusercontent.com/121338387/209430439-b21b4ff1-bf0f-4a45-a468-853e9c68a155.jpg)
[错误报告-2022-12-24_17.36.35.zip](https://github.com/Hex-Dragon/PCL2/files/10298326/-2022-12-24_17.36.35.zip)

**Comment by LTCatt** [comment]
因为你电脑真的没剩内存了……

**Comment by WratithCr** [comment]
> 因为你电脑真的没剩内存了……

注意前提，不论剩多少也无关，换句话说我只给PCL 500MB电脑剩4G（任务管理器看的）内存也没用，该是716还是716

**Comment by LTCatt** [comment]
如果其他启动器启动没有问题再考虑修复

**Comment by WratithCr** [comment]
> 如果其他启动器启动没有问题再考虑修复

感谢提醒，更换了HMCL启动器java的自动配置问题解决了
![！！](https://user-images.githubusercontent.com/121338387/209662201-2d7b6c01-4d8e-4d09-af1a-1c0f6d53d86f.jpg)

**Comment by LTCatt** [comment]
![image](https://user-images.githubusercontent.com/40348278/211066072-1edfe8e4-1288-431c-9ec2-b695a19caab5.png)

你看看你的版本设置里是不是调的自动配置？

**Comment by LTCatt** [comment]
超时关闭……
