### ISSUE TITLE
自动选择 Mod 下载文件夹时忽略了 MC 的最小版本

### ISSUE THREAD

**Issue by WForst-Breeze** [Hex-Dragon/PCL2#691]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

下载mod时，误将 1.19.3 版本的 mod 判断为 1.19.2 的 mod，导致在“选择保存位置”中打开了 1.19.2 版本的模组文件夹（其他版本简单测试后应该没有问题）详见重现步骤

### 重现步骤

1. 确保你的mc文件夹中有一个含相同模组加载器的 1.19.2、1.19.3 版本及一个**其他版本**
2. 在版本选择界面选择那个**其他版本**
3. 前往mod下载界面，尝试下载1.19.3的任意模组
4. 问题复现，弹出的**选择保存位置**窗口中打开了 **1.19.2** 版本的模组文件夹

详细操作视频：[[蓝奏云]](https://rbreezeqing-sc.lanzouy.com/iYivH0jd7i6j)

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10299416/Log2.txt)
```
[11:59:45.596] [Control] 按下单击列表项：[1.19.3] Mouse Tweaks 2.24 Fabric
[11:59:45.600] [Download] 允许 Forge：False，允许 Fabric：True
[11:59:45.626] [Download] 使用适合的游戏版本作为默认下载位置（1.19.2-Fabric 0.14.12）
```

**Comment by LTCatt** [comment]
绝大多数情况下，Mod 是兼容 MC 的不同小版本的，所以只检查了主要版本。如果有问题推荐手动调整。
事实上很多时候会因为 Mod 作者没有更新 Mod 的支持版本（例如在 1.16.4 发布的 Mod，之后 Mojang 更新了 1.16.5，但作者就没有把 1.16.5 加进支持的列表）导致版本判断并不准确，权衡后才这样做的。

**Comment by LTCatt** [comment]
基于 #5138 的讨论 reopen
