### ISSUE TITLE
隐藏主题“活跃橙”解锁前右击的反馈提交小改动

### ISSUE THREAD

**Issue by Jerry25565** [Hex-Dragon/PCL2#695]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [x] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

隐藏主题“活跃橙”解锁前右击的反馈提交界面中，点击“不需要”按钮时仍会用默认浏览器弹出https://github.com/Hex-Dragon/PCL2/issues/网址。
虽然影响不大，但是改一下能更好。

### 原因

防止有些人用的默认浏览器比较烦人（比如360（小声））。
其实也无关紧要吧（？）

**Comment by LTCatt** [comment]
与 #673 重复
