### ISSUE TITLE
添加新的登录方式 （比如PCL账号  

### ISSUE THREAD

**Issue by CruelBooch** [Hex-Dragon/PCL2#696]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

## 将微软或Mojang账号绑定与此账号  
方便在多台设备上登录
## 绑定设备信息 并制作设备控制面板
 方便远程退出其他设备的登录
## 隐藏主题每次都需要用解锁码和设备码来使用 
若更新设备 就需要从爱发电获取新的解锁码 不方便 
而这样就可以解决这些问题

我知道这个功能可能会消耗一定的财力资源 但我认为很实用

### 原因

（示例）
我需要这个功能来登录。很多人都有快捷登录的需求，但如果没有这个功能，就不能登录了。

**Comment by Big-Cake-jpg** [comment]
https://github.com/Hex-Dragon/PCL2/issues/315#issuecomment-1301718331
