### ISSUE TITLE
pcl安装的整合包无法用hmcl启动

### ISSUE THREAD

**Issue by HanbingYueyu** [Hex-Dragon/PCL2#705]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

pcl安装的整合包无法用hmcl启动
目前我试过的整合包有
create:above and beyond:https://www.mcmod.cn/modpack/312.html
create to sky:https://www.mcmod.cn/modpack/485.html

### 重现步骤

1、点击xxxx
2、往下滚，然后点击xxxx
无

### 日志与附件

[minecraft-exported-crash-info-2022-12-26T18-20-10.zip](https://github.com/Hex-Dragon/PCL2/files/10303017/minecraft-exported-crash-info-2022-12-26T18-20-10.zip)

**Comment by bwtx2022** [comment]
你可能得去找 HMCL 那边看看.jpg

**Comment by trustedinster** [comment]
你可以去[HMCL反馈界面](https://gitee.com/huanghongxun/HMCL/issues)看看

**Comment by LTCatt** [comment]
@Glavo 看看是哪边的锅……？是 HMCL 启动的问题还是我安装的问题……

**Comment by Glavo** [comment]
无法复现，请尝试更新 HMCL 至最新版本。

**Comment by LTCatt** [comment]
如果还要交 issue 的话交 HMCL 那边去 =。=
