### ISSUE TITLE
对于“提交新反馈”的指向链接的小改动

### ISSUE THREAD

**Issue by ComputerCPT** [Hex-Dragon/PCL2#710]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

启动器中 更多-反馈-提交新反馈按钮的指向链接改为 https://github.com/Hex-Dragon/PCL2/issues/new/choose 可能更好

不是特别急，也许可以改一下

### 原因

不然“提交新反馈”的指向链接与“查看反馈列表”的指向链接重复

**Comment by WForst-Breeze** [comment]
个人意见哈：提交新反馈前，反馈者需要前往 issues 页面进行搜索后再进行反馈，如果更改为您所述的链接，（如果这个反馈者会去搜索的话）**还是需要回到 issues 页面** ，直接跳转到选择反馈类型页面的话显得有点多此一举了。
- 提交新反馈：弹出询问是否需要打开 logs 文件夹后，打开 issue 页面
- 查看反馈列表：直接打开 issue 页面

还是有点区别的（

**Comment by ComputerCPT** [comment]
> 个人意见哈：提交新反馈前，反馈者需要前往 issues 页面进行搜索后再进行反馈，如果更改为您所述的链接，（如果这个反馈者会去搜索的话）**还是需要回到 issues 页面** ，直接跳转到选择反馈类型页面的话显得有点多此一举了。
> 
> * 提交新反馈：弹出询问是否需要打开 logs 文件夹后，打开 issue 页面
> * 查看反馈列表：直接打开 issue 页面
> 
> 还是有点区别的（

可是这样的话“查看反馈列表”不就没用了吗

**Comment by ComputerCPT** [comment]
> 个人意见哈：提交新反馈前，反馈者需要前往 issues 页面进行搜索后再进行反馈，如果更改为您所述的链接，（如果这个反馈者会去搜索的话）**还是需要回到 issues 页面** ，直接跳转到选择反馈类型页面的话显得有点多此一举了。
> 
> * 提交新反馈：弹出询问是否需要打开 logs 文件夹后，打开 issue 页面
> * 查看反馈列表：直接打开 issue 页面
> 
> 还是有点区别的（

那么就没必要叫做“提交新反馈”了吧（

**Comment by LTCatt** [comment]
直接弹进 choose 的话会没法查看是否有重复反馈，这是刻意的。
两个按钮的区别 WForst-Breeze 已经说了（

**Comment by allMagicNB** [comment]
> 直接弹进 choose 的话会没法查看是否有重复反馈，这是刻意的。
> 两个按钮的区别 WForst-Breeze 已经说了（

但是，真正会检查检查项的人是可以再跳到Issue列表的
不会检查的还是不会检查，该重复还是得重复
