### ISSUE TITLE
拖拽安装mod的行为有误

### ISSUE THREAD

**Issue by Crushedfish4740** [Hex-Dragon/PCL2#714]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我使用的游戏版本是1.19.2，fabric版本是0.14.10。但是我将mod文件拖入pcl主界面时，pcl提示说让我选择一个可安装mod的版本。

### 重现步骤

1、选择一个可安装mod的版本
2、将mod文件拖入pcl主界面

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10305588/Log1.txt)

**Comment by youzi-2333** [comment]
@LTCatt 给个活跃橙……？

**Comment by LTCatt** [comment]
你的解锁码：urt8cMYQX1A4J+LHERz9OGsJRmns9asu
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

见鬼，怎么没收到这个 issue 的回复提示（

**Comment by allMagicNB** [comment]
> 你的解锁码：urt8cMYQX1A4J+LHERz9OGsJRmns9asu
> 在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
> 
> 见鬼，怎么没收到这个 issue 的回复提示（

wc，迟来了一年的解锁码（
