### ISSUE TITLE
Mod 搜索 “舒适用品-fabric” 的指向有误

### ISSUE THREAD

**Issue by Chinese-people** [Hex-Dragon/PCL2#716]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

安装模组闪退

### 重现步骤

1、点击下载-mod
2、搜索舒适用品-fabric
3、闪退

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10305758/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10305759/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10305760/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10305761/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10305762/Log5.txt)

**Comment by LTCatt** [comment]
我没法重现崩溃，日志里也没有。
是 PCL 在搜索之后闪退了，并且没有任何报错？

**Comment by Chinese-people** [comment]
已经找到原因,我在文件名前面多打了一个点

**Comment by LTCatt** [comment]
哦没事，我在尝试重现的时候发现了另一个 bug，就这样开着吧（

**Comment by Chinese-people** [comment]
我可以获得主题吗

**Comment by LTCatt** [comment]
你的解锁码：hQmej0zJU4ZQlFBwP2KYwJ58BH84zHsC
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by Chinese-people** [comment]
哦 我重装了系统 导致我的主题消失 能在给我一个吗

**Comment by allMagicNB** [comment]
> 哦 我重装了系统 导致我的主题消失 能在给我一个吗
> 

有备份注册表吗

**Comment by WorldHim** [comment]
> 哦 我重装了系统 导致我的主题消失 能在给我一个吗
> 

请发识别码
