### ISSUE TITLE
在下载mod界面能直接选择安装到某个版本

### ISSUE THREAD

**Issue by lovelysheepfield** [Hex-Dragon/PCL2#721]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [x] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

希望在下载mod界面能直接选择安装到某个版本（就像Baka XL那样），是直接在PCL里选择需要安装此mod的版本而并非windows自带的文件夹界面

### 原因

这样的话对新手来讲会更加友好，省去了一个个找文件夹的烦恼；
相比将mod拖入PCL窗口可以将下载安装2合一，更省事。

**Comment by Big-Cake-jpg** [comment]
只要你在主页选择的 Minecraft 核心安装了受支持的模组加载器，PCL2 就会自动将保存路径设置为该版本的 Mods 文件夹。

**Comment by WForst-Breeze** [comment]
PCL2 会优先将您的 mod 下载至已选择的版本中，若此核心的游戏版本或模组加载器不兼容您所选择的 mod，PCL2 会尝试寻找兼容的游戏版本并将保存路径设于此处

**Comment by lovelysheepfield** [comment]
真的耶！感谢大佬们
