### ISSUE TITLE
PCL自定义主页BUG

### ISSUE THREAD

**Issue by rongjianuo** [Hex-Dragon/PCL2#722]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

PCL自定义页面有个BUG，这个图标显示不出来https://www.minecraft.net/etc.clientlibs/minecraft/clientlibs/main/resources/favicon.ico
望修复

代码：
<local:MyCard Title="BUG测试">
    <StackPanel Margin="25,40,23,15">
        <Image Width="50" Height="50" Margin="5,15,0,15" Source="https://www.minecraft.net/etc.clientlibs/minecraft/clientlibs/main/resources/favicon.ico"/>
    </StackPanel>
</local:MyCard>

### 重现步骤

1、点击XAML文件
2、放上我的代码
3、刷新主页
4、BUG就出现了

代码：
<local:MyCard Title="BUG测试">
    <StackPanel Margin="25,40,23,15">
        <Image Width="50" Height="50" Margin="5,15,0,15" Source="https://www.minecraft.net/etc.clientlibs/minecraft/clientlibs/main/resources/favicon.ico"/>
    </StackPanel>
</local:MyCard>

### 日志与附件

[Log.txt](https://github.com/Hex-Dragon/PCL2/files/10306645/Log.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10306646/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10306647/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10306648/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10306649/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10306650/Log5.txt)

**Comment by rongjianuo** [comment]
有bug
显示不出来

**Comment by rongjianuo** [comment]
[代码.txt](https://github.com/Hex-Dragon/PCL2/files/10306668/default.txt)

**Comment by rongjianuo** [comment]
就是这个（代码.txt）

**Comment by rongjianuo** [comment]
![image](https://user-images.githubusercontent.com/119654171/209629242-8f50e7eb-7279-4c0b-8883-2955d6fb83c9.png)

**Comment by rongjianuo** [comment]
第三行打错了，删掉最后两个

**Comment by LTCatt** [comment]
换用 png 试试，这应该是它不兼容 ico

**Comment by rongjianuo** [comment]
PNG也不行啊

**Comment by rongjianuo** [comment]
[代码.txt](https://github.com/Hex-Dragon/PCL2/files/10311334/default.txt)

**Comment by rongjianuo** [comment]
![Uploading image.png…]()

**Comment by rongjianuo** [comment]
也有啊

**Comment by rongjianuo** [comment]
https://www.minecraft.net/content/dam/minecraft/misc-photos/China_Version.png

**Comment by rongjianuo** [comment]
就是不行

**Comment by Light-Beacon** [comment]
我解释一下：MC官网有防护，你这个链接不用浏览器是打不开的...所以这不是PCL的问题
