### ISSUE TITLE
可以禁用某个Java

### ISSUE THREAD

**Issue by LBZiXL** [Hex-Dragon/PCL2#723]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

1、可以在游戏Java里设置禁用某个Java，设置后PCL2不会自动选择已被禁用的Java。
2、且在功能隐藏里增加隐藏已禁用的Java选项。

### 原因

这项优化让我可以更方便地让PCL2不用某个Java启动游戏。
如果没有这项优化，我每次都必须手动设置，让操作变得很麻烦。

**Comment by WForst-Breeze** [comment]
已初步确认，感谢您的反馈~

**Comment by LTCatt** [comment]
应用面太小，不考虑制作，抱歉）

**Comment by LBZiXL** [comment]
可我真的很想要这个功能呀......(哎
