### ISSUE TITLE
联网被ban

### ISSUE THREAD

**Issue by linShuoVincent** [Hex-Dragon/PCL2#724]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

被defender用防火墙ban掉无法联网，且在允许联网后仍无法连接网络
![mmc_nOakLI5VUU](https://user-images.githubusercontent.com/97793269/209658140-c99c2945-6c7e-4958-910b-27534c999f6e.png)

### 重现步骤

1、Windows defender会定期扫描，然后禁止pcl联网，且无通知也无法更改

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10307751/Log3.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10307748/Log2.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10307746/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10307752/Log1.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10307745/Log4.txt)

**Comment by xxtg666** [comment]
加入白名单，或者关闭wd，还有不懂的请去 [Discussions](https://github.com/Hex-Dragon/PCL2/discussions) 提问
