### ISSUE TITLE
对于反馈-提交新反馈的反馈提交提醒界面的小改动

### ISSUE THREAD

**Issue by ComputerCPT** [Hex-Dragon/PCL2#725]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

反馈-提交新反馈-反馈提交提醒界面“不需要按键”适配#695

### 原因

为了适配#695的改动

如果这俩是共用一个窗口的，请忽略此条反馈

**Comment by LTCatt** [comment]
与 #673 重复

**Comment by ComputerCPT** [comment]
> 与 #673 重复

额，这算重复？ #673 是活跃橙的界面，我这个是反馈-提交新反馈的反馈提交提醒界面……？

**Comment by LTCatt** [comment]
……等下那也不对啊
现在已经没有“反馈→提交新反馈”按钮了啊

**Comment by ComputerCPT** [comment]
<img width="350" alt="image" src="https://user-images.githubusercontent.com/120709135/210708113-7c91eaa6-e4f5-424a-a7fe-12e6953178e8.png">
哇嘎嘎？这个按钮没了……？

**Comment by LTCatt** [comment]
我还是没搞懂你的描述是啥意思
“不需要按键适配 #695 ”到底是啥意思……

**Comment by ComputerCPT** [comment]
<img width="512" alt="image" src="https://user-images.githubusercontent.com/120709135/210717022-7b4da16d-3195-495a-b1b9-3c65fd076225.png">
就这个啊

**Comment by LTCatt** [comment]
点不需要就不会打开文件夹啊……有啥问题么

**Comment by ComputerCPT** [comment]
> 点不需要就不会打开文件夹啊……有啥问题么

那么如果不选择采用 #695 的建议，这条反馈也就可以close了

（或者说在这个窗口下面再加一个**取消按键**以退出，防止有人误点两次，造成不必要的麻烦）
<img width="512" alt="image" src="https://user-images.githubusercontent.com/120709135/210748178-eaf91618-016c-4a03-b770-5fb880d276ce.png">

**Comment by LTCatt** [comment]
没有采用 #695，已经在这之前又加了一个确认弹窗了

**Comment by ComputerCPT** [comment]
> 没有采用 #695，已经在这之前又加了一个确认弹窗了

好
