### ISSUE TITLE
自动安装Optifine仅仅是下载安装程序

### ISSUE THREAD

**Issue by TanChenyu** [Hex-Dragon/PCL2#729]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在自动安装Optifine时，启动器仅仅是下载安装程序，使得用户要手动安装一遍
（不清楚算不算bug，如果不是的话就改一下label）

### 重现步骤

1、点击下载，选择版本
2、往下滚，然后点击OptiFine
3、下载后去libraries找到optifine，执行`java -jar OptiFine-xxx.jar`
4、弹出安装界面

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10311475/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10311476/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10311477/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10311478/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10311479/Log5.txt)

**Comment by xxtg666** [comment]
装了之后游戏里面有不就好了么……

**Comment by TanChenyu** [comment]
> 装了之后游戏里面有不就好了么…… 这是正常安装流程，不算bug吧 如果你自动安装没成功那另说

但游戏里没有啊，我还要把OF双击安装一遍

**Comment by ZS2147483647** [comment]
请不要使用optifine,元素周期表比他好用一万倍,你就算装了游戏也有可能崩,这optifine已经烂到家了,不是龙猫能够拯救得了的

**Comment by LTCatt** [comment]
是通过自动安装安的 optifine，然后装完打开游戏没有？
具体是啥版本？

**Comment by TanChenyu** [comment]
> 请不要使用optifine,元素周期表比他好用一万倍,你就算装了游戏也有可能崩,这optifine已经烂到家了,不是龙猫能够拯救得了的

但我有个资源包要OF，对应的Fabric模组没跟上

**Comment by TanChenyu** [comment]
> 是通过自动安装安的 optifine，然后装完打开游戏没有？ 具体是啥版本？

打开了，没有；任意版本
（OF改成安装包后就一直这样）

**Comment by LTCatt** [comment]
把自动安装装完的版本文件夹发一下看看？

**Comment by TanChenyu** [comment]
> 把自动安装装完的版本文件夹发一下看看？
[1.14.2.zip](https://github.com/Hex-Dragon/PCL2/files/10326744/1.14.2.zip)

**Comment by LTCatt** [comment]
你装的是 fabric，所以 optifine 只能通过 mod 形式加载（也就是你说的安装包）。
检查你的版本设置，需要开启版本隔离。

**Comment by TanChenyu** [comment]
自己测了个试，貌似修了？
估计龙猫改了下载链接
