### ISSUE TITLE
pcl自动分配4.5G内存启动安装fabric无mod1.19.2minecraft崩溃

### ISSUE THREAD

**Issue by ZS2147483647** [Hex-Dragon/PCL2#730]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃不是 PCL2 的原因，请 **不要** 提交反馈。你可以在 QQ 群里或者论坛找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是游戏本身的问题，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如题,它显示内存不足,但4.5G我曾经启动成功过

### 错误报告、日志与附件

上传不上来

**Comment by ZS2147483647** [comment]
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10311929/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10311930/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10311931/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10311932/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10311933/Log5.txt)
[错误报告-2022-12-28_11.33.18.zip](https://github.com/Hex-Dragon/PCL2/files/10311934/-2022-12-28_11.33.18.zip)

**Comment by ZS2147483647** [comment]
他甚至内存都没跑满,4,5G根本就没真正使用就崩了

**Comment by ZS2147483647** [comment]
最多占了不到1G就崩,这肯定不是内存问题.但是没有mod也崩肯定也不是mod的问题

**Comment by ZS2147483647** [comment]
补全文件无效,所以游戏肯定没问题,离线登录也崩,和微软服务器无关

**Comment by ZS2147483647** [comment]
补充一下,hmcl在我的电脑上不能正常工作,会出问题,bakaxl压根就不会用,所以pcl是我玩mc的唯一通道,所以我也不知道其他启动器行不行

**Comment by ZS2147483647** [comment]
手动分配6个G后该崩还是崩
[错误报告-2022-12-28_12.13.03.zip](https://github.com/Hex-Dragon/PCL2/files/10312049/-2022-12-28_12.13.03.zip)

**Comment by xxtg666** [comment]
这个似乎和PCL没什么关系吧，建议去 [Discussions](https://github.com/Hex-Dragon/PCL2/discussions) 提问

**Comment by WForst-Breeze** [comment]
后续讨论请移步 #732

**Comment by xxtg666** [comment]
> 后续讨论请移步 #732

页面不存在，你是不是打错了……？

**Comment by WForst-Breeze** [comment]
> 页面不存在，你是不是打错了……？

他直接把这条 Discussion 删了，不知道怎么回事……估计也不是PCL2的问题，蒜了吧
