### ISSUE TITLE
模组搜索无法准确筛选 Forge/Fabric/Quilt

### ISSUE THREAD

**Issue by HuajiCao** [Hex-Dragon/PCL2#733]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如题，在下载模组的时候，在设置模组选项为“1.16.5 Forge”的情况下搜索模组“DashLoader”后，会显示出DashLoader的模组下载选项。但是DashLoader的模组加载器为Fabric/Quilt，没有1.16.5中对Forge的支持。
<img width="570" alt="image" src="https://user-images.githubusercontent.com/90461220/209768402-7d781d28-00c2-40d5-960e-8eac4d4d8493.png">
<img width="570" alt="image" src="https://user-images.githubusercontent.com/90461220/209768360-7af7e9be-17c3-48f2-aa16-7ff3fcd4c146.png">

### 重现步骤

1、打开下载分页，在mod选项中搜索“DashLoader”
2、设置搜索条件：版本1.16.5，模组加载器Forge
3、之后会出现并不支持Forge的模组DashLoader

### 日志与附件

（因为Github访问问题，无法上传日志文件至Github，已上传至蓝奏云，链接如下）
https://caocheng241.lanzoue.com/b02k05kxg
密码:pcl2

**Comment by WorldHim** [comment]
呃，帮你传个日志
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10313827/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10313822/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10313824/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10313825/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10313826/Log5.txt)

**Comment by LTCatt** [comment]
这看起来是 CurseForge API 的 Bug，我没法修复……
