### ISSUE TITLE
无法选择Mod下载目录

### ISSUE THREAD

**Issue by JerryHan3** [Hex-Dragon/PCL2#734]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

下载Mod时会把Mod下载到上一次下载Mod时保存的文件夹，而不会根据现在选择的版本自动选择Mod文件夹。

### 重现步骤

进入Mod下载页面，任意下载一个Mod，弹出的就是上次下载Mod的文件夹

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10313905/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10313906/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10313907/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10313908/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10313904/Log5.txt)

**Comment by LBZiXL** [comment]
只要关闭PCL2重开就不会弹出上次下载的文件夹了

**Comment by xxtg666** [comment]
就是这么设计的

**Comment by JerryHan3** [comment]
不知道能不能设计一个选项，我就能选择是使用上一次下载的目录还是使用当前版本使用的mod目录了

而且之前的PCL2好像是根据现在选择的版本自动选择Mod文件夹……

**Comment by JerryHan3** [comment]
<img width="464" alt="image" src="https://user-images.githubusercontent.com/63506570/209890734-572de293-c64b-47be-a988-b7d7eb78a718.png">
我感觉可以把选项做在这个“目标文件夹”设置选项
