### ISSUE TITLE
安装整合包时下载OptiFine主文件失败，原因为错误的使用了BMCLAPI/MCBBS地址

### ISSUE THREAD

**Issue by cookie797** [Hex-Dragon/PCL2#735]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

安装整合包时报错：
```
游戏安装失败
Caused By: 下载 OptiFine 1.18.2 1.18.2H7失败
Caused By: 下载 OptiFine 主文件失败
Caused By: 文件下载失败：C:\Users\DELL\AppData\Local\Temp\PCL\Cache\Code\1.18.2-OptiFine_1.18.2_HD_U_H7_1260（第一下载源：https://download.mcbbs.net/optifine/1.18.2/HD_U/1.18.2H7）
Caused By: 远程服务器返回错误: (404) 未找到。
   在 PCL.ModNet.NetFile.Thread(NetThread Info)
错误类型：System.Net.WebException
```
经检查，optfine主文件下载地址错误，
应为[https://download.mcbbs.net/optifine/1.18.2/HD_U/H7](https://download.mcbbs.net/optifine/1.18.2/HD_U/H7)
实际为[https://download.mcbbs.net/optifine/1.18.2/HD_U/1.18.2H7](https://download.mcbbs.net/optifine/1.18.2/HD_U/1.18.2H7) 末尾多了“1.18.2”

使用其他启动器均未发生该错误。
附件中有引发此错误的整合包。

### 重现步骤

1.将整合包zip文件拖入PCL主页，按正常步骤安装。

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10314595/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10314596/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10314597/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10314598/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10314599/Log5.txt)
[把这个文件拖进PCL里.zip](https://github.com/Hex-Dragon/PCL2/files/10314600/PCL.zip)

**Comment by ZS2147483647** [comment]
请不要使用optifine，元素周期表比他好用一万倍，你就算装了游戏也有可能崩，这optifine已经烂到家了，不是龙猫能够拯救得了的
