### ISSUE TITLE
PCL2分析自己的日志出现错误的分析结果

### ISSUE THREAD

**Issue by G-mare** [Hex-Dragon/PCL2#736]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

PCL2分析自己的日志会出现如图所示的错误分析结果
![image](https://user-images.githubusercontent.com/64208603/209830245-fc719c1e-b745-4021-bf23-8fd8cb721448.png)

### 重现步骤

1、打开PCL2
2、把`.\PCL\Log1.txt`文件拖入PCL2主程序窗口
3、出现描述中的弹窗

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10314788/Log1.txt)

**Comment by xxtg666** [comment]
分析功能是针对游戏日志的……不过可以让龙猫加个判断？

**Comment by G-mare** [comment]
> 所以游戏目录到底有没有特殊字符

没有，我没开游戏。就是打开PCL2后直接把PCL2的`Log1.txt`拖进PCL2就能触发

https://user-images.githubusercontent.com/64208603/209899769-0f5f6401-0d49-4274-a95b-3f295faf0c66.mp4

**Comment by G-mare** [comment]
> 分析功能是针对游戏日志的……不过可以让龙猫加个判断？（判断这玩意能不能分析）

用PCL2启动游戏后PCL2的日志里面也会出现游戏日志，所以我才这样尝试。

**Comment by LBZiXL** [comment]
为什么我的PCL2拖不进去？？？？

**Comment by G-mare** [comment]
> 为什么我的PCL2拖不进去？？？？

PCL2的日志分析似乎是有白名单，我目前发现能拖`.minecraft\logs`文件夹下的`debug.log`和`latest.log`，还有就是PCL2程序文件夹下面的`PCL\Log1.txt`，其他的文本拖进去会提示`PCL2 无法确定应当执行的文件拖拽操作……`

**Comment by LBZiXL** [comment]
> 

不是，我的PCL2拖进去就显示一个红色的斜杠！

**Comment by G-mare** [comment]
> > 
> 
> 不是，我的PCL2拖进去就显示一个红色的斜杠！

这个我就不清楚了，我这里拖进去会触发描述中的弹窗，不过用PCL2启动游戏后再拖进去分析结果就是对的

**Comment by ZS2147483647** [comment]
问题在我这里也存在,严格按照他视频的步骤可以复现

**Comment by ZS2147483647** [comment]
![image](https://user-images.githubusercontent.com/121028009/209951344-af14d9bf-7934-4448-a0b9-5097f5b84326.png)

**Comment by WorldHim** [comment]
但是好像只有`Log1.txt`可以拖进去
