### ISSUE TITLE
选择“游戏关闭后关闭 PCL”时，取消启动导致 PCL 被关闭

### ISSUE THREAD

**Issue by zhengyoushang** [Hex-Dragon/PCL2#742]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

没啥好说的，就是在选“游戏启动后隐藏，启动后立即关闭”（除“游戏启动后立即关闭”）来启动游戏时，按“取消”取消游戏启动，不过启动器似乎当成游戏自动退出而自动关闭了。

还有我安装程序时把pcl2放后台的情况：
![image](https://user-images.githubusercontent.com/121605686/209933397-f0bb949a-5b16-4b54-8053-c387e0427ee1.png)
再之后：
![image](https://user-images.githubusercontent.com/121605686/209933413-8fc25129-a03a-45e9-aa86-ee899d600076.png)
再之后：
![image](https://user-images.githubusercontent.com/121605686/209933439-f90953d3-5357-4346-bca3-af8c6c44a1bc.png)
再再之后。。。：
![image](https://user-images.githubusercontent.com/121605686/209933486-f7f15e00-56c2-4ed4-8ff2-b232d5d7964f.png)
。。。。。。
![image](https://user-images.githubusercontent.com/121605686/209933514-1a114f4d-b2c5-41c8-b0f2-3bf3f78dce1f.png)
你猜结果咋了？
![image](https://user-images.githubusercontent.com/121605686/209934127-60f30f79-56d3-4c96-909b-0d1a34d2a1fe.png)

### 重现步骤

1.设置“启动游戏后隐藏，退出游戏自动关闭”来启动游戏，启动游戏时到“等待游戏窗口出现”按”取消“，启动器会判断游戏正常退出而关闭。
2.没啥步骤，把pcl放后台就会报警，我在安装FlashPlayer。

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10318752/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10318757/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10318759/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10318761/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10318762/Log5.txt)

**Comment by rongjianuo** [comment]
嗯，这很360...

**Comment by xxtg666** [comment]
360误判操作来源吧 这和PCL2有关系？

**Comment by ZS2147483647** [comment]
首先,你需要火绒安全,找不到官网我可以向你提供,其次,请不要安装flashplayer,因为flashplayer本身就是高危漏洞集合体+流氓软件,本身就是不被Windowsdefender承认的,安装成功那才叫奇迹,如果你需要玩flash游戏,可以尝试搜索它的h5页面或者下载它的微端而不是安装flashplayer

**Comment by wxjzx682** [comment]
一眼顶真，鉴定为360脑残

**Comment by LTCatt** [comment]
360 那个是 360 误判来源了……

**Comment by zhengyoushang** [comment]
> 360 那个是 360 误判来源了……

我知道360误判了，我点信任了，那为啥又安装软件失败了

**Comment by zhengyoushang** [comment]
> 360误判操作来源吧 这和PCL2有关系？

现在想起来，好像就是360搞的。。。。。

**Comment by zhengyoushang** [comment]
> 360 那个是 360 误判来源了……

现在想起来，应该就是360搞的安装失败吧。。。。

**Comment by zhengyoushang** [comment]
> > 360 那个是 360 误判来源了……
> 
> 现在想起来，应该就是360搞的安装失败吧。。。。

FlashPlayer本来也有点那啥
