### ISSUE TITLE
背景音乐突然停止，显示“音乐目前为停止状态

### ISSUE THREAD

**Issue by Maxpower233** [Hex-Dragon/PCL2#743]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

https://user-images.githubusercontent.com/121483790/209939903-ae3b05c6-43d3-4489-beea-fc1b28b48b23.mp4

播放到一半突然停止，期间没有启动游戏，无论暂停还是右击都无法继续播放音乐，建议对音乐播放进行优化。

### 重现步骤

1、打开pcl，pcl会自动播放音乐。
2，最小化pcl，放了一会儿，就突然停下来，就像下面

https://user-images.githubusercontent.com/121483790/209940616-1e413eb0-551a-4c64-ae45-6567959d250f.mp4

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10318962/Log1.txt)

**Comment by ZS2147483647** [comment]
pcl是minecraft启动器,不是音乐播放器.如果想听音乐请用potplayer,另外,你的日志好像没上传上来

**Comment by LTCatt** [comment]
Log 下载不了，再传一个？

**Comment by Maxpower233** [comment]
PCL 2.4.5似乎没问题了（
