### ISSUE TITLE
打开PCL2时有概率不出现界面

### ISSUE THREAD

**Issue by MC-luoluo** [Hex-Dragon/PCL2#745]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

使用任何方式打开PCL2，会出现打开成功但主界面不跳出的情况，鼠标移到任务栏会发现界面正常加载，但点击不会出现

### 重现步骤

使用任何方式打开你的PCL2，然后就复现了（

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10319347/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10319348/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10319349/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10319350/Log5.txt)
[log.txt](https://github.com/Hex-Dragon/PCL2/files/10319351/log.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10319354/Log1.txt)

**Comment by ZS2147483647** [comment]
是你电脑卡了吧,我这好好的

**Comment by Big-Cake-jpg** [comment]
给到的日志里并未表现出任何异常。

**Comment by LBZiXL** [comment]
我之前也遇到过同样的情况，在把PCL2以管理员身份运行后解决，此后在没出现过这种情况（应该是PCL2不兼容一些windows版本导致的吧）

**Comment by iPodtouch6557** [comment]
我的pcl2确实也没有…
这大概率是你的问题

**Comment by LTCatt** [comment]
曾经收到过类似反馈，是打开电脑第一次启动会这样吗？
此外，用管理员权限启动能否解决？

**Comment by xxtg666** [comment]
好像我也遇到过……不过是极小概率，重开一次就好了

**Comment by MC-luoluo** [comment]
> 

不是第一次了，打开很多次，经常这样，使用管理员权限打开后依然会出现

**Comment by LTCatt** [comment]
我的意思是，是不是打开电脑第一次启动一定会这样？还是说是随机的？

**Comment by TheBejinning** [comment]
![image](https://user-images.githubusercontent.com/121673730/210244257-660eb549-d9bd-4eb6-95ad-a782713d6c9e.png)
wo'xian我想你可以这样,一劳永逸

**Comment by MC-luoluo** [comment]
是的，开电脑后第一次打开一直都是这样，并且很长时间不打开或者重启（比如会话过期之后重启启动器）也这样

**Comment by LTCatt** [comment]
加我 QQ 1043137532，验证写 “反馈：打开PCL2时有概率不出现界面”
等我好了之后远程解决……

**Comment by just-int123** [comment]
我也有这个问题 打开pcl2后再打开其他窗口 等pcl2加载好后pcl2的窗口就点不开了 第一次启动情况暂时不确定 如果在pcl2启动过程中不开别的窗口能正常启动 影响不是很大 但还是希望能修复

**Comment by PythonSmall-Q** [comment]
管理员模式打开似乎能解决这个问题。反正我在win7，win11测试没问题的（测试次数大于等于20次）。win10和win8目前没有遇到这样的问题也没有测试过。

**Comment by miner233** [comment]
我这里没有这个问题啊...

**Comment by LTCatt** [comment]
无法重现，如果任何其他人有这个问题，加我 QQ 1043137532，验证写 “反馈：打开PCL2时有概率不出现界面”。

**Comment by MC-luoluo** [comment]
![7Q)M5(Y18T_E87@ R@` H%U](https://user-images.githubusercontent.com/113677351/212604595-7ef4275f-7cd8-4416-b9dc-826648c5cb28.png)

**Comment by MC-luoluo** [comment]
Issue 238A-2B1B-EE17-4ADF

**Comment by MC-luoluo** [comment]
238A-2B1B-EE17-4ADF 求解活跃橙

**Comment by MC-luoluo** [comment]
238A-2B1B-EE17-4ADF 求解活跃橙

**Comment by LTCatt** [comment]
你的解锁码：HM++rXWpEaGQ52+q6of0RC8GkzdcUMK6
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
