### ISSUE TITLE
优化 54.32 档位赞助者的分享流程

### ISSUE THREAD

**Issue by wxjzx682** [Hex-Dragon/PCL2#746]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

目的：
希望给54.32档用户获得的“分享 23.33 档位给他人”这一功能进行优化

大意：
将23.33档的内容分享给他人的方法有点繁琐了，而且获取快照版、更新密钥、解锁码的方法需要赞助者本人（以下简称甲方）在线，而不能被分享的人（一下简称乙方）单独进行操作
这点其实不是很方便，尤其是当你分享给一个同学做生日礼物的时候，当乙方想要更新的时候，就必须先联系甲方，或者直接使用甲方的爱发电账户进行操作，很不方便。
之前在群里发送“.更新”的时候，乙方可以直接在群里发送，从而避免了联系甲方这一烦恼，而现在改为了在爱发电上发送，就会造成一些不必要的打扰

具体操作：
      或许龙猫可以专门建一个被分享的PCL2用户（即乙方）的群，专门给这些人来使用，并且使用“识别码”+“分享”这两个关键词来进行分享，同时将此功能改为一次性的，用完之后就回复“您已使用分享权限”
      如果乙方的电脑换了（重装系统），那么需要联系甲方，甲方输入“旧的识别码”+“重置分享”这两个关键词，将旧的识别码移除，再重新绑定为新的识别码，而QQ群的话则是自动踢出，之后输入新的激活码后再重新加入

### 原因

因为自己的切身经历感觉不方便，所以提出了这个功能
本来自己是被分享的，感觉是在麻烦就自己赞助了，我和朋友都赞助的是54.32档，不过我已经没朋友可以分享了（悲）

**Comment by LTCatt** [comment]
这个涉及到蛋疼的爱发电机制……没有赞助的人是无法私信我的……
此外，如果用 QQ 机器人发更新密钥，会因为密钥是一串长乱码，导致机器人被封
可能之后再看看咋改……

**Comment by lvjiajjjlzy** [comment]
> 这个涉及到蛋疼的爱发电机制......没有赞助的人是无法私信我的...... 此外，如果用 QQ 机器人发更新密钥，会因为密钥是一串长乱码，导致机器人被封 可能之后再看看咋改......

可以试试用php搭个网站？

**Comment by youzi-2333** [comment]
> 可以试试用php搭个网站？

由于 PCL（以前）受到网络攻击，现在不会考虑制作网站……

**Comment by SuoHouDaiShi** [comment]
提个建议：
首次启动PCL弹出就像这样的窗口:
![图片](https://github.com/Hex-Dragon/PCL2/assets/119282947/6e85a645-cd9b-4b1f-92ba-307a062e7b36)
如果点击了否，就隐藏窗口
如果点击了是，弹出像这样的窗口：
![图片](https://github.com/Hex-Dragon/PCL2/assets/119282947/ab3917b8-4074-4cfb-8db8-544a4d93b1e6)
当用户输入识别码之后，弹出像这样的窗口：
![图片](https://github.com/Hex-Dragon/PCL2/assets/119282947/789553e8-4b8a-443b-9587-d300707eae46)
然后在注册表中添加`PresentActiveToken`项目，随机生成16位字母数字混合无序Token，并使用此Token作为更新凭证（可能会很麻烦）

**Comment by LTCatt** [comment]
寻思了一下，现在确实没啥好办法解决……

- 没有赞助的人不能通过爱发电发送私信
- 通过 QQ 群发命令的话，机器人会被腾讯暴杀
- 如果发爱发电激活码，现在已经分享出去的名额已然无法追溯

**Comment by iPodtouch6557** [comment]
哎，这个积压了那么久的功能就这么废了
