### ISSUE TITLE
Mod拖入有时无法实现

### ISSUE THREAD

**Issue by DXJLSFB139** [Hex-Dragon/PCL2#749]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在Mod选项中有个"把MOD拖入PCL2窗口来安装"，但是我的win11无法拖入Mod,会出现一个禁止的符号，然后强制拖入无效

### 重现步骤

1、打开PCL2
2.选择版本设置 → Mod设置
3.将mod拖入PCL2窗口后发现

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10322773/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10322771/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10322774/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10322775/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10322776/Log1.txt)

**Comment by xxtg666** [comment]
发现什么？描述清楚

**Comment by DXJLSFB139** [comment]
不知道了，但是我是不行的

**Comment by DXJLSFB139** [comment]
我重新修改了下

**Comment by DXJLSFB139** [comment]
@xxtg666 我已经修改了，您在看看

**Comment by LTCatt** [comment]
我理解你的意思了，但这个不像是我能处理的，似乎是系统禁止了文件拖放……
