### ISSUE TITLE
Minecraft启动进程失败

### ISSUE THREAD

**Issue by Darth-Nebula** [Hex-Dragon/PCL2#753]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃不是 PCL2 的原因，请 **不要** 提交反馈。你可以在 QQ 群里或者论坛找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是游戏本身的问题，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

[13:23:58.910] 加载线程 启动进程 (303) 发生运行时错误：系统找不到指定的文件。
   在 System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   在 PCL.ModLaunch.McLaunchRun(LoaderTask`2 Loader)
   在 PCL.ModLoader.LoaderTask`2._Closure$__12-0._Lambda$__0()
错误类型：System.ComponentModel.Win32Exception
[13:23:58.910] [Loader] 加载器 启动进程 状态改变：Failed
[13:23:58.910] [Loader] 加载器 Minecraft 启动 状态改变：Failed
[13:23:58.939] [Download] 1.17.json：文件大小 346003 B（338 K）
[13:23:59.076] [Launch] 错误：启动进程失败
→ 系统找不到指定的文件。
   在 PCL.ModLaunch.McLaunchStart(LoaderTask`2 Loader)
   在 PCL.ModLaunch.McLaunchRun(LoaderTask`2 Loader)
   在 PCL.ModLoader.LoaderTask`2._Closure$__12-0._Lambda$__0()
错误类型：System.ComponentModel.Win32Exception
[13:23:59.076] Minecraft 启动失败：启动进程失败
→ 系统找不到指定的文件。
   在 PCL.ModLaunch.McLaunchStart(LoaderTask`2 Loader)
   在 System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   在 PCL.ModLaunch.McLaunchRun(LoaderTask`2 Loader)
   在 PCL.ModLoader.LoaderTask`2._Closure$__12-0._Lambda$__0()
错误类型：System.ComponentModel.Win32Exception

### 错误报告、日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10323205/Log1.txt)

**Comment by xxtg666** [comment]
描述一下你当时在做什么

**Comment by LTCatt** [comment]
是每次都是这样吗？还是只有这一次出现了？

**Comment by LTCatt** [comment]
umm 加一下 QQ 1043137532，原因写 “启动进程失败：系统找不到指定的文件”

**Comment by 149441** [comment]
![Uploading QQ截图20231215191858.png…]()

**Comment by burningtnt** [comment]
> Uploading QQ截图20231215191858.png…

请等待 Uploading XXX 字样消失后再发送
