### ISSUE TITLE
龙腾猫跃代码的意见

### ISSUE THREAD

**Issue by rongjianuo** [Hex-Dragon/PCL2#754]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

龙腾猫跃，你可以让我们一起写代码好吗，你的更新速度实在太慢，你用的是VScode，那也行啊，SSH可以啊，(如果不行，我可以告诉你怎么白嫖CLion)好多有用的想法你没时间搞，都忽略了...（懒得搞.jpg）强迫症提议就是个好例子...，12.34点位可以和你搞（24.33就没人了...）求求了，实在不行教你怎么白嫖CLion(开源)。

### 原因

作者更新少又慢，让我们帮帮他。

**Comment by rongjianuo** [comment]
求求了好吗

**Comment by xxtg666** [comment]
你知道吗：PCL2所有的代码都是龙猫一个人写的

**Comment by xxtg666** [comment]
你要是实在想，可以去discussions问……这和bug或者新功能完全不沾边

**Comment by rongjianuo** [comment]
好的

**Comment by rongjianuo** [comment]
真快啊
