### ISSUE TITLE
在自动安装增加修改版本图标的快捷入口

### ISSUE THREAD

**Issue by ProgramApe6020** [Hex-Dragon/PCL2#758]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

能不能在安装MC的界面增加一个能修改版本图标的小功能，比如点一下草方块的图标就能更改图标？（或者是做一个下拉菜单？）

### 原因

这项优化让我可以更方便地改图标。
如果没有这项优化，我每次都必须去版本设置该图标，让操作变得很麻烦。

**Comment by LTCatt** [comment]
适用面可能不大，暂时不考虑 orz
