### ISSUE TITLE
Minecraft 1.12.2 原版游戏乱码

### ISSUE THREAD

**Issue by WinExp** [Hex-Dragon/PCL2#763]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

使用 PCL2 启动 1.12.2 原版后，出现下面一种情况：
![image](https://user-images.githubusercontent.com/55543397/210132269-bf0e4d98-56ad-4384-82c1-e64e3265f76f.png)

在按下任意一个按键后，游戏界面变为如下情况：
![image](https://user-images.githubusercontent.com/55543397/210132299-34b47de8-e0b1-48b2-9348-2841070bb8a3.png)

在删除 assets 和 libraries 文件夹并重新安装 1.12.2 原版后，此问题并没有得到解决。

### 重现步骤

1.下载 1.12.2 原版。
2.启动 1.12.2 原版。
3.出现此问题。

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10327134/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10327135/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10327136/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10327137/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10327138/Log5.txt)
[Log.txt](https://github.com/Hex-Dragon/PCL2/files/10327139/Log.txt)
[latest.log](https://github.com/Hex-Dragon/PCL2/files/10327140/latest.log)

**Comment by WForst-Breeze** [comment]
感觉是游戏贴图寄了，补全文件、使用其他启动器启动是否出现此问题？我这里没办法复现…… 感觉大概率不是 PCL2 本身的问题……？

**Comment by WinExp** [comment]
我正准备去试试，但是我把 assets 文件夹删除后再次启动确实无法解决此问题

**Comment by WinExp** [comment]
新年快乐

**Comment by alazeprt** [comment]
在检查latest.log时我发现了有非常多的这个报错：
`
[17:49:56] [Client thread/ERROR]: ########## GL ERROR ##########
[17:49:56] [Client thread/ERROR]: @ Post render
[17:49:56] [Client thread/ERROR]: 1281: Invalid value
`
看起来貌似是你的显卡驱动出现了问题，可以尝试重新安装/更新你的显卡驱动

**Comment by WForst-Breeze** [comment]
与 PCL2 无关，请检查你的显卡驱动，尝试进行重新安装或更新操作，感谢您的反馈~
```
[17:49:56] [Client thread/ERROR]: ########## GL ERROR ##########
[17:49:56] [Client thread/ERROR]: @ Post render
[17:49:56] [Client thread/ERROR]: 1281: Invalid value
```

**Comment by bruthax** [comment]
更新NVIDIA显卡驱动至527.26即可
