### ISSUE TITLE
内置的自定义下载器希望能支持更多种类的下载链接

### ISSUE THREAD

**Issue by lovelysheepfield** [Hex-Dragon/PCL2#764]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

希望下载器能够支持更多种类的下载链接（例如ed2k或者bt）。

### 原因

PCL的下载速度我是非常看好的，但是里面的自带下载器就只能下载http链接，有时我需要下载的链接不能通过pcl下载。有时下载资源的时候用别的下载器真的是太慢了

**Comment by LBZiXL** [comment]
那PCL就真成下载工具了。。。

**Comment by WForst-Breeze** [comment]
已初步确认，感谢您的反馈，新年快乐~

**Comment by SorrowRain** [comment]
PCL2是启动器，而非下载工具
此功能不会制作

**Comment by lovelysheepfield** [comment]
那你们很厉害呦。既然”PCL2是启动器，而非下载工具”那你们为啥还要支持自定义下载？我就是想把这个下载功能优化一下怎么了？

**Comment by Big-Cake-jpg** [comment]
> 那你们很厉害呦。既然”PCL2是启动器，而非下载工具”那你们为啥还要支持自定义下载？我就是想把这个下载功能优化一下怎么了？

自定义下载只是一个额外的小功能，并不是 PCL2 的主业：Minecraft 启动器。请你不要是用这种语气与我们交流。

**Comment by WForst-Breeze** [comment]
> 那你们很厉害呦。既然”PCL2是启动器，而非下载工具”那你们为啥还要支持自定义下载？我就是想把这个下载功能优化一下怎么了？

请注意您的语气，您的每一个反馈我们都会认真对待。出于技术问题和必要程度考虑，每个玩家用户的需求 PCL2 不能全部采纳。感谢您的支持、理解和对 PCL2 发展的关切😉

**Comment by TheBejinning** [comment]
我觉得他说的没问题呀,要么不做,要么做好,啥都不精但啥都有这不就是国产app的操作吗,我们宁可花钱玩minecraft国际版不玩我的世界的原因是什么,希望开发组好好想想

**Comment by TheBejinning** [comment]
我发现你们开发组雀氏挺牛逼,敢对用户这么说话的我还是见的头一个,微软工程师都是怎么回答客户问题的,好好到微软社区学学去吧

**Comment by Big-Cake-jpg** [comment]
> 我发现你们开发组雀氏挺牛逼,敢对用户这么说话的我还是见的头一个,微软工程师都是怎么回答客户问题的,好好到微软社区学学去吧

**Comment by Big-Cake-jpg** [comment]
淦 点错了

**Comment by Big-Cake-jpg** [comment]
> 我发现你们开发组雀氏挺牛逼,敢对用户这么说话的我还是见的头一个,微软工程师都是怎么回答客户问题的,好好到微软社区学学去吧

我们凭什么要在一个不是主业的功能上花费大量精力呢？

什么叫我们态度不好？应该是你们的态度不好吧。

**Comment by IceCream-QAQ** [comment]
> 我发现你们开发组雀氏挺牛逼,敢对用户这么说话的我还是见的头一个,微软工程师都是怎么回答客户问题的,好好到微软社区学学去吧

你每个月给我发三万块钱我态度比微软工程师还好。
什么？你不发？
爱死哪死哪去。
我不是你爹，也不是你妈。
我是做开源的，我不是养儿子的。

**Comment by WForst-Breeze** [comment]
> 我发现你们开发组雀氏挺牛逼,敢对用户这么说话的我还是见的头一个,微软工程师都是怎么回答客户问题的,好好到微软社区学学去吧

单论这件反馈本身，请您冷静，我们不想将事情闹得很僵，让我们**友善地**好好缕一缕这件事情：
- PCL2 是 Minecraft Java 版启动器，其主要功能为下载 Minecraft Java Edition 的各种游戏核心并提供游戏启动服务。
- PCL2 拥有告诉多线程下载引擎，为了使用户可以更好地利用这个功能，PCL2 提供了自定义文件下载服务。然而请您注意，这本质上已经超出了 PCL2 的服务范畴。
- 综上所述，**经过考虑**，PCL2 目前不会支持此反馈提及的功能，上面的那位 Collaborator 已经说了，PCL2 不会在这个功能上花费精力（换句话说，这个内容的优先级比较低）。毕竟现在 PCL2 所需要完善的内容真的很多，您可以看看 Issues 列表 中标记为**处理中**和**暂缓处理** label 的 Issue 有多少个。

那么接下来我们回到您所提及的态度问题上来：
- 我们是义务维护 PCL2 社区的，也就是说，我们一分钱也拿不到。
- 再次强调，我们对待每一条反馈都保证是认真的，我们不会无缘无故地 close 掉一个反馈，每一个反馈都是有意义的。
- 我们可能来自于各行各业，可能是职业的工程师，也可能只是普通的学生，大部分 Collaborator 只要有时间就会来到这个仓库，来处理 issue 或是回答 discussion 。你可能说我打感情牌，但是事实就是这样，我们的初衷是解决问题，而非是哄着各位反馈者。但是不知道您观察过吗，除了一些重复反馈或是就是来捣乱的反馈，每一条反馈下，**几乎都有**各位 Collaborator 和开发者的身影，还是刚才提到的，我们都是在认真的处理每一条 issue 和 discussion 。
- 如果我们态度真的不好，那就不会在这里跟您说这么一大段话了，也不会在每一条重复反馈下标记出与哪条反馈重复了，我们完全可以直接 close，毕竟我们只要解决了问题，其实我们的使命就完成了，但是我们没有。
- 我们明白，您说的这些话初心都是好的，都是为了使 PCL2 变得更好，我们都能理解，正如我上文所说的，每一条反馈都是有意义的，但或许只需要改变一下方式，事情的处理办法就会简单很多，不是吗？

再次感谢您对 PCL2 发展的关切

**Comment by TheBejinning** [comment]
我明白了你们的心意,我对你们1的无私奉献致以崇高的敬意和谢意,确实我们作为用户也只是想让pcl2走得更远,但在交流的过程中,难免会有一些歧义,我们希望双方能够有平等开放包容互助共赢的交流,这也是我们双方竭尽全力都在追寻的,我们用户确实对于你们社区维护者了解不够多,因此产生了一些误会,毕竟是谁花了钱购买了产品反馈个意见但连真正开发者的面都没见到就被否决了难免会有一些情绪变化,感谢您对我们的宽容和谅解,经过您的解释我也发现了我们用户的言语有时也有些问题,再此向您们开发组致歉,但是,不得不说并不是所有collector都向您一样愿意与我们用户友善交流,在这里我就不点名了[从上面的对话和其他反馈可以看出来您比其他collector素质高不少@最逆风].我只希望我们用户,开发组,作者三方能够积极协作,更高效地解决现实问题.在这里我也想对恶语相向的collector们说:没有人逼着你去做这件事,如果你们觉得这件事对你们来说是负担,或者影响你们的情感和生活,那你们可以不做,但只要做了就请你们注意素质,像'爱死哪死哪'这样的话着实不是一个文明人更不是一个社区管理者应该说的话,我们用户至始至终也没有骂过一句脏话,但到了你们这却出口成脏,我不理解你们做这件事的意义是什么,还是那句话,不想做可以不做,要做就要做好,这才配得上pcl2这款最强大的minecraft启动器,这才配得上minecraft玩家对游戏和启动器的热爱和信仰!

**Comment by TheBejinning** [comment]
感谢您们的辛勤付出,新年快乐!2023,我们一起携手并进,共创新高

**Comment by TheBejinning** [comment]
我们每一个用户都真诚希望自己能够为自己的热爱和信仰做一份贡献,但受到技术水平限制我们可能提出的建议并不是每一条都可行,诚恳希望开发组能够谅解,但也请collector们注意言行,不要寒了玩家们的心

**Comment by WForst-Breeze** [comment]
> 我们每一个用户都真诚希望自己能够为自己的热爱和信仰做一份贡献,但受到技术水平限制我们可能提出的建议并不是每一条都可行,诚恳希望开发组能够谅解,但也请collector们注意言行,不要寒了玩家们的心

感谢您的理解，我会向开发者检举并将那条不友善的社区评论折叠的，我相信各位 Collaborator 在这次问题发生后会注意自己的言行的，感谢您对 PCL2 社区的贡献，新年快乐！

**Comment by TheBejinning** [comment]
感谢!我也差不多明白了您们的运作机制也,希望您们能够多向用户充分介绍您们在背后的默默付出,多谢了解,也就多谢了理解.我以后肯定也会注意言行,主动和您们友善交流.最后,collector的问题确实很大,不止这一个帖子有不友善言论,尽管有时用户的言语也并不好,但我个人认为这并不是collector可以随便骂人甚至转发到其他平台骂人的理由,希望您如果有时间多多关照.给您的生活带来不便,抱歉!]

**Comment by TheBejinning** [comment]
您现在可以说是collector们的榜样,甚至是整个社区的榜样我们用户也相信collector们以及社区会在您的带领下素质变得越来越高,我也相信大家都会向您学习,我们共同的minecraft和pcl2一定能够拥有光明的前景!让我们一起共创美好未来!再见🥰🥰🥰

**Comment by SorrowRain** [comment]
> 那你们很厉害呦。既然”PCL2是启动器，而非下载工具”那你们为啥还要支持自定义下载？我就是想把这个下载功能优化一下怎么了？

PCL2的”下载自定义文件“功能是PCL2多线程下载引擎的附属功能。使用http/https协议下载文件是启动器的基础能力之一，我们也希望下载引擎不仅仅被用于mc下载中，所以开放了自定义下载并将其放在了与mc联系不大的”百宝箱“页面中。


由于PCL2下载体验较好，希望可以支持其他协议确实可以理解。但从开发角度来看，各个协议的原理不同，支持其他协议的工作量很大，可能需要消耗数周的开发时间，与百宝箱中其他的图一乐功能没法比较。这已经不是优化的范畴了，而是在PCL2中添加新的功能。


从PCL2的本职功能考虑，下载mc本体及相关文件使用的都是http/https协议，其他下载引擎没有任何用途。花费数周甚至更长的开发时间实现一个与软件本职工作不符的功能显然不够理智。


综上，PCL2暂时不会制作该功能，感谢理解。

**Comment by LTCatt** [comment]
嗯，我解释一下为什么 Collaborator 可以在我之前 Close 掉这个 Issue。
自定义下载此前就接到过相同反馈，我已经表示过不会进行扩展了（如果你在链接里输入 ftp:// 还能看到提示），所以可以按照重复反馈直接 Close。
这个功能不会进行优化的原因是它的收益相对较低，且超出启动器范畴。PCL2 是我 **个人** 开发的，所以我需要把 **非常有限的时间** 花在制作收益相对更高的功能上——例如 Mod 更新、多账号登录，所以我不可能把每一个小功能做到完美，这样的取舍是必须的……

**Comment by TheBejinning** [comment]
> 

感谢您的理解,不过我个人认为用户需要知道您们的运作机制,这样可以有效减少此类误会,也请collector们提高素质,打扰您了,抱歉
