### ISSUE TITLE
允许在下载失败时保留已下载文件

### ISSUE THREAD

**Issue by Emperormummy** [Hex-Dragon/PCL2#765]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [x] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

可否增加一个选项，下载失败时选择是否保留已下载的文件，我家网太差了，经常下载中断，断了就会自动删除所有已下载的文件，还要重新再下载，这就很令我头大了。但是HMCL可以保留已下载的文件，所以为了稳定只能用它了...要是PCL2也有这个功能就好了

### 原因

（示例）
这项优化让我可以更方便地xxxx。
如果没有这项优化，我每次都必须xxxx，让操作变得很麻烦。

**Comment by WForst-Breeze** [comment]
已初步确认，感谢您的反馈~

**Comment by LTCatt** [comment]
这里的问题在于，即使我保留了已下载的 **一部分** 文件，启动器也无法分辨是哪些东西没有完成下载，所以无法从上次失败的地方继续下载。这就导致保留这部分文件实际上没有意义。
