### ISSUE TITLE
让PCL的字体可以跟随windows字体改变

### ISSUE THREAD

**Issue by LBZiXL** [Hex-Dragon/PCL2#766]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

这是PCL2小论坛的一个提议，我只是帮忙照搬而已，具体见： https://afdian.net/p/0e24beec88d711eda08a52540025c377
1、PCL的字体跟随windows字体改变，具体是PCL2小论坛的一个人TA改了windows默认字体，但PCL2的字体没改，这让TA很烦恼。TA希望PCL2有这个功能。
2、在PCL2的个性化设置里增加“字体是否跟随系统字体”之类的设置。
3、也可以整一个单独换字体的功能。
![屏幕截图_20221231_215957](https://user-images.githubusercontent.com/115980764/210139254-5c58ca1b-25b7-4456-90b9-c5fb5e3be6f6.png)

### 原因

windows改了字体PCL2没有改，这让我很烦恼，希望有这个跟随系统字体更换功能，OK？

**Comment by WForst-Breeze** [comment]
已初步确认，感谢您的反馈~

**Comment by LBZiXL** [comment]
也可以整一个单独换字体的功能

**Comment by WForst-Breeze** [comment]
> 也可以整一个单独换字体的功能

此功能不会制作，请见 #366

**Comment by LBZiXL** [comment]
> > 也可以整一个单独换字体的功能
> 
> 此功能不会制作，请见 #366

知道了

**Comment by TheBejinning** [comment]
hmcl做了,但没完全做好,win11还有些问题
