### ISSUE TITLE
PCL II的今日人品出现了一个问题

### ISSUE THREAD

**Issue by BaiLanXiaoZhu** [Hex-Dragon/PCL2#767]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

当PCL II打开今日人品后 例如今日人品是23 但是 如果删掉了HKEY_CURRENT_USER\SOFTWARE\PCL里的注册表值 重新打开今日人品后会出现新的数字 我也是今天重装系统后发现的 再次恢复原来注册表的值 今日人品还会是23 但是重复删除注册表值操作 又会出现新的今日人品数字 希望龙猫能够解决这个问题 防止有人刷启动器皮肤

### 重现步骤

https://user-images.githubusercontent.com/110877112/210162016-df660ee7-c73c-465a-8189-d3c8c7697abb.mp4

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10328330/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10328331/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10328332/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10328333/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10328334/Log1.txt)

**Comment by TheBejinning** [comment]
别忘了你已经确定它没有bug才使用的,而且你这么发出来反而会导致刷皮肤泛滥

**Comment by LBZiXL** [comment]
> 别忘了你已经确定它没有bug才使用的,而且你这么发出来反而会导致刷皮肤泛滥

对，我本来不知道，现在就学到了（笑

**Comment by xiaoyi4335yyds** [comment]
啊这，其实直接改日期也可以

**Comment by LBZiXL** [comment]
我现在就研究一下，具体删掉那个值可以重置今日人品

**Comment by LTCatt** [comment]
通过非破解的手段获取启动器主题是被刻意允许的

**Comment by xxtg666** [comment]
你把记录的识别码给删了……
那当然会重新生成一个，并且计算新的
