### ISSUE TITLE
恢复注册表的时候和已经拥有的数据进行合并

### ISSUE THREAD

**Issue by BaiLanXiaoZhu** [Hex-Dragon/PCL2#768]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

例如原先启动器有欧皇彩 但是要恢复的注册表内没有 当恢复注册表时 原先启动器所拥有的欧皇彩皮肤将会消失 真的很难受 希望开发者能改一下 注册表合并后把原先的启动器数据也能够保留

### 原因

重装系统后抽到了欧皇彩 但是 恢复注册表后就没了 有的时候损失很大

**Comment by TheBejinning** [comment]
恢复注册表数据是覆盖的,不知道你这个合并是怎么个合并法,难道字符串拼接吗

**Comment by LTCatt** [comment]
备份可能无法恢复主题。
