### ISSUE TITLE
检查更新获取密钥引导有错误

### ISSUE THREAD

**Issue by woqucao** [Hex-Dragon/PCL2#769]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在下载新版本时，偶尔要密钥才能更新，但是提示写的是到qq获取，但是现在qq没法获取更新密钥，对于加qq的顶多多了一步，但是如果加不进去的，就可能误以为获取不到

### 重现步骤

点版本更新

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10328499/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10328500/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10328503/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10328502/Log4.txt)

**Comment by LTCatt** [comment]
最新版已经修改，你要更新之后才能看到……
