### ISSUE TITLE
切换启动器后原本的登录选择被重置为Mojang登录

### ISSUE THREAD

**Issue by Pixel-Cube** [Hex-Dragon/PCL2#773]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

同时用两个PCL2，一个是正式版作为服务器整合包启动器，使用的是第三方登录；另一个是测试版作为自己个人游戏启动器，使用的是微软账号登录。
问题：每次从第三方登录的整合包中的正式版启动器切换回个人游戏的测试版启动器后，测试版启动器的登录选项就变为了使用Mojang登录。
希望不同的启动器记忆的登录方式能分隔开，不相冲突。
[Log1（正式版启动器）.txt](https://github.com/Hex-Dragon/PCL2/files/10329958/Log1.txt)
[Log1（测试版启动器）.txt](https://github.com/Hex-Dragon/PCL2/files/10329957/Log1.txt)

### 原因

每次切换成测试版启动器的时候我都要重新选择微软登录，十分麻烦。

**Comment by Big-Cake-jpg** [comment]
🤔这个应该属于 Bug 吧

**Comment by LTCatt** [comment]
这样独立开是为了方便不同整合包的作者指定不同登录方式。WAI。
整合包之外的正常使用下也不需要放多个 PCL……

**Comment by Pixel-Cube** [comment]
> 这样独立开是为了方便不同整合包的作者指定不同登录方式。WAI。 整合包之外的正常使用下也不需要放多个 PCL……

我感觉...是不是我没表述清楚awa
我使用的是老式的那种打包式的（非导入式的）整合包类型，内置的pcl2如果用的第三方登录，回到我自用的启动器登录方式就会被重置成Mojang登录。
所以我正希望的是能独立开而不是现在这样混在一起会冲突......

**Comment by LTCatt** [comment]
我寻思了一下。
在完成 #42 和 #57 后，它应该会一并解决……所以不需要特别修复。
你的情况其实应该考虑在版本设置中指定登录方式？

**Comment by Pixel-Cube** [comment]
> 我寻思了一下。 在完成 #42 和 #57 后，它应该会一并解决……所以不需要特别修复。 你的情况其实应该考虑在版本设置中指定登录方式？

龙猫有道理，不过实际上我试过指定登陆方式了...并不能解决被重置的问题（因为指定正版登陆也包含mojang和微软两个登陆方式）。当然Mojang登陆移除后这个问题确实也就不存在了。_(:з」∠)_
