### ISSUE TITLE
又出现了带名称后缀的 Mod 在使用中文搜索时转换的关键字有误的问题

### ISSUE THREAD

**Issue by LBZiXL** [Hex-Dragon/PCL2#780]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在最新快照2.4.4版本中又出现了 https://github.com/Hex-Dragon/PCL2/issues/380 的问题，这次是搜索“旅行地图（Journey Map）”的问题，同样，在搜索栏里搜索“旅行地图”搜不到（图一），用英文“Journey Map”就能搜到（图二）！
图一：
![屏幕截图_20230103_151802](https://user-images.githubusercontent.com/115980764/210314207-b19faded-f516-455f-ad07-d683c5205bd2.png)
图二：
![屏幕截图_20230103_151855](https://user-images.githubusercontent.com/115980764/210314267-85845fc2-5925-4d80-a520-6ab957fd355f.png)

### 重现步骤

1、点击下载
2、搜索旅行地图，搜不到！
3、搜索Journey Map，就能搜到

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10334814/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10334815/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10334816/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10334817/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10334818/Log5.txt)

**Comment by LBZiXL** [comment]
@LTCatt 我的识别码：768E-5679-20A2-5D39

**Comment by LBZiXL** [comment]
@LTCatt

**Comment by LTCatt** [comment]
你的解锁码：TAGpRnI2FN3etBi0kmer0SOju/cVJHcv
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
