### ISSUE TITLE
bangbang93在爱发电上换了头像，但特别鸣谢列表中没有更改

### ISSUE THREAD

**Issue by ComputerCPT** [Hex-Dragon/PCL2#781]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如标题

### 重现步骤

无

### 日志与附件

无必要

**Comment by LTCatt** [comment]
我用的是 QQ 头像（
