### ISSUE TITLE
加大自定义标题栏文字的字体

### ISSUE THREAD

**Issue by ComputerCPT** [Hex-Dragon/PCL2#782]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

加大自定义标题栏文字的字体，使其与默认标题字体一致

### 原因

自定义标题栏文字的字体与默认PCL II标题字体不符

**Comment by LTCatt** [comment]
PCL2 默认标题不是字体，而是矢量图……所以不可能一致的……
