### ISSUE TITLE
自定义主页[灯塔的新闻主页]和pcl2调试模式不够兼容

### ISSUE THREAD

**Issue by TheBejinning** [Hex-Dragon/PCL2#783]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在打开时先会一闪而过启动日志,然后突然显示大段新闻主页内容,令人不适
启动游戏时不能自动跳转到启动日志,不利于处理游戏报错等问题
pcl2启动日志自带的背景框和'到底啦'下面'pcl2提示'的背景框宽度不一致,当启动游戏时由于日志过长就出现背景框宽带不一致问题,尤其是自定义背景影响严重
也就是说,我希望1.pcl2的启动日志和自定义主页先显示哪个能够确定
                          2.在自定义主页的情况下,对于游戏启动日志能够有处理,便于快速跳转[比如我换了游戏自定义标题,但到了游戏就没改,有日志我就能快速看出是我游戏专门设置的问题,没有日志我就觉得这又是bug又要提交]
                          3.把两个背景框想办法统一一下

### 重现步骤

1、设置自定义主页,打开调试模式
2、观察
3.启动游戏
4.观察

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10335641/Log1.txt)

**Comment by WForst-Breeze** [comment]
有时候自定义主页的确会与 PCL2 的部分提示产生排版上的冲突，，我个人感觉感觉不算是 bug 吧，先换成优化label了，感觉被处理的几率不大，等等看龙猫怎么想吧，感谢您的反馈

**Comment by LTCatt** [comment]
@Light-Beacon 有空看看……？

**Comment by LTCatt** [comment]
你去 https://github.com/Light-Beacon/PCL2-NewsHomepage/issues 交反馈吧……

**Comment by Light-Beacon** [comment]
草 我之前只优化了赞助提示 ~~怎么还有这玩意~~

**Comment by Light-Beacon** [comment]
修了 再有问题去我那交issue吧
