### ISSUE TITLE
PCL2赞助所得内容无故丢失

### ISSUE THREAD

**Issue by Francis0725** [Hex-Dragon/PCL2#787]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在没有更换电脑配件或整台电脑的情况下，PCL2的赞助内容丢失，主页快照版提示复现、各种主题也一同丢失。

尝试重新导入隐藏主题备份后生成的注册表，问题未能解决。

### 重现步骤

未知，真的未知，突如其来的问题把本人整懵逼了

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10340811/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10340812/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10340813/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10340814/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10340815/Log5.txt)

**Comment by LBZiXL** [comment]
难道是杀毒软件干的？

**Comment by Francis0725** [comment]
> 

已检查过火绒隔离区，甚至没有任何文件

**Comment by WForst-Breeze** [comment]
这个反馈好像有人曾经在金数据反馈过，但最终因为无法找到稳定复现方式而放弃处理，已初步确认，感谢您的反馈

**Comment by LTCatt** [comment]
这是因为识别码改变了，代表着你的硬件标识被其他软件更改，我没法确定是什么原因……
把新的识别码发到爱发电就行。
