### ISSUE TITLE
在全局设置中添加登录方式选项

### ISSUE THREAD

**Issue by quannen** [Hex-Dragon/PCL2#790]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

现在只能在每一个游戏版本的设置中改变登录使用的方式，希望可以在全局设置中也加上这项功能

### 原因

我会随着每个mc版本的更新而下载新版本（还有各种整合包），如果全局设置里没有的话每次下载新版本后都必须手动进行调整，比较麻烦。

**Comment by quannen** [comment]
不是
我是微软登录，因为强迫症，所以每次新版本要去把离线登录隐藏掉，希望可以直接在设置里加一个这样的

**Comment by LTCatt** [comment]
需求面太小了，暂时不考虑，抱歉（
