### ISSUE TITLE
Java自动查找重复

### ISSUE THREAD

**Issue by quannen** [Hex-Dragon/PCL2#794]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

明明是一个Open JDK,自动搜索后显示为两个

### 重现步骤

1、安装Eclipse Adoptium JDK，并且改变安装盘符（小写字母）
2、打开PCL,使用自动搜索Java
3、可以看到有两个在一个目录下的Java

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10342102/Log1.txt)

**Comment by quannen** [comment]
识别码C697-91CC-4789-5AFE，活跃橙......

**Comment by quannen** [comment]
解锁码.....

**Comment by LTCatt** [comment]
你的解锁码：SrjLrdNqq/Q1wQrSuGiQu32ieTAOSKxQ
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
