### ISSUE TITLE
PCL自动选择Java(小)版本

### ISSUE THREAD

**Issue by FUTURE16524** [Hex-Dragon/PCL2#795]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

![image](https://user-images.githubusercontent.com/95997396/210502524-e4f91a58-ee72-45ae-85e9-5de34bdc121b.png)
![image](https://user-images.githubusercontent.com/95997396/210502654-df9d73d9-5c46-4e61-b06c-a0ed85465386.png)
手动选择8.0.202可以正常启动游戏，希望存在合适的java版本时可以自动选择

### 原因

这项优化让我可以更方便地启动游戏。
如果没有这项优化，我每次都必须手动选择Java版本，让操作变得很麻烦。

**Comment by quannen** [comment]
你直接把不能用的java卸载了不就行了？
留着不占磁盘空间？

**Comment by FUTURE16524** [comment]
但是别的整合包需要更高版本的java8😅

**Comment by TheBejinning** [comment]
或许可以用hmcl把forge更新到可以兼容高版本java的版本,然后删除低版本Java

**Comment by LTCatt** [comment]
这个 Forge 版本的使用率已经很低了（可预见地，使用率还会继续下降），并且能用到这个修复的情况很少。
就算不说这个，这也是 Forge 的 Bug……
就……没啥必要修……

**Comment by LTCatt** [comment]
算了，姑且还是修了这个检测……

**Comment by LTCatt** [comment]
额，不对，与 #676 是同一个 Bug……

**Comment by FUTURE16524** [comment]
谢谢龙猫~

**Comment by Atclive** [comment]
> 你直接把不能用的java卸载了不就行了？ 留着不占磁盘空间？

PCL自动下载的怎么卸啊？
