### ISSUE TITLE
检查 Java 类别时出错：格式化 Json 对象失败

### ISSUE THREAD

**Issue by admin64github** [Hex-Dragon/PCL2#798]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

显示格式化json格式化失败，游戏无法启动！！！

### 重现步骤

1、启动mc1.18.2
2.Minecraft1.18.2使用java8]
3.点击启动
4.没了

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10343862/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10343864/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10343865/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10343866/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10343867/Log5.txt)

**Comment by TheBejinning** [comment]
1.18不是需要jdk17吗

**Comment by admin64github** [comment]
自动

**Comment by admin64github** [comment]
选择

**Comment by admin64github** [comment]
2A63-ACBF-E62C-5B83

**Comment by LTCatt** [comment]
你的解锁码：v/hdMxeJ+5gjFfPsVYbdZFll38CDRiBh
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
