### ISSUE TITLE
Forge 安装失败：java.lang.ClassNotFoundException: java.sql.Time

### ISSUE THREAD

**Issue by LTCatt** [Hex-Dragon/PCL2#799]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

由 @opopi5236 和 @ZXL-Q 在 #575 中提交。

```
选定的 Java：Java 16 (16.0.1)，64 位：E:\Program Files (x86)\jre\bin\
WARNING: Unknown module: cpw.mods.bootstraplauncher specified to --add-exports
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Caused by: java.lang.NoClassDefFoundError: java/sql/Time
	at com.google.gson.Gson.<init>(Gson.java:265)
Caused by: java.lang.ClassNotFoundException: java.sql.Time
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 14 more
加载线程 安装 Mod 加载器（方式 A） (1739) 发生运行时错误：安装新 Forge 版本失败
→ Forge 安装器出错，末行为 	... 14 more
加载器 下载 Forge 36.2.39 状态改变：Failed
```

### 重现步骤

疑似使用 Java 16 安装 Forge 36~40 触发，但我自己重现不出来……

### 日志与附件

[Log1 - 2023-01-05T024452.828.txt](https://github.com/Hex-Dragon/PCL2/files/10346727/Log1.-.2023-01-05T024452.828.txt)
[Log1 - 2023-01-05T024200.335.txt](https://github.com/Hex-Dragon/PCL2/files/10346728/Log1.-.2023-01-05T024200.335.txt)

**Comment by opopi5236** [comment]
唔，我的启动器在2.4.5版本之前自己莫名其妙的好了，有没有可能是win11的奇妙特性（

**Comment by LTCatt** [comment]
还有其他人遇到这个 Bug 吗？如果有的话直接加我 QQ 1043137532，原因写 “Forge 安装失败 https://github.com/Hex-Dragon/PCL2/issues/799”……

需要安装报错是如下内容：
```
安装新 Forge 版本失败
→ Forge 安装器出错，末行为 	... 14 more
```

如果提示末行为 false，是 #575 的 issue，目前已修复但未推送到正式版。

**Comment by LTCatt** [comment]
检查确认是高版本 JRE 导致。不应在任何情况下使用高版本 JRE……

MC		Forge	 Java		Result
1.19.3	44.1.7	 JRE 8.51	.
1.18.2	40.2.0	 JDK 20.0	.
1.18.2	40.2.0	 JRE 16.1	X
1.18.2	40.2.0	 JDK 16.1	.
1.18.2	40.2.0	 JRE 8.321	.
1.18.2	40.2.0	 JRE 8.51	.
1.18.2	40.2.0	 JRE 7.65	X
1.14.4	28.2.26	 JRE 8.51	.
1.14.4	28.0.1	 JRE 16.1	X
1.14.4	28.0.1	 JDK 20.0	.

**Comment by opopi5236** [comment]
好久了，活跃橙还能要嘛QWQ
识别码10FD-88AD-3446-865A

**Comment by LTCatt** [comment]
你的解锁码：/TfOB6/RVYRnlgCZ6cv0fIC2uON/sPdw
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by ZXL-Q** [comment]
草 我也来要把 识别码：9DE8-A4B9-3615-31DB


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Hex-Dragon/PCL2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月4日(星期二) 下午5:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Hex-Dragon/PCL2] Forge 安装失败：java.lang.ClassNotFoundException: java.sql.Time (Issue #799)





 
你的解锁码：/TfOB6/RVYRnlgCZ6cv0fIC2uON/sPdw
 在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by WForst-Breeze** [comment]
> 草 我也来要把 识别码：9DE8-A4B9-3615-31DB

很抱歉，提交重复反馈无法获得活跃橙 :(

**Comment by ZXL-Q** [comment]
issues 24E6-6A79-1C11-48D0

**Comment by burningtnt** [comment]
> > issues 24E6-6A79-1C11-48D0
> 
> 此反馈不是由你贡献的，你无法通过此反馈来获得解锁码...

虽说你确实为原 Issue 提供了一定的帮助，但…… 你不是直接发现者

**Comment by hejiehao** [comment]
> 检查确认是高版本 JRE 导致。不应在任何情况下使用高版本 JRE……
> 
> MC Forge Java Result 1.19.3 44.1.7 JRE 8.51 . 1.18.2 40.2.0 JDK 20.0 . 1.18.2 40.2.0 JRE 16.1 X 1.18.2 40.2.0 JDK 16.1 . 1.18.2 40.2.0 JRE 8.321 . 1.18.2 40.2.0 JRE 8.51 . 1.18.2 40.2.0 JRE 7.65 X 1.14.4 28.2.26 JRE 8.51 . 1.14.4 28.0.1 JRE 16.1 X 1.14.4 28.0.1 JDK 20.0 .

用的什么发行版测试？
