### ISSUE TITLE
无用的详见链接

### ISSUE THREAD

**Issue by ComputerCPT** [Hex-Dragon/PCL2#800]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

<img width="305" alt="image" src="https://user-images.githubusercontent.com/120709135/210675007-3be704e3-618c-4c50-b6bc-00e0ce9de9f7.png">
一般情况下，这个链接无法显示完全就没用了，并且爱发电里也有链接……

### 原因

链接无法显示完全，留着就没必要了，也有可能只是我电脑分辨率的问题……？

**Comment by TheBejinning** [comment]
你需要手动将pcl2窗口拉大才能看见
