### ISSUE TITLE
微软1.19.2进不去

### ISSUE THREAD

**Issue by EDChai494** [Hex-Dragon/PCL2#808]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃不是 PCL2 的原因，请 **不要** 提交反馈。你可以在 QQ 群里或者论坛找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是游戏本身的问题，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

说我的显卡问题，离线能进去，不加forge也能进，官方启动器也能进，应该是bug

### 错误报告、日志与附件

![QQ图片20230105135721](https://user-images.githubusercontent.com/122000976/210711891-11835591-4d56-4cde-ab90-0eb0fc337d05.png)

**Comment by quannen** [comment]
日志？错误报告？

**Comment by WForst-Breeze** [comment]
注：原 Discussion #807 
请提供错误报告及启动器日志

**Comment by EDChai494** [comment]
[hs_err_pid10952.log](https://github.com/Hex-Dragon/PCL2/files/10350909/hs_err_pid10952.log)

**Comment by LTCatt** [comment]
这个我不确定是什么原因，也不知道怎么办……
因为没有任何其他 Log，我也没法判断崩溃的具体原因是啥（
试试用 HMCL 启动？如果 HMCL 微软登录能启动，在这里继续回复，我再看怎么修……
