### ISSUE TITLE
不要识别mods内自创文件夹中的mod

### ISSUE THREAD

**Issue by Pixel-Cube** [Hex-Dragon/PCL2#811]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

如题，只要检测mods文件夹下的mod就行了，没必要检测子文件夹。

![image](https://user-images.githubusercontent.com/52479482/210743919-4c312cb7-88fe-4ec8-a3a4-6d2a72700da3.png)
_（我习惯在一个版本下测试多个mod（做多个整合包的时候用），习惯把一些会冲突的mod放进新建文件夹。）_

### 原因

？明明游戏都不会加载，为什么Mod管理要识别

**Comment by LTCatt** [comment]
但我记得似乎如果自创文件夹的名称是版本号啥的就会加载……？
有谁知道具体咋回事么？

**Comment by WForst-Breeze** [comment]
> 但我记得似乎如果自创文件夹的名称是版本号啥的就会加载……？ 有谁知道具体咋回事么？

好像是的，当 mods 文件夹中有文件夹名为该版本版本号，这里面的mod会被加载（Fabric 我没了解过这种情况，至少 Forge 是这样的🤔
![image](https://user-images.githubusercontent.com/110760354/210817127-ac94df87-bcbb-46d7-b601-e0ca7b1037c5.png)

**Comment by Pixel-Cube** [comment]
想起来这里好像可以解锁一个主题来着？

**Comment by Pixel-Cube** [comment]
想起来这里反馈成功好像可以解锁一个主题来着？
识别码：91F8-C27D-A55B-CEE6
谢谢啦~(*^▽^*)

**Comment by LTCatt** [comment]
你的解锁码：iuUjFf1t+8MJzNkqRqtIwcxBo4cAn14m
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
