### ISSUE TITLE
给自定义主题的透明度选项加上百分比显示

### ISSUE THREAD

**Issue by Xx114514xX1819** [Hex-Dragon/PCL2#815]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

给自定义主题中设置不透明度的滑动条加上百分比，其他四个选项选项都在拖拽的时候显示数值，就只有不透明度没有。

### 原因

这项优化让我可以更方便地分享给别人我的个性化主题。
如果没有这项优化，我每次都必须截图，让操作变得很麻烦。

**Comment by Pixel-Cube** [comment]
附议一下(ノ￣▽￣)

**Comment by WForst-Breeze** [comment]
已初步确认，感谢您的反馈~

**Comment by Xx114514xX1819** [comment]
识别码：A46F-9B85-CB50-A9FB

**Comment by WForst-Breeze** [comment]
> 识别码：A46F-9B85-CB50-A9FB

很抱歉，只有反馈 Bug 处理完成后才可以解锁隐藏主题，谢谢配合~
