### ISSUE TITLE
在MOD管理中增加修改文件名功能

### ISSUE THREAD

**Issue by RiverSDream** [Hex-Dragon/PCL2#819]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

在MOD的详情界面中增加“标记前置MOD”和“标记”按钮
前者可以直接选择一个前置MOD并将二者捆绑，在此之后，只要启动该MOD，就自动启动对应的前置MOD
后者可以在MOD管理页面为这个MOD添加一个标签，显示在MOD名称之前

### 原因

这个功能比较重要，因为我总是记不得哪些MOD是另一个MOD的前置模组，开启标记功能之后，可以提醒我;或者可以设置为标记之后，启用MOD本体后，自动启用其所有的前置模组。

**Comment by WForst-Breeze** [comment]
已初步确认，感谢您的反馈~
（注：此反馈不与 #179 重复，此反馈反馈者意为：用户手动标记已安装模组的前置模组，当两者均处于禁用状态时，当启用该模组时，同时启用被标记的前置模组）

**Comment by RiverSDream** [comment]
插句话，意思大概就是，扫描MOD名称来确定版本实在是太难了，这个工作就交给玩家自己，如果确实有这个需求（记不得前置模组），可以手动标记一下

**Comment by LTCatt** [comment]
这还不如直接修改 Mod 文件名……
要不然加一个修改文件名的选项得了 =。=

**Comment by LTCatt** [comment]
和 #102 一起做得了 =。=

**Comment by LTCatt** [comment]
重新考虑后必要性不大，暂时先不考虑了 Orz
