### ISSUE TITLE
分类版本列表失败：给定关键字不在字典中

### ISSUE THREAD

**Issue by yyk4728** [Hex-Dragon/PCL2#823]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在BUG被触发后，会让1.19.3安装失败，同时会在下一次刷新此目录时被触发，导致目录读取失败

https://user-images.githubusercontent.com/122078358/210944584-40ad0000-c83b-4a8d-9f05-935d0cb6b6e2.mp4

### 重现步骤

1、点击下载-1.19.3
2、将1.19.3改变安装名称并点击安装
3、安装完成后就会弹出分类失败窗口

### 日志与附件

[Uploading Log2.txt…]()

**Comment by quannen** [comment]
你的日志没有上传成功
（只是告诉你一下

**Comment by quannen** [comment]
没有复现，估计是你的问题

**Comment by yyk4728** [comment]
我不知道为什么上传失败，这里只显示"正在上传"......

**Comment by quannen** [comment]
多等一会

**Comment by yyk4728** [comment]
可能是我的问题，但我想知道这是什么引起的

**Comment by quannen** [comment]
重新上传log，上面那个已经上传不了了

**Comment by yyk4728** [comment]
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10359551/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10359552/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10359553/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10359554/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10359555/Log1.txt)

**Comment by yyk4728** [comment]
日志现在已经上传完成了

**Comment by miner233** [comment]
无法复现此 Bug。

**Comment by yyk4728** [comment]
目前bug造成原因不明，但现在bug所在目录一直不能被PCL2所读取

**Comment by quannen** [comment]
> 目前bug造成原因不明，但现在bug所在目录一直不能被PCL2所读取

那你换一个目录试试？说不定就好了........

**Comment by LTCatt** [comment]
把 `D:\我的世界hmcl主启动器\.minecraft\versions\` 整个打包发过来？

**Comment by youzi-2333** [comment]
（只是提醒一句）
请尽快补充信息，再过大约两三天就要超时关闭了……（悲）

**Comment by LTCatt** [comment]
超时关闭，如果看到了可以继续回复
