### ISSUE TITLE
快速隐藏联机界面

### ISSUE THREAD

**Issue by 080502** [Hex-Dragon/PCL2#824]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

![image](https://user-images.githubusercontent.com/34566121/210948708-064b5f50-7213-4802-83e4-8bb0f800c879.png)

### 原因

（示例）
这项优化可以使不看到烦人的提示（误点）。
如果没有这项优化，我必须手动点击隐藏，让操作变得很麻烦。

**Comment by quannen** [comment]
设置里面隐藏不彳亍吗？难道PCL以后再也没有联机了？
