### ISSUE TITLE
出现了连启动器都进不去直接报错的情况，要求我用管理员身份运行，而结果却是跟之前一模一样。

### ISSUE THREAD

**Issue by a2894454438** [Hex-Dragon/PCL2#825]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我连启动器都打不开，这么生成PCL文件夹，所以我不知道这么办。

### 重现步骤

1 我打开PCL启动器。
2 直接报错不给我启动，连打开都没有。
3 提示我要管理员权限运行。
4 按它要求打开也打不开。

### 日志与附件

![P@ 48UEXGO 2{B`4LL%)YIJ](https://user-images.githubusercontent.com/36083959/210966818-c3e4c9b5-4687-4d75-a40f-a716557c9ee1.png)

**Comment by LTCatt** [comment]
尝试给 PCL 换个文件夹（不要在桌面或 C 盘里）……
这个不管怎么说都是系统环境问题，我根本没办法修复的……
