### ISSUE TITLE
联机模块建议

### ISSUE THREAD

**Issue by EfleoX** [Hex-Dragon/PCL2#826]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

希望龙猫基于frp源码，制作大型穿透集群实现多人联机
中心服务器为房间创建者
主要更改token加密即可
感觉用户缺的是配置能力，与frps
所以没必要做得很复杂
#建议联机收费公摊云服/IDC

### 原因

我需要这个功能来联机。很多人都有联机的需求，但如果没有这个功能，就不能联机了。

**Comment by Big-Cake-jpg** [comment]
Frp 需要中心服务器作为依赖，且需要更多的金钱。

目前，Octo Network 章鱼网络将于本月底正式开放，基于 BakaXL Network 进行改善且支持跨启动器联机。启动器将会在联机时尝试直接打洞，如不成功，则 Octo 会自动分配可用且延迟较低的中继服务器转发流量。

你先别急。

**Comment by TT702** [comment]
只是去年11月的初步计划是在1月出第一版供调试，但实际上并没出来。
Octo Network 目前没有开放的准确时间表，还在开发中。
