### ISSUE TITLE
一个新的功能！使用 PCL2 启动器与 Minecraft 服务器交互！

### ISSUE THREAD

**Issue by YUANXINGlingyun** [Hex-Dragon/PCL2#829]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [x] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

一个与服务器交互的接口（要搭配服务器插件？）

例如
server type="get" info="hmplayer" ip="abc.de"
能获取到 abc.de服务器 的玩家数量
显示为 玩家数量：XXX人（动态更新每1分钟1次）

再例如
server type="send" info="npkey" ip="abc.de"
能给 abc.de服务器 发送新玩家key
显示为 [输入窗口 QQ号] [输入窗口 5位代码(进服时提供的)] [按钮 确认] （类似这样的）

### 原因

我需要这个功能来为服务器制作启动器菜单。
Q群内的机器人总是被冻结，导致新的玩家无法注册进入服务器。这很麻烦！
新的功能有助于改善这种局面！

有需要插件辅助的话 联系我吧 QQ1913532130

**Comment by Xx114514xX1819** [comment]
总感觉这是个广告(

**Comment by YUANXINGlingyun** [comment]
这不是啦
只是拿服务器举个栗子

**Comment by YUANXINGlingyun** [comment]
不然我改掉好了

**Comment by WForst-Breeze** [comment]
> 不然我改掉好了

最好改掉，容易被误会🤨

**Comment by WForst-Breeze** [comment]
已初步确认，感谢您的反馈~

**Comment by LTCatt** [comment]
最新版将添加 #59 的功能，你可以想想办法。
你的这个提案太超出启动器的范围了……
