### ISSUE TITLE
建议作者往新功能投票加一个加速器

### ISSUE THREAD

**Issue by rongjianuo** [Hex-Dragon/PCL2#831]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

[由于Github网络实在连不上，求作者加一个第三方开源加速器链接[https://gitee.com/docmirror/dev-sidecar/releases](url)或[https://gitee.com/link?target=https%3A%2F%2Fgithub.com%2Fdocmirror%2Fdev-sidecar%2Freleases](url)

### 原因

每次投建议时，Github实在进不去，求作者加上这个开源的加速器（这篇建议就是这么写的）

**Comment by LBZiXL** [comment]
按照龙猫的性格，我觉得TA不会做。。

**Comment by LBZiXL** [comment]
我更喜欢用 https://github.com/dotnetcore/FastGithub https://github.com/dotnetcore/FastGithub/releases

**Comment by WForst-Breeze** [comment]
hmmm... 这些东西只要动动手指查一查百度谷歌必应360就能找到答案吧……启动器不应该提供这些服务的按理说，感谢反馈
