### ISSUE TITLE
Forge 安装器出错，末行为 Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

### ISSUE THREAD

**Issue by sanqianxing3313** [Hex-Dragon/PCL2#832]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

这是pcl2的报告：下载 Forge 44.0.48失败
→ 安装 Mod 加载器（方式 A）失败
→ 安装新 Forge 版本失败
→ Forge 安装器出错，末行为 Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
   在 PCL.ModDownloadLib._Closure$__36-0._Lambda$__7(LoaderTask`2 Task)
   在 PCL.ModLoader.LoaderTask`2._Closure$__12-0._Lambda$__0()
   在 PCL.ModDownloadLib.ForgeInjector(String Target, LoaderTask`2 Task, String McFolder)
   在 PCL.ModDownloadLib._Closure$__36-0._Lambda$__7(LoaderTask`2 Task)

### 重现步骤

1.选择1..16.5等以上高版本，在下载时选择添加forge
2.等待下载
3.到下载模组加载器时（方式A），便会弹出无法下载组加载器（方式A）

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10365457/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10365458/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10365459/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10365460/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10365461/Log5.txt)

**Comment by Xx114514xX1819** [comment]
游戏版本1.19.3 Forge版本44.0.48，亲测无法复现

**Comment by sanqianxing3313** [comment]
but,我这边也试了HMCL，是可以下载的，但到了pcl2这里，就不行了

**Comment by LTCatt** [comment]
在 `设置 → 启动器 → 调试选项` 打开调试模式，然后再装一次直到失败，然后再发 Log 过来，这样 Log 会有更详细的信息（

**Comment by miner233** [comment]
![image](https://user-images.githubusercontent.com/110521837/211146927-b95fbf4e-1fec-41fe-967c-8b02df0c55be.png)
1.16.5 Forge 36.2.39 无法成功复现此 Bug。

**Comment by sanqianxing3313** [comment]
下载 Forge 44.0.48失败
→ 安装 Mod 加载器（方式 A）失败
→ 安装新 Forge 版本失败
→ Forge 安装器出错，末行为 Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
   在 PCL.ModDownloadLib._Closure$__36-0._Lambda$__7(LoaderTask`2 Task)
   在 PCL.ModLoader.LoaderTask`2._Closure$__12-0._Lambda$__0()
   在 PCL.ModDownloadLib.ForgeInjector(String Target, LoaderTask`2 Task, String McFolder)
   在 PCL.ModDownloadLib._Closure$__36-0._Lambda$__7(LoaderTask`2 Task)




以及log
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10366088/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10366089/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10366090/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10366091/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10366092/Log5.txt)

**Comment by sanqianxing3313** [comment]
我的pcl在前一段时间开始发生这种事情，刚下载pcl2时没有

**Comment by sanqianxing3313** [comment]
所以，会得到解决吗

**Comment by LTCatt** [comment]
已经修复了，下个版本就好了

**Comment by sanqianxing3313** [comment]
好的，感谢

**Comment by sanqianxing3313** [comment]
预计在什么时候会跟新呢

**Comment by sanqianxing3313** [comment]
lssue

**Comment by LTCatt** [comment]
2.4.5 已经更新了……

**Comment by sanqianxing3313** [comment]
E8F5-43BE-ECB5-18F6现在要求解锁主题还来得及吗🤔（

**Comment by LTCatt** [comment]
你的解锁码：YOjGIuSGj/hV92/NKz2RKFFrUi2KdlGw
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by sanqianxing3313** [comment]
谢谢龙猫



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2025年08月01日 17:08 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [Meloong-Git/PCL] Forge 安装器出错，末行为 Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 (Issue #832) |
LTCatt left a comment (Meloong-Git/PCL#832)

你的解锁码：YOjGIuSGj/hV92/NKz2RKFFrUi2KdlGw
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
