### ISSUE TITLE
建议把自定义下载功能移入下载页

### ISSUE THREAD

**Issue by hyplant** [Hex-Dragon/PCL2#834]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [x] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，但我仍然想要提交新功能提案。

### 描述

建议把**自定义下载**的功能从**百宝箱**中移动到**下载页**面左侧的栏目中，这样使用自定义下载功能更加方便。

### 原因

这个小小的改变可以让自定义下载使用起来更方便，同时也让新用户更容易了解到自定义下载功能。

**Comment by Xx114514xX1819** [comment]
建议把标签改成优化

**Comment by WForst-Breeze** [comment]
已初步确认，不过这个功能的定位更多的只是一个辅助性的小功能，按理讲不应该放入下载页面，感谢您的反馈~

**Comment by LTCatt** [comment]
同上 ↑
下载页提供的是 MC 的下载 =。=
