### ISSUE TITLE
Curseforge Mods 不全

### ISSUE THREAD

**Issue by WorldHim** [Hex-Dragon/PCL2#835]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

`Player API` 在 Curseforge 上能搜索到，但是在 PCL2 内搜索不到
[Player API - Curseforge](https://www.curseforge.com/minecraft/mc-mods/player-api)
也许是curseforge的问题？

### 重现步骤

1. 在`下载`-`Mod`中搜索`Player API`

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10365707/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10365708/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10365709/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10365710/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10365711/Log5.txt)

**Comment by Xx114514xX1819** [comment]
能搜到
![image](https://user-images.githubusercontent.com/114345474/211139615-8ce955b2-0af1-4ba4-93c7-2bacd970ed54.png)

**Comment by WForst-Breeze** [comment]
> 能搜到

这个搜到的和反馈者提及的不一样，估计又是CF的API的问题，等待开发者确认

**Comment by LTCatt** [comment]
![image](https://user-images.githubusercontent.com/40348278/211145228-fae647e0-50a3-4fbe-a005-256dd19f76bb.png)
![image](https://user-images.githubusercontent.com/40348278/211145231-655fcb7d-c778-4af7-92a0-217f353975ea.png)

……？

**Comment by WorldHim** [comment]
> ![image](https://user-images.githubusercontent.com/40348278/211145228-fae647e0-50a3-4fbe-a005-256dd19f76bb.png) ![image](https://user-images.githubusercontent.com/40348278/211145231-655fcb7d-c778-4af7-92a0-217f353975ea.png)
> 
> ……？

额……没发现（因为这个的版本显示有误

**Comment by WorldHim** [comment]
> ![image](https://user-images.githubusercontent.com/40348278/211145228-fae647e0-50a3-4fbe-a005-256dd19f76bb.png) ![image](https://user-images.githubusercontent.com/40348278/211145231-655fcb7d-c778-4af7-92a0-217f353975ea.png)
> 
> ……？

不对这个是其他作者对原mod的续作（图标上面有reboot），但是它指向的curseforge链接是原mod的

**Comment by LTCatt** [comment]
应该还是 CurseForge API 搜索的问题，我没办法 orz
