### ISSUE TITLE
在拖拽窗口边缘后新增“还原窗口大小”按钮

### ISSUE THREAD

**Issue by sleep80** [Hex-Dragon/PCL2#837]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [x] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

在拖拽窗口边缘后新增“还原窗口大小”按钮，可以是一个与主题色相同颜色的小圆圈在右下角，点一下就能恢复为默认的窗口大小

### 原因

有了这个功能就可以在拉大窗口后一键恢复窗口大小不需要自己慢慢拖动了。如果没有还需要自己往回拉很麻烦

**Comment by WForst-Breeze** [comment]
已初步确认，感谢您的反馈~

**Comment by LTCatt** [comment]
自己拉吧……就没有哪个其他软件做这个的…………
