### ISSUE TITLE
下载页面支持搜索

### ISSUE THREAD

**Issue by miner233** [Hex-Dragon/PCL2#838]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

下载页面（自动安装与手动安装）页面支持搜索某一个版本，包括 Minecraft、Forge、Fabric、Optifine、OptFabric 等。

### 原因

现在，Minecraft 的版本数量越来越多，光凭自己一个个找是很麻烦的。
有些时候想找某一个预览版，但是预览版目前已经有 531 个版本了...如果不能搜索，那得找很久...

**Comment by WForst-Breeze** [comment]
已初步确认，感谢您的反馈~

**Comment by LTCatt** [comment]
也就只是找老的预览版比较麻烦……99% 的时候都没太大用，算了 =。=
