### ISSUE TITLE
为标题栏增加 文本+图片 的选项

### ISSUE THREAD

**Issue by FangFuJi1991** [Hex-Dragon/PCL2#840]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

可以让 PCL2 的标题栏变成 文本+图片 的样子，如果可以，把文本和图片变成多选框，然后添加默认图标，可能我要求有点多，但如果可以的话谢谢了 :-D

### 原因

因为有些时候我想让pcl做到这种效果，但没有这种功能，能添加的话就谢谢了

**Comment by LTCatt** [comment]
你可以选择 `图片`，然后在图上写字……
