### ISSUE TITLE
自定义下载文件后缀名消失

### ISSUE THREAD

**Issue by Crushedfish4740** [Hex-Dragon/PCL2#841]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

使用百宝箱中的下载自定义文件功能时，若要下载的文件后缀名为.exe，则下载完成后文件的后缀名会消失。手动为文件添加后缀名后文件可以正常使用。（真是神奇）

### 重现步骤

1、点击更多
2、点击百宝箱
3、自定义下载一个后缀名为.exe的文件

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10366516/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10366517/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10366518/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10366519/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10366520/Log5.txt)

**Comment by LTCatt** [comment]
这是对方网页提供的文件没给全名导致的，考虑到不会影响 MC 的部分所以不会修复……
