### ISSUE TITLE
建议出个基岩版的，这样子我们就不用去下载网易版本的了，记住“基岩版”这个东西~

### ISSUE THREAD

**Issue by Hayden2018666** [Hex-Dragon/PCL2#845]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

可以运行基岩版，基岩也是个版本，基岩版也挺好玩的

### 原因

（示例）
我需要这个功能来xxxx。很多人都有xxxx的需求，但如果没有这个功能，就不能xxxx了。
想玩基岩版

**Comment by Big-Cake-jpg** [comment]
与 #81 重复，感谢反馈。

PCL2 不会加入对 Minecraft 衍生作品的支持。

**Comment by Hayden2018666** [comment]
要钱的





黄祖海
***@***.***







                       
原始邮件
                       
                     

发件人："quan_neng233"< ***@***.*** &gt;;

发件时间：2023/1/10 10:18

收件人："Hex-Dragon/PCL2"< ***@***.*** &gt;;

抄送人："Hayden2018666"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [Hex-Dragon/PCL2] 建议出个基岩版的，这样子我们就不用去下载网易版本的了，记住“基岩版”这个东西~ (Issue #845)




 
我记得基岩版是可以直接点开的吧（微软商店里有
