### ISSUE TITLE
允许修改 Minecraft 游戏窗口的图标

### ISSUE THREAD

**Issue by WForst-Breeze** [Hex-Dragon/PCL2#847]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

> 此功能曾在金数据被提及，此处仅做搬运和补充工作

如题，支持修改 Minecraft 游戏窗口左上角的小图标，类似于 [这个模组](https://www.curseforge.com/minecraft/mc-mods/window-title-changer) 。

或许可以设计三种设置：不做修改（默认）、与版本图标一致、自定义。

### 原因

部分玩家可能需要。
此功能可以拓宽用户自定义的范围，或许可以使得用户的游戏体验更加优雅（？
尽管此功能可以通过安装相应mod实现，但对于用户而言增添了不少麻烦。

（由于这个功能实在太过不起眼，因此我认为优先级其实相当低……）

**Comment by LTCatt** [comment]
不太好弄，这个 API 太头秃了……算了 =。=
