### ISSUE TITLE
为正版账号退出登录增加二次确认

### ISSUE THREAD

**Issue by BitterHazelnuts** [Hex-Dragon/PCL2#849]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

如题所述，用户退出正版账号登录时没有二次确认信息。当用户单击“退出登录”按钮时，PCL 2 会在未经过用户二次确认的情况下直接退出当前账号的登录。如果用户因误操作退出账号则需要重新提供登录信息，浪费了宝贵的游玩时间（）
为了避免这种情况，可考虑在用户单击“退出登录”按钮时弹出确认操作的对话框，为用户提供撤销操作的机会。

### 原因

此项优化有助于在误操作时为用户提供撤销操作的机会，避免了重复填写登录信息导致的时间浪费。
这不是一项紧要的功能改进，但有助于提升用户体验。

**Comment by LTCatt** [comment]
之后会重做账号系统的 =。=
合着一起做（
