### ISSUE TITLE
在开启版本隔离的前提下，允许一键打开光影/数据包/材质包文件夹

### ISSUE THREAD

**Issue by RiverSDream** [Hex-Dragon/PCL2#852]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

虽然我没有用过HMCL，但是据我所知，HMCL有一个窗口，可以直达Minecraft中任意的常用文件夹。
对于非版本隔离的MIinecraft，我再三检查之后确认所有的版本都共用同一个文件夹，因此不妨在首页设置一个直达按钮，让用户在随后弹出的下拉菜单中选择。
对于版本隔离的Minecraft，我也没有使用过，但是不妨在每个版本旁边都附上一个这样的按钮，这样子对不开启版本隔离的人也十分友好。

### 原因

我需要这个功能来【快速打开资源文件夹】。很多人都有【一键/更快捷地添加/编辑/删除一些光影/数据包/材质包】的需求，但如果没有这个功能，就【只能先打开mod文件夹，然后返回上一层的.minecarft文件夹，然后再找到datapack等文件夹】了。

注：与[#388](https://github.com/Hex-Dragon/PCL2/issues/388)和[#462](https://github.com/Hex-Dragon/PCL2/issues/462)不同，这里仅仅是希望可以打开文件夹，而不是进行内容管理

**Comment by RiverSDream** [comment]
可能是很傻瓜的一个功能……嗯……但是据我所知，我周围的人就是有人找不到这个文件夹，或者抱怨找不到，找起来麻烦

**Comment by Big-Cake-jpg** [comment]
与 #606 重复。
