### ISSUE TITLE
今日人品不应该是警告提示框

### ISSUE THREAD

**Issue by ZS2147483647** [Hex-Dragon/PCL2#854]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

太吓人了
![image](https://user-images.githubusercontent.com/121028009/211439362-5a450cee-b060-4514-bfed-195d02a7dc7b.png)

### 原因

吓死我了

**Comment by WForst-Breeze** [comment]
这应该是刻意的设计吧（）

**Comment by ZS2147483647** [comment]
我这人品这样还行,要是100人品也这样就不好了

**Comment by LBZiXL** [comment]
我觉得也挺吓人

**Comment by LTCatt** [comment]
刻意的设计。
