### ISSUE TITLE
mod搜索明显不当

### ISSUE THREAD

**Issue by ZS2147483647** [Hex-Dragon/PCL2#855]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

中文全称搜不到,然后删两个字就能搜到,why???

### 重现步骤

搜索mod砂轮增强
观察:没有
搜索mod砂轮
观察:发现砂轮增强

### 日志与附件

![9b1e34c2c051e6a9a65cf2729371be5](https://user-images.githubusercontent.com/121028009/211440631-814a3800-769c-4f5e-b004-4094935014fb.png)
![977d918c4064193f4ece26014d9cae8](https://user-images.githubusercontent.com/121028009/211440638-990b1518-ab55-4e55-a754-372c0345ea96.png)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10378149/Log1.txt)

**Comment by WForst-Breeze** [comment]
这明显是您输入“增强”后，Curseforge 更倾向于去搜索有关“More”的搜索结果，并把下载量高的排在了前面，当删去“增强”后，Curseforge 才去倾向于搜索有关砂轮的结果

**Comment by ZS2147483647** [comment]
这个逻辑居然是这样的!!!!?我以为是逐字对比,涨知识了
