### ISSUE TITLE
1.19.2窗口大小明显不对

### ISSUE THREAD

**Issue by ZS2147483647** [Hex-Dragon/PCL2#856]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

1.19.2设置1920*1080启动游戏大约只有1000*600,太小了[3200*2000的屏幕]

### 重现步骤

观察:窗口大小设置为:1920*1080
启动1.192
观察:太小了
使用微信截图确定大小:大约1000*600,明显不对

### 日志与附件

![feb5178f620c48a838ed18c39960746](https://user-images.githubusercontent.com/121028009/211443410-9dedebb5-7f04-4c73-a973-f49ccf29774f.png)
![060caaf0db263bb571bb502e2921313](https://user-images.githubusercontent.com/121028009/211443420-f34babb6-fc55-4f76-a52b-e580e82db4cf.png)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10378263/Log1.txt)

**Comment by ZS2147483647** [comment]
实测1.12.2已修,但1.19.2出了问题,我觉得应该添加个条件判断,在1.13以上的版本应该还原到修复之前的操作,1.12.2及以下的版本应用修复就行

**Comment by js-tst** [comment]
似乎哪个版本都不对，测了原版1.12.2,1.16.5,19w14a,forge1.18.2设置1920x1080实际启动都是1536x876

**Comment by ZS2147483647** [comment]
1.12.2确实可以,1.19.2不行

**Comment by Herobrine-bug** [comment]
我也发现了这个bug，启动1.19.2设置的1280*720大小，启动后只有1278*678 (从F3界面可获取窗口分辨率)

**Comment by liumingedwin** [comment]
其实可以直接MoveWindow解决...

**Comment by Herobrine-bug** [comment]
> o

所以我每次打开窗口都要手动调节到1280*720
