### ISSUE TITLE
在游戏内存选项里添加选择最小内存的选项

### ISSUE THREAD

**Issue by jocemod** [Hex-Dragon/PCL2#860]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在游戏内存选项里添加选择最小内存的选项

### 原因

这项优化让我可以更方便地修改-Xmn的数值。
如果没有这项优化，我每次都必须从.bat文件启动游戏，让操作变得很麻烦。

**Comment by WForst-Breeze** [comment]
已初步确认，感谢您的反馈~

**Comment by LTCatt** [comment]
-Xmn 没有必要手动修改吧？

**Comment by LBZiXL** [comment]
> > JVM 中最大最大小有三方面限制:
> > （后略）
> 
> 题外话：或许你可以直接提供相应的 [**知乎链接**](https://zhuanlan.zhihu.com/p/490965101) 就好……（）不然篇幅有点长可能影响观感

额，以后注意。。。

**Comment by LTCatt** [comment]
嗯……现在 xmn 是固定的 256M，有啥调优的经验数值么，我直接改了得了

**Comment by rumengchuxing062** [comment]
128-256够用了
太大貌似容易堆栈溢出
可以试试动态调整

**Comment by rumengchuxing062** [comment]
128-256够了

**Comment by LTCatt** [comment]
256 作为默认设置应该不会出现什么问题，先关了吧……
