### ISSUE TITLE
解压整合包文件错误：在某些文件和目录下未能完成操作

### ISSUE THREAD

**Issue by ZS2147483647** [Hex-Dragon/PCL2#861]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

有的时候行,有的时候不行,为什么??

### 重现步骤

在hmcl导出整合包
在pcl安装整合包
有的时候行,有的时候不行

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10378688/Log2.txt)

**Comment by ZS2147483647** [comment]
https://www.123pan.com/s/gxXSVv-P0oxA

**Comment by LBZiXL** [comment]
我也是，有时候会显示解压整合包文件失败

**Comment by quannen** [comment]
我记得HMCL改过版本json的，估计不是PCL原因

**Comment by LTCatt** [comment]
[11:30:31.619] 加载线程 解压整合包文件 (176) 发生运行时错误：在某些文件和目录下未能完成操作。有关详细信息，请参阅该异常的 Data 属性。
   在 Microsoft.VisualBasic.FileIO.FileSystem.FxCopyOrMoveDirectory(CopyOrMove operation, String sourceDirectoryPath, String targetDirectoryPath, Boolean overwrite)
   在 PCL.ModModpack._Closure$__10-0._Lambda$__0(LoaderTask`2 Task)
   在 PCL.ModLoader.LoaderTask`2._Closure$__12-0._Lambda$__0()
错误类型：System.IO.IOException
[11:30:31.619] [Loader] 加载器 解压整合包文件 状态改变：Failed


这是解压文件失败了，可能是压缩包不标准的原因？
试试先手动解压，再用常用的压缩软件重新压缩，看看还会不会出错？

**Comment by ZS2147483647** [comment]
不可以,仍然报错
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10387659/Log1.txt)

**Comment by ZS2147483647** [comment]
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10387784/Log1.txt)
7z标准压缩完成后问题仍旧`,无论是原始压缩包还是新压缩包都有成功的可能,但都不一定成功

**Comment by ZS2147483647** [comment]
新bug来了,显示安装失败但已在版本列表显示
![image](https://user-images.githubusercontent.com/121028009/211769765-8092c105-98f6-44d5-9b53-88ed57a72c19.png)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10390793/Log3.txt)

**Comment by ZS2147483647** [comment]
意思是,它提示安装失败,但在版本列表中有

**Comment by ZS2147483647** [comment]
https://www.123pan.com/s/gxXSVv-r0oxA

**Comment by ZS2147483647** [comment]
实在没辙了,使用hmcl安装成功

**Comment by XD90206** [comment]
下载1.19.3-Forge_44.0.48和1.19.2-Forge_43.2.0的时候报了同样的错误（哭
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10410466/Log2.txt)
