### ISSUE TITLE
在刚启动PCL2后点击顶部选项动画出现卡顿

### ISSUE THREAD

**Issue by qingsonggame666** [Hex-Dragon/PCL2#865]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在启动PCL2后点击顶部选项的时候动画会出现卡顿，任何一个选项都是这样（除了联机选项），只有点击其中一个顶部选项后被点击的选项动画才不会出现卡顿，目前只在更新最新快照版2.4.5后出现

### 重现步骤

1、点击顶部选项其中之一（除了联机选项）
2、然后卡顿就出现了

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10380711/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10380712/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10380713/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10380714/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10380715/Log5.txt)

**Comment by LTCatt** [comment]
电脑性能问题，第一次点开页面需要加载，这个真没办法

**Comment by 212112111zwl** [comment]
我启动后等了若干秒，动画仍然卡顿，有没有可能这不是加载的问题

**Comment by LTCatt** [comment]
它是在第一次点开那个选项的时候才开始加载，不是启动 PCL2 立即加载……
