### ISSUE TITLE
音乐切换歌曲与提示不符合

### ISSUE THREAD

**Issue by lynnguo666-personal** [Hex-Dragon/PCL2#866]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

PCL的音乐播放功能 提示条的播放音乐和实际播放音乐概率不符合

### 重现步骤

1、在Musics文件夹存4首歌曲
2、刷新后右键音乐按钮切换到下一首
3、重复第二步 概率出现错误

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10380859/Log1.txt)

**Comment by LTCatt** [comment]
播放音乐失败（猫耳酱 - 许愿星.mp3）：UnspecifiedError calling waveOutOpen
   在 NAudio.Wave.WaveOut.Init(IWaveProvider waveProvider)
   在 PCL.ModMusic.MusicLoop(String Address, Boolean IsFirstLoad)
错误类型：NAudio.MmException

怪，或许是 Hyper-Dragon/DgtAngel#68 的同样的问题……

**Comment by lynnguo666-personal** [comment]
这个可能是切歌切太快了？
在这之前也有测试过一次 没有报错 但是仍然是不符合的

**Comment by LTCatt** [comment]
这个应该是外部错误，考虑到触发率很小，还是算了……
