### ISSUE TITLE
微软正版无法登录（或许是微软的锅？）

### ISSUE THREAD

**Issue by Welsonpeaches** [Hex-Dragon/PCL2#869]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在登陆在PCL 2时，登录一个已经创建了Minecraft:Java Edition玩家档案，出现类似于没购买正版、没创建Minecraft:Java Edition档案的登录错误提示

### 重现步骤

1、点击**微软登录**
2、然后点击添加账号
3、添加一个**购买**了Minecraft:Java Edition的账号 **（已创建Minecraft:Java Edition玩家档案）**
4、登录完成后可能会出现这个Bug

### 日志与附件

这是别人发生的BUG
我自己也发生过
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10381387/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10381388/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10381389/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10381390/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10381391/Log5.txt)

**Comment by WForst-Breeze** [comment]
非 PCL2 自身原因，请前往 minecraft.net 登陆一遍再前往 PCL2 尝试登陆，感谢您的反馈~

**Comment by Welsonpeaches** [comment]
我说啦，有可能是微软的锅，我没怪PCL2啊
