### ISSUE TITLE
PCL2窗口不应该不可以放大到覆盖桌面

### ISSUE THREAD

**Issue by CNghost6** [Hex-Dragon/PCL2#876]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

试图将pcl2窗口拉到最大，发现拉到最大能拉的，左右还会留比较大的缝......
正式版2.4.4还是正常的，可以把窗口调到覆盖桌面那么大，满足强迫症
2.4.5就不行了
希望窗口大小的调整恢复到2.4.4的样子

![{N9IG F_J2HMLZX)0P HF7](https://user-images.githubusercontent.com/109255817/211564500-ccd0dbf0-98cd-4b15-9c98-71c9e9659335.png)
2.4.5的
![A3{3C9U4N9TE6855C REBGL](https://user-images.githubusercontent.com/109255817/211564869-b7d1d0ac-251f-433f-9238-89c469c0b6d1.png)
2.4.4正式版的

### 原因

是我个人的特殊习惯，希望能满足我的强迫症就行

**Comment by WForst-Breeze** [comment]
嘶……彳亍，已初步确认，感谢您的反馈~

**Comment by LTCatt** [comment]
不会修复……
2.4.5 扩大了白边的原因是 PCL2 只能渲染窗口内的内容，因此位移等动画如果超出了窗口范围就渲染不了，会导致一些奇怪的视觉异常。
