### ISSUE TITLE
弹窗动画

### ISSUE THREAD

**Issue by baolong520** [Hex-Dragon/PCL2#879]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

希望能自主选择新旧程序启动和关闭、弹出提示的弹窗动画

### 原因

新版动画不太习惯

**Comment by bwtx2023** [comment]
应该不会提供选项

**Comment by ZS2147483647** [comment]
也许你可以把动画速度拉到最大,这样就不会有动画了,非常的干净利落

**Comment by LTCatt** [comment]
我只能说，看多了就习惯了…………
