### ISSUE TITLE
界面显示有时出现问题

### ISSUE THREAD

**Issue by MJIFmc** [Hex-Dragon/PCL2#880]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在将动画速度调低时有时会出现显示错误

### 重现步骤

1,将调试选项中的动画速度拉低
2,在下载界面侧边栏点击多个栏目
3,有时会发现多个栏目名称同时亮起
4,有时还会导致一些栏目不显示
5,不确认在高动画速度下是否会出现此问题
详见截图

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10383932/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10383933/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10383934/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10383935/Log5.txt)
[Log.txt](https://github.com/Hex-Dragon/PCL2/files/10383936/Log.txt)
[Log.txt](https://github.com/Hex-Dragon/PCL2/files/10383939/Log.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10383940/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10383941/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10383943/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10383944/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10383945/Log5.txt)
![捕获](https://user-images.githubusercontent.com/110874026/211588803-2914bf01-787f-4949-8597-5204940e3227.PNG)
![捕获1](https://user-images.githubusercontent.com/110874026/211689239-2e90a61b-a792-4a8c-97b6-3a8030958b8e.PNG)

**Comment by ZS2147483647** [comment]
不知道你是咋做的,我调到0.1x仍然很丝滑,并没有出现任何bug

**Comment by MJIFmc** [comment]
> 

在低速动画下快速点击各个栏目

**Comment by MJIFmc** [comment]
OHHHHHHHHHHHHH完成了所以我活跃橙呢

**Comment by MJIFmc** [comment]
识别码:848A-E9FE-6593-F11A

**Comment by LTCatt** [comment]
你的解锁码：qbSXPtAcHYPx7jyklmjO30dbBLj7Vmxp
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
