### ISSUE TITLE
优化回声洞投稿方式

### ISSUE THREAD

**Issue by ghost** [Hex-Dragon/PCL2#883]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

回声洞投稿的时候，在PCL 2内弹出窗口，填写信息，最好能显示投稿是否被加入回声洞。

### 原因

这项优化让我可以更方便地投稿回声洞。
如果没有这项优化，我每次都必须打开网页，上传赞助凭证，让操作变得很麻烦。

**Comment by rumengchuxing062** [comment]
想法不错
但是金数据要求登录
所以自动提交要求账号的（QQ用户：az）

**Comment by LTCatt** [comment]
PCL2 没有真正意义的服务器，所以得用金数据（摊手
