### ISSUE TITLE
添加mod列表 可以对多版本安装相同mod mod迁移功能

### ISSUE THREAD

**Issue by XZirui** [Hex-Dragon/PCL2#884]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

对于部分玩家来说（生电或喜欢追求最新版本的玩家），游戏每次更新都要重新下载最新版本的mod，而mod列表通常是固定的（尤其对于生电玩家 基本更新到最新版本都要下载masa全家桶和各种mod） （虽然pcl2的mod下载已经很便利了 但是通常需要下载很多mod） 可否开发一个功能 可以对于某些版本下载特定的一些mod

### 原因

比如： 我需要苹果皮、小地图、masa全家桶、背包整理、地毯等等…… 但是当我从1.19迁移到1.20时 大部分mod都是无法通用的 而这些基于fabric的mod一般都会非常迅速地更新到最新版本（当然forge也一样） 就需要手动下载最新版 如果能有mod迁移功能 安装新版本时自动按照一个列表里的mod（自定义的列表）下载对应版本的mod就好了

**Comment by WForst-Breeze** [comment]
考虑使用 CurseForge 格式，与 #728 类似，感谢您的反馈~
