### ISSUE TITLE
游戏窗口大小设置失效

### ISSUE THREAD

**Issue by g-mph** [Hex-Dragon/PCL2#885]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

更新最新的 Snapshot 2.4.5 后出现的 bug。
![image](https://user-images.githubusercontent.com/64201424/211729085-d7810da5-8905-4365-b094-5af0a78cdbc1.png)
![image](https://user-images.githubusercontent.com/64201424/211729186-289245da-c288-40e7-8ce7-714bef40b8bc.png)

### 重现步骤

1、点击 PCL2
2、点击设置
3、往下滚，看到游戏窗口，选择自定义大小，在右边设置自定义大小（如 1280 * 720）
4、点击下载，随便找一个版本下载（已下载游戏请忽略）
5、点击启动
6、点击启动游戏
7、发现还是默认窗口大小

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10389216/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10389218/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10389219/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10389220/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10389221/Log1.txt)

**Comment by WForst-Breeze** [comment]
是不是 #856 引起的原因……？

**Comment by g-mph** [comment]
> 是不是 #856 引起的原因……？

有可能是。奇了怪了，为什么我搜索 issue 没搜到这个呢？

**Comment by g-mph** [comment]
> 是不是 #856 引起的原因……？

不过启动器 更新前都没这问题，我也不知道是不是一样的问题

**Comment by ZS2147483647** [comment]
不是一个东西,他的是是失效,我这是高版本实际分辨率长和宽分别是设置的一半

**Comment by ZS2147483647** [comment]
新版高版本需要加倍,旧版低版本需要减半,就是不能设多少来多少

**Comment by andywowws** [comment]
建议先用https://github.com/fenggwsx/WinSizer凑合着用

**Comment by LTCatt** [comment]
与 #856 重复
