### ISSUE TITLE
建议使右键菜单符合 PCL 风格。

### ISSUE THREAD

**Issue by g-mph** [Hex-Dragon/PCL2#886]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

![image](https://user-images.githubusercontent.com/64201424/211740759-af256a77-8928-45bc-addf-dae4d9789c75.png)

这里不是 PCL 风格的菜单。

### 原因

目前在这里右键菜单有一定延迟，点起来有点难受（虽然比垃圾 Win11 的菜单就更好）。
风格与  PCL 启动器的风格不匹配，看着也难受。

如果能优化就舒服多了。

**Comment by WForst-Breeze** [comment]
已初步确认，感谢您的反馈~
（这项反馈我依稀记得在金数据中有人提及过，我也不敢确定

**Comment by LBZiXL** [comment]
龙猫：我觉得没什么必要

**Comment by g-mph** [comment]
> 龙猫：我觉得没什么必要

我猜龙猫：要是我没有其他功能要做的话，或许可以做一下。

**Comment by LTCatt** [comment]
做不了，这个是傻逼 WPF 写死的，根本没法改……
