### ISSUE TITLE
建议增加挂起游戏功能。

### ISSUE THREAD

**Issue by g-mph** [Hex-Dragon/PCL2#887]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

众所周知，Java 版我的世界在暂停游戏进入后台后仍然大量占用系统资源。如果加入了挂起游戏功能，就能解决这一个问题。

### 原因

如果没有这个功能，Java 在后台仍占用大量系统资源。

**Comment by zkitefly** [comment]
我觉得这个功能可以交给模组，而且这个功能我觉得不在启动器的范畴里

**Comment by zkitefly** [comment]
我觉得这个功能可以交给模组，而且这个功能我觉得不在启动器的范畴里

**Comment by g-mph** [comment]
> 我觉得这个功能可以交给模组，而且这个功能我觉得不在启动器的范畴里

我觉得这个功能是模组无法实现的。模组也是 Java 的进程运行的，要让模组来挂起 Java 进程，我觉得不太现实。
我觉得这事挺适合启动器干的。

**Comment by zkitefly** [comment]
~我有种预感，龙猫会拒掉~

**Comment by nhx100218** [comment]
me too

**Comment by youzi-2333** [comment]
调用一下~~某人口中的系统级高危库 kernel32~~ 应该也许大概就能解决这个问题，毕竟就是把任务给挂起来，任务处理应该挺好做的，~~而且还能防止摸鱼被发现~~

**Comment by LTCatt** [comment]
超出启动器范畴了……

**Comment by quannen** [comment]
果不其然啊
