### ISSUE TITLE
搜索时拖入添加mod不会在搜索框搜索结果下显示

### ISSUE THREAD

**Issue by sssysy** [Hex-Dragon/PCL2#888]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在搜索mod时拖入新mod后**(mod文件名有包含搜索的内容)**不会立即显示该mod，需要刷新才能显示

### 重现步骤

1. 进入版本设置 - Mod管理
2. 在搜索框输入暂未添加进去的mod名字
3. 搜索结果出来后把mod拖入窗口安装
4. PCL2加载后不会立即显示新拖入的mod，必须改变搜索框内容使搜索重新开始搜索才能刷新出来

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10389736/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10389737/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10389738/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10389739/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10389740/Log2.txt)

**Comment by WorldHim** [comment]
这个不算bug吧……
PCL在你加入mod后已经完成了搜索，在 `mods` 文件夹内容更改时PCL可能没有重新搜索。所以……

**Comment by sssysy** [comment]
32F5-2980-F6D4-189E

**Comment by LTCatt** [comment]
你的解锁码：Q1BtoeK9uqphU6m+UT6aKD0hpZY76DsR
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
