### ISSUE TITLE
特定 URL 导致判断的文件名太长，从而无法使用自定义下载

### ISSUE THREAD

**Issue by youzi-2333** [Hex-Dragon/PCL2#889]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

虽然我知道和 #841 相似，但是还是想发一个……

http应该已经支持了一个头部，名字叫做 `Content-Disposition`，这里面有文件名相关信息，于是乎我们就可以做出自动重命名。

否则，有些URI带问号的链接会报错文件名太长，无法保存文件。

### 原因

这样可以让URI带问号的文件能够下载，并且免去了手动重命名的步骤。

**Comment by LTCatt** [comment]
这个涉及到 PCL2 的下载核心了……
因为 MC 相关的所有文件的文件名都不需要联网确认，所以下载核心在设计最初，就必须要求在任务创建时指定文件名。所以要添加这个支持比想像中困难许多。
至于文件名太长导致无法下载，可以作为 Bug 来修……传一个对应的 Log 并且给我一个会导致这个 Bug 的网址？

**Comment by LTCatt** [comment]
能不能传一个对应的 Log 并且给我一个会导致这个 Bug 的网址？

**Comment by myunco** [comment]
> 这个涉及到 PCL2 的下载核心了…… 因为 MC 相关的所有文件的文件名都不需要联网确认，所以下载核心在设计最初，就必须要求在任务创建时指定文件名。所以要添加这个支持比想像中困难许多。 至于文件名太长导致无法下载，可以作为 Bug 来修……传一个对应的 Log 并且给我一个会导致这个 Bug 的网址？

既然自动获取名称不好实现，不如下载前允许手动指定文件名...

**Comment by WorldHim** [comment]
> > 这个涉及到 PCL2 的下载核心了…… 因为 MC 相关的所有文件的文件名都不需要联网确认，所以下载核心在设计最初，就必须要求在任务创建时指定文件名。所以要添加这个支持比想像中困难许多。 至于文件名太长导致无法下载，可以作为 Bug 来修……传一个对应的 Log 并且给我一个会导致这个 Bug 的网址？
> 
> 既然自动获取名称不好实现，不如下载前允许手动指定文件名...

建议新开一个 issue？
