### ISSUE TITLE
自动选择 Java 时对每个 Java 控制优先级

### ISSUE THREAD

**Issue by WorldHim** [Hex-Dragon/PCL2#892]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在自动选择 Java 时允许优先选择某版本 Java，或是忽略某版本 Java。

### 原因

这项优化让我可以更方便地 控制 自动选择 使用的 Java（装了多个版本的 Java，有一部分 Java 因版本较老/优化较差我不使用，但因开发需要留存）。
如果没有这项优化，我每次都必须 手动指定，让操作变得很麻烦。

**Comment by LTCatt** [comment]
理论上 PCL2 只需要负责选出能启动游戏的 Java……这个功能绝大多数玩家都用不上，因此不太可能被制作。
如果选择的 Java 有误导致不能运行，可以额外提交 Bug。
如果想完全阻止选择某个 Java，可以等 #893……
