### ISSUE TITLE
允许删除自动搜索到的 Java，使这些 Java 不被自动选择

### ISSUE THREAD

**Issue by WorldHim** [Hex-Dragon/PCL2#893]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

使自动搜索到的 Java 条目能被删除（不是卸载 Java）

### 原因

类似 #892
这项优化让我可以更方便地 控制 自动选择 使用的 Java（装了多个版本的 Java，有一部分 Java 因版本较老/优化较差我不使用，但因开发需要留存）。
如果没有这项优化，我每次都必须 手动指定，让操作变得很麻烦。

**Comment by WForst-Breeze** [comment]
与 #874 重复，感谢您的反馈~

**Comment by WorldHim** [comment]
> 与 #874 重复，感谢您的反馈~

其实不重复，只是可以一起处理

**Comment by WForst-Breeze** [comment]
> 其实不重复，只是可以一起处理

是重复的（）您和 #874 提及的内容基本相同，#892 中[龙猫的拒绝原因](https://github.com/Hex-Dragon/PCL2/issues/892#issuecomment-1380845018)中指向的反馈也是 #874 qwq……

**Comment by horizon86** [comment]
可以从注册表手动删除一下？\HKEY_CURRENT_USER\SOFTWARE\PCL

**Comment by youzi-2333** [comment]
> 可以从注册表手动删除一下？\HKEY_CURRENT_USER\SOFTWARE\PCL

PCL2 又不会把搜索到的 Java 存注册表……
