### ISSUE TITLE
加入安装mrpack（Modrinth整合包）的选项

### ISSUE THREAD

**Issue by taoqibaohalo** [Hex-Dragon/PCL2#895]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [x] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

加入一个安装或搜索Modrinth整合包的选项，或添加拖拽操作

### 原因

我们某个服务器交流群都抱怨mrpack只能用MultiMC启动器（那玩意贼难用，还要正版）
目前国内启动器就一个HMCL支持
类似下图的整合包：
![image](https://user-images.githubusercontent.com/115784649/211955522-3ea1ca61-399c-4fff-8100-e1aa66685b2a.png)
我觉得挺有必要的（如果太忙没搞也能理解的.jpg

**Comment by Big-Cake-jpg** [comment]
与 #38 重复。

您可以查阅 [Modrinth 官方文档](https://docs.modrinth.com)来了解如何通过使用 BakaXL 安装 Modrinth 整合包（看不懂英文的话，我和其他两个人在做中文本地化了，过段时间发 PR）。目前国内除了 HMCL 外，BakaXL 也有对 Modrinth 的完全支持。
