### ISSUE TITLE
下载界面中发布时间显示错误

### ISSUE THREAD

**Issue by tianrenwufang** [Hex-Dragon/PCL2#896]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

PCL2下载界面在显示包括但不限于Minecraft本体与Forge,Liteloader等拥有具体发布时间的下载项时，发布时间被错误的显示为yyyy年MM年DD 时时：分分的格式

### 重现步骤

1、打开PCL2
2、打开下载页面
3、点击“自动安装”或“手动安装包”下的“Minecraft”或“Forge”或“Liteloader”

### 日志与附件

[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10397656/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10397657/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10397658/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10397659/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10397660/Log3.txt)

**Comment by LTCatt** [comment]
![image](https://user-images.githubusercontent.com/40348278/212151214-1aed7b92-0902-45c3-9cf6-b2bc0815e2a0.png)

有截图么，我看着是正常的啊？

**Comment by tianrenwufang** [comment]
![JM RHPJTZ{ GZC~3XX9~@H5](https://user-images.githubusercontent.com/79460434/212211072-2f6393d4-e32e-416c-8113-c2006bc2c369.png)

**Comment by rumengchuxing062** [comment]
这其实不影响吧

**Comment by LTCatt** [comment]
这应该是你的系统时间格式设置有问题，不是 PCL 的 Bug……
