### ISSUE TITLE
[优化] 修改Hosts文件后，日志中错误提示“你的网络环境不佳，导致难以连接到服务器”

### ISSUE THREAD

**Issue by youzi-2333** [Hex-Dragon/PCL2#897]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

重现步骤：
1. 在Hosts文件中加入：`127.0.0.1 pcl2-server-1253424809.file.myqcloud.com`
2. 重启PCL2
3. 一段时间后，打开日志文件，其中提示如下：
```
[11:11:33.103] [Launch] 验证登录失败：连接服务器超时，请检查你的网络环境是否良好（https://littleskin.cn/api/yggdrasil/authserver/validate）：你的网络环境不佳，导致难以连接到服务器。请重试，或尝试使用 VPN。
[11:11:33.103] [Launch] 已触发超时登录失败
[11:11:33.104] 加载线程 Loader Login Auth (15) 发生运行时错误：$登录失败：连接登录服务器超时。
请检查你的网络状况是否良好，或尝试使用 VPN！
你的网络环境不佳，导致难以连接到服务器。请重试，或尝试使用 VPN。
————————————
详细错误信息：
→ 
   在 PCL.ModLaunch.McLoginServerStart(LoaderTask`2 Data)
   在 PCL.ModLoader.LoaderTask`2._Closure$__12-0._Lambda$__0()
[11:11:33.104] [Loader] 加载器 Loader Login Auth 状态改变：Failed
[11:11:33.112] 加载线程 登录 (14) 发生运行时错误：$登录失败：连接登录服务器超时。
请检查你的网络状况是否良好，或尝试使用 VPN！
你的网络环境不佳，导致难以连接到服务器。请重试，或尝试使用 VPN。
————————————
详细错误信息：
→ 
   在 PCL.ModLoader.LoaderBase.WaitForExit(Object Input, LoaderBase LoaderToSyncProgress, Boolean IsForceRestart)
   在 PCL.ModLaunch.McLoginStart(LoaderTask`2 Data)
   在 PCL.ModLoader.LoaderTask`2._Closure$__12-0._Lambda$__0()
   在 PCL.ModLaunch.McLoginServerStart(LoaderTask`2 Data)
   在 PCL.ModLoader.LoaderTask`2._Closure$__12-0._Lambda$__0()
```
因此，可以在无法连接服务器时在Hosts文件中搜索PCL2服务器地址，或是判断解析后的IP是否准确，避免误导用户。

感觉我就是来卡Bug的，所以这个Issue没有提在Bug反馈里面，不想修就关了吧……

### 原因

这项优化能够更加准确的判断无法连接服务器时的问题。

如果不增加这项优化，在第三方程序恶意添加Hosts时，无法准确报出错误原因。

**Comment by youzi-2333** [comment]
等会，这个连接超时不是LittleSkin的吗，但是我的网络很好啊（

**Comment by WForst-Breeze** [comment]
刻意卡出的 Bug 龙猫不会修，除非真的能提高游戏体验，而且你这个 bug 到底有没有成功卡出来……？🤔如有，请补充日志

**Comment by youzi-2333** [comment]
um，bug是我卡出来的，但是我主要想到第三方程序会恶意写入Hosts，这样用户就没法下载PCL2更新了……

附Log：https://github.com/youzi-2333/cloud/blob/master/PCL/2023/01/12/Log2.txt

**Comment by g-mph** [comment]
如果第三方恶意写入 hosts 了，你还有心情游戏吗（

我觉得顶多加一个建议检查 hosts 文件的提示。

**Comment by WForst-Breeze** [comment]
收到，谢谢补充

**Comment by LTCatt** [comment]
作死不管。
