### ISSUE TITLE
修改程序报错时提交报告所指向的网站

### ISSUE THREAD

**Issue by rumengchuxing062** [Hex-Dragon/PCL2#902]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

PCLBUG反馈已经完全移交到GitHub
但是出现问题时PCL会要求用户将BUG提交到旧的金数据网站
可以改一下

### 原因

PCLBUG反馈已经完全移交到GitHub

**Comment by ComputerCPT** [comment]
这是BUG罢

**Comment by rumengchuxing062** [comment]
我觉得不像
他没有使PCL出现问题

**Comment by LTCatt** [comment]
额，你用的是最新版本么？最新版本应该已经改地址了

**Comment by WorldHim** [comment]
在 `Plain Craft Launcher 2/FormMain.xaml.vb` 中，第 `584` 行，有指向金数据的链接。
具体应该是在这种弹窗的反馈中
![image](https://user-images.githubusercontent.com/68632311/212574720-c5412b96-ae87-4b27-b433-6509a5e778a5.png)
（因为无法复现所以用的是 `Dev 0.4.4` 的 `弹窗测试`）
已提交 PR。

**Comment by rumengchuxing062** [comment]
@LTCatt
快照版2.4.5
确实有出现金数据的地址

**Comment by WorldHim** [comment]
> @LTCatt 快照版2.4.5 确实有出现金数据的地址

麻烦截个图？

**Comment by rumengchuxing062** [comment]
但是复现失败了.orz

**Comment by rumengchuxing062** [comment]
我翻一下源代码

**Comment by rumengchuxing062** [comment]
这个
Log("请在 https://jinshuju.net/f/rP4b6E?x_field_1=crash 提交错误报告，以便于作者解决此问题！")
和日志里面的一模一样[doge]

**Comment by rumengchuxing062** [comment]
> > @LTCatt 快照版2.4.5 确实有出现金数据的地址
> 
> 麻烦截个图？~（想知道是不是我说的那种~ 还有，建议不要随便@龙猫

是这个

**Comment by rumengchuxing062** [comment]
对了，我忘了，解锁码给一下

**Comment by rumengchuxing062** [comment]
解锁码给一下.jpg

**Comment by LTCatt** [comment]
发一下识别码……

**Comment by rumengchuxing062** [comment]
> 发一下识别码……
5697-C103-34AD-769C

**Comment by LTCatt** [comment]
你的解锁码：ZYIofXt8zHq0RMaQBtjDB6ckPANfvdwd
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
