### ISSUE TITLE
在前往下载Java界面增加不去官网下载

### ISSUE THREAD

**Issue by RawDiamondMC** [Hex-Dragon/PCL2#905]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

PCL2没有找到Java情况下启动游戏会提示前往下载Java17
希望在确定旁增加一个按钮“不去下载”

### 原因

有Java但是PCL2没找到，弹出个浏览器有些烦人

**Comment by zkitefly** [comment]
Liberica JDK (JRE 标准版)：
Java 8 x86_64：https://download.bell-sw.com/java/8u352+8/bellsoft-jre8u352+8-windows-amd64.msi
                         https://download.bell-sw.com/java/8u352+8/bellsoft-jre8u352+8-windows-amd64.zip
Java 8 x86：https://download.bell-sw.com/java/8u352+8/bellsoft-jre8u352+8-windows-i586.msi
                    https://download.bell-sw.com/java/8u352+8/bellsoft-jre8u352+8-windows-i586.zip
Java 17 x86_64：https://download.bell-sw.com/java/17.0.5+8/bellsoft-jre17.0.5+8-windows-amd64.msi
                           https://download.bell-sw.com/java/17.0.5+8/bellsoft-jre17.0.5+8-windows-amd64.zip
Java 17 x86：https://download.bell-sw.com/java/17.0.5+8/bellsoft-jre17.0.5+8-windows-i586.msi
                      https://download.bell-sw.com/java/17.0.5+8/bellsoft-jre17.0.5+8-windows-i586.zip
Java 17 ARM64：https://download.bell-sw.com/java/17.0.5+8/bellsoft-jre17.0.5+8-windows-aarch64.msi
                            https://download.bell-sw.com/java/17.0.5+8/bellsoft-jre17.0.5+8-windows-aarch64.zip

**Comment by WorldHim** [comment]
> Liberica JDK (JRE 标准版)： Java 8 x86_64：https://download.bell-sw.com/java/8u352+8/bellsoft-jre8u352+8-windows-amd64.msi https://download.bell-sw.com/java/8u352+8/bellsoft-jre8u352+8-windows-amd64.zip Java 8 x86：https://download.bell-sw.com/java/8u352+8/bellsoft-jre8u352+8-windows-i586.msi https://download.bell-sw.com/java/8u352+8/bellsoft-jre8u352+8-windows-i586.zip Java 17 x86_64：https://download.bell-sw.com/java/17.0.5+8/bellsoft-jre17.0.5+8-windows-amd64.msi https://download.bell-sw.com/java/17.0.5+8/bellsoft-jre17.0.5+8-windows-amd64.zip Java 17 x86：https://download.bell-sw.com/java/17.0.5+8/bellsoft-jre17.0.5+8-windows-i586.msi https://download.bell-sw.com/java/17.0.5+8/bellsoft-jre17.0.5+8-windows-i586.zip Java 17 ARM64：https://download.bell-sw.com/java/17.0.5+8/bellsoft-jre17.0.5+8-windows-aarch64.msi https://download.bell-sw.com/java/17.0.5+8/bellsoft-jre17.0.5+8-windows-aarch64.zip 这个是下载链接，可以用 ![image](https://user-images.githubusercontent.com/64117916/212466998-221270c0-7170-4386-922f-6b92b37cd4b8.png)

？

**Comment by zkitefly** [comment]
呀，艹，看错了，我以为是先“不去下载”是指直接通过PCL2下载 Java 问不是浏览器里面（

**Comment by LTCatt** [comment]
啊，算了，之后反正要做自动 java 补全的……
