### ISSUE TITLE
Java版本判断错误

### ISSUE THREAD

**Issue by Anythingteam** [Hex-Dragon/PCL2#907]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://user-images.githubusercontent.com/103157696/212300580-50094368-d51b-42f8-a74e-89f893145a80.png)
如图所示，java17.0.4为以前的指定版本（启动游戏时java文件夹已被删除并更换至zulu17.0.5）却仍提示我使用的Java为17.0.4，认为我的Java版本不属于17或18。

### 重现步骤

1、安装java17
2、将此版本设为指定版本
3，卸载此版本，安装其他版本的java17
4，启动游戏

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10410793/Log2.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10410794/Log1.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10410796/Log5.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10410797/Log4.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10410798/Log3.txt)

**Comment by Anythingteam** [comment]
![QQ截图20230113185628](https://user-images.githubusercontent.com/103157696/212303979-08a85dc0-8269-453e-bbc3-0391482a8e11.png)
补充：这是此时pcl2检测出的java

**Comment by Anythingteam** [comment]
![QQ截图20230113190400](https://user-images.githubusercontent.com/103157696/212305453-21151b4d-1df2-4451-97e0-b5bd52832763.png)
再次补充，可见此时原java文件夹已经没了（我换成zulu了

**Comment by WorldHim** [comment]
你重启 PCL 试试？

**Comment by Anythingteam** [comment]
重启也是如此，卸载后重装也是如此

**Comment by WorldHim** [comment]
你在版本设置里有没有单独设定过 `游戏 Java`，而不是使用全局设置

**Comment by Anythingteam** [comment]
有，指定的就是被删除的那个

**Comment by WorldHim** [comment]
> 有，指定的就是被删除的那个

那就对了，PCL 不会主动更新选定 Java 的信息。启动时 PCL 没有检测到原 Java，可能因为一些奇怪的判断机制，然后就弹窗了。（当然这个弹窗内容确实有问题）

**Comment by quannen** [comment]
那你自己调整一下不就行了..........
