### ISSUE TITLE
启动未响应

### ISSUE THREAD

**Issue by pengpeng9811** [Hex-Dragon/PCL2#912]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在个别时候启动游戏会卡在白屏未响应状态，就是有窗口自动最大化的那一步，手动设置启动游戏窗口为原大小，就可以正常进游戏

### 重现步骤

1.新安装一个版本，
2.创建游戏，
3.手动添加mod后再次启动游戏，
4.进游戏，等待游戏窗口出现，游戏就会一直未响应

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10418000/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10418001/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10418002/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10418003/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10418004/Log5.txt)

**Comment by WorldHim** [comment]
这个已经启动游戏了大概率不属于 PCL 的问题，很可能是你的电脑原因

**Comment by LTCatt** [comment]
MC 卡了和启动器无关……
