### ISSUE TITLE
关于PCL注册表的BUG

### ISSUE THREAD

**Issue by rongjianuo** [Hex-Dragon/PCL2#914]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

关于我换了个重装了个系统（电脑没换），再使用注册表时，啥也没有（隐藏主题），好像是龙猫的识别码DES加密没搞好，导致了这种注册表BUG
![image](https://user-images.githubusercontent.com/119654171/212527130-d38dd540-53bd-4e58-beda-d46b4daa546b.png)
服了，改一下吧
还有就是能不能把用过的识别码不加入本月去，我给我盆友更新码的时候我在更新，我本月用不了了（悲伤）

### 重现步骤

1、导出PCL注册表
2、复制文件到U盘
3、重装系统
4、使用U盘的注册表
5、打开PCL
6，查看个性化
7，BUG产生了

### 日志与附件

不用日志

**Comment by WorldHim** [comment]
额，你的描述与步骤不符啊，确定备份并导入了原注册表？
还有 PCL 如果你发电的不是 ￥54.32 档请不要与他人分享（龙猫也要赚钱

**Comment by LTCatt** [comment]
这类似的问题我没法处理……
此外，54.32 档位的赞助会给你 `3 个` 识别码的使用权，也就是说就算算上你送给朋友一个，你也 **在 20 天内自己使用了 3 个不同的识别码** ，我只能一概认为这超过了正常的限度，抱歉（
