### ISSUE TITLE
mod搜索显示“未将对象引用设置到对象的实例”

### ISSUE THREAD

**Issue by Cast245** [Hex-Dragon/PCL2#915]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

PCL快照版：在“下载”界面的“Mod分类”中，输入“动态fps”等关键字眼会显示“未将对象引用设置到对象的实例”，从而无法进行搜索。

### 重现步骤

1.打开最新快照版
2.点击"下载"板块
3.点击“CurseForge”中的“Mod”分类
4.搜索Mod“中文字符+英文字符”（例：动态fps，速度speed）
5.搜索结果显示“未将对象引用设置到对象的实例”

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10419667/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10419668/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10419669/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10419670/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10419671/Log5.txt)

**Comment by Big-Cake-jpg** [comment]
已复现，感谢你的反馈~

**Comment by wxjzx682** [comment]
看到这个标题就开始有心理阴影了（自己给泰拉瑞亚写mod的时候出现了N多次）
【只是单纯来凑个热闹的人】

**Comment by Cast245** [comment]
申请解锁活跃橙隐藏主题

**Comment by WorldHim** [comment]
> 申请解锁活跃橙隐藏主题

你得发识别码啊。。。

**Comment by WForst-Breeze** [comment]
反馈者识别码为：1326-8B4B-A330-568A

**Comment by Light-Beacon** [comment]
解锁码已私聊发送
