### ISSUE TITLE
看不到Optifine披风

### ISSUE THREAD

**Issue by gyeongjjot** [Hex-Dragon/PCL2#916]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

用PCL2启动的游戏看不到Optifine披风，别的启动器正常

### 重现步骤

1、点击xxxx
2、往下滚，然后点击xxxx

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10419794/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10419795/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10419796/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10419797/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10419798/Log1.txt)

**Comment by WorldHim** [comment]
额，确定一下你是否正确安装了Optifine

**Comment by Big-Cake-jpg** [comment]
OptiFine 披风只有安装 OptiFine 或者 Cape 模组方能显示，请检查你是否安装二者之一。

**Comment by LTCatt** [comment]
无论如何，这个问题都和启动器没有关系……
