### ISSUE TITLE
热力系列mod名称错误

### ISSUE THREAD

**Issue by MrZhang21626** [Hex-Dragon/PCL2#917]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

热力系列的mod名称错误，热力基本、热力革新、热力农业、热力运输均被显示为热力膨胀，且英文名称错误。
![image](https://user-images.githubusercontent.com/87157535/212532611-03806e0c-46d1-4b4d-ac49-a7002aa93db3.png)

### 重现步骤

在mod下载页面搜索“Thermal”，会发现大部分热力系列的mod名称显示为热力膨胀

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10419821/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10419822/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10419823/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10419824/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10419825/Log5.txt)

**Comment by WorldHim** [comment]
？并没有复现成功。
![image](https://user-images.githubusercontent.com/68632311/212548177-5eff506a-001c-4b02-8821-fca81f1f59dd.png)
会不会是 Curseforge API 抽风？（小概率事件？）

**Comment by LTCatt** [comment]
与 #589 重复

**Comment by MrZhang21626** [comment]
https://user-images.githubusercontent.com/87157535/212574940-fdd971fb-5d11-456d-8000-d05cc84c27f6.mp4

早上我又试了一下，名称还是不对

**Comment by WorldHim** [comment]
> ![image](https://user-images.githubusercontent.com/87157535/212575011-eb1cdefd-a5fd-4021-8f7b-9c7ad5bad79b.png)
> 
> 早上我又试了一下，名称还是不对

但是我一直是对的（疑惑.jpg

**Comment by MrZhang21626** [comment]
有可能Curseforge的API又抽风了

**Comment by LTCatt** [comment]
2.4.5 已经修复，还没有推送到正式版……
