### ISSUE TITLE
启动游戏中"你知道吗"中的问题

### ISSUE THREAD

**Issue by niuyuhao0818** [Hex-Dragon/PCL2#920]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

启动游戏中"你知道吗"中有一条“PCL2隐藏主题中有一个解密游戏，至今通关的人不超过40人！”描述不当，肯定有40人了

### 原因

误导大众

**Comment by xuzehao2012** [comment]
你怎么知道的？

**Comment by niuyuhao0818** [comment]
> 你怎么知道的？

因为我知道你知道我不知道你知道我知道

**Comment by WorldHim** [comment]
> 你怎么知道的？

你tm故意找茬是不是（doge

**Comment by WorldHim** [comment]
> 启动游戏中"你知道吗"中有一条“PCL2隐藏主题中有一个解密游戏，至今通关的人不超过40人！”描述不当，肯定有40人了

这个是远古时期投稿，不会自动更新

**Comment by Louis-ZYH** [comment]
已经有人公布解谜游戏的直接通过方法了…………
> 启动游戏中"你知道吗"中有一条“PCL2隐藏主题中有一个解密游戏，至今通关的人不超过40人！”描述不当，肯定有40人了

**Comment by WorldHim** [comment]
> 那个解密游戏到底是啥

极客蓝的主题解锁

**Comment by 212112111zwl** [comment]
我无耻的去b站上找了所有隐藏主题的解秘方法

**Comment by z0z0r4** [comment]
"你知道吗"是不会实时更新的…依稀记得之前发现是直接写在代码里面的
