### ISSUE TITLE
隐藏主题解锁bug

### ISSUE THREAD

**Issue by niuyuhao0818** [Hex-Dragon/PCL2#923]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

导致某99次的主题无法被解锁

### 重现步骤

1、启动100次游戏
2、弹出求赞助弹窗（启动100次游戏）
3、99次重逢的主题未解锁

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10420193/Log1.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10420195/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10420196/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10420197/Log5.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10420198/Log2.txt)

**Comment by WorldHim** [comment]
这个主题叫铁杆粉，还有请确定你使用的不是正式版

**Comment by niuyuhao0818** [comment]
> 这个主题叫铁杆粉，还有请确定你使用的不是正式版

不是

**Comment by LTCatt** [comment]
它的解锁条件是打开 100 次 PCL……
