### ISSUE TITLE
在没有java时提示自动下载

### ISSUE THREAD

**Issue by xuzehao2012** [Hex-Dragon/PCL2#924]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在pc没有Java时提示你还没有Java我们帮你自动下载

### 原因

（示例）
这项优化让我可以更方便地有java。
如果没有这项优化，我每次都必须找到官网，找到页面，点击下载，让操作变得很麻烦。

**Comment by WorldHim** [comment]
已有这个功能
