### ISSUE TITLE
PCL功能隐藏出现文件写入失败

### ISSUE THREAD

**Issue by rumengchuxing062** [Hex-Dragon/PCL2#926]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在设置-个性化-功能隐藏部分
随机勾选一个部分
会出现[09:48:08.552] 写入文件时出错：J:\minecraft\PCL\Setup.ini：对路径“J:\minecraft\PCL\Setup.ini”的访问被拒绝。
PCL2 的权限不足。请尝试右键 PCL2，选择以管理员身份运行。
以管理员身份执行也会报错
Windows权限页面里所有用户都可以写入
详细错误信息：
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   在 System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   在 System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding)
   在 PCL.ModBase.WriteFile(String FilePath, String Text, Boolean Append, Encoding Encoding)
错误类型：System.UnauthorizedAccessException
[09:48:10.119] [Control] 按下复选框（True）：下载
[09:48:10.120] 写入文件时出错：J:\minecraft\PCL\Setup.ini：对路径“J:\minecraft\PCL\Setup.ini”的访问被拒绝。
PCL2 的权限不足。请尝试右键 PCL2，选择以管理员身份运行。
————————————

### 重现步骤

1、点击设置
2、点击个性化
2、往下滚，然后点击功能隐藏的任何一个

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10421944/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10421945/Log2.txt)

**Comment by niuyuhao0818** [comment]
这个情况不好复现啊，还有这个锅应该windows背吧

**Comment by rumengchuxing062** [comment]
您是没看到我写的吗
Windows权限页面里所有用户均可写入该文件

**Comment by rumengchuxing062** [comment]
没事了
我权限没配好
