### ISSUE TITLE
整合包java选择错误

### ISSUE THREAD

**Issue by ffjjss** [Hex-Dragon/PCL2#927]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在使用整合包All the Mods 7 - To the Sky时，java选择为jdk19，启动失败需要手动选择为jdk17使用，我不知道这个情况会不会在其它1.18.2整合包上出现

### 重现步骤

1、在下载-整合包页面下载All the Mods 7 - To the Sky整合包
2、在安装jdk19且开启自动选择java的情况下启动
3、看到Java版本过高启动失败提示框

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10422297/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10422298/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10422299/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10422300/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10422301/Log5.txt)

**Comment by ffjjss** [comment]
已确认不会在1.18.2中出现该问题

**Comment by ffjjss** [comment]
识别码：912D-1FAA-5FC1-AAD5

**Comment by niuyuhao0818** [comment]
已经确认安装与整合包同版本Forge与Minecraft本体时不会出现该问题

**Comment by ffjjss** [comment]
那就应该是哪个mod的锅了

**Comment by LTCatt** [comment]
mod 导致兼容 java 变动不在我能处理的范围内 :(

**Comment by niuyuhao0818** [comment]
> mod 导致兼容 java 变动不在我能处理的范围内 :(

判断逻辑改一下，1.18.2用JAVA18，这样能大量避免ModAPI导致的整合包崩溃

**Comment by HeChuan404** [comment]
@niuyuhao0818 你要不去写个issue建议？awa
