### ISSUE TITLE
“你知道吗”显示错误

### ISSUE THREAD

**Issue by g-mph** [Hex-Dragon/PCL2#929]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://user-images.githubusercontent.com/64201424/212597974-5ecc63fa-80dc-48c3-9239-20d486dc633a.png)

### 重现步骤

1、点击启动游戏
2、查看“你知道吗”，有可能不是这一条，多试几遍即可吧

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10422456/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10422457/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10422458/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10422459/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10422460/Log5.txt)

**Comment by niuyuhao0818** [comment]
貌似没问题？

**Comment by g-mph** [comment]
抱歉……我看错了
