### ISSUE TITLE
（请点进来看看，这个请求不同）对Linux的支持

### ISSUE THREAD

**Issue by GADDQ** [Hex-Dragon/PCL2#931]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

支持linux系统，但你先别急，你听我说
我知道前面有两个提案被关了，万能的wine确实可以启动pcl2，但是老显示获取标识码错误，所以我在想能不能发一个不获取标识码的公测版本供linux下用wine启动pcl2，毕竟windows上用的全是pcl2，hmcl启动的时候大部分全是bug，很tm难受

### 原因

在linux上对wine跑pcl2进行支持

**Comment by niuyuhao0818** [comment]
去除标识码还会有其他奇怪的问题的。。。
还有去除标识码的话很多基于标识码的功能都要重写，懒猫不会改的。。。

**Comment by GADDQ** [comment]
noooooooooooooooooo linux用户哭泣

**Comment by niuyuhao0818** [comment]
> noooooooooooooooooo linux用户哭泣

VMware欢迎您的到来

**Comment by WTP016-CN** [comment]
建议更改 Issue 标题为删除标识码功能
此提案与支持 Linux 无关系

**Comment by WForst-Breeze** [comment]
建议同上，已初步确认，感谢您的反馈

**Comment by LTCatt** [comment]
对识别码系统的更改会让现有的东西炸一大片……算了…………
