### ISSUE TITLE
在mod页面显示更多热门模组

### ISSUE THREAD

**Issue by HeChuan404** [Hex-Dragon/PCL2#936]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在mod页面显示更多热门模组，可以做成很多页

### 原因

大家下载模组时可以看看热门模组，说不定能找到自己想要的

**Comment by WorldHim** [comment]
已初步确认，谢谢您的反馈
能否通过得看 curseforge API 支不支持，如果不支持那大概率会被毙掉

**Comment by LTCatt** [comment]
实际上就是翻页，已经有人交了（
