### ISSUE TITLE
关于动画的一些小建议

### ISSUE THREAD

**Issue by 212112111zwl** [Hex-Dragon/PCL2#937]
### 检查项

- [x] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

1. 做一个简单小巧但丝滑的最小化动画~
2. 快照版关闭PCL2时的下沉动画加一点弹跳感~

我在issues界面搜索过 “最小化“ ”动画“ 等关键词，都没搜到类似的结果

### 原因

不是要按强迫症标准精心设计嘛~~~

**Comment by WorldHim** [comment]
已初步确认，谢谢您的反馈。

**Comment by quannen** [comment]
我感觉新动画没以前的好看（真

**Comment by LTCatt** [comment]
最小化动画没法做，这被 windows 直接接管，要折腾很难……
关闭动画可能到时候再改一改吧……

**Comment by quannen** [comment]
罗伯特爆了.............
