### ISSUE TITLE
1.18.2默认使用用JAVA17，这样能大量避免ModAPI导致的整合包崩溃

### ISSUE THREAD

**Issue by niuyuhao0818** [Hex-Dragon/PCL2#942]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

导致的问题详见issues #927 
建议优先使用Java17启动（兼容性最好），若java列表中没有Java17，使用Java19启动（可以兼容游戏本体，但可能导致某些mod的ModAPI出现问题）

### 原因

（示例）
这项优化让我可以更方便地启动一些含有对JAVA19 ModAPI有兼容性问题的Mod的游戏或整合包。
如果没有这项优化，我每次都必须切换Java，让操作变得很麻烦。

**Comment by HeChuan404** [comment]
阿哲

**Comment by HeChuan404** [comment]
不愧是你还真写了
