### ISSUE TITLE
增加皮肤的 3D 预览

### ISSUE THREAD

**Issue by 212112111zwl** [Hex-Dragon/PCL2#945]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

在从本地选择好离线皮肤后弹出一个预览皮肤的窗口
支持的操作可以有：拖动以3D查看皮肤 确认选择皮肤 重新选择皮肤 等

### 原因

让大家可以预览并确认一下自己设置的皮肤
对一些更改了皮肤但在游戏中没有显示的情况可能也有帮助
预览让大家更方便得决定选择粗手臂还是细手臂

我不懂代码什么的，如果很难实现就算了~

**Comment by quannen** [comment]
你这个可以直接让龙猫加一个选择框选择一下，不过做起来不简单（littleskin不好用吗？

**Comment by WorldHim** [comment]
这个官启有，个人认为龙猫可能不会做
> * [x]  我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

**Comment by 212112111zwl** [comment]
我也是如此认为的🤣

**Comment by LTCatt** [comment]
考虑到实际意义有限但难度令人头疼，暂时不考虑制作
