### ISSUE TITLE
爱发电罗伯特BUG

### ISSUE THREAD

**Issue by LTDove** [Hex-Dragon/PCL2#946]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

好像54档时更新码和解锁码能无限刷(?)
我爱发电大号因违反用户协议被封禁,但是还能私聊已发电的创作者
然后发现封禁账户能无限刷?
现在测试了三台电脑(都是我的无代刷嫌疑)不同的解锁码.结果时都能刷????
但是没违反的好像就不能了(

### 重现步骤

用一个赞助龙猫后的封禁爱发电账号
私聊龙猫
按更新/解锁码+识别码私发龙猫即可
详细图片私聊:2487215845

### 日志与附件

无PCLBUG 爱发电bug

**Comment by quannen** [comment]
关了吧，龙猫不会处理的，又不是PCL的bug

**Comment by WorldHim** [comment]
#914 中龙猫有提到过
> 54.32 档位的赞助会给你 `3 个` 识别码的使用权
所以没有问题
