### ISSUE TITLE
Java版本报错后可退出

### ISSUE THREAD

**Issue by Anythingteam** [Hex-Dragon/PCL2#951]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在PCL2启动游戏报java版本有误时增加退出选项

### 原因

如果有错，我想退出后自己指定，而不是只能让pcl2自动选择

**Comment by WorldHim** [comment]
已初步确认，谢谢您的反馈。
