### ISSUE TITLE
在win11下运行会导致【以一种访问权限不允许的方式做了一个访问套接字的尝试】的问题，且无法下载

### ISSUE THREAD

**Issue by jiangcangyu** [Hex-Dragon/PCL2#952]
### 检查项

- [x] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

下载会出现【以一种访问权限不允许的方式做了一个访问套接字的尝试】的提示，登陆说需要vpn,网上所说因为端口冲突导致，请求加强win11的兼容性，对于HMCL同样出现相同问题，但是bakaXL没有出现以上问题

### 重现步骤
打开pcl2,点击下载
猜测是win11或hpyer-v兼容性问题
已经尝试关闭hpyer-v，调整动态端口范围，重启路由器，更改防火墙与杀毒，但是并没有解决问题。

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10440698/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10440699/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10440700/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10440701/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10440702/Log5.txt)

**Comment by PythonSmall-Q** [comment]
可能是梯子的端口和PCL的端口冲突了吧

**Comment by WorldHim** [comment]
请详细描述重现步骤，谢谢。

**Comment by jiangcangyu** [comment]
#这个没有步骤，点进去就是这样的

**Comment by jiangcangyu** [comment]
请问使用的是8080端口吗

**Comment by jiangcangyu** [comment]
@WorldHim  你可以尝试打开hpyer-v卡出相同效果，但是我不确定，也有可能是window11的更新导致其出现了如此的问题

**Comment by jiangcangyu** [comment]
> 可能是梯子的端口和PCL的端口冲突了吧

已经尝试删除梯子，但是未有效果

**Comment by PythonSmall-Q** [comment]
你说的Hyper-V已关闭是指从windows功能里移除还是关闭

**Comment by jiangcangyu** [comment]
> 你说的Hyper-V已关闭是指从windows功能里移除还是关闭

从windows功能关闭

**Comment by LTCatt** [comment]
`对于HMCL同样出现相同问题` 已经表示这不是启动器的问题了。考虑自己的网络环境……

**Comment by jiangcangyu** [comment]
> `对于HMCL同样出现相同问题` 已经表示这不是启动器的问题了。考虑自己的网络环境……

但是bakaXL却可以正常使用，我用pcl2是因为统一通行证登录，如果不能解决的话，请告诉我pcl2所用端口

**Comment by jiangcangyu** [comment]
> > `对于HMCL同样出现相同问题` 已经表示这不是启动器的问题了。考虑自己的网络环境……
> 
> 但是bakaXL却可以正常使用，我用pcl2是因为统一通行证登录，如果不能解决的话，请告诉我pcl2所用端口

@LTCatt

**Comment by LTCatt** [comment]
PCL2 没有占用任何端口……下载只是单纯的网络请求……
