### ISSUE TITLE
在 Mod 详情页一并显示该 Mod 的所有扩展 Mod

### ISSUE THREAD

**Issue by C1en-QwQ** [Hex-Dragon/PCL2#953]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

对有扩展的mod进行扩展展示
展示的方式类似前置mod的
![rt](https://image.dvrz.cn/images/2023/01/17/image.png)
在其主体mod下增加"扩展mod"
拿机械动力作为示例

依赖机械动力的Mod:
[更多机械动力物品 (More Create Stuffs)](https://www.mcmod.cn/class/3781.html)[机械动力：物品附加 (Create : Stuff Additions)](https://www.mcmod.cn/class/3779.html)[Create Plus](https://www.mcmod.cn/class/3931.html)[Boat Contraptions](https://www.mcmod.cn/class/3965.html)[CreateTweaker](https://www.mcmod.cn/class/3378.html)[Create Addon](https://www.mcmod.cn/class/3964.html)[Create Automated](https://www.mcmod.cn/class/4302.html)[[CC&A] Create Crafts & Additions](https://www.mcmod.cn/class/3437.html)[机械动力：甜食 (Create Confectionery)](https://www.mcmod.cn/class/4871.html)[[SP] 蒸汽动力 (Create: Steam Powered)](https://www.mcmod.cn/class/4944.html)[机械动力：齿轮附加 (Create Gears)](https://www.mcmod.cn/class/4223.html)[更多存储挂载 (More Mounted Storages)](https://www.mcmod.cn/class/5098.html)[KubeJS Create](https://www.mcmod.cn/class/5157.html)[应用机械 (applied_create)](https://www.mcmod.cn/class/5309.html)[Create Deco](https://www.mcmod.cn/class/5189.html)[机械动力：奶茶店 (Create Cafe)](https://www.mcmod.cn/class/6016.html)[Create Irrigation](https://www.mcmod.cn/class/5815.html)[压缩动力 (Compressed Creativity)](https://www.mcmod.cn/class/6054.html)[[IDAS] Integrated Dungeons and Structures](https://www.mcmod.cn/class/6142.html)[机械动力：合金 (Create: Alloyed)](https://www.mcmod.cn/class/6965.html)[Potato Canon Plus](https://www.mcmod.cn/class/7343.html)[Create Supercharged](https://www.mcmod.cn/class/6877.html)[Create Chunkloading](https://www.mcmod.cn/class/4637.html)[Ars Creo](https://www.mcmod.cn/class/5617.html)

这些mod是机械动力的扩展
如果采纳我的意见 这些应出现在机械动力主体mod安装的下方

### 原因

（示例）
这项优化让我可以更方便地安装mod扩展。
如果没有这项优化，我每次都必须重新搜索mod扩展，让操作变得很麻烦。

**Comment by WorldHim** [comment]
已初步确认，谢谢您的反馈。

**Comment by WForst-Breeze** [comment]
此反馈内容曾在 Discussion 中被提及，请见 [#607](https://github.com/Hex-Dragon/PCL2/discussions/607#discussioncomment-4416147)，鉴于反馈提及内容涉及到添加目前没有的新元素，故调整为 `新功能提案` ，感谢您的反馈~

**Comment by LTCatt** [comment]
这里的问题是，一个 Mod 可能会有非常多的扩展 Mod，导致加载会变得很艰难……
例如匠魂在 McMod 中显示有 50 个扩展，这会导致你在点进 Mod 详情页时，PCL2 需要获取这 50 个 Mod 的信息，已经相当于再进行一次 Mod 搜索了……也就是说，你每点进这种 Mod 的详情页，都得加载十秒钟。
所以还是算了……

**Comment by C1en-QwQ** [comment]
> 这里的问题是，一个 Mod 可能会有非常多的扩展 Mod，导致加载会变得很艰难……
> 
> 例如匠魂在 McMod 中显示有 50 个扩展，这会导致你在点进 Mod 详情页时，PCL2 需要获取这 50 个 Mod 的信息，已经相当于再进行一次 Mod 搜索了……也就是说，你每点进这种 Mod 的详情页，都得加载十秒钟。
> 
> 所以还是算了……

那如果是做成让用户选择性显示呢（
就是做成类似下拉框
