### ISSUE TITLE
在安装Optifine时未折叠原版

### ISSUE THREAD

**Issue by bruthax** [Hex-Dragon/PCL2#955]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在使用官方下载软件下载Optifine时，PCL2可以折叠原版。但用PCL2下载Optifine时，PCL2无法折叠
![b9fdc06ae10557bcb0d86040ae55cb1](https://user-images.githubusercontent.com/86935824/213068258-2b153d91-a2ca-4f1f-98e2-033294caf717.png)
（用官方下载器）
![1469136e3967efcf63c965e8d3badf5](https://user-images.githubusercontent.com/86935824/213068494-14e1141c-7426-478f-80b0-50a3180c31e3.png)
（用PCL2下载）

### 重现步骤

1、用PCL2安装Optifine
2、查看版本列表

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10441468/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10441469/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10441470/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10441471/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10441472/Log1.txt)

**Comment by quannen** [comment]
没看明白

**Comment by bruthax** [comment]
> 没看明白

就是用PCL2下载界面下载Optifine他不折叠原版（像第二张图片）

**Comment by bruthax** [comment]
> 没看明白

但用官方下载（https://www.optifine.net/）可以折叠（像第一张，原版1.19.2就在不常用版本里）

**Comment by WorldHim** [comment]
对比 `原版`、`Of官方版`、`PCL版Of` 的 `json` 文件，你就会发现：
`原版` 与 `PCL版Of` 的 `json` 大致相同，而 `Of官方版` 的 `json` 很小，依赖原版工作。
PCL 的折叠判断应该是看依赖关系，如果使用 `Of官方版`，`原版` 就是其依赖项，就会被折叠；而 `PCL版Of` 不依赖 `原版`，PCL 判断这是两个没有关系的版本，所以两者都不会折叠。

**Comment by WorldHim** [comment]
所以引起这个 bug 的主要原因是 `PCL安装的版本` 是不依赖原版的，而 `Of安装器安装的版本` 是依赖原版工作的。

**Comment by bruthax** [comment]
我觉得有两种修复办法：
1、把PCL安装的版本改为依赖原版
2、通过Of的版本找到与之相等的原版版本，再将其折叠
（个人建议，可能有漏洞）

**Comment by Louis-ZYH** [comment]
> 我觉得有两种修复办法： 1、把PCL安装的版本改为依赖原版 2、通过Of的版本找到与之相等的原版版本，再将其折叠 （个人建议，可能有漏洞）

也可以直接让PCL2在游戏文件夹中检测是否存在Of相关文件等。

**Comment by LTCatt** [comment]
![image](https://user-images.githubusercontent.com/40348278/213121363-7f06cb30-bfca-4dec-a2fe-39e99efd602b.png)

这是因为你的原版版本高于 OptiFine 版本，所以 PCL 会同时显示两个版本。
安装 OptiFine 1.19.3 后，原版才会被折叠。

**Comment by bruthax** [comment]
图一是已折叠
图二才是未折叠
![image](https://user-images.githubusercontent.com/86935824/213144586-e0ed3cb0-1d0d-4106-b60f-bec77c2e9452.png)
（已折叠，原版1.19.2在不常用版本）
![image](https://user-images.githubusercontent.com/86935824/213145083-72c931bb-142f-415d-8444-047c09ffd664.png)
（未折叠of1.19.2与1.19.2都在常用版本）

**Comment by bruthax** [comment]
能不能重新打开？

**Comment by bruthax** [comment]
第一张是已折叠
第二张才是未折叠
![3fe9e3c3845c98cda2bdb3741ef2830](https://user-images.githubusercontent.com/86935824/213148768-bb61ded7-5e37-4d0a-be8b-a534a125ff5d.png)
![1469136e3967efcf63c965e8d3badf5](https://user-images.githubusercontent.com/86935824/213148802-a4b5340e-0955-4b0a-85a6-12b6cd69b42a.png)

**Comment by bruthax** [comment]
蟹蟹…

**Comment by Xx114514xX1819** [comment]
又是一个反复横跳的label（

**Comment by bruthax** [comment]
对了，还有主题
我的识别码：5388-A8F0-7CCA-5095

**Comment by bruthax** [comment]
对了，还有隐藏主题
我的识别码：5388-A8F0-7CCA-5095

**Comment by LTCatt** [comment]
你的解锁码：kqBXMc8o0dO9LlL7GB7ktPp5YiWl4jHX
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
