### ISSUE TITLE
启动器显示日志初始化失败：PCL2权限不足，请尝试右键PCL2，选择以管理员身份运行

### ISSUE THREAD

**Issue by tou002** [Hex-Dragon/PCL2#957]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

补全文件出现启动器显示日志初始化失败：PCL2权限不足，请尝试右键PCL2，选择以管理员身份运行
但是我的D盘设置所有用户都有读写和写入的权限。
![image](https://user-images.githubusercontent.com/102643572/213091073-efad5a32-68f9-4b2f-a5ad-587fdb81b462.png)
![image](https://user-images.githubusercontent.com/102643572/213091113-d02e4541-153b-49d7-9755-104cd114d375.png)
![image](https://user-images.githubusercontent.com/102643572/213091136-a2f69531-6d3d-4b59-9fca-b396e40d72de.png)
![image](https://user-images.githubusercontent.com/102643572/213091148-164021bb-020d-4d41-a1ae-1b49a36cf2cf.png)
![image](https://user-images.githubusercontent.com/102643572/213091160-e99b7766-e02d-4009-801a-82920212033b.png)

### 重现步骤

点击版本设置
在点击补全文件

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10442415/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10442416/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10442417/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10442418/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10442419/Log2.txt)

**Comment by quannen** [comment]
?我的PCL也在D盘，没问题啊？大概率你的问题吧

**Comment by quannen** [comment]
你的问题不是D盘的读取，log中看出是你的用户文件夹无法读取（正常
用管理权限运行即可（不然龙猫也没办法

**Comment by quannen** [comment]
看来就是权限不足，访问被拒绝（.minecraft文件夹的读写权不是D盘的读写权，就像你没有权利删除System32但你可以访问C盘一样
用管理权限运行就行了

**Comment by LTCatt** [comment]
确实是权限不足，这个不是我能解决的……你可以自己排查权限到底哪里不对……
