### ISSUE TITLE
为每个游戏文件夹单独设置默认设置

### ISSUE THREAD

**Issue by fhh1224** [Hex-Dragon/PCL2#959]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

单独设置游戏文件夹默认设置，例如版本隔离、自动进入服务器

### 原因

有多个游戏文件夹时，每个版本要单独设置

**Comment by WForst-Breeze** [comment]
已初步确认，感谢您的反馈~
（注：反馈者意为为每个**游戏文件夹**提供默认设置

**Comment by Xx114514xX1819** [comment]
是.minecraft的那种文件夹吗

**Comment by LTCatt** [comment]
不太打算制作……
如果再在游戏文件夹添加一层的话，事情会变得非常恐怖：我们有全局设置、文件夹独立设置还有一个版本独立设置，当出现问题的时候会变得非常难排查，相比起制作这个功能的收益，这个负面效果甚至更大。
