### ISSUE TITLE
在Mod管理中右键模组点击esc会打开百科搜索，不符合操作逻辑

### ISSUE THREAD

**Issue by OnQ114514** [Hex-Dragon/PCL2#960]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

与https://github.com/Hex-Dragon/PCL2/issues/796相似

### 重现步骤

1.点击版本设置
2.点击Mod管理
3.点击详情/右键模组
4.按下esc

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10442624/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10442625/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10442626/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10442627/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10442628/Log1.txt)

**Comment by WForst-Breeze** [comment]
稳定复现，已初步确认问题存在，感谢您的反馈

**Comment by 212112111zwl** [comment]
我打开了curse……

**Comment by WorldHim** [comment]
貌似是会打开弹窗中最右边的按钮？有的 mod 右键还有 `打开官网` 按钮按 `esc` 就不会跳转到百科。
