### ISSUE TITLE
优化mod和整合包搜索布局

### ISSUE THREAD

**Issue by fhh1224** [Hex-Dragon/PCL2#961]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

1搜索mod页面和搜索整合包页面的类型和版本大小不一样
2搜索类型支持同时选择多个条件

### 原因

搜索整合包可以同时选大型整合、任务，方便搜索

**Comment by LTCatt** [comment]
`搜索mod页面和搜索整合包页面的类型和版本大小不一样` 这个可以优化
`搜索类型支持同时选择多个条件` CurseForge API 不支持，没办法

**Comment by fhh1224** [comment]
D77C-32C2-F52C-5E8B

**Comment by WForst-Breeze** [comment]
很抱歉，优化建议无法获取活跃橙
