### ISSUE TITLE
无法从官方源下载文件（报错 502 或 400）

### ISSUE THREAD

**Issue by LTCatt** [Hex-Dragon/PCL2#964]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

官方源目前已强制要求 https。

远程服务器返回错误: (502) 错误的网关。（http://resources.download.minecraft.net/14/141a6649d6cd6488409bc6c0cd31e6517dd7fd5d）

也可能报错 (400)，是相同原因引起的。

**Comment by Louis-ZYH** [comment]
由于国内 ISP 经常会错误地缓存镜像站的内容，所以我们不鼓励用户使用 HTTP 访问。
访问的安全性不靠 HTTPS 保证，提供 HTTPS 访问仅为了避免 ISP 错误缓存内容，引起各种缓存不一致的问题。
                                          ——摘选自https://mirrors.tuna.tsinghua.edu.cn/news/

**Comment by Xx114514xX1819** [comment]
第一眼：第一次发现这么高优先级的issue
第二眼：龙猫发的那没事了

**Comment by Minecrafthyr** [comment]
镜像源和官方源都挂了：
下载原版 1.19.3失败
→ 下载原版资源文件失败
→ 下载资源文件（副加载器）失败
→ 远程服务器返回错误: (400) 错误的请求。
   在 PCL.ModNet.NetFile.Thread(NetThread Info)
错误类型：System.Net.WebException

**Comment by Hatsushigure** [comment]
是的
![image](https://user-images.githubusercontent.com/65275829/213628535-447cdcad-7b86-4c40-97fc-06b5e980ad50.png)
所以现在该怎么下载呢

**Comment by WorldHim** [comment]
建议先使用 HMCL、BakaXL 等启动器代替？

**Comment by Minecrafthyr** [comment]
顺便说一句，HMCL也挂了

**Comment by Hatsushigure** [comment]
其实没挂。我在评论这个issue之后立马用了hmcl

在 2023-01-20 14:24:23，Minecrafthyr ***@***.***> 写道：


顺便说一句，HMCL也挂了

**Comment by Louis-ZYH** [comment]
> 其实没挂。我在评论这个issue之后立马用了hmcl  顺便说一句，HMCL也挂了 

> 建议先使用 Minecraft Launcher、~HMCL~、BakaXL 等启动器代替？

看来目前只能官启+VPN暂时用一阵子了……

**Comment by Louis-ZYH** [comment]
> > 其实没挂。我在评论这个issue之后立马用了hmcl  顺便说一句，HMCL也挂了
> 
> > 建议先使用 Minecraft Launcher、~HMCL~、BakaXL 等启动器代替？
> 
> 看来目前只能官启+VPN暂时用一阵子了……

官启是肯定率先跟进https的……

**Comment by quannen** [comment]
> 第一眼：第一次发现这么高优先级的issue 第二眼：龙猫发的那没事了

这里请不要灌水谢谢

**Comment by Hatsushigure** [comment]
> 其实没挂。我在评论这个issue之后立马用了hmcl

好吧，是我错了...目前HMCL上镜像源也不正常，但是官方源可以用。

**Comment by WorldHim** [comment]
PCL 使用镜像源也不能下载

**Comment by wifi-left** [comment]
> 其实没挂。我在评论这个issue之后立马用了hmcl 在 2023-01-20 14:24:23，Minecrafthyr ***@***.***> 写道： 顺便说一句，HMCL也挂了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

很抱歉，纠正一下，HMCL在 2020年已经用的 https 访问了
https://github.com/huanghongxun/HMCL/blob/214ff9de94622682f77d646b45f13f54f5639597/HMCLCore/src/main/java/org/jackhuang/hmcl/download/MojangDownloadProvider.java

**Comment by Q2297045667** [comment]
https://paste.ubuntu.com/p/zvKgWYMcFC/
我以为只有我遇到了
