### ISSUE TITLE
快照版本23w03a无法下载

### ISSUE THREAD

**Issue by DeathlyKH** [Hex-Dragon/PCL2#965]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![新建位图图像](https://user-images.githubusercontent.com/123037087/213330100-297276e2-e9cf-4be4-91e2-f612e6526ee4.png)

### 重现步骤

点击23w03a版本下载

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10452405/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10452406/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10452407/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10452408/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10452409/Log2.txt)

**Comment by bruthax** [comment]
龙猫已经发现了，详见[https://github.com/Hex-Dragon/PCL2/issues/964](url)

**Comment by bruthax** [comment]
龙猫已经发现了，详见#964

**Comment by WForst-Breeze** [comment]
#966 出现同样问题

**Comment by WForst-Breeze** [comment]
等等，我的锅，这位用的是官方源（）那就是 #964 重复，抱歉，感谢您的反馈
`
[08:54:29.003] [Download] f2487b6280c5ed387df6879d5c75b4c97a3c57c1 1507#：出错，远程服务器返回错误: (400) 错误的请求。
   在 PCL.ModNet.NetFile.Thread(NetThread Info)
错误类型：System.Net.WebException
`

**Comment by Xx114514xX1819** [comment]
反复横跳的label（

**Comment by LTCatt** [comment]
实质和 #964 是同一个问题。
