### ISSUE TITLE
无法下载 22w42a+

### ISSUE THREAD

**Issue by WorldHim** [Hex-Dragon/PCL2#967]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

已确定 PCL 无法下载 `22w42a` 及以上版本（即 `1.19.2` 以上版本），问题包含官方源与镜像源（说明是 PCL 的问题？），在 #965 #966 中也被提及。
**与** #964 **不同**，返回错误为 `404`（见 #965 #966）或 `400`（见本 issue 日志）。

### 重现步骤

下载 `22w42a` 及以上版本。

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10452969/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10452970/Log2.txt)

**Comment by Super-XiaoNian** [comment]
有人反馈过这个问题了(

**Comment by WorldHim** [comment]
> 有人反馈过这个问题了(

遇到的不一样

**Comment by WForst-Breeze** [comment]
> 所以我才提及了这两个 issue，这算是个总结（？，且遇到的问题不一样。

应该不用总结其实我个人认为（）

**Comment by WorldHim** [comment]
> > 所以我才提及了这两个 issue，这算是个总结（？，且遇到的问题不一样。
> 
> 应该不用总结其实我个人认为（）

但是我用的官方源，而且返回错误不同。

**Comment by niuyuhao0818** [comment]
so，为啥我能下？

**Comment by WorldHim** [comment]
> so，为啥我能下？

你好歹截个图啊 =。=

**Comment by niuyuhao0818** [comment]
> > so，为啥我能下？
> 
> 你好歹截个图啊 =。=

![image](https://user-images.githubusercontent.com/87165365/213396818-e79fefa5-2b7c-4da1-a713-34bba2eb35da.png)

**Comment by WorldHim** [comment]
> > > so，为啥我能下？
> > 
> > 
> > 你好歹截个图啊 =。=
> 
> ![image](https://user-images.githubusercontent.com/87165365/213396818-e79fefa5-2b7c-4da1-a713-34bba2eb35da.png)

你截一张还没下载完的图有什么用 =。=

**Comment by LTCatt** [comment]
实质和 #964 是同一个问题。
