### ISSUE TITLE
获取 PCL2 服务器状态失败：此实现不是 Windows 平台 FIPS 验证的加密算法的一部分

### ISSUE THREAD

**Issue by Louis-ZYH** [Hex-Dragon/PCL2#969]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如图：
![image](https://user-images.githubusercontent.com/115140320/213382990-6335a6b4-a789-4b36-b559-b534ec8d6f06.png)
已确认Windows Defender和其他杀毒软件均关闭，且校准了系统时间，但仍然报错，完全无法正常检查更新。
此外，本PCL2所有文件均处于一个32+16+16GB的单磁盘跨区卷分区中。
Windows磁盘管理图：
![image](https://user-images.githubusercontent.com/115140320/213384277-c4bb71c9-98e7-492f-8600-cd96cdcd0a4d.png)
DiskGenius v5.4.6.1441图：
![image](https://user-images.githubusercontent.com/115140320/213384742-8d58a48b-95b8-431b-a220-9af5d051b60a.png)

### 重现步骤

1、打开PCL2；
2、打开“设置”——“启动器”，点击“检查更新”，报错。

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10454520/Log1.txt)

**Comment by youzi-2333** [comment]
我也是 Release 2.4.4，复现不出，在日志里面找到以下内容：
```
[15:32:35.252] 获取 PCL2 服务器状态失败：此实现不是 Windows 平台 FIPS 验证的加密算法的一部分。
   在 PCL.ModNet.NetGetCodeByRequestRetry(String Url, Encoding Encode, String Accept, Boolean IsJson, String BackupUrl)
   在 PCL.ModMain.ServerSubReal()
错误类型：System.InvalidOperationException
```
网上说是注册表配置问题，把`HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa\FipsAlgorithmPolicy`项下的 Enabled 值设为 0 即可，**而且我在将其改为 1 时成功复现！**

**Comment by WorldHim** [comment]
> 我也是 Release 2.4.4，复现不出，在日志里面找到以下内容：
> 
> ```
> [15:32:35.252] 获取 PCL2 服务器状态失败：此实现不是 Windows 平台 FIPS 验证的加密算法的一部分。
>    在 PCL.ModNet.NetGetCodeByRequestRetry(String Url, Encoding Encode, String Accept, Boolean IsJson, String BackupUrl)
>    在 PCL.ModMain.ServerSubReal()
> 错误类型：System.InvalidOperationException
> ```
> 
> 网上说是注册表配置问题，把`HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa\FipsAlgorithmPolicy`项下的 Enabled 值设为 0 即可，**而且我在将其改为 1 时成功复现！**

如果是注册表的问题那么普通用户应该不会出现这个 bug（？

**Comment by youzi-2333** [comment]
确实，我重装了系统也没这个问题，默认值就是 0 吧，~~可能他装的是盗版系统~~

**Comment by Louis-ZYH** [comment]
> 确实，我重装了系统也没这个问题，默认值就是 0 吧，~可能他装的是盗版系统~

回上面的，我用的是Win10 20H2的精简版，换了个WiFi后就出问题了.

**Comment by z0z0r4** [comment]
从PCL2服务器拉取数据时，sign鉴权错误，以及其他原因，似乎都被认为是时间校准问题23333

**Comment by z0z0r4** [comment]
> 从PCL2服务器拉取数据时，sign鉴权错误，以及其他原因，似乎都被认为是时间校准问题23333

这个try except范围有点大

**Comment by Louis-ZYH** [comment]
> 从PCL2服务器拉取数据时，sign鉴权错误，以及其他原因，似乎都被认为是时间校准问题23333

那应该还顺带修改一下提示信息，与#[904]号提案中龙猫最后的处理方式类似=。=

**Comment by z0z0r4** [comment]
> 

不应该，因为能触发鉴权失败的那是违规操作（老实

**Comment by youzi-2333** [comment]
所以按照我的方法可以修好吗……



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年01月21日 16:16 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Hex-Dragon/PCL2] 获取 PCL2 服务器状态失败：此实现不是 Windows 平台 FIPS 验证的加密算法的一部分 (Issue #969) |

不应该，因为能触发鉴权失败的那是违规操作（老实

**Comment by Louis-ZYH** [comment]
> 所以按照我的方法可以修好吗……

已经修好了，谢谢！
