### ISSUE TITLE
[优化] Minecraft 版本安装时，在版本选择页面中提示“正在安装”而不是正常版本

### ISSUE THREAD

**Issue by youzi-2333** [Hex-Dragon/PCL2#973]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

安装 Minecraft 版本时，打开版本选择页面，此时可以选中该版本（甚至启动游戏），就会出现各种奇奇怪怪的 Bug……
如果安装了 Mod 加载器或 Optifine，还会错误的提示该版本为原版。
因此可以在版本安装时，将版本分类到另一个“正在安装”的分区，且无法选定。（当然也可以直接隐藏）

### 原因

这项优化可以让 Minecraft 在安装时不被启动。
如果没有这项优化，就会感觉很奇怪……而且会出现意料之外的 Bug……

**Comment by WorldHim** [comment]
这个应该是因为在安装时 PCL 是先安装原版，然后再用对应的 `Optifine` 或 `Mod 加载器` 对其进行修改。在安装完原版时，PCL 就会将其误识别为原版。~~所以扯了这么多~~已初步确认，谢谢您的反馈。

**Comment by LTCatt** [comment]
……算了，有点难整
