### ISSUE TITLE
综合优化

### ISSUE THREAD

**Issue by jiuxiao6** [Hex-Dragon/PCL2#976]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

以下均为个人意见
1.将快照版与普通版启动器的界面动画统一，建议统一为放大式动画，使用体验个人感觉很好
2.整体界面进行改动，增加一些创意性按钮，建议增加最大化按钮
3.希望自定义背景可以放动态背景
4.希望多增加一些启动器隐藏皮肤
5.希望增加启动器等级系统，升级方式列如启动一次游戏增加5经验值，并且为指定等级添加一些启动器皮肤或者称号
6.期待增加按钮点击音效和特效，最好可以自定义
7.最好增加一键修复整合包文件按钮，部分在诅咒锻造中下载的整合包拖到启动器无法正常使用

### 原因

没有原因

**Comment by Louis-ZYH** [comment]
emmm……有多个建议时，请单独发issue，不要把多个提案挤在同一个issue里，谢谢！

**Comment by z0z0r4** [comment]
您的提议里面几乎全是极其低优先级的…
UI改动和新主题显然只有在龙猫真的闲到要咬打火机的时候才会被提上日程

**Comment by z0z0r4** [comment]
从 Curseforge 下载整合包无法使用是整合包本身的问题吧…

**Comment by quannen** [comment]
这些基本都不会做了.....关了吧

**Comment by 212112111zwl** [comment]
动态背景其实我也挺想要的，但是楼上说了，优先级低没办法。
像这种UI相关的一般……除非很多人需要，否则没啥希望（哭

**Comment by 212112111zwl** [comment]
很难想象最大化的pcl是什么样子的

**Comment by WorldHim** [comment]
1. 同 #970，拒绝。
2. 描述不清，`创意性按钮` 具体指什么；最大化好像有人提到过，我记得是被拒绝了，大概率不会通过。
3. ~~同~~类似 #862，大概率被拒绝。
> 龙猫对 #862 的评论：太超出启动器的范围了，抱歉（
4. ~~这是闲到什么程度才会做的提案~~现在还有这么多 issue 是 [处理中](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+is%3Aopen+label%3A%E5%A4%84%E7%90%86%E4%B8%AD) 或 [暂缓处理](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+is%3Aopen+label%3A%E6%9A%82%E7%BC%93%E5%A4%84%E7%90%86)，大概率不会通过。
5. ~~这真的不是网易版，真的不是~~太超出启动器的范围了，大概率不会通过。
6. 音效可能有，但是自定义功能大概率不会通过。
7. 大概率为本人网络问题或是 Curseforge 的问题，建议交 bug 反馈。

**Comment by WForst-Breeze** [comment]
### 请注意：一个 issue 请只提及一条反馈，否则处理会很麻烦，谢谢配合~
1. 同上
2. 重复反馈，#876 已被拒绝
3. 同上
4. 之前已经宣布了，会重新制作隐藏主题，请耐心等待
5. 同上
6. 类似功能曾在金数据中被提及（下载完成时添加提示音），但目前仍未处理，如果您想要的话可以去新交一个 issue
7. 与 PCL2 无关，如有需要可以前往 Discussions 或相关论坛寻求帮助

---
> 期待增加按钮点击音效和特效，最好可以自定义

仅针对第六条初步确认，感谢您的反馈~

**Comment by LTCatt** [comment]
针对第七条，可以单独重发一个 Bug 反馈，其他的拒绝，抱歉 =。=
