### ISSUE TITLE
mod列表异常

### ISSUE THREAD

**Issue by tangpoya** [Hex-Dragon/PCL2#977]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

打开mod列表时用鼠标调节PCL2窗口大小时出现异常，不知道怎么形容，录了视频。重启PCL2无效。
视频地址：https://www.aliyundrive.com/s/QTVj3fq2LGj
或者：https://pan.baidu.com/s/1U3i3faJ7NnjDb-Kw6LMK2A?pwd=klqd

系统：Windows 11 专业工作站版 22H2

### 重现步骤

1.打开mod列表
2.用鼠标调节PCL2窗口大小

### 日志与附件

[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10466198/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10466199/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10466200/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10466201/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10466202/Log3.txt)

**Comment by WForst-Breeze** [comment]
稳定复现，不过我更倾向于这是一个优化建议（）已初步确认，感谢您的反馈~
