### ISSUE TITLE
java兼容性警告问题

### ISSUE THREAD

**Issue by MotWnb** [Hex-Dragon/PCL2#978]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

自动选择java时仍提示强制使用了java8
![新建位图图像](https://user-images.githubusercontent.com/98505614/213830976-e93403b3-2cad-4df1-80fc-2c2f87e7d442.jpg)
![新建位图图像 (2)](https://user-images.githubusercontent.com/98505614/213830985-1c09e181-367b-4184-a513-43316f29c863.jpg)

### 重现步骤

1、启动游戏

### 日志与附件

不会在启动文件中，但是还是上传一下吧
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10471226/Log2.txt)

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10471225/Log1.txt)

[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10471223/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10471224/Log5.txt)

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10471222/Log3.txt)

**Comment by WorldHim** [comment]
~~这个是自动选择 Java 功能的锅~~ `1.8.9` 确实要用 Java 8，已初步确认，谢谢您的反馈。

**Comment by LTCatt** [comment]
和 #907 重复
