### ISSUE TITLE
链接到正版服务器失败

### ISSUE THREAD

**Issue by ArtistC220** [Hex-Dragon/PCL2#979]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

无法正常更换皮肤，无法正常链接正版验证服务器，在单人游戏中只显示steve的默认皮肤
在pcl群友的排查下，网络没有问题，官方启动器，官方网站可以正常使用，挂加速器没有作用，不是防火墙问题，不是运营商问题，重装pcl无法解决，群友建议直接反馈到github上

### 重现步骤

刷新头像与更换皮肤，会显示
获取正版皮肤失败（Artist_C）:链接服务器超时，已接收0B
获取微软正版皮肤失败（Artist_C）:远程服务器返回错误（403）已禁止。直接下载文件失败

加入服务器显示
无法登录到正版验证服务器
连接中止

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10471470/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10471471/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10471472/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10471473/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10471474/Log2.txt)

**Comment by LTCatt** [comment]
提到了 `在单人游戏中只显示steve的默认皮肤` ，这实际上代表着 MC 也无法下载你的皮肤：PCL 只会向 MC 传递 UUID，然后 MC 会自行下载皮肤。
既然 MC 本体都出现了网络问题，这不应是 PCL 的 Bug，我也无能为力……
