### ISSUE TITLE
MC 崩溃（Failed to locate library: lwjgl.dll）

### ISSUE THREAD

**Issue by kunkunhaoshuai** [Hex-Dragon/PCL2#980]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃不是 PCL2 的原因，请 **不要** 提交反馈。你可以在 QQ 群里或者论坛找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是游戏本身的问题，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

有时候甚至是刚下载都启动不了 用的是离线模式

### 错误报告、日志与附件

[错误报告-2023-1-21_12.13.43.zip](https://github.com/Hex-Dragon/PCL2/files/10471476/-2023-1-21_12.13.43.zip)
[错误报告-2023-1-21_12.14.01.zip](https://github.com/Hex-Dragon/PCL2/files/10471477/-2023-1-21_12.14.01.zip)

**Comment by WorldHim** [comment]
使用原版不加of的换英文路径试试？

**Comment by LTCatt** [comment]
疑似是中文路径导致 Java 无法定位到 dll……
使用其他启动器可以启动吗？
在命令提示符中输入 `chcp`，看看活动代码页是不是 936？
![image](https://user-images.githubusercontent.com/40348278/213885226-a6303efe-92bb-4ec4-8f7d-1b082bb82b08.png)

**Comment by miner233** [comment]
应该是中文路径的问题，请 **确保 Minecraft 路径全英文** 后重试。

**Comment by kunkunhaoshuai** [comment]
也启动不了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月22日(周日) 凌晨4:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Hex-Dragon/PCL2] MC 崩溃（Failed to locate library: lwjgl.dll） (Issue #980)




 
疑似是中文路径导致 Java 无法定位到 dll……
 使用其他启动器可以启动吗？
 在命令提示符中输入 chcp，看看活动代码页是不是 936？

**Comment by LTCatt** [comment]
![image](https://user-images.githubusercontent.com/40348278/215569212-7e2dcadf-de7a-409b-b174-3a3115ebd502.png)

**Comment by ZHAOSBC** [comment]
emmm,你的电脑CPU是什么，jvm并没有识别出来，不会是骁龙8cx之类的ARM架构的U吧（

**Comment by kunkunhaoshuai** [comment]
Intel core i5 7200U



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月31日(周二) 下午3:42
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Hex-Dragon/PCL2] MC 崩溃（Failed to locate library: lwjgl.dll） (Issue #980)




 
emmm,你的电脑CPU是什么，jvm并没有识别出来，不会是骁龙8cx之类的ARM架构的U吧（

**Comment by ZHAOSBC** [comment]
安装java11再试试？

**Comment by kunkunhaoshuai** [comment]
有什么区别吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月31日(周二) 下午3:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Hex-Dragon/PCL2] MC 崩溃（Failed to locate library: lwjgl.dll） (Issue #980)




 
安装java11再试试？

**Comment by ZHAOSBC** [comment]
看看是不是java的原因，因为你使用的是2019年发布的java

**Comment by WForst-Breeze** [comment]
请反馈者尽快完成信息补充，否则此反馈将会被超时关闭🙁

**Comment by LTCatt** [comment]
超时关闭，若有需要可以继续回复
