### ISSUE TITLE
建立一个Discord群聊

### ISSUE THREAD

**Issue by Kauo7420** [Hex-Dragon/PCL2#981]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

目前，HMCL、BakaXL都在Discord上建立了社区，PCL同样可以仿照他们的途径去建立一个Disocrd社区

### 原因

这对没有QQ账号的人很友好，并且Discord管理起来更加方便，而且可以把他当主社区（比如用来下载启动器，用来提交错误报告日志）

**Comment by Big-Cake-jpg** [comment]
Discord 在国内的连通性很差，因此该 Issue 可能不会被处理直接关闭。

**Comment by wxjzx682** [comment]
可能性很低，因为国内很少有人用discord作为主要交流，而且QQ用的人已经够多了（）

**Comment by bwtx2023** [comment]
我的评价是，不如KOOK
