### ISSUE TITLE
pcl wont launch

### ISSUE THREAD

**Issue by floro677** [Hex-Dragon/PCL2#982]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

well it just dont launch as i double click on it

### 重现步骤

1、点击pcl launcher icon 

### 日志与附件

[15:47:34.077] [Start] 程序版本：Release 2.4.4（272）
[15:47:34.079] [Start] 识别码：550C-E189-2902-9BB1
[15:47:34.079] [Start] 程序路径：C:\Users\steve\OneDrive\桌面\Plain Craft Launcher 2.exe
[15:47:34.082] [Start] 第一阶段加载用时：46 ms
[15:47:34.168] [Loader] 加载器 Minecraft Folder List 状态改变：Loading
[15:47:34.168] [Start] 第二阶段加载用时：94 ms
[15:47:34.187] [Loader] 加载器 Minecraft Folder List 状态改变：Finished
[15:47:34.294] [Start] 加载 DLL：Json
[15:47:34.294] [System] 获取资源：Json
[15:47:34.359] [Java] 缓存中有 2 个可用的 Java
[15:47:34.464] [System] 诊断信息：
操作系统：Microsoft Windows 11 家庭版
剩余内存：10349 M / 16167 M
DPI：168（175%）
MC 文件夹：Nothing
文件位置：C:\Users\steve\OneDrive\桌面\
[15:47:34.466] 程序出现未知错误：“103942857142857”不是此属性的有效值。有效值在 Int32.MinValue 和 Int32.MaxValue 之间。
   在 System.Windows.Window.ValidateLengthForHeightWidth(Double l)
   在 System.Windows.Window.OnWidthChanged(Double width)
   在 System.Windows.Window._OnWidthChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   在 System.Windows.PropertyChangedCallback.Invoke(DependencyObject d, DependencyPropertyChangedEventArgs e)
   在 System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   在 System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   在 System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   在 System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   在 System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   在 System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   在 PCL.FormMain.FormMain_Loaded(Object sender, RoutedEventArgs e)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   在 System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   在 MS.Internal.LoadedOrUnloadedOperation.DoWork()
   在 System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   在 System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   在 System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   在 System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   在 System.Windows.Interop.HwndTarget.OnResize()
   在 System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   在 System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
错误类型：System.ArgumentException
[15:47:35.383] [System] 诊断信息：
操作系统：Microsoft Windows 11 家庭版
剩余内存：10440 M / 16167 M
DPI：168（175%）
MC 文件夹：Nothing
文件位置：C:\Users\steve\OneDrive\桌面\
[15:47:35.383] [System] 执行外部命令：explorer.exe "C:\Users\steve\OneDrive\桌面\PCL\"
[15:47:35.433] [System] 正在打开网页：https://github.com/Hex-Dragon/PCL2/issues/
[15:47:35.579] [System] PCL 已崩溃：
程序出现未知错误：“103942857142857”不是此属性的有效值。有效值在 Int32.MinValue 和 Int32.MaxValue 之间。
   在 PCL.FormMain.FormMain_Loaded(Object sender, RoutedEventArgs e)
错误类型：System.ArgumentException
[15:47:35.593] [System] 诊断信息：
操作系统：Microsoft Windows 11 家庭版
剩余内存：10429 M / 16167 M
DPI：168（175%）
MC 文件夹：Nothing
文件位置：C:\Users\steve\OneDrive\桌面\
[15:47:35.593] 请在 https://jinshuju.net/f/rP4b6E?x_field_1=crash 提交错误报告，以便于作者解决此问题！
[15:47:35.593] [System] 执行外部命令：C:\Users\steve\OneDrive\桌面\PCL\Log1.txt 
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10472372/Log1.txt)

**Comment by LTCatt** [comment]
在注册表中找一下 `HKEY_CURRENT_USER\SOFTWARE\PCL\WindowWidth` ，看看这个值是多少？

**Comment by floro677** [comment]
it says 1039.42857142857

**Comment by floro677** [comment]
好了，自己琢磨了一下，把那项删了结果就好了
龙猫新年快乐（doge
