### ISSUE TITLE
Java排序

### ISSUE THREAD

**Issue by quannen** [Hex-Dragon/PCL2#984]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

希望可以把Jvav列表里的Java按照版本进行排序

### 原因

我的Java装在了不同的磁盘中，如果按照磁盘进行排序会出现两个8夹一个17的现象，（丑

**Comment by LTCatt** [comment]
目前排序是按照对 MC 的兼容性排的，不是按照磁盘排序。
具体的优先次序：
![image](https://user-images.githubusercontent.com/40348278/214064809-1bae4e16-19e9-4be8-8854-9542e2c377d6.png)

**Comment by quannen** [comment]
？到底是忽略还是完成？？？

**Comment by WorldHim** [comment]
> ？到底是忽略还是完成？？？

忽略
