### ISSUE TITLE
模组禁用启用列表 有没有记录在某个文件上 我比较好查看

### ISSUE THREAD

**Issue by KGOne-666** [Hex-Dragon/PCL2#986]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

模组禁用启用列表 有没有记录在某个文件上 我比较好查看

### 原因

模组禁用启用列表 有没有记录在某个文件上 我比较好查看

**Comment by quannen** [comment]
？没看懂？在mod管理界面不好看？好像没有记录

**Comment by WorldHim** [comment]
有写在 log 文件里面，但是没有单独的文件记录。PCL 在每次打开 `mod管理` 时应该都会检查一遍，将后缀为 `.jar` 的标记为启用，将后缀为 `.disabled` 的标记为禁用。

**Comment by WorldHim** [comment]
请问是建议添加这个功能吗？

**Comment by quannen** [comment]
> 请问是建议添加这个功能吗？

不管他，先换个lable（大概率是不会加了，mod管理里面可以很清楚的看到

**Comment by Xx114514xX1819** [comment]
提问建议去discussions

**Comment by KGOne-666** [comment]
> > 请问是建议添加这个功能吗？
> 
> 不管他，先换个lable（大概率是不会加了，mod管理里面可以很清楚的看到

 太多模组了 我想帮别人测试一下我禁用了什么模组 启用了什么模组 你懂不懂啊 有个名单比较好测试啊

**Comment by KGOne-666** [comment]
> 请问是建议添加这个功能吗？

也不是建议你想加就加 不想加就算了 只是比较好测试一下模组 有禁用的和启用模组列表 那就更方便了

**Comment by KGOne-666** [comment]
> 请问是建议添加这个功能吗？

 100多个模组 我截图都截不过来  模组更多的话就更麻烦了 有这个列表就比较好用一点

**Comment by KGOne-666** [comment]
> ？没看懂？在mod管理界面不好看？好像没有记录

主要我今天帮别人看模组冲突的时候禁用了什么模组比较难看一点 就是想转发给别人啊 只能用图片 要是用记录了模组禁用和启用mod的文字的话（直接复制粘贴 ）就更方便一点

**Comment by KGOne-666** [comment]
> 提问建议去discussions

我刚来的 我都不知道去哪里问 手机很不方便 
有管理员的话 帮我换个标签就好了

**Comment by KGOne-666** [comment]
我试用了很多个启动器 
这个是我认为是最好用的

**Comment by z0z0r4** [comment]
大意：将mod启用信息以文件的方式保存以方便分查阅而非通过截图

**Comment by WorldHim** [comment]
已初步确认，谢谢您的反馈。

**Comment by LTCatt** [comment]
直接查看 mod 文件夹，禁用的 mod 是 .jar.disabled 文件后缀
如果需要列表的话自己写个小程序就行……

**Comment by bwtx2023** [comment]
下次不要把内容删掉...
