### ISSUE TITLE
模组下载界面将1.19.3模组显示为“1.20快照”

### ISSUE THREAD

**Issue by xiaoyan2007** [Hex-Dragon/PCL2#987]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如题

### 重现步骤

找一个已经更新1.19.3的mod并进入

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10474290/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10474291/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10474292/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10474293/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10474294/Log2.txt)

**Comment by quannen** [comment]
进入mod指的是啥？在游戏中装mod并进入游戏？

**Comment by z0z0r4** [comment]
建议提供一张截图

**Comment by WorldHim** [comment]
没有复现。是所有还是具体某个 mod？并请给出截图。
还有，有没有可能是 curseforge 的 api 问题？

**Comment by ZS2147483647** [comment]
mod menu是1.20,其他的没看到

**Comment by z0z0r4** [comment]
> mod menu是1.20,其他的没看到

请提供截图…

**Comment by xiaoyan2007** [comment]
![QQ截图20230123143204](https://user-images.githubusercontent.com/123301358/213978445-2653b811-5700-41b7-93a7-db8635f99f72.png)

**Comment by Louis-ZYH** [comment]
你指的是这个？
![image](https://user-images.githubusercontent.com/115140320/213978962-c4f9d7b6-d222-45aa-a653-2caead305973.png)

**Comment by Louis-ZYH** [comment]
好像这这个版本的Mod Menu本身就兼容1.20快照和1.19.3，所以两个MC版本展示的是同一个诶

**Comment by WorldHim** [comment]
`Mod Menu` 确实支持 `1.20 快照`（即 `23w03a`）。

**Comment by xiaoyan2007** [comment]
23w03a是1.19.4快照

**Comment by WorldHim** [comment]
额，但是这真的不是 PCL 的问题，你可以看 [Curseforge](https://www.curseforge.com/minecraft/mc-mods/modmenu/files) 上确实写的是 `1.20`。
![image](https://user-images.githubusercontent.com/68632311/214049894-611781f5-3032-4e3c-82eb-35e3d1f5e9b5.png)
