### ISSUE TITLE
在缺少 Java 时自动下载所需的 Java

### ISSUE THREAD

**Issue by bwtx2023** [Hex-Dragon/PCL2#99]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

由于 PCL2 至今还未实现自动 Java 下载，因此可以使用 Mojang 官方的 Java 下载。

### 原因

可以省去打开网页的步骤，调用 PCL2 自带的多线程下载引擎下载安装包。

---

下列一些非官方的 Java，基于 #99 的讨论暂时不考虑使用。

附链接：

Java 8u312 32bit：https://cdn.azul.com/zulu/bin/zulu8.64.0.15-ca-jre8.0.342-win_i686.msi
Java 8u312 64bit：https://cdn.azul.com/zulu/bin/zulu8.64.0.15-ca-jre8.0.342-win_x64.msi
Java 17 32bit：https://cdn.azul.com/zulu/bin/zulu17.36.15-ca-jre17.0.4-win_i686.msi
Java 17 64bit：https://cdn.azul.com/zulu/bin/zulu17.36.13-ca-jre17.0.4-win_x64.msi

需要注意的是，Zulu OpenJDK 疑似不能在 Windows 7 上使用，因此可以尝试使用来自 Bellsoft 的 Liberica OpenJDK 直链下载。

附链接：

Java 8u312 32bit：https://download.bell-sw.com/java/8u312+7/bellsoft-jre8u312+7-windows-i586.msi
Java 8u312 64bit：https://download.bell-sw.com/java/8u312+7/bellsoft-jre8u312+7-windows-amd64.msi
Java 17 32bit：https://download.bell-sw.com/java/17.0.4+8/bellsoft-jre17.0.4+8-windows-i586.msi
Java 17 64bit：https://download.bell-sw.com/java/17.0.4+8/bellsoft-jre17.0.4+8-windows-amd64.msi

**Comment by LTCatt** [comment]
Mojang 官方提供了 Java 下载，你给的 OpenJDK 相对官方的 Java 有啥额外好处么……
如果没啥明显区别的话，就改成自动下载官方提供的 Java，然后我就丢新功能投票去了 =。=

**Comment by Yummy-Cookie-S** [comment]
> 

OpenJDK  的效率高一些，是一个优化
参考 https://www.mcbbs.net/forum.php?mod=viewthread&tid=1232993
不过 OpenJDK 的种类就多了去了，对于需要用启动器下载 Java 的用户使用官方 Java 足矣

**Comment by bwtx2022** [comment]
> Mojang 官方提供了 Java 下载，你给的 OpenJDK 相对官方的 Java 有啥额外好处么……
> 
> 如果没啥明显区别的话，就改成自动下载官方提供的 Java，然后我就丢新功能投票去了 =。=

Zulu JDK 相比官方提供的性能更优，至于 Liberica JDK ，效率稍逊于 Zulu

**Comment by LTCatt** [comment]
……不过我们没有明确结论确保非官方 JDK 能有和官方一致的稳定性吧。
换句话说，虽然有可能的性能提升，但我们不确定会不会因为换了就导致某些版本启动失败。
所以我还是倾向于下载 Mojang 官方提供的 JDK……（如果要做的话
