### ISSUE TITLE
等价交换升级未含有1.16和1.12

### ISSUE THREAD

**Issue by luoyuqi11** [Hex-Dragon/PCL2#990]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

等价交换升级含有1.12.2和1.16.5，但是PCL2mod下载器里并未含有

### 重现步骤

1、点击xxxx
2、往下滚，然后点击xxxx
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10477404/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10477405/Log5.txt)
[Log.txt](https://github.com/Hex-Dragon/PCL2/files/10477406/Log.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10477407/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10477412/Log2.txt)
在mod搜索框里搜索等价交换升级，里面只有1.18.2，并未含有1.16和1.12

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10477403/Log3.txt)

**Comment by WorldHim** [comment]
低版本:[FTB ProjectEX](https://www.curseforge.com/minecraft/mc-mods/projectex)
高版本:[ExtendedExchange](https://www.curseforge.com/minecraft/mc-mods/extendedexchange)
