### ISSUE TITLE
游戏安装失败 Caused By: 下载 Forge 40.2.0失败

### ISSUE THREAD

**Issue by toby3939** [Hex-Dragon/PCL2#991]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

下载所有整合包的时候 都会出现Forge下载失败

### 重现步骤

1、点击下载
2、然后下载整合包开始下载

### 日志与附件

游戏安装失败
Caused By: 下载 Forge 40.2.0失败
Caused By: 安装 Mod 加载器（方式 A）失败
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10478611/Log1.txt)

Caused By: 安装新 Forge 版本失败
Caused By: Forge 安装器出错，末行为 false
   在 PCL.ModDownloadLib._Closure$__33-0._Lambda$__4(LoaderTask`2 Task)
   在 PCL.ModLoader.LoaderTask`2._Closure$__12-0._Lambda$__0()
   在 PCL.ModDownloadLib.ForgeInjector(String Target, LoaderTask`2 Task, String McFolder)
   在 PCL.ModDownloadLib._Closure$__33-0._Lambda$__4(LoaderTask`2 Task)

**Comment by quannen** [comment]
与[#575](#575 ) 重复

**Comment by youzi-2333** [comment]
um，是不是应该挂在重复上面（关issue的时候机器人自动挂了忽略）
