### ISSUE TITLE
下载mod时初步检查是否和已有mod冲突

### ISSUE THREAD

**Issue by IF-desu** [Hex-Dragon/PCL2#994]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

下载完fabricmod后自动检测包内fabric.mod.json内"break"后和本mod冲突的mod并检测当前版本有无break列表中的mod
如果有的话PCL会提示下载的mod和xxx冲突，请去除冲突的mod及其附属mod
(forge??不知道)
如果是mod本身class等冲突就不能用这个方法了，所以才叫“初步检查”

### 原因

（示例）
我需要这个功能来在下载mod时候就解决一部分mod冲突。很多人都不会看Log，写在break里面的mod冲突都看不出来，最常见的是有人把sodium和optifabric，optifine装在一起还傻傻地跑去问

**Comment by Big-Cake-jpg** [comment]
然而这种做法只对 Fabric 模组有效，Forge 模组没有包含有效的模组冲突信息。

**Comment by IF-desu** [comment]
lol

**Comment by ZS2147483647** [comment]
但确实类似的功能可以考虑,有的人不会配mod还装了几百个,游戏崩了去问,200+mod谁能给他捋的明白

**Comment by LTCatt** [comment]
没有有效的 Mod 冲突信息来源 —— Mod 作者自己都不会写它和哪些 Mod 冲突了。根本没法检查。
