### ISSUE TITLE
在多次快速进行启动再结束游戏后，出现了没有找到Java的窗口（加载线程 分析缺失资源文件 (110) 已中断但线程正常运行至结束，输出被弃用（最新线程：-1））

### ISSUE THREAD

**Issue by return6666** [Hex-Dragon/PCL2#996]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

多次进行启动游戏再快速取消后，出现了未找到Java的窗口，并出现了Java8蓝奏云的下载窗口
对不起，刚刚文件不知道为什么没有传上去
实在抱歉
我是在启动时点取消发现的

### 重现步骤

1.点击启动游戏
2.然后快速点击取消

### 日志与附件

https://wwqj.lanzoum.com/iWyvF0lqdila
刚刚不知道为什么传不上去，挂蓝奏云上了

**Comment by LTCatt** [comment]
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10487102/Log1.txt)
