### ISSUE TITLE
在点击刷新时进行自动跳转

### ISSUE THREAD

**Issue by Roser7419** [Hex-Dragon/PCL2#997]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

例如在下载页面中的自动安装、CurseForge中的Mod与整合包选项卡边都有一个刷新按钮，现行版本中在点击另一个选项卡的刷新时并不会跳转到该页面（刷新倒是确实会刷新）。可以修改为在点击了刷新时自动调转到被刷新的页面。

### 原因

这项优化可以让我更方便地进行资源下载，刷新应该就是为了刷新页面找最新资源吧（
若不需要进行刷新可以直接点击进入，需要刷新该页面即可通过直接点击该按钮进行刷新与跳转，而不需要进行两步操作

**Comment by 212112111zwl** [comment]
同意，上述更合理
